### ISSUE TITLE
List of contacts missing on country page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#100]
**List of contacts missing on country page**

I expect to find a contacts list on the country page.

Compare this to the current portal page, e.g. http://www.gbif.org/country/PH/participation

Note some contact information is supplied in the network page dialog.

-----
fbitem-648c3607b25337e2bdd5b0985f80a22977bdfa17
Reported by: @kbraak
System: Firefox 51.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/country/PH
Window size: width 1565 - height 940
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-27T13:08:04.720Z',mode:absolute,to:'2017-02-27T13:14:04.720Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-27T13:08:04.720Z',mode:absolute,to:'2017-02-27T13:14:04.720Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
participant page was not implemented at all. country pages is still under development. but contacts is there. If you still find that they are wrong the please create an issue on the portal project.
