### ISSUE TITLE
Dataset tab for programme pages?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1017]
**Dataset tab for programme pages?**

I think we've discussed this casually, but would it be possible to automate the aggregation of all BID-related datasets on a single-tab view (possibly simply a search result: dataset has projectID=BID-/foo/?)? If we gave the same instruction to other project grantees, this model could be extended to BIFA, CESP and any other relevant (or future) programmes. 

This would be an impressive display, even at this point, and provide one more reward for publishers who make use of the projectID as instructed. 

Related open issues include:
+ [#245](https://github.com/gbif/portal-feedback/issues/245)
+ [#719](https://github.com/gbif/portal-feedback/issues/719)
+ [#738](https://github.com/gbif/portal-feedback/issues/738)
+ [#779](https://github.com/gbif/portal-feedback/issues/779)

-----
fbitem-96e5f76b02601e2c8d89c30a693a069681a61b92
User provided contact info: @kcopas
System: Safari 11.0.3 / Mac OS X 10.13.3
Referer: https://www.gbif.org/programme/82243/bid-biodiversity-information-for-development
Window size: width 1237 - height 793
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-05T13:35:35.062Z',mode:absolute,to:'2018-02-05T13:41:35.062Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-05T13:35:35.062Z',mode:absolute,to:'2018-02-05T13:41:35.062Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
Currently there is nothing in the API that lets us do so. But the dataset APi could be extended to support it. We could even be using the keywords as we do for the invasive species checklists, but I'm not convinced we want to go down that route. Better fix machine tags or add a new field.

labelling as API issue

**Comment by MortenHofft** [comment]
I'm closing in favour of above - since this is really mostly an registry API request
