### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1018]
**Incorrect link**

The "Prepare data for publication" section includes the wrong link for "sampling-event datasets" - it links to the occurrence dataset information

-----
fbitem-85d0d47031d5c4dacde8bc9884e35afcbf08383e
User provided contact info: dhobern@gbif.org
System: Chrome 63.0.3239 / Windows 10 0.0.0
Referer: https://www.gbif.org/publishing-data
Window size: width 1536 - height 734
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-06T10:53:27.384Z',mode:absolute,to:'2018-02-06T10:59:27.384Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-06T10:53:27.384Z',mode:absolute,to:'2018-02-06T10:59:27.384Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by kcopas** [comment]
Link corrected
