### ISSUE TITLE
Latlong not correct

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1019]
**Latlong not correct**

Coordinates for Catalog number	13109 (Tropidonophis doriae) are not correct: locality is Sentani GHQ, on Lake Sentani near Jayapura, on the N coast of Irian Jaya near PNG, but coordinates map to S Sulawesi

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
User provided contact info: turner@casema.nl
System: Safari 11.0.3 / Mac OS X 10.13.3
Referer: https://www.gbif.org/
Window size: width 830 - height 692
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-06T21:11:12.061Z',mode:absolute,to:'2018-02-06T21:17:12.061Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-06T21:11:12.061Z',mode:absolute,to:'2018-02-06T21:17:12.061Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ahahn-gbif** [comment]
This issue appears to be fixed (https://www.gbif.org/occurrence/543720032)
