### ISSUE TITLE
text overflow

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1020]
**text overflow**

dataset titles should be truncated or wrapped

-----
fbitem-species8083599
User provided contact info: @MortenHofft
System: Chrome 63.0.3239 / Mac OS X 10.11.6
Referer: https://www.gbif.org/species/8083599
Window size: width 1916 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-07T10:45:14.849Z',mode:absolute,to:'2018-02-07T10:51:14.849Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-07T10:45:14.849Z',mode:absolute,to:'2018-02-07T10:51:14.849Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
no longer an issue
