### ISSUE TITLE
Network page design issue

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1021]
**Network page design issue**

The description of a network is oddly indented. It doesn't use the full width of the box.

-----
fbitem-4c4c0d01afc8840d5469ac3d33461c905ed30a77
User provided contact info: @peterdesmet
System: Chrome 63.0.3239 / Mac OS X 10.13.3
Referer: https://www.gbif.org/network/07b013b4-a2da-47a1-a8ef-df685912fbd6
Window size: width 1298 - height 736
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-07T12:11:29.641Z',mode:absolute,to:'2018-02-07T12:17:29.641Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-07T12:11:29.641Z',mode:absolute,to:'2018-02-07T12:17:29.641Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by peterdesmet** [comment]
<img width="771" alt="design issue" src="https://user-images.githubusercontent.com/600993/35915985-28c981a6-0c09-11e8-8c30-94ff53ee69a4.png">

**Comment by MortenHofft** [comment]
Still some inconsistency, but at least less messy. Thanks
