### ISSUE TITLE
System health icon does not display red dot for crawling issue

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1022]
**System health icon does not display red dot for crawling issue**

The system health indicates there is a partial outage, for Crawling: https://www.gbif.org/health

However, I seem to remember that the icon in the navbar indicates any health issue with a red dot. That is not the case currently (so the user doesn't see there is a health issue).

-----
fbitem-465f4ad16ed342b1a2d0972aceb430078ee021ba
User provided contact info: @peterdesmet
System: Chrome 63.0.3239 / Mac OS X 10.13.3
Referer: https://www.gbif.org/health
Window size: width 1298 - height 736
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-07T13:04:29.935Z',mode:absolute,to:'2018-02-07T13:10:29.935Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-07T13:04:29.935Z',mode:absolute,to:'2018-02-07T13:10:29.935Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
that is intentional as it isn't important for website usage that the crawler is offline. The red dot will only show when it impacts site usage.
