### ISSUE TITLE
reference not part of csv download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1026]
**reference not part of csv download**

The field `references` is not included in the simple CSV download (https://doi.org/10.15468/dl.ilo689), even though it is listed on occurrence pages: https://www.gbif.org/occurrence/1569827622

In fact, I see lots of properties of an occurrence (https://api.gbif.org/v1/occurrence/1569827622) are not part of the simple CSV. How it is decided what makes the cut and what does not?

-----
fbitem-be729dc37c1560970ee4eab936c31569c95bd9af
User provided contact info: @peterdesmet
System: Chrome 63.0.3239 / Mac OS X 10.13.3
Referer: https://www.gbif.org/occurrence/download/0002647-180131172636756
Window size: width 1298 - height 736
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-07T20:02:50.755Z',mode:absolute,to:'2018-02-07T20:08:50.755Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-07T20:02:50.755Z',mode:absolute,to:'2018-02-07T20:08:50.755Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
I'm not sure how it was first decided what goes into simple CSV, but to keep it simple, I don't think we should add everything, especially as references can be quite long. (So to actually answer the question: it's decided by discussion on these issues.)

In #531, I suggest we improve the text on the download page so people realize the DWCA format is just some zipped TSV files.
