### ISSUE TITLE
it would be nice if there was an archive for the slide decks, to find older ones

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1028]
**it would be nice if there was an archive for the slide decks, to find older ones**

e.g. I'm looking for the one covering the whole year of 2016

-----
fbitem-30f7060c479616aee0e808291e3e0319b7e26119
User provided contact info: icalabuig@snm.ku.dk
System: Chrome 64.0.3282 / Windows 10 0.0.0
Referer: https://www.gbif.org/document/81771/gbif-overview-powerpoint-slides
Window size: width 1557 - height 929
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-08T10:14:00.496Z',mode:absolute,to:'2018-02-08T10:20:00.496Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-08T10:14:00.496Z',mode:absolute,to:'2018-02-08T10:20:00.496Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by kcopas** [comment]
I'm preparing what I suspect you're looking for, Isabel!

**Comment by kcopas** [comment]
See [latest update](https://www.gbif.org/document/81771), with past versions appended in body of description.
