### ISSUE TITLE
Exclude duplicate lat, long coordinates

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1029]
**Exclude duplicate lat, long coordinates**

Is there a way to exclude records from a search or a download that have duplicate latitude and longitude coordinates?

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: @jameshansen91
System: Chrome 64.0.3282 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/search?basis_of_record=OBSERVATION&basis_of_record=HUMAN_OBSERVATION&basis_of_record=PRESERVED_SPECIMEN&geometry=POLYGON%20((-153.28125%2073.22669969306126,%20-171.5625%2069.65708627301174,%20-171.5625%2047.040182144806664,%20-153.28125%2034.30714385628804,%20-50.625%2036.59788913307022,%20-2.8125%2025.799891182088334,%2077.34374999999999%2019.31114335506464,%20154.68749999999997%2024.5271348225978,%20198.28125%2062.2679226294176,%20139.21874999999997%2079.4323707591471,%209.84375%2082.1183836069127,%20-142.03125%2083.97925949886205,%20-153.28125%2073.22669969306126))&geometry=POLYGON%20((-153.28125%2073.22669969306126,%20-171.5625%2069.65708627301174,%20-171.5625%2047.040182144806664,%20-153.28125%2034.30714385628804,%20-50.625%2036.59788913307022,%20-2.8125%2025.799891182088334,%2077.34374999999999%2019.31114335506464,%20154.68749999999997%2024.5271348225978,%20198.28125%2062.2679226294176,%20139.21874999999997%2079.4323707591471,%209.84375%2082.1183836069127,%20-142.03125%2083.97925949886205,%20-153.28125%2073.22669969306126))&has_coordinate=true&taxon_key=4889932&has_geospatial_issue=false
Window size: width 1600 - height 769
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-08T21:19:49.886Z',mode:absolute,to:'2018-02-08T21:25:49.886Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-08T21:19:49.886Z',mode:absolute,to:'2018-02-08T21:25:49.886Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
Hi James
I'm afraid the website do not have such a functionality. Be aware that when occurrences have the same coordinates it isn't necessarily because they are duplicates. It could be because they are a result of grid surveys where all occurrences within an area is assigned the same coordinates.

In other words you have to download the data and do it in your preferred software.
