### ISSUE TITLE
Confusing and potentially wrong dates shown on dataset page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#103]
**Confusing and potentially wrong dates shown on dataset page**

Atop this particular dataset page is the date 19 January 2017. One cannot distinguish if this is the date the dataset was registered with GBIF, initially published, or last updated. 

The [current dataset page](http://www.gbif.org/dataset/26d72d3b-4544-4645-aa56-27aa8a669c6f) shows 2 dates:

Pubication date = Jan 20, 2017
Registration date = Jul 12, 2016

Our [API response](http://api.gbif.org/v1/dataset/26d72d3b-4544-4645-aa56-27aa8a669c6f) has the following 2 datetime entries:

&quot;created&quot;: &quot;2016-07-12T08:40:03.383+0000&quot;,
&quot;modified&quot;: &quot;2017-01-20T08:12:59.586+0000&quot;,

Is &quot;2017-01-20T08:12:59.586+0000&quot; getting converted somehow to &quot;19 January 2017&quot;? Thanks.

![screen shot 2017-02-27 at 14 58 13](https://cloud.githubusercontent.com/assets/5981100/23364289/cc43674a-fcfe-11e6-8fba-6be13c912f94.png)

-----
fbitem-dataset26d72d3b-4544-4645-aa56-27aa8a669c6f
Reported by: @kbraak
System: Firefox 51.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/dataset/26d72d3b-4544-4645-aa56-27aa8a669c6f
Window size: width 1329 - height 954
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-27T14:03:37.666Z',mode:absolute,to:'2017-02-27T14:09:37.666Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-27T14:03:37.666Z',mode:absolute,to:'2017-02-27T14:09:37.666Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
It is the publication date:

**Comment by MortenHofft** [comment]
@kbraak  is this still an issue? if not could you please close it ? all the dates are available, but not all show in the header. for creation date for example you need to go to origin. Let me know what you believe is the most interesting date to show on the dataset.

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/299
