### ISSUE TITLE
Acknowledge YourKit and Intellij

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#105]
**Acknowledge YourKit and Intellij**

In return for free licenses we use for jetBrains and YourKit we should acknowledge them somewhere on our website. 

It makes sense to do so on the API page.
From YourKit:

The acknowledgment should contain:

1) Attached YourKit logo and text that your open source project is using YourKit profiler. Alternatively logo hosted at https://www.yourkit.com/images/yklogo.png
can be used.

2) Should contain a reference to YourKit web site.

For example:
&quot;
YourKit supports open source projects with its full-featured Java Profiler. YourKit, LLC is the creator of &lt;a href=&quot;https://www.yourkit.com/java/profiler/&quot;&gt;YourKit Java Profiler&lt;/a&gt;, innovative and intelligent tools for profiling Java  applications.
&quot;

See JetBrains acknowledgement here:
https://github.com/gbif/ipt/blob/master/README.md#acknowledgements

-----
fbitem-f0bca0774a9c8eaecc8788650664fc5d3e0b6ba1

System: Chrome 56.0.2924 / Mac OS X 10.12.3
Referer: https://demo.gbif.org/developer/summary
Window size: width 1418 - height 820
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-01T10:09:38.721Z',mode:absolute,to:'2017-03-01T10:15:38.721Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-01T10:09:38.721Z',mode:absolute,to:'2017-03-01T10:15:38.721Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
@kcopas should we create a general acknowledgement page. We are making use of a lot of open source tools, programmes, free licenses, open data etc. Could be a candidate for the footer. possible adverticed elsewhere (e.g. the API pages as Kyle sugests), but having it all gathered one place.

**Comment by kcopas** [comment]
@dnoesgaard flagging you so we don't loose track of this.

Going to add a starter page now. Think we should add a link to the footer—will talk with you soon about that @thomasstjerne

**Comment by kcopas** [comment]
[Acknowledgements page](https://www.gbif.org/acknowledgements) created.

@thomasstjerne , could you add a link to [Acknowledgements](https://www.gbif.org/acknowledgements) to the pipe-separated string in the footer? Preferred placement is between 'Terms and agreements' and 'Citation', I guess.

Issue can be closed following that addition.

**Comment by MattBlissett** [comment]
It would be nice to list some of the more important open source tools, rather than just commercial ones.

e.g. Linux, CentOS, Hadoop, Varnish.

For maps, we need to acknowledge OpenStreetMap, Natural Earth and OpenMapTiles.

**Comment by MortenHofft** [comment]
It is now in the footer.

**Comment by kcopas** [comment]
Thanks @MattBlissett — I kind of hoped/expected this might smoke out such credits. Bring 'em on!

Thanks for adding it to the footer, @MortenHofft — I'd only been bold enough to add @thomasstjerne because I had you not returning from the midwife in today's baby pool. ;-P

**Comment by kcopas** [comment]
@MattBlissett please have a look at the acknowledgements that you suggested. OpenStreetMap is the only one that requests a specific creditline (which I've reflected, even without a map on the acknowledgements page), so I'm mostly trying to make sure I link to the right source.

I've also tried to distinguish between the open-source tools we credit and the commercial ones that give us free licences. Suggestions welcome from any and all…

**Comment by MattBlissett** [comment]
Looks good to me.
