### ISSUE TITLE
[LIVE-TV]Saint Mary's vs Loyola Marymount Live Stream Free 2018 NCAA Basketball Online

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1051]
**[LIVE-TV]Saint Mary&#39;s vs Loyola Marymount Live Stream Free 2018 NCAA Basketball Online**

Saint Mary's vs Loyola Marymount Live Stream Free Watch NCAA Men's College Basketball Online TV Coverage 8 February 2018 from Gersten Pavilion, Los Angeles, California. Get unlimited access to college basketball on the go on your PC, Mac, Tab, iPhone, Android, Smart TV or Game Console in HD for Free without any restriction or unwanted ads.. Join now!!

Watch Live Online Free: http://livetv24.org/college-basketball/

Saint Mary's winning streak is alive at 18 games -- barely, after a 65-62 victory over San Diego -- and the Gaels are knocking on the door of a Top 10 ranking.

The No. 11 Gaels are setting all kinds of school records during the streak that started back on Dec. 2.

They're off to the best start in school history, have never been ranked as high as they are this week and their winning streak is the second-longest in the country.

And point guard Emmet Naar passed fellow Aussie Matthew Dellavadova as the school's all-time assist leader.

The Gaels (23-2, 12-0 West Coast Conference) go for No. 19 on Thursday against Loyola Marymount at Gersten Pavilion in Los Angeles. The Lions are 7-16 and 2-10 in conference play and on paper, the game looks like a mismatch.

The Gaels dominate in almost every category and the Lions don't have anyone who can match up with All-American candidate Jock Landale. Very few players in America can match up with the 6-foot-11 senior center, who averages 22.8 points, 10.8 rebounds and 2.1 assists per game.

The Gaels almost didn't make it to No. 18 in a row as they had their hands full with the Toreros. Landale rescued Saint Mary's by scoring 34 points and grabbing 18 rebounds.

"There's very few of those guys that you can actually just keep going to in the post, they're not going to double, they're going to make him beat them," Saint Mary's coach Randy Bennett told the San Jose Mercury News. "He can do it."

The Toreros' game plan was clear: Let Landale get his points and stop everyone else. The strategy almost paid off.

"We thought if we could let Landale get 100 and lock up the rest of the guys we may give ourselves a chance," San Diego coach Lamont Smith joked. "And he's a load. He's hard to guard. He did everything he could to keep his team in the game and then some."

The Lions are coming off an up-and-down week that started with an upset of BYU last Thursday and a heartbreaking loss to Portland on Saturday. Down by 10 at half, the Lions took a second-half lead only to lose in the last two seconds on a pair of free throws.

In the win against BYU, the Lions recorded 14 steals, with Jeffery McClendon, the conference leader, recording four of them. McClendon also is coming off a career-high tying 15 points in the loss to Portland.

"I'm just really happy for the players," head coach Mike Dunlap said. "To get this game against a very good team on the upper end of the conference is great for our guys."

James Batemon led all scorers with 28 points on 9-for-14 shooting. Eli Scott recorded his fourth double-double of the season with 19 points and 10 rebounds.

Dunlap will need the same kind of effort on Thursday to give the Lions a chance against the deeper and more experienced Gaels.

In the first meeting between the two schools this year, an 87-59 Gaels' win Landale scored 21 points and hauled down nine rebounds. Calvin Hermanson went 4 of 5 from 3-point range and Saint Mary's shot a sizzling 62 percent.

It seems like the Lions' best hope is that the Gaels might be looking ahead to Saturday's home game against No. 12 Gonzaga -- a mega-matchup for supremacy in the WCC.

-----
fbitem-7490229a59148a44a969f4b702276af26e940516

System: Chrome 63.0.3239 / Windows 10 0.0.0
Referer: https://www.gbif.org/standards
Window size: width 1185 - height 591
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-09T02:53:03.654Z',mode:absolute,to:'2018-02-09T02:59:03.654Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-09T02:53:03.654Z',mode:absolute,to:'2018-02-09T02:59:03.654Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by fgvdcgvdg** [comment]
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
http://www.sport2018.org/4k/madness/ch-2/
