### ISSUE TITLE
[LIVE-TV]Arizona vs UCLA Live Stream Free 2018 NCAA Basketball Online

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1054]
**[LIVE-TV]Arizona vs UCLA Live Stream Free 2018 NCAA Basketball Online**

Arizona vs UCLA Live Stream Free Watch NCAA Men's College Basketball Online TV Coverage 8 February 2018 from McKale Center, Tucson, Arizona. Get unlimited access to college basketball on the go on your PC, Mac, Tab, iPhone, Android, Smart TV or Game Console in HD for Free without any restriction or unwanted ads.. Join now!!

Watch Live Online Free: http://livetv24.org/college-basketball/

The 13th-ranked Arizona Wildcats and UCLA Bruins will battle it out in primetime Thursday in Tucson.

Arizona (19-5, 9-2 Pac-12) is coming off a loss to Washington, while UCLA (16-7, 7-4) is riding a three-game winning streak. This is the only time Arizona and UCLA will play against each other in the regular season.

Here are some storylines to watch and three keys for Arizona to come away with a win.

Below you can find out how to tune into the action.

-----
fbitem-7490229a59148a44a969f4b702276af26e940516

System: Chrome 63.0.3239 / Windows 10 0.0.0
Referer: https://www.gbif.org/standards
Window size: width 1185 - height 591
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-09T03:03:46.273Z',mode:absolute,to:'2018-02-09T03:09:46.273Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-09T03:03:46.273Z',mode:absolute,to:'2018-02-09T03:09:46.273Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by fgvdcgvdg** [comment]
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
Watch Live Now>>>> http://www.sport2018.org/4k/madness/ch-2/
