### ISSUE TITLE
How to download data?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#106]
**How to download data?**

How do I download the data?

-----
fbitem-066f438500c724cac3af4f667be0f432015473ff

System: Chrome 56.0.2924 / Windows 10 0.0.0
Referer: https://demo.gbif.org/tools/data-validator
Window size: width 1366 - height 638
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-02T05:27:53.650Z',mode:absolute,to:'2017-03-02T05:33:53.650Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-02T05:27:53.650Z',mode:absolute,to:'2017-03-02T05:33:53.650Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
For occurrence data, by clicking "Get data" -> "Occurrences" at the top of the page, it will bring you to this page: https://demo.gbif.org/occurrence/search . From there, there is the "Download" button at the right of the page, it is possible to see some screenshots on https://github.com/gbif/portal-feedback/issues/94
