### ISSUE TITLE
Duplicate records included in simple csv download

### ISSUE THREAD

**Issue by nickynicolson** [gbif/portal-feedback#1061]
This is a download request for a simple CSV format occurrence download. 

https://www.gbif.org/occurrence/download/0014881-171219132708484

It includes duplicate records, such as gbifid value 1675506980 which appears twice (in two identical rows).
Almost a million (997086) gbifids are duplicated in this datafile.

**Comment by MattBlissett** [comment]
`unzip -p 0014881-171219132708484.zip 0014881-171219132708484.csv | cut -d$'\t' -f 1 | sort | uniq -d | nl`

Shows the duplicated lines.

A test of some other recent large downloads didn't show any other problems, but I only checked a few.

**Comment by MattBlissett** [comment]
There is an earlier reported case: https://github.com/gbif/occurrence/issues/28

**Comment by MattBlissett** [comment]
Now an example with a DwCA: 

https://www.gbif.org/occurrence/download/0005575-181003121212138 and rerun as 
https://www.gbif.org/occurrence/download/0006806-181003121212138

The metadata says the dataset contributed 10M records, but it only contains 2M.

We need to get to the bottom of this.

**Comment by MattBlissett** [comment]
All the problem downloads from the last few days. The majority of/all records coming from a single dataset looks like a symptom, although 0005705-181003121212138 and 0005571-181003121212138 are just BasisOfRecord filters.

2018-10-17:
0007375-181003121212138 Record count 4168915 doesn't match API count 2408695
0007375-181003121212138 has duplicate rows
0007389-181003121212138 Record count 1477632 doesn't match API count 743753
0007389-181003121212138 has duplicate rows

2018-10-16:
0006806-181003121212138 Record count 4168915 doesn't match API count 2408695
0006806-181003121212138 has duplicate rows
0006822-181003121212138 Record count 4168915 doesn't match API count 2408695
0006822-181003121212138 has duplicate rows

2018-10-15:
0005705-181003121212138 Record count 47777274 doesn't match API count 43290895
0005705-181003121212138 has duplicate rows

2018-10-14:
0005571-181003121212138 Record count 9708760 doesn't match API count 8980654
0005571-181003121212138 has duplicate rows
0005575-181003121212138 Record count 5054221 doesn't match API count 2408695
0005575-181003121212138 has duplicate rows

2018-10-13:
0004714-181003121212138 Record count 5054221 doesn't match API count 2408695
0004714-181003121212138 has duplicate rows
0004754-181003121212138 Record count 8468676 doesn't match API count 4440020
0004754-181003121212138 has duplicate rows
0004844-181003121212138 Record count 5054221 doesn't match API count 2408695
0004844-181003121212138 has duplicate rows
0005036-181003121212138 Record count 5054221 doesn't match API count 2408695
0005036-181003121212138 has duplicate rows

**Comment by timrobertson100** [comment]
Fix now in production.
