### ISSUE TITLE
Return download/dataset DOI as https://doi.org/...

### ISSUE THREAD

**Issue by peterdesmet** [gbif/portal-feedback#1063]
Currently, the API for:

http://api.gbif.org/v1/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e

http://api.gbif.org/v1/occurrence/download/0000251-150304104939900

Return the property `doi` as `doi:10.15468/dl.ybrup3`. However, that is the old format for expressing DOIs. Since March 2017, [Crossref advises](https://www.crossref.org/display-guidelines/#full) to return DOIs as:

    https://doi.org/10.xxxx/xxxxx

That is already the case everywhere on the GBIF website. Would be good to do it the same for the API.

_Note 1: I'm aware for DOIs for datasets and downloads, but it might be returned for other GBIF endpoints as well..._

_Note 2: I'm reporting directly here, because the "feedback system doesn’t work"._

**Comment by MattBlissett** [comment]
I have already set it to be returned as `10.15468/dl.ybrup3`, currently awaiting deployment to production.

http://api.gbif-uat.org/v1/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e

http://api.gbif-uat.org/v1/occurrence/download/0000251-150304104939900

The DOI is strictly just `10.15468/dl.ybrup3`, the rest isn't part of the DOI. It's also easy enough to prepend whatever the user wants.

**Comment by MortenHofft** [comment]
Thanks @peterdesmet 
> Note 2: I'm reporting directly here, because the "feedback system doesn’t work".

We have started to receive bulks of spam and hence disabled feedback temporarily. See https://github.com/gbif/portal16/issues/666

**Comment by peterdesmet** [comment]
> Strictly not part of DOI

Fair enough, just wonder how often users will want to prepend that with something else. And getting a full clickable DOI back from the API seems more useful in most use cases.

**Comment by mdoering** [comment]
I would also better follow the current recommendations and return the https link

**Comment by peterdesmet** [comment]
In that case the issue should maybe be reopened. 😄

**Comment by MattBlissett** [comment]
I disagree — the API usually gives keys, not URLs or nicely formatted data.

Formatting values is a task for the client; for example using the Java client we can request `dataset.getDoi().getUrl()` if we want a URL.

Also, the DOI Handbook still describes several possible formats: http://www.doi.org/doi_handbook/2_Numbering.html#2.6
