### ISSUE TITLE
Prevent duplicate submissions via 'catcher'

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#109]
**Prevent duplicate submissions via &#39;catcher&#39;**

To prevent duplicate submissions being made via the &#39;catcher&#39; @dschigel and I propose:

Upon information being entered into either the &#39;Internet link to data&#39; or &#39;Bibliographic reference&#39; fields, query the [GitHub issues](https://github.com/gbif/data-mobilization/issues) to check for an existing issue having these links/identifiers. The same duplicate check could even be done for the title. In any case, upon finding a potential duplicate the user is warned an existing issue with this link/title already exists. 

This will alleviate the load on the person(s) managing incoming issues. 

More importantly, this will save users from wasting there time submitting duplicate issues. It has already happened once, and is likely to happen more as the &#39;catcher&#39; becomes more widely used.

-----
fbitem-650dd53d64421891d161f2147516cbcf45073b95
Reported by: @kbraak
System: Firefox 51.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/tools/suggest-dataset
Window size: width 1569 - height 968
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-03T10:45:30.110Z',mode:absolute,to:'2017-03-03T10:51:30.110Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-03T10:45:30.110Z',mode:absolute,to:'2017-03-03T10:51:30.110Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
I am not sure whether this would be in any way simpler/easier to add short-term, but maybe it would be enough to support a simple key word search before starting to register a dataset, á la "check whether the dataset you have in mind has already be suggested by someone else", and an autocomplete/search for some key terms that a hopeful submitter might pick from the title and enter, like "Predicts" or "Paris basin" or "Falco"?

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/329
