### ISSUE TITLE
ATTENTION PLEASE!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1098]
**ATTENTION PLEASE!**

Hello MattBlissett.. Please do me a favor, i post more then 100 post everyday but i only post few of them here cause i don't wanna spam here. I respect others hard work and don't wanna ruin it. But i will ask you as a favor please DELETE my post after 2 hour, it will be great if you give me some space here.

THANKS!

Please ans me @ matthewnewman20167@gmail.com

-----
fbitem-450d225af724cf2a5d268372839b2b840829034b

System: Chrome 63.0.3239 / Windows 10 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/d8eb0b1792eac6bb530513254756f624:6388142cfff387047054eb54b6999fb4d61c4718f820f66c69dea2f40ff4248aee38ae5a7808e86333243bd3cd28050beb6afaeebc8cf07cf68b7806821d1d91)
Referer: https://www.gbif.org/user/confirm?username=janetvcarter&code=8ff76ab2-3d0f-449a-ab76-ed22c01e80d3
Window size: width 1185 - height 591
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-13T20:58:18.128Z',mode:absolute,to:'2018-02-13T21:04:18.128Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-13T20:58:18.128Z',mode:absolute,to:'2018-02-13T21:04:18.128Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Test a hyperlink as monospace text: `https://www.gbif.org/`
