### ISSUE TITLE
content feedback on occurrences with contacts

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#11]
**content feedback on occurrences with contacts**

content feedback on occurrences with contacts displays unstyled. And the text beneath the is wrong.

I would suggest repeating the text from the annotatable occurrences and collapsing the contact info if the users decides to contact ud despite having the contact info for the dataset owner

-----
fbitem-occurrence1298979592
Reported by: @mortenhofft
System: Chrome 55.0.2883 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/occurrence/1298979592
Window size: width 1974 - height 1129

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/74262cac1e69f66294912bc0299cc17a2918bbc6
