### ISSUE TITLE
Unable to log in to new site

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#114]
**Unable to log in to new site**

Hi, 

I am trying to access species occurrence data in the new site but when I log in it says  &quot;Unable to log in. Unknown user or password&quot;, even though I have an account with GBIF and I have downloaded occurrence data before with no problem.  Is there something wrong with the system? 

I&#39;ve also created a new account, as did my colleague, and the same thing happens again to me and her. 

Can anyone offer any assistance?

All the best, 

B

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
Reported by: @betina
System: Chrome 56.0.2924 / Windows 7 0.0.0
Referer: https://demo.gbif.org/search?q=Andrena%20fulva
Window size: width 1920 - height 1070
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-05T14:06:53.714Z',mode:absolute,to:'2017-03-05T14:12:53.714Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-05T14:06:53.714Z',mode:absolute,to:'2017-03-05T14:12:53.714Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
I have just synchronised all accounts and see yours was migrated. Can you please try again and confirm it works?

**Comment by timrobertson100** [comment]
The synchornisation was incorrectly using the UAT environment as source, which meant accounts would not propagate correctly.  This has been addresses and the account for the original reporter is migrated and a CRON set up for this to operate every 15 minutes.

**Comment by timrobertson100** [comment]
Confirmed through email exchange - fixed
