### ISSUE TITLE
New French collections data lack year

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1145]
I'm wondering if the new datasets coming in from [RECOLNAT](https://www.gbif.org/publisher/02fce6f4-8dcd-4eaf-afe9-28ba30822751) are part of the 20 million records we're expecting this year. If so, we should be concerned about their completeness, because [just 93 of the 142,859 records](https://www.gbif.org/occurrence/search?publishing_org=02fce6f4-8dcd-4eaf-afe9-28ba30822751&year=1000,2018&advanced=1) appear to have an associated date—despite them consistently having high-res specimen images that clearly document the collection date. 

Can't seem to tag node staff—will forward issue via email.

**Comment by ahahn-gbif** [comment]
Not sure why, but these issues do not light up very much in the tagging so far (#1189).
Sent an email to the publisher CC Node. The collections include images of objects; first guess is that they need label transcriptions to still catch up, but worth inquiring anyway.

**Comment by ahahn-gbif** [comment]
According to communication from the publisher, occurrences are digitized specimen-image first, label transcription in progress, so that the dataset content will improve over time.

**Comment by ahahn-gbif** [comment]
closing, as there is no further action required
