### ISSUE TITLE
API example for typeSpecimens is empty

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1146]
**API example for typeSpecimens is empty**

The API example for `/species/{int}/typeSpecimens` at 'https://www.gbif.org/developer/species' returns an empty result:

'http://api.gbif.org/v1/species/5231190/typeSpecimens'

Is there an example with actual data?

-----

User provided contact info: @peterdesmet
System: Chrome 63.0.3239 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/72e04f3e1e1ef771e773e1bbf1f8dd81:9e16292b8550266680cd5041dd629cd63908d9d34af72755bdd599f6e9e796ae0455cc115b88ac68c86ff597014b3a8d85a3d835377ffec2410c156d235bc280)
Referer: https://www.gbif.org/developer/species
Window size: width 1411 - height 847
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-14T13:41:44.581Z',mode:absolute,to:'2018-02-14T13:47:44.581Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-14T13:41:44.581Z',mode:absolute,to:'2018-02-14T13:47:44.581Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
I think the species API currently returns empty results for any species, eg: [http://api.gbif.org/v1/species/9611316/typeSpecimens](http://api.gbif.org/v1/species/9611316/typeSpecimens) which should have a holotype. 
@mdoering could you take a look at this?

**Comment by mdoering** [comment]
in the current checklist bank index there is not too much type information available. Different from the original design specimens are not kept in CLB anymore.

The URL therefore only returns results for type species or genera. Unfortunately this is a hihgly patchy information and by nature only available for genus and family names.

An example for "Nesogryllus Perkins, 1899":

https://api.gbif.org/v1/species/1720860
https://api.gbif.org/v1/species/1720860/typeSpecimens
