### ISSUE TITLE
Node contact details no longer visible

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1166]
**Node contact details no longer visible**

I think the bug lies in the portal.

The first contact is no longer visible.

-----

User provided contact info: @MattBlissett
System: Firefox 57.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/fcb89f798a4e27d7e1c4e55621422e00:45b60142fb58844f3f6e5754ee8b8dbc97d8c7c80f1d1ec395e746ae853fbec63f0dec24529b8653c493e66cbf6437581d0aab69944a5555965b3da1df0aa28f)
Referer: https://www.gbif.org/country/DK/summary
Window size: width 1200 - height 1792
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-15T14:12:04.353Z',mode:absolute,to:'2018-02-15T14:18:04.353Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-15T14:12:04.353Z',mode:absolute,to:'2018-02-15T14:18:04.353Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
node name and node manager missing as well.
