### ISSUE TITLE
Email link incorrect on why hasn't GBIF (re)indexed ...

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1169]
**Email link incorrect on why hasn&#39;t GBIF (re)indexed ...**

Link goes to ``https://www.gbif.org/dataset/helpdesk@gbif.org``

Rather than:

`mailto:helpdesk@gbif.org`

-----

User provided contact info: @peterdesmet
System: Chrome 63.0.3239 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/19dd3c82d9dc0967e403989d435145b3:b10fe9cc0a99ff98967d8950ef85bda8a82d37e98cce2fe0c155636164d78dc7e7feae5b0823294034b006ef580748888ee82350c1fc8b75268432e86cf52f23)
Referer: https://www.gbif.org/dataset/98940a79-2bf1-46e6-afd6-ba2e85a26f9f
Window size: width 1227 - height 736
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-16T10:13:34.784Z',mode:absolute,to:'2018-02-16T10:19:34.784Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-16T10:13:34.784Z',mode:absolute,to:'2018-02-16T10:19:34.784Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by peterdesmet** [comment]
Screenshot:

<img width="767" alt="screen shot 2018-02-16 at 11 17 16" src="https://user-images.githubusercontent.com/600993/36303092-2ac7a498-130b-11e8-8f8f-9e6b2736b16f.png">

**Comment by MortenHofft** [comment]
Thanks peter
contentful updated and issue fixed.
@dnoesgaard be aware that mail links in contentful needs to be prefixed with `mailto:` the markdown parser doesn't do anything smart unfortunately
