### ISSUE TITLE
Add archive of previous slide updates

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1171]
Per Walter Berendsohn's suggestion, consider providing access to previous versions of the [GBIF slide update](https://www.gbif.org/document/81771/gbif-overview-powerpoint-slides).

Could be done with an unordered list of inline links to Contentful attachments in body text.

**Comment by dnoesgaard** [comment]
Sure. Do you prefer than we keep one, single document entry that we keep updating - or create a new one every update?

**Comment by kcopas** [comment]
See [latest update](https://www.gbif.org/document/81771), with past versions appended in body of description.
