### ISSUE TITLE
Occurence API and Species API

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1172]
**Occurence API and Species API**

Hi,

I would like to implement a functionality in my personal application : the possibility to retrieve all the species for a given country and a given taxon ( like on your website : `https://www.gbif.org/occurrence/species?country=AU&taxon_key=212&advanced=1` ).
At this time, I'm only able to retrieve all the occurence of human observation for a given country and a given taxon by using the Occurence API, is there a way to only retrieve the species for a location and not all the observations ? 

( Sorry I'm French my english is not really good ) 

Thank you,

Julien

-----

User provided contact info: jrouard@icloud.com
System: Safari 10.1.2 / Mac OS X 10.12.6
User: [See in registry](https://www.gbif.org/api/feedback/user/05fc51b2dfc2bd65af75284c81172ac7:c0e5776f0d5150bdd53e5e915ec53accf2434e6730507eb3255fc9fb6ff4ac77df8d780f65aefe7e63f8576fafed4f53f6c72313ba7ec7aa79fd5b3fceef15ef)
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1438 - height 962
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-17T11:54:47.085Z',mode:absolute,to:'2018-02-17T12:00:47.085Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-17T11:54:47.085Z',mode:absolute,to:'2018-02-17T12:00:47.085Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Hello
The api call for https://www.gbif.org/occurrence/species?country=AU&taxon_key=212&advanced=1
is https://api.gbif.org/v1/occurrence/search?limit=0&country=AU&taxon_key=212&facet=speciesKey

What this does is that it says:
* don't give me the occurrences (limit=0)
* but give me the distinct species (facet=speciesKey) and a count for each 

This returns the 10 most frequently occurrences species by their id/key.

You can then paginate using `facetLimit` and `facetOffset` e.g. https://api.gbif.org/v1/occurrence/search?limit=0&country=AU&taxon_key=212&facet=speciesKey&facetLimit=10&facetOffset=10 to get page 2 of 10 item pages.

You can then look up the names using the species api e.g. http://api.gbif.org/v1/species/2479598

What this will all give you is a list of species that have been reported as an occurrence in that area.

Hope that helps

>send per email
