### ISSUE TITLE
When selected a polygon, I get records from a different area

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1177]
**When selected a polygon, I get records from a different area**

https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&taxon_key=1470&geometry=POLYGON((-16.51007%20-3.44864,-16.51007%2014.46034,28.23993%2014.46034,28.23993%20-3.44864,-16.51007%20-3.44864))

searching for specimens in tropical west Africa I get records from the following countries:
Costa Rica
Venezuela 
Nicaragua 
Colombia 
Panama 
Ecuador 
Suriname 
Guyana 
French Guiara 
Tanzania, United Republic Of 

Cheers,

Paco

-----

System: Chrome 64.0.3282 / Windows 10 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/f8fd06e11ca13a316252aba6891fa0c5:98c74e543bdefd66624449d6682798ed7f997e66bc3f775e265cf78331931bc2b5c945f5d123eccb627e5a5c69d2410ce7da9ce8d0dc53c51beef81f2a484c54)
Referer: https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&taxon_key=1470&geometry=POLYGON((-16.51007%20-3.44864,-16.51007%2014.46034,28.23993%2014.46034,28.23993%20-3.44864,-16.51007%20-3.44864))

**Comment by MattBlissett** [comment]
That's weird. The polygon is correctly drawn around part of Africa, but the search query has become the rest of the world (across the date line).

**Comment by MattBlissett** [comment]
This is happening with all rectangles.

Changing the polygon to a trapezium (I added 0.000001 degrees to the first point's longitude) gives correct results.

https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&taxon_key=1470&geometry=POLYGON((-16.510071%20-3.44864,-16.51007%2014.46034,28.23993%2014.46034,28.23993%20-3.44864,-16.510071%20-3.44864))

**Comment by MattBlissett** [comment]
Fixed by https://github.com/gbif/occurrence/commit/50f2da36c40c567dbad8d3164eeb05eef98995e8
