### ISSUE TITLE
polar islands cut when opening country page of Russia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1178]
**polar islands cut when opening country page of Russia**

When opening the default view of Russian country page Arctic is not visible by default

-----

User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/2a9792e1287e7de2a02b3e77b18dee1a:1910d4304e10ac926ac8e81386cb6e2f6834b71d0a00ac6b9a7095f3c8eea889cc043c3aa5c30c37b80ec5afce32cde672aa99be969b55441d78efcae8d9a1d0)
Referer: https://www.gbif.org/country/RU/summary
Window size: width 1920 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-20T09:14:57.496Z',mode:absolute,to:'2018-02-20T09:20:57.496Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-20T09:14:57.496Z',mode:absolute,to:'2018-02-20T09:20:57.496Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
There are two parts of this

First most the [capabilities API](https://api.gbif.org/v2/map/occurrence/density/capabilities.json) that states worldwide coverage:
```
{
  'minLat': -90, 
  'minLng': -180, 
  'maxLat': 90, 
  'maxLng': 180,
  ...
}
```

secondly the website tries to fit all that into the view without repeating longitude and since the map isn't 1:2 it won't fit. I don't see any reason why it isn't. Looks like a mistake including the controls in the size calculation. See issue https://github.com/gbif/portal16/issues/681

**Comment by MattBlissett** [comment]
That capabilities request is for all occurrences, I don't know why the Russia page would make it.

It also makes this query https://api.gbif.org/v2/map/occurrence/density/capabilities.json?country=RU which is correct.

I'd still like to improve the capabilities response, e.g. https://github.com/gbif/maps/issues/17  and https://github.com/gbif/portal-feedback/issues/340

Russia is too big, but Greenland or Svalbard's capabilities could recommend a default Arctic projection.
