### ISSUE TITLE
Link checklist occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#118]
**Link checklist occurrences**

For a specific taxon in a checklist with occurrences we should also show the number of occurrences and a link to the occ search for that dataset &amp; species. This requires a backbone taxonKey to exist (nubKey), otherwise we can only link to a full text search for the scientific name and the datasetKey

-----
fbitem-dataset4ed70d4f-2ae9-4762-ad7f-f9d7bf2bee68

System: Chrome 56.0.2924 / Mac OS X 10.12.3
Referer: https://demo.gbif.org/dataset/4ed70d4f-2ae9-4762-ad7f-f9d7bf2bee68/taxonomy/127719096
Window size: width 1616 - height 939
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-08T09:07:24.049Z',mode:absolute,to:'2017-03-08T09:13:24.049Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-08T09:07:24.049Z',mode:absolute,to:'2017-03-08T09:13:24.049Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
This issue was moved to gbif/portal16#310
