### ISSUE TITLE
It would be nice to limit search results to vernacular names

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1181]
**It would be nice to limit search results to vernacular names**

Many vernacular names like Adler or Fish match authors and return rather irritating results

-----

System: Chrome 64.0.3282 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/cc64efd32c141edefa3ac9bd9288ae5a:45743807b5fc8f488c4981b1e0ee28b112a1e683069f0b2bf4ce842de2fd8f69fc185dfbb34c3757e149a0bd77edfcbcc9f7e197a62e63a720feb1037328df63)
Referer: https://www.gbif.org/species/search?q=fish
Window size: width 1609 - height 863
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-20T15:08:26.684Z',mode:absolute,to:'2018-02-20T15:14:26.684Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-20T15:08:26.684Z',mode:absolute,to:'2018-02-20T15:14:26.684Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@mdoering Yeah that makes sense. How do you imagine it should work? A filter with vernacular names suggest? Didn't you do something with species/match and vernacular names at some point? I'm afraid I cannot remember what anymore.

**Comment by mdoering** [comment]
I have to look it up myself, but the search & suggest can be limited to match just vernaculars I believe. A new lookup filter could work nicely, but it wont allow you to combine it with the main search query. Alternatively a checkbox or dropdown next to the main search that limits results to matches based on one of the 3 query fields: https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/model/checklistbank/search/NameUsageSearchRequest.java#L36

**Comment by MortenHofft** [comment]
I think I prefer the suggest. At least for now as it is simple and it fits how we do fx `Scientific Name` on occurrence search.  What is the suggest parameter please?

**Comment by mdoering** [comment]
For occurrences suggesting a taxonKey filter via a scientificName makes sense. But for a species search you would restrict results to always just one record. If combined with any other filter to nothing in most cases. Is that intuitive?

**Comment by mdoering** [comment]
Good question about the API parameter. It is undocumented here: https://www.gbif.org/developer/species#searching

It is qField:
http://api.gbif.org/v1/species/search?q=Adler&qField=VERNACULAR

Looks like hlField and likely some more parameters are also missing in the docs:
https://github.com/gbif/gbif-common-ws/blob/master/src/main/java/org/gbif/ws/util/WebserviceParameter.java
