### ISSUE TITLE
No species match for Argentina

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#1182]
No match for `argentina` 
http://api.gbif.org/v1/species/match?name=argentina&verbose=true

I'm fairly certain this used to be the case I have used this as a test case many times. It seems wrong given that there are two canonical names that are simply `argentina`

This might be a duplicate, I thought I created the issue the other day, but I cant find it anywhere. If so: bear with me.

**Comment by mdoering** [comment]
There are 3 Argentina genera:
http://api.gbif.org/v1/species/match?name=Argentina&verbose=true

The matching is case sensitive as it first does name parsing which expects genera to be Capitalized.
