### ISSUE TITLE
Missing nubKey from API?

### ISSUE THREAD

**Issue by davidorme** [gbif/portal-feedback#1199]
Hi,

I've been using the API /species/{int} endpoint to look up the accepted usage for synonyms in some taxon validation code. From the responses to that, I've been storing `nubKey` as a reference of the taxon ID. I've just run into an example where the JSON response doesn't provide `nubKey`. In comparison to another accepted usage, the JSON keys are identical except that this one lacks `nubKey`.

This is the link:
http://api.gbif.org/v1/species/8843683

and the response:
```json
{
	"key": 8843683,
	"nameKey": 12965228,
	"taxonID": "gbif:8843683",
	"sourceTaxonKey": 126905852,
	"kingdom": "Animalia",
	"phylum": "Chordata",
	"order": "Carnivora",
	"family": "Felidae",
	"genus": "Felis",
	"species": "Felis gracilis",
	"kingdomKey": 1,
	"phylumKey": 44,
	"classKey": 359,
	"orderKey": 732,
	"familyKey": 9703,
	"genusKey": 2435022,
	"speciesKey": 8843683,
	"datasetKey": "d7dddbf4-2cf0-4f39-9b2a-bb099caae36c",
	"constituentKey": "6cfd67d6-4f9b-400b-8549-1933ac27936f",
	"parentKey": 2435022,
	"parent": "Felis",
	"scientificName": "Felis gracilis Horsfield, 1821",
	"canonicalName": "Felis gracilis",
	"authorship": "Horsfield, 1821",
	"nameType": "SCIENTIFIC",
	"rank": "SPECIES",
	"origin": "SOURCE",
	"taxonomicStatus": "ACCEPTED",
	"nomenclaturalStatus": [	],
	"remarks": "",
	"numDescendants": 0,
	"lastCrawled": "2018-02-01T18:31:59.197+0000",
	"lastInterpreted": "2018-02-01T17:36:16.358+0000",
	"issues": [ ],
	"synonym": false,
	"class": "Mammalia"
}
```

The response also has `key` and `nameKey`, but I think `nameKey` refers to the key within one of the constituent datasets that contribute to the backbone. Is `key` always a synonym for `nubKey` for accepted species?

**Comment by thomasstjerne** [comment]
Yes, if it is a backbone taxon the key is the nubKey.
