### ISSUE TITLE
Correct terminology of species populations

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#12]
**Correct terminology of species populations**

**THIS NEEDS REVIEW FROM @dschigel BEFORE IMPLEMENTATION**

Thanks to detailed feedback from DS and SM, we should rename this as follows:

-  [ ] menu item should read &quot;Relative abundance trends&quot;
-  [ ] the URL should be /tools/relative-abundance-trends 
-  [ ] the embed URL should be /embed/relative-abundance-trends 
-  [ ] the information URL of the tool should be /tools/relative-abundance-trends/about
-  [ ] the title of the tool should read &quot;Relative Abundance Trends&quot;
-  [ ] the statement should read &quot;Visualise the rate of change of relative abundance of a species over time.&quot;

-----
fbitem-f0b1d8e8c6811b830ef2f932fb5cf1be7ba9cf0a
Reported by: @timrobertson100
System: Chrome 54.0.2840 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/tools/species-population
Window size: width 1433 - height 799

**Comment by MortenHofft** [comment]
not all text on the tools is in the translation file at this point, but some of it including the title is:
https://github.com/gbif/portal16/blob/master/locales/server/en.json#L1762

**Comment by gbif-portal** [comment]
Closed as duplicate of https://github.com/gbif/portal16/issues/200
