### ISSUE TITLE
Parent vs accepted usage in taxon database downloads

### ISSUE THREAD

**Issue by davidorme** [gbif/portal-feedback#1201]
I'm comparing the two available downloads for the taxonomy database for use in an offline taxonomy validator from here:

http://rs.gbif.org/datasets/backbone/

The `Taxon.tsv` file in `backbone-current.zip` contains two fields `parentNameUsageID` and `acceptedNameUsageID`. `acceptedNameUsageID` is only populated for synonyms and misapplications and points to the equivalent accepted taxon and `parentNameUsageID` points to the parent.  The `parentNameUsageID` for the taxon and the accepted taxon should then be identical. That makes it really easy to hook synonyms into the accepted backbone.

Unfortunately, because `Taxon.tsv` only includes the names of higher taxa for a taxon and not keys (so `family` but no `familyKey`). That makes it impossible to extract an unambiguous taxon level hierarchy (pairs of names and ID) for a taxon because ambiguous names like _Solenopsis_ or _Morus_ can't be resolved without their key.

The data in  `backbone-current-simple.txt.gz` does contain the higher taxon keys, but it conflates the accepted usage and parent into the single `parent_key` field. Is it the case that `parent_key` is _always_ the accepted usage when `is_synonym = 't'`? Because synonyms don't always have the same rank as the accepted usage, I can't think of a simple way to check if this is correct.

Sorry about the slew of questions/feedback!
David

**Comment by davidorme** [comment]
Was being dim - there is a simple way to check if this correct:

```SQL
sqlite> SELECT syn.status, par.status, count(*) 
   ...>   FROM (SELECT status, parent_key 
   ...>     FROM backbone 
   ...>     WHERE status NOT IN ('DOUBTFUL','ACCEPTED')) AS syn
   ...>   INNER JOIN (SELECT id, status FROM backbone) as par
   ...>   ON syn.parent_key = par.id
   ...>   GROUP BY syn.status, par.status;
HETEROTYPIC_SYNONYM|ACCEPTED|65000
HETEROTYPIC_SYNONYM|DOUBTFUL|448
HOMOTYPIC_SYNONYM|ACCEPTED|199834
HOMOTYPIC_SYNONYM|DOUBTFUL|38540
MISAPPLIED|ACCEPTED|3962
MISAPPLIED|DOUBTFUL|40
PROPARTE_SYNONYM|ACCEPTED|17960
PROPARTE_SYNONYM|DOUBTFUL|252
SYNONYM|ACCEPTED|2019810
SYNONYM|DOUBTFUL|33585
sqlite> 
```
So, yes, `parent_key` in `backbone-current-simple.txt.gz` has two interpretations:
  1) For 'ACCEPTED' and 'DOUBTFUL' taxa, the `parent_key` identifies the parent taxon.
  2) For all other statuses, `parent_key` maps the taxon an accepted or doubtful taxon as the accepted usage.

**Comment by ManonGros** [comment]
It looks like this issue can now be closed, could you confirm @davidorme?

**Comment by davidorme** [comment]
Yes, happy to close.
