### ISSUE TITLE
Taxonomy error with Salvia rosmarinus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1202]
**Taxonomy error with Salvia rosmarinus**

Taxonomy error with Salvia rosmarinus
According to the 2017 Checklist of "Catalogue of Life", Salvia rosmarinus Schleiden is a synonym of Rosmarinus officianlis L. and not the other way around.

`http://www.catalogueoflife.org/annual-checklist/2017/details/species/id/4a3026cbf7b18d0f1b397887aa6aa6b4`

----------------------------------------------
Error de taxonomía con Salvia rosmarinus
De acuerdo con la Lista de verificación 2017 del "Catálogo de la vida", Salvia rosmarinus Schleiden es sinónimo de Rosmarinus officianlis L. y no al revés.

`http://www.catalogueoflife.org/annual-checklist/2017/details/species/id/4a3026cbf7b18d0f1b397887aa6aa6b4`

-----

User provided contact info: herbariomgc@uma.es
System: Chrome 63.0.3239 / Windows 8 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/db643755ce6d8869525a884d7c30deef:63601dd6802bdd6a6e1bded1d1e76a364ccef696f4fdabf00d133f2f034eeb6d23f847f1101d48bf9529045bbd0cb5f90d0a0c9978d6aeece89e8c896a0caa57)
Referer: https://www.gbif.org/species/3889108
Window size: width 1280 - height 893
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-23T13:32:44.566Z',mode:absolute,to:'2018-02-23T13:38:44.566Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-23T13:32:44.566Z',mode:absolute,to:'2018-02-23T13:38:44.566Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
In the 2019 version (http://www.catalogueoflife.org/col/details/species/id/957f7c0be4a8e53a2e2a6cf7b8f0d3e4) Rosmarinus officianlis L. is a synonym of Salvia rosmarinus Schleiden.
