### ISSUE TITLE
The name of the plant of this specimen is wrong.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1203]
**The name of the plant of this specimen is wrong.**

This is not a specimen of Rosa marretii H.Lev. but of Rosa manettii hort. raised by an Italian breeder, Giuseppe Manetti.

-----

User provided contact info: mikanagi@chiba-muse.or.jp
System: Chrome 49.0.2623 / Mac OS X 10.8.5
User: [See in registry](https://www.gbif.org/api/feedback/user/641b4fdf42483bc800efe8b556573c7e:8f79f6f60cdbbf7c359b87252d2a0bcfed3d043459c50c057d0553cb0f9553d43a9d3d6a69bae5530f0a01f321a54da078d071e2d4579c9bc0fed6fb401f4f7d)
Referer: https://www.gbif.org/occurrence/437763692
Window size: width 1057 - height 634
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-25T06:24:51.777Z',mode:absolute,to:'2018-02-25T06:30:51.777Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-25T06:24:51.777Z',mode:absolute,to:'2018-02-25T06:30:51.777Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The issue is being dealt with by email.

**Comment by ManonGros** [comment]
The publishers have updated the record.
