### ISSUE TITLE
Deleted species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1205]
**Deleted species**

Hi GBIF; 

I have come across species that have been deleted e.g. this one:  `https://www.gbif.org/species/8555288` 

What are the basis for deleting the species? The specific species with that specific autor is Grønlands Flora / Flora of Greenland Böcher et al 1978.
Would you be interested in this reference a checklist datasest?

Best, 
Ida

-----

User provided contact info: @IBDJ
System: IE 11.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/8a7f649a5d44175d27ff3fb051dafe31:4a2eceb1a5fe22f4bd6b5a5cd1fa29956d2934a81d2a5a7269324e609f62b7e038cb3a175f81dbbe4d3c8cecfa07cff7884405bde4ff406915bc3f2944efd64d)
Referer: https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
Window size: width 1920 - height 878
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-26T17:31:20.487Z',mode:absolute,to:'2018-02-26T17:37:20.487Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-26T17:31:20.487Z',mode:absolute,to:'2018-02-26T17:37:20.487Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Relates to #1709

**Comment by ManonGros** [comment]
@IBDJ, we have now a FAQ explaining why we delete some taxa: https://www.gbif.org/faq?question=why-do-some-taxa-show-as-being-deleted-what-does-this-mean

And yes, we are interested in getting the Floor of Greenland as a checklist. We could potentially integrate in into the next taxonomic update.
Would you be interested in sharing it as a checklist?

**Comment by kcopas** [comment]
@IBDJ are you based in Greenland? If so, depending on your role and location, a quick email correspondence might be extremely timely.

Could you send me a note at kcopas [at] gbif [dot] org , please, if you're willing?
KC
=====
Kyle Copas
Communications Manager
GBIF Secretariat
ORCID: 0000-0002-6590-599X

**Comment by IBDJ** [comment]
Hi @kcopas and @ManonGros I have sent you and email from my work adress. I hope you got it. Best, Ida

**Comment by jhnwllr** [comment]
I think this should be closed. The explanation is now in the FAQ. 
https://www.gbif.org/faq?question=why-do-some-taxa-show-as-being-deleted-what-does-this-mean

Additionally, 
**Juniperus communis subsp. alpina** seems to exist in other checklists so it is not really a data gap. Any additional issues ,such as authorship, I think should be put in a separate issue and re-worded. 
https://www.gbif.org/species/180134375
