### ISSUE TITLE
Absence records should be displayed more clearly

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal-feedback#1208]
"*Elanus caeruleus* (Desfontaines, 1789) observed in Norway"

```
| individual count  | 0      |
| occurrence status | absent |
```

Perhaps the subtitle needs rewording to "absence recorded" or similar.

See also https://github.com/gbif/portal16/issues/308 and https://github.com/gbif/portal-feedback/issues/1206

**Comment by MortenHofft** [comment]
Should be better now - but of course we could do much more throughout the site. But there are other issues for that
https://www.gbif.org/occurrence/1657415136

![screen shot 2018-02-27 at 10 00 26](https://user-images.githubusercontent.com/6759267/36719337-13a4b63c-1ba5-11e8-8020-e728c702ce46.png)

**Comment by MortenHofft** [comment]
There can be conflicting information on the record. e.g.

```
| individual count  | 0      |
| occurrence status | present |
```

```
| individual count  | 10      |
| occurrence status | absent |
```

what should we do in those situations? It is a data issue and a question of how many cases there is like that. I'm labelling it for data product

**Comment by MattBlissett** [comment]
That's probably something that should be intepreted, and be given an issue.

**Comment by MattBlissett** [comment]
This will now be handled in https://github.com/gbif/pipelines/issues/268
