### ISSUE TITLE
Multimedia interpretation looks to be wrong

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#1209]
http://api.gbif.org/v1/occurrence/1680301813/fragment is having image identifiers
```
"extensions": {
"gbif:Multimedia": [
{
"creator": "Jørgen Kabel",
"format": "StillImage",
"identifier": "https://dofbasen.dk/image_proxy.php?mode=o&pic=12592079_1.jpg",
"license": "https://creativecommons.org/licenses/by-nc/4.0/",
"rightsHolder": "Jørgen Kabel",
"type": "image/jpeg"
},
...
]
}
```
but ends up as 
http://api.gbif.org/v1/occurrence/1680301813 
```
{
"references": "https://dofbasen.dk/image_proxy.php?mode=o&pic=12592079_1.jpg",
"creator": "Jørgen Kabel",
"license": "https://creativecommons.org/licenses/by-nc/4.0/",
"rightsHolder": "Jørgen Kabel"
}
```

that is missing the identifier and mapping it to reference. As a result it shows weird on the site:
https://www.gbif.org/occurrence/1680301813

**Comment by MattBlissett** [comment]
Two terms are mapped the wrong way round.

```
        "format": "StillImage",
        "type": "image/jpeg"
```

This should be

```
        "format": "image/jpeg"
        "type": "StillImage",
```

Although we ignore type, so just

```
        "format": "image/jpeg"
```

is sufficient.

Without the format being a valid, understood MIME type, the parser assumes the worst and thinks it's an HTML page describing the media, rather than a link to an actual media object.
