### ISSUE TITLE
Activity tab for new dataset pages to list derived publications based on DOIs

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#121]
**Activity tab for new dataset pages to list derived publications based on DOIs**

Using this example https://demo.gbif.org/dataset/b267ac9b-6516-458e-bea7-7643842187f7, I would like to suggest that Activity tab, when added, would primarily list publications where one or more records from the dataset contributed to the cited DOI for a download.

Perhaps, featured published uses, external portal uses and policy uses can be manually flagged as featured and brought to top (see how ResearchGate does it for illustration of the idea https://www.researchgate.net/profile/David_Hawksworth)

It would match the open data profile of GBIF, if we would separate open data papers from the rest, scroll down for an example from GloBI http://www.globalbioticinteractions.org/about.html

The download activity could be useful, but less illustrative for concrete uses http://www.gbif.org/dataset/b267ac9b-6516-458e-bea7-7643842187f7/activity

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c
Reported by: @dschigel
System: Firefox 51.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/dataset/search
Window size: width 1760 - height 758
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-08T13:38:32.442Z',mode:absolute,to:'2017-03-08T13:44:32.442Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-08T13:38:32.442Z',mode:absolute,to:'2017-03-08T13:44:32.442Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dschigel** [comment]
Duplicate, thanks @kbraak. Ideas moved to https://github.com/gbif/portal16/issues/307 and closed.
