### ISSUE TITLE
Counts are wrong

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1210]
**Counts are wrong**

Dataset counts are wrong on this page.  E.g. it shows 611M records for eBird, when eBird has only 361M records

-----

User provided contact info: @timrobertson100
System: Chrome 64.0.3282 / Mac OS X 10.11.5
User: [See in registry](https://www.gbif.org/api/feedback/user/5410dbb422c16b829efd9064003db3fb:535671750a86ace5d20238bc464660d0fa3ee693fccca7b896f5ca3c6ecad851493e82af31c9abce4fec399b07cf3086440f55fece3c0f56d291b4a06e2670fc)
Referer: https://www.gbif.org/occurrence/download/0011663-180131172636756
Window size: width 1583 - height 949
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-27T18:33:10.276Z',mode:absolute,to:'2018-02-27T18:39:10.276Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-27T18:33:10.276Z',mode:absolute,to:'2018-02-27T18:39:10.276Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by timrobertson100** [comment]
For info, the email had:
```
Download Information:
    DOI: https://doi.org/10.15468/dl.9uasis (may take some hours before being active)
    Creation Date: Tuesday, 27 February 2018 17:48:16 o'clock GMT
    Records included: 487336089 records from 10 published datasets
    Data size: 86.7 GB
    Download format: DWCA
    Filter used: DatasetKey: EOD - eBird Observation Dataset or Artportalen (Swedish Species Observation System) or DOF or Norwegian Species Observation Service or Finnish Bird Ringing and Recovery Database or BirdLife Australia, Birdata or Southern African Bird Atlas Project 2: Full protocol records or Anillamiento SEO_Bird ringing or Great Backyard Bird Count or Bird tracking - GPS tracking of Lesser Black-backed Gulls and Herring Gulls breeding at the southern North Sea coast
TaxonKey: Aves
```

which had the correct count

**Comment by MortenHofft** [comment]
611M is the count from the API
http://api.gbif.org/v1/occurrence/download/0011663-180131172636756/datasets

**Comment by timrobertson100** [comment]
They are wrong in the registry DB.  
This issue must lie in the occurrence download workflow.

SQL showing the incorrect values in the registry:
```
SELECT * FROM dataset_occurrence_download 
WHERE download_key='0011663-180131172636756'
```

**Comment by MattBlissett** [comment]
That's two problems with the download workflow.  https://github.com/gbif/portal-feedback/issues/1061 is also something that should be investigated.

**Comment by MattBlissett** [comment]
Most likely also fixed by https://github.com/gbif/occurrence/issues/28
