### ISSUE TITLE
Unlikely elevation

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#1212]
**content**
250K plants and fungi above 9900m
That sounds unlikely.

**api**
We have a flag for unlikely - shouldn't it be set? Currently `elevation unlikely == 0`

https://www.gbif.org/occurrence/datasets?elevation=9900,9999&taxon_key=6&taxon_key=5&advanced=1

**Comment by MattBlissett** [comment]
It could, but we don't have the taxonomy as context when interpreting the elevation. The limit is 17km for everything: https://github.com/gbif/parsers/blob/master/src/main/java/org/gbif/common/parsers/geospatial/MeterRangeParser.java#L80

All but 54 of them have elevation=9999, presumably some placeholder for "unknown". The 54 will mostly be where the measurement is in feet, we detect and convert the value if "ft" is present, but otherwise don't.

https://www.gbif.org/occurrence/datasets?elevation=9900,9998&taxon_key=6&taxon_key=5&advanced=1

**Comment by MortenHofft** [comment]
@fmendezh In that case a suggestion for the new pipeline. Consider taxonomy when flagging elevation issues. I'm removing the API label as I consider it a `won't fix for now`

**Comment by MattBlissett** [comment]
For georeferenced occurrences, we can even consider location.

**Comment by ManonGros** [comment]
It looks like Species Links is using 9999 as default value for some of the datasets that they host (see list below).
I contacted them by email.
* [UB - Herbário da Universidade de Brasília](https://www.gbif.org/dataset/d82d5a18-0428-4e52-be16-f509153e8126)
* [URM - Herbário Pe. Camille Torrand](https://www.gbif.org/dataset/23b714b1-fae6-4074-bdd0-5e17ae3b5f11)
* [SMDB - Santa Maria Departamento de Biologia](https://www.gbif.org/dataset/2deca60c-f147-417f-9af4-b52067589e99)
* [EAFM - Herbário do Instituto Federal de Educação, Ciência e Tecnologia do Amazonas](https://www.gbif.org/dataset/7aeb3ded-7443-4512-95f7-2ec7ab0f308c)
* [JPB - Herbário Lauro Pires Xavier](https://www.gbif.org/dataset/c9bc6b8d-a4ff-4a47-9cff-d0d1b9e548c7)
* [HUEG - Herbário da Universidade Estadual de Goiás](https://www.gbif.org/dataset/bbb1f181-3221-4a10-ad52-14f1da0dca26)
* [HUCO - Herbário da Universidade Estadual do Centro-Oeste](https://www.gbif.org/dataset/1a86be2b-aa83-424a-9e55-9f6ee344fdfc)
* [MFS - Herbário Profª. Drª. Marlene Freitas da Silva](https://www.gbif.org/dataset/0c00cc8f-fd48-4771-acae-216bfc42dfc2)
* [IRAI - Herbário do Parque da Ciência Newton Freire Maia](https://www.gbif.org/dataset/df761c30-988d-4ff8-b7d4-b24ff51c0c8d)
* [DVPR - Herbário da Universidade Tecnológica Federal do Paraná - Dois Vizinhos](https://www.gbif.org/dataset/0ec3229f-2b53-484e-817a-de8ceb1fce2b)
* [HUTO - Herbário da Universidade de Tocantins](https://www.gbif.org/dataset/965b5ae5-7b2d-4155-a7ff-e9e496d70f90)
* [UFRN-Fungos - Herbário UFRN - Fungos](https://www.gbif.org/dataset/54e9fbce-ed69-49b8-b240-c7450fb449e0)
* [FUEL - Herbário da Universidade Estadual de Londrina](https://www.gbif.org/dataset/78dcee36-b0a2-4679-802d-bc0b5016518b)
* [HUCPE - Herbário da Universidade Católica de Pernambuco](https://www.gbif.org/dataset/a59636ef-6028-4fa4-8895-553ba8af3b02)

**Comment by ManonGros** [comment]
the Species Links issue is fixed and we are working with Burke university to republish a new version of their dataset.
