### ISSUE TITLE
Reptilian birds

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1213]
If one looks at the taxonomy tab of occurrences and views the most observed/collected Reptiles, the first four are birds: https://www.gbif.org/occurrence/taxonomy?taxon_key=358

I know we know birds are living dinosaurs, but i’m surprised to see killdeer, semipalmated plovers, and others show up as such here. Highlighting for you @mdoering ?

**Comment by mdoering** [comment]
Thanks Kyle, strange. Looks like CoL has these genera like Charadrius twice:
https://www.gbif.org/species/search?q=Charadrius&dataset_key=7ddf754f-d193-4cc9-b351-99906754a03b&advanced=1

Hence we also end up with 2 copies of that genus: https://www.gbif.org/species/search?q=Charadrius&rank=GENUS&dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&advanced=1

**Comment by mdoering** [comment]
Reported to CoL with reply:

> We will fix the issue in March edition. Plus we will do checks for duplicated genera which help to find other possibly misplaced genera.
>  
> It looks like our supposed to be routine checks for duplicates failed.
>

**Comment by mdoering** [comment]
See also https://twitter.com/CamiSilver/status/988892386179862534

![screen shot 2018-04-25 at 09 43 49](https://user-images.githubusercontent.com/327505/39232500-d86843b8-486d-11e8-9a1e-33c9fd12a647.jpg)

**Comment by mdoering** [comment]
Glad to say this is fixed in the upcoming backbone. There is only one bird genus and all occurrences attach to it:
https://www.gbif-uat.org/species/search?q=Charadrius&rank=GENUS&dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&advanced=1

**Comment by mdoering** [comment]
Fixed for Charadrius & Crypturellus
But Dromaius, Gygis, Oceanodroma still have a reptile brother which is flagged as doubtful and therefore only gets very little ocurrences matched. They could even be good matches, but not checked

**Comment by timhirsch** [comment]
yay! Even if they are all dinosaurs, really ;)

**Comment by mdoering** [comment]
The total reptile occurrence numbers are also halfed from over 10 million down to 5.

Before:
<img width="1176" alt="screen shot 2018-07-04 at 12 52 09" src="https://user-images.githubusercontent.com/327505/42273357-38b34928-7f89-11e8-858c-16e907a808f1.png">

New:
<img width="1175" alt="screen shot 2018-07-04 at 12 52 18" src="https://user-images.githubusercontent.com/327505/42273352-36104806-7f89-11e8-95cb-1637ba1054bf.png">
