### ISSUE TITLE
Synonym/misspelling: Bembidium assimile

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1216]
**Synonym/misspelling: Bembidium assimile**

`https://www.gbif.org/species/8827816`  is  a synonym/misspelling of `https://www.gbif.org/species/5872148,` not an accepted species?

-----

User provided contact info: @oskarlphansen
System: Chrome 61.0.3163 / Linux 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/864c2f6c75ba7d4fd42ad35cfb3b5e31:d539fb53139c7d1a89fea47f384f6d56a4f95337080e11e6406efa82902cc15fb26b0002327529121fa604574b285ee24a5d2a2000d8f1588f2c0c1ab413f065)
Referer: https://www.gbif.org/species/8827816
Window size: width 960 - height 1082
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-28T18:35:44.204Z',mode:absolute,to:'2018-02-28T18:41:44.204Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-28T18:35:44.204Z',mode:absolute,to:'2018-02-28T18:41:44.204Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by yroskov** [comment]
Do not see mistake in the CoL: http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/04495afe3fc018cb7513673145bd00e5

It looks like, misspelling "Bembidium" for the genus Bembidion widely occurs in various publications. If user comment will be specified, it might be passed to GSD.

**Comment by ManonGros** [comment]
It looks like this has been solved in the new backbone.
