### ISSUE TITLE
Allowed to download unique species names

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#122]
**Allowed to download unique species names**

It would be great if we could download species checklist data instead of all occurrences from one country.

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
Reported by: @Maofangisme
System: Chrome 56.0.2924 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/download?country=CN
Window size: width 1920 - height 1094
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-08T13:41:59.852Z',mode:absolute,to:'2017-03-08T13:47:59.852Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-08T13:41:59.852Z',mode:absolute,to:'2017-03-08T13:47:59.852Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
related to #529

**Comment by MattBlissett** [comment]
This is implemented (some months ago now) with the SPECIES_LIST type download.
