### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#123]
**Reset password**

Too many passwords nowadays. It takes some time to get the email from the system to reset password. It would be more convenient if the waiting time could be shortened. Thanks.

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
Reported by: @Maofangisme
System: Chrome 56.0.2924 / Windows 10 0.0.0
Referer: https://demo.gbif.org/
Window size: width 1920 - height 1094
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-08T14:11:47.266Z',mode:absolute,to:'2017-03-08T14:17:47.266Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-08T14:11:47.266Z',mode:absolute,to:'2017-03-08T14:17:47.266Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
There's no waiting time on GBIF's servers, all emails are sent instantly.  Is this to an @gbif.org address? I don't see any password reset emails going through the system to a @gbif.org address today.

**Comment by Maofangisme** [comment]
Thanks, Matt. My mistake. I was in the new demo and did not go back. I received email to reset password but it seemed I lost into a circle of that. 

The link led to the type in my email address and verify I'm not a robot. It kept told me that "You have tried to use a one-time login link that has either been used or is no longer valid. Please request a new one using the form below." Then I followed and clicked the reset button. Another link was sent to me, which showed me the same information... Maybe I should try it again some time later.

**Comment by MortenHofft** [comment]
Hi Maofang. Did you get it to work? As it isn't related to the new portal i will close this issue. But of course it should be possible to reset passwords on the existing site. Let me know if it still fails. We are in the process of creating a new way of reseting and creating accounts for the new site. You will be the first person I ask to test it :) thanks

**Comment by Maofangisme** [comment]
Dear Morten,


Good morning!


No problem. Matt and Tim helped me to solve this.


I also tried to log in with email address, but it works well when I use my user name instead of email address. Thank you very much for asking.


Have a nice day.


Maofang



________________________________
