### ISSUE TITLE
Duplicate MadBIF datasets

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal-feedback#1234]
https://www.gbif.org/dataset/bf6810a4-befd-4f0b-82f9-c20c0ce11531 is an old version of https://www.gbif.org/dataset/e6751193-fafa-4aae-a0c2-f2f1a93172ca , which can no longer be accessed.

https://www.gbif.org/dataset/a5dd8cc3-7971-4b3c-a75c-d345940572bd is an old version of https://www.gbif.org/dataset/4c1bc8db-584e-4d69-bf8c-9221ff5bbb34

@jlegind, did you have something to move the citations over?

**Comment by ManonGros** [comment]
I contacted the publishers about tan-databases.

**Comment by ManonGros** [comment]
The tan-database duplicate was deleted after checking with the publisher.
