### ISSUE TITLE
Details about Naturalis are missing on participant webpage

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1237]
**Details about Naturalis are missing on participant webpage**

Colleagues of me pointed out that on the Associate Participant page on the GBIF website, details on published datasets and publishers of Naturalis are lacking.

I checked this with the page of Canadensys that obtained the associated participant status at the same time as Naturalis:
Naturalis: `https://www.gbif.org/participant/364`
Canadensys: `https://www.gbif.org/participant/365`

At the Canadensys page datasets and publishers are shown as expected. What do we wrong? 

We publish through 2 HTTP installations and details about Naturalis as a publisher can be found here:
`https://www.gbif.org/publisher/396d5f30-dea9-11db-8ab4-b8a03c50a862`

Jeroen Creuwels
Data manager Naturalis

-----

System: Chrome 64.0.3282 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/c02c026d69f584249acb0b6a9cd08595:3979b4d2b77e4bc3ebef0da58bb6055f2865a7d22dccb566af5d7711b4f022b46cfac16429f83c352d1bb67dfe717d22012a8a180c1827cbd05224b18656f363)
Referer: https://www.gbif.org/publisher/396d5f30-dea9-11db-8ab4-b8a03c50a862
Window size: width 1920 - height 959
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-07T09:54:22.669Z',mode:absolute,to:'2018-03-07T10:00:22.669Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-07T09:54:22.669Z',mode:absolute,to:'2018-03-07T10:00:22.669Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
I assume this is simply because the [Naturalis publisher entity](https://www.gbif.org/publisher/396d5f30-dea9-11db-8ab4-b8a03c50a862) isn't endorsed by the [Naturalis associate participant](https://www.gbif.org/participant/364), but rather by [Netherlands Biodiversity Information Facility](https://www.gbif.org/node/0909d601-bda2-42df-9e63-a6d51847ebce), as Naturalis became a publisher long before becoming a participant...

**Comment by ahahn-gbif** [comment]
Checking with the publisher whether rewiring the endorsement from NLBIF to Naturalis is required (see helpdesk)

**Comment by ahahn-gbif** [comment]
Received confirmation from Naturalis that, based on discussion with NLBIF, they prefer to leave the situation unchanged, keeping endorsement with the country node (NLBIF). Received 12/06/18, forwarded to helpdesk@ 2/10/18. Closing
