### ISSUE TITLE
replace KB as technical contact on the BID IPT installation

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1239]
**replace KB as technical contact on the BID IPT installation**

Not sure who should be listed here?

-----

User provided contact info: @dnoesgaard
System: Chrome 64.0.3282 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/50bf8dceb3b847abad416b84dac99afb:ef78784b0746e1e0f937ffbd4809b72595b4af35c6d33b8fbfc29dd42f4b86bdb63344ebe3ecf0374df851636eefd664a8223e2dc0bee3ea86db96d01be4c312)
Referer: https://www.gbif.org/installation/0213a1ce-cdd7-44fd-b4de-89ca889a7070
Window size: width 1707 - height 923
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-07T13:39:51.822Z',mode:absolute,to:'2018-03-07T13:45:51.822Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-07T13:39:51.822Z',mode:absolute,to:'2018-03-07T13:45:51.822Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
The helpdesk. Done.
