### ISSUE TITLE
Almost empty events

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1243]
**Almost empty events**

`https://www.gbif.org/event/62bHEFPbgImWwSigmukKIi/european-nodes-meeting`

Seems a bit silly to publish an event with this little information doesn't it? There are several like this

-----

User provided contact info: @MortenHofft
System: Chrome 64.0.3282 / Mac OS X 10.11.6
User: [See in registry](https://www.gbif.org/api/feedback/user/59ba5a694c409dbad9eb2032469384f4:f2accdf480333d8048c6d29d6216035d767c352af3dd54178c13c6fd804fdb7f520510dfbf4ade4d4df33c91377fb8bb0f4b06228ea214c7e9fe6b72813832aa)
Referer: https://www.gbif.org/event/62bHEFPbgImWwSigmukKIi/european-nodes-meeting
Window size: width 1918 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-08T07:37:44.946Z',mode:absolute,to:'2018-03-08T07:43:44.946Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-08T07:37:44.946Z',mode:absolute,to:'2018-03-08T07:43:44.946Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Yes. But I guess such events are added whenever the dates are set to allow people to see them asap even if the agenda, description, etc isn't at all ready. I can talk to admin about putting a standard placeholder text, e.g. agenda pending, tba, etc.

**Comment by MortenHofft** [comment]
makes sense. other examples

https://www.gbif.org/event/4ppM18SiSIG6KGo0Gu66gQ/un-biodiversity-conference

https://www.gbif.org/event/48Z8GFqGuk04UG8AUOQMEo/gbic2-the-2nd-global-biodiversity-information-conference

no links no descriptions.

**Comment by dnoesgaard** [comment]
Mail to Admin:

> Dear Anne Mette,
>  
> Morten pointed out that we have an increasing number of (almost) “empty” events on the website, i.e. events with no other information than a title, date and perhaps location. When these are in fact GBIF events, i.e. we don’t have another website to link to, I’m sure they are added simply as a means of saving the date. However, I’d like to see a little more content if even simply a placeholder text in those cases. I’ve updated the event for the European Nodes Meeting as an example:
>  
> https://www.gbif.org/event/62bHEFPbgImWwSigmukKIi/european-nodes-meeting
>  
> Placeholder text:
> The details/agenda of this event is still pending. Please return to this page at a later date for more information. For questions regarding the event, please contact [name/email](mailto:emailaddress).
>  
> If you agree, could you pass this on to your team?

**Comment by kcopas** [comment]
I know nothing of the UN biodiversity conference, but the other two are internal events that did in fact need stubs, in the vein of save-the-dates. The suggestion of dropping in a standard placeholder is good, but don't knock Admin for the practice of going thin on details.

**Comment by dnoesgaard** [comment]
I added some meat to the UN event.

I also spoke to Anne Mette and Sanja, and they've already started adding the placeholder.
