### ISSUE TITLE
Clio pyramidiata in the wrong family

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1244]
**Clio pyramidiata in the wrong family**

Possibly typo, should be in Cliidae, not Ciidae

-----

User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/866ca8a59be0f6cbfc184cb5c8b250fd:bc0ea2f2f7fad28f54de361e928342e5bd538ddc60d431d97a21c500f70ee76edd79bbe0fd48167b5da31aa8729c84dc37b081b17156eb809b70f63aa546797e)
Referer: https://www.gbif.org/occurrence/taxonomy?q=Ciidae
Window size: width 1920 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-08T09:27:14.090Z',mode:absolute,to:'2018-03-08T09:33:14.090Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-08T09:27:14.090Z',mode:absolute,to:'2018-03-08T09:33:14.090Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I'm not sure I understand. Who says it is in Ciidae?
https://www.gbif.org/species/2293864

You have done a free text query letters "Ciidae" - if you wish to filter for the family `Ciidae` the scientific name filter is the way to go. It also try to help you by asking you if you meant to do a structured search.

![screen shot 2018-03-08 at 13 22 27](https://user-images.githubusercontent.com/6759267/37150915-d6642970-22d3-11e8-876a-3030670cfb43.png)

looking at the list of distinct species within your free text search also says Cliidae

![screen shot 2018-03-08 at 13 23 17](https://user-images.githubusercontent.com/6759267/37150963-feef7656-22d3-11e8-8353-851f8873d228.png)

Let me know if you have suggestions for this should be easer to use or if I'm misunderstanding what you mean.
