### ISSUE TITLE
encoding issue with maps

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1248]
**encoding issue with maps**

Seeing some strange characters on maps of Morocco. Looks like we're unable to display Moroccan Amazigh correctly?

-----

User provided contact info: @dnoesgaard
System: Chrome 64.0.3282 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/1315ef886945f9d7e61462543d46adac:ab65fc62e10861ebe41f5e72b9dd2f3335f1ae77caf267c01b0735411f2f03ee2fe15397ebc826b38cad483bdce1f017fa2a36644f28a82cf279efc8f20d5ddf)
Referer: https://www.gbif.org/occurrence/search?geometry=POLYGON((-20.666689351201057%2018.755800900843596,0.0573053956031793%2018.755800900843596,0.0573053956031793%2037.57613890301403,-20.666689351201057%2037.57613890301403,-20.666689351201057%2018.755800900843596))
Window size: width 1631 - height 953
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-09T12:00:10.492Z',mode:absolute,to:'2018-03-09T12:06:10.492Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-09T12:00:10.492Z',mode:absolute,to:'2018-03-09T12:06:10.492Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
![screen shot 2018-03-09 at 13 06 36](https://user-images.githubusercontent.com/21358085/37206878-c0a5385a-239a-11e8-9eaa-6a5f94166722.png)

**Comment by dnoesgaard** [comment]
From Open Street Maps:

![screen shot 2018-03-09 at 13 08 23](https://user-images.githubusercontent.com/21358085/37206959-05edd76e-239b-11e8-99cb-d3377238953f.png)

**Comment by MattBlissett** [comment]
Correct, and I did have a fix to use the correct font, but we decided a while ago to use English labels on maps anyway.

**Comment by MortenHofft** [comment]
@thomasstjerne assigning to you as this is a chance to look at something you haven't already. The basemap styles are created here:
https://github.com/gbif/gbif-basemaps/blob/master/raster-basemap-server/src/main/node/styles.js
