### ISSUE TITLE
Are pelicans are now dinosaurs?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1249]
**Are pelicans are now dinosaurs?**

We noticed yesterday that a number of bird genera are now considered dinosaurs (Reptilia, Dinosauria). Is this for real?

(cc @mdoering)

-----

User provided contact info: @dnoesgaard
System: Chrome 64.0.3282 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/efa55fede42d54f6d1a7addbd011d3d6:cdeb946d719397b0f4f6f7ba3799d983ef1a8284a1432a94be266449652d8c202f844bfeea62139ae68ef1aee410ded39ba7c0b4390047a8c8c707a88a173209)
Referer: https://www.gbif.org/occurrence/gallery?taxon_key=9369825
Window size: width 1631 - height 953
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-09T12:15:10.172Z',mode:absolute,to:'2018-03-09T12:21:10.172Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-09T12:15:10.172Z',mode:absolute,to:'2018-03-09T12:21:10.172Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Also Charadrius, Crypturellus, Dromaius, Gygis, Oceanodroma...

**Comment by mdoering** [comment]
Apparently yes, see #1213 and please continue there
