### ISSUE TITLE
Links to "occurrences" and "species" are not working

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#125]
**Links to &quot;occurrences&quot; and &quot;species&quot; are not working**

From the dataset page, if we click on &quot;occurrences&quot; or &quot;species&quot; we get a 404.

-----
fbitem-dataset8d431c96-9e2f-4249-8b0a-d875e3273908
Reported by: @cgendreau
System: Chrome 56.0.2924 / Mac OS X 10.10.5
Referer: https://demo.gbif.org/dataset/8d431c96-9e2f-4249-8b0a-d875e3273908/
Window size: width 1440 - height 739
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-13T12:49:35.117Z',mode:absolute,to:'2017-03-13T12:55:35.117Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-13T12:49:35.117Z',mode:absolute,to:'2017-03-13T12:55:35.117Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
Actually, it points to
https://demo.gbif.org/dataset/occurrence/search?dataset_key=8d431c96-9e2f-4249-8b0a-d875e3273908

while it should points to https://demo.gbif.org/occurrence/search?dataset_key=8d431c96-9e2f-4249-8b0a-d875e3273908 (without the dataset/ part)
