### ISSUE TITLE
dubious records of Onobrychis arenaria

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1251]
**dubious records of Onobrychis arenaria**

`https://www.gbif.org/occurrence/search?geometry=POLYGON((1.56386%2050.00552,1.56386%2052.57632,7.99086%2052.57632,7.99086%2050.00552,1.56386%2050.00552))&has_coordinate=true&has_geospatial_issue=false&taxon_key=2972841`

The above occurences are highy dubious and should at least be tagged as being so!. There is no known expert-checked record for this species northwest of Bingen am Rhein in Rhineland-Palatinate. Narrow-leaved types of Onobrychis viciifolia are sometimes mistaken for O. arenaria when not taking into account fruit morphology.

Admitted, there is a slight possibility of the species being used (which I deem a quite irresposbile idea) in "greening"-seed mixtures for vineyards. Then again cultivated species, in my mind, should not be part of the GBIF-Dataset.

-----

User provided contact info: @hanselmannd
System: Firefox 58.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/24df90a84f36540e36e3a218f9d7f546:e8eb71a6c74f6a8b63f0ef034780b60d9a49ca2c00b1c5015b67435fcfaf065e11134685602db3cbb58efb0624e61d72f0ec28f39ba4a27e205ac547b159dbd0)
Referer: https://www.gbif.org/occurrence/search?geometry=POLYGON((1.56386%2050.00552,1.56386%2052.57632,7.99086%2052.57632,7.99086%2050.00552,1.56386%2050.00552))&has_coordinate=true&has_geospatial_issue=false&taxon_key=2972841
Window size: width 2560 - height 1303
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-10T18:06:13.277Z',mode:absolute,to:'2018-03-10T18:12:13.277Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-10T18:06:13.277Z',mode:absolute,to:'2018-03-10T18:12:13.277Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Note that two or the main contributing datasets are currently not indexed on a regular basis (see #1241 for one of them)

**Comment by aallspac** [comment]
The publisher received the message, is working on troubleshooting

**Comment by MortenHofft** [comment]
The first error is the polygon. The provided polygon is clockwise and hence a hole in the world asking for anything not in Belgium.

the second is that the interface doesn't warn you about the mistake.

The third is that the map/table/count interprets the unusual polygon differently.

**Comment by ManonGros** [comment]
We got a reply from one of the publishers (Senckenberg):
this particular collection is correctly  georeferenced and displayed in both our database as in GBIF and does not at all originate from NW of Bingen as the user suggested. In fact it is from NE of Bingen (Bad Frankenhausen, Thuringia) and fits well into the normal areal of this species which prefers warm and sunny habitats in the Main valley and the Kyffaeuser area in Germany e.g.
see: http://www.floraweb.de/webkarten/karte.html?taxnr=10685
 
The ones in GBIF from NW of Bingen (Loreley, NSG Sistig-Krekeler Heide, Wälder bei Nordkirchen) are all records from GEO Tag der Artenvielfalt observations (most likely unvouchered) an should be considered with great care. But none of these is a voucher in our collection.

**Comment by Cubey0** [comment]
I have contracted the wild collector of the material and they will look again at the material. Thank you for you feedback.
