### ISSUE TITLE
Registered dataset with no endpoint

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1254]
**Registered dataset with no endpoint**

Possibly an intermittent problem with our API at the moment of registration, possibly a bug on Plazi's end.

Could Plazi either fix it, or delete/ask us to delete it.

-----

User provided contact info: @MattBlissett
System: Firefox 57.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/1c112b5a13ddcb999022b673acd9baf4:2ce8c276d756efaf8b551ff881892148fc27c4f3925ea87d3f32665c96a5abcb3c9ba2fe59485a6077b5e50ccdb835d9633898bc628674d34dd3e3e4a53c3d68)
Referer: https://www.gbif.org/dataset/14c4213d-3a05-4ef8-8de9-369397be5710
Window size: width 1200 - height 1792
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-12T10:59:01.628Z',mode:absolute,to:'2018-03-12T11:05:01.628Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-12T10:59:01.628Z',mode:absolute,to:'2018-03-12T11:05:01.628Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publisher has been contacted.

**Comment by ManonGros** [comment]
The publishers said to delete this dataset and that a new one would be made with a valid endpoint should the DwC-A be exported again.
