### ISSUE TITLE
(some) literature topic counters are zero

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1256]
**literature topic counters are zero**

In the Topic facet of literature, we only show counts for the top 10 topics (it seems) - presumably because that's what the api returns...?

-----

User provided contact info: @dnoesgaard
System: Chrome 64.0.3282 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/135694e42c40d90ae68d1659d03bb4cd:be81e599ac0b3547cea3edc217b3feec25e096b6f97c07404ac50cf8ac7bf6cefeb3fd8d8f04cf0e3d35133696b7a9b6f868876b66a6d82dac836241537e5f76)
Referer: https://www.gbif.org/resource/search?contentType=literature&topics=BIODIVERSITY_SCIENCE
Window size: width 1694 - height 952
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-12T16:10:42.971Z',mode:absolute,to:'2018-03-12T16:16:42.971Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-12T16:10:42.971Z',mode:absolute,to:'2018-03-12T16:16:42.971Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
If i remember correctly that have been changed from top 10 to show all on your request. Seemingly that was only partly completed.
