### ISSUE TITLE
Gammanema magnum , Shi, Benze & Xu, Kuidong, 2018 is not In Press anymore

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1259]
**Gammanema magnum , Shi, Benze &amp; Xu, Kuidong, 2018 is not In Press anymore**

Backbone contains "In Press" authors.
This is temporary and maybe does not belong into the authorship. 

Should the backbone remove the In Press, keep it until the next backbone is built or exclude in press names alltogether?

Reported by Plazi:
`http://treatment.plazi.org/id/03A287D591391E05FDBC8F75FB2AE10D`

-----

User provided contact info: mdoering@gbif.org
System: Chrome 64.0.3282 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/086a2ddbb52d88063777ab7873fa159c:0f88abc4964050e28e1271eca378d0e00836f9cca792daa0969ff769229aeb2c6fb7642eeaf013d9e21dded330b10add0414e207edc7af1757f4b4bc267ea8e2)
Referer: https://www.gbif.org/species/9496677
Window size: width 1628 - height 976
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-13T10:26:03.682Z',mode:absolute,to:'2018-03-13T10:32:03.682Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-13T10:26:03.682Z',mode:absolute,to:'2018-03-13T10:32:03.682Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
I did not check the Codes, but from the memory the names become valid from the paper's publication date onwards.  If so, we should possibly avoid adding In Press names until they are validly published. If (as discussed with Arthur Chapman) we have provisional names of all sorts handled by the backbone, this is where In Press names belong. My choice would be simply delay additions of those names to the next versions of Backbone, until those are valid.

**Comment by ManonGros** [comment]
It seems like the authors are now correct for this species.
