### ISSUE TITLE
no insect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1260]
**no insect**

this species belongs to crustacea

-----

System: Firefox 52.0.0 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4be60a09723ff2535975f6904a6ced95:71e2927c84f66a7bce8f61d79beb94b2f009f5adddcef7b3ca73670ff1cfe518917cbbfb2facf85adb9cc108fd0d723213033a8df1962ee6d8ccd390f92aca3f)
Referer: https://www.gbif.org/occurrence/207826463
Window size: width 1956 - height 991
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-13T14:07:50.436Z',mode:absolute,to:'2018-03-13T14:13:50.436Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-13T14:07:50.436Z',mode:absolute,to:'2018-03-13T14:13:50.436Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by aallspac** [comment]
dahalacensis belongs to the genus Leptestheria:
https://www.gbif.org/species/2234680

**Comment by aallspac** [comment]
is it difficult to change the systematic backbone entries? 
Leptestheria belongs to Crustacea!

**Comment by jhnwllr** [comment]
Seems to be fixed. 
https://www.gbif.org/species/2234680
