### ISSUE TITLE
County by kingdom and by higher taxon don't line up

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1262]
**County by kingdom and by higher taxon don&#39;t line up**

The metrics for WoRMS show no plants at all in te number of accepted species by higher taxon pie. Under count by kingdom it is the 3rd largest group with ~2000 taxa

-----

User provided contact info: mdoering@gbif.org
System: Chrome 64.0.3282 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/90d0e7607e5cc9ff6cec9a63ee72d562:086ecaa12b4964f3079c345fc166dcbbb6fa2692a16f7513a5b1393ac3c134c373860c53838dcd8dd113a793757d3362ef791a1052e90695dca5e3cf729659c9)
Referer: https://www.gbif.org/dataset/2d59e5db-57ad-41ff-97d6-11f5fb264527/metrics
Window size: width 1628 - height 893
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-14T06:04:40.910Z',mode:absolute,to:'2018-03-14T06:10:40.910Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-14T06:04:40.910Z',mode:absolute,to:'2018-03-14T06:10:40.910Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@mdoering plants are shown in the pie. it is just a very small slice. because ther isn't many i suppose. And there isn't around 2000 taxa but 4520. It is alogarithmic scale. Let me know if I'm misunderstanding what you mean.

![screen shot 2018-03-14 at 10 10 09](https://user-images.githubusercontent.com/6759267/37392928-edb27140-276f-11e8-8cd8-74ef6fa460c0.png)

![screen shot 2018-03-14 at 10 12 56](https://user-images.githubusercontent.com/6759267/37393051-4fc21b6a-2770-11e8-888f-493c42353b8c.png)

**Comment by mdoering** [comment]
well, in the pie it says 698 Plantae species, by kingdom 4520 taxa. There are more taxa than accepted species as infraspecific taxa are included, but does that account for 3822 taxa?

Well, not infraspecific but apparently lots of genera:
https://www.gbif.org/species/search?rank=GENUS&dataset_key=2d59e5db-57ad-41ff-97d6-11f5fb264527&highertaxon_key=106339411&status=ACCEPTED&advanced=1

Ignore me then, I should have looked before
