### ISSUE TITLE
Remove acknowledgement of Jetbrains

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1263]
**Remove acknowledgement of Jetbrains**

JetBrains have changed their policy towards OSS and no longer consider GBIF projects eligible for support after 6 years of doing so.  

For accuracy we should remove them from this page.

-----

User provided contact info: @timrobertson100
System: Chrome 64.0.3282 / Mac OS X 10.11.5
User: [See in registry](https://www.gbif.org/api/feedback/user/c5290715bce9a2d15bd385a719fbb9c5:19ba4e620748211dc36e8cc4a0c5a8582f52147cc522560aece020fdbef42ca8b750749d19c8ca190958ab370d3f889a9e3e9fa16c782ec837c953a28604b491)
Referer: https://www.gbif.org/acknowledgements
Window size: width 1805 - height 1099
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-14T13:24:07.176Z',mode:absolute,to:'2018-03-14T13:30:07.176Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-14T13:24:07.176Z',mode:absolute,to:'2018-03-14T13:30:07.176Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Removed.
