### ISSUE TITLE
broken link "a community consultation" (404)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1264]
**broken link &quot;a community consultation&quot; (404)**

The second paragraph point at "a community consultation" (`https://www.gbif.org/newsroom/consultations#licensing),` which gives a 404. Do we still have that document public, or could we pull it back in? I am about to send some licensing background information to MoveBank, where a bit of history would actually help to illustrate what the process involved.

-----

User provided contact info: @ahahn-gbif
System: Firefox 58.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/602b7c3f245fba1652c5df1729b9e547:23c04677781cfb2b1a451ee37dcfcf889393ec554286999d5ff561b1fc13963f2bc7bdc6f8a429d0cfb6d4806254f9fe7b638b98dff0dc79a2e05e3509f6a165)
Referer: https://www.gbif.org/news/82812/licensing-milestone-for-data-access-in-gbiforg
Window size: width 1366 - height 861
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-14T15:57:51.895Z',mode:absolute,to:'2018-03-14T16:03:51.895Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-14T15:57:51.895Z',mode:absolute,to:'2018-03-14T16:03:51.895Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Will investigate, @ahahn-gbif ...

**Comment by kcopas** [comment]
I've got the doc

**Comment by dnoesgaard** [comment]
Yeah, I can provide all the text you need, if that helps, but resurrecting the resource online will take more time. Let us know.

**Comment by ahahn-gbif** [comment]
Is the text the same as https://gbif.box.com/s/j2cumhnxb97xevkiw7xp9ge8qyp2xfys? If so, that one is linked from https://www.gbif.org/news/82363/new-approaches-to-data-licensing-and-endorsement. If not, I would be interested in the content first, and fixing (or removing?) the broken link second. Thanks!

**Comment by dnoesgaard** [comment]
The broken link points to a page in the old website with this text:

> # Licensing of data within GBIF
> **This consultation is now closed. You can read a [news item](http://www.gbif.org/newsroom/news/data-licensing-and-endorsement) on the GBIF Governing Board's decision on the way forward for data licensing and endorsement in the GBIF community, based partly on the outcomes of this consultation.**
> 
> A report summarizing and analysing the responses is available here (**links to the document you sent**). You can view all responses here(**broken beyond repair**).
> Addressing the issue of data licensing, in a way that makes data as free from restrictions as possible, is essential to GBIF's mission of promoting free and open access to biodiversity data. In August 2013, the GBIF Secretariat conducted an initial consultation on options for change, proposing a more standardized approach to ensure that data users are aware of the terms under which datasets are published, and any restrictions that data holders may wish to apply to their re-use.
> 
> Between April and June 2014, the Secretariat requested feedback on a proposal with the following elements:
> 
> - All data publishers through GBIF would be asked to agree to waive rights when publishing their data (through a Creative Commons CCO license or equivalent);
> - All data publishers and users would agree to follow 'publishing and usage norms', to be drawn up collaboratively with the GBIF community, for example following standard guidelines for data citation and defining what constitutes commercial use;
> - The GBIF data publishing process would be modified to allow data publishers to flag datasets they wish to restrict from commercial use, as defined in the norms.
> The consultation invited views on whether respondents felt this was the right way to proceed, whether they foresaw substantial risks, and whether they would like to be involved in drawing up the documentation for this new approach to open data publishing through GBIF.
