### ISSUE TITLE
Points near Îles Glorieuses, provided with ISO code FR, are being flagged as mismatched against Madagascar

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1266]
**Inversion Latitude et Longitude- BioReCIE**

To whom it may concern, 

Latitude and longitude of the occurence data from the dataset BioReCIE (`https://www.gbif.org/dataset/b4be6d3b-6bb0-4d1d-8502-b09bf83ff905)` have been inverted.
Thank you by advance for correcting this error, 

Sincerely,
Marielle

-----

User provided contact info: marielle.dumestre@mnhn.fr
System: Chrome 64.0.3282 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/2fe450f274534be31293bd1725ac17ca:6b9eac221e212bb82ce0239b075658801e351df0649c88dac6cd38fa06fb10c3f8e08d68fc4aae905b329447de9db1e50715037eafa54fd6999ed530fd4cdfdf)
Referer: https://www.gbif.org/occurrence/map?dataset_key=b4be6d3b-6bb0-4d1d-8502-b09bf83ff905
Window size: width 1264 - height 804
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-15T16:49:00.371Z',mode:absolute,to:'2018-03-15T16:55:00.371Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-15T16:49:00.371Z',mode:absolute,to:'2018-03-15T16:55:00.371Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by SophiePamerlon** [comment]
Hi all,
Issue corrected on the INPN IPT, coordinates are ok after re-publishing.
Cheers,
Sophie

**Comment by MattBlissett** [comment]
...although points near Îles Glorieuses, provided with ISO code FR, are now being flagged as mismatched against Madagascar; example http://api.gbif.org/v1/geocode/reverse?lat=-11.61473&lng=47.33861 from https://www.gbif.org/occurrence/1656622749

We use Marine Regions' database, and this area is disputed between France and Madagascar. That should mean we follow the data publisher's lead, and accept either FR or MG.

**Comment by kcopas** [comment]
We've had previous issues with how best to handle French overseas territories. I don't recall the implementation details for, say, how we handle New Caledonia et al., but I suspect that if these records occur in les Îles Glorieuses, the record(s) should probably show the country code as [TF](https://www.gbif.org/country/TF/summary) instead of FR—

leaving aside any territorial dispute.

**Comment by MattBlissett** [comment]
> ...although points near Îles Glorieuses, provided with ISO code FR, are now being flagged as mismatched against Madagascar

With an improvement to the geocoder, these areas will soon return the overlapping claims as held in Marine Regions:

```json
[
 {
  "id": "232",
  "type": "EEZ",
  "source": "http://vliz.be/vmdcdata/marbound/",
  "title": "Overlapping claim Glorioso Islands: France / Madagascar",
  "isoCountryCode2Digit": "MG"
 },
 {
  "id": "232",
  "type": "EEZ",
  "source": "http://vliz.be/vmdcdata/marbound/",
  "title": "Overlapping claim Glorioso Islands: France / Madagascar",
  "isoCountryCode2Digit": "TF"
 }
]
```

@SophiePamerlon, I think your latitudes and longitudes have reversed again.

**Comment by MattBlissett** [comment]
This dataset has been deleted, so there's nothing more to do.

The Geocode fix for overlapping claims for EEZs will be deployed this week.
