### ISSUE TITLE
not a synonym / name missing (deleted)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1268]
**not a synonym**

acceptedNameUsageID and acceptedNameUsage both point back to the very same record so its clearly treated as accepted. "alternate representation" is probably being parsed as status=synonym but it should be overridden by looking at the actual accepted relationship which is very clear in this case

-----

System: Chrome 64.0.3282 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/f695c6e54a9bd3cf8841c708cdc14b5a:615a529d4190f7d19e3559ffa58360f56ff1c39ef3b7a5a1acbcdd18f1c1549a077e61c65831324e72d0a8b64ce85dafe3d7aa0b2277f6286676c96efb40fb9d)
Referer: https://www.gbif.org/species/106090109/verbatim
Window size: width 1628 - height 891
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-16T15:58:13.733Z',mode:absolute,to:'2018-03-16T16:04:13.733Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-16T15:58:13.733Z',mode:absolute,to:'2018-03-16T16:04:13.733Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The link to the species is not working here: https://www.gbif.org/species/106090109
Does it mean that this issue is no longer relevant?

**Comment by MattBlissett** [comment]
@mdoering may want to investigate why a usage is now gone, rather than marked as deleted.

**Comment by MattBlissett** [comment]
Ah, presumably it was part of a checklist dataset, and has been removed at source...

Still, Markus opened it, so let's leave it for him.

**Comment by mdoering** [comment]
This is not a backbone id but a regular checklist one. We only ever mark backbone usages as deleted but physically delete all other checklist usages. You can identify backbone usages as their ID is < 100 million
