### ISSUE TITLE
map of location of publisher

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1269]
**map of location of publisher**

I am not sure that map display for the publisher pages is correct (layout), looks a bit misplaced?

-----

User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5032da9d51aa4b04821dd44e86d384a3:19428f6cbbeb4a92537561b50cec3e4eaff8ebc80d9e222f67b1bff49983e0ad1ead6a910cca3c4c7874636e3888bdd30e4fc67b995314bbae2d5bfb4a43731b)
Referer: https://www.gbif.org/publisher/c14b9ce2-9545-4376-8a3b-6741558c256a
Window size: width 1920 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-16T16:38:46.738Z',mode:absolute,to:'2018-03-16T16:44:46.738Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-16T16:38:46.738Z',mode:absolute,to:'2018-03-16T16:44:46.738Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
thomas it used to fit the box (better at least) could you look to see if you are missing a class please? (I think I might have created another issue for this the other day).
