### ISSUE TITLE
Craterellus tubaeformis is not a synonym of Craterellus lutescens

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal-feedback#1273]
Seems that the synonymy has been apllied by the backbone:
Craterellus tubaeformis:
https://www.gbif.org/species/2554536
http://www.catalogueoflife.org/col/details/species/id/88cdf0ab3b8445db1fb3d0fa59642420
http://www.speciesfungorum.org/GSD/GSDspecies.asp?RecordID=455453

Craterellus lutescens
https://www.gbif.org/species/8871787
http://www.catalogueoflife.org/col/details/species/id/868557bfef3ab4e962e128fa3b29deb5
http://www.speciesfungorum.org/GSD/GSDspecies.asp?RecordID=184644

**Comment by ManonGros** [comment]
Craterellus tubaeformis and Craterellus lutescens are still synonym in the news backbone.

**Comment by yroskov** [comment]
Craterellus tubaeformis is not a synonym of Craterellus lutescens in the CoL:

http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/fa897d39d04df5ab3f37fa5afc7a9ff6

http://www.catalogueoflife.org/annual-checklist/2019/search/all/key/Craterellus+lutescens/fossil/1/match/1

**Comment by ManonGros** [comment]
It looks like this has been solved in the new backbone.
