### ISSUE TITLE
Data validator: Issue visualization + report download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1274]
**Data validator: Issue visualization + report download**

Hello,

Could it be possible to show all the occurrences with validation issues on the data validator reports? (For now I can only see the first ten occurrences in the report tables). Alternatively, is it or could it be possible to download the report as a csv file containing all the occurrences with issues? This would be easier to help fix them in the original source file.
Thanks a lot for this really helpful tool!

-----

User provided contact info: @SophiePamerlon
System: Chrome 65.0.3325 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/26cd34e51cb86f63f920c9e2115bb55d:3f3c0f31d3c6b2f800a94c2373cf72c89cf28a1f19bb382bb1c11858a2494cba154bba9c4161b0325ac2e577d76771d6a3cdd9782ada9c2750dd60942fd62531)
Referer: https://www.gbif.org/tools/data-validator/1521462679479
Window size: width 1440 - height 794
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-20T11:01:32.774Z',mode:absolute,to:'2018-03-20T11:07:32.774Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-20T11:01:32.774Z',mode:absolute,to:'2018-03-20T11:07:32.774Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by SophiePamerlon** [comment]
(I know that it is possible to download the occurrences with issues directly from the dataset page thanks to the filters, but it would be great to be able to do that from the data validator report page too)

**Comment by thomasstjerne** [comment]
Thanks @SophiePamerlon 

At the moment this will not be trivial to implement, but I have transferred your idea to the validator repo here https://github.com/gbif/gbif-data-validator/issues/69 for further consideration.
