### ISSUE TITLE
species API fails for more than 100 names

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1279]
**species API fails for more than 100 names**

I'm matching unique scientific names to the  GBIF Taxonomic Backbone calling the species API through OpenRefine using the following expression:
"`http://api.gbif.org/v1/species/match?strict=true&name=`"+value

The API works perfectly below 100 names, above that, it starts crashing (i.e it never retrieves the API answer)

We ( @SIB-Colombia @RicardoOrtizG @leobuitrago) have found this bug several times independently of the operative system or ram

-----

User provided contact info: @camisilver
System: Chrome 65.0.3325 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/d9fb6fed626323a1368c2ef8c8c49906:b32bba04976ddc276a8f0679fcee0bc3cdc024719c148ce1068f3dc94e288bd39db23e81ce00bc9a05a6640046e2424e528debc2df54b475da61eefe175b5b68)
Referer: https://www.gbif.org/developer/species
Window size: width 1440 - height 785
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-22T13:38:39.123Z',mode:absolute,to:'2018-03-22T13:44:39.123Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-22T13:38:39.123Z',mode:absolute,to:'2018-03-22T13:44:39.123Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by camiplata** [comment]
Update. Apparently, this bug is associated with the new versions of  @openrefine as in the 2.6v we were able to call GBIF's API for 1million+ names. 
@SIB-Colombia @RicardoOrtizG @leobuitrago

**Comment by MortenHofft** [comment]
Glad to hear so.

**A general note**
When using our and other APIs, one should be careful not to hammer it with for example a million concurrent requests. Doing so will basically make everything slow for everyone. Instead limit the number of concurrent requests to say 100.

I'm closing the issue as I understand that you have found a solution
