### ISSUE TITLE
Taxonomic Information erroneous: Setaria setosa (Sw.) P.Beauv. is not a Fungi

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1281]
**Taxonomic Information erroneous: Setaria setosa (Sw.) P.Beauv. is not a Fungi**

The classification for this species is not the right one.
Setaria setosa (Sw.) P.Beauv is not a Fungi but Vascular Plant.
Kingdom: Plantae
Phylum: Tracheophyta
Class: Magnolopsida
Order: Poales
Family: Poaceae
Genus: Setaria

Source: `https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=41258#null`

-----

User provided contact info: @CaroleSinou
System: Chrome 65.0.3325 / Mac OS X 10.12.6
User: [See in registry](https://www.gbif.org/api/feedback/user/da3b07d180f3d922fb92a7344afd61ec:4d0458069f7b75e897864306c5955f054e4bba1b4018df267b9f9b1031b8be5e75aeb922350400aadda518cad814ae34b99c0436ecdd74e6e7615862c57fec76)
Referer: https://www.gbif.org/species/9042334
Window size: width 1440 - height 799
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-22T18:20:26.361Z',mode:absolute,to:'2018-03-22T18:26:26.361Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-22T18:20:26.361Z',mode:absolute,to:'2018-03-22T18:26:26.361Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The link for the species concerned is deprecated but the issue remain. Here is a new link: https://www.gbif.org/species/10494854

**Comment by ManonGros** [comment]
The classification is ok in the newest backbone taxonomy: https://www.gbif.org/species/10672711
