### ISSUE TITLE
metadata dataset representing data already published?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1282]
**metadata dataset representing data already published?**

This metadata-only dataset links to an existing resource hosted on an IPT:

`http://www.verspreidingsatlas.nl:8085/ipt/resource.do?r=florivon`

This resource is an occurrence dataset, already published in GBIF:
`https://www.gbif.org/dataset/20e3fcbb-c285-49ee-a93d-cc6ccd06ca9e`

Is this intentional? @MattBlissett?

-----

User provided contact info: @dnoesgaard
System: Chrome 65.0.3325 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/152301f07ebd5f04f1c967f7e51374eb:d5c2ef5f86a3ca6f025a4a6e6cb99efc6d9e5b83bde074c308eda71905d9d0188d5f94394bb0072bbe1dc0f66ffdd629cb1fe8edd57b364ba2a68ac087d91cd1)
Referer: https://www.gbif.org/dataset/fffac8fa-d07e-4640-8222-e340e448595a
Window size: width 1644 - height 907
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-23T09:36:29.556Z',mode:absolute,to:'2018-03-23T09:42:29.556Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-23T09:36:29.556Z',mode:absolute,to:'2018-03-23T09:42:29.556Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
NDFF registered 60+ metadata only datasets in the last few days, and are planning to register more in the next few days. Later on, some (all?) will be converted to occurrence datasets. At that point, we wouldn't want two copies of the same occurrence dataset, but at the moment it's not really a problem.

I'll bring this to the attention of @IsabelSilvaNLBIF and @gbif/content.

**Comment by IsabelSilvaNLBIF** [comment]
Dear Matt,
Thanks for your comments. NDFF publishes metadasets concerning mostly data that are not yet published in GBIF. There are however exceptions, such as FLORIVON. In the dataset NDFF Florivon the following sentence is included: This resource is available in NDFF but already published by FLORON Plant Conservation Netherlands: http://www.verspreidingsatlas.nl:8085/ipt/resource.do?r=florivon
So, it is intentional.  Can a metadataset be easily converted to an occurrence dataset in the IPT version 2.3.4.? This would be very practical and would avoid having two copies of the same occurrence dataset.
Kind regards,
Isabel

**Comment by jeroencreuwels** [comment]
I have contacted the data owner at FLORON what the reason is to have a metadata and occurrence data set published at GBIF.

**Comment by jeroencreuwels** [comment]
After contact with Floron it was decided that they will request NDFF to remove the metadata dataset. The occurrence Florivon dataset is up to date and is the only one that should used.

**Comment by ahahn-gbif** [comment]
The dataset is cited in one publication so far (https://www.gbif.org/resource/search?contentType=literature&gbifDatasetKey=fffac8fa-d07e-4640-8222-e340e448595a). Just to flag that this information will be hidden when the dataset is removed.

**Comment by dnoesgaard** [comment]
I don't know quite know how, but the two resources share a single DOI—and as such the one citation of the metadata dataset is also applied to the occurrence dataset.
