### ISSUE TITLE
Dataset has had an invalid archive for 3 years

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1283]
**Dataset has had an invalid archive for 3 years**

`invalidationReason=Archive invalid because [100% invalid triplets is > than threshold of 25%; 372864 records without an occurrence id (should be 0)`

What is probably intended as the occurrenceId is marked as the collectionID.

We miss about 180k records.

-----

User provided contact info: @MattBlissett
System: Firefox 59.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e679b589ceace0e118f95caa4fe394e8:9b0857d62246787d6dfbeb26c6010686a342adc7c7f80c17d08cec0f2ced942f9977c2770958ce07afb6ee7135849b8e43f63511749ff58b1158a6a655f4ce00)
Referer: https://www.gbif.org/dataset/d6cc311c-c5ab-4f23-9a20-10514f9eb9c4
Window size: width 1952 - height 1100
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-26T08:24:04.074Z',mode:absolute,to:'2018-03-26T08:30:04.074Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-26T08:24:04.074Z',mode:absolute,to:'2018-03-26T08:30:04.074Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publishers were contacted.
