### ISSUE TITLE
We need to be able to filter occurrences for a continent

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#129]
**We need to be able to filter occurrences for a continent**

Currently if I need to search for occurrences from Africa, I need to add all 53 African countries to the filter. It would be much easier simply to search for occurrences from a continent.

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
Reported by: w.coetzer@saiab.ac.za
System: Chrome 56.0.2924 / Windows 7 0.0.0
Referer: https://demo.gbif.org/search?q=demo
Window size: width 1920 - height 911
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-16T09:54:15.324Z',mode:absolute,to:'2017-03-16T10:00:15.324Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-16T09:54:15.324Z',mode:absolute,to:'2017-03-16T10:00:15.324Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
The problem is mostly the definition of "continent":

> Generally identified by convention rather than any strict criteria, up to seven regions are commonly regarded as continents [1]

cc @timhirsch 

[1] https://en.wikipedia.org/wiki/Continent

**Comment by kcopas** [comment]
@burkeker recently added an 'IPBES region' designation for each country to enable the regional views, like [this one for Africa](https://demo.gbif.org/the-gbif-network/africa#), on the network page. That may or may not be sufficient to any specific application, but it's start.

See also [Brooks TM et al. (2016)](http://dx.doi.org/10.1038/sdata.2016.7) for context and challenges.

**Comment by mdoering** [comment]
We could indeed offer a continent filter for occurrence searches which gets translated into a country based search as defined by the [gbifRegion](https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/Country.java#L1434) property of a country. This would be rather simple and uninvasive, leaving solr & hbase unchanged.

**Comment by timhirsch** [comment]
FWIW I would completely agree with the approach suggested my @mdoering - don't confuse things by using different continent definitions but enable filtering based on regions we have already defined.

**Comment by cgendreau** [comment]
We would just need to make it clear that this is not a geographical classification of countries. So, using the name `GBIFRegion` instead of continent may not be intuitive for external users but I think it highlights the distinction.

**Comment by kcopas** [comment]
@mdoering just make sure that the implementation on the Regional pages uses that term—I don't know whether @burkeker used it or added a separate term for IPBES regions, but we needed a way to display non-participants regionally. 

Either way, we do still have [Israel showing up in Asia](https://demo.gbif.org/the-gbif-network/asia#) rather than Europe, which is where they choose to participate regionally.

**Comment by mdoering** [comment]
At least in our API they are listed under [Europe](https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/Country.java#L601)

**Comment by ahahn-gbif** [comment]
I temporarily lost access to the registry and cannot check, but our country table at some point did contain continents (Africa) of´r continent areas (East-Africa). We used to use those for the regional reports, where the actual geographic coverage (continents) had to be intersected with the GBIF-political GBIFregions. Do we still have that information, or am I remembering an old version of the registry?

**Comment by MortenHofft** [comment]
It is already in the occurrence API I see. It is simple to add then. http://api.gbif.org/v1/occurrence/search?continent=AFRICA

**Comment by MortenHofft** [comment]
@cgendreau and @timhirsch If the data in the API is as expected and something we want to expose, let me know. For now I have tagged this as an API issue.

search for country israel continent EUROPE gives [264 results](http://api.gbif.org/v1/occurrence/search?continent=EUROPE&country=IL)

search for country israel continent ASIA gives [17353 results](http://api.gbif.org/v1/occurrence/search?continent=ASIA&country=IL)

publishing country israel gives no results with a continent filter
http://api.gbif.org/v1/occurrence/search?continent=ASIA&publishingCountry=IL
http://api.gbif.org/v1/occurrence/search?continent=EUROPE&publishingCountry=IL

**Comment by cgendreau** [comment]
The one included in the API search is based on the Seven continents model: https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/Continent.java

The problem is that this search will only give you what was provided in the `continent` DarwinCore field. In other words, if the continent is not there, we do not infer it from the country. Not sure this is what the user would expect.

**Comment by mdoering** [comment]
We actually have a todo in the interpreter code suggesting we should make use of the country:
https://github.com/gbif/occurrence/blob/master/occurrence-processor/src/main/java/org/gbif/occurrence/processor/interpreting/LocationInterpreter.java#L128

I would expect GBIF to derive the continent as good as we can and follow a clear, single definition.
Simplest might be the GBIFRegion as derived from the country. Alternatively we could even use the coordinates to define different continents for the same country, e.g. European and Asian Turkey.

For the portal though the API would not change so it should be safe to implement a continent filter already.
