### ISSUE TITLE
How do I find out the amount of taxa in a country.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1297]
**How do I find out the amount of taxa in a country.**

I am trying to make a comparison of the biogeography between Ireland and Spain. I would like to highlight the differences in taxa abundance / richness. 

In the "DATA ABOUT" tab it displays data of taxa occurrences.
Is this the amount of species present (i.e. richness) or is it observations (i.e. abundance).

-----

User provided contact info: sean.rogers@ucdconnect.ie
System: Chrome 65.0.3325 / Windows 8.1.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/159eecacf982bc5b83aa90b8ec87ea98:f63bbfdd9cac7b743cdb3c37c23f5f24d6e2532703e55ed141519a07877d7562aabe3ca1477af443b1e33d72514a9d02f540be49334aa00e1f3334df8291551a)
Referer: https://www.gbif.org/country/ES/about
Window size: width 1366 - height 637
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-09T07:42:09.612Z',mode:absolute,to:'2018-04-09T07:48:09.612Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-09T07:42:09.612Z',mode:absolute,to:'2018-04-09T07:48:09.612Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
User answered by email
