### ISSUE TITLE
This needs GBIF branding

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#13]
**This needs GBIF branding**

For the embed mode, this needs:

 - [ ] a  logo 
 - [ ] a statement that &quot;All data mediated through the GBIF network (as a link to GBIF)

-----
fbitem-f0b1d8e8c6811b830ef2f932fb5cf1be7ba9cf0a
Reported by: @timrobertson100
System: Chrome 54.0.2840 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/tools/species-population
Window size: width 1433 - height 799

**Comment by MortenHofft** [comment]
resolved by https://github.com/gbif/portal16/commit/2793cb6af8f31148b87bfae27177d0d678be73d9
