### ISSUE TITLE
lapsus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1300]
**lapsus**

The name published by Hampson *Staphylinochrous euryperalis*, as can be seen in [the original publication](`https://www.biodiversitylibrary.org/page/31563186#page/649/mode/1up).` The 'i' is a handwritten addition to the [BM(NH) card index entry](`http://www.nhm.ac.uk/our-science/data/lepindex/search/detail.dsml?TaxonNo=78583.0).`

-----

User provided contact info: @willavery
System: Firefox 59.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/65b585be1943bd5ac9181ef3230e999a:0776ace2171b2a7b1fb9a8d47eec9c077f26dcf93c802e19ea8a1cf2f7e176b0db6b21b26187e36f0d0e21042597aa74dcb9948f2e8a116882fe82cd5c4bc17c)
Referer: https://www.gbif.org/species/1751915
Window size: width 1535 - height 779
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-10T19:37:25.554Z',mode:absolute,to:'2018-04-10T19:43:25.554Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-10T19:37:25.554Z',mode:absolute,to:'2018-04-10T19:43:25.554Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by WilliamAvery** [comment]
Link to Ham pson's 1910 paper: https://www.biodiversitylibrary.org/page/31563186#page/649/mode/1up

**Comment by jlegind** [comment]
I have assigned Markus to this issue because I can't fit it elsewhere.

**Comment by yroskov** [comment]
The comment should be passed to Donald's team. (LepIndex cannot be changed)

**Comment by mdoering** [comment]
ping @dhobern

**Comment by dhobern** [comment]
I have made an edit in the TaxonWorks version of LepIndex that we plan to use as the base for the reconstruction of LepIndex within a new Global Lepidoptera Checklist. S. euryperialis now appears as a misspelling for an accepted S. euryperalis.

![image](https://user-images.githubusercontent.com/26148454/68091855-2befb980-fed9-11e9-8394-6125637329be.png)

We need to republish LepIndex from TW as soon as we have a better version than today (not too hard).

**Comment by mdoering** [comment]
@gdower can we export LepIndex from TaxonWorks now easily into a ColDP file?

**Comment by ManonGros** [comment]
This other issue concerns the LepIndex: https://github.com/gbif/portal-feedback/issues/2169

**Comment by ManonGros** [comment]
This other issue concerns LepIndex: https://github.com/gbif/portal-feedback/issues/2211

**Comment by gdower** [comment]
@mdoering, there's still some bugs in the TaxonWorks CoLDP exporter that we're working on resolving, but it will likely be possible soon. @dhobern, it might be necessary to add OTUs to LepIndex in order to export the taxonomic classification.

**Comment by dhobern** [comment]
@gdower Thanks, Geoff. Is that something I can somehow trigger automatically or will we need to develop a script?

**Comment by mjy** [comment]
@gdower @dhobern We'll add functionality to TW directly, probably as a default option on a per/project basis.

**Comment by dhobern** [comment]
Thanks @mjy - does that mean that the TW function will do the "obvious" thing and create OTUs for all names that are not shown as objective or subjective synonyms? Putting it another way, do you expect us to need to do any processing or review of the LepIndex data to make it ready for this step?

**Comment by mjy** [comment]
@dhobern We are currently envisioning a task that summarizes (briefly) the current map b/w names and OTUs.  From there there will be be several options to stub OTUs for those names that aren't linked to concepts, likely with the ability to scope these operations to specific branches, or arbitrarily tagged groups, if desired.

At present you don't need OTUs for synonymous names as long as they are linked to a valid name that is in turn linked to an OTU, i.e. these are compiled into the CoL export as names by proxy.

**Comment by dhobern** [comment]
@mjy Thanks - that sounds excellent
