### ISSUE TITLE
BID requirement for occurrence datasets not consistent

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#1302]
Hi,

In the data requirement page of the BID website (https://bid.gbif.org/en/community/data-quality/), for the occurrence datasets, basis of record is said to be required for the metadata.
However, there is no basis of record field in the registry database.

Marie

**Comment by laurarussell** [comment]
It's also listed that way on the main site. https://www.gbif.org/data-quality-requirements-occurrences. Maybe that should read subtype instead of basis of record?

**Comment by kcopas** [comment]
I believe it's intended as a requirement for BID-funded datasets, just as projectID is required. Its status as a field in the IPT is something else. Enforcing a slightly higher initial standard of data quality with €€€.

**Comment by laurarussell** [comment]
Basis of Record is required within the datasets, but it is listed on these pages as a requirement for metadata and there is not a metadata term called basis of record. 
<img width="556" alt="basisofrecordinmetadata" src="https://user-images.githubusercontent.com/742537/38608656-3d3d7da0-3d7c-11e8-891a-74b4e793047f.png">

**Comment by dnoesgaard** [comment]
What do you suggest, @laurarussell?

Should we remove the reference to "basis of record" with the context of metadata? Or refer to it as "subtype", in which case I believe the content depends the type of dataset, no? Either way, would it be a required field (IPT doesn't require it, I believe)?

**Comment by laurarussell** [comment]
@dnoesgaard I would remove it from the metadata sections. You can add subtype as recommended if you want, but subtype does not = basisOfRecord although they are similar. subtype should not be required as an occurrence dataset might have mixed basisofRecord (and subtype is one or the other, not both).

**Comment by dnoesgaard** [comment]
I have now removed _basis of record_ from the __Dataset metadata__ section. I assume it should also be removed from the BID website (https://bid.gbif.org/en/community/data-quality/), correct?

**Comment by kcopas** [comment]
Change appears to be reflected in [current version](https://www.gbif.org/data-quality-requirements-occurrences)
