### ISSUE TITLE
elevation data contains some non-elevation entries

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1306]
**elevation data contains some non-elevation entries**

The following gbif IDs have elevation data that are non-numeric: 

1819187840, 1090341116, 1702880312, 1269837702, 1288173871, 1249259065, 1314596688, 1229423889, 912255189, 1091095182, 1091100318, 1091102301, 1091105893, 1091108566, 1091117122, 1091119925, 1091123538, 1316556130, 1088974763, 1091233095, 1091239795, 1091241304, 1091245851, 1091259494, 1091267056, 1091271193, 1091271863, 1091280145, 1091282739, 1091290545, 1091301923, 1091304719, 1091312406, 1091316528, 1274898010, 1091133238, 1091142037, 1091144574, 1091145314, 1091153106, 1091155837, 1091157841, 1091158072, 1091158561, 1091167277, 1091169546, 1091170295, 1091171676, 1091187532, 1091192674, 1091195427, 1091210410, 1091211226, 1091211966, 1091215869, 1091216590, 1091222932, 1091225799, 1699330132, 1226925955, 1302807796, 1268725987, 1268749055, 1091321639

-----

User provided contact info: @kendonb
System: Chrome 65.0.3325 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/685054b7a69299274d9c74fabb003905:cf077493c33b2bf1a1030a38d96226eb2f92032fcfdb27875b9f564043df0d976c4752f251e5ab9b70cd1212b6c64915048ef70ea19cd4156809c092713ad02f)
Referer: https://www.gbif.org/occurrence/search?elevation=0,5290&advanced=1
Window size: width 1910 - height 905
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-16T05:07:17.218Z',mode:absolute,to:'2018-04-16T05:13:17.218Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-16T05:07:17.218Z',mode:absolute,to:'2018-04-16T05:13:17.218Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Most of the records do not contain any elevation data. Some publishers provide us with textual information that we handle as verbatim (for example:  "10 m" or "c.1200ft"). The information in verbatim fields is not parsed any further.

That being said, it seems that 32 out of these 64 records have numerical values for elevation. Do you remember where you saw that the elevation data were non-numerical?  This would really help us understand what is happening.

**Comment by kendonB** [comment]
I identified these after downloading the database and reading it into R. I
will try and forensically follow them back and see what's going on in a few
days

**Comment by ManonGros** [comment]
@kendonB have you been able to figure out what is going on?

**Comment by ManonGros** [comment]
@kendonB, I am going to close this issue but if you still have concerns or if you find anything suspicious, please contact us again (we can re-open this issue or create a new one).
