### ISSUE TITLE
eventDates incorrect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1307]
**eventDates incorrect**

It is apparent that the construction of eventDate from year and month by GBIF is incorrect. All original records in the IPT resource for this data set (`https://www.gbif.org/dataset/11f7be1d-fdf3-4753-bfb0-c61ddbde3303)` have year=2014, month=7, yet GBIF produces an eventDate that is a W3C datetime ( 2014-07-01T02:00Z). This is definitively wrong. The eventDate should be simply "2014-07" for all of these records.

-----

User provided contact info: @tucotuco
System: Chrome 64.0.3282 / Mac OS X 10.10.3
User: [See in registry](https://www.gbif.org/api/feedback/user/e989096d477c5b0c9a21e7312a42e547:c618f388d7277fad6bad727a61c7df697e0b04eaf887787f970eaaf34802349249af32dd0df687e221b72b3cf6441378292be7baf5ed2f17aefda9f9cc313e2f)
Referer: https://www.gbif.org/occurrence/search?country=TO&publishing_org=43160fcd-f183-4d8f-b629-d13c982f1abe
Window size: width 1138 - height 607
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-16T08:00:50.151Z',mode:absolute,to:'2018-04-16T08:06:50.151Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-16T08:00:50.151Z',mode:absolute,to:'2018-04-16T08:06:50.151Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
This is a date range, so it's covered by https://github.com/gbif/gbif-api/issues/4

There should be progress on this with the work on the new ingestion pipeline.

**Comment by MattBlissett** [comment]
Thanks -- I'm closing this as a duplicate.
