### ISSUE TITLE
BIONOMENCLATURE-GLOSSARY.GBIF.ORG is dead

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1308]
**BIONOMENCLATURE-GLOSSARY.GBIF.ORG is dead**

the link `HTTP://BIONOMENCLATURE-GLOSSARY.GBIF.ORG/` given in `https://www.gbif.org/tool/81275/terms-used-in-bionomenclature-online-tool` links to back to the post itself.

If its a dead legacy app should this be indicated?

-----

System: Chrome 65.0.3325 / Mac OS X 10.13.4
User: [See in registry](https://www.gbif.org/api/feedback/user/7ce00cf1370616fc1a6f33d4fad3d64c:61c8b0fcae26624c41e6a563e3c8e01a96c480333bbf98650793da1347d73fd0a73a98b8310ec210a5005e78921d841078b3c994bc17c6fadf1bf882800cc60a)
Referer: https://www.gbif.org/tool/81275/terms-used-in-bionomenclature-online-tool
Window size: width 1658 - height 910
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-16T08:27:08.465Z',mode:absolute,to:'2018-04-16T08:33:08.465Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-16T08:27:08.465Z',mode:absolute,to:'2018-04-16T08:33:08.465Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
maybe just link to https://www.gbif.org/document/80577/terms-used-in-bionomenclature-the-naming-of-organisms-and-plant-communities ?

**Comment by MattBlissett** [comment]
I've redirected the domain to that link.
