### ISSUE TITLE
5M fewer records for MNHN?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1309]
**5M fewer records for MNHN?**

The IPT reports that the current version, published a few days ago, has 5M fewer records.

Either a mistake, or a manual deletion should be run.

http://collections.mnhn.fr/ipt/resource.do?r=mnhn-p

-----

User provided contact info: @MattBlissett
System: Firefox 59.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/6d490940bdde9d62f8ac4817c54c1227:3c2bfc2b677267590efa1444c35fcabdfa7c0783737d98b7e3d4f639d1881d256ef491cc3704cfb64bbb6936898569bb45a7f11dad7618115b0624cf71991f6a)
Referer: https://www.gbif.org/dataset/b5cdf794-8fa4-4a85-8b26-755d087bf531
Window size: width 2560 - height 1274
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-17T11:50:01.636Z',mode:absolute,to:'2018-04-17T11:56:01.636Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-17T11:50:01.636Z',mode:absolute,to:'2018-04-17T11:56:01.636Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It seems back to normal now.
