### ISSUE TITLE
Project description does not render links

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1312]
**Project description does not render links**

URLs in the project introduction (called `description` in the IPT) on the project tab of a dataset are not clickable: see [this example](`https://www.gbif.org/dataset/9ff7d317-609b-4c08-bd86-3bc404b77c42/project).` Note that in the description (called `design description` in the IPT), URLs **are** clickable.

-----

User provided contact info: @peterdesmet
System: Chrome 65.0.3325 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/e1c172a5d5dd4194aef33f3f5e0007da:173b46aedf46d10df7ad62548cd84accb09c628458b67da57eaca8c377c2cda5f41ee174fd9ee42f714931101804314cf2ff31f4e489578b90f4d489e707cfcb)
Referer: https://www.gbif.org/dataset/9ff7d317-609b-4c08-bd86-3bc404b77c42/project
Window size: width 1371 - height 759
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-19T14:12:13.706Z',mode:absolute,to:'2018-04-19T14:18:13.706Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-19T14:12:13.706Z',mode:absolute,to:'2018-04-19T14:18:13.706Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by peterdesmet** [comment]
Example was: https://www.gbif.org/dataset/9ff7d317-609b-4c08-bd86-3bc404b77c42/project
