### ISSUE TITLE
Datasets not appearing in search results

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1313]
**Datasets not appearing in search results**

Various datasets that include target observations do not show up in searches when I search via Get Data>Occurrences.  Looking for Lepidoptera in the province of Ontario , many datasets do show up but other datasets mysteriously do not.  

This is not an exhaustive list, but here are several GBIF datasets with observations that fit the criteria (Lepidoptera + Ontario) that are available for direct search through the Get Data>Datasets path but not through Get Data>Occurrences:
iNaturalist Research-grade Observations
Ross A. Layberry Observations
Ross A. Layberry, Collection
Peter Hall Observations

-----

User provided contact info: d_kaposi@hotmail.com
System: Safari 11.0.3 / Mac OS X 10.11.6
User: [See in registry](https://www.gbif.org/api/feedback/user/f7e4fceb67603971174b0451cc1a0ef4:49554a4564978cadd681f2f0b172b5c356523455d1eee9bc41c9f7b49c0abc1e149475421eb5cce376dc71d120d30dac8ec4aca00a06d2f6b382cbee11a92cea)
Referer: https://www.gbif.org/
Window size: width 1440 - height 746
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-21T12:19:31.885Z',mode:absolute,to:'2018-04-21T12:25:31.885Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-21T12:19:31.885Z',mode:absolute,to:'2018-04-21T12:25:31.885Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
User contacted by email
