### ISSUE TITLE
error downloading cvs

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1325]
**error downloading cvs**

Dear Sr/Md,
I am recovering an error whenever I try downloading the cvs with the occurrences of Merrilliopanax chinesis. 
Would you be so kind to help me with this issue
Thank you

-----

User provided contact info: marina.coca@uam.es
System: Firefox 59.0.0 / Mac OS X 10.13.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4f022e58af4c48f93bf97efd9ba830a7:d7b8dd5d4fe97d9be0f0e0cd9c6748f1ccdfc2c0848004629cb6c4e5138718cc391c7995effed36bec67f88225a78b377ece048221adc9cedf319ddd0f1b4273)
Referer: https://www.gbif.org/occurrence/download?taxon_key=3035262
Window size: width 1827 - height 1321
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-25T09:38:23.549Z',mode:absolute,to:'2018-04-25T09:44:23.549Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-25T09:38:23.549Z',mode:absolute,to:'2018-04-25T09:44:23.549Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by jlegind** [comment]
Replied by email.
