### ISSUE TITLE
countryCode should not be Required

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1326]
**countryCode should not be Required**

On the DwC Occurrence [quality requirements](`https://www.gbif.org/data-quality-requirements-occurrences)` I would suggest to make `countryCode` = `Strongly recommended` rather than `Required`. E.g. for GPS tracking data or marine data this often not available in the source data.

-----

User provided contact info: @peterdesmet
System: Chrome 65.0.3325 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/13009a6264331f536c084b5baa27d076:07c2e6e7f94fdabe2d5a8d11f35407b73e747bb74d8a2c63a303a0bc2c19a42aa8a7c86c40bcc68cd6480b744eb4fbf304c70c800bd9a90e03ddd15dfe16f449)
Referer: https://www.gbif.org/data-quality-requirements-occurrences
Window size: width 1328 - height 803
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-25T12:02:24.670Z',mode:absolute,to:'2018-04-25T12:08:24.670Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-25T12:02:24.670Z',mode:absolute,to:'2018-04-25T12:08:24.670Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by dschigel** [comment]
This is an interesting idea. For the terrestrial collections, one would typically know where one is collecting, especially in the times of tightening collecting permit rules. This is not true for old collections, as country borders change faster than country names, in those cases the provided country name will be in conflict with locality details or coordinates, if those are available. This is also not the case for the smartphone observations, where country could be available but possibly never entered / selected manually, always intrepreted from the coordinates? I agree with marine, country is likely indicated only for territorial waters, if at all. I am writing this on the basis of labels I was coming across, I did not dive into the GBIF mediated data to check these impressions.

**Comment by tucotuco** [comment]
I agree that countryCode can not be made a requirement, strictly on marine grounds (pun intended).
