### ISSUE TITLE
add validated URL

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1328]
**add validated URL**

Would be nice to know the URL of the validated file if it was accessed from a URL

-----

User provided contact info: mdoering@gbif.org
System: Chrome 65.0.3325 / Mac OS X 10.13.4
User: [See in registry](https://www.gbif.org/api/feedback/user/2b06ca036c17be1748c294d31c7b6937:a265dd19f55a3b940291c52bb224a4b9419059706cbc7c1ea9a025c413ec81eaecf8e2391a6729af2a597bdef0b72f1596757c2d0fce2f884ed0a9ccf48c86b0)
Referer: https://www.gbif.org/tools/data-validator/1524126551775
Window size: width 1658 - height 874
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-25T14:06:51.819Z',mode:absolute,to:'2018-04-25T14:12:51.819Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-25T14:06:51.819Z',mode:absolute,to:'2018-04-25T14:12:51.819Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
I think we need to keep that private; people might not want to share pre-publication data, or data they aren't sending to GBIF.

We'd also become a host of arbitrary files, anything can be added to a valid DWCA and it remains valid.
