### ISSUE TITLE
Show validated sample

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1329]
**Show validated sample**

Showing a sample of the validated data as seen through the dwca-io is very useful. E.g. `https://tools.gbif.org/dwca-reports/115-8237768766108232236.html` identifies badly mapped data which you cannot see with this tool

-----

User provided contact info: mdoering@gbif.org
System: Chrome 65.0.3325 / Mac OS X 10.13.4
User: [See in registry](https://www.gbif.org/api/feedback/user/9a057634a6f98763a6fe780bf05a0d05:5290b156e511bb874eacd7ee35f350e274b2551841fb7a5a7badb4887f8112a115e93c48513b4064f10945399f02bcf77486a7548b97b44eadfc77f0f858c49c)
Referer: https://www.gbif.org/tools/data-validator/1524126551775
Window size: width 1658 - height 874
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-25T14:08:53.849Z',mode:absolute,to:'2018-04-25T14:14:53.849Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-25T14:08:53.849Z',mode:absolute,to:'2018-04-25T14:14:53.849Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by thomasstjerne** [comment]
Needs work in the backend.
Transferred to https://github.com/gbif/gbif-data-validator/issues/71
