### ISSUE TITLE
Support GitHub id for entering contact information

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#133]
**Support GitHub id for entering contact information**

As per title

-----
fbitem-650dd53d64421891d161f2147516cbcf45073b95
Reported by: @Siro1
System: Chrome 56.0.2924 / Windows 10 0.0.0
Referer: https://demo.gbif.org/tools/suggest-dataset
Window size: width 1522 - height 810
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-21T13:04:14.677Z',mode:absolute,to:'2017-03-21T13:10:14.677Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-21T13:04:14.677Z',mode:absolute,to:'2017-03-21T13:10:14.677Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi Siro, I'm not sure what you mean. It is already possible to write your Github username instead of mail address if you want to. If a user does so, then you can contact that person through Github. 

Could you please specify what you mean?

**Comment by siro1** [comment]
Actually we have a common understanding. @Kbraak and I just thought that prompting people with the words "e.g., email or GitHub ID" will make them use their GitHub IDs more.

**Comment by kbraak** [comment]
Currently the hint only says email (see screenshot). Would be nice to mention possibility to add GitHub name, just like the field on the demo feedback (see screenshot). 

### Screenshots
![screen shot 2017-03-21 at 17 01 26](https://cloud.githubusercontent.com/assets/5981100/24156953/590cbedc-0e58-11e7-9f51-4073fa2f1cd5.png)
![screen shot 2017-03-21 at 17 02 44](https://cloud.githubusercontent.com/assets/5981100/24156947/57f7214a-0e58-11e7-8743-620d1e48ae65.png)

**Comment by MortenHofft** [comment]
@siro1 thanks for the clarification. I have changed it. It will be on https://demo.gbif-dev.org/tools/suggest-dataset shortly and on the public site with the next release.
