### ISSUE TITLE
scientificName missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1330]
**scientificName missing**

Required checklist fields are not validated.
This example has no scientificName or its atomised counterpart and thus fails to be indexed.

See `https://github.com/gbif/ipt/wiki/checklistData#required-dwc-fields`
(actually this is wrong, genus & specificEpithet are good enough instead of scientificName)

-----

User provided contact info: mdoering@gbif.org
System: Chrome 65.0.3325 / Mac OS X 10.13.4
User: [See in registry](https://www.gbif.org/api/feedback/user/127183854fe9e79c9afca522d0a762ae:76a767d441b4c798ec2905d16ba9dd79c6b04c2232868e9700da1bcf2aef927d990430260b8d5cb0b084aa68a6c4b3281b4fcfed26d20667775ad7bacdfe2176)
Referer: https://www.gbif.org/tools/data-validator/1524126551775
Window size: width 1658 - height 874
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-25T14:17:56.518Z',mode:absolute,to:'2018-04-25T14:23:56.518Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-25T14:17:56.518Z',mode:absolute,to:'2018-04-25T14:23:56.518Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
I also reported the same thing here:
https://github.com/gbif/gbif-data-validator/issues/73

**Comment by MortenHofft** [comment]
closing as duplicate
