### ISSUE TITLE
Trypanosoma cruzi missing from backbone

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1331]
Mostly a heads-up for @mdoering 

All this stems from investigations sparked by a [new paper in _Scientific Data_](https://doi.org/10.1038/sdata.2018.71) describing 'the most complete, integrated and updated database (DataTri) available on triatomine species at a continental scale'. This data paper, ironically enough, is quite cavalier about citation.

However, the issue here is that _Trypanosoma cruzi_, the protozoan vector of Chagas disease. While we appear to have about a few thousand occurrences, _T. cruzi_ does not appear in the backbone. As a result, these records only resolve to its genus, [_Trypanosoma_](https://www.gbif.org/species/3208283)—which has a [duplicate floating under the classification Animalia](https://www.gbif.org/species/3208283).

I don't know our sources, but it looks as if we might have a couple of items to resolve here, but until we do, we probably need to delay engaging _Scientific Data_'s editor on the issue of data citation and attribution.

@dschigel @dnoesgaard @ahahn-gbif

**Comment by yroskov** [comment]
Genus Trypanosoma, as well as entire Euglenozoa is a gap in the CoL: http://www.catalogueoflife.org/annual-checklist/2019/browse/tree/id/d2e91ef7afa31e489f8164956c3bc0ab

**Comment by mdoering** [comment]
maybe there are some taxonomic sources we could use in the article? I could not find a complete one at first glance though, just many small revisions

**Comment by kcopas** [comment]
This looks like the most recent attempt (link cuts to the chase): https://www.sciencedirect.com/science/article/pii/S0932473916300839?via%3Dihub#sec0025

Proposed classification is here:
https://www.sciencedirect.com/science/article/pii/S0932473916300839?via%3Dihub#tbl0005

Seems likely the systematists will know the source, but it's news to this layman: https://en.wikipedia.org/wiki/Cavalier-Smith%27s_system_of_classification

Just trying to help 👍

**Comment by ManonGros** [comment]
Trypanosoma cruzi is in the new backbone https://www.gbif.org/species/8205154

**Comment by kcopas** [comment]
It could be that I completely misunderstand, but the orphaned Animalia version of Trypanosoma name is still hanging about. https://www.gbif.org/species/3208283

Great to see the protozoan line added, but is that as would be expected?

**Comment by ManonGros** [comment]
Good point @kcopas! I don't know why it hasn't been put with the other genus (https://www.gbif.org/species/9543785). Reopening the issue

**Comment by mdoering** [comment]
[Trypanosoma brucei Plimmer & Bradford, 1899](https://www.gbif.org/species/7822322) as the sole species is the cause for creating the duplicate genus under Animalia. As the ICZN list does not have any further classification or a genus authorship given it is rather difficult to figure out if these are 2 distinct genera or not. 

I will add this one species to Protozoa in our patch list - this should solve this in the next version then.
