### ISSUE TITLE
citing individual occurrences when accessed through GBIF

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1332]
**citing individual occurrences when accessed through GBIF**

In addition to the improvement suggested earlier, I propose we add a paragraph on how to cite individual occurrences as a GBIF page and as a single record download.

Context in the examples from Kyle:

In the `https://doi.org/10.6084/m9.figshare.5822721.v1`
there is some citation of GBIF, line by line, record by record, along the lines of GBIF.org (4th August 2016) GBIF occurrence Download `http://www.gbif.org/species/8282740`

*
Identical citation is given to different records, which is pinciple a valid citation, but losing the record level details

-----

User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/1db32cd05f67e81c53ab24bc5641dda8:840119a980fdc998494dde61aa5b7f7334d93edbbf7aad2351ebf593114dbc586188be913ca2bf8a8e8411fa4d5a6081386e9ea4e3f93f78ece077db99faecbe)
Referer: https://www.gbif.org/citation-guidelines
Window size: width 2560 - height 1317
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-26T09:06:33.104Z',mode:absolute,to:'2018-04-26T09:12:33.104Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-26T09:06:33.104Z',mode:absolute,to:'2018-04-26T09:12:33.104Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by kcopas** [comment]
Address in review of #1221
