### ISSUE TITLE
Page does not load

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1333]
**Page does not load**

I have been unable to have any datasets validate for the past few days. The page keeps saying validation in progress. My files are less than 1000.

-----

User provided contact info: renguste@gmail.com
System: Chrome 65.0.3325 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b47d49aa8a4e53cda1dd8c01377d2dd1:4d7acb91e046ea5bac536b1fc5ec9b7298318022070a0c7278aeb71551bc8b266cc4fe096d3bd4347203d908ed60b06d488725b4c3f586cd793f9858eea0dc0c)
Referer: https://www.gbif.org/tools/data-validator/1524126551797
Window size: width 1920 - height 974
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-26T16:23:27.902Z',mode:absolute,to:'2018-04-26T16:29:27.902Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-26T16:23:27.902Z',mode:absolute,to:'2018-04-26T16:29:27.902Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
Replied by email for more information.

We may need a better monitor to check the validator is still working correctly.

**Comment by MattBlissett** [comment]
Large Excel sheet problem, or general failure to report the process has crashed.
