### ISSUE TITLE
Map mode

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1334]
**Map mode**

How can i change the layout of the maps? May I download the maps of occurrences?

-----

User provided contact info: @Tibério
System: Chrome 65.0.3325 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e43906f5764f912e9bb740a632e09583:16d069a3d7302e4b31aff050fcd4d27b0f61d9ddd73a8338692b529ded112f625a4ef53a1bf0934d0214110471aba15986b3ccf952e21238cc4d2657fed2d57e)
Referer: https://www.gbif.org/faq?q=map%20mode
Window size: width 1366 - height 662
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-28T18:20:11.468Z',mode:absolute,to:'2018-04-28T18:26:11.468Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-28T18:20:11.468Z',mode:absolute,to:'2018-04-28T18:26:11.468Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
Replied by email.

**Comment by MortenHofft** [comment]
Seems like this one is closed
