### ISSUE TITLE
Issues help information is missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1338]
**Issues help information is missing**

The validation issues have a help (?) button, but it doesn´t show any information beyond the name of the issue.  At the beginning of the year, it did have useful information.

-----

User provided contact info: @camiplata @sibcolombia
System: Chrome 66.0.3359 / Mac OS X 10.11.6
User: [See in registry](https://www.gbif.org/api/feedback/user/a5a2e098a91edfe4db00e54f421c5916:dd120a6fc1a03a1cd08f2221af90ad83cbf469d6ddd86f27ba8786dbb890cc2fda1826877af72962047e1de2a7506bba282aa196ed7099e473d3f1c838c26bb1)
Referer: https://www.gbif.org/tools/data-validator/1524760262297
Window size: width 1390 - height 731
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-05T18:22:28.180Z',mode:absolute,to:'2018-05-05T18:28:28.180Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-05T18:22:28.180Z',mode:absolute,to:'2018-05-05T18:28:28.180Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Dear @camiplata and @sibcolombia,
Thank you for your feedback. It is very useful since we are trying to improve our new validator.

The issue with your dataset is actually a simple warning: our system assembled the scientific names out of other fields in your dataset (genus and specificEpithet).
I hope this helps.

**Comment by thomasstjerne** [comment]
Thanks for reporting @camiplata.
We are working on translations of the portal, and during the restructuring we have run into a few regression errors like this one.
Should be back to normal now.
