### ISSUE TITLE
Community site not working

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1339]
**Community site not working**

`http://community.gbif.org/`  cannot be accessed, server IP address could not be found.

-----

User provided contact info: @pzermoglio
System: Chrome 66.0.3359 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/73ed821d4fe2456c9b03900489b9355e:7f77dc51d51ceb31087f9fae2d05ac1fa2debd123bae236f78194acb3b9ef80f9acce525abfbc8f804bd590340022d496de906b91d5a8aa4a52bca92bdacd210)
Referer: https://www.gbif.org/
Window size: width 1455 - height 722
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-07T15:00:38.781Z',mode:absolute,to:'2018-05-07T15:06:38.781Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-07T15:00:38.781Z',mode:absolute,to:'2018-05-07T15:06:38.781Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Thanks @pzermoglio. 

It's actually been off for several weeks now—we wanted to see if and when anyone would notice, and you're the first who felt compelled to note it. 

We are active right now exploring and preparing an alternative. But if there is something specific that you were looking for from the old site, [drop us a note](mailto:communications@gbif.org) with the details.

**Comment by pzermoglio** [comment]
@kcopas Thanks for the rapid response. Interesting experiment... (somewhat sad that no one noticed before).
Looking forward to the alternative you are working on.
