### ISSUE TITLE
vertical lines of dots across Russia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#134]
**vertical lines of dots across Russia**

Is there a way to find out what are the data behind the funny vertical lines across Russia on the occurrence map on the front page?

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
Reported by: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/
Window size: width 1536 - height 741
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-21T15:47:12.381Z',mode:absolute,to:'2017-03-21T15:53:12.381Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-21T15:47:12.381Z',mode:absolute,to:'2017-03-21T15:53:12.381Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
http://www.gbif.org/dataset/c779b049-28f3-4daf-bbf4-0a40830819b6

I used the "In Viewable Area" search from the map on http://www.gbif.org/occurrence.  This part of maps isn't done in the new portal yet.

**Comment by MortenHofft** [comment]
Hi Matt. thanks. actually it is there, but obviously not exposed enough.
As far as i remember both current portal and demo portal have (different) issues with this functionality. which means it is bugged, but works in many actual use cases. I got the same result using the demo

![screen shot 2017-03-22 at 08 04 02](https://cloud.githubusercontent.com/assets/6759267/24185957/371885b2-0ed6-11e7-8faf-77d7c31a9104.png)

**Comment by MattBlissett** [comment]
I'll admit, I didn't even look on the new portal -- I'd been checking my work on the new maps against the old portal, so I had the page open already.

**Comment by MattBlissett** [comment]
@dschigel, I think we answered your question :).
