### ISSUE TITLE
A new Organization has been endorsed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1340]
**A new Organization has been endorsed**

Dear GBIF,

Thanks for endorsing my organization. 

My organization was endosed by Participant Node Managers Committee.
I would like to know how I can update and add some basic information about my organization and how I can publish the dataset.

This is the link of my organization on GBIF: `https://www.gbif.org/publisher/0c44be00-f76f-4efb-9618-5bbf19817f1d`

Best Regards

-----

User provided contact info: delodorico@gmail.com
System: Chrome 66.0.3359 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/337a70bb3a6c8ba3b357a058b527b66f:ada4c230d913126cb91a7b139849fadcfb59f29e5c3d1f791c627943b913304edc541e7a694e24987033ab5b654d36da4f75c326ec557eb2dd4ab37c4a84d507)
Referer: https://www.gbif.org/node/7f48e0c8-5c96-49ec-b972-30748e339115
Window size: width 1440 - height 728
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-08T13:14:01.390Z',mode:absolute,to:'2018-05-08T13:20:01.390Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-08T13:14:01.390Z',mode:absolute,to:'2018-05-08T13:20:01.390Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
@laurarussell, my guess is this is a BID question.
