### ISSUE TITLE
geometry

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1341]
**geometry**

When I try to download gbif records from R using rgbif::occ_data, it's geometry argument reads latitude well but doesn't read longitude. Could you please suggest me how to get it working. In your previous version of gbif it used to work well.

-----

System: Chrome 66.0.3359 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/110aeb2f9d75ab48b4c1d9cba31b9ea7:865c97f279a872a1980a5d96de748c89159d0b4b5503847ddb6515a026ad7749fc8712d66c636d668cda0c92befaec7fd8adaf4269f493bb41be54a0eaa30681)
Referer: https://www.gbif.org/health
Window size: width 1366 - height 637
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-09T21:16:48.218Z',mode:absolute,to:'2018-05-09T21:22:48.218Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-09T21:16:48.218Z',mode:absolute,to:'2018-05-09T21:22:48.218Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I'm not much help here: perhaps a question for you @jlegind ?

**Comment by jlegind** [comment]
Talked to Scott about it. Probably left-hand-rule related, otherwise it doesn't make much sense.
