### ISSUE TITLE
usagekey/taxonKey

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1342]
**usagekey/taxonKey**

Why don't I see usagekey/taxonKey as in the previous version GBIF website? Can I still use usagekey/taxonKey to search for occurrences particularly from R?

-----

System: Chrome 66.0.3359 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e6d44a4112893be8cd0ab5ce819398e1:ff181df2b7a77ed1fcd2f70a11828ef61ecb099d8097c9b596234ea5e41648364ad0cd5f13cb81666f38bb60159150cbf45baea8f8078b58a5ace22cd89391d3)
Referer: https://www.gbif.org/occurrence/1821311323
Window size: width 1366 - height 637
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-09T22:03:16.901Z',mode:absolute,to:'2018-05-09T22:09:16.901Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-09T22:03:16.901Z',mode:absolute,to:'2018-05-09T22:09:16.901Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The API and hence R still allow you to search for occurrences by taxonKey. In fact it is the only way to search for a specific taxon.

When on a species page you can see the key in the url e.g. https://www.gbif.org/species/7960979
Internally we use this service to get the ID from the name:
http://api.gbif.org/v1/species/match?name=Urtica%20dioica%20L.
