### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1343]
**Image not showing**

-----

User provided contact info: @timhirsch
System: Safari 11.0.3 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/8c1928cb47f541f8201d3a36b74824fa:bdd4fdb54a937c8db8ac4a418ef12f75e203c938d044e1cc8f1a077a33fc752e427e056f14a6b27e21069379e1878195031e3c55564349260e44ca5e4526c3e7)
Referer: https://www.gbif.org/data-use/83227/the-case-for-a-russian-national-biodiversity-portal
Window size: width 1487 - height 992
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-11T05:13:47.409Z',mode:absolute,to:'2018-05-11T05:19:47.409Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-11T05:13:47.409Z',mode:absolute,to:'2018-05-11T05:19:47.409Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by timhirsch** [comment]
Sorry @gbif-portal and @dnoesgaard ignore this! Image appeared on refresh.

**Comment by kcopas** [comment]
This has been an intermittent problem for me, though, too, in recent days. I haven't had any that didn't turn up after hitting refresh, so I didn't submit anything since it wasn't replicable.

Image caching issue, perhaps @MattBlissett @thomasstjerne ?

**Comment by MattBlissett** [comment]
I assume this was the big picture of an insect used to illustrate the story.

```
xx.xx.xx.xx - - [11/May/2018:07:17:03 +0200] "GET http://api.gbif.org/v1/image/unsafe/1170x422/http:%2F%2Fimages.ctfassets.net%2Fuo17ejk9rkwj%2F3vjpJtu41GSc0YCWmQeqwY%2F6ae94b3f40b69632e66e0e5a3ccf5e97%2F111_Saperda_carcharias.jpeg HTTP/2.0" 200 67344 "https://www.gbif.org/data-use/83227/the-case-for-a-russian-national-biodiversity-portal" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
xx.xx.xx.xx - - [11/May/2018:07:21:18 +0200] "GET http://api.gbif.org/v1/image/unsafe/1170x422/http:%2F%2Fimages.ctfassets.net%2Fuo17ejk9rkwj%2F3vjpJtu41GSc0YCWmQeqwY%2F6ae94b3f40b69632e66e0e5a3ccf5e97%2F111_Saperda_carcharias.jpeg HTTP/2.0" 200 67344 "https://www.gbif.org/data-use/83227/the-case-for-a-russian-national-biodiversity-portal" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
```

Those are probably Tim at 7:17 and 7:21, and both say they were successful, but @timrobertson100 did make some changes to the image cache backend. @kcopas, did this start happening early this week, or before then?

**Comment by kcopas** [comment]
Early this week, probably.

=====
*Kyle Copas*
Skovtoftebakken 15
2830 Virum
(+45) 28 75 14 75 | skype kylecopas

**Comment by MattBlissett** [comment]
I don't see anything suspicious in the Varnish logs for any images from Contentful, but the timing is around when Tim made a change.

**Comment by MortenHofft** [comment]
I'm closing this unless anyone is still experiencing it. I haven't seen it or heard anyone mention it since this issue was created.
