### ISSUE TITLE
Participation page content glitch

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1344]
I've noticed on multiple country pages that the 'Node established' field is showing 'Invalid date', e.g. https://www.gbif.org/country/DE/participation

I suspect it's some systematic issue with the link to the directory. Alerting Anne Mette via email.

**Comment by MattBlissett** [comment]
I think it's more likely that the website isn't handling the year-month 
data correctly. Germany (2001-02) and all the others are in this format.

Anne Mette -- you don't need to do anything.

Matt

**Comment by thomasstjerne** [comment]
It is taking the date from the participant in contentful "Date of node establishment", if that is unset, this error occurs. 
We could switch / fall back to membershipStart ?

**Comment by MortenHofft** [comment]
it now hides the field when no information has been provided in Contentful. Relabelling this a content issue as this isn't showing because the data hasn't been provided in Contentful.
