### ISSUE TITLE
How to search excluding issues and add multiple taxa

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1345]
**How to search excluding issues and add multiple taxa**

I know I can search including issues (e.g. include records with 'Coordinate rounded') but I want to be able to search excluding issues (e.g. no records with 'Taxon Match Fuzzy'). It seems if I just select the ones I am ok with, it includes some of the ones I am not ok with. 

I also don't know how to download a file comprising multiple taxa anymore. In the old search I used to be able to input a list of taxa I wanted, but now I can only (sort of) figure out how to download one at a time. An example of what I want to do: I have a list of species at a fossil site that are extant. I want to download all modern occurrences of those species to use to estimate climate at my site. In the old search I could add each one, but I can't figure out how to do that in the new site.

-----

User provided contact info: @TheTams
System: Firefox 59.0.0 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/35477ffd256934af509360f4d5697922:4783caf563f5b6f58f218177d9c960b2df6bc5b4f33dd2d5f1900e1f891eae916acaf3b2f2486181b3d725fb00139f3968cd99c85f82e1e4da6e3693148aed5f8da08fa1e33f4d1ac61dae8c43d5fa3b)
Referer: https://www.gbif.org/occurrence/download/0001353-180508205500799
Window size: width 1590 - height 882
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-11T20:30:41.497Z',mode:absolute,to:'2018-05-11T20:36:41.497Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-11T20:30:41.497Z',mode:absolute,to:'2018-05-11T20:36:41.497Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I'm afraid excluding issues has never been - and still isn't - possible (another vote for https://github.com/gbif/portal-feedback/issues/49).

As for adding multiple taxa that should be identical to the old site. Simply add more scientific names

https://www.gbif.org/occurrence/search?taxon_key=7906030&taxon_key=3698087

![screen shot 2018-05-22 at 11 50 39](https://user-images.githubusercontent.com/6759267/40355353-6f62ff9e-5db6-11e8-91f2-5d2c6d93facc.png)
