### ISSUE TITLE
How to upload data?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1346]
**How to upload data?**

How to upload data?

-----

User provided contact info: eswar.narayana0101@gmail.com
System: Chrome 66.0.3359 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/3916689fd2a216a42f0670b09c73e7da:7815cb7e6b50b220dfbd615cd53237144968da6c8691b1f6dc887a55433773c7ee5f9a3f486d67449f92e4f343fd5fca4956383f91fde0adf35c5860e99626c9)
Referer: https://www.gbif.org/user/confirm?username=eswar_narayana&code=bd38711d-1a33-4b26-8f97-e1d9cddac6b4
Window size: width 1366 - height 651
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-14T05:26:57.780Z',mode:absolute,to:'2018-05-14T05:32:57.780Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-14T05:26:57.780Z',mode:absolute,to:'2018-05-14T05:32:57.780Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The user has been contacted by email.
