### ISSUE TITLE
'View event on GBIF' has disappeared

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1347]
Sanja has noted that 'the feature "view on GBIF" has disappeared.' Her assessment that 'it looks a bit odd when you click on an event and you are directed straight to the event’s website, even though there is a short description on our website too.' See, f. eks. the 3rd example [here](https://www.gbif.org/resource/search?contentType=event), the Russian workshop aka 'Digitization of collections and publishing data'

Not sure that this is by design.

**Comment by MortenHofft** [comment]
Happened with commit https://github.com/gbif/portal16/commit/0d98f2f81a62a2672e315e3cb8ca8d054df2e4ad#diff-c96578470a0fa5af534bf3bb835bbfbe

Moment was removed as an angular module, but it is still used = leading to failures.
