### ISSUE TITLE
Number of vertices in within predicate

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1348]
**Number of vertices in within predicate**

Dear all,

I'm working on a procedure for data download for the Lower Saxon Wadden Sea National Park using the API. My question is if the number of polygon vertices for the within predicate is limited.

Thanks for help.

Michael Reetz

-----

User provided contact info: michael.reetz@nlpv-wattenmeer.niedersachsen.de
System: Firefox 52.0.0 / Windows 8.1.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/720df9146729b00dcc369f63ad2d49a6:657118dc42102c52a13c7fa69e916705eadc96a52389100fecda02bfbf4d1e22528a8ec3b03df3aa30128af415fbac642ba39d37e4394480c16d348a333f782b)
Referer: https://www.gbif.org/faq
Window size: width 1920 - height 1042
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-15T09:46:25.678Z',mode:absolute,to:'2018-05-15T09:52:25.678Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-15T09:46:25.678Z',mode:absolute,to:'2018-05-15T09:52:25.678Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Essentially duplicates #741
