### ISSUE TITLE
Improve download failure handling

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1349]
**EMPTY DOWNLOAD**

The occurrence file of the download is empty, this issue is reccurrent

-----

User provided contact info: @camiplata
System: Chrome 66.0.3359 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/6409e030853e74cb157b65ead4b883f7:a593cc8f30f09ec964966e4ddb9b350fbcecc780228bc2184284f23743dc67d7dd61a996dab184f361496acc22ce71823e3dab582d7df29dc862f5638752b29b)
Referer: https://www.gbif.org/occurrence/download/0003315-180508205500799
Window size: width 1920 - height 940
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-16T21:00:05.760Z',mode:absolute,to:'2018-05-16T21:06:05.760Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-16T21:00:05.760Z',mode:absolute,to:'2018-05-16T21:06:05.760Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by camiplata** [comment]
Update, apparently this problem happens when the internet connection is deficient thus, it is not a problem from Gbif. Interestingly the download does not crash but I rather get an incomplete DwCA.

**Comment by MattBlissett** [comment]
Hi, could you tell me how you were downloading the archive? For example, with a web browser, using a download accelerator/manager or similar browser addon/plugin, or using a command line tool.

It's possible a download accelerator could corrupt the download, but we could improve the download service to work better with these tools.

**Comment by MattBlissett** [comment]
Without further information, I'll assume this would be improved by fixing https://github.com/gbif/occurrence/issues/45 , as that will mean download accellerators and so on will work correctly.

An alternative to consider for monthly downloads is sharing them with Bittorrent, which has built-in checksums and copes very well with poor internet connections.
