### ISSUE TITLE
Deleted taxa not marked as deleted

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#135]
**Deleted taxa not marked as deleted**

We only logically delete species in the backbone by setting their deleted property to the date it was removed.

This is not shown in the portal and deleted taxa appear to be regular names. The old portal shows these with a strike through name and a note when the name was removed:
http://www.gbif.org/species/9074

-----
fbitem-species9074
Reported by: mdoering@gbif.org
System: Chrome 56.0.2924 / Mac OS X 10.12.3
Referer: https://demo.gbif.org/species/9074
Window size: width 1639 - height 912
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-22T10:43:59.054Z',mode:absolute,to:'2017-03-22T10:49:59.054Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-22T10:43:59.054Z',mode:absolute,to:'2017-03-22T10:49:59.054Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
This issue was moved to gbif/portal16#338
