### ISSUE TITLE
How to search on "unknown phylum"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1350]
**How to search on &quot;unknown phylum&quot;**

Some records in [this dataset](`https://www.gbif.org/occurrence/search?dataset_key=bfc6fe18-77c7-4ede-a555-9207d60d1d86)` are assigned to `Unknown phylum`. To improve the data quality, I would like to know which ones, but that node in the tree is grayed out/inactive, so I cannot search for those records. Can this be resolved in some way?

Alternatives:

- Search for everything except "Tracheophyta": I don't think negative searches are supported
- Search for records with taxon match issues (e.g. higher rank): returns more than those assigned to `Unknown phylum`

-----

User provided contact info: @peterdesmet
System: Chrome 66.0.3359 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/41661bf0fd25bb22b8da97669a14dcce:82077539829b708cba596d860748390f2fb0c441474aebdd785c18dd48b9186ed9afe4aacc72bc17272353b8aa1a57fd4f55f5f070d776a86c57fcabaee3673c)
Referer: https://www.gbif.org/occurrence/search?dataset_key=bfc6fe18-77c7-4ede-a555-9207d60d1d86
Window size: width 1378 - height 759
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-17T06:48:52.570Z',mode:absolute,to:'2018-05-17T06:54:52.570Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-17T06:48:52.570Z',mode:absolute,to:'2018-05-17T06:54:52.570Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by peterdesmet** [comment]
Screenshot of grayed out button:

<img width="351" alt="unknown" src="https://user-images.githubusercontent.com/600993/40161074-e52b3bc0-59af-11e8-8e7f-90ed8c466986.png">

**Comment by thomasstjerne** [comment]
It is currently not possible. 
it would be a negative search, something like: `phylumKey=null`
The trees and graphs visualising taxonomy looks up the main linnean higher ranks:
Kingdom, Phylum, Class, Order, Family, Genus

Some taxa may not have all ranks, could be ordered in Subkingdoms or Superclasses instead of Phylums and these are counted under a placeholder node "Unknown phylum", i.e. there is no taxonKey(s) to use for the search.

**Comment by peterdesmet** [comment]
So, if a taxon has a class, but not have a phylum in the GBIF backbone taxonomy (can you confirm this is possible?), it would also end up in `Unknown phylum`?

In that case, a better implementation might be that you can click `Unknown phylum` in the visualization (but not search occurrences for it), so you can at least unfold the subranks and browse further from there.

**Comment by MortenHofft** [comment]
Indeed that would be nice, but that isn't possible with the API either I'm afraid. At least I couldn't come up with a sensible way to do so with the APIs. Let me know if you have ideas.

**Comment by MortenHofft** [comment]
closing as can't fix until APIs change

**Comment by thomasstjerne** [comment]
And we can confirm that it is possible for a backbone species  not to have a Phylum:
E.g.:
https://www.gbif.org/species/9029701
