### ISSUE TITLE
What rank to assign to hybrid formulas

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1354]
**What rank to assign to hybrid formulas**

According to the [data quality requirements](https://www.gbif.org/data-quality-requirements-checklists), `taxonRank` is a required field. However, what `taxonRank` should be used for hybrid formulas?

[Example](https://www.gbif.org/species/141266176/verbatim), which ideally should be written as:

    Chenopodium album L. x Chenopodium hircinum

Note that `hybrid` is not an accepted [taxonRank](http://rs.gbif.org/vocabulary/gbif/rank_2015-04-24.xml)

-----

User provided contact info: @peterdesmet
System: Chrome 66.0.3359 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/7116b11bfeefae0e7de9dfcff0fa97dd:0b6cdeff86e57d74fbe9a8b561fdec703dd1ce763fb1e49af1a4134afd855d64bdf758905372f9a3a1a1ec6e1edf97539587701a826ef708f60aaf3925e0c4f6)
Referer: https://www.gbif.org/species/141266176/verbatim
Window size: width 1238 - height 759
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-17T07:59:02.038Z',mode:absolute,to:'2018-05-17T08:05:02.038Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-17T07:59:02.038Z',mode:absolute,to:'2018-05-17T08:05:02.038Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by peterdesmet** [comment]
Markdown got messed up, here is the link to the example: https://www.gbif.org/species/141266176/verbatim

**Comment by peterdesmet** [comment]
Note that GBIF can recognize [hybrid formulas](https://www.gbif.org/species/search?dataset_key=9ff7d317-609b-4c08-bd86-3bc404b77c42&name_type=HYBRID&issue=RANK_INVALID&advanced=1) in `name type`. It would be good to have guidance on how to populate taxonRank for those.

**Comment by MortenHofft** [comment]
> Markdown got messed up
Due to excessive spam links we have had to introduce `messing up markdown`. It is a real shame. Sorry that it troubles actual users

**Comment by thomasstjerne** [comment]
Hi @peterdesmet 
If its a hybrid between two species, I would suggest using "species" as rank, if its a hybrid between subspecies, use "subspecies" as rank etc.

When the rank differ between the two hybridizing taxa, I don´t know what makes most sense, and it seems that the [backbone](https://www.gbif.org/species/search?dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&name_type=HYBRID&status=ACCEPTED&advanced=1) uses the lower rank in some cases and the higher in other:

https://www.gbif.org/species/9235228
https://www.gbif.org/species/9268206

Maybe @mdoering knows?

**Comment by mdoering** [comment]
The backbone uses the rank given by the original sources.
But the code does specify what to do in such cases:

> If the postulated or known parent taxa are at unequal ranks, the appropriate rank of the nothotaxon is the lowest of these ranks.

https://www.iapt-taxon.org/nomen/pages/main/art_h5.html

**Comment by peterdesmet** [comment]
Thanks for the reply!
