### ISSUE TITLE
How indexing is done by GFIB?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1355]
**How indexing is done by GFIB?**

How indexing is done by GFIB and what are the factors considered doing this?

-----

User provided contact info: ujjwal.khare.civ16@itbhu.ac.in
System: Chrome 66.0.3359 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/d8073bcdcf30b1970509af9c56659c55:8fe56403573bb49efa632b47f4023d60e0e79c9ef7f8d08c90b83c25d5f70dd580e139877841c73035f390fb036b47873f50035fdba5d3e1c0d1413625528d2a)
Referer: https://www.gbif.org/faq?q=index
Window size: width 1440 - height 794
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-22T05:49:31.563Z',mode:absolute,to:'2018-05-22T05:55:31.563Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-22T05:49:31.563Z',mode:absolute,to:'2018-05-22T05:55:31.563Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Try this as an intro:
https://www.gbif.org/data-processing

**Comment by ahahn-gbif** [comment]
more detail also here: 
https://www.gbif.org/infrastructure/processing

**Comment by MortenHofft** [comment]
@kcopas and @ahahn-gbif 

User notified per email
> Thank you for your question.
We have answered you here: https://github.com/gbif/portal-feedback/issues/1355
Hope that helps
