### ISSUE TITLE
GBIF registration data in GBIF data portal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1356]
**GBIF registration data in GBIF data portal**

I received questions in my institute about the section 'GBIF registration data' in GBIF data portal that is given at the end of the file. When looking more carefully I realized that I had no good answers on the exact meaning of the different entries. Is there somewhere documentation about the different definitions that are used?

As an example, I took a checklist dataset `https://www.gbif.org/dataset/4dd32523-a3a3-43b7-84df-4cda02f15cf7.` 
- Is it possible that the Publication date differs from the Last modification date and if so, how is this possible? 
- Am I correct that in the example above the last modification is not ingested and still need to be done? 
- Furthermore, what is meant with Ingestion completion reasons, and what is Normal and when is an ingestion aborted? 
- Can we say that  there have been 63 crawls in total since 30 September?

-----

User provided contact info: jeroen.creuwels@naturalis.nl
System: Chrome 66.0.3359 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/a1aea4cd5c3b3ba922385229f3b365ed:e659493c50c3d8e8482ce9517b221e783fa47b446faf9ae7fdc30b55daae0d780527cf170f507ca7298cefd1f0dbfde96d14e90078b27d18b21385898cc04325)
Referer: https://www.gbif.org/dataset/19828488-7ebf-43f8-88af-6461d8afef9e
Window size: width 1920 - height 959
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-22T15:26:02.163Z',mode:absolute,to:'2018-05-22T15:32:02.163Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-22T15:26:02.163Z',mode:absolute,to:'2018-05-22T15:32:02.163Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Those refer to the API fields

* created (first registration in GBIF)
* modified (when was dataset level meta data last changed)
* pubDate (controlled by publisher - when do you click publish in IPT fx - or explicit metadata stating it)

https://api.gbif.org/v1/dataset/4dd32523-a3a3-43b7-84df-4cda02f15cf7

hope that helps

**Comment by MattBlissett** [comment]
And this particular dataset fails validation of its DWCA:

```
Finished validating DwC-A for dataset [4dd32523-a3a3-43b7-84df-4cda02f15cf7],
   valid? is [false].
Full report [DwcaValidationReport{
datasetKey=4dd32523-a3a3-43b7-84df-4cda02f15cf7,
invalidationReason=null,
occurrenceReport=null,
genericReport=GenericValidationReport{checkedRecords=63504,
duplicateIds=[FFFFFF5BF24384DC],
rowNumbersMissingId=[],
allRecordsChecked=true,
invalidationReason=Non unique core ids,
valid=false}}]
```

```
$ grep FFFFFF5BF24384DC Taxa.txt 
FFFFFF5BF24384DC,WIUFFEYGN5S,"Trizerconoides radiatus (Berlese, 1910)","(Berlese, 1910)",synonym,,Animalia,,,,,Trizerconoides,,radiatus,,,
FFFFFF5BF24384DC,WIUFFEYGN5S,"Trizerconoides radiatus (Berlese, 1910)","(Berlese, 1910)",synonym,,Animalia,,,,,Trizerconoides,,radiatus,,,
```
