### ISSUE TITLE
UK Otter Data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1359]
**UK Otter Data**

Hi there, 
I am gathering data for the whole of the UK, mostly 2000+ (however, at some point may look back at annual differences in otter presence) to assess the habitat uses of individuals throughout the UK in general (potential to see if there are any local deviations). This is extending from my bachelors project which looked at the distribution of otters on the Isle of Anglesey in Wales and the proposed habitat usage of individuals, I also looked at male and female usages to see if there was any intraspecific variation. 
I was wondering if you'd be able to provide me with the date required for my research, specifically the lat and longs of the presence points as the download is very jumbled.

Kind Regards
Tanya

-----

User provided contact info: osu6ad@bangor.ac.uk
System: Edge 16.16299.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7b023c1306ebf58a56c47fdd8a9ff6d7:4b472df1d4bfeac74e4456cdbeb32fa311f38d36b69574be3e1d18dfe6d3b7a0772f05459271b556e4095ad36051537cf6f85a3c614f710ed002e6091963a18f)
Referer: https://www.gbif.org/species/104060159
Window size: width 1680 - height 933
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-24T10:53:51.221Z',mode:absolute,to:'2018-05-24T10:59:51.221Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-24T10:53:51.221Z',mode:absolute,to:'2018-05-24T10:59:51.221Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Isn't that just something like this?
https://www.gbif.org/occurrence/search?country=GB&taxon_key=2433753&year=2000,2018

**Comment by jhnwllr** [comment]
Dear Tanya,

You can download all Eurasian otter occurrence records in the UK using the following links: 

https://www.gbif.org/occurrence/search?country=GB&taxon_key=2433753
https://www.gbif.org/occurrence/download?country=GB&taxon_key=2433753

And from 2000 to the present with this link: 
https://www.gbif.org/occurrence/download?country=GB&taxon_key=2433753&year=2000,2018

Let me know if this is what you are looking for.

Best regards,

John Waller
Data Analyst
GBIF Secretariat
Universitetsparken 15
2100 København Ø
Denmark
e-mail: jwaller@gbif.org
