### ISSUE TITLE
over 250.000 occurrences attached to a deleted family

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#136]
**over 250.000 occurrences attached to a deleted family**

The family Ceratiaceae Lindemann, 1928 (key 9074) was deleted and the current backbone now uses the key 7479242 for the family Ceratiaceae without authorship.

There are still 254.972 occurrences attached to the deleted family: http://www.gbif.org/occurrence/search?taxon_key=9074

An example occurrence from this list is:
https://demo.gbif.org/occurrence/1134970361

Which is matched to the correct species with the correct family: https://demo.gbif.org/species/7598904

Somehow though the wrong, old family gets used in the occurrence index

-----
fbitem-species9074
Reported by: mdoering@gbif.org
System: Chrome 56.0.2924 / Mac OS X 10.12.3
Referer: https://demo.gbif.org/species/9074
Window size: width 1639 - height 912
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-22T10:48:54.964Z',mode:absolute,to:'2017-03-22T10:54:54.964Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-22T10:48:54.964Z',mode:absolute,to:'2017-03-22T10:54:54.964Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
Name matching on prod returns the expected species and family key: http://api.gbif.org/v1/species/match?verbose=true&name=Ceratium%20hirundinella

**Comment by mdoering** [comment]
Reinterpreting one record did not solve the issue, the family key is still the wrong deleted one:
http://api.gbif.org/v1/occurrence/1134970361

Which is different in the name matching lookup:
http://api.gbif.org/v1/species/match?verbose=true&kingdom=Chromista&phylum=Dinophyta&class=Dinophyceae&order=Peridiniales&family=Ceratiaceae&genus=Ceratium&name=Ceratium%20hirundinella&rank=species

**Comment by mdoering** [comment]
Here is another case of a genus that has the wrong, old & deleted family:
http://api.gbif.org/v1/occurrence/1143306225

taxonKey: 7351754
http://api.gbif.org/v1/species/7351754
(which has the correct familyKey: 8161533)

familyKey: 2326 (deleted)
http://api.gbif.org/v1/species/2326

Again this is the same canonical family differing in authorship only.

**Comment by mdoering** [comment]
Needs a deploy and reprocessing of all occurrences to be fully fixed

**Comment by mdoering** [comment]
Reprocessing first the reported deleted families 9074 & 2326
