### ISSUE TITLE
Wrong taxon interpretation

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal-feedback#1360]
This species in Checklist of Danish Wasps, Bees, Ants etc. (Hymenoptera):
https://www.gbif.org/species/128685563/verbatim
ends up mapped to this backbone taxon: https://www.gbif.org/species/1357633
rather than this: https://www.gbif.org/species/9636068

The checklist provides Danish vernacular names and in this case it is not linked to the correct backbone taxon. (Found out because it was not possible to find the correct species when searching for "Rødpelset jordbi")

**Comment by ManonGros** [comment]
Since https://www.gbif.org/species/1357633 is considered a synonym of https://www.gbif.org/species/9805254 in the newest taxonomy, I will close this issue (let me know if should be reopened).
