### ISSUE TITLE
iNat crawl failing

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1361]
Noting two failed ingestions here:
https://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7

Worth asking Ken-Ichi about?

**Comment by MattBlissett** [comment]
This has the same cause as https://github.com/gbif/portal-feedback/issues/1358, i.e. my recent changes to our processing. It is fixed, but I've not yet finished testing related changes, so it's not yet deployed.

**Comment by MattBlissett** [comment]
iNaturalist looks to have crawled correctly.
