### ISSUE TITLE
Misidentification

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1362]
**Misidentification**

The picture (`http://www.enjoynature.net/?bild=122289155)` given as reference shows Cheilanthes acrostica (= Allosorus acrosticus). Asplenium obovatum is a fern of wet places and very unlikely to occur at Lato.

-----

User provided contact info: @ralf_jahn
System: Opera 52.0.2871 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/d75d9f567d9075922f3659dddb36a0db:6b8867ac9d975e314eb8c7fab8dbf2be0477fda95e97a5a67be4acc4061d91243ce97c10850892faddb51969424a18a22aff7963316ce1338da89b68b224de6a)
Referer: https://www.gbif.org/occurrence/920673209
Window size: width 2016 - height 1042
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-26T15:39:50.648Z',mode:absolute,to:'2018-05-26T15:45:50.648Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-26T15:39:50.648Z',mode:absolute,to:'2018-05-26T15:45:50.648Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
EnjoyNature / NaturGucker doesn't seem to have a way to link directly to an observation, let alone comment on it.

**Comment by ManonGros** [comment]
The occurrence concerned seems to be this one: https://www.gbif.org/occurrence/1338354505
It is now associated with the scientific name *Cheilanthes acrostica* so the issue can now be closed.
