### ISSUE TITLE
Bird species in Norway

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1364]
**Bird species in Norway**

Hello,

I'd like to get a number on all the species with observations in Norway, grouped by Order. I thought of downloading all the occurrences and going from there, but the data is way too large for that

-----

User provided contact info: tiago.laranjeiro@ntnu.no
System: Chrome 66.0.3359 / Windows 8.1.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7243981b7c7b476843da709ab9a0719d:4a5240a9fdea7f2ba47415b2b90e92b0c71300ccc52110125680791ed5ee1978fa5ed32f0158d5c303a5bb4fe166b2e3c16c318259ba569a4f05797a200bd04ab056239173b0882aa3103f937a44e3cc)
Referer: https://www.gbif.org/occurrence/taxonomy?basis_of_record=OBSERVATION&basis_of_record=MACHINE_OBSERVATION&basis_of_record=UNKNOWN&basis_of_record=HUMAN_OBSERVATION&country=NO&has_coordinate=true&has_geospatial_issue=false&taxon_key=212&advanced=1
Window size: width 2560 - height 1309
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-28T08:14:03.633Z',mode:absolute,to:'2018-05-28T08:20:03.633Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-28T08:14:03.633Z',mode:absolute,to:'2018-05-28T08:20:03.633Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
Answered by email.
