### ISSUE TITLE
gbif_dwc-a_metafile_en_v1 file missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1366]
**gbif_dwc-a_metafile_en_v1 file missing**

From the IPT "Darwin Core Archives – How-to Guide" page, there is a link to a "A complete reference guide to this metafile" pointing to `http://links.gbif.org/gbif_dwc-a_metafile_en_v1.`

Would it be possible to recover the file or to update the link ?

-----

User provided contact info: @cgendreau
System: Chrome 66.0.3359 / Mac OS X 10.13.4
User: [See in registry](https://www.gbif.org/api/feedback/user/8b1eb262826c0e654c3a1a64287f884d:556d9d0acb5013b8ae72f79a0c5d04867d41db7690a14d9c4aeb5d7ebc08abf0225b191cefbc43cb0b9be7c7e06d63256a8da5ef3c0379a3bc13de676d5e1a06)
Referer: https://www.gbif.org/orc?doc_id=2819
Window size: width 1425 - height 746
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-28T14:37:07.593Z',mode:absolute,to:'2018-05-28T14:43:07.593Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-28T14:37:07.593Z',mode:absolute,to:'2018-05-28T14:43:07.593Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by cgendreau** [comment]
Missing link to the Guide: https://github.com/gbif/ipt/wiki/DwCAHowToGuide

**Comment by MattBlissett** [comment]
Thanks Christian.

The link originally went to what's now hidden at https://www.gbif.org/sites/default/files/gbif_resource/resource-80639/gbif_dwc-a_metafile_en_v1.pdf , but I've updated it to the Github document.
