### ISSUE TITLE
align CESP menu item with other programmes

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1367]
**align CESP menu item with other programmes**

Please change menu item 

Inside GBIF -> Programmes & Projects -> Capacity enhancement

to read:

CESP: Capacity Enhancement Support Programme

-----

User provided contact info: @dnoesgaard
System: Chrome 66.0.3359 / Mac OS X 10.13.4
User: [See in registry](https://www.gbif.org/api/feedback/user/8ee4b289a7d9fa99a793398a9659f387:fa4f6941e7d7ed8def4fc5802bd59692d4578a3916d09aaf36fff90acbac021d7cf01e37d9fb792242cdfa380bfb983f9e747bc38ca9d07ffb858b7d235bfcb6)
Referer: https://www.gbif.org/
Window size: width 2253 - height 1192
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-30T11:39:09.484Z',mode:absolute,to:'2018-05-30T11:45:09.484Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-30T11:39:09.484Z',mode:absolute,to:'2018-05-30T11:45:09.484Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
![gbif](https://user-images.githubusercontent.com/21358085/40718222-928170aa-640f-11e8-90e5-b2b149119de7.png)
