### ISSUE TITLE
wrong species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1368]
**wrong species**

specimen corresponds to Chamaedorea quezalteca Standl. & Steyermark. Seen at MEXU herbarium

-----

User provided contact info: @dgo.vimo
System: Chrome 66.0.3359 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/d7898ee1e4991f774dacc43608e1dd37:a85e0a97dde607292196f807eed90a209c04c8bb33aa984934c7af412f0dd2939c5c012857e92a5d21e955d76880ab0c40d5c9eee597c34c1bddf87e2326c5d3)
Referer: https://www.gbif.org/occurrence/1419427037
Window size: width 1366 - height 662
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-30T22:54:14.463Z',mode:absolute,to:'2018-05-30T23:00:14.463Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-30T22:54:14.463Z',mode:absolute,to:'2018-05-30T23:00:14.463Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publishers have been notified.

**Comment by ManonGros** [comment]
The publishers replied that they will investigate this.
