### ISSUE TITLE
Data Validator  is not working

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1373]
**Data Validator is not working**

I'm trying to validate a DwC .csv file and I get the following message:

The validation job ID was not found. If you believe this is an error, please report it.

I checked again with an already published DwC-archive and the error messages continues.

Thank you in Advance!

-----

User provided contact info: @camiplata
System: Chrome 66.0.3359 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/d41e78b99122238a83f5a60d1e9a7ec0:cab53e39300835e7cc3a80a693f1c1ef8124a02a26c0dd6a8bdf371513ecf9f57a421cdcf0c45ac38e9474338ac79f3fb49a58474c0c91685ce8c5bd29b27fd1)
Referer: https://www.gbif.org/tools/data-validator/1525842527806
Window size: width 1600 - height 872
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-31T14:01:15.393Z',mode:absolute,to:'2018-05-31T14:07:15.393Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-05-31T14:01:15.393Z',mode:absolute,to:'2018-05-31T14:07:15.393Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by camiplata** [comment]
It looks like the system health is critical O.o, I'll check again later probably it will work once the system gets stabilized

**Comment by MortenHofft** [comment]
Thanks @camiplata 
the service was down I'm afraid. Should be running again - thank you for notifying us.
