### ISSUE TITLE
Missing images on NHM dataset

### ISSUE THREAD

**Issue by jrdh** [gbif/portal-feedback#1374]
Currently, there are no occurrence images on the [Natural History Museum (London) dataset](https://www.gbif.org/occurrence/gallery?dataset_key=7e380070-f762-11e1-a439-00145eb45e9a) even though our DwC-A output contains multimedia data.

Could this be related to https://github.com/gbif/portal-feedback/issues/1358?

**Comment by MattBlissett** [comment]
It's possible, but I think the DwC-A has perhaps changed.

The format term is generally required, e.g. image/jpeg, and the URLs are currently returning 503: http://www.nhm.ac.uk/services/media-store/asset/c32f0b65aee0fcb1e850db61e578f0f3bed96ac1/contents/preview

This is record 1 from the archive, with two multimedia objects parsed: https://www.gbif.org/occurrence/1055736418 or https://api.gbif.org/v1/occurrence/1055736418

**Comment by jrdh** [comment]
After including the format in the multimedia csv the images are now appearing on GBIF as expected. Thanks @MattBlissett
