### ISSUE TITLE
Use consistent section titles on dataset page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1375]
**Use consistent section titles on dataset page**

The titles of the sections on a dataset page are not all consistent:

- Don't use `Title Case`. In the side menu it is used for `Data Description` and `GBIF Registration`, while on the page itself `Data description`, `GBIF registration` is used. The rest of the site doesn't seem to use it either: `Get data`, `Data processing`, ...
- Capitalize `geographic` as title
- Capitalize `taxonomic` as title
- `Temporal` and co are odd titles. Add `scope`: `Temporal scope`, `Geographic scope`, `Taxonomic scope`
- Make `Data description` an h3 rather than h4
- Make `GBIF registration` an h3 rather than h4
- Make `Citation` an h3 rather than h4

-----

User provided contact info: @peterdesmet
System: Chrome 66.0.3359 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/4a710d55aea3e16d522721071061f656:ecfaa5d6aee02fabaf714445c0cc6522b2c543e15425243de7f1d2e0b6d2383801a022935c1e2f64d703f22aa51f349e59b247150d3566cb023aae7cadd25379)
Referer: https://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e
Window size: width 1244 - height 803
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-01T11:45:47.096Z',mode:absolute,to:'2018-06-01T11:51:47.096Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-01T11:45:47.096Z',mode:absolute,to:'2018-06-01T11:51:47.096Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
This is in the translation file and can be edited by comms and translators into other languages as they see fit

**Comment by peterdesmet** [comment]
@MortenHofft can you point me to the translation file?

**Comment by MortenHofft** [comment]
Sure, but I thought I had changed it all already. oh, scope thing i didn't I see.

https://github.com/gbif/portal16/blob/master/locales/translations/en/components/dataset.json
