### ISSUE TITLE
Synonimized different valid species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1377]
**Synonimized different valid species**

We recently uploaded a dataset through the Chilean GBIF node (`https://www.gbif.org/dataset/c2d8bc68-8f4d-465e-80b2-734a4bb9d806)`

One of the best represented species in our dataset is Aeneator fontainei (d'Orbigny, 1839) when assimilated to GBIF  it associates with Austrofusus fontainei (d'Orbigny, 1841) taht is a different valid species.

Our records are of A. fontainei (d'Orbigny, 1839). Would it be possible to correct this? I checked the Catalogue of Life and they appear as different species, as well as in WORMS.

Thanks in advance and best regards

-----

System: Chrome 60.0.3112 / Windows 8.1.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/afa05ea85aaf8a11f6e09f2e74c169ef:bf76fa1852a68fb0c1e88ea81421579f51044c18817c84ed5ef78d8738743efe0a65b1573ee4e0decc14a69c2071b2c5fca9db58bffc338bad9d04f747390f06)
Referer: https://www.gbif.org/user/profile
Window size: width 1280 - height 732
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-01T19:03:17.972Z',mode:absolute,to:'2018-06-01T19:09:17.972Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-01T19:03:17.972Z',mode:absolute,to:'2018-06-01T19:09:17.972Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by yroskov** [comment]
Aeneator fontainei is an independent species in CoL:
http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/9c7d45a890622ea8170625c16e3be3b2

**Comment by mdoering** [comment]
This happened as the basionym grouping decided these 2 names are based on the same basionym:

Austrofusus fontainei (d'Orbigny, 1841)
Aeneator fontainei (d'Orbigny, 1839)

Same family, same epithet, same author, nearly the same year

**Comment by mdoering** [comment]
logged in https://github.com/Sp2000/colplus-backend/blob/master/bad-basionyms.tsv

**Comment by ManonGros** [comment]
Issue solved in the new backbone: https://www.gbif.org/species/6503984
