### ISSUE TITLE
stdTerms.citations on data use page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1380]
**stdTerms.citations on data use page**

1) this should be capitalized, i.e. Citations
2) not sure why it's plural when there's just one citation?

-----

User provided contact info: @dnoesgaard
System: Chrome 66.0.3359 / Mac OS X 10.13.4
User: [See in registry](https://www.gbif.org/api/feedback/user/12730920d17b6f5bf6213656f9bf6197:8dbbe3f92d3b30b8da2bb10d27e1666eab222f9e39a68ec7aa0301d28dcef8b3f65453706410ec54b431f69da9f0a302dcbe553f51c9a654d85aa3806b0489d0)
Referer: https://www.gbif.org/data-use/58f2bdn6CQOAGAkYuQMIMg/evolution-of-terrestrial-breeding-in-african-toads
Window size: width 1375 - height 669
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-04T13:23:26.070Z',mode:absolute,to:'2018-06-04T13:29:26.070Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-04T13:23:26.070Z',mode:absolute,to:'2018-06-04T13:29:26.070Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
<img width="757" alt="evolution_of_terrestrial_breeding_in_african_toads" src="https://user-images.githubusercontent.com/21358085/40920165-034cfe08-680c-11e8-9770-d3246efbbed1.png">

**Comment by MortenHofft** [comment]
it is plural because it is a possible to have many and how it was modelled in Drupal. So the assumption has always been that it would occasionally be used as such. And being a free text field we can not change to title to match the count. If in reality it is only one, then we can change that.
