### ISSUE TITLE
Dutch Vegetation Database (LVD) incorrect field mapping

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal-feedback#1381]
This dataset has lots of TAXON_MATCH_HIGHERRANK, because the term `scientificNameAuthoriship` also contains the scientific name, which confuses the name matcher. It should only have the authorship, e.g. `L.`.

https://www.gbif.org/dataset/740df67d-5663-41a2-9d12-33ec33876c47

**Comment by ManonGros** [comment]
The publisher was notified by email.

**Comment by ManonGros** [comment]
The publisher corrected the scientificNameAuthorship field.
The number of occurrence with the TAXON_MATCH_HIGHERRANK issue dropped from 425,195 to 145,774.
Most of occurrences left with this issue are to do with species of the genus "Taraxacum" which don't seem to be in our backbone.
