### ISSUE TITLE
Hosted datasets: show the link to the hosting institution more prominently

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1384]
**Hosted datasets: show the link to the hosting institution more prominently**

At present, hosting institutions are still relatively hard to find. On a dataset page, the link is hidden at the very bottom of the page. Consider to give the hosts more credit and make them easier to find, e.g. by adding a "Hosted by" link higher up on the dataset page. Options would be:
- the very top section, next to the "Published by" text
- the first block close to the description and license info

-----

User provided contact info: @ahahn-gbif
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5b0f2c95bd419ae113e5afb22a94e7f4:e278d8b217f0f65d64a2324b89812d7a380aad9ce29644f1ffc062704f2a51ed7a18376f32c14ad5af39b2fad9ab12152954ac9ea49a14190e8bdcdaa370f45c)
Referer: https://www.gbif.org/dataset/9324c04c-7ac6-4b69-b98c-4472c51c73c5
Window size: width 1410 - height 753
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-06T13:41:24.155Z',mode:absolute,to:'2018-06-06T13:47:24.155Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-06T13:41:24.155Z',mode:absolute,to:'2018-06-06T13:47:24.155Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Sure. Notice that the same has been said for networks. So as you know, the usual issue is: if every field is the most important, then it becomes a mess where no information is promiment. So by that reasoning, I would say the license block (as you suggest). It is prominent, but maintains a hierachy.
