### ISSUE TITLE
Scabiosa pratensis Jord. IS NOT synonym with Knautia arvensis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1386]
**Scabiosa pratensis Jord. IS NOT synonym with Knautia arvensis**

-----

User provided contact info: erik.welk@botanik.uni-halle.de
System: Chrome 66.0.3359 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/01e12f9223d697eb35fa4a6a25c22f55:ede4ad732c20ee4f327f316b0703d3233435e973517d1e3fdefb0a29d49eda03ebd456191db00bebf1010ddac43c49ea1d8df885c11bb0e8c5f009fefdf600d9)
Referer: https://www.gbif.org/species/8426947
Window size: width 1920 - height 900
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-06T15:07:59.944Z',mode:absolute,to:'2018-06-06T15:13:59.944Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-06T15:07:59.944Z',mode:absolute,to:'2018-06-06T15:13:59.944Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
Indeed CoL has it as a synonym for `Scabiosa columbaria subsp. pratensis (Jord.) J. Duvigneaud & J. Lambinon` while `Scabiosa pratensis F. W. Schmidt` is listed as a synonym for `Knautia arvensis subsp. arvensis F. W. Schmidt`

http://www.catalogueoflife.org/annual-checklist/2015/search/all/key/Scabiosa+pratensis/match/1

**Comment by yroskov** [comment]
The comment should be submitted for assessment by World Plants.

**Comment by ManonGros** [comment]
It looks like this has been solved in the new backbone.
