### ISSUE TITLE
ProjectID format varies from dataset API to cms API

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#1388]
dataset https://www.gbif.org/dataset/11f7be1d-fdf3-4753-bfb0-c61ddbde3303/project shows a non linkable project ID because the cms API states the project identifier to have trailing space.

http://api.gbif.org/v1/dataset/11f7be1d-fdf3-4753-bfb0-c61ddbde3303
vs
http://cms-search.gbif.org:9200/project/_search?q=projectId:%22BID-PA2016-0005-REG%20%22
vs
http://cms-search.gbif.org:9200/project/_search?q=projectId:%22BID-PA2016-0005-REG%22

This is a mistake in the contentful data, but might also be worth fixing in the API while indexing?

**Comment by dnoesgaard** [comment]
I removed a trailing space from the contentful item - looks better now, right?
