### ISSUE TITLE
Simple data error causing country mismatch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#139]
**Simple data error causing country mismatch**

The ISO country code for this record of *Neisosperma oppositifolia* is incorrectly entered as VA, when it should be VU—Vanuatu rather than the Holy See (Vatican City State).

Direct to source, at [MNHM](https://science.mnhn.fr/institution/mnhn/collection/p/item/p00515883)? If so, could we ask them to update their GBIF logo? I presume it's repeated more than 5 million times on their site...

-----
fbitem-occurrence438307324
Reported by: @kcopas
System: Safari 10.0.3 / Mac OS X 10.12.3
Referer: https://demo.gbif.org/occurrence/438307324
Window size: width 1137 - height 874
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T11:14:25.266Z',mode:absolute,to:'2017-03-23T11:20:25.266Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T11:14:25.266Z',mode:absolute,to:'2017-03-23T11:20:25.266Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: b5cdf794-8fa4-4a85-8b26-755d087bf531
publishingOrgKey: 2cd829bb-b713-433d-99cf-64bef11e5b3e

**Comment by kbraak** [comment]
@kcopas I have now brought this issue to MNHN's attention over email, including information about where new GBIF logos can be downloaded: http://www.gbif.org/resources/logos Thanks.

**Comment by ahahn-gbif** [comment]
On checking, this seems to be fixed now. Closing
