### ISSUE TITLE
Problems in download data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1391]
**Problems in download data**

Download csv it is not working. Too much time wainting and nothing happened

-----

User provided contact info: luizf@uef.fi
System: Chrome 67.0.3396 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/2588176a11a14961f10eee63d5de9285:1e3e6cd38122200a2de2eff906296c8b2183a206a3edd6f70c102630625d935d2f42966c429e83bbd7e34d01ba7214b3674328c6af3cb21b79a5ff081174c8bb)
Referer: https://www.gbif.org/occurrence/download?has_coordinate=true&has_geospatial_issue=false&year=1952,2018
Window size: width 1366 - height 662
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-11T11:13:43.908Z',mode:absolute,to:'2018-06-11T11:19:43.908Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-11T11:13:43.908Z',mode:absolute,to:'2018-06-11T11:19:43.908Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
the download in case was created 2018-06-11T11:30:09.622+0000 and still isn't done 3 hours later. The website states that it takes around 15 minutes.

**Comment by MattBlissett** [comment]
It took three hours. I'm not sure what was going on.

**Comment by MattBlissett** [comment]
https://github.com/gbif/occurrence/issues/63 should fix this.
