### ISSUE TITLE
renaming data use

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1395]
**renaming data use**

We've discussed options for featuring projects, events, and other types of content that isn't necessarily "data use". Rather than having to add a new content type, we propose renaming "data use" to "feature". 

I'd like to hear your thoughts on this to make sure we don't break anything. For the record, I'm only suggesting make the chance to the portal front-end, not CMS, API, etc.

-----

User provided contact info: @dnoesgaard
System: Chrome 67.0.3396 / Mac OS X 10.13.4
User: [See in registry](https://www.gbif.org/api/feedback/user/43cd66863013571f884eea8491fb0931:c1adaf77cbd642ed5224d222585ab7d09b9e8cdd4e5586b784a4756bce90abb861c9e53c00cc814d7de33f3e3f0571889681e1c3b92b9ddc12f390afb96cb8e9)
Referer: https://www.gbif.org/resource/search?contentType=dataUse
Window size: width 2117 - height 1124
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-12T10:02:55.209Z',mode:absolute,to:'2018-06-12T10:08:55.209Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-12T10:02:55.209Z',mode:absolute,to:'2018-06-12T10:08:55.209Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
![resource_search](https://user-images.githubusercontent.com/21358085/41284320-4933773e-6e39-11e8-9021-e0372aec46c4.png)

So in the translation file, "data use" becomes "feature", and in the navigation menu "featured data use" becomes simply "features".

**Comment by dnoesgaard** [comment]
@timhirsch, @kcopas, inviting you to chip in here...

**Comment by kcopas** [comment]
+1. I think it's more generic, accessible and approachable language. All good things in this context.

**Comment by timhirsch** [comment]
my only worry is that there is merit in guiding the reader on 'what I'm looking at' - as I have already pointed out, I feel the boxes on the homepage could do with short labels to highlight e.g. data use, news, call etc. But if these can be manually curated, the generic title 'feature' is probably fine. I guess once we build up substantial archives of features of different types, we can add a filter to https://www.gbif.org/resource/search?contentType=dataUse

**Comment by dnoesgaard** [comment]
For the homepage, I've already suggested adding the label in https://github.com/gbif/portal16/issues/779

If also introduce a feature "type" as suggested, this could be used for the card label and also as a filter...

**Comment by dnoesgaard** [comment]
Having discussed this further, it appears it might not be the best solution to allow a broader selection of "featured" content. I've asked @MortenHofft to roll this back for now while we explore another solution...
