### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1397]
**Delete account**

I would like to delete my account please

-----

User provided contact info: redacted
System: Chrome 67.0.3396 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/35839ac560b9921b506e28a14dd1fb3f:8bb5db8553eabbf179151439722d1e4d7a16a3da52e6636e7011e3faa3aa165dfb557b51563545ed762ce85f03d28326a99e866a46d203050baf3a1335cbdc9c)
Referer: https://www.gbif.org/faq?q=delete%20account
Window size: width 1280 - height 891
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-12T12:37:30.930Z',mode:absolute,to:'2018-06-12T12:43:30.930Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-12T12:37:30.930Z',mode:absolute,to:'2018-06-12T12:43:30.930Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
User deleted (blanked out) from GBIF.org and GBIF-UAT.org registry databases.
