### ISSUE TITLE
missing coordinates

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1398]
**missing coordinates**

I downloaded records for martes martes from the uk as a csv but there were no coordinates.  Why is that?

Andrew

-----

User provided contact info: arodrigues@gbif.org
System: Chrome 67.0.3396 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/70da570be96db1c7429a9432821d49dd:d55eb7664f993ff126ca01ed6ac1780e5f2790d5897b00cda4544f41e7595c031d9e133245db65b32abdaa5cef3d16ea09068f6f2ee1055f73d516224ca734fd)
Referer: https://www.gbif.org/
Window size: width 1266 - height 602
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-12T19:50:13.370Z',mode:absolute,to:'2018-06-12T19:56:13.370Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-12T19:50:13.370Z',mode:absolute,to:'2018-06-12T19:56:13.370Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
This is referencing downloads
https://www.gbif.org/occurrence/download/0026262-180508205500799
https://www.gbif.org/occurrence/download/0026252-180508205500799
https://www.gbif.org/occurrence/download/0026249-180508205500799
https://www.gbif.org/occurrence/download/0026275-180508205500799

checking download https://www.gbif.org/occurrence/download/0026262-180508205500799
it has coordinates.

For future reference it would be easier if a link to the download in case was provided :)

First line for example 
`1700895972	f14f3ec9-c54a-477d-82c8-f7ba6925534a	238ade98-9a53-482a-9a49-7b2773af5277	Animalia	Chordata	Mammalia	Carnivora	Mustelidae	Martes	Martes martes		SPECIES	Martes martes (Linnaeus, 1758)	GB		9ee06e28-a444-42cd-b34e-ba317f1c6b44	58,02	-3,95	1000						2014-10-01T02:00Z		10	2014	5218878	5218878	HUMAN_OBSERVATION						CC_BY_NC_4_0		x @hydrobates			2018-02-02T21:14Z		`

coordiantes **58,02 -3,95**
