### ISSUE TITLE
help publishers and dataset owners locate relevant issues

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#14]
**help publishers and dataset owners locate relevant issues**

when issues is created about an occurrence, then add the dataset key and publisher key so that fx publishers kan search for content issues related to their data.

same goes for datasets and species (non backbone)

-----
fbitem-occurrence1265894407
Reported by: @mortenhofft
System: Chrome 55.0.2883 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/occurrence/1265894407
Window size: width 1974 - height 1129

**Comment by MortenHofft** [comment]
on occurrence issues the dataset and publisher key is added with https://github.com/gbif/portal16/commit/9508a823b644725bba11b891ad24439d7f5c1dd9

For dataset issues the datasetkey is there, but not the publisher key.

If we see publishers and others starting to contribute, we can expand with additional tagging on species and datasets. possible also with country. For now this seems sufficient I would say. 

example of searching: [search for datasetKey](https://github.com/gbif/portal-feedback/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20fbb80520-f927-4ce0-a7a8-fda964bc33e5)
