### ISSUE TITLE
[Title unknown] in NamePublishedIn

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#140]
**[Title unknown] in NamePublishedIn**

>Published in Barbosa Rodriguez, J. 1886. [Title unknown].

Looks like the data could need a bit of cleaning

-----
fbitem-datasetb9a214b7-c368-4d22-aa53-b1fc16a1210a
Reported by: @mortenhofft
System: Chrome 56.0.2924 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/dataset/b9a214b7-c368-4d22-aa53-b1fc16a1210a/taxonomy/127518077
Window size: width 1912 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T11:33:22.022Z',mode:absolute,to:'2017-03-23T11:39:22.022Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T11:33:22.022Z',mode:absolute,to:'2017-03-23T11:39:22.022Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
Appears to be handled under #142 now - closing here
