### ISSUE TITLE
Bersama hebecalyx: location China

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1402]
**Bersama hebecalyx: location China**

I checked the photo of the specimens of Bersama hebecalyx from China and unfortunately the record is clearly not of a Bersama. It would have been interesting to see a Bersama so far from the main range.
Can it be removed?

-----

System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5ba5759de2dafa1543561324fda87725:ad13466304a763eb768d08ecd9b901cbc98fac5e6d58b1a14ce51c0fd5f186c62aea8fbff0b9dadaba2186df89f07f667f0a9bfab01e6c125cc2f022f81fc85e)
Referer: https://www.gbif.org/faq
Window size: width 1920 - height 915
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-14T07:43:38.022Z',mode:absolute,to:'2018-06-14T07:49:38.022Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-14T07:43:38.022Z',mode:absolute,to:'2018-06-14T07:49:38.022Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I assume this issue is about this occurrence: https://www.gbif.org/occurrence/919461952 since it is the only occurrence of Bersama hebecalyx in China we have, but there is no image. How can the user know it is not correct species?

**Comment by MattBlissett** [comment]
The source links through to http://www.cvh.ac.cn/spm/PE/01591280

**Comment by ManonGros** [comment]
The publishers have been notified.

**Comment by ManonGros** [comment]
I received a reply from the publishers about this specimen:
>  Bersama hebeca in not a native species of China. The specimen was collected from Xishuanbanna Tropical Gardens. It seems that it may be introduced from Africa.

See Helpdesk email from the 2018-02-18.
