### ISSUE TITLE
failing images

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1403]
**failing images**

the image cache seem to have issues with these URLS

`https://www.gbif.org/occurrence/gallery?dataset_key=83ae84cf-88e4-4b5c-80b2-271a15a3e0fc`

example: http://api.gbif.org/v1/image/unsafe/500x/http%253A%252F%252Fapi.aucklandmuseum.com%252Fid%252Fmedia%252Fv%252F105387%253Frendering%253Doriginal.jpg

is pointing to https://api.aucklandmuseum.com/id/media/v/105387?rendering=original.jpg

-----

System: Chrome 65.0.3325 / Mac OS X 10.11.6
User: [See in registry](https://www.gbif.org/api/feedback/user/0e05119c7826b9f2d5b0b565153135ad:2f3b1c5491e54580716e9e037907868b8bec44c4d628285bd25c83961378fdeb08eebf1d2c2adaf7d60a84590e0ff12129ec881df04022ad292bfea13c6348d6)
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=83ae84cf-88e4-4b5c-80b2-271a15a3e0fc
Window size: width 2065 - height 1320
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-14T09:40:35.061Z',mode:absolute,to:'2018-06-14T09:46:35.061Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-14T09:40:35.061Z',mode:absolute,to:'2018-06-14T09:46:35.061Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
That's an odd case.

The image cache was only getting a few hundred bytes in the response, which turned out to be like this:

```
curl -H 'Accept:' https://api.aucklandmuseum.com/id/media/v/105387?rendering=original.jpg
{
  "am:lastModifiedOn": [
    {
      "type": "datetime",
      "value": "2017-09-21T03:56:48.108Z"
    }
  ],
  "am:mediaLocation": [
    {
      "type": "string",
      "value": "Natural History\\Botany\\AK200001-AK300000\\290001-300000\\298001-299000\\AK298350a.JPG"
    }
  ],
  "am:metadata": [
    {
      "type": "uri",
      "value": "http://api.aucklandmuseum.com/id/media/v/105387/metadata"
    }
  ],
  "am:record_score": [
    {
      "type": "int",
      "value": "0"
    }
  ],
  "ecrm:P75_possesses": [
    {
      "type": "uri",
      "value": "http://api.aucklandmuseum.com/id/media/v/105387/rights"
    }
  ],
  "rdf:type": [
    {
      "type": "uri",
      "value": "ecrm:E38_Image"
    }
  ]
}
```

It's because the `Accept` header wasn't being set by Thumbor, see https://github.com/thumbor/thumbor/issues/1087

I've patched our server, so: https://www.gbif.org/occurrence/gallery?dataset_key=83ae84cf-88e4-4b5c-80b2-271a15a3e0fc

Also relates to https://github.com/gbif/portal-feedback/issues/19.
