### ISSUE TITLE
Occurrences are mapped to doubtful species: Phaeocollybia jennyae (P.Karst.) R.Heim

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal-feedback#1404]
Occurrences are mapped to doubtful species, eventhough there is an accepted species with the same canonical name.

This species is correctly flagged as doubtful since it is Nom. Illeg.: https://www.gbif.org/species/8155142 but some occurrences are mapped to it.

Occurrences should probably be mapped to this accepted species: https://www.gbif.org/species/2528569

https://www.gbif.org/occurrence/search?taxon_key=8155142&taxon_key=2528569

**Comment by jhnwllr** [comment]
@thomasstjerne any idea how to fix this?

**Comment by thomasstjerne** [comment]
@jhnwllr I added it to the Backbone patch
