### ISSUE TITLE
User reported inaccurate spelling

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1406]
**User reported inaccurate spelling**

- Phylloscopus sibilatrix should be "Phylloscopus sibilatrix" instead according to:
Veljo Runnel
Citizen Science expert
University of Tartu Natural History Museum `http://natmuseum.ut.ee`

-----

User provided contact info: @jlegind
System: Chrome 64.0.3282 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4fb6ffd41fc9b34088698555452691f7:1119c24a9570a8c841ab8b250042274b7c65be75ec96a22830f87a7a284c289b7aff66d27b5e051b0dd75280e9f83b99e8557e705f776ccce8e966c7ca36bfd9)
Referer: https://www.gbif.org/species/8128385
Window size: width 2560 - height 1309
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-15T07:48:10.559Z',mode:absolute,to:'2018-06-15T07:54:10.559Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-15T07:48:10.559Z',mode:absolute,to:'2018-06-15T07:54:10.559Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
This issue was moved to gbif/checklistbank#63
