### ISSUE TITLE
Broken links for 3 BID 2015 national projects

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1408]
**Broken links for 3 BID 2015 national projects**

These three national projects links are broken:
* Capacity building and biodiversity data mobilization to address health and food security priorities in Benin
* Building capacity in the Democratic Republic of Congo (DRC) to establish an effective GBIF Participant node
* Strengthening the biodiversity stakeholders network in Togo

-----

System: Chrome 67.0.3396 / Mac OS X 10.13.5
User: [See in registry](https://www.gbif.org/api/feedback/user/76d52c14d7a0d936da6b7ed5540456b6:42ec6714ead0ad426fbfb3c7e1d9075a2aba32a89717d9f4b8240d0039218fdb8076de97206399fcf500893935673f2d3c9219e28cd51b4fc37070cadd15e3d1)
Referer: https://www.gbif.org/news/82784/first-bid-grants-provide-nearly-euro1-million-in-funding-to-23-african-projects
Window size: width 1280 - height 1101
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-15T13:35:31.690Z',mode:absolute,to:'2018-06-15T13:41:31.690Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-15T13:35:31.690Z',mode:absolute,to:'2018-06-15T13:41:31.690Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
The item in question is a news item and the contents were accurate at the time of writing. I'm ok with fixing broken links, but changing the contents seems like rewriting history, which I don't think is accurate nor helpful.

@kcopas if you disagree, please let me know.

**Comment by dnoesgaard** [comment]
Rather than creating a new page, I've simply added _project discontinued_ to the project name in the list.
