### ISSUE TITLE
Different metadata - same dataset - registry API

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#1409]
In order to look at all the metadata of the datasets published by Togo, I used the following query:
http://api.gbif.org/v1/dataset?country=TG&limit=100

In the result of this query there is the dataset titled "[Djamde Wildlife Reserve in Togo: diversity of woody species](https://www.gbif.org/dataset/966b3e29-f1e4-4190-badd-100bc989788f)". This dataset has exhaustive metadata as you can see on the webpage and on the API using this other query:
http://api.gbif.org/v1/dataset/966b3e29-f1e4-4190-badd-100bc989788f

But with the first query, the metadata of this dataset is different, it is missing taxonomic coverage, temporal coverage, methods, etc.

**Comment by MortenHofft** [comment]
There is no guarentee that the full object is included in the search results. If I remember correctly that is also the case for some of our other endpoints. So you need to go to the `key`in some cases.

And further there are two dataset endpoints (and 2 species search endpoints) - the second one being driven of SOLR, the first of postgres (if I remember the implementation correctly).

http://api.gbif.org/v1/dataset?country=TG&limit=100
http://api.gbif.org/v1/dataset/search?publishingCountry=TG&limit=100

You probably want to be using the second (SOLR) one. Hope that helps.
