### ISSUE TITLE
publishedIn contains internal comments

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#141]
**publishedIn contains internal comments**

>Miller, Philip. 1754. [Title Not Known, please research and update]. [Unspecified Publisher]: [includes page check].

Looks like the data could need a bit of cleaning

-----
fbitem-species2684876
Reported by: @mortenhofft
System: Chrome 56.0.2924 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/species/2684876
Window size: width 1912 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T11:35:13.414Z',mode:absolute,to:'2017-03-23T11:41:13.414Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T11:35:13.414Z',mode:absolute,to:'2017-03-23T11:41:13.414Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
relates to https://github.com/gbif/portal-feedback/issues/142
