### ISSUE TITLE
change in tenses etc needed for ENC 2018 webpage

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1410]
**change in tenses etc needed for ENC 2018 webpage**

Hi comms, please chance the tenses and check the content so that it reads well for the ongoing call.

When editing, please check with GBIF Science Committee Chair <sc-chair@gbif.org> for possible updates on jury etc, cc me

Kindly prepare the one slide announcement version for use by GBIF staff, committees, and in the future, by the ambassadors.

-----

User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/aec15658875cc8f01f8d96bc8830bd55:8019c2b103af00f8558896846191a853a3f227ed76fa0537fa49940aa832a78c502cd4d2301a81007ea4933820d55923e5871273a4991cac008fbb18be103ff1)
Referer: https://www.gbif.org/news/2W274u835u4UAoQqEOyIIA/2018-gbif-ebbe-nielsen-challenge-to-open-on-9-may-2018
Window size: width 1696 - height 818
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-16T10:30:29.958Z',mode:absolute,to:'2018-06-16T10:36:29.958Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-16T10:30:29.958Z',mode:absolute,to:'2018-06-16T10:36:29.958Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
That's the wrong news item @dschigel—it's the pre-release version.

The correct one is here:
https://www.gbif.org/news/1GQURfK5jS4Iq4O06Y0EK4

My question to you (and to @dnoesgaard @MortenHofft @thomasstjerne) is whether the older one is sufficiently widespread to warrant a redirect PRIOR to archiving it. 

[looks at watch…]

**Comment by kcopas** [comment]
Yes, we'll archive it—technical question first.

**Comment by kcopas** [comment]
Tusind tak @MortenHofft !
