### ISSUE TITLE
Why share data?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1412]
**Why share data?**

Dear GBIF team, I work with natural history museums in South Africa and one of my roles is to promote open data sharing. In the article on your site at this link, `https://www.gbif.org/news/82363/new-approaches-to-data-licensing-and-endorsement,` it says that 'GBIF will ... develop information resources to explain and promote the value of adopting open data licences'. Could you point to any such resources that might be available? Many thanks!

-----

User provided contact info: ianicus.za@gmail.com
System: Chrome 67.0.3396 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e3a71e2fad09ed43628f69a219d54456:56b625a16bd44881ea43a35ea00b1a5ce0fb341ac7e12e497febd3fcc32ada1aa7c46a5df79a7af52fed3c240aee72b98b8e98b635e288ab71fca519ccc75af4)
Referer: https://www.gbif.org/news/82363/new-approaches-to-data-licensing-and-endorsement
Window size: width 1280 - height 566
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-19T11:29:25.815Z',mode:absolute,to:'2018-06-19T11:35:25.815Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-19T11:29:25.815Z',mode:absolute,to:'2018-06-19T11:35:25.815Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
@gbif/comms probably.

**Comment by dnoesgaard** [comment]
@kcopas, do you know if any such "resources" have been "developed"?

**Comment by kcopas** [comment]
One 'in development' from many, many months ago (there was a pretty boring version on the old site). 

I've been wanting to revisit and complete a draft. Coming your way shortly.

**Comment by kcopas** [comment]
Over to you, D-Nø…

**Comment by dnoesgaard** [comment]
website draft: https://www.gbif.org/article/4J0djzlbQ4yUmSOkmGMuaI/_preview

I recently copied over a section from the old website on "incentives of sharing data" - is that what you were referring to? https://www.gbif.org/publishing-data#incentives

I will happily get rid of that chunk and link to the new page instead, if you agree?

**Comment by kcopas** [comment]
I think we might need a one-sentence intro, which could easily be crafted from the incentives bit, but we should also add a sentence to each of these three:

+ Fulfill the open data policies of research publishers.
+ Make it easier for funders and potential employers to see your work.
+ Increase citations of your research

**Comment by timhirsch** [comment]
Without digging into the detail of this, just to flag that @laurarussell has been developing a segment around 'why publish' for the data mobilization course, still in the 'continuous improvement' phase. Not to discourage having a single page on this - we need it - but just to say the messages in both efforts should be coordinated, and as far as possible backed up by evidence and example.

**Comment by MattBlissett** [comment]
Closing an old issue that is probably resolved, please reopen if you need to.
