### ISSUE TITLE
it would be much more helpful if the list of occurrences included the name of the collector and ideally the collection number

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1417]
**it would be much more helpful if the list of occurrences included the name of the collector and ideally the collection number**

I use GBif to locate type specimens, in the current format I can only do this by checking each record from the relevant country.  It would be extremely helpful if the output could include further information on the collector and collection number enabling me to identify potential types.

-----

User provided contact info: m.gilbert@kew.org
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/9463b6dde3993133f7e5575cc0f236ff:bd1e2e4e324e071aef825d5ed939d4ee7de8cc99aa60d1c64e79a9a1dd01feb7f66a2126798c86a4625519df639a93c06b0f128c92c2e9b5e7d359b1d797e5e9)
Referer: https://www.gbif.org/occurrence/874732627
Window size: width 1110 - height 564
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-21T16:41:17.434Z',mode:absolute,to:'2018-06-21T16:47:17.434Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-21T16:41:17.434Z',mode:absolute,to:'2018-06-21T16:47:17.434Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thank you for your feedback

You might already know this, but you can [filter for type specimens](https://www.gbif.org/occurrence/search?type_status=HOLOTYPE&type_status=EPITYPE), but this will only show you occurrences where the publisher has stated that it is a type.

You can also filter for [preserved specimens](https://www.gbif.org/occurrence/search?basis_of_record=PRESERVED_SPECIMEN) - again it reflects the data stated by the publisher.

I have also added an option to customize the table columns

![screen shot 2018-06-22 at 13 57 59](https://user-images.githubusercontent.com/6759267/41776011-6ca66844-7626-11e8-95b6-da500f9d05c6.png)

Hope it helps. The new version will be in production early next week.
