### ISSUE TITLE
Classpath clash on occurrence-download v0.82.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1418]
**Solanum arenarium**

It is not available for download. It says Broken download.

-----

User provided contact info: carolinakaiserschnitzler@gmail.com
System: Chrome 67.0.3396 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/445c0d365c8e65e852782e9caf00b9d1:a8a1f4cc3b63c4b73879029db8739e414ef222fe735635eca1790e57657999740d758f70e8b54b697a4ef71759e29ebde9c5d5c1a314dd496078efe1ff289474)
Referer: https://www.gbif.org/occurrence/download/0031262-180508205500799
Window size: width 1304 - height 702
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-21T18:58:38.134Z',mode:absolute,to:'2018-06-21T19:04:38.134Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-21T18:58:38.134Z',mode:absolute,to:'2018-06-21T19:04:38.134Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Intermittent fault due to (probably) classpath clash. Occurrence-download rolled back to 0.80, user emailed.

**Comment by MattBlissett** [comment]
This was one of the fixes in the last month.
