### ISSUE TITLE
Polygon geometries being doubled/tripled for downloads

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1419]
**Polygon geometries being doubled/tripled for downloads**

The geometry appears twice, which is weird.

This also happened with downloads I tried this afternoon:

`https://www.gbif.org/occurrence/download/0031035-180508205500799`

`https://www.gbif.org/occurrence/download/0031034-180508205500799`

-----

User provided contact info: @MattBlissett
System: Firefox 60.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/514b95fef7499ac89bccca2ac611b808:349889bb48989bdc19340b8f7ef623b4bfe7f1f99d0e5fead790c3b3b974fdf5a81c9814cee798337786c7836b862784f0dcdaf977a8582469c221e5933cb0a9)
Referer: https://www.gbif.org/occurrence/download/0031355-180508205500799
Window size: width 1912 - height 945
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-21T22:11:50.639Z',mode:absolute,to:'2018-06-21T22:17:50.639Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-21T22:11:50.639Z',mode:absolute,to:'2018-06-21T22:17:50.639Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Ah, it is the "Rerun query" link that is adding an extra argument.
