### ISSUE TITLE
Migrate the "data quality requirements" docuementation into a single location

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/portal-feedback#1422]
Information on data quality requirements is presently available from two different locations in almost (but not quite) identical form: the gbif.org site, and the BID program-specific pages. With the BIFA program starting up, we not only want to avoid generating a third instance, but rather consolidate the information into a single, central location

Present locations:
- https://www.gbif.org/data-quality-requirements, linked from https://www.gbif.org/publishing-data under "Prepare data for publication", and sub-sections in linked pages
- https://bid.gbif.org/en/community/data-quality/, linked from the main menu (Grantee commmunity -> data quality requirements, and sub-sections in linked pages

Suggested steps:
- [x] Update the content at gbif.org to include the following information, relevant to funded programs run by GBIF:
- https://www.gbif.org/data-quality-requirements-occurrences:
-- Darwin core records -> countryCode: change to "Strongly recommended" rather than "Required", both in the list, and in the section describing the terms further down
-- after "Dataset metadata (EML), suggested to add a separate paragraph for better highlighting / visibility: "If the dataset is funded through a program run by GBIF (e.g. BID, BIFA, CESP), these two additional fields are required: "
--> list : projectID - Required; projectTitle - Required
-- add two new paragraphs in the Terms glossary further down to explain projectID (copy from https://bid.gbif.org/en/community/data-quality/#emlProjectID, extend to also name BIFA, CESP) and projectTitle (requires a new paragraph: the title of the funded project as listed in the contract document, but not containing the projectID and other administrative information. E.g.  [see project titles at https://www.gbif.org/programme/82243/bid-biodiversity-information-for-development#projects]
-- license paragraph under "Terms": change "(...) funded under the BID programme (...)" to "(...) funded under the BID and BIFA programmes (...)"
- https://www.gbif.org/data-quality-requirements-checklists
-- same changes as sketched above for adding projectID and projectTitle to the metadata section, incl. leader paragraph, and the Terms glossary
-- same change as sketched above for the Terms section on Licenses
- https://www.gbif.org/data-quality-requirements-sampling-events
-- same changes as sketched above for adding projectID and projectTitle to the metadata section, incl. leader paragraph, and the Terms glossary
-- same change as sketched above for the Terms section on Licenses
-- same change as sketched above for setting countryCode from "Required" to "Strongly recommended" in two places

- [ ] Remove the detailed information from the BID context, and reference the central documentation.

**Comment by kcopas** [comment]
@MortenHofft is it possible to keep 'Data quality requirements' in the navigation of the BID grantees' static site, remove the page and redirect it to https://www.gbif.org/data-quality-requirements? 

It's nice having the issue flagged there, even if we redirect the to GBIF.org. 

Please advise—this is the last bit of this issue that needs to be resolved.

**Comment by MortenHofft** [comment]
Sure just do:

```
---
title: External link
type: link
link: https://www.gbif.org/data-quality-requirements
---

Content won't be shown if type link
```

changed in https://github.com/gbif/ssg-bid/blob/master/content/02-Community/05-data-quality/en.md and building to UAT

**Comment by kcopas** [comment]
Thanks @MortenHofft !

**Comment by ManonGros** [comment]
Now that the BID data requirements have been migrated to https://www.gbif.org/data-quality-requirements, the page https://bid.gbif.org/en/community/data-quality/ is no longer working, is there anyway we could redirect it instead? (I have been sending this link to many publishers previously)

**Comment by MattBlissett** [comment]
Done.
