### ISSUE TITLE
Rubus robii Leiden specimen is from GB not NG

### ISSUE THREAD

**Issue by RenataBoros** [gbif/portal-feedback#1424]
Thanks!

**Comment by RenataBoros** [comment]
And so is Rubus subinermoides.

**Comment by ManonGros** [comment]
Thank you @RenataBoros but we need some context in order to help. Could you tell us which record you are referring to? Please send us a link

**Comment by MattBlissett** [comment]
Presumably this one, as there's only one occurrence of this species: https://www.gbif.org/occurrence/1140379327

**Comment by RenataBoros** [comment]
Hi Matt,
That's the one. Thanks,

Renata

On 24 Aug 2018, at 23:07, Matt Blissett <notifications@github.com<mailto:notifications@github.com>> wrote:


Presumably this one, as there's only one occurrence of this species: https://www.gbif.org/occurrence/1140379327<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gbif.org%2Foccurrence%2F1140379327&data=02%7C01%7Cr.borosova%40kew.org%7C477be051811e4b86279b08d60a0e0147%7C44892b45194046119753a4b3be4ea7fe%7C0%7C0%7C636707452686510809&sdata=NUHejB3gOIiRAujHLZxmRGmul8T2XWbaN9%2BwIvV2L1w%3D&reserved=0>

**Comment by ManonGros** [comment]
It seems that this occurrence is from [Naturalis Biodiversity Center (NL) - Botany](https://www.gbif.org/dataset/15f819bd-6612-4447-854b-14d12ee1022d)
Perhaps @jeroencreuwels could forward this to the relevant person?

**Comment by ManonGros** [comment]
Occurrence link changed.
The dataset concerned is [Naturalis Biodiversity Center (NL) - Botany](https://www.gbif.org/dataset/15f819bd-6612-4447-854b-14d12ee1022d)
The link to original data is http://data.biodiversitydata.nl/naturalis/specimen/L.4191805

**Comment by jeroencreuwels** [comment]
I checked record https://www.gbif.org/occurrence/2289462571 and the species is Robus robii and the country is United Kingdom (this holds also true for L.4191805 in our source BRAHMS database)
If another country(code) had been given earlier, then we have changed that in the meantime. The current country is correct.
