### ISSUE TITLE
no of occurrences from 1 dataset in download...

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1425]
**no of occurrences from 1 dataset in download...**

This dataset contains 54 records - however, in the 3 "no filters used" downloads, it says "108 occurrences from this dataset"

??

-----

User provided contact info: @dnoesgaard
System: Chrome 67.0.3396 / Mac OS X 10.13.4
User: [See in registry](https://www.gbif.org/api/feedback/user/d20293b857ab81309b48942f69248f91:5fa859f8f8064c4aa03b331a49fcdaa78ec90be29648a5b80877081eee94b2500fe84ad1388fa3985af40f4e657f7d2c31d49ff26ddf7301a81d7cbde5687e21)
Referer: https://www.gbif.org/dataset/0c77bfef-bbbc-43f9-9583-98bd4b9d5b77/activity
Window size: width 1818 - height 1119
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-22T14:02:55.443Z',mode:absolute,to:'2018-06-22T14:08:55.443Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-22T14:02:55.443Z',mode:absolute,to:'2018-06-22T14:08:55.443Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
closed in favour of https://github.com/gbif/portal-feedback/issues/1430
