### ISSUE TITLE
Option to download species list of dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1426]
**Option to download species list of dataset**

I would like to option to download the list of species contained in a dataset as a CSV. Columns I would like to have included are:

- scientific name as published by source
- GBIF matched scientific name
- GBIF taxon key
- GBIF taxon status (optional)
- Number of occurrences (optional)

It would look for this in the download dropdown, but you could also see it as a download of the `taxonomic distribution of occurrences` metric.

-----

User provided contact info: @peterdesmet
System: Chrome 67.0.3396 / Mac OS X 10.13.3
User: [See in registry](https://www.gbif.org/api/feedback/user/499acbb83426f77e34ed4cf251ef51fe:cca98337b83903f430fdbddb89cb89347809cef68b1f4a88f01670c30895b58ac5013b10b1a0d7717bfcf35790c53e6bb881341821b268da68d6ffd658f33953)
Referer: https://www.gbif.org/dataset/271c444f-f8d8-4986-b748-e7367755c0c1/metrics
Window size: width 1300 - height 803
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-26T08:34:58.253Z',mode:absolute,to:'2018-06-26T08:40:58.253Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-26T08:34:58.253Z',mode:absolute,to:'2018-06-26T08:40:58.253Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
This is implemented (some months ago now) with the SPECIES_LIST type download.
