### ISSUE TITLE
interpretation of associatedMedia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1427]
**interpretation of associatedMedia**

I've noticed that for Naturalis we have *no* images, but in their DwC archives, they include direct URL of images in "associatedMedia". This gets interpreted as
 
```
"media": [
{
"references": "url"
}
```

meaning that the image is not shown.

Is this a mistake in interpretation?

-----

User provided contact info: @dnoesgaard
Referer: https://www.gbif.org/occurrence/1850873036

**Comment by MattBlissett** [comment]
http://rs.gbif.org/extension/gbif/1.0/multimedia.xml

It is a mistake in mapping. References is "An html webpage that shows the image or its metadata".

The minimum mapping required is:

```
"media": [
    {
        "format": "image/jpeg",
        "identifier": "http://api.aucklandmuseum.com/id/media/v/465986?rendering=original.jpg"
    }
],
```

I wonder if we have some bad documentation somewhere, the same error has been made in several datasets.

**Comment by MattBlissett** [comment]
Ah, sorry. This dataset is using an http://rs.tdwg.org/dwc/terms/associatedMedia term, not an extra Multimedia extension.

In that case, we assume URLs are to HTML pages unless they end in .JPG or similar. If URLs aren't recognizable like that, it's necessary to use the multimedia extension.

**Comment by dnoesgaard** [comment]
So to solve this, the publisher should 

- either add an extension to the URLs in associatedMedia, or
- use the multimedia extension to map the URL straight to "identifier"

In the latter case, do we need more than "identifier" to show the image, e.g. "type", "format"?

**Comment by MattBlissett** [comment]
Yes, and in the latter case you need both the identifier and the format (as above).

**Comment by ManonGros** [comment]
The occurrence referenced is no longer visible. @dnoesgaard and @MattBlissett, do you remember which dataset was concerned? Has anyone contacted the publishers?

**Comment by MattBlissett** [comment]
It would have been this one: https://www.gbif.org/dataset/15f819bd-6612-4447-854b-14d12ee1022d

New example: https://www.gbif.org/occurrence/1804653091

**Comment by ManonGros** [comment]
I just sent an email to @jeroencreuwels to let him know about this issue.

PS: I am also adding the link to our new [blog post](https://data-blog.gbif.org/post/gbif-multimedia/) here, it might be useful.

**Comment by jeroencreuwels** [comment]
Thanks all for comments on this issue and the way the images of the Naturalis Botany collection are (not) shown.  Long ago we already noticed that no images were shown and that this was caused because we were not using a media extension. We are busy in making changes in our DwCAs, and in particular in adding a multimedia extension when we have images for that dataset.

**Comment by ManonGros** [comment]
Naturalis published now images for their collections.
