### ISSUE TITLE
Datasets related to the BID project not showing up on the project page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1428]
**Datasets related to the BID project not showing up on the project page**

The Tanzanian REDD+ project published five datasets so far. On the dataset pages, the project information shows as liked via the "Project" tab, which means that the project information is read correctly from the dataset metadata. The corresponding project page at `https://www.gbif.org/project/82753/publishing-metadata-for-biodiversity-data-generated-from-redd-projects-in-tanzania,` however, does not have a "Datasets" tab.

The datasets concerned:
- `https://www.gbif.org/dataset/7fa4ed8c-e879-465f-acd2-2e65f398cc96/project`
- `https://www.gbif.org/dataset/4405aa78-0622-4f21-a37c-75a0dbe7ca7b/project`
- `https://www.gbif.org/dataset/53ba0073-4eda-44a7-8ebd-b59219b3613a/project`
- `https://www.gbif.org/dataset/253fa82c-65ec-4f92-8892-c54b864dfd68/project`
- `https://www.gbif.org/dataset/5e5d014b-2bd1-45b2-a266-af3064370085/project`

Requires investigation why the datasets are missing from the project page.

-----

User provided contact info: @ahahn-gbif
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/8bb11a305a106318ceca89a4cd80adec:a7eb28ad1c92e2137e901f4a630d07c934cbefb55ebd4a2a182ed2a44640ad00967ff9bf5cff6935cb9c33c5b84bb08a64b18629af71b47799ec5f6ff2577cfb)
Referer: https://www.gbif.org/project/82753/publishing-metadata-for-biodiversity-data-generated-from-redd-projects-in-tanzania
Window size: width 1015 - height 844
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-26T14:32:31.841Z',mode:absolute,to:'2018-06-26T14:38:31.841Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-26T14:32:31.841Z',mode:absolute,to:'2018-06-26T14:38:31.841Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
**A first step to finding the reason**
Unlike other dataset with a project identifier these ones for some reason do not appear with one in the SOLR index. 
For example a search for [Tree Species Occurrence in Miombo Woodland of Tanzania](https://www.gbif.org/api/dataset/search?q=Tree%20Species%20Occurrence%20in%20Miombo%20Woodland%20of%20Tanzania) doesn't list a projectIdentifier, but there is one when asking for the item https://api.gbif.org/v1/dataset/7fa4ed8c-e879-465f-acd2-2e65f398cc96

So it doesn't show because https://www.gbif.org/api/dataset/search?limit=500&projectId=BID-AF2015-0069-SMA returns empty

**Comment by MattBlissett** [comment]
Fixed by reindexing the dataset index.
