### ISSUE TITLE
Add publishingOrg facet to occurrence search

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#143]
**Add publishingOrg facet to occurrence search**

This facet is currently supported on the dataset search page. 

This feature appears to be frequently requested for. 

Fortunately this facet is already supported in our API, e.g. http://api.gbif.org/v1/occurrence/search?limit=0&amp;facet=publishingOrg&amp;publishingOrg.facetLimit=1000&amp;publishingOrg.facetOffset=0 

https://github.com/gbif/portal-feedback/issues/49 suggests a negative filter by publisher would also be nice to have.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
Reported by: @kbraak
System: Firefox 52.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/occurrence/search?advanced=1
Window size: width 1424 - height 1017
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T13:13:02.952Z',mode:absolute,to:'2017-03-23T13:19:02.952Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T13:13:02.952Z',mode:absolute,to:'2017-03-23T13:19:02.952Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi Kyle I believe there is general agreement on this. But until there is API support for searching publishers with autocomplete it cannot really be added to occurrence search. I have logged an issue with @fmendezh and this is a good reminder

**Comment by MattBlissett** [comment]
Looks to have been implemented.
