### ISSUE TITLE
Juncaceae now Magnoliales not Poales

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1431]
**Juncaceae now Magnoliales not Poales**

When did this happen or is this like like pelicans becoming dinosaurs which at least is in a way correct.

-----

User provided contact info: kangus@hotkey.net.au
System: Chrome 66.0.3359 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/f72fd661d84de4ef578d738cc40f7895:192a82b637ae213f939e2cb5fc0b5a619bfa8270bfbe59b0664554e1037752fa16162bf090a6b9ae306c2edfe952bc03ef8b32a2f4d952a417c342abaf0c1757)
Referer: https://www.gbif.org/species/5353
Window size: width 1877 - height 898
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-27T20:20:17.496Z',mode:absolute,to:'2018-06-27T20:26:17.496Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-27T20:20:17.496Z',mode:absolute,to:'2018-06-27T20:26:17.496Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
No, indeed not correct and probably a CoL error.
APG IV has it still as Poales and glady the new backbone to go live too:
https://en.wikipedia.org/wiki/APG_IV_system
https://www.gbif-uat.org/species/5353
