### ISSUE TITLE
Definition missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1433]
**Definition missing**

As discussed in the Participation and engagement meeting on 28 June 2018, a clear definition of Mentor role is needed and a differential diagnosis with similar & potentially confusing roles

-----

User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/cc9d8ae8bfcdf8b9e339b7146a28d2e9:d3bfcb89dfb40a9733a27b00100284da0d2f0457cd1169d226c25306f207cb43fef069ffcfbbddcd20c7c20074ea3ae1bcadd54a9acf3cf01ac82e80fd6615a4)
Referer: 
Window size: width 1408 - height 679
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-28T13:20:05.055Z',mode:absolute,to:'2018-06-28T13:26:05.055Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-28T13:20:05.055Z',mode:absolute,to:'2018-06-28T13:26:05.055Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Preview URL removed from issue: not for public consumption

**Comment by ManonGros** [comment]
Can we close this issue @dschigel ?
