### ISSUE TITLE
Wrong Phylum

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1435]
**Wrong Phylum**

This specie is not part of Arthropoda, but must be : Mollusca / Gastropoda / Caenogastropoda / Tylostomidae / Pterodonta , according to `https://science.mnhn.fr/institution/mnhn/collection/f/item/a52057?lang=fr_FR`

-----

System: Chrome 67.0.3396 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/62bcfd1e19c66993f9e56c4a7f79f1d0:234647be06b0bc867668d1653ab82cdf4acf6bb1f6c47850e918794896e54d11d62d4928c99fabb2f5b0088fdf706c0c23b4c03507b72d3a36c91f447913937b)
Referer: https://www.gbif.org/occurrence/417216537
Window size: width 1920 - height 947
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-02T08:37:00.704Z',mode:absolute,to:'2018-07-02T08:43:00.704Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-02T08:37:00.704Z',mode:absolute,to:'2018-07-02T08:43:00.704Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
The species for this occurrence is under "Mollusca" not "Arthropoda". The phylum seems to be correct.
