### ISSUE TITLE
We would like to add our collections to your database

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1438]
**We would like to add our collections to your database**

I work at the Cambridge University Botanic Garden as Assistant Curator. We would like to add our collections to your database but we don't know 1) How to do it and 2) How to update it (since our collection is of living organisms they need to be regularly updated). Thank you and all the best

-----

User provided contact info: ac2202@cam.ac.uk
System: Safari 11.1.1 / Mac OS X 10.12.6
User: [See in registry](https://www.gbif.org/api/feedback/user/e3f1df2ef3849061087675bd1e00d65e:7a29ff85896a9e5aa0d1b510d625e8b5ec57295e359db741ffc6e628571021424512e12abc1e35f5bc1cf1c4b8e5ebfc5b5e7e9590231a4ed5dc9da559ac3bfc)
Referer: https://www.gbif.org/user/profile
Window size: width 1429 - height 893
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-04T09:01:24.999Z',mode:absolute,to:'2018-07-04T09:07:24.999Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-04T09:01:24.999Z',mode:absolute,to:'2018-07-04T09:07:24.999Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
FAO @gbif/content.

**Comment by ManonGros** [comment]
Contacted by email.
