### ISSUE TITLE
Would be nice for system to generate notification when a dataset is deleted

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#144]
**Would be nice for system to generate notification when a dataset is deleted**

I only bumped onto this deleted dataset by chance because I knew about it and wanted to refer to it. 

http://www.gbif.org/dataset/066847b6-8774-4ab2-9371-14659449ab66

Would be nice for system to generate notification to Data Manager when a dataset is deleted

-----
fbitem-dataset066847b6-8774-4ab2-9371-14659449ab66
Reported by: smasinde@gbif.org
System: Chrome 56.0.2924 / Windows 10 0.0.0
Referer: https://demo.gbif.org/dataset/066847b6-8774-4ab2-9371-14659449ab66
Window size: width 1536 - height 782
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T14:08:29.970Z',mode:absolute,to:'2017-03-23T14:14:29.970Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T14:08:29.970Z',mode:absolute,to:'2017-03-23T14:14:29.970Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
I am not sure I understand the rationale for this.  You would expect the deletion to have been triggered by the data manager themselves so it seems unnecessary to notify them doesn't it?

Is this something a data manager themselves asked for?

**Comment by MortenHofft** [comment]
@siro1 could you expand on this please?

**Comment by siro1** [comment]
Your'e right that the data manager on the publisher end triggered the deletion but what I fail to understand is whether there is a notification to the Data Manager at GBIF Helpdesk about this. Such notification can assist Helpdesk to also alert and liaise with relevant persons to help sort out issues.

**Comment by ahahn-gbif** [comment]
Having checked with Jan, this is not a requirement for helpdesk and or GBIFS data management. Deletions happen all the time, and do not get any specific follow-up. The general assumption is that someone deleting a dataset should know what they are doing. From volume alone, it is not possible to follow up on every deletion to confirm what the intention was. Deletions happen all the time. If it is critical, we will see it in the total numbers in portal.

**Comment by siro1** [comment]
OK, noted

**Comment by MortenHofft** [comment]
@siro1 I am closing the issue. If you believe there is still more to this issue, then please reopen and expand. thanks
