### ISSUE TITLE
Herpetology Collection failing ingestion

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1441]
**Herpetology Collection needs wiping and recrawling**

Something is badly wrong with this dataset, possibly between lookup keys or gbifids.

Matt will investigate.

-----

User provided contact info: @MattBlissett
System: Firefox 60.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5a7809b7970df4854df0f2f1cabd0d1d:8bd4229c9df7475b9fd5258ddb57de227a6696a307fbc2646331189939099b55743ce5735f91b1355ee1a6f1461ea9477d2e7255d319da0588ca7110363f1e74)
Referer: https://www.gbif.org/dataset/713088d4-f762-11e1-a439-00145eb45e9a
Window size: width 1440 - height 2424
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-10T14:43:15.886Z',mode:absolute,to:'2018-07-10T14:49:15.886Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-10T14:43:15.886Z',mode:absolute,to:'2018-07-10T14:49:15.886Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by tucotuco** [comment]
This resource is definitely defunct. A new resource has been made for this
collection on the VertNet IPT, but it remains private pending data updates
by AUM.

@David Bloom <dbloom@vertnet.org> Issue
http://ipt.vertnet.org:8080/ipt/resource.do?r=aum_herps

**Comment by MattBlissett** [comment]
Thanks John.

I will mention @dbloom so he can see this in Github.

**Comment by dbloom** [comment]
I have sent a message to AUM to restart the process to reset AUM Herp data. We will not do so using the DiGIR installation, especially since there are only 4 records on it.

If the DiGIR resource is causing issues, feel free to remove it from the GBIF process. It will help to encourage AUM to get their data published on the VertNet IPT.

**Comment by dbloom** [comment]
Thank you @tucotuco @mattblissett

I have sent another message to AUM to get this resource fixed and republished. I am sure they will respond after the holiday is over here.

**Comment by MattBlissett** [comment]
It looks like https://www.gbif.org/dataset/3cc72eb1-0f9e-496d-96e9-3cf6f7d94b0a is a dataset replacing the broken https://www.gbif.org/dataset/713088d4-f762-11e1-a439-00145eb45e9a — I will delete the latter, and add the "is replaced by" link.

Thanks all!
