### ISSUE TITLE
rgbif Verbatim Occurence Error

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1442]
**rgbif Verbatim Occurence Error**

When I run the following function

my.occ_get(key=1315970632, fields = "all", verbatim = TRUE, return = "data")

I get the error

Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0

This only occurs when using the verbatim = TRUE flag for this particular record. It looks like this is an issue with the verbatim parser (gbifparser_verbatim).

-----

User provided contact info: nathaniel.bloomfield@agriculture.gov.au
System: IE 11.0.0 / Windows 8.1.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/65c57c0fe15cf73c037b61df558f13e5:b096d930f36ad87e57db63feceebe7335a845bab980c5d2ca223c8ee3a6936c43c83e387adf29fa392b0427d57afe8d52084eec94a616a8e2ed13a69d1855037)
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1670 - height 831
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-11T01:08:19.097Z',mode:absolute,to:'2018-07-11T01:14:19.097Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-11T01:08:19.097Z',mode:absolute,to:'2018-07-11T01:14:19.097Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
@sckott  looks like this is a RGBIF question?

**Comment by sckott** [comment]
thanks @MortenHofft - yes is a rgbif problem. issue opened https://github.com/ropensci/rgbif/issues/318 will report back when fixed

**Comment by sckott** [comment]
@MortenHofft  its been fixed

**Comment by sckott** [comment]
and Ive contacted the person by email and they confirmed it works for them
