### ISSUE TITLE
Invasive lists should refer to countries and islands

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1443]
**Invasive lists should refer to countries and islands**

Delighted to see that the  'invasive in x countries' feature is now implemented using the GRIIS lists, but a couple of small tweaks required. First, these lists cover both countries and sub-national islands, so the heading should be changed to 'INVASIVE IN XX COUNTRIES AND ISLANDS'. 

Also there seems to be a bug which is preventing the country or island names from appearing correctly. For example, in the Lantana Camara list, Bangladesh appears as country.bd, and the sub-national islands appear with the codes rather than the names.

-----

User provided contact info: @timhirsch
System: Chrome 67.0.3396 / Mac OS X 10.13.5
User: [See in registry](https://www.gbif.org/api/feedback/user/b72a1b0f775c5902995e4203dd7fe575:fa44deaed6207a4aa8d0ede76b0994191b0b583978f3fc778fd006a747b41a2b4d4123f992bb708b1d2096a39f80bdf128527141bf87540010e738bef489e7a7)
Referer: https://www.gbif.org/species/2925303
Window size: width 1800 - height 868
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-13T01:17:28.804Z',mode:absolute,to:'2018-07-13T01:23:28.804Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-13T01:17:28.804Z',mode:absolute,to:'2018-07-13T01:23:28.804Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thanks. The code assumes that the checklists have a 2 letter isocode with the country abbreviation. Bangladesh fails because it is lowercase unlike the other checklists. Others because `BQ-SA` isn't two letters. I'll see if it makes sense to clean up the names or wether we should talk with the publishers about changing their naming

**Comment by MortenHofft** [comment]
Will know show as below instead. We do not have translations for all islands and sub territories. Only for countries. But the name appears in the checklist title. And we cannot search for nr of occurrences for an island code. So it will show as the country name and with no occurrences.

![screen shot 2018-07-13 at 06 34 31](https://user-images.githubusercontent.com/6759267/42672529-d6dca8ea-8666-11e8-8c11-6c9c5c423a47.png)
