### ISSUE TITLE
missing speciesKey for key == 2650133

### ISSUE THREAD

**Issue by hansvancalster** [gbif/portal-feedback#1444]
I noticed that "Ophioglossum vulgatum L.", for which the rank is SPECIES,  is missing a speciesKey:

[http://api.gbif.org/v1/species/2650133](http://api.gbif.org/v1/species/2650133)

**Comment by ManonGros** [comment]
I don't think I understand this issue, how can a species be missing a species key? Anyone can take a look and close the issue if needed?

**Comment by hansvancalster** [comment]
I will close this issue. I checked this and name_backbone() now does return the speciesKey and the speciesKey field is filled in in the link in my original post (it was not when I posted this a year ago). Thanks for taking a look.
