### ISSUE TITLE
'For registry admin eyes only'

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1446]
**&#39;For registry admin eyes only&#39;**

I am guessing the wording at the top of the event ID table is not supposed to appear on the public site.

-----

User provided contact info: @timhirsch
System: Chrome 67.0.3396 / Mac OS X 10.13.5
User: [See in registry](https://www.gbif.org/api/feedback/user/50bd97f214bc302d2c92c7036a0ee483:9a6002410da17320b6adbcbc96d97cf1de586aa0c1632fabbd1e19674fbed806e11bcb22311b6da94159847da3f4e1583d95597460d047ec01e73b99f1cc9587)
Referer: https://www.gbif.org/dataset/3b8c5ed8-b6c2-4264-ac52-a9d772d69e9f
Window size: width 1800 - height 923
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-13T15:21:46.463Z',mode:absolute,to:'2018-07-13T15:27:46.463Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-13T15:21:46.463Z',mode:absolute,to:'2018-07-13T15:27:46.463Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I've changed the text a bit.

**Comment by timhirsch** [comment]
Sorry I did not realise this was only visible to Secretariat. Got a bit overexcited ...

**Comment by MortenHofft** [comment]
Before going live I think [these caveats](https://github.com/gbif/portal16/issues/896) are worth considering. @ahahn-gbif is deliberating
