### ISSUE TITLE
Mink a long way from (adopted) home...

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1447]
**Mink a long way from (adopted) home...**

Text description of location is a lake in Northern Norway, coordinates place it in Central African Republic! Latitude might be wrong by a decimal place (62.5 instead of 6.25) but longitude makes no sense. Missing country in original data doesn't help...

-----

System: Safari 11.1.1 / Mac OS X 10.13.5
User: [See in registry](https://www.gbif.org/api/feedback/user/c801d06742ef0b557f0c8be7ad80a8be:5ee494861745c56ffef6f98b63ea141511399828f5a3258676ed8220cfceb1d55cfbc0b8e5c54782f64b53319aac03a652d289658ef2a8962deead372673f36d)
Referer: https://www.gbif.org/occurrence/1824731471
Window size: width 1694 - height 865
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-14T06:28:54.486Z',mode:absolute,to:'2018-07-14T06:34:54.486Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-14T06:28:54.486Z',mode:absolute,to:'2018-07-14T06:34:54.486Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publishers have been notified by email.

**Comment by ManonGros** [comment]
The publishers removed a few of their occurrences with unlikely coordinates.
