### ISSUE TITLE
What triggers metadata updates on gbif.org for datasets

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#1449]
From @dshorthouse

What triggers metadata updates on gbif.org for datasets? I updated the metadata for https://www.gbif.org/dataset/7086bdef-e377-4ac5-872f-751b1d614ed2 without any change in underlying data & republished the resource in an IPT. However, the changes I made appear not to bubble up. Must there also be change in data in the republication event for metadata changes to be recognized?

**Comment by MortenHofft** [comment]
Looks like crawling is still off https://www.gbif.org/health . But I see that the message on the website stating that crawling is off has been removed.

**Comment by MattBlissett** [comment]
It was off temporarily, but is back on now.

The IPT can request an update, but they are queued if the ingestion system is paused — which it was in this case, during some processing for quarterly analytics.

**Comment by dshorthouse** [comment]
Thanks, @MattBlissett but the citation on https://www.gbif.org/dataset/7086bdef-e377-4ac5-872f-751b1d614ed2 does not match what was re-published on http://ipt.nature.ca/resource?r=cmn_insect. How does the metadata on GBIF's end get updated?

**Comment by MortenHofft** [comment]
All dataset citations are generated based on title, authors and a few other params. The citation as provided (in e.g. the IPT) is no longer a part of the API. This choice was taken because the quality of many provided citations was so low and because we wanted a consistent format. @ahahn-gbif and @dschigel knows the exact rules and reasoning better.

**Comment by dshorthouse** [comment]
Thanks for this. May I ask you to produce a page on gbif.org or info bubble that precisely expresses how that citation is computed, inclusive of ordering of authors? It is difficult for a data manager like me to inform staff at our local institutions how we/they can affect change or have any control over the content & structuring of that citation.

**Comment by MortenHofft** [comment]
Seems reasonable. Pinging @dschigel and @dnoesgaard

**Comment by dschigel** [comment]
Sure; does this answer the question? https://www.gbif.org/faq?question=how-is-the-dataset-citation-text-auto-generated. See other explainers in the FAQ e.g. search for Citation here https://www.gbif.org/faq

**Comment by MortenHofft** [comment]
oh - see https://www.gbif.org/faq?q=citation

**Comment by dshorthouse** [comment]
Thanks @dschigel, @MortenHofft. Was there discussion on how to order the authors? I don't see that in the FAQs or on the README.

**Comment by dschigel** [comment]
The order of authors in the citation reflect the order of authored as entered into the IPT / as in source system. @dnoesgaard @ahahn-gbif I suggest a clarifying line is added to https://www.gbif.org/faq?question=how-is-the-dataset-citation-text-auto-generated after "Andersen"

**Comment by dshorthouse** [comment]
Thanks, @dschigel. In the case of the IPT however, there are specified roles for agents that *could* be understood to necessitate selecting and ordering of authors. In the IPT it appears to be solely Resource Creators whose names appear in its computed citation whereas other roles like Metadata Providers and Resource Contacts (and indeed anything in Associated Parties) appear not to be used in its computed citation. And, order of entry in Resource Creators indeed results in ordering of authors in its citation. However at GBIF's end, an alternative subset of those same agents/roles are thrown into a single bucket. At GBIF's end, it appears that both Resource Creators and Metadata Providers are used to compute authors in its citation but other roles are ignored. So, there is a marked disconnect between effort put into the IPT and what emerges at GBIF.
