### ISSUE TITLE
Life Stage field is empty

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#145]
**Life Stage field is empty**

Life Stage field within &quot;Occurrence&quot; block is empty. Old portal displays this field properly (e.g. “imago”, http://www.gbif.org/occurrence/1417496798/verbatim), new portal displays empty field (https://demo.gbif.org/occurrence/1417496798).

-----
fbitem-occurrence1417496798

System: Chrome 56.0.2924 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/1417496798
Window size: width 1298 - height 858
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T14:12:48.968Z',mode:absolute,to:'2017-03-23T14:18:48.968Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-23T14:12:48.968Z',mode:absolute,to:'2017-03-23T14:18:48.968Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: b267ac9b-6516-458e-bea7-7643842187f7
publishingOrgKey: c14b9ce2-9545-4376-8a3b-6741558c256a

**Comment by MortenHofft** [comment]
Both portals show it only as verbatim view. I suspect this is a case of the user not knowing the interface. But worth noticing as a potential usability issue.

**Comment by rkhalikov** [comment]
The same situation with **Scientific Name Authorship** field also.

**Comment by rkhalikov** [comment]
Empty fields look strange. Especially if they actually have data...

**Comment by mdoering** [comment]
Looks to me like we erroneously remove LifeStage from the interpreted Occurrence. We should only remove verbatim values in case we did interpret them. If they are uninterpreted they should remain the same in both views. 

Looking at the [code](https://github.com/gbif/occurrence/blob/master/occurrence-processor/src/main/java/org/gbif/occurrence/processor/interpreting/OccurrenceInterpreter.java#L190) it seems we interpret life stage, but do not flag any issue in case we fail to interpret it (like in this case). We should flag an issue and improve out life stage parser. Same for establishment means btw

**Comment by kbraak** [comment]
Thanks @mdoering - @cgendreau I suspect these would be of interest to you. I'll leave it to you to create some new occurrence or even gbif validator issues for these interpretation issues then.

**Comment by MortenHofft** [comment]
My misunderstanding of the issue them. I will reopen and label as an API task

**Comment by mdoering** [comment]
should we move issues like this to the occurrence repository? We move portal issues, so we should move others too into appropriate repositories or do we lose overview with over 100 gbif repos?

One can see all issues assigned to oneself and also all open ones for any gbif repository, so I think it is better to move issue: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Agbif+

Useful too to move issues: https://github-issue-mover.appspot.com/

**Comment by MortenHofft** [comment]
i would think it made sense to move to relevant repositories - that at least is what i do with presentation related issues.

**Comment by dschigel** [comment]
Looks like an important issue to fix regarding GLOBIS-B activities

**Comment by MattBlissett** [comment]
These are the things that are interpreted but don't have an issue. I've first reviewed what isn't interpreted to see what's affected.

These three can't be used in searches:
* `sex` — there is so much variety in this field (20,000 verbatim values!), I'm not adding an issue. The original value is in verbatim if required.
* `establishmentMeans` — I think I will leave this, as Quentin Groom is working on vocabularies etc. There are 1881 distinct unparsed values, including "Natural" on 64 million occurrences, and "wild" on about 9 million.
* `lifeStage` — we have 34,102 distinct verbatim values, and we didn't have a dictionary mapping. I have added some that I'm certain about (`Adulto` → `ADULT`), but the [rest are unassigned](https://github.com/gbif/parsers/blob/master/src/main/resources/dictionaries/parse/life_stage.tsv). Would anyone like to complete it? That should come before we add issues.

This one can be used in searches:
* `typeStatus` — potentially could have an issue, but I'll leave for further discussion. There are a lot of variations on "not a type", and "voucher of", but the rest is pretty good.  Should we add HYPOTYPE, PLESIOTYPE (both seem reasonable) and HOMEOTYPE (seems less reasonable) to the API, @mdoering? (Or Dmitry, and whoever actually knows about this.)

**Comment by dschigel** [comment]
on typeStatus - I am fogetting these things, the quick way to decide is to make  list of what we have, and list of possible additions, and show to Donald and Thomas Pape (works in the museum, head of ICZN). I can also look it up, but by going the way I suggest you will have a choice confimred by the expert.

**Comment by mdoering** [comment]
I'd be curious how much serious variety there can be in sex. If I remember correctly a lot has been "misusing" the field to do counts by sex, especially in the case of mixed observations. If the interpreted value would be a set of sexes can it be that challenging? And would it not be good to flag the cases when things are unexpected?
