### ISSUE TITLE
Geographic coverage for recorded species charts

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1455]
**Geographic coverage for recorded species charts**

The y-axis for these charts should not read "Cell count".  Rather I believe it should be "Number of species (thousands)".

The explanation should be expanded to something like: "These charts illustrate change in the number of species for which occurrence records are available and the geographic coverage of records for each species at different scales. In each chart, species are classified by the number of cells at a given scale for which occurrence records for the species are available. More cells indicates greater data coverage for the species.  Obviously, some species are only known from a small area, so low cell counts do not necessarily indicate lack of relevant data."

-----

User provided contact info: dhobern@gbif.org
System: Chrome 67.0.3396 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7be7661d263a4579d81646b242318fa1:b5d3a02db71de78fbd2a0bccdad4113344b9027f8903c8479259c2ef2f37435180b473ce414f3a239378d80c8751e33a1905f9906ca48bb2f7e4f6cf239b0091)
Referer: https://www.gbif.org/analytics/global
Window size: width 1396 - height 665
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-20T09:52:41.177Z',mode:absolute,to:'2018-07-20T09:58:41.177Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-20T09:52:41.177Z',mode:absolute,to:'2018-07-20T09:58:41.177Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
I've updated this in both places. The website will be updated fairly soon, but unless you feel this is particularly important, the graphs will not change until the October analytics run.
