### ISSUE TITLE
API usage example: dataset upload

### ISSUE THREAD

**Issue by NeonPaul** [gbif/portal-feedback#1456]
Are there any examples of how to upload a dataset for the v1 API? Specifically what the json payload should look like? I'm trying to maintain older code that is supposed to create a new dataset but I get a 403 response with no body - not very informative. I can't find information on what are required fields and what the data requirements are.
The auth is correct (I can log in ok) and the organisation is registered as a publisher.

Keys included in the JSON:
```
type: "CHECKLIST"
homepage
tile
installationKey
publishingOrganizationKey
citation: {
 text
}
```

Any help would be greatly appreciated!

**Comment by MattBlissett** [comment]
There's an example (it runs!) in this directory: https://github.com/gbif/registry/tree/master/registry-examples/src/test/scripts .  You need the language (for no good reason) but don't need the citation.

`403` does suggest an authentication problem, you may need to be granted permission for the publishingOrganization you are creating a dataset for. If you still get a 403, let me know the username you're using and the full payload; you can email mblissett at the obvious domain.

Also, for testing you can use api.gbif-uat.org.
