### ISSUE TITLE
Text change  (headers) in invasive table

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1460]
**Text change (headers) in invasive table**

Request from the Invasive Alien Species informal working meeting: change the table and column headers from "Invasive in (..)" to "Recorded as invasive in (...)" (2 places in the table underneath the map on a species page for known invasives)

-----

User provided contact info: @ahahn-gbif
System: Firefox 61.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5959826475646264a04764f9e0098ce5:0fc81a428ac11e2c44a802055412e16a3c762026bbe3507538f83f0557d38951fd7a9a982c80cbf1345accfd594dce87a988f8948188a38a473acdad2cfc79ca)
Referer: https://www.gbif.org/species/2891770
Window size: width 1280 - height 541
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-27T07:08:29.632Z',mode:absolute,to:'2018-07-27T07:14:29.632Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-27T07:08:29.632Z',mode:absolute,to:'2018-07-27T07:14:29.632Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I have changed it.
Be aware that this means translations of this is discarded. I'm not sure what a good process for this is. As a translator I imagine it is frustrating seeing translations being discarded due to what might be considered small textual changes?

**Comment by ahahn-gbif** [comment]
Thanks for raising this. A seemingly small change, but one that was considered essential. Who needs to be consulted re translations in general? What is best practice around the workflow for text updates like this - should translation needs be logged _before_ text changes in the English version? @dnoesgaard @kcopas

**Comment by MortenHofft** [comment]
But even if it is essential, it might appear to the translators to be a little detail that means that their work is trashed. I'm just wondering what to do in scenarios like this to spare frustration and not loose good work too often.

* If it is a small detail (typo): then perhaps manually copying the existing (say japanese) version to the new - now empty - field? Previous translations are available in the repo history and if it is a small change, then Crowdin is also likely to suggest the old translation.
* If it is an essential difference as in this case: then I guess there is nothing to do but have it retranslated? Either by volunteers or paid help.

And to minimize cases like this, then make sure that comms always proofread and approve english translations first? We largely do so already and it would not have made a difference in this case, but it will reduce the risk of me writing `country` where it should have been `country or area` and similar cases.
