### ISSUE TITLE
Xylophagidae Inaccurate taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1461]
**Inaccurate taxonomy**

The taxonomy for this species is:
- Phylum: Arthropoda
- Class: Insecta
- Order: Diptera
- Family: Xylophagidae

-----

User provided contact info: @CaroleSinou
System: Chrome 67.0.3396 / Mac OS X 10.12.6
User: [See in registry](https://www.gbif.org/api/feedback/user/734202b84b9725e78ecfe97cc9229341:93b23df959201b0b48b1f77bb86e0601ab73d10e57404e8f287da4eaa433f6397a737ae77e391b449a3d6f78e42fcc4cb95161613d4d6a3051c735e9ba842e3a)
Referer: https://www.gbif.org/species/5086414
Window size: width 1440 - height 776
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-30T18:28:44.801Z',mode:absolute,to:'2018-07-30T18:34:44.801Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-30T18:28:44.801Z',mode:absolute,to:'2018-07-30T18:34:44.801Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@mdoering, it looks like an issue with the catalog of life

**Comment by mdoering** [comment]
'Xylophagidae' is a homonym family used both for Diptera and Molluscs. 

 - Diptera: 'Xylophagidae Fallén, 1810'
 - Mollusca: 'Xylophagidae Purchon, 1941'

The Diptera one is correct and in frequent use, e.g. by [Systema Dipterorum](http://sd.zoobank.org/Nomenclator/Details/266454)

The Mollusc family is a later homonym and has an [ICZN Opinion 2429](https://www.iczn.org/cases/all-cases/case/3717#opinion-123) proposing  the emendation 'Xylophagaidae Purchon, 1941' instead which is already used by [WoRMS](http://www.marinespecies.org/aphia.php?p=taxdetails&id=489105)

**Comment by yroskov** [comment]
WoRMS has corrected name in April, after closure of AC19. Name in CoL should be updated automaticly after resuming monthly editions with automated updates in WoRMS checklists.

**Comment by mdoering** [comment]
Xylophagidae homonym families added to backbone patch: https://github.com/gbif/backbone-patch/commit/cba2416fbd7bdbb2c74d259d5af22a491c63d119

And update CLB to allow [intra kingdom family homonyms](https://github.com/gbif/checklistbank/commit/94feae9dd829d7749c3c6cda6c279345abdd14d0)
