### ISSUE TITLE
Hi, this is to inform you that the recent news published in your website (https://www.gbif.org/data-use/2CGn24Qg4UwGAwQcGgceqw/refining-predictions-of-invasive-species-using-remote-sensing-data) has a cover picture of Lantana camara (sensu lato); but the caption describe it to be Water Hyacinth. I thought, you may like to rectify. Cheers !

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1462]
**Hi, this is to inform you that the recent news published in your website (`https://www.gbif.org/data-use/2CGn24Qg4UwGAwQcGgceqw/refining-predictions-of-invasive-species-using-remote-sensing-data)` has a cover picture of Lantana camara (sensu lato); but the caption describe it to be Water Hyacinth. I thought, you may like to rectify. Cheers !**

-----

User provided contact info: shastri.ninad@gmail.com
System: Chrome Mobile 67.0.3396 / Android 6.0.1
User: [See in registry](https://www.gbif.org/api/feedback/user/62fcf98f7eaf6206ab4d4c9d71142b5b:8440f6db725bce88dc32292960352dc45d39fe934ba0be1313da6397e4d7622313354ceea59f86a165a0d678b0ae166fca15de0a31204fc1743c8e53760049a5)
Referer: https://www.gbif.org/user/profile
Window size: width 360 - height 311
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-31T04:31:51.534Z',mode:absolute,to:'2018-07-31T04:37:51.534Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-31T04:31:51.534Z',mode:absolute,to:'2018-07-31T04:37:51.534Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Thanks, fixed!

(sending email to user)
