### ISSUE TITLE
Broken meta.xml in DarwinC archive

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1464]
**Broken meta.xml in DarwinC archive**

Hello

meta.xml in DarwinCore archive is broken giving:

rowType="FreeMarker template error (DEBUG mode; use RETHROW in production!):
The following has evaluated to null or missing:
==> core.rowType.qualifiedName  [in template "meta.ftl" at line 4, column 315]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${core.rowType.qualifiedName()} auto-...  [in template "meta.ftl" at line 4, column 313]
----

etc.

Regards
Marko

-----

User provided contact info: marko.peterson@ut.ee
System: Chrome 67.0.3396 / Mac OS X 10.13.4
User: [See in registry](https://www.gbif.org/api/feedback/user/ba1c8e12ba22116c1b023d8ddd799065:be9e0006e38a6e4fe80ab4d50c8e4de9f36cc712107d160e469faa0650549e12a65e37cea24e85a9780f27be964adfe73b273d8ddbefb83716d9b5563ee1fe9f)
Referer: https://www.gbif.org/
Window size: width 1280 - height 703
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-31T07:58:35.182Z',mode:absolute,to:'2018-07-31T08:04:35.182Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-31T07:58:35.182Z',mode:absolute,to:'2018-07-31T08:04:35.182Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by timo-piirmann** [comment]
A few examples of datasets which have this broken meta.xml file:

https://www.gbif.org/dataset/cb6e66f1-3056-404d-a341-bb856762c57c
https://www.gbif.org/dataset/95da13d0-f762-11e1-a439-00145eb45e9a
https://www.gbif.org/dataset/81321482-f762-11e1-a439-00145eb45e9a
https://www.gbif.org/dataset/85275ce6-f762-11e1-a439-00145eb45e9a

It seems to be a general issue, not related to a single dataset/publisher

**Comment by MattBlissett** [comment]
Thanks, I'm looking into this.

An example download: https://www.gbif.org/occurrence/download/0000949-180730143533302

**Comment by MattBlissett** [comment]
The commit marks this as closed, but I still need to test it on the test system, then deploy it to the production system.

**Comment by MattBlissett** [comment]
The fix is now deployed to production. Thanks for reporting!
