### ISSUE TITLE
That location seems suspect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1465]
**That location seems suspect**

-----

System: Firefox 61.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4c6250cf18593d14d4333d0ab6755d60:4bda94cd5b9641f2c36ddc420f098852c5f6526f289754c2a347a222fd5d59602de9349359881a63eb7612c0f92c8c487349d92f75e2f02011decd11e37b2fd9)
Referer: https://www.gbif.org/occurrence/38217432
Window size: width 981 - height 681
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-31T11:25:17.063Z',mode:absolute,to:'2018-07-31T11:31:17.063Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-31T11:25:17.063Z',mode:absolute,to:'2018-07-31T11:31:17.063Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Publisher contacted by email.
