### ISSUE TITLE
rescued dataset deleted?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1466]
**rescued dataset deleted?**

Just wondering about this dataset that appears to have been deleted but also rescued?

-----

User provided contact info: @dnoesgaard
System: Chrome 67.0.3396 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/bdf8cadbe0978c9de5da4d638824f510:bdc9c9a440b4c0850bc32f3ef22733d3f253da1157d04fd23297b37dfe86fad304ffa6f09cabf2354e0c61d557a18451070a611df7d7d1e01f41d844bde38780)
Referer: https://www.gbif.org/dataset/83b58bb2-f762-11e1-a439-00145eb45e9a
Window size: width 1778 - height 1192
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-31T12:30:30.389Z',mode:absolute,to:'2018-07-31T12:36:30.389Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-07-31T12:30:30.389Z',mode:absolute,to:'2018-07-31T12:36:30.389Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Jan wrote "Dataset deleted at publishers request" when he deleted it.

**Comment by dnoesgaard** [comment]
Asking because someone just cited it...

**Comment by timhirsch** [comment]
In principle NIWA (OBIS Pacific) data should all be coming through their IPT, so hopefully that dataset will be included somewhere among these https://www.gbif.org/dataset/search?hosting_org=c58ac019-b413-4613-8772-39e57acbeb8e
