### ISSUE TITLE
That location seems suspect (in the sea).

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1468]
**That location seems suspect (in the sea).**

-----

System: Firefox 61.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/1b71b47ed3e18f33cd1ddb78c4b121ae:f8ba99b22571676619283c28ba8b5fccfda912fadca66e858068f2959ece82b010023274445050c551bd0c90f836bb735eee6169afd73ddd2bb990f98147bceb)
Referer: https://www.gbif.org/occurrence/1228626570
Window size: width 981 - height 710
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-01T09:47:11.799Z',mode:absolute,to:'2018-08-01T09:53:11.799Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-01T09:47:11.799Z',mode:absolute,to:'2018-08-01T09:53:11.799Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Publisher contacted by email.

**Comment by ManonGros** [comment]
The coordinates pointed towards the centroid for the Hawaiian archipelago.
This location has been moved after we forwarded the feedback to appear on land. The publishers are now considering removing centroid altogether but the dataset hasn't been updated yet.

See related issues here:
https://github.com/gbif/portal-feedback/issues/1467
https://github.com/gbif/portal-feedback/issues/1468
https://github.com/gbif/portal-feedback/issues/1469
https://github.com/gbif/portal-feedback/issues/1470
https://github.com/gbif/portal-feedback/issues/1471
https://github.com/gbif/portal-feedback/issues/1472
https://github.com/gbif/portal-feedback/issues/1473
https://github.com/gbif/portal-feedback/issues/1479
