### ISSUE TITLE
The page of data validator not working. It cant read the csv archive .

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1475]
**The page of data validator not working. It cant read the csv archive .**

-----

System: Firefox 52.0.0 / Windows XP.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/6a22028120355a4276a82f94df78331d:c62f43b4286ebfae81690f7fcdf81a20fddfd5df5b10268b8fb333ffdfe4b0aba94a9a3f1e2f3f2e5661ef5dd1e0f5202328e36346fae3a60fa9fa85860e4ca7391527c7555e99cb1ba82686a3ddc898)
Referer: https://www.gbif.org/tools/data-validator
Window size: width 1280 - height 635
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-02T14:53:55.501Z',mode:absolute,to:'2018-08-02T14:59:55.501Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-02T14:53:55.501Z',mode:absolute,to:'2018-08-02T14:59:55.501Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Closing lacking further information.
