### ISSUE TITLE
Issues filter disappeared?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1476]
**Issues filter disappeared?**

Why is it that the "issues" are no longer part of the facet filter for occurrence searches? It used to be a lightweight way to get an idea of the meaning and impact of "Known issue" flags on the download entry page, allowing a quick checking of the records concerned. The yellow flags themselves are not interactive, and in larger datasets, it is difficult to find the impacted records without a filter, e.g. during quality checks to report back to data owners.

-----

User provided contact info: @ahahn-gbif
System: Firefox 61.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e572fc37449f2fefd53e578ae90ac6c5:f294b7e1307c52d96bfea5062d44ffd5b54c0f77e671f8ee0a753e043ef07eadf77f87c05cce79bd0c882784019cfba86ed1824a6ef3fe642ef90a5b38951446)
Referer: https://www.gbif.org/occurrence/download?country=JM&taxon_key=4080795&advanced=1
Window size: width 1897 - height 748
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-03T09:58:01.927Z',mode:absolute,to:'2018-08-03T10:04:01.927Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-03T09:58:01.927Z',mode:absolute,to:'2018-08-03T10:04:01.927Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
@ahahn-gbif, are you looking for the section with the heading "Remarks"?

**Comment by ahahn-gbif** [comment]
Ah! Yes, thanks! I assume there is a reason why it got renamed? As a user, I would understand "remarks" to be something that the data publisher added to the record, not a processing result, but maybe that is just me. Also, the three-dot selector for fields to include in the result list still has the same item to be selected under "issues", which is a bit confusing.

**Comment by MortenHofft** [comment]
That is completely up to comms to decide. They have reviewed it, but are also welcome to change at will. Either by changing the actual translation file or by asking me/Thomas to do so. As with the invasive species rewording, this has consequences for translations to other languages. 

`Coordinate reprojected` and `Coordinate rounded` isn't really issues per se. It is remarks/notes/flags about the interpretation. That we decide to round the coordinates isn't an issue with the published record. But `issues` might still be a better name than `remarks`.

Let us know if you wan't it changed.
https://github.com/gbif/portal16/blob/master/locales/translations/en/components/filterNames.json#L21

**Comment by timhirsch** [comment]
Discussion involving comms and Donald just now concluded that 'Issues and flags' would be clearest name for this filter.
