### ISSUE TITLE
Eswatini vs Swaziland

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1477]
**Eswatini vs Swaziland**

For country code SZ, we use Swaziland on the country page but Eswatini on the activity report. I guess the relevant list should be updated?

`https://github.com/gbif/portal16/blob/f4584aaed7818cff8868061f651148073243d92e/locales/translations/en/enums/country.json#L218`

-----

User provided contact info: @dnoesgaard
System: Chrome 67.0.3396 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/43850153ce87128a29791f49695df0ee:355af322e63e292cf012e0081127fad6a3cfcfac8e421969f4ad70e80b64b7a756dfb6c7489ae2399168755fe4f0b7dfdbea627b07a1bdc07eda8d4627a57fc6)
Referer: https://www.gbif.org/country/SZ/summary
Window size: width 1356 - height 1028
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-03T13:11:44.379Z',mode:absolute,to:'2018-08-03T13:17:44.379Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-03T13:11:44.379Z',mode:absolute,to:'2018-08-03T13:17:44.379Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
the reports are generated from https://github.com/gbif/country-reports/blob/master/locales/en.json#L301
where it is updated. but the reports might have been generated before that name update. Reports are a snapshot - so I believe rerunning/recreating them will generate new data as well. @thomasstjerne you know this better than I.

**Comment by MattBlissett** [comment]
This is old, the report already has Eswatini.

**Comment by MattBlissett** [comment]
(Just waiting for a portal deploy to change Swaziland→Eswatini on the country page etc.)
