### ISSUE TITLE
"Type specimen" information attached to wrong name

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/portal-feedback#1478]
In some cases, there are type specimen, but they are not the type from the last identification. Example GOET000936 - https://www.gbif.org/occurrence/1638363416:  The specimen is the holotype of Cubincola trimera Urb. Later, someone changed the specimen identification to Cneorum tricoccon L., so this is the last identification. But the specimen is not the holotype of Cneorum tricoccon L..

(communicated by email by the SNSB.de data publishers, https://www.gbif.org/publisher/0674aea0-a7e1-11d8-9534-b8a03c50a862)

**Comment by ahahn-gbif** [comment]
Where type specimens are listed as such, they should stay combined with the typified name, not the most recent identification or the latest accepted name.

This is a data processing issue: We receive a record for a specimen that is marked as a type specimen for a specific name, but re-assign the specimen the most recently accepted name for that taxon. The type specimen status, however, is tied to the original name ("specimen [specimenID] is holotype of [name]"), not to the taxon, and should therefore always stay together with the typified name. In this specific example cited above, the data come in ABCD format, which allows to list alternative names for the specimen - often used e.g. in the identification history of a herbarium sheet. Such name changes may be re-identifications of formerly mis-assigned names (though not that commonly expected in the case of a type), or they may reflect taxonomic or nomenclatural changes (e.g. regroupings of taxa reflected in a name change). The type information, however, remains tied to the name it was originally assigned to - the most recent identification or nomenclatural change does _not_ carry over to the type status of the specimen. The same is true where we (e.g. through DwC-A) receive information about a type specimen with the name attached, and the name is no longer the accepted name of the taxon: regardless, the typified name should stick together with the information that this is "the type of [name]".

**Comment by ahahn-gbif** [comment]
Also see https://doi.org/10.3897/zookeys.751.24791 on the same issue

**Comment by NHMD** [comment]
A possible solution is to infer an [identification](http://rs.gbif.org/extension/dwc/identification.xml) from the Specimen Unit, which carries the typified name.

![holotype-id](https://user-images.githubusercontent.com/9532080/44341393-10d98b00-a488-11e8-80d2-6165c59a6d3b.png)

**Comment by thomasstjerne** [comment]
A possible solution is to infer an  [identification](http://rs.gbif.org/extension/dwc/identification.xml) from the specimen unit.

![holotype-id](https://user-images.githubusercontent.com/1666484/44341534-7e85b700-a488-11e8-9f3e-fa3dc717b695.png)

**Comment by ahahn-gbif** [comment]
Is there a similar solution for solving this in DwC-A records, where a specimen comes in marked as a type and with a scientific name, but the name gets overruled by a later accepted name during backbone matching?

**Comment by thomasstjerne** [comment]
Now displaying the typified name with the type status: https://www.gbif.org/occurrence/1638363416
