### ISSUE TITLE
Understanding some backbone comments

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1481]
**Understanding some backbone comments**

Eupagia is listed as an accepted name for a genus in the Geometridae - but no author or citation.  Eupagia Walker, 1860 is apparently a synonym of Drepanogynus Genee, 1857, also in the Geometridae.  
Why is Eupagia accepted if its place of publication is not known? Is the problem that there are no combinations in Drepanogyna for the species listed? Or what? This is a specific example of an issue that has been bothering me.

-----

User provided contact info: mary.barkworth@usu.edu
System: Chrome 68.0.3440 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/97ed3dd746229f1e235bde5cf9580c0a:e1159cc1daccb2d803e8f3e96843f72a2da5a4b460750bf6bf134a7cb8657332044f60eaf12c8424a298bf8e91f61a11764f8b79c9bfba4ea621f072199b22fd)
Referer: https://www.gbif.org/species/search?q=Eupagia&qField=SCIENTIFIC
Window size: width 1150 - height 859
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-07T17:53:01.701Z',mode:absolute,to:'2018-08-07T17:59:01.701Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-07T17:53:01.701Z',mode:absolute,to:'2018-08-07T17:59:01.701Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Replied by email.
