### ISSUE TITLE
Identifying problems in a data set

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1483]
**Identifying problems in a data set**

I have found the metrics page for ISL where it shows the 198 records with problems but how does one get to view the records involved. I am sure it is obvious but this is the second time I have just scratched around and I would really just like to know what to do.  
I am assuming that, since I have given my email, the response will come to me that way as well as to GitHub. Is that correct?

-----

User provided contact info: mary.barkworth@usu.edu
System: Chrome 68.0.3440 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/096778a31f00da240fbbbbe822a79388:9700731744b463828c00ea2b8762739d547dbea559fc00cb9fc9a7365675fd26a6630942703eadfbfba99d801f74c38700f4a9ad1baa69295d815581bb2f7458)
Referer: https://www.gbif.org/occurrence/charts?dataset_key=6f40c8ec-2b95-47d5-9064-eda6a8ddf3fb&issue=RECORDED_DATE_INVALID
Window size: width 1920 - height 902
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-08T17:45:55.991Z',mode:absolute,to:'2018-08-08T17:51:55.991Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-08T17:45:55.991Z',mode:absolute,to:'2018-08-08T17:51:55.991Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by thomasstjerne** [comment]
User answered by email
