### ISSUE TITLE
Review model for multilingual documents

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1485]
This might be easy and straightforward, but as we hurtle toward multilingual support on GBIF.org, I'd really like review our Contentful content model for documents with @MortenHofft and @dnoesgaard.

Best example I can provide is [Chapman, _Principles of Data Quality_](https://www.gbif.org/document/80509).

We currently have different items for four translated versions:
+ [Chinese (Traditional)](https://www.gbif.org/document/80517)
+ [French](https://www.gbif.org/document/80626)
+ [Korean](https://www.gbif.org/document/80507)
+ [Portuguese](https://www.gbif.org/document/80924)

In addition, we have a recent Spanish version translated through a CESP project that ought to be added. As I went to do just that, I realized we've got a little confirmation and curation to do as part of the internationalization work, because while this may be the most prominent example, it's not the only one.

**Comment by MortenHofft** [comment]
My intuition would be to use one article:
https://app.contentful.com/spaces/uo17ejk9rkwj/entries/80509

For the pdf, it depends whther we would like to have all versions explicitly listed or just one that reflect the translation you are currently reading.

If the later, then only use one media item and translate that. https://app.contentful.com/spaces/uo17ejk9rkwj/assets/2gupj7dJIw62UeOUYiqSsm
That way, when linking to that media item from somewhere else it will automatically be translated as well.
