### ISSUE TITLE
Related species not found

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal-feedback#1486]
The TAXREF checklist is among the results in this query:
http://api.gbif.org/v1/dataset/search?taxonKey=110&type=CHECKLIST&limit=10&offset=0

However, there seems to be no related species in the checklist:
http://api.gbif.org/v1/species/110/related?datasetKey=0e61f8fe-7d25-4f81-ada7-d970bbb2c6d6

Is it unsafe to assume that all checklists returned by the first call should have at least one species in the second call?

**Comment by ManonGros** [comment]
As far as I can see, https://www.gbif.org/species/134602661 from TAXREF references https://www.gbif.org/species/110 so I will close the issue.
Unless I missed something?
