### ISSUE TITLE
Translated MoU versions should be available from main MoU page.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1487]
**Translated MoU versions should be available from main MoU page.**

We should have a link here to the non-English versions of the MoU, making clear that this is the official version for signature, and the others are unofficial translations for reference. 

French at `https://www.gbif.org/document/80764/protocole-daccord-concernant-le-systeme-mondial-dinformation-sur-la-biodiversite-mou-french` 

Spanish at `https://www.gbif.org/document/80750/memorando-de-entendimiento-para-el-sistema-de-informacion-sobre-la-biodiversidad-global-mou-spanish` (resource seems to be missing)

Portuguese here `https://www.gbif.org/document/80767/memorando-de-entendimento-para-o-sistema-de-informacao-sobre-a-biodiversidade-global-mou-portuguese` 

There may be more ... ?

-----

User provided contact info: @timhirsch
System: Chrome 67.0.3396 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/4f3c4f23755fae8984e720a5f40baae2:17a6ca92f0719e38e1b2753a7184962692666be28764b0c933fde020cdb805f1bcc7b0aad3757a0fc0bbcda805cc8dd56262612be9ef9f32d6463dd8c0a6558d)
Referer: https://www.gbif.org/mou
Window size: width 1152 - height 578
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-09T10:05:46.718Z',mode:absolute,to:'2018-08-09T10:11:46.718Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-09T10:05:46.718Z',mode:absolute,to:'2018-08-09T10:11:46.718Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by kcopas** [comment]
Timely note—another important example to consider for #1485 

Hope to resolve our model and approach on this (in light of a soon-to-be multilingual site) as early as next week.

**Comment by kcopas** [comment]
https://www.gbif.org/mou now links to the versions listed here:
https://www.gbif.org/document/80661/gbif-memorandum-of-understanding

Acceptable?
