### ISSUE TITLE
Misleading "Identified date unlikely" flag (Remarks)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1488]
**Misleading &quot;Identified date unlikely&quot; flag (Remarks)**

It's not unusual for determination dates on specimens to be brief, perhaps just a year, when taxonomists rework a collection. This is especially true on insect pins.

Hence all these records with identifications with dates as 2007 or 2008, which we interpret as Jan 1 and then complain about as unlikely.

Couldn't we instead have a flag that means something like "Identification date supplied as year only"?

I assume you have the URL, but here it is:

`https://www.gbif.org/occurrence/search?has_geospatial_issue=false&issue=IDENTIFIED_DATE_UNLIKELY&taxon_key=8863&geometry=POLYGON((-94.51139%2028.80792,-88.74256%2028.80792,-88.74256%2033.09573,-94.51139%2033.09573,-94.51139%2028.80792))`

-----

User provided contact info: @dhobern
System: Chrome 67.0.3396 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/cca1895b487b62c63fd9c65e7f481cd1:1ba20e54437302aa6b13a9e74f9efb57cec98c0a04fa55f11bba908adb580f20056fc99bcf3044ff300c2318f52c5a7f91fbba3b34351efc0bc9da588a4293b7)
Referer: https://www.gbif.org/occurrence/search?has_geospatial_issue=false&issue=IDENTIFIED_DATE_UNLIKELY&taxon_key=8863&geometry=POLYGON((-94.51139%2028.80792,-88.74256%2028.80792,-88.74256%2033.09573,-94.51139%2033.09573,-94.51139%2028.80792))
Window size: width 1396 - height 665
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-10T05:57:20.086Z',mode:absolute,to:'2018-08-10T06:03:20.086Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-10T05:57:20.086Z',mode:absolute,to:'2018-08-10T06:03:20.086Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
@dhobern, I can easily remove the IDENTIFIED_DATE_UNLIKELY flag (this is a mistake), but then the date would say 1997-01-01 with no issue.

I could add a "year only" remark, but I think we should wait and handle these properly with the new data pipeline. https://github.com/gbif/gbif-api/issues/4 is for the same problem with eventDates.

**Comment by dhobern** [comment]
Thanks, Matt.

The thing to note is that an year-old identification date is still useful
for almost all purposes that a full date is - knowing how recent an
identification is.  An event date that is year only cannot be used validly
for anything relating to seasonality, etc.  It would be good for us to be
more explicit in both cases on what has happened.

In both cases "date unlikely" is a terrible description of the issues.
Agree we should handle as part of the pipeline work, but the ideal would be
for us somehow to retain the temporal imprecision in our interpreted form.
This probably needs general consideration to make it work at all stages in
our processing.

Donald

**Comment by MattBlissett** [comment]
On UAT, "Identified date unlikely" issues are no longer being added for partial dates: https://www.gbif.org/occurrence/1585284262 → https://www.gbif-uat.org/occurrence/1585284262

Unlike the recorded/event date, a fairly large interval for an identification date doesn't seem like it would affect anyone's use of the data, so I haven't added a flag.

**Comment by MattBlissett** [comment]
Note we have fixed eventDate interpretation, but not identified dates.

**Comment by MattBlissett** [comment]
Closing in favour of #4815, as the remark issue was solved.
