### ISSUE TITLE
Enhance the explaination

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#149]
**Enhance the explaination**

From private email from KH of ufz.de:

1) The trend method used in the EUBON portal has some potential interest, and seems well implemented, but will give you completely spurious data with the kind of information one normally mobilises via GBIF. And several partners of WP 4 think that giving (or more worryingly promoting) the wrong idea from the EUBON portal is a dangerous thing. While you explain in the “read more” part that it may or may not give reliable results, we feel that it would be very important that this information is presented also on the produced maps as many users will not read the background info in detail and because the majority of data in GBIF is not really suitable for such analyses (i.e., the assumptions behind the method will often be violated) because effort often will not be constant among taxa within a group, especially if one considers larger regions). We also feel that this and other assumptions should be explicitly mentioned in the background info.

-----
fbitem-f0b1d8e8c6811b830ef2f932fb5cf1be7ba9cf0a
Reported by: @timrobertson100
System: Chrome 57.0.2987 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/tools/species-population
Window size: width 1457 - height 560
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-24T12:22:54.637Z',mode:absolute,to:'2017-03-24T12:28:54.637Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-24T12:22:54.637Z',mode:absolute,to:'2017-03-24T12:28:54.637Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
A naming suggestion from KH of ufz.de : "Reporting frequency tool"

**Comment by MortenHofft** [comment]
The description have been changed and the tool renamed after instructions from Donald Hobern, Dmitry S. Schigel.
Mail recieved Friday 7 April 2017 at 16:23

Some of the issues were addressed, while others were not. @timrobertson100 Let me know if we should address this further. If so please reopen.

**Comment by MattBlissett** [comment]
The about page for the tool is now returning 404.

**Comment by MortenHofft** [comment]
The page needs to be ported into contentful and given the url-alias (or we can change the location in the link)

**Comment by kcopas** [comment]
Published as https://www.gbif.org/tools/observation-trends

**Comment by thomasstjerne** [comment]
If you publish it as a "tool" content type and use "https://www.gbif.org/tools/observation-trends" as primary link, it will get a small "tool" badge on the search result item and clicking it will take you directly to the tool, rather than the about page.

This will make it consistent with our other tools such as: https://www.gbif.org/search?q=name%20parser

**Comment by kcopas** [comment]
Sorry, just to be clear: you've reopened this because the content needs to be republished as a different content type? If so, it's helpful to go ahead and assign it to @dnoesgaard and @kcopas as  a matter of habit.

I closed the issue yesterday thinking it was just a lingering one that hadn't caught up to the many other changes left undocumented since May 2017 :-|

**Comment by thomasstjerne** [comment]
> you've reopened this because the content needs to be republished as a different content type?
Yes, in order to align it with our other tools. I think we introduced this when we launched the  data validator, so theres no way you could have known about it before that.

**Comment by dnoesgaard** [comment]
There is nothing outstanding here, is there?

**Comment by dnoesgaard** [comment]
Ah right, I get it now. I've copied over the about page to this tool item now: 1IVlBHIXeUK68ac6okOqkm

I guess this item should be used for the *About* section now?
