### ISSUE TITLE
API usage example: how to get all vernacular names for species?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1490]
**API usage example: how to get all vernacular names for species?**

I want all vernacular names for a species e.g. "Rhagium inquisitor". What is the best way to reach this? 

Now I've a chain of requests:

1. `https://api.gbif.org/v1/species/match?verbose=true&name=Rhagium%20inquisitor`

Result is a list of keys ("usageKey"):

8544630, 8305554, 8124606, 4292618, 7623196,, 8544630, 8170062 ... (11 more)

2. for each key of the list i make a request: `http://api.gbif.org/v1/species/{key}/vernacularNames`

Is there a more efficient way to get the vernacular names with less requests?

-----

User provided contact info: @augustjohann
System: Safari 11.1.2 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/388b7fa2a5ef0c0e8bbf17544b0018be:287c4a706de51be3b6ac0503c5c94f543474bd4cd15787ee2c22772ecf14a36be7dabe63740576a6d3fb2522f7ba2a53e9bdb5f846bc779cf541b5c6c47dea38)
Referer: https://www.gbif.org/developer/species
Window size: width 1422 - height 777
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-13T05:43:22.168Z',mode:absolute,to:'2018-08-13T05:49:22.168Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-13T05:43:22.168Z',mode:absolute,to:'2018-08-13T05:49:22.168Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
you can see the API documentation here:
https://www.gbif.org/developer/species

So what you do is to first get the taxonKey (the id) from fx the match service you link to above, and then you ask use the link `http://api.gbif.org/v1/species/[taxonKey]/vernacularNames`

An example is http://api.gbif.org/v1/species/5231190/vernacularNames?limit=5&offset=5

**Comment by augustjohann** [comment]
@MortenHofft e.g. with "Zootoca vivipara" the match service:

http://api.gbif.org/v1/species/match?verbose=true&name=Zootoca%20vivipara

does not return a `taxonKey`: 

```
{
  "usageKey": 9702100,
  "scientificName": "Zootoca vivipara (Lichtenstein, 1823)",
  "canonicalName": "Zootoca vivipara",
  "rank": "SPECIES",
  "status": "ACCEPTED",
  "confidence": 97,
  "note": "Similarity: name=110; authorship=0; classification=-2; rank=5; status=1; nextMatch=0",
  "matchType": "EXACT",
  "alternatives": [
    {
      "usageKey": 2468551,
      "acceptedUsageKey": 9702100,
      "scientificName": "Zootoca vivipara (Jacquin, 1787)",
      "canonicalName": "Zootoca vivipara",
      "rank": "SPECIES",
      "status": "SYNONYM",
      "confidence": 97,
      "note": "Similarity: name=110; authorship=0; classification=-2; rank=5; status=0",
      "matchType": "EXACT",
      "kingdom": "Animalia",
      "phylum": "Chordata",
      "order": "Squamata",
      "family": "Lacertidae",
      "genus": "Zootoca",
      "species": "Zootoca vivipara",
      "kingdomKey": 1,
      "phylumKey": 44,
      "classKey": 358,
      "orderKey": 715,
      "familyKey": 5201,
      "genusKey": 2468550,
      "speciesKey": 9702100,
      "synonym": true,
      "class": "Reptilia"
    },
    {
      "usageKey": 2468552,
      "acceptedUsageKey": 9702100,
      "scientificName": "Zootica vivpara Stork, 1838",
      "canonicalName": "Zootica vivpara",
      "rank": "SPECIES",
      "status": "SYNONYM",
      "confidence": 73,
      "note": "Similarity: name=70; authorship=0; classification=-2; rank=5; status=0",
      "matchType": "FUZZY",
      "kingdom": "Animalia",
      "phylum": "Chordata",
      "order": "Squamata",
      "family": "Lacertidae",
      "genus": "Zootoca",
      "species": "Zootoca vivipara",
      "kingdomKey": 1,
      "phylumKey": 44,
      "classKey": 358,
      "orderKey": 715,
      "familyKey": 5201,
      "genusKey": 2468550,
      "speciesKey": 9702100,
      "synonym": true,
      "class": "Reptilia"
    }
  ],
  "kingdom": "Animalia",
  "phylum": "Chordata",
  "order": "Squamata",
  "family": "Lacertidae",
  "genus": "Zootoca",
  "species": "Zootoca vivipara",
  "kingdomKey": 1,
  "phylumKey": 44,
  "classKey": 358,
  "orderKey": 715,
  "familyKey": 5201,
  "genusKey": 2468550,
  "speciesKey": 9702100,
  "synonym": false,
  "class": "Reptilia"
}
```
