### ISSUE TITLE
common name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1492]
**common name**

Hello, I am wondering if there is a way to view my occurrence results by common name in addition to scientific name.  Thank you.

-----

User provided contact info: marybeth.lynch@pc.gc.ca
System: Chrome 68.0.3440 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/9ee5cde14e124fac5e5939ce373a8b72:48f5a67f665750a70695307aaa949bec0e82f1c704fb273f743c953c141ba053668700c6c248d2dafaed328f553ad5b23bb7ec53cef1da989dae288c5bb44607)
Referer: https://www.gbif.org/tools/name-parser
Window size: width 1536 - height 711
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-13T20:43:22.787Z',mode:absolute,to:'2018-08-13T20:49:22.787Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-13T20:43:22.787Z',mode:absolute,to:'2018-08-13T20:49:22.787Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by thomasstjerne** [comment]
User contacted by email
