### ISSUE TITLE
repetetion in Desctription

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1496]
**repetetion in Desctription**

Please check first two lines

-----

User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/62cd33f496b99dfb3bb422d7dcf9987b:e3f48b28b64fe8a240163ab6c7dc8efa10418730364a51c2b34af7cc710c2a5791c4224a6684522f39524892094ec00eda4fddb379cadc3ebf193f7b192a7a99)
Referer: https://www.gbif.org/publisher/cdef28b1-db4e-4c58-aa71-3c5238c2d0b5
Window size: width 2347 - height 1207
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-17T12:06:15.171Z',mode:absolute,to:'2018-08-17T12:12:15.171Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-17T12:06:15.171Z',mode:absolute,to:'2018-08-17T12:12:15.171Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I contacted the administrative point of contact to know if there is anything else they would like us to modify.
