### ISSUE TITLE
add Greg Riccardi as a Chair of the 2018 jury

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1498]
**add Greg Riccardi as a Chair of the 2018 jury**

-----

User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/f18c8dd53533dc8860dff4bacd30de5c:645875d700a710e467d3f6a93884c3c35c56f1167e0a8a8b408c41d4a610c5c1ff4640d2f29d26d2fc2636f537eb31842a4e8fce8e7a5ddcd4b9838eb83cf838)
Referer: https://www.gbif.org/news/1GQURfK5jS4Iq4O06Y0EK4/2018-gbif-ebbe-nielsen-challenge-seeks-open-data-innovations-for-biodiversity
Window size: width 2347 - height 1207
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-20T12:16:14.018Z',mode:absolute,to:'2018-08-20T12:22:14.018Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-20T12:16:14.018Z',mode:absolute,to:'2018-08-20T12:22:14.018Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
@dschigel there's no mention of any jury names here. Given that the original plan had been to announce the jury as another opportunity to promote the challenge and encourage additional entries, I'm uncertain how or why we'd make this addition to a news item that's nearly four months old.

Leaving the issue open.

**Comment by dschigel** [comment]
Please add "Ebbe Nielse Jury 2018
