### ISSUE TITLE
DBpedia info is about country not species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#15]
**DBpedia info is about country not species**

info on Argentina Hill. species page is about Argentina the country.

is it possible to filter the dbpedia query somehow?

-----
fbitem-species3026341
Reported by: @mortenhofft
System: Chrome 55.0.2883 / Mac OS X 10.11.6
Referer: http://demo.gbif.org/species/3026341
Window size: width 1974 - height 1129

**Comment by mdoering** [comment]
This likely tells us it is a country, so we can filter those out. But the dbpedia linkage is not ideal in many more cases. E.g. there might be an entry for Argentinia the genus, but we cant find it by just linking with the name. See https://github.com/gbif/portal16/issues/53

Showing only results which say they are taxa would be good, but that needs some research to see what types are out there in dbpedia

**Comment by timrobertson100** [comment]
IIRC Rod suggested only using it for species, not higher

**Comment by gbif-portal** [comment]
Closed as duplicate of https://github.com/gbif/portal16/issues/199
