### ISSUE TITLE
Authors in article are wrong

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1504]
**Authors in article are wrong**

DOI10.15470/ibqzdo

it reads:
Aedo, C. Pando, F. Jones, M. Schildhauer, M. Aldasoro, J. (2017) Scientific Data

it should read:
Aedo, C. Pando, F.  (2017) Scientific Data

-----

System: Chrome 67.0.3396 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/1b2efc7c717a71ad23f804358045d99f:414fb6ce8666607f150bcf8cfb3f3ba47ef38729d26dc11e217e8570bb844f05d06cf5033b95c67e161f50d5b808048f953bf1ff97d14cee0e72eb6f17101093)
Referer: https://www.gbif.org/resource/search?q=Pando&contentType=literature
Window size: width 1178 - height 1085
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-22T07:03:11.380Z',mode:absolute,to:'2018-08-22T07:09:11.380Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-22T07:03:11.380Z',mode:absolute,to:'2018-08-22T07:09:11.380Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Fixed. This is unfortunately a common problem with Mendeley.
