### ISSUE TITLE
text corrections needed for projectID and projectTitle

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1505]
**text corrections needed for projectID and projectTitle**

The two last paragraphs on the page need some corrections:

- element names: should be "projectID" and "projectTitle" (currently both project ID)
- overall: should we unify the spelling to either reflect the element names (no blanks and camelCase) or the labels in the IPT (with blanks)? I would favor the first, as labels tend to change
- text under projectID: needs to be more prescriptive for BID (and needs some straightening of glitches in the last line). Suggested: 
A unique identifier for the project from which a dataset is derived. The record type is a GUID or other identifier that is near globally unique. This field is _required for a dataset that is funded through programmes operated by GBIF. In this case, the projectID is the ID of the funded project as listed in the contract document, e.g. "BID-AF2016-0001-REG"._
- text under projectTitle: (...) This field is _required for a dataset that is funded (...) _ (syntax,and one excess or missing underscore, as above)

Overall: when did we change to occurrence-only instead of just occurrence? We used to have metadata-only; is this a glitch, or intentional to set it off against sampling event? It raises the question whether we should then also distinguish checklist-only from e.g. checklist-cum-occurrences, but I don't think that is intended.

-----

User provided contact info: @ahahn-gbif
System: Firefox 61.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/a43dad8ac807a7340e915bd327e7e6a2:2cc346a5a9c42c778da7e339912c0b24517eae9f44edfbfd49ce2e9aa2eb6ecafb6b24347eceaa28e4f3af00f390cefe0ce581dc0d770f9ed165db77f06ec045)
Referer: https://www.gbif.org/data-quality-requirements-occurrences
Window size: width 1188 - height 806
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-22T07:41:37.865Z',mode:absolute,to:'2018-08-22T07:47:37.865Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-22T07:41:37.865Z',mode:absolute,to:'2018-08-22T07:47:37.865Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
The same comments apply to the sampling-event page (https://www.gbif.org/data-quality-requirements-sampling-events). On the checklist page (https://www.gbif.org/data-quality-requirements-checklists), the two paragraphs are missing altogether and need to be added and linked.
