### ISSUE TITLE
downloaded data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1507]
**downloaded data**

hello i used the Darwin version of the download, but there is no readable information, just text files that are extremely difficult to read and a folder containing an xml file which i do not know how to use, do you guys have a user guide for how to use the xml file in ARCGIS for location informatoin, or how to pull the photos????

-----

User provided contact info: yuriy.shimko@hdrinc.com
System: Chrome 68.0.3440 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5f64645919c1c3ab35b49c42e5c6b1c3:b8bd00839702974f76f0a4d459614cf0bfd664f88dc46487a87d89359733e4dba43341ea78cd24bf047881d939a9c975d9976f5b1260c042970281ca232de6f2)
Referer: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
Window size: width 1440 - height 714
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-22T21:39:31.455Z',mode:absolute,to:'2018-08-22T21:45:31.455Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-22T21:39:31.455Z',mode:absolute,to:'2018-08-22T21:45:31.455Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
I was expecting something more like this for larger datasets: https://gis.stackexchange.com/questions/174569/adding-custom-web-tile-layer-to-arcmap/257111#257111

For example, an all-plants occurrence layer could be `https://api.gbif.org/v2/map/occurrence/density/Z/X/Y@1x.png?taxonKey=6&style=classic.point` (with `Z/X/Y` being the zoom, x and y parameters).

But I have only ever used QGis, where this is fairly easy.

**Comment by dnoesgaard** [comment]
Aha, I wasn't aware. But this appears to be fairly simple also.

Adding a layer in ArcGIS, I can add parameters for {level}, {col} and {row}. Would that translate directly to z, x, and y?

I just tried adding a layer and it looks, I think:

![screenshot 2019-01-21 at 10 38 57](https://user-images.githubusercontent.com/21358085/51465730-cf1b7c00-1d68-11e9-8268-88d0c012e445.png)

**Comment by dnoesgaard** [comment]
Added Maps API to the ArcGIS FAQ entry now. I think we've done our duty now ;)
