### ISSUE TITLE
News: add an "expiry date" for news that go out of scope, and have them disappear automatically

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#151]
**News: add an &quot;expiry date&quot; for news that go out of scope, and have them disappear automatically**

Some news have an expiry date, e.g. the web developer position advertised with a deadline of March 20 - also visible on the home page demo.gbif.org. This needs manual maintenance so far. It might be handy to evaluate some kind of end date and no longer display and/or link the item from other places in the website after the date has been reached.

-----
fbitem-60af3065d694e748777c6ea94241378d9e7fc5c2
Reported by: @ahahn-gbif
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/news/web-developer-job-2017
Window size: width 1468 - height 479
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-24T14:14:53.205Z',mode:absolute,to:'2017-03-24T14:20:53.205Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-24T14:14:53.205Z',mode:absolute,to:'2017-03-24T14:20:53.205Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Ideally, requests for these pages should return "HTTP 410 Gone", so search engines remove them from their indexes quickly rather than assuming a possible temporary failure.

**Comment by MortenHofft** [comment]
@dnoesgaard how do you feel about simply unpublishing them manually? Do we need the option to show them but not feature them? The option to automatically unpublish? In this case i would think it was fine to unpublish or delete the news item manually so it didn't show up in anywhere on the site.

**Comment by dnoesgaard** [comment]
Generally, I'm not crazy about un-publishing news stories. I think the historical overview can be relevant as well. The job ad is perhaps not the best example, as it does lose its immediate relevance after the due date.

If the only option to get a story away from the frontpage is to un-publish I don't care if it's automated or manual. Automatic un-publishing on a certain expiry date is still un-publishing.

@kcopas - your 2¢?

**Comment by MortenHofft** [comment]
For now we have decided to have a flag on entries specifying if it is suitable for the home page. And one flag specifying if it should show in search. We can extend this in the future with auto publishing and auto un-publishing and auto home-suitable-unflagging.

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/464
