### ISSUE TITLE
Plant misidentified as animal

### ISSUE THREAD

**Issue by andzandz11** [gbif/portal-feedback#1510]
https://www.gbif.org/dataset/e6fab7b3-c733-40b9-8df3-2a03e49532c1/metrics

There are obviously no animals in this dataset. Please check the underlying mechanism that led to this failure, to prevent future misclassifications.

In ~10000 cases the author is not correctly inferred and not being seperated from the species name:
https://www.gbif.org/occurrence/search?dataset_key=e6fab7b3-c733-40b9-8df3-2a03e49532c1&issue=TAXON_MATCH_FUZZY

Thank you!
A

**Comment by ManonGros** [comment]
From what I understand, the following happened:
The misinterpreted species is Linaria vulgaris agg.
Our system does not recognise this species, the closest match it finds is Linaria Bartram, 1792 (a bird) and then infer its taxonomy (see example [here](https://www.gbif.org/occurrence/1308484490)).
The only other taxon provided is the Family "Scrophulariaceae" but in our backbone, the genus Linaria is under the Plantaginaceae family so there is no match.

I assume that this could be corrected if the Kingdom was specified as Plantae.
I will contact the publishers to suggest an update.

**Comment by andzandz11** [comment]
I am still confused because there is no Linaria vulgaris bird species. Maybe the agg. is confusing the classifier?

If I take a look at the raw data all the information is there to infer a species, even if the family is wrong:
<GenusOrMonomial>Linaria</GenusOrMonomial><FirstEpithet>vulgaris</FirstEpithet><Rank>AGG</Rank>
https://api.gbif.org/v1/occurrence/1308905152/fragment

Maybe the classifier will get better if it uses the most detailed information available instead of <FullScientificNameString>?

Thanks!
A

**Comment by ManonGros** [comment]
We do use the <FullScientificNameString> as scientific name. Actually, the mapping between Darwin Core (the standard we use) and ABCD is described [here](http://rs.tdwg.org/dwc/terms/history/dwctoabcd/index.htm).
However, discussions about this mapping should probably take place in https://github.com/tdwg.

@andzandz11 you are correct, AGG is not a rank our system can interpret and that is probably the reason why the species was misidentified.

In any case, thank you very much for raising this issue. I have notified the publishers and I will follow up with them about adding the kingdom to each records. This quick fix should remove this particular ambiguity.

**Comment by ManonGros** [comment]
The publishers have updated their dataset.
