### ISSUE TITLE
GBIF GNA profile

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1513]
**GBIF GNA profile**

I can't find the resource "GBIF GNA Profile Reference Guide for
Darwin Core Archive" which in my opinion is still the best work to get into the nitty gritty of publishing checklist data to GBIF. [Data quality requirements: Checklist datasets](`https://www.gbif.org/data-quality-requirements-checklists)` only covers the Taxon Core + EML. The file is still available on [gbif.jp](http://www.gbif.jp/v2/pdf/gbif_gna_profile_reference_guide.pdf) but it would be good to have a stable reference on gbif.org

-----

User provided contact info: @peterdesmet
System: Chrome 68.0.3440 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/8965a5ed5fe216fd4cd70652a753ba47:ef8c74c8ca7a55c86f968833c60f59dd52e7d0fe4019f49562456824745900532cb7fe176cea182a74f4f0f14886847d2f73e57a7562d63c93e93f7bf3a5a120)
Referer: https://www.gbif.org/data-quality-requirements-checklists
Window size: width 1254 - height 803
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-26T07:14:42.710Z',mode:absolute,to:'2018-08-26T07:20:42.710Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-26T07:14:42.710Z',mode:absolute,to:'2018-08-26T07:20:42.710Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Probably @dnoesgaard, the original location of this (and some other resources) are linked to from here:

https://github.com/gbif/checklistbank/blob/master/docs/DWCA-FORMAT.md

**Comment by kcopas** [comment]
Document attached.

Note that this was removed either during the migration to the new website
or after Kyle Braak's late 2017 review of GBIF documentation, which
specifically recommended removing the GNA Profile Reference Guide. So it
hasn't gone missing in error, and we will not republish it in its current
format.

Note, too, that the checklist bank thread above, speaking of all five
documents listed, mentions, "Sadly they contradict each other in some areas
and there is not a single, complete and up to date document available."

This is a timely thread, though, offering a strong reminder for including
guidance on publishing checklists in our plans for updates in 2019.

**Comment by peterdesmet** [comment]
Just noticed that the Best Practices document still exists in some form at https://github.com/gbif/ipt/wiki/BestPracticesChecklists

**Comment by mdoering** [comment]
... which contains an error I was pointed to just yesterday:
https://github.com/gbif/ipt/wiki/BestPracticesChecklists#normalised-classifications-parentchild

> no parent so that the parent identifier should be null or a “0”

Putting a real zero in there is not a good idea at all!

**Comment by peterdesmet** [comment]
Question: even though it is no longer a recommended document, could it please be made available again? It is something we would very much like to reference. It has the permanent identifier: http://links.gbif.org/gbif_gna_profile_reference_guide (and also referenced as https://www.gbif.org/resources/2562).

**Comment by kcopas** [comment]
@peterdesmet just to confirm: you're specifically looking for this to be placed where it can be referenced? If so, I think we're going to go for a Zenodo DOI.

**Comment by mdoering** [comment]
@kcopas please keep me in the loop when it comes to updated checklist recommendations. [ColDP](https://github.com/Sp2000/coldp/) and maybe an [updated TNC using data packages](https://github.com/tdwg/tnc) should be included

**Comment by peterdesmet** [comment]
@kcopas: yes that would be excellent! When would it be possible to do so? The editor of our article was asking for a better reference than the broken link we currently have.

**Comment by kcopas** [comment]
@mdoering it (or the topic, at least) is an obvious candidate for the next tranche of digital documentation…

**Comment by kcopas** [comment]
@peterdesmet probably won't resolve yet, but it will: https://doi.org/10.5281/zenodo.3463261

All other bibliographic details remain the same.

**Comment by peterdesmet** [comment]
Thanks, so the reference will be:

> GBIF (2010). GBIF GNA Profile Reference Guide for Darwin Core
Archives, version 1.2, released on 1 April 2011, (contributed by
Remsen D.P., Döring, M, Robertson, T.), Copenhagen: Global
Biodiversity Information Facility, 28 pp. https://doi.org/10.5281/zenodo.3463261

Once available, probably good to update the references mentioned above (in the wiki etc.)

**Comment by kcopas** [comment]
Yeah, we will. There now.

**Comment by peterdesmet** [comment]
Ok, might be easier to reference as Zenodo provided:

> Remsen, David P, Robertson, Tim, & Döring, Markus. (2010, April 1). GBIF GNA Profile Reference Guide for Darwin Core Archives (Version Version 1.2). Zenodo. http://doi.org/10.5281/zenodo.3463261

**Comment by kcopas** [comment]
When you return @MattBlissett could you put a couple of redirects in place? Both of the following should resolve to https://doi.org/10.5281/zenodo.3463261

- [ ] http://links.gbif.org/gbif_gna_profile_reference_guide 
- [ ] https://www.gbif.org/resources/2562

Link in wiki updated.

**Comment by kcopas** [comment]
@peterdesmet yeah, Zenodo wouldn't allow for 'corporate' authorship, so Remsen @timrobertson100 and @mdoering got an upgrade from the more modest 'contributor'. You can do as you see fit with the reference.

(mic drop)
