### ISSUE TITLE
Download of occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1516]
**Download of occurrences**

The system is currently not able to process your request. Try to refresh the page and please report the issue if it continues.

-----

System: Chrome 68.0.3440 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/88cd365510d7172fa09c1ebe3edc7435:510a8b6acf3891d49ab5142147832e17fd989a96ea66967a9b09c2c08e720219077c1f5abaf9d2429bf0547352f10366f97c401f05ce7fc727673d53201d33125197b939ec4d98c01e2b9924e789c57e)
Referer: https://www.gbif.org/occurrence/download?taxon_key=5220766
Window size: width 1366 - height 662
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-28T11:30:57.793Z',mode:absolute,to:'2018-08-28T11:36:57.793Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-28T11:30:57.793Z',mode:absolute,to:'2018-08-28T11:36:57.793Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Can not reproduce. Most likely an outage in the APIs.
