### ISSUE TITLE
Downloaded file of occurrences is tab-delimited, not comma-delimited

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1517]
**Downloaded file of occurrences is tab-delimited, not comma-delimited**

I recently downloaded some data (`https://doi.org/10.15468/dl.ux4jcf)` to find the .csv file is actually tab-delimited. That isn't a problem, but maybe the file should be named with the .txt or .tsv extension instead.

-----

User provided contact info: jcoliver@email.arizona.edu
System: Firefox 61.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/cce17f95edfa926252a2e793cac36c07:7adebd3b85765422b68bcbc409d054b6d8d9752850083dc40cf801d1f2c59e94e3c54184e1ff70c2a9eae8329310919f59569831b2fb965f4ea5a5c13971999e)
Referer: https://www.gbif.org/occurrence/download/0001721-180824113759888
Window size: width 1920 - height 928
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-28T23:50:27.296Z',mode:absolute,to:'2018-08-28T23:56:27.296Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-28T23:50:27.296Z',mode:absolute,to:'2018-08-28T23:56:27.296Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
See also https://github.com/gbif/occurrence/issues/100

**Comment by MattBlissett** [comment]
https://github.com/gbif/portal-feedback/issues/2147#issuecomment-518586274 shows the original reason the extension is `.csv` for a TSV.

It's not something I want to change, as it's essentially part of the API -- download the zip and extract `<download-key>.csv`.
