### ISSUE TITLE
Image URLs on this dataset are broken

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1518]
**Image URLs on this dataset are broken**

They all return 404.

-----

User provided contact info: @MattBlissett
System: Firefox 61.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7a53ffe01a8eacee67e6b879a255ef99:a8ed736b50b324ab6194656e7ea555a429bec8778634c2991f0b5923dee7cfcc3aae09178a2ad498021608ecc4256fae694a9a08468a7f3abcb0ed593e8e1a87)
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=1c403d2c-5c37-4237-9746-8ed539b9ba15
Window size: width 1600 - height 758
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-29T02:58:32.539Z',mode:absolute,to:'2018-08-29T03:04:32.539Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-29T02:58:32.539Z',mode:absolute,to:'2018-08-29T03:04:32.539Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I wrote to GBIF France since they were the ones hosting these images.

**Comment by ManonGros** [comment]
GBIF France fixed the issue (the images are beautiful).
