### ISSUE TITLE
Indicate where potential publishers can find an IPT

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1521]
**Indicate where potential publishers can find an IPT**

Neither the IPT page or [Publishing data](`https://www.gbif.org/publishing-data)` indicates where potential publishers can find a hosted IPT. Something along the lines of contact your local representative for support/hosting IPTs that can be used (with a useful link). Basically, it just explains the tool itself, not where to find it.

-----

User provided contact info: @peterdesmet
System: Chrome 68.0.3440 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/668bd3d7bea4b6480874f023d7a91c86:d17a76bb01ec6aaba79147937e5708f8c099f9dc0b7ddb9b675b0588d203574c9163b5a49c989b02861e15676dc542ab2b49fc0516c5677a7ade6b0d42d39ab7)
Referer: https://www.gbif.org/ipt
Window size: width 1331 - height 803
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-29T21:44:00.957Z',mode:absolute,to:'2018-08-29T21:50:00.957Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-29T21:44:00.957Z',mode:absolute,to:'2018-08-29T21:50:00.957Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Thanks @peterdesmet—this is a good point.

[This page](https://www.gbif.org/data-hosting) still needs another good edit, but it seems the obvious place to direct someone looking for a hosted solution. Do you think adding a sentence or two referring to it with a link under the '@Users' section would suffice?

Welcome your thoughts on this, as well as any other feedback…

**Comment by peterdesmet** [comment]
I now see under `@Users`:

> The simplest way to begin using the IPT is to request a free account on a [trusted data hosting centre](https://github.com/gbif/ipt/wiki/dataHostingCentres) allowing you to manage your own datasets and publish them through GBIF.org without the hassle of setting up and maintaining the IPT on your own server.

Is this new? Seems good to me. And better than referring to the [hosting page](https://www.gbif.org/data-hosting) which is currently more targeted to those who want to host than those seeking hosting.
