### ISSUE TITLE
Suggestion to add an expected response time for feedback

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1522]
**Suggestion to add an expected response time for feedback**

A presentation at TDWG implied that we don't respond to feedback (well, actually he said ALA, but people listening seem to have understood it to also apply to GBIF).

A suggestion is that on this box, we add something like "We will respond to your query within 2 working days" so people aren't put off.

Maybe also reword to "All issues are visible to the public, you can browse them at _GitHub_".

-----

User provided contact info: @MattBlissett

**Comment by dnoesgaard** [comment]
To avoid confusion about which "public" I've rephrased the last one to

> All issues are public and available through [Github](https://github.com/gbif/portal-feedback/issues).

I don't know that we _do_ respond to issues within 2 working days though...

**Comment by dnoesgaard** [comment]
Updated translation to read:

> Help us resolve any issues by choosing which type of feedback you’re providing. Please submit your feedback in English, if possible. We aim to respond within 2 working days.
