### ISSUE TITLE
Event date formatted inappropriately

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1523]
**Event date formatted inappropriately**

"January 24, 2017" should either be "24 January 2017" or "2017-01-24"

(Pedantic, but I complain enough about date formatting when we take in data.)

-----

User provided contact info: @MattBlissett
System: Firefox 61.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/ea41a23b5a4ff9e2218f407385f976eb:4e62661d2567ddd47a1b58a9575c29467848fa150a10716f228448afc827bdeda389eaea6d06b95e2221bb21a40af98b15ea7a8eae276d0b9b66b9fa2e341a07)
Referer: https://www.gbif.org/dataset/0645ccdb-e001-4ab0-9729-51f1755e007e
Window size: width 1279 - height 758
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-30T03:24:27.934Z',mode:absolute,to:'2018-08-30T03:30:27.934Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-30T03:24:27.934Z',mode:absolute,to:'2018-08-30T03:30:27.934Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Isn't it just american english? @kcopas what format should be used for english in general. I see that several formats are used on the website.

**Comment by timhirsch** [comment]
NO! We use UK English as interpreted by UN style guidelines without exception. If there are inconsistencies the exceptions are wrong. The key thing is we stick to one format.

**Comment by MortenHofft** [comment]
CLOSED BY gbif/portal16@1a982b6 !
