### ISSUE TITLE
Gemmabryum vinosum J.R. Spence & Kellman

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1526]
**Gemmabryum vinosum J.R. Spence &amp; Kellman**

Species - Gemmabryum vinosum J.R. Spence & Kellman
DOI: 10.3120/0024-9637-62.2.124

-----

User provided contact info: rcubey@rbge.org.uk
System: Chrome 68.0.3440 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b18da2377b591b82d9700944168dfec6:4148be03c3c9e5a3a81ac787ab936e952b608dd8e1e8f089b840d5c1c85f35eabed9bb54b08652bade95813ba0ae5a7fe11d261dda0b5981ba624f24d9f5aeef)
Referer: https://www.gbif.org/occurrence/1850998526
Window size: width 1600 - height 763
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-30T23:19:35.666Z',mode:absolute,to:'2018-08-30T23:25:35.666Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-30T23:19:35.666Z',mode:absolute,to:'2018-08-30T23:25:35.666Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Presuming this means *Gemmabryum vinosum* J.R. Spence & Kellman is missing from the backbone.

**Comment by camiplata** [comment]
Gemmabryum vinosum J.R. Spence & Kellman is now present in both [COL](https://www.catalogueoflife.org/data/taxon/9TWFH) and the [GBIF Backbone](https://www.gbif.org/species/8772280)
