### ISSUE TITLE
Validator date doesn't take into account timezone

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1530]
**Date doesn&#39;t take into account timezone**

I'm looking at one "It was generated 39 minutes ago" but still says "30 August 2018" at the top. 

That's particularly odd, as it's 31 August in UTC by now, although it wasn't when it was generated.

(Minor, but users re-run these reports as they fix their data, and one was puzzled by which was the most recent.)

-----

User provided contact info: @MattBlissett
System: Firefox 61.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/07860dfa259cfd941e26cce989353bbe:93b092a57a70300bcbb2b2569facc88600bdd9e66c5935633edd5ccf42240d1006d179ccfe47d32e58ca29b5084f34e1adcf2cc1435690cf1b62a1ea40a9b89f)
Referer: https://www.gbif.org/tools/data-validator
Window size: width 1600 - height 758
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-31T00:21:53.521Z',mode:absolute,to:'2018-08-31T00:27:53.521Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-31T00:21:53.521Z',mode:absolute,to:'2018-08-31T00:27:53.521Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
This is a (minor) portal issue.

https://www.gbif.org/tools/data-validator/1540191107870 has `"startTimestamp": 1540226491745`, which is 22 Oct 16:41:31 UTC, or **23 Oct** 04:41:31 +12 in Fiji.

If I temporarily set my computer to Fiji time, the web page still shows "Validation report 22 October 2018", but also says "generated a few seconds ago".
