### ISSUE TITLE
https://www.gbif.org/occurrence/1449841910 This specie shows 3 occurrences, actually is just one. You considered La Guadalupe as a country when is just a county in Colombia.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1535]
**`https://www.gbif.org/occurrence/1449841910` This specie shows 3 occurrences, actually is just one. You considered La Guadalupe as a country when is just a county in Colombia.**

-----

System: Chrome 68.0.3440 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/3dc6d9e984abde44d8ea7bff399dcfeb:bc7f3de8674a44048cdd4ff2a9e919a9ecb9954980d4cd0b247d00cc28d70509a0c96cf7f1422d8e48046bcca391e0e50a8f39c50d9f4e31e17a50f0ddb49397)
Referer: https://www.gbif.org/occurrence/1449841910
Window size: width 1280 - height 584
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-05T23:15:51.623Z',mode:absolute,to:'2018-09-05T23:21:51.623Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-05T23:15:51.623Z',mode:absolute,to:'2018-09-05T23:21:51.623Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
I haven't read the paper, but I do see three occurrences.


Guadalupe (with an A) can be a county in Colombia, but the record says country Guadeloupe with an E.

We'll need country=Colombia to show it correctly.

The dataset also has
```
<alternateIdentifier>http://dx.doi.org/https://doi.org/10.11646/zootaxa.4247.2.7</alternateIdentifier>
```
which we don't understand. (`https://doi.org/10.11646/zootaxa.4247.2.7`, `http://dx.doi.org/10.11646/zootaxa.4247.2.7` or `10.11646/zootaxa.4247.2.7` would be fine.)

**Comment by ManonGros** [comment]
This is a PLAZI dataset. And according to the title of the publication this was extracted from, the occurrences are from Columbia:

Two new species of freshwater, cave-dwelling crabs of the genus Neostrengeria Pretzmann, 1965, from Colombia (Crustacea: Decapoda: Pseudothelphusidae). Zootaxa 4247 (2): 157-164, DOI:

**Comment by gsautter** [comment]
Thanks for the hint, I updated the underlying document. The DwC-A should be updated within the next 15 minutes, and the harvester should be notified of the update.

**Comment by ManonGros** [comment]
It seems that one of the occurrences remains in Guadeloupe (https://www.gbif.org/occurrence/search?dataset_key=5e984d44-b4d1-4545-80fa-6c8ba21d11bc)

**Comment by gsautter** [comment]
Thanks for spotting this, I corrected it now. Looks like the country survived in an attribute that was copied from the faulty holotype citation (that I corrected before) to the paratypes citation as per "same data as for holotype".
The updated DwC-A should be available in ten minutes or so the latest.

**Comment by ManonGros** [comment]
Perfect! Thanks.
