### ISSUE TITLE
suspect location

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1536]
**suspect location**

the lat lon of urn:catalog:TRH:B:741306/1 appears to be 250km from the locality listed

-----

System: Firefox 61.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/54b230f37a0ea3a51aa30523355adea1:89a2260134b85568f67b5aae2568899409f5c8bdc7e68740ad9f29976e3e26f8ac9e71dedf2c1d893e1a81a37d7bd4bb4d43e95a7ef73e4c2397522d735bbbc3a975ad50f826f26d35c51d217d9bffaa)
Referer: https://www.gbif.org/user/download
Window size: width 1280 - height 607
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-06T08:00:14.678Z',mode:absolute,to:'2018-09-06T08:06:14.678Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-06T08:00:14.678Z',mode:absolute,to:'2018-09-06T08:06:14.678Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
information missing from issue, but probably this occurrence: https://www.gbif.org/occurrence/1042450084

**Comment by ManonGros** [comment]
The publishers have been contacted.

**Comment by dagendresen** [comment]
Curator Tommy Prestø at the NTNU University Museum in Trondheim has updated the museum database. The GBIF export tonight will update the data record in the GBIF portal. Thanks to @andersfi

**Comment by ManonGros** [comment]
Thank you @dagendresen and @andersfi! However, the last time the dataset was ingested with change was the 27th of September 2018. This means that the occurrence concerned hasn't been updated. Could you help us with that?

**Comment by ManonGros** [comment]
The occurrence is now updated in GBIF as well.
