### ISSUE TITLE
wrong coordinates

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1539]
**wrong coordinates**

I've found an occurrence that has the correct location information, but the coordinates are incorrect, so it's causing it to show up in the wrong area of the map. The correct coordinates should be, approximately, 34.971065 lat, -77.996208 long. It is showing Oklahoma state in the U.S., but should be North Carolina state in the U.S.

https://www.gbif.org/occurrence/895423429

-----

User provided contact info: @feistyone
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/83e27a3b62e262f69f6080b8e468c500:b5d57b475472be75a5c4c5a94748922b9981e434f08f311dbca152d7b1cc00528dace61a02bd9b3387a911f4475446f5ba08f104cabe7c1b62a2cb643c3fdd01)
Referer: https://www.gbif.org/faq?q=coordinates
Window size: width 1536 - height 700
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-09T18:42:32.702Z',mode:absolute,to:'2018-09-09T18:48:32.702Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-09T18:42:32.702Z',mode:absolute,to:'2018-09-09T18:48:32.702Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publishers have been contacted.

**Comment by ManonGros** [comment]
Thanks @feistyone, the publishers have corrected the coordinates.
