### ISSUE TITLE
coordinates available but missing from records

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1542]
**coordinates available but missing from records**

correct coordinates for these records are available at record data source (see NZAC portal link) but they are not displaying on GBIF

-----

User provided contact info: tassells@landcareresearch.co.nz
System: Chrome 68.0.3440 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5bf6cb0a446caf0e405a3f1c086970db:c30759f6642a9d10f19c779dc974fa24811690b60782da0dacbfd4a208c694e3c4d5fc6148d2dbe903b314779437b853be5c7e3e40a11a8e7136ab37a6405790)
Referer: https://www.gbif.org/occurrence/search?dataset_key=6e4b215e-9019-4934-8433-65d80a35c230&issue=COORDINATE_OUT_OF_RANGE
Window size: width 1866 - height 1014
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-13T00:08:26.104Z',mode:absolute,to:'2018-09-13T00:14:26.104Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-13T00:08:26.104Z',mode:absolute,to:'2018-09-13T00:14:26.104Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Hi,

Thanks for bringing this to our attention, I'm CCing your colleague Aaron.

These three records have incorrect coordinates in the data file shared 
with GBIF, for example -88°, -225°.

There are other errors, it will be worth using the "Issues and flags" 
search on GBIF.org to help find them: 
https://www.gbif.org/occurrence/search?dataset_key=6e4b215e-9019-4934-8433-65d80a35c230&issue=COUNTRY_COORDINATE_MISMATCH&issue=COUNTRY_DERIVED_FROM_COORDINATES&issue=COORDINATE_OUT_OF_RANGE&issue=PRESUMED_NEGATED_LONGITUDE&issue=PRESUMED_NEGATED_LATITUDE

Best regards,

Matt Blissett
