### ISSUE TITLE
No images in South Australian Museum Terrestrial Invertebrate Images

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1543]
Prompted by Twitter rant: https://twitter.com/rdmpage/status/1040102211366395906

https://www.gbif.org/occurrence/search?dataset_key=de077267-677e-4b3e-a40e-753a2d1c7b6a&media_type=StillImage

Images in [ALA source](https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:dr742), but not seeing anything in the verbatim data, so something seems not to be coming through.

**Comment by ManonGros** [comment]
It looks like there are images now.

**Comment by kcopas** [comment]
Yeah, and [about 50,000 additional images via ALA](https://www.gbif.org/occurrence/gallery?publishing_country=AU&advanced=1), too—still be good to know if this was a systemic design or an outage…
