### ISSUE TITLE
how do i remove a country from my filter?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1545]
**how do i remove a country from my filter?**

-----

User provided contact info: 3650724@myuwc.ac.za
System: Edge 17.17134.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/69384ea653847bec247e8a35eb3e0ac6:84278f5ea7ef83a3fc9d085aa0037efa494c045f3b9cdb5ba70bb8dd8a6988d24e77f0d955110281d5833a3077f79dd46381e37e18dde7b289eb7f26dcc887f5)
Referer: https://www.gbif.org/health
Window size: width 1920 - height 963
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-18T12:40:43.210Z',mode:absolute,to:'2018-09-18T12:46:43.210Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-18T12:40:43.210Z',mode:absolute,to:'2018-09-18T12:46:43.210Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I'm not sure I understand entirely. 

The API allow for `not` https://www.gbif.org/developer/occurrence.

But using the website, asking for occurrences from all countries but one isn't really possible I'm afraid. You can only select countries that you are intersted in. 

> user answered by email
