### ISSUE TITLE
Syzygium pterophorum

### ISSUE THREAD

**Issue by SandyUMSFRC** [gbif/portal-feedback#1548]
Hi,

I found out that the occurences table of Syzygium pterophorum _Merr. & L.M.Perry_  recorded a collection from New Coledonia. This species suppose be endemic to Sabah. So I checked the collection from New Coledonia, and turn out that the specimen picture is not S. pterophorum, it is S. pterocalyx

I hope the person in charge can remove that collection and place it into the correct species to prevent confusion.

Thanks!

**Comment by ManonGros** [comment]
I assume the two occurrence concerned are [these](https://www.gbif.org/occurrence/search?country=NC&dataset_key=15f819bd-6612-4447-854b-14d12ee1022d&taxon_key=3183955).

**Comment by SandyUMSFRC** [comment]
> I assume the two occurrence records concerned are [these](https://www.gbif.org/occurrence/search?country=NC&dataset_key=15f819bd-6612-4447-854b-14d12ee1022d&taxon_key=3183955).

yes

**Comment by ManonGros** [comment]
I have contacted the publishers by email.

**Comment by ManonGros** [comment]
Thanks @jeroencreuwels! Do you know when these changes will be visible on GBIF?

**Comment by jeroencreuwels** [comment]
At Naturalis we have a quarterly updates of all our datasets, we just missed the September harvest. In January 2019 we hope to publish the new Botany dataset.

**Comment by ManonGros** [comment]
Great! Thanks for letting us know.
