### ISSUE TITLE
Problem with DwC-A download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1552]
**Problem with DwC-A download**

I have downloaded the following file:
Download Information:
    DOI: `https://doi.org/10.15468/dl.oaddn3` (may take some hours before being active)
    Creation Date: Monday, 24 September 2018 15:11:44 o'clock GMT
    Records included: 37640 records from 1 published datasets

In the occurrence.txt and verbatim.txt tables the header rows do not correspond to the column content, at least in part. I wonder, if this is a provider problem, but since occurrence should contain cleaned data, I believe it's an issue with the output. 
For example, first row, ID=1844992517
OK up to column recordedBy, but then initials of recorder in column individualCount (="P.") and subsequent columns appear to contain co-collectors. eventTime seems to be ok again, by the year is given under month, etc.
Best wishes
Walter
P.
 

Apart from this, a suggestion for the page 
`https://www.gbif.org/faq?question=opening-gbif-csv-in-excel` 

Using LibreOffice Calc eliminates the necessity to specify format and character encoding, the programm automatically recognizes these parameters.

-----

User provided contact info: w.berendsohn@bgbm.org
System: Firefox 62.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/8ff8b47775febee23de05388974a9a4d:77a4c5ad5b24c31dee7032e22f0a1f7e8a4502fd481e5e481d99d84baf06520ad46fd7a97fa2f8a3bb4410da0ba7a987acba806a20362ec3e1a315c27c4a9894)
Referer: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
Window size: width 1762 - height 886
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-24T17:41:19.891Z',mode:absolute,to:'2018-09-24T17:47:19.891Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-24T17:41:19.891Z',mode:absolute,to:'2018-09-24T17:47:19.891Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal-feedback/issues/1555
