### ISSUE TITLE
Banisteriopsis caapi on Maui

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1554]
**Banisteriopsis caapi on Maui**

Hopefully, you can use this evidence to add to the GBIF database to show that Banisteriopsis caapi occurs on Maui:
`http://starrenvironmental.com/images/search/?q=Banisteriopsis+caapi`
Aloha,
Philip Thomas
PT@PhilipT.com

-----

User provided contact info: PT@PhilipT.com
System: Chrome 68.0.3440 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/221a6f887074e71aa63257807059d4be:74fbc9bd1ed28db6981c648618deda099878d88b4dd0cc4ed6f84e61716f52ca57a38d303c84167c2cd900add983dfa34653bf34e3fdc6444fc3aed44a9f9419)
Referer: https://www.gbif.org/user/profile
Window size: width 1536 - height 766
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-24T17:53:50.706Z',mode:absolute,to:'2018-09-24T17:59:50.706Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-24T17:53:50.706Z',mode:absolute,to:'2018-09-24T17:59:50.706Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
