### ISSUE TITLE
Citation edit

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1556]
**Citation edit**

Hi, I have updated the citation for multiple datasets on the IPT. However, on GBIF, it does not show it as being updated. This was done almost a week ago. How can this be rectified? Thanks.

-----

User provided contact info: renguste@gmail.com
System: Chrome 69.0.3497 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/8679de0d9c71e6aba0de147b277f8ac7:c8e6558033975d27905e41ae6569387b6d9cc7620f1bdd6cbdff4fae4a6b9ba665171999b67e398cdd456d18022a93edcbb88fe3d2f9b63187bc8b3ef0033229)
Referer: https://www.gbif.org/dataset/c151307b-d8f4-49e3-878d-ea3ab8f3bd65
Window size: width 1920 - height 969
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-25T15:19:45.344Z',mode:absolute,to:'2018-09-25T15:25:45.344Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-25T15:19:45.344Z',mode:absolute,to:'2018-09-25T15:25:45.344Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
User also asked the helpdesk, who answered.
