### ISSUE TITLE
I am unable to download the data. When I click on the links, a new tab opens in the browser that says "this page isn't working" api.gbif.org didn’t send any data. Please help!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1557]
**I am unable to download the data. When I click on the links, a new tab opens in the browser that says &quot;this page isn&#39;t working&quot; api.gbif.org didn’t send any data. Please help!**

-----

System: Chrome 69.0.3497 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/2c73fafdee7da4d210170da30620541b:a91ddad8555d2cf21be0b49ed6ab988239761bbd3722b5a5c11ec610d3645d39b80b65f56617c8dce5f3db58b1f1a8d0c5916240a41e9517386688f5108fa27f)
Referer: https://www.gbif.org/user/profile
Window size: width 1600 - height 758
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-26T07:13:26.205Z',mode:absolute,to:'2018-09-26T07:19:26.205Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-26T07:13:26.205Z',mode:absolute,to:'2018-09-26T07:19:26.205Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Could you please send the link that isn't working. Either from the mail or a link to the download page?
Thanks

> sen per mail

**Comment by MattBlissett** [comment]
Please CC the helpdesk when you reply by mail.

I'd already started looking into this users downloads, and I don't see any problem with any of them.
