### ISSUE TITLE
University of Hargeisa Data publishing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1559]
**University of Hargeisa Data publishing**

GBIF is now publishing 39 records. It says it is out of sync. I was expecting closer to 200.  Should I just wait another 24 hours? Or is there somewhere I can go to see which records were rejected and why/

-----

User provided contact info: mary.barkworth@usu.edu
System: Chrome 69.0.3497 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/897f8247cc51865d3a6311bc03add3ce:3c2e5ab1db5b1bb08c5508b4b2e2af980d16377db7e88aaf467120aca37f8ce0776e6710f285c831989fd4ab2515ee546d6743db30f898eaf0c67203810caaf9)
Referer: https://www.gbif.org/publisher/5fe4a5bb-1708-4046-8495-bb6a7c93aae6
Window size: width 1568 - height 971
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-27T11:02:43.895Z',mode:absolute,to:'2018-09-27T11:08:43.895Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-27T11:02:43.895Z',mode:absolute,to:'2018-09-27T11:08:43.895Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Looks like the data is in sync now.

https://www.gbif.org/dataset/e1966d34-2144-4a07-a6d4-b246d6f047aa
You can see the ingestion history here
https://management-tools.gbif.org/crawl-history?uuid=e1966d34-2144-4a07-a6d4-b246d6f047aa

> answered per mail
