### ISSUE TITLE
wrong authority?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1560]
**wrong authority?**

I suspect the authority here should be Lehm or Lehm & Kraenzl. given `https://en.wikipedia.org/wiki/Trichosalpinx_orbicularis`

-----

User provided contact info: @kueda
System: Chrome 69.0.3497 / Mac OS X 10.12.6
User: [See in registry](https://www.gbif.org/api/feedback/user/b9a440f35d918c8ef1d57dc40b1beba8:ec24e1d7777078719e801ab7d1a05935672c4e3e9758684ed1a1a412c11d83a6558aa5089ee759848a18b6432915c2d45b0bb9b85a97ea051c69b0b658b98bb6)
Referer: https://www.gbif.org/species/9022248
Window size: width 1088 - height 618
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-01T02:11:02.114Z',mode:absolute,to:'2018-10-01T02:17:02.114Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-01T02:11:02.114Z',mode:absolute,to:'2018-10-01T02:17:02.114Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This is correct in the new backbone: https://www.gbif.org/species/2791649
