### ISSUE TITLE
Encourage users to write feedback and Helpdesk messages in English

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#1561]
I just noticed that there were a few more message to the helpdesk in French this past week. Could it be because people can now access gbif.org in French?
It might be worth adding a note somewhere, something like "Please write your feedback/inquiry in English if possible".

**Comment by dnoesgaard** [comment]
I've added "Please submit your feedback in English, if possible." a few places now. Obviously, this will need to be translated also ;)
