### ISSUE TITLE
columns overlap

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1565]
**columns overlap**

-----

System: Chrome 69.0.3497 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/67d56dad110c341db8b8964f987ee663:581b3b2664e6edd8035e664fa7bed52459a7f7e62a73d3e8f48d17c8d13ba2e71f6648c48b72684f4d1d24bf93e9ddc9252de90f6c83ca479905952f7ba5de77)
Referer: https://www.gbif.org/citation-guidelines
Window size: width 1280 - height 882
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-05T02:21:22.050Z',mode:absolute,to:'2018-10-05T02:27:22.050Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-05T02:21:22.050Z',mode:absolute,to:'2018-10-05T02:27:22.050Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I'm not sure what the user means. I do not see any columns on the page. And no overlaps either.

> user asked per email what the issue is

**Comment by MattBlissett** [comment]
Closing lacking further information.
