### ISSUE TITLE
country page -> participation tab not translated

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1566]
**country page -&gt; participation tab not translated**

The text on this part is pulled from Contentful and should be translatable, no?

(cc: @kcopas)

-----

User provided contact info: @dnoesgaard
System: Chrome 69.0.3497 / Mac OS X 10.14.0
User: [See in registry](https://www.gbif.org/api/feedback/user/36181de8acdf22efb4e545415de3daee:2e75ac7a4883a97c2a5f2eff393ab8dfc496aef05d1f34c0337044cc34527db427b9bb6acfaeb3ba9c8add2404c7f7777cad22770e958d20e41953e55310c2b8)
Referer: https://www.gbif.org/pt/country/PT/participation
Window size: width 1440 - height 702
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-05T06:23:13.953Z',mode:absolute,to:'2018-10-05T06:29:13.953Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-05T06:23:13.953Z',mode:absolute,to:'2018-10-05T06:29:13.953Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
yes it is: https://app.contentful.com/spaces/uo17ejk9rkwj/entries/8549

**Comment by dnoesgaard** [comment]
Sorry, I meant: shouldn't the translated version be shown on the website?

**Comment by MortenHofft** [comment]
Ahh - in that case yes it ought to. But it clearly isn't made to be.
