### ISSUE TITLE
2018 update

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1567]
**2018 update**

Surely it's on the list - just a reminder that we need to update this page with 2018 SR with the e-version and source book

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e3d488fcfa479c90d43a19480b3bb273:819f57abb6a02ab9f3c11bddcf5d61bc87bc9a02ff79eeb346b850d1130852553c1bc2ffed80cee7388d650b8ef4a08aedb9ea53a4e3820ba2008a8420dbe037)
Referer: https://www.gbif.org/science-review
Window size: width 2144 - height 1198
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-05T11:22:13.904Z',mode:absolute,to:'2018-10-05T11:28:13.904Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-05T11:22:13.904Z',mode:absolute,to:'2018-10-05T11:28:13.904Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Looks like someone already did...

**Comment by kcopas** [comment]
I haven't updated, but I saw that a version was there—seemed like I either needed to be ready for questions or tell people it was there, even if it means we need to update it later.

@dschigel there is no 2018 sourcebook—people can access the full list through the website with much more control and accuracy than ever before.

**Comment by dnoesgaard** [comment]
I forget–did we agree to kill that page altogether?

**Comment by kcopas** [comment]
Right—it's the article, not the document. We don't have it in the nav. What if any reasons are there in its favour? 

If we want a consistent landing page, I think it should show all the back issues, too, rather than just the one. But I'm ambivalent on whether it's worth the trouble/duplication of effort.

**Comment by dnoesgaard** [comment]
Agree completely. It only adds to the confusion. I guess I created it because I was a bit unhappy with the document resource styling(sic!). But now with a DOI, the document page should be the landing page for the SR.

**Comment by dnoesgaard** [comment]
(that's not to say we can't have a (search?) page that includes all issues...)

**Comment by MortenHofft** [comment]
> I guess I created it because I was a bit unhappy with the document resource styling

@dnoesgaard Feel free to come with suggestions for how it should be different. I't is likely ease to accommodate.
