### ISSUE TITLE
May I get you to flush and reharvest this dataset, 00ed18ea-4993-4809-a656-62363baa4808? We unfortunately had to remove ~150 erroneous records and do not wish to have these persist in your index.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1569]
**May I get you to flush and reharvest this dataset, 00ed18ea-4993-4809-a656-62363baa4808? We unfortunately had to remove ~150 erroneous records and do not wish to have these persist in your index.**

-----

User provided contact info: @dshorthouse
System: Chrome 69.0.3497 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/69cfd9f39579b847d8347cc827a48ecc:5e4bb48ad338519468c6e1675404d4c67348960b61a3bc43b8706fa02ead241d94148349a47ea465abb4fb2d48d7ddfc8a3295ede6618c9c2042fe09732729b0aaa279b2aa8c95abe09e4de0bccb2269)
Referer: https://www.gbif.org/dataset/00ed18ea-4993-4809-a656-62363baa4808
Window size: width 1427 - height 748
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-05T14:05:11.434Z',mode:absolute,to:'2018-10-05T14:11:11.434Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-05T14:05:11.434Z',mode:absolute,to:'2018-10-05T14:11:11.434Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Hi @dshorthouse / David,

The [IPT](http://ipt.nature.ca/resource.do?r=cmn_parasite) reports 15229 records, which is what I see from the most recent ingestion: https://management-tools.gbif.org/crawl-history?uuid=00ed18ea-4993-4809-a656-62363baa4808

Since this is a DWCA dataset, the missing records will be deleted automatically at about 23:45 UTC.
