### ISSUE TITLE
Unique ID with the name checker CSV?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1572]
**Unique ID with the name checker CSV?**

Dear GBIF, when using the tool to normalize species names against the GBIF backbone, it would be great if the resulting CSV for download included your unique ID for the species, e.g. `https://www.gbif.org/species/2962021` or other global unique identifier. Which DwC term should that be matched to by the way?

-----

User provided contact info: @DanBIF
System: Chrome 69.0.3497 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/92a3d23b496a21fb42638ccc6cc7bfe3:6380d6eb68b49fae63ce45f27e46c5f03efcf117369db459bc2b07bab59c6e8ca8a72165b8a9a896f6e9d4a040e048ec06a8be5967a11a79008bfa43a798cf7e)
Referer: https://www.gbif.org/tools/species-lookup
Window size: width 1920 - height 1009
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-09T13:48:15.589Z',mode:absolute,to:'2018-10-09T13:54:15.589Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-09T13:48:15.589Z',mode:absolute,to:'2018-10-09T13:54:15.589Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The key column in the downloaded csv corresponds to https://www.gbif.org/species/[key]

Hope that helps.
