### ISSUE TITLE
Network map not displaying on Safari

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1573]
Map on the [network page](https://www.gbif.org/the-gbif-network) is not displaying for me in Mac/Safari, though it is in Firefox…
![network-map-safari](https://user-images.githubusercontent.com/12379236/46731054-f9e63680-cc89-11e8-929b-710152f31b68.png)

**Comment by MortenHofft** [comment]
Annoying - I see it just fine in Safari. Though it loaded slowly.

**Comment by MortenHofft** [comment]
@kcopas is this still the case please? I wonder because it cannot reproduce it.

**Comment by kcopas** [comment]
No—slow at times, but it shows
