### ISSUE TITLE
Entering multiple catalog numbers into the search interface

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1575]
**Entering multiple catalog numbers into the search interface**

Is there a way that I can enter multiple catalog numbers from a single provider into the search interface to be able to pull up a list of specific records from that provider?  I am trying to match vouchers from other collections to tissues in our collection for mapping to GGBN and need a list of GUIDs for those records.

-----

User provided contact info: abentley@ku.edu
System: Chrome 69.0.3497 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5b7fb739a2e5ef832a0e1cbe2d461425:09d1db14dad4e942c7ca957221a63e104365c8335930051125e83a0b257890b5d358e80edb6f0487a04e7e858a64e93af09ea06fd7a843c816f9b31c44598e36)
Referer: https://www.gbif.org/occurrence/search?institution_code=bpbm&taxon_key=204
Window size: width 2133 - height 1410
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-10T16:03:43.361Z',mode:absolute,to:'2018-10-10T16:09:43.361Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-10T16:03:43.361Z',mode:absolute,to:'2018-10-10T16:09:43.361Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
> user informed per email

**Comment by acbentley** [comment]
No, not a trick question but I have a large list of numbers that I need to enter and it is extremely tedious to enter each one individually.  I was wondering if there was some way of just entering a list in one go.

**Comment by MattBlissett** [comment]
There may be a limit to the length of the URL, so this could need multiple searches, especially if the  catalogue numbers are long.

But you could prepare the query using find & replace in a text editor, or (Mac/Linux) a small command:

```
cat catnums.txt | tr '\n' '~' | sed 's/~/\&catalog_number=/g'
```

and that add that to the end of the URL.

**Comment by MortenHofft** [comment]
There is always the API if the interface don't suffice. that might be a better option?
