### ISSUE TITLE
I don't find a way to delete a completed download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1576]
**I don&#39;t find a way to delete a completed download**

I don't need the download with DOI `10.15468/dl.m7blny` anymore. In order to decrease the overload on GBIF servers, I find worth to mention it, as it is a big download. 
Thanks in advance.

-----

User provided contact info: @damianooldoni
System: Chrome 69.0.3497 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/f47ce96efc50e2bbe91f04bd4322ed6c:fee83d91b53cfe121a20980c8825453d31ea26b53e1f16c73964b63ceadbae35ae3a3cecc9f910e47a95caa3ad4316b4041be6af4569bfc03a1faee5b3e43ec9)
Referer: https://www.gbif.org/user/download
Window size: width 1920 - height 948
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-10T16:43:32.876Z',mode:absolute,to:'2018-10-10T16:49:32.876Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-10T16:43:32.876Z',mode:absolute,to:'2018-10-10T16:49:32.876Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by damianooldoni** [comment]
Sorry, now I udnerstand the reason why. I deleted it already by pressing the red button. Afterwards the button disappears, but no other information about the previous deletion is given.
Anyway, issue solved I think.

**Comment by MortenHofft** [comment]
Yes, that is confusing. Deleting a download really just sets it as ready for deletion. The actually deletion only runs every 3 months or so. That also means you can undo it.

It is only eligible for deletion as the text says.

Thank you for mentioning it!
