### ISSUE TITLE
Adding 11th country breaks facet count

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1577]
**Adding 11th country breaks facet count**

`https://www.gbif.org/occurrence/search?basis_of_record=PRESERVED_SPECIMEN&country=KP&country=NP&country=JP&country=CN&country=LK&country=KR&country=US&country=AU&country=NZ&country=BR&taxon_key=7228684&taxon_key=246&taxon_key=245&taxon_key=7219203`

This page has 10 countries, and the DPRK facet on the left shows as 59 records.  However, adding an eleventh country makes it drop to 0

-----

User provided contact info: @timrobertson100
System: Chrome 69.0.3497 / Mac OS X 10.13.5
User: [See in registry](https://www.gbif.org/api/feedback/user/28be5ca9dc7a16d7361aa187a2c9d5f5:edd7a1c3c431bcbdcb512c5209328eaa9214cf71ef0b09091936b2d59441b9c6b55ea727719e6e47ecb8e156feb3139df6931fa5ced87cceedac63a4f15b83cb)
Referer: https://www.gbif.org/occurrence/search?basis_of_record=PRESERVED_SPECIMEN&country=KP&country=NP&country=JP&country=CN&country=LK&country=KR&country=US&country=AU&country=NZ&country=BR&taxon_key=7228684&taxon_key=246&taxon_key=245&taxon_key=7219203
Window size: width 1680 - height 948
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-10T21:40:22.566Z',mode:absolute,to:'2018-10-10T21:46:22.566Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-10T21:40:22.566Z',mode:absolute,to:'2018-10-10T21:46:22.566Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
apparently it only ever ask for top 10, unless an enum with a (lower) fixed size such as issues.
same issues goes for
any search with more than 10 selected. e.g. [datasets](https://www.gbif.org/occurrence/search?basis_of_record=PRESERVED_SPECIMEN&dataset_key=b5cdf794-8fa4-4a85-8b26-755d087bf531&dataset_key=15f819bd-6612-4447-854b-14d12ee1022d&dataset_key=eb7681c5-5c9c-4e28-954f-f328991c7004&dataset_key=d415c253-4d61-4459-9d25-4015b9084fb0&dataset_key=847375df-8ac8-4189-a8d6-deaefb90355c&dataset_key=9f747cff-839f-4485-83a1-f10317a92a82&dataset_key=4ce8e3f9-2546-4af1-b28d-e2eadf05dfd4&dataset_key=821cc27a-e3bb-4bc5-ac34-89ada245069d&dataset_key=7bd65a7a-f762-11e1-a439-00145eb45e9a&dataset_key=cd6e21c8-9e8a-493a-8a76-fbf7862069e5&dataset_key=95db4db8-f762-11e1-a439-00145eb45e9a&taxon_key=7228684&taxon_key=246&taxon_key=245&taxon_key=7219203)

the ui should up the facet.limit to max(10, nrOfSelectedInCategory)
