### ISSUE TITLE
Link to Partner site not available on news item

### ISSUE THREAD

**Issue by KFratnzen** [gbif/portal-feedback#1579]
Hi,

I was just wondering if a direct link to SPREP's homepage could be made available from this news item?

https://www.gbif.org/news/6akAtKIuAwyCk4ISkSoCQW/new-gbif-partner-in-the-pacific

Thanks,
Kate

**Comment by timhirsch** [comment]
Done!

**Comment by MattBlissett** [comment]
*tnz*? 🤨
