### ISSUE TITLE
URL formatting on user IDs

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1580]
**URL formatting on user IDs**

A bit of formatting love is needed on the user IDs on this page. This is a wonderful example of ORCID use from a new publisher

-----

User provided contact info: @timrobertson100
System: Chrome 69.0.3497 / Mac OS X 10.13.5
User: [See in registry](https://www.gbif.org/api/feedback/user/a971778b2121a1a7086333d65994962e:b7d75472f2796413bb432351ff7fc15b45c7a7aeca508cddec5497a4e0a84486d5cfb76c0e1691b2aa77114ce3341d6ef1056900e89d5733d73c68bcf95419fa)
Referer: https://www.gbif.org/dataset/24baf0da-60a9-4a13-99d7-a8c860c3cb30
Window size: width 1690 - height 1180
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-12T07:47:27.786Z',mode:absolute,to:'2018-10-12T07:53:27.786Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-12T07:47:27.786Z',mode:absolute,to:'2018-10-12T07:53:27.786Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
This is a published data error, see https://api.gbif.org/v1/dataset/24baf0da-60a9-4a13-99d7-a8c860c3cb30

Though that could mean it's an IPT problem.

**Comment by timrobertson100** [comment]
Well spotted @MattBlissett 
There are 2 issues.

1. The wrapping of the long ones (visual)
2. The data has e.g. http://orcid.org/http://orcid.org/0000-0002-2541-7932  (note the double http://orcid.org/http://orcid.org) which we need to identify the source (could be IPT issue or a data entry issue in IPT)

**Comment by MattBlissett** [comment]
For the second issue, the source is the IPT, which is older than the EML specification's guidance on user identifiers.

I have made an issue in the GBIF API, and also fixed it. It has the background on the EML standard: https://github.com/gbif/gbif-api/issues/30

I've also made an issue for the IPT: https://github.com/gbif/ipt/issues/1424

@rpfigueira, Tim and I will decide whether to deploy this small fix to production. We don't usually make production changes on a Friday, especially the Friday before the governing board meeting.

**Comment by MattBlissett** [comment]
We've decided not to deploy today, there are other changes in the way of a clean deployment.

@rpfigueira, if you'd like the user identifiers on the Azorean dataset to appear correctly, please write them like this in the IPT and republish:

![ipt-eml-orcid](https://user-images.githubusercontent.com/583320/46868017-34390a80-ce27-11e8-803f-c6c147f76ba8.png)

GBIF's processing concatenates the two parts.

**Comment by MortenHofft** [comment]
the loooong ids now wrap
