### ISSUE TITLE
Link Download not work

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1582]
**Link Download not work**

`https://www.gbif.org/occurrence/download?country=CO&taxon_key=2498599&taxon_key=5963031&taxon_key=2498644&taxon_key=2498587&taxon_key=2498665&taxon_key=2498688&taxon_key=2417441&taxon_key=2417443&taxon_key=2417334&taxon_key=5215470&taxon_key=5215455&taxon_key=2418421&taxon_key=2418435&taxon_key=5215607&taxon_key=5215608&taxon_key=2418535&taxon_key=2418677&taxon_key=2418680&taxon_key=5216352&taxon_key=5216338&taxon_key=5216423&taxon_key=5216430&taxon_key=2421062&taxon_key=2421057&taxon_key=2421042&taxon_key=2421056&taxon_key=2421053&taxon_key=2421076&taxon_key=2417699&taxon_key=2419818&taxon_key=2419820&taxon_key=2419844&taxon_key=2420132&taxon_key=2420220&taxon_key=2420162&taxon_key=2420227&taxon_key=2419946&taxon_key=2419929&taxon_key=2419777&taxon_key=2419858&taxon_key=5213262&taxon_key=5213261&taxon_key=2405472&taxon_key=2405474&taxon_key=2405532&taxon_key=2405509&taxon_key=2403044&taxon_key=2403985&taxon_key=2403798&taxon_key=2402876&taxon_key=2402829&taxon_key=2402821&taxon_key=2402842&taxon_key=2402855&taxon_key=5213135&taxon_key=5213207&taxon_key=2404425&taxon_key=2405385&taxon_key=5213060&taxon_key=2403733&taxon_key=2403686&taxon_key=2403103&taxon_key=2403372&taxon_key=2403366&taxon_key=2403395&taxon_key=2403363&taxon_key=2403456&taxon_key=2403075&taxon_key=2403477&taxon_key=2403113&taxon_key=2403429&taxon_key=2403438&taxon_key=2403469&taxon_key=2403467&taxon_key=2403470&taxon_key=2402941&taxon_key=2402953&taxon_key=2402939&taxon_key=2402913&taxon_key=5214458&taxon_key=5214459&taxon_key=5214449&taxon_key=2411210&taxon_key=2411158&taxon_key=2410468&taxon_key=2410945&taxon_key=5214394&taxon_key=5214339&taxon_key=2410772&taxon_key=5214331&taxon_key=2410645&taxon_key=5214370&taxon_key=2410800&taxon_key=2410813&taxon_key=2410638&taxon_key=5203360&taxon_key=2347408&taxon_key=2347412&taxon_key=2347617&taxon_key=2347579&taxon_key=2347501&taxon_key=2347522&taxon_key=2347529&taxon_key=2347517&taxon_key=2347610&taxon_key=2347557&taxon_key=2346808&taxon_key=2346825&taxon_key=2346789&taxon_key=2346791&taxon_key=5203191&taxon_key=5203189&taxon_key=2347024&taxon_key=5203203&taxon_key=2346933&taxon_key=5203238&taxon_key=5203296&taxon_key=2347368&taxon_key=2347378&taxon_key=2346861&taxon_key=2346880&taxon_key=5204677&taxon_key=2401157&taxon_key=2401136&taxon_key=2401149&taxon_key=2401401&taxon_key=2401380&taxon_key=2401051&taxon_key=2401367&taxon_key=2401351&taxon_key=2401343&taxon_key=2401348&taxon_key=2401360&taxon_key=2401329&taxon_key=2401542&taxon_key=2401629&taxon_key=2401650&taxon_key=5213280&taxon_key=9506888&taxon_key=2405792&taxon_key=2406184&taxon_key=2406248&taxon_key=2406218&taxon_key=2406303&taxon_key=2406331&taxon_key=9740143&taxon_key=2406262&taxon_key=2406297&taxon_key=2405913&taxon_key=2405710&taxon_key=2405852&taxon_key=2410398&taxon_key=2410396&taxon_key=7931988&taxon_key=2416415&taxon_key=2416425&taxon_key=2416416&taxon_key=2416752&taxon_key=2416296&taxon_key=2416355&taxon_key=5215165&taxon_key=5215286&taxon_key=2416787&taxon_key=2416785&taxon_key=2416781&taxon_key=5215121&taxon_key=5215125&taxon_key=5215127&taxon_key=2415950&taxon_key=5215092&taxon_key=5215097&taxon_key=2416866&taxon_key=2416969&taxon_key=2416899&taxon_key=2416823&taxon_key=2416007&taxon_key=2415999&taxon_key=2416989&taxon_key=2417024&taxon_key=2417083&taxon_key=5215412&taxon_key=2415661&taxon_key=2415690&taxon_key=2415747&taxon_key=2345878&taxon_key=2345691&taxon_key=2346002&taxon_key=2346047&taxon_key=2346007&taxon_key=2346011&taxon_key=2345601&taxon_key=8270562&taxon_key=8014169&taxon_key=2345620&taxon_key=2345616&taxon_key=8290057&taxon_key=2345596&taxon_key=8366288&taxon_key=2345578&taxon_key=2345975&taxon_key=2345714&taxon_key=2345724&taxon_key=2345759&taxon_key=2345708&taxon_key=2345585&taxon_key=2345630&taxon_key=2346190&taxon_key=2346315&taxon_key=2346091&taxon_key=2346269&taxon_key=2345533&taxon_key=2350812&taxon_key=2350824&taxon_key=2415025&taxon_key=2415043&taxon_key=2415026&taxon_key=2415076&taxon_key=2415205&taxon_key=2415215&taxon_key=2414913&taxon_key=2414912&taxon_key=2415008&taxon_key=5214837`

-----

User provided contact info: jmgamboac@unal.edu.co
System: Chrome 69.0.3497 / Windows 8.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e5e045980071e457e249c82234d737cc:b4856a2458041e79860641ed79e384b56138970c18629176bdc3179c9828664a1a5b5a25ebaf0fcca460e52ec8994ea952b7b54db0aaaf1056cf8cb853d3fa44)
Referer: https://www.gbif.org/occurrence/download?country=CO&taxon_key=2498599&taxon_key=5963031&taxon_key=2498644&taxon_key=2498587&taxon_key=2498665&taxon_key=2498688&taxon_key=2417441&taxon_key=2417443&taxon_key=2417334&taxon_key=5215470&taxon_key=5215455&taxon_key=2418421&taxon_key=2418435&taxon_key=5215607&taxon_key=5215608&taxon_key=2418535&taxon_key=2418677&taxon_key=2418680&taxon_key=5216352&taxon_key=5216338&taxon_key=5216423&taxon_key=5216430&taxon_key=2421062&taxon_key=2421057&taxon_key=2421042&taxon_key=2421056&taxon_key=2421053&taxon_key=2421076&taxon_key=2417699&taxon_key=2419818&taxon_key=2419820&taxon_key=2419844&taxon_key=2420132&taxon_key=2420220&taxon_key=2420162&taxon_key=2420227&taxon_key=2419946&taxon_key=2419929&taxon_key=2419777&taxon_key=2419858&taxon_key=5213262&taxon_key=5213261&taxon_key=2405472&taxon_key=2405474&taxon_key=2405532&taxon_key=2405509&taxon_key=2403044&taxon_key=2403985&taxon_key=2403798&taxon_key=2402876&taxon_key=2402829&taxon_key=2402821&taxon_key=2402842&taxon_key=2402855&taxon_key=5213135&taxon_key=5213207&taxon_key=2404425&taxon_key=2405385&taxon_key=5213060&taxon_key=2403733&taxon_key=2403686&taxon_key=2403103&taxon_key=2403372&taxon_key=2403366&taxon_key=2403395&taxon_key=2403363&taxon_key=2403456&taxon_key=2403075&taxon_key=2403477&taxon_key=2403113&taxon_key=2403429&taxon_key=2403438&taxon_key=2403469&taxon_key=2403467&taxon_key=2403470&taxon_key=2402941&taxon_key=2402953&taxon_key=2402939&taxon_key=2402913&taxon_key=5214458&taxon_key=5214459&taxon_key=5214449&taxon_key=2411210&taxon_key=2411158&taxon_key=2410468&taxon_key=2410945&taxon_key=5214394&taxon_key=5214339&taxon_key=2410772&taxon_key=5214331&taxon_key=2410645&taxon_key=5214370&taxon_key=2410800&taxon_key=2410813&taxon_key=2410638&taxon_key=5203360&taxon_key=2347408&taxon_key=2347412&taxon_key=2347617&taxon_key=2347579&taxon_key=2347501&taxon_key=2347522&taxon_key=2347529&taxon_key=2347517&taxon_key=2347610&taxon_key=2347557&taxon_key=2346808&taxon_key=2346825&taxon_key=2346789&taxon_key=2346791&taxon_key=5203191&taxon_key=5203189&taxon_key=2347024&taxon_key=5203203&taxon_key=2346933&taxon_key=5203238&taxon_key=5203296&taxon_key=2347368&taxon_key=2347378&taxon_key=2346861&taxon_key=2346880&taxon_key=5204677&taxon_key=2401157&taxon_key=2401136&taxon_key=2401149&taxon_key=2401401&taxon_key=2401380&taxon_key=2401051&taxon_key=2401367&taxon_key=2401351&taxon_key=2401343&taxon_key=2401348&taxon_key=2401360&taxon_key=2401329&taxon_key=2401542&taxon_key=2401629&taxon_key=2401650&taxon_key=5213280&taxon_key=9506888&taxon_key=2405792&taxon_key=2406184&taxon_key=2406248&taxon_key=2406218&taxon_key=2406303&taxon_key=2406331&taxon_key=9740143&taxon_key=2406262&taxon_key=2406297&taxon_key=2405913&taxon_key=2405710&taxon_key=2405852&taxon_key=2410398&taxon_key=2410396&taxon_key=7931988&taxon_key=2416415&taxon_key=2416425&taxon_key=2416416&taxon_key=2416752&taxon_key=2416296&taxon_key=2416355&taxon_key=5215165&taxon_key=5215286&taxon_key=2416787&taxon_key=2416785&taxon_key=2416781&taxon_key=5215121&taxon_key=5215125&taxon_key=5215127&taxon_key=2415950&taxon_key=5215092&taxon_key=5215097&taxon_key=2416866&taxon_key=2416969&taxon_key=2416899&taxon_key=2416823&taxon_key=2416007&taxon_key=2415999&taxon_key=2416989&taxon_key=2417024&taxon_key=2417083&taxon_key=5215412&taxon_key=2415661&taxon_key=2415690&taxon_key=2415747&taxon_key=2345878&taxon_key=2345691&taxon_key=2346002&taxon_key=2346047&taxon_key=2346007&taxon_key=2346011&taxon_key=2345601&taxon_key=8270562&taxon_key=8014169&taxon_key=2345620&taxon_key=2345616&taxon_key=8290057&taxon_key=2345596&taxon_key=8366288&taxon_key=2345578&taxon_key=2345975&taxon_key=2345714&taxon_key=2345724&taxon_key=2345759&taxon_key=2345708&taxon_key=2345585&taxon_key=2345630&taxon_key=2346190&taxon_key=2346315&taxon_key=2346091&taxon_key=2346269&taxon_key=2345533&taxon_key=2350812&taxon_key=2350824&taxon_key=2415025&taxon_key=2415043&taxon_key=2415026&taxon_key=2415076&taxon_key=2415205&taxon_key=2415215&taxon_key=2414913&taxon_key=2414912&taxon_key=2415008&taxon_key=5214837
Window size: width 1280 - height 882
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-12T16:37:11.476Z',mode:absolute,to:'2018-10-12T16:43:11.476Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-12T16:37:11.476Z',mode:absolute,to:'2018-10-12T16:43:11.476Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I believe we have seen this in the past for very long queries with hundreds of taxonKeys. Server responds with  "422 - Unprocessable Entity".

**Comment by MattBlissett** [comment]
Duplicate of https://github.com/gbif/occurrence/issues/50

**Comment by MattBlissett** [comment]
Closing as a duplicate of https://github.com/gbif/portal-feedback/issues/1586
