### ISSUE TITLE
Species identification and coordinates wrong for UMMZ 103548

### ISSUE THREAD

**Issue by VicVC** [gbif/portal-feedback#1583]
The information for UMMZ 103548 mentions "_Miniopterus schreibersii natalensis_" as taxon name, but _natalensis_ has been considered a separate species for quite some time (e.g. Simmons, 2005: 521).

The locality, where this specimen was collected is Wonderboom (cave) and is located near Pretoria in the former Transvaal (currently Gauteng) province of South Africa.  Its coordinates are 25 48 S 29 53 E, but the decimal latitude on the record mentions -30.78333, which situates the locality in the Eastern Cape province.

Best Regards,

Victor Van Cakenberghe

Simmons, N.B. (2005).  Order Chiroptera.  In: Wilson, D. E.; Reeder, D. M. [Eds]; Mammal Species of the World: A taxonomic and geographic reference. - The John Hopkins University Press - Baltimore.

**Comment by ManonGros** [comment]
This comments seems to concern this occurrence: https://www.gbif.org/occurrence/783994141

**Comment by ManonGros** [comment]
The publishers have been contacted.
