### ISSUE TITLE
Species identification for UMMZ 115813 to 115819

### ISSUE THREAD

**Issue by VicVC** [gbif/portal-feedback#1584]
Records UMMZ 115813 to 115819 are in the database identified as belonging to _Mormopterus acetabulosus_.  However, these specimens are paratypes of _Mormopterus francoismoutoui_ Goodman et al., 2008 (see page 1319).

Best regards,

Victor Van Cakenberghe

Goodman, S. M.; Jansen van Vuuren, B.; Ratrimomanarivo, F.; Probst, J.-M.; Bowie, R. C. K. (2008).  pecific status of populations in the Mascarene Islands referred to _Mormopterus acetabulosus_ (Chiroptera: Molossidae), with description of a new species. - Journal of Mammalogy, 89 (5): 1316 - 1327.

**Comment by ManonGros** [comment]
The occurrences concerned seem to be [these](https://www.gbif.org/occurrence/search?dataset_key=6d2cfc0a-9903-40b8-802b-403398218e4a&taxon_key=2433052).

**Comment by ManonGros** [comment]
The publishers have been contacted.
