### ISSUE TITLE
Generic assignment and province/county information of UMMZ 59011 to 59013

### ISSUE THREAD

**Issue by VicVC** [gbif/portal-feedback#1585]
UMMZ 59011 to 59013 are entered as "Eptesicus capensis" in the database, but the taxon has been assigned to the genus Neoromicia (see Simmons, 2005: 493).

The locality Grahamstown (with correct coordinates mentioned [33 18 S 26 32 E - 26.5333,-33.3]) is not located in the City of Cape Town county of the Western Cape province, but in the Cacadu district of the Eastern Cape province.

Additionally, "Eptesicus capensis" will need to be modified for quite a amount of records from various museums.

Regards,

Victor Van Cakenberghe

Simmons, N. B. (2005).  Order Chiroptera.  In: Wilson, D. E.; Reeder, D. M. [Eds]: Mammal Species of the World: A taxonomic and geographic reference. - The John Hopkins University Press - Baltimore.

**Comment by ManonGros** [comment]
The occurrence concerned seem to be [these](https://www.gbif.org/occurrence/search?dataset_key=6d2cfc0a-9903-40b8-802b-403398218e4a&taxon_key=2432348).

**Comment by ManonGros** [comment]
The publishers have been contacted.
