### ISSUE TITLE
The system is currently not able to process your request. Try to refresh the page and please report the issue if it continues.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1586]
**The system is currently not able to process your request. Try to refresh the page and please report the issue if it continues.**

The system is currently not able to process your request. Try to refresh the page and please report the issue if it continues.

-----

System: Chrome 69.0.3497 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b7f93cef6081f49d9a88d69d855b65de:211a445eb31744eaa7528510b82eb748694b67f5f3020d84fab5bf069d17a2b9835c6b5e92c70d846b19a14fad1f63116e53097bac4561b64dd07e18b6ea3c65)
Referer: https://www.gbif.org/occurrence/download?issue=COORDINATE_ROUNDED&issue=GEODETIC_DATUM_ASSUMED_WGS84&issue=COORDINATE_REPROJECTED&issue=COORDINATE_REPROJECTION_FAILED&issue=COORDINATE_REPROJECTION_SUSPICIOUS&issue=COORDINATE_ACCURACY_INVALID&issue=COORDINATE_PRECISION_INVALID&issue=COORDINATE_UNCERTAINTY_METERS_INVALID&issue=COORDINATE_PRECISION_UNCERTAINTY_MISMATCH&issue=COUNTRY_COORDINATE_MISMATCH&issue=CONTINENT_COUNTRY_MISMATCH&issue=CONTINENT_INVALID&issue=CONTINENT_DERIVED_FROM_COORDINATES&issue=PRESUMED_SWAPPED_COORDINATE&issue=PRESUMED_NEGATED_LONGITUDE&issue=PRESUMED_NEGATED_LATITUDE&issue=RECORDED_DATE_MISMATCH&issue=RECORDED_DATE_INVALID&issue=RECORDED_DATE_UNLIKELY&issue=TAXON_MATCH_FUZZY&issue=TAXON_MATCH_HIGHERRANK&issue=TAXON_MATCH_NONE&issue=DEPTH_NOT_METRIC&issue=DEPTH_UNLIKELY&issue=DEPTH_MIN_MAX_SWAPPED&issue=DEPTH_NON_NUMERIC&issue=ELEVATION_UNLIKELY&issue=ELEVATION_MIN_MAX_SWAPPED&issue=ELEVATION_NOT_METRIC&issue=ELEVATION_NON_NUMERIC&issue=MODIFIED_DATE_INVALID&issue=MODIFIED_DATE_UNLIKELY&issue=IDENTIFIED_DATE_UNLIKELY&issue=IDENTIFIED_DATE_INVALID&issue=BASIS_OF_RECORD_INVALID&issue=TYPE_STATUS_INVALID&issue=MULTIMEDIA_DATE_INVALID&issue=MULTIMEDIA_URI_INVALID&issue=REFERENCES_URI_INVALID&issue=INTERPRETATION_ERROR&issue=INDIVIDUAL_COUNT_INVALID&taxon_key=5384394&taxon_key=5384385&taxon_key=5384362&taxon_key=5384334&taxon_key=5548357&taxon_key=5384347&taxon_key=5548377&taxon_key=5384335&taxon_key=5384397&taxon_key=5384345&taxon_key=5384331&taxon_key=5384383&taxon_key=8404472&taxon_key=8016021&taxon_key=5548392&taxon_key=7865636&taxon_key=5548401&taxon_key=5384401&taxon_key=6710339&taxon_key=5384370&taxon_key=5548431&taxon_key=5548556&taxon_key=7323685&taxon_key=6109534&taxon_key=7323711&taxon_key=5384399&taxon_key=5548701&taxon_key=6429862&taxon_key=5548528&taxon_key=5384359&taxon_key=5384342&taxon_key=5548711&taxon_key=6710340&taxon_key=5384398&taxon_key=5384393&taxon_key=5384403&taxon_key=5384384&taxon_key=5384332&taxon_key=5384381&taxon_key=5547857&taxon_key=5384361&taxon_key=7323833&taxon_key=5384363&taxon_key=5384343&taxon_key=5384379&taxon_key=5547814&taxon_key=5547836&taxon_key=8394433&taxon_key=9080185&taxon_key=5547885&taxon_key=7561220&taxon_key=5384366&taxon_key=5384365&taxon_key=5384364&taxon_key=5384356&taxon_key=5547907&taxon_key=7826322&taxon_key=5384358&taxon_key=7219439&taxon_key=6875172&taxon_key=8044752&taxon_key=5384373&taxon_key=6710342&taxon_key=6710343&taxon_key=5548420&taxon_key=7410691&taxon_key=5384371&taxon_key=5384386&taxon_key=6875173&taxon_key=5384391&taxon_key=7695818&taxon_key=5384367&taxon_key=5384400&taxon_key=5384396&taxon_key=5384390&taxon_key=8185601&taxon_key=5384404&taxon_key=5548708&taxon_key=5384369&taxon_key=5384377&taxon_key=5547995&taxon_key=5547959&taxon_key=5547997&taxon_key=6710346&taxon_key=6710347&taxon_key=6109611&taxon_key=5548003&taxon_key=5384402&taxon_key=5384387&taxon_key=6710348&taxon_key=5384352&taxon_key=5548030&taxon_key=5548740&taxon_key=5547956&taxon_key=5548033&taxon_key=5547862&taxon_key=5384337&taxon_key=7323358&taxon_key=8911082&taxon_key=5384395&taxon_key=8093363&taxon_key=8145130&taxon_key=5384328&taxon_key=7323395&taxon_key=5384340&taxon_key=5384355&taxon_key=5548023&taxon_key=7905507&taxon_key=5384333&taxon_key=5384353&taxon_key=5548646&taxon_key=5548035
Window size: width 1035 - height 872
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-16T00:28:05.321Z',mode:absolute,to:'2018-10-16T00:34:05.321Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-16T00:28:05.321Z',mode:absolute,to:'2018-10-16T00:34:05.321Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The API responds with "request payload too large". Users are now informed more explicitly when the API response as such https://github.com/gbif/portal16/commit/628d41e27d44883da04af4af327b029f56ae8b04

How is the maximum size determined? characterLength? values?

**Comment by MattBlissett** [comment]
The maximum was 8192, including the format and notification address etc. I'm raising that to 1Mi, but there are limits in several places.

Closing in favour of https://github.com/gbif/occurrence/issues/50 and https://github.com/gbif/occurrence/issues/49.
