### ISSUE TITLE
WKT: Geometry too large

### ISSUE THREAD

**Issue by andzandz11** [gbif/portal-feedback#1588]
POLYGON((-25.590097833814866 67.36797082284382,-23.480722833814866 57.55501079675304,-11.85922931251639 48.116253070770014,-11.06821368751639 35.040814947897346,-5.220871503275703 36.05238722988097,0.08727518296961989 36.58181270233538,5.97594705796962 38.360417130163334,11.05163065171962 38.05287470688104,13.77624002671962 34.818790573829695,22.763056432969734 35.42981790410236,26.81837588418648 33.7522254701255,28.42237979043648 35.577383711587494,25.28028994668648 38.488444221666114,25.70026621683712 40.45124141982378,28.51276621683712 40.65158509436986,30.73200449808712 42.50866300168705,39.76276621683712 43.2992920488477,44.89185851767354 39.72449310268457,49.13258117392354 39.09637112224509,51.41773742392354 40.564294085922,48.38551086142354 44.73149923735219,40.10283463479777 47.34870300639049,36.292667676220844 50.71054843943353,31.77937571764403 52.155217662615115,32.92337545981809 53.4815090410304,31.012465174655176 55.7820636839676,28.486320514492263 56.33345478227602,27.706279014929237 57.720536826674056,27.98092501536621 59.59446999025547,31.85826020121965 62.8213741809747,29.638111279941654 67.14143405854475,30.830287253312918 69.7045846902049,32.55699159505423 72.19683235329389,-4.778271869380319 72.46719834933275,-25.590097833814866 67.36797082284382))

I tried to add this polygon to a query but it gave the error: Geometry too large
Unfortunately I don't know what the appropriate size would be? Is is just the number of nodes or the total characters that is too large? Is there some way to work around that? I think it would be helpful to give the error message a mouse-over explanation or something. "geometry too large" points me to the area size being too large, but this can hardly be the case? Shouldn't it rather be "query too long" or: "geometry too many nodes" ?

Best wishes

**Comment by MortenHofft** [comment]
It would be nice to know the exact number yes. Labelling this as an API question.

As for the interfce you might have noticed that it [suggests a simplification of the polygon](https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON%20((-25.590097833814866%2067.36797082284382,%20-23.480722833814866%2057.55501079675304,%20-11.85922931251639%2048.116253070770014,%20-11.06821368751639%2035.040814947897346,%205.97594705796962%2038.360417130163334,%2011.05163065171962%2038.05287470688104,%2013.77624002671962%2034.818790573829695,%2022.763056432969734%2035.42981790410236,%2026.81837588418648%2033.7522254701255,%2028.42237979043648%2035.577383711587494,%2025.28028994668648%2038.488444221666114,%2025.70026621683712%2040.45124141982378,%2030.73200449808712%2042.50866300168705,%2039.76276621683712%2043.2992920488477,%2044.89185851767354%2039.72449310268457,%2049.13258117392354%2039.09637112224509,%2051.41773742392354%2040.564294085922,%2048.38551086142354%2044.73149923735219,%2031.77937571764403%2052.155217662615115,%2032.92337545981809%2053.4815090410304,%2028.486320514492263%2056.33345478227602,%2027.98092501536621%2059.59446999025547,%2031.85826020121965%2062.8213741809747,%2029.638111279941654%2067.14143405854475,%2032.55699159505423%2072.19683235329389,%20-4.778271869380319%2072.46719834933275,%20-25.590097833814866%2067.36797082284382))) for you.

**Comment by MattBlissett** [comment]
Having [removed the default limit the occurrence-ws was stuck with](https://github.com/gbif/gbif-microservice/commit/a3098c38a78050d3233671c3a8e31f918f335823) and set it to 1MiB, we now hit a similar default limit on the SOLR servers:

```
Server Error</pre></p><h3>Caused by:</h3><pre>org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://c3n2.gbif.org:8983/solr/occurrence: non ok status: 414, message:Request-URI Too Long
        at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:508)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
        at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
        at org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:372)
        at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:325)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1100)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:871)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:807)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:150)
        at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:943)
        at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:958)
        at org.gbif.occurrence.search.OccurrenceSearchImpl.search(OccurrenceSearchImpl.java:141)
```

I've added `-Dsolr.jetty.request.header.size=1048576` to the SOLR startup options.

Now a query like [Brandenburg](https://api.gbif-uat.org/v1/occurrence/search?has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON%20((11.25854265728037%2053.11491175055851,%2011.26638372847722%2053.13203955670105,%2011.38487071308462%2053.12136407466974,%2011.39527607155671%2053.14999406081887,%2011.52921260239704%2053.13575982615944,%2011.55564959135974%2053.16826657360428,%2011.54657534859031%2053.21735099654164,%2011.62837524384679%2053.25195288430336,%2011.70121986963965%2053.25411550408752,%2011.73687867033906%2053.2281330937903,%2011.80145319035703%2053.23687283189753,%2011.79156580093446%2053.26256173095874,%2011.85680921844465%2053.25885795716984,%2011.88954058255834%2053.28836834728915,%2011.94760709393196%2053.28401566785716,%2011.97037134134446%2053.30853199911103,%2012.01005037788366%2053.30999991253976,%2012.00527941866106%2053.33801863926615,%2012.03959267414954%2053.35554463130263,%2012.04265661641253%2053.38063605298522,%2012.08011103296896%2053.37871211913809,%2012.0898150053548%2053.35591804958229,%2012.15311616388042%2053.37113114581379,%2012.1714551751884%2053.34988840592636,%2012.23162388499933%2053.36791810357917,%2012.26675622858292%2053.33471480029011,%2012.39780599892912%2053.31115090252921,%2012.44841113717391%2053.26126132142867,%2012.52893572185611%2053.27475359848759,%2012.60512308475863%2053.25541370210447,%2012.6676726193274%2053.26377682295425,%2012.68049189735234%2053.23783127682987,%2012.7620056384328%2053.23320293650411,%2012.76901236726571%2053.19848733198844,%2012.84567952775551%2053.21139766229843,%2012.87974610539405%2053.19026054766198,%2012.97894478945735%2053.20755310621107,%2012.98973482053765%2053.19136932799051,%2012.97840370856512%2053.17473506519134,%2013.14835059522571%2053.26042885223058,%2013.18435927371027%2053.2611334662925,%2013.22542936260945%2053.22754911292704,%2013.24709265789315%2053.27057573269199,%2013.29610379066698%2053.29074728844677,%2013.36310231477903%2053.28764094541584,%2013.39510062391971%2053.25572504370669,%2013.43197261782117%2053.30779880350784,%2013.48641552846985%2053.30636963859055,%2013.51757547204646%2053.37166026376046,%2013.54044367830052%2053.37900021458339,%2013.54403090869061%2053.40701965013158,%2013.6217870332613%2053.42197311957374,%2013.63283692050357%2053.45372382687967,%2013.71190778390259%2053.49140207767058,%2013.79911017079731%2053.48861413670063,%2013.76825655816997%2053.5128331380925,%2013.77090126361977%2053.54691097607884,%2013.79113400574081%2053.56842903041675,%2013.83126757185767%2053.52699413390713,%2013.88743078862469%2053.50991673529157,%2013.89145781623936%2053.47743125463074,%2013.92733236568064%2053.46010273409787,%2013.92151288913686%2053.43487017707542,%2014.00423011377053%2053.44476356700941,%2014.04874481865545%2053.43891942270341,%2014.05817069245327%2053.42275207676257,%2014.12056494666889%2053.45179512411173,%2014.17924159187166%2053.43257982485688,%2014.22862734853769%2053.44342791973099,%2014.25138211129271%2053.42439246743559,%2014.23915348239764%2053.36222138798026,%2014.11313059780577%2053.27126554474551,%2014.25465897219294%2053.26781162905876,%2014.25599757896834%2053.28465048953375,%2014.29307093271859%2053.29414443518812,%2014.31428627641505%2053.32188957050631,%2014.40752197207057%2053.34014903803826,%2014.42505730255412%2053.32693461240422,%2014.42859961989258%2053.28598947318384,%2014.45161251407164%2053.28219896212935,%2014.46036989156879%2053.26049477166259,%2014.41231580793051%2053.20315409002681,%2014.38625687737622%2053.19484287709425,%2014.37719160588718%2053.17156347504997,%2014.39696442136125%2053.13984132713468,%2014.35540082282168%2053.04745773142378,%2014.26277347094714%2052.99375889655189,%2014.1522800286649%2052.95397324717688,%2014.17135627167595%2052.88598861298929,%2014.13320423053513%2052.83991056154129,%2014.22030949500422%2052.82645894057478,%2014.2831683827408%2052.78346177139262,%2014.35590413672387%2052.76022081987355,%2014.47022684885436%2052.66991723132143,%2014.60095924617232%2052.61940203979879,%2014.64847296105551%2052.57647351888407,%2014.61456018806252%2052.53131636776389,%2014.64281393717922%2052.4867562495207,%2014.58548145227539%2052.43397718364022,%2014.55610724641453%2052.42608705782115,%2014.54517972147799%2052.39686098216953,%2014.599342932708%2052.28252153477464,%2014.69358705364845%2052.26605652839145,%2014.72436333320266%2052.24086009161331,%2014.70041973752616%2052.19364143030137,%2014.71514845219598%2052.16692748221372,%2014.68952843893885%2052.1411976489394,%2014.69214611281299%2052.11731416668288,%2014.74790986181173%2052.09268297882935,%2014.76898845925812%2052.06429845911677,%2014.71693157730571%2051.97115074860154,%2014.73114349199058%2051.94976286133161,%2014.70363550422481%2051.89823043912106,%2014.60197621061171%2051.82609365046714,%2014.65232125627689%2051.80270766910189,%2014.6748511883091%2051.73419830557349,%2014.75477049109777%2051.6822306785176,%2014.77447285762891%2051.60426235074966,%2014.67773420802567%2051.54161106973014,%2014.60623956781624%2051.5408386851428,%2014.57245925716719%2051.57096095895567,%2014.51861798231697%2051.54474866713531,%2014.39632319818828%2051.53178501174582,%2014.33760845376458%2051.49592421040121,%2014.27136853401893%2051.5226015228089,%2014.14705410007347%2051.53168339316244,%2014.14911117203567%2051.51542803457205,%2014.11181529099139%2051.51169254618713,%2014.09704950711962%2051.47196036402601,%2014.06588414853139%2051.46325187208815,%2014.07063600215502%2051.43984716225143,%2014.0033036951775%2051.36312302822699,%2013.965237013218%2051.36684901242399,%2013.95513338470319%2051.38694039739568,%2013.76442514041791%2051.34908933624506,%2013.59294780635238%2051.35941860242883,%2013.57203835565295%2051.37532751161467,%2013.54384854596004%2051.35933530084678,%2013.51196807333029%2051.39206671498565,%2013.4160146188706%2051.41340690508947,%2013.39814037371195%2051.43937613880392,%2013.38727107252998%2051.41713514908003,%2013.31870636422088%2051.41352652403054,%2013.27153682178368%2051.37525183378488,%2013.21127732883251%2051.38671045724829,%2013.19193174202195%2051.41635556117384,%2013.16490218783395%2051.42486647068171,%2013.1907376603324%2051.4534038531852,%2013.17250442030749%2051.4939874441741,%2013.19735209591602%2051.51289261102476,%2013.1776981812418%2051.54740045507838,%2013.14125882983543%2051.55507507398312,%2013.13106894384395%2051.5712238890483,%2013.14417942612958%2051.58801457926606,%2013.1186462914785%2051.60582498083524,%2013.08209417067695%2051.59931229150178,%2013.0410745563791%2051.64668530916979,%2013.14594276249134%2051.69437521872189,%2013.16192931305175%2051.72688843301259,%2013.13750821793755%2051.76591252760955,%2013.15032768151955%2051.80323018185096,%2013.11740284619548%2051.84208303860154,%2013.11716857275175%2051.86568892521964,%2013.0386796410286%2051.86103502536751,%2013.01173166113092%2051.89214761856015,%2012.96705955594111%2051.89259979614214,%2012.94640144637937%2051.92545525302705,%2012.8474848688755%2051.92627400836851,%2012.83704126319026%2051.95732293030117,%2012.77524591680534%2051.95487508332404,%2012.66597139616331%2052.00288418462027,%2012.60204359386455%2051.97113441668139,%2012.53593669065299%2051.97506499821663,%2012.52775437042853%2051.99434179176956,%2012.49369124339639%2052.00034215879653,%2012.47106417975244%2052.02426910820609,%2012.45026508444588%2052.00655266131072,%2012.42630113938697%2052.00893636855,%2012.27007099679146%2052.09655247726908,%2012.2081636652913%2052.16499861798791,%2012.25635897549393%2052.22554515937305,%2012.2347110471213%2052.24577651269692,%2012.24161897409404%2052.27566505618507,%2012.29245442206532%2052.34244195515059,%2012.27313645552596%2052.3628801294654,%2012.28732206560892%2052.39824081421386,%2012.26464726653838%2052.41809643738567,%2012.30851056321149%2052.46804109964427,%2012.29900419279784%2052.48362244697955,%2012.2661529026491%2052.4791794154069,%2012.24039162514308%2052.51121118898265,%2012.22562389028941%2052.49146960578033,%2012.18151200282261%2052.4865747146923,%2012.15988562133136%2052.52102064467046,%2012.13242398844347%2052.52661766132488,%2012.16471670211232%2052.57652410656204,%2012.16480397617845%2052.63290495953152,%2012.19885369083356%2052.62911376685443,%2012.22425105478054%2052.64708741349767,%2012.22742670201212%2052.67108927329845,%2012.18768435427137%2052.71738827937303,%2012.21164224948809%2052.79534027427047,%2012.24264943013411%2052.80508839552181,%2012.2217566731585%2052.85104220874167,%2012.19268280049651%2052.86401266978264,%2012.1229337831927%2052.84304556016453,%2012.11519009363793%2052.8663861556665,%2012.05877375508107%2052.87781942819197,%2011.97930682099662%2052.86618472496218,%2011.83151019531236%2052.90067538936401,%2011.81278897169368%2052.92221875108716,%2011.83620113776851%2052.94529909245931,%2011.78262928646715%2052.95165787915768,%2011.74132742190946%2052.97884566342584,%2011.68649988649272%2052.96985252282717,%2011.67334746783703%2052.99882553385521,%2011.62053461927959%2053.00428820806177,%2011.62324060405166%2053.03176059922742,%2011.5077196401616%2053.03775340521454,%2011.4477553810229%2053.06839773840417,%2011.33772553648372%2053.04506900666239,%2011.26637397455913%2053.08987309816927,%2011.25854265728037%2053.11491175055851),%20(13.13330930706823%2051.86833828784586,%2013.12694380308093%2051.8714107954864,%2013.12282447242357%2051.86793591295719,%2013.12312031697371%2051.86799115957792,%2013.13330930706823%2051.86833828784586),%20(12.1640715253774%2052.52483503735899,%2012.16464200356727%2052.52524324047167,%2012.16424084866621%2052.52516362436468,%2012.1640715253774%2052.52483503735899),%20(13.12251143834082%2052.41072272439865,%2013.24555587765305%2052.4307982315551,%2013.26803789654122%2052.41452272194669,%2013.34619028172921%2052.42117749205606,%2013.41580439361674%2052.38645794227364,%2013.41146976327115%2052.4167487553015,%2013.46426597690298%2052.43043358530691,%2013.48648446404981%2052.40752027468212,%2013.59292599324103%2052.40416834513871,%2013.64523701118899%2052.38721407213132,%2013.65679947923392%2052.36493578510132,%2013.72220127929877%2052.40909263366724,%2013.73024661013196%2052.44027112696154,%2013.64645239635413%2052.46888496264425,%2013.60394510292076%2052.46409572337138,%2013.62764495123774%2052.5202784735832,%2013.58072464815266%2052.53962509706825,%2013.55128560834776%2052.57516925907364,%2013.50232496733886%2052.58405756424838,%2013.48675253658828%2052.60502260450626,%2013.50150565514057%2052.63998921122315,%2013.48208839123152%2052.64890312035116,%2013.42579851341533%2052.62573371459286,%2013.39920926731856%2052.63562969970153,%2013.33584940051898%2052.61269102352433,%2013.29708573926235%2052.61910377621491,%2013.29296189638495%2052.64675547543112,%2013.2687243225862%2052.61797246336334,%2013.22724922398743%2052.61767750737501,%2013.22227294669617%2052.57875898798552,%2013.15912667372968%2052.58707714827385,%2013.15633707291664%2052.55079410020979,%2013.12944598567942%2052.52798507698476,%2013.17644632031146%2052.50964932962919,%2013.12179317501179%2052.46268987543668,%2013.13316184260355%2052.43990657267035,%2013.12251143834082%2052.41072272439865))) is successful, however the map tile server fails, and there are some caveats on security and reliability of long HTTP requests to consider before putting this into production.

We might need to [think of some other way](https://github.com/gbif/gbif-api/issues/35).

There are some example polygons for German states here: https://mapproxy.org/static/polygons/germany/

@andzandz11, an option for you (and an alternative idea for the website, @MortenHofft) is to simplify by truncating the decimals. 6-7 decimal places is on the order of 10-1cm, so is less disruptive than removing points. The current limit is 8192 bytes for the whole request (`GET /v1/occurrence... HTTP/1.1`).

**Comment by MattBlissett** [comment]
As of now, the limit is 10,000 points -- through the API.

The website has different limits, due to URL lengths.

@MortenHofft, I will leave this issue open to handle any portal changes needed.

**Comment by MortenHofft** [comment]
Based on our conversation in real life, I understand that this is really only a download API change, so the website will remain the same. If the SOLR API is changed to accept larger queries, then let me know and I will up the accepted limit in the interface.
