### ISSUE TITLE
Contact information for Acadia University

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1589]
**Contact information for Acadia University**

The administrative and technical contacts need to be changed for this publisher.
Allison Walker is the new administrative contact (allison.walker[at]acadiau.ca ), and Alain Belliveau is the new technical contact (alain.belliveau[at]acadiau.ca ).

Thanks to change it on every pages related to this publisher. It has been changed on our IPT (Canadensys) for the corresponding ressources.

-----

User provided contact info: carole.sinou@gmail.com
System: Chrome 69.0.3497 / Mac OS X 10.12.6
User: [See in registry](https://www.gbif.org/api/feedback/user/fc04a9d941e838947d5d2178e5e22eaf:8a41664cc983bef8a144934baaf553d2395e42cba6cb24f8f2f028e8a143a800dd0e72b12b93ed297ab085729031af6ec9f21f0bb13ed88f1129f7301f1dbd16)
Referer: https://www.gbif.org/publisher/6491ad8c-8e49-4bd4-a089-0ddb3bbe0890
Window size: width 1280 - height 663
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-19T20:47:01.976Z',mode:absolute,to:'2018-10-19T20:53:01.976Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-19T20:47:01.976Z',mode:absolute,to:'2018-10-19T20:53:01.976Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The organisation has been updated with the new contacts.
