### ISSUE TITLE
how to download data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#159]
**how to download data**

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f

System: Chrome 56.0.2924 / Mac OS X 10.10.5
Referer: https://demo.gbif.org/search?q=Cecropia
Window size: width 1284 - height 676
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-31T15:34:05.015Z',mode:absolute,to:'2017-03-31T15:40:05.015Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-31T15:34:05.015Z',mode:absolute,to:'2017-03-31T15:40:05.015Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
you need to select if you are interested in occurrences and the species or the dataset matches.
in your case you can download here: https://demo.gbif.org/occurrence/download?taxon_key=2984472

![screen shot 2017-04-04 at 10 19 38](https://cloud.githubusercontent.com/assets/6759267/24647463/48999d36-1920-11e7-87b9-365df322c233.png)

hope that helps.
