### ISSUE TITLE
Country name East Timor or Timor-Leste?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1590]
**Country name East Timor or Timor-Leste?**

When validating a new dataset with the GBIF validator we found an inconsistency for the country name of what is officially known as the Democratic Republic of Timor-Leste

Based on coordinates and in the absence of a country name the validator suggested East Timor. However for other records when the country name East Timor is filled in,  a warning is given  that this is an invalid country name.

In ISO-3611 for country code TL is Timor Leste given, which would be correct the Invalid country warning. But it is not correct for the suggested country name. 

Example in: `https://www.gbif.org/tools/data-validator/1539079444067#Occurrence.txt-Issues`

-----

System: Chrome 69.0.3497 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7b88d35949e566fafe70170f2e2b76a5:17649224e9c4ad5d2252526a42d3c47e4895faf75c0d597d741e2b8fc5f4dbaef0edcd528049df080bd45a89ec56c69070b45988412ef058d65cb4cc03506638)
Referer: https://www.gbif.org/user/profile
Window size: width 2387 - height 1172
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-22T10:15:35.466Z',mode:absolute,to:'2018-10-22T10:21:35.466Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-22T10:15:35.466Z',mode:absolute,to:'2018-10-22T10:21:35.466Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by MattBlissett** [comment]
Hi @jeroencreuwels,

The validator isn't showing recommendations, it is showing your data with the issues GBIF's occurrence processing would add.

We do follow ISO-3611, and display the ISO "short name" in English, in this case ["Timor-Leste"](https://www.gbif.org/country/TL/summary).

However, we also accept many variations with spelling, language and form, and since "East Timor" is unambiguous it should be accepted. I'll update our parsing dictionary with new entries. You can then use whichever you prefer; we will show "Timor-Leste".

**Comment by tucotuco** [comment]
Using the search interface as the reference, GBIF doesn't strictly follow
the names in the ISO English short name for countries (as given in
Wikipedia. I'm not willing to spend the 38 Swiss Francs to find out the
definitive list, especially given that ISO states "The purpose of ISO 3166
is to define internationally recognised codes of letters and/or numbers
that we can use when we refer to countries and subdivisions. However, it
does not define the names of countries – this information comes from United
Nations sources (Terminology Bulletin Country Names and the Country and
Region Codes for Statistical Use maintained by the United Nations
Statistics Divisions)." Furthermore, ISO is somewhat out of date (last
version in 2013).

In any case, these are currently exceptions to GBIF matching ISO as given
by Wikipedia:

Bolivia, Plurinational State of Bolivia (Plurinational State of)
Congo, The Democratic Republic of the Congo (Democratic Republic of the)
Micronesia, Federated States of Micronesia (Federated States of)
United Kingdom United Kingdom of Great Britain and Northern Ireland
Iran, Islamic Republic of Iran (Islamic Republic of)
Democratic People's Republic of Korea Korea (Democratic People's Republic
of)
Korea, Republic of Korea (Republic of)
Kosovo [not in ISO3166]
Moldova, Republic of Moldova (Republic of)
Macedonia, The Former Yugoslav Republic of Macedonia (the former Yugoslav
Republic of)
Palestine, State of Palestine (State of)
Taiwan Taiwan, Province of China
Tanzania, United Republic of Tanzania (United Republic of)
Venezuela, Bolivarian Republic of Venezuela (Bolivarian Republic of)
Virgin Islands, British Virgin Islands (British)
Virgin Islands, U.S. Virgin Islands (U.S.)

I don't think most of this matters much, but it would be good to at least
make North Korea consistent with the others on GBIF's list that start with
the name people actually use and put the rest after the comma or
parenthesis.

**Comment by MattBlissett** [comment]
GBIF uses the term "countries and areas", since not everything is a country. We can browse the standard here: https://www.iso.org/obp/ui/#iso:code:3166:SZ — from that entry, it is up to date to this summer.

You have found all the exceptions, which are a fairly consistent reformatting of parentheses. 

I believe Morten tagged it content so the communications team would update the website translation for "KP".

**Comment by dnoesgaard** [comment]
KP translation changed to 

Korea, Democratic People’s Republic of

**Comment by MattBlissett** [comment]
And accepting `East Timor` is now working in UAT: https://www.gbif-uat.org/occurrence/1450982551
