### ISSUE TITLE
Super minor: The profile tab shows as "My downloads"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1591]
**Super minor: The profile tab shows as &quot;My downloads&quot;**

The tab shows as "My downloads" in Chrome while the page tab is actually "Profile" if you go to Downloads and then click back to "profile"

It makes the browser back history look slightly odd.

-----

User provided contact info: @timrobertson100
System: Chrome 70.0.3538 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif-uat.org/api/feedback/user/5b7c0e21998e1f683b196eccdf64e70f:5988104956e64eab510ca9f8ad41198e32a35d10d8202c5443529a4d754612a4f53a843886b49d359f3555f5788dd1b9878e5f3ac0903996ccfbac19cebcfd3b)
Referer: https://www.gbif-uat.org/user/profile
Window size: width 2346 - height 1069
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-25T09:17:42.772Z',mode:absolute,to:'2018-10-25T09:23:42.772Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-25T09:17:42.772Z',mode:absolute,to:'2018-10-25T09:23:42.772Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
It isn't something I can reproduce or else I'm misunderstanding. Could you show me in screenshots or in persona please.

**Comment by MortenHofft** [comment]
ahh - actual proper browser tab/page title. the <head><title>. not the ui tab title.
