### ISSUE TITLE
Information Withheld Query

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1594]
**Information Withheld Query**

Hello,

I use GBIF data to run species distribution models as part of my PhD (it's a fantastic resource so thank you, and I'll be sure to cite GBIF in any publications). Recently I noticed the InformationWithheld field when I was cleaning some occurrence records. For one of my study species, Rana latastei, 99% of the inputs in this column will state something like 'Coordinate uncertainty increased to 27126m to protect threatened taxon'. Does this mean the longitude/latitude has been shifted in a random direction by 27.126km? I assume this is the case but I wanted to be 100% sure before I start removing species from my study due to coarse coordinate precision. 

Best wishes,
Joe

-----

User provided contact info: joebellis7@gmail.com
System: Chrome 69.0.3497 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/35d6d4c66da187da885322ea9cc77d63:7178f334c0d7d6d80cbf3ee070111a4ffdecc6f6bf6417e7cff998c6a89a71f17d7c856fef56ce8f4bd444cee5157da9af0a99afcf65333b049766850623713c)
Referer: https://www.gbif.org/faq
Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-27T11:47:43.251Z',mode:absolute,to:'2018-10-27T11:53:43.251Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-27T11:47:43.251Z',mode:absolute,to:'2018-10-27T11:53:43.251Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Hi Joe

> Does this mean the longitude/latitude has been shifted in a random direction by 27.126km?

Yes, that is what it means. The publisher has obfuscated the coordinates to protect the species in question. This is often seen with endangered species. If some cases the dataset holders are willing to share more detailed information upon request.

Hope that helps
Thanks

**Comment by tucotuco** [comment]
One slight point of information, the coordinates have been shifted by **up to** 27.16km.

**Comment by JoeBellis** [comment]
Hi Morten,

Thank you for your prompt response, shame I didn't do the same!

In your message you suggest that dataset holders are sometimes willing to share more detailed location data upon request. Is this something that can be done in one go through the GBIF platform or something that I would do by contacting each rights holder independently? 

Best wishes,
Joe

**Comment by MortenHofft** [comment]
Each rights holder independently I'm afraid.
