### ISSUE TITLE
Rename occurrence facet filter "GBIF network"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1597]
**Rename occurrence facet filter &quot;GBIF network&quot;**

We currently have an advanced facet filter called "GBIF network", which allows to search for registered data networks (so far, only OBIS). This is a confusing homonymy with what we call "GBIF network" in other places, i.e. the network of GBIF participant nodes, publishers etc. 

Suggest to rename to something like "Data network", "Special interest network" or similar (@gbif/comms ?)

-----

User provided contact info: @ahahn-gbif
System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/a1c0372a8429b7e0ccd3f5e90b272730:57f491b096a69617afa03063be2e780b9a49b8d57671bb5e5308d079ad9fe1958dfe977b5df8e25baca70adce2d5f0e125a70950bebd948b8bc10951f787208b)
Referer: https://www.gbif.org/occurrence/search?advanced=1
Window size: width 1120 - height 764
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-29T09:58:50.115Z',mode:absolute,to:'2018-10-29T10:04:50.115Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-29T09:58:50.115Z',mode:absolute,to:'2018-10-29T10:04:50.115Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
"Publishing network" or "data network" seem to make sense to me.

**Comment by dnoesgaard** [comment]
@kcopas, do you have any objections to changing this to "data network", e.g.

![screenshot 2018-10-29 at 11 28 30](https://user-images.githubusercontent.com/21358085/47644195-c94d3a80-db6d-11e8-9a2b-4a89922126b9.png)

**Comment by kcopas** [comment]
None. Sounds good. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dnoesgaard** [comment]
Translation changed in https://crowdin.com/translate/gbif-portal-en/all/endk-en#10308
