### ISSUE TITLE
Needs to support phylum, class, order, family, genus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#16]
**Needs to support phylum, class, order, family, genus**

The tool needs to allow people to pass in more fields in their CSV to represent what happens in e.g. indexing.

-----
fbitem-6229f97d983b0ca850db2714bee3e34d3773b8f9
Reported by: @timrobertson100
System: Chrome 54.0.2840 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/tools/species-lookup
Window size: width 1694 - height 906

**Comment by mdoering** [comment]
There are 2 matching modes, strict and normal/fuzzy one. The strict mode is used to match names from checklists and it only uses the kingdom, does not do any fuzzy matching and requires authors to match. So for that case the existing version is sufficient to represent what happens in indexing. For occurrence fuzzy matching it is a different story. Rank is an optional but useful field for both modes

**Comment by gbif-portal** [comment]
Closed as duplicate of https://github.com/gbif/portal16/issues/198
