### ISSUE TITLE
'Invalid date' on datset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#160]
**&#39;Invalid date&#39; on datset**

Indexing also appears to be failing on this dataset (not sure if it&#39;s dynamic)

-----
fbitem-dataset88e38292-f762-11e1-a439-00145eb45e9a
Reported by: @kcopas
System: Mobile Safari 9.0.0 / iOS 9.3.5
Referer: https://demo.gbif.org/dataset/88e38292-f762-11e1-a439-00145eb45e9a/origin
Window size: width 1024 - height 728
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-03T11:58:54.621Z',mode:absolute,to:'2017-04-03T12:04:54.621Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-03T11:58:54.621Z',mode:absolute,to:'2017-04-03T12:04:54.621Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
One of the candidates for data persistence measures (WP item 4a). The DiGIR access point is not functional, and likely has not been in a long time.

**Comment by MortenHofft** [comment]
Hi Kyle - I have changed the field it uses to use the timestamp most often present (always present?). and qualified what date of the many dataset timestamps we have. the creation/registration date.
the origin tab has since been removed:
https://demo.gbif.org/dataset/88e38292-f762-11e1-a439-00145eb45e9a

thanks
