### ISSUE TITLE
fautes de frappe et géoréférencement précis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1601]
**fautes de frappe et géoréférencement précis**

Localité :
Baume-les-Messieurs, [Grotte Du Dard] 17 km NE Lons-le-Saunier

Localité originale :
Baume-les-Messieurs, [Grotte Du Dard] 17 km NE Lons-le-Saunier

Latitude décimale 	46.690871
Longitude décimale 	5.638649
Système géodésique  WGS84

-----

User provided contact info: @domlecot
System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/48ce08580e0cf925770a4770bf6a7555:c608d7ad5e1f2212c9dc35fab54f18a8286bc098cf67273056b5920d69a2dc0e9c41f13cec5726f110166c4765cf19a15076d316b6ca265436c526aabac7f1f5)
Referer: https://www.gbif.org/fr/occurrence/1145698336
Window size: width 1366 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-29T21:25:11.383Z',mode:absolute,to:'2018-10-29T21:31:11.383Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-29T21:25:11.383Z',mode:absolute,to:'2018-10-29T21:31:11.383Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I forwarded te feedback through the Arctos feedback system (see "Comment or report bad data" [here](http://arctos.database.museum/guid/MVZ:Mamm:129660))

**Comment by ManonGros** [comment]
same dataset referenced as https://github.com/gbif/portal-feedback/issues/1602
