### ISSUE TITLE
fautes de frappe et géoréférencement précis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1602]
**fautes de frappe et géoréférencement précis**

Localité :
Baume-les-Messieurs, [Grotte Du Dard] 17 km NE Lons-le-Saunier

Localité originale :
Baume-les-Messieurs, [Grotte Du Dard] 17 km NE Lons-le-Saunier

Latitude décimale 46.690871
Longitude décimale 5.638649
Système géodésique WGS84

-----

System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/98840ca0d5725b67a6172f7c035ab3b5:d788320ca370d700bb11df88f3fcfc011e80c9f9f3dd7be604001d2f1b15272e75a94f19fc1914938f45284d234325f4b14e375c011c91dd1732ca90bf594478)
Referer: https://www.gbif.org/fr/occurrence/1145698416
Window size: width 1366 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-29T21:35:33.611Z',mode:absolute,to:'2018-10-29T21:41:33.611Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-29T21:35:33.611Z',mode:absolute,to:'2018-10-29T21:41:33.611Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I forwarded te feedback through the Arctos feedback system (see "Comment or report bad data" [here](http://arctos.database.museum/guid/MVZ:Mamm:129659?seid=1163883))
