### ISSUE TITLE
IPT user password reset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1603]
**IPT user password reset**

Hello,

I am writing for the help on the recovery of user password in a local IPT.

My admin password is lost. But I have the access to the IPT dir on the server. If I understand correctly, the only way is to replace the hashed password in user.xml.

Could you let me know how the password is hashed please?

Thank you very much in advance.

Best regards,
Zhengzhe

-----

User provided contact info: zhengzhe.wu@helsinki.fi
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/89c9223b9dd83e7c3e85265b85ef3580:6e6ff6efc913dc5037410147e437d93ffcd479851165159a22f5526905bb228a512100f38c104b006c6307b842646d275613061de6f9affe6ee2b6ce4afcb03c)
Referer: https://www.gbif.org/contact-us/directory
Window size: width 1292 - height 687
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-30T11:26:06.684Z',mode:absolute,to:'2018-10-30T11:32:06.684Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-30T11:26:06.684Z',mode:absolute,to:'2018-10-30T11:32:06.684Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
I've added an FAQ entry on resetting a lost admin password.

https://github.com/gbif/ipt/wiki/FAQ.wiki#8-how-do-i-reset-the-admin-password
