### ISSUE TITLE
Change in name of columns

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1604]
**Change in name of columns**

Changing the column names compared to 1-2 months ago made my script throw an error, and cost me time.
Why exactly did you feel the need to change column names?
And what a change.
decimallatitude became decimalLatitude... seriously, who is taking care of this database? Students?
Am I to check everytime for minor pointless changes?

-----

User provided contact info: adrian.stoica@icbcluj.ro
System: Chrome 69.0.3497 / Windows 8.1.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/aade08a212cff8d508058a912d88fee8:1cfcbf7a8ae278950a30d600420b9495292ed359a78fbde102a00c0129fc696de24e4afa18d2358e48e169e0b18897bc0c7641a589ebf665ecb32829ffcb7abe)
Referer: https://www.gbif.org/
Window size: width 1536 - height 724
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-30T12:28:03.019Z',mode:absolute,to:'2018-10-30T12:34:03.019Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-30T12:28:03.019Z',mode:absolute,to:'2018-10-30T12:34:03.019Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.
