### ISSUE TITLE
Api Use

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1605]
**Api Use**

Hello i would like to create an android app with the use of your api.
I am not a professional developer and i wont charge anything for the app.
 So i will like to know if i have your permission to do so.
Thank you in advance.

-----

User provided contact info: chartheodorou@hotmail.com
System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/8f1c0af2b2f789a61d4e951a6a152003:3dbb3a8ef0207282383bd06e66c637a6a4004d560269405389766eca1b5ff080e48f9f5c31c3b7c7213f93e5d6db253d41d40267718d22ab8fc3f9dcdd9831dd)
Referer: https://www.gbif.org/health
Window size: width 1920 - height 969
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-30T14:47:21.048Z',mode:absolute,to:'2018-10-30T14:53:21.048Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-30T14:47:21.048Z',mode:absolute,to:'2018-10-30T14:53:21.048Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.
