### ISSUE TITLE
mexican wolf dataset with no lat/long data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1606]
**mexican wolf dataset with no lat/long data**

I am trying to download occurrence records for the Mexican Wolf (Canus lupus baileyi) for a class exercise on niche modeling. Even when I select only those records with coordinates, my download does not have any coordinates (lat/long) for each occurrence record. Am I missing a step in the download process? Or are these data embargoed? If so, is there a way to un-embargo them for teaching purposes?

Thanks - Cori

-----

User provided contact info: cemyers@unm.edu
System: Chrome 68.0.3440 / Mac OS X 10.11.6
User: [See in registry](https://www.gbif.org/api/feedback/user/a429d07956e77189d1332a6ebca516df:311e0eb906de173ecb4d0678e20e5de575860083c5253c1a2ac48339e863e9b7a1ad567ea83002e23c0a22439af814d3b547f519ec0cd0239d328add5b052cb2)
Referer: https://www.gbif.org/dataset/84faa3a4-f762-11e1-a439-00145eb45e9a
Window size: width 1528 - height 1203
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-30T17:54:45.229Z',mode:absolute,to:'2018-10-30T18:00:45.229Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-30T17:54:45.229Z',mode:absolute,to:'2018-10-30T18:00:45.229Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.
