### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1607]
**Citations**

I am in the process of revising a paper to publish in which I used occurrence data from gbif. I have two questions regarding citations:

1. Some of the DOIs for my searches have disappeared. How can these be recovered?
2. I am citing searches for eight different species. How do I format one citation for all eight searches?

Thank you so much for your time and help.

-----

User provided contact info: erlan045@umn.edu
System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b905deb834a02471c2be96e482dbea7e:5f1e95baced8abf1d29b04996b3cb56281e0643aa8b70b72ab4f32f40528ca786f588a13a3a0a89d2efd708c8a39dc18418aa2b7b73613dfa8892e4ff4403423)
Referer: https://www.gbif.org/faq?question=for-how-long-will-does-gbif-store-downloads
Window size: width 1286 - height 664
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-30T18:44:42.930Z',mode:absolute,to:'2018-10-30T18:50:42.930Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-30T18:44:42.930Z',mode:absolute,to:'2018-10-30T18:50:42.930Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.

Serendipitous timing with https://github.com/gbif/gbif-doi/issues/6.
