### ISSUE TITLE
erreur taxonomique

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1608]
**erreur taxonomique**

le spécimen collecté par Grenier en 1843 est identifié Orchis pseudo-speculum par lui. Son nom valide est Ophrys virescens M.Philippe, 1859 (selon le CBNFC ORI)
`http://cbnfc-ori.org/fiche-espece/especes-vegetales/695b/13261`

-----

System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/51eb645e06bd2925c48a8ff11d939824:bbf17cc488421d4e80314d36c9cb540dc219d692f32508b5b72becef250b97cd1b01569bbe77199b33527ecd7e2f1b2a9d53bf6680b9fa2dee60a77966ef5456)
Referer: https://www.gbif.org/fr/occurrence/438713793
Window size: width 1366 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-30T23:56:38.852Z',mode:absolute,to:'2018-10-31T00:02:38.852Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-30T23:56:38.852Z',mode:absolute,to:'2018-10-31T00:02:38.852Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Google translate
> the specimen collected by Grenier in 1843 is identified Orchis pseudo-speculum by him. Its valid name is Ophrys virescens M.Philippe, 1859 (according to the CBNFC ORI)
http://cbnfc-ori.org/fiche-espece/especes-vegetales/695b/13261

**Comment by ManonGros** [comment]
The publishers have been notified.

**Comment by ManonGros** [comment]
The publishers have taken into account the feedback and decided to keep the original data content for now.
