### ISSUE TITLE
Publisher list without filters: "Published Datasets: 0" instances bubbling to the top needs either hiding or a more positive twist

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#161]
**Publisher list without filters: &quot;Published Datasets: 0&quot; instances bubbling to the top needs either hiding or a more positive twist**

The publisher list without set filters, as showing when coming through the main &quot;Get data&quot; menu, looks a bit depressing with most of them having &quot;0&quot; datasets. This is because in that case, newest registrations are listed at the top. This is good in principle - new publishers may be the ones most interested in checking whether their entry has come up yet after endorsement, plus we do want to show dynamics. To make this more transparent, a few ideas that have been tossed are:
- a pre-set filter to only show publishers with published datasets. This filter needs to be easily recognizable and removable though
- a default to hide publishers that have not (yet) published, and a filter to include publishers with zero datasets
- mark datasets as &quot;new&quot; if they are less than 3 months old
- add the registration date to the results list
- other options?

-----
fbitem-22de88f76c9d79b8f048b83b3cfbc3036b234366
Reported by: @ahahn-gbif
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/publisher/search
Window size: width 1257 - height 662
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-03T14:23:40.577Z',mode:absolute,to:'2017-04-03T14:29:40.577Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-03T14:23:40.577Z',mode:absolute,to:'2017-04-03T14:29:40.577Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I've added a new publisher label to all publishers that was created within the last 3 months
registration added to the search result.
![screen shot 2017-05-02 at 13 06 53](https://cloud.githubusercontent.com/assets/6759267/25615574/483daf84-2f38-11e7-974f-ed50627934fc.png)
The other suggestions are good but require API changes.
@ahahn-gbif could you please help evaluate the current state https://demo.gbif.org/publisher/search?q=peru
and suggest a priority. I will label this an API issue for now.

**Comment by ahahn-gbif** [comment]
Good for now - we can re-evaluate additional changes at some point, but I think this nicely fixes the issue around the "sad" list seen before. Closing - please reopen if needed.
