### ISSUE TITLE
faute de frappe pour l'année

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1610]
**faute de frappe pour l&#39;année**

1844 et non 1944 (Justin Marie Goudot est mort le 6 juin 1847 à Honda)

-----

System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7b5cc0819f9cbc9b9719683633b7ea50:78809a9f9e5db86b0f1227ab0a71480748695cd7248f455448d4b6f23ec4f124de0a9c5acfd41ff54a282665e905f9a2b96f4ba6091f4c041e48aada481a5a48)
Referer: https://www.gbif.org/fr/occurrence/438006786
Window size: width 1366 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-31T17:53:35.741Z',mode:absolute,to:'2018-10-31T17:59:35.741Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-31T17:53:35.741Z',mode:absolute,to:'2018-10-31T17:59:35.741Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publishers have been contacted.

**Comment by ManonGros** [comment]
The publishers have updated the record.
