### ISSUE TITLE
correction du pays

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1611]
**correction du pays**

Ce n'est pas l'ile de la Grenade mais la Nouvelle Grenade, soit la Colombie actuelle (ville de Carthagène)

-----

System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/a804eecc1f92007dc196ec2122eb38ca:8b92e051a97bc0bbffcab7f9ce324f21581c00483cd04eecfc7a06e3ba94781bb79fba6570cbc162e8e0696074827940b9a478fa80fdd930c8992a6dc910dfab)
Referer: https://www.gbif.org/fr/occurrence/437133171
Window size: width 1366 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-31T18:06:22.113Z',mode:absolute,to:'2018-10-31T18:12:22.113Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-31T18:06:22.113Z',mode:absolute,to:'2018-10-31T18:12:22.113Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publishers have been contacted.

**Comment by ManonGros** [comment]
The publishers have updated the record.
