### ISSUE TITLE
proposition de traduction de la localité

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1612]
**proposition de traduction de la localité**

regium calida = région de Cali, en Colombie !

-----

System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5f8c5ebadc64523fa8be75988926ff53:7dd2a15636eb90cddad252ecd2fe3ea3a8732513168a41dc369cb51b837b7d486dbf43ec879dec9111130faf31ccd17fb5c03d6596c6304020eaa9b73cf8bf69)
Referer: https://www.gbif.org/fr/occurrence/464982075
Window size: width 1366 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-31T18:26:37.745Z',mode:absolute,to:'2018-10-31T18:32:37.745Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-31T18:26:37.745Z',mode:absolute,to:'2018-10-31T18:32:37.745Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publishers have been contacted.

**Comment by ManonGros** [comment]
The publishers have updated the record.
