### ISSUE TITLE
erreur sur le collecteur

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1613]
**erreur sur le collecteur**

Cette plante collectée en Colombie l'a été par Justin Marie Goudot et non son frère Jules Prosper Goudot.
Les initiales du collecteur sont donc J. M.

-----

System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4a10268bc0f8f5e12a1c7ab918576e71:6563aa1df115e778f9d4be70d600a3d0c00d6c5ff87161bcb3fd2d48620951e0e99dd1eee93ba0ea8ce9594b15d2e550309c0ba4415de9825c915abb70cb6258)
Referer: https://www.gbif.org/fr/occurrence/1141493464
Window size: width 1525 - height 730
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T01:47:54.228Z',mode:absolute,to:'2018-11-01T01:53:54.228Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T01:47:54.228Z',mode:absolute,to:'2018-11-01T01:53:54.228Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publishers have been contacted.

**Comment by ManonGros** [comment]
Fixed in the collection database and should be visible with the next export.
