### ISSUE TITLE
erreur dans l'identification du collecteur

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1617]
**erreur dans l&#39;identification du collecteur**

Cette plante collectée en Colombie l'a été par Justin Marie Goudot et non son frère Jules Prosper Goudot.
Les initiales du collecteur sont donc J. M. et non J. P.

-----

System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/07fec767a2b4f8b664e167344e3ae459:748e66faaaebd81af27b2db0cb4596b5164b96672afe24a498e1398e4c13e245dd400c41c143c8b525314cd6545879b5a0cfa91e6d8aa67b780adbfc399779d3)
Referer: https://www.gbif.org/fr/occurrence/1137372337
Window size: width 1525 - height 730
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T02:06:00.535Z',mode:absolute,to:'2018-11-01T02:12:00.535Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T02:06:00.535Z',mode:absolute,to:'2018-11-01T02:12:00.535Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publishers have been contacted.

**Comment by ManonGros** [comment]
Fixed in the collection database and should be visible with the next export from Naturalis.
