### ISSUE TITLE
erreur dans l'identification du collecteur

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1618]
**erreur dans l&#39;identification du collecteur**

Cette plante collectée en Colombie l'a été par Justin Marie Goudot et non son frère Jules Prosper Goudot.
Les initiales du collecteur sont donc J. M.

La distinction des deux est en ligne ci dessous :
`https://de.wikipedia.org/wiki/Justin_Marie_Goudot`

`https://de.wikipedia.org/wiki/Jules_Prosper_Goudot`

-----

System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/946b9aadaec10a5d50d1f26c1d6ab36d:72f98620be9d347ad9eb2cb09891d2ac01d3130e2161cde9b45fc759088ee51d2b4956c0f6d0c74ea18a3a961dcbdaf480a21850b1354d5693ed272de3cfc0e2)
Referer: https://www.gbif.org/fr/occurrence/1139684997
Window size: width 1525 - height 730
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T02:14:03.555Z',mode:absolute,to:'2018-11-01T02:20:03.555Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T02:14:03.555Z',mode:absolute,to:'2018-11-01T02:20:03.555Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publishers have been contacted.

**Comment by ManonGros** [comment]
Fixed in the collection database and should be visible with the next export from Naturalis.
