### ISSUE TITLE
Erreur sur l'identité du collecteur

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1619]
**Erreur sur l&#39;identité du collecteur**

Le collecteur de cet isotype est Justin Marie Goudot et non son frère Jules Prosper Goudot. C'est le seul des deux qui soit allé en Colombie, notamment sur le pic Tolima, comme botaniste de la mission Zea à partir de 1822. 
L'année de collecte peut être 1828 (dès février suivant Decaisne) ou 1829 (suivant Lasègue)
initiales des prénoms à modifier : Goudot J. M.

-----

System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/78cbc54f6482bf92600783e35424fd22:97fc79664b5e67a22df33327992968b3198d9ae7ba81f243518db822d6b9f5f4fc64d4246e15dafcd2a3b01dce568ade943046162b4be1193e7c32fc373c7ad9)
Referer: https://www.gbif.org/fr/occurrence/1138258520
Window size: width 1525 - height 730
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T02:42:38.544Z',mode:absolute,to:'2018-11-01T02:48:38.544Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T02:42:38.544Z',mode:absolute,to:'2018-11-01T02:48:38.544Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publishers have been contacted.

**Comment by ManonGros** [comment]
Naturalis Biodiversity Center (NL) – Botany replied: the herbarium is currently moving its collection to a new facility and will process feedback when it reopens (during the summer 2019).

**Comment by ManonGros** [comment]
Issue solved (https://www.gbif.org/occurrence/2287200205)
