### ISSUE TITLE
GBIF network - country count - papers

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#162]
**country count - papers**

The page currently reads

xxx peer-reviewed publications by
xxxxx authors from
61 countries

I&#39;m not sure that last number is correct. I tried pulling the counts for all countries and I got values &gt;1 for 130 countries.

-----
fbitem-5f8f9aca65a6fc0d0677bfe440ec39d391db6ce0
Reported by: @dnoesgaard
System: Chrome 57.0.2987 / Mac OS X 10.12.3
Referer: https://demo.gbif.org/the-gbif-network
Window size: width 1782 - height 918
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-04T11:51:54.338Z',mode:absolute,to:'2017-04-04T11:57:54.338Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-04T11:51:54.338Z',mode:absolute,to:'2017-04-04T11:57:54.338Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
literature counts have been deemed less relevant for that page and therefore removed. If we decide to add them again it should have lower visual priority and get data from the SOLR api
