### ISSUE TITLE
Introduced and Invasive species wording

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/portal-feedback#1620]
Final wording for the table underneath the map (introduced and invasive species) on a species page like https://www.gbif.org/species/3222442:

table header: 
- Recorded as introduced in (x) countries and islands
column headers:
- Recorded as introduced in
- According to
- Evidence of impact? (values: Yes / No)
- Occurrences in GBIF

(related correspondence with the GRIIS editors: helpdesk reference archive)

**Comment by dnoesgaard** [comment]
I believe that's it:

![screenshot 2018-11-01 at 16 18 49](https://user-images.githubusercontent.com/21358085/47860874-df6b2d00-ddf1-11e8-916c-930dbf4492ed.png)
