### ISSUE TITLE
20 mil occurrences with the organismId 'None'

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1621]
**20 mil occurrences with the organismId &#39;None&#39;**

All from the same dataset

-----

User provided contact info: @MortenHofft
System: Chrome 69.0.3497 / Mac OS X 10.11.6
User: [See in registry](https://www.gbif.org/api/feedback/user/73a085a6f720591c25745b3e9003919a:9d9106eb80229f3466bf1a254de75d88766e6a7a846d29e1a1b5c710c108ee0e5f85196899135eb407177f2c99ea73a22eb0f978a5f2b98c7836017da5c71f03)
Referer: https://www.gbif.org/occurrence/search?dataset_key=b124e1e0-4755-430f-9eab-894f25a9b59c&organism_id=None&advanced=1
Window size: width 1904 - height 1275
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T08:47:52.766Z',mode:absolute,to:'2018-11-01T08:53:52.766Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T08:47:52.766Z',mode:absolute,to:'2018-11-01T08:53:52.766Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
This should be updated in the dataset, but I will also check what interpretation we are doing — values like n/a, none, - are often removed.

**Comment by MattBlissett** [comment]
We don't do any interpretation at all of organismId.

**Comment by ahahn-gbif** [comment]
publisher contacted (email, 18.12.18)

**Comment by dagendresen** [comment]
Hi @steinho seems that all ([19,718,192](https://www.gbif.org/occurrence/search?dataset_key=b124e1e0-4755-430f-9eab-894f25a9b59c&organism_id=None&advanced=1)) occurrences from [Artsobservasjoner](https://doi.org/10.15468/zjbzel) have [organismID](http://rs.tdwg.org/dwc/terms/organismID) set to "None". Would you consider to exclude organismID - or perhaps report at NULL? How do you plan to use organismID for this citizen science dataset?

**Comment by ahahn-gbif** [comment]
Data change at source confirmed Jan 1, 2019. Due to a two-step publication chain, this may take a bit longer to filter through to GBIF.org (reindexing attempt on Jan 7 still without changes, revisit).
