### ISSUE TITLE
Node Contact information update

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1623]
**Contact information update**

In the 'contacts' sections, some modifications are needed:
- David Shorthouse is no longer working at the IRBV, but at the Canadian Museum of Nature. His contact info are associated with in the CMN page (`https://www.gbif.org/publisher/a41250f0-7c3e-11d8-a19c-b8a03c50a862)`
He is the node manager for CMN
- For Canadensys, the contact (node manager) is me (Carole Sinou). My info are: 
Biodiversity Data Manger
Institut de recherche en biologie végétale (IRBV)
Dépt. sciences biologiques, Université de Montréal 
4101 Sherbrooke E. Montréal, Quebec H1X2B2
canadensys.network@gmail.com 
+1 514 343 6111 #83148

-----

User provided contact info: @CaroleSinou
System: Chrome 69.0.3497 / Mac OS X 10.12.6
User: [See in registry](https://www.gbif.org/api/feedback/user/b97c6a694d700174adf3137f8deadc20:594ca2190bd680e2144bfb830625d9cd63b5b62cc4ea0419c56ba1b940918539413eee69dc0592e2bf9841bd714c2d95e8b6f23842e628f96eab26bbb000935b)
Referer: https://www.gbif.org/country/CA/summary
Window size: width 1440 - height 790
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T13:37:40.573Z',mode:absolute,to:'2018-11-01T13:43:40.573Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-01T13:37:40.573Z',mode:absolute,to:'2018-11-01T13:43:40.573Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I can't update the node contact information.
@MattBlissett Could you forward it to someone?

**Comment by MattBlissett** [comment]
@anmnielsen, who in Admin is best to handle node information update requests?

**Comment by anmnielsen** [comment]
@MattBlissett I have updated the contact information for David Shorthouse in agreement with the Canadian Node manager. The contact information for the Canadensys Node manager, Carole Sinou, is up-to-date.

**Comment by ahahn-gbif** [comment]
@CaroleSinou, may I ask you to check that the changes are complete at: 
https://www.gbif.org/country/CA/summary
https://www.gbif.org/participant/365#contact3917
