### ISSUE TITLE
Location seems suspect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1626]
**Location seems suspect**

Although the coordinates are given, the voucher information of the sheet indicates that it was collected in Calvinia, not in the current place that it appears in the map

-----

User provided contact info: jimarcorr@gmail.com
System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/f7aea4cd5936b8843695bc6701c512a9:addc76f6f312857e5329d2711b33e924c0b85e4f56a536303d3233054601d2f6c7b964007fb432807f5b70e76ccdebc97036e665375ce9240be74161e88028db)
Referer: https://www.gbif.org/occurrence/1056758023
Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-05T13:54:39.572Z',mode:absolute,to:'2018-11-05T14:00:39.572Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-05T13:54:39.572Z',mode:absolute,to:'2018-11-05T14:00:39.572Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I forwarded this feedback to their [data portal](http://data.nhm.ac.uk/dataset/collection-specimens/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb/record/4559136#markdown).

**Comment by NorbertHolstein** [comment]
Thank you for your feedback. You are correct, the geo-reference was far off. The FM tower is at ca. 31.3844S 19.7806E. I updated the reference in our system, and it should online by tomorrow.

**Comment by ManonGros** [comment]
The update is now visible on GBIF.
