### ISSUE TITLE
GEOLocate update URL please

### ISSUE THREAD

**Issue by debpaul** [gbif/portal-feedback#1629]
See https://www.gbif.org/tool/81313/geolocate-tool
URL needs updating for GEOLocate. This software is now at Yale.

New URL http://www.geo-locate.org/
Perhaps you can contact nelson.rios@yale.edu for more information on any needed updates to the content.

Thanks!

**Comment by dnoesgaard** [comment]
Thanks Deb. I've updated the tool page.
