### ISSUE TITLE
Wrong dataset taxon redirection

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#163]
**Wrong dataset taxon redirection**

When looking up the dataset species/127741994 from UNITE on UAT I get redirected to an entirely different Plazi dataset.

Real species: http://api.gbif-uat.org/v1/species/127741994
Demo portal redirect: http://demo.gbif-uat.org/species/127741994

-----
fbitem-dataset43933ac0-4e71-49e9-98c0-c3cf6b7822c0

System: Chrome 56.0.2924 / Mac OS X 10.12.3
Referer: https://demo.gbif-uat.org/dataset/43933ac0-4e71-49e9-98c0-c3cf6b7822c0/taxonomy/127741994
Window size: width 1616 - height 797
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-05T20:25:29.313Z',mode:absolute,to:'2017-04-05T20:31:29.313Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-05T20:25:29.313Z',mode:absolute,to:'2017-04-05T20:31:29.313Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
demo portal is using prod APIs. the UAT is in interface only.
The problem is that the UAT API's cannot deliver the facets needed for the new site due to performance issues.
http://api.gbif.org/v1/species/127741994
