### ISSUE TITLE
Improve clarity to audio link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1630]
**Improve clarity to audio link**

This is a dataset primarily of sound recordings. We do have them, but the first link on this page to the MP3 is not entirely clear that it is the audio recording.

If we could make that more clear to users, I think it would be a good enhancement

-----

User provided contact info: @timrobertson100
System: Chrome 70.0.3538 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/6461a491c2c7a7a689ea713e7c007958:8668ae0027e02cb84c3df9ad052ae6e81b0cddb8905c6b112f5579cec469a5497b0495e18feb4b6bccc7e9fbe7805b2e1cea6b17cc10109023bfd8f62c67b73e)
Referer: https://www.gbif.org/occurrence/1934979362
Window size: width 2225 - height 1252
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-08T07:49:08.710Z',mode:absolute,to:'2018-11-08T07:55:08.710Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-08T07:49:08.710Z',mode:absolute,to:'2018-11-08T07:55:08.710Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
We just received 137k, nicely mapped in Audubon Core: https://www.gbif.org/dataset/b1047888-ae52-4179-9dd5-5448ea342a24

And we already had 16k: https://www.gbif.org/dataset/b7ec1bf8-819b-11e2-bad2-00145eb45e9a

Where `format=audio/mp3` we should show a small HTML media player, perhaps with `<audio controls="controls" preload="none">` which means it won't be loaded unless the user clicks play.

**Comment by MortenHofft** [comment]
Indeed we should. it has been kicked down the road for a long time.

**Comment by MattBlissett** [comment]
The real MIME type is `audio/mpeg`, which the parser ought to normalize to given the mix of `audio/mp3`, `audio/mpeg3`, and `audio/mpeg` that we have.

**Comment by MattBlissett** [comment]
Morten did this.
