### ISSUE TITLE
New text relating to media tool needs correcting

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1632]
**New text relating to media tool needs correcting**

In the new text below the audio/video player, please correct to:

Not working as expected? Try the publisher's version. Take me there

-----

User provided contact info: @timhirsch
System: Chrome 70.0.3538 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/50c3dd9be75573c7e78b72a1936531e8:4525db6f9400dbdbd716247d0d2ec4056436431479f68df394971a00e56aa451e7166cb601673760587e5341def50a6cf8c895d7bee586c97a4bab81af80d008)
Referer: https://www.gbif.org/occurrence/665765642
Window size: width 1436 - height 732
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-09T07:19:18.137Z',mode:absolute,to:'2018-11-09T07:25:18.137Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-09T07:19:18.137Z',mode:absolute,to:'2018-11-09T07:25:18.137Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The danglish version was corrected yesterday, but not in put in prod. For translation to proper english see https://crowdin.com/translate/gbif-portal-en/152/endk-en#q=expected

**Comment by dnoesgaard** [comment]
Also on this:
https://github.com/gbif/portal16/issues/1045

**Comment by dnoesgaard** [comment]
Have changed translation to:

Media playback not working as expected? [Try version at publisher's site]()
