### ISSUE TITLE
Scientific Name and Genus/Species are contradictory.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1634]
**Scientific Name and Genus/Species are contradictory.**

The scientific name is listed as Coryphasia albibarbis.The Genus/Species are listed as Neaetha membrosa, which occurs only in the Old World

-----

System: Safari 12.0.0 / Mac OS X 10.12.6
User: [See in registry](https://www.gbif.org/api/feedback/user/e306e5ff712d6d7ee0f78df32a4a8687:fb9533fe4f3346b6094a302339366d84b9273dd0a84f272f6c60e8e2eb2633f7595129951b263cc0f95de79abecb1a6d1039b612397abaef85f08959cf8f15bf)
Referer: https://www.gbif.org/occurrence/search?geometry=POLYGON((-56.717961234250936%20-28.77131754897715,-52.717961234250936%20-28.77131754897715,-52.717961234250936%20-24.77131754897715,-56.717961234250936%20-24.77131754897715,-56.717961234250936%20-28.77131754897715))&has_coordinate=true&has_geospatial_issue=false&taxon_key=2168442
Window size: width 1506 - height 964
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-09T17:52:26.700Z',mode:absolute,to:'2018-11-09T17:58:26.700Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-09T17:52:26.700Z',mode:absolute,to:'2018-11-09T17:58:26.700Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by yroskov** [comment]
I do not see any problem in CoL.

**Comment by ManonGros** [comment]
It looks like this has been solved in the new backbone.
