### ISSUE TITLE
Pellenes bitaeniata and Cosmophasis bitaeniata ARE NOT SYNONYMS

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1635]
**Pellenes bitaeniata and Cosmophasis bitaeniata ARE NOT SYNONYMS**

See wsc.nmbe.ch

-----

System: Safari 12.0.0 / Mac OS X 10.12.6
User: [See in registry](https://www.gbif.org/api/feedback/user/94b6dbf8c55e43d1606c94b2c8a6c5fa:e63dd97718f60558327824e14b5b3b5bc7ac112bcdd789701664bd1cf25847a68f6d1bcb4d6bec9e81c118bfa5191777898e80fee4f442a69b74379404e26041)
Referer: https://www.gbif.org/species/2168399
Window size: width 1506 - height 964
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-09T17:58:49.054Z',mode:absolute,to:'2018-11-09T18:04:49.054Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-09T17:58:49.054Z',mode:absolute,to:'2018-11-09T18:04:49.054Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by yroskov** [comment]
No problem in CoL. Both species are valid: Pellenes bitaeniata and Cosmophasis bitaeniata

**Comment by ManonGros** [comment]
solved in new backbone
