### ISSUE TITLE
Pelegrina flavipes is listed as in Viciria in the taxonomic path; it isn't

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1636]
**Pelegrina flavipes is listed as in Viciria in the taxonomic path; it isn&#39;t**

Pelegrina flavipes isn't in Viciria, and never was, not even close. (They're like sparrows and flamingoes).

Could this be autodiscovered by a discord between genus and scientificName?

-----

System: Safari 12.0.0 / Mac OS X 10.12.6
User: [See in registry](https://www.gbif.org/api/feedback/user/2fc8fb4e1b851e2d205c43579acdd3a0:3c61f8631ad942a091ca21d6d23fd3ce7555e6e1bba39f81480238cb9448cf1b9150309a67ad1e9e7e3a730f24cccba3e948a1db15d6a5fb8667a7f6068bcb93)
Referer: https://www.gbif.org/occurrence/1413814015
Window size: width 1506 - height 964
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-09T18:42:36.376Z',mode:absolute,to:'2018-11-09T18:48:36.376Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-09T18:42:36.376Z',mode:absolute,to:'2018-11-09T18:48:36.376Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
relate to this issue: https://github.com/gbif/portal-feedback/issues/1637

**Comment by ManonGros** [comment]
I am surprised that the corresponding BOLD bin (https://www.gbif.org/species/9969317) is attached to Viciria although the original data form iBOL specifies the genus as Pelegrina.
Shouldn't the two be showing the same taxonomy?

**Comment by ManonGros** [comment]
This issue has been solved with the new backbone.
