### ISSUE TITLE
Lists Pelegrina flavipes as synonym of Viciria flavipes. They're not.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1637]
**Lists Pelegrina flavipes as synonym of Viciria flavipes. They&#39;re not.**

Peckham and Peckham reused the specific epithet in two different genera, one from North America, the other from Africa. It seems that some script made the assumption that Peckham and Peckham would have used it only once.  I've found two cases like this in an hour of poking around. There may be hundreds of other cases.

-----

System: Safari 12.0.0 / Mac OS X 10.12.6
User: [See in registry](https://www.gbif.org/api/feedback/user/7030f50a683d376b01dfd7ad283c8bed:3655d207eea7bbf20c690508e463f02676ff374ce1e9708dec618152dded8e027ec6714ab2e4e59ba8bbb8cfc3f7a7e888e71568cd0776541c143706989a77b4)
Referer: https://www.gbif.org/species/2174261
Window size: width 1506 - height 964
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-09T18:48:14.612Z',mode:absolute,to:'2018-11-09T18:54:14.612Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-09T18:48:14.612Z',mode:absolute,to:'2018-11-09T18:54:14.612Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
They are no longer synonyms in the new backbone, however https://www.gbif.org/species/2174261 shows `Basionym: Viciria flavipes Peckham & Peckham, 1903`. Any idea why @mdoering ?

**Comment by mdoering** [comment]
I've seen that at various places, looks like we still establish the (wrong) basionym relation, but dont change the status as its coming now from our primary source
