### ISSUE TITLE
addition in Russian

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1638]
**addition in Russian**

As agreed with Anne Mette, please add the following text in  Russian after "...publishers in the country.", in the end. I will then revise the English, too.

Этот проект направлен на поддержку деятельности российского GBIF-сообщества по мобилизации данных о биоразнообразии Европейской части России. В ходе его реализации был организован обучающий семинар, посвященный методам оцифровки биологических коллекций и публикации данных через глобальные порталы. Семинар состоялся в Институте океанологии им. П.П. Ширшова РАН, в нем приняли участие кураторы коллекций, научные сотрудники, преподаватели ВУЗов и работники особо охраняемых природных территорий. В течение трех дней участники под руководством преподавателей из Франции, Норвегии, Бельгии и России осваивали основные приемы оцифровки и мобилизации данных.
Вторая часть работ по проекту была направлена на мобилизацию уже оцифрованных данных. Благодаря финансированию FinBIF выполнена геопривязка более 50-ти тысяч образцов уже доступной через GBIF гербарной коллекции МГУ(MW), опубликованы обширные флористические данные, в сотрудничестве с Сибирским экологическим центром мобилизованы данные о разнообразии птиц. В целом в ходе реализации проекта российский сегмент GBIF пополнился 28 новыми организациями и более чем 105 тысячами новых записей о находках видов.

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5e078238ab1e5ada244d3b3630aacf15:c7f044513321fa8752fcf6a2b7d0e919698008420aeecd80a35daaf4d69d24681a4fee340f884c5b767de67dfee2dcfb6e758683cbaf17176165517135d02cb4)
Referer: https://www.gbif.org/project/1r7RSp5iLqqKYssg88WIW2/gbifru-data-mobilization-activities
Window size: width 1760 - height 984
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-11T10:37:17.807Z',mode:absolute,to:'2018-11-11T10:43:17.807Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-11T10:37:17.807Z',mode:absolute,to:'2018-11-11T10:43:17.807Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
@dschigel please review and confirm that this looks ok:
https://www.gbif.org/project/1r7RSp5iLqqKYssg88WIW2/_preview

**Comment by dschigel** [comment]
Thanks, looks great. I checked the numbers in the EN part and they are ok. Could you kindly change the tenses in the EN part from future to past, as project is now finished? aims to increase -> increased, efforts will contribute -> contributed etc. Once done, please release right away.

**Comment by dnoesgaard** [comment]
We don't usually do post-hoc updates to the description, afaik. All progress is documented in the second section. @MBLaursen do you know if this is something that is done for the other programmes?

**Comment by dschigel** [comment]
I am happy to follow the practice here, at the moment EN tells the story in the future, "we will do",  RU in the past "we arranged, published". Perhaps there is a tense neutral way to do the project descriptions? If not, I aim in favour of adjusting the content (against reality) and tenses for the completed projects.

**Comment by MBLaursen** [comment]
For BID, BIFA and CESP, we aim to change the tense of the project description from future to present tense when we update the project page following the approval of the first progress report. 
This is usually done at the same time as when we start the section "project progress" by  whoever update the project page (most likely somebody in Admin)

**Comment by timhirsch** [comment]
Quick journalist's trick here - there are often tense choices that avoid making news stories or general event/project notices becoming outdated as soon as an event happens or gets under way. Simple solution is usually to use present instead of future - e.g. 'The workshop brings together  100 delegates ...', or 'The project is mobilizing datasets from herbaria and zoological collections ...' This avoids unnecessary fixes later. Won't always be applicable, but if at all possible avoid future tense in writing.

**Comment by dschigel** [comment]
Thanks @timhirsch and @MBLaursen, present is totally fine with me. We will follow this practice in the future. There current page, therefore, needs tense fixing anyhow on the English side, and also the Contact address is broken into "Instit" "ute". Thank for your attention here! I think we will add final reports when @anmnielsen is back, unless someone is ready to do it now.

**Comment by dnoesgaard** [comment]
Future tense changed to present. Contact address fixed.
