### ISSUE TITLE
Could the project tab be visible even if there is no project description?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1639]
**Could the project tab be visible even if there is no project description?**

For example, this page doesn't have any project tab although the dataset contains a project title and a project identifier.

It would make it easier for follow up and quality checking if this tab was visible.

-----

User provided contact info: @ManonGros
System: Safari 12.0.1 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/ee125d30d8a9afd94a1dfd452d634ee6:eda8ee9bbf627db9fbef02755cf90276360278f5d8348af126f0abe9d4360c08fd9853e1dec22e998d1991b47bfc267dc49c8ecf2671de87476510b05c54eff6)
Referer: https://www.gbif.org/dataset/7fafc0ae-7e73-4cec-b280-84bb69b62d75
Window size: width 1470 - height 993
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-12T10:41:29.730Z',mode:absolute,to:'2018-11-12T10:47:29.730Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-12T10:41:29.730Z',mode:absolute,to:'2018-11-12T10:47:29.730Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
We could do that. So far the logic has been to not show the tab when there isn't really any information.

currently the logic is: only show if there is at least one of
* abstract
* studyAreaDescription
* designDescription
* funding

But we could show it always - just seems uninteresting to show an essentially empty page.

**Comment by ManonGros** [comment]
Perhaps we could show it if it has an identifier? So that people can find the corresponding project page.
@timhirsch, any thoughts?

**Comment by ManonGros** [comment]
Sounds good to me!

**Comment by timhirsch** [comment]
The critical thing here is that the dataset should link back to the funded project that generated it, via the identifier - in this case https://www.gbif.org/project/82775/strengthening-the-institutional-network-in-angola-to-mobilize-biodiversity-data . You will see that the datasets including this one are linked from the project page, and it needs to happen the other way so that people can easily discover that any particular dataset was the outcome of a funded activity. The issue in this case seems to be that the project description is not pasted into the metadata of the particular dataset, and this needs to be clarified in the guidelines given to grantees @MBLaursen .

**Comment by ManonGros** [comment]
For future datasets, we define it in the guidelines but publishers are currently being told that they only need to write the project title and identifier (see [data requirement page](https://www.gbif.org/data-quality-requirements-occurrences)).

It is can be difficult to convince the publishers to update their metadata post-publication and more than 400 BID datasets have already been published. Although most of them have a Project Description paragraph, it would take us (me) months before all of them are corrected.

In the meanwhile, it would be great if we could display the link to the project page on the dataset page regardless of the project description content.
