### ISSUE TITLE
Data in data set messy after CSV download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1640]
**Data in data set messy after CSV download**

I would like to download the dataset `https://www.gbif.org/occurrence/search?taxon_key=1228026`

In order to merge records from the same coordinates and get a map with all occurrences. In this sense, tabs "Country or area" and "Coordinates" are the most important to me. 

So I've downloaded the CSV file 0002208-181108115102211, dumped it into Excel and turned text to columns. However, I quickly found out that the data is separated by tabs but instead of making new rows, new rows are indicated by a bigger number of consecutive tabs. When I open the file directly in Excel, it already looks like not all data from every row is in the row that it's supposed to be. Long story short, I don't know how to convert this data set to columns and rows in Excel(2010).

Could you please advise how to turn this data to rows and columns?

Kind regards

-----

User provided contact info: nick.schafstall@gmail.com
System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/3b93390262e7e2bee27e319b02cb20fa:a79bd9c05c2415d83aac970f9c1e24182368a960d44f41ea1212910550e7848e857a5868069c8793ae92d893c34faf67d220cb1793c67bf1e7bca44869633df8f6da86afd3bbac758eb85b508b824150)
Referer: https://www.gbif.org/occurrence/search?taxon_key=1228026
Window size: width 2133 - height 987
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-12T15:53:34.242Z',mode:absolute,to:'2018-11-12T15:59:34.242Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-12T15:53:34.242Z',mode:absolute,to:'2018-11-12T15:59:34.242Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
If I understand correctly, then this is what you are looking for https://www.gbif.org/faq?question=opening-gbif-csv-in-excel

Hope that helps
