### ISSUE TITLE
The limit of 200,000

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1643]
**The limit of 200,000**

Hello!

I just hope not being too repetitive with my question but I've found some counfunding information so far on the internet. 

I need to download all occurrences of GBIF for a certain number of species I'm working with. I use the package 'rgbif' in R Studio to download data directly from GBIF. The thing is that there is a limit of 200,000 entries to download using the function 'occ_search'. I though I could overcome this issue by specifying start='200001' and limit='400000', and keep going until I retrieved the whole set of data. However, this doesn't seem to work. It keeps warning that I have exceeded the limit. 

Is there any way to download all data from R or should I make a request directly from the webpage?

Thank you very much,
Ester

-----

User provided contact info: e.polaina@gmail.com
System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/481bedc2494fdf3a89ea5746cf037f73:d9fbb349df964f928616fbffd19eddd641fd686eef0cb70e5ea20a82f848adc94c3c1aa0504b96d1cef8f074ee815d3064a6fde619129e5e9c35a4dcb07ed186)
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1680 - height 909
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-13T13:21:34.661Z',mode:absolute,to:'2018-11-13T13:27:34.661Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-13T13:21:34.661Z',mode:absolute,to:'2018-11-13T13:27:34.661Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
Dear Ester,
The rgbif package relies on the GBIF API which allows paging through a large number of records. However this is capped at 200,000 records. Even if you specify the offset to be 200.000 it won't help. The API relies on a search index that is set to the 200K limit in order not to exceed the memory that is available.

If you have a specific list of species you can create an [occurrence_download](https://rdrr.io/cran/rgbif/man/occ_download.html) in rgbif. 
Initially you would parse the species names and get the taxon keys that go into the occurrence_download JSON predicate. The rgbif manual has more on this.

**Comment by mrchelseafan08** [comment]
Hello I'm unsure if you have managed to find this solution. I'm quite new to R and working with a professor. I'm currently trying to search data on deermice but am running into the same upper limit problem as you. Was your solution simply making a special occurence_download in rgbif?

**Comment by ManonGros** [comment]
Hi @mrchelseafan08, yes the best option is to use the occurrence_download function in rgbif. It is based on the occurrence download function of the GBIF API: https://www.gbif.org/developer/occurrence#download
This API generate download associated with a DOI and doesn't have any limit.
You will then be able to cite the DOI in your publication which will allow us to give the credit back to the data providers who's data contributed to your project.
Here is a post showing an example on generating a download with R: https://data-blog.gbif.org/post/downloading-long-species-lists-on-gbif/

The occurrence_search function is only meant for quick lookups, it is restricted to avoid too much load on our side. If possible, please use the occurrence download instead.

Does it answer your question?
