### ISSUE TITLE
Individuals registered as Publishers need handling or a change of policy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1644]
**Individuals registered as Publishers need handling or a change of policy**

Some National Node networks have access rights to register publishers and datasets through the API, including endorsements. GBIF's policy so far has been that only institutions can register as data publishers, not individuals. The fact that we now see registrations of individuals as data publishers through some of the Participant Nodes raises the question of whether to enforce the old policy (i.e. request re-linking the datasets to institutional publishers and deleting the individuals), or revisit the earlier decision.

-----

User provided contact info: @ahahn-gbif
System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e6d39dd19ae44e2c32840ebede22b065:f5bc2feeb9c8ea3553cb47d98880cf100f7fb2d1e056e264cefe10bed4e553ea7f60a704c6cc2a64db5fe5c94fe09de7e251b66f0595aa12c53ae8284e31e2a9)
Referer: https://www.gbif.org/dataset/599ba2ea-f3c1-4885-934a-7f5cad372c43
Window size: width 1009 - height 652
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-13T15:58:09.514Z',mode:absolute,to:'2018-11-13T16:04:09.514Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-13T15:58:09.514Z',mode:absolute,to:'2018-11-13T16:04:09.514Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by timhirsch** [comment]
In the particular case highlighted, the publisher remains ALA and it is the dataset that relates to the individual. It therefore does not contradict our model, although in such cases we should suggest alternative dataset titles rather than simply the person's name - so in this example, the dataset could be renamed 'Richard Hartland's personal photography collection of plants and fungi' or something similar. In fact the value of this dataset may be questioned as there is no location information, but that's not the issue under discussion. The model of an institutional publisher serving a dataset relating to an individual's collection seems perfectly fine, but this would of course be different if we find that individuals themselves are being submitted as publishers in which case we would need to consult on such a change.

**Comment by MattBlissett** [comment]
@timhirsch, this the individual publisher: https://www.gbif.org/publisher/9d209d82-4e8c-40a6-a9f5-3d4c69c957f4

**Comment by timhirsch** [comment]
ah ..yes, that's a different kettle of fish. I would recommend that we engage those nodes seen to be doing this, and suggest that in cases where the publisher is clearly an individual with no institutional affiliation, the best practice would be for the node (NBN or ALA in these kind of cases) to act as the publisher, unless and until we change the publisher model. I don't know how much of a hassle it is for these networks to make such a distinction but for the time being I think this should be our guidance. I don't see the need to take drastic action in these cases. I would appreciate @timrobertson100 's view as well.

**Comment by timrobertson100** [comment]
I don't have much to add and agree with the approach @timhirsch outlines.

This has arisen from the users of the ALA software creating "data providers" in their terminology which become "data publishers" in GBIF terminology. It is already the case that a publisher can represent a large institution, a faculty, a department or a research group.

**Comment by ahahn-gbif** [comment]
NBN: contacted by email, 14.11.18

**Comment by ahahn-gbif** [comment]
case UK NBN: relink to NBN as the data publisher, and remove the publisher entry. NBN confirmed to review their workflows, avoiding registration of individuals as GBIF publishers for the time being. Handing over to @jlegind for registry edits.

**Comment by ahahn-gbif** [comment]
done
