### ISSUE TITLE
Download species occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1645]
**Download species occurrences**

I am trying to download occurrence data for the ruby throated hummingbird from the years 2016-2017 in the United States and Canada. I pick my criteria, and is eventually narrowed down to about 40,000 records. However, once I hit download, it increases to 41,000,000 and there is no way for me to change it. How do I keep my criteria when I am downloading a CSV?

-----

User provided contact info: belan1m@cmich.edu
System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/2f41e69fcff2b149fb9f829270ee7f1b:ed016e92432b4e31411d9a004607a48f3e04a73879b75ae257a8333b6bf490e78d99147104dab1a3d763edc946b913b6556edd727032b2b38b74aeff8598067e)
Referer: https://www.gbif.org/
Window size: width 1920 - height 920
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-14T15:51:41.835Z',mode:absolute,to:'2018-11-14T15:57:41.835Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-14T15:51:41.835Z',mode:absolute,to:'2018-11-14T15:57:41.835Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
That does sound like an error. Could you please send a link to your download?

> sent per email

**Comment by MattBlissett** [comment]
The user seems to have solved the problem themselves 15 minutes later. They appear to have forgotten to add the species restriction in the first download.
