### ISSUE TITLE
project page to update

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1651]
**project page to update**

please update this page using the text provided by the project team. Please use Russian text as-is, and kindly do the necessary copy editing to the English text and links display in both versions:

В коллекциях Зоологического Mузея МГУ им. М.В. Ломоносова хранится более 150 тыс. экземпляров птиц и более 220 тыс. экземпляров млекопитающих. Коллекции охватывают период с начала XIX в. по настоящее время. Часть каталогов доступна в электронном виде на порталах Зоологического музея (`http://zmmu.msu.ru/dbs/search_start.php;` типовые экземпляры) и Депозитария живых систем (`http://animal.depo.msu.ru`). В ходе проекта «Поддержка работ по мобилизации данных в России к западу от Урала», поддержанного Секретариатом GBIF (GBIFS; код проекта “Russia-01”), были продолжены работы по оцифровке бумажных каталогов; данные, переведенные в электронную форму, опубликованы на портале GBIF. Набор данных содержит информацию о 54120 экземплярах, не имеющих типового статуса (50040 экз. птиц и 3926 экз. млекопитающих). Он включает основную информацию с каталожных карточек (вид, пол, возраст, форма хранения и др.), а также координаты мест их обнаружения (точность координат зависит от детальности географических сведений, предоставленных коллектором). Большая часть материалов собрана на территории Европейской части России; также охвачены Казахстан, Украина, Азербайджан, Грузия, Беларусь, Армения, Германия, Молдова и Латвия.

Данные доступны по ссылке: `https://www.gbif.org/dataset/9beef55a-b4a4-4031-a1e0-0d2bdeea2c21`

Collections of the Zoological Museum contain more than 150K of bird and 220K of mammal specimens, gathered since early 1880s to the present. A part of its catalogues is available in an electronic form on the museum website (`http://zmmu.msu.ru/dbs/search_start.php;` type specimen) and on the online portal of the National Depository Bank of Live Systems (`http://animal.depo.msu.ru`). In the course of the project ”Supporting data mobilization activities in Russia west of Ural mountains”, funded by the GBIF Secretariat (project code “Russia-01”), the work on digitizing the paper catalogues was continued. The data transformed into an electronic form was published on the GBIF web portal. The dataset includes main information from catalogue cards (species, sex, age, preparation form etc.) as well as coordinates of disposal site (their precision depends on the detail of geographic data provided by collectors). The major part of the data represents the European part of Russian Federation; areas covered also include Kazakhstan, Ukraine, Azerbaijan, Georgia, Belarus, Armenia, Germany, Moldova, and Republic of Latvia.

The dataset is available via `https://www.gbif.org/dataset/9beef55a-b4a4-4031-a1e0-0d2bdeea2c21`

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/fb8c02ce9044b70eff4b85d471fc2f8a:bf111cd2b88d6f29bd8737bdf4779444a17e957e756c1fff3f5526d908634f2ba57a52a513dcfe52fe336766578745f7aeb0a0f22c47e9e40aed9cad139beee2)
Referer: https://www.gbif.org/project/7xIH2xCxEWoIKom6wSQ2Y0/data-mobilization-by-the-lomonosov-moscow-state-university
Window size: width 1408 - height 675
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-20T14:01:17.019Z',mode:absolute,to:'2018-11-20T14:07:17.019Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-20T14:01:17.019Z',mode:absolute,to:'2018-11-20T14:07:17.019Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
@dschigel - "funded by the GBIF Secretariat" this is not correct, right? It's funded by FinBIF, no?

**Comment by dschigel** [comment]
Thanks, well spotted I would just borrow the words from the programme page: something like [GBIF] programme supported by FinBIF ... funded data mobilization activities... etc. Yes, please edit.

**Comment by dschigel** [comment]
Checked Russian, just one correction

from:

на портале GBIF

to:

на портале GBIF.org

**Comment by dnoesgaard** [comment]
Thanks. Now published.
