### ISSUE TITLE
Wrong georreferencing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1654]
**Wrong georreferencing**

The lat/long assigned to the specimen are totally wrong. The specimen was collcted in La Libertad, north of Lima.

-----

User provided contact info: mtimana@pucp.edu.pe
System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/9107a5e26bbb9b06deea41cdc0e515a8:3da654d0f46637afca6db4f8a8bfec6a9da084381ff31b1197b5de69f97c01d6752055f11bbbab69e81a625c6f5928727b6394ce8e1c383281849b11740bc354)
Referer: https://www.gbif.org/occurrence/1228202494
Window size: width 1280 - height 579
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-20T19:44:21.241Z',mode:absolute,to:'2018-11-20T19:50:21.241Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-20T19:44:21.241Z',mode:absolute,to:'2018-11-20T19:50:21.241Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
same dataset as https://github.com/gbif/portal-feedback/issues/1655

**Comment by ManonGros** [comment]
The publishers have been notified.

**Comment by ManonGros** [comment]
The coordinates pointed towards the centroid for the Peru.
The publishers are now considering removing centroid altogether but the dataset hasn't been updated yet.

See related issues here:
#1467
#1468
#1469
#1470
#1471
#1472
#1473
#1479
