### ISSUE TITLE
Documentation: missing examples

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#1656]
In the documentation for the species API there are links to examples. Some of these are 404s or empty arrays. As a consumer I would appreciate examples, though I might be able to guess the format in some cases.

http://api.gbif.org/v1/species/5231190/verbatim is a 404
http://api.gbif.org/v1/species/5231190/media is empty
http://api.gbif.org/v1/species/5231190/combinations is empty

**Comment by MattBlissett** [comment]
Resolved yesterday.
