### ISSUE TITLE
add ambassadors ORCID

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1660]
**add ambassadors ORCID**

via ambassadors@gbif.org

"Can you please add my ORCID `https://orcid.org/0000-0001-9320-5942`

Thanks 
Prabhakar"

-----

System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/9a0f9a4256760350026b3ffa19af46d2:9321bc1e688ba46b836742c405fb6cf7217ba8295553f69fa7b0abc8d5fff9222f57497608812f1d76d671106e220810bc952510c37640c86b24f410083dcf98)
Referer: https://www.gbif.org/article/6dNF1d0tgcI4cmqeoS2sQ4/biodiversity-open-data-ambassadors
Window size: width 1600 - height 894
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-22T14:12:25.282Z',mode:absolute,to:'2018-11-22T14:18:25.282Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-22T14:12:25.282Z',mode:absolute,to:'2018-11-22T14:18:25.282Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Done. (ping @dschigel)
