### ISSUE TITLE
Rhododendron

### ISSUE THREAD

**Issue by SandyUMSFRC** [gbif/portal-feedback#1662]
This https://www.gbif.org/occurrence/1931152857 is a synonym to Rhododendron bagobonum H.F.Copeland. Please refer to this link: http://www.catalogueoflife.org/annual-checklist/2018/details/species/id/123e4af10f6b0dd2483b52e6c0bee495/synonym/fa28569e43c9d3bebc1544958efde7b8 for verification.

Thanks!

**Comment by SandyUMSFRC** [comment]
Following the issues of Rhododendron cuneifolium dataset. Here is another wrong placement of species https://www.gbif.org/occurrence/1140311635. 
According to the specimen sheet on the Papua New Guinea collection, it is Rhododendron curviflorum. 

Rhododendron cuneifolium supposed to be Sabah endemic. I would really appreciate if the dataset can be clean up to prevent misunderstanding.

Thank you.

**Comment by ahahn-gbif** [comment]
notified Naturalis

**Comment by ahahn-gbif** [comment]
Contacted NYBG through helpdesk (also including #1665)

**Comment by jeroencreuwels** [comment]
Thanks Andrea! I have notified our botanical curator at Naturalis, who will have a look at it.

**Comment by jeroencreuwels** [comment]
The data entry has been changed (but it will take some time before this will be visible at GBIF). An error was made during the mass digitization at our institute, which caused wrong data entry. Cheers, Jeroen

**Comment by ahahn-gbif** [comment]
Thanks for the quick turnaround, Jeroen!

**Comment by ahahn-gbif** [comment]
Corrected at source - closing
