### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1663]
**dead link**

A link to 1999 recommendation by the Biodiversity Informatics Subgroup leads to an error page

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/34f75482a73be8d19524411a8bdd3605:1d1a2daa8f8b81ffaff4e4df54d683147c91f811fb230ccd2817618d4cd6d8085fd90fc894dcb1c1d43fa6dacf21aac3336f9926e25e41b2cca1d82fefd81f23)
Referer: https://www.gbif.org/what-is-gbif
Window size: width 1760 - height 984
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-26T12:51:20.041Z',mode:absolute,to:'2018-11-26T12:57:20.041Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-26T12:51:20.041Z',mode:absolute,to:'2018-11-26T12:57:20.041Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Broken link reported to OECD—will defer further action to see if they restore it. 

If they don't, we can post and link to a local copy of the PDF.

**Comment by kcopas** [comment]
OECD link restored:
http://www.oecd.org/science/inno/2105199.pdf
