### ISSUE TITLE
Unicode problem: incorrect display of accented characters in recordedby

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1665]
**Unicode problem: incorrect display of accented characters in recordedby**

-----

User provided contact info: @nickynicolson
System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/2b3f9a21603a70d1a19f89711b3d6d99:3462d035c29b8c69f1f7159521e659e4446c9dde3eecda95bd3e9ce9b0fc5d407490774fdf6ae833be0ae4f1ce75443c48c59a6459fd86a3e67070c85c9c645f)
Referer: https://www.gbif.org/occurrence/1930154966
Window size: width 2548 - height 1321
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-26T19:13:43.078Z',mode:absolute,to:'2018-11-26T19:19:43.078Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-11-26T19:13:43.078Z',mode:absolute,to:'2018-11-26T19:19:43.078Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by nickynicolson** [comment]
Screenshot snippet:

<img width="320" alt="gbif-1930154966" src="https://user-images.githubusercontent.com/3758694/49036712-5a84f080-f1b0-11e8-84f2-cbada65c0eb4.png">

**Comment by MortenHofft** [comment]
Thanks for reporting this

API or content issue
https://api.gbif.org/v1/occurrence/1930154966
https://api.gbif.org/v1/occurrence/1930154966/verbatim
https://api.gbif.org/v1/occurrence/1930154966/fragment

**Comment by MattBlissett** [comment]
This is a problem in the published data, the CSV file has a mixture of encodings within the file.

**Comment by ahahn-gbif** [comment]
Contacted publisher through helpdesk (also including #1662)

**Comment by ahahn-gbif** [comment]
fixed at source - closing
