### ISSUE TITLE
change the developer blog link to point to the data blog on the banner

### ISSUE THREAD

**Issue by jhnwllr** [gbif/portal-feedback#1667]
Since the developer blog is retired, the data blog should take its place. 

http://gbif.blogspot.com/ -> https://data-blog.gbif.org/

On  tools > gbif labs > developer blog

**Comment by MortenHofft** [comment]
@dnoesgaard do you have an opinion on this. The old one still hold data obviously, but is haven't been used by other that John since  22 June 2017. If it has been decided to abandon it, shouldn't we have a goodby post linking to the new one?

**Comment by jhnwllr** [comment]
Good idea. I can make a goodbye post on the Blogger (Developer Blog), and introduction to the new blog.

**Comment by dnoesgaard** [comment]
Sounds good. I think we can switch the nav link to the new one:

[GBIF data blog](https://data-blog.gbif.org/)

**Comment by jhnwllr** [comment]
I have posted a goodbye developer blog post on the developer blog. 
https://gbif.blogspot.com/2018/12/goodbye-developer-blog-hello-data-blog.html

**Comment by dnoesgaard** [comment]
Thanks @jhnwllr - @MortenHofft, please go ahead and update the navigation.
