### ISSUE TITLE
Matt testing again.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#167]
**Matt testing again.**

Varnish HTTP2 is hopefully fixed...

-----
fbitem-b7d0e782243d18e134a319c5602c145e6f6ae4f2

System: Firefox 51.0.0 / Ubuntu 0.0.0
Referer: https://demo.gbif-uat.org/user/profile
Window size: width 1920 - height 661
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-10T11:52:23.021Z',mode:absolute,to:'2017-04-10T11:58:23.021Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-10T11:52:23.021Z',mode:absolute,to:'2017-04-10T11:58:23.021Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Yes it is!
