### ISSUE TITLE
Add/reset pop-up for notification of new privacy policy update 

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1673]
At long last, we've got a fully updated privacy policy ready to go. Content is prepared and unpublished in Contentful.

Per my discussion with @thomasstjerne , I'll leave implementation to you all, but let's delay publishing the update and coordinate it with the deployment of a pop-up notification. 

Let me know if the current pop-up text needs refreshing.

**Comment by kcopas** [comment]
Sorry, but do you have an ETA on implementing this?

**Comment by thomasstjerne** [comment]
Could you publish in Contentful first?
Then I will reset the popup.

**Comment by kcopas** [comment]
Done—thanks.
