### ISSUE TITLE
Can't download CSV files with polygons

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1674]
**Can&#39;t download CSV files**

-----

System: Chrome 69.0.3497 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/3244a8f50bab6ef4c1276a75c9a7aa41:5420043c4afec5774a59b7b48c9a2bbf68c2f286d30fb25bd14a5e806b09dcf4950f6c605b80ce407be19e95554d8680dc08c45117580a21d9046247e8953424)
Referer: https://www.gbif.org/occurrence/download?has_coordinate=true&has_geospatial_issue=false&taxon_key=5203623&geometry=POLYGON((-98.6792%2026.43123,-97.18506%2025.79989,-94.85596%2024.84657,-94.50439%2025.44327,-93.49365%2026.98083,-92.35107%2028.88316,-92.26318%2030.41078,-95.29541%2030.25907,-98.23975%2028.88316,-98.6792%2026.43123))
Window size: width 1920 - height 920
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-03T23:16:55.413Z',mode:absolute,to:'2018-12-03T23:22:55.413Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-03T23:16:55.413Z',mode:absolute,to:'2018-12-03T23:22:55.413Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Fixed by https://github.com/gbif/portal16/commit/2de934affda91a377b1f8f6ae6b619055136294d
