### ISSUE TITLE
not existing dataset page retuns 500

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#168]
**not existing dataset page retuns 500**

we should see some meaningful 404 for the user instead

-----
fbitem-dataset8c841a09-d9bc-0000-bead-67b2775fb50e

System: Chrome 57.0.2987 / Mac OS X 10.12.4
Referer: https://demo.gbif.org/dataset/8c841a09-d9bc-0000-bead-67b2775fb50e
Window size: width 1665 - height 880
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-12T10:32:21.128Z',mode:absolute,to:'2017-04-12T10:38:21.128Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-12T10:32:21.128Z',mode:absolute,to:'2017-04-12T10:38:21.128Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/aa4b753117bccfcf44d8c1886e562468492062ff
