### ISSUE TITLE
Method typo

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1680]
**Method typo**

Reads “acousting” not acoustic.

-----

User provided contact info: @dnoesgaard
System: Chrome Mobile iOS 70.0.3538 / iOS 12.1.0
User: [See in registry](https://www.gbif.org/api/feedback/user/f80fe53896772c2865ae943143f9315d:4cbb2f829c551978f762a186c3677177282a0104ba5b7f96917702ea16160f7130bfc4c3b07fb171ccca4cf901a85459baddf97ca92f734cd8a1ba9793783ef8)
Referer: https://www.gbif.org/dataset/54df7284-37aa-4584-8484-433100d62c6c/event/QUI_AC28
Window size: width 375 - height 551
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-06T11:44:32.474Z',mode:absolute,to:'2018-12-06T11:50:32.474Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-06T11:44:32.474Z',mode:absolute,to:'2018-12-06T11:50:32.474Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
to do: contact publisher asking to fix the sampling protocol wording.

**Comment by ManonGros** [comment]
The publishers have been contacted.
