### ISSUE TITLE
this species may has

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1681]
**this species may has**

-----

System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/710e38415fb6d57efec33f20ad1cd2d7:77b7c2bc64659f37f6897e3c80aa15611ab524d52f2ef58934ab111b0278d091ef69f2c6f2376a53139b911c04e71443d875747c55a421f641bc3782cf607e41)
Referer: https://www.gbif.org/species/1038971
Window size: width 1366 - height 577
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-07T08:37:17.050Z',mode:absolute,to:'2018-12-07T08:43:17.050Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-07T08:37:17.050Z',mode:absolute,to:'2018-12-07T08:43:17.050Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Issue unclear. Closing
