### ISSUE TITLE
this species may has  synonymy ，see http://www.iab.uaf.edu/people/derek_sikes/zool575/handouts/z575-05a.pdf

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1682]
**this species may has synonymy ，see `http://www.iab.uaf.edu/people/derek_sikes/zool575/handouts/z575-05a.pdf`**

-----

System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/82d54480c160bb9834f1d8ba7651d331:31b139cd39aa952b7b0a67a5c167a52a1aaf0fb415b898653e562c74b5aa9305b8353a1f1d6e79f2c06847839f4a6caadd9f86e82d35e5d47126510e8d9071d8)
Referer: https://www.gbif.org/species/1038971
Window size: width 1366 - height 626
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-07T08:40:57.799Z',mode:absolute,to:'2018-12-07T08:46:57.799Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-07T08:40:57.799Z',mode:absolute,to:'2018-12-07T08:46:57.799Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by yroskov** [comment]
This species has synonymy in CoL: http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/15c896ac30ddf282055ebe3ca5eff73a

**Comment by ManonGros** [comment]
It seems like the synonyms cited in the documents are also now in the backbone.
