### ISSUE TITLE
updating collections, but not updated in all places

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#1683]
We updated this collection:
https://www.gbif.org/dataset/992e0685-5956-43c7-966c-6cde1fe009af
there are 18 occurrences whilst there should be 3. The latter three are properly updated in GBIF, whilst the rest ought be deleted.

With other words:  individual records (e.g. https://www.gbif.org/occurrence/1947393610)  have been updated, but those wrong occurrences have not been removed

**Comment by ahahn-gbif** [comment]
Thanks for reporting! This probably needs manual triggering of the deletion process, though that should in general be automatic for DwC-A datasets. Please be aware that automatic indexing for all Plazi datasets is temporarily on hold until we have the license statements reset (see #511), to avoid potential load issues.
