### ISSUE TITLE
feature request; (holo)type displayed in search occurrences results

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#1684]
in the recent ICEDIG meeting there has been a discussion around holotypes. Would it be possible to add a column "Type status" in the search results?
https://www.gbif.org/occurrence/search?dataset_key=992e0685-5956-43c7-966c-6cde1fe009af&type_status=HOLOTYPE

**Comment by MortenHofft** [comment]
It is added. As with other columns you can choose which to see

![show typestatus](https://user-images.githubusercontent.com/6759267/49786941-a2b22000-fd25-11e8-81f7-00d51e3bee0a.png)

**Comment by MortenHofft** [comment]
ahh sorry I didn't mention that. It is not in production yet. It will be later today. At that point you have to end your session (closing the window) first to see it after you reopen.

**Comment by myrmoteras** [comment]
Agile programming… wonderful
d

**Comment by dnoesgaard** [comment]
@MortenHofft - just noticed that while adding a couple of columns (on staging) I got a strange result with titles swapped(?):

<img width="1002" alt="screenshot 2018-12-11 at 11 32 28" src="https://user-images.githubusercontent.com/21358085/49794752-9f745f80-fd38-11e8-9ab7-ad6a7a344c27.png">

**Comment by MortenHofft** [comment]
Oops yes. if you enable both they are switched. if only one they show correctly. I have fixed and am building to prod
