### ISSUE TITLE
Publishing data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1686]
**Publishing data**

To whom it may concern, 
For an article that has not yet been published, I would like to register the populations, I studied, to the gbif database with their coordinates, altitude, lithology, vegetation and geographic location etc. 

I have already registered the organization (Gebze technical university) which I am affiliated by using "data publishing" section. Could you please guide me in detail for the next step of publishing my data?
Thanks in advance
Selin Gül Ünsal
selin.unsal@hotmail.com

-----

User provided contact info: selin.unsal@hotmail.com
System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/8e967f1563a589b534be361c40ad8712:705b3666cc7e7c3c9d0e36601408804f06c862d824fef111f6c2c07ac22c967ab07009225509c435cd378eff58c38f64c12c370bc58319eb3d84ba3de17c9d1d)
Referer: https://www.gbif.org/become-member
Window size: width 1517 - height 730
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-09T13:09:05.188Z',mode:absolute,to:'2018-12-09T13:15:05.188Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-09T13:09:05.188Z',mode:absolute,to:'2018-12-09T13:15:05.188Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Email response via helpdesk (10.12.18), refering to https://www.gbif.org/publishing-data, https://www.gbif.org/data-hosting and https://github.com/gbif/ipt/wiki/dataHostingCentres#data-hosting-centres. Based on the registration data, a hosting solution is most likely needed.
