### ISSUE TITLE
Data showing up in wrong country

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1687]
**Data showing up in wrong country**

This data is from Rwanda but showing up in Algeria - suspect that lat/long may be flipped, and since no country is specified in the original data this is not flagged as a mismatch.

-----

User provided contact info: @timhirsch
System: Chrome 70.0.3538 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/f5f9b48e5cb8ae99d6f66a9346f33a7b:8d591e69e763812f5f8a178cb67a28a8222f9cb8a08677b291b87ac20af29780ff9f7e967401f4e003dadb12d231566b19fdada71c2afc656ce2eed8478f235e)
Referer: https://www.gbif.org/dataset/cc9bd573-9c96-4532-a723-52ce1d155b36
Window size: width 1800 - height 897
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-10T06:04:32.352Z',mode:absolute,to:'2018-12-10T06:10:32.352Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-10T06:04:32.352Z',mode:absolute,to:'2018-12-10T06:10:32.352Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ahahn-gbif** [comment]
Notified by email (helpdesk 10.12.18).
