### ISSUE TITLE
How can I get the taxonKey number for using it in R?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1688]
**How can I get the taxonKey number for using it in R?**

Detailed description of hoow to find the taxonKey number. Use of occ_count in R requieres the entry of it

-----

User provided contact info: msantoss (santos.simon.m@gmail.com)
System: Firefox 63.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/c8b5d428cb7bccfc798caf5373f8ea3b:81d903f9652c1d705f5642477eab9592292cd852c913fcea8df46887fdb75a9f9d0085e47b408a194ca542440ae3c1b50d2471d1bec6b78862e485b9016f3ad6)
Referer: https://www.gbif.org/species/8084280
Window size: width 1366 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-11T12:01:29.405Z',mode:absolute,to:'2018-12-11T12:07:29.405Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-11T12:01:29.405Z',mode:absolute,to:'2018-12-11T12:07:29.405Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@msantoss it is in the url in above example : 8084280
If you use the API it is called nubKey: http://api.gbif.org/v1/species/search for the one matched to the backbone.

Hope that helps
