### ISSUE TITLE
Why does some taxon show "deleted"?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1693]
**Why does some taxon show &quot;deleted&quot;?**

For example, the page of Scincella reevesii shows "Deleted on February 1, 2018". What's the meaning of that??

link:
`https://www.gbif.org/species/2461348`

-----

User provided contact info: 102311107@gms.tcu.edu.tw
System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/649999cc449c02d37a9f73a217f44578:b8ca96b68cb3013265981cf1d188a255d54e57d4613d2a48963bc2a2b2e75bd2a3b5b4ee4fb4bcbca94e9ef553ecb1a872da2252fa5657ccda638d5bc60bdd76)
Referer: https://www.gbif.org/faq
Window size: width 1366 - height 626
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-13T15:39:04.205Z',mode:absolute,to:'2018-12-13T15:45:04.205Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-13T15:39:04.205Z',mode:absolute,to:'2018-12-13T15:45:04.205Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by dnoesgaard** [comment]
As per https://github.com/gbif/portal-feedback/issues/1709, we now have a pop FAQ entry for deleted taxa in the backbone.

Has or will someone get back to the user?

**Comment by ManonGros** [comment]
Notified the user by email (just in case).
