### ISSUE TITLE
No occurrence indexed although no visible issue

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1694]
**No occurrence indexed although no visible issue**

No occurrence can be indexed although [the validator](https://www.gbif.org/tools/data-validator/1540718763701) doesn't find any obvious issue. It seems like our log reports a problem with the license
```Refusing to fragment occurrence core in dataset [f367501d-f153-4a34-83ac-727a902c6c80] with unsupported license ```
but the license looks normal.
```<intellectualRights>
    <para>This work is licensed under a <ulink url="http://creativecommons.org/licenses/by-nc/4.0/legalcode"><citetitle>Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License</citetitle></ulink>.</para>
  </intellectualRights>
```
GBIF France contacted us to ask for help.

-----

User provided contact info: @ManonGros
System: Safari 12.0.2 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/a839c3daa8bf8da71111adba04080555:9a89f3b192b3da0effc760436aaccd942d97961b2777d762d4c3ccfcfd8dadfd0f863236566f8ecbbf925cb98779f1e378a595b62b6d7576dcd74a96f0991e94)
Referer: https://www.gbif.org/dataset/f367501d-f153-4a34-83ac-727a902c6c80
Window size: width 1333 - height 867
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-14T10:20:26.781Z',mode:absolute,to:'2018-12-14T10:26:26.781Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-14T10:20:26.781Z',mode:absolute,to:'2018-12-14T10:26:26.781Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
The metadata is failing to update, which is blocking the initial setting of the dataset's license.

```xml
<contact>
 <individualName>
  <givenName>MMM</givenName>
  <surName>FFFF</surName>
 </individualName>
 <organizationName>-</organizationName>
 <positionName>-</positionName>
 <address><city>Lyon</city><country>FR</country></address>
 <electronicMailAddress>...@hotmail.fr</electronicMailAddress>
</contact>
```
(Personal data not copied to Github)

The organizationName of `-` is the problem, it should either be null or ≥2 characters.

**Comment by ManonGros** [comment]
Thanks Matt! I will be writing to GBIF France.
