### ISSUE TITLE
number of records in downloads from specific dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1695]
**number of records in downloads from specific dataset**

`http://api.gbif.org/v1/occurrence/download/0001721-180824113759888/datasets`

I can't figure out why it says 10M records from iNat in this download...

-----

User provided contact info: @dnoesgaard
System: Chrome 70.0.3538 / Mac OS X 10.14.1
User: [See in registry](https://www.gbif.org/api/feedback/user/c9ea44618e90b199e973ab639af4ab57:0044088b746ec8e3578d69cf4ee707659c131c5a1c543b767076c32a7737b538e1a92e8c1977ddc0a7c420275317bf70f99a064eb0eb5b23f3c93de74b86c479)
Referer: https://www.gbif.org/occurrence/download/0001721-180824113759888
Window size: width 1998 - height 1123
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-14T12:51:30.954Z',mode:absolute,to:'2018-12-14T12:57:30.954Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-14T12:51:30.954Z',mode:absolute,to:'2018-12-14T12:57:30.954Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
See https://github.com/gbif/portal-feedback/issues/1659

**Comment by MattBlissett** [comment]
Closing as a duplicate.
