### ISSUE TITLE
Species naming error: https://www.gbif.org/species/2493686

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1696]
**Species naming error: `https://www.gbif.org/species/2493686`**

`https://www.gbif.org/species/2493686`

Photos Mandingoa nitidula (Green Twinspot) not Lagonosticta nitidula (Brown Firefinch)
Map data appear to be combined data for both species.

Page for Mandingoa nitidua looks OK `https://www.gbif.org/species/2493572,` though this photo is misidentified: `https://www.gbif.org/occurrence/1677325448.` It should be Hypargos niveoguttatus

This isn't a difference of taxonomic opinion; the two species have never been remotely connected.

-----

User provided contact info: jeremy.lindsell@arocha.org
System: Chrome 70.0.3538 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4e1ba058d635a1259d1d01ae9ec5cb7a:a3961adb06f80f75f260e0a13a3d7bca2ce7de990e63510d08c9fae608362061eee696df1da8af07bd8b7efc5a0808c771db78c2e664627ed926a17e762b74db)
Referer: https://www.gbif.org/health
Window size: width 1680 - height 919
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-14T14:52:56.679Z',mode:absolute,to:'2018-12-14T14:58:56.679Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-14T14:52:56.679Z',mode:absolute,to:'2018-12-14T14:58:56.679Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Checking the occurrence pages behind the Green Twinspot images at https://www.gbif.org/species/2493686, they lead to occurrences that are clearly labeled Mandingoa nitidula (e.g. https://www.gbif.org/occurrence/1891353824), but showing a taxonomic hierarchy of " Animalia Chordata Aves Passeriformes Estrildidae Lagonosticta Lagonosticta nitidula". The higher taxonomy in the source data (occurrence) is given correctly, though without the specific epithet - this is only included in the ScientificName. Indexing interprets this as Genus Mandingoa -> Genus Lagonosticta, maintains the Scientific Name as MAndingoa nitidula nitidula, but applies the wrong genus. The taxonomic status is inferred to be a synonym. 

At https://www.gbif.org/species/5845637, Mandingoa nitidula subsp. nitidula (Hartlaub, 1865) is listed as a synonym. The reference taxon link on that page leads to ITIS (http://www.catalogueoflife.org/annual-checklist/2015/details/species/id/31da4eba38054602576b25b38174d843), which has it as an accepted name. 

This seems to be rather a backbone issue than an indexing error (@mdoering ?) - needs further diagnosing.

**Comment by mdoering** [comment]
Yes, its a backbone problem. Though I cannot really see how this came about, it appears to have been like that in CoL at some stage already when we build the nub. Having the same epithet, author and nearly the same year I would have tought it would have been synonymised automatically via the basionym grouping, but it did not happen in this case. You would have an issue flagged which is missing here.

**Comment by yroskov** [comment]
Yes, its not a CoL problem

**Comment by ManonGros** [comment]
It looks like this has been solved in the new backbone.
