### ISSUE TITLE
Diamma is an accepted genus within Tiphiidae. I don't know why it is showing A. within Crabonridae (...)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1697]
**Diamma is an accepted genus within Tiphiidae. I don&#39;t know why it is showing A. within Crabonridae, and B. within Cerceris, which to my knowledge is not a related wasp genus? I can find the reference if needed. ALA seems to have it right:`https://bie.ala.org.au/species/urn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A06c08d51-1443-4bb7-b596-4ab5a86679ca#classification`**

-----

System: Chrome 71.0.3578 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/a44ed0b06b769ff43af4c8bb625510e3:bd40ace1f21c1e8389d563a29623bcc5c8b94a096fa1993ab451145f0a52401ef5ee85342b689bb2db1c92f9e30aa57f61485c4cd5b794f2a0ee082cfefdb25575f57743ddf7aa72dd741b620aaa1181)
Referer: https://www.gbif.org/species/9466120
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-14T22:37:38.437Z',mode:absolute,to:'2018-12-14T22:43:38.437Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-14T22:37:38.437Z',mode:absolute,to:'2018-12-14T22:43:38.437Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
This is a homonym issue:
1) the GBIF backbone entry of Diamma at https://www.gbif.org/species/9466120 is based on ITIS, who list Diamma Dahlbom, 1844 (ITIS taxonID: 1034174) as a junior homonym (taxonomic status: invalid) of Diamma Westwood, 1835, and reference it to Cerceris Latreille, 1802 as the accepted name
(https://www.gbif.org/species/134211760/verbatim; acceptedName usage ID: 154340 in https://www.itis.gov/)
2) the GBIF backbone holds a second entry ((also see https://www.gbif.org/species/search?q=diamma)) for Diamma Westwood, 1835 in the family of Tiphiidae at https://www.gbif.org/species/4674056 based on The Interim Register of Marine and Nonmarine Genera (http://www.irmng.org/aphia.php?p=taxdetails&id=1318246). At source, this genus is listed as accepted (https://www.gbif.org/species/107195456/verbatim).
