### ISSUE TITLE
two GBIF id for the same species?

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#1698]
in this case, there are two gbif ids for the same species?

Gyiophis salweenensis
https://www.gbif.org/species/127719449

![image](https://user-images.githubusercontent.com/4609956/50044858-176cbd80-008a-11e9-9885-24fb5226fc00.png)

and
https://www.gbif.org/species/9387792
![image](https://user-images.githubusercontent.com/4609956/50044850-09b73800-008a-11e9-8493-a9405476d93d.png)

It seems as if the later ...92 is the "species", and ...49 is the actual article/dataset where it has been published.

From the outset this is not clear, and I would suggest that you mark this accordingly.
Also, I find it a pitty that you don't show the images of this species in the "species" view

**Comment by ahahn-gbif** [comment]
Hi Donat, with the long reference name in the "published in" part, it is not as obvious as in other cases, but one of these is the GBIF backbone view of the taxon (https://www.gbif.org/species/9387792), the other one is the name "according to source" (https://www.gbif.org/species/127719449). You can recognize this, i.a., by the "view in GBIF backbone" label that you find on the latter, but not on the former, and the "appear in 1 checklist dataset" block lower on the page on the backbone version that does not show on the source dataset view.  This is a bit more transparent if you compare the two species pages for e.g. Picea abies: https://www.gbif.org/species/5284884 for the backbone view, https://www.gbif.org/species/112581995 for the Catalogue of Life that this is based on.
Best, Andrea
