### ISSUE TITLE
Gallery contain weird species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1699]
**Gallery contain weird species**

When demonstrating the Fomitopsis page to a BES 2018 delegate, we discovered many photos from different species in the gallery, such as Piptoporus betulinus. Why is that?

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/155097bddf36c925a12a498cc9172314:79e3f24bb9e1d1eb6af9c0cb3d1354f2d7393e9cebcbc178ac1ed8294a6ea6a894ae43c6c8394812a85dcb53e721baa14f492f0cd823f2ef9c2bfd3ddad9f8c3)
Referer: https://www.gbif.org/occurrence/gallery?taxon_key=2523631&year=2016,2018
Window size: width 1270 - height 603
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-18T10:22:17.230Z',mode:absolute,to:'2018-12-18T10:28:17.230Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-18T10:22:17.230Z',mode:absolute,to:'2018-12-18T10:28:17.230Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
Ok, we have quite a serious issue here, I think, which will be continue in fungi especialy and I suspect with other taxa, too. If we form a gallery of the synonym taxa at the species to species level, it is ok as you end up with more or less ok mixed gallery. If you do the same at the genus level, we should perhaps limit the gallery formation only to the child taxa of the valid genus name and NOT display children taxa of the synonimized genus name (same principle for the taxa above genus). I am happy to discuss this in the office with clearer examples and demo. http://www.speciesfungorum.org/Names/GSDSpecies.asp?RecordID=101927

**Comment by jhnwllr** [comment]
@dschigel any objection to closing this now?
