### ISSUE TITLE
Diamma Westwood, 1835: taxonomic status "doubtful"?

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/portal-feedback#1700]
relating to #1697:
Unclear why the entry at https://www.gbif.org/species/4674056 is flagged as "doubtful". There is a homonymy issue with https://www.gbif.org/species/9466120 which is resolved, but Diamma Westwood, 1835  is not listed as "accepted" either. According to the source (IRMNG: http://www.irmng.org/aphia.php?p=taxdetails&id=1318246), it is.

**Comment by ManonGros** [comment]
This is because the name is a genus without any species. See: https://www.gbif.org/faq?question=what-does-the-taxon-status-doubtful-mean-and-when-is-used
