### ISSUE TITLE
subtitle misleading

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1704]
**subtitle misleading**

It is very useful to have all participants in a single list, however the subtitle is misleading as the list is a mix of countries and organisations. Please correct the subtitle and update the paragraph below accordingly. I hope the very useful list stays as is.

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/efe4e52187e610e18300b65428758229:6b4872a06ad3ba86b701663254bb48cdb6973f15a6949dc2cef997355efffd3a5e2f7480ff8746cb3ade030698f65dbc27d6cb198038b067184da9f275a3da1e)
Referer: https://www.gbif.org/the-gbif-network/participant-organisations
Window size: width 1600 - height 894
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-21T14:00:04.599Z',mode:absolute,to:'2018-12-21T14:06:04.599Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-21T14:00:04.599Z',mode:absolute,to:'2018-12-21T14:06:04.599Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
I updated the page, and the countries disappeared... it would nice to have a single alphabetic list, but the subtitle issues is now gone.

**Comment by timhirsch** [comment]
Like this one? https://www.gbif.org/the-gbif-network
