### ISSUE TITLE
Political Geographic  information

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1706]
**Political Geographic information**

I want to download data from Pakistan that has fields for the different political entities so that I can extract records for the Province, even perhaps Districts. I have tried both interpreted and Darwin Core downloads and neither has a geographic unit between country and locality. How can I obtain data with the intermediate levels. I know I have done it in the past.
Mary

-----

User provided contact info: mary.barkworth@usu.edu
System: Chrome 71.0.3578 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/6438b44d8513910be6d7bc29c3af8db3:5ae8f3244fde6ee1b346406fa6b39e88596e89cfe7e0aa0c1d1eaee677ff19e61957c3cb603e6e4a5e29d99de85654c4f0f9634e7bb3525ce514cec6d55d578e)
Referer: https://www.gbif.org/
Window size: width 2133 - height 1042
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-22T14:10:20.821Z',mode:absolute,to:'2018-12-22T14:16:20.821Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-22T14:10:20.821Z',mode:absolute,to:'2018-12-22T14:16:20.821Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Email response:
You may try the field “stateProvince”, e.g.

https://www.gbif.org/occurrence/search?country=PK&taxon_key=7707728&state_province=punjab&advanced=1
