### ISSUE TITLE
Burrowing owl in  mid-Pacific

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1707]
**Burrowing owl in mid-Pacific**

Coordinates set at 0, -99 and no country specified in data. The publisher is from Mexico so is probably a Mexican occurrence, but there is no useful locality information.

-----

System: Chrome 71.0.3578 / Mac OS X 10.14.0
User: [See in registry](https://www.gbif.org/api/feedback/user/8ffae3ab6e313cbc81aac046f9143044:8bbdd1381425f6f9d4c9a7e83552cc85942a526178ddeffa3055d36592001154f529d4d8a78cf03f5cfad958abb937b5eb2c4dd6939885dca5a322c219daef5f)
Referer: https://www.gbif.org/occurrence/371041729
Window size: width 1763 - height 897
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-29T23:41:31.020Z',mode:absolute,to:'2018-12-29T23:47:31.020Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-29T23:41:31.020Z',mode:absolute,to:'2018-12-29T23:47:31.020Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The publishers have been notified.
