### ISSUE TITLE
FAQ item on what a deleted taxon mean?

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#1709]
See: https://github.com/gbif/portal-feedback/issues/1693

Should we have an FAQ entry explaining this?

**Comment by dnoesgaard** [comment]
Yes, I think that's good idea–considering I don't even know what it means ;)

@mdoering could you perhaps enlighten me?

**Comment by mdoering** [comment]
It's a deleted taxon, sth that does not exist anymore.
But we want the stable ID to still resolve to something in case someone uses them. They are gone

**Comment by dnoesgaard** [comment]
And in what would cause a taxon to be deleted in the backbone?

**Comment by mdoering** [comment]
all kinds of reasons. Mostly a false duplicate we didnt catch before or a name not found anymore in latest source datasets. Or we dropped an entire source dataset cause it was considered to add many  dirty/bad names. Or code changes that effect name/authorship matching.

**Comment by dnoesgaard** [comment]
Do we keep some sort of record of why a given taxon is deleted?

I've created a simple FAQ entry now:
https://www.gbif.org/faq?question=why-do-some-taxa-show-as-being-deleted-what-does-this-mean

Do you think it needs more information?

**Comment by mdoering** [comment]
yes, sounds fine to me.

**Comment by dnoesgaard** [comment]
@MortenHofft - technically speaking, I _could_ update the translation for "deletedOnDate" to include an in-line link to the FAQ entry, e.g.

`[Deleted on {DATE}](/faq?question=why-do-some-taxa-show-as-being-deleted-what-does-this-mean&inline=true)`

This does create a dependency and potential issues with other language translations. What do you think?

**Comment by MortenHofft** [comment]
Now shows as a popup on (?) click
![screen shot 2019-01-10 at 13 03 10](https://user-images.githubusercontent.com/6759267/50967322-19366f00-14d8-11e9-9eb6-6bdb2a4f0a26.png)

**Comment by dnoesgaard** [comment]
Thanks!
