### ISSUE TITLE
Results from Data validator

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1713]
**Results from Data validator**

Most of the things I think I understand. There are some names that should be added to the GBIF background.  RAW National Herbarium of Pakistan) is not yet a GBIF publisher. I am trying to clean things up before it makes the request.  Next week I hope.  Hmm. Cannot attach the file???? Comments and responses below. 
Go to OpenHerbarium.org and search collections for RAW (it is the top one).  
Identified date unlikely: I think the problem that only year is given. This has been a common practice in herbaria. It is quite likely. 215 would not be likely, nor 20015.
Recorded date mismatch145
I think because when the date downloads into the US, it swaps how day month year are listed but the three column format data seem fine.  Except that Symbiota enters year and month and 00 for unknown day of known month. I am converting our practices. 
Recorded date invalid71
I think these are the 00 issue. Can amend but time consuming. 
Coordinate invalid60
There is a comma in Verbatim coordinates, Will track down and FIX
Taxon match fuzzy
Trigonella cachemiriana is in Tropicos and IPNI
Calamagrostis stolizkai fixed
Oxystelma esculentum  in both Tropicos and Ipni (author (L. f.) Sm.
Vincetoxicum lenifolium – in a dissertation; will modify until published
Haloxylon griffithii subsp. wakhanicum is OK; cannot see why GBIF validator thinks that there was an additional infraspecific epithet.  
Same comment for Corydalis adiantifolia var. adiantifolia
Taxon match higherrank
Salvia aegyptiaca in both Tropicos and IPNI.
Vincetoxicum subcanescens – modified – publication in progress.

-----

User provided contact info: Mary.barkworth@usu.edu
System: Chrome 71.0.3578 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/edc5cf555c228d3c17eeef75b37c661c:a23ddc079393eb32f7d8d37e2b5fb7f8b9ea194db56127c791cdc3a0671ab3dfb30aee6851fb13690bd8f5a61942ac9a0042b19c1ab624f0d44765904bf4d920)
Referer: https://www.gbif.org/
Window size: width 1514 - height 738
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-02T21:18:57.003Z',mode:absolute,to:'2019-01-02T21:24:57.003Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-02T21:18:57.003Z',mode:absolute,to:'2019-01-02T21:24:57.003Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email CCd to Github, but it didn't seem to get through.

Hi Mary,

By just a few hours, you missed using the new version of the data validator, which has updates reflecting improvements in GBIF's date handling.

Here's a new report of the RAW dataset: https://www.gbif.org/tools/data-validator/1546511789347
> Identified date unlikely: I think the problem that only year is given. This has been a common practice in herbaria. It is quite likely. 215 would not be likely, nor 20015.

There is no longer an issue added when the date identified is only a year.
>
> Recorded date mismatch 145
> I think because when the date downloads into the US, it swaps how day month year are listed but the three column format data seem fine. Except that Symbiota enters year and month and 00 for unknown day of known month. I am converting our practices.
>
> Recorded date invalid 71
> I think these are the 00 issue. Can amend but time consuming.

This is now "Recorded date mismatch" for 72 records, those containing -00.  I'm afraid I can't accept -00 as it's ambiguous with some other systems.
>
> Coordinate invalid 60
> There is a comma in Verbatim coordinates, Will track down and FIX
I don't see this, so I think you've updated the data already.
>
> Taxon match fuzzy
> Trigonella cachemiriana is in Tropicos and IPNI
> Calamagrostis stolizkai fixed
> Oxystelma esculentum in both Tropicos and Ipni (author (L. f.) Sm.
> Vincetoxicum lenifolium – in a dissertation; will modify until published
> Haloxylon griffithii subsp. wakhanicum is OK; cannot see why GBIF validator thinks that there was an additional infraspecific epithet.
> Same comment for Corydalis adiantifolia var. adiantifolia

I think you've also fixed some of these already.

The "fuzzy" matches can be very small differences.  We have Trigonella cachem_Y_riana, Haloxylon griffithii subsp. wakhanic_a_, Corydalis adiant_h_ifolia.
>
> Taxon match higherrank
> Salvia aegyptiaca in both Tropicos and IPNI.

Yes, @mdoering I think there's an issue here. We have Salvia aegpytica L. only from a type specimen, and Salvia aegyptiAca Forssk. from another type specimen.  The first is in IPNI (with a source:  https://www.biodiversitylibrary.org/page/358044#page/35/mode/1up ), but not the second.

Thanks for the detailed report!

**Comment by MattBlissett** [comment]
With the new validator version, I think the only issue here is in the backbone.

**Comment by ManonGros** [comment]
I don't really understand the issue left here.
Why do we want to look for `Salvia aegpytica L`? It seems that the original issue concerned `Salvia aegyptiaca`, didn't it? We do have several species record matching to this canonical name.
@MattBlissett do you remember why this issue is a backbone one?

**Comment by jhnwllr** [comment]
closing because issue not actionable in current form.
