### ISSUE TITLE
GRBIO data cleaning

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1714]
**GRBIO data cleaning**

The data from GrBIO has been migrated to the registry. Before it goes live, the data would benefit from a critical eye. There is for example an iPhone commercial in there: `https://www.gbif-uat.org/grbio/collection/search?q=iphone&offset=0`

-----

User provided contact info: @mhoefft
System: Chrome 71.0.3578 / Mac OS X 10.11.6
User: [See in registry](https://www.gbif-uat.org/api/feedback/user/9548702adc7532ee42ad5178a80b5e26:f671a982e4fa3621d64de378365af071c5d4e3f19e9e2389e42b31886c9703bf652a13d25d79749d1c5a9a97c5cb6e1779db7920af720f15999e78363b6a232a)
Referer: https://www.gbif-uat.org/grbio/collection/search?q=iphone&offset=0
Window size: width 1720 - height 1206
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-03T10:45:07.417Z',mode:absolute,to:'2019-01-03T10:51:07.417Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-03T10:45:07.417Z',mode:absolute,to:'2019-01-03T10:51:07.417Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
At first glance, staff members data seems kind of dodgy—all of the names are in the fname column, despite the presence of the lname one. Names are also mixed in with titles and institutions, and at the back of the list there are a lot of entries where the country appears to be 'country.'

I also have concerns about adding searchable names index of this scale without considering how to make this GDPR compliant (sorry).

Collections and institutions lists look much better, but both seem a bit randomly ordered. Is it possible to allow users to sort them by column—and then to make our own default an alphabetical sort on the name in both tables?

Yes, it will definitely be worth a news story when it's ready to go.

**Comment by MortenHofft** [comment]
Thank you Kyle

No country showing as `country.` was me naively assuming that country was always present. That is fixed and in UAT.

As for sorting and search options, I believe the current scope is to get it live, and then later improve the search experience. Currently there is no such options in the API.

**Comment by ahahn-gbif** [comment]
Names:
- the full list of staff is currently also publicly available for download from http://scicoll.org/grbio_error.html. I realize that GDPR is more of a problem after migration though
- staff names, in the original, are a single field, "Staff Member Full Name". If we need to atomize those going forward, that will be for us to handle. I would not give this top priority, though, and I would not consider it a blocker for release
- contacts are listed on the detail pages for collections and institutions, as appropriate. @kcopas Is this also a concern, or is it the full, searchable list that causes headaches? Should we consider removing the "Staff Member" searchable full listing, at least for the first release, as long as contact information is still available through the institution and collection records?

**Comment by kcopas** [comment]
@MortenHofft and I spoke this morning. I don't think we need to defer the contacts, but we should have some clear and transparent messaging in place for the first phase here. I'll be responsible for that and will prepare it ASAP (I will likely be the blocker in the short term). It's important and existing information in the first instance.

However, I think that GDPR should lead us to consider following up with the collections contacts later to secure their explicit permissions, particularly when the planned additional functionality rolls out.

**Comment by kcopas** [comment]
Priority addition for staff member info in the next appropriate phase of GRBio: use ORCID IDs.

**Comment by kcopas** [comment]
Otherwise, text and translation files are ready, from my perspective. 

Should we try to crank out a news item this week?

**Comment by ahahn-gbif** [comment]
Marcos changed the iPhones entry in the version at http://api.gbif.org/v1/grbio/collection/f9070c8f-7727-4c47-bb30-e1539dd088ec. I had opted for just replacing name and description with a placeholder and trying to verify with the editors, as this seemingly once was a valid entry and I was not sure about referential issues with removing. If this does not make sense (or the placeholders), we may still want to opt for delete.

Other than that, I have not spotted any obvious issues in Institution or Collection entries. The database contains a number of duplicate entries (e.g. University of Helsinki, or InstitutionCode MU) that will require consolidation, but this is an editorial process that, at least at this point, is not on us.

**Comment by myrmoteras** [comment]
looking at GrBIO online, the individual collection pages list Identifiers, such as Ihttp://grbio.org/cool/71qz-j715. But they do not resolve and thus are misleading?! 

Is there a plan to create an identifier that could be used for it?
