### ISSUE TITLE
Sanity check GRBIO pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1716]
**Sanity check GRBIO pages**

@asturcon , @fmendezh @timrobertson100 is this what you imagined? Does it reflect the content and the APIs fairly? If so I will put in in prod, once the data has been cleaned and comms have approved.

-----

User provided contact info: @mhoefft
System: Chrome 71.0.3578 / Mac OS X 10.11.6
User: [See in registry](https://www.gbif-uat.org/api/feedback/user/a1da66f894f2f8223dffa77327191ba2:1ec81a48e6c5232f4bdbbbbd9c976f8a17fafa985d5187c51ad500090cf6f56c5a352cb7d2a4bbfd29f26feca19d75b9feb31222753857ae782107402d2c4257)
Referer: https://www.gbif-uat.org/grbio/institution/search
Window size: width 1720 - height 1206
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-03T10:56:14.314Z',mode:absolute,to:'2019-01-03T11:02:14.314Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-03T10:56:14.314Z',mode:absolute,to:'2019-01-03T11:02:14.314Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by asturcon** [comment]
The only thing that I'm not sure about is the "Additional affiliate collections" in the person page. Shouldn't we call it "Name of primary collection" instead? That's the name they have in the GRBIO site(http://dev.grscicoll.org/staff-member/gregor-aas), but it doesn't have to be exactly the same. Also, in the model it's a single value, not a list.

**Comment by MortenHofft** [comment]
This seem to have been set on indefinite hold
