### ISSUE TITLE
USU:UTC

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1718]
**USU:UTC**

Ed Gilbert pointed out that USU:UTC can now send data to you from SEINet. What I have long since lost track of it the GBIF key for the collection.  Please would you send it to me or, if you prefer a new one. We had sent data to you possibly back in the digger protocol days but the connection has been broken for several years. Once we have the key, it will be restored. The present director is Paul Wolf (paul.wolf@usu.edu). He is quite happy for me to take care of this issue.
Question 2: I am assuming that we can use the same key for sending you our data from all 4 symbiota networks to which we contribute. There is NO overlap in catalognumbers. We have been using preprinted barcodes since before GBIF was started.  
I shall feel less of a hypocrite once USU:UTC is once again sending you data.

-----

User provided contact info: mary.barkworth@usu.edu
System: Chrome 71.0.3578 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/71f96e0e437844b3dca77a4be41009fb:36d965e61d6907e26da5b70a7bf7383c796c678a20466f0b211faa7934e0d8b2518b167820fd1f930aa97d06cb77c27d3e68398e817c5ce9f9037188ddf38127)
Referer: https://www.gbif.org/
Window size: width 1536 - height 754
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-04T22:04:54.835Z',mode:absolute,to:'2019-01-04T22:10:54.835Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-04T22:04:54.835Z',mode:absolute,to:'2019-01-04T22:10:54.835Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Contacted via email from helpdesk.
