### ISSUE TITLE
Impossible to query with catalognumber in advance search?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1720]
**Impossible to query with catalognumber in advance search?**

We are trying to search for a specific occurrence record with a certain catalognumber. In our case we try to find a specific sound recording of a blackbird (Turdus merula) in the Xeno-canto database. Querying with field “catalognumber”does not seem to work. We therefore tried the overall search field, but gives different number of results.

`https://www.gbif.org/occurrence/search?q=XC372786&dataset_key=b1047888-ae52-4179-9dd5-5448ea342a24&taxon_key=2490719&advanced=1`  gives 3 results

`https://www.gbif.org/occurrence/search?q=XC372086&dataset_key=b1047888-ae52-4179-9dd5-5448ea342a24&taxon_key=2490719&advanced=1` gives 2 results

Do we do something wrong or is it not possible to perform an exact search query?

-----

User provided contact info: jeroen.creuwels@naturalis.nl
System: Chrome 71.0.3578 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7d13ba764da02bdc310a6dfb1cc68d58:98a43f4c1f3846ebbf997cb2adfa93906033b5e19e37a60da5862480395836dca90616ed35e171dd35cc24c3c70251b28ad856e5be544f207b1b0433118a15a5)
Referer: https://www.gbif.org/occurrence/1934972582
Window size: width 2322 - height 1117
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-08T15:32:39.630Z',mode:absolute,to:'2019-01-08T15:38:39.630Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-08T15:32:39.630Z',mode:absolute,to:'2019-01-08T15:38:39.630Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Looks to me like it works.

searching for catalog number from the interface:
https://www.gbif.org/occurrence/search?catalog_number=XC372786&dataset_key=b1047888-ae52-4179-9dd5-5448ea342a24&advanced=1
gives [one result](https://www.gbif.org/occurrence/1934972734) which is correct

searching for the catalog number as a text string will do a fuzzy matching and will therefore return many more results
https://www.gbif.org/occurrence/search?q=XC372786&dataset_key=b1047888-ae52-4179-9dd5-5448ea342a24&advanced=1

you write
> Querying with field “catalognumber”does not seem to work.

Just so we might learn how to improve documentation. How did you perform this query? using the API? Altering the url in the website? Or by using the interface (as in above link)?

In the interface it should be as simple as entering the number in the filter (there are many it it might get lost). If that didn't work, then it sounds like we have a bug. If you still believe this is a bug, please let me know, then I will reopen the issue.

![screen shot 2019-01-08 at 21 09 32](https://user-images.githubusercontent.com/6759267/50856024-e2524300-1389-11e9-904c-3af596290c94.png)

**Comment by MortenHofft** [comment]
Thanks for clarifying. Probably the suggestion was too slow to show up.

![screen shot 2019-01-09 at 12 07 43](https://user-images.githubusercontent.com/6759267/50895743-3c451e00-1407-11e9-8e06-bea7df5122b1.png)
