### ISSUE TITLE
link to the 2019 call

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1721]
**link to the 2019 call**

Please change the current wording for the link to the Russia 2019 call to:

Data mobilization in European Russia programme: the 2019 call

or similar. Kindly keep the link active.

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/635d1c5112f0f60977ccdba99b728f93:aa183df043f8289eeb487ed19c54f1f5b4eb572224c40ca3eb04d91a41bcc71545fb65ca18ffd6b9b45b51db739a331e5babf9498cbb09d358e5109b277f656f)
Referer: https://www.gbif.org/programme/3ilFFs3JdY2SqmyCuac0uc/data-mobilization-in-european-russia
Window size: width 2133 - height 1094
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-09T14:10:43.630Z',mode:absolute,to:'2019-01-09T14:16:43.630Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-09T14:10:43.630Z',mode:absolute,to:'2019-01-09T14:16:43.630Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
Yes, thanks. Any suitabel wording with a meaning that this is call is now closed and archive and a working lik to the call page (no edits in the actuall call page needed)

**Comment by dnoesgaard** [comment]
Done.
