### ISSUE TITLE
record  labelled as "Recorded date mismatch" although there is no mismatch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1723]
**record labelled as &quot;Recorded date mismatch&quot; although there is no mismatch**

The system interpret the original `eventDate`, `Feb-18` as `2018-02-01T00:00:00`, and then identifies a mismatch with the date given in `month` and `year`.

-----

User provided contact info: @ManonGros
System: Safari 12.0.2 / Mac OS X 10.14.2
User: [See in registry](https://www.gbif.org/api/feedback/user/edba0fa65b9df328ca2617d9f63ec59c:b3d9587fe8cbfad0bcd633592d1f533a35b38dc78e14fb157e5aa397573374c2d4d360f002490594829a31a395f30c2c500a7083b0be25650568ab9a020aed4c)
Referer: https://www.gbif.org/occurrence/1919496537
Window size: width 1622 - height 882
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-11T10:35:35.408Z',mode:absolute,to:'2019-01-11T10:41:35.408Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-11T10:35:35.408Z',mode:absolute,to:'2019-01-11T10:41:35.408Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
`Feb-18` isn't a valid, ISO date — is it February 2018, or the 18th February?

The bug is probably that `Feb-18` is interpreted at all.

**Comment by MattBlissett** [comment]
I think this one is now OK — the issue is there because "Feb-18" isn't a valid ISO date, but the result is correct anyway.
