### ISSUE TITLE
Time to refresh the value for an updated DWCA (article)

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#1725]
how long does it take to update the values for an exiting DWCA we submit from Plazi in GBIF? It would be helpful to know this  to make sure that changes on our side also show up in GBIF.

**Comment by MattBlissett** [comment]
This varies according to the queue of other datasets that might be ahead of yours.  You can see the queue here: https://management-tools.gbif.org/crawling-monitor -- click "Live view".

After we receive the submission from Plazi, we wait 60 seconds (in case of further changes to the same dataset), then add it to the ingestion queue. For a small dataset typical of Plazi, and if there's nothing ahead in the queue, it would be done within 2 minutes.

It then takes up to 10 minutes for the web caches to expire.
