### ISSUE TITLE
name appearances for new species

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#1726]
Just to understand your modus operandi. 

In this occurrence record https://www.gbif.org/occurrence/1913889620 the name of the occurrence is Tingis, as well as in the list of the holotypes https://www.gbif.org/occurrence/search?offset=0&dataset_key=fd8ba24f-4d68-431c-81f5-e924906aed5d&type_status=HOLOTYPE of the article, but here https://www.gbif.org/species/148421568  it is the name as in the publication (with the exception that in the treatment it has also the subgenus given) .

Does this mean, that this species name is in your provisional taxonomic backbone, but not in the updated taxonomic backbone yet?

But when you check the holotypes list, only the Tingis  is without species epithet, all the others have it?!

**Comment by thomasstjerne** [comment]
As for 2., its showing the canonical name until the formatted name returns from the portals name formatter (Which may need adjustment on this type name?).

**Comment by mdoering** [comment]
The occurrence has a name our backbone does not know about, so its matched to the genus only.
The occurrence page shows that as Taxon match higherrank and the name is yellow.

The species link https://www.gbif.org/species/148421568 is not to the backbone, but the very Plazi checklist the occurrence comes from - so it has it. It will be a source for the backbone when we rebuild it, but up to now it has not been used (as we only build the backbone every 6 month or so).

Infrageneric names are removed from bi- or trinomials when we represent them in their canonical form.
It is not lost though as you can see here: https://api.gbif.org/v1/species/148421568

```
}
  "key": 148421568,
  "nameKey": 19892394,
  "taxonID": "FB5E87A0082A3F03FF263A480588F557.taxon",
  "kingdom": "Animalia",
  "phylum": "Arthropoda",
  "order": "Hemiptera",
  "family": "Tingidae",
  "genus": "Tingis",
  "species": "Tingis bishopae",
  "kingdomKey": 151961351,
  "phylumKey": 151961352,
  "classKey": 151961353,
  "orderKey": 151961354,
  "familyKey": 151961355,
  "genusKey": 151961363,
  "speciesKey": 148421568,
  "datasetKey": "fd8ba24f-4d68-431c-81f5-e924906aed5d",
  "parentKey": 151961363,
  "parent": "Tingis",
  "scientificName": "Tingis (Caenotingis) bishopae Guilbert & Guidoti 2018",
  "canonicalName": "Tingis bishopae",
  "authorship": "Guilbert & Guidoti, 2018",
  "nameType": "SCIENTIFIC",
  "rank": "SPECIES",
  "origin": "SOURCE",
  "taxonomicStatus": "ACCEPTED",
  "nomenclaturalStatus": [
    
  ],
  "numDescendants": 0,
  "references": "http://treatment.plazi.org/id/FB5E87A0082A3F03FF263A480588F557",
  "lastCrawled": "2019-01-11T12:25:58.291+0000",
  "lastInterpreted": "2019-01-11T15:21:33.449+0000",
  "issues": [
    "BACKBONE_MATCH_NONE"
  ],
  "synonym": false,
  "class": "Insecta"
}
```

**Comment by ManonGros** [comment]
The question seem to have been answered and the PLAZI mediated checklists has been integrated in the latest backbone taxonomy.
I am closing the issue.
