### ISSUE TITLE
https://www.gbif.org/citation-guidelines missing name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1727]
**`https://www.gbif.org/citation-guidelines` missing name**

Dear, the foto used on the Citation guidelines (`https://www.gbif.org/citation-guidelines)` is missing the name of the hoverfly specie (Diptera:Syrphidae) in the photo! Helophilus pendulus is the fly on the Chicory flower.

Gbif stand for all species so please add this info too ;-)

-----

User provided contact info: bwakkie@syrphidae.com
System: Firefox 64.0.0 / Linux 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/18093bb613e575092f2fcf744ca1468d:5b4f5ad6ac171ac9be1daa7d4618c3c5e7ae9fd9a0bb75c1bdf3df9695fc2c840b5d8265fb0d57c95fd8cdce54f4958fd69501fe44fa77e93d33a5b0da067592)
Referer: https://www.gbif.org/citation-guidelines
Window size: width 1920 - height 1051
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-12T16:02:13.225Z',mode:absolute,to:'2019-01-12T16:08:13.225Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-12T16:02:13.225Z',mode:absolute,to:'2019-01-12T16:08:13.225Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Thanks @bwakkie, I've added the missing species to the caption now.
