### ISSUE TITLE
Plazi: species / dataset linked back to Plazi/TreatmentBank

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#1730]
like in the previous issue https://github.com/gbif/portal-feedback/issues/1728, here https://www.gbif.org/species/149668646 is no link back to the treatment and TreatmentBank at Plazi. I think there should be the respective persistent Identifier included so that a user could follow back to the source, in this case http://treatment.plazi.org/id/03A10B47-FFE7-FFA7-FDDB-FBCAFB9EFBAC

I think this is important so that somebody could follow back step by step to the source. The link to Plazi is important because it is there where errors can be corrected.

It could also be argued, similarly, that from the dataset record https://www.gbif.org/dataset/5dfd4ff4-6c8b-47f4-9aa7-0f6b1b2af967 there should be a link back to the respective Plazi summary page http://tb.plazi.org/GgServer/summary/FF98733FFFF8FF86FF85FF8AFFF2FFB8

For example, here 
![image](https://user-images.githubusercontent.com/4609956/51143353-a79b4f80-184e-11e9-9cb3-e6aa4e722882.png)

a second alternative identifier could be added with the one above

**Comment by MortenHofft** [comment]
> here https://www.gbif.org/species/149668646 is no link back to the treatment and TreatmentBank at Plazi. I think there should be the respective persistent Identifier included so that a user could follow back to the source, in this case http://treatment.plazi.org/id/03A10B47-FFE7-FFA7-FDDB-FBCAFB9EFBAC

![screen shot 2019-01-15 at 13 15 54](https://user-images.githubusercontent.com/6759267/51180137-d6094100-18c7-11e9-867e-aff2e3bb9ef0.png)

The REFERENCE TAXON links to http://treatment.plazi.org/id/03A10B47FFE7FFA7FDDBFBCAFB9EFBAC

**Comment by MortenHofft** [comment]
If I understand the issue correctly, then the links are there, but difficult to find?

**Comment by myrmoteras** [comment]
looks like - sorry, I wasn't aware of the HOME PAGE

**Comment by MortenHofft** [comment]
Np - the problem with these pages are that there are so many links, that things easily get lost. Or perhaps it is just the UI choices.
