### ISSUE TITLE
Replace "Species" on GBIF.org home page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1731]
**Replace &quot;Species&quot; on GBIF.org home page**

Having to manually update the Species count page is tedious, and the page not exactly visited a lot. It has received 168 unique page views in the last 3 months.  In comparison, the privacy policy and health page received 1,154 and 571 page views, respectively.

I suggest replacing the link on the home page with something more interesting and easy to manage, e.g. number of registered users?

-----

User provided contact info: @dnoesgaard
System: Chrome 71.0.3578 / Mac OS X 10.14.2
User: [See in registry](https://www.gbif.org/api/feedback/user/a371e3ffb5fc31a9c16027b0271559d7:f5c1f6544b70b9c65b45ad5eb283cdf34660742951c4cf9c423af1ac81511bbd26a4ac2588ebafc313761dd9781132a18886668bb119ce779482cf7f23b8e5c0)
Referer: https://www.gbif.org/
Window size: width 1948 - height 1173
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-15T09:39:14.738Z',mode:absolute,to:'2019-01-15T09:45:14.738Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-15T09:39:14.738Z',mode:absolute,to:'2019-01-15T09:45:14.738Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Hi @dnoesgaard, which page is it that you are referring to - the link underneath the header image, sitting on the right of occurrence records, datasets, and publishing institutions (i.e. the counts at the bottom of https://www.gbif.org/about-species-counts)? If so, it will be more of a policy decision than one of web traffic (@dhobern?)

If I remember correctly, the page was introduced exactly _because_ these numbers are hard to get at, and because we had struggled with other approaches that all gave a subtly wrong impression and invited criticism and an assumption that we did not know what we were talking about. After all, the backbone and how we handle integration of taxa is a major part of the data behind gbif.org

I guess I am trying to say that we would need to maintain this information anyway, whether it is prominently linked from the front page or not. If it is a pain to maintain, we should review whether there is an easier way to do so.

**Comment by dnoesgaard** [comment]
I think that having the species "count" on the front page doesn't make a lot of sense when it doesn't show any numbers. IMO it breaks the balance/symmetry of the page:

![screenshot 2019-01-24 at 11 04 14](https://user-images.githubusercontent.com/21358085/51670974-33884680-1fc8-11e9-89df-2513eb5d6dcc.png)

So my suggestion would be to replace it with something else, e.g. number of users, downloads, etc. (that can be obtained automatically)

With that being said, I recognize that the [About species counts in GBIF](https://www.gbif.org/about-species-counts) serves a purpose in explaining how we deal with species and our view of "coverage". In its current form, however, it refers to a practice that ended a while ago. I think its content could be updated to a more permanent form and perhaps placed within a more thorough description of the backbone and how it's compiled? We could also link to the page from within more specific contexts, e.g. [species searches](https://www.gbif.org/species/search) where actual numbers are shown.

And yes, having to update the table is a total nuisance ;)

**Comment by timhirsch** [comment]
I meant to comment on this earlier. I agree with Daniel that the species non-count on the homepage is distracting. I wonder, however whether number of users or downloads would be the best headline metrics here. Perhaps rather number of research papers citing use of GBIF? That would also have the benefit of giving some prominence to our literature resources which are not so easy to find from the homepage.

As a parallel issue regarding species numbers, I find an increasingly common request is 'how do I see the number of species in a particular occurrence search result/country/dataset etc.?' I realise this is not trivial (e.g. handling records at other taxon ranks) but I think it would be a popular feature.

**Comment by dnoesgaard** [comment]
Oh, I hadn't even thought about use (embarrassing!). Great idea.

The count is available from the content API: https://www.gbif.org/api/resource/search?contentType=literature&literatureType=journal&relevance=GBIF_USED&peerReview=true&limit=0

And it could link to literature search: https://www.gbif.org/api/resource/search?contentType=literature&literatureType=journal&relevance=GBIF_USED&peerReview=true (which gives us a direct link to literature on the homepage, yay!)

(applying standard filters, i.e. peer-reviewed journal articles with substantive use)

**Comment by dnoesgaard** [comment]
Labeling the number is tricky. This is probably my preferred suggestion:

![screenshot 2019-01-24 at 13 45 56](https://user-images.githubusercontent.com/21358085/51679153-69d0c080-1fde-11e9-965a-0fc471c18ec4.png)

**Comment by timhirsch** [comment]
I just blind-tested it with someone outside GBIF and she correctly identified the meaning, so I think the wording is fine unless someone thinks of something better. While we make that change, it may be good to re-label the third metric 'Data publishing institutions' as this can sometimes be confusing for those not familiar with our 'data publisher' concept.

**Comment by dnoesgaard** [comment]
Thanks @MortenHofft!

The change is live on https://www.gbif-staging.org/ in case anyone wants to check it out.

I do think I'll keep this one open so we can work out what to do with the now orphaned [About species counts in GBIF](https://www.gbif.org/about-species-counts) page.

**Comment by dnoesgaard** [comment]
I've created a simple FAQ entry linked to the "species count" article for now:

https://www.gbif.org/faq?question=how-many-species-are-in-gbif
