### ISSUE TITLE
Ingesting issues - no ingests this year and "Ingest Now" does nothing

### ISSUE THREAD

**Issue by jrdh** [gbif/portal-feedback#1732]
According to the [ingest history](https://management-tools.gbif.org/crawl-history?uuid=7e380070-f762-11e1-a439-00145eb45e9a) for the NHM's specimen collection on GBIF we haven't been ingested since 05/12/18. I attempted to request an ingest using the "Ingest Now" button on the [dataset page](https://www.gbif.org/dataset/7e380070-f762-11e1-a439-00145eb45e9a) but this just showed "ADDING TO QUEUE" and nothing seemed to happen after that.

Are there any ongoing issues with the ingest system or is this something specifically problematic with our dataset?

**Comment by MortenHofft** [comment]
Thank you for reporting it. I can confirm that it doesn't work for me either; not in website and not in the registry. There is no error messages and it doesn't show up in the crawling monitor after being started
https://management-tools.gbif.org/crawling-monitor

**Comment by jrdh** [comment]
This problem is still ongoing and the restart of the crawler mentioned in the other issue doesn't seem to have changed anything. Any update on when this might be resolved (sorry to pester!)?

**Comment by jrdh** [comment]
Looks like 2 ingests went through on the 21st, thank you!

**Comment by MattBlissett** [comment]
Yes, there was some corrupt data in the place we record ingestion state, so the system wouldn't start a new ingestion process, but also wouldn't "end" the corrupt one.

**Comment by MortenHofft** [comment]
Wow those are wonderful images!
