### ISSUE TITLE
Future functionality tests to take place with live GBIF.org, not UAT

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1733]
**Future functionality tests to take place with live GBIF.org, not UAT**

I am not sure if I understood the case well, but looks like the sucessful tests to publish from PlutoF to GBIF worked in UAT, but validation tests and ingestions failed upon the attempts to publish to GBIF.org.
@laurarussell @thomasstjerne @ManonGros 

Suggestion:
If UAT has softer requirements than real GBIF publications, we could

* carry out future test in UAT and in GBIF.org (and then kill these test publications)
* make UAT to be as strict as GBIF.org to fully mimick the publication experience

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/f42545e3f73fa85ba785d393ab5795b9:de2d53ddd6b7051ff266de8356d8f9cb1a76830736bdd02b08183f472548bd7be8de165204895c4805577c57a071235fcde764c1ee3c29ec9bbff6d86b916603)
Referer: https://www.gbif.org/dataset/ade32c37-fdce-450a-be18-87bdb792c0b1
Window size: width 1536 - height 737
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-15T15:35:55.933Z',mode:absolute,to:'2019-01-15T15:41:55.933Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-15T15:35:55.933Z',mode:absolute,to:'2019-01-15T15:41:55.933Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
UAT is supposed to be identical to production, if that's not the case we (Informatics) need to fix that.

Testing in production is strongly discouraged. It generates real DOIs, and real entries (marked as deleted) in the registry, and records may end up in downloads during the test period.

**Comment by MattBlissett** [comment]
I've restarted the crawler, which we (I) forgot to do in production last week.
