### ISSUE TITLE
possible bug in plant variety author

### ISSUE THREAD

**Issue by tmyersdn** [gbif/portal-feedback#1734]
Hi - interesting concatenation error in the variety author name:

[https://www.gbif.org/species/5623676](https://www.gbif.org/species/5623676)
shows _Mammillaria spinosissima_ var. _sanguinea_ (F.Haage) F.Haagex Brandegee
but the IPNI link shows
_Mammillaria spinosissima_ var. _sanguinea_ (Haage) Haage **ex** Brandegee

so it looks like the ex Brandee got concatenated onto the Haage, and an 'e' went missing :) (apologies if this is just a typo)

**Comment by ManonGros** [comment]
The entry in the dataset (Darwin Core Archive) contains the correct spelling.
Why would we show `Mammillaria spinosissima var. sanguinea (F.Haage) F.Haagex Brandegee`? I tried to paste `Mammillaria spinosissima var. sanguinea (Haage) Haage ex Brandegee` in our paper and it works fine.
I don't really know why we display an incorrect name.

**Comment by ManonGros** [comment]
The name is now Mammillaria spinosissima var. sanguinea (J.N.Haage ex Regel) Brandegee in the new backbone.
