### ISSUE TITLE
BINs as synonyms or unspecified rank?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1735]
**BINs as synonyms or unspecified rank?**

I suggest we review how we treat BINs compared to how we treat UNITE SHs. Currently BINs are shown as synonyms of their parent taxa, and I think this may not always be the case. Perhaps we can align this with UNITE and loosen a bit the dispolay to show BINs under thir parent Latin taxa as unspecified rank, and follow this practice of all other OTUs. The result needs to read "belongs to", but no specific systematic rank or more specific relations shown. @mdoering @thomasstjerne 

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/3eae844e3ec78b6b8a044bb96d9fdc9c:d578c774673621606a02be4431d6f3947fd6dea5b3b1a74cbeb81a233c80c1465e5971b8ccf26c88bea113afc37a45a9fa35195dab5176e2c433d3950156c7fb)
Referer: https://www.gbif.org/species/search?dataset_key=4cec8fef-f129-4966-89b7-4f8439aba058&name_type=OTU&advanced=1
Window size: width 2560 - height 1313
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-16T09:06:05.806Z',mode:absolute,to:'2019-01-16T09:12:05.806Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-16T09:06:05.806Z',mode:absolute,to:'2019-01-16T09:12:05.806Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
Yes, this is the long term plan. I am wondering the the display of the currently published data. Does it depend on how data is published, or on how backbone is assembled?

**Comment by mdoering** [comment]
both I believe

**Comment by ManonGros** [comment]
@dschigel @thomasstjerne
I am don't really see how the structure of the iBol DwCA is different from the UNITE one. They both have:
* taxonID
* parentNameUsageID
* taxonRank
* reference

If any anything, the iBol dataset has more information than the UNITE one. Unless I am missing something?
If so, please let me know. Otherwise, I suggest to close this issue.

**Comment by thomasstjerne** [comment]
This issue is outdated and was created before the major update of the BOLD bins dataset and the inclusion of them in the GBIF backbone.
