### ISSUE TITLE
Why this WKT is invalid?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1736]
**Why this WKT is invalid?**

Using both WKT, the first one is not working (GBIF say "invalid WKT or GeoJSON) and the second is ok:

POLYGON((-4.94872 36.58912,-4.94903 36.58831,-5.01985 36.55400,-5.04613 36.57450,-5.04613 36.77450)) => Not working

POLYGON((-4.67471 39.73619,-2.25497 39.73619,-2.25497 40.70298,-4.67471 40.70298,-4.67471 39.73619)) => Working

Thank you.
Regards

-----

User provided contact info: herbariomgc@uma.es
System: Chrome 71.0.3578 / Windows 8.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/635519ab0e19a20b04e546536fd7f73a:c124b46a5a6e03fe39071cf8b91a0c0c9470b8db9a972099b7fa7932db076af0ec9b5a9ea49f8cdeaac6200cb951d299eb1c2e6d4b3d18781c75f305e58a1fd8)
Referer: https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&advanced=1
Window size: width 1280 - height 882
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-16T12:48:37.615Z',mode:absolute,to:'2019-01-16T12:54:37.615Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-16T12:48:37.615Z',mode:absolute,to:'2019-01-16T12:54:37.615Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
wkt must end and start at the same point. the first one isn't
