### ISSUE TITLE
Replace "Learn more" links with FAQ pop-ups

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1738]
**Replace &quot;Learn more&quot; links with FAQ pop-ups**

Please replace the two "learn more" links with FAQ pop-ups:

CSV: `https://www.gbif.org/faq?question=csv-download`
DwC: `https://www.gbif.org/faq?question=dwc-download`

This is in line with https://github.com/gbif/portal-feedback/issues/1352

-----

User provided contact info: @dnoesgaard
System: Chrome 71.0.3578 / Mac OS X 10.14.2
User: [See in registry](https://www.gbif.org/api/feedback/user/07d1ef8abc5aa1c81429f0344e682f46:7adee5d14e7abb1afaa9d678f0edfc5985f61212ba1bf3b18d98d740d478b9011dca334edd4aaf81764b5ea608f983f89ae2e593a197a96c1974d584b6c234a9)
Referer: https://www.gbif.org/occurrence/download
Window size: width 2044 - height 1108
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-18T10:16:35.301Z',mode:absolute,to:'2019-01-18T10:22:35.301Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-18T10:16:35.301Z',mode:absolute,to:'2019-01-18T10:22:35.301Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
![screenshot 2019-01-18 at 11 19 58](https://user-images.githubusercontent.com/21358085/51381010-48ba2c80-1b13-11e9-953c-79b55ed5a882.png)
