### ISSUE TITLE
Several missing species in Neobuthus genus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1739]
**Several missing species in Neobuthus genus**

Source: `http://www.kovarex.com/scorpio/pdf/2018o-Neobuthus_271.pdf` (Kovařík, František; Lowe, Graeme; Awale, Ahmed Ibrahim; Elmi, Hassan Sh Abdirahman; Hurre, Ali Abdi (12 December 2018). Fet, Victor, ed. "Scorpions of the Horn of Africa (Arachnida, Scorpiones). Part XVII. Revision of Neobuthus, with Description of Seven New Species from Ethiopia, Kenya and Somaliland (Buthidae)" . Euscorpius. 271.)

Should add 7 missing species.

-----

User provided contact info: yurinikolai00@gmail.com
System: Chrome 71.0.3578 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/f22796784417e8e4d5a4eeb30d2c6ba5:64b954220d23c64fe551cb3cd124fc76f61e20a70c1e9db87e8bdd0dd21a94230643bc35cc39515a3f8dc9023e513b2ea027d24ce540cb9ea7a4e3a75d31a691)
Referer: https://www.gbif.org/search?q=neobuthus
Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-18T16:42:57.309Z',mode:absolute,to:'2019-01-18T16:48:57.309Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-18T16:42:57.309Z',mode:absolute,to:'2019-01-18T16:48:57.309Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by yroskov** [comment]
Good point. The Scorpion Files should be updated in CoL (scheduled). ~250 new species are in the source.

**Comment by ManonGros** [comment]
I checked and all the species from the publication are now in GBIF.
