### ISSUE TITLE
Problems with BID metadata-only datasets

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#174]
**Problems with BID metadata-only datasets**

First of a set of four metadata-only datasets from Togo, each which has several problems. I&#39;m not even sure they&#39;re supposed to be here, to be honest, as they refer to non-existent tables and do little to suggest anything about underlying data of the type generally served through the GBIF network.

Other three datasets are:
https://demo.gbif.org/dataset/2fb3f0a6-9e67-4c33-9be1-d9d566907c81
https://demo.gbif.org/dataset/27adc49e-d62b-4848-9257-290c3df7da47
https://demo.gbif.org/dataset/8fbc2d8f-7eb0-4e73-a36f-5dd162500b6b

At a glance:
+ Date is invalid
+ Description is in French, but the metadata language is identified as English
+ ProjectID leads the title, rather than including it in the projectID field 

With respect, all four are in desperate need of peer-review and clarification if they are to remain.

-----
fbitem-dataseteb71a9e1-a6ce-458f-bc72-4263b2236259
Reported by: @kcopas
System: Safari 10.1.0 / Mac OS X 10.12.4
Referer: https://demo.gbif.org/dataset/eb71a9e1-a6ce-458f-bc72-4263b2236259
Window size: width 1237 - height 793
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-21T13:37:16.317Z',mode:absolute,to:'2017-04-21T13:43:16.317Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-21T13:37:16.317Z',mode:absolute,to:'2017-04-21T13:43:16.317Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ManonGros** [comment]
I am in touch with the publishers about other issues but once these are solved, I will write to them about the metadata-only datasets.

**Comment by ManonGros** [comment]
Most of the datasets have been corrected, only one remains without BID ID:
https://www.gbif.org/dataset/8fbc2d8f-7eb0-4e73-a36f-5dd162500b6b

**Comment by ManonGros** [comment]
Actually, the BID ID is there, just not visible.

**Comment by MortenHofft** [comment]
it doesn't show the project page because there is so little information that I deemed it uninteresting to show:
https://www.gbif.org/dataset/8fbc2d8f-7eb0-4e73-a36f-5dd162500b6b/project
