### ISSUE TITLE
i just want to download only images so what i will do

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1740]
**i just want to download only images so what i will do**

-----

System: Chrome 71.0.3578 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/dd20b90c966dfba6055ed0c8a7d732cb:8bc30be12a892de8df52b6cf181db7b346b5cd2cfd11c128dbddc63e3944d0cec24f6a523e00642bb84cec99ecfade734585307cd954b4ed88224583fa9fa452)
Referer: https://www.gbif.org/occurrence/gallery?taxon_key=5401673
Window size: width 1536 - height 674
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-19T18:36:53.258Z',mode:absolute,to:'2019-01-19T18:42:53.258Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-19T18:36:53.258Z',mode:absolute,to:'2019-01-19T18:42:53.258Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Email response:

Please refer to this FAQ entry: https://www.gbif.org/faq?question=how-do-i-download-images-shown-in-the-gallery
