### ISSUE TITLE
are there plans to make the report from the validator downloadable,?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1741]
**are there plans to make the report from the validator downloadable,?**

would be nice to save locally and being able to see all issues (not just the first ten) and start correcting them :-)

-----

User provided contact info: DanBIF - Isabel
System: Chrome 71.0.3578 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/594847b01cd6b9dbc959eb716038dda9:7af9d03a9b3f7c797d4782e5543517f9b3600b309aa9d2d0ad37cebabf62f07ae9cfb4271a85e38cb8ad90ee55144058d81a57b63372eb165a92753fb149d94f)
Referer: https://www.gbif.org/tools/data-validator/1546511789541
Window size: width 1920 - height 1058
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-21T12:25:47.264Z',mode:absolute,to:'2019-01-21T12:31:47.264Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-21T12:25:47.264Z',mode:absolute,to:'2019-01-21T12:31:47.264Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by DanBIF** [comment]
sorry, I looked in the wrong place on github before submitting this, it seems it is already created as issue: https://github.com/gbif/gbif-data-validator/issues/69 
....but still much needed :-)
