### ISSUE TITLE
Doesen´t work

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1744]
**Doesen´t work**

-----

System: Chrome 71.0.3578 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7d5b0f1beb33a069c379706f6b23263c:eac693fc5393d0089381c53e7e142fec8ca5a262e03019d1cc490315db4c964dbe3ed045e4a02630bdb72c89df1a834930a5cb77ec334317c09a340410b0e850)
Referer: https://www.gbif.org/occurrence/download?taxon_key=5219426
Window size: width 1536 - height 754
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-22T22:12:40.037Z',mode:absolute,to:'2019-01-22T22:18:40.037Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-22T22:12:40.037Z',mode:absolute,to:'2019-01-22T22:18:40.037Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Downloads were a little slow for a while, this one took 26 minutes.

**Comment by MortenHofft** [comment]
It is intersting that the referer is not the [download page](https://www.gbif.org/occurrence/download/0029769-181108115102211)

I wonder if the redirect didn't work either?

**Comment by MattBlissett** [comment]
The user has a download for this taxon key just a few minutes before they submitted the issue. I expect they assumed it would be ready within a few minutes, and it wasn't.
