### ISSUE TITLE
Reset organization password(Environmental Protection Agency, Guyana)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1748]
**Reset organization password(Environmental Protection Agency, Guyana)**

Hi GBIF I'm a consultant hired to setup an IPT server on behalf of the Environmental Protection Agency in Guyana, South America. I'm currently at the point of associating the IPT server with an organization. Our organization is listed as 'Environmental Protection Agency' in your organization list(drop-down list) but the Environmental Protection Agency cannot remember their password. What is the procedure(if any) to reset the password for an organization listerd with GBIF? Many Thanks -ray

-----

User provided contact info: raywebspace@gmail.com
System: Chrome 71.0.3578 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/ce4e176938a755f4945b97a0e27a8302:22358654c466367484e60427bb8027d60e3e59468cfafbf2dcb0c681b3e6b1fc235d6c5b8c11e25241e9d27bad844a14a2dfb8eec3115a7db13f7e52b506ee58)
Referer: https://www.gbif.org/
Window size: width 1280 - height 913
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-23T19:45:53.574Z',mode:absolute,to:'2019-01-23T19:51:53.574Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-23T19:45:53.574Z',mode:absolute,to:'2019-01-23T19:51:53.574Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Answered through helpdesk - closing
