### ISSUE TITLE
Sharing data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1749]
**Sharing data**

I will be submitting a paper to a journal that requires my data to be publically available and I wish to use GBIF. I couldn't find a description of the format that the data should be in. Can you please indicate where I should be looking or send me the required format and where I go to submit it

-----

User provided contact info: @igrowns
System: Chrome 71.0.3578 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/92ca480702beb0ed4f93e3fe9dcab427:852b0bc5793e583fb470be0645c5ca4b695a626bc7ee8c24288b67a28d4acc5570dad91f099bb6348c9b22b391c02f3a94ceca19807cad42874d90536531cc36)
Referer: https://www.gbif.org/faq
Window size: width 1920 - height 920
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-25T02:07:05.669Z',mode:absolute,to:'2019-01-25T02:13:05.669Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-25T02:07:05.669Z',mode:absolute,to:'2019-01-25T02:13:05.669Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Sent response by email.
