### ISSUE TITLE
Occurrence match wrong/higher taxon although the scientific name is in backbone

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#1750]
The problem concerns occurrences of `Hirundo albicollis Vieillot, 1817` (see [this one](https://www.gbif.org/occurrence/1024302926) and [this one](https://www.gbif.org/occurrence/1024302924)). They are both matched to an annelid `Hirundo Catesby, 1771` although the species `Hirundo albicollis Vieillot, 1817` [exists in the backbone](https://www.gbif.org/species/9054394).

Same problem with [this occurrence](https://www.gbif.org/species/8992986) of `Hirundo vanikorensis Quoy & Gaimard, 1830` (see species page [here](https://www.gbif.org/species/8992986))

I told the publisher to specify the class as `Aves` but shouldn't the system pick the exact match instead of a different name?

**Comment by MattBlissett** [comment]
Remaining in UAT: https://www.gbif-uat.org/occurrence/1024302926

I don't know how that could have happened.

Updating the occurrence CLI and restarting it in production seems to have fixed it, but that doesn't explain why it was wrong in the first place.

**Comment by ManonGros** [comment]
Thanks! Since you were able to fix the issue, I will close it now.
