### ISSUE TITLE
Incorrect URL in 2019 Ebbe Nielsen challenge page

### ISSUE THREAD

**Issue by nickynicolson** [gbif/portal-feedback#1754]
Page URL: https://www.gbif.org/news/5POv0fV8h1tGvpI3GQwQ96/2019-gbif-ebbe-nielsen-challenge-seeks-open-data-innovations-for-biodiversity

In the final section of the page ("Past winners and past entries"), the all entries link for the 2018 prize shows a list of entries from 2016 (https://gbif2016.devpost.com/submissions)

**Comment by kcopas** [comment]
thanks @nickynicolson —nice catch!
