### ISSUE TITLE
Validator doesn't detect missing occurrence IDs

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1755]
**Validator doesn&#39;t detect missing occurrence IDs**

[This dataset](https://www.gbif.org/dataset/d83793f0-b48b-4842-b584-8ad65d73daf3) is missing occurrence IDs, which prevents its indexing. However, the validator doesn't find any issue preventing the indexing.

-----

User provided contact info: @ManonGros
System: Safari 12.0.2 / Mac OS X 10.14.2
User: [See in registry](https://www.gbif.org/api/feedback/user/81be23b8a46d840f9272099ec8402bf7:15e4fc708e5d03cb1db867c70e3defb56b85b9fb1bcfad7538dd4e6b2595ede95dcd557830e3c5b2f6d3c24cd281f32112bc99995c751e3bbe05148befd94c0d)
Referer: https://www.gbif.org/tools/data-validator/1546511789581
Window size: width 1993 - height 842
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-28T08:23:32.059Z',mode:absolute,to:'2019-01-28T08:29:32.059Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-28T08:23:32.059Z',mode:absolute,to:'2019-01-28T08:29:32.059Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by thomasstjerne** [comment]
transferred to https://github.com/gbif/gbif-data-validator/issues/80
