### ISSUE TITLE
This species has a misspelling error, it is Tangara, not Tanagra. I found it using the species matching tool, that give me the correct name as fuzzy match of Tanagra

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1757]
**This species has a misspelling error, it is Tangara, not Tanagra. I found it using the species matching tool, that give me the correct name as fuzzy match of Tanagra**

-----

User provided contact info: @RicardoOrtizG @SiBColombia
System: Chrome 71.0.3578 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/33583652b158f0c136aab6b7afbe591a:dbf3fc90ed8be4b2e7f51edd29b012634007fe31751652845ab1c0b6c4759dff99c1431716d5bdfc9895c4b5b09c7df4d358d96847f025686219d54158c22411ca0da647a161201ea54291b26a220479)
Referer: https://www.gbif.org/species/search?q=tanagra%20episcopus
Window size: width 1920 - height 889
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-28T21:31:17.582Z',mode:absolute,to:'2019-01-28T21:37:17.582Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-28T21:31:17.582Z',mode:absolute,to:'2019-01-28T21:37:17.582Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ahahn-gbif** [comment]
Thanks for reporting this, @RicardoOrtizG. It appears that the spelling of the name is based on an (erroneous, it seems) entry in the "Zoology Accessions Register: Aves (Skins): 1884 -1888: page 130" of the Natural History Museum, London (https://www.gbif.org/occurrence/1291491840). We will add it to the list of cases to consider in taxonomic processing.

**Comment by jhnwllr** [comment]
contacted zoobank by email.

**Comment by jhnwllr** [comment]
@RicardoOrtizG

The publisher claims this is not a misspelling, but appreciates the feedback. 

https://www.biodiversitylibrary.org/page/42946509#page/317/mode/1up

I will close the issue now.

**Comment by deepreef** [comment]
Original spelling in the 1764 work can be seen here:
https://www.biodiversitylibrary.org/page/51335440#page/766/mode/1up
and here:
https://www.biodiversitylibrary.org/page/35369214#page/764/mode/1up
(as well as other pages in this volume).

Additional information on this name is here:
https://www.biodiversitylibrary.org/page/12223665#page/98/mode/1up
