### ISSUE TITLE
peer reviewed papers at GBIF.org: what counts

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1758]
**peer reviewed papers at GBIF.org: what counts**

Good idea to add paper count to GBIF.org. When one clicks the number, the list is prefiltered to journal articles only. Peer-reviewed book chapters and proceeding are not second class literature, and could be inlcuded in the count. It is different for asbtract, theses etc, and it is indeed good not to count those. I would also exclude preprints, if we are not doing this yet.

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5c56096e4e5740d2eafb53b6914ac75b:c54f5dc9a8422fca35bb153c37b3b883fa9b09b577112b8e43798932a06971b1732ad5715c34df5cb9bf2b09f1585b60a6149b2c1937308be2bebed94be1c9eb)
Referer: https://www.gbif.org/
Window size: width 1920 - height 1073
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-29T09:31:41.804Z',mode:absolute,to:'2019-01-29T09:37:41.804Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-29T09:31:41.804Z',mode:absolute,to:'2019-01-29T09:37:41.804Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by kcopas** [comment]
One issue here is that our count has always zeroed in on articles. There's no intended disrespect of chapters and proceedings.

**Comment by dschigel** [comment]
@kcopas ok then, the gain would be only a few tens more, and consistensy is more important

**Comment by dschigel** [comment]
Thanks, all clear now. Strictly speaking proceedings are papers, too, but conistensy and invitation to click on the filter wins.
