### ISSUE TITLE
Occurance data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1761]
**Occurance data**

I am trying to download data that has coordinates.  However, when I open the .csv there are no coordinates.  Is there fix to this?

-----

User provided contact info: gmak@csumb.edu
System: Edge 17.17134.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/26b4ff07c343da70c4af330bcc3fa066:ae4b3cf041f6973760fca6f11d6c792282f511d88212ad61c7222ef5f789a0b035289749c49951d1fa0f5c53c4a3c86bcb4aa9e95851053218212f9ede41c2fb)
Referer: https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&taxon_key=2426756&geometry=POLYGON((-122.83015%2033.17133,-117.38928%2033.17133,-117.38928%2036.90521,-122.83015%2036.90521,-122.83015%2033.17133))
Window size: width 1829 - height 889
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-29T19:08:59.551Z',mode:absolute,to:'2019-01-29T19:14:59.551Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-29T19:08:59.551Z',mode:absolute,to:'2019-01-29T19:14:59.551Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by dnoesgaard** [comment]
Responded to user by email.
