### ISSUE TITLE
feedback.confirmation.example

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1762]
**feedback.confirmation.example**

What is this translation meant for?

It looks like its used after a user successfully submits an issue (but it's empty)

**Comment by MortenHofft** [comment]
@dnoesgaard I'm not sure I understand the question. Does it show in the interface? Or is it a key in the translation file that you believe isn't used?

**Comment by dnoesgaard** [comment]
![screenshot 2019-01-31 at 09 21 12](https://user-images.githubusercontent.com/21358085/52041087-adc14980-2539-11e9-9825-f68b563a75a2.png)

**Comment by MortenHofft** [comment]
Ah - I believe we used to have a message there and then someone decided that they didn't like it and so it was removed, but kept in case and probably because it was easier.

**Comment by dnoesgaard** [comment]
Maybe I'll add something then, e.g.

"Your feedback has logged as an issue in Github. If necessary and if contact details were provided, we might reach out to you for further information. You can track progress by visiting the issue page."

Make sense?

**Comment by MortenHofft** [comment]
@dnoesgaard a bit long perhaps, but the gist of it I like 👍

**Comment by dnoesgaard** [comment]
Oh, I'm not allowed to "save translations for empty strings" :(

**Comment by MortenHofft** [comment]
ah - makes sense. I've added it https://github.com/gbif/portal16/commit/c4c0111b815fd2750fdc69ef1487768bc79e9a95
