### ISSUE TITLE
CREATE TABLE for occurances

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1764]
**CREATE TABLE for occurances**

I am looking for an CREATE TABLE command in order to create a table for the occurance csv but I cannot find it anywhere. Would you be able to share this or point me to the correct link?

Kind regards,
Bastiaan

-----

User provided contact info: @bwakkie
System: Firefox 64.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/bc9ba6f87e5d1da0c2391c3b0bef6e19:584708ab7a5abec25f3bbe7b5c8d2a60f3fa04d581dc8ebb9193b01f71bb26623129d188d6f143c512e24e0d0953767dc1dee32f2ac518c9dcdad456b267b922)
Referer: https://www.gbif.org/
Window size: width 1916 - height 917
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-31T10:14:22.488Z',mode:absolute,to:'2019-01-31T10:20:22.488Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-31T10:14:22.488Z',mode:absolute,to:'2019-01-31T10:20:22.488Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by bwakkie** [comment]
CREATE TABLE for occurrence

**Comment by MattBlissett** [comment]
There is not an SQL schema -- we aren't using an SQL database for the occurrence records.

The types should be:

integer: gbifID, kingdomKey, phylumKey, classKey, orderKey, familyKey, genusKey, speciesKey, day, month, year

UUID: datasetKey, publishingOrgKey

decimal: decimalLatitude, decimalLongitude, coordinateUncertaintyInMeters, coordinatePrecision, elevation, elevationAccuracy, depth, depthAccuracy

date: eventDate, dateIdentified

enumeration: taxonRank, basisOfRecord, countryCode, license.

character string: everything else
