### ISSUE TITLE
Search occurrences matching set criteria

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1765]
**Search occurrences matching set criteria**

Is there a way to search for species occurrences by the amount of occurrences available? For example, say I am interested in all Myotis species in the United States for which there are more than 100 occurrences recorded. Is there a way I can know which Myotis sp. match that criteria?

Thank you in advance for any help.

-----

User provided contact info: @katemarkham
System: Chrome 71.0.3578 / Windows 8.1.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/494d2e7e9c344285b9cc8af5cecbabcf:75da057a210096426f9f2914dde661af7445e4cb9e38fd72a80085b707964719f5518dbbda66c1d4fde73c5e0e7532c7f4e1f693d260ce964dba524810155b32)
Referer: https://www.gbif.org/user/profile
Window size: width 1431 - height 738
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-31T22:49:37.426Z',mode:absolute,to:'2019-01-31T22:55:37.426Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-31T22:49:37.426Z',mode:absolute,to:'2019-01-31T22:55:37.426Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by dnoesgaard** [comment]
Hi @katemarkham,

Start by searching for the genus and the country–then switch to the taxonomy tab:

https://www.gbif.org/occurrence/taxonomy?country=US&taxon_key=2432384

I hope that gets your started.

**Comment by dnoesgaard** [comment]
If you prefer using the API, this will get you the list of species by taxonKey:

http://api.gbif.org/v1/occurrence/search?country=US&taxon_key=2432384&facet=speciesKey&limit=0&facetMincount=100&facetLimit=25

(you can adjust facetMincount to the minimum number of occurrences desired)
