### ISSUE TITLE
Cuban spinach? Never heard of it. Must be a VERY obscure English name, as the species occurs nowhere near Cuba, and no link between Cuba and its range. Miner's lettuce is the standard and widely applied name for this common weed, as its range is mineral rich and pioneer miners consumed it.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1767]
**Cuban spinach? Never heard of it. Must be a VERY obscure English name, as the species occurs nowhere near Cuba, and no link between Cuba and its range. Miner&#39;s lettuce is the standard and widely applied name for this common weed, as its range is mineral rich and pioneer miners consumed it.**

-----

User provided contact info: cistanthe@gmail.com
System: Chrome Mobile 39.0.2171 / Android 5.0.2
User: [See in registry](https://www.gbif.org/api/feedback/user/dddb75267a9d2e44b7ce99b933a50444:18458d30a2d4cbbf080371a68ce4e200dac9bd05b029e55cc2b365a1d1a49c087b00f199cc4f22106a0c64eeca9bd15bc94448926e203fffc51ca7ab4d348148)
Referer: https://www.gbif.org/species/3084748
Window size: width 360 - height 248
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-04T14:59:04.354Z',mode:absolute,to:'2019-02-04T15:05:04.354Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-04T14:59:04.354Z',mode:absolute,to:'2019-02-04T15:05:04.354Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by andzandz11** [comment]
https://hartley-botanic.co.uk/magazine/claytonia-montia-perfoliata-cuban-spinach-miners-lettuce/

I am sorry, what is the question here?

https://www.lebensmittellexikon.de/k0000240.php

> Durch die weißen Siedler verbreitete sich die Pflanze im Laufe der Zeit bis in das atlantische Amerika und nach Kuba. Von dort aus gelangte sie nach Australien und Westeuropa.

meaning:
"White settlers carried the seeds to the east coast and to Cuba. From there the plant spread to Australia and western Europe."

Keep in mind this is also a crop plant. It may not show up on species distribution lists if it is grown in gardens or greenhouses.

**Comment by ManonGros** [comment]
Thanks for the reply, I think we can close the issue.
