### ISSUE TITLE
Occurrence search/download for a long list of taxa

### ISSUE THREAD

**Issue by peterdesmet** [gbif/portal-feedback#1768]
For the [Tracking Invasive Species (TrIAS) project](http://trias-project.be), we want to (periodically) **download occurrences for a (long) list of (alien) species**.

Downloading occurrences for multiple taxa can be done by combining `taxon_key`s:

> http://api.gbif.org/v1/occurrence/search?taxon_key=5421039&taxon_key=5361785&taxon_key=5289808

We have the (over 3.500) `taxon_key`s we want to download, but the request URL is **limited to 12.000 characters**, which limits the number of taxa that can be queried. We could split the list of taxa over multiple download requests, but for reproducibility and efficiency it would better to only have one single download that can be referenced.

Potential suggestions to fix this:

1. Use `POST` instead of `GET` and provide a simple csv list with `taxon_key`s (one for each line). This is the most flexible solution.

2. Query all occurrences for taxa in a published checklist dataset. This would work for us (TrIAS) as well, since the set of 3.500 taxa are published as one of our checklists:

    > http://api.gbif.org/v1/occurrence/search?taxa_from=9ff7d317-609b-4c08-bd86-3bc404b77c42

@timrobertson100 as this is currently a bottleneck for our project, we are willing to fund this as a suggested subcontract.

**Comment by peterdesmet** [comment]
Yes, it is only download that we need (although a search is useful to preview what you get). We will try to trigger a download for our list of species using `rgbif`, which will build the POST request for us. /cc @damianooldoni

**Comment by peterdesmet** [comment]
@timrobertson100 triggering such a download resulted in a `Broken download`: https://www.gbif.org/occurrence/download/0036426-181108115102211 Any suggestions for fixes/alternatives?

**Comment by timrobertson100** [comment]
We’d like to arrange a call with you to discuss options that go beyond your initial proposal. This will need work and we could improve other things at the same time. Next week?

**Comment by MattBlissett** [comment]
See also https://github.com/gbif/occurrence/issues/50

**Comment by peterdesmet** [comment]
Update: as discussed with @timrobertson100 we will likely filter on taxa _after_ downloading all occurrences for Belgium for now.

**Comment by mdoering** [comment]
I'd like to suggest another variation of the uploaded CSV option.

In CoL+ we would like to allow registered GBIF users to upload their own name lists as a 'personal' dataset. Having this available we can provide many services on top including the option to provide a taxon id list to be used in occurrence search filters. It would also allow users to get an entire list of names matched without calling the matching API one by one, download that list with the latest CoL classification or other checklists, provide notification services for new specimens, species, etc.

**Comment by timrobertson100** [comment]
Thanks Markus.  We need that to support the ALA work too (known as named
lists in ALA)...

**Comment by MattBlissett** [comment]
The limit is now 101,000 "things" (e.g. taxa or other comparisons). That should allow for 100,000 taxa plus other filters on country, dataset etc.

(This is ready in production.)
