### ISSUE TITLE
Bounding box queries failing when submitted to API via R

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1769]
**Bounding box queries failing when submitted to API via R**

I have been trying to run downloads to your API via rgbif. These work, in that they appear correctly on my download page (e.g. `https://www.gbif.org/occurrence/download/0036073-181108115102211),` but the download is always reported by the API as broken when I use a polygon bounding box (they work fine otherwise).
 There seems to be nothing intrinsically wrong with the query however, it is displayed correctly on my downloads page under my GBIF account, and if I choose "rerun query" on the downloads page the query runs fine and I can see the bounding box displayed on the results map.

-----

User provided contact info: olipes@ceh.ac.uk
System: Chrome 71.0.3578 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/d462cb078474f2b7ca8f1988013e4a0c:247b6f8fe4e3858d764a08291795d086420bbbda253f430dacb2da1aaff4e7537223895db8190a5f25c6d0b3995a32319a5d1b2ec369395c4368ab2bb2077150)
Referer: https://www.gbif.org/occurrence/download/0036073-181108115102211
Window size: width 1920 - height 948
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-05T16:58:59.158Z',mode:absolute,to:'2019-02-05T17:04:59.158Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-05T16:58:59.158Z',mode:absolute,to:'2019-02-05T17:04:59.158Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The download page shows the download as broken because it is considered an invalid query. The UI shows it as red for the same reason.
![screen shot 2019-02-05 at 20 41 34](https://user-images.githubusercontent.com/6759267/52300061-3e0eec80-2987-11e9-92f8-148fdf6400d5.png)
The problem is that WKT standard requires you to define your polygon counter clockwise. And the polygon in your download is clockwise ordered.

When using the interface, such queries are not allowed, but if generating them by other means, we show them, but mark them as broken.

**Comment by MortenHofft** [comment]
```
Broken clockwise : POLYGON((-19.50419 34.06333,-25.27233 68.11722,35.96248 68.11722,27.75443 34.06333,-19.50419 34.06333))
Counter clockwise: POLYGON((-19.50419 34.06333,27.75443 34.06333,35.97336 68.121,-25.27233 68.11722,-19.50419 34.06333))
```
