### ISSUE TITLE
Incorrect location for NZ type specimen

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1770]
Type specimen for NZ endemic _Ceratomerus crassinervis_ has coordinates that place it in Canada: 
https://www.gbif.org/occurrence/1320884519

Apparently previously reported, but no related issues found:
https://twitter.com/stho002/status/1092900044938702848

**Comment by ManonGros** [comment]
I have reported this issue to Tom Hollowell the last June (2018), but it was before he passed away (see email Helpdesk from the 18th of June).
The reply I got was that he will forward it to the relevant person at the museum.

Note that the status of this record is “unreviewed” and the following remark is attached to it: “legacy data of uncertain quality”.

**Comment by ManonGros** [comment]
I transferred the feedback through the NMNH feedback system.
