### ISSUE TITLE
Photo from different occurrence

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1771]
**Photo from different occurrence**

This photo is for a Yellow Wagtail. It should be attached to the record from the same dataset with the record id ending in 1019 (as in the image URL l rather than 1018.

-----

User provided contact info: @dhobern
System: Chrome Mobile 72.0.3626 / Android 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/459965c7ee340eb1c6107623c18af700:40fc299514277c836648acb3472803998ed32229ac56fec99a1b5ee8b1b75b9ff6e47f2242828b541bd7248589a98047d74de7b3fd5b55e9fb83f9fe4d937bad)
Referer: https://www.gbif.org/occurrence/1932572061
Window size: width 412 - height 429
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-07T14:23:24.914Z',mode:absolute,to:'2019-02-07T14:29:24.914Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-07T14:23:24.914Z',mode:absolute,to:'2019-02-07T14:29:24.914Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dhobern** [comment]
Based on a display Tim Hirsch just showed I think this may be a more systemic issue with images in this dataset. Maybe many of them have been attached to the wrong records (one off?). I'm on my phone so having difficulty checking.

**Comment by dhobern** [comment]
See this one. That looks like Corvus splendens or similar. 

https://www.gbif.org/occurrence/1932571895

**Comment by timhirsch** [comment]
@MBLaursen @ManonGros this dataset is associated with Project ID BID-AF2017-0210-NAC so it will be good to get them to correct these errors perhaps through the mentor if there is one assigned - as one of the few image-based datasets from Nigeria it will be important to fix.

**Comment by dhobern** [comment]
The second one may just be a misidentification. It's Corvus albus, as far as I can see, but the photo number and record number do match for this one.

However, if I then search within the dataset for Corvus, I get this set:

https://www.gbif.org/occurrence/gallery?q=Corvus&dataset_key=ddb362fd-38cf-4bac-b7a2-19c614fcfae9

Two of these have images. One is a Pied Kingfisher:

https://www.gbif.org/occurrence/1932572266

So, the quality of the linkage between images and records should be reviewed by someone - the mentor would be the place to start.

**Comment by ManonGros** [comment]
I have contacted the publishers and CCied their mentor and GBIF France.

**Comment by ManonGros** [comment]
The publishers have corrected the issue.
