### ISSUE TITLE
Family Cepheidae

### ISSUE THREAD

**Issue by drmjshepherd** [gbif/portal-feedback#1773]
On GBIF, the family Cepehidae seems to contain both cnidarians and oribatid mites.  Only Cephea, Cotylorhiza, Marivagia, Netrostoma and Polyrhiza are Cnidarians.  The rest are Oribatid mites (Arthropoda, Arachnida, Acari, Sarcoptiformes, Oribatida, Brachypylina, Cepheoidea, Cepheidae)  See Balogh and Balogh, (1992). The Oribatid mites genera of the world, Hungarian National Museum Press, ISBN 963 7093 04 4 which lists all other genera, except Pilocepheus, Tereticepheus and ?implicatus.  However the authors of these taxa work/worked in the field of acarology.

**Comment by mdoering** [comment]
added to backbone patch: https://github.com/gbif/backbone-patch/blob/master/patch.csv#L90

**Comment by mdoering** [comment]
... and updated CLB to allow [intra kingdom family homonyms](https://github.com/gbif/checklistbank/commit/94feae9dd829d7749c3c6cda6c279345abdd14d0)
