### ISSUE TITLE
The author of the species is missing.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1774]
**The author of the species is missing.**

The author of the species is missing: Boiss.
Thymus granatensis Boiss. subsp. granatensis

Regards

-----

User provided contact info: herbariomgc@uma.es
System: Chrome 72.0.3626 / Windows 8.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7949cfb264c3a3144c141473f709f6d9:654267cdc8b5826206d337d0254142a70ea124cdc6f7fdb402be455aa164d268530a5c02ebdc07752f9227ebc7278a6ba204609dcd2d6ec3e5dc8f4039fa81b5)
Referer: https://www.gbif.org/species/7307347
Window size: width 1207 - height 710
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-08T12:45:03.012Z',mode:absolute,to:'2019-02-08T12:51:03.012Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-08T12:45:03.012Z',mode:absolute,to:'2019-02-08T12:51:03.012Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by andzandz11** [comment]
That is on purpose, check: https://www.gbif.org/species/7307798
The subsp. has no author because it is automatically generated and not the result of a (sub)species publication.

**Comment by ManonGros** [comment]
Thank you for the reply @andzandz11, this is exactly the reason for this.
Closing the issue.
