### ISSUE TITLE
Summary of references

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1775]
**Summary of references**

Hi!
Is possible to download all the metadata of my datasets references?
Regards

-----

User provided contact info: herbariomgc@uma.es
System: Chrome 72.0.3626 / Windows 8.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/f9f77d93147eeedbc1d222c47a481abf:7a91c4ff66d06d39c8a039fea6dc633b96f256b580bf444c5a92d1919bbc938c23f45ebbae00229ae5f94c4811cd2eb558ef0e7346119cdb2a2acc0e84b5ef63)
Referer: https://www.gbif.org/resource/search?offset=20&contentType=literature&gbifDatasetKey=962cceea-f762-11e1-a439-00145eb45e9a
Window size: width 1280 - height 881
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-11T13:43:58.486Z',mode:absolute,to:'2019-02-11T13:49:58.486Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-11T13:43:58.486Z',mode:absolute,to:'2019-02-11T13:49:58.486Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Responded to user via email:

> We don’t currently have an option to download citations of datasets, however, you can get to the data via the undocumented content API, e.g.
>  
> https://www.gbif.org/api/resource/search?contentType=literature&gbifDatasetKey=962cceea-f762-11e1-a439-00145eb45e9a&limit=100
>  
> This gives you a JSON output, which can be parsed using a number of tools. If you have no way of ingesting the JSON feed directly, there are several online tools to convert it to tabular format. For example, https://json-csv.com/ - you can paste the URL and download an Excel file. Because of the nested structure of the JSON feed, you may want to choose to concatenate nested data in the settings)
