### ISSUE TITLE
Data validator has problems with comma delineated files

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1776]
**Data validator has problems with comma delineated files**

The data validator seems to give problems with comma delineated files if commas appear in fields, even when they are enclosed by quotes.
For example, the dataset `https://www.gbif.org/dataset/4f8de55f-5967-46c4-b689-31de17090ed4` gives error message “validation.issueType.OCCURRENCE_NOT_UNIQUELY_IDENTIFIED”.This is caused by fields with a comma, the validator seems to ignore the quotes for enclosing the fields. . 
ZMA.COL.P.10563 : < Pilzen 400m"> or ZMA.COL.P.14719: < Farnborough">. Fields in this dataset above are terminated by commas, and not by tabs, which might be the problem .

Of minor importance, there seems an error in the layout with the date of validation. Now some code is shown in the report, not a real data)

-----

User provided contact info: jeroen.creuwels@naturalis.nl
System: Chrome 72.0.3626 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/64bfc02b46bf012e41884f9a1ffdc3a3:6bb0496f02a2a77a3e2d01bebef7607912d66f780f34401f56ad9129154b1565e16258e3812eef211ca21fe1adc95c9f57448f9d224a730924e44e5e30d1be5f)
Referer: https://www.gbif.org/tools/data-validator/1546511789742
Window size: width 2380 - height 1205
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-12T12:48:42.462Z',mode:absolute,to:'2019-02-12T12:54:42.462Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-12T12:48:42.462Z',mode:absolute,to:'2019-02-12T12:54:42.462Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
transferred to https://github.com/gbif/gbif-data-validator/issues/79
