### ISSUE TITLE
Infra-specific epithets - gender of genus name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1777]
**Infra-specific epithets - gender of genus name**

We received this feedback on Helpdesk:
>I believe that infra-specific epithets should be appropriate to the gender of genus name.  
For your reference, I attached anther taxonomic information from [the plant list](http://www.theplantlist.org/tpl1.1/record/kew-2878196).

-----

User provided contact info: @ManonGros
System: Safari 12.0.3 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/968f0df4feeac51c5e85133d4d513b1e:8242cd23314d40e6e1f4f1aef6e30d84262af84a2af388e664f3f15b6901f32b6342013d1ba2d6d7633d43155f0ce6900bffcbabe59d92c79e6a36bc97524369)
Referer: https://www.gbif.org/species/7649776
Window size: width 2032 - height 956
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-13T10:41:12.309Z',mode:absolute,to:'2019-02-13T10:47:12.309Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-13T10:41:12.309Z',mode:absolute,to:'2019-02-13T10:47:12.309Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by andzandz11** [comment]
https://www.iapt-taxon.org/nomen/pages/main/art_24.html
> 24.2. Infraspecific epithets are formed like specific epithets and, when adjectival in form and not used as nouns, they agree grammatically with the generic name (see Art. 23.5 and 32.2). 

This ruleset is the international standard.

**Comment by ManonGros** [comment]
It looks like this has been corrected in the new backbone: https://www.gbif.org/species/7803082
