### ISSUE TITLE
taxsize R package question 

### ISSUE THREAD

**Issue by beramir** [gbif/portal-feedback#1778]
(Delete this text after you have read it.)

Please summarize the issue, bug or improvement idea.  In most cases, you should paste in example URLs or API calls which show the problem.

For a problem, please describe what you did, what you expected to happen, and what happened instead.

For an idea for a new function, please explain what you'd like to be able to do, and why it would be useful.

```
You can format code or output like this,
to keep line breaks.
```

Thanks!

**Comment by beramir** [comment]
Hello, 

I am using the gbif_name_usage function from Taxsize R package, and it returns:

Error: Not Found (HTTP 404)

Why is this? any suggested solution?

Thanks,

B.

**Comment by jhnwllr** [comment]
Could you give more details on what you were trying to look up?

**Comment by andzandz11** [comment]
From the official readme:
`?taxize::gbif_name_usage`

> This is a taxize version of the same function in the rgbif package so as to not have to import rgbif and thus require GDAL binary installation.

**Comment by jhnwllr** [comment]
no response from @beramir so I am going to close the issue.

**Comment by sckott** [comment]
@beramir if this is an issue with the `taxize` package, please file an issue at https://github.com/ropensci/taxize/issues
