### ISSUE TITLE
Update Harvard University Herbaria info

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1783]
**Update Harvard University Herbaria info**

Hello, 

I am the informatics director at the Harvard University Herbaria. We are upgrading our IPT instance and recently registered a new endpoint. I am seeing on our main GBIF page data that is out of date and I was wondering if my GBIF user (jkennedy) could be given access to update this information? That info is:

- In the "Installations" list, I would like to mark the previous IPT link and DiGIR link as (deprecated).
- The Administrative contact and technical contacts should both be me (Jonathan Kennedy)

Thank you for your help.

-Jonathan Kennedy

-----

User provided contact info: jonathan_kennedy@harvard.edu
System: Chrome 71.0.3578 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/6c58d65fa9da4df33cb3378bb1442365:7edd846f66f8226ec6d9b0a8779fa3ecdc7e3b2458b0bcfed427fbe4b35419cf6ba8b977be27678b6e4f8d307ba04f763a293fda2da7ad092df8ce2f841b5f82)
Referer: https://www.gbif.org/publisher/485ff490-e3b7-11db-9acc-b8a03c50a862
Window size: width 1181 - height 726
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-17T22:18:45.476Z',mode:absolute,to:'2019-02-17T22:24:45.476Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-17T22:18:45.476Z',mode:absolute,to:'2019-02-17T22:24:45.476Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
These look like duplicates (and maybe triplicates) of existing records: see the first two records here (dupes in two diff datasets): https://www.gbif.org/occurrence/search?publishing_org=485ff490-e3b7-11db-9acc-b8a03c50a862

Thinking this approach also adds pairs to existing records (above looks new)

**Comment by ManonGros** [comment]
publisher contacted by email.
