### ISSUE TITLE
Harvard Herbaria broken images

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1784]
**Harvard Herbaria broken images**

There are numerous broken images from the Harvard Herbaria main page and gallery. This is the result of an error in a version of the huh_all_records dataset. These data were corrected and republished, but the broken links persist on GBIF.

-----

User provided contact info: jonathan_kennedy@harvard.edu
System: Chrome 71.0.3578 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/3d43241d4afe8348f9fda1cdf4e2fe00:bb1069631e86760712356c50be9716169cb4ad5c7e0f2040c3fa191dd81ca6b90bf333be7475c213b27d8358ed0e7f7c97ebf2a3a6bd4abbcf97f594acb14f0d)
Referer: https://www.gbif.org/occurrence/gallery?publishing_org=485ff490-e3b7-11db-9acc-b8a03c50a862
Window size: width 1181 - height 677
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-18T06:14:26.406Z',mode:absolute,to:'2019-02-18T06:20:26.406Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-18T06:14:26.406Z',mode:absolute,to:'2019-02-18T06:20:26.406Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Normally publishing via the IPT triggers a new ingestion by GBIF, but in this case the previous (first) ingestion was still in progress, so the new one was ignored.

I've re-ingested the dataset, and all seems well now.
