### ISSUE TITLE
occurrence labelled "Recorded date mismatch" when no day is given

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1785]
**occurrence labelled &quot;Recorded date mismatch&quot; when no day is given**

For this occurrence, the `eventDate` is `06-1991`, the `year` is `1991` and the `month` is `06`.

Could it be because the `eventDate` does not follow the ISO format?

-----

User provided contact info: @ManonGros
System: Safari 12.0.3 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/4e437f309198639a05ac124a48fb329f:8755b11775f156c39f0f74b50a843e7d6c31c47f164b8eb0eb5c09df2ecde4f0a0836d010590c7329a82c02c2ff1ecde7be4fb8cd7733021642bac6f2389a80f)
Referer: https://www.gbif.org/occurrence/1987574943
Window size: width 2488 - height 1268
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-19T13:06:51.310Z',mode:absolute,to:'2019-02-19T13:12:51.310Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-19T13:06:51.310Z',mode:absolute,to:'2019-02-19T13:12:51.310Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
`06-1991` is invalid, as it doesn't follow the ISO format.

`1991` and `06` is valid, and could perhaps be used to work out what `06-1991` was intended to mean, but we haven't yet specified the behaviour for this. For the moment, `mismatch` seems reasonable.
