### ISSUE TITLE
nesting birds in data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1787]
**nesting birds in data**

Hi ! 

I would like to know if it is possible to isolate the nesting birds when you download some datas (CSV) from eBird?

Thank you by advance,
Sincerely,

Miléna Aragon

-----

User provided contact info: milena_aragon@yahoo.ca
System: Safari 12.0.0 / Mac OS X 10.14.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e9cc1277a12aff988983abc15600987b:645785a1936ba1767eb8825ab8dd4ab0fa12947bb5c2e73d619ae3adb60f5380467dfb25a5f31cb7083aa26ca18309a78e91b0dd639fef48a59fba19954a7a68)
Referer: https://www.gbif.org/
Window size: width 1297 - height 558
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-19T14:23:36.657Z',mode:absolute,to:'2019-02-19T14:29:36.657Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-19T14:23:36.657Z',mode:absolute,to:'2019-02-19T14:29:36.657Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> We do not store information about nesting habits. In order to get the records for nesting birds, you would have to provide us with a list of nesting species. If you already have such list, don’t hesitate to contact us at heldesk@gbif.org to request a custom download.
 
> An alternative would be for you to contact directly eBird and see if they can help.
