### ISSUE TITLE
Mollusca appearing in the KUBI ichthyology resources

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1788]
**Mollusca appearing in the KUBI ichthyology resources**

On the metrics screen of both the KUBI ichthyology and ichthyology tissue collection there are two occurrence records attributed to the phylum mollusca.  This is due to an error in matching of the family Cepolidae which is found in both fishes and molluscs.  This issue has been brought up numerous times but has yet to be fixed and is a blemish on the voracity of our published data.  Please attend to this in your taxonomic backbone.

Thanks, Andy

-----

User provided contact info: abentley@ku.edu
System: Chrome 72.0.3626 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e30ce83b5f86103b9f6858b62b285051:391b2aaaf62721768c6212ec2f36e7b26399373bbf646290b8e3af5757a2dcf20251cebf603d7a16aae161dede4ff015a81dd61cb1e078eec3c0b3bb2d063cd3)
Referer: https://www.gbif.org/dataset/8f79c802-a58c-447f-99aa-1d6a0790825a/metrics
Window size: width 2133 - height 1409
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-19T16:53:52.990Z',mode:absolute,to:'2019-02-19T16:59:52.990Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-19T16:53:52.990Z',mode:absolute,to:'2019-02-19T16:59:52.990Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
Cepolidae homonym families added to backbone patch: https://github.com/gbif/backbone-patch/commit/cba2416fbd7bdbb2c74d259d5af22a491c63d119#diff-1cf536204dd397fe1fc39e75b494bec5R98

And update CLB to allow [intra kingdom family homonyms](https://github.com/gbif/checklistbank/commit/94feae9dd829d7749c3c6cda6c279345abdd14d0)
