### ISSUE TITLE
Rhinobatos schlegelii

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1789]
**Rhinobatos schlegelii**

This species name is being flagged as incorrect (`https://www.gbif.org/occurrence/1703048509)` when it is indeed correct - `http://researcharchive.calacademy.org/research/ichthyology/catalog/fishcatget.asp?spid=26771`

Andy

-----

User provided contact info: abentley@ku.edu
System: Chrome 72.0.3626 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/04d24ecc4b186d06ccba9860a4eb0438:d5d6e25785421897621e9e23f3fb5dababb490ea6823566b630a9d4c43eb210a798499329a3fd49e4c2dfd63510c815f38e258edf2986c951297ca313cde9779)
Referer: https://www.gbif.org/occurrence/1703048509
Window size: width 2133 - height 1409
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-19T16:59:25.103Z',mode:absolute,to:'2019-02-19T17:05:25.103Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-19T16:59:25.103Z',mode:absolute,to:'2019-02-19T17:05:25.103Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It looks like we have two issues leading to this mismatch:
- The scientific name authorship given for [the occurrence](https://www.gbif.org/occurrence/1703048509) is `Norman, 1926` but the scientific name [in our taxonomy](https://www.gbif.org/species/2418995) for this species is `Rhinobatos schlegelii Müller & Henle, 1841` which explains that the occurrence name wasn't matched to the proper species name.
- The [taxon that it is matched to](https://www.gbif.org/species/9743899), `Rhinobatos schegelii`, which comes from [a PLAZI checklist](https://www.gbif.org/dataset/abf8082d-c179-4cb2-acc4-3cdef16c4341), seems to be a spelling mistake as well.
    - This also raises the issue of spelling mistakes for the four occurrences attached to this species page. For example [this occurrence](https://www.gbif.org/occurrence/1056780350) from the [Natural History Museum (London) Collection Specimens](https://www.gbif.org/dataset/7e380070-f762-11e1-a439-00145eb45e9a) contains the name `Rhinobatus schegelii Richardson, 1846` but [the label](https://api.gbif.org/v1/image/unsafe/http%3A%2F%2Fwww.nhm.ac.uk%2Fservices%2Fmedia-store%2Fasset%2F1feeb38d6ba5f6edb093002ff3f2e4e201303dd8%2Fcontents%2Fpreview) reads `schlegelii`.

Therefore, the authorship on the KU collection should be updated, the PLAZI checklist should be corrected and the Natural History Museum should be contacted.

**Comment by ManonGros** [comment]
Contacted PLAZI and Andrew by email.

**Comment by ManonGros** [comment]
I left a comment on the NHN Data Portal for [this occurrence](http://data.nhm.ac.uk/object/bd846fbc-dd89-48df-9a06-8ab9c7bb4682).

**Comment by gsautter** [comment]
I just check the original PDF, and the Plazi website does reflect the published spelling of the taxon name in question. Whether or not this is the correct name form a domain specialist's point of view is a different question altogether. My feeling is that we should faithfully reflect the original publication in terms of content, and thus should not make a correction on the Plazi side.

So it would most likely be best to contact any of the originators for this checklist, unless @myrmoteras has a different take on this.

**Comment by myrmoteras** [comment]
We don't change names unless we made the mistake since we represent what is published and do not make interpretations. In case of printing errors then GBIF should have a mechanism to link this misspelling to the properly spelled name and attribute the agent who pointed it out.

**Comment by ManonGros** [comment]
Thank you both for the quick reply!
In that case, @mdoering would it be possible to review [this species](https://www.gbif.org/species/9743899) and link it to the properly spelled name?

**Comment by yroskov** [comment]
CoL follows taxonomy accepted in FishBase. Comment should be shared with FishBase.

**Comment by mdoering** [comment]
@yroskov can you please inform FishBase?

**Comment by yroskov** [comment]
I sent a link #1789 to FishBase.

**Comment by ManonGros** [comment]
It looks like this issue is now solved.
