### ISSUE TITLE
translations not used in species lookup tool?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1790]
**translations not used in species lookup tool?**

e.g. `https://www.gbif.org/ja/tools/species-lookup`

not using translation:
`https://crowdin.com/translate/gbif-portal/95/en-ja#8836`

-----

User provided contact info: @dnoesgaard
System: Chrome 72.0.3626 / Mac OS X 10.14.2
User: [See in registry](https://www.gbif.org/api/feedback/user/9b00d887fcc75042bc2175f64658507d:e432403a657bef031f6ad81014cc4dd70ac956ea597ebcac069e1b859c8e91f636e25c047ebd587be64cee42f8d74d129e2a1416c6a30aedfb6389e3cf3a5bf2)
Referer: https://www.gbif.org/tools/species-lookup
Window size: width 1560 - height 1055
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-21T08:22:36.966Z',mode:absolute,to:'2019-02-21T08:28:36.966Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-21T08:22:36.966Z',mode:absolute,to:'2019-02-21T08:28:36.966Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
It appears that a few phrases in the tool aren't localizable at all, e.g.

https://github.com/gbif/portal16/blob/a4bee900e74d5bbfc0d82fed2f6bd052a80cce3c/app/views/pages/tools/speciesLookup/selectKingdom.nunjucks#L10

https://github.com/gbif/portal16/blob/a4bee900e74d5bbfc0d82fed2f6bd052a80cce3c/app/views/pages/tools/speciesLookup/selectKingdom.nunjucks#L23

and others...

**Comment by MortenHofft** [comment]
I don't believe there has been any plans or attempt to localise that tool. I don't see anything translated.

**Comment by dnoesgaard** [comment]
Ah ok.

But it's a general principle to use translation files rather than hard-coded text in new developments?

**Comment by MortenHofft** [comment]
In general we do so, but some things are experimental and possibly short lived. Just like we have [Maxent](https://www.gbif.org/ja/tool/81279/maxent) as a prominent tool in the menu, but the article isn't translated. Either way we can do so if we believe it brings enough value.

**Comment by MortenHofft** [comment]
I'm closing this. If we believe that this tool should be translated, then please create a new issue
