### ISSUE TITLE
IUCN link dead

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1792]
**IUCN link dead**

404 link to `https://www.iucnredlist.org/details/41918`
for Encephalartos macrostrobilus

-----

System: Chrome 71.0.3578 / Mac OS X 10.14.2
User: [See in registry](https://www.gbif.org/api/feedback/user/62d1882a7e30e7a8aa131f754b2673cb:64e734515917dc96d98977badc6e8e4e9e601937c5f18eb24bbec8e280ef62d4a5e75016f0472ef95a5720e9be3d5df9b87afeb092fe152fd09a8828c2c92445)
Referer: https://www.gbif.org/species/2683712
Window size: width 1523 - height 871
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-21T17:00:56.333Z',mode:absolute,to:'2019-02-21T17:06:56.333Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-21T17:00:56.333Z',mode:absolute,to:'2019-02-21T17:06:56.333Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Seems to be site-wide, e.g.
https://www.gbif.org/species/5219446
links to http://www.iucnredlist.org/details/714 (also 404)

The new(?) IUCN website uses a different structure and another id is added to the URL, e.g.
https://www.iucnredlist.org/species/714/110023718

oddly, you do get to this using the API, e.g.
http://apiv3.iucnredlist.org/api/v3/website/Ailurus%20fulgens
or (even more odd) by simply adding /anything to the old URL, e.g
https://www.iucnredlist.org/details/41918/blablabla

**Comment by dnoesgaard** [comment]
Not quite sure why this one is assigned to @mdoering, probably belongs with @MortenHofft or @thomasstjerne ?

**Comment by MattBlissett** [comment]
I think the portal assigns them automatically, if the user who submits the bug is a GBIF developer.

**Comment by timhirsch** [comment]
If this is a bug that requires some action or guidance on the IUCN side, we will be seeing the red list team in Cambridge on Friday 10 May - so please update me and @arodrigues by EOB on Thursday 9 May.

**Comment by dnoesgaard** [comment]
@thomasstjerne has informed @andrewrodrigues so he's in the know...

**Comment by timhirsch** [comment]
This was discussed at the meeting we had with the IUCN Red List Committee meeting on 10 May, and @andrewrodrigues is in direct contact with Ackbar.joolia@iucn.org (technical contact at IUCN) to help find a resolution. Important that we keep line of communication open with Ackbar so he is aware of how we are showing the red list status which is part of a draft IUCN/GBIF agreement likely to be signed shortly.
