### ISSUE TITLE
dataset activity very slow

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1793]
**dataset activity very slow**

`https://www.gbif.org/dataset/e6fab7b3-c733-40b9-8df3-2a03e49532c1/activity`

to the point of not even loading

-----

System: Chrome 71.0.3578 / Mac OS X 10.14.2
User: [See in registry](https://www.gbif.org/api/feedback/user/90b8b7ac8a0df0551b22d5c5212f5617:3f3c0e15a36ac563493f9113e6626a51f7e89ffb388ec720c0289e6ab79906e2a7f873585bfbb192aacd06651fe00f909d73186f5987838a7250af30e2a91dae)
Referer: https://www.gbif.org/dataset/e6fab7b3-c733-40b9-8df3-2a03e49532c1/activity
Window size: width 1523 - height 871
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-22T09:40:13.220Z',mode:absolute,to:'2019-02-22T09:46:13.220Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-22T09:40:13.220Z',mode:absolute,to:'2019-02-22T09:46:13.220Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Yes it is very slow! When i called the API it took 58.21 seconds to load https://api.gbif.org/v1/occurrence/download/dataset/e6fab7b3-c733-40b9-8df3-2a03e49532c1?limit=20&locale=en&offset=0 - So very likely that it will timeout.

**Comment by MattBlissett** [comment]
Performance might improve with the new database servers, or if not, with a partitioning scheme we'll be able to set up with the updated PostgreSQL version.

**Comment by MattBlissett** [comment]
Resolved with the new PostgreSQL servers, with their fancy NVMe storage and increased RAM.
