### ISSUE TITLE
Incorrect species listed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1795]
**Incorrect species listed**

Specimen image shows species is Inga yasuniana T.D.Penn not Inga yacoana as it is filed here

-----

System: Chrome 72.0.3626 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/10bd6babff4745571f5d76eaf862a57b:ecdcad46bec741d1f222617dddcacffa513ef2caa61211c53cf0d99a7caef9e8e03c5e1e2d5cae061f2779275317f098d6f4f099d3ac61eb641f6048f907fce3)
Referer: https://www.gbif.org/occurrence/1563325100
Window size: width 2560 - height 1249
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-22T12:32:05.349Z',mode:absolute,to:'2019-02-22T12:38:05.349Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-22T12:32:05.349Z',mode:absolute,to:'2019-02-22T12:38:05.349Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I forwarded the feedback via the MNHN feedback system [here](https://collections.nmnh.si.edu/search/botany/?ark=ark:/65665/3d382db59c35640eab5c05561861540c4).
