### ISSUE TITLE
Missing project_id SOLR search parameter in Registry API

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#18]
**Missing project_id SOLR search parameter in Registry API**

While maintaining API documentation in the current and demo portals, this issue serves as a reminder that we need to port the anticipated fix for http://dev.gbif.org/issues/browse/POR-3205

-----
fbitem-79134785ef60aca67184f0d6352302a982e0c66d
Reported by: @kbraak
System: Firefox 50.0.0 / Mac OS X 10.10.0
Referer: http://demo.gbif.org/developer/registry
Window size: width 1432 - height 1006

**Comment by mdoering** [comment]
this done in the latest api release and the master branch of registry

**Comment by MortenHofft** [comment]
i have added it in the api docs : https://github.com/gbif/portal16/commit/088ab37681ef5367726eff66ff52a5e063d8f212
and will close.
Links however are dead and have been all along it seems. see https://github.com/gbif/portal16/issues/196
