### ISSUE TITLE
I can't register!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#180]
**I can&#39;t register!**

I put my info in but it won&#39;t let me register!

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
Reported by: jt1016@ic.ac.uk
System: Safari 10.1.0 / Mac OS X 10.12.4
Referer: https://demo.gbif.org/occurrence/download?has_coordinate=true&has_geospatial_issue=false&taxon_key=2763050&advanced=1
Window size: width 1580 - height 827
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-27T16:05:13.212Z',mode:absolute,to:'2017-04-27T16:11:13.212Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-27T16:05:13.212Z',mode:absolute,to:'2017-04-27T16:11:13.212Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Contacted by email.

@MortenHofft, there are quite a few of these, one every day or two.  Can you direct people to WWW to register?

**Comment by MortenHofft** [comment]
Yes - I accidentally removed the redirect to prod last week.

**Comment by MortenHofft** [comment]
user informed about fix
