### ISSUE TITLE
ES: Spanish unfinished priority 1 translations

### ISSUE THREAD

**Issue by akristensen** [gbif/portal-feedback#1800]
- [x] [Contacts](https://www.gbif.org/es/contact-us)

**Comment by akristensen** [comment]
Thank you @WUlate

**Comment by akristensen** [comment]
related bug https://github.com/gbif/portal-feedback/issues/1802

**Comment by MortenHofft** [comment]
closed as duplicate of https://github.com/gbif/portal-feedback/issues/1802

**Comment by akristensen** [comment]
Tak @MortenHofft
