### ISSUE TITLE
JA: Japanese unfinished priority 1 translations

### ISSUE THREAD

**Issue by akristensen** [gbif/portal-feedback#1802]
- [x] [Contacts](https://www.gbif.org/ja/contact-us)

**Comment by akristensen** [comment]
@ktotsu
thank you so much Kumiko for your great help, have you considered translating the bit about contacting the Secretariat?

**Comment by ktotsu** [comment]
@akristensen 
Translation is done a while ago, but it only works in the preview. Japanese contents appears for a second but it automatically changes to English. It seems other languages have the same problem too.

**Comment by kcopas** [comment]
Just noticed that yesterday. We’ll investigate…

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
