### ISSUE TITLE
May I get access to the tif-file of the plant/animal's worldwide-occurence map?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1804]
**May I get access to the tif-file of the plant/animal&#39;s worldwide-occurence map?**

Hi! This is Ping. I am looking for global grid-based plant/ animal distribution datasets for my academic research work. I will be really appreciative if I can get access to the tif file of the global-occurence map of each taxa group as showed on the following link: `https://www.gbif.org/occurrence/map.`
 Thank you very much!

-----

User provided contact info: lynpid@163.com
System: Sogou Explorer 1.0.0 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/9910d9ffccf9aae21bfdef8ac4bb1f28:5c340c9cff4b5ff66e16617c553aa8cc195c73bfd9d94afc74eb3b3c8b47ef4818a24b49bb267ec18720ca80f7c71a6b229f5ef1b43f3bcfa272ff3dc8270cb6)
Referer: https://www.gbif.org/occurrence/map
Window size: width 1440 - height 692
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-26T15:47:01.691Z',mode:absolute,to:'2019-02-26T15:53:01.691Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-26T15:47:01.691Z',mode:absolute,to:'2019-02-26T15:53:01.691Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by dnoesgaard** [comment]
Sent response by email (Maps API).
