### ISSUE TITLE
Missing University of Cambridge data and spurious? citations

### ISSUE THREAD

**Issue by rdmpage** [gbif/portal-feedback#1805]
Two possibly related problems with the page for the University of Cambridge.

The first is that the page https://www.gbif.org/publisher/d9ccac00-9bc7-11de-a329-b8a03c50a862 lists no occurrences and no datasets, but 20 citations:
<img width="429" alt="screenshot 2019-02-26 21 00 37" src="https://user-images.githubusercontent.com/83306/53445929-9aef4700-3a09-11e9-8a52-cc2695daa382.png">

It is possible that Cambridge have done something at their end that prevents any GBIF harvesting from happening.

The second problems is that when I click on any of the 20 citations Cambridge data https://www.gbif.org/resource/search?contentType=literature&publishingOrganizationKey=d9ccac00-9bc7-11de-a329-b8a03c50a862 I don't see any Cambridge datasets listed, e.g. https://www.gbif.org/occurrence/download/0000659-150211104439307. Is this because there are currently no Cambridge datasets available on GBIF, and the web site is filtering out those datasets from the list of datasets cited?

**Comment by timhirsch** [comment]
I happen to know the answer to this: the University Museum of Zoology, Cambridge previously published a dataset of its specimens, but it was taken down when they did not comply with the requirement to adopt a mandatory Creative Commons licence, introduced about three years ago. This was at a time when the museum was undergoing a major refurbishment and data issues were not prioritized. I recently visited the museum and started discussions which hopefully will lead to the dataset being republished soon through our partners in Vertnet, with additional digitized specimens. The citations still show from downloads ordered before the dataset was withdrawn. In fact if you look at the list of datasets in that download you will see 'UMZC Zoological Specimens' which is the dataset that was withdrawn in 2016.

**Comment by MattBlissett** [comment]
I'm closing this, as although there's potentially work for participation, it doesn't belong as a bug report with GBIF's systems.
