### ISSUE TITLE
"Distribution invalid"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1806]
**&quot;Distribution invalid&quot;**

Dear colleagues, we have recently published a checklist dataset,   and there is one issue with almost all records: "distribution invalid". Could you please make comments on this, why this happens?
`https://www.gbif.org/species/152603162`

-----

User provided contact info: filippova.courlee.nina@gmail.com
System: Chrome 72.0.3626 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5742b0d19bbfd4707acfde4867080628:e08ffe76d9f13dcbdae3a82b6e2340408f724ab42431471e4dec83776aed76fbb799d79928215b58b6c510467f96c9cf80fbd4f4b60699a31792f825d7926c4b)
Referer: https://www.gbif.org/
Window size: width 1455 - height 644
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-28T06:31:41.077Z',mode:absolute,to:'2019-02-28T06:37:41.077Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-28T06:31:41.077Z',mode:absolute,to:'2019-02-28T06:37:41.077Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> Thank you for your question on GitHub. I checked the State Cadastr Animal Monitoring in Yuganskiy Nature Reserve (1988-2018) checklist and it seems that the system flags the distribution as invalid because of the [occurrenceStatus](https://dwc.tdwg.org/terms/#dwc:occurrenceStatus) field.
This field can contain only two values “present” or “absent”. Perhaps you could integrate the current content of this field in the occurrenceRemarks?
