### ISSUE TITLE
This taxon is wrongly accepted check databases.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1807]
**This taxon is wrongly accepted check databases.**

H. ambiguum and H. lamarcki and other synonims to this taxon are badly agregated into de the dataset please check it out. Regards, Joshua

-----

System: Chrome 72.0.3626 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/a8016542d582be44882db6cf63cece1e:eca948f8fcc395578ffc44dca4514e76604e6024eea0101d659a40d4b888c03b6f0c9d8b01a981f0921b28ac5ee79614d58997ee189c10a8904770f9d61a2614)
Referer: https://www.gbif.org/occurrence/1416604883
Window size: width 1920 - height 969
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-28T16:03:21.129Z',mode:absolute,to:'2019-02-28T16:09:21.129Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-28T16:03:21.129Z',mode:absolute,to:'2019-02-28T16:09:21.129Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by yroskov** [comment]
GBIF taxonomy does not match CoL taxonomy for the species: http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/ec0b50211525558c3081d9181ee4d179/synonym/f63fb8596197575b6955598e571b59ed

**Comment by ManonGros** [comment]
I am not sure if I understand the issue but I can see that the new backbone follows the CoL for this species: https://www.gbif.org/species/3145265
