### ISSUE TITLE
How to get all species occurrences with API

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1808]
**How to get all species occurrences with API**

Can the API be used to return all occurrences for a given species rather than data for a single occurrence? I'd like to input a species and output all data for all occurrences of that species. I would prefer to do this through the API rather than occurrence downloads because my project requires searching many taxa over all living domains.

-----

User provided contact info: ariel.tarrand@ufl.edu
System: Chrome 72.0.3626 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/68c99f55c84513690ca289014cd558ac:dd996e7f7e39b420d0a74c6ae39423a0d5fddde76c694f4cbb6313a1b168a41d2e1d74713ab26640b593e64ee150e1e787f8cf4373a779d09372959f0066503a)
Referer: https://www.gbif.org/occurrence/download?taxon_key=4
Window size: width 1536 - height 722
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-28T21:09:37.729Z',mode:absolute,to:'2019-02-28T21:15:37.729Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-02-28T21:09:37.729Z',mode:absolute,to:'2019-02-28T21:15:37.729Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by dnoesgaard** [comment]
Email to user:
> Yes, you can get occurrences via the API. Say you wanted all occurrences for Chromista:
> 
> http://api.gbif.org/v1/occurrence/search?taxon_key=4
> 
> This API provides services for searching occurrence records that have been indexed by GBIF. In order to retrieve all results for a given search filter you need to issue individual requests for each page, which is limited to a maximum size of 300 records per page. Note that for technical reasons we also have a hard limit for any query of 200,000 records. You will get an error if the offset + limit exceeds 200,000. To retrieve all records beyond 200,000 you should use our asynchronous download service instead. If use the download service, a DOI will be created for each download for use in citing the data in publications.
> 
> The API documentation is available here:
> https://www.gbif.org/developer/occurrence
>
