### ISSUE TITLE
All data in one column

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1809]
**All data in one column**

Hi there,

I downloaded a fairly large dataset on the Epipactis helleborine orchid in Canada (E. helleborine + Canada necessary). The csv I downloaded had all the 1600 data points but all of the data from all of the columns was in the first column. 

How can this be fixed? Please get back to me asap.

Thank you,
D

-----

User provided contact info: @dorozthy
System: Chrome 72.0.3626 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/d283aa59618825a1acab9098f34f5d00:3cec2599d85df0bc49787a860b58a728a4ca9f11a58001b95b1e2bb9cf494d78c717ba1c835785dab129828cec21003ffbabeb513c0edf38051812a1af899028)
Referer: https://www.gbif.org/faq
Window size: width 1440 - height 765
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-01T05:12:13.733Z',mode:absolute,to:'2019-03-01T05:18:13.733Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-01T05:12:13.733Z',mode:absolute,to:'2019-03-01T05:18:13.733Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by dnoesgaard** [comment]
Hi @dorozthy 

The columns in the downloaded file are separated by tabs. Depending on what spreadsheet application you use, you may need to import the data slightly different. For example, on my Mac, double-clicking the CSV file opens the Numbers app and the data looks fine, e.g.

![screenshot 2019-03-01 at 10 20 57](https://user-images.githubusercontent.com/21358085/53628666-f5f08c00-3c0b-11e9-85ff-6788cd7b3774.png)

If you use Excel, here's a few tips that might help you:
https://www.gbif.org/faq?question=opening-gbif-csv-in-excel

**Comment by MortenHofft** [comment]
See also https://github.com/gbif/occurrence/issues/100
