### ISSUE TITLE
Data use numbers heading needs context

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#181]
**Data use numbers heading needs context**

The subheading on each of the Data Use pages (in this case &#39;338,945 species occurrences&#39;) needs some further contextual text or users will not understand what is referred to here. One option is to include the label for this field: &#39;Data resources used via GBIF:&#39; OR page authors should include this in free text, e.g. &#39;338,945 species occurrences used&#39;. The former is preferable, to avoid lots of re-authoring of existing pages.

-----
fbitem-106a321c0ced94c2078c6f3a18b7b446585e73e5
Reported by: thirsch@gbif.org
System: Chrome 57.0.2987 / Mac OS X 10.10.5
Referer: https://demo.gbif.org/data-use/2016-harris-et-al?utm_content=bufferad75d&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer
Window size: width 1600 - height 798
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-28T13:36:41.563Z',mode:absolute,to:'2017-04-28T13:42:41.563Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-28T13:36:41.563Z',mode:absolute,to:'2017-04-28T13:42:41.563Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I see what you mean. It might be difficult to find one that works well with all items though. Examples of how the field has been used:

* 1341 bat occurrence records used in model
* Records accessed from GBIF and other sources
* 24 breeding-season specimens
* More than 20 million species records
* 356 taxa
* 45,000 species occurrences (estimate)

I'll add the label, and then we can change the wording as you guys see fit.

**Comment by MortenHofft** [comment]
It is live and as per requested https://demo.gbif.org/data-use/83283/origins-of-renaissance-medicine. 

I'm closing, but please reopen if wording or layout needs changing.
