### ISSUE TITLE
Download SIMPLE_CSV is not properly delimited

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1810]
**Download SIMPLE_CSV is not properly delimited**

Just for some basic data exploration I was downloading records of species occurrence just to find that they are not properly delimited (e.g. by separators such as ";" or ";" or "/" etc.). 
Here is the first entry to my table:
"gbifID	datasetKey	occurrenceID	kingdom	phylum	class	order	family	genus	species	infraspecificEpithet	taxonRank	scientificName	countryCode	locality	publishingOrgKey	decimalLatitude	decimalLongitude	coordinateUncertaintyInMeters	coordinatePrecision	elevation	elevationAccuracy	depth	depthAccuracy	eventDate	day	month	year	taxonKey	speciesKey	basisOfRecord	institutionCode	collectionCode	catalogNumber	recordNumber	identifiedBy	dateIdentified	license	rightsHolder	recordedBy	typeStatus	establishmentMeans	lastInterpreted	mediaType	issue"

Since most software uses proper delimiting symbols (and can be set easily to whatever symbol one may choose) I was wondering if there is a mistake with the GBIF-CSV generation?

Or is their an intention behind this type of file?

When importing lat/long coordinates it would be considerably easier to do it with proper delimitation, as mentioned before.

I am a novice at gbif and most everything else so please forgive me if this is a stupid question ;)

-----

User provided contact info: glasermichael514@gmail.com
System: Safari 12.0.3 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/cafeff8aea51a26f4ce346864907ae17:013f68574e2072a9e59fc5dfa49a67ce97b6ad46ec148311023158207f4c4bfd9bcca2ac76b613e1ff6b5794c54316ebd733bfd1d9d56164cc1b19d183da8b15)
Referer: https://www.gbif.org/health
Window size: width 1280 - height 714
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-01T09:57:45.308Z',mode:absolute,to:'2019-03-01T10:03:45.308Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-01T09:57:45.308Z',mode:absolute,to:'2019-03-01T10:03:45.308Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by dnoesgaard** [comment]
> Hi,
> 
> The CSV files downloaded from GBIF.org are tab-separated. If opening the file e.g. Excel, this may be helpful: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
> 
> Kind regards,
>
