### ISSUE TITLE
Taxonomic name correction

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1811]
**Taxonomic name correction**

In this record the species name is incorrectly spelled - `https://www.gbif.org/occurrence/656957660.`

The correct spelling is caruleopunctatus as in the original record.  See `https://www.fishbase.de/summary/Epinephelus-coeruleopunctatus.html` and `http://researcharchive.calacademy.org/research/ichthyology/catalog/fishcatget.asp?spid=15895.`

Thanks

Andy

-----

User provided contact info: abentley@ku.edu
System: Chrome 72.0.3626 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5aff42c55a99295375f2535b76e898a5:71536419deb9e4208d253696031feb6ae7e055422e24f2fec60b8db4b79950278c6fbc5c8a73d00e44901c8693116d5c0d2aa149bdf5fac8bc895b1a7590e1ba)
Referer: https://www.gbif.org/occurrence/656957660
Window size: width 2133 - height 1409
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-01T18:51:44.026Z',mode:absolute,to:'2019-03-01T18:57:44.026Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-01T18:51:44.026Z',mode:absolute,to:'2019-03-01T18:57:44.026Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by yroskov** [comment]
"Epinephelus caerulEEopunctatus" is given as an orthographic variant among semantic synonyms in CoL-FishBase. Nothing wrong in CoL.

**Comment by ManonGros** [comment]
This is strange, we actually have caruleopunctatus in the taxonomy: https://www.gbif.org/species/2388316
But for some reason we "fuzzy match" the species to its synonym/spelling variant https://www.gbif.org/species/7815292

**Comment by MattBlissett** [comment]
CoL, Fishbase, GBIF etc have *Epinephelus c**o**eruleopunctatus* as the accepted name.

The source data is *Epinephelus c**a**eruleopunctatus*.

We match to the accepted name in this case, rather than the variant.

**Comment by ManonGros** [comment]
It looks like this has been solved with the newest backbone update (https://www.gbif.org/species/2388139)
