### ISSUE TITLE
Osmiopsis plumieri - double entry due to a orthoraphic variant of the Authors name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1812]
**Osmiopsis plumieri - double entry due to a orthoraphic variant of the Authors name**

-----

System: Firefox 65.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7cde9c625e49ecae81420935b9b8c65f:658749919e26a0677ca16c2ff0f109b7a275563b0c2f063f8531b684e925ff764848728d52aafeef8501621351e53a7e0457bef73c6d5cb9e2bb41145e7302c9)
Referer: https://www.gbif.org/search?q=Osmiopsis%20plumieri
Window size: width 1366 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-01T19:47:47.978Z',mode:absolute,to:'2019-03-01T19:53:47.978Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-01T19:47:47.978Z',mode:absolute,to:'2019-03-01T19:53:47.978Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
I can see only one entry for this species now: https://www.gbif.org/species/9300336
