### ISSUE TITLE
Good day! We have registered our organization - https://www.gbif.org/publisher/030a5850-a526-467b-9839-6c27aa204677 .  But did not get the password for association with IPT. Can you please tell me how to get a password?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1814]
**Good day! We have registered our organization - `https://www.gbif.org/publisher/030a5850-a526-467b-9839-6c27aa204677` . But did not get the password for association with IPT. Can you please tell me how to get a password?**

-----

System: Firefox 52.0.0 / FreeBSD 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/0fd667c300b5539ac811841c2a1c3597:c218b515d7ce3405b3d9f6a7661de3cf2e13ab8399890ff20720bdd6b8c7a131753e7956190caef03846aa3fbcd8110e2988771d1e6489b42e0dd7e66ed4ef39)
Referer: https://www.gbif.org/publisher/030a5850-a526-467b-9839-6c27aa204677
Window size: width 1252 - height 621
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-04T09:51:12.491Z',mode:absolute,to:'2019-03-04T09:57:12.491Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-04T09:51:12.491Z',mode:absolute,to:'2019-03-04T09:57:12.491Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
