### ISSUE TITLE
Recorded data mismatch although no mismatch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1815]
**Recorded data mismatch although no mismatch**

Could it be due to the fact that the `eventDate` field includes and event time?

-----

User provided contact info: @ManonGros
System: Safari 12.0.3 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/0ae182a6c9c40f9c0eba2ac8a0043192:ec337a7538e6121f6f52cbb70e0443facb635f01531e915f40199ab53817b898862027ae8a954b3856952aa618a30bdd70dafd3e4a7e46181d7081aa4388e284)
Referer: https://www.gbif.org/occurrence/1851000147
Window size: width 1510 - height 950
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-04T14:57:13.790Z',mode:absolute,to:'2019-03-04T15:03:13.790Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-04T14:57:13.790Z',mode:absolute,to:'2019-03-04T15:03:13.790Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
This now has an invalid flag, since the date format is unusual (non-ISO). There's a `:` for the milliseconds, when ISO format says it should be a `.`. 

The result is reasonable though.
