### ISSUE TITLE
strange occurrence download page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1817]
**strange occurrence download page**

I have a few examples of odd downloads, including this one.

1) no citation shown although 1 exists: `https://www.gbif.org/api/resource/search?contentType=literature&gbifDownloadKey=0013539-171219132708484`
2) predicates shown as clear text (perhaps because it's too big?)

-----

User provided contact info: @dnoesgaard
System: Chrome 72.0.3626 / Mac OS X 10.14.2
User: [See in registry](https://www.gbif.org/api/feedback/user/5699fa7b477dfb0fc0642c23906555a2:97d90fa3f18582830c0154fae34f483261abf1709da67105c507c251bd6da6b72b536421bece93c4b54d29f6056d64c13285e46411dde2ffb7e85d3e115f686c)
Referer: https://www.gbif.org/occurrence/download/0013539-171219132708484
Window size: width 2560 - height 1221
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-05T10:00:45.408Z',mode:absolute,to:'2019-03-05T10:06:45.408Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-05T10:00:45.408Z',mode:absolute,to:'2019-03-05T10:06:45.408Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
regarding 2: yes, it is too big and cause issues for the APIs and browser if rendered. The raw json fallback was introduced as some downloads had hundreds of names and that caused issues. So it is a deliberate choice. If we believe it is a problem that should be fixed, then we can revisit that decision. If so please reopen in a new issue.

**Comment by dnoesgaard** [comment]
no issue, just curious.

1 is more interesting...
