### ISSUE TITLE
Freshwater Invertebrate Master Taxon list for South Africa

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1818]
**Freshwater Invertebrate Master Taxon list for South Africa**

How would I extract a Master Taxon list, giving each level of the taxonomic hierarchy, for freshwater invertebrates from South Africa.

-----

User provided contact info: helen@frcsa.org.za
System: Firefox 66.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/29e6f33af380ae133825c31b3cbc8645:fe987a353d823b9f4c4b7c207092f01d3b08a8beed75be34b040bd2f84e35fd2adccd8183dbf0d6cc77a49a2bcf74efadc998aa0983e2297dd49f02286ef47f7)
Referer: https://www.gbif.org/search
Window size: width 1536 - height 728
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-05T11:13:51.148Z',mode:absolute,to:'2019-03-05T11:19:51.148Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-05T11:13:51.148Z',mode:absolute,to:'2019-03-05T11:19:51.148Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ahahn-gbif** [comment]
response sent by email (copy to helpdesk)
