### ISSUE TITLE
Show verbatim EML citation for CoL constituents

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1819]
**Show verbatim EML citation for CoL constituents**

The citation shown for CoL consituents should be the exact one provided in the EML citation field - if existing. This is a highly sensitive area and ideally is fixed before the Global Team meeting mid march. 

We also need to reindex CoL once their dwca download service is patched with updated citations

-----

System: Chrome 72.0.3626 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/2aaa4e3ebd24b98c4276fc2826f2cc67:db3f156e34247ae052d7a0c133c7abe64e509afbf823bde918f60485171a1065060fadd7920f9e134d147c03d8be1f12127139e2addd28e7a18d291126d3319a)
Referer: https://www.gbif.org/dataset/d48ff091-3c56-4b0f-8f46-14958e7d4395
Window size: width 1523 - height 821
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-05T16:01:19.116Z',mode:absolute,to:'2019-03-05T16:07:19.116Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-05T16:01:19.116Z',mode:absolute,to:'2019-03-05T16:07:19.116Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by timrobertson100** [comment]
I don't believe @MortenHofft would be able to address this. I presume this is set [in this section of the registry](https://github.com/gbif/registry/blob/master/registry-ws/src/main/java/org/gbif/registry/ws/resources/DatasetResource.java#L651)

**Comment by mdoering** [comment]
I'm attaching the zipped archive with just the EML but without data
[archive-complete-emlonly.zip](https://github.com/gbif/portal-feedback/files/2931740/archive-complete-emlonly.zip)

In the case of ThripsWiki this is:
```
<gbif>
	<dateStamp>2019-02-27T02:04:42+00:00</dateStamp>
	<citation identifier="http://www.catalogueoflife.org/col/info/cite" >Species 2000 &amp; ITIS Catalogue of Life: 26th February 2019, ThripsWiki</citation>
	<resourceLogoUrl>http://www.catalogueoflife.org/col/images/databases/ThripsWiki.png</resourceLogoUrl>
</gbif>
```

**Comment by mdoering** [comment]
yes, that is a generated citation on our portal

**Comment by MortenHofft** [comment]
Yes, the citation shown is simply the one provided in the dataset API. We decided that the logic of citation shouldn't be in the portal as there is also API users that should see the correct citation.

**Comment by mdoering** [comment]
registry change works with CoL EML:
http://api.gbif-dev.org/v1/dataset/cdba6733-3cf1-47cc-84e3-758ae0935da6/document
