### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#182]
**Unable to register**

It just won&#39;t let me register properly and I don&#39;t know why.

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
Reported by: mbuckley424@gmail.com
System: Chrome 58.0.3029 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/download?taxon_key=2882481
Window size: width 1600 - height 780
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-30T03:17:47.076Z',mode:absolute,to:'2017-04-30T03:23:47.076Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-30T03:17:47.076Z',mode:absolute,to:'2017-04-30T03:23:47.076Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
User informed per mail. Issue fixed
