### ISSUE TITLE
where can I  find the taxonkey of each taxon?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1820]
**where can I find the taxonkey of each taxon?**

Hi! This is Ping. I was trying to use the URL to download the map of occurrences but I didn't know what excatly the taxonkey was. The website page `https://www.gbif.org/developer/maps` only give a rough desciption of the meaning of the parameters. Would you please help me find the taxonkeys of all taxons? 
Thank you so much!

-----

User provided contact info: lynpid@163.com
System: Sogou Explorer 1.0.0 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/cd46c015e856ced2b371c30d881c1194:680f2c08934f99f2b7322eb367c0ad6be4322c4a5a851aa5d82f88d5525eb112ade159f9e5b5683394f99d6353bb89e26c9e6365fca76c26af636b21a6dc2f5b)
Referer: https://www.gbif.org/developer/maps
Window size: width 1440 - height 692
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-06T05:42:30.947Z',mode:absolute,to:'2019-03-06T05:48:30.947Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-06T05:42:30.947Z',mode:absolute,to:'2019-03-06T05:48:30.947Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Replied by email:
>Taxon keys refer to  taxa in our system and are necessary to use the GBIF API. You can access the key for one given taxon by looking at the URL for a taxon page. For example, the page for Apis mellifera Linnaeus, 1758 is the following: https://www.gbif.org/species/1341976 and the key is “1341976”.
If you would like to get the keys for more than one taxon, I suggest that you use our species matching tool here: https://www.gbif.org/tools/species-lookup. This tools matches scientific names to the GBIF taxonomy and returns the corresponding taxon key (you can download the result in a CSV format).
An alternative would to use our species API, don’t hesitate to check the documentation available [here](https://www.gbif.org/tools/species-lookup).
