### ISSUE TITLE
Coordinates flipped in Turkey butterfly dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1823]
**Coordinates flipped in Turkey butterfly dataset**

Judging by the shape of the data points this looks like a 90 degree rotation of the map of Turkey, so I suspect all records have lat/long flipped.

-----

User provided contact info: @timhirsch
System: Mobile Safari 12.0.0 / iOS 12.1.4
User: [See in registry](https://www.gbif.org/api/feedback/user/7fb5f0621b40db866647e0aed44a223b:e56ac5d096bbcf7d9d874ac7e5dd87c14773f7bc64dec8b409b08ba7812434007dbf54a7e09bb0cfec0895257d832427194255cb7c4b45b97c6d7b6a0eb25dd0)
Referer: https://www.gbif.org/dataset/758afb5f-11c9-44f8-8bff-294169123910
Window size: width 1366 - height 985
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-06T23:25:26.063Z',mode:absolute,to:'2019-03-06T23:31:26.063Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-06T23:25:26.063Z',mode:absolute,to:'2019-03-06T23:31:26.063Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
I don't see the issue, perhaps it has been corrected already? Tell me if I am wrong.

**Comment by timhirsch** [comment]
Indeed it has been corrected since last night. Turkey is right-side up! phew
