### ISSUE TITLE
Github status endpoint changed?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1824]
**Github status endpoint changed?**

Looks like there's a new endpoint for Github status:
`https://www.githubstatus.com/api/v2/status.json`

-----

User provided contact info: @dnoesgaard
System: Chrome 72.0.3626 / Mac OS X 10.14.2
User: [See in registry](https://www.gbif.org/api/feedback/user/e84c470bab7bba43f67072d04587ade1:7c918dae05cb6a3378e8a939f2cbcbeff8f9c07579c5c0e4345076d6b518ae39f93a2a6fb3edd8104317f354fe557f889e2122b7d25523300ab95629eee746d5)
Referer: https://www.gbif.org/health
Window size: width 2192 - height 1007
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-07T08:37:50.936Z',mode:absolute,to:'2019-03-07T08:43:50.936Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-07T08:37:50.936Z',mode:absolute,to:'2019-03-07T08:43:50.936Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/217401489bb37cf4cb5b1b90d05957a00b36d57b
