### ISSUE TITLE
Links to EOL

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1826]
**Links to EOL**

Links out to EOL return missing pages

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b824489c073cc9866c52ab48c3516a57:2c5283b437e3724cb721ca266d26b78927e9ef48f0dbd45e0a17fcce4464722d60f345a3654ca019fc3ac82980c0e200ba665dc07bfdaa5f3bfebdfc861ecd73)
Referer: https://www.gbif.org/species/1424038
Window size: width 2048 - height 1025
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-07T16:01:56.501Z',mode:absolute,to:'2019-03-07T16:07:56.501Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-07T16:01:56.501Z',mode:absolute,to:'2019-03-07T16:07:56.501Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/1c0e702f6db7cf13cacb71d38bd189c4e19d5173
