### ISSUE TITLE
I can't login or register.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#183]
**I can&#39;t login or register.**

I have an account in your previous site. And i can&#39;t login or register here. Why?

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
Reported by: piruvat1@gmail.com
System: Opera 44.0.2510 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/download?taxon_key=3495613
Window size: width 1536 - height 728
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-30T09:29:05.493Z',mode:absolute,to:'2017-04-30T09:35:05.493Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-04-30T09:29:05.493Z',mode:absolute,to:'2017-04-30T09:35:05.493Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
inform per mail. issues fixed
