### ISSUE TITLE
I'm trying to find out how the "Coordinate Uncertainty" is determined in my occurrence data set. Can you explain or provide a web link about the topic? Not obvious on web site.thank you

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1830]
**I&#39;m trying to find out how the &quot;Coordinate Uncertainty&quot; is determined in my occurrence data set. Can you explain or provide a web link about the topic? Not obvious on web site.thank you**

-----

User provided contact info: fdblouin@gmail.com
System: Chrome 72.0.3626 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/2a5903f88cdc987d97bbce05ff5dd115:11514d1734d0ff27c0e719b735aaca457b4e904bc5a3c84f9a94f3f39b9d7d75835d78c882c05f7b847eb83f3edde0f09508753918a48921142c2164028c8347)
Referer: https://www.gbif.org/resource/search?contentType=tool
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-12T17:46:55.689Z',mode:absolute,to:'2019-03-12T17:52:55.689Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-12T17:46:55.689Z',mode:absolute,to:'2019-03-12T17:52:55.689Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Replied by email:
> The definition of the coordinate uncertainty and other Darwin core terms can be found [here](https://dwc.tdwg.org/terms/#dwc:coordinateUncertaintyInMeters).
