### ISSUE TITLE
Button to get back to dataset frontpage

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1831]
**Button to get back to dataset frontpage**

From any view of data (table, gallery etc.), it would be really nice if it were possible to klick on a button and get back to the current datasets' frontpage. - or maybe it's possible already, but I can't find it :-)

-----

User provided contact info: @DanBIF
System: Chrome 72.0.3626 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/c4c28e089f8b8309300bd51d03dba586:6a152083b5a73597ff21b40e3dc47e5819cc854845e3ef1f26bc13306cc1ba085a4d9de875c06fff8db1c3f099f49a71731c5400c5942172e5607f52a5214b60)
Referer: https://www.gbif.org/occurrence/search?taxon_key=2311913
Window size: width 2560 - height 1297
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-13T09:55:51.909Z',mode:absolute,to:'2019-03-13T10:01:51.909Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-13T09:55:51.909Z',mode:absolute,to:'2019-03-13T10:01:51.909Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
Currently to get to a dataset from an occurrence search, you need to click the occurrence in case and from there go to the dataset. Similar if you want to go to the species page.

I'm not entirely sure what is meant by "current dataset" as an occurrence search result often spans many datasets. Could you expand a bit please?
