### ISSUE TITLE
Links to topic-filtered use cases from 'what is GBIF?' return no results.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1834]
**Links to topic-filtered use cases from &#39;what is GBIF?&#39; return no results.**

The links on this page to publications on impacts of climate change, invasive species, conservation, human health etc currently get zero results from the literature pages.

-----

System: Chrome 72.0.3626 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/75e06688d619c315cb40731a1b716dcb:310f8dd9b4452f46ce24ce02e6b2bb5918bf9948d16e0df33aace013130cbc52c1c1413d567e0a15d5cee042e2c89845bcd94ecc031ac47566bd0a5651b3ef42)
Referer: https://www.gbif.org/what-is-gbif
Window size: width 1201 - height 694
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-13T15:45:31.360Z',mode:absolute,to:'2019-03-13T15:51:31.360Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-13T15:45:31.360Z',mode:absolute,to:'2019-03-13T15:51:31.360Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by kcopas** [comment]
Thanks for the alert. Links corrected.
