### ISSUE TITLE
Number of records inconsistent for checklists between dataset page and project page

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#1835]
For example, [this checklist](https://www.gbif.org/dataset/d98c3efe-983e-455f-8fdb-ccc76c7959c3) shows `279` records on the dataset page and `333` records on the preview on the [project page](https://www.gbif.org/project/1YbRi07NuQ8skM4E46sIY6/digitizing-the-matobo-hills-arachnid-collections-at-the-natural-history-museum-of-zimbabwe#datasets) (see screenshots).
![dataset_page](https://user-images.githubusercontent.com/7677271/54344462-2fc88600-4641-11e9-978c-12174a23d870.png)
![project_page](https://user-images.githubusercontent.com/7677271/54344469-348d3a00-4641-11e9-9158-1af610df859a.png)
It looks like one number corresponds to the number of records in the checklist and the other one adds the higher ranks. The difference is the `Denormed classification` (see screenshot below). Would it be possible to have the same numbers?
![difference_in_number_checklist](https://user-images.githubusercontent.com/7677271/54344556-6a322300-4641-11e9-903f-9b859d9386ec.png)

**Comment by MortenHofft** [comment]
one is source records, the other including inferred taxa. I guess it makes sense to filter both by source
