### ISSUE TITLE
Broken link to DatasetType enum

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1837]
**Broken link to DatasetType enum**

The link (`http://api.gbif.org/v1/vocabulary/DatasetType.html)` under "DatasetType enum" throws a 404 error.

-----

User provided contact info: @tucotuco
System: Chrome 72.0.3626 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/56e0ba23048ed0f0ddc099b405a74920:9e1e291a4a1b78c125afdd318ecaed1444e159ae06221effed636fed7a440599fefabf73f685294f936f8aa7c541eae2c6bf1ffdfc1dbad62332b698e05f5184)
Referer: https://www.gbif.org/developer/registry
Window size: width 1145 - height 590
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-14T19:18:11.312Z',mode:absolute,to:'2019-03-14T19:24:11.312Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-14T19:18:11.312Z',mode:absolute,to:'2019-03-14T19:24:11.312Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by tucotuco** [comment]
Suggest http://api.gbif.org/v1/enumeration/basic/DatasetType

**Comment by MortenHofft** [comment]
Thank you - I have changed it. It will be live in next production deployment.
