### ISSUE TITLE
About specimen LSUMZ 20313

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1839]
**About specimen LSUMZ 20313**

Dear sirs. The specimen of Thomasomys cinereus LSUMZ 20313 has a wrong locality and coordinates. Mr. Thomas K.R. collected several specimens of T. cinereus the same day but at "33 road km SW Huancabamba". Obviously this typo ended in a wrong coordinate point. This wrong locality would be the single locality of T. cinereus from Amazonas department, far from other known records. I have published an account about T. cinereus in the II SAM volume (Patton et al. Eds). See my account in Pacheco (2015) for the right distribution of the species. In case the locality is correct, I would doubt the specimen is T. cinereus. If possible, I would need a good photo of the specimen and skull to confirm. Thanks. Víctor Pacheco

-----

User provided contact info: vpachecot@unmsm.edu.pe
System: Firefox 65.0.0 / Mac OS X 10.13.0
User: [See in registry](https://www.gbif.org/api/feedback/user/8b02d28116777eed0cdc7ceffa819d7e:cf60bb7ba5b9d8e6d387fdd78fcef4a68e22482a0917c953b1389dfc56a53a1d1658ee60372276010b75a672b0c992a3cdd1443894d3fcd32fe72cdaf4445ff3)
Referer: https://www.gbif.org/occurrence/45912597
Window size: width 2509 - height 1236
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-15T15:51:52.225Z',mode:absolute,to:'2019-03-15T15:57:52.225Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-15T15:51:52.225Z',mode:absolute,to:'2019-03-15T15:57:52.225Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Feedback forwarded to VertNet on the corresponding GitHub repository.

**Comment by ManonGros** [comment]
Unless I am mistaken, this seems to have been corrected.
