### ISSUE TITLE
What's the meaning of the "Year" filter and the "Last interpreted" filter?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1843]
**What&#39;s the meaning of the &quot;Year&quot; filter and the &quot;Last interpreted&quot; filter?**

Hi, this is Ping! 
I am not very clear about the meaning of the "Year" filter ". Does it mean the "Year" that the occurence record be summited to the website? Or it means the periods of the species being existing? Besides, what about the "last interpreted" filter? Does it mean the latest time that the occurences data of species were updated? 
If I set the "Year" filter as "between 2005 to 2015", then I set the "last interpreted " fliter as after 2015, would I get the data of species that existing between 2005 to 2015 and that records are still vaild after 2015? 
Last but not least,  I would be really apreciated if you could explain to me the GBIF's definition of "occurence data" .
I am looking forward to your reply. Thank you for your time!

-----

User provided contact info: lynpid@163.com
System: Sogou Explorer 1.0.0 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/966e6b98c1d96dde4846fc5e575a224b:84faeaada581f8e5860cfdbc241bd80c04d2ea134d46b5d3275fedcfd215706db836814d9ba5bbd45a02cb5e85fa4e2ea178638bc5864deb27c7b66ea2f89663)
Referer: https://www.gbif.org/terms
Window size: width 1600 - height 812
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-18T02:13:38.504Z',mode:absolute,to:'2019-03-18T02:19:38.504Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-18T02:13:38.504Z',mode:absolute,to:'2019-03-18T02:19:38.504Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Replied by email (CCied Helpdesk).
