### ISSUE TITLE
Occurrence: 1675998895

### ISSUE THREAD

**Issue by aallspac** [gbif/portal-feedback#1844]
Occurrence: 1675998895 Chara papulosa Wallr., 1833

This was misinterpreted, the correct determination (not already in GBIF Taxonomy implemented):

Chara papillosa Kütz

Please change the species name andf taxonomic position.

If this should be not possible please tell me what I can do

best regards
Andreas

![GIBF_Charapapulosa](https://user-images.githubusercontent.com/37361337/54520909-0f166e00-496a-11e9-813c-fac5cbcef380.JPG)
![orginalbeleg_Senkenberg](https://user-images.githubusercontent.com/37361337/54520910-0faf0480-496a-11e9-9d5e-a278a5492f8e.JPG)

**Comment by ManonGros** [comment]
The newest backbone contains _Chara papillosa_ Kützing, 1834: https://www.gbif.org/species/7990539
So the scientific name of the occurrence is correct: https://www.gbif.org/occurrence/3046145271
