### ISSUE TITLE
"Incertae" family

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1845]
**&quot;Incertae&quot; family**

I don't think we ought to have this — if the family (within Plantae) is uncertain, we should just link to Plantae.

-----

User provided contact info: @MattBlissett
System: Firefox 65.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/c8293e015bd0358fe7927978c01665aa:c5848e610950c0fff68ffa68de677760d024619100b00decb52d3ee58094284e425bc7179c0c93d1ee499fc30b63caf313a204137f724cf3c12228d6dc2f2d90)
Referer: https://www.gbif.org/species/8626645
Window size: width 1440 - height 2424
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-18T13:08:41.231Z',mode:absolute,to:'2019-03-18T13:14:41.231Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-18T13:08:41.231Z',mode:absolute,to:'2019-03-18T13:14:41.231Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by mdoering** [comment]
added to nub blacklist: https://github.com/gbif/checklistbank/blob/master/checklistbank-nub/blacklist.tsv
