### ISSUE TITLE
Mapping error?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1846]
**Mapping error?**

"Recorded by" is an integer, is there an mapping error in data from naturgucker, see `https://www.gbif.org/occurrence/1848604211`

-----

User provided contact info: snorre.henriksen@artsdatabanken.no
System: Chrome 72.0.3626 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/78e5724cb2a7bc22ff2a654bffe0d2c8:856cff1e854aa4bd7bbb025ce17c9281cef8b93568f52bab1e0cb2b8e0be02736c5644cf9db2a95e84e9065a85ee34925c4f3c5fdbf0d94dabdbcc5ea4f8999e)
Referer: https://www.gbif.org/occurrence/1848604211
Window size: width 1920 - height 1089
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-19T07:30:06.345Z',mode:absolute,to:'2019-03-19T07:36:06.345Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-19T07:30:06.345Z',mode:absolute,to:'2019-03-19T07:36:06.345Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Publisher contacted by email.
