### ISSUE TITLE
Description DWCA-term Subgenus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1850]
**Description DWCA-term Subgenus**

I do not know if this is right place to mention this issue, but we were a bit confused with how to fill in the field Subgenus.
Looking at  `http://rs.tdwg.org/dwc/terms/#dwc:subgenus` it is suggested that the field  should contain Genus + Subgenus but in the examples there is only one value.

I noticed that the examples were recently changed (but the  description  has not be changed?). This concurs with the discussion `https://github.com/tdwg/dwc/issues/176`

Maybe both the description and the examples of the term Subgenus should be straigthened?

-----

User provided contact info: jeroen.creuwels@naturalis.nl
System: Chrome 72.0.3626 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/41e0d65424cf4ff6ede0ff0a0ab0a54c:d16311be1e89e4a6bf9c60c52ed96221db850268348ffc6c8d0bbad8ba1d88dfef9c6db78f7b872914189f84b74f614071a22945da9be2953455fef7bfb1adbc)
Referer: https://www.gbif.org/tools/data-validator
Window size: width 2312 - height 1025
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-20T11:16:55.127Z',mode:absolute,to:'2019-03-20T11:22:55.127Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-20T11:16:55.127Z',mode:absolute,to:'2019-03-20T11:22:55.127Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by tucotuco** [comment]
Hi Jooen,

The place to make the proposal is https://github.com/tdwg/dwc/issues. The
place to discuss the proposal to get it to a state where a concrete
proposal can be made is https://github.com/tdwg/dwc-qa/issues.

Cheers,

John

**Comment by jhnwllr** [comment]
I think this can be closed. @jeroencreuwels  any comment?

**Comment by jhnwllr** [comment]
Closing since this is a tdwg issue.

**Comment by jeroencreuwels** [comment]
OK, I'll look at it again, and will approach TDWG if needed
