### ISSUE TITLE
Handling true occurrence record absence data

### ISSUE THREAD

**Issue by jlegind** [gbif/portal-feedback#1851]
Referencing #1405 
Some of the datasets in GBIF have explicit absence records which we do not handle well at the moment.

By explicit absence I mean:

- individual count says numerical 0
AND
- occurrence status says  #"absent"

Example: https://www.gbif.org/occurrence/1657667800 

The goal is to hide these records from users unless they are specifically selected in a filter. If users download records these absences are _deselected_ by default. 

A few numbers from the GBIF index:

Count of records having **0 individualCount** with its 'occurrenceStatus' value:    
1709039  |  absent
149  |  Absent

Total true absence records = 1,709,188

**Comment by rukayaj** [comment]
GBIF Norway is interested in this functionality, let us know if there's anything we can do to help.

**Comment by rpfigueira** [comment]
It would also make it more transparent to the user if a filter could be created in the portal for the occurrenceStatus term. This is also an issue for some portuguese publisher which are sharing sample based data with significant number of true absences.

**Comment by peterdesmet** [comment]
How are the above described absence records (`individualCount` = 0 or `occurrenceStatus` = absent) _currently_ handled by the GBIF API?

**Comment by timrobertson100** [comment]
> How are the above described absence records (individualCount = 0 or occurrenceStatus = absent) currently handled by the GBIF API?

They pass through with an attempt to create a numeric value from the `individualCount`. This puts the burden of interpretation on the consumer.

I am going to open an issue on the pipeline project and propose a solution. I'll link it here shortly.

**Comment by timrobertson100** [comment]
I recognize this does not solve all issues, but I'd appreciate suggestions to improve this proposal, which I believe is relatively simple to produce and would improve the current situation

https://github.com/gbif/pipelines/issues/268

**Comment by MattBlissett** [comment]
The backend work has been completed, and the frontend (portal) implementation will follow shortly.  

- https://api.gbif.org/v1/occurrence/search?occurrenceStatus=PRSENT
- https://api.gbif.org/v1/occurrence/search?occurrenceStatus=ABSENT
- https://api.gbif.org/v1/occurrence/search?issue=INDIVIDUAL_COUNT_CONFLICTS_WITH_OCCURRENCE_STATUS

The interpretation is according to this table: https://github.com/gbif/pipelines/issues/268#issuecomment-624755278
