### ISSUE TITLE
Link to ToR is 404

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1853]
**Link to ToR is 404**

Hi, I would like to include a link to this task group ToR for a document for Joe and GBIF Science Committee, could someone kindly revive the link, please?

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e06df962867f93718d78de814d609df3:130b7377b1a53252178047c8932e2a139aa8261a8d424c32ed3c91d8964b81bbb51dba84146e56bc6869f8c122303b4e29d610966a6f9c8278d419ba46a052ab)
Referer: https://www.gbif.org/news/82686/task-group-targets-data-on-invasive-alien-species
Window size: width 2048 - height 1025
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-21T09:28:22.526Z',mode:absolute,to:'2019-03-21T09:34:22.526Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-21T09:28:22.526Z',mode:absolute,to:'2019-03-21T09:34:22.526Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Is the file not on Box? Either way, I'll be glad to restore it to the news item, but the current reference is to a link that doesn't resolve.

**Comment by dschigel** [comment]
https://gbif.box.com/s/hy04ea56tb2zmgla8ylgejqxuy5vd79c

**Comment by kcopas** [comment]
Updated with link to PDF and new photo properly sized for current display
