### ISSUE TITLE
Biatora/Lecidea/Stereocaulon myriocarpoides synonymies

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#1854]
We just received the following message on the Helpdesk:

> I just wanted to alert the team responsible for managing the taxonomy in GBIF that there seems to be an erroneous synonymy currently in use there:
Lecidea myriocarpoides is listed as a synonym of Stereocaulon myriocarpum, and L. myriocarpoides is also listed as the basionym for both Stereocaulon myriocarpoides and Biatora myriocarpoides.
It is true (according to Index Fungorum at least) that Lecidea myriocarpoides is the basionym for Biatora myriocarpoides. And although Biatora/Lecidea myriocarpoides is a crustose lichen and Stereocaulon is a genus of fruticose lichens (i.e. not related to Biatoras/Lecideas), it looks like there’s some strange publication history in the literature that uncertainly  links Stereocaulon myriocarpoides to the other two species, so although that basionym relationship is probably an error, it probably isn’t GBIF’s error. However, the species Stereocaulon myriocarpum, as far as we can tell, is a separate species entirely from Stereocaulon myriocarpoides. It’s not clear how the synonymy in GBIF between Biatora/Lecidea(/Stereocaulon) myriocarpoides and Stereocaulon myriocarpum was established.
I’m not sure what the fix would be here, but I just wanted to alert the team to what appears to be a mislink between taxa, so that it’s on their radar.
Thanks very much for your time,

**Comment by jhnwllr** [comment]
> Lecidea myriocarpoides is listed as a synonym of Stereocaulon myriocarpum

**Stereocaulon myriocarpum**
https://www.gbif.org/species/7247116

does not list 
https://api.gbif.org/v1/species/7247116/synonyms

**Lecidea myriocarpoides Nyl.**
https://www.gbif.org/species/7249241

as a synonym.

**Comment by jhnwllr** [comment]
> L. myriocarpoides is also listed as the basionym for both Stereocaulon myriocarpoides and Biatora myriocarpoides.

**Lecanora myriocarpoides Vain.**
https://www.gbif.org/species/3401795

is not listed as a basionym of 
(_Lists all (re)combinations of a given basionym, excluding the basionym itself._)
https://api.gbif.org/v1/species/3401795/combinations	

of 

**Stereocaulon myriocarpoides**
**Biatora myriocarpoides**
