### ISSUE TITLE
API docs: add info on formats in download requests

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1855]
**API docs: add info on formats in download requests**

Would be nice if the different formats were included/explained somewhere here (CSV, DWCA and now also SPECIES_LIST)...

-----

User provided contact info: @dnoesgaard
System: Chrome 72.0.3626 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/648b20919e44157d17cf2bc05ca8e4d2:390018dbb40c713aadbc8612f0333584e8f0805842bcb5f0f1384b0cff2cb4164560da3d108a1d38d6738469a1dacf2e18ca91f5ed87f16193790466f9377ee1)
Referer: https://www.gbif.org/developer/occurrence
Window size: width 2096 - height 1105
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-22T15:13:53.165Z',mode:absolute,to:'2019-03-22T15:19:53.165Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-22T15:13:53.165Z',mode:absolute,to:'2019-03-22T15:19:53.165Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
If someone provides the prose, then I'd be happy to add it to the dev documentation

**Comment by dnoesgaard** [comment]
Between the query.json example box and "Then issue", add the text below:

Where `creator` is your GBIF username, `notification_address` is a email address to notify when the download is ready,  and `format` one of the following values: `SIMPLE_CSV`, `DWCA`, or `SPECIES_LIST` ([information about download formats](/faq?question=download-formats)).

Example:

![Screenshot 2019-05-27 at 14 37 47](https://user-images.githubusercontent.com/21358085/58420266-1b672780-808d-11e9-8ff5-3385d52e7437.png)
