### ISSUE TITLE
Change profile email

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1856]
**Change profile email**

I know that I can log in to my GBIF profile using my id rather than my email, but it would be nice if Edit Profile also allowed the user to change the email address (I realise the validation logic is more complicated) than changing country or name ...

-----

User provided contact info: dhobern@gbif.org
System: Chrome 72.0.3626 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/1823a347510b2daa71561420df918de5:b055c9cd73bddc41f7ece5cadca3906636c97aad8992c15f59e817c3932b526cdaa3fd1b9039648f7c02a14834f8b38e6619c9a37dd7dddce7586234b6a8e695)
Referer: https://www.gbif.org/user/profile
Window size: width 1152 - height 808
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-23T16:57:13.179Z',mode:absolute,to:'2019-03-23T17:03:13.179Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-23T16:57:13.179Z',mode:absolute,to:'2019-03-23T17:03:13.179Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Closing as a duplicate.
