### ISSUE TITLE
Checklist datasets without data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1857]
**Checklist datasets without data**

There are plazi checklist datasets without any species and occurrence records. that seems wrong. at best i guess it would be metadata only datasets? 
https://www.gbif.org/dataset/search?q=plazi

-----

User provided contact info: @MortenHofft

**Comment by MattBlissett** [comment]
Probably best if @myrmoteras comments. There's not a way to search for datasets with no records, but they happen to show up on that search as they don't have a box saying "X occurrences" or "X records".

**Comment by myrmoteras** [comment]
@gsautter will need to look into the technical issues. Generally, at least taxon records (treatments) should be in an article (checklist).
All we deal with are published scholarly articles.

**Comment by gsautter** [comment]
Looking through the datasets (e.g. https://www.gbif.org/dataset/8236bd26-3526-4cd6-8f59-d0a35546956a), I find there is a treatment (http://tb.plazi.org/GgServer/html/260AFD4EFFB4FF9FA8F4BFF2FD76FE04) but a look at the XML (http://tb.plazi.org/GgServer/xml/260AFD4EFFB4FF9FA8F4BFF2FD76FE04) shows it is lacking the "nomenclature" section.

**Comment by myrmoteras** [comment]
ok - I fixed this one.
