### ISSUE TITLE
Filter "Issue = Depth unlikeley" shows empty result list

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#186]
**Filer &quot;Issue = Depth unlikeley&quot; shows empty result list**

If I select the advanced filter Issue = Depth unlikely, the resulting occurrence list is empty. Other filter work fine.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
Reported by: @jholetschek
System: Chrome 57.0.2987 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/occurrence/search?issue=DEPTH_UNLIKELY&advanced=1
Window size: width 1262 - height 821
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-09T08:01:45.165Z',mode:absolute,to:'2017-05-09T08:07:45.165Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-09T08:01:45.165Z',mode:absolute,to:'2017-05-09T08:07:45.165Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by jholetschek** [comment]
![bildschirmfoto 2017-05-09 um 10 02 26](https://cloud.githubusercontent.com/assets/11058397/25841247/a8761adc-349f-11e7-8af4-205815e3d0c5.png)
This is a screenshot

**Comment by cgendreau** [comment]
Thanks for reporting the issue @jholetschek 

Debug info:
The API return only the count, no records.
http://api.gbif.org/v1/occurrence/search?issue=DEPTH_UNLIKELY

**Comment by cgendreau** [comment]
The issue is related to the content of the index where old records from a large dataset are still indexed. The log will show `"Occurrence 1055237519 not found in store, but present in solr"`.

If we use the facets to query another dataset we will get results.
e.g. https://demo.gbif.org/occurrence/search?dataset_key=8ea94e2a-118c-4a53-a957-5348d48d61e1&issue=DEPTH_UNLIKELY

We need to rebuild the Solr index from scratch to get consistency.

**Comment by MattBlissett** [comment]
I think this fixes itself eventually (after compaction of the SOLR index).
