### ISSUE TITLE
Angola out of order in alphabetical country list

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1863]
**Angola out of order in alphabetical country list**

Newly added associate country participant Angola is ordered under R because the name shown is Republic of Angola. This is inconsistent with other country names and should just be Angola - or Angola, Republic of. I guess this is probably due to the way it has been listed in the directory.

-----

User provided contact info: @timhirsch
System: Chrome 73.0.3683 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/619f818dbf7ededc5ce3019240d76569:5174c5356094c60a5292c5e30e885fb1d0d3cba4e9003c59e97f0404bc81dc648ba3e5bd24dd3f2a9af5ee0c1cbb1cde5116109be25694c831189037d717d637)
Referer: https://www.gbif.org/the-gbif-network/africa
Window size: width 1437 - height 610
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-27T20:49:31.274Z',mode:absolute,to:'2019-03-27T20:55:31.274Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-27T20:49:31.274Z',mode:absolute,to:'2019-03-27T20:55:31.274Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Indeed, Angola was listed as "Republic of Angola" in the directory. With the help of Admin, this has been changed to "Angola, Republic of", consistent with other country names.

Angola now shows up second on the list of African participants:

![Screenshot 2019-04-10 at 10 13 00](https://user-images.githubusercontent.com/21358085/55862695-44813680-5b79-11e9-8a84-a0f738d5d804.png)
