### ISSUE TITLE
Species from the old Scolytidae family, and are now in the Curculionidae family are incorrectly matched by GBIF to Bostrichidae family names.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1864]
**Species from the old Scolytidae family, and are now in the Curculionidae family are incorrectly matched by GBIF to Bostrichidae family names.**

Some species names which were in the old Scolytidae family, and are now in the Curculionidae family are incorrectly matched by GBIF as synonyms to names in the Bostrichidae family. This is despite Catalogue of life listing them under the Curculionidae family. (e.g. Hylastes ater)

Occasionally GBIF does find a Curculionidae match - but lists it as doubtful.

This unfortunately makes using the rgbif package to clean up Coleoptera species lists rather complicated.

-----

System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/dbfde78b5837f035271b5356773f2f11:efb8f231f3dfea39796832a56475d03f5907c0855042fdafe5884b6b6f1e589c07e3266dac64d2451091cb78cc20a227237e9e5453c1d1f729ef3b83204d2de6)
Referer: https://www.gbif.org/faq
Window size: width 1268 - height 610
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-27T22:23:15.253Z',mode:absolute,to:'2019-03-27T22:29:15.253Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-27T22:23:15.253Z',mode:absolute,to:'2019-03-27T22:29:15.253Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Curculionidae and Bostrichidae don't seem to be synonym any more in the latest backbone so I am closing the issue.
