### ISSUE TITLE
New main menu redirects to gbif.org from -dev

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal-feedback#1866]
Links such as the validator, species search and many others (but not all) redirect to gbif.org, which is confusing when using one of the other sites.

**Comment by MortenHofft** [comment]
I'm unable to reproduce this by going to UAT and clicking either `get data -> species` or `tools->data validator`. Both link to the UAT version. I'm labelling this content as has happened for some links when the url was full (http://www.gbif.org/species instead of /species)

**Comment by MattBlissett** [comment]
I was looking on Dev, which still shows the problem.

**Comment by MortenHofft** [comment]
that makes sense then. because that is a different contentful environment

**Comment by dnoesgaard** [comment]
Fixed.
