### ISSUE TITLE
Minor: Improve Method steps and Bibliography

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1869]
**Minor: Improve Method steps and Bibliography**

I suggest removing the (1) when there is only a single method step (perhaps removing the jagged circle around the 1 and just using the same style as bibliography too) as a single step doesn't need numbering.

The  empty biography doesn't need to show 1.

-----

User provided contact info: @MrStylePolice
System: Chrome 73.0.3683 / Mac OS X 10.14.0
User: [See in registry](https://www.gbif.org/api/feedback/user/9a3e31f69069b7dc4cad428199dea4cf:d60add4ed00919fc9606af0d0204efa4524fb10811725c3480bb4e7ddcc3861646fed28cf9146e3db12b7d1baae961a96640c46ede5ee17b10248d46e6dddb0f)
Referer: https://www.gbif.org/dataset/8a863029-f435-446a-821e-275f4f641165
Window size: width 2010 - height 1231
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-03T12:42:29.607Z',mode:absolute,to:'2019-04-03T12:48:29.607Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-03T12:42:29.607Z',mode:absolute,to:'2019-04-03T12:48:29.607Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
The jagged circle?

(Double size as it's a screenshot from a 4k screen.)

![Screenshot_20190403_145108](https://user-images.githubusercontent.com/583320/55480163-efe13700-561f-11e9-871d-e188a47acc29.png)

**Comment by MortenHofft** [comment]
the biography isn't empty. It is an empty string provided by the API.
