### ISSUE TITLE
Model of databe

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#187]
**Model of databe**

I would be great if the model of database provide from this website could be similar to Tropicos.org database given. It because handle the model database given here is a quiet difficult to use, information inside is too confused.

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
Reported by: alchumbe@gmail.com
System: Chrome 58.0.3029 / Windows 7 0.0.0
Referer: https://demo.gbif.org/search?q=IUL
Window size: width 1440 - height 745
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-09T13:43:03.188Z',mode:absolute,to:'2017-05-09T13:49:03.188Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-09T13:43:03.188Z',mode:absolute,to:'2017-05-09T13:49:03.188Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
How can we help you understand the data model? 

Note that Tropicos shares its data through GBIF.org: [https://demo.gbif.org/dataset/7bd65a7a-f762-11e1-a439-00145eb45e9a](https://demo.gbif.org/dataset/7bd65a7a-f762-11e1-a439-00145eb45e9a)

**Comment by kcopas** [comment]
Closing—request is unclear, and no response received to follow-up email sent to user/submitter.
