### ISSUE TITLE
the link to the DWCA is dead. Cheers Dave :)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1870]
**the link to the DWCA is dead. Cheers Dave :)**

-----

User provided contact info: @djtfmartin
System: Chrome 73.0.3683 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/c8752ba74d2409a3033853017a2e8348:0b204aa5e428f6124f80cdce5f379b1af5b5ecd57d3b404857cfe5528966a29d6fade1a5d498f2a78b5dd4f5fa2691e75abb26bf10eb472b9b10759a809c17f8)
Referer: https://www.gbif.org/dataset/1bba5c01-162b-48ef-a7f0-f17929f7b32e
Window size: width 1440 - height 797
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-03T13:41:40.577Z',mode:absolute,to:'2019-04-03T13:47:40.577Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-03T13:41:40.577Z',mode:absolute,to:'2019-04-03T13:47:40.577Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
Probably something @gsautter would know to fix. (The endpoint doesn't work.)

**Comment by gsautter** [comment]
I've added the functionality now to add a new endpoint to an existing registration, see https://www.gbif.org/dataset/1bba5c01-162b-48ef-a7f0-f17929f7b32e

Now the question is how to remove the old endpoint?

**Comment by MattBlissett** [comment]
You need to find the key of the endpoint (so in this case 90280 from either https://api.gbif.org/v1/dataset/1bba5c01-162b-48ef-a7f0-f17929f7b32e or https://api.gbif.org/v1/dataset/1bba5c01-162b-48ef-a7f0-f17929f7b32e/endpoint) and then send an authenticated HTTP DELETE request to https://api.gbif.org/v1/dataset/1bba5c01-162b-48ef-a7f0-f17929f7b32e/endpoint/90280

**Comment by gsautter** [comment]
Thanks for the hint, I implemented cleanup as well now, see https://www.gbif.org/dataset/1bba5c01-162b-48ef-a7f0-f17929f7b32e

Is it possible to search your API by a prefix of endpoint URLs? That would allow me to get a list of all datasets that still have invalid endpoints ...

**Comment by gsautter** [comment]
Resolved via a full diff of the datasets on both ends, updating north of 10,000 endpoints yesterday. Let me know if any errors remain.

**Comment by MattBlissett** [comment]
Thanks Guido, I can confirm that all Plazi endpoints have the same `http://tb.plazi.org/GgServer/dwca/` prefix.
