### ISSUE TITLE
Trying to clean data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1872]
**Trying to clean data**

I am trying to figure out how to clean data in GBIF but could not find instructions. So then I tried to download the records with a set of problems. I got a file of GBIF's identifiers. Sorry but that is not helpful. What I need is the catalog number and, preferably, the fields involved.  I am not prepared to go and search for each record by the GBIF identifier. That is an unreasonable time demand.  Actually, I am pretty sure there is an easier way to see the records - please instructions that are clear and easy to find.  
Mary

-----

User provided contact info: mary.barkworth@usu.edu
System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/ce13c1e42baa2f1daad941107d3f8ca5:e3e70bb6c0bcb9f0ae3114009343c609981463f84586387b4c33f5978c0c818e342f1c40be9ef791de7b3575c3a85b0b643194712858182240719bc027d67e4d)
Referer: https://www.gbif.org/occurrence/download/0007924-190320150433242
Window size: width 1887 - height 967
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-03T16:02:06.872Z',mode:absolute,to:'2019-04-03T16:08:06.872Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-03T16:02:06.872Z',mode:absolute,to:'2019-04-03T16:08:06.872Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Replied by email:
>We have some guidelines for Data Cleaning (see “[Principles and Methods of Data Cleaning: Primary Species and Species-Occurrence Data](https://www.gbif.org/document/80528/principles-and-methods-of-data-cleaning-primary-species-and-species-occurrence-data)”). In addition to that, some tutorials (non-affiliated with GBIF) are also available online (see for example, [this tutorial](https://recology.info/2016/03/scrubr/) for `rscrub`).
That being said, I don’t think that these would help you solve the issue you encountered. I suspect that this issue is due to the type of download chosen. You clicked on `SPECIED LIST AS CSV` instead of `CSV`.
`SPECIED LIST AS CSV` gave you a list of unique names and their number of associated occurrences. In this case, since none of them were matched to a name (e.g. “Taxon match none” flag), you got only one row.
If you clicked on `CSV` (see this link here) , you would get all the occurrences (including their occurrenceID/catalogue number).
