### ISSUE TITLE
Dataset page deleted by crawler.gbif.org although dataset still good

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1873]
**Dataset page deleted by crawler.gbif.org although dataset still good**

The dataset was hosted on VerNet and migrated to an other IPT. Then  `crawler.gbif.org` deleted it. I am not sure why and the publishers contacted us to to restore it.

It is now restored but see screenshots below.

* Dataset's page:
![Screenshot 2019-04-04 at 09 25 57](https://user-images.githubusercontent.com/7677271/55537313-2ff5f780-56bc-11e9-9294-d5082e27dee7.png)
* Dataset's endpoint:
![Screenshot 2019-04-04 at 09 26 27](https://user-images.githubusercontent.com/7677271/55537320-32f0e800-56bc-11e9-9602-ee41a4852875.png)
* Registry:
![Screenshot 2019-04-04 at 09 26 08](https://user-images.githubusercontent.com/7677271/55537323-35534200-56bc-11e9-8c69-d6aaed03c4f2.png)

-----

User provided contact info: @ManonGros
System: Safari 12.1.0 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/6a353e15ac86354c5f150ec3794a8f8f:1934eb69e57d28578c2316af3d4f7dd71a7cfd4c09565addbc01cf81bbc7d51e63c4d64dd1d49e04bc8820034cb1cbb2618c5cc1702abdf1d9d03d2e288d1d76)
Referer: https://www.gbif.org/dataset/be5507b9-7abf-4b69-afe1-5ca2b7561734
Window size: width 1615 - height 888
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-04T07:24:32.785Z',mode:absolute,to:'2019-04-04T07:30:32.785Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-04T07:24:32.785Z',mode:absolute,to:'2019-04-04T07:30:32.785Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
The same for:
* https://www.gbif.org/dataset/6d2cfc0a-9903-40b8-802b-403398218e4a
* https://www.gbif.org/dataset/8e479b8f-ac16-4bed-a11a-bc7e27c31663

**Comment by MattBlissett** [comment]
We received a DELETE message each of these from ipt.vertnet.org:

```
107.0.125.172 114066 6ea87510-0561-11d8-b851-b8a03c50a862 [03/Apr/2019:22:58:42 +0200] "DELETE http://gbrds.gbif.org/registry/ipt/resource/be5507b9-7abf-4b69-afe1-5ca2b7561734 HTTP/1.1" 200 0 '-' '-'
107.0.125.172 120520 6ea87510-0561-11d8-b851-b8a03c50a862 [03/Apr/2019:22:59:00 +0200] "DELETE http://gbrds.gbif.org/registry/ipt/resource/6d2cfc0a-9903-40b8-802b-403398218e4a HTTP/1.1" 200 0 '-' '-'
107.0.125.172 126138 6ea87510-0561-11d8-b851-b8a03c50a862 [03/Apr/2019:22:58:50 +0200] "DELETE http://gbrds.gbif.org/registry/ipt/resource/8e479b8f-ac16-4bed-a11a-bc7e27c31663 HTTP/1.1" 200 0 '-' '-'
```

The IPT sends this command when a dataset is deleted.  Maybe the process for migration between IPTs needs to be updated to say how this should be prevented. (Is there a documented process?)

**Comment by ManonGros** [comment]
The registry message said that it was deleted `17 days ago`, so it was before VertNet deleted the resources on their IPT. Unless the the date is wrong?

**Comment by MattBlissett** [comment]
That doesn't agree with the message the portal was showing, 3 April. I can't explain that.

**Comment by MattBlissett** [comment]
I don't think there's any more I can do with this.
