### ISSUE TITLE
Can records with the label "BASIS OF RECORD INVALID" still be used

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1876]
**Can records with the label &quot;BASIS OF RECORD INVALID&quot; still be used**

I have four occurrences with this label:
 'BASIS_OF_RECORD_INVALID;GEODETIC_DATUM_ASSUMED_WGS84;COORDINATE_PRECISION_INVALID"

Can I still use them as valid detection data?

-----

User provided contact info: glenn.fowler@usda.gov
System: Edge 17.17134.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/39d01f040da3dc8918ad27acef08b726:7f591bf9abf665b8b2e5e853dba1f3c32575e45414b69d455452896065ddbcf12f0a5bf2292f3a33e0a415f5533d3b9b5e4b7409629124e2a2f1b468bee209fe)
Referer: https://www.gbif.org/faq
Window size: width 1219 - height 561
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-05T19:31:26.853Z',mode:absolute,to:'2019-04-05T19:37:26.853Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-05T19:31:26.853Z',mode:absolute,to:'2019-04-05T19:37:26.853Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> Whether you choose to use records labelled as “invalid basis of record” or not is up to you. However, I suggest that you check the original data for the ambiguous cases. You can do so by downloading the raw Darwin Core Archive or by clicking on each occurrence and then clicking on the double arrow on the upper right corner (see screenshot attached). Perhaps our system flagged these occurrences because the basis of record was misspelled, in which case you could include them.
> You could also consider consulting the datasets metadata as they might indicate what type of records it contains.

![see_original_data](https://user-images.githubusercontent.com/7677271/57083083-4792c100-6cf8-11e9-88b7-44e28279c00f.png)
