### ISSUE TITLE
Get multiple species int from the API

### ISSUE THREAD

**Issue by ArimaSD** [gbif/portal-feedback#1877]
I'm making an app for my school and i wanted to recieve multiple species<int> and work it around like this in my c# code:

```
public class RootObject
        {
            [JsonProperty(PropertyName = "key")]
            public int Key { get; set; }

            public string kingdom { get; set; }
            public string phylum { get; set; }
            public string order { get; set; }
            public int kingdomKey { get; set; }
            public string parent { get; set; }
            public string scientificName { get; set; }
            public string canonicalName { get; set; }
            public string authorship { get; set; }
            public string nameType { get; set; }
            public string rank { get; set; }
            public string origin { get; set; }
            public string taxonomicStatus { get; set; }
}
```

for example i need this key ids in one pull

Acanthocybium   solandri
Acanthostracion   quadricornis
Acanthurus bahianus
Acanthurus chirurgus
Acanthurus coeruleus
Aetobatus narinari
Albula nemoptera
Albula vulpes
Alectis ciliaris
Alopias superciliosus
Alopias vulpinus

**Comment by MattBlissett** [comment]
Hi Arima,

I'm afraid it's not possible to retrieve many species keys in a single request.

You could use a loop (`foreach`) to go through your list of species names, and make 12 requests.
