### ISSUE TITLE
What is 'machine observations'?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1878]
**What is &#39;machine observations&#39;?**

Hello, I have a question on a term used here. I downloaded the database on Saltator similis records for all the species' distribution. The records were compiled on human observations, museums' preserved specimens and an odd 'machine observation'. I've never heard of machine observations to record bird data, so I was wondering what this term meant.
Best regards,

-----

User provided contact info: giuliana.ufrj@gmail.com
System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b13bc508e01d0ec93cc57aa5fcc7a42c:f33e4d3dd7f40c1ca07206d3a46e0d8913e49335a50d14dd1e30f6556729bc481e6f900cb541a348c1c1b3260606b5d87c96dff4d199c1afa0bed8c6365d3701fa8866af8df4ffba513ac89072ad9655)
Referer: https://www.gbif.org/
Window size: width 1366 - height 635
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-08T12:53:45.206Z',mode:absolute,to:'2019-04-08T12:59:45.206Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-08T12:53:45.206Z',mode:absolute,to:'2019-04-08T12:59:45.206Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by tucotuco** [comment]
Hi Giuliana,

MachineObservation is one of the Darwin Core terms used to describe the
source or nature of the record as a value in the basisOfRecord field.
Machine observations are those arising from a machine, such as a camera
trap, capturing the evidence. You can see the definition and more examples
at http://rs.tdwg.org/dwc/terms/#machineobservation.

Cheers,

John

**Comment by MortenHofft** [comment]
user informed per email
