### ISSUE TITLE
iCal link dead?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1879]
**iCal link dead?**

Seems to return an http500

-----

User provided contact info: @timrobertson100
System: Chrome 73.0.3683 / Mac OS X 10.14.0
User: [See in registry](https://www.gbif.org/api/feedback/user/0dd2d351b0f5c88544c4d110e9d2dd1d:c3818e39425bf11bd2c1873bdd2f870e6574280bacf872faf66d9c19c16dd2410ce2bd06eacc5078f314a8d2bbfff731f6860703b9e8eb3454bd74d757ac8f00)
Referer: https://www.gbif.org/resource/search?contentType=event
Window size: width 1680 - height 948
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-08T14:11:58.198Z',mode:absolute,to:'2019-04-08T14:17:58.198Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-08T14:11:58.198Z',mode:absolute,to:'2019-04-08T14:17:58.198Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I have a lurking feeling that many of these feeds never worked honestly...

@fmendezh and @thomasstjerne you are the ones that know the history of this best.
See also:

https://github.com/gbif/ssg-bid/issues/6
https://github.com/gbif/portal16/issues/153
https://github.com/gbif/portal16/issues/629
https://github.com/gbif/portal-feedback/issues/1847

**Comment by thomasstjerne** [comment]
It seems the api gives a 500: 
http://api.gbif.org/v1/newsroom/events/PnCA9Id0oScMw8UWIswwA
http://api.gbif.org/v1/newsroom/events/calendar/upcoming.ics

**Comment by MattBlissett** [comment]
The content-ws is throwing an exception:

```
! java.lang.ClassCastException: java.util.HashMap cannot be cast to java.lang.String
! at org.gbif.content.utils.SearchFieldsUtils.lambda$getField$1(SearchFieldsUtils.java:34)
! at java.util.Optional.map(Optional.java:215)
! at org.gbif.content.utils.SearchFieldsUtils.getField(SearchFieldsUtils.java:34)
! at org.gbif.content.utils.ConversionUtil.toVEvent(ConversionUtil.java:87)
! at org.gbif.content.resource.EventsResource.getEvent(EventsResource.java:150)
```
