### ISSUE TITLE
Wording change for non-participant message

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#188]
**Wording change for non-participant message**

Please change message for non-participant countries as follows:

This country is not a participant in GBIF

But you will still find data about its biodiversity, and some of its institutions may be publishing datasets!

-----
fbitem-a9a687bfdfefefb615293f830fc4eceaef112af7
Reported by: thirsch@gbif.org
System: Chrome 58.0.3029 / Mac OS X 10.10.5
Referer: https://demo.gbif.org/country/AT
Window size: width 1600 - height 745
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-11T13:49:00.176Z',mode:absolute,to:'2017-05-11T13:55:00.176Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-11T13:49:00.176Z',mode:absolute,to:'2017-05-11T13:55:00.176Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/21c5479191cf73e8c5e29ce16d31ee18594809ca
