### ISSUE TITLE
taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1881]
**taxonomy**

"Compsus auricephalus Say, 1824"
S/B: Compsus auricephalus (Say, 1824)
Orig. Comb: Curculio auricephalus Say 1824

-----

System: Chrome 72.0.3626 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/2a6733b988d8a3747d8547b75caff618:6135c7f7d8a5903fc28ebc3f8e4d233ef99a63a81f266e63378ca9ce31ad972319c7e1269c14a4e5653d671a802fd427d2e46ba6e4c7052f03ea2561aeb44ffa)
Referer: https://www.gbif.org/species/5015904
Window size: width 1158 - height 785
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-10T02:48:03.897Z',mode:absolute,to:'2019-04-10T02:54:03.897Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-10T02:48:03.897Z',mode:absolute,to:'2019-04-10T02:54:03.897Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by yroskov** [comment]
Comment sent to 3i Curculio.
