### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1882]
**Dataset**

Hello, I'm Anita Lava, I would like to know if it is possible to delete any DATASET while I'm getting datas. Let me know,
thank you.

-----

User provided contact info: anita.12@outlook.it
System: Edge 17.17134.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/19bb339062bc59d0c3f3c9f296a7af63:b5361a3a912022c452ee56fe3840d0700ffba412105e09d8ac5499a63021dcf19f294a9edcdb4977fe46155fc658b26ffaa518e326ea9b3cc854ece00964eda1)
Referer: https://www.gbif.org/dataset/search
Window size: width 1366 - height 651
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-10T14:37:10.710Z',mode:absolute,to:'2019-04-10T14:43:10.710Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-10T14:37:10.710Z',mode:absolute,to:'2019-04-10T14:43:10.710Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
