### ISSUE TITLE
Problem for downloading some data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1883]
**Problem for downloading some data**

In Get data>Occurrences, I searched "Bustard Ardeotis nigriceps" in India. I am not able to download the corresponding data that are shown in the screen.

I need the coordinates and the date

Thanks

-----

User provided contact info: paula.saavedra@usc.es
System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/89d8a6d1d7e57b8a7720cc507bca8d3f:902971e109ab4311f71b4d929b419875bd288d813915e447459e9c65c947b4df8f58f503eb4e86cdc98ad0e21c123cdb0234f2e44952486673892e8ff80847e9)
Referer: https://www.gbif.org/occurrence/search?q=Bustard%20Ardeotis%20nigriceps&country=IN
Window size: width 1366 - height 576
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-10T16:27:00.106Z',mode:absolute,to:'2019-04-10T16:33:00.106Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-10T16:27:00.106Z',mode:absolute,to:'2019-04-10T16:33:00.106Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Response sent by email:

> Dear Paula,
>  
> You’ll want to specify the scientific name of the species you’re interested in, e.g. https://www.gbif.org/occurrence/search?country=IN&taxon_key=2474902
>  
> When the search is structured (i.e. not free text-based) you can download the results.
>  
> I hope this helps.
