### ISSUE TITLE
Basionym confusion makes Monticola semirufus and Cossypha semirufa synonyms

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1884]
**Basionym confusion makes Monticola semirufus and Cossypha semirufa synonyms**

Petrocincla semirufa (Rüppell, 1840) is listed as the basionym for both Monticola semirufus and Cossypha semirufa; however, it should only be the basionym for C. semirufa. Saxicola semirufa, also described by Rüppell (1837) is the true basionym for M. semirufus. As a result of the basionym confusion the two species are listed as synonymous in GBIF, though they are actually in different genera.  Media presented on the M. semirufus page are also  of C. semirufa, not M. semirufus.  

See Rüppell's "Neue Wirbelthiere zu der Fauna von Abyssinien gehörig" (1835-1840) for descriptions of both true basionyms (P. semirufa on p. 81, and S. semirufa on p. 74) (text available at: `https://www.biodiversitylibrary.org/item/114234).` 
Avibase (`https://avibase.bsc-eoc.org`) also lists C. semirufa and M. semirufus as separate species and provides further taxonomic clarification.

-----

User provided contact info: @btsuru
System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/cff880f96e4888c8d8d3613c526b846f:265fcb6b9d99e80f1181d3267153a7573d3d3357ab66a63421bb77bf4614213f4beb48140f7031c81b17aa504f4217d18a0fb8e3c7be10d1cc028796ca72f66c)
Referer: https://www.gbif.org/species/6100855
Window size: width 1366 - height 625
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-10T20:33:37.856Z',mode:absolute,to:'2019-04-10T20:39:37.856Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-10T20:33:37.856Z',mode:absolute,to:'2019-04-10T20:39:37.856Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by yroskov** [comment]
Monticola semirufus and Cossypha semirufa are two different species in CoL:
http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/11793c6cbbaff5f4658aacb0126c024e
http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/f2f9cc0a64863d31be00a8e7a2d01c9f

**Comment by ManonGros** [comment]
the species are independent in GBIF now: https://www.gbif.org/species/2492595 and https://www.gbif.org/species/6100855
