### ISSUE TITLE
Species Name Matching tool inquiry

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1885]
**Species Name Matching tool inquiry**

Hi, I'm trying to reconcile 2 different taxonomies, specifically, matching species names between the two. Is the code in your Species Name Matching tool available on GitHub to view? I'm trying to find an effective species name pattern matching code.

Any help would be greatly appreciated. Thanks!
Russell

-----

User provided contact info: russellscarpino@gmail.com
System: Firefox 66.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/9dc3280f4549220aed95ffa05b897e3b:1425ae778aa22c9ca9b758ba4c721a29c99b2f6633d0846889ab47c457f4a10c6779079ffe71b80591b2f7a93e4984d603b3b4fe8c2989f8eae8f71dcaacc84b)
Referer: https://www.gbif.org/user/confirm?username=rscar&code=e8293c0f-4618-47f1-af6d-ba2f240a948f
Window size: width 1280 - height 888
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-12T16:38:10.513Z',mode:absolute,to:'2019-04-12T16:44:10.513Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-12T16:38:10.513Z',mode:absolute,to:'2019-04-12T16:44:10.513Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Hi Russell
The online tool is simply using the public APIs from the browser. 
https://www.gbif.org/developer/species see `species/match`

Hope that helps
