### ISSUE TITLE
Failed crawls of NHM DwC-A

### ISSUE THREAD

**Issue by jrdh** [gbif/portal-feedback#1887]
Hi!

Dataset: `7e380070-f762-11e1-a439-00145eb45e9a`

The last two crawls of our specimen data have failed and I can't seem to find a reason in the logs. Here's the [dataset ingestion history](https://management-tools.gbif.org/crawl-history?uuid=7e380070-f762-11e1-a439-00145eb45e9a) and the last ingestion attempt logs that I could find are [here](https://logs.gbif.org/app/kibana#/discover?_g=(time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWDqIeCpf8lu3pmEHglJ,key:datasetKey,negate:!f,type:phrase,value:'7e380070-f762-11e1-a439-00145eb45e9a'),query:(match:(datasetKey:(query:'7e380070-f762-11e1-a439-00145eb45e9a',type:phrase))))),index:AWDqIeCpf8lu3pmEHglJ,interval:auto,query:(query_string:(query:'level:INFO')),sort:!('@timestamp',desc))). Both just report an abort result but no further details.

Thanks!

**Comment by MattBlissett** [comment]
Hi,

The website `data.nhm.ac.uk` has recently moved to HTTPS, but the configuration is incomplete.  Many web browsers can work around the problem (an incomplete certificate chain), but other clients often can't.

By far the best solution is to fix the problem on your server, I've never had to look into how we'd apply a workaround in Java.

https://www.ssllabs.com/ssltest/analyze.html?d=data.nhm.ac.uk should be useful.

**Comment by jrdh** [comment]
Thanks @MattBlissett, wasn't aware of the problem so thanks for raising it! I'll look into it and close this for now.
