### ISSUE TITLE
S. brasiliense is a synonym of S. indicum L.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1890]
**S. brasiliense is a synonym of S. indicum L.**

Bedigian, D. 2015. Systematics and evolution in Sesamum L. (Pedaliaceae), part 1: Evidence regarding the origin of sesame and its closest relatives. Webbia: Journal of Plant Taxonomy and Geography 70(1): 1-42. doi.org/10.1080/00837792.2014.968457

-----

User provided contact info: @dbedigian
System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/91e991b51c8060d8a9be7edcd86c3097:421dbc98eec554929089dccf93239da915924b07db28bb973dd0b9006f3e3510d6085b7fab17ff35af337a4fedd97efa9fec67b1a711eac0125bd9f1e6a3fff4)
Referer: https://www.gbif.org/species/3585170
Window size: width 1331 - height 580
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-15T13:31:29.918Z',mode:absolute,to:'2019-04-15T13:37:29.918Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-15T13:31:29.918Z',mode:absolute,to:'2019-04-15T13:37:29.918Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This is the case in the current backbone.
