### ISSUE TITLE
S. auriculatum is a synonym of S. indicum L.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1891]
**S. auriculatum is a synonym of S. indicum L.**

Bedigian, D. 2015. Systematics and evolution in Sesamum L. (Pedaliaceae), part 1: Evidence regarding the origin of sesame and its closest relatives. Webbia: Journal of Plant Taxonomy and Geography 70(1): 1-42. doi.org/10.1080/00837792.2014.968457

-----

User provided contact info: @dbedigian
System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/28f4c2cacbe28e5be71c67c1c63dcc44:40060e6ba34cbdaec578d5d12bbd70fee381a9b3353e1574e0e8f218c219460c04c8e947594ce1ae0756ff7d582808c354881392f76a1b82f2262a96119f4989)
Referer: https://www.gbif.org/species/3585170
Window size: width 1331 - height 580
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-15T13:32:14.230Z',mode:absolute,to:'2019-04-15T13:38:14.230Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-15T13:32:14.230Z',mode:absolute,to:'2019-04-15T13:38:14.230Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This is the case in the current backbone: https://www.gbif.org/species/3585188
