### ISSUE TITLE
the correct name is Sesamum indicum L. subsp. malabaricum (Burm.) Bedigian

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1895]
**the correct name is Sesamum indicum L. subsp. malabaricum (Burm.) Bedigian**

Bedigian D. 2015. Systematics and evolution in Sesamum L. (Pedaliaceae), part 1: Evidence regarding the origin of sesame and its closest relatives. Webbia. 70:1–42.
Bedigian, D. 2014. A new combination for the Indian progenitor of sesame, Sesamum indicum L. (Pedaliaceae). Novon 23(1): 5-13.

-----

User provided contact info: @dbedigian
System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/a66330df6b772c1f1ac35a9334cfdb56:1cc29321360b628fad45d936b9cf10b94bcb511d1fa575c86d9828079548feae35a564eac73d0344a0ee752b8fbf7b04e2c676343784a11f2f3618bae8eb5e4a)
Referer: https://www.gbif.org/occurrence/gallery?taxon_key=3172619
Window size: width 1340 - height 531
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-16T04:12:26.702Z',mode:absolute,to:'2019-04-16T04:18:26.702Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-16T04:12:26.702Z',mode:absolute,to:'2019-04-16T04:18:26.702Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It looks like the correct name is included in the taxonomy: https://www.gbif.org/species/7528736
I don't know if this issue refers to one of the images in the gallery, perhaps a specimen misidentified? Or a previously misspelled or missing taxon in the previous backbone.

**Comment by jhnwllr** [comment]
I think we have to close this issue because it is not actionable with the given information. Also seems like the github user no longer exists...
