### ISSUE TITLE
Ceratotheca triloba (Bernh.) E. Mey.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1896]
**Ceratotheca triloba (Bernh.) E. Mey.**

Abels J. 1975. Die Gattungen Ceratotheca Endl. und Dicerocaryum Boj. (Monographien der Afrikanischen Pedaliaceae III-IV).  Mem Soc Brot Coimbra. 25:1–358.

-----

System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/42fb967bf3933b5d8e3ce5ea209e7f28:133169c220fcf14dd1aba7e2ee89be0c891dc6cce6b7943b7e7d3c4b84284f2857bacf509822cdc5075a70bcfb853165d7a222eaed169181bc42f83d7c45086a)
Referer: https://www.gbif.org/occurrence/1137175921
Window size: width 1340 - height 531
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-16T04:24:57.130Z',mode:absolute,to:'2019-04-16T04:30:57.130Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-16T04:24:57.130Z',mode:absolute,to:'2019-04-16T04:30:57.130Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Publishers notified by email.

**Comment by ManonGros** [comment]
Occurrence link changed.
The dataset concerned is [Naturalis Biodiversity Center (NL) - Botany](https://www.gbif.org/dataset/15f819bd-6612-4447-854b-14d12ee1022d)
The link to original data is http://data.biodiversitydata.nl/naturalis/specimen/WAG.1149760

**Comment by jeroencreuwels** [comment]
This issue is forwarded to our botanical expert at Naturalis. I will keep you posted when or if this has been changed in our registration system and a new export will become available for GBIF.
