### ISSUE TITLE
Link to Taxon journal giving 404 error

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1902]
**Link to Taxon journal giving 404 error**

Seems to have moved to `https://onlinelibrary.wiley.com/journal/19968175`

-----

System: Chrome 73.0.3683 / Mac OS X 10.14.3
User: [See in registry](https://www.gbif.org/api/feedback/user/2e293b982068e45305cd2d547f937955:bf8408abb2e4268db17f3a873683066a4242efba912714fe4c06c9f7f22c2a1232558fb24d45e4d25ea4495e2dffafe4d1d39c5a77febb108997153b8a62200d)
Referer: https://www.gbif.org/data-papers
Window size: width 1684 - height 778
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-16T05:36:06.887Z',mode:absolute,to:'2019-04-16T05:42:06.887Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-16T05:36:06.887Z',mode:absolute,to:'2019-04-16T05:42:06.887Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Fixed.
