### ISSUE TITLE
northern record(s) seem suspect.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1905]
**northern record(s) seem suspect.**

-----

System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b435e2ab58a7c24a6a5414387f999b6e:1c73a10d253c260298fecc4a4c48d149dd32b0d373ffa9cc22ebc13f3f75b0da16bad4b3e081c89781f414b09777cf38f9dea7c2dfa9ae1b873deb2e6cf8ea03)
Referer: https://www.gbif.org/species/1035528
Window size: width 1362 - height 829
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-17T17:12:27.884Z',mode:absolute,to:'2019-04-17T17:18:27.884Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-17T17:12:27.884Z',mode:absolute,to:'2019-04-17T17:18:27.884Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Specimens belonging to the [C.A. Triplehorn Insect Collection (OSUC), Ohio State University](https://www.gbif.org/dataset/84ab7b76-f762-11e1-a439-00145eb45e9a).
I suspect that the location is a centroid.
The publishers were contacted but they are currently working on setting up a new IPT and migrating their dataset so it might take some time.

**Comment by jhnwllr** [comment]
https://www.gbif.org/occurrence/map?dataset_key=84ab7b76-f762-11e1-a439-00145eb45e9a&taxon_key=9616230
the dataset seems to have deleted the records.
