### ISSUE TITLE
Invalid WKT or GeoJSON

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1906]
**Invalid WKT or GeoJSON**

I'm trying to extract all records from an area using the GeoJSON option. First I had a "area too large" error, so I simplified the polygon. Then I realised QGIS was exporting to JSON as a multipolygon, so installed the 'Get WKT' v.1 plugin for QGIS 3.4.2 and extracted the WKT text for the feature. However, it still throws an "invalid WKT or GeoJSON" error. Below is the WKT. 

I also tried simplifying the shapefile to single part and exporting as GeoJSON, but get this error:

"Failed
Your filters might be invalid or the servers having issues. Please try again and report the issue if it continues"

Could you offer me some guidance on what the issue with is and how I can fix it?

Polygon ((708229.2 1334391.7, 702269.2 1334292.8, 703697.6 1336297.8, 706784.7 1336818.0, 708219.9 1341335.8, 705587.6 1348016.4, 702576.5 1349665.8, 699004.9 1346670.0, 696285.0 1347657.6, 696561.9 1349871.0, 688160.3 1351744.7, 683847.7 1346595.3, 676213.6 1343475.2, 671379.5 1346294.8, 670195.1 1344779.6, 667479.2 1345757.2, 663449.1 1349652.3, 658098.4 1345464.7, 655741.5 1356304.0, 652850.9 1359081.1, 653563.1 1361176.0, 656318.6 1363248.3, 656282.3 1365319.6, 662874.1 1365192.7, 670431.4 1371748.7, 674961.4 1379058.6, 677325.1 1380126.9, 676738.5 1386748.2, 683980.8 1383152.7, 693043.1 1382534.1, 701722.6 1387716.9, 706526.5 1394608.3, 710699.4 1389117.4, 713026.3 1389043.1, 711802.8 1387562.3, 712734.8 1386476.0, 721941.9 1383664.3, 723060.6 1389899.1, 729796.2 1391102.5, 733286.6 1385215.5, 733272.1 1382215.8, 732419.5 1379911.2, 727780.4 1379409.8, 727392.3 1377170.5, 735954.0 1370328.7, 735125.9 1363015.5, 738033.5 1361816.5, 741051.8 1363113.7, 741301.3 1364959.6, 749757.7 1366281.7, 748983.0 1363023.4, 734514.8 1357703, 733075.8 1352592.2, 730102.4 1351396.8, 728126.0 1347150.2, 726030.7 1347810.7, 726638.8 1345122.7, 724445.4 1344885.6, 723474.1 1341955.2, 718515.7 1339745.0, 719445.9 1339070.1, 717485.1 1336662.3, 708229.2 1334391.7))

{
"type": "FeatureCollection",
"name": "singleGeoJSON",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::3148" } },
"features": [
{ "type": "Feature", "properties": { "ID": 0, "AREA": 2926907732.9910002, "PERIMETER": 421463.922, "HECTARES": 292690.773, "Code": 1 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 708229.2, 1334391.7 ], [ 702269.2, 1334292.8 ], [ 703697.6, 1336297.9 ], [ 706784.8, 1336818.1 ], [ 708219.9, 1341335.9 ], [ 705587.7, 1348016.5 ], [ 702576.5, 1349665.8 ], [ 699004.9, 1346670.1 ], [ 696285.1, 1347657.6 ], [ 696562.0, 1349871.1 ], [ 688160.3, 1351744.8 ], [ 683847.7, 1346595.4 ], [ 676213.6, 1343475.3 ], [ 671379.6, 1346294.8 ], [ 670195.2, 1344779.6 ], [ 667479.2, 1345757.3 ], [ 663449.2, 1349652.3 ], [ 658098.4, 1345464.7 ], [ 655741.5, 1356304.0 ], [ 652851.0, 1359081.1 ], [ 653563.2, 1361176.0 ], [ 656318.7, 1363248.4 ], [ 656282.4, 1365319.6 ], [ 662874.2, 1365192.8 ], [ 670431.5, 1371748.7 ], [ 674961.4, 1379058.7 ], [ 677325.1, 1380127.0 ], [ 676738.6, 1386748.2 ], [ 683980.9, 1383152.7 ], [ 693043.2, 1382534.1 ], [ 701722.7, 1387717.0 ], [ 706526.6, 1394608.3 ], [ 710699.5, 1389117.4 ], [ 713026.4, 1389043.1 ], [ 711802.9, 1387562.3 ], [ 712734.8, 1386476.1 ], [ 721941.9, 1383664.3 ], [ 723060.7, 1389899.1 ], [ 729796.2, 1391102.5 ], [ 733286.7, 1385215.6 ], [ 733272.1, 1382215.9 ], [ 732419.6, 1379911.2 ], [ 727780.4, 1379409.8 ], [ 727392.3, 1377170.5 ], [ 735954.1, 1370328.8 ], [ 735125.9, 1363015.6 ], [ 738033.5, 1361816.6 ], [ 741051.9, 1363113.7 ], [ 741301.3, 1364959.7 ], [ 749757.7, 1366281.8 ], [ 748983.0, 1363023.4 ], [ 734514.9, 1357703.0 ], [ 733075.9, 1352592.3 ], [ 730102.4, 1351396.9 ], [ 728126.1, 1347150.3 ], [ 726030.8, 1347810.8 ], [ 726638.9, 1345122.8 ], [ 724445.4, 1344885.6 ], [ 723474.2, 1341955.3 ], [ 718515.7, 1339745.0 ], [ 719446.0, 1339070.1 ], [ 717485.1, 1336662.3 ], [ 708229.2, 1334391.7 ] ] ] } }
]
}

-----

User provided contact info: @git-og
System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b34cfffcaa4fc5330680446039fa11a8:8ecde5c8f90049597d55beb9e82d6abdbe593b12e10bee967f86e62556d9b7c1c78da54d1702b461d9970ada419308e99063ba54a89e5af5e9c7eeee64d8922a)
Referer: https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON((708229.2%201334391.7,717485.1%201336662.3,719446%201339070.1,718515.7%201339745,723474.2%201341955.3,724445.4%201344885.6,726638.9%201345122.8,726030.8%201347810.8,728126.1%201347150.3,730102.4%201351396.9,733075.9%201352592.3,734514.9%201357703,748983%201363023.4,749757.7%201366281.8,741301.3%201364959.7,741051.9%201363113.7,738033.5%201361816.6,735125.9%201363015.6,735954.1%201370328.8,727392.3%201377170.5,727780.4%201379409.8,732419.6%201379911.2,733272.1%201382215.9,733286.7%201385215.6,729796.2%201391102.5,723060.7%201389899.1,721941.9%201383664.3,712734.8%201386476.1,711802.9%201387562.3,713026.4%201389043.1,710699.5%201389117.4,706526.6%201394608.3,701722.7%201387717,693043.2%201382534.1,683980.9%201383152.7,676738.6%201386748.2,677325.1%201380127,674961.4%201379058.7,670431.5%201371748.7,662874.2%201365192.8,656282.4%201365319.6,656318.7%201363248.4,653563.2%201361176,652851%201359081.1,655741.5%201356304,658098.4%201345464.7,663449.2%201349652.3,667479.2%201345757.3,670195.2%201344779.6,671379.6%201346294.8,676213.6%201343475.3,683847.7%201346595.4,688160.3%201351744.8,696562%201349871.1,696285.1%201347657.6,699004.9%201346670.1,702576.5%201349665.8,705587.7%201348016.5,708219.9%201341335.9,706784.8%201336818.1,703697.6%201336297.9,702269.2%201334292.8,708229.2%201334391.7))
Window size: width 1388 - height 746
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-19T10:35:26.471Z',mode:absolute,to:'2019-04-19T10:41:26.471Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-19T10:35:26.471Z',mode:absolute,to:'2019-04-19T10:41:26.471Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
It has to do with the coordinate reference system. 

We assume latitude: -90,90 and longitude: -180,180
For your WKT we are unlikely to detect what the values are referring to.

In theory we could for GeoJSON, but it isn't in the standard as far as in know:

>  2008 geojson.org GeoJSON supported alternative coordinate reference systems other than ESPG:4326, but this capability was **removed in the current GeoJSON standard**. So, this section is of historical interest but you shouldn’t use the crs member or try to put projected data into GeoJSON: you should instead **reproject it to WGS84 first**.

from https://macwright.org/2015/03/23/geojson-second-bite#projections

Hope this helps. To solve this you should reproject it to WGS84 first.

**Comment by MortenHofft** [comment]
conversion can be done many ways: here is one online service: https://ogre.adc4gis.com/
