### ISSUE TITLE
suspicious location

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1907]
**suspicious location**

The georeference locates the specimen in the state of Oaxaca in Mexico, outside the area of distribution of the species, which corresponds to an error since in the description of the locality it is mentioned that it was collected in the state Baja California in Mexico where it is distributed naturally

-----

User provided contact info: gpandradep@unal.edu.co
System: Firefox 66.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4c15f3baa1731eb61a4598b80afec05a:767dad2078e3c168ce7c6acb0e30b8ba9dbea2c888db3067848b30f063df74e0e2726c20427789110180086140a6f7842fc3d9c09e668b6cf8c19d724e4ca873)
Referer: https://www.gbif.org/occurrence/476858510
Window size: width 1366 - height 642
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-19T21:50:00.709Z',mode:absolute,to:'2019-04-19T21:56:00.709Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-19T21:50:00.709Z',mode:absolute,to:'2019-04-19T21:56:00.709Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I reported the issue to the [MCZBASE](https://mczbase.mcz.harvard.edu/guid/MCZ:Mamm:38619)
