### ISSUE TITLE
Adding Data set to project profile

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1908]
**Adding Data set to project profile**

We have been told to do this for BIFA3_47. How does one do it?

-----

User provided contact info: Mary.barkworth@usu.edu
System: Chrome 73.0.3683 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/bed8511395bd19d2cd453ac8e567b13b:5fbbc347261eae3573219361e18f7c328976eb4274f98da4eb18dfb87b5190399b6c84703e3eb41ede6a2a253bb6123ce6916f9c401fc996a8c626b1d56ec5f3)
Referer: https://www.gbif.org/
Window size: width 929 - height 932
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-21T10:37:53.392Z',mode:absolute,to:'2019-04-21T10:43:53.392Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-21T10:37:53.392Z',mode:absolute,to:'2019-04-21T10:43:53.392Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by timhirsch** [comment]
Mary this is already done in the metadata for https://www.gbif.org/dataset/6f40c8ec-2b95-47d5-9064-eda6a8ddf3fb - please do the same with the other datasets mobilised through this project, contact helpdesk@gbif.org directly for detailed instructions.
