### ISSUE TITLE
Display of "depth" on Occurrence page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#191]
**Display of &quot;depth&quot; on Occurrence page**

&quot;depth&quot; is provided by the API in a single field as opposed to minimum and maximum in the verbatim version. If minimum and maximum are provided in the verbatim, &quot;depthAccuracy&quot; should be provided by the API (not sure about the usage of the word &quot;accuracy&quot; but it&#39;s its current name).

-----
fbitem-occurrence883267042
Reported by: @cgendreau
System: Chrome 57.0.2987 / Mac OS X 10.10.5
Referer: https://demo.gbif.org/occurrence/883267042
Window size: width 1440 - height 733
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-17T07:40:09.793Z',mode:absolute,to:'2017-05-17T07:46:09.793Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-17T07:40:09.793Z',mode:absolute,to:'2017-05-17T07:46:09.793Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 8ea94e2a-118c-4a53-a957-5348d48d61e1
publishingOrgKey: d5778510-eb28-11da-8629-b8a03c50a862

**Comment by kbraak** [comment]
Hi @cgendreau, according to the infrastructure section of our website under section [DARWIN CORE VS GBIF TERMS](http://www.gbif.org/infrastructure/processing), "[w]e decided to be consistent and always use a single term, e.g. depth, accompanied by a matching accuracy term, in this case depthAccuracy." Therefore as a user, indeed I'd expect both terms depth and depthAccuracy to appear on the occurrence page, hopefully with an accompanying definition some place, such as the [proposed glossary](https://github.com/gbif/portal16/issues/240).

**Comment by MortenHofft** [comment]
thanks
fixed, but is currently only on dev https://demo.gbif-dev.org/occurrence/883267042
