### ISSUE TITLE
Serious date issues with platypus records

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#1915]
Seems odd that there are 34 MCZ specimens of duck-billed platypus whose [records appear to use 1/1/1700 as a null date](https://www.gbif.org/occurrence/search?taxon_key=2433376&year=1700). I haven't reviewed all of them, but the ones I did consistently and clearly state that there is 'no verbatim date data'. Wouldn't it be better to have actual null fields for date?

Likewise, there's another set of [17 records from two different datasets that record human observations from 1770](https://www.gbif.org/occurrence/search?taxon_key=2433376&year=1770). These just seem like straight-up errors.

Note, too, that the species was only described in 1799.

**Comment by ManonGros** [comment]
I have forwarded the issue to the ALA data management repository.

**Comment by ManonGros** [comment]
Reply from ALA:
> The ANWC records are dated as "Pre 1900" and the way to express that in DwC eventDate was to select a date range:

> Theoretically, this means that the earliest date they could possibly have been collected would be the first day that Captain Cook touched down in Australia, and have given a date range = 29/04/1770 – 31/12/1900. Presently a record which has verbatimEventDate = ‘PRE 1900’, gets an eventDate = 1770-04-29/1900-12-31

> We are discussing alternatives that may express this better.
