### ISSUE TITLE
Incorrect image mapping

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1917]
**Incorrect image mapping**

The same image is mapped to 95 different occurrences.

-----

User provided contact info: @MattBlissett
System: Firefox 65.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/6b1ae1c626c788925a7f6708c9514648:b0cf13079ce3b0f561535e8cbab2f4dd5327e68f812cf69ef89476eca1964801d02a3c1ea2f4a6a3f4b46a80d653479118d56206343a440019592c052336d914)
Referer: https://www.gbif.org/occurrence/gallery?media_type=StillImage&publishing_org=bc092ff0-02e4-11dc-991f-b8a03c50a862&recorded_by=G.%20Ashton%20%26%20W.%20Keel&advanced=1
Window size: width 1440 - height 2424
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-29T11:11:28.830Z',mode:absolute,to:'2019-04-29T11:17:28.830Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-04-29T11:11:28.830Z',mode:absolute,to:'2019-04-29T11:17:28.830Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Left a feedback message on the Smithsonian website.
