### ISSUE TITLE
data papers link from the main menu is broken (404)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#192]
**data papers link from the main menu is broken (404)**

From the main menu, Share &gt; Data Papers, the link points at https://demo.gbif.org/publishing/data-papers and gives a 404. Apparently it should now be https://demo.gbif.org/data-papers instead

-----
fbitem-fcb3cded49511a21a90f61b9a8318b9e561b2531
Reported by: ahahn@gbif.org
System: Firefox 53.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/data-papers
Window size: width 1201 - height 861
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-17T13:53:51.160Z',mode:absolute,to:'2017-05-17T13:59:51.160Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-17T13:53:51.160Z',mode:absolute,to:'2017-05-17T13:59:51.160Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
thanks andrea. 
@dnoesgaard the urls are the same now, but what do we opt for. flat or nested?
