### ISSUE TITLE
Apterygothrips priesneri zur Strassen, 1966 interpreted as subspecies

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1924]
**Apterygothrips priesneri zur Strassen, 1966 interpreted as subspecies**

`Apterygothrips priesneri zur Strassen, 1966` (`https://www.gbif.org/species/9069024)` is interpreted as a subspecies, but I think it is actually a species, with the author `zur Strassen, 1966`. I guess the lowercase `z` throws off the name matching.

-----

User provided contact info: @peterdesmet
System: Chrome 73.0.3683 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/8265cbad2cee0f4210ef77f406876f5b:c5183b2a87cf62b1f575301c0a50d7693e571c668cb0453e3d445ebf8116520f400fb68c49346f72684dd6e49b0f028bdefd878d9cf8bc43040687affe090985)
Referer: https://www.gbif.org/species/9069024
Window size: width 1386 - height 766
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-06T13:40:52.889Z',mode:absolute,to:'2019-05-06T13:46:52.889Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-06T13:40:52.889Z',mode:absolute,to:'2019-05-06T13:46:52.889Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
this seems correct in the new backbone

**Comment by peterdesmet** [comment]
Indeed, see https://www.gbif.org/species/8745264
