### ISSUE TITLE
How do I modify the email associated with my account?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1925]
**How do I modify the email associated with my account?**

I click "start editing" on my profile, which allows me to change my first name, last name, and country. However, the option to change my email is grayed out. How do I change the email address associated with my account?

-----

User provided contact info: jsouc073@uottawa.ca
System: Firefox 66.0.0 / Fedora 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/fc2e23b730382d9af4443fc76b5e698b:0c46ce25d0b1acd8a8390938c2efc1ebeef36ae934e539947a61ab6a87cc972cd024cef1ad8e8965093e22aeaccc63ce4fe9535ab1bc0856448d6ccdcc20cf68)
Referer: https://www.gbif.org/user/profile
Window size: width 1920 - height 918
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-07T11:55:49.425Z',mode:absolute,to:'2019-05-07T12:01:49.425Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-07T11:55:49.425Z',mode:absolute,to:'2019-05-07T12:01:49.425Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> Please send an email to helpdesk@gbif.org from the email attached to your account.
Let us know which account should be updated and what should be the new email address.
