### ISSUE TITLE
IUCN links missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1926]
**IUCN links missing**

We were wondering on the IV floor about once present, now missing IUCN statuses and links to IUCN species pages? Perhaps there is some revision going on?

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/f2eb26b590eefcd1bffc140d9714a458:42b63e5751f53e87cbb311d710a2d3b881fbf628d3364d5601a25b39e86ca970029ddc98e728ae026b07429c039f73a627be70438e18b0a115b013ed4ad478d4)
Referer: https://www.gbif.org/species/5220113
Window size: width 1922 - height 1073
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-07T12:59:42.152Z',mode:absolute,to:'2019-05-07T13:05:42.152Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-07T12:59:42.152Z',mode:absolute,to:'2019-05-07T13:05:42.152Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
@timhirsch, @andrewrodrigues  likely need this function on 10 May meeting with IUCN

**Comment by ahahn-gbif** [comment]
#1792

**Comment by MortenHofft** [comment]
closing in favour of #1792
