### ISSUE TITLE
location should be Tamps., Mex., not in the Gulf of Mexico...

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1928]
**location should be Tamps., Mex., not in the Gulf of Mexico...**

`https://www.gbif.org/occurrence/1895041057`

-----

System: Chrome 74.0.3729 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/c862eb1b52bc5cd2110c7d2cdd6648ea:07249ebd69dce98c0232e0e8f5e100675699c74f987761d5aa250df4dd17f5c479bb578bcfdaf03fa9910cefc3438e49f47f3b7cf8cc97ebc892b845a7afbfee)
Referer: https://www.gbif.org/occurrence/1895041057
Window size: width 1208 - height 730
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-07T22:48:15.380Z',mode:absolute,to:'2019-05-07T22:54:15.380Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-07T22:48:15.380Z',mode:absolute,to:'2019-05-07T22:54:15.380Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
The coordinates given with this record (https://api.gbif.org/v1/occurrence/1895041057/fragment) point at 
decimalLatitude: 24.0675;decimalLongitude: -92.1016667, which is inconsistent with the textual location information ("IXMIQUILPAN, CARR. 85, HIDALGO"). We will inform the publisher of the dataset.

**Comment by ahahn-gbif** [comment]
(information sent by email)

**Comment by jhnwllr** [comment]
The occurrence was deleted.
