### ISSUE TITLE
images not of Pachybrachis...

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1931]
**images not of Pachybrachis...**

I assume these images are Derospidea brevicollis (LeConte)
but certainly not Pachybrachis brevicollis LeConte, 1880...

-----

System: Chrome 74.0.3729 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b6acb1e66a906f526b4dc088c805ed6d:389b6cf19db0b920d8fb519811f3151076358473996f0ecf2f5baecf6b54ed95402b5637c585c2f7e8569cea410e4fb9ee1c31ac1b5b482a3e8d838e00507c54)
Referer: https://www.gbif.org/species/1047994
Window size: width 988 - height 730
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-08T14:45:36.676Z',mode:absolute,to:'2019-05-08T14:51:36.676Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-08T14:45:36.676Z',mode:absolute,to:'2019-05-08T14:51:36.676Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The CoL assumes that these two species are synonym.

**Comment by yroskov** [comment]
There are two different species in CoL: Derospidea brevicollis (J. L. LeConte, 1865) and Pachybrachis brevicollis J. L. LeConte, 1880. They are not synonyms.

**Comment by ManonGros** [comment]
issue fixed in the current backbone
