### ISSUE TITLE
Does speciesKey number represent genomic sequence?

### ISSUE THREAD

**Issue by valerydec17** [gbif/portal-feedback#1932]
This is from a table on Bacteria 
species	speciesKey
Edwardsiella	3221906
Aquicella	3223027
Chitinophaga	3228826
Chilodonella	7542662

My question is: Are these numbers abstract? Or they are based on similarity of organisms. So that it becomes possible to make some meaningful ML analysis of this data.

**Comment by MortenHofft** [comment]
Species Keys are essentially random. They are IDs and can not be used to infer anything about relations. For that you need the taxonomy which is also available through the APIs.

Hope that helps
