### ISSUE TITLE
Too many occurrences for newly ingested dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1934]
**Too many occurrences for newly ingested dataset**

1. I just republished `https://www.gbif.org/dataset/8124cd73-ac84-43d2-ab39-1d80dc346525` with 16,742 occurrences.
2. On the dataset page, I clicked `Ingest now`
3. Dataset was harvested
4. Number of occurrences at GBIF is now 17,481, which is too much. Are some records not correctly removed?

-----

User provided contact info: @peterdesmet
System: Chrome 74.0.3729 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/882a41ca87b10f15372793d22fbb4bde:a1926a421fa75da0d17bace4a97fcdda77cbe67636cb11b867bbbc64311830b2570cad035665fdc3db1ab34ae273367d6d26d1af9fd7c2a213407b1f01f9e9b8)
Referer: https://www.gbif.org/dataset/8124cd73-ac84-43d2-ab39-1d80dc346525
Window size: width 1375 - height 717
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-09T08:00:57.440Z',mode:absolute,to:'2019-05-09T08:06:57.440Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-09T08:00:57.440Z',mode:absolute,to:'2019-05-09T08:06:57.440Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
https://registry.gbif.org/monitoring/overingested shows it as a possibly overingested dataset for investigation. This typically happens if there are a lot of changes in the dataset or occurrenceIds are not kept. Or if the source data cannot be parsed correctly and we cut it in 2. In these cases we are conservative and investigate before deleting records that aren't in the newest crawl. I cannot remember the threshold for this.

**Comment by peterdesmet** [comment]
Normally the occIDs should be the same. I see the issue is resolved now (number of occs is correct).
