### ISSUE TITLE
Obsolete Datasts

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1935]
**Obsolete Datasts**

Hi
we - the Herbaria of the University and ETH Zurich had to refactor our whole database and the IPT installation. Now we have some obsolete datasets which schould be either hidden or deleted. One of them has 0 occurences and the ingestion doesn't work at all, the other one has around 83'000 occurences but the last update is from 2013.

-----

User provided contact info: alex.bernhard@systbot.uzh.ch
System: Firefox 66.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7f1d1277175c2398040b03833ab51263:5782b949310e14e19bbe9a07c8578d88eb6f6b2c9b2be0887c48f7f088a22922c2ae06dee80cb7eeb34f12df961b83a7180868b7719055f3dbd5a5bc822354fa)
Referer: https://www.gbif.org/dataset/db504a46-955f-45a6-bdc9-d9a7ebc85668
Window size: width 1328 - height 722
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-09T13:39:16.251Z',mode:absolute,to:'2019-05-09T13:45:16.251Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-09T13:39:16.251Z',mode:absolute,to:'2019-05-09T13:45:16.251Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The two datasets have been deleted. The pages are still preserved (along with the citations) but are now linked to the new dataset.
