### ISSUE TITLE
Can´t download any dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#194]
**Can´t download any dataset**

when i trry to dowload mi selected area, the following message appears:

We currently cannot process your download request. Please report the error and try the production site instead at GBIF.org

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51

System: Chrome 58.0.3029 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/download?geometry=POLYGON%20((-99.755859375%2028.05259082333983,%20-100.4150390625%2027.27416111737468,%20-100.107421875%2026.15543796871355,%20-99.25048828124999%2026.82407078047018,%20-99.140625%2027.72243591897343,%20-99.755859375%2028.05259082333983))
Window size: width 1920 - height 974
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-23T16:11:21.045Z',mode:absolute,to:'2017-05-23T16:17:21.045Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-23T16:11:21.045Z',mode:absolute,to:'2017-05-23T16:17:21.045Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thanks for reporting.
This is due to https://github.com/gbif/occurrence/issues/8 and will of course be fixed before release.
