### ISSUE TITLE
Consortium of California Herbaria dataset listed as 'metadata'

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1940]
**Consortium of California Herbaria dataset listed as &#39;metadata&#39;**

2.7 million records in this dataset, lots of citations—but it's listed as a metadata dataset. Is some inadvertent mistake that's slipped in…?

-----

User provided contact info: @kcopas
System: Safari 12.1.0 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/210c27ab5f28ddc2250b245558f2730b:c6f2e73d26dc0c003c1af879279a0e30d82e71e219b7b4218c152e9f62c3d5938f424c06585a02242d63c03ee4c1bf887e02d371452653ef2d2c7d4e643ff931)
Referer: https://www.gbif.org/dataset/4fa894f4-b6c6-4ec0-b816-9bb03b3ca106
Window size: width 1399 - height 864
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-10T10:05:46.724Z',mode:absolute,to:'2019-05-10T10:11:46.724Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-10T10:05:46.724Z',mode:absolute,to:'2019-05-10T10:11:46.724Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@kcopas They actually wanted to make it into a metadata dataset (and remove all their occurrences) because they would like each publisher to republisher their own data through their Symbiota platform. I actually suggest that they keep the metadata with the citations.

I am not sure why we still have the occurrences right now, perhaps they thought that they didn't need to remove them if they changed the type to `metadata`. I will forward you my conversation with them.

**Comment by ManonGros** [comment]
Actually, they did remove their data but we didn't de-index them.

**Comment by kcopas** [comment]
Got it—that's a very cool explanation. Do we now how many herbaria we're talking about in the consortium? And are they all set up and ready on Symbiota? 

All this is the positive flip side of wondering: are we going to experience any data loss when we do de-index this?

**Comment by MattBlissett** [comment]
The citations will remain, but it would mean 2.3 million fewer occurrences in our index.

It would be reasonable to update the dataset description with a link to the replacement datasets, or perhaps the publisher that's sharing them.
