### ISSUE TITLE
Finch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1941]
**Finch**

The finch R package has a dwca_validate function, which is great. But there are two issues making it difficult to set up reproducible workflows using finch::dwca_validate:

- It seems to use the older validation tool (?) and although no errors are reported the validation report looks like this: `https://tools.gbif.org/dwca-reports/130-3216664245498808666.html` when running it with a call like this one:

library(finch)
dwca_validate("`https://github.com/bioatlas/data-mobilization-pipeline/blob/master/molecular-data/using-existing-taxa/indata_its/occur-its.zip?raw=true`", browse = TRUE)

I think it used to work differently before and reported back the issues in details.... Now it just says "validation succeeded" and links back to itself, so to speak.

- It would be nice if the finch library could call out to the newer data validator, but it has authentication. Any advice or pointers on how to authenticate when automating use of the validation tool? I could perhaps try to make a PR to the finch library but then I need to understand how to authenticate, I guess?

- The finch library dwca_validate requires a public url for the dwca before the validation tool can be used, which is a little like the egg needing a hen, in the sense that when validating you might not yet be ready to publish stuff on the internet. So, for a starter, would it be possible to post a dwca-file directly to the service/api for the validation tool?

Just a few ideas and happy to listen to suggestions - I am looking ideally for a using a library or tool that would allow off-line validation before submitting. Are there any such efforts? Could existing tools for dwca validation from GBIF be used in offline scenarios?

-----

User provided contact info: @mskyttner
System: Firefox 66.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/19b5bdfd7b215cd9daa2006547a7d7bf:1d91ab7e42e94f87732f9e15703745c8fb499bc6e394b287532b69cb4d72c01cc4720ab3f20bbd2dd6f0e0a1884385bb53396dd6c14babf613b8d33c36da08c3)
Referer: https://www.gbif.org/tools/data-validator/1556043575723
Window size: width 1600 - height 769
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-10T18:14:12.068Z',mode:absolute,to:'2019-05-10T18:20:12.068Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-10T18:14:12.068Z',mode:absolute,to:'2019-05-10T18:20:12.068Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Just quickly...

(I haven't used finch, the main developer @sckott will have his own thoughts on this.)

> It seems to use the older validation tool (?)

That is the older tool, but they serve different purposes: the older one does a structural test of the archive — is the meta.xml present and correct, using valid terms and so on.  The newer one runs an interpretation using GBIF's normal processes (or close to that), so it can say if the scientific names are unknown, or the coordinates don't match the provided country.

> Any advice or pointers on how to authenticate when automating use of the validation tool?

A straightforward authentication method is to use HTTP Basic authentication.  You can test if you are authenticating correctly by receiving a 200: `curl --user username:password -i 'http://api.gbif.org/v1/user/login'`

> So, for a starter, would it be possible to post a dwca-file directly to the service/api for the validation tool?

Both tools support an HTTP file upload instead, so this should be possible.

> Could existing tools for dwca validation from GBIF be used in offline scenarios?

Not with the interpretation, as that uses GBIF's webservices, although you can run the [validator](https://github.com/gbif/gbif-data-validator/) yourself if you want to. It could also be modified to not run the interpretation checks, although it's then a pretty heavy tool for just the structural checks.

The [dwca-io](https://github.com/gbif/dwca-io/) library makes a basic validation when opening a DWCA, but it doesn't give a helpful error if the archive is invalid.

**Comment by sckott** [comment]
I concur that the old validation API at https://tools.gbif.org/dwca-validator/api.do doesn't seem to work as it used to. Is it essentially end of life and shouldn't be used anymore?  

I don't see any API docs for the new validator, is it GUI interface only for now?

**Comment by mskyttner** [comment]
The docs at https://github.com/gbif/gbif-data-validator/blob/master/doc/cli.md describes an example curl call for doing a POST using basic authentication against the validator, so I tried used it like this:

`curl -i --user mysername:mypassword -H "Content-Type: application/json" -H "Accept: application/json" -X POST -F 'file=@dwca.zip;type=application/zip' http://api.gbif.org/v1/validator/jobserver/submit`

And tried the same from R also:

```r
library(httr)

job <- POST(
  "https://api.gbif.org/v1/validator/jobserver/submit",
  authenticate(Sys.getenv("GBIF_USER"), Sys.getenv("GBIF_PASS")), 
  body = upload_file("~/Downloads/dyntaxa.dwca-with-lsid.zip"),
  encode = "multipart"
)

content(job) %>% as.character()

```

The Varnish responds to both these POSTs with a complaint about a failed backend fetch:

`HTTP/1.1 100 Continue

HTTP/1.1 503 Backend fetch failed
Date: Mon, 13 May 2019 19:28:42 GMT
Server: Varnish
Content-Type: text/html; charset=utf-8
Retry-After: 5
X-Varnish: 592284053
Age: 0
Via: 1.1 varnish (Varnish/5.2)
Content-Length: 286
Connection: close

<!DOCTYPE html>
<html>
  <head>
    <title>503 Backend fetch failed</title>
  </head>
  <body>
    <h1>Error 503 Backend fetch failed</h1>
    <p>Backend fetch failed</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 592284054</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
`

When doing this the response header for "location" I noticed in the browser's "network view" mode is "http://api.gbif.org/v1/v1/jobserver/status/1556043575739" which has a double **/v1/v1** - could that somehow come into play and cause the failed fetch, or is something other at play here?

**Comment by jhnwllr** [comment]
https://github.com/ropensci-archive/finch/issues
This tool is no longer actively maintained. I am going to close this issue, since it no longer seems relevant.
