### ISSUE TITLE
Count of accepted species by County and Phylum

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1943]
**Count of accepted species by County and Phylum**

Hi there,

Thank you for providing this wonderful resource!  I'm looking for a way to query the data so I can generate a count of accepted species in Canada by Phylum.  When you search the data by 'Species', you can see how many species there are in each taxonomic group, but there is no way to search/subset the data by Country or Area.  As a work-around, I tried searching occurrences by Country and Phylum, then downloading the species list in CSV.  However, this gives a list of accepted species, unaccepted species, synonyms etc., such that it is very cumbersome to sort through the data.  Do you have any suggestions on how to get a count of accepted species in a particular taxonomic group by country?  

Thank you for your help,
Jessica

-----

User provided contact info: schultz.jessica.a@gmail.com
System: Chrome 73.0.3683 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/f78894218b9ea4fb91d03bea9f98a341:159377049bbb94187055a12ac44580eed68b468a95e576c230fce4b3861ffc220027d1b2fc9417096404379cb38605177b0a60b699b449809b983d23e99099c3)
Referer: https://www.gbif.org/
Window size: width 1440 - height 717
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-12T03:46:45.831Z',mode:absolute,to:'2019-05-12T03:52:45.831Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-12T03:46:45.831Z',mode:absolute,to:'2019-05-12T03:52:45.831Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
Replied via email schultz.jessica.a@gmail.com

Hi Jessica, 

The species count downloads are a new feature, so it is not yet possible to download a species list of only accepted species using the website. 

The best option is probably to download the species list you want and then filter using some 3rd party software like Excel, R, ect… 

I have attached a csv of ACCEPTED species in Canada. 

Best regards,

John Waller
Data Analyst
GBIF Secretariat
Universitetsparken 15
2100 København Ø
Denmark
e-mail: jwaller@gbif.org
