### ISSUE TITLE
I downloaded data on the distribution of koalas in Australia. When I input the csv into Excel there seems to be a mismatch between the column headings and the coordinate data. The latitude is listed in the longitude column and the longitude is listed in the coordinate uncertainty column. I can send a screenshot if you wish.. Best regards,

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1944]
**I downloaded data on the distribution of koalas in Australia. When I input the csv into Excel there seems to be a mismatch between the column headings and the coordinate data. The latitude is listed in the longitude column and the longitude is listed in the coordinate uncertainty column. I can send a screenshot if you wish.. Best regards,**

-----

System: IE 11.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/cc0fc488df2aa132261c204b34ec0a6d:0ddc695828ce6be09f589353900179f117b8766ea0d0fad3515400986b23fb64a32dbca29a809f3b6410c35d760f5c1f9da1fd7b087ffbb99dd49dc35d9db74f)
Referer: https://www.gbif.org/faq
Window size: width 1951 - height 889
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-12T15:14:06.763Z',mode:absolute,to:'2019-05-12T15:20:06.763Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-12T15:14:06.763Z',mode:absolute,to:'2019-05-12T15:20:06.763Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I downloaded the data in https://www.gbif.org/occurrence/download/0011832-190415153152247 and it looks good to me. 
Be aware that the data is tab seperated. See https://www.gbif.org/faq?question=opening-gbif-csv-in-excel

> sent per mail
