### ISSUE TITLE
Confused identifiedBy, recordedBy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1946]
**Confused identifiedBy, recordedBy**

Data from this publisher appears to have confused the semantics and intended use of identifiedBy & recordedBy resulting in illogical dates associated with these terms. In this particular example, the specimen also appears to have been collected by Naumann,F.C. in 1875.

-----

System: Chrome 74.0.3729 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/575783ca7922bdf4ab1a322272979bef:f939917c53558a758587519d85a9a30f7b4af5a79dc38ef770c4235c369e921d8d35bd8ac0335ba51a4bd638a12c5d6d8b050f6d5cda60ec30a4ecd7d372fd7f8c5ff9453daa924cf97ab7a18f41dd9c)
Referer: https://www.gbif.org/occurrence/1703323949
Window size: width 1324 - height 699
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-13T13:16:34.554Z',mode:absolute,to:'2019-05-13T13:22:34.554Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-13T13:16:34.554Z',mode:absolute,to:'2019-05-13T13:22:34.554Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This occurrence seems to have been updated: both `recordedBy` and `identifiedBy` have the same name. Closing the issue, let me know if I overlooked something.
