### ISSUE TITLE
gbifID=1503113218 contains a tab that corrupts the CSV

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1947]
**gbifID=1503113218 contains a tab that corrupts the CSV**

gbifID=1503113218 contains a tab that corrupts the CSV

-----

System: Firefox 66.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4f5b2b86aeb77826e67fe7fdefff6b7f:231ea2acbac5ac2a495dacac81e75fd4af88d30af60b2cd89434f6f023c764af380dabdf4e431e2d1d6282780af40d982da02f4a96af2254a670b63591987187)
Referer: https://www.gbif.org/faq
Window size: width 1673 - height 850
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-14T07:23:40.956Z',mode:absolute,to:'2019-05-14T07:29:40.956Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-14T07:23:40.956Z',mode:absolute,to:'2019-05-14T07:29:40.956Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
https://www.gbif.org/occurrence/1503113218

I don't see any tabs, but I do see that `identifiedBy="` (a single double quote), which could cause a problem if the file is imported with "String delimiter" set to `"`.

![localc-tsv](https://user-images.githubusercontent.com/583320/57681461-0bccf500-7630-11e9-9583-cfdaf262e59f.png)

**Comment by eloi-isric** [comment]
Thanks @MattBlissett for pointing me out what the problem was.
I was trying to put this csv in a PostgreSQL database and I didn't find a way to tell the PostgreSQL COPY command to ignore the double quotes. So what I did was to remove all double quotes in the csv with sed command and then the import worked just fine.

```
-- remove all " in a text file
sed -i -e 's/"//g' 0012192-190415153152247.csv

```
