### ISSUE TITLE
kindom and higher taxonomy possibly wrong or missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1950]
**kindom and higher taxonomy possibly wrong or missing**

I see incertae sedis for kingdom. Likely higehr taxonomy and kingdom information was available for the SH, but somehow did not reach GBIF. Same for all records in the dataset, resulting in the empty metrics for the dataset

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/c483d83fae5fb811d5f852e6bea3f81f:c1cf740463d17075a73ffa4162a3bdfe74042219f2e2433080a79bad37cace402001d0e51ce2b084f03b713c582d12cbe0efd91ff7833569396ccba385fe96d2)
Referer: https://www.gbif.org/occurrence/2238656118
Window size: width 1536 - height 737
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-14T12:21:43.574Z',mode:absolute,to:'2019-05-14T12:27:43.574Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-14T12:21:43.574Z',mode:absolute,to:'2019-05-14T12:27:43.574Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
@thomasstjerne thought you might have an idea? Kai was with us in Dragør

**Comment by thomasstjerne** [comment]
It looks like no higher classification was given; https://api.gbif.org/v1/occurrence/2238656118/fragment

The GBIF taxonomy has not yet included Species Hypothesis V8. This will be in the next backbone build, probably late 2019

**Comment by dschigel** [comment]
Thanks @thomasstjerne. I suggest we keep the issue open and dependent on the switch to V8, and inform Kai Ilves on the changes needed, if any, after the reindexing under V8

**Comment by ManonGros** [comment]
The issue seems to have been solved with the latest backbone update.
