### ISSUE TITLE
ID equals Apoidea NOT Apoides

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1951]
**ID equals Apoidea NOT Apoides**

There are at least 1,477 collection object records from the SEMC database with the incorrect determination of Apoides Tsuneki, 1968 in GBIF.  These records are correctly ID'ed in the SEMC database as the superfamily APOIDEA. 

We don't have any specimens in the SEMC database determined to Apoides. Thanks for your help.

-----

User provided contact info: jct@ku.edu
System: Chrome 74.0.3729 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/cee7d805d6c006409f33d5dcd731c64e:1be00bd148a50cbf1e72821e74395dec8e430d813e8d870166c55e146f264b8f6ba7d834425c34e71e05adf4ad75f24e895155d03c03ba6de5a0c06389bafec4)
Referer: https://www.gbif.org/occurrence/1580839861
Window size: width 1439 - height 785
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-14T19:41:41.833Z',mode:absolute,to:'2019-05-14T19:47:41.833Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-14T19:41:41.833Z',mode:absolute,to:'2019-05-14T19:47:41.833Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> Unfortunately, our backbone taxonomy doesn’t contain intermediary ranks (no super-family, nor super-order, etc). Since our system doesn’t find any matching name for “Apoidea”, it matches it to “Apoides”.
> The issue is logged and the relevant people have been notified so we will try to work on it. However, I don’t know we will be able to fix the issue.

> In the meanwhile, in order to avoid having the records tagged as “Apoides”, I suggest that you use the family name is you can or the order name. I know that the later would be a loss of information but this is better than having the wrong genus.

**Comment by mdoering** [comment]
the backbone does not have super/sub ranks, so we can only support this in the new CoL+ based version that is estimated for first half of 2020
