### ISSUE TITLE
data papers needs IF updates from 2018

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1952]
**data papers needs IF updates from 2018**

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/d76c35118a591cbdf42cc2310c344d36:5e0504aac5d1050fa45e8a0f3ce6033c251bb38b9b5f76e0f2c40de57ec9b7e0d4b468c8f8ac726de191e25ac93138c822da239fc82153279d7a221e9a5768ce)
Referer: https://www.gbif.org/data-papers
Window size: width 1536 - height 737
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-15T07:57:04.662Z',mode:absolute,to:'2019-05-15T08:03:04.662Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-15T07:57:04.662Z',mode:absolute,to:'2019-05-15T08:03:04.662Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
Adding Daniel and Kyle to make sure this is not missed by comms & webteam (perhaps there is a more elegant way, or "content" category is enough). It may be a very good idea to add two more columns to highlight if the journals are listed in i) Scopus ii) Web of Science, this is the question I have to answer basically every time I explain data papers, and my unswer at the moment is "please check youselves", maybe it is ok like that, maybe can can have a more informative page.

**Comment by kcopas** [comment]
Sorry, I don't understand what is being requested here.

**Comment by kcopas** [comment]
What is IF? 

Asking for a friend, in case you use that abbreviation again…

**Comment by dschigel** [comment]
IF = impact factor

**Comment by kcopas** [comment]
Please don't assume it's more columns. 

Good to know what information you're looking for. Let us devise implementation.

**Comment by dnoesgaard** [comment]
I don't think 2018 data is out yet, but I've updated the table with 2017 data now. Will look into the additional information...

**Comment by dnoesgaard** [comment]
(Btw any issue tagged 'content' ends up with comms)

**Comment by dnoesgaard** [comment]
I've added Scopus indexing information now. AFAIK, having an impact factor implies indexing in Web of Science. I've also reworked the OA column to include licensing. A big applause for open APIs!
