### ISSUE TITLE
Problems with rodent taxonomy

### ISSUE THREAD

**Issue by PMoreno92** [gbif/portal-feedback#1953]
Hi, I was looking at the taxonomy of some rodents in GBIF and I have some doubts:

 - When querying for Alticola macrotis, GBIF returns Thomasomys macrotis. Nevertheless, Alticola macrostis is a species distributed in Asia (mainly Russia and Mongolia) whereas the genus Thomasomys is neotropical and distributed mainly in Colombia, Peru and Ecuador. All of the records in GBIF are from Russia, thus I do not really understand why is Alticola substituted by Thomasomys.

 - I am confused about the source that is used for the mammal taxonomy, Wilson and Reeder use Spermophilus rather than Urocitellus. Additionally, both Wilson and Reeder and the IUCN redlist use Neodon juldaschi rather than Blanfordimys juldaschi. 

Thanks!

**Comment by ManonGros** [comment]
It looks like in the current taxonomy, Spermophilus is the preferred name but the other issues remain.

**Comment by yroskov** [comment]
Comment should be send to ITIS.

**Comment by ManonGros** [comment]
the issue seems to be fixed in the latest backbone
