### ISSUE TITLE
My download with geometry failed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1954]
**My download with geometry failed**

Hi there,

I'm developing a script in r through rgbif to download gbif data for arbitrary areas using the geometry argument. Could you please tell me what may be going wrong with my request as the only error I get was that the download request was unsuccessful. The link to my query is `https://www.gbif.org/occurrence/download/0014194-190415153152247`

Best

Jorge

-----

User provided contact info: @jivelasquezt
System: Chrome 73.0.3683 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/242a93008f23c79c99dc5d3c8a37aa94:bdff393596adb0544f16fa9bdfec8a544a63e62241e5ab033a7d677e606acfd5015f338fb654659444f9e6752b908f23462a6c9431a04448f3284091fab7c272)
Referer: https://www.gbif.org/occurrence/download/0014194-190415153152247
Window size: width 1878 - height 816
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-16T16:22:46.047Z',mode:absolute,to:'2019-05-16T16:28:46.047Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-16T16:22:46.047Z',mode:absolute,to:'2019-05-16T16:28:46.047Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Hi,

Sorry for the slow answer.

The geometry query needs to use a "within" predicate, not "equals". If you search for "within" on https://www.gbif.org/developer/occurrence you will see an example.

Also relevant to https://github.com/gbif/occurrence/issues/124
