### ISSUE TITLE
Collector info missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1958]
**Collector info missing**

Record at source clearly identifies the listed identifiers (L.B. Moore & L.M. Cranwell) as the collectors, too.

-----

User provided contact info: @kcopas
System: Safari 12.1.0 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/c7487bc0a5f2df087d499088c83f1cb2:65e7ca9073c89e8bdfd0f4443a51de287be277f87077c33243418cb767b857df3351302e32762a89ec94d1904fa79f5e104bc4b305028acbc7f073346415d98c)
Referer: https://www.gbif.org/occurrence/1091163394
Window size: width 1431 - height 939
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-19T13:06:45.673Z',mode:absolute,to:'2019-05-19T13:12:45.673Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-19T13:06:45.673Z',mode:absolute,to:'2019-05-19T13:12:45.673Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Same issue as above for records from the same collection/dataset for the following: 
https://www.gbif.org/occurrence/1091128246
https://www.gbif.org/occurrence/1091250848

Additional records with issues

Collector probably incorrectly identified as 'LN Cranwell':
https://www.gbif.org/occurrence/1316271013
https://www.gbif.org/occurrence/1316556116

**Comment by jhnwllr** [comment]
I am not sure if we should push a dataset to include non-required fields that they choose not to include. @ahahn-gbif 

I think this issue should be closed if there is not other problems other than that it is missing. 

[df582950-3b58-11dc-8c19-b8a03c50a862](https://www.gbif.org/dataset/df582950-3b58-11dc-8c19-b8a03c50a862)
