### ISSUE TITLE
Incorrect collection date

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1964]
**Incorrect collection date**

Date is 1/1/1700, despite associated evidence that this specimen was collected by Charles Darwin in Jan 1832 during the Beagle voyage.

-----

User provided contact info: @kcopas
System: Safari 12.1.0 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/a8561be058cf8333e46689ae07cfd780:4d20bc1311102d9389cd91eddadb6ab09a9ff404d87fa5f42ad19b8ad5ca48333525723334d9b3ccfd5ffdf3146f4c01d25f3549eea76a88bec55338d45f42dd)
Referer: https://www.gbif.org/occurrence/477891621
Window size: width 1431 - height 939
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-19T14:55:59.808Z',mode:absolute,to:'2019-05-19T15:01:59.808Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-19T14:55:59.808Z',mode:absolute,to:'2019-05-19T15:01:59.808Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The date entered is actually a date range `1700-01-01/2016-12-14`. I don't think that they had the opportunity to assign precise dates to their specimens.

**Comment by kcopas** [comment]
Fair enough. But wouldn't a null value be more useful than a four-century range?

**Comment by ManonGros** [comment]
They removed the dates.

**Comment by kcopas** [comment]
what a cop-out!
