### ISSUE TITLE
display of occurrences on map not complete

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#1966]
In this case https://www.gbif.org/dataset/8bb17a01-6ca6-4225-a42c-be3cb22e3db0 there are many occurences with coordinates https://www.gbif.org/occurrence/search?dataset_key=8bb17a01-6ca6-4225-a42c-be3cb22e3db0, but on the map there is only one (one dot, and when you explore the area, there is only one occurrence provided.

![image](https://user-images.githubusercontent.com/4609956/57999722-b9c81b80-7ad6-11e9-90aa-2c19d62e9d28.png)

**Comment by MattBlissett** [comment]
The DWCA only contains 9 records (in occurrence.txt) with a decimalLatitude and decimalLongitude so I don't think there's an issue on our side.

**Comment by MortenHofft** [comment]
Sounds like a temporary data inconsistency. The map in the screenshot also says that is is 6 hours old.  @myrmoteras I'm closing this. Please reopen if you believe there still is an issue.
