### ISSUE TITLE
Page typo: illusive / elusive

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1967]
**Page typo: illusive / elusive**

From a [description of acoustic profiling research](`https://www.gbif.org/data-use/5rQoNfQKiLQuB3LI22zTUK/classifying-crickets-chirps-acoustic-profiling-in-orthoptera)` using GBIF mediated data

> Allowing for non-invasive and cheap detection of **illusive** species, identifying animals—e.g birds and frogs—through sound is becoming increasingly popular, particularly in habitats where visual observation is difficult or even impossible.

If the intent is to describe the species as difficult to spot this should be "elusive". "Illusive" derived from illusion, i.e. not really there.

-----

User provided contact info: @nickynicolson
System: Chrome 74.0.3729 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/44651f547270fe66b49fb09bb59966a1:ee2589e632be9a986a90540a9d22bbffb4fef4d5d3f1267f19a0881b273a8b561a917cae3c9cabac1837921b0844d2aba77d2ca5afa98e9672cd436075ab2ba2)
Referer: https://www.gbif.org/data-use/5rQoNfQKiLQuB3LI22zTUK/classifying-crickets-chirps-acoustic-profiling-in-orthoptera
Window size: width 2542 - height 1313
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-21T09:59:24.669Z',mode:absolute,to:'2019-05-21T10:05:24.669Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-21T09:59:24.669Z',mode:absolute,to:'2019-05-21T10:05:24.669Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Thanks @nickynicolson for spotting this. I've corrected it now.
