### ISSUE TITLE
BOLD and IUCN to add to See also and to rename the section

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1968]
**BOLD and IUCN to add to See also and to rename the section**

I suggest that footnote See also has two more icons, IUCN and BOLD, where their respective species pages are opened through a simple name search (before the taxon and species identifiers allow to do that in a smarter way).

See link to the barcodes implemented by GBIF Finland `https://laji.fi/en/taxon/MX.193109`

I also think See also is a bit wrong name. I thin kthe meaning is that there is more data from the key partners, but not yet sure what would be a clearer name for this

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e73a0598a1dc51268e4ac9ed0a716657:1eff021dd4a35eccdcf3330e5e29344111f1c86ade4638bff08d0fab1d53877f6e33dece7b322debcda344673ca9aaa483497e4d085480653b4e6e4502aaa0cb)
Referer: https://www.gbif.org/species/4449455
Window size: width 1922 - height 1073
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-22T09:34:20.351Z',mode:absolute,to:'2019-05-22T09:40:20.351Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-22T09:34:20.351Z',mode:absolute,to:'2019-05-22T09:40:20.351Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
This has since changed to show all related identifiers from wikidata. I'll assume this can be closed. Else please reopen.
