### ISSUE TITLE
Address styling issues of developer API docs

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#197]
**TOC not floating**

-----
fbitem-d7fe0c58772fa99501bfeba54604bc553eb4399f

System: Chrome 58.0.3029 / Mac OS X 10.12.5
Referer: https://demo.gbif.org/developer/species
Window size: width 1665 - height 883
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-31T11:29:29.493Z',mode:absolute,to:'2017-05-31T11:35:29.493Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-31T11:29:29.493Z',mode:absolute,to:'2017-05-31T11:35:29.493Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
If I understand the issue correctly, I cannot reproduce this. I have tested with the same browser and version. But the page could need more cross browser testing

**Comment by mdoering** [comment]
The gap above "Working with Name Usages" should not exist, or is this intentional?

![screen shot 2017-06-01 at 12 12 42](https://cloud.githubusercontent.com/assets/327505/26675288/aa1eea0e-46c3-11e7-831f-4a7e652bf921.png)

**Comment by MortenHofft** [comment]
The developer pages in general need some attention. Maps is another example that doesn' display correctly. Didn't get that was the issue. Thanks.

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/461
