### ISSUE TITLE
New version of backbone with SILVA and Dyntaxa taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1970]
**New version of backbone with SILVA and Dyntaxa taxonomy**

Can you give some indication on when the new version of the backbone will be published next?

We'd like to know if there is a timeline we need to meet, because we'd like to get an up-to-date Dyntaxa into it, so we later can use the GBIF backbone taxonomy within Bioatlas Sweden.

We also work with people that ask about when the SILVA bacterial taxonomy could be incorporated in the GBIF backbone. If it would be possible for you to indicate a timeline or expectation here, we'd be interested in synching our actions based on that.

We have done some initial work with packaging the SILVA dataset as a checklist but would prefer to use it from the GBIF backbone rather than trying to merge Dyntaxa, SILVA and the GBIF backbone on our own, since we're struggling a bit with the tools we have available for the merge while at the same time the software we use (Living Atlases) does not (yet) allow indexing against several different checklists or taxonomies, which seems to be something asked for frequently by our stakeholders here.

-----

User provided contact info: @mskyttner
System: Firefox 66.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/d7ca8caa0e4d30738fbbb683ff20a992:77482d7fd31ff51a9505c828d17c89c1967cac527427b22293f049460d3d76b849f9fcdf0d3f668c3b4610382e4cf63f14c7ffee2d73e7451acfd656d214eebe)
Referer: https://www.gbif.org/user/profile
Window size: width 2349 - height 1236
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-23T07:01:22.968Z',mode:absolute,to:'2019-05-23T07:07:22.968Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-23T07:01:22.968Z',mode:absolute,to:'2019-05-23T07:07:22.968Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
Dear @mskyttner
We expect to pay attention to this around Q3 2019. 
Like Living Atlases, GBIF does not support multi-taxonomy indexing. We are looking into the possibilities of incorporating either SILVA or GTDB into the backbone, but cannot promise anything yet.

Best,
Thomas Stjernegaard Jeppesen

**Comment by mskyttner** [comment]
Thanks @thomasstjerne, could you also say something about when the deadline is for us to get the latest Dyntaxa into the next version of the backbone?

**Comment by ManonGros** [comment]
it seems like this issue is a bit outdated. I will close it, let me know if it should be reopened.
