### ISSUE TITLE
Integration with Mendeley plugin

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1971]
**Integration with Mendeley plugin**

@dnoesgaard I see that Mendeley promote their webplugin. It isn't really working well with GBIF. Is it worth exploring what it takes to autogenerate sensible citations (perhaps in dialog with Mendeley)?

-----

User provided contact info: @MortenHofft
System: Chrome 74.0.3729 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/ff81858aa2dad558df0dbc6e41dc9c3e:3e9368efdd84221e3dcabf0e9c3f304520af5ca19c703145bea61cb3c616d60005c5a140b2ad8750d577fbc5d081d8990bc560fbcd70facb287e7a81a56eabbe)
Referer: https://www.gbif.org/occurrence/download/0017239-190415153152247
Window size: width 1889 - height 1292
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-23T07:08:21.901Z',mode:absolute,to:'2019-05-23T07:14:21.901Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-23T07:08:21.901Z',mode:absolute,to:'2019-05-23T07:14:21.901Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
As mentioned, I don't think this is worth pursuing...
