### ISSUE TITLE
checklist dataset country is Ireland in occurrences but is actually Papua New Guinea

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1976]
**checklist dataset country is Irealand in occurrences but is actually Papua New Gunea**

This checklist dataset has 1026 occurrences that have the country Ireland. 

`https://www.gbif.org/dataset/8bb17a01-6ca6-4225-a42c-be3cb22e3db0`

But the province is "New Ireland". The country field is filled in incorrectly for 1026 records.  Country coordinate mismatch flagged 48 records.

-----

User provided contact info: @jhnwllr
System: Chrome 74.0.3729 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/88f84837b0d3e04f6a1b3139a7d94135:dcd6b414080b8f15fa2850ff9b6d8a5e4b8f509e05458ab9ba41351b69f26bebe728e41c116974c2245e58200897ec861cdc281d3e560dc52234fe4e0ae3b954)
Referer: https://www.gbif.org/dataset/8bb17a01-6ca6-4225-a42c-be3cb22e3db0
Window size: width 1920 - height 1057
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-24T09:39:38.604Z',mode:absolute,to:'2019-05-24T09:45:38.604Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-24T09:39:38.604Z',mode:absolute,to:'2019-05-24T09:45:38.604Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
@myrmoteras @gsautter This is mis-interpreted plazi checklist.

**Comment by ManonGros** [comment]
Contacted PLAZI by email.

**Comment by myrmoteras** [comment]
sorry - I messed up to respond in time. Will fix asap
