### ISSUE TITLE
The new URL for the Central Siberian Botanical Garden: http://csbg-nsk.ru

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1977]
**The new URL for the Central Siberian Botanical Garden: `http://csbg-nsk.ru`**

-----

System: Opera 60.0.3255 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/ac2baadc00266485d86f783a39ff718b:5abc2ea630abccd0ce445021324b4f7d64c288751de192fd99f5427b88833876c75d1845addc2f9d891f5bb8e7dfd590cdb7c820af049d354e178b19baab5888)
Referer: https://www.gbif.org/publisher/8f6232c3-5523-44ad-825c-e066fc6b15ad?fbclid=IwAR2vG4e5YYDfhAka0-ezrlG4fjKVALdqEO5MLXuSmbVp2Yx52H4TW4t8-3w
Window size: width 1240 - height 882
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-24T15:35:42.676Z',mode:absolute,to:'2019-05-24T15:41:42.676Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-24T15:35:42.676Z',mode:absolute,to:'2019-05-24T15:41:42.676Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Publishers contacted by email for confirmation.

**Comment by ManonGros** [comment]
URL updated.
