### ISSUE TITLE
Image for data papers page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#198]
**Image for data papers page**

The previous visual with &quot;dark skies&quot; was so cool! People loved it. It is still visible at the homepage.

-----
fbitem-798a246d270eb86c9618bff1749fad185b1857ba
Reported by: @dschigel
System: Firefox 53.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/publishing/data-papers
Window size: width 1922 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-31T15:20:56.386Z',mode:absolute,to:'2017-05-31T15:26:56.386Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-05-31T15:20:56.386Z',mode:absolute,to:'2017-05-31T15:26:56.386Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
Daniel changed it back for you ;)
