### ISSUE TITLE
0,0 coordinates instead of null

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1981]
**0,0 coordinates instead of null**

Adding zeros instead of null values for lat-long put this North American fossil specimen off São Tomé and Principe.

-----

User provided contact info: @kcopas
System: Safari 12.1.1 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/ec7a3b832744219cb33c42fa73337535:f390e267e1cf906326a58de5209333f9974f4dde42f18a1e31d9ad259eb02a377a073592d701bf46ac5cf3ddaa206c47cb9d048e2fcf6a701cfd8d9d7147e0b5)
Referer: https://www.gbif.org/occurrence/1913628551
Window size: width 1591 - height 939
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-25T06:07:31.663Z',mode:absolute,to:'2019-05-25T06:13:31.663Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-25T06:07:31.663Z',mode:absolute,to:'2019-05-25T06:13:31.663Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
email notification
