### ISSUE TITLE
1854, not 1834

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1982]
**1854, not 1834**

This specimen is clearly marked as one of those collected on the Perry expedition to Japan—correct year is 1854, not 1834 as listed.

-----

User provided contact info: @kcopas
System: Safari 12.1.1 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/9717aa7dc3ca0c908c807f368362f594:bd1302898c5e4ccf19c4c3f2df69b0c9bc52d85bc476bd2b2c6aaf55ec1118a262892761761d5ae9f5152d6582b2cfdc9dbe73e1d5bd1ae11730cb5c1dc63ae3)
Referer: https://www.gbif.org/occurrence/1317595184
Window size: width 1591 - height 939
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-25T16:23:28.361Z',mode:absolute,to:'2019-05-25T16:29:28.361Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-25T16:23:28.361Z',mode:absolute,to:'2019-05-25T16:29:28.361Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Feedback forwarded through the NMNH feedback system (http://n2t.net/ark:/65665/31160245a-3f81-4e3d-a356-e1e70d06b8ae).
