### ISSUE TITLE
Species list download failing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1984]
**Species list download failing**

Tried it twice, just to be sure ;-)

`https://doi.org/10.15468/dl.dqhfds`

`https://doi.org/10.15468/dl.v9pm08`

Same query, filtered on recorded_by,, 112 records in total: `https://www.gbif.org/occurrence/gallery?recorded_by=S.%20W.%20Williams%20%26%20J.%20Morrow&advanced=1`

-----

User provided contact info: @kcopas
System: Safari 12.1.1 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/078ee1d5097b7aab67919b6eb843d714:f38b9686669b976b057da8f953378bf2dfa5d281174535fc143ad0fea29678cfc7eabfd21470607ca0ecda7efdef93304ab0b29bcae1afbe0de702b45e8297af)
Referer: https://www.gbif.org/occurrence/download/0018556-190415153152247
Window size: width 1591 - height 939
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-26T07:33:11.525Z',mode:absolute,to:'2019-05-26T07:39:11.525Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-26T07:33:11.525Z',mode:absolute,to:'2019-05-26T07:39:11.525Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Confirmed. https://www.gbif-uat.org/occurrence/download/0000066-190802075855554

**Comment by MattBlissett** [comment]
```
  <arg>recorded_by:"S.\ W.\ Williams\ \&\ J.\ Morrow"</arg>
```

The & is not escaped.
