### ISSUE TITLE
Pagination links not working on DOI pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1985]
**Pagination links not working on DOI pages**

I can't get off the first set of 500 datasets on any DOI page—clicking on other numbers or next just reloads the first page.

My efforts to do so revolve around trying to uncover and reveal the depth of information, related to this [feature request for improvements on the page](`https://github.com/gbif/portal-feedback/issues/1916),` fwiw.

-----

User provided contact info: @kcopas
System: Safari 12.1.1 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/73a8453aae7e6e057c9cc5b57178abdb:666cc8ddcd9b4ac87aabd80a1a001ccaa9eeabd54a2f5637a5196b7ad4b5f4a5164e3e2762eb77a707a71528eafed49b57467f231b9171f013fd67ebf9099029)
Referer: https://www.gbif.org/occurrence/download/0011799-180412121330197
Window size: width 1469 - height 939
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-26T07:59:36.728Z',mode:absolute,to:'2019-05-26T08:05:36.728Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-26T07:59:36.728Z',mode:absolute,to:'2019-05-26T08:05:36.728Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/46bfb33b983710043711bda10d158f194b1eb58a

**Comment by kcopas** [comment]
New build coming? Still seeing the same behaviour here. 

I can work around but got excited that it might be fixed—it would help me with one screenshot series!

**Comment by kcopas** [comment]
working now—thx
