### ISSUE TITLE
Make well known scientificNameID and taxonID clickable

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#199]
**Make well known scientificNameID and taxonID clickable**

IPNI, IndexFungorum and ZooBank provide stable scientificNameIDs that people sometimes use both in occurrences and checklist taxa. We should make resolve these as real links.

In addition BOLD BIN numbers get used as taxonID and can be resolved in a similar ways

**LSIDs**
LSIDs are used for name ids often. These take up the form: 
urn:lsid:{authority}:{ID}:{VERSION}

In general the urn: prefix might be omitted and the version suffix is optional

**IndexFungorum**
urn:lsid:indexfungorum.org:names:{ID}
=> http://www.indexfungorum.org/names/NamesRecord.asp?RecordID={ID}

urn:lsid:indexfungorum.org:names:500733
=> http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=500733

Example https://demo.gbif.org/occurrence/1413593063

**IPNI**
with a version given:
urn:lsid:ipni.org:names:{ID}:{VERSION}
=> http://www.ipni.org/ipni/plantNameByVersion.do?id={ID}&version={VERSION}

without the version:
urn:lsid:ipni.org:names:60468511-2:{ID}
=> http://www.ipni.org/ipni/idPlantNameSearch.do?id={ID}

urn:lsid:ipni.org:names:60468511-2:1.1
=> http://www.ipni.org/ipni/plantNameByVersion.do?id=60468511-2&version=1.1

**ZooBank**
urn:lsid:zoobank.org:act:{ID}
=> http://zoobank.org/NomenclaturalActs/{ID}

urn:lsid:zoobank.org:act:8BDC0735-FEA4-4298-83FA-D04F67C3FBEC
=> http://zoobank.org/NomenclaturalActs/8BDC0735-FEA4-4298-83FA-D04F67C3FBEC

**BOLD**
uses [Barcode Index Numbers - BINs](http://www.boldsystems.org/index.php/resources/handbook?chapter=2_databases.html&section=bins) and [PLOS article](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0066213)

BOLD:{ID}
=> http://www.boldsystems.org/index.php/Public_BarcodeCluster?clusteruri=BOLD:{ID}

BOLD:AAA9206
=> http://www.boldsystems.org/index.php/Public_BarcodeCluster?clusteruri=BOLD:AAA9206

-----
fbitem-occurrence1413593063

System: Chrome 58.0.3029 / Mac OS X 10.12.5
Referer: https://demo.gbif.org/occurrence/1413593063
Window size: width 1665 - height 839
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-01T09:11:26.029Z',mode:absolute,to:'2017-06-01T09:17:26.029Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-01T09:11:26.029Z',mode:absolute,to:'2017-06-01T09:17:26.029Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 84d26682-f762-11e1-a439-00145eb45e9a
publishingOrgKey: ccc2e3ec-98ba-4e74-878d-7dcf0f57baba

**Comment by MattBlissett** [comment]
Is that the resurrection of LSIDs? :)

When I looked for TDWG, many LSID resolvers were broken. If it's just for the few nomenclators, then skipping the proper resolution would be faster and more reliable.

For example, IPNI will accept a URL like http://ipni.org/urn:lsid:ipni.org:names:1234-1.

**Comment by timrobertson100** [comment]
We should at least make LSID linkable prefixing them with the resolver:
  http://www.lsid.info/urn:lsid:ipni.org:names:77145066-1:1.4

**Comment by mdoering** [comment]
But afaik most LSIDs do not resolve. IPNI works, thats good news, but these not:
http://www.lsid.info/urn:lsid:zoobank.org:act:8BDC0735-FEA4-4298-83FA-D04F67C3FBEC
http://www.lsid.info/urn:lsid:indexfungorum.org:names:500733

I'd suggest to use direct resolutions for those 4 kind of ids instead.
For IPNI probably the link Matt gave, I did not know that one:
http://ipni.org/urn:lsid:ipni.org:names:1234-1

**Comment by MattBlissett** [comment]
The http://ipni.org/urn:lsid:ipni.org:names:1234-1 link is the way IPNI would like to be linked and cited, the plantNameVersionById stuff is ugly.

**Comment by MattBlissett** [comment]
See http://wiki.pro-ibiosphere.eu/wiki/Best_practices_for_stable_URIs for IPNI saying they prefer this structure.

**Comment by timrobertson100** [comment]
Given that only IPNI actually work and they prefer not to use them I propose we don't promote LSIDs but rather rewrite the links for ipni, indexfungorum zoobank etc.

e.g. http://www.lsid.info/urn:lsid:indexfungorum.org:names:329735 could be a link to http://www.indexfungorum.org/names/namesrecord.asp?RecordID=329735 without confusing everyone or promoting further broken identifiers.

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/460
