### ISSUE TITLE
OccurrenceID search doesn't return results

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#200]
**OccurrenceID search doesn&#39;t return results**

Copying the occurrenceID from this record:
  https://demo.gbif.org/occurrence/575175144

Does not return results when you add it to an occurrence search:

https://demo.gbif.org/occurrence/search?dataset_key=bf2a4bf0-5f31-11de-b67e-b8a03c50a862&amp;occurrence_id=http:%2F%2Fdata.rbge.org.uk%2Fherb%2Fe00070244&amp;taxon_key=3097538&amp;advanced=1

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482

System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/occurrence/search?dataset_key=bf2a4bf0-5f31-11de-b67e-b8a03c50a862&occurrence_id=http:%2F%2Fdata.rbge.org.uk%2Fherb%2Fe00070244&taxon_key=3097538&advanced=1
Window size: width 1344 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-03T20:10:29.214Z',mode:absolute,to:'2017-06-03T20:16:29.214Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-03T20:10:29.214Z',mode:absolute,to:'2017-06-03T20:16:29.214Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thanks for reporting

This looks like an API issue and is same behaviour as the current production site:

Current site: http://www.gbif.org/occurrence/search?ORGANISM_ID=http%3A%2F%2Fdata.rbge.org.uk%2Fherb%2FE00070244

no results for 
not encoded http://api.gbif.org/v1/occurrence/search?occurrence_id=http://data.rbge.org.uk/herb/e00070244

no results for encoded http://api.gbif.org/v1/occurrence/search?occurrence_id=http%3A%2F%2Fdata.rbge.org.uk%2Fherb%2Fe00070244

but the occurrence is in SOLR
https://demo.gbif.org/occurrence/search?q=e00070244&basis_of_record=PRESERVED_SPECIMEN&country=CL&taxon_key=3097538

Occurrence: https://demo.gbif.org/occurrence/575175144

**Comment by dgasl** [comment]
Hi. The above referenced duplicated issue was mine (for some reason my login info was not reported; perhaps I started writing the issue before I logged).

[https://github.com/gbif/portal-feedback/issues/235](https://github.com/gbif/portal-feedback/issues/235)

But I have to say the behaviour is not the same. In my case, the API works well:
http://api.gbif.org/v1/occurrence/search?occurrence_id=SANT:SANT-Lich:8850-B

**Comment by MortenHofft** [comment]
@dgasl I see that it is an issue of casing - looks like the api and front end don't agree on wether case is important and varies per field. I'll look into it. Thank you for reporting

As for the login info, that is to be expected (and leaving feedback without contact info is just fine btw). We have deliberately left the option to the user to provide contact details, but the idea is to have the option to set a default (e.g. your github handle). But that we haven't implemented yet

**Comment by MortenHofft** [comment]
> no results for encoded http://api.gbif.org/v1/occurrence/search?occurrence_id=http%3A%2F%2Fdata.rbge.org.uk%2Fherb%2Fe00070244

The e is lowercased following the procedure for other fields. This is not how the API works. Seems reasonable that ids are case sensitive, so the front end should reflect that.
This works: http://api.gbif.org/v1/occurrence/search?occurrence_id=http%3A%2F%2Fdata.rbge.org.uk%2Fherb%2FE00070244
