### ISSUE TITLE
Missing decimalLatitude and longitude in the interpreted columns

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#201]
**Missing decimalLatitude and longitude in the interpreted columns**

The verbatim values are shown but I think this might be missing labels showing the interpreted latitude/longitude

-----
fbitem-occurrence142728753
Reported by: timrobertson100@gmail.com
System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/occurrence/142728753
Window size: width 1344 - height 755
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-06T21:17:36.959Z',mode:absolute,to:'2017-06-06T21:23:36.959Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-06T21:17:36.959Z',mode:absolute,to:'2017-06-06T21:23:36.959Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 83422c44-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 12308e00-4b80-11da-8809-b8a03c50a862

**Comment by MortenHofft** [comment]
Hi Tim - thanks
should be fixed by https://github.com/gbif/portal16/commit/0afd02f7fbf68f0b1167d7edc89464048c8920e0
