### ISSUE TITLE
How to register hybrids in botanical datasets?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2013]
**How to register hybrids in botanical datasets?**

Are there recommendations in the way how hybrids should be  recorded?  And which fields should be used to indicate that the record concerns a hybrid?

Here are two examples in the dataset dd6ef36f-3345-4c9e-9188-161de0668127:
Begonia elatostemmoides Hook.f. × minutifolia N.Hallé
Begonia macrocarpa Warb. × sessilifolia Hook.f.

-----

User provided contact info: @jeroen
System: Chrome 74.0.3729 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/54215b10c59d5066866b468114760fa7:870009f3a64e7a71afac9c35faa268b10c65acdf852c190eed61de5a52f319fed910a020a97afb1f1ae4399f541bcbff1fb7d1d80e262c81ae3de49e44422f4f)
Referer: https://www.gbif.org/
Window size: width 1707 - height 760
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-28T20:09:04.949Z',mode:absolute,to:'2019-05-28T20:15:04.949Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-28T20:09:04.949Z',mode:absolute,to:'2019-05-28T20:15:04.949Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
As far as I know, we don't have any specific recommendation on the way hybrids should be recorded. Having `Begonia elatostemmoides Hook.f. × minutifolia N.Hallé` in the the `scientificName` field seem valid. Perhaps @mdoering has some thoughts on the topic?

**Comment by mdoering** [comment]
Yes, simply place the full hybrid formula into the scientificName field.
We do not keep hybrids in our backbone and thus wont be able to match them, but they are searchable on their raw name and linked to their higher classification

**Comment by ahahn-gbif** [comment]
This thread appears to be closed. @jeroen: could you re-open, please, if this did not answer your request?
