### ISSUE TITLE
Dekkera bruxellensis subsp. van der Walt

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2014]
**Dekkera bruxellensis subsp. van der Walt**

`https://www.gbif.org/species/9721154:` `Dekkera bruxellensis subsp. van der Walt` seems like an incorrectly parsed name. `van der Walt, 1964` should be the other of the SPECIES `Dekkera bruxellensis`

-----

User provided contact info: @peterdesmet
System: Chrome 74.0.3729 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/c13f0ce372560174c5f7504d13f4200b:e8906e95413b6aafab95439197063a49ae5a67f7a6c93e3562cb464c7cd6f726415abcbaf29249b2657a6506bc9b8428e14d821ad519e8295c2c57e7b408f35f)
Referer: https://www.gbif.org/species/9721154
Window size: width 1197 - height 717
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-29T07:17:02.765Z',mode:absolute,to:'2019-05-29T07:23:02.765Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-29T07:17:02.765Z',mode:absolute,to:'2019-05-29T07:23:02.765Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
The taxon name now shows as deleted and is no longer available to searches or occurrence matching. The originating resource (GBIF Type Specimen Names) has been withdrawn from the backbone generation process earlier this year. Closing.
