### ISSUE TITLE
Kluyveromyces marxianus subsp. der Walt, 1971

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2015]
**Kluyveromyces marxianus subsp. der Walt, 1971**

This taxon seems suspected. Probably an error in parsing names? The authorship should be referred to the species [`Kluyveromyces marxianus`](`https://www.gbif.org/species/9661694).` Could you please check?

-----

User provided contact info: @damianooldoni
System: Chrome 74.0.3729 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/c1ffe78846990c1f4451a587a62741de:844dad304400a2fcb8c41b0c78011c5233e4029a2b09bc1615d3782954b885ca503ea0ce1568cc324664e3253290c957ae363a630566b88207cbaf81b0676c63)
Referer: https://www.gbif.org/species/9661694
Window size: width 1366 - height 635
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-29T07:52:16.485Z',mode:absolute,to:'2019-05-29T07:58:16.485Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-29T07:52:16.485Z',mode:absolute,to:'2019-05-29T07:58:16.485Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This issue is solved in the newest taxonomy.
