### ISSUE TITLE
8359307 typo

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2020]
**8359307 typo**

The spider Pinkfloydia harveyi should be spelled Pinkfloydia harveii as in Dimitrov &Hormiga's 2011 paper.

-----

User provided contact info: kim@questagame.com
System: Chrome 74.0.3729 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/bba59ea93c4d3435df1f1302248b86a6:241a2b3eaa11637baa76bace4a258d663380916d95ca6840c4c34620ecb4351aa777b8bb6787d6c0a72e43fd1c0c1d5266da0c0a7414e0c9e1cdd5976ba3fd21)
Referer: https://www.gbif.org/species/8359307
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-29T17:26:59.491Z',mode:absolute,to:'2019-05-29T17:32:59.491Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-29T17:26:59.491Z',mode:absolute,to:'2019-05-29T17:32:59.491Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by yroskov** [comment]
Comment sent to the World Spider Catalog.

**Comment by ManonGros** [comment]
Reply from WSC:
> Thanks for forwarding the issue. Please see the comment at https://wsc.nmbe.ch/species/36676
"The species epithet is a patronym after the Australian arachnologist Mark S. Harvey"; lapsus calami, cf. ICZN Article 32.5.1. - there is no note that the authors intended to latinize"
According to Theo Blick from the WSC Board, there is no need to correct the specific epithet.
Best regards, Daniel
