### ISSUE TITLE
Update in metadata not reflected on gbif.org

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2022]
**Update in metadata not reflected on gbif.org**

I've republished `https://ipt.inbo.be/resource?r=dagvlinders-natuurpunt-occurrences` to v1.8 to make a requested change in the metadata: using the term `new-native` in the [taxonomic coverage](`https://ipt.inbo.be/resource?r=dagvlinders-natuurpunt-occurrences#taxanomic).`

That change is not reflected in the dataset on GBIF: `https://www.gbif.org/dataset/1f968e89-ca96-4065-91a5-4858e736b5aa#taxonomicCoverages.` Even if I click `Ingest now` the metadata doesn't seem to be updated.

-----

User provided contact info: @peterdesmet
System: Chrome 74.0.3729 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/6e7bbdd71445025349834f666a8371bf:1eef36716b4c75ba88f5a09c76d21a054c8840d0896d86fde9570147272bed1f3d3f7981ce42cebb223d6743f1da83e84dda115a844f539b22e9265eac170066)
Referer: https://www.gbif.org/dataset/1f968e89-ca96-4065-91a5-4858e736b5aa
Window size: width 1273 - height 717
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-29T19:41:45.159Z',mode:absolute,to:'2019-05-29T19:47:45.159Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-29T19:41:45.159Z',mode:absolute,to:'2019-05-29T19:47:45.159Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The APIs do not reflect the change
https://api.gbif.org/v1/dataset/1f968e89-ca96-4065-91a5-4858e736b5aa
https://api.gbif.org/v1/dataset/1f968e89-ca96-4065-91a5-4858e736b5aa/document

**Comment by peterdesmet** [comment]
I've republished the dataset (1.9), did an `ingest now` and the issue is now resolved: https://www.gbif.org/dataset/1f968e89-ca96-4065-91a5-4858e736b5aa#taxonomicCoverages 🤷‍♂ Can be closed.
