### ISSUE TITLE
UMMZ Collections-Specific Epithets Not Displayed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2023]
**UMMZ Collections-Specific Epithets Not Displayed**

To Whom It May Concern:

We are working with the GBIF API to connect the UMMZ collection records to an in-house CT data repository.  However, it does not appear that the specific epithets are showing up for all UMMZ records, which is limiting our ingestion of taxonomic information with our data entries.  These data are found in our collection databases and are being made available via the University of Michigan IPT.  Does GBIF's process remove specific epithets if the records do not comply with the backbone taxonomy?  Are there other reasons that might restrict this information?

Thanks,
Cody

-----

User provided contact info: cwthomp@umich.edu
System: Safari 12.1.1 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/81408cb3f1426465ed9181f06f3c7fe5:daf65499e6b3155f6da2c2f9f7cab4ca97bc6242858304c11751df94f0483254d4f9f2ef26d98619ccc2620ae8f7ae498a4737e6ecc977511a587cd43e81d8de)
Referer: https://www.gbif.org/user/profile
Window size: width 1274 - height 1281
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-30T15:41:47.518Z',mode:absolute,to:'2019-05-30T15:47:47.518Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-30T15:41:47.518Z',mode:absolute,to:'2019-05-30T15:47:47.518Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> You are correct, GBIF removes specific epithet if no match can be found in the backbone taxonomy. The system then matches it to the higher taxon rank available and labels the record with the flag “TAXON_MATCH_HIGHERRANK”.
That being said, the original verbatim name is still available. If you are using the API, all you need to do is add “/verbatim” to your call.
For example, for [this occurrence](https://www.gbif.org/occurrence/1987277891), the interpreted data is available with https://api.gbif.org/v1/occurrence/1987277891, while the verbatim data can be access with https://api.gbif.org/v1/occurrence/1987277891/verbatim.
As far as I am aware, there isn’t any other reason for restricting this information.
If you notice any missing taxon, please leave us a feedback message on GitHub.
