### ISSUE TITLE
Images preserved specimens show living animals

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2026]
**Images preserved specimens show living animals**

From an user in need of images of preserved specimens I received the following query results mainly showing living animals and catalogue images. Is this a bug?

`https://www.gbif.org/occurrence/gallery?basis_of_record=PRESERVED_SPECIMEN&taxon_key=785`
`https://www.gbif.org/occurrence/gallery?basis_of_record=PRESERVED_SPECIMEN&taxon_key=729`
`https://www.gbif.org/occurrence/gallery?basis_of_record=PRESERVED_SPECIMEN&publishing_org=19456090-b49a-11d8-abeb-b8a03c50a862&taxon_key=732`

-----

User provided contact info: nlbif@naturalis.nl
System: Chrome 74.0.3729 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/7c611b34a28303a7d576cdb568d9b679:fc143ac421de5be6aee3d86c1302eb0497662b9038576a4dbb181acc48492f4b69ec54dce4c8d49c2d9c9ac98ac2a745ed2a6254e7ba4a267fc7a75f5f436325)
Referer: https://www.gbif.org/occurrence/gallery?basis_of_record=PRESERVED_SPECIMEN&taxon_key=785
Window size: width 1536 - height 682
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-04T10:59:51.606Z',mode:absolute,to:'2019-06-04T11:05:51.606Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-04T10:59:51.606Z',mode:absolute,to:'2019-06-04T11:05:51.606Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.
