### ISSUE TITLE
Plant classified as Animal in PLAZI checklist

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#2028]
We received the following feedback on Helpdesk:
> The link below shows the classification of Dracaena as an animal rather than a plant. The text below the classification refers to Dracaena as a genus in the plant kingdom.
https://www.gbif.org/species/119636544/verbatim

@myrmoteras @gsautter, this is a PLAZI checklist. The title of the article mentions a genus of Lepidoptera but it seems that the content is about its food (an Asparagaceae). The result is a plant classified as an Animal (but a reptile for some reason).

**Comment by myrmoteras** [comment]
thanks for pointing this out. Should be fixed now. It is indeed the food plant of leps

**Comment by ManonGros** [comment]
Perfect, thanks!
