### ISSUE TITLE
Project id link: lead to project page in the related program?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#203]
**Project id link: lead to project page in the related program?**

The link behind the project id currently links to a filter in the section of, e.g., https://demo.gbif.org/resource?q=BID-AF2015-0065-NAC&amp;contentType=project. This filter is currently empty.

 It would be much better if it could instead go to the project page in the context of the financing program, https://demo.gbif.org/project/82741/capacity-building-and-biodiversity-data-mobilization-to-address-health-and-food-security-priorities-in-benin, which is otherwise very difficult to impossible to identify for a user, if they do not know where to start the search.

-----
fbitem-dataset9cc68a7f-df2d-49d6-b797-94c99a2cafe8
Reported by: @ahahn-gbif
System: Firefox 53.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/dataset/9cc68a7f-df2d-49d6-b797-94c99a2cafe8/project
Window size: width 1270 - height 614
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-07T07:16:29.588Z',mode:absolute,to:'2017-06-07T07:22:29.588Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-07T07:16:29.588Z',mode:absolute,to:'2017-06-07T07:22:29.588Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi Andrea, my bad. should be partially fixed with: https://github.com/gbif/portal16/commit/97f0357c3b1034f7d689944469a8c2a24044ef19

it wont link directly to the project. i see that makes sense, but it requires a bit more. so for now i simply link to the search result. BUT now with a working result. Sorry about that
