### ISSUE TITLE
Link displayed in IPT broken - https://www.gbif.org/terms/licences/data-sharing

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#2030]
We received a comment on Helpdesk that the link https://www.gbif.org/terms/licences/data-sharing, displayed in the IPT Version 2.3.6 is broken.
I guess we cannot easily change that in the IPT but perhaps we can redirect the users to an other page, https://www.gbif.org/news/82363/new-approaches-to-data-licensing-and-endorsement for example?

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/gbif-configuration/commit/e4b642a51138d8f2b53fc22a7bc4d6ef81138b5b
