### ISSUE TITLE
Species occurrences mismatch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2031]
**Species occurrences mismatch**

Hoplobatrachus tigerinus is an African/Asian species; the name and the occurrences (many of them in south america) are a mismatch.

You can check this by looking at one of your own sources: `https://www.gbif.org/species/102077442`
`https://www.gbif.org/species/110873212`

The species name originally assigned for the south american occurrences is Bufo typhonius.

This is probably a problem of an erroneous synonym assignation at your backbone.

-----

User provided contact info: @camiplata @sibcolombia
System: Chrome 74.0.3729 / Mac OS X 10.11.6
User: [See in registry](https://www.gbif.org/api/feedback/user/f36df93912ed6a4c4895a4555fb94f8c:bb48f2780d4cadaefc33941b124d6ebb72eab5e24bd1429f95af6d30194ade7a6b75ee77e561d69f6b97dd3e47648830ae7834e14b0508800dd4cbbe9a52d03f)
Referer: https://www.gbif.org/species/2430380
Window size: width 1155 - height 629
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-09T21:46:36.435Z',mode:absolute,to:'2019-06-09T21:52:36.435Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-09T21:46:36.435Z',mode:absolute,to:'2019-06-09T21:52:36.435Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by yroskov** [comment]
Obsolete data in CoL. ITIS dataset should be updated in CoL.

**Comment by ManonGros** [comment]
Bufo typhonius and Hoplobatrachus tigerinus are distinct species in the new backbone. All the south American occurrences of Hoplobatrachus tigerinus have the scientific name "Hoplobatrachus tigerinus": https://www.gbif.org/occurrence/search?continent=SOUTH_AMERICA&taxon_key=2430380
