### ISSUE TITLE
Downloads being killed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2032]
**Downloads being killed**

Hey there! 

My occ_download requests are failing, and I'm not sure what's up. At first I thought something was wrong with the wkt I was using with the 'geometry' parameter, or that I was making a request for too many species. However, I just tried one of Scott Chamberlain's example download requests (with one taxon record), and that request was killed also. 

My username, password and email are stored as R environment variables, and I'm receiving emails that my requests failed, so seems like things are communicating on that end. My code for this project is on GitHub, but I haven't opened an issue for this since it seems like it might be an issue with my account. 

Any ideas or help would be much appreciated!
Thanks in advance,
Julie

-----

User provided contact info: @j-galloway
System: Chrome 74.0.3729 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/d4a2bd6f7379966c25bde0c6fe11d499:420c6788d30c4c840f01c50fe082cf042f9490e75e0d15a2dfb32033e4351eb14e2156a3711025a7013474c1bc0929ac8d48aaa42aaa677f8db52554e0bb5596)
Referer: https://www.gbif.org/occurrence/download/0026780-190415153152247
Window size: width 1440 - height 717
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-09T21:52:09.668Z',mode:absolute,to:'2019-06-09T21:58:09.668Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-09T21:52:09.668Z',mode:absolute,to:'2019-06-09T21:58:09.668Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thank you for your feedback.

The polygons are winded clockwise. That is stating the the geometry is a hole. We don't support that as an outer ring. I see that you have many failed downloads, the ones I checked where all clockwise.

So there are 2 issues:
1) the query is invalid. You should wind the polygon counter clockwise.
2) The API shouldn't accept the request if it won't work. I will label this an API issue.

Hope that helps.

> However, I just tried one of Scott Chamberlain's example download requests (with one taxon record), and that request was killed also.

@sckott if I read that correct (as an example with an invalid clockwise WKT), there might be an unfortunate example in the documentation. I looked but couldn't find it.

**Comment by sckott** [comment]
thanks for the ping @MortenHofft 

I've just fixed all the clockwise WKT to counter-clockwise throughout the documentation in rgbif

**Comment by j-galloway** [comment]
Thanks so much for your help, @MortenHofft and @sckott ! Rookie mistake - no wonder the requests were failing. I'll have to do some digging to see if there's a way to specify winding order when converting an sf to wkt using st_as_text...by default, they're returned in clockwise order.

**Comment by sckott** [comment]
I have a dev branch of the [wicket pkg](https://github.com/ropensci/wicket/) that has a fxn to reverse winding order, 

```r
remotes::install_github("ropensci/wicket@reverse")
library(wicket)
wkt_reverse("POLYGON((42 -26,42 -13,52 -13,52 -26,42 -26))")
```

**Comment by j-galloway** [comment]
Thanks @sckott , I'll check that out! I have a bunch of wkts that are mapped to a list, so I'm glad that function exists.

**Comment by timrobertson100** [comment]
can we close this issue please @j-galloway ?

**Comment by j-galloway** [comment]
@timrobertson100 Yep! Thanks :)
