### ISSUE TITLE
How to get occurrences using a list of scientific names as opposed to entering names one at a time to the user interface?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2033]
**How to get occurrences using a list of scientific names as opposed to entering names one at a time to the user interface?**

-----

User provided contact info: bob.branton@gmail.com
System: Chrome 74.0.3729 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/bce2980d63601b351729a9201a78fc8a:234cef1ce28a4b2a27e9bd61a61cad9fcb36a5bee28b4480271b303e2d6649b999f902c68d3715f23b154e60952a8d9953bca71ecec2aa2030aac080ca132a85)
Referer: https://www.gbif.org/
Window size: width 1280 - height 529
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-09T22:05:05.775Z',mode:absolute,to:'2019-06-09T22:11:05.775Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-09T22:05:05.775Z',mode:absolute,to:'2019-06-09T22:11:05.775Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
To do so you should use[ our API](https://www.gbif.org/developer/occurrence)s or the community created [rgbif](https://cran.r-project.org/web/packages/rgbif/index.html).

First you need to match your names to a taxonID (using the `/species/match` endpoint), secondly you can do a query the occurrence API, for those IDs. If you have hundreds of IDs, you need to split it into multiple downloads.

Hope that helps
