### ISSUE TITLE
Mistranscribed recorder in three records from NHM (London)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2034]
**Mistranscribed recorder in three records from NHM (London)**

This occurrence and two others incorrectly transcribe the specimen recorder as 'Meriwether Lewis'. Not sure how this happened, as the image accompanying two of the three clearly identifies 'Marko Lewis' as the recorder.

See also:
https://www.gbif.org/occurrence/1135482456
https://www.gbif.org/occurrence/1135485823

-----

User provided contact info: @kcopas
System: Safari 12.1.1 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/a2d11ab2636a1655c5c083cbf5cf6da2:a17760dedb1d3059477184a1f6dba34c7cffa69c3840bd9b29be4c97a5bd4fe83671e38d350db0365cfaa73d1680dd91693a8814dca33e28d28cac6b4c0e5a3c)
Referer: https://www.gbif.org/occurrence/1135482428
Window size: width 1523 - height 929
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-10T12:25:27.461Z',mode:absolute,to:'2019-06-10T12:31:27.461Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-10T12:25:27.461Z',mode:absolute,to:'2019-06-10T12:31:27.461Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Publishers notified by email.
