### ISSUE TITLE
Hide link to deleted installation

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2038]
**Hide link to deleted installation**

This installation is now deleted (`https://www.gbif.org/installation/603f8066-f762-11e1-a439-00145eb45e9a)` following a request from the publishers. However, the link to the installation is still visible from the organization page.
It might be a good idea to remove/hide that link once an organization is deleted.

-----

User provided contact info: @ManonGros
System: Safari 12.1.1 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/e420151187b2ad1db901b7e6e72aec6a:1e97e6b8e43ead1fb4b7a5d130f72f33af2cf17e51864173ed5d1298d967245a72104ba4deff71a89cac84d81719297dbd9b63d8eaa41a9d6df4514f8b181618)
Referer: https://www.gbif.org/publisher/1354d651-e529-4a8e-95be-faa807639461
Window size: width 1780 - height 691
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-11T11:51:44.136Z',mode:absolute,to:'2019-06-11T11:57:44.136Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-11T11:51:44.136Z',mode:absolute,to:'2019-06-11T11:57:44.136Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I do not see any link to the installation from the publisher page. 

Either way, I would think that if the publisher is referencing an installation that is deleted, then it should show. So that it can be cleaned up in the data. But perhaps I'm misunderstanding?

**Comment by ManonGros** [comment]
I am confused, yesterday the link was there but not any more. I guess the issue is solved then.
