### ISSUE TITLE
New dataset name = publisher name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2039]
**New dataset name = publisher name**

The new dataset from CU MNH seems very poorly named, given that, with the exception of a comma, it's exactly the same as the [publisher](https://www.gbif.org/publisher/4cadac10-3e7b-11d9-8439-b8a03c50a862). This might not be a problem if there weren't already [9 other datasets](https://www.gbif.org/dataset/search?publishing_org=4cadac10-3e7b-11d9-8439-b8a03c50a862)

The description makes it clear that it's the bryophyte collection from the herbarium. The dataset name would probably be more helpful if it reflected that.

-----

User provided contact info: @kcopas
System: Safari 12.1.1 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/3ce821f4722809c7fa091a3471601262:63a8825d01871ed0b8be86e744af4e084476119241282da5679a1fcca12d38e1854b8702b88295df4efe59025615d943b88a86751b57eca6193923d263fc42c9)
Referer: https://www.gbif.org/dataset/72d3505f-70c4-4743-a872-7f8010498fb9
Window size: width 2063 - height 1233
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-11T14:14:15.458Z',mode:absolute,to:'2019-06-11T14:20:15.458Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-11T14:14:15.458Z',mode:absolute,to:'2019-06-11T14:20:15.458Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by timrobertson100** [comment]
Now shows:

University of Colorado, Museum of Natural History Bryophyte Collection
Published by University of Colorado Museum of Natural History 

@kcopas - can be closed?
