### ISSUE TITLE
Suggestion: Add synchronisation state to installation page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#204]
**Suggestion: Add synchronisation state to installation page**

It would be immensely useful for data managers to be able to get an overview of the synchronization state of datasets in GBIF.  The IPT is one of the most promoted tools and offers an inventory API such as [this one from Canadensys](http://data.canadensys.net/ipt/inventory/dataset).

This API could be used to easily show a table summarising if the expected count is available in GBIF.  

Recognising this is targeting a specialist audience, it might be suitable for e.g. a new tab called &quot;Registrations&quot; or &quot;Synchronisation&quot; or similar.

Not all IPTs support this and there is a [known issue](https://github.com/gbif/ipt/issues/1344) in the IPT, so it would need to degrade nicely. 

This would replace the ad hoc consoles we have developed for this purpose such as [this VertNet demo](http://timrobertson100.github.io/vertnet-gbif-diagnostic/target/index.html)

-----
fbitem-2747b19311481a03744a6234de7fb361822e957a
Reported by: @timrobertson100
System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/installation/7c519b4c-1100-4f39-a95a-9b679b4542e4
Window size: width 1552 - height 938
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-07T11:47:42.881Z',mode:absolute,to:'2017-06-07T11:53:42.881Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-07T11:47:42.881Z',mode:absolute,to:'2017-06-07T11:53:42.881Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
A great idea. Of course the IPT needs to be online to get an up-to-date inventory response. Otherwise if the IPT is offline, the proposed synchronisation tab should show the IPT is offline in my opinion. Tracking each installation's uptime would be a nice complimentary feature, that would be especially useful explaining why things are 'out-of-sync'. 

During the last webinar, several Nodes expressed that they would even like to receive email notifications when their installations go offline. Uptime tracking would allow us to do this, and ensure the content in GBIF.org remains accessible online more consistently. Thanks.

**Comment by timrobertson100** [comment]
A solution to this is [demonstrated on this plnkr](http://embed.plnkr.co/shQMHYpnpZX9V6xo5xgx/) and attached as `.txt` file (GH does not allow `.html` files).

[index.txt](https://github.com/gbif/portal-feedback/files/1062161/index.txt)

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/448
