### ISSUE TITLE
link to project

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2042]
**link to project**

Please link this event to this project `https://www.gbif.org/project/6KNJbZiFijpWCogLRqxZum/mobilization-of-biodiversity-data-on-soil-mesofauna-across-european-russia-biomes`

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5134325fa4730b364d2606c39e3b7bb2:43026b2fddf5e5982c31115fdf6ef444106e2e311840d5240531c277335bcd58bc4540f65d3fef5ea9c25e111d0b2a76980606a5e582cf90206230bea2cbd88b)
Referer: https://www.gbif.org/event/77COVkAP0GNzUzhmQrzM0W/diversity-of-soil-animals-publication-and-effective-use-of-primary-data
Window size: width 1536 - height 769
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-13T08:39:44.836Z',mode:absolute,to:'2019-06-13T08:45:44.836Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-13T08:39:44.836Z',mode:absolute,to:'2019-06-13T08:45:44.836Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Done.
