### ISSUE TITLE
Teucrium chamaedrys subsp. germanicum (F.Herm.) Rech.f. not matched to Backbone

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2044]
**Teucrium chamaedrys subsp. germanicum (F.Herm.) Rech.f. not matched to Backbone**

While trying to match this taxon (`https://www.gbif.org/species/6096561)` to GBIF Backbone I get no match. Reason: `No match because of too little confidence`. However, it is exactly the scientific name as it appears in the API: `http://api.gbif.org/v1/species/6096561.`

-----

User provided contact info: @damianooldoni
System: Chrome 74.0.3729 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/e4a0f98ea64a28f6c42e467511cf9330:0644cee51c7f447f3beb40f6d0c7fe0779216c9f78afec769c8f88ac2e94cce3118802be085c0a086da23c875968662809cc9a9927da32404341383441d80d3f)
Referer: https://www.gbif.org/species/6096561
Window size: width 1366 - height 635
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-13T10:20:49.510Z',mode:absolute,to:'2019-06-13T10:26:49.510Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-13T10:20:49.510Z',mode:absolute,to:'2019-06-13T10:26:49.510Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thank you for reporting it, but I'm unable to reproduce it.

Scientific name from http://api.gbif.org/v1/species/6096561 is `Teucrium chamaedrys subsp. germanicum (F.Herm.) Rech.f.`
Match API returns [one result](http://api.gbif.org/v1/species/match?name=Teucrium%20chamaedrys%20subsp.%20germanicum%20(F.Herm.)%20Rech.f.) for this query

Let us know if you believe something is wrong with either API or documentation.

Thanks
