### ISSUE TITLE
KBIF IPT ingestions failing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2045]
**KBIF IPT ingestions failing**

All KBIF IPT ingestions are failing.

This is because the TLS (secure/HTTPS) configuration for the server is incomplete, see `https://www.ssllabs.com/ssltest/analyze.html?d=www.kbif.go.kr&hideResults=on` for example.

The fix needed to make it work with tools like Java is the incomplete certificate chain.

-----

User provided contact info: @MattBlissett
System: Firefox 66.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/6f1b224fd33cc87c4a17227c5015d0ef:2509eae9366ed5c6638e83caf1efa21745a56cf87528beb29edcbf35647fbecc7f491176637881e8eb77316212a27947515a4bd50dae7280228d8e406a55cb1c)
Referer: https://www.gbif.org/installation/9afa1395-6e93-4848-a42d-bce896f5195e
Window size: width 2560 - height 1266
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-13T15:14:40.700Z',mode:absolute,to:'2019-06-13T15:20:40.700Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-13T15:14:40.700Z',mode:absolute,to:'2019-06-13T15:20:40.700Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
https://www.securesign.kr/guides/Intermediate-Chain-Certificates has information in Korean about this problem.

I've applied a workaround (added the intermediate certificate to the local trust store).
