### ISSUE TITLE
Notification email address not listed on download page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2046]
**Notification email address not listed on download page**

Just started a download at `https://www.gbif.org/occurrence/download/0029336-190415153152247` It states: 

> The download has been started and is currently being processed.
> 
> Please expect up to 3 hours for the download to complete. Most downloads will complete within 15 minutes.
> 
> A notification email with a link to download the results will be sent to the following address once ready:

But no email address is listed.

-----

User provided contact info: @peterdesmet
System: Chrome 74.0.3729 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/732c60fdd176cc8ce8379858c1e35ce3:658fca57bb5be64495362934edc7d27e0cd37e603a5bb33678fce8d80a69e51f4df1e58f828471d098de3bef53f4145cdde68626719773f2245d3620c9c8ed6a)
Referer: https://www.gbif.org/occurrence/download/0029336-190415153152247
Window size: width 1354 - height 646
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-13T19:08:29.065Z',mode:absolute,to:'2019-06-13T19:14:29.065Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-13T19:08:29.065Z',mode:absolute,to:'2019-06-13T19:14:29.065Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The field is called something else in the API than what the website assumes. I'll update the website accordingly.

This has apparently changed at some point? Below examples at least indicates that it has been different in the recent past. A breaking change in the API?

[Past issue with response dump](https://github.com/gbif/gbif-configuration/issues/2)
I dont know freemarker well, but [this looks like a JSON with another name](https://github.com/gbif/portal-web/blob/eea21094d64b99979030cf33fe7c64b0d75c0fdc/src/main/webapp/WEB-INF/pages/occurrence/download.ftl#L35)

**Comment by MattBlissett** [comment]
Yes, this has been changed, presumably unintentionally. This is the commit: https://github.com/gbif/gbif-api/commit/d7c3dcf4c8a14841cc58bf7d43d50bcaa213dd45#diff-4f12148d337fefd6834e72d637582015

**Comment by MortenHofft** [comment]
Given that it is a breaking change, should we perhaps revert it?

**Comment by MattBlissett** [comment]
I've changed it back in gbif-api, we will coordinate changing the portal back to notification_addresses when that's included in the registry and released.

**Comment by MortenHofft** [comment]
> I've changed it back in gbif-api, we will coordinate changing the portal back to notification_addresses when that's included in the registry and released.

Let me know when this is to be changed on the website
