### ISSUE TITLE
12M single-dataset download contains 0 records

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2047]
**12M single-dataset download contains 0 records**

Steps:

1. Go to `https://www.gbif.org/dataset/e7cbb0ed-04c6-44ce-ac86-ebe49f4efb28`
2. Click download and initiate download for csv file of dataset
3. [Download](`https://www.gbif.org/occurrence/download/0029336-190415153152247)` is initiated
4. Download finishes quite quickly, resulting in a 3KB CSV file containing only headers and no data
5. The download page indicates `12,778,515 occurrences downloaded`

Two other users have reported the same issue on Twitter

- `https://twitter.com/maartenzam/status/1139241404998332423` [download](`https://www.gbif.org/occurrence/download/0029211-190415153152247)`
- `https://twitter.com/michelstuyts/status/1139245091237896192`

Note: at the time of downloading, the dataset was [being ingested](`https://registry.gbif.org/dataset/e7cbb0ed-04c6-44ce-ac86-ebe49f4efb28/process).` This ingestion was initiated by me to harvest v1.1 of the dataset (which contains content for the `datasetID` term).

-----

User provided contact info: @peterdesmet
System: Chrome 74.0.3729 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/c7105625aa23c044db552a15e5d35d7a:01c4baaa389430310627b2d9b186955eef30c31fb2ebc2306a0a35ce916d54a20a4c21d38a41115b3c639f299211713b62cab37f2896c5ca1cf69f7537b6df24)
Referer: https://www.gbif.org/occurrence/download/0029336-190415153152247
Window size: width 1354 - height 646
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-13T19:22:30.057Z',mode:absolute,to:'2019-06-13T19:28:30.057Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-13T19:22:30.057Z',mode:absolute,to:'2019-06-13T19:28:30.057Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by peterdesmet** [comment]
Reference to second download by maartenzam: https://www.gbif.org/occurrence/download/0029211-190415153152247

**Comment by MattBlissett** [comment]
GBIF's ingestion system is "eventually consistent", and the source database for large downloads is the slowest part to become consistent — it is regenerated nightly (European time). Until it is regenerated, the new/updated records won't be visible in large downloads.

Last night, the task finished at 22:34 UTC, so if you repeat this download request the records should be present.

**Comment by peterdesmet** [comment]
Good to know. So newly created datasets are only available for download the day after? 

The new download I trigger seems to contain the data (file size 561MB), but it is listed as 0 occurrences: https://www.gbif.org/occurrence/download/0029696-190415153152247

**Comment by peterdesmet** [comment]
Issue can be closed.
