### ISSUE TITLE
Contact person not indicated correctly

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2048]
**Contact person not indicated correctly**

For Natuurpunt dataset, the contact person is always Marc Herremans. For all except one dataset, the email icon is indicated for the first author instead. Can this be corrected?

Correct:

`https://www.gbif.org/dataset/8124cd73-ac84-43d2-ab39-1d80dc346525`

Incorrect:

`https://www.gbif.org/dataset/e7cbb0ed-04c6-44ce-ac86-ebe49f4efb28`
`https://www.gbif.org/dataset/bfc6fe18-77c7-4ede-a555-9207d60d1d86`
`https://www.gbif.org/dataset/7f5e4129-0717-428e-876a-464fbd5d9a47`
`https://www.gbif.org/dataset/9a0b66df-7535-4f28-9f4e-5bc11b8b096c`
`https://www.gbif.org/dataset/37e094f3-dcf2-469f-93a2-c4b9b5fa7275`
`https://www.gbif.org/dataset/958b1d2f-2d11-4e94-a828-c8e2d2c013ca`
`https://www.gbif.org/dataset/1f968e89-ca96-4065-91a5-4858e736b5aa`
`https://www.gbif.org/dataset/27e9e069-2862-4183-bcec-1e1a7f74d3e7`
`https://www.gbif.org/dataset/71cfd412-6327-4ec7-8035-d8b2d0509ac5`
`https://www.gbif.org/dataset/e7cbb0ed-04c6-44ce-ac86-ebe49f4efb28`

-----

User provided contact info: @peterdesmet
System: Chrome 75.0.3770 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/3f9fdc12e6b63428903e0f70820d1a2d:f06e868f17851329d5bce290a3979f26bce7dc0eb3b936f854772346d6f080fc32bfbd943c230ef1b4869a52e456ca072adccefc311878003f61d398776afe16)
Referer: https://www.gbif.org/health
Window size: width 1381 - height 705
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-14T07:55:50.200Z',mode:absolute,to:'2019-06-14T08:01:50.200Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-14T07:55:50.200Z',mode:absolute,to:'2019-06-14T08:01:50.200Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The website tries to create people (the API models roles, not persons). It then tries to decide who should be in the header, what order and whom should show as primary. It looks like a bug/oddity in that process.

**Comment by MortenHofft** [comment]
This functionality has since been removed. What was intended as a service was in reality a source of frustration. Now ordering comes from the API and match the citation string.
