### ISSUE TITLE
Explainer for citation

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#205]
**Explainer for citation**

1) Change cite to cites
2) I suggest we add something like this, after &quot;...known to GBIF.&quot; 
This is a list of research papers where at least one record from the dataset has contributed to the data download analyzed in the scientific publication.

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb
Reported by: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/resource/search?contentType=literature&gbifDatasetKey=50c9509d-22c7-4a22-a47d-8c48425ef4a7
Window size: width 1922 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-07T13:55:53.023Z',mode:absolute,to:'2017-06-07T14:01:53.023Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-07T13:55:53.023Z',mode:absolute,to:'2017-06-07T14:01:53.023Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
@dnoesgaard you are working on this text as far as I understand. I will remove until it is ready.
