### ISSUE TITLE
Feedback on iBOL dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2050]
**feedback**

This Twitter line should have some ideas on prefered fixes `https://twitter.com/dpsSpiders/status/1139539017379274752`

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/819bc9949f28f1e0c4f2b959f1a9871d:9ac740dbc9c2c9f27acdeee037234ef2b3aa6573944238581cd7b39b282c66456964565f2ab5e7e0f90ca0a9f3ce8f9b34ed3844fb1c3df8415d858358a1fae3)
Referer: https://www.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c
Window size: width 1922 - height 1073
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-15T16:51:48.227Z',mode:absolute,to:'2019-06-15T16:57:48.227Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-15T16:51:48.227Z',mode:absolute,to:'2019-06-15T16:57:48.227Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by timrobertson100** [comment]
The comments on twitter by @dshorthouse are completely valid and causing headache.

It was the case this was rushed out in preparation for the iBOL meeting this week, but as a quick fix these should probably be reduced to UNKNOWN type and removing the instititionCode value.

**Comment by dschigel** [comment]
Adding @thomasstjerne @dhobern as we will have a meeting on this (as a subtopic for the BOLD to GBIF dynamic connection) in a few hours.

**Comment by MattBlissett** [comment]
https://www.gbif.org/occurrence/1413980893

https://www.gbif-uat.org/occurrence/1413980893

Putting the BOLD id in brackets has meant it's stripped off (presumably as a basionym author?) during processing. (Unless something is different between the prod and UAT websites.)

The BasisOfRecord "Occurrence" is better than "Unknown".
