### ISSUE TITLE
Redundancy in the publisher reg form

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2051]
**Redundancy in the publisher reg form**

Optional organisational e-mail seems redundant as there is an obligatory contact e-mail is requested. These two, admin and tech contacts are not self-evident contact categories, and very oftern require clarification or corrections as we proceed (in the FSU).

-----

User provided contact info: @dschigel
System: Firefox 60.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4260f98a0db39ae4568fc753042c522f:1481ff333600719f2427825fdf20aacb6ed07e3b88f0c757e8ee80b36825f147132b2fdbeee6bc98bcd2063e7a846e4709b65159db1d2e4a8c01c767a10111cc)
Referer: https://www.gbif.org/become-a-publisher
Window size: width 1536 - height 737
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-15T21:08:46.524Z',mode:absolute,to:'2019-06-15T21:14:46.524Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-15T21:08:46.524Z',mode:absolute,to:'2019-06-15T21:14:46.524Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@jlegind you know better than I, as you specified the form.

But on the face of it, it makes sense to me to have both. People come and go so it might be nice to have an institutional mail address as well?

It is of course also the way the registry backend expects it, but that is not much of an explanation.

**Comment by ahahn-gbif** [comment]
They are two different things. The organizational email is located in the neighborhood of institution name, physical address, institution logo etc., and is an email for the _institution as a whole_, as an institution, just like the physical address. Where this does not exist or is not meaningful, it does not have to be provided, hence optional. 

The administrative and technical contacts are roles that lead to people who speak and act for the _institution as a data publisher_. They are required in procedures involving content aspects, including legal (e.g. consultation around licensing) and the institution's policy around data publishing and use (admin contact), and involving technical aspects (functional data endpoints, accessibility, role of a data host etc).

**Comment by dschigel** [comment]
I agree but suggest clearer labels:
Contact e-mail (organisational e-mail):
Administrative contact (personal e-mail):
Technical contact (personal e-mail):
It might be so that the current wording does not work in Slavic langugages, in such case I am happy to keep explaining the difference. It is a minor nice to have thing.

**Comment by ahahn-gbif** [comment]
Sorry, I was not clear enough:
- Email (Organization email e.g. secretariat@fibg-museum.org), as it is now: - this is _not_ a contact email in the sense of us sending routine mails to, or expecting to run any kind of communication through. It is the equivalent of the physical mail address in an address book. It can be the email that is printed in the footer / address field of the institutions site, for example. In the form, leave as-is. The fact that it is optional should be clear enough. When in doubt, leave it out (don't fill it).
- Administrative / technical contact: email. Again, leave as is. This is an email that the person or the role can be reached under, but that does _not_ mean that it has to be a personal email. It can very well be a functional one (e.g. collectionsmanagement@museum.org), as long as it has the right people behind it. Actually, we recommend that if a certain amount of staff turnover is to be expected. The important part here is an email address that reaches the right people to answer questions or make decisions that concern the institution as a data publisher, either on the administrative or the technical side.

**Comment by dschigel** [comment]
Thanks, clear
