### ISSUE TITLE
Record Number

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2055]
**Record Number**

Why can't record number be selected as a field to be displayed while searching for specific occurrences? I would like to see the collector and the specimen number (record number) for all herbarium specimens of a specific taxon.

-----

User provided contact info: h.steyn@sanbi.org.za
System: Chrome 75.0.3770 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/1d457d45a24da50bd2438cbd152a1964:f788d92714397f4e610da555411d47406ab1ee93fdb07669eefa9a66125e62d39ca188591ba4b57468c1636985730b9787bab62dda70468afee8d340536778ed)
Referer: https://www.gbif.org/health
Window size: width 1920 - height 920
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-20T14:27:00.547Z',mode:absolute,to:'2019-06-20T14:33:00.547Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-20T14:27:00.547Z',mode:absolute,to:'2019-06-20T14:33:00.547Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Seems reasonable. I hav added it. Thanks for the feedback.
> sent per mail
