### ISSUE TITLE
doubt on citing via rgbif

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2056]
**doubt on citing via rgbif**

Dear colleagues,
I used occ_search of rgbif to retrieve occurrences of a number of taxa, which were stored in an R list.
I can get the citation of the data for each taxon of the list, separately, using the gbif_citation function of rgibf. Each of those citations refers to the original dataset. Therefore, if i get all citations of all of the 800 taxa, I will have thousands of references to be cite.

But, I cant find a single doi in any of the elements of my list of occurrences that i may use as a single unified citation (such as "GBIF Occurrence Download `https://doi.org/10.15468/dl.j0ehrr` Accessed from R via rgbif (`https://github.com/ropensci/rgbif)` on 2017-10-18")

is there a way I can get that single citation?

thanks,
Ruben Milla

-----

System: Chrome 75.0.3770 / Windows 8.1.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b8e2714d9f9c06a918de5255e56aabee:51285f845a5f96f4cf6c5ef6c2f8a570164bcfedd3f4d915d9c5c0657a97c12141e00748bd124ef3fea7c28725ee88d40855516bab7783013b51ef5fc04aa695)
Referer: https://www.gbif.org/en/citation-guidelines
Window size: width 1164 - height 525
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-20T18:51:24.354Z',mode:absolute,to:'2019-06-20T18:57:24.354Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-20T18:51:24.354Z',mode:absolute,to:'2019-06-20T18:57:24.354Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email
> The best would be to use occ_download() instead of occ_search(). If you download all your taxa at once, you will get a single citation.
 
> Even if you already downloaded the data that you need. You could consider generating a new (big) download containing everything you need under one DOI.
This would make the citation process more manageable.
 
> I haven’t tested this, but I assume that if you have all your taxon keys in one list (named here `taxon_keys`), you should be able to generate a download with the following line:
`res <- occ_download(paste("taxonKey = ",paste(taxon_keys,collapse=",")), 'hasCoordinate = TRUE')`
 
> You should then be able to access the citation by using: `occ_download_meta(res) %>% gbif_citation()`
See [this vignette](https://cran.r-project.org/web/packages/rgbif/vignettes/downloads.html) for more information.
 
> The citations for download are also available on the download pages (regardless of whether they were generated in R or via the web interface).
For example, for this download: https://www.gbif.org/occurrence/download/0030480-181108115102211, the citation is “GBIF.org (24 January 2019) GBIF Occurrence Download https://doi.org/10.15468/dl.jmmjsu”.
