### ISSUE TITLE
Download request unsuccessful

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2057]
**Download request unsuccessful**

Download request submitted via the rgbif package are unsuccessful when including >500 species in the request. How can this be addressed?

-----

User provided contact info: phill@gmx.li
System: Chrome 75.0.3770 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/d95188ff96e1ae74a282edc9645da59e:99c104b2ffd571d1ef40bb58873ba09fb6143d3bbfaee128afc848e9e27ff95f82692150cc26fa20295e1359ab1312a85aefba1db9ffd67a148cfda18901afd3)
Referer: https://www.gbif.org/user/download
Window size: width 1231 - height 670
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-21T04:51:14.260Z',mode:absolute,to:'2019-06-21T04:57:14.260Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-21T04:51:14.260Z',mode:absolute,to:'2019-06-21T04:57:14.260Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
Responded via helpdesk. 

Hello Phil, 

There is a hard limit in our system of 200 groups (taxon_key(s)). I am not really sure why we have this limit but I believe it is something to do with a string character limit somewhere. 

If you find a grouping of your species list that is less than 200 taxon_key(s) you will be able to download all your species. For example, if your list is only birds, you could download all birds or just the few families of birds that your species belongs. This should get you all the species in your list in one download. You can then filter the list on your end to include only the species you want. 

There is also the possibility to request a custom download if your list is hard to gather into a higher taxonomic grouping.
