### ISSUE TITLE
Multimedia possibile in checklist datasets?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2058]
**Multimedia possibile in checklist datasets?**

We recently added multimedia to the DWCA of one of our  species checklist (`https://www.gbif.org/dataset/4dd32523-a3a3-43b7-84df-4cda02f15cf7).`

Including multimedia in the DWCA is accepted by the harvester but I wondered whether these images are used in GBIF taxonomic backbone (Are the images only taken from occurrence datasets?).  In the best practice guide the (`https://github.com/gbif/ipt/wiki/BestPracticesChecklists)` multimedia extension is not mentioned as one of options, which suggests that is has no value to enrich the species data with images.

-----

User provided contact info: @jeroen
System: Chrome 75.0.3770 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/4d7b214fd566dcb3e2cd5d2b3e93ab06:6543715a8eeddc6f39ea41c9e93a6f8f8d51547fe460ccce186a80c5108386f27935e8172e0ea19767d8740e2c8f142b33a3f504f1f4dbf8b6cd87021e306daa)
Referer: https://www.gbif.org/user/profile
Window size: width 1707 - height 760
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-24T14:48:17.679Z',mode:absolute,to:'2019-06-24T14:54:17.679Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-24T14:48:17.679Z',mode:absolute,to:'2019-06-24T14:54:17.679Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jeroencreuwels** [comment]
It appears that the images are visible at various species pages  (e.g. https://www.gbif.org/species/152462221).  This issue can be closed.

**Comment by ManonGros** [comment]
They are visible on the species page for which the source is the checklist, but not on the backbone species page (https://www.gbif.org/species/8225376) when only the images associated with occurrences are visible.
