### ISSUE TITLE
HoD and NM roles unclear at GBIF.org

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2060]
**HoD and NM roles unclear at GBIF.org**

Any discussion with a potential participant country requires explanation of the role of HoD and a Node Manager, there seems to be no short definition on the open pages. I suggest a compressed description of the roles is added to the last lines of the this page, based on the longer PDF were duties are listed.

-----

User provided contact info: @dschigel
System: Firefox 67.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/1aeb8378c9a9b05a369ea5296a3e41b1:dc4926962997b12ab50939a1073eacb40dac42f59ffb324a32eb2e25a39ab43d4c41f1885ecff8bcb9bf4a720e90440e2e47f8ce1a7e796b5bb83bc46c64120b)
Referer: https://www.gbif.org/become-member
Window size: width 1536 - height 760
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-25T09:49:36.616Z',mode:absolute,to:'2019-06-25T09:55:36.616Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-25T09:49:36.616Z',mode:absolute,to:'2019-06-25T09:55:36.616Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by anmnielsen** [comment]
This is the PDF that @dschigel  is referring to. [GBIF Head of Delegation and Node Manager.pdf](https://github.com/gbif/portal-feedback/files/3324705/GBIF.Head.of.Delegation.and.Node.Manager.pdf)

**Comment by dnoesgaard** [comment]
Thanks, @anmnielsen for the PDF. Does that document live anywhere online?

**Comment by kcopas** [comment]
https://docs.gbif.org/effective-nodes-guidance/1.0/en/#box-2

**Comment by dnoesgaard** [comment]
Very nice. Is that documentation "in production" status?

We can add a link, e.g. ([more details about roles and responsibilities](https://docs.gbif.org/effective-nodes-guidance/1.0/en/#box-2)) to the "Become a member" page?

**Comment by kcopas** [comment]
Yes, though it's (as yet) unannounced, it's the one digital document that can be considered in production, having move from a uat address to final production one. 

Probably (hopefully) not the last instance where we can direct attention to a source, rather than replicating and/or rephrasing.

**Comment by dnoesgaard** [comment]
Yes, very nice indeed. This'll be a great resource.

Now stop looking at Github on your day off :)

**Comment by kcopas** [comment]
At least it wasn't via GBIF email ;-)

**Comment by dnoesgaard** [comment]
Link to nodes documentation added.
