### ISSUE TITLE
Quercus sadleriana missing from backbone

### ISSUE THREAD

**Issue by esbeckman** [gbif/portal-feedback#2061]
I have downloaded GBIF points for Quercus sadleriana in the past, but it seems it has been deleted from the taxonomic backbone (https://www.gbif.org/species/search?q=quercus%20sadleriana)? To my knowledge, there are no taxonomic reasons for the species to be deleted; here are some sources: 
- Flora of North America, http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=233501081
- The Plant List, http://www.theplantlist.org/tpl1.1/record/kew-174947
- World Checklist of Selected Plant Families, https://wcsp.science.kew.org/namedetail.do?name_id=174947
- etc.

**Comment by MattBlissett** [comment]
Thanks Emily,

The deleted taxon is https://www.gbif.org/species/2880444

Our checklist/backbone developer might be able to explain why the name is no longer present in GBIF's backbone taxonomy, though I think he is on holiday today. I see we do have the name in several of the datasets which are used for assembling the backbone taxonomy: https://www.gbif.org/species/search?q=Quercus%20sadleriana&advanced=1

Searching for Q. sadleriana occurrences can be done like this, if you need to: https://www.gbif.org/occurrence/search?q=sadleriana&taxon_key=2877951 (i.e. search for the genus Quercus, and a free-text search for sadleriana.)

If you need to download the data, which isn't possible with a free-text search, I suggest downloading Quercus in Darwin Core Archive format.  The ZIP file will then contain two data files: occurrence.txt, which contains GBIF-interpreted values similar to the CSV file, and verbatim.txt, which has the original values from the data publisher.

**Comment by ManonGros** [comment]
It looks like `Quercus sadleriana` is in the current backbone so I am closing the issue.
