### ISSUE TITLE
Fields in results not mapped correctly

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2062]
**Fields in results not mapped correctly**

When I added fields to the results view, they were not mapped correctly. Record number contained the collector, Recorded by seemed to be the barcode. Catalogue number appeared to be the Institute code.

-----

User provided contact info: e.haston@rbge.org.uk
System: Chrome 74.0.3729 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/8dbed14ebc37166b5ee652d98550295a:dac4ba03af5f51c252b0a4ee35ed8f833d291a743218761bfb5f08069b8879295627f95d6d7050ad8bef33b8aef44b072721809958b5d8b27a5144b79d61b06e)
Referer: https://www.gbif.org/occurrence/search?offset=60&taxon_key=2976907
Window size: width 1280 - height 864
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-26T20:56:50.176Z',mode:absolute,to:'2019-06-26T21:02:50.176Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-26T20:56:50.176Z',mode:absolute,to:'2019-06-26T21:02:50.176Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Confirmed:

![image](https://user-images.githubusercontent.com/583320/60327832-3929f400-998d-11e9-9f10-096096b6e1b9.png)

Are null fields disrupting the table?
