### ISSUE TITLE
I am not a caddisfly.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2066]
**I am not a caddisfly.**

Expert on the staphylinid in question feels demoralized. See `https://twitter.com/schatzimanolis/status/1145449545524023296`

-----

System: Chrome 75.0.3770 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/ae0e8c6b027987acca4076d5f3273251:9df12fcadbc0d09187839b5ea987d6868ea3eb3c55e310ff598a5a31b21491570dc7687c21b3c90f087917cbe8eed5443d4ed49ed417e4d64eb0144f15f90df900342965ad73b1ecddc77b4897ccfa47)
Referer: https://www.gbif.org/occurrence/1324904706
Window size: width 1412 - height 699
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-01T22:22:25.509Z',mode:absolute,to:'2019-07-01T22:28:25.509Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-01T22:22:25.509Z',mode:absolute,to:'2019-07-01T22:28:25.509Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: b65c0886-3c24-4ead-a93a-b89d2a676b10
publishingOrgKey: efcf5460-a06a-11d9-8ec2-b8a03c50a862

**Comment by ManonGros** [comment]
Indeed we don't seem to have Leptochirus gracilis (https://www.gbif.org/species/3262255). The name was mistakenly matched to [Leptocerus gracilis (Ulmer, 1912)](https://www.gbif.org/species/5053206).

**Comment by ManonGros** [comment]
Looks like the new taxonomy contain `Leptochirus gracilis` (https://www.gbif.org/species/10310540) so the match is now correct.
