### ISSUE TITLE
Download page shows 0 occurrence even thought download not empty

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2067]
**Download page shows 0 occurrence even thought download not empty**

Is the number displayed on this page 0 because no-one actually downloaded the data or could it be a bug?

(The download was generated by a rgbif user to get one citation for his analysis: https://github.com/gbif/portal-feedback/issues/2056)

-----

User provided contact info: @ManonGros
System: Safari 12.1.1 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/778cf0f460e945b45600ea54084b250c:d1c1de7f923735f9fb6133c3dd49aa3462b125891b0bbe4a4eab18a3cc21e70942f3346092e85da49de0446ec86e8e35dd32637386943227f464df476332b0bd)
Referer: https://www.gbif.org/occurrence/download/0004229-190621201848488
Window size: width 2149 - height 874
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-02T07:21:55.949Z',mode:absolute,to:'2019-07-02T07:27:55.949Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-02T07:21:55.949Z',mode:absolute,to:'2019-07-02T07:27:55.949Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Sometimes the download metadata doesn't update once the download is complete. I've fixed it for all the downloads that have this problem.
