### ISSUE TITLE
Missing name: Cette Fiche N'Est Pas Une fiche taxon

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2069]
**Missing name: Cette Fiche N&#39;Est Pas Une fiche taxon**

This specimen appears to be one collected by Philipp Franz von Siebold, but the name is totally mangled—maybe a simple data entry error, with a note intruding on the name field?

Either that or Marcel Duchamp is responsible for the identification…

-----

User provided contact info: @kcopas
System: Safari 12.1.1 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/2d3986ae0654683a228542bca4b52906:64c2d2d45d20588fe6735cc099636ee3afd1f41c6aec910c8a2a889dcee8df9e60597a904a977be6ad7feba53116a9fd52159aa34d3415a792eff109133596c3)
Referer: https://www.gbif.org/occurrence/1019451845
Window size: width 1516 - height 932
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-02T18:45:52.541Z',mode:absolute,to:'2019-07-02T18:51:52.541Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-02T18:45:52.541Z',mode:absolute,to:'2019-07-02T18:51:52.541Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Contacted MNHN.

**Comment by ahahn-gbif** [comment]
Closing (all records from https://www.gbif.org/dataset/fea77396-7b26-44cb-8580-aefadc8db276 have been fixed)
