### ISSUE TITLE
taxonKey wrongly linked in occ search

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#207]
**taxonKey wrongly linked in occ search**

When following the polygon occ search from the species map the taxonKey is wrongly passed over so its missing in the occ search. It should be taxon_key not taxonKey

-----
fbitem-species3230710

System: Chrome 58.0.3029 / Mac OS X 10.12.5
Referer: https://demo.gbif.org/species/3230710
Window size: width 1665 - height 845
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-07T20:21:42.276Z',mode:absolute,to:'2017-06-07T20:27:42.276Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-07T20:21:42.276Z',mode:absolute,to:'2017-06-07T20:27:42.276Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
fixed
