### ISSUE TITLE
no mollusc

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2070]
**no mollusc**

Coenomyia ferruginea is not a molluscan species, it belongs to the insect family:

>  Animalia: Arthropoda: Mandibulata: Insecta: Diptera: Coenomyidae: Coenomyia

-----

User provided contact info: @aallspac
System: Firefox 60.0.0 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b011bf84bc3a2aa9c620beb363f40c8c:5a40871e2fca8bbf2cc62397b67681c59e8cca4426f1be2b7c92a16120ba4089f23af0941ab2bad1f2397888e87859fe3cba87aa7e0beec4ac0bd8ff0d8d99d8)
Referer: https://www.gbif.org/occurrence/1831057725
Window size: width 1866 - height 988
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-03T11:14:03.233Z',mode:absolute,to:'2019-07-03T11:20:03.233Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-03T11:14:03.233Z',mode:absolute,to:'2019-07-03T11:20:03.233Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
see https://github.com/gbif/portal-feedback/issues/1461
