### ISSUE TITLE
Adding dataset UUID to issues reported from the portal

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#2071]
It would be great if the issues concerning occurrences could also include their dataset's UUID.

**Comment by ManonGros** [comment]
It would help me forward and keep track of the issues logged. Especially since the occurrence links might become deprecated easily.

Overall, it would be great if there was a way to link all the occurrence related to the same dataset. That way, if I write about a new issue to a publisher, I could also add "there are X reported issues concerning specimens included in this dataset, you can consult them here [link]".

The links to the issues could be available the dataset page somehow. It wouldn't have to be automated (since someone has to review them anyway) but it might make it easier for publishers (and mostly me) to keep track of what is happening.

**Comment by ahahn-gbif** [comment]
also (in the wider sense) relates to #1780

**Comment by ManonGros** [comment]
The part where the issues are linked to the dataset page isn't at all necessary but being able to group the issues per datasets on GitHub would be very useful.
