### ISSUE TITLE
Change title to avoid 0

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2074]
**Change title to avoid 0**

This happens when a query can't be fired at solr but it ended up running a correct Hive download.

There is not an easy fix for this (likely it needs the addition of a new stage of counting in the download).

I suggest simple saying "Occurrence download" instead of "0 occurrences downloaded" when the number is 0

-----

User provided contact info: @timrobertson100
System: Chrome 75.0.3770 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/755db6c33a315c473f270799d8ae235a:0647ddd67b9d059b02e1fb34b174bb5724b78d3c3ffc3d29d78144b7bac4fa117e4abf9704ce9ab7e7939e35d1bb5bf976e3e59eb32c829ecc4cc8b6bc668565)
Referer: https://www.gbif.org/occurrence/download/0005968-190621201848488
Window size: width 2172 - height 1225
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-05T09:27:38.748Z',mode:absolute,to:'2019-07-05T09:33:38.748Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-05T09:27:38.748Z',mode:absolute,to:'2019-07-05T09:33:38.748Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Yes, that's an easy fix, and will avoid confusion.

The download workflows count per-dataset and update the dataset-occurrence-download table, so the proper fix will be to sum those values and update the occurrence-download table too.
