### ISSUE TITLE
false synonyms

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2078]
**false synonyms**

Muscicapa striata (ref: 2492576) has been merged into Setophaga striata (ref: 6092935) though they are not synonyms at all (not in the same family) !

-----

User provided contact info: @YvesBas
System: Chrome 75.0.3770 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/abf2e9caa17a22d7c24d92599015d34e:59e30e1b6f9598b05685bb5c882138766907af3af56bb73711f721fe9e5d0342cca3697b495134f74a5a6cb1363c471bbe09d4b692b0679efbf0cf14a3517cd5)
Referer: https://www.gbif.org/species/6092935
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-07T08:50:17.971Z',mode:absolute,to:'2019-07-07T08:56:17.971Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-07T08:50:17.971Z',mode:absolute,to:'2019-07-07T08:56:17.971Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by yroskov** [comment]
Muscicapa striata (Pallas, 1764) and Setophaga striata (J. R. Forster, 1772) are two different species:
http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/09e3d20d937addb4de95958f1b2d3e0a
http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/891172a2730002d57948ac2b10c03c80

**Comment by ManonGros** [comment]
The issue has been solved in the new backbone.
