### ISSUE TITLE
Improve the context for search hits

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#208]
**Improve the context for search hits**

A species search for _Antigone antigone_ finds only _Buenoa platycnemis Fieber_, 1851 but it is not entirely clear to a user why at this point.

The reason is that the &quot;materials examined&quot; information mentions that species.  Some context would be nice to show in the search results when it is not a name or synonym match.  I believe the API already supports this, as it shows like that in the current www.gbif.org site http://www.gbif.org/species/search?q=Antigone+antigone&dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c

-----
fbitem-1f059dd0d137ccd641e791a2992ee7e29204a773
Reported by: @timrobertson100
System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/species/search?q=Antigone%20antigone
Window size: width 1621 - height 1063
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-08T08:23:30.153Z',mode:absolute,to:'2017-06-08T08:29:30.153Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-08T08:23:30.153Z',mode:absolute,to:'2017-06-08T08:29:30.153Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
Similar when searching for vernacular names there is no indication what has matched:
https://demo.gbif.org/species/search?q=eiche

**Comment by timrobertson100** [comment]
The API call for this is to add [`&hl=true`](http://api.gbif.org/v1/dataset/search?q=plant&hl=true) and then check the response for instances of `<em class=\"gbifHl\">`.

**Comment by mdoering** [comment]
To reduce the amount of data returned the extended=false flag should also be used (default is true):
http://api.gbif.org/v1/species/search?q=eiche&hl=true&extended=false

https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/model/checklistbank/search/NameUsageSearchRequest.java#L87

**Comment by mdoering** [comment]
... and by setting the request.queryFields one can also avoid matching to the descriptions entirely. Not sure if thats what we want in this case, but an example as its not documented well:

http://api.gbif.org/v1/species/search?q=eiche&hl=true&extended=false&qField=SCIENTIFIC&qField=VERNACULAR&hlContext=10

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/446
