### ISSUE TITLE
Dataset locked (perhaps?) unnecessarily

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2080]
**Dataset locked (perhaps?) unnecessarily**

The dataset `https://www.gbif.org/dataset/835ac57e-f762-11e1-a439-00145eb45e9a` is locked for auto-update, which means it has the incorrect license.  The EML says CC BY, but the registry contains CC BY NC. Is there any reason to keep it locked?

Once unlocked, a recrawl will probably fix things.

-----

User provided contact info: @MattBlissett
System: Firefox 67.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/ef393a83902ebd3795fbe67eecfece69:f34038b936e8cd08d6e651d239d59de18960d8fc8795d04fdbb45d3645db938365dd59806b8b2a81d4160dedd6033a61a636ab8567e7583a110adf0ce8fb2389)
Referer: https://www.gbif.org/dataset/835ac57e-f762-11e1-a439-00145eb45e9a
Window size: width 1920 - height 948
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-09T08:02:33.468Z',mode:absolute,to:'2019-07-09T08:08:33.468Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-09T08:02:33.468Z',mode:absolute,to:'2019-07-09T08:08:33.468Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I tried to unlock it with the registry interface but it didn't work (https://github.com/gbif/registry-console/issues/304)

**Comment by MortenHofft** [comment]
The issues have been fixed and I have unlocked the dataset

**Comment by ManonGros** [comment]
Thanks Morten! Now the dataset has been unlocked and recrawled but the license isn't updated. @MattBlissett any idea why? Should I update the license in the registry?

**Comment by MattBlissett** [comment]
I have reprocessed the metadata:

`./reprocess-metadata 835ac57e-f762-11e1-a439-00145eb45e9a` (new command on crap).

Normally, if the metadata doesn't change between ingestions, no action is taken.
