### ISSUE TITLE
Out-of-sync / overingested dataset not detected or auto-deleted

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2081]
**Out-of-sync / overingested dataset not detected or auto-deleted**

The dataset has exactly double the occurrences it should have, but it doesn't show up on the overingested datasets page.

-----

User provided contact info: @MattBlissett
System: Firefox 67.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/b27aa996fa3f3dbafad07dd89eaebc68:c601e84dfc6d62c01d4a2fbcdbd699c08330b599fb7f64c34d7bd820469ac5c89cf698ceba878f54c842f669ccc8b58072cd393ce347e878656e7abca26447fc)
Referer: https://www.gbif.org/dataset/835ac57e-f762-11e1-a439-00145eb45e9a
Window size: width 1920 - height 948
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-09T08:08:28.118Z',mode:absolute,to:'2019-07-09T08:14:28.118Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-09T08:08:28.118Z',mode:absolute,to:'2019-07-09T08:14:28.118Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
IIRC, the autodeleter wasn't running.
