### ISSUE TITLE
Publishing individual occurrence data versus lot data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2082]
**Publishing individual occurrence data versus lot data**

Hello,

I am working on getting some collections cleaned and uploaded onto GBIF.

At my institution (Canterbury Museum) every specimen receives a unique accession number (catalog number) and record, even though a specimen may be part of a collection lot event. Can individual data records be uploaded, or do they need to be specimen lots with number of individual counts?

Best,
Johno

-----

User provided contact info: jridden@canterburymuseum.com
System: Chrome 75.0.3770 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/a7b4ed00298d36c201cc1c17cbd94f3f:a96640a11ea5e5692c642cc9535a307e293f9f54ae6c114e9e951fa4c591ea5db89f7a721f7ad07a7623418b4e66cfc0959dcdb6325dbe6045c05cccda01fa1b)
Referer: https://www.gbif.org/science-review
Window size: width 1264 - height 908
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-09T21:13:18.371Z',mode:absolute,to:'2019-07-09T21:19:18.371Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-09T21:13:18.371Z',mode:absolute,to:'2019-07-09T21:19:18.371Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by tucotuco** [comment]
Hi Johno,

Individual specimen records can be published, but there is a constraint
that they be uniquely identified. It sounds like you have that ("every
specimen receives a unique accession number (catalog number) and record").
If this is indeed the case, then no problem.

Cheers,

John
