### ISSUE TITLE
record on page https://www.gbif.org/occurrence/1457777105 contains a typo.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2084]
**record on page `https://www.gbif.org/occurrence/1457777105` contains a typo.**

typo details: coordinates do read  
Decimal longitude -7.523889
They should however read 
Decimal longitude -70.523889 

This would resolve the country mismatch and would also perfectly fit the location as described in the text.

-----

User provided contact info: martin.reith@rhul.ac.uk
System: Firefox 68.0.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/6e628783e1660107bda59a0c208ae117:c458a63265f6e2a1ea00aecaa45d8c14d6b30fd8ad2adc8592d1ec425322128d3d7a7b52f80b5fb1b19a6c30971787baae0850a487c53b9b03400152749b581e)
Referer: https://www.gbif.org/occurrence/1457777105
Window size: width 1119 - height 608
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-10T03:52:51.791Z',mode:absolute,to:'2019-07-10T03:58:51.791Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-10T03:52:51.791Z',mode:absolute,to:'2019-07-10T03:58:51.791Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Publisher notified by email.
