### ISSUE TITLE
Broken links on contry summary page in alternative language

### ISSUE THREAD

**Issue by cgendreau** [gbif/portal-feedback#2085]
Hi GBIF!

From https://www.gbif.org/fr/country/CA/summary (but same with Spanish) links like "Fournisseurs de données" send us to https://www.gbif.org/null which makes links on the page non-functional. For example I see the tab "Statistiques" but all the links in the table are not working.

Please let me know if it`s not clear.

**Comment by MortenHofft** [comment]
Salut Christian. Merci. C'est réparé je croix.
