### ISSUE TITLE
markup for greaterThanOrEquals

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2086]
**markup for greaterThanOrEquals**

I just noticed this download in which the filter below has been used:

    {
      "type": "greaterThanOrEquals",
      "key": "EVENT_DATE",
      "value": "1950-01-01"
    }

In the human-readable version of the query, it appears we don't distinguish between *equals* and *greaterThanOrEquals*, so I thought this was a very specific query or a mistake.

Perhaps there's an easy of showing different types of predicates?

-----

User provided contact info: @dnoesgaard
System: Chrome 75.0.3770 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/4ad08489b9a37eae77811fd769b8d31b:634978242d655862ec3c08983dfc474375c7e7acd21d40956b1960e8ad549e5866ed6e37834b858fdfa840e99f594c062d055cc63890638fc8460436abece810)
Referer: https://www.gbif.org/occurrence/download/0003932-151016162008034
Window size: width 2560 - height 1221
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-11T07:40:20.653Z',mode:absolute,to:'2019-07-11T07:46:20.653Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-11T07:40:20.653Z',mode:absolute,to:'2019-07-11T07:46:20.653Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/25cdd8519562d54807d2b1d688c6c1f6cb439217
