### ISSUE TITLE
Italicize scientific names

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#209]
**Italicize scientific names**

Scientific names in the search results and on the header of the species detail page should be italicized.

-----
fbitem-1f059dd0d137ccd641e791a2992ee7e29204a773
Reported by: @timrobertson100
System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/species/search?q=Antigone%20antigone
Window size: width 1621 - height 1063
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-08T08:24:34.410Z',mode:absolute,to:'2017-06-08T08:30:34.410Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-08T08:24:34.410Z',mode:absolute,to:'2017-06-08T08:30:34.410Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Indeed. they are now. As I cannot evaluate this myself I used the macro by Markus (https://github.com/gbif/portal16/blob/master/app/views/components/common.macros.nunjucks) (ported to js) and confirmed doing so with Tim. @mdoering and @thomasstjerne you might want to evaluate it once again. I have a feeling it is the kind of thing we want to get right. I notice that kingdoms are italicized. Is that correct or just the best we can do or a bug? It will available be on dev shortly.

**Comment by mdoering** [comment]
names family rank and above incl kingdom should not be italicized.
The code also still needs to be updated to work with the following name types which have special attributes currently not rendered:
- named hybrids (x not showing): http://api.gbif-uat.org/v1/species/114008304/name
- cultivar names: http://api.gbif-uat.org/v1/species/100428818/name
- bacterial candidate names: http://api.gbif-uat.org/v1/species/100221413/name
- unparsable names:
   - hybrid formulas: http://api.gbif-uat.org/v1/species/115078221/name
   - virus names: https://demo.gbif-dev.org/species/8992747 or https://demo.gbif-dev.org/species/8904339
   - OTU: http://api.gbif-uat.org/v1/species/125595117/name

This is also true for displaying names in the species search. Unparsable names lacking a canonical name (virus, hybrid, OTU) are showing as blanks now:
https://demo.gbif-dev.org/species/search?name_type=OTU&advanced=1

**Comment by MattBlissett** [comment]
The botanical code does italicize names of higher ranks, and recommends it, but doesn't mandate it: http://www.iapt-taxon.org/nomen/main.php?page=pf&emph=italic

I don't know about zoological names.

**Comment by MortenHofft** [comment]
I'm getting comflicting signals. I like Matts version as I don't have to change anything, but I will leave it to you guys to decide. Let me know when you have.

**Comment by mdoering** [comment]
I think the crucial part is "scientific names under the jurisdiction of the Code" which higher ranks above family are not. 

I suppose this is a little bit up to us and conventions rather than strict rules.
I would suggest to stick with no italics at family level and above.

-----
ZooBank does only place genus & below in italics, not families:
species: http://zoobank.org/NomenclaturalActs/B6CD71C7-2AB9-4973-A12B-E960677AA573
genus: http://zoobank.org/NomenclaturalActs/9533CC4B-0306-4EBE-B9E4-EE679E1464EE
family: http://zoobank.org/NomenclaturalActs/5E8A5264-DD6B-406B-A69B-01ADA841389F
subphylum: http://zoobank.org/NomenclaturalActs/7CE23269-D566-4FFE-AA1A-A5EB23822684

Same here: http://blog.vancouvereditor.com/2011/03/science-writing-and-editing-scientific.html

-----
IPNI does not place families in italics:
http://www.ipni.org/ipni/idPlantNameSearch.do?id=319342-2

But many of the Kew applications do:
http://e-monocot.org/taxon/urn:kew.org:wcs:family:79;jsessionid=4A58CECD2BF547FBDC88C505EC6584A4.kppapp02

http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:319342-2

-----
Related older issue in Jira: http://dev.gbif.org/issues/browse/POR-1551

**Comment by MattBlissett** [comment]
Are the higher ranks not under the code? I thought they were, based on http://www.iapt-taxon.org/nomen/main.php?page=art16 -- in any case, they are italic when mentioned in the code.

Kew decided to follow the way the Code was printed with the newer web apps, and italicize all ranks; both for consistency and to avoid getting it wrong when the data was incomplete. I personally prefer it, as it gives a clear distinction between the name and the author.

**Comment by mdoering** [comment]
@MattBlissett so you prefer to show zoological and botanical names differently?
ICZN clearly says:

> "The scientific names of genus- or species-group taxa should be printed in a type-face (font) different from that used in the text; such names are usually printed in italics, which should not be used for names of higher taxa."

**Comment by MattBlissett** [comment]
Ah, I didn't see your edit.

We should have consistency between kingdoms, so that means following the ICZN style, even though I don't like it.

**Comment by kcopas** [comment]
Comms perspective—itals for genus and species, roman for other ranks. 

It's just a choice to stick to, either way (though I'd prefer the above). It's not consistent across authorities, or even for common names, i.e. birders want Initial Caps for Common Names, though most others prefer lowercase (less Germanic?) approaches ;-)

**Comment by ahahn-gbif** [comment]
As above, but "itals for (...) and subspecific levels", as already displayed here: https://demo.gbif-dev.org/species/7823929 (NB: the "var" should indeed _not_ be in italics)

**Comment by MortenHofft** [comment]
I've updated the parser to simply use the scientific name for type = Hybrids, OTU or Virus.

The remaining is better left to you @thomasstjerne

**Comment by thomasstjerne** [comment]
I have done an update on the name renderer, please check and let me know if it needs further adjustments.
Some examples:
Families: https://demo.gbif-dev.org/species/search?rank=FAMILY&advanced=1
Candidate names: https://demo.gbif-dev.org/species/search?name_type=CANDIDATUS&advanced=1
Cultivars: https://demo.gbif-dev.org/species/search?name_type=CULTIVAR&advanced=1
A named hybrid: https://demo.gbif-dev.org/species/114008304

**Comment by mdoering** [comment]
That looks great, Thomas!
A tiny issue is superfluous whitespace at the end of candidatus species: https://demo.gbif-dev.org/species/126231748

Looking at the list of cultivar names lots of them seem to be regular linnean names, oh well.
