### ISSUE TITLE
What are the restrictions/conventions for "Area/Country" in the GBIF occurrence database? That is, if a datapoint doesn't use a country for that field, is there any standards for what is used?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2094]
**What are the restrictions/conventions for &quot;Area/Country&quot; in the GBIF occurrence database? That is, if a datapoint doesn&#39;t use a country for that field, is there any standards for what is used?**

-----

User provided contact info: dsmith@tyemil.com
System: Chrome 75.0.3770 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/7be4cc1eab684f918e133bd64ea7d971:f7b5a05e6fedfb5a659c266f1515cc1dab4da142bdb44f8c892d962cb89aaaefcbec254acbf604e478daf4b7ca232c6bc214522e579cf55a62488d548d615557)
Referer: https://www.gbif.org/faq?q=country
Window size: width 1180 - height 1085
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-12T18:25:58.562Z',mode:absolute,to:'2019-07-12T18:31:58.562Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-12T18:25:58.562Z',mode:absolute,to:'2019-07-12T18:31:58.562Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.

**Comment by ManonGros** [comment]
It seems like the recipient's domain does not exist so the email couldn't be delivered.

dsmith just in case you are checking this issue, here is what I tried to reply:
> Depending on what type of information is available, our system process occurrences differently:
> * If only coordinates are provided, our system [flags](https://www.gbif.org/occurrence/search?issue=COUNTRY_DERIVED_FROM_COORDINATES) the occurrence infers the country/area base on these coordinates.
> * If only the country/arear is provided, you will be able to find the occurrence with the “Country or area” filter in the menu. However, the occurrence won’t appear on the [map](https://www.gbif.org/occurrence/map).
> * If both coordinates and country are provided, our system will check whether they match. If the system detects any discrepancy, the occurrence will be flagged and the coordinates might be corrected. See for example, the occurrences with [presumed swapped coordinates](https://www.gbif.org/occurrence/search?issue=PRESUMED_SWAPPED_COORDINATE) or [presumed negated longitude](https://www.gbif.org/occurrence/search?issue=PRESUMED_NEGATED_LONGITUDE).

> There are many other fields which can convey location information. Check out the [Darwin Core Terms](https://dwc.tdwg.org/terms/#location) to see what is available.
If you would like to download raw, uninterpreted data, I suggest that you choose the “DARWIN CORE ARCHIVE” format on the download page.
