### ISSUE TITLE
Update AUMNH publisher name?

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#2096]
With the update and replacement of an old DiGIR dataset (#1441 ), it might be a good moment to change the publisher currently known as [Auburn University Museum DiGIR Provider](https://www.gbif.org/publisher/34cc6c50-812c-11de-86fe-b8a03c50a862) to something like the Auburn University Museum of Natural History. 

cc: @dbloom

**Comment by tucotuco** [comment]
Yes, that looks right.

**Comment by ManonGros** [comment]
I just wrote to the contact to ask for confirmation and ask if they would like to add any description.

**Comment by ManonGros** [comment]
Title updated.
