### ISSUE TITLE
? zonarius

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2097]
**? zonarius**

`https://www.gbif.org/species/2479720`
What's with the question mark in "? zonarius" ?
Shaw's Miscellany, volume 16, first page of signature F, plainly says Psittacus zonarius.

-----

System: Firefox 68.0.0 / Mac OS X 10.9.0
User: [See in registry](https://www.gbif.org/api/feedback/user/14973546d33068a956b646eafc06c3c3:7ede665f7146a102647e966956fb2d982edb6797c8c5d849534605eaa17ebb7718342a537a00079e15e5268804444da90389e8a026d9ea842f7047a0637516cf)
Referer: https://www.gbif.org/species/2479720
Window size: width 1145 - height 782
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-14T00:57:41.702Z',mode:absolute,to:'2019-07-14T01:03:41.702Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-14T00:57:41.702Z',mode:absolute,to:'2019-07-14T01:03:41.702Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This record has been created during indexing and did not explicitly exist in the source data as such.

Origin: Placeholder usage for a missing or implicit basionym.

**Comment by jhnwllr** [comment]
question mark appears to be gone.
