### ISSUE TITLE
temporal coverage starting at 0206

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#21]
**temporal coverage starting at 0206**

It seems unlikely that the temporal coverage of iNaturalist is 7 August 0206 - 6 October 2016.

I assume it is a typo?

-----
fbitem-dataset50c9509d-22c7-4a22-a47d-8c48425ef4a7
Reported by: @mhoefft
System: Chrome 54.0.2840 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7
Window size: width 1838 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-05T10:09:57.208Z',mode:absolute,to:'2017-01-05T10:15:57.208Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-05T10:09:57.208Z',mode:absolute,to:'2017-01-05T10:15:57.208Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
iNaturalist have been notified here: https://github.com/inaturalist/inaturalist/issues/1248

**Comment by MortenHofft** [comment]
It was caused by a bad record that had been qualified as research grade. The record has since been down voted and should disappear when next indexing.
