### ISSUE TITLE
When I search on a species, the table that shows seems to have coordinates for all observations (under field: "coordinates"), but when I download, most don't have coordinates - and it is in two fields "decimal.latitude" and "decimal.longitude").  So it seems to me that there is a field that doesn't download.  I'm not sure if those are inferred coordinates for your hexes on your map visualizations.  But it would be nice to get all that information.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2102]
**When I search on a species, the table that shows seems to have coordinates for all observations (under field: &quot;coordinates&quot;), but when I download, most don&#39;t have coordinates - and it is in two fields &quot;decimal.latitude&quot; and &quot;decimal.longitude&quot;). So it seems to me that there is a field that doesn&#39;t download. I&#39;m not sure if those are inferred coordinates for your hexes on your map visualizations. But it would be nice to get all that information.**

-----

User provided contact info: leslie.ries@georgetown.edu
System: Chrome 75.0.3770 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/152d71c0c63f1931303a0e79630b0668:1f9947b9abdcbc95c91778e076776b29172e82ee2e84ef3804405c23742ea8cf36b3fe84f581fdf7e6b96621d12e30e2168d7c9e82a42c5373ca53b6a2c3481c)
Referer: https://www.gbif.org/occurrence/search?offset=120&has_coordinate=true&has_geospatial_issue=false&taxon_key=1895138
Window size: width 1920 - height 946
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-15T19:25:31.908Z',mode:absolute,to:'2019-07-15T19:31:31.908Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-15T19:25:31.908Z',mode:absolute,to:'2019-07-15T19:31:31.908Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
https://www.gbif.org/occurrence/download/0012498-190621201848488
I believe this has to do with the tool you use to see the download. Above download for example has coordinates for all fields. But the csv is in fact a tsv and need to be treated as such when opening it.
See also 
https://www.gbif.org/faq?question=opening-gbif-csv-in-excel

hope that helps
Thanks

**Comment by MortenHofft** [comment]
Suugested fix https://github.com/gbif/occurrence/issues/100
