### ISSUE TITLE
Login in IPT several times

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2105]
**Login in IPT several times**

Hi!

My IPT keeps on telling mr to login everytime I click the upper menu? and everytime I click the manage resources.

`http://bim-mirror.aseanbiodiversity.org:8080/ipt/`

Thanks,
Kit

-----

User provided contact info: cbelloran@aseanbiodiversity.org
System: Chrome 75.0.3770 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/c99d65be0804c7708a2b60f60fe15718:a39bee3fb503164ce421e480824e870b20d53c2fc53f4f278ce706fb34636aad9a237bc1858e0d41cc5263ca4714df5e5a002724efec695e737d0ed8138793a8)
Referer: https://www.gbif.org/
Window size: width 1920 - height 947
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-16T03:26:52.594Z',mode:absolute,to:'2019-07-16T03:32:52.594Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-16T03:26:52.594Z',mode:absolute,to:'2019-07-16T03:32:52.594Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mike-podolskiy90** [comment]
This does not occur in new IPT versions (^3.0.0)
