### ISSUE TITLE
Inconsistent publishing information

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2106]
**Inconsistent publishing information**

A [search](`https://www.gbif.org/search?q=Armenia)` shows `10,171 occurrences published` but the detail page shows nothing which is confusing.

The cause is eBird, but I anticipate other datasets will also contribute in the future.

We should consider making this more clear on the country page with some information about those datasets not published by the country, but likely to represent national effort. 

Reporting for a friend how was confused.

-----

User provided contact info: @timrobertson100
System: Chrome 75.0.3770 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/005269a00b44f993b52416f49fad0c0f:ab6c759f15835d560f9e1395f1812233d5e905c900971c2680017e88487e098e4578ae8074d672986eb1b5466f38da2c19f4a34ad703315a30ef1e51c52993e4)
Referer: https://www.gbif.org/country/AM/publishing
Window size: width 1680 - height 559
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-16T08:37:55.784Z',mode:absolute,to:'2019-07-16T08:43:55.784Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-16T08:37:55.784Z',mode:absolute,to:'2019-07-16T08:43:55.784Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
the numbers now align
