### ISSUE TITLE
GBIF vs. GIBF

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#2107]
Dataset behind a new Scientific Data data paper has GBIF misspelled consistently as 'GIBF' in the description. Any chance we could get that fixed?
https://www.gbif.org/dataset/eb605c7a-a91c-4ab8-a588-85d0ccb2be9e#description

**Comment by ahahn-gbif** [comment]
Hi @SophiePamerlon, we got an issue flagged about a misspelling of GBIF as "GIBF" in three places in the description of https://www.gbif.org/dataset/eb605c7a-a91c-4ab8-a588-85d0ccb2be9e#description. Would you be the right person to ask for help with this? Many thanks!

**Comment by SophiePamerlon** [comment]
Hi @ahahn-gbif @kcopas, sorry about the delay, I received the notification for this while on holidays and I completely forgot to answer sooner! I just fixed the "GIBF" instances in the dataset description on our IPT and re-published it so it should appear correctly now. Please let me know if I can do anything else to help!
Best,
Sophie

**Comment by ManonGros** [comment]
Thanks Sophie!
