### ISSUE TITLE
That species is synonym to Myotis blythii

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2108]
**That species is synonym to Myotis blythii**

Reference: `https://www.gbif.org/species/2432414`

-----

User provided contact info: yves.bas@gmail.com
System: Chrome 75.0.3770 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/920af23356a4bce965dc9ab20fd11018:8bac750adaf3254d154136341ed78555b95a4da2b454ba5159cafb87ac070131c0dabb7755eb588c0560197007e44a5abe90db78931ce16c49f877c1deaed3cb)
Referer: https://www.gbif.org/species/4266394
Window size: width 1366 - height 608
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-16T19:35:17.070Z',mode:absolute,to:'2019-07-16T19:41:17.070Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-16T19:35:17.070Z',mode:absolute,to:'2019-07-16T19:41:17.070Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by yroskov** [comment]
Comment   should be send to ITIS.

**Comment by ManonGros** [comment]
it seems to be the case in the new backbone
