### ISSUE TITLE
Capture GIS Points into Another Source

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2109]
**Capture GIS Points into Another Source**

How can I pull the GIS points of the record as a layer, into another mashup, such as pulling it as a Tileset, WMS or Mapbox into Palladio?

-----

User provided contact info: mstanleybaker@gmail.com
System: Chrome 75.0.3770 / Mac OS X 10.14.0
User: [See in registry](https://www.gbif.org/api/feedback/user/dbe203e28d84edda44f10105381733ed:fc3e0f141350e23e4efe2ceea31463bb4c93edc53624b83681cff7fbd7d1d6e4c7527e5f4c98dbdc4f5c46c530a33f0d849c61aa5fb1404a21c9dbcba8cd07ce)
Referer: https://www.gbif.org/species/2441147
Window size: width 1574 - height 822
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-17T04:43:47.316Z',mode:absolute,to:'2019-07-17T04:49:47.316Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-17T04:43:47.316Z',mode:absolute,to:'2019-07-17T04:49:47.316Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
This is described in our documentation:
https://www.gbif.org/developer/maps

Hope that helps
