### ISSUE TITLE
Page gone missing: What is Darwin Core, and why does it matter?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#211]
**Page gone missing: What is Darwin Core, and why does it matter?**

Page&#39;s address is/was: https://demo.gbif.org/publishing/darwin-core

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
Reported by: @kbraak
System: Firefox 53.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/
Window size: width 1560 - height 998
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-12T13:32:50.226Z',mode:absolute,to:'2017-06-12T13:38:50.226Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-12T13:32:50.226Z',mode:absolute,to:'2017-06-12T13:38:50.226Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Drupal content that needs to be recreated as an article in Contentful: from this http://www.gbif.org/publishing/darwin-core
to the link @kbraak cited above

**Comment by MortenHofft** [comment]
I have mapped the menu and contentful
