### ISSUE TITLE
Make proper pluralisation possible for metrics

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2111]
**Make proper pluralisation possible for metrics**

Make proper pluralisation possible for metrics.
e.g. 1234 occurrences vs 1 occurrence

-----

User provided contact info: @mortenhofft
System: Chrome 75.0.3770 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/4cc8dbd203d7054e4dceaccc35817632:ce9adc919add73a6c764ab70a362ea32be71d007b3ba034369ba6c6072abba57cb04407360bfaf703b21f1183a88a7e5eedba6c3839d8297242df3ed5db20c50)
Referer: https://www.gbif.org/country/RU/summary
Window size: width 1851 - height 1239
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-17T10:07:19.539Z',mode:absolute,to:'2019-07-17T10:13:19.539Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-17T10:07:19.539Z',mode:absolute,to:'2019-07-17T10:13:19.539Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Arabic and Russian have some relatively complicated (compared to English) rules around this.

https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html

https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals

**Comment by MortenHofft** [comment]
Thanks @MattBlissett  - that is already in place. Just not on the country page.
