### ISSUE TITLE
enum mismatch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2115]
**enum mismatch**

DATA_CURATION_&_QUALITY
vs.
DATA_CURATION_QUALITY

should I correct in Contentful or?

-----

User provided contact info: @dnoesgaard
System: Chrome 75.0.3770 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/5ade3ab25f2e64b79ae666318fa9b5bf:298dd72c9a40ca9927b066c24dd5b6984751239f8aefcce0e4564bf36e0b93503bfc789bd8024f99ecf29e043bd50f435c08bc8d4258697c4771c637f96a4814)
Referer: https://www.gbif.org/resource/search?contentType=project&purposes=DATA_CURATION_%26_QUALITY
Window size: width 2495 - height 1204
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-22T09:41:31.287Z',mode:absolute,to:'2019-07-22T09:47:31.287Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-22T09:41:31.287Z',mode:absolute,to:'2019-07-22T09:47:31.287Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
That would be the easiest as far as I can see (else translations is lost). As far as I remember this term keeps changing - I'm not sure why honestly, but I have adapted code to match it in the past. The code that index it in ES also rewrite some terms, perhaps that has been the reason in the past.

**Comment by ahahn-gbif** [comment]
I am not sure what we could do from the data content side - this is portal UI, and looks from earlier comments as though the change you suggest is the right solution.

**Comment by dnoesgaard** [comment]
Yeah I don't know why this was tagged data content.

**Comment by dnoesgaard** [comment]
fwiw, I can still can't figure out why "enums.cms.vocabularyTerms.purposes.DATA_CURATION_&_QUALITY" shows up in the facets when the count is 0?
