### ISSUE TITLE
More dropdown  on country pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2121]
**More dropdown on country pages**

The dropdown links to projects despite there isn't any. I would suggest we only show that menu item if we have content.

The dropdown more shows 2 links to publications. I would suggest those simply took you to the literature search pages. Now that this page has been split into 2 links it is silly to show a custom page with a link to the actual literature search pages.

little thing: do we really want `MORE...` and not just `MORE`?

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/f061de86be92bd71c67d1220fe3d59bd:b50c597611402efc119e43353db4da8a89184dd8fdb6e1cff2e59bb833d02fab4ba18b05fbe128852828d1f351c370154ec06b567a4ab76677609a150a03ef31)
System: Chrome 75.0.3770 / Mac OS X 10.14.5
Referer: https://www.gbif.org/country/AM/publications/from
Window size: width 1304 - height 766
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-24T10:48:13.473Z',mode:absolute,to:'2019-07-24T10:54:13.473Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-24T10:48:13.473Z',mode:absolute,to:'2019-07-24T10:54:13.473Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
These changes were made based on to https://github.com/gbif/portal16/issues/1168

> The dropdown more shows 2 links to publications. I would suggest those simply took you to the literature search pages. Now that this page has been split into 2 links it is silly to show a custom page with a link to the actual literature search pages.

Disagree. I would personally like to stay within the country context and be able to navigate within this without using the browser back button.

The publications page has by the way not changed or been split into two. Theres just two new menu items pointing at it with preselected from/about param as per requested in https://github.com/gbif/portal16/issues/1168

**Comment by MortenHofft** [comment]
> The publications page has by the way not changed or been split into two

No, but it `has been split into 2 links`. The reason I bring it up is because I don't like it as it was either. It has very limited functionality and instead links to the literature search if you need more. I would think it is easier to use if it just linked to this in the first instance. 

The new version also has 2 urls, but the toggle do not affect it.

But of course this is just my intuition.
