### ISSUE TITLE
On the frontpage peer-reviewed papers using data: 0

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2124]
**On the frontpage peer-reviewed papers using data: 0**

If the API is unavailable or returns zero, hide this cout

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/498b0cb3b405553421412346f0a7d8dc:8541f4899776fdd615874b04932ff6741a412743ea99fac1d53ba30e008eca30dbc62349ee47947cef23af077dee2f897531fee76b946215a4520fecf5fa26f7)
System: Chrome Mobile 75.0.3770 / Android 8.0.0
Referer: https://www.gbif.org/
Window size: width 360 - height 269
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-25T11:11:11.192Z',mode:absolute,to:'2019-07-25T11:17:11.192Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-25T11:11:11.192Z',mode:absolute,to:'2019-07-25T11:17:11.192Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I don't see any reason to hide this. If the API returns 0, then what else to do. The API do not return an error. It returns zero results. I agree that it would be nice to inform the user that there is something wrong, but I'd rather that we used the health check to do so. Making assumptions about what the API should return in terms of counts throughout the interface is annoying. And if so we should also hide occurrences and dataset counts if we believe those counts are wrong. I'd rather trust the API for this.

Please reopen if needed
