### ISSUE TITLE
Add additional free text input request under "What and how" (help Nodes to better judge an endorsement request)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2125]
**Add additional free text input request under &quot;What and how&quot; (help Nodes to better judge an endorsement request)**

Context: This is part of some changes that are requested by the NSG for the endorsement workflow. The changes should make it easier for a Node to understand the actions required on receiving an endorsement email ("A new Organization requires endorsement"). The mail should contain some more information, supplied by the prospective new publisher, about the data they intend to publish, and at the very least open to further dialog about the appropriateness of the application if there still is doubt.

Change requests:

- [x] `https://www.gbif.org/become-a-publisher,` "What and how": add a free text entry field, with a header of "What kinds of relevant data do you have that you intend to publish through GBIF? Please give a brief description."
- [x]  the content entered here by the registering institution can be concatenated into the same registry comment field that also the other additional information from this form section (check box and radio button responses) is stored in. The only purpose is to add it to the email that is sent out to the node automatically. Otherwise, it should not be made public
- [ ]  check that the content of the free text field becomes part of the mail sent out by the registry to the node

- [x] Also, correct a minor typo in the information already inserted into the registry comment: "OccurenceData" should be "OccurrenceData" with 2 r

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a14849f1ddd6f4b25b8c434547d46043:43ba5629b8efc14c1bf2d0bd21001b42edaf39750eeb6c69dfbe6c9c6fc8c5da822a18e30eca80e14c17901369254e5eee496bd38c5277c273556632cf1d1c8d)
System: Firefox 68.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/become-a-publisher
Window size: width 1153 - height 809
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-25T14:07:02.110Z',mode:absolute,to:'2019-07-25T14:13:02.110Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-25T14:07:02.110Z',mode:absolute,to:'2019-07-25T14:13:02.110Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
@MortenHofft: not so much an idea as a change request, to be proposed at the NSG meeting next week

**Comment by MattBlissett** [comment]
> Otherwise, it should not be made public

Note that these comments *are* public, though we don't display them on the website. For example, https://api.gbif.org/v1/organization/9c947337-58c9-46cc-9848-605fea969660

**Comment by MortenHofft** [comment]
@ahahn-gbif 

> check that the content of the free text field becomes part of the mail sent out by the registry to the node

It is added to the comment field as you describe. if comments are normally included in the email, then the new data will be included as well I suppose. Is that the case (that comments go out in the email)?

**Comment by ahahn-gbif** [comment]
Yes, this comment goes out as part of the email. Given that it is a new registration, we assume that no other comments exist at this point. If there were two comments, I am not sure whether they would both be added (@MattBlissett ?)

**Comment by MattBlissett** [comment]
All comments are shown, though it's correct that there is only ever one.
