### ISSUE TITLE
Text changes for the automated endorsement email

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/portal-feedback#2126]
Relates to #2125 - changes requested for the endorsement workflow
Context: automated endorsement email going out from the registry to the selected Participant node, titled "A new Organization requires endorsement"

- - [x] Between the second paragraph of text of the email ("A new organization is requesting to be endorsed by [Node]" plus "[Organization name]") and the institutional data, insert this text:

"To help you decide whether to endorse this organization, consult our endorsement guidelines [link to https://www.gbif.org/endorsement-guidelines] and the information included below. If you are ready to endorse, you can go straight ahead, using the link at the bottom of this email. If the process takes longer, if you cannot take it on at this time, or if you decide against endorsing the organization, please notify us by email to helpdesk@gbif.org.

Please remember our commitment to prospective publishers, and respond to this endorsement request as soon as possible, and within a maximum of 30 days."

(Possibly repeat the [organization name] after that, as the first line of the address block.)

- - [x] Remove the last paragraph/line of the mail that reads "If you have any questions start by consulting our endorsement guidelines." - this is now included at the top

- - [x] Make sure that the "Additional Information" block also contains the new textual information requested from the applying organization (#2125)

- - [x] The two paragraphs above, starting from "If you wish to endorse [organization name] (...)" up until "(...) and a short explanation.", replace with the following:

"Click here to endorse the [organization name]: ENDORSE [hyperlink to the registry endorsement under "ENDORSE"]
If you do NOT want to endorse this organization, please send an email to helpdesk@gbif.org, including a copy of this message and a short explanation."

**Comment by ahahn-gbif** [comment]
@timhirsch @ManonGros @melianieraymond: could I please ask you to sanity-check that this captures what we decided today? Many thanks!

**Comment by MattBlissett** [comment]
(Was this something you wanted done, or to wait for further discussion with the NGS?)

I made changes to the email template here: https://github.com/gbif/registry/commit/927090b5f90bc2661b7b1cd2da96d2c54f6f19b3

The whole email template is here: https://github.com/gbif/registry/blob/master/registry-ws/src/main/resources/email/confirm_organization_en.ftl

Assuming Morten implements #2125 by adding an additional comment, or extending the existing comment, that will appear without further changes to the registry.

**Comment by ahahn-gbif** [comment]
Confirmed - closing
