### ISSUE TITLE
CC BY interpreted as CC BY-NC?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2127]
**CC BY interpreted as CC BY-NC?**

Just noticed that an occurrence with

"license": "`http://creativecommons.org/licenses/by/4.0/`"

becomes

"license": "`http://creativecommons.org/licenses/by-nc/4.0/legalcode`"

when interpreted.

Why is that?

(all iNat records appear as CC BY-NC for this reason, I believe)

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/5b44ff82b4e9be27f829610c4e052c2b:eff6d88097830a15d2d888bb6511df24468d97f704f87aa2be623aaeef462cdf010d73bb27fd0f080e308ba37e4971633c30e0f81004f5986f77fb62788acbb3)
System: Chrome 75.0.3770 / Mac OS X 10.14.5
Referer: https://www.gbif.org/occurrence/2283253659
Window size: width 1440 - height 696
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-25T17:59:40.446Z',mode:absolute,to:'2019-07-25T18:05:40.446Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-25T17:59:40.446Z',mode:absolute,to:'2019-07-25T18:05:40.446Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

**Comment by MattBlissett** [comment]
GBIF only recognizes the dataset license, and iNaturalist is provided to us under CC-BY-NC license.

#549
