### ISSUE TITLE
csv download and absence data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2128]
**csv download and absence data**

A GBIF publisher and user pointed me out to the following issue: this query `https://www.gbif.org/occurrence/download/0017389-190621201848488` results in a large number of records with absence data that can be identified in a DwC file download by occurrenceStatus column.
But if the user asks to download in csv format, he has no means to identify which records are absence, because occurrenceStatus is not included. Shouldn't occurrenceStatus be included in csv download format?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6a25f68417f83bb0a5e69e97248b10e4:b5d72036584faa7159fc66ea623dd36ec4aa51fb6babebb0558589e03a0b534d924a7e2ef51d932bdb6210f38a34ab22fde0ec314f444ac12ad285a46539d9ca)
System: Firefox 68.0.0 / Fedora 0.0.0
Referer: https://www.gbif.org/occurrence/download/0017389-190621201848488
Window size: width 1600 - height 722
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-26T13:26:42.656Z',mode:absolute,to:'2019-07-26T13:32:42.656Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-26T13:26:42.656Z',mode:absolute,to:'2019-07-26T13:32:42.656Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
related maybe? https://github.com/gbif/portal-feedback/issues/1168
