### ISSUE TITLE
No answer after registration form was sent

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2131]
**No answer after registration form was sent**

Dear colleagues, a couple of weeks ago i have registered a new publishing organization from Russia, West Siberia ("Regional historical, cultural and ecological center"). We have not received an answer and i am worried if it is ok. Please, would you be kind to respond about this registration to me (as a technical contact).

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ce0ed84e2677f5a510b2d073d0af7e36:ea7ee791dba61b00b040c74b207f448b5b06b3ccc7a32b907144f4bdb85db6fa3b90e81b48020b38f9b97206d8c19ec5c4cb0e771e77d8508898c36636bb57b1)
System: Chrome 75.0.3770 / Windows 7.0.0
Referer: https://www.gbif.org/
Window size: width 2000 - height 946
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-27T05:23:50.646Z',mode:absolute,to:'2019-07-27T05:29:50.646Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-27T05:23:50.646Z',mode:absolute,to:'2019-07-27T05:29:50.646Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
I am sorry you did not get a reply yet, Nina. We have received your registration. Registrations of new publishers from Russia presently go through a community endorsement process that has not been concluded yet. I would agree, though, that you should expect a notification that your registration was received, even or especially if the process takes longer than expected. We will see what needs to be done to improve on that. Meanwhile, please hang in a bit longer, while we check on the status.

**Comment by ahahn-gbif** [comment]
Endorsement received 6.8.19
