### ISSUE TITLE
Linnaeus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2133]
**Linnaeus**

`https://www.gbif.org/species/5784980`
Name "Linnaeus" misspelled.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/da2ef59b1cde066899db95711d8fe791:cb50428cb44eec2920dd9c8ca634cfa55991afa5dc290eb0e9e523e380cf7e13cd48a4206599d3b96e6f40420497fc481bf15e4ce9144335d304603870b3727b)
System: Firefox 68.0.0 / Mac OS X 10.9.0
Referer: https://www.gbif.org/species/5784980
Window size: width 1174 - height 782
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-28T02:15:38.612Z',mode:absolute,to:'2019-07-28T02:21:38.612Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-28T02:15:38.612Z',mode:absolute,to:'2019-07-28T02:21:38.612Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Ironically, it's in the Swedish national checklist. Probably just fatigue: "Oh, for crying out loud, this guy ***again***!?!"

**Comment by ManonGros** [comment]
The name seems correctly spelled in the new backbone.
