### ISSUE TITLE
? curvirostris

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2134]
**? curvirostris**

`https://www.gbif.org/species/7676623`
Volume 21 (1809-1810) of Shaw's Miscellany says Cuculus curvirostris.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/62cd443a21882d527a22558be0b4c8ef:9cd268698a349537b8a8a746e8d0373063b57930027b5c185c6de4855abc7a87658681e54e12fc503682e1a08d8975649d9dd346e27c8df9dec43b6d932e633c)
System: Firefox 68.0.0 / Mac OS X 10.9.0
Referer: https://www.gbif.org/species/7676623
Window size: width 1174 - height 782
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-29T23:07:05.198Z',mode:absolute,to:'2019-07-29T23:13:05.198Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-29T23:07:05.198Z',mode:absolute,to:'2019-07-29T23:13:05.198Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Thank you for reporting these issues on taxon names. Updates will take a bit longer, as they are not just text edits, but need to go through the processes of the names data providers. But your feedback is registered, and much appreciated.

**Comment by ManonGros** [comment]
https://www.gbif.org/species/11306087
