### ISSUE TITLE
wrong number of occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2136]
**wrong number of occurrences**

We have published a dataset with 11396 occurrences.
On the homepage appears as 8384 occurrences with wrong date.
Appears only 26% (3012) with year.
But the date is correct in 100% of the occurrences in the DwC file.
`https://www.gbif.org/dataset/a98a63c9-206f-467b-9f85-40f4fa22599f`
Please, something is wrong.
Thank you

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6bc33c62925bd1ee1cb24fa653d4a8e8:cc7492bcbce87626481848254283c357f2d1395a8998d932bacf38981defde0c0cf6b4b0e7ca3ceb3e53b433b9606c64f5e1a720806faca26bdcf770fda40fb8)
System: Chrome 75.0.3770 / Windows 7.0.0
Referer: https://www.gbif.org/dataset/a98a63c9-206f-467b-9f85-40f4fa22599f
Window size: width 2048 - height 899
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-30T13:11:00.770Z',mode:absolute,to:'2019-07-30T13:17:00.770Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-30T13:11:00.770Z',mode:absolute,to:'2019-07-30T13:17:00.770Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Incorrect date format -- replied by email.
