### ISSUE TITLE
Re-write the "endorsement guidelines for community-level endorsement"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2137]
**Re-write the &quot;endorsement guidelines for community-level endorsement&quot;**

Based on the decisions in the the NSG teleconference, July 31, 2019, the lower section of the text at `https://www.gbif.org/endorsement-guidelines` needs to be re-written to reflect the following points:

1. the NSG will no longer aim to identify an endorsing node to delegate the decision to
1.a - if there is an obvious node, like SPREP for Oceania, GBIFS aims to re-route the endorsement request from the start
1.b - as before, all endorsements through this workflow will be in the name of the "Participant Node Managers' Committee"

2. the community endorsement email will now be sent only to the _regional representative and their deputy_, CC the Chair of the NSG. **A single "Yes"** from either the regional representative or the deputy **will be sufficient** for endorsement

Related points to check:
- [x] update the content of the automated registry email with the same changes as for the mails going out to a Node; esp.: include a clickable link to ENDORSE  (see #2126)
- [ ] document the GBIFS-internal workflow (email forward to appropriate contacts from https://www.gbif.org/contact-us/directory?group=nsg) - transferred to #2148

-----

User: @ahahn-gbif
System: Firefox 68.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/endorsement-guidelines
Window size: width 1259 - height 555
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-31T13:10:42.397Z',mode:absolute,to:'2019-07-31T13:16:42.397Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-31T13:10:42.397Z',mode:absolute,to:'2019-07-31T13:16:42.397Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
text draft, to replace the section starting from "Endorsement guidelines for community-level endorsement by the Nodes Steering Group" at https://www.gbif.org/endorsement-guidelines:

**Endorsement guidelines for community-level endorsement by the Nodes Steering Group**

For cases in which a prospective data publisher is in a country not yet participating in GBIF, and has no connections with an existing Participant node, the Secretariat will write to the holders of the following positions in the NSG to request community endorsement:

1. Regional Representative
2. Regional Deputy Representative
3. NSG Chair (cc:)

The respective Regional Representative and the Deputy Regional Representative will be furnished with the completed questionnaire from the prospective publisher as well as the guidelines and criteria for endorsement. A single vote (confirmation) of endorsement will be considered sufficient.

The NSG post holders through their chair may endorse a prospective publisher if both the Regional Representative and the Deputy Regional Representative become unresponsive to GBIFS and NSG communications, or fail to complete the endorsement procedure in reasonable time.

In situations where a Regional Representative has not been appointed, or where the prospective publisher has a natural affinity to a thematic Participant node, the Secretariat will verify association with this alternative endorsing node in advance of initiating community endorsement, and give it preference if approved by the prospective publisher.

All endorsements that will be done through the NSG will be regarded as endorsements by the Nodes Committee and only the collective name, ‘Participant Node Managers Committee’, will appear on the GBIF website as the endorser.

If a country joins GBIF and there are existing publishers endorsed by the Nodes Committee, endorsement will be transferred to the new national node.

The criteria and guidelines for community-level endorsement are the same as those for national-level endorsement.


@melianieraymond: could I ask you to review, please?

**Comment by ahahn-gbif** [comment]
Content reviewed and updated at https://www.gbif.org/endorsement-guidelines (thanks @dnoesgaard)

**Comment by ahahn-gbif** [comment]
Last open reminder transferred to issue - closing
