### ISSUE TITLE
Question concerning Tetranychus evansi Baker & Pritchard, 1960 occurrences in Finland

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2140]
**Hi there, there are 8 records of Tetranychus evansi Baker &amp; Pritchard, 1960 for Finland. Because these greatly extend the species distribution to the north, it would be important to know: 1- certainty of identification?, 2- where were these found, outdoors or in greenhouses? 3- on what plant hosts? The links to the records ID do not work. Would you be able to answer these questions and/or put me in contact with the originator? many thanks! Stephan**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5df345c4ccf7a1250cb156ef5ea4aae6:15a76c8126b5f6a5da5621c5135a719a69d807d39727c6790dea79c02206d4ddb7898072f977d7772f035f736fadec0da3480a0c80be609fc783cf3d85563e14)
System: Edge 18.17763.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1607710970
Window size: width 1024 - height 460
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-02T02:11:53.469Z',mode:absolute,to:'2019-08-02T02:17:53.469Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-02T02:11:53.469Z',mode:absolute,to:'2019-08-02T02:17:53.469Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: b84a3711-b4ca-4e4f-adac-80dfaea98d1c
publishingOrgKey: 04fd2e13-6881-4e5c-9dd1-8fdd9ab993c1

**Comment by ManonGros** [comment]
I couldn't find the corresponding occurrences on https://laji.fi/
(the links to the original data don't seem to work either, see for example: http://tun.fi/MHU.30343216).
I contacted the current IPT Administrator and the FinBIF Node manager about it.

**Comment by ManonGros** [comment]
The links are back online and I notified the user by email.
