### ISSUE TITLE
Genus Piophila belongs in Piophilidae

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2141]
**Genus Piophila belongs in Piophilidae**

I am not sure why "Piophila" was moved to Lauxaniidae (it used to be in the right place), but I think it must be a coding error.

See (for example):
Zajak et al. 2016. Molecular identification and phylogenetic analysis of the forensically important family Piophilidae (Diptera) from different European locations. Forensic Science International 259: 77-84. `https://doi.org/10.1016/j.forsciint.2015.12.024`

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/56fbf00130df69a84d3eaa4f20b02b0b:1489f049215b9a4401d1a2231fd3320a77bdd85591a76978f7a5a5d879cbeed7c293b1739e2892b6331bc97c02d115c4d477d6236180474fecec933609ed5134)
System: Firefox 68.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/1444550
Window size: width 1680 - height 914
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-03T20:49:16.433Z',mode:absolute,to:'2019-08-03T20:55:16.433Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-03T20:49:16.433Z',mode:absolute,to:'2019-08-03T20:55:16.433Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by Psilopa** [comment]
This error is not limited to Piophilidae, it is a wider problem and seems to follow this rule:

Many, perhaps most genus names that are nominotypical for family level names in Diptera (like  Piophila for Piophilidae etc. ) are erroneously linked to wrong families. I am not sure of the pattern, but it may follow some ancient 18th century classification.

This is pretty nasty as in many cases these genera hold some of the better known species of each genus, and/or a majority of species in a family are incorrectly placed (genus Tipula is listed as a culicid mosquito...).

For example Drosophila melanogaster is currently not recognised as a drosophilid by GBIF! D. melanogaster is listed as a lauxaniid: https://www.gbif.org/species/5073713 .

I have spotted at least the following mistakes in the placement of type genera of corresponging families. Looks like *all* the Diptera nominotypical general should be checked:
* Drosophila  (https://www.gbif.org/species/1522683) is listed in Lauxaniidae
* Musca (https://www.gbif.org/species/8097933) is listed in Syrphidae
* Anthomyia  (https://www.gbif.org/species/1480567) is in Scathophagidae
* Anthomyza Fallén, 1810 (https://www.gbif.org/species/1475907) is in Scathophagidae
* Tipula Linnaeus, 1758 (https://www.gbif.org/species/1446543) is in Culicidae.
* Chlorops Meigen, 1803 (https://www.gbif.org/species/1489152) is in Lauxaniidae.

and so on...

Cheers,
Jere Kahanpää

**Comment by ManonGros** [comment]
This issue seems to have been corrected in the newest backbone taxonomy.
