### ISSUE TITLE
Possible misspelling of Holotype

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2144]
**Possible mispelling**

We received an email on helpdesk:
> Elymnias nesaea lioreli - I believe this is a MIS-spelling; it is lioneli, not lioreli
> `https://www.gbif.org/species/9210186`

Since 36 out of 37 occurrences on GBIF have the name lioneli and not lioreli (https://www.gbif.org/occurrence/search?issue=TAXON_MATCH_FUZZY&taxon_key=9210186), I contacted the NHM and asked them if they could check the name (via [their system](https://data.nhm.ac.uk/dataset/56e711e6-c847-4f99-915a-6894bb5c5dea/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb/record/832731#markdown).)

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/7b0c8e30ecbae4b9209bb695f628a7a9:2dcccac914659246cc1d006a784893cc3312d46dcc85695a6aa49e19a2004f2c8f68fbfca642a49905598bd34b23214cd3213a37cfd224ac0c964437e3a1528a)
System: Safari 12.1.2 / Mac OS X 10.14.6
Referer: https://www.gbif.org/species/127193124
Window size: width 1969 - height 1026
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-05T10:45:41.010Z',mode:absolute,to:'2019-08-05T10:51:41.010Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-05T10:45:41.010Z',mode:absolute,to:'2019-08-05T10:51:41.010Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The subspecies is not included in the new backbone (as it was coming from the GBIF Type checklist).
