### ISSUE TITLE
I wrote earlier about a problem in formatting the dates. I replace the file with the correct information in IPT, but the problem has not been resolved in GBIF. Can you help me please? Thank you

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2145]
**I wrote earlier about a problem in formatting the dates. I replace the file with the correct information in IPT, but the problem has not been resolved in GBIF. Can you help me please? Thank you**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8e39dc628289dc79838db855b044d930:d36baaf9d619e00475c5ba5e48f188d89d7ffda8e33090c3e017a19b85a8a785b43761e1a87a6326703e4f473f6fb3d7f17e05c5ed8fe89809b1f04b65df5d91)
System: Chrome 75.0.3770 / Windows 7.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 2048 - height 964
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-05T17:29:15.939Z',mode:absolute,to:'2019-08-05T17:35:15.939Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-05T17:29:15.939Z',mode:absolute,to:'2019-08-05T17:35:15.939Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Relates to #2136.

**Comment by ManonGros** [comment]
replied by email.
