### ISSUE TITLE
Content of identifiedBy appears to be an XSS attempt or merely innocuous stamping, suggest such <script> be removed while processing & provider informed.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2146]
**Content of identifiedBy appears to be an XSS attempt or merely innocuous stamping, suggest such be removed while processing &amp; provider informed.**

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/3f6533ae07f3d87665653f690a5e3e47:f93ff8bd38d351c75a5602f245aa18828345b02146011db6e0be09caae98c164a4a823eb87b954d47fdb37360e8899e7e0fad133b42438e0604169aaa364772071896432057a146e1ce9556fc47ef871)
System: Chrome 75.0.3770 / Mac OS X 10.14.5
Referer: https://www.gbif.org/occurrence/1090576121
Window size: width 1409 - height 699
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-05T21:36:26.525Z',mode:absolute,to:'2019-08-05T21:42:26.525Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-05T21:36:26.525Z',mode:absolute,to:'2019-08-05T21:42:26.525Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 1064b787-c882-493e-b17d-4ffba363b776
publishingOrgKey: c47cd3b0-2178-4a4b-87a6-740b482970a9

**Comment by MattBlissett** [comment]
Thanks David.

It is innocuous stamping, it shows a Japanese cartoon and some computer game music, and affects only this one occurrence record.

It shows up on the institution's own website, which was presumably the real target for the attack.

I have informed the publisher. I'll delete the record from GBIF once they've seen the problem; it's safer for them to see it on GBIF.org than on their own site, which doesn't escape the HTML.

**Comment by MattBlissett** [comment]
Fixed (nice and quickly) by the data publisher :-)
