### ISSUE TITLE
deleting records in a dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2151]
**deleting records in a dataset**

Hi, I was changing some of occurrenceID in my dataset `https://www.gbif.org/dataset/4ba838f7-a61e-4bcd-ad2b-bdc01d6485ea#registration` for consistently in the original database. Unfortunately, the IPT system (or the GBIF?) merged the results of the first & the second upload. As a result, I have occurrences more than I expected. There are duplicates data in my dataset with different occurrenceID. Would you help me fix this issue? I try to google it and read the IPT manual, but I don't find the solution yet. Thank you for your help.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2936a674edee3f63d5e45e43159421a6:adeb910bfa4075efc4a636b4817d24495d4c3a28b5c7be8d9098b12951c2245d36234c0d1da4187cd6fb16b0e75b37a2873bd6ce0f3e19a172a82a07a331ab85)
System: Chrome 75.0.3770 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/4ba838f7-a61e-4bcd-ad2b-bdc01d6485ea
Window size: width 1366 - height 608
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-09T10:41:29.335Z',mode:absolute,to:'2019-08-09T10:47:29.335Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-09T10:41:29.335Z',mode:absolute,to:'2019-08-09T10:47:29.335Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The over-ingested records have been deleted automatically.
