### ISSUE TITLE
Validator doesn't report invalid EML file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2154]
**Validator doesn&#39;t report invalid EML file**

I tried to test the DwCA for this dataset:
`https://www.gbif-uat.org/dataset/44386cd3-9510-47ea-9bb5-4efd5ff6cbd1`
Its EML is invalid but the validator doesn't catch it.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/71a19a4a521ac3e32373d216db7f25c8:49340ee937831c673b9e183c25e22e1481f6779393067ecf55b27a9508c5c0fdfcce7e6a5b171c63313025a7a935743378269163e272af55321a5f69f24e7c59)
System: Safari 12.1.2 / Mac OS X 10.14.6
Referer: https://www.gbif.org/tools/data-validator/1562926583024
Window size: width 1493 - height 892
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-12T12:39:25.712Z',mode:absolute,to:'2019-08-12T12:45:25.712Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-12T12:39:25.712Z',mode:absolute,to:'2019-08-12T12:45:25.712Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by muttcg** [comment]
Link redirects to page 404
