### ISSUE TITLE
name conflict

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2158]
**name conflict**

These two listings can't both be right (“Accepted”):

`https://www.gbif.org/species/2480169`
Glossopsitta porphyrocephala (Dietrichsen, 1837)

`https://www.gbif.org/species/9143066`
Parvipsitta porphyrocephala (Dietrichsen, 1837)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/53021966a9e9866e79ee2c69f91ed6dc:3929655679b3b9b21bc07342c41518edee7e82cfafd6eee60faaa32326e0599ffb68d98eddd8fd5c4b58022c4100e8e4067d5689463bd45588f8fc7223cc2861)
System: Firefox 68.0.0 / Mac OS X 10.9.0
Referer: https://www.gbif.org/species/9143066
Window size: width 1193 - height 782
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-15T20:38:36.996Z',mode:absolute,to:'2019-08-15T20:44:36.996Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-15T20:38:36.996Z',mode:absolute,to:'2019-08-15T20:44:36.996Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
https://www.gbif.org/species/9143066 was deleted and the genus Parvipsitta (https://www.gbif.org/species/4851231) is a synonym of Glossopsitta in the newest taxonomy so I guess this solves the issue.
