### ISSUE TITLE
occurrence search dataset tab does not add a dataset filter

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#216]
**occurrence search dataset tab does not add a dataset filter**

I would have expected to add a dataset filter when following the occurrence search dataset tab results

-----
fbitem-367fbea4afd888a3d8e33ed9130e11ce8143be62

System: Chrome 58.0.3029 / Mac OS X 10.12.5
Referer: https://demo.gbif.org/occurrence/datasets?media_type=StillImage&taxon_key=6920
Window size: width 1665 - height 845
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-14T07:01:16.922Z',mode:absolute,to:'2017-06-14T07:07:16.922Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-14T07:01:16.922Z',mode:absolute,to:'2017-06-14T07:07:16.922Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
The idea of that tab is to show all the datasets and publishers who publish data for that filter.

* Maybe a different name for the tab? 
* Instead of linking to the dataset it could also add the clicked dataset as a filter instead? 

Either way an explanation in the top about what you are looking at sounds useful.

**Comment by mdoering** [comment]
or link to both the dataset and a restricted occurrence search with a new dataset filter? Not sure whats the most intuitive, but I did expect to stay in the occurrence search and not to see the dataset details

**Comment by MortenHofft** [comment]
Makes sense - similar for species tab then. I often find that scenarios where i want to stay within search, but has to click the item (occ/species/dataset), only to click on the "xxx.xxx occurrence" and to come back to search. 

Maybe a general option to add values as filter. clicking the scientific name in the occurrence table fx.

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/444
