### ISSUE TITLE
How I can predict species occurrences under future climate change Scenarios?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2161]
**How I can predict species occurrences under future climate change Scenarios?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/56d67528c056e93a5d2e39f98f21bd8c:8370b6e922431ee7eec401f3696833b0be81937951589275cea7d0a5421ad352b4d4deabf3bfc88bd0911f40e348de19c085be3abb9ab31de25a6ad5fcc9fc38)
System: Chrome 76.0.3809 / Windows 7.0.0
Referer: https://www.gbif.org/faq?q=how%20I%20can%20predict%20species%20occurrences%20under%20future%20climate%20change%20Scenarios%3F
Window size: width 1366 - height 576
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-19T15:37:01.094Z',mode:absolute,to:'2019-08-19T15:43:01.094Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-19T15:37:01.094Z',mode:absolute,to:'2019-08-19T15:43:01.094Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
Replied by email.
