### ISSUE TITLE
Outdated map for the news item on the GBIF network

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2164]
**Outdated map for the news item on the GBIF network**

The news item at GBIF.org highlighting the GBIF network has old map, e.g. Belarus should be blue, possibly other countries are not correctly displayed, too - makes to replace the screenshot for the icon? The map is correct at the actual webpage when you click through.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2a385232c447bcf707943dd930c89ec9:76e597dd4fef70643c0ef00747c26e393dce93f70fe22a0d6b301ab19094c62cddef44b7d6b2bb392bd89efc645f2c474cc21a1b8f55d09000ae185ab917bc8d)
System: Chrome 76.0.3809 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 2048 - height 1019
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-20T07:45:02.239Z',mode:absolute,to:'2019-08-20T07:51:02.239Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-20T07:45:02.239Z',mode:absolute,to:'2019-08-20T07:51:02.239Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Is this the page in case https://www.gbif.org/news/2cbfQDD4ggKwkSEAeM0myO/top-tip-the-gbif-network-country-by-country-region-by-region

Personally I don't think it is desirable to update news items. They are time specific by nature. Counts, peoples positions, names, maps - it is all likely to change over time. I don't see any reason to update them. That is also why we have a datestamp on them.

**Comment by dnoesgaard** [comment]
I'll take this one, thanks.

**Comment by dnoesgaard** [comment]
Feature updated. (ping @dschigel)
