### ISSUE TITLE
Multimedia/Custom Info of Occurrence via API

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2168]
**Multimedia/Custom Info of Occurrence via API**

Looking at the online documentation, it does not seem as if the occurence response object contains the multimedia information of an occurence? How can I get this via the API? Also, will the Occurence response object include custom properties (if any) for the occurrences?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c42bcd553abee2a99d38acf3d7f73a92:4a912b8c7d2db640bb3994a36fc8860d59d42a6848cdeb151d234e15dfb57984cb00077b10f199c7f58fbdd58d65f87ac5801c5cbb3292280ac7967549f12084)
System: Chrome 76.0.3809 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-21T03:50:22.956Z',mode:absolute,to:'2019-08-21T03:56:22.956Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-21T03:50:22.956Z',mode:absolute,to:'2019-08-21T03:56:22.956Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
