### ISSUE TITLE
event date whats wrong?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#217]
**event date whats wrong?**

Hi, looking at the DwC terms quick guide we thought we formatted the date-interval correctly, the IPT did not protest at upload and I have a faint memory of the date being displayed correctly at an earlier time at gbif.org portal. could you please tell me what is wrong with our format so that we may correct it?

-----
fbitem-occurrence1229920640
Reported by: icalabuig@snm.ku.dk
System: Chrome 58.0.3029 / Windows 7 0.0.0
Referer: https://demo.gbif.org/occurrence/1229920640
Window size: width 1852 - height 1006
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-14T12:47:16.681Z',mode:absolute,to:'2017-06-14T12:53:16.681Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-14T12:47:16.681Z',mode:absolute,to:'2017-06-14T12:53:16.681Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 033ce57f-20a2-4d58-a1f6-c2f5a1f32c13
publishingOrgKey: 8e1a7b73-e746-4d20-a0ba-e647ce0f9784

**Comment by cgendreau** [comment]
The date format used is fine but date ranges are not supported at the moment.
The technical details are available here: https://github.com/gbif/gbif-api/issues/4

**Comment by MortenHofft** [comment]
Hi @cgendreau 
is there something that i should do in the weblayer or is this solely an API issue?

**Comment by cgendreau** [comment]
It requires to be fixed at the API level.

**Comment by ManonGros** [comment]
An other publisher wrote to the Helpdesk because the system does not accept date ranges when [the documentation states the opposite](http://tdwg.github.io/dwc/terms/#eventDate).
In addition to that, the validator doesn't flag the date ranges so the publishers do not understand why they get warnings once the data is ingested.

- Shouldn't we change the documentation? (at least while we do not have ranges)
- What about the validator?

**Comment by cgendreau** [comment]
If I remember correctly, the validator should already flag date ranges no? (they would be flagged as invalid which is not excellent but it should match what you have on the portal)

**Comment by cgendreau** [comment]
Yes, this is related to the Event core with an Occurrence extension. The GBIF crawler handles Occurrence extension [differently](https://github.com/gbif/crawler/blob/master/crawler-cli/src/main/java/org/gbif/crawler/dwca/fragmenter/StarRecordSerializer.java#L90) so the validator should probably do the same.

**Comment by MattBlissett** [comment]
Thanks all.

Date ranges like `2018-10-12/2018-10-18` or `1992/1994`, and single dates provided as a range like `2018-10-24/2018-10-24`, are now interpreted as the earliest date in the range (`2018-10-12`, `1992-01-01`, `2018-10-24`). (Ready in UAT.)  This is a step towards  full support of ranges, intended to fix the worst part of the current situation.

Examples: https://www.gbif-uat.org/occurrence/1314661942 and https://www.gbif-uat.org/occurrence/1113312922

I'm closing this issue, further discussion should be on https://github.com/gbif/gbif-api/issues/2 or https://github.com/gbif/gbif-api/issues/4
