### ISSUE TITLE
One sample event lasting 42 years spanning entire England

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2170]
**One sample event lasting 42 years spanning entire England**

EventId 1 seem to be everything. This looks like an error. Could be in our processing as well

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/3328e14da0c397e615d7688683e417cb:3cd0945768e16a7e7dfb5f2e626be47b08dd542bb5c7ce1a1efdc363e74b835e81679ab7616bc1c516a627b83486651892851daa7e0267336387c1987894fd09)
System: Chrome 75.0.3770 / Mac OS X 10.14.5
Referer: https://www.gbif.org/dataset/1e266c3d-92ef-4d5a-8e4a-c04742c772c3
Window size: width 1821 - height 1294
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-21T12:13:41.283Z',mode:absolute,to:'2019-08-21T12:19:41.283Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-21T12:13:41.283Z',mode:absolute,to:'2019-08-21T12:19:41.283Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Ahh - I see now that there are many like this. It is occurrence datasets that add an eventId to their occurrences. And since it doesn't make any sense they probably just write `1`. This makes them all appear like sample datasets in the interface.

**Comment by MortenHofft** [comment]
Having looked at 10 of these. Also with other eventIds that are clearly not sample data, they all come from NBN Atlas.

**Comment by ManonGros** [comment]
I contacted NBN Atlas by email.

**Comment by sophiathirza** [comment]
Many thanks for alerting us to this. There must be an error in how we populate the eventID field in the Archive file. I will report it to our developers and let you know when it will be corrected.

**Comment by ManonGros** [comment]
Thanks Sophie for fixing the issue.
