### ISSUE TITLE
Please let me know if there is a way of seeing the actual occurences on species maps rather than the dots indicating frequencies within boxed areas.  Thanks,  Trevor

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2172]
**Please let me know if there is a way of seeing the actual occurences on species maps rather than the dots indicating frequencies within boxed areas. Thanks, Trevor**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/72c48dd6a289c87a238305be5cd95b42:c0e04f16b46a382252c562593fdc6a8f175fc9ce95839f439c039888fb5ba78ca6f56c996a52aee66cde1b10fc6408eae53d86b2ded4a14f4a02d78acdf75c4a)
System: IE 11.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1404 - height 998
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-22T23:57:50.231Z',mode:absolute,to:'2019-08-23T00:03:50.231Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-22T23:57:50.231Z',mode:absolute,to:'2019-08-23T00:03:50.231Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
Replied by email:

> You can directly customize the map on the species page by using the tool box in the lower right  corner, you can select “Classic Points” for example (see screenshot below).

![map_customization](https://user-images.githubusercontent.com/7677271/63581042-631b2380-c596-11e9-843d-3627e2fb3dac.png)

> Alternatively, you can also click on “Occurrences” and browse the occurrences themselves.

> If you would like to go further, I suggest that take a look at [this blogpost](https://data-blog.gbif.org/post/gbif-maps-api-using-r-and-leaflet/). It gives a few examples on how to customize maps from GBIF using R and our map API.
