### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2174]
**Information**

Good morning,
I am a researcher and I would like to know if the Porpita porpita data tables can be used in scientific publications. If the answer is affirmative, how to quote the dataset?

Best regards

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c5c69a35c9a16cd3763c6f1d4525cd8c:eb958044efa2a892be8a7a3d70f62ae39e24043e0f282115032c4120a962f200655215c728f3894dc43a45647cfb53cea7fa94913ad3163b8d5eb695c38d44f2)
System: Chrome 76.0.3809 / Windows 10.0.0
Referer: https://www.gbif.org/faq
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-23T10:16:36.929Z',mode:absolute,to:'2019-08-23T10:22:36.929Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-23T10:16:36.929Z',mode:absolute,to:'2019-08-23T10:22:36.929Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
I would like to reply but I can't find his user profile (when I click on the "See in the registry" link, I get and `invalid token...` error.

**Comment by MattBlissett** [comment]
You need to log in to the website again.

**Comment by ManonGros** [comment]
Thanks Matt!
I replied by email.
