### ISSUE TITLE
P. eximius

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2176]
**P. eximius**

`https://www.gbif.org/species/7467188`

There's no question mark about it. Shaw's Miscellany for February 1792 (volume 3, signature mark K) calls it Psittacus eximius.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/dc3f79a31275feaf2851e6691a9a8ee1:5468301dea9318d58e0648373b52b4c95fa6f3e80012dcb4be04f4a76d04db9a56a947b4c852a11500c62ea2919c14a558d3aa1d8dc8329cd3dbfcb8adae83df)
System: Firefox 68.0.0 / Mac OS X 10.9.0
Referer: https://www.gbif.org/species/7467188
Window size: width 1232 - height 782
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-24T02:48:23.059Z',mode:absolute,to:'2019-08-24T02:54:23.059Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-24T02:48:23.059Z',mode:absolute,to:'2019-08-24T02:54:23.059Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ahahn-gbif** [comment]
This record is generated as technically necessary during data processing, see comments ("This record has been created during indexing and did not explicitly exist in the source data as such. Origin: Placeholder usage for a missing or implicit basionym."). Whether it should be exposed to data users in this form is questionable.

**Comment by ManonGros** [comment]
The records is now deleted: https://www.gbif.org/species/7467188
And Psittacus eximius is available in the backbone as a synonym: https://www.gbif.org/species/10046909
Closing the issue.
