### ISSUE TITLE
Palpada erratica (Curran, 1930) [/species/1533310] wrong synonymy

### ISSUE THREAD

**Issue by Psilopa** [gbif/portal-feedback#2178]
The name Palpada erratica (Curran, 1930) (https://www.gbif.org/species/1533310 ) is currently listed as a younger synonym of  Platycheirus hyperboreus (Staeger, 1845) (https://www.gbif.org/species/1542997). This is rather obviously incorrect.

Palpada erratica (Curran, 1930) should be treated as a valid species.

Reference: http://sd.zoobank.org/Nomenclator/Details/207849 (=Systema Dipterorum)

Cheers,
Jere Kahanpää

**Comment by yroskov** [comment]
Palpada erratica (Curran, 1930) is treated as a valid species in CoL: http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/b4e8d5c306f9565467c3bd646a53e32b.
 Platycheirus hyperboreus (Staeger, 1845) is an independent species: http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/56181e5887cba46c6e82900d2bd02d48

**Comment by Psilopa** [comment]
PS. These are Diptera ... does the "col" label also cover this order? :)

**Comment by yroskov** [comment]
http://www.catalogueoflife.org/annual-checklist/2019/details/database/id/101

**Comment by ManonGros** [comment]
Solved in the new backbone.
