### ISSUE TITLE
Incorrect recorder

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2180]
**Incorrect recorder**

This French dataset of the insects of Guadeloupe consistently labels occurrences of species described by Fabricius as being recorded by Fabricius. 

This is a variant of a problem plaguing many other datasets (SANBI's  IZIKO South Africa Museum Collection, Harvard MCZ and Smithsonian's NMNH) that list the person who described the species in the identifiedBy field. In both instances, I think this information should be included in scientificNameAuthorship.

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/9f99a7c51e40fb275291f7d028414b68:58abdb6bd56ab51a9c9b257923c0bb563a044c31e0dfaa5d9cf4be33115c386086dc51c84a59c0c9300dde3ee8643646624df4af9dd376e961b4a27552fa01cb)
System: Firefox 68.0.0 / Mac OS X 10.14.0
Referer: https://www.gbif.org/occurrence/search?dataset_key=e4526ee9-1592-4764-8af1-c89621255f82&recorded_by=fabricius&advanced=1
Window size: width 1606 - height 919
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-27T07:17:41.655Z',mode:absolute,to:'2019-08-27T07:23:41.655Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-27T07:17:41.655Z',mode:absolute,to:'2019-08-27T07:23:41.655Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Publisher contacted by email.

**Comment by ManonGros** [comment]
GBIF France fixed the issue.
