### ISSUE TITLE
Log links use wrong index

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2181]
**Log links use wrong index**

Ingestion log links go wrong
"AWDqIeCpf8lu3pmEHglJ" is not a configured pattern ID. Using the default index pattern: "AWyKwQsdHCKcR6PFVqgv"

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e7d49816a99100fc8d84903ae667fd0b:6909f6f4e15c8466f2fbe74d2549444e2e23e75e1e5ba0dde40b07749403180d679328c4ad248ca925b352768a6634117c3ab6be50bbe2a3c06ae881e4c10cdf)
System: Chrome 76.0.3809 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/e01b0cbb-a10a-420c-b5f3-a3b20cc266ad
Window size: width 1491 - height 821
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-27T13:59:10.065Z',mode:absolute,to:'2019-08-27T14:05:10.065Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-27T13:59:10.065Z',mode:absolute,to:'2019-08-27T14:05:10.065Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Apparently we change index names sometimes. What is the best way to link to the logs please?
