### ISSUE TITLE
aggregate data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2182]
**aggregate data**

Hi, the Auburn University Museum of Natural History has recently uploaded some data sets to the idigbio IPT and would like these data to be available in searches on GBIF.  What steps need to occur for this to happen?  

Thanks,
Curtis

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2668adfbac7cb8c87d9897d5af9b325c:a2abbce6572faaf50321b23ac84ab6285204ad3ff849af6e4bfb749cb988c77c95c9dde6ea3ca2c7d84e2079479bf838aaded132bddc66b74743193654afcd8f)
System: Chrome 76.0.3809 / Windows 10.0.0
Referer: https://www.gbif.org/user/confirm?username=hansecj&code=4f2f309c-e9f0-4046-b187-5591475ed722
Window size: width 1849 - height 916
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-27T21:29:12.911Z',mode:absolute,to:'2019-08-27T21:35:12.911Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-27T21:29:12.911Z',mode:absolute,to:'2019-08-27T21:35:12.911Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
