### ISSUE TITLE
Is it possible to retrieve a list of species from a given area?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2184]
**Is it possible to retrieve a list of species from a given area?**

For example, if the location and radius was specified in the api  request could a list of species be downloaded?

Many thanks

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/514a49ab43b530fc6c05bfdd078af637:53ab6b44a6e6d4536bf6e55d043dd16923bd1a00dc52a9512f317d4c9fe16b7018379b54eb490dbe64cd025937dc25112f3de9e620d67e1c82b63ffb65cbfbca)
System: Chrome 76.0.3809 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-29T16:30:10.320Z',mode:absolute,to:'2019-08-29T16:36:10.320Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-29T16:30:10.320Z',mode:absolute,to:'2019-08-29T16:36:10.320Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
