### ISSUE TITLE
export dataset citations?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2186]
**export dataset citations?**

I would like to compile a list to include in an annual report of all the datasets cited for our collection. Is there a way to do that? I see that I can get a list of lit citations for specific collections here:
`https://www.gbif.org/resource/search?contentType=literature&year=2018,2019&gbifDatasetKey=e3b959d6-fcbe-4a28-a166-e4a807c340a0&gbifDatasetKey=09c4287e-e6d5-4552-a07f-bff8a00833d8&gbifDatasetKey=0daed095-478a-4af6-abf5-18acb790fbb2&gbifDatasetKey=9ce52ff6-01b6-44a2-b617-9bc2ee8e8cd1&gbifDatasetKey=62ad511d-d298-4fd7-80e7-f5d5bd32299e&gbifDatasetKey=f3e4b261-00c5-4f3a-a5b7-d66075b7f3e1&gbifDatasetKey=f86f5466-8f18-4b83-84d4-d0edab4c0e90`

But cannot export the citations.
Thanks, MK

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/37f4772139ff340e5864fd430d00cf48:4e87d06f390c51067987604827edf5cfd0270edaeb002bfdfcaf41641ef5d0a02bf6eaf19b6de67c425f95dac13e3c95fb910aac82665e39f7f0c7df4628fda7)
System: Chrome 76.0.3809 / Windows 7.0.0
Referer: https://www.gbif.org/
Window size: width 1372 - height 912
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-29T21:55:03.985Z',mode:absolute,to:'2019-08-29T22:01:03.985Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-29T21:55:03.985Z',mode:absolute,to:'2019-08-29T22:01:03.985Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Hi 
Regarding literature tracking

The API is not guaranteed stable, but I don’t imagine it will change a lot. But be aware before you integrate it into a larger product. If so we should talk more about stability.
If you just need it for a single report, then I guess you do not have to care about stability.

Here are some examples of usage

Search for any literature item, go to page 3 show 10 items
https://www.gbif.org/api/resource/search?contentType=literature&offset=20&limit=10

Literature, no results but breakdown of 10 most frequent countries of the researcher
https://www.gbif.org/api/resource/search?contentType=literature&limit=0&facet=countriesOfResearcher

Literature from Portugal, breakdown on covered countries
https://www.gbif.org/api/resource/search?contentType=literature&limit=0&countriesOfResearcher=PT&facet=countriesOfCoverage

Known literature usages of the dataset https://www.gbif.org/dataset/231c5bcf-1b56-4905-a398-6d0e18f6de1a
https://www.gbif.org/api/resource/search?contentType=literature&gbifDatasetKey=231c5bcf-1b56-4905-a398-6d0e18f6de1a

Known literature from either of two publishers. If a citation is using datasets from both publishers the literature item will only count once.
https://www.gbif.org/api/resource/search?contentType=literature&publishingOrganizationKey=16e26fb0-7f13-4ae2-b57c-2543f451f5b3&publishingOrganizationKey=d1805d75-066e-42d6-8cab-1c0d30323db3

For the technical minded you can also see the calls made by looking at the network activity on the website
https://www.gbif.org/resource/search?contentType=literature&countriesOfResearcher=PT&gbifDatasetKey=231c5bcf-1b56-4905-a398-6d0e18f6de1a&gbifDatasetKey=79673413-746f-48f2-bd8a-7cf27807317e

Hope that it helps – else let us know.
Thanks

**Comment by MortenHofft** [comment]
So in your case: https://www.gbif.org/api/resource/search?contentType=literature&year=2018,2019&gbifDatasetKey=e3b959d6-fcbe-4a28-a166-e4a807c340a0&gbifDatasetKey=09c4287e-e6d5-4552-a07f-bff8a00833d8&gbifDatasetKey=0daed095-478a-4af6-abf5-18acb790fbb2&gbifDatasetKey=9ce52ff6-01b6-44a2-b617-9bc2ee8e8cd1&gbifDatasetKey=62ad511d-d298-4fd7-80e7-f5d5bd32299e&gbifDatasetKey=f3e4b261-00c5-4f3a-a5b7-d66075b7f3e1&gbifDatasetKey=f86f5466-8f18-4b83-84d4-d0edab4c0e90&limit=200

will give you all the citations you linked to.

**Comment by mkoo** [comment]
Thanks for the examples and reply!
