### ISSUE TITLE
Version for Nodes guide, guiding examples

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2187]
**Version for Nodes guide, guiding examples**

Hi, was looking for the new guide for Nodes, but one only realizes that this is ver. 2 from March 2019 when you download the PDF, the recomended citation does help. I also realized that guideing examples for Nodes are separate stories, is there a a way to connect the guide and the examples into a single easy to find page? `https://www.gbif.org/resource/search?q=nodes%20guidance.` The newly founded Nodes would likely benefit from such a compilation.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/62700f802a04df718ba5299f7714f00a:6c5706fc31aa0bd32b2fb7e6e64de73f62d6faa83bb4ccd92376750263f15efb98c00bd2a1c334d6b6ebae0d86bba0e5d878cce3c0a565309c6db5a92d8732c9)
System: Chrome 76.0.3809 / Windows 10.0.0
Referer: https://www.gbif.org/document/80925/establishing-an-effective-gbif-participant-node
Window size: width 1920 - height 1067
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-30T08:51:12.389Z',mode:absolute,to:'2019-08-30T08:57:12.389Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-30T08:51:12.389Z',mode:absolute,to:'2019-08-30T08:57:12.389Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Already being considered in https://github.com/gbif/doc-effective-nodes-guidance/issues/3
