### ISSUE TITLE
INSDC sequence data have basisOfRecord = PRESERVED_SPECIMEN

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2188]
**INSDC sequence data have basisOfRecord = PRESERVED_SPECIMEN**

More than half of these 4M records have basisOfRecord = PRESERVED_SPECIMEN whereas the other half = MATERIAL_SAMPLED yet there's no apparent difference in any these. They should all be MATERIAL_SAMPLED.

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/682b15cd394494ad9fdf67c7275c78bb:200a93e46f27f2d01db0472bbc2d8f51a71cf0cf982b1e240be6e1c941a945f5ea3461a55b1fb4422666939b0a6cafa43b890fc2e3644c282bc407d85f4186ce2a8eb19b4da33094672b34877f77f0c9)
System: Chrome 76.0.3809 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/ad43e954-dd79-4986-ae34-9ccdbd8bf568
Window size: width 1419 - height 669
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-01T15:13:14.707Z',mode:absolute,to:'2019-09-01T15:19:14.707Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-01T15:13:14.707Z',mode:absolute,to:'2019-09-01T15:19:14.707Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
My understanding is that the preserved specimens are sequence of preserved specimen. For example, [this record](https://www.gbif.org/occurrence/2286510262) comes from the Mycology, Musee National dHistoire Naturelle, 25 rue Muenster, Luxembourg L-2160, Luxembourg (see [link in EMBL](https://www.ebi.ac.uk/ena/data/view/MN151402)).
While the material sample, are sequences which are to coming from preserved specimens.

Anyone has any thought on what should be the basis of record for the [Geographically tagged INSDC sequences](https://www.gbif.org/dataset/ad43e954-dd79-4986-ae34-9ccdbd8bf568)?

**Comment by ManonGros** [comment]
closing since the conversation is continuing here: https://github.com/gbif/portal-feedback/issues/3009
