### ISSUE TITLE
Are measurementOrFacts data harvested by GBIF?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2189]
**Are measurementOrFacts data harvested by GBIF?**

The measurementOrFacts extension (`http://rs.gbif.org/extension/dwc/measurements_or_facts.xml)` is becoming increasingly important for sharing rich biodiversity data. Is this Darwin Core extension being harvested by GBIF and available via an API (for occurrence and taxon records)? And if not, is this on the roadmap?

-----

Github user: @peterdesmet
User: [See in registry](https://www.gbif.org/api/feedback/user/47c1e061286b0f582ffa29033155f64b:96a0ed4c3857b0d65e6076368e346d33072f070f186c817969bfcab0bad4aead79abd111fe0adf3b69ee3098f05d179b8bc97a279ede41ae9a8f29a84cabd465)
System: Chrome 76.0.3809 / Mac OS X 10.14.6
Referer: https://www.gbif.org/occurrence/895539280
Window size: width 1388 - height 681
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-02T19:50:20.935Z',mode:absolute,to:'2019-09-02T19:56:20.935Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-02T19:50:20.935Z',mode:absolute,to:'2019-09-02T19:56:20.935Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL
datasetKey: 5d637678-cb64-4863-a12b-78b4e1a56628
publishingOrgKey: 1cd669d0-80ea-11de-a9d0-f1765f95f18b

**Comment by MortenHofft** [comment]
It is currently only available through the fragment for individual occurrences
e.g. https://api.gbif.org/v1/occurrence/1949669416/fragment

It is on the roadmap to include it in the occurrence search index.
