### ISSUE TITLE
linking a dataset into existing publications.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2191]
**linking a dataset into existing publications.**

Dear Helpdesk,

I would like to know there is a way to put the existing publications related to a particular dataset?

I published a dataset (`https://www.gbif.org/dataset/4ba838f7-a61e-4bcd-ad2b-bdc01d6485ea)` in GBIF last month. There are some journals related to this data in this dataset but published before the dataset published in GBIF.

I want to make these journals accessible through GBIF too as part of the citations sections, like in this dataset:    
`https://www.gbif.org/dataset/81b551f9-3e4f-47b4-952e-56e870c1b363`

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bfc9ec83f6ce9203e3a4263bba729dc7:421fec51909cc7f210f557bda60ffa81c5eaaf6822218d7e433b316dbd7fa630834daa6954633f3b455d79f4fce8206634cbb987d4872950fccc018004d90643)
System: Chrome 76.0.3809 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-04T09:20:02.125Z',mode:absolute,to:'2019-09-04T09:26:02.125Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-04T09:20:02.125Z',mode:absolute,to:'2019-09-04T09:26:02.125Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi @dnoesgaard, could you take a look at this question? Is this something we can do? thanks!

**Comment by dnoesgaard** [comment]
Thanks @ManonGros, I'll follow up with the user by email :)
