### ISSUE TITLE
unable to see data set

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2193]
**unable to see data set**

Hi,
I have downloaded a dataset and clicked the link in my email. I followed the instructions to open it in an excel file, but the only think that shows up is the citation, where is the data?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/362167c7b8e8cd3b7ef878984e2850e7:55a1aad1f6cd667c1e17035573ea53ec13a3a0713f5a90107c40734b3b148d42ae63a1ea8af3649769fb8b838d8a97039991b9e756a37da72084864bdb6d3cbe)
System: Chrome 76.0.3809 / Windows 8.1.0.0
Referer: https://www.gbif.org/faq
Window size: width 1280 - height 580
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-05T07:38:32.217Z',mode:absolute,to:'2019-09-05T07:44:32.217Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-05T07:38:32.217Z',mode:absolute,to:'2019-09-05T07:44:32.217Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
