### ISSUE TITLE
measure range area

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2194]
**measure range area**

hi
there is option to measure area range on the map of occurrences?
thank you

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/08e4088d331b390851cda14485a48649:34bc94328ab2180acc0ae01da24a46cf2d9bac0a3db0bed7a322a13a7f523c6c627cc1c8b44707db5a536b0193a2fdca786bbe4b1fa123e4d4dad926c74c0a84)
System: Chrome 76.0.3809 / Windows 10.0.0
Referer: https://www.gbif.org/search?q=Lasiurus%20xanthinus
Window size: width 1821 - height 810
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-05T08:34:00.412Z',mode:absolute,to:'2019-09-05T08:40:00.412Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-05T08:34:00.412Z',mode:absolute,to:'2019-09-05T08:40:00.412Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
