### ISSUE TITLE
LInk to dataset homepage?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#22]
**LInk to dataset homepage?**

...a nice feature on the old portal was: LINKS
Dataset homepage, will it be implemetned here too?

-----
fbitem-dataset6867ae37-74b8-43e7-805d-5dac0a6d447e

System: Chrome 55.0.2883 / Windows 7 0.0.0
Referer: https://demo.gbif.org/dataset/6867ae37-74b8-43e7-805d-5dac0a6d447e
Window size: width 2048 - height 1024
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-06T14:47:59.285Z',mode:absolute,to:'2017-01-06T14:53:59.285Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-06T14:47:59.285Z',mode:absolute,to:'2017-01-06T14:53:59.285Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
The homepage link is hidden under the Origin tab. But I would second the request to present the homepage link on the dataset front page more prominently

**Comment by MortenHofft** [comment]
We have been back and fourth on this one and people seem to disagree. We all agree that it is important, but how prominent should it be. For some datasets it makes much sense, but for others it is dead links, links to sites about other stuff or links to an IPT site with the same information repeated. 

I wouldn't think that the link was "hidden" under the Origin tab. The idea at least was to make it clear that there was an origin and give that a full area to give proper credit in addition to highlighting the authors. But if it is experienced as something that is hidden away, it should probably be done differently. 

Being new to the existing GBIF.org I thought that the sea of blue links on the right made important things disappear. For example: origin and how to download for example a checklist. So I'm wondering if this is an example of a user that knows the site well and have been trained to look for the odd title LINKS searching for the homepage. I would imagine it was hard to find the first time around?

That said it might be a good idea to highlight the homepage link more, but I'm not convinced that it is more hidden now than it was before.

**Comment by gbif-portal** [comment]
Closed as duplicate of https://github.com/gbif/portal16/issues/219

**Comment by mdoering** [comment]
Morten, I totally agree the blue links section was dreadful and unable to differentiate between important and rather technical links. But I think a link to the homepage of a dataset - at least if its a real one - is a very important feature that means even more to publishers than a good citation.

Maybe we should follow a similar approach as for occurrence links where we show "Reference: LINK" in the sub-heading? https://demo.gbif.org/occurrence/1291160904

**Comment by kbraak** [comment]
+1 from me as well.

I initially suggested making the origin of the dataset more prominent on the dataset page of the new portal, because some publishers feel we don't do enough to redirect traffic to them. Traffic on their own website is important, otherwise their funders won't continue to sustain them. This is the case for Reef Life Survey for example, who has a [feature rich website](http://reeflifesurvey.com/) including several services for exploring and downloading their raw data. 

We should also keep in mind the publishers' own websites is where users can get the latest data (Reef Life Surver only publishes to GBIF biannually). The same can surely be said for eBird and other big projects.

**Comment by MortenHofft** [comment]
could we please have this conversation on the issue that isn't closed
