### ISSUE TITLE
Mini-typo (word switch) in "(...)aimed at providing anyone, anywhere to access data(...)"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#220]
**Mini-typo (word switch) in &quot;(...)aimed at providing anyone, anywhere to access data(...)&quot;**

On the entry page, the &quot;what is GBIF&quot; paragraph reads &quot;to access data&quot; when it should be &quot;access to data&quot;, as in https://demo.gbif.org/what-is-gbif

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
Reported by: @ahahn-gbif
System: Firefox 53.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/
Window size: width 1198 - height 801
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-20T13:24:11.667Z',mode:absolute,to:'2017-06-20T13:30:11.667Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-20T13:24:11.667Z',mode:absolute,to:'2017-06-20T13:30:11.667Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Correction is incorrect. The construction is that GBIF.org is+ 'aimed at providing anyone, anywhere access to data…' 

The verb would be wrong for the proposed change. An alternate would be 'aimed at enabling anyone, anywhere to access data…', but the current wording is better.
