### ISSUE TITLE
Icons disappear against white background on Chrome

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2202]
**Icons disappear against white background on Chrome**

When accessed on Chrome on a Macbook, the icons to the left of the login button (languages, feedback etc) are pretty much invisible on most pages apart from the home page because they
 drop below the green bar and appear against a white background. On Safari they are clearly visible against the green background.

-----
<img width="713" alt="Screenshot 2019-09-16 at 16 33 45" src="https://user-images.githubusercontent.com/17124772/64967273-7e7d0400-d8a0-11e9-8210-9212a53f0558.png">

User: [See in registry](https://www.gbif.org/api/feedback/user/8047c67de1636f7c6916487771d4883b:42c66e86a5e249b44a5ddd0a83f0bb784c8def804f63138b1bce72a22cb71bdac7be37d0a84eb38904f33e953ca29eff063a75ad53f7a42e31be78f2e7b41bc3)
System: Chrome 76.0.3809 / Mac OS X 10.14.6
Referer: https://www.gbif.org/occurrence/search
Window size: width 1440 - height 686
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-16T14:33:10.581Z',mode:absolute,to:'2019-09-16T14:39:10.581Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-16T14:33:10.581Z',mode:absolute,to:'2019-09-16T14:39:10.581Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
Thanks - for some reason chrome has changed how it renders the website. closed by https://github.com/gbif/portal16/commit/70db543743640bb39ca7dd773953dc94a83e6eaf
