### ISSUE TITLE
Artibeus intermedius should be synonym of Artibeus lituratus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2203]
**Artibeus intermedius should be synonym of Artibeus lituratus**

Artibeus intermedius (`https://www.gbif.org/species/4832182)` was "This record has been created during indexing and did not explicitly exist in the source data as such.
Origin: Generated, missing genus or species for ‘orphaned’ lower name."
According to one of our users, it should be a synonym of Artibeus lituratus (`https://www.gbif.org/species/2433270)` which seems to be confirmed by this subspecies from the CoL: `https://www.gbif.org/species/9031261`

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/4b68a5a418e9835b080104c74f42b0f8:cbdc33ff922619704008654adfb6a47ccddb0d39587c12e27f4b3a4488ee846b0e01cff03346dfa228f62d89a3e18aacade9a0dc51238c2ab691430f0b5c5757)
System: Safari 12.1.2 / Mac OS X 10.14.6
Referer: https://www.gbif.org/species/4832182
Window size: width 1790 - height 849
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-17T09:20:39.702Z',mode:absolute,to:'2019-09-17T09:26:39.702Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-17T09:20:39.702Z',mode:absolute,to:'2019-09-17T09:26:39.702Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by yroskov** [comment]
Only subspecies Artibeus  intermedius  koopmani  Wilson, 1991 present in the CoL and it is a synonym for Artibeus  lituratus  koopmani  Wilson, 1991.

**Comment by ManonGros** [comment]
Solved in the new backbone.
