### ISSUE TITLE
Boocerus eurycerus is missing genus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2204]
**Boocerus eurycerus is missing genus**

This species seems to have been added without a genus: `https://www.gbif.org/species/8883103`

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/53ae7d86ecbef7e71fcac7d91f33f258:e8405885f1ad2979328b4f774f0b7bb85fc7932a9623a8998b3191e55354596ff2e91f3f0805e39dd3224a10e5d8be933ece78aa3ce7cacc4f093894d5715093)
System: Safari 12.1.2 / Mac OS X 10.14.6
Referer: https://www.gbif.org/species/8883103
Window size: width 1790 - height 849
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-17T09:25:15.588Z',mode:absolute,to:'2019-09-17T09:31:15.588Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-17T09:25:15.588Z',mode:absolute,to:'2019-09-17T09:31:15.588Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
The species doesn't exist in the new backbone: https://www.gbif.org/species/search?q=Boocerus%20eurycerus
