### ISSUE TITLE
Alouatta villosa is a synonym of Alouatta pigra

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2205]
**Alouatta villosa is a synonym of Alouatta pigra**

Alouatta villosa isn't included in the CoL, it comes from the GBIF Type Specimen Names.
According to one of our users and this publication: `https://doi.org/10.1896/0898-6207.21.1.41,` this species is in fact a synonym of Alouatta pigra (`https://www.gbif.org/species/2436653).`

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/715b4b9fe5abae5148fcbd95e728deb4:ba7fb069e956b4fce039490555cdc091529757d77c8ba4abbbca6f23573dd7a10123757a0c93a844dd02cfd9e3c6370ba2dc2fad7450b98128016f7526a7225f)
System: Safari 12.1.2 / Mac OS X 10.14.6
Referer: https://www.gbif.org/species/8919918
Window size: width 1790 - height 849
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-17T09:38:12.459Z',mode:absolute,to:'2019-09-17T09:44:12.459Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-17T09:38:12.459Z',mode:absolute,to:'2019-09-17T09:44:12.459Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
The species doesn't exist in the new backbone: https://www.gbif.org/species/search?q=Alouatta%20villosa
