### ISSUE TITLE
3.436 occurrences of scientificName: flowering plant

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2206]
**3.436 occurrences of scientificName: flowering plant**

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/f67a1c5a3aea931c6d4327a54d6ec68b:1761223d880c7c0e0d3e44a479260ae3c6497208400d2d50eb5d63a466be59b78550b20c90b76ee00d7af8395ec8ac41d0e5cfeaf71713a2176294f0f058fc8e)
System: Chrome 76.0.3809 / Mac OS X 10.14.5
Referer: https://www.gbif.org/occurrence/search?taxon_key=9192154
Window size: width 1812 - height 1306
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-18T14:48:54.643Z',mode:absolute,to:'2019-09-18T14:54:54.643Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-18T14:48:54.643Z',mode:absolute,to:'2019-09-18T14:54:54.643Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by kcopas** [comment]
All from NHM London—that should be fixable. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ahahn-gbif** [comment]
The visibility is due to a species name entry (https://www.gbif.org/species/9192154). This requires some work around backbone constituents (https://www.gbif.org/dataset/6cfd67d6-4f9b-400b-8549-1933ac27936f)

**Comment by ManonGros** [comment]
https://github.com/gbif/portal-feedback/issues/661

**Comment by ManonGros** [comment]
Issue solved in with the backbone update.
