### ISSUE TITLE
that identifier looks wrong

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2207]
**that projectID looks wrong**

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/34b99450337db32a97d6601fcacb2bf2:19bcb4f1f299335ec3347bbeb54c34848c7fdcd67a0ab07fd8b62d526b86e895c720e7f53a333896f6b9155a3f5abe2e5792b9175b570b3bcf06dd8907a49a9a)
System: Chrome 76.0.3809 / Mac OS X 10.14.5
Referer: https://www.gbif.org/dataset/f6cdf322-c67f-406d-afd1-1dba97209ec0/project
Window size: width 1812 - height 1306
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-19T08:42:44.994Z',mode:absolute,to:'2019-09-19T08:48:44.994Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-19T08:42:44.994Z',mode:absolute,to:'2019-09-19T08:48:44.994Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Email contact 2.10.19

**Comment by ManonGros** [comment]
This issue seems solved.
