### ISSUE TITLE
I am working with Piper L. data and am wondering which field is best to query to be sure to capture all of the synonyms in a group.  Looking at the data I downloaded, i am guessing that the verbatimScientificName is the best field, but wanted to be sure.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2208]
**I am working with Piper L. data and am wondering which field is best to query to be sure to capture all of the synonyms in a group. Looking at the data I downloaded, i am guessing that the verbatimScientificName is the best field, but wanted to be sure.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8e6a0ccf81fef49f7ed023bcabf829a7:2885dc4e6cec8b033a0acf9113be5835713817c5dc1bff7e23a5fb536bce66afa12a51cf95fce85704b5aeb9390560a9fd599c51d1b3c01254c19dacae12b53b)
System: Chrome 76.0.3809 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0007216-190813142620410
Window size: width 1600 - height 740
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-19T18:11:00.943Z',mode:absolute,to:'2019-09-19T18:17:00.943Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-19T18:11:00.943Z',mode:absolute,to:'2019-09-19T18:17:00.943Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
