### ISSUE TITLE
Taxon name interpretation error: Taraxacum sect. Naevosa (Asteraceae) -> Naevosa (Mollusca)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2209]
**Taxon name interpretation error: Taraxacum sect. Naevosa (Asteraceae) -&gt; Naevosa (Mollusca)**

The higher taxonomy of the source record only gives Asteraceae, but that should be unambiguous enough to interpret the scientific name (Taraxacum sect. Naevosa) as a plant record. Similarly, also see `https://www.gbif.org/occurrence/search?dataset_key=8df9af24-1fbd-4699-a545-9a2867ff25fe&taxon_key=1.` Also in those cases, the sectio gets interpreted as genus name and matched into the wrong classification.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/139e0091837d098a2c8e84c7c692a582:fc82f7ffab56500a98b2aa2c3f2d4388b4e59357d7515e68b53a234a0a377350a4f3de8a40cbfc206da7e335d0b82e470e506e507d9f84775d6c51d8b8a6a05f)
System: Firefox 69.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1343049247
Window size: width 1132 - height 609
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-20T08:24:35.092Z',mode:absolute,to:'2019-09-20T08:30:35.092Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-20T08:24:35.092Z',mode:absolute,to:'2019-09-20T08:30:35.092Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 8df9af24-1fbd-4699-a545-9a2867ff25fe
publishingOrgKey: 98255206-f0fe-4183-9845-77143274938c

**Comment by ahahn-gbif** [comment]
A candidate for setting a registry default for the kingdom

**Comment by ManonGros** [comment]
I added the default value and launched the re-interpretation of the data but I get unexpected results. For example, these two occurrences have the same name but are interpreted differently:
* https://www.gbif.org/occurrence/1343049247
* https://www.gbif.org/occurrence/1343048967

I am not sure why, perhaps only some of the records are re-interpreted?

**Comment by ManonGros** [comment]
Seems like the issue has been fixed (the data has been reinterpreted correctly)!
