### ISSUE TITLE
basionym

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2212]
**basionym**

for "? sanguinolenta" read “Gorgonia sanguinolenta”. WoRMS says so, and I see no reason to disagree.
`http://www.marinespecies.org/aphia.php?p=taxdetails&id=1337411`

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bb28e0318e026e3ffb5ba328a179dee8:2fb298ed3802ec42a90fc697abc2170b06b6f90554956995e6058be87f4143326a36cf24b3c593f6f9b5f8d76d6b572455d8806f92f7f547cc4729bd40353e54)
System: Firefox 69.0.0 / Mac OS X 10.9.0
Referer: https://www.gbif.org/species/6473206
Window size: width 1165 - height 782
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-21T23:29:01.532Z',mode:absolute,to:'2019-09-21T23:35:01.532Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-21T23:29:01.532Z',mode:absolute,to:'2019-09-21T23:35:01.532Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
I don't see any "? sanguinolenta", but I see `Filigorgia sanguinolenta (Pallas, 1766)` basionym of `Gorgonia sanguinolenta Pallas, 1766`. I am closing the issue but let me know if I missed something.
