### ISSUE TITLE
date of binomial

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2213]
**date of binomial**

Yes, Stylephorus chordatus is described by George Shaw in the Linnean Transactions for 1791 (scans at BHL). But the identical description and illustration already appeared in Shaw's Miscellany, volume 8 (early 1797, also at BHL).
???

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b4120be29d6f41938595a725654c3a74:1ed1a676df597f43923251d8318a67862ab1419cad42aa0e4b6f7c690a9a5d189ed510c7e469aaac861bd2f6b07b959df30fec74d81eb4cfc659cd9e1e008113)
System: Firefox 69.0.0 / Mac OS X 10.9.0
Referer: https://www.gbif.org/species/2400459
Window size: width 1165 - height 782
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-23T01:50:44.924Z',mode:absolute,to:'2019-09-23T01:56:44.924Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-23T01:50:44.924Z',mode:absolute,to:'2019-09-23T01:56:44.924Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
https://github.com/gbif/portal-feedback/issues/2214
