### ISSUE TITLE
Link to Biodiversity Open Data Ambassadors form gives a warning

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#2215]
The issue is on this page: https://www.gbif.org/article/6dNF1d0tgcI4cmqeoS2sQ4/biodiversity-open-data-ambassadors

The following link https://www.bit.ly/gbifamb should probably be https://bit.ly/gbifamb because otherwise I get a certificate warning.

**Comment by ahahn-gbif** [comment]
updated - closing
