### ISSUE TITLE
FAQ on Doubtful

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2218]
**FAQ on Doubtful**

That these concepts are all marked as doubtful is confusing. 

I am sure there is a good reason (not in the nomenclator perhaps?) but I suggest we need an FAQ documenting the scenarios why something can be marked as doubtful (infra kingdom homonym etc).

@wixner can assist in writing

-----

Github user: @timrobertson100
User: [See in registry](https://www.gbif.org/api/feedback/user/4cb8c42587233e4cbbc16c31d98de762:58961741bc72e5ba5fb8dbde5b3ec0a8c98e8d6d8c5a4612896d2aa726c823469ebb84fbfb9278270158eb07627b11226c6ecab0a0c102898e49febbe196e2c1)
System: Chrome 76.0.3809 / Mac OS X 10.14.5
Referer: https://www.gbif.org/species/search?q=hobern
Window size: width 2378 - height 1294
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-24T09:45:21.968Z',mode:absolute,to:'2019-09-24T09:51:21.968Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-24T09:45:21.968Z',mode:absolute,to:'2019-09-24T09:51:21.968Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
According to [these slides](https://de.slideshare.net/mdoering/gbif-checklist-bank-and-the-backbone#19), a taxon is marked as doubtful when:
* it is a genus or higher taxon without any species (IRMNG)
* it is species or infrasp. with a parent genus or species considered to be a synonym

However, I don't know why these species are flagged as doubtful as they don't fit in either of these categories.
@mdoering, any idea?

**Comment by mdoering** [comment]
There are many more reasons why a taxon becomes doubtful. I am not sure if I can list them all, but here are some more:

 - name comes from a nomenclator only (thats the case here mostly at least, ZooBank names)
 - homonyms. We have more than 1 accepted name with the same canonical (but different author) and only keep the most trusted only as accepted. Others become doubtful
 - basionym placeholders with `? epithet`
 - homonym usages from a single source are doubtful

**Comment by ManonGros** [comment]
Ok so we could either put that in the FAQ, for example:
```
A name can be flagged as doubtful for several reasons that have to do
with the way the GBIF backbone taxonomy is built.
Here is a non- exhaustive list:
- The name comes from a nomenclator only.
- There is more than one accepted name with the same canonical name but 
different author. In that case, the most trusted one is accepted and the other(s)
become doubtful.
- The name has homonyms in the same source.
- The name is a basionym placeholder and contains "? epithet".
- The name is a genus or higher taxon without any species.
- The name is a species or and infra-species with a parent genus or
species considered to be a synonym.
```
I have the feeling that this might be a bit too cryptic for a FAQ though. Perhaps we could put that somewhere else, on a wiki? and link it from a simpler FAQ.
Any thoughts?

**Comment by mdoering** [comment]
I would like best a single, large article that explains how the backbone is assembled and includes these things. But as we are moving to an entirely new procedure with CoL+ I don't feel like spending resources on this now. Splitting information into many different places is something I would very much avoid, it leads to outdated, wrong informations.

So Id vote for no wiki, but simple FAQ (even if its cryptic for now)

**Comment by ManonGros** [comment]
Sounds good, in that case, could someone make the FAQ with this text? @dnoesgaard perhaps? I don't really know how it works.

**Comment by dnoesgaard** [comment]
https://www.gbif.org/faq?question=what-does-the-taxon-status-doubtful-mean-and-when-is-used

**Comment by dnoesgaard** [comment]
Should we have a pop-up somewhere?

**Comment by ManonGros** [comment]
![Screenshot 2019-10-01 at 12 16 18](https://user-images.githubusercontent.com/7677271/65953987-6c28cb80-e445-11e9-9603-f43af9ce3d84.png)

**Comment by dnoesgaard** [comment]
@MortenHofft any suggestions?

**Comment by MortenHofft** [comment]
In next iteration of the website I imagine we will have help texts for all filters. But changing that in the current website is a bit more cumbersome. Adding it to the result card is easier (though I'd rather add it to the filter drawer)

**Comment by dnoesgaard** [comment]
+1 for the filter drawer

**Comment by dnoesgaard** [comment]
Although, come to think of it, it might be useful to have on the taxon page in question, where 'Doubtful' is shown in the article header. I don't know...

**Comment by ManonGros** [comment]
Yes you are right, that would make sense and probably be easier to implement.

**Comment by dnoesgaard** [comment]
Morten, the `&inline=true` FAQ 'hack' only works in Contentful content, right? ;)

**Comment by MortenHofft** [comment]
@dnoesgaard You cannot add it to a translation string if that is the thinking. It still needs some parsing and I do not believe we do so if it is a translation string. 

Adding it to the species page makes sense to me. 

And at some point to the filters themselves as it seems the perception of that idea has changed since it was first suggested.

**Comment by ManonGros** [comment]
> Adding it to the species page makes sense to me.

Would it be possible to add it to the species page then? Thanks!

**Comment by MortenHofft** [comment]
@ManonGros there is a better chance that Thomas or I notice the issue, if it is assigned to us or labeled as a portal issue. Please feel free to do so.
