### ISSUE TITLE
Does Sequence ID use the latest UNITE version?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2219]
**Does Sequence ID use the latest UNITE version?**

See topic

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0452139a0448822dfad8c732cdb4153d:79a780d0aea2dbf87195a34bfb7536fb92706c2c85270db9ed39436cdf40de7a6aaabd456e38abe0cbba4d7b36721764794c04badc85120ace3cf8d09654714e)
System: Chrome 77.0.3865 / Windows 10.0.0
Referer: https://www.gbif.org/tools/sequence-id
Window size: width 1396 - height 665
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-26T14:21:12.385Z',mode:absolute,to:'2019-09-26T14:27:12.385Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-26T14:21:12.385Z',mode:absolute,to:'2019-09-26T14:27:12.385Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
@dschigel working on it. Code is ready but have a deployment issue. Will keep you posted

**Comment by thomasstjerne** [comment]
Now it does.
