### ISSUE TITLE
How to change IPT contacts

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2221]
**How to change IPT contacts**

We at the Vermont Center for Ecostudies need to change the contacts for our IPT.

I cannot find anywhere in our IPT where we can alter those values. I need assistance to find where I make those changes.

Thank you.

Jason Loomis
jloomis@vtecostudies.org

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e449cf5930ebcc6423c81d978cc5f1b1:af878d0af299dde44c766eeef12edf27e479a1d7c7ade84142738bc676adf6ed11a58fe2fb3e7a507bef8f427aeaba57437ac181b4479f57836e565b6393b89e)
System: Firefox 69.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/contact-us/directory
Window size: width 1536 - height 706
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-26T16:09:02.727Z',mode:absolute,to:'2019-09-26T16:15:02.727Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-26T16:09:02.727Z',mode:absolute,to:'2019-09-26T16:15:02.727Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email
> * If you would like to update the installation contact on the GBIF installation page (https://www.gbif.org/installation/5ae8b93d-03d9-48f1-8334-f1f251d13f1f) you should contact us (helpdesk@gbif.org) and we apply the changes for you. Note that you should also contact us if you want to update anything on your GBIF organization page (https://www.gbif.org/publisher/b6d09100-919d-4026-b35b-22be3dae7156).
> * If you would like to modify the contact on your IPT about page (http://ipt.vtecostudies.org/ipt-2.3.5/about.do), you can do so by updating the about.ftl file in your “config” directory.
