### ISSUE TITLE
Cannot trigger DiGIR dataset ingestion

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2224]
**Cannot trigger DiGIR dataset ingestion**

I tried:
- clicking on "ingest now" on GBIF.org
- clicking on crawl in the registry
- synchronising the installation: `https://registry.gbif.org/installation/5fe82690-f762-11e1-a439-00145eb45e9a`

Also, the link to the logs available from the dataset page doesn't work unless I manually select "prod-crawl" instead of "prod-pipeline":
`https://logs.gbif.org/app/kibana#/discover?_g=(time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWDqIeCpf8lu3pmEHglJ,key:datasetKey,negate:!f,type:phrase,value:ebf3c079-f88e-4b85-bcc5-f568229e68f3),query:(match:(datasetKey:(query:ebf3c079-f88e-4b85-bcc5-f568229e68f3,type:phrase))))),index:AWyKwQsdHCKcR6PFVqgv,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))`

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/a30d399a2804868fe1ae6f36ca3fa956:97e6823da58aa672f67bc95fedc74a86a9ef0980f982a1f7091ee2aa00bf7b402d8dc5f8c12dafa068552f3323ea2e4f28d3e45bfbe99f443c91480d7827e3be)
System: Safari 13.0.1 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/ebf3c079-f88e-4b85-bcc5-f568229e68f3
Window size: width 1872 - height 1042
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-01T08:30:29.464Z',mode:absolute,to:'2019-10-01T08:36:29.464Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-01T08:30:29.464Z',mode:absolute,to:'2019-10-01T08:36:29.464Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by asturcon** [comment]
There was a bad state in ZK and this dataset appeared in ZK but it wasn't being crawled. I just cleaned it from ZK.
