### ISSUE TITLE
Genus + sect. should be interpreted as Genus

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#2225]
This is an issue related to: https://github.com/gbif/portal-feedback/issues/2209
The taxon `Taraxacum sect. Naevosa` is not linked to the genus `Taraxacum` (https://www.gbif.org/species/7787708) because `sect.` seems to be interpreted as a scientific epithet when it shouldn't be.

It seems like this is a name parser issue, could someone check?

**Comment by ahahn-gbif** [comment]
example occurrence record: https://www.gbif.org/occurrence/1438211144
(This example rather demonstrates a mismapping of the occurrence data source: specificEpithet and infraspecificEpithet are mapped as "sect." and "Naevosa", resp., which is factually incorrect.)

See https://www.gbif.org/occurrence/2939082993 for a proper name mapping.

Suggestion: at least in cases where the source supplies the atomized genus name (second example, above), taxon-match to higherRank = genus if available, not family
