### ISSUE TITLE
Indigenous versus non-indigenous species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2227]
**Indigenous versus non-indigenous species**

Please can you let me know if it is possible to differentiate between indigenous and non-indigenous species from the same family in a specific geographical region?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c7b61a8cb17050aea567769e3ffacf47:22cf7ede19200476c68a4b9a15e49b4734e4995d77abf8a6a5ba1dae8021a4dce6a101f290b56a901ca6e6add1473adda43b77f1ed73f0149545a78d112b7c15)
System: Chrome 77.0.3865 / Windows 10.0.0
Referer: https://www.gbif.org/faq
Window size: width 1536 - height 754
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-02T13:58:11.454Z',mode:absolute,to:'2019-10-02T14:04:11.454Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-02T13:58:11.454Z',mode:absolute,to:'2019-10-02T14:04:11.454Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Answered by email.
