### ISSUE TITLE
Brazilian dataset not ingested

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2229]
**Brazilian dataset not ingested**

This is not because of the content, it is something that has to do with their URL.
If I download the archive and process it with the validator it works but if I just use the URL (`https://ipt.sibbr.gov.br/sibbr/archive.do?r=forest-island_floristic)` it doesn't.

It seems like it is not the only dataset from this IPT with issues like that (see this one for example: `https://www.gbif.org/dataset/01d28467-87a1-4d64-ba40-4e3e1cc9091b)`

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/dae956d4b67b97774a0b47ebfb37ddc0:9adc2cac150eb5ec4890894d4bc54811962647839136948a4d8cbb76d996e5bc27a3974a3c6a0561edfb56b9f552e18aa2ea1ec1ec8fa97d74e5dc455438b3e4)
System: Safari 13.0.1 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/5846793d-f540-473c-88ee-23b2b13af7ef
Window size: width 1257 - height 1066
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-03T08:19:22.501Z',mode:absolute,to:'2019-10-03T08:25:22.501Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-03T08:19:22.501Z',mode:absolute,to:'2019-10-03T08:25:22.501Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Their IPT was down (or more likely, something it depends on, like their internet connection).

It's back up, and the affected datasets ingested.
