### ISSUE TITLE
Some questions about fields and mapping

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2230]
**Some questions about fields and mapping**

Good day to you,

We, the Natural History Museum Rotterdam,  are contributors to the GBIF community with 6 datasets containing altogether  441.350 records. We have listed some questions and remarks regarding presentation of our data in GBIF. Perhaps you might be able to elucidate some of those:

Dwc fields year, month and day are shown in the correct way if all are present. If only year is known, we fill in 00 for both month and day. In such cases GBIF deletes all three fields, even the field year which originally contained data. We simply use the 00-entry as an indicator to show we didn’t overlook entering data! Do we have to leave these particular fields empty in future uploads?

Does the DwC-field vernacularName have unlimited data entry? Should different names be separated by a vertical bar space?

The field minimumDepthInMeters is sometimes not accepted. Could this have something to do with coordinates not matching depth?

The field scientificNameAuthorship is uploaded but does not show with the occurrence. Why?
 
Images:
In out next upload we will enter links to our images in the DwC field associatedMedia.
Link will look like this: `http://www.nmr-pics.nl/PICTURES/` followed by the unique name of the image.
Can a second (3rd, 4th, 5th, etc.) image belonging to the same sample be listed in the same associatedMedia field as multiple full links seperated by vertical bars?

Upload DwC-field waterBody (field country left blank):  We noticed that particular coordinates, in this case North Sea, were situated in international waters outside the 12 mile zone. GBIF subsequently assigns the records to country=United Kingdom. Bug or use of different definitions?

Last but not least: we consider showing our GBIF datasets by the GBIF portal through a webviewer on our NMR website. Testing this we concluded everything works fine, only the map freezes and the tools on the mapping don’t work. Could you please advise?

Hope you can help us out with these issues. 

Kind regards

Frans Slieker (Honorary Curator NMR)

cc. Bram Langeveld MSc (Curator NMR)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9df280cc969cc52214b67d27b5e1a361:7f09b2a10669fca092ed4463e384cb17481288036c0a674e98ca5f6ac1c4e656b45624fd6f8057e9beadd08e5ea4d01fee4c01effe586afa551940d783393f31)
System: Firefox 69.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?publishing_org=3ead5cf3-2840-482e-bbd9-76380825be63&advanced=1
Window size: width 1920 - height 966
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-03T21:53:49.401Z',mode:absolute,to:'2019-10-03T21:59:49.401Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-03T21:53:49.401Z',mode:absolute,to:'2019-10-03T21:59:49.401Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
