### ISSUE TITLE
URL for current backbone taxonomy is incorrect

### ISSUE THREAD

**Issue by Mesibov** [gbif/portal-feedback#2232]
The backbone-taxonomy-as-dataset page
https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c

has this URL for the backbone archive
http://rs.gbif.org/datasets/backbone/backbone-current.zip

which is a 2018 backbone version. Similarly, the backbone page in GBIF Resources
http://rs.gbif.org/datasets/backbone/

has that 2018 version as "current". The current version is in this folder:
http://rs.gbif.org/datasets/backbone/2019-09-06/

and the correct URL for the current archive is
http://rs.gbif.org/datasets/backbone/2019-09-06/backbone.zip

**Comment by mdoering** [comment]
Indeed. We forgot to update he symlink!
http://rs.gbif.org/datasets/backbone/backbone-current.zip and http://rs.gbif.org/datasets/backbone/backbone-current-simple.txt.gz should always point to the latest, current version so we have a single, stable URL.

Updated just now
