### ISSUE TITLE
Taxonomic howlers in current backbone taxonomy

### ISSUE THREAD

**Issue by Mesibov** [gbif/portal-feedback#2234]
Taxonomists and identifiers often use "technical" abbreviations and codes in name strings which could be confused with names by non-taxonomists. Some of these abbreviations and codes have been detected in compiling the backbone, but not all. A scan of short specificEpithet entries in the latest backbone turned up the howlers below. All of these have taxonomicStatus = "accepted", and this is by no means a complete list.

-------------------
"gen" for "genus"
-------------------
scientificName: Gracillariidae gen ChrysobalanusUSA
https://www.gbif.org/species/10462109
taxonRank: species
datasetID for: International Barcode of Life
(in genus "Gracillariidae"!!)

------------------
"gr" for "group"
------------------
scientificName: Cretirhynchia gr J.Sowerby
taxonRank: species
datasetID for: GBIF Type Specimen Names
(See https://www.gbif.org/occurrence/932716509)

--------------------
"kl" for "klepton"
--------------------
scientificName: Rana kl
taxonRank: species
datasetID for: MNHN Reptiles and Amphibians
(See https://www.gbif.org/occurrence/440020321)

-------
"new"
-------
scientificName: Eriopyga new
taxonRank: species
datasetID for: International Barcode of Life

-----------------
"nr" for "near"
-----------------
scientificName: Nomada nr
taxonRank: species
datasetID for: International Barcode of Life
(source name: one of several possible "Nomada nr {species}")

-------------------
"nov" for "nova"
-------------------
scientificName: Rissoa nov
taxonRank: species
datasetID for: GBIF Type Specimen Names
(See https://www.gbif.org/occurrence/932716509)

------------------------
"sg" for "subgenus"
------------------------
scientificName: Bombus sg
taxonRank: species
datasetID for: GBIF Type Specimen Names

------------------------
"subg" for "subgenus"
------------------------
scientificName: Megachile subg
taxonRank: species
datasetID for: GBIF Type Specimen Names
(See https://www.gbif.org/occurrence/2292490533)

------------------
"cr" in codename
------------------
scientificName: Nicetas cr
taxonRank: species
datasetID for: International Barcode of Life
(source name: Nicetas cr-1)

**Comment by jhnwllr** [comment]
I will break this issue into separate issues and then close this one.
