### ISSUE TITLE
iNaturalist in GBIF, metadata: geographic scope bounding box out of range

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2235]
**iNaturalist in GBIF, metadata: geographic scope bounding box out of range**

The metadata of iNaturalist in GBIF.org define a geographic scope of 

<boundingCoordinates>
<westBoundingCoordinate>-179.9989</westBoundingCoordinate>
<eastBoundingCoordinate>179.9974</eastBoundingCoordinate>
<northBoundingCoordinate>943.6344</northBoundingCoordinate>
<southBoundingCoordinate>-77.8930904568244</southBoundingCoordinate>
</boundingCoordinates>

As the north bounding coordinate exceeds the latitude range, the scope does not display meaningfully (suspected typo).

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8df2cf39d0af3dce659b416ed1de5bee:93cdd911773597acb3aba1492a1d10e98569b94d55ebbcea3f35149326afcbc025f7410ccae41ce0c21f9aec3d10a30b97e591fc202bf064784a551bde15b867)
System: Firefox 69.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7
Window size: width 1349 - height 769
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-07T13:11:49.926Z',mode:absolute,to:'2019-10-07T13:17:49.926Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-07T13:11:49.926Z',mode:absolute,to:'2019-10-07T13:17:49.926Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
@kueda @loarie

**Comment by kueda** [comment]
Not a typo, but certainly something we need to fix. Thanks for the heads up. Should be addressed the next time our DwC-A updates.

**Comment by ManonGros** [comment]
The bounding box looks fixed, closing the issue.
