### ISSUE TITLE
458 occurrences ingested but only 12 displayed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2236]
**458 occurrences ingested but only 12 displayed**

I am not sure why this is happening.
I have recrawled the data but it didn't seem to fix anything. Could someone take a look at what is happening?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/eb32092cf86d0ec1503a49a01e7ac76e:f0fb123b4126b3e1aa2c767bb024355efc7a9f66dace3a3eec2fa024e40d79fce9a3e733089e859995e6a24e08a0068359adacb80043b5e2462e7b5658e05ce5)
System: Safari 13.0.1 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/9e87656d-d76c-4ab0-8222-8666c349650c
Window size: width 1614 - height 846
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-07T14:26:29.156Z',mode:absolute,to:'2019-10-07T14:32:29.156Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-07T14:26:29.156Z',mode:absolute,to:'2019-10-07T14:32:29.156Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This dataset seems to have a similar issue: https://www.gbif.org/dataset/ae33dc82-0bc2-43b5-b69b-65bf858f1e7a

**Comment by muttcg** [comment]
https://www.gbif.org/dataset/9e87656d-d76c-4ab0-8222-8666c349650c is fixed
