### ISSUE TITLE
Allow queries by keys in occurrence downloads

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal-feedback#2238]
I would like to suggest allowing queries with KEY predicates like

`{
    "type":"in",
    "key":"KEY",
    "values":["xxx","yyy","zzz"]
  }`

This would allow of to "reconstruct" smaller downloads AND provide an easy means of generating a citable download for a dataset already retrieved through the search API.

**Comment by dmi3kno** [comment]
You mean something like this in R:
```r
s<- occ_download(pred_in("occurrenceId",c("urn:lsid:artportalen.se:sighting:47472320",
                                      "urn:lsid:artportalen.se:sighting:46374792",
                                      "urn:lsid:artportalen.se:sighting:47292189",
                                      "urn:lsid:artportalen.se:sighting:47292189")))
s
```
This results in the valid query 

>   GBIF Occurrence Download https://doi.org/10.15468/dl.69bne7 Accessed from R via rgbif (https://github.com/ropensci/rgbif) on 2023-08-10

**Comment by dnoesgaard** [comment]
Actually, my request was for the occurrence key aka gbifID, not the occurrenceId.

But in all fairness, with derived datasets, this is now less relevant in my perspective...

**Comment by MattBlissett** [comment]
@MortenHofft, this is done in UAT and will need a translation key added for the portal: https://www.gbif-uat.org/occurrence/download/0000002-230824125624414 / https://api.gbif-uat.org/v1/occurrence/download/0000002-230824125624414 — and presumably a new search filter.

**Comment by MortenHofft** [comment]
I've added translation and filters for it to the master branch. So API triggered downloads will be recognized, but the filter isn't available in the UI. I will do that when the API is on production. Please let me know when.

**Comment by MattBlissett** [comment]
Very soon.

**Comment by MattBlissett** [comment]
I cancelled it, but an example: https://www.gbif.org/occurrence/download/0000255-230828120925497

(Oops, IDs are from UAT and don't exist in prod. https://api.gbif.org/v1/occurrence/search?gbif_id=4089794301 works.)

**Comment by MattBlissett** [comment]
I see this is now in production.
