### ISSUE TITLE
Link to GBIF's Data Publisher Agreement in Spanish broken

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2240]
**Link to GBIF&#39;s Data Publisher Agreement in Spanish broken**

We link to this link which doesn't seem to work: `https://www.gbif.org/es/t%C3%A9rminos/proveedores%20de%20datos`

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/acceb19d22671aed102b066403dc8597:8ad9e0ae4be812975d7fbbe33a7542272f7dd3680cd0db16caa9e681072fb4b7bb383acc499a7aed1b9fcb7104f1ac949a12f1d12c8836da9ef88bffcf8f8fd1)
System: Safari 13.0.2 / Mac OS X 10.14.6
Referer: https://www.gbif.org/es/become-a-publisher
Window size: width 1485 - height 902
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-10T07:31:21.074Z',mode:absolute,to:'2019-10-10T07:37:21.074Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-10T07:31:21.074Z',mode:absolute,to:'2019-10-10T07:37:21.074Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by akristensen** [comment]
@MortenHofft @dnoesgaard think it might be an issue for you guys?

**Comment by dnoesgaard** [comment]
Fixed in https://crowdin.com/translate/gbif-portal/90/en-es#7462
