### ISSUE TITLE
Correct title

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2242]
**Correct title**

Please correct title to match the event webpage `http://insma.urfu.ru/en/research/itbio`

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4d8579cdfa47c991a4c88d0d3821e261:cefdaf006e10dd61c7956fc5eaf4f2a6646e7cdb05046fc98f15d66da4de5cbb997539b482be55efa7259375dddbde47ef503d66048c471749dbb8a0899373fe)
System: Chrome 77.0.3865 / Windows 10.0.0
Referer: https://www.gbif.org/event/ncQ4KNmYaYsY6kiTfsJ33/information-technologies-in-the-research-of-biodiversity
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-11T09:30:59.253Z',mode:absolute,to:'2019-10-11T09:36:59.253Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-11T09:30:59.253Z',mode:absolute,to:'2019-10-11T09:36:59.253Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Updated as requested
