### ISSUE TITLE
A search for Bergia texana yields two names, differing in authorship. I think these are the same plant and should be combined. But, the correct full name should be: Bergia texana (Hook.) Seub. ex Walp.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2243]
**A search for Bergia texana yields two names, differing in authorship. I think these are the same plant and should be combined. But, the correct full name should be: Bergia texana (Hook.) Seub. ex Walp.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1b8b1ce7ad736a0fba6f076faf136654:c2eff72e1e23508640d2c056c4edfdfb6465f4571110d154e5a91de4e7151a711d33e48d69b9df2e0caa89c63b264dd671607e6a8b17c733ae3d851df8c01b10)
System: Safari 11.1.2 / Mac OS X 10.11.6
Referer: https://www.gbif.org/search?q=Bergia%20texana
Window size: width 1190 - height 759
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-11T13:23:13.134Z',mode:absolute,to:'2019-10-11T13:29:13.134Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-11T13:23:13.134Z',mode:absolute,to:'2019-10-11T13:29:13.134Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
These two species are actually synonyms in our backbone.

**Comment by ManonGros** [comment]
The accepted name doesn't seem to fit with the suggested name here.

**Comment by yroskov** [comment]
CoL has only one names as accepted species: Bergia texana (Hook.) Seub. ex Walp.
http://www.catalogueoflife.org/annual-checklist/2019/search/all/key/Bergia+texana/fossil/1/match/1
