### ISSUE TITLE
Add metro directions

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2244]
**Add metro directions**

It's probably worth updating the travel directions, so people who aren't comfortable using a bus can use the metro, at the cost of a bit more walking.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b5e1bfcd89fdbca9822e6f059d2002df:2093c4741ccaeecbc28276b382c3a2a30447d238101f23203a862b089fcc4c3943977766efdbcc14c51c69d93e75b045f9bd5ef70f8aba8b56953e7e40613e47)
System: Firefox 68.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/contact-us
Window size: width 1440 - height 2430
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-11T15:53:42.852Z',mode:absolute,to:'2019-10-11T15:59:42.852Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-11T15:53:42.852Z',mode:absolute,to:'2019-10-11T15:59:42.852Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
@akristensen could take a run at this, please?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akristensen** [comment]
Done
