### ISSUE TITLE
wrong taxonomic position

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2245]
**wrong taxonomic position**

This species belongs to the following genus:

`https://www.gbif.org/species/2235049`

Greetings

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bd9bf7e3e2185fa73a786d65d7bf0bef:4cc112d9a63548b178f1d0938f81b2b901511392044f7b5f035e4fbb2589d1dc0b2269e9460a6972e2c11188d3186c4b625e7e10fce7847329dd52a3bf94f918)
System: Firefox 68.0.0 / Windows 7.0.0
Referer: https://www.gbif.org/species/4667735
Window size: width 2269 - height 1129
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-14T08:05:34.364Z',mode:absolute,to:'2019-10-14T08:11:34.364Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-14T08:05:34.364Z',mode:absolute,to:'2019-10-14T08:11:34.364Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The species is a synonym of `Monoculus apus Linnaeus, 1758` (https://www.gbif.org/species/8057833) which belongs to the genus Monoculus.
