### ISSUE TITLE
'Accepted name' link goes to the applied name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2247]
**&#39;Accepted name&#39; link goes to the applied name**

The two links both go to *Piliocolobus temminckii* here.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2b999baaa726bb32b0aa468f589aea5c:07ddc895e523e435a0de4b451bd874b2e3d3a393d1577f0b78a6e0f011b60e390f85300c9d0fae5a2307ce58fb10b39bed3f61a8d92012f9f32ccf39a39b7ebb)
System: Firefox 68.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/occurrence/1802794710
Window size: width 1276 - height 1226
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-14T13:05:38.172Z',mode:absolute,to:'2019-10-14T13:11:38.172Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-14T13:05:38.172Z',mode:absolute,to:'2019-10-14T13:11:38.172Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

**Comment by ManonGros** [comment]
Isn't it because they are synonym?
