### ISSUE TITLE
Hi, This Magnify dataset shouldn't contain grasses. Something was mismatched

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2248]
**Hi, This Magnify dataset shouldn&#39;t contain grasses. Something was mismatched**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3a8a90c44efcc9e7712e7522a65fdaa7:73c043d4d0b8d74ce990967248c55518e4d84c187d2a09aebf8e3a64abfd0cad2008187d871d4b1532f720d7af92359d1e5969c0af89ed29df23a260f506219b)
System: Chrome 77.0.3865 / Mac OS X 10.14.6
Referer: https://www.gbif.org/occurrence/search?dataset_key=d596fccb-2319-42eb-b13b-986c932780ad&taxon_key=5289779
Window size: width 1757 - height 883
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-14T14:06:16.156Z',mode:absolute,to:'2019-10-14T14:12:16.156Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-14T14:06:16.156Z',mode:absolute,to:'2019-10-14T14:12:16.156Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Nor should it contain Rhinos: https://www.gbif.org/occurrence/search?publishing_org=ab733144-7043-4e88-bd4f-fca7bf858880&taxon_key=795
We need a flag for occurrences records that are based on sequences and have only `Organism quantity` = 1, regardless of whether a species is terrestrial or not.

**Comment by thomasstjerne** [comment]
I can verify that the mismatch isn´t on our side. You will see _Aegilops tauschii_ in the [MGnify API here](https://www.ebi.ac.uk/metagenomics/api/v1/analyses/MGYA00167849/taxonomy/ssu)

I agree with @ManonGros that we need a way to flag and filter out occurrences from metagenomic datasets that are based very few reads. Preferably the user would be able to select a minimum number of reads, or even better a relative value based on `Organism quantity` and `Sample size value`

**Comment by ManonGros** [comment]
Closing since most vascular plants and vertebrates have been filtered out and that we now have the relative organism quantity filter: https://www.gbif.org/occurrence/search?publishing_org=ab733144-7043-4e88-bd4f-fca7bf858880&advanced=1&relative_organism_quantity=0.00001,*
