### ISSUE TITLE
In a Sampling-event paradigm, what would be the best way to represent sampling at three depths at the same sampling point?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2249]
**In a Sampling-event paradigm, what would be the best way to represent sampling at three depths at the same sampling point?**

Dear sir or madam,

I'm relatively new to Darwin Core and GBIF, so I apologize if the question is too simple.

What should be the best way to represent my data in Sampling-event, considering that for the same sampling point in a river I need to collect three water samples at three different depths? Would there be a rule to express this?

Thank you in advance.

Kind regards,

Daniel

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/384776f6c30082028c1db8665835b9c3:a532876015239f921a46d7d01706878c10252d5b3f0b134548b7ebc7e8a56bac3b5f3f0d5a7af392b74bfc9e70abd34c184ae9ac14abc4ed595681fa95d2779c)
System: Chrome 77.0.3865 / Windows 10.0.0
Referer: https://www.gbif.org/user/confirm?username=dtrns&code=7a5ffba3-352a-44a3-bc17-17bf1b98ae1b
Window size: width 1454 - height 782
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-14T17:00:57.107Z',mode:absolute,to:'2019-10-14T17:06:57.107Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-14T17:00:57.107Z',mode:absolute,to:'2019-10-14T17:06:57.107Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by albenson-usgs** [comment]
Each of those sampling events would have their own unique eventID. So the decimalLatituide and decimalLongitude would be the same for three unique eventIDs but the minimumDepthInMeters and maximumDepthInMeters would be different for each of those three unique eventIDs and there would be unique occurrences for each of those three unique eventIDs.
