### ISSUE TITLE
can't login to demo.gbif.org

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#225]
**can&#39;t login to demo.gbif.org**

I can login to www.gbif.org to make downloads.
(account created years ago)

But I can&#39;t use those credentials to login demo.gbif.org

Is this normal?

-----
fbitem-90ca04c707cd953f778e8789ed7ec98e67b20053
Reported by: sant.herbarium@gmail.com
System: Chrome 49.0.2623 / Windows XP 0.0.0
Referer: https://demo.gbif.org/occurrence/gallery?publishing_org=def87a70-0837-11d9-acb2-b8a03c50a862&taxon_key=5015
Window size: width 1024 - height 707
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-27T19:44:14.039Z',mode:absolute,to:'2017-06-27T19:50:14.039Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-27T19:44:14.039Z',mode:absolute,to:'2017-06-27T19:50:14.039Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
Yes, this is expected at the moment due to the server moving that has been going on.  This is still in demo, and not all functionality is working, but once it is live, the login will of course work

**Comment by timrobertson100** [comment]
@MattBlissett Can we please try and open the labs identity DB tomorrow?

**Comment by MattBlissett** [comment]
I've restarted it; presumably it didn't restart automatically after the power cut out.

If it's become part of our semi-production/demo service, it deserves a Nagios monitor.

**Comment by timrobertson100** [comment]
Thanks!  I'll mail David
