### ISSUE TITLE
When preparing a dataset in DwC format, there is always the doubt of whcih terms are indexed individualy and available for search or shown in gbif.org. An examplie: preparing a sampling event dataset, with environmental data associated to each event, should I decide to use dynamicProperties term or the DwC MoF extension. Is there a list with information to what is the processing and result of each DwC term as shown in gbif.org?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2251]
**When preparing a dataset in DwC format, there is always the doubt of whcih terms are indexed individualy and available for search or shown in gbif.org. An examplie: preparing a sampling event dataset, with environmental data associated to each event, should I decide to use dynamicProperties term or the DwC MoF extension. Is there a list with information to what is the processing and result of each DwC term as shown in gbif.org?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/07958c12c3bbd5ce664961ce84fa8c1a:b1577e3d90db40cb91c98f5f799436c81429d2fd8f7c378face3c2c317e1804352b628dc721a08883793bb402f7452d74debd3950e3438b7d835f6a6d3dde807)
System: Firefox 69.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/dataset/0d862dd2-12af-4445-92c9-d81d76598b19/event/2742
Window size: width 1440 - height 733
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-16T07:13:25.053Z',mode:absolute,to:'2019-10-16T07:19:25.053Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-16T07:13:25.053Z',mode:absolute,to:'2019-10-16T07:19:25.053Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
## Present

The search API supports these fields: https://www.gbif.org/developer/occurrence#parameters

All of the data should be available through the API for the individual occurrences.

**Dynamic properties**
Not available for search. But are on individual records e.g. https://api.gbif.org/v1/occurrence/2237852970
`"dynamicProperties": "{\"Substrate\":\"dead wood (including bark)\"}"`

but the field is not parsed in any way and usage varies. Some use JSON, other pipe separated key:values others prose descriptions.

**MoF**
Again it is available for individual records, but not searchable and you need to go the fragment.
e.g. https://api.gbif.org/v1/occurrence/1949673254/fragment

## Future
We have recently started indexing extensions (such as MoF) to make them available for search, but it is not ready for public consumptions just yet. We have not discussed what to do with dynamicProperties, but one approach could be to try to parse them and make them searchable as key:value pairs.
