### ISSUE TITLE
species name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2253]
**species name**

I tend to doubt that
Galagoides demidoff
and
Galagoides demidoffi
are BOTH accepted names. One or the other, surely?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b09980e8075b314f8bbcf709cbe38dc2:1232e7da0ea50a690baba57235796f0d475f1303a39e1bc7d21e4ad13a8884cdfa1891198d8191f74e8e628a33a63b38ae96271e6d1a5d1e75c14d3017874ede)
System: Firefox 69.0.0 / Mac OS X 10.9.0
Referer: https://www.gbif.org/species/9004030
Window size: width 1164 - height 782
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-20T23:48:21.023Z',mode:absolute,to:'2019-10-20T23:54:21.023Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-20T23:48:21.023Z',mode:absolute,to:'2019-10-20T23:54:21.023Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Galagoides demidoffi has been deleted when we removed the GBIF Type Specimen Names checklist from he backbone (it might have been a mistranscribed label)
