### ISSUE TITLE
Contacts title tab displays as a variable

### ISSUE THREAD

**Issue by muttcg** [gbif/portal-feedback#2254]
When you go to https://www.gbif.org/contact-us web browser tab title displays as "contactUs.title" instead of "Contacts"

**Comment by thomasstjerne** [comment]
Cannot reproduce

**Comment by MortenHofft** [comment]
![Screenshot 2019-10-28 at 14 34 47](https://user-images.githubusercontent.com/6759267/67682653-27cf1380-f990-11e9-8094-02d59bbc75cb.png)
