### ISSUE TITLE
I have been looking for a description for the institution and collection code fields.  Can you tell me how I can find them?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2255]
**I have been looking for a description for the institution and collection code fields. Can you tell me how I can find them?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4c9f9e85c99e205210283ab7cbca38fd:a85cd6c89f86f510d10be12b19a5fa7e9ba7f34715de5b4316b3f0743d16f38baef4cff120d82f161de30a39004cb5c0e47f06ad1596fa70ac4bb8f7bd8bf500)
System: Chrome 77.0.3865 / Windows 7.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 1009
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-21T20:49:24.539Z',mode:absolute,to:'2019-10-21T20:55:24.539Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-21T20:49:24.539Z',mode:absolute,to:'2019-10-21T20:55:24.539Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> Most of the fields available in GBIF are Darwin Core terms. The definitions for these terms are maintained by TDWG.
> You can find a description for these fields in the following links:
> * https://dwc.tdwg.org/terms/#dwc:institutionCode
> * https://dwc.tdwg.org/terms/#dwc:collectionCode
 
> If you have any question, you are also very welcome to check the Darwin Core Questions & Answers Site: https://github.com/tdwg/dwc-qa
