### ISSUE TITLE
image links broken

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2258]
**image links broken**

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/4ec69e5e9bce6baa2904b60b4a5fc030:d665344ebffbc9f6890b9756a3760f7e416ece0ddfbcebda81046acdc14af936525360c504e83ebe1ef5a5fa1346ac071efd0b527436f1a412bdb03804145a23)
System: Chrome 77.0.3865 / Mac OS X 10.14.6
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=1d31211e-350e-492a-a597-34d24bbc1769
Window size: width 1420 - height 625
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-23T07:16:11.189Z',mode:absolute,to:'2019-10-23T07:22:11.189Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-23T07:16:11.189Z',mode:absolute,to:'2019-10-23T07:22:11.189Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Fixed (I was discussing this one with Kew staff yesterday).
