### ISSUE TITLE
How do I update my email address in my account?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2259]
**How do I update my email address in my account?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/66516899b12a9b11262fd867323b07ff:552385a924e5c64c90453e9104d7cde29da71bf3404336fa9e1367acd7e38c47fef39f820e3f5019cf75a5e1cefea243e06abf3769e07651da81dbab3ba87c50)
System: Firefox 69.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0028750-190918142434337
Window size: width 1920 - height 966
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-24T14:50:38.375Z',mode:absolute,to:'2019-10-24T14:56:38.375Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-24T14:50:38.375Z',mode:absolute,to:'2019-10-24T14:56:38.375Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
To update your email, you need to write to helpdesk@gbif.org and send us your new address.
I hope you will see this message, I tried writing to you but I guess your old email is already inactive.
