### ISSUE TITLE
some filters do not work when browsing the gallery

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#226]
**some filters do not work when browsing the gallery**

Issue in demo.gbif.org/occurrence/gallery 

When I use some filters (Scientific name, or country, for example) the images in the gallery are filtered correctly.

But one important filter, the Type Status, has not any effects.

Type status is one of the most useful image filters for taxonomists, since their most wanted images are probably those of type specimens.

-----
fbitem-90ca04c707cd953f778e8789ed7ec98e67b20053
Reported by: sant.herbarium@gmail.com
System: Chrome 49.0.2623 / Windows XP 0.0.0
Referer: https://demo.gbif.org/occurrence/gallery?country=FR&publishing_org=def87a70-0837-11d9-acb2-b8a03c50a862
Window size: width 1024 - height 707
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-27T19:50:33.412Z',mode:absolute,to:'2017-06-27T19:56:33.412Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-27T19:50:33.412Z',mode:absolute,to:'2017-06-27T19:56:33.412Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
I have confirmed this and this is not restricted to the gallery.  
Type status filters are not changing the search results at all.

**Comment by dgasl** [comment]
Mmmm 

Regarding my problem to filter images which correspond to Types, it can be solved using the "advanced" filtering (sorry I didn't discover it until now). 

If I use "advanced", then tye Type Status filter works as expected (I only see images of type specimens).  

And this also works with the search results.
So the "issue" is somehow solved, but anyway, this way to solve it is not intuitive: 
How do we know which filter concepts are supposed to work only if I click "advanced"? 

The "advanced filter concepts" should be hidden when "advanced" is not selected, I guess.

**Comment by MortenHofft** [comment]
yes that is no good. We recently moved type status from advanced to a standard filter due to feedback that it was so frequently used, that is should be immediately available. I forgot to "move" it completely. Should be fixed and will be available in next build. thanks for reporting
