### ISSUE TITLE
Citation link doesn't display correctly on download page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2260]
**Citation link doesn&#39;t display correctly on download page**

I see the message:

Unless \[GBIF discovers citations\](/literature-tracking) of this download, the data file is eligible for deletion after April 25, 2020.

Where  \[GBIF discovers citations\](/literature-tracking) displays as a tag, instead of a link

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8fcbe33d82bf363829d41dd57264d520:0e221917a4f2fa09ad3be1c0dc09dbcc13a9af970bef19a505998cb54bd377c1ab370316e7ab7c2c4882046f53cc4543e41def1af4aaef1464d5fed4cd9ca4fb)
System: Chrome 77.0.3865 / Linux 0.0.0
Referer: https://www.gbif.org/occurrence/download/0029109-190918142434337
Window size: width 2327 - height 1211
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-25T06:52:23.137Z',mode:absolute,to:'2019-10-25T06:58:23.137Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-25T06:52:23.137Z',mode:absolute,to:'2019-10-25T06:58:23.137Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
https://crowdin.com/translate/gbif-portal-en/134/endk-en#q=unless

@dnoesgaard Not all fields allow markdown. This one doesn't and is therefore shown exactly as above (no link). Please create an issue if you need markdown in a new field, then I will check that it will be compiled.

**Comment by dnoesgaard** [comment]
Link removed for now.
