### ISSUE TITLE
NLBIF or GBIF?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2262]
**NLBIF or GBIF?**

Good morning,  just a simple question. We are now uploading our data via NLBIF to the GBIF community. Would it be simpler to upload directly to the GBIF-IPT or should we continue using the NLBIF-IPT? What would be the difference?
Kind regards
Frans Slieker
Natural History Museum Rotterdam

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4192010594e50364a6341ca4bccbd632:c68c957a61259cf6bceb7393fe44c81d668236c1abd23ba29f1fa033ead5339a397673ab4cf6b7273aa99892e6a14df96792f4b7a5e92be2c5fcfbdcf063d8da)
System: Firefox 70.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 966
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-28T08:17:07.727Z',mode:absolute,to:'2019-10-28T08:23:07.727Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-28T08:17:07.727Z',mode:absolute,to:'2019-10-28T08:23:07.727Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Answered by email.
