### ISSUE TITLE
https://www.gbif.org/restricted doesn't exist

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2263]
**`https://www.gbif.org/restricted` doesn&#39;t exist**

I tried to make a download and got a message, that my access is temporarily restricted and button with a link when I pressed to the link I got page 404

`https://www.gbif.org/restricted`

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4a35aa467773fb44e6efa310d21a9af5:ac380eeef911051510b334557c5bc27f61e7c03e0a461c822a1e7eb8c8b0e99b356c1d40dc104d329a95b3005a553126deea9870cb50cc6071f6be634b700bdc)
System: Chrome 77.0.3865 / Linux 0.0.0
Referer: https://www.gbif.org/restricted
Window size: width 2327 - height 1211
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-28T09:53:06.194Z',mode:absolute,to:'2019-10-28T09:59:06.194Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-28T09:53:06.194Z',mode:absolute,to:'2019-10-28T09:59:06.194Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I had changed the url in contentful, but not in code.
