### ISSUE TITLE
Field Museum: duplicate images

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal-feedback#2264]
This is fairly minor, but I noticed it we have duplicate images from at least this Field Museum dataset: https://www.gbif.org/dataset/36f15a36-6b45-442e-9c31-cd633423aee0

https://www.gbif.org/occurrence/2350125790

I *think* we deduplicate images from basic DWC `associatedMedia` and (in this case) an Audubon core extension using the `identifier`, but in this case we have HTTP URLs for the former, and HTTPS URLs for the latter.

(We could also detect this.)

**Comment by ManonGros** [comment]
Contacted by email.

**Comment by ManonGros** [comment]
They updated their Darwin Core and check the other datasets as well.
