### ISSUE TITLE
Dataset failing ingestion due to unacceptable metadata

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2266]
**Dataset failing ingestion due to unacceptable metadata**

The contact João Lanna has the organization "J".

This isn't accepted by the API, the organization needs a minimum length of 2 (or 3? I can't remember) letters to be accepted.

Once this is fixed, and the dataset republished, the license will be recognized and the data ingested.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d20804effcbbc16bfb07398b79f39f8f:1e4636e390da60f2922f2f7e077d49c5e5b30942bc0e42b41a47486715aaa5450234e2cbeb70e22fb167e9a86e5ab85cc1302abdf18da0129c24167fb9b6b0f0)
System: Firefox 69.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/dataset/e6694e54-1cd6-4527-a26e-387518ea550a
Window size: width 1276 - height 1226
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-29T15:13:43.054Z',mode:absolute,to:'2019-10-29T15:19:43.054Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-29T15:13:43.054Z',mode:absolute,to:'2019-10-29T15:19:43.054Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Publisher contacted by email.
