### ISSUE TITLE
Is there a list with the Institution Codes used for preserved specimen?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2268]
**Is there a list with the Institution Codes used for preserved specimen?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9f154cf1e8f327ce2b61b9b40b06e69d:3dd5330bd65ab7f4ae3a9ae14eef63c57ce2ba82f9d5e242d07254a998e2d4431360396a3dcd393b29b5719bb3b5dcb20bbb1a83278e41d6a31f2cd81cfb42c7)
System: Chrome 77.0.3865 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/4fa894f4-b6c6-4ec0-b816-9bb03b3ca106
Window size: width 1920 - height 968
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-29T21:06:59.974Z',mode:absolute,to:'2019-10-29T21:12:59.974Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-29T21:06:59.974Z',mode:absolute,to:'2019-10-29T21:12:59.974Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
You can get them through the API. There are only 3192 I see
Here are some examples - as you can see publishers use the field is different ways

```
k,lisc,srgh,wag
mhn-unm de san marcos
plantae ab a. becherer collectae
rmcdiversity.be/africanrodentia/specimen/show/42105
zoologische staatssammlung münchen, munich
```

http://api.gbif.org/v1/occurrence/search?basisOfRecord=PRESERVED_SPECIMEN&limit=0&facet=institutionCode&facetLimit=100&facetOffset=100

facetLimit: how many results
facetOffset: where to start

See also https://www.gbif.org/developer/occurrence#search
