### ISSUE TITLE
Display issue of country in Programme/Events

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#227]
**Display issue of country in Programme/Events**

country.{&quot;sys&quot;:{&quot;type&quot;:&quot;Link&quot;,&quot;linkType&quot;:&quot;Entry&quot;},&quot;id&quot;:&quot;ES&quot;}

-----
fbitem-2685271de3ece2ea1bc629a115e92efe03e98182
Reported by: @cgendreau
System: Chrome 58.0.3029 / Mac OS X 10.10.5
Referer: https://demo.gbif.org/programme/82953/living-atlases#events
Window size: width 1440 - height 733
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-29T06:56:48.559Z',mode:absolute,to:'2017-06-29T07:02:48.559Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-29T06:56:48.559Z',mode:absolute,to:'2017-06-29T07:02:48.559Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
thanks chris. The es api had changed and things in my end hadn't been updated to match. closed by https://github.com/gbif/portal16/commit/ca1a461aed527da14c96a3cf5383825a069ce186
