### ISSUE TITLE
Gonepteryx amintha subsp. formosana (Fruhstorfer, 1908) is not a homotypic synonym of Hebomoia glaucippe subsp. formosana Fruhstorfer, 1908

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2271]
**Gonepteryx amintha subsp. formosana (Fruhstorfer, 1908) is not a homotypic synonym of Hebomoia glaucippe subsp. formosana Fruhstorfer, 1908**

Although both Gonepteryx amintha subsp. formosana (Fruhstorfer, 1908) (`https://www.gbif.org/species/6133463)` and Hebomoia glaucippe subsp. formosana Fruhstorfer, 1908 (`https://www.gbif.org/species/6133470)` come from the National Checklist of Taiwan, they are not synonym in that checklist.

See the rest of message received on helpdesk:
> This is likely because the square shape of four wings and their four spots appeared in images of Hebomoia glaucippe subsp. formosana Fruhstorfer, 1908 are characteristics of Gonepteryx amintha (Blanchard, 1871) (`https://www.gbif.org/species/1920718).`
> I think that Hebomoia glaucippe subsp. formosana Fruhstorfer, 1908 accepted in GBIF was replaced with Gonepteryx amintha subsp. formosana (Fruhstorfer, 1908) (for details, see `https://www.gbif.org/occurrence/1934782773)` and should not have been included in immediate children of Hebomoia glaucippe (Linnaeus, 1758) (`https://www.gbif.org/species/1919951).`
> As a result, Gonepteryx amintha subsp. formosana (Fruhstorfer, 1908) should be included in immediate children of Gonepteryx amintha (Blanchard, 1871).

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/5ead82bb1457704e9e287b92c89ab138:72336aa0db9f90acd59886661f04a511e6779cc83a3411d9746c59b905bc77bd0481520c808c241eb5a1304fec213a50d811e6a356c4ba26f45d894d7a3fde29)
System: Safari 13.0.3 / Mac OS X 10.15.1
Referer: https://www.gbif.org/species/6133463
Window size: width 1843 - height 960
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-30T15:13:34.093Z',mode:absolute,to:'2019-10-30T15:19:34.093Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-30T15:13:34.093Z',mode:absolute,to:'2019-10-30T15:19:34.093Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The issue has been fixed in the new backbone.
