### ISSUE TITLE
Missed levels after Kingdom for Columbigallina cruziana

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2273]
**Missed levels after Kingdom for Columbigallina cruziana**

The link - `https://www.gbif.org/species/9132903`

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c06a24273767843204797d532b308438:3a0f81a1d49e4d3442e6d30746dce78de4973185e1db17d90af9fb63c370322a05a727e07818277032c6ec860c14f7afa395649a7d88f1d5914a9ea4964f049c)
System: Chrome 78.0.3904 / Linux 0.0.0
Referer: https://www.gbif.org/
Window size: width 2327 - height 1211
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-31T09:40:22.831Z',mode:absolute,to:'2019-10-31T09:46:22.831Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-31T09:40:22.831Z',mode:absolute,to:'2019-10-31T09:46:22.831Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Columbigallina cruziana is not included in the new backbone taxonomy: https://www.gbif.org/species/search?q=Columbigallina%20cruziana
