### ISSUE TITLE
potential duplicate records

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2274]
**potential duplicate records**

details reported by user in this thread:
`https://twitter.com/ZSiders/status/1189536564486950913`

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/fdaeaad163482f7f4333927ce9dd0763:28025208552ff02dbd571e7b354e971a13117161ae698edcf6641111326c873f409000d72a6c3912095beb3a54c9a40d8d2b44ea0409ec7000250ff9a6219b60)
System: Chrome 78.0.3904 / Mac OS X 10.14.6
Referer: https://www.gbif.org/occurrence/search?country=AU&taxon_key=2420637
Window size: width 2026 - height 1113
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-31T10:22:59.328Z',mode:absolute,to:'2019-10-31T10:28:59.328Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-10-31T10:22:59.328Z',mode:absolute,to:'2019-10-31T10:28:59.328Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
A [sampling event](https://www.gbif.org/occurrence/search?dataset_key=dce8feb0-6c89-11de-8225-b8a03c50a862&advanced=1&event_id=urn:australianmuseum.net.au:Events:1210824) with 6 occurrences of the same species. The data comes from the [same dataset](https://www.gbif.org/dataset/dce8feb0-6c89-11de-8225-b8a03c50a862). ALA marks them as [potential duplicates](https://biocache.ala.org.au/occurrences/38d3bc35-d73e-4a11-8dc8-b1750f8001de).

**Comment by ManonGros** [comment]
In addition to that, it seems that some records from the [Museums Victoria provider for OZCAM](https://www.gbif.org/dataset/39905320-6c8a-11de-8226-b8a03c50a862) could be several DNA samples taken from the same individuals:
https://www.gbif.org/occurrence/search?basis_of_record=MATERIAL_SAMPLE&country=AU&dataset_key=39905320-6c8a-11de-8226-b8a03c50a862&taxon_key=2420637

**Comment by jhnwllr** [comment]
Not sure what we can do here. It is known that many datasets that publish material samples, publish multiple samples from the same individual. 

I think we should close this since it is a known problem, but with no clear guidance available for publishers. And I don't see much value in keeping this particular instance documented as an open issue.

**Comment by ManonGros** [comment]
I agree that we can close the issue. It seems that these duplicate "specimens" are in fact samples from the same individual. My guess is that those would be clustered if the clustering function ran within datasets.
