### ISSUE TITLE
CONTINENT_INVALID flag inconsistent

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2276]
**CONTINENT_INVALID flag inconsistent**

Some records are flagged as CONTINENT_INVALID but other records with the same type of data aren't: `https://www.gbif.org/occurrence/search?country=BO&dataset_key=ba0c03ab-fa61-4a3c-8db7-35c8c3454168.`

Plus the flag is not visible on the occurrence pages. Would it be possible to check what is happening?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/e1e385f51ed0217d0f332a7b35963b1d:a8af2ba527b4715d283e049ded5fa6ed77ca259235b22cf7ceb022ea96902f78396bb225c4ec7999f00f1e804eff011e50b1ecadeeeb15f44533f2f155375555)
System: Safari 13.0.3 / Mac OS X 10.15.1
Referer: https://www.gbif.org/occurrence/search?country=BO&dataset_key=ba0c03ab-fa61-4a3c-8db7-35c8c3454168&issue=CONTINENT_INVALID
Window size: width 1466 - height 900
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-01T08:38:23.303Z',mode:absolute,to:'2019-11-01T08:44:23.303Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-01T08:38:23.303Z',mode:absolute,to:'2019-11-01T08:44:23.303Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
I think this is fine now.  "Amérique" isn't specific enough, as we have a north and south America.
