### ISSUE TITLE
Link back to Wikidata

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#228]
**Link back to Wikidata**

As per title 
https://www.wikidata.org/wiki/Q35255#P846

From the Wikidata page, there are links to all wikimedia pages about the topic, in all wikimedia languages available. For instance 102 for this particular species.

-----
fbitem-species2435099
Reported by: @Daniel-Mietchen
System: Firefox 54.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/species/2435099
Window size: width 1332 - height 759
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-29T16:44:45.735Z',mode:absolute,to:'2017-06-29T16:50:45.735Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-29T16:44:45.735Z',mode:absolute,to:'2017-06-29T16:50:45.735Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
Wikidata could also be part of the solution for stable org. ids as well, https://github.com/gbif/portal16/issues/251

**Comment by MortenHofft** [comment]
I like the idea. It would be nice to have some stable information we could link to. 

We have tried incorporating Dbpedia to have species descriptions, but we didn't manage to do something that wasn't occasionally completely off (e.g. linking Argentina Hill to a hill in argentina) - and decided that there was too many false positives to proceed for now. It is a decision we could revisit in the future.

@Daniel-Mietchen do you have experience linking to wikidata and do you have an idea of how solid it would be for GBIF usage? I must admit I do not know their API

dbPedia issue here: https://github.com/gbif/portal16/issues/53

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/441
