### ISSUE TITLE
Character encoding issue and pseudo-duplication in new Korean dataset

### ISSUE THREAD

**Issue by Mesibov** [gbif/portal-feedback#2280]
Following this just-published tweet
https://twitter.com/GBIFDodo/status/1191262513775759361
I downloaded the DwC source archive from
https://www.gbif.org/dataset/c6b0f7e3-5fd9-4566-8fd4-8f12c26fa8b6

There are two problems with the dataset. The first is that the dataset is in UTF-8 encoding, but locality and vernacularName fields contain entries with numerous Korean characters not properly encoded to UTF-8, e.g.:
"강원도 동해시 송정동 1283-8".

The second problem is that scientificName has not been cleaned for pseudo-duplicates, e.g.

7       Kichulchoia multifasciata (Wakiya and Mori, 1929)
2       Kichulchoia multifasciata (Wakiya And Mori 1929)
12      Kichulchoia multifasciata (Wakiya And Mori, 1929)

The pseudo-duplications are carried over into the occurrence records, e.g. in
https://www.gbif.org/occurrence/2446771704 (see also the locality field in this record for character encoding failures).

**Comment by MortenHofft** [comment]
> There are two problems with the dataset. The first is that the dataset is in UTF-8 encoding, but locality and vernacularName fields contain entries with numerous Korean characters not properly encoded to UTF-8, e.g.:
"강원도 동해시 송정동 1283-8".

I do not read Korean, but isn't `강원도 동해시 송정동 1283-8` just an address? Google displays it as such. Street number `1283-8`.

**Comment by MortenHofft** [comment]
> The second problem is that scientificName has not been cleaned for pseudo-duplicates, e.g.
7 Kichulchoia multifasciata (Wakiya and Mori, 1929)
2 Kichulchoia multifasciata (Wakiya And Mori 1929)
12 Kichulchoia multifasciata (Wakiya And Mori, 1929)

Indeed that is unfortunate that the data is provided as such. They are all mapped to the same taxon in GBIF though. They all say
`GBIF Taxon interpretation: Kichulchoia Kim, Park & Nalbant, 1999` But we also show the verbatim name (we show both the verbatim and the normalized, in case we have mistakenly mapped the name)

**Comment by MattBlissett** [comment]
This is also an issue with the taxonomic backbone, which is missing this name.

If we had *Kichulchoia multifasciata* in the backbone, these records would be matched to it, and the small typographic differences in the source data would not be seen by most users.

We see the name only in the [NCBI taxonomy](https://www.gbif.org/species/104652087), which is not used to create the GBIF backbone.

**Comment by Mesibov** [comment]
@MattBlissett Don't you give feedback to providers about cleaning their data? Pseudo-duplication variants can create problems for GBIF if parsing fails to give you a string you can match to the backbone.

@MortenHofft I tried a number of original encodings with iconv to get the original Korean characters into UTF-8, where they would display properly: euc-kr, cp949, iso-2022-kr, etc. Each converted some of the characters but all gave "illegal input sequence at postion..." messages.

Is there a reason why GBIF should not display correct Korean characters in UTF-8? Perhaps you could contact the data provider to learn what encoding was used originally and along the way to upload.

**Comment by MattBlissett** [comment]
We don't actively send data quality reports to data providers. Issues are marked against each occurrence, and summarized on the [metrics page for a dataset](https://www.gbif.org/dataset/c6b0f7e3-5fd9-4566-8fd4-8f12c26fa8b6/metrics).

I don't see any problem with the encodings on this dataset.  Could you give a shell script one-liner showing the problem?

```
$ curl -Ss https://api.gbif.org/v1/occurrence/2446771704 | jq .locality
"경상북도 성주군 수륜면 남은리 1259-1"

$ unzip -p dwca-nsmkfish2019-v1.0.zip occurrence.txt | iconv -f utf-8 > /dev/null
# No errors

$ unzip -p dwca-nsmkfish2019-v1.0.zip occurrence.txt | cut -d$'\t' -f 11 | uniq | head -n 10
locality
전라남도 순천시 승주읍 죽학리 756-6
전라남도 순천시 송광면 장안리 161
전라남도 순천시 주암면 복다리 785-2
전라남도 순천시 주암면 행정리 442
전라남도 순천시 주암면 갈마리 488-13
전라남도 순천시 승주읍 봉덕리 690-35
전라남도 순천시 송광면 신평리 705-4
전라남도 순천시 송광면 봉산리 647-1
전라남도 순천시 낙안면 석흥리 721
```

**Comment by Mesibov** [comment]
@MattBlissett  Apologies, it's a font issue. The characters are indeed UTF-8 and display properly with a Korean-aware font - I've installed nanum and all original characters are now clear. Does this point at another problem for GBIF data users, most of whom would not be using a Korean-aware font? Or do you assume that anyone interested in GBIF records from Korea would already be using a suitable font?

"We don't actively send data quality reports to data providers." I think I knew that (https://data-blog.gbif.org/post/search-download-analyze-cite/; datafixer comment), just confirming. It's one of the reasons data remains messy at source (http://iphylo.blogspot.com/2018/09/guest-post-quality-paralysis.html, number 14).

**Comment by Mesibov** [comment]
@MattBlissett A recommendation to the data provider would be to use Latin as well as Korean characters, e.g.
전라남도 순천시 승주읍 죽학리 756-6 (756-2 Jukhak-ri, Seungju-eup)
Will GBIF make that recommendation, or should I do it?

**Comment by ManonGros** [comment]
We have been in touch with the Korean publishers this summer and from what I understand they are at maximum capacity. I don't think that they have the resources necessary to go over their database and update/translate all the locality names.

**Comment by MattBlissett** [comment]
Thanks Bob.

I think it's reasonable for us to assume someone who reads Korean has a suitable font installed.  With a quick test around the office, our fairly average Windows and Mac computers and Android/Apple phones already include a suitable font for Korean. My Linux one does too, but I can't remember if it came by default.

> A recommendation to the data provider would be to use Latin as well as Korean characters ... Will GBIF make that recommendation, or should I do it?

As far as I understand it, GBIF won't request that.  Changing/creating that policy would need to be discussed with the participation team, e.g. Tim Hirsch.  

From a data quality view, I think it could be an additional source of errors (there are presumably multiple transliteration schemes, and some probably require non-ASCII characters, or else introduce ambiguity -- this would be the case with Chinese writing).  As someone who doesn't understand Korean, "Jukhak-ri, Seungju-eup" isn't really more helpful to me than "전라남도 순천시 승주읍 죽학리". I would save the effort for scientific names and other values, which we do occasionally see in other languages.

I've created an issue for the missing name: https://github.com/gbif/portal-feedback/issues/2282 so I don't think there's anything left to do here,

Cheers,

**Comment by timhirsch** [comment]
Since I am called out here: I would need to take advice from those closer to data publication guidance e.g. @laurarussell what current recommendations are and the implications for recommending always to include Latin characters. While I can see real benefits in recommending dataset metadata to be in English as well as local language, to help in assessing methodologies and fitness for use of the data, I am not so sure what the added value would be of always transcribing locality names or vernacular names in Latin script. For the first, I suppose the main benefit could be helping an international user verify a location against lat/long coordinates, or even carry out georeferencing - but as Matt suggests, this may not be any more useful than original script for these purposes. Those more familiar with typical gazetteering practices would be better placed to advise. Equally (maybe even more so) the relevance of a transcribed vernacular name, as opposed to original script, is not obvious to me - the user most interested in a vernacular name is going to be able to read the original, and the transcribed version will not mean much to others.  At least it would be a point for discussion rather than making assumptions about our recommended practice.
