### ISSUE TITLE
What would be the best way of representing microscope slides in parasite-host DwC-As?

### ISSUE THREAD

**Issue by dtrns** [gbif/portal-feedback#2281]
Hey, everybody,

I need to build a DwC-A Sampling-event that displays the parasitism relationship between collected fishes and their endoparasites. However, this time I would also need to associate the parasites to the microscope slides in which they were found. Would there be any extension or standard procedure for dealing with situations like this?

I'll leave this diagram here to try to illustrate the problem.

![parasite_slides](https://user-images.githubusercontent.com/56555253/68141491-66267e80-ff0c-11e9-947b-a060182f0914.png)

Any help would be welcome!
Thank you for your support!

**Comment by dtrns** [comment]
Just to explain the need, the microscope slides will be deposited in a museum as vouchers.

**Comment by albenson-usgs** [comment]
Do you actually need an extension? Couldn't you just use the [associatedOccurrences](https://dwc.tdwg.org/terms/#dwc:associatedOccurrences) term to link the parasites to their associated fish? Then any necessary slide/museum voucher information could be included in the occurrence file for the parasites.

**Comment by nnsdtr** [comment]
Hi, @albenson-usgs!!
Thank you for your reply!! 😄

I have some difficulty understanding how Darwin Core works with GBIF. For this reason, it is more likely that I am making a mistake. So I really appreciate your help! =)

Can I have two occurrence.txt files in the same DwC-A? I mean, one for the hosts and the other for the parasites?

**Comment by dtrns** [comment]
Hi, @albenson-usgs!!
Thank you for your reply!! 😄

I have basic difficulties in understanding how Darwin Core works with GBIF Sampling-event pattern. For this reason, it is more likely that I am making a mistake. So I really appreciate your help! 😊

Can I have two occurrence.txt files in the same DwC-A? I mean, one for the hosts and the other for the parasites?

**Comment by albenson-usgs** [comment]
Hi @dtrns :-)

I think we're all still learning and experimenting with how best to implement the sampling event schema so to be honest my suggestion might not be the best way either. Hopefully others will jump in with their thoughts. 

To answer your question, no you would only have one occurrence file with both the hosts and the parasites together in the same file but there might be different information available based on whether the row is for a parasite or a host. For example:

occurrenceID           scientificName                          associatedOccurrences              decimalLatitude....
wu2974yshyf7         Oncorhynchus tshawytscha      hostOf: dyy2874asjhy19             68.635
dyy2874asjhy19      Henneguya zschokkei               parasiteOf: wu2974yshyf7          68.635

**Comment by dtrns** [comment]
Thanks again @albenson-usgs!!

Hmm... I don't know. What you said makes total sense to me, mainly because in fact both parasites and hosts end up being occurrences of the same event. However, the impression I get is that the organization of the data would be difficult for the common user to understand.

Separating the objects in different tables seems (at least for me) to bring more clarity to the hierarchical structure present in the relationship between Event, Host and Parasites. It is for this reason that I ended up thinking about adopting the [ResourceRelationship] extension (https://tools.gbif.org/dwca-validator/extension.do?id=dwc:ResourceRelationship) and that's why I'm hoping there's a way to represent the microscope slides in the context.

**Comment by dtrns** [comment]
Sorry, I accidentally closed the topic.

**Comment by ManonGros** [comment]
Thanks @albenson-usgs for your answers!

@dtrns With the Darwin Core schema, all the extensions have to be linked to the same Core (that's what is called the "star-schema"). If you decide to use a sampling-event core, you can't add and extension describing the occurrences.
I see two potential solutions around this limitation:
* The solution that Abby described in which you would use the `associatedOccurrences` term in the occurrence file and have all the host and parasites in the same file.
* Creating an occurrence dataset instead of a sampling-event dataset and using the `ResourceRelationship` extension to describe the relationship between the occurrences.

That being said, perhaps I am missing something. Anyone else have any input on the topic?

What type of information do you have available for your microscope slides? Voucher information and images could be integrated in the occurrence file.

**Comment by dtrns** [comment]
Hi, @ManonGros and @albenson-usgs!! 😄

Thanks for answering me, @ManonGros!! Hmmm... I see! I thought I could make a kind of "relational database" style with the dataset, but there's the star-schema limitation. 😕 So, maybe it's better to change from sampling-event to an occurrence dataset as you mentioned so I can keep the elements separate. 😊

But there's one thing I don't understand very well in the standard. Maybe you can help me. Both of you mentioned that I could use the term `associatedOccurrences` from the `Organism class` inside the `Occurrence file`. I thought I could only use terms from the Occurrence class inside the Occurrence file. So my question is: How is this flexibility in using the terms in the schema files determined? I mean, how can I know which terms are allowed to use where?

Thank you both for being so kind!

**Comment by ManonGros** [comment]
Hi again @dtrns 

I am not sure if the second option I suggested is the way to go. It also depends on what you would like to emphasise/show.

To check what you can and cannot map to your occurrence file, perhaps the best would be to just try directly in an IPT? This would allow you to experiment with the various mappings and dataset structure.
If don't have one, you could ask for an account on our test IPT: https://ipt.gbif.org. You can even use it to publish on our [test website](https://www.gbif-uat.org) and check how it would look on GBIF.
Just write to helpdesk@gbif.org to ask for an account.

**Comment by albenson-usgs** [comment]
Well the occurrence file actually can include terms from basically all of the categories down to Taxon from [here](https://dwc.tdwg.org/terms/) because you can provide occurrence only data to GBIF.

One thing you might want to note is that any data in any of the extensions will not be indexed by GBIF so it will not be available to users searching GBIF for information. Although I don't think associatedOccurrences is indexed either.

**Comment by dtrns** [comment]
Hi @ManonGros!

Great idea! I've sent an email to the helpdesk. Hopefully I'll find a solution.

Thank you for the support!

**Comment by ManonGros** [comment]
@dtrns please let us know if we should close this issue or if you have other pending questions.

**Comment by dtrns** [comment]
@ManonGros
