### ISSUE TITLE
Downloads not formatting correctly

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2283]
**Downloads not formatting correctly**

I am able to download occurrences fine, but when I try to view the data the csv provided just isn't working. Because a download needs to be re-formatted after downloading, using tab-delimited functions in excel this is causing a large proportion of the data to be forced into the wrong column. Unfortunately this is not consistent across all of the data lines, instead being apparently random thus making re-re-formatting manually almost impossible in any period of time less than 'days'. Is it possible for the initial downloads to be formatted correctly in the first place (i.e. columns fitting what is displayed on the website) rather than it all appearing in the first column and then the end user having to alter everything themselves please?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/99ac20715872e2dceb875a9567b8f35f:a9fc0f834c9349c1cd6992b7b5fc44811449831abd6e65a0af18e2ecb1b009c66c53688bce36c092833a35d5196a03ec138696154e464315728a06fd213fb120)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 969
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-06T16:10:50.804Z',mode:absolute,to:'2019-11-06T16:16:50.804Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-06T16:10:50.804Z',mode:absolute,to:'2019-11-06T16:16:50.804Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
