### ISSUE TITLE
<IH> appendeed to institution codes

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2284]
**appendeed to institution codes**

We write

>Due to the integration of several older datasets, and to avoid duplication of InstitutionCode, <IH> has been appended to all Index Herbariorum Herbarium codes.

But I do not see it on any institutions:
https://www.gbif.org/grscicoll/institution/3abc5362-3872-40b6-9994-3567268da2bd
states to be an Index Herbariorum Record but do not have start with `<IH>`. 

No appending IH seems somewhat reasonable as it isn't how it is used. Should we perhaps just remove the description?

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/ac8d86d97f1b160a5b9c0757ff056838:deeaacb946f6a8af924808557dc7ab8c10c7595676742a470fbff30a6d9214d9f0013ee063166779c4ae01826acae4984c6c1fdaf5737877fb8162c92fb57a73)
System: Chrome 78.0.3904 / Mac OS X 10.14.5
Referer: https://www.gbif.org/grscicoll/institution/search
Window size: width 2037 - height 1286
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-08T09:20:20.965Z',mode:absolute,to:'2019-11-08T09:26:20.965Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-08T09:20:20.965Z',mode:absolute,to:'2019-11-08T09:26:20.965Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Begin tagged "content" this falls under my responsibility, however, I don't know the history of this at all. So all I can say is that I agree with your logic. If we don't use the appendix, no reason to have the disclaimer. I've removed it from the [translation](https://crowdin.com/translate/gbif-portal-en/244/endk-en#18006) now.
