### ISSUE TITLE
Wrong genus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2287]
**Wrong genus**

This is Anubias heterophylla ENgler according to annotations on the sheet.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6d2a81dbb6ca6f5152c23dbb20b8b542:b972abe36b2356eac317bbdcb13e5db1979d06bc33c2c4e4f6dbd8951ff1b50723685ea0cde729123db8479448a60ca4e636bac588d457643dd7da62c4bdfeeb)
System: Firefox 70.0.0 / Windows 7.0.0
Referer: https://www.gbif.org/occurrence/1057640307
Window size: width 1600 - height 737
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-11T10:52:06.426Z',mode:absolute,to:'2019-11-11T10:58:06.426Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-11T10:52:06.426Z',mode:absolute,to:'2019-11-11T10:58:06.426Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 7e380070-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 19456090-b49a-11d8-abeb-b8a03c50a862

**Comment by ManonGros** [comment]
The name provided is _Anubias heterophylla_ Engl.
I think it is just a different nomenclature, I don't see the problem with that. The genus is still Anubias.
