### ISSUE TITLE
validator timestamps off

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2288]
**validator timestamps off**

Whenever you submit a file for validation, the validator immediately responds that the report was done 1 hour ago. Seems like there's a timezone offset problem or something?

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/5f7a2f5e61d84754c44b6b4ba15e4afe:0b0fa337f8db69edc948505fa01a0d5fcf0642f8538a845478fd5ca6281283a806b247605d4f3180acc48e3b1159673adcd6a316bfcc54d5c77ab4f1e8a666fc)
System: Chrome 78.0.3904 / Mac OS X 10.14.6
Referer: https://www.gbif.org/tools/data-validator/1568816669588
Window size: width 1870 - height 1172
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-11T11:54:07.314Z',mode:absolute,to:'2019-11-11T12:00:07.314Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-11T11:54:07.314Z',mode:absolute,to:'2019-11-11T12:00:07.314Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
See also #1530.
