### ISSUE TITLE
dataset occurrences count not working

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#229]
**dataset occurrences count not working**

In this page there are 4 datasets from the same publishing organization.

Two of them (SANT-Algae, SANT-Bryo) show the occurrences count in each one.

The other two (SANT, SANT-Lich) do not show any info about occurrences count.

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c

System: Chrome 49.0.2623 / Windows XP 0.0.0
Referer: https://demo.gbif.org/dataset/search?publishing_org=def87a70-0837-11d9-acb2-b8a03c50a862
Window size: width 1024 - height 664
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-29T18:15:59.580Z',mode:absolute,to:'2017-06-29T18:21:59.580Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-29T18:15:59.580Z',mode:absolute,to:'2017-06-29T18:21:59.580Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you for reporting - unfortunately this part of the API has been deprecated, so counts are wrong. The interface should remove counts completely or do it in a different way. I will look into it. Thanks.
