### ISSUE TITLE
grbio URI: h

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2290]
**grbio URI: h**

We have grBioURIs that are just a single letter. That seems like an easy clean up task in the database. I assume this is nonsense or am I missing something? Do we need to keep them for some reason?

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/7d1b0d928174555b769be80dc88d7b8c:3b600c6fc324c20a1c443089f7bf9e5feb155e9f40f5f72d2abb184555133bc9b960ac877d0290817b00a662152a72c233b4c7e5152c4662cf7b608e474e352a)
System: Chrome 78.0.3904 / Mac OS X 10.11.6
Referer: https://www.gbif.org/grscicoll/institution/afca95ad-fca2-4757-9d20-c3902120bed2
Window size: width 1841 - height 1245
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-14T20:20:20.575Z',mode:absolute,to:'2019-11-14T20:26:20.575Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-14T20:20:20.575Z',mode:absolute,to:'2019-11-14T20:26:20.575Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I found 3 other institutions with the same issue:

- https://registry.gbif.org/institution/3dab214b-81ca-4f3b-853a-561b20595631
- https://registry.gbif.org/institution/93826dc0-0181-4a1b-8bbf-c4012818d406
- https://registry.gbif.org/institution/1616f171-9f72-4114-be87-58399550879c

I removed the single letter identifier for all of them.
