### ISSUE TITLE
grBio URI reused on multiple institutions

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2291]
**grBio URI reused on multiple institutions**

The same identifiers are used for multiple institutions

e.g.
`http://biocol.org/urn:lsid:biocol.org:col:12909`
is used for
`https://www.gbif.org/grscicoll/institution/369c6bae-a55b-43bd-b4f5-53fc72b08cf2`
and 
`https://www.gbif.org/grscicoll/institution/5affd03a-8591-4558-933c-223b7ae75824`

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/6ebef280271eaf02faca1f2851ccda87:d66a093c9a313d2889e19c094e5a26e0650a3c11ebe4edb23b42a3f8d29f37c328597ead25aeca4e9cdf378d99557f85da4d12f55da9aafc0b765258ebbe7b40)
System: Chrome 78.0.3904 / Mac OS X 10.11.6
Referer: https://www.gbif.org/grscicoll/institution/369c6bae-a55b-43bd-b4f5-53fc72b08cf2
Window size: width 1841 - height 1245
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-14T20:24:53.013Z',mode:absolute,to:'2019-11-14T20:30:53.013Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-14T20:24:53.013Z',mode:absolute,to:'2019-11-14T20:30:53.013Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
i joined the two as it seemed uncontroversial. there is another example here https://registry.gbif.org/institution/search?q=Scripps%20Institution%20of%20Oceanography

**Comment by ManonGros** [comment]
I merged the two entries as one of them was labelled as "inactive". The duplication of identifiers is quite problematic since we advice publishers to use them in our FAQ about linking occurrences to GRSciColl.
We need to clean that up.

**Comment by ManonGros** [comment]
I have been looking for more duplicate identifiers for institutions and aside from the iDigBio UUIDs, there aren't any left.

But there are those 4 collections with the same identifier (urn:lsid:biocol.org:col:34777):

- https://registry.gbif.org/collection/910442b2-e0aa-46a9-b3dc-5a4efb1ed3a3
- https://registry.gbif.org/collection/dc806805-f05c-4a09-9d58-78743a9e8cd6
- https://registry.gbif.org/collection/cd251b9b-bfa1-40be-b303-d89e54a2513d
- https://registry.gbif.org/collection/c1613ee4-0696-4f7c-8cd7-ee0a53e71134
- https://registry.gbif.org/collection/0ff01dee-ef32-4dad-a51d-7927aba43274

I can see that these entries have been edited by one of our editors. Although they haven't added the identifiers specifically, I will contact them just to check.

**Comment by ManonGros** [comment]
I have removed the identifier from the collections, it is now only associated with the institution.
