### ISSUE TITLE
How do you sort alphabetically on species name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2295]
**How do you sort alphabetically on species name**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4785564067153d730eb313e0899876dd:4d7560b06cf9f5fff676289f0d82b8fe491634393105724f3f6ce662c80a73e3e101db91794e373e2ece5ad9855a051273206b06a071868e3803d2de7bc7aa76)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?taxon_key=2872218
Window size: width 1542 - height 936
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-18T22:23:17.386Z',mode:absolute,to:'2019-11-18T22:29:17.386Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-18T22:23:17.386Z',mode:absolute,to:'2019-11-18T22:29:17.386Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
You cannot I'm afraid. You can search for a species name and you can see a list of all distinct species. If you need sorting you need to download the data and analyse it locally.

I'm labelling this as a duplicate and vote for https://github.com/gbif/portal-feedback/issues/224
