### ISSUE TITLE
GrSciColl and IH: Duplicate institutions

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2297]
**GrSciColl and IH: Duplicate institutions**

2 x World Museum Liverpool

One is an IH record, the other describes that they also do zoology etc. They both have the same institution code. It is the same person, same address, same institution. 

It seems silly to have 2 entries.

But if we make them one and sync IH to this, then we throw away the information that this entity is much more than a herbarium.

`https://www.gbif.org/grscicoll/institution/33d66e93-b94f-4969-b8bd-726855c15238`

`https://www.gbif.org/grscicoll/institution/b246c7f9-5103-456a-bd2d-b3196e52b055`

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/6553478b9a39dce6898d73d03ae08de9:c6da60a3c8c31c344effc78a326d2b8c51f883b2a2f684a16b8ecd4ef2900491cfbe096be8a788ee4d64067eb602cb6401459a77d27018a6ae658fb30e2f15f0)
System: Chrome 78.0.3904 / Mac OS X 10.14.5
Referer: https://www.gbif.org/grscicoll/institution/33d66e93-b94f-4969-b8bd-726855c15238
Window size: width 2156 - height 1306
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-19T15:34:31.151Z',mode:absolute,to:'2019-11-19T15:40:31.151Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-19T15:34:31.151Z',mode:absolute,to:'2019-11-19T15:40:31.151Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@leo-buitrago resolved that duplicate. Closing the issue.
