### ISSUE TITLE
Incorrect spelling for author names from Zoobank

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2304]
Cheers; my name is Renzo Seminario, author of the publication Collembola of the Campanet cave (Mallorca, Balearic Islands), with descriptions of new species of Pseudosinella (Entomobryidae) and Oncopodura (Oncopoduridae); I would like to clarify that in my scientific names my last name is being misquoted by placing &quot;CORDOBA&quot; being the real name &quot;CORDOVA&quot;. I would appreciate correcting that mistake. thank you very much.. my e-mail is retonio1989@gmail.com

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ac3b980e18de7f3dd3b3574cd509c899:8184d0d8dda379db3a9ac78a27b021b877943dc25b40a2d360305e595cdfead097a2ba20b0e372339af0a2bb1509e1b1fce9e9647b88bb6f4ff2e2efaaf4da01)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/es/species/search?rank=SPECIES&name_type=SCIENTIFIC&advanced=1
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-21T07:16:00.545Z',mode:absolute,to:'2019-11-21T07:22:00.545Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-21T07:16:00.545Z',mode:absolute,to:'2019-11-21T07:22:00.545Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Dataset on GBIF.org: https://www.gbif.org/dataset/f82fd4e4-fc53-40eb-8644-83bc51c9417d
Original: https://biotaxa.org/Zootaxa/article/view/zootaxa.4532.1.2
Species search: https://www.gbif.org/species/search?rank=SPECIES&dataset_key=f82fd4e4-fc53-40eb-8644-83bc51c9417d&name_type=SCIENTIFIC&advanced=1

In all of these places the name is spelled the Córdova.

**Comment by ManonGros** [comment]
The issue seems to come from Zoobank.
See for example the species `Pseudosinella grauae Seminario-Córdoba, Baquero, Jordana & Vadell, 2018` https://www.gbif.org/species/1054061, which is also incorrectly spelled in Zoobank: http://zoobank.org/NomenclaturalActs/0d4fa4a5-404b-4719-9064-143af2daef93.

Therefore most of [the occurrences associated with the PLAZI treatment dataset](https://www.gbif.org/occurrence/search?dataset_key=f82fd4e4-fc53-40eb-8644-83bc51c9417d) are matched to incorrectly spelled names.

**Comment by ManonGros** [comment]
After Zoobank was notified, they corrected the issue on their side.
I also notified Renzo.

Now we just need to wait. Hopefully, the Zoobank IPT will be back online before we make a new backbone update.

**Comment by ahahn-gbif** [comment]
The resource as indexed in GBIF today (Zootaxa checklist) shows the author name correctly, see https://www.gbif.org/species/157318933. This does not automatically include it into the backbone version yet, though: https://www.gbif.org/species/10540612. Is it possible that descriptions of new species are not part of the dynamic process, @mdoering?

**Comment by mdoering** [comment]
> Is it possible that descriptions of new species are not part of the dynamic process?

Not sure what descriptions mean in this context.
Authorships in the backbone only change when we build a new backbone, so right now. 
And a nomenclator like ZooBank is taken as the reference for the correct spelling and will change whatever was given in other sources. Maybe we should reconsider that, but with ZB fixed the new nub should be fine. This is in the [new draft nub](http://backbonebuild-vh.gbif.org:9000/species/match?verbose=true&kingom=&phylum=&class=&order=&family=&name=Pseudosinella%20grauae):

> Pseudosinella grauae Seminario-Córdova, Baquero, Jordana & Vadell, 2018

**Comment by ManonGros** [comment]
the issue seem to be fixed in the new backbone
