### ISSUE TITLE
Literature associated with specific datasets

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2307]
**Literature associated with specific datasets**

Would it be at all possible to show the date of inclusion (and maybe allow sorting by that date) for literature associated with specific datasets?  As a collections manager I am in the habit of periodically checking these to include in our collection Google Scholar page (`https://scholar.google.com/citations?user=FdXNWeMAAAAJ&hl=en&authuser=1)` and potentially add specific references to specimens to our database.  As these references increase in number it is becoming increasingly difficult to parse out new materials from materials that I have added already necessitating me going through the full list each time.

Thanks, Andy

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/97a983b372a1347693ea498d559f993e:c50d00e58e31eef2d33b6c883374357b67ab6cba2eaaae1335068d14952ab768f086578c935239ad48f47c31dca80e30d1a726f26f0953e4a76436de1115f4fd)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?offset=20&contentType=literature&gbifDatasetKey=8f79c802-a58c-447f-99aa-1d6a0790825a
Window size: width 2133 - height 1409
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-21T16:07:40.800Z',mode:absolute,to:'2019-11-21T16:13:40.800Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-21T16:07:40.800Z',mode:absolute,to:'2019-11-21T16:13:40.800Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
We have an unofficial API here https://www.gbif.org/api/resource/search?contentType=literature&gbifDatasetKey=8f79c802-a58c-447f-99aa-1d6a0790825a&searchable=true which might be useful. It has a lot of dates, but I'm not sure what they all refer to. There is 2 created dates for example. @dnoesgaard you are likely to know.

**Comment by dnoesgaard** [comment]
Response sent by email:

> As suggested by my colleague Morten, you might use our content API to get the details you need.
>  
> To get to the API, simply insert “api/” in the URL:
>  
> https://www.gbif.org/resource/search?contentType=literature&gbifDatasetKey=8f79c802-a58c-447f-99aa-1d6a0790825a
>  
> https://www.gbif.org/api/resource/search?contentType=literature&gbifDatasetKey=8f79c802-a58c-447f-99aa-1d6a0790825a
>  
> This gives you the raw data including information on when the papers were found/added, etc.:
>  
> accessed is when our system discovered the paper
> created is when it was added to our internal database
> createdAt is when it was added to the index shown on the website
>  
> (the latter two are usually the same date)
