### ISSUE TITLE
Distribution is not entirely clear

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#231]
**Distribution is not entirely clear**

The distribution shows:

11 AUT-AU AUT-LI CZE-CZ CZE-SL GER HUN POL SWI 12 COR FRA-FR SPA-AN SPA-SP 13 ALB BUL GRC ITA-IT ROM TUE YUG-BH YUG-CR YUG-KO YUG-MA YUG-MN YUG-SE YUG-SL 14 UKR-UK
Source: missing

I am not sure how useful this is

-----
fbitem-species112581316

System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/species/112581316
Window size: width 1490 - height 1099
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-30T12:45:52.905Z',mode:absolute,to:'2017-06-30T12:51:52.905Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-30T12:45:52.905Z',mode:absolute,to:'2017-06-30T12:51:52.905Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
True, but this is a CoL species page and they unfortunately have a lot of unstructured distributions given as free text descriptions. I hope to get that handled in CoL+ a little better

**Comment by MattBlissett** [comment]
That looks like something that's come from the World Checklist , or similar.  It's a list of TDWG region codes.

Example with a map and names rather than codes: http://wfo.kew.org/taxon/urn:kew.org:wcs:taxon:381621

**Comment by mdoering** [comment]
Yes it is. CoL recommends to use TDWG codes, but this one comes in as a single text string as opposed to individual distribution records as it should be

**Comment by MortenHofft** [comment]
@thomasstjerne since you are looking at adding more distrubutions this might interest you

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/440
