### ISSUE TITLE
Add GBIF regions as standard filters for Country or area.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2310]
**Add GBIF regions as standard filters for Country or area.**

It would be very handy for making Metrics based visuals for presentations. Likely useful in the context of regional meetings. E.g. now I need the pie chart by Basis of record for Europe... will use the global one for now. Minor importance, nice to have category?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5cf0027a7469d6806bbfa528cd8bb263:a20af6e6b513c6ae8bf946cdb7f7862780e0f9b979338bfc11144344c983b252743a116ae65273f21aec2f23e704bd05267d40a71572846d7a46ccea24faf755)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/charts
Window size: width 1920 - height 1018
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-26T11:33:41.390Z',mode:absolute,to:'2019-11-26T11:39:41.390Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-26T11:33:41.390Z',mode:absolute,to:'2019-11-26T11:39:41.390Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@dnoesgaard We have continent in the API, which I believe is what we also call GBIF regions. I do not know what the preferred label is, but it should be possible to change the name in Crowdin. Currently it is called Continent on the website

**Comment by MattBlissett** [comment]
I don't think they're the same.

A GBIF member country can choose their region based on typical collaborations etc, but the continent is a geographic designation.

Israel is in GBIF region Europe, but continent Asia.

**Comment by dnoesgaard** [comment]
Definitely two different things. But having continent as a searchable facet is still nice—although the example @MattBlissett mentions highlights that this field is far from controlled, e.g.

https://www.gbif-staging.org/api/occurrence/search?country=IL&limit=0&facet=continent

**Comment by MortenHofft** [comment]
Perfect, then there is nothing to change. Except for perhaps adding an additional flag for continent coordinate mismatch

**Comment by dnoesgaard** [comment]
(@dschigel if you put your Github handle in when opening issues, you'll be notified of updates...)
