### ISSUE TITLE
Erroneous synonymy of Pachyta quadrimaculata (Linnaeus, 1758)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2312]
**Erroneous synonymy of Pachyta quadrimaculata (Linnaeus, 1758)**

`https://www.gbif.org/species/1136138`

From GBIF France: 
The french responsible of TAXREF  send me this message:  it seems that there is a mistake in the GBIF backbone around these species 

Eburia quadrimaculata (Linnaeus, 1767) (M en FR, D en Guadeloupe) is NOT a synonym of 

 Pachyta quadrimaculata (Linnaeus, 1758) (P en FR)

(full message, see helpdesk 27.11.19)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c4eebbd2d6a98172f19b77c7a02ae408:aa7e5b7cfcafbfe59db80667d672de4278e35aa69e8abdf23b6df5ecb27259cc7422281e2722478bf8a71e569fdb86d4141050acc9d99106ac4f78a9c8216ab3)
System: Firefox 70.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/fr/species/1136138
Window size: width 1268 - height 554
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-27T11:04:51.638Z',mode:absolute,to:'2019-11-27T11:10:51.638Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-27T11:04:51.638Z',mode:absolute,to:'2019-11-27T11:10:51.638Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It looks like a similar issue to this one: https://github.com/gbif/portal-feedback/issues/1377
Where the species share the same family, same epithet, same author and nearly the same year so they are grouped together with some inferred common basionym (not sure exactly how it works but the issues look very similar).

**Comment by ManonGros** [comment]
Issue solved in the new backbone.
