### ISSUE TITLE
Broken link on FAQ page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2313]
**Broken link on FAQ page**

On this page:
`https://www.gbif.org/faq?question=dwc-download`

The link for "(but not the actual image files)" is pointing to a broken staging url, not prod

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/739e949b6fe23ddde8ce74a22508859d:4655c258e0d9171bc59adc5c7d3a08a08a57f56dd2aa230cf5558fa710ca2fa1b02843d63ba691b188754156eb17b0a72ff77414113f6283b79ad358997782c3)
System: Firefox 70.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/faq?question=dwc-download
Window size: width 1920 - height 961
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-27T11:13:17.700Z',mode:absolute,to:'2019-11-27T11:19:17.700Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-27T11:13:17.700Z',mode:absolute,to:'2019-11-27T11:19:17.700Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
fixed
