### ISSUE TITLE
Images not showing from any records in Austrian dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2314]
**Images not showing from any records in Austrian dataset**

Almost half of the specimen records in this dataset are shown as having images associated with them, but none are showing up in the gallery or on individual records

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8a1fc4bb3b89ae66763bf85552b86468:58c3654818e8e9c3f28f6e079f0b0be4b459d94958b0d897837f29bf8105a0e95698a4195da4ccbc604c010ed7b6732747d81f6c16b8b65aa8903aa995521b49)
System: Chrome 78.0.3904 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/5830fa3c-497c-4d37-b771-bd6c84997f2c
Window size: width 2160 - height 1063
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-28T20:44:13.547Z',mode:absolute,to:'2019-11-28T20:50:13.547Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-28T20:44:13.547Z',mode:absolute,to:'2019-11-28T20:50:13.547Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Heimo Rainer of [NHM Wien](https://www.gbif.org/publisher/4e11d750-bafb-11d9-8e53-b8a03c50a862) / [University of Vienna Herbarium](https://www.gbif.org/publisher/58520c30-bafb-11d9-8e53-b8a03c50a862) might be able to help here if we need it…

**Comment by ManonGros** [comment]
That's because they provide us with links to some display system instead of the images themselves.
See [this occurrence](https://www.gbif.org/occurrence/2005720973) where the link provided is: http://herbarium.univie.ac.at/database/image.php?filename=1447524&method=show

**Comment by ManonGros** [comment]
It looks like this is no longer an issue: https://www.gbif.org/occurrence/gallery?dataset_key=5830fa3c-497c-4d37-b771-bd6c84997f2c
