### ISSUE TITLE
Changing email address on account?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2322]
**Changing email address on account?**

Dear GBIF Helpdesk,

I can't seem to work out how to change my email address on my account. It used to be l.gardiner@kew.org (to which I no longer have access) - my current work email address is lmg32@cam.ac.uk. 

Many thanks!

Lauren Gardiner

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/51848b042add4dcb4209fc15ac774b29:bb3b5cc62ded05d58ad0819623d5f48dfbf450422ed47181cf2dc97048594f82ba9c193f4d6551f205b7eff8008377906920b6f1501b7e2a5ff3a5edd34b1cd1)
System: Firefox 70.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1333 - height 707
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-02T00:12:47.980Z',mode:absolute,to:'2019-12-02T00:18:47.980Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-02T00:12:47.980Z',mode:absolute,to:'2019-12-02T00:18:47.980Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Done (since I know Lauren).
