### ISSUE TITLE
establishedMeans = "NATIVE" produces Python regius in the US

### ISSUE THREAD

**Issue by RussellGrayxd** [gbif/portal-feedback#2323]
As stated in the subject header. the argument for rgbif package in R "establishedMeans = "NATIVE" produces non-native occurrence data in the US.

I tried to find a way to flag these specific records on the website, but I couldn't find a way to filter by native species and country. 

-RG

**Comment by ManonGros** [comment]
Thanks @RussellGrayxd for notifying us.
Could you send us a list of the species concerned? Or perhaps upload the records with this issue as a CSV here on GitHub?
Anything would help, thanks!

**Comment by RussellGrayxd** [comment]
This is just a subset of 1000 points I pulled in which 16 individuals showed up, but I expect there are more. Unfortunately my wifi is too slow to make big queries. Here is the code in case someone on your end can reproduce it with a larger limitation
fam <- name_suggest(q = "Pythonidae", rank = "family")occ_search(taxonKey = fam$key, return = "meta")$count# Pulls your data from GBIF, limit to 200 records with no invaisve speciesspdat.new <- occ_search(taxonKey = fam$key,return = "data",                         limit = 1000, establishmentMeans = "NATIVE")
dat.US <- subset(spdat.new, country == "United States of America")
write.csv(dat.US, "nonnativeUSpythons.csv")


    On Thursday, December 5, 2019, 03:57:42 p.m. GMT+7, Marie Grosjean <notifications@github.com> wrote:  
 
 
Thanks @RussellGrayxd for notifying us.
Could you send us a list of the species concerned? Or perhaps upload the records with this issue as a CSV here on GitHub?
Anything would help, thanks!

**Comment by ManonGros** [comment]
Thanks @RussellGrayxd! I had read your previous issue too fast and didn't see that it concerned pythons. We will look into the issue and contact the data providers.

FYI, you can also get this information from the portal by using the "Advanced" filter:
https://www.gbif.org/occurrence/search?q=NATIVE&country=US&taxon_key=4287591&establishment_means=NATIVE&advanced=1

Thanks again!
