### ISSUE TITLE
broken link on GBIF Infrastructure: Data processing page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2324]
**broken link on GBIF Infrastructure: Data processing page**

There is a link to an occurrence in the sentence `On the details page of any occurrence record you will see the list of issues in the notice at the bottom.`: `https://www.gbif.org/occurrence/236047012`
This occurrence doesn't exist any more. Perhaps we could remove the link (or update it but we risk it being obsolete again).

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/00859af2d40b7421925a3a6981285884:6ca274eeb6624d848cc74c59f74f20f40061055077f344389ec32633ef4fb5593a2341b6f56eeb4e4beedb9a66f39214b3584d122027a79aed05bf0ba4a67755)
System: Safari 13.0.3 / Mac OS X 10.15.1
Referer: https://www.gbif.org/article/5i3CQEZ6DuWiycgMaaakCo/gbif-infrastructure-data-processing
Window size: width 1926 - height 1169
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-05T11:56:52.277Z',mode:absolute,to:'2019-12-05T12:02:52.277Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-05T11:56:52.277Z',mode:absolute,to:'2019-12-05T12:02:52.277Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Anything from PonTaurus (Marcus' PhD) should be pretty stable: https://www.gbif.org/occurrence/142316220

**Comment by ManonGros** [comment]
@dnoesgaard would it be possible to update this link? Thanks!

**Comment by dnoesgaard** [comment]
Done.
