### ISSUE TITLE
This cannot be the Holotype of Cantharallus cibarius Fr.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2325]
**This cannot be the Holotype of Cantharallus cibarius Fr.**

I asumme that this could be the Holotype of Cantharellus aurantiacus (Wulfen) Fr. var. congolensis Beeli as this is present at the source page: `http://www.botanicalcollections.be/#/en/details/BR5020032470720`

If so, Cantharellus aurantiacus (Wulfen) Fr. var. congolensis Beeli could be given as the typifiedName. Otherwise the type status should be removed.

Cantharellus cibarius was described by Elias Fries in 1821.
`http://www.speciesfungorum.org/Names/SynSpecies.asp?RecordID=200345`

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0b867ecf3f29c0593c0761d67ca97b42:9979b9e0c06620bd2b3286770e2f2a417d5e0d3f10285757cd54742bdb47547bf3be9fe463fdae8c68e140da970c4f1f9e148acd67eeddfb7323518fb202473f)
System: Chrome 78.0.3904 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/1840601236
Window size: width 1931 - height 1181
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-05T12:50:16.977Z',mode:absolute,to:'2019-12-05T12:56:16.977Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-05T12:50:16.977Z',mode:absolute,to:'2019-12-05T12:56:16.977Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: b740eaa0-0679-41dc-acb7-990d562dfa37
publishingOrgKey: a344ee9f-f1b7-4761-be2c-58ee6d741395

**Comment by ManonGros** [comment]
Contacted publisher by email.

**Comment by matdillen** [comment]
This specimen is indeed the holotype for Cantharellus aurantiacus (Wulfen) Fr. var. congolensis Beeli. 

However, I am not entirely certain how to model this in our next update. What to do with the typestatus in the occurrence core?

like this?

Occurrence core:
dwc:occurrenceID = "http://www.botanicalcollections.be/specimen/BR5020032470720"
dwc:scientificname = "Cantharellus cibarius Fr."
dwc:typeStatus = ""

Types and Specimen extension:
dwc:occurrenceID = "http://www.botanicalcollections.be/specimen/BR5020032470720"
dwc:scientificName = "Cantharellus aurantiacus (Wulfen) Fr. var. congolensis Beeli"
dwc:typeStatus = "Holotype"

**Comment by ManonGros** [comment]
Perhaps I am missing something, but would it make sense to just have the following?

Occurrence core:
dwc:occurrenceID = "http://www.botanicalcollections.be/specimen/BR5020032470720"
dwc:scientificname = "Cantharellus aurantiacus (Wulfen) Fr. var. congolensis Beeli."
dwc:typeStatus = "Holotype"

Why would we need *Cantharellus cibarius* Fr.? Is it the current identification?

**Comment by matdillen** [comment]
Cantharellus cibarius Fr. is indeed the latest identification. We still have to add the verification history to our IPT mapping.

**Comment by thomasstjerne** [comment]
It seems that the field [typifiedName](https://terms.tdwg.org/wiki/abcd2:SpecimenUnit-TypifiedName)  is not present in DwC Occurrence. But in the case where the specimen is the holotype of another name than that of the latest identification, it is suggested do:

dwc:typeStatus = "Holotype for Cantharellus aurantiacus (Wulfen) Fr. var. congolensis Beeli."

Suggested here: http://rs.tdwg.org/dwc/terms/#typeStatus

**Comment by matdillen** [comment]
@thomasstjerne How would GBIF parse that? Wouldn't it still be interpreted as a holotype (under the Cantharellus cibarius name)?

**Comment by matdillen** [comment]
We finally got to updating our data on GBIF. The value for typestatus has been modified and the verification history added. So I think this issue is resolved now?

**Comment by ManonGros** [comment]
Thanks @matdillen I think this issue can be closed.
