### ISSUE TITLE
Species synonymised to wrong kingdom

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2326]
**Species synonymised to wrong kingdom**

`https://www.gbif.org/species/10494854`
This species from Poaceae, Plantae has been synonymised to a taxon in Fungi. The original genus (Setaria) remains in Plantae. 
Hopefully a mistake based on speciesname (setosa) similarity, and not a larger problem with the matching algorithm.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4ff1ddf475948eae7db338233330e72a:d2ef60a833af062044f03fa9861a19d8769ba26ca6b960d87e2e9aa2a2120c1ac52f0342a3e1f72060f2d80560928ffb88156b659b03dd641f2b4f2385975c0b6ae7f66252fff605b66a83765d7f3306)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/species/10494854
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-06T10:36:46.600Z',mode:absolute,to:'2019-12-06T10:42:46.600Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-06T10:36:46.600Z',mode:absolute,to:'2019-12-06T10:42:46.600Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Setaria setosa (Sw.) P.Beauv. is now in the correct kingdom: https://www.gbif.org/species/10672711
