### ISSUE TITLE
Empty "dubious" genera in Piophilidae due to synonymization

### ISSUE THREAD

**Issue by Chris-Angell** [gbif/portal-feedback#2327]
There are a bunch of empty genera [in this family](https://www.gbif.org/species/9503), apparently left over when the included species were synonymized into other genera. They are as follows:

_Ambopogon_ into _Amphipogon_ (McAlpine 1977)
?_Agrodaeta_ into _Amphipogon_. This genus doesn't appear anywhere except [IRMNG](http://www.irmng.org/aphia.php?p=taxdetails&id=1346229), where I think it is a synonym for _Macrochira_, itself a synonym for _Amphipogon_.

_Amurocelsia_ seems to be a misspelling of _Amuroclusia_ (Clusiidae) inherited from IRMNG, based on the fact that its [only child species there](http://www.irmng.org/aphia.php?p=taxdetails&id=1209839) is _Amurocelsia nigromaculata_, which mirrors the _Amuoclusia_ species of [the same name](http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/2dc5d78b380a3a581519a139aa9fa37f/source/tree).

_Arctopiophila_ into _Allopiophila_ (Ozerov 2004).

_Lasiopiophila_ into _Piophila_. The only species in this genus is _L. pilosa_ (McAlpine 1977, Ozerov 2004), which now appears under _Piophila_, following [Catalogue of Life](http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/28597bf4c90785769affc90fd176f77d/source/tree).

_Liopiophila_ into _Prochyliza_ (Ozerov 2004). This genus contains only _L. varipes_ (McAlpine 1977), which appears misspelled as "varipesa" here and spelled correctly under _Prochyliza_.

_Stearibia_ into _Piophila_. The only species in this genus is _S. nigriceps_ (McAlpine 1977, Ozerov 2004), which now appears under _Piophila_, following [Catalogue of Life](http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/7529389540803014b6dd72351ca1d97b/source/tree).

_Thyreolepida_ into _Centrophlebomyia_ (Ceretti et al. 2013). The only species in this genus is _T. cineria_ (McAlpine 1977, Ozerov 2004), which now appears as a synonym of _Centrophlebomyia furcata_, following [Catalogue of Life](http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/2828fa058bea8f650666750bfea3e211/source/tree).

I hope this is helpful in some way! There are also some genera -- _Parapiophila, Protopiophila_, and _Mycetaulus_ -- that have been "partially synonymized" with another genus on GBIF, but have a few species still left over in the old genus, but maybe that's a story for another day/post.

------
JF McAlpine 1977. A revised classification of the piophilidae including 'Neottiophilidae' and 'Thyriophoridae' (Diptera: Schizophora). Mem. Ent. Soc. Can. 103: 1-66.

AL Ozerov 2004. On the classification of the family Piophilidae (Diptera). Zoologicheskiĭ zhurnal 83:1353-1360. (this paper is hard to find but the abstract is available [on Researchgate](https://www.researchgate.net/publication/289746416_On_classification_of_the_family_Piophilidae_Diptera))

Cerretti P, Mei M, Whitmore D, Lo Giudice G (2013) A neotype designation for the bone-skipper Centrophlebomyia anthropophaga (Diptera, Piophilidae, Thyreophorina), with a review of the Palaearctic species of Centrophlebomyia. ZooKeys 310: 7-28. https://doi.org/10.3897/zookeys.310.4914

**Comment by jhnwllr** [comment]
Ambopogon is  into Amphipogon (McAlpine 1977)
https://www.gbif.org/species/1522414
is classed as **doubtful**

**Comment by jhnwllr** [comment]
This issue needs to be split into separate issues to be handled properly.

**Comment by jhnwllr** [comment]
https://github.com/gbif/checklistbank/issues/52
