### ISSUE TITLE
https://www.gbif.org/species/2646813 Broken Gallery section - important new pictures

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2331]
**`https://www.gbif.org/species/2646813` Broken Gallery section - important new pictures**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8a06ccf76db697962a05149d5f13c6e8:d5dedec71be0158777b11f2697820d5bb5f250f008564f2e25c5b66bfd74154661a7b0529403820bd312704144dc161f37460b3ad65f98ef512cc8d8c06f1891)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/species/2646813
Window size: width 1920 - height 947
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-09T09:01:16.709Z',mode:absolute,to:'2019-12-09T09:07:16.709Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-09T09:01:16.709Z',mode:absolute,to:'2019-12-09T09:07:16.709Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Contacted iNaturalist, it looks like we've been temporarily blocked from their images.
