### ISSUE TITLE
Genus Eisenia placed in wrong kingdom

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2333]
**Genus Eisenia placed in wrong kingdom**

Most species of genus Eisenia that should be worms placed into the homonimic genus Eisenia of kingdom Chromista. So I could not publish correctly checklist on the Earthworms.
see `https://www.gbif.org/species/3196066`
species with authors Perel, Pop, Michaelsen, Malevic, Kvavadze, Zisci, Pavlicek, Svetlov, Csuzdi, Cernosvitov and Blakemore are worms.

-----

Github user: @MaxCarabus
User: [See in registry](https://www.gbif.org/api/feedback/user/06a69bd661934766467ce7cfd0ab3413:57547e4b4122a19d2cacc92c5b5d4192304832c3356bc8e99f27d0f58a00433980abc565c5b582358d862fdb1769e9723042cdf58b7cd6bd7980f47fb8237cab)
System: Chrome 78.0.3904 / Windows 7.0.0
Referer: https://www.gbif.org/species/3196066
Window size: width 1918 - height 1048
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-09T20:20:04.234Z',mode:absolute,to:'2019-12-09T20:26:04.234Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-09T20:20:04.234Z',mode:absolute,to:'2019-12-09T20:26:04.234Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
There is a worm genus "Eisenia" in the backbone and CoL. 
https://www.gbif.org/species/5431563

Eisenia Malm, 1877
https://www.catalogueoflife.org/data/taxon/84NDF

I think the issue should be closed.
