### ISSUE TITLE
This dataset contains more occurrence than the source file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2335]
**This dataset contains more occurrence than the source file**

On the OBIS Canada IPT, this dataset contains 785 records (`http://ipt.iobis.org/obiscanada/resource?r=nsm),` but the ressource on GBIF contains 579 more records with institutionCode=NSM and collectionCode=Zoology. The source DwC Archive has institutionCode=Nova Scotia Museum and collectionCode=Zoology.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0703cd6509ad47f79cb88ddf2ff4ea11:29b55cc1cbc73d145b581a711ec8988c0702e55f9bacfc3d9a8d06d6e89d99e3efa379a8c2c2efac451ea12a85afdbaf6a2d71c4583f635dfbfdf8fbbab60b2e)
System: Chrome 78.0.3904 / Mac OS X 10.12.6
Referer: https://www.gbif.org/dataset/83ab0f8e-f762-11e1-a439-00145eb45e9a
Window size: width 2560 - height 1292
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-13T21:10:07.901Z',mode:absolute,to:'2019-12-13T21:16:07.901Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-13T21:10:07.901Z',mode:absolute,to:'2019-12-13T21:16:07.901Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The dataset had been over-ingested prior to the switch to the pipeline. It has now been recrawled so the number of records will soon be back to normal.
