### ISSUE TITLE
seek business Cooperation in china

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2336]
**seek business Cooperation in china**

we're doing bigdata and ai technical, from china and need to cooperations with your tech deeply, mail is : bigdata@usa.com  wechat:553088828 , telephone: +86 17600107890  LUO CHUAN

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1c069a16a42987ba53652fa2ff75b979:14299738a1e804cdef1304fcf648ebe61078e5418ba7007bc1a45dd079e5adcbef78ff4e2d4fd442e3aa5269cfc8b8bed34e567df507a34aded6a83f385eb89e)
System: Chrome 78.0.3904 / Windows 7.0.0
Referer: https://www.gbif.org/dataset/82cb293c-f762-11e1-a439-00145eb45e9a
Window size: width 2048 - height 1009
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-16T07:37:00.957Z',mode:absolute,to:'2019-12-16T07:43:00.957Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-16T07:37:00.957Z',mode:absolute,to:'2019-12-16T07:43:00.957Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> We are happy to help if we can. Please send us your questions to helpdesk@gbif.org and we will do our best to reply and put you in touch with the relevant people.
