### ISSUE TITLE
Country Code ZZ for New Zealand

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2337]
**Country Code ZZ for New Zealand**

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/f4f442873844e40db5f796d97d82fa7c:a122acccf4ff7c9081118688a3434aa607b1838da4fcf9b8b91024a47a7f0a0aeb3f5a2cf95822f9c46d112081d203c5261d7b89712d8a9bfd9450096ca8b09a8cafead74f299190b4f9a3552054a1d9)
System: Chrome 79.0.3945 / Mac OS X 10.15.2
Referer: https://www.gbif.org/occurrence/1987716814
Window size: width 1582 - height 808
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-17T03:41:28.207Z',mode:absolute,to:'2019-12-17T03:47:28.207Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-17T03:41:28.207Z',mode:absolute,to:'2019-12-17T03:47:28.207Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 90302970-1bc6-4865-be76-9aef1dd707f9
publishingOrgKey: b542788f-0dc2-4a2b-b652-fceced449591

**Comment by kcopas** [comment]
Looks like “Unknown country” in the country code may be systemic problem in the dataset: 
https://www.gbif.org/occurrence/search?country=ZZ&dataset_key=90302970-1bc6-4865-be76-9aef1dd707f9

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ManonGros** [comment]
The original data shows "New Zealand" as country and "unknown" as country code.
We could ask the publisher to leave the country code field empty or to use "NZ" instead but shouldn't our system be able to interpret the country name?

**Comment by MattBlissett** [comment]
It prioritizes the country code ("Unknown"), and is taking this as a definitive statement that the country isn't known.

An empty country code would work, or "NZ" (or many other values like "New Zealand").

**Comment by ManonGros** [comment]
Publisher contacted by email.

**Comment by ManonGros** [comment]
The issue has been fixed.
