### ISSUE TITLE
Data usage report

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2338]
**Data usage report**

Hello
I am interested in getting a report on the data usage of the records of a specific publisher, including the number of downloads, citations, etc over time.  
I am a graduate student as the CU Boulder Museum of Natural History, and I am working on a project that involves data on scientific impact. 
Thank you!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/79c75c6e7b6e76fba89734f1c39149c3:455c9091b48aac38b351fea89e6e96b8f4be41ea7333d220baf08a345fc79a05651fc169bc2470c6699b87e243b3e89b488c7e77f463f93f3b2d49556fad4b97)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/faq
Window size: width 1536 - height 722
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-17T16:31:53.163Z',mode:absolute,to:'2019-12-17T16:37:53.163Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-17T16:31:53.163Z',mode:absolute,to:'2019-12-17T16:37:53.163Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
