### ISSUE TITLE
Dataset not harvesting correctly

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2339]
**Dataset not harvesting correctly**

Eduardo Klein and I can't figure out why Hexacorallians of the world isn't harvesting correctly from the Caribbean OBIS Node. OBIS is able to harvest it. Can someone help us figure out what's going on?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d780a19bc9140291865630ef35dd29ed:0e8480f813eab485dc4f080a4d485590cef7781252801478619638bb94482f79fed53ac1a573c63ada6a99a79d636ef8a54a515377c491e21ccd132186eefb64)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/adb92d68-aaff-47ba-b197-d3d26f72f728
Window size: width 1643 - height 1238
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-17T21:57:16.235Z',mode:absolute,to:'2019-12-17T22:03:16.235Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-17T21:57:16.235Z',mode:absolute,to:'2019-12-17T22:03:16.235Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It looks like the occurrenceIDs are missing.
Unfortunately, the validator doesn't detect that: https://www.gbif.org/tools/data-validator/1568816670070
And it seems like the IPT allowed the dataset to be published as well.

**Comment by ManonGros** [comment]
Replied by email.

**Comment by ManonGros** [comment]
The IPT adminsitrator added the occurrenceIDs and republished.
The dataset is now good but it would be great if the validator and IPT could detect the missing occurrenceIDs.
