### ISSUE TITLE
Errors in taxon data: Fannia serena != Pyrellia rapax

### ISSUE THREAD

**Issue by Psilopa** [gbif/portal-feedback#2341]
The record for Fannia serena Fallen (https://www.gbif.org/species/5094809) does erroneously synonymise it with Pyrellia rapax. 

This might be caused by  Musca serena Meigen, 1826 (a real synonym of Pyrellia rapax) being confused with Musca serena Fallén, 1825.

Both Fannia serena (Fallén, 1825) and Pyrellia rapax (Harris, 1780) are valid species, in different familier no less...

Cheers, Jere

**Comment by ManonGros** [comment]
As far as I can see, the two species are now separate in the new backbone:
https://www.gbif.org/species/5094809 in the Faniidae family
https://www.gbif.org/species/1525985 in the Muscidae family
