### ISSUE TITLE
Error in taxon data: Fannia monilis != Anthomyia monilis 

### ISSUE THREAD

**Issue by Psilopa** [gbif/portal-feedback#2342]
Another far-fetched mistake involving two common species or two different families:

Record https://www.gbif.org/species/5094794 has Fannia monilis (Haliday, 1838) as a homotypic synonym of Anthomyia monilis (Meigen, 1826). This is definitely false.

Both names represent valid species (in different families).

Cheers, 
Jere K.

**Comment by ManonGros** [comment]
They are both separate species in separate families in the new backbone:
https://www.gbif.org/species/1573446
https://www.gbif.org/species/5094794
