### ISSUE TITLE
list of data sets

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2343]
**list of data sets**

Hi,

is it possible to export a list of occurence datasets in GBIF along with the number of observations in the dataset?

I am trying to understand better the occurence data in GBIF and its sources.

best wishes

/Steve

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8ba700298952b88cef0f150459b4ff45:3aaa20393b9caaf328e45f6c16fcc6335f951131c5c6eb005b1f93241922612e879479048044c03701572cbb771a5e85c65b81eee37af0544adefec3ca2b2f9f)
System: Chrome 78.0.3904 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/38b4c89f-584c-41bb-bd8f-cd1def33e92f
Window size: width 1920 - height 1089
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-19T08:19:19.246Z',mode:absolute,to:'2019-12-19T08:25:19.246Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-19T08:19:19.246Z',mode:absolute,to:'2019-12-19T08:25:19.246Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
