### ISSUE TITLE
Woodfordia fruticose is classified as belonging to the class Aves, when it should be a plant

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2344]
**Woodfordia fruticose is classified as belonging to the class Aves, when it should be a plant**

`http://www.gbif.org/species/10311272`

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/04ea944fa6d5e714168fdc28f3517a87:7f44a88755a8f293aeb7eb09a7db02c3f96c97fe204609afeed228e16ce45409794ffd548f338d5a777534eab1c139c3938d1d1c0d9af58adeaa5ded1c36321e)
System: Safari 12.1.2 / Mac OS X 10.14.6
Referer: https://www.gbif.org/species/10311272
Window size: width 1440 - height 837
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-19T13:49:23.759Z',mode:absolute,to:'2019-12-19T13:55:23.759Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-19T13:49:23.759Z',mode:absolute,to:'2019-12-19T13:55:23.759Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Solved in new backbone update: https://www.gbif.org/species/5635525
