### ISSUE TITLE
:Listing countries

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2346]
**:Listing countries**

Found it. I would consider it as being of greater interest- like front page interest.  Sorry - should have spent more time exploring

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/506102c3da66133de170abb73af74055:5ae9b5eed66505d5dfee987055eb50fd5d3d3824322b87b989cf444bc8a36e591cc85bc60c7ed83fed78bf09d6f4dfca80789247d50ed362468858373433e41c)
System: Chrome 79.0.3945 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/charts?basis_of_record=PRESERVED_SPECIMEN&taxon_key=2703482
Window size: width 1536 - height 754
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-19T15:13:53.809Z',mode:absolute,to:'2019-12-19T15:19:53.809Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-19T15:13:53.809Z',mode:absolute,to:'2019-12-19T15:19:53.809Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
relates to https://github.com/gbif/portal-feedback/issues/2345
