### ISSUE TITLE
That location seems suspect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2351]
**That location seems suspect**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/eb99101f50a0748153d1b01a57b91176:053c4b1c562c49268034f2a07cc789d91360d9dda353d823fe7e6ab9ff7ec44f0f0412479ff0d220a7282dcfab8c61419460fff128254fdc9798e5ebb6e60f35)
System: Chrome 79.0.3945 / Mac OS X 10.15.2
Referer: https://www.gbif.org/occurrence/2422283915
Window size: width 1274 - height 616
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-27T02:17:59.774Z',mode:absolute,to:'2019-12-27T02:23:59.774Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-27T02:17:59.774Z',mode:absolute,to:'2019-12-27T02:23:59.774Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: e523cf2d-4fc2-48d8-aa75-80ecbc90b3f5
publishingOrgKey: 53e59855-7653-4d3e-87cc-162021713823

**Comment by ManonGros** [comment]
Publisher contacted by email.

**Comment by jhnwllr** [comment]
record deleted
