### ISSUE TITLE
Plant species checklist

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2356]
**Plant species checklist**

Dear colleagues,

I would like to access to a clean and full species checklist of plant species (tracheophyta) of Iran. Unfortunately, it takes plenty of time to extract species list according to occurrence data. Would you please kindly help me to have this checklist? Thanks a lot in advance

Best regards
Alireza Naqinezhad

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/da2ee522ea4909fc71a1c9c03357e42a:ae9661765e1584367051841f78f96f16a23aa6b6c3ac70815f6f99c4063bff6c3ede23fc4866b8bae5b58e2944d80ff7a282c37a3ca578ee46113b8a847d390f)
System: Firefox 71.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/search?q=poa%20annua&rank=SPECIES&highertaxon_key=6&status=ACCEPTED&advanced=1
Window size: width 1536 - height 728
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-04T02:39:25.082Z',mode:absolute,to:'2020-01-04T02:45:25.082Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-04T02:39:25.082Z',mode:absolute,to:'2020-01-04T02:45:25.082Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Kyle already replied.
