### ISSUE TITLE
authors name contains a typo

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2357]
**authors name contains a typo**

the name of the validating author has to be written Gustafsson (not Gustofsson)

Best greetings
G. Matzke-Hajek

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fe026f0105f7c0a4e24a91b880d8abe6:6ce6c50e10c8c41d187d890259476d553bb0c5b5c10e608ea6ffe86ab918a182ba2190d7d7042620fb1f52d687f35ded1852cb79b5c8a762adeaf319add35e96)
System: Firefox 71.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/2995029
Window size: width 1536 - height 722
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-04T10:28:36.962Z',mode:absolute,to:'2020-01-04T10:34:36.962Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-04T10:28:36.962Z',mode:absolute,to:'2020-01-04T10:34:36.962Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I guess this issue is not longer relevant since in the new backbone the authorship is "Gust.".
