### ISSUE TITLE
misidentification of the plant on the photo

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2358]
**misidentification of the plant on the photo**

The photo shows Rubus steudneri Schweinf., not Rubus apetalus Poir. 
The same applies to the following four photos from Mt. Bale Nat. Park, Ethiopia, which are taken in the same locality.

Best greetings
G. Matzke-Hajek

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/87fee3fe5b4ab57301e2733b52b65e77:f845ce0de161c181d5ec5933eba70632b34a3aa7a3c12d4c3e6b9554454e7014ced4b7c8eaf88a60b594425d0412c129ae54c7b67cc611eaa4781c9909828f47)
System: Firefox 71.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1288085142
Window size: width 1536 - height 722
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-04T10:41:13.834Z',mode:absolute,to:'2020-01-04T10:47:13.834Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-04T10:41:13.834Z',mode:absolute,to:'2020-01-04T10:47:13.834Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: e5774d90-9f01-42bb-a747-32331be82b18
publishingOrgKey: c76cf030-2a95-11da-9cc1-b8a03c50a862

**Comment by ManonGros** [comment]
Publisher contacted by email.
