### ISSUE TITLE
I already told my colleague Kurt Zernig, the cultivated fern in question does represent Dryopteris cycadina, please do correct it's identificatin. Best regards, Erwin Gruber

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2359]
**I already told my colleague Kurt Zernig, the cultivated fern in question does represent Dryopteris cycadina, please do correct it&#39;s identificatin. Best regards, Erwin Gruber**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f7d60a320b034af7fc961f83ec746d61:4c5e281f2212520a91918a9aa8dcdb0a6a38493e6c9d4186de5267323333a52e402a28430bd5d0738eb16eaa0855b46b06481959a043cb0460389be73bcb9a59)
System: Chrome 79.0.3945 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1935713570
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-04T13:17:18.337Z',mode:absolute,to:'2020-01-04T13:23:18.337Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-04T13:17:18.337Z',mode:absolute,to:'2020-01-04T13:23:18.337Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 5830fa3c-497c-4d37-b771-bd6c84997f2c
publishingOrgKey: 32ceedc0-bafb-11d9-8e53-b8a03c50a862

**Comment by ManonGros** [comment]
It seems like the record is now up to date, thanks @botanykerwin1968 for the revision!
