### ISSUE TITLE
where is the "verbatim" link in the new occurence demo site?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#236]
**where is the &quot;verbatim&quot; link in the new occurence demo site?**

When I am looking at this page ...
https://demo.gbif.org/occurrence/225941757

... where can I find this info?
http://www.gbif.org/occurrence/225941757/verbatim

-----
fbitem-occurrence225941757

System: Chrome 49.0.2623 / Windows XP 0.0.0
Referer: https://demo.gbif.org/occurrence/225941757
Window size: width 1024 - height 707
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-04T12:31:57.324Z',mode:absolute,to:'2017-07-04T12:37:57.324Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-04T12:31:57.324Z',mode:absolute,to:'2017-07-04T12:37:57.324Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 10734a60-7ed1-11df-8c4a-0800200c9a66
publishingOrgKey: def87a70-0837-11d9-acb2-b8a03c50a862

**Comment by cgendreau** [comment]
Related to: https://github.com/gbif/portal16/issues/341

**Comment by MortenHofft** [comment]
Thanks for your feedback
There is no contact info, so here goes an answer that no one is likely to hear ;)

Good news: The verbatim tab is not there, but the info is.
Bad news: it isn't visible enough for you to find it, but good news: there is an issue related to that.

![screen shot 2017-07-04 at 14 45 02](https://user-images.githubusercontent.com/6759267/27830600-70dab4c6-60c7-11e7-94bc-d136241b8e31.png)

Closing as duplicate
