### ISSUE TITLE
GBIF - Bug while accessing occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2360]
**GBIF - Bug while accessing occurrences**

As a user, I'm not allowed to access "older" occurrences in large datasets. Problem is related to offset atribute that is set to accept only values smaller than 200000. Please see following example.

WEB:
- OK -> `https://www.gbif.org/occurrence/search?offset=199000&dataset_key=84d26682-f762-11e1-a439-00145eb45e9a`
- Not OK -> `https://www.gbif.org/occurrence/search?offset=200000&dataset_key=84d26682-f762-11e1-a439-00145eb45e9a`

API:
- OK -> `http://api.gbif.org/v1/occurrence/search?datasetKey=84d26682-f762-11e1-a439-00145eb45e9a&limit=10&offset=199000`
- Not OK -> `http://api.gbif.org/v1/occurrence/search?datasetKey=84d26682-f762-11e1-a439-00145eb45e9a&limit=10&offset=200000`

Please don't hesitate to contact me on my email.
lukaspicek@gmail.com

Best,
Lukas

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9a3f2f47898ad3f703a77bdfd4ee32c6:019655d2c01f04aefe117850c78202a2fd000b90b340d0e111d2b80da94a50a70bfabc0717c77d9485752c3fc7902deffe78014de27c4fa275dbe6612f29af50)
System: Chrome 79.0.3945 / Mac OS X 10.15.1
Referer: https://www.gbif.org/occurrence/search
Window size: width 1280 - height 689
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-04T15:30:07.994Z',mode:absolute,to:'2020-01-04T15:36:07.994Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-04T15:30:07.994Z',mode:absolute,to:'2020-01-04T15:36:07.994Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
