### ISSUE TITLE
As image title says: Canada, British Columbia, Vancouver, Seymor, the added location in north central Canada is far away from right one. Can you please correct this?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2362]
**As image title says: Canada, British Columbia, Vancouver, Seymor, the added location in north central Canada is far away from right one. Can you please correct this?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6306a71d6515f3916c9ddf232ad0c540:f70ab6ccb62fec55ca38dabff7ce6f9e3605694dd9345b1ab85116e140c8ca181e45985f7554d13ce8d61acc86dbddf302b9cc85e8c5b78b4687ef9540ecec4a)
System: Chrome 79.0.3945 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2382965199
Window size: width 1366 - height 608
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-04T22:35:49.959Z',mode:absolute,to:'2020-01-04T22:41:49.959Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-04T22:35:49.959Z',mode:absolute,to:'2020-01-04T22:41:49.959Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 88d6237c-fbce-4135-b509-0aeed1e4222e
publishingOrgKey: 6c1dec01-8c82-4341-8584-26c6576d3b69

**Comment by ManonGros** [comment]
Publishers contacted by email.

**Comment by jhnwllr** [comment]
seems correct now
