### ISSUE TITLE
Coordinate reprojection failed - occurrence flagged when it looks ok

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2364]
**Coordinate reprojection failed - occurrence flagged when it looks ok**

The geodetic datum provided is already WGS84 so it seems like the coordinate shouldn't be reprojected.

The issue is the same for all the occurrences of the two following datasets:
* `https://www.gbif.org/dataset/0324faa2-894d-459c-b86a-bda617ef0690`
* `https://www.gbif.org/dataset/96f53e46-902a-48d5-a599-7c96c065b214`

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/f9816f3b2e4884671831cc3a5937cb32:b255b4afe92aa90855103a932e36eeec676374cc37ad67effd4274bc38121cf7189b305b71af641a8fc556ff65956692bb18a4da24e6ff8aeb8c4dc770be418c)
System: Safari 13.0.4 / Mac OS X 10.15.2
Referer: https://www.gbif.org/occurrence/2532994010
Window size: width 2147 - height 983
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-06T13:51:20.795Z',mode:absolute,to:'2020-01-06T13:57:20.795Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-06T13:51:20.795Z',mode:absolute,to:'2020-01-06T13:57:20.795Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 0324faa2-894d-459c-b86a-bda617ef0690
publishingOrgKey: cecc196e-f262-4986-a88a-6adf035dca0e

**Comment by fmendezh** [comment]
@asturcon I added this line to track the error https://github.com/gbif/pipelines/commit/3847e73c8664fe35ddc38019d7ff28fc784dd238
we can deploy this change en test it in UAT

**Comment by asturcon** [comment]
It's not happening anymore and all datasets look ok now after the latest reprocessing. Please reopen if it happens again.
