### ISSUE TITLE
Downlaod list of species from one locality

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2365]
**Downlaod list of species from one locality**

Bonjour,
Je souhaiterais télécharger toutes les données provenant de la réserve naturelle de la Montagne-aux-Buis (Belgique, Province de Namur, Viroinval, Nismes-Dourbes).
Comment dois-je m'y prendre ?
Merci
Cordialement
Stéphane Claerebout

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f3f3ab1d2e163182641f59cd12826d75:d85cfd52861554b22f01be93b4166bb6bbc2af96e1cc5f4fe394b9d0c326d47c9a097cf987631cb97125e69d2a3ba5b39f841f5f98f43d8b901acade96a54242)
System: Chrome 49.0.2623 / Mac OS X 10.6.8
Referer: https://www.gbif.org/faq
Window size: width 1705 - height 850
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-07T10:14:18.191Z',mode:absolute,to:'2020-01-07T10:20:18.191Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-07T10:14:18.191Z',mode:absolute,to:'2020-01-07T10:20:18.191Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
