### ISSUE TITLE
cant download occurence data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2367]
**cant download occurence data**

im trying to download occurence data for all giraffe species however keep being met with the same error when going to download of ''Download is only supported for structured search – not for free text queries.' i cant seem to get past this and i dont know what it means or what i need to do. help would be appreciated.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ffd818bf0a6a951795a9f5a7e144613c:1ea934db31672b60df55bd3aa74aa7bfc2cb3163c90aaadce898226b61cab5153a45caaf863220fcb804e270e6c9d203f68787cd2ff274e04a2f9a00c01c94a2)
System: Chrome 79.0.3945 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1242 - height 568
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-07T15:52:57.472Z',mode:absolute,to:'2020-01-07T15:58:57.472Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-07T15:52:57.472Z',mode:absolute,to:'2020-01-07T15:58:57.472Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
