### ISSUE TITLE
gbif portal languages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#237]
**gbif portal languages**

Is there any option to link to a specific version of the portal in other languages?

I recall in some previous version the portal was avaiable in Spanish, but I don&#39;t remember the way to change the language.

-----
fbitem-90ca04c707cd953f778e8789ed7ec98e67b20053
Reported by: sant.herbarium@gmail.com
System: Chrome 49.0.2623 / Windows XP 0.0.0
Referer: https://demo.gbif.org/occurrence/gallery?dataset_key=1c334170-7ed1-11df-8c4a-0800200c9a66&type_status=TYPE&type_status=TYPE_SPECIES&type_status=ALLOLECTOTYPE&type_status=ALLONEOTYPE&type_status=COTYPE&type_status=EXTYPE&type_status=HOLOTYPE&type_status=ISOTYPE&type_status=LECTOTYPE&type_status=PARATYPE&type_status=ORIGINALMATERIAL&advanced=1
Window size: width 1024 - height 707
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-05T09:16:27.398Z',mode:absolute,to:'2017-07-05T09:22:27.398Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-05T09:16:27.398Z',mode:absolute,to:'2017-07-05T09:22:27.398Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
nope there isn't at this point. That is something we consider addressing during autumn. I consider this a vote for a spanish translation then :)

**Comment by dgasl** [comment]
Yes, but I was also wondering about how it was done in the past.

Is there some way to do see current www.gbif.org in Spanish, o what I recall is a previous version of the portal?  (I don't even remember if there was a previous one, lol)

In any case I would like it to be possible to link to a certain language version directly (so the user does not need to do anything).  Would that be possible?

**Comment by MortenHofft** [comment]
yes it will be explicit in the url (if it is a supported language). The current gbif.org isn't multilingual i'm afraid. The previous or previous previous website was though - we plan to bring that back

**Comment by MortenHofft** [comment]
Would you be interested in helping with the translations when we start working on that?

**Comment by dgasl** [comment]
I am afraid I will probably not have enough free time for that.  
How many words can you estimate for the whole portal?  

Do I still help if I can just translate a page or some paragraphs?
I haven't done software translations before, so no idea about the workflow.

**Comment by MortenHofft** [comment]
Thank you. Anything would be a help. 

The workflow will likely be https://crowdin.com/ a online tool for translating. And you can translate anything from a few terms to the whole site depending on time and desire. Basically all filter names, darwin core terms, menus, error texts, feedback messages, help texts, articles etc should be translated. So it is quite a lot to make it fully available in fx. spanish. So the more the merrier. 

Rough estimate is 2500 sentences/words. Not counting articles, news stories, terms of use and longer paragraphs of text. Some - like country - we can hopefully find a translated version of somewhere online, but most are unique to the site.

**Comment by mdoering** [comment]
Has it be discussed if its worthwhile translating the whole site and into which languages? Translating menus and the portal code text is doable but probably the smaller part. All the content including news, articles, but also the actual data, dataset titles, descriptions etc will unlikely be all translated. Is it worth the effort if its never entirely in Spanish?

**Comment by dgasl** [comment]
Thanks @MortenHofft 
@mdoering : Of course, I was just meaning translation of the site for navegability, searches, downloads and so on.  
That's the only part I could try to collaborate in.

I was not meaning all the other stuff (news, articles, dataset content). 
That is too much and not affordable, in my opinion.

**Comment by MortenHofft** [comment]
I was imprecise sorry. With `anything from a few terms to the whole site` I didn't mean everything. 

I believe the exact scope is still to be decided. Selected news item probably will (we already do that e.g. BID).

So to summarize:
The interface (buttons, menu items, field labels etc.) and selected prose items (e.g. "what is GBIF").
Dataset descriptions, occurrence remarks etc is of course not something that we will ask anyone to translate.
