### ISSUE TITLE
Duplicate resource in GBIF data portal

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/portal-feedback#2370]
We have found a duplicate publishing resource in the GBIF data portal, One of them has a doi that point to the IPT and the other point to the same resource in the GBIF Portal. In the datadir there is only one resource.  

Resource links:

https://www.gbif.org/dataset/d1867c3f-9fc4-4dfd-8161-cd6a13393f39
https://www.gbif.org/dataset/5b4aaf68-137d-4355-abf1-d4a7e38f88a9

From Colombia's GBIF node, we ask for your help to delete the resource that **doesn't** poin to to our IPT.

Thanks!

**Comment by ManonGros** [comment]
Thanks for notifying us @RicardoOrtizG!
We deleted the duplicate dataset: https://www.gbif.org/dataset/5b4aaf68-137d-4355-abf1-d4a7e38f88a9
