### ISSUE TITLE
Endemic Species?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2371]
**Endemic Species?**

I was wondering if there is a way to search for records plant species that are found only in one particular area (such as Panama) and not anywhere else? 

This would be a great way to estimate endemic species of just about any group for a particular area. 

I could not find a way to do this in the advanced search but perhaps I missed something. 

Best,
Bertrand Black 
Plant Biology Department 
University of Vermont

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1809b0e75eb65a60961411ecbb3e88e4:9ff18e066c97d2124df817d63b0252b24d7ed75b6da73788ba9df70be74c1d28df4a4b64c11c0694aa40549d89ceb4510898236a9618563b9d57a7e4074ca07b)
System: Chrome 79.0.3945 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 920
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-09T16:34:11.023Z',mode:absolute,to:'2020-01-09T16:40:11.023Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-09T16:34:11.023Z',mode:absolute,to:'2020-01-09T16:40:11.023Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
