### ISSUE TITLE
Add ORCID IDs for Secretariat staff (where available)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2372]
**Add ORCID IDs for Secretariat staff (where available)**

As a small initial step, I'd suggest that we add ORCID IDs to Secretariat staff information in the directory, preferably with links to ORCID profiles in the individual entries.

<img width="499" alt="Screenshot 2020-01-09 at 21 01 57" src="https://user-images.githubusercontent.com/12379236/72100748-75b6af00-3323-11ea-9b1b-2c18d8acad7e.png">

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/7e142c6ed0ae52481da36809ae13ba45:1359bc67169cbab2c13180e437fd537830b07d3a5f5d314af5c327af7b64b37eb80fe5f6c93e0089c903f52f1715751f560a4fbd70886160bd454d1ca5ca6f7c)
System: Firefox 71.0.0 / Mac OS X 10.14.0
Referer: https://www.gbif.org/contact-us/directory?group=secretariat
Window size: width 1297 - height 931
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-09T19:57:39.653Z',mode:absolute,to:'2020-01-09T20:03:39.653Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-09T19:57:39.653Z',mode:absolute,to:'2020-01-09T20:03:39.653Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Done — I've added the ORCIDs for current staff where I could find them.

(Kyle, your entry links to an unlinked employer: https://orcid.org/0000-0002-6590-599X .  Compare https://orcid.org/0000-0003-0623-6682 which has the ROR etc for GBIF.)
