### ISSUE TITLE
Incorrect location - NMNH Extant Specimen Record

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2373]
Feedback from GBIF.org regarding: `https://www.gbif.org/occurrence/1318987456` Dear colleagues, the specimen in question, does represent relatively small leaves of juvenile Todea barbara grown in a nursery in Plymouth, New Zealand. So far so good, still it is diplayd at GBIF map at far remote location SE of NZ in Pacific Ocean. Coordinates of the collecting site are presented as Lat. -39° 05&#39;, Long. +174° 05&#39;. This had been altered to: Lat. -29.1°, Long. -174.1° at GBIF databank. Could you please manage the needed correction? `https://collections.nmnh.si.edu/search/botany/?ark=ark:/65665/34ef09e4cee7948709579cde3b54ebb1c` With best regards and thanks in advance Erwin Gruber, botanist

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/826b7ea6b3fbf722fb9f9b5bd9f04df7:088e411c7ed2df50c465bb05ff0896c06dfba7b80bdef3a790a4f344d51ac0836a7c8bb7844f0c8097360a4d38831b37c2e5410e7fbd4ddd76d05ec195f5d74c)
System: Chrome 79.0.3945 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1318987456
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-09T23:02:20.254Z',mode:absolute,to:'2020-01-09T23:08:20.254Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-09T23:02:20.254Z',mode:absolute,to:'2020-01-09T23:08:20.254Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 821cc27a-e3bb-4bc5-ac34-89ada245069d
publishingOrgKey: bc092ff0-02e4-11dc-991f-b8a03c50a862

**Comment by botanykerwin1968** [comment]
Just to be accurate: geoposition had been altered to Lat. -29.08°, Long. -174.08°.

**Comment by ManonGros** [comment]
I forward the message via their feedback system: https://collections.nmnh.si.edu/search/botany/?ark=ark:/65665/34ef09e4cee7948709579cde3b54ebb1c

**Comment by ManonGros** [comment]
The record seem to have been updated
