### ISSUE TITLE
Wrong synonym of Ligustrum vulgare

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2374]
**Wrong synonym of Ligustrum vulgare**

One of our users contacted us on helpdesk about this species page:

Syringa vulgaris shouldn't be a synonym of Ligustrum vulgare (`http://www.theplantlist.org/tpl1.1/record/kew-353907)`
In addition to that, the species isn't included in the CoL even though it is shown as a source: `http://www.catalogueoflife.org/col/details/species/id/6108af631184eae8fef59df411b19e2c/synonym/bcfcf961180083726b7e8f19dc32f4b1`

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/2c0d9f8ddbee6bf8dc34b1e1b8c1915c:9d5da62d1962fdd7ecdfc4431e5c0387b3e8d1c24475dcc29f749977a0469e9297284f53a2739dded3c7db56a82d0f74d2e2b47c830ff4d118c8374c040fca96)
System: Safari 13.0.4 / Mac OS X 10.15.2
Referer: https://www.gbif.org/species/3172300
Window size: width 2147 - height 983
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-13T09:39:56.051Z',mode:absolute,to:'2020-01-13T09:45:56.051Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-13T09:39:56.051Z',mode:absolute,to:'2020-01-13T09:45:56.051Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
solved in the new backbone.
