### ISSUE TITLE
Crepidotus variabilis and Entoloma lividum are not linked

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2375]
**Crepidotus variabilis and Entoloma lividum are not linked**

Entoloma lividum, Entoloma sinuatum are in GBIF synonyms of Crepidotus variabilis (as accepted taxon).

This taxa are not in the same family. Entoloma are Entolomataceae.

Thanks for the open API, it's great.

Félicien

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/386615026787dd30d0d1d047885808dc:5da3351ca839a35df00e2aeb26532e00a70d07870ee16be7dcf69f4200b58ac0de20904f3ff93db238a4e0b945681753652f6dda5e376db2321ebb57002bc438)
System: Safari 13.0.4 / Mac OS X 10.15.0
Referer: https://www.gbif.org/species/2539312
Window size: width 1280 - height 873
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-13T23:31:22.243Z',mode:absolute,to:'2020-01-13T23:37:22.243Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-13T23:31:22.243Z',mode:absolute,to:'2020-01-13T23:37:22.243Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Solved in the new backbone.
