### ISSUE TITLE
10.5281/zenodo.3608758 does not show up in GBIF

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#2379]
To whom it may belong
This Plazi collection 10.5281/zenodo.3608758 does not show up in GBIF - do you have a long processing queue right now (which I can't see right now on https://registry.gbif.org/monitoring/ingestion 

thanks for a brief feedback

**Comment by thomasstjerne** [comment]
It is in now: https://www.gbif.org/dataset/3269bae6-36d8-4c4e-a814-cda94b6aeece

Our backend team has worked on some adjustments that may have queued up some ingestions.
