### ISSUE TITLE
displaying gbif institution page inside iframe

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#238]
**displaying gbif institution page inside iframe**

Is there anything wrong with displaying GBIF served pages inside an iframe?
We are insterested only in displaying info belonging to and provided from our own institution.

I know there are other much better ways to do it using the API, more suited to whatever we want to show.

But in the mean time this would be a quick and easy way of displaying the image gallery of specimens shared by our institution. 
Of course there is no problem in clearly acknowledging GBIF in a banner close to the iframe

-----
fbitem-90ca04c707cd953f778e8789ed7ec98e67b20053
Reported by: sant.herbarium@gmail.com
System: Chrome 49.0.2623 / Windows XP 0.0.0
Referer: https://demo.gbif.org/occurrence/gallery?publishing_org=def87a70-0837-11d9-acb2-b8a03c50a862
Window size: width 992 - height 1550
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-05T17:50:12.675Z',mode:absolute,to:'2017-07-05T17:56:12.675Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-05T17:50:12.675Z',mode:absolute,to:'2017-07-05T17:56:12.675Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
You are welcome to do that, but - as you say - you would get a much better result with little effort by doing a gallery yourself i believe. If you need filtering, maps etc of course it becomes more complicated.

If we find that it is something publishers often need, we could also consider making a more dedicated iFrame that removed navbar and had a fixed prefilter (on say publisher or datasets or country).

![screen shot 2017-07-06 at 10 33 32](https://user-images.githubusercontent.com/6759267/27902702-e6fa0e16-6236-11e7-9e7c-92221b5b0203.png)

But yes - you are welcome to embed as an iframe. And if you need help getting started with a gallery and the API let me know.
