### ISSUE TITLE
Canis lupus in Australia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2381]
**Canis lupus in Australia**

As far as I can see, this is because the taxonomy considers Canis familiaris Linnaeus, 1758 a synonym of Canis lupus subsp. familiaris Linnaeus, 1758 (which is a subspecies of Canis lupus Linnaeus, 1758).

Is that really correct?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/c5767af9d745584da4e05765dc5e591b:e8d9413b62ef321dacadfc2b27d9c34cf79cded75489c4f3ca83d60c4ca1e5f876151975d2a9a401efeea84afeeb79afef563084c79de8e4ade8033f4b3f48d7)
System: Safari 13.0.4 / Mac OS X 10.15.2
Referer: https://www.gbif.org/occurrence/search?country=AU&taxon_key=5219173
Window size: width 1700 - height 979
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-16T14:34:56.807Z',mode:absolute,to:'2020-01-16T14:40:56.807Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-16T14:34:56.807Z',mode:absolute,to:'2020-01-16T14:40:56.807Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
I think we can close this. The "dog" taxonomy seems not settled. 

https://en.wikipedia.org/wiki/Dingo
> Its taxonomic classification is debated; as per the variety of scientific names presently applied in different publications, it is variously considered a form of domestic dog not warranting recognition as a subspecies; a subspecies of dog or wolf; or a full species in its own right.
