### ISSUE TITLE
Anthyllis vulneraria subsp. macedonica is not a synonym of Hippocrepis comosa L.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2383]
**Anthyllis vulneraria subsp. macedonica is not a synonym of Hippocrepis comosa L.**

This follow an email that we received on helpdesk.
These two species are not synonym.

In fact, this isn't the case in the original record from the Plant list: `https://www.gbif.org/species/118958142`

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/90516b5a77dd383385e5b197394d991d:4cf7753445201cd9ad080da7ec0f70d3bc7945925ce6fdad323bf2e65ef4533e0ee4cd35ff665dd8d8fee418effc758440a741e2ad47284aaddb1c1a6f5b864a)
System: Safari 13.0.4 / Mac OS X 10.15.2
Referer: https://www.gbif.org/species/8377001
Window size: width 2073 - height 1272
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-17T16:07:05.642Z',mode:absolute,to:'2020-01-17T16:13:05.642Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-17T16:07:05.642Z',mode:absolute,to:'2020-01-17T16:13:05.642Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Solved in the new backbone taxonomy.
