### ISSUE TITLE
Download species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2384]
**Download species**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f92fea1b53a77af0adeb010704752b74:68f2fff0c0cda80278e2358f6d2df3716b486c0612fd09c554bf72559973430983895cd238e54f743f021771ca5632d3eb4aae296fb8eb0d69b039d1938de9d9)
System: Opera 63.0.3368 / Windows 10.0.0
Referer: https://www.gbif.org/species/3120946
Window size: width 1840 - height 978
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-17T16:22:14.678Z',mode:absolute,to:'2020-01-17T16:28:14.678Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-17T16:22:14.678Z',mode:absolute,to:'2020-01-17T16:28:14.678Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Not enough information.
