### ISSUE TITLE
Oeneis polixenes (Fabricius, 1775) is not a synonym of Papilio polixenes Fabricius, 1775

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2386]
**Oeneis polixenes (Fabricius, 1775) is not a synonym of Papilio polixenes Fabricius, 1775**

This issue was reported to helpdesk by one of our users.

Oeneis polixenes (Fabricius, 1775) and Papilio polixenes Fabricius, 1775 should not be synonym.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/fe1824fd84fdb18eddd92550c2ca6eba:4386f74ce2d89d13c953d798a45f2333d722c0428f7b5572a858006b53618e82f6396038242ca83ade9e6b863abc42693bf6fb051077c5196944cb574d61d883)
System: Safari 13.0.4 / Mac OS X 10.15.2
Referer: https://www.gbif.org/species/5128279
Window size: width 1700 - height 979
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-21T09:16:15.386Z',mode:absolute,to:'2020-01-21T09:22:15.386Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-21T09:16:15.386Z',mode:absolute,to:'2020-01-21T09:22:15.386Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
same issue: https://github.com/gbif/portal-feedback/issues/3427
