### ISSUE TITLE
question to understand functioning of occurrence website: collected at

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#2391]
in this case https://www.gbif.org/occurrence/2558863054
![image](https://user-images.githubusercontent.com/4609956/73132905-c9aedc80-4021-11ea-924e-77de480a3139.png)
the holotype has a statment collected at unknown location. This is not really the case, because you in fact have the respective occurence. Originally, it has not been included- like so far all the zookeys article, but I made then now available. 

Will this change the collected at unknown location? How does this work?

**Comment by MortenHofft** [comment]
It simple takes the country code if provided. In this case it looks like it should be provided as China. 
It is not more smart than that and do not use the free text fields `Municipality` etc.

**Comment by myrmoteras** [comment]
ok - updated and looking forwards to seeing it. learned something this morning... tx

**Comment by kcopas** [comment]
Et, voilà!

![Screenshot 2020-01-27 at 14 46 21](https://user-images.githubusercontent.com/12379236/73179526-df043380-4113-11ea-8922-1ea02b268dae.png)
