### ISSUE TITLE
Explaining GBIF download columns

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2392]
**Explaining GBIF download columns**

I don't know if this was discussed before but it would be nice to have an FAQ explaining the header of the downloaded SIMPLE CSV file.

We just got an email on Helpdesk asking about that. It is not the first time we get questions like that.

The short answer I sent was the following:
> Most of the columns are mapped to Darwin Core Terms. You can find the definition of these terms on the TDWG website: `https://dwc.tdwg.org/terms/`
> However, some columns are GBIF-specific:
> * gbifID: the record identifier in GBIF, you can access a record online by adding the prefix `https://www.gbif.org/occurrence/` to its identifier (for example: `https://www.gbif.org/occurrence/2304124775).`
> * datasetKey: the UUID of the dataset from which the record comes from. You can access the dataset page by adding the prefix `https://www.gbif.org/dataset/` to its UUID (for example: `https://www.gbif.org/dataset/ad43e954-dd79-4986-ae34-9ccdbd8bf568).`
> * Issue: issues and flags automatically generated by our system when interpreting the records. You can find a list of the possible issues and flags and some explanations here: `https://gbif.github.io/gbif-api/apidocs/org/gbif/api/vocabulary/OccurrenceIssue.html.`

Would it make sense?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/9f16acc381164f94324b6515e53831df:5c9cd29e10936fea8db3ccce7041a60b2ae4b239a1324b0558d0b424a8162618e8fa77a9aca976479b42d0204f0d1820925c9dfeb0048a820a8f6faa2cee08e9)
System: Safari 13.0.4 / Mac OS X 10.15.2
Referer: https://www.gbif.org/faq?question=csv-download
Window size: width 1393 - height 777
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-27T09:43:39.524Z',mode:absolute,to:'2020-01-27T09:49:39.524Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-27T09:43:39.524Z',mode:absolute,to:'2020-01-27T09:49:39.524Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MattBlissett** [comment]
See https://techdocs.gbif.org/en/data-use/download-formats
