### ISSUE TITLE
grsicol operating?

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#2395]
@timrobertson100 does grsicol work again? It seems so. I

![image](https://user-images.githubusercontent.com/4609956/73233686-91291300-4187-11ea-8f2d-66b7427e1916.png)

http://tb.plazi.org/GgServer/html/03D10D23FFFD542FFF572B26FE03F82B, althoug we can't link to the respective species....

**Comment by timrobertson100** [comment]
Thanks, yes everything is fine now - https://www.gbif.org/health
Sorry for the outage

**Comment by myrmoteras** [comment]
@timrobertson100 sorry to confuse: I am wondering about the grsicol that seems to resolve again - this article's collection code has automatically be attributed with the respective PID and thus I am happy to see that this works again.
I did not worry about the services note
