### ISSUE TITLE
Data missing in occurrences download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2399]
**Data missing in occurrences download**

Hi,
I'm currently working on a project where I need the occurrence data of forest plants in Europe. After downloading the data (using the website at first but also trying out rgbif) I noticed some weird differences depending on how I downloaded the data. My test species was Stellaria holostea (taxonKey: 5384676) as it is widespread and I know it quite well. When I download it in a simple query via the website everything is fine. But once I try to work more efficiently, data is lost on the way somehow. When using rgbif and also when downloading the species data together with roughly 100 other species I lose the info of two datasets. One is especially annoying because it contains 8645 entries and completely messes up the distribution map. If that helps you in helping me, I identfied the dataset as being provided by the German Bundesamt für Naturschutz (institutionCode: BfN) but I cannot find any reasons for why this should be excluded from the other searches. I struggled for days to find a solution and now hope that you can help me.
Thank you for this great database!
Kathrin

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1c4cdc742a608ed81b0e95594b1d0aba:c44769918c97177f5bb570a0f4df9ea7cb9e43bdd2093d5f438583bddba4368ec4c623649bbf08be6b4ce62a5d3628b0adfc6a751c80f746d360c3da5883e82c)
System: Firefox 72.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0050132-191105090559680
Window size: width 1280 - height 910
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-30T10:37:51.788Z',mode:absolute,to:'2020-01-30T10:43:51.788Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-30T10:37:51.788Z',mode:absolute,to:'2020-01-30T10:43:51.788Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.

I suspect that the issue has to do with the number of records that we ingest from the German Bundesamt für Naturschutz.
 
I looked into the history of the [Flora von Deutschland (Phanerogamen)](https://www.gbif.org/dataset/e6fab7b3-c733-40b9-8df3-2a03e49532c1) on GBIF as an example.
* The 2nd of January 2020, we received around 8 million records from this dataset.
* The 10th, we got only around 3 million records (so around 5 million records were deleted).
* The 19th, we got almost 7 million records.
* The 29th, we got more than 9 million records.

As far as I can tell, this fits what can be observed in the downloads.
In the [download from the 9th of January](https://www.gbif.org/occurrence/download/0036074-191105090559680), there were 8,646 records from this dataset while on the [download from the 27th](https://www.gbif.org/occurrence/download/0050178-191105090559680), there weren't any record from this dataset.
Now, after the latest update, I can see [8,646 records of Stellaria holostea from this dataset](https://www.gbif.org/occurrence/search?dataset_key=e6fab7b3-c733-40b9-8df3-2a03e49532c1&taxon_key=5384676) in GBIF.
