### ISSUE TITLE
Map search failing with typical queries

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal-feedback#240]
I don't know if this is still a WIP, but anyway. With no other filters than "including coordinates"

* Adding the default range filter (-90 to 90, -180 to 180) returns 725 records, all on ±180°.

* Adding only a north-south filter (e.g. -58° to 58°) returns a subset of these 725 records on ±180°.

* Adding a wide east-west filter goes over the Pacific, but it is displayed on the tiny map as over Africa.

* The big map should probably scroll to where the results are.

If some of these are SOLR issues, we should fix them in the API rather than the portal.

Other than that, I like the interface. The range sliders should be easier to use for a lot of queries.

**Comment by MortenHofft** [comment]
To the best of my knowledge these are SOLR issues and something we have talked about multiple times during the last year no?

**Comment by MortenHofft** [comment]
> Adding a wide east-west filter goes over the Pacific, but it is displayed on the tiny map as over Africa.
Could you please provided an example query - i don't get this one i'm afraid

the first to seem to me like SOLR issues. at least there is also SOLR issues with those.

>The big map should probably scroll to where the results are. - YES

**Comment by MattBlissett** [comment]
They may well be. I think we should add some integration tests, and document it on the API page.

My example for the third entry is https://demo.gbif.org/occurrence/map?geometry=POLYGON%20((-90%20-27.870151412481935,%20-90%2022.398848050489416,%2099.84374999999999%2022.398848050489416,%2099.84374999999999%20-27.870151412481935,%20-90%20-27.870151412481935))

**Comment by MortenHofft** [comment]
But isn't the tiny map showing the correct result? We agree that the issue is the SOLR map right?

![screen shot 2017-07-19 at 14 14 49](https://user-images.githubusercontent.com/6759267/28366395-cb08d61e-6c8c-11e7-9e7a-8f607dc51351.png)
