### ISSUE TITLE
Science Review collection

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2403]
**Science Review collection**

I was looking for the webpage that has the full collection of GBIF Science Reviews since 2012. I found the annual individual pages - was this supposed to be a summary pages? If yes, it needs updates back into the history. I would like to see such at GBIF.org, even though visit and use will be low - unless added to new navigation or linked to the GBIF impact page / section discussed earlier.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/f2eac04d6db4807f785b82a264510ecd:9c4d6beea6c327da09557c85eb370a0e80e9b0d7bfa7c082d4a4febb70d2445ab34b2bff78ce1c5122b92f6fad6b694af91e0a44651246e9b686043842909602)
System: Chrome 79.0.3945 / Windows 10.0.0
Referer: https://www.gbif.org/science-review
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-31T10:10:11.617Z',mode:absolute,to:'2020-01-31T10:16:11.617Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-01-31T10:10:11.617Z',mode:absolute,to:'2020-01-31T10:16:11.617Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
I was thinking about this myself the other day, coming across the Science Review page. Will see to it.

**Comment by akristensen** [comment]
yes!

**Comment by kcopas** [comment]
Looks like the gang's all here:
https://www.gbif.org/resource/search?q=science%20review&contentType=document

Note that there is no 2015—we flipped the date forward in 2016, which covers the 2015 papers, and so on into the future.

**Comment by dschigel** [comment]
Yes, this what I found, too. Not sure if you see value in turning this search results into a webpage with the explanation of what they are (and what they are not ), why we have them, and the year flip?

**Comment by akristensen** [comment]
OK, so I can start adding the PDF's in chronological order? newest on top?

**Comment by kcopas** [comment]
Yes. Individual links, not search results. For now, just line-list them as links.

No need for anything more complicated, as once @dnoesgaard 's card-based landing page is ready, this is another sensible candidate.

**Comment by akristensen** [comment]
OK, just realising I might have misunderstood, 
https://www.gbif.org/science-review

Maybe it should have been links in stead in the text?

**Comment by dschigel** [comment]
To me this already enough, I would just explain 2015 to reduce questions, and then it could improve with cards view in due course

**Comment by kcopas** [comment]
yeah, looks great. I'll circle back to the text soon.

**Comment by akristensen** [comment]
Now with both options. missing 2017 it is really hidden on the site, found it through my contentful log in

**Comment by akristensen** [comment]
https://www.gbif.org/article/3QLcfg9I248ci6WYoyW20M/_preview

**Comment by akristensen** [comment]
2017 is really hidden, found it through my contentful log in 
it does not come up via search on gbif.org @dnoesgaard 
https://www.gbif.org/document/11axtLEZwMC6ouoioO4qsq/gbif-science-review-2017

**Comment by akristensen** [comment]
> Yes. Individual links, not search results. For now, just line-list them as links.
> 
> No need for anything more complicated, as once @dnoesgaard 's card-based landing page is ready, this is another sensible candidate.

Can somebody explain me the thing about cards?

**Comment by kcopas** [comment]
Planned, not yet developed. For future reference.
