### ISSUE TITLE
The locality "Loma Preluda S.W. of Cajalbana" occurs in Cuba not in Puerto Rico

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2406]
**The locality &quot;Loma Preluda S.W. of Cajalbana&quot; occurs in Cuba not in Puerto Rico**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a506a34dbe4bdc4ede78ede04f664596:10f85a45592f1f0e724da7c298a9b671233faeefd121f022f465d6412c87b5d3d60936067ed2f02bdafa67c8e0bd2caa4d0769c99e4abefac2a42d4e188c9574)
System: Firefox 47.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/occurrence/1929383976
Window size: width 683 - height 330
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-04T21:09:15.063Z',mode:absolute,to:'2020-02-04T21:15:15.063Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-04T21:09:15.063Z',mode:absolute,to:'2020-02-04T21:15:15.063Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: d415c253-4d61-4459-9d25-4015b9084fb0
publishingOrgKey: ae447c50-b8a8-11d8-92a4-b8a03c50a862

**Comment by ManonGros** [comment]
Contacted data providers by email.
