### ISSUE TITLE
How can I update the Organization pages for which I am the contact person?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2407]
**How can I update the Organization pages for which I am the contact person?**

I have created new Organization pages for George Mason University Herbarium (GMUF) and Lord Fairfax Community College Herbarium (LFCC). I would like to edit the contact information portion and the descriptions. But, I cannot find where/how I can access an edit function.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5be41c0728ecf01be8b6b39c399c3720:e5ef5f37a97eb3726107afff85257ab314ede98bfcf31ffdf601251d5420f28fb7e772817339ac757628049acafa2337c5e0f40a82f571c87ff7faa24ccc7de1)
System: Firefox 72.0.0 / Mac OS X 10.11.0
Referer: https://www.gbif.org/user/profile
Window size: width 1440 - height 739
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-05T18:38:42.776Z',mode:absolute,to:'2020-02-05T18:44:42.776Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-05T18:38:42.776Z',mode:absolute,to:'2020-02-05T18:44:42.776Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Answered by email.
