### ISSUE TITLE
Can I download distribution maps in KML?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2409]
**Can I download distribution maps in KML?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b9e01287324e779af755d37e39012eee:712a94ae344e9c534ff2652294424dc9ce546d8a90d5b191dfee65373d44b70504635b26b39cd27aa98482c400a6c088ef2c12112635148cb00bacc025421497)
System: Chrome 79.0.3945 / Mac OS X 10.15.2
Referer: https://www.gbif.org/health
Window size: width 889 - height 740
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-06T20:14:11.771Z',mode:absolute,to:'2020-02-06T20:20:11.771Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-06T20:14:11.771Z',mode:absolute,to:'2020-02-06T20:20:11.771Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
