### ISSUE TITLE
missing spaces in treatments

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#2410]
in this treatment, and in fact in many, there is a space missing between the taxonomic name and the label "n. sp."
https://www.gbif.org/species/162054365
See eg 
![image](https://user-images.githubusercontent.com/4609956/74020467-e9d38980-4999-11ea-907a-dc2ed205a44a.png)

**Comment by MortenHofft** [comment]
That is how it is provided in the source DwC archive of https://www.gbif.org/dataset/540d050b-de90-4176-9b1f-034ad19eecba

**Comment by gsautter** [comment]
I take it this is the HTML from the `media.txt`? That text is XSLT generated, so if there is no space punctuation mark (usually a comma) between the binomial and its status label and both of the latter are tagged, there is nothing separating the two tags ... XSLT and spaces are a problematic mix ... I'll see what I can do.

**Comment by gsautter** [comment]
Fixed for now ... got the space in between the binomial and its status label, but have a few obsolete spaces to fix in other places now.

**Comment by ManonGros** [comment]
Thanks a lot!

**Comment by gsautter** [comment]
Fixed the obsolete spaces as well now ... finally.
