### ISSUE TITLE
visual logo examples not loading

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2412]
**visual logo examples not loading**

See Logo types

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/cf9b06c261feaaaee11fc01842ea28f9:74a729d63b3b33f6b0a4a7126063e312be5b5b98f6c3dbcfaf558d123de8ad1d375fbf86c35b796004bc08468f7c8039445f5d9887555430aee80b44949288ff)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/logos
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-07T15:41:12.384Z',mode:absolute,to:'2020-02-07T15:47:12.384Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-07T15:41:12.384Z',mode:absolute,to:'2020-02-07T15:47:12.384Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Thanks @dschigel - I had noticed a missing logo last week, but I couldn't figure out what the problem was. Seems like these files were on a old CMS account or something. Anyway, re-uploaded and links fixed now.
