### ISSUE TITLE
The occurrences count doesn't match the original publication

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2413]
**The occurrences count doesn&#39;t match the original publication**

The page shows 2450 occurrences, the real count is 2452 (`https://ipt.biodiversidad.co/sinchi/resource?r=colombiabio_apaporis_coah&v=2.4)` from @sibcolombia already checked the maping but everything looks ok

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/96d7935bc388ceb42b4e352a25fd192e:f109ad05d03a5e21f27ccd30857215c5a7c08e693a6a9fa93c6a61a0a021df90efe2a1e5cf8ad0bd3e383ddd3878f06159a49fd6f23dc9f6af0b5fda57830e7e)
System: Chrome 79.0.3945 / Windows 7.0.0
Referer: https://www.gbif.org/dataset/a8f65e0b-5b75-4880-bebc-f9a3efe13ccd
Window size: width 1920 - height 977
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-07T16:31:14.250Z',mode:absolute,to:'2020-02-07T16:37:14.250Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-07T16:31:14.250Z',mode:absolute,to:'2020-02-07T16:37:14.250Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by camiplata** [comment]
Let me know if it is a bug from GBIF or if we need to take actions at the IPT
Thanks!

**Comment by muttcg** [comment]
Looks like an internal bug (gbifid?), the number match archive in DEV environment -> https://www.gbif-dev.org/dataset/a8f65e0b-5b75-4880-bebc-f9a3efe13ccd

**Comment by muttcg** [comment]
```
occId == occId -> gbifId
ColombiaBio:SINCHI:Apaporis:COAH:2018:27598 == ColombiaBio:SINCHI:Apaporis:COAH:2018:89 -> 2294340962
ColombiaBio:SINCHI:Apaporis:COAH:2018:154 == ColombiaBio:SINCHI:Apaporis:COAH:2018:28840 -> 2294340873
```

**Comment by MattBlissett** [comment]
```
c5gateway-vh ~ $ lookup-occurrence-key 2294340873
Lookup 2294340873 with dataset key from API a8f65e0b-5b75-4880-bebc-f9a3efe13ccd
 30:a8f65e0b-5b75-4880-bebc-f9a3efe13ccd|ColombiaBio:SINCHI:Apaporis:COAH:2018:28840 column=o:i, timestamp=1565273393068, value=\x00\x00\x00\x00\x88\xC0\xDD\x09
 39:a8f65e0b-5b75-4880-bebc-f9a3efe13ccd|Instituto Amaz\xC3\xB3nico de Investigaciones Cient\xC3\xADficas SINCHI|COAH|28840|null column=o:i, timestamp=1563977215656, value=\x00\x00\x00\x00\x88\xC0\xDD\x09
 64:a8f65e0b-5b75-4880-bebc-f9a3efe13ccd|ColombiaBio:SINCHI:Apaporis:COAH:2018:154 column=o:i, timestamp=1563977215646, value=\x00\x00\x00\x00\x88\xC0\xDD\x09
 79:a8f65e0b-5b75-4880-bebc-f9a3efe13ccd|Instituto Amaz\xC3\xB3nico de Investigaciones Cient\xC3\xADficas SINCHI|COAH|154|null column=o:i, timestamp=1576708613056, value=\x00\x00\x00\x00\x88\xC0\xDD\x09
```

The first two are the newer pair.

```
hbase(main):002:0> delete 'prod_h_occurrence_lookup', "30:a8f65e0b-5b75-4880-bebc-f9a3efe13ccd|ColombiaBio:SINCHI:Apaporis:COAH:2018:28840"

hbase(main):003:0> delete 'prod_h_occurrence_lookup', "39:a8f65e0b-5b75-4880-bebc-f9a3efe13ccd|Instituto Amaz\xC3\xB3nico de Investigaciones Cient\xC3\xADficas SINCHI|COAH|28840|null"
```

and ingestion rerun.

**Comment by MattBlissett** [comment]
> Let me know if it is a bug from GBIF or if we need to take actions at the IPT

Thanks for reporting the issue.  We had an unusual bug or edge case in GBIF, which is now resolved.

**Comment by camiplata** [comment]
Great! Thanks
