### ISSUE TITLE
The API isn't working on https as far as I can tell

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2416]
**The API isn&#39;t working on https as far as I can tell**

Compare

curl '`http://api.gbif.org/v1/species/match?name=Poa%20annua&limit=10'`

{"usageKey":2704179,"scientificName":"Poa annua L.","canonicalName":"Poa annua","rank":"SPECIES","status":"ACCEPTED","confidence":97,"matchType":"EXACT","kingdom":"Plantae","phylum":"Tracheophyta","order":"Poales","family":"Poaceae","genus":"Poa","species":"Poa annua","kingdomKey":6,"phylumKey":7707728,"classKey":196,"orderKey":1369,"familyKey":3073,"genusKey":2704173,"speciesKey":2704179,"synonym":false,"class":"Liliopsida"}

To:

curl '`https://api.gbif.org/v1/species/match?name=Poa%20annua&limit=10'`

curl: (56) Unexpected EOF

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7e91f9c0fc48b52d12feee0e2676cac2:496ac837753c26bbc3998a3e5e53bd8471ec105a75501cdb19423af475a267856a9f57ccd994a3966647100ac8a27c3ef79662654b1a1ca1f9674d0acb01dc53)
System: Chrome 80.0.3987 / Mac OS X 10.14.6
Referer: https://www.gbif.org/health
Window size: width 1680 - height 952
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-08T23:54:37.763Z',mode:absolute,to:'2020-02-09T00:00:37.763Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-08T23:54:37.763Z',mode:absolute,to:'2020-02-09T00:00:37.763Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by sckott** [comment]
Although, I don't get this problem on other routes regardless of http vs https, so it may not be an SSL problem per se, but rather only a problem with when using this route?

**Comment by MattBlissett** [comment]
Hi Scott,

I can't see any problem.  Can you try `curl -v 'https://api.gbif.org/v1/species/match?name=Poa%20annua&limit=10'` and paste what you see?

**Comment by sckott** [comment]
Weird, It works now 

```
curl -v 'https://api.gbif.org/v1/species/match?name=Poa%20annua&limit=10'
```

<details> <summary><strong>output</strong></summary>

```
*   Trying 130.225.43.2...
* TCP_NODELAY set
* Connected to api.gbif.org (130.225.43.2) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.gbif.org
*  start date: Jun 12 00:00:00 2018 GMT
*  expire date: Jun 11 23:59:59 2020 GMT
*  subjectAltName: host "api.gbif.org" matched cert's "*.gbif.org"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fcfdf008c00)
> GET /v1/species/match?name=Poa%20annua&limit=10 HTTP/2
> Host: api.gbif.org
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< date: Mon, 10 Feb 2020 17:22:49 GMT
< content-type: application/json
< access-control-allow-origin: *
< access-control-allow-methods: HEAD, GET, POST, DELETE, PUT, OPTIONS
< server: Jetty(9.3.z-SNAPSHOT)
< cache-control: public, max-age=3601
< x-varnish: 571147989 602439901
< age: 22
< via: 1.1 varnish (Varnish/5.2)
< accept-ranges: bytes
< content-length: 429
<
* Connection #0 to host api.gbif.org left intact
{"usageKey":2704179,"scientificName":"Poa annua L.","canonicalName":"Poa annua","rank":"SPECIES","status":"ACCEPTED","confidence":97,"matchType":"EXACT","kingdom":"Plantae","phylum":"Tracheophyta","order":"Poales","family":"Poaceae","genus":"Poa","species":"Poa annua","kingdomKey":6,"phylumKey":7707728,"classKey":196,"orderKey":1369,"familyKey":3073,"genusKey":2704173,"speciesKey":2704179,"synonym":false,"class":"Liliopsida"}
```
</details>

**Comment by MortenHofft** [comment]
I'm closing this - please let us know if the issue reappears
