### ISSUE TITLE
Taxonomic names mismatch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2417]
**Taxonomic names mismatch**

Specimens of the genus "Kiwi" Khalaim & Ward, 2019, are being assigned to the wrong phylum.

Species of "Kiwi" Khalaim & Ward, 2019, are insects in the Order Hymenoptera (Ichneumonidae) but are being assigned as birds (Aves: Apterygidae) probably because of the common name "Kiwi" for birds

Khalaim AI & Ward DF. 2019. Tersilochinae (Hymenoptera: Ichneumonidae) from New Zealand. Part 2. Review of genera Kiwi gen. nov. and Zealochus Khalaim. Zootaxa 4613 (3): 521–545. `https://doi.org/10.11646/zootaxa.4613.3.6`

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7a07ef65dcca9c86dbf9fb18d88999c9:906eb7b942cde7c9105c9f782185d5c8b95a8b63ef253b52669ec95f66c2bac4f9182d68ed81a1b72e712801757d95ae2e7f12faced41d120ecee053f190afce)
System: Chrome 79.0.3945 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-09T21:33:01.450Z',mode:absolute,to:'2020-02-09T21:39:01.450Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-09T21:33:01.450Z',mode:absolute,to:'2020-02-09T21:39:01.450Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Same as / Related to this issue: https://github.com/gbif/portal-feedback/issues/2316
