### ISSUE TITLE
eventDate incorrect. See thread https://twitter.com/dpsSpiders/status/1227289495982268417

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2421]
**eventDate incorrect. See thread `https://twitter.com/dpsSpiders/status/1227289495982268417`**

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/ec00f40f374c0bd385632d833667038a:050e43657fb5efecd76d6ee3cea587abfd59fa2814d440bb2ce5fa54a303f26ccbf5fc1ea68988d6e043f0266cfd4aa5afd8b28969a45d4cd05070abc08f76ae26e18c6b5ff112bd75d1676e695d613b)
System: Chrome 80.0.3987 / Mac OS X 10.15.3
Referer: https://www.gbif.org/occurrence/1099994705
Window size: width 1390 - height 722
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-11T20:11:23.129Z',mode:absolute,to:'2020-02-11T20:17:23.129Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-11T20:11:23.129Z',mode:absolute,to:'2020-02-11T20:17:23.129Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 4bfac3ea-8763-4f4b-a71a-76a6f5f243d3
publishingOrgKey: b4640710-8e03-11d8-b956-b8a03c50a862

**Comment by ManonGros** [comment]
I reported the issue via the MCZ feedback system.

**Comment by kcopas** [comment]
Can you provide a direct link to that @ManonGros ?

We could keep it busy for weeks on their fubar dates…

**Comment by ManonGros** [comment]
You have two options:
* use their search interface: https://mczbase.mcz.harvard.edu/SpecimenSearch.cf and look for the specimen you need (I used the catalogue number for that),
* or use the link they provide in the references: https://mczbase.mcz.harvard.edu/guid/MCZ:Ent:536246 and click on "Return to result" (see screenshot.
![Screenshot 2020-02-12 at 14 08 03](https://user-images.githubusercontent.com/7677271/74337754-3277b200-4da1-11ea-9cc1-faacdfcbf976.png)
----

Then you have to click on "Report bad data" and fill their form (see the two screenshots below):


![Screenshot 2020-02-12 at 14 04 20](https://user-images.githubusercontent.com/7677271/74337538-c1d09580-4da0-11ea-9b2a-204013d60ef5.png)
![Screenshot 2020-02-12 at 14 05 01](https://user-images.githubusercontent.com/7677271/74337548-c5641c80-4da0-11ea-988c-e4441b9d2914.png)

**Comment by MattBlissett** [comment]
If we get lots of feedback for datasets on this system, we should ask them to improve that form so we can link to it directly. It can then be added for direct feedback, as we do for iNaturalist records etc.

**Comment by MattBlissett** [comment]
Looks to have been fixed.
