### ISSUE TITLE
Preserve record-level licences over dataset-level ones

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/portal-feedback#2423]
For occurrence datasets, dataset-level licenses are mandatory, and have to be chosen from a limited set of options (CC0, CC BY, CC BY-NC) - the rationale for this is explained in other places. Most datasets do not contain record-level licenses, and in these cases, the dataset license is transfered to the contained occurrence records to allow filtering and informed use of data in mixed data downloads.

Some datasets, like iNaturalist, come with individual verbatim licenses for occurrence records as well as with the mandatory dataset license. Where this is the case, the dataset license at present still overrides the individual occurrence license. We want to change this so that recognizable and supported occurrence licenses get preserved and are available to searches.

Example: according to specifications, https://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7 is published under the most restrictive license of records contained in the dataset. Individual records inside the set have also been published under CC0 (about 462k records) or CC BY (about 1.23mio records to date), but currently get subsumed in the total 12.7mio and issued with CC BY-NC. In future, we want these records to be discoverable in a search for CC0 or CC BY-licensed records.

The same should apply to all datasets that contain records with an explicit license statement, provided 
(a) the license is recognizable, and 
(b) it still falls into the accepted set of CC0, CC BY and CC BY-NC

Some issues to consider when rolling this out for all datasets:
Point (a) will most likely need some kind of mapping, as the verbatim license statement is a free text field and is not in all cases easily interpreted. 
Point (b)  
- may need communication with publishers in those cases where a blanket, but unusable text is supplied for all records that has so far been overridden by the dataset license (analysis of the size of this problem to follow), or where the license cannot be interpreted from the contained varied free text values. The instruction here would be to 
-- either add a recognizable license statement, 
-- or to revert to NULL values, in which case the dataset-level license can again kick in. 
- Where a license cannot be interpreted from the record license, or the license does not fall into the agreed set, the record should be excluded from indexing.

Datasets with more than one distinct text string in the occurrence record license field:

| datasetkey | num_distinct_verbatim_licenses |
| --- | --- |
| 872e998a-7ff6-4384-9b25-a4bb6c0d71f1 | 1850    <- probably excel dragging error |
| 7c67da7f-490e-4e8d-8848-7dc152dd4734 | 166 |
| 7a28b1b1-9d4c-4aeb-b239-38865417b5ea | 147 |
| d5e61920-9863-4fc3-8e5a-80f0c7bfe640 | 143 |
| e6d20998-59b1-4032-b4d1-bfe35671be54 | 54 |
| 7bb2d451-5ffa-4d58-bc7f-19ea7aecb201 | 31 |
| 6676b3f8-e389-4911-aa09-2e04f964a419 | 8 |
| ad4c9413-95bc-4b3c-a1e9-b7cf16f391a2 | 4 |
| 50c9509d-22c7-4a22-a47d-8c48425ef4a7 | 3   <- iNaturalist |
| b42a2e9a-fba0-41bf-ba18-d430cc6c3c59 | 2 |
| eaf9401e-a5e3-4a27-89ad-2d6ac6559167 | 2 |
| 275319e1-f91c-406f-b239-62cb9d4185cb  | 2 |
| f1a4ce9a-97cd-4d35-bf5e-561f2f1c6d91 | 2 |
| 3e0987c4-375f-4d68-b2ac-5e4e3a6d3d6d | 2 |
| 891af376-b9b7-4547-b17d-e1d2e6b8d96b | 2 |
| f861b96e-76f8-4a4d-b301-ebb82eed6011 | 2 |
| e0aff3c8-3e32-412b-888c-fde75c2e8750 | 2 |
| 3484c814-c0f1-453c-8501-50d4846c4ba6 | 2 |
everything below this point has 1 or fewer licenses supplied to GBIF
| 78dcee36-b0a2-4679-802d-bc0b5016518b | 1 |  
| 377fe452-9ed9-4092-a0fe-55b7d69fb258 | 1 |
| 7afb26e9-aad6-47cb-a5bf-de49dc7597a4 | 1 |

NB. that also for only 1 distinct string, the value may be uninterpretable, and need review

**Comment by muttcg** [comment]
The fix was deployed in PROD, all datasets were reinterpreted
