### ISSUE TITLE
Couldn't find csv file after downloaded succesfully.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2426]
**Couldn&#39;t find csv file after downloaded succesfully.**

After download, I could only find the text.file or XML files in it without anyone marked as csv.
I want to fugure out why but I can't.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bc7ab4661c453c017de53a8aea20d104:120af6a1bc65266a24a1a2ddb8db30e688c4cce77b16073a2dbaad286624fb20247865f33f3dd7b675422decc3fcfa2bd469d8e20de8d4d4c05422f5b13cc6d6)
System: Chrome 79.0.3945 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=Why%20only%20XML%20files%20exising%20in%20my%20download%20files%3F
Window size: width 1536 - height 674
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-13T21:08:25.616Z',mode:absolute,to:'2020-02-13T21:14:25.616Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-13T21:08:25.616Z',mode:absolute,to:'2020-02-13T21:14:25.616Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
