### ISSUE TITLE
GEOLocate probable source of many country centroids and other issues.

### ISSUE THREAD

**Issue by jhnwllr** [gbif/portal-feedback#2428]
**GeoLocate** ( https://www.geo-locate.org/ ) is a website service that helps natural history museums turn a locality into lat-lon coordinates.

### GeoLocate returns country centroids from country strings

When a user only supplies a country name (with no locality name), it returns the **country centroid**. 

Examples:
https://www.gbif.org/occurrence/477217972
https://www.gbif.org/occurrence/1318974889

### 301 coordinateUncertaintyInMetres
GeoLocate will give the country centroid a default coordinateUncertaintyInMetres of **301**. 

Example when giving only "Japan" as the country. 
```
lat: 36, lon: 138, pattern: JAPAN, error polygon: Unavailable, uncertainty: 301 m, precision: High(80)
```
```
sqlContext.sql("SELECT * FROM uat.occurrence_pipeline_hdfs").
filter($"coordinateuncertaintyinmeters" === 301).
count()
```
* 370K occurrences have **301m** for coordinateuncertaintyinmeters. 
* **301m** is probably the default minimum, so we can assume that most records with this value are suspect. 

### extent of the issue

Around 2 M occurrences fill in the **georeferenceprotocol** DWCA field with some type of "geolocate" string. 

```
val sqlContext = new org.apache.spark.sql.SQLContext(sc)
val df = sqlContext.sql("SELECT * FROM prod_h.occurrence_pipeline_hdfs").
filter($"georeferenceprotocol".rlike("(?i)GeoLocate")).
count()
```

```
SELECT count(*) FROM occurrence_pipeline_hdfs 
WHERE georeferenceprotocol = "GEOLocate" AND locality IS NULL LIMIT 1000;
```

**Comment by jhnwllr** [comment]
Table of how many country centroids for each georeferenceprotocol: 

georeferenceprotocol | num_of_occ
-- | --
null | 294380
GEOLocate | 31064
Google Earth | 15375
TGN - Centroid | 5298
Getty Thesaurus o... | 1559
Area polygon calc... | 634
MaNIS georeferenc... | 367
doi:10.1080/13658... | 296
MaNIS/HerpNET/ORN... | 259
Escobar D, Jojoa ... | 189
MaNIS/HerpNet/ORN... | 130
GEOREF tool | 128
unknown, from legacy | 125
VertNet Georefere... | 124
Mapa Geografico d... | 69
Gazetteer | 60
Getty Thesaurus o... | 49
GeoLocate | 48
not recorded | 45
Geonet Names Serv... | 37

**Comment by jhnwllr** [comment]
See how CoordinateCleaner centroids compare with centroids from Geolocate here. 
https://github.com/jhnwllr/gbif_shapefile_geocoder/blob/master/shapefile_making_R_scripts/plots/centroids/combined.pdf

**Comment by MattBlissett** [comment]
Your list, and my reimplementation of it, is just using ISO 3166 areas.

Should we also look at states and provinces? e.g. http://geo-locate.org/webservices/geolocatesvcv2/glcwrap.aspx?country=China&locality=Anhui,+China&state=Anhui&county= → 31.916667°N, 117.166667°E

Or maybe the state/province should be sufficiently large.

A centroid from GADM of Anhui province is  31.825789°, 117.226230°.

I don't know if there are other non-country values that Geolocate would give different centroids for, like "Contiguous United States" or "Great Britain" or "Metropolitan France" or "Channel Islands" etc.

**Comment by jhnwllr** [comment]
I agree it might be worth looking into GeoLocate at the sub-country level. I am sure there are others in there.  I will probably look into running some stats at the sub-country level. We might want to eventually contact the people running the service...

### stats 
For the country-level centroids, I ran some statistics with 2km buffer. 

Both centroid sources together flagged: **410 459** gbifids

CoordinateCleaner non-unique gbifids flagged : **342 397**
GeoLocate non-unique gbifids flagged: **239 982**

CoordinateCleaner flagged **170 674** unique to itself gbifids
GeoLocate flagged **68 259** unique to itself gbifids 

Geolocate centroids often overlap with the ones from CoordianteCleaner, but there are others for example in BE and CZ are not in caught by CoordinateCleaner.  

source | iso2 | lat | lon | count
-- | -- | -- | -- | --
http://geo-locate.org | MX | 23 | -102 | 20910
CoordinateCleaner | MX | 23 | -102 | 20910
http://geo-locate.org | BR | -10 | -55 | 17814
CoordinateCleaner | BR | -10 | -55 | 17814
CoordinateCleaner | IN | 22.88348 | 79.6162 | 11438
CoordinateCleaner | GB | 54.163 | -2.8969 | 8819
CoordinateCleaner | BR | -10.7731 | -53.0898 | 8193
CoordinateCleaner | DE | 51 | 9 | 7345
CoordinateCleaner | PH | 13 | 122 | 7305
CoordinateCleaner | PY | -23.2362 | -58.391 | 6571
http://geo-locate.org | CZ | 50 | 14.5 | 6355
http://geo-locate.org | BE | 50.74432 | 4.52368 | 5862
CoordinateCleaner | NP | 28.25301 | 83.93855 | 5311
CoordinateCleaner | MX | 23.95047 | -102.533 | 5267
CoordinateCleaner | AO | -12.2953 | 17.54468 | 5024
http://geo-locate.org | JP | 36 | 138 | 4866
CoordinateCleaner | JP | 36 | 138 | 4866
http://geo-locate.org | SE | 62 | 15 | 4860
CoordinateCleaner | SE | 62 | 15 | 4860
http://geo-locate.org | NL | 52.25 | 5.75 | 4802
CoordinateCleaner | CU | 21.5 | -80 | 4800
http://geo-locate.org | FR | 46 | 2 | 4779
CoordinateCleaner | FR | 46 | 2 | 4779
http://geo-locate.org | DE | 51.5 | 10.5 | 4762
CoordinateCleaner | BR | -10.7731 | -53.0897 | 4668
CoordinateCleaner | JM | 18.25 | -77.5 | 4667
http://geo-locate.org | JM | 18.25 | -77.5 | 4667
CoordinateCleaner | CR | 10 | -84 | 4159
http://geo-locate.org | GY | 5 | -59 | 4126
CoordinateCleaner | GY | 5 | -59 | 4126
CoordinateCleaner | IN | 20 | 77 | 3984
http://geo-locate.org | IN | 20 | 77 | 3984
http://geo-locate.org | IT | 42.8333 | 12.8333 | 3912
CoordinateCleaner | JM | 18.15142 | -77.319 | 3871
http://geo-locate.org | AU | -25 | 135 | 3801
CoordinateCleaner | CO | 3.901155 | -73.0734 | 3633
http://geo-locate.org | FJ | -18 | 178 | 3464
CoordinateCleaner | LK | 7 | 81 | 3460
CoordinateCleaner | NO | 61.15408 | 8.727591 | 3374
CoordinateCleaner | CD | 0 | 25 | 3052
http://geo-locate.org | DK | 56 | 10 | 2839
CoordinateCleaner | DK | 56 | 10 | 2839
http://geo-locate.org | BZ | 17.25484 | -88.7591 | 2756
CoordinateCleaner | BZ | 17.25484 | -88.7591 | 2756
CoordinateCleaner | MX | 23.95056 | -102.533 | 2583
CoordinateCleaner | NC | -21.5 | 165.5 | 2577
CoordinateCleaner | CN | 35 | 105 | 2500
http://geo-locate.org | CN | 35 | 105 | 2500
CoordinateCleaner | TR | 39.06056 | 35.17972 | 2370
CoordinateCleaner | MG | -19.3734 | 46.70604 | 2142
CoordinateCleaner | IN | 22.88361 | 79.61611 | 2105
CoordinateCleaner | ES | 40.22694 | -3.64944 | 2067
http://geo-locate.org | MG | -20 | 47 | 2013
CoordinateCleaner | MG | -20 | 47 | 2013
CoordinateCleaner | BE | 50.82341 | 3.99999 | 1971
http://geo-locate.org | BE | 50.82341 | 3.99999 | 1971
CoordinateCleaner | BO | -16.7146 | -64.6709 | 1959
CoordinateCleaner | IT | 42.8333 | 12.8333 | 1956
http://geo-locate.org | BE | 50.82977 | 4.01142 | 1953
CoordinateCleaner | BE | 50.82977 | 4.01142 | 1953
http://geo-locate.org | TH | 15 | 100 | 1932
CoordinateCleaner | TH | 15 | 100 | 1932
http://geo-locate.org | TN | 34 | 9 | 1913
CoordinateCleaner | TN | 34 | 9 | 1913
CoordinateCleaner | VE | 7.122449 | -66.1696 | 1861
http://geo-locate.org | CL | -30 | -71 | 1849
CoordinateCleaner | CL | -30 | -71 | 1849
http://geo-locate.org | HT | 19 | -72.4167 | 1828
CoordinateCleaner | PE | -10 | -76 | 1822
http://geo-locate.org | PE | -10 | -76 | 1822
CoordinateCleaner | ET | 8 | 38 | 1798
CoordinateCleaner | CH | 47 | 8 | 1769
http://geo-locate.org | CH | 47 | 8 | 1769
CoordinateCleaner | TZ | -6 | 35 | 1728
http://geo-locate.org | TZ | -6 | 35 | 1728
http://geo-locate.org | EC | -2 | -77.5 | 1658
CoordinateCleaner | EC | -2 | -77.5 | 1658
http://geo-locate.org | AT | 47.3333 | 13.3333 | 1652
http://geo-locate.org | RU | 60 | 47 | 1647
CoordinateCleaner | HU | 47 | 20 | 1625
http://geo-locate.org | HU | 47 | 20 | 1625
http://geo-locate.org | EE | 59 | 26 | 1597
CoordinateCleaner | EE | 59 | 26 | 1597
CoordinateCleaner | SB | -8 | 159 | 1585
CoordinateCleaner | SV | 13.7369 | -88.8665 | 1571
http://geo-locate.org | CA | 60 | -96 | 1460
http://geo-locate.org | BT | 27.50142 | 90.50621 | 1458
CoordinateCleaner | BT | 27.50142 | 90.50621 | 1458
http://geo-locate.org | ET | 8 | 39 | 1445
http://geo-locate.org | PA | 9 | -80 | 1416
CoordinateCleaner | PA | 9 | -80 | 1416
http://geo-locate.org | ID | -5 | 120 | 1392
CoordinateCleaner | ID | -5 | 120 | 1392
http://geo-locate.org | CZ | 49.75 | 15 | 1344
http://geo-locate.org | CM | 6 | 12 | 1339
CoordinateCleaner | CM | 6 | 12 | 1339
CoordinateCleaner | FR | 46.5597 | 2.553 | 1320
http://geo-locate.org | DJ | 11.54327 | 43.15481 | 1314
http://geo-locate.org | IR | 32 | 53 | 1289
CoordinateCleaner | IR | 32 | 53 | 1289

**Comment by jhnwllr** [comment]
I 
I think 

I think we should perhaps only flag centroids that are PRESERVED_SPECIMEN. The others are probably false positives. Especially when we get down to the sub-country level. 
basisofrecord | count
-- | --
PRESERVED_SPECIMEN | 294318
HUMAN_OBSERVATION | 81728
UNKNOWN | 13836
FOSSIL_SPECIMEN | 8896
MATERIAL_SAMPLE | 8019
LIVING_SPECIMEN | 2287
OBSERVATION | 1187
MACHINE_OBSERVATION | 187
LITERATURE | 1

**Comment by jhnwllr** [comment]
I have been looking into this more with the environmental outliers work. Many environmental outliers seem to be centroids from GeoLocate.  

I really think that **301m** for CoordinateUnvertaintyInMeters should be a **data quality flag**. It would be a simple record-by-record flag. 

Maybe something like " **KNOWN_DEFAULT_COORDINATE_UNCERTAINTY** ". 

@muttcg

**Comment by tucotuco** [comment]
That seems like a good idea to me. Such a flag could facilitate a cleanup.

**Comment by jhnwllr** [comment]
I am going to close this now since Geolocate is part of the 
https://github.com/jhnwllr/catalogue-of-centroids
