### ISSUE TITLE
replace copyright sign with (c)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2433]
**replace copyright sign with (3)**

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/bf07758ede869d2b8a1963503a545086:63952d02472a1cfe1afe2fa26011f78f80815f354e97be0dc38d265e92568a04ace076085235274e1ced961aada28678706313a4a6a8ae9c210b1413d1eb7f23)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/terms/data-publisher
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-17T21:42:23.145Z',mode:absolute,to:'2020-02-17T21:48:23.145Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-17T21:42:23.145Z',mode:absolute,to:'2020-02-17T21:48:23.145Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
Sorry, not (3) but (c).
