### ISSUE TITLE
FAQ difference in the number of records in download between page and file

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#2434]
Suggestion for an FAQ (not sure if this is the best way to explain it):

**Why doesn't the file I download contain the same number of records displayed on the download page?**

The number of records displayed on download pages is generated with our Elasticsearch-based system, which is constantly updated. This number might differ from the number of records actually contained in the download file. This is the case for very large downloads as they are generated from a different system which uses a table rebuilt every 24 hours.

**Comment by MattBlissett** [comment]
What we really ought to do is update the download metadata with the real number, after the download has been produced.

We already update the dataset citations table, and this is just be the sum of all those values.

**Comment by dnoesgaard** [comment]
Just so I understand completely:

1) I do a search that yields 10,000 records
2) When I hit download, metadata is populated immediately based on information in ES
3) The final download, being based on a separate table, might differ slightly, resulting in metadata being off

Is this correct?

**Comment by ManonGros** [comment]
As far as I understand this is the case.

But if we could update the metadata with the actual number of records, it would be even better!

**Comment by dnoesgaard** [comment]
I guess technically, metadata in general should be based on what the download contains, i.e. also links to datasets, etc.

**Comment by dnoesgaard** [comment]
I rewrote the FAQ a bit to avoid too much technical lingo:

https://www.gbif.org/faq?question=why-does-my-download-contain-a-different-number-of-records-than-reported-in

Let me know if anything need changing. Otherwise, I'll take silence as agreement :)

**Comment by kcopas** [comment]
I don’t think we need to be overly explicit or emphatic, but maybe defining large datasets parenthetically as “(approximately 100,000 records or more)” would be a useful addition. 

Could even save it for the last paragraph, or qualify it as a current threshold…just a thought. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
