### ISSUE TITLE
duplicate dataset 

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#2437]
why are there two datasets that are slightly differnt (58 vs 57 occurrences, no vs with map) for 

![image](https://user-images.githubusercontent.com/4609956/75015384-c07e2780-5488-11ea-8d4d-1c05edf7bfa6.png)

https://www.gbif.org/search?q=%2210.5852%2Fejt.2020.606%22

@gsautter

**Comment by ahahn-gbif** [comment]
There are two registrations from Feb 20 and 21, with different endpoints (http://tb.plazi.org/GgServer/dwca/9D1CFFC0C960D657FF99FFF1FFC9635C.zip, 
http://tb.plazi.org/GgServer/dwca/0C2AFFBDFFE5FFB3FFB4FF82C4226027.zip). Should not one of these be withdrawn at source?

**Comment by gsautter** [comment]
Most definitely ... this was a rare accident where the same article was imported independently by two different users ... this is normally caught via the byte based checksum of the original PDF, but in this case, one user used the PDF, and the other one the PDF/A, which differ on the byte level, defeating the checksum approach.

We will take case of this rare occurrence asap, which will also take down one of the two datasets.

**Comment by ahahn-gbif** [comment]
Hi @gsautter, not sure what happened, but your change did not make it through to us: we still find both at https://www.gbif.org/search?q=%2210.5852%2Fejt.2020.606%22. Would you have a chance to check?

**Comment by gsautter** [comment]
@ahahn-gbif this is an isolated case of a PDF that was converted and imported in our systems twice, once as a normal PDF, and once as a PDF/A, and since the two files are different at the byte level, hash based duplicate detection had no chance of catching this one.

We'll be removing one of the duplicates in due time, sorry for the inconvenience.

**Comment by ManonGros** [comment]
Adding PLAZI organization key to this issue to help them keep an eye on it: 7ce8aef0-9e92-11dc-8738-b8a03c50a862

**Comment by mguidoti** [comment]
Thanks, @ManonGros !

**Comment by gsautter** [comment]
Taken care of. I simply renamed the `treatment`s in the duplicate that was added later to `treatmentDuplicate`, effectively removing them from TreatmentBank and all export destinations served from there, so the duplicate dataset (b36d4f5e-a68c-4930-aa94-50250dd93c67) is gone now.
