### ISSUE TITLE
Sharing Specify data with Symbiota (SCAN)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2438]
**Sharing Specify data with Symbiota (SCAN)**

We are setting up our local version of Specify 6.7.04 to share data with SCAN (Symbiota Collections of Arthropods Network).  According to the setup instructions from Specify we need a "Base URL" from Symbiota and security key.
Can this be provided?  If there is anything else needed from the Symbiota side, please let me know. Or if any information is needed from our collection.
Thanks very much!
Ralph Holzenthal
University of Minnesota Insect Collection

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e826f5c9be308521b3b2bfafe954e42d:6c3241fc75e166839fdf3ec135acdc3a670b9a271e1788729ceaebcf6b0f8cf8e6d737cdf741b01468b1d176f7004d64d8139b43c2f4e348852b18f997d34be3)
System: Chrome 80.0.3987 / Mac OS X 10.14.6
Referer: https://www.gbif.org/installation/2c733a9d-363d-4d66-9aef-3e0f7bc44bec
Window size: width 1082 - height 666
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-22T22:56:05.339Z',mode:absolute,to:'2020-02-22T23:02:05.339Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-22T22:56:05.339Z',mode:absolute,to:'2020-02-22T23:02:05.339Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
replied by email.
I advised to contact directly the SCAN technical support: https://scan-bugs.org/portal/misc/contacts.php
