### ISSUE TITLE
extant

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2440]
**extant**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/13fe33dc17c2e3822e4c34618e621935:8e5bb2b672be50d93d8e6ece0bcb6e649e6f52aa766106adb6e92009737319699c3965a7a079f6791f48d08f011c637157cd007a8001c229e7b681aef4852e0e)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/charts?has_coordinate=true&has_geospatial_issue=false&taxon_key=953&advanced=1&geometry=POLYGON((-180%20-23.5,180%20-23.5,180%2023.5,-180%2023.5,-180%20-23.5))
Window size: width 1536 - height 754
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-23T19:36:48.079Z',mode:absolute,to:'2020-02-23T19:42:48.079Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-23T19:36:48.079Z',mode:absolute,to:'2020-02-23T19:42:48.079Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Closing as lacking enough information
