### ISSUE TITLE
NodeCommittee page contains a link to Terms of Reference that points to old URL.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2441]
**NodeCommittee page contains a link to Terms of Reference that points to old URL.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/66bcf633650dc3e237f0be64b7974495:57c404349b206605cd8be9f146f414591c52669a71508c692d918f2cc2a73b4d8663c5f1e2adfca160098a67b33ab8eb69d6d8151c0dd4b4c4c43ebaf91159e8)
System: Chrome 79.0.3945 / Mac OS X 10.15.3
Referer: https://www.gbif.org/contact-us/directory?group=nodesCommittee
Window size: width 1024 - height 800
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-25T08:32:33.666Z',mode:absolute,to:'2020-02-25T08:38:33.666Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-25T08:32:33.666Z',mode:absolute,to:'2020-02-25T08:38:33.666Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Thanks for reporting. Fixed in [translations](https://crowdin.com/translate/gbif-portal-en/132/endk-en#10039). Will require rebuild of portal to take effect.
