### ISSUE TITLE
Add a journal (Big Earth Data)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2443]
**Add a journal**

Big Earth Data is missing and needs to be added
`https://www.tandfonline.com/action/journalInformation?show=aimsScope&journalCode=tbed20.` Pls let me know as I will need to reply to the journal using the updated link

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/bd5c95b366d54ea0b90049e7459e14c9:e150ef8ac9071b34e40807fd119ee7ccb278320f289bd0582219192dd7e19d6cf4be1c0d6514512b9424a3d9df165a6d1bfcb2339f02e18333d5d2ece3185d79)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/data-papers
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-25T14:03:26.193Z',mode:absolute,to:'2020-02-25T14:09:26.193Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-25T14:03:26.193Z',mode:absolute,to:'2020-02-25T14:09:26.193Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@dnoesgaard could you take care of this issue?

**Comment by dnoesgaard** [comment]
Yes, thanks, @ManonGros.

**Comment by akristensen** [comment]
Updated Oct 2020
