### ISSUE TITLE
Licenses, APC, metrics

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2444]
**Licenses, APC, metrics**

I suggest we keep these key parameters for the data journals we list, and update them once a year. I think it's time for the next update.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/dd8c57ca1a0c5f0ddeb8171a247fe353:180afdc4d9b9181c0752cdc92994fa4ccf5d8db3934a50f0b4994b0f1c26de3e8127d49357c5615d702327324504e665f83ab03242938d66ec4e8297b536203b)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/data-papers
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-25T14:04:55.736Z',mode:absolute,to:'2020-02-25T14:10:55.736Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-25T14:04:55.736Z',mode:absolute,to:'2020-02-25T14:10:55.736Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by akristensen** [comment]
last update October 2020
