### ISSUE TITLE
Get rid of Google 3rd party scripts

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2446]
**Get rid of Google 3rd party scripts**

According to this tool `https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fwww.gbif.org` there are several google scripts embedded on yourr website.
Is google analyctis really needed? If yes, according to GDPR it has to be opt-in.
Better: Install a local instance of matomo.
Please install fonts locally as well or delete.
thanks.

G is evil.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b82abf39bad6050d6b43a0824660f270:5460af7f3586a7e5bcc4a8a011d5e76023c94098d767109397263c0715e88cec81c37ee5230716ae1849cea088782ba3e21e0be3f5e4d4d05c4303572c6dc833)
System: Firefox 68.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/map?taxon_key=5959233
Window size: width 1000 - height 597
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-26T03:19:15.609Z',mode:absolute,to:'2020-02-26T03:25:15.609Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-26T03:19:15.609Z',mode:absolute,to:'2020-02-26T03:25:15.609Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@kcopas let me know if you believe we should act on this suggestion
