### ISSUE TITLE
"occurrences with images"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2447]
**&quot;occurrences with images&quot;**

I can neither scroll through the images any more on the overview screen nor leaf through the records after I have opened one

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0f750ea8232b51b3f16cc57cc14dca91:5e59bd991e0a390a9ba184676b41043ba08256ccc02997ec6fb59065185e66b31579e4c88d2206dfbac5773a021a18a50a99eb6fcfaee8273c7df5e5ba6c7d6e)
System: Chrome 79.0.3945 / Windows 7.0.0
Referer: https://www.gbif.org/species/3575042
Window size: width 1680 - height 947
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-26T10:42:59.356Z',mode:absolute,to:'2020-02-26T10:48:59.356Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-26T10:42:59.356Z',mode:absolute,to:'2020-02-26T10:48:59.356Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The behaviour has not changed, but on species pages with less than 20 images (like the one in case), all the images are shown and the link to the gallery not present. This is not ideal as not all users can scroll horizontally. So effectively only 5 or so images can be seen, the remaining is lost.

closed by https://github.com/gbif/portal16/commit/62c858513c674137c1efc669bc6c1548dc091ffb
