### ISSUE TITLE
BID datasets from Togo using projectID in title, not field

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#245]
**BID datasets from Togo using projectID in title, not field**

I can see that more data is coming in from the Togolese BID activities, but because they&#39;re using the projectIDs in the title rather than in the appropriate field, the datasets are not linking automatically to the project page. 

I&#39;ve raised this before—I think maybe even directly with Pierre—but they keep on coming in this way:
http://doi.org/10.15468/4g7knn
http://doi.org/10.15468/njmrjb
(plus four more datasets pre-registered as metadata-only)

-----
fbitem-ed794f3b0ea8841f22f95477b9ab9fdcfee2926f
Reported by: @kcopas
System: Safari 10.1.1 / Mac OS X 10.12.5
Referer: https://demo.gbif.org/project/82693/strengthening-the-biodiversity-stakeholders-network-in-togo
Window size: width 1203 - height 749
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-12T10:17:01.622Z',mode:absolute,to:'2017-07-12T10:23:01.622Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-12T10:17:01.622Z',mode:absolute,to:'2017-07-12T10:23:01.622Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
Thanks @kcopas, I just sent email reminders to the publishers of http://doi.org/10.15468/4g7knn and 
http://doi.org/10.15468/njmrjb urging them to fillin in the projectID properly. I copied BID and Helpdesk on my email, which can now serve as a template for communicating the same problem with other publishers.

**Comment by kcopas** [comment]
Another new dataset—https://doi.org/10.15468/uochb8—with the same dang problem. The message is not getting across here.

I'd strongly suggest that, if we can get engaged, we encourage edits to the dataset titles so that they use sensible words and syntax, not filenames, c.f. https://www.gbif.org/project/82693/strengthening-the-biodiversity-stakeholders-network-in-togo#datasets

**Comment by ahahn-gbif** [comment]
This kind of issue is usually handled through the BID helpdesk. Could we rather route them there than having a parallel activity logging line in GitHub? BID@gbif.org

**Comment by kcopas** [comment]
Yes, of course. 

Please note that I did try to keep it simple by tagging an existing issue!

**Comment by MattBlissett** [comment]
@melianieraymond / @MBLaursen
Since I'm sitting with her – Marie-Elise says to CC GBIF France when contacting Togo, and they will help if needed.

All the datasets published on the Togo IPT need the project id fixing: http://ipt-togo.gbif.fr/

**Comment by ManonGros** [comment]
Except for [this dataset](https://www.gbif.org/dataset/c1fde599-9bc7-426c-8e4b-fa3941ec784b), which is not indexed, the other issues have been solved.

**Comment by MattBlissett** [comment]
That particular dataset has a project id set in the IPT, but the Darwin Core Archive is invalid, so ingestion is aborted before the metadata is read from the archive.

The problem is no ids on the records.

**Comment by ManonGros** [comment]
The publishers have corrected the issues with this dataset now.
