### ISSUE TITLE
Possible to have other projections on map interface?

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#2456]
It would be very useful if the main occurrence map (i.e. https://www.gbif.org/occurrence/map?dataset_key=2b52369a-7fe0-4d28-b88c-c882c0ce71d8)  had the same projection control options as the occurrence maps which appear on the dataset pages (e.g. globe icon in bottom right of map on https://www.gbif.org/dataset/8287097d-cec6-4103-b23e-fb5374b1ee06).

**Comment by MattBlissett** [comment]
Hi Rukaya,

Thanks for the feedback.  What projections did you have in mind?

It currently uses Plate Carrée. Adding Mercator is easier than the polar projections, due to compromises made for the fast search index.

Also, is this for browsing on GBIF.org, or to embed the map in a different website?

Thanks

**Comment by rukayaj** [comment]
Hi Matt, 

Thanks for the fast response. 

We would like the arctic projection in particular, but I was thinking it would make sense if all 4 of the projections available on the dataset page map (i.e. Arctic, Plate Carrée, Mercator, Antarctic) were available. This is just for browsing on GBIF.org, not for embedding. 

If polar projections are a problem then I'll pass the message on to the researchers we have asking for it.

**Comment by MattBlissett** [comment]
Realistically, ad-hoc search in polar projections aren't something we're likely to implement this year. 

The new spatial index (and the old one) can summarize by rectangles in Plate Carrée (WGS84) projection.  Those values are what's currently shown.

If those values are stretched and squeezed to fit a polar projection, the resulting map is misleading.  It's possible to reproject the tiles client-side (like [this](https://openlayers.org/en/latest/examples/reprojection.html) but I think it leads to the same possible misinterpretation.

**Comment by rukayaj** [comment]
https://twitter.com/timrobertson100/status/1539585887520137217 Thanks guys! i see the search option is removed, but it is really nice to be able to see our arctic data in a projection which makes sense!
