### ISSUE TITLE
Incorrect author for Pseudodictyophimus gracilipes

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#2457]
One of our taxonomists has issued a correction to a record in WoRMS http://www.marinespecies.org/aphia.php?p=taxdetails&id=493570 -  the author for Pseudodictyophimus gracilipes has changed from Caulet, 1979 to Bailey, 1856. 

On GBIF the author is still wrong, see https://www.gbif.org/species/5955916. I see the source is Catalogue of Life, and there's also WoRMS listed as a source for https://www.gbif.org/species/154608683 with the incorrect author. 

Is it possible to get this correction reflected in GBIF?

**Comment by jhnwllr** [comment]
author is Bailey, 1856 on CoL, so should be fine for next backbone...
 https://www.catalogueoflife.org/data/taxon/856PM

**Comment by ManonGros** [comment]
Solved in the new backbone taxonomy.
