### ISSUE TITLE
Problem with scientific names in new dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2459]
**Problem with scientific names in new dataset**

Many of the scientific names are showing up as four-letter codes even though the genus and specific epithet entries appear to be correct, so matching to higher rank. Seem a fairly straightforward error to fix.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a724b7f66a812539714a3c2e31a45465:2465a85bd43f783275527c56c0d3f4a1b2998a660abbbc96dc232ca7bee61a68d80a1cacf363a949ebec5972579fdd3c6edda2781dcbf7f562c029341198d3c0)
System: Chrome 80.0.3987 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/d7b80380-1156-4d50-a261-c5b1ac1ea59a
Window size: width 1293 - height 605
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-01T08:04:06.732Z',mode:absolute,to:'2020-03-01T08:10:06.732Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-01T08:04:06.732Z',mode:absolute,to:'2020-03-01T08:10:06.732Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thanks @timhirsch  - It is probably correctly interpreted. But the website prioritise showing the verbatim name. Arguments could be made both ways. @thomasstjerne has strong opinions on this :)

E.g. https://www.gbif.org/occurrence/2571459868
Shows the verbatim name as a headline.
Shows the interpreted name below
And shows a label stating that it was matched to a higher rank.

**Comment by timhirsch** [comment]
Sorry @MortenHofft I meant easy to fix at publisher end - no doubt we are correctly representing what the verbatim data is showing, but it’s a shame to be losing the species information apparently available from this dataset. Maybe one for @ManonGros to feed back to publisher with suggestions on how to fix?

**Comment by albenson-usgs** [comment]
@ManonGros let me know if you don't hear back from NEON Biorepository (or if you want me to reach out).

**Comment by ManonGros** [comment]
Contacted by email.

**Comment by ManonGros** [comment]
The publishers have updated their dataset with the full scientific names. Everything looks good now.
