### ISSUE TITLE
Another orphaned U.S. dataset?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#246]
**Another orphaned U.S. dataset?**

This mosquito dataset looks to be an (older?) subset of a larger collection of occurrences (&quot;Vector-Borne Disease Pathogen Observations&quot;) from the Smithsonian&#39;s Walter Reed Biosystematics Unit, available [here](https://www.arcgis.com/home/item.html?id=d55506f716fc4128958ca94852e9dd76) among other places.

DiGIR installation appears to have failed consistently for a very long time.

-----
fbitem-dataset88e38292-f762-11e1-a439-00145eb45e9a
Reported by: @kcopas
System: Safari 10.1.1 / Mac OS X 10.12.5
Referer: https://demo.gbif.org/dataset/88e38292-f762-11e1-a439-00145eb45e9a
Window size: width 1203 - height 749
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-12T12:22:20.012Z',mode:absolute,to:'2017-07-12T12:28:20.012Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-12T12:22:20.012Z',mode:absolute,to:'2017-07-12T12:28:20.012Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
Thanks @kcopas @ahahn-gbif 

I can confirm that this dataset is in the list of potential [US orphans](https://github.com/kbraak/watchdog/blob/master/lists/orphans/UnitedStates.tsv).

Unfortunately as @cgendreau can attest, a couple of bugs in our crawling infrastructure ([bug#3](https://github.com/gbif/crawler/issues/3) & [bug#4](https://github.com/gbif/crawler/issues/4)) prevent GBIF from being able to crawl approximately 10% of all registered datasets. Until these bugs get fixed, we aren't able to reliably trust the crawl history as an indication of whether the dataset is online or offline.

**Comment by MattBlissett** [comment]
This has been rescued.
