### ISSUE TITLE
Download landing page: isNotNull predicates dropped in "rerun query" link

### ISSUE THREAD

**Issue by nickynicolson** [gbif/portal-feedback#2463]
It is really useful to have access to predicates such as `isNotNull` when constructing download requests by POSTing to the download API (as documented in https://www.gbif.org/developer/occurrence#predicates)

An example here uses `isNotNull` on the `recordedBy`, `recordNumber` and `eventDate` fields:
https://www.gbif.org/occurrence/download/0007179-200221144449610
... but the link to rerun the query on the portal interface (https://www.gbif.org/occurrence/search?basis_of_record=PRESERVED_SPECIMEN&taxon_key=7707728) silently drops these - I suppose as `isNotNull` is not supported in the web interface? In this case there is a big difference in terms of record counts (27 million in download vs 70 million on website).

I suppose it would be challenging to support all logic that could be constructed with complex predicates - but if this is intentional, would it be worth considering showing a warning here?

(Also is web interface support for simple `isNotNull` planned?)

**Comment by thomasstjerne** [comment]
The portal is only supposed to show the "rerun query" link for simple downloads, which can actually be be rerun on the portal - so I will make sure that link is not displayed for isNotNull predicates.
There are several other predicates (OR and NOT) that cannot be reproduced with GET params.

**Comment by MattBlissett** [comment]
Thanks for reporting this.

> (Also is web interface support for simple isNotNull planned?)

The website uses the public APIs (for occurrence, names, registry).  The current (V1) occurrence API doesn't support isNotNull, so it's something that would need to be in a V2 API.  There are a few things planned in the medium-to-long term which would need a new API version, but we haven't yet planned how to get to that point.
