### ISSUE TITLE
DOIs as part of URL

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2466]
**DOIs as part of URL**

I was working with some references and noticed that journals include the paper's DOI into the paper's URL, see e.g. `https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.1303.`

Does this approach bring any citation benefits for DOI tracking? How would CrossRef etc. would react to URLs containing the DOIs?

Would it work for download pages?

Copy-pasting a URL is natural instinct for many, while following and remembering specific citation rules which are not native to journals world is a burden.

Just a thought.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/a5545eb64981f28682fb107362872aab:1aeaf6132e092414c34f5b5d6694f620d63b97160e8bd8d45705489e7fb6fbf435479f0db1452267f01ec46fc696f80b90f92eeca2186641e1e90aaaa43ba7c4)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/3b301884-51b9-443f-b63c-47feeccfb89f
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-04T16:53:55.907Z',mode:absolute,to:'2020-03-04T16:59:55.907Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-04T16:53:55.907Z',mode:absolute,to:'2020-03-04T16:59:55.907Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
@dnoesgaard some crazy evening thoughts

**Comment by dnoesgaard** [comment]
You mean, would it make a difference if we included DOIs in the URLs of download and dataset pages?

I don't think so. While we do see a (very) few citations of such URLs, the vast majority are way more generic, e.g. just "GBIF" or "GBIF.org".

Also, including DOIs in URLs and having people cite them wouldn't improve uptake of machine-readable links in Crossref metadata and event data. Only real DOIs does that. In other words, we'd still rely on Google Scholar, etc. to catch them.

**Comment by dschigel** [comment]
Thanks
