### ISSUE TITLE
Do commercial databases exist for storing terrestrial biodiversity data?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2467]
**Do commercial databases exist for storing terrestrial biodiversity data?**

Hello, 

I work for a large conservation NGO that collects a lot of biodiversity data using multiple surveys (e.g. pitfall, cameras, audio sensor, spotlight transects). We're investigating off-the-shelf commercial databases for storing our data. Do you know if any exist? 

Thank you,
Liana
liana.joseph@australianwildlife.org

Best wishes,
Liana

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/439a2f04421f0152891ad7a9ba9edb9b:d431980898f4344c59db69a753c5b8c1c643bf74c2988405af798c10ce5d1ae15555f664bc31e1bc2b9595a3a1167a7bb1fb260fa7899096d26251f22fb17817)
System: Chrome 79.0.3945 / Windows 10.0.0
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-05T02:49:43.082Z',mode:absolute,to:'2020-03-05T02:55:43.082Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-05T02:49:43.082Z',mode:absolute,to:'2020-03-05T02:55:43.082Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
I suggested to post the question on https://discourse.gbif.org and sent [the blogpost about tools compatible with GBIF](https://data-blog.gbif.org/post/installations-and-hosting-solutions-explained/).
