### ISSUE TITLE
Lat/lon transposed in records of mes_plantae_bimr1

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2469]
**Lat/lon transposed in records of mes_plantae_bimr1**

Some records in mes_plantae_bimr1 (`https://www.gbif.org/dataset/03232707-6550-4524-a935-bef9b3e89092)` are appearing in Saudi Arabia. This is most likely due to transposition of latitude and longitude when the data were uploaded. Comparison with textual locality information confirms this for one occurrence: `https://www.gbif.org/occurrence/2382892024.` The originator of the dataset has also been informed by email.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d0409209208ad82917a829f1e4b20dc6:088941b028dd88ecacd969fb32a14f15e9872a6c02d7b03351f2bc716faf234c74dab93075a9c5f6709ac974a966ab1119df735604a4b236473903d38b77ddb3)
System: Edge 18.18362.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/03232707-6550-4524-a935-bef9b3e89092
Window size: width 1366 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-05T18:37:14.157Z',mode:absolute,to:'2020-03-05T18:43:14.157Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-05T18:37:14.157Z',mode:absolute,to:'2020-03-05T18:43:14.157Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Related to https://github.com/gbif/portal-feedback/issues/2315
