### ISSUE TITLE
additional occurrence images missing from gallery

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#247]
**additional occurrence images missing from gallery**

Hi.  I didn&#39;t know how to classify this comment.

I don&#39;t think it&#39;s a bug, but when you search occurences the image gallery is not showing all images. 
It just shows one image per occurrence (so, if one occurrence has several images, only one of them is shown in the gallery). Example:
https://demo.gbif.org/occurrence/gallery?catalog_number=69652&amp;publishing_org=def87a70-0837-11d9-acb2-b8a03c50a862&amp;taxon_key=3096621

I think this is a bad idea.  For accounting the number of occurrences it is better to use the table tab.

I think if a user is looking for images, it is better to show all of them (otherwise the user could miss a good macro or microphotography of flowers, seeds, spores ...).

When a close-up image is hidden from gallery, there are many chances that final users will never find it: they would need to first click on the &quot;default&quot; image so they see the occurrence page, where all images will be shown.

But if the default image is a general view of the specimen, and the user is looking for close-up images, then I am pretty sure this user will never click on that default image.

BTW.  Can I know how GBIF decides which one of the images available (for the same occurrence) will be used for the gallery?

-----
fbitem-90ca04c707cd953f778e8789ed7ec98e67b20053
Reported by: sant.herbarium@gmail.com
System: Chrome 49.0.2623 / Windows XP 0.0.0
Referer: https://demo.gbif.org/occurrence/gallery?catalog_number=69652&publishing_org=def87a70-0837-11d9-acb2-b8a03c50a862&taxon_key=3096621
Window size: width 1008 - height 550
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-13T08:39:08.959Z',mode:absolute,to:'2017-07-13T08:45:08.959Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-13T08:39:08.959Z',mode:absolute,to:'2017-07-13T08:45:08.959Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dgasl** [comment]
For some reason, the example link above was wrong (I think the "&" was urlencoded).

Here is the good one:
https://demo.gbif.org/occurrence/gallery?catalog_number=69652&publishing_org=def87a70-0837-11d9-acb2-b8a03c50a862

**Comment by MortenHofft** [comment]
Thanks
We don't show all because some occurrences have hundreds of images and we figured showing all, even just 10 for each wouldn't give a better overview of the data. But we have talked about displaying info that there are more images available. The image shown is the first on in the API. I suspect that reflects the first one listed in the published archive.

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/436
