### ISSUE TITLE
Picoides dorsalis data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2471]
**Picoides dorsalis data**

Hello I was wondering if there is an ArcGIS compatible file available for download which contains the abundance of Picoides dorsalis, the american three toed woodpecker.
Thank you

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c559df6c21de40d0d89a8dd163f2ca52:9f38ebb5d4033a55cc4954857708211b369db2a732d3c97b77b5ab557e81382b14eb7c53707131310c6574751c1a867a4a85abf27202d5b52415881061715b79)
System: Chrome 79.0.3945 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?contentType=dataUse
Window size: width 1920 - height 969
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-06T23:00:57.899Z',mode:absolute,to:'2020-03-06T23:06:57.899Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-06T23:00:57.899Z',mode:absolute,to:'2020-03-06T23:06:57.899Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.

**Comment by MortenHofft** [comment]
See also https://github.com/gbif/portal16/issues/589
