### ISSUE TITLE
Map missing on main dataset page?

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#2474]
This dataset https://www.gbif.org/dataset/2b52369a-7fe0-4d28-b88c-c882c0ce71d8 is a sampling event dataset with various coordinates, but no map is showing up on the main page of the dataset. Any ideas why?

A very similar dataset is this one https://www.gbif.org/dataset/8287097d-cec6-4103-b23e-fb5374b1ee06 which does have a map. The only difference I can see is that it only has 1 location, whereas the other has multiple. However, this German dataset https://www.gbif.org/dataset/72006b62-f762-11e1-a439-00145eb45e9a has multiple points and has a map.

**Comment by MattBlissett** [comment]
![image](https://user-images.githubusercontent.com/583320/76213150-598f9b00-620a-11ea-8e94-081065e0acc7.png)

I see a map -- could you check if perhaps your web browser has a plugin to block adverts/trackers etc, and if that is overblocking?

**Comment by rukayaj** [comment]
How weird, it is there now. No didn't have any plugins blocking it, it just suddenly appeared. Thanks anyway Matt.
