### ISSUE TITLE
relink old document resouce to external link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2476]
**relink old document resouce to external link**

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/9e771cd73bb00ffde455f10b2d239d89:52893fa3ab1937dab944adf3309a9cb8a456e19f8775c634e7b6480a0a7a0c94858fc9631ee67462cdc409a0047f52bace659fe38417cdc5e9a122136115495a)
System: Chrome 80.0.3987 / Mac OS X 10.15.3
Referer: https://www.gbif.org/resource/80974
Window size: width 2532 - height 1062
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-09T15:44:34.279Z',mode:absolute,to:'2020-03-09T15:50:34.279Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-09T15:44:34.279Z',mode:absolute,to:'2020-03-09T15:50:34.279Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
https://hdl.handle.net/10568/72785

**Comment by dnoesgaard** [comment]
Resource resurrected. Could someone please alias

/resource/80974 -> /document/80974/

**Comment by kcopas** [comment]
Do we want to assign this a doi and deposit the pdf on Zenodo?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dnoesgaard** [comment]
It's already got a PID (handle) so I don't think that's necessary...

**Comment by MortenHofft** [comment]
Instead of adding a redirect I changed to backend to accept resource links and just redirect them to their appropriate counterpart (in this case document).
