### ISSUE TITLE
missing/wrong coordinates

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#248]
**missing/wrong coordinates**

This otherwise interesting dataset lacks coordinates, or the supplied coordinates are in an unknown format and as such not being interpreted correctly.

-----
fbitem-dataset914c3b86-f2a1-4d5e-b343-b2597b9d4542
Reported by: @dnoesgaard
System: Chrome 59.0.3071 / Mac OS X 10.12.5
Referer: https://demo.gbif.org/dataset/914c3b86-f2a1-4d5e-b343-b2597b9d4542
Window size: width 1831 - height 956
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-13T08:58:00.030Z',mode:absolute,to:'2017-07-13T09:04:00.030Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-13T08:58:00.030Z',mode:absolute,to:'2017-07-13T09:04:00.030Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
Thanks @dnoesgaard, I have contacted the publisher asking them to update their dataset with a fix.
