### ISSUE TITLE
additional filters for literature

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2481]
**additional filters for literature**

Could we add filters (faceted) for fields

source (translation: "Journal")
publisher (translation: "Journal publisher)

Thanks!

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/6ec1b028f63d0625015680417f79534b:1c07653ca17380a32e562864f58831afa8b8abbd564ef302e27f5530f8ca3b7922908904e33824b17485f08599b69796b79806a5726fe385315dc58a8e99d548)
System: Chrome 80.0.3987 / Mac OS X 10.15.3
Referer: https://www.gbif.org/resource/search?contentType=literature&literatureType=journal&relevance=GBIF_USED&peerReview=true
Window size: width 2560 - height 1226
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-11T10:58:45.857Z',mode:absolute,to:'2020-03-11T11:04:45.857Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-11T10:58:45.857Z',mode:absolute,to:'2020-03-11T11:04:45.857Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
If it is for internal use this is already available in the es index:
http://cms-search.gbif.org:9200/_search?q=contentType:literature%20AND%20publisher:Wiley

**Comment by MortenHofft** [comment]
We generally do not add facets for things that are free text fields, but I have now done so. It might be worth cleaning them up if you have the option to do so. Below is an excerpt of the facets including actual casing and spelling mistakes: 

* article
* 10 th Worl Bamboo Congress,
* Electronic Article
* IUCN Red List of Threatened Species Assessment
* Letter
* Newspaper Article
* dataset
* homework

There is no suggest endpoint, so search is free text is hoping for the best

**Comment by dnoesgaard** [comment]
Hey, thanks for this.

However, I think you might have used the wrong field: `sourceType` 

Should have been `source`

**Comment by MortenHofft** [comment]
Oh, I couldn't see source in the data, so i figured it was sourcetype. I must have misspelled in my search. Thanks
