### ISSUE TITLE
Genus Polyommatus presented wrongly by GBIF as Polyomamtus.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2484]
**Genus Polyommatus presented wrongly by GBIF as Polyomamtus.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/00c847cf21daac7c8b8ed914412c0a52:eb383698d6162792d4fc2d2d5e13fc95af7a1241fb33c1c876ce3126648de86098d09fe5dd779787f771df00258e0bb3972ebb3e8271f21d442f5ae842eb3b4d)
System: Firefox 74.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/856681215
Window size: width 1920 - height 944
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-17T11:27:42.520Z',mode:absolute,to:'2020-03-17T11:33:42.520Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-17T11:27:42.520Z',mode:absolute,to:'2020-03-17T11:33:42.520Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO
datasetKey: d5e61920-9863-4fc3-8e5a-80f0c7bfe640
publishingOrgKey: 3ead5cf3-2840-482e-bbd9-76380825be63

**Comment by ManonGros** [comment]
Dataset was deleted and replaced by a larger one.
I assume the records concerned are the following: https://www.gbif.org/occurrence/search?q=Polyomamtus&dataset_key=a307e4d7-1de2-4adc-95d5-a0a8d5f57236
Original name is "Polyommatus elvira (Eversmann, 1854)" but is interpreted as "Polyomamtus elvira (Eversmann, 1854)", which is an accepted species in the GBIF backbone taxonomy: https://www.gbif.org/species/9115120

The name comes from the GBIF Type Specimen Names checklist: https://www.gbif.org/dataset/6cfd67d6-4f9b-400b-8549-1933ac27936f, from a Paralectotype of the  Natural History Museum (London) Collection Specimens (https://www.gbif.org/dataset/7e380070-f762-11e1-a439-00145eb45e9a). Could they have misspelled it?

**Comment by ManonGros** [comment]
I contacted NHM via their feedback system: https://data.nhm.ac.uk/dataset/56e711e6-c847-4f99-915a-6894bb5c5dea/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb/record/848055

**Comment by ManonGros** [comment]
The Lepidoptera curator replied that the name is in fact Polyommatus elvira (Eversmann, 1854) and that the corrections will appear shortly on their portal (and therefore I assume on GBIF.org).

**Comment by ahahn-gbif** [comment]
This issue can be closed now. The GBIF Type Specimen Names checklist is no longer used in backbone generation. The misspelled name is still showing within that checklist, but is not used in any way outside of that context (https://www.gbif.org/species/search?q=Polyomamtus&advanced=1)
