### ISSUE TITLE
The longitude seems to be wrong. The record is informed to be in Germany, but the latitude corresponds to Russia.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2489]
**The longitude seems to be wrong. The record is informed to be in Germany, but the latitude corresponds to Russia.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/91be1e644526f0e8c824a2f728de9191:7dc1a2a3ba7fa26f556205675bd656d4151010dc368213db4cbe46c243b4158395045d5934af1b40d4a55f71af4b64f7edbef4ee4e2aa6b0d2d3192859dd9b45)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1270704609
Window size: width 1366 - height 625
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-20T14:52:44.096Z',mode:absolute,to:'2020-03-20T14:58:44.096Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-20T14:52:44.096Z',mode:absolute,to:'2020-03-20T14:58:44.096Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO
datasetKey: 7b84c0a2-f762-11e1-a439-00145eb45e9a
publishingOrgKey: c76cf030-2a95-11da-9cc1-b8a03c50a862

**Comment by ManonGros** [comment]
Publisher contacted by email.
