### ISSUE TITLE
This plant is Sesleria autumnalis (Scop.) F.W. Schultz not Sesleria argentea  (Savi) Savi

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2496]
**This plant is Sesleria autumnalis (Scop.) F.W. Schultz not Sesleria argentea (Savi) Savi**

Sesleria autumnalis belongs to the same sect. Argenteae to which also Sesleria argentea is included, but it distinguishes especially for slender and longer panicle, flabby at maturity, 3-5(7) x 45-100 mm again 6-10 x 35-80 mm always straight.
Western Balkan Peninsula, Italy.

Reference
Deyl, M. 1980: Sesleria Scop. In: Tutin, T.G. Heywood, V.H. Burges, N.A. Valentine, D.H. Walters, S.M. & Webb, D.A. (Eds.) Flora Europaea 5: 173-177. Cambridge.
Pignatti, S. 1982: Flora d’Italia, vol. 3 (Sesleria, pag. 505 - 509). Edagricole.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e7c2b2a61208a895ca5a55ca814fbc2a:5e6e5b7f77bb2b45e47d901e5f3cbdf47143498f1f2fab970e7047eaf347f0988c13aab5141b716fb2ff32f1e737461c56a8fb69143d1ebfc1c9ce7953a74697)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/occurrence/gallery?taxon_key=4119703
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-22T17:27:43.090Z',mode:absolute,to:'2020-03-22T17:33:43.090Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-22T17:27:43.090Z',mode:absolute,to:'2020-03-22T17:33:43.090Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
I am not sure if the issue refers to one of the records (and if so which one?) or the entire taxonomy.
That being said, the species mentioned `Sesleria autumnalis (Scop.) F.W. Schultz`, is definitely not in the backbone taxonomy: https://www.gbif.org/species/search?q=Sesleria%20autumnalis%20(Scop.)%20F.W.%20Schultz

**Comment by ahahn-gbif** [comment]
CoL: https://www.catalogueoflife.org/data/taxon/4WZRS (Sesleria autumnalis (Scop.) F.W.Schultz)
GBIF: https://www.gbif.org/species/4119674

**Comment by ahahn-gbif** [comment]
Given the taxon is now available in the backbone, the remaining issue appears to be about misidentification of the occurrences from the original reference link

**Comment by jhnwllr** [comment]
I don't think this is actionable with the current information given in the issue. I think we should close or ask for clarification.
