### ISSUE TITLE
Author citation error

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2498]
**Author citation error**

The authorship of Evolvulus alsinoides and E. nummularius should be (L.) L.  The basioyms are Convolvulus alsinoides and Convolvulus nummularius, respectivley. See Tropicos.org and IPNI

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/85433651516f09f88f3e0ec646ec7bf8:b93198d1c850ef8b841199d950718fb359f819956001e20d6a0a05e299a6e088ce5d35df767bf6a557b9b2df163162da533715f4cf35cfd6f470cd82cf82b6a9)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/map?taxon_key=2928673
Window size: width 1229 - height 603
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-22T21:40:34.313Z',mode:absolute,to:'2020-03-22T21:46:34.313Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-22T21:40:34.313Z',mode:absolute,to:'2020-03-22T21:46:34.313Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by jhnwllr** [comment]
Both species  have **(L.) L.** authorship

https://www.gbif.org/species/2928673 Evolvulus alsinoides (L.) L.
https://www.gbif.org/species/2928680 Evolvulus nummularius (L.) L.
