### ISSUE TITLE
Clicking on "more" makes data content disappear

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2509]
**Clicking on &quot;more&quot; makes data content disappear**

I tried to display the the whole text in the `Georeference remarks` field but when I clicked on `more`, the content disappear all together.

<img width="980" alt="Screenshot 2020-03-24 at 09 13 04" src="https://user-images.githubusercontent.com/7677271/77402961-c466d780-6daf-11ea-96a2-676b28896284.png">
After clicking:
<img width="985" alt="Screenshot 2020-03-24 at 09 13 32" src="https://user-images.githubusercontent.com/7677271/77402979-cc267c00-6daf-11ea-8a07-7cfb6e2c58bc.png">

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/79e5bde29843a118a46edd035fd96cfc:deacefaecf4b05e5d06e797f15d9e20a26ab3b6354fb891523500c19685aed08488fdd10e9c22838a82f650e383d2dc96eba35ff327b981470df49472656f348)
System: Safari 13.0.5 / Mac OS X 10.15.3
Referer: https://www.gbif.org/occurrence/1932813348
Window size: width 1283 - height 896
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-24T08:07:39.063Z',mode:absolute,to:'2020-03-24T08:13:39.063Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-24T08:07:39.063Z',mode:absolute,to:'2020-03-24T08:13:39.063Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO
datasetKey: 6080b6cc-1c24-41ff-ad7f-0ebe7b56f311
publishingOrgKey: 3c6ad080-bdbe-11da-ac59-b8a03c50a862

**Comment by thomasstjerne** [comment]
https://code.angularjs.org/1.5.8/docs/error/$parse/lexerr?p0=Unterminated%20quote&p1=s%20482-483%20%5B%27%5D&p2=%27Original%20georeference%20taken%20from%20locality%20ID%236034.%20Original%20notes:%20Map%20of%20Clear%20Creek%20showing%20spring%20locations%20is%20provided%20in%20the%20%26quot;Clear%20Creek%20Gambusia%20Recovery%20Plan%26quot;.%20Point%20is%20placed%20in%20area%20of%20greatest%20density%20of%20springs%20and%20extent%20covers%20two%20more%20distant%20springs.%20This%20record%20was%20reviewed%20during%20a%20meeting%20at%20which%20Gary%20Garrett%20was%20present.%20He%20was%20able%20to%20provide%20more%20detailed%20information%20regarding%20locality%20description.%20Moved%20coordinates%20as%20per%20Gary%27s%20instructions.%0A
