### ISSUE TITLE
Error when clicking download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#251]
**Error when clicking download**

When hitting download an orange box appears saying unable to complete download.

This is a small polygon search by Donald H.

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
Reported by: @timrobertson100
System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/occurrence/download?has_coordinate=true&has_geospatial_issue=false&publishing_org=47e00926-5a2f-44e8-8509-139a689c8b4d&taxon_key=3073&geometry=POLYGON%20((149.0796661376953%20-35.28828272902797,%20149.0796661376953%20-35.23558062543034,%20149.14077758789062%20-35.23558062543034,%20149.14077758789062%20-35.28828272902797,%20149.0796661376953%20-35.28828272902797))
Window size: width 1389 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-13T10:32:22.108Z',mode:absolute,to:'2017-07-13T10:38:22.108Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-13T10:32:22.108Z',mode:absolute,to:'2017-07-13T10:38:22.108Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
Note this fails in WWW too:

http://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&publishing_org=47e00926-5a2f-44e8-8509-139a689c8b4d&taxon_key=3073&geometry=POLYGON%20((149.0796661376953%20-35.28828272902797,%20149.0796661376953%20-35.23558062543034,%20149.14077758789062%20-35.23558062543034,%20149.14077758789062%20-35.28828272902797,%20149.0796661376953%20-35.28828272902797))

@fmendezh - any idea what is wrong with this polygon?

**Comment by MattBlissett** [comment]
http://api.gbif.org/v1/occurrence/search?has_coordinate=true&has_geospatial_issue=false&publishing_org=47e00926-5a2f-44e8-8509-139a689c8b4d&taxon_key=3073&geometry=POLYGON%20((149.0796661376953%20-35.28828272902797,%20149.0796661376953%20-35.23558062543034,%20149.14077758789062%20-35.23558062543034,%20149.14077758789062%20-35.28828272902797,%20149.0796661376953%20-35.28828272902797))

works for me though.

**Comment by MattBlissett** [comment]
http://www.gbif.org/occurrence/download/0005896-170627171947987 may be a correct download.

The demo site wraps the geometry parameter in an extra POLYGON(( )) when a download is requested.

I don't know why the www site says the parameter is invalid.

**Comment by MattBlissett** [comment]
For Morten/Thomas:

Request for https://demo.gbif.org/api/user/download?format=DWCA&geometry=POLYGON+((149.0796661376953+-35.28828272902797,+149.0796661376953+-35.23558062543034,+149.14077758789062+-35.23558062543034,+149.14077758789062+-35.28828272902797,+149.0796661376953+-35.28828272902797))&has_coordinate=true&has_geospatial_issue=false&locale=en&publishing_org=47e00926-5a2f-44e8-8509-139a689c8b4d&taxon_key=3073 

Gave: "Invalid simple WKT: POLYGON((POLYGON ((149.0796661376953 -35.28828272902797, 149.0796661376953 -35.23558062543034, 149.14077758789062 -35.23558062543034, 149.14077758789062 -35.28828272902797, 149.0796661376953 -35.28828272902797))))"

**Comment by MortenHofft** [comment]
This is an API issue. Or rather Fede and I agreed that the API should support the same query parameter as the search API does. See issue https://github.com/gbif/occurrence/issues/8

Tim and I talked a couple of weeks ago about this issue. I suggested it should be considered a release blocker. I still believe it is. 

The demo site doesn't wrap the wkt. it just doesn't  send invalid wkt :)

**Comment by MortenHofft** [comment]
I just confirmed with @fmendezh, that this is still something we believe should be fixed on the API side.
