### ISSUE TITLE
Dataset citations

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2523]
**Dataset citations**

I was wondering: is there a particular reason for the citation format of different datasets to be inconsistent?
e.g. Arizona State University Biocollections (2020). Arizona State University Hasbrouck Insect Collection. Occurrence dataset `https://doi.org/10.15468/vv6k58` accessed via GBIF.org on 2020-03-25.  [Collection name, year...]
vs.
Johnson N, Cora J. C.A. Triplehorn Insect Collection (OSUC), Ohio State University. Museum of Biological Diversity, The Ohio State University. Occurrence dataset `https://doi.org/10.15468/efb17f` accessed via GBIF.org on 2020-03-25.  [Authors (of the dataset? collection code, no year...]?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c9101b53d009bc907c438cac12837692:c3d53b621b1617e79ba29010fd38cd19b0be6fcd6f92ba8fe6bfdf9b8f55cde8a7c88f358118c1109e1fa803efcb25517343cee76a088bd4c436e707d3eef464)
System: Chrome 80.0.3987 / Mac OS X 10.13.6
Referer: https://www.gbif.org/dataset/76525e81-9210-401d-a90d-5509f771c0e7
Window size: width 1319 - height 765
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-25T22:03:41.694Z',mode:absolute,to:'2020-03-25T22:09:41.694Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-25T22:03:41.694Z',mode:absolute,to:'2020-03-25T22:09:41.694Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by mike-podolskiy90** [comment]
There are rules how citations are generated:
https://github.com/gbif/registry/blob/master/docs/citations.md

Those two datasets data:
http://api.gbif.org/v1/dataset/750b7bfc-3577-4b26-8aaf-3e4be9f0d639
http://api.gbif.org/v1/dataset/84ab7b76-f762-11e1-a439-00145eb45e9a
