### ISSUE TITLE
Missing total count?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#253]
**Missing total count?**

I think this should show the total number of datasets.

-----
fbitem-29a45851c2b1c6db7cfbe5481db5e749560c4077
Reported by: @timrobertson100
System: Chrome 59.0.3071 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/installation/99552c70-f762-11e1-a439-00145eb45e9a
Window size: width 1612 - height 1025
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-17T08:26:58.820Z',mode:absolute,to:'2017-07-17T08:32:58.820Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-17T08:26:58.820Z',mode:absolute,to:'2017-07-17T08:32:58.820Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/583c9780d05a0b31d79b16753da02eb6f569fc69
