### ISSUE TITLE
Misplaced location

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#254]
**Misplaced location**

Itapetininga is a municipality far from the coastline. The coordinates provided is from a point on the Atlantic Ocean.

The coordinates of the district headquarters are:

-23.639906° / -48.159794°

Best regards!

-----
fbitem-occurrence1039640431

System: Chrome 59.0.3071 / Windows 8.1 0.0.0
Referer: https://demo.gbif.org/occurrence/1039640431
Window size: width 1852 - height 990
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-17T12:16:44.245Z',mode:absolute,to:'2017-07-17T12:22:44.245Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-17T12:16:44.245Z',mode:absolute,to:'2017-07-17T12:22:44.245Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 854cf79e-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 2e167bb0-4441-11db-9ba2-b8a03c50a862

**Comment by ahahn-gbif** [comment]
Dataset owners notified of the feedback.

**Comment by ahahn-gbif** [comment]
Data updated at origin, waiting for synch to catch up.
