### ISSUE TITLE
Queries on www do not produce same results on demo

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#256]
**Queries on www do not produce same results on demo**

http://www.gbif.org/occurrence/search?GEOMETRY=-70.878295%2B41.734429%2C-70.878295%2B41.397415%2C-70.449829%2B41.397415%2C-70.449829%2B41.734429%2C-70.878295%2B41.734429&amp;q=Clytia%2Bhaemisphaerica&amp;display=map

swapping out www to demo has to return the same result set.  These URLs are all over the place so we need to maintain backwards compatibility

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
Reported by: @timrobertson100
System: Chrome 59.0.3071 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/
Window size: width 1402 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-24T07:50:23.699Z',mode:absolute,to:'2017-07-24T07:56:23.699Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-24T07:50:23.699Z',mode:absolute,to:'2017-07-24T07:56:23.699Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
species, dataset and publisher search is using the old params. but same of the occurrence parameters have changed. This are mapped with https://github.com/gbif/portal16/commit/e532526c098103d65db11660eda4b74905dff5ec
