### ISSUE TITLE
API page has misaligned table of contents element

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#259]
**API page has misaligned table of contents element**

FF &amp; Chrome, the &quot;Content&quot; element is pushing down the rest of the page.

-----
fbitem-b1018fb447ec8b1aa84ee420b36825314783d5a9
Reported by: @MattBlissett
System: Firefox 53.0.0 / Ubuntu 0.0.0
Referer: https://demo.gbif.org/developer/occurrence
Window size: width 1912 - height 1038
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-26T12:58:58.404Z',mode:absolute,to:'2017-07-26T13:04:58.404Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-26T12:58:58.404Z',mode:absolute,to:'2017-07-26T13:04:58.404Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thanks @MattBlissett - yes it is a known issue. The developer pages need some attention.

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/434
