### ISSUE TITLE
Publishers on IPT Stats page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#260]
**Publishers on IPT Stats page**

What is the meaning of the Publishers count on the page?

-----
fbitem-7139f8609c88dfc8d6f63e185b48f05341718691
Reported by: @tucotuco
System: Chrome 58.0.3029 / Mac OS X 10.10.3
Referer: https://demo.gbif.org/ipt
Window size: width 1304 - height 621
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-27T02:02:38.253Z',mode:absolute,to:'2017-07-27T02:08:38.253Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-27T02:02:38.253Z',mode:absolute,to:'2017-07-27T02:08:38.253Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you
You are right - that number is wrong. What it was intended to mean was how many publishers are publishing using those installations, but the number isn't correct. Thanks for noticing.

**Comment by MortenHofft** [comment]
Thanks - I've removed the faulty info. It will be available (or rather removed) on next deployment. Currently the IPT stats are hard coded and updated manually. It would be nice to have it driven of a dynamic API at some point.
