### ISSUE TITLE
Download big data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2601]
**Download big data**

Good Morning,

I wonder if there is any other way to download data from the site.

At the moment I needed the bird observation data, however the zip has 32gGb and my internet does not support such long downloads.
Eventually the connection is lost and the entire process is lost.

thanks for that

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0856f95e47aea7f13a26d10fa440c062:66a3582a12345e58ffe8af03df76511f1a5499e8549b651ad604fee76caa25a178172f998d1269cf692185df11d6dda8d6baa5877efdaea0011e5928943b35c9)
System: Chrome 80.0.3987 / Windows 7.0.0
Referer: https://www.gbif.org/faq
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-30T15:02:51.820Z',mode:absolute,to:'2020-03-30T15:08:51.820Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-30T15:02:51.820Z',mode:absolute,to:'2020-03-30T15:08:51.820Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by jlegind** [comment]
user contacted.
