### ISSUE TITLE
VertNet IPT

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#261]
**VertNet IPT**

VertNet&#39;s IPT installation does not appear on the IPT stats page. What it the root cause of that and what can we do to fix it?

-----
fbitem-7139f8609c88dfc8d6f63e185b48f05341718691
Reported by: @tucotuco
System: Chrome 58.0.3029 / Mac OS X 10.10.3
Referer: https://demo.gbif.org/ipt
Window size: width 1304 - height 621
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-27T02:03:43.645Z',mode:absolute,to:'2017-07-27T02:09:43.645Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-27T02:03:43.645Z',mode:absolute,to:'2017-07-27T02:09:43.645Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
The data comes from this endpoint: https://api.gbif.org/v1/installation/location/IPT_INSTALLATION
@kbraak is this an automatic or manually build endpoint? Do you know the course of the missing installation?

**Comment by timrobertson100** [comment]
You need to add coordinates to the organisation hosting the IPT in the
registry for it to appear.

**Comment by timrobertson100** [comment]
Should be fixed.

Listed in https://api.gbif.org/v1/installation/location/IPT_INSTALLATION

I found the coordinates in the RSS feed and added then in the registry to the VertNet organization entry http://ipt.vertnet.org:8080/ipt/rss.do.  Seemingly we don't update that automagically.
