### ISSUE TITLE
Almost all of these samples are determined correctly, but should go under the general title “Sesleria alba Sibth. & Sm. ”, adding Sesleria anatolica Deyl and Sesleria pontica Deyl as synonyms.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2612]
**Almost all of these samples are determined correctly, but should go under the general title “Sesleria alba Sibth. &amp; Sm. ”, adding Sesleria anatolica Deyl and Sesleria pontica Deyl as synonyms.**

Almost all of these samples are determined correctly, but should go under the general title “Sesleria alba Sibth. & Sm. ”, adding Sesleria anatolica Deyl and Sesleria pontica Deyl as synonyms. A specimen belongs to Sesleria phleoides Steven ex Roem. & Schult. and I have sent its correction apart. Another specimen, labeled as Carex dubia, is problematic but however is not a Carex, it may be an anomalous plant of Sesleria alba.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6c3cec0bd5fa0ca3491ad1f4ef53aff0:e791a3fde1b499d0afc1dd9cec05be2f804b2cdbbfcc497a0cceab7d92d4e5190df64e6b1af02bb9a7bfd1e3b8fa42fb94beccd547fb3f658ac1abd92b6ffa88)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/occurrence/gallery?taxon_key=8090403
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-31T19:53:17.302Z',mode:absolute,to:'2020-03-31T19:59:17.302Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-31T19:53:17.302Z',mode:absolute,to:'2020-03-31T19:59:17.302Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
It seems like the backbone update fixed this issue
