### ISSUE TITLE
Yes, this is Sesleria albicans! Then it is to take aways from the page dedicated to Sesleria coerulea (L) Ard.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2619]
**Yes, this is Sesleria albicans! Then it is to take aways from the page dedicated to Sesleria coerulea (L) Ard.**

Yes, this is Sesleria albicans! Then it is to take aways from the page dedicated to Sesleria coerulea (L) Ard.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4cfa270db2cf2e25c7952d8896f26b76:3057890343ba337a8d530707885f70d920719ce64cfb2453c50404ca6cbdbfc6fd0759a1c7cc56d9b0bb04d5d07c5bb32e143b7b4dc29aa7ba8d626c79369741)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/occurrence/1341612247
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-01T09:49:33.237Z',mode:absolute,to:'2020-04-01T09:55:33.237Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-01T09:49:33.237Z',mode:absolute,to:'2020-04-01T09:55:33.237Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO
datasetKey: 64dabd3c-4f34-4520-b9dd-d227a0bf1582
publishingOrgKey: 0674aea0-a7e1-11d8-9534-b8a03c50a862

**Comment by ManonGros** [comment]
The occurrence has been removed and I don't see any relationship between S. albicans and S. coerulea in the Curren backbone.
