### ISSUE TITLE
Data user agreement: hard to find

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#262]
**Data user agreement: hard to find**

I had trouble re-finding the data user agreement page, wanting to refer to it. It used to be included in the page footer, but that seems to have changed. Suggest to
- refer to is somewhere from the menu structure
- include in notification mails on &quot;GBIF data download is ready&quot;
- possibly add link to the data citation page
whatever makes best sense, unless the agreement is being retired

-----
fbitem-ab29ac3a8dcee341f980bfa4f6246a83884060fe
Reported by: @ahahn-gbif
System: Firefox 54.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/terms/data-user
Window size: width 1075 - height 586
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-27T09:26:32.380Z',mode:absolute,to:'2017-07-27T09:32:32.380Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-27T09:26:32.380Z',mode:absolute,to:'2017-07-27T09:32:32.380Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
I've expected this to reappear in a footer, though it's obviously not yet in place.

**Comment by MortenHofft** [comment]
Thanks
I've added it to the footer (it had been removed because the page hadn't been ported) https://github.com/gbif/portal16/commit/0aef41e57a31500d08c83e8ce54862510f2eb7e7

**Comment by MortenHofft** [comment]
>include in notification mails on "GBIF data download is ready

@kcopas this might be a chance to review the email notification and add that info? changing the template is simple once the text has been decided. If so @cgendreau can quickly do that. Or let me know how to.

**Comment by kcopas** [comment]
Have a draft of the onboarding message underway—will wrap it up either later today or tomorrow.
