### ISSUE TITLE
Transfer of images from Sesleria caerulea page to Sesleria albicans.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2620]
**Transfer of images from Sesleria caerulea page to Sesleria albicans.**

There are several images that bear the title Sesleria albicans. These should be transferred to the appropriate page.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bd72c404cd191e7706612cb8e991c135:63fbe3fe45b3e3c4cea002fdedabc5a91f51b56405d842abca9fd6f50785a83206e50d0814985a40b9900cc2ee736f6db9f044357b68e07e7043097ebe1962eb)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/occurrence/gallery?taxon_key=4119608
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-01T09:58:52.766Z',mode:absolute,to:'2020-04-01T10:04:52.766Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-01T09:58:52.766Z',mode:absolute,to:'2020-04-01T10:04:52.766Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
I assume that the details of the misidentified observation were logged in the other issues from the same user:
https://github.com/gbif/portal-feedback/issues?q=is%3Aissue+is%3Aopen+Sesleria+albicans
