### ISSUE TITLE
image numbers

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2623]
**image numbers**

Reference is made to the license of the iNaturalist images. However, the downloads do not contain links to the image. Download contained urls only link to observations, and the image numbers or urls are missing.

It would be very welcome to have these image numbers.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c7dc9c35dddf544fc45361ba0f138ae6:21e47e6d71887c9699544df2718b3e7d2a22516b52e8c7cb44d6401004f9eed9c79d89a7abdebfef17926ef8980e16c879ed3d3e5d81b4f08849c56bf0a0480e)
System: Firefox 74.0.0 / Windows 7.0.0
Referer: https://www.gbif.org/occurrence/search?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7
Window size: width 1440 - height 755
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-02T15:03:24.194Z',mode:absolute,to:'2020-04-02T15:09:24.194Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-02T15:03:24.194Z',mode:absolute,to:'2020-04-02T15:09:24.194Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
replied by email.
