### ISSUE TITLE
List of Institutional Codes

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2673]
**List of Institutional Codes**

Hello, I was wondering whether you might have access to a list of institutional codes and the corresponding institution? 
Thanks, 
Emily

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/99a309af5a541c78b6bc80cb6ecec8f1:4882e85e885835dd03bd320d13b05d487ea46aab46231459df2b3477e7283616f9bcc910360f7c398756a28327e30cf7a5a59051fcac45d2f79275ef50608d60)
System: Opera 67.0.3575 / Mac OS X 10.11.6
Referer: https://www.gbif.org/faq?q=institutional%20codes
Window size: width 1101 - height 579
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-06T15:47:28.527Z',mode:absolute,to:'2020-04-06T15:53:28.527Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-06T15:47:28.527Z',mode:absolute,to:'2020-04-06T15:53:28.527Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by albenson-usgs** [comment]
Hi Emily,

Recently someone pointed me to the Research Organization Registry Community (https://ror.org/). GBIF also has GRSciColl https://www.gbif.org/grscicoll/institution/search?q=university%20of%20guam&offset=0

**Comment by ManonGros** [comment]
Replied by email as well.
