### ISSUE TITLE
Sesleria haynaldiana Schur is a synonym

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2678]
**Sesleria haynaldiana Schur is a synonym**

According to Deyl (1980) Sesleria haynaldiana Schur is synonym of Sesleria rigida Heuffel ex Reichenb.

Reference:
Deyl, M. 1980: Sesleria Scop. In: Tutin, T.G. Heywood, V.H. Burges, N.A. Valentine, D.H. Walters, S.M. & Webb, D.A. (Eds.) Flora Europaea 5: 173-177. Cambridge.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/aa1b3f565593fd5fe0f19e5b0ffad8d5:14e5d65c2491794947df853c350bd2dac1051dce7bf0569548526e3dc22e76ecdf88d9a1afa98019fd9e98688174174484a8e44a61960fc640b92b482b70ba2f)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/species/7800120
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-06T20:02:39.947Z',mode:absolute,to:'2020-04-06T20:08:39.947Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-06T20:02:39.947Z',mode:absolute,to:'2020-04-06T20:08:39.947Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
This seems to be correct in the CoL: https://www.catalogueoflife.org/data/taxon/4WZTW so we expect to be ok in the next backbone

**Comment by ManonGros** [comment]
This seems fine now: https://www.gbif.org/species/4119351
