### ISSUE TITLE
renaming Europe region

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2680]
**renaming Europe region**

Based on the decision and recommendations from the NSG we should change the wording of the Europe region to "Europe and Central Asia" in all relevant locations. I've updated Contentful and translations, but we should also consider re-centering/adjusting zoom level for the map of the region to incorporate Central Asia (see `https://www.nature.com/articles/sdata20167/figures/1).`

Finally, if you could do a new build to get the new translations in, that would be lovely.

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/84b9877a8579a5cdba0c44c320d966f0:ae94af444602742feca1512b5d1bf3e79f349382cd5930e4341332256e55a984c54a553c5d55ff69b3f7e8e0c01578713d95932451221682df2a931a8e31034c)
System: Chrome 80.0.3987 / Mac OS X 10.15.3
Referer: https://www.gbif.org/the-gbif-network/europe
Window size: width 1405 - height 1124
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-07T09:32:08.529Z',mode:absolute,to:'2020-04-07T09:38:08.529Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-07T09:32:08.529Z',mode:absolute,to:'2020-04-07T09:38:08.529Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by jlegind** [comment]
Hi @dnoesgaard and Thomas,

Do you have a link to a list or table of these official definitions of Regions?

-Jan

**Comment by dnoesgaard** [comment]
@jlegind, would this work?

https://api.gbif.org/v1/enumeration/country

**Comment by MattBlissett** [comment]
That, and therefore https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/Country.java, is the source for everything else.
