### ISSUE TITLE
I downloaded occurrence data for Jungle Bush Quail (India) and it really huge in size (1.5 GB). I extracted the files from the zip but it contains no data. How to correct this?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2693]
**I downloaded occurrence data for Jungle Bush Quail (India) and it really huge in size (1.5 GB). I extracted the files from the zip but it contains no data. How to correct this?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/842bd538f061cf355dd75fb68493b88c:c5b9ce459cd1c666579be1c533a96a91a688fdbbc62e41826dce530d2b59cc4bd323c9ea25352443ea7fcee3166de637ced1d5172579ebf642630f30dfd0aff9)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=csv%20files
Window size: width 1093 - height 500
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-09T07:38:45.139Z',mode:absolute,to:'2020-04-09T07:44:45.139Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-09T07:38:45.139Z',mode:absolute,to:'2020-04-09T07:44:45.139Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
replied by email.
