### ISSUE TITLE
Sesleria coerulans Friv., not Sesleria rigida.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2697]
**Sesleria coerulans Friv., not Sesleria rigida.**

For the modest stature (ca. 25 cm), flat and quite wide leaves, I would assign these specimens to Sesleria coerulans Friv., certainly not to Sesleria rigida.
The country of origin is probably Romania, whose borders after the war expanded at the expense of Hungary.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d3d5b16f38993b8868e8a4052a3da835:1187ca95304abb9371e28ed631cbb799c0ad0b04a5cd7551c9e96d385a1335c64c668ddab71021f43bdaa7cdea29c7ad327d12136f852f74ae14734ff07fd563)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/occurrence/2517063877
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-09T14:57:02.175Z',mode:absolute,to:'2020-04-09T15:03:02.175Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-09T14:57:02.175Z',mode:absolute,to:'2020-04-09T15:03:02.175Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO
datasetKey: 15f819bd-6612-4447-854b-14d12ee1022d
publishingOrgKey: 396d5f30-dea9-11db-8ab4-b8a03c50a862

**Comment by ManonGros** [comment]
The determination was updated even though it isn't Sesleria coerulans
