### ISSUE TITLE
Sesleria coerulans Frv. not Sesleria rigida.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2698]
**Sesleria coerulans Frv. not Sesleria rigida.**

For the modest stature (ca. 25 cm), flat and quite wide leaves, I would assign these specimens to Sesleria coerulans Friv., certainly not to Sesleria rigida.
The country of origin is Transylvania (Romania), whose borders after the wars expanded at the expense of Hungary.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f7a280a3ea02062bc247a52d184b1255:4b7f9c81d36dafe2de4b3c400c73e80678a61fa8ff8efc9b64a50ae16f8b0f5484e85c11f51718e51de8a18b7524f2488ff3c55b4c08cf5d5b87ddf4adc6f1a1)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/occurrence/2514980562
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-09T15:09:13.691Z',mode:absolute,to:'2020-04-09T15:15:13.691Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-09T15:09:13.691Z',mode:absolute,to:'2020-04-09T15:15:13.691Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO
datasetKey: 15f819bd-6612-4447-854b-14d12ee1022d
publishingOrgKey: 396d5f30-dea9-11db-8ab4-b8a03c50a862

**Comment by ManonGros** [comment]
The determination is no longer Sesleria rigida so the curators have checked the specimen (although it isn't Sesleria coerulans).
