### ISSUE TITLE
2 rows of 4 cards would probably look nicer

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#270]
**2 rows of 4 cards would probably look nicer**

curently there is only 7 cards, that doesn&#39;t break nice on different sizes.

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
Reported by: @mortenhofft
System: Chrome 59.0.3071 / Mac OS X 10.11.6
Referer: https://www.gbif-uat.org/
Window size: width 1921 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-04T11:29:36.633Z',mode:absolute,to:'2017-08-04T11:35:36.633Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-04T11:29:36.633Z',mode:absolute,to:'2017-08-04T11:35:36.633Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I'll leave this to you @dnoesgaard

**Comment by dnoesgaard** [comment]
I agree. I think @kcopas does too?
