### ISSUE TITLE
Authorship of Dichondra, a flowering plant

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2704]
**Authorship of Dichondra, a flowering plant**

GBIF is treating the accepted authorship as Forst. I cannot understand why. Two highly reliable (but not error-free) resources (IPNI and Tropicos) state that the correct authorship is J.R. Forst. & G. Forst. Please either justify your decision - cite its source - or make a change.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b2bad4a58cd7fc925c5340b31eb58e9d:d6d08985f1393576119895babc9aaef799bae6380e0d00d7749d2edafbb11aab3a5688243f424972f0cba318d9598ecaed6409e98126bf770b3c1921b2f710bd)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/map?taxon_key=2928658
Window size: width 1041 - height 805
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-10T11:37:20.169Z',mode:absolute,to:'2020-04-10T11:43:20.169Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-10T11:37:20.169Z',mode:absolute,to:'2020-04-10T11:43:20.169Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
As far as I can see, this scientific authorship is based on the Catalogue of life: https://www.gbif.org/species/2928658
That being said, I couldn't find the reference to the CoL. To check with the next update.

**Comment by ManonGros** [comment]
Solved in the new backbone.
