### ISSUE TITLE
Sesleria krajinae is considered synonym of Sesleria vaginalis.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2707]
**Sesleria krajinae is considered synonym of Sesleria vaginalis.**

Sesleria krajinae is considered synonym of Sesleria vaginalis (The Plant List). Perhaps only a form with narrower leaves.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1bbfecc009f29bffb40280515c872660:809e6e767669db09b3872b4cf796cd3982d11d8e4dcd0c9c44e8a7d33ada1abce613791b7100547e022f488807c453fa7c4cf0a55a06d3ed978d3232a1877111)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/occurrence/438260426
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-11T07:40:44.774Z',mode:absolute,to:'2020-04-11T07:46:44.774Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-11T07:40:44.774Z',mode:absolute,to:'2020-04-11T07:46:44.774Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO
datasetKey: b5cdf794-8fa4-4a85-8b26-755d087bf531
publishingOrgKey: 2cd829bb-b713-433d-99cf-64bef11e5b3e

**Comment by leo-buitrago** [comment]
The identification is correct and also the taxonomy in the GBIF Backbone https://www.gbif.org/species/4119197
