### ISSUE TITLE
This sample was collected in Greece not in Germany.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2708]
**This sample was collected in Greece not in Germany.**

This is a sample of Sesleria taygetea Hayek, an endemic species of M. Taygeto in Greece, collected on this mountain, not in Germany.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ddce9412209a83e311dc5afb39d0c2ae:b89eb9ae9bd3cb8c1f253fc7856b9c70e8e5bd41f92047c2a9b51341f71475c2c5095dfbbe7ac94412cc8e9490d2365cfbf209cfbe772a38af52687be4b655ac)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/occurrence/1056116352
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-11T08:02:06.259Z',mode:absolute,to:'2020-04-11T08:08:06.259Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-11T08:02:06.259Z',mode:absolute,to:'2020-04-11T08:08:06.259Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO
datasetKey: 7e380070-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 19456090-b49a-11d8-abeb-b8a03c50a862

**Comment by ManonGros** [comment]
The records shows that the specimen was collected in Greece.
