### ISSUE TITLE
descriptions is spanish. I want to see english. But I cannot change.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2711]
**descriptions is spanish. I want to see english. But I cannot change.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/31d28d8ad882341aaf77f316bb8128e9:fd765dc747506f21329164ee8bc00fc4ce9a2ec05ab0cc59159945061a4e8b2043bb2818e6480e30dc1c7e6b1be5702f7a838aefadc6e8752241ab8d7925aee7)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/species/2432416
Window size: width 1536 - height 722
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-13T10:41:39.649Z',mode:absolute,to:'2020-04-13T10:47:39.649Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-13T10:41:39.649Z',mode:absolute,to:'2020-04-13T10:47:39.649Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
Replied by email.
