### ISSUE TITLE
Regions pages: map overlays text underneath, depending on zoom level

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2712]
**Map overlays text underneath, depending on zoom level**

The map in my (laptop) display, at default opening level, overlays part of the text underneath. I need to change the zoom level of my display several notches to have the header and the green labels appear. Not an issue on large screens, but confusing on a small display. Can this be prevented?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8907e0d56150908d50a495ab096883cc:15035c2b0c3b32f80fb35f96945ba485e019d3d9dc4d1a40a7b3881548767115b73d72a8ba463ef104bf27869fc82631b1c52de9eb8c6aad39b129312f2eaf2e)
System: Firefox 75.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/the-gbif-network/europe
Window size: width 1220 - height 556
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-14T07:41:34.444Z',mode:absolute,to:'2020-04-14T07:47:34.444Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-14T07:41:34.444Z',mode:absolute,to:'2020-04-14T07:47:34.444Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
![image](https://user-images.githubusercontent.com/13435656/79199236-fb6f5c80-7e34-11ea-9901-6128c1580b62.png)
