### ISSUE TITLE
host relationships / descriptions

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#2713]
I was looking for descriptions (taxonomic treatments) of bats in GBIF "species" search and discovered that I find mainly fleas parasites of bats.
https://www.gbif.org/species/search?q=Chiroptera&qField=DESCRIPTION

This is interesting and at the same time misleading

Description thus refers to the description of the occurrence not to the taxonomic treatment which in a sense should be the case arriving there from the "species" search?!

**Comment by myrmoteras** [comment]
btw, this is even more puzzling.
So searching for "Chiroptera"  https://www.gbif.org/species/search?q=Chiroptera
leads to this, of which the first two records are shown
![image](https://user-images.githubusercontent.com/4609956/79206080-1d6ddc80-7e3f-11ea-9665-5a7782653685.png)

Following the link https://www.gbif.org/species/7921571 leads to this 
![image](https://user-images.githubusercontent.com/4609956/79206203-4aba8a80-7e3f-11ea-9f64-b85e86685ce0.png)

which has 1 treatment https://www.gbif.org/species/7921571/treatments

which in fact is the same as this https://www.gbif.org/species/119510697 does the same species has two GBIF numbers.

Does 7921571 refer to a taxon, whilst 119510697 refers to a taxonomic treatment (names usage)? If so, are you aware of a species aka taxon, that has several treatments?

**Comment by myrmoteras** [comment]
is there a way to search for anything that belongs to Chiroptera (bats) taxa only?

BTW this would be a  great asset for GBIF to be able to list species interaction!

**Comment by thomasstjerne** [comment]
@myrmoteras the species https://www.gbif.org/species/7921571 is in the GBIF backbone taxonomy, whereas the species  https://www.gbif.org/species/119510697 is from the dataset "Revision of Aciuroides Hendel and Neoacanthoneura Hendel (Diptera: Ulidiidae: Pterocallini)".
The backbone species has the other one as source - i.e. is copied into the GBIF backbone from that checklist. 
There are some differences in how GBIF displays backbone species opposed to species from other checklists, for example having treatments on their own tab.

**Comment by thomasstjerne** [comment]
> is there a way to search for anything that belongs to Chiroptera (bats) taxa only?
> 

Yes, by clicking the first link in your search you will be taken to https://www.gbif.org/species/734
From there, you will see all taxa under Chiroptera in the "taxon browser" on the left.
