### ISSUE TITLE
Clarify the license number in the text

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2716]
**Clarify the license number in the text**

Right now we support only CC BY and CC BY 4.0 but the text doesn't specify this. It only shows "CC BY" and "CC BY-NC" (the number is only accessible by clicking on the links, for example: https://creativecommons.org/licenses/by-nc/4.0/).

Would it be possible to update the text?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/1d0b7bf958f8fbc732898dacba5a17a6:a206e55491e1e5f2609e3a14ad21674ca957c2158a2b1c19e1adfc4f68c37c3f74cf02849989a8d2c3394507b534bb9e6333c09210bb48b1c428e3276d58410f)
System: Safari 13.1.0 / Mac OS X 10.15.4
Referer: https://www.gbif.org/publishing-data
Window size: width 1392 - height 765
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-16T07:33:26.577Z',mode:absolute,to:'2020-04-16T07:39:26.577Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-16T07:33:26.577Z',mode:absolute,to:'2020-04-16T07:39:26.577Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Just so I'm clear: We _only_ support these for occurrence datasets, correct?

CC BY version 4.0
CC BY-NC version 4.0
CC0 version 1.0

So if someone was to publish a dataset with, e.g. CC BY version 3.0, we would reject it?

**Comment by MattBlissett** [comment]
That's correct.

**Comment by dnoesgaard** [comment]
Updated text to include version numbers.
