### ISSUE TITLE
Establishment means

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2718]
**Establishment means**

Does this filter work? I tried and it did not for me (little arrow goes up and down but that's it)

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/de2751d02648e3803fa0d0a8629f0989:bc4aeceb07ee2304c21f8a2348e0ac09eadc1bdde7a20b20af7b96eb40c365013c15d56f75614bd980856a3119e57f8f33b56feb1e4f61df8d4176862e64accf)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?advanced=1
Window size: width 1920 - height 1067
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-17T10:54:37.773Z',mode:absolute,to:'2020-04-17T11:00:37.773Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-17T10:54:37.773Z',mode:absolute,to:'2020-04-17T11:00:37.773Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@thomasstjerne I see you removed this recently
https://github.com/gbif/portal16/blame/verifyaccount/app/views/pages/occurrence/occurrence.ctrl.js/#L77

If it is related to the performance issues, then we need to remove it from the filter resource instead.

**Comment by thomasstjerne** [comment]
It seems to work, yes:
<img width="381" alt="Screenshot at Nov 09 14-43-46" src="https://user-images.githubusercontent.com/1666484/98548630-0cccfa00-229a-11eb-9aac-27cf2811ac78.png">
