### ISSUE TITLE
wrong name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2720]
**wrong name**

This species aren't accepted anymore with this name, and I'm having some trouble to identify the name in use now

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e04dc349739e3d7e787da86ef6bfbbff:90050fa122be537947e0b22607135375888fbada3c7e49c8325f2613cf0ad7cb69633fae1b8bc6d4e68fe63d0b6a7110b803bd869b6688d3d69f252a550c3b56)
System: Opera 67.0.3575 / Windows 10.0.0
Referer: https://www.gbif.org/species/124787710
Window size: width 1496 - height 723
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-19T19:22:25.851Z',mode:absolute,to:'2020-04-19T19:28:25.851Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-19T19:22:25.851Z',mode:absolute,to:'2020-04-19T19:28:25.851Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
From Plazi. 
Source dataset:
https://www.gbif.org/dataset/c7258597-fa96-4b98-a6f8-aecc1f8779d5

**Comment by jhnwllr** [comment]
Will contact user for clarification.

**Comment by jhnwllr** [comment]
User has not responded. (closing issue)
