### ISSUE TITLE
species matching tool

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2722]
**species matching tool**

Dear helpdesk,
i am searching for more detailed description of how the Species mathing tool is working (algorithms behind the process). I guess that there should be a description somewhere at github, but i couldn't find it. 
We are writing an instruction on how to use the tool for our Russian GBIF community. And we wanted to add a link ('read more') for advanced reading.
Sincerely,
Nina.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2fe3417f2802ff2cac6df46eb09d09a2:0616118b64997dd3d23bf67dfff5b57ebad6185db41d80ab57bc69a29c03b03d3874d1c5478dc853282f0be2dd4a1e81252ad5347fabd84145ddeab635a4b696)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1396 - height 612
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-20T08:28:40.407Z',mode:absolute,to:'2020-04-20T08:34:40.407Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-20T08:28:40.407Z',mode:absolute,to:'2020-04-20T08:34:40.407Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This blogpost might help: https://data-blog.gbif.org/post/gbif-species-api/
