### ISSUE TITLE
Fish genus classified as bird - Jerdonia Day, 1871

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2724]
**Fish genus classified as bird - Jerdonia Day, 1871**

This issue was reported on Helpdesk.

Looking into it more:
Jerdonia Day, 1871 is a fish. It is a synonym of Lepidocephalichthys Bleeker, 1863 (https://www.gbif.org/species/162879260), according to The Interim Register of Marine and Nonmarine Genera: https://www.gbif.org/species/162879269.

However, the species "Jerdonia agricolensis Hume, 1870" (https://www.gbif.org/species/9052657) is a bird according to this Syntype from the Natural History Museum (London) Collection Specimens: https://www.gbif.org/occurrence/1291495148.

I suspect that this is the reason for this misclassification.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/3405ce15fddcaf77552e935a2c5eb915:ed9957a2603eea80dd68bbe0b06aaddef07e5d4a86c184b84617a25044953548c26751ee15c8e565a362d748b8a3d3d3887f069ca2991dde644b1854bec1a123)
System: Safari 13.1.0 / Mac OS X 10.15.4
Referer: https://www.gbif.org/species/2367800
Window size: width 1372 - height 895
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-20T09:47:17.024Z',mode:absolute,to:'2020-04-20T09:53:17.024Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-20T09:47:17.024Z',mode:absolute,to:'2020-04-20T09:53:17.024Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
Here are all Jerdonia genera we know about in the latest build:

- Jerdonia Wight - ACCEPTED Gesneriaceae plant
- Jerdonia W.T.Blanford & H.F.Blanford, 1861 - SYNONYM of mollusc genus Cyathopoma
- Jerdonia Hume, 1870 - DOUBTFUL Aves genus

This is not ideal. We have the Hume genus at least as a bird, but Jerdonia Day, 1871 is not included at all even though it is in IRMNG:

> NubBuilder:  process SYNONYM GENUS Jerdonia Day, 1871
> NubBuilder:  Ignore source usage. Status SYNONYM is different from nub (ACCEPTED): Jerdonia Day, 1871
> NubBuilder:  process ACCEPTED GENUS Jerdonia Day, 1871
> NubBuilder:  Updating Jerdonia Hume, 1870 from source Jerdonia Day, 1871
> NubBuilder:  Updating nomenclature for Jerdonia Hume, 1870 from source Jerdonia Day, 1871

Jerdonia agricolensis Hume, 1870 matches now as higher rank match in plants without any additional context. With kingdom=Animalia it becomes a mollusc. WIth class=Aves it snaps to the doubtful aves genus...

I'll see why the nub build merges Jerdonia Hume, 1870 with Jerdonia Day, 1871 - this should not happen.

**Comment by mdoering** [comment]
Fixed. And nub build configured to exclude Jerdonia from Aves.
We also do not make use of the types data anymore, that reduces bad entries too.
