### ISSUE TITLE
Mix up in higher taxonomy between host and parasite

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#2727]
One of our users contacted us because he noticed that the higher taxonomy for the following genera was suspicious.
It seems like these come from PLAZI taxonomic treatment of parasites (such as feather mites) where the host's taxonomy (Aves) was mistaken for the parasite's taxonomy. @myrmoteras @gsautter would it be possible to check what is happening?

| Genera | DOI(s) of the dataset concerned |
|-------|-------|
| [Pseudonematophila](https://www.gbif.org/species/7891454) | https://doi.org/10.5281/zenodo.279099, https://doi.org/10.15468/tshrol |
| [Crassacarus](https://www.gbif.org/species/8457789) | https://doi.org/10.11646/zootaxa.4023.1.1, https://doi.org/10.15468/lqwl7q |
| [Vireodectes](https://www.gbif.org/species/8513913), [Picipterodectes](https://www.gbif.org/species/9392170) and [Montsauria](https://www.gbif.org/species/8605526)| https://doi.org/10.5281/zenodo.282115, https://doi.org/10.15468/d6pc0u |
| [Fainharpirhynchus](https://www.gbif.org/species/8605579) and [Perhapyrhynchus](https://www.gbif.org/species/8689433) | https://doi.org/10.11646/zootaxa.3860.4.1, https://doi.org/10.15468/rj0uq2 |
| [Atelophyllodes](https://www.gbif.org/species/9565519) | https://doi.org/10.5281/zenodo.192069, https://doi.org/10.15468/bfafmr |
| [Neopicobia](https://www.gbif.org/species/9575040) and [Rafapicobia](https://www.gbif.org/species/8110864)| https://doi.org/10.11646/zootaxa.4113.1.1, https://doi.org/10.15468/ad9psd |
| [Harpactiacus](https://www.gbif.org/species/9954887), [Cinclosomatiellum](https://www.gbif.org/species/10349537), [Philemoniellus](https://www.gbif.org/species/10391309), [Garrulaxeus](https://www.gbif.org/species/10485031) and [Estrildinirmus](https://www.gbif.org/species/10047892)| https://doi.org/10.11646/zootaxa.4615.2.2, https://doi.org/10.15468/yg76nv |
| [Krantziaulonastus](https://www.gbif.org/species/7967474) | https://doi.org/10.5281/zenodo.207623, https://doi.org/10.15468/urlfnk |
| [Tyrannidectes](https://www.gbif.org/species/7633796) | https://doi.org/10.5281/zenodo.203166, https://doi.org/10.15468/b6e5m8 |

I am also adding some other genera from PLAZI treatment that seem to have been misclassified (although as far as I can tell they are not parasites):

| Genera | DOI(s) of the dataset concerned |
|-------|-------|
| [Carnarvoncochlea](https://www.gbif.org/species/10088057) and [Conondalia](https://www.gbif.org/species/10596038)| https://doi.org/10.11646/zootaxa.4583.1.1, https://doi.org/10.15468/ycrhs6 |

**Comment by myrmoteras** [comment]
Dear ManonGros, GBIF
might it be possible to post such messages for Plazi also into our https://github.com/plazi/community/issues github repository that is for such purposes. 
Let us know - this would save some emails, and also keep a track on such issues on our side.
cheers
donat

**Comment by ManonGros** [comment]
Yes, we will try to log in these issues directly on https://github.com/plazi/community/issues as. such as possible.

**Comment by ManonGros** [comment]
The taxonomy has been updated on PLAZI side. Now we need to check that everything is corrected in the next backbone update.

**Comment by ManonGros** [comment]
There seem to be two remaining ones in the new backbone:
| Genera | DOI(s) of the dataset concerned |
|-------|-------|
| [Neopicobia](https://www.gbif.org/species/9575040) and [Rafapicobia](https://www.gbif.org/species/8110864)| https://doi.org/10.11646/zootaxa.4113.1.1, https://doi.org/10.15468/ad9psd |
| [Tyrannidectes](https://www.gbif.org/species/7633796) | https://doi.org/10.5281/zenodo.203166, https://doi.org/10.15468/b6e5m8 |

**Comment by gsautter** [comment]
Cleaned up now ... @ManonGros thanks for pointing us to this mix-up.

**Comment by ManonGros** [comment]
@gsautter Thanks for correcting those!
Now I realise I forgot to report a few more, could you perhaps check all of the records in this checklist (https://doi.org/10.15468/ad9psd, https://doi.org/10.11646/zootaxa.4113.1.1)?
Here are a few examples of suspicious taxonomy left:
* https://www.gbif.org/species/120682368
* https://www.gbif.org/species/120682399
* https://www.gbif.org/species/120682401

**Comment by gsautter** [comment]
@ManonGros thanks for spotting this one, fixed ... always a bit of a problem untangling the higher taxa of parasites and their hosts, especially if the latter have a way more prominent presence in literature ...

**Comment by ManonGros** [comment]
Thanks @gsautter ! I can see [some potential others](https://www.gbif.org/species/search?dataset_key=2510711e-d91f-4685-8d30-292eedbc9b41&highertaxon_key=159486090&origin=SOURCE&advanced=1) in this checklist: https://doi.org/10.5281/zenodo.203166, https://doi.org/10.15468/b6e5m8
Could you check if this is the case?

**Comment by gsautter** [comment]
Fixed that latter one as well.

**Comment by ManonGros** [comment]
Wonderful! Thanks @gsautter
