### ISSUE TITLE
Genus name could be misspelling - Calorhamphus - Caloramphus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2729]
**Genus name could be misspelling - Calorhamphus - Caloramphus**

This issue was reported on Helpdesk.

The genus Calorhamphus seems to be a misspelling for the genus Caloramphus Lesson, 1839 (https://www.gbif.org/species/2478986).

The record comes from the [Taxon list of animals with German names (worldwide) compiled at the SMNS](https://www.gbif.org/dataset/88f4e35a-bdf8-4aa2-9a1b-56401d4eed15)

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/3b4473d98047fbc936caac891e5978c2:be4265f58cea7afa48e7e54a24d534a71327c37404b907d17734d64a94daaa8729b9588aae69e2046e7eb5e5945ae5c85a7d47b01c39d785552b50e6c276aa3f)
System: Safari 13.1.0 / Mac OS X 10.15.4
Referer: https://www.gbif.org/species/7340154
Window size: width 1372 - height 895
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-20T14:50:58.358Z',mode:absolute,to:'2020-04-20T14:56:58.358Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-20T14:50:58.358Z',mode:absolute,to:'2020-04-20T14:56:58.358Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
There are 3 sources that claim the same spelling:

- The Interim Register of Marine and Nonmarine Genera As Calorhamphus Lesson, 1839
- Artsnavnebasen As Calorhamphus
- Taxon list of animals with German names (worldwide) compiled at the SMNS As Calorhamphus

IRMNG declares is a synonym of Caloramphus, so thats probably correct then.
