### ISSUE TITLE
Suspicious higher taxonomy - Gunningia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2731]
**Suspicious higher taxonomy - Gunningia**

This issue was reported on Helpdesk.

This genus is likely not a bird.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/03ac5b4156020118cab10dc28315700f:91ddc29649bb69919228109bee4372fe47fba111e886be0d8044e2d20ed50cf6fc73b83d92ee7f55a4e7d32f7b09ada0b1801920648afd6848257d768d411af2)
System: Safari 13.1.0 / Mac OS X 10.15.4
Referer: https://www.gbif.org/species/4850671
Window size: width 1372 - height 896
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-20T14:56:36.263Z',mode:absolute,to:'2020-04-20T15:02:36.263Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-20T14:56:36.263Z',mode:absolute,to:'2020-04-20T15:02:36.263Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
It is a bird, sunbbird:

<img width="316" alt="Screenshot 2021-02-15 at 18 55 52" src="https://user-images.githubusercontent.com/327505/107980017-d94beb00-6fbf-11eb-9ec3-e484d4b425fd.png">

https://www.zobodat.at/pdf/Bonner-Zoologische-Beitraege_28_0082-0101.pdf

Also on German Wikipedia:

> Die von Austin Roberts 1922 neu eingeführte Gattung Gunningia gilt heute als Synonym für die Gattung Euchloridia.[7]
