### ISSUE TITLE
I am working with several colleagues on a Monograph on the Mammals of Tanzania (checklist, distribution, etc). Would I have to search each individual species (over 400 species) in order to develop a dataset ? or is there a way I download  a list of all mammals from Tanzania that are recorded in GBIF?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2733]
**I am working with several colleagues on a Monograph on the Mammals of Tanzania (checklist, distribution, etc). Would I have to search each individual species (over 400 species) in order to develop a dataset ? or is there a way I download a list of all mammals from Tanzania that are recorded in GBIF?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6f415719ee35b82a9a32d009795a2610:36c26d74ebfc12a74735d66460c68da5767326e621a79ca574225234724471d4c0baafb7d3c4eeed393d24990e30a063a6ed34c00e8f19767eb2ea716f044266)
System: Safari 11.1.1 / Mac OS X 10.13.5
Referer: https://www.gbif.org/occurrence/search?country=TZ&taxon_key=2437731
Window size: width 1270 - height 638
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-21T20:12:25.179Z',mode:absolute,to:'2020-04-21T20:18:25.179Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-21T20:12:25.179Z',mode:absolute,to:'2020-04-21T20:18:25.179Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by timhirsch** [comment]
Try https://www.gbif.org/occurrence/search?country=TZ&taxon_key=359 , view species at https://www.gbif.org/occurrence/taxonomy?country=TZ&taxon_key=359 
Click 'download' and there is an option to download the species list.

**Comment by MattBlissett** [comment]
@timhirsch, did you also send this response by email? It's not automatic, and many users won't know to look again at the Github issue.

**Comment by timhirsch** [comment]
Oops sorry no, made an assumption there. Serves me right for interfering. Not sure I would have the right access for that - could you help @MattBlissett ?

**Comment by MattBlissett** [comment]
Replied by email — using Tim's reply :-)
