### ISSUE TITLE
IPT password for a newly registered organization

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2736]
**IPT password for a newly registered organization**

Dear friends, we have just received an endorsement letter for this organization: https://www.gbif.org/publisher/c21e080a-4bee-4a46-97c4-2cc8b814686b
Please, send me an IPT password as well, it will be hosted on our university' installation.
Sincerely, Nina.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c22594a7864916aa7eefe8523783206f:e3cec90d236679b1454089af35ad550f25201ff9c98c8b0fc73ab8b0b40de70680b1d6f4247cc808784c09cfa97281cb4c8ac6354b07e22b4a26f1f05ad1781a)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1396 - height 612
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-22T16:03:27.035Z',mode:absolute,to:'2020-04-22T16:09:27.035Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-22T16:03:27.035Z',mode:absolute,to:'2020-04-22T16:09:27.035Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
Pass token already sent.
