### ISSUE TITLE
Pipe being included in reference work link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2737]
**Pipe being included in reference work link**

As an example see this record:  https://www.gbif.org/occurrence/657033948.  Go to the Associated references field.  Note that the pipe is being included in the URL each time which breaks it.  Not sure if this is an error from my end or yours.  I know that I am porting these out as a concatenated list and you are then creating URls.  I am hoping to use the reference work extension in the near future but could you check it out please?

Thanks

Andy

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4c1b24aaa70a75158e6e7862f74a763e:415846fff3ba3c9c7e936601aa34d62eb44bcc3ca4e2114b2777eaf8d0d98d4c6c7585bbaae5031a7a6ae9a9c607159c282cd72c968547da117306ac5a562fba)
System: Chrome 81.0.4044 / Mac OS X 10.15.4
Referer: https://www.gbif.org/occurrence/657033948
Window size: width 1600 - height 851
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-22T17:10:09.125Z',mode:absolute,to:'2020-04-22T17:16:09.125Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-22T17:10:09.125Z',mode:absolute,to:'2020-04-22T17:16:09.125Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 8f79c802-a58c-447f-99aa-1d6a0790825a
publishingOrgKey: b554c320-0560-11d8-b851-b8a03c50a862

**Comment by MattBlissett** [comment]
Hi Andy

Although it's not stated on the associatedReferences DarwinCore term, 
several other terms say "Recommended best practice is to separate the 
values in a list with space vertical bar space (|| |)."

Your current delimiter is "| ".  If you can easily use " | " as a 
delimiter, I think your URLs will show up correctly.  We only do minimal 
interpretation on this field, so the only processing is the website 
itself trying to make things that look like URLs into hyperlinks.  It 
seems that's considering the | at the end as part of the URL.

Here's exactly what you provided for that record:

http://www.scielo.cl/scielo.php?script=sci_arttext&pid=S0718-19572010000400009| 
| http://www.bioone.org/doi/10.1643/CG-14-184| 
http://www.tandfonline.com/doi/abs/10.1080/02724634.2013.835642| 
http://dx.doi.org/10.1590/1982-0224-20180079 | 
https://www.tandfonline.com/doi/full/10.1080/02724634.2017.1312690

Cheers,

Matt

(By Github and email)

**Comment by ManonGros** [comment]
The data looks good now, closing the issue. We can re-open it if needed.
