### ISSUE TITLE
Incorrect taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2738]
**Incorrect taxonomy**

I am still seeing Cepolidae being placed in Mollusca even though it is also a valid fish family.  See metrics tab here:  https://www.gbif.org/dataset/8f79c802-a58c-447f-99aa-1d6a0790825a.  I have submitted this issue before without resolution.

Can we get this resolved please? It doesn't look good!

Andy

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/09abec94bb7c636e76a03828c9b6f8b2:2396316964b607d3ab284b94596d3c160e5078526eea576cf5710ae3bb8f4b851aefd8ed3e57a2c7b454a812343e0f1cfc0f5a942a299c202f8cc052dcedb04d)
System: Chrome 81.0.4044 / Mac OS X 10.15.4
Referer: https://www.gbif.org/occurrence/657033948
Window size: width 1600 - height 851
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-22T17:12:32.470Z',mode:absolute,to:'2020-04-22T17:18:32.470Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-22T17:12:32.470Z',mode:absolute,to:'2020-04-22T17:18:32.470Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 8f79c802-a58c-447f-99aa-1d6a0790825a
publishingOrgKey: b554c320-0560-11d8-b851-b8a03c50a862

**Comment by ManonGros** [comment]
Solved in the new backbone.
