### ISSUE TITLE
many different names - be more explicit about which is what

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#274]
**many different names - be more explicit about which is what**

we show the verbatim name in the headline. But link to a backbone species. Maybe this should be called differently?

-----
fbitem-occurrence1425909074
Reported by: @mortenhofft
System: Chrome 59.0.3071 / Mac OS X 10.11.6
Referer: https://www.gbif-uat.org/occurrence/1425909074
Window size: width 1921 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-04T11:36:47.116Z',mode:absolute,to:'2017-08-04T11:42:47.116Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-04T11:36:47.116Z',mode:absolute,to:'2017-08-04T11:42:47.116Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: b124e1e0-4755-430f-9eab-894f25a9b59c
publishingOrgKey: d3978a37-635a-4ae3-bb85-7b4d41bc0b88

**Comment by MortenHofft** [comment]
![screen shot 2017-08-04 at 13 39 51](https://user-images.githubusercontent.com/6759267/28967273-b2a52a92-791a-11e7-9641-5c7e01961483.png)

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/423
