### ISSUE TITLE
consider moving description of publisher from datasets to publisher

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2740]
**consider moving description of publisher from datasets to publisher**

This and other datasets by the same publisher have a generic description of the publisher included in their descriptions—while the publisher itself has very little useful description. 

Consider moving the generic part to the publisher.

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/2aa4fe1d523a9a3cbabd80f4c739783f:e069aba5aeadb4fad4ae924b04a41530b5d8176c2aa6af79c61f21a7d0032a8b3b6414de0258531f5583f8c1c3946940b2c1c75300d556aad96205ca71bc8ab0)
System: Chrome 80.0.3987 / Mac OS X 10.15.3
Referer: https://www.gbif.org/dataset/873fed70-e0f0-411d-a6d1-1d2417c9991f
Window size: width 1781 - height 1176
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-23T11:51:19.094Z',mode:absolute,to:'2020-04-23T11:57:19.094Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-23T11:51:19.094Z',mode:absolute,to:'2020-04-23T11:57:19.094Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
fyi @dagendresen

**Comment by jhnwllr** [comment]
I think this can be closed since they only publish one dataset. 

https://www.gbif.org/dataset/bed78790-cbec-44af-82af-fe78e9692287
