### ISSUE TITLE
This is a sample of Sesleria alba Sibth. & Sm. not Sesleria heufleriana

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2744]
**This is a sample of Sesleria alba Sibth. &amp; Sm. not Sesleria heufleriana**

This is a sample of Sesleria alba Sibth. & Sm. not Sesleria heufleriana, considering wider leaves and size of the panicle. Moreover this sample comes from Caucasus, a region in which Sesleria heufleriana is not Known.

Reference
Deyl, M. 1980: Sesleria Scop. In: Tutin, T.G. Heywood, V.H. Burges, N.A. Valentine, D.H. Walters, S.M. & Webb, D.A. (Eds.) Flora Europaea 5: 173-177. Cambridge.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2682e841fce69d3a7dc0e1f69fdc6b9e:8b231926143fe45db5a19132fc25fcecb9c7a7704704f1b3f5250db45ddba101769dd16df61cb4766acd2d7bbc11d3df3faad0557c7466ec186e67ec14427e9e)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/occurrence/1697764283
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-26T15:21:20.898Z',mode:absolute,to:'2020-04-26T15:27:20.898Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-26T15:21:20.898Z',mode:absolute,to:'2020-04-26T15:27:20.898Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 902c8fe7-8f38-45b0-854e-c324fed36303
publishingOrgKey: f5fc4e61-b7a0-414b-ab68-b41cb23e7fdc

**Comment by leo-buitrago** [comment]
The issue was incorrect, see https://github.com/gbif/portal-feedback/issues/2745
