### ISSUE TITLE
Debatable provenance.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2746]
**Debatable provenance.**

This sample could be coming from Germany as cultivated plants, since Sesleria heufleriana do not exist in the wilderness of Germany.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2c48e264b9bae50823df4e857ba4d422:1edff66ef48e646af97028ebcc76d5ff3dd632193a7330ece8e42777a4a1c58ee90df07523163b9679e205e745997eaa6095912b5b1a89601ad3a08e1c6ba111)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/occurrence/2513629915
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-26T15:58:57.437Z',mode:absolute,to:'2020-04-26T16:04:57.437Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-26T15:58:57.437Z',mode:absolute,to:'2020-04-26T16:04:57.437Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 15f819bd-6612-4447-854b-14d12ee1022d
publishingOrgKey: 396d5f30-dea9-11db-8ab4-b8a03c50a862

**Comment by timhirsch** [comment]
From the textual locality description, this appears to have been collected in present-day Romania

**Comment by jeroencreuwels** [comment]
I will contact the botany collection managers at Naturalis. I agree with Tim that this is located in Transylvania (which is Siebenbuergen in German), Romania.

**Comment by jhnwllr** [comment]
The record now appears to be in Romania. 
![image](https://user-images.githubusercontent.com/4245213/146179698-714576ae-4c7d-4f23-a468-cef10f0c7426.png)
