### ISSUE TITLE
link to Alien Species Checklist in PT Country page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2748]
**link to Alien Species Checklist in PT Country page**

It is nice to see a link in the country page of many countries to their Alien Species checklist. Could it be added to the PT country page? The checklist is https://www.gbif.org/dataset/61b67ae8-c623-42a9-9172-3283f2f1473b

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/375547a0c9c0660412dd3edaa3d7a768:80cb65bcc7377dd280ca30470fc21f7cdd2fe2da258dcb62166c055b5a55f8dd49785f893954961b4402ff4fa88409202417ae87b06067a4c3214a902765bc42)
System: Firefox 75.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/country/PT/summary
Window size: width 1440 - height 692
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-28T14:24:44.153Z',mode:absolute,to:'2020-04-28T14:30:44.153Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-28T14:24:44.153Z',mode:absolute,to:'2020-04-28T14:30:44.153Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@ahahn-gbif it looks like the keywords are missing from the dataset

**Comment by ahahn-gbif** [comment]
The keyword reads "Portugal_PT" instead of "country_PT". Contact with GRIIS in process, thanks

**Comment by rpfigueira** [comment]
@ahahn-gbif Thanks! The link `Alien Species` is now added, with links to two checklists for Azores and Madeira. But the checklist for Portugal Mainland (link above) still does not appear. I guess it is under process as well...

**Comment by timhirsch** [comment]
Yes @rpfigueira this is a simple coding error on the IUCN side we hoped she had fixed, but apparently not yet. Soon I hope! At least the islands are now appearing in the right place.

**Comment by timhirsch** [comment]
@rpfigueira the coding error has now been corrected, so the main country list is now showing up correctly alongside Azores and Madeira when you use the link from the Portugal country page.

**Comment by ManonGros** [comment]
It seems that the issue should be closed now. Let me know if not.
