### ISSUE TITLE
Out of Sync 317fd0a9-1bcf-4e94-bc3c-a685c4693c10

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/portal-feedback#2751]
The dataset https://www.gbif.org/dataset/317fd0a9-1bcf-4e94-bc3c-a685c4693c10 looks 'out of sync', apparently due to a gbifID creation problem in the DB.

The dataset must have 1786 occurrences associated (like [here](https://www.gbif-uat.org/dataset/ec6743a3-96fb-4cd4-9bfc-a5e528b2a355)) but it shows only 712.

**Comment by leo-buitrago** [comment]
katia.gbif@gmail.com you can follow the solution here.

**Comment by muttcg** [comment]
Looks like gbifId generation returns NULL for all these ids:

IEO-CD-CCLME11/559
IEO-CD-CCLME11/556
IEO-CD-CCLME11/555
IEO-CD-CCLME11/558

...etc

So I need to check why it can't generate ids

**Comment by muttcg** [comment]
Fixed
