### ISSUE TITLE
I am trying to identify this species of air plant. I cannot find any other like it

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2754]
**I am trying to identify this species of air plant. I cannot find any other like it**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/092b2fb8659a83f4956740cea8090e59:2b9058938c4a5f81ffdfbc3b522781afb5e9af7b2623c04988128208d9ae29f8a665e092dad6a51eef1563b23a1863a18b93bab2fb5d24abe78e79011fb04269)
System: Chrome Mobile WebView 81.0.4044 / Android 0.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 412 - height 717
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-30T17:17:41.544Z',mode:absolute,to:'2020-04-30T17:23:41.544Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-30T17:17:41.544Z',mode:absolute,to:'2020-04-30T17:23:41.544Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
