### ISSUE TITLE
country names

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2757]
**country names**

I noticed a rather inconsistent use of country names. Some countries are stated with their official names, some are not. Our records indicating Iran are being altered by GBIF in Iran, Islamic Republic of. Records indicating Netherlands remain Netherlands instead of Netherlands, Kingdom of the. Filling in something like Islamic Republic of Iran in our database will automatically show this on our labels as well and will occupy lots of needless space there.... Only <200 countries in the world today so please let's standardize!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/943153880b6a485770d780e71589a651:940e155a5c14bb9e461aa10d9ced877a0fce2f857f1550f81827fab96d0d770fb9d6f3bc84d0f904fe6d07b72ed93a5ed09a476bc03cdf1ddc53aea6a686a46e)
System: Firefox 75.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?country=IR
Window size: width 1920 - height 944
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-02T08:15:17.960Z',mode:absolute,to:'2020-05-02T08:21:17.960Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-02T08:15:17.960Z',mode:absolute,to:'2020-05-02T08:21:17.960Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Standard is ISO-3166. Pretty sure we use short names. 

‘The Kingdom of the Netherlands’ is a long name: https://www.iso.org/obp/ui/#iso:code:3166:NL

‘Iran, Islamic Republic of’ is a short name: https://www.iso.org/obp/ui/#iso:code:3166:IR

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MattBlissett** [comment]
Replied by email.
