### ISSUE TITLE
when I download info of a species, i can't download the latitude and longitude info, i doesn't appear in the excel when I download it

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2758]
**when I download info of a species, i can&#39;t download the latitude and longitude info, i doesn&#39;t appear in the excel when I download it**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/385ef228dea9e4a1974bf92e27cbbac8:b8c7329005a7719c15de997d3c802bb224125186027bda67a108a1afc277d37c5cdf5b737d19af627889b9c69d46bd7a97f60b9c63c79681e2fa09dfed727f01)
System: Chrome 81.0.4044 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0054621-200221144449610
Window size: width 1517 - height 694
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-02T14:22:54.299Z',mode:absolute,to:'2020-05-02T14:28:54.299Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-02T14:22:54.299Z',mode:absolute,to:'2020-05-02T14:28:54.299Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
