### ISSUE TITLE
Coordinate error for longitude of Rincón de la Vieja

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2760]
**Coordinate error for longitude of Rincón de la Vieja**

This is to report a suspicious coordinate for specimen NHMUK:ecatalogue:436845 in Natural History Museum (London) Collection Specimens data.  The specimen (https://www.gbif.org/occurrence/1057032734) was collected by Gerardo Herrera (630) at Rincon de la Vieja National Park.  The longitude coordinate is currently 083 19 00.0000 W so it falls on the Caribbean sea, and collecting sites at Rincón de la Vieja National Park have a starting coordinate of 085 W.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b4cfb1668fde7c453e70584777f4d385:8a9e5d9dcdc459d29181db366c45a0acf3ad58c7eab1879d1ae03828fcdada6c3ab61e521e239aa0e8b2737bbe8cc1f2a372996bd423d3a005bc7165cd72b4f8)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1057032734
Window size: width 1280 - height 648
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-04T01:02:25.747Z',mode:absolute,to:'2020-05-04T01:08:25.747Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-04T01:02:25.747Z',mode:absolute,to:'2020-05-04T01:08:25.747Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 7e380070-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 19456090-b49a-11d8-abeb-b8a03c50a862

**Comment by ManonGros** [comment]
It looks like the coordinates have already been corrected.
