### ISSUE TITLE
Ordering for Plant search

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2763]
**Ordering for Plant search**

Hi all, in the API description for Species on the /search endpoint you say that the result is ordered by relevance. How is this relevance defined and can it be influenced by some parameters?

We would like to search plants for german vernacular names and get the ones that are most likely present in Switzerland.

Thanks!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/be71c368e70faf760765392d15dcdb68:0b7167cb6fd7a099b258225ed87f066047ff9f6a9e60668febbf3b633fad4da60071d320e9429410bd46f6cfa4f01f257d6fd720820bd1c29ccb4f913b0fd11b)
System: Chrome 81.0.4044 / Mac OS X 10.15.4
Referer: https://www.gbif.org/species/2994120
Window size: width 2560 - height 1306
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-05T15:34:12.298Z',mode:absolute,to:'2020-05-05T15:40:12.298Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-05T15:34:12.298Z',mode:absolute,to:'2020-05-05T15:40:12.298Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
You can limit the search to work against vernacular names only to avoid other hits like "Adler" being a virus or authorname:

https://api.gbif.org/v1/species/search?q=Adler
 vs 
https://api.gbif.org/v1/species/search?q=Adler&qField=VERNACULAR

Ordering unfortunately cannot be changed

**Comment by ManonGros** [comment]
Replied by email:
> The order of the names returned by the GBIF Species search API/UI depends on the type of field the information was found in. This blogpost contains some explanations with and example and a figure: https://data-blog.gbif.org/post/gbif-species-api/
> Unfortunately, the names cannot be ordered based on their distribution. You would have to work with the [occurrence search](https://www.gbif.org/occurrence/search?occurrence_status=present&q=) directly.
