### ISSUE TITLE
0 bytes download size

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2764]
**0 bytes download size**

This download shows

> File 0 Bytes Darwin Core Archive

also in the API:

"size": 0

I tried downloading the archive and the ZIP file is 233 KB

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/15243de3595e299d0d5ed3e6c91f779b:0a4bb53f5a72b1cefad5574437b5d2ab03622e9e1671aa43f63d3f4984e6ef21eeb43e3eaded428d0b164c9a74bce4d8de9a7ba3339b263b034aad025a55371b)
System: Chrome 81.0.4044 / Mac OS X 10.15.4
Referer: https://www.gbif.org/occurrence/download/0028826-190918142434337
Window size: width 1440 - height 637
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-06T06:46:41.375Z',mode:absolute,to:'2020-05-06T06:52:41.375Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-06T06:46:41.375Z',mode:absolute,to:'2020-05-06T06:52:41.375Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
@dnoesgaard the download no longer shows 0 bytes - I guess the bug was fixed. Ok if I close this issue?

**Comment by dnoesgaard** [comment]
Ok!
