### ISSUE TITLE
I have issues with basis of record. I am told invalid I do not know where error is

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2770]
**I have issues with basis of record. I am told invalid I do not know where error is**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/35c6e400963663fa3d2f865add166807:2b3a61c20db8e2c0d865988633078b179ae5317431370562a1007ebaa10b47893079cfe0b15ed0896921d2110d258c1dcadec89de79203ec7bda71ec93dfdd38)
System: Chrome 81.0.4044 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator/1580460393555
Window size: width 1280 - height 610
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-08T10:54:11.444Z',mode:absolute,to:'2020-05-08T11:00:11.444Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-08T10:54:11.444Z',mode:absolute,to:'2020-05-08T11:00:11.444Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email (CC helpdesk). Basis of record is missing.
