### ISSUE TITLE
taxonomic name authority not correct

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#2772]
in this case. https://www.gbif.org/species/163998346

The taxonomic name is `Centipeda minima Linneaus, 1758` which is not correct and should be `Centipeda minima (L.) A. Braun & Asch.` as we have it in TreatmentBank. http://treatment.plazi.org/id/0388E4CC-890F-CE53-8EAA-3610C873118B

Where does this change happen? Can you please help to find out so we can fix this? Is this something that happens on GBIF or the Plazi DWCA  import side?

This would be especially helpful, since these data sets include more than 9K linnaeus taxonomic names and their types. https://www.gbif.org/dataset/search?q=%2210.5281~2Fzenodo.291971%22

TX
Donat

![image](https://user-images.githubusercontent.com/4609956/81644473-14fdc700-9428-11ea-9921-87f6c09af542.png)

**Comment by thomasstjerne** [comment]
@mdoering it seems that a space in the author string prevents this one from mapping to the right species:
`Centipeda minima (L.) A. Braun & Asch.`
`Centipeda minima (L.) A.Braun & Asch.` -> https://www.gbif.org/species/5391292

**Comment by mdoering** [comment]
The space doesnt make any difference, at least not anymore:

http://api.dev.catalogue.life/parser/name?name=Centipeda%20minima%20(L.)%20A.%20Braun%20&%20Asch.

http://api.dev.catalogue.life/parser/name?name=Centipeda%20minima%20(L.)%20A.Braun%20&%20Asch.


BUT @myrmoteras the Plazi data comes in using `Centipeda minima Linneaus 1758` as the scientificName:
https://www.gbif.org/species/163998346/verbatim

The change happens on your side

**Comment by mdoering** [comment]
<img width="1021" alt="Screenshot 2020-05-19 at 10 13 31" src="https://user-images.githubusercontent.com/327505/82302094-6de5d600-99b9-11ea-857b-6e4dc9c4b691.png">
