### ISSUE TITLE
Mixed up language Japanese - Arabic

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/portal-feedback#2773]
When users choose "Japanese", many parts of the web site appear in Arabic. For example:

- https://www.gbif.org/ja/dataset/search
- https://www.gbif.org/ja/dataset/8a863029-f435-446a-821e-275f4f641165

**Comment by leo-buitrago** [comment]
thosoya1941@gmail.com you can follow the issue here

**Comment by MortenHofft** [comment]
I have currently no idea why, but the translation service have apparently confused languages in their commit
https://github.com/gbif/portal16/blob/master/locales/translations/ja/components/dataset.json

**Comment by MortenHofft** [comment]
Some of it is even in spanish! https://www.gbif.org/ja/user/profile

**Comment by MortenHofft** [comment]
Resyncing with Crowdin solved it. Crowdin had software issues that specific date and we were in contact with them.
