### ISSUE TITLE
Mycetophila ocultans Lundstrom, 1913 should be Mycetophila occultans Lundstrom, 1913

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#2774]
One of our users believes that Mycetophila ocultans Lundstrom, 1913 (https://www.gbif.org/species/5084968) should be Mycetophila oc**c**ultans Lundstrom, 1913.  

Also, Stigmatomeria obscurum (Winnertz, 1863) https://www.gbif.org/species/5979166 was originally described as Allodia obscura Winnertz, 1864. Stigmatomeria is female gender and thus the epithet should be obscura rather than obscurum.

Should I contact CoL directly regarding these corrections, or is this something GBIF can feed back about?

**Comment by rukayaj** [comment]
I've found the original description of _ Mycetophila occultans_ here, with the correct spelling https://www.biodiversitylibrary.org/page/56374417

**Comment by rukayaj** [comment]
Platyura lugubris (Zetterstedt, 1851) (https://www.gbif.org/species/1563668) should be moved to genus Orfelia, and was described as Platyura and should not have parentheses around the author when listed as Platyura. For placement in Orfelia see: http://sciaroidea.info/taxonomy/40514, and note that although listed as invalid there it has been reinstated in http://sciaroidea.info/node/26324

**Comment by yroskov** [comment]
Thanks! I have reported it to Thomas Pape, custodian of Systema Dipterorum. (Changes in the CoL can be made through correction in source database and new update of the checklist).

**Comment by rukayaj** [comment]
Thank you! There are some more corrections that have been sent through, but I think I found Thomas Pape's email so we can contact him directly.

**Comment by yroskov** [comment]
Great. This is the most optimal way. Thomas' contact email can be found here: https://www.iczn.org/about-the-iczn/commissioners/thomas-pape/
