### ISSUE TITLE
Many occurrence records for the chatham islands are in the wrong hemisphere!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2775]
**Many occurrence records for the chatham islands are in the wrong hemisphere!**

Kia ora. 

I recently downloaded a large number of weed occurrence records for NZ. As these are terrestrial weeds they should not be in the sea. However there is a significant cluster well out to sea east of banks peninsula.
Closer investigation revealed that these locations are all from the Chatham islands, but have decimal.longitude between 176 and 177. But as chathams sits in different hemisphere from the rest of NZ  the direction on the longitude should be negative.
I'ts a simple fix for the sub-set of the data of interest to me, but is likely more widespread in gbif records. The original records in my subset were mostly herbarium specimens from AK and CHR herbaria. I can chase up directly with curators if required.
Regards
Clayson Howell.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/59a722b037d027ed264b93be67493b0d:74597154b28cc8b397e03109217c5d0b08e0d52f0817b11d3c813de7a4cfa7af93c9527e205344d13376dd7cdea663414cab134a4220dcc6356795744867e5ee04f1fb3dadfa6da5dd7eac5a785f4248)
System: Chrome 80.0.3987 / Windows 7.0.0
Referer: https://www.gbif.org/
Window size: width 1430 - height 562
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-12T20:58:56.630Z',mode:absolute,to:'2020-05-12T21:04:56.630Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-12T20:58:56.630Z',mode:absolute,to:'2020-05-12T21:04:56.630Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email (and CCd here, but they don't seem to show up.)

It seems most likely this is incorrect data.
