### ISSUE TITLE
I am doing an assignment for a college course and my teacher wants me to find how many specimens of the genus Cervus are on this site, but I can't seem to find it. If you could let me know where to look that would be great, thanks

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2777]
**I am doing an assignment for a college course and my teacher wants me to find how many specimens of the genus Cervus are on this site, but I can&#39;t seem to find it. If you could let me know where to look that would be great, thanks**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/34333a89667cc3ed6143bd4bdbc383d3:3cac10c6a3abf7ce2a68f8445cbd205eda45b8679dacf2241aa86d27321581fcea6f19d6d4059afd727efbd07ff59908cba6a56d179a74ffe79909138d8b5d1b)
System: Chrome 81.0.4044 / Mac OS X 10.14.6
Referer: https://www.gbif.org/user/profile
Window size: width 972 - height 594
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-13T22:56:19.024Z',mode:absolute,to:'2020-05-13T23:02:19.024Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-13T22:56:19.024Z',mode:absolute,to:'2020-05-13T23:02:19.024Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
