### ISSUE TITLE
Flip decimal longitude to -84.85 to be correct

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2782]
**Flip decimal longitude to -84.85 to be correct**

GBIF is interpreting these coordinates incorrectly. This collector is a well known botanist in the southeastern USA. Ge collected a lot in  Florida and did not collect in China, ever. CollectionEnquiries@aucklandmuseum.com needs to flip the sign for the dec long value.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/dec0132481225e2844f038429b3f2e9c:511df521a00352a9ddd161f4f2588995746fb5e9c751d63ba0112125156c905a786e11e293d60233f4e436b9f4600dfb1a54083188d4538a094fca7f84c9f5fc)
System: Firefox 76.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1897806558
Window size: width 1240 - height 825
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-18T23:06:25.407Z',mode:absolute,to:'2020-05-18T23:12:25.407Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-18T23:06:25.407Z',mode:absolute,to:'2020-05-18T23:12:25.407Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 83ae84cf-88e4-4b5c-80b2-271a15a3e0fc
publishingOrgKey: 32e82a64-c9b4-4b2f-9fbd-d446309b973f

**Comment by MattBlissett** [comment]
Thanks @debpaul.

There are also records like https://www.gbif.org/occurrence/1897843373 with a countryCode of `"FJ, Comprises over 800 islands; area was settled by Austronesian-speaking people in 2nd millennium BCE; development of pottery by 1300 BCE; sighted by Dutch Tasman 1643, visited by British in 18th century; was haven for escaped convicts from Australia by 1804; official language is English, though most speak Bauan or Hindustani." ` (we'd like just `FJ`). Or https://www.gbif.org/occurrence/1897815094 

Where these country codes and names aren't in our lookup dictionary, we aren't sufficiently confident to flip the sign on a coordinate.  I'll add some to the dictionary, but hopefully the data can be fixed at source. (@leo-buitrago, could you contact them? There are thousands of records with location issues. Thanks.)

**Comment by leo-buitrago** [comment]
Sure @MattBlissett , I will contact the people from [Auckland Museum Botany Collection](https://www.gbif.org/dataset/83ae84cf-88e4-4b5c-80b2-271a15a3e0fc) about this occurrence and encourage them to fix all the location issues, as you pointed they have several geographic inconsistencies https://www.gbif.org/dataset/83ae84cf-88e4-4b5c-80b2-271a15a3e0fc/metrics. For cases like these https://www.gbif.org/occurrence/1897843373, https://www.gbif.org/occurrence/1897815094 they should use dwc:locationRemarks and assign a proper countryCode, or even left empty.

**Comment by jhnwllr** [comment]
Seems to be fixed now.
