### ISSUE TITLE
Download all species of Coleoptera in Europe in one batch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2785]
**Download all species of Coleoptera in Europe in one batch**

I would like to compare the full species list of European Coleoptera in GBIF with the full species list in a fossil database (BugsCEP). For the species missing in BugsCEP, I would like to download the distribution data from GBIF.

For this idea, I assume that all Coleoptersa species in Europe are registered in GBIF.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/dc26197656107b213e1ddc0e0951fc62:457f5cd274b75f0194aad56e1cd6ffda0cc4eff078182fe95e2e8dd3b88a892a3b9129e26f78704bd53eb3749fbb64af617af5e2c6c2ae7557ea3f570959a00beeb1b37b29c24b5e17a2f6b6a3f15b30)
System: Chrome 81.0.4044 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/search?q=
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-21T20:17:40.299Z',mode:absolute,to:'2020-05-21T20:23:40.299Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-21T20:17:40.299Z',mode:absolute,to:'2020-05-21T20:23:40.299Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
