### ISSUE TITLE
Environment Agency Eiseniella tetraedra Records (England) duplicated dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2786]
**Environment Agency Eiseniella tetraedra Records (England) duplicated dataset**

I'm the NBN contact for the Earthworm Society of Britain. I've noticed that one of our datasets is duplicated on our GBIF publisher profile.

The dataset in question is Environment Agency Eiseniella tetraedra Records (England).

Please can you remove the duplicate.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b23313d3ec1e02ad371784d299d4a587:0c89b3a591da3a0265dfce056c23bc83f1a32742d04564a5b294f0f7a44b6036eb60d9f108211d63c51d350db0a97106e51f8278180c2734200ed9387c64ca6fae373ccfd982eace2101cd97a04f8819)
System: Chrome 81.0.4044 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/0b8171d0-6b32-4ccc-bf3d-bf34b56c36d3
Window size: width 1707 - height 771
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-24T14:51:20.940Z',mode:absolute,to:'2020-05-24T14:57:20.940Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-24T14:51:20.940Z',mode:absolute,to:'2020-05-24T14:57:20.940Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ahahn-gbif** [comment]
@leo-buitrago  Seems this has been fixed, could you confirm/close?

**Comment by leo-buitrago** [comment]
Yes, the dataset was removed on May 27, see https://www.gbif.org/dataset/0f9edd36-b20e-4611-9ea6-67ff6313ce20
