### ISSUE TITLE
Missing accent mark in scientificName Authorship - GBIF Backbone

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/portal-feedback#2789]
The authorship for this scientific name in GBIF backbone https://www.gbif.org/species/4011666 has a missing accent mark. According  to the [reference taxon in CoL](http://www.catalogueoflife.org/col/details/species/id/0440a8636dd287a99e0a55a2d2942c8d) has to be "(Glaz. ex F**é**e)" instead of "(Glaz. ex Fee)".

**Comment by ManonGros** [comment]
Solved in the new backbone.
