### ISSUE TITLE
Missing umlaut in scientific Name Authorship - GBIF Backbone

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/portal-feedback#2790]
The authorship for this scientific name in GBIF backbone https://www.gbif.org/species/9157457 has a missing umlaut. According  to the [reference taxon](http://treatment.plazi.org/id/8F2387DD06740969FF31FBB2FD20FEFF) has to be "(_Naineris chilensis_ Hartmann-Schr**ö**der, 1965)" instead of "(_Naineris chilensis_ Hartmann-Schroder, 1965)".

**Comment by ManonGros** [comment]
Solved in the new backbone.
