### ISSUE TITLE
wrong taxonomic position

### ISSUE THREAD

**Issue by aallspac** [gbif/portal-feedback#2791]
The species: Leucon rossi Rehm, 2007 (https://www.gbif.org/species/9060730) is positioned under Porifera, but need to be positioned under Crustacea, family Leuconidae, Genus Leucon Krøyer, 1846 
(https://www.gbif.org/species/2215525).
The correct epithet is as follows:
Leucon rossi Rehm & Heard 2008

**Comment by ManonGros** [comment]
It seems that this species is no longer in the GBIF backbone but the genus Leucon Krøyer, 1846 (https://www.gbif.org/species/2215525) has the correct taxonomy.
