### ISSUE TITLE
GBIF password for IPT registration

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2793]
**GBIF password for IPT registration**

Dear colleagues. I am respondible for IPT installation in Yugra State University, Russia (http://ipt.ugrasu.ru:8080/ipt/). A newly registered organization (https://www.gbif.org/publisher/858f9c4c-942e-4b66-96b3-97b5170043a3) will be hosted on our IPT. Please, would you be kind to send me the password to proceed with IPT registration of this organization. Sincerely, Nina Filippova.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5758d3a72e3007161b5c80c8485ee8f3:cd030c4bde162c56fcdefb016b4a2d87ca1a95b2d3542e94db27b6bff9161d3d289062023958d5f51c3b8ef62462ee467e35359c39ecef81bb91987a95784b56)
System: Chrome 81.0.4044 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1396 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-27T07:22:09.623Z',mode:absolute,to:'2020-05-27T07:28:09.623Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-27T07:22:09.623Z',mode:absolute,to:'2020-05-27T07:28:09.623Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
Token sent.
