### ISSUE TITLE
Make projectID clickable

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2798]
**Make projectID clickable**

Datasets have a separate tab for project information, with the projectID mentioned in gray letters at the top. Since GBIF allows to search on projectID, I would make this grey text a link to the search for that project.

E.g. on https://www.gbif.org/dataset/63938753-1fec-4c08-ae39-e9f8a6576521/project

Link to: https://www.gbif.org/dataset/search?project_id=meetnetten.be

-----

Github user: @peterdesmet
User: [See in registry](https://www.gbif.org/api/feedback/user/a0396e9fefba141146d5b7752db5753f:becbcab3fbf3b99882d4a1d4952e37ddf50517645fa9be5ab6a461d4a85ccfb28a61b1b7c7b68687fa7da04e68b818cb788f4ad41f11e385ceabb10002fffaa0)
System: Chrome 81.0.4044 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/63938753-1fec-4c08-ae39-e9f8a6576521/project
Window size: width 1018 - height 717
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-29T12:47:09.607Z',mode:absolute,to:'2020-05-29T12:53:09.607Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-29T12:47:09.607Z',mode:absolute,to:'2020-05-29T12:53:09.607Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by peterdesmet** [comment]
<img width="1018" alt="Screenshot 2020-05-29 at 14 50 15" src="https://user-images.githubusercontent.com/600993/83261670-06e7ce80-a1bc-11ea-9a2a-ae240f6a9e1a.png">

**Comment by MortenHofft** [comment]
Hi Peter
I believe this field was introduced with specifically capacity enhancement programme and projects in mind. At least I have been under that impression, so it [does link](https://www.gbif.org/dataset/c3413793-cd8e-4f74-b0b7-e1f0c155102c/project) to [prose pages](https://www.gbif.org/project/83239/improving-biodiversity-data-accessibility-in-trinidad-and-tobago-barbados-and-suriname) describing the project when there is such a page.
I didn't know it was also used by other.

It is a good idea to use dataset search as a fallback.

Thanks
