### ISSUE TITLE
COORDINATE_ACCURACY_INVALID deprecated?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2799]
**COORDINATE_ACCURACY_INVALID deprecated?**

I have a question from a translator on this issue. It appears it has been deprecated and is no longer in use? Can someone verify? And if so, we should remove it from the translation file (occurrenceIssue.json)

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/7bbe431a5882b155f4a362d069bdba23:f2f87e90d4b61489b528b73bd27da746b0f57a2444e55d864949375d0f1d6a2ac3ab22bba9dbe53f9e27c22fed4ad5c7161d7383073aeb6c0a731abb9d1b350b)
System: Chrome 81.0.4044 / Mac OS X 10.15.4
Referer: https://www.gbif.org/occurrence/search?issue=COORDINATE_ACCURACY_INVALID
Window size: width 1440 - height 641
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-02T09:15:02.609Z',mode:absolute,to:'2020-06-02T09:21:02.609Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-02T09:15:02.609Z',mode:absolute,to:'2020-06-02T09:21:02.609Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
There are 8 occurrences issue types that have zero occurrences. It could just as well be because there are no offenders I guess.

>It appears it has been deprecated

Have it been deprecated @muttcg ?

**Comment by MattBlissett** [comment]
Only COORDINATE_ACCURACY_INVALID is deprecated, as the GBIF term coordinateAccuracy is itself deprecated.  Darwin Core includes coordinatePrecision and coordinateUncertaintyInMeters.

The other issues either have no records, or are not set by the current interpretation but could be used in the future.

**Comment by MortenHofft** [comment]
It is still in http://api.gbif.org/v1/enumeration/basic/OccurrenceIssue
Should it be removed then?

**Comment by MattBlissett** [comment]
In general for the V1 API, we don't remove things, we just stop using them.

**Comment by MortenHofft** [comment]
> In general for the V1 API, we don't remove things, we just stop using them.

Hmm, I'm not convinced that otherwise fine principle applies very well to the values of an enumeration. Isn't adding something to an enumeration as breaking as removing a value? 

Anyway, then we should stop using the enumeration API in web projects I guess. The downside of that is that we do not get new terms added automatically. Hmm - I'll remove it and consider how to do it going forward. I'll probably go back to have the various web projects have their own curated copies. It also makes it easier to control translations.
