### ISSUE TITLE
Bonjour depuis ce matin les liens vers le TAXREF ne sont plus affichés par exemple.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2800]
**Bonjour depuis ce matin les liens vers le TAXREF ne sont plus affichés par exemple.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/98353116fc78f7cce4425d165714b0dd:cc2055bd911c91e2d5790d98087cef359979d2bbf3a1892f9effd0193dc49a7c14d6de5874e2be155f67de5ebc006020de76f499beb11b51779bd58b4157bc61)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/fr/species/5115818?occurrenceDatasetOffset=30
Window size: width 1920 - height 975
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-02T12:02:00.321Z',mode:absolute,to:'2020-06-02T12:08:00.321Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-02T12:02:00.321Z',mode:absolute,to:'2020-06-02T12:08:00.321Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Google translate
> Hello since this morning, the links to TAXREF are no longer displayed, for example.

**Comment by ManonGros** [comment]
I don't see any issue with the TAXREF links. Could someone else check (just in case) and close the issue if all is good?
