### ISSUE TITLE
dates not translated

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2803]
**dates not translated**

`LAST CRAWLED SEPTEMBER 8, 2019` the date is not translated

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/b248b0a94b453baa9bb371435e77d48e:1ec68b648297658cc07f96643aeb7ae38bc4aee59a985a6dad7834d44c0ef884fff49c9ad70c53e2df1e23abe307cd0292a71c871c8f256fce2e77a310a5a2ab)
System: Chrome 83.0.4103 / Mac OS X 10.14.6
Referer: https://www.gbif.org/species/100236890/verbatim
Window size: width 1082 - height 766
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-03T07:15:44.184Z',mode:absolute,to:'2020-06-03T07:21:44.184Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-03T07:15:44.184Z',mode:absolute,to:'2020-06-03T07:21:44.184Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
relates to https://github.com/gbif/portal16/issues/1361
