### ISSUE TITLE
GBIF password for IPT registration of an organization

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2805]
**Dear colleagues, another GBIF password is requred to register the organization on our IPT. Please, provide the password for `https://www.gbif.org/publisher/d86fda91-d43c-4707-a40c-1c783bfbdedd.` Sincerely, Nina.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/322ed899a119ba5d40dcaf1f2449ad29:5fcdf5e851c9ef215a7529a4397461eb6a3dd2b96c4875f06c96ab124979e1def0115451e4914afae43192e23c3c364fdad064a25557bcf5134980e0503e33f8)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1396 - height 612
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-04T10:28:35.417Z',mode:absolute,to:'2020-06-04T10:34:35.417Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-04T10:28:35.417Z',mode:absolute,to:'2020-06-04T10:34:35.417Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
Token sent.
