### ISSUE TITLE
Dataset logo cached?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2806]
**Dataset logo cached?**

Are dataset logos cached? For https://www.gbif.org/dataset/b7ee2a4d-8e10-410f-a951-a7f032678ffe we have updated the logo to:

https://ipt.inbo.be/logo.do?r=mica-legacy-occurrences

The dataset page still shows the general "Research institute" logo from:

https://api.gbif.org/v1/image/unsafe/https://ipt.inbo.be/logo.do?r=mica-legacy-occurrences

-----

Github user: @peterdesmet
User: [See in registry](https://www.gbif.org/api/feedback/user/56e8d9b4e1de7e4fb76c85a60b144cf8:a5c3796e40bb95d3ccdd32ccf39004ac9ef48fbe35af9cd5e9230668daec4abd6b9c09dad34800a37604033fb714ce8f0a236d7bbedd235dd35346ec2681b2d7)
System: Chrome 83.0.4103 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/b7ee2a4d-8e10-410f-a951-a7f032678ffe
Window size: width 1367 - height 717
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-04T11:23:08.193Z',mode:absolute,to:'2020-06-04T11:29:08.193Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-04T11:23:08.193Z',mode:absolute,to:'2020-06-04T11:29:08.193Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Yes, they are cached the same way occurrence images are cached.

IPTs can go offline, so the cache is very long. I've cleared it for this image.
