### ISSUE TITLE
there is no documents yet

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#281]
**there is no documents yet**

documents are linked all over - we need to transfer those that are deemed worty and create a contenttype for them and expose them in the ES index and the website

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb
Reported by: @mortenhofft
System: Chrome 59.0.3071 / Mac OS X 10.11.6
Referer: https://www.gbif-uat.org/resource/search
Window size: width 1921 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-04T12:07:14.896Z',mode:absolute,to:'2017-08-04T12:13:14.896Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-04T12:07:14.896Z',mode:absolute,to:'2017-08-04T12:13:14.896Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Documents to test with
http://www.gbif.org/resource/83029
http://www.gbif.org/resource/82873
http://www.gbif.org/resource/81771
http://www.gbif.org/resource/80813
which is also in Russian:
http://www.gbif.org/resource/82278

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/416
