### ISSUE TITLE
This sample of Sesleria coerulans comes from Romania

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2813]
**This sample of Sesleria coerulans comes from Romania**

This sample of Sesleria coerulans comes from Romania, collected in Transylvania, a region today belonging to Romania not to Ungary.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ad37f9c695a8901a0af357f4f05ff925:697a2b24dfdadc3a680ebd62a360e98fecd1aec6800aac16f11cec96dde671ca08e82b40d822641cbbe5ea384461e9004d40b8ada4923e4ce0945ed3e2795ca5)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/occurrence/2513639420
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-08T09:35:11.315Z',mode:absolute,to:'2020-06-08T09:41:11.315Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-08T09:35:11.315Z',mode:absolute,to:'2020-06-08T09:41:11.315Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO
datasetKey: 15f819bd-6612-4447-854b-14d12ee1022d
publishingOrgKey: 396d5f30-dea9-11db-8ab4-b8a03c50a862

**Comment by ManonGros** [comment]
The country now shows Romania.
