### ISSUE TITLE
Error 500 when I tried to logged

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2815]
**Error 500 when I tried to logged**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bcc6f0a1bc6e6ae022538e84f8614365:585ae331a3e5be9ede1839462d6d3101c5d8a1f624f2afded259e4f960b1498a20eccb4152e60bd0cf82715503ba5114e1b15db6b392ec74adf3f58dd61ad69d)
System: Chrome 83.0.4103 / Windows 10.0.0
Window size: width 1366 - height 663
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-08T12:56:40.457Z',mode:absolute,to:'2020-06-08T13:02:40.457Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-08T12:56:40.457Z',mode:absolute,to:'2020-06-08T13:02:40.457Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Login with Google does not work for me either
