### ISSUE TITLE
Can we prevent over-precise eventDates being generated in interpretation?

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/portal-feedback#2816]
We have a long-standing issue in the handling of incomplete dates received from occurrence data. The data transfer formats follow ISO-8601, which allows to omit information "from the right" of the string: a date can be supplied as 2017-02-25, but also as 2017-02 (no day), or 2017 (only the year is known). On processing, this gets padded with wrong precision, so that 2017-02 becomes 2017-02-01, and 2017 becomes 2017-01-01. This is clearly factually wrong, and leads to over-reporting not only for the first day of the year, but also for the first of each month, leading to odd spikes in record volumes for these dates (see, e.g., the trends for records and species "by day of year" at https://www.gbif.org/analytics/global). 

For a user, it would at this point in time be safer to consult the original values (the information contained in the "verbatim" section of a DwC-A download). Much better, though, would be to prevent this padding of dates that leads to false precision.

some points to check:
- required:  a parser that can handle this case without affecting other, more obvious cases (e.g. DD vs YY vs MM being ambiguous)
- data structure: could it handle incomplete dates?
- search API issue: the current state is not sufficient to consider those partial dates

**Comment by MattBlissett** [comment]
This is fixed and deployed.

Some smaller changes remain, e.g. handling missing published month/day values where a year is provided.
