### ISSUE TITLE
The "your account has been updated" pop-up has a typo and reads: "your account have been updated"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2818]
**The &quot;your account has been updated&quot; pop-up has a typo and reads: &quot;your account have been updated&quot;**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/63e29523326a8a8fc24ed7b775236bb3:cc523ca93cd8ca7e8630fd2a2091c78ea9d94187f49b8c7e4e9d7de89c68d1894f7cc87eeed3b4f8ad25287b48df29d179daf0139c38825e57ff1a9d459e42b1)
System: Chrome 83.0.4103 / Mac OS X 10.12.6
Referer: https://www.gbif.org/user/profile
Window size: width 1440 - height 744
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-10T21:03:01.186Z',mode:absolute,to:'2020-06-10T21:09:01.186Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-10T21:03:01.186Z',mode:absolute,to:'2020-06-10T21:09:01.186Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Corrected in https://crowdin.com/translate/gbif-portal-en/159/endk-en#11105
