### ISSUE TITLE
literature citations download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2819]
**literature citations download**

Hello!

My institution (Royal British Columbia Museum) has a few datasets uploaded to GBIF and we're wondering if it's possible  to download the citations for the literature that used our data?  

Many thanks,

Chris

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8fff39f69ff3418fdbb23f2fadc38a5f:bf7a0ad761cca5fd665454340b69d340eac32c2febf7dc4cd6bf6e0bdb7649bc3f84df82e38ad93468b978ba7f189e503481a16a5424bff6fb29d85f32769eb4)
System: Chrome 81.0.4044 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?contentType=literature&publishingOrganizationKey=cc6110c7-f75c-47c8-8931-f7dd3f324777
Window size: width 1440 - height 757
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-11T15:14:48.091Z',mode:absolute,to:'2020-06-11T15:20:48.091Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-11T15:14:48.091Z',mode:absolute,to:'2020-06-11T15:20:48.091Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
> answered by email

Hi 
Regarding literature tracking

The API is not guaranteed stable, but I don’t imagine it will change a lot. But be aware before you integrate it into a larger product. If so we should talk more about stability.

Here are some examples of usage

Search for any literature item, go to page 3 show 10 items
https://www.gbif.org/api/resource/search?contentType=literature&offset=20&limit=10

Literature, no results but breakdown of 10 most frequent countries of the researcher
https://www.gbif.org/api/resource/search?contentType=literature&limit=0&facet=countriesOfResearcher

Literature from Portugal, breakdown on covered countries
https://www.gbif.org/api/resource/search?contentType=literature&limit=0&countriesOfResearcher=PT&facet=countriesOfCoverage

Known literature usages of the dataset https://www.gbif.org/dataset/231c5bcf-1b56-4905-a398-6d0e18f6de1a
https://www.gbif.org/api/resource/search?contentType=literature&gbifDatasetKey=231c5bcf-1b56-4905-a398-6d0e18f6de1a

Known literature from either of two publishers. If a citation is using datasets from both publishers the literature item will only count once.
https://www.gbif.org/api/resource/search?contentType=literature&publishingOrganizationKey=16e26fb0-7f13-4ae2-b57c-2543f451f5b3&publishingOrganizationKey=d1805d75-066e-42d6-8cab-1c0d30323db3

For the technical minded you can also see the calls made by looking at the network activity on the website
https://www.gbif.org/resource/search?contentType=literature&countriesOfResearcher=PT&gbifDatasetKey=231c5bcf-1b56-4905-a398-6d0e18f6de1a&gbifDatasetKey=79673413-746f-48f2-bd8a-7cf27807317e

Hope that it helps – else let us know.
