### ISSUE TITLE
I see this species listed with the specific epithet "littoralis" with two ts rather than one, and I know this word is typically spelled with two ts.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2820]
**I see this species listed with the specific epithet &quot;littoralis&quot; with two ts rather than one, and I know this word is typically spelled with two ts.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6b559fc546fee20cc3a75714b1e44450:4d8a9cf398eb1e657159647fceb4d81503a13ba10a059b036179d02850ddbfab4f50760e61bdfb6a9cd818d3c3c0c4126f160bdaed3db9ed67873415a3c68828)
System: Chrome 83.0.4103 / Mac OS X 10.11.6
Referer: https://www.gbif.org/species/3695619
Window size: width 1266 - height 613
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-11T20:06:05.605Z',mode:absolute,to:'2020-06-11T20:12:05.605Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-11T20:06:05.605Z',mode:absolute,to:'2020-06-11T20:12:05.605Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ahahn-gbif** [comment]
Can no longer reproduce - the epithet is given as "litoralis". If this refers to two of the checklist datasets further down the page, then please be aware that it gives the spelling at source, which may well include spelling variants / typos.
