### ISSUE TITLE
S. minutifolia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2822]
**S. minutifolia**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/74b508d89c966099c004b3e06f305f1c:7e0c63758270c78f0f0b626c575b0abbe1323c9e323d0b58e6a26e274cc8982a165c586e4ed8d356daa9ffc883a2c56abd3d3815cad1c0e6422aec3dfc60e6d6)
System: Opera 68.0.3618 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0084386-200221144449610
Window size: width 1536 - height 754
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-12T06:47:34.104Z',mode:absolute,to:'2020-06-12T06:53:34.104Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-12T06:47:34.104Z',mode:absolute,to:'2020-06-12T06:53:34.104Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ahahn-gbif** [comment]
It is unclear what the question is. The referring page leads to a download that was cancelled. A rerun (https://www.gbif.org/occurrence/download/0022878-200613084148143) retrieved 29 records from 6 datasets for Selaginella minutifolia.
