### ISSUE TITLE
Synonymization / identification conflicts between Geomys bursarius llanensis and Geomys texensis llanensis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2824]
**I noticed that Geomys bursarius llanensis is being renamed Geomys texensis llanensis in GBIF. There have been several taxonomic changes over the years since Bailey gave this name in 1905, but some specimens are incorrect. For example:**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c448eaa00a45e69a46bc3a769d867add:160feae733611e48c1fd1e90856b542d263ef3a2932c15026f2d7b5f32f92f51b15321b5863a5264f7d92ffa1a4468dff57f285dbb415a36aa4ad199151a98cd)
System: Firefox 77.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/583463275
Window size: width 1536 - height 722
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-13T19:20:58.725Z',mode:absolute,to:'2020-06-13T19:26:58.725Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-13T19:20:58.725Z',mode:absolute,to:'2020-06-13T19:26:58.725Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 6ce7290f-47f6-4046-8356-371f5b6749df
publishingOrgKey: 66522820-055c-11d8-b84e-b8a03c50a862

**Comment by rspfau** [comment]
I noticed that Geomys bursarius llanensis is being renamed Geomys texensis llanensis in GBIF. There have been several taxonomic changes over the years since Bailey gave this name in 1905, but some specimens are incorrect. For example: https://www.gbif.org/occurrence/583463275. This is definitely Geomys bursarius and not G. texensis. The museum where this specimen is housed has the name correct, but it's changed to G. texensis here on GBIF

**Comment by rspfau** [comment]
Here's another instance of that happening:
https://www.gbif.org/occurrence/1145127404

**Comment by ahahn-gbif** [comment]
In both examples, GBIF retains the Geomys bursarius subsp. llanensis Bailey, 1905 of the original in the interpreted version (see page header and table at the bottom), but synonymizes this with Geomys texensis llanensis Bailey, 1905  in the "accepted name". The source for this is the Catalogue of Life (https://www.gbif.org/species/8768115), which in turn cites ITIS as the source (http://www.catalogueoflife.org/col/details/species/id/0ef26268b3f3fd3ca3150ccac1874498/synonym/c5eb07f01aec6244043b218f04f007a3). We will need to forward this to the Catalogue of Life editors.
