### ISSUE TITLE
download species data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2825]
**download species data**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c4854e5ecfc85205ea88a4043669277a:78e298e863bee0bb1d346d6531b833fe49c55d6e972c3ccbbc24c4f22130ebcd49375ba43dcd8d3b78fb744b733205675189e838717a6e468d4a4668879a68e4)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0001664-200613084148143
Window size: width 1920 - height 920
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-15T14:40:39.786Z',mode:absolute,to:'2020-06-15T14:46:39.786Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-15T14:40:39.786Z',mode:absolute,to:'2020-06-15T14:46:39.786Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
question unclear

**Comment by ahahn-gbif** [comment]
The referenced download finished successfully on June 15th. Issue assumed closed.
