### ISSUE TITLE
Herbier de Wallis et Futuna

### ISSUE THREAD

**Issue by jhnwllr** [gbif/portal-feedback#2826]
The dataset **Herbier de Wallis et Futuna** needs to have a default value set for its country (WF) or the publisher needs to add a negative sign to the decimallatitude. 

https://www.gbif.org/dataset/75e787b4-14c4-4040-9bd8-477d343e3a91
https://registry.gbif.org/dataset/75e787b4-14c4-4040-9bd8-477d343e3a91/defaultValue

As was done for this dataset: 
https://registry.gbif.org/dataset/cc9bd573-9c96-4532-a723-52ce1d155b36/defaultValue

**Comment by ahahn-gbif** [comment]
first mail bounced (contact no longer functional)

**Comment by jhnwllr** [comment]
So I think we should set the default value then.

**Comment by ahahn-gbif** [comment]
one more attempt to the publisher - it appears we have an updated address there, but the local metadata of dataset still carry the old one

**Comment by jhnwllr** [comment]
I am now setting the default value countryCode = WF and country = Wallis and Futana since the publisher emails bounced.

**Comment by jhnwllr** [comment]
default value set
