### ISSUE TITLE
Changes requested by Ward Appeltans

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2827]
**Changes requested by Ward Appeltans**

changes to this page?
https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6

1/ replace Biogeographic to Biodiversity in the name
2/ replace the link to the OBIS website to https://obis.org/about/ (we moved from iobis.org to obis.org)

Some OBIS nodes may ask you to correct their names as well.

I also hope we can get the numbers correct, because 9M records is way too low.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/a3e909151cdc5cdab9afe0a8b96fd021:b338ff830dc42cc50eb0532a4f6d659713d5d5c6164af6fd75af541ce8cb7b6d99441f9f923e5ebf84ce8684f0015fd11925f878de784fee64ea717dbc2ee64b)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-17T10:45:25.936Z',mode:absolute,to:'2020-06-17T10:51:25.936Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-17T10:45:25.936Z',mode:absolute,to:'2020-06-17T10:51:25.936Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
Issue as requested by e-mail from Ward @timhirsch @kcopas @ahahn-gbif

**Comment by kcopas** [comment]
Name changes in Contentful and registry (awaiting refresh?)

Link corrected in text from Contentful.

**Comment by ahahn-gbif** [comment]
The network page did catch up on the update now (https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6).

Concerning the record numbers: a few years back, we deleted a large batch of records/datasets on request from OBIS, concerning mostly EurOBIS. As these datasets are re-registered and added to the network entry, we should also see the numbers go up again. A check for newly registered datasets does not show any more recent additions pending though.

**Comment by MattBlissett** [comment]
The "Node" links ("AntOBIS" etc) go to their old website, and now just redirect to the home page of the new one.

I removed the hidden, old logo, which was causing the security warning on this page.

**Comment by pieterprovoost** [comment]
@MattBlissett Here's an up-to-date list of OBIS nodes: https://api.obis.org/node

**Comment by ahahn-gbif** [comment]
No action point, just for some clarity as we have different components here:
- the network page (https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6) is static, authored content (content management system), and as such needs an editor to update information. We recognize it got a bit stale and needs to be updated - checking options for giving access to OBIS to curate
- the "network" tab behind that page (https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6/dataset) is based on an explicit mapping of datasets to the network, curated in a table in the registry. Again, we would like to find better and more dynamic ways to curate. Due to the concept of a "network" (bracketing individual datasets across a range of publishers, but usually only a subset of their datasets), this mapping has to be done per dataset, not per GBIF publisher (= OBIS node)
- while OBIS nodes can be listed in the authored content of the network page without being registered with GBIF, the linking of datasets to the network requires that the OBIS Node is registered as a publishing institution with GBIF, and publishes the datasets to GBIF. GBIF-external datasets cannot be shown here.

**Comment by dnoesgaard** [comment]
I can easily import the data on nodes from the API, e.g.

| Name                                                                                                            | Type        | Theme                                                    |
|-----------------------------------------------------------------------------------------------------------------|-------------|----------------------------------------------------------|
| [AfrOBIS](https://obis.org/node/14fc439c-707d-41d6-a3d4-b9d2696205fe)                                           | regional    | Sub-Saharan African OBIS node                            |
| [Antarctic OBIS](http://www.biodiversity.aq/)                                                                   | regional    |                                                          |
| [Arctic OBIS](https://www.abds.is/)                                                                             | regional    |                                                          |
| [Caribbean OBIS]()                                                                                              | regional    |                                                          |
| [ESP OBIS](http://ron.udec.cl/)                                                                                 | regional    | Tropical and Subtropical Eastern South Pacific OBIS node |

but linking to GBIF publishers is manual and time-consuming. Suggestions?

**Comment by ahahn-gbif** [comment]
For the OBIS network page, the list of Nodes is the relevant information. DP will then need to link datasets (not publishers) to the OBIS network table - if you extracted the list of publishers anyway, we would be happy to take that on from there. Yes - manual and time-consuming.

**Comment by dnoesgaard** [comment]
In that case, is the above format ok—Name, Type, Theme?

**Comment by ahahn-gbif** [comment]
Is it possible to continue with the same information / structure that is currently showing under "OBIS nodes in GBIF" at https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6?

**Comment by dnoesgaard** [comment]
Not if I'm to use the OBIS API. The current list was (painfully) put together manually. Creating one from the API, however, takes 10 seconds...

**Comment by ahahn-gbif** [comment]
I see, thanks. Can we then update the table based on the OBIS API, please, and maintain backup of the previous version? I agree that the manual edits are not sustainable in the long run

**Comment by dnoesgaard** [comment]
Done.

Here's the previous version for your records:

| Region                                          | Node                                                                 | Host                                                                                                                                       | GBIF publisher                                                                                                                                   |
|-------------------------------------------------|----------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|
| Antarctica                                      | [AntOBIS](http://www.iobis.org/explore/#/node/3)                     | [Biodiversity and Ecosystems Data and Information Centre (BEDIC), Royal Belgian Institute of Natural Sciences](http://www.biodiversity.aq) | [SCAR - AntOBIS](https://www.gbif.org/publisher/104e9c96-791b-4f14-978c-f581cb214912)                                                            |
| Arctic                                          | [Arctic OBIS](http://www.iobis.org/explore/#/node/28)                | [Conservation of Arctic Flora and Fauna (CAFF), Iceland](http://www.caff.is/)                                                              | [Conservation of Arctic Flora and Fauna](https://www.gbif.org/publisher/44862593-2fdd-4491-ab79-b500b8272aac)                                    |
| Argentina                                       | [ArOBIS](http://www.iobis.org/explore/#/node/1)                      | [Centro Nacional Patagónico (CENPAT) CONICET](http://arobis.cenpat-conicet.gob.ar/)                                                        | [ArOBIS Centro Nacional Patagónico](https://www.gbif.org/publisher/d6bc1312-f24f-4258-b117-a13243b915ff)                                         |
| Australia                                       | [OBIS Australia](http://www.iobis.org/explore/#/node/8)              | [Commonwealth Scientific and Industrial Research Organisation (CSIRO)](http://www.cmar.csiro.au/)                                          | [Australian Ocean Biogeographic Information System (OBIS Australia)](https://www.gbif.org/publisher/2174414a-9b2a-4774-85f1-2a9c54c28ca9)        |
| Black Sea                                       | [OBIS Black Sea](http://www.iobis.org/explore/#/node/21)             | [Ukrainian Scientific Centre of Ecology of the Sea](http://www.sea.gov.ua/)                                                                | []()                                                                                                                                             |
| Canada                                          | [OBIS Canada](http://www.iobis.org/explore/#/node/9)                 | [Centre of Marine Biodiversity, Bedford Institute of Oceanography](http://www.marinebiodiversity.ca/)                                      | [Canadian node of the Ocean Biogeographic Information System (OBIS Canada)](https://www.gbif.org/publisher/09a9c196-cb5b-4fa1-afc2-3499b868b225) |
| Caribbean                                       | [Caribbean OBIS](http://www.iobis.org/explore/#/node/23)             | [Universidad Simón Bolívar - Centro de Biodiversidad Marina](http://cbm.usb.ve/sv/lsr)                                                     | [Caribbean OBIS Node](https://www.gbif.org/publisher/1e9400fa-ce73-4737-9eaa-f25df148945c)                                                       |
| China                                           | [OBIS China](http://www.iobis.org/explore/#/node/10)                 | [Department of Marine Organism Taxonomy &amp; Phylogeny, Institute of Oceanology, Chinese Academy of Sciences](http://www.qdio.ac.cn/)     | []()                                                                                                                                             |
| Colombia                                        | [OBIS Colombia](http://www.iobis.org/explore/#/node/)                | [The Marine and Coastal Research Institute of Colombia (INVEMAR)](http://siam.invemar.org.co/sibm)                                         | []()                                                                                                                                             |
| CPPS - South Pacific                            | [OBIS CPPS](http://www.iobis.org/explore/#/node/)                    | [Comisión Permanente Pacifico Sur](http://www.cpps-int.org)                                                                                | []()                                                                                                                                             |
| Europe                                          | [EurOBIS](http://www.iobis.org/explore/#/node/5)                     | [Vlaams Instituut voor de Zee (VLIZ)](http://www.eurobis.eu/)                                                                              | []()                                                                                                                                             |
| Indian Ocean                                    | [IndOBIS](http://www.iobis.org/explore/#/node/6)                     | [Centre for Marine Living Resources and the Environment, Ministry of Eart Sciences, India](http://www.cmlre.gov.in/)                       | []()                                                                                                                                             |
| Japan                                           | [OBIS Japan](http://www.iobis.org/explore/#/node/14)                 | [Japan agency for Marine-Earth Science and Technology](http://www.godac.jamstec.go.jp/j-obis/j/index.html)                                 | []()                                                                                                                                             |
| Korea                                           | [KOBIS](http://www.iobis.org/explore/#/node/7)                       | [Korea Institute of Ocean Science and Technology](http://kobis.kiost.ac.kr/kobis/main_en)                                                  | []()                                                                                                                                             |
| Malaysia                                        | [OBIS Malaysia](http://www.iobis.org/explore/#/node/)                | [Institute of Oceanography and Environment (INOS) of the University of Malaysia, Terengganu](http://inos.umt.edu.my/?lang=en)              | []()                                                                                                                                             |
| Mediterranean                                   | [MedOBIS](http://www.iobis.org/explore/#/node/24)                    | [Hellenic Centre for Marine Research](https://portal.lifewatchgreece.eu/)                                                                  | [Hellenic Center for Marine Research](https://www.gbif.org/publisher/96d7ceab-ce9f-4c8a-8d3a-448a5637094a)                                       |
| Persian Gulf and Gulf of Oman                   | [PEGO-OBIS](http://www.iobis.org/explore/#/node/)                    | [Iranian National Institute for Oceanography (INIO)](http://www.inio.ac.ir/)                                                               | []()                                                                                                                                             |
| Senegal                                         | [OBIS Senegal](http://www.iobis.org/explore/#/node/30)               | [Centre De Recherches Océanographiques Dakar-Thiaroye (C.R.O.D.T)](http://oregonstate.edu/dept/oird/temp/irn/senegal/Crodt.htm)            | []()                                                                                                                                             |
| South-East Asia                                 | [SEAOBIS](http://www.iobis.org/explore/#/node/25)                    | [ASEAN Centre for Biodiversity](http://www.aseanbiodiversity.org/)                                                                         | []()                                                                                                                                             |
| South-West Pacific                              | [South Western Pacific OBIS](http://www.iobis.org/explore/#/node/11) | [National Institute of Water &amp; Atmospheric Research](http://nzobis.niwa.co.nz/)                                                        | [Southwestern Pacific Ocean Biogeographic Information System (OBIS) Node](https://www.gbif.org/publisher/1c9c3bb4-377c-4547-aa79-16ea755d6006)   |
| Sub-Saharan Africa                              | [AfrOBIS](http://www.iobis.org/explore/#/node/2)                     | [Southern African Data Centre for Oceanography](http://afrobis.csir.co.za/)                                                                | []()                                                                                                                                             |
| Tropical and Subtropical Eastern South Pacific  | [ESPOBIS](http://www.iobis.org/explore/#/node/4)                     | [FONDAP COPAS](http://ron.udec.cl/)                                                                                                        | []()                                                                                                                                             |
| Tropical and Subtropical Western South Atlantic | [WSAOBIS](http://www.iobis.org/explore/#/node/13)                    | [University of São Paulo](http://obisbr.cria.org.br/)                                                                                      | []()                                                                                                                                             |
| UK                                              | [OBIS UK](http://www.iobis.org/explore/#/node/)                      | [The Marine Biological Association of the United Kingdom](http://www.mba.ac.uk/)                                                           | []()                                                                                                                                             |
| USA                                             | [OBIS-USA](http://www.iobis.org/explore/#/node/12)                   | [US Geological Survey](http://www.usgs.gov/obis-usa/)                                                                                      | []()                                                                                                                                             |

**Comment by wardappeltans** [comment]
Can GBIF and @pieterprovoost think of an automated way to assign the "OBIS network" to datasets from OBIS nodes?

**Comment by ahahn-gbif** [comment]
I suspect this will remain semi-automatic, but to make the process smoother, it would be helpful to have a list of those GBIF-registered entities (publishers or installations: name and UUID) under which we can assume all published datasets to be OBIS-datasets. We could then define a process to trawl these entities periodically, and add all datasets to the network that are new since the last check. 

For EurOBIS, for example, we would need to manage the information that the GBIF entry corresponding to the OBIS Node is called "Flanders Marine Institute" (https://www.gbif.org/publisher/2089ce96-4fb5-4a20-999c-3ccf45a27a4d), and is of type publisher, but that only those, and all those, datasets behind the "European Ocean Biodiversity Information System (EurOBIS)" installation (https://www.gbif.org/installation/f9df6cff-21d4-4d4b-8da4-eda454f5a086), not the other one, should be hooked up to the network.

Also keep in mind that this kind of trawl would not work for entry points that serve both OBIS and non-OBIS datasets through a single installation, if such cases exist - these would still require individual, explicit network registration.

**Comment by wardappeltans** [comment]
@ahahn-gbif, i was more thinking like a script that compares the DwC-A URLs in OBIS with GBIF via the OBIS API? But not sure if that is possible...

**Comment by MattBlissett** [comment]
> but linking [OBIS notes] to GBIF publishers is manual and time-consuming. Suggestions?

To do this properly, you'd add an additional identifier to the publishing organization, as I've done here: https://registry.gbif.org/organization/104e9c96-791b-4f14-978c-f581cb214912/identifier . You can then search for organizations by identifier: http://api.gbif.org/v1/organization?identifier=dc6c6ea2-83f5-4b18-985a-9efff6320d69

i.e. there's manual / semi-manual work to link each publishing organization the first time (either GBIF or OBIS must make a link where currently none exists).

----

> I was more thinking like a script that compares the DwC-A URLs in OBIS with GBIF via the OBIS API? But not sure if that is possible...

That's certainly possible as a one-off check or a script -- I've sent a list of omissions to the GBIF helpdesk address.

**Comment by kcopas** [comment]
Just want to flag the arrival of a new Caribbean OBIS dataset [here](https://doi.org/10.15468/qaecsh), in the event it helps this process.

h/t [GBIFDodo](https://twitter.com/GBIFDodo/status/1275906723207884800?s=20)

**Comment by ManonGros** [comment]
@ahahn-gbif could you check if we can close this issue?

**Comment by ahahn-gbif** [comment]
The initial issue (update of the network page) has been dealt with. Suggest to open a new issue for outstanding workflow items on the dataset-network association, rather than continuing here (closing).
