### ISSUE TITLE
Me efrecen en el título  lista de peses de mi país y no hay nada referente a este tema

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2831]
**Me efrecen en el título lista de peses de mi país y no hay nada referente a este tema**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7ce0ae8f522c265ad5630b50bf6cb3e7:ec066cae4b5c95c57b3024643352aff70b31a882f54f3dd7ad09c549004ac92d5b6924e9a4b9ced47d193ed64bc8799d0f9d58dee406cbf637b463761949a542)
System: Chrome Mobile 81.0.4044 / Android 8.0.0
Referer: https://www.gbif.org/search?q=Peses%20colombia
Window size: width 360 - height 253
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-18T04:40:43.999Z',mode:absolute,to:'2020-06-18T04:46:43.999Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-18T04:40:43.999Z',mode:absolute,to:'2020-06-18T04:46:43.999Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Googel translate
> They appear in the title of the weightings of my country and there is nothing referring to this topic

**Comment by leo-buitrago** [comment]
I replied this requirement right from helpdesk email
