### ISSUE TITLE
Herbarium (AMNH) default value for country

### ISSUE THREAD

**Issue by jhnwllr** [gbif/portal-feedback#2832]
The dataset Herbarium (AMNH) needs to have a default value set for country countrycode.

or 

the publisher needs to be contacted.

https://www.gbif.org/dataset/83435394-f762-11e1-a439-00145eb45e9a
https://registry.gbif.org/dataset/83435394-f762-11e1-a439-00145eb45e9a/defaultValue

example here:
https://registry.gbif.org/dataset/cc9bd573-9c96-4532-a723-52ce1d155b36/defaultValue

**Comment by ahahn-gbif** [comment]
Since this is another orphaned dataset (see endpoint), I would suggest going ahead with setting a default value

**Comment by jhnwllr** [comment]
default value set to country=Iceland and countryCode=IS
