### ISSUE TITLE
Plants of Scotia Sanctuary needs a default value for country

### ISSUE THREAD

**Issue by jhnwllr** [gbif/portal-feedback#2833]
The dataset Plants of Scotia Sanctuary needs to have a default value set for country countrycode.

or

the publisher needs to be contacted.

https://www.gbif.org/dataset/694b8003-0ee9-4360-982e-cb7dfb0cafe5
https://registry.gbif.org/dataset/694b8003-0ee9-4360-982e-cb7dfb0cafe5/defaultValue

example here:
https://registry.gbif.org/dataset/cc9bd573-9c96-4532-a723-52ce1d155b36/defaultValue

**Comment by ahahn-gbif** [comment]
Notified data curators and ALA via email. This should be corrected at source, but consider adding default values if nothing changed in reasonable time (suggest 2 weeks)

**Comment by jhnwllr** [comment]
Should we add the default value now has been 8 days?

**Comment by ahahn-gbif** [comment]
ALA received a corrected data file from the dataset owners on June 19th. Dependent on lag time, we should see this correction trickle through. Feel free to add a default; it should be overridden by any explicit update in the data
