### ISSUE TITLE
CSS spacing issue with vernacular names

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2838]
**CSS spacing issue with vernacular names**

Taxonomic scope of https://www.gbif.org/dataset/f9af6ffd-febc-4626-b2e8-809b1c60fa01#taxonomicCoverages: there is no space between the scientific and the vernacular name.

Oddly enough, it seems to be correct on other dataset pages I checked: https://www.gbif.org/dataset/3dfbaea0-f5df-4978-b3a1-fb22edcde0de#taxonomicCoverages

Maybe it is only an issue on checklist datasets?

-----

Github user: @peterdesmet
User: [See in registry](https://www.gbif.org/api/feedback/user/15a168c9263c7385f838d2fe55ea2b7e:deea9a1eeceaad1579f00f9a35dc7bb94f0b8d60d4fd26af6f77b65e90701ccbb991f57bcfcb54d832bc5d79cba3f604ab1b1ead80451b3c92a44d4b1ea0271c)
System: Chrome 83.0.4103 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/f9af6ffd-febc-4626-b2e8-809b1c60fa01
Window size: width 1365 - height 716
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-19T08:34:13.700Z',mode:absolute,to:'2020-06-19T08:40:13.700Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-19T08:34:13.700Z',mode:absolute,to:'2020-06-19T08:40:13.700Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by peterdesmet** [comment]
<img width="412" alt="Screenshot 2020-06-19 at 10 35 24" src="https://user-images.githubusercontent.com/600993/85115022-4cc40f80-b21b-11ea-8248-706fe559d873.png">
