### ISSUE TITLE
The registration of a new organization failed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2841]
**The registration of a new organization failed**

Dear colleague, i have a problem with registerin a new organization. I have submitted the registration form, but received a message saying "The registration failed, please contact Helpdesk". I made a normal registration and the organization itself had not been registered in GBIF yet (at least i couldn't find it among the registered organizations available). 
The organization is "Voronezh State University". A person who is responsible for registration (Anna Bedenko) tried to register herself, but received failue as well and asked my help. I tried the registration using her data and as well failed.
Thank you for your support! Nina.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2a4f642eb8b15ca8ae895942551be83d:b7dcb6c43499aede337b4deead670cf45697abcb88b1af453de536b9929c6fda1f48e8763fac7e9c26b37dac990ce1c609fc848481a46120f8dad45132e08c9a)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1396 - height 612
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-20T12:57:04.954Z',mode:absolute,to:'2020-06-20T13:03:04.954Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-20T12:57:04.954Z',mode:absolute,to:'2020-06-20T13:03:04.954Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
The issue has meanwhile been fixed via helpdesk (publisher registered and  endorsed)
