### ISSUE TITLE
Invasive species lists not appearing on species pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2842]
**Invasive species lists not appearing on species pages**

Something is preventing the tables generated by the GRIIS lists "Introduced in xx countries" appearing on species pages.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/32b89205b96bea38c65e8ea745ac17b3:e2fa3d5a8e318ffd9804f788b922981e0d99e64fd6a4f47479d8738db7efb85bb6e5c61d3b19cd902719b3a90eb5c32162c56cf7af5e661d87d88e8e203738b0)
System: Chrome 83.0.4103 / Mac OS X 10.15.4
Referer: https://www.gbif.org/species/2224546
Window size: width 1772 - height 1070
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-21T14:11:03.263Z',mode:absolute,to:'2020-06-21T14:17:03.263Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-21T14:11:03.263Z',mode:absolute,to:'2020-06-21T14:17:03.263Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Lists are visible again now
