### ISSUE TITLE
The species name 'cynoid' looks a bit suspicious.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2844]
**The species name &#39;cynoid&#39; looks a bit suspicious.**

Could this be a typo / or that the 'es' of 'cynoides' has been missed out while copy/pasting? The Birdlife Taxonomic checklist contains the same name, as does the IUCN factsheet for the species. However, I cannot find a source to indicate why the names has changed. Has it taken the name from an earlier described species? Seems a bit strange anyway.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fce6deb0b33c6697cb8124aca0fedfeb:916eba5516f70300bdbc97bbc18dbda32252422e77ce3eeeed40b7dce1240d7fbb3432a43c161d43418fe734a030afdc97d423c663bfae489efb8423291ad4f5292c588bedb55d3c90d09d78e13a33c1)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/species/9408431
Window size: width 2560 - height 1292
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-24T15:02:35.374Z',mode:absolute,to:'2020-06-24T15:08:35.374Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-24T15:02:35.374Z',mode:absolute,to:'2020-06-24T15:08:35.374Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by timgreenfinland** [comment]
that should be 'cygnoides' by the way.

**Comment by ahahn-gbif** [comment]
Our source for this name is http://www.marinespecies.org/aphia.php?p=taxdetails&id=1037303. Will forward the feedback to them.

**Comment by ahahn-gbif** [comment]
Email sent to WoRMS

**Comment by ahahn-gbif** [comment]
Response from WoRMS: "Thank you for your feedback! We forwarded this to the taxonomic editor, and the typo was fixed in WoRMS."

It will take more time to translate into the GBIF backbone, which only gets updated periodically.
