### ISSUE TITLE
Duplicate datasets from North Macedonia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2845]
**Duplicate datasets from North Macedonia**

Looks like the [Macedonian Ecological Society](https://www.gbif.org/publisher/856529fb-02f1-4539-80c1-174f7231ef0f) has been doing some clean-up on datasets (good) but they're duplicating what's there (less good). One of the old datasets has a citation already, so probably even better not to jettison the old if the new is just an update (occurrence numbers are exactly the same). Perhaps some suggestions or quick tips could help them navigate this process better…?

Example 1: compare [mes_beetles_bimr](https://www.gbif.org/dataset/e9281f33-8c68-4e0a-a868-a4a161905e96) with [Classic localities of endemic beetles (Coleoptera) from the Western Balkans](https://www.gbif.org/dataset/69bbc9fb-a432-4945-bb4f-654bff3bc2de).

Example 2: [mes_verte_bimr](https://www.gbif.org/dataset/d15d62f1-9369-4f3f-b717-d8ea4efd5f5d) and [Classic localities of endemic amphibians, reptiles and mammals from the Western Balkans](https://www.gbif.org/dataset/45b032fa-620b-4c33-ac85-c72521c0a41e)

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/481ef467684c054037061d7d5aabd9c9:b135008175a6039cdd06842cda1d7d26cce8b48f675ce3484cac2d7bfe5120b33ad667c25001d1a150f4e3ec57c220eb7934831698ba3421a0fdf5ec20981eb7)
System: Firefox 77.0.0 / Mac OS X 10.14.0
Referer: https://www.gbif.org/dataset/69bbc9fb-a432-4945-bb4f-654bff3bc2de
Window size: width 2370 - height 1259
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-25T05:48:43.206Z',mode:absolute,to:'2020-06-25T05:54:43.206Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-25T05:48:43.206Z',mode:absolute,to:'2020-06-25T05:54:43.206Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by timhirsch** [comment]
FWIW the old datasets seem to be hosted with GBIF Poland and the new ones published on their own IPT, so the simplest may be just to take the former down - admittedly that would lose the citation. Probably worth bringing in Piotr (Poland node manager).

**Comment by ManonGros** [comment]
It looks like the old datasets have been deleted.
