### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2847]
**Broken images**

Many images from this dataset point to broken identifiers like http://www2.nau.edu/sbugs-p/UHIM/UHIM2014.12/UHIM2014.12516_lg.jpg where access is denied

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/a4d1b94bd1d00683189a911334bbcf90:4058d365816236d7a5731252c34200e2ca5a7e6b122f47fcd4e94a66c6e58a9fe5753a3bc2c849486a6de55377fd61ad39e39d0c53f443d4b97e4d6f770b5d5f)
System: Chrome 83.0.4103 / Mac OS X 10.14.6
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=47576eae-c976-4c45-adc2-35d895bb1cbb
Window size: width 1438 - height 736
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-25T07:34:07.039Z',mode:absolute,to:'2020-06-25T07:40:07.039Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-25T07:34:07.039Z',mode:absolute,to:'2020-06-25T07:40:07.039Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
publisher contacted via helpdesk

**Comment by ahahn-gbif** [comment]
Fixed by publisher and reindexed - closing
