### ISSUE TITLE
CAFF not included in Iceland totals

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#285]
**CAFF not included in Iceland totals**

I suspect the source of the problem is the lack of a country listing in the registry, but CAFF is based in Iceland, publishes 60-odd datasets with several hundred thousand records, but they&#39;re not captured in the country page or country report.

This omission has a big impact on all the various the national totals and significantly underestimates the activity.

-----
fbitem-publisher44862593-2fdd-4491-ab79-b500b8272aac
Reported by: @kcopas
System: Safari 10.1.2 / Mac OS X 10.12.6
Referer: https://demo.gbif.org/publisher/44862593-2fdd-4491-ab79-b500b8272aac
Window size: width 1326 - height 757
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-04T12:51:53.210Z',mode:absolute,to:'2017-08-04T12:57:53.210Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-04T12:51:53.210Z',mode:absolute,to:'2017-08-04T12:57:53.210Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
According to the description CAFF is international by nature and therefore this is by considered decision.
