### ISSUE TITLE
Malaysian bat datasets missing from BIFA project page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2850]
**Malaysian bat datasets missing from BIFA project page**

[Twenty-one newly published datasets](https://www.gbif.org/dataset/search?publishing_org=768e0109-68c6-4611-b8be-df2ae01aa470) are not appearing on the BIFA project page. There is a project_ID entered, but I'm guessing there must be a problem with it…?

Worth checking out as we've been promoting the datasets in several different venues, including today's webinar.

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/aec44d7a150a5f07970f29744b9ac6d0:474f4889d64f7151ffa27f7b755bb2dac2b33c989e4feaba7224bb198dc8129f69ca05729bc39220bf4e77fe0b8824603257db807a32ce5dd0a23c983940b715)
System: Firefox 77.0.0 / Mac OS X 10.14.0
Referer: https://www.gbif.org/project/3PMwZjKycuPnEo5FUDY99S/deploying-acoustic-data-to-fill-gaps-in-bat-biodiversity-information-for-southeast-asia
Window size: width 1535 - height 1022
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-25T17:14:41.633Z',mode:absolute,to:'2020-06-25T17:20:41.633Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-25T17:14:41.633Z',mode:absolute,to:'2020-06-25T17:20:41.633Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ahahn-gbif** [comment]
The issue has been fixed as part of the routine BID data review process
