### ISSUE TITLE
Missinterpretation of _Ervilia articulata_ hierarchy at GBIF Backbone

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/portal-feedback#2856]
The Backbone is interpreting **_Ervilia articulata_ (Hornem.) H.Schaef., Coulot & Rabaute, 2016** as a mollusc species https://www.gbif.org/species/9493756 but it is a plant https://inpn.mnhn.fr/espece/cd_nom/788870/tab/archeo?lg=en.

I think it is adding the scientificName to the backbone from this checklist [Global Register of Introduced and Invasive Species - France](https://www.gbif.org/dataset/692a0aec-70e2-4038-ac9c-9a1d7acc025f) but the species hierarchy corresponds to a plant https://www.gbif.org/species/148792168/verbatim, so why the backbone assigns it a mollusc hierarchy? (also to the occurrences (e.g. https://www.gbif.org/occurrence/2495800697) 

Same story with the synonyms https://www.gbif.org/species/9303405 , https://www.gbif.org/species/9464882

**Comment by ManonGros** [comment]
It seems to have been fixed in the latest backbone update.
