### ISSUE TITLE
show UTC off set on event pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2858]
**show UTC off set on event pages**

Can we please show UTC offset on event page times?

E.g.

20 July 2020 09:00 - 11:00 (UTC+2)

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/af38315be3e10b7a273f357420c56b8f:488b3b43aa13f370b017ca774faef63db468a0bbed745451e50a3337c670ee8f620361ad28ee475b0716fbcb4d07ac6c2303e2ff7394e24a95f0b0abb1dae811)
System: Chrome 83.0.4103 / Mac OS X 10.15.5
Referer: https://www.gbif.org/event/2mhSFStVVJVdM8pYK7TScR/gbif-asia-virtual-summit
Window size: width 1432 - height 687
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-30T08:37:45.506Z',mode:absolute,to:'2020-06-30T08:43:45.506Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-30T08:37:45.506Z',mode:absolute,to:'2020-06-30T08:43:45.506Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by dnoesgaard** [comment]
To avoid all confusion, I've added a new field to the event content model called "timezone" (in DEV only). Ideally, we would derive UTC offset from this, but since we don't have that logic,  it'll have to be up to the content author. Dates/times should be shown in the format

DD MMMM YYYY HH:MM - HH:MM <timezone> (UTC <UTC offset>)

e.g.

20 July 2020 09:00 - 11:00 CEST (UTC+2)

**Comment by dnoesgaard** [comment]
https://www.gbif-dev.org/event/1bntBl5dBFlywKENhg24eR/big-important-timezone-event

shows UTC +00:00

while it should be +02:00

??
