### ISSUE TITLE
Bibio hortulanus should be accepted

### ISSUE THREAD

**Issue by mdoering** [gbif/portal-feedback#2859]
`Bibio hortulanus (Linnaeus, 1758)` IS the accepted name and `Tipula hortulana Linnaeus, 1758`
is NOT the accepted name.

See https://www.gbif.org/species/4520688 and https://www.gbif.org/species/100091509

From: Rob Deady

**Comment by ManonGros** [comment]
I think this could be an issue with the way we synonymize the names.
In the CoL, Bibio hortulanus (Linnaeus, 1758) is an accepted name https://www.catalogueoflife.org/data/taxon/8B73N and Tipula hortulana Linnaeus, 1758 is a synonym of a different species: https://www.catalogueoflife.org/data/taxon/57648

**Comment by ManonGros** [comment]
Solved in the current backbone.
