### ISSUE TITLE
New impact factors out

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2860]
**New impact factors out**

Perhaps could IF and Scopus scores could be updated, especially if data papers are going to play some role in WP2021. It does not harm to check APCs, too.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/07cb16df4e9e9870db18c02010cb897c:3bbd68ce201e71ab35b43b8d5cc5072819b33afb92c2a7ac0a5d190ba0caac4a4067111a84b3aa61bb0b6d89a9c57080be3d08b0f8f41a6a609f197e7271d5cb)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/data-papers
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-30T20:57:13.699Z',mode:absolute,to:'2020-06-30T21:03:13.699Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-30T20:57:13.699Z',mode:absolute,to:'2020-06-30T21:03:13.699Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
@akristensen assigning this to you to have a look at when you're back. Let me know and I'll show you how to pull the numbers :-)
