### ISSUE TITLE
cannot access blog

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2861]
**cannot access blog**

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/b05b2addc2b547bad98ab1431118c138:9bde2147b065dff58278f8faba8e192108dd199c5c630bf54dd651ddd0102fde739b70f8c5d7b956121fa827bff893f622c4b659640647da13304351c0284f19)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-01T19:00:26.274Z',mode:absolute,to:'2020-07-01T19:06:26.274Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-01T19:00:26.274Z',mode:absolute,to:'2020-07-01T19:06:26.274Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
@dschigel, do you mean https://data-blog.gbif.org/?

Where were you trying to access it from, and using what device?

**Comment by dschigel** [comment]
GBIF PC, Chrome. Works now, but not last evening.

**Comment by MattBlissett** [comment]
It worked when I looked yesterday, but it's hosted by an external service which I don't monitor.  If it happens again, try somewhere else (e.g. a phone) to see if the problem is your computer on the website.
