### ISSUE TITLE
Caesalpinia gardneriana Benth. is a synonym for Cenostigma nordestinum E.Gagnon & GPLewis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2862]
**Caesalpinia gardneriana Benth. is a synonym for Cenostigma nordestinum E.Gagnon &amp; GPLewis**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/634fe3b524d0f0e672967b4f4f8a6055:3c2fcd1e2d20a08061291ee4c1bd9b3bbb4071d96001e6cce8cc55b212fc37c6096a6713dc8ca0dd2b03184c7a8eb580819d1e56e96f3a52d05084dc16448e35)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/species/2958455
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-02T06:17:40.245Z',mode:absolute,to:'2020-07-02T06:23:40.245Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-02T06:17:40.245Z',mode:absolute,to:'2020-07-02T06:23:40.245Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It seems to be the case in the new backbone.
