### ISSUE TITLE
Erroneous synonymy (Insecta: Diptera: Muscidae/Calliphoridae)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2863]
**Erroneous synonymy (Insecta: Diptera: Muscidae/Calliphoridae)**

Muscina angustifrons (Loew, 1858) is not a synonym of  Philornis angustifrons (Loew, 1861).

M. angustifrons is (currently recognised as valid) a Palearctic muscid species. Philornis are tropical blowflies.
 Reefrence: for example http://www.catalogueoflife.org/col/details/species/id/f24dc1878eb9137d769a8f2d1acf3cee

There are a a *lot* of mistakes in the GBIF backbone taxonomy. Should I keep reporting single cases like this?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/479fa5d15d47c34c5a45b4aefe4855db:77c4632bfd5a508c4d56eb7f03b0b8c09d5f268a25445bb3587120bef5a78afcc158d87e0ec17c9fb7376d242e3c10442a068627529a2c2cc7623689534725ef)
System: Firefox 77.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/species/1526140
Window size: width 1654 - height 950
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-02T07:13:31.364Z',mode:absolute,to:'2020-07-02T07:19:31.364Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-02T07:13:31.364Z',mode:absolute,to:'2020-07-02T07:19:31.364Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
They are distinct species in the new backbone.
