### ISSUE TITLE
quality concerns about unverified citizen science observations impact GBIF data quality image

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2864]
**quality concerns about unverified citizen science observations impact GBIF data quality image**

I can see in Russian biodiversity social media that availability of unverified occurrences from Pl@ntNet (in addition to verified ones) fuels the existing worries about data quality in GBIF. Any reason why Pl@ntNet unverified comes to GBIF at to start with? Is not it different from the setup with iNat and eBird?

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/fa17d44cc0747c5918a09ee3a3e962ac:ca6fa169faf66bb707ee5344493e304eb5cfafc98a1805ae33e849e36b7649bfcf5cda9b7920900f59869c4611f89fd087f403a84971e5a66cc2f8249473dfcb)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/14d5676a-2c54-4f94-9023-1e8dcd822aa0
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-02T12:32:16.466Z',mode:absolute,to:'2020-07-02T12:38:16.466Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-02T12:32:16.466Z',mode:absolute,to:'2020-07-02T12:38:16.466Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Publisher feedback:
- as the description of the "automatically identified occurrences" dataset explains, there is already a threshold on the confidence score of the classifier. This threshold was set up to a quite high value (>0.9 probability). Among the 150 million observations collected by Pl@ntNet, only 6 million were kept for inclusion in GBIF. 

Questions: 
- does the confidence score need to be raised further? 
- would there be a specific type of observations for such data (neither human nor machine observations) for automatic determinations? Those would come with a confidence score.

[see helpdesk, 8.7.20]

**Comment by dschigel** [comment]
Feedback is great and clear, will use to calm down the waves of concern, will report if it fails. I think 0.9 probability is probably fine, but I am unfamiliar with what is customary in AI worlds (@timrobertson100). In sequence identifications, 0.97 is common, but sometimes stricter values are used @thomasstjerne 

To me this is not a specific type of observation, but it might be useful for us to consider filtering by 100% machine (AI or sequence pipeline) vs. human-assisted identifications.

**Comment by thomasstjerne** [comment]
I dont know if you can compare different models and their thresholds. But the AI model in Svampeatlas is usually right if confidence is > 0.8. If their model is good, I would not imagine many misidentifications with 0.9 threshold

**Comment by MattBlissett** [comment]
As far as I know, it makes no sense at all to compare a probability between different models.

**Comment by dschigel** [comment]
But it makes sense to compare probabilities of identification being correct, comparison of probabilities can be independent from the method of calculating them, I think. All identification processes are probabilistic. This is a key paper on this approach https://pubmed.ncbi.nlm.nih.gov/27296980 and there were several others later. I think we should explore this more before we dismiss cross-method comparisons of IC accuracy probabilities. This could be a very powerful DQ metric, if it works.

**Comment by jhnwllr** [comment]
The threshold of 0.9 will not tell you the probability of id being correct. It will only tell you about the model's confidence. If the model is not very good or is only trained on a limited set, then the model's confidence and reality will be pretty far apart!

**Comment by jhnwllr** [comment]
In defense of **Pl@ntNet automatically identified occurrences** I did **not** find a single outlier point from that dataset.

**Comment by dschigel** [comment]
Publisher feedback was sufficient to address concerns and clarify ID process at source.

**Comment by MattBlissett** [comment]
> In defense of **Pl@ntNet automatically identified occurrences** I did **not** find a single outlier point from that dataset.

Note that could be because their algorithm takes range into account, and won't identify something you'd detect as an outlier (i.e. a real outlier would be identified to something else).

(I haven't looked at the data myself.)

**Comment by jhnwllr** [comment]
I re-ran the outlier detection, since **Pl@ntNet automatically identified occurrences**, was not run before probably. 

I found **297** outliers. 

This is not very many considering the millions of points within the dataset, so I would bet there are not many indoor plants in the dataset.

**Comment by MattBlissett** [comment]
Maybe it's https://www.gbif.org/dataset/7a3679ef-5582-4aaa-81f0-8c2545cafc81 that has the indoor plants. It's easy to scroll through the images and see them: https://www.gbif.org/occurrence/gallery?dataset_key=7a3679ef-5582-4aaa-81f0-8c2545cafc81&taxon_key=2772666

**Comment by jhnwllr** [comment]
These are the **204** outliers I find for https://www.gbif.org/dataset/7a3679ef-5582-4aaa-81f0-8c2545cafc81 

There are only a few in there that seem to have been taken indoors.  Probably the ones in the pictures happen to align with existing distributions...

link
--
https://www.gbif.org/occurrence/2644844608
https://www.gbif.org/occurrence/2645204814
https://www.gbif.org/occurrence/2645661946
https://www.gbif.org/occurrence/2645839703
https://www.gbif.org/occurrence/2644347926
https://www.gbif.org/occurrence/2643598132
https://www.gbif.org/occurrence/2644243963
https://www.gbif.org/occurrence/2644577223
https://www.gbif.org/occurrence/2644108904
https://www.gbif.org/occurrence/2644326771
https://www.gbif.org/occurrence/2645876407
https://www.gbif.org/occurrence/2644200071
https://www.gbif.org/occurrence/2644284515
https://www.gbif.org/occurrence/2645739985
https://www.gbif.org/occurrence/2644283789
https://www.gbif.org/occurrence/2644336376
https://www.gbif.org/occurrence/2644347484
https://www.gbif.org/occurrence/2644237626
https://www.gbif.org/occurrence/2645020573
https://www.gbif.org/occurrence/2644376831
https://www.gbif.org/occurrence/2644331609
https://www.gbif.org/occurrence/2645974778
https://www.gbif.org/occurrence/2645012994
https://www.gbif.org/occurrence/2645681488
https://www.gbif.org/occurrence/2644869108
https://www.gbif.org/occurrence/2644092471
https://www.gbif.org/occurrence/2644753526
https://www.gbif.org/occurrence/2643559678
https://www.gbif.org/occurrence/2645907341
https://www.gbif.org/occurrence/2645748755
https://www.gbif.org/occurrence/2645803138
https://www.gbif.org/occurrence/2645866321
https://www.gbif.org/occurrence/2644331713
https://www.gbif.org/occurrence/2645799847
https://www.gbif.org/occurrence/2643585449
https://www.gbif.org/occurrence/2644882330
https://www.gbif.org/occurrence/2644830793
https://www.gbif.org/occurrence/2643564230
https://www.gbif.org/occurrence/2644034449
https://www.gbif.org/occurrence/2645715689
https://www.gbif.org/occurrence/2643505282
https://www.gbif.org/occurrence/2645372573
https://www.gbif.org/occurrence/2644264825
https://www.gbif.org/occurrence/2645688843
https://www.gbif.org/occurrence/2644336425
https://www.gbif.org/occurrence/2643485789
https://www.gbif.org/occurrence/2645932776
https://www.gbif.org/occurrence/2644265264
https://www.gbif.org/occurrence/2645692927
https://www.gbif.org/occurrence/2645816061
https://www.gbif.org/occurrence/2644336488
https://www.gbif.org/occurrence/2644192098
https://www.gbif.org/occurrence/2644265299
https://www.gbif.org/occurrence/2645639691
https://www.gbif.org/occurrence/2644052244
https://www.gbif.org/occurrence/2643603924
https://www.gbif.org/occurrence/2644601720
https://www.gbif.org/occurrence/2643984482
https://www.gbif.org/occurrence/2645659968
https://www.gbif.org/occurrence/2644017744
https://www.gbif.org/occurrence/2645783301
https://www.gbif.org/occurrence/2643536055
https://www.gbif.org/occurrence/2645693176
https://www.gbif.org/occurrence/2644975809
https://www.gbif.org/occurrence/2645692442
https://www.gbif.org/occurrence/2645672269
https://www.gbif.org/occurrence/2644017393
https://www.gbif.org/occurrence/2643851462
https://www.gbif.org/occurrence/2643650792
https://www.gbif.org/occurrence/2644279031
https://www.gbif.org/occurrence/2645847528
https://www.gbif.org/occurrence/2644182827
https://www.gbif.org/occurrence/2644264369
https://www.gbif.org/occurrence/2645112321
https://www.gbif.org/occurrence/2644209638
https://www.gbif.org/occurrence/2643583616
https://www.gbif.org/occurrence/2645784272
https://www.gbif.org/occurrence/2644074728
https://www.gbif.org/occurrence/2645800036
https://www.gbif.org/occurrence/2645745826
https://www.gbif.org/occurrence/2644277349
https://www.gbif.org/occurrence/2644460791
https://www.gbif.org/occurrence/2644332029
https://www.gbif.org/occurrence/2643781444
https://www.gbif.org/occurrence/2645521818
https://www.gbif.org/occurrence/2643600428
https://www.gbif.org/occurrence/2644419457
https://www.gbif.org/occurrence/2645937412
https://www.gbif.org/occurrence/2644285275
https://www.gbif.org/occurrence/2643606736
https://www.gbif.org/occurrence/2643483740
https://www.gbif.org/occurrence/2645734110
https://www.gbif.org/occurrence/2644054541
https://www.gbif.org/occurrence/2644326966
https://www.gbif.org/occurrence/2644748627
https://www.gbif.org/occurrence/2645113419
https://www.gbif.org/occurrence/2644303130
https://www.gbif.org/occurrence/2643517533
https://www.gbif.org/occurrence/2644156527
https://www.gbif.org/occurrence/2643604323
https://www.gbif.org/occurrence/2644034876
https://www.gbif.org/occurrence/2645935683
https://www.gbif.org/occurrence/2643834415
https://www.gbif.org/occurrence/2645518592
https://www.gbif.org/occurrence/2644017791
https://www.gbif.org/occurrence/2643926941
https://www.gbif.org/occurrence/2645559549
https://www.gbif.org/occurrence/2644226688
https://www.gbif.org/occurrence/2643604429
https://www.gbif.org/occurrence/2644777054
https://www.gbif.org/occurrence/2645520508
https://www.gbif.org/occurrence/2644332008
https://www.gbif.org/occurrence/2645764116
https://www.gbif.org/occurrence/2644235052
https://www.gbif.org/occurrence/2643557813
https://www.gbif.org/occurrence/2645231833
https://www.gbif.org/occurrence/2644134219
https://www.gbif.org/occurrence/2644612693
https://www.gbif.org/occurrence/2645779575
https://www.gbif.org/occurrence/2645012778
https://www.gbif.org/occurrence/2644628553
https://www.gbif.org/occurrence/2644337175
https://www.gbif.org/occurrence/2645802766
https://www.gbif.org/occurrence/2644606799
https://www.gbif.org/occurrence/2645321730
https://www.gbif.org/occurrence/2644166948
https://www.gbif.org/occurrence/2644228014
https://www.gbif.org/occurrence/2644830738
https://www.gbif.org/occurrence/2645285429
https://www.gbif.org/occurrence/2644228247
https://www.gbif.org/occurrence/2644243910
https://www.gbif.org/occurrence/2644953459
https://www.gbif.org/occurrence/2644776319
https://www.gbif.org/occurrence/2645936069
https://www.gbif.org/occurrence/2645254624
https://www.gbif.org/occurrence/2644847210
https://www.gbif.org/occurrence/2644098101
https://www.gbif.org/occurrence/2645908028
https://www.gbif.org/occurrence/2643598263
https://www.gbif.org/occurrence/2643672057
https://www.gbif.org/occurrence/2644183183
https://www.gbif.org/occurrence/2644260171
https://www.gbif.org/occurrence/2644187238
https://www.gbif.org/occurrence/2644243129
https://www.gbif.org/occurrence/2645779774
https://www.gbif.org/occurrence/2645822952
https://www.gbif.org/occurrence/2643545687
https://www.gbif.org/occurrence/2643928295
https://www.gbif.org/occurrence/2644244338
https://www.gbif.org/occurrence/2645784039
https://www.gbif.org/occurrence/2644278977
https://www.gbif.org/occurrence/2645709655
https://www.gbif.org/occurrence/2644263651
https://www.gbif.org/occurrence/2645457092
https://www.gbif.org/occurrence/2644223571
https://www.gbif.org/occurrence/2644846941
https://www.gbif.org/occurrence/2644885536
https://www.gbif.org/occurrence/2645907874
https://www.gbif.org/occurrence/2643581533
https://www.gbif.org/occurrence/2643858928
https://www.gbif.org/occurrence/2645777940
https://www.gbif.org/occurrence/2645756396
https://www.gbif.org/occurrence/2644157196
https://www.gbif.org/occurrence/2644612397
https://www.gbif.org/occurrence/2645595753
https://www.gbif.org/occurrence/2644234745
https://www.gbif.org/occurrence/2643614120
https://www.gbif.org/occurrence/2643543022
https://www.gbif.org/occurrence/2645583767
https://www.gbif.org/occurrence/2645731054
https://www.gbif.org/occurrence/2645021089
https://www.gbif.org/occurrence/2643479571
https://www.gbif.org/occurrence/2645881958
https://www.gbif.org/occurrence/2645908008
https://www.gbif.org/occurrence/2644336641
https://www.gbif.org/occurrence/2645763321
https://www.gbif.org/occurrence/2643643874
https://www.gbif.org/occurrence/2645777429
https://www.gbif.org/occurrence/2645860459
https://www.gbif.org/occurrence/2643787252
https://www.gbif.org/occurrence/2643822279
https://www.gbif.org/occurrence/2645331114
https://www.gbif.org/occurrence/2645699739
https://www.gbif.org/occurrence/2644792167
https://www.gbif.org/occurrence/2645839678
https://www.gbif.org/occurrence/2643568666
https://www.gbif.org/occurrence/2645503131
https://www.gbif.org/occurrence/2644524539
https://www.gbif.org/occurrence/2644247452
https://www.gbif.org/occurrence/2644972499
https://www.gbif.org/occurrence/2645936230
https://www.gbif.org/occurrence/2644376635
https://www.gbif.org/occurrence/2644419455
https://www.gbif.org/occurrence/2645613798
https://www.gbif.org/occurrence/2644283622
https://www.gbif.org/occurrence/2645907339
https://www.gbif.org/occurrence/2644294260
https://www.gbif.org/occurrence/2645346651
https://www.gbif.org/occurrence/2644100066
https://www.gbif.org/occurrence/2643741390
https://www.gbif.org/occurrence/2644425819
https://www.gbif.org/occurrence/2643479743
https://www.gbif.org/occurrence/2644347590
https://www.gbif.org/occurrence/2644183247
