### ISSUE TITLE
Processing Country from Plazi is erroneous. The country is Nicaragua as is evident and the title of the paper and as communicated by the collector only noticed this because he has never collected in Grenada & yet it appears in bionomia.net

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2866]
**Processing Country from Plazi is erroneous. The country is Nicaragua as is evident and the title of the paper and as communicated by the collector only noticed this because he has never collected in Grenada &amp; yet it appears in bionomia.net**

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/adb43fe0cba81d022ed660fa75638567:d371eace03e3e27b35012ebf4755d89df42acb9954e6d923b4b465521f6c9c08fee489a337c49740b40bf61bb2ce42ae8748904de0e6081c8b33836091ab775cc585075f1f1922801eae315bea839559)
System: Chrome 83.0.4103 / Mac OS X 10.15.5
Referer: https://www.gbif.org/occurrence/1303591499
Window size: width 1509 - height 844
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-03T15:11:57.585Z',mode:absolute,to:'2020-07-03T15:17:57.585Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-03T15:11:57.585Z',mode:absolute,to:'2020-07-03T15:17:57.585Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 252261d0-0838-4430-a885-5aa00e5ae788
publishingOrgKey: 7ce8aef0-9e92-11dc-8738-b8a03c50a862

**Comment by truschel** [comment]
The problem was solved.
Thank you!
