### ISSUE TITLE
Markup showing up in species names in occurrence titles

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2867]
**Markup showing up in species names in occurrence titles**

The names in this dataset are showing up with (em) etc in the titles, although they seem to be interpreted correctly.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1c80dbbf6caefbc978ec3a4b33cc77b9:0dad0d8f72cdf77883aaf327b5d9f84876964f44171ad22ad5186d8b9eccdfb2757cb19b11ead8498fe5a04068ffc92ee16bca282244741134d0293a09c7400e)
System: Chrome 83.0.4103 / Mac OS X 10.15.4
Referer: https://www.gbif.org/occurrence/search?dataset_key=830a425a-3e5d-4796-bc0c-269630f3187c
Window size: width 2084 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-04T07:27:27.902Z',mode:absolute,to:'2020-07-04T07:33:27.902Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-04T07:27:27.902Z',mode:absolute,to:'2020-07-04T07:33:27.902Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Thanks @timhirsch, the website hides the HTML in some places.

It's visible in the API: https://api.gbif.org/v1/occurrence/2804828345/verbatim

**Comment by ahahn-gbif** [comment]
Hi @leo-buitrago, this will require contacting the publisher. Dataset fields (scientific names) should not contain any markup, only the information - thanks!

**Comment by ManonGros** [comment]
Contacted publisher by email.
