### ISSUE TITLE
finding issues

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2868]
**finding issues**

I have difficulty in finding the issues I submitted. Search on frans_slieker doesn't return anything...... Could you please inform me how I create an overview of all the issues I forwarded including their status....

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ebe43f564c6cf5c48b4aff83edbc78f9:50ece7789df0502889acf3dd377208acf6d3aa5b5edf6642e9a1e9b0e6b8730ebf2b52f3e6d58304bfaced789b37875700c375f6a9731f95a7572d50a144c691)
System: Firefox 78.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1920 - height 901
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-05T20:20:53.858Z',mode:absolute,to:'2020-07-05T20:26:53.858Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-05T20:20:53.858Z',mode:absolute,to:'2020-07-05T20:26:53.858Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
The reason no "frans_slieker" username showed up is because that name is hidden behind a url and is protected user information.
I believe this is part of the 'data user agreement' that ensures the privacy of the GBIF users.

I have a quick idea: When a user submits an issue, then the user gets a receipt to their email containing the url to the feedback issue.

**Comment by MortenHofft** [comment]
If the user in case have a Github account, then linking it to GBIF will result in a mention on all issues. That might help in some cases.

**Comment by jlegind** [comment]
Issue has been fully handled .
