### ISSUE TITLE
add link to publishers from the country

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#287]
**add link to publishers from the country**

suggestion from @kcopas

&gt;add link to publishers from the country page

Not on the current prod site.

-----
fbitem-4d1204653c1eb9d3b84febdf50d7cf5c376a4d0b
Reported by: @mortenhofft
System: Chrome 59.0.3071 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/country/IS/summary
Window size: width 1921 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-04T13:37:31.216Z',mode:absolute,to:'2017-08-04T13:43:31.216Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-04T13:37:31.216Z',mode:absolute,to:'2017-08-04T13:43:31.216Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Tusind tak, Morten.

The idea is, if possible, to
+ give the start of a list of publishers as, for instance, in this example from [France](https://demo.gbif.org/publisher/search?country=FR)
+ provide a count of publishers in a given country (e.g. 47 publishers for France)

I thought this was in the current site, but after looking, I think it may only appear in the country report…in which case, apologies for providing such an excellent new requirement at this late date 
;P

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/412
