### ISSUE TITLE
Potted plants marked as human observations

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2870]
**Potted plants marked as human observations**

This dataset contains ex-situ observations that are presently marked as "human Observations". Contact the publisher and recommend to change the basis of record to "living".

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4ffd803656a6d264ad748e5286a06a53:aacd9c2b6273ee869dd0a1fb340b8f336477ffb3d5adc300f7e28173ce1c92d605a4d3beeea831e1af29a6ac8a0e420a11cb482c495ffce6a95a66b6e0a20a08)
System: Firefox 78.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2644183172
Window size: width 1280 - height 551
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-08T10:54:21.856Z',mode:absolute,to:'2020-07-08T11:00:21.856Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-08T10:54:21.856Z',mode:absolute,to:'2020-07-08T11:00:21.856Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by ahahn-gbif** [comment]
Email sent

**Comment by ahahn-gbif** [comment]
#2864

**Comment by ahahn-gbif** [comment]
Response received: integration of this information is already in the work plan, but may take a few months due to development requirements

**Comment by timrobertson100** [comment]
Presumably, those development months will be to model more sophisticated routines to screen in situ/ex situ observations.
Changing the basisOfRecord as suggested seems like a sensible quick fix to apply in the meantime to me.

**Comment by ManonGros** [comment]
It looks like this record was excluded from the dataset when Pl@ntNET updated their data. Should we close the issue?
