### ISSUE TITLE
Is there a way to search for multiple taxa at a time? So far alll I know how to do is look for one at a time. Very frusttating.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2873]
**Is there a way to search for multiple taxa at a time? So far alll I know how to do is look for one at a time. Very frusttating.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c92c0357d114957b25ced985968dad60:0e743b435eb8e46d31147d2aad72e61d0a1a73129b2682dd94dde211aaf2f161716813610f0efc281a126f963d3f39ce4a0a844ca3691006cbe2dfd74606e8db)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?q=
Window size: width 2133 - height 1076
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-10T16:54:31.713Z',mode:absolute,to:'2020-07-10T17:00:31.713Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-10T16:54:31.713Z',mode:absolute,to:'2020-07-10T17:00:31.713Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
If you’re using the interface and have search results for one taxonomic, just type another scientific name in the search field. You should get the prompt (again) as to whether you’re searching for [taxon name]. Click yes, and you’ve got a multitaxa search result. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ahahn-gbif** [comment]
contacted by email via helpdesk

**Comment by ahahn-gbif** [comment]
Also keep in mind that you can search for a parent taxon (genus, family) to include all the children underneath.
