### ISSUE TITLE
Senegalia brevispica

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2875]
**Senegalia brevispica**

page has pictures posted that are not of this species

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/347e81d949f8cb6049d103f910af27d3:146c2f83e11995eda23fe3a355303700885dc9169fa797231b5627f8dfa87ba05f6e00eed23c91d6152245ebe3452320f0680ccb9614f7b03285513fb2ec013a)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/species/7642799
Window size: width 1858 - height 1009
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-13T07:09:46.333Z',mode:absolute,to:'2020-07-13T07:15:46.333Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-13T07:09:46.333Z',mode:absolute,to:'2020-07-13T07:15:46.333Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
The backbone considers Desmodium dregeanum Benth. (https://www.gbif.org/species/2967240) to be a synonym of Senegalia brevispica subsp. dregeana (Benth.) Kyal. & Boatwr. (https://www.gbif.org/species/8377970).
