### ISSUE TITLE
"Data last changed" does not actualize in dataset pages

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#2876]
The information in "Data last changed" does not actualize and keep the old date, despite the last changes in the data.  Only the information in "Metadata last modified" change adequately. 
![Data_last_changed](https://user-images.githubusercontent.com/63795703/87438415-19c03200-c5b5-11ea-9152-b5475f64555c.PNG)
I made the actualization in the data last week.
![Data_last_review](https://user-images.githubusercontent.com/63795703/87443199-c81aa600-c5ba-11ea-91e7-5ab55a3d7543.PNG)

With the new datasets this information does not exist at all, only displaying the "Metadata last modified"
![Data_last_changed_New_Dataset](https://user-images.githubusercontent.com/63795703/87440696-dfa45f80-c5b7-11ea-8bf3-64c06458c660.PNG)
We have reviewed and this problem happens in all datasets published since May.

@RicardoOrtizG @camiplata @sibcolombia

**Comment by ahahn-gbif** [comment]
example screenshots from:
https://www.gbif.org/dataset/027c10bb-9fab-4236-982f-224d0f749c49
https://www.gbif.org/dataset/b0637f64-52a5-4938-b9e0-63f702fdecdc

**Comment by ahahn-gbif** [comment]
This is a change (and transition) in displaying the update information. In the context of the descriptive dataset page, we want to be clear that the information (incl. contacts) could be updated independent of a full data update. The data update information, on the other hand, is currently under revision. As background processing workflows changed recently, there are a few inconsistencies that we are working to resolve in the near future.

**Comment by MortenHofft** [comment]
The misleading information has been removed. For details we now refer to the registry ui (e.g. https://registry.gbif.org/dataset/027c10bb-9fab-4236-982f-224d0f749c49/ingestion-history) where details on the ingestions can be explored in more details
