### ISSUE TITLE
Cómo cambio mi nombre de usuario

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2877]
**Cómo cambio mi nombre de usuario**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a23bf62807361c3a800e97618573ce44:af843723ce292642fdb40204594b0945d1e85d9c3fb1cd6142f1f15453076d8efc77e06f5be1834de89ce1da92edd67a34f9b91f15925aa2c53c4d79366cf454)
System: Firefox 78.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/user/profile
Window size: width 1920 - height 901
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-14T16:36:07.506Z',mode:absolute,to:'2020-07-14T16:42:07.506Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-14T16:36:07.506Z',mode:absolute,to:'2020-07-14T16:42:07.506Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
You can update your real name through the interface at https://www.gbif.org/es/user/profile when logged in. Your user name, on the other hand, is the identifier of your account, and cannot be changed.

Email response sent via helpdesk
