### ISSUE TITLE
In your section 'Quality Control' please refer to us as: Peter Smith University of Botswana (PSUB) Herbarium. That is our internationally recognized official title. If you can edit the text please do so, it will help when people search on the acronym

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2878]
**In your section &#39;Quality Control&#39; please refer to us as: Peter Smith University of Botswana (PSUB) Herbarium. That is our internationally recognized official title. If you can edit the text please do so, it will help when people search on the acronym**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2aca49bd6e83d78481e4a6a2f5bbb9db:5bcf6ebea1becbfe78bf49ccf5810c557864f765a893a86e21b442c6b84e6eabb02e6c26c912bd0d250b641a7459e6587ae69b4f36eb240b6d88917fbbac42e7)
System: Chrome 84.0.4147 / Windows 7.0.0
Referer: https://www.gbif.org/dataset/602b5978-0777-41d7-8c9f-44f459b0f8ef
Window size: width 1680 - height 907
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-15T14:41:21.591Z',mode:absolute,to:'2020-07-15T14:47:21.591Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-15T14:41:21.591Z',mode:absolute,to:'2020-07-15T14:47:21.591Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email, advise they update the metadata in their IPT
