### ISSUE TITLE
Mass Download of Occurrence Data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2879]
**Mass Download of Occurrence Data**

Dear Ladies and Gentlemen,

for a research project I'm interested in the occurrence data of multiple species and genus. We have a list of 150 species/genus and need the geolocations of each occurrence (including the subspecies of the general genus).
E.g.:
Acer pseudoplatanus
Pyrus communis
Picea abies
Populus alba
Diospyros  => all subspecies
Dalbergia => all subspecies
Juglans regia
Haliotis  => all subspecies
Haliotis iris
Haliotis asinina
....

Is it possible to receive a bulk download or raw data from you instead of requesting for each speciesKey in the Occurrence Download interface and waiting for the download link?

Thanks in forward.
Beste regards
Jakob Kusnick

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/13d41079eddfe99ea99eb19deb630109:7684973e2700eef0ea0778327134ab1952a3dc88a65665e89ce3ebdb8ce8eb8ebb88bcd48bae5e7e1c2b57b11929414134f2ae440e8744a3b41e9886b3b8f216)
System: Safari 13.1.1 / Mac OS X 10.15.5
Referer: https://www.gbif.org/developer/occurrence
Window size: width 2560 - height 1352
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-15T15:41:49.402Z',mode:absolute,to:'2020-07-15T15:47:49.402Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-15T15:41:49.402Z',mode:absolute,to:'2020-07-15T15:47:49.402Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by MattBlissett** [comment]
Emailed, referred to https://data-blog.gbif.org/post/downloading-long-species-lists-on-gbif/ or https://www.gbif.org/occurrence/download/0005968-190621201848488 as an example.
