### ISSUE TITLE
Tool Name Parser not working

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2880]
**Tool Name Parser not working**

The page is not responding to a click in `Load Test Names` button

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1870c1820b9f42ff165b9a6c4c734b45:07a2e7455f66b4da819efbe6d8a91bb2f8879523da389fd291d4c46c445065cdd21fcaf2eda2baec0a606418c59e038317b338832f242142239c94e8454f3e38)
System: Firefox 77.0.0 / Fedora 0.0.0
Referer: https://www.gbif.org/tools/name-parser
Window size: width 1920 - height 568
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-15T16:56:46.056Z',mode:absolute,to:'2020-07-15T17:02:46.056Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-15T16:56:46.056Z',mode:absolute,to:'2020-07-15T17:02:46.056Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/3cc156ea518f138439ef11de7da047c0598bb2fd
