### ISSUE TITLE
Downloading average, min and max elevation and latitude for 1450 species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2882]
**Downloading average, min and max elevation and latitude for 1450 species**

Can you help me download average, min and max elevation and latitude data for 1450 species in my phylogeny?

I am not sure how to do this, or if it is possible.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bb4e048a59bd4c88644092c1e8373e3f:c54bdafed9bfa7314b8e65b44abff4668ae0d6f2737c6b1cf9ff9e4089e2afd253b2b85ab3bed11329a2614f4a47c8b09065e74909d58aa6967e3faada399f4d)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/species/6
Window size: width 1366 - height 695
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-17T19:16:14.398Z',mode:absolute,to:'2020-07-17T19:22:14.398Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-17T19:16:14.398Z',mode:absolute,to:'2020-07-17T19:22:14.398Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
Responded via helpdesk.
