### ISSUE TITLE
For the ant species Paratrechina guatemalensis there is a set of records of another species (Syllophopsis sechellensis).  One such example is: https://www.gbif.org/occurrence/865253059

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2889]
**For the ant species Paratrechina guatemalensis there is a set of records of another species (Syllophopsis sechellensis). One such example is: `https://www.gbif.org/occurrence/865253059`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6195e6a26bb66992d33e4b7fca6bbd4a:70d3c7b4d32f07ea85637daf04866812623bbebc673ae713ea0c3ebd348c40feb2f9e08e7fda0cf1414d6a0655d4427c70343243ea86a687531be6a3f7a71e6da15d6c6f0f603cbbdcabc55e976411d7)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/865253059
Window size: width 1920 - height 969
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-23T20:46:21.304Z',mode:absolute,to:'2020-07-23T20:52:21.304Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-23T20:46:21.304Z',mode:absolute,to:'2020-07-23T20:52:21.304Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 13b70480-bd69-11dd-b15f-b8a03c50a862
publishingOrgKey: 66522820-055c-11d8-b84e-b8a03c50a862

**Comment by mbfer** [comment]
I reported this and I'm sorry for the mistake. The error is in Paratrechina madagascarensis records.

**Comment by jlegind** [comment]
Syllophopsis sechellensis (Emery, 1894) is a HOMOTYPIC SYNONYM of Paratrechina madagascarensis subsp. sechellensis (Emery, 1894).
This is a legitimate response: You can search on the synonym and this will return all records of that particular synonym. If you search on the accepted name you will get all records, including every synonym.
