### ISSUE TITLE
Arnebia benthamii

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#289]
**Arnebia benthamii**

Arnebia benthamii (2 separate species differing with a space and a dot in the name of author)

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
Reported by: @bartoszmajcher
System: Chrome 59.0.3071 / Windows 7 0.0.0
Referer: https://demo.gbif.org/search?q=Arnebia%20benthamii
Window size: width 1280 - height 869
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-07T13:43:25.798Z',mode:absolute,to:'2017-08-07T13:49:25.798Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-07T13:43:25.798Z',mode:absolute,to:'2017-08-07T13:49:25.798Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
Not sure what is was before, but now we have 
`Arnebia benthamii (Wall. ex G.Don) I.M.Johnst.`
being a synonym of `Arnebia benthamii (Wall. ex G.Don) L M.Johnston` which appears correct. Authors do often differ just by initials. There are [14 Johnston listed in IPNI](http://beta.ipni.org/?q=author+surname%3AJohnston).
