### ISSUE TITLE
alternative identifiers

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2890]
**alternative identifiers**

hi, I work with a taxon list. I want to add an extension to cover its information (URL form) from other sources such as TPL, WFO, POWO, etc. should I use literature or alternative identifiers extension for this case? thank you for your help

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9ae14c6147b2df39b9e1a60370214d82:66efeb4ef514b3e62d86549456cb44196d43bac124ab5b8f5a8aa51ad069932b84617df86da79130e561a60591e478c6efb797707217710b17604a4d67501ed5)
System: Chrome 84.0.4147 / Windows 10.0.0
Referer: https://www.gbif.org/user/download
Window size: width 1366 - height 625
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-24T04:58:35.093Z',mode:absolute,to:'2020-07-24T05:04:35.093Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-24T04:58:35.093Z',mode:absolute,to:'2020-07-24T05:04:35.093Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
