### ISSUE TITLE
plant databases

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2891]
**plant databases**

Hi I'm looking for databases of plants (by species) including as many phenotypes as possible.  What's the easiest way to get that?

Thanks!

Tyler

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3bcadfee04d075e5d66b8c4d8d2d2e95:718e6c57d094e9fecbc546156080fdebe5b4f161828c3b82dbf17f5f9c74f19e29a54b26f989984011c000bde5c77405948a0806d20f5b09505b157c3f6632a7)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search
Window size: width 1920 - height 888
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-25T19:46:46.482Z',mode:absolute,to:'2020-07-25T19:52:46.482Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-25T19:46:46.482Z',mode:absolute,to:'2020-07-25T19:52:46.482Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
Dear Tyler,

I can not speak about plant databases outside of GBIF, but I did a search on GBIF datasets that have a significant number of records having kingdom: Plantae AND the infraspecific epithet is present. Here is the table of the Top Five datasets.

datasetkey                              | record count | title | translated | gbif url
-- | -- | -- | -- | --
fa7e6ad8-0a2e-49f2-b95d-e9f1e380fadf | 2560336 | Localización de táxones botánicos de interés   para la identificación de hábitats de la REDIAM (Secretaría General de Medio   Ambiente, Agua y Cambio Climático) | Location of   botanical taxa of interest for the identification of habitats of REDIAM   (General Secretariat for the Environment, Water and Climate Change) | https://www.gbif.org/dataset/fa7e6ad8-0a2e-49f2-b95d-e9f1e380fadf
38b4c89f-584c-41bb-bd8f-cd1def33e92f | 1350433 | Artportalen |   | https://www.gbif.org/dataset/38b4c89f-584c-41bb-bd8f-cd1def33e92f
dd238f50-f594-4e51-82af-033227ccab55 | 1229646 | Flore du   Bassin parisien (CBNBP) |   | https://www.gbif.org/dataset/dd238f50-f594-4e51-82af-033227ccab55
e6fab7b3-c733-40b9-8df3-2a03e49532c1 | 1065906 | Flora von   Deutschland (Phanerogamen) |   | https://www.gbif.org/dataset/e6fab7b3-c733-40b9-8df3-2a03e49532c1
64dabd3c-4f34-4520-b9dd-d227a0bf1582 | 1037827 | Occurrence Data of Vascular Plants collected   or compiled for the Flora of Bavaria |   | https://www.gbif.org/dataset/64dabd3c-4f34-4520-b9dd-d227a0bf1582
