### ISSUE TITLE
how doi get my project ID

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2892]
**how doi get my project ID**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fcc7647ee10cc2401a8f82e4ef493d2f:ae8aabfd7145333004e2ac1af0b084ef57ba905e9ef0e23798bb3050c2e3840c110b82b3fb4b54b0a1c3fa6ef8bffdecdaf8a4daf8194962068d8b0f33a130ac1fe5b6f4289717dcbbde927a05714c04)
System: Chrome 84.0.4147 / Windows 10.0.0
Referer: https://www.gbif.org/faq?question=gbif-grants-do-i-need-multiple-accounts-in-the-gbif-grants-portal-if-i-wish
Window size: width 1366 - height 625
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T12:58:40.449Z',mode:absolute,to:'2020-07-27T13:04:40.449Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T12:58:40.449Z',mode:absolute,to:'2020-07-27T13:04:40.449Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
User has been contacted and this issue will be passed on to the admin team as they handle project matters.

**Comment by jlegind** [comment]
Admin team contacted user. No project proposals have been received yet, so no new project ids exist.
