### ISSUE TITLE
The plant in the photo is an Abelia x grandiflora, not Jasminum.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2893]
**The plant in the photo is an Abelia x grandiflora, not Jasminum.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2a629f7071e67191d25e77984eca4774:84bc881d1fcc16fa46ba69d8ad9961ff0aa555df9884413c4a4d62dc366be62d79cb1dc17ca24c884efc94cf4d925a93f3b62ad3caf3bef06e3078145bf64b82)
System: Firefox 52.0.0 / Windows XP.0.0
Referer: https://www.gbif.org/occurrence/2644306921
Window size: width 1280 - height 643
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T15:56:08.227Z',mode:absolute,to:'2020-07-27T16:02:08.227Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T15:56:08.227Z',mode:absolute,to:'2020-07-27T16:02:08.227Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by ManonGros** [comment]
Voted on the suggested name on Pl@ntNet: https://identify.plantnet.org/observation/the-plant-list/1005497619

**Comment by ManonGros** [comment]
Occurrence removed from GBIF dataset.
