### ISSUE TITLE
The plant in the photo is a Jasminum polyanthum, not officinale

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2895]
**The plant in the photo is a Jasminum polyanthum, not officinale**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/95ff840f5be8b7c07f9c36605db24000:a3eca20e5d13eec924ac2a4cf8e664973b88cffb552f977753e48d1943212b680006964bbdf55390e8871da7e222127ba23c00da6fd77e5e12e2e6307bf594c0)
System: Firefox 52.0.0 / Windows XP.0.0
Referer: https://www.gbif.org/occurrence/2645953877
Window size: width 1280 - height 643
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T16:06:29.708Z',mode:absolute,to:'2020-07-27T16:12:29.708Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T16:06:29.708Z',mode:absolute,to:'2020-07-27T16:12:29.708Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by ManonGros** [comment]
Voted on the suggested name on Pl@ntNet: https://identify.plantnet.org/observation/the-plant-list/1005650433

**Comment by ManonGros** [comment]
Occurrence removed from GBIF dataset.
