### ISSUE TITLE
The plant in the photo is a Jasminum polyanthum, not officinale

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2896]
**The plant in the photo is a Jasminum polyanthum, not officinale**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/15d8a25085520057f0b58977084d4362:7318c64d7d940b09a9298254f2c5e4a1e899cd5444c7868b8431aceae9f50867293c8037762cc67af8cb6b79122e4867e0caf41a66ffd022e74b28c7a636f203)
System: Firefox 52.0.0 / Windows XP.0.0
Referer: https://www.gbif.org/occurrence/2643541771
Window size: width 1280 - height 643
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T16:09:42.790Z',mode:absolute,to:'2020-07-27T16:15:42.790Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T16:09:42.790Z',mode:absolute,to:'2020-07-27T16:15:42.790Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by ManonGros** [comment]
Voted on the suggested name on Pl@ntNet: https://identify.plantnet.org/observation/weurope/1003532515

**Comment by ManonGros** [comment]
Occurrence removed from GBIF dataset.
