### ISSUE TITLE
Parastemon urophyllus (Wall. ex A.DC.) A.DC.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#291]
**Parastemon urophyllus (Wall. ex A.DC.) A.DC.**

Parastemon urophyllus (Wall. ex A.DC.) A.DC. = Parastemon urophyllus (A.DC. ex Wall.) A.DC.

SYNYNYMS!

-----
fbitem-species2985237

System: Chrome 59.0.3071 / Windows 7 0.0.0
Referer: https://demo.gbif.org/species/2985237
Window size: width 1280 - height 918
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-07T14:35:05.884Z',mode:absolute,to:'2017-08-07T14:41:05.884Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-07T14:35:05.884Z',mode:absolute,to:'2017-08-07T14:41:05.884Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
there is only one species of [Parastemon urophyllus A.DC.](https://www.gbif.org/species/2985237) left in the backbone
