### ISSUE TITLE
The plant in the photo is a Carissa macrocarpa

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2916]
**The plant in the photo is a Carissa macrocarpa**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/34c86b81b3f3dd13d80e5f50cae2d997:001bbec7d643c51e94205be2908ba007fcde74abd657eb0878672217c0780f5212a32b16b70a3a8ad014304debaf3a00a2c82b00e4ea20612981b92280b42573)
System: Firefox 52.0.0 / Windows XP.0.0
Referer: https://www.gbif.org/occurrence/2643732426
Window size: width 1280 - height 643
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T20:03:35.161Z',mode:absolute,to:'2020-07-27T20:09:35.161Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T20:03:35.161Z',mode:absolute,to:'2020-07-27T20:09:35.161Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by ManonGros** [comment]
Voted on the suggested name on Pl@ntNet: https://identify.plantnet.org/observation/namerica/1004235332

**Comment by ManonGros** [comment]
Occurrence removed from GBIF dataset.
