### ISSUE TITLE
The plant in the photo is a Mardsenia floribunda (Stephanotis floribunda)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2918]
**The plant in the photo is a Mardsenia floribunda (Stephanotis floribunda)**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/884b419ce064c52bbec3c5e2a9ad8dab:9de6a5eec22364bb3dfa508aaf8ce1cd7f63ff8629c393c05fe60b9b540b2d1b6f89f7e5b023f7c696682e945d2c765e249535d4ec9bef3fff0d2b756eb7431f)
System: Firefox 52.0.0 / Windows XP.0.0
Referer: https://www.gbif.org/occurrence/2643989861
Window size: width 1280 - height 643
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T20:16:41.182Z',mode:absolute,to:'2020-07-27T20:22:41.182Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-27T20:16:41.182Z',mode:absolute,to:'2020-07-27T20:22:41.182Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by ManonGros** [comment]
Voted on the suggested name on Pl@ntNet: https://identify.plantnet.org/observation/weurope/1004708809

**Comment by ManonGros** [comment]
Occurrence removed from GBIF dataset.
