### ISSUE TITLE
Using maps API.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2920]
**Using maps API.**

Hey I need help using the maps API for an external project. I don't know if your familiar with Bubble.io but I am trying to find the right headers and parameters to add to my project. Please help. This is a "no code" platform I am using.

-----

Github user: @kingwiss
User: [See in registry](https://www.gbif.org/api/feedback/user/ac57715a8dd666b8c8f3b8ffc0f2ece7:8cdb51c1246f66b3dcaee5325534a053782646df14892ce1ed528274c81322633e37ffebf8b86f59b0c53133033bbe20198da090cb0a8f8d88607e1c8dcce2d7)
System: Chrome Mobile 84.0.4147 / Android 0.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 412 - height 413
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-29T00:54:11.760Z',mode:absolute,to:'2020-07-29T01:00:11.760Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-29T00:54:11.760Z',mode:absolute,to:'2020-07-29T01:00:11.760Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
Dear Mr. King,
I would recommend that you look at these two resources that deal with the GBIF map API feature:
https://www.gbif.org/developer/maps 
https://data-blog.gbif.org/post/gbif-maps-api-using-r-and-leaflet/

Regretfully, I am not familiar with bubble.io
