### ISSUE TITLE
Source not consistently mentioned for vernacular names/descriptions of species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2921]
**Source not consistently mentioned for vernacular names/descriptions of species**

For most vernacular names, a source (dataset) is mentioned (search "Goudvis" in https://api.gbif.org/v1/species/4286942/vernacularNames?limit=100):

```json
{
"taxonKey": 4286942,
"vernacularName": "Goudvis",
"language": "nld",
"country": "NL",
"area": "Netherlands",
"source": "Catalogue of Life",
"sourceTaxonKey": 142921839
}
```

For some however it is not, even though a `sourceTaxonKey`  (https://www.gbif.org/species/141117240) and thus the source dataset (https://www.gbif.org/dataset/98940a79-2bf1-46e6-afd6-ba2e85a26f9f) is known: 

```
{
"taxonKey": 4286942,
"vernacularName": "Goudvis",
"language": "nld",
"sourceTaxonKey": 141117240
},
```

The missing source is also a problem for e.g. descriptions (https://api.gbif.org/v1/species/4286942/descriptions?limit=100):

```json
{
"key": 57575036,
"taxonKey": 4286942,
"type": "native range",
"language": "eng",
"description": "Asia",
"sourceTaxonKey": 141117240
}
```

Can this be fixed so it is consistent across all vernacular names/desciptions?

-----

Github user: @peterdesmet
User: [See in registry](https://www.gbif.org/api/feedback/user/070049b522671036c5f6cc076f43a2fd:ef5461c156624f51e5ed048974b20dc359b10e2539f87aaf16afb210284718d7e01eb444da605998f373e03b233a840e093fa776cd586382fad0d7d7a5a4d278)
System: Chrome 84.0.4147 / Mac OS X 10.14.6
Referer: https://www.gbif.org/species/4286942
Window size: width 1194 - height 717
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-30T08:34:41.515Z',mode:absolute,to:'2020-07-30T08:40:41.515Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-30T08:34:41.515Z',mode:absolute,to:'2020-07-30T08:40:41.515Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
Fixed, see https://github.com/gbif/gbif-api/issues/56
