### ISSUE TITLE
Suspicious occurrence records of Nilaparvata lugens (Stål, 1854).

### ISSUE THREAD

**Issue by kongsol** [gbif/portal-feedback#2922]
I think these samples of _N. lugens_ occurrence records are suspicious.

https://www.gbif.org/occurrence/2304398798
https://www.gbif.org/occurrence/2305131140
https://www.gbif.org/occurrence/2305721081
https://www.gbif.org/occurrence/2306810572
https://www.gbif.org/occurrence/2309535077
https://www.gbif.org/occurrence/2310765351

This species only reported for East Asia, Southern Asia, South East Asia, Oceania (https://www.cabi.org/isc/datasheet/36301/).

Furthermore, when I tracked the reference for the sample (http://europepmc.org/article/MED/29337073), I could find this sentence.

> A laboratory-maintained strain of _N. lugens_ exhibiting susceptibility to imidacloprid (NLS) and eight field strains of BPH collected from Thailand (NLF1), Vietnam (NLF2, NLF3), Indonesia (NLF4) and India (NLF5, NLF6, NLF7, NLF8) were reared in the laboratory on whole rice plants (Oryza sativa L. ssp.) under controlled environmental conditions (26°C/16h photoperiod).

So I think those samples were georeferenced with the locality of the laboratory, not the original occurrence record of the species.

**Comment by ManonGros** [comment]
This is an other issue concerning data from the [Geographically tagged INSDC sequences](https://www.gbif.org/dataset/ad43e954-dd79-4986-ae34-9ccdbd8bf568).

datasetKey: ad43e954-dd79-4986-ae34-9ccdbd8bf568
publisherKey: ada9d123-ddb4-467d-8891-806ea8d94230

**Comment by jhnwllr** [comment]
Records in original issue have been deleted but I think the user is referring to these: 

https://www.gbif.org/occurrence/search?dataset_key=d8cd16ba-bb74-4420-821e-083f2bac17c2&has_coordinate=true&taxon_key=2056628&advanced=1&geometry=POLYGON((-9.49218%2044.96484,0.35157%2044.96484,0.35157%2052.83984,-9.49218%2052.83984,-9.49218%2044.96484))

**Comment by kongsol** [comment]
> Records in original issue have been deleted but I think the user is referring to these:
> 
> https://www.gbif.org/occurrence/search?dataset_key=d8cd16ba-bb74-4420-821e-083f2bac17c2&has_coordinate=true&taxon_key=2056628&advanced=1&geometry=POLYGON((-9.49218%2044.96484,0.35157%2044.96484,0.35157%2052.83984,-9.49218%2052.83984,-9.49218%2044.96484))
