### ISSUE TITLE
How can I find the coordinates of the two findings of Tetrapygus niger in Patagonia?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2923]
**How can I find the coordinates of the two findings of Tetrapygus niger in Patagonia?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b098228a9db6c072a85086235c03b34d:ecfbfcd5f2e817c823e4b24cc3277c6b4e3a79c55e30ce9e03028673dc97930577a2a9fb6be75957ac4656ceea97864a730dfdd71226ec81f64ef753a7621189)
System: Chrome 84.0.4147 / Windows 10.0.0
Referer: https://www.gbif.org/species/5842764
Window size: width 1920 - height 920
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-31T21:26:39.238Z',mode:absolute,to:'2020-07-31T21:32:39.238Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-07-31T21:26:39.238Z',mode:absolute,to:'2020-07-31T21:32:39.238Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by tucotuco** [comment]
I'm curious why you think there should be just two "findings". A search for
Tetrapygus niger (https://www.gbif.org/occurrence/search?taxon_key=5842764)
shows many occurrences from Chilean Patagonia, many with coordinates. Any
that don't you would have to georeference from the information in the
geography and locality fields.

**Comment by jlegind** [comment]
Tuco gave a sufficient reply.
User was contacted via email.

**Comment by ManonGros** [comment]
@jlegind please forward the reply to the user if you haven't already, thanks!
