### ISSUE TITLE
common misspelling

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2924]
**common misspelling**

The correct name is:

Spirontocaris liljeborgii (Danielssen, 1859)

http://www.marinespecies.org/aphia.php?p=taxdetails&id=107531

regards, Andreas

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5ab0b1a434d365471db56a3c07046516:b270d574be0d1da1dd6e280ff8d2a1639c910c5487bed28d452304120df3df3da1f6575375d597a8ff292d0b218ab46217dc843e29beba118e5fb5db0062945e)
System: Opera 69.0.3686 / Windows 10.0.0
Referer: https://www.gbif.org/species/2226308
Window size: width 1595 - height 992
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-03T10:51:37.897Z',mode:absolute,to:'2020-08-03T10:57:37.897Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-03T10:51:37.897Z',mode:absolute,to:'2020-08-03T10:57:37.897Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by jhnwllr** [comment]
Appears to be fixed:
https://www.gbif.org/species/2226312
Original species has been deleted.
