### ISSUE TITLE
Special characters not rendered in authorship of accepted names

### ISSUE THREAD

**Issue by damianooldoni** [gbif/portal-feedback#2925]
Butterfly specialist and colleague Dirk Maes (@dirkmaes33) needs accurate authorship names and showed me this suspect behavior of the GBIF backbone. Unfortunately I don't find immediately a reason for it, so I write this issue. 

**Some** author names containing special characters are mispelled in the GBIF Backbone (e.g. a instead of ä, u instead of ü, e instead of é) while they are correctly written in the source. Examples:

GBIF Backbone scientificname | key | Source scientificname | sourceTaxonKey 
--- | --- | --- | ---
_Orthosia cruda (Denis & Schiffermuller, 1775)_ | [1798933](https://api.gbif.org/v1/species/1798933) | _Orthosia cruda Schiffermüller, 1776_ | [110476419](https://api.gbif.org/v1/species/110476419)
_Athrips rancidella (Herrich-Schaffer, 1854)_ | [5122232](https://api.gbif.org/v1/species/5122232) | _Athrips rancidella Herrich-Schäffer, 1855_ | [110382356](https://api.gbif.org/v1/species/110382356)
_Acompsia antirrhinella Milliere, 1866_ | [1852185](https://api.gbif.org/v1/species/1852185) | _Acompsia antirrhinella Milliére, 1868_ | [110381699](https://api.gbif.org/v1/species/110381699)

I wrote "**some**" as I noticed that this behavior doesn't happen for this other name (synonym): 
_Taeniocampa cruda (Denis & Schiffermüller, 1775_, key = [9614504](https://www.gbif.org/species/9614504). Or this accepted genus: _Acompsia Hübner, 1825_, key = [1852176](https://www.gbif.org/species/1852176).

Any idea about it? Thanks in advance and keep up the good work! :+1:

**Comment by damianooldoni** [comment]
Hi, any update?
@dirkmaes33 noticed that this issue is still present.
I checked a little more and first I thought that the reason behind the absence of special characters in GBIF Backbone was the absence of special characters in some datasets linked to the taxon. Reusing the first example above, [Orthosia cruda (Denis & Schiffermuller, 1775)](https://www.gbif.org/species/1798933), two datasets linking to this GBIF Backbone taxon mention the species **without umlaut**:  
- https://www.gbif.org/species/123464309
- https://www.gbif.org/species/137268090

However, this is the same situation of [Acompsia Hübner, 1825](https://www.gbif.org/species/1852176) which has also two datasets where the species appears without umlaut:
- https://www.gbif.org/species/123416512
- https://www.gbif.org/species/137261593

So, I still do not  understand why sometimes the umlaut is returned, sometimes not. Any update about this is very welcome. Thanks again.

**Comment by mdoering** [comment]
It is a problem case by case depending on which source provides the name and authorship to the Backbone.
We do not standardise authorships across names, but take it as it comes from the primary source.

In case of Athrips rancidella (Herrich-Schaffer, 1854) this is Fauna Europaea which misses the Umlauts:
https://www.gbif.org/species/123422519

COL does it right, but is less trusted for its butterfly taxonomy:
https://www.catalogueoflife.org/data/taxon/5W8HM

**Comment by mdoering** [comment]
As the FauEu Lepidoptera DwC-A is a static one we don't get any updates for I will fix the Umlauts for the most prominent authors:

 - Herrich-Schaffer -> Herrich-Schäffer
 - Schiffermuller -> Schiffermüller
 - Milliere -> Milliére

The facet of the [most frequent authors in FauEu Lepidoptera](http://api.catalogueoflife.org/dataset/3LR/nameusage/search?facet=authorship&limit=0) looks correct.

**Comment by mdoering** [comment]
The full Fauna Europaea dataset was also fixed for the above authorships

**Comment by damianooldoni** [comment]
Thanks, @mdoering for working on this. Any idea when this patch will go in production and will stream to the GBIF Backbone?

**Comment by mdoering** [comment]
The FauEu dataset is already fixed in prod and I am working on a new backbone right now - hope this is a matter of a few weeks at most.
