### ISSUE TITLE
Missing link on an image in "Citizen Science" page (JA translation)

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/portal-feedback#2927]
The photo in the middle of "Citizen science" page in Japanese has a missing link https://www.gbif.org/ja/citizen-science

<img width="843" alt="Screen Shot 2020-08-03 at 6 30 26 PM" src="https://user-images.githubusercontent.com/61566113/89205094-72348f00-d5b7-11ea-8d25-2c2d35e03cdb.png">

The current link in the broken image is this https://images.ctfassets.net/q553fnlofhvs/1lbMY6pWNaiQc0mESmquK6/cd6a552348d6d2ad637846064b1ef5bf/ecsa_member.jpg

**Comment by dnoesgaard** [comment]
I'm not sure what the purpose of this image was, so I've removed it.
