### ISSUE TITLE
This is a chrysomelid as indicated, not a megachilid.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2930]
**This is a chrysomelid as indicated, not a megachilid.**

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/0d74a04c8ecea1da10665c6cc4320ac5:8752ecb4152ccd2c1dbe7aaf2edb6befa59fd47ed86565360115f2e625e78c7c800dba0eba3089c53741e65731640387dae5ebc553a354ce92deabcd7d031c94376a8de8effdc23f42ce5a6594377ce2)
System: Chrome 84.0.4147 / Mac OS X 10.15.6
Referer: https://www.gbif.org/occurrence/658264657
Window size: width 1453 - height 792
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-05T22:41:21.340Z',mode:absolute,to:'2020-08-05T22:47:21.340Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-05T22:41:21.340Z',mode:absolute,to:'2020-08-05T22:47:21.340Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: aae308f4-9f9c-4cdd-b4ef-c026f48be551
publishingOrgKey: b554c320-0560-11d8-b851-b8a03c50a862

**Comment by ManonGros** [comment]
It seems like the issue has to do with a missing name in the taxonomy. The Backbone doesn't contain Stolas costaricensis: https://www.gbif.org/species/search?q=Stolas%20costaricensis

**Comment by ahahn-gbif** [comment]
This is a **taxon matching issue**, similar to #3360 and #3110.

Propose: If a genus name exists that is identical with the verbatim genus name, and in the same family as given in the verbatim data, but the species name not available in the backbone, then taxon matching should match the name to the higher rank (genus), and not attempt to fuzzy-match it to a different genus name in a different family, even if the genus-epithet combination is similar.

@mdoering does this make sense, and is it doable, or is the extension of taxon data resources the only way to prevent this type of matching error?

**Comment by mdoering** [comment]
This is doable, but a major change in how we match with potential changes all over. It might be all good changes though, I like the proposal. The only weak part is "if the verbatim family matches". Do we require a family to be present and match? What if there is only an order given? I guess sticking with just family initially safe guards us from unwanted side effects

**Comment by ahahn-gbif** [comment]
> The only weak part is "if the verbatim family matches".

Right... might better be formulated along the lines of "if the next higher taxonomic rank given matches". The main point I was trying to make here was rather from the opposite angle: if _the next higher rank of the proposed fuzzy match contradicts_ the one in the verbatim data, then do not fuzzy-match, and rather match upwards in taxonomic rank with the same spelling and higher taxonomy

**Comment by mdoering** [comment]
Agree, thats a more robust logic!
