### ISSUE TITLE
These two locations are erroneous. The location description text in both cases state that these records are from the Okanagan in BC.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2934]
**These two locations are erroneous. The location description text in both cases state that these records are from the Okanagan in BC.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/40a1e066e8755e43a4174b4e63ae49c6:8ca4b8c5a3e116ba07e3c8a5632d54106b92df2afdd6ff79f5f73962084a766d77e1eee755dcd16fa8f7921225d13448492e9a9bd904f7d5ce626ccc3b1957bb)
System: Firefox 78.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/occurrence/search?geometry=POLYGON((-112.49732%2040.64634,-79.86959%2040.64634,-79.86959%2053.69743,-112.49732%2053.69743,-112.49732%2040.64634))&has_coordinate=true&has_geospatial_issue=false&taxon_key=3015794
Window size: width 1432 - height 708
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-07T19:38:12.776Z',mode:absolute,to:'2020-08-07T19:44:12.776Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-07T19:38:12.776Z',mode:absolute,to:'2020-08-07T19:44:12.776Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Publishers contacted by email.

**Comment by TADatTRT** [comment]
The erroneous data were transcribed from the specimen label. Subsequently, but after the data upload to GBIF, these data were corrected as shown below. 

TRT00004299 50.585705, -119.121073
TRT00004300 50.471476  -119.150475

Thank you for catching this problem.

**Comment by TADatTRT** [comment]
Ummm... corrected using Google Earth, using the location descriptions, which are sufficiently detailed to make for considerable accuracy (greater, in fact, than the recorded uncertainty).

**Comment by ManonGros** [comment]
The records are now up to date on GBIF!
