### ISSUE TITLE
publisher located at null island

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#294]
**publisher located at null island**

publisher located at null island - I guess it should be removed or updated?

-----
fbitem-publisher4e50cb40-ecf4-45d5-a325-9fcbd7489463
Reported by: @mortenhofft
System: Chrome 59.0.3071 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/publisher/4e50cb40-ecf4-45d5-a325-9fcbd7489463
Window size: width 1918 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-09T12:03:58.934Z',mode:absolute,to:'2017-08-09T12:09:58.934Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-09T12:03:58.934Z',mode:absolute,to:'2017-08-09T12:09:58.934Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
28 GB-endorsed publishers have this issue; suspect a database default or export artifact (coordinates are -1/-1). Replacing with NULL values instead.

**Comment by jlegind** [comment]
All publishers having coordinates -1,-1 have had them reset to DEFAULT (empty).
