### ISSUE TITLE
I have a doi, https://doi.org/10.15468/dl.wmbryk. How can i download the datafile involved?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2949]
**I have a doi, `https://doi.org/10.15468/dl.wmbryk.` How can i download the datafile involved?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0e93f04987904309e59dcc96ec9d3599:a373842c07470982c95ea483dabfd0d327f1f328ad1179845f5fc2d7b35e08953763c9ce4f8a7be78e0db83e1ea05fc3f25b33953e7ae8545b3b2005e495db44)
System: Chrome 84.0.4147 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?q=https:~2F~2Fdoi.org~2F10.15468~2Fdl.wmbryk&contentType=literature&gbifDownloadKey=https:~2F~2Fdoi.org~2F10.15468~2Fdl.wmbryk
Window size: width 1985 - height 941
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-08T14:47:05.812Z',mode:absolute,to:'2020-08-08T14:53:05.812Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-08T14:47:05.812Z',mode:absolute,to:'2020-08-08T14:53:05.812Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Enter https://doi.org/10.15468/dl.wmbryk into a browser and click the 'Download' chip in the upper right of the page.

**Comment by ManonGros** [comment]
@kcopas @MattBlissett did you write back to the user? If the answer is only posted on GitHub, it is unlikely that they will see it.

**Comment by kcopas** [comment]
Three years ago?

I don't have access to email addresses, so nothing would've come direct from me, though…

**Comment by MattBlissett** [comment]
I didn't. I closed it as it seemed too late.
