### ISSUE TITLE
Newsletter confirmation appears in search

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#295]
**Newsletter confirmation appears in search**

Is that on purpose? There is a flag in Contentful to hide it from search results

-----
fbitem-e15538ca708aa259304b7008fa7e85e62d53db7f
Reported by: @mortenhofft
System: Safari 10.1.2 / Mac OS X 10.10.5
Referer: https://www.gbif-uat.org/newsletters/subscribed
Window size: width 1440 - height 811
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-10T05:22:20.780Z',mode:absolute,to:'2017-08-10T05:28:20.780Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-10T05:22:20.780Z',mode:absolute,to:'2017-08-10T05:28:20.780Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I've decided it to hide it - undo if on purpose
