### ISSUE TITLE
downloading coordinate data and loading in Excel incorrect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2951]
**downloading coordinate data and loading in Excel incorrect**

Hi, I am doing research about the occurence of plant species on the Kai islands. When i download the data as a csv file and then load the data in Excel the decimal coordinates are incorrect. As in there are no decimals, there is no comma or  period so the numbers are impossibly large for coordinates. Can you help me with this? I do really hope there is a way to fix this so i won't have to do it manually. Thankyou!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ac6ef8cd34c821abe910cba4ddf988b0:e773726f90472cca8dd0946d266969720330ca1ac4c19669beb67601adfa018c8fda46ee4635065aa243a79330c219fd5ee0a27d271961c4bc22c63817e24bba)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/search?q=coordinates%20download%20to%20excel
Window size: width 1280 - height 648
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-10T14:06:44.492Z',mode:absolute,to:'2020-08-10T14:12:44.492Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-10T14:06:44.492Z',mode:absolute,to:'2020-08-10T14:12:44.492Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
Dear user,

From the Data tab in Excel, you need to use the 'From Text' function in the _Get External Data_ section of the top panel.
Here you select the csv download file and choose UTF-8 as the encoding and tab as the column separator.
No the really important step is this: 
Under the Text Import Wizard - step 3 of 3; you need to select decimalLatitude and longitude columns and press the 'Advanced' button. Here remove the Thousands separator and change the Decimal separator to the desired format.
![coordinate_decimal_formatting](https://user-images.githubusercontent.com/5330066/89874745-8cc0c680-dbbc-11ea-9f12-d6b72fabebf6.png)

This will preserve the coordinate numbers format.

**Comment by jlegind** [comment]
User contacted.
