### ISSUE TITLE
Diodora philippiana

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2955]
**Diodora philippiana**

This species is not Diodora philippiana (Dunker, 1846) which occurs on the Cape Verde Islands. The label on the picture is correct, but Fissurella philippiana Reeve, 1850 is a synonym of Fissurella radiosa Lesson, 1831 from Chile. Therefore wrongly interpreted by Naturalis as a synonym of Diodora philippiana (Dunker, 1846). Please correct.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/697763750c7d49f5dba4081a949fa387:1a3c91a3ea5479b1e3879c9d115ad5396b665b1fea60480a767a3686b5adc7e055be25f54dc5372ec73a9717a2335c509d95656ab5970e33f843e6b6c73f4d30)
System: Firefox 79.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2443983632
Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-17T12:04:39.498Z',mode:absolute,to:'2020-08-17T12:10:39.498Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-17T12:04:39.498Z',mode:absolute,to:'2020-08-17T12:10:39.498Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: d962a7dc-2183-4824-bb88-5e0ba14ec62d
publishingOrgKey: 396d5f30-dea9-11db-8ab4-b8a03c50a862

**Comment by jeroencreuwels** [comment]
I have contacted the Mollusc curator at Naturalis to have a look at this notification.

**Comment by jhnwllr** [comment]
@jeroencreuwels  issue appears to be solved.
