### ISSUE TITLE
Hi, I was wondering if there is a way to find out what geodetic datum/coordinate system has been used for occurrence records? I can see information such as "geodetic datum assumed: WGS84", but what is this assumption based on? Thank you for your help

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2958]
**Hi, I was wondering if there is a way to find out what geodetic datum/coordinate system has been used for occurrence records? I can see information such as &quot;geodetic datum assumed: WGS84&quot;, but what is this assumption based on? Thank you for your help**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e6d8cecb6132e4a788cf3380ab4b9370:ca0f8eed5c6bca10ca1d6aaf1e0c6b5612e1ac137077cf115192f5eb7591cf614ab0ce8f3f1f4ddbb08ed6722bc36d13c02063ee707ece6ab5c4ffc91a5493b3)
System: Chrome 84.0.4147 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-18T17:58:52.898Z',mode:absolute,to:'2020-08-18T18:04:52.898Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-18T17:58:52.898Z',mode:absolute,to:'2020-08-18T18:04:52.898Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by tucotuco** [comment]
I believe this is based on the fact that no explicit (nor unambiguously
understandable) geodetic datum was provided in the original data.

**Comment by MattBlissett** [comment]
That's right.

I replied by email:

Occurrence records published to GBIF.org use several datums/coordinate systems.  As part of GBIF's data processing, we convert all records to WGS84.

Where the record is provided without a geodetic datum, we assume it to be WGS84 as this is the most common -- used by GPS etc.  In this case, the "geodetic datum assumed" issue is added to the record.  It would be reasonable to add an additional uncertainty to records with this issue (around 5km depending on location), although this is not yet done by GBIF's processing.
