### ISSUE TITLE
CSS issue: double border on number of occ/citations

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2959]
**CSS issue: double border on number of occ/citations**

On the dataset search page (and maybe elsewhere), datasets list the number of occurrences and citations. The boxes have double borders (and double hover), which I think is not intentional.

-----

Github user: @peterdesmet
User: [See in registry](https://www.gbif.org/api/feedback/user/c35023584f01daccc5aa5722da8d6c2f:503bf50889c80135293dff421eb415e5470ee235dba683f658c2917545241f5f4426e36431bbc0ba45063a752b658e169deff2adfb1a8eda08c876b6c65a2e60)
System: Chrome 84.0.4147 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/search?project_id=meetnetten.be
Window size: width 1386 - height 701
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-20T09:09:49.054Z',mode:absolute,to:'2020-08-20T09:15:49.054Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-20T09:09:49.054Z',mode:absolute,to:'2020-08-20T09:15:49.054Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by peterdesmet** [comment]
<img width="753" alt="Screenshot 2020-08-20 at 11 12 14" src="https://user-images.githubusercontent.com/600993/90751421-67c40600-e2d6-11ea-9ec9-633fc672eec9.png">
