### ISSUE TITLE
Suspicious georeferencing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#296]
**Suspicious georeferencing**

This dataset seems suspicious with cats in the sea and with suspicious dates

https://demo.gbif.org/occurrence/map?dataset_key=4ffe66a0-6c8b-11de-8226-b8a03c50a862&amp;has_coordinate=true&amp;has_geospatial_issue=false&amp;taxon_key=9703

We should contact the provider, as the data is to sparse to get caught out with georeferencing checks.

-----
fbitem-dataset4ffe66a0-6c8b-11de-8226-b8a03c50a862
Reported by: @timrobertson100
System: Chrome 59.0.3071 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/dataset/4ffe66a0-6c8b-11de-8226-b8a03c50a862
Window size: width 1216 - height 766
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-12T13:21:43.974Z',mode:absolute,to:'2017-08-12T13:27:43.974Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-12T13:21:43.974Z',mode:absolute,to:'2017-08-12T13:27:43.974Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
28 NBN publishers have this issue - coordinates of publisher location are -1/-1, probably a database default or export artifact. Replacing with NULL/NULL for the time being

**Comment by ManonGros** [comment]
The publishers have been notified that these records were flagged.

**Comment by ManonGros** [comment]
The records have been corrected on ALA side (but their new DwC archive hasn't been generated yet).
