### ISSUE TITLE
wrong spelling in generic name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2962]
**wrong spelling in generic name**

Two records of Polyommatus elvira (Eversmann, 1854) are wrongly placed in the non-existing genus Polyomamtus (clearly a typo...)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a6732badc39ec9c04266aa564d3a5fb6:97716a505d57bcfcd987adb3d2c777891fcb463da5102e7df0848636c1e1e985908ffed9b3f0d7ecb596863dcc1543ab69e203532f65f985b6a6c6198b00148e)
System: Firefox 79.0.0 / Windows 10.0.0

Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-24T06:10:30.105Z',mode:absolute,to:'2020-08-24T06:16:30.105Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-24T06:10:30.105Z',mode:absolute,to:'2020-08-24T06:16:30.105Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Name concerned: https://www.gbif.org/species/9115120

**Comment by ManonGros** [comment]
The type from which this spelling mistake originated was corrected: https://www.gbif.org/occurrence/1055533314
Hopefully the name will be corrected in the backbone taxonomy update.

**Comment by jhnwllr** [comment]
species mis-spelling is deleted. Name is missing form backbone still. Closing issue...
