### ISSUE TITLE
message:Invalid DwC archive for dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2969]
**message:Invalid DwC archive for dataset**

New dataset from first-time UK publisher is not indexing: 
https://www.gbif.org/dataset/d740f242-6c26-4229-9a8f-b63bfab63dc6 

Logs suggest the DwC-A is missing some pieces. NBN is hosting the dataset—perhaps something's gone wrong in the export?

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/308c391213539509576becc8316fed3a:de21448cddda2547e56c4ac57c264315b38a3d031a05849196f00b273c8f82a26f5e259d2e016a03ad2dbbef0871a05b1192d924a7d7ba75a9c595e9d4a4dd2e)
System: Firefox 80.0.0 / Mac OS X 10.15.0

Window size: width 1535 - height 925
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-31T07:07:09.676Z',mode:absolute,to:'2020-08-31T07:13:09.676Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-31T07:07:09.676Z',mode:absolute,to:'2020-08-31T07:13:09.676Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
The DWCA contains only an eml.xml (metadata description).  @reupost, is this intended to be a metadata-only publication to GBIF, or will records appear later?

**Comment by sophiathirza** [comment]
@MattBlissett yes, we will add the records when the manuscript is accepted. It is in final revision now.
