### ISSUE TITLE
Download activity reports for a dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2970]
**Download activity reports for a dataset**

Is there a way to download metadata from download events in a datasets activity tab? For instance, the San Diego Natrual History Museum Entomology Department dataset activity tab currently has "2,420 download events". I would love to get a downloadable table of the metadata from those events (i.e., date, occurrences from dataset, etc.).  Thanks, Michael

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4b4d42d69f0977970e1e30b0c84e3f62:606690c5cd99aba73bf7f7c54054d3847c5071278f74e008d29afc3d0a0a861849db46ede8d86eb2fec746210d2888344e3bebe144ecf47f249231de833f80a0)
System: Chrome 84.0.4147 / Windows 10.0.0

Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-31T15:29:26.094Z',mode:absolute,to:'2020-08-31T15:35:26.094Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-08-31T15:29:26.094Z',mode:absolute,to:'2020-08-31T15:35:26.094Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
Replied by email.
