### ISSUE TITLE
The page reports 0 Occurances

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2971]
**The page reports 0 Occurances**

The description states there are 186687 occurrence records but there is 0 displayed in the Occurrence box

-----

Github user: @DrMattG
User: [See in registry](https://www.gbif.org/api/feedback/user/c1533a48e1a62cb391d479898eaa8678:65a8953d681974ddb686186c2d3ea0e240320d04281bc81e7844e6f1cf68722bb84e77c52cb6ac57f747fa13cb2797bc258f1728dc06ee17a0b6ece4f557a22a)
System: Edge 18.18363.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/d740f242-6c26-4229-9a8f-b63bfab63dc6
Window size: width 1662 - height 818
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-01T06:55:56.940Z',mode:absolute,to:'2020-09-01T07:01:56.940Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-01T06:55:56.940Z',mode:absolute,to:'2020-09-01T07:01:56.940Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Thanks @DrMattG.

We already have this reported as #2969, so I will close this issue.
