### ISSUE TITLE
WDCM'S CONTACT INFORMATION

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#298]
**WDCM&#39;S CONTACT INFORMATION**

The contact address is in Japan, but the contact persons are in China. After check in their website, the contact address should be:

Information Network Center, Institute of Microbiology, Chinese Academy of Sciences
1 West Beichen Road, Chaoyang District, Beijing 100101, China

-----
fbitem-publisher8273e420-46f3-11d8-aa2e-b8a03c50a862

System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://demo.gbif.org/publisher/8273e420-46f3-11d8-aa2e-b8a03c50a862
Window size: width 1920 - height 1045
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-14T13:10:07.002Z',mode:absolute,to:'2017-08-14T13:16:07.002Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-14T13:10:07.002Z',mode:absolute,to:'2017-08-14T13:16:07.002Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
This is very helpful feedback. Updating the centrally maintained contact information for a publisher based on anonymous feedback is not strictly within policy though. Would you mind identifying yourself, please? Feel free to follow up with a message to helpdesk@gbif.org, if you prefer. Many thanks in advance.

**Comment by Maofangisme** [comment]
Hey, thank you very much for replying. I am Maofang :) I will remember to put in my information the next time.

**Comment by ManonGros** [comment]
Done.
