### ISSUE TITLE
GBIF Network page not loading

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2981]
**GBIF Network page not loading**

This may be temporary, but the green buttons below the map showing the number of participants etc is not showing, and there is a message 'Not all data is currently available ...'

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/07e8859b2e5cf2394020555c7c9f2937:9c674b8cf4a1134f6fc2752aa37ff8921058822a9bf801b18f65998da71f843603eea865a63e909d89318938abe8a81bd2e044fde8c004ed763605b89efa4cf0)
System: Chrome 85.0.4183 / Mac OS X 10.14.6
Referer: https://www.gbif.org/the-gbif-network
Window size: width 1897 - height 1305
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-04T07:35:57.237Z',mode:absolute,to:'2020-09-04T07:41:57.237Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-04T07:35:57.237Z',mode:absolute,to:'2020-09-04T07:41:57.237Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by timhirsch** [comment]
Working now .. obviously was a temporary thing
