### ISSUE TITLE
That species does not exist:

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2985]
**That species does not exist:**

The correct GBIF species ID is:

https://www.gbif.org/species/10517921

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b89d2fecdf03192b4baadaeedffd6b61:f783d22218b9fdfdfe8f70207733c5b7a9a3360525f3beac5c2708283f5504f0928709ab37622cefc2759c684e6df8a9ff36ca10ecc17e669670a1ce34e96237)
System: Opera 70.0.3728 / Windows 10.0.0
Referer: https://www.gbif.org/species/4418651
Window size: width 2023 - height 1040
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-07T09:23:45.635Z',mode:absolute,to:'2020-09-07T09:29:45.635Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-07T09:23:45.635Z',mode:absolute,to:'2020-09-07T09:29:45.635Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
We need some proof for `Leptestheria dahalencis (Ruppell, 1837)` from FaEu being a misspelling and `Leptestheria dahalacensis` being the real name. FaEu even lists the basionym.
Can someone verify this before we apply manual changes?

**Comment by ManonGros** [comment]
I tried to contact Fauna Europea by email to ask if they could check but the addresses I used bounced back. I also contacted a member of their steering committee. I hope that I will get an answer.

**Comment by ManonGros** [comment]
I got a reply and unfortunately, Fauna Europea is no longer active.
That being said, I was told that this user is correct that the spelling from BOLD is correct. Indeed, a quick search shows many papers using the name Leptestheria dahalacensis (Rüppel, 1837) (for example https://doi.org/10.1007/s10750-007-0645-2 and https://doi.org/10.1007/BF00016681) but almost no literature mentioning the other spelling.
Plus it was pointed out to me that GeneBank also used the same spelling as BOLD: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?lvl=0&id=202083

@mdoering is that enough proof to apply a manual change?
