### ISSUE TITLE
Endorsement needed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2987]
**Endorsement needed**

Hello,

Yesterday I requested a space for my University to be accepted as publisher on GBIF. We currently are located in Guatemala and do not have a national Node for the endorsement. I was wondering if you could help us with this matter. Also, I enter my self as tech contact but I haven't received any email yet. I wanted to now if you could help us with this. The publisher name is Universidad del Valle de Guatemala, and this is the link to the profile https://www.gbif.org/publisher/5c1a4c27-795a-4294-aecc-46d7176706b7 

Thanks again for your help.

Zabdi López

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d57bbaa0c9bfaac93085eb666db4b792:f40c074ae89d7e6544fc0b76edb307f3c567e9913d5490a4b1b39f34c98146e2418eda0ba8de54b61d7e99dd3de61041e94607b28802a11faf78c0586e10f917)
System: Chrome 85.0.4183 / Mac OS X 10.15.6
Referer: https://www.gbif.org/node/7f48e0c8-5c96-49ec-b972-30748e339115
Window size: width 1440 - height 798
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-08T17:55:15.598Z',mode:absolute,to:'2020-09-08T18:01:15.598Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-08T17:55:15.598Z',mode:absolute,to:'2020-09-08T18:01:15.598Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
