### ISSUE TITLE
date format on events in Chinese

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2988]
**date format on events in Chinese**

When creating an event specifically aimed at a Chinese audience, I noticed that we show the correct format in search (https://www.gbif.org/zh/resource/search?contentType=event):

> 2020年9月11日

But on the event page itself (https://www.gbif.org/zh/event/6dYlPWsrTyOR9EZYGmewQM/gbif), the format is different:

> 11 九月 2020 (literally "11 September 2020")

I can't figure out if this is caused by Contentful, Crowdin or something else...

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/4eea2b25c0b378ebae7ac250ab665dd4:63777c9f52bc5c9783ca8d929e597389f375a61519d10d8b8aea5ffc5554599652d76534863360d1ad8ea8a8d71a33497e262fe79f088179d5654efb249d31a3)
System: Chrome 85.0.4183 / Mac OS X 10.15.6
Referer: https://www.gbif.org/event/6dYlPWsrTyOR9EZYGmewQM/webinar-on-gbif-data-use-and-citation-in-chinese
Window size: width 1434 - height 636
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-08T19:09:08.080Z',mode:absolute,to:'2020-09-08T19:15:08.080Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-08T19:09:08.080Z',mode:absolute,to:'2020-09-08T19:15:08.080Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I do not know chinese. Is one wrong or are they just different?

@thomasstjerne I believe you changed date formats at some point? Would you mind take a look?

**Comment by dnoesgaard** [comment]
The correct format is 

`<yyyy>年<m>月<d>日` for full date

as shown e.g. in event search results (https://www.gbif.org/zh/resource/search?contentType=event) and also in the header of occurrence pages.

Incidently, the month/year colum of occurrence search doesn't follow this format either—it reads e.g. `2020 一月` when it should read `2020年一月`

**Comment by MattBlissett** [comment]
年 means year (harvest) and 月 means month (it's a drawing of the moon: https://en.wiktionary.org/wiki/%E6%9C%88#Glyph_origin ) and 日 means sun (it's a drawing of the sun: https://en.wiktionary.org/wiki/%E6%97%A5#Glyph_origin )

So Chinese dates are very easy. Today is 2020th year, 9th month, 11th day.

> Incidently, the month/year column of occurrence search doesn't follow this format either—it reads e.g. 2020 一月 when it should read 2020年一月

It should read 2020年1月, as western numbers are generally preferred for scientific/data/most purposes. 

My "incidentally" is that the English dates are mixed up in various places (dataset/publisher/installation pages), and when written in full should be in day-month-year order, i.e. 11 September 2020.

**Comment by MattBlissett** [comment]
Also, Japanese has the same issue, and the same required format.
