### ISSUE TITLE
Global Red List categories have a confusing display

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2989]
**Global Red List categories have a confusing display**

They says "Present in Global".

This needs to be reworded, for example, "Global assessment", or just "Present" ("Absent" for extinct species).

"Present worldwide" or similar isn't appropriate -- elephants don't occur worldwide.

-----

User: [See in registry](https://www.gbif-uat.org/api/feedback/user/13b87f7624e11a84dfa9533768a3e4a3:830b6953d1286f29ffe65ec2d505b13b7e07db6166220fd2568c4d24edaa43a1beec40008bbeae71f028bc301daaa92c7bfa0ff20d711e4e44640c6ca07b4ca3)
System: Firefox 80.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif-uat.org/species/165549597
Window size: width 1920 - height 945
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-11T11:44:48.934Z',mode:absolute,to:'2020-09-11T11:50:48.934Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-11T11:44:48.934Z',mode:absolute,to:'2020-09-11T11:50:48.934Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I'm pretty sure this isn't structured data, but simply verbatim text strings. To do this the website would need a list of likely word to use for global in the most likely languages.
If we find this problematic, we should consider a more dry data presentation approach with a table or such
locality: global
status: present

It is less readable for most cases, but wont generate odd sentences.
