### ISSUE TITLE
View search result in the map

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#299]
**View search result in the map**

In the front page, I could choose different style to view data in the map (Classic hex, Classic, Orange dots, Osm, Green, Dark). But in the data search page, only orange dots is available (or I failed to find the options?). Will other types or the classic type be developed in occurrences search page? Personally, I prefer the classic one. Thanks.

-----
fbitem-632937989213bf4e43cb42556216fa1047383e29
Reported by: @Maofangisme
System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&advanced=1
Window size: width 1920 - height 1094
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-14T13:52:42.655Z',mode:absolute,to:'2017-08-14T13:58:42.655Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-14T13:52:42.655Z',mode:absolute,to:'2017-08-14T13:58:42.655Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi @Maofangisme I'm afraid we cannot have support for all those. We can do those really detailed maps only for precalculated maps (we precalculate all species, datasets, publishers, countries). But for arbitrary filters we can only do really coarse maps I'm afraid. We would love to, but we don't have the technology and machines to do so at this point. Perhaps in the future. But you are right of course, it would be very nice.
