### ISSUE TITLE
Year filter: include 2017

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#30]
**Year filter: include 2017**

It is not currently possible to choose 2017 on the slider. Also &quot;largerThan&quot; operator works as larger than or equal to, so you cant get 2017 records by choosing largerThan 2016.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
Reported by: t.stjernegaard@snm.ku.dk
System: Chrome 55.0.2883 / Mac OS X 10.10.2
Referer: https://demo.gbif.org/occurrence/search?dataset_key=84d26682-f762-11e1-a439-00145eb45e9a&amp;year=2016,*
Window size: width 1798 - height 1199
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-11T09:18:11.948Z',mode:absolute,to:'2017-01-11T09:24:11.948Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-11T09:18:11.948Z',mode:absolute,to:'2017-01-11T09:24:11.948Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you for reporting this bug. The issue has been fixed and deployed to production. You should be able to run your query now.
https://demo.gbif.org/occurrence/search?dataset_key=84d26682-f762-11e1-a439-00145eb45e9a&year=2017,*

> user informed per mail
