### ISSUE TITLE
suspicious records

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3001]
**suspicious records**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3495620139aae50487fd4babcf03a667:6d34fb7510dec6851bf31bf169453f33a2be0d573343ffbc8d394da90e62d338e921c9960ed00a3c699ed585f78d6322d800840f535bd8a3a87cf7475a6aa497)
System: Chrome 84.0.4147 / Windows 10.0.0
Referer: https://www.gbif.org/species/search?q=indigofera%20densiflora&qField=SCIENTIFIC
Window size: width 1920 - height 888
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-14T14:44:49.649Z',mode:absolute,to:'2020-09-14T14:50:49.649Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-14T14:44:49.649Z',mode:absolute,to:'2020-09-14T14:50:49.649Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
non-actionable current form I going to close.
