### ISSUE TITLE
Interpreting Data validator output

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3002]
**Interpreting Data validator output**

Hello,

I am trying to prepare data for eventual upload. I have run it through the Data validator to see how clean it is. I am confused by some of the output.Is there somewhere I can try and figure out how to fix the problems flagged in the data.

I can't seem to match up the lineNumber, with the data error given. For example in Recorded date mismatch with 9 errors, line 20001 doesn't match what is in the raw data.

Also how does the Resource integrity and Resource Structure errors relate to the data?

https://www.gbif.org/tools/data-validator/1580460395650

Any assistance that can be provided is greatly appreciated.

Many thanks,
Johno

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/56a32fdc7dd54af2f57a3a0971b71472:ccf6afe8d586e2155dac2aae40253a47b6d9aa4fb7984e1856ddb731f92627f9c4e2c0f8434aa589a91f618e8adce5a1926fdd8c470c224f4fcd6e86d4f8707f)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator/1580460395650
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-15T21:15:45.324Z',mode:absolute,to:'2020-09-15T21:21:45.324Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-15T21:15:45.324Z',mode:absolute,to:'2020-09-15T21:21:45.324Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
