### ISSUE TITLE
Can't change profile email?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3003]
**Can&#39;t change profile email?**

I can't seem to change my email address, even after disconnecting the social logins.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ea86748eba2f7da2a13fcce5096b36e3:b1f3f58fe9e7f658e97369d6c0a5fce17650da5bea6e8cd218307b8b99ae6fabac6463daf98808fb49055e871411ea6e5be63afbb77c0e3e90416d39e3b2113a)
System: Chrome 85.0.4183 / Mac OS X 10.15.6
Referer: https://www.gbif.org/user/profile
Window size: width 1147 - height 817
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-16T16:49:50.552Z',mode:absolute,to:'2020-09-16T16:55:50.552Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-16T16:49:50.552Z',mode:absolute,to:'2020-09-16T16:55:50.552Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@MortenHofft Could we display a message when editing user profiles?
Something like this:
"To update your email address, please contact helpdesk@gbif.org"

Otherwise, we could also allow users to update their address.

**Comment by MattBlissett** [comment]
https://github.com/gbif/informatics/issues/2

Mikhail is working on this, so it's probably fine to wait.
