### ISSUE TITLE
New species name Rallidens mcfarlanei Penniket 1966 to update.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3004]
**New species name Rallidens mcfarlanei Penniket 1966 to update.**

Hello,

This species is not on the GBIF backbone. The genus is on the GBIF backbone, referencing the same paper below.

Rallidens mcfarlanei Penniket 1966

This is the type species for the genus Rallidens. Reference as follows.

Penniket JG. 1966. Notes on New Zealand Ephemeroptera IV. A new siphlonurid subfamily: Rallidentinae. Records of the Canterbury Museum 8: 163-175.

It is also listed in this checklist by Pohe 2018. http://dx.doi.org/10.26021/500

A pdf can be provided if required.

Many thanks,
Johno

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/97179a92e2ede6be6a7df14c700e6928:2afea07b74c319113773934ea4f50f1787afbe82910642d840ff1945c5861b051ff2773012b62e0a5bd034b688be82f070e8bb39e73db391f0a7af84f5b3d6a1)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/tools/species-lookup
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-16T21:50:29.281Z',mode:absolute,to:'2020-09-16T21:56:29.281Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-16T21:50:29.281Z',mode:absolute,to:'2020-09-16T21:56:29.281Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by Museumdatacleaner** [comment]
I would note that it is on the backbone I think as Rallidens macfarlanei (https://www.gbif.org/species/7197021). Spelling needs to be amended rather than being added.

**Comment by jhnwllr** [comment]
Contacting CoL. Remember to cite dataset.

**Comment by jhnwllr** [comment]
Appears to be present in CoL and GBIF. 
Rallidens macfarlanei Penniket, 1966
https://www.gbif.org/species/7197021
