### ISSUE TITLE
Ligustrum vulgare vs Syringa vulgaris

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3008]
**Ligustrum vulgare vs Syringa vulgaris**

Hi I have been searching for observations of Ligustrum vulgare, but records returned for Syringa vulgaris - I don't think there are any taxonomic issues here  - maybe something mixed up in the gbif taxonomy? Cheers, Dave

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d2c272160e7452dfbcf12f3767cdefc7:17c058b361f15bb75572e2cf8d0ca8223bc429dc6e88349f8f053e8717de312c6ceb658bf0cd20f5363f09e6861f5d8582d1b8692e0072f651b5118581821612)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 2400 - height 1171
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-21T00:44:00.932Z',mode:absolute,to:'2020-09-21T00:50:00.932Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-21T00:44:00.932Z',mode:absolute,to:'2020-09-21T00:50:00.932Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The backbone considers Ligustrum vulgare L. a synonym of Syringa vulgaris L., I suspect that this is an error.

**Comment by ManonGros** [comment]
One more person reported this issue.
