### ISSUE TITLE
Not a preserved specimen

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3009]
**Not a preserved specimen**

Basis of record is incorrect. This is not a preserved specimen. Many (most!) of the records from EMBL-EBI suffer from this problem.

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/384728fad1a4bc30050e46b36659bb6b:cd89e5ec57883f2c749fda87e4bc820486755737c4a9206c309f7eb49994ca7cd8b50d8ffdae2b6f5b8621430a88fd8a68995054ab0166e118299a3802f87636b1c1e42b5732baac08a0eb69ca3f75cd)
System: Chrome 85.0.4183 / Mac OS X 10.15.6
Referer: https://www.gbif.org/occurrence/2309481263
Window size: width 1540 - height 899
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-21T16:52:40.272Z',mode:absolute,to:'2020-09-21T16:58:40.272Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-21T16:52:40.272Z',mode:absolute,to:'2020-09-21T16:58:40.272Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: ad43e954-dd79-4986-ae34-9ccdbd8bf568
publishingOrgKey: ada9d123-ddb4-467d-8891-806ea8d94230

**Comment by ManonGros** [comment]
It seems to me that the sequences were extracted from preserved specimens:
```A total of 10,647 ant specimens from 8 subfamilies, 61 genera and 1,155 species were tested for Wolbachia infection. Ninety-nine percent of these specimens were collected from the Malagasy region. [...]
Specimens were collected by Brian Fisher and the Malagasy Arthropod Team between 1996 and 2009. 
```
https://atrium.lib.uoguelph.ca/xmlui/handle/10214/7531

If not preserved specimen, what should the basis of record be in these cases?

**Comment by dshorthouse** [comment]
If we're strict about how we interpret the definition of `basisOfRecord`, "The specific nature of the data record." then this is a sequence. It is derived from a preserved specimen just as is a photograph. In essence, this is not an occurrence record. It's rather nonsensical to have other DwC terms populated like decimalLatitude and decimalLongitude for a sequence record.

**Comment by ManonGros** [comment]
relate to this issue: https://github.com/gbif/portal-feedback/issues/2188

**Comment by jhnwllr** [comment]
INSDC Sequences
https://www.gbif.org/dataset/d8cd16ba-bb74-4420-821e-083f2bac17c2

**Comment by jhnwllr** [comment]
I think a wider discussion about how to apply basis of record is necessary. It is probably outside of the scope portal feedback and would need tdwg involvement... 

I think we should close this issue or open a new one on tdwg or more generally formatted.
