### ISSUE TITLE
Suggest adding text to 404

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#301]
**Suggest adding text to 404**

I suggest adding:

It is possible some URLs have changed.  Please try [a search](...) or perhaps visit the [legacy website on www-old.gbif.org](http://www-old.gbif.org)

-----
fbitem-06b8ff40a48c8ccf8989ec40d67b87a2c9a3171f
Reported by: @timrobetson100
System: Chrome 59.0.3071 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/vfevs
Window size: width 1886 - height 938
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T07:18:38.941Z',mode:absolute,to:'2017-08-15T07:24:38.941Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T07:18:38.941Z',mode:absolute,to:'2017-08-15T07:24:38.941Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Maybe a little more lead-in/context, like:

> **We have just released an improved and updated GBIF.org, so it** is possible some URLs have changed...
