### ISSUE TITLE
IPT Video Missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3010]
**IPT Video Missing**

The IPT Video is missing from https://www.gbif.org/ipt.  Is there some other way to access it?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/937a896cf2a9182dc48d3d9a1e528c32:2426c405017f51f8bf51fb9eab309197c0d77358875ff35b783b25eb900cd78ae9556dfcf205440175c8258cee21e42d8b13e8bfb7ca155af6e2d7e6e9d371fe)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/ipt
Window size: width 1920 - height 1089
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-22T02:36:08.945Z',mode:absolute,to:'2020-09-22T02:42:08.945Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-22T02:36:08.945Z',mode:absolute,to:'2020-09-22T02:42:08.945Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
@thomasstjerne, we are missing a security policy attribute allowing the embedding of the YouTube video.

@dnoesgaard, the link to the backup video on Contentful isn't working either.

**Comment by MortenHofft** [comment]
security policy fixed in https://github.com/gbif/portal16/commit/ebab8622a131ddac2715dec307438b0042b6813c
