### ISSUE TITLE
Example Missing from FAQ

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3012]
**Example Missing from FAQ**

The FAQ is "Can you provide an example of an auto-generated dataset citation?"
but there is no example shown

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/246a19ffc63728bf6dec7dbcd528a6d7:eee13ba912bdd4220c2751e261548f5f49c3e002dd498a2649d19b4b9cd8d8ea594da629d9171092c56800dd50b47ab771221919afcbc0b8ce723a5ba13ce2d6)
System: Safari 13.1.2 / Mac OS X 10.15.6
Referer: https://www.gbif.org/faq?question=dataset-citation
Window size: width 2898 - height 765
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-22T07:33:38.852Z',mode:absolute,to:'2020-09-22T07:39:38.852Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-22T07:33:38.852Z',mode:absolute,to:'2020-09-22T07:39:38.852Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Ha, that's very useful...I'll have a look
