### ISSUE TITLE
add GigaByte journal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3013]
**add GigaByte journal**

As per https://twitter.com/dschigel/status/1308380099218214913?s=20.

And a friendly reminder to update this whole page. Looking at WP2021 draft and based on the discussions we had recently, data papers may play important role in near future, and we need to keep this page up to date, incl. IF, Scopus and PC estimate. This page is the worlds best resource on biodiversity data papers (compare it to e.g. https://en.wikipedia.org/wiki/Data_publishing#Data_journals), just slightly outdated.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/847e591e01a2d751b52c692cbf5843ca:4a8ba9c4c46dd7d5cf48c0905656a962b8539fc48c24edb1b7d71285d1e7c6ef31f27e266c0370ce14f2797be9ac881e5622c44ba3a39320366bcb4bf5831183)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/data-papers
Window size: width 1396 - height 665
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-22T12:24:15.247Z',mode:absolute,to:'2020-09-22T12:30:15.247Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-22T12:24:15.247Z',mode:absolute,to:'2020-09-22T12:30:15.247Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
I've added GigaByte and updated values for CiteScore and IF to 2019...

**Comment by dschigel** [comment]
Thanks @dnoesgaard ! Can we ask admin to help update APC estimates, too? This field helps this table to work in the at-a-glance mode.

**Comment by kcopas** [comment]
@dschigel we've got it under control. We've also discussed ongoing maintenance and made arrangements.
