### ISSUE TITLE
tentrepohlia annulata

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3014]
**tentrepohlia annulata**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e1d8759093deb915bfe29fbb3a707755:14ce40cf207d086cd69c9cfa0a6d7b2c23b576d5798921df7a3fb6e30b9f31f33e4af0f2296a5f4924f2719daba340b76fc969d3750a99f8271ca2f9778907d5)
System: Firefox 80.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?q=tentepohlia%20annulata&taxon_key=5
Window size: width 1366 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-22T18:58:40.730Z',mode:absolute,to:'2020-09-22T19:04:40.730Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-22T18:58:40.730Z',mode:absolute,to:'2020-09-22T19:04:40.730Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I believe this user tried to look for Trentepohlia annulata and not tentrepohlia annulata.
https://www.gbif.org/occurrence/search?taxon_key=5273093
Will reply by email.
