### ISSUE TITLE
Website address apparently hacked

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3015]
**Website address apparently hacked**

The url for the official website for the country lands in a strange page, in a language I don't understand, but apparently mentioning a hacked website.
Should be checked.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8fbd50fa989bab693e9c58c6b9fb49cc:09503268cd808263c316e535abdf84a9d79426aa060f25dd24964ea3b9bffaa6e2102e170c1bc0c30d6f56b32b1541ee9c7a5bce2f4e022d20f776c918f83b6b)
System: Chrome 85.0.4183 / Mac OS X 10.12.6
Referer: https://www.gbif.org/country/NG/participation
Window size: width 1440 - height 821
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-24T13:52:45.531Z',mode:absolute,to:'2020-09-24T13:58:45.531Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-24T13:52:45.531Z',mode:absolute,to:'2020-09-24T13:58:45.531Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
The URL seems ok now: http://www.ngbif.org.ng
I will be closing the issue.
