### ISSUE TITLE
Node manager's console view

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3016]
**Node manager&#39;s console view**

For each country, list publishers with names, links, N datasets (by type), N records (by BoR), N citations. Display total citations (deduplicated) for each country. Develop other features that help at-a-glance overview of what is going on in the country. Save snapshots of these parameters in regular snapshot statistics, develop cool and helpful visualizations. Allow saving as ppt for local presentations by Nodes. Repeat for all GBIF regions.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/a77e2a8d4b92a42b559ae6cdaa7ed3a9:a08d6df13c896541372272b4cd19c3adccb5ad1bc66bf435e73dfa220dc50876e04e08d6d53349bf47500368ff345fef2aa7835585668ebf8495b4fd6358ca9e)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/country/RU/publishing
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-24T18:09:37.920Z',mode:absolute,to:'2020-09-24T18:15:37.920Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-24T18:09:37.920Z',mode:absolute,to:'2020-09-24T18:15:37.920Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by dschigel** [comment]
Thanks to @jlegind we have some files on Russia as an example to play with

**Comment by jlegind** [comment]
Issue has been overtaken by developments.
