### ISSUE TITLE
Euoniticellus intermedius (REICHE) is not a synonym of Digitonthophagus gazella (FABRICIUS).

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3017]
**Euoniticellus intermedius (REICHE) is not a synonym of Digitonthophagus gazella (FABRICIUS).**

There is a discussion about conservation of the name Digitonthophagus gazella in the actual sense, but nothing dealing with Euoniticellus intermedius.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/905b8ff28778c73b3628b5bb85ae9dea:d3592e5ab471a8efd98987b09aa0ecef7d7f33bd2ecfbd7efa800987e23a2a9b75e75dcba79eb53429e1345998df35a74bfd53d33ff646aacf17409d9fe295dfc79ed32b1cd02fa688351af56d2a4ffb)
System: Chrome 85.0.4183 / Windows 7.0.0
Referer: https://www.gbif.org/es/species/1094483/treatments
Window size: width 1366 - height 608
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-26T17:29:08.788Z',mode:absolute,to:'2020-09-26T17:35:08.788Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-26T17:29:08.788Z',mode:absolute,to:'2020-09-26T17:35:08.788Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
This seems to be solved in the latest backbone.
