### ISSUE TITLE
deleted file recover?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3019]
**deleted file recover?**

Dear GBIF helpdesk, 
would it be possible to recover the file associated with the DOI 10.15468/dl.jfkwcg? We were expecting to publish the associated study before it expired, but it hasn't been the case. We are now preparing the publication, and we would like to know if it could be recovered.
Best regards
Michela Leonardi

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7d066fc45ad886da1b8a14f25b60ffe2:9afe2111675aa6e2c17615337647144a85271300edf1bbe8ccaf4f8b384d28731cb4958b579946fef61838dda3a8664ae0b1126ec0a6c209b3850d62eed2a2a9)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/user/download?offset=100&limit=20
Window size: width 1187 - height 921
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-29T07:27:49.407Z',mode:absolute,to:'2020-09-29T07:33:49.407Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-29T07:27:49.407Z',mode:absolute,to:'2020-09-29T07:33:49.407Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
https://doi.org/10.15468/dl.jfkwcg restored after discussion with the user, who sent me the file.
