### ISSUE TITLE
Quirks with the Other Associate Participant pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#302]
**Quirks with the Other Associate Participant pages**

The VertNet participant page doesn&#39;t turn up in [search](https://demo.gbif.org/search?q=vertnet).

And when I access it through the list on the network page, its URL is a numeric ID (https://demo.gbif.org/participant/361).

Maybe some final tweaks to be made? 

For reference, current site simply has node pages for organizational participants [i.e.](http://www.gbif.org/node/d205def7-82c3-472a-be4b-31d11dcd51fd)

-----
fbitem-1ebbc29a5832546519960f735eacfe01923e7a85
Reported by: @kcopas
System: Safari 10.1.2 / Mac OS X 10.12.6
Referer: https://demo.gbif.org/participant/361
Window size: width 1227 - height 734
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T07:56:58.878Z',mode:absolute,to:'2017-08-15T08:02:58.878Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T07:56:58.878Z',mode:absolute,to:'2017-08-15T08:02:58.878Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
The URL change is intentional on suggestion by Tim R. That is the id of the actual participant in the directory API where most of the data is located. The old url redirects. 

The missing from search is an oversight and requires some development

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/492
