### ISSUE TITLE
Longitude flipped for American warblers

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3020]
**Longitude flipped for American warblers**

All four of these localities named as Curacao island in Netherlands Antilles, seems certain to be issue of longitude showing positive instead of negative.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a3667a7e6b25282796debadb9f5ebc05:68b5e0b34941f7e4ff59c51fe5ed72c17a016c7a36f2297326d0d6a077f347eadc88942472e9ba68210d696a98a0efee5a137ee7dba7fe8d4cf91026e53eb196)
System: Chrome 85.0.4183 / Mac OS X 10.15.6
Referer: https://www.gbif.org/occurrence/search?month=1&taxon_key=7341834&geometry=POLYGON((68.46897%2012.65911,67.70567%2011.68355,70.14219%2012.17944,68.46897%2012.65911))
Window size: width 2573 - height 1360
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-29T07:38:23.187Z',mode:absolute,to:'2020-09-29T07:44:23.187Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-29T07:38:23.187Z',mode:absolute,to:'2020-09-29T07:44:23.187Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
It seems like the longitude is negated for many other specimens as well. Our system flagged 2,659 of them: https://www.gbif.org/occurrence/search?dataset_key=889c91a3-614f-4355-8df8-b6d0260a118c&issue=PRESUMED_NEGATED_LONGITUDE

**Comment by ManonGros** [comment]
Contacted publisher by email.
