### ISSUE TITLE
Wrong website SDMdata

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3021]
**Wrong website SDMdata**

Hi,

The tool SDMdata now links to a gambling website.

Any reply to this with the e-mail address in my profile will not reach me as that no longer funcitons. I can be reached on [removed]

Many thanks

Charlie

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2033a33d6dbe293d4241766cbf19491f:8874a3e10e43f36448419bffeb26898b05c8207b24a036a00653e3a7105b80239f3ef56e829ff82331d1b20e788711faf55411e3c393de3ae4f6168a67cfa82bd134d0c7410bca50280089bda9d4a6f0)
System: Firefox 81.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?contentType=tool
Window size: width 1920 - height 966
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-29T07:39:30.237Z',mode:absolute,to:'2020-09-29T07:45:30.237Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-29T07:39:30.237Z',mode:absolute,to:'2020-09-29T07:45:30.237Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
@dnoesgaard, it should perhaps be removed, as it's no longer running anywhere. The source seems to be https://github.com/howl-anderson/SDMdata

**Comment by dnoesgaard** [comment]
I've archived the entry so it's no longer shown on the website.
