### ISSUE TITLE
add line with a feedback collecting link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3024]
**add line with a feedback collecting link**

Please add 

We appreciate when ambassadors capture their presenters' experiences [https://forms.gle/vWR8VgLTZs1ajs5n7], which helps us to improve our materials and messaging for future events.

After

... your role is confirmed.

Or before

Biodiversity Open Data Ambassadors are also encouraged to network

Comms, please edit wording and placement as necessary.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/86bbdccffb45f4bf4bf83e58830e545f:a1358d423971a8f1202c93081c51e24ded9901b08fb33e0c90a75572c92e3f862df2067ff2d50ba2348950cac766ac144bf76152f7b497f7102a406ed4f0f3b7)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/article/6dNF1d0tgcI4cmqeoS2sQ4/biodiversity-open-data-ambassadors
Window size: width 1745 - height 970
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-29T14:45:47.588Z',mode:absolute,to:'2020-09-29T14:51:47.588Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-09-29T14:45:47.588Z',mode:absolute,to:'2020-09-29T14:51:47.588Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by dnoesgaard** [comment]
Thanks, added:

> We appreciate when ambassadors capture and [share their experiences](https://forms.gle/vWR8VgLTZs1ajs5n7) from events attended, which helps us to improve our materials and messaging for future events.
