### ISSUE TITLE
Occurrence search - datasetID/datasetName

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3026]
**Occurrence search - datasetID/datasetName**

Hi

Is it possible to search occurrences by datasetID or datasetName. Like the variables found in this record: https://www.gbif.org/occurrence/2402407820. If not I would very much be in favor of developing/implementing that possibility.

Thomas Sæther

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a3eb3d350963eb8d500ea14963688744:efbcfa5289546334fbd9c54385dbf6fbf60e63db1cbedd469733a038b0a64489fb0bdfe79d64bb42f9ed8323380e5704d06a498670c5783103215231c0e98ea9)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2402407820
Window size: width 2048 - height 1010
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-01T11:47:16.636Z',mode:absolute,to:'2020-10-01T11:53:16.636Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-01T11:47:16.636Z',mode:absolute,to:'2020-10-01T11:53:16.636Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL
datasetKey: b124e1e0-4755-430f-9eab-894f25a9b59c
publishingOrgKey: d3978a37-635a-4ae3-bb85-7b4d41bc0b88

**Comment by dagendresen** [comment]
A thrilling thought indeed would certainly be if data records from across "DwC-A datasets" could be grouped and displayed as participants in "datasets" identified by `datasetID` (and maybe `datasetName`) -- and likewise for `collectionID` -- and some kind of "projectID" thing. (However, the `datasetID`s would of course preferably use globally unique persistent identifiers and not plain integers/literals as in the example).

Maybe even completely replacing the current "DwC-A" = "the dataset" concept. In other words split the "DwC-A" as the data-package-container from the "dataset" concept. And enable the authoring of the (EML) dataset metadata completely outside externally to the IPT - and simply referenced from the data-package.  However, I realise this would need deep thinking to not break current implementations.

**Comment by MortenHofft** [comment]
Hi Thomas
Just to confirm as I see your question was never answered. No you cannot search for datasetID or datasetName.

It is always nice to understand the motivation behind feature requests, could you describe the use case a bit more please?

Would it make sense to split your dataset into multiple if the datasetName/datasetId changes within the "GBIF dataset". That would create a 1:1 relation so you could use the regular dataset filter

> user notified by email

**Comment by MortenHofft** [comment]
@dagendresen it sounds like what you are asking is something else and might deserve a separate issue? Also note that there is already ways to group occurrences across datasets.

[search dataset by projectId](https://www.gbif.org/dataset/search?project_id=BID-CA2016-0006-REG)
[search occurrences by projectID](https://www.gbif.org/occurrence/search?advanced=1&project_id=BID-CA2016-0006-REG)
[search occurrences by matched grscicoll collection](https://www.gbif.org/occurrence/search?advanced=1&collection_key=dceb8d52-094c-4c2c-8960-75e0097c6861)
[search occurrences by collection code](https://www.gbif.org/occurrence/search?collection_code=k&advanced=1)
[search occurrences by publisher](https://www.gbif.org/occurrence/search?publishing_org=d3978a37-635a-4ae3-bb85-7b4d41bc0b88&advanced=1)

**Comment by ThomasSather** [comment]
@MortenHofft this was a novice attempt to suggest a workaround to what might be a local (Norwegian) problem. As you probably know, we have large and well-functioning national species data infrastructure (Artsdatabanken/Artsobservasjoner) in Norway, run by the Norwegian Biodiversity Information Centre (NBIC; www.biodiversity.no). GBIF harvest data from this database every night. Nordre Øyeren Bird Observatory (https://www.gbif.org/publisher/74331676-6384-4da7-8e92-11001735db6a) has chosen to use NBIC’s digital infrastructure to publish data from our systematic, weekly waterfowl and wader counts dating back more than 45 years. This is easy for us, but also poses a couple of problems: NBIC is automatically listed as the owner/publisher of all our data. We are looking for a way to stratify the NBIC data so that we can generate DOIs for our own data. However, based on discussions with @dagendresen we understand that this is better solved locally, by NBIC splitting up/re-annotating their data.

**Comment by MortenHofft** [comment]
If the NBIC dataset is made up of many smaller datasets and it is useful for the data owners of those dataset to delimit their own data, then splitting it sounds natural to me. 

That also gives you the added benefit of citation tracking for your individual dataset, which might be of interest. And an option to describe your specific data in more details than the [NBIC dataset](https://www.gbif.org/dataset/b124e1e0-4755-430f-9eab-894f25a9b59c) can.

Thank you for the explanation

**Comment by timrobertson100** [comment]
Please see https://github.com/gbif/pipelines/issues/662 where we intend to implement multivalue dataset ID and name search capabilities shortly.

**Comment by ThomasSather** [comment]
This is great news! Looking forward to testing it out!
