### ISSUE TITLE
Why is this species  deleted ?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3027]
**Why is this species deleted ?**

Why is this species  deleted ? This seems absurd.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a8213a5665e2cc629089f256a0b92a27:97c392da2ee99811e429f3dba5c2321c90c568b17330ccc43974af4e62995781a38405a5d532380af68f20b2713c95eab07b44ddd151f62daa0e47104158a1bd)
System: Firefox 48.0.0 / Mac OS X 10.8.0
Referer: https://www.gbif.org/species/5142971
Window size: width 1061 - height 816
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-02T08:47:00.666Z',mode:absolute,to:'2020-10-02T08:53:00.666Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-02T08:47:00.666Z',mode:absolute,to:'2020-10-02T08:53:00.666Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Replied by email.
