### ISSUE TITLE
Why is this species  deleted ?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3028]
**Why is this species deleted ?**

Why is this species  deleted ? This seems absurd.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a4f49d20f365ec05b24490b625a65a8a:0771ec5189c1e5a1a65c2f42b887f21c9d43fc6f51c111e174bee35cd902550ea4a929108b4853e9bed71334b5f65eafe1f0f0648fd51d0178b2e1b8554c7a34)
System: Firefox 48.0.0 / Mac OS X 10.8.0
Referer: https://www.gbif.org/species/8751271
Window size: width 1061 - height 816
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-02T08:48:15.235Z',mode:absolute,to:'2020-10-02T08:54:15.235Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-02T08:48:15.235Z',mode:absolute,to:'2020-10-02T08:54:15.235Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Replied by email.
