### ISSUE TITLE
Why doubtful ?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3029]
**Why doubtful ?**

Why is this species labeled "doubtful" ?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f04995b22e12547f9f80b5275c21353a:1b7950833f788fe54ef86f3070e282e3c7fb6128aa6a16687a451c2e98defe0e65b62f03c77b129880aaf7d324d3c0db4ffeed4eedd1a1f39600789a9a067d35)
System: Firefox 48.0.0 / Mac OS X 10.8.0
Referer: https://www.gbif.org/species/8891058
Window size: width 1061 - height 816
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-02T08:54:45.025Z',mode:absolute,to:'2020-10-02T09:00:45.025Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-02T08:54:45.025Z',mode:absolute,to:'2020-10-02T09:00:45.025Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
This is a good question: why is this particular species labelled as "doubtful"?
Any insights @mdoering ?

**Comment by mdoering** [comment]
I would think because it is from ZooBank which is a nomenclator. So the taxonomic status and placement is not verified and we treat all these names as doubtful if they do not occurr in other taxonomic lists.
