### ISSUE TITLE
This Ourimbah is in Australia.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3030]
**This Ourimbah is in Australia.**

Title is "Revision of the Australian species..." , content of treatment says Sydney, collector did not collect in the UK.

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/edb43b4589fa22a49f95894a544cec60:9a0debb4d66d89a954afb5427a40502b2988c8acf34885c28f2d5b7a2d77d5f1c5daf65bda11aae14a5154978e380e147479755c7e73fb7f25d10533bf2832d631d1a58cfc345784089d5b5b0af39a60)
System: Chrome 85.0.4183 / Mac OS X 10.15.6
Referer: https://www.gbif.org/occurrence/1324963913
Window size: width 1616 - height 916
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-02T13:37:29.576Z',mode:absolute,to:'2020-10-02T13:43:29.576Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-02T13:37:29.576Z',mode:absolute,to:'2020-10-02T13:43:29.576Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL
datasetKey: c55b8fbe-5e88-4dae-89fb-38df76c0b839
publishingOrgKey: 7ce8aef0-9e92-11dc-8738-b8a03c50a862

**Comment by truschel** [comment]
The problem was solved.
Thank you!
