### ISSUE TITLE
Inachis io

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3031]
**Inachis io**

Why is "Inachis io" labeled doubtful ?  It is simply a synonym for Aglais io.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/39b69e562dc758508cf96aed30be94f2:c4893789651ac47421e4e95892ca66b08e29fe79f098bb52071b30bdda03ac69608a03ccd90b7955319f6e50a04b066c66fc6f83c868de1f977bd3b4212aa6fc)
System: Firefox 48.0.0 / Mac OS X 10.8.0
Referer: https://www.gbif.org/species/5881450
Window size: width 1081 - height 875
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-03T12:12:22.763Z',mode:absolute,to:'2020-10-03T12:18:22.763Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-03T12:12:22.763Z',mode:absolute,to:'2020-10-03T12:18:22.763Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Replied by email.
