### ISSUE TITLE
Why doubtful

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3032]
**Why doubtful**

Why is Agrodiaetus dantchenkoi labeled "doubtful" ?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9cb6ee96ac7734bbb88c79233dd9585b:4ece9e7c05eee2b9a4c64808718d992204ccbce32aa035317af4721289c5198690fb7bd403ad8c8d674dcfeeec9b98ad5b793c7724accf20d7b293ba2120aab1)
System: Firefox 48.0.0 / Mac OS X 10.8.0
Referer: https://www.gbif.org/species/8885542
Window size: width 1081 - height 875
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-03T12:17:47.280Z',mode:absolute,to:'2020-10-03T12:23:47.280Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-03T12:17:47.280Z',mode:absolute,to:'2020-10-03T12:23:47.280Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by jlegind** [comment]
_Generally speaking:_
What does the taxon status "doubtful" mean and when is used?
A taxon name can be flagged as doubtful for several reasons that have to do with the way the GBIF backbone taxonomy is built.

Here is a non-exhaustive list:

* The name comes from a nomenclator only.
* There is more than one accepted name with the same canonical name but different author. In that case, the most trusted one is * accepted and others are flagged doubtful.
* The name has homonyms in the same source.
* The name is a basionym placeholder and contains "? epithet".
* The name is a genus or higher taxon without any species.
* The name is a species or and infra-species with a parent genus or species considered to be a synonym.

**Comment by ManonGros** [comment]
I think the question was about this particular taxon.
