### ISSUE TITLE
Cant consider Offsets in GBIF API

### ISSUE THREAD

**Issue by math-sasso** [gbif/portal-feedback#3033]
What is the correct way to consider offsets when requesting GBIF data?

I need this beacuse I want to download more than 300 occurrences, wich is the limit for one request,

``` 
def _managing_complete_species_dataframe(self):
    df = pd.DataFrame(columns=['SCIENTIFIC_NAME','LONGITUDE','LATITUDE','COUNTRY','STATE_PROVINCE','IDENTIFICATION_DATE','DAY','MONTH','YEAR'])
    endOfRecords = False  
    offset = 0  
    status = 200
    params = {'taxonKey': str(self._taxonKey) ,'limit':self._limit,'hasCoordinate':self._hasCoordinate,'year':self._year_range,'country':'BR'} 
    #params = [f'taxonKey={str(self._taxonKey)}' ,f'limit={self._limit}',f'hasCoordinate={self._hasCoordinate}',f'year={self._year_range}','country=BR'] 
    while endOfRecords == False and status == 200:  
        r, endOfRecords, status = self._gbif_request_json_request(offset, params)
        self._create_specie_dataframe(df,r)
        offset = len(df) + 1


  def _gbif_request_json_request(self,offset,params):

    params['offset'] = offset
    r = requests.get(query,params=params)

    if r.status_code != 200:  
        print(f"API call failed at offset {offset} with a status code of {r.status_code}.") 
        endOfRecords = True 
    else:  
        r = r.json() 
        endOfRecords = r['endOfRecords']

    import pdb;pdb.set_trace()  
    return r,endOfRecords,r.status_code
```

Thanks!

**Comment by ManonGros** [comment]
Hi @math-sasso 

I haven't tested your code but it seems like what you wrote should work (just keep the limit parameter under 300).

Note that the search API has hard limit for any query of 100,000 records.
I would strongly encourage you to use the [download API](https://www.gbif.org/developer/occurrence#download) instead. Not only this will allow you to download all the occurrences at once without the hard limit, it will also generate a DOI for each download. Once cited, this DOI allow us to give the credit back to the original data providers whose work contributed to your download.

You can find a python example on how to download a long list of species in this blogpost: https://data-blog.gbif.org/post/downloading-long-species-lists-on-gbif/.

Please let us know if you have any question.

**Comment by math-sasso** [comment]
Thank you for the answer.

In fact, with some small modification my code worked well and I used  the API. The only point I would suggest you is to include the offset parameter on the documentation. I could only find the parameters "facetOffset" and  "facetLimit" that are not the same thing.

Best Regards :)

**Comment by jlegind** [comment]
As Marie already suggested: Please use the download API rather than scraping occurrence_search pages.
Since you are fluent in Python, I suggest you take a look at the pygbif package: 
https://pypi.org/project/pygbif/ 

Specifically look towards this module:
https://github.com/sckott/pygbif/blob/master/pygbif/occurrences/download.py
You will be generating a 'user download' based upon predicates, and you will get email notification when the download is ready. 
There is a DOI attached to the download which makes citation much more accurate.
