### ISSUE TITLE
The system is not available.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3034]
**The system is not available.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/12cb8952c2df9c879613f766980241d5:b2e26fe8397569f36dc12764b3e7256e068f7695b8f74761c65c13b9ab852779852b9e7c426a1e25c861f0ae7ff74903a9308135fa0e4e7659cf76ccdf34e842)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator
Window size: width 1366 - height 608
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-03T17:10:56.998Z',mode:absolute,to:'2020-10-03T17:16:56.998Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-03T17:10:56.998Z',mode:absolute,to:'2020-10-03T17:16:56.998Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
Service restarted, it had a "Too many open files" error.
