### ISSUE TITLE
country trends offline?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3035]
**country trends offline?**

Trends charts don't seem to show for data from or about countries - discovered in preparation for my conference presentation on Monday. Does not really change my preps, only the visuals, but I thought to let you know

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/31cbb837f204a0aaf54707288bb14ba1:1f81174648a8eda71320f81f10d93972e489ca9b693092d5af034531c8f91acef406486f82ba340ff8a800644c5e94ff3a01316b243982c19fdf1fe55a39fcb0)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/country/RU/about
Window size: width 1920 - height 1067
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-03T17:24:14.349Z',mode:absolute,to:'2020-10-03T17:30:14.349Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-03T17:24:14.349Z',mode:absolute,to:'2020-10-03T17:30:14.349Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by kcopas** [comment]
Check the charts at the bottoms of the respective (from and about) pages—are they not what you’re looking for?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dschigel** [comment]
![Charts](https://user-images.githubusercontent.com/14940052/95014595-2e5a1680-0648-11eb-978b-308abffd7d2e.png)

**Comment by MattBlissett** [comment]
Check if you have an ad blocker or similar which might be interfering.

**Comment by kcopas** [comment]
They’re there for me, too. Clear browser cache, refresh page, switch browsers…?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jlegind** [comment]
Problem went away.
