### ISSUE TITLE
This picture is another seahorse species, H. trimaculatus.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3036]
**This picture is another seahorse species, H. trimaculatus.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1f7100707d61c95174b7a13af00db113:5d0a69e3d4816d09bc88a5c3a1af53325c05cf6e29801e02e274b51a6d843026880f65c283698708ee2de11e8b32482362e3175ce145dfdebe0eed061338318e)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2579317846
Window size: width 1779 - height 851
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-04T09:59:39.607Z',mode:absolute,to:'2020-10-04T10:05:39.607Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-04T09:59:39.607Z',mode:absolute,to:'2020-10-04T10:05:39.607Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

**Comment by ManonGros** [comment]
This record is from iNaturalist, I forwarded the feedback: https://www.inaturalist.org/observations/37248705
