### ISSUE TITLE
User feedback - Synargis Hübner, 1819 should be in Riodinidae family

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3037]
**User feedback - Synargis Hübner, 1819 should be in Riodinidae family**

This is from an email that we received on Helpdesk.

It seems like this genus is already Riodinidae (https://www.gbif.org/species/1933999) on iNaturalist.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/294ac654a3518d99b508176ff6d17c2f:22dde78dc12257f067422147f4986457365fe888d208351f4a19c52b22d9f746a13cf7c9f05a78b11e7ae03f01bb5df8706cb4042fc2aee1cdd0fa4614f3571a)
System: Safari 14.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/4695593
Window size: width 1680 - height 830
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-05T13:09:08.713Z',mode:absolute,to:'2020-10-05T13:15:08.713Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-05T13:09:08.713Z',mode:absolute,to:'2020-10-05T13:15:08.713Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Solved in the new backbone.
