### ISSUE TITLE
All occurrences disappeared

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3040]
**All occurrences disappeared**

Seems all the occurrence records have disappeared from this dataset.

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/91debe9cad85aaefbec5080cecb803a7:87efed81117d3fd89cfb12dc98d84dbaaacd4f3c0b820771c907936456645c7f0e424bfbbb8cc4a816a79878c6fab5428625ca04762ea4bd6d1b7e5b021005c69624261294a7b2ec2c2ce3893b9ab6b9)
System: Chrome 85.0.4183 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/4300f8d5-1ae5-49e5-a101-63894b005868
Window size: width 1627 - height 916
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-08T04:27:21.933Z',mode:absolute,to:'2020-10-08T04:33:21.933Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-08T04:27:21.933Z',mode:absolute,to:'2020-10-08T04:33:21.933Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
the dataset was reindexed.
