### ISSUE TITLE
Date vs event date

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3042]
**Date vs event date**

I haven't looked at all 24,767 records, but we're showing 0% of them as having dates. However, every record I *did* look at has a 'verbatim event date' that clearly appears to be the collection date. Is this a mismatch of expectations or interpretation of the field? Since it's a VertNet hosted dataset, I'm also wondering if the issue's unique to it…

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/9ba4dee5d1bb8bf3b8f8cb134c7e4c37:38f1edd882617f9b45367daa1ec5fa5f5710c3468a075f32775e3b31deef40ec6671bc3dd8889034a63ab83e4ea1018ed905f78e238a41f33cb6a98f59beb5e8)
System: Firefox 81.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/dataset/a9ae9ece-e753-4fb9-8595-a37d0f5aa59c
Window size: width 1546 - height 1172
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-08T06:39:32.436Z',mode:absolute,to:'2020-10-08T06:45:32.436Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-08T06:39:32.436Z',mode:absolute,to:'2020-10-08T06:45:32.436Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by jhnwllr** [comment]
Hi @kcopas, 

I did a quick query and I was not able to find any dataset which has 0% eventdate filled and only verbatimeventdate filled in. There are some datasets that have more verbatimevendate filled in than evendate. The cluster is pretty busy so I wasn't able to do more research into it.

**Comment by kcopas** [comment]
sorry, should've been clearer! Dataset metrics:
![Screenshot 2020-10-08 at 10 31 05](https://user-images.githubusercontent.com/12379236/95434361-71223400-0951-11eb-91e5-566470ea49fe.png)

Example: https://www.gbif.org/occurrence/2381387189
![Screenshot 2020-10-08 at 10 32 04](https://user-images.githubusercontent.com/12379236/95434459-92832000-0951-11eb-9000-04008992340a.png)
![Screenshot 2020-10-08 at 10 32 14](https://user-images.githubusercontent.com/12379236/95434467-94e57a00-0951-11eb-969d-8dcfd2461603.png)

**Comment by MortenHofft** [comment]
As far as I know it is a way to encode the data interpretation trail. 

**From the publishers view**
The date provided to the publisher is the `verbatim event date`. And `event date` is how they interpreted it before publishing it.

**From our view**
We consider all above verbatim. And then adds another layer of interpretation (for some fields, incl event date)

In this case it looks to me like they should add a field `event date` (if they believe the date to be valid).

**Comment by dbloom** [comment]
Hi folks,  I have found the issue with the missing dates and corrected it on the VertNet mobilization side. I have republished the dataset and dates should now be present. Note that not all records contained dates, but the vast majority of these records did and do.

**Comment by ManonGros** [comment]
Thanks @dbloom!
