### ISSUE TITLE
Replace logo

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3043]
**Replace logo**

As requested by Leif Schulman.
In the footnote and all other possible uses, e.g. project pages: whole section of Northern Eurasia needs to be checked.
-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/63ec7b35f7e9612c877bd7c9f76a347d:6a079766f810fd0996a4a956e19d82a034ef86ec43a88cebc2021c5f6c8d4e04c1ddcd2596c4c3d367c9d0b35ccf90d3268451ec0c5bfa203ffad29dc3d3c011)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/programme/3ilFFs3JdY2SqmyCuac0uc/northern-eurasia
Window size: width 2133 - height 1131
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-08T17:09:04.018Z',mode:absolute,to:'2020-10-08T17:15:04.018Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-08T17:09:04.018Z',mode:absolute,to:'2020-10-08T17:15:04.018Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by dschigel** [comment]
![FinBIF_ENG_rgp](https://user-images.githubusercontent.com/14940052/95491837-7b1c5500-099a-11eb-8bf3-ce0d1b38f85e.png)

**Comment by dnoesgaard** [comment]
Done.
