### ISSUE TITLE
Add LivingNorwayR

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3046]
**Add LivingNorwayR**

To catalogue to tools and maybe Tools menu

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/77dc86ce2061dc173cd9cf0da0441d58:4bc4bc8f99e298781402a7c42e08bb792321aa3dcef2520117b6ae802b9f21e72966cc9be8140c2c5561524b9bcd5ec25b37885a4f2d6fa134f4a26364e99035)
System: Chrome 85.0.4183 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 2133 - height 1131
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-12T09:22:30.962Z',mode:absolute,to:'2020-10-12T09:28:30.962Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-12T09:22:30.962Z',mode:absolute,to:'2020-10-12T09:28:30.962Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by dschigel** [comment]
Looks very promising data use library, descriptor and details via Dag Endresen and Anders Finstad. Presentation by developer at Living Atlas Norway given on 12 October 2020.

**Comment by dnoesgaard** [comment]
Do you have a link or some more descriptive details?

**Comment by dschigel** [comment]
Not directly, probably faster to contact Erlend Nilsen <Erlend.Nilsen@nina.no> than to look at https://livingnorway.no/blog/

**Comment by dnoesgaard** [comment]
Done: https://www.gbif.org/tool/4uVqj4nCoX3GH4uQxOTAyG/livingnorwayr
