### ISSUE TITLE
Invalid EML metadata

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3047]
**Invalid EML metadata**

The organization name for one of the contacts is "-", which the IPT accepts, but the Registry does not.

Until that's changed, future metadata updates will be ignored.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c73e1989ba8da62f8c68e39d0e45f254:ca16a54113f8c0fcbd2925b8979fe27c8d0a87f7522b88f23f840e6aa9f0d7c04a08d8a836c498ef530ff6c58afd2cc441e0bf9c816a46948681e80570537fc0)
System: Firefox 81.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/dataset/32be30f9-0129-4508-8185-3f09c654f9ed
Window size: width 1920 - height 945
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-12T09:47:52.594Z',mode:absolute,to:'2020-10-12T09:53:52.594Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-12T09:47:52.594Z',mode:absolute,to:'2020-10-12T09:53:52.594Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Publisher contacted by email.
