### ISSUE TITLE
retire or redirect link old validator

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#3049]
It seems like some people still find an try to use our old validator: https://tools.gbif.org/dwca-validator/validate.do
(we got a question on helpdesk about it yesterday). Would it be possible to redirect users to the new validator?

**Comment by MattBlissett** [comment]
There are a few cases where this validator is still useful, but I have fixed the "Not Found" issue (server permissions) and made the recommendation much bigger.

https://github.com/gbif/dwca-validator3/commit/af988f2cc2e525f8e72b3096df6951f0c9313dea
