### ISSUE TITLE
Region page: depending on browser scaling, part of the text can hide under the map

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3051]
**Region page: depending on browser scaling, part of the text can hide under the map**

Opening the regional pages (like https://www.gbif.org/the-gbif-network/africa) starts with the normal 100% (browser: Firefox). In that view, however, both the green buttons with counts and part of the text underneath the map is hidden behind the map. Scaling down to 80% has them appear, but without knowing that, the user is not even aware they exist.
(screenshots to follow)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/72dfd5ae11b5bac66d5c4b2dc7f5c427:c709b5c1915a16039de8c6e6ded7960a0c8f08cc64e729d2187df1187cc19e091b335b6c71e495ea109547fc1837fa60c2c4539c18c19ef74370299e5330a6b9)
System: Firefox 81.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/the-gbif-network/africa
Window size: width 1600 - height 688
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-14T09:37:11.777Z',mode:absolute,to:'2020-10-14T09:43:11.777Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-14T09:37:11.777Z',mode:absolute,to:'2020-10-14T09:43:11.777Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ahahn-gbif** [comment]
![regionPageAF01_20201014](https://user-images.githubusercontent.com/13435656/95972551-df17a100-0e12-11eb-9ab8-e13562397d79.JPG)
![regionPageAF02_20201014](https://user-images.githubusercontent.com/13435656/95972560-e048ce00-0e12-11eb-9527-89400fa9aa7f.JPG)
