### ISSUE TITLE
Continuation of "Bad Text on Institutional Page". The first sentence marked as NOT PART OF TEXT should not be part of the text here. The description should start with "The A.L. ..."" Thank you for the correction.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3053]
**Continuation of &quot;Bad Text on Institutional Page&quot;. The first sentence marked as NOT PART OF TEXT should not be part of the text here. The description should start with &quot;The A.L. ...&quot;&quot; Thank you for the correction.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/597e286e7af4ec630ea98e61d4ebe501:c4740e76635357385bfeba6fce5d3ec43f771087df09a485e1f1b1fda6e092909aea51f8dfb4b8d82ccf5b462204c2bba6f8c88b0e1ee914b27b0092231a7fee)
System: Firefox 81.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/d3fa50b3-ed10-420a-a289-5c0a60dadbf5
Window size: width 1760 - height 895
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-14T13:24:07.897Z',mode:absolute,to:'2020-10-14T13:30:07.897Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-14T13:24:07.897Z',mode:absolute,to:'2020-10-14T13:30:07.897Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Corrected.
