### ISSUE TITLE
Hello, I have been trying to download fynbos data but I cannot find a relevant link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3054]
**Hello, I have been trying to download fynbos data but I cannot find a relevant link**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ead75e2a75a1a73c04571bdab426ff29:ca35cd84d4a3ebf003f7b09fe91cc6ad694d639ebd80ea6c35db7380175f1253dadd6b8d16789a1723b64219fcb339f3446c12d7b26104475996afe61f868add)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/species/6
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-16T17:30:05.710Z',mode:absolute,to:'2020-10-16T17:36:05.710Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-16T17:30:05.710Z',mode:absolute,to:'2020-10-16T17:36:05.710Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
