### ISSUE TITLE
exclude filters possible?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3057]
**exclude filters possible?**

I would like to download all Avian data for Canada, but excluding some large datasets that I already have, such as eBird that represents almost 99% of all data.

Can this be done?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b9f55c78e0746f64f9096ad38438f7a0:b10066780a2088600efa6e46db022d1010f7cb9b61a2c3d39a05c620f76d0d1ad15cf6fb0488afe4724eb05d262605519c344589b5bf265738686c51bf20c8c4)
System: Firefox 81.0.0 / Windows 8.1.0.0
Referer: https://www.gbif.org/occurrence/search?country=CA&publishing_org=28eb1a3f-1c15-4a95-931a-4af90ecb574d&publishing_org=ff418020-1d67-11d9-8435-b8a03c50a862&publishing_org=a41250f0-7c3e-11d8-a19c-b8a03c50a862&publishing_org=09871350-0a23-11d8-b854-b8a03c50a862&publishing_org=aa40a1e0-818b-11d9-b6d0-b8a03c50a862&publishing_org=c3ad790a-d426-4ac1-8e32-da61f81f0117&publishing_org=c1da06f0-580e-11dc-8a9e-b8a03c50a862&taxon_key=212&advanced=1
Window size: width 1920 - height 929
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-18T20:10:45.028Z',mode:absolute,to:'2020-10-18T20:16:45.028Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-18T20:10:45.028Z',mode:absolute,to:'2020-10-18T20:16:45.028Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> It isn’t possible to exclude filters on our web portal but our [occurrence download API](https://www.gbif.org/developer/occurrence#download) allows for a “not” predicate.
For example, you can exclude eBird from occurrences of Birds in Canada with the following query:
{
  "creator":"userName",
  "notificationAddresses": ["userName@example.org"],
  "predicate":
  {
    "type":"and",
    "predicates":     [
      {"type":"equals","key":"COUNTRY","value":"CA"},
      {"type":"equals","key":"TAXON_KEY","value":"212"},
        {
        "type":"not",
        "predicate":
        {
          "type":"equals",
          "key":"DATASET_KEY",
          "value":"4fa7b334-ce0d-4e88-aaae-2e0c138d049e"
        }
        }
    ]}
}
More information is available on the API documentation page.

**Comment by timrobertson100** [comment]
Please also be aware that negation filters will be coming in 2021.
