### ISSUE TITLE
IPT video not available on Spanish page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3058]
**IPT video not available on Spanish page**

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/4f8d51bd7f0be9c3af7748f1fe8eb3b7:81f957430c94ea2903330c10ee463f676c0139baa5f3e6e6d21f4fbb698403b3402e66815f27799190fbbae3c7f54b9f7a3b4964415b2ae02c8c90e682e4b37f)
System: Safari 14.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/es/ipt
Window size: width 1680 - height 830
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-19T06:30:53.425Z',mode:absolute,to:'2020-10-19T06:36:53.425Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-19T06:30:53.425Z',mode:absolute,to:'2020-10-19T06:36:53.425Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Not sure why it was missing, but I've added it now.
