### ISSUE TITLE
how to connect inaturalist observation to gbif

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3059]
**how to connect inaturalist observation to gbif**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/71bc9200c2f9462510f9586483136471:3a0bf4621cd6ecc1828fde29f82457d6776a5ce2ed0303500f36a40e9b1bcacede50e122a71fb5dea5c9d342711db3d98b7cc2b401592f1010211283cee33693)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=How%20to%20connect%20inaturalist%20and%20gbif
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-20T04:47:54.724Z',mode:absolute,to:'2020-10-20T04:53:54.724Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-20T04:47:54.724Z',mode:absolute,to:'2020-10-20T04:53:54.724Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
replied by email
