### ISSUE TITLE
French translation wrong and misleading

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3060]
**French translation wrong and misleading**

In the French version of the site, I found a misleading translation. In the "Relevance"  section of the left-hand panel, "GBIF used" presumably means "GBIF has been used" whereas the French translation, "utilisé par le GBIF" means "used by the GBIF", which is kind of the opposite. I therefore suggest "utilisant le GBIF", the direct English translation of which would be "using GBIF". 
Regards, 
Olivier

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a6660262bed1fd218e396e38617fd11d:4fe5c83bbbda1254849cfa9f89d5f3267abab151c9a817594f8828871d886412a5da8df0b6c5ddd330b6f8afb655dc8b85bf61658fc6f463f277152d5e98604f)
System: Chrome 86.0.4240 / Mac OS X 10.15.6
Referer: https://www.gbif.org/resource/search?contentType=literature&literatureType=journal&relevance=GBIF_FUNDED&peerReview=true
Window size: width 2560 - height 1329
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-20T09:05:28.511Z',mode:absolute,to:'2020-10-20T09:11:28.511Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-20T09:05:28.511Z',mode:absolute,to:'2020-10-20T09:11:28.511Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Is this something handled in crowdin?

**Comment by ManonGros** [comment]
New translations added to crowdin.
