### ISSUE TITLE
"Your GBIF data download is ready" email needs https in download link

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#3061]
When you download data and your download is ready, you get the following email:

> Hello rukaya,
> 
> Your download is available at the following address:
> http://api.gbif.org/v1/occurrence/download/request/0087662-200613084148143.zip
> 

This should really be https, clicking on the link doesn't work in chrome, it gives an error to say this file cannot be downloaded securely.

**Comment by MattBlissett** [comment]
The latest version of Chrome encourages the user not to download zip files over HTTP, but  I think there's a small ^ button to download anyway.

We'll update the links in emails and from the download page tomorrow.
