### ISSUE TITLE
1 Species duplicated, 2 species missing, 3 occurrences elsewhere

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3062]
**1 Species duplicated, 2 species missing, 3 occurrences elsewhere**

Under 
Animalia > Arthropoda > Arachnida > Araneae > Araneidae
Genus Testudinaria 
https://www.gbif.org/species/2160651

Compare reference taxonomy (with 9 species)
https://wsc.nmbe.ch/genus/412/Testudinaria

(1) Here for Testudinaria there is a false listing of
Testudinaria debsmithi Levi, 2005 
https://www.gbif.org/species/5171174
[note: that is duplicated with the correct entry of
Testudinaria debsmithae Levi, 2005]

(2) Here for Testudinaria it lacks main entry for
Testudinaria geometrica Taczanowski, 1879
(see below - for occurrences)

--

Then related, see https://wsc.nmbe.ch/genus/331/Hypognatha

(3) The following entry for
Hypognatha testudinaria (Taczanowski, 1879)
https://www.gbif.org/species/2160496
is wrongly linked to 7 occurrences for (the previously missing) Testudinaria geometrica Taczanowski, 1879

Where
Hypophthalma geometrica Taczanowski, 1879 (his p.126) - Became Hypognatha testudinaria (Taczanowski, 1879).

Hypophthalma testudinaria Taczanowski, 1879 (on p.128) -  Became junior synonym of Hypognatha testudinaria (Taczanowski, 1879)*

Testudinaria geometrica Taczanowski, 1879 on (p.133) - Retained Testudinaria geometrica Taczanowski, 1879 (and has no nomenclatural interaction with the above - nothing beyond a confusingly similar name from sam author.

\* Where the first revisor Levi 1996 (p.109) says "Because males are much easier to determine than females, I use the second name testudinaria for this species. [There is no page priority for names that were published together  (ICZN, 1985, Art. 24a, 24A)."]

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/cf82960bd4488f0674ee47f5609801a4:c879542b247c55982595080572a9876b00d5a95940380326085a60d6647bf7dbfe58597570cbf50983651ccc482f8887e49d29965a6c99288d762e1aea00e21f)
System: Safari 14.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/2160651
Window size: width 1099 - height 700
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-20T23:01:40.159Z',mode:absolute,to:'2020-10-20T23:07:40.159Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-20T23:01:40.159Z',mode:absolute,to:'2020-10-20T23:07:40.159Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
The "duplicate" issue is actually concerning a spelling variant (which is shown as a synonym of the correct spelling).
The rest of the issues have been solved with the latest backbone update.
