### ISSUE TITLE
Mollusca in KUBI Ichthyology dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3065]
**Mollusca in KUBI Ichthyology dataset**

I still have two occurrences in my ichthyology dataset (https://www.gbif.org/dataset/8f79c802-a58c-447f-99aa-1d6a0790825a) that are incorrectly being attributed to Mollusca due to their being a duplication of the family name Cepolidae in both Mollusca and Actinopterygii (https://www.gbif.org/occurrence/search?dataset_key=8f79c802-a58c-447f-99aa-1d6a0790825a&taxon_key=2379520).  How can we get these correctly attributed to the fish family Cepolidae to remove this erroneous attribution and clean up my data?

Thanks

Andy

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/75798b101555e845697d97bab204a53d:9e9e22031bceab22a741b6233e7e1c522d769e798319bdc1873c4de2d57fa551dfa337ca42cbc208cb82e5abf4f09567370fb4a727c81bed5289f19c216fd52f)
System: Chrome 86.0.4240 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/search?dataset_key=8f79c802-a58c-447f-99aa-1d6a0790825a&taxon_key=2379520
Window size: width 1600 - height 851
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-22T19:50:52.120Z',mode:absolute,to:'2020-10-22T19:56:52.120Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-22T19:50:52.120Z',mode:absolute,to:'2020-10-22T19:56:52.120Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This is definitely a backbone taxonomy issue. The "Cepolidae" family for the fish (Bandfish) is merged with its homonym (the air-breathing land snails).
They should be two separate families.

**Comment by mdoering** [comment]
we do have 2 families now in the latest build, but the mollusc one is accepted and the fish one doubtful. Both contain quite a few species (see size):

```
   id    |  rank  |  status  | syn | scientific_name | size | pid  |     parent      |  family   |      order      |     class      |  phylum  | kingdom  
---------+--------+----------+-----+-----------------+------+------+-----------------+-----------+-----------------+----------------+----------+----------
 6755596 | FAMILY | DOUBTFUL | f   | Cepolidae       |   88 |  587 | Perciformes     | Cepolidae | Perciformes     | Actinopterygii | Chordata | Animalia
    4257 | FAMILY | ACCEPTED | f   | Cepolidae       |   68 | 1456 | Stylommatophora | Cepolidae | Stylommatophora | Gastropoda     | Mollusca | Animalia

```

**Comment by mdoering** [comment]
I guess we can still see this as completed as the fish occurrences should not be moved to molluscs anymore as we have both families.

**Comment by mdoering** [comment]
[Acanthocepola indica](https://www.gbif.org/occurrence/1703048376) and [Acanthocepola limbata](https://www.gbif.org/occurrence/1703048371) are both a fish in Cepolidae, Perciformes in the latest build now
