### ISSUE TITLE
How do I change my GBIF password?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3067]
**How do I change my GBIF password?**

How do I change my GBIF password?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ddc10dedbb2f8233cbd3f25421469a31:57399f5e1c8150d32112bcc32e814c367a4c12c51701fbd4fbddf151c447bc892341fd55ac07373977646c585636fc964638df097ab123fa12a757a9d196b533)
System: Chrome 86.0.4240 / Mac OS X 10.15.6
Referer: https://www.gbif.org/faq?q=password
Window size: width 1346 - height 757
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-23T16:55:44.945Z',mode:absolute,to:'2020-10-23T17:01:44.945Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-23T16:55:44.945Z',mode:absolute,to:'2020-10-23T17:01:44.945Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
replied by email.
