### ISSUE TITLE
This record shoud clearly be Vireo olivaceus and for some reason has been interpreted as Chlorophoneus olivaceus with a ? in interpreted scientific name. Not clear why this should be the case as the original appears correct apart from missing scientific name. Same applies to https://www.gbif.org/occurrence/910360834

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3069]
**This record shoud clearly be Vireo olivaceus and for some reason has been interpreted as Chlorophoneus olivaceus with a ? in interpreted scientific name. Not clear why this should be the case as the original appears correct apart from missing scientific name. Same applies to `https://www.gbif.org/occurrence/910360834`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/18b203ab7e85b8e6f2333898344d8eb9:21797e17c2a82d03ea7d08f545d4cf0ba5f0e04df46db9c4072709fe0222bcdf8fc91029345f86b628ec5de2852ad378d59700c7893a8a6e5e0a75f25d05c2e1)
System: Chrome 86.0.4240 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/910358584
Window size: width 2135 - height 1332
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-24T09:24:41.711Z',mode:absolute,to:'2020-10-24T09:30:41.711Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-24T09:24:41.711Z',mode:absolute,to:'2020-10-24T09:30:41.711Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 39f021d5-240c-445d-b62f-33bfed94938d
publishingOrgKey: 609765e0-4ce8-11db-b80e-b8a03c50a862

**Comment by ManonGros** [comment]
This issue seem to have been solved.
