### ISSUE TITLE
Author name misspelled

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3070]
**Author name misspelled**

This was reported on helpdesk:
> error in the botanical name of Ruppia cirrhosa : the author is Grande and not Grandr

It seems like the name is correctly spelled in the Catalogue of life.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/38e3e61077bb8dad25739c02593b47c8:e37f614b6af3b9c0b0daa39c8d85164424cbda8157de228e4ed8ddae7fcf9e73b6c60a542d190ef42fc26a830fb633fab39dfa16ba3dddd70ade702559103945)
System: Safari 14.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/2863987
Window size: width 1464 - height 661
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-26T07:49:50.536Z',mode:absolute,to:'2020-10-26T07:55:50.536Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-26T07:49:50.536Z',mode:absolute,to:'2020-10-26T07:55:50.536Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Solved in the new backbone.
