### ISSUE TITLE
I have searched the resources for species named after one of the three Macleay scientists (Alexander, William Sharp, William John). Is there a way that I can download the ouput as a file readable in excel?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3072]
**I have searched the resources for species named after one of the three Macleay scientists (Alexander, William Sharp, William John). Is there a way that I can download the ouput as a file readable in excel?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/dacacd827fd9ed8f5b33e7a4a4327c3b:07b76c4f40b5d989d88aaaad55b6d0d1cdbff42f3c2cf65921fbe98d9494be01d9f92e30dd91d70643c29a24a256b7ce54e9791750f71d9399565a2ae712bcac)
System: Chrome 85.0.4183 / Mac OS X 10.13.6
Referer: https://www.gbif.org/resource/search?contentType=tool
Window size: width 1259 - height 652
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-27T13:56:48.271Z',mode:absolute,to:'2020-10-27T14:02:48.271Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-27T13:56:48.271Z',mode:absolute,to:'2020-10-27T14:02:48.271Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
