### ISSUE TITLE
下载了 Cunninghamia lanceolate Hook.的数据 发现有很多在经度和纬度都是空白的 是数据错误吗？

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3073]
**下载了 Cunninghamia lanceolate Hook.的数据 发现有很多在经度和纬度都是空白的 是数据错误吗？**

我下载了杉木中国大陆 中国台湾和香港3个地区的物种分布数据 但是我用Excel 打开之后 发现在经度和纬度这两个指标中有一百多行的数据都是空白的 想知道是数据出错了吗 还是正常情况？

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0badee93d76750cfc8449deae9767103:8f6b036eb220f79cd9f5398bc8e06c5e5addad3b74dd8ed0e0990f1d64721bfdb53da75834a437f4b871e4002d97242e120f2c3c6f5d5cdfc7715a1c2d5e0829)
System: Edge 18.18362.0 / Windows 10.0.0
Referer: https://www.gbif.org/zh/occurrence/search?taxon_key=5284278
Window size: width 2560 - height 1327
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-28T13:24:26.674Z',mode:absolute,to:'2020-10-28T13:30:26.674Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-28T13:24:26.674Z',mode:absolute,to:'2020-10-28T13:30:26.674Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
