### ISSUE TITLE
It is highly unlikely that yellow-eyed penguins were found here, or inland as some other points suggest. Their range is not this far north. The individual count is also incorrect, as they do not forage together usually and this number has never been observed at sea together. Source- yellow-eyed penguin ecologist

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3074]
**It is highly unlikely that yellow-eyed penguins were found here, or inland as some other points suggest. Their range is not this far north. The individual count is also incorrect, as they do not forage together usually and this number has never been observed at sea together. Source- yellow-eyed penguin ecologist**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1425c4308c9494d0559956b904332a7b:d379b96e49a3a89d822b873f2f66ca1267b552ad6e6958f7ca88afd7192a2f0916dc38f2e9e4b29f6fe406295b9148d67d8a13b3a8f2d1c729eab92e8f804288)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2835503841
Window size: width 1536 - height 666
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-29T01:04:39.761Z',mode:absolute,to:'2020-10-29T01:10:39.761Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-29T01:04:39.761Z',mode:absolute,to:'2020-10-29T01:10:39.761Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 8a863029-f435-446a-821e-275f4f641165
publishingOrgKey: c8d737e0-2ff8-42e8-b8fc-6b805d26fc5f

**Comment by jhnwllr** [comment]
It might because of a default coordinate uncertainty: 999.

**Comment by jhnwllr** [comment]
responded by email
