### ISSUE TITLE
Citation occurrence data downloaded through QGIS

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3075]
**Citation occurrence data downloaded through QGIS**

Hello, I need to cite in a paper occurrence data of Lanius nubicus, stored in GBIF but downloaded through the QGIS plugin "GBIF occurrences". Following GBIF guidelines I must cite them with a DOI, but the download through this plugin does not assign any DOI. Therefore, I downloaded them directly through the website today, obtaining a DOI. However, for my analyses I downloaded data in April, so I ask you if I can use DOI assigned to data downloaded today, for citing data I downloaded in April.

Thank you in advance
Best wishes
Gianpasquale Chiatante PhD

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ce89a81fcd56a59336d6b0ea80d8632f:03ae79069389491e75051b5b53a7f47202863549980f818d1469c6285c4ebbcc53b42e575ef689641b1da10be7abe60e8e431ca853954a9dfcf7d7482dc6780a)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0096261-200613084148143
Window size: width 1366 - height 625
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-29T11:23:00.462Z',mode:absolute,to:'2020-10-29T11:29:00.462Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-29T11:23:00.462Z',mode:absolute,to:'2020-10-29T11:29:00.462Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.

**Comment by dnoesgaard** [comment]
NB. I just updated the QGIS tool page on GBIF.org with some notes on how to cite:

https://www.gbif.org/tool/81453/qgis
