### ISSUE TITLE
When I try to download datasets, i get an error saying that the file is corrupted and unsafe. This never used to happen...

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3076]
**When I try to download datasets, i get an error saying that the file is corrupted and unsafe. This never used to happen...**

-----

Github user: @johngphillips
User: [See in registry](https://www.gbif.org/api/feedback/user/3af5044999a4193c5f868b70ba65f286:fc8f2774321ff289b84dd10349b90faebbf332406be2584a217d8f0fb762816080a40b79d5531133bcbd5cd96f547396602fd066386ec370f29d8b431a2b81dd)
System: Chrome 86.0.4240 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/0096646-200613084148143
Window size: width 1280 - height 666
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-29T18:30:35.979Z',mode:absolute,to:'2020-10-29T18:36:35.979Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-29T18:30:35.979Z',mode:absolute,to:'2020-10-29T18:36:35.979Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The bug was fixed with and update two weeks ago.
