### ISSUE TITLE
Project pages missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3078]
**Project pages missing**

The pages displaying the BIFA (https://www.gbif.org/programme/82629/bifa-biodiversity-information-fund-for-asia#projects) and CESP (https://www.gbif.org/programme/82219/capacity-enhancement-support-programme#projects) project pages do not show all projects. And the  link to the project pages for BID is no longer available.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/af8d4317b7d102213da4f7451f2b1a64:1609f4c4f1c4badf3ddecee4098cc4271940ef7bb030beb52bf9b326b6b26bc7d954a9c503e23cb57a8764b9e9166e01fa154118e22efb34ae21ac515879de54)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 2100 - height 1133
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-30T08:13:57.798Z',mode:absolute,to:'2020-10-30T08:19:57.798Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-30T08:13:57.798Z',mode:absolute,to:'2020-10-30T08:19:57.798Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/8fb1e419a597b22290c5af11705df16a9ad15256
