### ISSUE TITLE
All incertae sedis in new dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3079]
**All incertae sedis in new dataset**

Scientific names missing from all records in this new TW sampling-event dataset. Looks like nothing in the taxon fields and the ID entered only in 'Scientific name ID"—resulting in zero matches.

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/75552e53e02de4c2a52662d0056189b6:5880e42360a573be37339dfea4909048d6db7c2769c36db426494a655cc029b70cbae9eb30db3484b299f7483279e9140b6398608d32c3b672c9628bf1cd655d)
System: Firefox 81.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/occurrence/search?dataset_key=00dfc6d8-0463-4302-862d-328a374965b9
Window size: width 1675 - height 1046
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-30T11:29:32.186Z',mode:absolute,to:'2020-10-30T11:35:32.186Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-10-30T11:29:32.186Z',mode:absolute,to:'2020-10-30T11:35:32.186Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Publisher contacted by email.

**Comment by kcopas** [comment]
Great to see this fixed. Now I notice that there are no dates—surely an oversight in a sampling-event dataset, right?

**Comment by ManonGros** [comment]
I don't know, I didn't receive any reply from them, I just saw that the dataset was fixed.
