### ISSUE TITLE
No link to IPT homepage displayed on IPT installation page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#308]
**No link to IPT homepage displayed on IPT installation page**

Only the RSS endpoint is currently displayed

-----
fbitem-96b9527ed3c47b4e8e65817ad1ca3f20236b567a
Reported by: @kbraak
System: Safari 10.1.2 / Mac OS X 10.10.5
Referer: https://www.gbif-uat.org/installation/b6bbcb00-d6a6-4c2b-a4a2-c70dbed7f188
Window size: width 1397 - height 801
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:28:41.586Z',mode:absolute,to:'2017-08-15T09:34:41.586Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:28:41.586Z',mode:absolute,to:'2017-08-15T09:34:41.586Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
@kbraak I'm not sure how to approach that.
http://api.gbif.org/v1/installation/b6bbcb00-d6a6-4c2b-a4a2-c70dbed7f188
There is no IPT homepage or IPT endpoint listed in the API. But there is an option to add a home page. Wouldn't that be the natural place to do it.

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/488
