### ISSUE TITLE
can't search literature by DOI

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3080]
**can&#39;t search literature by DOI**

Probably related to the changes to ES, but I can no longer search for papers by DOI.

(this is using the current UI/API, but it seems to be a problem in the new literature API as well)

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/3cc2dbbb25aebeec31d6d5fde4869285:24bd3b008fc679cc1fc1a5770fa39b25e591f7e8487c9cddc4f9b186f78729424042eae9eadd77c7920d7562855e20a583af28d577e9f1e1e25e1100b873ebf3)
System: Chrome 86.0.4240 / Mac OS X 10.15.7
Referer: https://www.gbif.org/resource/search?q=10.1016~2Fj.jnc.2020.125890
Window size: width 1252 - height 646
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-01T07:33:41.552Z',mode:absolute,to:'2020-11-01T07:39:41.552Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-01T07:33:41.552Z',mode:absolute,to:'2020-11-01T07:39:41.552Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
It has always been a coincidence that you could since it is a free text search. The website wrapper do not have structured search by DOI. If that is something that is important we should add it as a search field

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/a354d77e44f77b3f6358c53eefa8b79178bb62f2
please reopen if you believe free text search should work
