### ISSUE TITLE
Contact not displayed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3081]
**Contact not displayed**

The author of this dataset contacted us because one of their contacts is not displayed in "Contacts" (although it is included in the citation and available via the API: https://api.gbif.org/v1/dataset/07246b3c-69f9-4ad9-b952-8b8eb20cc4df/contact).

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/04e6ee7b6a1b9a6896175ff33d9b6e3c:70c59335847eee8d465762c7d23ddfc6ae65d1b762d94903e038c98bef5520b58ad414fbe83285ffab33689d55e2d4e134a73897badc83600504bde4224a8df3)
System: Safari 14.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/07246b3c-69f9-4ad9-b952-8b8eb20cc4df
Window size: width 1795 - height 1097
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-02T07:52:38.384Z',mode:absolute,to:'2020-11-02T07:58:38.384Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-02T07:52:38.384Z',mode:absolute,to:'2020-11-02T07:58:38.384Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
That is because they reuse the same orcid for multiple of their authors. Gregory is using the orcid of Irina Belyaeva. But since we aren't resolving the orcids to find the actual name behind the record, then the first person claiming it wins = Gregory. Since they use the same unique identifier, then they are considered one person.

```
"type": "ORIGINATOR",
"primary": false,
"userId": [
"http://orcid.org/0000-0002-1368-4806"
],
"firstName": "Gregory",
"lastName": "Tyusov",
```
