### ISSUE TITLE
Cyrillic vs. Roman

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3083]
**Cyrillic vs. Roman**

I noticed that your new field Administrative areas (backbone provided by gadm.org) deals very strangly with Cyrillic interpretations. Example: The Amurskaya oblast (BGN/PCGN) or the now worldwide adapted Amurskaja oblast (GOST 1983) appear in your thesaurus as Amurskiy rayon. This is an incorrect spelling. Also the Russian administrative subdivision according to ISO 3166-2 is "oblast" and not "rayon".

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4dccecb8e17f3b6821ff1aa350c4345c:885f5f3db88430909816727474e5bc395dab9881a12ad4e8c717bc9f44e522c4f8c56130123dc93ec4291f7002f85806217ad86264949254ced3791a0399b83b)
System: Firefox 82.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search
Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-09T07:03:39.135Z',mode:absolute,to:'2020-11-09T07:09:39.135Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-09T07:03:39.135Z',mode:absolute,to:'2020-11-09T07:09:39.135Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Hi @MortenHofft, I am not sure where best to re-link this and whether it still applies, could you advise, please?

**Comment by MortenHofft** [comment]
I do not get any results for the mentioned names. But the names used should be the ones use by GADM. If those are incorrect, then an issue should be logged with GADM? @MattBlissett you know the process for when and how we sync with GADM and what if any modifications we do.

**Comment by MattBlissett** [comment]
I don't think there's a problem here, except possibly different choices of how to transliterate Cyrillic -ий into Roman -iy or -y.

My understanding from Wikipedia: the first divisions of the Russia Federation (the federal subjects) include republics, territories (kray/krai), oblast (roughly, province), federal cities, autonomous oblasts, autonomous okrugs.

This "rayon" is a second level division: https://gadm.org/maps/RUS/khabarovsk/amurskiyrayon.html

The GADM division is Russia → Khabarovsk / Khabarovskiy Kray / Хабаровский край (Kray or Territory) → Amurskiy rayon / Амурский район (Raion or District)

ISO 3166 has this division: Russia (RU) → Khabarovskiy kray (RU-KHA) (administrative territory) → (no second-level divisions in ISO).

English Wikipedia: Russia → Khabarovsk Krai → Amursky District.

**Comment by MortenHofft** [comment]
@slieker I'm closing the issue. Feel free to comment if you believe it should be reopened.
