### ISSUE TITLE
Can't confirm new user account on UAT

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3084]
**Can&#39;t confirm new user account on UAT**

I don't know if this is by design but when creating a new user account on UAT, the confirmation email isn't received.
One of our users reported the issue and I tried it myself: I can register but I never received the confirmation email so I can't log in. My test username is: testmarie

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif-uat.org/api/feedback/user/69285232b030853cd1f133d9ffd19c31:6e6624ceb1d05970a185ef1a40f2d16fb2ab487fab8f1d6a93a0da48fb2f9f5d405f8b905fe3958158b0a55e36816981311298e2b1ede44cbae6104d0ff2f4c1)
System: Safari 14.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif-uat.org/user/profile
Window size: width 2183 - height 964
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-09T14:16:00.610Z',mode:absolute,to:'2020-11-09T14:22:00.610Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-09T14:16:00.610Z',mode:absolute,to:'2020-11-09T14:22:00.610Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Mail from the UAT registry was unintentionally disabled, but it should be working again now.
