### ISSUE TITLE
Harvard MCZ data retrieval issues

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3086]
**Harvard MCZ data retrieval issues**

I am trying to download the complete database for the Harvard MCZ collection. I first tried to download this via rgbif based on the documentation. However, I received an error when running occ_download_get because the download terminates early. 

I then tried just downloading through my browser by queuing up the same dataset and then trying to download the Darwin Core Archive. Again, I get a "Failed - Network error" issue on Chrome on Mac OSX.

Finally, I took the URL for that download and tried downloading through the terminal with wget. I have issues with this too, as the command keeps timing out with "Connection closed at byte 943184427. Retrying." Fortunately, it retries and after 18 tries, it does eventually download the entire file. However, when I tried to unzip it, I received an error, which suggests the data integrity was compromised.

So in summary, I seem to be getting this persistent connection issue. I'm on my home network and do not have issues with other large downloads, so this may be a GBIF issue. I wanted to report it in hopes that it could get solved for me and for others. Thank you!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6c0b4a0fd18cb3f81b7704c3aad06081:ef02d2b0142b7fc9761ebb797d3d1ee6fa4a8bd51114da32e3a661f8226915f9d658603acf24df45dd6ad020ded845b1cd4340498bbc83ef95a6c8e01380a684)
System: Chrome 86.0.4240 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/0106293-200613084148143
Window size: width 1387 - height 583
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-09T20:23:16.039Z',mode:absolute,to:'2020-11-09T20:29:16.039Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-09T20:23:16.039Z',mode:absolute,to:'2020-11-09T20:29:16.039Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
I'm able to reproduce this, even downloading using HTTP bypassing Varnish.

Download a few MB, then ^C and resume with:

wget --limit-rate=9M -c http://ws.gbif.org:9016/occurrence/download/request/0106293-200613084148143.zip

The resulting download is often corrupted (MD5SUM of this one should be `7ea6dded1f2ae5c5f52c6e76345f60fc`).  Inspecting the file with a binary diff, some data from earlier in the file is duplicated.

```
WARN  [2020-11-10 12:57:59,360+0000] [http-nio-9016-exec-34] org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver: Async request timed out
WARN  [2020-11-10 12:57:59,360+0000] [http-nio-9016-exec-34] org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver: Resolved [org.springframework.web.context.request.async.AsyncRequestTimeoutException]
INFO  [2020-11-10 12:57:59,360+0000] [http-nio-9016-exec-34] org.apache.catalina.connector.CoyoteAdapter: Encountered a non-recycled response and recycled it forcedly.
org.apache.catalina.connector.CoyoteAdapter$RecycleRequiredException: null
        at org.apache.catalina.connector.CoyoteAdapter.checkRecycled(CoyoteAdapter.java:525)
        at org.apache.coyote.http11.Http11Processor.recycle(Http11Processor.java:1328)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.release(AbstractProtocol.java:1071)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:945)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by MattBlissett** [comment]
Fixed, by running downloads through an Apache server rather than occurrence-ws. (This has other advantages, like being able to restart occurrence-ws without interrupting downloads, and not needing to implement HTTP Range queries ourselves.)
