### ISSUE TITLE
It seems that the true name of this taxon is Kalanchoe delagoensis Eckl. & Zeyh.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3087]
**It seems that the true name of this taxon is Kalanchoe delagoensis Eckl. &amp; Zeyh.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8a762f2d6d318434475d62b50a03a16f:bba74bd44e4a58554afdc43f6773fb1e7a3d0c59d0a4f1f591ea65ac009d85b125136d74b83e86eb47e8e858a559b2293bc1cac1d9cce2d5f44fd3d061f6b1b1)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/species/117901776
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-10T10:07:50.227Z',mode:absolute,to:'2020-11-10T10:13:50.227Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-10T10:07:50.227Z',mode:absolute,to:'2020-11-10T10:13:50.227Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Potential mis-spelling in the checklists titled "A list of the terrestrial fungi, flora and fauna of Madeira and Selvagens archipelagos": https://www.gbif.org/dataset/a43ec6d8-7b8a-4868-ad74-56b824c75698

Suggested name: Kalanchoe delagoensis Eckl. & Zeyh.
Current name: Kalanchoe delago*n*ensis Eckl. & Zeyh.

I contacted the author of the checklist by email.

**Comment by rpfigueira** [comment]
The name was changes at the source dataset by request of the publisher (http://ipt.gbif.pt/ipt/resource?r=uac_checklist_madeira). It is now pending on GBIF.org ingestion.

**Comment by ManonGros** [comment]
Solved in the new backbone.
