### ISSUE TITLE
Taxonomy of host mixed up with taxonomy of parasite

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3091]
**Taxonomy of host mixed up with taxonomy of parasite**

The title of the dataset is: Revision of Noctiliostrebla (Diptera: Streblidae), parasites of bulldog bats (Chiroptera: Noctilionidae: Noctilio)

but the higher taxonomy shown here for Noctiliostrebla is Chiroptera, Mammalia.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/cc55bad6404cb7b1b7a6c2c1acde9d34:6cfc73d4aee1c2aa51ea22ffc0dc7eba8ac4b11d88fcd6845fe4aed46969d393020172b9e1c496602e00c3e0fbacb883bea87f373149ea56a6906c22b7f36e98)
System: Safari 14.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/2234219791
Window size: width 1747 - height 899
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-12T14:52:24.356Z',mode:absolute,to:'2020-11-12T14:58:24.356Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-12T14:52:24.356Z',mode:absolute,to:'2020-11-12T14:58:24.356Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 6efa7f72-4a8f-4101-aa9f-eab5c40ab01a
publishingOrgKey: 7ce8aef0-9e92-11dc-8738-b8a03c50a862

**Comment by truschel** [comment]
The problem was solved.
Thank you for showing us this problem!

**Comment by ManonGros** [comment]
Great, thank you @truschel!
