### ISSUE TITLE
Endorsement of DBES to publish

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3092]
**Endorsement of DBES to publish**

Hello,

I would like to ask for an update regarding the status of our application to publish data on GBIF. 

Also, I would like to amend the name of the publisher 

from:  "Department of Biology and Environmental Science, College of  Science, University of the Philippines" 

to: "Department of Biology and Environmental Science, College of  Science, University of the Philippines Cebu"

 The 'University of the Philippines Cebu" (UP Cebu) is a constituent university of the 'University of the Philippines" (UP).

Thank you. 

Regards,

Brisneve Edullantes
bedullantes@up.edu.ph

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/48b18ee125ff1dc0bf7a378b622f4595:890539c06339847f797ec0fdb31f622e8e4c177abeda76d8e725f5d75e24d1ad3936a3515ebd8cc77fef96ee16dd1551f725067ad64ec51324ac513e41f1aec3)
System: Chrome 86.0.4240 / Mac OS X 10.15.0
Referer: https://www.gbif.org/node/7f48e0c8-5c96-49ec-b972-30748e339115
Window size: width 1366 - height 581
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-13T05:25:11.870Z',mode:absolute,to:'2020-11-13T05:31:11.870Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-13T05:25:11.870Z',mode:absolute,to:'2020-11-13T05:31:11.870Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I see that this has been handled on Helpdesk
