### ISSUE TITLE
broken images and placeholder images

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3093]
**broken images and placeholder images**

Auckland Museum Botany Collection has a lot of broken images and many of those that do work is actually placeholders with the text: "Digital image not yet created" or "Online image not available"

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/50e119b26fc3f00b21afd07cd5cf9a37:51c0246b8f283d8a05f95fb2d5ecb7cb7a57f502cdfcaae86f178847d6303e19d53b5e370de7aef6494ee9354f86077437844b92b007faaa8091b10af50e6871)
System: Chrome 86.0.4240 / Mac OS X 10.15.6
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=83ae84cf-88e4-4b5c-80b2-271a15a3e0fc
Window size: width 1440 - height 766
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-13T09:42:12.386Z',mode:absolute,to:'2020-11-13T09:48:12.386Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-13T09:42:12.386Z',mode:absolute,to:'2020-11-13T09:48:12.386Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Related to https://github.com/gbif/portal-feedback/issues/19
