### ISSUE TITLE
When I draw a polygon it is difficult to see whether the inflection point coordinates are accurate.  Is there an easy way to simply enter the sequence of coordinates or to view all of them (not just the first few) while they are being adjusted on the search map?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3094]
**When I draw a polygon it is difficult to see whether the inflection point coordinates are accurate. Is there an easy way to simply enter the sequence of coordinates or to view all of them (not just the first few) while they are being adjusted on the search map?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/dfbff01180ea5c92888c605efdc2362d:4133cca9e586a7baee081eaef759621f74e711794660d40b855bd45cfe748b12ccc5150359fa4c1329002d1332e406db75571d03baaf99a061cafd802fb9fdb4)
System: Firefox 82.0.0 / Mac OS X 10.14.0
Referer: https://www.gbif.org/dataset-classes
Window size: width 1825 - height 888
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-14T21:05:54.260Z',mode:absolute,to:'2020-11-14T21:11:54.260Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-14T21:05:54.260Z',mode:absolute,to:'2020-11-14T21:11:54.260Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I'm not sure I fully understand the question, but there are multiple ways to do a spatial search

* search for an area [using Global Administrative Areas](https://www.gbif.org/occurrence/search?occurrence_status=present&gadm_gid=TTO.8_1).
* Using a [country](https://www.gbif.org/occurrence/search?country=US&occurrence_status=present) (ISO 3166-1 standard)
* Using a [continent](https://www.gbif.org/occurrence/search?continent=ANTARCTICA&occurrence_status=present) 
* By drawing an area (location filter)
  * <img width="349" alt="Screenshot 2020-11-16 at 08 11 55" src="https://user-images.githubusercontent.com/6759267/99222894-bdc81d00-27e3-11eb-8ef2-0cf5990fabfa.png">
* By entering a min-max latitude, longitude (location filter)
  * <img width="338" alt="Screenshot 2020-11-16 at 08 12 07" src="https://user-images.githubusercontent.com/6759267/99222811-a0934e80-27e3-11eb-910f-a850763cee00.png">
* By entering/cp WKT or GeoJSON (location filter)
  * <img width="334" alt="Screenshot 2020-11-16 at 08 12 12" src="https://user-images.githubusercontent.com/6759267/99222784-95d8b980-27e3-11eb-8db8-020d64c0fa73.png">

Hope that helps
