### ISSUE TITLE
Generic name wrong

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3097]
**Generic name wrong**

The genus Otiorhynchus (Insecta, Coleoptera) is wrongly given as Otiorrhynchus in Otiorrhynchus bisulcatoides.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a6a26ade0b1ed8e7dd5224ec4c477fe1:c054f0bd14270fd6d7faf77c2359e6818c462e16dd1a611fedccd412ae04f54e1bbc0e5d08d93fa9ab6a88e562093555961a9adc4b729c0183dacf9bd5b7efbf)
System: Firefox 82.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0113898-200613084148143
Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-17T04:41:50.080Z',mode:absolute,to:'2020-11-17T04:47:50.080Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-17T04:41:50.080Z',mode:absolute,to:'2020-11-17T04:47:50.080Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The mis-spelling concerns this species: https://www.gbif.org/species/1200377

**Comment by ManonGros** [comment]
The only checklist using the name `Otiorrhynchus bisulcatoides E.Reitter, 1913` is the Backbone Taxonomy. And I don't know where it comes from.

The CoL is using what seems to be the correct spelling. WoRMS seems to have used the spelling we have for the genus (https://www.gbif.org/species/155468527) but the link to their system for that species is unresponsive.

@mdoering, can you help me find out where we got this name from?

**Comment by mdoering** [comment]
Checking the API response for the backbone species you can see it originated from COL:
https://api.gbif.org/v1/species/1200377
`
"constituentKey":"7ddf754f-d193-4cc9-b351-99906754a03b",
`
http://api.gbif.org/v1/dataset/7ddf754f-d193-4cc9-b351-99906754a03b

It must have existed in the december edition:
https://data.catalogueoflife.org/dataset/2242/taxon/4B585

A provisionally accepted name from the notorious wtaxa source that has been cleaned since.
