### ISSUE TITLE
How to register when in doubt about subspecies

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3098]
**How to register when in doubt about subspecies**

How do we best indicate when in doubt about which of two subspieces in a sample it concerns? In the Netherlands we have breeding colonies of Larus fuscus where two different subspecies are found. Up to a certain age it is difficult to determine which subspecies is concerned. Example: we now enter Larus fuscus intermedius/graelsii. GIBF returns an incomplete Larus fuscus intermedius (Catalognumber NMR998900162870)......

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0f98e6e854ea59f104c0fb8a3596e191:7db647c7e94db594f7959c63ebe2e3c5cd164137f1cc7958f9313d6eb17f0d438ccb17f7bc4157da6e8c727f2edf75df867bcbbed856a5938a2dbae9f137ceb3)
System: Firefox 82.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2865699348
Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-17T06:39:50.494Z',mode:absolute,to:'2020-11-17T06:45:50.494Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-17T06:39:50.494Z',mode:absolute,to:'2020-11-17T06:45:50.494Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: a307e4d7-1de2-4adc-95d5-a0a8d5f57236
publishingOrgKey: 3ead5cf3-2840-482e-bbd9-76380825be63

**Comment by ManonGros** [comment]
Replied by email:
> When in doubt with the identification of a specimen, the best is to use the higher taxon in the scientific name (our system isn’t able to interpret two names in the scientific name field). So in your case, I would suggest to put the species name in the scientific name. You can specify the two potential sub-species in the occurrenceRemark field (or if you use the [identification extension](https://dwc.tdwg.org/terms/#identification), in the identificationRemark field).

**Comment by ManonGros** [comment]
I sent a second email based on some useful feedback:
> It has been brought to my attention that my reply was actually incomplete.
Not only, you should keep the identification to the species level in the scientific name but it is also probably worthwhile to add "intermedius or graelsii" to identificationQualifier. You can also populate the specificEpithet field and leave the intraspecificEpithet blank.
I would also like to add that the identificationRemak field is available for occurrences (no need to use an identification extension).
