### ISSUE TITLE
iDigBio news item fails

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#310]
**iDigBio news item fails**

https://www.gbif-uat.org/news/83368/idigbio-joins-gbif-as-organizational-member

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb
Reported by: @mortenhofft
System: Chrome 60.0.3112 / Mac OS X 10.11.6
Referer: https://www.gbif-uat.org/resource/search?contentType=news
Window size: width 1440 - height 776
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:35:55.474Z',mode:absolute,to:'2017-08-15T09:41:55.474Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:35:55.474Z',mode:absolute,to:'2017-08-15T09:41:55.474Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/8d997894274330ec4b346f3b89899ccedd4792b9
