### ISSUE TITLE
Making data cleaning more efficient

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3101]
**Making data cleaning more efficient**

I am working on one of our datasets. There are multiple flags, more than the number of records. It would be useful if there were an option for selecting aan aggregatd download, one with all the flagged records with flags indicating which flags applied to a particular record. I am creating such a file because it will enable use to address all issues with a record at the same time.

It would also be good if one could mark a record as reviewed and either resolved or impossible to resolve, for example if the only collection location is "Soviet Union" or the occurrence is an artificial hybrid so it is identified by a hybrid formula.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8bcba5d4b6affe3933c2380d53d8e41b:ea8d57d4fd2059c3d7258b1edeb8269d467f80cba05fe982fab0167106c3e33de3a6344f6645183aefc0bbc6dc35d9d4e0d2cd458155f5b48ba135fb6b2f2e09)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download?dataset_key=7827f68d-c981-4023-bace-288a03434044&issue=TAXON_MATCH_HIGHERRANK
Window size: width 1055 - height 932
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-17T21:17:01.739Z',mode:absolute,to:'2020-11-17T21:23:01.739Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-17T21:17:01.739Z',mode:absolute,to:'2020-11-17T21:23:01.739Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
Replied by email:
> It is already possible to select all the record flagged and to download them, see [this link](https://www.gbif.org/occurrence/download?dataset_key=7827f68d-c981-4023-bace-288a03434044&issue=COORDINATE_OUT_OF_RANGE&issue=COORDINATE_INVALID&issue=COORDINATE_ROUNDED&issue=GEODETIC_DATUM_INVALID&issue=GEODETIC_DATUM_ASSUMED_WGS84&issue=COORDINATE_REPROJECTED&issue=COORDINATE_REPROJECTION_FAILED&issue=COORDINATE_REPROJECTION_SUSPICIOUS&issue=COORDINATE_ACCURACY_INVALID&issue=COORDINATE_PRECISION_INVALID&issue=COORDINATE_UNCERTAINTY_METERS_INVALID&issue=COORDINATE_PRECISION_UNCERTAINTY_MISMATCH&issue=COUNTRY_COORDINATE_MISMATCH&issue=COUNTRY_MISMATCH&issue=COUNTRY_INVALID&issue=COUNTRY_DERIVED_FROM_COORDINATES&issue=CONTINENT_COUNTRY_MISMATCH&issue=CONTINENT_INVALID&issue=CONTINENT_DERIVED_FROM_COORDINATES&issue=PRESUMED_SWAPPED_COORDINATE&issue=PRESUMED_NEGATED_LONGITUDE&issue=PRESUMED_NEGATED_LATITUDE&issue=RECORDED_DATE_MISMATCH&issue=RECORDED_DATE_INVALID&issue=RECORDED_DATE_UNLIKELY&issue=TAXON_MATCH_FUZZY&issue=TAXON_MATCH_HIGHERRANK&issue=TAXON_MATCH_NONE&issue=DEPTH_NOT_METRIC&issue=DEPTH_UNLIKELY&issue=DEPTH_MIN_MAX_SWAPPED&issue=DEPTH_NON_NUMERIC&issue=ELEVATION_UNLIKELY&issue=ELEVATION_MIN_MAX_SWAPPED&issue=ELEVATION_NOT_METRIC&issue=ELEVATION_NON_NUMERIC&issue=MODIFIED_DATE_INVALID&issue=MODIFIED_DATE_UNLIKELY&issue=IDENTIFIED_DATE_UNLIKELY&issue=IDENTIFIED_DATE_INVALID&issue=BASIS_OF_RECORD_INVALID&issue=TYPE_STATUS_INVALID&issue=MULTIMEDIA_DATE_INVALID&issue=MULTIMEDIA_URI_INVALID&issue=REFERENCES_URI_INVALID&issue=INTERPRETATION_ERROR&issue=INDIVIDUAL_COUNT_INVALID&issue=INDIVIDUAL_COUNT_CONFLICTS_WITH_OCCURRENCE_STATUS&issue=OCCURRENCE_STATUS_UNPARSABLE&issue=OCCURRENCE_STATUS_INFERRED_FROM_INDIVIDUAL_COUNT&issue=ZERO_COORDINATE). If you choose the “SIMPLE” download format, you will be able to see the issues in the “issue” column. This column with contain all the flags and issues concerning each record separated by a “;”. For example: “COORDINATE_ROUNDED;OCCURRENCE_STATUS_INFERRED_FROM_INDIVIDUAL_COUNT”.
You can use this column to filter for records (I know it is possible in excel and OpenRefine for example).

> For issues that can’t be resolved such as the one you mentioned, I suggest to leave the records as they are and/or add a comment in the occurrenceRemark field for example (or other “remark” fields)

**Comment by MortenHofft** [comment]
It looks to me like this can be closed i favour of https://github.com/gbif/portal-feedback/issues/3113
please reopen if I misunderstand
