### ISSUE TITLE
Link to OBIS manual needs updated

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3102]
**Link to OBIS manual needs updated**

The current link to the OBIS Darwin Core manual needs to be updated to https://obis.org/manual/. Basically just need to remove the i in front of OBIS.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/09ace04fa05d7e5082ea50e94c373053:6d41208e310f7fffad5c4ce3408dbce97093d4f9883770cd9339dee9f06d597eb5a8c2f3e4d97e8530c4e2b8364e1cec5e78f96d28bb872f4b148cee2ea2afd9)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/darwin-core
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-19T17:52:46.914Z',mode:absolute,to:'2020-11-19T17:58:46.914Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-19T17:52:46.914Z',mode:absolute,to:'2020-11-19T17:58:46.914Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by dnoesgaard** [comment]
Thanks, @albenson-usgs. This has now been updated.
