### ISSUE TITLE
Downloading images

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3105]
**Downloading images**

Hi there, 

Is there a way to batch-download images associated to occurrences the same way there is one to download occurrence data?

Thanks a lot!
AP Drapeau Picard

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e82bfff610daddc535d06aec3b171bf7:835f61a595d3d929ec21d7efc49f0aeb0f73721ad406b79f9c03996623890fdb125923aa109a911b34c0aa4851c74086fb698dee20d9aca37a747369cfc7e1f7)
System: Chrome 87.0.4280 / Mac OS X 10.15.7
Referer: https://www.gbif.org/fr/occurrence/1587290321
Window size: width 1280 - height 698
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-20T14:14:16.022Z',mode:absolute,to:'2020-11-20T14:20:16.022Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-20T14:14:16.022Z',mode:absolute,to:'2020-11-20T14:20:16.022Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO
datasetKey: 1b2af425-9f6f-4b28-a008-af9757317c4c
publishingOrgKey: 2cd829bb-b713-433d-99cf-64bef11e5b3e

**Comment by ManonGros** [comment]
Replied by email:
> As you might already know, GBIF doesn’t host any images. Data providers share images URLs with us, that we then display (more information on how multimedia is share on GBIF [here](https://data-blog.gbif.org/post/gbif-multimedia/)).
You can access the image URLs by choosing the “DARWIN CORE FORMAT” when downloading the data. This format will include a “verbatim.txt” file as well as a “multimedia.txt” file. Both these files can contain references to images. If you are comfortable with command lines and/or programming language, you can automate the download of these images by using these URLs.
 
> Note that the licenses for images might differ from the coordinate licenses. I suggest to check the images licenses (in the multimedia file or directly on the occurrence pages) to see if they are suitable for your use case.
