### ISSUE TITLE
Updating language in user settings doesn't work

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3107]
**Updating language in user settings doesn&#39;t work**

Clicking "Start editing", changing the language, then "Save", doesn't persist changes.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d4fadb10f243f3c6f51b37d954ecc110:ac5daae724303065a94cf6962de2ae86fe4e475a360a8f3872767e605e39e7b165e503e6ed23719e1566d5197b08457e05fb03446e596266eb44350d2d42d6e6)
System: Firefox 83.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1920 - height 618
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-24T08:27:13.307Z',mode:absolute,to:'2020-11-24T08:33:13.307Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-24T08:27:13.307Z',mode:absolute,to:'2020-11-24T08:33:13.307Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MattBlissett** [comment]
Never mind, it seems to work for everyone else.
