### ISSUE TITLE
A curadoria e contato com o Herbário IAC mudaram - The curatorship and contact with the Herbarium IAC changed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3109]
**A curadoria e contato com o Herbário IAC mudaram - The curatorship and contact with the Herbarium IAC changed**

Due to the retirement of colleague Dr. Roseli Torres, I (Luís Bernacci - bernacci@iac.sp.gov.br, herbarioIAC@gmail.com) took over the curatorial work at Herbário IAC (http://splink.cria.org.br / manager / detail? resource = IAC).

Roseli's institutional email (@ iac.sp.gov.br) has been disabled and it is no longer possible to contact her through this address, and it is possible to contact her through emailrbtorres@gmail.com.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7c5d9f9916164b0ec5fad0c37e205548:0bd672faf3b0fc26a5a8cacd09d26e02d0265d3b90e98847d241ad8c517ace1b94cd34f35eb2a8050a3283f1c7cc8661604bf4275e32f8968eed1852d0839991)
System: Chrome 87.0.4280 / Windows 7.0.0
Referer: https://www.gbif.org/dataset/1064b787-c882-493e-b17d-4ffba363b776
Window size: width 1360 - height 600
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-24T15:59:32.174Z',mode:absolute,to:'2020-11-24T16:05:32.174Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-24T15:59:32.174Z',mode:absolute,to:'2020-11-24T16:05:32.174Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
It seems like the dataset has been updated.
