### ISSUE TITLE
busket icon

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#311]
**busket icon**

to remove filters is not intuitive - a bit scary as you feel like you are about to delete smth, not remove filters. Not sure what is a lighter alternative https://www.google.dk/search?q=remove+filters+icon&amp;ie=utf-8&amp;oe=utf-8&amp;client=firefox-b&amp;gws_rd=cr&amp;ei=HMSSWfYu0tfpBPa3k6AH

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c
Reported by: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/dataset/search?q=
Window size: width 1694 - height 819
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:46:44.342Z',mode:absolute,to:'2017-08-15T09:52:44.342Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:46:44.342Z',mode:absolute,to:'2017-08-15T09:52:44.342Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Probably a crossed out funnel,

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/487
