### ISSUE TITLE
Today we published dataset https://www.gbif.org/dataset/4ab87d2f-a65c-4f81-9064-352aa746efa3with 281 occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3116]
**Today we published dataset `https://www.gbif.org/dataset/4ab87d2f-a65c-4f81-9064-352aa746efa3with` 281 occurrences**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7f6dc66c6afa25dd92b2c919d19669d7:d1a3197b016e337ba45e5f064a0c095310c686d95a273cbb058315a83477dfc31b3554340dfcff0eab3d1c128ecb765c3f01c4cab57ce5473f30bdb635887784)
System: Opera 72.0.3815 / Windows 7.0.0
Referer: https://www.gbif.org/dataset/4ab87d2f-a65c-4f81-9064-352aa746efa3
Window size: width 1504 - height 751
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-27T03:52:54.488Z',mode:absolute,to:'2020-11-27T03:58:54.488Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-27T03:52:54.488Z',mode:absolute,to:'2020-11-27T03:58:54.488Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
Replied by email.
