### ISSUE TITLE
Organism ID push button renders the whole dataset after the first click

### ISSUE THREAD

**Issue by vmzomdav** [gbif/portal-feedback#3118]
Hi

I have noticed a rendering miss function in the second time click calling link for Organism ID push button.
The first time click renders the number of occurrences displayed on the push button, but using the browser “go back” will the second time click renders the dataset content.

https://www.gbif.org/occurrence/1810013068
 
Mvh
Marc

**Comment by ManonGros** [comment]
I have the same issue (very strange).
