### ISSUE TITLE
Irish dragonfly dataset not indexing?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3120]
**Irish dragonfly dataset not indexing?**

Just noticing that this new-ish (May 2020) dataset from the Irish node has no occurrences. Having trouble determining how many records are at the source, but even though this looks to be a dynamic project-based dataset, it seems odd that there are still no records. 

Flagging it in the event it's gone unnoticed. 

And, because dragonflies.

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/673410815569a5dc0f844951da282aad:1ae6a076e13bbe69b528614eed5890a82d4550e8ff5ed0d1e86ecd4c86c1cb006c07a8630cb9ea84447f6424ddce20d58cdbfe9f76c73f8c9f21567de6fd91b9)
System: Firefox 83.0.0 / Mac OS X 10.16.0
Referer: https://www.gbif.org/dataset/43fa788e-a1ac-46bd-ab45-cd39db08d754
Window size: width 1680 - height 923
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-01T06:56:38.377Z',mode:absolute,to:'2020-12-01T07:02:38.377Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-01T06:56:38.377Z',mode:absolute,to:'2020-12-01T07:02:38.377Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by ahahn-gbif** [comment]
publisher contacted via email from helpdesk

**Comment by ahahn-gbif** [comment]
fixed, closing
