### ISSUE TITLE
Mis-mapped spmns

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3122]
**Mis-mapped spmns**

These spmns were collected in Hidalgo County, in southmost Texas, but they are mapped to a location well north of that.

Thanks, Mike Quinn, Austin

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/975e3490b71a25d09b4798c4ac13dbc5:a6ec03ea1d16f71520ce3bfe6e46fb4f6a9b77637e8215806d79dff862ef5e4d6446b9ccd315de197edb533a289259469f4358c63ba728c9aeeeb58ad67fa70d)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?geometry=POLYGON((-97.0839846432209%2029.624633738771085,-96.4248049557209%2029.624633738771085,-96.4248049557209%2030.283813426271085,-97.0839846432209%2030.283813426271085,-97.0839846432209%2029.624633738771085))&has_coordinate=true&has_geospatial_issue=false&occurrence_status=present&taxon_key=6003262
Window size: width 1515 - height 673
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-02T23:27:38.846Z',mode:absolute,to:'2020-12-02T23:33:38.846Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-02T23:27:38.846Z',mode:absolute,to:'2020-12-02T23:33:38.846Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Contacted publisher by email.
