### ISSUE TITLE
After publication dataset we received "Collection match fuzzy	  Institution match none"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3123]
**After publication dataset we received &quot;Collection match fuzzy Institution match none&quot;**

It seems all specimens of our datasets (and some other datasets based on 
herbarium specimens) have error "Collection match fuzzy". How the field 
"Collection code" should be filled to get rid of this error?
Another new error is "Institution match none". Does it mean we should 
fill the field "institutionCode" or "institutionID" or both?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6ddcffe5571837e3d0435201512f7a3a:946789b282a9889ba7b412252fb7d30dc25fed124c15a0d785cb72fe5c19af9ac4aaa45594e5a0d33f890e2a69a5e78b238aca55098c368326422c4e5c6a069a)
System: Opera 72.0.3815 / Windows 7.0.0
Referer: https://www.gbif.org/dataset/4ab87d2f-a65c-4f81-9064-352aa746efa3/metrics
Window size: width 1244 - height 679
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-03T03:03:15.715Z',mode:absolute,to:'2020-12-03T03:09:15.715Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-03T03:03:15.715Z',mode:absolute,to:'2020-12-03T03:09:15.715Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.

**Comment by rukayaj** [comment]
Can you paste the reply @ManonGros, this is the first hit on google for this error :)

**Comment by ManonGros** [comment]
Thanks @rukayaj!
I will write an answer a bit more generic on the topic:

These flags are the result of our attempt to match our GrSciColl entries to specimen records. We now have a lookup service (https://www.gbif.org/developer/registry#lookup) which we use to match institution/collection codes and IDs.
 
You can avoid getting the “Institution match none” by providing an institution code and/or identifier as long as it is registered in GrSciColl. For more information, please check our FAQ on the topic: https://www.gbif.org/faq?question=how-can-i-improve-the-matching-of-occurrence-records-with-grscicoll
