### ISSUE TITLE
interpreted country is wrong, original country correct

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3126]
**interpreted country is wrong, original country correct**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d7fe36f71fe746454f8abea745771925:5bb8b49be668da07b14de178c2e7c07bbc0b9c8d94871e95961ec9fd46973a1bfb437f3b635dc5cd268f236aa4c9a464465444bb33ba61bbb6ece5627d30faa6)
System: Safari 14.0.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/437911126
Window size: width 1366 - height 594
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-04T19:58:17.563Z',mode:absolute,to:'2020-12-04T20:04:17.563Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-04T19:58:17.563Z',mode:absolute,to:'2020-12-04T20:04:17.563Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: b5cdf794-8fa4-4a85-8b26-755d087bf531
publishingOrgKey: 2cd829bb-b713-433d-99cf-64bef11e5b3e

**Comment by ManonGros** [comment]
The country entered is Nepal but the country code is "NE" (Niger), Nepal should be "NP".

**Comment by ahahn-gbif** [comment]
Since no coordinates are provided, the interpretation mechanism uses the country code over the country name in case of contradictory values.
