### ISSUE TITLE
this specimen is from Nigeria, not Niger

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3127]
**this specimen is from Nigeria, not Niger**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/db2f988c0b36ccc45398e88dce38c822:321f59cfcc834b720a0e2a68c467f1f8cd33d0395473c422d3ce795e7fde9b10c61739728e7e2296d202469a67f735afdc8b6e628c063950d9a629a57531db8c)
System: Safari 14.0.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/438981660
Window size: width 1366 - height 594
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-04T20:05:48.878Z',mode:absolute,to:'2020-12-04T20:11:48.878Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-04T20:05:48.878Z',mode:absolute,to:'2020-12-04T20:11:48.878Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: b5cdf794-8fa4-4a85-8b26-755d087bf531
publishingOrgKey: 2cd829bb-b713-433d-99cf-64bef11e5b3e

**Comment by ManonGros** [comment]
The country is Nigeria but the country code entered is "NE" (Niger). The country code should be "NG".

**Comment by jhnwllr** [comment]
record appears in Nigeria now.
