### ISSUE TITLE
CoL logo (page bottom) does not show

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#313]
**CoL logo (page bottom) does not show**

as per title

-----
fbitem-species7478081
Reported by: @ahahn-gbif
System: Firefox 54.0.0 / Windows 10 0.0.0
Referer: https://www.gbif-uat.org/species/7478081
Window size: width 1408 - height 596
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:51:22.756Z',mode:absolute,to:'2017-08-15T09:57:22.756Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:51:22.756Z',mode:absolute,to:'2017-08-15T09:57:22.756Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I cannot reproduce, but could have something to do with the image not be properly located on our server as it should be. I have added it. If the issue continues please reopen.
https://github.com/gbif/portal16/commit/a885133423a7e363e7d9da110e40b1c7e62079d6
