### ISSUE TITLE
how do I search for records with a blank in the "recorded by" field?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3130]
**how do I search for records with a blank in the &quot;recorded by&quot; field?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2a33a6efa3d3bc5dcb0daef30e4ab84b:777f8388f41b6b62b484c9b25cba395c9ea2a32a8ea8be31d26bd32a0d3808d30925dc0ce3f02bdbe168dff3b1c9e1422d917422cd91f83bfdae49d6c1e555d3)
System: Safari 14.0.0 / Mac OS X 10.15.6
Referer: https://www.gbif.org/occurrence/search?basis_of_record=PRESERVED_SPECIMEN&country=AU&event_date=1700-01-01,1900-12-31&taxon_key=359&advanced=1
Window size: width 1680 - height 779
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-05T23:43:36.581Z',mode:absolute,to:'2020-12-05T23:49:36.581Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-05T23:43:36.581Z',mode:absolute,to:'2020-12-05T23:49:36.581Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.

**Comment by chooknanny** [comment]
Im sorry but I did not get an email with the answer. can you send to Celia.cramer@sydney.edu.au

**Comment by Farabon** [comment]
Hi,
I have the same question and would welcome the solution. Thanks !

**Comment by MortenHofft** [comment]
The UI do not allow you to do that. But you can do so using our APIs using the predicate type `isNull`.
See https://techdocs.gbif.org/en/openapi/v1/occurrence#/Occurrence%20downloads
```json
{
  "type": "isNull",
  "parameter": "RECORDED_BY"
}
```

We are also working on a new UI that allows "exists" type queries.
