### ISSUE TITLE
search to find null data for 'recorded by'

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3133]
**search to find null data for &#39;recorded by&#39;**

how do I search to find all the records which have no data for the field "recorded by'.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a45c3c599e05acff635a8b08c08cc63d:156d15b8446ae3f6c72b6bbf950769a7f652451dc70e0ee42511e73cc1789428e244841d69cc8c9b62264f682b98def17dab8d2c1eecac3d295d871d885ccd5f)
System: Safari 14.0.0 / Mac OS X 10.15.6
Referer: https://www.gbif.org/occurrence/search?basis_of_record=PRESERVED_SPECIMEN&country=AU&event_date=1700-01-01,1900-12-31&taxon_key=212&advanced=1
Window size: width 1680 - height 779
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-06T23:42:21.858Z',mode:absolute,to:'2020-12-06T23:48:21.858Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-06T23:42:21.858Z',mode:absolute,to:'2020-12-06T23:48:21.858Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
