### ISSUE TITLE
visual navigation for participation and publishers

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3135]
**visual navigation for participation and publishers**

Please take a look how visual search works, try e.g. find Denmark. I like visual and hierarchical navigation, which could, potentially, go all the way to publisher level https://www.ups.com/us/en/global.page

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/836267a3e280bd4a501815ae49280d14:6c30975f30142bf74059fcadad2aee10edf882daab7895606dba957475c950db3e5023e4c62b4b266ea153d87a989d157477865a86317f95279784fbc3ca7ab7)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/the-gbif-network
Window size: width 1862 - height 926
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-07T10:30:45.400Z',mode:absolute,to:'2020-12-07T10:36:45.400Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-07T10:30:45.400Z',mode:absolute,to:'2020-12-07T10:36:45.400Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
Isn´t  this pretty well covered here: https://www.gbif.org/the-gbif-network ?
The countries on the map are clickable, which then gives a list of participants and associated datasets (below the map).
Shortcuts for regions (continents) given as tabs above the map will zoom to and aggregate at regional level

**Comment by dschigel** [comment]
Yes you are right @thomasstjerne

**Comment by MortenHofft** [comment]
I'm confused @dschigel - should this issue be closed again then?
