### ISSUE TITLE
I am new to iNaturalist. I joined so that I could contact owners of various images to get permission to use them. Is there a way to message someone? Thank you!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3136]
**I am new to iNaturalist. I joined so that I could contact owners of various images to get permission to use them. Is there a way to message someone? Thank you!**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/061c2b77fb3d77bc9131ff445c95d1f9:73fef0e7b27364c8a91fb80d2f43e7f32077cfc48e8de5dd248840319e95cd0420129c1299c6297fcde99ab0e05cd79e05b3411ceeea1cf234bc3b9c5c37e5cd)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2634021546
Window size: width 1536 - height 736
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-08T00:24:22.085Z',mode:absolute,to:'2020-12-08T00:30:22.085Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-08T00:24:22.085Z',mode:absolute,to:'2020-12-08T00:30:22.085Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

**Comment by ManonGros** [comment]
Contacted by email.
