### ISSUE TITLE
This isn't Veronica cymbalaria, it's a clear Veronica hederifolia (violet corolla, deltoid sepals...) , please you must correct this mistake.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3138]
**This isn&#39;t Veronica cymbalaria, it&#39;s a clear Veronica hederifolia (violet corolla, deltoid sepals...) , please you must correct this mistake.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8e231cc3401ba6edb1b67f2a875673a7:8be7d5d3561b0c6e83cf640b26aefbd95ec6003c3eab7e9e54dba6f1bea50822bb51880260cf4ade41cb4ffbc5094a575edc2871920836f02b8769c912ff1099)
System: Chrome Mobile 86.0.4240 / Android 0.0.0
Referer: https://www.gbif.org/es/occurrence/2644791008
Window size: width 360 - height 598
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-08T10:41:48.624Z',mode:absolute,to:'2020-12-08T10:47:48.624Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-08T10:41:48.624Z',mode:absolute,to:'2020-12-08T10:47:48.624Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by ManonGros** [comment]
Voted for suggestion in Pl@ntNet feedback system: https://identify.plantnet.org/weurope/observations/1003276174

**Comment by CecSve** [comment]
Pl@ntNet has removed the occurrence and the record is no longer searchable on GBIF.org. The user has been notified via helpdesk.
