### ISSUE TITLE
Add FAQ about linking records to GrSciColl entries

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#3139]
@dnoesgaard Could you put up the following FAQ?

---
**How can I improve my matches to GRSciColl?**

Data comes to us in a variety of forms. We match occurrences to collections using collectionCode, institutionCode, collectionID...
Sometimes these are ambiguous, and during these cases we flag that the match was fuzzy - we think it is correct, but may have issues. This is documented [here](https://www.gbif.org/developer/registry#lookup).

To improve matching we recommend:
* Populate the Darwin Core fields `institutionID` and `collectionID` in your data using identifiers available in GRSciColl. This is the safest option as it it a definitive statement and will ensure a direct match. There can be several identifiers to choose from, and we recommend in priority order:
    1. An LSID if one is available,
    2. A GRSCICOLL ID or GRSCICOLL URI,
    3. If no others exist, please use the UUID from the page URL.
* Ensure you use both institutionCode and collectionCode in your data - if ambiguous, it may not match.

For help fixing data in GRSciColl please contact scientific-collections@gbif.org

Please be aware that we expect to issue new guidelines in the future to use DOIs. The UUIDs will still be supported when this happens and the DOI solution is not yet in place.

---

It would be great to have the FAQ linked from the occurrence tagged with the related flags ("collection match fuzzy", "collection match none", etc.) as well as from GrSciColl entries.
@MortenHofft do you think this would be possible?

**Comment by dnoesgaard** [comment]
Done. I've edited the entry slightly for style: https://www.gbif.org/faq?question=how-can-i-improve-the-matching-of-occurrence-records-with-grscicoll

(Formating these is tricky because tags are stripped)

**Comment by dnoesgaard** [comment]
(Btw I removed the DOI stuff as it's a bit too uncertain for this type of content)

**Comment by ManonGros** [comment]
Thanks @dnoesgaard! Would it be possible to add the link to the API documentation?
> Our matching service and associated flags are documented [here](https://www.gbif.org/developer/registry#lookup)

**Comment by dnoesgaard** [comment]
Done.
