### ISSUE TITLE
Open newly registered organisation page broken (404)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#314]
**Open newly registered organisation page broken (404)**

Blocked by service only deployed currently on Dev

However, confirmed working on Dev at least: https://api.gbif-dev.org/v1/organization/a5759ce9-f00d-4346-9e51-4d5fb067a729

-----
fbitem-publishera5759ce9-f00d-4346-9e51-4d5fb067a729
Reported by: @kbraak
System: Safari 10.1.2 / Mac OS X 10.10.5
Referer: https://www.gbif-uat.org/publisher/a5759ce9-f00d-4346-9e51-4d5fb067a729
Window size: width 1397 - height 778
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:51:46.659Z',mode:absolute,to:'2017-08-15T09:57:46.659Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:51:46.659Z',mode:absolute,to:'2017-08-15T09:57:46.659Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
A case of mixed endpoints and a hardcoded environment variable

**Comment by MortenHofft** [comment]
Thanks. We have retested on dev with the correct config of endpoints where it works. To work in prod/uat we need the registry to be deployed. That will be done for the release.
