### ISSUE TITLE
Calculation of totals shown on home page, mismatch with click through resultset for publishers

### ISSUE THREAD

**Issue by nickynicolson** [gbif/portal-feedback#3141]
The [GBIF home page](http://www.gbif.org) shows data totals (numbers as per 2020-12-09):

- Occurrence records 1,635,146,264
- Datasets 54,920
- Publishing institutions 1,679
- Peer-reviewed papers using data 5,205

These are presented as clickable links through into the search results. For occurrences, datasets and papers, the record total in the click through results is as shown on the home page, but in the case of the publishing institutions, the click through result set shows a different total: home page shows 1679, click through result set shows 2087.

What is the cause of the discrepancy? Should there be some search parameters added to the link, as in the case of papers where the total displayed is not the total for all literature items, but constrained to literatureType=journal and relevance=GBIF_USED and peerReview=true

**Comment by timrobertson100** [comment]
Thanks, Nicky
This is an open issue https://github.com/gbif/registry/issues/237

**Comment by nickynicolson** [comment]
Thanks Tim, I didn't mean "publishing orgs" had anything to do with literature, just used the link btw home page count & search results in the case of peer reviewed papers as an example of a parameterised search, rather than a simple entity count.

**Comment by timrobertson100** [comment]
Thanks, @nickynicolson - sorry, I wrote that just to be clear for anyone stumbling on this as sometimes causes confusion.

The bug should be fixed soon, but there will still be a difference as you click through due to the "having datasets" criteria

**Comment by timrobertson100** [comment]
Closing this as the bug is fixed, and it is indeed the intention that the homepage and click through are not the same. Please comment if this should be reconsidered, and I can take it back to those who made the original decision.
