### ISSUE TITLE
Add unofficial RU translation of MoU

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3145]
**Add unofficial RU translation of MoU**

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/d6b868fbb61fc2cd56afb76c05c699bb:bfe66cb2c46415558003de0b3c21fd65b17680df871077e1a505edd6780cef5f917117dc323608b7bec1188603ff9b37def38e4f7dc9909753ca90ff601ea504)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/document/80661/gbif-memorandum-of-understanding
Window size: width 1862 - height 926
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-10T19:42:35.758Z',mode:absolute,to:'2020-12-10T19:48:35.758Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-10T19:42:35.758Z',mode:absolute,to:'2020-12-10T19:48:35.758Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
[MoU_Russian.pdf](https://github.com/gbif/portal-feedback/files/5675266/MoU_Russian.pdf)
[MoU_Russian.docx](https://github.com/gbif/portal-feedback/files/5675267/MoU_Russian.docx)

**Comment by dnoesgaard** [comment]
I'm not sure if this has been done already, since it was closed?

**Comment by dschigel** [comment]
Yes, it was completed very fast by @kcopas, but not yet added to available translations to https://www.gbif.org/document/80661/gbif-memorandum-of-understanding, which would be great to do

**Comment by kcopas** [comment]
It’s not going up as a PDF—all versions will move to digital-first format early this year.
