### ISSUE TITLE
How I can select the dataset about a specific place? for example, Spain, or Granada or Sierra Nevada

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3146]
**How I can select the dataset about a specific place? for example, Spain, or Granada or Sierra Nevada**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/57272905115c08336bdb8e08578300bf:9c4dc2303e6342c7ef871d957d6a9ae6444782f5add2d9ef67e3244b4dd9a518363cd9b2003fcb5968a69e5eb468c743fc5487e9ba60f77654122b504c281087)
System: IE 11.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/user/profile
Window size: width 1920 - height 932
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-11T06:08:07.667Z',mode:absolute,to:'2020-12-11T06:14:07.667Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-11T06:08:07.667Z',mode:absolute,to:'2020-12-11T06:14:07.667Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
