### ISSUE TITLE
We need to delete the dataset "Fedosov V, Pisarenko O (2020). Checklist of mosses of the river Yarap upper reaches. Version 1.3. Central Siberian Botanical Garden SB RAS. Occurrence dataset https://doi.org/10.15468/mwwgeh accessed via GBIF.org on 2020-12-11." because the checklist was published as occurrences. We need add taxon ID for 290 mosses species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3147]
**We need to delete the dataset &quot;Fedosov V, Pisarenko O (2020). Checklist of mosses of the river Yarap upper reaches. Version 1.3. Central Siberian Botanical Garden SB RAS. Occurrence dataset `https://doi.org/10.15468/mwwgeh` accessed via GBIF.org on 2020-12-11.&quot; because the checklist was published as occurrences. We need add taxon ID for 290 mosses species**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e539e5f71c247fd034ef74162ab29c14:b8306c8d69bc61903e3a182050a7ad167c76b938eb83da0f6cddbf2661a4f547453fdc240be5c7b632c85d30f42195ee6fe8406e0e5d6b4694389d61bd871014)
System: Yandex Browser 20.11.2 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/87365979-f7fb-4909-a7e5-d3392692979c
Window size: width 1093 - height 786
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-11T06:57:47.631Z',mode:absolute,to:'2020-12-11T07:03:47.631Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-11T06:57:47.631Z',mode:absolute,to:'2020-12-11T07:03:47.631Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It seems like the dataset mentioned has already been deleted. I will close the issue.
