### ISSUE TITLE
Genus name is mistaken, is should be Herrera

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3148]
**Genus name is mistaken, is should be Herrera**

Genus name is mistaken, is should be Herrera according to the publication mentioned: The cicadas (Hemiptera: Cicadidae) of Panama including the description of six new species, three new combinations, one new  (Sanborn 2018)
https://doi.org/10.11646/zootaxa.4493.1.1

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bf53bb8c295b2d5acdc70ed1c613dcd6:4ce8691ec68b33bde673260d442007205fa46214d185f96890e06982b299544ff37c3c3d100741ed492acfc8923a5faaf34271d233ab3b77b7a22186739616d3)
System: Firefox 83.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/10257631
Window size: width 1366 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-11T17:00:18.430Z',mode:absolute,to:'2020-12-11T17:06:18.430Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-11T17:00:18.430Z',mode:absolute,to:'2020-12-11T17:06:18.430Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This comes from a PLAZI treatment: https://www.gbif.org/dataset/ac55c1cd-0227-47c0-a130-15d18759b313
Tagging their UUID so they can find the issue: 7ce8aef0-9e92-11dc-8738-b8a03c50a862

**Comment by truschel** [comment]
The problem was solved.
Thank you for showing us this problem!

**Comment by ManonGros** [comment]
Great! I am keeping the issue open as it is now concerning the GBIF Backbone.

**Comment by ManonGros** [comment]
error corrected in the new backbone: https://www.gbif.org/species/10928814
