### ISSUE TITLE
the genus name is the title is mistaken, shoul be Herrera

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3150]
**the genus name is the title is mistaken, shoul be Herrera**

the genus name is the title is mistaken, shoul be Herrera as in the description

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0ee93486e06b5ec3e538327e5ddf9f56:a94302ab70d2ecbb6bd124b83e725a60f55c3d7af04f92bc86164f28ce2f463c2cabdcafb81180b0a46565fbf8f804eef704cca139e7ef743447d58b9aa5fb60)
System: Firefox 83.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/10654137
Window size: width 1366 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-11T17:02:59.137Z',mode:absolute,to:'2020-12-11T17:08:59.137Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-11T17:02:59.137Z',mode:absolute,to:'2020-12-11T17:08:59.137Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This comes from a PLAZI treatment: https://www.gbif.org/dataset/ac55c1cd-0227-47c0-a130-15d18759b313
Tagging their UUID so they can find the issue: 7ce8aef0-9e92-11dc-8738-b8a03c50a862
(Same dataset concerned as this issue: https://github.com/gbif/portal-feedback/issues/3148)

**Comment by truschel** [comment]
The problem was solved.
Thank you for showing us this problem!

**Comment by ManonGros** [comment]
Great, thanks! @truschel I am keeping the issue open since it still needs to be integrated in the GBIF backbone.
