### ISSUE TITLE
Aoma is not in Pleocomidae

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3154]
**Aoma is not in Pleocomidae**

Acoma seems to be a genus in Scarabaeidae, not in Pleocomidae as https://www.gbif.org/species/6757652 would suggest

See:

https://bugguide.net/node/view/187163
https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=926491#null

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4244f3ef4f9e2ffebe2b0f3ff519d82b:347023afb04c94e0319c99068659d577216bfa2456b285c6b5db9abf321606a0e7373005a46dd99148448c0ce2bd74296ca7c3d7f7c2f9fd32cb03417487102c)
System: Chrome 87.0.4280 / Mac OS X 11.0.1
Referer: https://www.gbif.org/species/6757652
Window size: width 1280 - height 700
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-15T02:59:48.161Z',mode:absolute,to:'2020-12-15T03:05:48.161Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-15T02:59:48.161Z',mode:absolute,to:'2020-12-15T03:05:48.161Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
The latest COL has it in Melolonthidae inside the superfamily Scarabaeoidea: https://www.catalogueoflife.org/data/taxon/N4W
This originates from a recently added beetle source [World Scarabaeidae Database](https://www.catalogueoflife.org/data/dataset/1027) and we will follow their opinion.

BugGuide has Melolonthinae as the subfamily.
