### ISSUE TITLE
Lepisiota incisa and Brachymyrmex incisus aren't synonyms

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3155]
**Lepisiota incisa and Brachymyrmex incisus aren&#39;t synonyms**

This feedback comes from an email received on Helpdesk. One of our users believe that the error might have been made based on the species epithet and author.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/5662e0fad4304c74fa2bf0ffddf9d461:25cb4e6aa4c1ede4f48d70d833eaa8bc590409c93a106dcc1ff042a4183eacb9496e6509e285e5b156e1db955b093e5705d73575a60f3699d061f8b7ddc5f956)
System: Safari 14.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/1320929
Window size: width 1608 - height 832
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-16T08:14:23.448Z',mode:absolute,to:'2020-12-16T08:20:23.448Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-16T08:14:23.448Z',mode:absolute,to:'2020-12-16T08:20:23.448Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
Solved in the new backbone.
