### ISSUE TITLE
Change the wording on occurrence pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3156]
**Change the wording on occurrence pages**

Currently, it says "X occurrences downloaded", but the users still have to click on the "download" button to download these occurrences. This can be confusing.
One of our users suggested to write "Processing Complete and Ready for Download by the User" instead.
We could also have something like "X occurrences included in the download".
@dnoesgaard would it make sense? Any thought on the topic?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/536fa701909eb4a3c4abde74810de63c:c9ca9bdfda12910cd67ada04071d0d4a519efcfb82330a3cfb8452afb804e6049a4578b403b42d656a3aefe9feb9fc422731e6049714d468a0092e32584210b5)
System: Safari 14.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/0136267-200613084148143
Window size: width 1608 - height 832
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-16T09:49:11.763Z',mode:absolute,to:'2020-12-16T09:55:11.763Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-16T09:49:11.763Z',mode:absolute,to:'2020-12-16T09:55:11.763Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by dnoesgaard** [comment]
I agree with this, but I can't change it because Crowdin is giving me this ridiculous error message

<img width="733" alt="Screenshot 2021-01-13 at 08 51 25" src="https://user-images.githubusercontent.com/21358085/104422084-89bb6f00-557c-11eb-9c63-ce67af5a74fd.png">

I've seen this error a couple of times, but never figured out what is causing. Will try to reach out to Crowdin for help...

**Comment by MortenHofft** [comment]
@dnoesgaard  Would be nice to know the reason and be able to edit it in Crowdin, but else I can change it in the source.

**Comment by dnoesgaard** [comment]
I heard back from Crowdin and the reason *is* that the source uses SELECT while the translation uses PLURAL. As mentioned previously, I'd prefer to use PLURAL when dealing when pluralizations. If you could change this one, we can do the others at a later stage?

**Comment by MortenHofft** [comment]
@dnoesgaard  Can you please review that [this](https://github.com/gbif/portal16/commit/28ce053930c3fefc1de9f26742b6200224d619ab) is the changes that you would like?

**Comment by dnoesgaard** [comment]
It looks fine. I assume you've just replaced "select" with "plural"? One/1 is the same, afaik.

**Comment by MortenHofft** [comment]
> It looks fine. I assume you've just replaced "select" with "plural"? One/1 is the same, afaik.

I also changed `1` to `one` as that seemed to be your preference. But else: yes

**Comment by MortenHofft** [comment]
As a test, I've changed one value https://github.com/gbif/portal16/commit/a102fc81a77a5723f5f0798e46ba034827f5cc2d

**Comment by dnoesgaard** [comment]
Translation updated to read

![Screenshot 2021-01-15 at 14 02 44](https://user-images.githubusercontent.com/21358085/104730450-5aeaf780-573a-11eb-8fbf-4aa40d4e3539.png)
