### ISSUE TITLE
downloading coordinates

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3158]
**downloading coordinates**

I am using the database forthe first time, to extract coordinates of presence locations; I have downloaded a file, but the script is strange when imported into an excel file and  all infromation per row appears in one cell.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/abd8a0a71678f66373c4bf0f918b6c33:d68276a642f2bb38f6126ef468cd0c864e8f2d747ee065e7996f885d349ba7a9059d6b1b72eec270edf47a4d6d2516ee631a0e35d483092138cd29b22b1d553a)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/faq
Window size: width 1366 - height 600
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-16T17:51:20.261Z',mode:absolute,to:'2020-12-16T17:57:20.261Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-16T17:51:20.261Z',mode:absolute,to:'2020-12-16T17:57:20.261Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
Replied by email.
