### ISSUE TITLE
Wrong date for a species' description?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3159]
**Wrong date for a species&#39; description?**

Hi, I've been notified by an ornithology collection manager that the description date for this species' page (https://www.gbif.org/fr/species/2481882) is most likely wrong: the GBIF Backbone Taxonomy and several other checklists say 1905 but it should be 1805, given A. von Humboldt's date of death.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c874d132b16bb7b26a8eed73448b8c6d:a37d6e159634ba093f60c16d95f59c31fc3b38872d0f8a3bac5e590058dad40d726ef89775c3452c2fba2cb949c9d844038116f4aa05453d99c73c75d83cadda)
System: Firefox 83.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/fr/species/2481882
Window size: width 1198 - height 654
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-17T10:48:10.784Z',mode:absolute,to:'2020-12-17T10:54:10.784Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-17T10:48:10.784Z',mode:absolute,to:'2020-12-17T10:54:10.784Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by SophiePamerlon** [comment]
I'm checking on this issue to see if something can be done (in addition to trying to contact every checklist publisher that have the wrong date? :) )
Thank you!
Sophie

**Comment by MattBlissett** [comment]
I think GBIF has this from Catalogue of Life, and that has it from ITIS.

https://www.catalogueoflife.org/data/taxon/7KK6S

I think, if it were corrected in ITIS it would eventually make its way through to GBIF.  @mdoering, is that best?

**Comment by mdoering** [comment]
Thats correct. I've notified the COL editors via https://github.com/CatalogueOfLife/data/issues/227
