### ISSUE TITLE
EOD dataset for family Fringillidae contains Leistes meadowlarks

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3165]
**EOD dataset for family Fringillidae contains Leistes meadowlarks**

I downloaded an EOD dataset of familiy Fringillidae recently for a species diversity map project, and on my plotted map I noticed icterid meadowlarks in the genus Leistes showing up.

I checked the data and found about 37,000 observations (out of the total data set of 12.8MM+) for 4 different Leistes species:

Leistes bellicosus - 4967
Leistes defilippii - 82
Leistes loyca - 25810
Leistes superciliaris - 6947

This was easy enough to filter out of my map by cross-referencing with the eBird taxonomy and filtering out anything that didn't belong in Fringillidae, but I wanted to let the team know about the data error. Thanks!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4e8ba110509a1e1d1a0d533ef0561da3:ccc6c916396906467503e2fc6bd06510973ca1069b9d570569444bc839b847f03be1a45a493b1c5a39305b085b031773d7513f33c9cb24e16dbb7bde5ec5c524)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator
Window size: width 1536 - height 775
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-19T05:25:59.488Z',mode:absolute,to:'2020-12-19T05:31:59.488Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-19T05:25:59.488Z',mode:absolute,to:'2020-12-19T05:31:59.488Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
After checking, it seems that this issue was originally a backbone taxonomy one.
The previous backbone has the genus Leistes Vigors, 1825 as well as the species mentioned above in the family Fringillidae.
However, this is no longer the case. The newest backbone seem to have https://www.gbif.org/species/4846742 in the correct family.
