### ISSUE TITLE
not this species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3167]
**not this species**

The correct species ID is:

https://www.gbif.org/species/5178351

Greetings
Andreas

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4dc6557a8b3aec4a93c502a5d659649f:f80f36c27b2e541ee74e0d6f46af38a2287735b75fff768c10b137aee985fe85884a632b922a1b8ddcdf68c8fc8012b94b7e592c03992bac7bf1486cb51510f9)
System: Opera 73.0.3856 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1436916155
Window size: width 1992 - height 972
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-22T08:21:28.267Z',mode:absolute,to:'2020-12-22T08:27:28.267Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-22T08:21:28.267Z',mode:absolute,to:'2020-12-22T08:27:28.267Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 8138eb72-f762-11e1-a439-00145eb45e9a
publishingOrgKey: e88c96a3-5884-4e51-a580-e417ca4c9eed

**Comment by ManonGros** [comment]
@aallspac, it looks like the record has been deleted. I will close the issue now.
