### ISSUE TITLE
Feedback can be provided twice by double clicking fast

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#317]
**Maps controls are not usable on mobile**

Pinch zoom etc quickly just get into a bad state, or a double-tap on the map. Iphone safari and firefox on &#39;droid

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
Reported by: @Timrobertson100
System: Mobile Safari 10.0.0 / iOS 10.3.3
Referer: https://www.gbif-uat.org/
Window size: width 375 - height 628
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T11:23:16.266Z',mode:absolute,to:'2017-08-15T11:29:16.266Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T11:23:16.266Z',mode:absolute,to:'2017-08-15T11:29:16.266Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
and this is such an example
