### ISSUE TITLE
family placed in wrong taxonomic tree

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3170]
**family placed in wrong taxonomic tree**

The Mollusc family Personidae has an overall wrong match with an Arthropod order. Please correct!

-----

Github user: @slieker
User: [See in registry](https://www.gbif.org/api/feedback/user/15ffdbd1feb1493d2f5086fab3618361:f4bc0bd73bf672c134042acc97de60a10e82d2674f42ecbdf7fd1a4eb26e2e0bcbc250c69f702ac4f94d6c2db04ae6f256db1932f22b6b7d4424906a47382954)
System: Firefox 84.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?taxon_key=7070
Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-31T05:22:26.300Z',mode:absolute,to:'2020-12-31T05:28:26.300Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-12-31T05:22:26.300Z',mode:absolute,to:'2020-12-31T05:28:26.300Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by TonyRees** [comment]
@mdoering : Personidae in GBIF is here, misclassified as Insecta:
https://www.gbif.org/species/7070

There is an invalid family level homonym in Insecta, but the correct classification (for most of the contained genera) should be Mollusca, as per these IRMNG records:

 Personidae Gray, 1854 · Animalia (Kingdom) > Mollusca (Phylum) > Gastropoda (Class) > Littorinimorpha (Order) > Personidae (Family)  https://www.irmng.org/aphia.php?p=taxdetails&id=106977

 Personidae Novokshonov, 1995 † accepted as · Animalia (Kingdom) > Arthropoda (Phylum) > Insecta (Class) > Insecta incertae sedis (Order) > Personidae (Family)  https://www.irmng.org/aphia.php?p=taxdetails&id=11916617

In IRMNG, the only genus to be allocated to the instance in Insecta is Persona Novokshonov, 1995 † (junior homonym), all others are Mollusca.

In case this helps - Tony

**Comment by slieker** [comment]
Hi Tony,
Thanks for your explanation, but is GBIF going to correct this as they keep interpreting it wrongly?

Regards
Frans

 
François J.A. Slieker BSc. - Honorary Head Curator Invertebrates
Natural History Museum Rotterdam

**Comment by mdoering** [comment]
I will make sure GBIF has this right in our next backbone due in ~2 weeks

**Comment by mdoering** [comment]
@yroskov COL actually has both families accepted: https://www.catalogueoflife.org/data/search?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0&q=Personidae&sortBy=taxonomic

The insect family has a single fossil species included with a great name, [Persona incognita](https://www.catalogueoflife.org/data/taxon/6V7CC)

**Comment by yroskov** [comment]
CoL: I just can confirm that both families exist in source datasets:
http://grylloblattodea.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1221748
https://www.molluscabase.org/aphia.php?p=taxdetails&id=23090

I have changed status of †Personidae Novokshonov, 1995 from  Grylloblattodea Species File to "provisionally accepted" in CoL.

Synced on 2021-02-19.
