### ISSUE TITLE
The correct name is Leptomantella (Aetaella) bakeri Hebard, 1920 ; OR Aetaella bakeri Hebard, 1920

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3175]
**The correct name is Leptomantella (Aetaella) bakeri Hebard, 1920 ; OR Aetaella bakeri Hebard, 1920**

bakeri is the type species of Aetaella Hebard, 1920.  It has been treated as a sub genus by Giglio-Tos (1927), and Beier (1935) and recently suggested as a valid genus Schwartz & Konopik (2014: 138)

Ref:  Schwartz & Konopik (2014) An annotated checklist of the praying mantises (Mantodea) of Borneo, including the results of the 2008 scientific expedition to Lanjak Entimau Wildlife Sanctuary, Sarawak.  Zootaxa, 3797 (1): 130-168.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4445e605a4db9fba6886e7f8653ef097:bac0590d717d3914a450bc12afc2dedc589a68ddc50fd763b9070becd6327a9ca25c315f0cdd1c1c20eb28924d1717da31039f3d5f162d7bf35e156ddbf9c52b)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/species/1404480
Window size: width 1366 - height 625
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-04T16:36:48.213Z',mode:absolute,to:'2021-01-04T16:42:48.213Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-04T16:36:48.213Z',mode:absolute,to:'2021-01-04T16:42:48.213Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It looks like the name has been updated in the CoL: https://www.catalogueoflife.org/data/taxon/3TQXY
So I would expect it to be correct in the next backbone update.
