### ISSUE TITLE
Indonesian butterfly record showing in the Atlantic

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3177]
**Indonesian butterfly record showing in the Atlantic**

The lat and long values are identical - looks like the latitude may be correct and is wrongly repeated as longitude value. Country code is missing.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0e47fa9db4a627a3837a40961fe65528:b084b1bffa8b78ee1b8967707a371d475548c671fba1b4d7d72e23d1965e90de647a365564ea13211051ebd49203fe7807b51499409ee6ce39a9c3dd4b44568f)
System: Chrome 87.0.4280 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/3007906078
Window size: width 3013 - height 1361
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-05T10:14:01.548Z',mode:absolute,to:'2021-01-05T10:20:01.548Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-05T10:14:01.548Z',mode:absolute,to:'2021-01-05T10:20:01.548Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 442647f8-8883-462d-901f-115f0753969d
publishingOrgKey: 07acecfd-5994-47a7-bd1b-ccdbf534973b

**Comment by jhnwllr** [comment]
Probably in this case the lat-lon are simply repeated. Could be a default value candidate? @ahahn-gbif

**Comment by ahahn-gbif** [comment]
A default value for the country would cause this record to be flagged as erroneous. If the dataset is (and always will be) covering Indonesia, this would be a viable fix to inform data users. The even better fix would be to curate those data at source, and also request to add the country code.

**Comment by ManonGros** [comment]
The country code is inferred from the country provided. I don't think a default value would fix it @jhnwllr. We need to contact the publishers.

**Comment by jhnwllr** [comment]
written to dataset publisher regarding the issue.

**Comment by ManonGros** [comment]
The issue has been fixed.
