### ISSUE TITLE
Royal Dutch Angling Association

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3178]
**Royal Dutch Angling Association**

Dear GBIF,

A few things are in need of updating on the following page about the Royal Dutch Angling Association (Sportvisserij Nederland): https://www.gbif.org/publisher/224c2985-c87e-4330-bc0d-da0c8067fac4

The administrative contact is no longer Jaap Quak. Could you change that to me as both technical and administrative contact (Remko Verspui)?
The link-text to the website of the Royal Dutch Angling Association contains http:// in stead of https://, not a big deal, but if you could update that to I would appreciate it.

Cheers, 

Remko Verspui
Royal Dutch Angling Association / Sportvisserij Nederland

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2ddf9e520bb7d3afb5cd50cddc6e7b1d:130b35867f42024971a3c6009fb7c6976566a9b084bc5dd1f9a2af1659e6229559a329de1431ad21e5a5c148b91d6ae0856d4a6b50022a99854a7bdfc98302d3)
System: Chrome 87.0.4280 / Windows 7.0.0
Referer: https://www.gbif.org/publisher/224c2985-c87e-4330-bc0d-da0c8067fac4
Window size: width 1745 - height 809
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-05T11:32:03.591Z',mode:absolute,to:'2021-01-05T11:38:03.591Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-05T11:32:03.591Z',mode:absolute,to:'2021-01-05T11:38:03.591Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Done.
