### ISSUE TITLE
Elevation is incorrect. Original elevation written on specien is 19000 ft, which is 5790m.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3181]
**Elevation is incorrect. Original elevation written on specien is 19000 ft, which is 5790m.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ffcf4ef8bbcf0f5d9f6f14ec1c59245a:8bc186e74432a13de92566e9df6ab5b2b9d09d9799792ab0c542e412e18bd0bd21ecf74c8eb9afa5f5924e701b8a38b8d626e03a990ee3da4ff1931c4f5a7b93)
System: Firefox 84.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1098999249
Window size: width 1920 - height 977
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-06T10:19:27.248Z',mode:absolute,to:'2021-01-06T10:25:27.248Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-06T10:19:27.248Z',mode:absolute,to:'2021-01-06T10:25:27.248Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 85714c48-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 57254bd0-8256-11d8-b7ed-b8a03c50a862

**Comment by MortenHofft** [comment]
The elevation as it is published to us is in meters. The herbarium sheet however says 19000

**Comment by jhnwllr** [comment]
data was fixed at source
