### ISSUE TITLE
How to do an Occurrence search for all Aves EXCEPT for Passeriformes

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3184]
**How to do an Occurrence search for all Aves EXCEPT for Passeriformes**

I want to create a occurrence search for all Aves EXCEPT for Passeriformes. Is this possible using the search tools? I couldn't figure out how to do so. 

I also tried to figure out how to use REST, but can't figure out the syntax. If I use taxon_key=212&taxon_key!=729 the not equal to sign turns to an equal sign. 

How do I do this?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2c4d134b79a2673db5bb591874bb563a:7f4b25b902ef64dd57a6544d132c39857a0a8b7c4950b6219831c8b431eb931225c965bf8cdccba5834a60cb107054f6c934067be8935f3e3b83ef0e83400af2)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?country=US&has_coordinate=true&has_geospatial_issue=false&taxon_key=729&year=1900,2021&coordinate_uncertainty_in_meters=0,1000&occurrence_status=present
Window size: width 1536 - height 698
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-06T23:57:48.219Z',mode:absolute,to:'2021-01-07T00:03:48.219Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-06T23:57:48.219Z',mode:absolute,to:'2021-01-07T00:03:48.219Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
answered via email: 

Currently there is not a very clean way of doing this query with the web interface. Below I paste a query of all bird orders that are not Passeriformes. 

https://www.gbif.org/occurrence/map?taxon_key=716&taxon_key=721&taxon_key=723&taxon_key=724&taxon_key=725&taxon_key=726&taxon_key=839&taxon_key=1108&taxon_key=1444&taxon_key=1445&taxon_key=1446&taxon_key=1447&taxon_key=1448&taxon_key=1449&taxon_key=1450&taxon_key=1492&taxon_key=1493&taxon_key=7190953&taxon_key=7190978&taxon_key=7190987&taxon_key=7191147&taxon_key=7191407&taxon_key=7191426&taxon_key=7191588&taxon_key=7192402&taxon_key=7192749&taxon_key=7192754&taxon_key=7192755&taxon_key=7192775&taxon_key=8454030&taxon_key=8454707&taxon_key=8481794&taxon_key=8510645&taxon_key=8602104&taxon_key=8603836&taxon_key=8617753&taxon_key=8705315&taxon_key=8706725&taxon_key=8708973

This can be done however using the Downloads API, but requires using Curl. 

I made a download of all Aves but not Passeriformes: 
https://www.gbif.org/occurrence/download/0150411-200613084148143

request.json file

```json
{
  "creator":"jwaller",
  "notificationAddresses": ["jwaller@gbif.org"],
  "predicate":
  {
    "type":"and",
    "predicates":     [
      {"type":"equals","key":"TAXON_KEY","value":"212"},
      {"type": "not", "predicate": {"type": "equals", "key": "TAXON_KEY", "value": "279"}}
    ]
  }
}
``` 

Run this on the command line (replace username and password). 

```shell 
curl --include --user jwaller:yourPassword --header "Content-Type: application/json" --data @request.json https://api.gbif.org/v1/occurrence/download/request
```
