### ISSUE TITLE
Location is wrong.  The included picture shows another location.  It is somewhere around here: https://www.google.ca/maps/place/Fawn+River/@53.8821322,-90.148043,9z/data=!4m5!3m4!1s0x4d7dd9789779c4d1:0xb4c60cf5e32a22cb!8m2!3d54.0033299!4d-89.4329874.  There is another observation with the same error.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3186]
**Location is wrong. The included picture shows another location. It is somewhere around here: `https://www.google.ca/maps/place/Fawn+River/@53.8821322,-90.148043,9z/data=!4m5!3m4!1s0x4d7dd9789779c4d1:0xb4c60cf5e32a22cb!8m2!3d54.0033299!4d-89.4329874.` There is another observation with the same error.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f76b20383044db8b984a8a1cfb61841c:ec1bec5aeddfaaea7e8d1e21e3f844d4b90b03489023b7a6eb3830d174c54668152cb2f3532d0ae4d87cb6c4931c84e2c43a0cf15eee3e56cfeefddd0de01c39)
System: Firefox 84.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2651321550
Window size: width 1067 - height 712
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-07T15:58:51.804Z',mode:absolute,to:'2021-01-07T16:04:51.804Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-07T15:58:51.804Z',mode:absolute,to:'2021-01-07T16:04:51.804Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: a36438d0-bec7-4b7b-9bfa-2c31e7610c39
publishingOrgKey: 927f1e70-cf74-11d8-bf68-b8a03c50a862

**Comment by jhnwllr** [comment]
responded via email: 

The record appears to have be georeferenced using the automated service GeoLocate. This is most likely the reason why it was given the wrong locality. Instead of ... 

"Fawn River between Big Trout Lake and Otter River" 

We will need to write to the publisher of the record and have them correct it at source in order for it to show a more accurate location.

**Comment by jhnwllr** [comment]
written to the publisher regarding the issue.

**Comment by jhnwllr** [comment]
The publisher says they have fixed it at source and the record will be updated on next ingestion into GBIF.
