### ISSUE TITLE
no puedo descargar una lista de registros de herbarios. cómo puedo hacer?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3189]
**no puedo descargar una lista de registros de herbarios. cómo puedo hacer?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b24bff7820696c52655e23efd0115c5f:7e0dce525a98ffb6bdd6f3518a2edd61bf852999df67446e8edc5f40f9785895793c555a1a95e4fa2e035a121b73bbbdee041c6f74064776144012a704150233)
System: Chrome 87.0.4280 / Windows 7.0.0
Referer: https://www.gbif.org/es/occurrence/search?offset=100&q=lippia%20turbinata&country=AR&has_coordinate=true&has_geospatial_issue=false&advanced=1
Window size: width 1360 - height 625
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-08T19:42:28.654Z',mode:absolute,to:'2021-01-08T19:48:28.654Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-08T19:42:28.654Z',mode:absolute,to:'2021-01-08T19:48:28.654Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Google translate

> I cannot download a list of herbal records. how can I do?

**Comment by ManonGros** [comment]
replied by email
