### ISSUE TITLE
Drymaeus meesi occurences in Trinidad & Tobago should be Drymaeus mossi

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3195]
**Drymaeus meesi occurences in Trinidad &amp; Tobago should be Drymaeus mossi**

All records of Drymaeus mossi in Trinidad, Trinidad & Tobago have been mistakenly interpreted as Drymaeus meesi by GBIF. The original sources are correct e.g. https://www.gbif.org/occurrence/1838839363

See also GBIF ID 2814444130; 2294650797; 1901026080; 1838839527; 1838839502; 1838839420; 1838839397.

D. mossi is an endemic of Trinidad whilst D. meesi is found in French Guiana and Suriname. 

Molluscabase accepts D. mossi as a species see http://www.molluscabase.org/aphia.php?p=taxdetails&id=1367970

Cheers,
Mike G. Rutherford

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8c10ef046536dabcc4f3900591719f5a:008c6232437b71c1f3ef315f2344d6941877cb1dc6fa6d8a9de10ab65d072709d070868a582225f5e1746d446e8016e05761bdb16e6fad4021ea5c407f7224b5aae49b7de4cb9ff55e05977142bc0cdb)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/data-quality-requirements
Window size: width 1536 - height 750
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-13T09:59:39.962Z',mode:absolute,to:'2021-01-13T10:05:39.962Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-13T09:59:39.962Z',mode:absolute,to:'2021-01-13T10:05:39.962Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mikegrutherford** [comment]
Hi, I raised the initial issue and would like to be kept up to date with progress

**Comment by ManonGros** [comment]
Hi @mikegrutherford
Drymaeus mossi (E.A.Smith, 1896) should be integrated in the next backbone taxonomy as it is available in the World Register of Marine Species checklist: https://www.gbif.org/species/160093795

For more information on how our taxonomy is generated, you can check this blogpost: https://data-blog.gbif.org/post/gbif-backbone-taxonomy/

**Comment by ManonGros** [comment]
It seems like the latest backbone update fixed this issue.
