### ISSUE TITLE
Geometry occurence API help

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3198]
**Geometry occurence API help**

I clicked on the Occurence Api page and one of the parameters is that we can use geometry.  I clicked on the example link: https://api.gbif.org/v1//occurrence/search?geometry=POLYGON((30.1%2010.1,%2040%2040,%2020%2040,%2010%2020,%2030.1%2010.1))  , but it's not working.  Can I get a working example?  Thank you.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ca8208afefd0708f9ca283bca203a18e:d5d2cfe072f55fbc5e8c134ecf0f94cc41b5788b1dc6bcfffe0aa68f4aa5bffdf373bbe6de177d62238c82dd9f7819e17fbda0b3eb14d265839b7de580568620)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1465 - height 698
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-13T23:31:13.649Z',mode:absolute,to:'2021-01-13T23:37:13.649Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-13T23:31:13.649Z',mode:absolute,to:'2021-01-13T23:37:13.649Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The link has a double `//`. That is a mistake and should be a single slash.
https://api.gbif.org/v1/occurrence/search?geometry=POLYGON((30.1%2010.1,%2040%2040,%2020%2040,%2010%2020,%2030.1%2010.1))
