### ISSUE TITLE
everything is broken (just kidding)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#32]
**everything is broken (just kidding)**

this issue needs to be copied/moved to another repo - how do we deal with that?

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
Reported by: @dnoesgaard
System: Chrome 55.0.2883 / Mac OS X 10.12.2
Referer: https://demo.gbif.org/
Window size: width 1440 - height 700
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-12T10:12:25.132Z',mode:absolute,to:'2017-01-12T10:18:25.132Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-12T10:12:25.132Z',mode:absolute,to:'2017-01-12T10:18:25.132Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
@MortenHofft just go ahead and close this :)
