### ISSUE TITLE
Scientific name correction not appearing after re-publishing the dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3200]
**Scientific name correction not appearing after re-publishing the dataset**

Hi,

The Berlie collection manager notified me that the scientific name for the occurrence https://www.gbif.org/occurrence/2876033515 should be fixed (Phalaropus fulacarius should be Phalaropus fulicarius), as it was flagged as 'Taxon match fuzzy' after the first ingestion.
I fixed it directly in the source data file and re-published the dataset but it looks like the typo is still there, as well as the 'taxon match fuzzy' flag. 

Thanks for your help!
With best regards,
Sophie

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/576e47fff3c67296ecdb2afd4174f8e7:3b73631a1c5786e02c4e885075dd5804d7706a89922d34471dafaeaf56d105364add72a360857f454d6c0a8e8cc9708d270e82ed433197ac5394050e60eaf0a5)
System: Firefox 84.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2876033515
Window size: width 1366 - height 626
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-14T14:06:38.187Z',mode:absolute,to:'2021-01-14T14:12:38.187Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-14T14:06:38.187Z',mode:absolute,to:'2021-01-14T14:12:38.187Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 1ea700b0-994c-4333-b487-e4e7d7f635cb
publishingOrgKey: 95e0556d-0271-4ded-a317-58b2236afc22

**Comment by MattBlissett** [comment]
Hi @SophiePamerlon,

The updated record is showing correctly now.

It will often take 10-20 minutes between publication of the dataset, and the updated records showing up on www.gbif.org.  Sometimes (if there are some large datasets being updated at the same time) it can take longer.

Thanks,

Matt

**Comment by SophiePamerlon** [comment]
Hi @MattBlissett 

Sorry about that, I saw the correct value appear on the occurrence page a few minutes ago!
Thanks for the explanation, I'll notify the collection manager right away 👍 

Best,
Sophie
