### ISSUE TITLE
Why are my dates not displayed on GBIF?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3201]
**Why are my dates not displayed on GBIF?**

I have consulted the Darwin Core guide, and I simply cannot figure out, why the dates from my sampling based dataset are not ingested correctly. Sorry to bother you, but I have really tried to figure it out my self. See e.g. https://www.gbif.org/occurrence/1587092452

-----

Github user: @DanBIF
User: [See in registry](https://www.gbif.org/api/feedback/user/696a23de5d5db18899b000455aaccc04:60a12d8428ab3ac5506a142d14fa0ecfd9c2d1a85472b1981f2146d17b4239b34e234ec175fa64eccba6d6b6c2d626f08d32baa3206c24e7782a532fc53995aa)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1587092452
Window size: width 1920 - height 1057
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-14T16:10:56.573Z',mode:absolute,to:'2021-01-14T16:16:56.573Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-14T16:10:56.573Z',mode:absolute,to:'2021-01-14T16:16:56.573Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 0528c11e-4074-43bb-829f-13b161bd0a56
publishingOrgKey: 2e7df380-8356-4533-bcb3-5459e23c794e

**Comment by muttcg** [comment]
Thank you, it is a bug, please follow https://github.com/gbif/pipelines/issues/458

**Comment by DanBIF** [comment]
Great, thanx, I’ll follow the subject ☺
/Isabel

Isabel Calabuig
M.Sc., Ph.D. biologist, Node manager, Data curator
Natural History Museum of Denmark
DIR +45 35321103 / MOB +45 22136624

**Comment by muttcg** [comment]
Fixed. It might take some time to update portal data(cache), but you can see that dataset **year** is 100%
There is another issue with how we display interpreted event date ranges, the API returns only the first date in range.
