### ISSUE TITLE
Quiero conocer el número de especies de Ruabiaceae de Veracruz, así como el número de especies de Randia en Veracruz

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3202]
**Quiero conocer el número de especies de Ruabiaceae de Veracruz, así como el número de especies de Randia en Veracruz**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2943fce6380facacbe87be2d9ec23c85:c3c8ed06de94eaa8bc040d8c8e227d1f5577b3d18f64fd15dd4880ed222e3d24d8a5d606ab0e439551f3e64fa246573377ee3656b81da6644f3573ee1357d96e)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/es/health
Window size: width 1366 - height 635
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-15T23:04:42.300Z',mode:absolute,to:'2021-01-15T23:10:42.300Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-15T23:04:42.300Z',mode:absolute,to:'2021-01-15T23:10:42.300Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Google translate
> I want to know the number of species of Ruabiaceae from Veracruz, as well as the number of species of Randia in Veracruz

**Comment by kcopas** [comment]
Filter GBIF occurrences by taxa and GADM administrative area:
https://www.gbif.org/occurrence/search?taxon_key=8798&taxon_key=2911655&gadm_gid=MEX.30_1

Download species list format…et voilà!

**Comment by ManonGros** [comment]
Forwarded answer to the user by email.
