### ISSUE TITLE
Broken image link https://www.gbif.org/sampling-event-data

### ISSUE THREAD

**Issue by ckotwn** [gbif/portal-feedback#3203]
<img width="1501" alt="Screen Shot 2021-01-16 at 15 12 23" src="https://user-images.githubusercontent.com/637631/104805792-7f63d400-580d-11eb-9714-5531eecaaf8d.png">

The image "http://images.contentful.com/q553fnlofhvs/452cXXMlpCQW40YYc4qsKG/9c81b1f87f99cab1acc3f03835a87db6/image_0.jpg" doesn't seem to exist.

**Comment by dnoesgaard** [comment]
Fixed.
