### ISSUE TITLE
Dataset Content Query

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3205]
**Dataset Content Query**

I recently downloaded a species occurrence dataset for Limaria hians, specifically containing records from the United Kingdom of Great Britain and Northern Ireland. In the "issues" column of the dataset many of the records have "INSTITUTION_MATCH_NONE;COLLECTION_MATCH_NONE"," listed. What does this mean? 

Many thanks for you help,

Danielle

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2a1160983f494baf151e179569cf0214:41f00592f59758f890762fa4bd9cb61003b20341e17aedea2a9cf6c514e61b9e4aab76663dfebfb96750eeee5d59aa7d0d6326d00ffb465137af3834e1ca9900)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/tools/name-parser
Window size: width 1187 - height 593
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-18T10:47:00.660Z',mode:absolute,to:'2021-01-18T10:53:00.660Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-18T10:47:00.660Z',mode:absolute,to:'2021-01-18T10:53:00.660Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> Both of these flags are related to our efforts to link records to [our Registry of Scientific Collections (GrSciColl)](https://www.gbif.org/grscicoll). Records with these flags couldn’t be matched to any GrSciColl entry. In other words, the Institution and Collection codes (or identifiers) used for those records aren’t associated with any Institution or Collection in the registry. More information on our matching system [here](https://www.gbif.org/developer/registry#lookup).
 > Unless you are particularly interested in the institutional affiliation of these records, I suggest to ignore these flags. They are mainly aimed at our data providers.
