### ISSUE TITLE
Network name for KUBI resources

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3206]
**Network name for KUBI resources**

I am wondering how I can change the network name for all of the University of Kansas Biodiversity Institute (KUBI) resources?  The four vertebrate collections and vertebrate paleontology are indicating Vertnet Plus as the Network when our collections do not have any affiliation to Vertnet.  They are published directly to GBIF from our own IPT.  The other resources from KUBI do not have any indication of Network.  I would like to change all of them to "University of Kansas Biodiversity Institute (Specify Collections Consortium)".  If possible if we could link the Biodiversity institute to www.biodiversity.ku.edu and the Specify Collections Consortium to www.specifysoftware.org.

Thanks

Andy

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/648b5ee5d75f217f055f27ce70cfc60b:eb6af6e07245b6efd261ef4df0a61c1dfc55dd09e742ba0fca38e47b9d8d6c6778d88587b36fafb4c4f787395e030afc7a772180e121b063f1b8f45a56c48245)
System: Chrome 87.0.4280 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/5b0cfab4-9145-4fe2-89e3-fcbc294aa5b2
Window size: width 1600 - height 851
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-18T20:03:21.825Z',mode:absolute,to:'2021-01-18T20:09:21.825Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-18T20:03:21.825Z',mode:absolute,to:'2021-01-18T20:09:21.825Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
(this conversation continued via helpdesk@gbif.org)
