### ISSUE TITLE
Missing page in contentful

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#321]
**Missing page in contentful**

/tools/observation-trends/about is a 404. This was intended as a page where the user could read more about the trends tool.

-----
fbitem-fc7f4c7519dd3a1290c2cab68063b8e717d003b0
Reported by: @mortenhofft
System: Chrome 60.0.3112 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/tools/observation-trends/about
Window size: width 1918 - height 1007
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T15:21:41.161Z',mode:absolute,to:'2017-08-15T15:27:41.161Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T15:21:41.161Z',mode:absolute,to:'2017-08-15T15:27:41.161Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Um, there was a page there at some point. I had nothing to do with writing it, though. 
Ring a bell, @timrobertson100 ?

**Comment by timrobertson100** [comment]
I have supplied the info by email
