### ISSUE TITLE
is GBIF willing to publish the Leipzig Catalogue of Vascular Plants as a GBIF checklist dataset?

### ISSUE THREAD

**Issue by abubelinha** [gbif/portal-feedback#3210]
Are there any GBIF plans of publishing the _[Leipzig Catalogue of Vasculare Plants](https://www.biorxiv.org/content/10.1101/2020.05.08.077149v1)_ (github [LCVP](https://github.com/idiv-biodiversity/LCVP)) as a _[Darwincore checklist dataset](https://www.gbif.org/dataset-classes#checklists)_?

I think it was published with an open license months ago, but surprisingly I couldn't find this dataset it in the [GBIF checklists catalogue](https://www.gbif.org/dataset/search?type=CHECKLIST), where one can find IPNI, TPL, WCVP and many more.

I wonder if publishing such LCVP version is something which has to be [done by the LCVP authors](https://github.com/idiv-biodiversity/LCVP/issues/2), or anyone else could do it (being or not GBIF staff) just by citing the original sources and authors.

**Comment by ManonGros** [comment]
@abubelinha the The Leipzig catalogue of vascular plants is now a checklist on GBIF: https://doi.org/10.15468/9qxmn3
