### ISSUE TITLE
Incorrect display in the number of records for the advanced filter DWCA extension

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#3212]
First I would like to say that this option for the filter is really useful, thank you for all your hard work ❤️. 

When I select the option for DWCA extension, it displays 0 records for Loan in the filter, but when I applied the filter it shows 782 results.
![image](https://user-images.githubusercontent.com/63795703/105271792-24601300-5b66-11eb-8f73-1c0fdcea7415.png)
I do not know if this is a problem or maybe is because is a small number compared to the other extensions.

Additionally I have another small question about this filter, I should like to know if the extensions with 0 results (Cloning, ChronometricAge, GelImage) is because these extensions has never been indexed in GBIF or is something related with the functioning of the filter?
![image](https://user-images.githubusercontent.com/63795703/105271723-04c8ea80-5b66-11eb-89c2-0974bd0945fb.png)

Thanks in advance for your answer,
Esteban SiB Colombia @RicardoOrtizG @camiplata @SiBColombia

**Comment by muttcg** [comment]
Thanks a lot!
1) It is a bug, looks like we display only the top 10 results. @MortenHofft  
2) Filter result is correct, there is no record with **http://data.ggbn.org/schemas/ggbn/terms/Cloning** extension
