### ISSUE TITLE
No se ve la taxonomía

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3218]
**No se ve la taxonomía**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bfe0872a06a99bdc4b5763d1879c7035:70d77ff85ce37a3200f03f20ae81f6ab182a9625fc798dbc6cd718438c19809d634ac7aefa4415131c35b78524eb2a02aced2fe9b524d79688d7033f84bf41ba)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/es/species/4906296
Window size: width 1366 - height 667
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-25T23:19:02.768Z',mode:absolute,to:'2021-01-25T23:25:02.768Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-25T23:19:02.768Z',mode:absolute,to:'2021-01-25T23:25:02.768Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
google translate
> Taxonomy not seen

**Comment by MortenHofft** [comment]
Testing in 4 browsers just now (though not the one mentioned on windows). But I'm unable to reproduce. Most likely a temporary API issue.
