### ISSUE TITLE
thumbnails broken

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#322]
**thumbnails broken**

after moving env config thumbnails is broken.
https://github.com/gbif/portal16/commit/900c901dd4230036eb8c364ec556c1dcf8badb80

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c
Reported by: @mortenhofft
System: Chrome 60.0.3112 / Mac OS X 10.11.6
Referer: https://www.gbif-uat.org/dataset/search?q=
Window size: width 1918 - height 1007
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T16:35:37.029Z',mode:absolute,to:'2017-08-15T16:41:37.029Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T16:35:37.029Z',mode:absolute,to:'2017-08-15T16:41:37.029Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/96d6dcfac32863101b6b0f13194b1d8694c0a71f
