### ISSUE TITLE
search by polygon

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3223]
**search by polygon**

It would be great if it were possible to search by kml (or other) polygon as the map is a little basic. This would help with searching for records within a reserve or property boundary.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8e8fc2c970a21637647d9f13cae00226:fed11c92cdc3e899cb95ca50ba641c8918d4b1702060707052873c6ccd26f9c98dfef4863f7fe9ba3db051675700465c5c7a604a8b739f5738a2dcb64d14db0b)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/map?advanced=1&occurrence_status=present
Window size: width 1920 - height 937
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-27T22:29:22.111Z',mode:absolute,to:'2021-01-27T22:35:22.111Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-27T22:29:22.111Z',mode:absolute,to:'2021-01-27T22:35:22.111Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
It is possible to search by GeoJSON, WKT, by lat/lon range and by drawing on the map.

<img width="863" alt="Screenshot 2021-01-28 at 12 22 06" src="https://user-images.githubusercontent.com/6759267/106131972-a1414d00-6163-11eb-954e-e5912e7f21d1.png">

If you need other formats, then you need to transform it to one of the above formats. Perhaps this works? https://mygeodata.cloud/converter/kml-to-geojson
