### ISSUE TITLE
Wrong correlation between accepted name and synonym

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3229]
**Wrong correlation between accepted name and synonym**

Hi !
There seems to be an issue regarding Craterellus undulatus (Pers.) Redeuilh (https://www.gbif.org/species/2554620). This is presented as a synonym of Pseudocraterellus undulatus (Pers.) Rauschert. According to the photos it is clearly a mistake.
This was pointed out by a user of Arter.dk, the Danish species portal, where wrong photos are shown because of mapping to GBIF (https://arter.dk/taxa/taxon/details/8a428cf8-f785-ea11-aa77-501ac539d1ea).

Best regards
Lars

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ea053ce081eb2a799bdc36c247fe790d:ea2c7b3b4de34f39fdccf9b714c566c027519d2a50882ed8bac5dca9d3159a7e30d6b7ba2d978ce5d6db8c5223d6e8e040c5810284592012882d8ae75d6019cf)
System: Firefox 85.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/5249610
Window size: width 1680 - height 919
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-29T13:56:05.293Z',mode:absolute,to:'2021-01-29T14:02:05.293Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-29T13:56:05.293Z',mode:absolute,to:'2021-01-29T14:02:05.293Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
GBIF occurrences for Pseudocraterellus undulatus largely come as 4 different names:
<img width="669" alt="Screenshot 2021-08-13 at 15 30 55" src="https://user-images.githubusercontent.com/327505/129364656-ec3b66f6-e465-4091-9c4e-93dc9981b6da.png">

These are 2 pairs with 2 epithets: undulatus & sinuosus

Are maybe all 4 distinct taxa?

**Comment by mdoering** [comment]
Looks like the GBIF synonym is used elsewhere too: https://svampe.databasen.org/en/taxon/60864
I would leave things as they are
