### ISSUE TITLE
How can i download all plant data in this database into a csv format?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3230]
**How can i download all plant data in this database into a csv format?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7dde31833d2f82d50e06b1e9aa072f67:9f6716f451b88e94be94191a4ff8a0c5b96ad9995fd89b60dfd20b85a723d86220d953377ab056a73df23b2d46d86108bb50e0b21958eee7b09942aedee07d2e)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/developer/registry
Window size: width 1680 - height 907
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-29T17:55:40.653Z',mode:absolute,to:'2021-01-29T18:01:40.653Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-29T17:55:40.653Z',mode:absolute,to:'2021-01-29T18:01:40.653Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
related to https://github.com/gbif/portal-feedback/issues/3236 (will answer in one email)
