### ISSUE TITLE
two spmns from near southmost TX mapped to up near the TX panhandle.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3232]
**two spmns from near southmost TX mapped to up near the TX panhandle.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/08b6327d967931c11e60133222589095:bcb65886a952402d2e0e5e579f6c4066ac688bcd8c803acedb0fa38a01c453642245d10ff195577e187fa2c8a2e7604c155bcdc3946810246967521ce26812ae)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?geometry=POLYGON((-103.2407218515873%2033.205078125,-101.9223624765873%2033.205078125,-101.9223624765873%2034.5234375,-103.2407218515873%2034.5234375,-103.2407218515873%2033.205078125))&has_coordinate=true&has_geospatial_issue=false&occurrence_status=present&taxon_key=1310047
Window size: width 1493 - height 718
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-31T21:52:21.399Z',mode:absolute,to:'2021-01-31T21:58:21.399Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-01-31T21:52:21.399Z',mode:absolute,to:'2021-01-31T21:58:21.399Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Contacted publishers by emails.

**Comment by ManonGros** [comment]
The publishers have updated the records.
