### ISSUE TITLE
Clarification of the text in "Introduction to sampling-event data"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3233]
**Clarification of the text in &quot;Introduction to sampling-event data&quot;**

In the last sentence of the 3rd paragraph "Changes in community structure other metrics enable a range of Essential Biodiversity Variables EBVs," is there an "and" missing between "structure" and "other"? Or maybe it needs rephrase to provide better clarity, please?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b35b3998f74f9c51b27b38947b7f626e:29cb14b894203043e70f68a7b7c3f7ade68670e5dc9f9ff867c4999ba5ad6ae9c45b386eee93df477ae49d9adff1dd62dabf8d48360112124dba1c20e56f8b21)
System: Firefox 84.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/sampling-event-data
Window size: width 1504 - height 1595
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-01T08:37:37.356Z',mode:absolute,to:'2021-02-01T08:43:37.356Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-01T08:37:37.356Z',mode:absolute,to:'2021-02-01T08:43:37.356Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Indeed missing a word. Added "and" to sentence.
