### ISSUE TITLE
Hello, I donwloaded a file from you. However, it keeps failing ot extract the folder. How can I extract the contents? The optimal goal is to convert it into a csv file, but it keeps getting an error code of 0x80004005. Thanks in advance!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3235]
**Hello, I donwloaded a file from you. However, it keeps failing ot extract the folder. How can I extract the contents? The optimal goal is to convert it into a csv file, but it keeps getting an error code of 0x80004005. Thanks in advance!**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/64c478a5fe8021d64cb8390b02b71fd4:630e66a0330d48b5d0e3a67d4f69bf1e235a32fb6b1b859c4229dec2acce1c4c8d1bf7b99d8de819f00de538db8b2d3b369243eec6ff943502236b509c98fb0d)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
Window size: width 924 - height 809
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-01T17:00:50.529Z',mode:absolute,to:'2021-02-01T17:06:50.529Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-01T17:00:50.529Z',mode:absolute,to:'2021-02-01T17:06:50.529Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
related to https://github.com/gbif/portal-feedback/issues/3236 (will answer in one email)
