### ISSUE TITLE
I am trying to download the data from all the plants species available in your database. How can i obtain this information in sections, so that i can open it up on excel? I want to convert it onto a csv file eventually. Can someone help me do this? Ive donwloaded the simple file option and cannot extract any data from it.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3236]
**I am trying to download the data from all the plants species available in your database. How can i obtain this information in sections, so that i can open it up on excel? I want to convert it onto a csv file eventually. Can someone help me do this? Ive donwloaded the simple file option and cannot extract any data from it.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/89d16c033ff0c0b68bfc446ef79442fd:087c09edcc34d33321988b2b10d25bccd8ba509e92594c21441bfb87a3ab6ca5fa41955f97be3b001b42e16786048083fb17b7fa3d5ba49b49b6d7c510c60985)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download?taxon_key=6&advanced=1&occurrence_status=present
Window size: width 1598 - height 809
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-01T17:14:48.745Z',mode:absolute,to:'2021-02-01T17:20:48.745Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-01T17:14:48.745Z',mode:absolute,to:'2021-02-01T17:20:48.745Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
