### ISSUE TITLE
No online tool

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3237]
**No online tool**

Behind the URL, just a redirect to a document. Retire?

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/669db79252e64b15a87462dc4d8e17fc:8280fdb82fc34956d7e5228df918a86537a3ca1001783d202433942a4138867e98cebc575d21e7dbd4883cd81b068149167abf3c2745708e18076389cbbe19b0)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/tool/81275/terms-used-in-bionomenclature-online-tool
Window size: width 1862 - height 926
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-01T21:16:15.445Z',mode:absolute,to:'2021-02-01T21:22:15.445Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-01T21:16:15.445Z',mode:absolute,to:'2021-02-01T21:22:15.445Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Resource archived.
