### ISSUE TITLE
Make a precise polygon

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3239]
**Make a precise polygon**

Hello,
I'd like to get all inaturalist occurances in a given area. The area is not listed as a place on the pulldown list. I need to draw a polygon. However, the Open Street Map layer on the menu doesn't show topographic lines or a scale bar, so I can't get very precise. It needs to follow the boundaries of the land unit.  Is it possible to search within a KML or similar layer created on another map? Or, toggle to get the OPen Stree Map layer that has the topographic lines?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/92d1c43d1a8ff2678e5ee7617680eca0:857c86f60353371274cc372a91edeb605d758dc19980c4baaad6d58f0e6f7b8b1aa97a5cbf3ab1446aadb7598ea31932031b460c710b0b7a04481318c9ec6c7f)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/map
Window size: width 963 - height 715
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-02T18:55:37.458Z',mode:absolute,to:'2021-02-02T19:01:37.458Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-02T18:55:37.458Z',mode:absolute,to:'2021-02-02T19:01:37.458Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Is is possible to search by GeoJSON or WKT or lat/lon ranges or by drawing

<img width="863" alt="Screenshot 2021-01-28 at 12 22 06" src="https://user-images.githubusercontent.com/6759267/106731949-6716f600-6610-11eb-8236-6ea0090611f2.png">

It is a good idea to add more base maps. Our challenge in that respect is that we use a projection that includes the poles unlike the standard Mercator that Google and most others use. But we can add more than what we currently show.

I've captured the suggestion here https://github.com/gbif/portal16/issues/1488

**Comment by MattBlissett** [comment]
It's also possible to use the Open Street Map API to extract a polygon, and (possibly simplifying it if needed) use that to query GBIF. 

An outline is shown here: https://github.com/gbif/portal16/issues/1077
