### ISSUE TITLE
Text correction in feedback box examples

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#324]
**Text correction in feedback box examples**

Love! your feedback system. Note, there&#39;s a small grammatical error in the &quot;Content&quot; part.
E. g. that species don&#39;t exist.
needs to be
E. g. that species doesn&#39;t exist.
(from Deb Paul via email)

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
Reported by: @ahahn-gbif
System: Firefox 54.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/
Window size: width 1099 - height 497
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-16T06:59:50.868Z',mode:absolute,to:'2017-08-16T07:05:50.868Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-16T06:59:50.868Z',mode:absolute,to:'2017-08-16T07:05:50.868Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
The current text was my attempt at being funny. Kyle C has rewritten it to proper english.
