### ISSUE TITLE
Does GBIF offer one license for pictures and another for record data?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3241]
**Does GBIF offer one license for pictures and another for record data?**

Hello.

When you are a portal and exchange records with GBIF: Does the entire record follow one CC-license or is it possible for a contributor to send data to GBIF with one license for pictures (for instance CC-NC) and another for the rest of the record data, such as location (for instance CC-BY)?

And if so, is it possible for a platform that receives data from GBIF to receive only record data but no pictures if the appropiate technical solution is build into the platform?

I am sorry if I could have read about this myself somewhere on gbif.org. if so, I was not able to find it and you are more than welcome to answer me by just sending a link :o)

Thank you so much in advance!

Best wishes
Jon

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ed6e8e5b8310d8c4a26e603eeb08c050:b9a1257570705f73fe6d05fd040cf97d3dd4eb82daa1a60326393f62e08a3e759773595ecf736540784f989bcfadabb458602f615e4475b248f317622cdb49d4)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=license
Window size: width 1676 - height 791
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-03T07:25:32.892Z',mode:absolute,to:'2021-02-03T07:31:32.892Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-03T07:25:32.892Z',mode:absolute,to:'2021-02-03T07:31:32.892Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> Yes occurrences and images can have different licenses. But our portal and API don’t offer a way to filter for images based on their license.

> Note that publishers provide links to images on GBIF, not the images themselves. For more information on how images are shared on GBIF, you can check this blogpost: https://data-blog.gbif.org/post/gbif-multimedia/
