### ISSUE TITLE
incorrect authors - should be Romanoff, 1885

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3243]
**incorrect authors - should be Romanoff, 1885**

This is a feedback message that we got on Helpdesk.
Romanoff, 1885 is the person who described Apocolotois smirnovi, not Romieux.

It seems like this name comes from the CoL: https://www.catalogueoflife.org/data/taxon/FQXQ (it is Apocolotois smirnovi Romieux, 1885).

However, the reference that the CoL uses: https://www.nhm.ac.uk/our-science/data/lepindex/detail/?taxonno=230333 (The Global Lepidoptera Names Index) now shows APOCOLOTOIS smirnovi Romanoff, 1885.

So I assume that this was updated in the Lepidoptera index but not in the CoL.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/0f7f06b7f31216b0fa18e28bf7053db1:e1a5524baf5ca8d0f396e2bc6e2948a1c60a06e5e30b05080a5d01205558fef79cdedc149209de7415d908a79848dd351901d31267e8d25b20d5c72e13612ed1)
System: Safari 14.0.2 / Mac OS X 10.15.6
Referer: https://www.gbif.org/species/173136281/verbatim
Window size: width 1415 - height 793
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-04T08:22:45.004Z',mode:absolute,to:'2021-02-04T08:28:45.004Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-04T08:22:45.004Z',mode:absolute,to:'2021-02-04T08:28:45.004Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi @yroskov, we got this feedback from one of our users.
It looks like the author for Apocolotois smirnovi might be incorrect and should be Romanoff, 1885: https://www.catalogueoflife.org/data/taxon/FQXQ
Would it be possible to check this entry? Thanks!

**Comment by yroskov** [comment]
Indeed, LepIndex says APOCOLOTOIS smirnovi Romanoff, 1885.

Corrected in CoL as Apocolotois smirnovi (Romanoff, 1885). Correction will appear in the next release.
