### ISSUE TITLE
Erroneous locations for Pterodroma hasitata in Amazonian Colombia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3244]
**Erroneous locations for Pterodroma hasitata in Amazonian Colombia**

DATAVES database lists 14 records of Pterodroma hasitata in inland, Amazonian Colombia. These locations are erroneous. I contacted the lead contact listed in the dataset (R Gaviria) who confirms not seeing this species at this location.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/69aae64313226ddad04586f327ea6ff8:e4cda5aba9a3e096c51bc26f97cb0d7fe3d734d3e6073dfd01406e0ef4c8cb3803641c67241e7c67bbdd84ae1cd1d6b68bbd22f923661e43720cfd9bc488605e)
System: Chrome 87.0.4280 / Windows 8.1.0.0
Referer: https://www.gbif.org/occurrence/map?basis_of_record=HUMAN_OBSERVATION&dataset_key=9850b85a-793f-429d-a437-2d5b46282acf&has_coordinate=true&has_geospatial_issue=false&taxon_key=2481477&advanced=1&occurrence_status=present
Window size: width 1600 - height 789
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-04T10:56:16.713Z',mode:absolute,to:'2021-02-04T11:02:16.713Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-04T10:56:16.713Z',mode:absolute,to:'2021-02-04T11:02:16.713Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Publishers contacted by email.

**Comment by camiplata** [comment]
This issue has been fixed at the original publication. We check with the authors of the national Birds Checklist and generalized the identification as the other DwC elements looked correct.
@sibcolombia

**Comment by ManonGros** [comment]
Wonderful! Thank you @camiplata!
