### ISSUE TITLE
Confusing timing on the Data Validator

### ISSUE THREAD

**Issue by ckotwn** [gbif/portal-feedback#3245]
I just have uploaded a DwC-A for validation, but after seemingly the completion of upload, the web page tells me it started an hour ago... but in fact it has just started.

<img width="1326" alt="Screen Shot 2021-02-04 at 22 18 39" src="https://user-images.githubusercontent.com/637631/106905640-70e74900-6737-11eb-9ed6-ac91d4e2183c.png">

**Comment by MattBlissett** [comment]
There's a bug in the portal, in the thing that converts the time into "an hour ago". It's not taking account of the timezone.

See also #1530 and #2288.

Maybe we should just show the timestamp and not try to be clever with "an hour ago", it is probably better for users when they resubmit a dataset for validation. ("Started an hour ago" "Started an hour ago" vs "Started: 2020-02-04 16:02", "Started: 2020-02-04 16:31")
