### ISSUE TITLE
NO PUEDO LEER LA TABLA TAXONOMICA NO SALE EN LA PANTALLA.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3246]
**NO PUEDO LEER LA TABLA TAXONOMICA NO SALE EN LA PANTALLA.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e661dbf4a8216dc8dffb8471cdc2f8c8:1702ed99a6631caa7f9ebc7b51c2e998883f379501ef7867a379a6b9e0afe38f4eb56a125589fdbc4aa6928fdae98125862e213236f6f334c2661d6829c499fb)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/species/1651891
Window size: width 1360 - height 625
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-04T23:12:35.146Z',mode:absolute,to:'2021-02-04T23:18:35.146Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-04T23:12:35.146Z',mode:absolute,to:'2021-02-04T23:18:35.146Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Google translate
> I CANNOT READ THE TAXONOMIC TABLE IT DOES NOT APPEAR ON THE SCREEN.

**Comment by MortenHofft** [comment]
Closing as this issue is old and lacks context. I do not see anything wrong, when looking at the page
