### ISSUE TITLE
Photography are Histeridae (may be an Onthophilus) and the name display is one of curculionidae scolytinae: Scolytus scolytus. There is a mistakes in classification tree

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3248]
**Photography are Histeridae (may be an Onthophilus) and the name display is one of curculionidae scolytinae: Scolytus scolytus. There is a mistakes in classification tree**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7545f22a2f1f680aa0bfc6bed5923a57:f41d0f6bff5be4f56e11448134699e9959e017c2ac08c349bb71202f4a2041f55f9b31beab55dc4feaff645d7ed1bc77f6b706457e2b3cc40408f7ad47a393db)
System: Firefox 85.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/1189355
Window size: width 1696 - height 798
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-05T14:27:15.642Z',mode:absolute,to:'2021-02-05T14:33:15.642Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-05T14:27:15.642Z',mode:absolute,to:'2021-02-05T14:33:15.642Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I don't think I understand exactly what the issue is here so I contacted the user to ask for some additional explanations.

**Comment by ManonGros** [comment]
I got a reply from the user. Apparently the issue seems to have been solved since the issue was logged.
