### ISSUE TITLE
Taxonomy tab broken

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#325]
**Taxonomy tab broken**

Taxonomy tab is not clickable:
custom.js?v=1502872394086:34 Error: Could not resolve &#39;datasetKeyTaxonomy&#39; from state &#39;datasetKey&#39;
    at Object.$.transitionTo (custom.js?v=1502872394086:32)
    at Object.$.go (custom.js?v=1502872394086:31)
    at custom.js?v=1502872394086:32
    at custom.js?v=1502872394086:35
    at o (custom.js?v=1502872394086:33)
    at custom.js?v=1502872394086:33

-----
fbitem-datasetbf3db7c9-5e5d-4fd0-bd5b-94539eaf9598
Reported by: @thomasstjerne
System: Firefox 55.0.0 / Mac OS X 10.12.0
Referer: https://www.gbif-uat.org/dataset/bf3db7c9-5e5d-4fd0-bd5b-94539eaf9598
Window size: width 1782 - height 905
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-16T09:40:19.904Z',mode:absolute,to:'2017-08-16T09:46:19.904Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-16T09:40:19.904Z',mode:absolute,to:'2017-08-16T09:46:19.904Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
see https://github.com/gbif/portal16/issues/420

**Comment by MortenHofft** [comment]
Now links to species search and opens the root element for selection https://github.com/gbif/portal16/commit/d811888a88badf79b013f5337a5dd6adb04b50a0
