### ISSUE TITLE
incorrect author name: the species should be Agistemus collyerae González-Rodriguez

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3251]
**incorrect author name: the species should be Agistemus collyerae González-Rodriguez**

This is a feedback message we received on helpdesk.

The name is correct in the PLAZI treatment: https://www.gbif.org/species/177209902 and in TAXREF: https://www.gbif.org/species/161644476 but not in the backbone taxonomy.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/1f4a09a452b0397316c3983f10738c89:49a7c1f0dbd621a0589370a7d0c93e0c1fb2bd43cc34575148668fd039f08d1b42b28faaf5bd940b191841dd3a50e78dac6c3ea8751ce15578f66dee98fc640d)
System: Safari 14.0.3 / Mac OS X 10.15.6
Referer: https://www.gbif.org/species/2128629
Window size: width 1248 - height 793
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-10T08:00:08.920Z',mode:absolute,to:'2021-02-10T08:06:08.920Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2021-02-10T08:00:08.920Z',mode:absolute,to:'2021-02-10T08:06:08.920Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It looks like this issue has been fixed.
