### ISSUE TITLE
Good afternoon, I am reaching out because I was trying to donwload all the planta data from north America, south America and Europe. However, when i download it on excel as a csv file, i keep getting the message "Microsoft is waiting for another application to complete OLE action". I have redownloaded the same files with different variations, but it is the same result. If it does load, nothing shows up and just says "ready" I have downloaded the other continents with plantae and had no issues. Please let me know how to solve this issue.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3255]
**Good afternoon, I am reaching out because I was trying to donwload all the planta data from north America, south America and Europe. However, when i download it on excel as a csv file, i keep getting the message &quot;Microsoft is waiting for another application to complete OLE action&quot;. I have redownloaded the same files with different variations, but it is the same result. If it does load, nothing shows up and just says &quot;ready&quot; I have downloaded the other continents with plantae and had no issues. Please let me know how to solve this issue.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/cb73330dc41a5b7697abf6d929b73105:7aa1bf32abb2dbd5c3c0f617fe3defb81ab4ceb0c4ba49ec48da326f3af07e11ffafc9a09963d459ba335bebadf1974c2caec75f04a402ba1ab9cf5086753804)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0189955-200613084148143
Window size: width 500 - height 809
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-12T17:53:31.444Z',to:'2021-02-12T17:59:31.444Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-12T17:53:31.444Z',to:'2021-02-12T17:59:31.444Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I believe the question was answered when I contacted them about this other message: https://github.com/gbif/portal-feedback/issues/3236
