### ISSUE TITLE
Locate records I downloaded - cannot find email with doi

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3256]
**Locate records I downloaded - cannot find email with doi**

Is there a place I could look up all my recent (January) downloads? I have lost one email that I need.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7446735c751b8c5cc381d2c308d423aa:7411bcc22c753f829a81ea84874fee4f10b2edfeea5cee72e44400be3caba64a0d6795adeb699180fdc10f9ff5eeaf22875a8389de31016905b16e97c7bd6717)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/health
Window size: width 1536 - height 750
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-12T23:50:45.209Z',to:'2021-02-12T23:56:45.209Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-12T23:50:45.209Z',to:'2021-02-12T23:56:45.209Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Log in to your profile and go to the downloads tab 😁

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ManonGros** [comment]
Notified user
