### ISSUE TITLE
Automate DarwinCore download of one family

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3258]
**Automate DarwinCore download of one family**

Dear,

Do you have somewhere a script that I can use to download on a timely basis the whole DarwinCode of one family I am intrested in for integration within my website syrphidae.com?

now I am downloading manually but would like to automate this.
https://www.gbif.org/occurrence/download?taxon_key=6920

Kind regards,
Bastiaan Wakkie

-----

Github user: @bwakkie
User: [See in registry](https://www.gbif.org/api/feedback/user/c2b79b34f78e9d24a6271f828664553f:90658a5e077c9784b80331ccc04138ad5994edacbd5c2d24e706b0ac4ff5ae825c392f8d2e423b1f67bd898b0c46adb447e723571e1c487ae34f37690ed28ef3)
System: Firefox 85.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/occurrence/download?taxon_key=6920
Window size: width 1280 - height 693
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-14T15:09:07.925Z',to:'2021-02-14T15:15:07.925Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-14T15:09:07.925Z',to:'2021-02-14T15:15:07.925Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi @bwakkie you could use our download API: https://www.gbif.org/developer/occurrence#download

Use the client that's best for you. Example using CURL:

```
curl --include --user userName:PASSWORD --header "Content-Type: application/json" --data '{"creator": "userName","notificationAddresses": ["userEmail@example.org"],"format": "DWCA","predicate": {"type": "equal","key": "TAXON_KEY","values": 6920}}' https://api.gbif.org/v1/occurrence/download/request
```

Is this what you needed?

**Comment by ManonGros** [comment]
@bwakkie I hope the answer above is what you needed. Please let me know if the issue should be reopened.

**Comment by bwakkie** [comment]
Yes, thank you!
