### ISSUE TITLE
Missing names in the GBIF backbone taxonomy, mollusca.

### ISSUE THREAD

**Issue by jlegind** [gbif/portal-feedback#3259]
Tsuyoshi Hosoya from NMNS Japan found the following names are lacking in the GBIF backbone taxonomy.

・Duplicaria latisulcata (Yokoyama, 1922)　
・Maculauger kokiy Pacaud & Lesport, 2020
・Melampus nuxcastanea Kuroda, 1949　

He asks to have these names included under Mollusca in Animalia,

**Comment by mdoering** [comment]
Melampus nuxeastaneus Kuroda, 1949 and Maculauger kokiy Pacaud & Lesport, 2020 are now included.
Duplicaria latisulcata is still not found in any source in GBIF: https://www.gbif.org/species/search?q=Duplicaria%20latisulcata&advanced=1

Not much we can do about that one. We do lack good sources for Molluscs
