### ISSUE TITLE
Event date as date-time

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3262]
**Event date as date-time**

event date loads in a date time format but the collection was carried out in an interval so it would be best to have date and time separated

-----

User: [See in registry](https://www.gbif-uat.org/api/feedback/user/528699d5881427bdc3711ea73aee163f:cd4f0eb6fe9b49ab2c9a7158fd05e7292e5d600d8e1ad683cb07a2808101506ec686cdae588f0b6ac8c35333aed703b50b43ffc8692d662eaf8b1a7f5e1cb7cd)
System: Firefox 85.0.0 / Windows 10.0.0
Referer: https://www.gbif-uat.org/occurrence/2916086285
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-15T14:35:09.525Z',to:'2021-02-15T14:41:09.525Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-15T14:35:09.525Z',to:'2021-02-15T14:41:09.525Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 6309f2b7-f4ba-469f-b083-95859c9e9df7
publishingOrgKey: 0a16da09-7719-40de-8d4f-56a15ed52fb6

**Comment by ManonGros** [comment]
If I understand correctly, the issue is that the interpretation adds a time `2018-06-08T00:00:00` even though the eventTime is also provided.
It would be better to have the date and time separated: `eventDate: 2018-06-08` and `eventTime: 14:17:00/14:43:00`.

**Comment by tucotuco** [comment]
Also, it is incorrect to add the time precision information to an ISO 8601 date that is given with day-level precision. I strongly urge that it be removed.

**Comment by MattBlissett** [comment]
The general issues with intervals in eventDate have been fixed. (The linked example is an old test on UAT.)
