### ISSUE TITLE
Synonymy Comptosia stria (Walker, 1849) = Villa fasciata (Meigen, 1804) is wrong.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3265]
**Synonymy Comptosia stria (Walker, 1849) = Villa fasciata (Meigen, 1804) is wrong.**

GBIF does currently list Villa fasciata (Meigen, 1804) (and its synonyms) as a synonym of Comptosia stria. 

This is an obvious mistake and the cause is also easy to stop. Someome or something mistook Anthrax fasciata Fabricius, 1805 (this is synonym of Comptosia stria) for Anthrax fasciata Meigen, 1804, the original name for Villa fasciata. 

The two species are also extremely dissimilar in appearance :) 

Cheers,
Jere K.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b996d0d1e964a04cb9bb4418891554a7:3d47e65f36e4b2817f4c409d7bef0eaeae713704147c92e9cc5563f10cc2e8fed506267fecac62b5407ee110f3b6a6e46729e9613bbc6ce767c1fc79743b9181)
System: Firefox 85.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/species/1668875
Window size: width 1916 - height 785
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-17T15:21:15.695Z',to:'2021-02-17T15:27:15.695Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-17T15:21:15.695Z',to:'2021-02-17T15:27:15.695Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by jhnwllr** [comment]
This appears to have been corrected.
