### ISSUE TITLE
Missing Species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3266]
**Missing Species**

Auplopus mellipes is a well documented US species.

https://bugguide.net/node/view/7640
https://www.biodiversitylibrary.org/page/7835203

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a7477a0c6fc5b0065e08a29a514ae486:ea8b6447aa5be0a216d339a5bdcd9b9de8169f884070a8fdbeb8064395303beddd1d7f16edfffc381653b119e2e1bb8f7ea27859d6d2fa3638910b7af96b7de5)
System: Firefox 85.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/species/4404428
Window size: width 1920 - height 904
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-18T02:10:17.973Z',to:'2021-02-18T02:16:17.973Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-18T02:10:17.973Z',to:'2021-02-18T02:16:17.973Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
Present in GBIF and COL

https://www.gbif.org/species/10898787
https://www.catalogueoflife.org/data/taxon/JT69
