### ISSUE TITLE
Data for biodiversity richness for terrestrial animals

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3270]
**Data for biodiversity richness for terrestrial animals**

I would like to access biodiversity richness data for terrestrial animals in protected areas, non-protected areas and indigenous protected areas and compare levels over a 5,10 and 20 year period
This is for a research project for my university degree
Any help/advice is appreciated
kind regards
Julio Bullen
julio.i.bullen@gmail.com

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0d7594cf8d51b5abcd5bfe8bbe63ba4e:e207c71765fe36a1e3fc37f6dab54477d9d44f61065e40f78aeead45f5953bf7f625b339b12e4438f802c9c1b2df2123117a50b4217713b3f808bc26963fa1b3)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1280 - height 610
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-19T22:10:50.515Z',to:'2021-02-19T22:16:50.515Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-19T22:10:50.515Z',to:'2021-02-19T22:16:50.515Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> We can’t generate exactly what you need. What we can offer you is to help you filter occurrences (https://www.gbif.org/occurrence/search?occurrence_status=present) based on your criteria.
Here are a few questions and suggestions:
> - When you write “terrestrial animals”, do you mean any non-marine animal? Or do you have something more specific in mind? If so, you will need to generate a specific list of species or taxonomic groups of interest.
> - You can filter occurrences by year on GBIF (for example, these are the organisms observed or collected after the start of 2021). I suggest to use that filter to select the periods you would like to study.
> - Anyone can access the protected area shapefile here: https://www.protectedplanet.net/en. These files can be turned into polygons to filter for data on GBIF. However, since you are interested in both protected and non-protected area, I suggest to download the data you need from GBIF and do the filtering locally.
