### ISSUE TITLE
P. filicornis = P. fuscipennis, not C. iridipennis!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3273]
**P. filicornis = P. fuscipennis, not C. iridipennis!**

Psilus filicornis is a synonym of P. fuscipennis such as Johnson 1992 states. Cinetus iridipennis is not associated with with taxon. 
There was probably a mixup because it also exists Cinetus fuscipennis, with is indeed a synonym of Cinetus iridipennis.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8c7de0e1cac300096ac50ca9d0957026:d8d11e1a31383be0cd10fdcf94c891989b16c59b1d26172ce3bce943e67fa0383c62e6e260bd39fba55d4f38b27d922e6030925de12372913c407a299b6cd91d)
System: Chrome 87.0.4280 / Windows 10.0.0
Referer: https://www.gbif.org/species/9890608
Window size: width 1366 - height 568
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-22T16:54:16.266Z',to:'2021-02-22T17:00:16.266Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-22T16:54:16.266Z',to:'2021-02-22T17:00:16.266Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It looks like iy is solved in the new backbone.
