### ISSUE TITLE
missing accepted names

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#3278]
in todays submitted plazi datasets, the accepted names part is missing. eg https://www.gbif.org/dataset/3ec27add-200f-4d9f-9fd3-a46ed282720a

or do we  just need to be a bit patient? Normally, it took more time for the occurrences to appear.
Thanks!

![image](https://user-images.githubusercontent.com/4609956/109157523-66d2cc00-7772-11eb-9cc2-c5c1f94c34ef.png)

**Comment by ManonGros** [comment]
Hi @myrmoteras this is because the indexing of taxa/checklists is currently paused: https://www.gbif.org/health
It should resume next week.
