### ISSUE TITLE
Karenia brevis not part of the GBIF backbone

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3279]
**Karenia brevis not part of the GBIF backbone**

I recently shared a dataset on a particular harmful algal bloom species in the Gulf of Mexico, Karenia brevis which has an LSID from WoRMS of urn:lsid:marinespecies.org:taxname:233015 but this is not finding a match in the GBIF backbone. How can we get this fixed?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ccdf04a6cc104bd917337994b88b27a1:3f3346eb6e0188b9ab5d26a0dbcbed7fb523859965bcc50504a7914e0b6e6c80dab14c633c7f897b0b14b0352c11801ab640410a9394028562cace3a02fbd73b)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?dataset_key=277b6f51-9e44-47f1-8d88-397ac0245d20
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-25T14:22:25.049Z',to:'2021-02-25T14:28:25.049Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-25T14:22:25.049Z',to:'2021-02-25T14:28:25.049Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by kcopas** [comment]
Thanks for submitting this, Abby. One suggestion I didn't have time to mention in the webinar chat yesterday was to include the higher-level taxa. That would at least allow resolution to something more than Incertis sedis while the question of the Kareniaceae gets sorted…

**Comment by ManonGros** [comment]
Hi @albenson-usgs
In order for to include a name in the GBIF backbone taxonomy, it needs to be published in a checklist that is integrated in the backbone.
I can see that [Karenia brevis is included in several checklists](https://www.gbif.org/species/search?q=Karenia%20brevis&origin=SOURCE&advanced=1) but none of them are used in the backbone taxonomy.

Would you consider publishing your own checklist?

**Comment by AbbyBenson** [comment]
Showing my ignorance here, but since WoRMS is part of the backbone taxonomy and the name is in WoRMS why is it not in the GBIF backbone? Because WoRMS hasn't published a checklist with it in it? So it seems like the disconnect is that WoRMS needs to publish a checklist with this species in it?

**Comment by ManonGros** [comment]
The [WoRMS checklist](https://www.gbif.org/dataset/2d59e5db-57ad-41ff-97d6-11f5fb264527) published on GBIF (integrated in the backbone) doesn't contain [Karenia brevis](https://www.gbif.org/species/search?q=Karenia&dataset_key=2d59e5db-57ad-41ff-97d6-11f5fb264527&origin=SOURCE&advanced=1).
If the species was in that checklist, it would automatically be integrated to the backbone.

I don't really know how the checklist is generated and why a species with a LSID would not be included. We need to check with WoRMS or EurOBIS.

**Comment by ManonGros** [comment]
So from what I understand, the [WoRMS record](http://www.marinespecies.org/aphia.php?p=taxdetails&id=233015#sources) comes from AlgaeBase:
> Guiry, M.D. & Guiry, G.M. (2021). AlgaeBase. World-wide electronic publication, National University of Ireland, Galway (taxonomic information republished from AlgaeBase with permission of M.D. Guiry). Karenia brevis (C.C.Davis) Gert Hansen & Moestrup, 2000. Accessed through: World Register of Marine Species at: http://www.marinespecies.org/aphia.php?p=taxdetails&id=233015 on 2021-03-05

And AlgaeBase is not open:
> Copyright notice: the information originating from AlgaeBase may not be downloaded or replicated by any means, without the written permission of the copyright owner (generally AlgaeBase). Fair usage of data in scientific publications is permitted.

**Comment by ManonGros** [comment]
Karenia brevis is now in the backbone https://www.gbif.org/species/5424511! Thanks to the integration of the UKSI checklist.
