### ISSUE TITLE
Multiple records linked to one image on a server

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3281]
**Multiple records linked to one image on a server**

Dear GBIF people,
The Natural History Museum Rotterdam is about to upload a set of >800.000 observations. Many of the observations were made at the same locality,  sometimes as much as 100.000. We are not very thrilled by the idea of uploading 100.000 pics, each of them individually linked to it's own record by catalogNumber/GUID. Would it be possible to put one image on our server and link all records involved to this particular image? Would the image subsequently be shown on each record, or would there just be the link? Please advise.
Kind regards
Frans

-----

Github user: @slieker
User: [See in registry](https://www.gbif.org/api/feedback/user/ffcf6bfc13d535d6755e66fe427788d1:5834a2acc3c3ab2a8da2ce1d6a5632dbe559138a1edfeca57dde9d7855be0c1d3965e15a82bb4aa63b0a19f02b90ef3a10b5f9e83a3a20eee8b0d193cefbb737)
System: Firefox 86.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?dataset_key=a307e4d7-1de2-4adc-95d5-a0a8d5f57236
Window size: width 1920 - height 938
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-01T13:18:20.209Z',to:'2021-03-01T13:24:20.209Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-01T13:18:20.209Z',to:'2021-03-01T13:24:20.209Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jeroencreuwels** [comment]
I have contacted Frans Slieker about this issue and it has been solved. This issue can be closed.
Jeroen Creuwels, datamanager NLBIF.

**Comment by ManonGros** [comment]
Thanks @jeroencreuwels
