### ISSUE TITLE
Triepeolus cressonii is showing up under Nomada cressonii

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3282]
**Triepeolus cressonii is showing up under Nomada cressonii**

https://www.gbif.org/species/1343369

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fa466094572f0f05f7ec5755be30e5b0:dcb387bebccc645bd5cd71c002929686b5393ea4cd542a6ac7f129e8f553cf6d11cb0201a8e838b9c81afb41390c207948f8e928b0ebba377f84d2203475ab72)
System: Firefox 86.0.0 / Mac OS X 10.13.0
Referer: https://www.gbif.org/species/1343369
Window size: width 1264 - height 675
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-01T16:23:14.784Z',to:'2021-03-01T16:29:14.784Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-01T16:23:14.784Z',to:'2021-03-01T16:29:14.784Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
User has been contacted.
Triepeolus cressonii is a homotypic synonym of Nomada cressonii.

**Comment by mdoering** [comment]
this is solved in the 2021-03-03 backbone about to go live:
https://www.gbif-uat.org/species/1341647
