### ISSUE TITLE
Add-on to GRSciColl FAQ

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3285]
**Add-on to GRSciColl FAQ**

BioCASE publishers have no way of providing the institution and collection IDs. So we should add something here.
Maybe something like:
"""
For publishers using the BioCASE protocol, please contact directly scientific-collections@gbif.org
"""

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/2ef0371a64865837354aae044d0841e9:caa6d8e05b96b94ec695c84aba3173f504e661755b7790d9a7aef8c8a57bc0a70c48c74b2144e9585cd80f52b548e88bf26fad4307fabb2582f5fcca5620d0b8)
System: Safari 14.0.3 / Mac OS X 10.15.6
Referer: https://www.gbif.org/faq?question=how-can-i-improve-the-matching-of-occurrence-records-with-grscicoll
Window size: width 1492 - height 794
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-02T08:44:41.961Z',to:'2021-03-02T08:50:41.961Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-02T08:44:41.961Z',to:'2021-03-02T08:50:41.961Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Added.
