### ISSUE TITLE
Possible incorrect synonym - Maxomys whiteheadi

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3289]
**Possible incorrect synonym - Maxomys whiteheadi**

Would it be possible to check if Maxomys whiteheadi Thomas, 1895 is indeed a synonym of Chrotomys whiteheadi Thomas, 1895?
According to one of our publishers, this seems suspicious.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/886e5cb28af9c6bee934d17299176c9e:ee8993f6af64d0f61cf4148839448a867f6fdc2d8167014f8b721c4da193d989b7f1950ca04c698aea0ce0f652226b1f85c72e6095fd7beeb981d4c1d88606fd)
System: Safari 14.0.3 / Mac OS X 10.15.6
Referer: https://www.gbif.org/species/2438838
Window size: width 1492 - height 794
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-02T17:19:33.818Z',to:'2021-03-02T17:25:33.818Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-02T17:19:33.818Z',to:'2021-03-02T17:25:33.818Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
They are no longer synonyms in the new backbone.
