### ISSUE TITLE
institution match none collection match none  GriSciColl

### ISSUE THREAD

**Issue by DimEvil** [gbif/portal-feedback#3296]
Almost all of our records are flagged with 'institution match none' and/or 'collection match none'
This is probably because the GriSciCol list is far from complete. I would suggest to find a way to be able to complete this list in a straight forward and nice way and/or remove this 'flag/error' for the time being. It doesn't look good on our records.

[example here](https://www.gbif.org/occurrence/3045035385)

**Comment by ManonGros** [comment]
Hi @DimEvil 

The best would be to write to scientific-collections@gbif.org
We can create the missing institutions for you and give the institutions contacts (or a representative person, you perhaps?) access to the entries created (to edit/complete them and add collections). Or we can also discuss making you part of our editorial team. In either case, you or the institution contacts would be using our registry UI: https://registry.gbif.org/institution/

We cannot remove the flags for the time being. If you would like to avoid attempts by the system to match the occurrences to GRSciColl (and therefore flag the records), you could consider not including any institutionCode, collectionCode, institutionID nor collectionID.
