### ISSUE TITLE
treatment borne names are are not in gbif backbone: 344f8a86-21a1-428e-ae4f-01ea6082254a 

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#3298]
how long, or at what time will the names submitted by Plazi's datasets show up in the GBIF datasets? there seems to be no names indexing related issue anymore in /health, and it seems to be processed: https://api.gbif.org/v1/dataset/process/running 

https://www.gbif.org/dataset/344f8a86-21a1-428e-ae4f-01ea6082254a

**Comment by ManonGros** [comment]
Thanks Donat, I assume that this is no longer an issue. Let me know if I should reopen it.
