### ISSUE TITLE
Incorrect synonym

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3302]
**Incorrect synonym**

Hyleoglomeris japonica is accepted, not Perkeomeris japonica. Perkeomeris japonica is invalidly proposed without type species recognition.

First, "Hyleoglomeris (Perkeomeris) japonica" was described by Verhoeff (1936). Later, the subgenus Perkeomeris was considered invalid (e.g. Golovatch, Geoffroy and Mauriès, 2006).

Reference
Verhoeff, K. W. (1936) Ueber Diplopoden aus Japan, gesammelt von Herrn Y. Takakuwa. Transactions of the Sapporo Natural History Society, 14(3): 148-172. http://hdl.handle.net/2115/64185

Golovatch, S. I., Geoffroy, J.-J. and Mauriès, J.-P. (2006) Review of the millipede genus Hyleoglomeris Verhoeff, 1910 (Diplopoda, Glomerida, Glomeridae), with descriptions of new species from caves in Southeast Asia. Zoosystema, 28(4): 887-915. http://sciencepress.mnhn.fr/en/periodiques/zoosystema/28/4/revision-des-diplopodes-du-genre-hyleoglomeris-verhoeff-1910-diplopoda-glomerida-glomeridae-et-description-de-nouvelles-especes-cavernicoles-d-asie-du-sud-est

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ee948e088e66b02c03aa9a512f112e78:3b25b5de2551f0d6ecfc28b994a6da096478112bdb9805aae9ab66f6e74e1fec838406f838945b0071afaa28ea2bc7f94f35362f0bd59752eeaf45ac0fc47cc58b8b41928f0dcb1b9b468b034bfea449)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/ja/species/1027915
Window size: width 1600 - height 827
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-09T07:40:32.344Z',to:'2021-03-09T07:46:32.344Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-09T07:40:32.344Z',to:'2021-03-09T07:46:32.344Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
@mdoering This looks like an other incorrect synonym due to the similar scientific epithet and authorship (like some of the ones mentioned here: https://github.com/gbif/checklistbank/issues/106).

**Comment by RyoKuwa** [comment]
_Hyleoglomeris japonica_ and _Perkeomeris japonica_ refer to the same taxon. _P. japonica_ is invalid and _H. japonica_ is valid. _P. japonica_ is accepted in GBIF, but in fact _H. japonica_ is accepted.

**Comment by mdoering** [comment]
Correct now in COL21, so GBIF will be fine soon
