### ISSUE TITLE
Bazillozonium was synonymized with Brachycybe

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3304]
**Bazillozonium was synonymized with Brachycybe**

Bazillozonium was synonymized with Brachycybe by Gardner (1974/1975). Bazillozonium nodulosum was changed to Brachycybe nodulosa.

Gardner, M.R. (1974/1975) Revision of the millipede family Andrognathidae in the Nearctic region. Memoirs of the Pacific Coast Entomological Society, 5, 1–61.

-----

Github user: @RyoKuwa
User: [See in registry](https://www.gbif.org/api/feedback/user/0844d576b5c3d996b6918ced46d46029:25ff6072f4585a6b9791a8a39cc005d50015312f0830453d031dfced37df8815cdca11ef5e154f0445db9308c632fc53845241f1d91e0ac325d1c32099801b5d60ed73241fa5ff56de60db0b5b01daae)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/ja/species/1021085
Window size: width 1600 - height 827
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-09T08:28:10.742Z',to:'2021-03-09T08:34:10.742Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-09T08:28:10.742Z',to:'2021-03-09T08:34:10.742Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
It looks like this issue together with these others concern the [MilliBase](https://www.gbif.org/dataset/8ea9b257-1d1a-4cd2-a752-bbc2a125633d) checklist:
* https://github.com/gbif/backbone-feedback/issues/400
* https://github.com/gbif/portal-feedback/issues/3304
* https://github.com/gbif/backbone-feedback/issues/401
* https://github.com/gbif/backbone-feedback/issues/402

But I don't see any data from on the dataset page.
@mdoering any idea on where to forward those issues?

**Comment by mdoering** [comment]
@ManonGros please move all COL issues to our data repository and label them with `feedback`:
https://github.com/CatalogueOfLife/data/issues/new/choose

If you know its from one of the COL sources you are very welcome to already place the issue on one of the project boards which are named after the source, e.g. for Millibase it is https://github.com/CatalogueOfLife/data/projects/189

**Comment by ManonGros** [comment]
thanks @mdoering! I don't have access to this repo so I won't be able to transfer the issues or place them on the project boards.
But I can create new issues in the CoL repo and link to the old ones. Would that be ok?

**Comment by mdoering** [comment]
Thats probably OK. Just select a meaningful title and maybe a very short summary and link to here. 
Or can I give you permissions to transfer? As far as I know one cannot transfer issues between organisations.

**Comment by RyoKuwa** [comment]
[#3302](https://github.com/gbif/portal-feedback/issues/3302)
Isn't this problem also related to Millibase?
These issues were raised by me through the GBIF website, but since this is my first time, I do not know how to respond.

**Comment by ManonGros** [comment]
You are right @RyoKuwa, this is also an issue related to Milibase. Thanks for notifying us!
We will forward the issues to the relevant people via GitHub, I will tag you there so you can keep an eye on the situation.

**Comment by RyoKuwa** [comment]
Thank you @ManonGros ! I have about 100 more suggestions for similar fixes about Millibase, is it better to report them one by one as I have been doing, or should I report them all at once?

**Comment by ManonGros** [comment]
Thanks @RyoKuwa! I think it might be easier for the Catalogue of Life and Millibase to review the issues one by one.
That being said, it is up to you. If you prefer putting everything in one big issue, this is no problem, we can make it work!

**Comment by RyoKuwa** [comment]
Thank you! I would like to report them one by one.

**Comment by ManonGros** [comment]
It looks like this issue has been solved in the newest backbone.
