### ISSUE TITLE
Author and year need to be put in "()".

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3306]
**Author and year need to be put in &quot;()&quot;.**

Kiusiozonium okai was described as "Saraminozonium okai" (Takakuwa and Miyosi, 1949). So author and year need to be put in "()".

Takakuwa, Y. and Miyosi, Y. (1949) Über eine neue Gattung and eine neue Art von Coloboognatha aus Japan. Acta Arachnologica, 11(1-2): 26-32.

-----

Github user: @RyoKuwa
User: [See in registry](https://www.gbif.org/api/feedback/user/23dab96e9f39282717ff4c362ace558a:37d8f03efd0a1afc74b371b50ccf1be1ea45346364a24be05b2eedf9b3e37fd32145ab6b66c00337a729004ca303e703768d94263f0aafb51a942cdc19999fb4669400b096d5603ddc54fcacf95adbc8)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/ja/species/8071755
Window size: width 1024 - height 738
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-09T09:13:17.382Z',to:'2021-03-09T09:19:17.382Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-09T09:13:17.382Z',to:'2021-03-09T09:19:17.382Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by jhnwllr** [comment]
@RyoKuwa
The name looks like this now Kiusiozonium okai (Takakuwa & Miyosi, 1949)

so I am closing the issue
