### ISSUE TITLE
good afternoon

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3307]
**good afternoon**

sir
how to search by api

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/935fd820efb47e4717dd0dae09be8271:6ee9859d21835ed234558003a94dde9774c73f303a3b7541e2c5951a4960462b5d9649e593f627cda7502adebb94510f51ee21bf63fa93c7de6868f4e21db18b)
System: Chrome 88.0.4324 / Windows 7.0.0
Referer: https://www.gbif.org/faq?q=how%20to%20api%20search
Window size: width 1680 - height 907
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-09T10:04:24.701Z',to:'2021-03-09T10:10:24.701Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-09T10:04:24.701Z',to:'2021-03-09T10:10:24.701Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
I can see this person also wrote to the API user list and Tim answered by sending the documentation link
