### ISSUE TITLE
sir i can't search data from api

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3308]
**sir i can&#39;t search data from api**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/acb4dd89d95a071d64c0f4178f45049f:235b7b020d53274f3b42b38be69802607e2cbcb225658a04cc78deddc5a1e37daa010a1e68a46861689c1d31664d6f234cc6dc98ca16a749684c23fe886fa76d)
System: Chrome 88.0.4324 / Windows 7.0.0
Referer: https://www.gbif.org/resource/search?contentType=programme
Window size: width 1680 - height 907
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-09T10:12:52.643Z',to:'2021-03-09T10:18:52.643Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-09T10:12:52.643Z',to:'2021-03-09T10:18:52.643Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by jlegind** [comment]
User has been contacted:

This works https://www.gbif.org/occurrence/search?advanced=1&project_id=BID-CA2016-0001-NAC 
Project ID is needed and not title.
