### ISSUE TITLE
Erro de informação

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3312]
**Erro de informação**

Nessa página aparece uma espécie de Cephalotrigona como sinonimo de uma Exomalopsis, mas isso não fez sentido pois C. zexmeniae é um nome válido, ver http://moure.cria.org.br/catalogue?id=34505

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/485c4ae222a287b3713f59ea71c851e9:459967a233df28b263a411866cce87170c2d366358b2af7362a71e78352c93cf79efc42f5439c21081c0232b9a9e09705ac8d434ac9b1065a13b433b3e969bd0)
System: Chrome 88.0.4324 / Mac OS X 10.15.7
Referer: https://www.gbif.org/pt/species/1340162
Window size: width 1280 - height 664
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-10T14:12:03.862Z',to:'2021-03-10T14:18:03.862Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-10T14:12:03.862Z',to:'2021-03-10T14:18:03.862Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
google translate

------

Information error

On this page appears a species of Cephalotrigona as a synonym for an Exomalopsis, but that did not make sense since C. zexmeniae is a valid name, see http://moure.cria.org.br/catalogue?id=34505

**Comment by MattBlissett** [comment]
I think this might be more useful for Markus etc:

On this page a species of Cephalotrigona appears as a synonym for an Exomalopsis, but that did not make sense since C. zexmeniae is a valid name, see http://moure.cria.org.br/catalogue?id=34505

https://www.gbif.org/species/1340162

It's fixed in the new backbone, which should be live within a few hours. (So I won't write to the user, at least not yet.)

**Comment by MattBlissett** [comment]
Replied by email from the helpdesk, the new backbone fixes this error.
