### ISSUE TITLE
plazi data not showing up properly

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#3313]
I never seen a treatment article from Plazi displayed this way, that's why I am asking. I though the indexing has been over, or is it just a question of patience?
![image](https://user-images.githubusercontent.com/4609956/110667428-87674100-81ca-11eb-9e37-c6d5b6aaaa8a.png)

https://www.gbif.org/dataset/970faa7a-925b-4fd1-85c5-215e05605b2b

**Comment by MattBlissett** [comment]
Hi Donat,

Indexing is off, but we expect to switch over to the new backbone tomorrow morning.  Assuming that goes well, indexing should be turned on again tomorrow afternoon.
