### ISSUE TITLE
country level occurrences through the API

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3317]
**country level occurrences through the API**

I would like to get a list of countries where a  given species has been observed. I have tried the following API call: 

https://api.gbif.org/v1/occurrence/search?taxonKey=8357600

This indeed returns countryCodes, which I can easily extract. However, the results seem to be limited to 20 records. 

I have also tried the following API call:
https://api.gbif.org/v1/occurrence/counts/countries?taxonKey=8357600

but this returns all counts per country. 

How can get counts per country/geographical region given a taxonKey?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3f1458a01a6e4a41433f5d9fe54d76c8:8d56efbf791bc7103293b4eabd4d9153c348e8a81727b67eaddfeb8f96941aacd3774038614db61ccdbcb2571e65f68c481605bfb8cdce51cc76f240630144c7)
System: Chrome 89.0.4389 / Mac OS X 10.15.6
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1439 - height 765
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-11T08:50:37.364Z',to:'2021-03-11T08:56:37.364Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-11T08:50:37.364Z',to:'2021-03-11T08:56:37.364Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: CRITICAL

**Comment by ManonGros** [comment]
Replied by email:
> You can use “facet” in the API. This allows you to group occurrences given a particular search query.

> For example, here are the occurrences for the taxon you mentioned grouped by country code:
https://api.gbif.org/v1/occurrence/search?limit=0&taxonKey=8357600&facet=country&facetLimit=200

> The “limit” is set to zero to avoid returning all the occurrences. The facetLimit corresponds to the maximum number of countries you will get back. Overall the “offset” and “limit” parameters as well as the “facetOffset” and “facetLimit” parameters will allow you to page through the results of the API.
