### ISSUE TITLE
Freetext search not resetting on filter change

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3318]
**Freetext search not resetting on filter change**

(unrelated to backbone refresh)

After a search with a free text filter, the filter keeps hanging in the URL even if removed from the search facets, leading to confusing results.

To reproduce:
- enter a free text search for "sheep" (gallery: the result contains some plants and insects aside from sheep)
- add a Scientific Name filter for "Mammalia"
- remove the free text search
- add another Scientific Name search for "Canis lupus" (wolf)
--> the result (see gallery) still contains sheep, the URL reads https://www.gbif.org/occurrence/gallery?q=sheep&taxon_key=359&taxon_key=5219173 even though the facet filter does not show the free text term any more

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e0f4993e5beb0e707c750817c1fe6b97:460942f6b66882c30abe3a5527ff466ba5efaf960fc7b8d2608a3b2634c047dd07d84b2585c2b66f65d7371321cb72eda1450b97433d6d39ed9132fedc21bd63)
System: Firefox 86.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/gallery?q=sheep&taxon_key=359&taxon_key=5219173
Window size: width 1095 - height 557
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-11T09:28:11.346Z',to:'2021-03-11T09:34:11.346Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-11T09:28:11.346Z',to:'2021-03-11T09:34:11.346Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
@ahahn-gbif 
This a usability issue. You deleted the text but didn't apply the change (by pressing enter or by clicking the search icon). So you are still searching for "sheep".

Makes sense that it can confuse. Perhaps just filling the field again if the user didn't apply is the simplest solution

**Comment by ahahn-gbif** [comment]
Thanks! I agree that re-filling it would limit the confusion. I am not the only one this happens to.
