### ISSUE TITLE
Search and browsing options not working

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#332]
**Search and browsing options not working**

Search and browsing options inside classification is not working when the browser is not in the full screen mode.

-----
fbitem-species9154373
Reported by: sreetama.bhadra@gmail.com
System: Chrome 52.0.2743 / Windows 7 0.0.0
Referer: https://www.gbif.org/species/9154373
Window size: width 950 - height 1078
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T12:29:24.813Z',mode:absolute,to:'2017-08-17T12:35:24.813Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T12:29:24.813Z',mode:absolute,to:'2017-08-17T12:35:24.813Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you for taking the time to report this.
That should teach me not to change things last minute. I have fixed the bug. The new version is now available.
