### ISSUE TITLE
Add 2020 review

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3330]
**Add 2020 review**

Collection incomplete, please add https://www.gbif.org/document/6yWPsmfxuJ7YFuHtbMsqbt/gbif-science-review-2020

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/cd5028d2a56b82ae8c7acc0a713bc71d:b2a20ed0b8de925da446bb3719b67a063dfd0d97c7a421435f178a3baabc07fde461b73cb17127f1445f82bf66dd37928a5d79498f49013e5316b3aca1d60fe9)
System: Chrome 89.0.4389 / Windows 10.0.0
Referer: https://www.gbif.org/science-review
Window size: width 1862 - height 926
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-18T16:12:08.409Z',to:'2021-03-18T16:18:08.409Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-18T16:12:08.409Z',to:'2021-03-18T16:18:08.409Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Thanks, done.
