### ISSUE TITLE
选中一个个体查看，在返回后直接返回到第一页 ，这样统计数据就很麻烦

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3334]
**选中一个个体查看，在返回后直接返回到第一页 ，这样统计数据就很麻烦**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/73032e2ffdb6db1ee3971b90cfad1f99:ec68ee4bbc4db57d0a75a74afec167f2104490f14c5dbaa448e73e91590cdbb996406a2131878722419c62f9b7af026edc95596dcc1fb9a9b05fe8cdc3974f3a)
System: Chrome 80.0.3987 / Windows 10.0.0
Referer: https://www.gbif.org/zh/occurrence/search?country=CN&has_coordinate=true&has_geospatial_issue=false&taxon_key=5332182&advanced=1
Window size: width 1536 - height 763
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-19T08:33:01.537Z',to:'2021-03-19T08:39:01.537Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-19T08:33:01.537Z',to:'2021-03-19T08:39:01.537Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Google translate

> Select an individual to view, and return to the first page directly after returning, so the statistical data is very troublesome

**Comment by MortenHofft** [comment]
I think this means that offset is lost when clicking back in the browser after having viewed an individual record. Apparently this is only the case if advanced mode is true.
