### ISSUE TITLE
Dutch vernacular name incorrect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3337]
**Dutch vernacular name incorrect**

This is some feedback we received on Helpdesk:
>  Verborgen boswitje is the dutch name for Leptidea reali.
> The dutch name for L. juvernica is Cryptisch boswitje

The vernacular Dutch name comes from the Catalogue of the Lepidoptera of Belgium (https://www.gbif.org/dataset/848271aa-6a4f-4bae-a055-7081f3e70c4b)

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/e72824a6296af3442a146c4640a92335:a1f329afabc1f1f3f6b1f603845e2816d37f19911c1e87463317f7777b8392dd6a13e2f43afc89278e5df21d629a88304e9f36a21be3d70821bc33c740929195)
System: Safari 14.0.3 / Mac OS X 10.15.6
Referer: https://www.gbif.org/species/5804895
Window size: width 1494 - height 846
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-19T12:22:36.927Z',to:'2021-03-19T12:28:36.927Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-19T12:22:36.927Z',to:'2021-03-19T12:28:36.927Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Contacted publisher by email.

**Comment by ManonGros** [comment]
The checklist has been corrected.
