### ISSUE TITLE
Why I can't download the dataset as a CSV file? How can I download it as CSV file?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3339]
**Why I can&#39;t download the dataset as a CSV file? How can I download it as CSV file?**

https://www.gbif.org/occurrence/download/0228104-200613084148143

-----

Github user: @mgcrp
User: [See in registry](https://www.gbif.org/api/feedback/user/dc10c430665e34573023bfa0f7805a53:efa8a16f09523f457ee73511d746504973993e6063744dae0b0fb3dc83d46682080f78034d0f55461eb2346ecb4fff42e3945e548e3563a9d5c47ec36f14244e)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0228104-200613084148143
Window size: width 1920 - height 922
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-22T11:27:43.437Z',to:'2021-03-22T11:33:43.437Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-22T11:27:43.437Z',to:'2021-03-22T11:33:43.437Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
According to the referring page, the download was requested in DwC Archive format. This means that it comes as a zipped folder that contains several files - the interpreted core data (occurrence.txt), the same data in their original version (verbatim.txt), a number of joined tables, and metadata files. All txt files are csv (tab delimited) data files, and should be available as such after un-zipping the containing folder.

**Comment by MortenHofft** [comment]
We support multiple download formats for occurrences. One of them is a tab delimited csv. 

For help with opening this type of files, see https://www.gbif.org/faq?question=opening-gbif-csv-in-excel

I'm closing this issue. Feel free to open a new if you still experience issues
