### ISSUE TITLE
Downloads list more occurrences then are available in dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#334]
**Downloads list more occurrences then are available in dataset**

On [this activity page](https://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e/activity), some recent downloads list:

&gt; xx occurrences from this dataset

Where `xx` is more than the number of occurrences present in the dataset. See e.g. some of the downloads for August 15 with 11.96 million records for a dataset with 8.47 million records.

-----
fbitem-dataset83e20573-f7dd-4852-9159-21566e1e691e
Reported by: @peterdesmet
System: Chrome 59.0.3071 / Mac OS X 10.12.5
Referer: https://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e/activity
Window size: width 1319 - height 736
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T12:34:36.655Z',mode:absolute,to:'2017-08-17T12:40:36.655Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T12:34:36.655Z',mode:absolute,to:'2017-08-17T12:40:36.655Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
this look to me like an API issue. Unless I'm reading the API wrongly
http://api.gbif.org/v1/occurrence/download/dataset/83e20573-f7dd-4852-9159-21566e1e691e

```
//extract
"numberRecords": 11961599,
"totalRecords": 342362316,
"numberDatasets": 9551

{
    "downloadKey": "0000140-170814131059671",
    "datasetKey": "83e20573-f7dd-4852-9159-21566e1e691e",
    "datasetTitle": "Bird tracking - GPS tracking of Lesser Black-backed Gulls and Herring Gulls breeding at the southern North Sea coast",
    "datasetDOI": "doi:10.15468/02omly",
    "datasetCitation": "Stienen E W, Desmet P, Aelterman B, Courtens W, Feys S, Vanermen N, Verstraete H, Van de walle M, Deneudt K, Hernandez F, Houthoofdt R, Vanhoorne B, Bouten W, Buijs R, Kavelaars M M, MÃ¼ller W, Herman D, Matheve H, Sotillo A, Lens L (2017). Bird tracking - GPS tracking of Lesser Black-backed Gulls and Herring Gulls breeding at the southern North Sea coast. Version 5.6. Research Institute for Nature and Forest (INBO). Occurrence Dataset https://doi.org/10.15468/02omly accessed via GBIF.org on 2017-08-15.",
    "numberRecords": 11961599,
    "download": {
    "key": "0000140-170814131059671",
        "doi": "doi:10.15468/dl.zcvp7k",
        "license": "unspecified",
        "request": {
        "predicate": {
            "type": "and",
                "predicates": [
                {
                    "type": "or",
                    "predicates": [
                        {
                            "type": "within",
                            "geometry": "POLYGON((-35.51 -89.14,-35.51 89.14,126.21 89.14,126.21 -89.14,-35.51 -89.14))"
                        },
                        {
                            "type": "within",
                            "geometry": "POLYGON((-99.213581 19.333336,-99.222850 19.329610,-99.227313 19.327180,-99.231433 19.323131,-99.234523 19.321997,-99.239158 19.318919,-99.240360 19.315517,-99.242248 19.312439,-99.240016 19.309361,-99.238128 19.307741,-99.234008 19.307579,-99.231948 19.306931,-99.226799 19.304501,-99.215469 19.316165,-99.210147 19.323779,-99.209461 19.331554,-99.210319 19.332850,-99.210319 19.332850,-99.210319 19.332850,-99.213581 19.333336))"
                        }
                    ]
                },
                {
                    "type": "equals",
                    "key": "HAS_GEOSPATIAL_ISSUE",
                    "value": "false"
                }
            ]
        },
        "format": "SIMPLE_CSV",
            "sendNotification": true
    },
    "created": "2017-08-15T18:39:23.714+0000",
        "modified": "2017-08-15T19:08:28.830+0000",
        "status": "SUCCEEDED",
        "downloadLink": "http://api.gbif.org/v1/occurrence/download/request/0000140-170814131059671.zip",
        "size": 23681015666,
        "totalRecords": 342362316,
        "numberDatasets": 9551
    }
}
```

**Comment by MattBlissett** [comment]
This is very likely fixed by the same work for https://github.com/gbif/occurrence/issues/28

Please reopen or file a new issue if you notice it again.
