### ISSUE TITLE
Activity Report: "Data availability in.." misreports Virus count (duplicate of Bacteria)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3340]
**Activity Report: &quot;Data availability in..&quot; misreports Virus count (duplicate of Bacteria)**

Glitch: the country activity reports contain a miscount (duplicated value from Bacteria) for viruses.

(reported during NSG call by JP node manager)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/92f7c3dd820b9aa966807b590bdde125:13f3fc7e59e25649153930e77c7f1f23fe07c9f5862aab15e37786530ecadaa4a6876106043ecbdca8b0c39d66d34a4837adb7ebc9c209489b94d8213ee027a9)
System: Firefox 86.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/country/JP/summary
Window size: width 1357 - height 826
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-23T14:00:46.760Z',to:'2021-03-23T14:06:46.760Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-23T14:00:46.760Z',to:'2021-03-23T14:06:46.760Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
@ahahn-gbif, I've fixed this in the code — it's been like this since they were converted to this format, in summer 2018.

I haven't regenerated the reports, since some sections (recent peer-reviewed articles, most recent datasets, newest publishers, top datasets, projects) would then show March 2021 data.

**Comment by ahahn-gbif** [comment]
Thanks Matt for the reminder - I logged it as it was pointed out during today's call. Good sign that the reports are actually read and used. The change will come into effect with the next annual update then?

**Comment by MattBlissett** [comment]
Yes, in January 2022.  (Unless we do something special.)
