### ISSUE TITLE
disconnect 2020 page in Russian from the new 2021 (master) page in EN

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3341]
**disconnect 2020 page in Russian from the new 2021 (master) page in EN**

Nataliya I noticed that if someone is switching to Russian language from the 2021 data papers announcement, then the reader sees the 2020 text but with 2021 picture. Please remove this incorrect link. The 2020 RU page should have an old visual (bumblebee), and instead of (1) in the title should read (2020). Most importantly, please disconnect the new 2021 page from that old translation.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/3a394e6f3f140fd04229adab0cdd0bc1:feedb7ac78f9f7dbf1f67bd51dde0b9f35718f97a5b2ac67785e8671e660d4dea301bfba25e1973eedc911ea7d0cbe0cac610a7c16bef95329f8ed5090cef745)
System: Chrome 89.0.4389 / Windows 10.0.0
Referer: https://www.gbif.org/ru/news/HdDwtyv9jjrvG99OSHsP6/vozmozhnost-opublikovat-stati-o-dannyh-po-evropejskoj-chasti-rossii-1
Window size: width 1862 - height 926
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-24T07:24:02.780Z',to:'2021-03-24T07:30:02.780Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-24T07:24:02.780Z',to:'2021-03-24T07:30:02.780Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Sorry, this is my bad. I duplicated the 2020 item when creating the 2021 one, not realising that the RU translation would be copied over as well. I've removed this now.

Do you want to provide a translation of the 2021 item as well?

**Comment by dschigel** [comment]
I will ask GBIF.ru

**Comment by dnoesgaard** [comment]
Ok thanks!
