### ISSUE TITLE
Download help

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3343]
**Download help**

Hi there, when I download records as a csv, there don't appear to be commas in the right places, such that the fields don't all line up, when opened in, for example, MS Excel.  When I set comma as the delimiter, it didn't work.

Please help.

For example, the data below is from one cell:

3031984820																										68080267										CC_BY_NC_4_0			2021-01-16T07:43:50Z			https://www.inaturalist.org/observations/68080267				┬® garywwilson some rights reserved	garywwilson												iNaturalist	Observations	iNaturalist research-grade observations		HUMAN_OBSERVATION				https://www.inaturalist.org/observations/68080267	68080267		garywwilson									PRESENT							These animals are in a Cairns City Central roost.												2020-01-25T15:31:00	05:31:00Z			2020	1	25	2020/01/25 3:31 PM AEST															AU	Queensland				Cairns QLD, Australia							-16.9202	145.7749	50.0																																150570176			garywwilson	2021-01-15T00:44:29				40911								Pteropus conspicillatus Gould, 1850								Animalia	Chordata	Mammalia	Chiroptera	Pteropodidae	Pteropus		conspicillatus		SPECIES				ACCEPTED			50c9509d-22c7-4a22-a47d-8c48425ef4a7	US	2021-03-21T09:21:34.666Z							GEODETIC_DATUM_ASSUMED_WGS84;INSTITUTION_MATCH_NONE;COLLECTION_MATCH_NONE	StillImage	true	false	5218680	5218680	1	44	359	734	9367	2432854		5218680	Pteropus conspicillatus	Pteropus	Pteropus conspicillatus Gould, 1850	Pteropus conspicillatus		DWC_ARCHIVE	2021-03-21T09:21:34.666Z	2021-03-21T07:12:09.319Z	true				AUS	Australia	AUS.7_1	Queensland	AUS.7.13_1	Cairns			EN

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2620424ffb2d83de462739fbd4eb1329:bac98a2f9b37469906bc345423a25ea8bf942d29782628ed47abb9b2dbd00f8cb580b401a74e83bf1f815a91d0346991327ae23c7d0e2ff95733773f2b0eeb308f9ae48d991cc1a50e89946dbe9e96c7)
System: Chrome 89.0.4389 / Windows 10.0.0
Referer: https://www.gbif.org/health
Window size: width 1920 - height 1000
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-25T06:24:06.326Z',to:'2021-03-25T06:30:06.326Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-25T06:24:06.326Z',to:'2021-03-25T06:30:06.326Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by Jegelewicz** [comment]
Try opening as a tab separated file.

**Comment by MortenHofft** [comment]
https://www.gbif.org/faq?q=csv

If you are still having issues, then please send a link to the download in case - it might be that it is corrupt somehow.

**Comment by Jegelewicz** [comment]
When I downloaded from GBIF, I found that the file is tab separated - two other people that I am working with have noticed the same issue. The downloads should either be structured as comma separated or they should be .tsv

All I had to do was change the file from .csv to .tsv in order to be able to open it with Excel.

**Comment by MortenHofft** [comment]
Related to https://github.com/gbif/occurrence/issues/100

Good to hear that you solved it. The mail with the download link also describes that it is a tab delimited csv and a description of how to open it in excel

**Comment by MortenHofft** [comment]
> user informed per email
