### ISSUE TITLE
API limits species offset to 100,000

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3345]
**API limits species offset to 100,000**

Hi there,

I'm using the GBIF API to cache species records locally—so I don't hit the API with lots of queries during development—but I ran into this issue:

(venv) Raphaels-MacBook-Pro:conservation raphaelmatto$ python utils.py
Requesting records with offset 100001 ...
Starting new HTTPS connection (1): api.gbif.org:443
https://api.gbif.org:443 "GET /v1/species/?language=en&limit=20&offset=100001 HTTP/1.1" 400 46
Response status code is: 400
Response text is: Offset is limited for this operation to 100000

Is it possible to get a token with permissions that will allow me to complete my download? It's a one-time thing, although I might want to refresh the data in 1/2 a year or a year. Alternatively, do you folks provide a link to a download that contains all species records? I'm guessing the entire thing is less than 2GB, so not that big. Seems better for developers to d/l the records while in dev, instead of hammering your db all day. Thanks!

Raphael

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3d80f7f7dff9efdba0ba048ed72ff1bb:ab4db5bdba6d964bd4864807a2280db22183dd76b7f5b53d3d432e110ed2f495eaa33d63caa20f00caab6f93f6b493ff8ecf7d1c2bd3bc8debb30a34571f003a)
System: Safari 14.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/developer/species
Window size: width 1635 - height 939
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-26T03:07:25.335Z',to:'2021-03-26T03:13:25.335Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-26T03:07:25.335Z',to:'2021-03-26T03:13:25.335Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email with a link to https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c which links to the downloads of the backbone.
