### ISSUE TITLE
discrepency in taxonomic backbone for Siphonaptera between download and UI

### ISSUE THREAD

**Issue by Jegelewicz** [gbif/portal-feedback#3346]
A download of the taxonomic backbone filtered for order = Siphonaptera results in 4,429 names but a search in the UI (https://www.gbif.org/species/search?highertaxon_key=1366&advanced=1) results in only 4,275.

I expected these numbers to be the same and am curious to know why they are not.

I am also curious as to why I am unable to search for the order Siphonaptera in the UI. I got to the results above by finding the taxon key for Siphonaptera and modifying the url in a search for Insecta.

**Comment by MortenHofft** [comment]
I've created a new issue for searching higher taxonomy as that is unrelated to what I understand as your main question

**Comment by Jegelewicz** [comment]
Just checking in to see if anyone can take a look at this issue. As I have been working through a names list, I also discovered that Ceratophyllus anisus does not appear in my download, although it does in the UI - https://www.gbif.org/species/10859342 

I can guess at why this is so, but I would like to know for sure. Any assistance would be appreciated.

**Comment by ManonGros** [comment]
Hi @Jegelewicz, as far as I understand the numbers on the API (and UI) correspond to the accepted species names.

**For example:**
The Tungidae family shows 26 species: https://www.gbif.org/species/5321
If you look in the backbone file, there are 42 names for this family:
* 31 of them are accepted (the others are "doubtful" or "synonym")
* Of these 31 names, there is one family name, 4 genus names and 26 species names.

@mdoering Could you confirm that this is what is happening here?

**Comment by mdoering** [comment]
@ManonGros this is correct. But it does not explain the discrepancy @Jegelewicz  has spotted with [Siphonaptera](https://www.gbif.org/species/search?highertaxon_key=1366&advanced=1). The search should return all names regardless their rank and status that have Siphonaptera in their classification. You can see the rank & status facets for the breakdown. 

A quick `grep "Insecta\tSiphonaptera" Taxon.tsv | wc -l` on the current [march 2021 download](https://hosted-datasets.gbif.org/datasets/backbone/backbone-current.zip) returns 4276 names, while the search returns 
4275. This matches up perfectly as the grep also spots Siphonaptera itself which the search does not.

@Jegelewicz maybe you have been using an older version of the backbone?

**Comment by Jegelewicz** [comment]
@mdoering thanks for that, but I am pretty sure we have the latest version - we downloaded again this am. I have attached the file with the list of "Siphonaptera" that we queried from the download. Oddly, there appear to be names from the UI that are not in the query, even though there are more names in the query than I find in the UI. See https://github.com/gbif/portal-feedback/issues/3346#issuecomment-818243138 as well as Callopsylla gemina https://www.gbif.org/species/1417422


[GBIF_Siphonaptera.zip](https://github.com/gbif/portal-feedback/files/6305793/GBIF_Siphonaptera.zip)

**Comment by Jegelewicz** [comment]
> A quick grep "Insecta\tSiphonaptera" Taxon.tsv | wc -l

This makes sense given how I have to get to the Siphonaptera in the UI, but with the download, we can just query for order=Siphonpatera, which gives different results apparently?

**Comment by mdoering** [comment]
When you say _queried from the download_ you mean you have somehow filtered the file https://hosted-datasets.gbif.org/datasets/backbone/backbone-current.zip to only contain the rows with `order=Siphonaptera`? How exactly did you do this? Your file contains 4429 names, while my grep finds 4275 (which includes Ceratophyllus anisus and Callopsylla gemina).

**Comment by ManonGros** [comment]
@mdoering I downloaded the backbone a few days ago from https://hosted-datasets.gbif.org/datasets/backbone/backbone-current.zip
and did `grep "Insecta\tSiphonaptera" backbone-current/Taxon.tsv | wc -l` and got `4431`.
Today, I re-downloaded it from the same URL and used the same command and got `4276`.

I remember that you wrote that you updated a link recently, could it be the reason why?

If that's the case, then @Jegelewicz has an old backbone version. @Jegelewicz could you try re-downloading the backbone?

**Comment by mdoering** [comment]
Ah yes. That's it. The _current_ link is or rather should be a symbolic link to the latest version of the backbone.
But we forgot to update the link so until yesterday it still pointed to the last 2019 version. That explains it all.

You can always access the individual versions by date as folders here:
https://hosted-datasets.gbif.org/datasets/backbone/

**Comment by Jegelewicz** [comment]
A new download (as of yesterday) now matches your experience, but (asking for a friend)

> Why does the GBIF download page still list September 2019 as the last modified date on the web front end?

**Comment by MortenHofft** [comment]
> **Metadata** last modified September 6, 2019.

The metadata is different from the checklist (core) data. Metadata is essentially the description and an endpoint to where the data is located.
