### ISSUE TITLE
Does bug reports support all the Markdown referenced in the Markdown guide?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#335]
**Does bug reports support all the Markdown referenced in the Markdown guide?**

A whole bunch of Markdown to test

---

It&#39;s very easy to make some words **bold** and other words *italic* with Markdown. You can even [link to Google!](http://google.com)

---

Sometimes you want numbered lists:

1. One
2. Two
3. Three

Sometimes you want bullet points:

* Start a line with a star
* Profit!

Alternatively,

- Dashes work just as well
- And if you have sub points, put two spaces before the dash or star:
  - Like this
  - And this

---

If you want to embed images, this is how you do it:

![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)

---

# Structured documents

Sometimes it&#39;s useful to have different levels of headings to structure your documents. Start lines with a `#` to create headings. Multiple `##` in a row denote smaller heading sizes.

### This is a third-tier heading

You can use one `#` all the way up to `######` six for different heading sizes.

If you&#39;d like to quote someone, use the &gt; character before the line:

&gt; Coffee. The finest organic suspension ever devised... I beat the Borg with it.
&gt; - Captain Janeway

---

There are many different ways to style code with GitHub&#39;s markdown. If you have inline code blocks, wrap them in backticks: `var example = true`.  If you&#39;ve got a longer block of code, you can indent with four spaces:

    if (isAwesome){
      return true
    }

GitHub also supports something called code fencing, which allows for multiple lines without indentation:

```
if (isAwesome){
  return true
}
```

And if you&#39;d like to use syntax highlighting, include the language:

```javascript
if (isAwesome){
  return true
}
```

---

GitHub supports many extras in Markdown that help you reference and link to people. If you ever want to direct a comment at someone, you can prefix their name with an @ symbol: Hey @kneath — love your sweater!

But I have to admit, tasks lists are my favorite:

- [x] This is a complete item
- [ ] This is an incomplete item

When you include a task list in the first comment of an Issue, you will see a helpful progress bar in your list of issues. It works in Pull Requests, too!

And, of course emoji! :sparkles: :camel: :boom:

-----
fbitem-dataset83e20573-f7dd-4852-9159-21566e1e691e
Reported by: @peterdesmet
System: Chrome 59.0.3071 / Mac OS X 10.12.5
Referer: https://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e/activity
Window size: width 1319 - height 736
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T12:42:32.320Z',mode:absolute,to:'2017-08-17T12:48:32.320Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T12:42:32.320Z',mode:absolute,to:'2017-08-17T12:48:32.320Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by peterdesmet** [comment]
It looks like **all the Markdown** features (from the examples in [this guide](https://guides.github.com/features/mastering-markdown/)) are supported, except:

> Blockquotes

Which is a bug.

**Comment by MortenHofft** [comment]
It's a feature

**Comment by peterdesmet** [comment]
As in: blockquotes are not supported by design? 😄
