### ISSUE TITLE
the photo is not of the species listed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3350]
**the photo is not of the species listed**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4b094d659f78a5177222e13be7959f05:24f6c0afdd641e332932b5cd2564e341fc451576835b9ce236d8ac680aa68f4b22d60ed98b58e26573a5be86086f5e5698a3ea5a7fc8b405c0f5cc45913d56b8)
System: Chrome 89.0.4389 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2242781618
Window size: width 1366 - height 635
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-30T07:28:02.502Z',to:'2021-03-30T07:34:02.502Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-30T07:28:02.502Z',to:'2021-03-30T07:34:02.502Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

**Comment by ManonGros** [comment]
The corresponding iNaturalist is no longer research-grade and therefore no longer on GBIF under that name: https://www.inaturalist.org/observations/23868947
