### ISSUE TITLE
the distribution shown on the map is incorrect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3351]
**the distribution shown on the map is incorrect**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5707fe34393596a2a6eb036db3c8f919:2d30ce85f956c0bd406196de99423d7c12dc7510bcc475fa16964ebee4c17a7a87031fd5098d05235c24c6a294528a3296d597f74ed00df20ad37233e9675a92)
System: Chrome 89.0.4389 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2242781618
Window size: width 1366 - height 635
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-30T07:28:56.276Z',to:'2021-03-30T07:34:56.276Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-30T07:28:56.276Z',to:'2021-03-30T07:34:56.276Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

**Comment by ManonGros** [comment]
The record is no longer available, I will close this issue.

**Comment by ManonGros** [comment]
Actually, it looks like this is the record: https://www.gbif.org/occurrence/2456496866

**Comment by jhnwllr** [comment]
Several seen in S. Africa. I will close the issue. 
https://www.inaturalist.org/observations/24007605
