### ISSUE TITLE
Several of our occurrences are marked as "Presumed swapped coordinates". Sometimes it can be right, but on many occasions (e.g. NSK0007601) our coordinates are right (Siberia) but your coordinates are wrong. After coordinate swapping this point was moved to the ocean.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3353]
**Several of our occurrences are marked as &quot;Presumed swapped coordinates&quot;. Sometimes it can be right, but on many occasions (e.g. NSK0007601) our coordinates are right (Siberia) but your coordinates are wrong. After coordinate swapping this point was moved to the ocean.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/cabd354017391d6efc7a48f12f1c6a7c:0cebe91707d0e753d867c67d0703536abe461634a693a01265eba7e67fada534f3eec692cae5ba17440e929b0fc05d5fe2f36e2ba26d60370c0eec98c00776f2)
System: Opera 74.0.3911 / Windows 7.0.0
Referer: https://www.gbif.org/occurrence/2562063886
Window size: width 1504 - height 751
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-06T04:31:48.642Z',to:'2021-04-06T04:37:48.642Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-06T04:31:48.642Z',to:'2021-04-06T04:37:48.642Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: e4fd8292-95cb-4f49-a639-e59c89e82045
publishingOrgKey: 8f6232c3-5523-44ad-825c-e066fc6b15ad

**Comment by MortenHofft** [comment]
The original coordinates are located in what our parser consider Kazakhstan. And since the occurrence record states that the country is Russia, the solution is to swap the coordinates. This can by solved by removing the country or by changing it to `Kazakhstan`

https://www.google.dk/maps/place/53%C2%B054'00.0%22N+76%C2%B024'00.0%22E/@53.9,76.3978113,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d53.9!4d76.4

please correct me if I'm wrong @MattBlissett 

> user informed by email
