### ISSUE TITLE
I would like to download an image to use in a publication (original source iNaturalist). Please can you advise me if this is acceptable, and if so, how to carry out the download? Thanks

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3355]
**I would like to download an image to use in a publication (original source iNaturalist). Please can you advise me if this is acceptable, and if so, how to carry out the download? Thanks**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6bc5ba3754166316b037242df256e20c:f46888bdb1056da99f69e5c57612db234e2b4c8eb454eb814282cd70398b7cde759b8ca06b1ee80a5cfce63237bb760e44b9b70f646e3f5ae8a5dbec62de9df6)
System: Chrome 89.0.4389 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2826152344
Window size: width 1280 - height 553
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-06T10:59:24.087Z',to:'2021-04-06T11:05:24.087Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-06T10:59:24.087Z',to:'2021-04-06T11:05:24.087Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

**Comment by ManonGros** [comment]
Replied by email:

> The images published here https://www.gbif.org/occurrence/2826152344 are under a CC BY license so you should be able to use it for your publications if you give the proper attribution.
Under each image on the occurrence page, you should find a suggested attribution (see screenshot below). For example: “Polygala vulgaris L. observed in Germany by Markus Krieger (licensed under http://creativecommons.org/licenses/by/4.0/)”, you can use it to credit the original owner.
> You can also download the image by clicking on the “Identifier” link below the image (see attached screenshot) and save the image.
<img width="475" alt="find_info_image" src="https://user-images.githubusercontent.com/7677271/113703999-dde97180-96db-11eb-9728-5cd4b11755ba.png">

> If you are unsure about the image license, you can always look back at the reference, for example: https://www.inaturalist.org/photos/39050395. This will not only show you a particular image license but will also give you the possibility to contact the image owner if you have an iNaturalist account (https://www.inaturalist.org/people/markuskrieger).
