### ISSUE TITLE
How do I start reporting transects?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3357]
**How do I start reporting transects?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/58c833bd79916d7524a61292b6b5cda6:e4d3304f8afcf70833a1522a8036d2428524877bb577ccdad0ef5b580bc4116e863d1937e97896ef1ab3abb7a56d4b34503bc920e16ef3ea734b9b65fa7b88ce)
System: Mobile Safari 14.0.3 / iOS 14.4.2
Referer: https://www.gbif.org/health
Window size: width 320 - height 438
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-06T23:24:10.606Z',to:'2021-04-06T23:30:10.606Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-06T23:24:10.606Z',to:'2021-04-06T23:30:10.606Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
>  [This quick guide to data publishing](https://www.gbif.org/publishing-data) will contain all the relevant links to help you navigate the data publishing process.
