### ISSUE TITLE
Palorus foveicollis was oddly listed as a synonym of 2206 (Tenebrionidae sp.)??? This is now the second Tenebrionidae species with this issue (the other being Blapstinus rufipes).

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3359]
**Palorus foveicollis was oddly listed as a synonym of 2206 (Tenebrionidae sp.)??? This is now the second Tenebrionidae species with this issue (the other being Blapstinus rufipes).**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0ac05d303374dfe1f56f1dd84f98126c:304ad8c1f91002473dac186b6b6a2b638f32cf9baa9f8f269355c4f56331189b578f933858c740a739118ef8f24c5606fe799fa6eb01676f884a05d3a6bb5688)
System: Chrome 89.0.4389 / Windows 10.0.0
Referer: https://www.gbif.org/species/1045838
Window size: width 1536 - height 754
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-07T05:14:27.925Z',to:'2021-04-07T05:20:27.925Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-07T05:14:27.925Z',to:'2021-04-07T05:20:27.925Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@mdoering I can see that the checklist the issue comes from, the Catalogue of Tenebrionidae (Coleoptera) of North America (https://doi.org/10.15468/wm3ukc), is using identifiers (such as 2206) as `acceptedNameUsage`. Could it be the reason why we see this odd taxonomy in the backbone?
(see related issue here: https://github.com/gbif/portal-feedback/issues/3358)

If that's the case, I guess remapping the column to `parentNameUsageID` would fix the issue, wouldn't it? Should I notify the author of the checklist?
let me know, thanks!

**Comment by mdoering** [comment]
There are a few things wrong in this dataset indeed:
https://www.gbif.org/species/140387896/verbatim

 - acceptedNameUsage should probably be _acceptedNameUsageID_: `2206`
 -  quoted values for _scientificNameAuthorship_: `"Blair, 1930"`
 - quoted values for _scientificName_: `"Palorus foveicollis Blair, 1930"`

parentNameUsageID would not be correct as these are synonyms.
I see that they also have not used parentNameUsageID at all but rely on the flat dwc ranks, even though there are more names in the _higherClassification_, e.g. Pimeliinae & Edrotini are missing here: https://www.gbif.org/species/140393204/verbatim

It would be nice if they would export all taxa using the parent child model using parentNameUsageID and acceptedNameUsageID.

We might need to exclude all synonyms from this dataset or rather block it completely from the backbone

**Comment by mdoering** [comment]
I have added this to the next backbone build todos: https://github.com/orgs/gbif/projects/5

**Comment by mdoering** [comment]
The checklist still contains bad data / mappings. @ManonGros can we notify the publisher about this or park the issue somewhere? There are over 6000 names coming from this list though: https://www.gbif.org/species/search?dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&constituent_key=56c83fd9-533b-4b77-a67a-cf521816866e&advanced=1

more than 1400 are bad numbers though:
https://www.gbif.org/species/search?dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&constituent_key=56c83fd9-533b-4b77-a67a-cf521816866e&name_type=OTU&advanced=1

more than 3200 accepted species look very correct:
https://www.gbif.org/species/search?dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&constituent_key=56c83fd9-533b-4b77-a67a-cf521816866e&name_type=SCIENTIFIC&status=ACCEPTED&advanced=1

I will make the nub build configurable which source can supply OTU names. Default will then be none, so we only get BOLD and UNITE OTUs into the nub and keep the 1400 numbers here out.

**Comment by ManonGros** [comment]
I just contacted the publisher by email.
