### ISSUE TITLE
Mendeley

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#336]
**Mendeley**

Mendeley public library is not searchable for me, and link from here https://www.gbif.org/literature-tracking to Mendeley seems to be not working in Firefox or Chrome. IMHO we cannot yet fully abandon Mendeley, some functions are very neat and fast there, but probably not very frequently used (how many GBIF used papers dealt with traits in 2015?). I keep recommending to GBIF users to look through GBIF Mendeley collections. Which access point or webpage?

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
Reported by: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/search?q=Mendeley
Window size: width 1600 - height 868
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T12:53:31.670Z',mode:absolute,to:'2017-08-17T12:59:31.670Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T12:53:31.670Z',mode:absolute,to:'2017-08-17T12:59:31.670Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
I don't think anyone has suggested to abandon Mendeley have they?  All the literature on GBIF.org is sourced from indexing Mendeley

**Comment by dnoesgaard** [comment]
This appears to be a problem with Mendeley. Investigating...

**Comment by dnoesgaard** [comment]
The link is dead, doesn't work. Applies to the old site also btw.

I've changed the wording slightly on https://www.gbif.org/literature-tracking and added a new link, as it seems that Mendeley requires that you are logged in to access the library...
