### ISSUE TITLE
Fuzzy matching algorithm is going overboard on this one.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3360]
**Fuzzy matching algorithm is going overboard on this one.**

Rhagonycha carolynae Fanti & Walker, 2019 is correct. It's a new name, as you can see. It is in PBDB. SEE https://paleobiodb.org/classic/basicTaxonInfo?taxon_no=399711 and indeed a search in GBIF for Rhagonycha turns up this literature containing this new species https://doi.org/10.11646/palaeoentomology.2.5.13

How does LACM let GBIF know a) these are fuzzy-matched in error, b) prevent this from happening again?

IF
a) genus exists (which it does) AND
b) year of name (2019 in this case) is newer than perhaps the last update from PBDB, then one would not fuzzy-match but realize it's a new name?

For fuzzy-matching, if the genus token is spelled correctly, (and it is) and it exists in the backbone (which I assume it does) why would fuzzy matching change it? It seems this would be a clue that the name is new, not in error. 

I realize all of this is hard! So please note, my goals are 

a) to understand more about how these issues are occurring

b) figure out how collections find out about these

c) figure out what agency collection / data managers are offered by GBIF (or others) to help in improving the situation going forward

For example: IF collections were to check their names against what GBIF has, in advance, and then resolve before publishing their data? This would slow data publishing BUT it might speed up improving the backbone contents? Would this be a practice to recommend? 

 In other words, we'd have to focus on the processes that enable (give agency to) the collection/data managers to take part in helping with taxonomy that feeds the backbone.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/232b00084567f850e38b2928db4c72ff:c815bee4be15e42b1ea786691bbb3972834f8580bd298413167cbf20c65911bef1c121062e49427a052d3736e18e7464727cb95243d7503419e21cc00f1f2abd)
System: Firefox 87.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1950906981
Window size: width 1667 - height 1083
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-08T15:54:45.121Z',to:'2021-04-08T16:00:45.121Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-08T15:54:45.121Z',to:'2021-04-08T16:00:45.121Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: f0a7ca6e-8da6-4629-97bd-0368705a4d6b
publishingOrgKey: 493fe050-055d-11d8-b84f-b8a03c50a862

**Comment by ahendy-zz** [comment]
> In other words, we'd have to focus on the processes that enable (give agency to) the collection/data managers to take part in helping with taxonomy that feeds the backbone.

So collections can contribute to the GBIF backbone in the form of a Checklist dataset. I'd suggest that future collaborative digitization projects (e.g., TCNs) - and past projects where such data was internally generated - should submit a checklist that helps the GBIF taxonomic backbone parse there own data. Relying on other services (e.g., IRMG, WoRMS, PBDB) to provide that data is an indirect solution, and relies on taxonomic opinions from those who are not in possession of the taxa in question - "be in control of your own data". I would suggest that this would be a good practice moving forward.

**Comment by debpaul** [comment]
To @MortenHofft @timrobertson100 @mdoering would it be possible to index **verbatimScientificName**?  

This would be one step toward discovery, before the name is (might be) inserted into the backbone formally? 

I realize (I think) this means the name would not be available via the search method that lets one traverse the hierarchical tree. But, it would potentially allow one to find these specimens when searching the full-text.

**Comment by ahahn-gbif** [comment]
The correct genus name (Rhagonycha) presently comes from the "Checklist of Beetles (Coleoptera) of Canada and Alaska. Second Edition." (https://www.gbif.org/species/4407026). The issue with interpretation here is a combination of
- missing taxonomic information (the species is not available in the taxonomic sources)
- taxon matching needing a certain level of rule-based interpretation (i.e. working off the taxonomic backbone, without options to consider constituent databases separately). In this case, a modification of the algorithm does not appear to be a viable solution.

This issue should resolve once the full name at species level becomes available in the taxonomic sources. Meanwhile, agree with @ahendy-zz that expert-curated checklist publication, and their integration into the backbone, is something that GBIF would want to support. The primary mechanism for this would still ideally go through Catalogue of Life, or in this case through PaleoDB, but the publication of an authoritative checklist outside of these is possible as well.

**Comment by ahahn-gbif** [comment]
appears to be fixed now - closing
