### ISSUE TITLE
Hello, excellent project. Very useful and interesting. I am in Tucumán, I live in the Yungas area, we have agro-ecological crops (and many more people) for example Smallanthus sonchifolius, Curcuma longa and C. zedoaria, Manihot esculenta, among other things. I know that in other provinces of my country it is also cultivated a lot. How do they update the maps? How do they get the information? I could send you photos and location if it works for you. Greetings, have a nice weekend. Erika

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3361]
**Hello, excellent project. Very useful and interesting. I am in Tucumán, I live in the Yungas area, we have agro-ecological crops (and many more people) for example Smallanthus sonchifolius, Curcuma longa and C. zedoaria, Manihot esculenta, among other things. I know that in other provinces of my country it is also cultivated a lot. How do they update the maps? How do they get the information? I could send you photos and location if it works for you. Greetings, have a nice weekend. Erika**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bca4456fe0745c9283b3d2e576b85f65:3eb716e5214e62a9bad8420f6efb51ffc14c2e5ab7dfd84d943ca274b63f67841ab19236c40852cf36b8e642109a3422ffc601d9900c60110bbb703904e15633)
System: Chrome 89.0.4389 / Windows 10.0.0
Referer: https://www.gbif.org/contact-us
Window size: width 1366 - height 657
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-10T00:44:34.322Z',to:'2021-04-10T00:50:34.322Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-10T00:44:34.322Z',to:'2021-04-10T00:50:34.322Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
User has been contacted.
