### ISSUE TITLE
Possible misspelling Macrotricidae - Macrothricidae

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3369]
**Possible misspelling Macrotricidae - Macrothricidae**

We got this feedback on Helpdesk.
One of our users suspects that this family, Macrotricidae, could be a misspelling of the Family Macrothricidae (https://www.gbif.org/species/7641).

Macrotricidae has no genus children in the backbone.
Buts some of the genera in the original source (https://www.gbif.org/species/167991674) are the same as the genera for the Macrothricidae family in the backbone.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/7fecbef134ccde03343335e7d8cecc1e:1d23ad0ad47f54c6005fd7bc43af0920c22b835e232ce9ba7a840bb3029953435204d5f164dff51431853d0e32ef3aa60d3825faeabe601aac8a9945995ffaea)
System: Safari 14.0.3 / Mac OS X 10.15.6
Referer: https://www.gbif.org/species/8469663
Window size: width 1543 - height 814
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-14T06:28:27.619Z',to:'2021-04-14T06:34:27.619Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-14T06:28:27.619Z',to:'2021-04-14T06:34:27.619Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I contacted Artsnavnebasen and they confirmed that this is likely a misspelling. The name has been corrected so the issue should be solved in the next backbone update.

**Comment by ManonGros** [comment]
solved in the new backbone
