### ISSUE TITLE
Metadata only datasets do not appear

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#337]
**Metadata only datasets do not appear**

On DataPublisher page or when searching for a dataset,
Metadata-only datasets do not appear

-----
fbitem-publishera5c9b60f-8603-43c5-adf9-c2b2b8cbe95f
Reported by: @andrejjh
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/publisher/a5c9b60f-8603-43c5-adf9-c2b2b8cbe95f
Window size: width 1401 - height 759
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T13:10:47.698Z',mode:absolute,to:'2017-08-17T13:16:47.698Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T13:10:47.698Z',mode:absolute,to:'2017-08-17T13:16:47.698Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
For this publisher
https://www.gbif.org/dataset/72928c80-aeaf-4778-b414-3a13f2ad41b1 is a
metadata only dataset

**Comment by cgendreau** [comment]
The dataset is returned by the API:
http://api.gbif.org/v1/organization/a5c9b60f-8603-43c5-adf9-c2b2b8cbe95f/publishedDataset

**Comment by MortenHofft** [comment]
http://api.gbif.org/v1/dataset/search?publishing_org=a5c9b60f-8603-43c5-adf9-c2b2b8cbe95f
is the one we are using on the site

**Comment by cgendreau** [comment]
The dataset (and only this one based on counts) was not in the search index.
I can't really explain why, fixed it by forcing an update.
