### ISSUE TITLE
recognize tsv files

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3370]
**recognize tsv files**

My Darwin Core Archive has .tsv files in it, and the validator seems unable to recognize that. The taxonID, taxonomicStatus, etc. are all smooshed together, and I get errors. When I use .csv the archive validates

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6684b4927d35293012a4c68e2155c620:e29d06ad0e5d373a9a8d528536b94fe6b00bd6cdc3206aba585a4787f3b7cf0f0785b383ce874320040885cb33b12063e547a9e95d804392338a7dee8f0432e5)
System: Chrome 89.0.4389 / Mac OS X 11.2.3
Referer: https://www.gbif.org/tools/data-validator/1614975526341
Window size: width 1780 - height 1193
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-14T13:44:35.906Z',to:'2021-04-14T13:50:35.906Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-14T13:44:35.906Z',to:'2021-04-14T13:50:35.906Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Will reply by email.

The user's archive has TSV files, but `linesTerminatedBy="\r\n" fieldsTerminatedBy="," fieldsEnclosedBy="&quot;" ignoreHeaderLines="1"` (i.e. CSV) metadata.
