### ISSUE TITLE
Error in opening tab-delimited CSV in Excel

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3372]
**Error in opening tab-delimited CSV in Excel**

I'm using Excel in Windows 10 (Microsoft 365 Apps for enterprise, version 2013). I downloaded a Simple format query file.

From the Data tab in Excel you can select Get Data - From file - From text/CSV. You can then select the file origin (UTF-8) and delimiter (comma? tab?) - none of these work. The result is 3 columns, with various fields lumped together.

Please could you check your instructions? At present it is necessary to download the full DarwinCore version and load occurrences.txt into Excel.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e18b723901d00fc2a4d935d62aa01313:899fbcc4416a35bee2e5200eed73a2b12085faeabb911c1d1b193d3ba56f30f44444bfa9fe8c0d1560631cd8817d226a2423d85ee5a45d717844645662c3457c)
System: Firefox 87.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
Window size: width 1600 - height 826
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-14T19:22:45.595Z',to:'2021-04-14T19:28:45.595Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-14T19:22:45.595Z',to:'2021-04-14T19:28:45.595Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Has this been resolved?

**Comment by jlegind** [comment]
User contacted.
Issue was not reproducible.

**Comment by jlegind** [comment]
Grabbed to first 10,000 lines from the download (to get around the 50MB limit in Office Excel) and these imported fine with all columns tab separated.
