### ISSUE TITLE
How do I cite this website?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3373]
**How do I cite this website?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6188c03f01c0885a4fe8324bbdbbfaa1:c505971359b6e762d129b5fc34e34a182b838b328ab74536efc51a0751b5605f53aa3ef925ab5409a48845c519d6c2f62d08eb550e21465eb66ac2b7856ff9bd)
System: Chrome 89.0.4389 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/charts?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7&has_coordinate=true&has_geospatial_issue=false&month=1&month=2&month=3&month=4&month=5&month=6&month=7&month=8&month=9&month=10&month=11&month=12&taxon_key=2444354&year=2014,2021
Window size: width 1280 - height 578
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-15T04:31:27.763Z',to:'2021-04-15T04:37:27.763Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-15T04:31:27.763Z',to:'2021-04-15T04:37:27.763Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> The best way to this page is to cite the underlying data. I can see that you already generated a download for this selection. I suggest to cite this download by following the recommended citation.

> For general information about the citation, please check [our citation guidelines](https://www.gbif.org/citation-guidelines).
