### ISSUE TITLE
1.9 million correct scientific names

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3377]
**1.9 million correct scientific names**

Massive new Canadian dataset has “Pacific herring” listed in scientificName, which mangles the taxonomic match. This looks like a simple and important fix to make.

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/58d190f48d9790952fd60c064b6356a6:0a156ca39bf5203229cecfb98c7c97201244428a4936026ddb43d7366d8b4d51767f85972ee0b0f6b1b376d955f530d1486adcf888d088114672623217a6efbf)
System: Mobile Safari 14.0.3 / iOS 14.4.2
Referer: https://www.gbif.org/dataset/78540eb6-95b0-4c3d-b362-03ed0bb5b2d3
Window size: width 375 - height 553
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-16T05:38:10.726Z',to:'2021-04-16T05:44:10.726Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-16T05:38:10.726Z',to:'2021-04-16T05:44:10.726Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
It looks like the scientificName and vernacularName fields are swapped by the publisher.

**Comment by AbbyBenson** [comment]
Did someone already reach out? If not I can message them on Slack to let them know.

**Comment by MattBlissett** [comment]
We haven't contacted them yet, so please do, thanks.

(We were distracted by the new "Footprint WKT invalid" flag, which seems to be incorrectly applied.)

**Comment by heidivanvliet** [comment]
I have fixed the problem. :)
