### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3379]
**Missing link**

On this page in the individualCount, organismQuantity, & organismQuantityType there is a note to link to a document instead of actually providing the link. I'll add a screenshot in a comment.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c6fe9c380cde1581424f43d3bc3ec4be:9ebbdd7588b3db5e9563e23d48d1a6b11199fd39d7f8df382b76fb66d052a6eff43eb4c59b3a1edf761a435147faa07a3a1777af795f08ee0d34e3dcd4d1248d)
System: Chrome 89.0.4389 / Windows 10.0.0
Referer: https://www.gbif.org/data-quality-requirements-occurrences
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-17T17:45:13.544Z',to:'2021-04-17T17:51:13.544Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-17T17:45:13.544Z',to:'2021-04-17T17:51:13.544Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by AbbyBenson** [comment]
<img width="400" alt="Capture" src="https://user-images.githubusercontent.com/7586150/115122045-16f2d300-9f73-11eb-950a-84b58a0ec6a7.PNG">

**Comment by ManonGros** [comment]
@dnoesgaard Could you take a look at the missing link on the https://www.gbif.org/data-quality-requirements-occurrences page?

**Comment by dnoesgaard** [comment]
I've added a link to https://www.gbif.org/dataset-classes#samplingevents instead.
