### ISSUE TITLE
Publisher page edit

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3386]
**Publisher page edit**

I'd like to edit the contact information for the CSU Desert Studies Center publisher page, both the general and technical points of contact. Specifically, I'd like to switch the people in these roles. Thanks!d

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3f7fc27daf3cc8365d942dd2d27593c6:b1dc8c15a66548f621eb3b46cfaee8adff00ea75598f8462d617025c7298b1608ca3d81ee6e86a37791dcdc0cb696703ff559c5f5896e84e07eca14b35faaf40)
System: Firefox 87.0.0 / Mac OS X 10.14.0
Referer: https://www.gbif.org/faq?q=publisher
Window size: width 1447 - height 860
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-23T22:08:48.766Z',to:'2021-04-23T22:14:48.766Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-23T22:08:48.766Z',to:'2021-04-23T22:14:48.766Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I updated the page and contacted the user. I told them to forward future requests to helpdesk.
