### ISSUE TITLE
Prices and indexes may need updates

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3389]
**Prices and indexes may need updates**

As we are active in the data papers space in 2021, this page may benefit from updates on prices and scores

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/72a1dc818bd1f05b2aac2bac9f92b2f4:f8f72ff21082149b1f7840c8863e00dc2df92515d0e0ecea2a9cc2938ff81e54a82936338c91ce273db1b3c8ff6782e5548cbeafccd721223fbe28b6d3555274)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/data-papers
Window size: width 1638 - height 815
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-26T13:15:17.021Z',to:'2021-04-26T13:21:17.021Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-26T13:15:17.021Z',to:'2021-04-26T13:21:17.021Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
JIFs are updated sometime in June so I suggest doing an update after that...
