### ISSUE TITLE
species name is not transferred correctly

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#339]
**species name is not transferred correctly**

species epithet from SCAN (idigBio) raw data is not transferred here. This is a widespread bug, at least within the UTCI data

-----
fbitem-occurrence1324904427
Reported by: stylianos-chatzimanolis@utc.edu
System: Safari 10.1.2 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/1324904427
Window size: width 1941 - height 1228
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T14:55:28.802Z',mode:absolute,to:'2017-08-17T15:01:28.802Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T14:55:28.802Z',mode:absolute,to:'2017-08-17T15:01:28.802Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: b65c0886-3c24-4ead-a93a-b89d2a676b10
publishingOrgKey: efcf5460-a06a-11d9-8ec2-b8a03c50a862

**Comment by ManonGros** [comment]
This looks solved.
