### ISSUE TITLE
Edit one line

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3390]
**Edit one line**

Update from Pensoft

Please replace:

When submitting a manuscript to BDJ, authors are requested to select the Biota of Russia collection. 

with:

When submitting a manuscript to BDJ, authors are requested at Step 3 of the Submission process to assign their manuscript to the Topical Collection [Biota of Russia](https://bdj.pensoft.net/topical_collection/59). To initiate the manuscript submission, remember to press the **_Submit to the journal_** button.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/b6532a7f89a47db6243994fee0b017fd:ceccc3cb441404d97bc3330b852c0a43c23efe1ab6808ed8a01cc25033990f428206296aefab5e4a2564d27f1d2901fbdad3ebbde2613b43dc9d6fffab525374)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/news/HdDwtyv9jjrvG99OSHsP6/call-for-data-papers-describing-datasets-from-russia
Window size: width 1638 - height 815
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-26T14:41:19.743Z',to:'2021-04-26T14:47:19.743Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-26T14:41:19.743Z',to:'2021-04-26T14:47:19.743Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Sorry for the delay, this was flagged incorrectly. Fixed now!
