### ISSUE TITLE
I would like to know how I can edit the contact details of the organization. The person who is in administrative point is no longer the same and I would like to update the information.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3391]
**I would like to know how I can edit the contact details of the organization. The person who is in administrative point is no longer the same and I would like to update the information.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ca3b3f775128ebf694e690ad71c790c4:94f17dd874dd303031ed097654b69348326cf19fa6a563c632bb5d0569004fd3c96410ec9f4c62aae59b82ae18973e2284979344246aae38eccb67efccba2e55)
System: Chrome 90.0.4430 / Mac OS X 10.12.6
Referer: https://www.gbif.org/user/profile
Window size: width 1280 - height 627
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-26T14:54:40.589Z',to:'2021-04-26T15:00:40.589Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-26T14:54:40.589Z',to:'2021-04-26T15:00:40.589Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Please send the updates that you would like to see on the organization page to helpdesk@gbif.org. If possible, please CC at least one of the current contact in the email.

> Replied by email
