### ISSUE TITLE
I would like to know how I can edit the contact details of the organization. The person who is in administrative point is no longer the same and I would like to update the information.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3392]
**I would like to know how I can edit the contact details of the organization. The person who is in administrative point is no longer the same and I would like to update the information.**

I would like to know how I can edit the contact details of the organization. The person who is in administrative point is no longer the same and I would like to update the information.
Can you contact me at melysa_gm@yahoo.es

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/da668c6aca26e4ed92d49823fee2ac88:f71cc0d01153d45118a21192de2a4b5c858af3147f6412d16a81723b8b09bc5a7a509e0845fb9adf4fb47b0aa7a7a76f134b12e3fa7382ab70aea0654001e74a)
System: Chrome 90.0.4430 / Mac OS X 10.12.6
Referer: https://www.gbif.org/user/profile
Window size: width 1280 - height 627
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-26T14:57:28.257Z',to:'2021-04-26T15:03:28.257Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-26T14:57:28.257Z',to:'2021-04-26T15:03:28.257Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
User contacted.
