### ISSUE TITLE
dataset with "Unspecified" license doesn't show in dataset search

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3395]
**dataset with &quot;Unspecified&quot; license doesn&#39;t show in dataset search**

In other words, this dataset doesn't show here: https://www.gbif.org/dataset/search?publishing_org=67b2263f-6990-4d9d-b32b-20aa72ef4fbc&license=UNSPECIFIED&license=UNSUPPORTED

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/d7f5663f97b445aa51f2ac21aabfe8cf:b7280142fcf4e450979e18711d5f1ca75ecce5c70e8b01348eff592f8b20141f273beb7aa445c0da5b427a985137177a2fb926056f50fc55e6e2ebc0dc70aabb)
System: Safari 14.0.3 / Mac OS X 10.15.6
Referer: https://www.gbif.org/dataset/0745302b-927a-4384-8459-dc1a56720c67
Window size: width 1353 - height 788
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-27T07:37:17.379Z',to:'2021-04-27T07:43:17.379Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-27T07:37:17.379Z',to:'2021-04-27T07:43:17.379Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
This is not a UI issue, but related to the API
https://api.gbif.org/v1/dataset/search?license=UNSPECIFIED

**Comment by fmendezh** [comment]
this seems to be working now
