### ISSUE TITLE
Expose authors from citation in API

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#3398]
The dataset pages currently have a highlighted list of people in the top. 

Example https://www.gbif.org/dataset/75956ee6-1a2b-4fa3-b3e8-ccda64ce6c2d
shows `Dutrève Bruno * Robert Solène * Thomas Milon  * Anaïs Just`

And then we have the citation string in the bottom which reads
```
citation: {
  text: Bruno D, Solène R (2016). INPN - Données flore des CBN agrégées par la FCBN. Version 1.2. UMS PatriNat (OFB-CNRS-MNHN), Paris. Occurrence dataset https://doi.org/10.15468/omae84 accessed via GBIF.org on 2021-04-27.
}
```

Shouldn't they be the same? Could we extend the API to return
```
citation: {
  text: Bruno D, Solène R (2016). INPN - Données flore des CBN agrégées par la FCBN. Version 1.2. UMS PatriNat (OFB-CNRS-MNHN), Paris. Occurrence dataset https://doi.org/10.15468/omae84 accessed via GBIF.org on 2021-04-27.
  people: [
    "Bruno D", "Solène R" // possible as objects along with the contact Key from the API and their roles?
  ]
}
```

Then we can reuse the code used in the API.

@dschigel you provided the specifications for the list of people in the UI (top of the page), do you see any issues in using the people from the citation string instead?

**Comment by dschigel** [comment]
I am not sure how the the list of authors in the top of the page is generated, we may have discussed this with @ahahn-gbif? Is there a formula for the display at the top of the page? There is a for the [citation](https://www.gbif.org/faq?question=how-is-the-dataset-citation-text-auto-generated) in the bottom. Here is the choice as publisher sees it: you prepare metadata in the IPT or other source system and you add people with a range of roles. All these people and all these roles are displayed under Contacts, but only some of them are use for the citation. Which roles are shown at the top of the page? All roles? Selected roles, which and why? There must be some past logic behind the current display, but I cannot recollect. in a nutshell: shall we sync the top of the page with all contacts or only with roles used in citation?

**Comment by dschigel** [comment]
In other words, should dataset authorship and recommended citation be the same? Two use cases: 1) the GBIF dataset is re-displayed in e.g. a thematic hosted portal. You probably want lossless reflection of the GBIF display at the alternative portal 2) some one need to access the as-published dataset with its recommended citation for new analysis, for reuse. Only recommended citation matters. I also flagged earlier that citation formatting rules of the data reuse will dictate the look of the citation, and GBIF recommendation (order of citation elements, punctuation, etc. )will be likely ignored - but not the elements themselves, such as DOI and whom GBIF shows as authors. Typing this, I think there are many benefits in making dataset authorship and recommended citation to display the same roles and people. If we apply the citation formula to the dataset authors in the top part, how many names will end up in Contacts sections only? I wonder if we would be cutting the authors strings by 5% or by 50%. In any case, what I like is that authors and citation strings are generated according to metadata supplied.

**Comment by ahahn-gbif** [comment]
I would support consistency between both. I don't remember any discussion or explicit decision - the top-of-the-page list seems to just name everybody in the contacts section, nothing more or less.

**Comment by dschigel** [comment]
Thanks @ahahn-gbif. Great that we agree that citation formula should apply also to the top of the dataset pages. A cautious implementation would start from estimate of % names to disappear from the top page positions. Likely a minor change, and I would guess manly administrative contacts would stop looking like dataset authors. I wonder if there are some regional sensitivities there. Even if there are, this is a healthy move: there is a difference in contact transparency (many roles in Contacts section) and decorative, unjustified co-authorship, which is a bad thing.

**Comment by MortenHofft** [comment]
**Top list**
The list in the top was created some months before we generated the citation (the one from the bottom and the API) as far as i remember. @dschigel created the rules and I tried to implement it - it went back and forth a couple of times. 

**Citation list of authors**
I think that the subsequent work where we added it to the API was done as a collaboration between Christian G, @dschigel and @ahahn-gbif. But the top list remained the same.

**Future**
I'm about to implement a dataset page for the hosted portals. I can either replicate the code from the portal or we can extend the API for benefit of all future websites.

I would just like to kill code that seem like a silly duplicate. Especially since the code used for the citation footer is of a later date and probably more worked through.

**Comment by MortenHofft** [comment]
Thank you - in that case I will create an issue in the registry to expose the ordered list of authors/people in the API as they should appear when presenting the dataset.

**Comment by dschigel** [comment]
Thanks @MortenHofft, as said, no memories on the top of the pages discussion & rules, perhaps there is little point to review those (though I am available). Sound like a good plan to me. It would make sense to first make sure that top string and citation at GBF.org are based on the same formula, and then make sure (choose the tech) that GBIF.org and derived portals have the same sequences of dataset authors, plus dataset DOIs are the same no matter where datasets are displayed. The recommended citation in the hosted portals will likely look a bit different as you won't be able to say "accessed via GBIF.org" anymore at the hosted portal.

**Comment by MortenHofft** [comment]
No point in reviewing it. Especially not since there is a more than fair chance that I mis-implemented it. I'm just happy to discard it and use something from the API instead.
