### ISSUE TITLE
Sort by name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3401]
**Sort by name**

List of journals is alphabetic, but not the lines in the bottom of the table

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/ea25f25896ddc512aa80c592510b0557:b48c3435a160d32b5b8d696db2036f9a5c8c36b180026f286435ba388fb4591d37035cf4ae4344cfe912e26d978d38e50c0610177859b3fdf80ea4a8080323ae)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/data-papers
Window size: width 1627 - height 827
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-28T14:15:32.357Z',to:'2021-04-28T14:21:32.357Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-28T14:15:32.357Z',to:'2021-04-28T14:21:32.357Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
I think I made the decision to do OA journals first, then the rest which explains the sorting order. I'm happy to change this, if you think?

**Comment by dschigel** [comment]
I did not realize we have non-OA data journals at all in the GBIF web list, this an important parameter. If those non-OAs are in minority, should we have them at all in a GBIF page, adding @timhirsch @kcopas for opinions.

**Comment by dnoesgaard** [comment]
Fwiw, they're not non-OA, but OA-optional.

**Comment by dschigel** [comment]
Thanks in such case they can stay in I guess... If you don't want all alphabetic and extra field on OA details not justified, perhaps you could separate the bottom lines on optional OA journals in a separate table? This way we will visually stress the OA principles of GBIF through table headings. But is it a small thing, happy with any setup now it is clear why list is non-alphabetic.

**Comment by dnoesgaard** [comment]
I thought it was pretty clear?

![Screenshot 2021-05-05 at 12 36 39](https://user-images.githubusercontent.com/21358085/117129165-a505f080-ad9e-11eb-85a6-5cf894c6897e.png)

**Comment by dschigel** [comment]
Age comes with decreased eyesight
