### ISSUE TITLE
this is not a Melastomataceae, and NOT Adelobotrys adscendens!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3402]
**this is not a Melastomataceae, and NOT Adelobotrys adscendens!**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e8d370dc273a025923bdd8e776809ea2:107137aae90cd8d2e86002a9e2598fa402b91ee6ca22525a6ca3fc2da7c5cc4fec5b6eac46795246e335c9389a23ce7ca29892d05e18a5132d647a4b371a9207)
System: Firefox 87.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2644922467
Window size: width 1920 - height 918
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-29T09:27:51.967Z',to:'2021-04-29T09:33:51.967Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-29T09:27:51.967Z',to:'2021-04-29T09:33:51.967Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by ManonGros** [comment]
The record comes from Pl@ntNet. I voted the "unidentified" but I am afraid that without an alternative identification, the name will remain.
I have contacted Pl@ntNet to ask.
