### ISSUE TITLE
A new species Scolopendra alcyona Tsukamoto & Shimano, 2021 (Japanese name: リュウジンオオムカデ; English name: Halcyon giant centipede) was described.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3404]
**A new species Scolopendra alcyona Tsukamoto &amp; Shimano, 2021 (Japanese name: リュウジンオオムカデ; English name: Halcyon giant centipede) was described.**

A new species Scolopendra alcyona Tsukamoto & Shimano, 2021 (Japanese name: リュウジンオオムカデ; English name: Halcyon giant centipede) was described.
Please add this taxon to the list under Scolopendra.

-----

Github user: @RyoKuwa
User: [See in registry](https://www.gbif.org/api/feedback/user/3d33fd77ce97a6eb66ae7f85659913b3:9a7b6d4dea19d7440ddd3589cb3fdc69d6ea6d399648e6736b263b1df7e58826ab895a581e14f235fae9ec451532b15837b17a05cbb03ae398746236adefe62bc6c80697b8cc8d616e7e6df6458e0f45)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/ja/species/2231802
Window size: width 1536 - height 850
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-01T13:12:32.350Z',to:'2021-05-01T13:18:32.350Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-01T13:12:32.350Z',to:'2021-05-01T13:18:32.350Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by RyoKuwa** [comment]
A new amphibious species of the genus Scolopendra Linnaeus, 1758 (Scolopendromorpha, Scolopendridae) from the Ryukyu Archipelago and Taiwan
https://doi.org/10.11646/zootaxa.4952.3.3

**Comment by ManonGros** [comment]
Now in the GBIF backbone: https://www.gbif.org/species/11166877
