### ISSUE TITLE
Link to Global Ecology and Biogeography 404

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3406]
**Link to Global Ecology and Biogeography 404**

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/cb94e47f9be4ded3fbd4227452d0da5f:03c17241a0b71a4ad1c321dc9026673ac418deb6ce88b40c0c439cf6f8e78ce97fb22fa102d7636cee6ca2842f359d9b8edc18714b5642c335c34d2e999475c9)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/data-papers
Window size: width 1638 - height 815
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-03T10:06:15.882Z',to:'2021-05-03T10:12:15.882Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-03T10:06:15.882Z',to:'2021-05-03T10:12:15.882Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
fixed
