### ISSUE TITLE
Possible incorrect scientific name authorship - Dictamnus fraxinella Pers.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3408]
**Possible incorrect scientific name authorship - ~Dictamnus fraxinella Link~ Dictamnus fraxinella Pers. (see last comment)**

This name comes from the The World Checklist of Vascular Plants (WCVP) and cannot be found anywhere else:
https://www.gbif.org/species/search?q=Dictamnus%20fraxinella%20Link&advanced=1

The issue was originally reported on Helpdesk.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/2b59709cabe540e9181ecf1e30c4593b:cb73315b4dfa514c7b687798823c196dfd47dc1ad5844142f83f46d4743085a278d677b5b9473fe10355782063e4086546a8e3a1a89c34a7997b97f8cf4d08a4)
System: Safari 14.0.3 / Mac OS X 10.15.6
Referer: https://www.gbif.org/species/10945630
Window size: width 1353 - height 788
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-04T11:16:19.977Z',to:'2021-05-04T11:22:19.977Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-04T11:16:19.977Z',to:'2021-05-04T11:22:19.977Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@mdoering do you know whom I can contact for potential mistakes in [The World Checklist of Vascular Plants (WCVP)](https://www.gbif.org/dataset/f382f0ce-323a-4091-bb9f-add557f3a9a2)?
The email addresses on the dataset page seem quite generic and I see that they don't host the checklist.

**Comment by mdoering** [comment]
Kew plans to host the list themselves shortly, but until then you can email them via bi address given.
It is the same on their official site: https://wcvp.science.kew.org/feedback

**Comment by ManonGros** [comment]
Thanks! I contacted them by email.

**Comment by ManonGros** [comment]
I got a reply from their content editor:
> Pers. did not validly publish Dictamnus fraxinella in 1805:
https://www.biodiversitylibrary.org/page/235249#page/476/mode/1up
he tried to publish Dictamnus fraxinella var. purpureus
which is also not validly published as the species had not been validly published.
 
> Link (1821) is the first to validate the species name Dictamnus fraxinella

So it seems like Link is the correct name an not Dictamnus fraxinella Pers. (https://www.gbif.org/species/5593085).
