### ISSUE TITLE
The contact email address for the UK PDC has changed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3412]
**The contact email address for the UK PDC has changed**

Hi,
I work for the UK Polar Data Centre and we've just changed our contact email address. Please can you update this page to remove polardatacentre@bas.ac.uk and replace it with our new email address: PDCServiceDesk@bas.ac.uk. Thank you.
Kind regards,
Alysa Hulbert

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c0f74c713b002e66f0b64ba1e4f0c584:96e0881499906c0b25993677368f36e8cd2610316b939f7e11da79668bfe06ce1dcca22e6da708142cf352a20ac1107bb2108bfb6b216e9b3a0bb2c956566a8c)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/80420c96-95d0-44eb-9f77-339ac92051fb
Window size: width 1920 - height 1057
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-06T10:37:26.224Z',to:'2021-05-06T10:43:26.224Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-06T10:37:26.224Z',to:'2021-05-06T10:43:26.224Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
PDC page updated and user contacted.
