### ISSUE TITLE
A new species Haustorioides furotai Ogawa, 2021 was described.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3413]
**A new species Haustorioides furotai Ogawa, 2021 was described.**

A New Species of the Sand-burrowing Dogielinotidae, Haustorioides furotai, from Tokyo Bay, Japan (Crustacea: Amphipoda)
https://doi.org/10.12782/specdiv.26.65

It seems to be related to WoRMS and COL.

-----

Github user: @RyoKuwa
User: [See in registry](https://www.gbif.org/api/feedback/user/ba795dbff1d53686e1971fe41a042a0a:a68dd68f84316fece4dbf9b65e1256f6f54a26888e8e0c0edb544ce32c03a0dd2aa447a4d0d5e0ad2c502c04317e4b48f23ae143d41b34c31669e9ceabd39ce7c7fba6daccdd948b248b65f4a6e484cd)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/ja/species/2217512
Window size: width 1536 - height 850
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-06T22:48:46.717Z',to:'2021-05-06T22:54:46.717Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-06T22:48:46.717Z',to:'2021-05-06T22:54:46.717Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The species seems to have been included in the Catalogue of Life: https://www.catalogueoflife.org/data/taxon/8H78Z so I expect it to become available on GBIF with the next GBIF backbone update.

**Comment by ManonGros** [comment]
Available in the new backbone: https://www.gbif.org/species/11180009
