### ISSUE TITLE
Asteraceae

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3416]
**Asteraceae**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/04c7c3650927f3662b388f5f55ee8913:7d8ebcba6e3937f5bbd459d32783786b748bcb69f4bf0a0b7a35042b7184140bc107948b8f2c58c8f0847f2f9d125d6c099e5a6693e5de8cf7a4747fe84d817f)
System: Chrome 90.0.4430 / Windows 7.0.0
Referer: https://www.gbif.org/species/3065?vnOffset=10
Window size: width 1366 - height 625
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-11T19:39:08.503Z',to:'2021-05-11T19:45:08.503Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-11T19:39:08.503Z',to:'2021-05-11T19:45:08.503Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
User contacted for more information. If no reply before June 1, 2021 then remove issue.
