### ISSUE TITLE
ingestion of dataset skips some authors

### ISSUE THREAD

**Issue by DimEvil** [gbif/portal-feedback#3417]
The author Frank Van de Meutter is not seen on the portal, however he is in the registry: https://registry.gbif.org/dataset/22211949-9a6e-445f-86c0-6a0e019bc055/contact

Link to dataset on IPT, Frank is there
https://ipt.inbo.be/resource?r=alien-scheldt-checklist

Link to GBIF, Frank dissapeared
https://www.gbif.org/dataset/22211949-9a6e-445f-86c0-6a0e019bc055

I don't have a clue on what the reason could be.

**Comment by MortenHofft** [comment]
Frank is in the API https://api.gbif.org/v1/dataset/22211949-9a6e-445f-86c0-6a0e019bc055
But not on the website.

Frank is listed with the same userId as Jan Soors and hence the 2 are considered to be one and only one of them show. The IPT, Eml and the API will list the same person for multiple roles, the website tries to group those roles into on *person* it does so based on userIds when present or else a combination of emails and names. In this case there is a clear statement in the data that the 2 are in fact one person: the have the same userID.

@DimEvil let us know if you believe this approach is problematic, but for now I will consider this a data issue and close this ticket.

**Comment by DimEvil** [comment]
I'm ok with this.  An error was made in the ORCID ID's. (I missed this...) and it i fixed now!
