### ISSUE TITLE
Taxonomic generalization is not enough

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3418]
**Taxonomic generalization is not enough**

Generalizing these to the genus Homo doesn't make these records any more usable.

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/71502f8a6ef0247b2478ad84c0f5fb54:f80b622f24881f5aa3345f4080d76582afac764b596cf418980cd51410c57126f7487d0120a28fd880c762ff781eebc391882590d6eeed8a9bfd14d066f2740b)
System: Firefox 88.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=84a649ce-ff81-420d-9c41-aa1de59e3766&recorded_by=Ned%20LOYND&taxon_key=1&advanced=1
Window size: width 1983 - height 1250
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-18T11:59:04.898Z',to:'2021-05-18T12:05:04.898Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-18T11:59:04.898Z',to:'2021-05-18T12:05:04.898Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by MattBlissett** [comment]
It does mean they skip the ALA's export filters for _Homo sapiens_.

CC @djtfmartin.

See also https://www.gbif.org/occurrence/gallery?dataset_key=84a649ce-ff81-420d-9c41-aa1de59e3766&taxon_key=2436435

**Comment by jhnwllr** [comment]
I will contact the publisher.
