### ISSUE TITLE
I can't download the csv file.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#342]
**I can&#39;t download the csv file.**

I made a polygon to select ocurrences (2 millons), the csv file is 136 mb, but i can´t download this file. Perhaps the polygon has to many vertex. 
geometry=POLYGON%20((-116.98242187499999%2032.52458504923801,%20-132.890625%2032.74662747466574,%20-132.890625%2011.41972981423215,%20-84.90234375%2011.299091230593271,%20-89.20898437499999%2014.0683833118158,%20-92.724609375%2015.059393614699374,%20-93.9990234375%2016.412902065461612,%20-96.1962890625%2016.202015517411237,%20-98.4814453125%2016.5814469873171,%20-101.9970703125%2018.216829462816218,%20-103.35937499999999%2018.717016588574673,%20-105.2490234375%2020.16734919430541,%20-104.853515625%2021.726845216584174,%20-106.171875%2023.63244728408054,%20-108.720703125%2026.06467883641701,%20-110.7861328125%2028.331461588646953,%20-111.97265625%2029.21738484658348,%20-112.8955078125%2030.928616463626792,%20-113.5986328125%2031.75432837019855,%20-114.9169921875%2031.940975861541617,%20-115.1806640625%2031.21656002927879,%20-114.67529296874999%2029.796797985361014,%20-113.115234375%2028.279228628627674,%20-112.43408203124999%2027.229233686607184,%20-111.81884765624999%2026.30720393958023,%20-111.4892578125%2026.090335193162165,%20-110.830078125%2024.760799135572405,%20-110.8740234375%2024.42114369064522,%20-110.21484375%2024.04044437367387,%20-109.97314453125%2023.879810568442664,%20-109.51171875%2023.295847107320572,%20-109.92919921875%2022.99278387204715,%20-110.5224609375%2023.899900731994176,%20-112.0166015625%2024.98008324458478,%20-112.08251953125%2026.129795897440964,%20-113.37890625%2026.974954341175273,%20-114.19189453125%2027.42443912774298,%20-113.818359375%2028.007981990389354,%20-114.58740234375%2029.242311890868855,%20-115.59814453125001%2029.93018293428911,%20-116.52099609375%2031.74124868178526,%20-116.98242187499999%2032.52458504923801))

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
Reported by: heimndal@hotmail.com
System: Firefox 54.0.0 / Windows 8 0.0.0
Referer: https://www.gbif.org/occurrence/download?basis_of_record=OBSERVATION&basis_of_record=LITERATURE&basis_of_record=PRESERVED_SPECIMEN&basis_of_record=HUMAN_OBSERVATION&basis_of_record=MACHINE_OBSERVATION&basis_of_record=MATERIAL_SAMPLE&country=MX&has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON%20((-116.98242187499999%2032.52458504923801,%20-132.890625%2032.74662747466574,%20-132.890625%2011.41972981423215,%20-84.90234375%2011.299091230593271,%20-89.20898437499999%2014.0683833118158,%20-92.724609375%2015.059393614699374,%20-93.9990234375%2016.412902065461612,%20-96.1962890625%2016.202015517411237,%20-98.4814453125%2016.5814469873171,%20-101.9970703125%2018.216829462816218,%20-103.35937499999999%2018.717016588574673,%20-105.2490234375%2020.16734919430541,%20-104.853515625%2021.726845216584174,%20-106.171875%2023.63244728408054,%20-108.720703125%2026.06467883641701,%20-110.7861328125%2028.331461588646953,%20-111.97265625%2029.21738484658348,%20-112.8955078125%2030.928616463626792,%20-113.5986328125%2031.75432837019855,%20-114.9169921875%2031.940975861541617,%20-115.1806640625%2031.21656002927879,%20-114.67529296874999%2029.796797985361014,%20-113.115234375%2028.279228628627674,%20-112.43408203124999%2027.229233686607184,%20-111.81884765624999%2026.30720393958023,%20-111.4892578125%2026.090335193162165,%20-110.830078125%2024.760799135572405,%20-110.8740234375%2024.42114369064522,%20-110.21484375%2024.04044437367387,%20-109.97314453125%2023.879810568442664,%20-109.51171875%2023.295847107320572,%20-109.92919921875%2022.99278387204715,%20-110.5224609375%2023.899900731994176,%20-112.0166015625%2024.98008324458478,%20-112.08251953125%2026.129795897440964,%20-113.37890625%2026.974954341175273,%20-114.19189453125%2027.42443912774298,%20-113.818359375%2028.007981990389354,%20-114.58740234375%2029.242311890868855,%20-115.59814453125001%2029.93018293428911,%20-116.52099609375%2031.74124868178526,%20-116.98242187499999%2032.52458504923801))
Window size: width 1280 - height 868
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T17:54:36.639Z',mode:absolute,to:'2017-08-17T18:00:36.639Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-17T17:54:36.639Z',mode:absolute,to:'2017-08-17T18:00:36.639Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
Probably https://github.com/gbif/occurrence/issues/8

**Comment by MortenHofft** [comment]
User informed that the API is now functional
