### ISSUE TITLE
add button to suggest event

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3422]
**add button to suggest event**

We're collecting event suggestions from the community through a simple form. Could we add a  button (perhaps with a plus icon?) next to "Subscribe to calendar" simply linking to the page at https://www.gbif.org/suggest-event

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/5b0e811762217e169f149506abf98dd9:e1440cc5705be10a6bce866d19a00818b11ce7e1067943bcd593cf3c36118e07ff96cf95644647c365974cdfa01b98d82405c1d3d01e316246ee100e919da12d)
System: Chrome 90.0.4430 / Mac OS X 10.15.7
Referer: https://www.gbif.org/resource/search?contentType=event
Window size: width 1510 - height 1243
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-19T11:31:42.395Z',to:'2021-05-19T11:37:42.395Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-19T11:31:42.395Z',to:'2021-05-19T11:37:42.395Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
fyi @akristensen

**Comment by akristensen** [comment]
@thomasstjerne would be great if it could be up an running for our GBIF newsletter going out mid June, so we can promote the new feature there. Thanks Annie
