### ISSUE TITLE
Camirus porosus (Germar, 1839) and Acantholomidea porosa Germar, 1839 are synonyms. See Eger & Lattin (1995): https://www.jstor.org/stable/25010192?seq=1

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3426]
**Camirus porosus (Germar, 1839) and Acantholomidea porosa Germar, 1839 are synonyms. See Eger &amp; Lattin (1995): `https://www.jstor.org/stable/25010192?seq=1`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4bed27630220f340fedfaaa0eafb714f:785c0abe0286d83aa5a4405ca43391aa470e16fcb054f18253b1428d75b2ab37c51a91414af0acb531a3ec3f1ba3af6f4b3bc819734e8336e7627947cfdba57f)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/species/5160035
Window size: width 1219 - height 673
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-20T18:27:03.696Z',to:'2021-05-20T18:33:03.696Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-20T18:27:03.696Z',to:'2021-05-20T18:33:03.696Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
The name Camirus porosus (Germar, 1839) comes from ITIS (https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=109055#null) but doesn't exist in the CoL.
[Acantholomidea porosa Germar, 1839](https://www.gbif.org/species/10670262) cam from a PLAZI treatment but isn't in ITIS.

I assume that Acantholomidea porosa Germar, 1839 should be added to ITIS. I have contacted them to propose the change.

**Comment by ManonGros** [comment]
It looks like the issue is solved in the new backbone.
