### ISSUE TITLE
False synonymization - Papilio polixenes

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3427]
**False synonymization - Papilio polixenes**

Papilio polixenes (Papilionidae) is falsely considered a synonym of Oeneis polixenes (Nymphalidae)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/aa16f798bf349f6f86645d8f5030317d:8c476a4d934d630409429913a41e934df9e55ae5582d12a9d55b36af253e8c678365da6f9679b65c5c01785b2751ad5e570b8d3f330ad3e061a0034b6f81e5ac)
System: Firefox 88.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/1937816
Window size: width 2144 - height 1016
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-21T08:40:49.054Z',to:'2021-05-21T08:46:49.054Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-21T08:40:49.054Z',to:'2021-05-21T08:46:49.054Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Solved in the newest backbone
