### ISSUE TITLE
Institution Code match fuzzy or mismatch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3429]
**Institution Code match fuzzy or mismatch**

The intermountain Herbarium (collection code UTC) is part of Utah State University (referred to as USU in Utah). USU is sometimes interpreted as "USU Utah State University" by GBIF - and labeled as "Institution match fuzzy" and "Institution collection mismatch". 

The metadata, as we record them, show the collection code at UTC, that being the internationally recognized code for the COLLECTION. There is no internationally recognized CODE for the institution, but the university is known as USU in Utah (and probably elsewhere in the US), but there is no official code. Its NAME is Utah State University. From where I sit, the problem has been created by GBIF. Is there any way to resolve this? We are making an effort to address the issues identified by GBIF, hence my inquiry.  Does GBIF have a field "Institutionname" that could be used to clarify the meaning of the code as we use it?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5c067d000351feaf4c839c6da5455771:0b25f32f56fde474debb9389f071da8a3fc0d0d0e8efb54f04bd450aa1f709812105e78b8c42a9f3e154dfeab2d069053354bffe4fa0b30c85ea0e47ffc51667)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1986910358
Window size: width 1536 - height 730
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-24T11:17:09.467Z',to:'2021-05-24T11:23:09.467Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-24T11:17:09.467Z',to:'2021-05-24T11:23:09.467Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7827f68d-c981-4023-bace-288a03434044
publishingOrgKey: 4c0e9f60-c489-11d8-bf60-b8a03c50a862

**Comment by ManonGros** [comment]
Replied by email:
> These flags are the result of our attempt to link the GBIF Specimen records to [GRSciColl](https://www.gbif.org/grscicoll). They are generated when our system is unable to find a match in GRSciColl based on what is given in the data. To avoid the record being flagged, we need to either update the data to match what is available in GRSciColl or update GRSciColl to use what is given in the data.
 
> We have [an FAQ](https://www.gbif.org/faq?question=how-can-i-improve-the-matching-of-occurrence-records-with-grscicoll) explaining what to put in the data to help the GRSciColl matching.
