### ISSUE TITLE
Problem with a interpreted Elevation

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#3431]
I have a small question about interpreted Elevation, just to be sure.

One of our publishers recive a report that a plant have an incorrect elevation, is not possible for that plant to live in high altitudes. The original record didn't have an elevation because is an old record and the field is empty.

![image](https://user-images.githubusercontent.com/63795703/119538291-946ae980-bd50-11eb-9272-d5edccf25096.png)
The specimen with the problem is this https://www.gbif.org/occurrence/3032729981 

My question is if there is a way to stop the interpretarion for this specific specimen?
I almost sure that there is no way, because is an automatic process. But the publisher want to be sure about that.

Thanks in advance a have a wonderful day,

**Comment by MattBlissett** [comment]
Hi Esteban,

Scroll a little further down on that record, and you will see the field "Maximum elevation in metres" and "Minimim elevation in metres".  

GBIF's occurrence API is based on an older version of Darwin Core (I think) with only an "Elevation" term, which it calculates from the supplied Minimum/Maximum Elevation In Metres terms if they are present, as here.
