### ISSUE TITLE
Update contact information Western Australian Herbarium (publisher)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3436]
**Update contact information Western Australian Herbarium (publisher)**

Description: https://www.dpaw.wa.gov.au/plants-and-animals/wa-herbarium
Admin Contact: Shelley James - herbarium@dbca.wa.gov.au - +61 (08) 9219 9000
Technical contact: Ben Richardson - ben.richardson@dbca.wa.gov.au - +61 (08) 9219 9000

Thanks

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/16b357d57842b100740def6bcd6c9414:cbac24d6c96e9c847705aca7ef7e028feb306e4796f77e1d3ccac927aac00303b5424da6342f43f8ae9f8ddab3f2273e6cb35d07c253cd9ea3195ebcde42d5d2)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/9d23a1e0-5388-11df-a59b-b8a03c50a862
Window size: width 1280 - height 578
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-01T10:18:05.570Z',to:'2021-06-01T10:24:05.570Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-01T10:18:05.570Z',to:'2021-06-01T10:24:05.570Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Contacted them so one of the current contacts would confirm the change.

**Comment by ManonGros** [comment]
Organization page updated.
