### ISSUE TITLE
How do I search  for GBIF applied mtadata in the portal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3437]
**How do I search for GBIF applied mtadata in the portal**

eg gbifID, datasetKey. How  can I use these identifiers to locate records/datasets using the GBIF portal. The fields don't appear in any search forms.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/788b87c1315681a5e10cc0e169b123b3:7aa1e6981bfd6f418262cfe2591edf9b98afaa0f796e3c810248a67889672e80060132f8206041cae1a068afe8593158738a20af379c9dba6a4116dfa021cd8d)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?q=2418712840
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-01T22:11:55.407Z',to:'2021-06-01T22:17:55.407Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-01T22:11:55.407Z',to:'2021-06-01T22:17:55.407Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> There is no filters for gbifIDs and datasetKeys in the portal because those are internal identifiers used in our URLs.
> *	To see a particular occurrence given a gbifID, you will need to use the prefix `https://www.gbif.org/occurrence/`. For example, the link to the occurrences with the gbifID `2418712840` is: https://www.gbif.org/occurrence/2418712840
> *	To access the dataset page of a dataset given a datasetKey, you will have to use the prefix `https://www.gbif.org/dataset/`. For example, the link to the dataset with the datasetKey `5d7f5915-0561-4107-aa20-20a4267c203f` is https://www.gbif.org/dataset/5d7f5915-0561-4107-aa20-20a4267c203f
