### ISSUE TITLE
Diploderma drukdaypo

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3438]
**Diploderma drukdaypo**

Diploderma drukdaypo, a key protected species in China discovered in 2019, does not exist, please add this species.

https://en.wikipedia.org/wiki/Diploderma_drukdaypo,

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/65a163db5ecc181c5f571ae6359051e0:bafd4b8503fe8e356301cbd527d412a22013a80c52097ecba8c1918dd632d82ffad02de1fecac81f4b6ab44005e978b399312f8963fd674311c2b0a9344375dc)
System: Chrome 90.0.4430 / Mac OS X 10.15.7
Referer: https://www.gbif.org/zh/user/confirm
Window size: width 1817 - height 881
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-02T02:17:28.168Z',to:'2021-06-02T02:23:28.168Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-02T02:17:28.168Z',to:'2021-06-02T02:23:28.168Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
Present in COL and will be added in next backbone update. 
https://www.catalogueoflife.org/data/taxon/8GPM9

**Comment by ManonGros** [comment]
Available in the new backbone: https://www.gbif.org/species/11211490
