### ISSUE TITLE
typo on contact-us

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#344]
**typo on contact-us**

"The offices fo the GBIF"

-----
fbitem-4fe74f928479e92cdee3d84f464947d51931306e

System: Chrome 60.0.3112 / Mac OS X 10.11.6
Referer: https://www.gbif.org/contact-us
Window size: width 2064 - height 1119
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T00:16:47.822Z',mode:absolute,to:'2017-08-18T00:22:47.822Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T00:16:47.822Z',mode:absolute,to:'2017-08-18T00:22:47.822Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
Fixed.
