### ISSUE TITLE
Can you help me with the gbif API?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3442]
**Can you help me with the gbif API?**

I have experimented with various endings on the base URL (https://api.gbif.org/v1/) but can not understand how to control the output to give me what I want. My immediate aim is to obtain a list of all the species' accepted scientific names within a given taxon. I have not been able to find a beginner's guide to the API.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/54707d01072a8feeecd48aef774deab7:bf39d634e61722e90645a97a294d5843799bdf168370a74c4f4ab346a74a021cb8f5d6cfb684ebc8963bc3616da8a1b190def6763fd9213c7321dad4ba7b4675)
System: Firefox 80.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/developer/summary
Window size: width 1600 - height 747
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-02T17:35:46.860Z',to:'2021-06-02T17:41:46.860Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-02T17:35:46.860Z',to:'2021-06-02T17:41:46.860Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
> I have not been able to find a beginner's guide to the API.

I see that you have already found the documentation. We are currently looking into migrating our documentation to another software stack. Could you describe what more you would like to see in terms of documentation?

> My immediate aim is to obtain a list of all the species' accepted scientific names within a given taxon

First of all you have to decide what checklist to use. GBIF mediate multiple checklists. And we build our own from merging those published. We call the latter for "the backbone"

It sounds like what you want to do is this in the UI:
https://www.gbif.org/species/search?rank=SPECIES&highertaxon_key=9778871&status=ACCEPTED

the equivalent in the API is 
https://api.gbif.org/v1/species/search?rank=SPECIES&highertaxonKey=9778871&status=ACCEPTED

You can use `limit` and `offset` params to page through the results.

Above is described in the API 
https://www.gbif.org/developer/species#searching

Hope that helps

> user informed per email

**Comment by stevespages** [comment]
That is great feedback to have.

I would really like to see an explanation of how to use the API aimed at people with a low level knowledge (but not none at all) of APIs and JSON and gbif. I was thinking that a handful of worked examples which showed how to interrogate the database(s) for certain types of information would be very useful. I think it would be particularly useful if these examples also showed where in the documentation the information for constructing the API search term URL was. I have given some examples below.

The example you gave could be expressed in prose and then explained how to construct the URL. One of many issues I am unsure about is where do I find the number for the highertaxonKey parameter corresponding to a particular taxon (you used 9778871 in your example)?

For a given search such as the example you gave is it possible to specify which information is returned. For example, if I only wanted one field for each species (eg the scientificName) and I did not want any of the other information for that species how would I go about that assuming it is possible in the first place?

Other examples than the one you gave could be: How do I find all the species in a given genus in France occurring at higher altitudes than 1000m.

I did spend some time looking at the description you suggested (https://www.gbif.org/developer/species#searching) and it was quite frustrating because I could see in principle that it seems to be describing a way I can construct URLs to answer questions using the database(s) but I just could not pin down the procedure sufficiently to be able to do it effectively.

I would have thought there would be quite a few people similar to me and it would be worth adding something in the documentation to help them but it may be that I am an unusual case!

Cheers!

**Comment by MortenHofft** [comment]
Thank you - that is useful feedback.

For now I will just answer your specific questions:

## where do I find the number for the highertaxonKey parameter corresponding to a particular taxon?

You use the species match API to find the taxonKey you are looking for. The documentation says

> Fuzzy matches scientific names against the GBIF Backbone Taxonomy with the optional classification provided. If a classification is provided and strict is not set to true, the default matching will also try to match against these if no direct match is found for the name parameter alone.

E.g. https://api.gbif.org/v1/species/match?verbose=true&kingdom=Plantae&name=Oenante
Which returns
```
{
  "usageKey": 3034893, // <==== this is the KEY
  "scientificName": "Oenanthe L.",
  "canonicalName": "Oenanthe",
  "rank": "GENUS",
  "status": "ACCEPTED",
  "confidence": 85,
  "note": "Similarity: name=75; authorship=0; classification=4; rank=0; status=1; nextMatch=5",
  "matchType": "FUZZY",
  "alternatives": [],
  "kingdom": "Plantae",
  "phylum": "Tracheophyta",
  "order": "Apiales",
  "family": "Apiaceae",
  "genus": "Oenanthe",
  "kingdomKey": 6,
  "phylumKey": 7707728,
  "classKey": 220,
  "orderKey": 1351,
  "familyKey": 6720,
  "genusKey": 3034893,
  "synonym": false,
  "class": "Magnoliopsida"
}
```

This is doing it using the species/match service. You could also use species/search instead. Or you could use the website to find it and copy it from the url.

## How do I find all the species in a given genus in France occurring at higher altitudes than 1000m.
That is more tricky - we can only tell you what occurrences (aka observations) there have been. And where the recorder wrote down the elevation (or the publisher inferred it from the coordinates).

In the UI that is 
https://www.gbif.org/occurrence/search?country=FR&elevation=1000,*&taxon_key=95&advanced=1&occurrence_status=present
in the API that is
https://www.gbif.org/api/occurrence/search?country=FR&elevation=1000,*&occurrenceStatus=present&taxonKey=95

Hope that helps you getting started

**Comment by stevespages** [comment]
Thanks for that information. I find the extract from the documentation very difficult to understand but I can see that using the UI can give me a clue with regard to some aspects. I really have very little idea of what the UI and the API can do and what it can not do. I imagine it is very powerful and can give the results to almost anything one would want to know about the data.

Please can you tell me if I can get it to just return a single field such as "scientificName" and if so how I would specify that. I realize I could extract that data from the JSON returned but feel it would be better if it were possible to discard the unwanted information earlier.

I have been playing around with the UI and the API today and feel I am making progress with your help: thanks!

**Comment by stevespages** [comment]
I thought I would explain my broader aim as it may make more sense of my questions.

I am trying to build a website were people can add the name of a plant and, using the phone's GPS, its position and a description and a photo(s). Then they can go to a webpage where the plants in the system are listed in order of their proximity to the phone. This could be useful for them in identifying plants in a park or garden. I am sure there are many services which already have these abilities but I feel I would like to make my own version as some details are quite important to me which I feel other services might lack. I have realized it would be unsatisfactory if people used different names for plants and spelt them wrong hence I wanted a list of species' names from gbif and only those names would be allowed to be entered by users of my service.

I am slightly worried that the list of possible species might be so large as to be a problem as I am not sure how big the list might be and also I am not sure how big a list my HTML based system of data input could cope with but I thought it would be worth playing around with to see if I can get a workable solution to constrain the data input.

**Comment by MortenHofft** [comment]
For those type of things one usually use a suggest service that are optimised for speed. We have one in the API `v1/species/suggest` - make sure to set the datasetKey to the checklist you wish to use. That way one can constrain the input to a controlled set. 

So to use the GBIF backbone as the suggest list
https://api.gbif.org/v1/species/suggest?datasetKey=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&limit=10&q=felis+concolor

Good luck with your project. If you end up generating a lot of data then make sure to share it with GBIF through your local node 😄 (perhaps [the UK node](https://www.gbif.org/country/GB/participation)?)
