### ISSUE TITLE
Images show an image with the text "No Image Available"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3445]
**Images show an image with the text &quot;No Image Available&quot;**

This seems silly. I guess it might convey the information that the do not have an image on demand either, but if that is the case perhaps a comment is better.

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/3f6fa9e8e8bab25025ebe265d1ad51d8:c6a423374b6aac6c09d7aa8b26f2cf3520dfc5c3557931ab4677a11ec4dfb61a0d156cf7b31b2560c64f0ea177679772091faac7b95da45249da15bb0b17aa11)
System: Chrome 90.0.4430 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=96404cc2-f762-11e1-a439-00145eb45e9a
Window size: width 1440 - height 766
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-03T09:03:57.948Z',to:'2021-06-03T09:09:57.948Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-03T09:03:57.948Z',to:'2021-06-03T09:09:57.948Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I've managed to find an actual image by clicking "more, more, more, more, more". They just disappear among the placeholder images. It is a nice image.
https://www.gbif.org/occurrence/2365571744

**Comment by jhnwllr** [comment]
Seems to be fixed. 

![image](https://user-images.githubusercontent.com/4245213/146184060-ab5f00b9-0263-4b6b-9609-3d6579a05b05.png)

**Comment by ManonGros** [comment]
It isn't fixed @jhnwllr there are still plenty of images like that: https://www.gbif.org/occurrence/gallery?dataset_key=96404cc2-f762-11e1-a439-00145eb45e9a

**Comment by jhnwllr** [comment]
I will write to the publisher.
