### ISSUE TITLE
Paragraph spacing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3446]
**Paragraph spacing**

Not a bug, but I'd suggest adding a little spacing between paragraphs in e.g. the description to aid readability.

-----

Github user: @timrobertson100
User: [See in registry](https://www.gbif.org/api/feedback/user/b912456e528320f38f5bd058a2e972a0:a3557bc308acbc4a5c51331cebc3fb2190c9913abbc97b81c0b7d7da4c90e1355e514de1be5ae8ca8de81b40140ec2b5b616a2ae17be22cfd7b3953e4fd34fff)
System: Chrome 90.0.4430 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e
Window size: width 1999 - height 1279
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-04T08:50:05.473Z',to:'2021-06-04T08:56:05.473Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-04T08:50:05.473Z',to:'2021-06-04T08:56:05.473Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
This was a case of https://github.com/gbif/ipt/issues/1332 and not a bug with the portal.

Paragraphs (where the registry didn't corrupt them) are formatted with some line space, and simple `\n` line breaks use `<br>`, which is probably best kept like this for when people have written lists etc using line breaks.
