### ISSUE TITLE
Citing user agreement

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#345]
**Citing user agreement**

I need to cite GBIF user agreement in the paper - is URL ok or should we have "how to cite" line below at the page? Guidelines give an example of citing specific pages https://www.gbif.org/citation-guidelines, but perhaps at some point we can have the autogenerated citation for the webpages like this? Not urgent, but possibly changing the citation practice.

-----
fbitem-ab29ac3a8dcee341f980bfa4f6246a83884060fe
Reported by: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/terms/data-user
Window size: width 1600 - height 898
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T08:16:16.582Z',mode:absolute,to:'2017-08-18T08:22:16.582Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T08:16:16.582Z',mode:absolute,to:'2017-08-18T08:22:16.582Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
To cite the GBIF user agreement, would you not cite this?
https://www.gbif.org/terms/data-user

**Comment by dschigel** [comment]
Sure, that's what I have now. I removed "Secretariat".
GBIF (2017) GBIF User Agreement. Accessed via https://www.gbif.org/terms/data-user on 18 August 2017.
Citing three such pages in a paragraph, I will end up with GBIF 2017a, GBIF 2017b, and GBIF 2017c. Maybe this is the way.
