### ISSUE TITLE
Uploading species occurrence data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3451]
**Uploading species occurrence data**

Hi,

I am a research scholar working at the ICMR-National Institute of Malaria Research, India. I have conducted a nation wide study on the abundance of Aedine vectors in India using modeling techniques and intend to publish my study soon. 

For the initial occurrence records I used the gbif data base (properly referenced and cited within manuscript as well as at the end in the data availability section), which included a global study that compiled occurrence locations from researches that employed entomological surveillance upto 2015. 

I have updated this record by making an extensive search of all literature with entomological surveillance after 2015. As part of the process of submission of my manuscript, I intend to submit the updated species occurrence data to a data repository. I would therefore like to enquire if the data would be eligible for hosting at GBIF, the process to do so, and the incurred costs if any.

Looking forward to your reply.

Kind Regards

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a25f946f45bd5dc1645a9ed73a42eae4:1cad4dadac581926c90527ec5ca01e3e7ec083f5df8d1a68498d3737cac68b8f2d9fe8fa27d89ec5da8cab91fb5a3e9ca81f75aab3bc4b5d43f30a390a983e9d)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1366 - height 635
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-08T04:54:14.219Z',to:'2021-06-08T05:00:14.219Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-08T04:54:14.219Z',to:'2021-06-08T05:00:14.219Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> GBIF cannot exactly host your data.
However, one solution would be to share your data on another platform such as https://zenodo.org (which is free) and use our derived dataset service to register it with a GBIF DOI. We have a blogpost on the topic: https://data-blog.gbif.org/post/derived-datasets/. I suggest to read it and see if this fits your case. Don’t hesitate to send us your questions.
