### ISSUE TITLE
I'm in doubt, I used GBIF for naming correction with the match tool, how do I mention this use?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3452]
**I&#39;m in doubt, I used GBIF for naming correction with the match tool, how do I mention this use?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/45c25c37cc14b815c4a289cc1e214456:f8981dd9d6e1e0ed8ff720716bf5459d45c04f99b235a79639bc0a54f120880543ad193ba60a0bebd68196bbd923a67a5db05aa8baa46832f0dd410c88d47861)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1366 - height 657
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-08T14:11:33.052Z',to:'2021-06-08T14:17:33.052Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-08T14:11:33.052Z',to:'2021-06-08T14:17:33.052Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:

> The matching tool uses the GBIF Backbone Taxonomy so I suggest to cite it as followed:

> GBIF Secretariat (2021). GBIF Backbone Taxonomy. Checklist dataset https://doi.org/10.15468/39omei accessed via Species matching tool https://www.gbif.org/tools/species-lookup on 2021-06-25.
