### ISSUE TITLE
double menu, double footer, double scripts etc on derived dataset pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3454]
**double footer on derived dataset pages**

Looks like the site footer has been included twice...

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/50933f738009c9ac43199f04daa9be22:dc1dfbd8058ee967833e717031664f32e4f2350771a138b36df1bb1f0df681607f20ecb19a64dd551fa96f824fe293f1c82b68206cbc9abc9398389174df7213)
System: Chrome 91.0.4472 / Mac OS X 10.15.7
Referer: https://www.gbif.org/derivedDataset/10.15468/dd.959yt8
Window size: width 1112 - height 1380
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-09T10:53:04.420Z',to:'2021-06-09T10:59:04.420Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-09T10:53:04.420Z',to:'2021-06-09T10:59:04.420Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The top menu bar (on top of eachother), all scripts, terms popup etc is also there twice.
