### ISSUE TITLE
Images don't work because they are links to web pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#346]
**Images don&#39;t work because they are links to web pages**

I suggest Helpdesk contact the publisher and ask for the links to the images be provided along with the source pages - it is possible to map both.

-----
fbitem-90ca04c707cd953f778e8789ed7ec98e67b20053
Reported by: @timrobertson100
System: Chrome 59.0.3071 / Mac OS X 10.11.5
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=f96a6f8c-b992-4159-8039-db8f30bac985
Window size: width 1674 - height 939
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T08:23:12.044Z',mode:absolute,to:'2017-08-18T08:29:12.044Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T08:23:12.044Z',mode:absolute,to:'2017-08-18T08:29:12.044Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
sent email

**Comment by ahahn-gbif** [comment]
issue confirmed and taken over by VertNet

**Comment by MattBlissett** [comment]
This looks to be fixed, any remaining problem is Arctos blocking our IP.
