### ISSUE TITLE
Suggest the event form

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3460]
**Suggest the event form**

Suggestion

Change time from AM/PM to 24h format

When selecting the end date the option in the calendar should not start from the current date, but from the provided start date (like when you select dates for a travel dates on an airline website)

Time zones list would work better if there would be typical cities, a more common format (and less thinking)

Add GBIF Secretariat staff and Other formal GBIF role to the selection list in Role, just above Ambassador option

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/b945360e5ea0408287599bbba4fee658:0de251af775eec0471587336cb93c68f9e204ee1b88cf043cb50ec28183b301f7b60eb2440beb74dd6dd406fa5fc11ce850cc6a2de84f9f919b0ef03b9801862)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/suggest-event
Window size: width 1638 - height 815
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-11T14:17:20.897Z',to:'2021-06-11T14:23:20.897Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-11T14:17:20.897Z',to:'2021-06-11T14:23:20.897Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by akristensen** [comment]
thanks @dschigel for the feedback, will let @dnoesgaard look at it. It is a google form that needs to be able to talk to Zapier, in order to "import " it to contentful. So we are limited in options regarding time format. I am sure we can change the Role order.

**Comment by dnoesgaard** [comment]
We can't change anything regarding dates, times or timezones. The form is strict because it has to connect directly to the CMS.

@akristensen, I thought we didn't want roles to describe _who_ people are, but rather what their role is _at_ the event?

**Comment by akristensen** [comment]
yes @dnoesgaard entirely right! I misread Dmitry, I thought it was about changing the order of the listed roles..... as we discussed previously , we want to keep the form simple, and we are not collecting info or interested in who people are. Only the relation to the event.
