### ISSUE TITLE
Supposedly only known from a single locality, this is north of this locality and probably incorrectly georeferenced. Please check. https://www.iucnredlist.org/species/179387/1576879#text-fields

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3462]
**Supposedly only known from a single locality, this is north of this locality and probably incorrectly georeferenced. Please check. `https://www.iucnredlist.org/species/179387/1576879#text-fields`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1be0740dd6e5c2209613f5f9af36a967:cf3cb7ed165bfd10bdca89f281bfb8179c3558f717b2a95b52e2695669cbe8a91be525a76f398112f9bb692e3e2489950598c37c9c9e96e1631c9d5f80a01d9e)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1260867495
Window size: width 1122 - height 670
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-14T08:32:28.590Z',to:'2021-06-14T08:38:28.590Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-14T08:32:28.590Z',to:'2021-06-14T08:38:28.590Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7bd65a7a-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 90fd6680-349f-11d8-aa2d-b8a03c50a862

**Comment by jhnwllr** [comment]
Responded to user and publisher via email. Record could be a low resolution record, since it is from the 1980s or perhaps it was located there in the past.

**Comment by jhnwllr** [comment]
publisher says record is correct.

**Comment by jhnwllr** [comment]
Publisher qualify that species name has an identification qualifier of `?`
