### ISSUE TITLE
Improving citation of downloads

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3464]
**Improving citation of downloads**

A few suggestions for the download page, inspired by [NEON](https://data.neonscience.org/data-products/DP1.20219.001/RELEASE-2021):

- [x] move __Citation__ into its own box
- [x] style it so that it's look like something you need to copy
- [x] add button to copy citation string to clipboard
- [x] add buttons to download citation as RIS and BibTex (*)

(*) can be [pulled directly from DataCite](https://support.datacite.org/docs/datacite-content-resolver), e.g.

`https://data.crosscite.org/application/x-bibtex/10.15468/dl.5pm5pt`
`https://data.crosscite.org/application/x-research-info-systems/10.15468/dl.5pm5pt`

(but filenames should be improved to at least have correct extensions)

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/4443aedc26d46a8111f85cd2c87b83e6:63a898d06c06485b6bac4597c5e7e30a7d7d7da1f1cd18cc3d398abd997a3aab3d1b19bddb098ef1468c2b55d0e4e1e03cc393021da7bccc2b613857657e1b13)
System: Chrome 91.0.4472 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/0220580-200613084148143
Window size: width 1431 - height 595
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-16T06:37:03.779Z',to:'2021-06-16T06:43:03.779Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-16T06:37:03.779Z',to:'2021-06-16T06:43:03.779Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Also see #33 and #2027

**Comment by dschigel** [comment]
This is very cool and welcome. Data citation needs to be very visible, inviting and hard to forget (to do), and also easy to copy / grab / import for those using copy-paste and for those using reference management systems.

*
Possibly related (for pages, not download citations): anecdotally, I was wondering how come my citations are going up so fast? The main reason is that I happen to co-author the latest UNITE paper, and [UNITE](https://unite.ut.ee/index.php#)  has a  very prominent How to cite? box visible from any UNITE page. In contrast, most GBIF pages have a citation footnote (also without RIS / BibTex), and you need to know i) it exists, to start with ii) scroll down all the way to find it. Only a very motivated and well-informed page visitor / and citation-oriented user would do that. I am no UI/UX expert, but I can see the difference. Of course, UNITE prefers to be cited as a whole, whereas we need DOI based breakdown, but I am only noting this for illustration of visibility of citation services - in case it helps.

**Comment by MortenHofft** [comment]
> (but filenames should be improved to at least have correct extensions)

It sounds like a good idea to give those files a better name. Could you log an issue with Datacite?

**Comment by dnoesgaard** [comment]
Ref https://github.com/datacite/datacite/issues/1291

**Comment by dnoesgaard** [comment]
Would anyone be opposed making it pop even more?

![Screenshot 2021-06-23 at 15 24 36](https://user-images.githubusercontent.com/21358085/123105717-4ec93b80-d438-11eb-8316-638402908e4e.png)

(`style="background-color: #40BFFF;color: white;`)

**Comment by MortenHofft** [comment]
I'm personally not a fan of it

**Comment by dschigel** [comment]
I like the highlight, but the way it is done - color, position,  boldface etc. - I leave this to professionals. A ?small thing: as discussed with @dnoesgaard I would like "please" to go. I checked NASA, UNITE and other places, this is something that is not asked, but required: Cite as. Or even better, with a tiny hyprlinked reference to User agreement: GBIF user agreement [LINK] requires this download to be cited as. No "please". Just follow the rules you accepted when creating the GBIF profile, or leave :).  There might be some style rules we should follow, but if you share my doubts about softness of this, please test with other non-native English speakers. The pshychological effect I would like to see here that this citations will be i) impossible to overlook and ii) impossible to misinterpret this hard requirements as soft option, which it is not. Any means to achieve this are welcome. And I love export boxes. Hope we can have them for all citations, not only downloads.

**Comment by dnoesgaard** [comment]
Using "please" does not make it a question, it's simply a polite request as opposed to simply a request:

> do this

vs

> please do this

I really don't share your doubts in this matter. And since the tasks listed in the issue are done, I think we're good to close it.

**Comment by timhirsch** [comment]
fwiw I am with @dnoesgaard on the 'please' issue. It does not suggest it is any more optional than 'cite as'.
