### ISSUE TITLE
Is this a weed or a flower? Is taking over my flowerbed.  How do I get rid of it?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3468]
**Is this a weed or a flower? Is taking over my flowerbed. How do I get rid of it?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7e177e3cc6a9747a297ae13618681ab9:80b5ab164b93a01969cd4c7f209c7dcd5a9b3e107a232be80430c198af8a9d00d80979a74f594a70cedc706c1688a4a38ce312ece2f8da592e4f9998767d82de)
System: Samsung Internet 14.0.0 / Android 0.0.0
Referer: https://www.gbif.org/user/confirm
Window size: width 412 - height 678
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-18T12:05:18.637Z',to:'2021-06-18T12:11:18.637Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-18T12:05:18.637Z',to:'2021-06-18T12:11:18.637Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I'm afraid we cannot help you with this. Try a garden site. A quick google search shows
https://garden.org/ . From their website:

> Since 1971, our mission is to promote gardening.
> 1. We teach people how to get started gardening and to improve their plant growing skills.

User informed per email
