### ISSUE TITLE
Mismatch between photograph and record

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3471]
**Mismatch between photograph and record**

The record states that this is Arcoscalpellum hirsutum, but the photograph of the record states Tetraclita purpurescens. Similarly, the location etc do not match. I assume the photographs were mixed up during upload.

All the best,
Christine

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4cdee3383a85aeb261a7aa9e0f332751:cb8ee1d4d62e19d7c23e4a971e15da9b4c59122518a9d1d064e9354b0709ebbeb3fdafc88926821009df56a8784e399416a216f0f47106cf270234e1758deb9e)
System: Chrome 91.0.4472 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/1317554998
Window size: width 1400 - height 621
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-19T17:06:55.147Z',to:'2021-06-19T17:12:55.147Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-19T17:06:55.147Z',to:'2021-06-19T17:12:55.147Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 821cc27a-e3bb-4bc5-ac34-89ada245069d
publishingOrgKey: bc092ff0-02e4-11dc-991f-b8a03c50a862

**Comment by jhnwllr** [comment]
Wrote to data publisher via email...

On label: 
Tetraclita purpurascens (Wood)
Tetracliten purpurascens (Wood)

In Dataset: 
Arcoscalpellum hirsutum

**Comment by ManonGros** [comment]
The record now shows the name and locality corresponding to the image.
