### ISSUE TITLE
Area downloaded

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3473]
**Area downloaded**

Hello. I wonder if there is anyway that you can provide the image of the area that my data was inclusive in? I selected the area on a map, but need to reference the area selected in my work. Is there a way to recall the map selection?

Thank you

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/80d213232ed4273df3463148a155f161:fd88f437300a22fc65d7eb58ff790a03cbcb44f308080d10af7999a60602142681c3fc3c1c23d22069cf088dc2b4cda19b8131306475cc36b225523e983ca8fc)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1366 - height 625
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-21T12:18:30.699Z',to:'2021-06-21T12:24:30.699Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-21T12:18:30.699Z',to:'2021-06-21T12:24:30.699Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
User was contacted and the solution was presented.
