### ISSUE TITLE
Harmonia axyridis f. succinea not in backbone

### ISSUE THREAD

**Issue by damianooldoni** [gbif/portal-feedback#3474]
[Harmonia axyridis](https://www.gbif.org/species/4989904) is one of the most important and studied invasive species in Europe and North-America. It seems that its most common form, f. succinea is not in the GBIF backbone, with disappointed biologists (colleagues) as result.

As GBIF promoter I would like to mention this to GBIF and I would like to ask you:
1. why f. succinea is not in the Backbone?
2. can this form be added to the Backbone (via patch if automatically impossible)?

Thanks!

**Comment by ManonGros** [comment]
It seems like we get the species name from the [Checklist of Beetles (Coleoptera) of Canada and Alaska. Second Edition.](https://www.gbif.org/dataset/7a9bccd4-32fc-420e-a73b-352b92267571) but the form names from [TAXREF](https://www.gbif.org/dataset/0e61f8fe-7d25-4f81-ada7-d970bbb2c6d6). Perhaps we could ask one or the other to include f. succinea in their checklist.
What do you think @mdoering ?

**Comment by mdoering** [comment]
we can surely add this form to the next backbone with a patch!
I will contact TaxREF and inform them.
The form is also present in the [United Kingdom Species Inventory (UKSI)](https://www.gbif.org/species/180188884), maybe we should add that to the backbone?

**Comment by ManonGros** [comment]
Thanks for asking TAXREF! And yes the UKSI seems like a good addition to the backbone (but I am no expert).

**Comment by mdoering** [comment]
Adding the UKSI dataset as a backbone source might will have some impact.
There are ~11.200 names that will be added: https://www.gbif.org/species/search?rank=SPECIES&rank=GENUS&rank=SPECIES_AGGREGATE&rank=VARIETY&rank=FORM&rank=SUBSPECIES&dataset_key=dbaa27eb-29e7-4cbb-8eab-3f689cfce116&highertaxon_key=180120333&name_type=SCIENTIFIC&origin=SOURCE&issue=BACKBONE_MATCH_NONE&advanced=1

Looks like a good idea. There are many informal names in there too, but they all seem to be recognised fine by the parser so they will be blocked from entering the backbone.
