### ISSUE TITLE
Genus is incorrectly grafted

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3476]
**Genus is incorrectly grafted**

https://www.gbif.org/species/73842
Per the citation and papers defining it, this genus and its single species (A. talladega) is a moth, yet it is grafted in your tree as a plant.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/07cddb1d68d7959a2838a5c363ae71f5:bc42a197c77c48120dba63d4a75a27bf4a433e783137f255049696f115b2a3e3486325174680e9a93822faff84a77f5e9259debe66a1a50b63641f3266c87188)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/faq
Window size: width 1366 - height 625
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-23T15:46:35.103Z',to:'2021-06-23T15:52:35.103Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-23T15:46:35.103Z',to:'2021-06-23T15:52:35.103Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The issue seems to come from this dataset: https://www.gbif.org/dataset/834831a3-c0b8-44fa-b357-c14c05822909

It seems like the higher taxonomy provided is incorrect.
PLAZI UUID to easily find the issue: 7ce8aef0-9e92-11dc-8738-b8a03c50a862

**Comment by truschel** [comment]
Hi @ManonGros 
I corrected the higher taxonomy for _Arcutelphusa_ and _A. talladega_ occurrences in this publication. Please bear in mind that changes sent to GBIF might take a few hours to come into effect. Thanks for report it for us!

**Comment by ManonGros** [comment]
Great, thanks @truschel !
