### ISSUE TITLE
Spartina patens has two IDs, one as a plant (correct) and another one as an insect (wrong).

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3478]
**Spartina patens has two IDs, one as a plant (correct) and another one as an insect (wrong).**

The species Spartina patens (https://www.gbif.org/species/10857569) is classified as Insect, whereas in fact the species is a plant (https://www.gbif.org/pt/species/5290026)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9f4de11768c366c57eae10d85f2b2c71:ce01f61c00d6f9488d73471747b122fdb4707ae347548d7f348d72d5ccc48d7d5c356a86f5a6052d1af589ce885dd3a3cca36a194b6d69bca22d26392ed19490)
System: Chrome 91.0.4472 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/10857569
Window size: width 1241 - height 696
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-23T19:48:02.575Z',to:'2021-06-23T19:54:02.575Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-23T19:48:02.575Z',to:'2021-06-23T19:54:02.575Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The issue seems to come from this PLAZI dataset: https://www.gbif.org/dataset/7a684426-15d9-4d60-9e1e-a5c182e5b17b

It seems like the higher taxonomy provided is incorrect.
PLAZI UUID to easily find the issue: 7ce8aef0-9e92-11dc-8738-b8a03c50a862

**Comment by ManonGros** [comment]
fixed in the new backbone
