### ISSUE TITLE
data use topic enums with spacing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#348]
**data use topic enums with spacing**

Just noticed that some topics in Data, e.g. Human health, has 0 items. This is of course not true:

"Human health": {
"name": "Human health",
"title": "enums.cms.vocabularyTerms.Human health",
"count": 21
}

But I guess the space somehow messes up the link?

Maybe it happened when the enums were aligned for literature and dataUse?

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb
Reported by: @dnoesgaard
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/resource/search?contentType=dataUse
Window size: width 1600 - height 951
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T09:34:01.882Z',mode:absolute,to:'2017-08-18T09:40:01.882Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T09:34:01.882Z',mode:absolute,to:'2017-08-18T09:40:01.882Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
it was decided [here](https://github.com/gbif/portal16/issues/401) how terms hould be labeled.
The contentful terms should be updated accordingly since they have changed.
Perhaps updating the contentype with an ENUM value

**Comment by MortenHofft** [comment]
@fmendezh Could we normalize the enums to constant case at indexing time? E.g. transforming (Human health, Human_health etc) -> HUMAN_HEALTH 

Would that make sense to you? Alternative extending the contentmodel for vocabularies with an enum field and then use that in indexing instead.

Which makes the most sense to you? I think I'm in favor of version 1.

**Comment by MortenHofft** [comment]
Looks good on UAT @fmendezh https://www.gbif-uat.org/resource/search?contentType=dataUse
