### ISSUE TITLE
add to synonym list

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3486]
**add to synonym list**

I suggest to add to the synonym list of this species:
Trochus papilla

see e.g.
http://www.molluscabase.org/aphia.php?p=taxdetails&id=1475636

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ae8dcae2238a09c105b9ec3cbd69682a:67e870e2ed3f1be4ade629d9bccbc92cb78d6ec055255055b71b00b586d748fbd07ec05a034dea292e0373654f4b916afff65bd2df90fab2a3ba6b54947ba50b)
System: Firefox 89.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/10804185
Window size: width 1920 - height 955
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-29T07:28:52.718Z',to:'2021-06-29T07:34:52.718Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-29T07:28:52.718Z',to:'2021-06-29T07:34:52.718Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This seems to have already been added in the CoL: https://www.catalogueoflife.org/data/taxon/7Q3KV

**Comment by ManonGros** [comment]
Solved in the new backbone: https://www.gbif.org/species/11264909
