### ISSUE TITLE
Show me my roles please

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3488]
**Show me my roles please**

It would be helpful to see what roles and scopes you have on this page.
(from David Bloom)

-----

Github user: @timrobertson100
User: [See in registry](https://www.gbif.org/api/feedback/user/adaaede6ed5dfe911e1b3f45291295c7:1fd2ed3f046d2da62d6817a0713e9553f9b6f8426ab2975842905bcf86f9c18b8544133d5bb4e3d626352b327dcc865ad7c6e7b3cf79f99714e5e4ab25bed305)
System: Chrome 91.0.4472 / Mac OS X 10.15.7
Referer: https://www.gbif.org/user/profile
Window size: width 2100 - height 1253
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-29T12:52:50.602Z',to:'2021-06-29T12:58:50.602Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-29T12:52:50.602Z',to:'2021-06-29T12:58:50.602Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
See also https://github.com/gbif/registry-console/issues/399

**Comment by dbloom** [comment]
Thank you @timrobertson100  I could see several uses for this, not just for Node Managers and staff, but also for individual users. Happy to elaborate if useful to GBIF.

**Comment by MortenHofft** [comment]
It is now possible to do so in the registry. Since [the registry](https://registry.gbif.org/) is where you can edit I figured it was most pertinent in that context. 
<img width="265" alt="Screenshot 2021-06-30 at 10 17 35" src="https://user-images.githubusercontent.com/6759267/123926925-a877bb80-d98c-11eb-8bc4-4e9ec1f0339e.png">

**Comment by MortenHofft** [comment]
Does anyone believe this should be added to the gbif.org profile view? Currently it is only available in the registry where editing rights and roles matter. If so let me know and I will reopen the issue.

**Comment by ManonGros** [comment]
I think it makes sense to keep it in the registry. Does that sound good @dbloom ?

**Comment by dbloom** [comment]
@ManonGros  et al.  I think keeping in within the registry makes sense to me. This will keep the focus where it needs to be without complicating things elsewhere.
