### ISSUE TITLE
'Publications from' not showing on non-participant country pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#349]
**&#39;Publications from&#39; not showing on non-participant country pages**

NB this is not very high priority, but something to consider for future enhancements.

Currently in countries where there is no data publishing activity, the dashboard summaries do not show publications with authors from that country. In the case of Egypt, this means that although papers tagged with Egypt as a subject appear in 'Data about Egypt' (nice), the country page does not show the list of 15 Egypt-authored papers (see https://www.gbif.org/resource/search?contentType=literature&countriesOfResearcher=EG). This is a shame as it is important to show to prospective GBIF participant countries that their researchers are already making use of data from GBIF. A solution might be to separate out Research as a separate tab at the top, as really these publications do not intuitively belong under the heading 'Data about' or 'Data from'. That could then lead to two lists - one headed 'Peer reviewed publications about xx citing GBIF as a data source', and the other 'Peer reviewed publications authored from xx citing GBIF as a data source'. This could apply to all countries whether publishing data or not.

-----
fbitem-c3e982eac1c07704b727bf29a15abbf3b621640d
Reported by: Tim Hirsch
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/country/EG/summary
Window size: width 1313 - height 785
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T09:47:34.478Z',mode:absolute,to:'2017-08-18T09:53:34.478Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T09:47:34.478Z',mode:absolute,to:'2017-08-18T09:53:34.478Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I've added this for non data publishing countries

![screen shot 2017-08-18 at 15 58 46](https://user-images.githubusercontent.com/6759267/29462018-27ae9a26-842e-11e7-9047-8378a385f4f5.png)

**Comment by MortenHofft** [comment]
@timhirsch https://www.gbif-uat.org/country/EG/research something along these lines perhaps?

**Comment by timhirsch** [comment]
Perfect, thanks!

**Comment by MortenHofft** [comment]
In that case I will close the issue.
Currently it shows odd if there is no publications:
https://www.gbif-uat.org/country/AF/research I've changed this to display similar to 
https://www.gbif-uat.org/country/AF/publishing
Will be available on next build
