### ISSUE TITLE
Possibly erroneous synonymization - Pollenia intermedia and Pollenia labialis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3491]
**Possibly erroneous synonymization - Pollenia intermedia and Pollenia labialis**

This is a message we received on heldpesk:

Pollenia intermedia is currently listed by GBIF as the preferred name for the synonym Pollenia labialis. 

However, the cited taxonomic authorities (both Catalog of Life and Diptera.org) list both names as valid, and show no relationship between them (other than that they are the same genus).

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/cdb60bd418ea713f1941de18eb954983:ef41f5e4d5de73c104de72055609461ab9520311ac1f022bd9882b29816113f0035865bbc30262164771f9dfc466e1c972660f997f7ae38ecc493e616dc6346a)
System: Safari 14.1.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/1503663
Window size: width 1471 - height 793
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-30T07:56:14.913Z',to:'2021-06-30T08:02:14.913Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-30T07:56:14.913Z',to:'2021-06-30T08:02:14.913Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@mdoering I don't know why these two species are synonym, I cannot find any source behind it. Could you take a look? Thanks!

**Comment by mdoering** [comment]
The COL version from december 2020 which we used does have them as synonyms, taken from an old version of Systema Dipterorum: https://data.catalogueoflife.org/dataset/2242/taxon/6VSRD

SD has been updated since which seemed to correct the mistake!

**Comment by ManonGros** [comment]
Solved in the new backbone
