### ISSUE TITLE
DwC-A data validator - apparently it stopped working? It flashes a text for a while and then states that "The validation job ID was not found"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3493]
**DwC-A data validator - apparently it stopped working? It flashes a text for a while and then states that &quot;The validation job ID was not found&quot;**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/564e029baa0e2ffe259306799e678f65:7f670d322b6a6300d1028c1c6cb5d2a602135791dda266dc6d2948e4e548e82431bee310efd984067c1bbe2aad404b10d0e02d634c68f360ba67d69cd8c9cae0)
System: Firefox 89.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator/1622015286570
Window size: width 1920 - height 927
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-01T12:38:07.697Z',to:'2021-07-01T12:44:07.697Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-01T12:38:07.697Z',to:'2021-07-01T12:44:07.697Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
Cannot reproduce issue. Probably a temporal glitch and new validator is in the works. So not worth spending resources on.
