### ISSUE TITLE
"Rerun query" link on downloads ignores In predicates

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3494]
**&quot;Rerun query&quot; link on downloads ignores In predicates**

The license predicate (which is an In predicate) isn't included when clicking "Rerun query" on this download.

https://www.gbif.org/occurrence/download/0314814-200613084148143

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4e66f4c1d380404bf25bf8fe57f371a0:ec99e79677a823c242989626b32e2edbea2e1f99ea2a4f42c498d26f48865392fbfa1cfac08bb509c5417a895f805874ee1873e9e017653ef20fdd64d26f0645)
System: Firefox 89.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/occurrence/download/0314814-200613084148143
Window size: width 956 - height 936
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-01T13:29:17.175Z',to:'2021-07-01T13:35:17.175Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-01T13:29:17.175Z',to:'2021-07-01T13:35:17.175Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The code for processing download predicates is convoluted and miss testing. 
We translate them into simple search queries and into the trees we show in the UI.

Either way above issue should be solved now, but the code is still in a state that it would benefit from refactoring.
