### ISSUE TITLE
End date and time

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3496]
**End date and time**

First month to see when entering end date and time should not be current, but same as Start date and time.

BONUS. Make time a separate and non-obligatory field.

For illustration, try to repeat what I did, create a new even that takes three full days on 13-15 March 2023.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/22c7627d11c49a097d1ef2955227e638:6835889b007afa9b686f8971ce7e0875d631cb4fcc6eb8649f0f187513e83cc71a3043c320408c74bf3e5d36b61194e1ecd03b92589f7a4453fd043a0ebb5049)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/suggest-event
Window size: width 2048 - height 1019
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-02T11:50:40.270Z',to:'2021-07-02T11:56:40.270Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-02T11:50:40.270Z',to:'2021-07-02T11:56:40.270Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
This is a Google Form and it doesn't allow us to make the suggested changes.

Hint: click the month name to navigate years/months more easily
![Screenshot 2021-07-02 at 14 23 51](https://user-images.githubusercontent.com/21358085/124274088-21b80f80-db41-11eb-9996-3f8ed015bc58.png)
