### ISSUE TITLE
Duplicate Taxon IDs for "Balanus nubilus" and "Balanus nubilus Darwin, 1854" ?

### ISSUE THREAD

**Issue by cebraj** [gbif/portal-feedback#3499]
Greetings,
It seems there are 2 different IDs for "Balanus nubilus" in GBIF. Are they in fact the same taxon? If so, can they be merged into one record?

https://www.gbif.org/species/2115695
https://www.gbif.org/species/2115727

I am working on a linked data project and need to include a single Taxon ID for this species.

Much appreciated,
Jessica

**Comment by ManonGros** [comment]
After a quick search, both spellings exists and seem to be referring to the same species. Perhaps those should be synonymized? @mdoering any thought on that issue?

**Comment by mdoering** [comment]
Probably, although B, nubilus and nubilis (contrary to the issue title) might be different names and thus the backbone build isn't doing sth unexpected.

**Comment by mdoering** [comment]
WoRMS, Wikipedia, iNaturalist and others use nubilus, but none have nubilis as a synonym or misspelling.
ITIS, sealifebase, coralnet and others just the other way around, accepting nubilis but no mentioning of nubilus.

**Comment by mdoering** [comment]
nubilus is in ZooBank and seems to be the correct spelling: http://zoobank.org/NomenclaturalActs/0284f552-cf71-4579-8881-2ab8dc7825cf

Darwin clearly published nubilus: https://www.biodiversitylibrary.org/item/18394#page/269/mode/1up

**Comment by mdoering** [comment]
I'll add a patch entry to synonymise them

**Comment by mdoering** [comment]
ITIS actually contains both species:
https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=89600#null

```
Species | Balanus nubilis |  
Species | Balanus nubilus Darwin, 1854

```
