### ISSUE TITLE
Consider using PhyloPic for images of organisms

### ISSUE THREAD

**Issue by rdmpage** [gbif/portal-feedback#35]
[PhyloPic](http://phylopic.org) provides free and open images of organisms in a standardised form and has an API (albeit with not the most obvious interface). I use it in BioNames, e.g. http://bionames.org/search/Apus

![screenshot 2017-01-13 13 19 22](https://cloud.githubusercontent.com/assets/83306/21931457/69ac5990-d993-11e6-8791-b037b8557090.png)

OpenTreeofLife also use it. I think it would help people navigate the GBIF taxonomic hierarchy and get a sense of what they are looking at if GBIF uses this images on taxon on occurrence pages, especially if there are no existing images available in GBIF itself.

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/227
