### ISSUE TITLE
Primary link missing from dataUse

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#350]
**Primary link missing from dataUse**

I've just noticed that we're not showing links on dataUse items. Could we add that just before the citation?

On that note, the content model now only has 1 citation, but allows for multiple links (primary and secondaries), so we could probably change "Citations" to singular, and maybe just put "Link(s)" for links.

-----
fbitem-bfbcd65f6cb0f3f43558c102b0fe8bd972c2ec2f
Reported by: @dnoesgaard
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/data-use/83369/strategy-for-conservation-of-crop-wild-relatives
Window size: width 1600 - height 951
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T10:08:43.489Z',mode:absolute,to:'2017-08-18T10:14:43.489Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T10:08:43.489Z',mode:absolute,to:'2017-08-18T10:14:43.489Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Is is called citationS because the content type in drupal allowed for multiple citations and if I remember correctly they were sometimes also written in a single field. If it in reality is always singular, then I'm good with changing it, but there is nothing in contentful hindering you from entering 2 citations. I imagine that could be useful to have that option at times? E.g. for an article.

**Comment by MortenHofft** [comment]
links will be shown on data use and news items: https://github.com/gbif/portal16/commit/b415c9159c5f63898ff3343f07ee5aab1c91a2bc

**Comment by dnoesgaard** [comment]
Ok. I guess it's possible that a story could have more than one citation. It's just not common right now. Are you opposed to "Citation(s)" to deal with the possibility of more than one?

For links, we always have a primary link and sometimes (but not often) secondaries.

**Comment by MortenHofft** [comment]
Added below the article as discussed https://github.com/gbif/portal16/commit/78ed7a8428d3819d058b444621e686c8ad07ad9f
![screen shot 2017-08-18 at 15 02 33](https://user-images.githubusercontent.com/6759267/29460071-c4dae21c-8426-11e7-9d9a-9526385b7c60.png)
