### ISSUE TITLE
RIS, BIBTEX download of citation is not working

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3500]
**RIS, BIBTEX download of citation is not working**

RIS, BIBTEX download of citation is not working

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/869d95c426ba93689b479a5e3148f590:ebba08f1ad8023b4703dfe921f016d828cb90428792c415e0ae726099d5d807a3a024f498b21b0280c18c3d95e982a208328f866b17b85d9cbff1db4e7c74c81)
System: Opera 77.0.4054 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?q=3307507198
Window size: width 1920 - height 939
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-05T09:10:53.023Z',to:'2021-07-05T09:16:53.023Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-05T09:10:53.023Z',to:'2021-07-05T09:16:53.023Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@dnoesgaard do you know what this is about?

It is hard to tell from the link the user has provided I find. I've tried the specific users downloads and they work fine to me. And I've tried them in the Opera browser as the user is using. That works fine as well. 

Perhaps it is a question about latency before the Datacite link works? Could you possibly list when this works and how to detect it then I can update the site. Cancelled downloads do not seem to work either. Is that always the case?

**Comment by MattBlissett** [comment]
For cancelled / broken downloads we don't register the DOI, though it has been reserved.  We should not display the citation block or the DOI on these.

**Comment by MortenHofft** [comment]
If it isn't registered anywhere, should we then remove the DOI rom the API?

**Comment by dnoesgaard** [comment]
I guess we don't register until the download is ready? I did a test and the moment my download was ready, I was able to query the Datacite API and get RIS and Bibtex files. Perhaps we could hide the citation box until the download is ready?

**Comment by MattBlissett** [comment]
We need to keep it in the database (unless we delete the reservation, but there have been cases where people cancel a download but still cite the download).

I think it would be reasonable to hide it from the API if the status is not RUNNING, SUCCEEDED, or FILE_ERASED.

**Comment by dnoesgaard** [comment]
Fairly sure we delete draft DOIs if unused. Example: https://www.gbif.org/occurrence/download/0148547-200613084148143 

![Screenshot 2021-07-05 at 13 20 55](https://user-images.githubusercontent.com/21358085/124463920-d6496f80-dd93-11eb-81b8-a929a6d0181b.png)

**Comment by MortenHofft** [comment]
So is it correctly understood that we should only show it if `status: SUCCEEDED` AND a DOI is included in the API response.

So users can only download the citation once the data is ready to download.

**Comment by dnoesgaard** [comment]
I'm a little bit worried about what might happen if we don't show the citation block until the download is ready. 

But since the RIS/Bibtex links will not work until the DOI is registered, we might consider only showing these when the download status is `SUCCEEDED`. Does that make sense?

**Comment by MattBlissett** [comment]
`FILE_ERASED` is just as good for citation, as we still keep the metadata and the DOI is registered.  It is equivalent to `SUCCEEDED` in this case.

I was thinking we should change the registry API response, but I don't mind this being done in the portal instead.

**Comment by MortenHofft** [comment]
I agree it is a shame that we cannot show it until it is completed, but unless we create the endpoint ourselves there isn't much I can do (if it isn't available through the DataCite API)

**Comment by dnoesgaard** [comment]
If we can hide the RIS/Bibtex buttons until the download is ready, I think that's fine. I don't think we should hide the entire citation block. We don't want to give people any excuse not to cite the downloads properly.

**Comment by MortenHofft** [comment]
I will do that, but I also believe we should remove the DOI from the API if we know it doesn't work. As in the issue linked above.

**Comment by dnoesgaard** [comment]
Btw, @MortenHofft did you write the user? Otherwise I will...

**Comment by MortenHofft** [comment]
No I haven't. please do yes :)
