### ISSUE TITLE
add redirect (BID communications guidelines)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3501]
**add redirect (BID communications guidelines)**

would it be possible to add a more specific redirect for http://bid.gbif.org/en/community/communication-guidelines/

to
https://www.gbif.org/article/4VrlT3i4ZCJPOY8dX9JcQo

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/87d58d9c7cfe771ed4d9ad71ee4e0bba:94bdad318065e8a2910308ec923ecd32965cc0231e1fd76ab1e76e2a2ca71b64793ac5009d0cf5582f51d3da8f694be3a79f488651ce1e18952a65643e190bf6)
System: Chrome 91.0.4472 / Mac OS X 10.15.7
Referer: https://www.gbif.org/article/4VrlT3i4ZCJPOY8dX9JcQo/bid-communications-guidelines
Window size: width 1440 - height 622
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-06T07:54:44.147Z',to:'2021-07-06T08:00:44.147Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-06T07:54:44.147Z',to:'2021-07-06T08:00:44.147Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Done.
