### ISSUE TITLE
link to citation guidelines on species pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3503]
**link to citation guidelines on species pages**

I'd like to include a link to the citation guides right next to the citation header (`species.citation`) on species pages. I'm not sure I can include links in translations. Can you advise?

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/2e51067471ce3bc62f05c68615c4311b:28a99afa02e45b399b549cf8c4ab8a4251d8669ea74431ea123a28ffd56c204dcac18b828c4bd1c69d744f33cad6d651a701509f3189f66dca47636b33fc9642)
System: Chrome 91.0.4472 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/2735116
Window size: width 1440 - height 622
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-06T08:16:34.063Z',to:'2021-07-06T08:22:34.063Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-06T08:16:34.063Z',to:'2021-07-06T08:22:34.063Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Something like this

<img width="397" alt="Screenshot 2021-07-06 at 10 19 49" src="https://user-images.githubusercontent.com/21358085/124567122-fb95b680-de43-11eb-8be9-4a2e03a679ad.png">


linking to `/citation-guidelines#occDataDownload`

**Comment by MortenHofft** [comment]
Makes sense to do this.

Should we aim to add the copy/bibtex/ris buttons as well? Should it be styled similar to the download citation box?

Would it make sense to create an issue with all of the changes you would like to see to how citations display in the UI?
It can be nice to know from a development perspective if the implementation is to be used 10 places or 1. I'm mentioning it because we just did something bespoke for first downloads, then derived datasets and now species pages.

**Comment by dnoesgaard** [comment]
I think styling the citations similarly (and providing downloadable RIS/Bibtex links where possible) across all citable objects makes a lot of sense. Species are slightly different, however, as they don't have unique DOIs. Reviewing all these take time and requesting small changes one at a time is sometimes more manageable. But I get your point, I agree it would make sense to review all of them together, which I will happily do.

Perhaps we could limit this issue to the simple "link in translation" question?
