### ISSUE TITLE
broken links to images on BLR

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#3504]
in these cases the images do not show up
https://www.gbif.org/species/164184173
![image](https://user-images.githubusercontent.com/4609956/124592341-a6ff3500-de5d-11eb-81e6-823a5d9f1fa0.png)
it seems to load, but then suddenly stops, but the link to the image on BLR is working https://zenodo.org/record/3833633#.YOQ9w-gzb8A

I thought that there are some others too, but can't recapitulate the error

**Comment by thomasstjerne** [comment]
@myrmoteras I see both images when I click https://www.gbif.org/species/164184173
Could it be network issues causing this temporarily?

**Comment by MortenHofft** [comment]
I've tried in Firefox, Safari, Opera and Chrome on mac and cannot reproduce. Sounds very likely that this is due to a network outage.

**Comment by myrmoteras** [comment]
looks like it - I can't reproduce it either
