### ISSUE TITLE
The data file is cluttered

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3507]
**The data file is cluttered**

Hi,
I downloaded the following dataset:
GBIF.org (08 July 2021) GBIF Occurrence Download https://doi.org/10.15468/dl.hqa4ck

However, the data are cluttered in excel and seems to be in the wrong columns. I used R to open the data and the same issues still exist. 

It would be great if you could resolve the issue. 

Regards
Hadi

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ad6e27c52a1d3d9b166a0cc4a00af5c9:84866f6af1206640154f7312fbfc1a22bf68fef0bc890367c09148578bfeae9ecc527f2f5b4b11645ce2de8e1e507917d6742eebd7af2f351419384b5c5d30ac)
System: Chrome 91.0.4472 / Windows 7.0.0
Referer: https://www.gbif.org/occurrence/download/0319092-200613084148143
Window size: width 1422 - height 776
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-08T07:22:27.805Z',to:'2021-07-08T07:28:27.805Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-08T07:22:27.805Z',to:'2021-07-08T07:28:27.805Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

The files downloadable from GBIF are tab-separated CSV files. Here is a link to an FAQ explaining how to open this type of file in excel: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
Here is a thread on our forum explaining various way to open these files in R: https://discourse.gbif.org/t/reading-gbif-downloads-simple-csv-with-r/2615
