### ISSUE TITLE
no funciona el botón de búsqueda. La página no carga. No puede leer esto porque las columnas se superponen

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3508]
**no funciona el botón de búsqueda. La página no carga. No puede leer esto porque las columnas se superponen**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2b30cc89825318e2ae17f4ef166b9a06:62cf1c489ab9c7b7a87f160ab0c72c3454cd5a1622c5fd9399a17b85a138a48447a2bce1e37c2c9c9570c9d53c14d896bfda13c13800a8747266942f9379ead971c50fca9bb975815f20d800906dfd44)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/es/health
Window size: width 1366 - height 657
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-08T13:33:31.481Z',to:'2021-07-08T13:39:31.481Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-08T13:33:31.481Z',to:'2021-07-08T13:39:31.481Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Google translate

> search button does not work. The page does not load. You cannot read this because the columns overlap

**Comment by MortenHofft** [comment]
Hi, Thank you for reporting this. I'm afraid I do not speak Spanish. 

Could you provide some more context please? What page are you having issues with? Possibly with a screenshot.
Do you still have the issue or was it temporary? Do you have any plugins running (for example that blocks Javascript). 

Thank you for your help

> sent per email
