### ISSUE TITLE
Bug in web address

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3510]
**Bug in web address**

link should be https://www.nocturne.org.uk/ (right now it contains gbif in front )

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/62f4b20257c86a1baa80346a8ee11ee5:dac1d983789d9b01cf1092c84b44719636c04876a9be433d152959a73220068f99f99dc32d0b96dd3a070406073e2d4f8e56a08827c164c01521e94fbb8706e8)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/4e8fae15-2ca7-4493-8c57-573194d29c0f
Window size: width 2327 - height 1179
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-09T11:03:24.022Z',to:'2021-07-09T11:09:24.022Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-09T11:03:24.022Z',to:'2021-07-09T11:09:24.022Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Thanks @akristensen, fixed in the registry.
