### ISSUE TITLE
The occurrence data files I get are not comma delimited. Excel can't divide the data into fields. I can't figure out how to fix.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3512]
**The occurrence data files I get are not comma delimited. Excel can&#39;t divide the data into fields. I can&#39;t figure out how to fix.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/53af30d2fe8dc489561c563ce22ed6dd:af23a87b4d2ee1fdf301e72ab4b1dbffbe156cf67fc48a242d4ae6512ebacbda93d1baadfc53f04db9994eb6c4dd0ec46eaf8b1ed748bc215d1449ca51ff29a7)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/data-processing
Window size: width 1536 - height 664
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-12T00:38:49.504Z',to:'2021-07-12T00:44:49.504Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-12T00:38:49.504Z',to:'2021-07-12T00:44:49.504Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
User contacted by email:
> The files downloadable from GBIF are tab-separated CSV files. Here is a link to an FAQ explaining how to open this type of file in excel: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
