### ISSUE TITLE
Bug when trying to download large dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3515]
**Bug when trying to download large dataset**

Hello GBIF,

I am trying to download a species list for Polesia, which I mapped and converted to coordinates. Below is the link I used. The polygon seems correct, as it load properly in the minimap. I use Chrome which supports URLs of this length. 

Can you help me download these data?

https://www.gbif.org/occurrence/download?basis_of_record=HUMAN_OBSERVATION&has_geospatial_issue=false&year=1971,2021&geometry=POLYGON((31.54303%2050.91727,31.07572%2050.63062,30.83434%2050.53507,30.8312%2050.56495,30.77478%2050.58685,30.65252%2050.53308,30.43464%2050.58088,30.03965%2050.39739,29.89545%2050.40538,29.75124%2050.50518,29.63839%2050.48124,29.33744%2050.27333,28.94245%2050.14493,28.44714%2050.12885,26.49412%2050.19312,26.10539%2050.12483,25.5035%2050.10071,24.93295%2050.02424,24.83205%2049.82627,24.44836%2049.77771,24.20762%2049.84083,23.83898%2050.05384,23.66594%2050.22742,23.55309%2050.34279,23.58319%2050.42434,23.50345%2050.47725,23.8465%2050.52489,24.68217%2050.41664,25.27152%2050.39739,25.45334%2050.3374,25.98627%2050.32539,27.22767%2050.3734,27.27783%2050.40538,27.27783%2050.48124,27.17752%2050.64056,26.92673%2050.68428,26.51919%2050.66441,25.6477%2050.78348,24.71351%2050.81122,24.45018%2050.8627,23.69781%2050.8983,23.42822%2050.96942,23.27147%2051.08378,23.11063%2051.18731,23.03869%2051.3915,23.05806%2051.4812,23.14384%2051.63087,23.17743%2051.70578,23.24639%2051.85318,23.35925%2051.9808,23.64766%2052.06953,23.41568%2052.18884,23.69546%2052.42652,24.50191%2052.78822,26.14615%2052.87156,27.03723%2052.79391,27.36718%2052.80339,27.92518%2052.75788,28.42833%2052.8337,28.65561%2052.95851,28.80608%2052.96984,28.9252%2052.90182,28.91267%2052.76926,28.94401%2052.69713,29.10076%2052.65531,29.28258%2052.71992,29.29512%2052.88291,29.15091%2053.01136,29.10076%2053.11309,29.10076%2053.22208,29.13211%2053.26336,29.28258%2053.26336,29.37036%2053.18077,29.42051%2053.07544,29.41424%2053.00758,29.54105%2052.8386,29.79481%2052.74518,29.94303%2052.78881,29.90698%2053.08817,29.94703%2053.22748,30.19139%2053.31851,30.22744%2053.49045,30.17937%2053.6142,30.18338%2053.79205,30.21542%2053.84172,30.41572%2053.83226,30.47981%2053.69018,30.45577%2053.52857,30.5439%2053.27541,30.51586%2053.11462,30.39168%2052.95202,30.40997%2052.78895,30.55761%2052.70397,30.71252%2052.70103,31.09193%2052.59309,31.46952%2052.56221,32.51852%2052.51649,33.60346%2052.55493,33.83135%2052.57759,34.0485%2052.56863,34.14038%2052.55133,34.17693%2052.52101,34.20351%2052.44006,34.19354%2052.32851,34.00746%2052.21261,33.84132%2052.06782,33.86541%2051.99792,33.88285%2051.91195,33.76078%2051.87159,33.62564%2051.84467,33.53845%2051.72061,33.41203%2051.58808,33.22021%2051.55557,33.1679%2051.53659,33.10687%2051.50133,33.01968%2051.28916,32.94121%2051.24279,32.79735%2051.2073,31.71466%2051.06786,31.54303%2050.91727))

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3e624d54467f4b44bb165a28caa770e3:2e9e4697cb34b33b118a166875403bcfe68022842721c78c6afc0d2092a25e4d132460c84812d797b5cee06a85508e9113befbc13ce2d2cc271c36cc40c8a3f9)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1098 - height 507
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-14T11:59:27.274Z',to:'2021-07-14T12:05:27.274Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-14T11:59:27.274Z',to:'2021-07-14T12:05:27.274Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email to use the download API and sent the user an example.
