### ISSUE TITLE
Cannot get data in CSV format

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3516]
**Cannot get data in CSV format**

When I try downloading data, it does not appear in a CSV file format. Rather it appears only as Text Documents and XML Documents, so I am having trouble viewing my data. Why might this be happening, and how can I view my data?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/82fab3a9870f2d004960fe8ccc944cbb:a18c0855422ecbdae6d395c8f4e93b22747a21780d21ce1356651be3f3da2fb62015d37d173ee9b653ba84f501a04d196b2282fcad367302daabc0e84696ae15)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0324748-200613084148143
Window size: width 1280 - height 649
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-14T22:57:22.297Z',to:'2021-07-14T23:03:22.297Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-14T22:57:22.297Z',to:'2021-07-14T23:03:22.297Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The format selected for this download is the DARWIN CORE ARCHIVE format. We have two FAQs explaining a bit more what this format is and what it contains:
* https://www.gbif.org/faq?question=dwc-download
* https://www.gbif.org/faq?question=what-is-inside-a-gbif-download-zip-file
 
You are very welcome to select a different download format. Here is a list of the formats available: https://www.gbif.org/faq?question=download-formats

> Replied by email
