### ISSUE TITLE
derived dataset - csv header

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3521]
**derived dataset - csv header**

If you upload a CSV with column headers, you get an error message that isn't very helpful. Could we improve this or perhaps ignore the first line if it looks like a header?

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/8097010dba4806a215cf131938450479:f19572545310a29b1b016f0c58b04894d2b592e3fa88b573cbf458ba98537563408f5cdb63c7177cb516040126a3a0a39cceed022b5d8357fb0b2dba9e8d2088)
System: Chrome 91.0.4472 / Mac OS X 10.15.7
Referer: https://www.gbif.org/derived-dataset/register
Window size: width 1436 - height 1187
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-23T09:07:33.194Z',to:'2021-07-23T09:13:33.194Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-23T09:07:33.194Z',to:'2021-07-23T09:13:33.194Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
![Screenshot 2021-07-23 at 11 11 16](https://user-images.githubusercontent.com/21358085/126761487-2f52af17-7d30-4819-8b2b-090e50acf0fe.png)

(ref https://github.com/eveskew/plant_rapid_assessment/issues/1)
