### ISSUE TITLE
Inachis io is synonymous with Aglais io and the latter is valid.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3522]
**Inachis io is synonymous with Aglais io and the latter is valid.**

Inachis io is synonymous with Aglais io and the latter is the valid name.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6962bb21a406858d0d23314a4cdf8e8c:b543d2213a4be4451282f23910567b02de704af2c9fc50f407e08d196ca03661627bf57402dbfb35bd2c172e8ba7cf46115ee094d14f9ff0c9d4902cc8b3f869)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/species/5881450
Window size: width 2560 - height 1329
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-26T04:34:04.049Z',to:'2021-07-26T04:40:04.049Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-26T04:34:04.049Z',to:'2021-07-26T04:40:04.049Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The original checklist ([Taxon list of animals with German names (worldwide) compiled at the SMNS](https://www.gbif.org/dataset/88f4e35a-bdf8-4aa2-9a1b-56401d4eed15)) is unresponsive.
I contacted the SNSB to forward the feedback and ask if their checklist could be put back online.

**Comment by ManonGros** [comment]
Issue solved in the new backbone update
