### ISSUE TITLE
Species Lookup - CSV export should escape quotes

### ISSUE THREAD

**Issue by fmendezh** [gbif/portal-feedback#3523]
This issue was notified by email:
_I am writing because I encountered a little issue with the species lookup under https://www.gbif.org/tools/species-lookup . Please forward it to the developers in case I got the wrong address.

I uploaded a csv file which contained an entry with double quotes in the name: Citrus grandis "Tomentosa", to be exact (escaped "Citrus grandis ""Tomentosa""" in the file). Import worked fine and the list view displayed the entry correctly, but when I exported the result to CSV again, the double quotes were not escaped, so the file was messed up._

**Comment by MortenHofft** [comment]
We don't use any library to generate the csv. That might well be a good idea. we simply concatenate strings. Quotes are now escaped, but it is likely that there are other cases we do not properly handle.
