### ISSUE TITLE
Download runs but occurence.txt is empty

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3526]
**Download runs but occurence.txt is empty**

I'm trying to download a dataset with just under 150,000 occurrences. The occurrence dataset link is https://www.gbif.org/occurrence/download/0333002-200613084148143 and for whatever reason, the download appears to run, but generates only a 6kb zip file which, when opened, contains the files I would expect but no information inside!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d5022cd27c4f88199472de303227d3bf:d14ec273a6b0089851dfd04140f151a47e323385881f85d1a97085feb6bc9646350ae54c55c738b00dadc003894ec8161aad5fc0c2c7aca13dfe102317d0c99c)
System: Chrome 92.0.4515 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/0333002-200613084148143
Window size: width 1120 - height 625
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-27T23:12:41.334Z',to:'2021-07-27T23:18:41.334Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-27T23:12:41.334Z',to:'2021-07-27T23:18:41.334Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.

See https://github.com/gbif/parsers/issues/26 

https://github.com/gbif/portal-feedback/issues/3324

https://github.com/gbif/portal-feedback/issues/2387

etc.
