### ISSUE TITLE
species missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3527]
**species missing**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7dc088535d3ca6ae1095db942d9fcc31:681067e59bdf8490efa356899af38d4e0ab28db74591a1682944b3e9a2b8a2441b6f9b55ad68428292ea390888235dda2bb7ddcea76e1ed880a87bf9d1c14adc)
System: Chrome 92.0.4515 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-29T12:42:35.584Z',to:'2021-07-29T12:48:35.584Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-29T12:42:35.584Z',to:'2021-07-29T12:48:35.584Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
copy of  #3528
