### ISSUE TITLE
Hi! It appears that Oxalis stricta is missing from GBiF. This Oxalis species appears to be valid and separated from other species by a set of morphological characters (Groom et al. 2017 10.3989/collectbot.2017.v36.004); and it is considered valid by Plants of the World Online (http://www.plantsoftheworldonline.org/taxon/urn:lsid:ipni.org:names:178499-2). Therefore, this species appears to merit it's inclusion in GBiF as a distinct taxon. Nevertheless, if the taxonomic criterion of GBiF is that Oxalis stricta is a synonym of another Oxalis species, this could be introduced in the backbone... at present, Oxalis stricta retursn HIGHERRANK rather than SYNONYM (when rgbif::name_backbone() is used). Many thanks!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3528]
**Hi! It appears that Oxalis stricta is missing from GBiF. This Oxalis species appears to be valid and separated from other species by a set of morphological characters (Groom et al. 2017 10.3989/collectbot.2017.v36.004); and it is considered valid by Plants of the World Online (`http://www.plantsoftheworldonline.org/taxon/urn:lsid:ipni.org:names:178499-2).` Therefore, this species appears to merit it&#39;s inclusion in GBiF as a distinct taxon. Nevertheless, if the taxonomic criterion of GBiF is that Oxalis stricta is a synonym of another Oxalis species, this could be introduced in the backbone... at present, Oxalis stricta retursn HIGHERRANK rather than SYNONYM (when rgbif::name_backbone() is used). Many thanks!**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d64f6749e3a45e56120f72bc96aae07e:76051fd861ea43aa69cd56b9188e2f3072b7d359b9d567f170d8911edbabf052272eb40328991016b738f7f4c9e0cff84190084cebf0ee55dd6a264bfaa0b4d2)
System: Chrome 92.0.4515 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-29T12:48:13.448Z',to:'2021-07-29T12:54:13.448Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-29T12:48:13.448Z',to:'2021-07-29T12:54:13.448Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It seems that Oxalis stricta L. is currently a synonym of Oxalis dillenii Jacq. in the backbone: https://www.gbif.org/species/9823072.

In the PLAZI treatment, it seems to be its own species: https://www.gbif.org/species/164946434
It is its own species in the CoL: https://www.catalogueoflife.org/data/taxon/7NJ5M

@mdoering do you know why this species is a synonym in the backbone?

**Comment by mdoering** [comment]
The last build logs from march indicate that O. stricta came in as a synonym from COL:

`1243322:DEBUG [03-02 20:27:03,284+0000] [main] org.gbif.checklistbank.nub.NubBuilder:  process HETEROTYPIC_SYNONYM SPECIES Oxalis stricta L.
`

In the december release of COL you can see it was listed as an ambiguous synonym, i.e. pro parte for _Oxalis corniculata_ and _Oxalis dillenii_:
https://data.catalogueoflife.org/dataset/2242/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=oxalis%20stricta&sortBy=taxonomic

Should be good in the next release then
