### ISSUE TITLE
Expose programme filter for resourceType projects

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#353]
**Expose programme filter for resourceType projects**

Feature request: By making project search results filterable based on programme, we could (for example) provide a programmatic link to all CESP projects related to ALA tools, for instance, without complicating the content model.

Rating its priority as low now, because I can use the 'capacity enhancement' term in the 'purpose' vocabulary to get the same result.

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb
Reported by: @kcopas
System: Safari 10.1.2 / Mac OS X 10.12.6
Referer: https://www.gbif.org/resource/search?q=ala&contentType=project
Window size: width 1425 - height 1091
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T14:55:53.281Z',mode:absolute,to:'2017-08-18T15:01:53.281Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T14:55:53.281Z',mode:absolute,to:'2017-08-18T15:01:53.281Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
@kcopas yes it is a shame we don't have it in the search. But it sounds like it is the same as this list https://www.gbif.org/programme/82953/living-atlases#projects ?

**Comment by kcopas** [comment]
No, it would be a hybrid: CESP Projects that fund ALA-related activities. Because these examples actually cross and overlap two programmes, I'm suggesting that a programme facet could be paired with keyword search to show the group. 

I hacked it another way by using the term 'capacity enhancement ' from a controlled vocabulary

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/531
