### ISSUE TITLE
Is there a wholistic way to download all of the records from a given publisher used in citations. Eg. I would like to summarize record citations for a given publisher, so it would be useful if it was possible to  download all of the records x citation x dataset, rather than filtering each of the large cited datasets for records from the publisher's datasets

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3536]
**Is there a wholistic way to download all of the records from a given publisher used in citations. Eg. I would like to summarize record citations for a given publisher, so it would be useful if it was possible to download all of the records x citation x dataset, rather than filtering each of the large cited datasets for records from the publisher&#39;s datasets**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c141a30643cce32bb459e51f2c65372a:2b69b6fe1d1609dd274e1f7ec31eec0bcca97880eae302de537df30c8dc0f234c3b86c2ac927b8e17efa8bd8b1c0efda60162bfdd3aaa66320c5a753bb028a91)
System: Firefox 90.0.0 / Mac OS X 10.14.0
Referer: https://www.gbif.org/faq?q=citation
Window size: width 1337 - height 717
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-05T21:59:03.001Z',to:'2021-08-05T22:05:03.001Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-05T21:59:03.001Z',to:'2021-08-05T22:05:03.001Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

There is not easy way for you to get the occurrence records for a given publishers attached to citations. However, we can do it for you if this is a one-time request.
> Contact us at helpdesk@gbif.org
