### ISSUE TITLE
Incorrect authorship for some Beckhoplia species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3537]
**Incorrect authorship for some Beckhoplia species**

We were notified of this issue by email:

Some of the Beckhoplia species have the authorship "Dombrow & Colville" which is incorrect (for example this one: https://www.gbif.org/species/10721415). According to the email we received, the authorship should be just "Dombrow".

The problem is that I don't know where the issue comes from. The species coming from the PLAZI dataset all have the correct authorship: https://www.gbif.org/species/search?dataset_key=a43d0118-9df5-4970-a316-0dae5c9caebf&origin=SOURCE&advanced=1

And I cannot find any example of species with the authorship "Dombrow & Colville" in the CoL nor in the World Scarabaeidae Database: https://www.catalogueoflife.org/data/search?SECTOR_DATASET_KEY=1027&extinct=false&extinct=_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=extinct&facet=environment&limit=50&offset=0&q=Beckhoplia&rank=species

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/508a173504d6cebfd191938f05a30ae3:158e9313057cdd4d59571e4f03d8fa3a416029c6a59c22d33b3681d1ae9be305718f46c3ae195291001f0cff083756ab837d962c8b085a1ce47d75853dbeb9e2)
System: Safari 14.1.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/search?q=Beckhoplia
Window size: width 1339 - height 793
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-10T08:03:47.119Z',to:'2021-08-10T08:09:47.119Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-10T08:03:47.119Z',to:'2021-08-10T08:09:47.119Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@mdoering could you help me figure out what happened?

**Comment by mdoering** [comment]
It was wrong in the June version of COL: 
https://www.gbif.org/species/174032754
and https://data.catalogueoflife.org/dataset/2315/taxon/L63Q

Will be fixed in the next backbone due in September using the new annual release of COL:
https://data.catalogueoflife.org/dataset/2328/taxon/L63Q

**Comment by ManonGros** [comment]
Solved in the new backbone.
