### ISSUE TITLE
Biorhiza pallida and Diplolepsis pallida are not synonyms

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#354]
**Biorhiza pallida and Diplolepsis pallida are non synonyms**

Biorhiza pallida seems to have been incorrectly synonymized with Diplolepsis pallida. The former is seems to be a European cynipid wasp that forms galls on oaks, and the latter a European cynipid wasp that forms galls on roses. I'm not an expert on either though, so maybe I'm missing some recent changes in taxonomy.

-----
fbitem-species1309640
Reported by: @kueda
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/species/1309640
Window size: width 1310 - height 814
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T16:58:47.286Z',mode:absolute,to:'2017-08-18T17:04:47.286Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T16:58:47.286Z',mode:absolute,to:'2017-08-18T17:04:47.286Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kueda** [comment]
Ugh, are *not*.

**Comment by mdoering** [comment]
Fauna Europaea indicates that the 2 are homotypic synonyms:
http://www.eu-nomen.eu/portal/taxon.php?guid=urn:lsid:faunaeur.org:taxname:197501#

And from the authorship this seems very true, so I am closing the issue as  invalid until we get contradicting evidence.

Other supporting evidence:

- https://nl.wikipedia.org/wiki/Aardappelgalwesp
- [Hymenoptera: Cynipidae, Band 16 von José Luis Nieves-Aldrey](https://books.google.de/books?id=P3n5Ivjg2lsC&pg=PA547&lpg=PA547&dq=Diplolepsis+pallida&source=bl&ots=FHcsRh6y1u&sig=dNHAqbOzKZRsZ-lWkc9ua29iSbc&hl=de&sa=X&ved=0ahUKEwin9r71jaXZAhWC6CwKHf69D34Q6AEIXTAM#v=onepage&q=Diplolepsis%20pallida&f=false)
