### ISSUE TITLE
Bursaphelenchus xylophilus and Bursaphelenchus mucronatus are separate distinct species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3540]
**Bursaphelenchus xylophilus and Bursaphelenchus mucronatus are separate distinct species**

Summary
For  the species Bursaphelenchus xylophilus on GBIF here - https://www.gbif.org/species/5777790 
It is listed as Synonym of Bursaphelenchus mucronatus, and Accepted name Bursaphelenchus mucronatus. 

Bursaphelenchus xylophilus and Bursaphelenchus mucronatus are separate distinct species. For instance on NCBI and also throughout a large amount of literature they are considered separate species. In addition, Bursaphelenchus xylophilus is  known as an introduced invasive species in Europe that causes pine wilt disease (PWD) whereas Bursaphelenchus mucronatus is a native species to Europe that also affects pine but is regarded as a much weaker pathogen. 

In addition, following contact with the source of the dataset, we believe this is a misinterpretation on the side of GBIF. With both Bursaphelenchus xylophilus and Bursaphelenchus mucronatus considered valid species.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4ee3355b4f23e59218ea39e86e32a462:c80322120653527d88effd0b0fbff694e5b3cf875979c7912c77837dad652d6117d6b43249f661f744df8c89cd312ad92f01d8b61f1260dbe07d7b19f3182a61)
System: Chrome 92.0.4515 / Windows 8.1.0.0
Referer: https://www.gbif.org/species/5777790
Window size: width 1920 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-12T12:58:16.814Z',to:'2021-08-12T13:04:16.814Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-12T12:58:16.814Z',to:'2021-08-12T13:04:16.814Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
Dyntaxa publisher contacted by email.

**Comment by ManonGros** [comment]
Issue solved in the new backbone.
