### ISSUE TITLE
Integration of existing database into GBIF

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3543]
**Integration of existing database into GBIF**

Daugavpils University has a database on alien species of trees in the arboretum. The data is in either a shape file or a GDB (about 16000 records in database). Is it possible to integrate this data directly into GBIF? For example, using specialized APIs. Dmitry Shchigel advised to contact you with this question

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f040e60ea43a05db4be76f8505573d59:c233690d44aaf5339a9508a8ee491c568787f01e1ce0356a7497f6a5e755f11a5023ab7f3679166298e78a0cfb1b84d27f06b095d63e7e21043a59f947dee275)
System: Chrome 92.0.4515 / Windows 10.0.0
Referer: https://www.gbif.org/faq
Window size: width 1280 - height 609
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-18T09:25:47.143Z',to:'2021-08-18T09:31:47.143Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-18T09:25:47.143Z',to:'2021-08-18T09:31:47.143Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

There is no way to integrate a Shapefile or GBD directly in GBIF. It has to be converted into a GBIF compatible format first. There are a few formats suitable. The most common one is the [Darwin Core Archive](https://dwc.tdwg.org/text/) format. In its simplest form, this format is a CSV file with headers corresponding [Darwin Core terms](https://dwc.tdwg.org/terms/).
The terms and possible extensions used will depend on the dataset class you choose. [Here](https://data-blog.gbif.org/post/choose-dataset-type/) is a blogpost summarizing the different types of dataset classes that can be made available on GBIF. I suspect that your data could perhaps be formatted as a checklist with a “distribution” extension.

There are a number of tools that can help you format and register your data on GBIF. The IPT is the most common one but there are others. Most of them are described in [this blogpost](https://data-blog.gbif.org/post/installations-and-hosting-solutions-explained/).
That being said, you can also format the data yourself and register it on GBIF by using [our API](https://www.gbif.org/developer/registry). We are happy to help you format the data and answer all your API related questions.
