### ISSUE TITLE
Suggest a word change.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3545]
**Suggest a word change.**

On the page [Data quality requirement: Checklist Dataset](https://www.gbif.org/data-quality-requirements-checklists), the first sentence of "Required information" says "...publishing an occurrence dataset." Should it be "...publishing a checklist dataset" to better align with the context? And the page doesn't mention about attaching an occurrence extension.

-----

Github user: @ckotwn
User: [See in registry](https://www.gbif.org/api/feedback/user/0e6ee58f4cdebab159f91d12da7315b8:9c9b57544c7fa2b52d911a958e771266ce9ff0c1b5aad0c2fdea2806af2ed634e1a4925c9d8feddcd8a9a346a53feafebecb17c4790a78d721ced5088d8881a6)
System: Firefox 91.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/data-quality-requirements-checklists
Window size: width 1003 - height 1584
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-19T04:13:14.192Z',to:'2021-08-19T04:19:14.192Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-19T04:13:14.192Z',to:'2021-08-19T04:19:14.192Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ckotwn** [comment]
This suggestion is included in #3553.

**Comment by dnoesgaard** [comment]
(closing this as it's part of the mentioned issue)
