### ISSUE TITLE
https://www.gbif.org/zh-tw/data-quality-requirements-checklists

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3546]
**`https://www.gbif.org/zh-tw/data-quality-requirements-checklists`**

On the last point of "Strongly recommended" should be corrected as: "last **but** not least...the dataset will **be**..."

-----

Github user: @ckotwn
User: [See in registry](https://www.gbif.org/api/feedback/user/f7372eee866a3d6671d7552b25d6b4a3:fd402277261c08f894d7bc99aacdc503ea3116b570553c4bafef5e261c84850b3df39db9d6eeaae35f2e9cacdc8a2b3b256eaf7014ec80c95badac27be52dd8d)
System: Firefox 91.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/zh-tw/data-quality-requirements-checklists
Window size: width 1003 - height 1584
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-19T05:46:42.253Z',to:'2021-08-19T05:52:42.253Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-19T05:46:42.253Z',to:'2021-08-19T05:52:42.253Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ckotwn** [comment]
This suggestion is included in #3553.
