### ISSUE TITLE
Creative commons licenses

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#355]
**Creative commons licenses**

I searched for Hemideina thoracica under the "simple" search and ticked CC0 1.0 and CC BY 4.0 as limiting factors. Two images were returned of the species but when I clicked on the images the details stated that they were licensed under CC BY NC ND license. This is not just confusing,  it is also irritating as I'm wanting images I can use in Wikipedia which only allows images under CC0 CC BY & CC BY SA licenses.

-----
fbitem-90ca04c707cd953f778e8789ed7ec98e67b20053
Reported by: Siobhan_Leachman@yahoo.co.nz
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/gallery?basis_of_record=PRESERVED_SPECIMEN&taxon_key=1725451&license=CC_BY_4_0&license=CC0_1_0
Window size: width 1440 - height 803
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T17:39:44.676Z',mode:absolute,to:'2017-08-18T17:45:44.676Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T17:39:44.676Z',mode:absolute,to:'2017-08-18T17:45:44.676Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
The search will return the occurrence records with the specified licences (as opposed to the images linked to the records). Records and images can have different licences but the search is on records. That can be confusing when searching with the gallery.

Maybe we could label the filter Occurrence License or Record License?

**Comment by MortenHofft** [comment]
Makes sense and also add a notification to the gallery in case there is a license filter. I've also created a suggestion for expanding the API to allow for more complex image search https://github.com/gbif/portal16/issues/505

**Comment by MortenHofft** [comment]
There is now an explanation in top of the gallery.
@dnoesgaard could you please provide the text. Currently it simply reads: `Be aware that images can have a different license than the occurrence record`. The license filter has also been renamed to record license.

**Comment by MortenHofft** [comment]
The user have been contacted per email with an explanation

**Comment by dnoesgaard** [comment]
Text:
> Be aware that licenses applied to images may differ from those applied to occurrence records.

Senere kan det være vi skal have et "help" tip til hvordan man checker licensen på billeder :)
