### ISSUE TITLE
Recommended changes for checklist quality requirements

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3553]
**Recommended changes for checklist quality requirements**

While working on the translation for /data-quality-requirements-checklists, I have found that there are changes needed for the original English text, which includes:
- missing links
- old, redirecting links
- rooms for clarity
- consistency, such as plural terms like "creator(s) that may better be "creator" since all other terms use the form as stated in the standard documents. 

I have made a diff at https://bit.ly/3kkDSzB, please review, and hopefully if it's ready enough, as easy for you as copy-n-paste.

Thanks!

-----

Github user: @ckotwn
User: [See in registry](https://www.gbif.org/api/feedback/user/281d58412e0963cec97c05812c384faa:2c1fb7123c5bf7397c4cfda72e4c627e0fa8645ed5aa584e8ff84e3624b3e9c1d26a2a0274c5a07d921f24eb8feca8e267462534a8dce1e39a655830b879173f)
System: Firefox 91.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/zh-tw/data-quality-requirements-checklists
Window size: width 1504 - height 1584
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-24T12:48:11.418Z',to:'2021-08-24T12:54:11.418Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-24T12:48:11.418Z',to:'2021-08-24T12:54:11.418Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Thanks for the thorough review, @ckotwn.

The suggested changes all look fine to me, but I would prefer if someone from @gbif/content could take a look as well? (ping @ahahn-gbif)

**Comment by ahahn-gbif** [comment]
Thank you very much, @ckotwn! That is very helpful indeed. The suggested changes look fine to me, too, and I would be happy to see them in production.

**Comment by dnoesgaard** [comment]
Thanks both—the changes to the page have now been made.
