### ISSUE TITLE
Taxonomy classification issue: Odontophotopsis aufidia is a species of velvet ant (Mutillidae) rather than Formicidae

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3555]
**Taxonomy classification issue: Odontophotopsis aufidia is a species of velvet ant (Mutillidae) rather than Formicidae**

I pulled all Formicidae species in Southern California and Odontophotopsis aufidia was included; although it is in the Mutillidae family.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/54c9fe688f34fd8ce38ecdf36f87540a:5753f0800dbc03bbb0304384f7af9f97c104812be40d4474e854a8657585c0330ddf26975520dd15a5e5de5df1a3bee511ee1a8d8ee12a430d0b931bbec4b671)
System: Chrome 92.0.4515 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1707 - height 802
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-24T14:49:22.404Z',to:'2021-08-24T14:55:22.404Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-24T14:49:22.404Z',to:'2021-08-24T14:55:22.404Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The classification is correct in the original PLAZI treatment: https://www.gbif.org/species/134031441

The issue seems to come from the classification of the genus in the IRMNG: https://www.irmng.org/aphia.php?p=taxdetails&id=1127689 which shows Odontophotopsis Viereck, 1903 as a Formicidae when it should be Mutillidae.

@TonyRees would it be possible to take a look and see if this could be updated?

**Comment by ManonGros** [comment]
Contacted the IRMNG by email.

**Comment by TonyRees** [comment]
OK, fixed now at the IRMNG end, see https://www.irmng.org/aphia.php?p=taxdetails&id=1127689 - also upgraded genus status to "accepted". BTW the original (bad) assignment came in from a batch of GBIF data (from AntWeb) in around 2012, so the error presumably originated there - tried to check the AntWeb site (also AntBase) but got an error message just now in both cases.

It seems that this genus is not currently in CoL or ITIS ... ITIS has the family with a single genus (Dasymutilla) but according to Wikispecies there are around 37, see https://species.wikimedia.org/wiki/Mutillidae ; CoL has this genus plus one more (Ephutomorpha) so a bit of a gap there. IRMNG has 203 genus names currently assigned to this family, but many of them are still unassessed - a job for someone to take further (along with similar in many other families...)

Cheers - Tony

**Comment by ManonGros** [comment]
Issue solved in the new GBIF backbone taxonomy
