### ISSUE TITLE
No or fuzzy institution match

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3558]
**No or fuzzy institution match**

834K records with institution code and yet most do not match any institution (at least not without a fuzzy match)

https://www.gbif.org/occurrence/search?basis_of_record=PRESERVED_SPECIMEN&basis_of_record=FOSSIL_SPECIMEN&institution_code=smf&publishing_country=DE&protocol=BIOCASE&advanced=1

Perhaps the publisher could add an institutionID pointing to the GrSciColl entry?
The code isn't unique so we cannot match on the code alone
https://registry.gbif.org/institution/search?code=SMF

This issue is mostly just to test that node staff get notified

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/53fd385673a0ee8940f6e2c9f48c9765:14da208b2156e6b083f2687fcd56e1682bd02e0b06c49c804eaefc8da853177c08d3a6df09c028c6447d50f1a308f60c31c34b2147930d96eefaea129910880f)
System: Chrome 92.0.4515 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/3111110313
Window size: width 1440 - height 766
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-26T08:08:19.073Z',to:'2021-08-26T08:14:19.073Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-26T08:08:19.073Z',to:'2021-08-26T08:14:19.073Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 96596036-f762-11e1-a439-00145eb45e9a
publishingOrgKey: c76cf030-2a95-11da-9cc1-b8a03c50a862
Network keys: 17abcf75-2f1e-46dd-bf75-a5b21dd02655 
Node handles: @jholetschek

**Comment by MortenHofft** [comment]
It worked - I'm closing this as it was really mostly to test that @jholetschek got a notification (this issue is real though in case someone can do anything about it)

**Comment by jholetschek** [comment]
It works - I got a notification!

**Comment by jholetschek** [comment]
Is there a way to get a list of the datasets contained in this list (any maybe the URLs for these datasets)?

**Comment by ManonGros** [comment]
@jholetschek would this work for you? https://www.gbif.org/occurrence/datasets?basis_of_record=PRESERVED_SPECIMEN&basis_of_record=FOSSIL_SPECIMEN&institution_code=smf&issue=COLLECTION_MATCH_NONE&issue=INSTITUTION_MATCH_FUZZY&issue=INSTITUTION_COLLECTION_MISMATCH&issue=COLLECTION_MATCH_FUZZY&publishing_country=DE&protocol=BIOCASE&advanced=1

**Comment by MortenHofft** [comment]
Or using the [website charts](https://www.gbif.org/occurrence/charts?basis_of_record=PRESERVED_SPECIMEN&basis_of_record=FOSSIL_SPECIMEN&institution_code=smf&issue=COLLECTION_MATCH_NONE&issue=INSTITUTION_MATCH_FUZZY&issue=INSTITUTION_COLLECTION_MISMATCH&issue=COLLECTION_MATCH_FUZZY&publishing_country=DE&protocol=BIOCASE&advanced=1&d=datasetKey)

or using [the API](https://api.gbif.org/v1/occurrence/search?basis_of_record=PRESERVED_SPECIMEN&basis_of_record=FOSSIL_SPECIMEN&institution_code=smf&issue=COLLECTION_MATCH_NONE&issue=INSTITUTION_MATCH_FUZZY&issue=INSTITUTION_COLLECTION_MISMATCH&issue=COLLECTION_MATCH_FUZZY&publishing_country=DE&protocol=BIOCASE&limit=0&facet=datasetKey&facetLimit=100)

**Comment by MortenHofft** [comment]
But above leave out occurrences like https://www.gbif.org/occurrence/3062763347 - I'm not sure why that doesn't have a flag. @ManonGros you probably know better than I?

**Comment by jholetschek** [comment]
I can see it's only Senckenberg datasets. That's up to the museum... I'll keep that in mind and will try to remind them as soon as I get in contact!

**Comment by ManonGros** [comment]
I don't know why the labels weren't showing but I reinterpreted the dataset and it is good now: https://www.gbif.org/occurrence/3062763347
