### ISSUE TITLE
https://www.gbif.org/analytics

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#356]
**https://www.gbif.org/analytics**

Should redirect to https://www.gbif.org/analytics/global

-----
fbitem-b62f92af778035c25985ab887a761ba20dfe4d26
Reported by: @MortenHofft
System: Chrome 59.0.3071 / Mac OS X 10.11.5
Referer: https://www.gbif.org/analytics/global
Window size: width 1255 - height 785
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T18:59:17.890Z',mode:absolute,to:'2017-08-18T19:05:17.890Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T18:59:17.890Z',mode:absolute,to:'2017-08-18T19:05:17.890Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
fixed by https://github.com/gbif/gbif-configuration/blob/master/portal16/common/redirects.json#L4
