### ISSUE TITLE
Nemopistha sinica

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3567]
**Nemopistha sinica**

Nemopistha sinica  There is no data for this species

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6279e3a7d2dcfab09831a3817224ba55:1312733da41f63dbf0e7135890daa8654ddcd5a9f16dacfacf629f055537cccfc529d3e72eccbbc8dbebd8d8438712ce2a2ada8de6cd6c9709add9cf4aea2622)
System: Chrome 92.0.4515 / Mac OS X 10.15.7
Referer: https://www.gbif.org/zh/search?q=Scarabaeus%20erichsoni
Window size: width 1880 - height 759
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-30T08:59:28.184Z',to:'2021-08-30T09:05:28.184Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-08-30T08:59:28.184Z',to:'2021-08-30T09:05:28.184Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Nemopistha sinica C.-k. Yang, 1986 is in the CoL: https://www.catalogueoflife.org/data/taxon/468RT

**Comment by ManonGros** [comment]
@mdoering This species (Nemopistha sinica) is in the catalogue of life but not in the backbone, any idea why that would be?

**Comment by mdoering** [comment]
If you want to make sure it was in COL when the backbone was built you need to check against the version used at that time. In March 2021 it was the december 2020 COL release where it already existed: https://data.catalogueoflife.org/dataset/2242/taxon/468RT

**Comment by mdoering** [comment]
Seem to be a name parsing problem. From the last build logs:

> process ACCEPTED SPECIES Nemopistha sinica C.-k. Yang, 1986
> Rank SPECIES does not match parsed rank SUBSPECIES. Ignore Nemopistha sinica C.-k. Yang, 1986
> Ignore usage 174541595 >Nemopistha sinica C.-k. Yang, 1986< Parsed rank mismatch
>

**Comment by mdoering** [comment]
filed under https://github.com/gbif/name-parser/issues/80

**Comment by ManonGros** [comment]
Thanks!
