### ISSUE TITLE
danaus eresimus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3575]
**danaus eresimus**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d8a35e9ab656562b1028670c7d50a4cc:29fd049a02b9c5707662b656ae984541ff444f8b3848f40d266273dee3c90dc15f1ab2f35fe68f4de454921236f3f0cb54c002e0fb5a17fa93be7c1c205714a8)
System: Chrome 92.0.4515 / Windows 10.0.0
Referer: https://www.gbif.org/species/5714302
Window size: width 1366 - height 657
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-01T00:37:07.973Z',to:'2021-09-01T00:43:07.973Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-01T00:37:07.973Z',to:'2021-09-01T00:43:07.973Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It seems like an error, closing
