### ISSUE TITLE
Request for filter: migratory gps data on all birds originating from a specific geo location (Country/region)..

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3576]
**Request for filter: migratory gps data on all birds originating from a specific geo location (Country/region)..**

How would I filter unique birds (or multiple paths of all birds) that have visited a specific specific geographic location?

For example: All birds that have visited Latvia & full migratory paths:

-----

Github user: @OtoGodfrey
User: [See in registry](https://www.gbif.org/api/feedback/user/96183769452642f680b54d93d426c36c:910bb371cb7a76e52437f5b7dec0f1d171d61111cfb681a97f9e35da3c0c6e3ab5ed5161c40097b217c3882db709dfb97670174dff2e72248f7bf5d46c82527c)
System: Firefox 91.0.0 / Windows 7.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 2560 - height 1299
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-02T01:18:52.116Z',to:'2021-09-02T01:24:52.116Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-02T01:18:52.116Z',to:'2021-09-02T01:24:52.116Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi @OtoGodfrey,

I don't think there is an ideal solution for that but there are some things you can try:

- Look for birds that have been observed in a given region or country: https://www.gbif.org/occurrence/search?country=LV&taxon_key=212&occurrence_status=present (example with Latvia). You could refine the selection by choosing only migratory species.
- Or look for birds with similar criteria but select a tracking dataset specifically: https://www.gbif.org/occurrence/search?country=LV&dataset_key=712dba38-74cc-4704-87c0-63d1bf8484bc&taxon_key=212&occurrence_status=present (example with Latvia)

Once you have what you need, you can group those birds by organismIDs (https://dwc.tdwg.org/terms/#dwc:organismID) when post processing the data. Not all datasets have them but this is the case for the [BirdMap Data](https://www.gbif.org/dataset/712dba38-74cc-4704-87c0-63d1bf8484bc). You will also be able to select a specific bird in the web interface, for example: https://www.gbif.org/occurrence/search?dataset_key=712dba38-74cc-4704-87c0-63d1bf8484bc&organism_id=112.LV235&advanced=1

Let us know if this answers your question, thanks!

**Comment by OtoGodfrey** [comment]
I figured out how to do individual birds, but the problem is the data
processing is cumbersome, lots of clicking and then it's down to individual
birds.

I have no way of seeing data where Storks / birds from Latvia migrate to.
Maybe there's a preference for birds from Latvia to fly to a specific
region in Africa, but I have no ability to aggregate such information.

Best,
Oto

**Comment by ManonGros** [comment]
Hi @OtoGodfrey, note that you can always download the data selected by clicking on the DOWNLOAD tab and choosing a download format or by using our API. Once downloaded, you can analyse the data with your favourite tool. You don't necessarily need to click around.

This blogpost summarises what to keep in mind when analysing data downloaded from GBIF, perhaps this will be helpful: https://data-blog.gbif.org/post/gbif-filtering-guide/
