### ISSUE TITLE
pdf user guide

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3577]
**pdf user guide**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/dc249b2dd7ea3fe1a595149c864e3819:f09f24e7a4589d0365cb91d731fdaf6a11f5acad836350b74f8c9b22d2e569cf74fc7435fdf2d00afe469672ac5ed325ea61e453bd690060899854c17750a881117cd5eda52762ca662c20a960fcb252)
System: Chrome 92.0.4515 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-03T11:00:32.738Z',to:'2021-09-03T11:06:32.738Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-03T11:00:32.738Z',to:'2021-09-03T11:06:32.738Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
User replied:
Dear Jan,
Thank you for your message and I'm terribly sorry for the incomplete thread. I could not find a way to modify it once posted.
I don't know if the GitHub GBIF portal only deals with technical troubleshooting or also more general topics. But I was just wondering if there is any document that compiles all the information that a new user would need in order to prepare and import data to the GBIF.  

To be continued...

**Comment by jlegind** [comment]
¨This was communicated:

If you are seeking guidance on how to share/publish data to the GBIF network, we has a few guides on data sharing/mobilization:
•	How to select dataset type or class: https://data-blog.gbif.org/post/choose-dataset-type/ 
•	This blogpost deals with publishing platforms: https://data-blog.gbif.org/post/installations-and-hosting-solutions-explained/ 
•	And there is a comprehensive course on data mobilization here (pdf): https://docs.gbif.org/course-data-mobilization/en/biodiversity-data-mobilization-course.en.pdf 

Should you wish to have a more personal hands-on introduction, I would direct you to the GBIF France node.
