### ISSUE TITLE
Spiders don't have any class

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3579]
**Spiders don&#39;t have any class**

The order Araneae doesn't have a class specified. This is probably because in the CoL, Arachnida is a sub-class and not a class: https://www.catalogueoflife.org/?taxonKey=RN

However, I can see there is a patch creating Arachnida as a class: https://www.gbif.org/species/367 but it isn't connected to the Araneae order.

So users looking for Arachnida won't be able to find any spider.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/fc6d2a975a3ddd9e4736ecf541c4f538:dec509d5c5bb7118e6831303ee388e68e08743f7d31ed13d5edcd9ffb137e9542cc9a75342e0822ca67a3e4f0f4ed30221918b7812ceecefc8a9f3e932316b42)
System: Safari 14.1.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/1496
Window size: width 1339 - height 869
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-06T13:10:14.460Z',to:'2021-09-06T13:16:14.460Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-06T13:10:14.460Z',to:'2021-09-06T13:16:14.460Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@mdoering Could you take a look at this issue? Perhaps for the next backbone?

**Comment by mdoering** [comment]
Uh, this is not nice but what should be the fix? We could...
 - allow more ranks in the backbone, see https://github.com/gbif/backbone-feedback/issues/485. But that requires a lot of code changes also for occurrences
 - allow subclass Arachnida to snap to class Arachnida and create that in the backbone patch which we already do?
 - make Arachnida a class again when reading COL with a code change and some manual configs

I would opt for the second now, but put number 1 on the occurrence agenda sooner than later!
@timrobertson100 @fmendezh FYI

<img width="381" alt="image" src="https://user-images.githubusercontent.com/327505/132232494-003d0ff5-6e52-4294-a8b4-b8fe4bca25db.png">

**Comment by mdoering** [comment]
Allowing sub/super ranks to snap to the linnean base rank seems to work fine. It might change our next backbone quite a bit though, hopefully only to the better :)
