### ISSUE TITLE
Filter for europe doesn´t include the Dataset from iNaturalist

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3580]
**Filter for europe doesn´t include the Dataset from iNaturalist**

If i filter for the whole world i can see occurences of the iNaturalist Research-grade Observations dataset in the table (so i see that there are occurences in european countries) but if my filter includes a special continent (for example europe) i have zero occurences in my table. So if i download the table for europe ,the data from the iNaturalist Research-grade Observations dataset are missing.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ad8e91990277f648532abcd718caf1f1:11dca46b2a25e62c1f98969d2f2278e3afe7b8b3b4a03f8aec52f33e8e1e0cc5efee1531bc95db51e3cf9c52025870f7d77445185873c03e3d36b60f2c86fc55)
System: Firefox 91.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?continent=EUROPE&dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7&occurrence_status=present
Window size: width 1536 - height 739
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-06T13:18:54.291Z',to:'2021-09-06T13:24:54.291Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-06T13:18:54.291Z',to:'2021-09-06T13:24:54.291Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
indeed. inat is not mapped to any continents
https://api.gbif.org/v1/occurrence/search?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7&occurrence_status=present&facet=continent&limit=0
That looks like an error during processing

**Comment by MattBlissett** [comment]
https://github.com/gbif/portal-feedback/issues/2387, essentially. The work I'm doing on the geocoder should enable us to introduce continent interpretation soon.

**Comment by MattBlissett** [comment]
This is now implemented: https://www.gbif.org/occurrence/search?continent=EUROPE&dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7
