### ISSUE TITLE
Dear Gbif, This data is reported as doubtful by the data provider. I think it would be also the case for the others in Finland. Best regards

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3584]
**Dear Gbif, This data is reported as doubtful by the data provider. I think it would be also the case for the others in Finland. Best regards**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/619bb59812b192e445e73c1317f90674:08b84b2be6138c3c719e1f363029843e34230d136a6e8c0b119a20022017aa40765875b136a8fa453b7257e6a2d5749646faaed6afcea7b0cb96a74a5df3d334)
System: Firefox 92.0.0 / Mac OS X 10.14.0
Referer: https://www.gbif.org/occurrence/2998833212
Window size: width 2560 - height 1321
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-10T13:26:10.405Z',to:'2021-09-10T13:32:10.405Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-10T13:26:10.405Z',to:'2021-09-10T13:32:10.405Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: baeca59f-e986-49fb-b322-1f940c446bc1
publishingOrgKey: 04fd2e13-6881-4e5c-9dd1-8fdd9ab993c1

**Comment by jhnwllr** [comment]
Will contact publisher. 

Löydös Open Invasive Alien Species Observations

source record is marked as uncertain by citizen science user: 
https://laji.fi/en/view?uri=http:%2F%2Ftun.fi%2FKE.176%2F5f2eb553d5de9c735c60698d#Unit1

**Comment by jhnwllr** [comment]
Publisher has **doubtful as a default** when data is submitted, so I will close the issue.
