### ISSUE TITLE
how do you download a map

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3585]
**how do you download a map**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0431ddfb04565cb6fe22597e5421effc:a9ebcd5e0073f9d7438c7bf5c5dfde31b450906a176d913aca0984301a19b614143cd796eb60b2853cd1a90af5017c3383d4d4c72628a12e229437a81916b38b)
System: Chrome 88.0.4324 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/map?q=Salicornia&has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON((-160%2043,-40%2043,-40%2090,-160%2090,-160%2043))
Window size: width 1920 - height 880
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-10T16:43:17.001Z',to:'2021-09-10T16:49:17.001Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-10T16:43:17.001Z',to:'2021-09-10T16:49:17.001Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
You cannot download the map directly, however, you can download its underlying data and replot the map yourself in your software of choice. Our system is unable to generate downloads with free-text searchers, so you will have to use the “scientific name” field to select the genus you would like to see, for example: https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&taxon_key=3083796&geometry=POLYGON((-160%2043,-40%2043,-40%2090,-160%2090,-160%2043))
Afterwards, all you need to do is to click on the “DOWNLOAD” tab and then select the format you need (I suggest “SIMPLE CSV”). You will receive a notification when the query is processed and the data available.

The data available on GBIF are quite heterogenous so you might want to process them before generating a map. [Here](https://data-blog.gbif.org/post/gbif-filtering-guide/) is a blogpost highlighting what to keep in mind when doing so.
> Replied by email
