### ISSUE TITLE
Change e-mail address

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3586]
**Change e-mail address**

Unable to save changed e-mail address using editing facility. Old e-mail address is defunct.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8d2c1b255ea7e5488a6bac92d8e69e32:5260d121efb25c22a4d0e566eeb5bcb85e9ce6eff89d693d03f50105a26660cd9cf94fcc6c831b93c6eaa9cf05e8be9a34e40b723fc39a6b1541be328d899cf1)
System: Chrome 86.0.4240 / Mac OS X 11.0.0
Referer: https://www.gbif.org/resource/search?q=maxent&contentType=literature&literatureType=journal&relevance=GBIF_USED&peerReview=true
Window size: width 1837 - height 840
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-13T01:09:54.752Z',to:'2021-09-13T01:15:54.752Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-13T01:09:54.752Z',to:'2021-09-13T01:15:54.752Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I'm unable to reproduce the issue. 
What I did was
* Login
* Go to the profile page
* Change the email
* Click Save
* I received an email (to the new email I provided) asking me to confirm.
* I confirmed and can now login with the new email address (and can see in the database that it is updated)

**Comment by ManonGros** [comment]
I contacted the user and he wrote back that the problem has been resolved.
