### ISSUE TITLE
That species (Paraphysomonas flaveolata) doesn't exist...

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#359]
**That species (Paraphysomonas flaveolata) doesn&#39;t exist...**

That species doesn't exist... it is a typo for P. faveolata (already in GBIF), originating from an old version of ITIS, subsequently removed.

-----
fbitem-species4278104
Reported by: Tony.Rees@marinespecies.org
System: Chrome 60.0.3112 / Windows 8.1 0.0.0
Referer: https://www.gbif.org/species/4278104
Window size: width 1366 - height 638
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T20:10:56.087Z',mode:absolute,to:'2017-08-18T20:16:56.087Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T20:10:56.087Z',mode:absolute,to:'2017-08-18T20:16:56.087Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
Fixed as in not refering to IRMNG anymore. But funny enough we do still get the species through ITIS: https://www.gbif.org/species/102313698

https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=1650&print_version=PRT&source=to_print#null
