### ISSUE TITLE
How do I edit a derived dataset? I initially didn't have a url for my dataset as I downloaded it using an R package so I just included the url for my GitHub where I'm hosting it. It still doesn't appear when you look at the derived dataset that there are any records

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3591]
**How do I edit a derived dataset? I initially didn&#39;t have a url for my dataset as I downloaded it using an R package so I just included the url for my GitHub where I&#39;m hosting it. It still doesn&#39;t appear when you look at the derived dataset that there are any records**

-----

Github user: @TannerMyers
User: [See in registry](https://www.gbif.org/api/feedback/user/6b9bfc05354a2fe847748159f12b22ad:49c415d2674fe474c70f132f95fca368fa01fdc39d570f02d450c3b7a4bc1a74ab5ada1c277132d44403494a72688252f408c23babe49807cf0bad3a0f70c40c)
System: Chrome 93.0.4577 / Mac OS X 10.14.6
Referer: https://www.gbif.org/derived-dataset
Window size: width 1780 - height 883
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-14T20:44:19.179Z',to:'2021-09-14T20:50:19.179Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-14T20:44:19.179Z',to:'2021-09-14T20:50:19.179Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
Hi @TannerMyers, you can log on GBIF.org and check your derived datasets here: https://www.gbif.org/derived-dataset, you should be able to see an "edit" button next to the title like in the example below:
<img width="818" alt="Screenshot 2021-09-16 at 15 19 53" src="https://user-images.githubusercontent.com/7677271/133619626-fd9247fb-5cc5-496a-a96e-2f8bdbad166e.png">

This will allow you to edit your derived dataset.

This blogpost explains how to specify the number of occurrences in a download:
https://data-blog.gbif.org/post/derived-datasets/
