### ISSUE TITLE
Citation question for GBIF occurrence records

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3592]
**Citation question for GBIF occurrence records**

Hello,

I am trying to figure out the best way to cite GBIF as a reference for the occurrences of about 30 species of lichens. I have not downloaded any occurrence data, and am not presenting specific occurrence records. Instead, I am citing GBIF data to support the classification of these 30 species as restricted to North America. It's not clear to me what the best way to cite this would be (I'd love to avoid having 30 separate citations for each species!). Thanks in advance for your help,

Michael

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6c3f50f63ad80a96b72f6626080e63dc:404f0622ee39af75a12539190d05ca52d734593646f62fa1d63e759fe1263482e897cc4629ad5e8e09c87c6a0614ab035424ea261728a9560ce51d46a4f51baf)
System: Chrome 93.0.4577 / Windows 10.0.0
Referer: https://www.gbif.org/citation-guidelines
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-14T22:54:25.514Z',to:'2021-09-14T23:00:25.514Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-14T22:54:25.514Z',to:'2021-09-14T23:00:25.514Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
Replied by email: if only the maps were used without any download this is a bit of a grey area.
> Ideally, the map's underlying data should be cited. You could generate a download with the occurrences containing coordinates for all 30 species at once and cite the DOI provided.
> But this isn’t the only option available, you could also just cite the GBIF backbone taxonomy:
GBIF Secretariat (2021). GBIF Backbone Taxonomy. Checklist dataset https://doi.org/10.15468/39omei accessed via GBIF.org on 2021-09-16.
Or GBIF.org.
