### ISSUE TITLE
Provide a way to find deleted taxa

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3596]
**Provide a way to find deleted taxa**

This is following an email we received on heldpesk.

Several wikidata pages link to detailed GBIF taxa. For example:
* Epithemia turgida https://www.wikidata.org/wiki/Q67834374 
* this wikidata entry previously linked to this “deleted” GBIF species: https://www.gbif.org/species/2627693 
* the wiki data editors have since made the link to the correct entry on GBIF: https://www.gbif.org/species/7443621 

To help the editors maintain the information on wikidata, it would be great if we could easily provide them with a list of the deleted taxa. This would help them identify the records that need updating.

Perhaps have a "deleted" filter or endpoint in the species API?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/b57c73056f1e41a78cd6b43a6bca1829:713bbf4ae891194521c139bc33b3bdd24bc9d3488078e895bd5c9510ead42580752f536813be0e676813c8cf9d061d1a16301f69795dbed1fdcb1547152366ce)
System: Safari 14.1.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/2627693
Window size: width 1339 - height 868
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-16T09:36:01.250Z',to:'2021-09-16T09:42:01.250Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-16T09:36:01.250Z',to:'2021-09-16T09:42:01.250Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
@mnhn-paul
For each new backbone update, a file is generated containing all the deleted taxa (for that update). See for example, the folder of the latest update: https://hosted-datasets.gbif.org/datasets/backbone/2021-09-14/

It isn't as convenient as an API endpoint but this could still be useful.

**Comment by mnhn-paul** [comment]
Thanks @ManonGros for this.
I think this will already be very helpful.

**Comment by mnhn-paul** [comment]
@ManonGros I do have another question related to this:
In the logic of the backbone is there the possibility of a taxon being "undeleted" or "reactivated".
If this would be the case this is something that we would need to take into account in our checks against Wikidata.

thanks

**Comment by ManonGros** [comment]
This is a good question. I don't think so but I am not sure.
@mdoering once a taxon is deleted from the backbone, can it ever be restored?

**Comment by mdoering** [comment]
The API does not allow you to search for deleted taxa, but that might be sth we could add if it is really useful.
We only keep deleted taxa for the backbone, taxa for other datasets are fully removed.

And yes, we can restore once deleted backbone taxa. That is what we call "resurrected" names in the logs:
https://hosted-datasets.gbif.org/datasets/backbone/2021-09-14/

**Comment by davidorme** [comment]
Hope it is ok to resurrect this, but I have a related question. 

We have a tool that validates taxa against the backbone, which occasionally uses GBIF ID to disambiguate taxa. In order to avoid thrashing your API, we mostly use a local version of the backbone database. At the moment, the lookup works using your API if a taxon is deleted: the record is still there but there is a deleted key. However, deleted taxa are _removed_ from the backbone dumps and so a taxon that once passed checking but now has been deleted will fail with updated backbones. We'd like to still be able to trace those historical records.

You mentioned the deleted taxon files per update - if we got _all_ of those and then added them back to the backbone (chronologically, in order to cope with resurrection) would that then be close to what is served from the API?

**Comment by mdoering** [comment]
I believe it would be simple for us to always provide a deleted-all file next to each backbone dump in the exact same [simple format](https://hosted-datasets.gbif.org/datasets/backbone/readme.html). It would be an optional addon to the backbone and link to the still existing taxa via the parentID.

Would that be exactly what you need?

**Comment by davidorme** [comment]
That sounds like it would be perfect - basically import the backbone and then, optionally, import the deleted taxa file, which would just add the new tuples into the same table to include deleted taxa.  

I need to do some intermediate processing because I'm using sqlite3 as a backend but that's my problem :-)

**Comment by mdoering** [comment]
Sorry this took a while, but here is the dump of all deleted records:
https://hosted-datasets.gbif.org/datasets/backbone/current/simple-deleted.txt.gz

I will maintain this onwards from now for all future releases

**Comment by davidorme** [comment]
That's fantastic. Many thanks.

**Comment by davidorme** [comment]
Just for information, the data for the deleted taxa uses the same schema as the main simple backbone. That does _not_ include a field to indicate deleted taxa. So, if you are using this to build a backbone database that includes deleted taxa, it may be worth working out how to tag deleted taxa in that database!

**Comment by mdoering** [comment]
Right. Maybe I should have included the deleted timestamp with the dump

**Comment by davidorme** [comment]
@mdoering Just referring back to something you said above:

> The API does not allow you to search for deleted taxa, but that might be sth we could add if it is really useful. We only keep deleted taxa for the backbone, taxa for other datasets are fully removed.

The scenario I have is where a user has provided a set of names that we validate on name and rank using `species/match` with `strict=True`. If a taxon is found, then the data passes validation, but if we were to revalidate the same dataset after a taxon had been deleted, then `species/match` will not match it and the data now fails validation. 

We do record the ID separately during validation, so could always find the taxon using `species/{int}`, which does return deleted taxa. However, it would be useful for us to be able to revalidate the same inputs, while warning that - although GBIF know about a taxon - it has been deleted and so a new version of the dataset may need compiling.

Not a particularly pressing need, but just a vote to say that we have a use case for making searches return deleted taxa!

**Comment by mdoering** [comment]
We wont be able to include deleted taxa in the species/match, that would mess up results as many of the deletions were bad duplicates/homonyms. Sorry, that won't be possible.

**Comment by davidorme** [comment]
Thanks very much for the update and clarification - very useful to know what is and isn't possible!
