### ISSUE TITLE
Dataset indexing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3597]
**Dataset indexing**

Hello 
How soon will Dataset indexing be continued? 
Thanks

-----

Github user: @ANSozontov
User: [See in registry](https://www.gbif.org/api/feedback/user/35a715c1d5dbab148751ee5ce1f93f93:a8a8dd4f8e3caa350ae3891ca8b161b5fc3e9a57a35e3effb6492d8d7c3b19893bcab7a842d882a147840c66a05288146d82da381bd8a014f97010b7c1d26105)
System: Chrome 93.0.4577 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1536 - height 754
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-16T10:35:25.122Z',to:'2021-09-16T10:41:25.122Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-16T10:35:25.122Z',to:'2021-09-16T10:41:25.122Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
Hi @ANSozontov, we expect the dataset indexing to be paused until next week. We will be posting more information on the health page: https://www.gbif.org/health

**Comment by MattBlissett** [comment]
Hi @Ansozontov,

Indexing was resumed yesterday European-evening-time, and the queue of datasets was processed within an hour or two.  Everything is currently running normally.
