### ISSUE TITLE
Update data papers page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3599]
**Update data papers page**

One of the GB28 videos approved is on data papers; I will refer to the GBIF.org page. It would be very nice to update IF, CiteScore, and prices

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/18ac9fa50731430c1e1106d8ad4102fd:c7de0aac445b6171d0a401ef200680b9817696dd905fcba696e52b739b8346cf1f9882c1f0bb34ca512bcfa5202cf6d51eaaa42a88fc5c4394898c5198bd5302)
System: Chrome 93.0.4577 / Windows 10.0.0
Referer: https://www.gbif.org/data-papers
Window size: width 2048 - height 962
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-19T20:52:23.377Z',to:'2021-09-19T20:58:23.377Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-19T20:52:23.377Z',to:'2021-09-19T20:58:23.377Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by akristensen** [comment]
@dnoesgaard It was last updated in May 2021....think we forgot to change the top of the table, says 2019 right now. OK for me to change it to 2021?  I will check through the list now.

**Comment by dnoesgaard** [comment]
I don't think we have updated the table with 2020 JIF and Citescore yet. These came out around June or so.

**Comment by akristensen** [comment]
thanks @dnoesgaard , I will have a go at updating it !

**Comment by dnoesgaard** [comment]
Actually, I've pulled the new Citescore numbers now. If you could focus on prices, that would be great.

**Comment by dnoesgaard** [comment]
Table has been updated with 202 JIF and Citescore values.

**Comment by akristensen** [comment]
Done, however can't find the price for Global Ecology and Biogeography (GEB is not to be found in the excel price list): https://authorservices.wiley.com/author-resources/Journal-Authors/open-access/article-publication-charges.html
