### ISSUE TITLE
Notatype is "Not a type"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#36]
**Notatype is &quot;Not a type&quot;**

the GBIF typestatus enumeration lacks underscores and the NOTATYPE entry is confusing. It appears to be some sort of type, but in reality it stands for &quot;Not a type&quot; as you can see from the javadocs and from some of the specimen records: https://demo.gbif.org/occurrence/1275042158

Use a different label &quot;Not a type&quot; or just &quot;No type&quot;

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482

System: Chrome 55.0.2883 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/occurrence/search?type_status=NOTATYPE&amp;advanced=1
Window size: width 1440 - height 744
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-13T16:57:33.336Z',mode:absolute,to:'2017-01-13T17:03:33.336Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-13T16:57:33.336Z',mode:absolute,to:'2017-01-13T17:03:33.336Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you for reporting this.
Fixed and closed with https://github.com/gbif/portal16/commit/3be187167e5683993c7f23999e70ba8eadac7605
It will be visible with next build to production
