### ISSUE TITLE
person ID formatting

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3600]
**person ID formatting**

recordedById: `"identifiedByID": "https://www.wikidata.org/wiki/Q5407225, | https://www.wikidata.org/wiki/Q26714396"`

is using two seperators at the same time. `,` and `|`

Other records from the dataset is prefixing with a seperator. E.g. `"identifiedByID": "| https://www.wikidata.org/wiki/Q21338542"` in https://www.gbif.org/occurrence/2867560301

Related issues https://github.com/gbif/pipelines/issues/590 and https://github.com/gbif/pipelines/issues/589

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/0f6a37ca51ada3ca075a563c09a8de7b:0e7d5f4de7e593254cc3820c91e0c82b9cf892d0ebfdf9104c5b61a40b7bdaf03990851d77885f19f27837dd5383088fbd899b573872c246e2bfc0b29706ab97)
System: Chrome 93.0.4577 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/2867518679
Window size: width 1440 - height 766
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-20T09:48:37.365Z',to:'2021-09-20T09:54:37.365Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-20T09:48:37.365Z',to:'2021-09-20T09:54:37.365Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: e45c7d91-81c6-4455-86e3-2965a5739b1f
publishingOrgKey: f314b0b0-e3dc-11d9-8d81-b8a03c50a862
Network keys: 17abcf75-2f1e-46dd-bf75-a5b21dd02655

**Comment by jhnwllr** [comment]
https://dwc.tdwg.org/terms/#dwc:identifiedByID

https://api.gbif.org/v1/occurrence/2867560301/fragment

```json 
  "identifiedBy": "Reidar Elven | Heidi Solstad",
```

Wrote to publisher.

**Comment by rukayaj** [comment]
While investigating this I noticed that identifedByID is not getting published on the IPT at all - see https://github.com/gbif/ipt/issues/1703.

**Comment by rukayaj** [comment]
I have fixed the ',' issue, but I guess we will only see it when the IPT bug gets fixed.

**Comment by rukayaj** [comment]
I think this looks ok and has been resolved, so this issue can be closed now?
