### ISSUE TITLE
How to delete my account permanently?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3601]
**How to delete my account permanently?**

Hello there. Could you please delete the account 'imranaliphd' permanently with all associated information. Thank you.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0100f4b02dcb97cd8e6cb7e39b8c1373:7367252243071ba710f15abdddb3202c0048cea67327c43aa51fd9779ffc20ba7a1fb365a483d95817f6c774e8097d9c07a708c582a88caccb376a1c76941b2d)
System: Chrome 93.0.4577 / Mac OS X 10.15.7
Referer: https://www.gbif.org/user/profile
Window size: width 2319 - height 1220
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-21T07:04:49.280Z',to:'2021-09-21T07:10:49.280Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-21T07:04:49.280Z',to:'2021-09-21T07:10:49.280Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The account has been deleted.
