### ISSUE TITLE
Hello gbif

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3608]
**Hello gbif**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0b81cbbfd78a31dfa7da4e4054c98066:4ff975123d0463e9f41a95af9e86f3afc3bfd743ae6e81e06e8b55d97f96e983bfe6bc8d99a988f6cb12abb16126c36aa6dfc47c47c2fdc36f018aa513ed26f7)
System: Chrome 93.0.4577 / Windows 10.0.0
Referer: https://www.gbif.org/health
Window size: width 1680 - height 882
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-23T12:58:14.141Z',to:'2021-09-23T13:04:14.141Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-23T12:58:14.141Z',to:'2021-09-23T13:04:14.141Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Closing as error. The user left feedback in another issue
