### ISSUE TITLE
Cannot download more than 1 GB

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3609]
**Cannot download more than 1 GB**

Hello GBIF, I wanted to download a 2 GB file as seen here: GBIF.org (23 September 2021) GBIF Occurrence Download  https://doi.org/10.15468/dl.37ztdg.

However, the file I got offered is at a very suspicious 1 GB in total, is this because I was not offered the entire dataset? Is there someway to get a download for the 2 GB file? I wanted to download all 12 million plantae occurances in Denmark

Thank you.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/50af02ba03df8ad1fc4c2e1eabc18f3a:78493cf2387210ba3535642081cb731a95a1e98e5acf8a5788b66f1df23ba620155f750b770d0e8c3cf860a38b505a580fee62937a4883c48bb5b02309c3fe5a)
System: Chrome 93.0.4577 / Windows 10.0.0
Referer: https://www.gbif.org/health
Window size: width 1680 - height 882
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-23T13:00:29.110Z',to:'2021-09-23T13:06:29.110Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-23T13:00:29.110Z',to:'2021-09-23T13:06:29.110Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The file downloaded seems to contain the correct number of lines. Perhaps the size estimate was just incorrect. Could that be?

**Comment by MortenHofft** [comment]
I'm guessing this has to do with the estimate provided here
https://www.gbif.org/occurrence/download?country=DK&taxon_key=6
that says 2gb.

**Comment by MortenHofft** [comment]
@ManonGros we commented same time it seems. Yes that is most likely the case. Those estimates are hard to do. The size depends on the content and not just number of rows. We just do the estimate based on the row count. That isn't to say we couldn't do better.

**Comment by ManonGros** [comment]
Thanks @MortenHofft ! I will let the user know by email. -> Done!
