### ISSUE TITLE
What is the correct way of document the element footprintWKT?

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#3615]
We have a couple of datasets that use this element for transects or plots, however we always get he flag of **Footprint WKT invalid**, we are following the example of TDWG: POLYGON ((longitude1 latitude1, longitude2 latitude2, longitude3 latitude3)) and I have tried some variations like first using latitude, but still got the same flag.

Here is an example of a record with this field documented https://www.gbif.org/occurrence/3337369301
![image](https://user-images.githubusercontent.com/63795703/134681534-4e0ac9c5-5a42-49fc-9623-43526fc0ecc4.png)

So I should like to know what is the correct way of document the element, maybe there is another format or we are doing something wrong.

Thank you very much in advance and have a good day,
@camiplata @SiBColombia

**Comment by MortenHofft** [comment]
I haven't checked the polygon, but sounds likely to be due to https://github.com/gbif/pipelines/issues/509

**Comment by MortenHofft** [comment]
Oh, the polygon isn't closed I see. Start and end coordinates differ. That isn't legal.

**Comment by MortenHofft** [comment]
You probably need to change

invalid open `POLYGON ((-75.6974717 4.3252667, -75.697555 4.32554, -75.6976442 4.32585, -75.6974939 4.3257772))`
to 
legal closed `POLYGON ((-75.6974717 4.3252667, -75.697555 4.32554, -75.6976442 4.32585, -75.6974939 4.3257772, -75.6974717 4.3252667))`

**Comment by AbbyBenson** [comment]
Just wanted to check that you need the start and end dates to be the same for POLYGON specifically. If you use LINESTRING you do not have to, right? Because it should work for transects as well I believe.

**Comment by MortenHofft** [comment]
yes linestrings are not closed. The examples in the wiki article are fairly clear I think
https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry
also highlights that the winding is important (spoiler - it needs to be counter clockwise)
