### ISSUE TITLE
problem importing GBIF backbone taxonomy data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3618]
**problem importing GBIF backbone taxonomy data**

Hello,
I wanted to import GBIF backbone taxonomy from https://hosted-datasets.gbif.org/datasets/backbone/ 
I downloaded “backbone-current-simple.txt.gz” file. I was able to import it, but I didn’t find details about the meaning of each column.
For example, I thought that  column  “u.id” was a unique key for each taxon. And “u.parent_fk”  indicated the “parent” taxon of a taxon. But I detected that not all values of “u.parent_fk”   appear in “u.id”, so some taxons seems to not have parent (for example some genuses).
Where can I find more detailed information in order to  properly understand those data and be able to reconstruct the taxonomic tree?
Thank you very much.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c61032a0944492e29786a8a48bc2f528:e868fbe2378cd183b58ba56bf7abdc1687195207d072a726ef1f1da863de729c1eae3b0a706280fe061a8399b81fef2bff2e5db68389cf6d2ae52b784cc4e5eb)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/es/user/profile
Window size: width 1280 - height 615
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-28T15:43:37.167Z',to:'2021-09-28T15:49:37.167Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-28T15:43:37.167Z',to:'2021-09-28T15:49:37.167Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email
> Your assumptions were correct: “u.id” is a unique key for each taxon and “u.parent_fk” indicated the “parent” taxon of a taxon.
The backbone taxonomy is generated semi-automatically and can contain some errors and discrepancies. So the backbone actually contains taxa with no parent, for example [this genus](https://www.gbif.org/species/1000041). This isn’t ideal and we try to improve that with each version. We appreciate any feedback message to help us improve the backbone.
If you would like to know more about how it is generated, you can check [this blogpost](https://data-blog.gbif.org/post/gbif-backbone-taxonomy/).

> I suggest to try filtering out the taxa with the “doubtful” taxonomic status when reconstructing your taxonomic tree.

> We don’t have any documentation made specifically for the backbone-current-simple.txt.gz file. That being said, the terms for the field used in the Darwin Core Archive version are described in the [Darwin Core Term Reference guide](https://dwc.tdwg.org/terms/).
