### ISSUE TITLE
email in account profile reverts to original

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3619]
**email in account profile reverts to original**

I've tried changing my email for my account several times. I use the edit toggle and change the email field, then save changes. Then if I go back to my account, it shows my original email still. There seems to be a glitch where it will not change my email.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1e7fa72c2796dfc12e7cac3f70ebc79f:03a4dd3c957414264883a13b93e5c4ab8588b68e3a47946d6f22ac72d8d0f40771e2bd4f8f5e21e118612c882d3f2a1cda47573580f6cb139b20b61734dd1b50)
System: Chrome 93.0.4577 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1280 - height 577
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-28T18:55:29.087Z',to:'2021-09-28T19:01:29.087Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-28T18:55:29.087Z',to:'2021-09-28T19:01:29.087Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
It sounds to me like it works, but the user hasn't seen the email. Which makes sense since the UI doesn't inform the user. I've updated the message to tell users to check their email

> user informed per email
