### ISSUE TITLE
Flagging possible sync issue with NHM London

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#362]
**Flagging possible sync issue with NHM London**

Wasn't looking for it, but stumbled across the fact that there's some daylight between the number of records that [NHM London is displaying](http://data.nhm.ac.uk) (3.5 million) and the number that are making it to GBIF (2.9). 

Noting an aborted crawl a couple days ago, too, fwiw.

Better safe than sorry…

-----
fbitem-dataset7e380070-f762-11e1-a439-00145eb45e9a
Reported by: @kcopas
System: Safari 10.1.2 / Mac OS X 10.12.6
Referer: https://www.gbif.org/dataset/7e380070-f762-11e1-a439-00145eb45e9a
Window size: width 1227 - height 765
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-19T07:48:38.167Z',mode:absolute,to:'2017-08-19T07:54:38.167Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-19T07:48:38.167Z',mode:absolute,to:'2017-08-19T07:54:38.167Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
The DWC endpoint returns 404.

**Comment by ManonGros** [comment]
It seems like this is no longer an issue. We have the same number of occurrences as the NHM London announces on it website (minus the mineralogy collection).
