### ISSUE TITLE
How to open MVHF file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3621]
**How to open MVHF file**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9a0024a371d7e1304a2726e2960c8515:bf93f46df8902f01a383a5e87e7526f9600c43db41b7113530a150c48398bdf8fdf0b94353593604ede17f3d48728fa4c328a153a286632de7d042c302c88b50)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0011390-210914110416597
Window size: width 1366 - height 568
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-29T15:46:07.046Z',to:'2021-09-29T15:52:07.046Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-29T15:46:07.046Z',to:'2021-09-29T15:52:07.046Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

Our downloads are available in tab-separated CSV format. You can access the files by clicking on the green “download” button on the download page.
If you need to know more about this format and how to open it in excel, I suggest to check out the two FAQs:
https://www.gbif.org/faq?question=csv-download
https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
 
We don’t have any MVHF file. I can see that the DOI attached to your download ends with “mvhf”. Perhaps this is what generated the confusion?
