### ISSUE TITLE
Fetching all species (with some conditions) from GBIF API

### ISSUE THREAD

**Issue by margorski** [gbif/portal-feedback#3623]
Hello,
I need a piece of advice before we will start to use your API. I want to understand if our approach is right/best. 

We would like to use the GBIF taxonomic data as a fundament for an application we are developing. Data needs to be prefetched from your database and put in our database filtered out from unnecessary records. We are interested in species data.

1. All species records in the GBIF database are 6 million names, and many of them seem to be names for the same species (synonyms). We would like to add synonyms. However, even for synonyms, there seem to be several results in the GBIF database for the same species. 

For instance, when we did a test to see what we got back when asking for **Betula pubescens cezerepanovii** we got 11 results:

Input:
```
import pygbif
pygbif.name_lookup('Betula pubescens czerepanovii', rank='SUBSPECIES')
```

Output (only keys and **nubKeys** showed):
```
{
  'offset': 0,
  'limit': 11,
  'endOfRecords': True,
  'count': 11,
  'results': [
  {
     'key': 169374088,   
    'nubKey': 5331759,
    [...]
  },
  {
    'key': 127646663,
   'nubKey': 5331759,
   [...]
  },
  {
    'key': 168101913,  
    'nubKey': 5331759,
    [...]
  },
  {
    'key': 160022378,
    'nubKey': 5331759,
    [...]
  },
  {
    'key': 101331989,
    'nubKey': 5331759,
    [...]
  },
  { 
    'key': 170984136,
    'nubKey': 5331759,
    [...]
  },
  {
    'key': 168560978,
    'nubKey': 5331759,
    [...]
  },
  {
    'key': 103843941,
    'nubKey': 5331759,
    [...]
  },
  {
    'key': 5331759,
    'nubKey': 5331759,
    [...]
  },
  {
    'key': 118328110,
    'nubKey': 5331759,
    [...]
  },
  {
    'key': 148947811,
    'nubKey': 5331759,
    [...]
  }],
 'facets': []}
```

Looking at results, only one of them (5331759) seems to be the one GBIF interpret as the right one, while the others point to other checklists like for instance this one: [](https://www.gbif.org/species/169374088
). 
All of the above keys have the same **nubKey** (5331759). I guess we only want the result where the key and the **nubKey** is the same (5331759), and filter out the rest? So we think about taking only the ones where `nubKey == key` to filter out synonym duplicates from other checklists. Does it make sense?

2. What is the best way to fetch all of the species taking into account the above conditions (take synonyms and accepted names without duplicates)? 

Species API works mostly with name matching. One solution I figured out for now is to use
`https://api.gbif.org/v1/species` endpoint with `limit` (we could use 1000 records limit value) and `offset` to iterate and fetch all of data. Filtering on `taxonomicStatus` and `nubKey`, `key` condition would be done in code on our side after fetching data.

Is this the best approach?

3. Are there other considerations we should be aware of when using GBIF taxonomic database as the fundament for our solution? How will for instance COL+ influence the GBIF backbone data?

**Comment by ManonGros** [comment]
Hi @margorski

It seems like the pygbif.name_lookup function uses the Species search API function which queries all checklists available on GBIF. If you would like to query the Backbone only, you either have to specify it in the parameters or use the Species Match function instead (for example: https://api.gbif.org/v1/species/match?verbose=true&name=Betula%20pubescens%20cezerepanovii).
The following blogpost explains the main differences between the Species API functions: https://data-blog.gbif.org/post/gbif-species-api/.

The API will allow you to get only up to 100,000 records. If your goal is to store the backbone somewhere and use it locally, perhaps an easier solution would be to download it directly from the source: https://hosted-datasets.gbif.org/datasets/backbone/backbone-current.zip (or https://hosted-datasets.gbif.org/datasets/backbone/ if you need to check previous versions).

> Are there other considerations we should be aware of when using GBIF taxonomic database as the fundament for our solution? How will for instance COL+ influence the GBIF backbone data?

This last question is probably for @mdoering or @thomasstjerne

**Comment by margorski** [comment]
> The API will allow you to get only up to 100,000 records. If your goal is to store the backbone somewhere and use it locally, perhaps an easier solution would be to download it directly from the source: https://hosted-datasets.gbif.org/datasets/backbone/backbone-current.zip (or https://hosted-datasets.gbif.org/datasets/backbone/ if you need to check previous versions).
> 
Thank you, that is really valuable. I didn't know that it is possible to download whole backbone. This is perfect solution!

**Comment by margorski** [comment]
> The API will allow you to get only up to 100,000 records. 

What does that exactly means? API would block my next requests?

**Comment by mdoering** [comment]
Yes, we block deep paging at some point as it is very ineffective and costly for our infrastructure.
