### ISSUE TITLE
I am responsible for the "National checklist of all species occurring in Denmark". For some taxa on GBIF this checklist is given as the source, ie. Euura flavescens (Stephens, 1835). I would be very happy if I could download a complete list of taxa on GBIF with the checklist as source.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3624]
**I am responsible for the &quot;National checklist of all species occurring in Denmark&quot;. For some taxa on GBIF this checklist is given as the source, ie. Euura flavescens (Stephens, 1835). I would be very happy if I could download a complete list of taxa on GBIF with the checklist as source.**

-----

Github user: @LarsSkipper
User: [See in registry](https://www.gbif.org/api/feedback/user/0cd0d4a0fcee10270ce8d096617ad3b7:09e50889b8f8185024a117a24ffc274c049188d3c83d19d4921c3e7d0234bb0b24cc6f9aa7e6f1faada1fe4e738488ebf898c87f304564a78ad98015e1069774)
System: Firefox 92.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/4b3e4a71-704a-485c-917c-20a89944ea37
Window size: width 1536 - height 751
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-30T11:00:38.229Z',to:'2021-09-30T11:06:38.229Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-30T11:00:38.229Z',to:'2021-09-30T11:06:38.229Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
You can download the backbone here: https://download.catalogueoflife.org/col/latest_dwca.zip
then run the following command line"
`grep 4b3e4a71-704a-485c-917c-20a89944ea37 Taxon.tsv > taxa_with_source_4b3e4a71-704a-485c-917c-20a89944ea37.txt`

This will give you the following file:
[taxa_with_source_4b3e4a71-704a-485c-917c-20a89944ea37.txt](https://github.com/gbif/portal-feedback/files/7264878/taxa_with_source_4b3e4a71-704a-485c-917c-20a89944ea37.txt)
