### ISSUE TITLE
Full taxon name and full authorship as separate coloumns in download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3625]
**Full taxon name and full authorship as separate coloumns in download**

I would like to make a comparison between GBIF and the "National checklist of all species occurring in Denmark" regarding taxon names, author names and classification.

I am very happy with the "species matching" tool on GBIF, but I miss coloumns with the the full taxon name and the full authorship separated, ie. "Anser albifrons subsp. flavirostris" and " Dalgety & P. Scott, 1948". Is there a way I can download a list with these informations ?

-----

Github user: @LarsSkipper
User: [See in registry](https://www.gbif.org/api/feedback/user/7fda5ac78174898714792c9b82a4a6f4:59def7ab2f6ab29fe327ce1ba037f4366b899ebffc8e224d414cf0778f6f0c45151882a4b30d39777333f8ea4bf73ecdc24054c1c263be98f4326cb27e566c72)
System: Firefox 92.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/4b3e4a71-704a-485c-917c-20a89944ea37
Window size: width 1536 - height 751
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-30T11:20:39.543Z',to:'2021-09-30T11:26:39.543Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-30T11:20:39.543Z',to:'2021-09-30T11:26:39.543Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi @LarsSkipper,

You could try using the name-parser tool (https://www.gbif.org/tools/name-parser), to parse the scientific names generated by the species matching tool. This tool can separate canonical names from scientific name authorship.

**Comment by LarsSkipper** [comment]
Thanks for a quick answer.

I have tried using the name-parser tool. It includes the "canonicalNameWithMarker" which is good for the full scientific name. The coloumns "bracketAuthorship" and "authorship" can be concatenated, but the year of authorship is missing out.

**Comment by mdoering** [comment]
The authorship only is unfortunately missing from the species match response, so you gotta lookup the taxon by its key to yield it: https://api.gbif.org/v1/species/6178325 or do a name parsing.

The COL name parser does expose the parsed name slightly differently (using the same underlying parser library) which includes the full authorship: https://api.catalogueoflife.org/parser/name?name=Anser%20albifrons%20flavirostris%20Dalgety%20%26%20P.Scott,%201948
