### ISSUE TITLE
iBOL updates behind

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3627]
**iBOL updates behind**

We discussed this yesterday in the evening that iBOL representation in GBIF is API based and dynamic. A quick check for stats for Arthropoda only https://www.boldsystems.org/index.php/Public_SearchTerms -> Arthropoda shows higher numbers of 7.8M than all public non-BIN records at GBIF https://www.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c with 7.2M. Are we in sync really?

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/f6e15f4afc44c756e848563f3fe9df7c:99bfd21fc0c10aa1fbd29407c139f810e17859006e84f651a6dbd0e89a8e705c6be334ad35d93e5d90708df3add8773665789fb779294e5068f29132c149bcd8)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c
Window size: width 1365 - height 679
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-30T15:01:16.590Z',to:'2021-09-30T15:07:16.590Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-30T15:01:16.590Z',to:'2021-09-30T15:07:16.590Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by dschigel** [comment]
Also I found the reason of my initial confusion about the dynamic links: the dates at the dataset page show registration and latest metadata updates, but of the content is growing through an API, would not we like to show the date of the recent indexing event? I might be looking in the wrong place, too

**Comment by ManonGros** [comment]
[As far as I can see](https://registry.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c/ingestion-history), the last time the number of records ingested increased, was in March 2021.
I think @thomasstjerne might know how often the DwCA is updated for BOLD. But I doubt that the difference between the numbers @dschigel found and the ones we have on GBIF is due to some delay in importing. Perhaps there are some filter used before creating the DwCA?
Thomas, what do you think?

**Comment by thomasstjerne** [comment]
It has been crawled 1-2 times a year since 2018. Right now we have run into issues with API timeouts that needs fixed before we can crawl it again.
Difficult to say if there is more to the difference is only from because of the importing delay.
