### ISSUE TITLE
How to exclude a publisher from the occurrence data?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3628]
**How to exclude a publisher from the occurrence data?**

On teh occurrences dataset, I would like to exclude eBird dta and get everything else. How do I do this?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d808f16d0ea99b119b4698b092b81d52:7194e257c8729e0830c92370c460255682a6427a735a94b3777f90d34a36f70f434831d5819ba1cf7561ecc87f88b013799da169c9d60f3bc7e9fef7ba41010c)
System: Chrome 93.0.4577 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/search?country=IN
Window size: width 1280 - height 696
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-01T10:43:37.823Z',to:'2021-10-01T10:49:37.823Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-01T10:43:37.823Z',to:'2021-10-01T10:49:37.823Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
> Replied by email

Currently, the only way to use exclude records with specific characteristics (based on publisher, datasets, etc.) is to use the [occurrence download API](https://www.gbif.org/developer/occurrence#download).
 
If you are not familiar with using REST APIs, I suggest to take a look at these two blogposts:
* https://data-blog.gbif.org/post/gbif-api-beginners-guide/
* https://data-blog.gbif.org/post/downloading-long-species-lists-on-gbif/ (this one contains examples in Python)
 
Here is also an example of download generated with the API where the user specified they didn’t want any eBird record: https://doi.org/10.15468/dl.earce5 (you can click on the “API” button to see the predicate used in the JSON form
