### ISSUE TITLE
Country names not capitalized in list from country publishing page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#363]
**Country names not capitalized in list from country publishing page**

In the list from 'Data publishing' tab from country pages showing countries for which xx has published data, the country names use upper case only for the first word (e.g. United kingdom, Russian federation - should be United Kingdom, Russian Federation)

This applies to other county lists on country pages (e.g. https://www.gbif.org/country/GB/about) 

Also, I would expect the occurrence numbers here to link to the relevant filtered search result.

-----
fbitem-4eca296f125d3ef262111bb8eb8aaba72cb42169
Reported by: @timhirsch
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/country/GB/about
Window size: width 1442 - height 882
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-19T09:32:04.762Z',mode:absolute,to:'2017-08-19T09:38:04.762Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-19T09:32:04.762Z',mode:absolute,to:'2017-08-19T09:38:04.762Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Those data is taken from an API that doesn't use country codes but names.  Therefore the names are not taken from the translation file. Instead we simply try to make them more readable. I can add capitalization, but for this should really be changed in the API or we should use a different API than the counts API.

https://api.gbif.org/v1/occurrence/counts/publishingCountries?country=GB
```
{
"UNITED_KINGDOM": 60881233,
"UNITED_STATES": 2124250,
"BELGIUM": 248459,
"NETHERLANDS": 77953,
...
}
```

**Comment by MortenHofft** [comment]
I've changed it to not use our counts api. The downside is that the page will be slower.
