### ISSUE TITLE
Page tags displaying with fully qualified names (enums.cms.vocabularyTerms.*)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3632]
**Page tags displaying with fully qualified names (enums.cms.vocabularyTerms.*)**

See e.g. the tag section at the foot of https://www.gbif.org/news/3jpFT9gysj9zwcupx1gOKU/cross-infrastructure-collaboration-with-ena-improves-processing-quality-of-dna-derived-occurrences where "enums.cms.vocabularyTerms.topics.INFRASTRUCTURE" and "enums.cms.vocabularyTerms.topics.DNA" are included in the list

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4e1fa3b43eb33c136767eec5361108c5:261a00467e48af6230b456cc14ae7930b5512f097a516d4ab8b29129dd1c67885d61f42c3cacd189595b2f5c9d56ece872ceadab878cec4ab3b63f1df202f1d6)
System: Firefox 78.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/news/3jpFT9gysj9zwcupx1gOKU/cross-infrastructure-collaboration-with-ena-improves-processing-quality-of-dna-derived-occurrences
Window size: width 1792 - height 915
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-04T13:29:21.062Z',to:'2021-10-04T13:35:21.062Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-04T13:29:21.062Z',to:'2021-10-04T13:35:21.062Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by MortenHofft** [comment]
Thank you - I've added the missing terms so that they can be translated
