### ISSUE TITLE
Broken link under Publish datasets

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3633]
**Broken link under Publish datasets**

The first example link is broken under the "Publish datasets" section.

-----

Github user: @albenson-usgs
User: [See in registry](https://www.gbif.org/api/feedback/user/4ddaf53b0c8ee4a5fb7af117492bbbc8:412872da9c4566cf0c9817c02ce77f9753b08c198bb6beaade292ad97fc0f1b5564060caeb03d5c71a73333de10bed01e1b9609a9fbc21ca60e4600a5e4d53a4)
System: Chrome 93.0.4577 / Windows 10.0.0
Referer: https://www.gbif.org/publishing-data
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-04T15:44:48.331Z',to:'2021-10-04T15:50:48.331Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-04T15:44:48.331Z',to:'2021-10-04T15:50:48.331Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by MattBlissett** [comment]
Thanks, this is now fixed.
