### ISSUE TITLE
Correct name is Samia canningii (Hutton, 1859)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3634]
**Correct name is Samia canningii (Hutton, 1859)**

This taxon has sometimes been treated as a subspecies of Samia cynthia (Drury, 1773), which probably explains the error.

A case was made for conservation of Hutton's name, which was unneeded, but has bibliographic details. See: 
Richard S. Peigler, Reeta Luikham "Case 3638
Saturnia canningi Hutton, 1859 (currently Samia canningi; Insecta, Lepidoptera, saturniidae): proposed conservation," The Bulletin of Zoological Nomenclature, 70(4), 229-233, (1 December 2013)   
https://doi.org/10.21805/bzn.v70i4.a6

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/359d6ed397a4337ade00bf4deb9ba287:11b31b00c65583f2799fedf9a01c908844388ba6873b2359afffeda8a8cec18b2ae962b06b7552023844b4f225bcc43b5174cc6c048e9a37c89ca01056507498)
System: Firefox 92.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/species/5124740
Window size: width 1208 - height 912
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-04T22:52:30.045Z',to:'2021-10-04T22:58:30.045Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-04T22:52:30.045Z',to:'2021-10-04T22:58:30.045Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by WilliamAvery** [comment]
I missed the inconsistency in spelling of the epithet canningi or canningii. I suspect the workers laying a case before ICZN checked things pretty thoroughly.

**Comment by ManonGros** [comment]
In the new backbone taxonomy, Samia canningii Drury, 1773 has been removed and Samia canningi Hutton, 1859 (https://www.gbif.org/species/7429039) has been added. Let me know if the issue should be reopened @WilliamAvery
