### ISSUE TITLE
Page typo

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3635]
**Page typo**

"Ian Ondo of RGB Kew" should be "Ian Ondo of RBG Kew"

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e90ac57496934e80413dae46c2277bda:bd11a66030be139d95fab50d4a79a2cd6c6de6e3916760918a1d50adf3853af0098c933f64e87123ccf847999912e1c4cae35d856f870a94c7204733a378d16d)
System: Firefox 78.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/news/QWLleXqOFkDOGR4Oxaj94/bio-dem-wins-2021-gbif-ebbe-nielsen-challenge
Window size: width 1792 - height 915
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-05T13:01:21.304Z',to:'2021-10-05T13:07:21.304Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-05T13:01:21.304Z',to:'2021-10-05T13:07:21.304Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by MattBlissett** [comment]
Thanks, it's fixed.
