### ISSUE TITLE
About WKT data from a data provider

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3636]
**About WKT data from a data provider**

If a data provider supplies WKT shape data for a given occurrence would GBIF use this information (as in, for the display)? Or would it be only available for download if someone grabs that dataset?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5f0b1ac86a89eaff44521792890c378a:ef7d2486075051eba8a55b1d458caaeeb4742ea06d3de7c67554bf111ff1ff8832037805aaab3682d1cd6f24f1164e2f9f332ed2515717b3764f53c73b0ebb44)
System: Firefox 93.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/data-quality-requirements-occurrences
Window size: width 1411 - height 645
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-06T19:14:43.462Z',to:'2021-10-06T19:20:43.462Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-06T19:14:43.462Z',to:'2021-10-06T19:20:43.462Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by MortenHofft** [comment]
It will show as a dot in search
https://www.gbif.org/occurrence/map?occurrence_id=a01b3f51-4b0b-11e9-b8e8-005056be20a7&advanced=1

it will show as a polygon/line on the individual occurrence page
https://www.gbif.org/occurrence/2575350796

It will be included in DwcA downloads but not in simple downloads.

> also sent per mail
