### ISSUE TITLE
A dataset created for OBIS is registered with GBIF with a wrong DOI. The dataset is: https://www.gbif.org/dataset/d80c46be-b600-44d5-9758-ef5159d40002. In this dataset, I'd like the DOI to be changed to 10.21966/7cmt-ca72 to reflect the DOI in the OBIS dataset.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3638]
**A dataset created for OBIS is registered with GBIF with a wrong DOI. The dataset is: `https://www.gbif.org/dataset/d80c46be-b600-44d5-9758-ef5159d40002.` In this dataset, I&#39;d like the DOI to be changed to 10.21966/7cmt-ca72 to reflect the DOI in the OBIS dataset.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ee5bf0a64c670eb477698a046f573b3c:8935ec02848e9f9608c046a9d6dd90e3a38bcae433c771e1f180e805effbec67818de393356b8a02cf8a9e638aaf0afec754c726f0a0cc1ce4a4de06fb516fc4)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1536 - height 664
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-07T23:17:54.071Z',to:'2021-10-07T23:23:54.071Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-07T23:17:54.071Z',to:'2021-10-07T23:23:54.071Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by timvdstap** [comment]
Sorry - didn't realize it would appear this clunky as a GitHub issue. Please let me know if it's possible to change the DOI or, if this is not possible, how I should best go about this. Thanks!

**Comment by MortenHofft** [comment]
> Sorry - didn't realize it would appear this clunky as a GitHub issue. 

No worries. If you link your Github account to your [GBIF profile](https://www.gbif.org/user/profile) then we will automatically tag you in the issue so you can easier keep track of any development. It isn't a requirement of course.

**Comment by MattBlissett** [comment]
The DOI should be added within the IPT, under Metadata → Citation and Metadata → Alternative Identifiers.

But I think you've already done this, since we see 10.21966/7cmt-ca72 here:
![image](https://user-images.githubusercontent.com/583320/136789100-b3fe9309-351a-4e21-8ff6-bc1c93314a31.png)

**Comment by timvdstap** [comment]
Ah great - thank you Matt! Yeah a colleague told me that that's where the DOI have to go that populate the DOIs under GBIF. Thanks, seems to all be resolved now 👍
