### ISSUE TITLE
continent issue

### ISSUE THREAD

**Issue by bhanberry** [gbif/portal-feedback#3642]
Hello,

Is it possible to automatically fill out the continent field based on the country field? Only about 15% of occurrences in GBIF have the continent field filled out, and so it is misleading/not useful as a filter.

Thanks! Brice

**Comment by MortenHofft** [comment]
Thanks - this have come up several times recently.
Same as https://github.com/gbif/portal-feedback/issues/3580 and https://github.com/gbif/portal-feedback/issues/3620

**Comment by MattBlissett** [comment]
Thanks for reporting this. It's now implemented, for example iNaturalist records in Europe: https://www.gbif.org/occurrence/map?continent=EUROPE&dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7
