### ISSUE TITLE
"subsp. alternifolium" repeated twice in the name Asplenium ×alternifolium subsp. alternifolium subsp. alternifolium Wulfen

### ISSUE THREAD

**Issue by sginzbar** [gbif/portal-feedback#3644]
~Euphrasia minima Jacq. ex DC. is listed both as a synonym and as accepted.~

"subsp. alternifolium" repeated twice in the name Asplenium ×alternifolium subsp. alternifolium subsp. alternifolium Wulfen

**Comment by ahahn-gbif** [comment]
https://www.gbif.org/species/7310827
The reference taxon entry (CoL, verbatim data) does not contain this artifact: https://www.gbif.org/species/171991845/verbatim

**Comment by ahahn-gbif** [comment]
@mdoering: do you have a preferred way for this kind of assumed processing glitch to be flagged up, or is "interpretation" appropriate, please?

**Comment by mdoering** [comment]
@thomasstjerne @MortenHofft this appears to be a portal bug. The API does have the correct name:
https://api.gbif.org/v1/species/7310827
https://api.gbif.org/v1/species/171991845

**Comment by MortenHofft** [comment]
Looks like an issue with this endpoint `https://www.gbif.org/api/species/7310827/name` which tries to format the name with italics.

**Comment by mdoering** [comment]
What is this endpoint? CLB offers it, but the response is altered and very different from the original:

```
curl -s "http://localhost:9009/species/7310827/name"
{"key":19801297,"scientificName":"Asplenium ×alternifolium subsp. alternifolium","type":"SCIENTIFIC","genusOrAbove":"Asplenium","specificEpithet":"alternifolium","infraSpecificEpithet":"alternifolium","notho":"SPECIFIC","authorship":"Wulfen","parsed":true,"parsedPartially":false,"canonicalName":"Asplenium alternifolium alternifolium","canonicalNameWithMarker":"Asplenium ×alternifolium subsp. alternifolium","canonicalNameComplete":"Asplenium ×alternifolium subsp. alternifolium","rankMarker":"subsp."}
```

**Comment by MortenHofft** [comment]
On the website most names are italicised. Since there is no API endpoint to provide formatting for names, then the portal16 attempts to format names. In this case the logic to do so clearly fails. It uses the APIv1 name response to do so.

**Comment by MortenHofft** [comment]
The logic is here https://github.com/gbif/portal16/blob/master/app/controllers/api/species/scientificName.ctrl.js
I'll defer to @thomasstjerne for the implementation details

**Comment by thomasstjerne** [comment]
The portals name presentation got fooled by the name type being `SCIENTIFIC` rather than `HYBRID` here: https://api.gbif.org/v1/species/7310827/name .
It will now always show names containing the "hybrid ×" as hybrids, e.g. `Asplenium ×alternifolium`

**Comment by mdoering** [comment]
The HYBRID name type is only for formulars, not for named hybrids! It is intended to flag that hybrid formulars cannot be parsed, while the named hybrid can and we even have a `notho` field indicating the hybrid markers position.
