### ISSUE TITLE
GRSciColl - display alternative codes and ROR and GRID identifiers

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#3645]
Several institutions are grateful to be able to have several codes associated with one entry. But these alternative codes are only visible in the registry.
Could they be displayed on the GRSciColl pages? (see [this example](https://www.gbif.org/grscicoll/institution/13edc77b-7023-4ddd-89c7-d883a480b294) with several codes)

DISSCO is asking its participants to add ROR identifiers to their GRSciColl entries. It would be good to display them (and also GRID identifiers) on the GRSciColl pages? (see [this example](https://www.gbif.org/grscicoll/institution/2bb5e9c3-5fc3-406a-8421-ebd49f775974) where the identifiers aren't showing)

@MortenHofft would that be possible?

**Comment by MortenHofft** [comment]
**Identifiers**
We have a whitelist of identifiers to show. I have added ROR and GRID

**Alternative codes**
I have added those including the description
