### ISSUE TITLE
Enum values and their keys

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3646]
**Enum values and their keys**

How do I get the Enum values and their keys? For example what is the PhylumKey for Chordate?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/566867c711d70e01dd0880492b4e8dd1:0605a9be8d90a50dbff9215ccd97dc3cd870d03fe82646e2f2993a3efc24449d445a5861d54775d0266acd9922bf43b94f64ff6a78f62421cff51726c5bdb0a6)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/developer/occurrence
Window size: width 2560 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-11T12:46:34.077Z',to:'2021-10-11T12:52:34.077Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-11T12:46:34.077Z',to:'2021-10-11T12:52:34.077Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
> Replied by email

To get the information associated with taxon keys, you should try to use our Species API: https://www.gbif.org/developer/species

For example, you can use the Match API to find the key for Chordata: https://api.gbif.org/v1/species/match?verbose=true&name=Chordata (the key is 44).
We have [a blogpost](https://data-blog.gbif.org/post/gbif-species-api/) explaining the difference between the Species API functions as well as [a post ](https://data-blog.gbif.org/post/gbif-api-beginners-guide/)to help users get started with the API.

For other types of enumeration, you can check our documentation [here](https://www.gbif.org/developer/summary#enumerations).

I hope this helps. Please let us know if you have any question.
