### ISSUE TITLE
Linking GBIF taxonomic backbone entries with type specimens registered in GBIF

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#3647]
One of our users has said it would be helpful for them if species pages (e.g. https://www.gbif.org/species/2247679) had information about type specimens + the dataset/collection they are registered in. 

So for this _Geodia barretti Bowerbank, 1858_ species, there is one type specimen https://www.gbif.org/occurrence/search?taxon_key=2247679&type_status=TYPE, and it would be great if some of the information related to this specimen could show up on https://www.gbif.org/species/2247679, maybe even just highlighted in the "APPEARS IN 24 OCCURRENCE DATASETS" list or something.

**Comment by MortenHofft** [comment]
Type specimens are now shown (if species or below and if the occurrence isn't a higher taxon match)
![Screenshot 2021-10-12 at 11 37 50](https://user-images.githubusercontent.com/6759267/136931843-2c10d8e9-0038-4abb-a3d2-a0354a434dc0.png)

**Comment by rukayaj** [comment]
Wow that was fast! Thanks @MortenHofft
