### ISSUE TITLE
Most (all?) scientificName entries are now incertae sedis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3648]
**Most (all?) scientificName entries are now incertae sedis**

A recent republication event has wiped out scientificName entries, presumably because they've hard-coded a mapping in their IPT.

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/76598696d1bffa41ea1bc80530c30b4c:72faac2f1e7d52cd4bfb211fcc793fdac6b0200bbad91af0a01881842d8ab61bd7ee420bb1e15835e5c35ab4578d0deab9333aa3bceee2e668ceb7d3c5df6a8b9932bb9188b1d84d35226592ae391a9d)
System: Chrome 94.0.4606 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/cd096ec0-a8a0-4c65-92cc-48b00fb934ce
Window size: width 1635 - height 950
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-11T16:50:57.425Z',to:'2021-10-11T16:56:57.425Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-11T16:50:57.425Z',to:'2021-10-11T16:56:57.425Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by dshorthouse** [comment]
Publisher republished their dataset & all fixed now.
