### ISSUE TITLE
Occurrence numbers: mismatch of totals

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3649]
**Occurrence numbers: mismatch of totals**

Detected when updating numbers for a presentation: compare what happens when you click word "occurrences" above the main search vs. when you click the number 1,910,330,874. Compare the numbers you see at the resulting pages.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/92b75e8cf08780ecee33b245870add93:a1ef75d84638b75268ea0ac8b625751e82e166265be171d42604772fdc457aa02a9bf74bc1b9514f3fd3672d36d7b99ce51627e8ed9f976221be6388734c451b)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1280 - height 711
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-11T18:09:52.364Z',to:'2021-10-11T18:15:52.364Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-11T18:09:52.364Z',to:'2021-10-11T18:15:52.364Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by muttcg** [comment]
One of them applies "Occurrence status - present" filter by default

**Comment by MortenHofft** [comment]
I'll make both counts reflect PRESENT only. We want that to be the default for users - at least that was the case last we discussed it
