### ISSUE TITLE
Typo in 'No data publishing activity'

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#365]
**Typo in &#39;No data publishing activity&#39;**

Text showing for countries without data publishers currently reads 'No data publising activity' instead of 'No data publishing activity' 

Also the text underneath should read: No institutions from this country have published data through GBIF

-----
fbitem-496884c0ff18aad1d4aff9b8d651aff122bab281
Reported by: @timhirsch
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/country/CG/publishing
Window size: width 1442 - height 882
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-19T09:47:08.594Z',mode:absolute,to:'2017-08-19T09:53:08.594Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-19T09:47:08.594Z',mode:absolute,to:'2017-08-19T09:53:08.594Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Main point duplicates #351 . Fixed on UAT, will move to prod on Mon.

@MortenHofft , note additional edit:
> text underneath should read: No institutions from this country have published data through GBIF

**Comment by MortenHofft** [comment]
Will be available with the next build
