### ISSUE TITLE
Seal tracking dataset showing implausible locations

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3650]
**Seal tracking dataset showing implausible locations**

Most locations in this dataset are showing seals deep inside the Antarctic land mass. From the pattern of occurrences it seems most likely the latitude values are repeated from a single location, as the longitude range seems plausible for a track along the Antarctic coastline.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/782d7dbe5aa86b31860769229877a0c2:28c579773ee4c945e391f5baa42829c19ad343245e134c9533a35d63d3d036f7b0bc1bde28df3ec59fcdf01d8e057d3957f5650eeb783c13fdb82a544fa36ebb)
System: Chrome 93.0.4577 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/8ea94e2a-118c-4a53-a957-5348d48d61e1
Window size: width 1567 - height 786
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-12T08:24:21.866Z',to:'2021-10-12T08:30:21.866Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-12T08:24:21.866Z',to:'2021-10-12T08:30:21.866Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by jhnwllr** [comment]
Will contact Pangea.

**Comment by jhnwllr** [comment]
data is correct. It appears to be a visualization issue that certain zoom levels that creates a straight line. 
<img width="420" alt="Screenshot 2021-12-07 at 11 35 25" src="https://user-images.githubusercontent.com/4245213/145015058-c4d5f360-4b23-4480-8ecc-1f6563d5fb5d.png">
<img width="817" alt="Screenshot 2021-12-07 at 11 34 14" src="https://user-images.githubusercontent.com/4245213/145015076-1b1da061-cc7e-462c-9cb2-2132ac83fe2e.png">
