### ISSUE TITLE
This cannot be the Holotype of Cortinarius largus Fr.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3652]
**This cannot be the Holotype of Cortinarius largus Fr.**

The collection year of this record is 1977.
Cortinarius largus was described in:
Fr. In: Epicr. syst. mycol. (Upsaliae): 259 ('1836-1838'). (1838).

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2a3730f8357f3b0f31a1cfdd7536a7b9:8c40016bf85e737b58ec2a41720a68a9c09725185ea9d3fc457da32821a0374e7dc266d07d3d192cfce7ee43acaafc1310b2fb60a7fe9a608d85301058a09c5e)
System: Chrome 94.0.4606 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/3053144589
Window size: width 1429 - height 736
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-12T12:46:18.319Z',to:'2021-10-12T12:52:18.319Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-12T12:46:18.319Z',to:'2021-10-12T12:52:18.319Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING
datasetKey: 828a3d8c-f762-11e1-a439-00145eb45e9a
publishingOrgKey: c76cf030-2a95-11da-9cc1-b8a03c50a862
Network keys: 17abcf75-2f1e-46dd-bf75-a5b21dd02655 
Node handles: @jholetschek

**Comment by jhnwllr** [comment]
contacted the publisher Herbarium Senckenbergianum (FR) - Fungi

**Comment by aallspac** [comment]
Dear John,

thank you for informing us. True, a mistake from our side, it is the holotype of _Cortinarius coalescens_, and not the one of  _Cortinarius largus._

[https://search.senckenberg.de/aquila-public-search/search?searchTerm=aquila_id:sesam-1214723](url)

We have corrected and updated the record, after reingestion it should also be visible correctly on GBIF.

Best regards

Andreas

**Comment by aallspac** [comment]
was updated yesterday, many thanks...

**Comment by jhnwllr** [comment]
Great thank you. I will close the issue when the changes are visible on GBIF.org.
