### ISSUE TITLE
How do you protect data on rare species?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3656]
**How do you protect data on rare species?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/32e17213eb9c1377dba24074e667e561:a4afd773f0937207e704c05977746cc702f4a6b25ed3907790612b46985969ed21d55d40551279298b1b483129ab054f79ee86e547cad1fb5591fbaac9ca23e65f7f16fc274b37d23b3a82fd2679ac91)
System: Firefox 93.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/5b31a95f-5326-45b2-a52c-52cf3d724719
Window size: width 1920 - height 955
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-13T19:37:50.668Z',to:'2021-10-13T19:43:50.668Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-13T19:37:50.668Z',to:'2021-10-13T19:43:50.668Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
> Replied by email

Publishing organizations (Museums, herbaria, citizen science initiatives, etc.) are responsible for the content they share on GBIF.

We made available some guidelines on how to handle information concerning sensitive species: https://doi.org/10.15468/doc-5jp4-5g10. We strongly encourage all our data providers to check those guidelines before sharing their data on GBIF.

The data you can access on GBIF is shown as provided by the publishing organization. We don’t obscure coordinates for sensitive species.
