### ISSUE TITLE
Corrupt CSV-file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3662]
**Corrupt CSV-file**

I've produced a download via the api. The download list says that 896 occurrences are found. The CSV-file contains only 887 occurrences. The last record ends after the month of the event date. I can delete the download but it is not possible to produce a new one with the same filter. Can you please delete the corrupt download so that I can try a new one? The DOI is 10.15468/dl.fdczuu, the link to the ZIP-archive is https://api.gbif.org/v1/occurrence/download/request/0027494-210914110416597.zip.
Thank you.
Best,
Michael

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/84b2e52558a6dbb9c6c8284f5923eb45:1a0f93d4a2c1a4f7ca7bf4dbee084183f6cf2c898e7d24ee9bcb283f35213d0b58d6f579e641541a38544e3de25a79872780f18bab1bfdc75b91c015c26759fa)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/user/download
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-15T07:47:11.793Z',to:'2021-10-15T07:53:11.793Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-15T07:47:11.793Z',to:'2021-10-15T07:53:11.793Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by fmendezh** [comment]
I reproduced this download and counts now match, there's no indication of errors or outages at the time the reported download was done
https://www.gbif.org/occurrence/download/0081363-210914110416597
