### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3664]
**Broken image links**

All images in this dataset seem to be invalid/non existing identifiers
https://www.gbif.org/occurrence/gallery?dataset_key=821cc27a-e3bb-4bc5-ac34-89ada245069d

Originally posted in https://github.com/gbif/portal-feedback/issues/3663

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/55bfb052adf8d0f765a0001181807a7e:7d0c8857de023b0b7cbcb8b155330b56230ef8e8964ea680c14dfe42b8d872b94f8fab3b5cf23314005880bcb18914167c26a066d2b7da681c7d5ed2595cc86b)
System: Chrome 94.0.4606 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/3311063329
Window size: width 1440 - height 762
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-15T09:25:02.066Z',to:'2021-10-15T09:31:02.066Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-15T09:25:02.066Z',to:'2021-10-15T09:31:02.066Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING
datasetKey: 821cc27a-e3bb-4bc5-ac34-89ada245069d
publishingOrgKey: bc092ff0-02e4-11dc-991f-b8a03c50a862
Network keys: 99d66b6c-9087-452f-a9d4-f15f2c2d0e7e 
Node handles: @albenson-usgs

**Comment by AbbyBenson** [comment]
I will reach out to the Smithsonian.

**Comment by AbbyBenson** [comment]
Smithsonian IT is working to fix this. "It is a case of putting in a URL prefix twice.  Should be correct via next IPT creation."

@gamblebnmnh will you update here when it's corrected so we can close the ticket?

**Comment by gamblebnmnh** [comment]
I have create new datasets with this URL error fixed.  I don't know how long it takes before our IPT is ingested into GBIF but it should be corrected when the Nov 5, 2021 published version is available.

**Comment by ManonGros** [comment]
Thank you @gamblebnmnh !
