### ISSUE TITLE
Incomplete CSV-file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3666]
**Incomplete CSV-file**

The csv- file in the download DOI 10.15468/dl.m6rra5 is not complete. The last record (gbifID 920170520) ends with the decimalLatitude. Can you please delete the ZIP-archive https://api.gbif.org/v1/occurrence/download/request/0027864-210914110416597.zip since it is not possible for me?

The ZIP-archive I asked you to delete before ( https://api.gbif.org/v1/occurrence/download/request/0027494-210914110416597.zip) seems to be gone. I could do a new download with the same parameters and this one is complete.

Thank you.

Best,
Michael

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f1a8b639d30671ffad9689e71699eb6f:bba8f146ab5d372ce0ffd2b1fac6b539b20338bd8ed746c99bbd146ddabd780e03e3d6f16d9d15aa543973f9e8a2dee981040bfaa6eea3cf6f35608e11250dcb)
System: Chrome 90.0.4430 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0027864-210914110416597
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-15T12:26:04.701Z',to:'2021-10-15T12:32:04.701Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-15T12:26:04.701Z',to:'2021-10-15T12:32:04.701Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
Related to https://github.com/gbif/portal-feedback/issues/3662

**Comment by fmendezh** [comment]
I reproduced this download and it seems that produced file are correct now, did not find anything in the logs indicating there was an error or outage in the backend services
https://www.gbif.org/occurrence/download/0081344-210914110416597

**Comment by ManonGros** [comment]
Thanks @fmendezh I notified the user by email so we can close the issues.
