### ISSUE TITLE
Both Euphorbia platyphyllos L. and E. platyphylla L. are accepted

### ISSUE THREAD

**Issue by sginzbar** [gbif/portal-feedback#3667]
Linnaeus published the name as E. platyphyllos. Should it be corrected to platyphylla?

**Comment by jhnwllr** [comment]
Euphorbia platyphylla L.
https://www.gbif.org/species/4271590

Euphorbia platyphyllos L. -> Euphorbia platyphylla L. 
https://www.gbif.org/species/3068153

**Comment by ahahn-gbif** [comment]
needs verification of the original description, but if L. published the name as _Euphorbia platyphyllos_ L., then that should remain the accepted name, and _E. platyphylla_ not marked as accepted.

**Comment by ahahn-gbif** [comment]
CoL only lists _Euphorbia platyphyllos_: https://www.catalogueoflife.org/data/taxon/6GZX6
The variant _E. platyphylla_ seems to go back to Tropicos (https://tropicos.org/name/Search?name=Euphorbia%20platyphylla) or a source thereof, with both variants listed here side by side and both referencing Sp. Pl. 1: 460–461. 1753. as the source.

At first estimate, this would be best resolved during backbone generation by marking one (E. platyphylla) as spelling variant of the other. @mdoering what would be the best mechanism to include this information into the workflow?

**Comment by mdoering** [comment]
That's gotta be an entry in our patch list. With the disadvantage that we have to declare an accepted name which will remain accepted even if other authoritative sources claim it is not anymore and thus needs a review from time to time.
