### ISSUE TITLE
Need to show authorities for GBIF taxon concepts

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#367]
**Need to show authorities for GBIF taxon concepts**

We list the classification and synonyms but don't state which datasets underpin this.

-----
fbitem-species5749074
Reported by: dhobern@gbif.org
System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://www.gbif.org/species/5749074
Window size: width 1897 - height 924
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T05:56:29.049Z',mode:absolute,to:'2017-08-21T06:02:29.049Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T05:56:29.049Z',mode:absolute,to:'2017-08-21T06:02:29.049Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
We currently provide a link to a "Reference Taxon" as the primary source for the backbone entry. I would agree it would be better to show the actual dataset name of that reference taxon in addition to the link. @MortenHofft what do you think about that? Something like "based on Catalogue of Life" underneath the name in this case?

**Comment by thomasstjerne** [comment]
I like the idea of stating more explicitly which dataset a backbone taxon is based on. But we have quite a bit of information under the taxon names already in some cases e.g.: https://www.gbif.org/species/5231190
Maybe we have to move some other information to avoid the header being messy?

**Comment by mdoering** [comment]
maybe we display the source dataset elsewhere then? It is tied a lot to the "origin" property we show below the header so we could use that, especially since these are mutually exclusive: https://www.gbif.org/species/1004924

**Comment by MortenHofft** [comment]
What do you mean mutually exclusive?
https://www.gbif.org/species/212 has both `source taxon` and a `published in`
I like the idea, it makes sense. But I agree with Thomas that it can get a bit cluttered so some changes in the layout might be necessary.

**Comment by mdoering** [comment]
I dont mean publishedIn, but origin.
We currently only show the origin if it is not equal SOURCE, e.g. here as "This record has been created during indexing and did not explicitly exist in the source data as such.
Origin: Generated, missing genus or species for 'orphaned' lower name."

https://www.gbif.org/species/1004924

A reference taxon link and a constituent_key can only exist if origin is equal to SOURCE, so we could show the source dataset in the same style (even though it feels more of a warning).

**Comment by mdoering** [comment]
Btw, this does not make much sense for backbone pages as these are not indexed:
"This record has been created during indexing and did not explicitly exist in the source data as such"

Maybe just show it for non backbone pages?

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/528
