### ISSUE TITLE
question difference between expected number of occurrence and rows read in file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3670]
**Hi! I am Marc Riera, a PhD researcher, interested in using distriution data from GBIF for an analysis of climatic niche shifts. I have generated a dataset of over 5 million occurrences (through rgbif::occ_download). The resulting DOI is (`https://doi.org/10.15468/dl.ezawr4).` But, when I download and unzip the Darwin Core Archive, the occurrence.txt file contains only 274731 rows (either loading it in R through fread::data.table(), or through finch::dwca_read()). If I just open the .txt in notepad and check the number of rows I get the same number (in the notepad it&#39;s actually 274733 rows). Any guidance on why I am missing so much information in this download? Thank you!**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e47e4fd6d42d98007a23d4347f860ef0:6afc85bfa46cd18a5e097c17fee3ce67dfd574707505fbdc6559797f3d9b918c2fa933c427286bdaa7506a3b7cf3ac3983c3e3882559c3bda00296fc95133802)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0028403-210914110416597
Window size: width 1280 - height 577
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-18T13:50:35.476Z',to:'2021-10-18T13:56:35.476Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-18T13:50:35.476Z',to:'2021-10-18T13:56:35.476Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by MarcRieraDominguez** [comment]
Hi! Many thanks for your reply! I don't know how to also select NULL with the predicate syntaxis of the rgbif package, I'm still new to it.
How could I modify the following code to avoid this issue?
pred_not(pred("establishmentMeans", "MANAGED"))
Thank you!

**Comment by ManonGros** [comment]
Hi @MarcRieraDominguez, 
Until we fix this issue on our side, the way to go is to also select for records with the NULL values. So instead of the line `pred_not(pred("establishmentMeans", "MANAGED"))`, use:
```
pred_or(
pred_not(pred("establishmentMeans","MANAGED")),
pred_not(pred_notnull("establishmentMeans"))
)
```
(either the establishment is not managed or it is null)

**Comment by ManonGros** [comment]
Note that you can also format your query in JSON instead of using the `pred()` functions. This would allow you to use the `isNull` predicated (instead of `pred_not(pred_notnull())`) (see examples in [our documentation](https://www.gbif.org/developer/occurrence)).

You might also find the following two blogposts useful for your work:
https://data-blog.gbif.org/post/gbif-api-beginners-guide/
https://data-blog.gbif.org/post/gbif-filtering-guide/

**Comment by MarcRieraDominguez** [comment]
Great! Thank you for your help!
