### ISSUE TITLE
"Tipula matsumuriana ssp. pseudohortensis" should be moved to a synonym of Tipula pseudohortensis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3672]
**&quot;Tipula matsumuriana ssp. pseudohortensis&quot; should be moved to a synonym of Tipula pseudohortensis**

Hi.

Tipula pseudohortensis Lackschewitz, 1932 was recently reinstated as a full species. GBIF has a new species-level record for it (backbone https://www.gbif.org/species/11119797). 

However, the old subspecies-level name still lingers under Tipula matsumuriana as "Tipula matsumuriana subsp. pseudohortensis Lackschewitz, 1932" (https://www.gbif.org/species/6258563).

Proposed fix: move Tipula matsumuriana subsp. pseudohortensis to a synonym of Tipula pseudohortensis. 

Best wishes,
Jere Kahanpää

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/48c0162f64edb290889d10d99c24c9ca:da2138b30b880bdf97e01decb2ce9db6de41d29f3f2ad7b8a2523a0b44dfc71ba718989b12290b33bf389497277e5ad820952fdeb84fb9a6c2acbef3be7d5580)
System: Firefox 78.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/6258563
Window size: width 1283 - height 1107
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-18T14:13:51.173Z',to:'2021-10-18T14:19:51.173Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-18T14:13:51.173Z',to:'2021-10-18T14:19:51.173Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by jhnwllr** [comment]
emailed publisher of https://www.gbif.org/dataset/a6c6cead-b5ce-4a4e-8cf5-1542ba708dec

**Comment by jhnwllr** [comment]
**Tipula matsumuriana subsp. pseudohortensis Lackschewitz, 1932**
https://www.gbif.org/species/6258563

is now syn of 

**Tipula pseudohortensis Lackschewitz, 1932**
https://www.gbif.org/species/11119797
