### ISSUE TITLE
Coördinate mismatch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#368]
**Coördinate mismatch**

Occurrences pertain to Belgium - Coordinate is in Belgium -- GBIF gives Country Coordinate mismatch

-----
fbitem-632937989213bf4e43cb42556216fa1047383e29
Reported by: @DimEvil
System: Chrome 60.0.3112 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/map?dataset_key=bcbfd319-8813-4b6d-b529-07dc5a6ccf56&issue=COUNTRY_COORDINATE_MISMATCH
Window size: width 1920 - height 911
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T07:52:00.836Z',mode:absolute,to:'2017-08-21T07:58:00.836Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T07:52:00.836Z',mode:absolute,to:'2017-08-21T07:58:00.836Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
I've made the country matching less strict. As this example showed, the data source we use (Natural Earth 10m cultural vectors) isn't sufficiently accurate.

@DimEvil — I've re-crawled your dataset, and there are now zero coordinate issues.
