### ISSUE TITLE
The location is wrong....belongs to Chaco, in Argentina and the point is almost in Antarctica.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3688]
**The location is wrong....belongs to Chaco, in Argentina and the point is almost in Antarctica.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5939ffc154fa7da62f47c3e04cf11b6a:7d6b3ed943397a2f388c41bd6c9ed9ac9e06dcd91f3440451267b88ceb427a24db409d2d61b9e0c4824368ec03125553f752033859c0d9135b4009e52c2d685c)
System: Firefox 93.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/occurrence/1317881560
Window size: width 1525 - height 698
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-21T11:05:26.587Z',to:'2021-10-21T11:11:26.587Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-21T11:05:26.587Z',to:'2021-10-21T11:11:26.587Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING
datasetKey: 821cc27a-e3bb-4bc5-ac34-89ada245069d
publishingOrgKey: bc092ff0-02e4-11dc-991f-b8a03c50a862
Network keys: 99d66b6c-9087-452f-a9d4-f15f2c2d0e7e 
Node handles: @albenson-usgs

**Comment by gamblebnmnh** [comment]
For some reason the interpreted lat long for this record has reversed the lat long values from the original data.  I think this issue is to be corrected on GBIF side not NMNH side.

**Comment by ManonGros** [comment]
Hi @gamblebnmnh
The original coordinates point to a location in Paraguay which doesn't match the country provided (Argentina), this is why the system attempts to swap them.
Would it be possible to update the coordinates at the MNHN to point to Chaco?

**Comment by gamblebnmnh** [comment]
Botany Department confirmed location is actually Paraguay so lat long were correct, country was wrong.  will be updated sometime this Friday Nov. 5, 2021.
