### ISSUE TITLE
I am trying to pull updated locations for Glaucidium brasilianum cactorum after pulling locations last year. However, I am getting far fewer locations than previously and I am not clear why. In my existing dataset, I have >2000 records. Now with my query I am only getting 368 results.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3689]
**I am trying to pull updated locations for Glaucidium brasilianum cactorum after pulling locations last year. However, I am getting far fewer locations than previously and I am not clear why. In my existing dataset, I have &gt;2000 records. Now with my query I am only getting 368 results.**

-----

Github user: @rachwilliams56
User: [See in registry](https://www.gbif.org/api/feedback/user/42bf07c34d3e9fd9defed93211aeef08:42f3dbbbc00dfaafa2bc8d9ca64b3f22a269b42e92736b137c703233a8b823ebdbe41dc78f7797170a1d8992ee88cfba525926f6c787f75d2039e1f06e0058eb)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download?taxon_key=5232122&advanced=1
Window size: width 1918 - height 1390
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-21T23:36:40.323Z',to:'2021-10-21T23:42:40.323Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-21T23:36:40.323Z',to:'2021-10-21T23:42:40.323Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
@rachwilliams56 is the dataset you got last year available somewhere to check?

I tried checking the data from last year's snapshot and I couldn't find more than 366 records. Perhaps I missed something, it would be helpful the data you have from last year.

**Comment by rachel-laura** [comment]
[GBIF_Gbrasilianum_19Aug20_0042067-200613084148143.zip](https://github.com/gbif/portal-feedback/files/7400200/GBIF_Gbrasilianum_19Aug20_0042067-200613084148143.zip)

Here is the zip file from last year's data. Does the default dataset on GBIF include all the eBird and iNaturalist observations?

**Comment by MortenHofft** [comment]
https://www.gbif.org/occurrence/download/0042067-200613084148143

The download includes 75,614 occurrences (but that includes other taxa)

`grep -o -i 5232122 occurrence.txt | wc -l` returns 423 matches for that taxonKey.
And that includes rows where it appears as both `taxonKey` and `acceptedTaxonKey` (columns located next to each other). 

`grep -o -i "5232122\t5232122" occurrence.txt | wc -l` 210 matches. 

Looks to me like there are 213 occurrences in that file with the taxonKey 5232122  (Glaucidium brasilianum cactorum van Rossem, 1937)?

**Comment by rachel-laura** [comment]
Thanks for looking into that! I guess last year we just searched on the species and not subspecies. Thanks for the help!
