### ISSUE TITLE
Location issue

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#369]
**Location issue**

https://www.gbif.org/occurrence/search?dataset_key=bcbfd319-8813-4b6d-b529-07dc5a6ccf56

I have 4362 occurrences (no preference on location)
Including coordinates it gives me 3865
without coordinates: 0 results

it should be 4362 and all occurrences do have coordinates. That the occurrences with country mismatch (faulty mismatch) are not included here is not  clear for the user

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
Reported by: @DimEvil
System: Chrome 60.0.3112 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/search?dataset_key=bcbfd319-8813-4b6d-b529-07dc5a6ccf56&has_coordinate=false
Window size: width 1920 - height 911
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T08:30:10.148Z',mode:absolute,to:'2017-08-21T08:36:10.148Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T08:30:10.148Z',mode:absolute,to:'2017-08-21T08:36:10.148Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you for your feedback
The checkbox marked in red below was intended to draw attention to the fact that not all coordinates are without issues. But highlighting it even more might be useful as you point out. thanks

![screen shot 2017-08-21 at 11 34 50](https://user-images.githubusercontent.com/6759267/29513206-e03d4db6-8664-11e7-935c-6b045c2335ba.png)

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/527
