### ISSUE TITLE
Hello, in the occurrences dataset, I choose the fields I want to use. I assume that's actualized by simply not filling them out in the excel spreadsheet. Can the fields I choose be optional. Stupid question, but just to be sure.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3690]
**Hello, in the occurrences dataset, I choose the fields I want to use. I assume that&#39;s actualized by simply not filling them out in the excel spreadsheet. Can the fields I choose be optional. Stupid question, but just to be sure.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d380af7ee47f470ce5b6342ddb3396e6:42ebef90f8bfc8514af98d36d1d2f1e7d774d40dac4c92f84336bb22dd0fc73b441999f98a57c17782c13b1e4f186f8a8c790a59e592f8a9c379a05dd833ad87)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/data-quality-requirements-checklists
Window size: width 1024 - height 480
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-22T01:02:25.677Z',to:'2021-10-22T01:08:25.677Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-22T01:02:25.677Z',to:'2021-10-22T01:08:25.677Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
> replied by email (I assume that the question is about publishing data on GBIF)

You can choose which fields you would like to share on GBIF by omitting the columns you don’t wish to share, or by not mapping those columns to Darwin Core terms, or by leaving the fields empty.
Keep in mind that some fields are necessary for indexing. I suggest to check [our data validator](https://www.gbif.org/tools/data-validator) and [our data-quality requirement page](https://www.gbif.org/data-quality-requirements) to check that you can and cannot remove.
