### ISSUE TITLE
The photos that are linked to supposedly ollistrate Galactia argentea Brandegee are all of an orchid, probably a species of Platanthera. It is recommendable to remome the links.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3692]
**The photos that are linked to supposedly ollistrate Galactia argentea Brandegee are all of an orchid, probably a species of Platanthera. It is recommendable to remome the links.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/670bb86de0977bda60085fc43c17d7bc:252c1bc124d86f784804fcd19f5629f9d02b6436f2b65de5d79f4dc166b21b60d84d64c6ad48170510680efa53acc9d2fc2232a080c07869b503f1a7f0f31282)
System: Firefox 93.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2643585666
Window size: width 2560 - height 1315
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-24T14:42:18.436Z',to:'2021-10-24T14:48:18.436Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-24T14:42:18.436Z',to:'2021-10-24T14:48:18.436Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by ManonGros** [comment]
Feedback forwarded to Pl@ntNET via they feedback system: https://identify.plantnet.org/central-america/observations/1003810726

**Comment by CecSve** [comment]
Pl@ntnet have now removed the observation and the changes also appear on GBIF.org.
