### ISSUE TITLE
The Excel templates without the Example Data appear to have less properties.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3694]
**The Excel templates without the Example Data appear to have less properties.**

Hello, I'm not understanding the templates. The Excel templates without the Example Data appear to have less properties.  For instance the Checklist template (without example data) has 6 properties. taxonID	parentNameUsageID	acceptedNameUsageID	scientificName	kingdom	taxonRank. But the Template with Examples has about 20. Occurrences template with no example data only has 13 properties. Aren't the templates without example data supposed to have the same number of properties as the templates with data?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c743d68946d14be6067185e2b952e19c:5e53813227e8f8c997e1bbc132809e7f06967b75db09d0fbf0c9467013028678a9567e4c8de2ecde3b77d6d8677b1f2380fda6b557c7ab82f1e80881a24d5ba0)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1024 - height 525
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-25T14:44:53.555Z',to:'2021-10-25T14:50:53.555Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-25T14:44:53.555Z',to:'2021-10-25T14:50:53.555Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

The templates available include only the required and recommended Darwin Core fields. There are many Darwin Core terms and we don’t want to overwhelm new users by putting all of them in the template. The examples are not as tidy as they are based on real life data.
