### ISSUE TITLE
OBIS extentions under development?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3695]
**OBIS extentions under development?**

Why are the OBIS extensions "Under Development"? They also have broken links attached. Actually where are the OBIS terms on the internet. I can't  seem to find them.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b2cc357a7b1ce2295f3b21e83142e5cd:40129b4740dd6bbb462311eff49e045642f70ac98909966de52a9454b9ec04840c4480d5b2551142e3ae01fba63b18f2ff28e9dd4686f2e41a109f4ae7109bcc)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1024 - height 525
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-25T14:47:44.814Z',to:'2021-10-25T14:53:44.814Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-25T14:47:44.814Z',to:'2021-10-25T14:53:44.814Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email
As far as I understand, OBIS decided to use the Extended Measurement Or Facts extension so the other ones were retired from the Sandbox (see [this comment](https://github.com/gbif/rs.gbif.org/issues/74)).
