### ISSUE TITLE
Taxon needed in occurrences?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3696]
**Taxon needed in occurrences?**

If I have the taxon info in the checklist, why do I need them in occurrences. Can I eliminate them from the occurrences excel spreadsheet without issues in GBIF?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/89671c9ad28cf7927b1fa7ff7b62d116:00a8b9711eb888f92610eac0c2716db2ef69f276121d69148ed3ab5d9681637542f78d24806a776e6ae51998fc7f99c15017144bb564df5e063f4af040dcdb1d)
System: Chrome 94.0.4606 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1024 - height 480
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-25T18:06:36.628Z',to:'2021-10-25T18:12:36.628Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-25T18:06:36.628Z',to:'2021-10-25T18:12:36.628Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

Our system isn’t able to infer occurrence scientific names from a checklist.
Perhaps this could change in the future, but for now you will have to add the scientific names in the occurrence files.
