### ISSUE TITLE
maximising map gives blank screen

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#370]
**maximising map gives blank screen**

-----
fbitem-dataset8c3e2fd5-2c7a-4126-a5c0-b6f67c9911db

System: Chrome 60.0.3112 / Windows 7 0.0.0
Referer: https://www.gbif.org/dataset/8c3e2fd5-2c7a-4126-a5c0-b6f67c9911db
Window size: width 2048 - height 1024
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T11:27:55.368Z',mode:absolute,to:'2017-08-21T11:33:55.368Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T11:27:55.368Z',mode:absolute,to:'2017-08-21T11:33:55.368Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I changed the map styling and broke the fullscreen - sorry about that. It is fixed again. I'm deploying a new version now. https://github.com/gbif/portal16/commit/b6cbbc18af5b59a05a3315bad06b7eb7c3ebf6d4

**Comment by MortenHofft** [comment]
fixed and in production. Thank you for reporting
