### ISSUE TITLE
Downloading GBIF occurrence data in CSV file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3700]
**Downloading GBIF occurrence data in CSV file**

Good day. I can't see (on your website) how to download occurrence data (especially including lat and long) in a CSV file for species or subspecies I specify. How do I do this?

Many thanks
Kevin Murray

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/23097e1af2adb130e041473bbf49cef0:504adf81cafad99aefa283af69b9d4a2ea211cd51bd4f89fc787febb57062d4f0dba8912ae0e82038bb686c1a2c074ffba1af70dfe503faf1962e89120f66dba)
System: Chrome 95.0.4638 / Windows 10.0.0
Referer: https://www.gbif.org/faq?question=csv-download
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-27T12:20:54.524Z',to:'2021-10-27T12:26:54.524Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-27T12:20:54.524Z',to:'2021-10-27T12:26:54.524Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
