### ISSUE TITLE
Buenos días en la carrera 33 a  11 -08 del barrio la Independencia en estos días de lluvia  el agua de la quebrada  se lleva  la basura produciendo  contaminación  en el ambiente  por eso solicito cambio de sitio para la recolección  de basuras donde no afecta la quebrada. Recuerdan que días atrás aparecieron peces muertos en el barrio siete de agosto.  Mi teléfono  3157897132 y si porfavor nos colaboran con un letrero de no botar basura aqu

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3702]
**Buenos días en la carrera 33 a 11 -08 del barrio la Independencia en estos días de lluvia el agua de la quebrada se lleva la basura produciendo contaminación en el ambiente por eso solicito cambio de sitio para la recolección de basuras donde no afecta la quebrada. Recuerdan que días atrás aparecieron peces muertos en el barrio siete de agosto. Mi teléfono 3157897132 y si porfavor nos colaboran con un letrero de no botar basura aqu**

Tengo fotos pero aquí no me deja subirlas

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7785a98891e22a824a2d394e94cb9ce5:0ae084a5edf22c537677212365928678a05c7fedf75c4e573d698ce91547ec01e9cf055fa1aff89d7013521101a6e88fddfb7906c4ef4f260f207ff6e3753a9e)
System: Chrome Mobile 94.0.4606 / Android 0.0.0
Referer: https://www.gbif.org/es/user/download
Window size: width 412 - height 718
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-27T13:14:52.528Z',to:'2021-10-27T13:20:52.528Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-27T13:14:52.528Z',to:'2021-10-27T13:20:52.528Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Google translate
> Good morning in Carrera 33-11-08 of the Independencia neighborhood, on these rainy days, the water from the stream carries away the garbage, producing pollution in the environment, so I request a change of site for garbage collection where it does not affect the stream. They remember that days ago dead fish appeared in the neighborhood of 7 de Agosto. My phone number 3157897132 and if you please help us with a sign not to litter here

> I have photos but he won't let me upload them here
