### ISSUE TITLE
HP download request - filterApplied data undefined

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3704]
**HP download request - filterApplied data undefined**

The date value used in downloadKey.filterApplied is not defined for DL requests from hosted portals...?

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/2a55fcaa867f2bc08e4f9489bde9de7a:c978622480f64ceb655b57995e7dba5d37e5a1dcc0975b8b40fb26a94d8ad22a7ead7cb2921eb909be6175dc4ceab47baa344737511bb20b3ab30d77b91b99ce)
System: Chrome 94.0.4606 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/request?date=123&predicate=%7B%22type%22:%22equals%22,%22key%22:%22TAXON_KEY%22,%22value%22:5386%7D
Window size: width 1440 - height 622
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-27T18:17:05.513Z',to:'2021-10-27T18:23:05.513Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-27T18:17:05.513Z',to:'2021-10-27T18:23:05.513Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thanks @dnoesgaard - I've fixed the translation to match the one we use on the occurrence metrics page
