### ISSUE TITLE
Help with CSV

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3706]
**Help with CSV**

Hello,
 
Thank you for providing this publicly-available dataset. I tried downloading the 'simple' version of the North American Bombus dataset (with ~10,000 observations), but am confused about its organization. 

It seems that information that should be separated into different columns is being compressed into single cells: (e.g., 1252614697	c4a2c617-91a7-4d4f-90dd-a78b899f8545	urn:catalog:USDA-ARS:BBSL:BBSL798558	Animalia	Arthropoda	Insecta	Hymenoptera					ORDER	Hymenoptera	Bee	author date not provided	US	Lowell Point State Park). 

I am most interested in the count data and geographical coordinate data. Not sure if there's an easy way to obtain this from the format presented in the excel file, but any insights into how to work with your datasets would be greatly appreciated. 

I will also note that I tried using the more complex version but have no idea how to work with the attached .txt and .xml files. 

Thank you for your time! 

Link to location where I downloaded from: https://www.gbif.org/occurrence/download?dataset_key=c4a2c617-91a7-4d4f-90dd-a78b899f8545

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0edb384d72a2c70f01e24ecf0005085b:7ce2e2c93a17b1d3cb0cd3a07fbe6451c130d75d74a852c2a9cd20881e1e7b108cb6ed35741f9c230a2ce7773921e7dcd7ac6b919b58458bb1fb9cd117d6bd31)
System: Safari 15.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/data-processing
Window size: width 1792 - height 916
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-28T17:25:31.253Z',to:'2021-10-28T17:31:31.253Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-28T17:25:31.253Z',to:'2021-10-28T17:31:31.253Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by maxhermanson** [comment]
NEVER MIND, SORRY!!! Used this link: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
