### ISSUE TITLE
would be great if i could sort according to columns by choice

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#371]
**would be great if i could sort according to columns by choice**

-----
fbitem-f55b22d402f0bf9841531850ab0f3ed8d9273208

System: Chrome 60.0.3112 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/species?dataset_key=a968d7e9-5391-482d-8927-4b34b9863d56&dataset_key=8c3e2fd5-2c7a-4126-a5c0-b6f67c9911db
Window size: width 2048 - height 1024
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T12:10:08.365Z',mode:absolute,to:'2017-08-21T12:16:08.365Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T12:10:08.365Z',mode:absolute,to:'2017-08-21T12:16:08.365Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you for reporting this. I can see why that would be useful.
For the ad hoc view, it isn't really feasable at this point I'm afraid. To do so we we need a new API for these adhoc facets (species tab and dataset tab). And the API should enable sort in general (which it doesn't at this point). Notice that this is closely related to https://github.com/gbif/portal-feedback/issues/224
