### ISSUE TITLE
Update links to Excel templates

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3712]
**Update links to Excel templates**

Right now the links on this page for the Excel templates point to the IPT manual in GitHub (for example: https://github.com/gbif/ipt/wiki/checklistData#templates) but perhaps it would be better to link to this pretty manual: https://ipt.gbif.org/manual/en/ipt/2.5/checklist-data

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/81804911de7ac8493e406c7fbd302330:540c28672efe265a054ecbe119064c8ce1a7d5d979d81ffc2330c5e75cbd73bb95829812e7caf9b76f23a5f36e9e61498ada7af4089a179a34220800e142b9f7)
System: Safari 14.1.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset-classes
Window size: width 1405 - height 766
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-02T13:25:09.058Z',to:'2021-11-02T13:31:09.058Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-02T13:25:09.058Z',to:'2021-11-02T13:31:09.058Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Updated—thanks!
