### ISSUE TITLE
Hi. A few questions to 1st user.I ran 1st query on Camassia howellii, to see how that works

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3714]
**Hi. A few questions to 1st user.I ran 1st query on Camassia howellii, to see how that works**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4e74889f947e4ba6701417b183ea779b:322c3faf605c5f0290841732d2a606378337e3375be8ad1e5a505371bd8d13aa04f76d741005c8d13e2b84e912de828837ccb13945cdb541e3f8479d97ac8d9c)
System: Safari 11.1.2 / Mac OS X 10.12.6
Referer: https://www.gbif.org/faq?question=for-how-long-will-does-gbif-store-downloads
Window size: width 1400 - height 862
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-02T16:58:40.035Z',to:'2021-11-02T17:04:40.035Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-02T16:58:40.035Z',to:'2021-11-02T17:04:40.035Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email as this user sent more detailed questions on helpdesk.
