### ISSUE TITLE
Add circled question mark to project page tabs

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3716]
**Add circled question mark to project page tabs**

The project page automatically includes tabs for datasets and news and event if available. To help projects, could we please add a (?) tab that simply shows this FAQ as a popup:

https://www.gbif.org/faq?question=how-can-i-link-datasets-events-etc-to-my-project-page

(could use class="circle-char" with a question mark that we use for inline faq popups)

Thanks!

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/41c9b1dc98eb33713315779042ab6012:eab47a2b107ded501f31111d105256dddf9614e5ef2f9354873d6089fb336099f1aad4d22ef5b3877071e2507a7414f02314b74839fddc7c9a3dfddf08d2a9c8)
System: Chrome 95.0.4638 / Mac OS X 10.15.7
Referer: https://www.gbif.org/project/82649/biodiversity-informatics-cookbook
Window size: width 1559 - height 1330
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-03T11:10:35.395Z',to:'2021-11-03T11:16:35.395Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-03T11:10:35.395Z',to:'2021-11-03T11:16:35.395Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I've always dreamt about us having a (?) tab on all pages, but one that explained what the entity was and how it related to other resources. So a "what am I looking at" for consumers, not a guide for publishers.

Does the FAQ belong in a tab? Isn't is like having a (?) tab on dataset pages with a description on how to debug and publish data. 

If it belongs to that page shouldn't it be like the "trusted contact" session on datasets. Or a footnote? Or in training material? Or on a general page about projects in GBIF that all that participate in a programme get? Or always show the dataset tab even when there is no datasets, and then have it as a note on that page.

I might be silly and I do not know who looks at those pages, but assuming it isn't primarily intended for the project owners themselves, then I think it is a bit confusing to add as a tab.

Let me know what you think. I very much like the idea of more help texts, but a tab with an FAQ for publishers wouldn't be my favourite solution. Is it a question you often get?

**Comment by dnoesgaard** [comment]
I like the idea of a general help tab/button/whatever, explaining what you're looking at and where to get more information!

This idea came out of discussions with Admin. It is intended for project leads and staff, who are not your average nor experienced publishers. We know that even though it is a requirement for projects, _and_ it is included in training materials and dataset requirement pages, getting them to (remember to) include the project ID in metadata is still a bit of a struggle. And we want to encourage projects to make _their_ project pages as rich as possible. 

I'm open to other suggestions, however, I don't think this should be hidden and only visible to certain logged-in contacts.

**Comment by MortenHofft** [comment]
Would this work. Always showing the tab (also if no data) - and then have a FAQ popup on that page.
<img width="1434" alt="Screenshot 2021-11-04 at 09 34 20" src="https://user-images.githubusercontent.com/6759267/140282595-8dd39261-093c-4202-8a69-2b62ac4099df.png">

<img width="1439" alt="Screenshot 2021-11-04 at 09 34 51" src="https://user-images.githubusercontent.com/6759267/140282609-802bdaf1-514c-4c40-ada6-892700cc77a1.png">

The same for events of course

**Comment by dnoesgaard** [comment]
Yeah, I think that works quite well. I'll split up the FAQ into two separate entries, then?

**Comment by dnoesgaard** [comment]
(I do like it when FAQs are specific!)

**Comment by dnoesgaard** [comment]
Dataset FAQ: 1GisR2xxlxvL2mfLmjVsEl
Events FAQ: 4seuMfKWNZ9LZjDSeiMu3P
