### ISSUE TITLE
The download for  DOI10.15468/dl.rw5n5r was supposed to contain ~1.5 million records but only returned ~650,000

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3726]
**The download for DOI10.15468/dl.rw5n5r was supposed to contain ~1.5 million records but only returned ~650,000**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d120ebe5380e87cf1067e237c9787f4b:91296f3fce35e1cf14937e1f0b130007c52037f17afd865a406b80fc3884d71039359e477ab27feb21252a937809d827d08a5280e88ba90256e612c1f37278a3)
System: Firefox 93.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0041178-210914110416597
Window size: width 1536 - height 739
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-03T15:40:11.663Z',to:'2021-11-03T15:46:11.663Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-03T15:40:11.663Z',to:'2021-11-03T15:46:11.663Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I checked with `wc -l 0041178-210914110416597.csv` and the file contained 1,512,860 lines so I don't think there is any bug. I will contact the user to let them know (and also that adding the continent filter removes about 8M records. -> Done
