### ISSUE TITLE
Dataset not crawling, registry-ws not responding

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#373]
**Dataset not crawling, registry-ws not responding**

This dataset isn't crawling because it's type is set to METADATA rather than OCCURRENCE.

Updating it in the registry console leads to a 503. If bypassing Varnish it hangs 'forever'.

-----
fbitem-datasetd62f9c58-7c8e-446e-84ad-d2a082ab79ea
Reported by: @MattBlissett
System: Firefox 54.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/dataset/d62f9c58-7c8e-446e-84ad-d2a082ab79ea
Window size: width 1920 - height 1038
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T16:06:13.758Z',mode:absolute,to:'2017-08-21T16:12:13.758Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-21T16:06:13.758Z',mode:absolute,to:'2017-08-21T16:12:13.758Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Also, registry-ws is at >400% CPU, which isn't good. Could that be related?

**Comment by cgendreau** [comment]
Dataset type changed to OCCURRENCE (using the console) and the dataset was successfully crawled
https://www.gbif.org/dataset/d62f9c58-7c8e-446e-84ad-d2a082ab79ea

closing for now
