### ISSUE TITLE
Large File Occurrence Data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3735]
**Large File Occurrence Data**

My json queried simple csv Excel document had more than 1,400,000 occurrences and was cut off after 1 sheet (1,400,000+ rows). What is the best way around this? Is it possible to download a text document to convert to csv?

Also, as a non programmer, it took me quite a bit of trial and error to figure out curl and json! Is the Helpdesk the best place to ask questions, or should I consider reaching out to the listed mentors on the site?

Thank you

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5707984fe7c6263cfa1979a4ee809ac5:2dc7f562f0c5120dd149c98148aa0b16a4873cd3d3e9d12aff32c250a8271a4d038474fc8ddcb58b9bdc5f0cd578fd60996a225340a907f82552b5168287ccbc)
System: Chrome 95.0.4638 / Windows 10.0.0
Referer: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
Window size: width 1024 - height 515
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-12T00:35:28.744Z',to:'2021-11-12T00:41:28.744Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-12T00:35:28.744Z',to:'2021-11-12T00:41:28.744Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:

> The CSV files generated by the downloads are really tab-separated text files. So most tools able to handle text files should also be able to handle this type of file (you could also change the extension from CSV to TXT).
You could try using some R library to process the file (see [our forum thread on the topic](https://discourse.gbif.org/t/reading-gbif-downloads-simple-csv-with-r/2615)) for example. You could also consider splitting the file or generating two downloads (with two set of species) so that each download generated is smaller and easier to handle.

> Note that we also have some of the GBIF data available on Microsoft Azure and AWS clouds which allows users to analyze the data directly on those platforms. That being said, I wouldn’t advise it if you are not very confident with programming languages. You are welcome to check our tutorials on the topic though ([Azure](https://data-blog.gbif.org/post/microsoft-azure-and-gbif/) and [AWS](https://data-blog.gbif.org/post/aws-and-gbif/)).

> You are very welcome to send your questions to helpdesk@gbif.org.
You can also post them on our forum or as comments on our blog (for example under [this API beginner guide](https://data-blog.gbif.org/post/gbif-api-beginners-guide/)).
