### ISSUE TITLE
Location error

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3740]
**Location error**

The label and detailed description state the location is "Harapan Rain Forest" in Jambi, Sumatra; not in Borneo

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6f585408c029279abe2d42424a96a335:db4fc470a4478d251f5bd0d6d2dba7517cbe7ced503a4a8050ea6e550304f9caa95ed3d37eb9fcf5f3eac8e855ce3a99e2056ea1d99b9d65d7ac622d37853020)
System: Chrome 95.0.4638 / Mac OS X 10.13.1
Referer: https://www.gbif.org/occurrence/2516884736
Window size: width 1280 - height 689
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-13T01:31:10.863Z',to:'2021-11-13T01:37:10.863Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-13T01:31:10.863Z',to:'2021-11-13T01:37:10.863Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 15f819bd-6612-4447-854b-14d12ee1022d
publishingOrgKey: 396d5f30-dea9-11db-8ab4-b8a03c50a862
Network keys: 17abcf75-2f1e-46dd-bf75-a5b21dd02655

**Comment by jeroencreuwels** [comment]
I have contacted the botanical collection managers to look at this. I agree that the coordinates are probably wrong and something like LatLong of -2.049219,103.31253 would be much closer to the real collecting place in Sumatra!

**Comment by jhnwllr** [comment]
The publisher removed the coordinates, so I am closing the issue.
