### ISSUE TITLE
How to Obtain Synonym Taxon Keys

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3742]
**How to Obtain Synonym Taxon Keys**

I noticed that when I grabbed a bunch of occurrence data for my collection of taxon keys that it included the occurrences for synonym taxa as well. I now need to tag the new synonym keys back to the species. I see that it's possible to access the infraspecies taxon information from a species page, but I can't always find the taxon key for the synonym taxa. What is the best way to do this? Is it possible to query directly with a JSON code? Thank you.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e3f249daa32aed0a9c942e6c4b3b5013:a098dc9f94641772b440849194dd980146993511e5910b73c6bdd066fc15186c6059236ee155a2db99a16b08104c6ce57238107c9b256958aaa233139054ace1)
System: Chrome 95.0.4638 / Windows 10.0.0
Referer: https://www.gbif.org/developer/occurrence
Window size: width 2048 - height 1031
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-14T04:00:20.335Z',to:'2021-11-14T04:06:20.335Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-14T04:00:20.335Z',to:'2021-11-14T04:06:20.335Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email together with other questions the user had.

I sent them the link to the documentation of the [Species API](https://www.gbif.org/developer/species)
