### ISSUE TITLE
Trouble with occurrence counts from API

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3743]
**Trouble with occurrence counts from API**

I managed to download occurrences by following the directions in the API, but have been unsuccessful with querying counts for observations from my collection of taxon keys. Would you be able to help me out?

Here is my curl line: 

curl --include --user smudd13:PASSWORD --header "Content-Type: application/json" --data @/c/Users/smudd/OneDrive/Documents/query.json https://api.gbif.org/v1/occurrence/counts

Then for the JSON portion I was unable to figure out how to assemble the code with the dimension component compared to the examples. If you could point me in the right direction, I would really appreciate it.

Thank you!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/faa5cecc0c90b72719b88d63c82880e3:d16421cee6487aa88aae2624d3db436e7177bafcb96da2dce19e41a350bd8161c81312ecf8be948ee70d32e0159b6269765cfd3c5777504be9f681030b435769)
System: Chrome 95.0.4638 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download?taxon_key=7307319
Window size: width 2560 - height 1232
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-15T06:59:59.923Z',to:'2021-11-15T07:05:59.923Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-15T06:59:59.923Z',to:'2021-11-15T07:05:59.923Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied to the user by email together with other questions.

I think the issue is that the URL used is https://api.gbif.org/v1/occurrence/counts but should be https://api.gbif.org/v1/occurrence/count
