### ISSUE TITLE
'ScientificName' for Pentagramma triangularis contains a comma. Would be great to have this removed, it was causing problems when I was processing data in R. It took forever for me to find this issue amongst millions of records.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3744]
**&#39;ScientificName&#39; for Pentagramma triangularis contains a comma. Would be great to have this removed, it was causing problems when I was processing data in R. It took forever for me to find this issue amongst millions of records.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d9df8fab6ffdbd50c63cdff3d537f35a:effa20d210ea9c4702c403a99c621e7ab2c5cd11a9c12b93a2151b0670b378ac162c7f4d482ca8a79665d0466c2839292141cb64e1b40890db7f7ba9f4990d30)
System: Firefox 94.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1536 - height 739
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-15T15:46:35.696Z',to:'2021-11-15T15:52:35.696Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-15T15:46:35.696Z',to:'2021-11-15T15:52:35.696Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The species concerned is this one but I don't think we can just remove the comma: https://www.gbif.org/species/5275443, can we?
