### ISSUE TITLE
Please could the contact details and email of user "PSG Webmaster" be removed from the dataset https://www.gbif.org/dataset/f49dfe83-55d7-4fd8-8d5e-3480cc9fa420. Thank you.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3756]
**Please could the contact details and email of user &quot;PSG Webmaster&quot; be removed from the dataset `https://www.gbif.org/dataset/f49dfe83-55d7-4fd8-8d5e-3480cc9fa420.` Thank you.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c22451709e9b70b72e3192da03ffe9ae:617378e839b80602169d4015bc7e8fca024df160db8dd458b5e784f3ff9399a1c36b9e5ea209c3a1a83621ef94a3fac96b1e13b136342cf74242a72a74131473)
System: Firefox 94.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/dataset/f49dfe83-55d7-4fd8-8d5e-3480cc9fa420
Window size: width 1440 - height 735
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-17T09:57:17.819Z',to:'2021-11-17T10:03:17.819Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-17T09:57:17.819Z',to:'2021-11-17T10:03:17.819Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Done, replied by email.
