### ISSUE TITLE
Data language mentioned as flemish

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#376]
**Data language mentioned as flemish**

The language should be Dutch http://www.loc.gov/standards/iso639-2/php/langcodes-keyword.php?SearchTerm=flemish&SearchType=ALL

-----
fbitem-dataset4dd32523-a3a3-43b7-84df-4cda02f15cf7
Reported by: @olafbanki
System: Chrome 60.0.3112 / Windows 7 0.0.0
Referer: https://www.gbif.org/dataset/4dd32523-a3a3-43b7-84df-4cda02f15cf7
Window size: width 1097 - height 548
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T08:01:58.244Z',mode:absolute,to:'2017-08-22T08:07:58.244Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T08:01:58.244Z',mode:absolute,to:'2017-08-22T08:07:58.244Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
thanks for reporting @olafbanki
the api returns "nld" so looks like a display issue.

**Comment by olafbanki** [comment]
Hi Christian,

The API is then correct because it should be NLD. On the webpage flemish is mentioned as the language and this is incorrect. 

Cheers,

Olaf

**Comment by MortenHofft** [comment]
Thanks. I have updated the translation file. it said flemish for nld for some reason. It will be available on the next build

**Comment by olafbanki** [comment]
Thanks Morten
