### ISSUE TITLE
"Calidris virgata Gmelin, 1789" is incorrect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3761]
**&quot;Calidris virgata Gmelin, 1789&quot; is incorrect**

Gmelin's original descriptions don't seem to be accessible online, but here's a link to a vintage paper confirming that the his original combination was  Tringa virgata. 

https://www.jstor.org/stable/1366692

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0fb2f6e574a75dac99d1009d4573f96d:db8f163a7a5aefd3af493fe3bab572ae574e126a6be72204d5dd5908d46a6bf392f91154f3b45ed27c9fe062aa216a51aeaf02e6b508e10f8b45049aeaff1fb5)
System: Firefox 94.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/species/7964835
Window size: width 1208 - height 912
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-17T20:46:17.785Z',to:'2021-11-17T20:52:17.785Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-17T20:46:17.785Z',to:'2021-11-17T20:52:17.785Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
source dataset that supplies the name is hosted by GBIF. 
https://www.gbif.org/dataset/19491596-35ae-4a91-9a98-85cf505f1bd3

**Comment by jhnwllr** [comment]
**Calidris virgata Gmelin, 1789**  should be **Calidris virgata (Gmelin, 1789)**

**Comment by jhnwllr** [comment]
@MattBlissett is the technical contact for the IUCN checklist. Any suggestions?

**Comment by CecSve** [comment]
From the [Name Parser](https://www.gbif.org/tools/name-parser/about)

bracketAuthorship
```
The authorship in brackets. Usually the authorship of the original name, e.g the basionym. 
```

authorship
```
The authorship with no brackets. Usually the combination authorship. 
```

**Comment by CecSve** [comment]
According to the[ IUCN Red List](https://www.iucnredlist.org/species/22693356/93398351) the original name is now the synonym. This means, according to GBIFs name parser, that the authorship should **not** be in brackets, since the species has been moved into another genus since the original description. This corresponds to the findings of the paper from the [link ](https://www.jstor.org/stable/1366692)in the question. I will therefore close the issue.
