### ISSUE TITLE
Nematus luteus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3764]
**Nematus luteus**

https://www.inaturalist.org/observations/99341514
https://www.inaturalist.org/observations/99341515

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/89be8ee248727ff11b5f74b175797f11:44339e92b1b6f118c0e5d40720bdb6594999461bd893faad52d30aa6c3161273347ba6d7915c4a7f0168bf87cacaae8057323f6fcfe2faa1e736d6c9acec992a)
System: Yandex Browser 21.11.0 / Windows 10.0.0
Referer: https://www.gbif.org/ru/species/4491479
Window size: width 1280 - height 884
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-18T12:41:19.119Z',to:'2021-11-18T12:47:19.119Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-18T12:41:19.119Z',to:'2021-11-18T12:47:19.119Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The observations are on GBIF: https://www.gbif.org/ru/occurrence/search?recorded_by=Andrey%20Ponomarev&taxon_key=4491476&advanced=1, I contacted the user to let him know.
