### ISSUE TITLE
New Zealand cut off content thumbnails

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#377]
**New Zealand cut off content thumbnails**

This is minor, but it's the first thing anyone from New Zealand or Pacific islands is going to notice: the preview images for "The GBIF network" and "Living Atlases" cut off New Zealand.

Maybe cut off the west of Alaska instead?

(Then we won't end up on http://worldmapswithout.nz/ )

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
Reported by: @MattBlissett
System: Firefox 54.0.0 / Mac OS X 10.12.0
Referer: https://www.gbif.org/
Window size: width 1440 - height 770
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T08:04:06.865Z',mode:absolute,to:'2017-08-22T08:10:06.865Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T08:04:06.865Z',mode:absolute,to:'2017-08-22T08:10:06.865Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I too think that a thumbnail service would be very nice

**Comment by timrobertson100** [comment]
Where should a thumbnail service reside?  Thumbnails likely need to use both the data service and the basemap service - we could put a dependency (it's an HTTP API) on the node mapnik server, or it could be a portal service.

Perhaps this might be a good time to also pull the node-mapnik server out of the Java project so the web team can also contribute - it doesn't belong where it is now.

**Comment by MattBlissett** [comment]
This isn't related to the basemaps, is it? We don't have the GBIF network or atlases maps presented as vector/raster tiles.

Thumbor can chop from the left or the right when cropping:

![left](https://api.gbif.org/v1/image/unsafe/200x141/left/http:%2F%2Fimages.contentful.com%2Fuo17ejk9rkwj%2F1DOkVqCKre2awaEkmeOsi8%2F15860f7309863c5e3d31c15a65d5dd75%2Fgbif-network.png)

![right](https://api.gbif.org/v1/image/unsafe/200x141/right/http:%2F%2Fimages.contentful.com%2Fuo17ejk9rkwj%2F1DOkVqCKre2awaEkmeOsi8%2F15860f7309863c5e3d31c15a65d5dd75%2Fgbif-network.png)

but the original image is missing New Zealand anyway

![original](https://api.gbif.org/v1/image/unsafe/0x141/http:%2F%2Fimages.contentful.com%2Fuo17ejk9rkwj%2F1DOkVqCKre2awaEkmeOsi8%2F15860f7309863c5e3d31c15a65d5dd75%2Fgbif-network.png)

**Comment by timrobertson100** [comment]
Sorry - the comments relating to a thumbnail service were more generally speaking for e.g. species maps which appear in search results as thumbnails.  Seems like consistent thumbnails across the site might be useful to me (for network maps or for occurrence data driven)

**Comment by MortenHofft** [comment]
Ahh - I understood it as a general thumbnail issue as well. Because there is that.
@dnoesgaard It relates to this image in case you want to change it https://app.contentful.com/spaces/uo17ejk9rkwj/assets/1DOkVqCKre2awaEkmeOsi8

**Comment by dnoesgaard** [comment]
Although it pains me cut off any part of Alaska (except maybe Wasilla), I've re-centered the image for the GBIF network feature now so that NZ is visible. Maybe @kcopas can do the same for the Living Atlases feature?
