### ISSUE TITLE
dataset record contains a dead link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3771]
**dataset record contains a dead link**

The dataset https://www.gbif.org/dataset/b0a42677-76a5-445a-aa5e-d1956f4ab142 should have the alternate identifier: http://ipt.vliz.be/eurobis/resource?r=epibenthos_demersal_fish_aniline_discharge_belgian_shelf_1982-1984 removed

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/58714d3fc0a21a3562618c440b05b452:0d261513bc4292f51fb0c70d785cc0b13b58bc4c7d04c031685264228e631602d21e4b3b00a6f489698010c029aca10d5608c02b3c7c256252e9c5716880efa4)
System: Chrome 96.0.4664 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1920 - height 880
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-22T08:59:18.180Z',to:'2021-11-22T09:05:18.180Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-22T08:59:18.180Z',to:'2021-11-22T09:05:18.180Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Removed alternative identifier in the registry
