### ISSUE TITLE
Key visuals in SVG only, not PPT friendly

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3774]
**Key visuals in SVG only, not PPT friendly**

I am probably not the only one using these key visuals in PPTs often. Currently have to mess with screenshots. Can we have the same nice choice of PNG and SVG like in Metrics please?

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/14d6396d7205df8837b80ee8d13ebc99:3a56312b2a8747549be5ef2a3aa94366625e0c58a02f71eec1b5cb657870d66977ccf017fdedfb51b1c60656fd3cf3b515b392cffc7cae46bbacfda5bc4e6130)
System: Chrome 96.0.4664 / Windows 10.0.0
Referer: https://www.gbif.org/analytics/global
Window size: width 2048 - height 1000
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-24T14:38:45.423Z',to:'2021-11-24T14:44:45.423Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-24T14:38:45.423Z',to:'2021-11-24T14:44:45.423Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
While I am on that: axes fonts in these screenshots don't seem to match the website or the PPT template resulting in ugly combinations... a detail.

**Comment by MattBlissett** [comment]
You can change `svg` in the URL to `png` and get a PNG version.

(And I think the newest version of PowerPoint has support for SVGs, as it's what we provide for the publisher maps: https://analytics-files.gbif.org/registry/organization/active_gbif_publishing_organizations_by_country.svg)

**Comment by dschigel** [comment]
Perfect, it works, happy to learn
