### ISSUE TITLE
how to get DOI from download?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3776]
Hello, the last time I used GBIF data it was a dataset a co-author sent to me and she did not send along the doi. Now I need to get in contact as the editors are asking for this number and my co-author cannot remember this number and is too busy to get it. How can I get this number? What do you need to know in order to have this number? The taxonomic group is Cocoseae tribe of the palm family Arecaceae. Thank you so much. I am looking forward to hear from you. My email is cintuca@gmail.com

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/554ba98318640c799b2957b3ddc1ad59:cbd74e1d52873121ad4e5b6c3c97aec91d7a176778987dc10d8b05ec8b54e78a9f9671478ad335a3f6932f8f0271b49496819ada95e60cb7d6fe8e8f72cce3a5)
System: Chrome 95.0.4638 / Linux 0.0.0
Referer: https://www.gbif.org/citation-guidelines
Window size: width 1294 - height 636
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-26T18:28:04.065Z',to:'2021-11-26T18:34:04.065Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-26T18:28:04.065Z',to:'2021-11-26T18:34:04.065Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
Replied by email:

> We are happy to help you find the DOI associated with the download you used but it would help us if you could give us a bit more information.
Ideally, it would really help us to know the name (and/or email address) of the person who generated the download, as well as the download date and filter used.
If you don’t have an exact download date, we can look for downloads within a data range.
