### ISSUE TITLE
How do I delete my account?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3778]
**How do I delete my account?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6a822ba9d50ff62bac795eaf499eeafb:eb41da8a601c1b4ac2f53d8dbb46ee13c5fc61656721f2056240cb08081b7a614af88ea19d40b30fed6f515462a0c0948f8ea3d7fb116fc92f168ac192606234)
System: Chrome 95.0.4638 / Mac OS X 10.15.7
Referer: https://www.gbif.org/faq?q=delete%20account
Window size: width 1532 - height 734
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-27T06:25:28.166Z',to:'2021-11-27T06:31:28.166Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-27T06:25:28.166Z',to:'2021-11-27T06:31:28.166Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
> notified by email

You need to send a request to heldpesk@gbif.org
