### ISSUE TITLE
would be great i f I could choose map projection is this kind of data view

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#378]
**would be great i f I could choose map projection is this kind of data view**

-----
fbitem-632937989213bf4e43cb42556216fa1047383e29
Reported by: icalabuig@snm.ku.dk
System: Chrome 60.0.3112 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/map?dataset_key=8c3e2fd5-2c7a-4126-a5c0-b6f67c9911db&dataset_key=a968d7e9-5391-482d-8927-4b34b9863d56&advanced=1
Window size: width 2048 - height 1024
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T08:07:10.276Z',mode:absolute,to:'2017-08-22T08:13:10.276Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T08:07:10.276Z',mode:absolute,to:'2017-08-22T08:13:10.276Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thanks
I'm afraid that it isn't something that we can do at this point, but it would be very nice indeed.

**Comment by MattBlissett** [comment]
We partly could, although it relies on the OpenLayers reprojection of raster tiles.

Examples from Isabelle's query, in Arctic and Web Mercator projections:

<img width="515" alt="screen shot 2017-09-21 at 17 19 11" src="https://user-images.githubusercontent.com/583320/30703916-54a5dba6-9ef1-11e7-9be3-9b5e4bf03984.png">
<img width="645" alt="screen shot 2017-09-21 at 17 19 38" src="https://user-images.githubusercontent.com/583320/30703917-54a63fb0-9ef1-11e7-8b05-f9c20ff8b7c7.png">

Then BGBM's data:

<img width="514" alt="screen shot 2017-09-21 at 17 21 06" src="https://user-images.githubusercontent.com/583320/30703918-54d5e562-9ef1-11e7-9f8b-0cdf7731f83a.png">

And plants:

<img width="513" alt="screen shot 2017-09-21 at 17 23 54" src="https://user-images.githubusercontent.com/583320/30704039-b0aab142-9ef1-11e7-97fe-0f2e56b4a015.png">

**Comment by MortenHofft** [comment]
I'm closing this. The client reprojection isn't really a good solution I think. My computer fans goes crazy when I tried it. Working on getting ES and vector tiles working seems to be the direction we are heading instead.
