### ISSUE TITLE
Continent "NA" not interpreted as "North America"

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#3784]
We have a doubt about what values are accepted in the field continent in the portal.

We always use the two letters representation in this field, and it works for South America (SA), but it does not work for North America(NA), for example in this [record](https://www.gbif.org/es/occurrence/2640762952).

So we should like to know what are the valid ways to do it or if you have recommendations for documenting this field.

Thanks in advance!

**Comment by MattBlissett** [comment]
Ah, that seems like a bug. "NA" is often ignored since it can mean "Not Applicable", although we have an exception for the country code Namibia.

The best values are as follows, from http://api.gbif.org/v1/enumeration/basic/Continent.  `_` or ` ` doesn't matter, and neither does case.

```
  AFRICA
  ANTARCTICA
  ASIA
  OCEANIA
  EUROPE
  NORTH_AMERICA
  SOUTH_AMERICA
```

**Comment by ManonGros** [comment]
I will close this issue, ok?
the conversation around interpretation for continents can continue here: https://github.com/gbif/vocabulary/issues/72
