### ISSUE TITLE
The interpreted date seems to be wrong :  "2008-06-01/2008-06-30" is interpreted to "2008-06-01"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3786]
**The interpreted date seems to be wrong : &quot;2008-06-01/2008-06-30&quot; is interpreted to &quot;2008-06-01&quot;**

-----

Github user: @jbdesbas
User: [See in registry](https://www.gbif.org/api/feedback/user/b4381be3a40e9e63a8fcba1f3c4fdd64:699468444f874b795d5280cf3c6cda873eda12784ce4e71b4c97c46056b053e56a72b230f94911e7519ddeeef9d116fdf1a559a8c3c48a2259868fd0820a4369)
System: Firefox 94.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/occurrence/1252442994
Window size: width 1920 - height 930
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-29T21:40:49.905Z',to:'2021-11-29T21:46:49.905Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-11-29T21:40:49.905Z',to:'2021-11-29T21:46:49.905Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO
datasetKey: 271c444f-f8d8-4986-b748-e7367755c0c1
publishingOrgKey: 1cd669d0-80ea-11de-a9d0-f1765f95f18b

**Comment by jhnwllr** [comment]
@jbdesbas 

GBIF does not currently interpret date ranges unfortunately, so that is why only one date was used.

**Comment by jbdesbas** [comment]
Ok understood, thanks. 
So shouldn't the _day_ field be  NULL ?

**Comment by MattBlissett** [comment]
That's a reasonable point, although we also have occurrences published with a `day`, and an `eventDate` covering more than one day.

https://github.com/gbif/gbif-api/issues/2 and https://github.com/gbif/gbif-api/issues/4 led to the current use of the start of the range for `year`, `month` and `day`.

(I won't reopen this issue, as it's now linked from those two anyway.)
