### ISSUE TITLE
Please check stats on accepted names and synonyms

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#379]
**Please check stats on accepted names and synonyms**

What do the stats underneath the description signify. For example there are 523 accepted names listed in IPNI? That would sound way to low. Or does it mean there are only 523 accepted names listed in the GBIF Backbone taxonomy? What does 0 synonyms signify? Perhaps I a mistunderstanding these stats.

-----
fbitem-dataset046bbc50-cae2-47ff-aa43-729fbf53f7c5
Reported by: @olafbanki
System: Chrome 60.0.3112 / Windows 7 0.0.0
Referer: https://www.gbif.org/dataset/046bbc50-cae2-47ff-aa43-729fbf53f7c5
Window size: width 1097 - height 548
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T08:08:59.513Z',mode:absolute,to:'2017-08-22T08:14:59.513Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T08:08:59.513Z',mode:absolute,to:'2017-08-22T08:14:59.513Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by olafbanki** [comment]
Dave is still mentioned as administrative contact:

David Remsen
Administrative Point Of Contact
Programme Officer
GBIF Secretariat
Universitetsparken 15
Copenhagen 2100
Ø
Denmark
dremsen@gbif.org
+45 28751472
http://www.gbif.org

**Comment by mdoering** [comment]
IPNI does not provide synonyms to us, just a flat list of names. Thats why synonyms=0. They also do not state whether a name is accepted, nomenclaturally valid. The 523 accepted names are just the families they use to classify the names: https://www.gbif.org/species/search?dataset_key=046bbc50-cae2-47ff-aa43-729fbf53f7c5&status=ACCEPTED&advanced=1

This is correct but misleading I agree. @MortenHofft maybe we should not display number of accepted names in case the checklist is of subtype NOMENCLATOR_AUTHORITY ?

**Comment by olafbanki** [comment]
Thanks Markus for the clarification.

**Comment by MortenHofft** [comment]
@mdoering This has since changed to display 1,587,835 accepted names instead. Should we still hide accepted names for subtype NOMENCLATOR_AUTHORITY?

**Comment by mdoering** [comment]
Yes, it would be good for NOMENCLATOR_AUTHORITY datasets to just state "x number of names" and not differ between synonyms and accepted. Just add them both up and show them as one count (even thugh there *should* not be synonyms)

**Comment by MortenHofft** [comment]
I've removed the stats for subtype NOMENCLATOR_AUTHORITY.

https://github.com/gbif/portal-feedback/issues/379#issuecomment-323955958 is still the case

**Comment by ManonGros** [comment]
I deleted David as a contact. I am closing the issue, unless I missed anything?
