### ISSUE TITLE
Month & year

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3790]
**Month &amp; year**

taxon recorded by Helm P. G., collection year is incorrect. 
instead of the 20th century, it should be the 19th century.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6950924118e2ca8098c9bf226c305b83:79a2b31a4f73adbeed8a39204764fc96de2b8df2e244259ce6d585a63cd21dc27ba25706cf63abb8291b89f3f6e0c6295de1fc16344d9d84534c646092b61c6e277929f56b47262e6aef057d365fa2a3)
System: Yandex Browser 21.11.1 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?recorded_by=Helm%20P.%20G.&advanced=1
Window size: width 1366 - height 628
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-02T05:35:44.462Z',to:'2021-12-02T05:41:44.462Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-02T05:35:44.462Z',to:'2021-12-02T05:41:44.462Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
Same as this issue: https://github.com/gbif/portal-feedback/issues/3741
I already contacted the publisher.
