### ISSUE TITLE
Dataset has broken encoding

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3795]
**Dataset has broken encoding**

The dataset is not in UTF8 - it seems to be UTF-8 that has then been interpreted as 1252 and reencoded as UTF-8 (all mismatched characters show the values here: https://www.i18nqa.com/debug/utf8-debug.html).

-----

Github user: @dhobern
User: [See in registry](https://www.gbif.org/api/feedback/user/79ef6af29888c155c2dbca4ebd1b97fe:f7caf875b6a396bb5ad8e64ae8975b844fcfe8296ba51cab6d683924a97d8737a068838796750436c37ad57ce1a4b731ee51b82efd72db4c276f9d3f88abb2d6)
System: Chrome 96.0.4664 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/15147db1-27c3-49b5-9c69-c78d55a4b8ff
Window size: width 1920 - height 929
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-06T04:24:42.007Z',to:'2021-12-06T04:30:42.007Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-06T04:24:42.007Z',to:'2021-12-06T04:30:42.007Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
I will write to the publisher.

**Comment by jhnwllr** [comment]
Will contact Shyama Pagad.

**Comment by MattBlissett** [comment]
Fixable with [ftfy](https://ftfy.readthedocs.io/), e.g. `ftfy -o australia_griisgbif2021c_pub_fixed_encoding.csv australia_griisgbif2021c_pub.csv` after saving as CSV from Excel. (Then I replaced ` x ` with ` × ` for consistency.)

[australia_griisgbif2021c_pub_fixed_encoding.xlsx](https://github.com/gbif/portal-feedback/files/7718848/australia_griisgbif2021c_pub_fixed_encoding.xlsx)

**Comment by dhobern** [comment]
Thanks - I am so glad to have learned of ftfy ...

**Comment by MattBlissett** [comment]
Looks fixed, e.g. https://www.gbif.org/species/162494056
