### ISSUE TITLE
Edit to contact

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3796]
**Edit to contact**

PLease replace ", and Dmitry Schigel, GBIF scientific officer." with ", or health@gbif.org". FYI both the health contractor and I will be watching this inbox.

Perhals this is also the contact you want to indicate for the new webpage on GBIF health?

Thanks!

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/dceb99c9a42ffcd1f0211620346b9783:951da30975ad5b27e6a00b1446a6f153dedec8ce5861c6b3c45786112b4e0342b60808dda9a92f3da94333fd92f86c0e181552502da91c6e061d6d26624d7a27)
System: Chrome 96.0.4664 / Windows 10.0.0
Referer: https://www.gbif.org/news/u076BiFDma9AZqOyf7rkk/call-for-data-papers-describing-datasets-on-vectors-of-human-diseases
Window size: width 1862 - height 926
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-06T10:34:35.813Z',to:'2021-12-06T10:40:35.813Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-06T10:34:35.813Z',to:'2021-12-06T10:40:35.813Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
maybe this is an issue for @dnoesgaard or @akristensen?

**Comment by dnoesgaard** [comment]
Done.
