### ISSUE TITLE
Certain zoom levels create the appearance of a straight line on maps

### ISSUE THREAD

**Issue by jhnwllr** [gbif/portal-feedback#3799]
https://github.com/gbif/portal-feedback/issues/3650

https://www.gbif.org/dataset/8ea94e2a-118c-4a53-a957-5348d48d61e1

<img width="420" alt="Screenshot 2021-12-07 at 11 35 25" src="https://user-images.githubusercontent.com/4245213/145015414-21aada87-7528-4a3e-9a54-0244b05f1a81.png">
<img width="817" alt="Screenshot 2021-12-07 at 11 34 14" src="https://user-images.githubusercontent.com/4245213/145015415-bf0f368c-cc1e-418b-bccb-efb2ee06d008.png">

**Comment by ManonGros** [comment]
Note that on the dataset map (map on the dataset page), the data look like a straight line no matter the zoom level.

**Comment by MattBlissett** [comment]
The data was changed this morning, you must have seen a cached map tile. The old data has `-75.798` for all the latitudes.

The dataset page map will be refreshed in the next map build, in about an hour, and in the HDFS table tomorrow morning.
