### ISSUE TITLE
taxonKey filter on checklists out of order?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#38]
**taxonKey filter on checklists out of order?**

We searched for taxonKey=1355948 and found it should be in 14 checklists. When clicking the link alle checklists are displayed and not only the 14 which contains taxon 1355948

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c
Reported by: @NHMD
System: Chrome 55.0.2883 / Mac OS X 10.10.2
Referer: https://demo.gbif.org/dataset/search?type=CHECKLIST&amp;taxonKey=1355948
Window size: width 1835 - height 1065
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-17T10:42:13.313Z',mode:absolute,to:'2017-01-17T10:48:13.313Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-17T10:42:13.313Z',mode:absolute,to:'2017-01-17T10:48:13.313Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
The API responds correct: https://api.gbif.org/v1/dataset/search?type=CHECKLIST&taxonKey=1355948

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/230
