### ISSUE TITLE
add missing link to strategic plan

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#380]
**add missing link to strategic plan**

strategic plan
<a href="/strategic-plan">

-----
fbitem-5e59ac11e30838aa9d201b7ecad598e743c16cb7
Reported by: @dnoesgaard
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/suggest-dataset
Window size: width 1880 - height 892
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T08:29:12.239Z',mode:absolute,to:'2017-08-22T08:35:12.239Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T08:29:12.239Z',mode:absolute,to:'2017-08-22T08:35:12.239Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
sorry, my html got stripped. should link to /strategic-plan
