### ISSUE TITLE
name has changed from DNG to DNV, remove old website and only mention dnv: https://www.dnv.com/about/index.html

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3800]
**name has changed from DNG to DNV, remove old website and only mention dnv: `https://www.dnv.com/about/index.html`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0ec22b6f70a1c6284081fee57b8f4580:b8f321464faae14292d68d0e7a7f0ee12f23d74aa4313047c6261a2c25a5bf034e15f275f77924e8e59d38ac60dea084942fa2d3b40e2a623a8165614d66a1af)
System: Chrome 96.0.4664 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/efc5d3c7-2fec-42dd-85de-078a73973bd1
Window size: width 2560 - height 1297
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-07T12:53:52.680Z',to:'2021-12-07T12:59:52.680Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-07T12:53:52.680Z',to:'2021-12-07T12:59:52.680Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@dagendresen could you take a look at this issue and let us know if this should be closed?
