### ISSUE TITLE
FAQ shows "hidden" entries

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3801]
**FAQ shows &quot;hidden&quot; entries**

Not sure if this is a feature or a bug, but the main FAQ returns entries that have "no" selected in the "Discoverable in search results on GBIF.org?" field.

Either way, I think it makes sense to only show the ones with "yes" in this field.

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/87e7b80a53ad0e75886edc025c1bcbcd:97c31c5dadb247e571ff8a38551142133a8a72efe3fa4465a0836bd2810daf4905b950ac0a3b9e34b026496c77407eb84c6deb76e54c04183e5d737ea6fbc482)
System: Chrome 96.0.4664 / Mac OS X 10.15.7
Referer: https://www.gbif.org/faq
Window size: width 2090 - height 1072
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-08T11:33:25.065Z',to:'2021-12-08T11:39:25.065Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-08T11:33:25.065Z',to:'2021-12-08T11:39:25.065Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I probably wasn't aware that there was such a label on FAQ items. We can filter them out. Why is it there? Do we need FAQ items that isn't searchable?

UPDATE: ahh - I might be able to answer that myself. We use FAQ items for popup boxes where the content shouldn't go into the FAQ?

**Comment by dnoesgaard** [comment]
Exactly.
