### ISSUE TITLE
some backbone names have twice the same authorship

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3802]
**some backbone names have twice the same authorship**

This issue was originally reported on Helpdesk.
I don't think this comes from the data sources but from some processing.
The names reported were:
- Clematis × jackmanii T.Moore T.Moore (https://www.gbif.org/species/3033584)
- Caryopteris × clandonensis N.W.Simmonds N.W.Simmonds (https://www.gbif.org/species/9417675)
- Hebe × andersonii (Lindl. & Paxton) Cockayne (Lindl. & Paxton) Cockayne (https://www.gbif.org/species/5560096)

But I suspect other names might have similar issues.

@mdoering could you take a look?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/77343c3c4cc46a3abec8c8fcbc2b2bfd:a78ac7bdd1c46b9e7b9fa408c73ec071d5e9b657238da9ef23e6afadd7abf20af3b6c61393050855d2ed38ce555121e281e4d5c10b5c49fa0f87d6c7f38b1fb0)
System: Safari 14.1.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/9417675
Window size: width 1207 - height 796
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-08T15:08:17.154Z',to:'2021-12-08T15:14:17.154Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-08T15:08:17.154Z',to:'2021-12-08T15:14:17.154Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@thomasstjerne this looks like an issue with the formatted name parser?

The thing is - there is no API to provide names with italics. So Thomas has written one because users wanted italics. It looks like that is the one causing issues in this case.

The name in the API is fine https://api.gbif.org/v1/species/3033584
And the one parsed by the API looks good as well https://api.gbif.org/v1/species/3033584/name

**Comment by mdoering** [comment]
We have added a label and labelHtml to the COL API. It will take a while until we do the switch, so maybe it would be good to provide the same for a NameUsage in the GBIF API?

**Comment by MortenHofft** [comment]
That would be wonderful yes. Especially because I would like to use that in the GraphQL endpoints as well.

**Comment by MortenHofft** [comment]
Currently GraphQL has a copy of the portal version. So when Thomas fix this issue as above, then the hosted portals still show the wrong name

**Comment by thomasstjerne** [comment]
Our formatting got confused because the author is included in the scientificName [here](https://api.gbif.org/v1/species/3033584/name) but not [here](https://api.gbif.org/v1/species/7310827/name)
I think it catches both cases now.
