### ISSUE TITLE
Unfurtunate use of vernacular names

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3803]
**Unfurtunate use of vernacular names**

The "National checklist of all species occurring in Denmark" is becoming the "authorized" taxon list from Denmark. Because of this we would very much appreciate if the vernacular names on GBIF also follow the national checklist.

For the time being there is a lot of wrong vernacular names attached to danish taxa, many of which derives from DAISIE.

An example:

The correct danish name for Centaurea cyanus (https://www.gbif.org/species/3089561) is Kornblomst. The danish name shown in GBIF is Gul Fladbælg. The source (DAISIE) even use several different names for the same taxon.

Hopefully you will be able to make a connection between scientific names and vernacular names from the Danish checklist.

Best regards
Lars

-----

Github user: @LarsSkipper
User: [See in registry](https://www.gbif.org/api/feedback/user/557e2eb18212b55cc880b8b27ee6a480:40d717d941f11747c95e80cf2fae299db468bd8652698680b81cb90ed05a6827fa5993ddcf98f597b26675fe32fd2219c84502f4d05f4fd9fca09c0998eb4f8b)
System: Firefox 94.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/3089561?vnOffset=40
Window size: width 1536 - height 751
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-09T14:44:26.671Z',to:'2021-12-09T14:50:26.671Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-09T14:44:26.671Z',to:'2021-12-09T14:50:26.671Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thanks - I can see why this would be useful.

Currently no dataset is considered more trustworthy than others in this regard. To change this we would either have to 
* Create or update the APIs to give priority to certain checklists
* Maintain a curated list in the frontend of checklists to prioritise (this version of course is more fragile, won't naturally carry between website iterations and won't benefit API users).

I'm not sure how to decide what checklists to trust, but I guess that could be decided by the nodes. And then hope that e.g. Spanish speakers from different countries do not disagree on the correct name (no doubt there will be disagreement)

**Comment by LarsSkipper** [comment]
Thanks for your Answer, Morten.

As you probably know Thomas Stjernegaard has made a "hook", so the danish vernacular names follow The "National checklist of all species occurring in Denmark".

I can see the problem regarding e.g. spanish speaking countries. Fortunately Denmark is a sufficiently small and unimportant country on a global scale for that to be an issue :-)
