### ISSUE TITLE
I've spotted that Sheffield Museum appears to be listed twice on GBIF.  Once as SHF (Museums Sheffield, Weston Park Museum) and once as CMSK (City Museum, Sheffield).  As curator of natural science for the institution, I can confirm that these two are one and the same.  Is it possible to merge these two under SHF (Weston Park Museum, Sheffield), whilst retaining the CMSK as an alternative?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3804]
**I&#39;ve spotted that Sheffield Museum appears to be listed twice on GBIF. Once as SHF (Museums Sheffield, Weston Park Museum) and once as CMSK (City Museum, Sheffield). As curator of natural science for the institution, I can confirm that these two are one and the same. Is it possible to merge these two under SHF (Weston Park Museum, Sheffield), whilst retaining the CMSK as an alternative?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1be9ec283ff0d8531fcd35178f49dfae:7f06642d79882df5a633c2a95c7252330673e67dfb4c6829a322baeacbc35500c6db5732432be2d7c69f094b444335e8c4e1f0730d876ca9f1807ca48ff237efc88fee0800d7bea5a480b9f81b9dcdd9)
System: Chrome 96.0.4664 / Windows 8.1.0.0
Referer: https://www.gbif.org/user/confirm
Window size: width 1366 - height 625
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-09T15:22:11.489Z',to:'2021-12-09T15:28:11.489Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-09T15:22:11.489Z',to:'2021-12-09T15:28:11.489Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Institution merged and user notified (from the GRSciColl email address)
