### ISSUE TITLE
new validator page: "Here" link for feedback links back to same page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3806]
**new validator page: &quot;Here&quot; link for feedback links back to same page**

The link that should allow to log an issue in GitHub just leads back to the same page that it is coming from (validator report). Hyperlink needs correction (https://github.com/gbif/pipelines/issues/new ?)

-----

User: [See in registry](https://www.gbif-uat.org/api/feedback/user/4e53d8a4b08c033316cf6a6fe16bb6b9:bbeec73c60a9c534a174683ea077b3e7254de28e92596e511795ac430889e93d571e3aa675baa2e54edf1feae8f72a7114b2ad74795a27128e3abb697449488a)
System: Firefox 95.0.0 / Windows 10.0.0
Referer: https://www.gbif-uat.org/tools/data-validator/4ef486ee-9a2d-482b-a735-7b715e3ee5de
Window size: width 965 - height 829
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-09T16:03:35.923Z',to:'2021-12-09T16:09:35.923Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-09T16:03:35.923Z',to:'2021-12-09T16:09:35.923Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@ahahn-gbif could it be because of your browser parameters? On my browser it does the same think as clicking on the feedback button (opens the little form in the upper right corner).

**Comment by ahahn-gbif** [comment]
Hm, you are right - today it does that. No browser parameters changed, but seems to be ok - closing
