### ISSUE TITLE
literature enum issue (literatureType)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#381]
**literature enum issue (literatureType)**

the enum fix we did for literature doesn't seem to have been applied to literatureType, as the counts for all types are currently 0.

Also, I'd like to correct the display names for literatureType to exclude underscores, etc.

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb
Reported by: @dnoesgaard
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/resource/search?contentType=literature&literatureType=JOURNAL
Window size: width 1880 - height 892
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T09:10:27.720Z',mode:absolute,to:'2017-08-22T09:16:27.720Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T09:10:27.720Z',mode:absolute,to:'2017-08-22T09:16:27.720Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
yep - we changed the index yesterday afternoon to use CAPITALIZED_ENUMS instead of the many versions of camelCase, Capitalized_underscores, spaced enums etc. The interface search items need updating to reflect it. @fmendezh could you update it inthe mendeley crawler as well please?

**Comment by MortenHofft** [comment]
fixed on uat

**Comment by dnoesgaard** [comment]
Just curious, it works now, yes, but doesn't look like the literatureType is CAP'D?

https://www.gbif.org/resource/search?contentType=literature&literatureType=journal&relevance=GBIF_USED

**Comment by MortenHofft** [comment]
nope - Fede had capitalized all but that one. A communications misunderstanding and since he is a busy man I adapted to the exception. I would prefer consistency in how we used enums, but this was the pragmatic approach.
