### ISSUE TITLE
order by date or Filter by date:  i.e. events and documents

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3816]
**ability to order by date or a filter by date functions: i.e. events and documents**

example: https://www.gbif.org/resource/search?q=portuguese&contentType=event

The search is on "Portuguese" but I can only see future, not the entire series. The order is not chronological.

Another example is a search on  "meeting reports": https://www.gbif.org/resource/search?q=Meeting%20Report

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6987e957d1765e6c34477a7806699ecb:11ef492d2df469348bbe1b3c3cb66db7d66f863fda55b47cc29189c9cee81f62d9e561f55b9926d8b27ce65dbcde5a930f1224da0aa57f677aea3c6a52d306b2)
System: Chrome 96.0.4664 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?contentType=event
Window size: width 2560 - height 1297
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-14T09:38:29.288Z',to:'2021-12-14T09:44:29.288Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-14T09:38:29.288Z',to:'2021-12-14T09:44:29.288Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
**How it currently works**

> The order is not chronological.

Results filtered by free text is sorted by relevance (a good text match). So not by date. 

> The search is on "Portuguese" but I can only see future, not the entire series

You can filter events on past and future by applying the filter in the left drawer. Just like you would with other filters.

> Another example is a search on "meeting reports": https://www.gbif.org/resource/search?q=Meeting%20Report

Would you expect the result to be ordered by dates?

**Changes**
We can change search to always sort chronological. @dnoesgaard you should be involved if this is to be changed.

**Comment by dnoesgaard** [comment]
I'm tempted to say yes, but I'm also unsure about the consequences. Sorting by date might make sense in cases when you are searching for something very specific, but perhaps not in others.

That being said, if changing this is not a major task, I think we should try it for **events**—and then revert if it doesn't work as expected.

I'm not sure if the use case for showing a whole series of events is that big—but @akristensen might know otherwise. The solution could be to add a third option to the filter, i.e. "upcoming", "past", "all"...

**Comment by MortenHofft** [comment]
Personally i prefer sorting by relevance, but it is trivial to change if we want to. I've created an example to argue for sorting by relevance.

## Search for "open webinar" when sorting by relevance.

<img width="760" alt="Screenshot 2022-01-12 at 12 47 55" src="https://user-images.githubusercontent.com/6759267/149134941-2ab3c69b-2553-425d-abb0-457dfcf89ae5.png">

## Search for "open webinar" when sorting by date
These are still reasonable results (they include both words)
<img width="751" alt="Screenshot 2022-01-12 at 12 48 05" src="https://user-images.githubusercontent.com/6759267/149135039-9a6fdcc7-8501-4f49-9525-64251842ff16.png">

**Comment by dnoesgaard** [comment]
Thanks, Morten, this is exactly what I was referring to. I'm sure sorting by date would be good when searching for a very specific term, but for generic searches, it will be messy.

**Comment by dnoesgaard** [comment]
I guess we could consider allowing the user to choose a sorting order on their search results?

**Comment by MortenHofft** [comment]
It is now in production as discussed in private messages

https://www.gbif.org/resource/search?q=open%20webinar&contentType=event&_showPastEvents=true
