### ISSUE TITLE
Key for occurence map - Meaning of colours of the dots on the maps

### ISSUE THREAD

**Issue by DocLahulotte** [gbif/portal-feedback#3819]
Hello,
I can't find any key for occurence map 

Perhaps density of observations, according to

**Comment by MattBlissett** [comment]
Hi,

It isn't documented properly on the website.

For the default yellow-orange-red map, the boundaries are as follows:

https://github.com/gbif/maps/blob/6a51a063b399f2030982138a5174119968334b1c/mapnik-server/src/main/node/cartocss/classic-dot.mss#L3-L7

```
                 [total <=    10] { dot-fill: #FFFF00;  }
  [total >    10][total <=   100] { dot-fill: #FFCC00;  }
  [total >   100][total <=  1000] { dot-fill: #FF9900;  }
  [total >  1000][total <= 10000] { dot-fill: #FF6600;  }
  [total > 10000]                 { dot-fill: #D60A00;  }
```


i.e. the boundaries are at 10, 100, 1000, 10000.

**Comment by ManonGros** [comment]
Hi @DocLahulotte 
Just adding to Matt's answer, you can also download the georeferenced records and make your own map.
I will close the issue now but let us know if anything remains unclear or if you have more questions.
