### ISSUE TITLE
find number of mammals in china

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#382]
**find number of mammals in china**

-----
fbitem-6229f97d983b0ca850db2714bee3e34d3773b8f9

System: Chrome 60.0.3112 / Mac OS X 10.12.0
Referer: https://www.gbif.org/tools/species-lookup
Window size: width 1440 - height 786
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T11:37:03.739Z',mode:absolute,to:'2017-08-22T11:43:03.739Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T11:37:03.739Z',mode:absolute,to:'2017-08-22T11:43:03.739Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Not clear what the issue is

**Comment by rdmpage** [comment]
I think the issue is that there's no obvious way to go to GBIF and answer a pretty basic question, namely, "how many mammal species are found in China?".
