### ISSUE TITLE
Cropland data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3820]
**Cropland data**

Does the GBIF data contain cropland data?  Or is it simply wild/naturally occurring species that are recorded in the occurrence data?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/61f14738231aad3e4e648ec8b0145d6d:eeaa88acff2f91bbaddc4dc328237bde9456fe33a3c47e0c57856425ac61d2d6e37d364a3766385b10f022db510bd4f1a72b09a95381353a31c5888351ae9b12)
System: Safari 14.1.2 / Mac OS X 10.15.7
Referer: https://www.gbif.org/system-health
Window size: width 1204 - height 795
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-15T13:55:36.719Z',to:'2021-12-15T14:01:36.719Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-15T13:55:36.719Z',to:'2021-12-15T14:01:36.719Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

Although most of the data on GBIF is about wild/naturally occurring species, there are some records for cultivated/managed species.
These records aren’t necessarily easy to find though:
* One way is to use “Establishment means” filter and select “managed”. See for example, the records of “managed” Poaceae: https://www.gbif.org/occurrence/search?taxon_key=3073&establishment_means=MANAGED&advanced=1&occurrence_status=present. Not many data providers fill the establishment means field so the number of records you can get from this query is quiet limited.
* An alternative is to select the “living specimen” basis of record. It is often used for occurrences in botanical gardens or zoo and sometimes, cultivated fields. Here is a selection for living specimens of Poaceae: https://www.gbif.org/occurrence/search?basis_of_record=LIVING_SPECIMEN&taxon_key=3073&occurrence_status=present

You might also find records for crops that aren’t necessarily “managed” or “living specimen” but it doesn’t mean that they occurred naturally. It means that the information wasn’t put in a searchable field.
