### ISSUE TITLE
New validator - clicking on a validation report doesn't show me the full report

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3822]
**New validator - clicking on a validation report doesn&#39;t show me the full report**

I only see the top part of the report, not the detail.

<img width="1186" alt="Screenshot 2021-12-15 at 15 36 33" src="https://user-images.githubusercontent.com/7677271/146206145-d2eaf6ea-5c92-4a4b-855b-8d8979ec1ac8.png">

@muttcg

-----

User: [See in registry](https://www.gbif-uat.org/api/feedback/user/003dccb75019feb9bb19eccf79cf3df7:4e8c66ee28bd7b47927810ad549c171ddf3132db5ddce730451d4b12ef55456f08827d58817e1bef5c617c90aa7abbd9b9cb63f56943b74746ba5675f5d96824)
System: Safari 14.1.1 / Mac OS X 10.15.7
Referer: https://www.gbif-uat.org/tools/data-validator/2200dc1a-9bf1-439a-a644-7ffb65d859c5
Window size: width 1207 - height 796
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-15T14:31:22.448Z',to:'2021-12-15T14:37:22.448Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-15T14:31:22.448Z',to:'2021-12-15T14:37:22.448Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It looks ok now
