### ISSUE TITLE
Living Atlases

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#383]
**Living Atlases**

Hi,
In the map of ALA installations Norway is highlighted as having an ALA installation which I think is wrong. They have another system.
Regards,
Veronika

-----
fbitem-2685271de3ece2ea1bc629a115e92efe03e98182
Reported by: veronika.johansson@nrm.se
System: Firefox 54.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/programme/82953/living-atlases
Window size: width 1484 - height 783
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T12:38:39.176Z',mode:absolute,to:'2017-08-22T12:44:39.176Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-22T12:38:39.176Z',mode:absolute,to:'2017-08-22T12:44:39.176Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Map was produced by Katia Cezón of GBIF Spain ([link crediting the source](https://katia.carto.com/viz/92d56bd0-a0e1-11e6-a7e6-0e3ebc282e83/public_map) went missing but is restored now). @melecoq do you know why Norway would appear on the ALA network map?

Will ask the question on the non-Git circuit, too.

**Comment by melecoq** [comment]
It's not a map that represents countries with installation in production but countries with interest on this system. For instance, GBIF France is currently working on the GBIF Benin one but it's not live yet.

**Comment by kcopas** [comment]
Thanks, @melecoq ! I've adjusted the caption to capture this thought. Hope it addresses the concern of the moment, Veronika.

Meanwhile, I've also asked Katia and others working on the ALA collaboration whether we should show 1) installations and 2) interest, so further refinement *may* be coming.
