### ISSUE TITLE
Role of the contacts are showing differently in the GBIF Portal, from the IPT selection

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/portal-feedback#3832]
Some of the selected options in the IPT for the role of the contacts (**Associated Parties** section) are displayed differently in the GBIF Portal. See the example:

Roles –selected in the IPT (**"Reviewer"** in both cases):
<img width="640" alt="Screen Shot 2021-12-20 at 11 48 29 AM" src="https://user-images.githubusercontent.com/61566113/146809650-a4668b8a-c6fc-46ad-bb5e-15e2d7abb09b.png">

Roles –displayed in the GBIF Portal (**"Administrative point of contact"** in both cases)
<img width="938" alt="Screen Shot 2021-12-20 at 12 45 22 PM" src="https://user-images.githubusercontent.com/61566113/146809998-f9355aa8-8746-4287-8068-b1e1ab17c038.png">

**Comment by MortenHofft** [comment]
Thank you
Could you provide a link as well? Just to ease debugging.

At this point my guess is that the role isn't mapped. At least I do not see it here:
https://api.gbif.org/v1/enumeration/basic/ContactType

**Comment by leo-buitrago** [comment]
Hi @MortenHofft, see the specific example
Dataset in the GBIF IPT: https://ipt.gbif.org/resource?r=vz_redlist_endemic_trees
Dataset in GBIF.org:  https://doi.org/10.21373/jp88kf

**Comment by MortenHofft** [comment]
Thank you. The DOI doesn't work for me, but I assume it is [this dataset](https://www.gbif.org/dataset/35f444fa-b3bb-4a1d-bf56-93fbc81f28d5)

I see that the EML lists e.g. `Ariany García` as a `reviewer`. 
But [in the API](https://api.gbif.org/v1/dataset/35f444fa-b3bb-4a1d-bf56-93fbc81f28d5) she has the role `ADMINISTRATIVE_POINT_OF_CONTACT`.

(it is the same for the [UAT dataset](https://www.gbif-uat.org/dataset/3461b8a0-0bbe-40a5-9a6f-c4f3f020ff42))

So I will label this as an API/interpretation issue.

**Comment by mike-podolskiy90** [comment]
related https://github.com/gbif/ipt/issues/1621

**Comment by mike-podolskiy90** [comment]
Registry interprets all unknown contacts as `ADMINISTRATIVE_POINT_OF_CONTACT` roles.
I added new role REVIEWER to the gbif-api

**Comment by MortenHofft** [comment]
In that case the website need a new translation
