### ISSUE TITLE
This resource have 47.150 occurrence associated, but do not show in GBIF. We re-publish the resource but the issue remains.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3833]
**This resource have 47.150 occurrence associated, but do not show in GBIF. We re-publish the resource but the issue remains.**

This resource have 47.150 occurrence associated, but do not show in GBIF. We re-publish the resource but the issue remains.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2a4996e68f9f51f5f0f1d2a41aa3369b:f115d3cf9067e210518c750d588427d93a2f6e190d363c09b2d655076dd82cc651cee63de7816c6042a05f98a3f8808a26f289f585560e1e092a1b0448465b8c5304d5dc23653c4da9c8990afc0bbff7)
System: Firefox 95.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/01598aee-87a8-4a95-83ec-263469faaf4d
Window size: width 1760 - height 875
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-23T22:12:59.140Z',to:'2021-12-23T22:18:59.140Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-23T22:12:59.140Z',to:'2021-12-23T22:18:59.140Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@RicardoOrtizG I don't know what happened but I triggered the dataset reingestion and the number of records seems ok now. I will close the issue but let us know if it should be reopened.
