### ISSUE TITLE
Registry biological collections

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3834]
**Registry biological collections**

I want to advise the herbarium at Reno on how to become a data publisher but under the umbrella of university of Nevada, Reno.  I have tried search BioColl registry but that is not what I am looking for. Help please.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0a6660f450d7109711fff4554c332ca8:916b2b118a7f8247f433e460d21cb907753838c78e5eaa322d15506d4476d31d27ee40d640dd08c37cba3d2ba888ad048eebdc5ae4220f799266523d9a9bc253)
System: Chrome 96.0.4664 / Windows 10.0.0
Referer: https://www.gbif.org/search?q=collections%20registry
Window size: width 1097 - height 535
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-27T18:14:32.800Z',to:'2021-12-27T18:20:32.800Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-27T18:14:32.800Z',to:'2021-12-27T18:20:32.800Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Contacted by email.
The University of Nevada, Reno is registered as a publisher here: https://www.gbif.org/publisher/470365d0-812d-11de-86fe-b8a03c50a862
