### ISSUE TITLE
protected species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3835]
**protected species**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/346ad726c69fd96b8f6a6c508edb0d87:3dbcce6635c3173f09c5b40a9f6f94b0e193d4f26d071aa9aacfd12c0c973ae524eb3e8806b23ec1d09600bd06e5bbed55ec199af89b11c556193bd0cd206e66)
System: Chrome 96.0.4664 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 912
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-28T18:26:56.565Z',to:'2021-12-28T18:32:56.565Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-28T18:26:56.565Z',to:'2021-12-28T18:32:56.565Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Not enough information
