### ISSUE TITLE
How do i download species records that have had there locations generalized?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3836]
**How do i download species records that have had there locations generalized?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/cb939593b2ee193f889377000cbc9048:8298d3daaed9bf89da7ed550e0a8097ecb86e7af5a5326e89bd0a97e5bda8e1959b974370274fe74058ced314774f18c5918443117e4da115da626860c052ddd)
System: Chrome 96.0.4664 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 912
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-28T18:27:36.423Z',to:'2021-12-28T18:33:36.423Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-28T18:27:36.423Z',to:'2021-12-28T18:33:36.423Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

GBIF doesn’t obscure coordinates, our platform displays what the data providers choose to share. This means that if you would like to access the data before their location has been generalized, you need to contact the original data providers.
The data providers’ contact information should be available on the dataset pages, for example: https://www.gbif.org/dataset/832b8188-f762-11e1-a439-00145eb45e9a.
Note that iNaturalist has a specific system where you need to ask permission to individual citizen scientists to see their observation’s original coordinates. I suggest to check iNaturalist’s website for more information: https://www.inaturalist.org/pages/help#geoprivacy
