### ISSUE TITLE
New validator doesn't show the same as pipeline

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3841]
**New validator doesn&#39;t show the same as pipeline**

Both old (https://www.gbif.org/tools/data-validator/1638898791811) and new (https://www.gbif-uat.org/tools/data-validator/e6d52865-7962-419b-b154-c795f766ee43) validator say this dataset cannot be ingested. However, the dataset and its images seem to have been ingested successfully here: https://www.gbif.org/dataset/cb0ab16c-7589-4a44-80d0-30bae8c952ef

-----

User: [See in registry](https://www.gbif-uat.org/api/feedback/user/bdd94a099d33aaa1f42d0db229b79968:1d8d16ecd326cb4837207e879e7b634c676abc1e7c7d70ceccf9d3e2ae2ffc981782adab2200f624b70fd28829c8d1573cd8e7c0c5d32862093274b36b6d3e82)
System: Safari 14.1.1 / Mac OS X 10.15.7
Referer: https://www.gbif-uat.org/tools/data-validator/e6d52865-7962-419b-b154-c795f766ee43
Window size: width 1207 - height 796
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-03T08:40:37.272Z',to:'2022-01-03T08:46:37.272Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-03T08:40:37.272Z',to:'2022-01-03T08:46:37.272Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ckotwn** [comment]
The consistency between the pipeline and the validator is very important in guiding supporters' actions with the publishers. Now I am not sure whether it makes sense to proceed with the publisher to fix those issues. I'll first look into the data and see if the validator report is correct.

**Comment by muttcg** [comment]
@ckotwn Thanks. New validator is part of pipelines project and it is uses the same workflow plus some additional checks and metrics aggregations. 
The UAT validator had technical issue, I have restarted it, please try again and let me know about possible issues

**Comment by ManonGros** [comment]
Thanks @muttcg I checked again and this time I get an "indexing failed": https://www.gbif-uat.org/tools/data-validator/37838e3a-3d47-4800-bf69-ed515d78c207

**Comment by ckotwn** [comment]
@muttcg does the code base https://github.com/gbif/gbif-data-validator still relevant, then?

**Comment by ckotwn** [comment]
> Thanks @muttcg I checked again and this time I get an "indexing failed": https://www.gbif-uat.org/tools/data-validator/37838e3a-3d47-4800-bf69-ed515d78c207

@ManonGros : Does this link mean to run the validation again? (I see the URL is not ending with a 14-digit number). I get "The system is currently not able to process your request. Try to refresh the page and please report the issue if it continues."

**Comment by muttcg** [comment]
> @muttcg does the code base https://github.com/gbif/gbif-data-validator still relevant, then?

No, new version is here https://github.com/gbif/pipelines/tree/dev/gbif/validator
It hasn't been released yet, but will be released and replace old validator soon

Now it works https://www.gbif-uat.org/tools/data-validator/5f5fc986-e610-458e-9fd9-04874500186e

**Comment by ckotwn** [comment]
https://www.gbif-uat.org/tools/data-validator/5f5fc986-e610-458e-9fd9-04874500186e this link still brings me to "The system is currently not able to process your request. Try to refresh the page and please report the issue if it continues."
<img width="1367" alt="Screenshot 2022-01-03 at 18 17 50" src="https://user-images.githubusercontent.com/637631/147919745-cb767402-5d10-411a-91d3-4136300d336e.png">

**Comment by muttcg** [comment]
@ckotwn You have to be logged to the portal and be the owner/admin for the validation, just try to validate your own archive

**Comment by ckotwn** [comment]
Throw in the original DwC-A and the validator looks like hanging at step 2:
https://www.gbif-uat.org/tools/data-validator/7c70d348-b141-4889-8ec4-acb1a1b6655c

<img width="1478" alt="Screenshot 2022-01-03 at 18 20 36" src="https://user-images.githubusercontent.com/637631/147919994-ee767ba2-6abc-437c-b637-eb124cf68995.png">

**Comment by ckotwn** [comment]
> @ckotwn You have to be logged to the portal and be the owner/admin for the validation, just try to validate your own archive

This would prevent from sending a link to others and see the same validation result, right? I hope it's not the case once it's released.

**Comment by muttcg** [comment]
@ckotwn Good point, I will check your case before releasing the validator
