### ISSUE TITLE
add dates for Paloma

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3846]
**add dates for Paloma**

PLease add after Paloma's full name (see examples for Sylvie and Marianne)

Chair: November 2021- June 2022

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/58d669280cb1fe2d72f566e959ccce6e:3d30a6de6187d1fca6f905fef20234ad6d6bfb2f18c3fc6477691df958a59e3c866c8b5732fb61f9915b9408b2468ea6fa751329dc9a24054b9f4404caac53cc)
System: Chrome 96.0.4664 / Windows 10.0.0
Referer: https://www.gbif.org/news/j6dXMQP9an4EnREeTT3oi/task-group-to-enhance-gbif-enabled-research-on-species-linked-to-human-diseases
Window size: width 1745 - height 970
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-04T17:18:38.520Z',to:'2022-01-04T17:24:38.520Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-04T17:18:38.520Z',to:'2022-01-04T17:24:38.520Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@dnoesgaard

**Comment by dnoesgaard** [comment]
Done.
