### ISSUE TITLE
Unranked species in Edge

### ISSUE THREAD

**Issue by eduardolacx** [gbif/portal-feedback#3847]
I’m having issues using the Microsoft Edge’s browser; I search an species and it appears unranked and does not allow me to see the information of the species, map, etc. But if I use Google chrome, for example, it works; though, I don’t want to change my browser, because I have all my information in Microsoft Edge. Please help me.
you can see image of the problem here: https://user-images.githubusercontent.com/97155282/148182843-8db11d48-b027-4e32-8701-ca9faeab6d5d.png

**Comment by MortenHofft** [comment]
Thank you for reporting this!

I'm unable to reproduce this in Edge unfortunately (I've tested version 96 (latest) and on Windows and macOS)
Could you please try again and if it still doesn't work then provide:

* Exact version of Edge
* What OS you are using
* Check that you do not have any plugins in place that is the cause of this. You can probably do so by using InPrivate mode (Ctrl + Shift + N) or (cmd + shift + n on a Mac).
* And ideally tell me if you see any errors in the browser log (you can open it with tools => developer => Javascript console). Refresh the page once you have open the console.

Thank you for your help

**Comment by eduardolacx** [comment]
eduardola
6m
The Exact version of Microsoft is this (Microsoft Edge
Version 96.0.1054.62 (Official build) (64-bit))
 I’m using Windows 10 Home
Version 20H2
Installed on ‎31/‎12/‎21
OS build 19042.1415
Experience Windows Feature Experience Pack 120.2212.3920.0
and the issue appears in whichever link of species I want to get in
For example:
Panthera onca (Linnaeus, 1758) (gbif.org)
I've tryied to use the incognito mode and it does not fix the issue.
![image](https://user-images.githubusercontent.com/97155282/148249029-d0e13f23-bc85-43c9-a532-8fe2d3b76775.png)

**Comment by eduardolacx** [comment]
I managed to solve it  :D
I only restared the settings of Microsoft Edge

**Comment by MortenHofft** [comment]
That is a relief. It sounded like it would be painful to debug. Thanks
