### ISSUE TITLE
Taxon record scientific name incorrectly interpreted (content of the parenthesis are removed)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3848]
**Taxon record scientific name incorrectly interpreted (content of the parenthesis are removed)**

Relating to this other issue: https://github.com/gbif/backbone-feedback/issues/302

The original name provided is "Sabethes (Peytonulus) shannoni (Lane & Cerqueira 1942)" but the name shown on the species page is "Sabethes shannoni (Lane & Cerqueira, 1942)".
`(Peytonulus)` seems to have been removed.
Anything that we could do to avoid that? @thomasstjerne @mdoering

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/3834c8c72912428be3903d556e8dd0ec:9eb6041edc3c13ac12bb2ff3df0cab99e19efad1c851ea916957ad045e8f2e280fb68e6bc389a04bc77b0ea67eec2fc3f595332f3568ba6c5ee9bde54680a873)
System: Safari 14.1.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/191654844/verbatim
Window size: width 1207 - height 796
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-05T09:44:23.833Z',to:'2022-01-05T09:50:23.833Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-05T09:44:23.833Z',to:'2022-01-05T09:50:23.833Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
The reason it is not displayed on the portal is that the subgenus in parantheses is missng in the `canonicalName` field.
````
"scientificName": "Sabethes (Peytonulus) shannoni (Lane & Cerqueira 1942)",
"canonicalName": "Sabethes shannoni",
"authorship": " (Lane & Cerqueira, 1942)",
````
https://api.gbif.org/v1/species/191654844

**Comment by ManonGros** [comment]
Thanks for checking @thomasstjerne. This is really odd, the canonical name displayed in the UI contains the genus. How can it be different in the API?

<img width="830" alt="Screenshot 2022-01-05 at 13 26 11" src="https://user-images.githubusercontent.com/7677271/148217504-a4896c92-da2d-4e33-b94c-53400fa9bdf8.png">

**Comment by ManonGros** [comment]
I suppose this probably has to do with the interpretation as the API shows the correct values for the verbatim data: https://api.gbif.org/v1/species/191654844/verbatim

**Comment by mdoering** [comment]
The subgenus within a name is often problematic. In this case it is not reflected by the actual classification which does not use a subgenus at all.

The name appears to be parsable and the infraGeneric name is set correctly:
http://api.gbif.org/v1/parser/name?name=Sabethes%20(Peytonulus)%20shannoni%20(Lane%20%26%20Cerqueira%201942)

The canonical name in GBIF removes the infrageneric part. This is done on purpose. But the infrageneric name seems to be missing in the API, so the portal is unable to include and render it. Sth that will be fixed when we move the COL CLB which builds the label in the API...
