### ISSUE TITLE
On gbif.org/tool/81747/rgbif (page about rgbif package), the link to the rgibf tutorial below the bulleted list is broken. I believe the new URL should be: https://mran.microsoft.com/snapshot/2014-11-06/web/packages/rgbif/vignettes/rgbif_vignette_oldapi.html

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3849]
**On gbif.org/tool/81747/rgbif (page about rgbif package), the link to the rgibf tutorial below the bulleted list is broken. I believe the new URL should be: `https://mran.microsoft.com/snapshot/2014-11-06/web/packages/rgbif/vignettes/rgbif_vignette_oldapi.html`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/16b721ac189a6a6401a0ae9ccaabfada:ea368a628518db299ce39542df611ceedb9a2cb9cf9c5962900b70457b3da93c7cf93ac03c2084847f2aaa00648847cce27a5ea1b194256d53490a3fd17887b6)
System: Chrome 96.0.4664 / Windows 10.0.0
Referer: https://www.gbif.org/tool/81747/rgbif
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-06T16:09:54.152Z',to:'2022-01-06T16:15:54.152Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-06T16:09:54.152Z',to:'2022-01-06T16:15:54.152Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by themerekat** [comment]
Actually, link might be: https://docs.ropensci.org/rgbif/

**Comment by jhnwllr** [comment]
Tutorial should probably be re-written anyway as it is a few years old now...

**Comment by ManonGros** [comment]
I updated the link on the page.
