### ISSUE TITLE
redirect needed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#385]
**redirect needed**

/newsroom/uses

->

/resource/search?contentType=dataUse

-----
fbitem-2c07af25a9ef9769c735e0c6a09b0ed86c946d0c
Reported by: @dnoesgaard
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/newsroom/uses
Window size: width 1775 - height 956
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-23T09:46:22.057Z',mode:absolute,to:'2017-08-23T09:52:22.057Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-23T09:46:22.057Z',mode:absolute,to:'2017-08-23T09:52:22.057Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/gbif-configuration/blob/master/portal16/common/redirects.json#L2 [building](https://builds.gbif.org/job/portal16/1291/)
