### ISSUE TITLE
Can I search for specific data quality flags using the API?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3850]
**Can I search for specific data quality flags using the API?**

I see that I can search for whether occurrences have a geospatial issue (https://www.gbif.org/developer/occurrence), but it's not clear whether I can use the API (or rgbif) to obtain a list of all occurrences from a specific collection that have a specific data quality flag. Thanks!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/865a7385c9cbaa13f62a016cf03dd94a:32d0b517835e70887e463b16956a584692874668bbeedac0b5515281cdef8d6214a362fbdf90f118d6f6dc07a84477e8af4d9448a3ec7262460ad6c988c03a7d)
System: Chrome 96.0.4664 / Windows 10.0.0
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-06T16:15:57.048Z',to:'2022-01-06T16:21:57.048Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-06T16:15:57.048Z',to:'2022-01-06T16:21:57.048Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by AbbyBenson** [comment]
@themerekat did I get you all sorted on this question? Should this ticket be closed?

**Comment by themerekat** [comment]
Yes it can be closed, thanks! @albenson-usgs
