### ISSUE TITLE
Ancylis habeleri

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3853]
**Ancylis habeleri**

https://www.inaturalist.org/observations?taxon_id=1080421

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/27cb5808175e483304242831e8e9f100:5acbc209692f69a3933534b41cc9dc2635b3748c0cfa52e60c3879fccd2a1dc378c35c144a154761ce48569f6234c68793aeaec75187971dc4f04a6ea7e5b7cd)
System: Yandex Browser 21.11.4 / Windows 10.0.0
Referer: https://www.gbif.org/ru/species/9021151
Window size: width 1280 - height 884
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-08T11:49:36.632Z',to:'2022-01-08T11:55:36.632Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-08T11:49:36.632Z',to:'2022-01-08T11:55:36.632Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
I think the user is wondering why these records from iNaturalist are not in GBIF. 
https://www.gbif.org/occurrence/search?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7&taxon_key=9021151

**Comment by ManonGros** [comment]
I have contacted this user previously for similar issues:
https://github.com/gbif/portal-feedback/issues/3780
https://github.com/gbif/portal-feedback/issues/3770
https://github.com/gbif/portal-feedback/issues/3769
https://github.com/gbif/portal-feedback/issues/3768
https://github.com/gbif/portal-feedback/issues/3767

I explained how the iNaturalist records were shared on GBIF. I think it is ok to close this issue.
