### ISSUE TITLE
Could derived dataset pages show total number of records as well as datasets?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3860]
**Could derived dataset pages show total number of records as well as datasets?**

It's great to see derived dataset DOIs starting to appear in literature citations. At the moment the page heading shows 'Records from xx datasets in derived dataset'. Would it be possible also to give the number of occurrence records involved, as is currently done with download pages? This would help to give an idea of the scale of the dataset used in the citation. Also the citation style shown on these pages seems a little odd. I would favour 'GBIF.org derived dataset' rather than 'Derived dataset GBIF.org'

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/eecacf6d7ffef80856c80c728f690114:5e277ebff267f09ef4a22093ef79c90da77b9feb983e099aca06a931c62ac77ef8100918fd607a970fc3e085c1a622e491829b8bce73efc658c682821280e9fc)
System: Chrome 96.0.4664 / Mac OS X 10.15.7
Referer: https://www.gbif.org/derivedDataset/10.15468/dd.df4evh
Window size: width 2243 - height 1237
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-13T08:11:57.023Z',to:'2022-01-13T08:17:57.023Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-13T08:11:57.023Z',to:'2022-01-13T08:17:57.023Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
**Record count**
The UI look for a field called `totalRecords`, if it is present then it will show occurrence counts. I do not know how that field is populated in the API. I would think it could be calculated by summing up the dataset record counts. I'm unable to find an example with the value populated. Is this field ever populated or did I just foresee the need and implemented something hoping that it would come?

**Citation format**
This value comes from the API.

I think you might be the best to answer/correct this @mike-podolskiy90

**Comment by mike-podolskiy90** [comment]
there is no such option for derived datasets, unfortunately

**Comment by timhirsch** [comment]
OK - just thought I would check!

**Comment by MortenHofft** [comment]
Should we reopen this as a feature request. It seems like a simple thing to sum the counts of the datasets? Or is there more to this than I see @mike-podolskiy90 ?
