### ISSUE TITLE
Find publishers from a level2 admin region

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3861]
**Find publishers from a level2 admin region**

I would like to find who is publishing to GBIF from Utah and Nevada (USA) so that I can send an email to those not doing so without adding to the inboxes of those who are doing so.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/01e8da51da146d229b502e5c5ffd0fab:34696526d2e4fd97d2efd3d6617b3474ca97238f64a28b2cba41989aaaebfa6ebf74d642a80cebb7fe114664c7b928819fc01d1953fdbbcb4bb867006d0536fb)
System: Chrome 97.0.4692 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/search?country=US
Window size: width 1035 - height 548
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-13T16:19:07.791Z',to:'2022-01-13T16:25:07.791Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-13T16:19:07.791Z',to:'2022-01-13T16:25:07.791Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

We don’t really have a way to filter publishing organizations by Province or State. I suggest to try the free text search and review the result manually. For example, here is what you get when looking for the word “Nevada” in the free text field: https://www.gbif.org/publisher/search?q=Nevada&country=US.
