### ISSUE TITLE
Month & Year occurrence search

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3862]
**Month &amp; Year occurrence search**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/def215fdc5aafb120a09a635983af399:55842815aadbb79b36223d7d11774165fda699e2796cdca32bc9191a413ceaf2d01b4b931d262a13ce6c21a08cf4e2886585b52edfe53c3300826a6bbf4b5707)
System: Chrome 97.0.4692 / Windows 10.0.0
Referer: https://www.gbif.org/system-health
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-14T15:24:48.548Z',to:'2022-01-14T15:30:48.548Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-14T15:24:48.548Z',to:'2022-01-14T15:30:48.548Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jpupko10** [comment]
sorry this can get deleted, I was trying to search, not open an issue!

**Comment by MortenHofft** [comment]
Did you find what you were looking for? If not then feel free to create an issue - you now know how to.
