### ISSUE TITLE
wrong subspecies

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#3863]
in this case there is the name wrong and should not include the subsp. racer.

https://www.gbif.org/species/191979801

![image](https://user-images.githubusercontent.com/4609956/149748205-9bfd3768-90e8-4848-bfa9-0c08c29ea504.png)

It seems that the source is ok https://treatment.plazi.org/id/7759EE8D12FF5CB49412834543DADB7B

**Comment by ManonGros** [comment]
The name appears correctly now. I am closing the issue. Let me know if I missed anything.
