### ISSUE TITLE
Delete erroneous ocurrences from a checklist dataset

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#3864]
On December 16, the resource "[Biodiversidad de Huertas Urbanas en el Valle de Sibundoy, Putumayo, Colombia](https://www.gbif.org/dataset/9197e55c-462d-460a-8177-6a6ef2afa0f5)" was mistakenly modified and 131 occurrences were added that do not correspond to this checklist dataset.

We made the update in the [IPT of SiB-Colombia](https://ipt.biodiversidad.co/sib/resource?r=itp-1), however in GBIF still shows the 115 records corresponding to the checklist plus the 131 records added by mistake. 
Therefore, we should like to ask for your help eliminating the 131 erroneous occurrences.

Thanks in advance for your help,

**Comment by ManonGros** [comment]
Thanks @EstebanMH-SiB, our system has a safeguard that prevents the deletion of occurrences when the number of occurrences drops to zero (as this is often the result of accidental deletions).
The occurrences have been removed now.
