### ISSUE TITLE
Two one letter diffrence species names  have both taxonomic status accepted with the dataset gbif backbone although probably one is a misspelling

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#387]
**Two one letter diffrence species names have both taxonomic status accepted with the dataset gbif backbone although probably one is a misspelling**

If i type on the browser 
http://api.gbif.org/v1/species/match?name=Aegithalus caudatus
I get  gbif:7629107 from "d7dddbf4-2cf0-4f39-9b2a-bb099caae36c"
if I type on the browser:
http://api.gbif.org/v1/species/match?name=Aegithalos caudatus 
I get another thing ("gbif:2495000") from "d7dddbf4-2cf0-4f39-9b2a-bb099caae36c"

Both results are taxonomic status accepted so they seem to belong to different species and both are correct, while this is the same species of bird, so one is correct and the other is synonymous as decided by GBIF backbone team 
When I ask to match on NCBI backbone
http://api.gbif.org/v1/species?name=Aegithalus%20caudatus&datasetKey=fab88965-e69d-4491-a04d-e3198b626e52
I get nothing,  only Aegithalos match a record and no trace of Aegithalus. 
This is really annoying. I was using "match" to correct misspelling of a species list and then the exact search specifying NCBI data set to get the version accepted by NCBI, so  to later get from NCBI the taxonID. This was not possible for this species given the lack of synonymous link between the two spelling form Aegithalus/Aegithalos  
 
When i "Aegithalos caudatus", "Aegithalus caudatus"

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
Reported by: saverio.vicario@cnr.it
System: Firefox 55.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/
Window size: width 1660 - height 935
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-24T07:47:46.986Z',mode:absolute,to:'2017-08-24T07:53:46.986Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-24T07:47:46.986Z',mode:absolute,to:'2017-08-24T07:53:46.986Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
The genus Aegithalus and its species A. caudatus is created in the backbone because we have a subspecies taiti given as a type specimen in occurrences: https://www.gbif.org/species/126968698

This is unfortunate. We will add this spelling mistake as a synonym to the manual patch list so it gets fixed in the next backbone version.

**Comment by mdoering** [comment]
https://github.com/gbif/backbone-patch/commit/dded70563275090e1986b61241b9b42a7af99968
