### ISSUE TITLE
Location error on occurrence.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3870]
**Location error on occurrence.**

http://n2t.net/ark:/65665/321200275-64af-414c-8c01-a8921707fc48

Record is for Kosrae, coordinates point to Palmyra Atoll.

Switch longitude from -162.975 to 162.975

Smithsonian notified.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bdb5273447693b6641df4103d2d59352:eb038d2ceb9c7af4ff717b29b0d0b3c81d62b670f713a74e2bdc1d821ed31dba2aa8b34559605f8a6c72f85b522c3f9f972ef78ab8d6e3c5bff4b23aa2007a8c)
System: Chrome 96.0.4664 / Mac OS X 10.15.7
Referer: https://www.gbif.org/faq
Window size: width 1563 - height 959
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-19T17:51:36.561Z',to:'2022-01-19T17:57:36.561Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-19T17:51:36.561Z',to:'2022-01-19T17:57:36.561Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Record concerned: https://www.gbif.org/occurrence/3391247309
[NMNH Material Samples (USNM)](https://www.gbif.org/dataset/26098c25-8f7f-4c71-97ac-1d3db181c65e)
[National Museum of Natural History, Smithsonian Institution](https://www.gbif.org/publisher/bc092ff0-02e4-11dc-991f-b8a03c50a862)
The coordinates correspond to centroids.

**Comment by ManonGros** [comment]
@gamblebnmnh
This issue was already reported to the Smithsonian but I am tagging you so you can keep an eye on the issue.

**Comment by gamblebnmnh** [comment]
Thank you @ManonGros.  Do you happen to know what contact was used to report the issue to the Smithsonian originally?  I have forwarded to the Botany person who created the record in our CIS.  Hopefully will be corrected next load.

**Comment by ManonGros** [comment]
@gamblebnmnh The user is the person who said they have originally reported the issue on GitHub. I don’t know which email address they used to report the issue to the NMNH but I can contact them to ask, would it be helpful?

**Comment by gamblebnmnh** [comment]
@ManonGros if it wouldn't be too much trouble that would be helpful.  I want to know if folks are just emailing Tom Orrell as he is listed as first contact in our data sets.  Tom is sooooooooo busy I'm sure this stuff just falls out of his email.  InformaticsHelp is our second contact and that would go to me and others in my office and would have a higher chance of being looked at.  Thanks so much!!

**Comment by ManonGros** [comment]
Hi @gamblebnmnh I contacted the user and they told me that they don't exactly remember but that they most likely used the feedback system on the NMNH portal.

**Comment by gamblebnmnh** [comment]
Thanks, record has been modified and will be corrected next monthly IPT update.

**Comment by jhnwllr** [comment]
it's fixed now
