### ISSUE TITLE
Please can you look at these two species:

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3873]
**Please can you look at these two species:**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f77c4ccf2b4f1e5a570c1e0f261f66f3:34ebec3641d03b98108a6b4914c1a127ac55e71bc98e134af5786033283cf78b6214100f73c12667dfc21771e78bb1faad48b7ce8e1b36015b17a340c073cf10)
System: Chrome 97.0.4692 / Windows 10.0.0
Referer: https://www.gbif.org/species/1938038
Window size: width 1680 - height 917
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-20T15:53:49.985Z',to:'2022-01-20T15:59:49.985Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-20T15:53:49.985Z',to:'2022-01-20T15:59:49.985Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I contacted the user by email to ask for more information.

**Comment by ManonGros** [comment]
The user answered and explained that he figured out what he needed.
