### ISSUE TITLE
Highlight the dataset-first approach

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3879]
**Highlight the dataset-first approach**

Transferring the request from the task group to move a sentence within the page.

"We recommend that authors start by preparing the dataset and publishing it through GBIF.org before turning to manuscript writing and editing.” and  linke to GBIF Quick guide to publishing to a more visible  position within the page.

The group recommended that this imporant thing is said earlier and is more clear with a "as do this first" or "start here" effect.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/0bd78272724c830604a15210939c6076:995c39fe0b9ef24ca9ba4842e35e530ac8f84a31f170cd542293b8d83660ccaa1b31f536c8d18781afaca4b69e241b197c361331d436339e46e4548edc782b34)
System: Chrome 97.0.4692 / Windows 10.0.0
Referer: https://www.gbif.org/news/u076BiFDma9AZqOyf7rkk/call-for-data-papers-describing-datasets-on-vectors-of-human-diseases
Window size: width 1365 - height 631
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-24T16:16:36.378Z',to:'2022-01-24T16:22:36.378Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-24T16:16:36.378Z',to:'2022-01-24T16:22:36.378Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
@dnoesgaard @kcopas sorry it comes so close to the webinar, I agree this should be stressed more, especially with the audience of beginners to the format

**Comment by dnoesgaard** [comment]
Moved the sentence to the top of the instructions and highlighted using a blockquote, i.e.,

> We recommend that authors start by [preparing the dataset and publishing it](/publishing-data) through GBIF.org before turning to manuscript writing and editing.
