### ISSUE TITLE
Coordinate Accuracy of Observations with no Country/State Codes

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3880]
**Coordinate Accuracy of Observations with no Country/State Codes**

Hello, 

I've noticed that certain coastal plant species include a large number of occurrences with coordinates, but not country/state info. These occurrence coordinates are usually over the ocean, sometimes 5-10 miles away from land. I'm assuming this was an error by the observer logging coordinates? I've found some species with over 50% of occurrences over the ocean.

I'm working on creating distribution maps with climate and elevation data and hoping that this issue isn't common with inland species where it's more difficult to filter out erroneous occurrences.

Thank you,
Sam

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7658b1c8634c84b52bfa9ab2f8c976aa:1f6715ec2e5c5eee444b87ce1c253fcc284a56b0665b86bef2d06f225583e1417a5c133b06b8f30e7a663337175401ebab85df8e20dead20b1cf6ed969c285a5)
System: Chrome 97.0.4692 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 2844 - height 1432
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-24T20:26:05.236Z',to:'2022-01-24T20:32:05.236Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-24T20:26:05.236Z',to:'2022-01-24T20:32:05.236Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.

> We have a blogpost on post processing GBIF-mediated data: https://data-blog.gbif.org/post/gbif-filtering-guide/. I think it might be helpful for identifying so problematic records (both inland and oceanic records).
