### ISSUE TITLE
How can I download the citations for my data set?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3881]
**How can I download the citations for my data set?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/051e8fd7012323886687c855899b708b:d35e82305ddeaf552554b3c3c8d772befa6576c67a4014300bf611fae68f17579e856fe69aea24c63a113551dd2fa8d32f6af32d9ec7ab3b00a0fbe43bd613d3)
System: Chrome 97.0.4692 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?q=faq
Window size: width 1920 - height 880
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-24T20:54:04.039Z',to:'2022-01-24T21:00:04.039Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-24T20:54:04.039Z',to:'2022-01-24T21:00:04.039Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

Unfortunately, we don’t have any button to download dataset citations in the web interface. However, you can use [our literature API](https://www.gbif.org/developer/literature) to access the information. This API will allow you to query the citations for a given dataset and will send you back a JSON-formatted response.
For example, here are the citations for the eBird dataset: https://api.gbif.org/v1/literature/search?gbifDatasetKey=4fa7b334-ce0d-4e88-aaae-2e0c138d049e
You can replace the value for the gbifDatasetKey by your own dataset key, which you can find in your dataset URL (see the example for the eBird URL: https://www.gbif.org/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e).
