### ISSUE TITLE
A question about the classification system

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3883]
**A question about the classification system**

Hello, I have downloaded the data of a genus of Rhododendron here..It contains family / genus / species information. I would like to ask whether GBIF's data follows APG III classification system or APG IV classification system? Because I want to use this data to build an evolutionary tree later, I need to make this clear first, so as to consider whether to use plantlist package for query (plantlist package uses apgiii classification system). I urgently hope you can answer this question for me. Thank you!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a74bb21abb6ecea27d49b057fa3c146d:752077a015841b223308c7ae1435e77615bd471cf6d7d28c733613de28262258cbd8e75a32dc17ed2c7b9c304e43cb4176669efc8cb4ed058a17bc6e5bc03194)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/zh/data-quality-requirements
Window size: width 1318 - height 635
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-25T15:20:49.012Z',to:'2022-01-25T15:26:49.012Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-25T15:20:49.012Z',to:'2022-01-25T15:26:49.012Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@ckotwn

**Comment by mdoering** [comment]
As far as I know World Plants still uses APG III, is that correct @yroskov?

**Comment by yroskov** [comment]
World Plants follows own classification which is sometimes ahead of APG IV. However, the Catalogue of Life based on Angiosperm Phylogeny Website powered by the Missouri Botaniocal Garden (http://www.mobot.org/MOBOT/research/APweb/).

**Comment by mdoering** [comment]
Please note that the algorithm building up the backbone starts out with the Catalogue of Life checklist which in turn is based on world plants. But we then add in more families that might not be in any of the APG classifications. See https://www.gbif.org/species/search?rank=FAMILY&dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&constituent_key=0938172b-2086-439c-a1dd-c21cb0109ed5&constituent_key=c33ce2f2-c3cc-43a5-a380-fe4526d63650&constituent_key=aacd816d-662c-49d2-ad1a-97e66e2a2908&constituent_key=a43ec6d8-7b8a-4868-ad74-56b824c75698&constituent_key=f382f0ce-323a-4091-bb9f-add557f3a9a2&constituent_key=bae5856f-da10-4333-90a0-5a2135361b30&constituent_key=de8934f4-a136-481c-a87a-b0b202b80a31&highertaxon_key=220&status=ACCEPTED&status=DOUBTFUL&advanced=1

**Comment by mdoering** [comment]
@yroskov what about [Styracaceae](https://www.gbif.org/species/2507) which is recognised by APGIV but is not sourced to COL? Ah, I see that COL has an odd authorship: [Styracaceae DC. & Spreng. [transl. Jameson]](https://www.catalogueoflife.org/data/taxon/GST) Maybe thats the reason. Any chance to remove the brackets?

**Comment by yroskov** [comment]
The Catalogue of Life flowering plant classification for families and orders is based on the Angiosperm Phylogeny Website. Global species checklists from World Checklist of Selected Plant Families and from World Plants databases attached on family level.

**Comment by yroskov** [comment]
CoL consistent with Angiosperm Phylogeny Website: Styracaceae DC. & Spreng. http://www.mobot.org/MOBOT/research/APweb/
I do not see a reason to alter WP spelling of the authorstring in the CoL. As less alterations we add on our side, as more transparent are relations between data in the CoL and in the source.

**Comment by mdoering** [comment]
As you can see having odd information in brackets can break software like the GBIF bacbone build. `[transl. Jameson]` should not be in the authorship. @dhobern any opinion? I would think COL should be more strict in properlynaming at least higher taxa as a start.

**Comment by yroskov** [comment]
I would suggest that software should be accurate enough to eat original data. As I said many times, I am not comfortable with clb software where it dramatically changing original authorstrings.

**Comment by CecSve** [comment]
I am closing this @mdoering - let me know if it should be reopened.
