### ISSUE TITLE
slides

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3884]
**slides**

please add PDF or link to Scott's slides, we have his permission https://www.slideshare.net/GigaScience/scott-edmunds-preparing-a-data-paper-for-gigabyte

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/96b323f14607691790e5844c2db96b43:046a85f7e292ec9387df1a108f55019022a3753cfcbb07910f254e30abe205430d3b1a975885646b29b2be5a5ec911fc752d92676bc019ee77ef253be950f46c)
System: Chrome 97.0.4692 / Windows 10.0.0
Referer: https://www.gbif.org/event/11MBxAHpdEQvVHw2RXjH0I/webinar-data-papers-describing-datasets-on-vectors-of-human-diseases
Window size: width 1638 - height 758
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-26T10:22:10.941Z',to:'2022-01-26T10:28:10.941Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-26T10:22:10.941Z',to:'2022-01-26T10:28:10.941Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
@dnoesgaard also Scott just confirmed that Q&A are ready to from the google doc

**Comment by dnoesgaard** [comment]
Added link to slides and all Q&As.
