### ISSUE TITLE
Registering a new museum

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3885]
**Registering a new museum**

Hi, I recently took over as curator/caretaker of a small zoology museum at Swansea University. I am in the process of updating the catalog and wanted to register the collection with GBIF. Should this be done through the collections or institutions section? Thanks, Jessica

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6db4feab45393b71175dce4fc10211fa:5534ea58da39a3eeb18cd16b8b449533a93c0a3f816fe3197eefb916450deb55a75d16b97e2a3042a530dbeeced7cefa5da2020f926258a3f14d950b1b620d29071f81e1fe5c77c73f0e1ec3e4b01b9e)
System: Chrome 97.0.4692 / Windows 10.0.0
Referer: https://www.gbif.org/contact-us
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-26T14:33:35.265Z',to:'2022-01-26T14:39:35.265Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-26T14:33:35.265Z',to:'2022-01-26T14:39:35.265Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

This is a really good question. And the answer depends on how you and your institution would like to be represented on GRSciColl.
I can see that there are already two institution entries relating to herbaria in Swansea:
* https://registry.gbif.org/institution/d26e7ce9-35d1-4163-a190-446b332a74d0
* https://registry.gbif.org/institution/8c1e39a7-6804-488e-82a5-d0327c216e9f

We could merge them and have one institution: “Swansea University” with the herbaria and the zoological museum as collections.
Or you could create a new institution entry to represent the museum as its own institution. It might be especially useful if you have several collections that you would like to detail.

Note that the explanations above are about updating the registry of scientific collections (GRSciColl) which is independent from sharing digitized specimen records on GBIF.
If you would like to share digitized specimen records on GBIF, you should check our quick step guide here: https://www.gbif.org/publishing-data
