### ISSUE TITLE
IPT indexing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3886]
**IPT indexing**

Dear colleagues, 
please look into this dataset, something wrong with indexing data on GBIF page,
it has 262 events and 1018 occurrences in IPT,
but showing only 214 occurrences on GBIF page, 
at the same time Donwload through GBIF gives right numbers (262 events and 1018 occurrences)!
https://www.gbif.org/dataset/5ee9f4a9-6c63-4a72-80c7-9e674d4b7577
http://ipt.ugrasu.ru:8080/ipt/resource?r=zmu-chugas
Nina

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5dcc2ce51705fa9d0d7bbf20d7ef76ee:8b4332a51ed0c0c173191ee14de4675b3d47357a58fd0e8819b743add1032dda771f07ff112ecb7671f93f2df53c01554d58497cb8dc555701703131367beb9d)
System: Chrome 97.0.4692 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/5ee9f4a9-6c63-4a72-80c7-9e674d4b7577
Window size: width 1920 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-27T08:00:41.903Z',to:'2022-01-27T08:06:41.903Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-27T08:00:41.903Z',to:'2022-01-27T08:06:41.903Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

The occurrences refer to eventIDs that don't exist in the event file. For example, the occurrence with the occurrenceID “SamChugas_ZMU_00001” refers the eventID “SamChugas_ZMU_01_(01)_2017-01-17”, which doesn’t exist in the event file.
This is the reason why some occurrences are dropped during the ingestion.

**Comment by ninacourlee** [comment]
I am very sorry, very stupid of me, of course my faul!
