### ISSUE TITLE
excluding issues and flags in downloads

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3889]
**excluding issues and flags in downloads**

In this query, I'm trying to exclude occurrences with certain issues, but when I move on to download the results, the download query seems to do the opposite, i.e. include only occurrence WITH the issues?

I was expecting this https://www.gbif.org/occurrence/download/request?predicate=%7B%20%22type%22:%20%22and%22,%20%22predicates%22:%20%5B%20%7B%20%22type%22:%20%22in%22,%20%22key%22:%20%22TAXON_KEY%22,%20%22values%22:%20%5B%20%223661939%22%20%5D%20%7D,%20%7B%20%22type%22:%22not%22,%20%22predicate%22:%20%7B%20%22type%22:%20%22in%22,%20%22key%22:%20%22ISSUE%22,%20%22values%22:%20%5B%20%22COORDINATE_ROUNDED%22,%20%22GEODETIC_DATUM_ASSUMED_WGS84%22,%20%22COUNTRY_DERIVED_FROM_COORDINATES%22%20%5D%20%7D%20%7D%20%5D%20%7D#create

but I got this

https://www.gbif.org/occurrence/download/request?predicate=%7B%22type%22:%22and%22,%22predicates%22:%5B%7B%22type%22:%22in%22,%22key%22:%22TAXON_KEY%22,%22values%22:%5B%223661939%22%5D%7D,%7B%22type%22:%22in%22,%22key%22:%22ISSUE%22,%22values%22:%5B%22COORDINATE_ROUNDED%22,%22GEODETIC_DATUM_ASSUMED_WGS84%22,%22COUNTRY_DERIVED_FROM_COORDINATES%22%5D%7D%5D%7D#create

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/115f4995e97dbcbde6b87779c6c4d34c:4deb28e0695fa8062d4bc4d15fd5ffd72451aa84aa4509d32c49285e86b3328859ff7c99ddb7de4a984258ea2422756dafe5ca5454cbae7f8d171b2bf8b38ebf)
System: Chrome 97.0.4692 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence-search/beta?filter=eyJtdXN0Ijp7InRheG9uS2V5IjpbIjM2NjE5MzkiXX0sIm11c3Rfbm90Ijp7Im9jY3VycmVuY2VJc3N1ZSI6WyJDT09SRElOQVRFX1JPVU5ERUQiLCJHRU9ERVRJQ19EQVRVTV9BU1NVTUVEX1dHUzg0IiwiQ09VTlRSWV9ERVJJVkVEX0ZST01fQ09PUkRJTkFURVMiXX19&has_coordinate=true&view=DOWNLOAD
Window size: width 1679 - height 1073
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-27T12:06:56.538Z',to:'2022-01-27T12:12:56.538Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-27T12:06:56.538Z',to:'2022-01-27T12:12:56.538Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thank you!
I'm not sure how that sneaked in, but now it is fixed and there is a test to avoid the regression from happening again.
