### ISSUE TITLE
Gonatopus nigricans: a wasp species misplaced under plants

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3892]
**Gonatopus nigricans: a wasp species misplaced under plants**

The species name appears in GBIF.org under the wrong branch of the backbone (a wasp species linked into a plant family). Together with this, the occurrence record (https://www.gbif.org/occurrence/1653530363: Holotype!) also appears under plants rather than under animals, where it belongs. 

Tracing this back: the source dataset (https://www.gbif.org/dataset/5fac9c21-a601-4155-873a-0ddd55f3a0b0) contains six names in the "taxa.txt" file, three of which are classified as Plantae... Araceae. The title of the dataset suggests that these classifications should rather read as Animalia... Hymenoptera. 

Homonymous genera:
- Gonatopus Engl. (Araceae, Liliopsida)
- Gonatopus Ljungh, 1810 (Dryinidae, Hymenoptera)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ee6ba14e877e07b7e9eb274a44a1a239:8934b2be056493cd1511781a46eb472b8af10a73046ce9ce442c7944ac7568bf702bbd5559dbb822a9089cf51e40eb0a6403ce248d3175438a5ee0d58e934627)
System: Firefox 96.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/8482880
Window size: width 1571 - height 810
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-28T09:04:59.745Z',to:'2022-01-28T09:10:59.745Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-28T09:04:59.745Z',to:'2022-01-28T09:10:59.745Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ahahn-gbif** [comment]
@myrmoteras @gsautter Is this something you could help with?  Thanks!

**Comment by myrmoteras** [comment]
@ahahn-gbif please add such cases into our community github and they will re resolved asap, inidvidual cases within a day or so
eg. 
https://github.com/plazi/community/issues/137

I think, this path should already be in place in occurrences?!

cheers
donat

**Comment by ahahn-gbif** [comment]
Thanks @myrmoteras! Yes, it should - coming from the species record, I bypassed that automatic. Noted, and thanks for pulling it over

**Comment by myrmoteras** [comment]
@ahahn-gbif fixed on our side

**Comment by ahahn-gbif** [comment]
confirmed fixed (https://www.gbif.org/dataset/5fac9c21-a601-4155-873a-0ddd55f3a0b0/metrics), closing
