### ISSUE TITLE
Taxonomy (Diptera): Ornidia (Syrphidae) is wrongly associated with Tipulidae

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3893]
**Taxonomy (Diptera): Ornidia (Syrphidae) is wrongly associated with Tipulidae**

see: https://www.gbif.org/species/1543375. 

For reference, the genus in Systema Dipterorum: http://www.diptera.org/Nomenclator?op_name=&Name=Ornidia&op_author=&Author=&op_year=&Year=&op_family=&Family=&op_validname=&ValidName=&kind=&Sortfield=unsorted&sortorder=ascending&max=10&find=Start+Search

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ee08bd50ea86317b157433ba2cdbe824:44d46400669e3cb3b7f5c25e0daafd38dee9fb64bda629bda1ba1ddc43dcb1be494e3d0a676d00599b698fc631b2db2d7ae4b24442fdd595774845511c1e05d3)
System: Firefox 96.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/species/1543375
Window size: width 1584 - height 817
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-28T12:00:47.885Z',to:'2022-01-28T12:06:47.885Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-28T12:00:47.885Z',to:'2022-01-28T12:06:47.885Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The record comes from CoL and the family is correct there (https://www.catalogueoflife.org/data/taxon/69X2).
I am not sure why the family is different in the backbone.
@mdoering could you take a look? how can we check what is happening?

**Comment by mdoering** [comment]
The source reference takes you to [Systema Dipterorum in COL](https://www.gbif.org/species/173709665) which has it classified under Syrphidae. Systema Dipterorum in GBIF has 2 genus records, one also in [Tipulidae](https://www.gbif.org/species/187605740). I suspect this is the cause as we also include it in the backbone.

Looking at the last build configs we actually exclude Diptera from COL and rely directly on Systema Dipterorum: 
https://hosted-datasets.gbif.org/datasets/backbone/backbone-config.yaml

That explains it. But I am surprised that the genus reference taxon points to COL!

**Comment by mdoering** [comment]
Switching to SD directly was a temporary solution since Sept. 2021, see https://github.com/gbif/checklistbank/blob/master/docs/backbone-builds/2021-09-14.md#data-source-changes

We should revert to COL with the next build!

**Comment by mdoering** [comment]
@yroskov has the early issues with Systema Dipterorum in COL been removed in the latest january 2021 release?

**Comment by yroskov** [comment]
Here is a placement in the CoL: unranked: Biota > kingdom: Animalia > phylum: Arthropoda > class: Insecta > order: Diptera > family: Syrphidae > subfamily: Eristalinae > tribe: Volucellini > genus: Ornidia.

Is anything wrong?
