### ISSUE TITLE
occurrence count on homepage links to undefined value

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3896]
**occurrence count on homepage links to undefined value**

https://www.gbif.org/occurrence/search?occurrence_status=PRESENT 

vs 

https://www.gbif.org/occurrence/search?occurrence_status=present

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/403de62516f48ff5b5f26adb9fa0b347:d00297b1f09efc9a5fa70fb302e77d5e7d811bfe28766c57bdf5ca13478b55f9565289cbf31df556392836926a2f8410ab2d0ef86fbf45f40778db0eca7dcfdc)
System: Chrome 97.0.4692 / Mac OS X 10.15.7
Referer: https://www.gbif.org/
Window size: width 1612 - height 1211
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-31T12:15:06.045Z',to:'2022-01-31T12:21:06.045Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-31T12:15:06.045Z',to:'2022-01-31T12:21:06.045Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
Has this been broken all along in the UI or has the API changed with the reprocessing today? Ping @muttcg and @MattBlissett 

It is still uppercase according to https://api.gbif.org/v1/enumeration/basic/OccurrenceStatus but perhaps it has changed to use a vocabulary?

**Comment by MattBlissett** [comment]
https://api.gbif.org/v1/occurrence/search?occurrence_status=PRESENT

https://api.gbif.org/v1/occurrence/search?occurrence_status=present

The API gives the same results for both queries. Nothing is supposed to have changed with this term.

**Comment by dnoesgaard** [comment]
fwiw, I had noticed this before today...

**Comment by MortenHofft** [comment]
https://github.com/gbif/portal16/commit/e4322b2f65c1375adb531fd48bd2d596e34bebbd I did this 4 months ago. I remember it doing in 1 minute without much consideration. And we had a talk afterwards Daniel. Apparently i was sloppy in more than one way. The API and the UI use different case for some reason. That normally isn't the case for values.
