### ISSUE TITLE
Incorrect family placing of Porotermes and Stolotermes genera

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3898]
**Incorrect family placing of Porotermes and Stolotermes genera**

Currently GBIF places species in the Porotermes and Stolotermes genera (e.g. Porotermes adamsoni (Froggatt, 1867), Porotermes quadricollis (Rambur, 1842), Stolotermes inopinus Gay, 1969, and Stolotermes ruficeps (Brauer, 1865 )) under the Hodotermitidae family. However, these species are in the Stolotermitidae family.
Engel, M. S., Grimaldi, D. A., & Krishna, K. (2009). Termites (Isoptera): their phylogeny, classification, and rise to ecological dominance. American Museum Novitates, 2009(3650), 1-27.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a2fc2d2ae6224e7fe908db14240053f0:c6f60a115bb9130f22c5d7a42efae0bdf7914fdf64bbb64b226b69277e5aafc5b53427ae1e37eb1855024a084cd51fad5e8a94aee80c06490e6078bfcf772aba)
System: Chrome 97.0.4692 / Windows 10.0.0
Referer: https://www.gbif.org/species/9710254
Window size: width 1835 - height 850
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-01T20:55:04.801Z',to:'2022-02-01T21:01:04.801Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-01T20:55:04.801Z',to:'2022-02-01T21:01:04.801Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Both of these genera come from the CoL. Except in the CoL, they aren't assigned to any family:
* Porotermes Hagen, 1858 (https://www.catalogueoflife.org/data/taxon/8NXTL) is only assigned to the infraorder: [Isoptera Brulle, 1832](https://www.catalogueoflife.org/data/taxon/8NKF8)
* Stolotermes Hagen, 1858 (https://www.catalogueoflife.org/data/taxon/8NZLF) is assigned to the subfamily: [Stolotermitinae Holmgren, 1910](https://www.catalogueoflife.org/data/taxon/8PS2K)

I don't really know how the system picked the family they are assigned to in the backbone. Any insights @mdoering ? Is this something we could fix on our side?

**Comment by mdoering** [comment]
Definitely sth for COL and Species Files to look into!
@yroskov can you chase this up please? I am not sure where and which SF resource is the current. Blattodea SF, Isoptera SF, Cockroach SF...

**Comment by yroskov** [comment]
@gdower, it looks like there was a problem in TW export script: Set of genera dropped out of parental families. 
https://github.com/CatalogueOfLife/testing/issues/171#issuecomment-1035543612

After correction of the script, we'll re-import SF Isoptera (March-April?).

**Comment by yroskov** [comment]
Fixed now. Changes will appear in CoL of February.

**Comment by ManonGros** [comment]
Solved in the new backbone.
