### ISSUE TITLE
Create a project page for Biota of Russia 2021

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3903]
**Create a project page for Biota of Russia 2021**

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/19b555274fd0afe75f029eb32b226290:0e0001f277ca3873429153aae7c040458ed3335e7e64abee26bb7eb23a14a72594929a5669b25777e26d9f6c11c61775348b42fb95082083c6f135c1cb52ba25)
System: Chrome 97.0.4692 / Windows 10.0.0
Referer: https://www.gbif.org/programme/3ilFFs3JdY2SqmyCuac0uc/northern-eurasia
Window size: width 1862 - height 861
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-03T16:21:22.892Z',to:'2022-02-03T16:27:22.892Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-03T16:21:22.892Z',to:'2022-02-03T16:27:22.892Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
As agreed with / requiested by @timhirsch 

Please create a new project page called Biota of Russia 2021 using this https://www.gbif.org/project/1lLoEkmf2ioQlr7bwDfeDx/west-of-urals-2020 as a template and this https://www.gbif.org/news/HdDwtyv9jjrvG99OSHsP6/call-for-data-papers-describing-datasets-from-russia-closed as a source of information for the new page, sum of contract is €17,000 - public info as for our other projects under Norther Eurasia. Please use the same forget-me-nots visual as in the 2021 call page.

Note that tags mentioned that will be used to update the datasets which were created or updated to publish data papers listed here https://bdj.pensoft.net/topical_collection/59. Annie and Dmitry will take care of correspondence with authors, so it would be nice if a project page is ready to receive and show these datasets as updates will be done by the 2021 authors. Please do the necessary settings so datasets with Russia 2021” in Project Data: Title and “N-Eurasia-Russia2021“ in Project Data: Identifier in the dataset’s metadata will be shown under this new page (currently there maybe none or few tagged like that).

@ahahn-gbif, just to check that you agree this is the same system of retrospective dataset updates as we did in 2020?

**Comment by kcopas** [comment]
Strongly recommend not using the same image. You worried we’re running short?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ahahn-gbif** [comment]
Some verification needed (looks like some line breaks got lost):
- the Project ID is "N-Eurasia-Russia2021" - correct? And all datasets link under just one project for the entire year. This project ID needs to be in the datasets' metadata, in exactly the same spelling as defined for the project page itself, so that the datasets are automatically linked
- the project title and description within the individual datasets are technically no longer needed to link up datasets, though they are strongly recommended to give some meaningful context to the "project" tab on the individual dataset page. That would be the name of the project that the dataset got assembled under, not the program (in case of a program like BID that has many difference projects, each with 1 or more datasets)

Setting up the project pages is under Admin curation for GBIF-run projects. I will forward this information by email, but would ask you to coordinate the details directly.

**Comment by dschigel** [comment]
@kcopas same visual was only suggested to coninue optical matching of the call to the project page, like in 2020. It is astetics, does not have to be like that, see 2020 [call](https://www.gbif.org/news/1VHfuSBGwSzDBxqRHucAHY/call-for-data-papers-from-european-russia) and [project](https://www.gbif.org/project/1lLoEkmf2ioQlr7bwDfeDx/west-of-urals-2020) with the same bumblebee.

- @ahahn-gbif true, spelling could have been better, but this is what tags were for a few months at the 2021 [call page](https://www.gbif.org/news/HdDwtyv9jjrvG99OSHsP6/call-for-data-papers-describing-datasets-from-russia-closed). If there are no datasets tagged yet, we can add an extra hypen, but if there are, I would just use this ugly one. Yes, I remember the exact spelling rule for automatic display of datasets under their project.
- @ahahn-gbif can you check the second box in the closed 2021 call, link above? I hope that “Russia 2021” in Project Data: Title is accurate enough - I remember we agreed about that before opening the call, but useful to double check before Annie will send reminder to all who did not use project data identifiers and project titles...  If the project page setups are with admin, great - I rember you and @dnoesgaard invovled in finishing the 2020 project page, I just don't know / remember current roles.

Thanks!

**Comment by ahahn-gbif** [comment]
Sorry, @dschigel, I don't understand what you mean by "checking the second box". As per your earlier question, I am completely fine with you proceeding as with the earlier call. I have not been involved with setting up any project pages in the past though, so I cannot really advise on anything other than how to make sure the datasets can get connected automatically. 

@dnoesgaard, were you involved with setting up the [2020 project page](https://www.gbif.org/project/1lLoEkmf2ioQlr7bwDfeDx/west-of-urals-2020), and would you do it again, or does it need coordination with the Admin group?

**Comment by dschigel** [comment]
Thanks everyone, Annie will pospone correspondence with dataset until the new project page is set.

**Comment by dnoesgaard** [comment]
It looks like I set up the previous one. I don't mind doing this new one. ..

**Comment by dnoesgaard** [comment]
https://www.gbif.org/project/7fzLHvyCdEfM21SNS568ac/biota-of-russia-2021
