### ISSUE TITLE
gbif/health

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#3904]
some time ago, gbif/health has been the place to go to check the status of GBIFs system. Now it is something completely different.

Is there a place to go to find out whether the system is working, processing so if something takes a moment to show up in GBIF, we have a first check?

thanks
donat

**Comment by kcopas** [comment]
Still in the toolbar, but now located at https://www.gbif.org/system-health

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
