### ISSUE TITLE
Data validator is not working and keeps uploading archives

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3906]
**Data validator is not working and keeps uploading archives**

Data validator is not working, it keeps uploading files for a long time and gives an error message at the end.
All systems appear operational, so I don't know if there is a problem or maybe you are changing things in the validator

-----

User: [See in registry](https://www.gbif-uat.org/api/feedback/user/d9aa25f21b11c639707540edaee28fc6:9cffcf0a5a8a7e4e771d949cb77872e6585889abc90fe0b0a79af6b4891a93e558f89be904f6d05f15245a3c41467fc117654e43bba4b0053bed534f8e9a72fb)
System: Chrome 88.0.4324 / Mac OS X 11.5.1
Referer: https://www.gbif-uat.org/tools/data-validator/4f1432f4-4686-432a-b711-8dae89ed0015
Window size: width 1344 - height 729
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-03T21:34:18.257Z',to:'2022-02-03T21:40:18.257Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-03T21:34:18.257Z',to:'2022-02-03T21:40:18.257Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
NB: this is coming from UAT

**Comment by EstebanMH-SiB** [comment]
Hi, it does not work with using a single file (I tried a .txt and .xlsx), but it works with a DwC-A. Also I did the report in the UAT but the normal validator have the same problem

**Comment by ManonGros** [comment]
Hi @EstebanMH-SiB the new validator no longer supports txt, csv and xlsx files but you can always use the old validator for those cases: https://www.gbif.org/tools/data-validator-legacy

**Comment by muttcg** [comment]
It will appear soon in the new version, please follow https://github.com/gbif/pipelines/issues/659
