### ISSUE TITLE
KUBI Ornithology images

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3907]
**KUBI Ornithology images**

Hi.  I just republished our Ornithology collection using image links (URLs) rather than the Audubon Core extension we [previously used for this collection.  This is due to an error that is occurring in the Vertnet post-processing step that we previously used to produce the extension data.  We are using the same mechanism (URLs) for all other KUBI collections, however, now I am not seeing any images at all.  Could you check to see why these images are not showing up, please?

Thanks

Andy

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1e0a66148974a645ce9d10f2287b22cc:3c6e08c3c9ae17253f20b450cc667d824ef097922958d365d9e4433296b4684378d6b866c4cb3f353e00428787fd080b565c7c3d66e16b73e45d91d4ba9bc1a7)
System: Chrome 98.0.4758 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/3462064333
Window size: width 1152 - height 629
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-04T01:06:44.395Z',to:'2022-02-04T01:12:44.395Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-04T01:06:44.395Z',to:'2022-02-04T01:12:44.395Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: e635240a-3cb1-4d26-ab87-57d8c7afdfdb
publishingOrgKey: b554c320-0560-11d8-b851-b8a03c50a862
Network keys: 99d66b6c-9087-452f-a9d4-f15f2c2d0e7e 
Node handles: @albenson-usgs

**Comment by MortenHofft** [comment]
The fragment (data as provided by the publisher, but split into individual records) for this occurrence has no associated media
https://api.gbif.org/v1/occurrence/3462064333/fragment

The fragment for one of the other KUBI occurrences has associated media and hence shows an image.
https://api.gbif.org/v1/occurrence/1934868999/fragment

I do see associatedMedia for other occurrences in the dataset though. E.g.
https://api.gbif.org/v1/occurrence/3462067307/fragment
which says: `turkey.png`. Which doesn't show as the url isn't valid. https://www.gbif.org/occurrence/3462067307

Is that at all any help?

> user notified by email

**Comment by acbentley** [comment]
I am seeing this in the associatedMedia DwC field for one of the records (catalog number 131254; occurrenceID 5f8483c9-25bf-4220-949b-ddc657f0d9f1) in the bird dataset:

http://biimages.biodiversity.ku.edu/static/Ornithology/originals/sp64164506455926919016.att.JPG

There should be about 2280 more of them in the occurrence dataset.

These resolve to images on the attachment server associated with this collection.  This is how it is done in all our other KU collections and thumbnails are generated from these.

**Comment by acbentley** [comment]
Looks to be working now after finding my error and republishing
