### ISSUE TITLE
about the repository

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3911]
**about the repository**

Dear staff of GBIF,

I’d like to know the cost of depositing the data in GBIF, and how long can my data in this repository preserved?
I can’t find corresponding document.
Thanks for your help.

Sincerely yours,
Zhenyu Wei

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/42174be2b790cc534f2525495e878d3f:519517bd5bf6ce61be419dda4fbb57234932b61e3f43c86ed9393bf744e52ab5984950153c920b9fab0a7f9f230f370b695791d3b2b14429eb42c7ba8cffb0c7)
System: Safari 15.2.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/publisher/search
Window size: width 1440 - height 820
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-04T19:26:02.819Z',to:'2022-02-04T19:32:02.819Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-04T19:26:02.819Z',to:'2022-02-04T19:32:02.819Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Responded via (duplicate) email.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
