### ISSUE TITLE
Checklist data published using occurrence core

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3913]
**Checklist data published using occurrence core**

This seems like a premature data publication which publishes checklist data as occurrences. Will this complicate the indexing of GBIF.org? If so, I should coordinate to correct it.

-----

Github user: @ckotwn
User: [See in registry](https://www.gbif.org/api/feedback/user/326a46c9298a0931c09cf0ce3de20b63:54a276162ab37cd4c5f04e77bf5a0945dfd2461d2d865c2518a71a1d66bbe7b42619e56250ac7aa0f94164dffffd04fe4ac00f4ba20638c4b3c275d295a2590d)
System: Firefox 96.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/dataset/14d71780-b34f-4fbb-9545-a73e3f31e439
Window size: width 1504 - height 1582
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-07T04:25:14.775Z',to:'2022-02-07T04:31:14.775Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-07T04:25:14.775Z',to:'2022-02-07T04:31:14.775Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ckotwn** [comment]
@ManonGros

**Comment by ManonGros** [comment]
Hi @ckotwn it does look like it should be a checklist and not an occurrence dataset. Especially since the occurrence published aren't the actual occurrences they mentioned:
> The data presented in this checklist come from specimen records, field surveys, and local floras. We do not find any records in GBIF but 1767 records in NSII.

That being said, there is no harm in keeping the occurrences for now. The only information associated with them is "this species occurred in China at some point". It isn't very useful but it isn't incorrect either.

In any case, it would be great if you could talk with the publishers and make sure they understand the differences between the dataset types (we have this blogpost that can help: https://data-blog.gbif.org/post/choose-dataset-type/). Many thanks!

**Comment by ckotwn** [comment]
@ManonGros A quick look-up reveals that the publisher has registered two datasets of the same resource:
checklist_of_wanda: https://www.gbif.org/dataset/14d71780-b34f-4fbb-9545-a73e3f31e439
checklist_wanda: https://www.gbif.org/dataset/ea3ad43a-e96f-47e8-b3ae-2272d730c18f

To merge these, do you recommend deleting first one, or migrating? In such a case when the newer dataset is already registered, does it work by inserting older UUID in the 'Additional Identifiers' section of the newer one?

**Comment by ManonGros** [comment]
@ckotwn the Additional identifier method won't work for datasets that are already registered but we can link the old dataset to the new one before deleting it. Like in this example: https://www.gbif.org/dataset/fc003253-5eee-414e-84c8-817e12bdb708
Should I just do that?

**Comment by ckotwn** [comment]
Hi @ManonGros once you've done, please let me know so that I can inform the publisher to delete the dataset from the IPT. Thanks!

**Comment by ManonGros** [comment]
Hi @ckotwn the dataset can now be deleted from the IPT (and the registry)

**Comment by ckotwn** [comment]
Tried deleting https://www.gbif.org/dataset/14d71780-b34f-4fbb-9545-a73e3f31e439 from the IPT. First we chose `Delete from the IPT and GBIF.org`, reported error. Then we chose `Delete from the IPT (orphan) successfully. Why the first error, please?

**Comment by ManonGros** [comment]
@ckotwn it is my fault, sorry, I had deleted the dataset in the registry already. I should have told you to only delete the dataset in the IPT. When a dataset is already deleted in the registry and the IPT is trying to delete (again), it generates an error.
Again, I am sorry for the confusion.
