### ISSUE TITLE
Image error

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3915]
**Image error**

That species here isn't P. graveolens, which has philotaxy is palmated, not like this

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5c73be579114de1b106d69be0b256d32:d34e7d51738a613a4590af42dbea5448b4dedece61dcfb9ab6caca1efbb0b6b9c7cd8915a0b352a57f61bd42467215b3a1fca5957558e39f914d972347c0b4d0)
System: Chrome 97.0.4692 / Windows 7.0.0
Referer: https://www.gbif.org/occurrence/2974602541
Window size: width 1400 - height 945
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-08T17:06:45.294Z',to:'2022-02-08T17:12:45.294Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-08T17:06:45.294Z',to:'2022-02-08T17:12:45.294Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by jhnwllr** [comment]
https://identify.plantnet.org/the-plant-list/observations/1008278714
I have marked the observation as "Unidentified" using a plant net account.

**Comment by CecSve** [comment]
User has been notified of the removed record and I will close the issue.
