### ISSUE TITLE
Publisher seeking to add a new dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3917]
**Publisher seeking to add a new dataset**

Hello, I'm trying to find how to add a new dataset. I'm the technical contact for the publisher (https://www.gbif.org/publisher/c4cbb860-e9c7-11da-8113-b8a03c50a862) but can't find information about how to edit the publisher details or add a new dataset. Old login information I have on file is not working. The current publisher profile was created a long time ago and datasets were provided via DiGIR. We no longer have those methods and don't use the IPT, instead we use Symbiota with the built in DwC-A publishing method.
Thanks! Jason Best

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1406fc7bc754a7a19816c20726510095:56544ccc60163ed30289e29ae91cad9790f8199679984f61b0b001a8ca3002dd7a76bb7ec3ac21d02bc50268eb914ad87af33270299036628417e85a71b433dc)
System: Firefox 96.0.0 / Mac OS X 10.12.0
Referer: https://www.gbif.org/installation/5ffe5e10-f762-11e1-a439-00145eb45e9a
Window size: width 1440 - height 760
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-08T20:52:47.044Z',to:'2022-02-08T20:58:47.044Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-08T20:52:47.044Z',to:'2022-02-08T20:58:47.044Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email.

We can update [your GBIF publisher page](https://www.gbif.org/publisher/c4cbb860-e9c7-11da-8113-b8a03c50a862). Just send us the list of changes you would like to see at [helpdesk@gbif.org](mailto:helpdesk@gbif.org)
 
The way to publish data via Symbiota depends on whether the portal is already configure to share data on GBIF.
