### ISSUE TITLE
Can you help me find all records of species invasive to the United States of America?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3918]
**Can you help me find all records of species invasive to the United States of America?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6d3d07f5ffbf4740849b63d91c97b502:18be0e697e36ca3a168529a8404a8650a4d735d4a535a1f0ce0fea1f7dcc758d7c9b04517eda0a8d5b8fd0c4557c96af9037631143a10c369ad0135707b13d7e)
System: Chrome 98.0.4758 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0132306-210914110416597
Window size: width 1280 - height 577
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-08T22:20:27.393Z',to:'2022-02-08T22:26:27.393Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-08T22:20:27.393Z',to:'2022-02-08T22:26:27.393Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
responded by email.
