### ISSUE TITLE
Download datasets as original dwca

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#392]
**Download datasets as original dwca**

The datasets page contains a download tab/link.
I would expect to be able to download the original, registered dwc archive there, but instead I only get offered an EML file.

Propose to also add the dwca URL as it is registered and shown below in GBIF registration details

-----
fbitem-dataset52a423d2-0486-4e77-bcee-6350d708d6ff

System: Chrome 60.0.3112 / Mac OS X 10.12.5
Referer: https://www.gbif.org/dataset/52a423d2-0486-4e77-bcee-6350d708d6ff
Window size: width 1667 - height 886
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-24T14:13:03.714Z',mode:absolute,to:'2017-08-24T14:19:03.714Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-24T14:13:03.714Z',mode:absolute,to:'2017-08-24T14:19:03.714Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
This is because it is hosted by the GBIF Secretariat and we don't wish to advertise that too prominently.
