### ISSUE TITLE
Flicker in the UI truncates the authority information

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3920]
**Flicker in the UI truncates the authority information**

The authority information on the name in the H1 tag on this page gets truncated on page reflow.

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/2e1e7c498dac5b0a19ddcd81b982612b:38028ebe9ecd8733528acd3f1cd0d66aa5d6c577f410eef443ab9b52a6127b88b6842e8fe0c221805ec24201f2c80198d95e0f33873a0ff33f272a2fe102419822c38db7d33fc81ad94f218b92f223b3)
System: Chrome 98.0.4758 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/192604755
Window size: width 1624 - height 517
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-09T14:56:03.202Z',to:'2022-02-09T15:02:03.202Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-09T14:56:03.202Z',to:'2022-02-09T15:02:03.202Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dshorthouse** [comment]
Duplicate #3916.

**Comment by thomasstjerne** [comment]
Closing, for further info see https://github.com/gbif/portal-feedback/issues/3916
