### ISSUE TITLE
All records flipped from PRESERVED_SPECIMEN to HUMAN_OBSERVATION

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3925]
**All records flipped from PRESERVED_SPECIMEN to HUMAN_OBSERVATION**

All the records from this dataset were republished with the basisOfRecord = HUMAN_OBSERVATION whereas they were all once PRESERVED_SPECIMEN. This must be in error.

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/19c44ddd78fd12eb6f14b9885637e2e4:8537a48d89874186a447777a9b844bbfc805e2a9c611d6245d3549d9c3c1cb5800aa629c9800e80649bcac394c24a7efd9290a40a5d0d2c6442720e3e86ea78cd2579791bfb148e850a07f104454f9bc)
System: Chrome 98.0.4758 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/cf8f886b-7289-4d59-9cb1-f2d293147d98
Window size: width 1624 - height 894
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-10T16:34:52.250Z',to:'2022-02-10T16:40:52.250Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-10T16:34:52.250Z',to:'2022-02-10T16:40:52.250Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
They are back to preserved specimens
