### ISSUE TITLE
occurrenceIDs now have braces around them

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3926]
**occurrenceIDs now have braces around them**

This dataset was recently republished to newly include braces around all its occurrenceIDs, triggering whole new gbifIDs to be created.

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/020069c59d3e3a1401647c45024fd6e4:2be6f0ad8e945f8810dbdacbc0b2e07220d2eeff5724ed55a56ec2da3ad07c63ff16e3d5080169aac41d72b8527aa2364c5f30fe769b9bbf4fdd5fa4efcde47bb11f04b444897f6cec905754744d7588)
System: Chrome 98.0.4758 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/9b7d1acf-b22f-4a1f-b6e8-f1ddd744dc07
Window size: width 1624 - height 894
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-10T16:57:22.358Z',to:'2022-02-10T17:03:22.358Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-10T16:57:22.358Z',to:'2022-02-10T17:03:22.358Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by AbbyBenson** [comment]
@themerekat is contacting the data manager about this.

**Comment by dshorthouse** [comment]
Thanks @themerekat & @albenson-usgs. I too contacted the data publisher (& Ed Gilbert in the event this is a systemic issue to Symbiota) via email. They may have received this now from all sides.

**Comment by dshorthouse** [comment]
Looks like the occurrenceIDs have all been reverted, with braces removed. Can close this now.
