### ISSUE TITLE
I have a question about occurrence data.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3929]
**I have a question about occurrence data.**

I have a question about occurrence data. In the "basis of record" menu, what does "preserved specimen" include? Does this include un-vouchered tissue samples, like a blood sample? Does this include photographs? I'm hoping that this only includes traditional museum-style specimens (e.g., study skins, skeletons, etc.). Thanks very much for your help!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3565b45daf5cad119d294276bd2c1b71:fbccd467efd3b2774c71502234751773641354a4624962986829fb10c62950f113247e77d74a7736e06f1039be25c0f072961540c39e763efd892cf6e8554449)
System: Chrome 97.0.4692 / Mac OS X 10.14.6
Referer: https://www.gbif.org/faq
Window size: width 1627 - height 1173
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-11T20:59:36.305Z',to:'2022-02-11T21:05:36.305Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-11T20:59:36.305Z',to:'2022-02-11T21:05:36.305Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
replied by email:
> The preserved specimen basis of record will mostly include traditional museum-style specimens such as herbarium sheet or skeleton.
That being said, the interpretation of the vocabulary (https://dwc.tdwg.org/terms/#preservedspecimen) is up to the data provider. Some “preserved specimens” might be preserved tissues but most would be under the basis of record “material samples”.
 
> In doubt, I suggest to check the dataset metadata for the records you would like to work with. They will include more context about the records (for example, if they are part of a Natural History collection). You will also find the contact information for the data providers.
