### ISSUE TITLE
Encounter Bay project link doesn't work

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#393]
**Encounter Bay project link doesn&#39;t work**

Living Atlases page

The Encounter Bay project link doesn't work.

Best,
Marie-Elise

-----
fbitem-2685271de3ece2ea1bc629a115e92efe03e98182
Reported by: @melecoq
System: Chrome 60.0.3112 / Mac OS X 10.11.6
Referer: https://www.gbif.org/programme/82953/living-atlases
Window size: width 1296 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-24T20:58:24.886Z',mode:absolute,to:'2017-08-24T21:04:24.886Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-24T20:58:24.886Z',mode:absolute,to:'2017-08-24T21:04:24.886Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
Thanks for noticing, @melecoq. I fixed the project link now.
