### ISSUE TITLE
How do I select data on endangered species for Timor-Leste?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3930]
**How do I select data on endangered species for Timor-Leste?**

I need to create a data set for Timor-Leste that covers the critically-endangered CR and endangered EN species, then get the distribution data. Can you tell me how? Thank you.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2e77efde927c1bd3fce016bb7f41c679:c0546c089a425a25c85b6e5fe9f09bcbf9c73ec081c4f2fa5bac655329b7d40a353d5335294e7c83fe48f4ccaa539ed684c7dcdffe6f7bff29f7052bc5fa038e)
System: Safari 15.1.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/search?q=Timor-Leste
Window size: width 1366 - height 705
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-11T22:28:27.869Z',to:'2022-02-11T22:34:27.869Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-11T22:28:27.869Z',to:'2022-02-11T22:34:27.869Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Filter occurrences by country and Red List status(es):
https://www.gbif.org/occurrence/search?country=TL&advanced=1&occurrence_status=present&iucn_red_list_category=CR&iucn_red_list_category=EN

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ManonGros** [comment]
notified the user by email too (in case the answer was missed)
