### ISSUE TITLE
This species, Saussurea talungensis is only found in Humla, Nepal. Therefore the page that contains distribution record besides from Nepal is a typo error.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3937]
**This species, Saussurea talungensis is only found in Humla, Nepal. Therefore the page that contains distribution record besides from Nepal is a typo error.**

The valid link for recently published manuscript of new species is: https://doi.org/10.3897/phytokeys.176.61996

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f63d3aac8f997b24296a0a7e7c65fb61:f0a60f2dc08d80ffaf6c4a51e685231ab8799d1ddf6a2c0b718396d954239a4574731e111f6d2857ecd4d8aafbb8b15c3bab1869f3a65e7afeb3642c87bc0e5739db1c399986647f543ac98f4ec52102)
System: Chrome 98.0.4758 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/3079224311
Window size: width 1920 - height 902
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-17T15:12:56.759Z',to:'2022-02-17T15:18:56.759Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-17T15:12:56.759Z',to:'2022-02-17T15:18:56.759Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: c31ce8bd-b442-4668-956b-a6696feae657
publishingOrgKey: 7ce8aef0-9e92-11dc-8738-b8a03c50a862

**Comment by santoshkumarrana** [comment]
Data portal should have authentic source (like herbarium, publication, etc.) when providing the distributional record of species, particularly for an endemic species. Observation based records should be discouraged in such portal.

**Comment by JonasBlanco** [comment]
We identified the problem. The additional examined materials were linked to the treatment of the species Saussurea talungensis, and between them were specimens from outside Nepal. We have already separated these materials from the treatment, so the information must be soon updated and corrected in the links.

Please, let us know if the problem was solved and if there is any other issue regarding these treatments and materials citations.
