### ISSUE TITLE
"Geodetic datum assumed WGS84"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3939]
**&quot;Geodetic datum assumed WGS84&quot;**

If the flag of data is "Geodetic datum assumed WGS84", does that means the Geodetic datum information is not right?

Thank you so much.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/10015cb77a93892e8686c6c2674ae7c5:bf1ff59b27f28657ddd6ec27d5274b10b72ccddffc1d393cfe463c6b54511048670f123b55d47d260f3345a22aa596a0a68e85df4ad8fc4481f322503d61116e)
System: Chrome 98.0.4758 / Mac OS X 10.15.7
Referer: https://www.gbif.org/faq?q=Geodetic%20datum%20assumed%20WGS84
Window size: width 1440 - height 732
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-18T16:11:47.851Z',to:'2022-02-18T16:17:47.851Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-18T16:11:47.851Z',to:'2022-02-18T16:17:47.851Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by tucotuco** [comment]
No, it means that there was not enough information to determine what the
geodetic datum was, therefore it MIGHT not be right.

**Comment by MortenHofft** [comment]
User informed per email
