### ISSUE TITLE
IPT

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3942]
**IPT**

Good afternoon! We've had a crash)

The number of records in datasets does not correspond to those indexed by IPT.

https://www.gbif.org/publisher/943a5811-d56e-4c37-853d-bd64957d3833 
&
http://altb.asu.ru/ipt/ 

It happened without our influence. We send the data again - nothing changes.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/aec1e2bfe2c845efd47ceeabb5f98643:1c25df0711646678a6ed8220f7f3137d9178a6eb74a670e21271dab81fc09bf9eafdd5d14b561c703832edc1be160e46ed33d114bb6c7f97410d0b25228805df716d905cc7e035da28d18cecdf70d93d)
System: Safari 15.2.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/ru/contact-us/directory
Window size: width 1365 - height 642
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-21T05:35:32.329Z',to:'2022-02-21T05:41:32.329Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-21T05:35:32.329Z',to:'2022-02-21T05:41:32.329Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The issue seems to have been solved but I wrote to the user to ask for confirmation.
