### ISSUE TITLE
Occurrence basemap and overlay options

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3943]
**Occurrence basemap and overlay options**

It's difficult to place occurrences in their geographic and administrative context because the map background is so basic. A different base map and/or the addition of a few overlay layers like terrain and possibly even geological and bioclimatic maps would make exploring occurrences within gbif.org easier and more informative. With more map options, researchers could undertake a brief analysis before loading datasets into GIS software or doing analysis in R or Python, for example.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a680f6e011763e6dd10535669d8c83c1:31da0c8d58326682e1ed8a433ff55f301a8cd3b6331698dbfebecf58037175cd0562b799b2db3f0f37716bcfc7947d69b976d9ccf9dbe18683ba0bd0dccac49c)
System: Chrome 98.0.4758 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/map?taxon_key=2497&gadm_gid=MEX.13.20_1
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-21T15:35:20.293Z',to:'2022-02-21T15:41:20.293Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-21T15:35:20.293Z',to:'2022-02-21T15:41:20.293Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thanks for your comment

You can now toggle the style to a basemap with more details and an overlay that has bold colors, so hopefully nothing is lost on the more information rich basemap.

![Screenshot 2022-02-22 at 16 20 27](https://user-images.githubusercontent.com/6759267/155163071-d9f14814-f610-4758-af4b-eabfab0ba1f3.png)

> user notified by email
