### ISSUE TITLE
On https://www.gbif.org/standards in "conventions to describe, recording and structure thousands of different datasets" should be "record" instead of "recording", right?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3946]
**On `https://www.gbif.org/standards` in &quot;conventions to describe, recording and structure thousands of different datasets&quot; should be &quot;record&quot; instead of &quot;recording&quot;, right?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/54cfe6cadf4886bd1509b16098e4822a:002bc0ea7a79a45c35d5f29d72150eeabf314249dda8e1f53ce6a35573fcd4377d02dbece04263f95fcf6fbcb0f54474f1305831d2cc5226f18062a84e106b3b)
System: Firefox 97.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/standards
Window size: width 1536 - height 711
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-22T19:51:22.687Z',to:'2022-02-22T19:57:22.687Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-22T19:51:22.687Z',to:'2022-02-22T19:57:22.687Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Corrected.
