### ISSUE TITLE
On https://www.gbif.org/darwin-core "samping" (only occurs once on the page) should be "sampling" (the 'l' is missing).

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3947]
**On `https://www.gbif.org/darwin-core` &quot;samping&quot; (only occurs once on the page) should be &quot;sampling&quot; (the &#39;l&#39; is missing).**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/985060dc53b3f3dcec2bfc5016c33d96:02387339af0bbb1fb55d8439e0598dad2846680e65830ad5b3d110a11d2b760a1401f1650ff44394741295d168d44cecad0bc82724d30a94228b422f8e136b1d)
System: Firefox 97.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/darwin-core
Window size: width 1536 - height 670
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-22T20:06:44.350Z',to:'2022-02-22T20:12:44.350Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-22T20:06:44.350Z',to:'2022-02-22T20:12:44.350Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Corrected.
