### ISSUE TITLE
Metrics reported in the Activity Report do not match the Summary Page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3948]
**Metrics reported in the Activity Report do not match the Summary Page**

The Summary page shows 754,087,823 occurrences mobilized by the US from 2138 datasets but the Activity Report shows 740,180,209 occurrences from 1000 datasets in the data mobilization section. I'm confused by this discrepancy. Obviously the number of occurrences may be due to when the Activity Report is run (January 2022) but the number of datasets doesn't seem right. I seriously doubt there have been 1138 datasets published since January.

-----

Github user: @albenson-usgs
User: [See in registry](https://www.gbif.org/api/feedback/user/322a44cd4c11fa0a795cb5b8b5100378:3a2c2189acaea0e65dbe29a1382e832e7454172d7ef2478993118b46c2a42d646d25f8e3d718450dc12bcd8833c7992c9098b94c55a22b4a092f053d07b60cbd)
System: Chrome 98.0.4758 / Windows 10.0.0
Referer: https://www.gbif.org/country/US/summary
Window size: width 1024 - height 462
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-22T21:38:30.294Z',to:'2022-02-22T21:44:30.294Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-22T21:38:30.294Z',to:'2022-02-22T21:44:30.294Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
API responses (just to check that it isn't the website)
https://api.gbif.org/v1/occurrence/search?publishing_country=US&limit=0 `count=745138680`
https://api.gbif.org/v1/dataset/search?publishing_country=US&limit=0 `count= 2138 `

The report says `occurrences: 740,180,209` and `datasets: 1000`

So it is "only" 5 million more occurrences. But the dataset count really do sound weird and `1000` is a somewhat suspicious number.

**Comment by MortenHofft** [comment]
https://analytics-files.gbif.org/country/CH/GBIF_CountryReport_CH.pdf
Switzerland has 1000 datasets (accoording to the country report) as well. According to the API they have 38k+ datasets.

This looks like a bug in the country report

ping @thomasstjerne and @MattBlissett

**Comment by MattBlissett** [comment]
Thanks for letting us know.

It's a bug in the country reports affecting publishers with over 1000 occurrence  datasets, which includes the USA for the first time this year.

These reports are affected:

```
 1029 MX 2022 2021
 1462 CO 2022 2021
 1860 GB 2022 2021 2020
 2016 US 2022
 2617 FR 2022 2021 2020 2019 2018
 8728 DE 2022 2021 2020 2019 2018
15265 CH 2022 2021 2020
```

I've updated the 7 current reports.

**Comment by AbbyBenson** [comment]
> which includes the USA for the first time this year.

Wait something still doesn't make sense- are you saying that the US published 1138 datasets in 2022? That doesn't seem right? We had to have been over 1000 before this year? I don't think anyone is going back to old Activity Reports so this is only a minor point and not worth digging into but that just doesn't sound right to me.

**Comment by MattBlissett** [comment]
The [2021 USA activity report](https://labs.gbif.org/country-reports/country-reports-2021/country/US/GBIF_CountryReport_US.pdf) showed 844 datasets with occurrences in January 2021, so it should not have been affected by the limit of 1000. The 2022 report now shows 2,016 datasets with occurrences for January 2022. 

There are currently 2,139 datasets, but this includes 2022 publications as well as datasets without occurrences (metadata and some checklists).

1,101 of the new datasets for 2021 are from [OBIS-SEAMAP](https://www.gbif.org/publisher/67b2263f-6990-4d9d-b32b-20aa72ef4fbc).

**Comment by AbbyBenson** [comment]
Ah ok these reports are run yearly. I had it in my head they are run monthly. Thanks Matt for providing all that information. I appreciate it.

> 1,101 of the new datasets for 2021 are from [OBIS-SEAMAP](https://www.gbif.org/publisher/67b2263f-6990-4d9d-b32b-20aa72ef4fbc).

Wow! 🎉👏
