### ISSUE TITLE
Metadata datasets with occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3953]
**Metadata datasets with occurrences**

We have a surprising amount of metadata only datasets with occurrences.

Perhaps we should automatically detect them?

https://www.gbif.org/dataset/search?type=METADATA

17/20 on the first page has occurrences with coordinates

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/deece996669bb6b8bc9c8158fee2505d:556f3e9fed9d02a08b208aaf7472c700711cd2cf5aa60348921b183e88179cd864d34d89edd020cb19f3ff8e9532cd5ed723493393c4bdd275a7905b0eeaebca)
System: Chrome 98.0.4758 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/search?offset=0&type=METADATA
Window size: width 1925 - height 1306
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-28T13:23:50.012Z',to:'2022-02-28T13:29:50.012Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-28T13:23:50.012Z',to:'2022-02-28T13:29:50.012Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It looks like a lot of them were occurrence dataset which were transformed into metadata datasets like this one: https://www.gbif.org/dataset/bc76c690-60a3-11de-a447-b8a03c50a862, except our safeguard prevented the deletion of occurrences.
I will remove occurrences for those cases.

**Comment by ManonGros** [comment]
It doesn't look like there is any more dataset like that.
