### ISSUE TITLE
Broken links to the old community site

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3957]
**Broken links to the old community site**

Was looking for names of receivers of GBIF badges and landed this page. Suggest links can be either removed or point to any curated online documents (the recipients).

-----

Github user: @ckotwn
User: [See in registry](https://www.gbif.org/api/feedback/user/8a77af75a6d89be3ab56f2271d7926f2:7905becac0d94620afe0c1c29b611a5483e0756637fa223e38278b45e46308dbe590504a7e674d8385d23a4742811d1b334adead2fbc97eaa56d8902708d0825)
System: Firefox 97.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/news/82656/gbif-nodes-staff-earn-first-digital-badges-for-data-publishing
Window size: width 1504 - height 1582
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-02T11:10:09.113Z',to:'2022-03-02T11:16:09.113Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-02T11:10:09.113Z',to:'2022-03-02T11:16:09.113Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Removed.
