### ISSUE TITLE
Verbatim page without information shown

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3958]
**Verbatim page without information shown**

When I visit a verbatim page for a species I can get to its parent, e.g. this genus, by hitting the tree navigation.

The verbatim tab then stays, though there is no verbatim data existing because the origin is VERBATIM_PARENT

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1241c4e632381a4b24612355f3e816e7:6a911a2b2ad31c511c461a1dba2135a61a29c014f70cac80c4056822487b83dc9e0c2e8d657ba01f7d0cc7336602267f38875393b5f166b936dedbab5d7a73d3)
System: Safari 15.1.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/193586595/verbatim
Window size: width 1466 - height 971
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-02T12:12:22.215Z',to:'2022-03-02T12:18:22.215Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-02T12:12:22.215Z',to:'2022-03-02T12:18:22.215Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
It sounds like it should either flip to the main page. Or as we generally do; inform the user that they are on a page without content a la https://www.gbif.org/country/CN/participation (which you can only get to by tampering with the url or from a "dead" link since the tab isn't there)
