### ISSUE TITLE
pterolobim stellatum

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#396]
**pterolobim stellatum**

-----
fbitem-species5357452

System: UC Browser 11.3.8 / Android 5.1.1
Referer: https://www.gbif.org/species/5357452
Window size: width 360 - height 519
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-25T07:49:10.910Z',mode:absolute,to:'2017-08-25T07:55:10.910Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-25T07:49:10.910Z',mode:absolute,to:'2017-08-25T07:55:10.910Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I'm guessing the user believe the name is spelled wrongly

**Comment by ahahn-gbif** [comment]
They have a lot of taxonomic name sources against them, though. Without any further explanation or a contact address, I suggest to close as "can't reproduce"
