### ISSUE TITLE
"Licence" should be "License"!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3962]
**&quot;Licence&quot; should be &quot;License&quot;!**

In the right side of the first paragraph of the dataset page (e.g. 
https://www.gbif.org/dataset/e3f878c9-d44d-419b-8b4d-4d4a755d8159), "Licence" should be "License"!
This typo is seen all the dataset pages.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c86d2034a3e15fd1e3f245138509252f:01f7ee4e30ffc0f56c560c49fe565ca6f68e8525695d0534977d870085203055dcacf76d41660237b558109821287b47e55353556957697653e4681aad51caf1)
System: Firefox 97.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/e3f878c9-d44d-419b-8b4d-4d4a755d8159
Window size: width 1469 - height 871
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-03T16:20:16.288Z',to:'2022-03-03T16:26:16.288Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-03T16:20:16.288Z',to:'2022-03-03T16:26:16.288Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Licence is the correct spelling. We follow the Oxford dictionary.

**Comment by kcopas** [comment]
Actually, it’s UN style—but it’s still ‘licence’.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timhirsch** [comment]
In case of doubt on this - UN and UK spelling use licence for the noun, license for the verb.
