### ISSUE TITLE
Columns collapsed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3964]
**Columns collapsed**

Hi

I generated a larger dataset of occurrences than I expected and it appears that when I try and read it in to R, the columns aren't reading correctly, with some fields containing multiple values. Unfortunately the way they're collapsed means that R thinks there are different numbers of columns in the header and rows, so it poses a number of challenges when I try and tidy / wrangle it.

This is the download I requested: https://doi.org/10.15468/dl.ae7ye3

Any ideas what's going on or how to read the data?

Thanks

Harry

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e7dd37bc67e394823509cdb7620b20f9:a15fbdd52405a12611b90800bc2f8034fd5c8898a36256124abbceab1893126eb95edf95bbd3527bb15189a7ce3199254e515dbf2f07546db4afe4bf3fcd67d1)
System: Safari 15.3.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/0172956-210914110416597
Window size: width 1619 - height 1019
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-05T11:08:30.824Z',to:'2022-03-05T11:14:30.824Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-05T11:08:30.824Z',to:'2022-03-05T11:14:30.824Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> R users might encounter some issues when reading files downloaded from GBIF. I suggest to check the following forum thread: https://discourse.gbif.org/t/reading-gbif-downloads-simple-csv-with-r/2615
