### ISSUE TITLE
The coordinate for this specimen seems to be in the water. I'm not sure if there is actually an island there but I wanted to flag it just in case!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3967]
**The coordinate for this specimen seems to be in the water. I&#39;m not sure if there is actually an island there but I wanted to flag it just in case!**

-----

Github user: @ayress97
User: [See in registry](https://www.gbif.org/api/feedback/user/65ca7243fa3ee3975f6b4897c44d643f:1ad6881e705452d224958156f8cd3423c911ed62acdafb1c9131a19f57fc6d0e9749dca4ede1fcfd32fe99c116ad18ce7011681f4c13bd3e9b796d64102ace53)
System: Chrome 96.0.4664 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/1503277367
Window size: width 1440 - height 679
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-06T18:06:30.267Z',to:'2022-03-06T18:12:30.267Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-06T18:06:30.267Z',to:'2022-03-06T18:12:30.267Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: af1b4db0-c8ce-4a95-b700-8a6a02bed9d6
publishingOrgKey: 253fc67c-c7fb-4c85-88f5-43ac6d9dc8a9

Node handles: @albenson-usgs

**Comment by nonenmac** [comment]
It looks like an error in the longitude.  The longitude printed on the herbarium sheet is -82.365383, while the longitude recorded in the occurrence data is -92.3654.  A longitude of -82.3654 would put it in Hernando County, Florida, where it was reportedly collected.

**Comment by ManonGros** [comment]
Contacted publishers by email.

**Comment by AbbyBenson** [comment]
This looks fixed to me. I think this ticket can be closed.
