### ISSUE TITLE
Index Fungorum dataset has 0 accepted taxa at species rank

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal-feedback#397]
http://www.gbif.org/dataset/bf3db7c9-5e5d-4fd0-bd5b-94539eaf9598
http://api.gbif.org/v1/species/search?offset=0&rank=SPECIES&dataset_key=bf3db7c9-5e5d-4fd0-bd5b-94539eaf9598&status=ACCEPTED

However browsing the checklist gives lots of accepted names - at least they should be and are also presented as such in the taxonomybrowser on the species pages. 

Examing these in the API shows that they have no taxonomicStatus: http://api.gbif.org/v1/species/113214856 http://api.gbif.org/v1/species/113212213 etc

**Comment by MattBlissett** [comment]
Index Fungorum is the nomenclatural data, so it doesn't assert any current taxonomic status.

That comes from Species Fungorum.

Therefore, this may well be intentional.
