### ISSUE TITLE
term of use of species photos

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3972]
**term of use of species photos**

Dear Madam or Sir,

Our research group is developing a species genetic diversity database and a web application.

We consider showing an image for each species that is extracted from the species gallery from GBIF. May I ask can we do this and if so, what we should do to properly cite these images?

Thank you very much and I am looking forward to your help!

Best regards,
Haonan

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3d6b285908a6d9526ee6c5083ca8bace:5293807ced11cf37a3c4fba85f306e82c21a88be612ea13f23e2a2dcaa69d89b84caec64b2239231e3baa177e694e1a8fa61c07103dd3194f6f54c18c121952c)
System: Chrome 97.0.4692 / Windows 10.0.0
Referer: https://www.gbif.org/faq
Window size: width 1920 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-10T09:26:37.709Z',to:'2022-03-10T09:32:37.709Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-10T09:26:37.709Z',to:'2022-03-10T09:32:37.709Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

The answer depends on the images you would like to use. I suggest to check the licenses associated with those images and use and cite them accordingly. You can find the license associated with an image by clicking on the occurrence associated with that image.
For example, the image for this occurrence: https://www.gbif.org/occurrence/3424333386 has an “all right reserved” license so you should contact directly the right holder for permission.
While this image license (https://www.gbif.org/occurrence/3455522603) is CC0 so in theory you can use the image without attribution. That being said, attributions are always appreciated.

Attributions should ideally contain a link to the original data, the name of the right holder, and the record/image license. For example:  [Gomphosus caeruleus Lacepède, 1801](https://www.gbif.org/occurrence/3455522603) observed in Egypt by Светлана Царахова (licensed under http://creativecommons.org/publicdomain/zero/1.0/)

More information on how images are shared on GBIF is available [here](https://data-blog.gbif.org/post/gbif-multimedia/).

**Comment by raynoryang** [comment]
Thank you very much for your help!
