### ISSUE TITLE
Misapplied names in Index Fungorum

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal-feedback#398]
It may cause confusion that e.g. the name Cortinarius glaucopus is present twice in the dataset:
As accepted name: www.gbif.org/species/113212676
And as a synonym: www.gbif.org/species/113210421
The latter with no Author or reference to publication. Examing these records in Index Fungorum shows that the synonym is a misapplied (sensu) name used in a certain publication.

In these cases the misapplication authors should be included in the record, prefixed with "sensu":
<MISAPPLICATION_x0020_AUTHORS>
Rea (1922); fide Checklist of Basidiomycota of Great Britain and Ireland (2005)
</MISAPPLICATION_x0020_AUTHORS>

**Comment by mdoering** [comment]
Our copy of Index Fungorum unfortunately is not updated since years. We should get in touch with Kew for a new version with better mappings.

**Comment by ahahn-gbif** [comment]
#397

**Comment by thomasstjerne** [comment]
Ideally, we should have a more dynamic setup with Index Fungorum were updates are crawled say every month or so. 
Index Fungorum is widely accepted as an authoritative source for fungal nomenclature. In the Danish fungal Atlas I see quite some TAXON MATCH NONE issues. These occur when new combinations are pulled and accepted from Index Fungorum into the atlas. This happens frequently, even for common species: https://www.gbif.org/occurrence/search?dataset_key=84d26682-f762-11e1-a439-00145eb45e9a&issue=TAXON_MATCH_NONE&issue=TAXON_MATCH_HIGHERRANK

**Comment by ahahn-gbif** [comment]
@mdoering is better placed to answer this, but backbone building is not part of the routine crawling procedures so far. We can try to negotiate a live connection while we are at it, so that the most recent version is always available, but it will not filter through into the portal at the same rate occurrence datasets can be updated

**Comment by mdoering** [comment]
Andrea is right, but we do rebuild the backbone at least quarterly. Just the copy of IF is stale and years old, probably 10 years now. See http://dev.gbif.org/issues/browse/DM-163

Would be really good to get IF published by Kew on a regular basis

**Comment by ManonGros** [comment]
@mdoering @thomasstjerne Do you know if there has been any discussion with Kew to update Index Fungorum on GBIF?
Let me know, thanks!

**Comment by thomasstjerne** [comment]
From email related to a missing species in Index Fungorum, so I guess some time next year:
> You are correct, the comment is wrong, and it’s origin is unclear. A quick Google find the species is accepted and I have updated IF and SF accordingly. The name will appear in the Catalogue of Life after the next download, which I plan to carry out early in 2021.

**Comment by ManonGros** [comment]
As far as I can see, the data is now correct.
