### ISSUE TITLE
plants of Europe

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3981]
**plants of Europe**

I would like to retrieve a dataset of all plants recorded for Europe. Apparently such a dataset doesn't exist among the GBIF datasets. I was wondering if there is a way to compile such data from the species search? I downloaded all occurrence records of Tracheophyta in Europe, a 55GB dataset that R can't seem to handle (at least on my laptop), and the rgbif package also doesn't have the option of retrieving a species list for a particular continent. Can you help me with this? Best wishes, Richard

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/81026c134897ba1396a79ea3bdb43b77:7d7d455eb83c5b9297fcdc55a8e814d93776e84ac5e8c63c59ab2461de972d5de65941ca0ed0d51f2ce7e9809d77c118a959c91a6ce4ad3f82dcc4cd5e871a0b)
System: Firefox 98.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/search?q=
Window size: width 2497 - height 1327
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-17T09:33:49.224Z',to:'2022-03-17T09:39:49.224Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-17T09:33:49.224Z',to:'2022-03-17T09:39:49.224Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
https://www.gbif.org/occurrence/download/0184485-210914110416597
is a download of the occurrences

Perhaps download the species list instead?
https://www.gbif.org/occurrence/download?continent=EUROPE&taxon_key=7707728&occurrence_status=present
<img width="1438" alt="Screenshot 2022-03-17 at 13 08 58" src="https://user-images.githubusercontent.com/6759267/158805561-f44a5015-8ddb-4466-bb70-9c04bc83f2f8.png">

**Comment by MortenHofft** [comment]
User answered by email
