### ISSUE TITLE
Mapping not completing due to basisofRecord

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3983]
**Mapping not completing due to basisofRecord**

I am trying to upload an occurrence data set, but when mapping to the DWC the BasisofRecord seem to 'block'. I have tried including it in the file, and also deleting it from the file and using the predefined vocabulary instead. None of those worked. Any tips would be helpful. Thank you in advance. Regards, Ida

-----

Github user: @IBDJ
User: [See in registry](https://www.gbif.org/api/feedback/user/fe67716027ee3c4c5bf691c52acafbe5:501349226bb4cb2c81c309264be7a54d0064e93ed08cab7556f7f0a1e6f093e306b360b3748087314b95bc00465c7682fbc0783b5c61f25930d9b6ef2af73981)
System: Chrome 99.0.4844 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=citation
Window size: width 2133 - height 1052
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-18T16:36:46.558Z',to:'2022-03-18T16:42:46.558Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-18T16:36:46.558Z',to:'2022-03-18T16:42:46.558Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi @IBDJ, could you share the dataset that you are trying to publish? If you would rather not upload it to GitHub, you are very welcome to send it to heldpesk@gbif.org.

**Comment by ibdj** [comment]
Hi @ManonGros Sure. Of course. I’ll do one or the other when I get to the office. Thank you in advance.

**Comment by ibdj** [comment]
Hi @ManonGros 

I just sendt an email for you to helpdesk@gbif.org. I tried to send et earlier via the adresse you wrote, but there was a spelling error that I didn't see :)

**Comment by ibdj** [comment]
Hi again @ManonGros Apparently the file is too big to send. I have tried makeing you a link: https://naturinstitut.sharepoint.com/:x:/s/FloraofGreenland/EePqdonunXtFhooX4amS48UBcihnVqADaLZLfmaSO9fNXw?email=mgrosjean%40gbif.org&e=VZVFY7

Let me know if this works or if someone else needs access.

**Comment by ManonGros** [comment]
Thanks @IBDJ so sorry about the spelling mistake! I was able to access the file but I don't think I will have time to check it today. I will get back to you once I had the chance to work on it.

**Comment by ibdj** [comment]
No problem :) 
No, I didn't expect that, thank you in advance. Just let me know when you have had the time to look at it.

**Comment by ibdj** [comment]
Hi @ManonGros Do you have any kind of time frame as to when you/someone might get the time to look at my issue? I am just eager to a move on it :)

**Comment by ManonGros** [comment]
Hi @IBDJ my apologies for the delay, I will look at it today

**Comment by ManonGros** [comment]
Hi again @IBDJ, I published your data on our test system: https://www.gbif-uat.org/occurrence/search?dataset_key=b7bfc3d4-de5e-4e8a-b4a8-bf2689792c7d
In order to do so:
* I used the predefined vocabulary in the IPT for the basis of record
* I deleted one of the records with the occurrenceID `113`. I think the issue with generating the archive had to do with the duplicated occurrenceID (`113`). As the system checks if the data contains unique occurrenceIDs before generating the archive.

Could you try the same on your side and let me know if you still encounter the same issue? Thanks!
