### ISSUE TITLE
Download Options: SIMPLE?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3984]
**Download Options: SIMPLE?**

From a recent interview with a former BIFA participant, one said he couldn't find a format easy to use with Excel.

This makes me wonder, isn't there a "SIMPLE" option? Did he even bother to click the question mark?

For an average user, who has only heard of GBIF and know nothing about text delimiter or TDWG and just want to get a quick list in Excel, perhaps the Download Options card can be a bit more clear to him/her:

1. What is "SIMPLE"? If we don't want he/she to read https://dwc.tdwg.org/simple/ before figuring out what it is, perhaps we should use "SIMPLE (DARWIN CORE) TEXT" or just "SIMPLE TEXT"?
2. Or, since the question marks are all about opening the TSV in Excel, how about replacing the (?) with "Using Excel?" so the visitor doesn't give up?
3. Or, should we offer OpenDocument Spreadsheet .ods so average people can avoid clicking through the importing steps?

-----

Github user: @ckotwn
User: [See in registry](https://www.gbif.org/api/feedback/user/8f0df94e7cde067db9a4c668b3336f20:ac18777ddff6b102a97890549830f04babb638c444881815ce38481d7b2aca7e0183b0f224e7b7d2596988faa3460a15c79ac50ca61989c98b38dc76852894f6)
System: Firefox 98.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/occurrence/download?taxon_key=2864092
Window size: width 1504 - height 1582
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-19T08:30:04.136Z',to:'2022-03-19T08:36:04.136Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-19T08:30:04.136Z',to:'2022-03-19T08:36:04.136Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ckotwn** [comment]
This is somewhat related to https://github.com/gbif/portal-feedback/issues/574 regarding using the download in Excel.

**Comment by MortenHofft** [comment]
Thank you @ckotwn 

@dnoesgaard suggestion 1+2 is textual I think. Let me know if you would like to change anything but cannot. If so feel free to create an issue for it.

Suggestion 3 - new download formats is probably a question for @ahahn-gbif ?

**Comment by dnoesgaard** [comment]
I've amended the text for format to read:

> Tab-delimited CSV (for use in Excel, etc.)
