### ISSUE TITLE
Affilation change

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3985]
**Affilation change**

Please update the affliation for Carlos to [USAID - Global Health Security Division](USAID - Global Health Security Division ) as a Senior Data Advisor

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/8bcdd839604fe93c76417f740b751711:097d2aae235bb8ba1e9f38f477a4560340c79a53d604fed4a07e78cb2a806a3ae298ddbd2b3e401dd25c59db2ea1befb4089eda191ef074a7dd7c2b4d36a2005)
System: Chrome 99.0.4844 / Windows 10.0.0
Referer: https://www.gbif.org/news/j6dXMQP9an4EnREeTT3oi/task-group-to-enhance-gbif-enabled-research-on-species-linked-to-human-diseases
Window size: width 1638 - height 815
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-21T14:44:35.077Z',to:'2022-03-21T14:50:35.077Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-21T14:44:35.077Z',to:'2022-03-21T14:50:35.077Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
[https://www.usaid.gov/global-health/health-areas/global-health-security](url)

**Comment by dnoesgaard** [comment]
Done. Let's not make a habit of trying to keep all details in old news items current. They are intended to be accurate at the time they are published.
