### ISSUE TITLE
UiO Vascular plant herbarium dataset not updating on portal

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#3986]
Our vascular plant herbarium dataset (https://www.gbif.org/dataset/e45c7d91-81c6-4455-86e3-2965a5739b1f) doesn't seem to be showing updates any more on the portal, and I'm not entirely sure why.

The most recent change was made last night, to update the data published in identificationqualifier, and add verbatimidentification, and identificationremarks as new fields. 

This record https://www.gbif.org/occurrence/1701596920, for example, should have some data in these fields, but I can see that it's showing the old data for IdentificationQualifier, and the new fields are not present. Here's the IPT data mapping preview for the same record (it's the 3rd row):

<img width="623" alt="Screenshot 2022-03-22 at 08 46 17" src="https://user-images.githubusercontent.com/9654499/159432920-0d295c86-9967-4f91-b760-ae4dc5ee6789.png">

I tried triggering a crawl using the registry too:
https://registry.gbif.org/dataset/e45c7d91-81c6-4455-86e3-2965a5739b1f

Link to it on our IPT:
https://ipt.gbif.no/resource?r=o_vascular

**Comment by ahahn-gbif** [comment]
I get the same effect; scheduling > 7 days after the last successful run according to the [ingestion history](https://registry.gbif.org/dataset/e45c7d91-81c6-4455-86e3-2965a5739b1f/ingestion-history). The [logs](https://logs.gbif.org/app/discover#/?_g=(time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(level,datasetKey,service,logger_name,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'24993300-fdb1-11ea-93de-b97c40066ce8',key:datasetKey,negate:!f,params:(query:e45c7d91-81c6-4455-86e3-2965a5739b1f),type:phrase),query:(match_phrase:(datasetKey:e45c7d91-81c6-4455-86e3-2965a5739b1f)))),index:'24993300-fdb1-11ea-93de-b97c40066ce8',interval:auto,query:(language:kuery,query:''),sort:!())) show repetitive entries. The last entry in the [ingestion history log](https://registry.gbif.org/dataset/e45c7d91-81c6-4455-86e3-2965a5739b1f/ingestion-history) is from March 15th at this point.

Is this something you could help with, @muttcg?

**Comment by MattBlissett** [comment]
Sorry, it was stuck for some (unclear) reason. I've aborted the stuck ingestion and triggered a new one, which is running now.

The DWCA has validated, so I'm fairly sure this will succeed.

**Comment by rukayaj** [comment]
Great! Thanks :)
