### ISSUE TITLE
missing sub section of treatments from Plazi

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#3993]
in this treatment, the subsection description is missing and the diagnosis is complemented with the caption of the figure in  article.
Also the taxonomic name seems to be mixed up.

https://www.gbif.org/species/194257701

https://treatment.plazi.org/GgServer/html/5AF2FA6B54FB5F259E0A0C499A6FFADF

https://africaninvertebrates.pensoft.net/article/76309/list/7/

![image](https://user-images.githubusercontent.com/4609956/160349206-b4280187-bda3-48bf-904e-2740975d4743.png)

**Comment by thomasstjerne** [comment]
The main issue here is the missing EOL extension that we use to represent treatments in the UI - see https://github.com/gbif/checklistbank/issues/215

In your screenshot the name indeed looks odd - but when I follow the link https://www.gbif.org/species/194257701 it displays correct. Can you please check if the name still looks odd?

**Comment by myrmoteras** [comment]
@thomasstjerne the name looks ok now.

the subsesctions still do not show - you can compare the most recent treatments. https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+doc.gbifTaxonId+doc.articleUuid+doc.articleGbifId+doc.uploadDate+cit.figCitCount&groupingFields=doc.uuid+doc.gbifTaxonId+doc.articleUuid+doc.articleGbifId+doc.uploadDate+cit.figCitCount&FP-doc.gbifTaxonId=1-&FP-doc.uploadDate=%222022-04-10%22-&FP-cit.figCitCount=1-&format=HTML  compare Document UUID with Document GBIF Taxon ID

![image](https://user-images.githubusercontent.com/4609956/163352683-c2381ade-86e0-4e8f-bc17-9d59d6914c48.png)

@gsautter is looking into this from our side
