### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3995]
**Dates**

please update the dates to May according to https://www.nhm.uio.no/english/research/projects/biodata/activities/2022-yerevan.html

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/b59db83379d57e86109bae16c39e53ad:88597c2afb46a257b196cfb621a7512963c907b5e935571625f8f127bb1403e6c950d14a96bf011f7a44f1edecd1b5d3918eb11e0efebf79fe96c25325b1f28e)
System: Chrome 99.0.4844 / Windows 10.0.0
Referer: https://www.gbif.org/event/8dc574-61ef-4468-9b22-1293258/biodata-course-on-data-skills-in-biodiversity-education-and-research-in-yerevan
Window size: width 2048 - height 1019
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-28T12:38:02.033Z',to:'2022-03-28T12:44:02.033Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-28T12:38:02.033Z',to:'2022-03-28T12:44:02.033Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by akristensen** [comment]
Thanks, dates are fixed now but had to unpublish and issue new event so it could sync to the outlook event calendar.
NEW URL is : https://www.gbif.org/event/43qpwu3TvTdePBfDJHRh7J/biodata-course-on-data-skills-in-biodiversity-education-and-research-in-dilijan-armenia
