### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3996]
**Change password**

Hi,

I accidentaly published my password on github. How can I reset it please?

Thank you

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/eb4f9f836b17ad8a529f85e29ea0188f:d0f68bc7cd5e33a7b3c4cfebf7fcbccfc607521fa14613f07612146f0b8fe33a074f7c0450bfc02091ed97bd12f4a27575a6f81628aaff7fe8dbe56e2f3fc3c5)
System: Firefox 98.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/faq?q=password
Window size: width 2560 - height 1326
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-29T06:37:06.929Z',to:'2022-03-29T06:43:06.929Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-29T06:37:06.929Z',to:'2022-03-29T06:43:06.929Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.
