### ISSUE TITLE
Good afternoon. Writing from Kenya. I am trying to validate a dataset but it appears the data validator tool has issues. I upload the file but it seems that the tool  doesn't respond. Kindly assist.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3998]
**Good afternoon. Writing from Kenya. I am trying to validate a dataset but it appears the data validator tool has issues. I upload the file but it seems that the tool doesn&#39;t respond. Kindly assist.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ad662aecbb59d4b96b41abe18118acb4:4007a91e1598094d7a3f943e3faa663756a2c6d14b0171a384eefbfd5e0382e18ca4f478e2fad01ff0279391cf6844b3e00fa82458a2ccee993e61e71c213b33)
System: Chrome 99.0.4844 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator/
Window size: width 1920 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-29T09:33:33.465Z',to:'2022-03-29T09:39:33.465Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-29T09:33:33.465Z',to:'2022-03-29T09:39:33.465Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by EstebanMH-SiB** [comment]
I know that there is not a lot of context in this issue, but I think the problem is when you upload your data to the data validator, it only shows a blank page:
![image](https://user-images.githubusercontent.com/63795703/161356183-80a9177b-89a3-4800-b6df-6b744f05bae4.png)

You need to click the Validation Reports tab and now you can see the result:
![image](https://user-images.githubusercontent.com/63795703/161356228-097290ec-747b-4baf-ae42-72bbc7a4f825.png)

It should redirect to Validation Reports inmediately or maybe show a message telling users to wait for an email with the link.

**Comment by MortenHofft** [comment]
Thank you @EstebanMH-SiB , that doesn't sound ideal. @thomasstjerne it might be worth revisiting the UI with this feedback in mind?

**Comment by ManonGros** [comment]
The user sent me his file (an excel file) and it doesn't validate, even after I converted it to CSV. I was able to publish it in a test mode IPT.
Nikolay confirmed that the validator supports some excellent formats so the issue must be elsewhere. Still looking into it.

**Comment by Lincy77** [comment]
Hello！Do you have help documentation for uploading data to the data validator?  When I use the occurrence data download link (whether it is 'simple' format or 'Darwin core' format), the result is always like below：
![FEZ)N)~ZLWC~`K09E_)0}AR](https://user-images.githubusercontent.com/70764323/161793307-e8234ec3-d641-4192-8003-be08a1cc8bdf.png)

I can
![HJ5C14MT8XMM9@)6O{9{B55](https://user-images.githubusercontent.com/70764323/161793550-bfdd9bff-c511-49cc-8246-8f9cba64be60.png)
 not get help from this description below：

**Comment by Lincy77** [comment]
Hello！Do you have help documentation for uploading data to the data validator?  When I use the occurrence data download link (whether it is 'simple' format or 'Darwin core' format), the result is always like below：
![FEZ)N)~ZLWC~`K09E_)0}AR](https://user-images.githubusercontent.com/70764323/161793307-e8234ec3-d641-4192-8003-be08a1cc8bdf.png)

 I can not get help from this description below：
![HJ5C14MT8XMM9@)6O{9{B55](https://user-images.githubusercontent.com/70764323/161793550-bfdd9bff-c511-49cc-8246-8f9cba64be60.png)

**Comment by muttcg** [comment]
Hi @Lincy77 

I am sorry that you experienced the issue, I did some fixes and tested your xlsx files, so please try again, xlsx files must work now.

P.S Regarding the "downloaded" dwca, the dwca itself is correct, but validator tries to check can the file be indexed or not, so "downloaded" dwca contains 2 occurrences, verbatim and interpreted versions, to make it work you need to delete one extension from the meta.xml description

**Comment by Lincy77** [comment]
thank you! now it is ok!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nikolay ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 下午5:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gbif/portal-feedback] Good afternoon. Writing from Kenya. I am trying to validate a dataset but it appears the data validator tool has issues. I upload the file but it seems that the tool  doesn&#39;t respond. Kindly assist. (Issue #3998)





 
Hi @Lincy77
 I am sorry that you experienced the issue, I did some fixes and tested your xlsx files, so please try again, xlsx files must work now.
 Regarding the "downloaded" dwca, the dwca itself is correct, but validator tries to check can the file be indexed or not, so "downloaded" dwca contains 2 occurrences, verbatim and interpreted versions, to make it work you need to delete one extension from the meta.xml description
