### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4]
**Broken image**

On first page view the image did not show, but on refresh it did.

-----
fbitem-7ff603e5cee85f8d3bb68abe45ba6ebee3872bb4
Reported by: @timrobertson100
System: Chrome 54.0.2840 / Mac OS X 10.11.5
Referer: https://demo.gbif-dev.org/generic/publishing/data-papers
Window size: width 1433 - height 799

**Comment by MortenHofft** [comment]
Difficult to reproduce as it happens sporadically. Goes for both occurrence images and Drupal images. Two weeks ago it happened a lot in the image gallery, today not so. @MattBlissett I'll inform you next time i come across an example.

**Comment by MattBlissett** [comment]
I've upgraded Thumbor, which has either removed some spurious error messages, or fixed some other error.

I'll now wait a further day or two, so there's something in the log files to look at.

**Comment by gbif-portal** [comment]
Closed as duplicate of https://github.com/gbif/portal16/issues/202
