### ISSUE TITLE
search contains

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4000]
**search contains**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e93e808c5b86c7389d680a1772e617fc:b66d7e7d181d36207c9e9c234f420fe3e4d9eb235b841b0bb57f09f2c84c2229fe4e3c0a0dcf2583667ba861c308bffac72fae08edd672fb9c828c4ac89bc4fc)
System: Chrome 99.0.4844 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1249 - height 666
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-29T18:00:45.215Z',to:'2022-03-29T18:06:45.215Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-29T18:00:45.215Z',to:'2022-03-29T18:06:45.215Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jfong** [comment]
How do I search for Locality contains "tomales bay"?  Apologies if this is the wrong place for this. I thought I was searching for help.

**Comment by ManonGros** [comment]
Hi @jfong 
If I understand correctly, you are looking for the occurrence records for which the locality contains "tomales bay"?
The easiest would be to generate a download using our download API and the `like` predicate.

I generated one for you using the following predicate (=filter):
```
{
  "type": "and",
  "predicates": [
    {
      "type": "like",
      "key": "LOCALITY",
      "value": "*tomales bay*",
      "matchCase": false
    },
    {
      "type": "equals",
      "key": "COUNTRY",
      "value": "US",
      "matchCase": false
    }
  ]
}
```
You can access the download here: https://doi.org/10.15468/dl.2uyyym
More information about our download API here: https://www.gbif.org/developer/occurrence#download

Alternatively, you could also use our polygon tool in our web interface to select records with coordinates in the region. For example: https://www.gbif.org/occurrence/map?geometry=POLYGON((-123.00259%2038.25302,-122.99023%2038.23242,-122.9504%2038.18779,-122.90371%2038.13766,-122.84809%2038.07175,-122.81719%2038.07861,-122.81651%2038.10059,-122.85976%2038.13629,-122.90165%2038.18298,-122.9195%2038.22487,-122.94422%2038.24341,-123.00259%2038.25302))&occurrence_status=present

Does it answer your question? Please let me know, thanks!

**Comment by jfong** [comment]
Hi Marie,

This is very helpful, thank you. I was hoping it would be easier to
search with the web interface, but it's good to know that these options
are available.

Best regards,
Jon

*Jon D. Fong*
Curatorial Assistant / Programmer
Dept. of Ichthyology
California Academy of Sciences
p. 415.379.5280
***@***.***
www.calacademy.org

55 Music Concourse Drive
Golden Gate Park
San Francisco, CA 94118

We regenerate the natural world through science, learning, and
collaboration. Learn more at calacademy.org <http://www.calacademy.org/>.

**Comment by timhirsch** [comment]
Jumping in as a busybody observer here, but you can also use the free text box at the top of the occurrence search filters, and https://www.gbif.org/occurrence/search?offset=120&q=tomales&occurrence_status=present gives a pretty good approximation.

**Comment by ManonGros** [comment]
@timhirsch yes but you cannot download data with the free text search

**Comment by timhirsch** [comment]
Good point @ManonGros - I will stop being a busybody.

**Comment by MortenHofft** [comment]
Another busybody here

The `locality` field is a free text field, meaning it is not normalised and requires publishers to fill it. So you will likely miss out on records in the bay. This might be what you want, but a better approach is probably to use a geometry to search (as @ManonGros mentions) for your area of interest. That will also include records that have coordinates, but not filled the `locality`.

Geometry search has 144k results
https://www.gbif.org/occurrence/map?has_geospatial_issue=false&advanced=1&geometry=POLYGON((-123.01019%2038.24184,-122.99097%2038.23696,-122.95301%2038.2017,-122.95278%2038.19333,-122.9401%2038.18855,-122.91057%2038.14982,-122.83172%2038.07391,-122.82075%2038.09051,-122.87414%2038.14396,-122.91857%2038.19994,-122.92041%2038.22302,-122.93337%2038.21738,-122.94812%2038.22679,-122.95701%2038.23826,-122.96804%2038.23606,-122.96503%2038.25451,-123.01019%2038.24184))&occurrence_status=present

but `locality: *tomales bay*` has around 90k results including points that look wrong.

<img width="1365" alt="Screenshot 2022-04-05 at 13 05 10" src="https://user-images.githubusercontent.com/6759267/161741322-886dab29-92fb-4f95-8b84-d7177feeb712.png">

<img width="369" alt="Screenshot 2022-04-05 at 13 10 27" src="https://user-images.githubusercontent.com/6759267/161741439-ac552c14-9c5c-426f-85d4-fc64649eb8e2.png">
