### ISSUE TITLE
bug: event_date filtered downloads not working

### ISSUE THREAD

**Issue by dgasl** [gbif/portal-feedback#4004]
[System health](https://www.gbif.org/system-health) page says "_all systems operational_", but when I try a download some data filtered by event date, I get this error message (red toast message in bottom right corner):
"_The system is currently not able to process your request. Try to refresh the page and please report the issue if it continues._"
Same message for both Simple CSV or Darwincore formats.

Example query:
https://www.gbif.org/occurrence/search?dataset_key=1c334170-7ed1-11df-8c4a-0800200c9a66&event_date=2021-06-21,2021-06-27

If I remove the event_date filter, then it works.

I am trying to download info related to several short field trips.
Is there any other way of filtering records between two start-end days before downloading?

Thanks

**Comment by MortenHofft** [comment]
Thank you for raising that.

The download works fine now. The health page isn't perfect. It checks a number of endpoints, but seems the API was temporarily not functioning in this case. @MattBlissett do you know what was failing and how we could have checked for it?

**Comment by MattBlissett** [comment]
There was a bug and we deployed a fix yesterday afternoon, but Marie/I haven't yet responded to the user reports.
