### ISSUE TITLE
Download resource list?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4007]
**Download resource list?**

On the Resources GBIF pages I can select (for example) all the peer-reviewed journal articles published in calendar year 2021 that have been identified by GBIF as utilising GBIF-mediated data.

There are 2854 results as of today, presented  20 results per page. Scraping from or transcribing from 140 webpages is not a practical option.

Are there download options?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c230a7fde84e3ddc4676e1fc351b8faa:eef0267597c45569abe8821ecf225fc9dfc7730b648c09996a9b2fdbb98c69ad8f5a4bee62dff5ffdd764679e784eea8b1cf16db611e2f53670646d33f1a86e6)
System: Firefox 95.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/resource/search?contentType=literature&year=2021,2021&literatureType=journal&peerReview=true
Window size: width 1384 - height 884
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-05T08:54:04.824Z',to:'2022-04-05T09:00:04.824Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-05T08:54:04.824Z',to:'2022-04-05T09:00:04.824Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
There is no download option, but there is an API https://www.gbif.org/developer/literature - let me know if you aren't sure how to use an API to get the data you need.

> user notified per email
