### ISSUE TITLE
image license and attribution displayed incorrectly

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#401]
**image license and attribution displayed incorrectly**

Not sure if this relates to the specific Wikipedia dataset or is more general, however, the image license (in this case CC BY-SA 3.0) is not shown, nor is the creator attributed. We just show a copyright symbol.

-----
fbitem-species100435300
Reported by: @dnoesgaard
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/species/100435300
Window size: width 1672 - height 908
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-28T09:13:44.068Z',mode:absolute,to:'2017-08-28T09:19:44.068Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-28T09:13:44.068Z',mode:absolute,to:'2017-08-28T09:19:44.068Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
The API seems to return it correctly:
https://api.gbif.org/v1/species/100435300/media?limit=50&media_type=stillImage

**Comment by MortenHofft** [comment]
https://github.com/gbif/portal16/blob/master/app/views/pages/species/key2/speciesImages.nunjucks
It is a lightbox I see and show the rightsholder field even if it is empty
