### ISSUE TITLE
Dowload of DwC Source archive is not available for some lists

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4013]
**Dowload of DwC Source archive is not available for some lists**

Hi, we have a couple of list from this publisher where the option to dowload the source archive is not possible in the portal but in IPT is working properly.

No all lists have this problem, just a couple and we do not know the reason. We should like to know if there is a bug in the portal or maybe something from our IPT that is missing.

Thanks in advance,

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/faaf0d5bf426d8a859fd0914be01c8c8:d3b1ba25f28865f26bae372231f9015f8bcc708813308cc6dc6aea2d5f8847636941d4d9855d7d06bad827bd31bb05678d56e9ac5ee0e59da268d97e0cd58009)
System: Chrome 88.0.4324 / Mac OS X 11.5.1
Referer: https://www.gbif.org/dataset/bb81601d-d838-4007-b863-208d588b4a3b
Window size: width 1920 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-07T20:09:59.778Z',to:'2022-04-07T20:15:59.778Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-07T20:09:59.778Z',to:'2022-04-07T20:15:59.778Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The download option will only show if the dataset has a proper license. In this case it is unspecified, so we do not advertise that it can be downloaded

> User informed per email

**Comment by MattBlissett** [comment]
Marcos fixed the registry issue, and I've reprocessed the EML metadata, so this dataset now has a licence and the download button is shown.
