### ISSUE TITLE
"File can't be validated" unclear

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4015]
**&quot;File can&#39;t be validated&quot; unclear**

When I upload a DWCA to the data validator, all it says is "The file could not be processed, or it may be missing if you provided a URL." This is very unclear. How am I supposed to know what I'm doing wrong?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d1890f21bd9952f449f33a9f9cb7397a:9319322fe7fec4054d66b853e0ba0fda22835727451dae867476e13fe3af94b44f1ad0b54d50125f7a475543fbbce9af4befda8b67aa765dbf0198bb8ef33d35)
System: Chrome 100.0.4896 / Mac OS X 10.15.7
Referer: https://www.gbif.org/tools/data-validator
Window size: width 1226 - height 734
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-08T16:18:51.209Z',to:'2022-04-08T16:24:51.209Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-08T16:18:51.209Z',to:'2022-04-08T16:24:51.209Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by tmcelrath** [comment]
I am uploading a ZIP file of ~65 mB. When unzipped it is around 615 mB. Is this the problem?

**Comment by AbbyBenson** [comment]
Jumping in - I can't really help with the validator but I can help with reviewing a dataset for publishing to GBIF if that would be helpful? I'm the US Node Manager.

**Comment by tmcelrath** [comment]
That would be awesome! Is your contact email still albenson at usgs d0t gov?

**Comment by tmcelrath** [comment]
Able to get around the problem by clicking "Select File" and uploading it there, instead of dragging the file onto the "Drop Here" button. Feel free to close this issue, I'll open another one for improvements to error processing.

**Comment by thomasstjerne** [comment]
Superseded by https://github.com/gbif/portal-feedback/issues/4032
