### ISSUE TITLE
update data papers table

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4016]
**update data papers table**

Please update table to the latest IF, CiteScore, and prices as this page will be needed after 20 april to request quotes for the freshwater actions in GBIF S.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/644fda25241ecdef27e21545ae01dd00:f69c80d5002e3982c8170bce393b8f4513a4d9253df0a78a938546163bd2cb87bf0fcca75c3bbb485ceb957f87af7172f2af92dac5142ce62130f3c2540ea400)
System: Chrome 100.0.4896 / Windows 10.0.0
Referer: https://www.gbif.org/data-papers
Window size: width 1365 - height 631
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-09T08:43:18.027Z',to:'2022-04-09T08:49:18.027Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-09T08:43:18.027Z',to:'2022-04-09T08:49:18.027Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
JIF and CiteScore for 2021 won't be available until June. I've made a few updates to prices...
