### ISSUE TITLE
Suggest using bumblebee as a visual

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4017]
**Suggest using bumblebee as a visual**

For the card on "Accelerating biodiversity research through DNA barcodes, collection and observation data" perhaps you can recycle the Bumblebee on a clover, as on the course cover - as pollination is our "data journey" for this course.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/73855462d07c1206c815548f9d91339a:e93850e16997150f446e356d34a8630602780e160f2d45e6e88c7c8cb532d20464dd4962017e142f5fe83080252c5f0717fc23a6e457a33f998d124dbc21ca4e)
System: Chrome 100.0.4896 / Windows 10.0.0
Referer: https://www.gbif.org/dna
Window size: width 1365 - height 631
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-09T19:31:32.470Z',to:'2022-04-09T19:37:32.470Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-09T19:31:32.470Z',to:'2022-04-09T19:37:32.470Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Done
