### ISSUE TITLE
I have made several attempts to convert a data set into Excel, I have tried to follow the instructions on your website with little success. I was hoping I could receive some advice on this matter please. This is the data set: GBIF.org (07 April 2022) GBIF Occurrence Download  https://doi.org/10.15468/dl.rw48cx

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4018]
**I have made several attempts to convert a data set into Excel, I have tried to follow the instructions on your website with little success. I was hoping I could receive some advice on this matter please. This is the data set: GBIF.org (07 April 2022) GBIF Occurrence Download `https://doi.org/10.15468/dl.rw48cx`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7f0e378ce52f6fbf4b5362fa1f282891:d89327968fca86eb7826582d3512134c2bfb4d705da011238c0b1c497948226e7bed710e4f728a49afc2752eeb0e21982f08051fe2ea84a3d9d3277ea1777963)
System: Chrome 95.0.4638 / Windows 10.0.0
Referer: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
Window size: width 1536 - height 754
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-11T15:11:04.891Z',to:'2022-04-11T15:17:04.891Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-11T15:11:04.891Z',to:'2022-04-11T15:17:04.891Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
In the following I will go through the step by step process to access the data from the download in Excel assuming you use a Windows computer:

1. First download the [dataset](https://www.gbif.org/occurrence/download/0212645-210914110416597) to your computer 
2. Put the zip-folder in a folder where you want to store the data
3. Right-click the folder and choose “Extract all” to unzip the folder
4. Open the file folder to get an overview of the content. 
5. From here, I will show you how to open the “occurrence.txt” file using Excel, however, the other .txt files can be opened in a similar manner.
6. Open Excel and in an empty spreadsheet choose the “Data” tab.
7. Choose the “From Text/CSV” option. 
8. Navigate to the folder where your placed the unzipped folder and the files
9. Click the “occurrence.txt” file and choose import
10. Choose the “Tab” option as Delimiter and press “Load”. The occurrence dataset should now be in distinct columns - however, be aware that most of the columns are empty and perhaps redundant.
