### ISSUE TITLE
Papilio polyxenes is missing from the GBIF backbone | 43,553 occurrences mismatched

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4019]
**Papilio polyxenes is missing from the GBIF backbone | 43,553 occurrences mismatched**

This is an issue originally reported by email.

The name `Papilio polyxenes` is missing from our backbone. This results in many occurrences matched to other species: https://www.gbif.org/occurrence/search?issue=TAXON_MATCH_FUZZY&advanced=1&verbatim_scientific_name=Papilio%20polyxenes

The name `Papilio polyxenes` exists in the ITIS checklist (which is used to build the backbone): https://www.gbif.org/species/101961786. We integrate the subspecies of Papilio polyxenes provided by ITIS but they are put under a wrong species: `Oeneis polixenes`.

It is as if the name `Papilio polyxenes` is fuzzy matched to `Papilio polixenes` during the backbone building and that instead of creating an entry for `Papilio polyxenes`, all the sub species were linked to `Papilio polixenes` (which is incorrectly synonymized with  `Oeneis polixenes`, see this issue: https://github.com/gbif/portal-feedback/issues/2386).

@mdoering @thomasstjerne, could you check whether this is the case? Is there a way to make sure that `Papilio polyxenes` is added in the next backbone update? Thanks!

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/780dc1ca6ecfee7c9e74a1c7ed460ffe:723b97c716498be44b1b750a1039e4622bab05ab8e4b0607869dc878a640f9bbb3c8fbde69d52987770546e097df14df2c9e2c6375b31066273df18752318034)
System: Safari 15.3.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/search?q=Papilio%20polyxenes
Window size: width 1258 - height 849
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-12T08:21:57.314Z',to:'2022-04-12T08:27:57.314Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-12T08:21:57.314Z',to:'2022-04-12T08:27:57.314Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
Weird, it exists in COL: https://www.catalogueoflife.org/data/taxon/4CKMZ

**Comment by kpmcfarland** [comment]
Hi, thanks for posting this. I was the one that reported it via email. It affects a lot of our records and I was just curious when something like this will be addressed in GBIF backbone and occurrences re-indexed?

**Comment by ManonGros** [comment]
It looks like the issue was solved
