### ISSUE TITLE
PANGAEA not longer being indexed?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#402]
**PANGAEA not longer being indexed?**

Is PANGAEA no longer being indexed? For example, dataset https://doi.org/10.1594/PANGAEA.611454 does not seem to be in GBIF.
Some of the PANGAEA datasets in GBIF have seemingly inconsistent metadata, e.g. https://www.gbif.org/dataset/86c75830-f762-11e1-a439-00145eb45e9a#registration says last crawled 1 August 2015 but last modified 18 August 2016. How is this possible?
I'm trying to figure out whether this dataset is missing because PANGAEA don't provide it in a format GBIF can use, or because the endpoint is broken (as suggested by the "last crawled" date.

-----
fbitem-dataset86c75830-f762-11e1-a439-00145eb45e9a
Reported by: @cgendreau
System: Chrome 59.0.3071 / Mac OS X 10.10.5
Referer: https://www.gbif.org/dataset/86c75830-f762-11e1-a439-00145eb45e9a
Window size: width 1440 - height 849
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-28T11:10:00.441Z',mode:absolute,to:'2017-08-28T11:16:00.441Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-28T11:10:00.441Z',mode:absolute,to:'2017-08-28T11:16:00.441Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
Originally reported by @rdmpage
I triggered a crawl manually and 0 records were returned for the dataset.

**Comment by rdmpage** [comment]
Thanks for moving the issue @cgendreau does this mean I should post these sorts of issues here and not in JIRA?

**Comment by cgendreau** [comment]
yes, please, we are trying to move all to GitHub over time.

**Comment by MortenHofft** [comment]
> crawled 1 August 2015 but last modified 18 August 2016. How is this possible?

Because one is crawling of the data and the other one is registry information. So if we update a typo in the title the modification date is updated. I can see how an explanation of those could be informative. We added that info because it might be useful when diagnosing, but perhaps it brings more confusion then information.

And just to confirm that it reflects API data and isn't an interface issue:
https://www.gbif.org/dataset/7e689ac8-f762-11e1-a439-00145eb45e9a
interface:
Last Modification Date 18 August 2016
Last Successful Crawl 3 August 2015

```
//API http://api.gbif.org/v1/dataset/7e689ac8-f762-11e1-a439-00145eb45e9a
"createdBy": "registry-migration.gbif.org",
"modifiedBy": "License Import script",
"created": "2011-04-29T00:06:16.000+0000",
"modified": "2016-08-18T12:32:37.996+0000",

//process API http://api.gbif.org/v1/dataset/7e689ac8-f762-11e1-a439-00145eb45e9a/process
"startedCrawling": "2015-08-01T22:00:00.000+0000",
"finishedCrawling": "2015-08-02T22:00:00.000+0000",
"finishReason": "NORMAL",
"processStateOccurrence": "RUNNING",
"processStateChecklist": "EMPTY",
```

**Comment by rdmpage** [comment]
Thanks for the clarification, I suspected it might be something like this. Which still leaves the problem of why this provider hasn’t been successfully crawled for two years…

**Comment by ManonGros** [comment]
It seems that [111 of PANGEA's datasets have zero occurrence right now](https://www.gbif.org/dataset/search?offset=6924&type=OCCURRENCE&publishing_org=d5778510-eb28-11da-8629-b8a03c50a862). But the [dataset at the origin of this thread](https://www.gbif.org/dataset/86c75830-f762-11e1-a439-00145eb45e9a) is indexed (although only 12,018 were ingested in the last ingestion out of 55,580).

**Comment by MattBlissett** [comment]
Robert at Pangaea is working on them moving from DiGIR to DWCA, https://www.gbif-uat.org/dataset/cef775a7-999f-49f3-b03f-802f1b839b59 is the test so far.

The current DiGIR server is broken and doesn't return any records. For this reason, Pangaea is excluded from the scheduled weekly ingestions. 

Assigning myself, as I'm helping Robert as needed.

**Comment by MattBlissett** [comment]
PANGAEA's migration was completed a couple of months ago, and the original example dataset is now being ingested correctly.

http://api.gbif.org/v1/dataset/doi/10.1594/PANGAEA.611454 shows we don't have the first dataset Rod mentioned, I don't know why that is, probably PANGAEA's decision on what is shared.

**Comment by ManonGros** [comment]
Looks like the issue has been solved.
