### ISSUE TITLE
alternate

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4022]
**alternate**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fae0fe00f12ca010fa283a234a23ba02:b718c31d8dcffc80582ddac0ceb5821d1ab5b94358c4d276898f15cf956a9e631797323fc1bf4884488c58bedda9f22bc01f81329ccd96bdc43534962b423b6d)
System: Chrome 100.0.4896 / Mac OS X 10.15.7
Referer: https://www.gbif.org/user/profile
Window size: width 1440 - height 764
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-14T01:21:22.870Z',to:'2022-04-14T01:27:22.870Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-14T01:21:22.870Z',to:'2022-04-14T01:27:22.870Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by mcruz-umich** [comment]
created by mistake and I cannot find how to delete it - sorry.
