### ISSUE TITLE
Wrong link to Wikipedia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4026]
**Wrong link to Wikipedia**

To whom it may concern,

I have been looking at the page of the species Mesoparapylocheles michaeljacksoni (this is its link: https://www.gbif.org/species/165406902) and I realized that the information from Wikipedia found there comes from the wrong Wikipedia article.

The linked Wikipedia article is "Mesoparapylocheles" (corresponding to the genus Mesoparapylocheles); while the correct thing to do would be to link it to the Wikipedia article titled "Mesoparapylocheles michaeljacksoni" (corresponding to the species Mesoparapylocheles michaeljacksoni).

This is the link to the Wikipedia article that should be linked: https://en.wikipedia.org/wiki/Mesoparapylocheles_michaeljacksoni

Thank you very much in advance for your time.

Yours faithfully,
Teresa Garmendia

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0bf939daf4e6ba458c4bc42f3cfdf9dd:66b38e699acc438c93e49c96ec0463d3cd665d08662046d577b6925b77f7449e4baeae5b356acb6bc89f044f90aa738ca87e722571a552987b493dc249fb25f3)
System: Chrome 100.0.4896 / Windows 10.0.0
Referer: https://www.gbif.org/species/165406902
Window size: width 1280 - height 913
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-18T22:44:32.915Z',to:'2022-04-18T22:50:32.915Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-18T22:44:32.915Z',to:'2022-04-18T22:50:32.915Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
@mdoering 

Perhaps the sources dataset needs to be updated?

**English Wikipedia - Species Pages**
https://www.gbif.org/dataset/cbb6498e-8927-405a-916b-576d00a6289b

**Comment by mdoering** [comment]
The GBIF link given points to the genus, not the species, so the link is perfectly fine.
This is the species in GBIF: https://www.gbif.org/species/194819761
and it does point to https://en.wikipedia.org/wiki/Mesoparapylocheles_michaeljacksoni
