### ISSUE TITLE
Templating failure in dataset generator

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4027]
**Templating failure in dataset generator**

`Species pages extracted from the $LANG Wikipedia article XML dump from $DATE.` this looks a lot like a template that isn't working as intended. @mdoering you are listed as the author, so I've assigned you as a best guess.

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/188951611b7263fdacbbe6e97ce6f28d:f246785eb03bfbeb8002979c97b01e6cb875850a4bee65c2538fb0ef7b9b4230a9718724967854a1b44c727cac93c00520cc0cdd3d52b185e8c8127f3b69ede1)
System: Chrome 100.0.4896 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/cbb6498e-8927-405a-916b-576d00a6289b
Window size: width 1437 - height 765
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-19T07:06:20.469Z',to:'2022-04-19T07:12:20.469Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-19T07:06:20.469Z',to:'2022-04-19T07:12:20.469Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
Code is fixed and archives are rebuilding now

**Comment by mdoering** [comment]
The Spanish one is good now: https://www.gbif.org/dataset/cd9fa1dd-d29f-47c6-bac1-31245a9f08e9
