### ISSUE TITLE
Display hosted occurrences statistics on NA node statistics page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4028]
**Display hosted occurrences statistics on NA node statistics page**

On the North American node page (https://www.gbif.org/the-gbif-network/north-america), the number of occurrences associated with the Symbiota Support Hub is 0 because the 1 publisher that it endorses has "hosted occurrences" rather than "published occurrences". The Symbiota Support Hub Associate Participant does not have any hosted datasets, although it facilitates the hosting of datasets through the Symbiota Support Hub publisher & installations (https://www.gbif.org/publisher/96710dc8-fecb-440d-ae3e-c34ae8a9616f). Could the "hosted occurrences" be included in the count of occurrences on the NA node page, or would this duplicate the statistics listed elsewhere (e.g., the U.S. node)?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e4d403afbc4464c91e9515abfdc073ce:ad90862ea0052957e7467efc4afbeba8ce4a1f82f17c0e1047c48c91168a2e24fe6dc209553c796ed2c146b25b077d6f354477238f76e549a5a3871a19cad8ed)
System: Chrome 100.0.4896 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/96710dc8-fecb-440d-ae3e-c34ae8a9616f
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-19T13:47:33.526Z',to:'2022-04-19T13:53:33.526Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-19T13:47:33.526Z',to:'2022-04-19T13:53:33.526Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by themerekat** [comment]
Posted by me!

**Comment by MortenHofft** [comment]
@themerekat - you can [link your github account to GBIF](https://www.gbif.org/user/profile). It isn't a perfect solution, but it means that we will mention you by your github handle on the issue. It is optional obviously

**Comment by themerekat** [comment]
Thanks, @MortenHofft !
