### ISSUE TITLE
Species authority incorrect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#403]
**Species authority incorrect**

There is no such things as Sitophilus granarius Gyllenhal - most likely it should be Sitophilus granarius Linnaeus.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
Reported by: phil.buckland@umu.se
System: Firefox 55.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/search?taxon_key=8098661
Window size: width 1760 - height 832
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-28T12:35:53.153Z',mode:absolute,to:'2017-08-28T12:41:53.153Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-28T12:35:53.153Z',mode:absolute,to:'2017-08-28T12:41:53.153Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
There are 4 species with different authorities for that name in the backbone which is very likely wrong:
https://www.gbif.org/search?q=Sitophilus%20granarius

Even the main one _Sitophilus granarius (Linnaeus, 1758) Linnaeus, 1758_ has a bad authorship.
All 3 others came from the CoL, but it seems to be fixed in the latest version. So once the backbone is rebuild this should be fixed

**Comment by mdoering** [comment]
Just one version remaining in backbone 2018-01
https://www.gbif.org/species/1170174
