### ISSUE TITLE
error in translation

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4034]
**error in translation**

When viewing this page https://www.gbif.org/species/155117748 in portuguese (https://www.gbif.org/pt/species/155117748), the language of vernacular names are wrongly translated. When the language is "english", it is translated to "portuguese", but should be translated to "inglês". Not sure were to look in the project in Crowdin to correct it, or is it another problem?

-----

Github user: @rpfigueira
User: [See in registry](https://www.gbif.org/api/feedback/user/01851ddd533cf140e2ce427335e67f91:9cf4d93a86e3875bd960423fa43a9632b749a3993942dd3b7a0041b16e36d0bb6db7c18c6a6a49dc8b3c74019163d835ba4183240782755dbc1cec8fb6374f5b)
System: Firefox 98.0.0 / Fedora 0.0.0
Referer: https://www.gbif.org/species/155117748
Window size: width 1920 - height 933
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-22T13:45:45.178Z',to:'2022-04-22T13:51:45.178Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-22T13:45:45.178Z',to:'2022-04-22T13:51:45.178Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
That sounds like a code issue and not a translation issue. Thank you for reporting it

**Comment by MortenHofft** [comment]
I retract that - I see it shows correctly in other languages. I see in your translation file that it says `"eng": "Portuguese",`

https://crowdin.com/translate/gbif-portal/43/en-pt?filter=basic&value=3#q=eng

**Comment by MortenHofft** [comment]
I've updated it in crowdin
