### ISSUE TITLE
Event table paginates by 10, but shows 11 records

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4035]
**Event table paginates by 10, but shows 11 records**

Datasets like https://www.gbif.org/dataset/8a5cbaec-2839-4471-9e1d-98df301095dd have an event table with pagination.

- The first page of the table shows 11 records rather than the likely intended 10 records. Note the last record with Event ID `e8007a9f-f5a9-4809-948d-64cb6537a966`
- The next page of the table jumps 10 records ahead (intended), but since 11 records are shown at a time, the same Event ID `e8007a9f-f5a9-4809-948d-64cb6537a966` now appears at the top.

-----

Github user: @peterdesmet
User: [See in registry](https://www.gbif.org/api/feedback/user/2e477bb04d7f499d6b9825110554c430:ec19824767009f95ff779c5cb4c2601754edcd16cd7f5442291d363f257df4a57447c9e5531a23b2a76fe941d407231d464e5a1c477191008ae53545c15be6a1)
System: Chrome 100.0.4896 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/8a5cbaec-2839-4471-9e1d-98df301095dd
Window size: width 1290 - height 766
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-22T15:36:20.027Z',to:'2022-04-22T15:42:20.027Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-22T15:36:20.027Z',to:'2022-04-22T15:42:20.027Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
That sounds like a UI bug - since we do no really model events, then this is using facets. But facets do not have counts (number of distincts). So to know if we can show a "next" button we ask for 11 and (should) show 10. If there is in fact 11 results, we show a "next" button.

suprising no one has noticed for 4 years

**Comment by peterdesmet** [comment]
Is it possible to also update this in UAT? https://www.gbif-uat.org/dataset/0ef15f32-b41d-4274-ae96-eb5d0059fee6
