### ISSUE TITLE
Issue robot to help send email

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#4039]
For the most part answering issues require sending an email to the user. This is because most users do not have a Github account or haven't linked it to their GBIF account. Often we will also send mails to publishers or dataset owners.

This is fairly time consuming (and boring).
> I think contacting the publishers automatically would be great!
Most of the time I spend on GitHub consists in rephrasing and sending by email the "data content" GitHub issues. It would be great if I could check the issue and send an email to the publisher directly in GH.
>
>_Originally posted by @ManonGros in https://github.com/MortenHofft/issueBot/issues/8#issuecomment-844767502_

One way to make this easier would be a Github robot. E.g. like the one I implemented and tested in [this issue](https://github.com/MortenHofft/issueBot/issues/8#issuecomment-844767502). The idea with that solution was that we in the secretariat could command the robot to send the user or publisher an email, notifying them that there had been relevant activity on the issue.

I'm guessing that it will easily be a couple of days work (email templates, setting it up etc). And then some bug fixing/feature requests/clarifications after that. For example it isn't obvious to me how to send the publisher an email as there could be multiple listed.

@ahahn-gbif your team spend more time than any answering Github issues. What is your thoughts please? Is it at all worth the effort?

**Comment by ManonGros** [comment]
@MortenHofft @ahahn-gbif as much as I like the idea of automated emails from Github, it might not be worth the amount of work. The main reason is that so many of the `data content` issues we receive lately are actually `backbone` issues. We haven't received that many "occurrence" issues the past few months (it seems less than last year or maybe it is just that we have finally made a dent in what we accumulated?)

Anyway, we can't really automate sending emails about backbone issues, it requires a lot of manual checking and investigation to determine what needs to happen and whom to contact.

The other reason is that, as you mentioned Morten, the person to send the email to isn't always obvious.
I imagine that if we were to implement sending emails to publishers that someone logged an issue concerning one of their occurrences, we would probably want to notify the administrative contact.
The problem is that not all administrative contacts have email addresses. I am thinking about the datasets published by the MNHN, where the only contact with an email address is the metadata contact (and it is a generic email address), see this example: https://www.gbif.org/dataset/b5cdf794-8fa4-4a85-8b26-755d087bf531#contacts. And they have a lot of unsolved issues: https://github.com/gbif/portal-feedback/issues?page=1&q=is%3Aissue+is%3Aopen+2cd829bb-b713-433d-99cf-64bef11e5b3e

So in practise it wouldn't help as much as I would hope. Perhaps it isn't worth putting work into it.

**Comment by MattBlissett** [comment]
An encrypted mailto: link to the user's email, to go next to See In Registry, would be all I might use. It saves being logged in to both the registry and the portal.

Redirects to mailto: links work: https://labs.gbif.org/mail

**Comment by ahahn-gbif** [comment]
I agree that mailto: link would be handy. Thanks, @ManonGros for the feedback on the other options!

**Comment by MortenHofft** [comment]
I've created a test issue  - is this usable and should the email template be updated to say something else?
It is currently available in UAT

------

**Test issue**

Hi @manongros - see the email link

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif-uat.org/api/feedback/user/184b1ef66f8a1b5d81c23b4bf07d728f:07388e706022ab9654f3a0e4b8f62be05494df6b7665055d9e33ff4e51b9d8a3596b0bebf9b3af2f8e1def646f50925883ef3aa70b58ecfae4afe7551a0012c04f4f37eed7877d735bd799426f9f9e249b8886542cb8fd418d909982f0775bb9c16dfc2680a0199328ab249f29ab1867e1513fe059c74c318825446aed7e377c) - [Send email](https://www.gbif-uat.org/api/feedback/user/mailto/184b1ef66f8a1b5d81c23b4bf07d728f:07388e706022ab9654f3a0e4b8f62be05494df6b7665055d9e33ff4e51b9d8a3596b0bebf9b3af2f8e1def646f50925883ef3aa70b58ecfae4afe7551a0012c04f4f37eed7877d735bd799426f9f9e249b8886542cb8fd418d909982f0775bb9c16dfc2680a0199328ab249f29ab1867e1513fe059c74c318825446aed7e377c)
System: Chrome 100.0.4896 / Mac OS X 10.15.7
Referer: https://www.gbif-uat.org/data-use/TJK7vSoFUyUrNKevrxyqe/global-assessment-of-the-effects-of-climate-change-on-freshwater-fish
Window size: width 1437 - height 765
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-27T07:31:23.921Z',to:'2022-04-27T07:37:23.921Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-27T07:31:23.921Z',to:'2022-04-27T07:37:23.921Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@MortenHofft I am logged in both GBIF-uat and the registry UAT but I still get an `Internal Server Error` message.

**Comment by MortenHofft** [comment]
> @MortenHofft I am logged in both GBIF-uat and the registry UAT but I still get an `Internal Server Error` message.

you do? when clicking above link "Send email" ?

**Comment by ManonGros** [comment]
Yes by clicking on the "send email"

**Comment by ManonGros** [comment]
Ok so it turns out I was opening the link in a new tab. But If I don't do that, it works!

For the template, could we make a small modification:
> There has been activity on **the message you logged via the GBIF feedback system:** https://github.com/gbif/portal-feedback/issues/4039.
>           
>           You need a Github account to participate in the discussion.
>           Did you know you can link your Github user profile to GBIF?
>           
>           Thanks,
>           GBIF Helpdesk

I assume that the user might not be familiar with GitHub terminology and could be confused by `your issue` wording. Does that make sense?

**Comment by MortenHofft** [comment]
From private chat: the problem is that in Safari when opening a link in a new tab, then the referer (what site you come from) is lost. And the code expects a referer as that is needed for the mail template to tell the user what issue the mail is about.

I cannot fix the Safari behaviour, but I can make it fail nicer.

**Comment by MortenHofft** [comment]
@ManonGros I cannot make html links in the template I’m afraid. Only plain text. That is the constraint of that approach of putting the mail text inside a link mailto

**Comment by ManonGros** [comment]
@MortenHofft I originally pasted the full URL, GitHub interpreted it. No need to have any html link

**Comment by ManonGros** [comment]
@MortenHofft I just used the email button for the first time in real life! This is really convenient.
But I only noticed the subject of the email afterwards `GBIF issue 4060`. Could we replace it by `GBIF Feedback system - ticket 4060` or something like that? (Just to avoid the word "issue" for those who aren't familiar with the GitHub wording).
