### ISSUE TITLE
Update text for NSG on Contacts page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#404]
**Update text for NSG on Contacts page**

The NSG portion of the Contacts page has some slight inconsistencies that I'd like to correct—these are in the translation file, right?

Please correct the header/subheader to read 'Nodes Steering Group'—plural 'Nodes' and initial capital letters for all three words.

Great to have links to the regional views, but please update the text to the following:

> Established in 2011, the Nodes Steering Group (NSG) consists of the chair and vice-chairs of the Participant Node Managers Committee joined by a regional representative from each of GBIF's six regions (Africa, Asia, Europe, Latin America, North America and Oceania). The NSG's objectives are to formulate specific recommendations to relevant GBIF bodies based on feedback provided by Participant nodes, and to provide advice on GBIF's annual work programmes as they relate to the efforts of GBIF nodes.

-----
fbitem-b9a89399d6e22a5a19c7088594ffd8667400a71f
Reported by: @kcopas
System: Safari 10.1.2 / Mac OS X 10.12.6
Referer: https://www.gbif.org/contact-us/directory?group=nsg
Window size: width 1326 - height 734
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-28T13:33:51.701Z',mode:absolute,to:'2017-08-28T13:39:51.701Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-28T13:33:51.701Z',mode:absolute,to:'2017-08-28T13:39:51.701Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Sorry, just realizing that there could/should be an inline link to the nodes committee here. 

> Established in 2011, the Nodes Steering Group (NSG) consists of the chair and vice-chairs of the [Participant Node Managers Committee](https://www.gbif.org/contact-us/directory?group=nodesCommittee) joined…
