### ISSUE TITLE
Edit FAQ - How can I link datasets to my project page?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4041]
**Edit FAQ - How can I link datasets to my project page?**

Would it be possible to add the following sentence to this FAQ?
"Once the project ID has been added to the dataset metadata, don't forget to refresh your Darwin Core Archive, i.e. click on the `publish` button in the IPT."

What do you think @laurarussell @dnoesgaard?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/27f5dd211ef0e21fa94a806d4fb3c911:914d55f3d35534f1f3ef7ffa0a4c3a7092e7fee31392a9420a49871fdd34f4ec1cefcea753bd48ba1391ca02ef1350900e2121963940d96f0eb636e2b4257b9d)
System: Safari 15.3.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/faq?question=how-to-link-datasets-to-my-project-page
Window size: width 1242 - height 847
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-26T13:54:59.490Z',to:'2022-04-26T14:00:59.490Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-04-26T13:54:59.490Z',to:'2022-04-26T14:00:59.490Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by dnoesgaard** [comment]
How about

> (If you add a project ID to an existing dataset in the IPT, don't forget to publish a new version of the resource to refresh the Darwin Core Archive to be ingested by GBIF)

**Comment by ManonGros** [comment]
Yes that's better, thanks @dnoesgaard!
