### ISSUE TITLE
taxonomic name combination error

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#4049]
in this case, the taxonomic name is wrong https://www.gbif.org/species/184010543 

![image](https://user-images.githubusercontent.com/4609956/165503712-cc99814d-01a8-441f-b9be-2b5034fdae92.png)

**Comment by thomasstjerne** [comment]
https://api.gbif.org/v1/species/184010543/name

**Comment by myrmoteras** [comment]
@thomasstjerne does this mean, that the name is wrong in our DWCA?

**Comment by ManonGros** [comment]
@myrmoteras The scientific name provided in the archive is `Nisitrus vittatus (Haan 1844) Haan 1844`: https://www.gbif.org/species/184010543/verbatim
<img width="686" alt="Screenshot 2022-04-27 at 14 17 18" src="https://user-images.githubusercontent.com/7677271/165516330-34fc7dbe-2118-4c9e-bffa-83552099af4e.png">

**Comment by flsimoes** [comment]
Fixed on our side
![image](https://user-images.githubusercontent.com/3343086/165522431-7c329ed6-06fa-400b-912d-a3a1128f9442.png)
https://treatment.plazi.org/id/039487A4FFD3FFB8FD89F26CFD84FCA3?cacheControl=force
