### ISSUE TITLE
Questions / updates to the map view message

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#405]
**Questions / updates to the map view message**

I'd like to propose some tweaks to the message that appears when a user moves from the default tabular view of a search result to the map view. 

Current message is: 
> This map may include records known to have issues. Would you like to apply filters to hide any records with known coordinate issues?

I have some ideas about how to adjust this, but first I need to understand what I'm seeing. The filter that's applied is the 'location: including coordinates' 

Does this mean that the user is choosing whether or not to filter and show only those occurrences that explicitly include coordinates?

-----
fbitem-632937989213bf4e43cb42556216fa1047383e29
Reported by: @kcopas
System: Safari 10.1.2 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false
Window size: width 1326 - height 734
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-28T18:51:16.593Z',mode:absolute,to:'2017-08-28T18:57:16.593Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-28T18:51:16.593Z',mode:absolute,to:'2017-08-28T18:57:16.593Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
No. When you are on the map view it is already filtered to only show occurrences with coordinates.
Some of these may however have coordinate-related issues such as Zero coordinates, suspicious or failed reprojection etc.
So the basic question is: would you like to omit records that do have coordinates, but we know that these coordinates are imprecise or have even more servere errors.

If you see the data from the Danish Mycological Society, this is what you get unfiltered:
https://www.gbif.org/occurrence/map?dataset_key=84d26682-f762-11e1-a439-00145eb45e9a&has_coordinate=true&advanced=1
**Notice the 0,0 records west of Angola.**
They are gone if you chose "yes" in the dialogue box:
https://www.gbif.org/occurrence/map?dataset_key=84d26682-f762-11e1-a439-00145eb45e9a&has_coordinate=true&has_geospatial_issue=false

**Comment by kcopas** [comment]
Great, thanks for the explanation, @thomasstjerne. I think I can take this and come back with a suggestion on text edits later today.

**Comment by kcopas** [comment]
How about this, @thomasstjerne ? Does this explain the mechanism accurately? I think this structures the question more clearly for a 'Yes'/'No' response, but do tell me if you think it still needs work. 

> GBIF’s indexing and processing routines have flagged the coordinates for some records as suspicious. Would you like filter these records from your current map view?
>
> Note: you can always reset the view to see all georeferenced records by going to the ‘Location’ filter and choosing to 'include records where coordinates are flagged as suspicious’.

**Comment by MattBlissett** [comment]
How about changing "yes" and "no" to "show them" and "hide them" or similar? I assume that's straightforward.

**Comment by thomasstjerne** [comment]
Yes @kcopas it is accurate. And I think @MattBlissett ´s suggestion makes it even more clear. So I suggest:

>GBIF’s indexing and quality-check routines have flagged the coordinates for some records as suspicious. Would you like to hide these records from your current map view?
>Note: you can always reset the view to see all georeferenced records by going to the ‘Location’ filter and choosing to 'include records where coordinates are flagged as suspicious’.

And then followed by "Hide them" "Show them" buttons

**Comment by kcopas** [comment]
Hmmm, well, actually, I think the question as now written above leads to a clear yes/no response.

If you feel that it's not clear enough, i'd suggest 
+ Yes - hide them
+ No - show them

But I don't think they're needed.
