### ISSUE TITLE
Delete a duplicated dataset in the portal

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#4054]
We published this dataset in the IPT [Plantas de la Ecoreserva La Tribuna (Neiva, Huila) - Proyecto FIBRAS](https://doi.org/10.15472/p0tfdc), but for some reason it got indexed twice in GBIF. 
- GBIF UUID:[130b6762-42f8-40cd-9f52-a9cd487fdbb1](https://www.gbif.org/dataset/130b6762-42f8-40cd-9f52-a9cd487fdbb1) 
- GBIF UUID:[b7dadc8b-b78f-4e59-aa5d-ba8b13169810](https://www.gbif.org/dataset/b7dadc8b-b78f-4e59-aa5d-ba8b13169810).

We want to delete the dataset with GBIF UUID [b7dadc8b-b78f-4e59-aa5d-ba8b13169810](https://www.gbif.org/dataset/b7dadc8b-b78f-4e59-aa5d-ba8b13169810), because this one have a different UUID from the IPT.

@camiplata @RicardoOrtizG

**Comment by ManonGros** [comment]
Thanks for notifying us @EstebanMH-SiB, I have deleted the duplicate dataset. Let us know if you need anything else.
