### ISSUE TITLE
treatment missing treatments, occurence in treatment article

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#4058]
this recently uploaded treatment article is missing treatmens, material citation and in part of the dashboard

https://www.gbif.org/dataset/be7ce06e-df7d-4a1a-bc53-e4341fa53ee4

https://tb.plazi.org/GgServer/summary/2417FFFCFFD179772A69FFEEFFCAD673

![image](https://user-images.githubusercontent.com/4609956/166916378-d5159e51-110f-4da8-9b08-a8c14ff87f4a.png)

**Comment by gsautter** [comment]
Looks like this was merely a timing issue ... the dataset landing page seems to be OK now.
