### ISSUE TITLE
dataset homepage link intended?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#406]
**dataset homepage link intended?**

Looks like the dataset homepage is added a second time with its full URL accidently?

-----
fbitem-dataset64dabd3c-4f34-4520-b9dd-d227a0bf1582

System: Chrome 60.0.3112 / Mac OS X 10.12.5
Referer: https://www.gbif.org/dataset/64dabd3c-4f34-4520-b9dd-d227a0bf1582
Window size: width 1667 - height 886
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-29T07:27:05.215Z',mode:absolute,to:'2017-08-29T07:33:05.215Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-29T07:27:05.215Z',mode:absolute,to:'2017-08-29T07:33:05.215Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
In this case the description consists of that single link: https://www.gbif.org/api/dataset/64dabd3c-4f34-4520-b9dd-d227a0bf1582
We could contact the publisher and ask for a more detailed one.

**Comment by mdoering** [comment]
;) I did not even consider that, just looked strange. Sorry for bothering

**Comment by thomasstjerne** [comment]
No worries :-)
