### ISSUE TITLE
Question about getting information of filed notes or labels from plant specimens

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4060]
**Question about getting information of filed notes or labels from plant specimens**

Dear GBIF team,

My name is Sebastián Ayala-Ruano, and I'm a research assistant at the Universidad de las Américas in Ecuador. I'm working on a project about using digitalized filed notes or labels from herbarium plant specimens to predict the phenology of plants from Ecuador for conservation purposes. Today, I discovered the GBIF website, and it seems to be perfect for the data collection for our research. However, I have downloaded the CSV files of some searches and realized that there is no column about field notes or descriptions, which is the most important part of our study. Therefore, I would like to know if there is an option to obtain this data using the GBIF website or its API.

Thanks in advance for your support and help.

You can contact me at sebasar1245@gmail.com

Kind regards,

Sebastián

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8f3de317e9a5b4b4b09a79510c5d2f0b:cd14298e28d05fbe174ee291d1bc812efc069e05934974fab3f8c78232e57075eb16a58c021046abc58f1c3d0c402f6022df9bde0540db583a354746ee5e367a4890ad22a7ee403256150619696ccc90ffdf853e439ac5921b50333d6202bae3) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8f3de317e9a5b4b4b09a79510c5d2f0b:cd14298e28d05fbe174ee291d1bc812efc069e05934974fab3f8c78232e57075eb16a58c021046abc58f1c3d0c402f6022df9bde0540db583a354746ee5e367a4890ad22a7ee403256150619696ccc90ffdf853e439ac5921b50333d6202bae3)
System: Firefox 91.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/occurrence/download?taxon_key=3056298
Window size: width 1366 - height 623
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-05T14:57:32.681Z',to:'2022-05-05T15:03:32.681Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-05T14:57:32.681Z',to:'2022-05-05T15:03:32.681Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi Sebastián,

Thank you for contacting us. I suggest select the `DARWIN CORE ARCHIVE` format for your download. This download format will include a file called `verbatim.txt`, which contains more of the field provided by the data publishers. For example: `occurrenceRemarks`, `organismRemarks`, `eventRemarks`, `fieldNotes` and `fieldNumber`.

Here is more information about the formats available and what the `DARWIN CORE ARCHIVE` format contains:

- https://www.gbif.org/faq?question=download-formats
- https://www.gbif.org/faq?question=dwc-download
- https://www.gbif.org/faq?question=what-is-inside-a-gbif-download-zip-file

I will close this issue but don't hesitate to contact us again if you have more questions.
