### ISSUE TITLE
Dataset not indexing on GBIF.org

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4063]
**Dataset not indexing on GBIF.org**

A question has come in through Help Desk where a dataset is not being crawled even though there is no clear reason for why this is - it might be a bug:
-----------------------------------
I published today a [new dataset](https://www.gbif.org/dataset/4eb17049-8b26-43e6-902c-e45884634796) on GBIF.org, but the occurrences do not appear on GBIF.org yet (it's been a few hours since I published it now); I tried [running the archive through the Data Validator](https://www.gbif.org/tools/data-validator/625aee40-2b97-4ecd-aaf4-e4a8b0ffb8b9) and it came out fine except for (what I think are) a few minor flags, so I don't know where the issue could come from (I corrected a forgotten '-' in a contact field of the metadata and tried to publish the whole dataset again, to no avail). 
I tried crawling it directly from the registry but it didn't work either.
This dataset has links to associated pictures but they look ok, I don't know if it could come from this?

I also encounter an issue with [this other dataset](https://www.gbif.org/dataset/7a8bcb65-021a-4c3d-bab8-0844a381f5b1): I tried updating the metadata with a logo but it doesn't appear on GBIF.org whereas it does on [the resource page on our IPT](http://ipt.gbif.fr/resource?r=inrae_bresle_sat). Again, re-publishing the dataset several times did nothing.

Do you have an idea where these issues could come from?
--------------------------------------------
Could you please help with this issue?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0baf5c1549dfe657d2761457a2c173a5:1f8b24697f7c5d8cbeff7d808715d2ddc4f2693fd20ec3ddb8e568dda25f3f922635b74404019ff2ef72047fbdedca3756cd609c0f43f35710798624f0ef9f641abb1dbcfe44546c3413dcb5ece1b700f0d47708644f28f9dcd4e10bb858d348) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0baf5c1549dfe657d2761457a2c173a5:1f8b24697f7c5d8cbeff7d808715d2ddc4f2693fd20ec3ddb8e568dda25f3f922635b74404019ff2ef72047fbdedca3756cd609c0f43f35710798624f0ef9f641abb1dbcfe44546c3413dcb5ece1b700f0d47708644f28f9dcd4e10bb858d348)
System: Firefox 100.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator/625aee40-2b97-4ecd-aaf4-e4a8b0ffb8b9
Window size: width 2560 - height 1287
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-06T09:23:42.481Z',to:'2022-05-06T09:29:42.481Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-06T09:23:42.481Z',to:'2022-05-06T09:29:42.481Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
@muttcg or @fmendezh maybe you can help with this issue?

**Comment by SophiePamerlon** [comment]
Thanks @CecSve for creating this issue for me! I can provide screenshots or other links if necessary.
Best,
Sophie

**Comment by CecSve** [comment]
Hi again @SophiePamerlon - the issue seems to be due to a (very) large data crawl from one of our publishers so it should fix itself. I will check again Monday and see if your dataset + logo has been updated.

**Comment by SophiePamerlon** [comment]
@CecSve Thank you for the explanation, and glad to hear it's not directly linked to these datasets in particular :D I'll check them on Monday!

**Comment by CecSve** [comment]
Data has been ingested and logo has been updated. I therefor close the issue.
