### ISSUE TITLE
这根本不是二尾凤蝶Bhutanitis mansfieldi 而是二尾蛱蝶Polyura narcaea

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4065]
**这根本不是二尾凤蝶Bhutanitis mansfieldi 而是二尾蛱蝶Polyura narcaea**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/eda820afb4142e7226f50516ad70cc8a:521daddf59d8ade4dac6ce9bd13fab09facf98e8c8ca3889f82cc31ddae6e3d30d1fdf4129bbdbe5d2aa1d8400ffee88e53c7d705b51710744ea1aefd620150a8065f11448627cdcd4536f80d501a2f8a2b3e84e16dbe239f5960349bdef318d2403b11c8d094ed649c04065c0916b35f4358724274f229e409b4d3962209e50) - [Send email](https://www.gbif.org/api/feedback/user/mailto/eda820afb4142e7226f50516ad70cc8a:521daddf59d8ade4dac6ce9bd13fab09facf98e8c8ca3889f82cc31ddae6e3d30d1fdf4129bbdbe5d2aa1d8400ffee88e53c7d705b51710744ea1aefd620150a8065f11448627cdcd4536f80d501a2f8a2b3e84e16dbe239f5960349bdef318d2403b11c8d094ed649c04065c0916b35f4358724274f229e409b4d3962209e50)
System: Chrome 101.0.4951 / Windows 10.0.0
Referer: https://www.gbif.org/zh/occurrence/3753787302
Window size: width 1440 - height 767
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-07T10:55:46.370Z',to:'2022-05-07T11:01:46.370Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-07T10:55:46.370Z',to:'2022-05-07T11:01:46.370Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 1b26c417-366a-4eb0-a212-6ee8035d83fb
publishingOrgKey: 1f001218-e6d3-4e97-a129-63475d0dac88

**Comment by MortenHofft** [comment]
> It's not Bhutanitis mansfieldi at all, it's Polyura narcaea

Google translate

**Comment by melissa0520** [comment]
This suggestion was already sent to the publisher(cc with the user).

**Comment by melissa0520** [comment]
The issue is solved by the publisher: https://www.gbif.org/occurrence/3753787302

**Comment by MattBlissett** [comment]
Thanks, Melissa.
