### ISSUE TITLE
Incorrect location: Equatorial Guinea, not Guinea-Bissau

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4067]
**Incorrect location: Equatorial Guinea, not Guinea-Bissau**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6d7a893cf5818cff860a00fe3de3386b:deaff731873d84c86076cd1221770882e5090f9c29efe3f8281995ffff0e25757ac6423eab7d54b28d42e349bfbc6ed4661f058d2aaa7684233ef604321fc109fa9125e67bd3fe70859d83c7a34c2184a630bfc3ca338c659fe113f5f81ece992a8a044a2cc0f93eddb3941b55936fc35400b817b05c1b92b09dfe51341f6d33b2c4ba639f8f8cd0d749ccc9485f6403) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6d7a893cf5818cff860a00fe3de3386b:deaff731873d84c86076cd1221770882e5090f9c29efe3f8281995ffff0e25757ac6423eab7d54b28d42e349bfbc6ed4661f058d2aaa7684233ef604321fc109fa9125e67bd3fe70859d83c7a34c2184a630bfc3ca338c659fe113f5f81ece992a8a044a2cc0f93eddb3941b55936fc35400b817b05c1b92b09dfe51341f6d33b2c4ba639f8f8cd0d749ccc9485f6403)
System: Chrome 100.0.4896 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/29696755
Window size: width 1280 - height 609
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-08T03:17:06.583Z',to:'2022-05-08T03:23:06.583Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-08T03:17:06.583Z',to:'2022-05-08T03:23:06.583Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 834a4794-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 8209258a-80e8-4094-aba2-a3febe5ed45b

**Comment by CecSve** [comment]
The publisher has been contacted and asked to correct the country field.

**Comment by CecSve** [comment]
Should be updated through the next update of the dataset

**Comment by jhnwllr** [comment]
![image](https://github.com/gbif/portal-feedback/assets/4245213/aeb34984-7582-4458-9c16-bca6fb4492cc)
