### ISSUE TITLE
GB29 not showing in Events

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4072]
**GB29 not showing in Events**

I need to refer to a GBIF event page of GB29 in the participation related correspondence, but could not find the event

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/cb645d1b9b40e092c7b983a8ceaa8102:c5762a7d3008a25ca50bf7dda1086f3abe31de2e29645c8b41ede2473527ba244113fc5513211b31ab8fd0eed0f762b07bb10ce1be47717c93edaf2601fcef4556c67740327b74a0f12ee12b0ba4dff9960fd926aa6a829cfbc5b6d7d75938883fa7235469fed097cd9420ad719a1e324062dd641933363b0da6f70709a32e2d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/cb645d1b9b40e092c7b983a8ceaa8102:c5762a7d3008a25ca50bf7dda1086f3abe31de2e29645c8b41ede2473527ba244113fc5513211b31ab8fd0eed0f762b07bb10ce1be47717c93edaf2601fcef4556c67740327b74a0f12ee12b0ba4dff9960fd926aa6a829cfbc5b6d7d75938883fa7235469fed097cd9420ad719a1e324062dd641933363b0da6f70709a32e2d)
System: Chrome 101.0.4951 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?offset=20&contentType=event
Window size: width 1365 - height 679
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-10T10:55:53.185Z',to:'2022-05-10T11:01:53.185Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-10T10:55:53.185Z',to:'2022-05-10T11:01:53.185Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by akristensen** [comment]
To my knowledge Anne Mette and GB29 prep team will have the site ready in JUNE. I will check up with her today.

**Comment by anmnielsen** [comment]
@akristensen @dschigel - Yes, the information and registration site for GB29 will only be up and running mid-June.  If you think it would be useful we can have an event set up now with just information about the dates + location, and saying that the info site will be released in June and GBIF delegates will be notified when it is available.  Would that be an option?

**Comment by dschigel** [comment]
No hurry - I simply went to GBIF Events to double check the GB dates, and found nothing - so flagged it here.
