### ISSUE TITLE
Does the threat parameter in species API query is implemented ?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4075]
**Does the threat parameter in species API query is implemented ?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a68f42e5a83f37b6de3a4633b69ae8f3:ee361ba4411eb8d28858a14882989793c747ce885d6c3ecde500ed02d8903cc1bb24b2e45b120d018006e571d6699706fe7ad90a80eac1bc93a17eb6d5b68b657643d127d1551f1cc81eb47f7183a4307fab6f54739a4221fb89d23cf05e4bdb8f29870eaf7a4120e3cebd2b0ca1a4b949c12809d3129aeac1ec1acdb80685e97bc118b5453b2fe77dbe652fc8dd4866ae3ff33c997e1fc3e40fc4a917cbd81b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a68f42e5a83f37b6de3a4633b69ae8f3:ee361ba4411eb8d28858a14882989793c747ce885d6c3ecde500ed02d8903cc1bb24b2e45b120d018006e571d6699706fe7ad90a80eac1bc93a17eb6d5b68b657643d127d1551f1cc81eb47f7183a4307fab6f54739a4221fb89d23cf05e4bdb8f29870eaf7a4120e3cebd2b0ca1a4b949c12809d3129aeac1ec1acdb80685e97bc118b5453b2fe77dbe652fc8dd4866ae3ff33c997e1fc3e40fc4a917cbd81b)
System: Chrome 100.0.4896 / Windows 10.0.0
Referer: https://www.gbif.org/developer/species
Window size: width 1920 - height 929
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-12T08:33:52.377Z',to:'2022-05-12T08:39:52.377Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-12T08:33:52.377Z',to:'2022-05-12T08:39:52.377Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Seems to work.

Available values https://api.gbif.org/v1/enumeration/basic/ThreatStatus
```
[
"EXTINCT",
"EXTINCT_IN_THE_WILD",
"REGIONALLY_EXTINCT",
"CRITICALLY_ENDANGERED",
"ENDANGERED",
"VULNERABLE",
"NEAR_THREATENED",
"LEAST_CONCERN",
"DATA_DEFICIENT",
"NOT_APPLICABLE",
"NOT_EVALUATED"
]
```

https://api.gbif.org/v1/species/search?threat=VULNERABLE 46521 results
https://api.gbif.org/v1/species/search?threat=NEAR_THREATENED 29765 results

@mdoering should the API be updated to remove the text `Not yet implemented, but will eventually allow for filtering by a threat status enum` ?

> user informed by email

**Comment by mdoering** [comment]
Looks like we should, yes!

**Comment by MortenHofft** [comment]
Great - I've update the documentation and it will be in production shortly.
