### ISSUE TITLE
Greetings sir and madam,  I am Ben Mehrez Mayssem, a research student at the higher institute of management of Tunis.  I am currently doing my master thesis about climate change, im asking you to send me a database about biodiversity (number of species of Europe, The United States, China and Canada). I will be so grateful and thank you very much.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4077]
**Greetings sir and madam, I am Ben Mehrez Mayssem, a research student at the higher institute of management of Tunis. I am currently doing my master thesis about climate change, im asking you to send me a database about biodiversity (number of species of Europe, The United States, China and Canada). I will be so grateful and thank you very much.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d2e8bd1afbd364099e893f718e8f870b:e0651374dafc77fc3cde7c9d6bad6d18e7c4ff46706608e054a4f0a8f6d2e19264e34432a4a8c09632b41ac70deb2f7c1170313f7d4e2a430ee8ad4da57d874bdffc3406acc080431a67a1d271859982b7816773d68646a476f69f0c4e2599a79ed3d74f8c3fe9e63cf04e178d823f77f195d53a16c1b6c6cef9317447a499068e8a36f9109d70415c12e8b78ff23f20) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d2e8bd1afbd364099e893f718e8f870b:e0651374dafc77fc3cde7c9d6bad6d18e7c4ff46706608e054a4f0a8f6d2e19264e34432a4a8c09632b41ac70deb2f7c1170313f7d4e2a430ee8ad4da57d874bdffc3406acc080431a67a1d271859982b7816773d68646a476f69f0c4e2599a79ed3d74f8c3fe9e63cf04e178d823f77f195d53a16c1b6c6cef9317447a499068e8a36f9109d70415c12e8b78ff23f20)
System: Chrome 101.0.4951 / Windows 10.0.0
Referer: https://www.gbif.org/?fbclid=IwAR3f1-GS6JU47L7D1tRfHZ6ihfvbhHgMOF3UIS5ls7qx_X93B5Z_AJwmzmk
Window size: width 1707 - height 781
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-13T21:50:19.217Z',to:'2022-05-13T21:56:19.217Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-13T21:50:19.217Z',to:'2022-05-13T21:56:19.217Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The user also wrote to helpdesk and we answered by email.
