### ISSUE TITLE
geographic coverage map display lacks context

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#408]
**map display**

my data is sample-based in a small area on zealand, denmark. is there a way the initial display of the geographic coverage could be less zoomed so that e.g. the whole of denmark with the study area square on it could be seen?

-----
fbitem-dataset0528c11e-4074-43bb-829f-13b161bd0a56
Reported by: @icalabuig
System: Chrome 60.0.3112 / Windows 7 0.0.0
Referer: https://www.gbif.org/dataset/0528c11e-4074-43bb-829f-13b161bd0a56
Window size: width 2048 - height 1024
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-29T13:11:37.951Z',mode:absolute,to:'2017-08-29T13:17:37.951Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-29T13:11:37.951Z',mode:absolute,to:'2017-08-29T13:17:37.951Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Automatically selecting the best zoom level for all bounding boxes is a bit tricky, but some more padding seems very reasonable. And more importantly a better base map so one can see where in the world you are. Better base maps with more details are coming soon.

**Comment by MortenHofft** [comment]
blocked by https://github.com/gbif/gbif-basemaps/issues/6
