### ISSUE TITLE
Add button to download aggregated statistics on dataset and publisher pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4080]
**Add button to download aggregated statistics on dataset and publisher pages**

Not many publishers know that they can use the API to get and CSV files of aggregated download statistics.
When publishers write to helpdesk, we usually send them API calls like `https://api.gbif.org/v1/occurrence/download/statistics/export?datasetKey=84b18cce-083a-4464-bee8-25b2083a17cd`. But I think some people are intimated by the API. It would be useful if there was a button on the dataset "ACTIVITY" page to download the CSV of the aggregated statistics for that dataset.
There could be something similar on the publisher page (although I am not sure of where this button should be).

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/1141ed018eec8ed1ceff7f7dc01fa938:2eca0526f4025acfee977298974511c8d6128c49d7739487f41f9e43cd3cded464f939b4bea8a2cca5680931ec021cc7f3cc8d6eafecccbbf5a2e865d750659dde21ce718c9e2e9b39f9e736d3becb769956f75c521c88004e476c359c83bf1b7522c3e0f171afd71d1f415f01d5d2ba8f56093d527e997cf6dd9c1b88217a617afc9918cd3b725faeda6ab71c215226) - [Send email](https://www.gbif.org/api/feedback/user/mailto/1141ed018eec8ed1ceff7f7dc01fa938:2eca0526f4025acfee977298974511c8d6128c49d7739487f41f9e43cd3cded464f939b4bea8a2cca5680931ec021cc7f3cc8d6eafecccbbf5a2e865d750659dde21ce718c9e2e9b39f9e736d3becb769956f75c521c88004e476c359c83bf1b7522c3e0f171afd71d1f415f01d5d2ba8f56093d527e997cf6dd9c1b88217a617afc9918cd3b725faeda6ab71c215226)
System: Safari 15.3.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/84b18cce-083a-4464-bee8-25b2083a17cd/activity
Window size: width 1223 - height 826
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-16T07:46:03.868Z',to:'2022-05-16T07:52:03.868Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-16T07:46:03.868Z',to:'2022-05-16T07:52:03.868Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by acbentley** [comment]
Yes, I concur.  Our collection managers routinely have to report this information as part of our annual report statistics that show attribution.  However, I have a number of collection managers that are not API savvy and would like an easy mechanism of getting at these statistics.  It would be great if there could be summary statistics by month, and year that was easily digestible and maybe even presented additionally in a graphical representation similar to the citations graph on this page: https://www.gbif.org/dataset/8f79c802-a58c-447f-99aa-1d6a0790825a/activity. Vertnet is the poster child for providing easily digestible attribution stats as posted here:  http://tools-usagestats.vertnet-portal.appspot.com/reports/8f79c802-a58c-447f-99aa-1d6a0790825a/201901/.  This is what we are looking for.  What is even more frustrating is that each of the aggregators reports different information which makes amalgamating these statistics for reporting even harder.  Collection holding institutions rely on this information as metrics for attribution and advocacy

**Comment by ManonGros** [comment]
@MortenHofft could you take a look at this issue? If not for GBIF.org, perhaps this is something that could be considered for hosted portals?

**Comment by MortenHofft** [comment]
I've added it to the activity tab on dataset pages (I will deploy it to prod later today)
https://www.gbif-uat.org/dataset/8f79c802-a58c-447f-99aa-1d6a0790825a/activity
<img width="453" alt="Screenshot 2022-06-02 at 06 21 57" src="https://user-images.githubusercontent.com/6759267/171552478-b5dad0bf-2429-4074-8636-e359164c8e9d.png">

----

I'm not sure where a good fit would be on publisher pages. Has anyone asked for it @ManonGros ?
I found the API for it https://api.gbif.org/v1/occurrence/download/statistics/export?publishingOrgKey=b554c320-0560-11d8-b851-b8a03c50a862
it returns stats for all datasets that the publisher has published.

**Comment by ManonGros** [comment]
I know that several publishers have contacted us to get this type of information for all their datasets. They didn't specifically ask for a button in the UI though. I think for now having the button on the dataset pages would be a start. Most publishers would probably be able to download everything from the various datasets and combine the information if necessary.

That being said, I will keep an eye on this type of request and let you know if I there is more need for something at the publisher level.

**Comment by acbentley** [comment]
That is great, thanks Morten.  Much appreciated.  We can work with those figures and accumulate them as necessary.

Andy
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V
Andy Bentley
Ichthyology Collection Manager
University of Kansas
Biodiversity Institute
Dyche Hall
1345 Jayhawk Boulevard<x-apple-data-detectors://9/>
Lawrence, KS, 66045-7561<x-apple-data-detectors://9/>
USA<x-apple-data-detectors://9/>

Tel: (785) 864-3863<tel:%28785%29%20864-3863>
Fax: (785) 864-5335<tel:%28785%29%20864-5335>
Email: ***@***.******@***.***>
ORCID: https://orcid.org/0000-0002-3093-1258
http://ichthyology.biodiversity.ku.edu<http://ichthyology.biodiversity.ku.edu/>
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V

**Comment by acbentley** [comment]
It might also be nice to have something a little more proactive to build community.  I used to get an email from Vertnet indicating that stats were available for that month.  Implementing something like this linked to the data manager or other contact might be something to consider in the future to build engagement in the work that GBIF does but also to acknowledge the work of the collections in providing the data.  You could incorporate links to recent citations, etc. to fill it out.

**Comment by CecSve** [comment]
@SophiePamerlon this is the issue I mentioned in the helpdesk email.

**Comment by SophiePamerlon** [comment]
@CecSve Thank you, I confirm that a general button for dl stats about all datasets published by a data publisher is something that could be useful & has been requested by French publishers :)

**Comment by MortenHofft** [comment]
It is now on publisher pages as well. It isn't exactly highlighted, see if you can find it
https://www.gbif.org/publisher/b554c320-0560-11d8-b851-b8a03c50a862

I'm surprised to see that it has more citations than download? @ManonGros doesn't this look odd?

UPDATE:
51,354 for this dataset https://www.gbif.org/dataset/8f79c802-a58c-447f-99aa-1d6a0790825a/activity
1286 for the publisher https://www.gbif.org/publisher/b554c320-0560-11d8-b851-b8a03c50a862

there seem to be an API bug

**Comment by CecSve** [comment]
The 1286 comes from the number of lines (unique datasetKey + month + year combo) in the download report. It should be the sum of downloads (number_downloads) instead.

**Comment by ManonGros** [comment]
Yes it looks like 1286 is not the sum of downloads but the number of entries in the result of this query: https://api.gbif.org/v1/occurrence/download/statistics?publishingOrgKey=b554c320-0560-11d8-b851-b8a03c50a862 (number of lines). I suggest to remove the number `1286`.

**Comment by MortenHofft** [comment]
I did that. It looks weird to say: `download: download report`, so I'm changing the layout a bit and will close this issue as it is now there. It looks a bit odd to be honest, but I will close the issue. Feel free to create a new if there is other changes related to this, but the core functionality of it seem to be there: you can download the reports

**Comment by acbentley** [comment]
That looks awesome.  Thanks for adding that.

Andy
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V
Andy Bentley
Ichthyology Collection Manager
University of Kansas
Biodiversity Institute
Dyche Hall
1345 Jayhawk Boulevard<x-apple-data-detectors://9/>
Lawrence, KS, 66045-7561<x-apple-data-detectors://9/>
USA<x-apple-data-detectors://9/>

Tel: (785) 864-3863<tel:%28785%29%20864-3863>
Fax: (785) 864-5335<tel:%28785%29%20864-5335>
Email: ***@***.******@***.***>
ORCID: https://orcid.org/0000-0002-3093-1258
http://ichthyology.biodiversity.ku.edu<http://ichthyology.biodiversity.ku.edu/>
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V
