### ISSUE TITLE
alphanumric requirement in the Event form

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4085]
**alphanumric requirement in the Event form**

I tried to submit the event description text but the following did not pass the alphanumeric requirements:

"Turning the Internet into a meaningful data space. Successful management, exchange and interpretation of knowledge in an ever-growing information tsunami will depend on highly automated methods dealing with combined data. This will require artificial intelligence but also robust and informative ways to store and disseminate data and metadata. Here is where one crucial concept shows up: FAIR Digital Objects (FDOs). FAIR is about making data findable, accessible, interoperable and reusable both for humans and machines. FAIR digital objects have shown key capabilities to simplify and scale the use of data across domains, increase trust in data and ease the handling of high volumes of information. The developments are there. Now we need widespread consensus."

Looks alphanumeric to me.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/c5e06d42356fd92183d173fa628f7703:b92dcf6e050698ff04a1600bc554355ea065da73411854977554889e9248e935d1e48da5d6dbc0d6f1d25c6684884589dcb002af92e0ce9b41c15129ecd8129e6d24f0c80948f151a0b40ac680a4a0f6e8d4e0cb0ed493acb93382278138ec5e6b7d12fb88e9d6a301b75e787768ef7792eeeff7f5feca8fb2086af7eed1d7ab) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c5e06d42356fd92183d173fa628f7703:b92dcf6e050698ff04a1600bc554355ea065da73411854977554889e9248e935d1e48da5d6dbc0d6f1d25c6684884589dcb002af92e0ce9b41c15129ecd8129e6d24f0c80948f151a0b40ac680a4a0f6e8d4e0cb0ed493acb93382278138ec5e6b7d12fb88e9d6a301b75e787768ef7792eeeff7f5feca8fb2086af7eed1d7ab)
System: Chrome 101.0.4951 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?offset=20&contentType=event
Window size: width 1365 - height 679
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-17T12:22:43.740Z',to:'2022-05-17T12:28:43.740Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-17T12:22:43.740Z',to:'2022-05-17T12:28:43.740Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thanks @dschigel 
I need a bit more context. What do you mean submit?
Did you do [a search](https://www.gbif.org/resource/search?q=Turning%20the%20Internet%20into%20a%20meaningful%20data%20space.%20Successful%20management,%20exchange%20and%20interpretation%20of%20knowledge%20in%20an%20ever-growing%20information%20tsunami%20will%20depend%20on%20highly%20automated%20methods%20dealing%20with%20combined%20data.%20This%20will%20require%20artificial%20intelligence%20but%20also%20robust%20and%20informative%20ways%20to%20store%20and%20disseminate%20data%20and%20metadata.%20Here%20is%20where%20one%20crucial%20concept%20shows%20up:%20FAIR%20Digital%20Objects%20(FDOs).%20FAIR%20is%20about%20making%20data%20findable,%20accessible,%20interoperable%20and%20reusable%20both%20for%20humans%20and%20machines.%20FAIR%20digital%20objects%20have%20shown%20key%20capabilities%20to%20simplify%20and%20scale%20the%20use%20of%20data%20across%20domains,%20increase%20trust%20in%20data%20and%20ease%20the%20handling%20of%20high%20volumes%20of%20information.%20The%20developments%20are%20there.%20Now%20we%20need%20widespread%20consensus.&contentType=event) for that text? Where is it you got that feedback about "alphanumeric requirements"? 

Is this related to the website or are we talking about another piece of software? Is it Contentful?

**Comment by dschigel** [comment]
PLease try suggesting an Event from https://www.gbif.org/resource/search?offset=20&contentType=event and use my text for decription (taken from the event's website). This is a Google form that is linked from GBIF.org, maybe @akristensen knowns more

**Comment by MortenHofft** [comment]
Thank you. So it is related to the Google form linked to from https://www.gbif.org/suggest-event
Let us hope @akristensen knows more

**Comment by akristensen** [comment]
@dnoesgaard apparently there is a small bug in the form, see Dmitry's comments above.....

I think it is because there is a max. amount of text you can add to this box....maybe we can specify how many characters can be used for the description?

**Comment by dschigel** [comment]
At the same type I heard @kcopas requesting better event descriptions - which is not necesserily contradiction with a charachter limit, likely on the contrary, but just a flag anyhow

**Comment by kcopas** [comment]
Yeah, not really the same point.

**Comment by akristensen** [comment]
I agree about the lack of description Dmitry. This was meant as an information to Daniel, as it seems to be the character limit that has caused the block you have experienced.

**Comment by dnoesgaard** [comment]
There was a filter on which characters were allowed in the description to avoid problems with the code. I've removed this filter now and instead encoded the field. I've instructed @akristensen on how to deal with this moving forward.
