### ISSUE TITLE
Identifier in exponential notation

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4088]
**Identifier in exponential notation**

The multimedia identifier for this occurrence is displayed in exponential notation https://collections.nmnh.si.edu/media/?i=1.00692e+07 This may be a bug in the originally source where a string has been interpreted as a number.

-----

Github user: @rdmpage
User: [See in registry](https://www.gbif.org/api/feedback/user/2f224c413cb0c0e79a7e90ce3c19468d:dc7ae8d6e91896d1b0c82dec71903679182f450e2aba3fccd2cebe7db7a71dc14f29520813e2da155804b993885d9fc004bb329804bd4b1d541aa59d3a9ab42efa53120e5113889ef9f6e85de6227391be3912344d35d038f5657d307750972d62758df2feb7fb14f924a01d8e4ffcb79063dcb2b3a68f9be07623dfb2a35c1f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2f224c413cb0c0e79a7e90ce3c19468d:dc7ae8d6e91896d1b0c82dec71903679182f450e2aba3fccd2cebe7db7a71dc14f29520813e2da155804b993885d9fc004bb329804bd4b1d541aa59d3a9ab42efa53120e5113889ef9f6e85de6227391be3912344d35d038f5657d307750972d62758df2feb7fb14f924a01d8e4ffcb79063dcb2b3a68f9be07623dfb2a35c1f)
System: Safari 14.1.2 / Mac OS X 10.14.6
Referer: https://www.gbif.org/occurrence/1319088685
Window size: width 1185 - height 875
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-18T22:59:03.779Z',to:'2022-05-18T23:05:03.779Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-18T22:59:03.779Z',to:'2022-05-18T23:05:03.779Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 821cc27a-e3bb-4bc5-ac34-89ada245069d
publishingOrgKey: bc092ff0-02e4-11dc-991f-b8a03c50a862
Network keys: 99d66b6c-9087-452f-a9d4-f15f2c2d0e7e 
Node handles: @albenson-usgs

**Comment by timrobertson100** [comment]
I saw the tweet and have written to the publisher CCing helpdesk before I found this GH issue

**Comment by rdmpage** [comment]
Thanks Tim, I meant to add this issue to the tweet but, as usual, got distracted by the next shiny thing...

**Comment by AbbyBenson** [comment]
I think this can be closed. Looks resolved to me.
