### ISSUE TITLE
Map API examples: page 400 error?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4089]
**Map API exxamples: page 400 error?**

The example URLs given for the map API look as though they should work from a browser URL. I just get a page displaying a large red "400" though (Bad Request Error). Is there any change needed, or are there known problems?

Tested on three browsers (Firefox, Chrome, Edge) with the same result.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d0c2d09d6db68eb41e5f8f256bb7a4b4:6d189f625adc4ded41bd3a968e4a5646734dcd967d1df2cc888a2facd2770f2ac9b4c2bf70a4af43b304459d617f59b44040c30ed59f4250acab50fd3ad27655194fd71188f65c587adf08aa7fb2a47dbf38247edfe2edc4a477d81c48353749a1e57bb5e66a127319dedfc81063c31e046b78388d4c2f3e7a774bd0d33e9b68) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d0c2d09d6db68eb41e5f8f256bb7a4b4:6d189f625adc4ded41bd3a968e4a5646734dcd967d1df2cc888a2facd2770f2ac9b4c2bf70a4af43b304459d617f59b44040c30ed59f4250acab50fd3ad27655194fd71188f65c587adf08aa7fb2a47dbf38247edfe2edc4a477d81c48353749a1e57bb5e66a127319dedfc81063c31e046b78388d4c2f3e7a774bd0d33e9b68)
System: Firefox 100.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/developer/maps
Window size: width 1461 - height 643
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-19T08:18:58.296Z',to:'2022-05-19T08:24:58.296Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-19T08:18:58.296Z',to:'2022-05-19T08:24:58.296Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Do you mean the URLs like `https://api.gbif.org/v2/map/occurrence/density/{z}/{x}/{y}@1x.png?style=purpleYellow.point`? The `{z}/{x}/{y}` needs to be replaced with a valid coordinate, like `0/0/0`.

They are shown like this as it is the format for using them in OpenLayers, Mapbox, Leaflet etc.

**Comment by ahahn-gbif** [comment]
Ouch! Thanks! I assumed they directly related to the snapshot to the right - all good, closing.
