### ISSUE TITLE
Remove duplicate dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4093]
**Remove duplicate dataset**

The dataset 

"Crustacea collection of the Finnish Museum of Natural History"  https://doi.org/10.15468/8cse43 

is now fully contained as part of the dataset 

"Invertebrata varia (Luomus)" 10.15468/h37nwv

I am the administrative point of contact for both datasets.

Please could the first dataset be removed to avoid duplication.

thank you

Risto Väinölä, Senior Curator, Finnish Museum of Natural History Luomus

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/54e415dcf6702a9c477f0c915b0b4e44:e76024fe8a3c671c79eaa0abe6dc2050a35e4ff4977a13866551d1a1178a8bc30bb62a69fa4f7b617851c1e49ee6e4d6651ba7abf815af6f2213ded31e48af801e6ab7372dab01833d7eb8845fdede191e1f357e92c8aaf918d1b34cee2463d4) - [Send email](https://www.gbif.org/api/feedback/user/mailto/54e415dcf6702a9c477f0c915b0b4e44:e76024fe8a3c671c79eaa0abe6dc2050a35e4ff4977a13866551d1a1178a8bc30bb62a69fa4f7b617851c1e49ee6e4d6651ba7abf815af6f2213ded31e48af801e6ab7372dab01833d7eb8845fdede191e1f357e92c8aaf918d1b34cee2463d4)
System: Chrome 101.0.4951 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/96313a17-ea7a-471b-978b-a86d15bd4d6f
Window size: width 1707 - height 802
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-21T08:10:50.763Z',to:'2022-05-21T08:16:50.763Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-21T08:10:50.763Z',to:'2022-05-21T08:16:50.763Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Dataset deleted and use notified.
