### ISSUE TITLE
Deleted occurrence from a valid research-grade observation from iNaturalist

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4094]
**Deleted occurrence from a valid research-grade observation from iNaturalist**

Hello, is it possible to know why this occurrence was deleted on GBIF.org, whereas it's still available on iNaturalist as a research-grade observation? (see https://www.inaturalist.org/observations/67484466 ). Its addition to iNat dates back to early 2021 so it probably isn't an issue with it being too recent to be indexed yet?
Thank you for your help as always :)
Sophie

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/31e3e597250c14764f027a8e83b86df9:dbbd271f2279bd6cf92dac62302015c05c772b3cf3fc17a8a2348b38811012c9ee8c0ef90bc9fb5fdb34c61c9e4a65b5423603ec909e4fe903e3905b7c08dcc3c13ea28041fc7ae42b3b138096526f5e5e400c45afc658fbea30ce4350e1164f52aa73bad8e2061c94c3b230579742868049072290da415d23cb8a05008ed50d690b49ad979fb81e467a03236a5b430e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/31e3e597250c14764f027a8e83b86df9:dbbd271f2279bd6cf92dac62302015c05c772b3cf3fc17a8a2348b38811012c9ee8c0ef90bc9fb5fdb34c61c9e4a65b5423603ec909e4fe903e3905b7c08dcc3c13ea28041fc7ae42b3b138096526f5e5e400c45afc658fbea30ce4350e1164f52aa73bad8e2061c94c3b230579742868049072290da415d23cb8a05008ed50d690b49ad979fb81e467a03236a5b430e)
System: Firefox 100.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/3018027853/fragment
Window size: width 1185 - height 643
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-23T11:44:37.419Z',to:'2022-05-23T11:50:37.419Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-23T11:44:37.419Z',to:'2022-05-23T11:50:37.419Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
@muttcg - @jhnwllr and I cannot figure this out. The occurrence is licensed correctly (BY-NC) and it received the research grade a year ago but it seems to be deleted by iNaturalist although iNaturalist link to the GBIF occurrence.. do you know what might be going on? We tried to find the occurrences (maybe a dead link), but it seems like it is really missing

**Comment by CecSve** [comment]
The occurrence is now back in GBIF: https://www.gbif.org/occurrence/3018027853.
