### ISSUE TITLE
Show coordinateUncertainty on map

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4096]
**Show coordinateUncertainty on map**

On occurrence pages, I think it would be useful to visualize the `coordinateUncertaintyInMeters` as a circle on the map. It helps to understand the occurrence in the context of its location and its a better representation of where an occurrence was observed/collected. Currently too much attention goes to the center, while it can actually be anywhere in the circle.

We do this on the RIPARIAS early alert site: https://alert.riparias.be/observation/a26299f03e0e026b40f950f430e840d5a3551eec

vs

GBIF: https://www.gbif.org/occurrence/1569866192

Notes:

- The circle should not be opaque, so that the base layer is still visible
- To not show the center (see argument above)

-----

Github user: @peterdesmet
User: [See in registry](https://www.gbif.org/api/feedback/user/7fdbb761d8ff2362a1cf322eb916799c:68402dfb906dc57f0979c86f127af19ebc523026c0d5c8e7b02f44052f4dbc2f4b6fab45912cbf74f037b38c70cef4b04dcc07cbe05c53a82f787a0765306d0a3cba67eed0be91f68df852b07345456e1a8c5a6f75dc1bbcec687ba86232738a5f60f78d4275c00baf007af2424708491a48b7f2ccd91e8a9cf7f8a168dcdb3170b28a487458264a5862d47f06440d29) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7fdbb761d8ff2362a1cf322eb916799c:68402dfb906dc57f0979c86f127af19ebc523026c0d5c8e7b02f44052f4dbc2f4b6fab45912cbf74f037b38c70cef4b04dcc07cbe05c53a82f787a0765306d0a3cba67eed0be91f68df852b07345456e1a8c5a6f75dc1bbcec687ba86232738a5f60f78d4275c00baf007af2424708491a48b7f2ccd91e8a9cf7f8a168dcdb3170b28a487458264a5862d47f06440d29)
System: Chrome 101.0.4951 / Mac OS X 10.14.6
Referer: https://www.gbif.org/occurrence/1569866192
Window size: width 1312 - height 707
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-24T10:00:45.906Z',to:'2022-05-24T10:06:45.906Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-24T10:00:45.906Z',to:'2022-05-24T10:06:45.906Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7f5e4129-0717-428e-876a-464fbd5d9a47
publishingOrgKey: 4d3ceea8-5699-439d-a899-decac9cbbdac
Network keys: b153643d-735a-440f-a0e9-428b4f9d1cd2

**Comment by MortenHofft** [comment]
Thanks
We do show the uncertainty normally
e.g. https://www.gbif.org/occurrence/3424493344

I'm not sure why it isn't shown in the case above. Perhaps because it is so relatively small (10m)

**Comment by peterdesmet** [comment]
Oh cool! Is there indeed a cutoff at which point it is no longer show?

**Comment by MortenHofft** [comment]
https://github.com/gbif/portal16/blame/master/app/views/pages/occurrence/key/occurrenceKey.ctrl.js#L160
yes there seem to be. I added that in the first version 7 years ago. I will remove it, or perhaps set the cutoff to something less
