### ISSUE TITLE
GRIIS list now showing at country page for .bg

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4097]
**GRIIS list now showing at country page for .bg**

This https://www.gbif.org/dataset/d015d9e7-9eed-47c6-a0cd-62c627ad1e8b I beleive should be linked fomr the country page? I will show a standalone dataset in the ministry tomorrow, but I think we need to fix this. Perhaps there are other no-display cases for the GRIIS datasets?

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/c68ccb36177afa29b56a983ff4acd9b4:c9a5482dfeca0d3efac996d474d7dc226059e7073c43eded8020456e328f7b8bd08f3df2c3d92b243a2add28bbe4fc7bccd4f83ae76d4a0cd9cbeb9017f0a9f997f398a87d9d3c4ca9b03643615db90dc78dd098a17a18027a8cabfdc2c4d0aa0f0e15242a2f5ce1c64ae8f861b63ba9aacd47f40326bf1860a21d32f6e15f0b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c68ccb36177afa29b56a983ff4acd9b4:c9a5482dfeca0d3efac996d474d7dc226059e7073c43eded8020456e328f7b8bd08f3df2c3d92b243a2add28bbe4fc7bccd4f83ae76d4a0cd9cbeb9017f0a9f997f398a87d9d3c4ca9b03643615db90dc78dd098a17a18027a8cabfdc2c4d0aa0f0e15242a2f5ce1c64ae8f861b63ba9aacd47f40326bf1860a21d32f6e15f0b)
System: Chrome 101.0.4951 / Windows 10.0.0
Referer: https://www.gbif.org/country/BG/summary
Window size: width 2560 - height 1262
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-25T12:21:17.812Z',to:'2022-05-25T12:27:17.812Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-25T12:21:17.812Z',to:'2022-05-25T12:27:17.812Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by dschigel** [comment]
Also, in case it matters with the discussions with the IT of CBD with @timhirsch, the list is not linked from the CBD party page https://www.cbd.int/countries/ias/?country=BG

**Comment by dschigel** [comment]
Also, clicking Taxonomy from this dataset does not show the pie chart, but links to Animalia in backbone and "back" button does not send you back anymore... looks like a bunch of issues here

**Comment by ahahn-gbif** [comment]
As Matt points out, the base reason is that the keyword in the dataset metadata is using the wrong spelling (Country_BG instead of country_BG). Notified Shyama and hoping for a fix to be applied soon.

**Comment by MattBlissett** [comment]
Antarctica and the Saint Helena datasets also have this problem (Country_AQ, Country_SH-TA, Country_SH-AC, Country_SH-HL).

I'm not sure the taxonomy button is doing anything wrong (except the back button problem), but I can't remember. Did you mean to use the Metrics button?

**Comment by dschigel** [comment]
Thanks for picking the case; @MattBlissett there is no Metrics button on the GRIIS dataset, only Taxonomy which does not show me the pie chart I need

**Comment by ahahn-gbif** [comment]
I would expect this in the metrics tab, as in this case for Togo: https://www.gbif.org/dataset/bd5ac264-bc88-4ee8-8fbb-e16247e1119c/metrics

**Comment by dschigel** [comment]
Me too, but compare to https://www.gbif.org/es/dataset/d015d9e7-9eed-47c6-a0cd-62c627ad1e8b

**Comment by ahahn-gbif** [comment]
seems to be ok now: https://www.gbif.org/es/dataset/d015d9e7-9eed-47c6-a0cd-62c627ad1e8b/metrics

**Comment by MortenHofft** [comment]
I'm not sure why the metrics tab wasn't showing, perhaps there was an API outage or the data wasn't indexed yet?

The back button issue I understand it was introduce recently
https://github.com/gbif/portal16/commit/9267479e9b92668fe8dd4b75609762db47faad0d

**Comment by MortenHofft** [comment]
Am I correct in closing this @dschigel ? It seems there is no issues after all except the back button which I have just fixed. If I misunderstand then please reopen.
