### ISSUE TITLE
download broken

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4098]
**download broken**

have tried to download 777K+ records from US three times today and no go. Latest is:
https://www.gbif.org/occurrence/download/0309200-210914110416597

Can you help?

Annie Simpson
asimpson@usg.gov

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7667978df53df7dcc87b4cf9eb35ad53:9e1ba7f42a6fac1889fb9e05001eeb32eb9ec4c423cd80d1a8115aa1d5482f77878110353f32dd806099270cc8289ae03465db083a236fa3326927245aede9990674966f6c0086ca2ef804b3c983c5a85f58e4589c5b4a723d98a6ae9723db8a539ac2f908b90b92808d820da172289ec8961c2904535beac5e5cebfe787f085) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7667978df53df7dcc87b4cf9eb35ad53:9e1ba7f42a6fac1889fb9e05001eeb32eb9ec4c423cd80d1a8115aa1d5482f77878110353f32dd806099270cc8289ae03465db083a236fa3326927245aede9990674966f6c0086ca2ef804b3c983c5a85f58e4589c5b4a723d98a6ae9723db8a539ac2f908b90b92808d820da172289ec8961c2904535beac5e5cebfe787f085)
System: Firefox 91.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/occurrence/download/0309200-210914110416597
Window size: width 1420 - height 752
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-25T16:50:28.714Z',to:'2022-05-25T16:56:28.714Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-25T16:50:28.714Z',to:'2022-05-25T16:56:28.714Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by asimpson-usgs** [comment]
Tried again today; a different smaller download had no issue:
Download Information
DOI: [https://doi.org/10.15468/dl.5xjkpc](https://doi.org/10.15468/dl.5xjkpc)
Creation Date: 13:59:59 26 May 2022 
Records included: 1413 records from 2 published datasets 

Am trying again with establishmentMeans=introduced but adding parameters to make it very small.

**Comment by asimpson-usgs** [comment]
Tried this search, 100+ records, with establishmentMeans = introduced, species = Alliaria petiolata, for US:
GBIF.org (26 May 2022) GBIF Occurrence Download  [https://doi.org/10.15468/dl.cfqpx5](https://doi.org/10.15468/dl.cfqpx5)
and it came through with no problem.
So my assumption is that the issue may be related to the size of the download. Do I need special permission to download 777K+ records?

**Comment by asimpson-usgs** [comment]
Download key: 0313290-210914110416597
Latest failure is for download request that is equal in every way to the successful request except scientificName specified (which made download small):
GBIF.org (26 May 2022) GBIF Occurrence Download  [https://doi.org/10.15468/dl.ahzsh5](https://doi.org/10.15468/dl.ahzsh5)
So I have to conclude this is a 'request exceeds maximum allowed download size' issue. If this is correct, could someone at GBIF please do this download for me and send me the link? (Or provide me with other guidance.) Kind regards, Annie

**Comment by MattBlissett** [comment]
Sorry Annie, I forgot to reply to this on Friday.

The problem was on our side, where the "IN" query didn't work correctly on the new, vocabulary-aligned establishmentMeans term ("equals" did).  It should work now.
