### ISSUE TITLE
Is there a lookup table for GADM data?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4099]
**Is there a lookup table for GADM data?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ef2fcf1e2b9bae9f7e60521fa268ec04:fbfc8c5f2211e202c6ad83efd7b6f52137c956ee304b57f9c55e9518d40bc813869e34a26cda2515c704375d299ba156f5df17a3788be3272dc09e3796c7e76d2ffcf857268620f1cc83856cb9d30f2676b015a4fcb834d8cd44db673e0a9ffddcec33b4f980b5ea00c2eb68a9a0da7483efcb39db53856577fb56f24ee94b5be578a29468cf87af28fe8e45c69b861f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ef2fcf1e2b9bae9f7e60521fa268ec04:fbfc8c5f2211e202c6ad83efd7b6f52137c956ee304b57f9c55e9518d40bc813869e34a26cda2515c704375d299ba156f5df17a3788be3272dc09e3796c7e76d2ffcf857268620f1cc83856cb9d30f2676b015a4fcb834d8cd44db673e0a9ffddcec33b4f980b5ea00c2eb68a9a0da7483efcb39db53856577fb56f24ee94b5be578a29468cf87af28fe8e45c69b861f)
System: Chrome 101.0.4951 / Windows 10.0.0
Referer: https://www.gbif.org/faq
Window size: width 1920 - height 880
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-25T18:28:29.369Z',to:'2022-05-25T18:34:29.369Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-25T18:28:29.369Z',to:'2022-05-25T18:34:29.369Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by NgAMB** [comment]
I, too, was looking for such a table and could not find one. I wrote this little python script to pull out the information I needed and put it into a human-readable table. My input file was a level2 GeoJSON file available from the [GADM website](https://gadm.org/download_country.html).

```
import csv
import json

with open('Path/to/gadm/file.json') as inFile:
    data = json.load(inFile)

with open('Path/to/desired/output.csv', 'w', newline='', encoding='utf-8') as outFile:
    gadmWriter = csv.writer(outFile)
    gadmWriter.writerow(['GID_1', 'NAME_1', 'GID_2', 'NAME_2'])
    for i in data['features']:
        gadmWriter.writerow([i['properties']['GID_1'], i['properties']['NAME_1'], i['properties']['GID_2'], i['properties']['NAME_2']])
```

**Comment by MortenHofft** [comment]
Sorry that you never got a response to this question! For others that stumble over this it might still be useful with an answer.

I'm not sure what lookup you are interested in, but you can get information about an ID using
https://api.gbif.org/v1/geocode/gadm/DNK.1.25_1

I will close this issue, feel free to comment if this isn't what you are looking for. We are working on a new documentation, that will include this btw.

Thanks

**Comment by ManonGros** [comment]
did you notify the original user who posted the issue @MortenHofft ?
