### ISSUE TITLE
"Collection match none" and "Institution match fuzzy"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4101]
**&quot;Collection match none&quot; and &quot;Institution match fuzzy&quot;**

HARG (herbarium of the University of Hargeisa) has 515 records (almost all of them) with collection match none and the same number with institution match fuzzy. How do I address these?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ad78e2b92bd0c3a2d73b63976863169d:f9430d70fa6a76bf490de7960d5f72bfbb1002fc0061256f60af9072757c08a5d0e1741b7661361e94b6803faa09534e9ad26e26d7f2b30d68e95c09c680fa855df1485894ebd736f50ef6affa00bcc7f26d248eb48fe80e2b70a0b01befe5e855f8627ea96af31b334db9398f50121ee7ce99df5f82e8ba410cbe5d8f7cf1d33ed11c5fa16276587c4b059831f66be8) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ad78e2b92bd0c3a2d73b63976863169d:f9430d70fa6a76bf490de7960d5f72bfbb1002fc0061256f60af9072757c08a5d0e1741b7661361e94b6803faa09534e9ad26e26d7f2b30d68e95c09c680fa855df1485894ebd736f50ef6affa00bcc7f26d248eb48fe80e2b70a0b01befe5e855f8627ea96af31b334db9398f50121ee7ce99df5f82e8ba410cbe5d8f7cf1d33ed11c5fa16276587c4b059831f66be8)
System: Chrome 102.0.5005 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/e1966d34-2144-4a07-a6d4-b246d6f047aa/metrics
Window size: width 1920 - height 942
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-29T06:55:17.668Z',to:'2022-05-29T07:01:17.668Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-29T06:55:17.668Z',to:'2022-05-29T07:01:17.668Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This is because no institutionID is provided and the collectionID doesn't correspond to any identifier in GRSciColl. See more information on this blogpost: https://data-blog.gbif.org/post/grscicoll-flags/

User contacted by email.
