### ISSUE TITLE
Deputy regional representative for Europe showing before representative

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#411]
**Deputy regional representative for Europe showing before representative**

I suspect because it is sorting alphabetically on the full title .. but clearly the regional representative should show up before the deputy.

-----
fbitem-2f490e24d093373543a643a154f2bbaa4c6ec09b
Reported by: @timhirsch
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/the-gbif-network/europe
Window size: width 1800 - height 716
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-29T14:43:25.811Z',mode:absolute,to:'2017-08-29T14:49:25.811Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-29T14:43:25.811Z',mode:absolute,to:'2017-08-29T14:49:25.811Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
@thomasstjerne how is this section loaded (which API request)? We have sort order server side for most of them.
