### ISSUE TITLE
Data Query Download Bug

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4111]
**Data Query Download Bug**

I'm trying to download a .csv file with coordinates from a specific crop, which is Apple(Malus domestica).
I've tried to filter the data by the crop or scientific names, then click on the download button. After that, I get a message saying that I need to delete the text "Apple" from the data query to be able to download the .csv file. I get into the page where my 'filtered' data is being processed by deleting. Finally, I got an email that notified me that my data was ready to be downloaded, but the size was too large (more than 200 M; ~28 GB), which is supposed to be ~15-20 MB. Any guess why I'm getting this output?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8ed39147bd9228920e82971d7cb39689:dffec02663cffe4513bb990c942df148a350c77e2bb53973f760726f92f4f88255e1787e3d5fadac6ce67985df7852b2e65789a69951bf084941e0d7d57ae98f347b1fa66f6de617c9d93975665c5eca2f98650f65a6c54675a279f742eabf92) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8ed39147bd9228920e82971d7cb39689:dffec02663cffe4513bb990c942df148a350c77e2bb53973f760726f92f4f88255e1787e3d5fadac6ce67985df7852b2e65789a69951bf084941e0d7d57ae98f347b1fa66f6de617c9d93975665c5eca2f98650f65a6c54675a279f742eabf92)
System: Chrome 102.0.5005 / Windows 10.0.0
Referer: https://www.gbif.org/faq
Window size: width 1366 - height 617
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-02T11:18:32.435Z',to:'2022-06-02T11:24:32.435Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-02T11:18:32.435Z',to:'2022-06-02T11:24:32.435Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Our system is unable to generate downloads based on free-text search queries. I suggest to use the scientific name filter to get the apple records. See this example: https://www.gbif.org/occurrence/search?taxon_key=7821083&taxon_key=3001244&occurrence_status=present. I suspect that when the free-text filter was removed from your query, nothing was left to filter the data. That’s why you got a very large download.
Could you try again generating the download by filtering the records with the scientific name field?
