### ISSUE TITLE
GRIIS Colombia List with Duplicated taxa

### ISSUE THREAD

**Issue by camiplata** [gbif/portal-feedback#4117]
The species Canis lupus is duplicated on this List.

https://www.gbif.org/dataset/168568e7-eb5f-4ef6-8c59-f73ceaf57e91

Thanks!
@sibcolombia

**Comment by ManonGros** [comment]
publisher contacted by email.

**Comment by ManonGros** [comment]
The issue has been fixed: https://www.gbif.org/species/search?q=Canis%20lupus&dataset_key=168568e7-eb5f-4ef6-8c59-f73ceaf57e91&origin=SOURCE&advanced=1
