### ISSUE TITLE
API url should point to https

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#412]
**API url should point to https**

This url is loaded from the config but returns the http version instead of the https version.

-----
fbitem-f0bca0774a9c8eaecc8788650664fc5d3e0b6ba1
Reported by: @cgendreau
System: Chrome 59.0.3071 / Mac OS X 10.10.5
Referer: https://www.gbif.org/developer/summary
Window size: width 1440 - height 851
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-30T07:15:37.483Z',mode:absolute,to:'2017-08-30T07:21:37.483Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-30T07:15:37.483Z',mode:absolute,to:'2017-08-30T07:21:37.483Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
It should explain that both HTTP and HTTPS are supported, and HTTP/2 on both.

I don't mind which people choose to use.
