### ISSUE TITLE
Wrong link to ingestion queue

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4123]
**Wrong link to ingestion queue**

When clicking `Ingest now` on a dataset (available if you are trusted contact), the button switches to `Is in ingestion queue`. The link of that button is:

https://registry.gbif.org//monitoring/running-ingestions

rather than:

https://registry.gbif.org/monitoring/running-ingestions

-----

Github user: @peterdesmet
User: [See in registry](https://www.gbif.org/api/feedback/user/ac46370fd4d86f17b71876298aaf4778:985e3ddde81dd3a3cba8e38620caa11ce56ae8e818ee325229cbef18932530679286321b2fc44366270ddddf27ad57360a50342111c094770fb0fabf1f7ac6595dccf9b16a88d47db4e3f8103b2eacb207432559a42db74ce03eac62cbfcc3af5ee7ff0dbe95ec9742d11e18c4eb1324a227ada18ae071e0188aa6e0b1653d30889491beb0c1cc9da360da1b64620259) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ac46370fd4d86f17b71876298aaf4778:985e3ddde81dd3a3cba8e38620caa11ce56ae8e818ee325229cbef18932530679286321b2fc44366270ddddf27ad57360a50342111c094770fb0fabf1f7ac6595dccf9b16a88d47db4e3f8103b2eacb207432559a42db74ce03eac62cbfcc3af5ee7ff0dbe95ec9742d11e18c4eb1324a227ada18ae071e0188aa6e0b1653d30889491beb0c1cc9da360da1b64620259)
System: Chrome 102.0.5005 / Mac OS X 10.14.6
Referer: https://www.gbif.org/dataset/6c860eb3-83ba-48c3-9328-a7b3c7a3c7b4
Window size: width 1228 - height 766
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-10T19:38:07.363Z',to:'2022-06-10T19:44:07.363Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-10T19:38:07.363Z',to:'2022-06-10T19:44:07.363Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thanks @peterdesmet
