### ISSUE TITLE
How GBIF deals with species affinis or species proxima qualifiers (nr. prox.)

### ISSUE THREAD

**Issue by jhnwllr** [gbif/portal-feedback#4124]
> Within [entomology](https://en.wikipedia.org/wiki/Entomology), species proxima (Latin: 'the nearest species', abbreviated prox. or sp. prox.) and species near (abbreviated nr. or sp. nr.) indicate a specimen is similar to, but distinct from, a described species.[[4]](https://en.wikipedia.org/wiki/Species_affinis#cite_note-Sigovini_et_al.,_2016-4)

> Species affinis (commonly abbreviated to: sp., aff., or affin.) is [taxonomic](https://en.wikipedia.org/wiki/Taxonomy_(biology)) terminology in [zoology](https://en.wikipedia.org/wiki/Zoology) and [botany](https://en.wikipedia.org/wiki/Botany). In [open nomenclature](https://en.wikipedia.org/wiki/Open_nomenclature) it indicates that available material or evidence suggests that the proposed [species](https://en.wikipedia.org/wiki/Species) is related to, has an [affinity](https://en.wikipedia.org/wiki/Affinity_(taxonomy)) to, but is not identical to, the species with the [binomial](https://en.wikipedia.org/wiki/Binomial_nomenclature) name it comes after.[[1]](https://en.wikipedia.org/wiki/Species_affinis#cite_note-1) The Latin word affinis can be translated as "closely related to", or "akin to".[[2]](https://en.wikipedia.org/wiki/Species_affinis#cite_note-2)

I noticed that the GBIF **name matcher** takes into account the uncertainty in names with "uncertainty" qualifiers (nr. prox. probably others) by giving them a **higher rank flag**. 

Still, the uncertain name is still matched at the level of **species rank** (making it seem certain), so anyone searching for the name without the qualifier will get back **occurrence data** that perhaps appears to be more certain than the publisher intended. 

For example, 

**Camponotus vicinus nr. Mayr, 1870** has a qualifier of **"nr."** for "near". 

All occurrences with this name get a **taxon match higherrank** flag. 
https://www.gbif.org/occurrence/search?advanced=1&verbatim_scientific_name=Camponotus%20vicinus%20nr.%20Mayr,%201870

However, searches for **Camponotus vicinus Mayr, 1870** without "nr." return the flagged occurrences as well. 
https://www.gbif.org/occurrence/search?issue=TAXON_MATCH_HIGHERRANK&taxon_key=5034187&advanced=1

So a user would have to be aware of this little quirk in GBIF processing to filter out all occurrences with uncertain ids because the uncertain records are mixed in with the certain ones. 

A more intuitive way to handle these "uncertain" occurrences would be to **actually match them to the higher rank** ("Camponotus"). 

Similar situation for **prox.**
**Sabethes tarsopus prox. Dyar | Knab, 1908**
https://www.gbif.org/occurrence/search?advanced=1&verbatim_scientific_name=Sabethes%20tarsopus%20prox.%20Dyar%20%7C%20Knab,%201908

@mdoering

**Comment by mdoering** [comment]
I assume the name parser thinks these 2 names are subspecies and hence tags them as higher rank match and includes them in species searches:

 - http://api.gbif.org/v1/parser/name?name=Sabethes%20tarsopus%20prox.%20Dyar
 - http://api.gbif.org/v1/parser/name?name=Camponotus%20vicinus%20nr.%20Mayr,%201870

The only uncertain identification notes I am aware of that is implemented in the parser are "aff." and "spec." or "sp.".
Please leave an issue in the [name parser](https://github.com/gbif/name-parser/issues/new) for dealing with various others remarks that indicate an uncertain identification.
