### ISSUE TITLE
Cannot find my Organization(in the dropdown list) to configure our IPT server. The organization is 'Environmental Protection Agency' from Guyana. And it is listed as a participating organization but it is not listed in the IPT Administration list of organization in the organization dropdown list

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4128]
**Cannot find my Organization(in the dropdown list) to configure our IPT server. The organization is &#39;Environmental Protection Agency&#39; from Guyana. And it is listed as a participating organization but it is not listed in the IPT Administration list of organization in the organization dropdown list**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a98ace1790ed0f005cffade52716cf4f:aef3bd2a3d8600ec0d87e5f7085c4947d404a353fe6be32626170cf1695a1c9481fe2fb3964c95c81f2ddd1a187defb88d5cfb1d99c8b277ddbe6968cf759f2bb4a34034a0b72f1ef18de4f9d6bc7d788febe74fea88bab9daeb4eb4588ec3ea10148158ab9a2c1f6ffdf1fd4d6d210106fcf24177538575fb99490110706692) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a98ace1790ed0f005cffade52716cf4f:aef3bd2a3d8600ec0d87e5f7085c4947d404a353fe6be32626170cf1695a1c9481fe2fb3964c95c81f2ddd1a187defb88d5cfb1d99c8b277ddbe6968cf759f2bb4a34034a0b72f1ef18de4f9d6bc7d788febe74fea88bab9daeb4eb4588ec3ea10148158ab9a2c1f6ffdf1fd4d6d210106fcf24177538575fb99490110706692)
System: Chrome 102.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/e7cc89db-d984-4b46-bf67-fb2ffdcf1e22
Window size: width 1280 - height 676
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-14T19:48:12.382Z',to:'2022-06-14T19:54:12.382Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-14T19:48:12.382Z',to:'2022-06-14T19:54:12.382Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email
> Could you let us know if adding your organization to your IPT is still an issue?
I checked from an IPT in production mode and your organization was in the dropdown list.
Is your IPT in TEST mode or in PRODUCTION mode?
