### ISSUE TITLE
GBIF user account link gives 404

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#413]
**GBIF user account link gives 404**

The link behind "GBIF user account" in the API Summary page points to the previous page used to create user accounts. Since it is now included in the Login "box" I'm not sure if we should keep a link or simply change the text to explain how.

-----
fbitem-f0bca0774a9c8eaecc8788650664fc5d3e0b6ba1
Reported by: @cgendreau
System: Chrome 59.0.3071 / Mac OS X 10.10.5
Referer: https://www.gbif.org/developer/summary
Window size: width 1440 - height 851
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-30T07:39:15.329Z',mode:absolute,to:'2017-08-30T07:45:15.329Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-30T07:39:15.329Z',mode:absolute,to:'2017-08-30T07:45:15.329Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
Should point to https://www.gbif.org/user/profile
