### ISSUE TITLE
16th-century dates present but not parsing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4130]
**16th-century dates present but not parsing**

We're showing that 0% of the 7,000+ records in this new dataset with a year, but years definitely appear to be present in the verbatim data. 

Probably just a matter of date formatting that's easy for the triumvirate of help desk–GBIF Spain–los sevillanes to sort out…

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/d4a81ba34f4ed32b95c3dbd85c609ed1:4109ba6524ba0a8f0249d6c49cd3bd5519475ed7e5934c13e33d2c22921242cdf0f80320ff139307bbe744f8b8bd1c764b21aa99e44bf995c43ff7b15e62b179934788667148e9589ea89f775d9082dcc2564a934cbdf3e33cf38e8a9a8223cdcc734f327cc02ebdba65152af9a13ece6a0230d2b673919c39b3c5ce317676ab) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d4a81ba34f4ed32b95c3dbd85c609ed1:4109ba6524ba0a8f0249d6c49cd3bd5519475ed7e5934c13e33d2c22921242cdf0f80320ff139307bbe744f8b8bd1c764b21aa99e44bf995c43ff7b15e62b179934788667148e9589ea89f775d9082dcc2564a934cbdf3e33cf38e8a9a8223cdcc734f327cc02ebdba65152af9a13ece6a0230d2b673919c39b3c5ce317676ab)
System: Firefox 101.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/dataset/49304fda-fd0b-4ae8-9747-89c508d60aee
Window size: width 1534 - height 910
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-15T15:46:55.918Z',to:'2022-06-15T15:52:55.918Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-15T15:46:55.918Z',to:'2022-06-15T15:52:55.918Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
https://www.gbif.org/occurrence/3804272302



Term | Interpreted | Original | Remarks
-- | -- | -- | --
Event date |   | 1579 | Recorded date unlikely

Looks like we remove it deliberately

I believe all our maps also exclude everything before 1600. It is a hardcoded value some places I believe

**Comment by kcopas** [comment]
Okay, that clearly would be a problem with this dataset.

Was that basically an arbitrary limit? Thinking, like, yeah, we probably don't have any records that date to before 1600?

**Comment by MortenHofft** [comment]
I think so yes. It has been so since I started here. @timrobertson100 will know the history of it and I might be mistaken

**Comment by timrobertson100** [comment]
> Thinking, like, yeah, we probably don't have any records that date to before 1600?

Yes, but the origins were about removing "dirty" data

**Comment by timrobertson100** [comment]
We'll track the fix here https://github.com/gbif/pipelines/issues/735
