### ISSUE TITLE
Download citation include information on download type and/or content

### ISSUE THREAD

**Issue by CecSve** [gbif/portal-feedback#4134]
Currently the citation for an occurrence download is for example:

> GBIF.org (21 June 2022) GBIF Occurrence Download https://doi.org/10.15468/dl.xxqwmp 

This does not give any information on which type of download was used or the content of the download other than it is occurrence based. Could it be an idea to include the type of download used, for example:

- GBIF.org (21 June 2022) **SIMPLE** GBIF Occurrence Download https://doi.org/10.15468/dl.xxqwmp 
- GBIF.org (21 June 2022) **Darwin Core Archive** GBIF Occurrence Download https://doi.org/10.15468/dl.xxqwmp 
- GBIF.org (21 June 2022) **Species List** GBIF Occurrence Download https://doi.org/10.15468/dl.xxqwmp 

This would probably require accessible documentation (https://github.com/gbif/portal-feedback/issues/3153, https://github.com/gbif/portal-feedback/issues/3077) on the different types of download. 

If users were able to select which columns to download (e.g https://github.com/gbif/portal-feedback/issues/3106, https://github.com/gbif/portal-feedback/issues/3737) then ideally this should be clear from the citation as well. 

@dnoesgaard any thoughts on this idea?

**Comment by dnoesgaard** [comment]
IMHO, the download format names aren't very meaningful to anyone outside GBIF. I'm not sure I would see the benefit of making a distinction in the citation. Anyone can go to the download and find out more. 

We could try to add more information to the citation about a lot of things (taxa, numbers, years, etc), but really, anything that complicates the citation is a risk and not good from my point of view.
