### ISSUE TITLE
Inclusion of (optional) extension-data in DwC-A downloads

### ISSUE THREAD

**Issue by CecSve** [gbif/portal-feedback#4135]
More extensions should be included in the DwC-A download option besides the Multimedia extension. Ideally, users should be able to select which extension data they wish to download based on the available option for a given dataset. 

Potentially the extensions downloaded could show in the citation for the download (https://github.com/gbif/portal-feedback/issues/4134).

**Comment by AbbyBenson** [comment]
As a node manager that facilitates the use of several extensions for sharing data I support this idea!

**Comment by SophiePamerlon** [comment]
Hello,
I also wholeheartedly support this idea, I recently had a technical meeting with a researcher who wants to publish occurrence data with traits information using the Traits extension(s) + Plinian extension, and the occurrences are not wholly reusable (or at least not as interesting) without the information shared in the extensions.
The same applies to (e)MoF which is a really common & useful extension to share variables, sometimes crucial to the understanding of the occurrences/events/taxa they're linked to.

**Comment by MattBlissett** [comment]
Extension data can now be downloaded through the API — for the website see https://github.com/gbif/portal16/issues/1910

API documentation: https://techdocs.gbif.org/en/data-use/api-downloads#verbatimextensions
