### ISSUE TITLE
Quick links on this page not working

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4137]
**Quick links on this page not working**

Clicking on "Read the case studies" changes the URL but doesn't take you to that section of the page.

-----

Github user: @albenson-usgs
User: [See in registry](https://www.gbif.org/api/feedback/user/0a8dcac3756369b85825a02441e5c0a6:d144fbea8efb73683e5d7c9f34e47e993844853d73c681e9e673613cf246d5565fa159533776f8a175596f0c77bd07a1ce1348bcc74b457d1a06a18d514a6aa358e471e02193f0f1c73e90445067a14180dbb90ca697f632b9c751e2fe90866229d217f7cb012734f7f3557581ac71cff39619117f38ad14d1c43104d8f0912c) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0a8dcac3756369b85825a02441e5c0a6:d144fbea8efb73683e5d7c9f34e47e993844853d73c681e9e673613cf246d5565fa159533776f8a175596f0c77bd07a1ce1348bcc74b457d1a06a18d514a6aa358e471e02193f0f1c73e90445067a14180dbb90ca697f632b9c751e2fe90866229d217f7cb012734f7f3557581ac71cff39619117f38ad14d1c43104d8f0912c)
System: Firefox 101.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/composition/HjlTr705BctcnaZkcjRJq/data-model
Window size: width 1707 - height 1074
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-21T20:18:09.030Z',to:'2022-06-21T20:24:09.030Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-21T20:18:09.030Z',to:'2022-06-21T20:24:09.030Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Not sure who can fix this @MortenHofft maybe?

**Comment by MortenHofft** [comment]
The website do not automatically generate anchors. So content editors need to add them themselves in contentful. In this case that hasn't been done.

There is a feature request to auto generate them
Notice that it is this issue https://github.com/gbif/portal16/issues/1695

I will look at the issue.

**Comment by MortenHofft** [comment]
Actually I will reopen this issue as the editor might want to correct the article in the meantime (even though I'm not entirely sure it is even possible in this case)

**Comment by MortenHofft** [comment]
I've fixed the link in Contentful for this specific case.
