### ISSUE TITLE
Report can't be generated

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4138]
**Report can&#39;t be generated**

I've been trying to validate a dataset and it keeps telling me the validation failed and the report can't be generated.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/aa06556c1ab15ed71274fab3064040d8:59bb13dfa3174a198823c89044ed10919918e56ea74c6f692f3cea45fcc7cdb88f73cd5751758d22fa405fe06232d281686a9bf89b392b182ef5e2d00bf613e201194e91584eda7a21f75309fe8bed6373c6b5349044b16f66b68e3eb71f4057ac0893a3f2aff31c91e549e6e0697068) - [Send email](https://www.gbif.org/api/feedback/user/mailto/aa06556c1ab15ed71274fab3064040d8:59bb13dfa3174a198823c89044ed10919918e56ea74c6f692f3cea45fcc7cdb88f73cd5751758d22fa405fe06232d281686a9bf89b392b182ef5e2d00bf613e201194e91584eda7a21f75309fe8bed6373c6b5349044b16f66b68e3eb71f4057ac0893a3f2aff31c91e549e6e0697068)
System: Chrome 95.0.4638 / Windows 10.0.0
Referer: https://www.gbif.org/es/tools/data-validator/my-validations
Window size: width 1813 - height 757
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-21T22:07:40.333Z',to:'2022-06-21T22:13:40.333Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-21T22:07:40.333Z',to:'2022-06-21T22:13:40.333Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
User has been contacted via help desk

**Comment by CecSve** [comment]
The user managed to validate the file.
