### ISSUE TITLE
Alternative identifier DOI removal

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#4145]
I added a DOI as an alternative identifier to a dataset (https://www.gbif.org/dataset/0db86a4c-5b10-4a39-b81d-15e1525bb27f, the zenodo DOI), and we've decided we would actually rather have a separate GBIF-generated DOI for the GBIF dataset, and we'll just link the zenodo DOI in the bibliographic citations in the IPT. 

So I deleted the zenodo DOI in the IPT's alternative identifiers list, and I was hoping that would remove it from the GBIF dataset and generate a GBIF DOI for the dataset. I think this hasn't happened though. Should I delete the dataset and try again?

**Comment by MattBlissett** [comment]
Hi,

Identifiers must be deleted/changed manually in the GBIF registry, as we generally don't want to lose them. I've done this for this dataset.

**Comment by rukayaj** [comment]
Thanks @MattBlissett
