### ISSUE TITLE
The images do not correspond to Miconia neomicrantha (Melastomataceae), the photos belong to genera Ficus (Moraceae). https://www.gbif.org/occurrence/gallery?taxon_key=7944396

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4147]
**The images do not correspond to Miconia neomicrantha (Melastomataceae), the photos belong to genera Ficus (Moraceae). `https://www.gbif.org/occurrence/gallery?taxon_key=7944396`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2c3fd5229fc585b667341da531570e43:4911eb093e4d6b18a0fd9690df49b12e1c1bad21756114226f2ddee8c48ab2c5e20da660d8dfc5483875ad33aa55e27ccd976762d7993f252925c1d4cbbcff03b83ab560e1f08cef1e4df81cfa721eb118d6be7592090bd53c67f776a14e70fbd932ea8d8c69af5613b52e60133fec32376039e117d5e47c1a511abf79884ce2ba4b1a0bfe99d2480df4898facc9832777a8a0bcb54cf7699bd6ecf6a02b5a8c) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2c3fd5229fc585b667341da531570e43:4911eb093e4d6b18a0fd9690df49b12e1c1bad21756114226f2ddee8c48ab2c5e20da660d8dfc5483875ad33aa55e27ccd976762d7993f252925c1d4cbbcff03b83ab560e1f08cef1e4df81cfa721eb118d6be7592090bd53c67f776a14e70fbd932ea8d8c69af5613b52e60133fec32376039e117d5e47c1a511abf79884ce2ba4b1a0bfe99d2480df4898facc9832777a8a0bcb54cf7699bd6ecf6a02b5a8c)
System: Chrome 102.0.5005 / Windows 10.0.0
Referer: https://www.gbif.org/es/occurrence/2643585628
Window size: width 1910 - height 1014
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-27T20:29:36.276Z',to:'2022-06-27T20:35:36.276Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-27T20:29:36.276Z',to:'2022-06-27T20:35:36.276Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by CecSve** [comment]
The original observation on [PlantNet](https://identify.plantnet.org/central-america/observations/1003809728) no longer exist. The observation should be removed from the dataset, but still appears on GBIF.

**Comment by CecSve** [comment]
The dataset is currently being reprocessed and will be updated momentarily. This should resolve the issue eventually.

**Comment by CecSve** [comment]
The observation has now been updated by Pl@ntnet and the observation is deleted on GBIF.org
