### ISSUE TITLE
The images do not correspond to Miconia neomicrantha, the photos belong to Drymonia coriacea (Gesneriaceae) https://www.gbif.org/occurrence/gallery?taxon_key=5591161

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4148]
**The images do not correspond to Miconia neomicrantha, the photos belong to Drymonia coriacea (Gesneriaceae) `https://www.gbif.org/occurrence/gallery?taxon_key=5591161`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9a5a0aee7cca2f728f1524d5afe79fb5:45583204a7a080c28496881e5e58170ba861f0a6227c9de9a1794ef611454acd45db3f0308022d2a7d6781d4fcb58c1db89e56ca4105df16bb3ba677bb8629142ad9b552c904f3a1fc47f82f900a8dc868c9769a069423d7e6491192be9cd75d7bb7441dd6eead14f8fdaa895e70f71e2dd24a940abbff4e4291d9e76e16dd065bdf3b486ad3f8b31d9ac29d8f91402f434dadcef108f3f950a3cac54ad99045) - [Send email](https://www.gbif.org/api/feedback/user/mailto/9a5a0aee7cca2f728f1524d5afe79fb5:45583204a7a080c28496881e5e58170ba861f0a6227c9de9a1794ef611454acd45db3f0308022d2a7d6781d4fcb58c1db89e56ca4105df16bb3ba677bb8629142ad9b552c904f3a1fc47f82f900a8dc868c9769a069423d7e6491192be9cd75d7bb7441dd6eead14f8fdaa895e70f71e2dd24a940abbff4e4291d9e76e16dd065bdf3b486ad3f8b31d9ac29d8f91402f434dadcef108f3f950a3cac54ad99045)
System: Chrome 102.0.5005 / Windows 10.0.0
Referer: https://www.gbif.org/es/occurrence/2643588460
Window size: width 1910 - height 1014
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-27T20:34:03.640Z',to:'2022-06-27T20:40:03.640Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-27T20:34:03.640Z',to:'2022-06-27T20:40:03.640Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7a3679ef-5582-4aaa-81f0-8c2545cafc81
publishingOrgKey: da86174a-a605-43a4-a5e8-53d484152cd3

**Comment by CecSve** [comment]
This occurrence is no longer part of the plantnet dataset (source) and will be removed when the dataset is updated. Plantnet is currently reworking the entire dataset to remove poor quality records and this might take a while.

**Comment by CecSve** [comment]
Pl@ntnet has updated the dataset and the observation is no longer available on GBIF.org
