### ISSUE TITLE
accepted names missing in https://www.gbif.org/dataset/3566822f-2b74-468a-af13-e75651813d3f

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#4149]
I wonder why the accepted names are missing in this dataset. there are only occurrences listed

This is a paper written in cyrilic and thus I wonder whether this might be a reason

https://www.gbif.org/dataset/3566822f-2b74-468a-af13-e75651813d3f

Plazi article https://tb.plazi.org/GgServer/summary/2050147AFF8BFFE4FFF5FFACFFE3FF81 which include material citations in the treatments

**Comment by thomasstjerne** [comment]
I think they are there now.

**Comment by myrmoteras** [comment]
@thomasstjerne thanks. can you check, why the figures do not show up in the treatment

https://treatment.plazi.org/id/DC696C02FF8AFFE7FE8FFA9CFC75FC82
![image](https://user-images.githubusercontent.com/4609956/176390179-4e42d645-6738-4c5b-b571-3ac6a616161c.png)

**Comment by thomasstjerne** [comment]
It looks like the multimedia extension is not ingested correctly even though present in the source archive.
I have create an issue here https://github.com/gbif/checklistbank/issues/218
