### ISSUE TITLE
GRIIS Colombia List Mistmatch betweenn scientificName and higher taxonomy

### ISSUE THREAD

**Issue by camiplata** [gbif/portal-feedback#4151]
Hi!

We noticed the  species [Ferrissia californica (A molusc)](https://www.gbif.org/es/species/9520065) has the [higher taxonomy of an anfibian: Amphibia | Anura | Pipidae](https://www.gbif.org/es/species/196368481)

https://www.gbif.org/dataset/168568e7-eb5f-4ef6-8c59-f73ceaf57e91

Thanks!
@SiBColombia

**Comment by CecSve** [comment]
Thank you for notifying us - we have contacted the data admin and await their answer.

**Comment by CecSve** [comment]
The error has been corrected and the record now appears under Mollusca instead of Amphibia: https://www.gbif.org/species/196368481
