### ISSUE TITLE
Strange date/timestamp shown instead of year

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4155]
**Strange date/timestamp shown instead of year**

Was exploring Alismatales occurrences per year and noticed that mouse-over pop-up shown in the graph changes around the year 1894, looking fine after but weird before.

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/a9d559fc630e1b858a90591ff15d92a7:e69633298a456b0e1faeb38506e330b8aec8648b95aeed55084d8724cdc91ff53b4f31c52950a32603098f90d7687d7b5b608210de0b85db0229bb1e99b6e2627ecf01b98067dd27d27bd556f1a8d22187b4541853062c343ecd24f385a8b621f5f081b6ed2cc344cbb61c37fd8ddb98af4ce1752fc5f9739221c2ffa5745a4f4a935e4a7d4857e378189967d5af82cc) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a9d559fc630e1b858a90591ff15d92a7:e69633298a456b0e1faeb38506e330b8aec8648b95aeed55084d8724cdc91ff53b4f31c52950a32603098f90d7687d7b5b608210de0b85db0229bb1e99b6e2627ecf01b98067dd27d27bd556f1a8d22187b4541853062c343ecd24f385a8b621f5f081b6ed2cc344cbb61c37fd8ddb98af4ce1752fc5f9739221c2ffa5745a4f4a935e4a7d4857e378189967d5af82cc)
System: Chrome 103.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/charts?taxon_key=551
Window size: width 1787 - height 966
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-30T12:34:55.032Z',to:'2022-06-30T12:40:55.032Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-06-30T12:34:55.032Z',to:'2022-06-30T12:40:55.032Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
![Screenshot 2022-06-30 at 14 40 31](https://user-images.githubusercontent.com/21358085/176679362-6966d8a7-9e3f-4c8e-a467-fdd5abe0050c.png)
![Screenshot 2022-06-30 at 14 40 26](https://user-images.githubusercontent.com/21358085/176679367-16e0ce8c-d2d1-4240-baea-f7db6124b8fc.png)

**Comment by MortenHofft** [comment]
Odd. The API as well as the proxy API shows the correct information. But the Highcharts presentation looks weird. Somewhere around here things go wrong https://github.com/gbif/portal16/tree/master/app/views/components/occurrenceBreakdown

**Comment by MortenHofft** [comment]
We never got around to this issue and i see it is solved in the way we do year charts in the new stack. i will close this
