### ISSUE TITLE
Mismapped data in dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4157]
**Mismapped data in dataset**

Found this just by accident, but this is a dataset that has mismapped data - look at the scientific name

Tim R

-----

Github user: @timrobertson100
User: [See in registry](https://www.gbif.org/api/feedback/user/b2003490475b62c016ef6831891dc779:979ba25a6b89749582879ac4e38800a139a27555e0a7d04c602d355008bbe0d27e5ff6c8a9fa1739c95c1b79c3f2633576562a58d9ac2a8a424fb0c4f3b5b325a0c3649856345ca6c8d7bbd19a433bdc9030c797f4b4aba3aaf63ff75d0c4ee4af8d6e578dbdc14c76d66d904debae87f0c8f8851027d5577aa70bc66ab603c264137bdaa6b2d0fcfae6f651e731a8c9) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b2003490475b62c016ef6831891dc779:979ba25a6b89749582879ac4e38800a139a27555e0a7d04c602d355008bbe0d27e5ff6c8a9fa1739c95c1b79c3f2633576562a58d9ac2a8a424fb0c4f3b5b325a0c3649856345ca6c8d7bbd19a433bdc9030c797f4b4aba3aaf63ff75d0c4ee4af8d6e578dbdc14c76d66d904debae87f0c8f8851027d5577aa70bc66ab603c264137bdaa6b2d0fcfae6f651e731a8c9)
System: Chrome 102.0.5005 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/1087858942
Window size: width 2163 - height 1243
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-03T10:01:02.927Z',to:'2022-07-03T10:07:02.927Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-03T10:01:02.927Z',to:'2022-07-03T10:07:02.927Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 52f2051b-c47e-403a-8e32-04b2f2273c20
publishingOrgKey: 823818f6-0696-4e29-bc4c-b6f3817535a7

**Comment by CecSve** [comment]
More records appear to be affected: https://www.gbif.org/occurrence/search?dataset_key=52f2051b-c47e-403a-8e32-04b2f2273c20&issue=TAXON_MATCH_NONE

**Comment by ManonGros** [comment]
contacted publisher by email
