### ISSUE TITLE
Update on Organization Contacts

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4158]
**Update on Organization Contacts**

Dear Helpdesk,

I want to ask you if you could remove María Renée Álvarez Ruano from the point of contact from Universidad del Valle de Guatemala. She stopped working with us last month. 

Thank you very much.

-----

Github user: @zabdi8
User: [See in registry](https://www.gbif.org/api/feedback/user/3e8174cf3f0fe01e5645e83883110ab7:167bf7f7b7143dc96f97ea1c337e87e997d8477f2a01dc76fd584d0cd687028133435c224e3bc6ab6896a3e460b833e3ff3045d51e32b1e7b5461b0fbf30ea5bc4213bd1fb27f0c6299d1637b2447fa6e1ecb017d4c661d72a9a0db129f4177abdd3b4823ddbd4ecf991277cda79c2855bc65eccd2ee42a85bdc721866123c45) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3e8174cf3f0fe01e5645e83883110ab7:167bf7f7b7143dc96f97ea1c337e87e997d8477f2a01dc76fd584d0cd687028133435c224e3bc6ab6896a3e460b833e3ff3045d51e32b1e7b5461b0fbf30ea5bc4213bd1fb27f0c6299d1637b2447fa6e1ecb017d4c661d72a9a0db129f4177abdd3b4823ddbd4ecf991277cda79c2855bc65eccd2ee42a85bdc721866123c45)
System: Chrome 102.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/publisher/5c1a4c27-795a-4294-aecc-46d7176706b7
Window size: width 1440 - height 796
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-04T17:27:33.909Z',to:'2022-07-04T17:33:33.909Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-04T17:27:33.909Z',to:'2022-07-04T17:33:33.909Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Thanks @zabdi8, we have removed María (the changes should appear in a few min). Let us know if you need anything else.

**Comment by zabdilopez** [comment]
Excellent thank you for all your help!


Zabdi Moisés López U
Master en Gestión Ambiental y Sostenibilidad
Universidad del Valle de Guatemala
