### ISSUE TITLE
(LSIGMA-USB)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4159]
**(LSIGMA-USB)**

I have just accredited a data publishing institution (Laboratory of Geographic Information Systems and Environmental Modeling (LSIGMA-USB)) and I am waiting for the support of the Committee of Administrators of Participating Nodes. 
Greetings 
Carlos Enrique González Rojas

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/08465d78a7b06c981cab9a066e70dc69:cb5cf31140d16cdd06faee9a8cedbfd809ee8221b921387b22ac7bfc2ade7814d3ad29a2b9ead62ac91bc34d459267dbf53f2eb30bd99a8aa26898d14dbc9c47978c69004597691ad3c8da9112e416d7f712fbd55c7616fe07811add2a08d1e60c7a3df2f0c8656c769d1eb6610be703) - [Send email](https://www.gbif.org/api/feedback/user/mailto/08465d78a7b06c981cab9a066e70dc69:cb5cf31140d16cdd06faee9a8cedbfd809ee8221b921387b22ac7bfc2ade7814d3ad29a2b9ead62ac91bc34d459267dbf53f2eb30bd99a8aa26898d14dbc9c47978c69004597691ad3c8da9112e416d7f712fbd55c7616fe07811add2a08d1e60c7a3df2f0c8656c769d1eb6610be703)
System: Chrome 103.0.0 / Windows 7.0.0
Referer: https://www.gbif.org/node/7f48e0c8-5c96-49ec-b972-30748e339115
Window size: width 1707 - height 839
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-04T19:56:31.394Z',to:'2022-07-04T20:02:31.394Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-04T19:56:31.394Z',to:'2022-07-04T20:02:31.394Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
The endorsement request was received July 4th, 19:10 local time, and has since been forwarded to the relevant members of the GBIF Participant Node Managers Committee. Procedural guidelines allow up to four weeks to process such a request, though the turn-around is usually much faster than that. You will receive an automated notification, followed by a personal message, as soon as the procedure has completed.
With best regards, 
Andrea
