### ISSUE TITLE
Missing redirect to licensing info

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#416]
**Missing redirect to licensing info**

The IPT links to The http://www.gbif.org/terms/licences

which used to redirect to 

http://www.gbif.org/terms/overview#licensing

(currently available at http://www-old.gbif.org/terms/overview#licensing)

This page has moved to 

https://www.gbif.org/terms

Can this redirect please be reinstated? Thanks

-----
fbitem-6d40cf55bc0ebb2ec875d2f766849807aed6ac7d
Reported by: @kbraak
System: Firefox 55.0.0 / Mac OS X 10.10.0
Referer: https://www.gbif.org/terms/licences
Window size: width 1435 - height 1170
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-30T14:17:48.919Z',mode:absolute,to:'2017-08-30T14:23:48.919Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-30T14:17:48.919Z',mode:absolute,to:'2017-08-30T14:23:48.919Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
@dnoesgaard @kcopas is this something you can help with please? Thanks guys.
