### ISSUE TITLE
Ingestion seems to be running since Mon 27 Jun 2022

### ISSUE THREAD

**Issue by sylvain-morin** [gbif/portal-feedback#4160]
We have updated lots of french datasets between yesterday (5th of July) and today (6th of July)
We are analyzing the results (the update is triggered by an automatic workflow - more than 8000 datasets updated)

One issue is on this one:
https://www.gbif.org/dataset/adcdeb1e-83ed-4b4d-b955-63c244c22e67

It's a small one (132 occurrences on the IPT), however, it's still not updated on GBIF.org (127 occurrences).

From registry.gbif.org, we don't see any recent ingestion
![image](https://user-images.githubusercontent.com/56630013/177576839-6e68032c-e311-459c-a097-2794dbffde04.png)

Only the one from the 27th of June: the attempt 123.

I was looking at Elastic logs, to get more information, and I'm very surprised to see recent logs related to the attempt 123:
https://logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(display:On,pause:!f,value:0),time:(from:now-1M,to:now))&_a=(columns:!(_source),filters:!(),index:'24993300-fdb1-11ea-93de-b97c40066ce8',interval:auto,query:(language:lucene,query:'datasetKey.keyword:%22adcdeb1e-83ed-4b4d-b955-63c244c22e67%22%20'),sort:!('@timestamp',desc))

![image](https://user-images.githubusercontent.com/56630013/177577159-66f98833-d147-48e9-8389-46e9f6e1b51b.png)

Do you think this ingestion of this dataset is stucked since the 27th of June?
Which would explain why no new ingestion started recently for this dataset.

(8769 datasets were correctly updated between yesterday and today :) 

Thank you

**Comment by sylvain-morin** [comment]
Here is the list of the datasets I updated yesterday, but are still stucked on GBIF.org ingestion since the 27th of June: 

https://www.gbif.org/dataset/9e84be57-3b59-4486-99d7-26f260cfb1ad
https://www.gbif.org/dataset/33244db4-63eb-446f-bd83-16e4119ad6e3
https://www.gbif.org/dataset/adcdeb1e-83ed-4b4d-b955-63c244c22e67
https://www.gbif.org/dataset/c621bdda-1e6b-4c61-ba7f-9c5848755b4e
https://www.gbif.org/dataset/0cd5354f-75ef-4cfd-a66b-f224f09d7f64
https://www.gbif.org/dataset/390b6899-a3e4-4a0b-8730-af8d026a69bc
https://www.gbif.org/dataset/02d536bb-d119-41d7-bfaa-7b9472cdd6ca
https://www.gbif.org/dataset/11a3c7e5-c620-4478-af89-542b8cd3c540
https://www.gbif.org/dataset/99182513-1c74-4cb3-8334-6837862a032d
https://www.gbif.org/dataset/3b5f32ff-46d0-4c9b-a247-100afd96f331

This list could be longer since I'm only comparing the size of the datasets between IPT and GBIF.org....

**Comment by ManonGros** [comment]
Thanks @sylmorin-gbif !
It looks indeed like your datasets are stuck. I triggered the regingestion for all of them (running now), I can see that it now works for the first one you mentioned: https://registry.gbif.org/dataset/adcdeb1e-83ed-4b4d-b955-63c244c22e67/ingestion-history

I don't know why they got stuck these weren't the only ones. I will close the issue. now but let me know if you noticed more of them. Thanks!
