### ISSUE TITLE
how to import a matched GBIF occurrence key with a material citation via DWCA to GBIF?

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#4162]
we have an increasing number of project that involve linking material citations with specimen/occurrence/GBIFkeys

The links MC/specimen is made by adding an attribute to the material citation annotation in the treatments by Plazi.

The question to you is how to import this link to GBIF? Right now we plan to add the matching `occurrence gbif Key` as `reference` in the DWCA (see eg https://www.gbif.org/occurrence/2608708400)

![image](https://user-images.githubusercontent.com/4609956/177124733-0d82c4e7-2d95-4b78-b811-b6a820d5a55d.png)

What is your position in this?  Is this what can be done now? is there a better way to do it? Can we find a way that in the future we could also add some provenience data for the respective link we made, either by machine based on what is provided in the publication, or what the person does who curated the link?

in the mid to long term we also need to add the provenance of the link - we know.

**Comment by timrobertson100** [comment]
Thanks, @myrmoteras - others may weigh in on this.

At the moment, I can't see any other sensible alternative if it is to link to the GBIF record. Putting https://www.gbif.org/occurrence/n in there will be something that we can parse out in the future if needed, and it's clear what it is.

**Comment by timrobertson100** [comment]
While [gbif/pipelines#882](https://github.com/gbif/pipelines/issues/822) remains open, I'd recommend filling `otherCatalogNumbers` with the triplet of `institutionCode:collectionCode:catalogNumber` for the target record, using the exact(!) values you'd find on the target record.

For example, if you want to connect your record to a record from _The Acme Museum_ which appears as:

```
{
  occurrenceID: urn:lsid:acme.org:mamm:don326,
  institutionCode: ACME,
  collectionCode: MAMM,
  catalogNumber: don_326,
  ...
  
}
```

If you add `otherCatalogNumbers=ACME:MAMM:don_326` on your record it will likely help improve clustering performance significantly.

This is in addition to the `references` field you currently populate using the GBIF ID which will be picked up at some point when we do another phase of development.

Beyond that I think we need to wait for [gbif/pipelines#882](https://github.com/gbif/pipelines/issues/822) to get picked up.
