### ISSUE TITLE
Same dataset indexing two times with a differnt ID

### ISSUE THREAD

**Issue by camiplata** [gbif/portal-feedback#4164]
This dataset: https://ipt.biodiversidad.co/iavh/resource?r=mamiferos_asa-fibras_2022 is been indexed two times on the portal:

1. https://www.gbif.org/dataset/1f0b0a0b-f61b-4a47-95f5-58f511399404
2. https://www.gbif.org/dataset/8bfff073-399c-4e58-897d-a437ad918092

<img width="824" alt="Captura de Pantalla 2022-07-08 a la(s) 5 15 52 p  m" src="https://user-images.githubusercontent.com/5700527/178076959-bcd6b0a9-ae15-4da8-bf6e-11c6463d72bc.png">

**Comment by ManonGros** [comment]
Thanks for reporting this issue @camiplata, I have deleted the version that isn't currently linked from your IPT. I don't know how the dataset got registered twice though. But if it is a one time event, perhaps we can close this issue?

**Comment by camiplata** [comment]
yes, it looks like a one time event
