### ISSUE TITLE
Hey, Im tring to find out how to gat plants images by plant name. for each plant im looking for hhighst numember of images, becouse its for mashine lerning use. please help me to do it simply and easly. Thanks

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4176]
**Hey, Im tring to find out how to gat plants images by plant name. for each plant im looking for hhighst numember of images, becouse its for mashine lerning use. please help me to do it simply and easly. Thanks**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/44c6547984323cc7795a653e47275277:5cfa4d8e1882dc281542535f23368f97a36db9b38d3cebd1a2bdba3d6cc6f89f926bc40c2e040f060867db38e3ef94b5ece7910de3761eca0e22492b5c3de924ff661141f300a9d0ce3e6f5826d3fa6d4a1de971613a4c236de991cbb824b36a402a6926d188858f280b5e56bdee35d86266c46f6434d4d64a07e81b2dd528829dac90191ed183880cd128e5a1a24da4) - [Send email](https://www.gbif.org/api/feedback/user/mailto/44c6547984323cc7795a653e47275277:5cfa4d8e1882dc281542535f23368f97a36db9b38d3cebd1a2bdba3d6cc6f89f926bc40c2e040f060867db38e3ef94b5ece7910de3761eca0e22492b5c3de924ff661141f300a9d0ce3e6f5826d3fa6d4a1de971613a4c236de991cbb824b36a402a6926d188858f280b5e56bdee35d86266c46f6434d4d64a07e81b2dd528829dac90191ed183880cd128e5a1a24da4)
System: Chrome 103.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/8a863029-f435-446a-821e-275f4f641165/event/115577
Window size: width 1680 - height 850
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-13T10:07:27.530Z',to:'2022-07-13T10:13:27.530Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-13T10:07:27.530Z',to:'2022-07-13T10:13:27.530Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The easiest would be to check the number of occurrence records associated images for each species. You can do so via our occurrence search web interface by selecting the Plant occurrences with images like here: https://www.gbif.org/occurrence/search?media_type=StillImage&taxon_key=6&advanced=1&occurrence_status=present. You can then either check the species with the most records on the taxonomic tab (see [here](https://www.gbif.org/occurrence/taxonomy?media_type=StillImage&taxon_key=6&advanced=1&occurrence_status=present)) or generate a Species list download.
Note that many images are digitized herbarium sheet. If you would rather not include them in your selection, you should modify the basis of record selection,  see [this example](https://www.gbif.org/occurrence/taxonomy?basis_of_record=OBSERVATION&basis_of_record=MACHINE_OBSERVATION&basis_of_record=HUMAN_OBSERVATION&basis_of_record=MATERIAL_SAMPLE&basis_of_record=MATERIAL_CITATION&basis_of_record=LIVING_SPECIMEN&basis_of_record=OCCURRENCE&media_type=StillImage&taxon_key=6&advanced=1&occurrence_status=present).

> notified by email
