### ISSUE TITLE
Versioning validation against the backbone - what backbone version is used on the API?

### ISSUE THREAD

**Issue by davidorme** [gbif/portal-feedback#4178]
Hi,

Apologies if this is documented - I've had a look and couldn't find it! 

I'm validating some taxonomy against the GBIF backbone and trying to work out the best way to assign versions to that validation. A set of taxa might all map onto one version of the backbone but then fail with a later version as taxa are reinterpreted, and I'd like to be able to pin a validation attempt to what it was validated against.

Doing this against a downloaded local database is easy because we can just use the date-stamp of the backbone dataset version from here:

https://hosted-datasets.gbif.org/datasets/backbone/

It isn't clear (or I've missed!) what version the live API is using. The options seem to be:

* The live API uses a rolling set of changes, so varies on a day to day basis, and backbone downloads are released when some threshold passes. In this case, basically only the validation date could really be used could be used to version the validation.

* The live API uses the current version, so the backbone is updated in isolation and then is made available to the API when a new version is released. In this case the backbone version datestamp very neatly pins the validation to a specific archived version.  If so, is that version datestamp available from the API? The datestamps in `backbone/current` suggest that current would be `2022-02-05`, but of course the folder is called `current`.

Many thanks,
David

**Comment by MattBlissett** [comment]
current is just a symbolic link to the newest folder in that directory.

The publication date on https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c (i.e. pubDate on https://api.gbif.org/v1/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c) should match, @mdoering might confirm.

There will be a period where these don't match, when a new backbone is published and the data is reprocessed.

**Comment by CecSve** [comment]
The issue seems resolved and I will close it. Please reopen if needed.
