### ISSUE TITLE
taxonomic ranks

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#418]
**taxonomic ranks**

Good morning,

I remember from the old website that there was a page where one could, for example, choose plants and order and than see which plant orders are in GBIF and one could then download all occurrence data of a particular order. Can this still be done with the new website? If this is still work in progress, could you maybe let me know how many plant orders GBIF covers?

Kind regards,
Laura Scherer

-----
fbitem-11604403ff7bf23fab7c5c6f98bcdc41e1c310a4
User provided contact info: l.a.scherer@cml.leidenuniv.nl
System: Firefox 45.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/top-tips-for-using-the-new-gbif-dot-org
Window size: width 1680 - height 939
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-31T09:12:41.526Z',mode:absolute,to:'2017-08-31T09:18:41.526Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-31T09:12:41.526Z',mode:absolute,to:'2017-08-31T09:18:41.526Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
Yes, this is possible on the new site:
You should go to species serach, on choose "Plantae" as higher taxon, and then check "order"  as Rank.
It will give you this result:
https://www.gbif.org/species/search?rank=ORDER&highertaxon_key=6&status=ACCEPTED&status=DOUBTFUL

As you see, there is a small badge wih the number of occurences in each order. If you click it you will be taken to the occurrence search from where a download is possible.

Best regards,
Thomas Stjernegaard
