### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4180]
**Account deletion**

Hello!

Please delete my newly created account.

sincerely
Ronny Langer

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/49b524d2ba51d402fb10d4af5809a719:b9d2eede77bfb7edebf7722bfd8f48726cfa20be33e6cc052cb85ed0bb00994b6f536bbbb49969046b4be2f36f9eda068c09dfa53b99225b5b4894dded2a24352c22de387848fbff8a07c6f4764c922d570c6654ec370759217e94dd50efdb0a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/49b524d2ba51d402fb10d4af5809a719:b9d2eede77bfb7edebf7722bfd8f48726cfa20be33e6cc052cb85ed0bb00994b6f536bbbb49969046b4be2f36f9eda068c09dfa53b99225b5b4894dded2a24352c22de387848fbff8a07c6f4764c922d570c6654ec370759217e94dd50efdb0a)
System: Firefox 102.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/terms/privacy-policy
Window size: width 1920 - height 897
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-24T20:02:27.996Z',to:'2022-07-24T20:08:27.996Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-24T20:02:27.996Z',to:'2022-07-24T20:08:27.996Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
The user account has been deleted an the user has been notified through help desk.
