### ISSUE TITLE
I would like to know hoy can we order a species from your database that we need as a positive control

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4181]
**I would like to know hoy can we order a species from your database that we need as a positive control**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2b9f5762fcea1b26ae4d4b237f5ba0d8:5ab5aa2e78a3f790c94572c99778c5f46dfb92fa743de6c6a3a25d5f800d1dff6282752b48687472bfea77a77b4e8f71827493ea49fe31c2ec1c17418f47954dcece315aa457eff068673cac98f489ffa031cd9dc890521546c18e1cd28197448421046871b0d0956d307ed901b16457f2b62b21642ae773f3a7b061dc3fd8b3) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2b9f5762fcea1b26ae4d4b237f5ba0d8:5ab5aa2e78a3f790c94572c99778c5f46dfb92fa743de6c6a3a25d5f800d1dff6282752b48687472bfea77a77b4e8f71827493ea49fe31c2ec1c17418f47954dcece315aa457eff068673cac98f489ffa031cd9dc890521546c18e1cd28197448421046871b0d0956d307ed901b16457f2b62b21642ae773f3a7b061dc3fd8b3)
System: Chrome 103.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1536 - height 714
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-25T10:53:46.867Z',to:'2022-07-25T10:59:46.867Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-25T10:53:46.867Z',to:'2022-07-25T10:59:46.867Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
The user has been contacted through help desk.
