### ISSUE TITLE
The dataset in GBIF is not indexing the data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4184]
**The dataset in GBIF is not indexing the data**

Hi, this dataset is not updated in GBIF based on the last version published through the IPT, as shown in the image below.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0cec57ce371322b25d3e50c8c4c25b90:b756e8d817e2124ff45a858e5b76b5d4b70ad5d493fca8acbb22553c0d2b96cccb3c82790e090398058ce0be726c3e3fea953fd45380369d0eb048af303022170bd52bc3c9b0348d52f5726cb29aa199acaf09c930a1dec9823fb5f126162987b8211cd2f96f68bd712d701dec2e2cfdff81a0804f86ffb994b9d13beb85b6937158b921287be0f035140c5b6fa0dd53) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0cec57ce371322b25d3e50c8c4c25b90:b756e8d817e2124ff45a858e5b76b5d4b70ad5d493fca8acbb22553c0d2b96cccb3c82790e090398058ce0be726c3e3fea953fd45380369d0eb048af303022170bd52bc3c9b0348d52f5726cb29aa199acaf09c930a1dec9823fb5f126162987b8211cd2f96f68bd712d701dec2e2cfdff81a0804f86ffb994b9d13beb85b6937158b921287be0f035140c5b6fa0dd53)
System: Firefox 100.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/dataset/edaa3a20-1d73-42ee-85f2-19105c1c8525
Window size: width 1728 - height 909
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-26T19:23:15.986Z',to:'2022-07-26T19:29:15.986Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-26T19:23:15.986Z',to:'2022-07-26T19:29:15.986Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by RicardoOrtizG** [comment]
This event dataset must have 93.474 according to the last version. In the GBIF data portal, it has 106.713.

<img width="894" alt="imagen" src="https://user-images.githubusercontent.com/15789737/181095460-cb5d4081-30da-4f4d-add1-8c519e2b577f.png">

**Comment by ahahn-gbif** [comment]
Hi @leo-buitrago, Cecilie reminded me that it would be a good idea to tag you on issues regarding CESP projects within your domain - same as for the other issue #4185

**Comment by ahahn-gbif** [comment]
@RicardoOrtizG, just to check: the dataset appears to now be indexed with 106,713 records. Does this sound plausible, or are we still missing any records?

**Comment by ahahn-gbif** [comment]
On a test through ipt.gbif.org, the different capitalization between eventID in the occurrence table and in the event core is indeed the reason for the non-ingestion - both versions need to be identical. An update in the event table, replacing the values with the same capitalization pattern, should fix this issue. The same applies to #4185

**Comment by RicardoOrtizG** [comment]
Thanks, Andrea. We are checking the errors you found in both resources and we will try to publish them again.

**Comment by camiplata** [comment]
BTW @ahahn-gbif @leo-buitrago this is not a dataset related to a CESP project,  unintendedly we added the wrong key words.

**Comment by ahahn-gbif** [comment]
From checking the record numbers at GBIF.org, is appears that both ingestion issues are fixed now - closing the issue.
