### ISSUE TITLE
The data is not indexed through the GBIF data portal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4185]
**The data is not indexed through the GBIF data portal**

The data is not indexed through the GBIF data portal. This event dataset must have 7.653 records.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ad47772d95a464fd8e3bbc4572363973:bb46a99fdee8ffed286b184ee445984e824970f1ea0bd9c25f6edbd02996283497182774da5a0824e5d502887e5b7efac0ca0d9143f702cd755d0be2fff3ed665c5e97cdc5b9ba68df3535142d60eb4a282f0ec814d75d48ddd819edd1e5422f12f13cdb9871a59ef5495f2cfaa7ed3f79beb03e57c2a2fc538167bbdf3dcabec630e8e1ef9fb4becd54e9b66f56f93e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ad47772d95a464fd8e3bbc4572363973:bb46a99fdee8ffed286b184ee445984e824970f1ea0bd9c25f6edbd02996283497182774da5a0824e5d502887e5b7efac0ca0d9143f702cd755d0be2fff3ed665c5e97cdc5b9ba68df3535142d60eb4a282f0ec814d75d48ddd819edd1e5422f12f13cdb9871a59ef5495f2cfaa7ed3f79beb03e57c2a2fc538167bbdf3dcabec630e8e1ef9fb4becd54e9b66f56f93e)
System: Firefox 100.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/dataset/f1065731-92e2-43fe-b402-ed7736b95c79
Window size: width 1728 - height 909
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-26T19:28:29.846Z',to:'2022-07-26T19:34:29.846Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-26T19:28:29.846Z',to:'2022-07-26T19:34:29.846Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by RicardoOrtizG** [comment]
![imagen](https://user-images.githubusercontent.com/15789737/181096492-5b8b5be5-d189-41b5-9e3a-4f841812ee42.png)

**Comment by ahahn-gbif** [comment]
On a quick check:
- the core table ids are lowercase only, while the foreign key in the occurrence extension is capitalized in several places. I am not sure this is the only reason, but it is worth checking that id values are identical between tables
- the configuration contains a measurementsOrFacts extension that references the occurrence table. This should not cause this kind of issue, but please be aware that extensions to DwC can only be mapped one single level deep ("star-schema")

**Comment by RicardoOrtizG** [comment]
Thanks for the recommendations, we will check it out and let you know. About the second observation you mentioned, ¿should we use the Extended Measurement or Fact extension in order to have measurements related to the occurrence in the event core?

**Comment by ahahn-gbif** [comment]
DwC-A only caters for extensions linked to the core, not for extensions linked to other extensions (adding a second level) or to each other (building cross-connections) - this is what I meant when saying "only one level deep". This is an unfortunate and recognized limitation of this schema, which is also one of the reasons driving the discussions around a new data model (see https://www.gbif.org/new-data-model). 

It will only be possible to link (and ingest) measurements that concern the event core, in this setup, not measurements for occurrences. If the content structure for measurements is less essential, it might be better to include the information in the occurrence table itself. The alternative (structuring the archive around 'occurrence.csv' as the core table) is less desirable if the event is actually a major focus in data generation and communication.

**Comment by ahahn-gbif** [comment]
Hi @leo-buitrago, Cecilie reminded me that it would be a good idea to tag you on issues regarding CESP projects within your domain

**Comment by ahahn-gbif** [comment]
Issue appears fixed, dataset correctly ingested - closing
