### ISSUE TITLE
add MBMG

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4189]
**add MBMG**

Requested by Pensoft: please add MBMG journal with its metircs and price to the list.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/9e8decc95e955ad2ab0d053368b4202e:9d6d6c25a654126a05bdf58cb6b3b842f6de34495cca11c6f8d139930ace602ad3f0b68bdb0e20255a8ec6e9edf829c720117f9b61af9022297591d0e5e1a39bc26fdc10a414ad3c873e82406e834f106506fc63154a2743d2c933aada71abcbb719a9c9b03e7bee31fb7ed01bf30b8d2e5c72af4c76df7b0911efc2877630cc) - [Send email](https://www.gbif.org/api/feedback/user/mailto/9e8decc95e955ad2ab0d053368b4202e:9d6d6c25a654126a05bdf58cb6b3b842f6de34495cca11c6f8d139930ace602ad3f0b68bdb0e20255a8ec6e9edf829c720117f9b61af9022297591d0e5e1a39bc26fdc10a414ad3c873e82406e834f106506fc63154a2743d2c933aada71abcbb719a9c9b03e7bee31fb7ed01bf30b8d2e5c72af4c76df7b0911efc2877630cc)
System: Chrome 103.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/data-papers
Window size: width 1536 - height 758
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-28T14:10:27.693Z',to:'2022-07-28T14:16:27.693Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-28T14:10:27.693Z',to:'2022-07-28T14:16:27.693Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
@kcopas is this something your team can help with?

**Comment by kcopas** [comment]
yes: that Daniel

**Comment by dnoesgaard** [comment]
Added.

| Journal                                                                                                             | Publisher                                  | Open Access (license)                                                                        | APC estimate                                                                                                                                          | Journal Impact Factor (2021) | Scopus CiteScore (2021)                             |
|---------------------------------------------------------------------------------------------------------------------|--------------------------------------------|----------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------|-----------------------------------------------------|
| [Metabarcoding and Metagenomics (MBMG)](https://mbmg.pensoft.net/)                                                  | Pensoft                                    | [CC BY](https://doaj.org/toc/2534-9708)                                                      | [from EUR 650](https://mbmg.pensoft.net/about#ArticleProcessingCharges)                                                                               | -                            | [7.9](https://www.scopus.com/sourceid/21101022488)  |
