### ISSUE TITLE
"yyyy/yyyy" format for EventDate altered 

### ISSUE THREAD

**Issue by Rafnuss** [gbif/portal-feedback#4194]
Here is an example where I've entered `eventDate` as `1970/1984` according to one of the example of https://dwc.tdwg.org/list/#dwc_eventDate. But there seems to be a modification to `1970`: 
https://www.gbif.org/occurrence/3868039317

Thanks for your help,

**Comment by Rafnuss** [comment]
I've also tried `1970-01-01T00:00:00/1984-01-01T00:00:00`, but it still doesn't seem to work

**Comment by muttcg** [comment]
Hi @Rafnuss 

You are doing everything right, you can and should use 1970/1984, we have some technical limitations with dates and at the moment GBIF portal does not support partial dates, replacing 1970 with 1970-01-01.

Also you can find similar discussion and some explanations here https://github.com/gbif/pipelines/issues/389
