### ISSUE TITLE
Musca (Diptera), move to family Muscidae.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4196]
**Musca (Diptera), move to family Muscidae.**

One more case where the type genus of a family is in the wrong family! As these are often very well known representatives of their families, these errors are a bit embarrassing!

Musca Linnaeus currently listed under Tachinidae. The correct family is naturally Muscidae.

Cheers,
Jere Kahanpää
jere.kahanpaa@helsinki.fi

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/013ad46a90a104bcb25aad1f7295674e:2c3f59e4d33c98b710b0670dc5b7ea763efd326b7d716126325703b8c22f560ec9f2ba7b7206de1b21b28574f13d473a53b3f8d682971001b55d7905eb09af1199e43513d2e7b8c58db7858d6829cd5a5e7cdcec597fc5681621198f06dc48344d57fc8247a478f8e9229e51bd6f20e9873d73af4ea46475eb4ec0d16c64e72fd8d3fa2787ffc29f800d51cc567fe723) - [Send email](https://www.gbif.org/api/feedback/user/mailto/013ad46a90a104bcb25aad1f7295674e:2c3f59e4d33c98b710b0670dc5b7ea763efd326b7d716126325703b8c22f560ec9f2ba7b7206de1b21b28574f13d473a53b3f8d682971001b55d7905eb09af1199e43513d2e7b8c58db7858d6829cd5a5e7cdcec597fc5681621198f06dc48344d57fc8247a478f8e9229e51bd6f20e9873d73af4ea46475eb4ec0d16c64e72fd8d3fa2787ffc29f800d51cc567fe723)
System: Firefox 91.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/8097933
Window size: width 1412 - height 764
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-02T13:42:33.486Z',to:'2022-08-02T13:48:33.486Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-02T13:42:33.486Z',to:'2022-08-02T13:48:33.486Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
**Musca** is in **Muscidae** in COL. 

https://www.catalogueoflife.org/data/taxon/9CJPH

>kingdom: [Animalia](https://www.catalogueoflife.org/data/taxon/N) >phylum: [Arthropoda](https://www.catalogueoflife.org/data/taxon/RT) >class: [Insecta](https://www.catalogueoflife.org/data/taxon/H6) >order: [Diptera](https://www.catalogueoflife.org/data/taxon/D2P) >family: [Muscidae](https://www.catalogueoflife.org/data/taxon/CZP) >subfamily: [Muscinae](https://www.catalogueoflife.org/data/taxon/99D25) >tribe: [Muscini](https://www.catalogueoflife.org/data/taxon/9CJB8) >genus: Musca

**Comment by mdoering** [comment]
but also in Tachinidae, @yroskov there are 2 duplicates. The one under Tachinidae contains 11 species, all of which are accepted:
https://www.catalogueoflife.org/data/search?TAXON_ID=9GLJJ&rank=species&status=accepted&status=provisionally%20accepted

**Comment by yroskov** [comment]
Yeah, unfortunately, we may have lot of provisional placements (which look like misplacements) in Systema Dipterorum@CoL. 

We are unable to catch and fix all the problems in the CoL. Master data themselves need more editorial work.

**Comment by mdoering** [comment]
There are still lots of open Diptera issues in COL apparently: https://github.com/CatalogueOfLife/data/issues?q=is%3Aissue+is%3Aopen+diptera
