### ISSUE TITLE
Please show taxonRemarks

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#420]
**Please show taxonRemarks**

At least some checklists like Clements have valuable information n the remarks field which is worth showing in the main view.

Similar the taxonID identifier used in the source might be of interest?

-----
fbitem-species133107821

System: Chrome 60.0.3112 / Mac OS X 10.12.5
Referer: https://www.gbif.org/species/133107821/verbatim
Window size: width 1480 - height 846
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-31T15:40:07.915Z',mode:absolute,to:'2017-08-31T15:46:07.915Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-31T15:40:07.915Z',mode:absolute,to:'2017-08-31T15:46:07.915Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by rdmpage** [comment]
It drives me nuts that taxonomic databases don't cite sources! The "Chesser et al. 2017" mentioned in the remarks is "Fifty-eighth supplement to the American Ornithological Society's Check-list of North American Birds" https://doi.org/10.1642/AUK-17-72.1

**Comment by mdoering** [comment]
@rdmpage, you can blame me for that.
I ahven't seen this before, but if you download the original Clements excel spreadsheet there is another reference sheet with the references resolved: http://www.birds.cornell.edu/clementschecklist/wp-content/uploads/2017/08/Clements-Checklist-v2017-August-2017.xlsx

Some even with links. They simply cite a reference like you would in a paper and provide the list of full references at the end.

_Chesser et al. 2017_ then becomes:

Chesser, R.T., K.J. Burns, C.   Cicero, J.L. Dunn, A.W. Kratter, I.J. Lovette, P.C. Rasmussen, J.V. Remsen,   Jr., J.D. Rising, D.F. Stotz, and K. Winker. | 2017. | Fifty-eighth   supplement to the American Ornithological Society's Check-list of North   American birds. | Auk 134: 751-773.

**Comment by mdoering** [comment]
Not straight forward to a) interpolate the reference abbreviation in the remarks and b) place the full reference in a dedicated field.

Best I can think of is to add the entire reference list to the dataset metadata

**Comment by rdmpage** [comment]
@mdoering Yes, a bit tedious to do the string parsing and matching :(

**Comment by mdoering** [comment]
Quite some bibliography now: https://www.gbif.org/dataset/47f16512-bf31-410f-b272-d151c996b2f6
