### ISSUE TITLE
Lonchaea Fallén, 1820 in wrong family

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4200]
**Lonchaea Fallén, 1820 in wrong family**

Another genus not in its 'own' family: 

Lonchaea Fallen should be in Lonchaeidae (now it's in Tachinidae).

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d1103b505fc09f047f66296dc68d0f0c:4dd4d08a38de4ded3d178a02f1dea4b67e3b6dfd0d0e6858fd9a340360850d5267d499a87d430e6b14424f78460f0b8995efc24ae64d932d789f2b2383f7d954a9927ff4d511e17c5f194bae3935ab731c1a4c3974083eb27a94a2cf5ee5632ad934040b3847eefa02edcf6a79b6a6a90b227be71692159209537deef39c0b350292de9c2d256e7d5cbbd39618fa657b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d1103b505fc09f047f66296dc68d0f0c:4dd4d08a38de4ded3d178a02f1dea4b67e3b6dfd0d0e6858fd9a340360850d5267d499a87d430e6b14424f78460f0b8995efc24ae64d932d789f2b2383f7d954a9927ff4d511e17c5f194bae3935ab731c1a4c3974083eb27a94a2cf5ee5632ad934040b3847eefa02edcf6a79b6a6a90b227be71692159209537deef39c0b350292de9c2d256e7d5cbbd39618fa657b)
System: Firefox 91.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/1529245
Window size: width 1412 - height 764
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-02T13:58:05.474Z',to:'2022-08-02T14:04:05.474Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-02T13:58:05.474Z',to:'2022-08-02T14:04:05.474Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by camiplata** [comment]
[Fixed on COL](https://github.com/CatalogueOfLife/data/issues/457)

**Comment by camiplata** [comment]
Also fixed on GBIF

<img width="387" alt="Captura de pantalla 2024-06-13 a la(s) 11 02 32 a m" src="https://github.com/gbif/portal-feedback/assets/5700527/025ca997-2fc1-49cb-9c15-d66ad1b124b7">
