### ISSUE TITLE
News API page (almost) empty and with a broken link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4206]
**News API page (almost) empty and with a broken link**

The News API documentation page at https://www.gbif.org/developer/news is not very instructive right now. Would it be better to hide it from view until we have something more informative to show?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/23274a5213f8d1976751ad5f0e478d45:10abf8ef911aed1c38b4cea5305163c469bb94a4777099059fb258096aaa6fc3ab487ab780c6336902f777d674fa8a4d41ec541b831a48bf8075ebc7d81ea08ad8318c654559d34563da03ff3032c1cf9ab394667b74b7c5bd5fbcedf133f31d9fe1329876f9bcf652e5f221732db3de022d3e69a30987971537eb7b30739298) - [Send email](https://www.gbif.org/api/feedback/user/mailto/23274a5213f8d1976751ad5f0e478d45:10abf8ef911aed1c38b4cea5305163c469bb94a4777099059fb258096aaa6fc3ab487ab780c6336902f777d674fa8a4d41ec541b831a48bf8075ebc7d81ea08ad8318c654559d34563da03ff3032c1cf9ab394667b74b7c5bd5fbcedf133f31d9fe1329876f9bcf652e5f221732db3de022d3e69a30987971537eb7b30739298)
System: Firefox 103.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/developer/news
Window size: width 1261 - height 837
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-03T09:07:53.693Z',to:'2022-08-03T09:13:53.693Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-03T09:07:53.693Z',to:'2022-08-03T09:13:53.693Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@ahahn-gbif I agree it does look weird. I *think* it has been like this from the begining. Probably just ported from the previous site as was (except the link has since been broken I assume). 
I'll try to find out if this page should be dropped or we actually have something meaningful to show.
Thanks

UPDATE: I've removed the news section

**Comment by MortenHofft** [comment]
I do not believe we have a stable news API. We have an rss feed. We have an RSS feed linked from here https://www.gbif.org/resource/search?contentType=news
