### ISSUE TITLE
No way to select other backbone constituents than the top 10

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#421]
**No way to select other backbone constituents than the top 10**

It is impossible to select backbone constituents that are not in the top 10 most frequent ones. Maybe allow paging or even better some title lookup like for the dataset filter?

-----
fbitem-1f059dd0d137ccd641e791a2992ee7e29204a773

System: Chrome 60.0.3112 / Mac OS X 10.12.5
Referer: https://www.gbif.org/species/search?advanced=1
Window size: width 1423 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-01T09:06:45.236Z',mode:absolute,to:'2017-09-01T09:12:45.236Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-01T09:06:45.236Z',mode:absolute,to:'2017-09-01T09:12:45.236Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
transferred to https://github.com/gbif/portal16/issues/551
