### ISSUE TITLE
Misinterpretation of occurrenceStatus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4210]
**Misinterpretation of occurrenceStatus**

This dataset (https://www.gbif.org/dataset/fca5e616-990e-4d62-adc3-3122ed64b8e8) contains absence record. The occurrencStatus is in fact "absent" for most records and the organismQuantity is 0.
However, we interpret it as "PRESENT".
This was reported by one of the publishers.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/894599d1e70c58fb3e5c7db427cb9d8a:1384913669ab3003ca809c6f8c1bc3e39359b2c8c4e9ff83a50803ec9103028418f05008b2a4b42a24de74c42a33896c16678552a41749adc944f09487b43003f0688eb9077a249070cb38ec12045fd3a013dbfaa617e1b2a30634236e051e1353145eacfe0cb914c6959a94e96db447061c1dcbca03ea323a3ca26b830ba3dd4129771b0150a71abf50066a45503697) - [Send email](https://www.gbif.org/api/feedback/user/mailto/894599d1e70c58fb3e5c7db427cb9d8a:1384913669ab3003ca809c6f8c1bc3e39359b2c8c4e9ff83a50803ec9103028418f05008b2a4b42a24de74c42a33896c16678552a41749adc944f09487b43003f0688eb9077a249070cb38ec12045fd3a013dbfaa617e1b2a30634236e051e1353145eacfe0cb914c6959a94e96db447061c1dcbca03ea323a3ca26b830ba3dd4129771b0150a71abf50066a45503697)
System: Safari 15.3.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/3882059407
Window size: width 1332 - height 871
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-09T13:30:36.344Z',to:'2022-08-09T13:36:36.344Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-09T13:30:36.344Z',to:'2022-08-09T13:36:36.344Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: fca5e616-990e-4d62-adc3-3122ed64b8e8
publishingOrgKey: 46718b9b-f349-439e-bab5-3fd4200b66f7

Node handles: @albenson-usgs

**Comment by timrobertson100** [comment]
I notice v1.3 did not have `occurrenceStatus` mapped and v1.4 does.

I suspect 1.3 was published, GBIF started crawling, then 1.4 was produced while crawling was in progress so the request to crawl was ignored.

~I have triggered a crawl now, and suspect this will fix it. https://registry.gbif.org/dataset/fca5e616-990e-4d62-adc3-3122ed64b8e8/ingestion-history~

Edited: Looks correct now https://www.gbif.org/occurrence/search?dataset_key=fca5e616-990e-4d62-adc3-3122ed64b8e8&occurrence_status=absent @ManonGros

**Comment by ManonGros** [comment]
Thanks Tim! it looks good now
