### ISSUE TITLE
I am working with a protected threatened taxon, how do I get more accurate spatial locations? The informationWithheld is >28k uncertainty. I have 6 species that I would like accurate location information for modeling distribution.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4211]
**I am working with a protected threatened taxon, how do I get more accurate spatial locations? The informationWithheld is &gt;28k uncertainty. I have 6 species that I would like accurate location information for modeling distribution.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d043964f60d68efdde882b24d7ab746a:c8534e8398df6154b180d38456e8a489f501cc95c6f0916be2d9e87b35d19bcb5b048c585229a1b84c75fc3905182652e800f3673b0e34ba5330dc60bab5fc447193c98d63766e923e3a77c280dcd0396e29f1c17f234aa3e722fd942bfafc4c02608b8c148c736d8964d04bf21d94d1) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d043964f60d68efdde882b24d7ab746a:c8534e8398df6154b180d38456e8a489f501cc95c6f0916be2d9e87b35d19bcb5b048c585229a1b84c75fc3905182652e800f3673b0e34ba5330dc60bab5fc447193c98d63766e923e3a77c280dcd0396e29f1c17f234aa3e722fd942bfafc4c02608b8c148c736d8964d04bf21d94d1)
System: Chrome 104.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1243 - height 667
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-09T13:46:04.810Z',to:'2022-08-09T13:52:04.810Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-09T13:46:04.810Z',to:'2022-08-09T13:52:04.810Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
Responded via email. 

GBIF does not store more lat-lon values. To get unobscured values, one has to contact the original data publisher.
