### ISSUE TITLE
Questions on ease of data access and source copyrights

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4214]
**Questions on ease of data access and source copyrights**

Hi GBIF

I really like how data here is assembled to allow for public information and CC BY 4.0 commercial usage. As alot of animal diversity by distribution data is locked into firms for non commercial usage. By making data free it will help with innovation for env, health and the economy. 

My question for you is: With your 10000s of data sources that can be exported on organism taxa. When the data comes through in SQL or on the cloud, does the data include the full citation, not just the DOI? Sort of like your, webpage Citation embedding wizard. But just as a full SQL export. It would be to long a tedious to reference that many, but if its ready can just upload to the page or use your widget. If you dont export the full reference, how would i convert all those DOI to references in such a massive size? Yes i know python, also endnote and SQL.

My second question for you is: With the source affirmation that the publisher did check and warrant that all third parties were accounted for and is free under CC0 ( I selected CC0) or CC BY 4.0 (I selected CC BY4.0 directly to prevent infringements), accounting for every reference in that published page or article. If something was missed by a publisher and i used articles that had a hidden non commercial claim, somewhere in that article? Am i protected or would i be able to pursue the publisher who made that false claim (or you put in protections)? Its not about quality as such, infact double checking this data looks fantastic. Its just that i dont want to put all references up and find some had hidden third parties and be sent a infringement notice. I mean all these references are assembled primary source or are they meta-anayltical (secondary sources may have hidden third parties behind the papers)? How do you prevent an unnotified deliberate or accidental copyright overstep by the publisher e.g a publisher lies or is negligent, do you have checks before submission to GBIF? How do you validate the publishers claim to complete CC0 1.0 or CC BY 4.0?

Thanks GBIF for any assistance you can provide towards these questions.
From Jordan

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c0bc3099acb2658d44c75f3a1a698244:162536cb5364df668ea802d53b1cd204a4b5decba864979119338a74f099e602d9db292d6a278c40556d94267c89feca4d4a23c193f9ab870b39942af28ee7256f494902c113af4dabc45040099547142515c889bb33eaf9c662e7b067664e33) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c0bc3099acb2658d44c75f3a1a698244:162536cb5364df668ea802d53b1cd204a4b5decba864979119338a74f099e602d9db292d6a278c40556d94267c89feca4d4a23c193f9ab870b39942af28ee7256f494902c113af4dabc45040099547142515c889bb33eaf9c662e7b067664e33)
System: Firefox 103.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/map?q=fishes&license=CC_BY_4_0&license=CC_BY_NC_4_0&license=CC0_1_0
Window size: width 1536 - height 731
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-13T08:51:11.755Z',to:'2022-08-13T08:57:11.755Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-13T08:51:11.755Z',to:'2022-08-13T08:57:11.755Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> In any case, if you generate a GBIF a download via our [web interface](https://www.gbif.org/occurrence/search?occurrence_status=present&q=) or [API](https://www.gbif.org/developer/occurrence#download), a citable DOI will automatically be generated. If you access data on one of the cloud service and you are planning to filter it down, the best is to use our derived dataset service. You can do so via [our web interface](https://www.gbif.org/derived-dataset/register) or via [our API](https://github.com/gbif/registry/blob/dev/docs/derived-dataset.md). In either case, you will have to provide the keys or DOIs for the dataset from which the data you used came from. This is something that you should be able to generate programmatically as the occurrence data includes those dataset keys.
 
> I am not sure I understand your questions here. It would help to know a bit more about your use case. I encourage you to check our terms and agreements if you haven’t already: https://www.gbif.org/terms
I can tell you that all data providers on GBIF should have agreed to our data publisher agreement: https://www.gbif.org/terms/data-publisher. In case of doubt, you are always welcome to contact the data providers directly to ask questions about specific datasets.
 
> Keep in mind that images displayed on GBIF don’t necessarily have the same licenses as occurrences. We strongly advise to always check the license of any image you might be interested in using.
