### ISSUE TITLE
Confirm all is well with this dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4215]
**Confirm all is well with this dataset**

Hi All, I created a dataset. I started download and then David Shorthouse @dpsspiders said I didn't need to. That he would download. So I cancelled my download. His link works for me to see the download this way: 
https://www.gbif.org/occurrence/download/0418303-210914110416597 

BUT, I see "Cancelled" when I log into GBIF myself
https://www.gbif.org/occurrence/download/0418273-210914110416597

Need: please confirm the dataset won't go anywhere? Or do we just use David's link and not mine anymore?

Thanks for the help. Happy to answer questions if the above scenario is confusing.

@debpaul on gitHub

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b6875e9f47f32c1dd836f2718ab5f3d0:1cfaa55a2d29b8c5dcc24d17d7247a8531333bd763001d7725eb5b532426d85a807ba5db8fd7faf6cd3114ddc7f354fd7a185543eedef247bd6ef8e010c5788a0091ea13ea04bd3de4f8e9453a9f5d93f71d75548d2a69501e610fe18e7032f873df1da5d38bce35092272ea8490daed577e88cef76460fc6345dd4b06436f52) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b6875e9f47f32c1dd836f2718ab5f3d0:1cfaa55a2d29b8c5dcc24d17d7247a8531333bd763001d7725eb5b532426d85a807ba5db8fd7faf6cd3114ddc7f354fd7a185543eedef247bd6ef8e010c5788a0091ea13ea04bd3de4f8e9453a9f5d93f71d75548d2a69501e610fe18e7032f873df1da5d38bce35092272ea8490daed577e88cef76460fc6345dd4b06436f52)
System: Firefox 103.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0418273-210914110416597
Window size: width 1469 - height 811
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-15T20:57:38.996Z',to:'2022-08-15T21:03:38.996Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-15T20:57:38.996Z',to:'2022-08-15T21:03:38.996Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@debpaul 
It is 2 different downloads with different DOIs. One was cancelled, the other one wasn't. They just happen to have the same filter.
The cancelled one was assigned a DOI, but never generated as it was cancelled.

https://www.gbif.org/faq?question=for-how-long-will-does-gbif-store-downloads

So everything looks fine to me
