### ISSUE TITLE
Toggle map style

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4218]
**Toggle map style**

Toggle map style button in MAP overview (search occurrences) is inactive.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/93782931dc12def69d7682b876df5781:ec030c618a43cc5d06dad7ec734177caf226b16bd294bcf44723424699371d5525a1f352014f667fa39793ddee790a9ae0d3f45f19bf2fed6925cbe37467df7f8b9216b3eecb02f5363016ded43d6345acd7d30f729a8ce0ea6461b658d5fb9243de9b74ede4868ad4cae034a42c36ca) - [Send email](https://www.gbif.org/api/feedback/user/mailto/93782931dc12def69d7682b876df5781:ec030c618a43cc5d06dad7ec734177caf226b16bd294bcf44723424699371d5525a1f352014f667fa39793ddee790a9ae0d3f45f19bf2fed6925cbe37467df7f8b9216b3eecb02f5363016ded43d6345acd7d30f729a8ce0ea6461b658d5fb9243de9b74ede4868ad4cae034a42c36ca)
System: Firefox 103.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&occurrence_status=present
Window size: width 1155 - height 591
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-18T16:07:00.390Z',to:'2022-08-18T16:13:00.390Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-18T16:07:00.390Z',to:'2022-08-18T16:13:00.390Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by MortenHofft** [comment]
I'm unable to reproduce any errors. Could you expand on the issue you experience please? What you should expect to see is that the background map changes from grey to blue/green (and more details). The dots remain yellow/red.

If you can provide me with more details, then I would be happy to reopen the issue.

> user contacted per email for more information
