### ISSUE TITLE
wrong tab when backbone filter is selected in advanced

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#422]
**wrong tab when backbone filter is selected in advanced**

When the backbone dataset is selected as a filter in the advanced search still the ALL CHECKLIST tab shows which is confusing, as the search result in this case is just the backbone.

Features like constituent search are not available in the simple search and one needs the advanced search in this case

-----
fbitem-1f059dd0d137ccd641e791a2992ee7e29204a773

System: Chrome 60.0.3112 / Mac OS X 10.12.5
Referer: https://www.gbif.org/species/search?dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&constituent_key=c33ce2f2-c3cc-43a5-a380-fe4526d63650&advanced=1
Window size: width 1423 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-01T09:09:57.364Z',mode:absolute,to:'2017-09-01T09:15:57.364Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-01T09:09:57.364Z',mode:absolute,to:'2017-09-01T09:15:57.364Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I'm not convinced this is confusing. Choosing to search all checklists and then actively filtering to only show a specific dataset shouldn't leave too much room for confusion I would think. The tab allow you to search all checklist, but the users can decide not to. Any filter for any dataset would make the tab title "wrong". If the selected dataset had been `International Plant Names Index` then the tab `all checklists` would also be wrong.

Anyhow - I have renamed the tabs to simple and advanced.

**Comment by MortenHofft** [comment]
The change will be visible on next release
