### ISSUE TITLE
Hw can I correct and update the page for GC University, Lahoe

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4222]
**Hw can I correct and update the page for GC University, Lahoe**

The dept. head contacted me and asked me to update the information. I have updated OpenHerbarium, through which they began to share data. They stopped adding records because, I was told, too much curation was required before they could do so. I shall check their informatioin in Index herbariorum, but it was the GBIF page, which I suspect came from OpenHerbarium, that was the problem. Thought: Perhaps if I update their DWC archives that will take care of it. If you know it will, then nothing more to do on your side. It the metadata are not normally updated, I shall need a reminder on how to edit the GBIF data.
Thanks.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a386c98480b1600fe3f22b95d6f1a24b:72c39faf7acfa9a062747b6a907dc69dafbc57f2cf0c5f57ec0152fdbbca451c9e19427aaf82b717382eca91f02e56f9357515242bed9864f1bb0f0729015b8831540bfaed3040398cc455db432d472721eececdb43470361eeeb8ce59adfafb9240e594c164a1a2c117ab8b63c38bf96eea83b1e56712d98e4f41ef4b7e07192e3358b43fa604638d2d88468ff1f50a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a386c98480b1600fe3f22b95d6f1a24b:72c39faf7acfa9a062747b6a907dc69dafbc57f2cf0c5f57ec0152fdbbca451c9e19427aaf82b717382eca91f02e56f9357515242bed9864f1bb0f0729015b8831540bfaed3040398cc455db432d472721eececdb43470361eeeb8ce59adfafb9240e594c164a1a2c117ab8b63c38bf96eea83b1e56712d98e4f41ef4b7e07192e3358b43fa604638d2d88468ff1f50a)
System: Chrome 104.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/d5e9316e-8600-45b4-9eb3-f6ba38460ed1
Window size: width 1536 - height 750
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-23T10:23:15.482Z',to:'2022-08-23T10:29:15.482Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-23T10:23:15.482Z',to:'2022-08-23T10:29:15.482Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
The user has been contacted by email and had a similar request on help desk last week. The publisher contact information was updated last week but may require further updates.

**Comment by CecSve** [comment]
No new update requests have been submitted so I will close the issue
