### ISSUE TITLE
elevation

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4226]
**elevation**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0250395f791b3d99b3f08af5a6b2acc8:35b5d164c63e6e9bbe64a6c51f8b49aa32cce11556f1ceebcc291c4fb41c8fc1002925fe5bf8a877fd0ea5f3a758e0116f7f8882411f5c684c77f5c3cd9584ca59ce6fb3f4a5b023f436d9145ef2619e1137cdab21a1b1c396882e84e816ac74) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0250395f791b3d99b3f08af5a6b2acc8:35b5d164c63e6e9bbe64a6c51f8b49aa32cce11556f1ceebcc291c4fb41c8fc1002925fe5bf8a877fd0ea5f3a758e0116f7f8882411f5c684c77f5c3cd9584ca59ce6fb3f4a5b023f436d9145ef2619e1137cdab21a1b1c396882e84e816ac74)
System: Chrome 104.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/citation-guidelines
Window size: width 1280 - height 609
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-23T20:06:14.623Z',to:'2022-08-23T20:12:14.623Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-23T20:06:14.623Z',to:'2022-08-23T20:12:14.623Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Perhaps related to https://www.gbif.org/occurrence/download/0429933-210914110416597
but unclear what the user means. I'm closing as invalid
