### ISSUE TITLE
This is suspicious -test

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4227]
**This is suspicious -test**

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/765d576a4977f25418711712a945fdf9:252d95a5d6810896237f77883aa8f82cf1c1413600392dde8348476f89e096e393abde399a033a8ace55e559a9abd5c4463fb449b329d011d92cf7874e727d133f24fbff50c72edc0e5f9d3768739be1797958e1524405067e32e9b6139ac276df8ee5613c402575472338e6776856913fc91642f73b3a35291fe4de9ae4057a20337bf32730942c859756df312f0c70) - [Send email](https://www.gbif.org/api/feedback/user/mailto/765d576a4977f25418711712a945fdf9:252d95a5d6810896237f77883aa8f82cf1c1413600392dde8348476f89e096e393abde399a033a8ace55e559a9abd5c4463fb449b329d011d92cf7874e727d133f24fbff50c72edc0e5f9d3768739be1797958e1524405067e32e9b6139ac276df8ee5613c402575472338e6776856913fc91642f73b3a35291fe4de9ae4057a20337bf32730942c859756df312f0c70)
System: Safari 15.3.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/map?taxon_key=7&geometry=POLYGON((-4.93251%2010.86581,3.78874%207.05325,-2.78794%2015.67918,-4.93251%2010.86581))&occurrence_status=present
Window size: width 1289 - height 867
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-24T08:46:55.654Z',to:'2022-08-24T08:52:55.654Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-24T08:46:55.654Z',to:'2022-08-24T08:52:55.654Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
kk. I will make a rule to fix it. This is the last you will hear from me. Godspeed
