### ISSUE TITLE
List of extant species scientific names

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4228]
**List of extant species scientific names**

I would like a list of taxonomic names including higher taxonomies for each species for the 5 fish classes.  I have tried downloading the taxonomic backbone and filtering out palaeo datasets but keep getting extinct species coming from other cheklists.  Do you have associated data for cheklists datasets in the taxonomic backbone on whether these names are fossil species to develop a custom filter. If this exist could you help in producing a custom download of non-fossil fish species names.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/cd4303e28df26631b36621fce2b8ebdc:4d841310ec7d3beb92330ebdf336fdcbe24a34895728efcb90b98c1d32e84233d9ef82aaf229255ede194edb8a47e2bc211d321be067b556e0def7517a7f8dd263a3bae3253d35cc452c3398874cd0bde62d60cecf1bb0737fe25991bb30b77e7ef9f43e6fb054884cd6a619ac9302f99380c9b9c46daf23f7424631bf37479943d3d0f68204b0cb322a1769e8529a31) - [Send email](https://www.gbif.org/api/feedback/user/mailto/cd4303e28df26631b36621fce2b8ebdc:4d841310ec7d3beb92330ebdf336fdcbe24a34895728efcb90b98c1d32e84233d9ef82aaf229255ede194edb8a47e2bc211d321be067b556e0def7517a7f8dd263a3bae3253d35cc452c3398874cd0bde62d60cecf1bb0737fe25991bb30b77e7ef9f43e6fb054884cd6a619ac9302f99380c9b9c46daf23f7424631bf37479943d3d0f68204b0cb322a1769e8529a31)
System: Chrome 104.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search
Window size: width 1422 - height 641
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-24T15:58:24.520Z',to:'2022-08-24T16:04:24.520Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-24T15:58:24.520Z',to:'2022-08-24T16:04:24.520Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
User also contacted by email with the following response:

> It is unfortunately not possible to exclude extinct species from the backbone as it is compiled across many different checklists that may not supply this sort of data. The large majority of taxonomic data in the backbone comes from the [Catalogue of Life](https://www.catalogueoflife.org/) (CoL) where it is possible to exclude extinct species. I would therefore encourage you to extract the names you need from CoL instead of GBIFs backbone, if you are only interested in extanct species.
