### ISSUE TITLE
Taxon remarks illegible on mobile

### ISSUE THREAD

**Issue by rdmpage** [gbif/portal-feedback#423]
Viewing https://github.com/gbif/portal-feedback/issues/420 on my iPhone I couldn't read the verbatim remarks that were being discussed. On my phone the display looked like this:
![file 01-09-2017 10 40 37](https://user-images.githubusercontent.com/83306/29964578-65fb5056-8f02-11e7-9b85-9d9c6766b70c.png)

On my Mac if I shrink the window I can still see the remarks
![screenshot 2017-09-01 10 40 00](https://user-images.githubusercontent.com/83306/29964552-4e1cb970-8f02-11e7-8cdd-5ffd3eda341b.png)

I'm guessing that the problem is the URL for the terms being unwrappable. If the text was styled with  "word-wrap: break-word" maybe this would fix the problem. Alternatively maybe hide the term URL on small screens. Most people won't care about them (at least, they won't care as much as not being able to read the contents of the term).

**Comment by mdoering** [comment]
+1 for hiding the term URLs on small screens
