### ISSUE TITLE
common name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4230]
**common name**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/cc0aa779134bf2a612e228f1e448d4fd:8a4d2f838f6aec27d03bfb5f6c7fb2903ca404f330947b17d77d2cd969f67fed500e46044c99f2cd5595a2483fb7dbbdd9c2628e0956aa3e793b022e8003f0f1b78d9228d196354b38f7652defb90cbb4fdcde44f3a2fc06204fa59a02c47ea2) - [Send email](https://www.gbif.org/api/feedback/user/mailto/cc0aa779134bf2a612e228f1e448d4fd:8a4d2f838f6aec27d03bfb5f6c7fb2903ca404f330947b17d77d2cd969f67fed500e46044c99f2cd5595a2483fb7dbbdd9c2628e0956aa3e793b022e8003f0f1b78d9228d196354b38f7652defb90cbb4fdcde44f3a2fc06204fa59a02c47ea2)
System: Chrome 104.0.5112 / Windows 10.0.0
Referer: https://www.gbif.org/system-health
Window size: width 1536 - height 732
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-28T14:42:08.042Z',to:'2022-08-28T14:48:08.042Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-28T14:42:08.042Z',to:'2022-08-28T14:48:08.042Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
There is not enough information to do anything. I will close the issue and inform the user.
