### ISSUE TITLE
Taxon linking interpretation from verbatim if no scientificName provided

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4231]
**Taxon linking interpretation from verbatim if no scientificName provided**

Hi!

Esko from FinBIF here.

Example case: https://www.gbif.org/occurrence/3861711423
Here we do not send anything to GBIF as "scientificName" since the name given by the user is unknown to us (non-finnish species). We send unknown names as "Verbatim identification". 

It would be great that in these cases - when scientific name is not given - you would try to match verbatim name for taxon linking?

We'd not like to send all our unknown names as scientificName since they sometimes are not that -- they may be vernacular names, bird species codes etc.

Thanks!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fadcb78cc570f433bb803530dc5bf12c:0907bb8fddaa7e6d220711f93750083896998c845487fc99c16ceb21717d0cc37423123b93ea1384e96fd2fe950811b0149517f6710172f540c2699d8996513d9a8b1b98963ee2448a1a14fea1b5418c995765944bd30735dc85d7ab90060a9d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/fadcb78cc570f433bb803530dc5bf12c:0907bb8fddaa7e6d220711f93750083896998c845487fc99c16ceb21717d0cc37423123b93ea1384e96fd2fe950811b0149517f6710172f540c2699d8996513d9a8b1b98963ee2448a1a14fea1b5418c995765944bd30735dc85d7ab90060a9d)
System: Firefox 103.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/3861711423
Window size: width 1920 - height 995
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-29T10:49:29.895Z',to:'2022-08-29T10:55:29.895Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-29T10:49:29.895Z',to:'2022-08-29T10:55:29.895Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: df12ca07-f133-4550-ab3b-fde13f0e76ba
publishingOrgKey: 04fd2e13-6881-4e5c-9dd1-8fdd9ab993c1

**Comment by esko-piirainen** [comment]
:)

**Comment by esko-piirainen** [comment]
@CecSve Do you think this might be implemented at some point? If not, we can start making adjustments in our end.

**Comment by CecSve** [comment]
> @CecSve Do you think this might be implemented at some point? If not, we can start making adjustments in our end.

I think it would be best if you make the adjustments on your end, if possible. Ideally, vernacular names should be mapped to the [vernacularName](http://rs.tdwg.org/dwc/terms/vernacularName) field. @muttcg or @mdoering might have input on whether it would be possible for us to interpret on verbatim name if no scientificName is provided?

**Comment by mdoering** [comment]
@muttcg I suppose pipelines could use the [dwc:verbatimIdentification](http://rs.tdwg.org/dwc/terms/verbatimIdentification) value if no scientificName is found and try to match that as if it was a scientificName? There is no way for us to match vernacular names and there is also no plan for us to do so. These are just too unspecific - though they could yield matches in some cases I suppose.

**Comment by esko-piirainen** [comment]
> I suppose pipelines could use the [dwc:verbatimIdentification](http://rs.tdwg.org/dwc/terms/verbatimIdentification) value if no scientificName is found and try to match that as if it was a scientificName

@CecSve @mdoering 
What is stated above would be perfect 


(We don't care about vernacular names in this case -- I mentioned them just as an example of why we do not want to put "unknown" names to dwc:scientificName field -- since the names are unknown, we do not know if they are scientific or vernacular or other names.

Any idea if this could be implemented and when?

**Comment by mdoering** [comment]
@fmendezh @muttcg would be best to know. It does not sound very  difficult.

**Comment by esko-piirainen** [comment]
Any updates? If not, we can start working on an alternative solution

**Comment by muttcg** [comment]
I will try to deploy fix to UAT today for testing

**Comment by CecSve** [comment]
@esko-piirainen as @muttcg mention we will test and see if we can apply the change. We will let you know whether it is possible, when we have looked at the results.

**Comment by muttcg** [comment]
@esko-piirainen @CecSve Changes deployed to UAT for testing:
The same record: https://www.gbif-uat.org/occurrence/3049454295
https://www.gbif-uat.org/occurrence/search?dataset_key=f589e9e8-9654-468b-97de-46ff4fe50fc6

**Comment by CecSve** [comment]
The change would affect **34 datasets** and **30,418 occurrences**. The datasets are **published by 8 different countries** and **76.5% of the datasets are from Finland** and **96% of the occurrences are from Finland**. 

The changes to the other countries datasets seem to either cause no change or in some cases also provide taxon match, so I think we can safely put the fix in production @muttcg, if @esko-piirainen confirms.

@esko-piirainen there is two things to be aware of when we apply the fix on our side instead of your side:

1. users looking at the archive endpoint you provide will not be presented with the same data view as they see in our portal and may struggle to use the data
2. if you supply homonyms in the verbatimIdentification field, the lack of higher taxonomy may cause records to be misplaced in higher taxonomies

Are this risks acceptable for you or would you prefer to make the changes on you side?

**Comment by esko-piirainen** [comment]
These are valid points, but we are happy if you can implement the change in production!

For the first one, there is no changes to current situation before or after this GBIF-internal interpretation change; so our data's use(lessness) will remain the same.

Second: This is of course not ideal. However it might be noted, that even for the records that we currently DO offer a dwc:scientificName, we do not always know if the higher taxonomy is actually correct. For example we have lots of occurrences that are reported on genus level, but our backbone taxonomy only has the animalia genus, and we do not know anything about the homonym plantae genus -> we interpret the occurrence as animalia, even though it should be plantae. 

___

Overall, we have had for a long time a goal to start using GBIF backbone taxonomy as an extension of our internal taxonomy backbone for names unknown to our internal backbone. When that feature is completed, it will fix many problems in our own services; and it would also would fix this problem with GBIF taxon linking. The feature is however still some ways away from being ready, so having this quick fix now is much appreciated!

Let me know when it is in prod and occurrences have been re-interpreted, so I can inform our users that problems in GBIF related to our foreign occurrences/species are now fixed.
Thank you!

**Comment by CecSve** [comment]
@muttcg please go ahead and put the fix in production then.

**Comment by muttcg** [comment]
@esko-piirainen it is deployed to PROD and occurrences have been re-interpreted
