### ISSUE TITLE
Vernacular names not being returned by /species/search

### ISSUE THREAD

**Issue by wellcaffeinated** [gbif/portal-feedback#4238]
Hi, 

The search api endpoint is no longer returning vernacular names in the results.

Example:

https://api.gbif.org/v1/species/search?qField=VERNACULAR&status=ACCEPTED&q=house%20cat

```json
{
  "offset": 0,
  "limit": 20,
  "endOfRecords": false,
  "count": 31,
  "results": [
    {
      "key": 100220634,
      "datasetKey": "b351a324-77c4-41c9-a909-f30f77268bc4",
      "nubKey": 2435035,
      "scientificName": "Felis catus",
      "canonicalName": "Felis catus",
      "nameType": "SCIENTIFIC",
      "taxonomicStatus": "ACCEPTED",
      "origin": "SOURCE",
      "numDescendants": 0,
      "numOccurrences": 0,
      "habitats": [
        
      ],
      "nomenclaturalStatus": [
        
      ],
      "threatStatuses": [
        
      ],
      "descriptions": [
        
      ],
      "vernacularNames": [
        
      ],
      "synonym": false,
      "higherClassificationMap": {
        
      }
    },
    // ...
```

The api used to output vernacular names which i made heavy use of for filtering relevant results. I use the gbif api for the name searching functionality of the Tree of Life Explorer: https://labs.minutelabs.io/Tree-of-Life-Explorer/

Hope this is a quick fix. Thanks!

**Comment by marcos-lg** [comment]
Fixed in PROD.

**Comment by wellcaffeinated** [comment]
Hi there
This seems to be broken again. Maybe a regression bug?

**Comment by MortenHofft** [comment]
The first result is empty, but the second returns them just fine. It seems wrong since it is a vernacular name search. So I would expect it to always have at least one vernacular name.

First result
```json
{
"key": 100220634,
"vernacularNames": [],
},
```

But if I go to the actual entry I get: https://api.gbif.org/v1/species/100220634/vernacularNames then the results show just fine.

**Comment by wellcaffeinated** [comment]
I think in my app I've been filtering by a certain dataset key.
My request is:
https://api.gbif.org/v1/species/search?qField=VERNACULAR&status=ACCEPTED&dataset_key=fab88965-e69d-4491-a04d-e3198b626e52&q=cat

and then i filter by results that contain vernacular names of the requested `q` field ("cat"). But these results don't have any entries in their vernacularNames... so they get dropped.

**Comment by marcos-lg** [comment]
Fixed

**Comment by wellcaffeinated** [comment]
@marcos-lg Thank you!!
