### ISSUE TITLE
¿How to get the Wikidata ID from the species API?

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/portal-feedback#4239]
Hi!

I have a question, It's possible to get the WikidataID from the GBIF species API? I can't find a parameter that returns this information for each species on a list. It may help us to improve the connection between our species list services to reference other species profiles or descriptions pages like the ones available for eBird or iNat. 

Example: (Tachornis squamata (Cassin, 1853))[https://www.gbif.org/es/species/2477436]

These is the links we want to get:

<img width="1212" alt="imagen" src="https://user-images.githubusercontent.com/15789737/188722816-b04b5792-29fd-4bb7-a6fe-44015b7847fc.png">

Thanks!

**Comment by ManonGros** [comment]
Hi @RicardoOrtizG, our website uses the Wikidata API to display the Wikidata identifiers. See: https://discourse.gbif.org/t/given-a-gbif-human-readable-webpage-for-a-species-how-to-find-the-api-call-for-each-item-on-the-page/3134/4

I will close the issue now, let me know if it should be reopened.
