### ISSUE TITLE
Phylum with type specimen

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#424]
**Phylum with type specimen**

For ranks of genus or above there are no type specimens so it does not make sense to show them. 

In this case the record is interpreted correctly, but it cannot be a type specimen for a phylum. Maybe occurrence processing should verify that a type specimen has a species or infraspecific rank, raise a flag otherwise and even change the interpreted data?

-----
fbitem-species62

System: Chrome 60.0.3112 / Mac OS X 10.12.5
Referer: https://www.gbif.org/species/62
Window size: width 1423 - height 842
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-01T12:13:44.294Z',mode:absolute,to:'2017-09-01T12:19:44.294Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-01T12:13:44.294Z',mode:absolute,to:'2017-09-01T12:19:44.294Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
Type specimen of phylum Onychophora from New Zealand Arthropod Collection (NZAC)
https://www.gbif.org/occurrence/1315620984

**Comment by ManonGros** [comment]
The specimen from NZAC seems to be a species (https://www.gbif.org/species/2235589). I am closing the issue.
