### ISSUE TITLE
Resources is not indexing the new number of records

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4240]
**Resources is not indexing the new number of records**

We are having problems with this dataset, we made an actualization adding 17 new records, but the data is not indexing in GBIF portal. It looks fine in [our IPT](https://doi.org/10.15472/xyzi2q) and we tried to republish the dataset but is still not indexing.
This was before indexing was paused today.

We should like to ask for help looking at the source of this issue or solving the incorrect number of records. 

Thank yuu very much.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c6b7e273b86f6b378797e83adff2e29a:ae5c2bd7036d096e095bf440186cdc146b3fd2e795210a5b7be7a862618436d4df38fda1f384b5260e6c73f65bdbdf0ee57eb3554483e225b9b55e7d83148ce1642950ea994be30259d65aeef039ba76f462cdc2d1776947af7e3b7e4be25ad4) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c6b7e273b86f6b378797e83adff2e29a:ae5c2bd7036d096e095bf440186cdc146b3fd2e795210a5b7be7a862618436d4df38fda1f384b5260e6c73f65bdbdf0ee57eb3554483e225b9b55e7d83148ce1642950ea994be30259d65aeef039ba76f462cdc2d1776947af7e3b7e4be25ad4)
System: Chrome 104.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/1324ac5a-4bc8-4fe2-853f-d091bbf97107
Window size: width 1920 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-08T18:15:48.473Z',to:'2022-09-08T18:21:48.473Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-08T18:15:48.473Z',to:'2022-09-08T18:21:48.473Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
@EstebanMH-SiB The ingestions are currently paused: https://www.gbif.org/system-health, if the dataset isn't ingested by tomorrow, please open a new issue.
