### ISSUE TITLE
No match in GrSCiColl

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4241]
**No match in GrSCiColl**

Bell Museum has 800K records that looks like they could be matched to GrSciColl if the codes were updated.

https://www.gbif.org/occurrence/search?publishing_org=927f1e70-cf74-11d8-bf68-b8a03c50a862

https://registry.gbif.org/institution/3c35744f-5766-4364-83cb-7e78d366131e/collection

The provide collection code as institution code (if GrSciColl is to be trusted)

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/de4ba059f910578ee8cc76287ef03610:a0551bf59cbe9e6ff1451e34f19caddeb66a04f32d90fe2a35118e2ee74a29e3985022b9ac21378a5b139f94b5af2357bc127b366fa51ffcc2c015a18187a3c8be9fcf7b42059cf634b1c742ec8741fd0e24cbf7ac3ad3bb1c64559c6049fd5a7a9759aa902c75aeffa3215dd25f2f889bfbb438294a94786eed0b410b62a93a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/de4ba059f910578ee8cc76287ef03610:a0551bf59cbe9e6ff1451e34f19caddeb66a04f32d90fe2a35118e2ee74a29e3985022b9ac21378a5b139f94b5af2357bc127b366fa51ffcc2c015a18187a3c8be9fcf7b42059cf634b1c742ec8741fd0e24cbf7ac3ad3bb1c64559c6049fd5a7a9759aa902c75aeffa3215dd25f2f889bfbb438294a94786eed0b410b62a93a)
System: Chrome 105.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/2265601299
Window size: width 1728 - height 968
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-09T07:55:44.331Z',to:'2022-09-09T08:01:44.331Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-09T07:55:44.331Z',to:'2022-09-09T08:01:44.331Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO
datasetKey: a36438d0-bec7-4b7b-9bfa-2c31e7610c39
publishingOrgKey: 927f1e70-cf74-11d8-bf68-b8a03c50a862

Node handles: @albenson-usgs

**Comment by ManonGros** [comment]
I added the collection codes to the the collections in GRSciColl, merged two institution entries and added explicit mapping of the dataset to https://registry.gbif.org/institution/283b0179-5657-4959-9547-a64470481c77. So once the cache is refreshed and the datasets are reinterpreted, the occurrences should be properly linked.

**Comment by MortenHofft** [comment]
Wuhuu. And GrSciColl just grew by nearly a million specimens. nice
