### ISSUE TITLE
bug in GADM filter ¿wrong parents of level3?

### ISSUE THREAD

**Issue by abubelinha** [gbif/portal-feedback#4255]
When using GADM filter for a region in NW Spain, I found a group of occurrences which GBIF locates far outside that GADM, in SE Spain. This is the portal request:
https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&gadm_gid=ESP.12_1

There you can use the WKT filter to clearly see the big set of [1340791 occurrences GADM area in NW](https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON((-9.5971%2043.12882,-9.00523%2041.51935,-6.59622%2041.75817,-6.61699%2043.53378,-7.71765%2044.18795,-9.5971%2043.12882))&gadm_gid=ESP.12_1), and the small subset of [1856 SE occurrences wrongly adscribed to that GADM](https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON((-2.2887%2037.02913,-0.59303%2037.02913,-0.59303%2038.60786,-2.2887%2038.60786,-2.2887%2037.02913))&gadm_gid=ESP.12_1)).

This looks to me as a bug in GADM hierarchy, but I am just guessing after looking at one of the wrong occurrences latitude and longitude:
https://api.gbif.org/v1/occurrence/616635798
```json
  "decimalLatitude": 37.84,
  "decimalLongitude": -1.52,
  "coordinateUncertaintyInMeters": 10000.0,
  "gadm": {
    "level0": {
      "gid": "ESP",
      "name": "Spain"
    },
    "level1": {
      "gid": "ESP.12_1",
      "name": "Galicia"
    },
    "level2": {
      "gid": "ESP.12.4_1",
      "name": "Pontevedra"
    },
    "level3": {
      "gid": "ESP.12.4.4_1",
      "name": "n.a. (210)"
    }
  },

```
Pontevedra is in Galicia, and Galicia is entirely located in NW Spain (approximate bounding box: SE 41.8 -6.5, NW 43.8 -9.8).
I don't know what "_n.a. (210)_" is, but if it contains those 37.84 -1.52 coordinates, then it is in Spain, but NOT in Galicia

Perhaps that level3 does not correspond to the level2 parent, or something like that ¿?

Thanks!
@abubelinha

**Comment by MattBlissett** [comment]
Thanks, this was a bug in an internal cache and was fixed a few days after your report (see linked issue).
