### ISSUE TITLE
change title of case study 'eDNA barcoding'

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4257]
**change title of case study &#39;eDNA barcoding&#39;**

The title of the case study 'eDNA barcoding' should be 'eDNA metabarcoding' since the case study refers to complex, multispecies samples processed with a metabarcoding pipeline.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/dfe002384893338060b2a9b6c2e5cb29:2cd902f8498f0f143e856cd51dff3818ec85827a250f1d28065760f611beac3e8d9ce6c89676760bf0c7d5e00437950a431f18df0cdd57e5bc0d87c15a99b163ea127bf3add6d9b76889162d8538dead9c48da8c9bf9fe5cec84fe030cf8ddc9) - [Send email](https://www.gbif.org/api/feedback/user/mailto/dfe002384893338060b2a9b6c2e5cb29:2cd902f8498f0f143e856cd51dff3818ec85827a250f1d28065760f611beac3e8d9ce6c89676760bf0c7d5e00437950a431f18df0cdd57e5bc0d87c15a99b163ea127bf3add6d9b76889162d8538dead9c48da8c9bf9fe5cec84fe030cf8ddc9)
System: Firefox 104.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/new-data-model
Window size: width 2560 - height 1287
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-14T12:22:47.921Z',to:'2022-09-14T12:28:47.921Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-14T12:22:47.921Z',to:'2022-09-14T12:28:47.921Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Ok done.
