### ISSUE TITLE
Typo in year for latest entry

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4258]
**Typo in year for latest entry**

Suggest to change "26 August 2026" to 2022

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e22d57c3cdeb6ca996e7ea9a31b1b885:a8703c238e1ea9bf18c631de8eafa3aa7e483df7af4d4754283dc27444ee279bf90c6ba52aab329ab009eeea492df9083cca586eb100ff1fe17f081ad04651ce3ae19a6a9caf57e04ddd25fd5f6d7819bb3ad01393d7fd9807e81102434820016d62b87fcdbeca28e00815a0d3a3e7c1aac7e034736aaed02f516676b45b83bb) - [Send email](https://www.gbif.org/api/feedback/user/mailto/e22d57c3cdeb6ca996e7ea9a31b1b885:a8703c238e1ea9bf18c631de8eafa3aa7e483df7af4d4754283dc27444ee279bf90c6ba52aab329ab009eeea492df9083cca586eb100ff1fe17f081ad04651ce3ae19a6a9caf57e04ddd25fd5f6d7819bb3ad01393d7fd9807e81102434820016d62b87fcdbeca28e00815a0d3a3e7c1aac7e034736aaed02f516676b45b83bb)
System: Firefox 104.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/release-notes
Window size: width 1299 - height 679
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-14T13:37:24.528Z',to:'2022-09-14T13:43:24.528Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-14T13:37:24.528Z',to:'2022-09-14T13:43:24.528Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Excellent suggestion, thanks :)
