### ISSUE TITLE
Region name incomplete

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4259]
**Region name incomplete**

Please change "Europe" -> "Europe and Central Asia" in prantheses, keep link

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/72e7fb1f612604764f18b495f263bd1b:212a52346175d8a25ff1824d55c33d23f5775d5a0da2f598181eb57f757adb3060b31423490704ed916a59bde05c611622a2756b6f77905d129d4e25bfc4e42ea9e6a44313c17d228fb0fef3f9b6d154e1673f7dc7df0925eb507a2b51000f5b49e60bb2ebf7cf73f3ab0f8e33154eb325f127b25152849e188520ad7f8304e1) - [Send email](https://www.gbif.org/api/feedback/user/mailto/72e7fb1f612604764f18b495f263bd1b:212a52346175d8a25ff1824d55c33d23f5775d5a0da2f598181eb57f757adb3060b31423490704ed916a59bde05c611622a2756b6f77905d129d4e25bfc4e42ea9e6a44313c17d228fb0fef3f9b6d154e1673f7dc7df0925eb507a2b51000f5b49e60bb2ebf7cf73f3ab0f8e33154eb325f127b25152849e188520ad7f8304e1)
System: Chrome 105.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/contact-us/directory?group=nsg
Window size: width 1731 - height 845
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-14T13:46:18.400Z',to:'2022-09-14T13:52:18.400Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-14T13:46:18.400Z',to:'2022-09-14T13:52:18.400Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
This has been changed in the site translations. It will be available when the translations are merged and the site rebuilt.
