### ISSUE TITLE
dwca validator fails for wrong reasons

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4260]
**dwca validator fails for wrong reasons**

Trying to validate the iNat dwca here the validator fails and reports "meta.xml file was not found" - which is not true, it is in the archive at https://www.inaturalist.org/taxa/inaturalist-taxonomy.dwca.zip

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b9ff5418f04277942fe9b40386f12f10:3df9d5229cb261f3b5d428eb27326e2abd19b25ac3b1130a8feff4d6454fa2f6fbfe5b1c5f732350f4b40b946cc7f5112e613fcb714cb9e38b2a365e6f2a8b01c228e0e288c294e60098312a9992a57c5996413d296c5a383b541d4098a1283dcf0431ce1102ed7fef580b80e683687079fb920ba753313f54b3c51cfbead7f3) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b9ff5418f04277942fe9b40386f12f10:3df9d5229cb261f3b5d428eb27326e2abd19b25ac3b1130a8feff4d6454fa2f6fbfe5b1c5f732350f4b40b946cc7f5112e613fcb714cb9e38b2a365e6f2a8b01c228e0e288c294e60098312a9992a57c5996413d296c5a383b541d4098a1283dcf0431ce1102ed7fef580b80e683687079fb920ba753313f54b3c51cfbead7f3)
System: Safari 15.4.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/tools/data-validator/c3413298-7e63-4760-8c99-e45311b39169
Window size: width 1287 - height 830
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-15T09:44:09.311Z',to:'2022-09-15T09:50:09.311Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-15T09:44:09.311Z',to:'2022-09-15T09:50:09.311Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
@mdoering I renamed the EML-file (new name eml.xml instead of metadata.eml.xml) and the tool was able to find both .xml files and finish the [validation](https://www.gbif.org/tools/data-validator/ff18d319-d725-4c47-b98c-35dbd55f2872). There are some other issues for the archive still, but did this at least solve this issue?

**Comment by mdoering** [comment]
Thanks @CecSve. I was mostly curious to see how we currently handle multiple files per rowType, see https://github.com/gbif/dwca-io/issues/59 and how the various languages were interpreted. As we currently only read one file that remains to be seen.

I wonder why the original EML file was not found, that's also a bug in dwca-io?

**Comment by mdoering** [comment]
I have opened a new issue for the EML problem which turns out to be an issue for others too:
https://github.com/gbif/pipelines/issues/791

**Comment by muttcg** [comment]
Fixed
