### ISSUE TITLE
grscicoll mapping

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4263]
**grscicoll mapping**

From the API response we see:
```
"collections": [
  {
    "name": "Colección de Plantas Vasculares;MEXU;Instituto de Biología, Universidad Nacional Autónoma de México;IBUNAM",
    "identifier": "SNIB-KE002-KE0022006F_MEXU_PV_2020.08.06-plantas vasculares",
    "parentIdentifier": "NO APLICA",
    "specimenPreservationMethod": "DRIED_AND_PRESSED",
    "curatorialUnits": [
      {
        "typeVerbatim": "Ejemplar",
        "count": 0,
        "deviation": 0,
        "lower": 1,
        "upper": 71
      }
    ]
  }
],
```
All records have institution code `ibunam`  and collection code `mexu` - just as stated in the metadata.

the `Owner institution code: Instituto de Biología, Universidad Nacional Autónoma de México` - leading to a `Different owner institution` flag and no match. But that name is actually just the name of the institution. the spelled out version of `ibunam`.
This look like a disagreement on how that field should be used (owner institution). We could eihter be more generous in our matching or ask them to remove the text from that field.

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/f97dfd9acfd0839d25837db9e81b0379:518551fcdf082b06d4096eda4621a6406219349a8a441c9c31df92e4cb2bd4f0bd69eb21fd8158e3bef468be6afbfa4c39f1e00e4c218c5b2c0dfa1547d6422dc1c67c5da71acfefd1b5ae072965479b4c0cdc3699523bc7cf76f028cf9764f438d0e5162e9c3bc26d55b8a4e3b3b0b144dda1a948f01798899ee618b31edf59) - [Send email](https://www.gbif.org/api/feedback/user/mailto/f97dfd9acfd0839d25837db9e81b0379:518551fcdf082b06d4096eda4621a6406219349a8a441c9c31df92e4cb2bd4f0bd69eb21fd8158e3bef468be6afbfa4c39f1e00e4c218c5b2c0dfa1547d6422dc1c67c5da71acfefd1b5ae072965479b4c0cdc3699523bc7cf76f028cf9764f438d0e5162e9c3bc26d55b8a4e3b3b0b144dda1a948f01798899ee618b31edf59)
System: Chrome 105.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/8016518a-f762-11e1-a439-00145eb45e9a
Window size: width 1728 - height 968
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-16T10:23:09.291Z',to:'2022-09-16T10:29:09.291Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-16T10:23:09.291Z',to:'2022-09-16T10:29:09.291Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I added the `Instituto de Biología, Universidad Nacional Autónoma de México` as alternative code for the IBUNAM institution. I believe that it enable the record linking to GRSciColl: https://api.gbif.org/v1/grscicoll/lookup?institutionCode=IBUNAM&institutionId=20&ownerInstitutionCode=Instituto%20de%20Biolog%C3%ADa,%20Universidad%20Nacional%20Autónoma%20de%20México

Now we just need to wait until the cache is refreshed and reinterpret the dataset.
