### ISSUE TITLE
grscicoll mapping

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4266]
**grscicoll mapping**

Dataset title: `RB - Rio de Janeiro Botanical Garden Herbarium Collection`

All institutionCodes: `jbrj`
all collectionCodes: `rb`

## GrSciColl
institution (RB)
https://registry.gbif.org/institution/48b29504-e1ac-432c-a0d6-f09f46023207
collection (RB)
https://registry.gbif.org/collection/e89ac5d6-77af-4d2a-adef-f54d512af4fa

I suggest we change the [institution](https://registry.gbif.org/institution/48b29504-e1ac-432c-a0d6-f09f46023207) code to `JBRJ `

doing so would add 750K records to grscicoll

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/28d29cc04810e976aad73b98386c65ae:6ba3e0b8aeff08001a6e15203843480da5a07ce0e717a044d1201fefb4b5389b73400532d3d6bcb8494024f9943d1099cd00246293dd547d420278761ed642604c807397705d3324989bf4c740a53f5f8a7da0247008d75b74dbeb11cd40b85c03a225868fdbdbf17ee97dabecceeabf368a24fc2d6f1cd7d3c6da463c373a3a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/28d29cc04810e976aad73b98386c65ae:6ba3e0b8aeff08001a6e15203843480da5a07ce0e717a044d1201fefb4b5389b73400532d3d6bcb8494024f9943d1099cd00246293dd547d420278761ed642604c807397705d3324989bf4c740a53f5f8a7da0247008d75b74dbeb11cd40b85c03a225868fdbdbf17ee97dabecceeabf368a24fc2d6f1cd7d3c6da463c373a3a)
System: Chrome 105.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/4300f8d5-1ae5-49e5-a101-63894b005868
Window size: width 1658 - height 1556
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-16T11:14:56.293Z',to:'2022-09-16T11:20:56.293Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-16T11:14:56.293Z',to:'2022-09-16T11:20:56.293Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Added `JBRJ` as alternative institution code for BR. Will reinterpret the data after the cache is refreshed.
