### ISSUE TITLE
How often are herbarium data sets updated?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4279]
**How often are herbarium data sets updated?**

I shall be giving a talk in Pakistan at Hazara University in mid-October. So far as I can see, the data set has not been refreshed since Sept 3. It has been refreshed since then, the most recent refresh being Sept 11.  I thought one could look for a refresh within about 2-3 days. It appears that is wrong. Can you tell me a guestimate as to how long it takes?
Thank you.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/36ab7bee404552078a65612b7f14aa35:156d0e7e76b03db2364f914833a2e02868314f74ec69c436f8ba07d30480eb416dbba6832fddd46877e4ad737eb1f766995601d51294deb5e501c341c88f387b0cfb88c634853f3fcb2cdfb4ce948d76849a73eb90ff996e9bd2db0f69fe03d9759b7f6e478d294e99955f97c7f94c789cbb85ee9c775f4b443863b03d167e60b2a11cf8ddecd11672a113091417b454) - [Send email](https://www.gbif.org/api/feedback/user/mailto/36ab7bee404552078a65612b7f14aa35:156d0e7e76b03db2364f914833a2e02868314f74ec69c436f8ba07d30480eb416dbba6832fddd46877e4ad737eb1f766995601d51294deb5e501c341c88f387b0cfb88c634853f3fcb2cdfb4ce948d76849a73eb90ff996e9bd2db0f69fe03d9759b7f6e478d294e99955f97c7f94c789cbb85ee9c775f4b443863b03d167e60b2a11cf8ddecd11672a113091417b454)
System: Chrome 105.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/8f8b91a7-e367-46fb-bdf4-2f7da25c988f
Window size: width 1418 - height 696
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-17T21:41:28.194Z',to:'2022-09-17T21:47:28.194Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-17T21:41:28.194Z',to:'2022-09-17T21:47:28.194Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
GBIF crawls the dataset from the source every seven days and the last change was on September 18th 2022.
