### ISSUE TITLE
Missing datasets in search

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#428]
**Missing datasets in search**

The [luomus_ring dataset](https://www.gbif.org/dataset/292a71df-588b-48fa-9ab5-29ae868ba88c) is missing in the search results for data published by Finland.  It is the biggest dataset from Finland by a long way.

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c
User provided contact info: timrobertson100
System: Chrome 60.0.3112 / Mac OS X 10.11.5
Referer: https://www.gbif.org/dataset/search?offset=0&publishing_country=FI
Window size: width 1417 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-04T11:16:41.961Z',mode:absolute,to:'2017-09-04T11:22:41.961Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-04T11:16:41.961Z',mode:absolute,to:'2017-09-04T11:22:41.961Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
Strangely it shows up when adding [a freetext to the search](https://www.gbif.org/dataset/search?offset=0&q=luomus_ring&publishing_country=FI) 

Could be cache related

**Comment by timrobertson100** [comment]
Confirmed - does now show up
