### ISSUE TITLE
Update acknowledgements page

### ISSUE THREAD

**Issue by MattBlissett** [gbif/portal-feedback#4282]
We need to update the Acknowledgements page.

Sauce Labs can be removed from the top bullets, it's already at the bottom of the page.

I think OSM, Natural Earth and OpenMapTiles should be in a separate section of "open data" or similar.  Added to that section:

- GADM for administrative areas, https://gadm.org/license.html
- Marine Regions. They have preferred citations, we are using both the [Marine and land zones: the union of world country boundaries and EEZ's](https://www.marineregions.org/sources.php#unioneezcountry) and [IHO](https://www.marineregions.org/sources.php#iho) datasets.

I think it would also be nice to credit the open source software and data in the same way as we do the commercial software, i.e. with a logo etc. (Varnish and OpenMapTiles are companies providing open source software/data without asking for a free licence.)

@dnoesgaard / @kcopas .

**Comment by dnoesgaard** [comment]
It's really difficult to make something like this look nice with logos of different sizes and formats. I contemplated a table but I would have to hardcode style it. So, for now this is what I can offer:

https://www.gbif.org/article/7ajp2nD76o640qIeMmmiwI/_preview
