### ISSUE TITLE
Map has collapsed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4286]
**Map has collapsed**

The map has collapsed on this page, i assume it has to do with the recent rewrite of components using openlayers, but it might be caused by something else

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/0c0d00a43ce7ac955cb3612f62970cbe:0e266b0c8de76b9229936d30ff8c10fd631477d644e93932965d03af142ff5f21318a9db71952815b19c413f4de7172b91af016268de79cb8c874cb1d468fbcf20b36f7d1c7f01cc45d72fbf97da984dcaf34dfbbc004dde1f822450c464cdb339a1331a1a44ee365b97b7bf5911df86244ec8b4eb49e764fba135daa72f4c85) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0c0d00a43ce7ac955cb3612f62970cbe:0e266b0c8de76b9229936d30ff8c10fd631477d644e93932965d03af142ff5f21318a9db71952815b19c413f4de7172b91af016268de79cb8c874cb1d468fbcf20b36f7d1c7f01cc45d72fbf97da984dcaf34dfbbc004dde1f822450c464cdb339a1331a1a44ee365b97b7bf5911df86244ec8b4eb49e764fba135daa72f4c85)
System: Chrome 105.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/grscicoll/collection/dceb8d52-094c-4c2c-8960-75e0097c6861/metrics
Window size: width 1572 - height 1518
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-20T13:27:37.699Z',to:'2022-09-20T13:33:37.699Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-20T13:27:37.699Z',to:'2022-09-20T13:33:37.699Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
That map is still collapsed, perhaps it hasn't been deployed yet?
