### ISSUE TITLE
Empty publication date on dataset page confusing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#429]
**Empty publication date on dataset page confusing**

Datasets without an EML metadata document can't populate the published date. The result is an empty publication date on the dataset page that looks like a mistake. Instead of leaving it blank, I propose filling it in with "Unspecified".

-----
fbitem-dataset81119a40-f762-11e1-a439-00145eb45e9a
User provided contact info: kbraak
System: Firefox 55.0.0 / Mac OS X 10.10.0
Referer: https://www.gbif.org/dataset/81119a40-f762-11e1-a439-00145eb45e9a
Window size: width 1214 - height 1138
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-04T12:15:45.328Z',mode:absolute,to:'2017-09-04T12:21:45.328Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-04T12:15:45.328Z',mode:absolute,to:'2017-09-04T12:21:45.328Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
Screenshot showing empty publication date:
![screen shot 2017-09-04 at 14 13 18](https://user-images.githubusercontent.com/5981100/30026394-fb0f03e6-917c-11e7-92a4-17f7efd61f84.png)
