### ISSUE TITLE
Headline with scientificname missing on occurrence without taxon math

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#43]
**Headline with scientificname missing on occurrence without taxon math**

When no taxon match the occurrence headline should read either incertae sedis or the unmatched name (marked as unmatched somehow).

-----
fbitem-occurrence1423852657
Reported by: @mortenhofft
System: Chrome 55.0.2883 / Mac OS X 10.10.5
Referer: https://demo.gbif.org/occurrence/1423852657
Window size: width 1440 - height 776
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-22T09:59:15.214Z',mode:absolute,to:'2017-01-22T10:05:15.214Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-22T09:59:15.214Z',mode:absolute,to:'2017-01-22T10:05:15.214Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 84d26682-f762-11e1-a439-00145eb45e9a
publishingOrgKey: ccc2e3ec-98ba-4e74-878d-7dcf0f57baba

**Comment by MortenHofft** [comment]
Fixed with gbif/occurrence@bf744aa . incertae sedis will show instead
