### ISSUE TITLE
Crawl history not shown

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#430]
**Crawl history not shown**

Indeed, this particular dataset has never been successfully crawled (only 1 attempt that was aborted). In these cases, however, I think it's better to show this dataset has never been successfully crawled than to not show anything at all. Otherwise the dataset's publisher and GBIF aren't aware there has been a problem crawling this dataset.

-----
fbitem-dataset81119a40-f762-11e1-a439-00145eb45e9a
User provided contact info: kbraak
System: Firefox 55.0.0 / Mac OS X 10.10.0
Referer: https://www.gbif.org/dataset/81119a40-f762-11e1-a439-00145eb45e9a
Window size: width 1214 - height 1138
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-04T12:19:57.651Z',mode:absolute,to:'2017-09-04T12:25:57.651Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-04T12:19:57.651Z',mode:absolute,to:'2017-09-04T12:25:57.651Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
Screenshot showing lack of crawl history: 
![screen shot 2017-09-04 at 14 25 05](https://user-images.githubusercontent.com/5981100/30026375-e637fba8-917c-11e7-9978-bd2c7fb9d43e.png)

**Comment by kcopas** [comment]
Is this a feature rather than a bug for TAPIR installations?
cf. https://www.gbif.org/dataset/fdf5cc60-9fcc-11da-a90c-b8a03c50a862

**Comment by kbraak** [comment]
I doubt it. Many TAPIR endpoints are dead and not responding. While we continue to support TAPIR we should still show we are attempting to crawl them, and even better, show reasons why our attempts to crawl them fail.

**Comment by kcopas** [comment]
Sorry, wasn't suggesting that we shouldn't show attempts in any way. I only noticed a second example with no information and thought it might be systemic w.r.t. TAPIR installations.

However, I don't think that hypothesis holds:
https://www.gbif.org/dataset/a8d08280-1def-11de-be11-b8a03c50a862

**Comment by MortenHofft** [comment]
There is no crawl history to show - no failed attempts nor any success - is there? @kbraak where do you see that there is "1 attempt that was aborted" ? The website might be using a wrong endpoint? Anyway I don't see it in the API we are using. Maybe an API issue then?
http://api.gbif.org/v1/dataset/81119a40-f762-11e1-a439-00145eb45e9a/process

```
{
"offset": 0,
"limit": 20,
"endOfRecords": true,
"count": 0,
"results": []
}
```

**Comment by kbraak** [comment]
Strange, perhaps I was looking at the UAT registry console https://registry.gbif-uat.org/web/#/dataset/81119a40-f762-11e1-a439-00145eb45e9a/crawl

In any case, showing a "no crawling attempts" or "crawl in progress" would be greatly appreciated by publishers and help traffic to GBIF Helpdesk, thanks.

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/fa23e4450ca7895b2fb5570283b3fb1b88764728

**Comment by MortenHofft** [comment]
the crawl in progress information was already in there, but is now more explicit and validated against another endpoint. The never crawled information is now also explicitly stated.
