### ISSUE TITLE
Mistake in the date

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4307]
**Mistake in the date**

Apparently, the date is wrong. I guess it should be "Lithodendron dichotomum Goldfuss, 1826" instead of "Lithodendron dichotomum Goldfuss, 1926" ;)

Best regards

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4fa96aa755de3b2812631ef96b4d6784:462864b9245ff951014ba4266860f24c054f082f75e8507fd9a43a4e4613f4245db13403ad5a77fb95d6fe18d64eee3814d764c157e9bee385c9a67b9187211ea4ce8976583124885ee5e6de177a9d7d103378024a65ee69ab48f717c304391e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/4fa96aa755de3b2812631ef96b4d6784:462864b9245ff951014ba4266860f24c054f082f75e8507fd9a43a4e4613f4245db13403ad5a77fb95d6fe18d64eee3814d764c157e9bee385c9a67b9187211ea4ce8976583124885ee5e6de177a9d7d103378024a65ee69ab48f717c304391e)
System: Firefox 105.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/9364549
Window size: width 1173 - height 824
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-25T06:47:20.743Z',to:'2022-09-25T06:53:20.743Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-25T06:47:20.743Z',to:'2022-09-25T06:53:20.743Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by bart-v** [comment]
Fixed in WoRMS & GBIF
Can be closed
