### ISSUE TITLE
Deleting account

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4309]
**Deleting account**

I would like to delete my account. Could this process be started please?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/61f42d02e2300b3d4fbcf756f1d0b876:d9ef355aae53947818bab311fc153a6fa342fba9e8bfcdf61e0d547dac34f0e324d540636d2cedf7db25df5474ccd077684ee78ef8fe486d2a1904b4bc0737116ac0b50296a70bed3cd284d705352b8284fcdd5ec88696f3b6a03fd19edaa56a4cb0d259399815069a657e112a4443799601767232037a7631a46071f9593a15) - [Send email](https://www.gbif.org/api/feedback/user/mailto/61f42d02e2300b3d4fbcf756f1d0b876:d9ef355aae53947818bab311fc153a6fa342fba9e8bfcdf61e0d547dac34f0e324d540636d2cedf7db25df5474ccd077684ee78ef8fe486d2a1904b4bc0737116ac0b50296a70bed3cd284d705352b8284fcdd5ec88696f3b6a03fd19edaa56a4cb0d259399815069a657e112a4443799601767232037a7631a46071f9593a15)
System: Chrome 105.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=delete%20account
Window size: width 3072 - height 1595
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-26T17:33:49.262Z',to:'2022-09-26T17:39:49.262Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-26T17:33:49.262Z',to:'2022-09-26T17:39:49.262Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Deleted using the registry console, notified user by email.

**Comment by ManonGros** [comment]
Thanks @MattBlissett I forgot to follow up
