### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4310]
**数据问题**

下载Elephas maximus 数据后，斯里兰卡部分分布在海洋里

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7e18b76fce2cfd81d4339c182af310c2:5448ba4bdd30fcb14eec699cc202e375a7d032594baea6421399b26b9c7c8a1137b0fae69da3062bafbc5233548dbc56b1ac8656187de4bbf2b0dbaee862c540287c244fff21f5aa33fff8106e5394061f4736d5fceb150d256ae9c880d196ba) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7e18b76fce2cfd81d4339c182af310c2:5448ba4bdd30fcb14eec699cc202e375a7d032594baea6421399b26b9c7c8a1137b0fae69da3062bafbc5233548dbc56b1ac8656187de4bbf2b0dbaee862c540287c244fff21f5aa33fff8106e5394061f4736d5fceb150d256ae9c880d196ba)
System: Chrome 105.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/zh/occurrence/search?occurrence_status=present
Window size: width 1535 - height 746
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-27T08:11:54.073Z',to:'2022-09-27T08:17:54.073Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-27T08:11:54.073Z',to:'2022-09-27T08:17:54.073Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
translation - though my chinese is a bit rusty ;)

> data problem
After downloading Elephas maximus data, Sri Lanka is partly distributed in the ocean

**Comment by MortenHofft** [comment]
Thank you for taking the time to give feedback

Here is an example record that you reference https://www.gbif.org/occurrence/1291116143

In this case the coordinate uncertainty explains it. I suspect that is the explanation for most if not all of the records

<img width="604" alt="Screenshot 2022-09-27 at 14 06 08" src="https://user-images.githubusercontent.com/6759267/192521122-cd99af5e-f554-4779-afc5-cc1948c9f5b6.png">
<img width="658" alt="Screenshot 2022-09-27 at 14 06 24" src="https://user-images.githubusercontent.com/6759267/192521287-f001b1f3-2ea2-4aa9-91b3-3610a7ce1874.png">

So it looks to me like the data is as it should be. You should consider the coordinate uncertainty

Best

**Comment by MortenHofft** [comment]
> user informed per email
