### ISSUE TITLE
IH => GrSciColl contact mapping

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#4315]
@marcos-lg 

It looks like we are mapping contact information oddly from IH. At least in this example.

Notice how we put country into state for example. It looks like everything is off by 1

Relating to https://registry.gbif.org/institution/e0cd510a-a05e-4a39-b00b-6ebb4cb04aeb
http://sweetgum.nybg.org/science/ih/ihh-edit/?irn=252693

**Comment by marcos-lg** [comment]
Same issue as https://github.com/gbif/registry/issues/444.

The data we fetch from IH is swapped.
