### ISSUE TITLE
Doubtful data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4328]
**Doubtful data**

I am not sure, but as I understand metadata description, this data derived from results of species distribution modelling, not from real field data. Are simulation results a possible data source for GBIF?

-----

Github user: @NatalyaDryomys
User: [See in registry](https://www.gbif.org/api/feedback/user/eebe421f1636ce0c380268129801c645:a8361b8e7b2334b93fa4299326982e1b4a0d183acfacf0d24b9f4a6f0dd599c4dc72faa8f29eb3d54566841c84579655a517e41d9b3ebb84f2de57bc8b16f5b5dda20facb828fb648a00f9e4163a2a11ba00b9250384dd64aeb925a7781fefa7edd8ce15fccc9b5b8dc6d4598e83ea2d7ad0254817bce4ef3c1c703139dd0911b0839b7a54aaa082ae2b664b7b34d6bd) - [Send email](https://www.gbif.org/api/feedback/user/mailto/eebe421f1636ce0c380268129801c645:a8361b8e7b2334b93fa4299326982e1b4a0d183acfacf0d24b9f4a6f0dd599c4dc72faa8f29eb3d54566841c84579655a517e41d9b3ebb84f2de57bc8b16f5b5dda20facb828fb648a00f9e4163a2a11ba00b9250384dd64aeb925a7781fefa7edd8ce15fccc9b5b8dc6d4598e83ea2d7ad0254817bce4ef3c1c703139dd0911b0839b7a54aaa082ae2b664b7b34d6bd)
System: Chrome 104.0.5112 / Linux 0.0.0
Referer: https://www.gbif.org/dataset/53efcac4-cd08-4b4d-93e6-cb06c1d37de1
Window size: width 1849 - height 952
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-05T07:23:24.188Z',to:'2022-10-05T07:29:24.188Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-05T07:23:24.188Z',to:'2022-10-05T07:29:24.188Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Thank you @NatalyaDryomys for bringing this dataset to our attention. Predictions are indeed outside of the GBIF scope. We will be following up with the publisher.
