### ISSUE TITLE
Broken link to literature

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#433]
**Broken link to literature "Best practice guidelines in the development and maintenance of regional marine species checklists"**

Appears to duplicate document resource (see screenshot)

![screen shot 2017-09-05 at 16 22 59](https://user-images.githubusercontent.com/5981100/30065936-bda02c9e-9256-11e7-8a35-7f7bacf969cc.png)

-----
fbitem-c10dc129aa10326466e097eb5bc20b64d9619fe4
User provided contact info: kbraak
System: Firefox 55.0.0 / Mac OS X 10.10.0
Referer: https://www.gbif.org/orc?doc_id=4712
Window size: width 1187 - height 1098
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-05T14:19:36.225Z',mode:absolute,to:'2017-09-05T14:25:36.225Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-05T14:19:36.225Z',mode:absolute,to:'2017-09-05T14:25:36.225Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
One is a literature item the other a document. I agree it looks confusing. Both links are working now.
I'll label this a content issue for @dnoesgaard to decide if both should appear.

**Comment by dnoesgaard** [comment]
I would remove the literature item, as we wouldn't add such a document to Mendeley today.

Any objections?

@kbraak ?

**Comment by kbraak** [comment]
not from me, nope

**Comment by dnoesgaard** [comment]
kthxbi

removed from Mendeley
