### ISSUE TITLE
Typo in citation identifier causes broken link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#434]
**Typo in citation identifier causes broken link**

http://www.gbif.org/documents/80784

Should be 

http://www.gbif.org/document/80784 (without the s)

Please check if this is an isolated incidence - thanks?

-----
fbitem-d7185e0826be2e0d966da241d4698bd4b2c17664
User provided contact info: kbraak
System: Firefox 55.0.0 / Mac OS X 10.10.0
Referer: https://www.gbif.org/document/80784/best-practice-guide-for-compiling-maintaining-disseminating-national-species-checklists
Window size: width 1904 - height 1160
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-05T14:24:44.491Z',mode:absolute,to:'2017-09-05T14:30:44.491Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-05T14:24:44.491Z',mode:absolute,to:'2017-09-05T14:30:44.491Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
Just a typo made in content editor
