### ISSUE TITLE
Citation identifier differs from that in document

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#435]
**Citation identifier differs from that in document**

The document specifies http://www.gbif.org/orc/?doc_id=4752 as the persistent identifier used in the citation. At the very least, this identifier should redirect to the new citation identifier instead

-----
fbitem-d7185e0826be2e0d966da241d4698bd4b2c17664
User provided contact info: kbraak
System: Firefox 55.0.0 / Mac OS X 10.10.0
Referer: https://www.gbif.org/document/80784/best-practice-guide-for-compiling-maintaining-disseminating-national-species-checklists
Window size: width 1904 - height 1160
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-05T14:29:13.345Z',mode:absolute,to:'2017-09-05T14:35:13.345Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-05T14:29:13.345Z',mode:absolute,to:'2017-09-05T14:35:13.345Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you and indeed. http://www.gbif.org/orc/?doc_id=4752 now redirects to https://www.gbif.org/document/80784/best-practice-guide-for-compiling-maintaining-disseminating-national-species-checklists
