### ISSUE TITLE
Validator: Meta.xml not found

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4353]
**Validator: Meta.xml not found**

The validator does not find the meta.xml file. Please see http://www.gbif.org/tools/data-validator/ffee511b-a5e6-480a-a8ab-bb112ecd8908
I already tried to rename the meta.xml to eml.xml, same error. 
Please see http://www.gbif.org/tools/data-validator/e6453591-8859-49e8-9f24-3df62373df39 f

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4a4e72ebffca6bcc05dbd3845a48460d:f6362e5a75ca5d86a1b63daa17e23f44fe9a8e5b921f03d9ec17981716ad4ec548a3e9c53d5c675d87864f80235f9deef97a153898e7dbbe22ff30eadb6f0f2e3c9e05eaa3cef474b12cc15abc166c8eb92a9ea74610f7e9360337318baab055e66740ece940b74624a6015ece87518af18850a0f4a88b11c3339167f49d7e0a1c3890a5d687a406df2ac597bb54ca1b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/4a4e72ebffca6bcc05dbd3845a48460d:f6362e5a75ca5d86a1b63daa17e23f44fe9a8e5b921f03d9ec17981716ad4ec548a3e9c53d5c675d87864f80235f9deef97a153898e7dbbe22ff30eadb6f0f2e3c9e05eaa3cef474b12cc15abc166c8eb92a9ea74610f7e9360337318baab055e66740ece940b74624a6015ece87518af18850a0f4a88b11c3339167f49d7e0a1c3890a5d687a406df2ac597bb54ca1b)
System: Chrome 106.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator
Window size: width 767 - height 712
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-18T01:48:47.228Z',to:'2022-10-18T01:54:47.228Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-18T01:48:47.228Z',to:'2022-10-18T01:54:47.228Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by muttcg** [comment]
Fixed
