### ISSUE TITLE
how to cite data downloaded via rgbif package

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4356]
**how to cite data downloaded via rgbif package**

If I download data via the webpage, I get a DOI to cite. If I download data via the R Package rgbif with `occ_search`, how should I cite the resulting data?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0085d89585de9d11e9d786a35f9eb4a1:a77538b8789835ea6e6ba74e230f8b65a99074ca4e1358f971f6f247eb7a26804c737004cb89ef96b396cedd7b391bf3c41194f867ac82f74c5ab64f9a860814e8c1a32ba5f528cb488ec5952b3c0f763f81f8f224b4d327c5e28eead241ba4cb9aa8c892fcea433d96436d00fa2b03c720f6b7887662daec7c895388f8ece62) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0085d89585de9d11e9d786a35f9eb4a1:a77538b8789835ea6e6ba74e230f8b65a99074ca4e1358f971f6f247eb7a26804c737004cb89ef96b396cedd7b391bf3c41194f867ac82f74c5ab64f9a860814e8c1a32ba5f528cb488ec5952b3c0f763f81f8f224b4d327c5e28eead241ba4cb9aa8c892fcea433d96436d00fa2b03c720f6b7887662daec7c895388f8ece62)
System: Firefox 105.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 955
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-18T19:20:34.336Z',to:'2022-10-18T19:26:34.336Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-18T19:20:34.336Z',to:'2022-10-18T19:26:34.336Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
(Responded via email) 

Please see this article Citing GBIF Mediated Data. 
https://docs.ropensci.org/rgbif/articles/gbif_citations.html

You can also leave any further questions regarding rgbif here: 
https://github.com/ropensci/rgbif/issues
