### ISSUE TITLE
please update derived dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4357]
**please update derived dataset**

Please update the relatedDatasets of this dd.

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/e38ce2d2fa0c33d3aaef6d837c09ee55:2ef05bb49a60814f786fa72d4a8465718acc900532519b85284a3face15bac37e61e152d4af1c738fe24a8ea5929f44a99645c57f7f9c78dfc6996fff1ae38373d263f05a331170f075458c6eff342adb046d68acb8b991696cf947851710e850b9ef69045cc0e87d510cbb9ee682dde7ccc3f7d5d2d0f2e8aadbbf1bb04a75ce944d99b2ca30da78ae699f33b3498f3) - [Send email](https://www.gbif.org/api/feedback/user/mailto/e38ce2d2fa0c33d3aaef6d837c09ee55:2ef05bb49a60814f786fa72d4a8465718acc900532519b85284a3face15bac37e61e152d4af1c738fe24a8ea5929f44a99645c57f7f9c78dfc6996fff1ae38373d263f05a331170f075458c6eff342adb046d68acb8b991696cf947851710e850b9ef69045cc0e87d510cbb9ee682dde7ccc3f7d5d2d0f2e8aadbbf1bb04a75ce944d99b2ca30da78ae699f33b3498f3)
System: Chrome 106.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/derivedDataset/10.15468/dd.2u7f3z
Window size: width 1664 - height 1039
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-19T11:07:53.326Z',to:'2022-10-19T11:13:53.326Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-19T11:07:53.326Z',to:'2022-10-19T11:13:53.326Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
details in file:
[hyperArid_dd.csv](https://github.com/gbif/portal-feedback/files/9819885/hyperArid_dd.csv)

**Comment by MattBlissett** [comment]
Sorry, missed this while I was travelling. It's done now.
