### ISSUE TITLE
Species and Synonym are identical

### ISSUE THREAD

**Issue by Andreas-Bio** [gbif/portal-feedback#4358]
![image](https://user-images.githubusercontent.com/19622117/196769030-9a15fb49-5ce5-41ac-8e14-c2da3f951a01.png)

The synonym with the typo is in the backbone taxonomy but not the accepted name? Is it possible to add it?
https://www.gbif.org/species/1340610

Thanks!

**Comment by jhnwllr** [comment]
This is weird it could be GBIF's fault. 

**Euglossa stilbonota Dressler, 1982-18**
Doesn't appear in the source. 
https://www.gbif.org/species/167766588/verbatim

**Comment by Andreas-Bio** [comment]
Thanknyou, all seems to be good now. Both in backbone.
It appears in the source on page 8.
