### ISSUE TITLE
Add library to tools catalogue

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#436]
**Add library to tools catalogue**

Hi,

I think it would be great if python-dwca-reader (http://python-dwca-reader.readthedocs.io/en/latest/) was listed in the Tools catalogue.

What do you think?

Thanks

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb
User provided contact info: niconoe
System: Chrome 60.0.3112 / Mac OS X 10.12.5
Referer: https://www.gbif.org/resource/search?contentType=tool
Window size: width 1436 - height 803
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-06T08:22:42.059Z',mode:absolute,to:'2017-09-06T08:28:42.059Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-06T08:22:42.059Z',mode:absolute,to:'2017-09-06T08:28:42.059Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
@niconoe sure, I've added it now:

https://www.gbif.org/resource/search?q=python-dwca&contentType=tool
