### ISSUE TITLE
Como registrar especies con evidencia fisica: foto, video o sonido

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4362]
**Como registrar especies con evidencia fisica: foto, video o sonido**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1d77ea6520a6289d5ed50ca600da28ae:110df4e74ddcd5d1755788046b5069428547969094bc7142b13347dfc51279249bde9d38a1bf5d53229fa4ebb7c3ec919b04f456e60fe73cdd2def542c79616088550ed34857d3554b8ab29a251b2367c4a76bd8f10c4958acee389d0e0b6d827049310504559aa00036ec7064d09eb2fa076d1924ae7a2e5549d3aeb792a730506be25859d29f8bb7d4ed61c5e9d0c3) - [Send email](https://www.gbif.org/api/feedback/user/mailto/1d77ea6520a6289d5ed50ca600da28ae:110df4e74ddcd5d1755788046b5069428547969094bc7142b13347dfc51279249bde9d38a1bf5d53229fa4ebb7c3ec919b04f456e60fe73cdd2def542c79616088550ed34857d3554b8ab29a251b2367c4a76bd8f10c4958acee389d0e0b6d827049310504559aa00036ec7064d09eb2fa076d1924ae7a2e5549d3aeb792a730506be25859d29f8bb7d4ed61c5e9d0c3)
System: Chrome 106.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/system-health
Window size: width 1920 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-24T17:20:51.913Z',to:'2022-10-24T17:26:51.913Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-24T17:20:51.913Z',to:'2022-10-24T17:26:51.913Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Google translate
> How to register species with physical evidence: photo, video or sound

**Comment by ManonGros** [comment]
The process of sharing data on GBIF depends on whether you are affiliated with an institution or not.
 
If you are affiliated with an institution or organization, the first step to share data on GBIF is to make sure it is registered as publisher. The registration can be done via the following form: https://www.gbif.org/es/become-a-publisher
The next step is to choose a publishing tool. You can find more information on the type of tools available here: https://data-blog.gbif.org/post/installations-and-hosting-solutions-explained/
If your organization cannot host a publishing tool, please let us know and we will help you find alternatives.
Once everything is set up, I suggest to consult this blog post on how to share data associated images, videos and sounds on GBIF: https://data-blog.gbif.org/post/gbif-multimedia/
 
If you aren’t part of any organization, the best would be to share your data via a citizen science initiative like https://www.inaturalist.org/. iNaturalist allows you to share photo, video and sounds and export all the research-grade observations to GBIF. To learn more, you can check this page: https://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7

> Replied by email
