### ISSUE TITLE
dates changed due to time zone change on event level

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4364]
**dates changed due to time zone change on event level**

the overview of project is correct, but when you click on individual project page the end dates are wrong by 1 day i.e. 
https://www.gbif.org/project/CESP2021-007/extending-knowledge-on-biodiversity-data-quality-and-publication-in-the-spanish-speaking-community should end on the 30th

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9ff8dfd19e75a0e806b0d71652837598:176699809cd476854d218c41e06d69b55d0b403b4192390d2be2fa9632b7e27ed3abe47a13736f37daef7342b3e62eb62946b7dad28bb3be8a3af906eaf4455ac0fb4e67f71c59e8cd5ccafe57aa138db465dbc5fe5ecc80b571f7923b71a610) - [Send email](https://www.gbif.org/api/feedback/user/mailto/9ff8dfd19e75a0e806b0d71652837598:176699809cd476854d218c41e06d69b55d0b403b4192390d2be2fa9632b7e27ed3abe47a13736f37daef7342b3e62eb62946b7dad28bb3be8a3af906eaf4455ac0fb4e67f71c59e8cd5ccafe57aa138db465dbc5fe5ecc80b571f7923b71a610)
System: Chrome 106.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/programme/82243/bid-biodiversity-information-for-development
Window size: width 3200 - height 1630
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-26T07:44:13.665Z',to:'2022-10-26T07:50:13.665Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-26T07:44:13.665Z',to:'2022-10-26T07:50:13.665Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
In Contentful, the date interval is `2022-08-01T00:00+02:00`  - `2022-12-30T00:00+02:00` 
Note that the endDate is still using UTC offset +2 (daylight saving time).
So the portal is actually showing the correct date, as the event is set to end at 23 PM 29th Dec Copenhagen Time
