### ISSUE TITLE
TW datasets with Zero occurrences indexed

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#4369]
- [x] https://www.gbif.org/dataset/18680b2b-84db-4d45-8acd-0b0e9467fb33 by Taiwan Biodiversity Information Facility (TaiBIF)
- [x] https://www.gbif.org/dataset/12f0a851-62f6-464d-8da9-7c92e1ed4ec7 by Taiwan Forestry Bureau
- [x] https://www.gbif.org/dataset/35fd702c-c615-4fb2-a7ed-5ab0e1f0946c by Taiwan Forestry Bureau
- [x] https://www.gbif.org/dataset/b5e26f14-c003-4c43-8e80-4287bbfb0cf1 by Taiwan Forestry Bureau
- [x] https://www.gbif.org/dataset/effadc23-e856-45fa-b8aa-ada31950efcd by Taiwan Forestry Bureau
- [x] https://www.gbif.org/dataset/f6460062-1923-4a73-93af-c3d672ac7175 by Taiwan Forestry Bureau

@melissa0520 Those datasets don't seem to have any occurrences. Would it be possible to investigate what could be happening? Possibly reach out to the publisher?

**Comment by daphnehoh** [comment]
Hi @ManonGros 

For the first dataset published by TaiBIF, we checked the dataset csv download via our TaiBIF IPT and found inconsistent and blank cells in the basisOfRecord field. We are not sure if this is the reason causing the 0 occurrences on GBIF.org but we managed to solve the issue after we edited the column. 

This is the current dataset:
https://www.gbif.org/dataset/18680b2b-84db-4d45-8acd-0b0e9467fb33

FYI, upon checking the basisOfRecord field we found that checklist was included in the dataset hence we pulled out this data and create another checklist core: https://www.gbif.org/dataset/26c7f6c0-1c96-4726-8bd8-71824699a914

My colleague is now investigating the other datasets you mentioned above.

**Comment by ManonGros** [comment]
Thanks @daphnehoh this is really great!
I can see that [the new checklist](https://www.gbif.org/dataset/26c7f6c0-1c96-4726-8bd8-71824699a914) doesn't have any records on GBIF. I suspect that this is because it is missing a [taxonID](https://dwc.tdwg.org/terms/#dwc:taxonID) column. This field should contain identifiers for each row/taxa in the checklist (they must be unique within the dataset).
Could you try adding taxonIDs and clicking on publish?

**Comment by daphnehoh** [comment]
Thanks @ManonGros for pointing it out! Yes I accidentally missed this column and it is now solved.

**Comment by Jeffersonktw** [comment]
Hi @ManonGros 

The problem was solved in all remaining datasets after mapping the occurrenceID.

**Comment by ManonGros** [comment]
Thank you @melissa0520 @daphnehoh and @Jeffersonktw!  This is really great!
I am closing the issue.
