### ISSUE TITLE
Member statistics?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#437]
**Member statistics?**

So where in the new portal can I see statistics of how many records each GBIF Member has published?

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: hannu.saarenmaa@helsinki.fi
System: Firefox 55.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/search?q=
Window size: width 1280 - height 887
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-07T10:24:37.292Z',mode:absolute,to:'2017-09-07T10:30:37.292Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-07T10:24:37.292Z',mode:absolute,to:'2017-09-07T10:30:37.292Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
You will find that here: https://www.gbif.org/the-gbif-network
Scroll down below the map.
Best regards,
Thomas
