### ISSUE TITLE
Accepted zip format for DwC Archive validator?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4380]
**Accepted zip format for DwC Archive validator?**

Dear team,

I'm trying to use the DarwinCore Archive validator. Unfortunately, it fails at the second stage (Failed to verify archive format). I'm wondering which type of zip files are accepted - any special compression method required?

The ID of the failed trial is http://www.gbif.org/tools/data-validator/96a9c24a-21e9-4741-b599-d24039e519a9.

Any help would be appreciated!
Jörg

-----

Github user: @jholetschek
User: [See in registry](https://www.gbif.org/api/feedback/user/489be185a2a70ff090ba4cf41ff3bfdd:c6f50bc040a2d3b1c67826046116ad82b2dfc858e594739e98b841a4daedc604fca2380105eb6bd33d55fbe51d9e283cafdd58b8d20e0811ffbb1eb08a18783ecc8d3852b419f8fdc46a1df6e10b569eede14b7a7918bea42fa7b183167a0d8ce4a069aeee077be2e4be90dd0d1c2339d5a6c6af43c6bdd36594bffb4fb5393e2ad48d0157d4faa9a3d9b90ded72db1f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/489be185a2a70ff090ba4cf41ff3bfdd:c6f50bc040a2d3b1c67826046116ad82b2dfc858e594739e98b841a4daedc604fca2380105eb6bd33d55fbe51d9e283cafdd58b8d20e0811ffbb1eb08a18783ecc8d3852b419f8fdc46a1df6e10b569eede14b7a7918bea42fa7b183167a0d8ce4a069aeee077be2e4be90dd0d1c2339d5a6c6af43c6bdd36594bffb4fb5393e2ad48d0157d4faa9a3d9b90ded72db1f)
System: Firefox 105.0.0 / Windows 7.0.0
Referer: https://www.gbif.org/tools/data-validator/96a9c24a-21e9-4741-b599-d24039e519a9
Window size: width 1920 - height 967
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-27T16:33:11.770Z',to:'2022-10-27T16:39:11.770Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-27T16:33:11.770Z',to:'2022-10-27T16:39:11.770Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by muttcg** [comment]
Hi @jholetschek
Unfortunately validator doesn't give correct issue message in your case, so it is not a format issue, zip files works will, I checked you archive manually and found issue with the structure of content txt files, some files have more content fields that headers fields

I also created an issue for your problem https://github.com/gbif/pipelines/issues/813

**Comment by jholetschek** [comment]
Thanks Nikolay!
I've already found the issues in the text files and I'm working on that. Indeed a different message would be helpful!

Cheers, Jörg
