### ISSUE TITLE
name not found by species checking tool, but is present in data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4381]
**name not found by species checking tool, but is present in data**

The species matching tool is great, but I have run into a problem with the following name [Ranunculus ficaria] not being matched even though it is present in the data:
https://www.gbif.org/species/8397184

I suspect the name is not indexed to the backbone

Cheers, Tom Myers

NB the name is a synonym, but that is usually not a problem.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9513fa9be39a7cb96620991807e7ff04:f66330acf135e62f598742cc996e3500e495b7ee7ff816daa1cd328c08d46113f03182e77a40416ec2eaae86ca88eedab62149bb124e389d41226aead1ad0c6fa9b49d73abecca3a919151b64f2ce5ec0cf66370b79556f224a1a974d7b2559aaee6da6dd446abc683a416f4ed7975033e611225fe9297f7e80bb8387afce6f5d0f701005139a1035f1f51fb93df5d1a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/9513fa9be39a7cb96620991807e7ff04:f66330acf135e62f598742cc996e3500e495b7ee7ff816daa1cd328c08d46113f03182e77a40416ec2eaae86ca88eedab62149bb124e389d41226aead1ad0c6fa9b49d73abecca3a919151b64f2ce5ec0cf66370b79556f224a1a974d7b2559aaee6da6dd446abc683a416f4ed7975033e611225fe9297f7e80bb8387afce6f5d0f701005139a1035f1f51fb93df5d1a)
System: Chrome 107.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/8397184
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-27T20:43:04.390Z',to:'2022-10-27T20:49:04.390Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-27T20:43:04.390Z',to:'2022-10-27T20:49:04.390Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
As far as I can see, the GBIF backbone taxonomy contains three different taxa that could match to the name Ranunculus ficaria:
•	Ranunculus ficaria L.: https://www.gbif.org/species/3033351
•	Ranunculus ficaria Walter: https://www.gbif.org/species/8397184
•	Ranunculus riparius Edgew.: https://www.gbif.org/species/3926527
In those case, if only the canonical name is provided (without any authorship) our system is unable to identify which of these taxa the name refers to.
This is why Ranunculus ficaria is matched to the genus.

You can test name matching with our [species API](https://www.gbif.org/developer/species) in verbose mode and it will give you the list of possible matches. See: https://api.gbif.org/v1/species/match?verbose=true&name=Ranunculus%20ficaria. More information about the species API is available [here](https://data-blog.gbif.org/post/gbif-species-api/).

> Replied by email
