### ISSUE TITLE
download higher resolution images?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4382]
**download higher resolution images?**

Is it possible to download higher resolution specimen images through GBIF to help facilitate specimen identification? Thanks!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d250492cd2a9322f9e13e937e6e7bbd6:9384f14f4714fdbfec96b286e8d937eb7aa65b7668f2de15e730230d82f36431dc41e163a38084dde71d9217ea84040086254733417033092d2cdad0dada5122af17c9fffe5d47ff776b47be30e6d3af65c0fe30de24a4e445f6b9db0b3141edebd54019b6fbda9f0f7a4f0aabc15ad601d057babdfab623745bccb4e86754da968c0c1b8355bdecf19f575bb651c519) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d250492cd2a9322f9e13e937e6e7bbd6:9384f14f4714fdbfec96b286e8d937eb7aa65b7668f2de15e730230d82f36431dc41e163a38084dde71d9217ea84040086254733417033092d2cdad0dada5122af17c9fffe5d47ff776b47be30e6d3af65c0fe30de24a4e445f6b9db0b3141edebd54019b6fbda9f0f7a4f0aabc15ad601d057babdfab623745bccb4e86754da968c0c1b8355bdecf19f575bb651c519)
System: Chrome 103.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2251583178
Window size: width 1098 - height 450
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-29T14:44:43.040Z',to:'2022-10-29T14:50:43.040Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-29T14:44:43.040Z',to:'2022-10-29T14:50:43.040Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 040c5662-da76-4782-a48e-cdea1892d14c
publishingOrgKey: b3bf3a83-1f68-4541-a03f-330d30d567f5

**Comment by ManonGros** [comment]
Data providers share images on GBIF by providing us URLs to images which we then display. We don’t host any images and we don’t have access to higher resolution than what is on our website.
I would advise to check the data at the source. In this case (https://www.gbif.org/occurrence/2251583178), you can check the reference provided: http://bins.boldsystems.org/index.php/Public_RecordView?processid=VASCB336-15. There are references to publications which might contain better images as well as contacts with whom you can get in touch.

> Replied by email
