### ISSUE TITLE
How do I download a species list from the species search page?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4383]
**How do I download a species list from the species search page?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7de5cfcbd683e25dcc7469efdab5bb34:3e02405450a271150fbfbe1df93cb1f97310f75cff0e68956dfc3a4d9125bfbda1d3e82116f9029ba297de553a89968534411682017c691390d04042ba23bb4f1f4d9f6283a71d0289f7a405e0460aec8a2dfc40601455683701d63358769043) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7de5cfcbd683e25dcc7469efdab5bb34:3e02405450a271150fbfbe1df93cb1f97310f75cff0e68956dfc3a4d9125bfbda1d3e82116f9029ba297de553a89968534411682017c691390d04042ba23bb4f1f4d9f6283a71d0289f7a405e0460aec8a2dfc40601455683701d63358769043)
System: Chrome 106.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/search?rank=GENUS&dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&highertaxon_key=5&highertaxon_key=6&advanced=1
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-31T20:27:27.013Z',to:'2022-10-31T20:33:27.013Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-31T20:27:27.013Z',to:'2022-10-31T20:33:27.013Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
You cannot download the result of a species search in the species search web interface.
However, you can generate downloads in ChecklistBank which also contains the GBIF backbone taxonomy. There, you can download names for a given root (higher taxa) and with a specified rank, for example: https://www.checklistbank.org/dataset/53147/download?taxonID=5 (don’t forget to specify the rank and choose a format). You might have to generate one download for fungi and one for plants. You can use your GBIF account to download data from ChecklistBank.

Alternatively, you can also use our [species API](https://www.gbif.org/developer/species) to programmatically access the information. See more information on the Species API [here](https://data-blog.gbif.org/post/gbif-species-api/) and a beginner’s guide to the API [here](https://data-blog.gbif.org/post/gbif-api-beginners-guide/).

> Replied by email
