### ISSUE TITLE
format downloaded table

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4387]
**format downloaded table**

Hi, I've downloaded an occurrence database from a specific area using the "simple" download option, opened excel, and see that the headers are all in a single column.  I swear I figured out a few years ago how to make that data presentable in excel but can't for the life of me figure it out this time.  
Thanks

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/942ee03a454cb0f28f5c9d8648c06a4d:b745bdc805213c1632867ec6465f223fae94b4d0d32b27183ca8e368e7c4cb1990abea89c59866871ddc0761cb4219f538ed07a1bd75c7f59c55963c0555d8e7baf9062eda8d8a84abfe9acca509c7b0f3963de7f4b6be34e1a3b404b7a8473d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/942ee03a454cb0f28f5c9d8648c06a4d:b745bdc805213c1632867ec6465f223fae94b4d0d32b27183ca8e368e7c4cb1990abea89c59866871ddc0761cb4219f538ed07a1bd75c7f59c55963c0555d8e7baf9062eda8d8a84abfe9acca509c7b0f3963de7f4b6be34e1a3b404b7a8473d)
System: Chrome 107.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?contentType=dataUse
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-02T20:05:49.939Z',to:'2022-11-02T20:11:49.939Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-02T20:05:49.939Z',to:'2022-11-02T20:11:49.939Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
does this help?
https://www.gbif.org/faq?question=opening-gbif-csv-in-excel

else let us know

> sent per email
