### ISSUE TITLE
Keywords section of the metadata

### ISSUE THREAD

**Issue by SophiePamerlon** [gbif/portal-feedback#4390]
Hello,
I've been wondering for a while where do the metadata keywords appear on a dataset's GBIF page after publishing? I can see the geographic description & taxonomical keywords (when available) but not the general keywords from the 'Keywords' metadata section.
Thanks for your help!

**Comment by mike-podolskiy90** [comment]
@SophiePamerlon Thank you for your question. I think they aren't displayed at the GBIF portal

**Comment by AbbyBenson** [comment]
Are they used in the [Schema.org representation](https://github.com/gbif/portal-feedback/issues/1669) of the dataset?

**Comment by mike-podolskiy90** [comment]
Unfortunately, I can't answer this, and it's not an IPT scope. Closing this

**Comment by MattBlissett** [comment]
We still need to answer the question!

The keywords aren't shown on the GBIF dataset page, and aren't present in the Schema.org metadata.  They are in the API response (at the bottom), e.g. https://api.gbif-uat.org/v1/dataset/0f51112f-a122-4d55-a3e0-12267186d3b9

It seems like something we should show, although I don't know what values are usually present. The default (dataset type) is shown at the very top of the page "Occurrence Dataset" etc.

**Comment by MortenHofft** [comment]
We do not show the keywords on GBIF.org. At the time we looked at the keywords and decided it made little sense. It is a free for all text field. We didn't believe it brought much value to expose it in search, but rather confusion. And I was of the opinion that keywords were mostly useful for search (but only if it is a controlled vocabulary). 

And for the detail pages I tend to think the description is more informative than the keywords. 

It makes sense to use the keywords as a booster for search results though. 

But if you miss seeing a list of keywords on the dataset pages we can add it, I'm just not convinced it brings any value honestly. But I might be the only sceptic.

Keyword examples for reference
```
New records
Location
Pisces
Occurrence
Inventaire pour étude impact
Observation
Specimen
Observations naturalistes opportunistes
Inventaire de répartition
Checklist
Samplingevent
Inventaire pour étude d'espèces ou de communautés
Metagenomics
environmental genomics
Inventorythematic
Plantas
Invasive
Alien
Metadata
Aves
Regroupement de données
Inventoryregional
PERMISO_COLECTA
Invertebrados
Mamíferos
Reptiles
Validated and verified
OccurrencePhotoID;Visual sighting
Anfibios
Inventaire/Evaluation pour plans de gestion
Peces
Colombia
aves
Numérisation de bibliographie
Inventaire d'habitat
Insecta
reptiles
Inventaire de Zonages d'intérêt
Derivedfromoccurrence
anfibios
biodiversity
Flora
flora
registro biológico
Autres études et programmes
Surveillance temporelle espèces
birds
occurrence
Boyacá
Benin
mamíferos
Biodiversidad
Fish
Inventaires généralisés et exploration
Lepidoptera
Plantae
n/a
Sweden
monitoring
Malaise Trap
Numérisation de collections
fish
Protected areas
Hymenoptera
taxonomy
Protoctistas
Taxonomicauthority
VALLE_DEL_CAUCA
Ukraine
IIAP
Surveillance communauté d'espèces
Plants
fauna
Colombia BIO
Hongos
Validated and Verified
Biodiversity
plants
Cartographie habitats
plantas
species
Coleoptera
Fauna
collection
checklist
peces
Fungi
Santander
Birds
Diptera
Inventaire type ABC
conservation
espécimen
Alianza SiB Colombia ANDI
Inventario
Sector empresarial
Taxonomy
Taxonomía
biodiversidad
páramo
SIB_MARINO
Boyacá-Bio
```

**Comment by MortenHofft** [comment]
Good point with the schema @albenson-usgs 
@dnoesgaard you have defined what goes into the schema. Would adding the keywords make sense/be possible?

**Comment by dnoesgaard** [comment]
Possible, yes. Make sense? 🤷 

They can be added to the schema as either

`"keywords": [ "keyword1, keyword2, keyword3" ]`

or

`"keywords": [ "keyword1", "keyword2", "keyword3" ]`

Probably the latter is the safest bet, but I'm not sure if anyone indexes these and in which manner.

@albenson-usgs do you have more information?

**Comment by AbbyBenson** [comment]
I don't know much about schema.org. The reason I suggested it is that I know that keywords are supposed to help with search. I don't think they are useful in the aggregators like GBIF and OBIS because the use of Darwin Core and taxonomic harmonization makes it better at finding what you are looking for than a federated portal. But since GBIF-mediated datasets are available in google dataset search- maybe it would be helpful there? 

There is a schema.org cluster at ESIP. I could ask there (in the ESIP Slack) if that would be helpful?

**Comment by dnoesgaard** [comment]
Assuming the keywords are good, then yes :)

I can see that the keywords property is listed in the [Dataset Search](https://toolbox.google.com/datasetsearch/) documentation, so I assume it would indexed/searchable.

I say go for it.

**Comment by mbjones** [comment]
ESIP science-on-schema.org guidelines on how to format keywords in schema.org: https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#keywords
