### ISSUE TITLE
add journal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4391]
**add journal**

https://www.mdpi.com/journal/diversity

Via mail fron N Ivanova who discoved the missing journal thourgh 
https://www.mdpi.com/1424-2818/14/10/825/htm

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/b4b7ceb17d6e0800e0d17c55f550c440:e2bcf6b3de2c795f1ba6d5217a491378bd0a83d4c5c08cb2af5425350d927815bd3a9b45068a0379662dbe47f875eb11824e7eca653fc34db34702018e3dced21f698e664c4d3935347c652e1b935aa941fee3cb73e864c92c2ac5d70826160c57ceb2e146de178ca05df4ad8ce41d07dfd97163523e5651adba476727984cd7) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b4b7ceb17d6e0800e0d17c55f550c440:e2bcf6b3de2c795f1ba6d5217a491378bd0a83d4c5c08cb2af5425350d927815bd3a9b45068a0379662dbe47f875eb11824e7eca653fc34db34702018e3dced21f698e664c4d3935347c652e1b935aa941fee3cb73e864c92c2ac5d70826160c57ceb2e146de178ca05df4ad8ce41d07dfd97163523e5651adba476727984cd7)
System: Chrome 107.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/data-papers
Window size: width 1365 - height 679
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-04T12:02:30.970Z',to:'2022-11-04T12:08:30.970Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-04T12:02:30.970Z',to:'2022-11-04T12:08:30.970Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Thanks @dschigel. Now added.
