### ISSUE TITLE
using curation of cluster data by eBioDiv matching service

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#4396]
Plazi established the matching service to match material citations and preserved specimen in GBIF. During the curation process, a person decides whether a MC is linked to a PS, or not by selecting the respective tag.  

https://prod.ebiodiv.org/?institutionKey=9cfe8cbf-35ff-4d93-b932-cb05d91b7922&datasetKeys=dce8feb0-6c89-11de-8225-b8a03c50a862&format=specimen_matcit&occurrenceKey=1100115091

![image](https://user-images.githubusercontent.com/4609956/200562794-3b016813-6173-4678-99ad-454d78846a87.png)

At this moment, the positive link is written into the occurrence.txt in the DWCA into the reference column, which then is displayed in the MC in GBIF. 

![image](https://user-images.githubusercontent.com/4609956/200563197-d252805b-6527-432d-ba29-ffbc059f221c.png)

We also know, who made this decision:  https://tb.plazi.org/GgServer/tdlStats/stats?outputFields=doc.contribUser+doc.contribDateTime+doc.contribDate+link.linkId+link.masterDocId+link.treatmentId+link.detailId+link.detailType+link.attributeName+link.attributeValue+link.contributeUser+link.contributeTime+link.inRoute&groupingFields=doc.contribUser+doc.contribDateTime+doc.contribDate+link.linkId+link.masterDocId+link.treatmentId+link.detailId+link.detailType+link.attributeName+link.attributeValue+link.contributeTime+link.inRoute&limit=1000&FP-link.attributeValue=1100115091&format=HTML  via https://tb.plazi.org/GgServer/tdlStats whereby the Link Attribute Value is the GBIF key for the linked occurrrence (PS). The Linked Annotation UUID is the material citation UUID in treatmentBank, part of the identifier 0387B964394BFFFCFE0CF5E8F70DF40D.mc.3B46022F394BFFFCFC0FF467FC10F3CF in GBIF.

We also know which material citations do not belong into the cluster.

How could this be integrated into the GBIF workflow? For example by adding a flag to the the respective related occurrence in https://www.gbif.org/occurrence/1100115091/cluster

**Comment by CecSve** [comment]
@timrobertson100 this seems to be a question for your team and the cluster mechanism

**Comment by timrobertson100** [comment]
I'll leave an answer here just for transparency.
I'm afraid we don't have a solution to this at the moment and it's not being worked on right now. It's certainly something we want to accommodate and we'll come back to it when we can.

**Comment by timrobertson100** [comment]
I've opened [an issue](https://github.com/gbif/pipelines/issues/822) to capture the change needed so will close this question.
