### ISSUE TITLE
Coordinates lost when data updated

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4397]
**Coordinates lost when data updated**

Hello, I'm curator of the Long Beach Herbarium and it looks like when our data updated from Symbiota on Nov 1 somehow all of our coordinate data failed to come through. We have lat/long for about 60% of our collection in the Symbiota database but none of it was ported to GBIF. This hasn't happened before and I wonder what the issue is. 
Thank you, Amanda Fisher

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5a6adc9cfa37b499414c0b73a1bcfdf7:c2f91945bb094596a982a0643246887875b749cca116dedb2dc562ff3694147bd2905ac77759d1bf861f69f770f46c249f6f295c545a4284891b232b4b5900183e36487cf16bf5a5e03a76c0bf51f31c713ed9a8e777a23fbb9e165961a94b7ec93789c939764f3c6fedd2ad328555c709a9ab7bba9d9f3638b72cd20bd7a5a0) - [Send email](https://www.gbif.org/api/feedback/user/mailto/5a6adc9cfa37b499414c0b73a1bcfdf7:c2f91945bb094596a982a0643246887875b749cca116dedb2dc562ff3694147bd2905ac77759d1bf861f69f770f46c249f6f295c545a4284891b232b4b5900183e36487cf16bf5a5e03a76c0bf51f31c713ed9a8e777a23fbb9e165961a94b7ec93789c939764f3c6fedd2ad328555c709a9ab7bba9d9f3638b72cd20bd7a5a0)
System: Chrome 107.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/user/profile
Window size: width 1789 - height 849
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-08T20:44:33.888Z',to:'2022-11-08T20:50:33.888Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-08T20:44:33.888Z',to:'2022-11-08T20:50:33.888Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by AbbyBenson** [comment]
SSH is looking into this.

**Comment by AFisherCSULB** [comment]
Hello, 
It looks like datum field uploaded into the longitude field so none of the coordinates are valid. Was there a change in the field mapping going in to GBIF or I wonder if this an issue with a change in Symbiota? 
Thank you, Amanda Fisher

**Comment by themerekat** [comment]
@ManonGros or someone else, can you look at how the data are coming into GBIF? The Darwin Core archive is being generated correctly on our end. We used the same code to push from another portal, and it's working fine. Not sure why something would be wonky with this particular portal, but I have no clue what's going on.

**Comment by MattBlissett** [comment]
In the latest DWCA at https://cch2.org/portal/content/dwca/LOB_DwC-A.zip I see `<field index="34" term="https://symbiota.org/terms/eventDate2"/>` in meta.xml, but no corresponding column in occurrence.csv -- counting from 0, the 33rd column eventDate is followed by year.

https://www.gbif.org/dataset/b2d55172-8980-4195-9632-a186edb27d5a

**Comment by themerekat** [comment]
Hm, eventDate2 is in our schema, but must be missing from the DwC-creation scripts. I'll touch base with the team again. Thank you!

**Comment by themerekat** [comment]
This has been resolved

**Comment by AFisherCSULB** [comment]
Thank you- coordinates are restored on GitHub!


_______________________________________________________

Amanda Fisher, Ph.D. (she/her)

Assoc. Prof. of Botany

Dept. of Biological Sciences

California State University, Long Beach

Long Beach, California

________________________________
