### ISSUE TITLE
Admin region files for Pakistan

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4398]
**Admin region files for Pakistan**

I am trying to ensure that what I advise wrt admin levels in Pakistan conforms to GBIF standards. Technically, Pakistan has 5 primary admin levels, essentially - country, province, division, district, tehsil, with tehsils being further divided into union councils.  I have been ignoring divisions because they do not seem to be used by biologists, but what is GBIF doing? This morning I came across https://pakistangis.org/ and it too seems to ignore divisions. Last time I looked, GBIF referenced a source that was still using FATA and Northern Areas and referred to NWFP. I trust that is no longer the case. But what is used?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b4e8763fb2bf52b5ce383b312f9a6029:2a0b619f920ea4dee26ec2059b8e55830759ee59792525fd1fabab23d8e0d82511e91c06f7d0b22495295c0c75f910b2894359f742644bfe773660ae2a4cb77e2dd5bc6fa66e1f5aa77eaeea858146cf7af8c9befb4bfa6b691c786ae65d9ee17a45e7b860496b24b2117a1fe2f480b6cc42a5abf3739f4c2a5532803dd81437bcd294cfb6c5b2db942d879ea0347928) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b4e8763fb2bf52b5ce383b312f9a6029:2a0b619f920ea4dee26ec2059b8e55830759ee59792525fd1fabab23d8e0d82511e91c06f7d0b22495295c0c75f910b2894359f742644bfe773660ae2a4cb77e2dd5bc6fa66e1f5aa77eaeea858146cf7af8c9befb4bfa6b691c786ae65d9ee17a45e7b860496b24b2117a1fe2f480b6cc42a5abf3739f4c2a5532803dd81437bcd294cfb6c5b2db942d879ea0347928)
System: Chrome 107.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?q=admin%20regions%20pakistan
Window size: width 1536 - height 754
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-11T01:46:03.609Z',to:'2022-11-11T01:52:03.609Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-11T01:46:03.609Z',to:'2022-11-11T01:52:03.609Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.

We don't currently use the stateProvince/country/municipality values on occurrences.  This could change in the future, although I'm cautious about messing up good data.

For occurrences with coordinates, we assign an administrative region value using GADM.org.  That has these subdivisions for Pakistan:

1. Province (and a Territory, "Federally Administered Tribal Area", and Capital Territory "Islamabad")
2. Division
3. District

Example search for a GADM province: https://www.gbif.org/occurrence/search?advanced=1&gadm_gid=PAK.2_1
