### ISSUE TITLE
Dataset Detail error

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4399]
**Dataset Detail error**

Some dataset pages return 500 pages:

https://www.gbif.org/dataset/f7053f73-74fb-4c9f-ab63-de28c61140c2

https://www.gbif.org/dataset/f382f0ce-323a-4091-bb9f-add557f3a9a2

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b8374780959d6684a534a65d35a4f4d4:6bd27f23b6694464996222d9a06602145ae7a733a5545e931e92695a3dc5db616270b120ce046f97912d5f2a5cadcc4cce5d6900284a4601f67927771a2066bdc7d5ac6dfc49891e31c7581c7ecff67466a88a48a6ba791f95a5ad255fdd6f58ac4343d534c9078a969e9113240f422136af6be422168e0f448ff1dc380020c2) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b8374780959d6684a534a65d35a4f4d4:6bd27f23b6694464996222d9a06602145ae7a733a5545e931e92695a3dc5db616270b120ce046f97912d5f2a5cadcc4cce5d6900284a4601f67927771a2066bdc7d5ac6dfc49891e31c7581c7ecff67466a88a48a6ba791f95a5ad255fdd6f58ac4343d534c9078a969e9113240f422136af6be422168e0f448ff1dc380020c2)
System: Safari 15.4.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/f7053f73-74fb-4c9f-ab63-de28c61140c2
Window size: width 1593 - height 443
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-11T14:55:15.884Z',to:'2022-11-11T15:01:15.884Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-11T14:55:15.884Z',to:'2022-11-11T15:01:15.884Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I cannot reproduce it. Perhaps a temporary API outage? Did you happen to check the API response @mdoering ?

**Comment by MortenHofft** [comment]
Ahh - I just see slack thread now.
Introduced in 
https://github.com/gbif/portal16/commit/361a1a5513721744bf58c78f1e43a6a210059223
and fixed in
https://github.com/gbif/portal16/commit/3f8633e62c4e6cba6e33e7e337ff6e1f009d89b7
