### ISSUE TITLE
sometimes scientific name filters are missing their name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#44]
**sometimes scientific name filters are missing their name**

names is missing in filters for this query
https://demo.gbif.org/occurrence/search?taxon_key=0&amp;taxon_key=8

seemingly not for other taxon keys.

missing canonical name. is that to be expected?

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
Reported by: @MortenHofft
System: Chrome 55.0.2883 / Mac OS X 10.10.5
Referer: https://demo.gbif.org/occurrence/search?taxon_key=0&amp;taxon_key=1&amp;taxon_key=2&amp;taxon_key=3&amp;taxon_key=4&amp;taxon_key=5&amp;taxon_key=6&amp;taxon_key=7&amp;taxon_key=8
Window size: width 1440 - height 529
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-22T10:20:11.492Z',mode:absolute,to:'2017-01-22T10:26:11.492Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-22T10:20:11.492Z',mode:absolute,to:'2017-01-22T10:26:11.492Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
Yes, unfortunately you should expect the canonical name not to be present in all cases. It only exists for scientific names that the name parser was able to parse. This is by far the majority, but all virus names, hybrid formulas and some edge cases the parser cant deal with will have it blank and the full scientificName should be given in those cases. I wonder if we should not use the full name in all cases anyways to have a means to distinguish homonyms with different authors

**Comment by MortenHofft** [comment]
sounds correct. but that is the case for suggestions as well then. 
closed with https://github.com/gbif/portal16/commit/465c8015fb6e88360b2e2eed7b5810ff79605ef9
