### ISSUE TITLE
Faculty Job Posting

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#440]
**Faculty Job Posting**

I am on the search committee for a new faculty member and GBIF data users might be a good fit. Is there a venue for me to post this advertisement so it reaches GBIF users?

Thank you,
Katja Seltmann, UCSB

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
User provided contact info: seltmann@ccber.ucsb.edu
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/
Window size: width 1298 - height 659
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-08T23:00:30.769Z',mode:absolute,to:'2017-09-08T23:06:30.769Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-08T23:00:30.769Z',mode:absolute,to:'2017-09-08T23:06:30.769Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
contacted per mail

**Comment by kcopas** [comment]
Cycle complete: https://twitter.com/GBIF/status/909731367457624064
