### ISSUE TITLE
Identified by: brak danych

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4401]
**Identified by: brak danych**

Some time in Bionomia brought this item to my attention: I was really curious to figure out who this "brak danych" was that did all the identification work on specimen records from collections of Adam Mickiewicz University (and spelled their name in all lowercase).

As I presume @ManonGros will quickly point out, nearly 50k records (20% of their data) have used Polish for "no data" in the identifiedBy field. Given that this seems exclusively the case with one dataset, should we or Piotr/KSIB encourage any adjustment?

Note, too, that the same records are missing collection codes, so maybe there's another improvement that could be made at scale…

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/35321b9990ca52808dde218964e11694:0aa0c2c5ac72a0daaa2091e030e943ed90c29cc520a57887210953770ad4112fdbb098610f6a2f22b76c86595fec2ba3d80573462f4a44cb167266190ba8a81c505d968215521c550089e371e10d27898c290da19df079ee4547695e4dcb6d48f5897c021dea62d52f3440dd7dee9a5188eefaf9549a8c7b04b8ef02c51af247) - [Send email](https://www.gbif.org/api/feedback/user/mailto/35321b9990ca52808dde218964e11694:0aa0c2c5ac72a0daaa2091e030e943ed90c29cc520a57887210953770ad4112fdbb098610f6a2f22b76c86595fec2ba3d80573462f4a44cb167266190ba8a81c505d968215521c550089e371e10d27898c290da19df079ee4547695e4dcb6d48f5897c021dea62d52f3440dd7dee9a5188eefaf9549a8c7b04b8ef02c51af247)
System: Firefox 106.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/occurrence/charts?identified_by=brak%20danych&advanced=1&occurrence_status=present
Window size: width 1440 - height 966
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-14T13:05:41.631Z',to:'2022-11-14T13:11:41.631Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-14T13:05:41.631Z',to:'2022-11-14T13:11:41.631Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
Thank you @kcopas helpdesk will follow up with the publisher

**Comment by CecSve** [comment]
The publisher has updated the dataset and 'brak danych' has been removed from the affected records.
