### ISSUE TITLE
portal not rendering HTML in "project" and "bibliography" sections of dataset page

### ISSUE THREAD

**Issue by abubelinha** [gbif/portal-feedback#4402]
I have noticed "project"  and "bibliography" sections of portal dataset pages do not yet support rendering HTML elements.

> @MattBlissett : The registry accepts HTML elements according to this sanitizer policy 
> https://github.com/gbif/registry/blob/cdb1358a56438de71eaf652223a3a0225fdb0c55/registry-service/src/main/java/org/gbif/registry/service/RegistryDatasetServiceImpl.java#L68-L77

See https://github.com/gbif/ipt/issues/1571#issuecomment-1314203720 for example datasets. 

Thanks
@abubelinha

**Comment by MortenHofft** [comment]
Thanks @abubelinha
I can see that it has been broken and has been for years!
Anyway it should work again. It will not show any tag you throw at it though. You lists in the headline for example will be removed.
Essentially we only allow p, a, i, ul, ol, li. So you cannot add an h1 in the middle of a description for example. If you have real examples with real content where you can sensibly argue that we add to many restrictions, then feel please open an issue.

**Comment by abubelinha** [comment]
Thanks @MortenHofft . Some questions:
- When you say "it should work again", you mean gbif.org?  I am just trying this in gbif-uat.org for now, but I don't see any changes in my [bibliography](https://www.gbif-uat.org/dataset/2adad0d3-6150-4eb7-ac89-b59b71833045?adfasdf#bibliography) and [project](https://www.gbif-uat.org/dataset/2adad0d3-6150-4eb7-ac89-b59b71833045/project) tests.
- I don't get what you mean with "lists in the headline will be removed": you later say "we allow ... ul, ol, li".
- I agree it's enough with current allowed tags. But it would be good to allow exactly the same kind of stuff in both portal and IPT, just to avoid confusion.
  And I think it would also be good to have **info about allowed text formatting** (html tags, markdown ...) somewhere **in the IPT manual**.  

Thanks a lot

**Comment by MortenHofft** [comment]
Works again means that the code has been changed, but it hasn't been deployed. That will probably happen at some point during today. It is currently building and then deploying to UAT. Sorry about that - i get that was a misleading statement for you.

What tags are allowed differ per element. We do not allow in list tags in headlines for example. But allow it in descriptive text. lists are not allowed within the bibliography. What is allowed has been a per case guess/decision on what is useful, legal html, and won't lead to a chaotic visual expression. No doubt there will be cases where some one believes I have taken the wrong decision and allowed too much or too little.

**Comment by abubelinha** [comment]
> What tags are allowed differ per element (...) What is allowed has been a per case guess/decision on what is useful, legal html, and won't lead to a chaotic visual expression.

Understood. I think it's just perfect like it is, as long as we know _**how**_ it is.

I miss some documentation about text formatting for both portal and IPT.
Being documented avoids users opening unnecessary issues (so I know if it's correct that `<b>` tags are still not working in some sections, or whatever).

So I'd open an IPT issue requesting to **document gbif's text formatting guidelines in IPT manual** ... but perhaps that's not the proper place, since there are other publishing tools.
Would you mind to open that issue yourself in the most suitable repository and link to it?  (or tell me where to open it, so I can do it myself).

Thanks a lot in advance
