### ISSUE TITLE
how to completely remove a dataset from gbif.org / gbif-uat.org

### ISSUE THREAD

**Issue by abubelinha** [gbif/portal-feedback#4403]
I would like to know if it's possible to completely remove a dataset from gbif (both UAT and production).

- I understand it is not advisable to do that in production registry, because it could already have been linked and cited somewhere else. So you want to keep a copy of metadata at that url, even if it's not searchable anymore ... perhaps linking to a new place (like in [#4054](https://github.com/gbif/portal-feedback/issues/4054), [#4093](https://github.com/gbif/portal-feedback/issues/4093) ...). In that case I'd like to reduce at a minimum the wrong metadata information which could remain visible in that deleted dataset.
- And what about gbif-uat.org datasets?  Is it possible to completely delete a given dataset, so the url does not serve that page anymore?

I am just wondering about the hypothetical situation where you are concerned about having published by mistake some data/metadata which should have never been made public. So you want to completely remove any traces from the web.

I guess the best approach might be (1) publishing a new empty version (blank meta/data) from IPT, so the version which GBIF portal will kept forever is replaced with this.  And then (2) use the IPT option to delete it from IPT and GBIF

Thanks
@abubelinha

**Comment by ManonGros** [comment]
yes I think that your proposed solution would be the easiest (although a completely blank metadata wouldn't exactly be possible).
