### ISSUE TITLE
Dataset download activity available through API not up to date

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4404]
**Dataset download activity available through API not up to date**

The activity reports for downloads that are available through the API do not appear to be up to date.  They end with July 2022, and provide no data for August 2022 and beyond.

I have tried accessing data multiple ways: 1) through the "Download report" button on the dataset's Activity page, for example at https://www.gbif.org/dataset/f0a7ca6e-8da6-4629-97bd-0368705a4d6b/activity ; 2) using the API page at https://www.gbif.org/developer/occurrence to make my own URL, using the options in the Occurrence Download Statistics section to either recreate the CSV/TSV export URL or to try other download statistics.  There appears to be no data available past July 2022.  

Is this expected?  If so, how often are these download activity reports updated?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6575f6d12ef5567f114a5e515adbbdee:1deeac27fe8a3cdfb3e0d610c0815b0d81f3f6ed7fdc7df31aeda7d63e055fed1c284367a0c0366bdb7c56ec07d158f73b939bbc0a0e5f657b99fb3a9df34ddac432435e69ace7027159ef4f58ea1753250ae4d2faf0500dc9da34f63f1bcbde4ebb636530a9b854da8bcb9d3ce610119e0d2b5f5d80759118fe0b59f544a8e251cd7bff1cfb48a792b1576b3d7d1389) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6575f6d12ef5567f114a5e515adbbdee:1deeac27fe8a3cdfb3e0d610c0815b0d81f3f6ed7fdc7df31aeda7d63e055fed1c284367a0c0366bdb7c56ec07d158f73b939bbc0a0e5f657b99fb3a9df34ddac432435e69ace7027159ef4f58ea1753250ae4d2faf0500dc9da34f63f1bcbde4ebb636530a9b854da8bcb9d3ce610119e0d2b5f5d80759118fe0b59f544a8e251cd7bff1cfb48a792b1576b3d7d1389)
System: Chrome 106.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq
Window size: width 864 - height 718
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-15T02:08:11.606Z',to:'2022-11-15T02:14:11.606Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-15T02:08:11.606Z',to:'2022-11-15T02:14:11.606Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
User was notified that the statistics were updated and that the numbers for November will be available in December.

**Comment by MattBlissett** [comment]
The automatic update worked on 1 March.
