### ISSUE TITLE
issue with coordinates of these datasets

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4405]
**issue with coordinates of these datasets**

https://www.gbif.org/dataset/b281d0c7-e700-4067-a47f-39eafda1b893

https://www.gbif.org/dataset/6a190a6c-f762-11e1-a439-00145eb45e9a#description

-----

Github user: @jhnwllr
User: [See in registry](https://www.gbif.org/api/feedback/user/6a9389d3934365f1fd3e8c76c6ed7ed7:963ba596edee17f72a420f871ef368a99c933d89393e78a254fd1b8574547a3a3a598c0b115762d5f140439a4527e7f0926781397bcb213cb2af5115b7b9589d2a6c7a69ae0c9b92938ec41f7c703e6a5042273d7a5ac083be4832aa4303b06b7facbce967a46e3bebc58ce9532825821c28c6dc0fbea808ee06e2c0f596a34e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6a9389d3934365f1fd3e8c76c6ed7ed7:963ba596edee17f72a420f871ef368a99c933d89393e78a254fd1b8574547a3a3a598c0b115762d5f140439a4527e7f0926781397bcb213cb2af5115b7b9589d2a6c7a69ae0c9b92938ec41f7c703e6a5042273d7a5ac083be4832aa4303b06b7facbce967a46e3bebc58ce9532825821c28c6dc0fbea808ee06e2c0f596a34e)
System: Chrome 107.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/b281d0c7-e700-4067-a47f-39eafda1b893
Window size: width 1220 - height 574
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-15T08:09:50.795Z',to:'2022-11-15T08:15:50.795Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-15T08:09:50.795Z',to:'2022-11-15T08:15:50.795Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
![image](https://user-images.githubusercontent.com/4245213/201865668-1061b518-4208-41b2-bb71-3e42c30ac84f.png)

**Comment by MattBlissett** [comment]
For b281d0c7-e700-4067-a47f-39eafda1b893 the meta.xml is incorrect, and the latitude/longitude/datum/eventDate/name fields are mixed up:

```
head -n 1 818280_data.tab | tr '|' '\n' | nl -v0
     0  id
     1  modified
     2  institutionCode
     3  CollectionCode
     4  datasetID
     5  basisOfRecord
     6  catalogNumber
     7  recordedBy
     8  scientificName
     9  kingdom
    10  geodeticDatum
    11  decimalLatitude
    12  decimalLongitude
    13  organismQuantity
    14  organismQuantityType
    15  geologicalContextID

xmllint --format meta.xml
<?xml version="1.0"?>
<archive xmlns="http://rs.tdwg.org/dwc/text/" metadata="eml.xml">
  <core encoding="UTF-8" fieldsTerminatedBy="|" linesTerminatedBy=" " fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/Occurrence">
    <files>
      <location>818280_data.tab</location>
    </files>
    <id index="0"/>
    <field index="1" term="http://purl.org/dc/terms/modified"/>
    <field index="2" term="http://rs.tdwg.org/dwc/terms/institutionCode"/>
    <field index="3" term="http://rs.tdwg.org/dwc/terms/CollectionCode"/>
    <field index="4" term="http://rs.tdwg.org/dwc/terms/datasetID"/>
    <field index="5" term="http://rs.tdwg.org/dwc/terms/basisOfRecord"/>
    <field index="6" term="http://rs.tdwg.org/dwc/terms/catalogNumber"/>
    <field index="7" term="http://rs.tdwg.org/dwc/terms/recordedBy"/>
    <field index="8" term="http://rs.tdwg.org/dwc/terms/eventDate"/>
    <field index="9" term="http://rs.tdwg.org/dwc/terms/scientificName"/>
    <field index="10" term="http://rs.tdwg.org/dwc/terms/kingdom"/>
    <field index="11" term="http://rs.tdwg.org/dwc/terms/geodeticDatum"/>
    <field index="12" term="http://rs.tdwg.org/dwc/terms/decimalLatitude"/>
    <field index="13" term="http://rs.tdwg.org/dwc/terms/decimalLongitude"/>
    <field index="14" term="http://rs.tdwg.org/dwc/terms/organismQuantity"/>
    <field index="15" term="http://rs.tdwg.org/dwc/terms/organismQuantityType"/>
  </core>
</archive>
```

This is a Pangaea dataset.

**Comment by MattBlissett** [comment]
Same problem for 6a190a6c-f762-11e1-a439-00145eb45e9a which is also Pangaea.

**Comment by MattBlissett** [comment]
Lots of Pangaea datasets are corrupt in the same way, several hundred for big errors like above, and many more for minimumElevationInMeters/geologicalContextID being mixed up.

```
for d in $(curl -Ss 'api.gbif.org/v1/installation/600586fe-f762-11e1-a439-00145eb45e9a/dataset?limit=100' | jq -r '.results[].key');
    do echo $d;
    diff <(head -n 1 $d/*.tab | tr '|' '\n' | nl -v0 -nln -w1 -s' ') \
        <(xmllint --format $d/meta.xml | grep field\  | sed 's/" term.*terms//; s/.*="//; s/"\/>//' | tr / ' ') -y -i --ignore-all-space | grep '|';
    echo;
done
```

**Comment by MattBlissett** [comment]
Hi @huberrob, would you be able to look at this?

It's noticeable on the map thumbnails scrolling through https://www.gbif.org/dataset/search?publishing_org=d5778510-eb28-11da-8629-b8a03c50a862, where there are many straight lines etc.

**Comment by huberrob** [comment]
Dear Matt,

yes I already noticed that our DwC Exporter seems to be buggy (e.g. the coordinate export) due to some changes on the underlying export library. 
I think I have fixed most of this but this still has to be tested. 

Robert

**Comment by ahahn-gbif** [comment]
It would appear that the missing eventDate column in the data file (between recordedBy and scientificName) shifts all following fields one step down against the field sequence in the meta.xml

**Comment by MattBlissett** [comment]
Thanks for fixing this quickly Robert, I think that has sorted it.

Remaining issues are lower priority and not related to this issue, but I have found them as I looked into the problem.

For some Pangaea datasets we aren't able to retrieve the DWCA at all, instead we get an error "No taxonomic information identified in dataset, skipping DwC-A ASCII table generation." 

These are:

```
c5d6095b-6775-4186-81e1-a41a56e9cbcc
800489ed-b266-4c34-8495-355537068fb1
8c468e30-1dcf-400e-9606-7ff4bf2c6e58
3c6106dd-2948-4bce-894e-e5f8258cc5e7
6ba15d13-dd67-4d24-aa91-bf6a26cd7181
c8ec4cc4-c9cf-431e-9390-d41ad30cb1ff
8259b55e-f762-11e1-a439-00145eb45e9a
824923c4-f762-11e1-a439-00145eb45e9a
8192ba94-f762-11e1-a439-00145eb45e9a
818a01e2-f762-11e1-a439-00145eb45e9a
7e5275e0-f762-11e1-a439-00145eb45e9a
```

**Comment by jhnwllr** [comment]
problem solved
![image](https://github.com/gbif/portal-feedback/assets/4245213/3ca81845-d529-41f1-9810-0a98000e66a6)
