### ISSUE TITLE
How to access from a node js file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#442]
**How to access from a node js file**

I want to access the GBIF API from my local node.js file. How can authenticate from the code to access the database.

-----
fbitem-f0bca0774a9c8eaecc8788650664fc5d3e0b6ba1

System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://www.gbif.org/developer/summary
Window size: width 1536 - height 735
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-10T06:38:19.091Z',mode:absolute,to:'2017-09-10T06:44:19.091Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-10T06:38:19.091Z',mode:absolute,to:'2017-09-10T06:44:19.091Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
You should use Basic Auth. 
If you use Node-Rest-Client, look here: https://www.npmjs.com/package/node-rest-client#basic-http-auth

If you use Request look here: https://www.haykranen.nl/2011/06/21/basic-http-authentication-in-node-js-using-the-request-module/

Most endpoints do not require authentication at all. But if you are going to push updates on datasets etc you will of course need to authenticate.

Kind regards,
Thomas
