### ISSUE TITLE
Processing error message contains wrong link to system-health

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4421]
**Processing error message contains wrong link to system-health**

Reported via email to helpdesk: the validator message that reads

Hello [name], 
We are sorry, but an error has occurred processing your data. 
Please see http://www.gbif.org/tools/data-validator/[validation key] for more details, http://www.gbif.org/system-health for the current status of GBIF.org's systems, and try again in a few minutes. 
If the problem persists, contact us using the feedback system on the website, or at helpdesk@gbif.org. Please include the validation key ([validation key]) of the failed validation. 
The GBIF Secretariat 

contains the wrong link behind the URL to system health, opening https://www.gbif.org/health instead

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d9d38f06f882b7d06b99f754a7e6a5f4:f3cf04377c2eb0aa765caae04640014d69302c5f3c87434f2fa39caddf26a7665c3d2f285dea07b3205b657845e2f45176b1bb830d018ed5658b62de3e47c4fef5ecb25a9f705814af7ed76da9895fc9c6a3b8b65273a6e721f759b32fab43a7acd7bfedbca32cca147cf70900d2684ddb6dac29e94a2a74fa68db821a8d12e6) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d9d38f06f882b7d06b99f754a7e6a5f4:f3cf04377c2eb0aa765caae04640014d69302c5f3c87434f2fa39caddf26a7665c3d2f285dea07b3205b657845e2f45176b1bb830d018ed5658b62de3e47c4fef5ecb25a9f705814af7ed76da9895fc9c6a3b8b65273a6e721f759b32fab43a7acd7bfedbca32cca147cf70900d2684ddb6dac29e94a2a74fa68db821a8d12e6)
System: Firefox 107.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator
Window size: width 1420 - height 624
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-21T08:14:38.079Z',to:'2022-11-21T08:20:38.079Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-21T08:14:38.079Z',to:'2022-11-21T08:20:38.079Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
@mike-podolskiy90 I believe you know where to fix this?
