### ISSUE TITLE
Zero occurrences in the eventID button on occurrence record page for events with present occurrences

### ISSUE THREAD

**Issue by CecSve** [gbif/portal-feedback#4424]
I noticed the issue in this [dataset](https://www.gbif.org/dataset/df12ca07-f133-4550-ab3b-fde13f0e76ba) and do not know if it is occurring in others. This dataset was recently updated to allow interpretation of scientificName in the verbatimIdentification field if the scientificName was not provided - but the issue occurs in cases where the [scientificName](https://www.gbif.org/occurrence/3448054165) is provided as well.

**The issue**
On individual [occurrence](https://www.gbif.org/occurrence/3448308167) pages, the eventID field has an button to show the total amount of occurrences in the associated event and in this case i shows 0 occurrences even though there are [6 present occurrences](https://www.gbif.org/occurrence/search?dataset_key=df12ca07-f133-4550-ab3b-fde13f0e76ba&advanced=1&event_id=http:~2F~2Ftun.fi~2FJX.1202462%232) associated with the event when you click the button. 

Is this a bug?

**Comment by MortenHofft** [comment]
It is, in the portal at first glance. Looks like strip the `#2` part of the eventId/url when we search for it

**Comment by MortenHofft** [comment]
Turns out we didn't encode eventId and organisIDs when searching, so eventIDs with characters such as the `#` above didn't work as they should. 
BTW having a url with an anchor doesn't sound like a good ID to me.
