### ISSUE TITLE
Add mentions of the Data Use Club in email notifications - registration and/or download?

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#4427]
Last Data Use Club Webinar, a lot of the participants seemed to be more from our publisher community than our user community.
Would it make sense to mention the data use club in the emails that are sent to users when they register on GBIF or when they download data?

What do you think @andrewrodrigues @dnoesgaard ?

**Comment by dnoesgaard** [comment]
I've added a snippet to the popup that users get when downloading data. It'll look something like this:

![Screenshot 2022-12-14 at 15 31 38](https://user-images.githubusercontent.com/21358085/207622939-0ee3a73d-5af2-45cf-8aa3-1cff64fd742d.png)

**Comment by ManonGros** [comment]
Thank you Daniel! I think this looks great (just the right amount of text).

**Comment by andrewrodrigues** [comment]
Agree!


Andrew Rodrigues
Programme Officer for Participation and Engagement
Global Biodiversity Information Facility (GBIF) Secretariat

Universitetsparken 15
DK-2100 Copenhagen Ø
Denmark

+45 35 33 35 62 (office, direct line)
***@***.*** (email)
anrodrigues2 (Skype)

www.gbif.org


________________________________

**Comment by MortenHofft** [comment]
Will close as it sounds like this is done. Else feel free to open again
