### ISSUE TITLE
How do I ask for specific attributes (columns in the resulting search, like "publisher country")?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#443]
**How do I ask for specific attributes (columns in the resulting search, like &quot;publisher country&quot;)?**

I want to search for all occurrences in Costa Rica, and I want to know, for each, what's the publishing country. Is that possible? - Thanks in advance for your help.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482

System: Chrome 56.0.2924 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/search
Window size: width 1366 - height 662
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-11T22:10:26.234Z',mode:absolute,to:'2017-09-11T22:16:26.234Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-11T22:10:26.234Z',mode:absolute,to:'2017-09-11T22:16:26.234Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
If the goal is simply seeing an accounting for that, the [country page for Costa Rica](https://www.gbif.org/country/CR/about) already provides the information (35 countries contribute 7,438,134 occurrences: the list shows individual totals in descending order).

If the question is focused on downloading the information, the process would be slightly different.

**Comment by MortenHofft** [comment]
In this case the country pages is indeed the only place to do so. Or the API.
But see also https://github.com/gbif/occurrence/issues/25 and https://github.com/gbif/portal16/issues/556 for related issues.
