### ISSUE TITLE
Please delete my account. Thank you!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4441]
**Please delete my account. Thank you!**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6818dd11ec7615a9b04516d2b4a8c613:eb2894e44f6da723e8e0de9964924bd39978163f162b09cdbda844f0557b8e127d0fead119e78369ca279edb557653588b4587ed8b381ed1eb5ff933dd528536a965a82156ab43ff294b076f0eec3eca8c883fb9a615458f56c03affc0a7dcde) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6818dd11ec7615a9b04516d2b4a8c613:eb2894e44f6da723e8e0de9964924bd39978163f162b09cdbda844f0557b8e127d0fead119e78369ca279edb557653588b4587ed8b381ed1eb5ff933dd528536a965a82156ab43ff294b076f0eec3eca8c883fb9a615458f56c03affc0a7dcde)
System: Chrome 107.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1536 - height 714
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-26T06:04:48.429Z',to:'2022-11-26T06:10:48.429Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-26T06:04:48.429Z',to:'2022-11-26T06:10:48.429Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
Account deleted and user notified by email.
