### ISSUE TITLE
Dataset not updating

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#4444]
We've got a Ukrainian dataset that does not seem to be updating: 

https://ukraine.ipt.gbif.no/resource?r=ancient_settlements
https://www.gbif.org/dataset/89292560-7a4c-4a05-a0b7-7c839f1c252d
https://registry.gbif.org/dataset/89292560-7a4c-4a05-a0b7-7c839f1c252d/crawling-history

There should be 3210 occurrences. There's 1 record which was added on 25 Nov which still isn't showing. We've published 3 times since then, and I've triggered a crawl on the registry page, but it's still not showing. 

The new record is an observation of Jurinea cyanoides, it should be appearing here: https://www.gbif.org/occurrence/search?dataset_key=89292560-7a4c-4a05-a0b7-7c839f1c252d&taxon_key=5392633

Any idea what's gone wrong?

**Comment by ManonGros** [comment]
Hi @rukayaj 
The dataset ingestions are currently paused while we are working on the backbone update.
We will put a message again, keep an eye on the health page. If the datasets aren't ingesting after we resume ingestions, let us know. Thanks!

**Comment by rukayaj** [comment]
Ok thank you @ManonGros :)
