### ISSUE TITLE
I would like to make a species list download with all synonyms for the accepted species, as well as the name for the species in certain languages. Is that possible or can i use any of the tools to get a certain list?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4445]
**I would like to make a species list download with all synonyms for the accepted species, as well as the name for the species in certain languages. Is that possible or can i use any of the tools to get a certain list?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c1f2cddde073c25d1f988e60d050f980:5c1d36f50d22f58e811b3ea086297a36938fc15fc9560606c596247fc816ffc6a69384e403d7515ef20787959a82749f2426d638db414823a0f40f7bb6473568dbc3823901de901aa005b6ffb2ca76fb7804e6051f8e7d264c8f3a22acaadc823d9043345656764b27a6c033738d7ba7) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c1f2cddde073c25d1f988e60d050f980:5c1d36f50d22f58e811b3ea086297a36938fc15fc9560606c596247fc816ffc6a69384e403d7515ef20787959a82749f2426d638db414823a0f40f7bb6473568dbc3823901de901aa005b6ffb2ca76fb7804e6051f8e7d264c8f3a22acaadc823d9043345656764b27a6c033738d7ba7)
System: Chrome 107.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/7734845
Window size: width 1233 - height 609
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-28T15:33:19.489Z',to:'2022-11-28T15:39:19.489Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-28T15:33:19.489Z',to:'2022-11-28T15:39:19.489Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
> replied by email

If you want to access a list of names without any associated occurrence. The easiest is to use the [GBIF Species API](https://www.gbif.org/developer/species).

This will allow you to access the synonyms of a taxon (for example here are the synonyms of Callidiellum rufipennis (Motschulsky, 1861): https://api.gbif.org/v1/species/1152186/synonyms?limit=500) as well as the vernacular names available (here are the vernaculat names for the same species: https://api.gbif.org/v1/species/1152186/vernacularNames).
If you aren’t familiar with APIs, you can check this API beginner blogpost: https://data-blog.gbif.org/post/gbif-api-beginners-guide/
In addition to that, you can also check this blogpost about the species API: https://data-blog.gbif.org/post/gbif-species-api/
