### ISSUE TITLE
How can I download a checklist data set in a csv file?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4447]
**How can I download a checklist data set in a csv file?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a40025b8c2de0495de71b0c2a1317aa2:f69bb9bf3905223049ab9bed2566866dd8de8cc26e76c2dac5cd4e7680aed576645ce6ad224bda72aa69981521567612f264962785ddcdc9ccb442b1bdc0f3dbb5df3cd8b416148d4efba9f31b9f3d0026718008c65c99ea9a6f35bcc581044681811cea4e6302bb38d8efea6b0a07c89adf83ef698de9243f71995aa70d4a2e3e9c92f310a5416a130ea8758c5e7dc4) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a40025b8c2de0495de71b0c2a1317aa2:f69bb9bf3905223049ab9bed2566866dd8de8cc26e76c2dac5cd4e7680aed576645ce6ad224bda72aa69981521567612f264962785ddcdc9ccb442b1bdc0f3dbb5df3cd8b416148d4efba9f31b9f3d0026718008c65c99ea9a6f35bcc581044681811cea4e6302bb38d8efea6b0a07c89adf83ef698de9243f71995aa70d4a2e3e9c92f310a5416a130ea8758c5e7dc4)
System: Chrome 107.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=checklist
Window size: width 1536 - height 745
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-29T15:41:07.741Z',to:'2022-11-29T15:47:07.741Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-29T15:41:07.741Z',to:'2022-11-29T15:47:07.741Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by CecSve** [comment]
User has been contacted through help desk with the following instructions.

You would need to download the zip-archive from the source from the dataset page. I will use the Catalogue of Life [checklist](https://www.gbif.org/dataset/7ddf754f-d193-4cc9-b351-99906754a03b) as an example – if you scroll down to the bottom of the page you will see the details of the GBIF registration:
 
![image](https://user-images.githubusercontent.com/54532645/204819069-4418d6b9-b152-494b-83ce-089b6411a60c.png)

Here you can click the download link for the full Darwin Core Archive where you can open the individual files in Excel.

**Comment by MortenHofft** [comment]
Notice that the Catalogue of Life dataset has a unspecified license and hence we have deliberately downplayed the option for downloading. Normally the original archive is linked to from the download menu

https://www.gbif.org/dataset/38b4c89f-584c-41bb-bd8f-cd1def33e92f
<img width="397" alt="Screenshot 2022-12-01 at 08 51 38" src="https://user-images.githubusercontent.com/6759267/204996784-01e6b1b8-e7c7-4b9a-b4f6-9c8b681b3c0c.png">

**Comment by CecSve** [comment]
Thanks @MortenHofft I can see we do this for other checklists as well, for example the [The Plant List with literature](https://www.gbif.org/dataset/d9a4eedb-e985-4456-ad46-3df8472e00e8) and we also have checklists without GBIF annotated archives but the other files are present ([example](https://www.gbif.org/dataset/f382f0ce-323a-4091-bb9f-add557f3a9a2)) - is that always missing from checklists or how does it work?

**Comment by timhirsch** [comment]
I would just add that when GBIF moved to mandatory licences for occurrence datasets the issue of licensing for checklists was set aside - it is something we will need to return to at a policy level at some point.

**Comment by MortenHofft** [comment]
> Thanks @MortenHofft I can see we do this for other checklists as well, for example the [The Plant List with literature](https://www.gbif.org/dataset/d9a4eedb-e985-4456-ad46-3df8472e00e8) and we also have checklists without GBIF annotated archives but the other files are present ([example](https://www.gbif.org/dataset/f382f0ce-323a-4091-bb9f-add557f3a9a2)) - is that always missing from checklists or how does it work?

The GBIF annotated archive, is the occurrences only (the name is not that informative one could argue). This CHECKLIST has all 3 https://www.gbif.org/dataset/e09e1e1f-2460-4017-a964-e999abd2bf66

**Comment by CecSve** [comment]
Huh. Do you know why? I suppose it is because there is occurrences associated with the checklist?
