### ISSUE TITLE
API returns lovercase enum for unspecified license

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4451]
**API returns lovercase enum for unspecified license**

https://api.gbif.org/v1/dataset/search?type=CHECKLIST&facet=license&limit=0

```
{
"name": "unspecified",
"count": 186
}
```

But the enum endpoints says uppercase
https://api.gbif.org/v1/enumeration/basic/License

The website assumes uppercase, and hence the website shows that there are no dataset with an unspecified license, but there is really 186 of them

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/1be4c6593e3782a3c32fe572d9afc6d8:46809c3095843f8804df48d553604596102043fe60969d7233b39b2e58a32edc9fa7ec474d20315ad821e9b0f1b5d41b4b0f92b4e4e22cfba26b9c869ae8fa6d9d75a3eedebb54ef9ae992cb7276f851808c4517e2644ad3f5e9dabde63ac34bbbdf856da7db213ecb17c2904fd738404e34df08aa09daed07cd176d91355a70) - [Send email](https://www.gbif.org/api/feedback/user/mailto/1be4c6593e3782a3c32fe572d9afc6d8:46809c3095843f8804df48d553604596102043fe60969d7233b39b2e58a32edc9fa7ec474d20315ad821e9b0f1b5d41b4b0f92b4e4e22cfba26b9c869ae8fa6d9d75a3eedebb54ef9ae992cb7276f851808c4517e2644ad3f5e9dabde63ac34bbbdf856da7db213ecb17c2904fd738404e34df08aa09daed07cd176d91355a70)
System: Chrome 107.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/search?type=CHECKLIST
Window size: width 1728 - height 968
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-01T07:42:56.374Z',to:'2022-12-01T07:48:56.374Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-01T07:42:56.374Z',to:'2022-12-01T07:48:56.374Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by fmendezh** [comment]
this seems to be fixed now
