### ISSUE TITLE
Visual for species stats

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4452]
**Visual for species stats**

Can we have a summary view of all species known to GBIF? Like this https://twitter.com/josef_tumbrinck/status/1324757944542613506. Can some of the code behind the pie chart or block view for occurrences breakdown by taxa? https://www.gbif.org/occurrence/taxonomy?occurrence_status=present.

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/c383e934ce5f02c8afbeaa767999e968:725b0d1755c36e125d0aa5fe22a87a594ad4f6dbfe7ee51926f08285e30ebd7446d7d4f36e60cb41d0ee73f4cec637f3ca5c72accf3bc5ec241731757fb3fdd37fbac1952de15f1c3026faa6b41294e3fabad3469ca17bb5046df660c200525fcaad6d19253f7fabdc37084268a2cc9ecafb2f6b38486606013c737d6e878113) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c383e934ce5f02c8afbeaa767999e968:725b0d1755c36e125d0aa5fe22a87a594ad4f6dbfe7ee51926f08285e30ebd7446d7d4f36e60cb41d0ee73f4cec637f3ca5c72accf3bc5ec241731757fb3fdd37fbac1952de15f1c3026faa6b41294e3fabad3469ca17bb5046df660c200525fcaad6d19253f7fabdc37084268a2cc9ecafb2f6b38486606013c737d6e878113)
System: Chrome 108.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/search?q=
Window size: width 2560 - height 1307
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-02T09:44:44.232Z',to:'2022-12-02T09:50:44.232Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-02T09:44:44.232Z',to:'2022-12-02T09:50:44.232Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
I thought I can see Metrics or Taxonomy just in the backbone dataset - but got an Animalia page instead https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c

**Comment by MortenHofft** [comment]
https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c/metrics
is this what you are looking for? A breakdown per accepted species instead of occurrence counts

<img width="653" alt="Screenshot 2022-12-02 at 13 29 12" src="https://user-images.githubusercontent.com/6759267/205293476-0d1f77df-435a-444d-9c54-cc5155431e1a.png">

**Comment by dschigel** [comment]
Yes! Thanks. I might have ask and you might have found it before - apologies if this is my blackout. It would be nice to have it as a rectangular chart, too, but this is beautification, the message is there, thanks! however, please try to go to the backbone dataset, click taxonomy and try to go back to backbone page

**Comment by MortenHofft** [comment]
> however, please try to go to the backbone dataset, click taxonomy and try to go back to backbone page

It might not be obvious enough, but for that you need to either click the browser back button or click the source link

<img width="304" alt="Screenshot 2022-12-05 at 10 11 47" src="https://user-images.githubusercontent.com/6759267/205598680-09ef7c78-7982-4557-9ac5-6a2b3888cb42.png">

We currently mostly treat the backbone like any other dataset. And we always show the taxonomy as species pages. But it might have been more intuitive to have it as part of the dataset pages. But we also wanted to avoid having the species pages replicated under the individual datasets. And wanted to keep the existing URLs.

**Comment by dschigel** [comment]
R u working on this now @MortenHofft ? I was trying to explain the bug, but could not illustrate as dataset changes every time I refresh...

**Comment by MortenHofft** [comment]
No I haven't made any changes since you created the issue.
