### ISSUE TITLE
I have been trying to download species geo-location data via GBIF. I go on getting the error Download is only supported for structured search – not for free text queries.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4454]
**I have been trying to download species geo-location data via GBIF. I go on getting the error Download is only supported for structured search – not for free text queries.**

-----

Github user: @Jojo666
User: [See in registry](https://www.gbif.org/api/feedback/user/8708afe569d36796361e35820daf083e:79a2582c04d1130b2a619dcba073a95985635d6d4063c89915aff3619d437fc5ad2c56eebf3d29cce7f434025e129bebee2ff52ac088c901bb5be55ac5cf8db1661360ffd63fee3bc78bbb32688965109ab56a80fbd529e39b25c3c2397155a4) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8708afe569d36796361e35820daf083e:79a2582c04d1130b2a619dcba073a95985635d6d4063c89915aff3619d437fc5ad2c56eebf3d29cce7f434025e129bebee2ff52ac088c901bb5be55ac5cf8db1661360ffd63fee3bc78bbb32688965109ab56a80fbd529e39b25c3c2397155a4)
System: Chrome 108.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/0193224-220831081235567
Window size: width 1711 - height 811
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-05T10:44:40.887Z',to:'2022-12-05T10:50:40.887Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-05T10:44:40.887Z',to:'2022-12-05T10:50:40.887Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@Jojo666 the query to get the Metasequoia associated with coordinates would be the following: https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&taxon_key=5284230
Is that what you tried? Was there any other filter you wanted to use?

**Comment by Jojo666** [comment]
Hi,
I was interested in obtaining the geolocation coordinates for Persea Americana for Mexico, Colombia, Brazil, USA, Chile. I tried to filter them by country and from 2010-2021. I go on getting the same error
RegardsMinerva 
    On Monday, 5 December, 2022 at 11:49:03 am GMT, Marie Grosjean ***@***.***> wrote:  
 
 


@Jojo666 the query to get the Metasequoia associated with coordinates would be the following: https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&taxon_key=5284230
Is that what you tried? Was there any other filter you wanted to use?

**Comment by ManonGros** [comment]
@Jojo666 would this query work for you? https://www.gbif.org/occurrence/search?country=MX&country=CO&country=BR&country=US&country=CL&has_coordinate=true&has_geospatial_issue=false&taxon_key=3034046&year=2010,2021

**Comment by MortenHofft** [comment]
@Jojo666 am I correct in assuming that what you did was to enter the species name in the top field. That is a free text search that returns text similar to "Persea Americana", it isn't possible to download that. You should use the structured  `scientific name` filter instead - as @ManonGros have done in above comment.

https://www.gbif.org/occurrence/download?q=Persea%20Americana&country=MX&country=CO&country=BR&country=US&country=CL&has_coordinate=true&has_geospatial_issue=false&year=2010,2021

**Comment by Jojo666** [comment]
Hi,
How do I use a structured scientific name?
RegardsMinerva 


Sent from Yahoo Mail for iPhone


On Tuesday, December 6, 2022, 9:37 am, Morten Høfft ***@***.***> wrote:




@Jojo666 am I correct in assuming that what you did was to enter the species name in the top field. That is a free text search that returns text similar to "Persea Americana", it isn't possible to download that. You should use the structured scientific name filter instead - as @ManonGros have done in above comment.

https://www.gbif.org/occurrence/download?q=Persea%20Americana&country=MX&country=CO&country=BR&country=US&country=CL&has_coordinate=true&has_geospatial_issue=false&year=2010,2021

**Comment by ManonGros** [comment]
@Jojo666 use the scientific name fied:
<img width="1054" alt="Screenshot 2022-12-06 at 10 46 11" src="https://user-images.githubusercontent.com/7677271/205876803-23db690a-1e64-4ffb-a34e-ba51a4bd608a.png">

**Comment by ManonGros** [comment]
@Jojo666 I will close the issue. If you still have issues downloading what you need, please let us know.
