### ISSUE TITLE
validation.issueType.OCCURRENCE_NOT_UNIQUELY_IDENTIFIED

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4457]
**validation.issueType.OCCURRENCE_NOT_UNIQUELY_IDENTIFIED**

how I resolve this error? it appeared in my file altough I previously validated days ago

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/231fc08b85bcedd5e7007f882bfd56b3:09916315f6c27861c1578a529e545f868f5698077b22490dc4065769629e34d54379dfb39cd53d92e60ef7dcb05a2eb4ab44a41bacb7fc0873935a3b18ac184dad8e862f7feff4d4d8124d01c983e31802f0974d214d4cf43de06d011582fdc8) - [Send email](https://www.gbif.org/api/feedback/user/mailto/231fc08b85bcedd5e7007f882bfd56b3:09916315f6c27861c1578a529e545f868f5698077b22490dc4065769629e34d54379dfb39cd53d92e60ef7dcb05a2eb4ab44a41bacb7fc0873935a3b18ac184dad8e862f7feff4d4d8124d01c983e31802f0974d214d4cf43de06d011582fdc8)
System: Chrome 107.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/tools/data-validator/cf64c58d-bf12-4aeb-8dd9-2521e7a33f73
Window size: width 1920 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-06T17:04:46.380Z',to:'2022-12-06T17:10:46.380Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-06T17:04:46.380Z',to:'2022-12-06T17:10:46.380Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by muttcg** [comment]
HI! This means that occurrence_ids are duplicated in the file, e.g. 2 records have the same occurrence_id -**MZUC_UCCC_FLEA_46916a**
The file must contain unique occurrence_id values
