### ISSUE TITLE
Bibliographic citation is not respected

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#446]
**Bibliographic citation is not respected**

This shows the dataset citation, but the verbatim view has a bibliographic citation. The publisher has approached GBIF directly and questioned this.

Should it be the case that the bibliographic citation be used where present, otherwise defaulting to the dataset citation?  Alternatively, the publisher reports that the citation should be “WoRMS Editorial Board (2017). World Register of Marine Species. Available from http://www.marinespecies.org at VLIZ. Accessed 2017-09-07. doi:10.14284/170”.

Note: This is not a nub view.

-----
fbitem-species106102536
User provided contact info: timrobertson100
System: Chrome 60.0.3112 / Mac OS X 10.11.5
Referer: https://www.gbif.org/species/106102536
Window size: width 1878 - height 1099
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-13T09:50:45.205Z',mode:absolute,to:'2017-09-13T09:56:45.205Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-13T09:50:45.205Z',mode:absolute,to:'2017-09-13T09:56:45.205Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
I would also suggest we show the bibliographicCitation value if its present.
And if not simply "SCIENTIFIC_NAME in DATASET CITATION" (preferably fixed without the metadata author)

**Comment by thomasstjerne** [comment]
The bibliographicCitation is not in the species endpoint: http://api.gbif.org/v1/species/106102536
so i pulled it from the http://api.gbif.org/v1/species/106102536/verbatim

However, if we are promoting this approach of citing, maybe the species endpoint should include the bibliographicCitation attribute

**Comment by mdoering** [comment]
Good point. Is it also not exposed on Occurrence which should follow the same citation approach I suppose.
