### ISSUE TITLE
How to get a list of all datasets related to an institution?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4461]
**How to get a list of all datasets related to an institution?**

I would like to get a list of all datasets featuring occurrences registered to the institution code G (Conservatoire et Jardin botaniques de la Ville de Genève). Is there a simple way to do this?
Thank you

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0b138ff343ba0bc7ba6ab492a35cf402:7915538fcfb147774322dab6be8dba363dd8669cc5b4af286785cc8bae1de4b39e169e1784a38062a970271cdd20c93688dc10a6b50ee080a1fc4f4777895c4e5b69c6ffa68b29a56cf940aa137aed50f1528b5b56c1568b57e3af345cbdee83b6e580e8072e4e8cc22c7b97a8da0404c708cd54db566850dd646c7663cc1f8862ca0ede77044f5278235e923e7bb0df) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0b138ff343ba0bc7ba6ab492a35cf402:7915538fcfb147774322dab6be8dba363dd8669cc5b4af286785cc8bae1de4b39e169e1784a38062a970271cdd20c93688dc10a6b50ee080a1fc4f4777895c4e5b69c6ffa68b29a56cf940aa137aed50f1528b5b56c1568b57e3af345cbdee83b6e580e8072e4e8cc22c7b97a8da0404c708cd54db566850dd646c7663cc1f8862ca0ede77044f5278235e923e7bb0df)
System: Chrome 108.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?advanced=1&institution_key=d200fcbc-972e-4488-bcb6-eaa47209148d
Window size: width 1920 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-08T11:16:55.178Z',to:'2022-12-08T11:22:55.178Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-08T11:16:55.178Z',to:'2022-12-08T11:22:55.178Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Using the API to get dataset keys: 
https://api.gbif.org/v1/occurrence/search?advanced=1&institution_key=d200fcbc-972e-4488-bcb6-eaa47209148d&limit=0&facet=datasetKey&facetLimit=1000

Using the UI 
https://www.gbif.org/occurrence/charts?advanced=1&institution_key=d200fcbc-972e-4488-bcb6-eaa47209148d
look at the last chart that lists the datasets

> NOT sent per email as I just now realise that @ManonGros is assigned

**Comment by ManonGros** [comment]
Thanks Morten! There is also the GRSciColl institution page: https://www.gbif.org/grscicoll/institution/d200fcbc-972e-4488-bcb6-eaa47209148d/metrics
And this: https://www.gbif.org/occurrence/datasets?advanced=1&institution_key=d200fcbc-972e-4488-bcb6-eaa47209148d

**Comment by ManonGros** [comment]
I sent the email.
