### ISSUE TITLE
Conflicting license and rights values

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4462]
**Conflicting license and rights values**

The occurrence values in this dataset have an obsolete http://purl.org/dc/terms/rights value of https://creativecommons.org/publicdomain/zero/1.0/, but a dataset license of http://creativecommons.org/licenses/by/4.0/legalcode

Ideally the rights value should be removed, I'm not sure it was ever part of Darwin Core.

https://www.gbif.org/dataset/5d283bb6-64dd-4626-8b3b-a4e8db5415c3

**Comment by CecSve** [comment]
We will contact the data provider through helpdesk and ask them about which license they prefer for the occurrences and alert them of the contradicting information

**Comment by CecSve** [comment]
The rights value has now been removed from the occurrence records in the dataset.
