### ISSUE TITLE
Hello, I have used data for some of the invertebrates of the Mediterranean Sea. Althought the data coordinate system is  GCS_WGS_1984 WKID: 4326 Authority: EPSG, some records of the marine species are on land but it seems like there is a difference in the projection system. Could you help me define why there is this deviation. I can take for example the species Cladocora caespitosa. Thank you in advance.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4466]
**Hello, I have used data for some of the invertebrates of the Mediterranean Sea. Althought the data coordinate system is GCS_WGS_1984 WKID: 4326 Authority: EPSG, some records of the marine species are on land but it seems like there is a difference in the projection system. Could you help me define why there is this deviation. I can take for example the species Cladocora caespitosa. Thank you in advance.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b5afb825dbd89b47956590ffc45db510:3372bbf644f76f7b845b2ddea617acaa9b82f4a94a6ec542bca10bb044a76bd58f09651cc2befa59bccf800a52ba73efbc3022ace8cf71285ff7160c6e46da0f65c88ce6303d245f79d3b791975804a7af565e557da77ce0bbb3fe937054cc69) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b5afb825dbd89b47956590ffc45db510:3372bbf644f76f7b845b2ddea617acaa9b82f4a94a6ec542bca10bb044a76bd58f09651cc2befa59bccf800a52ba73efbc3022ace8cf71285ff7160c6e46da0f65c88ce6303d245f79d3b791975804a7af565e557da77ce0bbb3fe937054cc69)
System: Chrome 108.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search
Window size: width 1366 - height 625
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-11T12:59:54.661Z',to:'2022-12-11T13:05:54.661Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-11T12:59:54.661Z',to:'2022-12-11T13:05:54.661Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email and after some back and forth:

> I have point checked a few records and I don’t find any issue relating to the geodetic datum or with any reprojection. For example, this record (https://www.gbif.org/occurrence/3858776223) doesn’t seem to have any coordinate issue. Some records that might appear on land (like this one: https://www.gbif.org/occurrence/3759300250) are associated with a lard radius of uncertainty which encompasses the sea, this is very common for sensitive species because the data providers will often obscure coordinates. In those cases, the issue isn’t the geodetic datum.
 
I also sent:
 
> You might also be interested in checking the latest webinar from our [Data Use Club](https://www.gbif.org/data-use-club) about data quality on GBIF: https://vimeo.com/771925055 in which my colleagues highlight what you need to be aware of when analyzing GBIF data.
