### ISSUE TITLE
Central Park soil samples showing in Central Asia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4475]
**Central Park soil samples showing in Central Asia**

About 2000 records within this MGNify dataset from Central Park in New York are appearing in Central Asia, apparently through flipped longitude value

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a54f922ae6c018f37e0d6d8b1bbf9af7:8a1a8548e47f49800c98c5b2604da05c82be02341f5f1a93e695bb03c3439d6757a64a038abdacc91d87592035f9ef76efd8501c2edac40c23d728a67d1d1eb63fbbfe2c792f335556c21fce0cd0ab70e24dcf02c62c4243661543d419af7cfef11fd5416f76edd90ef459454c819ae7210aecd2a3fb9cecd5cbe3c7707bddc6) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a54f922ae6c018f37e0d6d8b1bbf9af7:8a1a8548e47f49800c98c5b2604da05c82be02341f5f1a93e695bb03c3439d6757a64a038abdacc91d87592035f9ef76efd8501c2edac40c23d728a67d1d1eb63fbbfe2c792f335556c21fce0cd0ab70e24dcf02c62c4243661543d419af7cfef11fd5416f76edd90ef459454c819ae7210aecd2a3fb9cecd5cbe3c7707bddc6)
System: Chrome 108.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/search?dataset_key=4a2b864b-f3b8-4964-8147-c28e7f73499e&geometry=POLYGON((42.01332%2027.93421,112.16967%2027.93421,112.16967%2055.98474,42.01332%2055.98474,42.01332%2027.93421))&has_coordinate=true&has_geospatial_issue=false&occurrence_status=present
Window size: width 1918 - height 961
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-16T21:07:24.727Z',to:'2022-12-16T21:13:24.727Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-16T21:07:24.727Z',to:'2022-12-16T21:13:24.727Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Same as https://github.com/gbif/portal-feedback/issues/3713
