### ISSUE TITLE
Bad DWCA URL

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4485]
**Bad DWCA URL**

Links to test IPT html page, not an archive: https://ukraine.ipt.gbif.no/archive.do?r=test

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f0094567e059ffbf3e1b169ef2efc175:2258a022d7e99f416018fe2f71dfc66b5e027827eda8ed0c68e4d3c0ec699c81e8f07e4149d3e49d81712feaec1ae4e43bbd5f886d77e84d731c062eec4978bfa278612b80ba0855e5bdef580f40de95b2211b3418d0ebc02d2cad0cb3253bcfcb1700ee40d1a921134d34f1cff23d63f86950344404a241d2449c1272145c61) - [Send email](https://www.gbif.org/api/feedback/user/mailto/f0094567e059ffbf3e1b169ef2efc175:2258a022d7e99f416018fe2f71dfc66b5e027827eda8ed0c68e4d3c0ec699c81e8f07e4149d3e49d81712feaec1ae4e43bbd5f886d77e84d731c062eec4978bfa278612b80ba0855e5bdef580f40de95b2211b3418d0ebc02d2cad0cb3253bcfcb1700ee40d1a921134d34f1cff23d63f86950344404a241d2449c1272145c61)
System: Safari 16.1.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/f994f6e8-4d7d-45bd-ab10-d59ecdfdbe80
Window size: width 1340 - height 826
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-19T15:36:11.684Z',to:'2022-12-19T15:42:11.684Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-19T15:36:11.684Z',to:'2022-12-19T15:42:11.684Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@mdoering it might be called test but it is an archive with everything in it from a prod IPT: https://ukraine.ipt.gbif.no/resource?r=test. Is it really an issue?

**Comment by Mesibov** [comment]
@ManonGros, yes it **was** an issue for several days, fixed now. I had 3 Ukrainian datasets to audit for Pensoft and couldn't reach any of them, getting this instead: https://ukraine.ipt.gbif.no/setup.do As of midday today (UTC midnight 19/20 December) the Ukrainian IPT's datasets are reachable. I queried the helpdesk in Norway 2 days ago about the issue but have so far not heard back from them with an explanation. I don't know where the server/s is/are physically located or whether GBIF Norway can mirror their servers.

**Comment by ManonGros** [comment]
thanks @Mesibov this is good to know. I don't know how the Ukraine IPT is set up maybe this is a question for @rukayaj
I will close is particular issue since it has been fixed.

**Comment by rukayaj** [comment]
Hi @Mesibov I did reply to you but outlook removed you from the listing when i hit reply-all for some reason. I just forwarded you my reply.

**Comment by rukayaj** [comment]
Just to update on this issue as well - we've had some problems with this IPT as we're storing the resource files in a bucket which we're mounting onto a kubernetes pod running the IPT, and it's slowing everything down so we are trying out some different methods for syncing. So it'll be slightly unstable for the next short while.

**Comment by mdoering** [comment]
thanks all, I saw exactly the same as @Mesibov and not its fine
