### ISSUE TITLE
Smithsonian "occurrence" is an image from a paper

### ISSUE THREAD

**Issue by rdmpage** [gbif/portal-feedback#449]
Occurrence https://www.gbif.org/occurrence/1318553764 _Euryrhynchus amazoniensis_ is listed as a "HUMAN OBSERVATION" and has an associated image. There is no event data (i.e., no locality and no date). Looking at the verbatim record it's clear that this is **not** a specimen or an observation but instead a figure extracted from a paper ("Palaemonid shrimps from the Amazon Basin, Brazil (Crustacea: Decapoda: Natantia)" https://doi.org/10.5479/si.00810282.362 ). 

I don't know how common this is, but it looks like potentially a lot of Smithsonian occurrences are simply media files tagged with a species name. Surely these aren't what most people would regard as occurrences...? 

```javascript
{
	"associatedMedia": "10166527",
	"associatedOccurrences": null,
	"associatedSequences": null,
	"basisOfRecord": "HumanObservation",
	"catalogNumber": "1202502",
	"class": "Malacostraca",
	"collectionCode": "Invertebrate Zoology",
	"continent": null,
	"coordinateUncertaintyInMeters": null,
	"country": null,
	"county": null,
	"day": null,
	"decimalLatitude": null,
	"decimalLongitude": null,
	"endDayOfYear": null,
	"extensions": {
		"http://rs.tdwg.org/ac/terms/Multimedia": [{
			"PixelXDimension": "4796",
			"PixelYDimension": "7928",
			"WebStatement": "http://si.edu/Termsofuse",
			"accessURI": "http://collections.nmnh.si.edu/media/index.php?irn=10166527",
			"creator": "Molly Kelly Ryan",
			"description": "Catalog number(s):  Subject: dorsal view Artist: Kensley, Brian Medium: Ink line and stipple Published: Kensley, B. and I. Walker. 1982. Palaemonid shrimps from the Amazon Basin, Brazil (Crustacea: Decapoda: Natantia). Smithsonian Contributions to Zoology  (362):1-28. Fig. 1",
			"format": "image/jpeg",
			"identifier": "http://collections.nmnh.si.edu/media/index.php?irn=10166527",
			"providerLiteral": "Smithsonian Institution, NMNH, Invertebrate Zoology",
			"scientificName": null,
			"source": "Ryan",
			"subjectCategoryVocabulary": "Other",
			"title": "IZ Euryrhynchus amazoniensis",
			"type": "image"
		}]
	},
	"family": "Euryrhynchidae",
	"fieldNotes": null,
	"fieldNumber": null,
	"genus": "Euryrhynchus",
	"geodeticDatum": null,
	"georeferenceProtocol": null,
	"georeferenceRemarks": null,
	"habitat": null,
	"higherClassification": "Animalia, Arthropoda, Crustacea, Malacostraca, Eumalacostraca, Eucarida, Decapoda, Pleocyemata, Euryrhynchidae",
	"higherGeography": null,
	"id": "http://n2t.net/ark:/65665/33bc0f0aa-033b-486a-acf6-4c3bfc48dd4a",
	"identificationQualifier": null,
	"identifiedBy": null,
	"individualCount": "0",
	"infraspecificEpithet": null,
	"institutionCode": "USNM",
	"institutionID": "http://biocol.org/urn:lsid:biocol.org:col:34871",
	"island": null,
	"islandGroup": null,
	"kingdom": "Animalia",
	"lifeStage": null,
	"locality": null,
	"locationID": null,
	"maximumDepthInMeters": null,
	"maximumElevationInMeters": null,
	"minimumDepthInMeters": null,
	"minimumElevationInMeters": null,
	"month": null,
	"occurrenceID": "http://n2t.net/ark:/65665/33bc0f0aa-033b-486a-acf6-4c3bfc48dd4a",
	"occurrenceRemarks": "Has original artwork or illustration attached.",
	"order": "Decapoda",
	"otherCatalogNumbers": null,
	"phylum": "Arthropoda",
	"preparations": "Illustration",
	"recordNumber": null,
	"recordedBy": null,
	"references": null,
	"scientificName": "Euryrhynchus amazoniensis",
	"scientificNameAuthorship": "Tiefenbacher",
	"sex": null,
	"specificEpithet": "amazoniensis",
	"startDayOfYear": null,
	"stateProvince": null,
	"subgenus": null,
	"taxonRank": null,
	"type": "Image",
	"typeStatus": null,
	"verbatimCoordinateSystem": null,
	"verbatimDepth": null,
	"verbatimElevation": null,
	"verbatimEventDate": null,
	"verbatimLatitude": null,
	"verbatimLongitude": null,
	"waterBody": null,
	"year": null
}
```

**Comment by MortenHofft** [comment]
Isn't it the same as other occurrences we have without date and location? And as such a general question about what fields we consider a minimum for publishing?

On the website I'm not what to do aside from highlighting some metrics about the data. This is done on the dataset page and when downloading.

![screen shot 2017-09-15 at 09 51 56](https://user-images.githubusercontent.com/6759267/30472171-b4a18758-99fb-11e7-8c05-1a9c91c2853c.png)

**Comment by MattBlissett** [comment]
"Occurrence" means a single organism, but this appears to be a drawing based on multiple organisms.  It probably belongs as a checklist dataset, where the diagram would be a nice addition to a species page.

**Comment by ManonGros** [comment]
This occurrence is now "ABSENT": https://www.gbif.org/occurrence/1318553764 (individual count of 0)
Is it a good way around this type of record?
Or should we ask the Smithsonian to just exclude these altogether?
@ahahn-gbif

**Comment by jhnwllr** [comment]
This seems like a harmless edge case. Any comment @gamblebnmnh?

**Comment by gamblebnmnh** [comment]
@jhnwllr thanks for pinging me on this.  I've forwarded to our IZ collection and data mangers to ask if we should be publishing our illustration collections as occurrence records. Some are illustrations of specimens in our collection but others are not.  @MattBlissett I don't think "Occurrence" means just a singular organism it could be a lot of multiple organisms (same taxa) collected at the same time and location couldn't it?  We certainly send many records of this type.

**Comment by gamblebnmnh** [comment]
The Illustration records in our Extant Occurrence data set will be excluded when we next publish it, set for Jan 2,2022.  Sorry for the confusion.

**Comment by ManonGros** [comment]
Thank you Beth, we will close the issue now.
