### ISSUE TITLE
Contact publisher and ask if there is any plans to update the dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4496]
**Contact publisher and ask if there is any plans to update the dataset**

The platform seems to be the main citizen science observation platform in Portugal. The dataset has not been update since 2020, but the platform is still in use. 

Contact the data publisher and ask if it would be possible to update the dataset and make them aware of the option of GBIF crawling the endpoint every week for continuous updates.

-----

Github user: @CecSve
User: [See in registry](https://www.gbif.org/api/feedback/user/929eccc5d2860d03bc49d6a3db2bc8aa:a88ac88a94e6de5be32dafd6bfe098fbbfa17c4deb2d26bec88f73647272a5417f23fd2bfef66d1a0b5af840cc08afd097dd55dfc5141b77ca82edb3626bf0b0bc34e616dc8fea7e4c16b106190ca0fc76f4d71b4dbae8b501947a90ede0ecbb) - [Send email](https://www.gbif.org/api/feedback/user/mailto/929eccc5d2860d03bc49d6a3db2bc8aa:a88ac88a94e6de5be32dafd6bfe098fbbfa17c4deb2d26bec88f73647272a5417f23fd2bfef66d1a0b5af840cc08afd097dd55dfc5141b77ca82edb3626bf0b0bc34e616dc8fea7e4c16b106190ca0fc76f4d71b4dbae8b501947a90ede0ecbb)
System: Firefox 108.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/2bf7b2c0-34dc-4458-8ee4-4f99fac03b33
Window size: width 1920 - height 927
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-23T10:12:29.501Z',to:'2022-12-23T10:18:29.501Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-23T10:12:29.501Z',to:'2022-12-23T10:18:29.501Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
BioDiversity4All is hosted by iNaturalist, so I think we should get the observations through iNaturalist:

https://www.biodiversity4all.org/observations/143460223

https://www.inaturalist.org/observations/143460223

https://www.gbif.org/occurrence/3988541856

But the observations in #4494 are all-rights-reserved, so we don't get them.

**Comment by CecSve** [comment]
Thanks for clarifying this @MattBlissett. I will close this issue and leave the other open for now.
