### ISSUE TITLE
HumanObservation records are indexing in GRSciColl collections

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#4497]
Page of collections in GRSciColl display records with basisOdRecord "HumanObservation" but it should only displays records with "PreservedSpecimen".

For example, in this collection [Centro de Colecciones Biológicas de la Universidad del Magdalena
](https://www.gbif.org/grscicoll/collection/a03172d2-ea56-439c-a71d-86235e80c72e/metrics) most of the occurrences come from this dataset [Diversidad de hormigas en ambientes urbanos de la ciudad de Santa Marta](https://www.gbif.org/dataset/b56fbfec-cf01-458a-b772-2df2c8403201), but it only have records as "HumanObservation".
It happens in all the collections we cheked and not just in this particular one.

Thanks for you help,

**Comment by ManonGros** [comment]
Hi @EstebanMH-SiB
We attempt linking any occurrences with an institution or collection code or ID. However, in those cases, if there is no match, we don't flag the non-specimen occurrences. The thought behind this is that perhaps institution would want to showcase their work on non-specimen records (at the institution level).
Does it make sense?
In you opinion, would it be better not to attempt any linking at all?

**Comment by camiplata** [comment]
Hi @ManonGros !

I do think the institutions want to have a complete account of both specimen and non-specimen records, but as far I understand thats already fulfilled by the general publisher page,  for Esteban's example that will be: https://www.gbif.org/publisher/30ff48bd-4dd1-429d-a5a5-348c8e5fbfb1

For GRSciColl I would expect to have only specimen or collection records as it is something extra that the GBIF data portal didn't offer previously.  The challenge will be how to bring only collections, for records with the basisOfRecord as PreservedSpecimen is prety clear, but for MaterialSample it can be trickier, as one can use this basisOfRecord for both tissue collections, or for any other type of samples such as soil and water for eDNA.

**Comment by ManonGros** [comment]
I can see now that, working on the new GRSciColl website, linking Observations to GRSciColl might be problematic. We can get much higher numbers than the amount of specimens expected: https://grscicoll.hp.gbif-staging.org/institution/2ae7293d-9c89-46ee-9aa8-ea116dacad3f and we can get a lot of incorrect linking: https://grscicoll.hp.gbif-staging.org/institution/4999d1c2-b78a-492b-91f7-22959a30b4e2.

I will open another issue to change the way we interpret occurrences.

**Comment by ManonGros** [comment]
The behaviour was changed. Observations should no longer be linked to GRSciColl entries.
