### ISSUE TITLE
Delete a duplicated dataset in GBIF portal

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#4499]
We published this dataset in our IPT [Hongos fitopatógenos asociados a la pudrición seca de ñame, registrados en la región Caribe](https://doi.org/10.15472/rzgfzf), but for some reason it got indexed twice in GBIF.

GBIF UUID:[54817577-4cdd-4836-a077-2f13dc723db2](https://www.gbif.org/dataset/54817577-4cdd-4836-a077-2f13dc723db2)
GBIF UUID:[1d83e528-9247-4d33-8e55-dcd66c287f5b](https://www.gbif.org/dataset/1d83e528-9247-4d33-8e55-dcd66c287f5b).

We want to delete the dataset with GBIF UUID [54817577-4cdd-4836-a077-2f13dc723db2](https://www.gbif.org/dataset/54817577-4cdd-4836-a077-2f13dc723db2), because this one has a different UUID from the one displayed in the IPT.

We had this problem in the past https://github.com/gbif/portal-feedback/issues/4054 and we should like to know if there is a reason for this to happen, so we can be avoided in the future.

Thanks in advance,

**Comment by ManonGros** [comment]
I wonder if this is an issue with the IPT. What do you think @mike-podolskiy90 ?

**Comment by mike-podolskiy90** [comment]
Thanks Marie. I doubt this is an IPT thing, it must be something in the registry

**Comment by ManonGros** [comment]
Maybe @marcos-lg has an idea of what could be happening then?

**Comment by MattBlissett** [comment]
It looks more like an issue with the IPT. Here are the log entries where the datasets were created:

```
51.75.204.191 379520 488f6b87-5688-4c9a-928c-2d5355054b01 [12/Dec/2022:19:25:59 +0000] "POST http://gbrds.gbif.org/registry/ipt/resource HTTP/1.1" 201 141 pass_uncacheable '-' 'GBIF-IPT/2.5.4-raf6eaba (+https://www.gbif.org/ipt) Java/1.8.0_312 (Linux)'
51.75.204.191 245558 488f6b87-5688-4c9a-928c-2d5355054b01 [12/Dec/2022:19:25:59 +0000] "POST http://gbrds.gbif.org/registry/ipt/resource HTTP/1.1" 201 141 pass_uncacheable '-' 'GBIF-IPT/2.5.4-raf6eaba (+https://www.gbif.org/ipt) Java/1.8.0_312 (Linux)'
```

The second column is the response time.  379ms and 245ms are very reasonable response times.  Could it be the button in the IPT was pressed twice in quick succession? (If so, this should be prevented.)

**Comment by EstebanMH-SiB** [comment]
Thanks for the answers, I guess that it can be a hardware error in our side, my mouse did a missclick and was pressed twice. We will try to avoid it as much as we can.

Maybe there is a way to avoid this in the IPT for future versions, that it should be a time delay (1-2 seconds) between publications?

@ManonGros if you can help us deleting the duplicate dataset, we can close this issue after that.

Thank you very much for the help,

**Comment by ManonGros** [comment]
Thanks @EstebanMH-SiB 
I am asking just to be sure: I should delete https://www.gbif.org/dataset/1d83e528-9247-4d33-8e55-dcd66c287f5b right?
I can see that the other one is linked from the IPT:
<img width="583" alt="Screenshot 2023-01-11 at 09 08 45" src="https://user-images.githubusercontent.com/7677271/211751907-ca4d6f62-674f-4c82-a4f7-93e34c599e42.png">

**Comment by EstebanMH-SiB** [comment]
Yes that one [https://www.gbif.org/dataset/1d83e528-9247-4d33-8e55-dcd66c287f5b](https://www.gbif.org/dataset/1d83e528-9247-4d33-8e55-dcd66c287f5b).
Thanks for noticing the error in my original comment!

**Comment by ManonGros** [comment]
Thanks @EstebanMH-SiB I have deleted the dataset (the changes should be visible in a few min)
