### ISSUE TITLE
Occurrences without any taxon

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#45]
**Occurrences without any taxon**

5 _something_ observed in Togo

It is worth very little. This occurrences do not even have a verbatim name. Might it be worth adding a new type of issue for cases where no taxon is provided (not just unmatched, but not provided).

-----
fbitem-occurrence1413023764
Reported by: @MortenHofft
System: Chrome 55.0.2883 / Mac OS X 10.10.5
Referer: https://demo.gbif.org/occurrence/1413023764
Window size: width 1440 - height 776
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-22T10:29:50.130Z',mode:absolute,to:'2017-01-22T10:35:50.130Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-22T10:29:50.130Z',mode:absolute,to:'2017-01-22T10:35:50.130Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: f83b0c09-4ef6-4c6c-9868-019709ba4820
publishingOrgKey: 50e959f4-fec1-44b7-9e03-04fab5cfd3c3

**Comment by MortenHofft** [comment]
there are 703,245,140 in total

there are 700,139,947 results when [searching for all kingdoms](
https://demo.gbif.org/occurrence/search?taxon_key=0&taxon_key=1&taxon_key=2&taxon_key=3&taxon_key=4&taxon_key=5&taxon_key=6&taxon_key=7&taxon_key=8)

310,789 results of these [has kingdom without taxon match](https://demo.gbif.org/occurrence/search?issue=TAXON_MATCH_NONE&taxon_key=0&taxon_key=1&taxon_key=2&taxon_key=3&taxon_key=4&taxon_key=5&taxon_key=6&taxon_key=7&taxon_key=8)

3,327,811 is [without taxon match in total](https://demo.gbif.org/occurrence/search?issue=TAXON_MATCH_NONE)

*that raises questions*
Sometimes TAXON_MATCH_NONE [maps to incertae sedis](https://demo.gbif.org/occurrence/search?issue=TAXON_MATCH_NONE&taxon_key=0) and [other times not](https://demo.gbif.org/occurrence/search?issue=TAXON_MATCH_NONE). why not always use that kingdom key when there is no match?

i would think that
total = all_kingdoms - all_kingdoms_without_taxonmatch + wihtout_taxonmatch_total
but there is a difference on 88171

That indicates that we have 90k occurrences that do not have a kingdom, nor incertae sedis and isn't unmatched either. That seem like something i would like to know as a publisher, but how to find those records?

no taxon match includes occurrences with no verbatim taxon provided as can be seen [here](https://demo.gbif.org/occurrence/search?dataset_key=f83b0c09-4ef6-4c6c-9868-019709ba4820&issue=TAXON_MATCH_NONE)

**Comment by mdoering** [comment]
See also recent commit https://github.com/gbif/occurrence/commit/bf744aae1bc43c46cf7b761c3fb6190a09e0e89b to fix very related issue http://dev.gbif.org/issues/browse/POR-2150

**Comment by MortenHofft** [comment]
Thank you. That largely solves the issue. 

I still find it worth a discussion whether no-taxon-match is the correct remark for occurrences missing a name altogether. Currently we do not mark missing dates as invalid-date for example. Wouldn't a NO_TAXON_PROVIDED info remark be a more informative and useful flag?

**Comment by cgendreau** [comment]
moved discussion to https://github.com/gbif/gbif-api/issues/11
