### ISSUE TITLE
potter wasp record but the photo is of a butterfly

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4501]
**potter wasp record but the photo is of a butterfly**

this is a potter wasp record but the photo is of a butterfly, so is the wrong photo or wrong label

(from helpdesk)

-----

Github user: @jhnwllr
User: [See in registry](https://www.gbif.org/api/feedback/user/96860c019d35d7997858683770425a89:7d431a1169ffa1288e8926d0cc0f0ce5a9677454b863e73a1e84ecb5a9a301f11e9184d36309a51bd7cca08baa6a8785b409baf2f16a498400f92095762c70e6267c7c767c24e1e89777ee03a4510c58548e00ab85e5d45136f889451b5e77ae9fe9c03714ea87c6079c64968f7a81c513815daea55c95158214243e69212e9f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/96860c019d35d7997858683770425a89:7d431a1169ffa1288e8926d0cc0f0ce5a9677454b863e73a1e84ecb5a9a301f11e9184d36309a51bd7cca08baa6a8785b409baf2f16a498400f92095762c70e6267c7c767c24e1e89777ee03a4510c58548e00ab85e5d45136f889451b5e77ae9fe9c03714ea87c6079c64968f7a81c513815daea55c95158214243e69212e9f)
System: Chrome 108.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1455673307
Window size: width 1373 - height 646
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-30T08:25:50.156Z',to:'2022-12-30T08:31:50.156Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-30T08:25:50.156Z',to:'2022-12-30T08:31:50.156Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 750b7bfc-3577-4b26-8aaf-3e4be9f0d639
publishingOrgKey: 814cdfb5-d4f8-4453-815f-ea5df98e76bf

Node handles: @arbolitoloco

**Comment by ManonGros** [comment]
Contacted the publisher by email.

**Comment by ManonGros** [comment]
The publisher put the image on the correct record.
