### ISSUE TITLE
Some iNat research observations are not in the GBIF download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4502]
**Some iNat research observations are not in the GBIF download**

Hi, I'm researching a wide variety of flora in the mid south US for the Southeastern Grasslands Institute (SGI). I pulled down approx 28 million records that included all of the state of Tennessee and large parts of neighboring states. 

While doing QA on our post-processed data, we noticed that a colleague's iNat observations at a target site were not present in the download, but should have been. The associate is Britney Georgic (also with SGI), iNat userid b_georgic. I discovered that *none* of her 1000+ research grade observations across Tennessee were in the GBIF download. The vast majority of these observations are over a year old, so they should have made it to GBIF.

I just successfully downloaded those observations directly from iNat, so I'm unsure why they would not be present in GBIF.

My larger interest is trying to understand what other research grade observations are not making it into GBIF downloads. Basically, how complete is my dataset? 

Is there something that I can do to ensure that I pick up her (and other) observations?

Thanks,
   Chip Morgan

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/514cefa326117c59d3adca35136bb26d:29e594822cb796688c2b68e2e38f64b13ccae0fbd0591fa60bc51de962206d5f9f52bd48a9316f60ef4805bda892197f7921385f69e2e63b04bb8560bbd180e4eafd24f12e3353c5fa5205a55d97066a0ce166f7fde4a7875fb24f5005cf3e73) - [Send email](https://www.gbif.org/api/feedback/user/mailto/514cefa326117c59d3adca35136bb26d:29e594822cb796688c2b68e2e38f64b13ccae0fbd0591fa60bc51de962206d5f9f52bd48a9316f60ef4805bda892197f7921385f69e2e63b04bb8560bbd180e4eafd24f12e3353c5fa5205a55d97066a0ce166f7fde4a7875fb24f5005cf3e73)
System: Chrome 108.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0234618-220831081235567
Window size: width 1707 - height 956
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-30T20:34:59.373Z',to:'2022-12-30T20:40:59.373Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-30T20:34:59.373Z',to:'2022-12-30T20:40:59.373Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
INaturalist only share observations that are research-grade and open licensed (CC 0, CC BY or CC BY-NC). You can find more information on this page: https://doi.org/10.15468/ab3s5x
I have checked some of the observations by Brittney Georgic  and I can see that they aren’t shared under an open license: “Observation © Brittney Georgic · all rights reserved”. If possible, I suggest that Britney changes the license associated with her observations.
