### ISSUE TITLE
CORRECTION FOR lAURUS NOBILIS

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4503]
**CORRECTION FOR lAURUS NOBILIS**

Hi dear sir I live in Iran and I want to say that in many temperate parts of my country, a lot of Laurus nobilis trees have been planted in gardens, parks, green areas of cities and I can't find in "OCCURRENCES PER COUNTRY OR AREA" . 
Dr. M.A.Malekan

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/48ca2fbe3f0d75733f1fc649cb008c7b:f13e21a38b80c4a9ce7c00419b4eaafa8d3b1d695e7488fd4468c721835690aeec5be1446036967897d98616e8588a0ad6bfb5a62372a637d13680a14352f3ce6c0f217b0d8cc1f35fd216424450a718ddb821cc7829c600ea798431e6dbc7c7c1ecf6dd18bc3d66db59dc03fab6827f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/48ca2fbe3f0d75733f1fc649cb008c7b:f13e21a38b80c4a9ce7c00419b4eaafa8d3b1d695e7488fd4468c721835690aeec5be1446036967897d98616e8588a0ad6bfb5a62372a637d13680a14352f3ce6c0f217b0d8cc1f35fd216424450a718ddb821cc7829c600ea798431e6dbc7c7c1ecf6dd18bc3d66db59dc03fab6827f)
System: Chrome 108.0.0 / Windows 7.0.0
Referer: https://www.gbif.org/species/3034015/metrics
Window size: width 1366 - height 625
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-01T09:05:42.807Z',to:'2023-01-01T09:11:42.807Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-01T09:05:42.807Z',to:'2023-01-01T09:11:42.807Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Contacted by email

The data available on GBIF come from many different sources: Museums, herbaria, research teams, citizen science initiatives, etc. They usually share occurrences, in this context, an occurrence is an observation or collection of a specimen at a given place and date

The metrics available on our species pages (like here: https://www.gbif.org/species/3034015/metrics) are based on the occurrences shared on GBIF for that species. We don’t manage that information centrally.
The best way to add missing data is to share occurrences on GBIF. There are two ways to do so:

* If you are affiliated with an organization, you can register it as a GBIF publisher via this following form: https://www.gbif.org/become-a-publisher. You can read more on how to share data on GBIF here: https://www.gbif.org/publishing-data.
* If you aren’t affiliated with an organization, you can share data via one of the citizen science initiatives which share data on GBIF like https://www.inaturalist.org/ or https://identify.plantnet.org/
