### ISSUE TITLE
Macedonia wrongly shown as Moldova on network map, Kosovo leads to error page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#451]
**Macedonia wrongly shown as Moldova on network map, Kosovo leads to error page**

When you click on the boundaries of Macedonia the link shown in the top right of the map shows Republic of Moldova! Should go to https://www.gbif.org/country/MK/summary. Also boundaries of Kosovo show 'a country' and link clicks through to an error page. This one is more complicated as Kosovo is a disputed territory with 'partially recognized' independence,  but we should find a better solution for the map. For offline discussion.

-----
fbitem-2f490e24d093373543a643a154f2bbaa4c6ec09b
User provided contact info: timhirsch
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/the-gbif-network/europe
Window size: width 1800 - height 857
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-14T06:00:39.673Z',mode:absolute,to:'2017-09-14T06:06:39.673Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-14T06:00:39.673Z',mode:absolute,to:'2017-09-14T06:06:39.673Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
The Macedonia part of this issue is now fixed, and Ksovo is displayed by name, but still has no country page.

**Comment by thomasstjerne** [comment]
Kosova part of this issue is moved to https://github.com/gbif/portal16/issues/558
Macedonia is done
