### ISSUE TITLE
when i search for a fish species, it says unknow class. this is for all the fish species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4513]
**when i search for a fish species, it says unknow class. this is for all the fish species**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/091c6265b5222f05deeb363f2f450d68:68e67fd2f44987dd6f14911c11d5a0a7ed2eb53ac13860c2bc6ee7b597560b4c614437e5486e169e70a085f3c078bd143add05d075ea1ee38ec893d01df42d7f440db7bd4dc3788ae0258910901250549c79d1f1799da88be01770ab74515646) - [Send email](https://www.gbif.org/api/feedback/user/mailto/091c6265b5222f05deeb363f2f450d68:68e67fd2f44987dd6f14911c11d5a0a7ed2eb53ac13860c2bc6ee7b597560b4c614437e5486e169e70a085f3c078bd143add05d075ea1ee38ec893d01df42d7f440db7bd4dc3788ae0258910901250549c79d1f1799da88be01770ab74515646)
System: Chrome 108.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&taxon_key=2371221&geometry=POLYGON((-65.32922%20-0.50917,-65.01585%20-0.49188,-64.94018%20-0.25428,-65.33018%20-0.26911,-65.32922%20-0.50917))&occurrence_status=present
Window size: width 2560 - height 1329
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-07T18:16:42.511Z',to:'2023-01-07T18:22:42.511Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-07T18:16:42.511Z',to:'2023-01-07T18:22:42.511Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
This issue relates to https://github.com/gbif/portal-feedback/issues/4507

**Comment by CecSve** [comment]
The user has been contacted through helpdesk with the following message:
GBIF recently updated [the taxonomic backbone](https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c) which introduced some changes to how names are organized. Actinopterygii used to be a class in Catalogue of Life (the main provider of taxonomy to the GBIF backbone) and is now considered a superclass. However, GBIF does not deal with intermediate ranks so Actinopterygii no longer is an official taxon rank in our system. We are aware that this is [problematic](https://github.com/gbif/checklistbank/issues/79) and are considering how best to solve the issue. For now, you would have to search for the known fish orders to get the occurrences on GBIF.org.
