### ISSUE TITLE
no links

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4515]
**no links**

Participants and Memorandum link not inserted

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bc16328b41fe9344b016a67b1044d4d6:601b87fa2a051b3042a64e6e38131daf6f2b410352c1bd68ec0733ec9358c46c03e8fcff177d9651b12af80359b23fd8c31a9b845763a2bef38979cd58163c5972cb683e07466993ff688bc832f9a4d315db7dce6a29188fae73d3b7e20e3c22) - [Send email](https://www.gbif.org/api/feedback/user/mailto/bc16328b41fe9344b016a67b1044d4d6:601b87fa2a051b3042a64e6e38131daf6f2b410352c1bd68ec0733ec9358c46c03e8fcff177d9651b12af80359b23fd8c31a9b845763a2bef38979cd58163c5972cb683e07466993ff688bc832f9a4d315db7dce6a29188fae73d3b7e20e3c22)
System: Chrome 108.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/composition/1aKAxGBtIAQwiEBzUjz9q6/nodes
Window size: width 1920 - height 1057
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-09T10:33:02.738Z',to:'2023-01-09T10:39:02.738Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-09T10:33:02.738Z',to:'2023-01-09T10:39:02.738Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Fixed
