### ISSUE TITLE
What is material sample, material citation in the basis of record option while extracting occurrence data on GBIF?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4517]
**What is material sample, material citation in the basis of record option while extracting occurrence data on GBIF?**

-----

Github user: @HarshYadav67
User: [See in registry](https://www.gbif.org/api/feedback/user/d2d31c9e1151d2eb5ad587a7a690b4f6:a01be678a34f5bc6385ff7a6fa3bae11c9df5bc89c59d94a5603c0139706774d2b1c1846b17124f12dc4cf2e8c0fab4787118d9ebcd9c96534481c1551de5225bd7ce163698cc337c52406321247eda7a043da2d6e0c3e1b4639e39aa14380829bca5130bef7df20a6b8f9fbae24847606f873f3fb1fa73658d95a2f50ce5b5a4b17048dec3d15f0298a68a9988e170f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d2d31c9e1151d2eb5ad587a7a690b4f6:a01be678a34f5bc6385ff7a6fa3bae11c9df5bc89c59d94a5603c0139706774d2b1c1846b17124f12dc4cf2e8c0fab4787118d9ebcd9c96534481c1551de5225bd7ce163698cc337c52406321247eda7a043da2d6e0c3e1b4639e39aa14380829bca5130bef7df20a6b8f9fbae24847606f873f3fb1fa73658d95a2f50ce5b5a4b17048dec3d15f0298a68a9988e170f)
System: Chrome 108.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=Material%20sample
Window size: width 1536 - height 731
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-10T08:35:26.008Z',to:'2023-01-10T08:41:26.008Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-10T08:35:26.008Z',to:'2023-01-10T08:41:26.008Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi @HarshYadav67,
Thank you for writing.
The material citation is defined here: https://dwc.tdwg.org/terms/#materialcitation
The material sample is a legacy term and there is currently a TDWG group working on the topic. The current definition available is:
> A physical result of a sampling (or subsampling) event. In biological collections, the material sample is typically collected, and either preserved or destructively processed.
(https://dwc.tdwg.org/terms/#materialsample)

Typically a lot of the occurrences with the material sample basis of records are coming from eDNA or are based on sequences. To give an idea, here are the three top datasets providing occurrences with the basis of record "material sample":

- https://www.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c
- https://www.gbif.org/dataset/9f0e1ca6-fb08-4c72-9a4a-1e3b7a528c10
- https://www.gbif.org/dataset/a74db578-ac84-4907-ab8f-8de6eaa7df56

I will close the issue, let us know if it should be reopened.
