### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4518]
**Links not working**

The links on this page (https://www.gbif.org/composition/1aKAxGBtIAQwiEBzUjz9q6/nodes) , specifically in this sentence "Each formal Participant that signs the GBIF Memorandum of Understanding agrees to establish a Participant node, which is"
do not work (Or: they are rather links to itself)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a218f61a883debfe158b36d76f87ad79:d64a8ed1e2cfde07452d6ecdd15011c08443b831ed2c06e1c196d38fb6d2970224493f4cbcf3a842a680b35f408066c1fcc499a26b6a5cbd492f7a6de6098ec06491729cba53a921fba59c5b30ddc99559dfe1ad19528bda193b288453a8457cf9e8c7e6bdeef53c305573fb2a1909cbec3be1d22053a1d3de8f11886ff87b90b4a594ab6627e6e6f643cda5f54e4b9b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a218f61a883debfe158b36d76f87ad79:d64a8ed1e2cfde07452d6ecdd15011c08443b831ed2c06e1c196d38fb6d2970224493f4cbcf3a842a680b35f408066c1fcc499a26b6a5cbd492f7a6de6098ec06491729cba53a921fba59c5b30ddc99559dfe1ad19528bda193b288453a8457cf9e8c7e6bdeef53c305573fb2a1909cbec3be1d22053a1d3de8f11886ff87b90b4a594ab6627e6e6f643cda5f54e4b9b)
System: Chrome 108.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/composition/1aKAxGBtIAQwiEBzUjz9q6/nodes
Window size: width 2305 - height 968
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-10T10:21:12.311Z',to:'2023-01-10T10:27:12.311Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-10T10:21:12.311Z',to:'2023-01-10T10:27:12.311Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Same as #4515
