### ISSUE TITLE
username

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4523]
**username**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/47b717e9cc3740fc882bbb94ed06ce0d:1b6e605a01a32438810d04e1c9fad4909a1ed3dcab5edb884003f03966fc63a48f28ba94a2d6d28744f97f274dfb8541a1bcff1c8f1581df83c84e0ea30af746d9da8b8f7a4ea499a4807f9c4fac91479415522e443ef81391f55ea3ec0bbb320d1a32b64dbbe67ff98f64c443d0d238a7488da33a5fe8ac373f129f3b551fad374a03f3ce749eff68f4432e28c7d284) - [Send email](https://www.gbif.org/api/feedback/user/mailto/47b717e9cc3740fc882bbb94ed06ce0d:1b6e605a01a32438810d04e1c9fad4909a1ed3dcab5edb884003f03966fc63a48f28ba94a2d6d28744f97f274dfb8541a1bcff1c8f1581df83c84e0ea30af746d9da8b8f7a4ea499a4807f9c4fac91479415522e443ef81391f55ea3ec0bbb320d1a32b64dbbe67ff98f64c443d0d238a7488da33a5fe8ac373f129f3b551fad374a03f3ce749eff68f4432e28c7d284)
System: Chrome 108.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/system-health
Window size: width 1280 - height 577
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-15T08:23:11.961Z',to:'2023-01-15T08:29:11.961Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-15T08:23:11.961Z',to:'2023-01-15T08:29:11.961Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
There isn't enough information to do anything. I will close the issue. Feel free to comment with more information if you indeed have a question.

User informed per email
