### ISSUE TITLE
RGBIF

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4526]
**RGBIF**

having trouble downloading occurance data as it says 'sendNotification' is missing

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4382ca8026d1a905d03c3021ca1d41cd:150e329a18a844e581fbf24e93fb4d8f4edb48db975e25fbab9e6750211c64f103e2702a69e1fb5a9f75dc59944b39b0e8a9a01e97e66a103d4f2d430010e88cbd5d64c56cc773697dacf49d73cbd812490e336adc2e7768ef0ba69ee338b73b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/4382ca8026d1a905d03c3021ca1d41cd:150e329a18a844e581fbf24e93fb4d8f4edb48db975e25fbab9e6750211c64f103e2702a69e1fb5a9f75dc59944b39b0e8a9a01e97e66a103d4f2d430010e88cbd5d64c56cc773697dacf49d73cbd812490e336adc2e7768ef0ba69ee338b73b)
System: Chrome 108.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/user/download
Window size: width 1113 - height 710
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-16T04:06:55.662Z',to:'2023-01-16T04:12:55.662Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-16T04:06:55.662Z',to:'2023-01-16T04:12:55.662Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
related to https://github.com/gbif/portal-feedback/issues/4525

**Comment by nmtarr** [comment]
I'm having this issue or a similar one when trying to download DWCA of occurrence data via email with pygbif (occurrences.download()).  My code ran successfully last week but now returns this message and the download seems to get hung up.  Did something change with download requests?

error: #: extraneous key [created] is not permitted
#/send_notification: expected: null, found: String
#/send_notification: expected type: Boolean, found: String, with error status code 400check your number of active downloads.

**Comment by MattBlissett** [comment]
Hi nmtarr,

I think this is because PyGBIF is sending `"sendNotification": "true"` when, strictly speaking, it should send `"sendNotification": true` in the request to GBIF's API.  We've recently tightened up this part of the processing for unrelated reasons, but this part is now too strict -- even some of our older documentation has quotes around true/false values.

We hope to have this fixed tomorrow.

**Comment by nmtarr** [comment]
@MattBlissett,

Thank you for responding.  Will the fix be applied to the API or PyGBIF?

**Comment by MattBlissett** [comment]
The fix will be to the API.

**Comment by MattBlissett** [comment]
There was another problem, with PyGBIF sending `created` for download requests.

Part of the fix was to the API, and part of the fix is to PyGBIF v0.6.2.
