### ISSUE TITLE
Occurrence download statistics doesn't work for Organization

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4527]
**Occurrence download statistics doesn&#39;t work for Organization**

It looks like clicking on the "Download activity report" button or using the API call: https://api.gbif.org/v1/occurrence/download/statistics/export?publishingOrgKey=35f61245-821b-453b-9691-22ccfb41e631
gives an empty file

This isn't the case for datasets: https://api.gbif.org/v1/occurrence/download/statistics/export?datasetKey=a14ea064-1abf-45ef-85ce-669a979815d7

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/5e8bbfa9f8bbfd35aab1100ab8a54da5:5762a32d7770c1cbe76ba7db0c6fac41421f0c50339a133d057236f54c4064df6d65cdda540b2119e212401bf66fe3aa846c5a3a5d0fd12e934b14dc34d6c990063ffe702b89cee9bbf8fcfba2ba9e382484653a1055154c79271d58c5bfc2de7904a9336c125b7168ebccf31ab385600346517c84d5e5928e31cd3caa009a6d3192cb0ea78898e36da60fa191abe77a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/5e8bbfa9f8bbfd35aab1100ab8a54da5:5762a32d7770c1cbe76ba7db0c6fac41421f0c50339a133d057236f54c4064df6d65cdda540b2119e212401bf66fe3aa846c5a3a5d0fd12e934b14dc34d6c990063ffe702b89cee9bbf8fcfba2ba9e382484653a1055154c79271d58c5bfc2de7904a9336c125b7168ebccf31ab385600346517c84d5e5928e31cd3caa009a6d3192cb0ea78898e36da60fa191abe77a)
System: Safari 16.1.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/publisher/35f61245-821b-453b-9691-22ccfb41e631
Window size: width 1522 - height 798
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-16T11:49:33.389Z',to:'2023-01-16T11:55:33.389Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-16T11:49:33.389Z',to:'2023-01-16T11:55:33.389Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Probably the same cause as https://api.gbif.org/v1/occurrence/download/statistics?fromDate=2022-11&publishingOrgKey=57254bd0-8256-11d8-b7ed-b8a03c50a862
