### ISSUE TITLE
GBIF taxon backbone, Squamata etc. placed as class instead of Reptilia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4528]
**GBIF taxon backbone, Squamata etc. placed as class instead of Reptilia**

I was using your species matching tool, and noticed that Reptilia was not put as class. Instead order was empty, and Squamata was put as class. I see now in the backbone that Crocodylia and Testudines are also put as class with Reptilia as synonym. This must be a mistake or?

-----

Github user: @AstridBVW
User: [See in registry](https://www.gbif.org/api/feedback/user/87b309e455c4fb001dfc84d9ef0ca2a6:0a349523f0e23748aaaeb36b673a9425fb4043760e6e474c3c5070ce51e003c9e53ad13cab7ae1627c7507dcdad3a94a41fa15c7a3ea7244c2557fadc1c5384002c01277a15368ae3256cd6705e27073c940acc2008eaa3174bc1410ed8bbb24) - [Send email](https://www.gbif.org/api/feedback/user/mailto/87b309e455c4fb001dfc84d9ef0ca2a6:0a349523f0e23748aaaeb36b673a9425fb4043760e6e474c3c5070ce51e003c9e53ad13cab7ae1627c7507dcdad3a94a41fa15c7a3ea7244c2557fadc1c5384002c01277a15368ae3256cd6705e27073c940acc2008eaa3174bc1410ed8bbb24)
System: Safari 16.2.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/11592253
Window size: width 1440 - height 710
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-16T12:29:20.363Z',to:'2023-01-16T12:35:20.363Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-16T12:29:20.363Z',to:'2023-01-16T12:35:20.363Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@AstridBVW we are following the classification from the Catalogue of Life where Reptilia is no longer a class.
Other taxa have changed as well like Actinopterygii (see https://hosted-datasets.gbif.org/datasets/backbone/current/README.html and https://github.com/CatalogueOfLife/data/issues/484)

In order to help users find reptiles, we create an artificial Reptilia class as synonym of the four "reptile" classes. https://www.gbif.org/species/search?q=reptilia
With the following warning for the Reptilia taxon:
> This record has been created during indexing and did not explicitly exist in the source data as such.

**Comment by AstridBVW** [comment]
Ok, thank you. I'm not informed on the taxonomy of reptiles but I asked people that are. They thought it was a mistake, hence me reporting it. I will let them know your answer.

**Comment by ManonGros** [comment]
I will close the issue, let me know if it should be reopened.
