### ISSUE TITLE
This Genus might be a typo, actually intended to be Strophurus?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4530]
**This Genus might be a typo, actually intended to be Strophurus?**

See Strophurus,Fitzinger, 1843

-----

Github user: @Squitoense
User: [See in registry](https://www.gbif.org/api/feedback/user/58363523af83791f332763ff9ce025c9:833c3c106ddb53b0532be47309a91132198944d2822a6e8f601970594873e6961ce41b16f3652dec25bc29c55f08392fad90c62d8193a107fdf1e0d44f7635b946b75130be83e6f53731e32c0c14eeb0a93e3ff0ccbd69277bf106bec939b68838d35e632ceb4ffaebb6f83a33b8e4d4f1f0bf7a6977e1bd9745de1c9d2ba06cdccdb0cf38170eb1152d0a45d1842c80) - [Send email](https://www.gbif.org/api/feedback/user/mailto/58363523af83791f332763ff9ce025c9:833c3c106ddb53b0532be47309a91132198944d2822a6e8f601970594873e6961ce41b16f3652dec25bc29c55f08392fad90c62d8193a107fdf1e0d44f7635b946b75130be83e6f53731e32c0c14eeb0a93e3ff0ccbd69277bf106bec939b68838d35e632ceb4ffaebb6f83a33b8e4d4f1f0bf7a6977e1bd9745de1c9d2ba06cdccdb0cf38170eb1152d0a45d1842c80)
System: Chrome 109.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/8807507
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-17T09:29:16.761Z',to:'2023-01-17T09:35:16.761Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-17T09:29:16.761Z',to:'2023-01-17T09:35:16.761Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by mdoering** [comment]
likely. I will block it entirely from the backbone
