### ISSUE TITLE
Blank spaces before opening XML tag in Dwc-A download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4533]
**Blank spaces before opening XML tag in Dwc-A download**

Hello,

I've discovered that for some(all?) recently generated downloads, the metadata.xml file doesn't start directly with the XML opening tag, there are 4 white spaces before instead. Apparently this is not valid XML and therefore makes parsers to report an error. In our cases, that happens in the RIPARIAS early alert tool that uses Python-dwca-reader to read the files.

Example of problematic download:  https://www.gbif.org/occurrence/download/0250339-220831081235567 for example.

Thanks a lot and keep up the good work! Nicolas

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2b36e8000a864b4a27f6e6a153dcfca9:33fcebff049fa4d570e0262b5c8c320e592cec1ff064981587fb4f97cc2edf52152e566e30c35143118231f50b30af8d21d1bd44f21cf84149bbeb695303389b29e4f48bb8c55e43a4a92a6c894fa909613c9a84f0584c6017fc2c6e50361e4f4ebd4f5293eddaeb040a3d9d136c92ba) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2b36e8000a864b4a27f6e6a153dcfca9:33fcebff049fa4d570e0262b5c8c320e592cec1ff064981587fb4f97cc2edf52152e566e30c35143118231f50b30af8d21d1bd44f21cf84149bbeb695303389b29e4f48bb8c55e43a4a92a6c894fa909613c9a84f0584c6017fc2c6e50361e4f4ebd4f5293eddaeb040a3d9d136c92ba)
System: Firefox 108.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 959
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-17T13:53:00.402Z',to:'2023-01-17T13:59:00.402Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-17T13:53:00.402Z',to:'2023-01-17T13:59:00.402Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
The whole file is indented.  @fmendezh, could this be a change with events?

```
    <?xml version="1.0" encoding="utf-8"?>
    <eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/schema/eml-gbif-profile/1.2/eml.xsd"
    packageId="10.15468/dl.qmec2c"  system="http://gbif.org" scope="system"
    xml:lang="en">

    <dataset>
```

**Comment by MattBlissett** [comment]
Or @mike-podolskiy90 maybe, with the Registry metadata refactoring?

**Comment by MattBlissett** [comment]
Ah, I see Mikhail already fixed it in https://github.com/gbif/gbif-metadata-profile/commit/9eb0d23b96de733e9c6bccbfc42f4d3649edb549 but we are not using the new version in the occurrence project. 

@niconoe I've updated and deployed the fix.

0245730-220831081235567 appears to be the first affected download (
2023-01-12 13:10:39.328214+00) and 0250749-220831081235567 should be the last.  I'll look at fixing their metadata.xml files tomorrow.

**Comment by niconoe** [comment]
Wow, that was fast! Thx a lot.
