### ISSUE TITLE
Data available

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4536]
**Data available**

Greetings!!!
Hi, I've a question....
I'm needing data from 2022 about one specie in particular. I saw that in the data available for download there's missing the data from CLO from last year. I don't know when that data will be updated so I'm asking if someone there can help me with that doubt.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c80195e92046e26e3a530139dc6c49ce:00645ed55a1bfdfd7ebdfc42427e443fdf2e6a3cfd09cdcd1921c3572f6e42c67c3034d8b0abc40dd1f6285f3f0b6537adf43a24880cfa6a02c641b1564a048faf813780060db31afb5511264e95d8eead6db46633db1f53c0cc5eaad3e541569af4893fa259931bc5a0f567dbb26927) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c80195e92046e26e3a530139dc6c49ce:00645ed55a1bfdfd7ebdfc42427e443fdf2e6a3cfd09cdcd1921c3572f6e42c67c3034d8b0abc40dd1f6285f3f0b6537adf43a24880cfa6a02c641b1564a048faf813780060db31afb5511264e95d8eead6db46633db1f53c0cc5eaad3e541569af4893fa259931bc5a0f567dbb26927)
System: Chrome 109.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0253560-220831081235567
Window size: width 1366 - height 560
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-19T22:23:53.237Z',to:'2023-01-19T22:29:53.237Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-19T22:23:53.237Z',to:'2023-01-19T22:29:53.237Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

The eBird dataset contains a lot of records (it is 46% of all the occurrence records on GBIF). For that reason, it is very costly to update and we aren’t able to update it very often. The next update should be in March.
In the meanwhile, if you need to access CLO data, I suggest to work directly with their system: https://science.ebird.org/en.
