### ISSUE TITLE
what are GBIF fees for assiciated members?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4537]
**what are GBIF fees for assiciated members?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/39ddcf116d70fca1904667e37b667f2c:98b5e26889477c6e89d62d2123f4840bb7fe821c01c01d76c2f0f01e6237e9aefa5b81948aced13fd376e33394cf129ac75c55030f49919f6ce1aeba206140076e16aa3b0a88d5dee13d11aa0ebfe8057dcc8f2e5d458dba1ffd982148aa9478) - [Send email](https://www.gbif.org/api/feedback/user/mailto/39ddcf116d70fca1904667e37b667f2c:98b5e26889477c6e89d62d2123f4840bb7fe821c01c01d76c2f0f01e6237e9aefa5b81948aced13fd376e33394cf129ac75c55030f49919f6ce1aeba206140076e16aa3b0a88d5dee13d11aa0ebfe8057dcc8f2e5d458dba1ffd982148aa9478)
System: Firefox 109.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/faq?q=fee
Window size: width 1402 - height 859
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-20T15:57:10.209Z',to:'2023-01-20T16:03:10.209Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-20T15:57:10.209Z',to:'2023-01-20T16:03:10.209Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by timhirsch** [comment]
There are no fees for associate participation in GBIF (either countries or organizations).

**Comment by ManonGros** [comment]
I can see that Tim replied by email, I will close the issue.
