### ISSUE TITLE
Do you have dictionnaries for insects in your dataset repositories, ?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4540]
**Do you have dictionnaries for insects in your dataset repositories, ?**

In our lab, we are numerazing our insect collection. And we are wondering if you have dictionnaries on insect taxonomy (order, familiy, tribe, genus, species....) that you can share to establish our own virtual dataset of our insect collections. The goal is also to implement it in the future to GBIF.

Kinds regards,

Grégoire

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c0feb5bf236648c25c26c167730d10bb:aaac653cee79a5bc4b04f5671c90615e7f3a85541d4b2443e8163282ac1b7d78228f4bc2b70ac323d3c9bf9445132b5ffc5ef3e1f0f1d6b69bd0d474878821f6b122fbf85136c739e2655e5328819d009bc099185af172c350def25add4d8dc5) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c0feb5bf236648c25c26c167730d10bb:aaac653cee79a5bc4b04f5671c90615e7f3a85541d4b2443e8163282ac1b7d78228f4bc2b70ac323d3c9bf9445132b5ffc5ef3e1f0f1d6b69bd0d474878821f6b122fbf85136c739e2655e5328819d009bc099185af172c350def25add4d8dc5)
System: Chrome 109.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1536 - height 754
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-24T15:20:27.541Z',to:'2023-01-24T15:26:27.541Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-24T15:20:27.541Z',to:'2023-01-24T15:26:27.541Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I don’t think we have exactly what you need.

You could try using the [GBIF backbone taxonomy](https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c) for that purpose but you might encounter some limitations. For example, it doesn’t have many ranks you might need (tribes, subphylum, etc.). See how the GBIF backbone taxonomy is generated here: https://data-blog.gbif.org/post/gbif-backbone-taxonomy/

The [Catalogue of Life](https://www.catalogueoflife.org/) has more ranks available (but less taxa). Perhaps you could take a look?

In any case, both checklists (and more) are available for download (partially or entirely) via https://www.checklistbank.org/. For example, here is where to download the Instects from the GBIF backbone taxonomy: https://www.checklistbank.org/dataset/53147/download?taxonID=216 (you will need to log in with GBIF credentials).

> Replied by email
