### ISSUE TITLE
Longitude incorrect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4546]
**Longitude incorrect**

The decimalLongitude should be negative here. The species is only known from NA.

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/2ed0c92fad7285188cbd41bd4c9653e9:b049b6e3f03205a1ef6ecf39f48824cb730300db93d21842116b2e538b221b2f84c901bcbad7b000c9a37d76669cca7f188a8f7b966eb8f02690558cc374aff75b682a7e28c1304a7ebf6d5bd5f0a6f2d96e5cf48976884bae1597a9998baedf75d411739213fc72d2bcf1156e21918373b1e41f99f821f69eb6905de1680cd20d180ab8f42aa42e0c67046a99b293c8dbce37bfaa17bf73795a525f194305de) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2ed0c92fad7285188cbd41bd4c9653e9:b049b6e3f03205a1ef6ecf39f48824cb730300db93d21842116b2e538b221b2f84c901bcbad7b000c9a37d76669cca7f188a8f7b966eb8f02690558cc374aff75b682a7e28c1304a7ebf6d5bd5f0a6f2d96e5cf48976884bae1597a9998baedf75d411739213fc72d2bcf1156e21918373b1e41f99f821f69eb6905de1680cd20d180ab8f42aa42e0c67046a99b293c8dbce37bfaa17bf73795a525f194305de)
System: Chrome 109.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/2350121618
Window size: width 1603 - height 913
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-27T03:34:25.265Z',to:'2023-01-27T03:40:25.265Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-27T03:34:25.265Z',to:'2023-01-27T03:40:25.265Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7931dcab-94f1-46ce-8092-56e4335423de
publishingOrgKey: 7b8aff00-a9f8-11d8-944b-b8a03c50a862

Node handles: @albenson-usgs @sformel-usgs

**Comment by sformel-usgs** [comment]
I have reached out to the [contacts for the dataset](https://www.gbif.org/dataset/7931dcab-94f1-46ce-8092-56e4335423de#contacts) for help reviewing and revising the data.

**Comment by sformel-usgs** [comment]
Just received word that checked and revised the data as advised. The change should be published in the near future once their new IPT installation (upgrade to new version) is complete.

**Comment by AbbyBenson** [comment]
From what I can tell this issue is fixed and this ticket can be closed.
