### ISSUE TITLE
Delete GBIF account

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4548]
**Delete GBIF account**

I would like to permanently delete my GBIF account.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9063189faf8e3039aa85943e96ec3b11:5eaaa6f9fe31a3b9fa3abf396c8ed7faafd3c54da998a10ddc4683e289cffbbfdcc781e5b16a345823c9672b4d5886c4f482a3a2108c0ef182aa8ed7dc6061c794e01fb40b43f1b724233ac183e07826e90290f6559d49e639e7be8dfbe10906) - [Send email](https://www.gbif.org/api/feedback/user/mailto/9063189faf8e3039aa85943e96ec3b11:5eaaa6f9fe31a3b9fa3abf396c8ed7faafd3c54da998a10ddc4683e289cffbbfdcc781e5b16a345823c9672b4d5886c4f482a3a2108c0ef182aa8ed7dc6061c794e01fb40b43f1b724233ac183e07826e90290f6559d49e639e7be8dfbe10906)
System: Chrome 109.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=delete%20account
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-28T12:21:38.100Z',to:'2023-01-28T12:27:38.100Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-28T12:21:38.100Z',to:'2023-01-28T12:27:38.100Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The account has been deleted and the user notified.
