### ISSUE TITLE
Dataset not updating

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#4552]
We have a dataset we've had some difficulty publishing, so we published a test subset of it when trying to work out what was wrong. 

We fixed the issue (a comma in a field we had not noticed) and republished it about 45 minutes ago. The IPT says it was published successfully, but the dataset isn't updating on GBIF. 

https://www.gbif.org/dataset/b4934203-2d86-44a6-9fec-b55d7ab97749
https://ipt.gbif.no/resource?r=geco-solhomfjell

Please help :)

**Comment by muttcg** [comment]
Fixed

**Comment by rukayaj** [comment]
Thanks!
