### ISSUE TITLE
Modify Institution information

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4553]
**Modify Institution information**

How can I modify my institution's information?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9231e7d211063cf21a76bb450aafa7f0:e0e0f5e429ee1b7f5eab591442c9a78a504a01eb7c218bd48f1565f1dcecaf41f43e9103f6a941ae8b0f2c41a416386f0d3073ac374f510831552d05f9194782a6f0cec0bd9b44e7b9fe1fec3956a141463e60c26d930fdd34c0cc187e5e48fd5840ff1f37cd001edb1e81ff2fe171f9d910eea566548fd5fba42e3984d758a5) - [Send email](https://www.gbif.org/api/feedback/user/mailto/9231e7d211063cf21a76bb450aafa7f0:e0e0f5e429ee1b7f5eab591442c9a78a504a01eb7c218bd48f1565f1dcecaf41f43e9103f6a941ae8b0f2c41a416386f0d3073ac374f510831552d05f9194782a6f0cec0bd9b44e7b9fe1fec3956a141463e60c26d930fdd34c0cc187e5e48fd5840ff1f37cd001edb1e81ff2fe171f9d910eea566548fd5fba42e3984d758a5)
System: Firefox 109.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=institution%20modify
Window size: width 1920 - height 919
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-01T09:41:49.729Z',to:'2023-02-01T09:47:49.729Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-01T09:41:49.729Z',to:'2023-02-01T09:47:49.729Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
If your organization is registered as a [GBIF publisher](https://www.gbif.org/publisher/search) and you would like to update your organization page, just send us the update you would like to see at [helpdesk@gbif.org](mailto:helpdesk@gbif.org).
If you would like to update an institution entry in the [Global Registry of Scientific Collections](https://www.gbif.org/grscicoll) (GRSciColl), you can click on the “suggest a change” button and submit the changes you would like to see via the form.

> replied by email

**Comment by SannaMau** [comment]
@ManonGros Thank you for the info
