### ISSUE TITLE
misspelling of Homoeographa lamceolella

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4556]
**misspelling of Homoeographa lamceolella**

Homoeographa "lamceolella" is a misspelling, the correct species epithet being "lanceolella"; see the Global Database of Pyraloidea, http://globiz.pyraloidea.org/Pages/Reports/TaxonReport.aspx?ReturnUrl=%2fPages%2fReports%2fTaxonomyReport.aspx . The correct spelling has been confirmed in the original description.

-----

Github user: @spilomallynae
User: [See in registry](https://www.gbif.org/api/feedback/user/fb0266d3bac5be564cebd3fda79d804d:3933b0eabc2e30d9d20e53048c7c419d79e345db8140779335ee8b16df5fe203faf911d1065d07512118cdd7865f1a7220a0d229c2d3465282c0da01ae67418f8a5a2204eaed371a992d03e52673ad3385002a43da98f5d4018472fd05954b4f042544d33897279827a0de4ffed31ee6bea99b7c49d34ea8aa14fa8d683ed4ca3124cae4249c01cf44d24ec029298eda) - [Send email](https://www.gbif.org/api/feedback/user/mailto/fb0266d3bac5be564cebd3fda79d804d:3933b0eabc2e30d9d20e53048c7c419d79e345db8140779335ee8b16df5fe203faf911d1065d07512118cdd7865f1a7220a0d229c2d3465282c0da01ae67418f8a5a2204eaed371a992d03e52673ad3385002a43da98f5d4018472fd05954b4f042544d33897279827a0de4ffed31ee6bea99b7c49d34ea8aa14fa8d683ed4ca3124cae4249c01cf44d24ec029298eda)
System: Firefox 109.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/1875243
Window size: width 1474 - height 751
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-02T10:49:20.134Z',to:'2023-02-02T10:55:20.134Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-02T10:49:20.134Z',to:'2023-02-02T10:55:20.134Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
@dhobern sth for GLI
