### ISSUE TITLE
Broken link to a literature resource

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#456]
**Broken link to a literature resource**

Its link contains HTML tag </p> thereby breaking the link

https://doi.org/10.5038/1827-806X.43.2.10%3C/p%3E

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
User provided contact info: kbraak
System: Firefox 55.0.0 / Mac OS X 10.10.0
Referer: https://www.gbif.org/search?q=Fossil%20Vertebrate%20Database
Window size: width 1108 - height 977
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-15T09:44:59.093Z',mode:absolute,to:'2017-09-15T09:50:59.093Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-15T09:44:59.093Z',mode:absolute,to:'2017-09-15T09:50:59.093Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
This is in fact the link returned by the API http://cms-search.gbif.org:9200/_search?q=%22Fossil%20Vertebrate%20Database%22

I guess it is a content issue from mendeley?

**Comment by dnoesgaard** [comment]
Indeed. Fixed in Mendeley and reindexed.

Thanks @kbraak.
