### ISSUE TITLE
Add Specify 7 to the list of tools

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4560]
**Add Specify 7 to the list of tools**

[Specify 6](https://www.gbif.org/tool/81465/specify-6-software) is listed on the GBIF site but we are encouraging users to migrate to Specify 7 and are primarily developing that application. Can we submit a copy to have it available on GBIF in the tools category for the use of other users?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4765b7ba27fbb0baff32a314cab7025b:0239016e155aa0405ecfea915b3d80e869cb86cb1f9e033729ff401ad1903e45f03ed96671434c9b383deed45fc3bb8b2ef4d26cdc56d654a8252347ecd5f2d858f764233b5cd8e12e1a5782054b7e4d330cf23a8bf8469b6d04324e3100baf0789e8c308773a63e97e4af57dfdeafb62cdb4e30da97bc0a09aa751228fa35dd4883ccbe67143a3f4edfdb53c81c57e57cf8d2313939bad33c0f4795b03463a7) - [Send email](https://www.gbif.org/api/feedback/user/mailto/4765b7ba27fbb0baff32a314cab7025b:0239016e155aa0405ecfea915b3d80e869cb86cb1f9e033729ff401ad1903e45f03ed96671434c9b383deed45fc3bb8b2ef4d26cdc56d654a8252347ecd5f2d858f764233b5cd8e12e1a5782054b7e4d330cf23a8bf8469b6d04324e3100baf0789e8c308773a63e97e4af57dfdeafb62cdb4e30da97bc0a09aa751228fa35dd4883ccbe67143a3f4edfdb53c81c57e57cf8d2313939bad33c0f4795b03463a7)
System: Firefox 110.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/resource/search?q=Specify%206&contentType=tool
Window size: width 1280 - height 1261
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-02T22:00:07.482Z',to:'2023-02-02T22:06:07.482Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-02T22:00:07.482Z',to:'2023-02-02T22:06:07.482Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by grantfitzsimmons** [comment]
This was on behalf of the Specify Collections Consortium. You can contact if you are interested!

**Comment by dnoesgaard** [comment]
Hi @grantfitzsimmons, thanks for the request. Would you be able to provide a blurb for the tools page? Then I will get it set up right away...

**Comment by grantfitzsimmons** [comment]
Hi @dnoesgaard,

Here's a description:

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/37256050/222276799-4cb138c9-a02a-4b15-8f97-aabb92275982.png">

**Specify 7**

> Specify is a comprehensive collections management application

Specify 7 is a comprehensive collections management software developed by the Specify Collections Consortium that is web-based and accessible in any browser. It is designed to help researchers, research organizations, and natural history museums manage their collections efficiently and effectively. Specify 7 offers a wide range of features, including data entry and editing, specimen tracking, imaging and multimedia support, and advanced reporting capabilities. It is also highly customizable, allowing users to tailor the software to their specific needs and workflows. With its user-friendly interface and powerful tools, Specify 7 is a valuable asset for any organization looking to manage its collections with precision and ease. It is open-source and available on [GitHub](https://github.com/specify/specify7/). It supports exporting to GBIF, iDigBio, and other large data aggregators automatically using an RSS feed function.

It has an intuitive user interface and customizable data forms aimed at streamlining routine collection data tasks while preparing and validating collection information for research analysis. Specify has an ever-growing list of features including robust support for a large number of disciplines and divisions, multimedia attachments, GUIDs, hierarchical storage, taxonomy, and geography data, bulk data importing from spreadsheets using the Workbench, accessions, loans, DNA sequencing data, and many additional functions. Specify supports the use of record sets for various types of processing, such as georeferencing with GEOLocate, printing labels for specimens, or building reports for interactions between institutions. It supports robust security with extraordinary granularity and is largely compliant with WCAG 2.1 standards for incredible accessibility. [Hosting is available](https://www.specifysoftware.org/products/cloud/) for members of the Specify Collections Consortium, or it can be self-hosted at your institution.

https://www.specifysoftware.org/products/specify-7/

**Comment by dnoesgaard** [comment]
All done: https://www.gbif.org/tool/7klSM5htvcvNLdbsLurT6f/specify-7

Would you like me to remove the Specify 6 page altogether?

**Comment by grantfitzsimmons** [comment]
Hi @dnoesgaard,

No need to remove Specify 6's listing, but thank you so much for your time! It looks great!
