### ISSUE TITLE
Wrong Country

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4562]
**Wrong Country**

The Location is wrongly listed as Asia>Indonesia>Sumatra, Ulu Gombak road is in the state of Selangor, Malaysia.

Best wishes
Wei Harn

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/775ee42a999e8dbb7db61cb55c6e9571:250d699aedeb392212fa88817b37fb19e926bfc4bd7c993c8c1075226b297365ff8b74ab724f50e6a96f01f45d856368e82609eaa7b5beecab7043d7655877867bb6f441ec561e6d12f14ef82d5fb25be2c936f68364e5702fb797830ce277d0) - [Send email](https://www.gbif.org/api/feedback/user/mailto/775ee42a999e8dbb7db61cb55c6e9571:250d699aedeb392212fa88817b37fb19e926bfc4bd7c993c8c1075226b297365ff8b74ab724f50e6a96f01f45d856368e82609eaa7b5beecab7043d7655877867bb6f441ec561e6d12f14ef82d5fb25be2c936f68364e5702fb797830ce277d0)
System: Chrome 109.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2513860637
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-07T06:31:40.807Z',to:'2023-02-07T06:37:40.807Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-07T06:31:40.807Z',to:'2023-02-07T06:37:40.807Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 15f819bd-6612-4447-854b-14d12ee1022d
publishingOrgKey: 396d5f30-dea9-11db-8ab4-b8a03c50a862
Network keys: 17abcf75-2f1e-46dd-bf75-a5b21dd02655

**Comment by CecSve** [comment]
The user and the data publishers from Naturalis has been contacted via helpdesk

**Comment by jhnwllr** [comment]
Seems like the record was fixed. 
```
Location
Term	Interpreted	Original	Remarks
Continent	ASIA	Asia	
Country or area	Malaysia	Malaysia/Malaya	Altered
Country code	MY		Inferred
Decimal latitude	3.3	3.3	
Decimal longitude	101.78	101.78	
Geodetic datum	WGS84	WGS84	
Locality	Culver 19/5 Ulu Gombak road.	Culver 19/5 Ulu Gombak road.	
Verbatim elevation	1500 m	1500 m
```
