### ISSUE TITLE
Wrong Location

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4563]
**Wrong Location**

Wrong Country listed Asia>Indonesia>Sumatra

Correct country Should be Asia>Malaysia>Peninsular Malaysia

Locality Rengam F.R., Kluang, Johore (modern day state of Johor) is in Malaysia.

For further queries, I'm reachable at weiharn.tan@gmail.com

Best wishes
Wei Harn

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c29e7b02b08ea757662c96332ce80e56:745a97839ee6948ad56a547bafcf14d7a218918b9a27dd97062973e58b1d76850c55115280505955baf044f18c4de1b71aa06874c6cd37269130d5a8055c4a07e1387f957e9bd1cfcda78b56c0521e4852731db731a6c192bd92e3530463a226) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c29e7b02b08ea757662c96332ce80e56:745a97839ee6948ad56a547bafcf14d7a218918b9a27dd97062973e58b1d76850c55115280505955baf044f18c4de1b71aa06874c6cd37269130d5a8055c4a07e1387f957e9bd1cfcda78b56c0521e4852731db731a6c192bd92e3530463a226)
System: Chrome 109.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2513861333
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-07T06:35:59.734Z',to:'2023-02-07T06:41:59.734Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-07T06:35:59.734Z',to:'2023-02-07T06:41:59.734Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 15f819bd-6612-4447-854b-14d12ee1022d
publishingOrgKey: 396d5f30-dea9-11db-8ab4-b8a03c50a862
Network keys: 17abcf75-2f1e-46dd-bf75-a5b21dd02655

**Comment by CecSve** [comment]
The user and the data publishers from Naturalis has been contacted via helpdesk

**Comment by jhnwllr** [comment]
Seems as though the record was corrected.
