### ISSUE TITLE
Hi, I need to change my last name and also my email address for my GBIF account, but I don't see a way to do that here.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4564]
**Hi, I need to change my last name and also my email address for my GBIF account, but I don&#39;t see a way to do that here.**

-----

Github user: @rachwilliams56
User: [See in registry](https://www.gbif.org/api/feedback/user/c81fcca1298b0bae4b76b88a9848bb8e:02a181f9ccdd799fc58d20dbd7bcd727e40b968789cb4d3322f10d6e2480b6e637f006492695d73e31298a2a0087f8c0a911644e9485a241acd3f3ae91f382456c1dccc2cc06d90f79d65b44b785242d41d6f667cb7041516a0fb7b3a00e2764727ea055e8b726d9b10e53a68aabd217b967ee1cf2f4ce1200da89fba641df2cb41caf847c1edb157d4627c209f0d836) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c81fcca1298b0bae4b76b88a9848bb8e:02a181f9ccdd799fc58d20dbd7bcd727e40b968789cb4d3322f10d6e2480b6e637f006492695d73e31298a2a0087f8c0a911644e9485a241acd3f3ae91f382456c1dccc2cc06d90f79d65b44b785242d41d6f667cb7041516a0fb7b3a00e2764727ea055e8b726d9b10e53a68aabd217b967ee1cf2f4ce1200da89fba641df2cb41caf847c1edb157d4627c209f0d836)
System: Chrome 109.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/user/profile
Window size: width 1768 - height 1395
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-07T17:09:10.078Z',to:'2023-02-07T17:15:10.078Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-07T17:09:10.078Z',to:'2023-02-07T17:15:10.078Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
Thank you for contacting us through our feedback system. You can change your GBIF profile information by clicking the ‘start editing’ button, see the highlight in the image below:
 
![image](https://user-images.githubusercontent.com/54532645/217485769-a9e587eb-310b-4768-9bc4-2cf837f668b7.png)
