### ISSUE TITLE
download the occurrence data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4566]
**download the occurrence data**

Hi, I want to download the occurrence data of white stork. could you please tell me how to download the dataset?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4b986fb05d7ff1300b74e371d28faef7:e1fe696dcc674a4999c17d45c7777efd024d47d875b13dabe30a5926fc508cca06dcc4b6668f04202f25dd6027a782b863a10ad3e2a7e7603504f6a4346b76582565bfc610a950e3a5538ea4852aee14f021b6214b88acfa1972caaae904da66) - [Send email](https://www.gbif.org/api/feedback/user/mailto/4b986fb05d7ff1300b74e371d28faef7:e1fe696dcc674a4999c17d45c7777efd024d47d875b13dabe30a5926fc508cca06dcc4b6668f04202f25dd6027a782b863a10ad3e2a7e7603504f6a4346b76582565bfc610a950e3a5538ea4852aee14f021b6214b88acfa1972caaae904da66)
System: Chrome 109.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/0197594-200613084148143
Window size: width 1920 - height 798
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-09T16:43:27.887Z',to:'2023-02-09T16:49:27.887Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-09T16:43:27.887Z',to:'2023-02-09T16:49:27.887Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
The user has been contacted via helpdesk with the following reply:

. GBIF currently holds > 1 million records of the white stork: https://www.gbif.org/occurrence/search?taxon_key=2481912 and you may want to provide further filters (menu bar to the left), before you download the data. You can either download the data by clicking the download button (see image):

 
![image](https://user-images.githubusercontent.com/54532645/218060249-ff73c5ab-2fd8-41bc-86be-b8f99a7a0531.png)


Or by using the API.
