### ISSUE TITLE
GBIF Backbone Taxonomy is a source for itself

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4571]
**GBIF Backbone Taxonomy is a source for itself**

In the description of the [GBIF Backbone Taxonomy](https://doi.org/10.15468/39omei) 100 sources of names are listed. Eighth on this list is, "GBIF Backbone Taxonomy - 118213 names." This seems recursive and nonsensical. What does this mean the source is for those nearly hundred and twenty thousand names?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b734a58d4a01894c4dcf9320315a19d7:299c65e39fe0e1ea3a9daa1f78a0ff154bd8619cc1ec0f5936c2e15655a88a9fb0e8b6ce509bbd15d4c4030e31b56cfbff784bb273c7b7c0b42186e2ba08fd48c6d8617a7f09a59dd82ebb7a338944b61d71015ec398e897b23767d1affa965f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b734a58d4a01894c4dcf9320315a19d7:299c65e39fe0e1ea3a9daa1f78a0ff154bd8619cc1ec0f5936c2e15655a88a9fb0e8b6ce509bbd15d4c4030e31b56cfbff784bb273c7b7c0b42186e2ba08fd48c6d8617a7f09a59dd82ebb7a338944b61d71015ec398e897b23767d1affa965f)
System: Firefox 109.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
Window size: width 1328 - height 698
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-13T22:12:54.341Z',to:'2023-02-13T22:18:54.341Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-13T22:12:54.341Z',to:'2023-02-13T22:18:54.341Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Not sure why that is actually. Perhaps this is a question for @thomasstjerne or @mdoering ?

**Comment by mdoering** [comment]
This is for taxa that basically have no source. They are created by the backbone algorithm. Kingdoms are the only records with origin=source, others are autonyms or ex author based implicit names:

https://www.gbif.org/species/search?dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&constituent_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&origin=SOURCE&advanced=1

**Comment by mdoering** [comment]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/327505/219063952-cf23c851-0cfb-4869-a321-0f54af26758d.png">

**Comment by sjl197** [comment]
"This is for taxa that basically have no source"
Every valid species description has a source. Otherwise they're invalid.

**Comment by mdoering** [comment]
Thats the nomenclatural reference aka dwc:namePublishedIn which is not to be confused with the source as where the backbone has directly retrieved the name from. And like I said for autonyms and other algorithmically generated names we don't have any.
