### ISSUE TITLE
I would like to download a map with the occurence data of a certain species. How can I do that? Is it possible at all?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4574]
**I would like to download a map with the occurence data of a certain species. How can I do that? Is it possible at all?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/942c1c08f5d15e2f6a9adea64dfc6878:d0040c2db92672127304c88aeda62c03adde59678d386ac8d55c4afc0282fcbaab70440f8e012003d36fb5d5e0d2bb903b69fe9ba9bbdf676225d5ad5788a3df113eb38e3ead9a8daebc35ed6936c91b6262c944132966a558ab7da3d14532cd) - [Send email](https://www.gbif.org/api/feedback/user/mailto/942c1c08f5d15e2f6a9adea64dfc6878:d0040c2db92672127304c88aeda62c03adde59678d386ac8d55c4afc0282fcbaab70440f8e012003d36fb5d5e0d2bb903b69fe9ba9bbdf676225d5ad5788a3df113eb38e3ead9a8daebc35ed6936c91b6262c944132966a558ab7da3d14532cd)
System: Firefox 110.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/5197206
Window size: width 1920 - height 899
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-16T11:05:27.453Z',to:'2023-02-16T11:11:27.453Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-16T11:05:27.453Z',to:'2023-02-16T11:11:27.453Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Here are a few ways you can generate maps from GBIF data:
* One way would be to use our Map API (https://www.gbif.org/developer/maps). One of my colleagues wrote a very short guide on how to use the API to make high resolution maps: https://labs.gbif.org/~mblissett/2021/03/high-resolution-maps/. If you aren’t familiar with APIs, you can check the recorded webinar from our Data Use Club on the topic [here](https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa/data-use-club-practical-session-3-recording-and-resources). 
* An alternative (and perhaps better option) might be to just download the occurrences and generate the maps afterwards in third party program. The advantage of that method is that you can clean up the data before you plot it. You can find more about the kinds of issues you might encounter with the data on GBIF [here](https://www.gbif.org/composition/3CF30vzt0K8AjoWOnmJsDR/data-use-club-practical-session-2-recording-and-resources-2). Perhaps [this thread](https://discourse.gbif.org/t/species-specific-icons-on-distribution-map/3817) on our forum would be useful as well.

> replied by email
