### ISSUE TITLE
Location data update

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4577]
**Location data update**

Hello! I have changed location data for this observation at iNaturalist. I would like to know if it will be updated here and when.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6b1a75604597ae921bd0e8fbc8e0bdb3:58a9be4fdeb94098c328282b0c343e0867acc69562aea9f116599c3a60d474aeb0d4e067445aa9e6db2cc16a1d367e58212838aaca49da070d6fd8002f396000de9d7fd41c8d2c36c091f9b172c8f15ab48611f6dc83c4ccb022851869b0c27b06c970fca815b87417ccf0e2ba057fecb2af4413ae4639ba51d4c85fef666b850ffb904db06b2ebb842b0067a0e873747c18c02f8578824c28c1be10fd792b32) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6b1a75604597ae921bd0e8fbc8e0bdb3:58a9be4fdeb94098c328282b0c343e0867acc69562aea9f116599c3a60d474aeb0d4e067445aa9e6db2cc16a1d367e58212838aaca49da070d6fd8002f396000de9d7fd41c8d2c36c091f9b172c8f15ab48611f6dc83c4ccb022851869b0c27b06c970fca815b87417ccf0e2ba057fecb2af4413ae4639ba51d4c85fef666b850ffb904db06b2ebb842b0067a0e873747c18c02f8578824c28c1be10fd792b32)
System: Mobile Safari 16.2.0 / iOS 16.2.0
Referer: https://www.gbif.org/occurrence/2898287349
Window size: width 375 - height 628
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-19T19:31:24.845Z',to:'2023-02-19T19:37:24.845Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-19T19:31:24.845Z',to:'2023-02-19T19:37:24.845Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

Node handles: @albenson-usgs @sformel-usgs

**Comment by sformel-usgs** [comment]
Apologies for the slow response. The inaturialist dataset is ingested weekly and the update should have come through with that event. However, it can take several days to update due to the high volume of records passing through the GBIF pipelines.  

I don't see evidence of the location update on iNaturalist.  Can you confirm for me that you're seeing the correct location on GBIF so I can close the issue?

**Comment by sformel-usgs** [comment]
@CecSve I think we can close this.
