### ISSUE TITLE
Clarify datacamp licence availability

### ISSUE THREAD

**Issue by nickynicolson** [gbif/portal-feedback#4578]
The page on [datacamp and the GBIF data use club](https://www.gbif.org/news/20UBPyN5zLlarJ4UZNmnSx/renewed-partnership-with-datacamp-extends-support-of-gbif-data-use-club) states:

> We accept applications from both organizations and individuals within GBIF participant countries and economies in [Latin America and the Caribbean](https://www.gbif.org/the-gbif-network/latin-america), [Africa](https://www.gbif.org/the-gbif-network/africa), [Asia](https://www.gbif.org/the-gbif-network/asia), [Northern Eurasia](https://www.gbif.org/programme/3ilFFs3JdY2SqmyCuac0uc/) and [the Pacific](https://www.gbif.org/article/y4yos8JwOVccTRuS1kYRD#pacific).

I read two criteria - (i) location in GBIF participant country and (ii) location in areas specified, but the wording does not explain if applications have meet *any* or *all* of these criteria. Could the page be clarified please?

**Comment by dnoesgaard** [comment]
Thanks for the feedback, @nickynicolson. I agree that this is ambiguous, and we will make sure it's updated.

For the record, applications are considered if the applicant organization is based in a country/economy that 1) is a GBIF participant and 2) is within one of the mentioned regions. Both are required.

 If you move through to the application form, I've narrowed it down to only include the eligible countries/economies:

- Argentina
- Armenia
- Benin
- Brazil
- Cambodia
- Cameroon
- Central African Republic
- Chile
- Chinese Taipei
- Colombia
- Costa Rica
- Ecuador
- Ghana
- Guatemala, Republic of
- Guinea
- Kenya
- Korea, Republic of
- Liberia
- Madagascar
- Malawi
- Mauritania
- Mexico
- Namibia
- Peru
- Sierra Leone
- South Africa
- South Sudan
- Suriname, Republic of
- Tajikistan
- Tanzania, United Republic of
- Togo
- Tonga, Kingdom of
- Uganda
- Uruguay
- Uzbekistan
- Viet Nam
- Zimbabwe
