### ISSUE TITLE
occurrenceIDs changing for a dataset

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#4585]
We've got a collections dataset [Invertebrate collections, UiB](https://www.gbif.org/dataset/ce697b4c-7803-47d8-81bd-5a172f4960b5) with dwc triplet style occurrenceIDs. This dataset also includes a subset of 470 records previously published here [artsprosjektet_53-14_copclad dataset from NBIC](https://www.gbif.org/dataset/339e9664-56f6-4174-a32e-c00ce3e5d60a), which have UUID style occurrenceIDs. 

In order to link the 470 records together, we published the UUID style occurrenceIDs from [artsprosjektet_53-14_copclad dataset from NBIC](https://www.gbif.org/dataset/339e9664-56f6-4174-a32e-c00ce3e5d60a) into the materialSampleID field in [Invertebrate collections, UiB](https://www.gbif.org/dataset/ce697b4c-7803-47d8-81bd-5a172f4960b5). We already have UUIDs in the materialSampleID field for all the other records. So that is the current set up. 

But we decided this was incorrect as it's confusing to link occurrenceIDs in one dataset to materialSampleIDs in another dataset, and we are going to move all the materialSampleID UUIDs in [Invertebrate collections, UiB](https://www.gbif.org/dataset/ce697b4c-7803-47d8-81bd-5a172f4960b5) to the occurrenceID field. So the 470 records in [Invertebrate collections, UiB](https://www.gbif.org/dataset/ce697b4c-7803-47d8-81bd-5a172f4960b5) will have the same occurrenceIDs as in [artsprosjektet_53-14_copclad dataset from NBIC](https://www.gbif.org/dataset/339e9664-56f6-4174-a32e-c00ce3e5d60a). And all occurrenceIDs in [Invertebrate collections, UiB](https://www.gbif.org/dataset/ce697b4c-7803-47d8-81bd-5a172f4960b5) will be UUID style ones, and we'll scrap the dwc triplet completely for all records. We won't publish anything in the materialSampleID field. 

So doing this is going to probably break the gbifKeys I think? What is the best way for us to proceed with this?

**Comment by rukayaj** [comment]
Here is a list of all the affected GBIF keys, the old occurrenceIDs and the new occurrenceIDs. 
[new-occurrenceids.csv](https://github.com/gbif/portal-feedback/files/10837561/new-occurrenceids.csv)

**Comment by ManonGros** [comment]
Hi @rukayaj 
If you can send to the GBIF helpdesk a CSV file with the old occurrenceID and new occurrenceID, we can do some magic on our side so when you publish the change, the occurrences will keep the same GBIFID and occurrence URLs.

**Comment by ManonGros** [comment]
Thanks @rukayaj ! I used the file to change the occurrenceIDs associated with those GBIFIDs on our side.
This means that you could now publish the data with the new occurrenceIDs and the occurrence will keep the same GBIFIDs and occurrence URLs.
Let us know if you encounter any issue or have any question.

**Comment by rukayaj** [comment]
Thanks @ManonGros ! We found a duplicate UUID, we're just trying to track down what caused it...

**Comment by rukayaj** [comment]
Now we have fixed the duplicate UUID, and I just republished the dataset.

**Comment by ManonGros** [comment]
Thanks Rukaya!
