### ISSUE TITLE
GBIF DwCA download will not validate in GBIF validator

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4587]
**GBIF DwCA download will not validate in GBIF validator**

Just downloaded some occurrences ( https://doi.org/10.15468/dl.tn3sr3). This file will not validate because there is no eml.xml file. If medadata.xml is renamed and meta.xml is edited accordingly, it will validate.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d013cb379a8f9b6172e0cb813f49b944:03cf33d17461f0120b809573ce893afc7eb5c14fd66b3371e55170b92620dde5fc263631c6eb5f27d4132ba4598d1c63eac82bfefa479c31a3b9fc6bce84663b0d52cc665d453083a42fbb68b332dfde8578def72a84d62d802629895b5fba1714837d30ddb564d808c38d41787ccd9986e6060b983e63d86c02e85b5bfc7bd7) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d013cb379a8f9b6172e0cb813f49b944:03cf33d17461f0120b809573ce893afc7eb5c14fd66b3371e55170b92620dde5fc263631c6eb5f27d4132ba4598d1c63eac82bfefa479c31a3b9fc6bce84663b0d52cc665d453083a42fbb68b332dfde8578def72a84d62d802629895b5fba1714837d30ddb564d808c38d41787ccd9986e6060b983e63d86c02e85b5bfc7bd7)
System: Firefox 110.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/tools/data-validator/467ccbc7-e2a9-4e40-87f6-69d3adf6daff
Window size: width 1280 - height 591
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-26T03:56:35.464Z',to:'2023-02-26T04:02:35.464Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-26T03:56:35.464Z',to:'2023-02-26T04:02:35.464Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by camwebb** [comment]
Submitted by me.

**Comment by muttcg** [comment]
Fixed
