### ISSUE TITLE
Problem linking CESP dataset to project page

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#4588]
We are possibly doing something wrong here, but we are struggling to link this Tajik dataset https://www.gbif.org/dataset/d4b0f477-0ddf-4c47-a1fe-a7ffed28788e to the project page https://www.gbif.org/project/CESP2022-001/kick-starting-the-biodiversity-data-publication-process-for-tajikistan#datasets 

We have the projectID in the metadata, which is published in the EML:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/9654499/221562323-4b410d06-4ae7-44b7-b0cd-64b824b33b4f.png">

**Comment by MortenHofft** [comment]
I've checked and it isn't a GBIF.org UI issue as far as I can see. The API response has no project information
https://api.gbif.org/v1/dataset/d4b0f477-0ddf-4c47-a1fe-a7ffed28788e

And I do not see it in the GBIF EML archive either
https://api.gbif.org/v1/dataset/d4b0f477-0ddf-4c47-a1fe-a7ffed28788e/document

@ManonGros doesn't the endpoint look wrong as well
https://registry.gbif.org/dataset/d4b0f477-0ddf-4c47-a1fe-a7ffed28788e/endpoint - there is no URLs, just a type

**Comment by ManonGros** [comment]
Yes the endpoint looks wrong. I don't think our system can crawl the archive at all here. Not sure how could that have happened. Any clue @rukayaj?
@mike-podolskiy90 do you think this could be an issue with the IPT?

**Comment by mike-podolskiy90** [comment]
Might be an IPT thing but I can't say right away

**Comment by rukayaj** [comment]
@ManonGros I am not sure what could be the cause... I have an IPT with an identical setup for Armenia and the dataset linking seemed to work there... 

https://www.gbif.org/project/CESP2021-010/mentoring-of-gbif-armenia-by-gbif-france#datasets
https://armenia.ipt.gbif.no/resource?r=scccwr_armenia
<img width="658" alt="image" src="https://user-images.githubusercontent.com/9654499/221807826-5821dfc5-bc36-4690-900f-c359157b0164.png">

**Comment by rukayaj** [comment]
I tried adding the same project identifier to another tajik dataset - https://tajik.ipt.gbif.no/resource?r=khatlon. That one doesn't seem to have worked either. Should I try add it to a random dataset from another IPT and see if it works from there? I'll be able to remove it again right?

**Comment by rukayaj** [comment]
Link to archive: https://tajik.ipt.gbif.no/archive.do?r=tnas-brahms

**Comment by MattBlissett** [comment]
@mike-podolskiy90 @marcos-lg, the IPT here seems to be creating empty endpoints.

I manually created the missing endpoint on [d4b0f477-0ddf-4c47-a1fe-a7ffed28788e](https://www.gbif.org/dataset/d4b0f477-0ddf-4c47-a1fe-a7ffed28788e) and it's working, but Rukaya's update to https://api.gbif.org/v1/dataset/4929d4f6-ea8a-40cc-ab3d-0e3a9da01a45 seems to have lost the endpoint.

**Comment by MattBlissett** [comment]
@rukayaj, an endpoint with a value of `eml.do?r=khatlon` was created, but it's not a valid URL and isn't shown in the API response:

```
─[ RECORD 1 ]─────────────────────────────────────
key         │ 835969
type        │ EML
url         │ eml.do?r=khatlon
description │ ␀
created_by  │ eb0b20ec-ca44-416c-a004-694461d425a6
modified_by │ eb0b20ec-ca44-416c-a004-694461d425a6
created     │ 2023-02-28 09:19:56.172556+00
modified    │ 2023-02-28 09:19:56.172556+00
```

This is the only endpoint like this, every other begins `http`. Could some sort of proxy or firewall be interfering with the IPT's communication to the GBIF Registry?

**Comment by rukayaj** [comment]
@MattBlissett I don't think so... I'm looking into it though. It's confusing that other IPTs with the same set up aren't experiencing this problem though.

**Comment by rukayaj** [comment]
Ok we updated the IPT and that seemed to fix it. Weird, but at least it's sorted now.
