### ISSUE TITLE
zip file is corrupted

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#459]
**zip file is corrupted**

I run a query on gbif web site (DOI10.15468/dl.wzviol) and the resulting zip file have a file with 0 kb. When I try to unzip the file (with 3 different softwares) I have the notice that the file is not a valid zip file or that the file is corrupted. What I need to do for unzip my file?

-----
fbitem-754c914deb62356d6e3f4ce3564309b9a21ee452
User provided contact info: luize.bg@gmail.com
System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/download/0007975-170826194755519
Window size: width 1536 - height 686
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-15T16:06:25.894Z',mode:absolute,to:'2017-09-15T16:12:25.894Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-15T16:06:25.894Z',mode:absolute,to:'2017-09-15T16:12:25.894Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
I suspect you tried to download the file before it was ready—there is generally a bit of a delay while it's processed and prepared. 

However, I can confirm that the download available at http://dx.doi.org/10.15468/dl.wzviol weighs in at 504MB and the .csv file opens.
