### ISSUE TITLE
The same logo is is displayed differently on GBIF

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4590]
**The same logo is is displayed differently on GBIF**

The same logo was upload in this other dataset: https://www.gbif.org/dataset/8347f6ba-f762-11e1-a439-00145eb45e9a and is displayed entirely.

However here (https://www.gbif.org/dataset/83459d16-f762-11e1-a439-00145eb45e9a), it is truncated.
Any idea why?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/0e31e7e27ac5773d59321fa5c6e91b4f:d59d802592cc70a92ce347908649b9ec9a5698e6c09541c8c13680fee452306e1ea9f3bbcafc993d529bf46c90e05ed35f3944fde05d2cafcf8cc3df1d5d3df05939fb692bf0a38d21cc942bb68bb7718db2218f8b894f2171fe3a0cf91a711d87f014539f0f29856e4ae44c503f0b82995cab14cf87166e59961f0df647902ab1594e8a903884055440696011f1bfc6) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0e31e7e27ac5773d59321fa5c6e91b4f:d59d802592cc70a92ce347908649b9ec9a5698e6c09541c8c13680fee452306e1ea9f3bbcafc993d529bf46c90e05ed35f3944fde05d2cafcf8cc3df1d5d3df05939fb692bf0a38d21cc942bb68bb7718db2218f8b894f2171fe3a0cf91a711d87f014539f0f29856e4ae44c503f0b82995cab14cf87166e59961f0df647902ab1594e8a903884055440696011f1bfc6)
System: Safari 16.1.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/83459d16-f762-11e1-a439-00145eb45e9a
Window size: width 1479 - height 859
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-28T13:48:06.280Z',to:'2023-02-28T13:54:06.280Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-28T13:48:06.280Z',to:'2023-02-28T13:54:06.280Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
I think they briefly had the bad logo on the IPT. I've flushed our cache.

**Comment by ManonGros** [comment]
Thanks Matt!
