### ISSUE TITLE
Datasets aren't appearing on the "DATASETS" tab of the project page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4591]
**Datasets aren&#39;t appearing on the &quot;DATASETS&quot; tab of the project page**

Those two datasets are linked to the project but don't show on the project page:
* https://www.gbif.org/dataset/ce66e0a8-36eb-4aa2-a5de-82ca60e20053
* https://www.gbif.org/dataset/d27090f0-8ea8-4a73-afdb-1f9ae18337da

<img width="1184" alt="Screenshot 2023-02-28 at 15 30 50" src="https://user-images.githubusercontent.com/7677271/221884096-2b04c0d1-085d-45b8-adcf-8f19b59eb8e2.png">

What could be happening?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/ed73d2eaf5c1210376b3718b56f94253:30f73340708df283fcf022b7c53e3b50f14ccf49e4cd9f18a55a9c6bf7cee9b1db8b85788f468c79ee1e06f7a91b89f137e1d07bfcea2ee275e07d4379aa8638953e28c20e0b9e51c65be6b626cb5659e0610ed0e44610c363e336430e5169dedede6cebfd400f04488f360e9013decf7efb1747b0ed6e3b1c25887271ffa3c4bc081712f84f3167641b606baf863301) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ed73d2eaf5c1210376b3718b56f94253:30f73340708df283fcf022b7c53e3b50f14ccf49e4cd9f18a55a9c6bf7cee9b1db8b85788f468c79ee1e06f7a91b89f137e1d07bfcea2ee275e07d4379aa8638953e28c20e0b9e51c65be6b626cb5659e0610ed0e44610c363e336430e5169dedede6cebfd400f04488f360e9013decf7efb1747b0ed6e3b1c25887271ffa3c4bc081712f84f3167641b606baf863301)
System: Safari 16.1.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/project/BID-CA2020-031-NAC/mobilizing-natural-history-collections-of-the-dominican-republic
Window size: width 1479 - height 859
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-28T14:25:30.795Z',to:'2023-02-28T14:31:30.795Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-28T14:25:30.795Z',to:'2023-02-28T14:31:30.795Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
The datasets are tagged correctly, but the index isn't correct: https://api.gbif.org/v1/dataset/search?projectId=BID-CA2020-031-NAC

@fmendezh, we used to have the reindexing job for datasets, but it's not deployed. Should we resurrect it?

**Comment by MortenHofft** [comment]
This has been fixed I see. And it was never a portal issue. Since almost all errors (in e.g. content or APIs or processing) eventually will show on gbif.org, it is not really practical to use the `portal` label simply because it is visible on the website.

But I see the challenge, it is also hard to know where the issue is and you need to get someones attention.

I think a good starting point for most of usm is ti as a minimum check if it is the same in the API. That will help decide the repo in most cases.
