### ISSUE TITLE
Simomesia Enderlein, 1912 should be Semomesia Westwood, 1851

### ISSUE THREAD

**Issue by jhnwllr** [gbif/portal-feedback#4596]
(from helpdesk) 

**Simomesia Enderlein, 1912** 
https://www.gbif.org/species/1678761

should probably be 

**Semomesia Westwood, 1851**
https://www.catalogueoflife.org/data/taxon/92MPK

**Comment by mdoering** [comment]
Rather unlikely. There are several species in IRMNG, the authorship is very different and its Diptera vs Lepidoptera.
https://www.irmng.org/aphia.php?p=taxdetails&id=1385126

Any evidence they are the same and just a misspelling?
