### ISSUE TITLE
Data validator is failing regardless of file type

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#4597]
[Data validator](https://www.gbif.org/tools/data-validator) is not working for me, it always gets stuck in the Indexing for previews step.

![image](https://user-images.githubusercontent.com/63795703/222814550-e60487e0-7017-4392-96db-5d74403da3b5.png)

I have tried several formats and all have the same problem:
![image](https://user-images.githubusercontent.com/63795703/222815251-776f1743-0f8e-48e6-ae5d-65d3b630da89.png)

I was wondering if maybe some change was made to the validator or if its a bug.

**Comment by muttcg** [comment]
Please try again, I have restarted the validaotr and tested csv versions, it worked
https://www.gbif.org/tools/data-validator/0860c012-1f87-47c4-aecb-b92173847051

**Comment by EstebanMH-SiB** [comment]
Look like it is working now, thank you very much!

**Comment by MattBlissett** [comment]
One of our Nagios monitors checks that there's been a successful GBIF download of some sort in the last hour or so.  On the rare occasion where there hasn't been any download (e.g. over holidays) it triggers one.

Should we make a similar monitor for validations?

**Comment by muttcg** [comment]
This is a Rabbit connection issue, so it's easier to track that particular issue in the log files
