### ISSUE TITLE
Search for occurrences without date isn't an option

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#46]
**Search for occurrences without date isn&#39;t an option**

total 703,245,140

592,565,753 occ [before 2020](https://demo.gbif.org/occurrence/search?year=*,2020)
(zero invalid and zero unlikely)

56,748,687 [recorded date invalid or unlikely or mismatch](https://demo.gbif.org/occurrence/search?issue=RECORDED_DATE_INVALID&amp;issue=RECORDED_DATE_UNLIKELY&amp;issue=RECORDED_DATE_MISMATCH)
(8.6 mil mismatch duplicates with _before 2020_ ignored)

592 mil + 56 mil is far from 703 mil. This I assume is the occurrences without date at all. But wouldn&#39;t it be practical to have them searchable as well?

I guess one could argue, that if you want a date you set a filter. And if you are a publisher you can look at your own data. Whereas the other issues has to do with our processing. But then again we add no_taxon_match when no taxon is provided. and flag occurrences without coordinates. And our issue filters are targeting the publishers in the first place.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
Reported by: @MortenHofft
System: Chrome 55.0.2883 / Mac OS X 10.10.5
Referer: https://demo.gbif.org/occurrence/search?issue=RECORDED_DATE_INVALID&amp;issue=RECORDED_DATE_UNLIKELY&amp;issue=RECORDED_DATE_MISMATCH
Window size: width 1440 - height 776
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-22T11:14:18.152Z',mode:absolute,to:'2017-01-22T11:20:18.152Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-22T11:14:18.152Z',mode:absolute,to:'2017-01-22T11:20:18.152Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
Moved to https://github.com/gbif/gbif-api/issues/9
