### ISSUE TITLE
Misses details on SIMPLE_CSV downloads

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#460]
**Misses details on SIMPLE_CSV downloads**

The download format is not mentioned and examples of what to POST are not included.  Suggest this be enriched with documentation making it very easy to use - perhaps examples with CURL showing the AUTH too.

-----
fbitem-b1018fb447ec8b1aa84ee420b36825314783d5a9
User provided contact info: @timrobertson100
System: Chrome 60.0.3112 / Mac OS X 10.11.5
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1440 - height 755
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-16T07:25:47.140Z',mode:absolute,to:'2017-09-16T07:31:47.140Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-16T07:25:47.140Z',mode:absolute,to:'2017-09-16T07:31:47.140Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
There are partial examples of what to post under 'Predicates', but not a full example.

A working example using Curl:

Put this in a file called query.json:

```
{
  "creator": "MattBlissett",
  "notification_address": [
    "mblissett@gbif.org"
  ],
  "format": "SIMPLE_CSV",
  "predicate": {
    "type": "and",
    "predicates": [
      {
        "type": "equals",
        "key": "DATASET_KEY",
        "value": "cd6e21c8-9e8a-493a-8a76-fbf7862069e5"
      },
      {
        "type": "equals",
        "key": "COUNTRY",
        "value": "KW"
      }
    ]
  }
}
```

Then issue:
```
curl --include --user MattBlissett:PASSWORD --header "Content-Type: application/json" --data @query.json https://api.gbif-uat.org/v1/occurrence/download/request
```

A download id is returned. This gives the status, and once ready, the download link:
```
curl -Ss https://api.gbif-uat.org/v1/occurrence/download/0000022-170829143010713 | jq .
```
(`| jq .` is optional, but formats the JSON nicely.)

**Comment by MortenHofft** [comment]
Thank you for the clear example Matt. I have added it to the documentation (without your email). Some more details and styling would be good, but have been postponed to a general brush up of the developer pages.
