### ISSUE TITLE
Huge data overlapp

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4605]
**Huge data overlapp**

The species "Muntiacus reveesi" has a huge duplication in occurrences. I downloaded the whole data set and before dropping such with NA coordinates I had 98,803 entries. After dropping NA coordinates it were 98,778. Then I searched for duplicated coordinate values and removed them. The "end dataset" contained 14,233 occurrences. So there is a really huge duplication of occurrences ongoing that might can be removed from the database.

Best wishes
Louis-Marvin Sander

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/eab6e11a0f28f6ef878edf26cbcfd9eb:f039a1974ce88eaf91d7c82b3ea3e3797f0e602fcf9a106cba714703dbc80873fe3f3c3f0e663b41e7e561b2e30fb095a8d8d72c21ccd0f99bb59d4c26fe423ffd9450f4441410cf8f3b4e1818a090355d3807fae5d46a69591e318405cfff00) - [Send email](https://www.gbif.org/api/feedback/user/mailto/eab6e11a0f28f6ef878edf26cbcfd9eb:f039a1974ce88eaf91d7c82b3ea3e3797f0e602fcf9a106cba714703dbc80873fe3f3c3f0e663b41e7e561b2e30fb095a8d8d72c21ccd0f99bb59d4c26fe423ffd9450f4441410cf8f3b4e1818a090355d3807fae5d46a69591e318405cfff00)
System: Opera 95.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?q=Muntiacus%20reveesi
Window size: width 1879 - height 931
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-12T13:06:26.470Z',to:'2023-03-12T13:12:26.470Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-12T13:06:26.470Z',to:'2023-03-12T13:12:26.470Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Would it be possible to give us a bit more details on how you identified the duplicates and in which datasets those duplicates are?

76,586 of the occurrences of Muntiacus reevesi subsp. micrurus (Sclater, 1875) associated with coordinates come from the same dataset: https://doi.org/10.15468/xluhdx (Abundance and distribution of medium- to large-sized mammals, usage of wildlife in traditional ceremonies and contemporary hunting territories of the aboriginal tribes in Alishan Township, Chiayi County).
As far as I can tell, there is no occurrence duplication. In the dataset description, it is mentioned that a lot of the data come from camera traps. In this set up, is possible that the same animals would be captured several times.

Understanding how you identified the duplicates would help us forward the feedback to the correct person. 

> contacted by email

**Comment by ManonGros** [comment]
The user replied and gave some example. After checking the data for those coordinates and it seems like most of them correspond to different days (the cameras were set up from January to September). For example, for one set of coordinates, there is an average of 31 observations per date (not all of them from the same species). This is a lot but not unlikely if the cameras are set up where the animals live (it is a shame the data providers didn’t share the time of the day for those observations).

In this particular instance, the occurrences aren’t technically duplicates but assuming they correspond to different animals would be misleading.
