### ISSUE TITLE
Two incertae sedis records need to be edited 

### ISSUE THREAD

**Issue by bdagley** [gbif/portal-feedback#4606]
The parent taxon needs to be fixed/assigned for the two records shown here (https://www.gbif.org/species/8453930). These species currently only make up one page which is disconnected from the GBIF taxonomic framework. The parent taxon these records should be edited to have is here (https://www.gbif.org/species/4240). Although, the two records seem to currently be identified only as that taxon (not more specifically), so if they move they should be in the gallery in the above link. Or, if they could somehow be more precisely categorized to genus, I think the wasp on the left is in genus Afreumenes (please verify vs. Delta) and the one on the right is Delta emarginatum.

**Comment by bdagley** [comment]
Thanks for adding the backbone label, @ManonGros. I have a new free GitHub account and to clarify, am I also able to add labels like that or is it only possible with a paid or other kind of account?

**Comment by ManonGros** [comment]
Thank you @bdagley for your question. 
People who can add labels were granted some permissions for our repository. But we only give this type of permissions to GBIF staff and contractors.
