### ISSUE TITLE
Identification incorrecte

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#461]
**Identification incorrecte**

La plante présentée ici ne correspond pas à liparis sambiranoensis, mais correspond à un oeceoclades. Cet oeceoclades de Mayotte est encore non identifié (oeceoclades sp.).

-----
fbitem-occurrence438629251
User provided contact info: etienne.vennetier@sfr.fr
System: Chrome 61.0.3163 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/438629251
Window size: width 1256 - height 676
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-16T14:05:28.283Z',mode:absolute,to:'2017-09-16T14:11:28.283Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-16T14:05:28.283Z',mode:absolute,to:'2017-09-16T14:11:28.283Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: b5cdf794-8fa4-4a85-8b26-755d087bf531
publishingOrgKey: 2cd829bb-b713-433d-99cf-64bef11e5b3e

**Comment by rdmpage** [comment]
Incorrect identification

The plant presented here does not correspond to Liparis sambiranoensis, but corresponds to a oeceoclades. This oeceoclades of Mayotte is still unidentified (oeceoclades sp.).

**Comment by ManonGros** [comment]
Issue is being dealt with by email.

**Comment by ManonGros** [comment]
The publishers have updated the record.
