### ISSUE TITLE
Maps not showing for 'Data about' on country pages!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4613]
**Maps not showing for &#39;Data about&#39; on country pages!**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/338d971127b3b75e5d99f116dcbca4aa:77f568a8d2ceb7ef672ad237ba23258ddb04406ce176e96b427fce04b46553233eb8fda24ea45e4399435106086ed9aaa025d3a59e21ae3255920151e1e4a85b0fef240c046fd14c72b17dffed7ba16ead188f60410c7c51ec9760a59d505b04172d4f5ac4017873b8d17ea2e1e784c5f28ffb912b7d128f4090df6cde5e93d4) - [Send email](https://www.gbif.org/api/feedback/user/mailto/338d971127b3b75e5d99f116dcbca4aa:77f568a8d2ceb7ef672ad237ba23258ddb04406ce176e96b427fce04b46553233eb8fda24ea45e4399435106086ed9aaa025d3a59e21ae3255920151e1e4a85b0fef240c046fd14c72b17dffed7ba16ead188f60410c7c51ec9760a59d505b04172d4f5ac4017873b8d17ea2e1e784c5f28ffb912b7d128f4090df6cde5e93d4)
System: Chrome 111.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/country/CN/summary
Window size: width 2160 - height 1029
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-18T03:53:59.873Z',to:'2023-03-18T03:59:59.873Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-18T03:53:59.873Z',to:'2023-03-18T03:59:59.873Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Indeed. That is because there is a [negative amount of records according to the API response](https://github.com/gbif/maps/issues/70). We only show the map if it is above 0 records with coordinates.

But the test in the frontend is also wrong. It was testing against everything not just the country. So fixing the frontend will not trigger the API bug.

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/d913b50923329ace72641ca73a4fa4775d904d3a
