### ISSUE TITLE
Unable to conduct structured search for Actinopterygii.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4615]
**Unable to conduct structured search for Actinopterygii.**

Hi, how can I do a structured search for Actinopterygii from Chile and Argentina? Calss Actinopterygii has been removed from the search options, and when I search using Actinopterygii as a keyword, it works nicely except that the data cannot be downloaded. There is a message saying that downloads are available only if the filter was conducted with a structured search, not using any free text. This puts me in the situation of either downloading each fish species one by one, or downloading all Chordata records which is huge. Thanks,

C

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/25cc3a5e0ce4d0bd851fe1ca46daf326:f87a720a3304f5203cd6bd32876e07f5c2ac5b7ac2bf7efa13f85e8f4baac11425c4bae55221999450e8d4355d5a1d08af1091a1f80305f26dffdb51cba98c5da8df8387e013eccdf796c145774cfe62065135996838b30e54e8648afaf2477180b44af233331be7477468785360f9ff5ff5c55c8ebbaee185eb6b39882740b36105e9bd166377941136acbddf67fbe1) - [Send email](https://www.gbif.org/api/feedback/user/mailto/25cc3a5e0ce4d0bd851fe1ca46daf326:f87a720a3304f5203cd6bd32876e07f5c2ac5b7ac2bf7efa13f85e8f4baac11425c4bae55221999450e8d4355d5a1d08af1091a1f80305f26dffdb51cba98c5da8df8387e013eccdf796c145774cfe62065135996838b30e54e8648afaf2477180b44af233331be7477468785360f9ff5ff5c55c8ebbaee185eb6b39882740b36105e9bd166377941136acbddf67fbe1)
System: Chrome 109.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=Actinopterygii
Window size: width 1707 - height 844
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-20T00:01:50.766Z',to:'2023-03-20T00:07:50.766Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-20T00:01:50.766Z',to:'2023-03-20T00:07:50.766Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
As you noted Actinopterygii is no longer a class in the GBIF backbone taxonomy (see [this GitHub issue](https://github.com/gbif/portal-feedback/issues/4507) for more information).
This means that you will have to select all the orders that were previously under the Actinopterygii class. I have made that selection for you (and added the country filter for Argentina and Chile):
https://www.gbif.org/occurrence/search?country=CL&country=AR&taxon_key=1103&taxon_key=1104&taxon_key=494&taxon_key=495&taxon_key=1105&taxon_key=496&taxon_key=497&taxon_key=1106&taxon_key=498&taxon_key=499&taxon_key=1107&taxon_key=537&taxon_key=538&taxon_key=1153&taxon_key=547&taxon_key=1162&taxon_key=548&taxon_key=549&taxon_key=550&taxon_key=1163&taxon_key=1164&taxon_key=1165&taxon_key=1166&taxon_key=1167&taxon_key=1305&taxon_key=1067&taxon_key=1306&taxon_key=1307&taxon_key=1308&taxon_key=1068&taxon_key=1069&taxon_key=587&taxon_key=1310&taxon_key=588&taxon_key=589&taxon_key=1311&taxon_key=1312&taxon_key=1313&taxon_key=590&taxon_key=708&taxon_key=890&taxon_key=774&taxon_key=889&taxon_key=773&taxon_key=772&taxon_key=888&occurrence_status=present

> Replied by email
