### ISSUE TITLE
Incorrect country or area for occurrence data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4616]
**Incorrect country or area for occurrence data**

From what I can identify, all of the following records fall within the Phillipines VLIZ marine  and GDAM regions and yet are labelled as coming from China https://www.gbif.org/occurrence/search?dataset_key=4515e736-fa02-44ee-9808-bf89445104fe&geometry=POLYGON((112.58491%203.14034,128.62075%203.14034,128.62075%2014.09816,112.58491%2014.09816,112.58491%203.14034)).  I know that this is a disputed territory i.e. claimed by China but it clearly falls within what we recognise as Filipino territory

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0f09c1cc520388119fa6a220404d6d20:073392ef60cf50077d98d4f21a5e943662f77cae2582e7f145641fc87fc3ae696d2ee7d4cb5b5f5630f21dd39916e8d921968fcd8acdbb577b762e56668f6c25fc2a4822cc10e08ed48529a4690d6ab62ebfbabdf9b53af8acd3592e134530351dd983231eeb87f343b766b400ba97b78de2c61ee63520e7f2e6c9c7d3f444dd29fff82bc335917ece8f49a31e18dd52) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0f09c1cc520388119fa6a220404d6d20:073392ef60cf50077d98d4f21a5e943662f77cae2582e7f145641fc87fc3ae696d2ee7d4cb5b5f5630f21dd39916e8d921968fcd8acdbb577b762e56668f6c25fc2a4822cc10e08ed48529a4690d6ab62ebfbabdf9b53af8acd3592e134530351dd983231eeb87f343b766b400ba97b78de2c61ee63520e7f2e6c9c7d3f444dd29fff82bc335917ece8f49a31e18dd52)
System: Chrome 111.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?dataset_key=4515e736-fa02-44ee-9808-bf89445104fe&geometry=POLYGON((112.58491%203.14034,128.62075%203.14034,128.62075%2014.09816,112.58491%2014.09816,112.58491%203.14034))
Window size: width 1260 - height 492
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-20T14:40:06.028Z',to:'2023-03-20T14:46:06.028Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-20T14:40:06.028Z',to:'2023-03-20T14:46:06.028Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
All those records have the COUNTRY_COORDINATE_MISMATCH issue applied.

We don't change the country field where it is provided but differs from our own interpretation.

**Comment by MattBlissett** [comment]
CC @andrewrodrigues
