### ISSUE TITLE
Changes in names from NMV to ALA to GBIF

### ISSUE THREAD

**Issue by rdmpage** [gbif/portal-feedback#462]
Bob Mesibov has a guest post on iPhylo http://iphylo.blogspot.co.uk/2017/09/guest-post-our-taxonomy-is-not-your.html In it he shows that of some 85,000 occurrences in a sample of NMV (Museums Victoria) data, 1 in 5 ends up with a different name in GBIF(!). He gives one example in detail, which I think is another case of basionym mismatching (closely related species names with same author and year being erroneously linked). We keep hitting this problem, and I think it's partly because we are relying on string matching names instead of matching identifiers. In this example, the Australian Faunal Directory (AFD) actually has enough information and identifiers to express the correct relationships between these names, we should attempt to use this info when it's available.

**Comment by thomasstjerne** [comment]
Transferred to https://github.com/gbif/checklistbank/issues/41

**Comment by thomasstjerne** [comment]
Possible dublicate of https://github.com/gbif/checklistbank/issues/35
