### ISSUE TITLE
Actinocyclus octonarius is a fossil protist, not a mollusc

### ISSUE THREAD

**Issue by aaltenburger2** [gbif/portal-feedback#4620]
Hi, 

a student of mine stumbled over _Actinocyclus octonarius_ Ehrenberg, 1837 classified as a mollusc https://www.gbif.org/species/9762031. This species is a fossil protist. The same genus name is used for nudibranchs as well. Apparently described by the same author, but a different year. 

[WoRMS - World Register of Marine Species - Actinocyclus octonarius Ehrenberg, 1837](https://www.marinespecies.org/aphia.php?p=taxdetails&id=149164) a fossil protist
and 
[WoRMS - World Register of Marine Species - Actinocyclus verrucosus Ehrenberg, 1831](https://www.marinespecies.org/aphia.php?p=taxdetails&id=527814) a nudibranch

Could you please update the GBIF taxonomy.

Best regards,

Andreas

**Comment by mdoering** [comment]
This lapsus came from WoRMS at the time we build the backbone and seems to be fixed in WoRMS now, so it should appear correctly in our next release

**Comment by aaltenburger2** [comment]
Thank you!
________________________________
