### ISSUE TITLE
Can we remove the HTML from the title?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4623]
**Can we remove the HTML from the title?**

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/736ad1c38b31372237986ba52cc7dd80:c0e3235ecbaa475ee62e9c8dea591f1d04a646634f7b71ee8a9e442e0dbe266b3a0f49f3645b229f72d813c4bd48b4f0feaf72127076bcd3387604d1f9cf4f1fe5bc030dd6346c8bf3ccb24642b4b3881aa06412b65106ab1eec3da9e183c4080a50c48fc8d8c35d89a5e44f4d1b387461ff56d98f6393bbd2559802b8d5da31f1aba78fff47fd055c9a5a23a7bfa8a16a7f41e2ca6f2e46aba5175b8120d7bd) - [Send email](https://www.gbif.org/api/feedback/user/mailto/736ad1c38b31372237986ba52cc7dd80:c0e3235ecbaa475ee62e9c8dea591f1d04a646634f7b71ee8a9e442e0dbe266b3a0f49f3645b229f72d813c4bd48b4f0feaf72127076bcd3387604d1f9cf4f1fe5bc030dd6346c8bf3ccb24642b4b3881aa06412b65106ab1eec3da9e183c4080a50c48fc8d8c35d89a5e44f4d1b387461ff56d98f6393bbd2559802b8d5da31f1aba78fff47fd055c9a5a23a7bfa8a16a7f41e2ca6f2e46aba5175b8120d7bd)
System: Chrome 111.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/c8670273-a22c-4b4a-972d-38a43cd66f86
Window size: width 1585 - height 861
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-23T03:06:05.112Z',to:'2023-03-23T03:12:05.112Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-23T03:06:05.112Z',to:'2023-03-23T03:12:05.112Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Issue forwarded to PLAZI

**Comment by ManonGros** [comment]
PLAZI fixed the issue
