### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4624]
**Coordinates**

Coordinates of this record (https://www.gbif.org/occurrence/2427475842) are written on the label of the specimen.

-----

Github user: @lmoliner
User: [See in registry](https://www.gbif.org/api/feedback/user/ebd713bdf6d688dba86cbccbf50c5d0a:881dd36b5f4aede4b5f50802c97059cb8ef3287c0505726ba4a56b289e72ce1c3bf5fb38a61971dfd20360e85e75bfa41f3d1a62b19df33ffd1b265845a591174e5b912bf8a39acc09f58807d218b15a550c5a53b8c563f5eab8d131ccdab3d1d8f3ba65fc2a8e2c03c23c9fd052a085b89ef6bba06e2f9a853ecb84dd683074f2d9e66bf7490896c64823dce3a400c409e654beaf09822b4b8379df858b0e16) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ebd713bdf6d688dba86cbccbf50c5d0a:881dd36b5f4aede4b5f50802c97059cb8ef3287c0505726ba4a56b289e72ce1c3bf5fb38a61971dfd20360e85e75bfa41f3d1a62b19df33ffd1b265845a591174e5b912bf8a39acc09f58807d218b15a550c5a53b8c563f5eab8d131ccdab3d1d8f3ba65fc2a8e2c03c23c9fd052a085b89ef6bba06e2f9a853ecb84dd683074f2d9e66bf7490896c64823dce3a400c409e654beaf09822b4b8379df858b0e16)
System: Opera 95.0.0 / Windows 8.1.0.0
Referer: https://www.gbif.org/occurrence/2427475842
Window size: width 1600 - height 727
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-23T09:47:48.522Z',to:'2023-03-23T09:53:48.522Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-23T09:47:48.522Z',to:'2023-03-23T09:53:48.522Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7bd65a7a-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 90fd6680-349f-11d8-aa2d-b8a03c50a862

Node handles: @albenson-usgs @sformel-usgs

**Comment by sformel-usgs** [comment]
I see that there are many other occurrences (both old and new) from this dataset with the same issue. I'm guessing that, like a lot of collections, they are probably developing methods to get more metadata out of your labels with the assistance of machines.  Writing Heather Stimmel and Chuck Miller to see if they have plans to harvest more metadata from label.

**Comment by sformel-usgs** [comment]
Received a prompt response from Heather:

>We are working on way to better capture label data using AI.  In the meantime though, we don’t mind hearing about issues like this because they can be corrected pretty easily (the one listed in your email below has already been corrected in Tropicos, not sure when GBIF will pick up the change).  You mentioned others.  Do you happen to have a list of them?    

After some more digging, I realized I don't have a brilliant way to identify occurrences that might have coordinates on the specimen label.  Here is a GBIF query for occurrences from the MO botanical garden that don't have coordinates, but do have a related image file:

https://www.gbif.org/occurrence/search?dataset_key=7bd65a7a-f762-11e1-a439-00145eb45e9a&has_coordinate=false&media_type=StillImage&advanced=1

Many don't seem to have coordinates on the label. For example, those that were collected at the MO garden.  But I did find a few, without digging too deep:

https://www.gbif.org/occurrence/4419908400
https://www.gbif.org/occurrence/4401856378

So maybe I just got lucky in finding them, and for now Heather is working on those two, at least.  I'll keep it in my brain and see if I can come up with a way to filter it down a little better. @Mesibov, do you have any good suggestions?

**Comment by Mesibov** [comment]
@sformel-usgs, no suggestions, unfortunately. I've only checked labels on images (where these exist) in cases where there was something odd about the details in the text record, not just "no coordinates".

**Comment by sformel-usgs** [comment]
This ended up being an excellent interaction with the MO botanical garden folks.  Heather told me we are always welcome to send problems with the data to her, or can send reports to [TropicosFeedback@mobot.org](mailto:TropicosFeedback@mobot.org).

I followed up by pointing out some flags that might be low hanging fruit to fix:

> Elevation Min and Max Swapped (2,933 occurrences)
> [https://www.gbif.org/occurrence/search?dataset_key=7bd65a7a-f762-11e1-a439-00145eb45e9a&issue=ELEVATION_MIN_MAX_SWAPPED](https://www.gbif.org/occurrence/search?dataset_key=7bd65a7a-f762-11e1-a439-00145eb45e9a&issue=ELEVATION_MIN_MAX_SWAPPED)
> 
> Likely an incorrect negative latitude (1,950 occurrences)
> [https://www.gbif.org/occurrence/search?dataset_key=7bd65a7a-f762-11e1-a439-00145eb45e9a&issue=PRESUMED_NEGATED_LATITUDE](https://www.gbif.org/occurrence/search?dataset_key=7bd65a7a-f762-11e1-a439-00145eb45e9a&issue=PRESUMED_NEGATED_LATITUDE)
> 
> Recorded data invalid (745 occurrences, e.g. a year made of a single digit)
> [https://www.gbif.org/occurrence/search?dataset_key=7bd65a7a-f762-11e1-a439-00145eb45e9a&issue=RECORDED_DATE_INVALID](https://www.gbif.org/occurrence/search?dataset_key=7bd65a7a-f762-11e1-a439-00145eb45e9a&issue=RECORDED_DATE_INVALID)
> 

From Heather's response, it sounds like the GBIF flags are not something that is already integrated into their work flows, but that they were happy I pointed them out and will start tackling these particular ones.

**Comment by sformel-usgs** [comment]
@ManonGros I believe this can be closed.  It did make me think of two suggestions to improve the response to this sort of flagged occurrence.  Let me know if you think I should submit these suggestions as an issue elswhere.

1. Could dataset managers opt in with an email to notify, when a github issue related to their data is pulled?  I don't know how successful it would be, but for MO garden issues going forward, Heather gave us a clear contact, and they do not seem interested in joining github.

2. Could we generate and email annual "health" reports for publishers or dataset POCs, reminding them of the types and quantities of issues that are being flagged in their data?

**Comment by sformel-usgs** [comment]
So, this issue can be closed, I'll submit the first idea as an issue in this repo. I'll see if I can develop a short report template for the second and test it out with GBIF-US publishers.
