### ISSUE TITLE
Myzus persicae misplaced in latest GBIF taxonomic backbone.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4627]
**Myzus persicae misplaced in latest GBIF taxonomic backbone.**

It seems that there have been some changes in the Aphididae taxonomy in GBIF in the latest update, but some errors remain. For example: Myzus persicae, a widely distributed aphid (see: https://www.cabidigitallibrary.org/doi/10.1079/cabicompendium.35642 and http://aphid.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1170639 and 
https://www.catalogueoflife.org/data/taxon/45J3R) is currently not an accepted species name in GBIF nor does it match to a suitable synonym pair.

In the previous GBIF backbone there were also Aphididae issues (see GBIF issue gbif/backbone-feedback#257), but the synonym pairings were different.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/26cd3415d251b0677c5fbfe70eacebf7:eea538c3f71edcc3198c1a11ab69b49ad0e5094277ec8d818a8129da932f9049455db19ab7cd04bac27381a9d2bfd44deafc5e5ac5b1c5955f2856cdb7d7f341f6b2a657d702c76d50bfb7efd79642b977b7abc7697f317ac3f9caab7057d3a386df75cc42579c7486ea45e7fed73901) - [Send email](https://www.gbif.org/api/feedback/user/mailto/26cd3415d251b0677c5fbfe70eacebf7:eea538c3f71edcc3198c1a11ab69b49ad0e5094277ec8d818a8129da932f9049455db19ab7cd04bac27381a9d2bfd44deafc5e5ac5b1c5955f2856cdb7d7f341f6b2a657d702c76d50bfb7efd79642b977b7abc7697f317ac3f9caab7057d3a386df75cc42579c7486ea45e7fed73901)
System: Chrome 111.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-24T04:31:20.456Z',to:'2023-03-24T04:37:20.456Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-24T04:31:20.456Z',to:'2023-03-24T04:37:20.456Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
As it is accepted in COL now it will be accepted in the next backbone
