### ISSUE TITLE
images not resolving

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#463]
**images not resolving**

Images are not available. The hosting server keeps hanging

https://www.gbif.org/occurrence/gallery?dataset_key=1162234d-4e06-4d63-8a49-034184a38c7e

single img: http://images.invcol.uprm.edu/?image=Coleoptera/Elateridae/Glyphonyx-sp1-dorsal&w=10000

-----
fbitem-dataset1162234d-4e06-4d63-8a49-034184a38c7e
User provided contact info: mortenhofft
System: Chrome 60.0.3112 / Mac OS X 10.11.6
Referer: https://www.gbif.org/dataset/1162234d-4e06-4d63-8a49-034184a38c7e
Window size: width 2133 - height 1195
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-19T11:53:56.542Z',mode:absolute,to:'2017-09-19T11:59:56.542Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-19T11:53:56.542Z',mode:absolute,to:'2017-09-19T11:59:56.542Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ManonGros** [comment]
The publishers have been contacted.

**Comment by ManonGros** [comment]
The data we republished through Symbiota SCAN (see new dataset [here](https://www.gbif.org/dataset/43e54c60-d6e0-41df-80a3-ca9487a3342a)). They will be able to upload images more easily.
