### ISSUE TITLE
GBIF ID 215793779 for Margaritifera falcata is in the wrong location. There are several Polecat Creeks in WY. The one this record belongs to says it should be in Teton County, but the coordinates are for a creek in another county. Have a look at these coordinates:44.10444444440, -110.68305555600

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4635]
**GBIF ID 215793779 for Margaritifera falcata is in the wrong location. There are several Polecat Creeks in WY. The one this record belongs to says it should be in Teton County, but the coordinates are for a creek in another county. Have a look at these coordinates:44.10444444440, -110.68305555600**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3ee8d5065d91142d7626bd20fdeac2b7:74876f95667da3738ccd9b061c656d9738afdcf18adb2c0ed26816194d69bacf19af5116f24387a2e08d1ca4b95e69ab1425ad9167fb083594ef110978963b7ed8d3e73170f826d6d0d16fcb9bba723cd14ae8ab680023733681b00d03fe7386) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3ee8d5065d91142d7626bd20fdeac2b7:74876f95667da3738ccd9b061c656d9738afdcf18adb2c0ed26816194d69bacf19af5116f24387a2e08d1ca4b95e69ab1425ad9167fb083594ef110978963b7ed8d3e73170f826d6d0d16fcb9bba723cd14ae8ab680023733681b00d03fe7386)
System: Firefox 111.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/data-quality-requirements
Window size: width 1536 - height 739
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-24T16:57:18.485Z',to:'2023-03-24T17:03:18.485Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-24T16:57:18.485Z',to:'2023-03-24T17:03:18.485Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
The coordinate appear correct to me.
