### ISSUE TITLE
change my password

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4637]
**change my password**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/07b6b263bda784d73cbaea47cc4bcb61:5a60ffb7a1d0af533cebfcdca0100c2f0ee7a8ab765ad75f652ae671bca08b5328ab7b048f80e9a7d5a770562566be79c605fe7940c64112d27e05f4f1e6f3c3573b54dfad9adfcd13ccf89c8cdf7cca599d4e31446d684f10b7fb1d534947c2d098d0da0e24dfd9c7586e045c234ee1d9b50612f7d8177a227698afbb619480c091f35e137e62a2e2f2650ee3bc533a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/07b6b263bda784d73cbaea47cc4bcb61:5a60ffb7a1d0af533cebfcdca0100c2f0ee7a8ab765ad75f652ae671bca08b5328ab7b048f80e9a7d5a770562566be79c605fe7940c64112d27e05f4f1e6f3c3573b54dfad9adfcd13ccf89c8cdf7cca599d4e31446d684f10b7fb1d534947c2d098d0da0e24dfd9c7586e045c234ee1d9b50612f7d8177a227698afbb619480c091f35e137e62a2e2f2650ee3bc533a)
System: Firefox 110.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/faq?q=password
Window size: width 1440 - height 790
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-25T23:00:28.603Z',to:'2023-03-25T23:06:28.603Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-25T23:00:28.603Z',to:'2023-03-25T23:06:28.603Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

You have two possible ways to change the password for your GBIF accounts.

- You can do it on your user profile: https://www.gbif.org/user/profile by clicking on the “start editing” toggle button.

- You can log out and click on the “Forgot your password?” link.
