### ISSUE TITLE
AnnoSys records are not showing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#464]
**AnnoSys records are not showing**

There are [2 annotations for this record](http://www-old.gbif.org/occurrence/144881791) which should be visible on this page.

-----
fbitem-occurrence144881791
User provided contact info: timrobertson100
System: Chrome 60.0.3112 / Mac OS X 10.11.5
Referer: https://www.gbif.org/occurrence/144881791
Window size: width 1878 - height 1055
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-19T12:59:56.810Z',mode:absolute,to:'2017-09-19T13:05:56.810Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-19T12:59:56.810Z',mode:absolute,to:'2017-09-19T13:05:56.810Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 85714c48-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 57254bd0-8256-11d8-b7ed-b8a03c50a862

**Comment by MortenHofft** [comment]
timrobertson100 suggests adding AnnoSys as a part of the count on the occurrence and list the annotation along side the Github comments

**Comment by MortenHofft** [comment]
Should we make a general recommendation on publishing feedback urls on occurrences? possibly also a suggested format for getting number of comments. This way we could make it a generic thing instead of an Annosys specific implementation.

So that an occurrence could look something along these lines?
```
...
feedbackUrl: "https://mySite.org/occurrence/1234/feedback.html", //html to redirect to
commentsUrl: "http://mySite.org/occurrence/1234/comments.json" //for machines. Will return e.g. {count: 11, comments: [{title, summary, date}]}
```

Either way, what is the priority of this? Should it be a part of the 3 month goals?

**Comment by MortenHofft** [comment]
it now shows on all occurrences from [Botanic Garden and Botanical Museum Berlin-Dahlem](https://www.gbif.org/publisher/57254bd0-8256-11d8-b7ed-b8a03c50a862)

will be in prod in the new year

**Comment by MortenHofft** [comment]
Just remembering that it isn't clear how to link too all annotations for an occurrence. And unclear how to limit the amount of annotations. Currently we cap to five despite the response. And link to the annotation page if there are more. Perhaps I overlooked it in their docs. Else we can write and ask them.

**Comment by MortenHofft** [comment]
docs here http://wiki.bgbm.org/annosys/index.php?title=TechnicalDocumentation

**Comment by MortenHofft** [comment]
From the AnnoSys team:

1. There is no way to limit the amount of annotations when asking for them. So there might be thousands. That is no limit. All annotations will be returned. No paging in the API.

2. There is currently no way to link to all annotations for a record. I'm not sure it makes sense to show any annotations until such a functionality is in place in AnnoSys? Perhaps we should remove the functionality again. On the other hand there isn't many annotations so it might never be an issue.

**Comment by MortenHofft** [comment]
I'm closing this issue despite it being a fragile implementation (see issues mentioned above). We are intersted in the integration and there are so few annotations in AnnoSys that above issues isn't a problem yet and might never be.
