### ISSUE TITLE
taxon match none isn't a warning

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#465]
**taxon match none isn&#39;t a warning**

taxon match none used to be marked as a critical red error. it still is in the download report

-----
fbitem-occurrence1058406100
User provided contact info: mortenhofft
System: Chrome 60.0.3112 / Mac OS X 10.11.6
Referer: https://www.gbif.org/occurrence/1058406100
Window size: width 1600 - height 866
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-19T13:50:26.998Z',mode:absolute,to:'2017-09-19T13:56:26.998Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-19T13:50:26.998Z',mode:absolute,to:'2017-09-19T13:56:26.998Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 9d8ff248-3f6d-4180-a7f5-3570c489cf72
publishingOrgKey: d1146fd8-35d2-4264-a569-8f88cc29d0c8

**Comment by mdoering** [comment]
In our API enum it always was a warning:
https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/OccurrenceIssue.java#L174

https://github.com/gbif/gbif-api/commit/3210bcf4ab52b863ea18860205ca4d1cabcf95cb

But I reckon we showed it otherwise before the issue severity was introduced

**Comment by MortenHofft** [comment]
I see that there are two endpoints and they classify differently. Which is the trusted one?
http://api.gbif.org/v1/occurrence/interpretation (deprecated?)
http://api.gbif.org/v1/enumeration/interpretationRemark/

**Comment by mdoering** [comment]
The enumeration one should be the up to date one to trust. I wasnt aware that the occurrence ws also exposes them. Actually the remarks exposed there are not the API enumeration but other ones: https://github.com/gbif/occurrence/tree/master/occurrence-common/src/main/java/org/gbif/occurrence/common/interpretation

@cgendreau should we not remove the org.gbif.occurrence.common.interpretation package alltogether with its [webservice](https://github.com/gbif/occurrence/blob/master/occurrence-ws/src/main/java/org/gbif/occurrence/ws/resources/InterpretationResource.java)?

**Comment by cgendreau** [comment]
yes, http://api.gbif.org/v1/occurrence/interpretation is the legacy one and it should be removed.

**Comment by mdoering** [comment]
... gone
