### ISSUE TITLE
hi I need plant Taxon id

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4650]
**hi I need plant Taxon id**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/85f142cfd9368603cbbf172604e4e66d:609f0885e5c12fede6d8f9cc146d7d25d01930bddf71fe03faf68a2d23f791daccd18cd5d0e5e8163ab788d3fd5d2501610fe2c2dedaf45481f00a6cf36a851c336b3b7e9c1a2b80ba9f8eb572577328bbe8b1b045d5a47a3701314a84d3d13d751c5bf6545edd141f13d4dff9f6483dad3d0425279ec039f9ef9b1726f2a8d7bdfbe8d69dedfa64541a213de8b61f29) - [Send email](https://www.gbif.org/api/feedback/user/mailto/85f142cfd9368603cbbf172604e4e66d:609f0885e5c12fede6d8f9cc146d7d25d01930bddf71fe03faf68a2d23f791daccd18cd5d0e5e8163ab788d3fd5d2501610fe2c2dedaf45481f00a6cf36a851c336b3b7e9c1a2b80ba9f8eb572577328bbe8b1b045d5a47a3701314a84d3d13d751c5bf6545edd141f13d4dff9f6483dad3d0425279ec039f9ef9b1726f2a8d7bdfbe8d69dedfa64541a213de8b61f29)
System: Chrome 111.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/system-health
Window size: width 1745 - height 886
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-29T07:18:15.613Z',to:'2023-03-29T07:24:15.613Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-29T07:18:15.613Z',to:'2023-03-29T07:24:15.613Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This user also wrote to helpdesk and I replied
