### ISSUE TITLE
Describe the changes for Reptilia and Actinopterygii in the backbone release notes

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#4651]
We keep getting questions on why Reptilia and Actinopterygii aren't in the backbone any more. There are a few GitHub issues on the topic but they are scattered.
It would be really helpful to be able to send those users one link. Ideally:
https://hosted-datasets.gbif.org/datasets/backbone/current/README.html

@mdoering would it be possible to add something there? Thanks!

**Comment by mdoering** [comment]
https://hosted-datasets.gbif.org/datasets/backbone/current/README.html#new-vertebrate-classification

**Comment by ManonGros** [comment]
Thank you Markus!
