### ISSUE TITLE
CAN i DO SEARCHES WHILE DATA IS DOWNLOADING

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4654]
**CAN i DO SEARCHES WHILE DATA IS DOWNLOADING**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e08bd1eb10ff67a74d027dca79b7f73c:044c5f5fabb9b9ff39585ed0fb8f9306f542bc382e9d287691fa3e37ec2ef2f26ad9de51073ff06e6f58ac61fa27a6ecb264da0bbc63b2217b6f1d828b9111a8ed49293db110de15622e48810e21ceb436bac0dbd1489c304dea4cd4b4e8e84d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/e08bd1eb10ff67a74d027dca79b7f73c:044c5f5fabb9b9ff39585ed0fb8f9306f542bc382e9d287691fa3e37ec2ef2f26ad9de51073ff06e6f58ac61fa27a6ecb264da0bbc63b2217b6f1d828b9111a8ed49293db110de15622e48810e21ceb436bac0dbd1489c304dea4cd4b4e8e84d)
System: Chrome 111.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search
Window size: width 1366 - height 625
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-29T19:04:20.728Z',to:'2023-03-29T19:10:20.728Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-29T19:04:20.728Z',to:'2023-03-29T19:10:20.728Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Yes you should be able to search occurrences while your downloads are being generated.

> Replied by email
