### ISSUE TITLE
iNaturalist Research Grade Species Complexes (groups) are matriculating as species records on GBIF

### ISSUE THREAD

**Issue by bdagley** [gbif/portal-feedback#4656]
This has been documented on iNaturalist multiple times recently. I suspect part of what may be involved is that species complexes are named after a focal species, so the scientific name contains the genus and species epithets of the focal species, which GBIF may be misinterpreting as a record of that species (rank mismatch). Although I don't fully know the casue or whether it would require work on GBIF and/or iNaturalist to correct. Some taxonomists on iNaturalist feel that this issue is serious enough that iNaturalist Research Grade Complex IDs should be temporarily stopped from being sent to GBIF.

**Comment by MattBlissett** [comment]
Thanks for bringing this to our attention.

An example: https://www.inaturalist.org/observations/13712739 — https://www.gbif.org/occurrence/3039147347

**Comment by thomasstjerne** [comment]
GBIF does not recognise the taxon rank `complex`. We have [Species Aggregate](https://gbif.github.io/gbif-api/apidocs/org/gbif/api/vocabulary/Rank.html#SPECIES_AGGREGATE). 
However, I am not sure whether this would be interpreted better or differently, but at least it would be recognised by our interpretation.
See also https://github.com/gbif/portal-feedback/issues/4014

**Comment by MattBlissett** [comment]
A complex is a synonym for species aggregate, see row 45: https://github.com/gbif/parsers/blob/master/src/main/resources/dictionaries/parse/rank.tsv

**Comment by bdagley** [comment]
I agree that it may work best to use species aggregate for iNaturalist complexes, although that doesn't seem to be functioning correctly currently. I notice one potential additional issue. In this example of an aggregate (https://www.gbif.org/species/100312176), the parent taxon is the genus, but the species (children/subtaxa) aren't shown under the aggregate. By contrast, iNaturalist (e.g. https://www.inaturalist.org/taxa/899420-Lasioglossum-pilosum) and BugGuide (e.g. https://bugguide.net/node/view/653202/tree) use a hierarchical framework where the species in a complex are shown under it as subtaxa of the complex (parent taxon). I'm aware that GBIF also uses a hierarchical framework, although as mentioned am unsure if it displays species below aggregates. In summary, it seems necessary to determine what rank aggregates occupies in GBIF's hierarchy, and whether any possible differences from iNaturalist would result in additional issues.

**Comment by thomasstjerne** [comment]
There are no consensus about which species belongs in a given species aggregate (often named by the oldest or most prominent name in the group). iNaturalist may have one taxon concept for `Aus bus complex`  or `Aus bus aggr.` which may include a different set of biological species than, say Swedish artportalens concept of `Aus bus aggr.` .
Species complexes / aggregates are informal groupings of biological species that are hard to distinguish and often they would be hard to compare across infrastructures or even geographical regions. For these reasons, it is currently not possible for GBIF to include child taxa of aggregates.

**Comment by MattBlissett** [comment]
Markus changed Checklistbank earlier this month to return a higher taxon for species aggregate queries. It's in UAT, but not yet in production:

http://api.gbif-uat.org/v1/species/match?name=Enchenopa%20binotata&kingdom=Animalia&phylum=Arthropoda&class=Insecta&order=Hemiptera&family=Membracidae&genus=Enchenopa&verbose=true&rank=complex

```json
{
  "usageKey": 2023682,
  "scientificName": "Enchenopa Amyot & Audinet-Serville, 1843",
  "canonicalName": "Enchenopa",
  "rank": "GENUS",
  "status": "ACCEPTED",
  "confidence": 100,
  "note": "Similarity: name=100; classification=50; rank=0; status=1; singleMatch=5",
  "matchType": "HIGHERRANK",
  "kingdom": "Animalia",
  "phylum": "Arthropoda",
  "order": "Hemiptera",
  "family": "Membracidae",
  "genus": "Enchenopa",
  "kingdomKey": 1,
  "phylumKey": 54,
  "classKey": 216,
  "orderKey": 809,
  "familyKey": 7889,
  "genusKey": 2023682,
  "synonym": false,
  "class": "Insecta"
}
```

So https://www.gbif.org/occurrence/3039147347 would then show as *Enchenopa* (just the genus) with a "higher taxon match" issue.  Searching for  *Enchenopa binotata* would not return the record.

We might make the change on gbif.org next week, or the week after, depending on some other ongoing work.

**Comment by bdagley** [comment]
iNaturalist mostly uses complexes or species groups from literature, and the subtaxa are hierarchically included on iNaturalist. I understand that there may still be some difficulty in comparing those to groupings from other sources, but just clarifying that the iNaturalist groupings are usually well-defined. 

The described solution to use genus instead of complex may be a fair compromise, since species-rank records are the most important anyway, and there isn't a huge difference between a complex and genus identified-record.

**Comment by CecSve** [comment]
This issue is also mentioned here https://github.com/gbif/portal-feedback/issues/4676

**Comment by MattBlissett** [comment]
Occurrences identified as species complexes now match to the genus, and have the `TAXON_MATCH_HIGHERRANK` issue applied; see https://www.gbif.org/occurrence/3039147347 for an example.

**Comment by bdagley** [comment]
Thanks for fixing this.
