### ISSUE TITLE
BioCASe synchronisation fails with cryptic message

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#4659]
This is the installation: https://registry.gbif.org/installation/603065ae-f762-11e1-a439-00145eb45e9a/synchronizationHistory
The error message is:
```
Synchronization failed with error [org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 3; The element type "link" must be terminated by the matching end-tag "</link>".]. 0 datasets were updated. 0 datasets were added. 0 datasets were deleted.
```

The endpoint with the issue is presumably this one: https://biocase.zfmk.de/biocase/dsa_info.cgi?dsa=ZMH-Collections-v2 (it is the latest one I added).
The publishers checked and there is no <Link> element in the whole DSA.

@MattBlissett @jholetschek, any idea of what could be happening? Thanks!

**Comment by MattBlissett** [comment]
The endpoint was https://biocase.zfmk.de/biocase/dsa_info.cgi?dsa=ZMH-Collections-v2 (the HTML page) rather than https://biocase.zfmk.de/biocase/pywrapper.cgi?dsa=ZMH-Collections-v2

**Comment by ManonGros** [comment]
Thanks Matt! I can't believe I missed that!

**Comment by jholetschek** [comment]
Oh... that's a classic!
