### ISSUE TITLE
verbatim name on occurrence pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#466]
**verbatim name on occurrence pages**

I'm still not sure i'm a fan of using the verbatim name instead the interpreted one you get if you download. I like better simply highlighting that they are different.

https://www.gbif.org/occurrence/1607002487 vs https://www.gbif.org/occurrence/1058406100

And it isn't clear to me when the title is in quotation marks and other times yellow.

-----
fbitem-occurrence1058406100
User provided contact info: mortenhofft
System: Chrome 60.0.3112 / Mac OS X 10.11.6
Referer: https://www.gbif.org/occurrence/1058406100
Window size: width 1600 - height 866
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-19T13:53:11.719Z',mode:absolute,to:'2017-09-19T13:59:11.719Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-19T13:53:11.719Z',mode:absolute,to:'2017-09-19T13:59:11.719Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 9d8ff248-3f6d-4180-a7f5-3570c489cf72
publishingOrgKey: d1146fd8-35d2-4264-a569-8f88cc29d0c8

**Comment by thomasstjerne** [comment]
See: https://github.com/gbif/portal16/issues/29
