### ISSUE TITLE
Hello, I am looking for occurrence data that includes the plant organ observed. I can see this in the interactive GUI on the website (e.g. flowers) but I have not been able to find this information in the GBIF download. I would like to use this to study flowering phenology for pollinators

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4664]
**Hello, I am looking for occurrence data that includes the plant organ observed. I can see this in the interactive GUI on the website (e.g. flowers) but I have not been able to find this information in the GBIF download. I would like to use this to study flowering phenology for pollinators**

-----

Github user: @KwnLi
User: [See in registry](https://www.gbif.org/api/feedback/user/8966b13f3341e0c9f7c9db4259cec97f:6bf90835e3275a7284c10b1611afb94c77b2023deeffe55fee6ea54560c5e236670ea52c4abf32f78c1c95e5ac7e5daf01f014081f5bb32cab066e4ff115e71cf9ebf27b5c0ca18e55194cc6cc98d4d763b21f72d16d250db6ae07db371b6aec) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8966b13f3341e0c9f7c9db4259cec97f:6bf90835e3275a7284c10b1611afb94c77b2023deeffe55fee6ea54560c5e236670ea52c4abf32f78c1c95e5ac7e5daf01f014081f5bb32cab066e4ff115e71cf9ebf27b5c0ca18e55194cc6cc98d4d763b21f72d16d250db6ae07db371b6aec)
System: Firefox 111.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/occurrence/download/0135553-230224095556074
Window size: width 1315 - height 769
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-31T17:46:19.078Z',to:'2023-03-31T17:52:19.078Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-03-31T17:46:19.078Z',to:'2023-03-31T17:52:19.078Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi @KwnLi
Thank you for your question and our apologies for the delayed answer. It looks like Pl@ntNet shares the information per image via the multimedia extension. So once your download the archive, open the file called `multimedia.txt` which should contain all the link to the images as well as the image caption, such as "Cercis canadensis L.: leaf	Cercis canadensis L.: **leaf**". You will have to link them to the occurrences yourself by using the occurrenceID.

Generally few data providers share phenology data on GBIF. You might find something for [datasets that are shared with a measurmentOrFact extension for example](https://www.gbif.org/occurrence/search?taxon_key=6&dwca_extension=http:~2F~2Frs.tdwg.org~2Fdwc~2Fterms~2FMeasurementOrFact&dwca_extension=http:~2F~2Frs.iobis.org~2Fobis~2Fterms~2FExtendedMeasurementOrFact). You can also take a look at field notes (like here: https://www.gbif.org/occurrence/1824266381) or remarks (https://www.gbif.org/occurrence/2809800817) which should both be available in the DARWIN CORE ARCHIVE format. But it isn't always easy to use as the formats are flexible and not specifically for phenology.

I will close the issue, don't hesitate to write again if anything remains unclear or have any question.
