### ISSUE TITLE
Orthographic variants "Artemisia siversiana" vs. "A. sieversiana" in backbone taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4672]
**Orthographic variants &quot;Artemisia siversiana&quot; vs. &quot;A. sieversiana&quot; in backbone taxonomy**

Artemisia siversiana Ehrh. ex Willd. (GBIF species 3121370) and Artemisia sieversiana Ehrh. ex Willd. (GBIF species 3121562) are orthographic variants of the same name, with the same publication cited, but are separate accepted species in the GBIF Backbone Taxonomy.

IPNI accepts "sieversiana" and has the nomenclatural note "as Siversiana": https://www.ipni.org/n/urn:lsid:ipni.org:names:180122-1

-----

Github user: @kbseah
User: [See in registry](https://www.gbif.org/api/feedback/user/24cbd55da05c6f1d94e0e88895ade4de:d4136262ca15d7f73bb52d4515cdf610cb4259992e6c8ffc86cd8d19e7c618ae9fc34b8078c06665a86188232255dede095f338baa146c863aca0f3227f60d9a14609d1014fe414cb9593c6ab3598c3423ace1aea79a4790f5914916793cb92837996d95c5ca0595e5ce545f7315951384686f30e4d183f8c38aed66b59f9e8f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/24cbd55da05c6f1d94e0e88895ade4de:d4136262ca15d7f73bb52d4515cdf610cb4259992e6c8ffc86cd8d19e7c618ae9fc34b8078c06665a86188232255dede095f338baa146c863aca0f3227f60d9a14609d1014fe414cb9593c6ab3598c3423ace1aea79a4790f5914916793cb92837996d95c5ca0595e5ce545f7315951384686f30e4d183f8c38aed66b59f9e8f)
System: Firefox 102.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/3121562
Window size: width 1963 - height 1017
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-06T10:08:06.535Z',to:'2023-04-06T10:14:06.535Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-06T10:08:06.535Z',to:'2023-04-06T10:14:06.535Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
@bart-v , this comes from WoRMS and you might want to fix it there

https://www.gbif.org/species/search?q=Artemisia%20siversiana&dataset_key=2d59e5db-57ad-41ff-97d6-11f5fb264527&origin=SOURCE&qField=SCIENTIFIC&advanced=1

**Comment by bart-v** [comment]
Fixed in WoRMS & available in next export

**Comment by kbseah** [comment]
thanks!
