### ISSUE TITLE
Cladonia Chlorophaea Complex is exported to GBIF as Cladonia Chlorophaea.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4676]
**Cladonia Chlorophaea Complex is exported to GBIF as Cladonia Chlorophaea.**

The occurence in question, and this is not limited to just this occurence is https://www.gbif.org/occurrence/4028920819;
It seems that GBIF alters all species-complex observations from the site "iNaturalist" to a random species within the complex, even if the identification is false and not supported by the community.

Why does the Global Biodiversity Information Facility do this? is there any way to stop misidentifications occuring primarily because of this?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b6fd23e621af3cfc66b9cdce3e990e64:647c12f6ac069fe599b77477b0216fa211d3cf592d06a5084728c2ac8c1d22863892dd002c75ecc6568d4898d4ca30c5c1775e080a84e83e4421b179121bb8255816353054fb9ac0bbb2279b87c918003c32d026a39061c8accd05ed02d03fd3) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b6fd23e621af3cfc66b9cdce3e990e64:647c12f6ac069fe599b77477b0216fa211d3cf592d06a5084728c2ac8c1d22863892dd002c75ecc6568d4898d4ca30c5c1775e080a84e83e4421b179121bb8255816353054fb9ac0bbb2279b87c918003c32d026a39061c8accd05ed02d03fd3)
System: Chrome 112.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/4028920819
Window size: width 1536 - height 746
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-08T00:27:38.043Z',to:'2023-04-08T00:33:38.043Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-08T00:27:38.043Z',to:'2023-04-08T00:33:38.043Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

Node handles: @albenson-usgs @sformel-usgs

**Comment by CecSve** [comment]
This issue is also mentioned here: https://github.com/gbif/portal-feedback/issues/2935. GBIF is working on changing the interpretation behavior so the taxa instead is matched to the higher rank (https://github.com/gbif/portal-feedback/issues/4656#issuecomment-1491669828) and is currently testing the implementation.

**Comment by MattBlissett** [comment]
Occurrences identified as species complexes now match to the genus, and have the `TAXON_MATCH_HIGHERRANK` issue applied; see https://www.gbif.org/occurrence/3039147347 for an example.

**Comment by CecSve** [comment]
Thank you, Matt. I have contacted the user who supplied the issue and will therefore close this issue.
