### ISSUE TITLE
The taxon Polistes testaceicolor also includes records and photos of a different species, Vespa analis

### ISSUE THREAD

**Issue by bdagley** [gbif/portal-feedback#4679]
Link: https://www.gbif.org/occurrence/search?taxon_key=1310852.

**Comment by ManonGros** [comment]
In the current version of the GBIF Backbone taxonomy, [Vespa analis (Fabricius, 1775)](https://www.gbif.org/species/1310853) is a synonym of [Polistes testaceicolor Bequard, 1937](https://www.gbif.org/species/1310852)

related issue: https://github.com/CatalogueOfLife/data-vespoidea/issues/1

**Comment by bdagley** [comment]
This issue was moved here (https://github.com/CatalogueOfLife/data-vespoidea/issues/20) where it is an open issue.
