### ISSUE TITLE
Ardeola ibis is a synonym for Bubulcus ibis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#468]
**Ardeola ibis is a synonym for Bubulcus ibis**

Testing whether it is really useful for us to collect "that species doesn't exist" comments - can we use this information this way?

-----
fbitem-species4847080
User provided contact info: dhobern@gbif.org
System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://www.gbif.org/species/4847080
Window size: width 1536 - height 735
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-20T06:57:09.973Z',mode:absolute,to:'2017-09-20T07:03:09.973Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-20T06:57:09.973Z',mode:absolute,to:'2017-09-20T07:03:09.973Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
We can. Usually we pool these backbone content comments until a new Backbone release is done. Here are the current open ones: https://github.com/gbif/portal-feedback/labels/backbone

Then we can review them and add them to the patch list so they enter the next backbone:
https://github.com/gbif/backbone-patch

Ideally these comments should end up in https://github.com/gbif/backbone-patch/issues

**Comment by mdoering** [comment]
Here is the commit history with the comments incorporated: https://github.com/gbif/backbone-patch/commits/master
