### ISSUE TITLE
Hello! We published our data yesterday, but we still don't see all occurences of our dataset. When It will be published?https://www.gbif.org/dataset/78f7dbd8-859a-4d46-a278-85439d28db49 Thank you!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4680]
**Hello! We published our data yesterday, but we still don&#39;t see all occurences of our dataset. When It will be published?`https://www.gbif.org/dataset/78f7dbd8-859a-4d46-a278-85439d28db49` Thank you!**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9ff388c5c5fcea48c537e8df17ee6309:7bd3c5004e4899b3db855fc3863d961be299a44554f9e49a2bbe88e1187c0450b5c0af7c2483ddb8b32ba6a3c69f78cac5c1a6d591b99299f0114361388850031f01cb6cc42517f1b522042b386105b2585df74149f49d482038415858ab29e17d122687d2819f9e602d7051f21dc7a385510a53c1ea7d661500af08f12e071dab6ef6c55c54c173eb887e3b6ea1c2c9c09bd3b9dd8824ffcf6767ddf67d4083) - [Send email](https://www.gbif.org/api/feedback/user/mailto/9ff388c5c5fcea48c537e8df17ee6309:7bd3c5004e4899b3db855fc3863d961be299a44554f9e49a2bbe88e1187c0450b5c0af7c2483ddb8b32ba6a3c69f78cac5c1a6d591b99299f0114361388850031f01cb6cc42517f1b522042b386105b2585df74149f49d482038415858ab29e17d122687d2819f9e602d7051f21dc7a385510a53c1ea7d661500af08f12e071dab6ef6c55c54c173eb887e3b6ea1c2c9c09bd3b9dd8824ffcf6767ddf67d4083)
System: Chrome 111.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/78f7dbd8-859a-4d46-a278-85439d28db49
Window size: width 1536 - height 760
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-10T10:34:39.717Z',to:'2023-04-10T10:40:39.717Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-10T10:34:39.717Z',to:'2023-04-10T10:40:39.717Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by muttcg** [comment]
The ingestion of the dataset was paused by one of the checker systems until it was manually checked, and coincidentally, this occurred during the Easter holidays.

Fixed
