### ISSUE TITLE
Dates not showing in Korean dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4688]
**Dates not showing in Korean dataset**

None of the dates are showing up in this new insect collection dataset - looks like it is a simple formatting error which should be easy to fix.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c4b4ef3eb34620cc996eb27f71d6ce4e:780c7787652c22f62393403866ddb7f2e315ea6634165ffd2f876637c7adb96ec8a26cbc7b0ead68196c2b7b59c8338f1d3a2c51633a8903885d7bb5059fee1960b171bd65f4b55337329c7411f9b7071acd24528a3cfa7082a333b18ec1321cd8ddd07feb2994e739f3062745bd60cebcb6554afcda8426ea1e0db05052fdba) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c4b4ef3eb34620cc996eb27f71d6ce4e:780c7787652c22f62393403866ddb7f2e315ea6634165ffd2f876637c7adb96ec8a26cbc7b0ead68196c2b7b59c8338f1d3a2c51633a8903885d7bb5059fee1960b171bd65f4b55337329c7411f9b7071acd24528a3cfa7082a333b18ec1321cd8ddd07feb2994e739f3062745bd60cebcb6554afcda8426ea1e0db05052fdba)
System: Chrome 111.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/6081c93c-6f13-46a6-a4eb-2852444d20c2
Window size: width 1901 - height 882
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-12T07:24:38.922Z',to:'2023-04-12T07:30:38.922Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-12T07:24:38.922Z',to:'2023-04-12T07:30:38.922Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Issue corrected by the data publisher - closing
