### ISSUE TITLE
Dates not showing in Korean plant dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4689]
**Dates not showing in Korean plant dataset**

Dates are not showing up in this plant dataset from Korea, same formatting problem as for insect dataset mentioned in https://github.com/gbif/portal-feedback/issues/4688

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/02222a7ace6a71086d5f3d49f1086284:22e3c13edd664864dcbefb7db81bb693ce0ced35ec863c69dfa0b339f786164fad7a94db967fff7a49923ed8b03255d13932b2d71bb8569324738cffac720ae9076baf04c123301192d0d071a1e30bcc98017bc8c37428c9c7103dc1d1624fe24d310c79c194e609289846189c7e8eb59ba9728d1fbc471e33a06c4dbc6d961c) - [Send email](https://www.gbif.org/api/feedback/user/mailto/02222a7ace6a71086d5f3d49f1086284:22e3c13edd664864dcbefb7db81bb693ce0ced35ec863c69dfa0b339f786164fad7a94db967fff7a49923ed8b03255d13932b2d71bb8569324738cffac720ae9076baf04c123301192d0d071a1e30bcc98017bc8c37428c9c7103dc1d1624fe24d310c79c194e609289846189c7e8eb59ba9728d1fbc471e33a06c4dbc6d961c)
System: Chrome 111.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/fd412894-d7c5-4a09-8dd7-271f2c83bf44
Window size: width 1901 - height 882
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-12T07:27:33.312Z',to:'2023-04-12T07:33:33.312Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-12T07:27:33.312Z',to:'2023-04-12T07:33:33.312Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Date format issue corrected by data publisher - closing
