### ISSUE TITLE
Vernacular name shows capital letters where verbatim record doesn't have them

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#469]
**Vernacular name shows capital letters where verbatim record doesn&#39;t have them**

For this specific record of Geophilus flavus in Checklist Dutch Species Register, the overview page shows vernacular name "Gele Aardkruiper", whereas the verbatim page shows "Gele aardkruiper" (without capital A). The verbatim page is correct. Is this a bug on the overview page?

Thanks,
Sander (Naturalis Biodiversity Center)

-----
fbitem-species124567189
User provided contact info: sander.pieterse@naturalis.nl
System: Chrome 60.0.3112 / Windows 7 0.0.0
Referer: https://www.gbif.org/species/124567189
Window size: width 1920 - height 950
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-20T07:30:30.723Z',mode:absolute,to:'2017-09-20T07:36:30.723Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-20T07:30:30.723Z',mode:absolute,to:'2017-09-20T07:36:30.723Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
The verbatim name from the publisher is `Gele aardkruiper`
The verbatim name provided by the API is `gele aardkruiper`
The website capitalize the name to `Gele Aardkruiper`

The correct would probably be to stick with the API version and change the API to respect the provided casing.

**Comment by mdoering** [comment]
Not sure what verbatim name from API is, but the species API returns `Gele aardkruiper` as published: https://api.gbif.org/v1/species/124567189/vernacularNames

**Comment by MortenHofft** [comment]
Sorry about that Markus - I see that it is an API wrapper. https://www.gbif.org/api/species/124567189/vernacularNames
@thomasstjerne I guess the names are lower cased as a part of removing duplicates?

**Comment by thomasstjerne** [comment]
Yes its a pure css issue. Will fix it
