### ISSUE TITLE
Hello! can i delete this dataset? was published by mistake from the IPT of Guatemala. https://www.gbif.org/dataset/4e0866ce-f9b1-4752-a40e-c7950765c99a

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4690]
**Hello! can i delete this dataset? was published by mistake from the IPT of Guatemala. `https://www.gbif.org/dataset/4e0866ce-f9b1-4752-a40e-c7950765c99a`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/79929ce70c47b72387d65d26cd4b369d:dbfa3e29081b5e67e1b360c17e9ede2558ef0068e4d411dbc87e74f6fc91f909e81713f0abe6ece681618ab0f7b337666f23a29aee033123ee5db3d3c9597fe248d9e1b32487a874a5e258eef4d0a7ab7b70a9c9130ef43d98ebf74aa479d1edb6df7699d593c241da214712dc370012acd82727a2d8e734e557f459de6dffea2dec409a1f49ded52ddbfe0ed711dda13332202a93b3dd50226ac200e71fd173be4ee466d557d89331c110746e05ceeb) - [Send email](https://www.gbif.org/api/feedback/user/mailto/79929ce70c47b72387d65d26cd4b369d:dbfa3e29081b5e67e1b360c17e9ede2558ef0068e4d411dbc87e74f6fc91f909e81713f0abe6ece681618ab0f7b337666f23a29aee033123ee5db3d3c9597fe248d9e1b32487a874a5e258eef4d0a7ab7b70a9c9130ef43d98ebf74aa479d1edb6df7699d593c241da214712dc370012acd82727a2d8e734e557f459de6dffea2dec409a1f49ded52ddbfe0ed711dda13332202a93b3dd50226ac200e71fd173be4ee466d557d89331c110746e05ceeb)
System: Chrome 111.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/4e0866ce-f9b1-4752-a40e-c7950765c99a
Window size: width 1643 - height 813
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-12T15:40:56.195Z',to:'2023-04-12T15:46:56.195Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-12T15:40:56.195Z',to:'2023-04-12T15:46:56.195Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
You can delete the dataset directly from the IPT (there is the option to delete it from GBIF as well). Alternatively, if you would like to keep the dataset in the IPT and only delete it on GBIF, it can be deleted registry: https://registry.gbif.org/dataset/4e0866ce-f9b1-4752-a40e-c7950765c99a.

> Replied by email
