### ISSUE TITLE
Records dropped ~5M

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4692]
**Records dropped ~5M**

5M records have disappeared in this dataset since the last publication event.

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/70505b7619a69d00c161ec9dc2a378a4:ba7ee5fc3dce45dd54b3adbc54410eaab6aa3fdfe1772c43ac16feae6e77393cbed995297ba9d56013f6b7d32322dc89c95d5a4c9edcfac3b92022235863ece7974069030e2f4f4b08526240364be51dc4691530448aa2a9c610f979b3e44ef170928d43c0996dc14f3b5a173ce36e34319064f639ed20c2dbdbe26f0b267c504535fcf6624b5b0f0627b4cd1c53644a10dfbc3b1442dd2cf86f1b4d1e324690) - [Send email](https://www.gbif.org/api/feedback/user/mailto/70505b7619a69d00c161ec9dc2a378a4:ba7ee5fc3dce45dd54b3adbc54410eaab6aa3fdfe1772c43ac16feae6e77393cbed995297ba9d56013f6b7d32322dc89c95d5a4c9edcfac3b92022235863ece7974069030e2f4f4b08526240364be51dc4691530448aa2a9c610f979b3e44ef170928d43c0996dc14f3b5a173ce36e34319064f639ed20c2dbdbe26f0b267c504535fcf6624b5b0f0627b4cd1c53644a10dfbc3b1442dd2cf86f1b4d1e324690)
System: Chrome 112.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/d8cd16ba-bb74-4420-821e-083f2bac17c2
Window size: width 1585 - height 861
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-14T01:52:19.902Z',to:'2023-04-14T01:58:19.902Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-14T01:52:19.902Z',to:'2023-04-14T01:58:19.902Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dshorthouse** [comment]
@dagendresen - I did not see until now that you are the installation contact. You know anything about the above &/or can prod who might respond?

**Comment by ManonGros** [comment]
@dshorthouse, Dag didn't publish this dataset, it is generated automatically from the EMBL API

@mike-podolskiy90 @thomasstjerne I am not sure what could have happened, any idea?

**Comment by mike-podolskiy90** [comment]
We have never had anything like that with that dataset. Another related resource https://cloud.gbif.org/eca/resource?r=insdc-host-organism-sequences lost half a million records too.

Looking into it

**Comment by mike-podolskiy90** [comment]
Both dataset are fine now in the IPT:
https://cloud.gbif.org/eca/resource?r=insdc-sequences
https://cloud.gbif.org/eca/resource?r=insdc-host-organism-sequences

They'll be re-indexed soon

**Comment by timrobertson100** [comment]
@ManonGros @muttcg - should we abort ingestion when detecting large data drops, similar to what we do when we detect large ID changes?
