### ISSUE TITLE
Hi my extraction of iNaturalist data states there are many more records than rows of data. For example i extracted DOI: https://doi.org/10.15468/dl.7x4dh3 (may take some hours before being active)  Creation Date: 01:03:13 15 April 2023  Records included: 557516 records from 1 published datasets  Compressed data size: 323.1 MB  Download format: DWCA  Filter used:  {   "and" : [     "Continent is Africa",     "DatasetKey is iNaturalist Research-grade Observations",     "Year 2022-2023"   ] } Download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4694]
**Hi my extraction of iNaturalist data states there are many more records than rows of data. For example i extracted DOI: `https://doi.org/10.15468/dl.7x4dh3` (may take some hours before being active) Creation Date: 01:03:13 15 April 2023 Records included: 557516 records from 1 published datasets Compressed data size: 323.1 MB Download format: DWCA Filter used: { &quot;and&quot; : [ &quot;Continent is Africa&quot;, &quot;DatasetKey is iNaturalist Research-grade Observations&quot;, &quot;Year 2022-2023&quot; ] } Download**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/21f545ec5ee403072b38766fc6000620:eb4452ed8136cdcf1f3d0996a5fb75e05dc6c7eccb5d610e897bcd7f004ab2ea3c1e1b4c912611abd00fcc46684507e97f42b9726dec256f48134220cfc2abe309ff491aa44c35551c7d6aa7ac197423901e7cebfbfe5ebdde260bf86913129ecbdc645b35527a8b7eac5e43bcc53bb0) - [Send email](https://www.gbif.org/api/feedback/user/mailto/21f545ec5ee403072b38766fc6000620:eb4452ed8136cdcf1f3d0996a5fb75e05dc6c7eccb5d610e897bcd7f004ab2ea3c1e1b4c912611abd00fcc46684507e97f42b9726dec256f48134220cfc2abe309ff491aa44c35551c7d6aa7ac197423901e7cebfbfe5ebdde260bf86913129ecbdc645b35527a8b7eac5e43bcc53bb0)
System: Chrome 112.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0168643-230224095556074
Window size: width 1290 - height 1038
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-15T01:39:42.254Z',to:'2023-04-15T01:45:42.254Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-15T01:39:42.254Z',to:'2023-04-15T01:45:42.254Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
As far as I can see, the file named occurrence.txt has 248,541 rows which corresponds to the 248,540 occurrences expected in the download. Could you let us know which tool you are using to open this file?
I know for example, that some R users have had issues with processing files downloaded from GBIF (https://discourse.gbif.org/t/reading-gbif-downloads-simple-csv-with-r/2615). Perhaps trying a different tool or a different way to open the file would help?

> Replied by email
