### ISSUE TITLE
Images do not appear

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4695]
**Images do not appear**

For dataset 39b4ca7a-27f7-4489-8b49-c539144ccdc8 (Fossil collection of University Museum Utrecht (UMU)) the images do not appear. There are no issues in the datavalidator with the multimedia, but somehow the multimedia extension is ignored.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/70f45d3dd6cdd6caaeed7958ef5104a7:7de2844b3820c8dac51213aab7d7d8eefa89eceeea9dda07b90a0f83674a2f899477cf7616976f9e5d57463e2426bcca9ee66cd538553763eded1875c236fa60e55d4adf55915641d41f02b344fb8047f0338b20619d14e5707469e239816d46b4731c052d3d032ad383003928afb3d60f26f20eda67344fdd7db5455c32021629a0f7f6a4c3b22a3fb5f582370929f9) - [Send email](https://www.gbif.org/api/feedback/user/mailto/70f45d3dd6cdd6caaeed7958ef5104a7:7de2844b3820c8dac51213aab7d7d8eefa89eceeea9dda07b90a0f83674a2f899477cf7616976f9e5d57463e2426bcca9ee66cd538553763eded1875c236fa60e55d4adf55915641d41f02b344fb8047f0338b20619d14e5707469e239816d46b4731c052d3d032ad383003928afb3d60f26f20eda67344fdd7db5455c32021629a0f7f6a4c3b22a3fb5f582370929f9)
System: Chrome 112.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0170471-230224095556074
Window size: width 1707 - height 738
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-15T22:37:11.752Z',to:'2023-04-15T22:43:11.752Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-15T22:37:11.752Z',to:'2023-04-15T22:43:11.752Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by muttcg** [comment]
Fixed
