### ISSUE TITLE
heavy saving process

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4700]
**heavy saving process**

May be it is just my PowerPoint - downloading pptx and saving after tiny edits (numbers edits), saving pptx takes forever and incl. a crash or two. Does it have to be so heavy? Just tested download on Win and on Mac in low internet area, other members of the network will likely have issues, too

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/831b56dbb797afa05b8634837cf6603c:553d72794b75cf817f6fd322bd04e8ac126638b282dbdda07de9e04dd7a063d29299d1922bf2bd35c668467c601aab323fa1223dfa72f22b7633e2b1af6aa25cf9e55dfc06244bdc8d8f71f572df25e4a2da9ab1de0d8de67dc0f63f97e38382486564bdc1e7d83a329a99307232ca832cdc958d819788c8be5b0d823d130c28) - [Send email](https://www.gbif.org/api/feedback/user/mailto/831b56dbb797afa05b8634837cf6603c:553d72794b75cf817f6fd322bd04e8ac126638b282dbdda07de9e04dd7a063d29299d1922bf2bd35c668467c601aab323fa1223dfa72f22b7633e2b1af6aa25cf9e55dfc06244bdc8d8f71f572df25e4a2da9ab1de0d8de67dc0f63f97e38382486564bdc1e7d83a329a99307232ca832cdc958d819788c8be5b0d823d130c28)
System: Chrome 112.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/document/81771/gbif-overview-powerpoint-slides
Window size: width 1536 - height 758
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-17T09:31:39.216Z',to:'2023-04-17T09:37:39.216Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-17T09:31:39.216Z',to:'2023-04-17T09:37:39.216Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
I reproduced this on my Mac, too. Saving the file after making changes takes > full minute for me. I tried it with the two latest versions of the slides.

**Comment by kcopas** [comment]
Thanks for the feedback. Work on an updated template is ongoing, as you know. Please send comments via email, rather than posting them as website issues.
