### ISSUE TITLE
Where is the legend on the species distribution maps? I also was wondering if it is possible to filter results to only show the native distribution.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4706]
**Where is the legend on the species distribution maps? I also was wondering if it is possible to filter results to only show the native distribution.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b82c50541c43bb0e9a05758fac78dd87:9f283dd6d4ce0513df978cce6db64c7185f22b4294d9d477be530746e22677fe0945d640420374d5e3559798945eb8f46842b9e61c408a834029699cb88ef601d7046d44168cda5a383222e3627acb3de1384396069ad41253f2dac2d757037a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b82c50541c43bb0e9a05758fac78dd87:9f283dd6d4ce0513df978cce6db64c7185f22b4294d9d477be530746e22677fe0945d640420374d5e3559798945eb8f46842b9e61c408a834029699cb88ef601d7046d44168cda5a383222e3627acb3de1384396069ad41253f2dac2d757037a)
System: Chrome 112.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=legend
Window size: width 1366 - height 625
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-18T15:24:07.323Z',to:'2023-04-18T15:30:07.323Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-18T15:24:07.323Z',to:'2023-04-18T15:30:07.323Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by thomasstjerne** [comment]
Answered by email
