### ISSUE TITLE
DNA sequences not in download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4717]
**DNA sequences not in download**

When downloading a set of occurrences, e.g. all occurrences from an event in the Biowide fungi eDNA dataset, none of the download options gives me the sequences (from the DNA derived extension).

Don't know if it is a bug, but I would expect to get the sequence and other info from the dna-extension in downloads.

https://www.gbif.org/occurrence/download?dataset_key=3b8c5ed8-b6c2-4264-ac52-a9d772d69e9f&event_id=biowide-sv088

-----

Github user: @tobiasgf
User: [See in registry](https://www.gbif.org/api/feedback/user/cce935c63b616e18c17ee6a3801f9b13:5a2ce21c0a0db2b4b219d3992180c65168fee7b8ef393f2e73c12a701213eb99db7b0adbc5d20b9d0f99288f6590ccf1c5fa0e43f48aa263ed214ddda5ca791c7a1173c0d83ddec65aa6ce2324ff44b3a115bfbad82d14e96787fb9396a885f330de0891b0ddd285fd7b1647275368884851a714d34841621d392e4c2938a79a4c55b47101f946a4f9a376eb04cf8a1f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/cce935c63b616e18c17ee6a3801f9b13:5a2ce21c0a0db2b4b219d3992180c65168fee7b8ef393f2e73c12a701213eb99db7b0adbc5d20b9d0f99288f6590ccf1c5fa0e43f48aa263ed214ddda5ca791c7a1173c0d83ddec65aa6ce2324ff44b3a115bfbad82d14e96787fb9396a885f330de0891b0ddd285fd7b1647275368884851a714d34841621d392e4c2938a79a4c55b47101f946a4f9a376eb04cf8a1f)
System: Chrome 112.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download?dataset_key=3b8c5ed8-b6c2-4264-ac52-a9d772d69e9f&event_id=biowide-sv088
Window size: width 1650 - height 919
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-25T09:16:23.906Z',to:'2023-04-25T09:22:23.906Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-25T09:16:23.906Z',to:'2023-04-25T09:22:23.906Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Looks to me like this is already captured in 
https://github.com/gbif/gbif-api/issues/100
https://github.com/gbif/portal-feedback/issues/4135
https://github.com/gbif/occurrence/issues/222

I will close unless in favour of the existing. Feel free to reopen if I misunderstand
