### ISSUE TITLE
Match to GBIF backbone of taxon in checklist different than result species matching tool

### ISSUE THREAD

**Issue by damianooldoni** [gbif/portal-feedback#4718]
Within the [RIPARIAS target species list](https://www.gbif.org/dataset/fd004d9a-2ea4-4244-bb60-0df508d20a15) we published this species, [_Zizania latifolia_](https://www.gbif.org/species/194877255) along with its vernacular names in English, Dutch and French. As you can see by clicking on "VIEW ON GBIF BACKBONE" button, this taxon is linked to [Zizania latifolia (Griseb.) Stapf](https://www.gbif.org/species/2703231 ) (taxonomic status: `DOUBTFUL`), which has the very same vernacular name(s).

However, if I run a species match via [Species matching tool](https://www.gbif.org/tools/species-lookup) or via `rgbif::name_backbone(name = "Zizania latifolia")` in R, I get a link to [_Zizania latifolia (Griseb.) Hance ex F.Muell._](https://www.gbif.org/species/10919373) (taxonomic status: `ACCEPTED`).

Is the indexing of all checklists against the Backbone maybe ongoing and so is it just a question of time? Or the problem is due to the fact that the GBIF checklist publication process takes into account the match of the vernacular names as well, which I thought it was not the case?

Thanks!

**Comment by damianooldoni** [comment]
I checked a little further. I think it's not a problem of indexing the checklist to the backbone as this "mismatch" was probably present already few months ago. Maybe a different matching script as supposed by @peterdesmet?

**Comment by ManonGros** [comment]
perhaps this is a question for @mdoering or @thomasstjerne ?

**Comment by mdoering** [comment]
There are subtle differences how the matching works for occurrences (=public matching) & checklists. That is likely the cause of the different results

**Comment by damianooldoni** [comment]
Thanks @mdoering. Is there a tool to get in advance the GBIF Backbone match for checklists? Which workflow do you suggest?

**Comment by mdoering** [comment]
Im afraid this is not exposed in our API. The closest is to use the "occurrence" matching in [strict mode](http://api.gbif.org/v1/species/match?verbose=true&name=Zizania%20latifolia&strict=true), but it's not gonna give you exactly the same results I am afraid. I will keep that in mind for the future to expose such services, but it's nothing we can easily change soon. In fact the exposed matching service does a better job in your case, it should have preferred the accepted name to the doubtful one.

**Comment by damianooldoni** [comment]
Thanks!
