### ISSUE TITLE
Steller's sea eagle doesn't occur in Europe

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#472]
**Steller&#39;s sea eagle doesn&#39;t occur in Europe**

There are numerous records from ArtDatabanken of _Haliaeetus pelagicus_ from Norway, which are almost certainly false. This bird (Steller's sea eagle) is restricted to Russia and Japan. I suspect the Norway records are actually https://en.wikipedia.org/wiki/White-tailed_eagle (_Haliaeetus albicilla_). Finding Steller's sea eagle in Europe would be pretty astounding.

-----
fbitem-species2480445
User provided contact info: rdmpage
System: Safari 10.0.2 / Mac OS X 10.10.5
Referer: https://www.gbif.org/species/2480445
Window size: width 1385 - height 912
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-20T21:12:08.408Z',mode:absolute,to:'2017-09-20T21:18:08.408Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-20T21:12:08.408Z',mode:absolute,to:'2017-09-20T21:18:08.408Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
Steller´s sea eagle occured in Denmark and Sweden some years ago. 
I Denmark, there was a Bird in 2013 for a few days: https://dofbasen.dk/search/result.php?design=table&soeg=soeg&periode=maanedaar&aar_first=1950&aar_second=2017&artdata=art&hiddenart=02450&obstype=observationer&species=alle&sortering=dato

Nice photo of the danish occurrence: http://www.netfugl.dk/pictures.php?id=showpicture&picture_id=55486

When I look at the data from swedish artsportalen it seems that a bird has been spotted in three periods in 2013, 2014 and 2015. The sightings in 2013 have comments that it is probably the same bird seen in Denmark the same year. There are some discussions whether the bird occurred spontaneous or it could have escaped from illegal bird trading activities : https://www.artportalen.se/Image/1289231

I was working in BirdLife Denmark when the bird was spotted, and I can indeed verify that danish ornithologists found it very astounding.

**Comment by rdmpage** [comment]
Cool! Now, how would I know this? Is there any way for a naive user who hasn’t worked for Birdlife Denmark to discover this? In other words, we can we annotate data...?

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________
