### ISSUE TITLE
We would like to use the map on your website, but the map marks Taiwan as a country. Can we not show Taiwan or label it as "Taiwan Province"?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4720]
**We would like to use the map on your website, but the map marks Taiwan as a country. Can we not show Taiwan or label it as &quot;Taiwan Province&quot;?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/cb41e83084d09d2ecf20ed1a03f01266:d251301fe0893431a6367f42f42d80942313e5fe66fba5c68582c810e431ade7762d1236d600087b1836820b02c437afcebafc491218caaa31c563992c8e87deec7414fcb6c9446bd568f4f5a87c72037a087a9c805180ee3c13add21c1a16a5) - [Send email](https://www.gbif.org/api/feedback/user/mailto/cb41e83084d09d2ecf20ed1a03f01266:d251301fe0893431a6367f42f42d80942313e5fe66fba5c68582c810e431ade7762d1236d600087b1836820b02c437afcebafc491218caaa31c563992c8e87deec7414fcb6c9446bd568f4f5a87c72037a087a9c805180ee3c13add21c1a16a5)
System: Chrome 86.0.4240 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/map?taxon_key=2678432&taxon_key=2677636&license=CC_BY_4_0&license=CC_BY_NC_4_0
Window size: width 1920 - height 871
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-27T03:59:39.596Z',to:'2023-04-27T04:05:39.596Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-27T03:59:39.596Z',to:'2023-04-27T04:05:39.596Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by RianQuenlin** [comment]
Taiwan **is** a country, you fucking idiot!

**Comment by RianQuenlin** [comment]
Taiwan is a country, you racist idiot. Deleting my comment doesn't change that fact.

**Comment by MattBlissett** [comment]
Thank you for your feedback on the GBIF.org website.

We derive our map layers from external sources for the purpose of data visualization, and GBIF does not make any judgement concerning the legal status of any territory.  Please see the "Maps and boundaries" section on https://www.gbif.org/terms.

Users may combine the data/occurrence layer of GBIF's maps with any base layer using the mapping API, see https://www.gbif.org/developer/maps.  This is commonly done to provide a map with labels in a different language, or a satellite map, etc. 

_Some comments on this discussion have been removed.  Comments must adhere to GBIF's code of conduct: https://www.gbif.org/code-of-conduct_
