### ISSUE TITLE
New CitSci dataset as checklist?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4721]
**New CitSci dataset as checklist?**

Saw this come in and thought it should probably be machine-tagged accordingly, but was surprised to see it's a checklist dataset: https://www.gbif.org/dataset/e9706a52-ee3c-46c3-b14a-c71e3071de6d

Two questions:
- is the dataset type an error?
- if we tag the dataset, will the occurrences be added to our cit-sci numbers, even though it's a checklist?

-----

Github user: @kcopas
User: [See in registry](https://www.gbif.org/api/feedback/user/87556de594cb9884485dbe7274c90264:ec6308991b8b617a13ec7f3d902ee2a98ce021c8ba7b963b712d1e9ada714648f8e65cb1a1f826b8c59845351dd303146c86d7b9160cdb0fc2340561370b22e7b447bf7297f1073408dec5f9b6687649e4b35df6b6e10631fb8c552f741630558362f97a9845ad49e856866979980c94278d10154bd48359830d3fc6d7580d7e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/87556de594cb9884485dbe7274c90264:ec6308991b8b617a13ec7f3d902ee2a98ce021c8ba7b963b712d1e9ada714648f8e65cb1a1f826b8c59845351dd303146c86d7b9160cdb0fc2340561370b22e7b447bf7297f1073408dec5f9b6687649e4b35df6b6e10631fb8c552f741630558362f97a9845ad49e856866979980c94278d10154bd48359830d3fc6d7580d7e)
System: Firefox 112.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/dataset/e9706a52-ee3c-46c3-b14a-c71e3071de6d
Window size: width 1355 - height 800
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-27T08:16:18.338Z',to:'2023-04-27T08:22:18.338Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-27T08:16:18.338Z',to:'2023-04-27T08:22:18.338Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi @kcopas it is checklist with an occurrence extension so the dataset type is actually correct.
The numbers would be added indeed if we tag the dataset.
