### ISSUE TITLE
Many images not showing on GBIF.org

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4724]
**Many images not showing on GBIF.org**

It seems something is preventing a large number of images appearing. While this may often be due to photo services being offline, this is affecting a significant proportion of iNat records as shown in this gallery view, suggesting a general bug. Same on Chrome and Safari.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5986a640eeb3a370eea3f59eedd2d393:cfcff3307278011d3588dc242a04c117e8c9a303e0ae45ddf053ede1c4a5b98e8c5865e3ab4f8352f0c8b70cfc2d9382e344d63490da28a1549523b6fb9943243f5436c2a2dd3fc766ba6ebb9f392ea68ffd92befad5d53f9ccbe47dd194eeb0edaa3ae9edb76f5c8b20533f988bf2dd8b15eb4cfaa10c2f2f201d35d28f1cd9) - [Send email](https://www.gbif.org/api/feedback/user/mailto/5986a640eeb3a370eea3f59eedd2d393:cfcff3307278011d3588dc242a04c117e8c9a303e0ae45ddf053ede1c4a5b98e8c5865e3ab4f8352f0c8b70cfc2d9382e344d63490da28a1549523b6fb9943243f5436c2a2dd3fc766ba6ebb9f392ea68ffd92befad5d53f9ccbe47dd194eeb0edaa3ae9edb76f5c8b20533f988bf2dd8b15eb4cfaa10c2f2f201d35d28f1cd9)
System: Chrome 112.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7
Window size: width 2466 - height 1306
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-28T08:20:08.583Z',to:'2023-04-28T08:26:08.583Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-04-28T08:20:08.583Z',to:'2023-04-28T08:26:08.583Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Thanks @timhirsch, this should now be fixed.

**Comment by timhirsch** [comment]
It is @MattBlissett , thanks!
