### ISSUE TITLE
columns overlap

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4728]
**columns overlap**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3511394e66336cdcf8b9824e157055b4:73249fb2bffee53f90966952553eef186108c2c8d841a76c8c8c23458d2f832c2b3163413fa9c71ce9aba66e9f15132d194d0f0ee1c9cd49ad84acc7151fe047d41fa24ff62089d171db941ceae632ab1b5087c152d9ec2aa70692c02caf96ea) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3511394e66336cdcf8b9824e157055b4:73249fb2bffee53f90966952553eef186108c2c8d841a76c8c8c23458d2f832c2b3163413fa9c71ce9aba66e9f15132d194d0f0ee1c9cd49ad84acc7151fe047d41fa24ff62089d171db941ceae632ab1b5087c152d9ec2aa70692c02caf96ea)
System: Firefox 112.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/system-health
Window size: width 2560 - height 1307
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-01T00:38:32.268Z',to:'2023-05-01T00:44:32.268Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-01T00:38:32.268Z',to:'2023-05-01T00:44:32.268Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Not enough information to do anything. Will close for now. Feel free to provide more information so it can be reopened. (user contacted per email)
