### ISSUE TITLE
Add the New Zealand Marine Macroalgae Species Checklist to the GBIF backbone taxonomy

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4731]
**Add the New Zealand Marine Macroalgae Species Checklist to the GBIF backbone taxonomy**

@mdoering 
Could we add this checklist to the GBIF Backbone?

One of our publishers on heldpesk noticed that some of his records couldn't be matched to the backbone despite being accepted names (Codium dimorphum and Iridaea tuberculosa). When looking for these names, I noticed that they are both included in this checklist.
It looks like the authors did a thorough job here and although it is not a global checklist, it seems it would be adding many names.

Is this something we could consider?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/8d34bb95e6b6c33f2167caa9b739c326:1a4bf4e9d7a01a0b3d3b3f7bb7e442c80ce79c7f260348c53ed0b0f0ae08e8ddb085e2a00497ca4f19a6184b4397c2e405d2b82d93e4dcc01e3f17a3a9a69504f4c2155b19a482083db9702f41dc29835a46552844f0df67e86b01cf0d39f467698b369213ff543a6de7a48a5ff62f6bf479e6c3d41b1b413a07065f02faa25466cde7a6474faf8831f7c2078aa5aac2) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8d34bb95e6b6c33f2167caa9b739c326:1a4bf4e9d7a01a0b3d3b3f7bb7e442c80ce79c7f260348c53ed0b0f0ae08e8ddb085e2a00497ca4f19a6184b4397c2e405d2b82d93e4dcc01e3f17a3a9a69504f4c2155b19a482083db9702f41dc29835a46552844f0df67e86b01cf0d39f467698b369213ff543a6de7a48a5ff62f6bf479e6c3d41b1b413a07065f02faa25466cde7a6474faf8831f7c2078aa5aac2)
System: Safari 16.1.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/763a8aa3-65de-443e-bd20-bbe958a1ef74
Window size: width 1601 - height 828
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-02T14:55:44.759Z',to:'2023-05-02T15:01:44.759Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-02T14:55:44.759Z',to:'2023-05-02T15:01:44.759Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by mdoering** [comment]
That indeed looks like a good gap filler which we should include!

**Comment by mdoering** [comment]
Question would be on which level to include taxa. COL has very limited algae classifications and we created our own classification for algae at some point. Maybe we can even use the classification here as a starting point much higher up?
