### ISSUE TITLE
Images not showing properly in a checklist dataset

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#4732]
We published a checklist dataset [Especies presentes en el catálogo virtual del Tropicario del Jardín Botánico de Bogotá](https://www.gbif.org/dataset/ac93fa04-744a-44d0-8274-39775509ec3f) that have images for almost every species, but the portal only shows a broken square, as in this case [https://www.gbif.org/species/209562993](https://www.gbif.org/species/209562993).

I made a test in GBIF's IPT, using an occurrence dataset because I thought maybe that was the problem, but it is still not working. We uploaded one image to another repository (Internet Archive) and it works [https://www.gbif-uat.org/occurrence/3068585356](https://www.gbif-uat.org/occurrence/3068585356), so maybe is something related with the server of our publisher, but they told us there is no restriction in place to access that server.

We would like to ask if you know a reason for this problem, if there is something in GBIF infrastructure or if it is related to our publisher, so we can let them know and we can fix the issue.

Thanks for your help

**Comment by MattBlissett** [comment]
Hi Esteban,

The SSL configuration for jbb.gov.co is incomplete, see https://www.ssllabs.com/ssltest/analyze.html?d=jbb.gov.co&s=20.119.228.39&latest for example.  If the "Chain issues: incomplete" error is fixed the image should be displayed.

**Comment by EstebanMH-SiB** [comment]
Thank you very much @MattBlissett , I have transmited your response to their IT team and they will address the problem. Once it is done and the images are working, I will close this issue

**Comment by EstebanMH-SiB** [comment]
Our publisher chose to upload all images in another repository and now they are working, so I will close this issue. Thank you very much @MattBlissett for your help!
