### ISSUE TITLE
What's the difference between authorship in parentheses or not in ()?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4737]
**What&#39;s the difference between authorship in parentheses or not in ()?**

E.g., Poeciloneta dokutchaevi Eskov & Marusik, 1994 vs. Acanthoneta dokutchaevi (Eskov & Marusik, 1994)

And what does it mean when the genus is repeated and placed in parentheses? E.g., Molophilus (Molophilus) cyatheticolus (Alexander, 1950)

Thank you

-John

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3f89d0eb815d070ec582511a088338aa:969a85ad20aa2b774746a92dc1551ca8d0aad547d92ba95fa0ec172d116890cda7d5c930397b6d73fa89adf60b9226e5a299fcf4f4cbf73db36d67a95b53266691ab55fc9c489493ab18151fb56a0e72fdc0ff8890edb4cb02c1b1ed6e16bdb6444ec5d2b304bb5fe7ffaef8bfaf63ff1b2272ec57f384c1bb5fc49508fa9cd1b76c23830442e366250c536c95d459d8) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3f89d0eb815d070ec582511a088338aa:969a85ad20aa2b774746a92dc1551ca8d0aad547d92ba95fa0ec172d116890cda7d5c930397b6d73fa89adf60b9226e5a299fcf4f4cbf73db36d67a95b53266691ab55fc9c489493ab18151fb56a0e72fdc0ff8890edb4cb02c1b1ed6e16bdb6444ec5d2b304bb5fe7ffaef8bfaf63ff1b2272ec57f384c1bb5fc49508fa9cd1b76c23830442e366250c536c95d459d8)
System: Opera 98.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/2134612
Window size: width 1115 - height 709
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-06T23:57:03.932Z',to:'2023-05-07T00:03:03.932Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-06T23:57:03.932Z',to:'2023-05-07T00:03:03.932Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by timrobertson100** [comment]
Hi John,

The zoological naming convention is governed by the International Code of Zoological Nomenclature ([ICZN](https://www.iczn.org/the-code/the-code-online/)).  There is a nice summary by [NatureServe](https://help.natureserve.org/biotics/content/record_management/Scientific_Name/SN_Author.htm#:~:text=When%20a%20species%20has%20been,and%20the%20date%20in%20parentheses.) of some important aspects which answer the first question you have:

> When a species has been reassigned to a genus other than the original one, enclose the name of the author and the date in parentheses.

In the case of Molophius (Molophilus), I believe Curtis created a subgenus named Molophilus within the genus Molophilis in 1833. You can see this subgenus in the Catalogue of Life [here](https://www.catalogueoflife.org/?taxonKey=8GN6S)

I hope this helps.

> user notified per email

**Comment by jhnwllr** [comment]
I am closing this since the question is answered.
