### ISSUE TITLE
IUCN dataset has truncated order-class information

### ISSUE THREAD

**Issue by camiplata** [gbif/portal-feedback#4739]
Downloading the dataset, and having a closer inspection IUCN dataset has truncated order-class information, for some reason, the taxon.txt on the DwC-A does not bring standard column labels but is easy to spot that columns 5 and 6 are truncated.

See an example on GBIF for a Mammal species
<img width="442" alt="Captura de pantalla 2023-05-08 a la(s) 4 19 45 p m" src="https://user-images.githubusercontent.com/5700527/236937793-0eb66773-5401-4682-a759-8c7a172142f4.png">

[Having a quick look into the IUCN API ](https://apiv3.iucnredlist.org/api/v3/species/Thylacinus%20cynocephalus/?token=9bb4facb6d23f48efbf424bb05c0c1ef1cf6f468393bc745d42179ac4aca5fee) I  see that the information is correct, so  probably it is an issue from when the dataset was hosted by GBIF.

See a closer inspection in OpenRefine for Mammalia
<img width="1147" alt="Captura de pantalla 2023-05-08 a la(s) 4 29 15 p m" src="https://user-images.githubusercontent.com/5700527/236939277-d24ab89e-d7ee-4f52-80e7-040e81bb7b82.png">

**Comment by camiplata** [comment]
I see this issue has been manage with the ticket #4742, I have checked again and the problem has been fixed. Thank you GBIF team!!!

**Comment by MortenHofft** [comment]
Thanks @camiplata - I haven't changed anything myself, but will close the issue now that it has been fixed by someone.
