### ISSUE TITLE
API url not accessible

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#474]
**API url not accessible**

http://api.gbif.org/v1/occurence/search returns 404

-----
fbitem-f0bca0774a9c8eaecc8788650664fc5d3e0b6ba1
User provided contact info: banjankri
System: Chrome 61.0.3163 / Windows 10 0.0.0
Referer: https://www.gbif.org/developer/summary
Window size: width 2048 - height 1046
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-21T15:05:39.911Z',mode:absolute,to:'2017-09-21T15:11:39.911Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-21T15:05:39.911Z',mode:absolute,to:'2017-09-21T15:11:39.911Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Hi @banjankri,

You need to Rs in occurrence: http://api.gbif.org/v1/occurrence/search
