### ISSUE TITLE
Erroneous genus and species taxon - Agalaia centralis is a mispelling of Agelaia centralis

### ISSUE THREAD

**Issue by bdagley** [gbif/portal-feedback#4745]
Mispelled genus taxon: https://www.gbif.org/species/1310189

Mispelled species taxon: https://www.gbif.org/species/1310190 (there are 4 occurrence records)

The errors originate from Biologiezentrum Linz/ZOBODAT and may also be on COL.

Correct genus taxon: https://www.gbif.org/species/1310134

Correct species taxon: https://www.gbif.org/species/1310153

**Comment by bdagley** [comment]
Hi @MortenHofft @mdoering, I created several issues in the past that were later determined to be ideal to move to the https://github.com/CatalogueOfLife/data-vespoidea/issues repository. I'm wondering if you can move this issue and the ones listed below to the vespoidea repository. I could move them myself, although I don't seem to allowed to, but would prefer to be allowed to. Thank you.

https://github.com/gbif/portal-feedback/issues/4754
https://github.com/gbif/portal-feedback/issues/4744
https://github.com/gbif/portal-feedback/issues/4743
https://github.com/gbif/portal-feedback/issues/4679

**Comment by ManonGros** [comment]
@bdagley, I don't think we can transfer issues between repositories that don't belong to the same GitHub organisation. You would have to create new issues in the Catalogue of Life repository.

**Comment by mdoering** [comment]
Unfortunately that is true indeed. The issues need to be recreated and copy pasted

**Comment by bdagley** [comment]
Okay, that's fine. I'll copy and paste those four issues to add to the vespoidea COL repository. Also just to clarify, I created additional issues besides those four that don't need to move to the COL repositories.

**Comment by bdagley** [comment]
This issue is copied and pasted here (https://github.com/CatalogueOfLife/data-vespoidea/issues/19) as an open issue.
