### ISSUE TITLE
Duplicate mispelled genus Eustennogaster, should be existing genus Eustenogaster

### ISSUE THREAD

**Issue by bdagley** [gbif/portal-feedback#4748]
Mispelled genus: https://www.gbif.org/species/175306342
Mispelled species: https://www.gbif.org/species/175306342 (same link, 3 child taxa)
Also mispelled on COL, originating from ZOBODAT

Correct genus: https://www.gbif.org/species/175306342
Correct species: https://www.gbif.org/species/175306342 (same link, 3 child taxa)

**Comment by mdoering** [comment]
All the same link to genus Leptocheilus
