### ISSUE TITLE
Duplicate genus/subgenus issue for Fuscopolistes

### ISSUE THREAD

**Issue by bdagley** [gbif/portal-feedback#4750]
Fuscopolistes is supposed to be a subgenus of genus Polistes, but is displayed as it's own genus in addition to Polistes (https://www.gbif.org/species/8598058), under parent taxon "Eumenidae" (which should be family Vespidae: subfamily: Polistinae, or at least family Vespidae because Eumeninae is a different subfamily). Note: there are no records or child taxa listed under "genus Fuscopolistes."

Reference taxon: http://treatment.plazi.org/id/B67C1D44FF92204F4F9FF90AFE46F983

**Comment by bdagley** [comment]
@mdoering The issue doesn't seem to be fixed (https://www.gbif.org/species/4240), unless is there a delay before changes are reflected on GBIF?

**Comment by mdoering** [comment]
Yes, it is not deployed. This will take a few weeks

**Comment by bdagley** [comment]
Okay, that's great. I had asked about this on a few different pages, which can be disregarded now.
