### ISSUE TITLE
Duplicate genus Pseudepipona

### ISSUE THREAD

**Issue by bdagley** [gbif/portal-feedback#4751]
There are two genera with the same (correct) spelling, but only one has records. 

Note: these taxa as shown in GBIF differ in their authority name, which seems to have originated from the reference taxon each use, which may have caused this.

Taxon without records or child taxa: https://www.gbif.org/species/7454359 

Taxon with records: https://www.gbif.org/species/1333873

**Comment by mdoering** [comment]
Pseudepipona Dalla Torre really is used in the publication by Ebrahim Ebrahimi in Zootaxa 1785: 1–42 (2008):
https://doi.org/10.11646/zootaxa.1785.1.1

I am going to make it a synonym of de Saussure

**Comment by bdagley** [comment]
@mdoering Both genera are still shown as children of their parent taxon (https://www.gbif.org/species/4240), unless there's something I don't understand.
