### ISSUE TITLE
Invalid wasp genus Ancystrocerus

### ISSUE THREAD

**Issue by bdagley** [gbif/portal-feedback#4754]
Invalid genus taxon: https://www.gbif.org/species/10460484
This seems to originate from ZOBODAT, and is also incorrect on COL

I do not yet know which genus this was supposed to be. The following page lists a third valid genus as the accepted name for Ancystrocerus, and lists a second genus as the basionym for Ancystrocerus (https://www.gbif.org/species/5036802). The spelling is also similar to the valid existing genus Ancistrocerus.

Note also that Ancystrocerus is a valid beetle (not wasp) name (see: https://zookeys.pensoft.net/article/54196/).

**Comment by mdoering** [comment]
The backbone [Ancystrocerus](https://www.gbif.org/species/10460484) genus originates from IRMNG which still includes it as a homonym:
 - [Ancystrocerus Dalla Torre, 1894](https://www.irmng.org/aphia.php?p=taxdetails&id=1196317) [Family: Vespidae]
 - [Ancystrocerus Raffray, 1893](https://www.irmng.org/aphia.php?p=taxdetails&id=1374697) [Family: Staphylinidae]

COL only has a single genus in Coleoptera: https://www.checklistbank.org/dataset/9910/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Ancystrocerus&rank=genus&sortBy=taxonomic

**Comment by mdoering** [comment]
As we cannot synonymise the genus or species I am inclined to leave it as such in the backbone. Especially as there is a distinct authorship for both.

**Comment by bdagley** [comment]
I should have clarified this issue better. Despite that I mentioned a beetle genus, this only concerns the vespid genus Ancistrocerus, which is the correct spelling. I know that https://www.irmng.org/aphia.php?p=taxdetails&id=11060358 should be Ancistrocerus, because the same species shown on that page A. ornatus is shown on the following website near the bottom as Ancistrocerus ornatus (http://treatment.plazi.org/id/03FAB85D4275FFC237DEFF49FBF2FD4E). So, essentially what happened is Zobodat mispelled Ancistrocerus 4 or 5 times as different genera, all of which should only be Ancistrocerus.

**Comment by bdagley** [comment]
This issue was moved here (https://github.com/CatalogueOfLife/data-vespoidea/issues/22) as an open issue.
