### ISSUE TITLE
Dataset not updating 7eb54e10-fd36-4139-8764-1fd8abc2bd67 

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#4757]
I've made an update to this dataset https://www.gbif.org/dataset/7eb54e10-fd36-4139-8764-1fd8abc2bd67 

On the IPT https://ipt.gbif.no/resource?r=trh_f - change summary is "Add image/jpeg to format (instead of just jpeg)". It doesn't seem to update though.

On the registry it says Out of sync https://registry.gbif.org/dataset/7eb54e10-fd36-4139-8764-1fd8abc2bd67/crawling-history. If i try running a crawl from there it doesn't seem to update either. 

From the logs https://logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,to:now))&_a=(columns:!(_source),filters:!(),index:'24993300-fdb1-11ea-93de-b97c40066ce8',interval:auto,query:(language:lucene,query:'datasetKey.keyword:%227eb54e10-fd36-4139-8764-1fd8abc2bd67%22'),sort:!('@timestamp',desc)) it looks like it thinks the dwca is not modified?

**Comment by rukayaj** [comment]
Seems to be fixed...

**Comment by ManonGros** [comment]
Hi @rukayaj the page to keep an eye on for occurrence datasets would be this one: https://registry.gbif.org/dataset/7eb54e10-fd36-4139-8764-1fd8abc2bd67/ingestion-history (where it shows a successful ingestion). You don't need to worry about the "Out of sync" warning on the other page.
