### ISSUE TITLE
Downloads are in XML not CV, so can't open them

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4758]
**Downloads are in XML not CV, so can&#39;t open them**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ffe1a831c41d71eb640404c33ca5875e:89a4c59e916a90799d62194a3f22d1a16b81c8e57587c9ceef4343bda460884c711fdc1f0b56a7b2ead22648257b934f3596a36c6630dc19edcfb7ef80149137ca8a95f35e394ad1581dc1c1912fcb25ff09e74ae2d3142d486778432176290195cfbb0acf2a244a67b086be2f9f3dfb9d33bedf05329c00246999338d8356889f84fff5770892942994e6af94e61a49) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ffe1a831c41d71eb640404c33ca5875e:89a4c59e916a90799d62194a3f22d1a16b81c8e57587c9ceef4343bda460884c711fdc1f0b56a7b2ead22648257b934f3596a36c6630dc19edcfb7ef80149137ca8a95f35e394ad1581dc1c1912fcb25ff09e74ae2d3142d486778432176290195cfbb0acf2a244a67b086be2f9f3dfb9d33bedf05329c00246999338d8356889f84fff5770892942994e6af94e61a49)
System: Chrome 112.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0231234-230224095556074
Window size: width 1920 - height 904
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-11T00:11:58.463Z',to:'2023-05-11T00:17:58.463Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-11T00:11:58.463Z',to:'2023-05-11T00:17:58.463Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
> Replied by email

As far as I can see, the download format you selected is the Darwin Core Archive format which contains some tab-separated files as well as some XML files.
•	The file containing the occurrence record is the file named occurrence.txt (it is a tab-separated file).
•	The xml files in the “dataset” subfolder contains the metadata of the various datasets that had records included in your selection.
I suggest to work with the occurrence file.
You can learn more about the Darwin Core Archive download format here:
* https://www.gbif.org/faq?question=dwc-download
* https://www.gbif.org/faq?question=what-is-inside-a-gbif-download-zip-file

Note that you can select and download several species in one download. See this example via our web interface: https://www.gbif.org/occurrence/search?taxon_key=2421907&taxon_key=2421827&taxon_key=2421896&occurrence_status=present
