### ISSUE TITLE
Title vs. citation difference

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#476]
**Title vs. citation difference**

via Arthur Chapman:

The resource
https://www.gbif.org/document/80512/guide-to-best-practices-for-generalising-sensitive-species-occurrence-data
is documented wrongly on GBIF. The title is correct, but from then on "Sensitive Species Occurrence Data" has been replaced with "Primary Species Occurrence Data" including in the citation.

Data Quality again!

Cheers

Arthur

--
----------------------
Arthur Chapman
(Australian Biodiversity Information Services) PO Box 35 Ballan  Vic 3342 Australia
+61 (0)400 400 326

-----
fbitem-fe53e123cf5d5f7ea4ec8b4e436fb1d63845640e
User provided contact info: dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/document/80512/guide-to-best-practices-for-generalising-sensitive-species-occurrence-data
Window size: width 1534 - height 742
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-22T07:55:50.095Z',mode:absolute,to:'2017-09-22T08:01:50.095Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-22T07:55:50.095Z',mode:absolute,to:'2017-09-22T08:01:50.095Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Closing—I think I parsed what correction was being requested.
