### ISSUE TITLE
The bee Melissodes desponsa page should be combined with the Melissodes desponsus page

### ISSUE THREAD

**Issue by bdagley** [gbif/portal-feedback#4763]
Melissodes desponsus Smith 1854 is the valid taxon (https://www.gbif.org/species/5040668).
Melissodes desponsa Smith 1854 is an invalid synonym (https://www.gbif.org/species/11064068). 
Both pages cite ITIS as the reference taxon.

**Comment by mdoering** [comment]
M. desponsa is a synonym of M. desponsus in both the backbone and ITIS
