### ISSUE TITLE
Millipedes still in the ocean - is a fix not possible?

### ISSUE THREAD

**Issue by Mesibov** [gbif/portal-feedback#4764]
Please see 
https://github.com/gbif/backbone-feedback/issues/192

The issue has been closed, but Diplopoda occurrence records still include the colonial hydrozoans incorrectly called  "Siphonophora" (see image below). Is it not possible to fix this?

![Diplopoda_2023-05-13](https://github.com/gbif/portal-feedback/assets/16182234/84c798a2-a8d1-4e50-a2b8-22994bac110a)

**Comment by mdoering** [comment]
I have implemented the nub key exclusion filter for species matching which pipelines can make use of. Datasets can then be configured to exclude for example any matches to millipedes.

**Comment by mdoering** [comment]
duplicate of gbif/backbone-feedback#192
