### ISSUE TITLE
Download API 401 Error

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4766]
**Download API 401 Error**

Hello, my name is junior (user:juniorq1995) and I am attempting to use the Download API but am running into issues. just attempting the default:
curl --include --user juniorq1995:PASSWORD --header "Content-Type: application/json" --data @query.json https://api.gbif.org/v1/occurrence/download/request

with PASSWORD set and the query.json file defined results in a 401 error being returned. Can you connect me with someone who can help me troubleshoot this error?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4da39be8ced2d2c182fddd79f6935079:8c8f7ed266242998d2fa855b40d37de50d515b2bb25a2d25b25a5fc2a9315f7e144b3b1cc15a5275f17012342e39fa707ee53782d8291016edceb7d5aaf077a1952bde1fc4b3b28fb335eed020ce86202f18080590e9f1e75e0e35f1d90d6338) - [Send email](https://www.gbif.org/api/feedback/user/mailto/4da39be8ced2d2c182fddd79f6935079:8c8f7ed266242998d2fa855b40d37de50d515b2bb25a2d25b25a5fc2a9315f7e144b3b1cc15a5275f17012342e39fa707ee53782d8291016edceb7d5aaf077a1952bde1fc4b3b28fb335eed020ce86202f18080590e9f1e75e0e35f1d90d6338)
System: Chrome 108.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1846 - height 975
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-16T03:27:58.714Z',to:'2023-05-16T03:33:58.714Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-16T03:27:58.714Z',to:'2023-05-16T03:33:58.714Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
(responded via helpdesk)
