### ISSUE TITLE
Reduce data from backbone

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4767]
**Reduce data from backbone**

Hello!

I would like to use the data from the taxonomy backbone of GBIF. Unfortunatly the files are too large to open them with the software I have installed. Is there a way to reduce the size of the files (e.g. by selecting the country first and download only the taxa from a single country or to split up the groups, so that I can download only the beetles or only birds?) 

Thank you and kind regards
Teresa Knoll

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/669f78a15cfe87195faef4aa20880b77:43713f3e492c63c98107ad3c387c7e8af64a342dd13c956bb312563da58305f08a8a1cb03b99f8899717bfa370b0737b5c0f48b859d81c8ba9ee364999c6bdfeb94b5e7ebd9216874014663857f0b1f2a9646a3cd2046f2ba6e41d698e85620c) - [Send email](https://www.gbif.org/api/feedback/user/mailto/669f78a15cfe87195faef4aa20880b77:43713f3e492c63c98107ad3c387c7e8af64a342dd13c956bb312563da58305f08a8a1cb03b99f8899717bfa370b0737b5c0f48b859d81c8ba9ee364999c6bdfeb94b5e7ebd9216874014663857f0b1f2a9646a3cd2046f2ba6e41d698e85620c)
System: Chrome 112.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=back%20bone
Window size: width 1920 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-16T07:18:06.651Z',to:'2023-05-16T07:24:06.651Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-16T07:18:06.651Z',to:'2023-05-16T07:24:06.651Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Contacted by email

The GBIF backbone taxonomy only contains scientific names for various taxon ranks and relationship between those names (parent taxon, synonyms, etc.)
It doesn’t contain any location information about where species occur.

With that in mind, you can download part of the GBIF Backbone taxonomy via ChecklistBank: https://www.checklistbank.org/dataset/53147/download. You can select any taxon root you would like as well as a download format.

If you are interested in occurrences available on GBIF (observation or collection of a specimen at a given time and a given place), you can use our occurrence search and download interface: https://www.gbif.org/occurrence/search?occurrence_status=present&q=. This will allow you to select occurrences based on continent, country, administrative areas, etc. and select one or several taxa.
To learn more about what you can do on the website, you can check [our Data Use Club recorded webinar on the topic](https://www.gbif.org/composition/4Xm5cVB4y9n7U1GlUtKx8Q/data-use-club-practical-session-1-recording-and-resources). You can also access GBIF data via our API, you are very welcome to watch [our Data Use Club recorded webinar on introducing to the GBIF API](https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa/data-use-club-practical-session-3-recording-and-resources).

Note that the next Data Use Club webinar on Wednesday is about the GBIF Backbone taxonomy. You can find the registration page [here](https://www.gbif.org/event/42jbz2tRyrjzTF5B8pClKa/data-use-club-practical-sessions-name-matching-and-the-gbif-taxonomic-backbone).
