### ISSUE TITLE
DOI fails

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#477]
**DOI fails**

DOI https://doi.org/10.15472/ciasei  in the example for INdividual checklist does not work

-----
fbitem-57ee03dd725ec36a7faf1f69bca70ff2ef3c507e
User provided contact info: dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/citation-guidelines
Window size: width 1920 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-22T12:10:24.583Z',mode:absolute,to:'2017-09-22T12:16:24.583Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-22T12:10:24.583Z',mode:absolute,to:'2017-09-22T12:16:24.583Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
It does work, but the "foo@gbif.org" email address should be changed.

**Comment by MattBlissett** [comment]
And gbif.org should probably be "https://www.gbif.org" (and https for the other examples).
