### ISSUE TITLE
The validation report can't be finished, it stops at Data interpret.ed step

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4775]
**The validation report can&#39;t be finished, it stops at Data interpret.ed step**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/17f27a3a1392dd918192525a0ba0fe77:fc1f3c8aa7d267b7d6e6736f9e55ad145b03fa9a725c036008d36fc4dad57c3e92e5dc1d3cec0dcdda5b320197d12bf00c985a2fc9d9ba272151584221f0fae15633d8db4fc8ae1c58805e5bda5a66677f019377dd77f472ecdd590ab96b57ca) - [Send email](https://www.gbif.org/api/feedback/user/mailto/17f27a3a1392dd918192525a0ba0fe77:fc1f3c8aa7d267b7d6e6736f9e55ad145b03fa9a725c036008d36fc4dad57c3e92e5dc1d3cec0dcdda5b320197d12bf00c985a2fc9d9ba272151584221f0fae15633d8db4fc8ae1c58805e5bda5a66677f019377dd77f472ecdd590ab96b57ca)
System: Chrome 113.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/tools/data-validator/af3cb2a0-4446-409a-959e-ab3b195adc4b
Window size: width 1536 - height 714
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-19T13:57:25.228Z',to:'2023-05-19T14:03:25.228Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-19T13:57:25.228Z',to:'2023-05-19T14:03:25.228Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by muttcg** [comment]
Validator link shows that validation was completed successfully
