### ISSUE TITLE
How can i get a list of all the species on the gbif website

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4776]
**How can i get a list of all the species on the gbif website**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/440685bce5149fc60c756cedd7fd421d:9a18f67950272a50cd80dac301499bab22c292c0fa62ffcc7a3b73557a741f15053df920b2e6e773406cc574982644ee409ce8c6c054cb6e0e927bf70caf6ff223fce223dd79daa28bc9f0b1497ebe6385e7cc842415ea22b8ec4ab5d2c79208070f9e6be2a3ad2623b1d13cc8c8f2e5e515849c5be2c3059107734788dd884489a98b6f6aa2fd52c6c51684a35c3aad) - [Send email](https://www.gbif.org/api/feedback/user/mailto/440685bce5149fc60c756cedd7fd421d:9a18f67950272a50cd80dac301499bab22c292c0fa62ffcc7a3b73557a741f15053df920b2e6e773406cc574982644ee409ce8c6c054cb6e0e927bf70caf6ff223fce223dd79daa28bc9f0b1497ebe6385e7cc842415ea22b8ec4ab5d2c79208070f9e6be2a3ad2623b1d13cc8c8f2e5e515849c5be2c3059107734788dd884489a98b6f6aa2fd52c6c51684a35c3aad)
System: Chrome 113.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/search?advanced=1
Window size: width 1920 - height 929
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-19T14:46:12.014Z',to:'2023-05-19T14:52:12.014Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-19T14:46:12.014Z',to:'2023-05-19T14:52:12.014Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
(responded via helpdesk)
