### ISSUE TITLE
Dataset search show the number of occurrences, but not species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#478]
**Dataset search show the number of occurrences, but not species**

When searching for checklist datasets one can see the number of included occurrences, but not the main number core Taxon records. Please add number of taxa to the search results

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c

System: Chrome 60.0.3112 / Mac OS X 10.12.5
Referer: https://www.gbif.org/dataset/search?type=CHECKLIST&publishing_org=7ce8aef0-9e92-11dc-8738-b8a03c50a862
Window size: width 1840 - height 1008
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-22T15:32:24.032Z',mode:absolute,to:'2017-09-22T15:38:24.032Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-22T15:32:24.032Z',mode:absolute,to:'2017-09-22T15:38:24.032Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/eab6313f501e3c402a9ff0f7ccf9de6b655e3781
