### ISSUE TITLE
basisOfRecord is turning RED in GBIF IPT

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4785]
**basisOfRecord is turning RED in GBIF IPT**

Hi, I was working to deposit a data through GBIF IPT for Pensoft journal, but I noticed that the 'basisOfRecord' part is turning to RED and causing a problem with my data deposition. Please advice what this means.

Thanks in advance!

Cheers,
Kriz

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fb7db0d09d7cc3365d80cbfc847212dd:cf540e4f7978d9e44a63e142ba005af3e1cb8d7c644365dfb2a275a7f66ed0b99e8e66b9e0e6c5039ffd2792c58bb4f5af83149c94fa47b593a0b2e08a62d1c107ddf65d2f28f7570e879389a68cf422d84af73095fdc37eed96a6399203f45df98b68b10a3cd5e5c491ffad642b9d32252990aba43c48cad7fe8c4e7bd47c337f8b5093289404362a95630ae5c1b67e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/fb7db0d09d7cc3365d80cbfc847212dd:cf540e4f7978d9e44a63e142ba005af3e1cb8d7c644365dfb2a275a7f66ed0b99e8e66b9e0e6c5039ffd2792c58bb4f5af83149c94fa47b593a0b2e08a62d1c107ddf65d2f28f7570e879389a68cf422d84af73095fdc37eed96a6399203f45df98b68b10a3cd5e5c491ffad642b9d32252990aba43c48cad7fe8c4e7bd47c337f8b5093289404362a95630ae5c1b67e)
System: Chrome 113.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/faq
Window size: width 1440 - height 789
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-29T12:26:26.678Z',to:'2023-05-29T12:32:26.678Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-29T12:26:26.678Z',to:'2023-05-29T12:32:26.678Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
The letters turn into red on the IPT when you go through the Darwin Core Mappings and it is normal.
https://ipt.gbif.org/manual/en/ipt/latest/manage-resources#darwin-core-mappings

Please let me know if you have any questions.
