### ISSUE TITLE
Cydista aequinoctialis Vahl is a made up taxon

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#479]
**Cydista aequinoctialis Vahl is a made up taxon**

One for @mdoering I'm pretty sure _Cydista aequinoctialis_ Vahl is a made up taxon. There is a _Cydista aequinoctialis_ Miers, http://www.ipni.org/ipni/idPlantNameSearch.do?id=109402-1 but not a 

It's source is given as the GBIF Type Specimen Names checklist. Looking at one of the types for this name https://api.gbif.org/v1/occurrence/466629461/fragment we see that the "fieldNotes" field has "Symb. Bot. 3: 80 (1794) On back of sheet: HB. SCHUM.  Bignonia spectabilis  Bignonia Vahl. Symb.3.  On sheet: Cotypus" I think somehow the authorship details for _Bignonia spectabilis_ have gotten merged with the name _Cydista aequinoctialis_ . There is the combination _Bignonia aequinoctialis_ var. _spectabilis_ (Vahl) DC I suspect the data provider has mangled this record, which is why GBIF ends up with a spurious taxon.

-----
fbitem-species8781200
User provided contact info: rdmpage
System: Safari 10.0.2 / Mac OS X 10.10.5
Referer: https://www.gbif.org/species/8781200
Window size: width 1338 - height 912
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-23T17:46:35.698Z',mode:absolute,to:'2017-09-23T17:52:35.698Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-23T17:46:35.698Z',mode:absolute,to:'2017-09-23T17:52:35.698Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ManonGros** [comment]
Looks solved.
