### ISSUE TITLE
Map - suspicious coordinates

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4790]
**Map - suspicious coordinates**

Hello,

I have just seen the message "This map contains occurrences flagged by GBIF as having suspicious coordinates. [Hide them]".

I'd like to know what this corresponds to.
Are these occurrences far from the normal range of the species? Or do they correspond to inconsistencies in the raw data (e.g. country code that doesn't match the coordinates)?

Best regards,

Antoine

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ecf68844c21bd8d1e9a1a84d69569736:29dd46b845271ff1a0e27e11d5e9dc9f454adff887326d5e5eca753939778489de0656e9fe064bebe9d8cd069df52383ed849a1151210d3e7b07ef67b46cea7f16dfd1f3bbda0216192a9ea294f97d8d162868be4e5db4e26480b61005eb07361118abe6f85f0cc1189d49eb44e699627ae37cc3dd7ae94106b1310bf6639c0d94bf5ba7f5950a4b310a4e51dad928b5) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ecf68844c21bd8d1e9a1a84d69569736:29dd46b845271ff1a0e27e11d5e9dc9f454adff887326d5e5eca753939778489de0656e9fe064bebe9d8cd069df52383ed849a1151210d3e7b07ef67b46cea7f16dfd1f3bbda0216192a9ea294f97d8d162868be4e5db4e26480b61005eb07361118abe6f85f0cc1189d49eb44e699627ae37cc3dd7ae94106b1310bf6639c0d94bf5ba7f5950a4b310a4e51dad928b5)
System: Firefox 113.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/fr/
Window size: width 1920 - height 899
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-30T12:41:29.496Z',to:'2023-05-30T12:47:29.496Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-30T12:41:29.496Z',to:'2023-05-30T12:47:29.496Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
(responded via helpdesk, but the answer is below for anyone stumbling upon this) 

GBIF removes common geospatial issues by default if you choose to have data with a location.

The following things will be removed:

Zero coordinate : Coordinates are exactly (0,0). [null island](https://en.wikipedia.org/wiki/Null_Island)
Country coordinate mismatch : The coordinates fall outside of the given country’s polygon.
Coordinate invalid : GBIF is unable to interpret the coordiantes.
Coordinate out of range : The coordinates are outside of the range for decimal lat/lon values ((-90,90), (-180,180)).
You can do this on the [web portal](https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&occurrence_status=present).
