### ISSUE TITLE
I need to download the dates with problems. For example, I have 865 invalid dates but I can't see all

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4792]
**I need to download the dates with problems. For example, I have 865 invalid dates but I can&#39;t see all**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8f4d460525df12717c3d946a6a16723b:5b3694fbd6f85a97aa47149b7827b1959f5894da78c73934ba692256d00c76b989c99186d06e614f5c62537bad4eb1c899c629e02cd0e7ec37a7ac4ce530f1ac39421d3ed4b3fae06ff6fc4dcdba20288f5141f5745a1171ef8639ba68acefbf) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8f4d460525df12717c3d946a6a16723b:5b3694fbd6f85a97aa47149b7827b1959f5894da78c73934ba692256d00c76b989c99186d06e614f5c62537bad4eb1c899c629e02cd0e7ec37a7ac4ce530f1ac39421d3ed4b3fae06ff6fc4dcdba20288f5141f5745a1171ef8639ba68acefbf)
System: Chrome 113.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/tools/data-validator/54dcb434-2fec-4307-909e-dcb58c01a159
Window size: width 2133 - height 977
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-31T00:33:59.446Z',to:'2023-05-31T00:39:59.446Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-31T00:33:59.446Z',to:'2023-05-31T00:39:59.446Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
(responded via helpdesk)
