### ISSUE TITLE
How do you search species by state?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4799]
**How do you search species by state?**

How do you search species by state?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e104e6244d0eb75da85d8fb145715131:6e05dd0e31f18254a39e3f2587b0ba4b5e45b8b8a6babb3af3ec3aaa9acfa7ce347ec9597ede89ded8204aee2d4add6d7244bcc9670e4daac962d4ec5fbfa592e8e76a557d187891391c7afa69398eaa08ab8f04b2091dbb7127a05467b0420b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/e104e6244d0eb75da85d8fb145715131:6e05dd0e31f18254a39e3f2587b0ba4b5e45b8b8a6babb3af3ec3aaa9acfa7ce347ec9597ede89ded8204aee2d4add6d7244bcc9670e4daac962d4ec5fbfa592e8e76a557d187891391c7afa69398eaa08ab8f04b2091dbb7127a05467b0420b)
System: Chrome 113.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?q=Cicindela%20hirticollis%20corpuscula
Window size: width 1280 - height 601
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-05T22:20:32.031Z',to:'2023-06-05T22:26:32.031Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-05T22:20:32.031Z',to:'2023-06-05T22:26:32.031Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
(responded via helpdesk)

**Comment by jhnwllr** [comment]
I am responding to the question asked here: 
https://github.com/gbif/portal-feedback/issues/4799

The best way to search for occurrences by USA state is by using the gadm filter. 
https://www.gbif.org/occurrence/map?advanced=1&occurrence_status=present&gadm_gid=USA.44_1&gadm_gid=USA.21_1&gadm_gid=USA.10_1

Here I can search for Texas, Florida, and Maryland. 

You can find the gadm filter on the occurrence search portal under advanced.
