### ISSUE TITLE
Publisher page: wrong occurrences count ?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#48]
**Publisher page: wrong occurrences count ?**

On the publisher page, the first line details the number of published datasets (correct) and counts the associated occurrences.

For a [specific publisher](https://demo.gbif.org/publisher/2cd829bb-b713-433d-99cf-64bef11e5b3e), the occurrences count seems to be wrong (8 396): 

This count is rather different on the [production software](http://www.gbif.org/publisher/2cd829bb-b713-433d-99cf-64bef11e5b3e) (7 090 471): 

It seems however right for other publishers:
https://demo.gbif.org/publisher/10980920-6dad-11da-ad13-b8a03c50a862

http://www.gbif.org/publisher/10980920-6dad-11da-ad13-b8a03c50a862

-----
fbitem-publisher2cd829bb-b713-433d-99cf-64bef11e5b3e
Reported by: @bdulac
System: Opera 42.0.2393 / Windows 8.1 0.0.0
Referer: https://demo.gbif.org/publisher/2cd829bb-b713-433d-99cf-64bef11e5b3e
Window size: width 1280 - height 909
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-23T12:52:26.956Z',mode:absolute,to:'2017-01-23T12:58:26.956Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-23T12:52:26.956Z',mode:absolute,to:'2017-01-23T12:58:26.956Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you for reporting this in such detail

Those two numbers are calculated in different ways. The most precise and up to date count is  is the one used on the demo site and what will be used in the future.

But there was a small bug. It has been corrected with https://github.com/gbif/occurrence/commit/90648b90328c0b7126f786a698040359f5e413ef
 The same error affects counts on the production site that also shows [8 396](http://www.gbif.org/occurrence/search?publishingOrg=2cd829bb-b713-433d-99cf-64bef11e5b3e)
