### ISSUE TITLE
Last Modified 26 August 2016

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#480]
**Last Modified 26 August 2016**

Itr is stated that the Backbone has been modified in August 2016. In discussion with Markus it turns out this should be February 2017. Something is up here with the date provided.

-----
fbitem-datasetd7dddbf4-2cf0-4f39-9b2a-bb099caae36c
User provided contact info: olafbanki
System: Chrome 60.0.3112 / Windows 7 0.0.0
Referer: https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
Window size: width 1242 - height 589
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-24T12:39:18.434Z',mode:absolute,to:'2017-09-24T12:45:18.434Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-24T12:39:18.434Z',mode:absolute,to:'2017-09-24T12:45:18.434Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
Updated the EML just now (see gbif/registry#27)
