### ISSUE TITLE
Next upload for eBird

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4805]
**Next upload for eBird**

Hi There, 

I see that eBird was last updated in March 2022 for all data up to 31 December 2021. Will the dataset for 2022 be uploaded soon?

Thanks,
Dan

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/345e94b5f8c588a2a6508696610d5718:84e459f28bdc291ffc1513385728638eb8973fd4607ac2dfbd0782322fbc2f4c60e99df8e2c50d4ae2c060b918d65ad5ac82469a6cb2f1a56bb0ee59028cf1bee94dd5f66b5d821f745a1b4343f062917ac202f73fbe38119022b2363c0f8076) - [Send email](https://www.gbif.org/api/feedback/user/mailto/345e94b5f8c588a2a6508696610d5718:84e459f28bdc291ffc1513385728638eb8973fd4607ac2dfbd0782322fbc2f4c60e99df8e2c50d4ae2c060b918d65ad5ac82469a6cb2f1a56bb0ee59028cf1bee94dd5f66b5d821f745a1b4343f062917ac202f73fbe38119022b2363c0f8076)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e
Window size: width 1920 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-08T04:48:51.702Z',to:'2023-06-08T04:54:51.702Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-08T04:48:51.702Z',to:'2023-06-08T04:54:51.702Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by timrobertson100** [comment]
Cornell has informed us they'll update "soon". I don't think it is expected within the next couple of weeks, but I would anticipate it within the next couple of months.

I hope this helps.
