### ISSUE TITLE
Decapod checklist import leading to several "spec" listed as accepted

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4807]
**Decapod checklist import leading to several &quot;spec&quot; listed as accepted**

An imported checklist via Plazi is leading to at least 75 records that all seem spuriously listed, e.g. 
"Alpheopsis spec Chace, 1972"
Under Accepted

This and many others could be tolerable if the authorship were not assigned to a "spec." and it were unranked. 

Checklist of the Decapods (Crustacea) from the outer continental shelf and seamounts from Northeast of Brazil REVIZEE Program (NE III)

https://www.gbif.org/dataset/2c234fee-9c05-4a6c-bd50-438312240644

Looking inside the files downloadable,
Inside the file taxa.txt under scientific names for the above example are [Seemingly misformatted with capitalization and the author data attached.]
Alpheopsis Labis Chace 1972
Alpheopsis Trigonus (Rathbun 1901)

which in the paper itself provide new records for two accepted valid species, namely
Alpheopsis labis Chace, 1972
Alpheopsis trigonus (Rathbun, 1901)

So presumably one or both these entries are misformatted for import, alongside many others, leading to many "spec".
Inside the data Brachyura, linked to completely wrong higer taxonomy for it of "Reptilia, Squamata, Colubridae", rather surprising annotation for a paper on marine Crustacea, especially as that's a crab genus.

From the files, it looks like could've been a quick job to correct such issues of apparent errors in the files - which seem machine generated - if done before import to gbif. I wonder how many other automated imports with such low overlap to backbone have been imported unchecked.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3153a8df00a5c92ad268440eed0302c4:2dfb97e9049d60508421de9a1360fab44f8a152b764461b8a8857b1f0e297cfbff351f9117bf3d1b86c05a6b3841a00eb6a94f9dada66a68ed514bfd9821a78bf73f86c288dd1e10be3148d000780114b3c746bb4a088ba40b9256e36cb1bc655300e292f7e7c62d4081ccb231729268f6d3cb71022947ae89b122471026f7c8) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3153a8df00a5c92ad268440eed0302c4:2dfb97e9049d60508421de9a1360fab44f8a152b764461b8a8857b1f0e297cfbff351f9117bf3d1b86c05a6b3841a00eb6a94f9dada66a68ed514bfd9821a78bf73f86c288dd1e10be3148d000780114b3c746bb4a088ba40b9256e36cb1bc655300e292f7e7c62d4081ccb231729268f6d3cb71022947ae89b122471026f7c8)
System: Safari 16.3.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/2c234fee-9c05-4a6c-bd50-438312240644
Window size: width 1158 - height 714
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-10T09:03:34.390Z',to:'2023-06-10T09:09:34.390Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-10T09:03:34.390Z',to:'2023-06-10T09:09:34.390Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
reported to PLAZI
