### ISSUE TITLE
I am trying to download occurrences in R using occ_download() so that I can properly cite GBIF; however, I keep getting and error that says "Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) :    HTTP/2 stream 3 was not closed cleanly before end of the underlying stream" I cant find help online.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4812]
**I am trying to download occurrences in R using occ_download() so that I can properly cite GBIF; however, I keep getting and error that says &quot;Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : HTTP/2 stream 3 was not closed cleanly before end of the underlying stream&quot; I cant find help online.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/428b91e8ef51b3283bc2a0fbf542752e:c11d655d01e2f523f09ea42be835733c9be1f719fae6b000518fe6bc8c635d2f30152a4d9fe2e0994abba5b173df26abb44dc1793c052c1487333fecf73d7811f37f15ce1c8f29331f690860918ffe4b013ab9766ea8b49e3472156c7c8321d81ab38c9a66a0dc0bdaa6dec2c0eaaa4fb1d5e15e338ac55a5215cdd25a7254b4fceb7da4c892c22e1fcc61e7048ca3cc) - [Send email](https://www.gbif.org/api/feedback/user/mailto/428b91e8ef51b3283bc2a0fbf542752e:c11d655d01e2f523f09ea42be835733c9be1f719fae6b000518fe6bc8c635d2f30152a4d9fe2e0994abba5b173df26abb44dc1793c052c1487333fecf73d7811f37f15ce1c8f29331f690860918ffe4b013ab9766ea8b49e3472156c7c8321d81ab38c9a66a0dc0bdaa6dec2c0eaaa4fb1d5e15e338ac55a5215cdd25a7254b4fceb7da4c892c22e1fcc61e7048ca3cc)
System: Chrome 113.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/
Window size: width 1255 - height 603
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-14T03:02:00.766Z',to:'2023-06-14T03:08:00.766Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-14T03:02:00.766Z',to:'2023-06-14T03:08:00.766Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
https://github.com/ropensci/rgbif/issues/579

**Comment by jhnwllr** [comment]
(responded via helpdesk)
