### ISSUE TITLE
Is the plant species name in gbif adopting Taxonomic Name Resolution Service?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4813]
**Is the plant species name in gbif adopting Taxonomic Name Resolution Service?**

Is the plant species name in gbif adopting Taxonomic Name Resolution Service?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/dfe8381f429012fc89b1836cbce3e9c6:18c991422bc715b16f6015bd044639816d3afacfb4b1372932fd686343a38e0d3a668583782651ee3ac5836d2d1bcde25f3c1b603f8976cb19f679559251f3ed78972d8f159c7e8543a6181a2cc07b3ad884968546e228b4e71fbcd566bbf795) - [Send email](https://www.gbif.org/api/feedback/user/mailto/dfe8381f429012fc89b1836cbce3e9c6:18c991422bc715b16f6015bd044639816d3afacfb4b1372932fd686343a38e0d3a668583782651ee3ac5836d2d1bcde25f3c1b603f8976cb19f679559251f3ed78972d8f159c7e8543a6181a2cc07b3ad884968546e228b4e71fbcd566bbf795)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/tool/81741/taxonomic-name-resolution-service-tnrs
Window size: width 1920 - height 937
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-14T16:29:33.397Z',to:'2023-06-14T16:35:33.397Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-14T16:29:33.397Z',to:'2023-06-14T16:35:33.397Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: CRITICAL

**Comment by ktotsum** [comment]
Taxonomic Name Resolution Service is not used in GBIF. We use GBIF species API for searching names.
https://www.gbif.org/developer/species#searching

Here are some tools and tutorials on species that might help you.

Species matching tool
https://www.gbif.org/tools/species-lookup

Data Use Club Practical Sessions: Name matching and the GBIF Taxonomic Backbone
https://www.gbif.org/event/42jbz2tRyrjzTF5B8pClKa/data-use-club-practical-sessions-name-matching-and-the-gbif-taxonomic-backbone

You can check more tutorials in Data Use Club.
https://www.gbif.org/data-use-club
