### ISSUE TITLE
how do I generate an API for the Catalogue of Life checklist?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4816]
**how do I generate an API for the Catalogue of Life checklist?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0bfdc2e7cdd06ab6a40100c476fd57cb:3c475dd2139e53b12cfdcd9e92dce0e27059239d8398a71c107fa37b7c3220235c94c2e165ad90df81c122c77a36c528c2f41dddbee13fc6c5ccc49847115d41ba78b9e196ad0cd01b0f076f17396643d0dda79d16185eafb78336053346a620) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0bfdc2e7cdd06ab6a40100c476fd57cb:3c475dd2139e53b12cfdcd9e92dce0e27059239d8398a71c107fa37b7c3220235c94c2e165ad90df81c122c77a36c528c2f41dddbee13fc6c5ccc49847115d41ba78b9e196ad0cd01b0f076f17396643d0dda79d16185eafb78336053346a620)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/7ddf754f-d193-4cc9-b351-99906754a03b
Window size: width 1025 - height 1809
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-15T12:55:30.288Z',to:'2023-06-15T13:01:30.288Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-15T12:55:30.288Z',to:'2023-06-15T13:01:30.288Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
Catalogue of Life Checklist Bank API
https://api.checklistbank.org/

Catalogue of life can also be accessed from the GBIF Species API
https://www.gbif.org/developer/species
for example,
https://api.gbif.org/v1/species/search?datasetKey=7ddf754f-d193-4cc9-b351-99906754a03b

You can find more information about GBIF species API in our blog.
https://data-blog.gbif.org/post/gbif-species-api/
