### ISSUE TITLE
Modification on a occurrence Dataset data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4819]
**Modification on a occurrence Dataset data**

Hi,
I'm the curator of CIRAD herbarium, member of Recolnat consortium. I contact you about this dataset :  https://www.gbif.org/dataset/18ae6f32-c82b-4065-a0aa-4167be45c78e. I found some little mistakes on the metadata, what is the process for correcting it ?
Many thanks in advance for your assistance.
Have a pleasant day
Samantha Bazan
Samantha.bazan@cirad.fr

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0a606ce946b1266da5b2c31ba116b861:050ba36cc68bc3c9b1a5caa4c290d37fa2ab5323528c0a1e78c1d3818392063380c7f96fff7728e17847b8ec59346b6695621d9f49b7a1e5ca72975a1835f2749dbdcde5ad6666be6806cf78d79daf2e0952cbe64b2c794ea60214e55d49909adb1e590c3a7afd9f52fb5a3d1bd738ef) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0a606ce946b1266da5b2c31ba116b861:050ba36cc68bc3c9b1a5caa4c290d37fa2ab5323528c0a1e78c1d3818392063380c7f96fff7728e17847b8ec59346b6695621d9f49b7a1e5ca72975a1835f2749dbdcde5ad6666be6806cf78d79daf2e0952cbe64b2c794ea60214e55d49909adb1e590c3a7afd9f52fb5a3d1bd738ef)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/18ae6f32-c82b-4065-a0aa-4167be45c78e
Window size: width 1745 - height 852
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-19T07:36:39.243Z',to:'2023-06-19T07:42:39.243Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-19T07:36:39.243Z',to:'2023-06-19T07:42:39.243Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
If you notice any mistake on a dataset page, the dataset metadata needs to be updated at the source. In this case, you or someone else need to log in the RECOLNAT IPT and edit this resource: https://ipt.recolnat.org/resource?r=erecolnat_alf

> replied by email
