### ISSUE TITLE
Examples of an observation of multiple species / organism simultaneously

### ISSUE THREAD

**Issue by oolonek** [gbif/portal-feedback#4823]
We are looking for examples of an observation in GBIF of multiple species/organisms simultaneously.
E.g. a soil sample collected by user U at location L on date D, contains  species [A, B, C and D]

Are such type of observations existing at GBIF ?

**Comment by MortenHofft** [comment]
Perhaps this sampling event https://www.gbif.org/dataset/aea17af8-5578-4b04-b5d3-7adf0c5a1e60/event/a658c0dd-6611-4cf4-b4fe-b1a2d7c4ef65
that resulted in these occurrences https://www.gbif.org/occurrence/search?dataset_key=aea17af8-5578-4b04-b5d3-7adf0c5a1e60&advanced=1&event_id=a658c0dd-6611-4cf4-b4fe-b1a2d7c4ef65

I found that using the dataset seach and a filter on sampling events.
Here is another entering random string in the eventID filter on occurrence search
https://www.gbif.org/occurrence/search?advanced=1&event_id=AB%200423%20B1 (and confirmed that the occurrences didn't come from multiple datasets)

Did that help?

**Comment by oolonek** [comment]
Thanks a lot ! This is exactly what we were looking for. Will dig your examples and the searches proposed.
