### ISSUE TITLE
Dear GBIF;

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4824]
**Dear GBIF;**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a7f752152e4af0e057d71c5d8cdbcedc:67839ae685e1644a1b5fc4952cee3980225baa7ab742eeb268e90e6722f94ac612194ce4bfed2ea2346b20f91b6ebb4912cce87dbc369496d387d082cfe5a8a0f63f9aed8941efe1fdc274cb00c597c586b51ec01b7519615ebffbd60dbc2a24) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a7f752152e4af0e057d71c5d8cdbcedc:67839ae685e1644a1b5fc4952cee3980225baa7ab742eeb268e90e6722f94ac612194ce4bfed2ea2346b20f91b6ebb4912cce87dbc369496d387d082cfe5a8a0f63f9aed8941efe1fdc274cb00c597c586b51ec01b7519615ebffbd60dbc2a24)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download?occurrence_status=present
Window size: width 1225 - height 601
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-20T13:28:46.407Z',to:'2023-06-20T13:34:46.407Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-20T13:28:46.407Z',to:'2023-06-20T13:34:46.407Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
see https://github.com/gbif/portal-feedback/issues/4825 instead
