### ISSUE TITLE
Dear GBIF; How can get Actinopterygii data now that it was removed from the search field.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4825]
**Dear GBIF; How can get Actinopterygii data now that it was removed from the search field.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5b761e5e31a4c315e50b3abddf2ad5ae:ce65aa94aa7762bfab906ae2847e72f66d95e40fdb84ab563426de977346fb187a89be02226b195b1c6c68328998326d189b3eb8c0bed9e8996cc0f1e03ca8c63c64455d53d8491cee29e483bc8f631259da82d03636796778ad76a74fd50370) - [Send email](https://www.gbif.org/api/feedback/user/mailto/5b761e5e31a4c315e50b3abddf2ad5ae:ce65aa94aa7762bfab906ae2847e72f66d95e40fdb84ab563426de977346fb187a89be02226b195b1c6c68328998326d189b3eb8c0bed9e8996cc0f1e03ca8c63c64455d53d8491cee29e483bc8f631259da82d03636796778ad76a74fd50370)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download?occurrence_status=present
Window size: width 1225 - height 601
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-20T13:31:13.213Z',to:'2023-06-20T13:37:13.213Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-20T13:31:13.213Z',to:'2023-06-20T13:37:13.213Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Sent by email

As you noted Actinopterygii is no longer a class in the GBIF backbone taxonomy (see https://github.com/gbif/portal-feedback/issues/4507 for more information).
This means that you will have to select all the orders that were previously under the Actinopterygii class. We have made that selection for you:

https://www.gbif.org/occurrence/search?taxon_key=1103&taxon_key=1104&taxon_key=494&taxon_key=495&taxon_key=1105&taxon_key=496&taxon_key=497&taxon_key=1106&taxon_key=498&taxon_key=499&taxon_key=1107&taxon_key=537&taxon_key=538&taxon_key=1153&taxon_key=547&taxon_key=1162&taxon_key=548&taxon_key=549&taxon_key=550&taxon_key=1163&taxon_key=1164&taxon_key=1165&taxon_key=1166&taxon_key=1167&taxon_key=1305&taxon_key=1067&taxon_key=1306&taxon_key=1307&taxon_key=1308&taxon_key=1068&taxon_key=1069&taxon_key=587&taxon_key=1310&taxon_key=588&taxon_key=589&taxon_key=1311&taxon_key=1312&taxon_key=1313&taxon_key=590&taxon_key=708&taxon_key=890&taxon_key=774&taxon_key=889&taxon_key=773&taxon_key=772&taxon_key=888&occurrence_status=present
