### ISSUE TITLE
How Can I Download Occurrence Data For Acanthothoracid Placoderms

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4827]
**How Can I Download Occurrence Data For Acanthothoracid Placoderms**

Both Placodermi and Acanthothoraci appear to be unrecognized classifications to GBIF. Is there a way to get around the limitation of not being able to download free text entries?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0e25bd53ce2374b864b39d58b11e49ad:456fc6ab572b05ba8116107c77a4c2173f8a9561dcd97dd44858b89d4be6abd44602cef85995e1dd5a0fee6ca0908008b33c0fc3b2e801ab0bae71711bbbb93289e2ed69747ff499b29cfe8d6b5baab4af6edd8eef935945a2207611d966298e1bd5b75860f42eb4b663d52758cbf05dacf42f68ed73c13a1e62fbaf3306a6ee) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0e25bd53ce2374b864b39d58b11e49ad:456fc6ab572b05ba8116107c77a4c2173f8a9561dcd97dd44858b89d4be6abd44602cef85995e1dd5a0fee6ca0908008b33c0fc3b2e801ab0bae71711bbbb93289e2ed69747ff499b29cfe8d6b5baab4af6edd8eef935945a2207611d966298e1bd5b75860f42eb4b663d52758cbf05dacf42f68ed73c13a1e62fbaf3306a6ee)
System: Safari 16.4.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/search?q=acanthothoraci&occurrence_status=present
Window size: width 960 - height 912
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-21T14:58:04.999Z',to:'2023-06-21T15:04:04.999Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-21T14:58:04.999Z',to:'2023-06-21T15:04:04.999Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
Placodermi and Acanthothoraci could not be matched to GBIF backbone, so you will need to create filters based on children of taxa which are indexed in the backbone such as following.

https://www.gbif.org/occurrence/search?taxon_key=4853178&taxon_key=9799638&taxon_key=9704461&taxon_key=4852947&taxon_key=4852959

To find which taxa are indexed in the backbone, search “Acanthothoraci” from all checklists,
https://www.gbif.org/species/search?q=Acanthothoraci&advanced=1

then click on each page to see subtaxa on the left side.
https://www.gbif.org/species/121471189

Please let me know if you have any questions.
