### ISSUE TITLE
The heading "Searching and downloading" should not be a link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4829]
**The heading &quot;Searching and downloading&quot; should not be a link**

The title "Searching and downloading" is an <a> tag, but doesn't link anywhere.

-----

Github user: @peterdesmet
User: [See in registry](https://www.gbif.org/api/feedback/user/5cce446f1a28ccd03540192b4c41fc81:8f2625df1946fe91a1c080cfbfd044bdbd009397bdfe8355ae44bc45ec1829c0534eabd0e1b040eb1e38e07c8aaa96850895130b99270eb777bc91b6c10b94e2763b2bdcc1d57c442314edb72dd05f978ac01273b8af23736197e30b9ea7c6a174f771f3ceab6b7aa3125263135b115ce2f8647e788e176c4c371f40174b0c2f018925d0c6bd9a380680cd6bd3d1bd88) - [Send email](https://www.gbif.org/api/feedback/user/mailto/5cce446f1a28ccd03540192b4c41fc81:8f2625df1946fe91a1c080cfbfd044bdbd009397bdfe8355ae44bc45ec1829c0534eabd0e1b040eb1e38e07c8aaa96850895130b99270eb777bc91b6c10b94e2763b2bdcc1d57c442314edb72dd05f978ac01273b8af23736197e30b9ea7c6a174f771f3ceab6b7aa3125263135b115ce2f8647e788e176c4c371f40174b0c2f018925d0c6bd9a380680cd6bd3d1bd88)
System: Chrome 114.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/data-processing
Window size: width 1259 - height 683
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-22T13:56:13.342Z',to:'2023-06-22T14:02:13.342Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-22T13:56:13.342Z',to:'2023-06-22T14:02:13.342Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by peterdesmet** [comment]
Correction of typo: " ... is an `<a>` tag ..."

**Comment by ManonGros** [comment]
@dnoesgaard

**Comment by dnoesgaard** [comment]
Fixed. Thanks @peterdesmet!
