### ISSUE TITLE
Hello, I would like to change the Administrative point of contact for TotalEnergies. Can you guide me on how to do this please?  Steven Dickinson

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4836]
**Hello, I would like to change the Administrative point of contact for TotalEnergies. Can you guide me on how to do this please? Steven Dickinson**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f5775ce94a5d2e06b2bb4167f6e7b13d:d9b062a75ac95596afd75f682d38c6d77ed73e3b64a36e3cd4c4d243f703800956fca67117a8d0a08d02b121e0c3b93b3b886b3a9748e661bc611bc36d61814a660bfbb0545c502ff288a562fbd57c26c7ba7bae1a81f3d4b97fe336882afef2bf05403442955cd6747e2a15eeb9ba17f1f959dbd63018f76f2a5914f9299313d48a12e016474d7ea41e5a33c4d90ef9169c79fbdd7c839d707974eeca123b6d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/f5775ce94a5d2e06b2bb4167f6e7b13d:d9b062a75ac95596afd75f682d38c6d77ed73e3b64a36e3cd4c4d243f703800956fca67117a8d0a08d02b121e0c3b93b3b886b3a9748e661bc611bc36d61814a660bfbb0545c502ff288a562fbd57c26c7ba7bae1a81f3d4b97fe336882afef2bf05403442955cd6747e2a15eeb9ba17f1f959dbd63018f76f2a5914f9299313d48a12e016474d7ea41e5a33c4d90ef9169c79fbdd7c839d707974eeca123b6d)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=Administrative%20point%20of%20contact
Window size: width 1366 - height 625
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-27T08:09:00.089Z',to:'2023-06-27T08:15:00.089Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-27T08:09:00.089Z',to:'2023-06-27T08:15:00.089Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email

> Please send us a list of the changes you would like to see on your organisation page at heldpesk@gbif.org

**Comment by ManonGros** [comment]
done
