### ISSUE TITLE
It's definitely a wrong identification. It's a juvenile Black-crowed Night-heron.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4837]
**It&#39;s definitely a wrong identification. It&#39;s a juvenile Black-crowed Night-heron.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0bc7f5ef320c33537aeec1beb9923257:e570599b25a964c1dfd13ff786e38be30d0ba68a16df815aee70cb5db08372a12d72fd6414ef997b32b002e4fd91d74919cae2e6799e593d0e60cf836222ee049e383370c19965cba43d05438e05085b7bf111252bc1ed4b098224808e37ca44) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0bc7f5ef320c33537aeec1beb9923257:e570599b25a964c1dfd13ff786e38be30d0ba68a16df815aee70cb5db08372a12d72fd6414ef997b32b002e4fd91d74919cae2e6799e593d0e60cf836222ee049e383370c19965cba43d05438e05085b7bf111252bc1ed4b098224808e37ca44)
System: Chrome 111.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/zh/occurrence/4133447301
Window size: width 1440 - height 730
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-27T09:01:56.911Z',to:'2023-06-27T09:07:56.911Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-27T09:01:56.911Z',to:'2023-06-27T09:07:56.911Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 1b26c417-366a-4eb0-a212-6ee8035d83fb
publishingOrgKey: 1f001218-e6d3-4e97-a129-63475d0dac88

**Comment by ktotsum** [comment]
Occurrence record of Cygnus olor 
https://www.gbif.org/zh/occurrence/4133447301

Image of species
http://z.cbcgdf.org/cn/view.jsp?fileID=ABUIABAEGAAgjuLfpAYo6PellAEwuAg40wU

It looks like that the image is showing swans but not Black-crowed Night-hero. If you have any questions, let me know.
