### ISSUE TITLE
It is suspected that the coordinates are wrong. It is an exclusively marine species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4839]
**It is suspected that the coordinates are wrong. It is an exclusively marine species**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c9f5a22118d2b1e925b73328db6d8e0c:df5d8eddee4828146f03475e18fc478605b6237d46af0a1b272ae44c6aa87020084e0bec3c24ccabaf1b1477773a0c68c403cda95e4b67129bbf62dca20b0f5b1eb81c0e9838701a32772126199083a0938998014be9ca8abbaa34f9a120f9e6) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c9f5a22118d2b1e925b73328db6d8e0c:df5d8eddee4828146f03475e18fc478605b6237d46af0a1b272ae44c6aa87020084e0bec3c24ccabaf1b1477773a0c68c403cda95e4b67129bbf62dca20b0f5b1eb81c0e9838701a32772126199083a0938998014be9ca8abbaa34f9a120f9e6)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1328191505
Window size: width 1366 - height 617
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-27T22:16:21.215Z',to:'2023-06-27T22:22:21.215Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-27T22:16:21.215Z',to:'2023-06-27T22:22:21.215Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: f0c3a31b-df3b-4670-ac1d-0c58d13e1420
publishingOrgKey: d6bc1312-f24f-4258-b117-a13243b915ff
Network keys: 2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6

**Comment by jhnwllr** [comment]
https://www.gbif.org/occurrence/1328191505
occurrence has a large footprintWKT provided by publisher, so the record is OK. 

![image](https://github.com/gbif/portal-feedback/assets/4245213/aa4accf8-33b0-4a9c-8c99-1f8227b6c8c6)
