### ISSUE TITLE
Best practice guide for checklist publishing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#484]
**Best practice guide for checklist publishing**

During GNM14 it's suggested to resurface the Best Practice guide for checklist publishing(Remsen, 2010). Should it be listed in the result of this URL?
https://www.gbif.org/resource/search?q=checklist&contentType=document

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb
User provided contact info: cjk@sinica.edu.tw
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/resource/search?q=checklist&contentType=document
Window size: width 1143 - height 949
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-25T07:26:04.736Z',mode:absolute,to:'2017-09-25T07:32:04.736Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-25T07:26:04.736Z',mode:absolute,to:'2017-09-25T07:32:04.736Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
User contacted.

It is there if querying for checklists (plural):
https://www.gbif.org/resource/search?q=checklists&contentType=document

**Comment by kcopas** [comment]
Please cross-check with @kbraak 's analysis/assessment of this document (it's got to be part of his broader review), just to be sure we understand and (plan to) address any issues that need updates or other attention.

**Comment by kbraak** [comment]
@kcopas @dnoesgaard @thomasstjerne This PDF should never have been transferred to the new portal as it has been replaced with a wiki version https://github.com/gbif/ipt/wiki/BestPracticesChecklists Please double check my data publishing documentation review. It is linked to from the how-to publish checklists wiki page: https://github.com/gbif/ipt/wiki/checklistData#how-to-transform-your-data-into-checklist-data

**Comment by thomasstjerne** [comment]
OK. Should be removed then, but since some publishers don´t use IPTs, information about checklist publishing should  be possible to find when searching the portal as well.

**Comment by dnoesgaard** [comment]
I don't know why this was ever created in Contentful. Must've been a mistake. I have archived it now, so it should disappear from the portal.

**Comment by thomasstjerne** [comment]
My mistake - I created it while in Helsinki. I was in a group discussing checklist publishing, and they pointed out that they could not find the document they had referred to earlier. 

Is there a resource pointing to the current wiki version? Or maybe it should be included here: https://www.gbif.org/data-quality-requirements-checklists ?

**Comment by mdoering** [comment]
Yes, I think a resource would be good and also a link from the quality requirements page.

The IPT wiki page also contains some links like this: http://links.gbif.org/gbif_dwca_how_to_guide_en_v1

Are these still valid or should they be replaced by some other URL?

**Comment by MattBlissett** [comment]
links.gbif.org links are supposed to still work. Daniel and Kyle have access to update them if needed.

**Comment by dnoesgaard** [comment]
@mdoering can you pls tell me where exactly you found these links?

**Comment by dnoesgaard** [comment]
I found 5 links in the page. They all point to documents that @kbraak recommended not be transferred to the new portal. It seems that the first one is simply a link to a previous version of the same document, but the rest I'm simply not sure about. @kbraak, can you help? I don't know if the relevant documents have been created in the wiki, too?

| link found                                                                                                                                                                                                                                                                                                                                                                                                                   | old resource                                                                                                                                   | document review                |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------|
| [1.11](http://links.gbif.org/checklist_best_practices)  Minor editorial changes  28 April 2011  David Remsen                                                                                                                                                                                                                                                                                                                 | https://www.gbif.org/orc?doc_id=2814 http://www-old.gbif.org/resource/80634                                                                    | Remove (preserved in IPT wiki) |
| This requires editing the XML metafile which requires some degree of familiarity with XML. GBIF [provides a complete guide the to Darwin Core metafile](http://links.gbif.org/gbif_dwc-a_metafile_en_v1).                                                                                                                                                                                                                    |  https://www.gbif.org/orc?doc_id=2819 http://www-old.gbif.org/resource/80639                                                                   | Remove                         |
| If it is the same throughout the dataset, consider using a static mapping of the term and value. See the Darwin Core Archive How-to Guide at http://links.gbif.org/gbif_dwca_how_to_guide_en_v1 for details on mapping global values.                                                                                                                                                                                        | (incorrect) should perhaps be gbif_dwca_how_to_guide_v1: https://www.gbif.org/document/80636/_redirect http://www-old.gbif.org/resource/80636/ | Remove (preserved in IPT wiki) |
| The GBIF Metadata profile supports resource-level data elements that contribute to citation and attribution and enable detailed description of the scope and provenance of a checklist. A complete reference list to all the metadata elements is beyond the scope of this document and [available](http://links.gbif.org/gbif_metadata_profile_guide_en_v1) but specific citation and attribution-related elements include: | https://www.gbif.org/orc?doc_id=2820 http://www-old.gbif.org/resource/80640                                                                    | Preserve in markdown/wiki only |
| A How-to guide describes all the options for describing a species checklist using this format. See http://links.gbif.org/gbif_metadata_profile_how-to_en_v1                                                                                                                                                                                                                                                                  | https://www.gbif.org/orc?doc_id=2821 http://www-old.gbif.org/resource/80641                                                                    | Preserve in markdown/wiki only |

**Comment by kbraak** [comment]
Indeed @dnoesgaard and I flagged these as outstanding actions needed, as the wiki version isn't finished yet albeit better than the PDF version. 

Please refer to my "GBIF data publishing documentation analysis", specifically the section entitled "Prioritized action points remaining".
