### ISSUE TITLE
API documentation incorrect regarding facet limitations

### ISSUE THREAD

**Issue by nickynicolson** [gbif/portal-feedback#4842]
The occurrence API documentation for facets (https://www.gbif.org/developer/occurrence#p_facet) states:

> A facet name used to retrieve the most frequent values for a field. Facets are allowed for all the parameters except for: eventDate, geometry, lastInterpreted, locality, organismId, stateProvince, waterBody. This parameter may by repeated to request multiple facets, as in this example [/occurrence/search?facet=datasetKey&facet=basisOfRecord&limit=0](https://api.gbif.org/v1/occurrence/search?facet=datasetKey&facet=basisOfRecord&limit=0)

It seems that it is not possible to get a facet on `habitat` (not specified in the list of excluded fields above) whilst it is possible to get a facet on `locality` (listed above as excluded):

Occurrence API call, faceting on locality: https://api.gbif.org/v1/occurrence/search?basisOfRecord=PRESERVED_SPECIMEN&country=NZ&limit=0&facet=locality
Occurrence API call, faceting on habitat: https://api.gbif.org/v1/occurrence/search?basisOfRecord=PRESERVED_SPECIMEN&country=NZ&limit=0&facet=habitat

Please could the facet documentation be updated to match behaviour of the API?

**Comment by MattBlissett** [comment]
The API and the documentation are now correct: faceting is enabled on all search parameters except geometry and geoDistance.

I'll tweak the documentation to explain that not all parameters are available for searching; habitat is not enabled.  Is that something you need?

**Comment by MattBlissett** [comment]
I've added an extra note to the faceting parameters.
