### ISSUE TITLE
Add preparations to occurrence table

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#4846]
From https://github.com/gbif/portal-feedback/issues/4843
>
> I also noticed that preparation is not a field that can be added. A number of collections (especially fish lot-based collections) use this to show number of specimens and preparation types which would be useful to add.

Github user: @acbentley
User: [See in registry](https://www.gbif.org/api/feedback/user/2399381f5814d48c01de747881387b15:3d401522809f40f51ce89fe7e02d8a8030c47cc5093e8819d8ddedcd3300ecc7ce635146b4387635e6c95907c2c83d13fad355fa5aad0bc2f8c102573bcaca4d6c7e60d406b5ae931642032f4188e568c6e79f10059e7253d704ee2001b80636664bc4cdc1a60e95320a3f9ce5103cf4a3a1beeca422ea87f351af2ac4247285) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2399381f5814d48c01de747881387b15:3d401522809f40f51ce89fe7e02d8a8030c47cc5093e8819d8ddedcd3300ecc7ce635146b4387635e6c95907c2c83d13fad355fa5aad0bc2f8c102573bcaca4d6c7e60d406b5ae931642032f4188e568c6e79f10059e7253d704ee2001b80636664bc4cdc1a60e95320a3f9ce5103cf4a3a1beeca422ea87f351af2ac4247285)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?dataset_key=56caf05f-1364-4f24-85f6-0c82520c2792&advanced=1&event_id=AL%2095-04:10

**Comment by MortenHofft** [comment]
I've added the option to show preparations in the table. But it won't help much in your case @acbentley. Since the preparations live in an extension and hence isn't searchable.
https://api.gbif.org/v1/occurrence/656968025

I do not know the standards well enough to know if it would make sense to map the extension data into the core dwc field during ingestion? @ManonGros you probably have a more qualified opinion on this than I do.

**Comment by acbentley** [comment]
No, that works great, thanks Morten.  I am mapping to the DwC concept for preparations so they show up nicely.

***@***.***

Andy

   A :            A :            A  :
}<(((_°>.,.,.,.}<(((_°>.,.,.,.}<(((_°>
   V              V              V
 Andy Bentley
 Ichthyology Collection Manager/Specify Usability Lead
 University of Kansas
 Natural History Museum & Biodiversity Research Center
 Dyche Hall
 1345 Jayhawk Boulevard
 Lawrence, KS, 66045-7593
 USA

 Tel: (785) 864-3863
 Fax: (785) 864-5335
 Email: ***@***.***<https://mail.ku.edu/owa/redir.aspx?C=dc73cada03f64a4395985d76c0587253&URL=http%3a%2f%2fABentley%40ku.edu>

   A :            A :            A  :
}<(((_°>.,.,.,.}<(((_°>.,.,.,.}<(((_°>
   V              V              V

**Comment by ahahn-gbif** [comment]
Thanks, Andy - you were faster than me, just wanted to add that in general, for now, mapping to the core concepts of 
https://dwc.tdwg.org/terms/#dwc:preparations and
(https://dwc.tdwg.org/terms/#dwc:individualCount)
would likely be the best approach
