### ISSUE TITLE
GBIF intake of weekly data publication has stopped working for our collection

### ISSUE THREAD

**Issue by ut-entomology** [gbif/portal-feedback#4851]
Our collection (here: https://www.gbif.org/dataset/ba9984d8-d982-4fe6-b81c-a7585790034a ) has been publishing weekly for years, but after we upgraded our own servers in mid-June, our publications have failed to be picked up by GBIF. The last functional one was June 19th, with 3 subsequent failures. Oddly, GBIF registers the new metadata each time we publish, but not the actual published data. 

Our IPT at utexas: https://ipt.tacc.utexas.edu/resource?r=utic

We could use some help figuring out where the problem lies.

Thanks,

Alex Wild, Curator
University of Texas Biodiversity Collections

**Comment by ManonGros** [comment]
Replied by email.
