### ISSUE TITLE
Suggestion: duplicate GBIF Dodo on Twitter as RSS feed

### ISSUE THREAD

**Issue by Mesibov** [gbif/portal-feedback#4852]
also, please note that the RSS link for GBIF-mediated papers in Mendeley (from here: https://www.gbif.org/newsletters) gives a redirect failure notice.

**Comment by ManonGros** [comment]
@dnoesgaard

**Comment by dnoesgaard** [comment]
Mendeley has silently killed the RSS feature, so I have removed the link now.

**Comment by dnoesgaard** [comment]
I don't think there are any plans for RSS feeds for literature, but perhaps your RSS client can consume JSON directly from the API: https://api.gbif.org/v1/literature/search?relevance=GBIF_USED&peerReview=true&literatureType=JOURNAL

**Comment by Mesibov** [comment]
@dnoesgaard Many thanks. So can you build a simple RSS feed for the bulk of Dodo messages, each of which has a new dataset link and some notes on it?

**Comment by dnoesgaard** [comment]
The dodo has two components:

- new datasets published in GBIF (fully automated)
- new papers using GBIF-mediated data (semi-automated）

Neither currently has an RSS feed, but you can get the same data in JSON format via the REST APIs:

Datasets: https://api.gbif.org/v1/dataset
Papers: https://api.gbif.org/v1/literature/search?relevance=GBIF_USED&peerReview=true&literatureType=JOURNAL

There are tools available online to convert to RSS, e.g. http://fetchrss.com/

While writing the above, I just realized that Mastodon has built-in RSS feeds for all accounts, which means that the [Mastodon version of the Dodo](https://botsin.space/@gbifmammut) has this feed: https://botsin.space/@gbifmammut.rss

**Comment by Mesibov** [comment]
Thanks, @dnoesgaard , that Mastodon feed is what I was proposing, good to see it already done.
