### ISSUE TITLE
Filter preview unreadable

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4854]
**Filter preview unreadable**

Styling has been broken by a recent commit. The filter preview is tiny.

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/b9ed3ea1c75c534b07b52ec39ab7fd5e:72cacbfe97658210e8dad126108b08f017c399ffed542305d7a3aa7757478151b84909e22ca8cc4ada044073875b831586a374b8083db14c0cb4d3f84e75864d05c08918a58089c36846e5e94e897578f6365eba0c73f8460734180f020057b9851e964363a7441d46f150901a1b10f8a5963515588586a2d48cad569ef8f209) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b9ed3ea1c75c534b07b52ec39ab7fd5e:72cacbfe97658210e8dad126108b08f017c399ffed542305d7a3aa7757478151b84909e22ca8cc4ada044073875b831586a374b8083db14c0cb4d3f84e75864d05c08918a58089c36846e5e94e897578f6365eba0c73f8460734180f020057b9851e964363a7441d46f150901a1b10f8a5963515588586a2d48cad569ef8f209)
System: Chrome 114.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/charts?dataset_key=b740eaa0-0679-41dc-acb7-990d562dfa37&month=1
Window size: width 1284 - height 968
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-07T04:35:21.640Z',to:'2023-07-07T04:41:21.640Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-07T04:35:21.640Z',to:'2023-07-07T04:41:21.640Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
<img width="503" alt="Screenshot 2023-07-07 at 06 40 30" src="https://github.com/gbif/portal-feedback/assets/6759267/172c0628-7499-4e1b-98b9-550743b8f63c">

**Comment by MortenHofft** [comment]
It is the recent addition of phylogonies that is very unspecific in its styling and simply styles anything with class `.node`
