### ISSUE TITLE
Is there a way to search for just the species of a particular name and not pull up all the Genera with that name?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4855]
**Is there a way to search for just the species of a particular name and not pull up all the Genera with that name?**

For example, I'd like to search for two "euodia" species (Aphilopota euodia and Fagara euodia) without having to sift through the several hundred species within the Euodia genus.  Or do a similar search looking only for the subspecies with a particular name.
If not, why not?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4b66d6c4c6890b1709cd4a67b2557d6c:1888fe00ece7f6eaed540a809edb8cfb6a68fb7d548397a2e55c6690ed013a95f04febf0cad6b815053ab13468f591fff2c5a2b16909f3fd8e2077003e5a15ed9d4146545eb87288e2697dcdf27aedd6704e7ee4cb7174a722152bacb18f5b9e9156d46a64a6615b73293ba186b5c01381b6a0cab63adfb2dfcdfce1aa0011b76bc46d7ac57a41f775f7e9e73d524032) - [Send email](https://www.gbif.org/api/feedback/user/mailto/4b66d6c4c6890b1709cd4a67b2557d6c:1888fe00ece7f6eaed540a809edb8cfb6a68fb7d548397a2e55c6690ed013a95f04febf0cad6b815053ab13468f591fff2c5a2b16909f3fd8e2077003e5a15ed9d4146545eb87288e2697dcdf27aedd6704e7ee4cb7174a722152bacb18f5b9e9156d46a64a6615b73293ba186b5c01381b6a0cab63adfb2dfcdfce1aa0011b76bc46d7ac57a41f775f7e9e73d524032)
System: Opera 99.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/7750997
Window size: width 993 - height 661
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-08T18:08:08.758Z',to:'2023-07-08T18:14:08.758Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-08T18:08:08.758Z',to:'2023-07-08T18:14:08.758Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
You can search specific species by adding names to scientific name filters as below for searching occurrences.
https://www.gbif.org/occurrence/search?taxon_key=1985859&taxon_key=7750997

As for searching species, you will need to search with each name to get a result.

Aphilopota euodia
https://www.gbif.org/species/1985859
Fagara euodia
https://www.gbif.org/species/7750997
