### ISSUE TITLE
Aphididae name_backbone

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4863]
**Aphididae name_backbone**

Dear Sir or Madam,

i am using rgbif to find synonms in species lists from various sources. I found that the backbone taxonomy of aphids seems to return only usage keys for the Family, even for very common species, such as Myzus persicae or Macrosiphum eurphorbiae. What can I do?

Kind regards

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8de683d5f3d5d9f432e47d6e835fd2aa:1557f41ae45da6ec7f2f9fe921388b2a4c483f7b2565968f63ecddfb2cef360fcd212c70204bcb72e1f59450e2d154f9394baa7079b3dc0039ecfd005e4dee26a372b4d78d30e326fe69fdaf596cddaffcc2a359b64900cb8add23783fff0be7125629cae9a0c901542eaacfa0d0e204) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8de683d5f3d5d9f432e47d6e835fd2aa:1557f41ae45da6ec7f2f9fe921388b2a4c483f7b2565968f63ecddfb2cef360fcd212c70204bcb72e1f59450e2d154f9394baa7079b3dc0039ecfd005e4dee26a372b4d78d30e326fe69fdaf596cddaffcc2a359b64900cb8add23783fff0be7125629cae9a0c901542eaacfa0d0e204)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/download
Window size: width 1632 - height 939
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-11T11:07:51.669Z',to:'2023-07-11T11:13:51.669Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-11T11:07:51.669Z',to:'2023-07-11T11:13:51.669Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
> Replied by email

You can use the name_lookup function in RGBIF to get the taxa under one give family.

For example, here is how to get all the species under the Aphididae family: `name_lookup(higherTaxonKey=3042,"rank=SPECIES")$data`
* It is equivalent to this search: https://www.gbif.org/species/search?rank=SPECIES&highertaxon_key=3042
* 3042 is the taxon key in the GBIF backbone for the Aphididae family
* It specifies that you only want species names
