### ISSUE TITLE
No images coming through with Finnish data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#487]
**No images coming through with Finnish data**

Suspect this is a simple mapping problem, given how compelling [Laji.fi's occurrence gallery](https://laji.fi/en/observation/images?hasMedia=true) is, but none of the images are coming through to GBIF.

Quick check with Tapani Lahti might sort things out, but probably not until after GB24...

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: @kcopas
System: Safari 10.1.2 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/search?media_type=StillImage&publishing_org=04fd2e13-6881-4e5c-9dd1-8fdd9ab993c1
Window size: width 1208 - height 793
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-25T12:00:20.121Z',mode:absolute,to:'2017-09-25T12:06:20.121Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-25T12:00:20.121Z',mode:absolute,to:'2017-09-25T12:06:20.121Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Correct, the images aren't included in the DWCA we see.

**Comment by dnoesgaard** [comment]
Note from Tapani from August 2018:

> So far we have not published any multimedia data to GBIF. There are a number of copyright issues, as well as quality control issues (primarily with correct species identification), associated with multimedia data in our repository. We want to resolve these issues properly before making multimedia data available through GBIF.
> 
> It is worth noticing that many of the largest occurrence datasets from FinBIF (e.g. Finnish Bird Ringing and Recovery Database, Finnish Floristic Database, Finnish Winter Bird Census) contain no multimedia data at all.
> 
> Digitisation of natural history collections produces plenty of images of museums specimens in the coming years. These images will be published to GBIF as part of specimen data in the near future.

**Comment by jhnwllr** [comment]
Closing this since the publisher is aware of the issue and working on it.
