### ISSUE TITLE
Ontologies for bulk DNA samples

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4871]
**Ontologies for bulk DNA samples**

I am creating a metadata template for Natural England's eDNA work. To make it as user-friendly as possible,  I have been creating drop down list for  env_broad_scale, env_local_scale and env_medium, to include our most common use cases. A number of our projects have used bulk DNA samples from things like Malaise traps or plankton netting. I can see that GBIF asks for env_medium to be an ontology from ENVO´s environmental material class: http://purl.obolibrary.org/obo/ENVO_00010483. However,  I can't find a suitable ontology for bulk DNA samples within this class. Do you have any suggestion for what ontologies we should use for bulk DNA samples?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fb73c2ee370f5c7f610159eeb12347e9:9bf67cffffaed83bc1902c11ac7a784a0d1b669c43ba5dc3b49a6959cd0697b23d569e404910c8e399deb5748438b87c5a1bf34ca54f11e8c317128f8c084c7ceb97c7d4c01d587d2dda345b760c601afb4802c825422c80dab86b514b3f005dc43346a3b2981ae035eeaff4011d850c7ef3593000cf17c22e0ec91353df60cadae8815da29920d5fa60bfd34aab06a6) - [Send email](https://www.gbif.org/api/feedback/user/mailto/fb73c2ee370f5c7f610159eeb12347e9:9bf67cffffaed83bc1902c11ac7a784a0d1b669c43ba5dc3b49a6959cd0697b23d569e404910c8e399deb5748438b87c5a1bf34ca54f11e8c317128f8c084c7ceb97c7d4c01d587d2dda345b760c601afb4802c825422c80dab86b514b3f005dc43346a3b2981ae035eeaff4011d850c7ef3593000cf17c22e0ec91353df60cadae8815da29920d5fa60bfd34aab06a6)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1415 - height 866
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-20T11:08:27.436Z',to:'2023-07-20T11:14:27.436Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-20T11:08:27.436Z',to:'2023-07-20T11:14:27.436Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@tobiasgf do we have any recommendations?

**Comment by thomasstjerne** [comment]
For Malaise traps it could be "Animal trap" http://purl.obolibrary.org/obo/ENVO_01000975
However, it might make sense to suggest a new more accurate term "Malaise trap" or "Malaise trap content" here:  https://github.com/EnvironmentOntology/envo/issues/

For plankton nettings, there is "sea water"  http://purl.obolibrary.org/obo/ENVO_00002149 which seems quite suitable.

GBIF basically relies on the [MiXS](http://www.gensc.org//pages/projects/mixs-gsc-project.html) standard here, they may know if there is a best practice for e.g. Malaise traps

**Comment by MortenHofft** [comment]
> user notified per email

**Comment by CecSve** [comment]
I will close the issue, but please let us know if this is still unresolved
