### ISSUE TITLE
I wat to explore all the geotagged audio around the world

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4872]
**I wat to explore all the geotagged audio around the world**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1226db7e5b4c93cc0882bac2b9c75451:3e2d5780949ffc2e14c2e7979b12c873ae11dc9543917674b55d8b0f44647c109b800e78660fc4e9a2c17ee198907733c249518bb8e21f669d9cb65e32f5fb60abc808d7abf579c97a26428689df8981d61469d9769f699a203ce571c4b939ae) - [Send email](https://www.gbif.org/api/feedback/user/mailto/1226db7e5b4c93cc0882bac2b9c75451:3e2d5780949ffc2e14c2e7979b12c873ae11dc9543917674b55d8b0f44647c109b800e78660fc4e9a2c17ee198907733c249518bb8e21f669d9cb65e32f5fb60abc808d7abf579c97a26428689df8981d61469d9769f699a203ce571c4b939ae)
System: Safari 16.3.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/system-health
Window size: width 2059 - height 1250
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-20T17:27:55.869Z',to:'2023-07-20T17:33:55.869Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-20T17:27:55.869Z',to:'2023-07-20T17:33:55.869Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
A filter for "Location: including coordinates" and "Media type: audio" should yield a reasonable starting point: https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&media_type=Sound&occurrence_status=present

**Comment by ahahn-gbif** [comment]
Submitter contacted via helpdesk, 25.7. (ticketnumber in subject line). Against expectation, GBIF does not store and ship the audio files, but only stores hyperlinks to the files available at the original site.
