### ISSUE TITLE
What alphabets/scripts can GBIF accept?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4873]
**What alphabets/scripts can GBIF accept?**

I am looking at Urdu, Pushto, and Bangladeshi? Primarily, I am curious. 
The impetus for the inquiry an interest in making easier for people to enter data in their own language, thereby potentially increasing the number of data providers.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b7a141581219d8a5a6ef5406408b1a40:509fc7700936523f90aad2d50c8d7df1294ce5e29dcb5c7b40aa495b32e9662e2ff8e63fa3dd028fce7652fc25ecfc4adc74324a21bb4cebfa4ccf3abd2db0345f140fdd9e575e6069e59ca7e9f8dda8ba9040a958e928bbbeae4442a812cb35457229bb48798aab8a5c7ce74fd337eba276967e6b5b35bcfb0883734e317da6feba5d542db6f82f0699a1434ce37713) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b7a141581219d8a5a6ef5406408b1a40:509fc7700936523f90aad2d50c8d7df1294ce5e29dcb5c7b40aa495b32e9662e2ff8e63fa3dd028fce7652fc25ecfc4adc74324a21bb4cebfa4ccf3abd2db0345f140fdd9e575e6069e59ca7e9f8dda8ba9040a958e928bbbeae4442a812cb35457229bb48798aab8a5c7ce74fd337eba276967e6b5b35bcfb0883734e317da6feba5d542db6f82f0699a1434ce37713)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1088 - height 951
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-22T13:08:18.662Z',to:'2023-07-22T13:14:18.662Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-22T13:08:18.662Z',to:'2023-07-22T13:14:18.662Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
By email:

All scripts are supported for dataset metadata and data (occurrences, checklist vernacular names) on GBIF.

To make it possible for a user to search for country=Bangladesh, or establishmentMeans=invasive, we convert translations of these values (Bangladeschu, Μπαγκλαντές, بَن٘گْلَہ دیْش and so on) into English.  We don't yet have translations for these values in Urdu, Pushto or Bangladeshi, so we might ask for them if data comes in using them.

Dataset metadata is not translated, it is displayed as we receive it. Test example: https://www.gbif-uat.org/dataset/f261c46d-28ee-46cc-bd84-1097001b0a3c

Real example of a dataset from Taiwan: https://www.gbif.org/dataset/1d9b55a1-1dfb-4b9d-9431-47de185ceea7


For details on translating the gbif.org website itself, see https://www.gbif.org/article/48VZfjFc9QBji8geU65YBD/how-to-become-a-gbif-translator .  The site is already available in Arabic, so it supports languages written from right to left.

The IPT can also be translated, see https://ipt.gbif.org/manual/en/ipt/latest/translations in that case.
