### ISSUE TITLE
页面无法加载

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4875]
**页面无法加载**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/06607a73ed1f7a81045317eb26af5cd8:e4e143fe27bdcb57a258cef315e5abf7ecde6a4a164f37fe6822732da00ce8ccdfe175e1025add967f519f3a59996a922cc3bfaa500213d145ead2e7cdb22e2f8e4aec33d9da868179b6040b3ff4707060f90bd697c23857cd6853093d975c55) - [Send email](https://www.gbif.org/api/feedback/user/mailto/06607a73ed1f7a81045317eb26af5cd8:e4e143fe27bdcb57a258cef315e5abf7ecde6a4a164f37fe6822732da00ce8ccdfe175e1025add967f519f3a59996a922cc3bfaa500213d145ead2e7cdb22e2f8e4aec33d9da868179b6040b3ff4707060f90bd697c23857cd6853093d975c55)
System: Chrome 108.0.5359 / Windows 10.0.0
Referer: https://www.gbif.org/zh/system-health
Window size: width 1275 - height 570
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-25T04:03:18.224Z',to:'2023-07-25T04:09:18.224Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-25T04:03:18.224Z',to:'2023-07-25T04:09:18.224Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Google analytics
> siden kunne ikke indlæses

closing in favour of https://github.com/gbif/portal-feedback/issues/4876
