### ISSUE TITLE
cannot download WoRMS Darwin Core Archive from its endpoint

### ISSUE THREAD

**Issue by ymgan** [gbif/portal-feedback#4877]
When I go to the endpoint in [WoRMS dataset in GBIF](https://www.gbif.org/dataset/2d59e5db-57ad-41ff-97d6-11f5fb264527#dataDescription): http://www.marinespecies.org/dwca/WoRMS_DwC-A.zip

I got 403 error with the message below and cannot download the Darwin Core Archive

```
Forbidden

You don't have permission to access this resource.
```

Is this normal?

**Comment by ktotsum** [comment]
Endpoint for checklist is not always public and the publishers may give access rights on request. We suggest contacting WoRMS directly. You can find email addresses for administrative point of contact and custodian steward [here](https://www.gbif.org/dataset/2d59e5db-57ad-41ff-97d6-11f5fb264527#contacts).
