### ISSUE TITLE
I cannot download the dataset. The system isn't able to process the requestt

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4878]
**I cannot download the dataset. The system isn&#39;t able to process the requestt**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2cfbbbed385bf05c0ea168a35a198715:6e2da5c0cfc1de20947d3aa37ce871cae60a51c8db0c1d519a5c3bef74835e6a10b0e24ef1493a0cd518f24af508431f7ded2a6e9998581ff1f96aeeaebf23747c6563dc19d8fb6ad5eb53f4af0fdad955bbcbf6b309f76af66d7899984a0b92cddc676a4edd9a3d74c99daa17c7d29980da177064965c0136f27c9e38461633bb681d86e47b93a397bd5afa1221646d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2cfbbbed385bf05c0ea168a35a198715:6e2da5c0cfc1de20947d3aa37ce871cae60a51c8db0c1d519a5c3bef74835e6a10b0e24ef1493a0cd518f24af508431f7ded2a6e9998581ff1f96aeeaebf23747c6563dc19d8fb6ad5eb53f4af0fdad955bbcbf6b309f76af66d7899984a0b92cddc676a4edd9a3d74c99daa17c7d29980da177064965c0136f27c9e38461633bb681d86e47b93a397bd5afa1221646d)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/system-health
Window size: width 1536 - height 714
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-25T11:15:35.346Z',to:'2023-07-25T11:21:35.346Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-25T11:15:35.346Z',to:'2023-07-25T11:21:35.346Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
closing as duplicate
