### ISSUE TITLE
Records of marbled salamander showing up in wrong place

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4879]
**Records of marbled salamander showing up in wrong place**

A search of this species with a range in Eastern US showed up 30 records in Colorado, all from the same collection dataset. Looking at the location descriptions of a few records,  the records are clearly from Eastern states so this would seem to be a georeferencing error.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a336788b71eb5a3f8bbdb9f5966c632d:2b43bf02979d8dfc7fd8be7ee3e2a810eafb79d368703b1246744b5ab16c674a184ffaf980680d7a070aebde95f5a16d9a189e84bdd06aac885b8e598ab2fc33392887cd2715a62dcaf2357d5b0d1b03865a9a0f2b2f3287a718835bf28507b29eaad932d12f74197114f27ae527c20b578a0a4d5753c29813c0cb1977e62202) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a336788b71eb5a3f8bbdb9f5966c632d:2b43bf02979d8dfc7fd8be7ee3e2a810eafb79d368703b1246744b5ab16c674a184ffaf980680d7a070aebde95f5a16d9a189e84bdd06aac885b8e598ab2fc33392887cd2715a62dcaf2357d5b0d1b03865a9a0f2b2f3287a718835bf28507b29eaad932d12f74197114f27ae527c20b578a0a4d5753c29813c0cb1977e62202)
System: Chrome 115.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/search?geometry=POLYGON((-116.26358%2037.34156,-102.12144%2037.34156,-102.12144%2042.99116,-116.26358%2042.99116,-116.26358%2037.34156))&has_coordinate=true&has_geospatial_issue=false&occurrence_status=present&taxon_key=2432006
Window size: width 1892 - height 901
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-26T08:47:01.807Z',to:'2023-07-26T08:53:01.807Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-26T08:47:01.807Z',to:'2023-07-26T08:53:01.807Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
Contacted [the dataset](https://www.gbif.org/dataset/fb639e31-52eb-4998-afb1-984ee12aca0f) and the user on 2023-07-28 from helpdesk. The records are labeled with geographic issues (geodetic datum invalid).

**Comment by jhnwllr** [comment]
This seems fixed now since the search has no records.
