### ISSUE TITLE
Polygon selection allows coordinates like -205

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#488]
**Polygon selection allows coordinates like -205**

For the Location filter for occurrences, zoomed out as far as possible and tried to define bounding box around whole northern hemisphere.  Ended up with a left-hand longitude of -205.xxx degrees.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: dhobern@gbif.org
System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&month=1&taxon_key=5229230&geometry=POLYGON%20((-73.10872435569763%2029.430403177822438,%20-73.10872435569763%2082.47907840349706,%20174.39127564430237%2082.47907840349706,%20174.39127564430237%2029.430403177822438,%20-73.10872435569763%2029.430403177822438))
Window size: width 1897 - height 924
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-25T12:27:46.358Z',mode:absolute,to:'2017-09-25T12:33:46.358Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-25T12:27:46.358Z',mode:absolute,to:'2017-09-25T12:33:46.358Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi Donald. If I understand the issue correctly, then this is on purpose and what most mapping libraries opt for when representing queries across the dateline.

But since that makes it difficult to select there is also the option to use the sliders

![screen shot 2017-09-26 at 10 31 21](https://user-images.githubusercontent.com/6759267/30850568-2cac356a-a2a6-11e7-893b-9551473bf9d4.png)

**Comment by MortenHofft** [comment]
User informed per email
