### ISSUE TITLE
A photograph listed under Boswellia serrata from Manipur (https://www.gbif.org/species/5421354) is of Gleaditsia assamica of Ceasalpinaceae. Please change.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4881]
**A photograph listed under Boswellia serrata from Manipur (`https://www.gbif.org/species/5421354)` is of Gleaditsia assamica of Ceasalpinaceae. Please change.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ae3d0ce2aed146d9af7b5612bbf3cd8c:57e54a6e05dcbf5661ea6108fd7dbbf54d401891a7dcbd57ec04d089bfc80c824d4f451a8422d04b157aec958810051daf1baed74df61ede12a32ae6d658e7007272ab39b0c06e562b7b4bf4b92f43c38fbaca82d4a9394f31d4db9a8221013a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ae3d0ce2aed146d9af7b5612bbf3cd8c:57e54a6e05dcbf5661ea6108fd7dbbf54d401891a7dcbd57ec04d089bfc80c824d4f451a8422d04b157aec958810051daf1baed74df61ede12a32ae6d658e7007272ab39b0c06e562b7b4bf4b92f43c38fbaca82d4a9394f31d4db9a8221013a)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/5421354
Window size: width 1536 - height 664
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-28T08:32:13.630Z',to:'2023-07-28T08:38:13.630Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-28T08:32:13.630Z',to:'2023-07-28T08:38:13.630Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
contacted the user and [the dataset](https://www.gbif.org/dataset/c6b86c40-ff71-4e5e-902c-111f400d0d56) from helpdesk on 2023-07-31.

**Comment by ktotsum** [comment]
The record was fixed and updated by the publisher.
