### ISSUE TITLE
Hello! For the purpose of publication, I am looking to re-download a dataset of 6433 records of many unrelated species as one GBIF download with an associated DOI. Is there any way I can query for a list using an identifier field like "catalogNumber" in Darwin Code to get this dataset from GBIF? Thank you!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4884]
**Hello! For the purpose of publication, I am looking to re-download a dataset of 6433 records of many unrelated species as one GBIF download with an associated DOI. Is there any way I can query for a list using an identifier field like &quot;catalogNumber&quot; in Darwin Code to get this dataset from GBIF? Thank you!**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/30d6769fa5dbba9d3baa2773e3a1494a:dfcd9fd95430080f708cab56ddc3856e9d6d6b90bfe5ce70c69314a10087d681a22446c227332b533b61bac5b3d22271e7f556215e43f78739b0592db3e5affcc2a383ebe662d5c7d09c00f36ece7dcec348b211e0d6dda7c2daf8e0f5535ea2cc1624824aaf26a8ad427283e7683466ab32e12d0092ca0dea928345d937ef8260916d9896297f759c2a17045bc45bf6) - [Send email](https://www.gbif.org/api/feedback/user/mailto/30d6769fa5dbba9d3baa2773e3a1494a:dfcd9fd95430080f708cab56ddc3856e9d6d6b90bfe5ce70c69314a10087d681a22446c227332b533b61bac5b3d22271e7f556215e43f78739b0592db3e5affcc2a383ebe662d5c7d09c00f36ece7dcec348b211e0d6dda7c2daf8e0f5535ea2cc1624824aaf26a8ad427283e7683466ab32e12d0092ca0dea928345d937ef8260916d9896297f759c2a17045bc45bf6)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1280 - height 649
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-29T15:56:04.501Z',to:'2023-07-29T16:02:04.501Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-29T15:56:04.501Z',to:'2023-07-29T16:02:04.501Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Yes you can download a list of catalog numbers. but be aware that catalog numbers are not necessarily unique. If you have an existing download with a DOI, you can download that again and again. Or trigger a new download with the same filter (getting the latest data for that filter).

I can see you have already figured out how to download a list of catalog numbers from your download activity.

I will close this issue then, let us know if you still have questions.

> user informed by email
