### ISSUE TITLE
means of establishment filter shows raw names

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4886]
**means of establishment filter shows raw names**

means of establishment filter shows raw names instead of proper tranlsated labels. I'm 99% convinced we used to show the proper labels. 
I similarly see that the hosted portals filter do not work anymore (shows no values at all). So most likely we have changed the API without updating the UIs to match the new behaviour.

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/0b9e8da120e4f800a7e2e235884644ae:8b3d6e040e0e1931ca853ffa70c36465b0f7e1d51f08ddab10f0663f9b96468cba7cbefc1c51ec8cc4be309f63662c765737920922f59453634da04246e9da3418ab13bad37e05b955af4c5124f49b33cbab0f950aa31efab2e7c72dfdcaa788fe3442e44b1404e0f972b40e6f0ade371fd1c5f0e95663555538c294b2c1bfa2) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0b9e8da120e4f800a7e2e235884644ae:8b3d6e040e0e1931ca853ffa70c36465b0f7e1d51f08ddab10f0663f9b96468cba7cbefc1c51ec8cc4be309f63662c765737920922f59453634da04246e9da3418ab13bad37e05b955af4c5124f49b33cbab0f950aa31efab2e7c72dfdcaa788fe3442e44b1404e0f972b40e6f0ade371fd1c5f0e95663555538c294b2c1bfa2)
System: Chrome 115.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/fr/occurrence/search?establishment_means=IntroducedAssistedColonisation&advanced=1&occurrence_status=present
Window size: width 1874 - height 1550
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-01T14:43:01.829Z',to:'2023-08-01T14:49:01.829Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-01T14:43:01.829Z',to:'2023-08-01T14:49:01.829Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I can see in the portal code as well as in the hosted portal code that we have accessed labels using `concept.label[vocabularyLocale]` in the past

But the response is structured as
```json
"label": [
  {
  "key": 177,
  "language": "es-ES",
  "value": "Introducida",
  "createdBy": "migration",
  "created": "2023-02-28T10:21:25.107153"
  }
]
```

@marcos-lg can you remember why we changed this. And when? I must admit I've completely forgotten. And apparently I've also missed it back then since the websites show raw values

**Comment by marcos-lg** [comment]
It was described here https://github.com/gbif/vocabulary/issues/117

This other issue is also relevant for the UI: https://github.com/gbif/vocabulary/issues/123
