### ISSUE TITLE
brachyplatys

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#489]
**brachyplatys**

-----
fbitem-94a6d58a8f6f4871dd15921c3a3d6d0250a8fccc

System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://www.gbif.org/what-is-gbif
Window size: width 1366 - height 676
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T04:08:27.820Z',mode:absolute,to:'2017-09-26T04:14:27.820Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T04:08:27.820Z',mode:absolute,to:'2017-09-26T04:14:27.820Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I cannot figure out what the user could have meant
