### ISSUE TITLE
About half the links to Darwin Core  on the Term Frequency list  404

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4890]
**About half the links to Darwin Core on the Term Frequency list 404**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2f899b24d46e49846d9039710f45a16f:936f5ab49e801bb977660fe9d2037ce149b0dbaa9a9811721ca04cd6ddebdc916aa6ff8052e149744afd8263e94477f934d9c2bfb91fae68c279b31609d826ef0d2b91c233336386799d6f5e0234f2a0dbab1cb71da55fbbec81d37aadef097482d1c112c797c92e783fb6fe00eeb26e0f90d1cf03f9382dd1e1601e55a708f80952274f4f9c0659eca5b2b0d23bf8ba) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2f899b24d46e49846d9039710f45a16f:936f5ab49e801bb977660fe9d2037ce149b0dbaa9a9811721ca04cd6ddebdc916aa6ff8052e149744afd8263e94477f934d9c2bfb91fae68c279b31609d826ef0d2b91c233336386799d6f5e0234f2a0dbab1cb71da55fbbec81d37aadef097482d1c112c797c92e783fb6fe00eeb26e0f90d1cf03f9382dd1e1601e55a708f80952274f4f9c0659eca5b2b0d23bf8ba)
System: Chrome 115.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator/1254f7f7-25d8-4be7-a0e4-85137adbe9a8
Window size: width 1920 - height 857
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-04T14:26:13.071Z',to:'2023-08-04T14:32:13.071Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-04T14:26:13.071Z',to:'2023-08-04T14:32:13.071Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
I think https://github.com/gbif/dwc-api/issues/3 would be part of the fix, although a workaround in the UI for unknown.org will be much faster to implement.

http://rs.col.plus/terms/acef/Country  is a surprise. We let the col.plus domain lapse as it was no longer being used, is this term part of a standard @mdoering / Thomas ?

**Comment by mdoering** [comment]
The term is, but not the URI. So we should just move it to the new catalogueoflife.org domain

**Comment by MattBlissett** [comment]
I think https://github.com/gbif/dwc-api/issues/3 would be part of the fix, although a workaround in the UI for unknown.org will be much faster to implement.

http://rs.col.plus/terms/acef/Country  is a surprise. We let the col.plus domain lapse as it was no longer being used, is this term part of a standard @mdoering / Thomas ?
