### ISSUE TITLE
Missing Research-grade Inaturalist Observation / Datasets. Regarding Opuntia polyacantha var. polyacantha Haw. (Cactaceae) discovered in eastern Ontario, Canada.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4892]
**Missing Research-grade Inaturalist Observation / Datasets. Regarding Opuntia polyacantha var. polyacantha Haw. (Cactaceae) discovered in eastern Ontario, Canada.**

Hi GBIF Technical Staff,

My name is Derek Stephen Hollingshead. I represent the Ottawa Cacti and Succulent Sanctuary as their founder, curator and research coordinator.

In 2018, a population of Opuntia polyacantha var. polyacantha Haw. (Plains Prickly Pear) was discovered and recorded on a private land trust property, in the Thousand Islands region of eastern Ontario, Canada. 

A five year study determined the existence of approximately 20 micro colonies that included upwards of 270-280 present individuals. This population is over 1800km disjunct from what was previously known as the extent of the species’ natural range; comparable to the isolated Opuntia fragilis (Nutt.) Brittle Prickly Pear population found in Kaladar, ON. (Beschel 1967, Staniforth and Frego 2000, Staniforth et al. 2002, Mottiar et al. 2015)

The species natural range and spatial boundaries including western Canada. Although Argus and White 1977 referenced O. polyacantha Haw. as an "excluded species of Cactaceae - U/SI unconfirmed/situation incertaine" in their "Atlas of the Rare Vascular Plants of Ontario."

In September 2022, I donated a preserved specimen to the Queen's University Biological Station - Folwer Herbarium (QUBS). For morphological comparison.

I am familiar with GBIF as a user. I regularly use the database to reference and cite preserved Opuntia cacti specimen and occurrences for my ongoing Opuntia conservation research. 

I am aware "research-grade" INaturalist observations are added to the GBIF database. Although, I cannot find a single one of my twenty research-grade, peer reviewed observations under the occurrence function of the GBIF search bar.
 
Could there potentially be some sort of unforseen filter that prevents my observation datasets from being upload onto GBIF?

Possibly because this is the first time this particular species has been observed in Ontario, Canada? Could links to my research-grade INaturalist observations or my user name be provide?

Thank you for your assistance,

Derek Stephen Hollingshead
Ottawa Cacti and Succulent Sanctuary
ottawacactisanctuary@gmail.com
1-613-897-0449
51 Creek’s End Lane
Nepean, Ontario, Canada
K2H 1C7

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f376fd7043ba63cacf22f321b88bd211:0415d21eb42e22a2749b9bfef8fd98073d246b1b4589b21e1f015a8fdcb610066003bd8c6b8c066f7e695b94f9ff3acb83455774c1bff42b2eb8865ee04f2ed1ea9ac60eb276de7fdda49ebfe1737f6276a9da9921d9b8a2f34e7636423d5c447b4181b8de6516ea929ebba355ee4e70459f1af6e7552efb7a71a82410947692215986ec2986cd59284a4397d8d2d237) - [Send email](https://www.gbif.org/api/feedback/user/mailto/f376fd7043ba63cacf22f321b88bd211:0415d21eb42e22a2749b9bfef8fd98073d246b1b4589b21e1f015a8fdcb610066003bd8c6b8c066f7e695b94f9ff3acb83455774c1bff42b2eb8865ee04f2ed1ea9ac60eb276de7fdda49ebfe1737f6276a9da9921d9b8a2f34e7636423d5c447b4181b8de6516ea929ebba355ee4e70459f1af6e7552efb7a71a82410947692215986ec2986cd59284a4397d8d2d237)
System: Chrome Mobile 115.0.0 / Android 0.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 412 - height 777
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-06T20:25:04.358Z',to:'2023-08-06T20:31:04.358Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-06T20:25:04.358Z',to:'2023-08-06T20:31:04.358Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

All the research-grade open licensed observation on iNaturalist are automatically shared on GBIF,  usually every few weeks (the latest update is from the 27th of July). You can read more about what is shared on GBIF here: https://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7.
 
I found [one of your records on iNaturalist](https://www.inaturalist.org/observations/169529967), its associated license is “© Derek Stephen Hollingshead · all rights reserved”. This means that it won’t be shared on GBIF. The license associated with the observation itself needs to be CC0, CC-BY or CC-BY NC. [Here](https://www.inaturalist.org/posts/21407-how-to-simply-modify-licenses-at-inaturalist#:~:text=On%20the%20observation%20page%2C%20there,the%20%22edit%20license%22%20option.) is a link explaining how to change the license for observations.
