### ISSUE TITLE
recordedBy misspelling of F. Marie-Victorin

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4896]
**recordedBy misspelling of F. Marie-Victorin**

recordedBy is expressed as "F.Marie-Victoria (sic) & Rolland-Germain" whereas this should be "F.Marie-Victorin & Rolland-Germain" for Frère Marie-Victorin, http://www.wikidata.org/entity/Q2596174

-----

Github user: @dshorthouse
User: [See in registry](https://www.gbif.org/api/feedback/user/a7d06ead5d7c5b7ad7f398d2bfd511ed:f77abe4880bb047c769cc9cabd16700394fea40133cefe03fcad2b2eb99f8cdd15f9cb6dd5637dd06fb74855782e89278daf665d8545401603d069dfa2c893ccd1762ce38caf409f133c36c4f354738ef132177fd0af273a84e12500f675200b95c1757de3c839b02a72aab8c183cc7622c169ff4e1c77236b513f92d1992b61ce26bdd562cb4644d50950cf3e73f89437aaff9b7725b41adf788b1cecacfd49) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a7d06ead5d7c5b7ad7f398d2bfd511ed:f77abe4880bb047c769cc9cabd16700394fea40133cefe03fcad2b2eb99f8cdd15f9cb6dd5637dd06fb74855782e89278daf665d8545401603d069dfa2c893ccd1762ce38caf409f133c36c4f354738ef132177fd0af273a84e12500f675200b95c1757de3c839b02a72aab8c183cc7622c169ff4e1c77236b513f92d1992b61ce26bdd562cb4644d50950cf3e73f89437aaff9b7725b41adf788b1cecacfd49)
System: Chrome 115.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/4166400655
Window size: width 1624 - height 891
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-08T03:30:52.324Z',to:'2023-08-08T03:36:52.324Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-08T03:30:52.324Z',to:'2023-08-08T03:36:52.324Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 695cef75-b65f-4776-b2ed-74565eebb16e
publishingOrgKey: 055bd978-2daa-4543-b3f0-44e0e87e86ca

**Comment by ManonGros** [comment]
It looks like the data is now up to date.

**Comment by dshorthouse** [comment]
I'm not seeing that on the occurrence page or on the source, reference page. Perhaps you're seeing it somewhere else?

**Comment by ManonGros** [comment]
Thanks for double checking @dshorthouse I was mistaken, the issue is now reopened

**Comment by ktotsum** [comment]
contacted the publisher and the user from helpdesk on 2023-08-16.

**Comment by jennehmonkeh** [comment]
Thanks David!  I've corrected the spelling in the source.
