### ISSUE TITLE
Issues with drop downs when querying for occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#490]
**Issues with drop downs when querying for occurrences**

Searching for datasets under occurrences the drop down only includes 7 items when there are more. I have no way to see them all. Also they are cropped off and can't see entire description in dropdown. suggest making left panel expandable to the right and adding more drop down possibilities.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482

System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/search?dataset_key=d0e9b7eb-29a9-4695-bb13-22585df648a5&dataset_key=17411afb-5543-4d0a-8f36-47cb8322062e&dataset_key=cc7cd3f8-1ff5-4273-ad34-f89351392925&dataset_key=a6e35034-fca7-457f-888b-e6d97030dee5&advanced=1
Window size: width 1536 - height 686
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T09:50:21.119Z',mode:absolute,to:'2017-09-26T09:56:21.119Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T09:50:21.119Z',mode:absolute,to:'2017-09-26T09:56:21.119Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
**options**
The dropdown shows up to 10 items. If there is only 7 to see, then it is because there isn't more options (or there is a bug). In cases where there are 10 options or more I would think it fine to require the user to specify what dataset they are looking for. 

**cropping**
But since the text is cut off, datasets that have long almost identical names cannot be told apart. Titles should probably wrap as below

![screen shot 2017-09-26 at 12 41 19](https://user-images.githubusercontent.com/6759267/30856375-7512db6c-a2b8-11e7-8558-d7dc5e57d2e6.png)

**Comment by thomasstjerne** [comment]
I did a change that will remove already selected datasets from the search autocomplete.
So typing "tpwd harc" and hitting enter will select them one by one until the list is empty.

**Comment by MortenHofft** [comment]
I've changed styling so that it expands on active https://github.com/gbif/portal16/commit/2a5d90f9f9300706e6f56673baf935c05c6f58e5
