### ISSUE TITLE
I am struggling to get any meaningful data for a species when I download with  the 'simple' option. For example, I am searching for Python bivittatus. I set options to include coordinates and only in the use. On the table tab, I can see all the data. When I download, all i receive is several tabs related to taxon classification but no data.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4903]
**I am struggling to get any meaningful data for a species when I download with the &#39;simple&#39; option. For example, I am searching for Python bivittatus. I set options to include coordinates and only in the use. On the table tab, I can see all the data. When I download, all i receive is several tabs related to taxon classification but no data.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/dcace9b263fe511a31a8211f2f3ac35b:b9f03854c208679c9f014d553381ffa5b706fe382f3ad68c7015c225206dcff53a0fa1036909c68096d30a9bf7b1475bef03c5b9dfec1776ce5231d37db36db01f797a542342dbb23e2a86ac0412266b2e84d30773c7ad4edc3864ebac265dd18222969c0d6575415924055b9ec993ffd30571917fd4e60ee18228d9cdf7a0b94e8fc9acc6980ca20aa4e6fc1e71e1bf) - [Send email](https://www.gbif.org/api/feedback/user/mailto/dcace9b263fe511a31a8211f2f3ac35b:b9f03854c208679c9f014d553381ffa5b706fe382f3ad68c7015c225206dcff53a0fa1036909c68096d30a9bf7b1475bef03c5b9dfec1776ce5231d37db36db01f797a542342dbb23e2a86ac0412266b2e84d30773c7ad4edc3864ebac265dd18222969c0d6575415924055b9ec993ffd30571917fd4e60ee18228d9cdf7a0b94e8fc9acc6980ca20aa4e6fc1e71e1bf)
System: Chrome 115.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/map?continent=NORTH_AMERICA&has_coordinate=true&has_geospatial_issue=false&taxon_key=4820533&year=1899,2023&occurrence_status=present
Window size: width 1366 - height 651
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-09T12:57:46.191Z',to:'2023-08-09T13:03:46.191Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-09T12:57:46.191Z',to:'2023-08-09T13:03:46.191Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

I found [one of your downloads](https://www.gbif.org/occurrence/download/0145947-230530130749713) and clicked on the download button. I opened the file in excel following [these instructions](https://www.gbif.org/faq?question=opening-gbif-csv-in-excel). As far as I can see, the file contains the coordinates, coordinate uncertainty, date, etc. The file contains 50 columns. Were you looking for a column in particular?
