### ISSUE TITLE
Nomada lutea

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4904]
**Nomada lutea**

It appears that iNat records from the Nomada luteola 
complex (in eastern North America) are considered as Nomada lutea on GBIF, which appears to be a Russian species. https://www.inaturalist.org/observations/120870491

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/736e5471c4981eb9aae0234366bb264d:904aeb881dc9e32fcc299ce834abcb29a52d314054bd272238c1ca5f4215ca6292d8c3f07f273fbd362825ed47292b9a9c0f05f30dd543fb22e54ed2dec3d9edf408b8af00b1c82c784b2443601b153b7dd46353de57235ebf3c596dcb640ab4468ff6705985ade920e005b82773b941abbbae163b092f34d6d56b951940d7a3132e18febd00111939971fd92e4ac073) - [Send email](https://www.gbif.org/api/feedback/user/mailto/736e5471c4981eb9aae0234366bb264d:904aeb881dc9e32fcc299ce834abcb29a52d314054bd272238c1ca5f4215ca6292d8c3f07f273fbd362825ed47292b9a9c0f05f30dd543fb22e54ed2dec3d9edf408b8af00b1c82c784b2443601b153b7dd46353de57235ebf3c596dcb640ab4468ff6705985ade920e005b82773b941abbbae163b092f34d6d56b951940d7a3132e18febd00111939971fd92e4ac073)
System: Chrome 112.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/1344020
Window size: width 1512 - height 749
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-10T19:15:09.304Z',to:'2023-08-10T19:21:09.304Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-10T19:15:09.304Z',to:'2023-08-10T19:21:09.304Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ktotsum** [comment]
It is now interpreted as Nomada.
https://www.gbif.org/occurrence/4039380531
