### ISSUE TITLE
How can I submit a list of scientific names (genus, species) and  generate higher taxonomic rankings (family, order, class, and phylum)?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4905]
**How can I submit a list of scientific names (genus, species) and generate higher taxonomic rankings (family, order, class, and phylum)?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/348011d036e9a28e03dc1809f6d2e6ff:182da3c6654260467ff34983dd489eefbde204117ffb85ab97658affb077c95c1ce2343612dcdac59189318281f707ad2b5aae283165b21cfc55f90b8c9a6294b14a124f0f0662d4fc1a6aea61b454e1391ff566acc329037b2a63d3d5ed91e8) - [Send email](https://www.gbif.org/api/feedback/user/mailto/348011d036e9a28e03dc1809f6d2e6ff:182da3c6654260467ff34983dd489eefbde204117ffb85ab97658affb077c95c1ce2343612dcdac59189318281f707ad2b5aae283165b21cfc55f90b8c9a6294b14a124f0f0662d4fc1a6aea61b454e1391ff566acc329037b2a63d3d5ed91e8)
System: Chrome 114.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator/8be57c38-305c-4bd1-a687-d81ed1356a52
Window size: width 1960 - height 758
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-10T21:29:28.949Z',to:'2023-08-10T21:35:28.949Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-10T21:29:28.949Z',to:'2023-08-10T21:35:28.949Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

The simplest way to get the higher taxonomic ranks given a list of scientific names would be to use [our species matching tool.](https://www.gbif.org/tools/species-lookup) This tool is based on match function [the GBIF species API](https://www.gbif.org/developer/species#searching) which matches scientific names to the GBIF backbone taxonomy and returns the higher ranks available in the backbone.
Note that can also use the API directly.

To learn more about the species API, you can check [this blogpost](https://data-blog.gbif.org/post/gbif-species-api/). If you are interested in how the GBIF backbone taxonomy is build, you can check [this blogpost](https://data-blog.gbif.org/post/gbif-backbone-taxonomy/), and [this recorded webinar](https://www.gbif.org/event/42jbz2tRyrjzTF5B8pClKa/data-use-club-practical-sessions-name-matching-and-the-gbif-taxonomic-backbone).
