### ISSUE TITLE
Download stuck in "preparing"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4911]
**Download stuck in &quot;preparing&quot;**

Hello,
Any download that I start now is stuck in "Preparing" status while this stage usually lastsfor less than 20 seconds, now stuck in there for hours... Could youi help me understand what's happening? Thank you,
Badis

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/74fe9ba2306632df876967d11b6b72e1:f7358e155f0f45beb9f8b6cd5891108a8dc306c3eb7c12b86c96e83793a89ba1bff469871623da9cc58a8fef7baabc3ca0212f972df12c7343a1be5e3f902dac3e7f2caea7796f021916e203d39e12e96cded13a395479f1007a0abd47bb204b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/74fe9ba2306632df876967d11b6b72e1:f7358e155f0f45beb9f8b6cd5891108a8dc306c3eb7c12b86c96e83793a89ba1bff469871623da9cc58a8fef7baabc3ca0212f972df12c7343a1be5e3f902dac3e7f2caea7796f021916e203d39e12e96cded13a395479f1007a0abd47bb204b)
System: Firefox 115.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/user/download?offset=0&limit=20
Window size: width 1229 - height 662
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-13T06:05:05.861Z',to:'2023-08-13T06:11:05.861Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-13T06:05:05.861Z',to:'2023-08-13T06:11:05.861Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
The systems was under very heavy load on Sunday morning, which would have meant downloads weren't able to start within 20 seconds, or in some cases even 20 minutes.

I've changed the translation for "PREPARING" to "Queued" for the portal, which is a more accurate description of what that status means.

_Replied by email._
