### ISSUE TITLE
I was hoping to make a data visualisation showing the number of recorded animal presence records (human observation) in GBIF - the data shown filtered here: https://www.gbif.org/occurrence/charts?basis_of_record=HUMAN_OBSERVATION&taxon_key=1&occurrence_status=present

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4914]
**I was hoping to make a data visualisation showing the number of recorded animal presence records (human observation) in GBIF - the data shown filtered here: `https://www.gbif.org/occurrence/charts?basis_of_record=HUMAN_OBSERVATION&amp;taxon_key=1&amp;occurrence_status=present`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/dc097b0d2bd11c67df3a423603cca153:3e5e9de8b1f1ca3a79022ee1836ab1667912d8d0e8967c9f0907f08092f1f27b9c12f1742cf80b106fde2a1bb7f4544986be698890c8d4f72f94075f4e138c0a3407ed9b1ed2ef930e1a4f288d98dcfcd14b89898485a119409c93cddc8228b840869a2dab9c0e6812f121a5e9acfd812595b02cad42c59e2e0e5b11db379954943cd3a97845776a7261bde6ac9c6310) - [Send email](https://www.gbif.org/api/feedback/user/mailto/dc097b0d2bd11c67df3a423603cca153:3e5e9de8b1f1ca3a79022ee1836ab1667912d8d0e8967c9f0907f08092f1f27b9c12f1742cf80b106fde2a1bb7f4544986be698890c8d4f72f94075f4e138c0a3407ed9b1ed2ef930e1a4f288d98dcfcd14b89898485a119409c93cddc8228b840869a2dab9c0e6812f121a5e9acfd812595b02cad42c59e2e0e5b11db379954943cd3a97845776a7261bde6ac9c6310)
System: Chrome 115.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/faq?q=citation
Window size: width 1440 - height 758
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-14T15:31:27.783Z',to:'2023-08-14T15:37:27.783Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-14T15:31:27.783Z',to:'2023-08-14T15:37:27.783Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by spoonerf** [comment]
How would I cite such a summary table?

**Comment by ManonGros** [comment]
@spoonerf the easiest would be to generate a download for the underlying data. You can click on the download button and select a format. This will give you a citable DOI (you don't have to download the actual data).

@dnoesgaard do you have a better recommendation?

**Comment by dnoesgaard** [comment]
Normally, this would be my recommendation as well, however, for a query of this magnitude it would be a bit wasteful. Also considering that you're not really using the data in an analysis, I would probably just argue for a generic citation.

> GBIF.org (year) Human observation records `<url>`

or whatever format the journal requires.

**Comment by spoonerf** [comment]
Thanks for the advice. It would just be for a data visualisation. 

I work at [Our World in Data](https://ourworldindata.org/) and was hoping to make a chart showing that the countries with the most biodiversity records (from GBIF) aren't necessarily the ones with the most biodiversity. Keen to show correct attribution, sounds like that will be: 

> GBIF.org (year) Human observation records <url>
