### ISSUE TITLE
it would be good to be able to filter the publisher download activity by time

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#492]
**it would be good to be able to filter the publisher download activity by time**

Its really great to see the activity tab for publishers.  I'd find it even more useful if it was possilbe to be able to say ' in the last callender year how many downloads were requested using data from Kew?  or how many in 2016?

-----
fbitem-datasetcd6e21c8-9e8a-493a-8a76-fbf7862069e5
User provided contact info: a.paton@kew.org
System: Firefox 55.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/dataset/cd6e21c8-9e8a-493a-8a76-fbf7862069e5/activity
Window size: width 1152 - height 568
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T13:27:17.897Z',mode:absolute,to:'2017-09-26T13:33:17.897Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T13:27:17.897Z',mode:absolute,to:'2017-09-26T13:33:17.897Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you - That seems reasonable. I have created a general issue for introducing various ways of understanding dataset usage https://github.com/gbif/portal-feedback/issues/492
