### ISSUE TITLE
This dataset has been replaced, but

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4922]
**This dataset has been replaced, but**

This dataset 
https://www.gbif.org/dataset/e7dc4c60-7c5b-44b6-b3a8-e64624580039 
has been replaced by 
https://www.gbif.org/dataset/95e15b18-f762-11e1-a439-00145eb45e9a

But we do not show that anywhere, because I wouldn't know how to figure it out.

[The API for the dataset that is not deleted](https://api.gbif.org/v1/dataset/95e15b18-f762-11e1-a439-00145eb45e9a) says that it is a duplicate, but it is far more likely that you want to know what the new version is, than what the old version is. 

Is there a way to know? If not could we perhaps add it to the API?

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/7195ca08d5eeb21c3919737818d9d6bd:695cd3d6ae79619fed6c8a3dfed9d48214762cd778b59a1a0d112cbb9a7959c35ebc8c4197042077a107b49e5e499bf706394a915fb44814b68162b8eeba900f73b23a441f5a4d289929fb3d41b96b50eeac2beaa1789b0f22a94b1c52d0e973b710cfcb6aee01f8fe4e47634276fb37aaf4da665af88ee1ca158d66aea55e9c) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7195ca08d5eeb21c3919737818d9d6bd:695cd3d6ae79619fed6c8a3dfed9d48214762cd778b59a1a0d112cbb9a7959c35ebc8c4197042077a107b49e5e499bf706394a915fb44814b68162b8eeba900f73b23a441f5a4d289929fb3d41b96b50eeac2beaa1789b0f22a94b1c52d0e973b710cfcb6aee01f8fe4e47634276fb37aaf4da665af88ee1ca158d66aea55e9c)
System: Chrome 115.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/e7dc4c60-7c5b-44b6-b3a8-e64624580039
Window size: width 1727 - height 962
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-18T10:02:13.008Z',to:'2023-08-18T10:08:13.008Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-18T10:02:13.008Z',to:'2023-08-18T10:08:13.008Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
I have switched the direction of the link.

The portal is caching the view for a few minutes, but the staging portal now shows "Replaced by ..." on the deleted dataset.

I will also update the documentation to make clear the direction of the link.

**Comment by ManonGros** [comment]
Note that I try to leave comments explaining what we do (https://registry.gbif.org/dataset/95e15b18-f762-11e1-a439-00145eb45e9a/comment). The other dataset was supposed to be deleted by the ALA

**Comment by MortenHofft** [comment]
Oh, if it wasn't intended, then I can say that for my 3 random attempts this was the direction for all of them. It might be worth doing a search for those cases where a dataset is deleted and there is a dataset that points to it as being the duplicate then?

**Comment by MattBlissett** [comment]
You were very unlucky, as there were around 600 links in total, and 20 had problems — about half were in the wrong direction (now fixed) and the other half pointed to themselves (now removed).

**Comment by MortenHofft** [comment]
Thanks Matt - yes I noticed there was a couple of selfreferring once as well. I only looked at the first page, perhaps it is something that has happened recently
