### ISSUE TITLE
BUG, error in country code

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4923]
**BUG, error in country code**

Country code  is acting funny

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a0af88d6bd9b63d345b738297cc80b5f:42f2ac5b6c8de39737015b1dd4e8bc07ca6eb6bdb58ac9d79a50dc1aad08015df57a12bf304c1eb6a9dc145e8a6fc8c506370971d1d00d7deebbb06c2f1e7a0965d856f714940f4c30a7f1a4a4d6c1df5954a3850790a0ece29940abb9c2275f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a0af88d6bd9b63d345b738297cc80b5f:42f2ac5b6c8de39737015b1dd4e8bc07ca6eb6bdb58ac9d79a50dc1aad08015df57a12bf304c1eb6a9dc145e8a6fc8c506370971d1d00d7deebbb06c2f1e7a0965d856f714940f4c30a7f1a4a4d6c1df5954a3850790a0ece29940abb9c2275f)
System: Chrome 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/event/34mG2jgjIHNslIDV0ZMdro/next-generation-dna-barcode-workshop
Window size: width 2560 - height 1291
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-22T11:54:19.619Z',to:'2023-08-22T12:00:19.619Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-22T11:54:19.619Z',to:'2023-08-22T12:00:19.619Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
That is because it relies on the ID to be the isocode. That isn't a great idea, but since that was how data has been structured in the past, then the UI used that information. 

Surprisingly that is correct for new entries  as well, except for Taiwan and perhaps a few others. @dnoesgaard I can see you have created country entries, but they have the expected ID = isocode. How did you do that? Using the management API?

Anyway, I will change it to fetch the linked entry and use the isocode as one would expect it to.

**Comment by dnoesgaard** [comment]
We have two entries for this one, but only one of them has the right id (TW). I've changed it to the other now one.

However, other entries are linked to the "wrong" one without this problem:

[Replacing coffee with cocoa to overcome effects of climate change](https://app.contentful.com/spaces/uo17ejk9rkwj/environments/master/entries/kRSkocRGlIzLsDlwHtEPA)
    [Biodiversity Information Fund for Asia funds 13 new projects](https://app.contentful.com/spaces/uo17ejk9rkwj/environments/master/entries/6ocCy8ilSvWAoftM0D4NhO)
    [BioTIME: A database of biodiversity time series for the Anthropocene](https://app.contentful.com/spaces/uo17ejk9rkwj/environments/master/entries/6BSj7sjyWhg7AvVIFMG5aO)
    [Global patterns of stony coral diversity](https://app.contentful.com/spaces/uo17ejk9rkwj/environments/master/entries/2bck5Q1zaw0jNepoccbUcw)
    [Four contractors selected to provide project support in Asia](https://app.contentful.com/spaces/uo17ejk9rkwj/environments/master/entries/2GCWBqcly9TCvaIfek5bfb)
    [(closed) Call for proposals: regional s](https://app.contentful.com/spaces/uo17ejk9rkwj/environments/master/entries/3IbvunwRI1cCKifENZzZFt)

**Comment by MortenHofft** [comment]
Thanks. Those are not events I suspect - the other entries i have been sensible and used the resolved link. When I did the events i just used the ID apparently. And since it worked I didn't notice

**Comment by dnoesgaard** [comment]
Thanks. Should I worry about the country entries in Contentful where the id isn't the iso2?

**Comment by MortenHofft** [comment]
no you shouldn't. if more issues come up, then I should change that in code as well.

**Comment by dnoesgaard** [comment]
(For my own record)

```
                      id                      en-GB en-GB
1  64yci4ffs7FbhQdnhqfTk                     Kosovo    XK
2 1RpE2oDAWEUtGHItC3o5NU              Åland Islands    AX
3 7suir2snzvOWHA9DCuQ5dv Saint Martin (French part)    MF
4 151oufkvR8iQKoc2qi2oO0             Haiti (remove)    HT
5  9OuHO1w11Ys6EIsUeym0m                     Taiwan    TW
```
