### ISSUE TITLE
will the new Darwin Core terms (eventType, vitality) be available at rs.gbif.org?

### ISSUE THREAD

**Issue by ymgan** [gbif/portal-feedback#4924]
Hello,

Just a curious question about whether the new Darwin Core terms (e.g. eventType, vitality) will be available at rs.gbif.org ? 
I am wondering if I can wait (if it will be fairly soon) or proceed to publishing a dataset (for a paper) without these new terms and update it later.

Thanks a lot!!

**Comment by ktotsum** [comment]
Thank you for your question. Yes, we will support the new terms, but we don't have the exact schedule yet. 
The implementation can be tracked at: https://github.com/gbif/pipelines/issues/926
