### ISSUE TITLE
uat: misdirected publisher registration, and how to make uat more obviously different

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4926]
**uat: misdirected publisher registration, and how to make uat more obviously different**

We have a (first?) publisher registration that went to UAT instead of the production site. 

This is not a frequent error we encounter, so maybe not worth the effort and just an idea: could/should gbif-uat, like a test IPT, be stamped more visibly as being different from the production environment? The whole registration workflow here looks identical to gbif.org, and once on this site, it is not transparent that this is not "GBIF proper"

-----

User: [See in registry](https://www.gbif-uat.org/api/feedback/user/be022b6c16ea074c15870232c2aa5c56:cde4cd95fead947dc1158e728c49f195ef354f5cc49dfcd2de22919004d04fa58f51c7edd1ed2237f40ef59a55283db9a438c1bbebcb87bae538c68ba56492ecb5498b997232680c5813644b9a72df0610a044e2a412bfbaa9ac1b06bd8dae9a89b9b78b16be2f28cd08dcf67c0b6e7bf823211cf44772d94fea623a1a680ee5) - [Send email](https://www.gbif-uat.org/api/feedback/user/mailto/be022b6c16ea074c15870232c2aa5c56:cde4cd95fead947dc1158e728c49f195ef354f5cc49dfcd2de22919004d04fa58f51c7edd1ed2237f40ef59a55283db9a438c1bbebcb87bae538c68ba56492ecb5498b997232680c5813644b9a72df0610a044e2a412bfbaa9ac1b06bd8dae9a89b9b78b16be2f28cd08dcf67c0b6e7bf823211cf44772d94fea623a1a680ee5)
System: Firefox 116.0.0 / Windows 10.0.0
Referer: https://www.gbif-uat.org/publisher/fceaf181-3948-485b-81ee-a9416f8cfe09
Window size: width 1463 - height 682
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-24T07:56:27.839Z',to:'2023-08-24T08:02:27.839Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-24T07:56:27.839Z',to:'2023-08-24T08:02:27.839Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thanks @ahahn-gbif - I've changed the header to make it different and a popup in the start of a session.

<img width="369" alt="Screenshot 2023-08-28 at 16 58 52" src="https://github.com/gbif/portal-feedback/assets/6759267/86e9d916-fe59-48e9-9818-406ea76d1366">

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/5a3e354ffabb247d62b16cd12d3b5a9f6aaf1c6d
