### ISSUE TITLE
Help downloading audio files

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4927]
**Help downloading audio files**

Hi, Is it possible to download the audio files associated with the records?
The download only provides links

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3179871bc24b6acf6459c6a5fe9dbc9a:2b35a09114f946038b7a9be1cac680efb1a29184c0c4db2ec9694a75ebb3aee1c55a9167be299273dfe6ab2f320dc85f67899705e4c55c1e0cbeba2e71c72bc46adf5a4a2a6cfb048fe122abe5250b1d032c25e2ffb02eae6fa24d85a8ac4ca9) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3179871bc24b6acf6459c6a5fe9dbc9a:2b35a09114f946038b7a9be1cac680efb1a29184c0c4db2ec9694a75ebb3aee1c55a9167be299273dfe6ab2f320dc85f67899705e4c55c1e0cbeba2e71c72bc46adf5a4a2a6cfb048fe122abe5250b1d032c25e2ffb02eae6fa24d85a8ac4ca9)
System: Safari 16.5.2 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/map?country=AU&has_geospatial_issue=false&media_type=Sound&geometry=POLYGON((145.14502%20-35.8863,142.1501%20-35.9936,140.77191%20-38.29604,143.02472%20-39.81889,146.68223%20-40.02216,147.10629%20-37.29076,145.14502%20-35.8863))
Window size: width 1000 - height 945
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-24T10:24:30.273Z',to:'2023-08-24T10:30:30.273Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-24T10:24:30.273Z',to:'2023-08-24T10:30:30.273Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ktotsum** [comment]
(2023-08-25 contacted the user from helpdesk)

You can only get multimedia links associated with occurrences from GBIF. GBIF is a data aggregator, and we do not store the multimedia files (image, audio, and video content). The files are hosted by publishers or through third party platforms. Likewise, we do not hold any rights to the multimedia files. For any use of multimedia files, we recommend contacting the rights holders where applicable.
