### ISSUE TITLE
Dataset/Absence/BareGround

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#493]
**Dataset/Absence/BareGround**

Greetings

I am interested in publishing samplingEvent Datasets for our institution. Right now I am curating a dataset of observation data from a  ground vegetation transect monitoring event. If some of the events document things like "bare soil", "leaf litter" or anything that is not the presence of an organism, how would I record that? I assume there would be no associated occurrence record, as those require a scientific name. Would I simply record an event and record the details in eventRemarks? 

Sincerely,

Rick Levy

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c
User provided contact info: ricklevy21@gmail.com
System: Chrome 61.0.3163 / Windows 7 0.0.0
Referer: https://www.gbif.org/dataset/search?q=
Window size: width 1164 - height 848
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T17:37:47.411Z',mode:absolute,to:'2017-09-26T17:43:47.411Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T17:37:47.411Z',mode:absolute,to:'2017-09-26T17:43:47.411Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I've assigned you kbraak because I'm not of much help here. And you would be my go to.

**Comment by kbraak** [comment]
Replied to reporter, thanks.
