### ISSUE TITLE
Why could not download data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4931]
**Why could not download data**

Hi there,
I am making a large number of queries (187) using rgbif. It worked well for the first (and largest) 26 queries. However, after then, nothing would happen no matter how many times I have tried to run the code using rgbif::occ_download_quene(). Not running downloads in my "DOWNLOADS" page. The last successful download was 23 August 2023. What would be the reasons for this? Reaching the data storage limit in my account? Or reaching the query limit? Thank you for your help!
Best,
Daijiang

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4215af209f4750fe486a2634841a03ed:3a968790849daa4d7cc7bdb21650b6d1d44d1bf8f2d41188fe786cbc3dc659000d43067170a0d0f4ebc974b946eabfd97e46a1c68639130709994eaf5f5109d6d9be8e72b2245976f3141060880020f050d9c090e11918c7487ffe2505b91c74) - [Send email](https://www.gbif.org/api/feedback/user/mailto/4215af209f4750fe486a2634841a03ed:3a968790849daa4d7cc7bdb21650b6d1d44d1bf8f2d41188fe786cbc3dc659000d43067170a0d0f4ebc974b946eabfd97e46a1c68639130709994eaf5f5109d6d9be8e72b2245976f3141060880020f050d9c090e11918c7487ffe2505b91c74)
System: Safari 16.5.2 / Mac OS X 10.15.7
Referer: https://www.gbif.org/user/download
Window size: width 1736 - height 1335
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-25T15:52:10.262Z',to:'2023-08-25T15:58:10.262Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-25T15:52:10.262Z',to:'2023-08-25T15:58:10.262Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by MattBlissett** [comment]
occurrence-ws log shows "Invalid geometry: Self-intersection at or near point (4.9905, 52.4541, NaN)"

Replied by email.

**Comment by MattBlissett** [comment]
Possible improvement in https://github.com/ropensci/rgbif/issues/672
