### ISSUE TITLE
Sync or DQ problem on the series of seed plants checklist

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4932]
**Sync or DQ problem on the series of seed plants checklist**

There may be a  sync or data quality problem on the series of seed plants checklists from the International Centre for Integrated Mountain Development. Several of those list do not show records on GBIF but on they IPT they do see: http://rds.icimod.org:8080/hkh-bif/?search=seed&sort=name&order=asc

I downloaded one of those lists from GBIF and the IPT,  and I noticed it has missing id's which I find very odd as the IPT usually avoids such a problem.

@CamiSilver

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/81fed61309dc535dd739be34445238b2:5c13ba08f109524a50384d88f0c8894d2269d4b0ad9f238f883e5ed6a35d0918626943f557de31a14b09dc96c2ea441aaf3aa1db81909ddc2479f43a5f27f5a8ca99a27c4b444d84f93d47aacc3082bfafc6362dac989306f31ab40751841b52eb0a0fa0fe4cc6098bf4bc1ea381934e51f7239c5d73cccb95c5f17deb368db4a2935af5382e82087673d8a5c9744e12) - [Send email](https://www.gbif.org/api/feedback/user/mailto/81fed61309dc535dd739be34445238b2:5c13ba08f109524a50384d88f0c8894d2269d4b0ad9f238f883e5ed6a35d0918626943f557de31a14b09dc96c2ea441aaf3aa1db81909ddc2479f43a5f27f5a8ca99a27c4b444d84f93d47aacc3082bfafc6362dac989306f31ab40751841b52eb0a0fa0fe4cc6098bf4bc1ea381934e51f7239c5d73cccb95c5f17deb368db4a2935af5382e82087673d8a5c9744e12)
System: Firefox 116.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/dataset/search?offset=0&type=CHECKLIST&publishing_org=d33a9c4e-e33c-4311-a2fe-88dbdff7b4b9
Window size: width 1325 - height 712
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-28T17:55:10.953Z',to:'2023-08-28T18:01:10.953Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-28T17:55:10.953Z',to:'2023-08-28T18:01:10.953Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@lilee-sh It looks like those are ICIMOD datasets. The person who reported the issue is correct, we aren't indexing any records for a number of these checklist because they are missing values in the `taxonID` field. Do you have the time to follow up with ICIMOD? Otherwise let me know and I will contact them.

**Comment by lilee-sh** [comment]
@ManonGros Thanks for letting me know. I will follow up with ICIMOD to get these corrected.

**Comment by lilee-sh** [comment]
taxonIDs have been added to the records of all these checklist datasets and is now indexed.

**Comment by lilee-sh** [comment]
taxonIDs have been added to the records of all these checklist datasets and is now indexed.
