### ISSUE TITLE
Não faz o Download dos itens corretos

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4933]
**Não faz o Download dos itens corretos**

Ao pesquisar as ocorrências do grupo Triatominae na América do Sul, aparecem quase 20 mil resultados, contudo a guia de Download fica cinza e não permite o Downloader dos dados. Após apagar o que está escrito na barra de pesquisa, a opção de download fica disponível e aparentemente está tudo correto, tamanhos dos arquivos equivalentes e relatório de transferência com todas as informações corretas. O erro aparece ao tentar baixar os arquivos, seja ele pelo modo simples ou ficheiro Darwin core, onde sai dos 20mil e pega todos os animais do continente.

-----

Github user: @nicaciobasilio
User: [See in registry](https://www.gbif.org/api/feedback/user/0264863087cf568985040e5737a08ebc:e2b7dc0cc0470e980ac7123fbe154db31694b4eaada8c7657bc11c88d9e4c710042a74ee45d2ddd387642821eb681c9e04fec71183c07848b5cd4086466fd50eb5bb68069f094587c12d9607ef31bb8d3a830f3bc3d650b979f5249ff3af8203f6aa00d4dea9b08e3bd3abfec2a1001ecb131a47a14f7f7203576a97c3842a19f56f3f4404eec44fd5c09b3015f2c1f729cb75a8ee8cf35c8ac98414d391beca90d80a7b224abcd46573e8906ac1fcb5) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0264863087cf568985040e5737a08ebc:e2b7dc0cc0470e980ac7123fbe154db31694b4eaada8c7657bc11c88d9e4c710042a74ee45d2ddd387642821eb681c9e04fec71183c07848b5cd4086466fd50eb5bb68069f094587c12d9607ef31bb8d3a830f3bc3d650b979f5249ff3af8203f6aa00d4dea9b08e3bd3abfec2a1001ecb131a47a14f7f7203576a97c3842a19f56f3f4404eec44fd5c09b3015f2c1f729cb75a8ee8cf35c8ac98414d391beca90d80a7b224abcd46573e8906ac1fcb5)
System: Chrome 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/pt/occurrence/download?q=triatominae&continent=SOUTH_AMERICA&occurrence_status=present
Window size: width 1366 - height 629
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-28T22:15:26.420Z',to:'2023-08-28T22:21:26.420Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-28T22:15:26.420Z',to:'2023-08-28T22:21:26.420Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
(Contacted the user from helpdesk on 2023-08-29)

Download is only supported for structured search, so the name should be filled in the scientific name. However, subfamily names are not indexed in GBIF backbone taxonomy and, therefore Triatominae is not searchable as a scientific name on the portal. If you download records by searching a family name “Reduviidae”, the records associated with Triatominae can be filtered in the file using spreadsheets etc.
