### ISSUE TITLE
Field output in the occurrence.txt appears to have changed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4935]
**Field output in the occurrence.txt appears to have changed**

We have a script that pulls iNaturalist data using the rgbif R module and processes it for analysis. It seems that the format of the downloaded data has changed recently to no longer include the "identifier" field, which was critical to our workflow. I cannot find documentation stating that this field has been removed, but I have archived downloads and recent downloads that show it has been.

Has this field actually been removed? And is there a replacement field for it? Where do we find documentation providing information about these types of changes?

We are using the rgbif occ_download function for reference.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7838336f8150ff71bb3d1d29c05aa509:eab3aa21bae8003050f3654f0dede39ea67c3f8835378d9cec82ef77180b94297da9ab3e6cf7eeb768f5bacf7f709d42f091241de3e47d1e7a63e831b61ff8c0fa455c5faffe47553ea585ea6772071f007451a4134c5ab6a23293717a0ee06a3a2c5cfebc43ad4e1a041e707adc17b1) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7838336f8150ff71bb3d1d29c05aa509:eab3aa21bae8003050f3654f0dede39ea67c3f8835378d9cec82ef77180b94297da9ab3e6cf7eeb768f5bacf7f709d42f091241de3e47d1e7a63e831b61ff8c0fa455c5faffe47553ea585ea6772071f007451a4134c5ab6a23293717a0ee06a3a2c5cfebc43ad4e1a041e707adc17b1)
System: Chrome 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/data-quality-requirements-occurrences
Window size: width 2560 - height 1241
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-29T16:00:35.317Z',to:'2023-08-29T16:06:35.317Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-29T16:00:35.317Z',to:'2023-08-29T16:06:35.317Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
By email.

You are correct that the "identifier" field has been removed from Darwin Core Archive downloads made through GBIF.  The field was introduced unintentionally, and contained only internal identifiers used by data publishers when publishing the data — there was no expectation that the values in the "identifier" field would be stable over time, unique between datasets, or have any meaning.

These fields can be used to identify an occurrence:

- occurrenceID, if present, is provided by the data publisher and intended (by the publisher) to be used to identify occurrences.

- gbifID, which is present on all occurrence records though assigned by GBIF.  We make a best effort to keep these identifiers stable, but it does depend on what data we receive from publishers.

Is it a single dataset you were interested in, or were you using this field on many datasets?
