### ISSUE TITLE
how can I get an API key to use rgbif?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4937]
**how can I get an API key to use rgbif?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fb89727de8bb545822325fb42a05ca72:b29a1575097b65c19976360b37865e0e55aff95a8a379b735b8436f4622e598f48350b4fd2659e5d054113a7e282c199a061c70a08bcbc9791cafa4db7500a8d423036bcc3df19677cfc3c242a542c579cc06ef1a2b1b94570f31ef253b4e36a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/fb89727de8bb545822325fb42a05ca72:b29a1575097b65c19976360b37865e0e55aff95a8a379b735b8436f4622e598f48350b4fd2659e5d054113a7e282c199a061c70a08bcbc9791cafa4db7500a8d423036bcc3df19677cfc3c242a542c579cc06ef1a2b1b94570f31ef253b4e36a)
System: Safari 16.6.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/developer/summary
Window size: width 1512 - height 865
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-29T20:56:46.658Z',to:'2023-08-29T21:02:46.658Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-29T20:56:46.658Z',to:'2023-08-29T21:02:46.658Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by jhnwllr** [comment]
(responded via helpdesk) 

You don't need a API key just a user account. 
https://docs.ropensci.org/rgbif/articles/gbif_credentials.html
