### ISSUE TITLE
Occurrences in a dataset are not visibile when searching for species

### ISSUE THREAD

**Issue by CatiaMM** [gbif/portal-feedback#4938]
The occurrence status of species in the dataset [Intertidal macroalgae species distribution along the Northwestern Iberian coast in 2020/2021](http://ipt.gbif.pt/ipt/manage/resource.do?r=2021_iberianpeninsula) is not visible when searching for individual species even though the dataset is public. When downloading GBIF occurrence for a certain species, data from the above mentioned dataset is not included.

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us. I think it might be something with data or ingestion. @MattBlissett could you help?

Also, your IPT is outdated (2.5.6, current is 2.7.5) and needs to be updated.

**Comment by timrobertson100** [comment]
I'll move this to the GBIF Feedback as this isn't an IPT-related issue. 

Since [most of this dataset](https://www.gbif.org/occurrence/search?dataset_key=c1e31227-6595-4797-b75a-d9d9f75e4cca) are records of "absence of detection" I wonder if an `occurrenceStatus=PRESENT` filter was enabled @CatiaMM when you downloaded? Do you have an example download URL, please?

**Comment by CatiaMM** [comment]
Hi, thank you for your replies. 
Even in that case, ocurrenceStatus=PRESENT, there should be occurrences that are not there. 
The examples:
https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&taxon_key=5279840&geometry=POLYGON((-13.39854%2036.2338,-5.34393%2036.2338,-5.34393%2043.47571,-13.39854%2043.47571,-13.39854%2036.2338))
https://www.gbif.org/occurrence/search?has_geospatial_issue=false&taxon_key=5279115&geometry=POLYGON((-10.88148%2036.71451,-7.00907%2036.71451,-7.00907%2043.23462,-10.88148%2043.23462,-10.88148%2036.71451))

Cheers,
Cátia

**Comment by timrobertson100** [comment]
Thanks, @CatiaMM - that helped identify the issue.

Here is [an example](https://www.gbif.org/occurrence/3356293158) record that you would expect to appear in a search for the species.

Note that the `Asparagopsis armata Harvey, 1855` is being interpreted to `Asparagopsis Montagne, 1840` which seems odd. On a closer look at the DwC-A file the "space" between the genus and species is not actually a space. It is the unicode character `\xa0` (i.e. 160), which is the translation for `&nbsp;` the HTML non-breaking space character.

For sure it would be nice that GBIF.org handles this, but these aren't actually correctly formatted names in the source file. Is it possible to fix that at the source please @CatiaMM?

Thanks

CC @mdoering for info - an unusual one, we may want the parser to handle

**Comment by mdoering** [comment]
Interesting case. I have applied the generic string cleaning methods we use for importing also to the backbone matching service and extended it for unicode normalisation as implemented in the latest CLB code: https://github.com/gbif/checklistbank/commit/41bdaf4f4a04b6412c3c6d6a41513691c24e543d

**Comment by timrobertson100** [comment]
@CatiaMM I think this might be looking better now and both your example searches return records.
Can you please confirm the fix @mdoering made addresses it on our side, so we can close this issue? 

It would still be best to fix this in source data, as others will be using these files from your repository.

Thanks

**Comment by CatiaMM** [comment]
Yes, it addresses the issue. Thank you very much.

I will try to fix the files soon.

Cheers,
Cátia

**Comment by timrobertson100** [comment]
Thanks for confirming @CatiaMM - I'll close this issue now then
Best wishes
