### ISSUE TITLE
trouble downloading all fish occurrences from Texas and neighbor states.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#494]
**trouble downloading all fish occurrences from Texas and neighbor states.**

I'm using your online query interface to download occurrences of all fishes from Texas and adjacent states. When I construct the query on the left panel the resulting records that appear on the right seem correct. But when I attempt to download them there are almost no data contained in the file. Am I doing something wrong. If my query is incorrect then the records displayed shouldn't be showing up right?

I was able to download specific datasets (with dataset being the only parameter used) using this system without problem.

Here are my query parameters as copied from the DOI page that was created after I pressed the "download" button. 

 All must apply
State province Texas Texas / new mexico Texas state Texas/louisiana Texas, gulf of mexico Texas, united states of america Texas/oklahoma Texas? Louisana Louisiana Louisiana ? Louisiana/texas Louisiane Arkansas Arkansas, mississippi Arkansas, missouri Arkansas, oklahoma Oklahoma Oklahoma - texas Oklahoma? Mexico Mexico state Coahu ila Coahuila Coahuila / nuevo leã³n Coahuila de zaragoza Coahuila state Chihuaha Chihuahua Chihuahua / sonora Chihuahua ? Chihuahua state Chihuahua sw Nuevo len Nuevo leon Nuevo leon state Nuevo leã³n Nuevo león Nuevo mexico Nuevo mxico Tamaulipas Tamaulipas state Tamauilpas

Scientific name Actinopterygii Sarcopterygii Elasmobranchii Cephalaspidomorphi Holocephali Leptocardii Myxini

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: acohen@austin.utexas.edu
System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/search
Window size: width 1920 - height 901
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T18:41:06.804Z',mode:absolute,to:'2017-09-26T18:47:06.804Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T18:41:06.804Z',mode:absolute,to:'2017-09-26T18:47:06.804Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I just made a similar query
https://www.gbif.org/occurrence/download/0001152-170925132151566
Despite stating that there is `997,445 occurrences downloaded`, when downloading there is only 50 records included.

**Comment by AdamECohen** [comment]
Here is the link to the original query that didn't work: https://www.gbif.org/occurrence/download/0000364-170925132151566

**Comment by MortenHofft** [comment]
In case you are not aware:
The "state province” field. It is up to the publishers to fill it. Meaning that there can be records from those areas that aren’t labeled as such. for example [occurrence 1453390209](https://www.gbif.org/occurrence/1453390209)
You could consider complementing your search with a location filter (there might also be occurrences without coordinates, but labeled as being from Texas)

But – complex geometries don’t go well with the search APIs. And so you see that [this query for Texas fails](https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON%20((-101.812942%2036.501861,%20-100.000075%2036.501861,%20-100.000075%2034.563024,%20-99.923398%2034.573978,%20-99.698843%2034.382285,%20-99.57835%2034.415147,%20-99.260688%2034.404193,%20-99.189488%2034.2125,%20-98.986841%2034.223454,%20-98.767763%2034.135823,%20-98.570593%2034.146777,%20-98.488439%2034.064623,%20-98.36247%2034.157731,%20-98.170777%2034.113915,%20-98.088623%2034.004376,%20-97.946222%2033.987946,%20-97.869545%2033.851022,%20-97.694283%2033.982469,%20-97.458774%2033.905791,%20-97.371143%2033.823637,%20-97.256128%2033.861976,%20-97.173974%2033.736006,%20-96.922034%2033.960561,%20-96.850834%2033.845545,%20-96.631756%2033.845545,%20-96.423633%2033.774345,%20-96.346956%2033.686714,%20-96.149786%2033.840068,%20-95.936185%2033.889361,%20-95.8376%2033.834591,%20-95.602092%2033.933176,%20-95.547322%2033.878407,%20-95.289906%2033.87293,%20-95.224183%2033.960561,%20-94.966767%2033.861976,%20-94.868182%2033.74696,%20-94.484796%2033.637421,%20-94.380734%2033.544313,%20-94.183564%2033.593606,%20-94.041164%2033.54979,%20-94.041164%2033.018527,%20-94.041164%2031.994339,%20-93.822086%2031.775262,%20-93.816609%2031.556184,%20-93.542762%2031.15089,%20-93.526331%2030.93729,%20-93.630393%2030.679874,%20-93.728978%2030.575812,%20-93.696116%2030.438888,%20-93.767317%2030.334826,%20-93.690639%2030.143133,%20-93.926148%2029.787132,%20-93.838517%2029.688547,%20-94.002825%2029.68307,%20-94.523134%2029.546147,%20-94.70935%2029.622824,%20-94.742212%2029.787132,%20-94.873659%2029.672117,%20-94.966767%2029.699501,%20-95.016059%2029.557101,%20-94.911997%2029.496854,%20-94.895566%2029.310638,%20-95.081782%2029.113469,%20-95.383014%2028.867006,%20-95.985477%2028.604113,%20-96.045724%2028.647929,%20-96.226463%2028.582205,%20-96.23194%2028.642452,%20-96.478402%2028.598636,%20-96.593418%2028.724606,%20-96.664618%2028.697221,%20-96.401725%2028.439805,%20-96.593418%2028.357651,%20-96.774157%2028.406943,%20-96.801542%2028.226204,%20-97.026096%2028.039988,%20-97.256128%2027.694941,%20-97.404005%2027.333463,%20-97.513544%2027.360848,%20-97.540929%2027.229401,%20-97.425913%2027.262263,%20-97.480682%2026.99937,%20-97.557359%2026.988416,%20-97.562836%2026.840538,%20-97.469728%2026.758384,%20-97.442344%2026.457153,%20-97.332805%2026.353091,%20-97.30542%2026.161398,%20-97.217789%2025.991613,%20-97.524498%2025.887551,%20-97.650467%2026.018997,%20-97.885976%2026.06829,%20-98.198161%2026.057336,%20-98.466531%2026.221644,%20-98.669178%2026.238075,%20-98.822533%2026.369522,%20-99.030656%2026.413337,%20-99.173057%2026.539307,%20-99.266165%2026.840538,%20-99.446904%2027.021277,%20-99.424996%2027.174632,%20-99.50715%2027.33894,%20-99.479765%2027.48134,%20-99.605735%2027.640172,%20-99.709797%2027.656603,%20-99.879582%2027.799003,%20-99.934351%2027.979742,%20-100.082229%2028.14405,%20-100.29583%2028.280974,%20-100.399891%2028.582205,%20-100.498476%2028.66436,%20-100.629923%2028.905345,%20-100.673738%2029.102515,%20-100.799708%2029.244915,%20-101.013309%2029.370885,%20-101.062601%2029.458516,%20-101.259771%2029.535193,%20-101.413125%2029.754271,%20-101.851281%2029.803563,%20-102.114174%2029.792609,%20-102.338728%2029.869286,%20-102.388021%2029.765225,%20-102.629006%2029.732363,%20-102.809745%2029.524239,%20-102.919284%2029.190146,%20-102.97953%2029.184669,%20-103.116454%2028.987499,%20-103.280762%2028.982022,%20-103.527224%2029.135376,%20-104.146119%2029.381839,%20-104.266611%2029.513285,%20-104.507597%2029.639255,%20-104.677382%2029.924056,%20-104.688336%2030.181472,%20-104.858121%2030.389596,%20-104.896459%2030.570335,%20-105.005998%2030.685351,%20-105.394861%2030.855136,%20-105.602985%2031.085167,%20-105.77277%2031.167321,%20-105.953509%2031.364491,%20-106.205448%2031.468553,%20-106.38071%2031.731446,%20-106.528588%2031.786216,%20-106.643603%2031.901231,%20-106.616219%2031.999816,%20-103.067161%2031.999816,%20-103.067161%2033.002096,%20-103.045254%2034.01533,%20-103.039777%2036.501861,%20-103.001438%2036.501861,%20-101.812942%2036.501861)))

You could instead [draw a cruder estimate](https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&taxon_key=204&taxon_key=238&taxon_key=121&taxon_key=239&taxon_key=120&taxon_key=7375758&taxon_key=119&advanced=1&geometry=POLYGON%20((-109.09423828125%2031.323140440957427,%20-109.18212890625%2037.09681225368692,%20-94.63623046875%2037.09681225368692,%20-94.54833984375%2036.569217971443635,%20-90.120849609375%2036.50742854183726,%20-90.02197265625%2036.32176422120382,%20-90.32958984375%2036.02911059663187,%20-89.549560546875%2036.03799493963659,%20-90.28564453125%2035.07271701786369,%20-91.07666015625%2033.76773195605407,%20-91.12060546875%2033.144450560077985,%20-90.98876953125%2032.145385562629315,%20-91.56005859375%2031.172859855662644,%20-89.67041015625%2031.059992641062365,%20-89.53857421875%2030.26618407355883,%20-88.65966796875%2029.542398322601738,%20-89.05517578125%2028.851890877683992,%20-91.56005859375%2029.389354660473675,%20-93.71337890625%2029.65702929559474,%20-94.85595703125%2029.27442054681336,%20-95.33935546875%2028.77488163974644,%20-96.65771484375%2028.00167680740309,%20-97.27294921875%2027.340054715183612,%20-97.22900390625%2025.84686509678058,%20-99.47021484375%2026.556593211456345,%20-101.35986328125%2029.618833448987818,%20-102.37060546875%2029.733377498237072,%20-103.11767578125%2028.851890877683992,%20-104.43603515625%2029.465905362203006,%20-105.09521484375%2030.682801890953776,%20-106.67724609375%2031.73517521911868,%20-108.12744140625%2031.69779270531287,%20-108.17138671875%2031.248030044481116,%20-109.09423828125%2031.323140440957427))) and possible filter out occurrences that are outside you desired boundaries afterwards (locally)

![screen shot 2017-09-28 at 10 12 45](https://user-images.githubusercontent.com/6759267/30955932-b1f29b16-a435-11e7-95ed-b942d7896e98.png)

**Comment by AdamECohen** [comment]
Morten,

Thank you so much for your help with this. I just tested it and it appears
to be working!

Perhaps you can give me some advise regarding what I am trying to do. I am
trying to get ALL Texas fish occurrence data that I can find via
aggregators. Do you think by querying both GBIF and iDigBio I'd get what's
out there. Other aggregators such as FishNet2, VertNet I believe funnel
data to GBIF and or iDigBio. Those are the two big aggregators I should be
checking right? Can you confirm my understanding that iDigBio contains only
specimen-based occurrence records, while GBIF contains those as well as
records from other sources. And I just noticed that iDigBio and GBIF differ
in their dataset holdings for specimen based records (noticed ANSP records
are not in GBIF but are in iDigBio).

So it sounds like the best way to get the records I want is to query GBIF
in two queries:
Query #1 on province for all variations of state names that are listed by
donors since many have spelling variations etc AND all fish higher taxa
names

Query #2 on bounding box drawn to include all neighbor states. And same
taxa as query 1.
Combine record sets and remove duplicates

I'll do the same in iDigBio. Then combine both datasets.

Adam

-------------------------

Adam E. Cohen
Ichthyology Collection Manager
Biodiversity Collections
<http://integrativebio.utexas.edu/about/collections> (Texas Natural History
Collections), University of Texas,

10100 Burnet Rd., PRC176/R4000
Austin, Texas 78758-4445 U.S.A.

Phone: Cell: 512 970 2479 | Office: 512 471-8845 | Lab: 512 471-4823

Websites: TNHC Ichthyology <http://www.utexas.edu/tmm/tnhc/fish/> | Fishes
of Texas <http://www.fishesoftexas.org/home>

**Comment by MortenHofft** [comment]
**iDigBio**
GBIF have most if not all the data that are in the iDigBio portal.
Here is an example of a publisher that are publishing to both iDigBio and GBIF

![screen shot 2017-09-29 at 10 44 00](https://user-images.githubusercontent.com/6759267/31008976-38d1300e-a506-11e7-8f33-bab49b6da4b3.png)
not linkable

![screen shot 2017-09-29 at 10 44 15](https://user-images.githubusercontent.com/6759267/31008985-412b43e8-a506-11e7-9841-9c264fab756d.png)
https://www.gbif.org/dataset/58d0f326-2e85-4d0a-a744-571461220f00

**fishnet2**
I cannot say, but based on a search and a catlognr from fishnet that record is also in GBIF
fishnet: not linkable
gbif: https://www.gbif.org/occurrence/search?q=IC.2708&catalog_number=IC.2708

**vertnet**
is also in gbif

I would be careful using the state province filter without further local validation/filtering.
There is [50,578 records in your state province filter](https://www.gbif.org/occurrence/search?has_coordinate=false&taxon_key=204&taxon_key=238&taxon_key=121&taxon_key=239&taxon_key=120&taxon_key=7375758&taxon_key=119&state_province=texas&state_province=texas%20~2F%20new%20mexico&state_province=texas%20state&state_province=texas~2Flouisiana&state_province=texas,%20gulf%20of%20mexico&state_province=texas,%20united%20states%20of%20america&state_province=texas~2Foklahoma&state_province=texas%3F&state_province=louisana&state_province=louisiana&state_province=louisiana%20%3F&state_province=louisiana~2Ftexas&state_province=louisiane&state_province=arkansas&state_province=arkansas,%20mississippi&state_province=arkansas,%20missouri&state_province=arkansas,%20oklahoma&state_province=oklahoma&state_province=oklahoma%20-%20texas&state_province=oklahoma%3F&state_province=mexico&state_province=mexico%20state&state_province=coahu%20ila&state_province=coahuila&state_province=coahuila%20~2F%20nuevo%20le%C3%A3%C2%B3n&state_province=coahuila%20de%20zaragoza&state_province=coahuila%20state&state_province=chihuaha&state_province=chihuahua&state_province=chihuahua%20~2F%20sonora&state_province=chihuahua%20%3F&state_province=chihuahua%20state&state_province=chihuahua%20sw&state_province=nuevo%20len&state_province=nuevo%20leon&state_province=nuevo%20leon%20state&state_province=nuevo%20le%C3%A3%C2%B3n&state_province=nuevo%20le%C3%B3n&state_province=nuevo%20mexico&state_province=nuevo%20mxico&state_province=tamaulipas&state_province=tamaulipas%20state&state_province=tamauilpas&advanced=1) without coordinates. Be aware that many of those that are also georeferenced looks [like either the coordinates or the state province is wrong](https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&taxon_key=204&taxon_key=238&taxon_key=121&taxon_key=239&taxon_key=120&taxon_key=7375758&taxon_key=119&state_province=texas&state_province=texas%20~2F%20new%20mexico&state_province=texas%20state&state_province=texas~2Flouisiana&state_province=texas,%20gulf%20of%20mexico&state_province=texas,%20united%20states%20of%20america&state_province=texas~2Foklahoma&state_province=texas%3F&state_province=louisana&state_province=louisiana&state_province=louisiana%20%3F&state_province=louisiana~2Ftexas&state_province=louisiane&state_province=arkansas&state_province=arkansas,%20mississippi&state_province=arkansas,%20missouri&state_province=arkansas,%20oklahoma&state_province=oklahoma&state_province=oklahoma%20-%20texas&state_province=oklahoma%3F&state_province=mexico&state_province=mexico%20state&state_province=coahu%20ila&state_province=coahuila&state_province=coahuila%20~2F%20nuevo%20le%C3%A3%C2%B3n&state_province=coahuila%20de%20zaragoza&state_province=coahuila%20state&state_province=chihuaha&state_province=chihuahua&state_province=chihuahua%20~2F%20sonora&state_province=chihuahua%20%3F&state_province=chihuahua%20state&state_province=chihuahua%20sw&state_province=nuevo%20len&state_province=nuevo%20leon&state_province=nuevo%20leon%20state&state_province=nuevo%20le%C3%A3%C2%B3n&state_province=nuevo%20le%C3%B3n&state_province=nuevo%20mexico&state_province=nuevo%20mxico&state_province=tamaulipas&state_province=tamaulipas%20state&state_province=tamauilpas&advanced=1)

![screen shot 2017-09-29 at 11 22 50](https://user-images.githubusercontent.com/6759267/31009656-90d2e278-a508-11e7-9722-b18928ac6d00.png)

Take occurrence [675489098](https://www.gbif.org/occurrence/675489098) as an example. It is stated as being located in Lake Ontario in State Texas.

I believe your best single query will be using only georeferenced records and ignoring the state province field. If you are very thorough you could do multiple queries and meticulously concatenate and filter them by their credibility. We try to flag issues that look suspicious. E.g. [coordinates and supplied country in conflict](https://www.gbif.org/occurrence/map?country=US&issue=COUNTRY_COORDINATE_MISMATCH&taxon_key=204&taxon_key=238&taxon_key=121&taxon_key=239&taxon_key=120&taxon_key=7375758&taxon_key=119&state_province=texas&state_province=texas%20~2F%20new%20mexico&state_province=texas%20state&state_province=texas~2Flouisiana&state_province=texas,%20gulf%20of%20mexico&state_province=texas,%20united%20states%20of%20america&state_province=texas~2Foklahoma&state_province=texas%3F&state_province=louisana&state_province=louisiana&state_province=louisiana%20%3F&state_province=louisiana~2Ftexas&state_province=louisiane&state_province=arkansas&state_province=arkansas,%20mississippi&state_province=arkansas,%20missouri&state_province=arkansas,%20oklahoma&state_province=oklahoma&state_province=oklahoma%20-%20texas&state_province=oklahoma%3F&state_province=mexico&state_province=mexico%20state&state_province=coahu%20ila&state_province=coahuila&state_province=coahuila%20~2F%20nuevo%20le%C3%A3%C2%B3n&state_province=coahuila%20de%20zaragoza&state_province=coahuila%20state&state_province=chihuaha&state_province=chihuahua&state_province=chihuahua%20~2F%20sonora&state_province=chihuahua%20%3F&state_province=chihuahua%20state&state_province=chihuahua%20sw&state_province=nuevo%20len&state_province=nuevo%20leon&state_province=nuevo%20leon%20state&state_province=nuevo%20le%C3%A3%C2%B3n&state_province=nuevo%20le%C3%B3n&state_province=nuevo%20mexico&state_province=nuevo%20mxico&state_province=tamaulipas&state_province=tamaulipas%20state&state_province=tamauilpas&advanced=1)

**Comment by AdamECohen** [comment]
Thanks, I really appreciate your help.

-------------------------

Adam E. Cohen
Ichthyology Collection Manager
Biodiversity Collections
<http://integrativebio.utexas.edu/about/collections> (Texas Natural History
Collections), University of Texas,

10100 Burnet Rd., PRC176/R4000
Austin, Texas 78758-4445 U.S.A.

Phone: Cell: 512 970 2479 | Office: 512 471-8845 | Lab: 512 471-4823

Websites: TNHC Ichthyology <http://www.utexas.edu/tmm/tnhc/fish/> | Fishes
of Texas <http://www.fishesoftexas.org/home>
