### ISSUE TITLE
homepage is a commercial

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4940]
**homepage is a commercial**

the listed website http://www.molluscsoftasmania.net/ is a commercial of some sort. At least it isn't the website for this dataset

the description also links a lot to this weird site. I see the entry was last edited 2 months ago

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/a545400f9c308065deea6a7281bf75d4:915ebc6e47ffe8e1246f80d68192e989198793998f27c23903b3b5dad3e15963ba639ad9dbc225da09cdca83ff67ebe28d58016e5b87b9a83e0d933a57d5a2725f86ceaa98f8fbef1d0f7bf0ea2c3051bd20102f9e2d2f39508efa9727c09c6cc54e52d8320ac56c1baa051229f4c00f48ff31cf05ad22188ed13713f48d24ca) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a545400f9c308065deea6a7281bf75d4:915ebc6e47ffe8e1246f80d68192e989198793998f27c23903b3b5dad3e15963ba639ad9dbc225da09cdca83ff67ebe28d58016e5b87b9a83e0d933a57d5a2725f86ceaa98f8fbef1d0f7bf0ea2c3051bd20102f9e2d2f39508efa9727c09c6cc54e52d8320ac56c1baa051229f4c00f48ff31cf05ad22188ed13713f48d24ca)
System: Chrome 116.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/3d5d2fc8-05bb-4d16-afb2-9d61a891e2d5
Window size: width 2077 - height 1550
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-30T13:07:00.426Z',to:'2023-08-30T13:13:00.426Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-30T13:07:00.426Z',to:'2023-08-30T13:13:00.426Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
Contacted the publisher from helpdesk on 2023-08-31.

**Comment by djtfmartin** [comment]
Ive just updated this on ALA and pushed the update to GBIF. New/corrected domain is https://molluscsoftasmania.org.au/
