### ISSUE TITLE
check on location of gbifid 2329775076

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4941]
**check on location of gbifid 2329775076**

Checked position of 2329775076. species doesn't exist here anymore, but a little further downstream the river (approx 250 m)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/715f5e8d9ceecefda8510692091410e2:a99f8a168dc58f83de2b337f65a4f187b5ea9b07886a69e0c38a8911605e81e49b8bd2d3b13648faa64db7799b438c747fcb8861a243937a3b06945b4c417dd48fa97ba05d3985654a83055dc248de8b9f27d648745be40c276f9e618cc95f03) - [Send email](https://www.gbif.org/api/feedback/user/mailto/715f5e8d9ceecefda8510692091410e2:a99f8a168dc58f83de2b337f65a4f187b5ea9b07886a69e0c38a8911605e81e49b8bd2d3b13648faa64db7799b438c747fcb8861a243937a3b06945b4c417dd48fa97ba05d3985654a83055dc248de8b9f27d648745be40c276f9e618cc95f03)
System: Firefox 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator
Window size: width 1858 - height 939
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-30T14:00:03.267Z',to:'2023-08-30T14:06:03.267Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-30T14:00:03.267Z',to:'2023-08-30T14:06:03.267Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
Contacted the publisher and the user from helpdesk on 2023-08-31.
https://www.gbif.org/occurrence/2329775076

**Comment by jhnwllr** [comment]
Annotations example

**Comment by jhnwllr** [comment]
The publisher seems to have fixed this one : 

`Coordinate uncertainty in metres : 250`
