### ISSUE TITLE
slow data download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4943]
**slow data download**

slow data download

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6a149d3034978c2e74e87e7961500d71:3667f7ca583d94fa354f8b7a5dea2d70592df6e2f33479b04eb4a1ad280c4990626c3e11d452406a928ec2d4e60dd3c597be4f7ddfd3d286e63172610f6fdae6c3f24b51a9f005a1f4ebe4769df7587c45938ce8faefeb5fab04aa3579e4bec55e51474a6d1c41212d555abdb161e77859dbb816706a0c96a733dc1bf367dbe8) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6a149d3034978c2e74e87e7961500d71:3667f7ca583d94fa354f8b7a5dea2d70592df6e2f33479b04eb4a1ad280c4990626c3e11d452406a928ec2d4e60dd3c597be4f7ddfd3d286e63172610f6fdae6c3f24b51a9f005a1f4ebe4769df7587c45938ce8faefeb5fab04aa3579e4bec55e51474a6d1c41212d555abdb161e77859dbb816706a0c96a733dc1bf367dbe8)
System: Chrome 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/zh/occurrence/download/0003436-230828120925497
Window size: width 1488 - height 742
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-31T09:25:06.066Z',to:'2023-08-31T09:31:06.066Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-31T09:25:06.066Z',to:'2023-08-31T09:31:06.066Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Download was created at 2023-08-31T09:23:20 UTC, and cancelled by the user at 2023-08-31T09:27:50 UTC.

They've done this several times. It does say downloads will take around 15 minutes.

**Comment by ktotsum** [comment]
contacted the user from helpdesk on 2023-08-31.
