### ISSUE TITLE
Remove point of contact from DMNS collections page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4944]
**Remove point of contact from DMNS collections page**

Need to remove Jeffrey Stephenson as a point of contact from the following Denver Museum of Nature & Science collections pages: birds, mammals, egg, and parasites

Thanks, John R. Demboski

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/daff5732e0268bd5cb2b3d945f979f84:26bf3a47375d27e10eb9247829082162cd8ce57f5c92e9f8a1f6f78634adea6a5d21837d3f51d6cb326273062994ea5f868ce6f7642fffb7eb289ee0e5ed25fd0bdfeda2b77e3cf2ee1b1a646a6e7429756a442de0b0d16ff6b93192ad21b9b7b02ede9b872cee1f0f20b6afb542a7e6c861691a3db1a51261d3817667b051b1803f5c44e85f6e35506954f18a19a69e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/daff5732e0268bd5cb2b3d945f979f84:26bf3a47375d27e10eb9247829082162cd8ce57f5c92e9f8a1f6f78634adea6a5d21837d3f51d6cb326273062994ea5f868ce6f7642fffb7eb289ee0e5ed25fd0bdfeda2b77e3cf2ee1b1a646a6e7429756a442de0b0d16ff6b93192ad21b9b7b02ede9b872cee1f0f20b6afb542a7e6c861691a3db1a51261d3817667b051b1803f5c44e85f6e35506954f18a19a69e)
System: Safari 16.6.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/user/profile
Window size: width 1498 - height 772
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-31T13:52:08.963Z',to:'2023-08-31T13:58:08.963Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-08-31T13:52:08.963Z',to:'2023-08-31T13:58:08.963Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The pages to updates are datasets and an Index Herbarium entry. I contacted the publisher by email.
