### ISSUE TITLE
depth records missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4947]
**depth records missing**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/315769a579312958bed5f5bd3ac17213:6b74f090449d1e2abd3aaa1323d0ec7d5a06760538af95ad4a63e95b056f16012bd47d1015ebc36f7a8cc83e5d29e2217ac0467960d034a5002d02b40ad59b1fcd282049ae3adaa5cd4cb238b1b54f13314f4be089054a1c54ee29f103e0945a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/315769a579312958bed5f5bd3ac17213:6b74f090449d1e2abd3aaa1323d0ec7d5a06760538af95ad4a63e95b056f16012bd47d1015ebc36f7a8cc83e5d29e2217ac0467960d034a5002d02b40ad59b1fcd282049ae3adaa5cd4cb238b1b54f13314f4be089054a1c54ee29f103e0945a)
System: Chrome 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0003746-230828120925497
Window size: width 1536 - height 747
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-01T10:38:34.953Z',to:'2023-09-01T10:44:34.953Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-01T10:38:34.953Z',to:'2023-09-01T10:44:34.953Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
Contacted the user from helpdesk on 2023-09-01.

**Comment by ktotsum** [comment]
There are three terms associated with depth (i.e. [minimumDepthInMeters](https://dwc.tdwg.org/terms/#dwc:minimumDepthInMeters), [maximumDepthInMeters](https://dwc.tdwg.org/terms/#dwc:maximumDepthInMeters), [verbatimDepth](https://dwc.tdwg.org/terms/#dwc:verbatimDepth)) for [Darwin Core Occurrence](https://rs.gbif.org/core/dwc_occurrence_2022-02-02.xml) and [Darwin Core Event](https://rs.gbif.org/core/dwc_event_2022-02-02.xml). None of these are mandatory fields for data publishing and therefore it is possible that these fields are blank in your downloads.
 
The columns depth accompanied with depthAccuracy are inferred from minimumDepthInMeters and maximumDepthInMeters. The definitions for these terms are explained [here](https://gbif.github.io/dwc-api/apidocs/org/gbif/dwc/terms/GbifTerm.html). We add issues and flags during the indexation process over the raw data ([this blog post](https://data-blog.gbif.org/post/issues-and-flags/)) and you can filter them in occurrence search.
 
You can find details on data processing [here](https://www.gbif.org/en/article/5i3CQEZ6DuWiycgMaaakCo/gbif-infrastructure-data-processing).
