### ISSUE TITLE
KML download?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4948]
**KML download?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6febf150ce8bb52672d1c72df53aea5e:0058c888f5689e1e3cbc69867f5d2829b5b981168f0d69a5fd3a707ca86cdbb64dfc4d56aee1ffd8937f5c0159468b4a0c9d47cf8773be943b49134f76f422d40c9386de8baccf34e162b7a25a72e89731271c29d836bdfb8f548dba55839895) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6febf150ce8bb52672d1c72df53aea5e:0058c888f5689e1e3cbc69867f5d2829b5b981168f0d69a5fd3a707ca86cdbb64dfc4d56aee1ffd8937f5c0159468b4a0c9d47cf8773be943b49134f76f422d40c9386de8baccf34e162b7a25a72e89731271c29d836bdfb8f548dba55839895)
System: Chrome 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/search?q=kml
Window size: width 2560 - height 1291
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-01T16:32:45.152Z',to:'2023-09-01T16:38:45.152Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-01T16:32:45.152Z',to:'2023-09-01T16:38:45.152Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
contacted the user from helpdesk on 2023-09-05.

**Comment by ktotsum** [comment]
KML service is not provided in our portal. You can [search occurrences](https://www.gbif.org/occurrence/search) by GeoJSON, WKT, a range of latitude/longitude and drawing on the map as described [here](https://github.com/gbif/portal-feedback/issues/3223).
