### ISSUE TITLE
Bad name rendered

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4949]
**Bad name rendered**

The subgenus Risophilus is not part of the name according to the backbone / API: https://api.gbif.org/v1/species/5757304

But it appears in the rendered name here: https://www.gbif.org/api/species/5757304/name

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fee5fc7393dfd796e2d5632b371969d3:a29dc5a9cf393c71e7bb2c85b23f2b667beb2da7cbc756d7d20822e4c68bffd1f7743b9aaaf2a158c3005fad7376395aff633f97e0fee102a7fa7b100931d8d7b7e767f0e837b5c6d71ea9501c012fec6d74ce883d005781d9f1da7dacb2d967b17f546a8977db1ee6a8668865d16414f3c4980e60fa11f4824d7ed84fbbc998) - [Send email](https://www.gbif.org/api/feedback/user/mailto/fee5fc7393dfd796e2d5632b371969d3:a29dc5a9cf393c71e7bb2c85b23f2b667beb2da7cbc756d7d20822e4c68bffd1f7743b9aaaf2a158c3005fad7376395aff633f97e0fee102a7fa7b100931d8d7b7e767f0e837b5c6d71ea9501c012fec6d74ce883d005781d9f1da7dacb2d967b17f546a8977db1ee6a8668865d16414f3c4980e60fa11f4824d7ed84fbbc998)
System: Safari 16.5.2 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/5757304
Window size: width 1609 - height 972
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-04T08:55:31.944Z',to:'2023-09-04T09:01:31.944Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-04T08:55:31.944Z',to:'2023-09-04T09:01:31.944Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
It is our attempt of creating italizesed names using the name usage endpoint. It might make sense to have an official species API endpoint for that at some point. Currently it lives in the portal16 project. Which will be replaced at some point. We can then carry that code to a new project of course, but a suppose it would be more ideal to have it somewhere else?
Already we now we have the issue that it is maintained 2 places. A Graphql resolver and in portal16. We should as a minimum move it to one service (probably Graphql) and use that. @thomasstjerne you wrote this code - what do you think is the preferred approach?

It is based on the name endpoint https://api.gbif.org/v1/species/5757304/name which states that "infraGeneric": "Risophilus",

**Comment by mdoering** [comment]
That makes sense. Just not that the infraGeneric is present at all. The infragenericName property should be empty in that case.

Actually the infraGenericName is very often wrong in the prod database.
135.000 names (not only backbone) are wrong. Ca 93.000 usages in the backbone

A deleted name, but terrible parsing: https://www.gbif.org/species/9406270
[Yarrowia der Walt & Arx](https://www.gbif.org/species/9406270)

**Comment by mdoering** [comment]
I have removed all those infragenerics for names of rank species, subspecies,variety or form and kept a table `_bad_infragenerics` in case we need to revert all or some of them.

The data model in the old clb shares names across datasets, so that can be an issue. For example the name Rhabditis bengalensis (Timm, 1956) Sudhaus, 1974 in WoRMS did have an infrageneric part:
https://www.gbif.org/species/154986405/verbatim

But it also did not show before and I think getting the backbone right is the most important aspect.
