### ISSUE TITLE
Incorrect numbering

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4950]
**Incorrect numbering**

https://www.gbif.org/composition/7zgSnALNuD1OvzanAUPG4z/hosted-portals-application-form

There is an error in the numbering on the page about the hosted portal application. Two number 4.

Regards,
Veronika

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/692ec857ae08e1eb3bee7e4df7090100:ea5090b19aa1532ed63a2ed2905a16f958388c0a19a4d766ec1149700f912316899503fe9e7d0201f895d3494b58f651741983e203582e2fa6411246408bb96190e30356eb98508c849b4c33cf969ffd6a77e365acc8f0d35eff4345bb52c90888873e571ff9636442e3c2a59d17e0313ce62a891817224d1c1949e48afb5de7698557cd54ff7f543050f8a458fffb41) - [Send email](https://www.gbif.org/api/feedback/user/mailto/692ec857ae08e1eb3bee7e4df7090100:ea5090b19aa1532ed63a2ed2905a16f958388c0a19a4d766ec1149700f912316899503fe9e7d0201f895d3494b58f651741983e203582e2fa6411246408bb96190e30356eb98508c849b4c33cf969ffd6a77e365acc8f0d35eff4345bb52c90888873e571ff9636442e3c2a59d17e0313ce62a891817224d1c1949e48afb5de7698557cd54ff7f543050f8a458fffb41)
System: Firefox 117.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 1047
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-05T09:46:34.480Z',to:'2023-09-05T09:52:34.480Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-05T09:46:34.480Z',to:'2023-09-05T09:52:34.480Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
not sure who this issue is for, maybe @MortenHofft ?
