### ISSUE TITLE
Accessing data from GBIF

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4957]
**Accessing data from GBIF**

1.How do I access and get the biodiversity data from GBIF ?
2. Is it free? 
3.What are the obligations and formalities for displaying the data publicly for commercial/educational/ buisness purpose.

4. What is the difference between data hosting and data publishing in context to GBIF and IPT

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c78b5bff3274d1168670995b0e3e0b42:fe4b8d344e17e06fc894f5043500135611ac0753b3b1c72d14b1a2d073aac4cab5a6b8aa145065bb179f5898865397273bc4c61633e6f90f11f231ca12a1dea1dbd04b38d32ffab6f56d9ccf3b16e42d8f20a416b92bae61e5e58bdcfbd2fd3356d74c5bc56c0044c49f512d6f4b5a19f43f83c61b78396276de85335c25606ae291a1d4b60558630998c10c29b66a27) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c78b5bff3274d1168670995b0e3e0b42:fe4b8d344e17e06fc894f5043500135611ac0753b3b1c72d14b1a2d073aac4cab5a6b8aa145065bb179f5898865397273bc4c61633e6f90f11f231ca12a1dea1dbd04b38d32ffab6f56d9ccf3b16e42d8f20a416b92bae61e5e58bdcfbd2fd3356d74c5bc56c0044c49f512d6f4b5a19f43f83c61b78396276de85335c25606ae291a1d4b60558630998c10c29b66a27)
System: Chrome 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/article/4qfLORxmM8kYOIwSYSMc2M/data-hosting
Window size: width 1536 - height 707
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-07T12:26:57.269Z',to:'2023-09-07T12:32:57.269Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-07T12:26:57.269Z',to:'2023-09-07T12:32:57.269Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
> Replied by email

1.	You can search and download occurrences (the observation or collection of a specimen at a given time and place) via [our occurrence search interface.](https://www.gbif.org/occurrence/search?occurrence_status=present&q=) Our [Data Use Club](https://www.gbif.org/data-use-club) has multiple recorded webinars on how to access and process data from GBIF. I suggest starting with [this one](https://www.gbif.org/composition/4Xm5cVB4y9n7U1GlUtKx8Q).
2.	You can access the data available on GBIF for free.
3.	Please check our [data user agreement](https://www.gbif.org/terms/data-user). Note that some occurrence records are published under a [CC BY-NC](https://creativecommons.org/licenses/by-nc/4.0/) license. This means that you must contact the data provider if you are planning to use the data for commercial purposes. The images displayed on GBIF might be under more restrictive licenses. Always check the license for and image or a record before using it.
4.	IPTs allow to package the data in a format that can be indexed by indexed by GBIF (Darwin Core Archives). The archives are hosted by the IPT and can be made publicly available. The IPTs are able to register the links to those archives on GBIF. This enable the data to be ingested by the GBIF ingestion system. Once the data is ingested and indexed on GBIF, we can say that it is published on GBIF. You can learn more about the tools that allow publishing on GBIF [here](https://data-blog.gbif.org/post/installations-and-hosting-solutions-explained/).
