### ISSUE TITLE
GBIF data validator: The EML document does not validate against the schema

### ISSUE THREAD

**Issue by ymgan** [gbif/portal-feedback#4958]
What does this error message from the GBIF data validator mean? 

`The EML document does not validate against the schema`

```
 cvc-complex-type.2.4.a: Invalid content was found starting with element 'abstract'. One of '{personnel}' is expected. 
```
![Screenshot 2023-09-07 at 15 00 47](https://github.com/gbif/portal-feedback/assets/11754081/dc920bdc-4249-43af-a070-7027b245a558)

Here is the report: https://www.gbif.org/tools/data-validator/9c5c9213-b5cf-496c-acd2-6b0ce0910509
Darwin Core Archive from this IPT resource: https://ipt.gbif.org/manage/resource?r=usamlr_cs-phoc (private-only, for testing)

**Comment by ktotsum** [comment]
This warning means that personnel is missing in the Project Data.
![image](https://github.com/gbif/portal-feedback/assets/138471170/5e094c5a-3c4c-4034-ac11-61839d241eb6)

**Comment by ymgan** [comment]
Thank you @ktotsum ~ Is it mandatory to have project personnel if there is project data?

**Comment by ktotsum** [comment]
Not strictly as a mandatory field, but we recommend filling out at least one personnel.
