### ISSUE TITLE
Excel template links are the old IPT wiki pages in the data validator

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4965]
**Excel template links are the old IPT wiki pages in the data validator**

Links in "Integrated Publishing Toolkit (IPT) Excel templates containing Checklist, Occurrence, or Sampling-event data" are the old IPT wiki links. Updating links to the latest IPT manual can be helpful especially for beginners.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b9d3a7c7d3130597da5eeb52c09756c4:6c761d6f60f28ebf69cbd0ceb7f2d1f74d74490ef69ca437f291e28273c1cd29625ff486a1d0422ef56f7d950f48089c0f0709c64c5d0c5027cbfad05802c9dd4235329c6d93ccdc148ada78455969cdaeca1bc040511ea2e0e9f60cef659711) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b9d3a7c7d3130597da5eeb52c09756c4:6c761d6f60f28ebf69cbd0ceb7f2d1f74d74490ef69ca437f291e28273c1cd29625ff486a1d0422ef56f7d950f48089c0f0709c64c5d0c5027cbfad05802c9dd4235329c6d93ccdc148ada78455969cdaeca1bc040511ea2e0e9f60cef659711)
System: Chrome 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/tools/data-validator/about
Window size: width 1280 - height 651
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-12T13:06:15.036Z',to:'2023-09-12T13:12:15.036Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-12T13:06:15.036Z',to:'2023-09-12T13:12:15.036Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
https://ipt.gbif.org/manual/en/ipt/latest/checklist-data#templates
https://ipt.gbif.org/manual/en/ipt/latest/occurrence-data#templates
https://ipt.gbif.org/manual/en/ipt/latest/sampling-event-data#templates

**Comment by dnoesgaard** [comment]
Links corrected.
