### ISSUE TITLE
Science Review 2021 doesnt appear in the search

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4966]
**Science Review 2021 doesnt appear in the search**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e7e0824bff970210c3923e0695ef44a3:1fff6cf455b3d4d514d7e7b199397f34755e4437cda059b3734678057b6ba6e1ac1e39d7377c3f1ff921e85609ebb115af4b90bd77cb29d2764d4e5db359a10be94a96e4fd124569e7809a8b76e03ab6eb2e8e47c34d1ce988b6745daa91c89e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/e7e0824bff970210c3923e0695ef44a3:1fff6cf455b3d4d514d7e7b199397f34755e4437cda059b3734678057b6ba6e1ac1e39d7377c3f1ff921e85609ebb115af4b90bd77cb29d2764d4e5db359a10be94a96e4fd124569e7809a8b76e03ab6eb2e8e47c34d1ce988b6745daa91c89e)
System: Chrome 117.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?q=science%20review&contentType=document
Window size: width 1920 - height 1051
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-14T06:13:02.950Z',to:'2023-09-14T06:19:02.950Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-14T06:13:02.950Z',to:'2023-09-14T06:19:02.950Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
I suspect that this may be a metadata / keywording issue (@kcopas)?

The report is available, here, via
https://www.gbif.org/science-review:
https://www.gbif.org/document/57InivSC2VzMFWbTJbqOsD/gbif-science-review-2021

**Comment by MortenHofft** [comment]
From contentful: `Discoverable in search results on GBIF.org? (required) : No`

I've changed it to `Yes`, as I didn't see any reason why it shouldn't be searchable. I hope that is okay, it seemed a bit silly not to do it when I was in there

**Comment by kcopas** [comment]
"There's your problem, right there…"

Tusind tak @MortenHofft !
