### ISSUE TITLE
Polygon for occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4967]
**Polygon for occurrences**

Hello,

I am trying to download a species list for species occurring in a specific region, defined by the following polygon: 

POLYGON((180 -45,172 -45,172 -48, 165 -48,165 -45,-63 -45,-63 -57,-77 -57,-77 -45,-180 -45,-180 -90,0 -90,180 -90,180 -45)). 

When I search via get data -> occurrences -> advance -> location -> geometry and add this polygon I get this error message "Failed. Your filters might be invalid or the servers having issues. Please try again and report the issue if it continues" even though the polygon shows up correctly on the mini map under the location tab. 

Could you help me identify what the problem is with my polygon and why this may be occurring? 

Thanks!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a05d68a8d9fdee7e67840081621ab24a:afd742a3fdbcdba66b592ab56d9c9a0f1555883f84d8bc4bad68cc9d584f381917eed3550e3e6d52273957b5306d859e7467df4394aae34bdf0a8494d9bef569f30343a44dcc73614e6567893d316f3a029de199f7818174dd297d47c165919298dd2aea6a3428a3edd6c337ea7c71c9) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a05d68a8d9fdee7e67840081621ab24a:afd742a3fdbcdba66b592ab56d9c9a0f1555883f84d8bc4bad68cc9d584f381917eed3550e3e6d52273957b5306d859e7467df4394aae34bdf0a8494d9bef569f30343a44dcc73614e6567893d316f3a029de199f7818174dd297d47c165919298dd2aea6a3428a3edd6c337ea7c71c9)
System: Chrome 116.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/faq?q=polygon
Window size: width 1314 - height 827
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-14T22:49:16.988Z',to:'2023-09-14T22:55:16.988Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-14T22:49:16.988Z',to:'2023-09-14T22:55:16.988Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
I haven't tested it, but I think the issue will be the very long straight lines — there is ambiguity on whether these lines go the short or long way around the globe.

A fix is to interpolate the lines, so there's a point every 60° or so.

(I haven't replied to the user.)

**Comment by MortenHofft** [comment]
[API says](https://www.gbif.org/api/occurrence/search?geometry=POLYGON((180+-45,172+-45,172+-48,165+-48,165+-45,-63+-45,-63+-57,-77+-57,-77+-45,-180+-45,-180+-90,0+-90,180+-90,180+-45)))
>{
"body": "Cannot parse simple WKT: POLYGON((180 -45,172 -45,172 -48,165 -48,165 -45,-63 -45,-63 -57,-77 -57,-77 -45,-180 -45,-180 -90,0 -90,180 -90,180 -45)) org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 180.0 -45.0, 172.0 -45.0 ) and LINESTRING ( 165.0 -45.0, 180.0 -45.0 ) [ (180.0, -45.0, NaN) ]"
}

**Comment by MortenHofft** [comment]
Adding a single point midway as Matt suggests indeed fix it
`POLYGON((180 -45,172 -45,172 -48,165 -48,165 -45,56 -45,-63 -45,-63 -57,-77 -57,-77 -45,-180 -45,-180 -90,0 -90,180 -90,180 -45))`
<img width="327" alt="Screenshot 2023-09-15 at 10 46 04" src="https://github.com/gbif/portal-feedback/assets/6759267/15cf7349-8b29-4fee-b4cb-00c1173dc274">

**Comment by ktotsum** [comment]
Contacted the user from helpdesk.
