### ISSUE TITLE
This species is marine. The citation locates it in the middle of Africa

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4969]
**This species is marine. The citation locates it in the middle of Africa**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/63f04aeda7abdacb0e7867d68ff80026:80253e3f87c2623642ec0ccc89de7467d70786005e1dadd17233e4067bc13cc852a1bbd9c957f964f96e5e9f023692506ef2576d27ca687e7f15cef43770e748b3c68684e481682757d7c85b7fdd739aa105f294ae671c7a734f83f524c534cca3390afb2b72dc9b2de6f6fdaa41f38f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/63f04aeda7abdacb0e7867d68ff80026:80253e3f87c2623642ec0ccc89de7467d70786005e1dadd17233e4067bc13cc852a1bbd9c957f964f96e5e9f023692506ef2576d27ca687e7f15cef43770e748b3c68684e481682757d7c85b7fdd739aa105f294ae671c7a734f83f524c534cca3390afb2b72dc9b2de6f6fdaa41f38f)
System: Chrome 116.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/es/occurrence/1055496324
Window size: width 1446 - height 684
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-15T13:07:40.965Z',to:'2023-09-15T13:13:40.965Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-15T13:07:40.965Z',to:'2023-09-15T13:13:40.965Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 7e380070-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 19456090-b49a-11d8-abeb-b8a03c50a862
Network keys: 17abcf75-2f1e-46dd-bf75-a5b21dd02655 99d66b6c-9087-452f-a9d4-f15f2c2d0e7e

**Comment by ktotsum** [comment]
Contacted the publisher and the user from helpdesk on 2023-09-18.

**Comment by ktotsum** [comment]
location information has been removed from the occurrence.
