### ISSUE TITLE
photo download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4973]
**photo download**

How can I download Holotype specimen photo?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3cd43f286cc3234fe35501dd80806c21:1f110a7836e74157ac70e66791dfd697eacff16bc46ad3a5f483b8a20331f2f111abf767740155e73ed0523b2a5f253090c28b31b80f43d4aaa9e658d4584bd7968cec5c05ab43410568e9aaae16e8d2d153664a8d0d671f23c05b7cae9a3d61) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3cd43f286cc3234fe35501dd80806c21:1f110a7836e74157ac70e66791dfd697eacff16bc46ad3a5f483b8a20331f2f111abf767740155e73ed0523b2a5f253090c28b31b80f43d4aaa9e658d4584bd7968cec5c05ab43410568e9aaae16e8d2d153664a8d0d671f23c05b7cae9a3d61)
System: Chrome 117.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/4062809323
Window size: width 2560 - height 963
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-18T07:54:50.648Z',to:'2023-09-18T08:00:50.648Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-18T07:54:50.648Z',to:'2023-09-18T08:00:50.648Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

Node handles: @albenson-usgs @sformel-usgs

**Comment by ManonGros** [comment]
> Replied by email

As you might already know, images aren’t hosted on GBIF. Instead, data providers will give the URLs to those images, which you can use to download images.
Here is an example explaining how to download an image for the holotype of Carex aphanolepis:
1.	You can find records for imaged type specimens in our occurrence search interface.
a.	Select the species that you would like to look a specimen for
b.	Select “image” in the media type filter
c.	Select “Holotype” (or other types) in the Type Status filter
d.	Here is how the selection looks like: https://www.gbif.org/occurrence/search?media_type=StillImage&taxon_key=2726105&type_status=HOLOTYPE&advanced=1
2.	Then click on the occurrence: https://www.gbif.org/occurrence/437978266
3.	Under each image, there should be a URL in the “identifier” field, you can right click and download the image (see screenshot)
<img width="694" alt="download_image" src="https://github.com/gbif/portal-feedback/assets/7677271/30b24542-0e32-4514-9fcf-dfe777dd49c3">

Note that some images may be place under restrictive licenses. Always check the license provided under the image that you would like to download.
