### ISSUE TITLE
Data validator is not showing any result, just the message "validation job ID was not found"

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#4976]
The data validator is not showing results, just a page like this:
<img width="742" alt="image" src="https://github.com/gbif/portal-feedback/assets/63795703/30c154ed-76ec-402f-a9ab-a20686d31ef5">
Source:[https://www.gbif.org/tools/data-validator/36596c0e-073b-4bab-9011-9039d4d1adf0](https://www.gbif.org/tools/data-validator/36596c0e-073b-4bab-9011-9039d4d1adf0)

This happens with new datasets, we tried with different ones and all have the same error and also happen with previously validated datasets. I do not know if there was some change in the data validator o maybe there is a bug in the indexing process.

Thanks in advance!

**Comment by MattBlissett** [comment]
Thanks, there was a problem with the webservice.  It is now working again.

(I think https://github.com/gbif/portal-feedback/issues/4977 is the same issue.)

**Comment by EstebanMH-SiB** [comment]
Thank you very much @MattBlissett, now is working perfectly, you are as diligent and fast as always!
