### ISSUE TITLE
gbif-uat test dataset 'Failed' error message when viewing occurrences

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#4978]
https://www.gbif-uat.org/occurrence/search?dataset_key=fcd30377-b400-44f5-8d39-437aef78aeab gives an error: "Failed: Your filters might be invalid or the servers having issues. Please try again and report the issue if it continues"

**Comment by MortenHofft** [comment]
Other datasets work fine
https://api.gbif-uat.org/v1/occurrence/search?dataset_key=76f8be6d-a1f5-474a-9f9f-dd6cf9cb18ad

But this one fails with a 404
https://api.gbif-uat.org/v1/occurrence/search?dataset_key=fcd30377-b400-44f5-8d39-437aef78aeab

**Comment by MattBlissett** [comment]
Thanks, fixed by https://github.com/gbif/gbif-api/commit/7ad00d144b9df4879f25451ce23d90ec848060c3, part of the work to introduce date intervals/ranges for eventDate (https://github.com/gbif/gbif-api/issues/4).
