### ISSUE TITLE
How can I submit species pictures or share location of orchid species which I found.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4979]
**How can I submit species pictures or share location of orchid species which I found.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c0a97f41f8d5265fcaaf280483f45a2e:38c2429f14c7fc132448a9af78755efcb0a5591b50fec6af1c298d3d38056b0c90a1fdfa13a41095d31ab3b4ea81de672e4d06c1036a019439e0da6d73e35a52d16e23ba8b3049e3dca9a0ef26dba4509403c586b0c17d0402f5e1fe3a1959e1088da83c36eee9f2b05509f12529b6de) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c0a97f41f8d5265fcaaf280483f45a2e:38c2429f14c7fc132448a9af78755efcb0a5591b50fec6af1c298d3d38056b0c90a1fdfa13a41095d31ab3b4ea81de672e4d06c1036a019439e0da6d73e35a52d16e23ba8b3049e3dca9a0ef26dba4509403c586b0c17d0402f5e1fe3a1959e1088da83c36eee9f2b05509f12529b6de)
System: Mobile Safari 16.6.0 / iOS 16.6.1
Referer: https://www.gbif.org/
Window size: width 390 - height 664
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-20T08:39:37.039Z',to:'2023-09-20T08:45:37.039Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-20T08:39:37.039Z',to:'2023-09-20T08:45:37.039Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

Node handles: @albenson-usgs @sformel-usgs

**Comment by ManonGros** [comment]
not sure why the US node is tagged here, the page reference is GBIF.org @MortenHofft any idea?

**Comment by ManonGros** [comment]
> Replied by email

If you are an amateur naturalist (meaning that you aren’t affiliated with an institution), the best is to share the data via a citizen science initiative that publishes data on GBIF. I would suggest uploading your photos and coordinates to https://www.inaturalist.org/ or https://observation.org/. I think you should also be able to share data via https://indiabiodiversity.org/. The data will automatically be made available on GBIF when it becomes research-grade and if it is shared under one of the following licenses:
* [CC0](https://creativecommons.org/publicdomain/zero/1.0), for data made available for any use without any restrictions
* [CC BY](https://creativecommons.org/licenses/by/4.0), for data made available for any use with appropriate attribution
* [CC BY-NC](https://creativecommons.org/licenses/by-nc/4.0), for data made available for any non-commercial use with appropriate attribution
 
If you are affiliated with an institution, you should make sure it is registered as a GBIF data publisher. You can register an institution via the following form: https://www.gbif.org/become-a-publisher

**Comment by MortenHofft** [comment]
No idea why we would spam US in this case. Looks like a bug at first glance
