### ISSUE TITLE
https://docs.gbif.org/ redirects to 404

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4981]
**https://docs.gbif.org/ redirects to 404**

As titled. Currently the URL redirects to https://docs.gbif.org/documentation-guidelines/en/%23current-documents which returns a 404.

-----

Github user: @ckotwn
User: [See in registry](https://www.gbif.org/api/feedback/user/10edcb0695630ee0bed2a24462666697:115c9d597788362de36281703e050d2df3160b5d5a4edeb3361c4e05e65d6cdc81475edc8f860ffad6ab8884485c644ec03612af99b5630dfbd64659dc761d756e6ca13f5b6189484df4c0d5e036c02109528fe886ed0e6d43a608bb4344ef4950ddd49ba1d8fdcb02e422deb8b8d7490752b7ace2fa8b02fea55a1d5aff7f1d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/10edcb0695630ee0bed2a24462666697:115c9d597788362de36281703e050d2df3160b5d5a4edeb3361c4e05e65d6cdc81475edc8f860ffad6ab8884485c644ec03612af99b5630dfbd64659dc761d756e6ca13f5b6189484df4c0d5e036c02109528fe886ed0e6d43a608bb4344ef4950ddd49ba1d8fdcb02e422deb8b8d7490752b7ace2fa8b02fea55a1d5aff7f1d)
System: Firefox 117.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/
Window size: width 1480 - height 1558
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-21T08:50:09.513Z',to:'2023-09-21T08:56:09.513Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-21T08:50:09.513Z',to:'2023-09-21T08:56:09.513Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Thanks @ckotwn, I've fixed it. Not sure how it was ever working...
