### ISSUE TITLE
Hello, how i visualice datasets downloaded from here?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4983]
**Hello, how i visualice datasets downloaded from here?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d01b7a2d867469fa068fdacf5a2dbdd5:a70e9abd3654cd290353c028c7a2318494008bffd7dbdf93cbfad924b0ed4de16713b0c823ae4a94f338ce722adcfce83fbf3a69710bbf46a9344264954a84590acf091ebf69abe0af7bc06078de00c694335d6fe9fc82d7fa9a0615194d1523686a584e2bbe088d93e805d6aa4034d9b1dd9bd285c0d6740f3f6c0eaa5b7ddd450ae2e04013667150a16b0409b46ba1) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d01b7a2d867469fa068fdacf5a2dbdd5:a70e9abd3654cd290353c028c7a2318494008bffd7dbdf93cbfad924b0ed4de16713b0c823ae4a94f338ce722adcfce83fbf3a69710bbf46a9344264954a84590acf091ebf69abe0af7bc06078de00c694335d6fe9fc82d7fa9a0615194d1523686a584e2bbe088d93e805d6aa4034d9b1dd9bd285c0d6740f3f6c0eaa5b7ddd450ae2e04013667150a16b0409b46ba1)
System: Chrome 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?contentType=dataUse
Window size: width 1366 - height 643
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-21T20:20:13.987Z',to:'2023-09-21T20:26:13.987Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-21T20:20:13.987Z',to:'2023-09-21T20:26:13.987Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
Contacted the user from helpdesk on 2023-09-22.

**Comment by ktotsum** [comment]
We have received the following URL in your question, which is the service for searching resources about data use but not the datasets themselves. 
https://www.gbif.org/resource/search?contentType=dataUse
 
You can search datasets [here](https://www.gbif.org/dataset/search) and species occurrences across the datasets [here](https://www.gbif.org/occurrence/search).
