### ISSUE TITLE
Hola buenas tarde, me podria decir como puedo ingresar unas coordenadas utm para poder localizar algunas especies?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4984]
**Hola buenas tarde, me podria decir como puedo ingresar unas coordenadas utm para poder localizar algunas especies?**

Hello, good afternoon, could you tell me how I can enter some UTM coordinates to be able to locate some species?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/12efcaed455758206b721f28b7ec3bfe:053a27d7b66c702dfc3a5cebf04a016a557f4bec48c8d8533cc5a7da18fe6a3f2751acb2fd29d816408220a404873451e3f211479ddf38f32ed8530a8e70a4108c11c9b667d35946969d138809c444c82e704e708051487ef8183896c45896c56081d347c45ce83bff87b30cc332d32a34b41650250eb70d79841449d6244ce303998fe82e46692d6467ad5597baf7ab64eea15f5cb9db5bf55e485f165abf96) - [Send email](https://www.gbif.org/api/feedback/user/mailto/12efcaed455758206b721f28b7ec3bfe:053a27d7b66c702dfc3a5cebf04a016a557f4bec48c8d8533cc5a7da18fe6a3f2751acb2fd29d816408220a404873451e3f211479ddf38f32ed8530a8e70a4108c11c9b667d35946969d138809c444c82e704e708051487ef8183896c45896c56081d347c45ce83bff87b30cc332d32a34b41650250eb70d79841449d6244ce303998fe82e46692d6467ad5597baf7ab64eea15f5cb9db5bf55e485f165abf96)
System: Chrome 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/faq
Window size: width 1600 - height 751
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-21T22:43:27.364Z',to:'2023-09-21T22:49:27.364Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-21T22:43:27.364Z',to:'2023-09-21T22:49:27.364Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

GBIF doesn’t support queries based on UTM coordinates. If you would like to query occurrences based on their geolocation, you can use decimal coordinate-based polygons (we support WKT). You can trace polygons directly on our map interface, see [this example](https://www.gbif.org/occurrence/map?geometry=POLYGON((-84.17417%205.45573,-61.31205%203.11756,-63.13062%2020.78374,-82.61538%2025.71988,-84.17417%205.45573))&occurrence_status=present) or paste and add polygons in the location filter. For more information on how to use our web interface, you can check our [Data Use Club](https://www.gbif.org/data-use-club) recorded webinar on the topic [here](https://www.gbif.org/composition/4Xm5cVB4y9n7U1GlUtKx8Q/data-use-club-practical-session-1-recording-and-resources).

Note that you can also query data with our API. If you are interested, we also have [a Data Use Club recorded webinar on the topic](https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa/data-use-club-practical-session-3-recording-and-resources).
