### ISSUE TITLE
About SRC obtained from Occurrence

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4986]
**About SRC obtained from Occurrence**

Hello, Im having problems to define wich is the SRC of origin of the datasets downloades from the pages. In my case Im trying to generate a vector points tile and the data of Lat and Long has different values (but very different)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ef517133042d362b4eb87849c62c5dda:2216cd67bc8d392c9e0cf2f32b29ac132147d23952293315cdddb1865f983d756ffd0d03028e34e935f1531614cc16c1903db7bce4bab3dd6accc575c8da2837b08c2468ecd3235b171e4e209984864127c46e9517fe2548a75a56fb664f16bba7dc62d525b76a519ecb24efbcc123d805555c1e3db1504cc3e53e12dd6d82b590d972d73eadbd01b0e1858c592c4da2) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ef517133042d362b4eb87849c62c5dda:2216cd67bc8d392c9e0cf2f32b29ac132147d23952293315cdddb1865f983d756ffd0d03028e34e935f1531614cc16c1903db7bce4bab3dd6accc575c8da2837b08c2468ecd3235b171e4e209984864127c46e9517fe2548a75a56fb664f16bba7dc62d525b76a519ecb24efbcc123d805555c1e3db1504cc3e53e12dd6d82b590d972d73eadbd01b0e1858c592c4da2)
System: Chrome 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/charts?country=AR&has_coordinate=true&has_geospatial_issue=false
Window size: width 1366 - height 643
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-22T14:24:53.121Z',to:'2023-09-22T14:30:53.121Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-22T14:24:53.121Z',to:'2023-09-22T14:30:53.121Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
Contacted the user from helpdesk on 2023-09-27.

**Comment by ktotsum** [comment]
The [search result](https://www.gbif.org/occurrence/charts?country=AR&has_coordinate=true&has_geospatial_issue=false) includes records flagged with “Geodetic datum invalid” and “Geodetic datum assumed WGS84”. These flags are added to records when we try to interpret geodetic datum from provided data. We conduct a reprojection into WGS84 if we can interpret geodetic datum (location interpretation is briefly explained [here](https://www.gbif.org/en/article/5i3CQEZ6DuWiycgMaaakCo/gbif-infrastructure-data-processing)). You can filter these issues on occurrence search (see [this blog](https://data-blog.gbif.org/post/issues-and-flags/)). We did [a webinar on data quality](https://www.gbif.org/event/2CAcHI4oxVK5ZgMnFszNUD/data-use-club-practical-sessions-data-quality) which explained some coordinate issues on GBIF. 

If you have doubts about interpreted data, you can download the original data provided by publishers (data before GBIF interpretation). You can find them in the verbatim.txt by selecting Darwin Core Archive format for downloads. Both coordinates and CRS are included in the file, if publishers provide them.
