### ISSUE TITLE
Link to create or commenting an issue redirects to dna derived data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4988]
**Link to create or commenting an issue redirects to dna derived data**

The link in this page redirects to dna derived data(https://github.com/gbif/doc-publishing-dna-derived-data/issues) instead of the repo to camera trap guide(https://github.com/gbif/doc-camera-trap-guide/issues)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/476a6c9166bdb658c8ea29da4c1df41c:364e6260ec6ba76642726f24ebaf7142f1a7459724bd8aed51dcf5d30c39f67890102df9ab3855efa030bc260ff03c2672c482dba87852a52ca2e8fea0dfc32e6d52e049ba390a39530451dd3e393d87061810070076096979434232057e51fb) - [Send email](https://www.gbif.org/api/feedback/user/mailto/476a6c9166bdb658c8ea29da4c1df41c:364e6260ec6ba76642726f24ebaf7142f1a7459724bd8aed51dcf5d30c39f67890102df9ab3855efa030bc260ff03c2672c482dba87852a52ca2e8fea0dfc32e6d52e049ba390a39530451dd3e393d87061810070076096979434232057e51fb)
System: Chrome 116.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/news/1tNrbZGtOLUw2rdUKsM8Se/guide-to-publishing-camera-trap-data-opens-for-community-peer-review
Window size: width 1344 - height 723
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-23T02:55:52.464Z',to:'2023-09-23T03:01:52.464Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-23T02:55:52.464Z',to:'2023-09-23T03:01:52.464Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Fixed, thanks!
