### ISSUE TITLE
How to report irregular content

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#499]
**How to report irregular content**

Hey GBIF team,
I am developing a smartphone app that queries your APIs. I've come across some irregular entries, and wanted to know if you would appreciate feedback about those. Ideally in some automated batch reporting function.

E.g.:  from the species API
key: 105153818
scientificName: "test organism"
canonicalName: "Test organism"

Best Regards,
Johannes

-----
fbitem-d7fe0c58772fa99501bfeba54604bc553eb4399f
User provided contact info: johannes@bionote.xyz
System: Chrome 61.0.3163 / Mac OS X 10.12.6
Referer: https://www.gbif.org/developer/species
Window size: width 1532 - height 899
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-30T11:42:11.919Z',mode:absolute,to:'2017-09-30T11:48:11.919Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-30T11:42:11.919Z',mode:absolute,to:'2017-09-30T11:48:11.919Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
User contacted by email.
