### ISSUE TITLE
iNat obscured data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4990]
**iNat obscured data**

Hello, 

I'm doing research on Ambystoma barbouri in Tennessee. They are listed in TN, and I was wondering how I could request to download observation data from iNaturalist that does NOT have the coordinates rounded? 

Thanks!
Anna

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a56a434cb5c4f885dbdf37d9f50a7c44:d10d1ff88d63a05510853f3ecc25f3e8973bc2d17ded5150bb0e507890b6b592cbf9156096930421d53b9aeda49c2bd63ceac0ad93302e8ec6bc57ac8afa17b2f2074d9ec69f847ff2dd08bdd9f841e60c69d0f859eef67873c29043cfd945d9) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a56a434cb5c4f885dbdf37d9f50a7c44:d10d1ff88d63a05510853f3ecc25f3e8973bc2d17ded5150bb0e507890b6b592cbf9156096930421d53b9aeda49c2bd63ceac0ad93302e8ec6bc57ac8afa17b2f2074d9ec69f847ff2dd08bdd9f841e60c69d0f859eef67873c29043cfd945d9)
System: Chrome 116.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7&taxon_key=2432017&occurrence_status=present&gadm_gid=USA.43_1
Window size: width 1536 - height 747
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-25T04:10:00.308Z',to:'2023-09-25T04:16:00.308Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-09-25T04:10:00.308Z',to:'2023-09-25T04:16:00.308Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
Contacted the user from helpdesk on 2023-09-25.
See also #4910

**Comment by ktotsum** [comment]
Additional question: Is there a way to access the unobscured coordinates?

Answer from helpdesk: The original data we received from iNaturalist are the data available on their website. We suggest contacting iNaturalist for requesting their unobscured data.
