### ISSUE TITLE
Good morning. I am trying to figure out how I can download the data but include all the metadata. When I download a particular group of data (I am interested in Whimbrel Preserved SPecimens for North America) I am getting that information but not metadata, I am particularly interested in Gender and Age

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4998]
**Good morning. I am trying to figure out how I can download the data but include all the metadata. When I download a particular group of data (I am interested in Whimbrel Preserved SPecimens for North America) I am getting that information but not metadata, I am particularly interested in Gender and Age**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/617bfb0870818da892e15fe8a8b84cc0:d844e5593b40756237356612ed3b8302504d2aa831d9bc085de3c5cf0ea6cb439c04503523079a656562a3df49974d5c20abc2966e9a5d235a03514e939cfba6523fceae7ff6a24c42d20c1c33a9b62c5bdf92a67337fb789e9c452945450b4a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/617bfb0870818da892e15fe8a8b84cc0:d844e5593b40756237356612ed3b8302504d2aa831d9bc085de3c5cf0ea6cb439c04503523079a656562a3df49974d5c20abc2966e9a5d235a03514e939cfba6523fceae7ff6a24c42d20c1c33a9b62c5bdf92a67337fb789e9c452945450b4a)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/70292095
Window size: width 1280 - height 881
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-03T15:51:36.272Z',to:'2023-10-03T15:57:36.272Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-03T15:51:36.272Z',to:'2023-10-03T15:57:36.272Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 830fd460-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 06fcbbf0-0562-11d8-b851-b8a03c50a862
Network keys: 99d66b6c-9087-452f-a9d4-f15f2c2d0e7e 
Node handles: @albenson-usgs @sformel-usgs

**Comment by ktotsum** [comment]
Replied to the user from helpdesk on 2023-10-11.

> If you select Darwin Core Archive format from download options, metadata xml files for each dataset are included in the dataset folder inside the downloads. Data of [sex](https://dwc.tdwg.org/terms/#dwc:sex) and [lifestage](https://dwc.tdwg.org/terms/#dwc:lifeStage) are included in occurrence.txt, although these terms can be left blank as they are not mandatory fields.
