### ISSUE TITLE
feedback popup doesn't show right in ie11

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5]
**feedback popup doesn&#39;t show right in ie11**

-----
fbitem-occurrence1265894407

System: Chrome 54.0.2840 / Mac OS X 10.11.6
Referer: https://demo.gbif-dev.org/occurrence/1265894407
Window size: width 1331 - height 1076

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/88d11c465cb9fab127653742001e000161473b37
ie11 doesn't support resetting params with :initial
That could be an issue elsewhere on the site as well.
