### ISSUE TITLE
Display multiple determinations & references better

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#50]
**Display multiple determinations &amp; references better**

There are cases with occurrences that have multiple identifications. Apart from the currently accepted or most recent one it is still worth showing this history nicely.

This record here also has the papers where it was cited as a holotype: https://demo.gbif.org/occurrence/419292570

A better, more compact way to show a reference would be good. The original french page does it well: https://science.mnhn.fr/institution/mnhn/collection/f/item/r10204

-----
fbitem-occurrence419292570

System: Chrome 55.0.2883 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/occurrence/419292570
Window size: width 1440 - height 742
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-24T10:38:11.470Z',mode:absolute,to:'2017-01-24T10:44:11.470Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-24T10:38:11.470Z',mode:absolute,to:'2017-01-24T10:44:11.470Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: b275a4c1-9859-4f3c-8ead-d86dde820fbc
publishingOrgKey: 2cd829bb-b713-433d-99cf-64bef11e5b3e

**Comment by mdoering** [comment]
See also #33

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/243
