### ISSUE TITLE
Countries do not appear in the endorsing drop down

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#500]
**Countries do not appear in the endorsing drop down**

I only see "Help me" and the list of organisations, but no country

-----
fbitem-ab3ccb02d409d7c1b6652ceee60e3937ce068b3e
User provided contact info: @timrobertson100
System: Chrome 61.0.3163 / Mac OS X 10.11.5
Referer: https://www.gbif.org/become-a-publisher
Window size: width 1251 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-02T07:49:27.394Z',mode:absolute,to:'2017-10-02T07:55:27.394Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-02T07:49:27.394Z',mode:absolute,to:'2017-10-02T07:55:27.394Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/1be2413f436b80eafae3680228f1e03ec7840fb0
