### ISSUE TITLE
Wondering why the thematic page is not coming up in search for GRSciColl.....

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5002]
**Wondering why the thematic page is not coming up in search for GRSciColl.....**

https://www.gbif.org/grscicoll

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d2aa8f5f37846ebcfc7e789626e62fea:8fe8180c8f55b0fb3bfeb590710e965e92d843aa14f4a5a18c089227c2083f76783bdbfd308169e932497b6d5542184fdbd24d41549543b629e58bdab112e451f56f7a9a1da827bf2ff1c0175461418ea3006075a372079d4592568edd312cf69b5c270d6576780b32b78ecccd176dc1d523cae48b78cb51d2a98b68a4ad2dc92257181f3d40023a217c039d16f3f2cd5085bde9e2a55ed61057291e932812a8) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d2aa8f5f37846ebcfc7e789626e62fea:8fe8180c8f55b0fb3bfeb590710e965e92d843aa14f4a5a18c089227c2083f76783bdbfd308169e932497b6d5542184fdbd24d41549543b629e58bdab112e451f56f7a9a1da827bf2ff1c0175461418ea3006075a372079d4592568edd312cf69b5c270d6576780b32b78ecccd176dc1d523cae48b78cb51d2a98b68a4ad2dc92257181f3d40023a217c039d16f3f2cd5085bde9e2a55ed61057291e932812a8)
System: Chrome 117.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/search?q=GRSciColl
Window size: width 1920 - height 1051
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-10T07:31:25.205Z',to:'2023-10-10T07:37:25.205Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-10T07:31:25.205Z',to:'2023-10-10T07:37:25.205Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by MortenHofft** [comment]
Probably because it is marked as being unsearchable in contentful

**Comment by MortenHofft** [comment]
@dnoesgaard I've changed the flag to allow it to be searchable. I hope you hadn't disabled it on purpose!

@akristensen I do not know if you have access to contentful, but I feel like you've asked a similar question recently where the answer was the same. When something cannot be found in search, then it is typically because it has been explicitly removed from search in Contentful.

**Comment by akristensen** [comment]
I just learned from @Marie ***@***.***> that https://www.gbif.org/grscicoll will be redirected to the new page in works by @Javier Gamboa ***@***.***>…..so probably it’s just me being impatient in this transition fase 😉
