### ISSUE TITLE
Download images of Cercis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5003]
**Download images of Cercis**

Hello,

I am an undergraduate student in biology at Université de Montreal. I'm doing a project on the Cercis genus phenology. I was wondering if there was a way to download the preserved specimen images directly into my computer. Since I'm only an undergraduate, I am not familiar with the API or python. 

Thank you,

Daphnée Sansregret

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/57541df57f5dab6458af0695e95bb7bc:ea0535f84f78a9468d0d3440d80843fc40040b6635343ed354c7dcba30cd80a8ce5a8c66a6d3e1ae844d87cfac1aacd7c97e83f634b29dc453e22bff1bfc7edb78c90ecb2e0f312758a947f8f928bc4d69abe03314fad02b18178bf8ef025ae03af998eb44c4077747eb457fb7e80d134beaee6a44afc19f63eff27a6a02b2a2f9bd920bec596d83ec92537ca0de7a422263759a5e6762d2e136b832e3284022) - [Send email](https://www.gbif.org/api/feedback/user/mailto/57541df57f5dab6458af0695e95bb7bc:ea0535f84f78a9468d0d3440d80843fc40040b6635343ed354c7dcba30cd80a8ce5a8c66a6d3e1ae844d87cfac1aacd7c97e83f634b29dc453e22bff1bfc7edb78c90ecb2e0f312758a947f8f928bc4d69abe03314fad02b18178bf8ef025ae03af998eb44c4077747eb457fb7e80d134beaee6a44afc19f63eff27a6a02b2a2f9bd920bec596d83ec92537ca0de7a422263759a5e6762d2e136b832e3284022)
System: Safari 16.6.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/system-health
Window size: width 1440 - height 820
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-10T12:46:10.620Z',to:'2023-10-10T12:52:10.620Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-10T12:46:10.620Z',to:'2023-10-10T12:52:10.620Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
Replied by email to the user from helpdesk on 2023-10-11.

> As you may know, GBIF is a data aggregator, and we do not host images, but the images are hosted by publishers or through third party platforms. Instead, URLs of the images are provided to GBIF which you can use for downloading images.

> Please note that images may have different licenses from occurrence records. We do not hold any rights to the images, and we recommend checking licenses of each image. 

> You can download URLs and licenses of images from occurrence search results. Go to the download tab and choose a Darwin Core Archive format. You can find the information in multimedia.txt from the downloaded file. 

> [Here]( https://www.gbif.org/occurrence/search?basis_of_record=PRESERVED_SPECIMEN&media_type=StillImage&taxon_key=2955919) is the occurrence search result for preserved specimens of Cercis genus which image links are provided.

> If you are interested in [download API](https://www.gbif.org/developer/occurrence#download), we recommend watching [our Data Use Club recorded webinar on the topic](https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa/data-use-club-practical-session-3-recording-and-resources). The webinar is based on [this blogpost](https://data-blog.gbif.org/post/gbif-api-beginners-guide/). As mentioned before, URLs of the images can be downloaded but not the images themselves.

> Downloading an image directly from occurrence record pages is explained [here](https://github.com/gbif/portal-feedback/issues/4973).
