### ISSUE TITLE
Abrupt lines end in Atlantic

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5009]
**Abrupt lines end in Atlantic**

Donald reminds that some of the southern lines in the Atlantic probably continue westwards and fixing those should (at least) improve the look of GBIF displayed maps

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/2a8f7cd661d75ea7dcb53e7359bf7e85:09d24a34829411b261bffda89ff4d94d7462fce1ff7996e29a76736a6dd07cf503bb7d700f885f46de88231487ea2384591902a1d2e55e861775d65117c3ba0cd20ce2af46813095a19952cc78288b65dcdd63d61279bb65aac36e1e90d26249cf2455eccd6f092b140cb2a864c9019e160855f439deef5dc911480a28940426) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2a8f7cd661d75ea7dcb53e7359bf7e85:09d24a34829411b261bffda89ff4d94d7462fce1ff7996e29a76736a6dd07cf503bb7d700f885f46de88231487ea2384591902a1d2e55e861775d65117c3ba0cd20ce2af46813095a19952cc78288b65dcdd63d61279bb65aac36e1e90d26249cf2455eccd6f092b140cb2a864c9019e160855f439deef5dc911480a28940426)
System: Chrome 117.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/6d56415d-b007-4273-9c74-bcd6b2467434
Window size: width 1745 - height 855
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-16T02:19:53.192Z',to:'2023-10-16T02:25:53.192Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-16T02:19:53.192Z',to:'2023-10-16T02:25:53.192Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@dschigel I don't think I understand the feedback. Are there issues with the data or is it just the map display?

**Comment by dschigel** [comment]
When we discussed it, we actually did not know the reason, data or display. One things we agreed on that no sampling design would be able to produce pattern like this and it does look strange
![image](https://github.com/gbif/portal-feedback/assets/14940052/4bdd45f2-549f-48c1-b044-0c73185543ce)

**Comment by timhirsch** [comment]
It seems fairly clear this is an issue for the data publisher, and for whatever reason these particular datasets (my understanding is they are plankton recorders collected by merchant shipping and collated by a UK marine laboratory) the records they send to GBIF cut off mid-Atlantic. Maybe the remaining locations are handled by a US equivalent institution? In any case the question should be addressed to them.

**Comment by ManonGros** [comment]
Thanks @dschigel looking at the original publication (https://doi.org/10.1016/j.pocean.2005.09.011), it seems like this could be due to variations on route `BC`. What do you think?
![1-s2 0-S0079661105001424-gr2](https://github.com/gbif/portal-feedback/assets/7677271/e9db98ea-65b4-4faa-9f8f-826b2c8ea3b2)

**Comment by ManonGros** [comment]
@dschigel @timhirsch, it is hard to tell from their display https://www.cprsurvey.org/data/map-data/ but it looks like that's the data they have collected. I don't see another set of records that we don't have.

**Comment by dschigel** [comment]
Thanks. The link you sent, Marie, shows sampling reaching all the way to N America. I agree with Tim this is something that can be  resolved with the publisher, In theory, one can imagine all these captains commanding "nets out, let's go home" right in the middle of Atlantic, but this is not my impression of how plankton monitoring is done in neutral waters.

**Comment by ManonGros** [comment]
@dschigel isn't it the same but just with a sightly different map projection?
<img width="1169" alt="Screenshot 2023-11-15 at 15 43 42" src="https://github.com/gbif/portal-feedback/assets/7677271/f6f09f35-e507-4147-a84e-de7a6cd87d0b">

<img width="752" alt="Screenshot 2023-11-15 at 14 58 21" src="https://github.com/gbif/portal-feedback/assets/7677271/038610e6-245b-4776-8cee-8ba22e1e2764">

**Comment by jhnwllr** [comment]
Image on website seems to imply that BC is one of the routes that ends abruptly...
![image](https://github.com/gbif/portal-feedback/assets/4245213/deabd1b9-70b6-4f99-926f-3c1551c42e89)

**Comment by jhnwllr** [comment]
![image](https://github.com/gbif/portal-feedback/assets/4245213/eb13ff42-4d45-4995-8521-70aa059b6903)
