### ISSUE TITLE
Endorsing node: add option specifically for OBIS

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#501]
**Endorsing node: add option specifically for OBIS**

In the section "Endorsing node", between the line with the suggested country" and the "Another node..."-dropdown, add a paragraph with the following text: "Publishers from the OBIS network, select this: Intergovernmental Oceanographic Commission of the UNESCO"

Background: the situation with OBIS needs special handling because the "OBIS" node as such has a participant status of "former", while the now wider-scoped "affiliate" member "Intergovernmental Oceanographic Commission of the United Nations Educational Scientific and Cultural Organisation" (a0206c54-ec0d-4f3f-9279-7db1d3eb1e7a). Someone looking for endorsement by OBIS would not easily make that connection, though, so that we need to make it rather explicit.

-----
fbitem-ab3ccb02d409d7c1b6652ceee60e3937ce068b3e
User provided contact info: ahahn-gbif
System: Firefox 56.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/become-a-publisher
Window size: width 1158 - height 874
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-02T09:21:35.185Z',mode:absolute,to:'2017-10-02T09:27:35.185Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-02T09:21:35.185Z',mode:absolute,to:'2017-10-02T09:27:35.185Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
@ahahn-gbif Should we include the other affiliate nodes as well then? Makes it somewhat consistent instead of yet another single exception. 
* Conservation of Arctic Flora and Fauna
* Data Observation Network for Earth

**Comment by ahahn-gbif** [comment]
It is an exception, really. The main purpose is to make it clear to a new publisher from the OBIS network which participant they need to choose, since the participant name does not name OBIS any longer. Other than that, affiliates are not by default included (also see participant list at https://www.gbif.org/the-gbif-network, and dropdown box filter on the endorsement page)

**Comment by MortenHofft** [comment]
Okay - I have added a magic OBIS GUID exception :) no other affiliates will show. And OBIS will be added to the list of options as the only one aside from the other associate participants

**Comment by MortenHofft** [comment]
From Skype
[02/10/17 13:54:54] Tim: To support publishers and review…. Please select one from below:


[ ] Help me with endorsement
[ ] DanBIF, Denmark
[ ] Request endorsement for OBIS related data (Endorsement provided by  Intergovernmental Oceanographic Commission of the UNESCO)

Or select another associated organisation:
[ lookup thing ]

---

[ ] Help me with endorsement
[ ] DanBIF, Denmark

Only one of those will show I guess
