### ISSUE TITLE
Hello, good morning!  My name is Guilherme and I'm from Brazil. Currently, I'm working on a project where I need to get the occurrence data from some species, to do that I'm using pygbif library, but when using the occurrence module searching using the datasetKey the results that I'm receiving don’t match with the ones that I have on an excel sheet. Can you help me understand what might be the problem?   Sincerely,   Guilherme Gomes

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5015]
**Hello, good morning! My name is Guilherme and I&#39;m from Brazil. Currently, I&#39;m working on a project where I need to get the occurrence data from some species, to do that I&#39;m using pygbif library, but when using the occurrence module searching using the datasetKey the results that I&#39;m receiving don’t match with the ones that I have on an excel sheet. Can you help me understand what might be the problem? Sincerely, Guilherme Gomes**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c1d44579108172c9170569f0d16d7ea0:196e83a686c7cc35ef0bd3c727e8a4327b6074752db755566428962d7019bf41613239d7ec554604713f50a212e91dd45b37e72ad819def331e87ad6a6ab215c6aa114292b042077514921a8c0e8c21fd85a239f4b599352cf17ebfb62632928c908e269f8c4218a45d98adf88859322bff42522d82db52395ef54a191554ef66ba43175a3dbfa3e9f76f5a1b95b8fee3b430e7d1d530f5495c47f88ca1f1305) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c1d44579108172c9170569f0d16d7ea0:196e83a686c7cc35ef0bd3c727e8a4327b6074752db755566428962d7019bf41613239d7ec554604713f50a212e91dd45b37e72ad819def331e87ad6a6ab215c6aa114292b042077514921a8c0e8c21fd85a239f4b599352cf17ebfb62632928c908e269f8c4218a45d98adf88859322bff42522d82db52395ef54a191554ef66ba43175a3dbfa3e9f76f5a1b95b8fee3b430e7d1d530f5495c47f88ca1f1305)
System: Chrome 117.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/user/profile
Window size: width 1440 - height 815
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-23T16:50:34.359Z',to:'2023-10-23T16:56:34.359Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-23T16:50:34.359Z',to:'2023-10-23T16:56:34.359Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by Guilhermetxgomes** [comment]
[Data_Processing_Reproducible.ipynb.zip](https://github.com/gbif/portal-feedback/files/13074204/Data_Processing_Reproducible.ipynb.zip)
I'm attaching my code here so you can take a look. I believe the reason might be the limit of 300 results, is it possible to get more results?

**Comment by ManonGros** [comment]
Hi @Guilhermetxgomes 
You should have received an email from me as well. I am pasting the same message here in case other people are interested to read it:

> It looks like you used the occurrences.search() function without paging through the result. The API limit for searches is of 300 occurrences per page and it doesn’t necessarily return the same 300 occurrences every time.
>
>
> I strongly suggest you use the download function instead. Not only you will be able to build better queries with no record limit, but you will get a download page and DOI. This means that you will be able to access the same data every time to refer to that download. In addition to that, you will be able to cite the DOI and credit the data provider’s whose data contributed to your work.
>  
> The latest version of PyGBIF has a download function which allows you to pass a query formatted as JSON. Alternatively, you could call directly the API with the [requests module](https://pypi.org/project/requests/).
> If you are interested, we have a Data Use Club recorded webinar on the GBIF API, see [this page](https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa/data-use-club-practical-session-3-recording-and-resources). This could be helpful to have in mind when working with the API.
