### ISSUE TITLE
Comment vérifier qu'une requête a déjà été exécutée ?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5018]
**Comment vérifier qu&#39;une requête a déjà été exécutée ?**

Bonjour,

Si j'exécute une commande de téléchargement d'occurence, elle est traitée par les serveurs de GBIF.

Mais j'aimerai pouvoir vérifier si une requête a déjà été réalisée et auquel cas directement récupérer la clé pour télécharger les données. 

Existe t'il un service sur l'API GBIF qui puisse vérifier si une requête a déjà été soumise à vos serveurs ?

Merci.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8ad5f4c590ae0922ec3d45dfaaaa634c:ff5b61da613eeb0e2a385be84686fa9ddb25c0b98db5f88a9e6da9dcd611dddeefff67f67387a25ddabfa43019b171fc49570afe7470745fab7b838cb46e09d2eea76f7c4bb2c543fa6c9f94de85228965e18afd1484e7e3effbe92873941720b36d5aef7e319d48e12a22e2c06603dd) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8ad5f4c590ae0922ec3d45dfaaaa634c:ff5b61da613eeb0e2a385be84686fa9ddb25c0b98db5f88a9e6da9dcd611dddeefff67f67387a25ddabfa43019b171fc49570afe7470745fab7b838cb46e09d2eea76f7c4bb2c543fa6c9f94de85228965e18afd1484e7e3effbe92873941720b36d5aef7e319d48e12a22e2c06603dd)
System: Firefox 118.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/fr/developer/occurrence
Window size: width 1920 - height 927
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-24T12:03:36.754Z',to:'2023-10-24T12:09:36.754Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-24T12:03:36.754Z',to:'2023-10-24T12:09:36.754Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

Il n’existe pas de fonction pour chercher les téléchargements déjà effectués par requête. La seule façon d’accéder aux téléchargements existants via l’API est par jeux de données dont les données sont incluses dans un téléchargement. Par exemple, ici la liste des téléchargements qui incluent des données du jeu de données intitulé [Fundación Carl Faust: Herbario del Jardí Botànic Marimurtra: HMIM ](https://www.gbif.org/dataset/7f2edc10-f762-11e1-a439-00145eb45e9a): https://api.gbif.org/v1/occurrence/download/dataset/7f2edc10-f762-11e1-a439-00145eb45e9a.

Dans quel but souhaitez-vous accéder aux téléchargements existants ? Est-ce pour économiser du temps ? Est-ce pour générer des statistiques ?

Notez que les données sur GBIF peuvent être mises à jour par les fournisseurs de donnée à n’importe quel moment. Cela signifie que la même requête à quelques heures d’intervalle peut donner des résultats différents.
