### ISSUE TITLE
Allow links to GBIF using native IDs

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#502]
**Allow links to GBIF using native IDs**

This might be possible, but if a publisher wanted to link to the GBIF view of their own record, it would be nice to have a URL for that.

e.g. 
https://www.gbif.org/occurrence/search?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7&occurrence_id=https:~2F~2Fwww.inaturalist.org~2Fobservations~2F4911324

returns 1 record, but perhaps it would be nice to have a service that links to the page itself that was usable in JS?

https://www.gbif.org/occurrence?datasetKey=...&occurrenceId=...

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: timrobertson100
System: Chrome 61.0.3163 / Mac OS X 10.11.5
Referer: https://www.gbif.org/occurrence/search?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7&occurrence_id=https:~2F~2Fwww.inaturalist.org~2Fobservations~2F4911324&advanced=1
Window size: width 1625 - height 960
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-02T10:14:29.222Z',mode:absolute,to:'2017-10-02T10:20:29.222Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-02T10:14:29.222Z',mode:absolute,to:'2017-10-02T10:20:29.222Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
+1 on this one

I've seen various implementations of this e.g. iNaturalist:
https://www.inaturalist.org/observations/4148287

![shaggy_mane__coprinus_comatus__observed_by_dnnyboy_04_05_pm_utc_on_september_19__2016_ _inaturalist_org](https://user-images.githubusercontent.com/21358085/31073575-be7308d2-a76c-11e7-81f4-3b15cb8d7fab.png)

**Comment by dnoesgaard** [comment]
This [implementation](https://github.com/inaturalist/inaturalist/blob/86070e1582d15fc52a9ff83cf3c46cc823ba9d7c/tools/gbif_observation_links.rb) seems to work by iNat downloading all their occurrences and matching GBIF id with the own...

**Comment by MortenHofft** [comment]
This of course is easily available by the API. And there is always the chance that there are multiple results. But if there is a need for it I have created this: https://www.gbif-uat.org/occurrence/first?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7&occurrence_id=https:%2F%2Fwww.inaturalist.org%2Fobservations%2F4911324

makes sense @timrobertson100 ? it simply redirects to the first occurrence that match the criteria. `I feel lucky`
