### ISSUE TITLE
problem with coordinates

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5020]
**problem with coordinates**

I have sent a data set, in GBIF format, for validation. 

GBIF mentions that two coordinates are incorrect : these are

 for Agdz on Morocco: N 30.7041 W 6.4531, indicated as ⁦30.7041 -6.4531

Where is the problem ? 

Thanks for hints on how  to correct this ! 

Gabriel

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/edc912f37100da4336b917ef171eb6c1:48f99841994fbcb07bfdc35f386d2b8ff2f1e786ef316a0b84a9b730c370eb1acf12483a7d32ebb2427b4a2c4bb4ec3ed3ce979a673c63171051ddea5339a335306e81175edd70b2ac214932a94eddb86d4a266e1e15aa285ac9b958f89309836a552d276082f4e9a31d400d41c8afd9f565108a8b99d876cdc7575d317e9b2a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/edc912f37100da4336b917ef171eb6c1:48f99841994fbcb07bfdc35f386d2b8ff2f1e786ef316a0b84a9b730c370eb1acf12483a7d32ebb2427b4a2c4bb4ec3ed3ce979a673c63171051ddea5339a335306e81175edd70b2ac214932a94eddb86d4a266e1e15aa285ac9b958f89309836a552d276082f4e9a31d400d41c8afd9f565108a8b99d876cdc7575d317e9b2a)
System: Firefox 119.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/data-quality-requirements-occurrences
Window size: width 1920 - height 955
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-26T19:20:49.440Z',to:'2023-10-26T19:26:49.440Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-26T19:20:49.440Z',to:'2023-10-26T19:26:49.440Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
Contacted the user from helpdesk to get more information.

**Comment by ktotsum** [comment]
(replied by email from helpdesk)

“30.7041” for dwc:decimalLatitude and “-6.4531” for dwc:decimalLongitude are correct input. Invalid values were included in the coordinates (an extra character was found in front). You can usually spot them by opening the CSV file with text editors.
