### ISSUE TITLE
Downloading data from given maps

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5021]
**Downloading data from given maps**

I would like to know how I can obtain the given point location data for the Ambystoma laterale for imput into a GIS project. So far I found two maps with good salamander point data but have not found any way to pull those points or download any data for use.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a64037d05a14449fbb2d3ec0c039c9c0:e080c6752c3d2b4dd9c01ef9961c17c38321ac500cd96c2201431ae9f373ba07e3410d922e33deed11263d7e95585a56b0f2c9b3f671be941c940336469ca78d77a4f69d2567ec33803f6a12901f72d83c63789862d2f715807cc1fa881a174a23c1bec84dc430deefbc6f6c1d49ec36b53ecc25661e5905ba192d066e7d3785) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a64037d05a14449fbb2d3ec0c039c9c0:e080c6752c3d2b4dd9c01ef9961c17c38321ac500cd96c2201431ae9f373ba07e3410d922e33deed11263d7e95585a56b0f2c9b3f671be941c940336469ca78d77a4f69d2567ec33803f6a12901f72d83c63789862d2f715807cc1fa881a174a23c1bec84dc430deefbc6f6c1d49ec36b53ecc25661e5905ba192d066e7d3785)
System: Chrome 118.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1920 - height 963
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-26T19:42:17.417Z',to:'2023-10-26T19:48:17.417Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-26T19:42:17.417Z',to:'2023-10-26T19:48:17.417Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
(replied by email from helpdesk)

You can download data from occurrence search. On [the search result page](https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&taxon_key=2432014), click on the DOWNLOAD button. You need a GBIF account for downloading data.
![how_to_download](https://github.com/gbif/portal-feedback/assets/138471170/56c4d0bb-fdbb-42ee-bcca-87d1d4fb7fd4)
Please aware that you may encounter coordinate issues with downloaded data and data cleaning can be required (see videos on data quality [here](https://www.gbif.org/composition/3CF30vzt0K8AjoWOnmJsDR/data-use-club-practical-session-2-recording-and-resources-2)).
