### ISSUE TITLE
Which event fields appear in occurrence records after GBIF processing?

### ISSUE THREAD

**Issue by Mesibov** [gbif/portal-feedback#5024]
Darwin Core archives often contain an event.txt and an occurrence.txt. Sometimes these are only tied together by eventID. In other words, the only event field in occurrence.txt is eventID.

In many archives, occurrence.txt contains event fields which are "repeated" from event.txt, such as eventDate, decimalLatitude, decimalLongitude etc.

How does GBIF process these archives to get occurrence records? Are all event fields in occurrence.txt completely ignored, and event fields in the processed record come only from event.txt, based on eventID, or are some event fields in occurrence.txt accepted in the processed occurrence records?

Does the processing differ between sampling-event datasets and occurrence datasets?

**Comment by ManonGros** [comment]
Thanks @Mesibov for the question.
We infer information at the occurrence level from the event file. That being said, if a field is filled in the occurrence file, it will have the priority over what is in the event file.

Here is an example:

event.txt

| eventID | eventDate |
| ------- | ---------- |
| event1 | 2020-01-01/2020-01-31 |
| event2 | 2020-02-01/2020-02-29 |

occurrence.txt

| occurrenceID | eventID | eventDate |
| --- | --- | --- |
| occ1 | event1 | 2020-01-03 |
| occ2 | event1 | |
| occ3 | event2 | 2020-02-04/2020-02-06 |

You should have:
occ1 -> `eventDate: 2020-01-03`
occ2 -> `eventDate: 2020-01-01/2020-01-31`
occ1 -> `eventDate: 2020-02-04/2020-02-06`

Note that we aren't able to handle eventDates range yet (but this will change: https://github.com/gbif/gbif-api/issues/4). This is just to illustrate the priorities.

Does it answer your question?

**Comment by Mesibov** [comment]
@ManonGros, Many thanks for your answer, that is just what I was asking. Would this then be a correct re-statement?

(Ignoring for now the issues with date formatting) If an event field is filled in both event.txt and occurrence.txt, GBIF will process the occurrence record by using the entry in occurrence.txt and ignoring the entry in event.txt.

The question arose because I've been seeing event.txt/occurrence.txt pairs with eventID in each one, but with event fields entries differing between event.txt and occurrence.txt for the same eventID.

GBIF processing resolves any contradictions by making the two files independent with regard to event information. Do you think that data compilers should either

- Use an event.txt file for all event-field information and include _only_ eventID in occurrence.txt, or
- Include all event-field information in occurrence.txt and not use an event.txt file?

**Comment by ManonGros** [comment]
Yes I think it is a correct re-statement.

Ideally, the data providers would model their study.
For example, if the sampling event corresponds to a range (ship trail, Pollard walks, ...)
* the information in the event file should correspond to the event (like footprintWTK or date/time range) 
* and the information in the occurrence file should correspond to the specific occurrences (for example collection of a specimen at a set of coordinate and specific time).
In this example, the information might differ but isn't contradictory (an occurrence with a date within an event's date range).

We might not be able to accommodate such complex model but at least the information would be available to users accessing the original archive.

If the information for the event and the occurrence file is the same, there is no need to repeat it.
Some event-related fields/terms aren't available for the occurrence file, for example sampleSizeValue and sampleSizeUnite so it would be worth having the event file.
With that in mind, I would suggest the first option you mentioned: use an event.txt file for all event-field information and include only eventID in occurrence.txt.

Does it make sense?

**Comment by Mesibov** [comment]
@ManonGros, thanks again, the first option is also what I think best (only eventID in occurrence.txt).

Again, this issue arose because I was finding contradictions, as in this made-up example:
event.txt has a single event with eventID A74-P02 and eventDate 2021-06-09
occurrence.txt has records with eventID A74-P02 and eventDate 2021-10-17

Since an event as specified with an eventID cannot have 2 different dates, one of those dates is wrong. But which one? GBIF chooses the date in occurrence.txt, while as a data-checker I would query the data compiler.

Yesterday I finished a data check for 29 datasets shared with GBIF in which all 16 event fields in event.txt also appear in occurrence.txt. This was the authors' preference, despite my recommendation to not include an event.txt in the DwC archive.

**Comment by ManonGros** [comment]
Thanks Bob, yes it is problematic when the information is contradictory. I hope the publishers realise that's the case now. On GBIF, we would only show the values of the occurrence file in this case.
I assume I can close the issue. Let me know if it should remain open and if you have more questions.
