### ISSUE TITLE
How to get specific taxa occurrences over world grid?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5025]
**How to get specific taxa occurrences over world grid?**

I have a specific list containing a few thousand taxa of interest, all with associated GBIF IDs (some species, some genus level), and I would like a data structure containing all of their GBIF occurrences throughout the world, including all of the GPS coordinates of those occurrences. Even better if it's over a grid of the world at some reasonably fine resolution e.g. <1000m^2, but I can create this myself given the former. How would I go about doing this? Thank you! Bianca

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6999ab15a0ed93f0a489014d94256ec5:17eefa8cd1838aa5cf3d51b102d89dc18125cf57ff58ae8f280a39735a3a8b12f06bbea738b2704fe82dcbd9057eff20d1be87a9d9d9b8580dd2b4fee028e52d8d1e46bae8ccc5e969037b1b06c67513a802022bd5c5eca01d529ee81d5c9996) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6999ab15a0ed93f0a489014d94256ec5:17eefa8cd1838aa5cf3d51b102d89dc18125cf57ff58ae8f280a39735a3a8b12f06bbea738b2704fe82dcbd9057eff20d1be87a9d9d9b8580dd2b4fee028e52d8d1e46bae8ccc5e969037b1b06c67513a802022bd5c5eca01d529ee81d5c9996)
System: Firefox 119.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/faq
Window size: width 1440 - height 815
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-28T01:39:10.302Z',to:'2023-10-28T01:45:10.302Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-28T01:39:10.302Z',to:'2023-10-28T01:45:10.302Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:
> The best right now is to download GBIF data via the [download API](https://www.gbif.org/developer/occurrence#download) and create your own grid. I can see you have already done so but just in case, here are a few resources that could be helpful:
> * [Our data use club recorded webinar on the API](https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa/data-use-club-practical-session-3-recording-and-resources)
> * [Our data use club recorded webinar on data quality issues on GBIF](https://www.gbif.org/composition/3CF30vzt0K8AjoWOnmJsDR/data-use-club-practical-session-2-recording-and-resources-2)
> * [This blogpost on downloading data based on a long list of species](https://data-blog.gbif.org/post/downloading-long-species-lists-on-gbif/)
> * [This blogpost on processing data downloaded from GBIF](https://data-blog.gbif.org/post/gbif-filtering-guide/)
