### ISSUE TITLE
solo Listado de especies

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5028]
**solo Listado de especies**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/75b776fc34fb022eadcbe827a77053ac:aae0178fbd1157c379b0708b284fb056e6e6fdfd64dbfaad8acee2741e0bfc32302599d1512cb2e40b6f053f7832afdf236785d38730b7974534d9a5c4edb549fcd51f75f4d60edf4cdf2ed5fe0d537874b6dd0ed10977510525d282b2b1f3133e65c87318332d589a42554e3e367ee696dcab87e7c9af2e05c1f3577def1ad4c60808be43986e9ae0edc6e50f49547a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/75b776fc34fb022eadcbe827a77053ac:aae0178fbd1157c379b0708b284fb056e6e6fdfd64dbfaad8acee2741e0bfc32302599d1512cb2e40b6f053f7832afdf236785d38730b7974534d9a5c4edb549fcd51f75f4d60edf4cdf2ed5fe0d537874b6dd0ed10977510525d282b2b1f3133e65c87318332d589a42554e3e367ee696dcab87e7c9af2e05c1f3577def1ad4c60808be43986e9ae0edc6e50f49547a)
System: Chrome 118.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/occurrence/download/0034707-231002084531237
Window size: width 1604 - height 924
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-01T18:20:59.906Z',to:'2023-11-01T18:26:59.906Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-01T18:20:59.906Z',to:'2023-11-01T18:26:59.906Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
That is simply because that was the format you chose. It looks like you solved it though https://www.gbif.org/occurrence/download/0034761-231002084531237

> send per email
