### ISSUE TITLE
Resource lost all records without a change at the source

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#5030]
This [resource](https://www.gbif.org/dataset/344742ba-29c4-4349-9b63-ad33f4a61067) used to have 109 records and still have them at the source [https://doi.org/10.15472/fqdqzv](https://doi.org/10.15472/fqdqzv). But now it is showing 0 records in GBIF without an apparent reason. I checked the registry and apparently there has not been a change this month, but last month it was working properly, it is puzzling.

**Comment by ktotsum** [comment]
The ingestion of the dataset stopped for some reason so we forced the ingestion. Now 109 records are shown on GBIF.
