### ISSUE TITLE
additional information on observation from iNaturalist

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5032]
**additional information on observation from iNaturalist**

Hi, I am the user for this finding. 
https://www.gbif.org/occurrence/4430577159
I have the coordinates obscured on my iNaturalist page. I am more than happy to give you coordinates of location if needed. Please let me know .

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/560bae717dbca0a92367d688a93c0c69:42adb4b58a493235d6298601cfdb9499430094d5f52c5038c025ac04c4e97001a91ce012a0bda4c7de61b4890f64d511961b0f79504bfac93b2049659c1eb3eb29eb694f067315973896ba3f0c21e2d9c6fc54262506008ae3fbf965ac245e6491ecc9081c4e2cd42035aeabc5f5a0b9) - [Send email](https://www.gbif.org/api/feedback/user/mailto/560bae717dbca0a92367d688a93c0c69:42adb4b58a493235d6298601cfdb9499430094d5f52c5038c025ac04c4e97001a91ce012a0bda4c7de61b4890f64d511961b0f79504bfac93b2049659c1eb3eb29eb694f067315973896ba3f0c21e2d9c6fc54262506008ae3fbf965ac245e6491ecc9081c4e2cd42035aeabc5f5a0b9)
System: Chrome 119.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/4430577159
Window size: width 1280 - height 714
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-07T00:16:34.214Z',to:'2023-11-07T00:22:34.214Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-07T00:16:34.214Z',to:'2023-11-07T00:22:34.214Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

Node handles: @albenson-usgs @sformel-usgs

**Comment by CecSve** [comment]
User contacted through helpdesk
