### ISSUE TITLE
Show duplicate of link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#504]
**Show duplicate of link**

This dataset is deleted because it is a duplicate of another.  When the response contains

"duplicateOfDatasetKey": "3b301884-51b9-443f-b63c-47feeccfb89f",

and the dataset is deleted I suggest changing the header to 

"This dataset was deleted 2 October 2017 and is likely replaced by [INSERT NEW DATASET TITLE(http://somelink)"

This is important, because we have DOI citations to dead pages now, and it would be nice if a user arriving there is enticed to click through to the new version

@dnoesgaard and @ahahn-gbif

-----
fbitem-dataset1eb5d9c0-2e4c-11de-909a-b8a03c50a862
User provided contact info: @timrobertson100
System: Chrome 61.0.3163 / Mac OS X 10.11.5
Referer: https://www.gbif.org/dataset/1eb5d9c0-2e4c-11de-909a-b8a03c50a862
Window size: width 1625 - height 1004
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-02T14:36:19.712Z',mode:absolute,to:'2017-10-02T14:42:19.712Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-02T14:36:19.712Z',mode:absolute,to:'2017-10-02T14:42:19.712Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
Very nice, thank you, @timrobertson100
