### ISSUE TITLE
A search for Gymnura crebipunctata produces no results.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5040]
**A search for Gymnura crebipunctata produces no results.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6087b30674258ee8703b2b31d4dda80f:e45d2db893f7b55036893cc93f1d65d033202510539134ff06e18f844b0ab27512e59044e241ba5c5c9f2364daf0d9215d535df73dced26f5271860f694cc70fc6d125774d9712230815a77df5a8bfe182e3abf325160f0f56382db79d1fda38) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6087b30674258ee8703b2b31d4dda80f:e45d2db893f7b55036893cc93f1d65d033202510539134ff06e18f844b0ab27512e59044e241ba5c5c9f2364daf0d9215d535df73dced26f5271860f694cc70fc6d125774d9712230815a77df5a8bfe182e3abf325160f0f56382db79d1fda38)
System: Chrome 119.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/search?q=gymnura%20crebipunctata
Window size: width 1340 - height 912
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-13T10:16:03.213Z',to:'2023-11-13T10:22:03.213Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-13T10:16:03.213Z',to:'2023-11-13T10:22:03.213Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
_Gymnura creb**r**ipunctata_ gives a result though: https://www.gbif.org/species/5216227

**Comment by ahahn-gbif** [comment]
could this be a case-sensitive issue in the free text search? https://www.gbif.org/search?q=Gymnura%20crebipunctata works as well.

**Comment by ManonGros** [comment]
Contacted user by email.
