### ISSUE TITLE
A search using Gymnura crebipunctata produces no results HOwever a search using only the genus name Gymnura shows that many points for that species do exists..you can see the name G crebi when you check the data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5041]
**A search using Gymnura crebipunctata produces no results HOwever a search using only the genus name Gymnura shows that many points for that species do exists..you can see the name G crebi when you check the data**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7701c286d8a8d1ac70f19deae7c5971f:cd1245158245302716176f9458e58a56c0f1a3c90f1fbc5fef34c090ea4ae045e07e5471abbf19f7b01d487f046498ca908755ecf19dacf0cec8f58fe81d2a5e110f7d51236db368c9506bc4c030e6b2a9814db576267038924b57ecd3a86d22) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7701c286d8a8d1ac70f19deae7c5971f:cd1245158245302716176f9458e58a56c0f1a3c90f1fbc5fef34c090ea4ae045e07e5471abbf19f7b01d487f046498ca908755ecf19dacf0cec8f58fe81d2a5e110f7d51236db368c9506bc4c030e6b2a9814db576267038924b57ecd3a86d22)
System: Chrome 119.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/search?q=gymnura%20crebipunctata
Window size: width 1340 - height 912
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-13T10:17:24.698Z',to:'2023-11-13T10:23:24.698Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-13T10:17:24.698Z',to:'2023-11-13T10:23:24.698Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Related to https://github.com/gbif/portal-feedback/issues/5040
