### ISSUE TITLE
Gbif is wrong on species

### ISSUE THREAD

**Issue by Olive4u** [gbif/portal-feedback#5044]
hello, It says that zodarion isn't in oregon even though it is, and i thought this pulled from iNat which has observations of species of zodariidae.

**Comment by ManonGros** [comment]
> Replied by email

iNaturalist does share observations on GBIF. Those observations need to be “research-grade” and associated with open licenses with GBIF (CC0, CC BY, CC BY-NC), https://www.inaturalist.org/pages/help#GBIFdata.
Unfortunately, the observations of Zodarion in Oregon don’t seem to be research grade ([this is the search result](https://www.inaturalist.org/observations?place_id=10&quality_grade=research&subview=map&taxon_id=60920&verifiable=any) for research-grade observations for this genus in Oregon). You can read more on how iNaturalist observations can become research grade [here](https://www.inaturalist.org/pages/help#quality).
