### ISSUE TITLE
Deleting my account

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5046]
**Deleting my account**

Hello, I would like to delete my account on GBIF as I don't use it anymore.

Thanks in advance.

Mrs OULIA H.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bcdac76b1f7927c9c105344f352ef5bf:c785d66a5ee8b04a1bdd62e1976a952a58e27f28fe89321fe425f846d54f3535178b347ad94bcafd25954e42705200b5cf74ebd84da75cdae7e034fec2a78638ee6b130c0b34cd8db1ad2092a4c807ea5a7cd45a2e0a387f71814cd1d7728993ade309b6e2dd1ecd388c188836801c555c15c348032ad45b7646c6709bf34b2708eb36a66efe44c703cc823cc1d81491) - [Send email](https://www.gbif.org/api/feedback/user/mailto/bcdac76b1f7927c9c105344f352ef5bf:c785d66a5ee8b04a1bdd62e1976a952a58e27f28fe89321fe425f846d54f3535178b347ad94bcafd25954e42705200b5cf74ebd84da75cdae7e034fec2a78638ee6b130c0b34cd8db1ad2092a4c807ea5a7cd45a2e0a387f71814cd1d7728993ade309b6e2dd1ecd388c188836801c555c15c348032ad45b7646c6709bf34b2708eb36a66efe44c703cc823cc1d81491)
System: Chrome 119.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=DELETE%20ACCOUNT
Window size: width 1369 - height 664
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-14T12:12:59.705Z',to:'2023-11-14T12:18:59.705Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-14T12:12:59.705Z',to:'2023-11-14T12:18:59.705Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
Deleted the account and contacted the user from helpdesk.
