### ISSUE TITLE
coordinate problem

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5049]
**coordinate problem**

the files I download does not have coordinate

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bff5f8438104d5f0d6d924383c142a5c:957136a8096780a4df5ab5a19114ffd0370c7744f87df4928f18f0733e1e78009d760ba9ed48434368e7aec3aed04d971aab822defe5d5c0443c4675aa8cd1e7f43c9b64daae8e8b30d510de1d5486ea95e38063511bf83e9c4b108a01608029dd35b46fe597f3eb5af9028bbee976aaa33e6758973eab66a45728d97d36f52ea948b3feee630ac6aeae545194a548ad) - [Send email](https://www.gbif.org/api/feedback/user/mailto/bff5f8438104d5f0d6d924383c142a5c:957136a8096780a4df5ab5a19114ffd0370c7744f87df4928f18f0733e1e78009d760ba9ed48434368e7aec3aed04d971aab822defe5d5c0443c4675aa8cd1e7f43c9b64daae8e8b30d510de1d5486ea95e38063511bf83e9c4b108a01608029dd35b46fe597f3eb5af9028bbee976aaa33e6758973eab66a45728d97d36f52ea948b3feee630ac6aeae545194a548ad)
System: Chrome 119.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
Window size: width 1366 - height 619
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-16T14:08:32.955Z',to:'2023-11-16T14:14:32.955Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-16T14:08:32.955Z',to:'2023-11-16T14:14:32.955Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
They also wrote to Helpdesk and Kumiko followed up.
