### ISSUE TITLE
Won't let me download.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#505]
**Won&#39;t let me download.**

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51

System: Chrome 61.0.3163 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/download?taxon_key=2685464
Window size: width 1536 - height 710
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-02T15:15:26.725Z',mode:absolute,to:'2017-10-02T15:21:26.725Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-02T15:15:26.725Z',mode:absolute,to:'2017-10-02T15:21:26.725Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Temporary server outage. But there seem to be a lot of them on the http://api.gbif.org/v1/occurrence/search/download/?format=SIMPLE_CSV/... endpoint

The site fails with a link to report an issue and explains that it cannot be downloaded at the moment. Which seems like a decent feedback, but better would be to report that there is an outage. Related https://github.com/gbif/portal16/issues/216
