### ISSUE TITLE
Pictures don't fit species on Parasmittina jeffreysi (Norman, 1876)

### ISSUE THREAD

**Issue by aaltenburger2** [gbif/portal-feedback#5051]
Hi, 

Parasmittina jeffreysi (Norman, 1876) is a bryozoan https://www.gbif.org/species/1006770. For some reason, several pictures of insects have been attached to it.
Same issue for https://www.gbif.org/species/2218427 an amphipod.
Same issue for https://www.gbif.org/species/2117782 a pycnogonid.
Same issue here https://www.gbif.org/species/8423287
Same issue https://www.gbif.org/species/2317019
https://www.gbif.org/species/4985162

Cheers,

Andreas

**Comment by ManonGros** [comment]
Thanks Andreas, it looks like all the unexpected images come from the same dataset: https://www.gbif.org/occurrence/gallery?dataset_key=7e380070-f762-11e1-a439-00145eb45e9a&media_type=StillImage&taxon_key=2218427&taxon_key=2117782&taxon_key=1006770&taxon_key=8423287&taxon_key=2317019&taxon_key=4985162. It seems like it could be some kind of issue in their system where the images don't correspond to the records. I have contacted them.

**Comment by ManonGros** [comment]
The Museum fixed the issue.
