### ISSUE TITLE
Download is only supported for structured search – not for free text queries.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5052]
**Download is only supported for structured search – not for free text queries.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1fb3e49e0b1d686fd9b9a86e2d5fb3ca:f991fe1dba299a9c3adf8a5e2637335bb86b6c2255faeced0f40bb46d628b3ad5aac9fe3c6c79a478e0ddb749b0f2e2e5e8fc9adb06d1f98fdf6f23c5ab3937467d17db1660a913922e2748003e7abe045a65da3439a5cd2ca666715646bba0d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/1fb3e49e0b1d686fd9b9a86e2d5fb3ca:f991fe1dba299a9c3adf8a5e2637335bb86b6c2255faeced0f40bb46d628b3ad5aac9fe3c6c79a478e0ddb749b0f2e2e5e8fc9adb06d1f98fdf6f23c5ab3937467d17db1660a913922e2748003e7abe045a65da3439a5cd2ca666715646bba0d)
System: Chrome 119.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/zh/occurrence/download?q=Amolops&advanced=1&occurrence_status=present
Window size: width 1872 - height 932
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-19T12:59:46.892Z',to:'2023-11-19T13:05:46.892Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-19T12:59:46.892Z',to:'2023-11-19T13:05:46.892Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email

> Our system doesn’t support free text search queries, but I can see that you generated some downloads using the scientific name field. Were you able to get the data you need?
Let us know if not, we can help you.
