### ISSUE TITLE
recordedByID order getting flipped in GBIF portal

### ISSUE THREAD

**Issue by rukayaj** [gbif/portal-feedback#5055]
![image](https://github.com/gbif/portal-feedback/assets/9654499/f61c577b-aafd-4088-9602-8d64c936775c)
The recordedByID field values seem to be getting flipped - we're publishing them in a certain order and that order is related to the order of the names of the collectors in the recordedBy field. 

Example record: https://www.gbif.org/occurrence/1262676576

**Comment by rukayaj** [comment]
Closing this as apparently order does not have meaning in the recordedByID field (see https://github.com/gbif/portal-feedback/issues/3409)

**Comment by dshorthouse** [comment]
GitHub needs another emoji for this. Something to convey recognition - I see you - when neither thumbs-up, hearts, or googly eyes are sufficient. And so, the non-committal, expressionless face is the closest thing I can offer: 😑
