### ISSUE TITLE
Link to GBIF GB documents directory

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#506]
**Link to GBIF GB documents directory**

I am aware that login is needed, but to have the link to login page at hand when in need to login and see documents would be nice.

-----
fbitem-94a6d58a8f6f4871dd15921c3a3d6d0250a8fccc
User provided contact info: icalabuig@snm.ku.dk
System: Chrome 61.0.3163 / Windows 10 0.0.0
Referer: https://www.gbif.org/what-is-gbif
Window size: width 1240 - height 1000
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-03T07:33:33.267Z',mode:absolute,to:'2017-10-03T07:39:33.267Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-03T07:33:33.267Z',mode:absolute,to:'2017-10-03T07:39:33.267Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
Asked Isabel for eloboration...

**Comment by MattBlissett** [comment]
I think she would mean a link to the Governing Board meeting documents, which are password protected and here: https://directory.gbif.org/documents/

**Comment by DanBIF** [comment]
Hi, indeed yes, a place to click and be asked for log in credentials to view GB documents on the URL Matt mentions is what I miss :-) it could be placed at  e.g. https://www.gbif.org/what-is-gbif or https://www.gbif.org/governance

**Comment by dnoesgaard** [comment]
@DanBIF - I've added a link to the documents on the Governance page under "Meetings of the Governing Board"...

**Comment by DanBIF** [comment]
Great! - Thanks a lot
