### ISSUE TITLE
raw data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5061]
**raw data**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c49ad4077541bb668eb3a33000ea88ba:c93d46db7fe6536123f14e10d708423a10b7c17dc117e90431fb4c51ef6ae8d836aa1550eb9df52767990be989c474cdc5f1ac2a83fb09ecbf1c9843ecedd71015fa4e1b676169606110c4d29e67ffdae2ad32adcca32d74f57b6797d2bb72f1) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c49ad4077541bb668eb3a33000ea88ba:c93d46db7fe6536123f14e10d708423a10b7c17dc117e90431fb4c51ef6ae8d836aa1550eb9df52767990be989c474cdc5f1ac2a83fb09ecbf1c9843ecedd71015fa4e1b676169606110c4d29e67ffdae2ad32adcca32d74f57b6797d2bb72f1)
System: Chrome 119.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/system-health
Window size: width 1388 - height 913
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-22T15:39:43.562Z',to:'2023-11-22T15:45:43.562Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-22T15:39:43.562Z',to:'2023-11-22T15:45:43.562Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
This look like a mistake. If not feel free to expand with a question

> user contacted per email
