### ISSUE TITLE
Hello! I was just curious when you think you will next index data from iNaturalist, I submitted an occurrence that is research grade that I need to incorporate into an analysis and I'm hoping it gets added soon. I added mine about two weeks ago.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5066]
**Hello! I was just curious when you think you will next index data from iNaturalist, I submitted an occurrence that is research grade that I need to incorporate into an analysis and I&#39;m hoping it gets added soon. I added mine about two weeks ago.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c5d1a856f1e52c5b3b5915e72a20820a:0e3b0ead06675f5ebde752f8fd3a95d8a05673aa76f38582cf49f46d7a8abbb0a714ebcd7e589d5e1c488542fa998b3b439f2904e5b81eca878c5c00932ec2d775e7d5e261773dfaf9fb45070044c302eb244262751aa95b3b7e8b59e6daecfe) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c5d1a856f1e52c5b3b5915e72a20820a:0e3b0ead06675f5ebde752f8fd3a95d8a05673aa76f38582cf49f46d7a8abbb0a714ebcd7e589d5e1c488542fa998b3b439f2904e5b81eca878c5c00932ec2d775e7d5e261773dfaf9fb45070044c302eb244262751aa95b3b7e8b59e6daecfe)
System: Chrome 119.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/search?taxon_key=2438517&gadm_gid=USA.16_1
Window size: width 1440 - height 813
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-27T15:40:01.101Z',to:'2023-11-27T15:46:01.101Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-27T15:40:01.101Z',to:'2023-11-27T15:46:01.101Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.

Summarized, around 2 days for iNaturalist to generate the archive, and 7-14 (generally nearer 7) days for us to pick it up.

The next check for new data is just over 7 days since the previous check shown on https://registry.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7/ingestion-history
