### ISSUE TITLE
Blattella germanica and Blatta germanica (Blattodea: Blattidae) seem to be synonyms, however both accepted species in GBIF. 

### ISSUE THREAD

**Issue by FrederikDeWint** [gbif/portal-feedback#5067]
_Blattella germanica_ Linnaeus, 1767 and _Blatta germanica_  Linnaeus, 1767 (Blattodea: Blattidae) seem to be synonyms, however both accepted species in GBIF. 
Is this correct? I think _Blatta germanica_ might not exist as valid species.

**Comment by ktotsum** [comment]
[Blatta germanica Linnaeus, 1767](https://www.gbif.org/species/7183398) seems to be a valid synonym of [Blattella germanica (Linnaeus, 1767)](https://www.gbif.org/species/159984732) according to its source.

Dyntaxa
https://www.dyntaxa.se/Taxon/Info/234519?changeRoot=True

Linnaeus. 1767. Systema naturae 1, ed. 12, Holmiae 688
https://www.biodiversitylibrary.org/item/137240#page/162/mode/1up
