### ISSUE TITLE
EML is not valid

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#507]
**EML is not valid**

The EML within the download is not valid, according to Joakim Philipson's presentation at TDWG.

-----
fbitem-38b294efce4c10b59bbc66a8576512a4d948e581

System: Firefox 55.0.0 / Mac OS X 10.12.0
Referer: https://www.gbif.org/occurrence/download/0008504-170826194755519
Window size: width 1440 - height 770
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-03T19:08:22.787Z',mode:absolute,to:'2017-10-03T19:14:22.787Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-03T19:08:22.787Z',mode:absolute,to:'2017-10-03T19:14:22.787Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Ah, Christian put it here at the same time: https://github.com/gbif/registry/issues/26
