### ISSUE TITLE
Endemic and near-endemic species of colombia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5072]
**Endemic and near-endemic species of colombia**

Plesa, can you tell me: ¿how can I download information about endemic and near-endemic species of Colombia?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/af73d35b00ccedf086ad2e498bf9dcff:dabe6c3ced078e36f38f7dc5710320053477296c045101c77ae092c3aa003cba3f55099393564d525e65e86be425ffb315a993a4ae12cf1746cd2a5568a313bc94ac6e71371422288dae9395f0e0137809b19cf5458992f20b46ffeb4023e57de7d97bf0aba3c5faf7231391cad9c10f0923239eda8d9a67a5443ce3cb64f35e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/af73d35b00ccedf086ad2e498bf9dcff:dabe6c3ced078e36f38f7dc5710320053477296c045101c77ae092c3aa003cba3f55099393564d525e65e86be425ffb315a993a4ae12cf1746cd2a5568a313bc94ac6e71371422288dae9395f0e0137809b19cf5458992f20b46ffeb4023e57de7d97bf0aba3c5faf7231391cad9c10f0923239eda8d9a67a5443ce3cb64f35e)
System: Chrome 119.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/system-health
Window size: width 1920 - height 931
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-28T19:51:43.597Z',to:'2023-11-28T19:57:43.597Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-28T19:51:43.597Z',to:'2023-11-28T19:57:43.597Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It looks like there are several checklists that refer to endemic species (https://www.gbif.org/dataset/search?q=endemic&type=CHECKLIST&publishing_country=CO) but I don't see one that would contain all the taxonomic groups. @EstebanMH-SiB and SIB Colombia would know better. Is there any list of Colombian endemic species available?

**Comment by EstebanMH-SiB** [comment]
There isn't a list with all the endemic species, we use some reference checklists that have this information in the Species Distribution extension, besides the one that you listed, we have:

- All this checklists for some families of Coleoptera: https://biodiversidad.co/dataset/search?publishingOrg=2c39be5c-c11e-46d0-bcb4-552f2072d19f&type=CHECKLIST
- Mamíferos de Colombia: https://doi.org/10.15472/kl1whs
- Lista de referencia de especies de aves de Colombia - 2022: https://doi.org/10.15472/qhsz0p
- Catálogo de Plantas y Líquenes de Colombia: https://doi.org/10.15472/7avdhn
- Lista de macroinvertebrados acuáticos continentales de Colombia: https://doi.org/10.15472/hmyvdl
- Lista de flora acuática continental de Colombia: https://doi.org/10.15472/vzde3s

For the groups that currently do not have an official checklist, we use other sources, for [Amphibia](https://amphibiaweb.org/), for [Reptilia](http://www.reptile-database.org/) and for [Lepidoptera](https://www.butterflycatalogs.com/uploads/1/0/3/2/103240120/checklist_colombia_version1_jun21_2021.pdf). 

As far as we know, there is not much information about near-endemic, most lists just use endemic or native.

Let me know if this is enough to answer this question and perhaps when you send the email with the answer you could copy us. Thanks!

**Comment by timhirsch** [comment]
Just to add to this discussion, could we suggest some semi-automated ways of generating endemic species lists (or draft/candidate lists) using existing occurrence data? So for example, an API call that says (sorry for the non-technical language!), "Show me a list of species for which GBIF has occurrences located in Colombia and in no other country"? This could also be broken down to different taxonomic groups, and compared with existing checklists where available. Of course the messaging for how such lists should be labelled and used would need to be done carefully, but it might be a useful tool for developing endemic lists.

**Comment by ManonGros** [comment]
Thanks @EstebanMH-SiB I just sent them a reply.

@timhirsch I am closing this issue as another one with a similar suggestion is open here: https://github.com/gbif/portal-feedback/issues/5012
