### ISSUE TITLE
DOI for full 1 November 2023 occurrences download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5082]
**DOI for full 1 November 2023 occurrences download**

On November 2, 2023, I executed a download of the full occurrences by opening "https://www.gbif.org/occurrence/search" and clicking "DOWNLOAD" (without adding any filters) and then selecting "DARWIN CORE ARCHIVE". This led to a page similar to the process done today (December 6, 2023): "https://doi.org/10.15468/dl.7hn2mg" but under a different DOI. It seems that this is a differently formatted version of the monthly full occurrence snapshots (https://www.gbif.org/occurrence-snapshots). However, the full Darwin Core Archive has more information that is useful to us compared to the parquet files in the occurrence snapshots page.

Since I did not save it, and it is not listed in the "DOWNLOADS" tab on my GBIF profile, I would like to recover the DOI associated with the 1 November 2023 equivalent of the 1 December 2023 "https://doi.org/10.15468/dl.7hn2mg" download. Is this possible?

-----

Github user: @thompsonmj
User: [See in registry](https://www.gbif.org/api/feedback/user/f1efdb2c6c03ee9009e6c0681bfa3d2b:1fdad013528c115be86aa8d471cd13a94a16f1ec8abec0d0c33db778c4289be79e56bdc2e5ced1028924a01259b27f74a88dfc6baec11df780364ecb438333b1bfce9ff71f4d128e1834494b88e4015bd1c48a6dab8008cf7f2f1ab480a94c854048a0135c55bfc7c075db1cf55aabb7517e384945eab5e81fc357949b8d8b1ae821796524886647717350cf0368fdec) - [Send email](https://www.gbif.org/api/feedback/user/mailto/f1efdb2c6c03ee9009e6c0681bfa3d2b:1fdad013528c115be86aa8d471cd13a94a16f1ec8abec0d0c33db778c4289be79e56bdc2e5ced1028924a01259b27f74a88dfc6baec11df780364ecb438333b1bfce9ff71f4d128e1834494b88e4015bd1c48a6dab8008cf7f2f1ab480a94c854048a0135c55bfc7c075db1cf55aabb7517e384945eab5e81fc357949b8d8b1ae821796524886647717350cf0368fdec)
System: Firefox 115.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/news/2M3n65fHOhvq4ek5oVOskc/new-processing-routine-improves-stability-of-gbif-occurrence-ids
Window size: width 1760 - height 821
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-06T15:59:59.775Z',to:'2023-12-06T16:05:59.775Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-06T15:59:59.775Z',to:'2023-12-06T16:05:59.775Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Hi @thompsonmj,

It is  https://doi.org/10.15468/dl.v4c6mc, which is listed further down the occurrence snapshots under "Monthly snapshot datasets" with no filter and Darwin Core Archive format.

**Comment by ktotsum** [comment]
Replied to the user by email

**Comment by thompsonmj** [comment]
Oh my, naturally the issue was that I didn't scroll down far enough. Thank you!
