### ISSUE TITLE
gbif sequence id not working

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5088]
**gbif sequence id not working**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/59e418212a861ab0dc3967c9160f8603:250e142907cd03f327dff2879efd2644009313c03b630d1f4e72429c53263f9cba3bb48c1cb19352b6a8dd72a7ea75234dcda465bf916752d76213e5be8e9cd975a443e66a6400363fed326cd589a654fea036012d730e631201e1dfdb67a00bda86ce5038ee672497c5b6eaa37217d6f78ce25398f3fec41292d8436e8021c3038112554c834552dc2b2cb1bc1da250) - [Send email](https://www.gbif.org/api/feedback/user/mailto/59e418212a861ab0dc3967c9160f8603:250e142907cd03f327dff2879efd2644009313c03b630d1f4e72429c53263f9cba3bb48c1cb19352b6a8dd72a7ea75234dcda465bf916752d76213e5be8e9cd975a443e66a6400363fed326cd589a654fea036012d730e631201e1dfdb67a00bda86ce5038ee672497c5b6eaa37217d6f78ce25398f3fec41292d8436e8021c3038112554c834552dc2b2cb1bc1da250)
System: Chrome 119.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1656 - height 876
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-11T18:14:59.949Z',to:'2023-12-11T18:20:59.949Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-11T18:14:59.949Z',to:'2023-12-11T18:20:59.949Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by drtplp** [comment]
Hello, I'm trying to use the sequence id blast tool but they only blast 4 sequences max and stop. Any suggestions on what would be the problem?

**Comment by thomasstjerne** [comment]
Hi @drtplp 
I have sent you an email asking for the data that can help us re-produce the problem.
