### ISSUE TITLE
Is there a field that indicates whether the (plant) species is native or introduced to the country where it has been observed?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5089]
**Is there a field that indicates whether the (plant) species is native or introduced to the country where it has been observed?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c38a1b171cb68a884239eaaa96d5380d:33905c5009583d7a612b2b0445205c2b4a9cf3a6c6c437b2dd71869737363d4371e0e2bf4c794af4aeccdbd37f70d7896c572bbc52c2c3e6a081d5a02490ef6e544a2e0a2c7add5ad148f589a8c842f66a11303413e93ed9b23d51d97be34f76) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c38a1b171cb68a884239eaaa96d5380d:33905c5009583d7a612b2b0445205c2b4a9cf3a6c6c437b2dd71869737363d4371e0e2bf4c794af4aeccdbd37f70d7896c572bbc52c2c3e6a081d5a02490ef6e544a2e0a2c7add5ad148f589a8c842f66a11303413e93ed9b23d51d97be34f76)
System: Chrome 119.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/search
Window size: width 1745 - height 835
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-11T21:56:11.901Z',to:'2023-12-11T22:02:11.901Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-11T21:56:11.901Z',to:'2023-12-11T22:02:11.901Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

The field [establishmentMeans ](https://dwc.tdwg.org/terms/#dwc:establishmentMeans)can indicate whether a species is native or introduced to the country where it has been observed. This field can be used to search occurrences on GBIF as well, for example: https://www.gbif.org/occurrence/search?establishment_means=Native&advanced=1. However, few data providers are able to share that information. This means that for more occurrences, this field is empty (and the occurrences won’t be selected when using the filter).

An alternative would be to work with the [checklists published by the Invasive Species Specialist Group](https://www.gbif.org/dataset/search?type=CHECKLIST&publishing_org=cdef28b1-db4e-4c58-aa71-3c5238c2d0b5). They have one per country and aim to list all the invasive and introduced species in the given country. See for example, [the checklist for New Zealand](https://www.gbif.org/dataset/b286f8ee-1e29-4f8a-a041-9106bb1796f3). We aggregate information provided in the checklist on our species pages. For example, if you scroll down on the page for Phoronis ijimai Oka, 1897 (https://www.gbif.org/species/5186402), you will see that it has been introduced in New Zealand.
