### ISSUE TITLE
Statement "For how long will GBIF store this data" is insufficient

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#509]
**Statement &quot;For how long will GBIF store this data&quot; is insufficient**

Joakim Philipson's TDWG presentation said it was unclear what metadata would remain in the case that a download is deleted.  I think he particularly wanted to know about the EML.

It could also be clearer that very few downloads will ever be removed, and even then only the very largest.

-----
fbitem-38b294efce4c10b59bbc66a8576512a4d948e581
User provided contact info: MattBlissett
System: Firefox 55.0.0 / Mac OS X 10.12.0
Referer: https://www.gbif.org/occurrence/download/0008504-170826194755519
Window size: width 1440 - height 770
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-03T19:15:25.938Z',mode:absolute,to:'2017-10-03T19:21:25.938Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-03T19:15:25.938Z',mode:absolute,to:'2017-10-03T19:21:25.938Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
This seems like something that could go into the FAQ - when there we can create a link (or popup) to use the FAQ entry.

**Comment by dnoesgaard** [comment]
I agree. @MattBlissett, can you provide more info on the criteria for deletion, and I'll add it to the [FAQ entry](https://app.contentful.com/spaces/uo17ejk9rkwj/entries/180mySqImUoKK02kIGiSiE), so that it can be used as a pop-up on the download page.

**Comment by MattBlissett** [comment]
I updated the FAQ for the upcoming change to download retention (it might not have synced just yet). Feel free to tweak.
