### ISSUE TITLE
Under the 'Get data' --> 'Occurence' i have found a map where i could zoom in to a specific area to watch registrations of species. But it was not possible to click on the dots to see information about species, date or other data? How can I find this information about what the registrations contain based on the map function?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5090]
**Under the &#39;Get data&#39; --&gt; &#39;Occurence&#39; i have found a map where i could zoom in to a specific area to watch registrations of species. But it was not possible to click on the dots to see information about species, date or other data? How can I find this information about what the registrations contain based on the map function?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8d329b8d38ed51c947e997ace79167f0:917e5d8685e2e19420119cfebd643d90e40555c50c99f9b28d8c14f54239a9e0fedf23ffa4e33b751c8faf870ecf68226109b77b5f61a21d47a50b325eaed4a308653afc5650f035aa509d0c748215e4d4987d37fd96c70380679e02585fd8e99e957df59f4b74714c76610277a26394) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8d329b8d38ed51c947e997ace79167f0:917e5d8685e2e19420119cfebd643d90e40555c50c99f9b28d8c14f54239a9e0fedf23ffa4e33b751c8faf870ecf68226109b77b5f61a21d47a50b325eaed4a308653afc5650f035aa509d0c748215e4d4987d37fd96c70380679e02585fd8e99e957df59f4b74714c76610277a26394)
System: Chrome 119.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence-snapshots
Window size: width 1272 - height 652
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-12T12:49:07.936Z',to:'2023-12-12T12:55:07.936Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-12T12:49:07.936Z',to:'2023-12-12T12:55:07.936Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
You should use the "search area" tool:
![occ_map1](https://github.com/gbif/portal-feedback/assets/1666484/7d224a5b-b639-4bac-902e-89763b56ce83)

You can draw a rectangle, and then information about the data in that area is displayed at the right:
![occ_map2](https://github.com/gbif/portal-feedback/assets/1666484/2068aaaa-60b9-4ed6-895d-d57aeef52bf7)

**Comment by thomasstjerne** [comment]
User contacted by email

**Comment by CecSve** [comment]
Thank you @thomasstjerne - I will close the issue.
