### ISSUE TITLE
Record incorrectly labeled as continent coordinate mismatch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5093]
**Record incorrectly labeled as continent coordinate mismatch**

This dataset have 1.227 records with this flag, but the whole dataset is in Colombia and have continent as "América del Sur", so I have no idea why these records in specific are labeled.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/50e35f1838617460a20121401d379fb5:3c9e8027f6ced99b1b2162c85fdf130b7a4b774a4a2b8efcf5a871184871372c1c1bb246f13c014495a850ba6970a3bf93ad9343159cd1bb51f67a2d9b7113944ecf268725e7df19ada6e13350a811d586b99472a917923c11f27d7cb1022b1b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/50e35f1838617460a20121401d379fb5:3c9e8027f6ced99b1b2162c85fdf130b7a4b774a4a2b8efcf5a871184871372c1c1bb246f13c014495a850ba6970a3bf93ad9343159cd1bb51f67a2d9b7113944ecf268725e7df19ada6e13350a811d586b99472a917923c11f27d7cb1022b1b)
System: Chrome 120.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/4456929379
Window size: width 1222 - height 653
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-12T20:36:53.244Z',to:'2023-12-12T20:42:53.244Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-12T20:36:53.244Z',to:'2023-12-12T20:42:53.244Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 010fcd64-caa7-47dd-b1b1-c8be5a2144b6
publishingOrgKey: f072f648-b8a4-47a0-9e1c-89d790645b5a

**Comment by MattBlissett** [comment]
They are in the sea (http://marineregions.org/mrgid/4287) which is not part of the continent.  There's a slight tolerance in the matching, and other occurrences in the sea but near enough to the cost don't get flagged.

https://www.gbif.org/occurrence/map?dataset_key=010fcd64-caa7-47dd-b1b1-c8be5a2144b6&issue=CONTINENT_COORDINATE_MISMATCH
