### ISSUE TITLE
species query

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5094]
**species query**

i want to have a list of species present within 15km of lincolnshire limewoods?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b5e8c924295ed55568772a360bc386b8:596b294fbce1a261376de13e4445bb631da45e261f90279024064926ed81c3b6e2d73153d64dfe44b778faececc78d8b914ca393bd57be4c5a43aa9e7f860abb280a6f7a7354acbfd189fc4d8eed2e1cd41485029902ab9c882735bd2d1befcc) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b5e8c924295ed55568772a360bc386b8:596b294fbce1a261376de13e4445bb631da45e261f90279024064926ed81c3b6e2d73153d64dfe44b778faececc78d8b914ca393bd57be4c5a43aa9e7f860abb280a6f7a7354acbfd189fc4d8eed2e1cd41485029902ab9c882735bd2d1befcc)
System: Chrome Mobile iOS 113.0.5672 / iOS 16.3.0
Referer: https://www.gbif.org/user/confirm
Window size: width 430 - height 745
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-13T08:10:55.839Z',to:'2023-12-13T08:16:55.839Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-13T08:10:55.839Z',to:'2023-12-13T08:16:55.839Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
John already replied by email:

Here is the download for 2km from the horncastle community woodlands. 
> https://www.gbif.org/occurrence/download/0027821-231120084113126

https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON((-0.09114%2053.19453,-0.09581%2053.20739,-0.10766%2053.21423,-0.12114%2053.21185,-0.12993%2053.20137,-0.12993%2053.18769,-0.12114%2053.17721,-0.10766%2053.17484,-0.09581%2053.18168,-0.09114%2053.19453,-0.09114%2053.19453))&occurrence_status=present
