### ISSUE TITLE
I would like to submit a (occurence) dataset as part of a study we did. "We" are a consultancy company (based in Germany) but the data collected forms part of a scientific study we will submit to a peer reviewed journal. Are we able to upload our data via a GBIF node?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5096]
**I would like to submit a (occurence) dataset as part of a study we did. &quot;We&quot; are a consultancy company (based in Germany) but the data collected forms part of a scientific study we will submit to a peer reviewed journal. Are we able to upload our data via a GBIF node?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c091205a3d4e0408c884c9c58e5cf26b:a6185bce24a6054be9af5c25d52d6763bc28997a96309defc1be793784663e859a6379385caa1f4fee0a32dce8f54ec1c64b8bf9539b4a4a745aeb20fc2a00a30160f2e5a9f6095539927108e7bfe3952c09ff1d09a50ce89efbb15c7f88b863) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c091205a3d4e0408c884c9c58e5cf26b:a6185bce24a6054be9af5c25d52d6763bc28997a96309defc1be793784663e859a6379385caa1f4fee0a32dce8f54ec1c64b8bf9539b4a4a745aeb20fc2a00a30160f2e5a9f6095539927108e7bfe3952c09ff1d09a50ce89efbb15c7f88b863)
System: Chrome 120.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=upload%20data
Window size: width 1872 - height 1052
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-14T10:33:28.909Z',to:'2023-12-14T10:39:28.909Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-14T10:33:28.909Z',to:'2023-12-14T10:39:28.909Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email pointing to the general workflow.
