### ISSUE TITLE
DMNS:Arac -> Ecdysis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5098]
**DMNS:Arac -&gt; Ecdysis**

We need to change our data source from SCAN to Ecdysis. How do we make that happen? Please let me know what info you need.
Andy

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/24b0571b741c9dad6c5c130af25efbbf:c964fedfd548f6a8ad4c58cd71a90ff96dd6b2627020b48f6e1b0f7524bf19633e920c4543362c307a7640becc48d95bb868aaddc989603c3c22be94f037839d586c907ab48251ecf4bfcaa3a0f1a64bd845b5636c766645f437ef5b7b928f0d91ceb6a7f20a866464c45703ff41e02f8fdc5922e197cf866b32924bedcc19740c52e821f6aca8cfbe1f3c5f6f903af5) - [Send email](https://www.gbif.org/api/feedback/user/mailto/24b0571b741c9dad6c5c130af25efbbf:c964fedfd548f6a8ad4c58cd71a90ff96dd6b2627020b48f6e1b0f7524bf19633e920c4543362c307a7640becc48d95bb868aaddc989603c3c22be94f037839d586c907ab48251ecf4bfcaa3a0f1a64bd845b5636c766645f437ef5b7b928f0d91ceb6a7f20a866464c45703ff41e02f8fdc5922e197cf866b32924bedcc19740c52e821f6aca8cfbe1f3c5f6f903af5)
System: Chrome 120.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/d762b508-7a70-441b-94ad-48fd77593275
Window size: width 2560 - height 1271
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-14T23:46:22.622Z',to:'2023-12-14T23:52:22.622Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-14T23:46:22.622Z',to:'2023-12-14T23:52:22.622Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email.
We can update the endpoint for them but the best is to check directly with the Symbiotia helpdesk.
