### ISSUE TITLE
Data use citations: aggregate literature citation reporting up to (publishing) country level

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#510]
**Data use citations: aggregate literature citation reporting up to (publishing) country level**

(following a question from the Node)

For reporting purposes on the Node level, it would be helpful to have access to the full list of all citations of data use / published literature that concern datasets mobilized through the Node. In a case like Spain, retrieving this information otherwise requires collecting the information for currently 96 publisher pages.

-----
fbitem-5ba0a373c5abbc6e749e2ab842a32570dec372c8
User provided contact info: ahahn-gbif
System: Firefox 56.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/country/ES/publishing
Window size: width 1226 - height 633
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-04T08:25:20.040Z',mode:absolute,to:'2017-10-04T08:31:20.040Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-04T08:25:20.040Z',mode:absolute,to:'2017-10-04T08:31:20.040Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
Already there (https://www.gbif.org/country/ES/research) - closing

**Comment by ahahn-gbif** [comment]
Correction: for the "about" publications at https://www.gbif.org/country/ES/research, the study subject has to do with Spain somehow, or data used include data about Spain (country of coverage is Spain), while in the "from" publications, one or more of the authors are located in Spain (country of researcher is Spain).
