### ISSUE TITLE
I have become the new curator of UWPG. How can I update the contact information for data associated with our herbarium?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5101]
**I have become the new curator of UWPG. How can I update the contact information for data associated with our herbarium?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2110ac393ceaf39357fc698c5b520d3d:de9e54226f2585bc87e194cbcf4587d223d31c48c4a851f55b6a4ff4261e70f079479fd8b0c1a417fb863b66dd6d2dc1cc44b7e4737a4ff1c714b04a66dc0a4f2d99d7676262d05bade0a323af77be7409b72a23c80852eef19e81094a8af3c0cdbba7d07194c689ebbeafac2af220d5) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2110ac393ceaf39357fc698c5b520d3d:de9e54226f2585bc87e194cbcf4587d223d31c48c4a851f55b6a4ff4261e70f079479fd8b0c1a417fb863b66dd6d2dc1cc44b7e4737a4ff1c714b04a66dc0a4f2d99d7676262d05bade0a323af77be7409b72a23c80852eef19e81094a8af3c0cdbba7d07194c689ebbeafac2af220d5)
System: Chrome 120.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/publisher/0bcc0651-08b6-4562-85e1-985aae8a07a1
Window size: width 1984 - height 1020
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-15T18:41:56.000Z',to:'2023-12-15T18:47:56.000Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-15T18:41:56.000Z',to:'2023-12-15T18:47:56.000Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
replied on helpdesk: please send the changes you would like to see to heldpesk@gbif.org
