### ISSUE TITLE
Hyllus semicupruces

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5106]
**Hyllus semicupruces**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7816335b5df94ffa5c73458d8334f24e:0b9fe7b0649ce2fc2e4e8a274c5496e11b7d44e2a71b27e74cbc7dd5f692b3f71db9700da2e0548476f9fb08c9e031af4953dc6e1741273db03ea60ecc843381227672a7e3eba10ea0ce6a91169b0107418b39a7bf05884b94f02653d88ecf8e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7816335b5df94ffa5c73458d8334f24e:0b9fe7b0649ce2fc2e4e8a274c5496e11b7d44e2a71b27e74cbc7dd5f692b3f71db9700da2e0548476f9fb08c9e031af4953dc6e1741273db03ea60ecc843381227672a7e3eba10ea0ce6a91169b0107418b39a7bf05884b94f02653d88ecf8e)
System: Chrome Mobile 114.0.0 / Android 0.0.0
Referer: https://www.gbif.org/dataset/b09c3987-af9a-4658-9bfd-19cf712ac3d1
Window size: width 393 - height 747
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-21T16:26:24.759Z',to:'2023-12-21T16:32:24.759Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-21T16:26:24.759Z',to:'2023-12-21T16:32:24.759Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
I will close this issue since there is insufficient information for helpdesk to investigate further
