### ISSUE TITLE
How do I export the latitude and longitude of all occurrence data for multiple species in my list? 

### ISSUE THREAD

**Issue by Hamorry** [gbif/portal-feedback#5109]

**Comment by ManonGros** [comment]
hi @Hamorry did you find a solution to your question?

I suggest checking our [Data Use Club](https://www.gbif.org/data-use-club) recorded webinars. [This one ](https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa/data-use-club-practical-session-3-recording-and-resources)is about the GBIF API. I hope it helps!
