### ISSUE TITLE
Please liaise with Plazi and get licenses applied

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#511]
**Please liaise with Plazi and get licenses applied**

https://www.gbif.org/dataset/95f5b38b-d9e1-4e74-8452-22b330d684ba as an example needs to have a compatible license

-----
fbitem-dataset95f5b38b-d9e1-4e74-8452-22b330d684ba
User provided contact info: timrobertson100
System: Chrome 61.0.3163 / Mac OS X 10.11.5
Referer: https://www.gbif.org/dataset/95f5b38b-d9e1-4e74-8452-22b330d684ba
Window size: width 1625 - height 960
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-04T12:22:26.742Z',mode:absolute,to:'2017-10-04T12:28:26.742Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-04T12:22:26.742Z',mode:absolute,to:'2017-10-04T12:28:26.742Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
[https://github.com/gbif/portal-feedback/issues/8](url)

**Comment by ahahn-gbif** [comment]
#8

**Comment by ahahn-gbif** [comment]
All Plazi checklist datasets with occurrence records should now have CC-BY assigned. NB: this does not apply for datasets that are deleted, yet still have indexed occurrences - requires clean-up. Re-indexing triggered but still running.

**Comment by mdoering** [comment]
we not all Plazi datasets?

**Comment by ahahn-gbif** [comment]
Licensing consultation never included checklists. I don't think Plazi have an issue with applying the same license to all, but I need to check back

**Comment by ahahn-gbif** [comment]
Got confirmation that CC0 is ok for all Plazi datasets

**Comment by MattBlissett** [comment]
Probably all Plazi datasets have this in the EML:

```xml
<intellectualRights>
  <para>Public Domain</para>
  <para>No known copyright restrictions apply. See Agosti, D., Egloff, W., 2009. Taxonomic information exchange and copyright: the Plazi approach. BMC Research Notes 2009, 2:53 for further explanation.</para>
</intellectualRights>
```

This isn't a machine readable license, and isn't one we recognize. To publish as CC0, we need something like:

```xml
<intellectualRights>
  <para>
    To the extent possible under law, the publisher has waived all rights to these data and has dedicated them to the
    <ulink url="http://creativecommons.org/publicdomain/zero/1.0/legalcode">
      <citetitle>Public Domain (CC0 1.0)</citetitle>
    </ulink>.
    Users may copy, modify, distribute and use the work, including for commercial purposes, without restriction.
  </para>
</intellectualRights>
```

The `url` in the `ulink` element is the important part, the descriptive text isn't used.

Without this, and without a change to behaviour in https://github.com/gbif/registry/issues/71, new Plazi datasets will continue to be marked CC-BY 4.0.

At the moment, we have:

```
 count │  license
───────┼───────────
   960 │ CC0_1_0
 22726 │ CC_BY_4_0
```

(Please don't do a mass-update of 22,726 dataset licenses without checking with me about any automatic reprocessing that will result!)

**Comment by ahahn-gbif** [comment]
Required steps (from @MattBlissett):
- Once/if they are going to make the change, add Plazi to the no-scheduled-crawls list
- Check the EML is changed correctly, then update the registry database directly. The metadata updates can then happen without triggering sync jobs.
- Reinterpret all Plazi occurrences so they pick up the change
- Remove the block on scheduled crawling.

**Comment by ahahn-gbif** [comment]
Email trail summary: 
- Plazi would prefer CC-BY, given that the data are based on treatments/publications (provenance information)
- EML update is feasible, incl. re-packaging of the DwC-Archives
- keep holding automatic updates for the time being, until confirmed

**Comment by ahahn-gbif** [comment]
Plazi reports all datasets re-exported with the new license statement (29/11/18)

**Comment by MattBlissett** [comment]
We do still have some CC0 Plazi datasets, where the archive hasn't been updated.

They're listed here: https://www.gbif.org/dataset/search?publishing_org=7ce8aef0-9e92-11dc-8738-b8a03c50a862&license=CC0_1_0

**Comment by ahahn-gbif** [comment]
(contacted by email, 10.12.18 - see helpdesk@)

**Comment by ahahn-gbif** [comment]
Some misunderstanding, apparently. The publisher confirms that all datasets should be published under CC0 (email helpdesk@, 10.12.18). Waiting for the metadata update on their side before resynchronizing.

**Comment by ahahn-gbif** [comment]
A test update (https://www.gbif.org/dataset/3920856d-4923-4276-ae0b-e8b3478df276) now has the following license at source: 

```xml
<intellectualRights>
  <para>To the extent possible under law, the publisher has waived all copyright and related or neighboring rights to these data, and has released them under 
    <ulink url="https://creativecommons.org/publicdomain/zero/1.0/">
      <citetitle>CC0 Public Domain Dedication</citetitle>
    </ulink>.
        Users may copy, modify, distribute and use the work, including for commercial purposes.
  </para>
  <para>No known copyright restrictions apply. See Agosti, D., Egloff, W., 2009. Taxonomic information exchange and copyright: the Plazi approach. BMC Research Notes 2009, 2:53
    <ulink url="https://doi.org/10.1186/1756-0500-2-53">
      <citetitle>https://doi.org/10.1186/1756-0500-2-53</citetitle>
    </ulink>for further explanation.
  </para>
</intellectualRights>
```

The metadata update date gives today's date, but the license showing at the dataset page is still the old one (CC BY). @MattBlissett, would you have time to help debugging, please?

**Comment by MattBlissett** [comment]
There is a bug in the registry with handling multiple licenses.  I've fixed it, but I'm looking at some other metadata-related changes before making the deployment.

**Comment by MattBlissett** [comment]
I've made the other changes and the deployment. Plazi can now update all their datasets.

**Comment by ahahn-gbif** [comment]
Publisher notified. Test dataset see https://www.gbif.org/dataset/66292f10-d487-47a0-b8a0-ed5eab57f723

**Comment by ahahn-gbif** [comment]
Plazi reports that re-export of all 22k+ DwC-A is running (17.12. 17:00). Assuming that the API notifications do not trigger an update with the mass-update-hold in place, running a metadata update on all of them in a couple of days should hopefully pick up all datasets under https://www.gbif.org/dataset/search?q=plazi&publishing_org=7ce8aef0-9e92-11dc-8738-b8a03c50a862 as CC0.

**Comment by ahahn-gbif** [comment]
Mostly done - only 7 datasets still remaining under CC BY: https://www.gbif.org/dataset/search?q=plazi&publishing_org=7ce8aef0-9e92-11dc-8738-b8a03c50a862&license=CC_BY_4_0

**Comment by MattBlissett** [comment]
These need individual investigation.

I reprocessed the metadata for them, and two updated to CC0.

The remaining five are either not updated at source, or have DWCA validation issues.

**Comment by MattBlissett** [comment]
No datasets remain, so I think this is finished.

But @gsautter, could you check what license you send in the initial registration of a new dataset with GBIF?

We have some fairly intensive processing if a dataset's license changes, and unfortunately that still happens even if the dataset is new.  It's therefore best for us if the license is included in the initial registration, and is the same as the license in the EML.

**Comment by gsautter** [comment]
We put CC0 in the `eml.xml`, and that's the only place we put a license at all.

Are you saying I should (redundantly) include the license in the JSON I send to your API?

**Comment by MattBlissett** [comment]
It would be very helpful, as I can't make a clean change to avoid the unnecessary processing until some other publishers have fixed their licenses — some background on https://github.com/gbif/registry/issues/71#issuecomment-438280021

You would just add
```json
"license": "http://creativecommons.org/publicdomain/zero/1.0/legalcode"
```
to the initial POST request.

**Comment by gsautter** [comment]
Right alongside the `installationKey`, `publishingOrganizationKey`, etc.?

**Comment by MattBlissett** [comment]
Exactly.

**Comment by gsautter** [comment]
Added, should come in with all new datasets from now on.

**Comment by MattBlissett** [comment]
Thanks, that looks fine now.
