### ISSUE TITLE
Download NOT CSV

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5110]
**Download NOT CSV**

You do not provide a correctly formatted CSV file. All text fields should be in double quotes. You therefore supply text fields with commas.
This means that all exports are likely to be useless. I see no point in using your data if I have to spend so much time trying to fix that which you deliberately corrupt. 
Pointless. So glad we do not supply data to you. We like people more I guess.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/286e6b23922ceef7ec56e03fd1cb2ca0:cfd5624401472f4d5c622bfb0e50ef246e6f5df9687832caa5d11a9434a0c60a1e6293e575d1b77dfbaea762e2e5f48b516bcac8766d358f59aff4ca55d8a0ad6b4585d1bc73ea317b6131b0b3a05939ccf097edefd228cf0bee0f2ffdc6103a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/286e6b23922ceef7ec56e03fd1cb2ca0:cfd5624401472f4d5c622bfb0e50ef246e6f5df9687832caa5d11a9434a0c60a1e6293e575d1b77dfbaea762e2e5f48b516bcac8766d358f59aff4ca55d8a0ad6b4585d1bc73ea317b6131b0b3a05939ccf097edefd228cf0bee0f2ffdc6103a)
System: Opera 105.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1866 - height 922
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-24T11:48:13.727Z',to:'2023-12-24T11:54:13.727Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-24T11:48:13.727Z',to:'2023-12-24T11:54:13.727Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email

GBIF downloads are in tab-separated format, to avoid common issues with comma-separated data sharing.

In case you are using Excel, we have advice on opening the files here: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
________________________________
From: gbif-portal ***@***.***>
Sent: Sunday, December 24, 2023 11:53:24 AM
To: gbif/portal-feedback ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gbif/portal-feedback] Download NOT CSV (Issue #5110)


Download NOT CSV

You do not provide a correctly formatted CSV file. All text fields should be in double quotes. You therefore supply text fields with commas.
This means that all exports are likely to be useless. I see no point in using your data if I have to spend so much time trying to fix that which you deliberately corrupt.
Pointless. So glad we do not supply data to you. We like people more I guess.

________________________________

User: See in registry<https://www.gbif.org/api/feedback/user/286e6b23922ceef7ec56e03fd1cb2ca0:cfd5624401472f4d5c622bfb0e50ef246e6f5df9687832caa5d11a9434a0c60a1e6293e575d1b77dfbaea762e2e5f48b516bcac8766d358f59aff4ca55d8a0ad6b4585d1bc73ea317b6131b0b3a05939ccf097edefd228cf0bee0f2ffdc6103a> - Send email<https://www.gbif.org/api/feedback/user/mailto/286e6b23922ceef7ec56e03fd1cb2ca0:cfd5624401472f4d5c622bfb0e50ef246e6f5df9687832caa5d11a9434a0c60a1e6293e575d1b77dfbaea762e2e5f48b516bcac8766d358f59aff4ca55d8a0ad6b4585d1bc73ea317b6131b0b3a05939ccf097edefd228cf0bee0f2ffdc6103a>
System: Opera 105.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1866 - height 922
API log<https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-24T11:48:13.727Z',to:'2023-12-24T11:54:13.727Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!())>
Site log<https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-24T11:48:13.727Z',to:'2023-12-24T11:54:13.727Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!())>
System health at time of feedback: OPERATIONAL
