### ISSUE TITLE
Citing past GBIF support

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5111]
**Citing past GBIF support**

I need to acknowledge GBIF's support, via a BID(?) grant to Quaid-i-Azam university for supporting digitization in Pakistan. I do not have a record of the citation because the money went to Mushtaq Ahmed at QAU, not me. Please would someone send me information on how to cite the support? I have been collaborating on a paper about data in another Pakistani herbarium, Hazara University, which was started after the herbarium manager attended the workshop at Islamabad - I think. It might have been another workshop. I do not know for sure; I have asked.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ee13359b4d3a9d3be750dbd196510b80:0bc023432df5351a71e4fe50397ae80ff8c76500eeb3a39420d8f9313393f87da36659a615e839603965589043451b90c6d723d7c22fa2417619a524eaa3c2d52277e849f7bdb9835b37d5eb6c44263cb6d9b3948dcac3e91bd67c25391f110b7aef59bb29d789558561b0a739ea226c72078c17d5d55c304e7d0d70008b8fc300170269aa8f894183965720d810615f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ee13359b4d3a9d3be750dbd196510b80:0bc023432df5351a71e4fe50397ae80ff8c76500eeb3a39420d8f9313393f87da36659a615e839603965589043451b90c6d723d7c22fa2417619a524eaa3c2d52277e849f7bdb9835b37d5eb6c44263cb6d9b3948dcac3e91bd67c25391f110b7aef59bb29d789558561b0a739ea226c72078c17d5d55c304e7d0d70008b8fc300170269aa8f894183965720d810615f)
System: Chrome 120.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/news/2b6mW6uaebea3cZUfXIxog/gbif-is-recruiting-a-software-developer
Window size: width 1280 - height 613
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-25T14:05:58.106Z',to:'2023-12-25T14:11:58.106Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-25T14:05:58.106Z',to:'2023-12-25T14:11:58.106Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Replied by email.
