### ISSUE TITLE
Fazer registro

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5115]
**Fazer registro**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/04565d81f5170fb4027c369fa6884874:491e11f2e53f3060cb752646452f14c38b5f077167b09c4c3293f4680638b8884ce62cfca761cd9abaa3057d20bbf99dca26de12fe0616726daf4e50d84d9b480cf133e4565923ef87e71712862dd942aa739703040166f5e5215e31ff357e2112c2f07369f58e8bce1b209547e112086edc29ab8a5970ec278cf499a7cb32a38d604ca6f25f1be02dc9ab46106446b4) - [Send email](https://www.gbif.org/api/feedback/user/mailto/04565d81f5170fb4027c369fa6884874:491e11f2e53f3060cb752646452f14c38b5f077167b09c4c3293f4680638b8884ce62cfca761cd9abaa3057d20bbf99dca26de12fe0616726daf4e50d84d9b480cf133e4565923ef87e71712862dd942aa739703040166f5e5215e31ff357e2112c2f07369f58e8bce1b209547e112086edc29ab8a5970ec278cf499a7cb32a38d604ca6f25f1be02dc9ab46106446b4)
System: Chrome Mobile 120.0.0 / Android 0.0.0
Referer: https://www.gbif.org/the-gbif-network
Window size: width 360 - height 649
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-01T17:10:49.251Z',to:'2024-01-01T17:16:49.251Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-01T17:10:49.251Z',to:'2024-01-01T17:16:49.251Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
Please contact helpdesk@gbif.org and elaborate if you require further assistance.
