### ISSUE TITLE
Issues ingesting opdates with georeferencing

### ISSUE THREAD

**Issue by ibdj** [gbif/portal-feedback#5117]
I have made an update to this data set https://danbif.au.dk/ipt/manage/resource?r=vascular_plants_of_south_east_greenland_1933
to include coordinates. 

I have published the dataset again, but despite that the mapping seem to be finde for the coordinates, the coordinetes arent ingested: https://www.gbif.org/dataset/41ff9b4b-190f-4dee-bf88-185d425ac0f5

Can anyone help to identify the issue and what I should de differently?
Thank you in advance.

**Comment by MattBlissett** [comment]
Hi,

There is a possible problem with the identifiers used in the dataset, see https://github.com/gbif/ingestion-management/issues/984

**Comment by jhnwllr** [comment]
We can close this now since the user is aware of the issue now on the ingestion management repo.
