### ISSUE TITLE
Location is incorrect.  I have checked the appropriate box on iNat to remove the "Research Grade" designation but I don't know if this will be reflected by GBIF (presumably resulting in the record being removed from your database).

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5121]
**Location is incorrect. I have checked the appropriate box on iNat to remove the &quot;Research Grade&quot; designation but I don&#39;t know if this will be reflected by GBIF (presumably resulting in the record being removed from your database).**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/ed61fe073c66bddf07cb5ffea60a7113:b42a797ad45d3d592a4e6ab2abcc9a2626ead468ac50cf132f59df455ff8572ae302a10d69bac4a60c652254ffcad473e1ca5394abd2ea483dcdb816c316890b973e0d3d33b79bdcc8530b1b3af4cd0c73d720e6b522f73de31d6fbc528f3891) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ed61fe073c66bddf07cb5ffea60a7113:b42a797ad45d3d592a4e6ab2abcc9a2626ead468ac50cf132f59df455ff8572ae302a10d69bac4a60c652254ffcad473e1ca5394abd2ea483dcdb816c316890b973e0d3d33b79bdcc8530b1b3af4cd0c73d720e6b522f73de31d6fbc528f3891)
System: Firefox 118.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/occurrence/3759209372
Window size: width 1658 - height 912
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-05T17:27:53.661Z',to:'2024-01-05T17:33:53.661Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-05T17:27:53.661Z',to:'2024-01-05T17:33:53.661Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

Node handles: @sformel-usgs

**Comment by sformel-usgs** [comment]
Looks like this occurrence has been removed and the issue can be closed @ManonGros @CecSve
