### ISSUE TITLE
January 2020 snapshot

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5122]
**January 2020 snapshot**

Hello, I need access to a January 2020 snapshot of GBIF occurrence data so I can perform a query. It says online that this snapshot is not available unless I get in touch with the Helpdesk. Any help you can give would be great. 

Best, 
Allison

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/94a16aaaf26a899b914973639c83cf48:4d7068f4f467e0cac4d38606321177cf6e478e596d3078bbdee19006f6e3db8965518c155efdea60bfb27f9fcc89dead728c14dd18850f08e77ed7c9dd3eebf55be2170e2ace65a8f9fe50912509ad410adc6306c4c2b33a91cc24c47f96311150d62ac9470eaaa646452d94bd671f53) - [Send email](https://www.gbif.org/api/feedback/user/mailto/94a16aaaf26a899b914973639c83cf48:4d7068f4f467e0cac4d38606321177cf6e478e596d3078bbdee19006f6e3db8965518c155efdea60bfb27f9fcc89dead728c14dd18850f08e77ed7c9dd3eebf55be2170e2ace65a8f9fe50912509ad410adc6306c4c2b33a91cc24c47f96311150d62ac9470eaaa646452d94bd671f53)
System: Safari 16.5.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/0002744-200127171203522
Window size: width 1587 - height 868
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-05T17:44:45.113Z',to:'2024-01-05T17:50:45.113Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-05T17:44:45.113Z',to:'2024-01-05T17:50:45.113Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
User has been contacted through help desk with a solution
