### ISSUE TITLE
How to I download a list of all invasive species recorded to occur in Australia?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5127]
**How to I download a list of all invasive species recorded to occur in Australia?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/28a301362081410d47eeb79f9533608f:26eb338f012ef95d0a33ba7b75da4c749f42c8f7db82aa60318f6660a072b84c1f624d1b914cdd0b227a0474eb467dc2895367ab9310615c54e8803425ced4a281ad781c31e4ecfe78b0f7b52b46aea8c3e15fa8863a4401ecb56ff49c62a917ca708d61b5cda01ce9aedea4528f54c62cc0c7377834ad3f4842175573ffe1ea) - [Send email](https://www.gbif.org/api/feedback/user/mailto/28a301362081410d47eeb79f9533608f:26eb338f012ef95d0a33ba7b75da4c749f42c8f7db82aa60318f6660a072b84c1f624d1b914cdd0b227a0474eb467dc2895367ab9310615c54e8803425ced4a281ad781c31e4ecfe78b0f7b52b46aea8c3e15fa8863a4401ecb56ff49c62a917ca708d61b5cda01ce9aedea4528f54c62cc0c7377834ad3f4842175573ffe1ea)
System: Chrome 120.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/search?dataset_key=15147db1-27c3-49b5-9c69-c78d55a4b8ff&origin=SOURCE&advanced=1
Window size: width 988 - height 620
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-10T01:42:32.904Z',to:'2024-01-10T01:48:32.904Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-10T01:42:32.904Z',to:'2024-01-10T01:48:32.904Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

If the goal is to download the names [here](https://www.gbif.org/species/search?dataset_key=15147db1-27c3-49b5-9c69-c78d55a4b8ff&origin=SOURCE&advanced=1), the simplest options are:
* Download the data at the source: https://cloud.gbif.org/griis/archive.do?r=griis-australia
* Download the data via checklistbank: https://www.checklistbank.org/dataset/24512/download. You can do so by using your GBIF credentials, one advantage of using checklistbank is that you can choose the download format as well as select a subset of taxon if needed.

If you would like to also download occurrences for those taxa. I suggest downloading the list above and generating a download via our API. Here are some resources that would be helpful:
* Our [recoded Data Use Club webinar on the GBIF API](https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa/data-use-club-practical-session-3-recording-and-resources).
* [A blogpost](https://data-blog.gbif.org/post/downloading-long-species-lists-on-gbif/) explaining how to download occurrences from a long list of species.
