### ISSUE TITLE
Hello, I would like to download the real coordinate data for rare species, not the obfuscated coordinates. I am analyzing altitudinal ranges for a conservation project among 904 species and the coordinate randomization is compromising the whole analysis. Is there a way to get a download of the true coordinates? Thanks for your consideration. The download request is: 0049069-231120084113126

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5129]
**Hello, I would like to download the real coordinate data for rare species, not the obfuscated coordinates. I am analyzing altitudinal ranges for a conservation project among 904 species and the coordinate randomization is compromising the whole analysis. Is there a way to get a download of the true coordinates? Thanks for your consideration. The download request is: 0049069-231120084113126**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e1cca4f96eba6da01f1e55c6df3a9353:c9d9b496bce0193a53fc07a570f761a88c9aefecd8f7f0ef40b5b63bf0cc339376bb2015de242ffa4c7f0148f4dd54b6830d14afb9a244a7f7634d2dcc5c813d6a7f7e077e5d0503b11260e3f4a855dc540c51e2531c2cd5f03e334604cb70d35bfce0d8d95ccfe19baa750d5691601edc24daf0f5485f7cfa77263a6279348198b0468c4ac11f3a6fbe9f3c91c699d5) - [Send email](https://www.gbif.org/api/feedback/user/mailto/e1cca4f96eba6da01f1e55c6df3a9353:c9d9b496bce0193a53fc07a570f761a88c9aefecd8f7f0ef40b5b63bf0cc339376bb2015de242ffa4c7f0148f4dd54b6830d14afb9a244a7f7634d2dcc5c813d6a7f7e077e5d0503b11260e3f4a855dc540c51e2531c2cd5f03e334604cb70d35bfce0d8d95ccfe19baa750d5691601edc24daf0f5485f7cfa77263a6279348198b0468c4ac11f3a6fbe9f3c91c699d5)
System: Chrome 120.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/
Window size: width 1707 - height 905
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-10T15:47:05.903Z',to:'2024-01-10T15:53:05.903Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-10T15:47:05.903Z',to:'2024-01-10T15:53:05.903Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

GBIF doesn’t obscure coordinates. What you can see on our platform is what was provided by the data providers. We don’t have access to unobscured version of the data.
If you would like to access the original data, you will have to contact the individual data providers. Each occurrence in your download should be associated with a dataset (page) and contact information. This is an example of a dataset page: https://www.gbif.org/dataset/7fac7128-936b-4da9-8baf-6020bb898fb7 (note that the URL contains the datasetKey from your download).
