### ISSUE TITLE
Dataset deleted and duplicated

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#513]
**Dataset deleted and duplicated**

Either the deletion was accidental, or else the citations should probably be moved to the new one.

https://www.gbif.org/dataset/962f59bc-f762-11e1-a439-00145eb45e9a

https://www.gbif.org/dataset/67268aeb-d714-4873-ab08-b9d06a78b097

-----
fbitem-dataset962f59bc-f762-11e1-a439-00145eb45e9a
User provided contact info: MattBlissett
System: Firefox 55.0.0 / Mac OS X 10.12.0
Referer: https://www.gbif.org/dataset/962f59bc-f762-11e1-a439-00145eb45e9a
Window size: width 1440 - height 770
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-04T15:11:15.583Z',mode:absolute,to:'2017-10-04T15:17:15.583Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-04T15:11:15.583Z',mode:absolute,to:'2017-10-04T15:17:15.583Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
And both datasets are being crawled, with the deletion partway through, so the occurrences will probably need to be deleted at the end.

**Comment by MortenHofft** [comment]
I don't see any citations on the deleted dataset. This is probably done already
