### ISSUE TITLE
Melia azedarach

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5130]
**Melia azedarach**

Mistaken identification

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5a21e6dfeb827885ebc0cedce22a52a6:e601cfebd24b49c58e91cb4fd70cb3e2d53c5cc7066d634bf2bc5ffe9816eec5a7d819fe8db41175294e6cf03300a9ab7b30045de0ffc9f732f87c7736ca24304441a01529f867df25360f92503f0ca2c55bab7780aafe601f657d15a6c60c45) - [Send email](https://www.gbif.org/api/feedback/user/mailto/5a21e6dfeb827885ebc0cedce22a52a6:e601cfebd24b49c58e91cb4fd70cb3e2d53c5cc7066d634bf2bc5ffe9816eec5a7d819fe8db41175294e6cf03300a9ab7b30045de0ffc9f732f87c7736ca24304441a01529f867df25360f92503f0ca2c55bab7780aafe601f657d15a6c60c45)
System: Firefox 121.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/occurrence/1805401511
Window size: width 1760 - height 783
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-10T17:54:04.426Z',to:'2024-01-10T18:00:04.426Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-10T17:54:04.426Z',to:'2024-01-10T18:00:04.426Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

Node handles: @sformel-usgs

**Comment by sformel-usgs** [comment]
It looks like this iNaturalist occurrence has been removed and this ticket can be closed. @ManonGros @CecSve

**Comment by CecSve** [comment]
Thanks!
