### ISSUE TITLE
include contact information of regional support team on GBIF contact page

### ISSUE THREAD

**Issue by ymgan** [gbif/portal-feedback#5135]
Hi, 

I am wondering if it is possible to include contact information of regional support team on GBIF contact page? I was looking for the email of GBIF ECA regional support team but there was no dedicated tab/page for it (unless I missed it). 

Thanks a lot!

**Comment by kcopas** [comment]
Thanks for the suggestion—update made, changes will post, ctrl/cmd+R 😄

**Comment by kcopas** [comment]
Content updated ([see here](https://www.gbif.org/article/6bWSsUaSOs4kYuYk8cqo4E/contacts)), but the copy cached for the alias https://www.gbif.org/contact-us has not yet updated. Reopening so that we can keep an eye on it with @MortenHofft

**Comment by MortenHofft** [comment]
Turns out the cache will expire in 100 days. I've missed that everything on route `/api/template` has a 100 day cache, and since I had reused that url prefix for the contacts template then it inherited the 100 day public URL cache.

That should now be fixed on all relevant route
