### ISSUE TITLE
The link to the image of the preserved specimens for this occurrence is https://collections.nmnh.si.edu/media/?i=14654853&ph=yes&thumb=yes. Adding it would open the occurrence to greater scrutiny.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5138]
**The link to the image of the preserved specimens for this occurrence is `https://collections.nmnh.si.edu/media/?i=14654853&amp;ph=yes&amp;thumb=yes.` Adding it would open the occurrence to greater scrutiny.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3c94abb25c7a415838a629aff8b43353:a1080ebc815a9c707ccd5505af0ce9a9862997c9bc585672c37404df3062963b391debd7ef21174b845aab54de1c9192e1ce0ab3b486eafbac13240ab67142f321a32b1d0bf6c2fbb2c41c95c3ece45d84da310a8315aa7e86bb5b1768bb729d4e3ceaf2f8d0e39f7493641e757e54993d8122483843c1eb1317ccd3e017cad7) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3c94abb25c7a415838a629aff8b43353:a1080ebc815a9c707ccd5505af0ce9a9862997c9bc585672c37404df3062963b391debd7ef21174b845aab54de1c9192e1ce0ab3b486eafbac13240ab67142f321a32b1d0bf6c2fbb2c41c95c3ece45d84da310a8315aa7e86bb5b1768bb729d4e3ceaf2f8d0e39f7493641e757e54993d8122483843c1eb1317ccd3e017cad7)
System: Firefox Mobile 121.0.0 / Android 0.0.0
Referer: https://www.gbif.org/occurrence/1319473027
Window size: width 324 - height 335
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-19T11:54:43.274Z',to:'2024-01-19T12:00:43.274Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-19T11:54:43.274Z',to:'2024-01-19T12:00:43.274Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 821cc27a-e3bb-4bc5-ac34-89ada245069d
publishingOrgKey: bc092ff0-02e4-11dc-991f-b8a03c50a862
Network keys: 99d66b6c-9087-452f-a9d4-f15f2c2d0e7e 
Node handles: @sformel-usgs

**Comment by sformel-usgs** [comment]
Thanks for pointing this out.  @gamblebnmnh, would it be possible to add this link via the `associatedMedia` term?

**Comment by gamblebnmnh** [comment]
@sformel-usgs We utilize the auduboncore data table to link our images but I do see that we are putting data in Associated Media so I will update that to use the link.  Next publication will be Feb 2, 2024.

**Comment by gamblebnmnh** [comment]
@gbif-portal , why is the Audubon Media Description data not shown on the details page of a occurrence record?  Our IPTs have image data in that table.

**Comment by sformel-usgs** [comment]
I'm going to tag @ManonGros since I'm not sure who monitors the `gbif-portal` handle.  Marie should be able to help us out.

**Comment by MattBlissett** [comment]
Hi,

This particular dataset has the Audubon/Audiovisual description mapped, but it doesn't contain any data.  See the "multimedia.txt" file in the Darwin Core Archive, which contains only the header row.

**Comment by gamblebnmnh** [comment]
Ahh,  sorry about that.  Something must have happened during last publish cycle.  Manually republished and Multmedia file now has data.

**Comment by sformel-usgs** [comment]
@MattBlissett looks like the data is good to go, you can close this ticket.
