### ISSUE TITLE
License in summary box does not match information in other places

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#514]
**License in summary box does not match information in other places**

Checklist dataset https://www.gbif.org/dataset/e08de352-9383-48b0-88ae-be15cce386c5, also containing occurrence records, does not specify a license in its metadata. The dialog on downloading the Annotated Archive gives the information that the License is CC0 1.0. This should be CC-BY, following the sense of the GBIF data publisher agreement (https://www.gbif.org/terms/data-publisher)

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
User provided contact info: ahahn-gbif
System: Firefox 56.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/download?dataset_key=e08de352-9383-48b0-88ae-be15cce386c5
Window size: width 1224 - height 566
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T08:14:43.824Z',mode:absolute,to:'2017-10-05T08:20:43.824Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T08:14:43.824Z',mode:absolute,to:'2017-10-05T08:20:43.824Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi @ahahn-gbif 
If I understand correctly this issue has resolved itself (unless someone else has fixed it willingly).
* The [occurrence download page](https://www.gbif.org/occurrence/download?dataset_key=e08de352-9383-48b0-88ae-be15cce386c5) says CC BY
* The [dataset](https://www.gbif.org/dataset/e08de352-9383-48b0-88ae-be15cce386c5) says CC BY
* The [GBIF annotated meta data](https://api.gbif.org/v1/dataset/e08de352-9383-48b0-88ae-be15cce386c5/document) says CC BY
* the [original darwinC](http://formicidae-bg.myspecies.info/gbif-dwca.zip ) says CC BY
* the [dataset search](https://www.gbif.org/dataset/search?q=The%20Ants%20of%20Bulgaria) says CC BY
* [all 92 occurrence in search](https://www.gbif.org/occurrence/search?dataset_key=e08de352-9383-48b0-88ae-be15cce386c5&license=CC_BY_4_0) are all CC BY

The only difference I see is that the original archive states CC  BY v3 and we map to CC By v4.
Odd. It hasn't changed for a while, so I guess the index shouldn't have changed.

**Comment by MattBlissett** [comment]
Assigning Andrea for confirmation this is resolved and can be closed.

**Comment by ahahn-gbif** [comment]
Confirm looks ok - closing
