### ISSUE TITLE
Clearly test occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5148]
Clearly test occurrences around this dta with the silly image

https://www.gbif.org/occurrence/gallery?q=test&dataset_key=38b4c89f-584c-41bb-bd8f-cd1def33e92f

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/90cf5a150f80c5ae87b86a1d5887771c:7b63e1400a45ee9c99b10edf7bc9773f627d8986f97211bf597d741e49a82d54a2e6d137654a3fd9a2f0aa95442602c1fbb57e9a5cd77a99a7f307e878455a66c545c84ea270884cda2c80cb5ab1aabd4ec7bac3d17d0e7f873e748402edfaab6e42df3969ae8bd630acfc4d1bed506d7636eb12e247e33b67181dd7afcb5a1e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/90cf5a150f80c5ae87b86a1d5887771c:7b63e1400a45ee9c99b10edf7bc9773f627d8986f97211bf597d741e49a82d54a2e6d137654a3fd9a2f0aa95442602c1fbb57e9a5cd77a99a7f307e878455a66c545c84ea270884cda2c80cb5ab1aabd4ec7bac3d17d0e7f873e748402edfaab6e42df3969ae8bd630acfc4d1bed506d7636eb12e247e33b67181dd7afcb5a1e)
System: Chrome 120.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/4146444756
Window size: width 2031 - height 1525
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-23T14:44:11.478Z',to:'2024-01-23T14:50:11.478Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-23T14:44:11.478Z',to:'2024-01-23T14:50:11.478Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 38b4c89f-584c-41bb-bd8f-cd1def33e92f
publishingOrgKey: b8323864-602a-4a7d-9127-bb903054e97d

**Comment by MattBlissett** [comment]
See https://www.gbif.org/occurrence/gallery?q=test&dataset_key=38b4c89f-584c-41bb-bd8f-cd1def33e92f

**Comment by CecSve** [comment]
The Swedish Node has been contacted and is looking into removing the test data

**Comment by Adbmnk** [comment]
The Artportalen team has removed incorrect observations
