### ISSUE TITLE
Using RGBIF package, I cannot use the occ_download function as I am given the error 401 - unauthorised. I have created an account with GBIF, and have tried adding my credentials to the Renvironment as the vignette shows and also by manually inputting them as arguments into the occ_download function but the error remains. How can IFix this to download species occurence data please? Kind regards,

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5149]
**Using RGBIF package, I cannot use the occ_download function as I am given the error 401 - unauthorised. I have created an account with GBIF, and have tried adding my credentials to the Renvironment as the vignette shows and also by manually inputting them as arguments into the occ_download function but the error remains. How can IFix this to download species occurence data please? Kind regards,**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fd2e3b6329818a10cf174495507aca71:62c497490f40f319282c65c3dc785dcdb1d5368f6c98065afbe04f4003399fc4f75f10f97f3a9451f99e8a3e6f6d5944a62a311da2a5feb24e2c28bc73bf879c957e6d7312b3e9fd34199c569083829bb2c0eaabea8e3277e30bbcfc7f8a99b0bbcf0f2840ba3de99e90d1e7f6a1bae5d6b4c244cec44c5a8f7a34155c84dbde) - [Send email](https://www.gbif.org/api/feedback/user/mailto/fd2e3b6329818a10cf174495507aca71:62c497490f40f319282c65c3dc785dcdb1d5368f6c98065afbe04f4003399fc4f75f10f97f3a9451f99e8a3e6f6d5944a62a311da2a5feb24e2c28bc73bf879c957e6d7312b3e9fd34199c569083829bb2c0eaabea8e3277e30bbcfc7f8a99b0bbcf0f2840ba3de99e90d1e7f6a1bae5d6b4c244cec44c5a8f7a34155c84dbde)
System: Chrome 120.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0073927-231120084113126
Window size: width 1920 - height 919
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-24T21:54:28.812Z',to:'2024-01-24T22:00:28.812Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-24T21:54:28.812Z',to:'2024-01-24T22:00:28.812Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by jhnwllr** [comment]
responded via email,.
