### ISSUE TITLE
Niger missing participant description

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#515]
**Niger missing participant description**

-----
fbitem-430bafc4cbca3bfdc054962fb9843810911e02b6
User provided contact info: mortenhofft
System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/country/NE/participation
Window size: width 1918 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T08:18:13.890Z',mode:absolute,to:'2017-10-05T08:24:13.890Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T08:18:13.890Z',mode:absolute,to:'2017-10-05T08:24:13.890Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
@melianieraymond would this be something you could help with?

**Comment by melianieraymond** [comment]
Sanja is now doing a request to all nodes to update or provide this information. From now on, this should be an annual process run by admin.

**Comment by kcopas** [comment]
Closing—process in place, addition of content dependent on response from node
