### ISSUE TITLE
Coordinates swapped an incorrect negation

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5152]
**Coordinates swapped an incorrect negation**

It looks like the coordinates here should be:

`decimalLatitude` == 42.3488998413
`decimalLongitude` == -82.9561004639

for the occurrence to be correctly georeferenced to Michigan, USA.

I've also sent an email to ummz-mollusks-data@umich.edu notifying them.

-----

Github user: @sformel-usgs
User: [See in registry](https://www.gbif.org/api/feedback/user/36119750a613ab93c7e6f025932aad95:032f806af451e429cefd2e74daf8a8f2bab5807f4571757ccab1238e03c8841b0b115e7b7ba0889f32499eada6da02e902a1cac2e352deab604885cd26c6e22d92ee1d7b976b3fd2157890d71b3f4e40a798186505d3b60d54231df9b16d87535bdfad46e26cc581d38279d7a8e21269397eb571575d4b730f18c34819f2cd0c) - [Send email](https://www.gbif.org/api/feedback/user/mailto/36119750a613ab93c7e6f025932aad95:032f806af451e429cefd2e74daf8a8f2bab5807f4571757ccab1238e03c8841b0b115e7b7ba0889f32499eada6da02e902a1cac2e352deab604885cd26c6e22d92ee1d7b976b3fd2157890d71b3f4e40a798186505d3b60d54231df9b16d87535bdfad46e26cc581d38279d7a8e21269397eb571575d4b730f18c34819f2cd0c)
System: Chrome 120.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1882241408
Window size: width 1498 - height 746
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-26T17:25:47.093Z',to:'2024-01-26T17:31:47.093Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-26T17:25:47.093Z',to:'2024-01-26T17:31:47.093Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO
datasetKey: 7dd6e9f8-f252-42c9-bd34-221716095973
publishingOrgKey: 6ea87510-0561-11d8-b851-b8a03c50a862

Node handles: @sformel-usgs

**Comment by sformel-usgs** [comment]
Heard back from Tom Duda:

> Thanks for catching that and informing us about it. I agree with you that it looks like the coordinate values got flipped. This is what the record shows: 82.9561004639, -42.3488998413. Flipping the numbers (i.e., 42.3488998413, -82.9561004639) gives a location at Belle Isle (which is what the catalog says).

I'll keep this open until I see those changes reflected in GBIF.

**Comment by sformel-usgs** [comment]
From Taehwan Lee:
 
> Thanks for letting me know. The information has been corrected in our Specify database. Since GBIF pulls our data every month, it will be corrected in a few days.

**Comment by jhnwllr** [comment]
This appears correct now. @sformel-usgs
