### ISSUE TITLE
What is the meaning of a "proparte synonym"?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5156]
**What is the meaning of a &quot;proparte synonym&quot;?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/471e8d3f23659af90842a16a7d52d343:2eea1551981c43829276e0a0cd251d2141874f2bf55778f178e7ce6b17ba03b7e645a3e4d3ea0f4f72dc8a80b2e9948e4997a6273d7d06a7eee95ce3ede97676e9afa3d9e7a683b22bc53dc69837af9d29c96509295b266437e04b0320a73e18c63156ff384121d4cfa54ec194bf5821a1b00247a3b2e6e3e0cfeaaa86e184b02e06896979363d0bab89450416d263f2) - [Send email](https://www.gbif.org/api/feedback/user/mailto/471e8d3f23659af90842a16a7d52d343:2eea1551981c43829276e0a0cd251d2141874f2bf55778f178e7ce6b17ba03b7e645a3e4d3ea0f4f72dc8a80b2e9948e4997a6273d7d06a7eee95ce3ede97676e9afa3d9e7a683b22bc53dc69837af9d29c96509295b266437e04b0320a73e18c63156ff384121d4cfa54ec194bf5821a1b00247a3b2e6e3e0cfeaaa86e184b02e06896979363d0bab89450416d263f2)
System: Opera 106.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/data-use
Window size: width 1306 - height 885
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-27T20:36:44.273Z',to:'2024-01-27T20:42:44.273Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-27T20:36:44.273Z',to:'2024-01-27T20:42:44.273Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
Replied by email

> A pro parte synonym denotes that a taxon includes more than one currently recognized entity, it can be caused by subdivided taxa and circumscriptional changes.
For example, Reptilia is labelled as a pro parte synonym of Crocodylia on GBIF: https://www.gbif.org/species/358. The concept of Reptilia actually corresponds to four accepted classes: [Testudines](file:///species/11418114), [Sphenodontia](file:///species/11569602), [Squamata](file:///species/11592253) and [Crocodylia](file:///species/11493978).
