### ISSUE TITLE
The IUCN status of plant species selected from sites in South Africa appears to be incorrect.  Most of the species are indicated as NE (Not Evaluated), but this is incorrect?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5160]
**The IUCN status of plant species selected from sites in South Africa appears to be incorrect. Most of the species are indicated as NE (Not Evaluated), but this is incorrect?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/72d56f574cbd2ff7346b52f3ef28ce8c:7faa0b6bf41b14e5ba01c94047822949f96a829d07c6a0b75606e47ca8ab5645b6d26fbe2f0db62ca7c978ba0f695ac88e33d0ca9f8e6d8e7043515ca52e6650c66a6c62d52c5226f915236cd4c856943325a9b86df9eac2258c24730df898fd) - [Send email](https://www.gbif.org/api/feedback/user/mailto/72d56f574cbd2ff7346b52f3ef28ce8c:7faa0b6bf41b14e5ba01c94047822949f96a829d07c6a0b75606e47ca8ab5645b6d26fbe2f0db62ca7c978ba0f695ac88e33d0ca9f8e6d8e7043515ca52e6650c66a6c62d52c5226f915236cd4c856943325a9b86df9eac2258c24730df898fd)
System: Chrome 121.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/map?dataset_key=d0963cee-1a29-47a2-b9bf-fb0e7690077c&has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON((26.02459%20-26.30947,26.29634%20-26.30947,26.29634%20-26.06657,26.02459%20-26.06657,26.02459%20-26.30947))&occurrence_status=present
Window size: width 1920 - height 929
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-30T06:57:51.172Z',to:'2024-01-30T07:03:51.172Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-30T06:57:51.172Z',to:'2024-01-30T07:03:51.172Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
> replied by email

The IUCN threat status displayed on the [GBIF occurrence search interface](https://www.gbif.org/occurrence/map?dataset_key=d0963cee-1a29-47a2-b9bf-fb0e7690077c&has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON((26.02459%20-26.30947,26.29634%20-26.30947,26.29634%20-26.06657,26.02459%20-26.06657,26.02459%20-26.30947))&occurrence_status=present) is based on [this version](https://www.gbif.org/dataset/19491596-35ae-4a91-9a98-85cf505f1bd3) of the IUCN Global red list of threatened species. This list doesn’t include local IUCN assessments. In addition to that, this list in matched to occurrences available on GBIF by matching the scientific names to the [GBIF backbone taxonomy](https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c). If a name isn’t available in the IUCN Global red list, its associated occurrences, will be shown as “NE”.
