### ISSUE TITLE
Dataset isn't being ingested

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5163]
**Dataset isn&#39;t being ingested**

This dataset hasn't been ingested in quite some time. The archive at the endpoint isn't accessible.
However, in the same IPT, this metadata-only dataset is available: https://ipt.gbif.us/resource?r=usgs_pwrc-bbl-us_bandings_state_1960-2010. Does it mean that there shouldn't be any occurrence associated with this dataset any more?
Tagging @sformel-usgs

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/a9f635916a453712f3545dd099d9e71e:c10d44c9b1ba5e96cface7159e64cd22ce17729fad38e40c81b866df6d94e979b8850a346c1ebc40fc2f3a4925b7ccbb3a8f423933ac48a65120da88da94ba134f43283af07599e51560a479938140ece65dcf06b4a7d65bb4dbc064aa525034a272c59078f6ad948a9054f519bc1bd7383dd515d38891742e2aeecba75c1d71a1c067c1bb061ef7007290252746f603) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a9f635916a453712f3545dd099d9e71e:c10d44c9b1ba5e96cface7159e64cd22ce17729fad38e40c81b866df6d94e979b8850a346c1ebc40fc2f3a4925b7ccbb3a8f423933ac48a65120da88da94ba134f43283af07599e51560a479938140ece65dcf06b4a7d65bb4dbc064aa525034a272c59078f6ad948a9054f519bc1bd7383dd515d38891742e2aeecba75c1d71a1c067c1bb061ef7007290252746f603)
System: Safari 17.3.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/721a99a4-71f4-4466-b346-83c367889238
Window size: width 1704 - height 927
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-31T13:58:45.074Z',to:'2024-01-31T14:04:45.074Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-31T13:58:45.074Z',to:'2024-01-31T14:04:45.074Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by sformel-usgs** [comment]
It looks like the IPT endpoint was lost during the IPT migration.  I'll regenerate it and update here when it's done. We're working with the provider to update this dataset, but it might take a few more months.

**Comment by MattBlissett** [comment]
It's also missing in the TAR.GZ file used for that migration.

In case it's useful, we have the last successful download of the DWCA stored. It's 260MB from 2021-10-05 18:25.

**Comment by sformel-usgs** [comment]
@MattBlissett that is very useful.  Can you add that to the correct endpoint in the IPT?  If not, can you please email it me and I will upload and publish it.

**Comment by CecSve** [comment]
@sformel-usgs let me know if everything worked out so I can close the issue

**Comment by sformel-usgs** [comment]
Sorry for the delay on this.  I mistakenly thought that the remaining resource on the IPT was a dataset. It's actually just metadata, so I can't just plug in the data like I hoped.  I'm going to double check with Abby on this one, to make sure I'm not creating problems for the provider (who is working on a new version of the data) by re-creating this dataset.

**Comment by sformel-usgs** [comment]
Ok, the only problem with me re-creating this data from the DwC-A that Matt sent me, but I want to check on some technical things before I do.   @CecSve could you please give these some thought?

1. The shortname for the orphaned resource is now being used by the metadata-only dataset. As far as I know there is no way to convert the metadata-only to an occurrence dataset. Correct?
2. If I delete the metadata-only dataset and create a new resource under the same shortname, can you/I manually apply the correct datasetKey and DOI to the new resource?
3. Will all the occurrenceIDs be automatically indexed, recognized as already existing, and be functionally restored? or does some magic need to be applied for everything to link back up?

**Comment by CecSve** [comment]
> 1. The shortname for the orphaned resource is now being used by the metadata-only dataset. As far as I know there is no way to convert the metadata-only to an occurrence dataset. Correct?

In the latest IPT version it should be possible to make a dataset type change automatically by adding occurrences. Can you try this first?

> 3\. Will all the occurrenceIDs be automatically indexed, recognized as already existing, and be functionally restored? or does some magic need to be applied for everything to link back up?

If it is the same occurrenceIDs as previously, then yes, it should be restored. Unless the dataset is older than when we implemented occurrenceID indexing.

**Comment by sformel-usgs** [comment]
Thanks for your patience on this one.  The update seems to have gone through fine and the issue can be closed.

**Comment by ManonGros** [comment]
Thanks Steve!
