### ISSUE TITLE
Download failure

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5165]
**Download failure**

Hello, I have the following list of species I'd like to download observations for within the United States, but I received an error email that it failed. The list in question:

Myriophyllum L. Najas L. Potamogeton L. Lemna minor L. Brasenia schreberi J.F.Gmel. Wolffia borealis (Engelm.) Landolt Marsilea vestita Hook. & Grev. Nuphar lutea (L.) Sibth. & Sm. Nymphaea odorata Sol. ex Aiton Sagittaria Ruppius ex L. Typha L. Zizania aquatica L. Downingia bicornuta A.Gray Cephalanthus occidentalis L. Nelumbo lutea (Willd.) Pers. Carya aquatica (F.Michx.) Nutt. Leersia oryzoides (L.) Sw. Acorus americanus (Raf.) Raf. Carex aquatilis Wahlenb. Toxicodendron vernix (L.) Kuntze Carex scoparia Schkuhr Aconitum columbianum Nutt. Cornus amomum Mill. Eleocharis compressa Sull. Lysimachia ciliata L. Platanthera dilatata (Pursh) Lindl. Salix amygdaloides Andersson Ranunculus flammula D.Don Ranunculus inamoenus Greene Sanguisorba canadensis L. Symphyotrichum novae-angliae (L.) G.L.Nesom Viola nephrophylla Greene Tamarix chinensis Lour.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6b1208fd8b09635cd75e88844bbc3789:79cb62d09016213a3d6b6fea1230fee185df3d673989e9761e77fc0ca4f055d081278bc15764f9ab6cfa8cd889214ac17f54759e2e8c9423570633e393678b4bb4d23452184b1b67b24246ca9e69f0df64a4a38c0f51a4997e4222cc4c058c9b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6b1208fd8b09635cd75e88844bbc3789:79cb62d09016213a3d6b6fea1230fee185df3d673989e9761e77fc0ca4f055d081278bc15764f9ab6cfa8cd889214ac17f54759e2e8c9423570633e393678b4bb4d23452184b1b67b24246ca9e69f0df64a4a38c0f51a4997e4222cc4c058c9b)
System: Chrome 121.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0002265-240130105604617
Window size: width 1679 - height 856
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-31T17:27:53.869Z',to:'2024-01-31T17:33:53.869Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-31T17:27:53.869Z',to:'2024-01-31T17:33:53.869Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Issue with a small percentage of downloads failing is hopefully corrected by https://github.com/gbif/occurrence/commit/7b9c272deb3013a13b93c4fa1a860f9f24e5c04b

Replied by email.
