### ISSUE TITLE
Bug indexing a dataset because a "change in occurrenceIDs"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5166]
**Bug indexing a dataset because a &quot;change in occurrenceIDs&quot;**

This datasets has not been indexed and in the registry it says that is because occurrenceIDs were changed, but this is the first publication of thit dataset. Maybe in the reindexing process something happened,

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d89d1ac3e1340a9fd2057df82ed40fee:3b3aeba4e6c8c9ca18eeaafbc445e8a040163ac7ea9c566be74e866fb224697c21b7a12dae9776a555ccde1b60ce6023045f1e0a69c38bfaca4f389b86e869dbd284a048cbf449ebd32feba00cd8c30f345fd70d18d85f12c6b5a8f1f9b12ff1) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d89d1ac3e1340a9fd2057df82ed40fee:3b3aeba4e6c8c9ca18eeaafbc445e8a040163ac7ea9c566be74e866fb224697c21b7a12dae9776a555ccde1b60ce6023045f1e0a69c38bfaca4f389b86e869dbd284a048cbf449ebd32feba00cd8c30f345fd70d18d85f12c6b5a8f1f9b12ff1)
System: Chrome 121.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/1c7e5e56-057f-43c2-a980-c9b500f812f5
Window size: width 1222 - height 684
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-31T20:37:07.522Z',to:'2024-01-31T20:43:07.522Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-31T20:37:07.522Z',to:'2024-01-31T20:43:07.522Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
The dataset has been reingested manually after the indexing pause earlier this week. The user has been contacted through help desk.
