### ISSUE TITLE
Occurrence search cannot facet by eventDate any more

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#5167]
This is a message that we recently received on helpdesk. This type of query doesn't work any more: https://api.gbif.org/v1/occurrence/search?gadmGid=USA.46_1&occurrenceStatus=PRESENT&taxonKey=6171851&facet=eventDate&facetLimit=1200000&limit=0

I will suggest to use https://api.gbif.org/v1/occurrence/search?gadmGid=USA.46_1&occurrenceStatus=PRESENT&taxonKey=6171851&facet=year&facetLimit=1200000&limit=0 but perhaps there is a way to make the eventDate facet work?

Related issue: https://github.com/gbif/gbif-api/issues/4#issuecomment-1735378954/

**Comment by MattBlissett** [comment]
The [old documentation](https://github.com/gbif/portal-feedback/issues/4842) said eventDate wasn't a supported facet field, though it must have started working at some point — that was probably an oversight.

It's not clear what a useful facet on eventDate would be, when the column might contain values like `1899`, `1980/1990`, `1989-01-30`, `2024-02-01T18:13:00` and so on (i.e. a mixture of dates at all resolutions, explicit or implicit rages, and dates with times).

**Comment by jloomisVCE** [comment]
We were aware that it wasn't supported and yet it worked... so we built web-apps around it. Specifically, granular phenology charts that are the (actual) rage in the bee and butterfly worlds (we had just published for our VT Butterfly Atlas a first/last Day-of-Year phenology feature requested by the Atlas team). To make it work, we had to discard nonsense eventDates anyway (eg. dates on the first of the year with T00:00:00), so contending with date ranges seems manageable. If there's a way you can still allow it - even if you must discard any date/range that can't be distilled to a day - this would be a big deal for us. If you see another way to get phenology by DOY from the occurrence API that's what we're after. Many thanks.

**Comment by MortenHofft** [comment]
The old documentation (until a few weeks ago) read
>  "facet": "A facet name used to retrieve the most frequent values for a field. Facets are allowed for all the parameters except for: eventDate, geometry, lastInterpreted, locality, organismId, stateProvince, waterBody.  This parameter may by repeated to request multiple facets, as in this example

The current documentation for occurrence search says: 
> A facet name used to retrieve the most frequent values for a field. Facets are **allowed for all search parameters except geometry and geoDistance**. This parameter may by repeated to request multiple facets, as in [this example](https://api.gbif.org/v1/occurrence/search?facet=datasetKey&facet=basisOfRecord&limit=0).

start and end day of year facets is possible if that helps
https://api.gbif.org/v1/occurrence/search?facet=startDayOfYear&facetLimit=367

For event dates we could just facet on `eventDateInterval` (ES field) that is already a keyword and so allow facets. And to make it easier to filter out ranges we could add a flag for event dates that are ranges (isDateRange or eventDateResolution or ...). 
That would keep the past, but unofficial, behaviour intact. The only difference would be that the facet results, can now return ranges, so users would  have to deal with that. So assumption on it being single dates would have to be revisited.

**Comment by MattBlissett** [comment]
Thanks Morten, using `eventDateInterval` seems sensible.

**Comment by MortenHofft** [comment]
@tobiasgf do you have any comments on the need to filter occurrences based on the eventDate duration? As in "do not/only show me occurrences that have a range below 2 days"

**Comment by tobiasgf** [comment]
I cannot immediately see a direct use, but there may be some. Indirect use could be to use it as a proxy for monitoring data?
Maybe @kingenloff has som more informed comments?

**Comment by MortenHofft** [comment]
I simply imagined that for some use cases, knowing that it happened on a specific day vs sometime during a 2 year span could make a big difference. And there isn't really a way to add such a filter currently. A bit like we have `coordinateUncertaintyInMeters`

**Comment by MattBlissett** [comment]
> I simply imagined that for some use cases, knowing that it happened on a specific day vs sometime during a 2 year span could make a big difference. And there isn't really a way to add such a filter currently.

I think this can be useful, there's a related requirement for B-cubed, but it's a new issue.

**Comment by ManonGros** [comment]
Why not provide all eventDates and let the users sort out what they want to do with those?

**Comment by MortenHofft** [comment]
> Why not provide all eventDates and let the users sort out what they want to do with those?

The suggestion isn't to remove anything. It is to enable facets by EventDate again. But since we now process event ranges, then the results of the facets will be different. In that it can include ranges, year only etc. So the users will have to take that into account. In the past it has always been a single date.

Then there is an additional suggestion to add one or more new filters to include or discard event ranges. E.g.
`?issues=IS_DATE_RANGE` to only include occurrences with date ranges. Or a new filter like `?eventDateDurationInDays=3,10` (just loose ideas and questions)

**Comment by fmendezh** [comment]
the facet is back using the eventDateInternal data for factes

**Comment by jloomisVCE** [comment]
Thank you very much for this discussion and for these facet query features.
