### ISSUE TITLE
asdasdasd

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5174]
**asdasdasd**

This is a test issue

-----

Github user: @tobiasgf
User: [See in registry](https://www.gbif.org/api/feedback/user/6b490a66be7e974534ee91ebf3780826:3c00f1a4c420e2087d11c95f101a0175b5839afc22daf6634f8a745539dabfe61cdd1b84047c49890271e9bf9044ea8babb7f165fad1f5370ab92bd6a4106e90dba9912da55afd84cd3b3458688488b8906c12e46eaee3a38b5b662b6aa9939be4042485200d9725f2949d5ff891e95f2e3cd65dba9629d051d39cadcdf14dd404354c436ee79d70e155eddb22c1cca5) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6b490a66be7e974534ee91ebf3780826:3c00f1a4c420e2087d11c95f101a0175b5839afc22daf6634f8a745539dabfe61cdd1b84047c49890271e9bf9044ea8babb7f165fad1f5370ab92bd6a4106e90dba9912da55afd84cd3b3458688488b8906c12e46eaee3a38b5b662b6aa9939be4042485200d9725f2949d5ff891e95f2e3cd65dba9629d051d39cadcdf14dd404354c436ee79d70e155eddb22c1cca5)
System: Chrome 121.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/e94f1b8b-671f-4ca4-9e4d-ffef194430da
Window size: width 1912 - height 968
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-07T13:45:24.884Z',to:'2024-02-07T13:51:24.884Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-07T13:45:24.884Z',to:'2024-02-07T13:51:24.884Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by tobiasgf** [comment]
closing test
