### ISSUE TITLE
Gaining access to our organizational account

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5175]
**Gaining access to our organizational account**

Hi,

I'm IT Manager for NatureServe - https://www.gbif.org/publisher/aa40a1e0-818b-11d9-b6d0-b8a03c50a862

Due to staff turnover and a switch to Office 365, we no longer have access to the publisher maintenance pages.  We would like to update our logo, in this instance.  Could I somehow get linked as an admin, which I'm presuming would allow me to (a) update the logo and (b) link other staff?  ('a' is definitely the priority for now).  I'm listed as the technical point of contact for https://www.gbif.org/installation/fb3dafd2-6b38-4b1d-956e-26e587af54ed

Thanks,

Frank

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8b2916f8b692dc680a08a81e08c302df:4a7b9e4c90b267eebdf82f2a1f2f34cf5edf39a9e5af443195bb9a36ff1efd67f2fb24ef6eb74bb06e15e48296859a69aa7f50e011c74ab79c0991e828d00e01d1931350c7a72e805de7eae79e84386d7647abe04c2a8a3093ed2f5540b80a79889aa01c67e5442d598421eac512c3a96bfffdeba48a2a013004eb3b99784b05) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8b2916f8b692dc680a08a81e08c302df:4a7b9e4c90b267eebdf82f2a1f2f34cf5edf39a9e5af443195bb9a36ff1efd67f2fb24ef6eb74bb06e15e48296859a69aa7f50e011c74ab79c0991e828d00e01d1931350c7a72e805de7eae79e84386d7647abe04c2a8a3093ed2f5540b80a79889aa01c67e5442d598421eac512c3a96bfffdeba48a2a013004eb3b99784b05)
System: Chrome 121.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/aa40a1e0-818b-11d9-b6d0-b8a03c50a862
Window size: width 1920 - height 919
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-08T18:45:35.203Z',to:'2024-02-08T18:51:35.203Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-08T18:45:35.203Z',to:'2024-02-08T18:51:35.203Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
User has been contacted through helpdesk

**Comment by CecSve** [comment]
This issue has already been resolved and I will close the issue
