### ISSUE TITLE
Should the data tables in a DwC archive have headers?

### ISSUE THREAD

**Issue by Mesibov** [gbif/portal-feedback#5176]
I am occasionally seeing DwC archives with fields listed in meta.xml but with no header lines with fieldnames in occurrence.txt, identification.txt etc. On the command line I can build a header for each table from meta.xml, but this is fiddly and time-consuming.

Looking through GBIF's documentation of DwC archiving I haven't seen a recommendation to include headers in data tables, but I may have missed it. Is it good practice (in GBIF's view) to do this?

**Comment by thomasstjerne** [comment]
This is optional, and configured by the `ignoreHeaderLines` attribute of the `core` and `extension` blocks in the meta.xml file.
For example:

`<core encoding="UTF-8" fieldsTerminatedBy="\t" linesTerminatedBy="\n" fieldsEnclosedBy='' ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/Taxon">`

**Comment by Mesibov** [comment]
@thomasstjerne, many thanks for your quick response. How would you answer my question?

I am also a little confused by the ignoreHeaderLines entry in the [DwC text guide](https://dwc.tdwg.org/text/). The default value is "0" meaning "ignore"? In a meta.xml I'm currently looking at with no headers in the data files, the value is "0".

**Comment by thomasstjerne** [comment]
@Mesibov 
Sorry, my response was not really answering your question. 
I think GBIF has no recommendation to include or exclude headers in the tabular files. Both are completely valid.

`ignoreHeaderLines="1"` means there are headers in the file, that should be ignored when reading data
`ignoreHeaderLines="0"` means there are NO headers in the file, so data will begin at the very top of the file.

i.e. "0" equals false and "1" equals true

Hope this was a bit more clear.

**Comment by Mesibov** [comment]
@thomasstjerne, many thanks. I see now in the iHL specification: "Specifies the number lines to ignore from the beginning of the file", so "1" would mean ignore the first line.

I understand, too, how this is an option and that both structures are valid for processing DwC archives. It does seem a little strange, though, given that headers have been part of data tables for [thousands of years](https://www.datafix.com.au/BASHing/2020-08-12.html), and excluding a header makes extra work for people looking at the raw data. Only a very small proportion of the archives I look at have header-less tables.

Thanks again.

**Comment by MattBlissett** [comment]
Hi Bob, 

I think the DWC Archive specification was designed to make it as easy as possible to export data from a range of systems, as even 4000 year old best practices aren't always followed.

GBIF's software — the IPT and the downloads part of API/www.gbif.org — includes the header line for convenience, although within our software we see "Plantae" as an instance of "http://rs.tdwg.org/dwc/terms/kingdom" rather than "kingdom".

Are the problem archives from particular publishers? If so, and if they're using the same collections management software, we could suggest they tweak it. I don't think making it an official recommendation would have much affect, since most publishers use someone else's software to produce archives.

There are libraries to read Darwin Core Archives in Java, Python, R, Ruby and I think even PHP.  Perhaps one of these could easily take an archive and add the header lines if they are missing.

**Comment by Mesibov** [comment]
@MattBlissett, many thanks. Adding the header isn't hard when one is missing, it's just extra work for archive users.

The particular archive I was looking at with a headerless occurrence table is [https://dwca-exports.ala.org.au/dr10574.zip](https://dwca-exports.ala.org.au/dr10574.zip). I like to think of meta.xml as a reference table for field name explainers, but this archive's meta.xml has one unreferenced field (\<field index="180" term="taxonRankID"/>) and another 13 that don't resolve:
http://rs.ala.org.au/terms/1.0/photographer
http://rs.ala.org.au/terms/1.0/northing
http://rs.ala.org.au/terms/1.0/easting
http://rs.ala.org.au/terms/1.0/species
http://rs.ala.org.au/terms/1.0/subfamily
http://rs.ala.org.au/terms/1.0/subspecies
http://rs.ala.org.au/terms/1.0/superfamily
http://rs.ala.org.au/terms/1.0/zone
http://hiscom.chah.org.au/hispid/terms/secondaryCollectors
http://hiscom.chah.org.au/hispid/terms/identifierRole
http://data.ggbn.org/schemas/ggbn/terms/loanDate
http://data.ggbn.org/schemas/ggbn/terms/loanDestination
http://data.ggbn.org/schemas/ggbn/terms/loanIdentifier

I'm happy to see this issue closed unless someone wants to comment further.
