### ISSUE TITLE
[pygbif] Problem with polygon queries

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5180]
**[pygbif] Problem with polygon queries**

For a few weeks now, I've been unable to make queries using a polygon representing a large bouding box (in my example, France), although the queries work on smaller areas such as regions. 

The query is received without a hitch, but after a few minutes, the hits found are no longer displayed and I receive an empty file as output.

Occitanie polygon (works) :
'POLYGON((4.845533483455289 42.33275510855692, 4.845533483455289 45.04663821933639, -0.327653133697266 45.04663821933639, -0.327653133697266 42.33275510855692, 4.845533483455289 42.33275510855692)'

France polygon (doesn't work) :
'POLYGON((9.560363710038699 41.33319101116324, 9.560363710038699 51.08984197104998, -5.142238397973238 51.08984197104998, -5.142238397973238 41.33319101116324, 9.560363710038699 41.33319101116324)'

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/18c06459d73da6c188bdd37aabc29cc8:b9238818fa0a0fac1022913ff8d8711c8abdd943ae390b83e2f8d7e7363377d917236bfd0b22e5a37559b93d728f1c6664ca063e1339e052b27de3d168c7a4bc9eb27db12d608680e6541780dc20a86b814b32e9a600969446d736431ac46cc514f2dca390fdfd5ebcd152f3982c80c9f554d118062cda4aa5b3642fed826ed27ed3e167864ae23e1f54cf8a0ae9b140d5a622924d77da070d5e425fac8cbb04) - [Send email](https://www.gbif.org/api/feedback/user/mailto/18c06459d73da6c188bdd37aabc29cc8:b9238818fa0a0fac1022913ff8d8711c8abdd943ae390b83e2f8d7e7363377d917236bfd0b22e5a37559b93d728f1c6664ca063e1339e052b27de3d168c7a4bc9eb27db12d608680e6541780dc20a86b814b32e9a600969446d736431ac46cc514f2dca390fdfd5ebcd152f3982c80c9f554d118062cda4aa5b3642fed826ed27ed3e167864ae23e1f54cf8a0ae9b140d5a622924d77da070d5e425fac8cbb04)
System: Chrome 121.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/download
Window size: width 1553 - height 711
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-12T10:24:13.032Z',to:'2024-02-12T10:30:13.032Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-12T10:24:13.032Z',to:'2024-02-12T10:30:13.032Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
Changes to the API to better support event dates caused an issue with the event date predicates for downloads. The issue has been fixed and the user has been contacted.
