### ISSUE TITLE
Buenos días, he hecho una descarga por coordenadas de la especie Aedes albopictus. Mi problema es que no entiendo en qué sistema de coordenadas me están dando los resultados.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5183]
**Buenos días, he hecho una descarga por coordenadas de la especie Aedes albopictus. Mi problema es que no entiendo en qué sistema de coordenadas me están dando los resultados.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9f833bad7d232a1c5b079de51a7bfe40:103edbc282b744a201b5ce36c9381c40ebed1890f9b380f2edb0ffdc6dccde73bd5e3cc3527b31f513bfbe03b5159f9e16959a1afd2bc966c33c95def486e7f23179c8b833519a6ffea5f8360bce78904f101ba41b5d53cbaa98cd04fd074af6) - [Send email](https://www.gbif.org/api/feedback/user/mailto/9f833bad7d232a1c5b079de51a7bfe40:103edbc282b744a201b5ce36c9381c40ebed1890f9b380f2edb0ffdc6dccde73bd5e3cc3527b31f513bfbe03b5159f9e16959a1afd2bc966c33c95def486e7f23179c8b833519a6ffea5f8360bce78904f101ba41b5d53cbaa98cd04fd074af6)
System: Chrome 121.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/occurrence/charts?basis_of_record=HUMAN_OBSERVATION&country=ES&has_coordinate=true&has_geospatial_issue=false&taxon_key=1651430&geometry=POLYGON((-2.52172%2039.91682,0.869%2039.91682,0.869%2043.0569,-2.52172%2043.0569,-2.52172%2039.91682))&occurrence_status=present
Window size: width 1920 - height 963
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-13T10:43:51.673Z',to:'2024-02-13T10:49:51.673Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-13T10:43:51.673Z',to:'2024-02-13T10:49:51.673Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
The user has been contacted through helpdesk with the following reply:

> All data with coordinates published to GBIF are reprojected into WGS84 which is the projection the coordinates are in in the simple download. If you download the full archive, then the occurrence table also contain coordinates in WGS84, and the verbatim file contains the original projection in the geodeticDatum column. Please see our technical documentation for more information: https://techdocs.gbif.org/en/data-use/download-formats.
