### ISSUE TITLE
Citation not as set in IPT

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5195]
**Citation not as set in IPT**

Hi, in https://www.gbif.org/dataset/dc684783-0838-43ab-b719-80da1639fead I have published through our IPT 2.7.7. (will upgtade soon). There, I set Resource Citation - Auto-generation to "Off" and stated the citation to be: Bruun, H.H., Finderup Nielsen, T. & Lassen, C.C. (2024). Danish 19th Century Regional Floras. But after publication, on GBIF, the citation does not include Lassen, C.C. I can not figure out why, can you maybe help?

-----

Github user: @DanBIF
User: [See in registry](https://www.gbif.org/api/feedback/user/7daea0671133426c77cf8e437a9f3e6a:29982f63254cca57f87af509b59a42fad33ff3197a1b395fe195b954917d8cd172f0b4d70c7f69c9065d12c12dfaec17b11ce1ad3c28e085519ad87e9d2f2c32d88df6022e525befdf6ec4758115c7832329ab06894bd464a9d3a421b0d49d0b3ff06bd0796e3beba60e6ebd9941d53b9b4cf13bd989acf083f1b2959bb28ae7b19c2d4ba4d56b722ddb9f26a6e1fd1a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7daea0671133426c77cf8e437a9f3e6a:29982f63254cca57f87af509b59a42fad33ff3197a1b395fe195b954917d8cd172f0b4d70c7f69c9065d12c12dfaec17b11ce1ad3c28e085519ad87e9d2f2c32d88df6022e525befdf6ec4758115c7832329ab06894bd464a9d3a421b0d49d0b3ff06bd0796e3beba60e6ebd9941d53b9b4cf13bd989acf083f1b2959bb28ae7b19c2d4ba4d56b722ddb9f26a6e1fd1a)
System: Chrome 121.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/dc684783-0838-43ab-b719-80da1639fead
Window size: width 2560 - height 1279
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-20T12:47:18.548Z',to:'2024-02-20T12:53:18.548Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-20T12:47:18.548Z',to:'2024-02-20T12:53:18.548Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi @DanBIF

The Auto-generation to "Off" button is only for the citation of the source in the IPT. As far as I can see, the citation you provided is correctly displayed in the IPT: https://ipt.danbif.dk/resource?r=danish19c_regionalfloras#anchor-citation

On GBIF.org, all the citations strings are auto-generated. You can read more about why here: https://www.gbif.org/faq?question=where-does-the-dataset-citation-text-come-from-i-published-this-dataset-and.
Here is also an explanations on how the citation is autogenerated here: https://www.gbif.org/faq?question=how-is-the-dataset-citation-text-auto-generated

Let us know if you have more questions!
