### ISSUE TITLE
Some Bombus species have family Apidae as their parent taxon instead of their genus/subgenus, e.g., Bombus bimaculatus

### ISSUE THREAD

**Issue by bdagley** [gbif/portal-feedback#5198]
Species such as Bombus bimaculatus are members of genus Bombus (and within Bombus, the species is a member of subgenus Pyrobombus, but there's currently a separately documented issue where subgenera including Pyrobombus are incorrectly being categorized as genera), but bimaculatus isn't listed in the list of species for genus Bombus. Instead, the species has it's family, Apidae, as the parent taxon (https://www.gbif.org/species/1340382). I only checked this issue for this species but this probably is true of multiple Bombus species.

**Comment by bdagley** [comment]
I currently assume this may be a COL and/or GBIF issue, but please indicate in the event that iNaturalist could be involved.

**Comment by CecSve** [comment]
Hi @bdagley - I may have misunderstood your feedback, but I am not able to reproduce the issue. As I understand it, your feedback is that [_Bombus bimaculatus_](https://www.gbif.org/species/1340382) is not registered as a species within the genus [_Bombus_](https://www.gbif.org/species/1340278), correct? I can find the species under the genus and the species page also shows the genus for the species.

**Comment by bdagley** [comment]
Thanks @CecSve, you're correct.
