### ISSUE TITLE
The "Add to Calendar" button adds the event for May 16th, not 17th

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5199]
**The &quot;Add to Calendar&quot; button adds the event for May 16th, not 17th**

which date is correct?

-----

Github user: @ahahn-gbif
User: [See in registry](https://www.gbif.org/api/feedback/user/201d1b1a53a782bd3ce0654c5c74be27:5adac919dd0c80dd52c255d488f6017b44f4c32961ecb156ba038e8fbcd7e8ce61396eea2a578b5ebfe6985fec3727cb09cc6e37ce574fd3a325f5f1f65d1026b03c7b825a5dcb902b1e17693525d98c2bb0ab70a3ef874e8a95f692bab81e0dea6161f43e9204097fb1416f5ada9d6f05e3bee911a2beafabc53c79ba33122b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/201d1b1a53a782bd3ce0654c5c74be27:5adac919dd0c80dd52c255d488f6017b44f4c32961ecb156ba038e8fbcd7e8ce61396eea2a578b5ebfe6985fec3727cb09cc6e37ce574fd3a325f5f1f65d1026b03c7b825a5dcb902b1e17693525d98c2bb0ab70a3ef874e8a95f692bab81e0dea6161f43e9204097fb1416f5ada9d6f05e3bee911a2beafabc53c79ba33122b)
System: Firefox 123.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/event/42jbz2tRyrjzTF5B8pClKa/data-use-club-practical-sessions-name-matching-and-the-gbif-taxonomic-backbone
Window size: width 1403 - height 683
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-21T09:37:31.728Z',to:'2024-02-21T09:43:31.728Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-21T09:37:31.728Z',to:'2024-02-21T09:43:31.728Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
forget that - wrong year :)
