### ISSUE TITLE
show endorser status

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#520]
**show endorser status**

For an ex-participant still showing as an endorser of institutions, this is a bit confusing. Should we consider showing the status of those as "Observer" or "Former Participant", or are there better solutions? To be discussed with Communications before implementing any changes.

from http://dev.gbif.org/issues/browse/PF-1845?jql=project%20%3D%20PF%20AND%20status%20%3D%20Open

-----
fbitem-publisher2a4eddf4-6e01-491c-8e59-c7948dfb943e

System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/publisher/2a4eddf4-6e01-491c-8e59-c7948dfb943e
Window size: width 1918 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T09:21:12.524Z',mode:absolute,to:'2017-10-05T09:27:12.524Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T09:21:12.524Z',mode:absolute,to:'2017-10-05T09:27:12.524Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
More a data products/registry issue than a comms one, save for potential canvassing of @timhirsch…

Yours, I presume @ahahn-gbif?

**Comment by ahahn-gbif** [comment]
If a participant endorsed a publisher while they were still in the role, it is factually correct that the publisher was endorsed by that participant. The texts in the example say "Endorsed by: Bulgaria", and when clicking on the Node, it is clear that Bulgaria is an ex-participant. I see no reason to change anything here.

**Comment by timhirsch** [comment]
agree no need for change.
