### ISSUE TITLE
data protection

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5200]
**data protection**

-----

Github user: @slucija
User: [See in registry](https://www.gbif.org/api/feedback/user/02b39f526a29f1e65d48c20d2d5bbf77:74e2612e85fdff103818553b26e10fd65f664308a7b01be7b290448476e7cb17a4fdf0cb85abe1bfbc6bde877a207346cb83b9471e08b95b3df856fbe849f62304202833d000f86f7f79a550e8b509ca2ec6b63e73c2519e26a7ba3952ffe8c1921758deac5e0644f5e7b547d1aaf29589d0a76c1e66fcddfc94a27e724aac5db1afac85a2932fbf11a5f98c9e477f5e1cad9caed876061af23d06b8e3ce7d3f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/02b39f526a29f1e65d48c20d2d5bbf77:74e2612e85fdff103818553b26e10fd65f664308a7b01be7b290448476e7cb17a4fdf0cb85abe1bfbc6bde877a207346cb83b9471e08b95b3df856fbe849f62304202833d000f86f7f79a550e8b509ca2ec6b63e73c2519e26a7ba3952ffe8c1921758deac5e0644f5e7b547d1aaf29589d0a76c1e66fcddfc94a27e724aac5db1afac85a2932fbf11a5f98c9e477f5e1cad9caed876061af23d06b8e3ce7d3f)
System: Firefox 122.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 748
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-21T11:13:52.593Z',to:'2024-02-21T11:19:52.593Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-21T11:13:52.593Z',to:'2024-02-21T11:19:52.593Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi @slucija would it be possible to give us a bit more context for your question?

**Comment by slucija** [comment]
Dear Marie, 

it was submitted by mistake so please ignore it, my apologizes for that.


Best regards, 

lucija 

Dana 2024-02-22 11:30, Marie Grosjean je napisao(la):

> Hi @slucija [1] would it be possible to give us a bit more context for your question? 
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
> You are receiving this because you were mentioned.Message ID: ***@***.***> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/gbif/portal-feedback/issues/5200#issuecomment-1959149511", "url": "https://github.com/gbif/portal-feedback/issues/5200#issuecomment-1959149511", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
 

Links:
------
[1] https://github.com/slucija
[2]
https://github.com/gbif/portal-feedback/issues/5200#issuecomment-1959149511
[3]

**Comment by ManonGros** [comment]
Ok thanks for letting me know! I will close the issue

**Comment by slucija** [comment]
than you :) 

Bets regards, 

lucija 

Dana 2024-02-22 12:27, Marie Grosjean je napisao(la):

> Ok thanks for letting me know! I will close the issue 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you were mentioned.Message ID: ***@***.***> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/gbif/portal-feedback/issues/5200#issuecomment-1959254609", "url": "https://github.com/gbif/portal-feedback/issues/5200#issuecomment-1959254609", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
 

Links:
------
[1]
https://github.com/gbif/portal-feedback/issues/5200#issuecomment-1959254609
[2]
