### ISSUE TITLE
Media URls broken

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5201]
**Media URls broken**

The media URLs in the naturgucker dataset all seem to be broken. They refer to the .net domain, whereas now the wed site uses .de. If these were updated then there would be images for this dataset available in GBIF.

-----

Github user: @rdmpage
User: [See in registry](https://www.gbif.org/api/feedback/user/9f93877fbeb9724799cdc67a977e3743:d902255f6650c55c369e0ce8de086a3509da00a6db4eec935d810a31e10e45b00a337ff46ca84d9f763a3c0124087a595d64beecc79f3af8bdaf223f65ce640327c95b4c548e4a5edad0d13dd4c77a7b92c4d6e24b3e82a8e42894f4ed6821574f3224bb5006351a24e4292df3fc9004fb107189b3e5b4ec13bb9692a631f4ff) - [Send email](https://www.gbif.org/api/feedback/user/mailto/9f93877fbeb9724799cdc67a977e3743:d902255f6650c55c369e0ce8de086a3509da00a6db4eec935d810a31e10e45b00a337ff46ca84d9f763a3c0124087a595d64beecc79f3af8bdaf223f65ce640327c95b4c548e4a5edad0d13dd4c77a7b92c4d6e24b3e82a8e42894f4ed6821574f3224bb5006351a24e4292df3fc9004fb107189b3e5b4ec13bb9692a631f4ff)
System: Safari 17.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/1580079353
Window size: width 1233 - height 1117
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-21T16:56:01.018Z',to:'2024-02-21T17:02:01.018Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-21T16:56:01.018Z',to:'2024-02-21T17:02:01.018Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 6ac3f774-d9fb-4796-b3e9-92bf6c81c084
publishingOrgKey: bb646dff-a905-4403-a49b-6d378c2cf0d9

Node handles: @jholetschek

**Comment by jholetschek** [comment]
Not sure I understand. The link provided is https://nabu-naturgucker.de/?sprache=en&bild=267771781. That's a different domain than the BioCASe data source, but is that a problem?

But I can see that there is no link to the actual image - the ProductURI refers to an HTML page. I'll get in contact with Naturgucker.

Jörg

**Comment by MortenHofft** [comment]
The media item has a reference to `https://naturgucker.net/?sprache=en&bild=267771781` which is a dead link. Correcting that to `.de` will make it work.

But the reason the image isn't showing is because there is no identifier for the image (the reference is the broken link to the html page)

https://rs.gbif.org/extension/gbif/1.0/multimedia.xml

**Comment by jholetschek** [comment]
Apparently that has already been changed to https://nabu-naturgucker.de/?sprache=en&bild=267771781 in the BioCASe source:
`
<abcd:ProductURI>
https://nabu-naturgucker.de/?sprache=en&bild=267771781
</abcd:ProductURI>
`

But the abcd:FileURI (=dwc:identifier) is still missing. I've contacted the curator.

**Comment by jholetschek** [comment]
FileURI ist now mapped correctly.

There is still the issue that the providers restart their IIS nightly, which kill the harvesting at 3.10. I'm trying to persuade them to use archive-based harvesting, let's see if that's successful.

**Comment by jholetschek** [comment]
The dataset has been successfully crawled (from the web service, no reply from the provider about archives yet).
Seems the thumbnails still need to be created, but the image link already shows up in the detail page: https://www.gbif.org/occurrence/1580079353

**Comment by MattBlissett** [comment]
Hi,

At the bottom of the page in the "Multimedia" table there's both the `references` value and the `identifier` value, which is the image itself. That's come from the ABCD:

```
        <MultiMediaObjects>
                <MultiMediaObject>
                        <FileURI>http://live.staticflickr.com/4238/35730818091_efc4bb0d19_b.jpg</FileURI>
                        <ProductURI>https://nabu-naturgucker.de/?sprache=en&amp;bild=267771781</ProductURI>
                        <Format>text/html</Format>
                </MultiMediaObject>
        </MultiMediaObjects>
```

I think it is probably the `text/html` in the format preventing display of the image. It should be `image/jpeg`.

**Comment by jholetschek** [comment]
I've changed that and triggered an update of the ABCD archive. That should be finished tomorrow - you can change to archives then and re-harvest the dataset.

**Comment by jholetschek** [comment]
I've created an ABCD archive. Could you please do a metadata update, so that the archive will be harvested?

**Comment by MattBlissett** [comment]
There was an error in parsing the XML:

```
Caused by: org.xml.sax.SAXParseException: An invalid XML character (Unicode: 0x10) was found in the element content of the document.
```

It is in this FileURI of unit 565890055:

```
http://live.staticflickr.com/31^P7/5836314465_2acd585925_b.jpg
```
(Emacs is showing the control character as `^P`.)

I found this with `for i in response.*.xml; do xmllint $i > /dev/null; done`.

**Comment by jholetschek** [comment]
Hi Matt,

I've forwarded that to the curator, let's hope they remove the character soon.
But it's a bit strange - it's the same data as in the web service, which was successfully harvested at the beginning of the week. Can you tell why? Does archive-based harvesting fail completely if one of the documents is invalid?

Cheers,
Jörg

**Comment by MattBlissett** [comment]
I don't see that character in the XML files we downloaded a few days ago, so something must be removing them, but Firefox gives me an XML encoding error if I look at `https://www.naturgucker.de/biocase/pywrapper.cgi?dsa=biocase&query=%3C%3Fxml+version%3D%271.0%27+encoding%3D%27UTF-8%27%3F%3E%0D%0A%3Crequest+xmlns%3D%27http%3A%2F%2Fwww.biocase.org%2Fschemas%2Fprotocol%2F1.3%27%3E%0D%0A++%3Cheader%3E%3Ctype%3Esearch%3C%2Ftype%3E%3C%2Fheader%3E%0D%0A++%3Csearch%3E%0D%0A++++%3CrequestFormat%3Ehttp%3A%2F%2Fwww.tdwg.org%2Fschemas%2Fabcd%2F2.06%3C%2FrequestFormat%3E%0D%0A++++%3CresponseFormat+start%3D%270%27+limit%3D%2710%27%3Ehttp%3A%2F%2Fwww.tdwg.org%2Fschemas%2Fabcd%2F2.06%3C%2FresponseFormat%3E%0D%0A++++++%3Cfilter%3E%0D%0A%3Clike+path%3D%27%2FDataSets%2FDataSet%2FUnits%2FUnit%2FUnitID%27%3E565890055%3C%2Flike%3E%0D%0A++++++%3C%2Ffilter%3E%0D%0A++++++%3Ccount%3Efalse%3C%2Fcount%3E%0D%0A++%3C%2Fsearch%3E%0D%0A%3C%2Frequest%3E`

The archive-based harvesting does fail completely with an invalid document. It updates entire datasets, and we wouldn't want to updated a dataset but be missing some occurrences.

**Comment by MortenHofft** [comment]
Images work now.
