### ISSUE TITLE
Agent role not displaying correctly on the web interface

### ISSUE THREAD

**Issue by spalp** [gbif/portal-feedback#5202]
The role of the Reviewer looks like it has not been processed on the page of the dataset:
https://www.gbif.org/dataset/e60d0a8d-81b7-40d7-95a1-7ab7b95f5100#contacts

![image](https://github.com/gbif/ipt/assets/11872373/12ef3ad6-8815-402a-91f7-72b175d61b7a)

**Comment by MortenHofft** [comment]
Thanks - the translation for the new role was missing. It is fixed and in production
