### ISSUE TITLE
Coordinates not in download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5203]
**Coordinates not in download**

I did a query for Odocoileus virginianus occurrences within a polygon that was roughly the U.S. State of Kentucky. I opted to only get records that had coordinates, and when looking through the table of data, each of the 2,874 results had coordinates. However when I downloaded the table, only 5 had coordinates. 

I do not know if there is a bug on my end, or with the system but any help would be appreciated! I would like the information to help with a research project proposal.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6b94db8d7408aff753ae4b127acd8d86:bd984a5a4cd69bcf29abb10cffdcba15e8d12f2633cf9ce991f6e3874c8fa5f0414bd08f6ffc664afe54482f8973de0e4f6c6d557f5303d23f222f9a2a0582126e2166d5fd96140f816a8fabaedebd3b5968632e3a7627685d7fce0a5a03f6d5) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6b94db8d7408aff753ae4b127acd8d86:bd984a5a4cd69bcf29abb10cffdcba15e8d12f2633cf9ce991f6e3874c8fa5f0414bd08f6ffc664afe54482f8973de0e4f6c6d557f5303d23f222f9a2a0582126e2166d5fd96140f816a8fabaedebd3b5968632e3a7627685d7fce0a5a03f6d5)
System: Chrome 121.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download?has_coordinate=true&has_geospatial_issue=false&taxon_key=2440965&geometry=POLYGON((-89.68038%2036.36195,-80.76967%2036.39209,-80.65735%2037.29096,-82.30471%2038.70705,-83.98951%2039.54929,-85.52455%2039.28899,-86.16102%2038.44362,-87.84582%2038.26746,-89.45574%2037.6179,-89.71782%2036.90275,-89.68038%2036.36195))
Window size: width 2560 - height 1313
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-22T15:21:57.993Z',to:'2024-02-22T15:27:57.993Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-22T15:21:57.993Z',to:'2024-02-22T15:27:57.993Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
As far as I can see, the coordinates are in the download files that the user generated (see for example: https://www.gbif.org/occurrence/download/0011626-240216155721649), maybe the issue is how they open the file. I will reach out to ask.
