### ISSUE TITLE
How do you find if a plant is edible?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5205]
**How do you find if a plant is edible?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2c9172da55ef4b3fa14a775eb67a2c8b:0edd2274a38002edc5a34b0ebc6c4d6010b3d9af68f8968843c74c362e619b95476862ef75adaf12d279cd4eaddc14be28f0951b201d51eabbcaba2d42ddc56ddd5bbf6e217cae63dd5e36724adf9dfee0766f0a484ffc87038cf37234cfd307) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2c9172da55ef4b3fa14a775eb67a2c8b:0edd2274a38002edc5a34b0ebc6c4d6010b3d9af68f8968843c74c362e619b95476862ef75adaf12d279cd4eaddc14be28f0951b201d51eabbcaba2d42ddc56ddd5bbf6e217cae63dd5e36724adf9dfee0766f0a484ffc87038cf37234cfd307)
System: Safari 17.3.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/system-health
Window size: width 1112 - height 731
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-22T21:06:05.020Z',to:'2024-02-22T21:12:05.020Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-22T21:06:05.020Z',to:'2024-02-22T21:12:05.020Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
We don’t have an easy way to filter for edible species in our system.

As you might know, GBIF is a data aggregator. The data avialable on our platform comes from many different sources: Museums, citizen science intiatives, research teams, etc.
The data providers package the data that they share on GBIF as dataset, which have associated title and descriptons. Some of these datasets are themed and could be relevant for you. For example, here is an occurrence dataset of specimens of edible fruits in Cameroon: https://doi.org/10.15468/zmcpyo

You can try to look for specific datasets by key words in our system. Here is the search result for “edible”: https://www.gbif.org/dataset/search?q=edible. Perhaps some data will be relevant for you in those dataset.

> contacted by email
