### ISSUE TITLE
como selecionar a una especie en un pais

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5209]
**como selecionar a una especie en un pais**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/f7d844b30ee03e511c2b504192c020bc:7fab23a8cf1306651c3801dbb649c72f88e391aaf466f46d81698fdc9f0310e53979dc3ca75665267d800752a421d32d8817af79853d4b67c8b2ade031c5eff93ed27e7c97cc5a9052a6551498eaf8ea14b975763a50a9f458d33f9fb910125beb3f78c9e5f21304716f60fcccfbcca2) - [Send email](https://www.gbif.org/api/feedback/user/mailto/f7d844b30ee03e511c2b504192c020bc:7fab23a8cf1306651c3801dbb649c72f88e391aaf466f46d81698fdc9f0310e53979dc3ca75665267d800752a421d32d8817af79853d4b67c8b2ade031c5eff93ed27e7c97cc5a9052a6551498eaf8ea14b975763a50a9f458d33f9fb910125beb3f78c9e5f21304716f60fcccfbcca2)
System: Chrome 122.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/es/species/8909809
Window size: width 1318 - height 620
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-28T15:07:27.277Z',to:'2024-02-28T15:13:27.277Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-02-28T15:07:27.277Z',to:'2024-02-28T15:13:27.277Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Here are some instructions:
1.	Go to our occurrence search interface: https://www.gbif.org/es/occurrence/search?occurrence_status=present&q=
2.	Use the “Nombre cientifíco” to select one or several scientific names
3.	Use the “País o área” filter to select one or several countries
See an example here: https://www.gbif.org/es/occurrence/search?country=ES&country=FR&taxon_key=8909809&taxon_key=9373638
Then click on the DESCARGAR tab and choose your download format.

Note that we have a [Data Use Club](https://www.gbif.org/es/data-use-club) recorded webinar on how to use GBIF.org [here](https://www.gbif.org/es/composition/4Xm5cVB4y9n7U1GlUtKx8Q/data-use-club-practical-session-1-recording-and-resources).

> Replied by email
