### ISSUE TITLE
Occurrences without license from checklist datasets: ensure licenses are applied

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#521]
**Occurrences without license from checklist datasets: ensure licenses are applied**

In the consultation and application of machine-readable licenses (2016), checklist datasets where explicitly excluded. This results, however, in some cases where occurrences served through checklist datasets are indexed with and unspecified license. 

Resolve these cases by either applying one of the available licenses, or deindex the occurrences.

-----
fbitem-367fbea4afd888a3d8e33ed9130e11ce8143be62
User provided contact info: ahahn-gbif
System: Firefox 56.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/datasets?license=UNSPECIFIED
Window size: width 1224 - height 566
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T09:25:01.328Z',mode:absolute,to:'2017-10-05T09:31:01.328Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T09:25:01.328Z',mode:absolute,to:'2017-10-05T09:31:01.328Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
Email sent to the administrators of the two remaining datasets (copy helpdesk, 5.10.17)

**Comment by ManonGros** [comment]
The other (more recent) datasets with unsupported license have been contacted as well, see #1531
