### ISSUE TITLE
Does GBIF offer a DOI badge?

### ISSUE THREAD

**Issue by ymgan** [gbif/portal-feedback#5216]
Does GBIF offer a DOI badge that users can embed in Markdown, similar to the one provided by Zenodo? Please see example below:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4942307.svg)](https://doi.org/10.5281/zenodo.4942307)

It's a question from our data provider who would like to have a badge like this on their GitHub repo. Right now he is creating his own badge using https://shields.io/ just wondering if there is anything more built-in? 

Thanks a lot!!

**Comment by ManonGros** [comment]
Hi Ming, we don't have such badges and publishers are welcome to create their own using third party systems.
