### ISSUE TITLE
Occ Search modified before is actually before or equals

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#522]
**Occ Search modified before is actually before or equals**

If you search occurrences modified in GBIF before 2015-01 you also get all records modified in january:

https://www.gbif.org/occurrence/search?last_interpreted=*,2017-01&advanced=1

A better name than before. @dnoesgaard what is a better name then simply `before` 

copied from http://dev.gbif.org/issues/browse/PF-1889?jql=project%20%3D%20PF%20AND%20status%20%3D%20Open

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: mortenhofft
System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/occurrence/search?last_interpreted=*,2017-01&advanced=1
Window size: width 1918 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T09:48:43.623Z',mode:absolute,to:'2017-10-05T09:54:43.623Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T09:48:43.623Z',mode:absolute,to:'2017-10-05T09:54:43.623Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
I guess the same applies to ?event_date= ... ?

How about adding "beginning of" or "end of" before the month field accordingly?

After start of ... 
Before end of ...
Between start of ... and end of ...
