### ISSUE TITLE
species name apparently not matched properly

### ISSUE THREAD

**Issue by kpmcfarland** [gbif/portal-feedback#5223]
_Poanes hobomok_ T.Harris, 1862 is now _Lon hobomok_. In our checklist (see https://www.gbif.org/dataset/73eb16f0-4b06-4347-8069-459bc2d96ddb) we have it as such with the syn. being _P. hobomok_. This apparently caused GBIF to do this: https://www.gbif.org/species/210595535, which created _Lon spec._ We would suggest that _P. hobomok_ becomes a syn. and _Lon hobomok_ is the accepted name in the backbone, or at least make _Lon hobomok_ something other then turning it into Lon spec.

**Comment by CecSve** [comment]
Thank you for reporting the issue. For some reason, the [checklist entry for the species](https://www.gbif.org/species/210595535) is not mapped to the backbone although the backbone does have the [accepted name](https://www.gbif.org/species/11834445) and [the synonym](https://www.gbif.org/species/1946611).

@thomasstjerne can you explain why this record is turned into [_Lon spec_. T. Harris, 1862](https://www.gbif.org/species/210595535) instead of being mapped to the [backbone _Lon hobomok_ (Harris, 1862)](https://www.gbif.org/species/11834445)?

**Comment by kpmcfarland** [comment]
I bet it has to do with the author name. GBIF backbone is Harris, 1862 while the authority in North America has it as T. Harris 1862, see https://www.butterfliesofamerica.com/L/t/Lon_hobomok_a.htm. I am going to change my checklist to match GBIF and I bet it works... stay tuned.

**Comment by CecSve** [comment]
Yes, I suspected the same but cannot tell for sure. I hope it works!

**Comment by kpmcfarland** [comment]
Sadly, it does not seem to have worked. See https://www.gbif.org/species/210595535/verbatim. So I am not sure why it is not matching this correctly.

**Comment by MattBlissett** [comment]
I think it is the capital letter on the species epithet, `Lon Hobomok`.

Cecilie, if you wish to see the API call:

Lon Hobomok: https://api.gbif.org/v1/species/match2?authorship=(Harris%2C%201862)&rank=SPECIES&specificEpithet=hobomok&kingdom=Animalia&phylum=Arthropoda&order=Lepidoptera&class=Insecta&family=Hesperiidae&genus=Lon&verbose=true&name=Lon%20Hobomok%20(Harris,%201862)

Lon hobomok: https://api.gbif.org/v1/species/match2?authorship=(Harris%2C%201862)&rank=SPECIES&specificEpithet=hobomok&kingdom=Animalia&phylum=Arthropoda&order=Lepidoptera&class=Insecta&family=Hesperiidae&genus=Lon&verbose=true&name=Lon%20hobomok%20(Harris,%201862)

**Comment by kpmcfarland** [comment]
Here's the stange thing, I saw that too, but my data frame does NOT have a that as a cap letter as far as I can tell. I even just downloaded it off my IPT and the species name is not in caps.

**Comment by kpmcfarland** [comment]
dang it. I missed that I guess. Let me correct that.

**Comment by kpmcfarland** [comment]
Okay, my change has traveled through the system and it is now fixed! I thank you for peering into this here and I also am sorry it was a dumb typo mistake that cost you time!

**Comment by CecSve** [comment]
No worries! Just glad it could be sorted out so quickly.
