### ISSUE TITLE
For occurrences published via a Symbiota installation, make feedback link go to specimen record so users can use comment feature

### ISSUE THREAD

**Issue by themerekat** [gbif/portal-feedback#5226]
For occurrences published via a Symbiota installation (we can help identify these), for example those in this dataset: https://www.gbif.org/dataset/f56df26e-73f5-4d37-bfed-3d46c0834e82

when a user wants to provide feedback in GBIF, rather than telling the user to email the dataset provider (see screenshot)
![image](https://github.com/gbif/portal-feedback/assets/16688784/d02f326c-cf3f-4cc4-a463-3ffbff307f4c)

could we have a link to the individual specimen page in the associated Symbiota portal, similarly to what is done for iNaturalist?
![image](https://github.com/gbif/portal-feedback/assets/16688784/73563e4c-5247-44a9-bae4-f1f206b05a6c)

The link should just go to the same link provided in References.
![image](https://github.com/gbif/portal-feedback/assets/16688784/3770cfbf-06d5-44e6-bce4-3f902d02b535)

For example, for this occurrence: https://www.gbif.org/occurrence/4040320514
it should be https://cch2.org/portal/collections/individual/index.php?occid=5764475
(there is a "comments" tab)

**Comment by MortenHofft** [comment]
If there is a simple way to identify the records (e.g. a single publisher or dataset) then yes. What is the logic?

Symbiota is already in there as a special rule (based on an old request probably - though I cannot see any reference to an issue). E.g. https://www.gbif.org/occurrence/1993812028

The logic is anything from installation https://api.gbif.org/v1/installation/2c733a9d-363d-4d66-9aef-3e0f7bc44bec
But the record you link to isn't from that installation

**Comment by themerekat** [comment]
@MortenHofft it would apply to any of the installations associated with the Symbiota Support Hub: https://www.gbif.org/publisher/96710dc8-fecb-440d-ae3e-c34ae8a9616f

**Comment by MortenHofft** [comment]
So this was very confusing to me. But after discussion with @ahahn-gbif this is what I understand:

[This record](https://www.gbif.org/occurrence/1993812028), that is currently categorized as Symbiota because it is from installation [2c733a9d-363d-4d66-9aef-3e0f7bc44bec](https://api.gbif.org/v1/installation/2c733a9d-363d-4d66-9aef-3e0f7bc44bec) will continue to do so. That rule will continue to be applied. And that will also say Symbiota despite not being part of the publishing @themerekat refers to.

And you have now provided an EXTRA rule (not a replacement) that says: any occurrence with `hostingOrgKey: 96710dc8-fecb-440d-ae3e-c34ae8a9616f` is ALSO Symbiota and should link to the value in the reference field. That new rule does NOT include the installation [Symbiota Collections of Arthropods Network (SCAN)](https://api.gbif.org/v1/installation/2c733a9d-363d-4d66-9aef-3e0f7bc44bec) despite it being called Symbiota (that was the part that confused me).

**Comment by MortenHofft** [comment]
This is now in production. Example https://www.gbif.org/occurrence/4534015382

**Comment by MattBlissett** [comment]
We have an InstallationType of "SYMBIOTA_INSTALLATION", should it apply to all of them?

**Comment by themerekat** [comment]
@MattBlissett , yes, I think it would apply to all! All Symbiota portals have a commenting feature.

**Comment by themerekat** [comment]
@MortenHofft , you are amazing!! We're very excited to see this in production. Thanks for your time.

**Comment by themerekat** [comment]
> So this was very confusing to me. But after discussion with @ahahn-gbif this is what I understand:
> 
> [This record](https://www.gbif.org/occurrence/1993812028), that is currently categorized as Symbiota because it is from installation [2c733a9d-363d-4d66-9aef-3e0f7bc44bec](https://api.gbif.org/v1/installation/2c733a9d-363d-4d66-9aef-3e0f7bc44bec) will continue to do so. That rule will continue to be applied. And that will also say Symbiota despite not being part of the publishing @themerekat refers to.
> 
> And you have now provided an EXTRA rule (not a replacement) that says: any occurrence with `hostingOrgKey: 96710dc8-fecb-440d-ae3e-c34ae8a9616f` is ALSO Symbiota and should link to the value in the reference field. That new rule does NOT include the installation [Symbiota Collections of Arthropods Network (SCAN)](https://api.gbif.org/v1/installation/2c733a9d-363d-4d66-9aef-3e0f7bc44bec) despite it being called Symbiota (that was the part that confused me).

AH, yes, sorry for that confusion. It's possible there will be other Symbiota installations that aren't stewarded by the Symbiota Support Hub. I think SCAN is the only one I know of, right now, but as an open source software, more could arise.

**Comment by MattBlissett** [comment]
I see 5 others:

select distinct i.key, i.title from installation i, dataset d where i.type = 'SYMBIOTA_INSTALLATION' and i.deleted is null and d.installation_key = i.key and d.deleted is null and i.organization_key != '96710dc8-fecb-440d-ae3e-c34ae8a9616f' order by 2;
```
                 key                  │                           title
──────────────────────────────────────┼────────────────────────────────────────────────────────────
 998fa743-e3d2-41bd-8cd3-754e22581224 │ Bell Atlas
 dd8ffb07-5f02-4e70-b4cd-dbba0dfae83e │ MyCoPortal
 da120392-50df-44d5-b523-aa0610a2b306 │ OregonFlora
 2c733a9d-363d-4d66-9aef-3e0f7bc44bec │ Symbiota Collections of Arthropods Network (SCAN)
 4ec55ebe-9f92-45ec-b076-dd45f61003ab │ UC Santa Barbara Collection Network
 20d6990b-596f-4f2a-af26-ce27221fc689 │ University of Colorado Museum of Natural History Herbarium
```
