### ISSUE TITLE
Original stated Longitude, -176.6333,  is correct.  The locality is in the Lau Basin, southeast of Fiji.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5228]
**Original stated Longitude, -176.6333, is correct. The locality is in the Lau Basin, southeast of Fiji.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7aa8dbbe23464e3d9106c5c9bbee85c0:f5d423227bf87148d59ad30be745f19bc42f9aed7c0360648761988234a440c991f614be24d12f91b198ca332759fd0e02e3391e4249c19b891bcf81d8564d12a4c213db47c601036f2222e02a55641aae76383299d3b10a59b240a04cd3ace76bcea81d024019d4dcea68e2b26b310d3d4b2dbabf8670aa34b5b6952b5f96e6) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7aa8dbbe23464e3d9106c5c9bbee85c0:f5d423227bf87148d59ad30be745f19bc42f9aed7c0360648761988234a440c991f614be24d12f91b198ca332759fd0e02e3391e4249c19b891bcf81d8564d12a4c213db47c601036f2222e02a55641aae76383299d3b10a59b240a04cd3ace76bcea81d024019d4dcea68e2b26b310d3d4b2dbabf8670aa34b5b6952b5f96e6)
System: Chrome 122.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/2594408758
Window size: width 1293 - height 691
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-07T00:42:53.171Z',to:'2024-03-07T00:48:53.171Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-07T00:42:53.171Z',to:'2024-03-07T00:48:53.171Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: ec0ad39f-3370-4d51-a663-cb27abd2a6bb
publishingOrgKey: 493fe050-055d-11d8-b84f-b8a03c50a862

Node handles: @sformel-usgs

**Comment by sformel-usgs** [comment]
I suspect this might be an anti-meridian bug in GBIF in the flag inerpreter. This illustrates the problem:

![image](https://github.com/gbif/portal-feedback/assets/118295402/bfc7371b-0c96-441e-87c0-a2f0151c2704)

@gbif-portal who should investigate? @vijaybarve who should we talk to at the museum if follow up is needed?

**Comment by MattBlissett** [comment]
![image](https://github.com/gbif/portal-feedback/assets/583320/36173ceb-b8ef-4734-89f4-26f13e03bb3d)

The occurrence says Fiji, and is south-east of the Viti Levu group of Fijian islands, but it is well within the EEZ of Tonga. Changing the country to Tonga is the best fix, assuming the coordinates are correct.

**Comment by MattBlissett** [comment]
However, these points near the meridian or antimeridian are a bit risky for having their longitude swapped: https://github.com/gbif/pipelines/issues/479

**Comment by sformel-usgs** [comment]
Thanks @MattBlissett for the feedback, both excellent points.  I'll write to the dataset POCs and see if they can weigh in on this.

**Comment by wlmertz** [comment]
It's likely the expedition originated in Fiji, and therefore all locality data was described in reference to Fiji as the nearest country.  Changing the country to Tonga may be an adequate solution in this case, but often collection managers prefer recording original/historical data.  To clarify, Longitude, -176.6333 is the correct coordinate for the Lau Basin, which stretches roughly north to south through Tonga.

**Comment by wlmertz** [comment]
In addition to the riskiness of swapping longitude near the antimeridian, we also see rare cases of swapping latitude near the equator. This is normally an issue regarding marine animals.  Localities are often described as "off the coast of" or "north/south/east/west of", and GBIF will return the latitude or longitude back across the antimeridian or equator despite the fact that the description places the locality on the other side of the antimeridian or equator.   On the other hand, it's often helpful to review these flagged localities.

**Comment by sformel-usgs** [comment]
This, and other similar occurrences, have been updated to correctly represent their locality. @ManonGros or @CecSve , I believe this issue can be closed.
