### ISSUE TITLE
why is an organism unranked

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5229]
**why is an organism unranked**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/aee59df6c9129bedcd4ec5f694d2ef9b:100d5c25eedecc7842203ab211618f8e7945c564f642669394712a67e42a273c946e40e6512d686fe52c742da8cadfda5d9b2ef51d47f523b51cda365f0367f5bcd91ad07308e7ba9d27fbbfe6db5b6a137dc6bab1041d5a7537b41ba5b05d71) - [Send email](https://www.gbif.org/api/feedback/user/mailto/aee59df6c9129bedcd4ec5f694d2ef9b:100d5c25eedecc7842203ab211618f8e7945c564f642669394712a67e42a273c946e40e6512d686fe52c742da8cadfda5d9b2ef51d47f523b51cda365f0367f5bcd91ad07308e7ba9d27fbbfe6db5b6a137dc6bab1041d5a7537b41ba5b05d71)
System: Firefox 123.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/species/10284627
Window size: width 1850 - height 1115
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-07T05:30:11.945Z',to:'2024-03-07T05:36:11.945Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-07T05:30:11.945Z',to:'2024-03-07T05:36:11.945Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

The page that you refer to is a taxon page from the GBIF Backbone taxonomy.
As you might already know, GBIF is a data aggregator. The data available on our platform comes from many different sources: museums, citizen science initatives, research teams, etc. Most data providers share occurrences on GBIF (the observation or collection of a given specimen at a specific time an place). Those occurrences are associated with scientific names.

We build a backbone taxonomy to organize the scientific names provided in the data. The GBIF backbone itself is build from many different sources (you can read more about how it is made [here](https://data-blog.gbif.org/post/gbif-backbone-taxonomy/)). This page: https://www.gbif.org/species/10284627 corresponds to one of the [International Barcode of Life project (iBOL) Barcode Index Numbers (BINs)](https://www.gbif.org/dataset/4cec8fef-f129-4966-89b7-4f8439aba058) (unique identifiers assigned to groups of DNA barcode sequences that are thought to correspond to individual species).
Those BINs aren’t classical lineean names themsleves but are associated with such names (in this case Spodoptera exigua (Hübner, 1808)). They don’t really have a defined taxon rank, this is why they are unranked.
