### ISSUE TITLE
Species list with classification

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5230]
**Species list with classification**

Hi I would like to download a list of verified records of fauna species including scientific name, common name (if available), class, and IUCN classification ranking. I s this possible? The list I have received moslt contains scientific names but other tabs are mostly blank includig Kingdom whicm make it difficult to know what species is relevant and which species is of conservation concern for a site. Thank you for your assistance.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/da04004947e521c86d0ea5ba88f0cd1f:498d0ee070c855ff8306939c12360240b650f29ff0b2ceae16c09ad4796c6a51e28a442b747f8f02da7350074f04c85f42999f123516470b27acc77dceb9c4b0776512ded59af9bb2a7eb9921667160402d2408a5836f34626a7c69a91a19864) - [Send email](https://www.gbif.org/api/feedback/user/mailto/da04004947e521c86d0ea5ba88f0cd1f:498d0ee070c855ff8306939c12360240b650f29ff0b2ceae16c09ad4796c6a51e28a442b747f8f02da7350074f04c85f42999f123516470b27acc77dceb9c4b0776512ded59af9bb2a7eb9921667160402d2408a5836f34626a7c69a91a19864)
System: Chrome 122.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
Window size: width 1920 - height 879
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-07T09:16:00.056Z',to:'2024-03-07T09:22:00.056Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-07T09:16:00.056Z',to:'2024-03-07T09:22:00.056Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

Several types of data are available on GBIF.
The most common type of data you will see are occurrences (the observation or collection of a specimen at a given place and time). This is what you can download and access from [this interface.](https://www.gbif.org/occurrence/search?occurrence_status=present&q=) Usually occurrences are associated with a scientific name which is then matched to the GBIF Backbone taxonomy (you can read more about it [here](https://data-blog.gbif.org/post/gbif-backbone-taxonomy/)). Once a name is matched to the backbone taxonomy, we can infer its higher taxonomy and IUCN Global threat status.
You can also access information about species (taxonomy, literature reference, vernacular names, etc.) independently of the occurrences.
* Some information can be access via [this interface](https://www.gbif.org/species/search?q=). 
* You can also use the GBIF Species API, find our more here: https://data-blog.gbif.org/post/gbif-species-api/ with a side note on vernacular names: https://discourse.gbif.org/t/api-offset-limit/4136/3
* You can also explore and download the data from https://www.checklistbank.org/
* You are also welcome to directly download the IUCN Redlist of Globally threatened species checklist here: https://www.gbif.org/dataset/19491596-35ae-4a91-9a98-85cf505f1bd3
* If this is an interesting topic for you, consider joining our next [Data Use Club](https://www.gbif.org/data-use-club) webinar on accessing species information, you can sign up [here](https://www.gbif.org/event/1cmaX8vGCVby0IBb11fvKJ/data-use-club-practical-sessions-accessing-and-downloading-species-information).

From the occurrence download interface, you can choose the SPECIES LIST format. Which will contain aggregated occurrence data per species. The higher taxonomy and IUCN threat status provided in this download is inferred from the GBIF backbone taxonomy.
As far as I can see, the latest download that you created (https://www.gbif.org/occurrence/download/0028754-240229165702484) includes  the higher taxonomy for each row (including values in the kingdom fields). The IUCN Global Threat status isn’t necessarily available for all the taxa though.
