### ISSUE TITLE
OBIS manual link on standards page is outdated

### ISSUE THREAD

**Issue by ymgan** [gbif/portal-feedback#5235]
Hi, 

Came across this page: https://www.gbif.org/standards

> The Darwin Core Standard (DwC) offers a stable, straightforward and flexible framework for compiling biodiversity data from varied and variable sources. The majority of the datasets shared through GBIF.org are published using the Darwin Core Archive format (DwC-A).

    [What is Darwin Core, and why does it matter?](https://www.gbif.org/darwin-core)
    [Introduction to sampling-event data](https://www.gbif.org/sampling-event-data)
    [iOBIS Darwin Core manual](http://www.iobis.org/manual/darwincore/)
    [Darwin Core terms](https://gcube.wiki.gcube-system.org/gcube/Darwin_Core_Terms) (via Gcube Wiki)

Can you please update the link for OBIS manual to https://manual.obis.org/darwin_core.html ? Thank you so much!!

**Comment by dnoesgaard** [comment]
Thanks! I've updated the link now.
