### ISSUE TITLE
I Downloaded an Darwin Core Archive but it doesnt contain an .CSV file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5237]
**I Downloaded an Darwin Core Archive but it doesnt contain an .CSV file**

Hello I just downloaded a Darwin Core Archive of Ctenomys, here is the link that I recived in my mail: https://api.gbif.org/v1/occurrence/download/request/0073709-240229165702484.zip
Maybe I have to generate the CSV file by myself, but im not exactly sure how does it works

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/974bac78b776cceba823f310b08a2a8a:a6fc9ddf44f21f51523ccfdc015e3fb8bec2a85cacb580960d4dd9b556eb4a2205f9c60c1e08e4ad2ac708ff5bfbd98fa9b23a469f544d2f1c5cda4b298677799c8ab7d0bc267c3af0698bef9a04d3b40049a1120f906dfebff4e482eeb2c351e31963ff4db5fe7f6d5177b3bec0cb26c602bd024cb8beb70cd63da43bd1ca036dfe195e7009f89735a8790e592fbeea) - [Send email](https://www.gbif.org/api/feedback/user/mailto/974bac78b776cceba823f310b08a2a8a:a6fc9ddf44f21f51523ccfdc015e3fb8bec2a85cacb580960d4dd9b556eb4a2205f9c60c1e08e4ad2ac708ff5bfbd98fa9b23a469f544d2f1c5cda4b298677799c8ab7d0bc267c3af0698bef9a04d3b40049a1120f906dfebff4e482eeb2c351e31963ff4db5fe7f6d5177b3bec0cb26c602bd024cb8beb70cd63da43bd1ca036dfe195e7009f89735a8790e592fbeea)
System: Chrome 122.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download?taxon_key=2439605&geometry=POLYGON((-58.84191%20-27.94331,-61.72743%20-27.95523,-64.95873%20-28.78989,-65.68608%20-30.1611,-65.80531%20-31.87811,-64.92296%20-32.51006,-65.13759%20-33.18971,-65.07797%20-34.45361,-63.39116%20-34.43897,-61.72442%20-34.36952,-60.16186%20-33.27573,-60.78688%20-32.70279,-60.45292%20-31.84005,-60.3702%20-31.62635,-59.58892%20-30.72354,-59.56291%20-29.98851,-59.67573%20-29.80336,-59.19397%20-29.01191,-58.84191%20-27.94331))
Window size: width 1536 - height 695
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-12T15:55:13.656Z',to:'2024-03-12T16:01:13.656Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-12T15:55:13.656Z',to:'2024-03-12T16:01:13.656Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

The occurrence.txt file and the verbatim.txt file are formatted as tab-separated CSV file. You can always change the extension of the files from .txt to .csv or .tsv by changing the file name.
[Here](https://www.gbif.org/faq?question=what-is-inside-a-gbif-download-zip-file) is a Q&A explaining the detail of the files you will find in the Darwin Core Archive. [Here](https://www.gbif.org/faq?question=opening-gbif-csv-in-excel) is how to open a tab-separated CSV file in excel.
