### ISSUE TITLE
need to find API key

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5246]
**need to find API key**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8cca4a95228626629af993ae2c699bed:8181b6581fa8a91ff72aa7bc2a32a93ffe02154f60f0579ef7d46b85227cb667a3245e377dc0804588b0b6f518bad09e589e286a317cd04096677250af612fd5147c85d3c9b31a9a00987446f07ef1bd6460f4cdc434edf0971cd1af4b04674a5904aef7026c39832dfce04080a4fcdb0391a79022a52926eaec1dc6b6c70d6085d8a6ff3a197f00ce32ed94a065b46f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8cca4a95228626629af993ae2c699bed:8181b6581fa8a91ff72aa7bc2a32a93ffe02154f60f0579ef7d46b85227cb667a3245e377dc0804588b0b6f518bad09e589e286a317cd04096677250af612fd5147c85d3c9b31a9a00987446f07ef1bd6460f4cdc434edf0971cd1af4b04674a5904aef7026c39832dfce04080a4fcdb0391a79022a52926eaec1dc6b6c70d6085d8a6ff3a197f00ce32ed94a065b46f)
System: Chrome 122.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/user/profile
Window size: width 1429 - height 790
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-19T00:54:47.848Z',to:'2024-03-19T01:00:47.848Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-19T00:54:47.848Z',to:'2024-03-19T01:00:47.848Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
same user (and I assume question) as https://github.com/gbif/portal-feedback/issues/5247
