### ISSUE TITLE
Blank downloaded TSV of  literature citations

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5248]
**Blank downloaded TSV of literature citations**

When I click the "download as tsv" button  from this page https://www.gbif.org/resource/search?contentType=literature&publishingOrganizationKey=66522820-055c-11d8-b84e-b8a03c50a862  the downloaded tsv is blank except for the columns. The search shows there should be 2,598 publications. Logging in and out of my account doesn't seem to help.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1f56cfba1f6b47c63b9deeabe64925ff:e4983dc3abed96d3584a5f6b821fce6cbe3bf206785f47fc459ada265e4f681804b17d5ba6e7f1899faa2e495db0ef42c104b2b608ef2ee6e7b874b9bdac0b348fee6a5e8750ddf69074b2cdf472bcfff0710d99b3fbfa60eeae00398e9efc81) - [Send email](https://www.gbif.org/api/feedback/user/mailto/1f56cfba1f6b47c63b9deeabe64925ff:e4983dc3abed96d3584a5f6b821fce6cbe3bf206785f47fc459ada265e4f681804b17d5ba6e7f1899faa2e495db0ef42c104b2b608ef2ee6e7b874b9bdac0b348fee6a5e8750ddf69074b2cdf472bcfff0710d99b3fbfa60eeae00398e9efc81)
System: Safari 17.2.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/resource/search?contentType=literature&publishingOrganizationKey=66522820-055c-11d8-b84e-b8a03c50a862
Window size: width 1470 - height 840
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-19T19:21:10.159Z',to:'2024-03-19T19:27:10.159Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-19T19:21:10.159Z',to:'2024-03-19T19:27:10.159Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
ping @mike-podolskiy90 
https://api.gbif.org/v1/literature/export?format=TSV&publishingOrganizationKey=66522820-055c-11d8-b84e-b8a03c50a862
vs
https://api.gbif.org/v1/literature/search?format=TSV&publishingOrganizationKey=66522820-055c-11d8-b84e-b8a03c50a862

**Comment by mike-podolskiy90** [comment]
@marcos-lg Can you have a look please? Or maybe @ahakanzn

**Comment by ahakanzn** [comment]
Fixed in the code and in dev: https://github.com/gbif/literature-ws/commit/008881085bc02ac93f23bdfa827b18f5a1ef7361

**Comment by ahakanzn** [comment]
Deployed on PROD
