### ISSUE TITLE
resource search overly strict on spelling

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#527]
**resource search overly strict on spelling**

might be worth including more results

ex: https://www.gbif.org/resource/search?q=work%20program
vs https://www.gbif.org/resource/search?q=work%20programme

from http://dev.gbif.org/issues/browse/PF-1941?jql=project%20%3D%20PF%20AND%20status%20%3D%20Open but still relevant

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb

System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/resource/search?q=work%20program
Window size: width 1918 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T10:18:00.379Z',mode:absolute,to:'2017-10-05T10:24:00.379Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T10:18:00.379Z',mode:absolute,to:'2017-10-05T10:24:00.379Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/08c24452d5e7a5d329d54114d231cb80a3c0755f
