### ISSUE TITLE
Inquiry Regarding Taxonomic ID Change from Reptilia (12170551) to Squamata (11592253)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5272]
**Inquiry Regarding Taxonomic ID Change from Reptilia (12170551) to Squamata (11592253)**

Dear GBIF Support Team,

I hope this message finds you well. I am writing to inquire about a specific change in the taxonomic identification within your database. It has come to my attention that the taxonomic ID previously associated with Reptilia (12170551) has now been updated to Squamata (11592253). I am curious about the rationale behind this change and how it affects the data and classifications previously under Reptilia.

As a user who relies on the accuracy and consistency of taxonomic data provided by GBIF for research purposes, understanding the reasons for such updates is crucial. Could you please provide some insight into the following:

What prompted the change from Reptilia to Squamata for the mentioned taxonomic ID?
How does this change impact the historical data and any research that utilized the previous classification?
Are there any recommended steps for users who have previously used Reptilia under the old taxonomic ID in their research or datasets?
I appreciate the complexity and the dynamic nature of taxonomic classifications and understand that revisions are part of ensuring the database remains accurate and up-to-date. However, any additional information or clarification you can provide regarding this specific change would be greatly appreciated.

Thank you for your time and the invaluable service that GBIF provides to the global research community. I look forward to your response and am happy to provide further details if needed.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3335824affd19f5e77c4a4f0a03db7f9:76ced84b1da7cc4b6412f2ae776c20ba5bac7ecc342a440ff382e756f2b48d21d2b4a62007f2620b7b8df94ca0bf7ad06ad06fdcc674846ff184bbdb2bd640371c474e61bbbf625377e2ae7880c39511406f351cf9c5e611cd17a30b7661bb89) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3335824affd19f5e77c4a4f0a03db7f9:76ced84b1da7cc4b6412f2ae776c20ba5bac7ecc342a440ff382e756f2b48d21d2b4a62007f2620b7b8df94ca0bf7ad06ad06fdcc674846ff184bbdb2bd640371c474e61bbbf625377e2ae7880c39511406f351cf9c5e611cd17a30b7661bb89)
System: Chrome 122.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/zh/species/search?q=Osteichthyes
Window size: width 1725 - height 914
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-26T06:27:57.143Z',to:'2024-03-26T06:33:57.143Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-26T06:27:57.143Z',to:'2024-03-26T06:33:57.143Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email


The GBIF Backbone taxonomy follows Catalogue of Life that have adopted a [new Vertebrate classification](https://github.com/CatalogueOfLife/testing/issues/186) that removes common taxa like Reptilia and raises former orders [Squamata](https://www.catalogueoflife.org/data/taxon/45C), [Testudines](https://www.catalogueoflife.org/data/taxon/477) and [Crocodylia](https://www.catalogueoflife.org/data/taxon/329) to class level.
 
In order to help users find reptiles, we generated the synonymy artificially. The idea is that users looking for Reptilia could still find the relevant classes: https://www.gbif.org/species/search?q=Reptilia
