### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5274]
**Data download**

Hi,

I would like to download data for Protea nana specifically, I do not want the whole gbif dataset. How does it work?

Kind regards

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d6ca6f5be36e854581b93c3c0b002b1b:e80a851d16be48cd6e6527a0cff20e0a596880b28dae7174289d23fb1f725a8a2fa7460258f3607968830cbaea99225ffc2fe2fa999eacf63cbc72d31249fbf2e99c73b05dd7efcafc1a236e5b4c2685d51500ace0a22f7e483a1a1eb5550d02) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d6ca6f5be36e854581b93c3c0b002b1b:e80a851d16be48cd6e6527a0cff20e0a596880b28dae7174289d23fb1f725a8a2fa7460258f3607968830cbaea99225ffc2fe2fa999eacf63cbc72d31249fbf2e99c73b05dd7efcafc1a236e5b4c2685d51500ace0a22f7e483a1a1eb5550d02)
System: Firefox 124.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/5637082
Window size: width 1536 - height 731
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-26T12:31:36.536Z',to:'2024-03-26T12:37:36.536Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-26T12:31:36.536Z',to:'2024-03-26T12:37:36.536Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email


You can download all the occurrences (observations or collection of a specimen at a given place and time) of Protea nana as follow:
* From the species page (https://www.gbif.org/species/5637082), click on the “occurrence” green button in the upper right corner
* Alternatively, you can also look for the species name in our occurrence search interface: https://www.gbif.org/occurrence/search?taxon_key=5637082
* Then click on the “DOWNLOAD” tab
* Select a download format
* When your download will be ready, you will be sent a notification with a link

You can find the documentation of all the fields included in the download [here](https://techdocs.gbif.org/en/data-use/download-formats).
If you would like more information on how to access data from GBIF.org, don’t hesitate to watch our [Data Use Club](https://www.gbif.org/data-use-club) recorded webinars. [This one](https://www.gbif.org/composition/4Xm5cVB4y9n7U1GlUtKx8Q/data-use-club-practical-session-1-recording-and-resources) is an introduction to our website.
