### ISSUE TITLE
wrong home page link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#528]
**wrong home page link**

http://ghabif.org/ is a wrong link

from but still true http://dev.gbif.org/issues/browse/PF-1942?jql=project%20%3D%20PF%20AND%20status%20%3D%20Open

-----
fbitem-dc692518854d3844327576e62622a13cc7e80c8e

System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/country/GH/participation
Window size: width 1918 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T10:20:31.347Z',mode:absolute,to:'2017-10-05T10:26:31.347Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T10:20:31.347Z',mode:absolute,to:'2017-10-05T10:26:31.347Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Removed.
