### ISSUE TITLE
The specimen was re-identified as Cicada similis (with the help of new pictures) : https://inaturalist.ca/observations/183825729

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5287]
**The specimen was re-identified as Cicada similis (with the help of new pictures) : `https://inaturalist.ca/observations/183825729`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8760954356dff9d3a57b476cfedb1a7a:d2b0e461ea4ed6673af6ea43236990dea08aa8346572898b2098b7e79fe9116742869e3a3290c23f9c2f7493234e9add5e4e6f770c01dbf410a426c172de10e897e241407d47ca173d3da81373e24060f63f30eb05f84266bf44d43929306400187f7c9491165df924daf6d41144f826131aad39180c35a7c2be01617458b6e0b845bbab022dc68f3e7e71253626c5c1) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8760954356dff9d3a57b476cfedb1a7a:d2b0e461ea4ed6673af6ea43236990dea08aa8346572898b2098b7e79fe9116742869e3a3290c23f9c2f7493234e9add5e4e6f770c01dbf410a426c172de10e897e241407d47ca173d3da81373e24060f63f30eb05f84266bf44d43929306400187f7c9491165df924daf6d41144f826131aad39180c35a7c2be01617458b6e0b845bbab022dc68f3e7e71253626c5c1)
System: Chrome 123.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/4535871892
Window size: width 1440 - height 779
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-07T15:56:07.945Z',to:'2024-04-07T16:02:07.945Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-07T15:56:07.945Z',to:'2024-04-07T16:02:07.945Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

Node handles: @sformel-usgs

**Comment by leilabrunner** [comment]
Sorry, I was meaning that the specie was identified as Tmetonyx similis instead of T. cicada

**Comment by sformel-usgs** [comment]
@leilabrunner I looked at the iNaturalist conversation, but I'm still a bit confused about how this should resolve.  I see both iNaturalist and GBIF assign this to `Tmetonyx similis (G.O.Sars, 1891)`. If that's correct, can we close this issue?

FYI, iNaturalist record updates are only pushed to GBIF on a weekly basis, so sometimes it takes a a few days to show up in GBIF.

**Comment by leilabrunner** [comment]
I see that it has been indeed updated, we can close the issue !

**Comment by sformel-usgs** [comment]
Thanks! @CecSve can you please close this when you have a moment?
