### ISSUE TITLE
No permit for my observation!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5288]
**No permit for my observation!**

I didn't permit for my observation to be part of the GBIF archive! I'm kindly asking you to remove all that you have under my name Urosh Grabner.
Data/observations from iNaturalist are strictly (all posts) with No license (all rights reserved)!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bfd02b66bfda13ad2a47b8beca3395b0:b4a0b651df4ee3da00d44054248e05f692b6bd3ab09667446bf58e8b123c169ccf3d1cf50bacbfe848f181447b5b33e70638f69148274d9d1458d96e4b47a801a87c6aeef62d6b2738128f6673412e9a0aa5a3d46894b3b274ce974f35f06a7b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/bfd02b66bfda13ad2a47b8beca3395b0:b4a0b651df4ee3da00d44054248e05f692b6bd3ab09667446bf58e8b123c169ccf3d1cf50bacbfe848f181447b5b33e70638f69148274d9d1458d96e4b47a801a87c6aeef62d6b2738128f6673412e9a0aa5a3d46894b3b274ce974f35f06a7b)
System: Chrome 123.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/code-of-conduct
Window size: width 1872 - height 966
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-07T19:05:48.416Z',to:'2024-04-07T19:11:48.416Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-07T19:05:48.416Z',to:'2024-04-07T19:11:48.416Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I see 20 results in inat identified by [Urosh Grabner](https://www.gbif.org/occurrence/search?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7&identified_by=Urosh%20Grabner&advanced=1&occurrence_status=present)

but [no records recordedBy](https://www.gbif.org/occurrence/search?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7&recorded_by=Urosh%20Grabner&advanced=1&occurrence_status=present)

**Comment by ManonGros** [comment]
I reply to the user by email and told him that he should contact us if any particular record is concerned.
