### ISSUE TITLE
ID wrong - Cerinthe major subsp. purpurascens (Boiss.) Selvi & L.Cecchi

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5296]
**ID wrong - Cerinthe major subsp. purpurascens (Boiss.) Selvi &amp; L.Cecchi**

Good morning. 
I would like to point out the incorrect attribution of the taxon Cerinthe major subsp. purpurascens to one of my observations carried out in Sardinia - IT (Borutta, Sassari, Sardinia - IT), present on iNaturalist, which I detected on GBIF.
Actually it is a specimen of Cerinthe major subsp. major and the incorrect attribution to C. major purpurascens was not unambiguous at the time and has now been withdrawn.
Below is the link to the position on GBIF and the observation on iNaturalist that traces the correct identification, now unique and confirmed by three identifiers.

https://www.gbif.org/occurrence/4129984732

https://www.inaturalist.org/observations/163895478

I remain available for any further clarification.
A cordial greeting
Roberto Meloni

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/19f2fd5a200718efe2b94340db4d2053:123bcc73d0032d222dde054c5206a5b3f26669d88d1bb1c3d4d250dbe03091a2287e8931d8e2a4d2d3a78b58febaac5320c6ca2e43a234abb4821ee2a4277ffd9712dc750327b894e3bd3d81ea2c2c4ae90dd1a261ab29cd1dddd34a26e49cfb) - [Send email](https://www.gbif.org/api/feedback/user/mailto/19f2fd5a200718efe2b94340db4d2053:123bcc73d0032d222dde054c5206a5b3f26669d88d1bb1c3d4d250dbe03091a2287e8931d8e2a4d2d3a78b58febaac5320c6ca2e43a234abb4821ee2a4277ffd9712dc750327b894e3bd3d81ea2c2c4ae90dd1a261ab29cd1dddd34a26e49cfb)
System: Chrome 123.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/4129984732
Window size: width 1872 - height 1004
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-12T06:50:55.206Z',to:'2024-04-12T06:56:55.206Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-12T06:50:55.206Z',to:'2024-04-12T06:56:55.206Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

Node handles: @sformel-usgs

**Comment by jhnwllr** [comment]
Correct now.
