### ISSUE TITLE
Request for list of newest resources

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#530]
**Request for list of newest resources**

Would be good to have the list of latest resources published to the GBIF website displayed. At the moment, visitors to the website have no way of knowing which the latest published documents are.

from 
http://dev.gbif.org/issues/browse/PF-1986?jql=project%20%3D%20PF%20AND%20status%20%3D%20Open

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb

System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/resource/search?contentType=document
Window size: width 1919 - height 1036
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T11:32:03.603Z',mode:absolute,to:'2017-10-05T11:38:03.603Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T11:32:03.603Z',mode:absolute,to:'2017-10-05T11:38:03.603Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
resources including documents are now sorted by creation date if no query is performed. ex: https://www.gbif.org/resource/search?contentType=document
