### ISSUE TITLE
My downloaded content number is not matching the downloaded results. My total when the download is qued is 1427 but I end up with 1957 on my spread sheet. Am I getting extra data?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5306]
**My downloaded content number is not matching the downloaded results. My total when the download is qued is 1427 but I end up with 1957 on my spread sheet. Am I getting extra data?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c947f67a71e288cc06d39437ce38cc96:461548b5b8aff6f01de8853eb98e1921663e3f38efe1f36e2fb07a7587a5e0720b816163d774f0a560a3ecd8cb97be383bd4156519d3638fbc16adee99c15c17e2d98f9654f1359ae41ccab0178b2061e30133ca4520b0f9f773d921818bf3fb) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c947f67a71e288cc06d39437ce38cc96:461548b5b8aff6f01de8853eb98e1921663e3f38efe1f36e2fb07a7587a5e0720b816163d774f0a560a3ecd8cb97be383bd4156519d3638fbc16adee99c15c17e2d98f9654f1359ae41ccab0178b2061e30133ca4520b0f9f773d921818bf3fb)
System: Safari 17.4.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download?basis_of_record=PRESERVED_SPECIMEN&basis_of_record=OCCURRENCE&basis_of_record=LIVING_SPECIMEN&continent=NORTH_AMERICA&country=US&has_coordinate=true&has_geospatial_issue=false&taxon_key=3052436&occurrence_status=present
Window size: width 1251 - height 778
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-25T15:08:31.976Z',to:'2024-04-25T15:14:31.976Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-25T15:08:31.976Z',to:'2024-04-25T15:14:31.976Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email — the has_coordinate filter wasn't used for the download.
