### ISSUE TITLE
Require complete Buprestidae species list

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5309]
**Require complete Buprestidae species list**

Hi there,

I am a registration officer with Melbourne Museum and I am trying to download a complete list of all species within the Buprestidae family.
I have tried multiple times, but the download keeps failing - 'Broken download' error message. 

Can you please help me to download this species list?

Thanks,
Alicia

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/708d2bd5a05bb9cdfdd051e99d72334b:c2354f01f11ae187fb70065394852691328278b5edc505483d066a4ac8924dfe582a82424397d177eb442d9de10757f7ba7499457350604811a62cada755f286c4b88ef754353fd2e59d965f445e4359b5e8f0d05da17dc1ddace3b1207a209a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/708d2bd5a05bb9cdfdd051e99d72334b:c2354f01f11ae187fb70065394852691328278b5edc505483d066a4ac8924dfe582a82424397d177eb442d9de10757f7ba7499457350604811a62cada755f286c4b88ef754353fd2e59d965f445e4359b5e8f0d05da17dc1ddace3b1207a209a)
System: Chrome 124.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0009531-240425142415019
Window size: width 1318 - height 620
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-01T05:36:30.259Z',to:'2024-05-01T05:42:30.259Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-01T05:36:30.259Z',to:'2024-05-01T05:42:30.259Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by jhnwllr** [comment]
(responded via helpdesk) likely due to system outages
