### ISSUE TITLE
Hi GBIF friends - how can we update the information associated with the publisher "Western Australian Herbarium"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5310]
**Hi GBIF friends - how can we update the information associated with the publisher &quot;Western Australian Herbarium&quot;**

https://www.gbif.org/publisher/9d23a1e0-5388-11df-a59b-b8a03c50a862

The website is now: https://www.dbca.wa.gov.au/science/research-tools-and-repositories/western-australian-herbarium
I don't think the contact phone will get you anywhere: Shelley James is +61 (08) 9219 9130

Many thanks!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3ea5850c18d3fa1b3a93ce6342e15fa0:40315727616edfac1fc6ae05a9a3eeb62d73df7194caa926918733b6c9d8ac487f4351e06bab9a5301c8a1d0e4992e70fb6b2d223c0fbdfe71b2089c9a89d6fd34ce8f55534ab3447251b833e14003f2fb4c240821cbeaa144b415624e5403fbc58db809003416dbe32be2962f744c36c4e6bf9c8577d96a7250a528ff170e9dbbc1462e8451636fe469577064e525f8) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3ea5850c18d3fa1b3a93ce6342e15fa0:40315727616edfac1fc6ae05a9a3eeb62d73df7194caa926918733b6c9d8ac487f4351e06bab9a5301c8a1d0e4992e70fb6b2d223c0fbdfe71b2089c9a89d6fd34ce8f55534ab3447251b833e14003f2fb4c240821cbeaa144b415624e5403fbc58db809003416dbe32be2962f744c36c4e6bf9c8577d96a7250a528ff170e9dbbc1462e8451636fe469577064e525f8)
System: Chrome 124.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/9d23a1e0-5388-11df-a59b-b8a03c50a862
Window size: width 1080 - height 1759
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-01T05:58:12.307Z',to:'2024-05-01T06:04:12.307Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-01T05:58:12.307Z',to:'2024-05-01T06:04:12.307Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
The person who logged the issue is one of the contacts, I contacted them and let them know that updates can be sent to helpdesk@gbif.org. In addition to that, I updated the organisation information.
