### ISSUE TITLE
would it be possible to have an export function for species search?

### ISSUE THREAD

**Issue by jhnwllr** [gbif/portal-feedback#5312]
https://techdocs.gbif.org/en/openapi/v1/registry#/Datasets/searchDatasetsExport
https://techdocs.gbif.org/en/openapi/v1/literature#/Literature/export

**Comment by ManonGros** [comment]
It could be a checklisbank function, it would be nice to be able to download things here: https://www.checklistbank.org/nameusage/search?extinct=true&facet=datasetKey&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&sortBy=taxonomic

**Comment by jhnwllr** [comment]
https://github.com/CatalogueOfLife/checklistbank/issues/1395
