### ISSUE TITLE
Can't handle DwC-As with measurementOrFact files

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5313]
**Can&#39;t handle DwC-As with measurementOrFact files**

We've noticed a problem that when we attempt to publish a Darwin Core Archive that contains a measurementOrFact extension, the dataset is rejected by your system (e.g., https://logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(display:On,pause:!f,value:0),time:(from:now-1y,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'439da4d0-290a-11ed-8155-a37cb1ead50e',key:level,negate:!f,params:(query:ERROR),type:phrase),query:(match_phrase:(level:ERROR)))),index:'439da4d0-290a-11ed-8155-a37cb1ead50e',interval:auto,query:(language:lucene,query:'datasetKey.keyword:%22b0515413-6d32-490a-83a0-f8c08f002c70%22%20AND%20attempt:%22167%22'),sort:!('@timestamp',desc))).

Could the system just ignore this file instead of rejecting the whole archive? Several of our portals now have this extension.

-----

Github user: @themerekat
User: [See in registry](https://www.gbif.org/api/feedback/user/cfcab931e6ca7e6b3c20b850a3945aff:14cb190bf5c99d378e1daa7e0ccc295b45c31b8b45f7ca7efaecd0461f6f5d9b351682817c9b9d35cd55fcd56259f964fa84e27c16d31288ce98636c3393e5ec271d89cdfdb3a279b28ba359fa938b54f60c92f6a0984111e261f8937c4c482eb6f674baa7e2a34f8c05bfe68af482e53f1eae9ff2bedb7edbb5a1a14799e301f3d2cfcc252ed8b0e5f925af1536e73d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/cfcab931e6ca7e6b3c20b850a3945aff:14cb190bf5c99d378e1daa7e0ccc295b45c31b8b45f7ca7efaecd0461f6f5d9b351682817c9b9d35cd55fcd56259f964fa84e27c16d31288ce98636c3393e5ec271d89cdfdb3a279b28ba359fa938b54f60c92f6a0984111e261f8937c4c482eb6f674baa7e2a34f8c05bfe68af482e53f1eae9ff2bedb7edbb5a1a14799e301f3d2cfcc252ed8b0e5f925af1536e73d)
System: Chrome 124.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/b0515413-6d32-490a-83a0-f8c08f002c70
Window size: width 1536 - height 703
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-01T22:26:58.676Z',to:'2024-05-01T22:32:58.676Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-01T22:26:58.676Z',to:'2024-05-01T22:32:58.676Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by CecSve** [comment]
Could it be a simple misspelling of the extension perhaps?

`DwC-A data file »measurementOrFact.csv« does not exist at`

It should be measurementOrFact**s**.csv

**Comment by themerekat** [comment]
Hm...wouldn't it need to be "measurementsOrFacts" if that was the case?

**Comment by themerekat** [comment]
Looks like Darwin Core kind of has it both ways 😅
![image](https://github.com/gbif/portal-feedback/assets/16688784/90f2c6d6-d9d8-4703-b4e5-907abfbc9ae6)

**Comment by CecSve** [comment]
> Looks like Darwin Core kind of has it both ways 😅 ![image](https://private-user-images.githubusercontent.com/16688784/327467519-90f2c6d6-d9d8-4703-b4e5-907abfbc9ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjA1MTcsIm5iZiI6MTcxNDY2MDIxNywicGF0aCI6Ii8xNjY4ODc4NC8zMjc0Njc1MTktOTBmMmM2ZDYtZDlkOC00NzAzLWI0ZTUtOTA3YWJmYmM5YWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE0MzAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMWZhODNkOWQ5NDNiMTQ5ODEzZTU1OGQwYTgxYWUzZjllMGM1ZWUwZWZlOTY3MzI4MmI4YWQ5NGQ3ZTU4ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T5eGU-bCTQBnoS7bOURgMqFUfIGkBReR-KQS4Vqmsmg)

Jeez. Well, it looks like you had it right to begin with: https://github.com/gbif/rs.gbif.org/blob/master/extension/measurements_or_facts_2024-02-19.xml and https://dwc.tdwg.org/terms/#measurementorfact.

Ok, back to the drawing board then. I will investigate.

**Comment by CecSve** [comment]
I downloaded the most recent endpoint and I cannot see that the file exist in the archive, however, you have added the extendedMeasurementOrFact to your meta.xml file. We use the meta.xml file to validate the content of the archive (see the message: `Exception caught during metasyncing DwC-A [b0515413-6d32-490a-83a0-f8c08f002c70]`, and service `crawler-dwca-metasync)` which then throws the error in stack_trace `org.gbif.dwc.UnsupportedArchiveException: DwC-A data file »measurementOrFact.csv« does not exist`.

If the meta.xml of the different archives keeps referring to such a file, whether there will be content in it or not, the file should be included in the archive. Does it make sense?

**Comment by themerekat** [comment]
Hm, so we have "extendedMeasurementOrFact" in the meta, but only "measurementOrFact" in the actual archive?

**Comment by CecSve** [comment]
> Hm, so we have "extendedMeasurementOrFact" in the meta, but only "measurementOrFact" in the actual archive?

I do not see either extension file in the archive, only the extendedMeasurementOrFact information in meta.

**Comment by themerekat** [comment]
> > Hm, so we have "extendedMeasurementOrFact" in the meta, but only "measurementOrFact" in the actual archive?
> 
> I do not see either extension file in the archive, only the extendedMeasurementOrFact information in meta.

Aha, thanks for the clarification! It does appear that our batch process is not including the measurementOrFact file, but our single-publishing process is. I'll look into this! Feel free to close this issue.
