### ISSUE TITLE
I don't understand why there is an error flag 'taxon match name and ID ambiguous': https://www.marinespecies.org/aphia.php?p=taxdetails&id=126529

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5314]
**I don&#39;t understand why there is an error flag &#39;taxon match name and ID ambiguous&#39;: `https://www.marinespecies.org/aphia.php?p=taxdetails&amp;id=126529`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4cc446d614e8c7554aded725995cca4c:b663444f2ece8153dd178a231454d4db79ee7cb63ba95fb8f94654477368ba6e02a8e2fc9afe8c3fb006b440f48a386f4281d30d3736e3d30d1b8ed79ec6d847ed3603fd4cd21f820e3a56f45178029714b0ca93add0bd8a3671ac67ced181253adb7a97974ddd114228f363ebbae15c2a7870fff2d2b239c781bb105a8ee097cf9494b0768e354bbb184b1feb969bb6) - [Send email](https://www.gbif.org/api/feedback/user/mailto/4cc446d614e8c7554aded725995cca4c:b663444f2ece8153dd178a231454d4db79ee7cb63ba95fb8f94654477368ba6e02a8e2fc9afe8c3fb006b440f48a386f4281d30d3736e3d30d1b8ed79ec6d847ed3603fd4cd21f820e3a56f45178029714b0ca93add0bd8a3671ac67ced181253adb7a97974ddd114228f363ebbae15c2a7870fff2d2b239c781bb105a8ee097cf9494b0768e354bbb184b1feb969bb6)
System: Chrome 123.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1230365123
Window size: width 1920 - height 919
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-02T10:44:33.045Z',to:'2024-05-02T10:50:33.045Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-02T10:44:33.045Z',to:'2024-05-02T10:50:33.045Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO
datasetKey: 1aaec653-c71c-4695-9b6e-0e26214dd817
publishingOrgKey: cecc196e-f262-4986-a88a-6adf035dca0e

**Comment by CecSve** [comment]
The user has been contacted through help desk with the following answer:

Issues and flags are documented in the [technical documentation](https://techdocs.gbif.org/en/data-use/occurrence-issues-and-flags). The explanation for this specific flag is the following:

> The GBIF Backbone concept was found using the scientificNameID, taxonID or taxonConceptID, but it differs from what would have been found if the classification names on the record were used. This may indicate a gap in the GBIF backbone, a poor mapping between the checklist and the backbone, or a mismatch between the classification names and the declared IDs (scientificNameID or taxonConceptID) on the occurrence record itself.
