### ISSUE TITLE
Unrecognized WoRMS classes

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5318]
**Unrecognized WoRMS classes**

Hello, 
To contextualize, my use of GBIF is recent and I have no expertise in ecology. 
While working on GBIF data, I was surprised to discover observations for which taxonomic information was missing at ranks higher than the rank of the most specific name (i.e `taxonRank`). When I tried to find out what was particular to the species concerned that could explain this, I realized that the missing information could be found in one of the backbones used by GBIF, namely WoRMS. For example: Dentalina cooperensis (Cushman, 1933) and the class Nodosariata  (https://www.marinespecies.org/aphia.php?p=taxdetails&id=522835), or Syngnathus affinis (Günther, 1870) and the class Teleostei (https://www.marinespecies.org/aphia.php?p=taxdetails&id=275216). In fact, there are other differences between WoRMS and GBIF.
I read [here](https://gbif.blogspot.com/2016/04/updating-gbif-backbone.html) that: " [The old backbone] was built using an automated process that made use of selected checklists from the GBIF ChecklistBank in a **prioritised** order. The Catalogue of Life was still the starting point and provided the **higher classification down to orders**". Is this the reason for the differences between the WoRMS and GBIF classifications? Or is there another reason?
Thank you very much for your answer

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d143e5841b136bbe831a4f42c16c149f:c1c2b6ace79dd6a60a4977f94a4f061109542dd78ce0546acfa5ced0ca5c85f8e85655bd938f07e50f100723c1d95319dd8733377f91f4067652297f37689d48e160f27f7d8e706e54fd7a4cd4346b1346cea5709ebd29e5a13441ef83472ab0293eba8b3d48120462d3fc2831d77364) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d143e5841b136bbe831a4f42c16c149f:c1c2b6ace79dd6a60a4977f94a4f061109542dd78ce0546acfa5ced0ca5c85f8e85655bd938f07e50f100723c1d95319dd8733377f91f4067652297f37689d48e160f27f7d8e706e54fd7a4cd4346b1346cea5709ebd29e5a13441ef83472ab0293eba8b3d48120462d3fc2831d77364)
System: Chrome 121.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/fr/
Window size: width 1294 - height 595
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-06T13:37:17.537Z',to:'2024-05-06T13:43:17.537Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-06T13:37:17.537Z',to:'2024-05-06T13:43:17.537Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by CecSve** [comment]
User has been contacted through helpdesk
