### ISSUE TITLE
auto fill email in feedback if logged in

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#532]
**auto fill email in feedback if logged in**

or better yet, integrate with Github so that is an option as well
see also http://dev.gbif.org/issues/browse/PF-2062?jql=project%20%3D%20PF%20AND%20status%20%3D%20Open

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
User provided contact info: mortenhofft
System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/
Window size: width 1919 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T11:59:40.352Z',mode:absolute,to:'2017-10-05T12:05:40.352Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T11:59:40.352Z',mode:absolute,to:'2017-10-05T12:05:40.352Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
if connected to Github the Github username is used as default. email are not used as a default to avoid peoples email being made public without them explicitly stating that it is okay
