### ISSUE TITLE
The species Foa fo Jordan & Seale 1905 needs to be added: https://www.marinespecies.org/aphia.php?p=taxdetails&id=279256

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5326]
**The species Foa fo Jordan &amp; Seale 1905 needs to be added: `https://www.marinespecies.org/aphia.php?p=taxdetails&amp;id=279256`**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/feca852d580b51e008d3932a1deb629a:8e7710790c225038b21e5319c5a5559a1bd71b04dfdb8cafa107a5d2342f9cd9248ea3b7da4574be6dc87aed6db02537248387f89f03562334f6d032a8c34322826eee145bc6a8c4981c5574957311a3a3a9aab31c77d7d296ca5c9cf7b5ec5e8c40197c77f7a0b39a472e2f5bb9e2a50a9c7b41113f30a80877a60f9283990ebae97e78256067cda86a2718d2e26d39) - [Send email](https://www.gbif.org/api/feedback/user/mailto/feca852d580b51e008d3932a1deb629a:8e7710790c225038b21e5319c5a5559a1bd71b04dfdb8cafa107a5d2342f9cd9248ea3b7da4574be6dc87aed6db02537248387f89f03562334f6d032a8c34322826eee145bc6a8c4981c5574957311a3a3a9aab31c77d7d296ca5c9cf7b5ec5e8c40197c77f7a0b39a472e2f5bb9e2a50a9c7b41113f30a80877a60f9283990ebae97e78256067cda86a2718d2e26d39)
System: Chrome 124.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/2397601
Window size: width 1920 - height 919
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-10T09:17:38.564Z',to:'2024-05-10T09:23:38.564Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-10T09:17:38.564Z',to:'2024-05-10T09:23:38.564Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by CecSve** [comment]
The species record is under a Creative Commons [Attribution-Noncommercial 4.0 License](http://creativecommons.org/licenses/by/4.0/deed.en) https://www.marinespecies.org/aphia.php?p=taxdetails&id=279256 and should be part of the [WoRMS checklist](https://www.gbif.org/dataset/2d59e5db-57ad-41ff-97d6-11f5fb264527).

There seems to be issues still with ingesting the checklist? @mdoering

**Comment by CecSve** [comment]
User has been contacted through helpdesk

**Comment by mdoering** [comment]
https://www.marinespecies.org/export/gbif/WoRMS_DwC-A.zip (which is painfully restricted to some GBIF IPs apparently) does contain the AphiaID 279256. 

Our version we last indexed is from the 1st of May and also contains the entry:

>147781:urn:lsid:marinespecies.org:taxname:279256	urn:lsid:marinespecies.org:taxname:279256	urn:lsid:marinespecies.org:taxname:279256	urn:lsid:marinespecies.org:taxname:206869		Foa fo	Foa fo	Foa	Jordan, D. S.; Seale A.

You can actually find the record through the API:
http://api.gbif.org/v1/species?datasetKey=2d59e5db-57ad-41ff-97d6-11f5fb264527&sourceId=urn:lsid:marinespecies.org:taxname:279256

But the name has problems and it is interpreted as `Foa spec.`:
https://www.gbif.org/species/155329171

I will try to figure out why that is

**Comment by mdoering** [comment]
Foa fo is parsed as a `form` apparently: https://api.gbif.org/v1/parser/name?name=Foa%20fo
I need to fix the name parser to solve this very problem

**Comment by CecSve** [comment]
I tried to crawl WoRMS, but perhaps it is the endpoint update -> crawl of Catalogue of Life that needs to happen for the change to take effect?

**Comment by mdoering** [comment]
I still need to deploy the fix. Releasing the old checklistbank right now. It all takes a bit of time

**Comment by mdoering** [comment]
new CLB CLIs deployed, services starting up now. Requested a recrawl of worms now

**Comment by CecSve** [comment]
The record has been corrected https://www.gbif.org/species/155329171 and the user has been notified.
