### ISSUE TITLE
hello! I am using occ_download to retrieve occurance data using rgbif package in R, however the download does not include the column called 'reproductiveCondition' which is one of the key things i am looking for (this column downloads with data when i use a different method. Upon further reseach it looks like this Key is not available currently. Could you help me out with this? Thanks so much!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5329]
**hello! I am using occ_download to retrieve occurance data using rgbif package in R, however the download does not include the column called &#39;reproductiveCondition&#39; which is one of the key things i am looking for (this column downloads with data when i use a different method. Upon further reseach it looks like this Key is not available currently. Could you help me out with this? Thanks so much!**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/db3665bc30b4337322ec944ca48019bc:a01ebaf62d28204078558ac8e765c6e9e454f45464ce0a59c6f39ed8133161a311626383ce22a81ad1a96bf5fe2a22cfa0e3b99e527efcc818fc0810440e5b3d1210b12e4406483700b4d581b17e46881f52e294d3369be02a01ee09944d479421f40ecadac181adb5e517442ca581c6) - [Send email](https://www.gbif.org/api/feedback/user/mailto/db3665bc30b4337322ec944ca48019bc:a01ebaf62d28204078558ac8e765c6e9e454f45464ce0a59c6f39ed8133161a311626383ce22a81ad1a96bf5fe2a22cfa0e3b99e527efcc818fc0810440e5b3d1210b12e4406483700b4d581b17e46881f52e294d3369be02a01ee09944d479421f40ecadac181adb5e517442ca581c6)
System: Chrome 124.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/0012333-240506114902167
Window size: width 1324 - height 1250
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-13T22:14:10.831Z',to:'2024-05-13T22:20:10.831Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-13T22:14:10.831Z',to:'2024-05-13T22:20:10.831Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by jhnwllr** [comment]
repost from rgbif repo. Answering there. 
https://github.com/ropensci/rgbif/issues/734
