### ISSUE TITLE
download link doesn't show

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#533]
**download link doesn&#39;t show**

works fine when running the project locally

-----
fbitem-dde7509bc5e8a6a60357b44e1326183c81df5565
User provided contact info: mortenhofft
System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/occurrence/download/0001261-171002173027117
Window size: width 1400 - height 1036
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T12:14:03.450Z',mode:absolute,to:'2017-10-05T12:20:03.450Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T12:14:03.450Z',mode:absolute,to:'2017-10-05T12:20:03.450Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
looks like a cache thing. changing to non varnish verison it works as well

**Comment by MortenHofft** [comment]
The introduction of the FILE_ERASED enumeration has hopefully solved this as we no longer need to do a GET header to estimate if the file is ready
