### ISSUE TITLE
Become a publisher > Terms and conditions: add a line that explains having to log in to/ register a user account first

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5331]
**Become a publisher &gt; Terms and conditions: add a line that explains having to log in to/ register a user account first**

As a preventative measure against spam registrations, we introduced a two-step process for publisher registration: create and/or log in to a verified user account first, and after that fill the form detailing organizational data etc.

In the recent past, we had a few cases of new publishers confusing the user registration with the publisher registration process, and stopping after having registered their user account, then waiting in vain for their publisher record to be confirmed.

Suggestion: add a line to the "Terms and conditions" page of the "become-a-publisher" workflow that explains the process, like e.g.

"This process requires you to be logged into your GBIF user account. If you do not have an account yet, you can create one in the next step. Please remember to refresh the registration page after that."

-----

Github user: @ahahn-gbif
User: [See in registry](https://www.gbif.org/api/feedback/user/a35697d26835d0a760bd2fc3efd2dd92:65a10a512431155bec031ed5a61835d686f8458d748773374c7ed09b3c5e666b91528d1455803700ee2ec25575197e48487c7a8e28bb6a69f0ef85af37ba29f80dbbcfee5f97e0775d4cf27f29b47386d6c6e0691b111a5a3146f54f83f78587f7584fa1f5027f4dd19756a5fa0eac9330e3afba4135276c6013f8a4176609fe) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a35697d26835d0a760bd2fc3efd2dd92:65a10a512431155bec031ed5a61835d686f8458d748773374c7ed09b3c5e666b91528d1455803700ee2ec25575197e48487c7a8e28bb6a69f0ef85af37ba29f80dbbcfee5f97e0775d4cf27f29b47386d6c6e0691b111a5a3146f54f83f78587f7584fa1f5027f4dd19756a5fa0eac9330e3afba4135276c6013f8a4176609fe)
System: Firefox 125.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/become-a-publisher
Window size: width 1040 - height 615
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-14T06:35:33.678Z',to:'2024-05-14T06:41:33.678Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-14T06:35:33.678Z',to:'2024-05-14T06:41:33.678Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
I find that the appearance of the login form is confusing as well. There is no information telling you that you need to login. And it appears somehow randomly when you click that your org doesn't exist already.

But I'm not crazy about adding more information to a "terms" section. It doens't have anything to do with terms and no one cares to read it unless they are somehow forced to.

I've added a notification stating
`You need an account to register a new organization. Please create an account first and then revisit this page.`
You cannot fill in the form unless logged in. The exact phrasing can be changed in crowdin in the `components/eoi/loginRequired` field
