### ISSUE TITLE
How to get more than 100,000 results ?

### ISSUE THREAD

**Issue by Kydae** [gbif/portal-feedback#5332]
Hello !

I'm trying to get a list of all the datasets that contains data from the Caribbean sea. I couldn't find a parameter in the dataset search that could help me for this task. So I tried to use the occurrence search with a range in the decimalLatitude and decimalLongitude parameters (After that I want to use the datasetKey of those occurrences to make the list of datasets). Unfortunately, there is too many results and I can't access all of them because of the limitations of those parameters: limit and offset. Is there a way to get over those limitations? Or do you know a better way to do this task? 

I'm using the python library to call the API. I'm joining pictures of my request, the result I get from this request and the information I found about the limitations of the limit and offset parameters.

Thank you for your time!

<img width="638" alt="code_used_to_call_API" src="https://github.com/gbif/portal-feedback/assets/118560141/0b209787-a978-4e88-9943-3e6c88025ce0">
<img width="448" alt="number_of_occurrences_found" src="https://github.com/gbif/portal-feedback/assets/118560141/d5c961ae-b046-406c-a6a2-2b1081c09b94">
<img width="682" alt="issue_with_limit_and_offset" src="https://github.com/gbif/portal-feedback/assets/118560141/2b7400ab-4da1-42a0-8786-9beddedb2a8b">

**Comment by MortenHofft** [comment]
Use facets (list of distinct keys) instead. 

https://api.gbif.org/v1/occurrence/search?geometry=POLYGON((-91.18288%2013.61407,-62.91435%2013.61407,-62.91435%2030.67822,-91.18288%2030.67822,-91.18288%2013.61407))&occurrence_status=present&limit=0&facet=datasetKey&facetLimit=100&facetOffset=0

used to generate things like https://www.gbif.org/occurrence/charts?geometry=POLYGON((-92.68212%208.22215,-56.48297%208.22215,-56.48297%2028.61908,-92.68212%2028.61908,-92.68212%208.22215))&occurrence_status=present&d=datasetKey

@CecSve will know how to do that in pygbif - above example is using the API directly

**Comment by Kydae** [comment]
Oh I didn't understand that you could use the facet parameter like that. I will try it ! Thank you for your help !

**Comment by Kydae** [comment]
I tried to use the facet parameter as you advised me, but it seems like my results are the same and I don't get a list of distinct keys. Here are pictures of my call to the API and the results I got (I got a little bit more results than before because I used the geometry parameter instead of decimalLatitude and decimalLongitude).

<img width="634" alt="call_to_API" src="https://github.com/gbif/portal-feedback/assets/118560141/20991257-3fa1-43b8-a60e-62a8d3bb313c">
<img width="187" alt="dataset_key_of_the_results" src="https://github.com/gbif/portal-feedback/assets/118560141/f473b8b0-241b-434c-b11f-a41ba9c60e0a">
<img width="365" alt="number_of_results" src="https://github.com/gbif/portal-feedback/assets/118560141/daacd914-5153-4618-ad5d-c93c013ea1bd">

**Comment by MortenHofft** [comment]
You should have a limit of `0` to exclude occurrence - you do not want the occurrence result but the facets. See the link above for the response format. You need to look at `facets[0].counts`

**Comment by Kydae** [comment]
Yeah it works ! I didn't notice the 'facets' key in the resulting dictionary, my bad.

Thank you for your time and help !
