### ISSUE TITLE
event file missing in DWC-download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5337]
**event file missing in DWC-download**

Download of https://doi.org/10.15468/fsxvp7 ( Earthworms and potworms in Dutch soils from the National Biological Soil Monitoring project 1997-2014. Sampling event dataset  accessed via GBIF.org on 2024-05-22.) is missing the event file. Other file are present in the zip-file

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fff99233d805d01a1a776b5d68555aaa:c860e676e49f349a942e0a48f6e800753cf11e8176dddfb59775530bdeea6353c11a8c41eba2355823d0031cf50f0a75ff79ff44ba1f8d86ee1b0ea06ba2f4c2b29057337513445d4e578511da833e1a6475c0b3920f3378d6af78a81b802175d285604e86a23e3dc2f61bd155f7d738e3b525864c9c393393c5a4d1ce65ab1035df9ae0a42c6a727885309a9369d2a2) - [Send email](https://www.gbif.org/api/feedback/user/mailto/fff99233d805d01a1a776b5d68555aaa:c860e676e49f349a942e0a48f6e800753cf11e8176dddfb59775530bdeea6353c11a8c41eba2355823d0031cf50f0a75ff79ff44ba1f8d86ee1b0ea06ba2f4c2b29057337513445d4e578511da833e1a6475c0b3920f3378d6af78a81b802175d285604e86a23e3dc2f61bd155f7d738e3b525864c9c393393c5a4d1ce65ab1035df9ae0a42c6a727885309a9369d2a2)
System: Chrome 124.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/document/81771/gbif-overview-powerpoint-slides
Window size: width 1707 - height 781
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-24T08:23:11.432Z',to:'2024-05-24T08:29:11.432Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-05-24T08:23:11.432Z',to:'2024-05-24T08:29:11.432Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
@jeroencreuwels sorry for the delated reply. It looks like the event file is available in the archive available at the endpoint: https://ipt.nlbif.nl/archive.do?r=rivm_worm_survey. Do you mean that the event file isn't available when generating an occurrence download like this https://www.gbif.org/occurrence/download?dataset_key=5ba29440-cdb5-4c7c-b98e-1b9adfc75173? (If so this is because the occurrence downloads only contain occurrences)

**Comment by jeroencreuwels** [comment]
Thanks Marie, I don't know why but today the event file is indeed available (thru the IPT and from the portal). This was not the case when made this issue (actually someone else pointed this out to me). It is working now, thus this issue can be closed.
