### ISSUE TITLE
maximum offsets

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#534]
**maximum offsets**

are there any maximum offsets? If so what are they so they can be documented and the user can get the information.

based on http://dev.gbif.org/issues/browse/PF-2101?jql=project%20%3D%20PF%20AND%20status%20%3D%20Open

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: mortenhofft
System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/occurrence/search
Window size: width 1391 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T12:30:36.112Z',mode:absolute,to:'2017-10-05T12:36:36.112Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T12:30:36.112Z',mode:absolute,to:'2017-10-05T12:36:36.112Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I labeling this as a bug as i think it is quite essential to have it documented. I myself have written code assuming something that isn't the case and there might be bugs in the portal for that very reason.

**Comment by MattBlissett** [comment]
There is only a maximum offset on the occurrence API, and it's documented near the top of https://www.gbif.org/developer/occurrence

Too high an offset gives a 400 Bad request, with the text "maximum offset allowed is 200000".
