### ISSUE TITLE
wrong coordinates

### ISSUE THREAD

**Issue by jhnwllr** [gbif/portal-feedback#5340]
(from helpdesk) 
Limacus flavus, Event ID 66e83ed6-dfeb-4f83-951a-4841a2bde36e. The coordinates (38.33 145.17) in this data set are completely wrong It must be somewhere in Japan, but the coordinates are leading me into the open sea far east of Japan… This should be corrected.

**Comment by jhnwllr** [comment]
https://www.gbif.org/occurrence/2423560273

**Comment by Mesibov** [comment]
It's not in Japan. The OzAtlas [record](https://biocollect.ala.org.au/sightings/bioActivity/index/66e83ed6-dfeb-4f83-951a-4841a2bde36e) says the slug was recorded in Bittern, Victoria, Australia. The latitude and longitude are correct if the latitude is negated. ALA should be queried to see if the loss of the "-" from the latitude was an ALA processing problem, and if it was, what other records have been shifted between hemispheres.
