### ISSUE TITLE
How do you download data that includes original event date (including month, day)?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5366]
**How do you download data that includes original event date (including month, day)?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/814b3b74ac01e465e4ff725bf358bed6:9aaae495410251731834c0357eec2a0dfaa0e7433d42dff09bd9a1bbe032674dc115a90cced5c4642b9c17a6b89e427168b00b894710273fa2cbdcda12d988f1e354fc961e6f529b9415c0dad95391a2be75c3baaa15c4695466f797e5e6c7a30d6c2bcba5dcb7b830f03b2382182a845f749d897ee8d0a751a772cac479d5f5ce93809a8ae26ba5ebbd4a811dd29b28) - [Send email](https://www.gbif.org/api/feedback/user/mailto/814b3b74ac01e465e4ff725bf358bed6:9aaae495410251731834c0357eec2a0dfaa0e7433d42dff09bd9a1bbe032674dc115a90cced5c4642b9c17a6b89e427168b00b894710273fa2cbdcda12d988f1e354fc961e6f529b9415c0dad95391a2be75c3baaa15c4695466f797e5e6c7a30d6c2bcba5dcb7b830f03b2382182a845f749d897ee8d0a751a772cac479d5f5ce93809a8ae26ba5ebbd4a811dd29b28)
System: Chrome 123.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/3055410812
Window size: width 1470 - height 799
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-06-24T21:36:13.784Z',to:'2024-06-24T21:42:13.784Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-06-24T21:36:13.784Z',to:'2024-06-24T21:42:13.784Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO
datasetKey: ce9d17f0-de7f-4518-83a6-690c615dd8d9
publishingOrgKey: c3ad790a-d426-4ac1-8e32-da61f81f0117

Node handles: @sformel-usgs

**Comment by ManonGros** [comment]
When downloading occurrences from GBIF from the [occurrence search interface](https://www.gbif.org/occurrence/download?occurrence_status=present), you can select the “DARWIN CORE ARCHIVE” download format. That format contains all the original data provided by the sources. You can read more about this format here:
* https://www.gbif.org/faq?question=dwc-download
* https://www.gbif.org/faq?question=what-is-inside-a-gbif-download-zip-file

> Replied by email
