### ISSUE TITLE
Individual Count

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5368]
**Individual Count**

Hello! 
Could you tell me the meaning of "Individual Count“ field in the download occurrence datasets, please? 
Does it refer to the number of observed mosquitoes ? 

Thank you very much!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/aa930e706ada31d2a31aca6843ce2655:8e9d115a7dc8cc1e4ebe3fafda33ac6b0e9a25405b2355330b5c5b336e777223252424237d4855e60e9373f4f67d5d00698d70b75ffb7776f84e3875590f81342d712bac2a76a803c03152958f114fbff340dfb2bacb995ab92faaff49458480b8402b502ac46e80d2dea3f576715c8935cb2a4d5d9cf929f7a3d21aa9e1817d054ad39f47ca964b95ed62d1f11d52e7) - [Send email](https://www.gbif.org/api/feedback/user/mailto/aa930e706ada31d2a31aca6843ce2655:8e9d115a7dc8cc1e4ebe3fafda33ac6b0e9a25405b2355330b5c5b336e777223252424237d4855e60e9373f4f67d5d00698d70b75ffb7776f84e3875590f81342d712bac2a76a803c03152958f114fbff340dfb2bacb995ab92faaff49458480b8402b502ac46e80d2dea3f576715c8935cb2a4d5d9cf929f7a3d21aa9e1817d054ad39f47ca964b95ed62d1f11d52e7)
System: Chrome 125.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0092508-240506114902167
Window size: width 1745 - height 866
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-06-25T10:02:16.086Z',to:'2024-06-25T10:08:16.086Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-06-25T10:02:16.086Z',to:'2024-06-25T10:08:16.086Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by CecSve** [comment]
The user has been contacted through helpdesk with the following reply:

> You can access information about all the interpreted fields in an occurrence download in our technical documentation: https://techdocs.gbif.org/en/data-use/download-formats#dwca-interpreted.
> 
> If you search for the field in the table, you will find the following definition:
> 
> The number of individuals present at the time of the Occurrence.
> 
> So yes, this refers to the number of individuals that were recorded for the occurrence of the species. However, please be aware this field is not mandatory, so you may find that some of the 6 datasets that contributed to the download, does not contain any information in the field. Depending on what you use the data for, it may only be possible to analyse the date based on presence/absence.
