### ISSUE TITLE
allow search by guid

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#537]
**allow search by guid**

from http://dev.gbif.org/issues/browse/PF-2301?jql=project%20%3D%20PF%20AND%20status%20%3D%20Open

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c

System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/dataset/search?q=864eb98e-f762-11e1-a439-00145eb45e9a
Window size: width 1919 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T13:07:48.290Z',mode:absolute,to:'2017-10-05T13:13:48.290Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T13:07:48.290Z',mode:absolute,to:'2017-10-05T13:13:48.290Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
might make sense to have the key as a searchable keyword?
