### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5371]
**Download issue**

My download has not started yet. I have been waiting since 3:00 AM.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5eef298d2e49d427c96c143c9552612d:c08fbb354a6307a9037f9126f5aca306cfc812cb2d58d224d694eeb88953df5f9b4a70eef0f03cd46db4e4fe0d90dc2706e5e39cfe0a0a0f67dfcc4e9b5ee804c0f6bc0db6485b76259c87cf6b51fe47b01f41fa270768c29800436c43eb3998350ccfdc81827ee61423acdfb5e1ac3f7cb6b4638268e8599f82f2f6e43991a8486bf6c4f0f04428d888df52b76029b3) - [Send email](https://www.gbif.org/api/feedback/user/mailto/5eef298d2e49d427c96c143c9552612d:c08fbb354a6307a9037f9126f5aca306cfc812cb2d58d224d694eeb88953df5f9b4a70eef0f03cd46db4e4fe0d90dc2706e5e39cfe0a0a0f67dfcc4e9b5ee804c0f6bc0db6485b76259c87cf6b51fe47b01f41fa270768c29800436c43eb3998350ccfdc81827ee61423acdfb5e1ac3f7cb6b4638268e8599f82f2f6e43991a8486bf6c4f0f04428d888df52b76029b3)
System: Chrome 126.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0093741-240506114902167
Window size: width 1920 - height 991
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-06-25T22:13:05.958Z',to:'2024-06-25T22:19:05.958Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-06-25T22:13:05.958Z',to:'2024-06-25T22:19:05.958Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by CecSve** [comment]
The user has been contacted with the following message:

> I can see the download was cancelled. Did you manage to get another download to work? If not, I have made a download for you: https://www.gbif.org/occurrence/download/0002144-240626123714530.
Please be aware of the content of the download report for your query and pay attention to the flags and issues etc. in you downstreams analysis:
 
![billede](https://github.com/gbif/portal-feedback/assets/54532645/f81105dd-8834-49e9-9316-f86b8b6de4d7)
