### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5372]
**API key**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/2f2f062f7ea7317f711847b718d341e6:923f6683ef1013177f564507a2b3ed1fcb71c0d4a09c38118830a813fbf4a5216dd68bb9c17faeca5cd973017680eb2f016d97d0399b8ac1c990b558fa62db54a39583afc56a27e7a89a3002b42a4b06aa0d37b546553b18e77483c80ca91a2b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/2f2f062f7ea7317f711847b718d341e6:923f6683ef1013177f564507a2b3ed1fcb71c0d4a09c38118830a813fbf4a5216dd68bb9c17faeca5cd973017680eb2f016d97d0399b8ac1c990b558fa62db54a39583afc56a27e7a89a3002b42a4b06aa0d37b546553b18e77483c80ca91a2b)
System: Chrome 126.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 1643 - height 808
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-06-26T09:38:33.341Z',to:'2024-06-26T09:44:33.341Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-06-26T09:38:33.341Z',to:'2024-06-26T09:44:33.341Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
We have had many users now reaching out and asking to find this "API key", it is something that often comes from ChatGPT (which when asking for code using the GBIF occurrence API mentions an API key)

**Comment by ManonGros** [comment]
I replied by email

> You are welcome to check our API documentation here: https://techdocs.gbif.org/en/openapi/ as well as this [recorded webinar on how to use the GBIF API](https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa/data-use-club-practical-session-3-recording-and-resources).

**Comment by MortenHofft** [comment]
I wonder if the tech docs url `openapi` will confuse the user that apparently came from `openai` 😄
