### ISSUE TITLE
Use https:// for all examples on citation guidelines

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#538]
**Use https:// for all examples on citation guidelines**

I like the https://www.gbif.org/citation-guidelines document: citations are kept short and are easy to make. 👌

I would update the DOIs in the examples to make use of the new [display guidelines](https://www.crossref.org/display-guidelines/): `https://doi.org/10.xxxx/xxxxx`

In the citation guidelines that means updating:

* Occurrence download, use: `http://doi.org/10.15468/dl.ywhpmz`
* Individual checklist: already OK
* Custom data export, use: `https://doi.org/10.15468/cdl.xxxx`
* Species page, use: `https://doi.org/10.15468/39omei`

-----
fbitem-57ee03dd725ec36a7faf1f69bca70ff2ef3c507e
User provided contact info: peterdesmet
System: Chrome 60.0.3112 / Mac OS X 10.12.6
Referer: https://www.gbif.org/citation-guidelines
Window size: width 1282 - height 780
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T18:17:00.759Z',mode:absolute,to:'2017-10-05T18:23:00.759Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-05T18:17:00.759Z',mode:absolute,to:'2017-10-05T18:23:00.759Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by peterdesmet** [comment]
Citation guidelines have now been tweeted too, so maybe good time to correct: https://twitter.com/gbif/status/922451347802394624 😊

**Comment by kcopas** [comment]
Thanks, Peter. Duly noted, and updated.

**Comment by peterdesmet** [comment]
Hi @kcopas: is now corrected for Occurrence download, but for the last Custom + Species citations, which still use `doi:`
