### ISSUE TITLE
The coordinates are wrong, the specimen label

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5381]
**The coordinates are wrong, the specimen label**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/66adb8781607ec1a0808424d4a592c15:f2ce478d2f2936d9d360c3f893349e2178d9a11e699421d79b1edded13304352c2c24375d43e3357b96814636e3047ee5201d8071b00553a3a1eb0446a0fcbb7889254dffe9da3264a40ef148f1e468ddb758350008ec4a212dda3a47070d61189f0a7b671847ffdef493e107a942bbf482ba6ae40b7ce0c776c7a4e5eddbe64e24282dcb78db74cfb9f8c29e31b41d2) - [Send email](https://www.gbif.org/api/feedback/user/mailto/66adb8781607ec1a0808424d4a592c15:f2ce478d2f2936d9d360c3f893349e2178d9a11e699421d79b1edded13304352c2c24375d43e3357b96814636e3047ee5201d8071b00553a3a1eb0446a0fcbb7889254dffe9da3264a40ef148f1e468ddb758350008ec4a212dda3a47070d61189f0a7b671847ffdef493e107a942bbf482ba6ae40b7ce0c776c7a4e5eddbe64e24282dcb78db74cfb9f8c29e31b41d2)
System: Chrome 126.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1228403069
Window size: width 1536 - height 695
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-03T06:58:04.279Z',to:'2024-07-03T07:04:04.279Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-03T06:58:04.279Z',to:'2024-07-03T07:04:04.279Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO
datasetKey: 90c853e6-56bd-480b-8e8f-6285c3f8d42b
publishingOrgKey: 7b8aff00-a9f8-11d8-944b-b8a03c50a862

Node handles: @sformel-usgs

**Comment by MortenHofft** [comment]
closed in favour of https://github.com/gbif/portal-feedback/issues/5382
