### ISSUE TITLE
Allow to download original Camtrap DP dataset from dataset page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5383]
**Allow to download original Camtrap DP dataset from dataset page**

The `Download` button on occurrence dataset allow to download the original Archive from the IPT, e.g. https://www.gbif.org/dataset/74196cd9-7ebc-4b20-bc27-3c2d22e31ed7

That option is currently missing for Camtrap DP datasets, while it is especially important there, since the original dataset contains data in a richer format than GBIF provides.

-----

Github user: @peterdesmet
User: [See in registry](https://www.gbif.org/api/feedback/user/7e3582fd41c45b751c7e5195e1e24a2a:515c1c0e2ac28f454012be4c30bbf2fed3a015b7cd985d91a2745086c3b6a80c819e42b171d6c8c43e64c7a1b1c06e49582322a5cfaab1762fa671974f548b3cd3e35af1b1f25418e69a67a54a90f2074fda6eef4ffd4b25ad47588da9ba62cfd310db11d37418e7be7f584182eae322285c84867e63362d25c88627ceae39e6663d7a45433e1cf6b0ad5545768191ce) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7e3582fd41c45b751c7e5195e1e24a2a:515c1c0e2ac28f454012be4c30bbf2fed3a015b7cd985d91a2745086c3b6a80c819e42b171d6c8c43e64c7a1b1c06e49582322a5cfaab1762fa671974f548b3cd3e35af1b1f25418e69a67a54a90f2074fda6eef4ffd4b25ad47588da9ba62cfd310db11d37418e7be7f584182eae322285c84867e63362d25c88627ceae39e6663d7a45433e1cf6b0ad5545768191ce)
System: Chrome 126.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/74196cd9-7ebc-4b20-bc27-3c2d22e31ed7
Window size: width 1366 - height 743
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-04T14:13:07.534Z',to:'2024-07-04T14:19:07.534Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-04T14:13:07.534Z',to:'2024-07-04T14:19:07.534Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by peterdesmet** [comment]
Compare [Occurrence dataset](https://www.gbif.org/dataset/9a0b66df-7535-4f28-9f4e-5bc11b8b096c):

<img width="280" alt="Screenshot 2024-07-04 at 16 16 15" src="https://github.com/gbif/portal-feedback/assets/600993/3d05983f-7f11-4afb-955f-e514860030f5">

With [Camtrap DP dataset](https://www.gbif.org/dataset/74196cd9-7ebc-4b20-bc27-3c2d22e31ed7):

<img width="279" alt="Screenshot 2024-07-04 at 16 14 57" src="https://github.com/gbif/portal-feedback/assets/600993/fb917a9c-dac3-481f-a976-a517b9701d92">

Please add:

> **Source archive** Camera Trap Data Package

In the middle

**Comment by MortenHofft** [comment]
I'ave added it. It will be available in next deployment
