### ISSUE TITLE
Typo in title ("continenal")

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5386]
**Typo in title (&quot;continenal&quot;)**

-----

Github user: @ahahn-gbif
User: [See in registry](https://www.gbif.org/api/feedback/user/abcb9504e2c3cf8c89b6ccd21e6d5e5e:4586d978d993cdf8bdd0a4d1d1ec4589e660062678e7d3f58e9ce96edf8a1ab136439ff74d2bf49dab9a59bb11a2ffa86a1382d6ee8c02ded5d87dec02317ebbdd7914814b64810d8b270bf306f69d54e2230cfc74659e96bc6833378858c85e2369ce2b52ce5274df320d42367804f8414569b7ee414055f61eae9ff7359566) - [Send email](https://www.gbif.org/api/feedback/user/mailto/abcb9504e2c3cf8c89b6ccd21e6d5e5e:4586d978d993cdf8bdd0a4d1d1ec4589e660062678e7d3f58e9ce96edf8a1ab136439ff74d2bf49dab9a59bb11a2ffa86a1382d6ee8c02ded5d87dec02317ebbdd7914814b64810d8b270bf306f69d54e2230cfc74659e96bc6833378858c85e2369ce2b52ce5274df320d42367804f8414569b7ee414055f61eae9ff7359566)
System: Firefox 128.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/data-use/3l69bW44dwiCW5B9Awe2Aa/global-continenal-and-biome-scale-tree-species-census
Window size: width 1485 - height 584
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-10T06:10:15.895Z',to:'2024-07-10T06:16:15.895Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-10T06:10:15.895Z',to:'2024-07-10T06:16:15.895Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by dnoesgaard** [comment]
corrected
