### ISSUE TITLE
Ability to download occurrences using a given download DOI

### ISSUE THREAD

**Issue by laurabrenskelle** [gbif/portal-feedback#5389]
Hello! It is possible this capability exists and I am misunderstanding something in the API or rgbif documentation. Is there a way to use a download DOI (example: https://doi.org/10.15468/dl.vwcmx2) to download all of the occurrences associated with the DOI in an automated way without having to go to the website and download them manually?

If not, can this capability be added?

Thank you!

**Comment by MattBlissett** [comment]
Very quickly as I'm about to leave the office:

1. http://api.gbif.org/v1/occurrence/download/10.15468/dl.vwcmx2
2. see the downloadLink, https://api.gbif.org/v1/occurrence/download/request/0020688-240626123714530.zip

**Comment by jhnwllr** [comment]
It isn't yet possible to do in rgbif.

I have added an issue about it. 

You can use the download id however. 
```r
occ_download_get("0020688-240626123714530") %>% 
occ_download_import()
```

**Comment by laurabrenskelle** [comment]
Thank you, @jhnwllr! That is the functionality I was looking for.
