### ISSUE TITLE
Inquiry about BIFA Funding for Biodiversity and Carbon Stock Monitoring Project

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5390]
**Inquiry about BIFA Funding for Biodiversity and Carbon Stock Monitoring Project**

Dear Mr./Madam,

I am Nguyen Manh Duc, a representative of the project titled "Biodiversity and Carbon Stock Monitoring in Vietnam Forests Based on Remotely Sensed Spectral Diversity" writing to inquire about the possibility of securing funding for our project through the Biodiversity Information Fund for Asia (BIFA).

Here is our brief of the motivation and how we can acheieve our target of this project
Project Overview:

Vietnam, grappling with severe air pollution and deforestation, requires efficient carbon stock assessment. This project aims to develop a robust model using satellite and UAV imagery, combined with deep learning techniques, to accurately estimate forest canopy height, biodiversity, and carbon stocks. By optimizing carbon stock assessment, we contribute to effective climate change mitigation strategies.

Project Objectives:

Develop a deep learning model to accurately estimate forest canopy height using satellite and UAV data.
Employ classification and segmentation models to assess forest biodiversity.
Create a model to estimate carbon stocks based on satellite and UAV data.
By leveraging advanced remote sensing techniques, we aim to contribute significantly to biodiversity conservation and carbon sequestration efforts in Vietnam.

We are particularly interested in learning more about the application process, eligibility criteria, and deadlines for the BIFA fund. Your guidance on these matters would be invaluable to us as we explore potential funding opportunities for our project.

Thank you for your time and consideration. We look forward to hearing from you soon.

Sincerely,
Duc

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6a0dcc1d0ed07130b2dcd15a62dc8d6d:fe6e6417828c8f76a88c8587e6b56f2c290c638425ce5f6044c97d5291bfab12c1f9952ab60726558ee0e5c8a8d6d3cb67174d60bbce7a85b0552263f982f4f2c8e9c3d87d374f3c810d86fc2714652acf87102a8bc6505789c75e816c2944cce47cb15e22a7b766f8d39c09668bc4ad7df43ee86074a0658f9f9b858ddc64fe0efeda7c6986f19f3620aff5322eef15b84491d701b36223f3e72938cc9a6ce1) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6a0dcc1d0ed07130b2dcd15a62dc8d6d:fe6e6417828c8f76a88c8587e6b56f2c290c638425ce5f6044c97d5291bfab12c1f9952ab60726558ee0e5c8a8d6d3cb67174d60bbce7a85b0552263f982f4f2c8e9c3d87d374f3c810d86fc2714652acf87102a8bc6505789c75e816c2944cce47cb15e22a7b766f8d39c09668bc4ad7df43ee86074a0658f9f9b858ddc64fe0efeda7c6986f19f3620aff5322eef15b84491d701b36223f3e72938cc9a6ce1)
System: Chrome 126.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1536 - height 730
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-17T03:49:39.735Z',to:'2024-07-17T03:55:39.735Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-17T03:49:39.735Z',to:'2024-07-17T03:55:39.735Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
@ckotwn replied by email

> Thank you for your inquiry about BIFA. Unfortunately, the Programme concluded its funding round in late 2022.

> However, the GBIF Asia Regional Support Team (asia_support@gbif.org) is available if you need any support regarding sharing or using GBIF-mediated data.
