### ISSUE TITLE
Good morning, the button MULTIMEDIA to filter the type of media, is no more present.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5395]
**Good morning, the button MULTIMEDIA to filter the type of media, is no more present.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7f9994e4ba90716c4d5d06fd08e72b45:79f33feffe33823b3222dbdd7e3c559c6c28095ce8d2c2e83b87ca4fa6421c514ae96fb3e09c7ae755d7d080fda39069c37f2dc7d087749d70b7f276860e7bd9c87eda9eaecc4c686806cd3d53463324e789ae92146226cdec2984e322fb90c5) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7f9994e4ba90716c4d5d06fd08e72b45:79f33feffe33823b3222dbdd7e3c559c6c28095ce8d2c2e83b87ca4fa6421c514ae96fb3e09c7ae755d7d080fda39069c37f2dc7d087749d70b7f276860e7bd9c87eda9eaecc4c686806cd3d53463324e789ae92146226cdec2984e322fb90c5)
System: Chrome 126.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search
Window size: width 1536 - height 695
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-23T08:42:04.392Z',to:'2024-07-23T08:48:04.392Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-23T08:42:04.392Z',to:'2024-07-23T08:48:04.392Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
It is there
You need to go see all filters first. it is called "media type"
It isn't a frequently used filter

hope that helps

https://www.gbif.org/occurrence/search?media_type=StillImage&media_type=MovingImage&media_type=Sound&advanced=1

> user notified by email
