### ISSUE TITLE
DMNS images not displaying

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5398]
**DMNS images not displaying**

For our collections using Arctos, many (but not all) of our media images are not displaying on the GBIF site. (eg, https://www.gbif.org/occurrence/gallery?media_type=StillImage&publishing_org=a2ef6dd1-8886-48c9-8025-c62bac973cc7&taxon_key=359&advanced=1). Can you tell if this is an issue with our images, something wrong with the data Arctos is passing along, or something internal to GBIF? Please let me know what you can find.
Everything from our collections in Ecdysis appear to be displaying here fine. 
Thanks!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/4b569f2228504f638caed0eaa161a0fb:0288d136c9ceface2a0628e233625fba1fa277202b44efcb47f19d86b2c00f2d82c5b018fb1b8d6d8de15adf885403b5313f59e49097dda941472d68aee3c43bab2310a2a8eaad9b01e86737aa3e1c579549c26b879015955b5c51d4f5f06236863001e68fc62cc0aa0c18937b10fc97e2277e0bf6509293b2ff0fc8d3fe5066713a15423286a66de5ca0e7550cffab2) - [Send email](https://www.gbif.org/api/feedback/user/mailto/4b569f2228504f638caed0eaa161a0fb:0288d136c9ceface2a0628e233625fba1fa277202b44efcb47f19d86b2c00f2d82c5b018fb1b8d6d8de15adf885403b5313f59e49097dda941472d68aee3c43bab2310a2a8eaad9b01e86737aa3e1c579549c26b879015955b5c51d4f5f06236863001e68fc62cc0aa0c18937b10fc97e2277e0bf6509293b2ff0fc8d3fe5066713a15423286a66de5ca0e7550cffab2)
System: Chrome 126.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/gallery?media_type=StillImage&publishing_org=8edbbde0-055e-11d8-b850-b8a03c50a862&advanced=1
Window size: width 2560 - height 1271
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-24T15:57:06.668Z',to:'2024-07-24T16:03:06.668Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-24T15:57:06.668Z',to:'2024-07-24T16:03:06.668Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: INFO
datasetKey: d762b508-7a70-441b-94ad-48fd77593275
publishingOrgKey: a2ef6dd1-8886-48c9-8025-c62bac973cc7

Node handles: @sformel-usgs

**Comment by MattBlissett** [comment]
Fixed by upgrading our SSL version.
