### ISSUE TITLE
Is there any sound data for this record that can be queried?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5399]
**Is there any sound data for this record that can be queried?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/66ddd27043a5436889b462035aba087e:e737cb2886d872a693783ce215075e086a1acc447a3a032c151d953b36a9244334cd954474958ccb920beb77a304e22c4e24a8f7b30661e545512cfe8ed0177c2d6d2716efc0f121a4326c3aca98423ba27de8df6772edf3d87f5b0f55412298) - [Send email](https://www.gbif.org/api/feedback/user/mailto/66ddd27043a5436889b462035aba087e:e737cb2886d872a693783ce215075e086a1acc447a3a032c151d953b36a9244334cd954474958ccb920beb77a304e22c4e24a8f7b30661e545512cfe8ed0177c2d6d2716efc0f121a4326c3aca98423ba27de8df6772edf3d87f5b0f55412298)
System: Chrome 126.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/3548776987
Window size: width 1482 - height 746
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-26T05:28:05.741Z',to:'2024-07-26T05:34:05.741Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-26T05:28:05.741Z',to:'2024-07-26T05:34:05.741Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 4fa7b334-ce0d-4e88-aaae-2e0c138d049e
publishingOrgKey: e2e717bf-551a-4917-bdc9-4fa0f342c530

Node handles: @sformel-usgs

**Comment by jhnwllr** [comment]
@sformel-usgs
 This question was answered on helpdesk. 
 
 There doesn't appear to be any sound data published for this record. 
 
 To search for sound data for this species, use this search: 
 https://www.gbif.org/occurrence/search?media_type=Sound&taxon_key=2493054&advanced=1
