### ISSUE TITLE
I have downloaded data for use in two publications. I've downloaded different species on different dates. I have copied the citation information, but I wanted to know if the citation can apply to multiple downloads performed over time. Thank you, Karen Blevins

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5400]
**I have downloaded data for use in two publications. I&#39;ve downloaded different species on different dates. I have copied the citation information, but I wanted to know if the citation can apply to multiple downloads performed over time. Thank you, Karen Blevins**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/012169cc664c956c093d7062d8bd1f30:377d3379ddd4463647960c8a5453ea3380525dee6754569bed942897c0419ec1e1cd9690e6f1f56aacfda82138a25b3b8d005eaebcbb2fa02bc238a6930a6c24fe24f7e3eb4c1c9b6853287c72c33e43fe373682f9413800139e984b857d3823) - [Send email](https://www.gbif.org/api/feedback/user/mailto/012169cc664c956c093d7062d8bd1f30:377d3379ddd4463647960c8a5453ea3380525dee6754569bed942897c0419ec1e1cd9690e6f1f56aacfda82138a25b3b8d005eaebcbb2fa02bc238a6930a6c24fe24f7e3eb4c1c9b6853287c72c33e43fe373682f9413800139e984b857d3823)
System: Chrome 126.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0038595-240626123714530
Window size: width 1920 - height 919
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-27T02:49:40.126Z',to:'2024-07-27T02:55:40.126Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-27T02:49:40.126Z',to:'2024-07-27T02:55:40.126Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email

> If you generated multiple downloads, you have several options. You could cite each download separately.
You could also consider creating a [derived dataset](https://www.gbif.org/citation-guidelines#derivedDatasets). You will need to first put the data you would like to cite online (for example on [Zenodo](https://zenodo.org/)),  then register it here: https://www.gbif.org/derived-dataset/register (see also [this blog post](https://data-blog.gbif.org/post/derived-datasets/)).
This will create one DOI that you can cite and will credit back the data publisher whose data contributed to your work.
