### ISSUE TITLE
IPT ingestion

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5402]
**IPT ingestion**

Dear Helpdesk colleagues, 

i have encountered an old problem with occurrenceID change i guess,

because my dataset doesn't ingested after update in IPT,

please would you be kind to look and push it to be ingested: 
https://www.gbif.org/dataset/8e227d53-5f48-4faf-9c74-29eefb305684

now i made everything right with occurrence IDs (there are two related tables, an occurrenceID and DNA-derived table).

Nina

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e82a33ece40733a00940d20a33f80713:b51032524f16ca2d19d303f7ba07db806f353058c96bb7f35d2e221cdce9613d0fea40762454f9ba2e47bed460150ccb89d1ee265f13b2f835311b5887c298b2041f3c6a4e07b190af59ff0331388769161f97624ee3814ce43920f07f51d76d529ffe2428c963c943a868effd1bc0efb96ef71db0c68dcfa36356ed7d5f77ca309e05dd6c922c1351a20602843f465e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/e82a33ece40733a00940d20a33f80713:b51032524f16ca2d19d303f7ba07db806f353058c96bb7f35d2e221cdce9613d0fea40762454f9ba2e47bed460150ccb89d1ee265f13b2f835311b5887c298b2041f3c6a4e07b190af59ff0331388769161f97624ee3814ce43920f07f51d76d529ffe2428c963c943a868effd1bc0efb96ef71db0c68dcfa36356ed7d5f77ca309e05dd6c922c1351a20602843f465e)
System: Chrome 127.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/8e227d53-5f48-4faf-9c74-29eefb305684
Window size: width 2560 - height 1270
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-29T05:10:49.939Z',to:'2024-07-29T05:16:49.939Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-29T05:10:49.939Z',to:'2024-07-29T05:16:49.939Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This seems to have been resolved here: https://github.com/gbif/ingestion-management/issues/1462
