### ISSUE TITLE
Sequence ID tool not working

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5403]
**Sequence ID tool not working**

Hi, I love your Seq ID tool, very fast! However its not working now, just times out and then says no matches, no matter how many sequences I try. I'm trying the BOLD COI matching, but haven't tried the other genes. Please fix asap - this tool is too useful!

Cheers,
Ben

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/cafb01bd9c5e948f4df22e8e7bb0c6ec:488fa0791be30c08d4605a2ea20bbe32aef91bb72ea8d34cdc11af8871fecd0cd46e6332a1754a94475afd66dbd0b99ad4885b50d4c80db03d36b35af313f0cab4bbc04aa860be378e3cc7ff05a34e57d49d986a5ba629cd0319f9b00a6d83e2fecb6ca0ffed5e1941cd6f709ef68eee5966eadaf9332bc4e593126503acd89cecde80ba6a0ffcef61848de0874ce6c4) - [Send email](https://www.gbif.org/api/feedback/user/mailto/cafb01bd9c5e948f4df22e8e7bb0c6ec:488fa0791be30c08d4605a2ea20bbe32aef91bb72ea8d34cdc11af8871fecd0cd46e6332a1754a94475afd66dbd0b99ad4885b50d4c80db03d36b35af313f0cab4bbc04aa860be378e3cc7ff05a34e57d49d986a5ba629cd0319f9b00a6d83e2fecb6ca0ffed5e1941cd6f709ef68eee5966eadaf9332bc4e593126503acd89cecde80ba6a0ffcef61848de0874ce6c4)
System: Chrome 126.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=sequence
Window size: width 1386 - height 743
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-30T20:25:39.900Z',to:'2024-07-30T20:31:39.900Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-07-30T20:25:39.900Z',to:'2024-07-30T20:31:39.900Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email that the Seq ID tool is now working again.
