### ISSUE TITLE
Data validator issue

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5407]
**Data validator issue**

I used data validator tool but I don't know how to fix my issue on dates and on occurrence status.
The tool says my obersvation date is incorrect but I've checked and it is correct! Also I have an "Occurrence status inferred from individual count" issue that I don't understand.

Thanks for your help.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d299ffd481be5b4404cf715eaafc62b5:b19c0b881551f58a85560cd964958a09c8df97b243a3dddeb4d103910c6951ac4961f42006c68dcd61436be906bdbdcfa1449bab0100d827203594a136ce57d58343e6fbe5e119a13a67eda45b4ca3119807d857485fa5d409c21bebba62d124a549eea8041aad4009f6f019b9f5e21a77c755f11014b1f91e35c4bfea0990c202f46f6cc0fe4c151287200944c7f20d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d299ffd481be5b4404cf715eaafc62b5:b19c0b881551f58a85560cd964958a09c8df97b243a3dddeb4d103910c6951ac4961f42006c68dcd61436be906bdbdcfa1449bab0100d827203594a136ce57d58343e6fbe5e119a13a67eda45b4ca3119807d857485fa5d409c21bebba62d124a549eea8041aad4009f6f019b9f5e21a77c755f11014b1f91e35c4bfea0990c202f46f6cc0fe4c151287200944c7f20d)
System: Chrome 127.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?q=date
Window size: width 2549 - height 1229
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-01T08:04:15.685Z',to:'2024-08-01T08:10:15.685Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-01T08:04:15.685Z',to:'2024-08-01T08:10:15.685Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Most of GBIF flags and issues are documented here: https://techdocs.gbif.org/en/data-use/occurrence-issues-and-flags.
Generally, the dates are often flagged as invalid when their format don’t follow the ISO standards (YYYY-MM-DD, for example 2024-08-01 for the first of August 2024). Could this be the case for your dataset?

The flag "Occurrence status inferred from individual count" is more a warning than an issue. It means that no [occurrenceStatus](https://dwc.tdwg.org/terms/#dwc:occurrenceStatus) was provided and that our system inferred whether the species was present or absent based on the value in the [individualCount](https://dwc.tdwg.org/terms/#dwc:individualCount) field.

> Replied by email
