### ISSUE TITLE
white logo of publisher not visible on GRSciColl web portal

### ISSUE THREAD

**Issue by spalp** [gbif/portal-feedback#5409]
I assume that the [logo](https://pmf.unsa.ba/eng/wp-content/uploads/2023/08/faculty-of-science-sarajevo-eng-logo-white.png) of the following [publisher](https://scientific-collections.gbif.org/institution/49efc929-ebe7-419d-8d0c-e22d984c30a8) is not visible on GRSciColl because it is white. I could not find an alternative (non-white) logo on their website. 

Can white logos be displayed on GRSciColl without changing the background (a non-white background would probably look odd)?

@ManonGros

**Comment by MattBlissett** [comment]
How about https://pmf.unsa.ba/eng/wp-content/uploads/2023/08/faculty-of-science-sarajevo-eng-logo-color.png ?

**Comment by spalp** [comment]
Wow, great. I tried replacing 'white' with 'black' but that didn't work. Silly me. 
Thanks for the solution. I will update now the address of the logo in the registry.

**Comment by ManonGros** [comment]
Thanks Matt! I am closing the issue. Let me know if it should be reopened Slaza
