### ISSUE TITLE
Add crawl button for certain users

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#541]
**Add crawl button for certain users**

How about if the logged in user has the same email address as any contact associated with the dataset, the owning or hosting institution or the node, or the use is an ADMIN or REGISTRY_EDITOR we add a crawl button on the site directly?

-----
fbitem-dataset38b4c89f-584c-41bb-bd8f-cd1def33e92f
User provided contact info: @timrobertson100
System: Chrome 61.0.3163 / Mac OS X 10.11.5
Referer: https://www.gbif.org/dataset/38b4c89f-584c-41bb-bd8f-cd1def33e92f
Window size: width 1251 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-07T08:47:23.824Z',mode:absolute,to:'2017-10-07T08:53:23.824Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-07T08:47:23.824Z',mode:absolute,to:'2017-10-07T08:53:23.824Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
roles are not exposed in the API. Is this something that you could add @cgendreau ?

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/7150b692901583d254b58c7a5f16f04c320d0075
