### ISSUE TITLE
Download for Aves query does not come with multimedia.txt file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5411]
**Download for Aves query does not come with multimedia.txt file**

I have setup a query that has associated images (checked in the User Interface). When I download I don't get the multimedia file with links despite asking for it.
Example: https://doi.org/10.15468/dl.mx6zcq

It works for mammals but the same query for Aves does not work for me.

Can you help?

Matthieu

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/04e16fc1ae25fb29d3f74d0a35eb1f71:dddf9a512110852971f694bf66dd1418963903bb2aa7c2c1355293e9e357e075a4fa85799f1b72997583a820767d5cdd97471da38bb21f84e1092718246cafc009efcb131df189ef14967291a394f1027cf7de908fdb00aaa0d2c477151650a52d4bd40453a23cac86767fc9f1f7bb9c51deff8337b291ea71876a2a3e4a0920) - [Send email](https://www.gbif.org/api/feedback/user/mailto/04e16fc1ae25fb29d3f74d0a35eb1f71:dddf9a512110852971f694bf66dd1418963903bb2aa7c2c1355293e9e357e075a4fa85799f1b72997583a820767d5cdd97471da38bb21f84e1092718246cafc009efcb131df189ef14967291a394f1027cf7de908fdb00aaa0d2c477151650a52d4bd40453a23cac86767fc9f1f7bb9c51deff8337b291ea71876a2a3e4a0920)
System: Safari 17.5.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/0047600-240626123714530
Window size: width 2480 - height 1284
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-04T16:46:31.986Z',to:'2024-08-04T16:52:31.986Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-04T16:46:31.986Z',to:'2024-08-04T16:52:31.986Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It is true, the DWCA doesn't contain any multimedia extension. Is that expected?
Maybe @MattBlissett can take a look?

**Comment by MattBlissett** [comment]
I see the multimedia.txt extension file:

```
unzip -l 0046690-240626123714530.zip
Archive:  0046690-240626123714530.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      125  2024-08-03 14:43   rights.txt
      307  2024-08-03 14:43   citations.txt
    55098  2024-08-03 14:43   dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7.xml
     3142  2024-08-03 14:43   metadata.xml
    33568  2024-08-03 14:43   meta.xml
22334836638  2024-08-03 14:43   occurrence.txt
13427430770  2024-08-03 14:44   verbatim.txt
7799559942  2024-08-03 14:44   multimedia.txt
---------                     -------
43561919590                     8 files
```

And the data looks to be valid.

**Comment by ManonGros** [comment]
how can it be? When I download and unzip the archive on my Mac, I don't see it:
<img width="716" alt="Screenshot 2024-08-21 at 09 38 14" src="https://github.com/user-attachments/assets/cdec70aa-1cef-4b41-909a-ec93cc8721d6">

**Comment by ManonGros** [comment]
Unzipping with command lines works and I am able to get the multimedia file. The problem is only for UI tools.

**Comment by ManonGros** [comment]
I contacted the user to let them know.
