### ISSUE TITLE
UAT webpage only shows one occurrence

### ISSUE THREAD

**Issue by vechocho** [gbif/portal-feedback#5416]
We use the UAT gbif page to test the datasets before movint to production, 

we just published two dataset 

https://www.gbif-uat.org/dataset/2fc52a91-be46-4be6-b42a-0b0d512f4974
https://www.gbif-uat.org/dataset/ca8147d7-d2c2-4e01-8049-1e4d57046f13

when we click on any occurrence inside the dataset the one that shows is this one https://www.gbif-uat.org/occurrence/34832754

**Comment by fmendezh** [comment]
we couldn't replicate the issue, the portal shows individual occurrence pages correctly

**Comment by vechocho** [comment]
https://github.com/user-attachments/assets/64dc3fb7-06d0-4830-884c-f4fc577af8f9

@djtfmartin te adjunto un video, o no sé si es un tema con mi equipo, siempre me sale esa observación de Reino Unido.

**Comment by MattBlissett** [comment]
These are different occurrences (it isn't https://www.gbif-uat.org/occurrence/34832754 every time) but they are not the correct occurrences.

**Comment by muttcg** [comment]
Recreated indices. Fixed
