### ISSUE TITLE
Certainly not Polygonia gracilis at this location. I disagreed with the ID on eButterfly, but it seems that does nothing and is still considered "research grade"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5418]
**Certainly not Polygonia gracilis at this location. I disagreed with the ID on eButterfly, but it seems that does nothing and is still considered &quot;research grade&quot;**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/8e60ba6c0fb0d2d53355809a83eb6242:32d92569ab04bf0a6a0251c64d285833b14aa236328b52339ac8a9f62bb45ef23ca4d0bf0848ca6cc8043f970a5523fce5eff5ccdf2e1cb1638b925c8088cf76985e545eaeea53b4a644cbd91f57e2f58d5a50a20947011a37e4df5da9a54a53) - [Send email](https://www.gbif.org/api/feedback/user/mailto/8e60ba6c0fb0d2d53355809a83eb6242:32d92569ab04bf0a6a0251c64d285833b14aa236328b52339ac8a9f62bb45ef23ca4d0bf0848ca6cc8043f970a5523fce5eff5ccdf2e1cb1638b925c8088cf76985e545eaeea53b4a644cbd91f57e2f58d5a50a20947011a37e4df5da9a54a53)
System: Chrome Mobile 127.0.0 / Android 0.0.0
Referer: https://www.gbif.org/occurrence/3397366524
Window size: width 384 - height 693
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-07T19:07:18.970Z',to:'2024-08-07T19:13:18.970Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-07T19:07:18.970Z',to:'2024-08-07T19:13:18.970Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: cf3bdc30-370c-48d3-8fff-b587a39d72d6
publishingOrgKey: b6d09100-919d-4026-b35b-22be3dae7156

Node handles: @sformel-usgs

**Comment by sformel-usgs** [comment]
Reached out to Kent McFarland and the OP via email. Will update when resolved.

**Comment by kpmcfarland** [comment]
This has been addressed. There were not enough ID votes to overturn that record to the genus level. There are now and it will update tomorrow as it updates at GBIF automatically every 24 hours. Thanks.

**Comment by sformel-usgs** [comment]
@ManonGros you should be able to close this once that update is reflected.
