### ISSUE TITLE
Downloaded CSV unreadable

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5421]
**Downloaded CSV unreadable**

I have downloaded occurrence data as a CSV, and it is tab delimited as I expect, but the some datapoints are across multiple or different columns so I can't use the text to columns function on the data.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b7137c0e0dc702699d8775a866e5602c:7546242652e39a50b7b69fad2dfdfea9bde31f85aecc26cb3b3d06f60aa53a9192f8c94ab67fa0ff15a064c42148a3ac12077d4a6257abde461d9970efe413c2f53a2bed9a72feee770eec2640b2a4646fb74e0483782ec0e2ae2295c4945d26) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b7137c0e0dc702699d8775a866e5602c:7546242652e39a50b7b69fad2dfdfea9bde31f85aecc26cb3b3d06f60aa53a9192f8c94ab67fa0ff15a064c42148a3ac12077d4a6257abde461d9970efe413c2f53a2bed9a72feee770eec2640b2a4646fb74e0483782ec0e2ae2295c4945d26)
System: Chrome 122.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0061132-240626123714530
Window size: width 1920 - height 919
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-13T00:38:00.237Z',to:'2024-08-13T00:44:00.237Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-13T00:38:00.237Z',to:'2024-08-13T00:44:00.237Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
As far as I can tell, the file looks fine. I have emailed the user to check which program they use to open it.
