### ISSUE TITLE
Searching datasets with IPT url using the API

### ISSUE THREAD

**Issue by cyrilrader** [gbif/portal-feedback#5422]
Hello,

I want to search for datasets by their IPT url using the API. I've noticed that the IPT url of a dataset is present in the 'endpoints' part of the result dictionary. The problem is that I don't see any argument in the API that could allow me to search for datasets with an IPT url. I've tried to do it with the full text search ('q' argument), but it didn't work. For now, I'm using the python package (pygbif) to call the API, but I don't mind using something else if it allows me to make this search.

Here are the calls I made when I tried to use the full text search:
'''
search_result=datasets(uuid='48c5c83b-2029-4b2c-9f48-5e610e6984d6',limit=1)
for elem in search_result['endpoints']:
    if elem['type']=='DWC_ARCHIVE':
        IPT_url=elem['url']
print(IPT_url)
print(datasets(query=IPT_url,limit=1))
'''

Here is a screenshot of the output:
![image](https://github.com/user-attachments/assets/480dd642-f34f-48bd-9d54-f515b62b021e)

Do you think you can help me with this issue ?

Thanks!

**Comment by ManonGros** [comment]
Hi @cyrilrader,

would it make sense to first query the installations and then use it to find the datasets?
for example: https://api.gbif.org/v1/installation?type=IPT_INSTALLATION&q=data.canadensys returns `4ce0e33d-ff23-4a00-9f6c-09b231eb0118` which you can use to query all the datasets: https://api.gbif.org/v1/installation/4ce0e33d-ff23-4a00-9f6c-09b231eb0118/dataset?limit=300

**Comment by cyrilrader** [comment]
Hi @ManonGros !

Hum... Maybe I could do it like this. This dataset was just an example, I will need to search for datasets that have other IPT installation than this one. So, it would be easier if I could directly search with the IPT resource. But if it's not possible then I think I can apply the logic you gave me and use it as a workaround.

**Comment by cyrilrader** [comment]
Hi @ManonGros 

I was investigating on how to include your workaround in my pipeline, but I have an issue. Since I have multiple IPT installation, the first step is to identify those installations, but I need a robust way to search for it. Since the only information I have about those installations is the IPT url, I tried to search with different parts of those url but I can't find the installation.

As an example, here are another IPT urls, "http://gp.sea.gov.ua:8082/ipt/resource?r=npmsuaaugust2017_phytoplankton" and "https://www.dassh.ac.uk/ipt/resource?r=cefas_02". I've found the installations of those urls by looking manually on the webpage:
![image](https://github.com/user-attachments/assets/379aa8ad-917f-4e95-9255-ce7ef44bf110)
![image](https://github.com/user-attachments/assets/7ceee210-d3db-4a2d-b909-91b44f9faca5)

I could retrieve that information from the webpage with python, but this field is not filled every time, so I need a better way to look for the installations.

I tried to search with the API for those installations with the part of the url in the endpoints field (cf links below), but it didn't find anything.
https://www.gbif.org/installation/98b255e0-2073-4e96-9d13-74833fdfa521
https://www.gbif.org/installation/b968184d-9a9f-4e9b-b035-caaf09f46db5

Do you have any idea on how I could solve this issue? 

Thanks!

**Comment by mike-podolskiy90** [comment]
New IPTs (2.7+) has a link containing their installation key at their about page (e.g. https://ipt.gbif-uat.org/about.do)

**Comment by mike-podolskiy90** [comment]
Also, there's RSS feed https://ipt.gbif-uat.org/rss.do (`ipt:identifier`)

**Comment by cyrilrader** [comment]
Thanks for all your help and answers!
I manage to make the script I wanted, so you can close this ticket if you want.
