### ISSUE TITLE
Allow download of backbone

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#543]
**Allow download of backbone**

The latest GBIF Backbone is freely available from http://rs.gbif.org/datasets/backbone/backbone-current.zip as a DwC-A or in other formats from http://rs.gbif.org/datasets/backbone/readme.html

Show the download link in portals download tab

-----
fbitem-datasetd7dddbf4-2cf0-4f39-9b2a-bb099caae36c

System: Chrome 61.0.3163 / Mac OS X 10.12.6
Referer: https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
Window size: width 1680 - height 888
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-09T07:37:29.580Z',mode:absolute,to:'2017-10-09T07:43:29.580Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-09T07:37:29.580Z',mode:absolute,to:'2017-10-09T07:43:29.580Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
the backbone is marked as having an unspecified license in the API. We do not promote downloading of datasets that doesn't have a proper license.
