### ISSUE TITLE
Crawler fails due to unknown/untrusted certificate

### ISSUE THREAD

**Issue by CecSve** [gbif/portal-feedback#5441]
This [dataset](https://www.gbif.org/dataset/0c235cd8-26cb-4b12-9f2f-a97fdb716957) cannot be ingested and the issue seems to be because the certificate of the website is not from a trusted source.

**Comment by muttcg** [comment]
Crawler can't download the file cause:
```
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
SSL verify error:
```
~ % openssl s_client -connect fgbggbn.lbg.lasy.gov.pl:443 -showcerts
Connecting to 80.54.190.149
CONNECTED(00000005)
depth=0 CN=fgbggbn.lbg.lasy.gov.pl
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN=fgbggbn.lbg.lasy.gov.pl
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN=fgbggbn.lbg.lasy.gov.pl
verify return:1
```

At the same time, my own Chrome and curl work without any issues, but CLI curl throws:

```
curl: (60) Peer's Certificate issuer is not recognized.
More details here: http://curl.haxx.se/docs/sslcerts.html
```

@MattBlissett maybe we need to get new list of certificates or so?

**Comment by muttcg** [comment]
Publisher fixed certificate

**Comment by MattBlissett** [comment]
For SSL/TLS issues, first do the checks here: https://ipt.gbif.org/manual/en/ipt/latest/faq#why-is-gbif-unable-to-access-my-ipt-over-https
