### ISSUE TITLE
how can i delete my account?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5445]
**how can i delete my account?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/0304106c4c8c56e3cf8c4a75319f19c4:c1614f258b93ac1d89c73a3ff672b17a4999d919163f71365a731245c0ba7653e3409b7b85fe53e5bd443b3ee273027bc0216b49c94da7d8905f55c0fb4903b498b5fd14a7b2676a453ae8a89207f914b843ba8d4f4871a5b9330c129df18406) - [Send email](https://www.gbif.org/api/feedback/user/mailto/0304106c4c8c56e3cf8c4a75319f19c4:c1614f258b93ac1d89c73a3ff672b17a4999d919163f71365a731245c0ba7653e3409b7b85fe53e5bd443b3ee273027bc0216b49c94da7d8905f55c0fb4903b498b5fd14a7b2676a453ae8a89207f914b843ba8d4f4871a5b9330c129df18406)
System: Chrome 128.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/zh/user/profile
Window size: width 1707 - height 791
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-02T08:18:35.520Z',to:'2024-09-02T08:24:35.520Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-02T08:18:35.520Z',to:'2024-09-02T08:24:35.520Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Contacted the user by email and they them to email helpdesk@gbif.org if they want to delete their account.
