### ISSUE TITLE
incorrectness in the csv data file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5458]
**incorrectness in the csv data file**

I am Kamlesh sahu, working as post-doc in university of Silesia in Katowice, Poland.  
I downloaded ur data and there are lots of problem in it
many lines are incorrect in your .csv file
and many blank cells.
i am cleaning it and whenever it is done.
I can upload this file to you
let me know if it is possible

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/56cdf1acb68b854325ffc817dc82011d:698c157ec70a60f9489f087cdfe7920feab7147ba95772e6c0f15b827aec2bfa846262999ceeb64fdf7b674945d851ab7f3b8884944ee22fd622952d188b4757171ee913eb1a84d157688916e288d643fac9021c6adda850d9fce4151634893af8a9f63f456e034c25cd412539a1c12159bbe91ac2c39388b6f1b66eb8d652a37e5c3914b016e25e507b4558f9356dfe) - [Send email](https://www.gbif.org/api/feedback/user/mailto/56cdf1acb68b854325ffc817dc82011d:698c157ec70a60f9489f087cdfe7920feab7147ba95772e6c0f15b827aec2bfa846262999ceeb64fdf7b674945d851ab7f3b8884944ee22fd622952d188b4757171ee913eb1a84d157688916e288d643fac9021c6adda850d9fce4151634893af8a9f63f456e034c25cd412539a1c12159bbe91ac2c39388b6f1b66eb8d652a37e5c3914b016e25e507b4558f9356dfe)
System: Chrome 128.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/contact-us/directory
Window size: width 1551 - height 819
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-05T09:40:53.201Z',to:'2024-09-05T09:46:53.201Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-05T09:40:53.201Z',to:'2024-09-05T09:46:53.201Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:

> Would it be possible to share an example where you found incorrect data?
> Blank fields are expected as many data providers don’t always have complete records.
> 
> You are also welcome to check [our recorded webinar on data quality for GBIF mediated data](https://www.gbif.org/composition/3CF30vzt0K8AjoWOnmJsDR/data-use-club-practical-session-2-recording-and-resources-2) as well as the associated blogpost: https://data-blog.gbif.org/post/gbif-filtering-guide/.
