### ISSUE TITLE
Hypericum revolutum Vahl.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#546]
**Hypericum revolutum Vahl.**

-----
fbitem-22de88f76c9d79b8f048b83b3cfbc3036b234366

System: Firefox 47.0.0 / Windows 8 0.0.0
Referer: https://www.gbif.org/publisher/search
Window size: width 1366 - height 657
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-10T07:40:27.265Z',mode:absolute,to:'2017-10-10T07:46:27.265Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-10T07:40:27.265Z',mode:absolute,to:'2017-10-10T07:46:27.265Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
See above issue. But I'm reluctant to to put too much trust in a report with so little effort.
