### ISSUE TITLE
publisher duplication

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5465]
**publisher duplication**

Looks like 3 identical entries for what ought to be one entry?
DEPARTMENT OF PLANNING AND ENVIRONMENT - Environment and Heritage

https://www.gbif.org/publisher/33b24ff7-b53d-4831-b4b2-37c279693670

https://www.gbif.org/publisher/454a6e93-29c2-46fb-a707-c3a0be5da83c

https://www.gbif.org/publisher/b7fd25ed-ba3d-48c0-8248-4547174ab782

-----

Github user: @MortenHofft
User: [See in registry](https://www.gbif.org/api/feedback/user/e024df07ec44155df81fa27ca2424001:a71ca0700c91e9fd8465c7f2f67c9a41713e809eaf70587732d66ff6c25eadbfd5fe73f6e9a9544db2d8da2065add827916305b3d63d7b38ef3253fa3d75a2d29d705c7ab1d28f169f4498d9fd4fac75221a45700ff4e4558dcebfd8a4fad42515d1350c462e682745e98058081a8b5eda3bf6f902596845a6cdb6e3090d391f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/e024df07ec44155df81fa27ca2424001:a71ca0700c91e9fd8465c7f2f67c9a41713e809eaf70587732d66ff6c25eadbfd5fe73f6e9a9544db2d8da2065add827916305b3d63d7b38ef3253fa3d75a2d29d705c7ab1d28f169f4498d9fd4fac75221a45700ff4e4558dcebfd8a4fad42515d1350c462e682745e98058081a8b5eda3bf6f902596845a6cdb6e3090d391f)
System: Chrome 128.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/publisher/33b24ff7-b53d-4831-b4b2-37c279693670
Window size: width 1828 - height 1542
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-10T11:02:57.998Z',to:'2024-09-10T11:08:57.998Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-10T11:02:57.998Z',to:'2024-09-10T11:08:57.998Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
This publishing organization should be preserved https://www.gbif.org/publisher/b7fd25ed-ba3d-48c0-8248-4547174ab782 and these two should be deleted: https://www.gbif.org/publisher/454a6e93-29c2-46fb-a707-c3a0be5da83c and https://www.gbif.org/publisher/33b24ff7-b53d-4831-b4b2-37c279693670. I will forward to ALA.

**Comment by CecSve** [comment]
The issue has been fixed by ALA
