### ISSUE TITLE
我需要世界海洋物种名录，由 WoRMS Editorial Board发布

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5467]
**我需要世界海洋物种名录，由 WoRMS Editorial Board发布**

Link jumps to a blank page.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/932cac18ad047d515f3a6818b17c1a56:0d6267c138a5188b0fb7e41fa9efe16401bb23b8586beebfbd520b37fa094cb622d9f9aa6738294a529735029e53fad6a2ea646308e625e8da36a0a6c130f93df78631d6996b5c69d8ba14add2ae0e6fc529fe3441c2e69242f5dfcf8a518abb) - [Send email](https://www.gbif.org/api/feedback/user/mailto/932cac18ad047d515f3a6818b17c1a56:0d6267c138a5188b0fb7e41fa9efe16401bb23b8586beebfbd520b37fa094cb622d9f9aa6738294a529735029e53fad6a2ea646308e625e8da36a0a6c130f93df78631d6996b5c69d8ba14add2ae0e6fc529fe3441c2e69242f5dfcf8a518abb)
System: Chrome 128.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/2d59e5db-57ad-41ff-97d6-11f5fb264527
Window size: width 1528 - height 740
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-11T10:11:36.358Z',to:'2024-09-11T10:17:36.358Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-11T10:11:36.358Z',to:'2024-09-11T10:17:36.358Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Replied by email:

> You can download the World Register of Marine Species checklist or a subset of it in the format of your choice on Checklistbank: https://www.checklistbank.org/dataset/2011/download (you will need to use your GBIF credentials).
