### ISSUE TITLE
link to country from the publisher page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#547]
**link to country from the publisher page**

I often need to go to the country page from the publisher and the dataset page. Perhaps, other users, too? Would it be possible to add a link to top sections, e.g. PUBLISHER... from [COUNTRY NAME], hyperlinked to country page.

-----
fbitem-publisherbb668662-8fd3-4740-9fac-9bac2d050755
User provided contact info: dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/publisher/bb668662-8fd3-4740-9fac-9bac2d050755
Window size: width 1920 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-10T08:41:05.572Z',mode:absolute,to:'2017-10-10T08:47:05.572Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-10T08:41:05.572Z',mode:absolute,to:'2017-10-10T08:47:05.572Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
added to publisher pages. I don't find that it is as relevant on dataset pages, but from there there is a link to the publisher and from there to the country
