### ISSUE TITLE
Taxon Match none flag, but there is a taxon match when searched manually

### ISSUE THREAD

**Issue by tmcelrath** [gbif/portal-feedback#5474]
This specimen is listed as incertae cedis in GBIF and flagged as taxon none:
https://www.gbif.org/occurrence/4911558636

we are exporting this as is currently listed in GBIF:
![image](https://github.com/user-attachments/assets/86913cb6-481c-4266-b2d1-08646d7558b5)
https://www.gbif.org/species/5169044

Why is this specimen not resolving?

There are other examples of this but this seems like a big problem. 

@mjy

**Comment by ManonGros** [comment]
Hi @tmcelrath I checked the record in the original archive (http://dmitriev.speciesfile.org/Export/insects.zip) and I don't see any scientific name provided in the scientific name field. I see that the name `Scytodes fusca Walckenaer` is provided in the verbatimLabel field though:
<img width="984" alt="Screenshot 2024-09-18 at 10 36 37" src="https://github.com/user-attachments/assets/1ba30967-38fe-4e04-8140-d4485212b5d4">

If you would like to have the name matched (and linked) to the GBIF Backbone taxonomy, we need the name to be in the scientificName field or in an identification extension.
Let us know if you have any question!

**Comment by MortenHofft** [comment]
https://api.gbif.org/v1/occurrence/4911558636/fragment
A good place to start error diagnostics is the raw fragment that is used for interpretation. This should be exactly as you provided it. It can be accessed via the UI

<img width="1119" alt="Screenshot 2024-09-18 at 13 21 44" src="https://github.com/user-attachments/assets/97e52c1e-cc26-4b2a-98fe-34575ad19636">

**Comment by tmcelrath** [comment]
Hmm, this might be just a problem with our indexing then. I'll check back after our next update/refresh. Thanks! Closing for now.
