### ISSUE TITLE
Search nodes on the GBIF network page

### ISSUE THREAD

**Issue by CecSve** [gbif/portal-feedback#5476]
Would it be possible to have a search option for nodes on [this page](https://www.gbif.org/the-gbif-network )? I find I have to navigate through the regions etc. to find contacts for a specific node and it would be great with a search bar with recommendations as you type across all nodes.

@MortenHofft maybe a question for you?

**Comment by MortenHofft** [comment]
Yes it is, but unless you believe it is critical I'd rather not (you could for example just do a "search page ctrl+f for now"). I would rather like us to have a broader discussion about that page before implementing it anew. And would like to avoid spending time adding bandaids to a page that has looked like that for 9 years.

My impression is that the network page deserves a revisit. Most pages we are porting as is to the new code base. But species pages and the network page are exceptions that should be reconsidered and discussed by anyone interested in it.
It would be great if you could capture ideas and examples of how it is and could be used.

Is it okay to ignore it for now?

**Comment by CecSve** [comment]
Yes of course and ctrl+f solves my problem (sorry for not thinking about that 💂‍♂️). I will make separate issues for the species and network pages and tag the DP team.
