### ISSUE TITLE
Time zone not taken into account when interpreting Event Date

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#548]
**Time zone not taken into account when interpreting Event Date**

https://www.gbif.org/occurrence/1453277312 has as original Event Date `2016-12-10T08:28:05-06:00` (= Costa Rica time) The portal has interpreted (indicated as `Altered`) this as `2016-12-10T08:28:05.000+0000` (= GMT), while it should be `2016-12-10T14:28:05.000+0000` (= with time updated to GMT).

This seems to be the case for all iNaturalist observations I checked: the time (and potentially date) is not updated to GMT.

-----
fbitem-occurrence1453277312
User provided contact info: peterdesmet
System: Chrome 61.0.3163 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/1453277312
Window size: width 1100 - height 755
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-10T18:57:48.230Z',mode:absolute,to:'2017-10-10T19:03:48.230Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-10T18:57:48.230Z',mode:absolute,to:'2017-10-10T19:03:48.230Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

**Comment by mdoering** [comment]
@cgendreau can you remind us again what interpreted times we should expect in GBIF? local times or only GMT times? It would be interesting to support range searches on local times

**Comment by cgendreau** [comment]
This behavior is expected:
https://github.com/gbif/gbif-api/issues/3

**Comment by peterdesmet** [comment]
@cgendreau you are right, this is indeed as expected and as that issue discusses, there are good reasons for interpreting it that way. However, to avoid further confusion, I would drop the timezone from the interpreted eventDate, so `2016-12-10T08:28:05.000` not `2016-12-10T08:28:05.000+0000`.
