### ISSUE TITLE
I am Ledi Selgjekaj, working with the...

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5483]
**I am Ledi Selgjekaj, working with the Protection and Preservation of Natural Environment in Albania (PPNEA), the BirdLife partner in Albania. I have recently started a PhD at the University of Debrecen in Hungary, with a focus on shorebirds. A key component of my PhD thesis involves analyzing waterbird populations and their distribution across Europe, aiming to understand the drivers behind any observed changes. My research relies on access to historical and current data on breeding waterbirds, their abundance, and their distribution. I would greatly appreciate an overview of the types of data you have available for waterbirds, particularly any related to Europe. Specifically, I’m interested in: -The availability of data at the country level in Europe. -Whether historical data (e.g., from 20 years ago) is accessible. -How the process works for requesting and using these datasets for academic research and publications. I would be grateful for any guidance on accessing and using these resources.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fdfb60cc4c6592bff3e0ad7bc19fb504:fcaae0f2d621697ab69f196d505bf069cf33b985263410fc09e6465db7a1de070f556e8519d589678d2765578befb3f7a6b3c7ac6ea0c00f0461860c10cc914c9ad65d26f81c36d25f4a384fd79fe9d1dfbbc52b6b3b8b8cf346c9611a2087593b9ee2e70780d03396e4fb04a6c55ae0) - [Send email](https://www.gbif.org/api/feedback/user/mailto/fdfb60cc4c6592bff3e0ad7bc19fb504:fcaae0f2d621697ab69f196d505bf069cf33b985263410fc09e6465db7a1de070f556e8519d589678d2765578befb3f7a6b3c7ac6ea0c00f0461860c10cc914c9ad65d26f81c36d25f4a384fd79fe9d1dfbbc52b6b3b8b8cf346c9611a2087593b9ee2e70780d03396e4fb04a6c55ae0)
System: Chrome 128.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/what-is-gbif
Window size: width 1280 - height 593
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-19T11:40:42.625Z',to:'2024-09-19T11:46:42.625Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-19T11:40:42.625Z',to:'2024-09-19T11:46:42.625Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The main type of data that you can access on GBIF are occurrence records, the observation or collection of a given specimen at a given time and place.
These aggregated occurrences can be searched in our occurrence search interface. Here is an example for a selection of all the bird occurrences in Europe: https://www.gbif.org/occurrence/search?continent=EUROPE&taxon_key=212&occurrence_status=present. You are very welcome to use the interface (or [our download API](https://techdocs.gbif.org/en/data-use/api-downloads)) to refine the selection further. You can for example select occurrences for a defined list of species (for example, waterbird species) or a specific area with polygons.

For more information, I invite you to watch our [Data Use Club](https://www.gbif.org/data-use-club) recorded webinars. Here are some relevant ones:
* [An introduction to GBIF.org and how to search on the website](https://www.gbif.org/composition/4Xm5cVB4y9n7U1GlUtKx8Q)
* [An introduction to our API](https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa)
* [An overview of the data quality issues that you might encounter](https://www.gbif.org/composition/3CF30vzt0K8AjoWOnmJsDR)

> Replied by email
