### ISSUE TITLE
I am following the User Guide for "THE_TOOL". Step 1 is to upload data, but I do not see "New Data" or any other place to upload, as described.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5488]
**I am following the User Guide for &quot;THE_TOOL&quot;. Step 1 is to upload data, but I do not see &quot;New Data&quot; or any other place to upload, as described.**

-----

Github user: @takers1124
User: [See in registry](https://www.gbif-uat.org/api/feedback/user/95312e31a08ecf3d4ce84169bdf0f081:246900f9c77b0837525cda5d5ab119425ae633b2aa23a8530c8a015db4390c70725f74e086c829a7d2eb988c5d5035cb658570edc6bb370d7385711b0878077118cdb4d37a5dedee652d74a32d391fad40913440d5728498add316d14dfe9ac0163a6740228fab6f6c2cfe08775c7376893bad6f25da5673ea26ab506b0ca4ea13418c422b98707aa96e016708196a70) - [Send email](https://www.gbif-uat.org/api/feedback/user/mailto/95312e31a08ecf3d4ce84169bdf0f081:246900f9c77b0837525cda5d5ab119425ae633b2aa23a8530c8a015db4390c70725f74e086c829a7d2eb988c5d5035cb658570edc6bb370d7385711b0878077118cdb4d37a5dedee652d74a32d391fad40913440d5728498add316d14dfe9ac0163a6740228fab6f6c2cfe08775c7376893bad6f25da5673ea26ab506b0ca4ea13418c422b98707aa96e016708196a70)
System: Chrome 129.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif-uat.org/publishing-data
Window size: width 1378 - height 754
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-22T22:15:28.504Z',to:'2024-09-22T22:21:28.504Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-22T22:15:28.504Z',to:'2024-09-22T22:21:28.504Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
User contacted through helpdesk.

**Comment by CecSve** [comment]
The user managed to make it work with the following solution:

> I think my original problem with access was related to how I created my account with GBIF. I originally tied it to my GitHub account, so each time I tried to log into GBIF-UAT and use the tool, it automatically logged me into the regular GBIF with GitHub. I eventually created a separate account with GBIF-UAT, just with a regular email, and that worked.

**Comment by MortenHofft** [comment]
I've reread this issue many times now and I'm unable to understand it. 
Is there a technical issue to address? or does this have to do with misunderstandings about metabarcoding tool vs gbif-uat vs gbif.org (prod) ? The later is also an issue, but not a technical one, but one of communication.

I'm unable to reproduce any issues about loggin in with github and being redirected to the wrong environment. And the metabarcoding tool do not have any github login either. 

I'm happy to look into any technical issues, but it isn't clear to me what they are at this point.

**Comment by CecSve** [comment]
> Is there a technical issue to address?

I do not think so. I was not able to reproduce the issue either and I think it relates to which environment the user is logged into.
