### ISSUE TITLE
Migration patterns

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5489]
**Migration patterns**

How can I see the migration patterns of different animal species? Is that info on this site?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/682d4aa6bfc6bbfb984ec6cb3359b3bd:0b423f650328c4d6b661f03e5183d34909bb56bcda5176c1ce6dab2c3b6e0b37a7468dc0104af15c3b4dd1bc194dbda7edb073d26fa2c08d84bf199f472ceb9080069c0eedbc41312bd7e36403be4977f88f006dceb0d971e7e94a267e8280a91bd397074136801eb3107516cf34bdc93da659d476f2b7b545435fb13189224d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/682d4aa6bfc6bbfb984ec6cb3359b3bd:0b423f650328c4d6b661f03e5183d34909bb56bcda5176c1ce6dab2c3b6e0b37a7468dc0104af15c3b4dd1bc194dbda7edb073d26fa2c08d84bf199f472ceb9080069c0eedbc41312bd7e36403be4977f88f006dceb0d971e7e94a267e8280a91bd397074136801eb3107516cf34bdc93da659d476f2b7b545435fb13189224d)
System: Chrome 128.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/derived-dataset
Window size: width 1912 - height 954
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-23T20:10:38.411Z',to:'2024-09-23T20:16:38.411Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-23T20:10:38.411Z',to:'2024-09-23T20:16:38.411Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
We don’t have migration patterns as such on GBIF but we might still have some relevant data for you.

As you might already know, the data available on GBIF comes from different sources: museums, research teams, citizen science initiatives, etc. These data providers package and share their records as datasets on GBIF. The main type of records that you will find on GBIF are occurrence records (the observation or collection of a given specimen at a given time and place).

With that in mind, we have some tracking datasets on GBIF, where we have several occurrences for the same individual. For example, see this dataset titled [Tracking of Arctic tern migrations 2007-2008](https://www.gbif.org/dataset/767f57dd-bdb8-44cb-bf20-f9aafafa4137) and an example of a set of occurrences for one organism: https://www.gbif.org/occurrence/map?dataset_key=767f57dd-bdb8-44cb-bf20-f9aafafa4137&organism_id=ARTE_373.
You can find more tracking datasets on GBIF by experimenting with keywords on our dataset search page: https://www.gbif.org/dataset/search?q=tracking.

It isn’t exactly what you are asking for, but you can extract some migration patterns from this type of data.

> Replied by email
