### ISSUE TITLE
Occurrence license altered to dataset license

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#549]
**Occurrence license altered to dataset license**

The record license for https://www.gbif.org/occurrence/1453277312 is CC0 (see original data). Why is it altered by GBIF to the more restrictive CC-BY-NC (which is the dataset license)?

-----
fbitem-occurrence1453277312
User provided contact info: peterdesmet
System: Chrome 61.0.3163 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/1453277312
Window size: width 1100 - height 780
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-10T20:02:18.458Z',mode:absolute,to:'2017-10-10T20:08:18.458Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-10T20:02:18.458Z',mode:absolute,to:'2017-10-10T20:08:18.458Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

**Comment by MattBlissett** [comment]
Just for interest, this principally affects iNaturalist.
