### ISSUE TITLE
Metadata for download filters

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5491]
**Metadata for download filters**

Hi, I've just learned about GBIF and am trying to download occurrence data in Ontario, Canada. I'm not sure I understand what some of the filters means, especially the issues and flags section. Is there a list of definitions that can be found somewhere?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6908ee124df2df2737f48971b1eea567:dae51ae10ddf05996ce99de16b1e41efa6b5d624b2222c731c87dcd212df5d2f78467c72efc19b9b45598317371ff180839083857c90000ca18240d8282387b9cf95d9e4a58c84b3288f2ba3a10f69e6dde792e4675928859aac7fb8645c2f3f) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6908ee124df2df2737f48971b1eea567:dae51ae10ddf05996ce99de16b1e41efa6b5d624b2222c731c87dcd212df5d2f78467c72efc19b9b45598317371ff180839083857c90000ca18240d8282387b9cf95d9e4a58c84b3288f2ba3a10f69e6dde792e4675928859aac7fb8645c2f3f)
System: Chrome 129.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq
Window size: width 1272 - height 562
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-24T11:55:26.859Z',to:'2024-09-24T12:01:26.859Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-24T11:55:26.859Z',to:'2024-09-24T12:01:26.859Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The GBIF issues and flags are documented here: https://techdocs.gbif.org/en/data-use/occurrence-issues-and-flags
We also have a description of all the fields available [here](https://techdocs.gbif.org/en/data-use/download-formats#simple).

As a side note, here is a selection of occurrences which have geolocation in Ontario: https://www.gbif.org/occurrence/search?occurrence_status=present&gadm_gid=CAN.9_1

In general, our [Data Use Club](https://www.gbif.org/data-use-club) recorded webinars can be quite helpful. Here are some relevant ones:
* [An introduction to GBIF.org and how to search on the website](https://www.gbif.org/composition/4Xm5cVB4y9n7U1GlUtKx8Q)
* [An introduction to our API](https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa)
* [An overview of the data quality issues that you might encounter](https://www.gbif.org/composition/3CF30vzt0K8AjoWOnmJsDR)

> replied by email
