### ISSUE TITLE
How do I set up my password?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5493]
**How do I set up my password?**

-----

Github user: @petronemilio
User: [See in registry](https://www.gbif.org/api/feedback/user/a2b419dc1b7d93fcef563e3263c04d45:40ed72fccb4911bb400ba6e29cd94eae9fd46d1527f38ebc4978348bc624f4d3fb55650b7cd498e5041827d5107ad86b004f1fed6d4024378e132780ed5e86f6edcf32c4be345be92b903da57d6a8bec8e40cb29f2beb680ff3c53ac4f340226a005fb1da0d4de97ee0538ca16400227661136091e759c003ac2d2f47a2245d9311f328d3e3da76dfda42506b3221e8ab4e4094916c2b916f72b8574e37c6869) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a2b419dc1b7d93fcef563e3263c04d45:40ed72fccb4911bb400ba6e29cd94eae9fd46d1527f38ebc4978348bc624f4d3fb55650b7cd498e5041827d5107ad86b004f1fed6d4024378e132780ed5e86f6edcf32c4be345be92b903da57d6a8bec8e40cb29f2beb680ff3c53ac4f340226a005fb1da0d4de97ee0538ca16400227661136091e759c003ac2d2f47a2245d9311f328d3e3da76dfda42506b3221e8ab4e4094916c2b916f72b8574e37c6869)
System: Chrome 129.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1874 - height 932
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-25T12:04:27.550Z',to:'2024-09-25T12:10:27.550Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-25T12:04:27.550Z',to:'2024-09-25T12:10:27.550Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@petronemilio would it be possible to give us a bit more context? Do you mean that you would like to reset your password for logging in GBIF.org?

**Comment by petronemilio** [comment]
Apologies for the confusion. I initially created my GBIF account by linking my Gmail and GitHub accounts without setting a password. When I tried to download data using the `rgbif` package, I wasn't sure whether to use my GitHub or Gmail password in the `Sys.setenv(GBIF_PWD = )` function. After trying both, I kept encountering errors when running `occ_download()`.

To resolve this, I unlinked my GitHub and Gmail accounts from GBIF, created a new password directly on GBIF, and everything worked perfectly afterward.

**Comment by ManonGros** [comment]
Thanks for letting us know @petronemilio

**Comment by MortenHofft** [comment]
We should consider removing account creation with Github/Google. Or at least require users to create a password as well. Since it understandably cause confusion when someone wants to later use the API. So at that point you then need to reset your password to start using the API. So you get an easy start, but then have to pay a higher price later. Better just ask for a password up front.

You can download via the UI just fine, but for the API the password is needed.

**Comment by ManonGros** [comment]
yes @MortenHofft I think it would make sense to ask users to create a password.
