### ISSUE TITLE
Locating records by gbifID and insitutions corresponding to an Instituion code

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5495]
**Locating records by gbifID and insitutions corresponding to an Instituion code**

I want to be able to do both of these things but cannot see how.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/7e97e2c18a871b5cafd6b15583cd4db8:b13b8a3fb2a8cb3808b28c1c4847fdac547f52ee194854e1a300cba62cb46a10d1b02c07893ab08768d72a0cd9b861ad132a8285c0a75aeb74fa83b2c82077a43441373305fa8cf6a650b665e97c41457e2d7d59a6210feecabf8d360bce6169f49cd76f45e0cb91925502a6590c30ca2bbc8a9979155ed023f332449a537a3067782ce63bf599da661009074359489a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/7e97e2c18a871b5cafd6b15583cd4db8:b13b8a3fb2a8cb3808b28c1c4847fdac547f52ee194854e1a300cba62cb46a10d1b02c07893ab08768d72a0cd9b861ad132a8285c0a75aeb74fa83b2c82077a43441373305fa8cf6a650b665e97c41457e2d7d59a6210feecabf8d360bce6169f49cd76f45e0cb91925502a6590c30ca2bbc8a9979155ed023f332449a537a3067782ce63bf599da661009074359489a)
System: Chrome 129.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?country=BD&taxon_key=7707728
Window size: width 1920 - height 953
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-25T20:40:44.830Z',to:'2024-09-25T20:46:44.830Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-09-25T20:40:44.830Z',to:'2024-09-25T20:46:44.830Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The GBIF ID and institution code filters are available in the advanced search interface. [Here](https://www.gbif.org/occurrence/search?country=BD&taxon_key=7707728&advanced=1&gbif_id=4519457813&gbif_id=4519455777&gbif_id=4519462005&gbif_id=4519463956&gbif_id=912727765) is an example of search based on GBIF ID and [here](https://www.gbif.org/occurrence/search?country=BD&institution_code=rbge&institution_code=k&taxon_key=7707728&advanced=1) is one based on institution code.
Note that you can also search for institution based on their codes in the [Global Registry of Scientific Collections](https://scientific-collections.gbif.org/). For example: https://scientific-collections.gbif.org/institution/search?code=K

> replied by email
