### ISSUE TITLE
page missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#550]
**page missing**

Hi - I am looking for the following page: Guide to Best Practices for Generalising Sensitive Species Occurence Data that used to be located at this URL: http://www.gbif.org/resources/2760

can you tell me where it has gone please?
thanks
Susannah

-----
fbitem-3d8b012a2e1cbab209381c683911f5ad92c157ec
User provided contact info: susannah.sabine@ands.org.au
System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/resources/2760
Window size: width 1483 - height 825
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-11T03:32:28.457Z',mode:absolute,to:'2017-10-11T03:38:28.457Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-11T03:32:28.457Z',mode:absolute,to:'2017-10-11T03:38:28.457Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
That is a shame the link doesn't work. it should. 
Should something similar again you can also [try searching ](https://www.gbif.org/resource/search?q=Guide%20to%20Best%20Practices%20for%20Generalising%20Sensitive%20Species%20Occurence%20Data&contentType=document)

the dicument is here https://www.gbif.org/document/80512/guide-to-best-practices-for-generalising-sensitive-species-occurrence-data

thanks for reporting it

>user informed per mail
