### ISSUE TITLE
coordinate problem

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5500]
**coordinate problem**

(on behalf of R. Kapeller - office@rkapeller.eu)

Dear Colleagues,

there is an erroneous occurence for Lepitochitona simrothi in your database.

This species lives only in the Azores, not in Greece. The record from Greece is due to a misinpterpretation of the coordinates, it is not at 25.68°E, which would be in Greece, but in 25.68°W, which is in the Azores.

Kind regards

R. Kapeller

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/1fd510b397d55df39291aa12d06f0bb7:6ba3fc9c5e5b384013136891f202457cea167b5469e878cd0cfc8f54042af2921fc160759fb3a102be8a89ba505bf670623e9464dd882efdbcef352187149c9bae2a8b8ad09247b8cf2b38315367dc9cb8ea55f6be76fa7293556bda43535cbf522ad24b340fb4a89dbce676d5cbbdd39b914d4ccf36db45a3017560a4f8a3024f1cf028f3c4756891094afb4b59e123) - [Send email](https://www.gbif.org/api/feedback/user/mailto/1fd510b397d55df39291aa12d06f0bb7:6ba3fc9c5e5b384013136891f202457cea167b5469e878cd0cfc8f54042af2921fc160759fb3a102be8a89ba505bf670623e9464dd882efdbcef352187149c9bae2a8b8ad09247b8cf2b38315367dc9cb8ea55f6be76fa7293556bda43535cbf522ad24b340fb4a89dbce676d5cbbdd39b914d4ccf36db45a3017560a4f8a3024f1cf028f3c4756891094afb4b59e123)
System: Firefox 131.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/occurrence/3323855335
Window size: width 1424 - height 714
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-03T09:23:52.982Z',to:'2024-10-03T09:29:52.982Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-03T09:23:52.982Z',to:'2024-10-03T09:29:52.982Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 965bbbd8-f762-11e1-a439-00145eb45e9a
publishingOrgKey: c76cf030-2a95-11da-9cc1-b8a03c50a862
Network keys: 17abcf75-2f1e-46dd-bf75-a5b21dd02655 
Node handles: @jholetschek

**Comment by jholetschek** [comment]
Issue forwarded to SeSam conact at Senckenberg, Andreas Allspach <andreas.allspach@senckenberg.de>

**Comment by jholetschek** [comment]
Mistake has been corrected in source database and has been re-harvested. I will inform the reporter.

**Comment by dnoesgaard** [comment]
Thanks @jholetschek!
