### ISSUE TITLE
The contact has to be changed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5508]
**The contact has to be changed**

New technical and administrative contact for publisher 19a3a4e0-1908-11dc-a07b-b8a03c50a862:

Markus Oppermann
opperman@ipk-gatersleben.de

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c8a0cc92119e6b4dafadc36e90cd81bc:c116a9d4eb4377fb627c82312a8d52dae42702889cffe891f5ccbb0fd24908ddd98aa63cd32eaf0007591fd7b6232c699527536e9028de84e563b8d43899cf8e59ecdea94e11bd30bfc3e4225b6213d6d46b1bb6b2ba452dd00116e0df537422cfb07dcf363596a2634d8ae359902dc1ad3c691de0133b72cf04866a79148ad1952a5bcd3c0bf1a675c020c7ebb6ef5e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c8a0cc92119e6b4dafadc36e90cd81bc:c116a9d4eb4377fb627c82312a8d52dae42702889cffe891f5ccbb0fd24908ddd98aa63cd32eaf0007591fd7b6232c699527536e9028de84e563b8d43899cf8e59ecdea94e11bd30bfc3e4225b6213d6d46b1bb6b2ba452dd00116e0df537422cfb07dcf363596a2634d8ae359902dc1ad3c691de0133b72cf04866a79148ad1952a5bcd3c0bf1a675c020c7ebb6ef5e)
System: Firefox 130.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/19a3a4e0-1908-11dc-a07b-b8a03c50a862
Window size: width 1200 - height 1725
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-11T10:29:46.822Z',to:'2024-10-11T10:35:46.822Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-11T10:29:46.822Z',to:'2024-10-11T10:35:46.822Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Updated the contact information and contacted the user
