### ISSUE TITLE
cited download deleted?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#551]
**cited download deleted?**

two things:

1) should this dataset not have been preserved due to its citation?
2) can we keep showing the citation even though the download is not available for download?

-----
fbitem-08207b915ea4b516420de3f861ca9595996630f6
User provided contact info: @dnoesgaard
System: Chrome 61.0.3163 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/download/0001240-151016162008034
Window size: width 1440 - height 715
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-12T07:13:33.254Z',mode:absolute,to:'2017-10-12T07:19:33.254Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-12T07:13:33.254Z',mode:absolute,to:'2017-10-12T07:19:33.254Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
>can we keep showing the citation even though the download is not available for download?

this part is now closed. Available on next deployment. I had to restructure quite a bit to make the styling consistent and keep the page from reflows as citations used to be client generated. The citation is now server rendered.

>should this dataset not have been preserved due to its citation?

The rest is a question to Matt about deletion policy. I suspect this was deleted before we started tracking DOIs and index them.

**Comment by MattBlissett** [comment]
It would have been deleted some time ago, although not before 20 October 2016. There's no way for us to restore it (unless someone like the paper authors have a copy).

Nothing more will be deleted for a long time, since the new cluster has much more space.

**Comment by kcopas** [comment]
Actually, the corresponding author responded to @timrobertson100 and did have the original download.

**Comment by dnoesgaard** [comment]
Super. Closing this one then...

**Comment by timrobertson100** [comment]
Fixed

**Comment by MattBlissett** [comment]
The size is 30GB in the registry, although the returned file is actually 20GB.

```
unzip -l 0001240-151016162008034.zip 
Archive:  0001240-151016162008034.zip
warning [0001240-151016162008034.zip]:  15925886631 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [0001240-151016162008034.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

**Comment by dnoesgaard** [comment]
@MattBlissett, @timrobertson100, was this fixed? Would like to close this issue, if so...
