### ISSUE TITLE
occurrences linked to the wrong GRSciColl entry

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5515]
**occurrences linked to the wrong GRSciColl entry**

the collectionID provided is https://scientific-collections.gbif.org/collection/427c8cd7-4358-4a00-9ef3-2b2676d28d1e yet the occurrences are linked to https://scientific-collections.gbif.org/collection/e2714a5f-7035-47ae-8dcd-f50e40067cdc

The API call shows the result I would expect: https://api.gbif.org/v1/grscicoll/lookup?institutionCode=RBGE&institutionId=https%3A%2F%2Fscientific-collections.gbif.org%2Finstitution%2F0237598a-853a-492c-af74-a723fe251799&collectionCode=E&collectionId=https%3A%2F%2Fscientific-collections.gbif.org%2Fcollection%2F427c8cd7-4358-4a00-9ef3-2b2676d28d1e

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/35d5ae365c850ff5d1184133a33f9138:dccc0000f56aa7b98cc0b9e447c5dfff885fa069a672b3d7e37b4852b0aa9f93ec1081464c0c02fd66628bf3aeeca71ecd413d8f63bb76f3ed73734a593924d823d2a7e41962e50d94ef8bdb099216f33ae5d101acf412d061d1375cb1d6b01008e0dc3d37042265843658cbf51a8672d9c156f5ddfe1d8cac467ff1c565b9a06de12c33b3b509815af52bac650d4a8c) - [Send email](https://www.gbif.org/api/feedback/user/mailto/35d5ae365c850ff5d1184133a33f9138:dccc0000f56aa7b98cc0b9e447c5dfff885fa069a672b3d7e37b4852b0aa9f93ec1081464c0c02fd66628bf3aeeca71ecd413d8f63bb76f3ed73734a593924d823d2a7e41962e50d94ef8bdb099216f33ae5d101acf412d061d1375cb1d6b01008e0dc3d37042265843658cbf51a8672d9c156f5ddfe1d8cac467ff1c565b9a06de12c33b3b509815af52bac650d4a8c)
System: Safari 18.0.1 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/4876542434
Window size: width 1728 - height 926
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-17T06:05:33.354Z',to:'2024-10-17T06:11:33.354Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-17T06:05:33.354Z',to:'2024-10-17T06:11:33.354Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: bf2a4bf0-5f31-11de-b67e-b8a03c50a862
publishingOrgKey: 98e934b0-5f31-11de-b67e-b8a03c50a862
Network keys: 17abcf75-2f1e-46dd-bf75-a5b21dd02655

**Comment by MortenHofft** [comment]
I see that one of the records was modified 5 days ago by you. The lookup is not performed at query time, but during indexing. So unless you know that the dataset in case have been indexed since, then I suppose it is expected if you edited the code. Does that explain it?

@marcos-lg you will know better than anyone

**Comment by marcos-lg** [comment]
I already handled this issue with @ManonGros, can it be closed @ManonGros ?

**Comment by ManonGros** [comment]
yes sorry, I forgot to close it, thanks!
