### ISSUE TITLE
data download does not include a .csv

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5531]
**data download does not include a .csv**

I am trying to download some data (https://doi.org/10.15468/dl.fgdcsb), but when I go to download the file the zipped folder does not include a .csv file. The filenames included are citations.txt, meta.html, metadata.html,  multimedia.txt, occurence.txt, rights.txt, verbatim.txt, and a folder named dataset. The FAQ page (https://www.gbif.org/faq?question=opening-gbif-csv-in-excel) suggests that the .csv should have the same name as the zipped folder (which is 0007401-241024112534372 in my case) and another source suggests that the occurence file shhould be a .csv file. Is there an issue with the way that I have downloaded the data, or else how can I open the data in Excel or R the way it is presented

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/5f6848b1227f7089a7e782a8b765cbb0:0a559d48bb8c6fd033a12d4088b5d2d39964d691ed809df88249f8b390cde42b2ac604e907438cdaed9d09b8d41c2e2c4d39c6c6f435468e675adc2220f6a5a262afeddb3ab0d76aa90bc7bdd15ede19bf3170d38ac916bb5cf830bcdb7af1c2b9503e79e5749cb5e70d7c3e2d0d7068926be99fab6cbfe4c163f79303e8f6b31149c1292e7a3d9fae85b3d53bef9926) - [Send email](https://www.gbif.org/api/feedback/user/mailto/5f6848b1227f7089a7e782a8b765cbb0:0a559d48bb8c6fd033a12d4088b5d2d39964d691ed809df88249f8b390cde42b2ac604e907438cdaed9d09b8d41c2e2c4d39c6c6f435468e675adc2220f6a5a262afeddb3ab0d76aa90bc7bdd15ede19bf3170d38ac916bb5cf830bcdb7af1c2b9503e79e5749cb5e70d7c3e2d0d7068926be99fab6cbfe4c163f79303e8f6b31149c1292e7a3d9fae85b3d53bef9926)
System: Chrome 129.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
Window size: width 1440 - height 768
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-27T19:25:01.948Z',to:'2024-10-27T19:31:01.948Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-27T19:25:01.948Z',to:'2024-10-27T19:31:01.948Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The occurrence table in the Darwin Core Archive contains the occurrences, it is tab-separated and can be open in Excel by following [the instructions you found.](https://www.gbif.org/faq?question=opening-gbif-csv-in-excel)

More information about the Darwin Core Archive download format is available here: https://www.gbif.org/faq?question=what-is-inside-a-gbif-download-zip-file

> Replied by email

**Comment by MortenHofft** [comment]
Isn't this also a case of mixing up simple csv and dwca downloads? The [opening-gbif-csv-in-excel](https://www.gbif.org/faq?question=opening-gbif-csv-in-excel) is implicitly reffering to simple csv downloads. Even if it also applies to other download formats
