### ISSUE TITLE
Philematium virens

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5532]
**Philematium virens**

Minha mãe se assustou e matou um bichinho , acredito que seja o philematium virens .
Ele apareceu em Ouro Preto, Olinda, Pernambuco, Brazil .
Queria saber se este bicho é venenoso.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6e376479aa0a8f5f1e3657d7c3a70d41:8fd5cca18d028c8135685a2994f8b186f7ec0ae7d81a48257a2a8c531228a2b964d0fc28590e572ff9ae6f0ca05437939574c47ae50a2fe773a69c282fc05e459cb9f81a5f29d8af7ec2a93e25c0705daf5f537b00d20d62cbffbd9ace1542903aa17351a4cd5b150294006bb8ba88c1a1de66c04ab31243cad1ad79bc86f248e5b7376465922b0f1a1994e3681abcb574b99b31dbc00a472d6adb58617bf5cd) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6e376479aa0a8f5f1e3657d7c3a70d41:8fd5cca18d028c8135685a2994f8b186f7ec0ae7d81a48257a2a8c531228a2b964d0fc28590e572ff9ae6f0ca05437939574c47ae50a2fe773a69c282fc05e459cb9f81a5f29d8af7ec2a93e25c0705daf5f537b00d20d62cbffbd9ace1542903aa17351a4cd5b150294006bb8ba88c1a1de66c04ab31243cad1ad79bc86f248e5b7376465922b0f1a1994e3681abcb574b99b31dbc00a472d6adb58617bf5cd)
System: Chrome Mobile 130.0.0 / Android 0.0.0
Referer: https://www.gbif.org/pt/species/4738507
Window size: width 412 - height 758
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-27T21:25:37.866Z',to:'2024-10-27T21:31:37.866Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-27T21:25:37.866Z',to:'2024-10-27T21:31:37.866Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Unfortunately, we can’t help you much with your question. We don’t have any in house taxonomic expert that could help you identify what your mother saw nor tell you whether it was a dangerous species.
As far as I can see in our database, Philematium virens mostly occurs in Africa so I would be surprised if you found a specimen in Brazil.
 
I would suggest contacting a local institution with expertise in the field, possibly someone from the UFPE https://www.ufpe.br/. They might be able to help you better than we can.

> replied by email
