### ISSUE TITLE
Is it possible to create a dataset (DOI) of occurrences by searching for a list of catalogue numbers? I have a list of catalogue numbers (herbarium barcodes) that were used for a study. To properly cite the ones accessible on GBIF, I need to create a DOI with those barcodes i.e. catalogue nubmers. Is this possible and how can it be done?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5534]
**Is it possible to create a dataset (DOI) of occurrences by searching for a list of catalogue numbers? I have a list of catalogue numbers (herbarium barcodes) that were used for a study. To properly cite the ones accessible on GBIF, I need to create a DOI with those barcodes i.e. catalogue nubmers. Is this possible and how can it be done?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b31b75325f9f2022d196cf996fa6b3cb:2977b955fedb171c67899e4a319a0f17ed5f971bd406600979f834598f723a0e476b04312c78bb63cd0a7a7a0647d1d65f79f43b4c972a34e8cff4d3f6276d79893c56d7965d7d90fb50640caa7569207b1fc62b33d14cb101ca6545b757ecd87682fada16c3b82e3a3ec397f10b4206) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b31b75325f9f2022d196cf996fa6b3cb:2977b955fedb171c67899e4a319a0f17ed5f971bd406600979f834598f723a0e476b04312c78bb63cd0a7a7a0647d1d65f79f43b4c972a34e8cff4d3f6276d79893c56d7965d7d90fb50640caa7569207b1fc62b33d14cb101ca6545b757ecd87682fada16c3b82e3a3ec397f10b4206)
System: Firefox 131.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/occurrence/search?country=CH&dataset_key=064508e2-255e-4d82-9f13-05d73476cc03&taxon_key=2730185&advanced=1
Window size: width 1440 - height 789
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-28T15:33:51.499Z',to:'2024-10-28T15:39:51.499Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-28T15:33:51.499Z',to:'2024-10-28T15:39:51.499Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Any download generated via our interface or via our [occurrence download API](https://techdocs.gbif.org/en/data-use/api-downloads) will generate an associated DOI. You are welcome to select occurrences based on their associated catalogue number and create a download for this selection.
You can do so via our web interface, [here](https://www.gbif.org/occurrence/search?catalog_number=ZT-00234380&catalog_number=ZT-00234376&country=CH&dataset_key=064508e2-255e-4d82-9f13-05d73476cc03&taxon_key=2730185&advanced=1) is an example of two records elected by catalogue numbers.

If you have a long list of catalogue numbers, you could consider using our API instead. If you aren’t familiar with our API, you can find an introduction here:
* [Recorded introduction webinar](https://www.gbif.org/composition/4TlmnRvvPs2RxrPvLH6mOa/data-use-club-practical-session-3-recording-and-resources)
* [Blogpost introduction](https://data-blog.gbif.org/post/gbif-api-beginners-guide/)

> replied by email
