### ISSUE TITLE
Any GBIF Java client?

### ISSUE THREAD

**Issue by YvanMazy** [gbif/portal-feedback#5535]
Hello!

Is there a Java client for the [GBIF API](https://techdocs.gbif.org/en/openapi/)? Searching the list of repositories, I found a [client in Python](https://github.com/gbif/pygbif), on this same repository there are links for clients in other languages ​​but nothing for Java.
If none exists, is one planned to be made?

Thanks!

**Comment by MattBlissett** [comment]
Hi,

Most of our software is written in Java.  There are Java clients, used internally, within the repositories for the webservices, e.g. https://github.com/gbif/occurrence/ has occurrence-ws-client, similarly for registry, checklistbank, crawler, etc.  They are published to our Maven repository, repository.gbif.org.

Note the way the API is documented isn't exactly the way it is implemented, so you will find parts of the documented occurrence API are implemented in different projects, e.g. the Registry.

**Comment by YvanMazy** [comment]
Thanks for your quick reply.

I had indeed found the repository you gave me, but it doesn't answer what I need.
To clarify my request, I'd like to use the API in a Java application, so if there is a Java client like there is in Python, it would save me a lot of time. My question was whether a Java client exists and, if not, whether there are any plans to provide one like in [Python](https://github.com/gbif/pygbif).

Thanks!

**Comment by ManonGros** [comment]
@YvanMazy, the various API wrappers that exist (rgbif, pygbif) were initiatives from our community (that we now maintain). GBIF isn't planning on making wrappers available in more languages. It is possible that the community made something like that in Java though. It might be worth asking our forum: https://discourse.gbif.org

But in general, why not use a generic API client?

(In python, I prefer using the `requests` library directly rather than use the `pygbif` module as more functions and are available if I query the API directly.)

**Comment by MattBlissett** [comment]
I'm not sure what you're looking for.

We use our Java clients in most of our webservices, and in many integration tests.

There's an example of using the Registry client with authentication here: https://github.com/gbif/registry/tree/dev/registry-ws-client

And here's anonymous use of a Registry API: https://github.com/gbif/collections-duplicates/blob/master/src/main/java/org/gbif/collections/duplicates/DuplicatesInspector.java

The clients are in our Maven repository:

```
    <repository>
      <id>gbif-all</id>
      <url>https://repository.gbif.org/content/groups/gbif</url>
    </repository>

  <dependency>
    <artifactId>registry-ws-client</artifactId>
    <groupId>org.gbif.registry</groupId>
    <version>3.96.22</version>
  </dependency>
```
