### ISSUE TITLE
Issues with Sequence ID

### ISSUE THREAD

**Issue by cmeidt** [gbif/portal-feedback#5539]
![Image](https://github.com/user-attachments/assets/c92d6a90-e43f-4467-837b-c6d81ef3a434)
I am trying to sequence ID 87 sequences for a project I am conducting. When submitting these sequences to the Sequence ID tool, it appears that the sequences are not being searched in BOLD. On the sequence ID tool, it seems to accept my input but nothing else. I have tried other previous sequences that have worked before- they are successful. I have made sure these sequences are in the correct FASTA format. Attached is a txt file of these sequences. Is there an issue with the website or server? I have done dozens of these blasts through the GBIF website, and this is the first time I have had this issue.[Pool9C_mini_samples.txt](https://github.com/user-attachments/files/17564079/Pool9C_mini_samples.txt)

**Comment by ManonGros** [comment]
@thomasstjerne when I test the Sequence ID tool with loading the test data, it works fine but when I use the file from @cmeidt (even if I just pick the first few sequences), I get the same issue as described above.

**Comment by thomasstjerne** [comment]
Thanks @cmeidt 
I restartet the service, it was stuck somehow. Should work now.
