### ISSUE TITLE
IPT password lost

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5550]
**IPT password lost**

Dear colleagues, 
i am in a process to add a new organization to our IPT (http://ipt.ugrasu.ru:8080/ipt),
but the GBIF password was lost by previous host,
please, would you be kind to help me and send the password to my email: filippova.courlee.nina@gmail.com
The organization is Central Siberian Botanical Garden (https://www.gbif.org/publisher/8f6232c3-5523-44ad-825c-e066fc6b15ad).

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e32c8fb4970040f7ddfb1ad441ac9a09:df17706a7b70cd9655a8cbdebd7a344c90f4bf95d5f5e14bcfa9c003c72380a97137e42857f998e6077299038ccbe763d5e7c7568e353adb13206c5230c4207f2a18c624102445e25c76b20174198d645c5ec2e95d50eafacf8cb6ee29b2cf8c6755b61da9384be6aa9624a91933868de4d44dc0965e562e6a0a3cc0941ad4bee68abe869aeeb51d14b29e2f774c0371) - [Send email](https://www.gbif.org/api/feedback/user/mailto/e32c8fb4970040f7ddfb1ad441ac9a09:df17706a7b70cd9655a8cbdebd7a344c90f4bf95d5f5e14bcfa9c003c72380a97137e42857f998e6077299038ccbe763d5e7c7568e353adb13206c5230c4207f2a18c624102445e25c76b20174198d645c5ec2e95d50eafacf8cb6ee29b2cf8c6755b61da9384be6aa9624a91933868de4d44dc0965e562e6a0a3cc0941ad4bee68abe869aeeb51d14b29e2f774c0371)
System: Chrome 130.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/
Window size: width 2133 - height 1058
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-04T08:17:00.275Z',to:'2024-11-04T08:23:00.275Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-04T08:17:00.275Z',to:'2024-11-04T08:23:00.275Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us.
I've just sent the tokens by email.

**Comment by CecSve** [comment]
Thank you for following up on this @mike-podolskiy90. I will close the issue.
