### ISSUE TITLE
Access agregated species data by country

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5553]
**Access agregated species data by country**

Dear GBIF Development Team,

I hope this message finds you well. I am currently working on a project that involves the EcoCrop database, which contains approximately 1,600 plant species. My objective is to obtain the distribution of occurrences for these plants by country, using their scientific names.

At present, I have identified a two-step process to achieve this: first, I retrieve the speciesKey using the API endpoint species/match, and then I iterate over the occurrence/search API with a limit set to 300, adjusting the offset accordingly to extract the country data for each occurrence.

However, I would like to know if there is a more efficient method to access this data, as it is available through the statistics tab in the interface. Additionally, could you please advise if I need to implement a pause between each request to avoid overwhelming the API?

Thank you very much for your assistance. I look forward to your guidance on this matter.

Best regards,

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/00e6a9f1ad170c8d387f04326c842702:b1ccbaec7d2560af83d3d39de766447e9391789a34d3177617e6de5d6714fa52d0c9d65ba5fd681a41b49687713b389e82ee1a3fb15c2f1d3d1a356c17b4011daaa7557b76f2b4b646616fc3caab2ceb8391c6405cb1365f5c712247fd471bfe43cf4b50950ab5fd56a0aa74447b02fb) - [Send email](https://www.gbif.org/api/feedback/user/mailto/00e6a9f1ad170c8d387f04326c842702:b1ccbaec7d2560af83d3d39de766447e9391789a34d3177617e6de5d6714fa52d0c9d65ba5fd681a41b49687713b389e82ee1a3fb15c2f1d3d1a356c17b4011daaa7557b76f2b4b646616fc3caab2ceb8391c6405cb1365f5c712247fd471bfe43cf4b50950ab5fd56a0aa74447b02fb)
System: Chrome 129.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/fr/occurrence/charts?taxon_key=2978751
Window size: width 1920 - height 968
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-04T17:38:42.482Z',to:'2024-11-04T17:44:42.482Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-04T17:38:42.482Z',to:'2024-11-04T17:44:42.482Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
(responding via helpdesk)

**Comment by jhnwllr** [comment]
User found solution themselves.
