### ISSUE TITLE
Lots of broken images from MVZ

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#556]
**Lots of broken images from MVZ**

On a lark, I went looking for occurrences attributed to Joseph Grinnell ([background](http://www.nature.com/news/the-ambitious-effort-to-document-california-s-changing-deserts-1.22799). 

While I was pleased to see as many records as there are—something like 16,000 of an estimated 100,000 specimens he collected (in California alone, I think)—most of the image 611 records that want to show images are not actually showing them in the gallery.

Prob low priority, but maybe it's something systemic that MVZ could address...

-----
fbitem-90ca04c707cd953f778e8789ed7ec98e67b20053
User provided contact info: @kcopas
System: Safari 11.0.0 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/gallery?media_type=StillImage&publishing_org=8edbbde0-055e-11d8-b850-b8a03c50a862&recorded_by=Collector(s):%20Joseph%20Grinnell&advanced=1
Window size: width 1282 - height 853
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-13T14:49:59.452Z',mode:absolute,to:'2017-10-13T14:55:59.452Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-13T14:49:59.452Z',mode:absolute,to:'2017-10-13T14:55:59.452Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
See https://github.com/gbif/portal16/issues/343

Our IP is blocked again.

**Comment by MattBlissett** [comment]
Considering this a duplicate.
