### ISSUE TITLE
Informazioni su daphnia bolivari

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5572]
**Informazioni su daphnia bolivari**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fe0f42e446c8d2e2229248d69e56488a:66144600311abfe4d70116f3ced7c7d294f26f38e51ff23423fc9e4b5e83f60747d6a89f43a857a0de8483b32c4309ac9a3efdec5a646239dd2751367df93b0c16333ab3181bed837b806048c42337a7e4162f18f9829a0995c9ae9d85105146aeff09874c6db93cdceb25c5a9d4811711c7ec05c6efb6cf78e757dc19906c7d102f28b27f973ca95229e6afdec769f30c956bfb51e2ea855bcb0312679715a7) - [Send email](https://www.gbif.org/api/feedback/user/mailto/fe0f42e446c8d2e2229248d69e56488a:66144600311abfe4d70116f3ced7c7d294f26f38e51ff23423fc9e4b5e83f60747d6a89f43a857a0de8483b32c4309ac9a3efdec5a646239dd2751367df93b0c16333ab3181bed837b806048c42337a7e4162f18f9829a0995c9ae9d85105146aeff09874c6db93cdceb25c5a9d4811711c7ec05c6efb6cf78e757dc19906c7d102f28b27f973ca95229e6afdec769f30c956bfb51e2ea855bcb0312679715a7)
System: Chrome 130.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/system-health
Window size: width 1536 - height 714
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-11T14:06:13.563Z',to:'2024-11-11T14:12:13.563Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-11T14:06:13.563Z',to:'2024-11-11T14:12:13.563Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Unfortunately, we have very little information available on Daphnia bolivari. The information aggregated on the corresponding species page is quite bare: https://www.gbif.org/species/4418633. The only occurrence record we have of the species is a record of the lectotype specimen held at the Smithsonian institution: https://www.gbif.org/occurrence/1321739134. You can also find the same record on the Smithsonian system: https://collections.nmnh.si.edu/search/iz/?ark=ark:/65665/3c8a54ac9132844fab4d7609fd3c0b3ae

I suggest contacting the Smithsonian institution if you would like more information about the specimen itself.

> replied by email
