### ISSUE TITLE
Download not deleted as requested

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5578]
**Download not deleted as requested**

The download of occurrence data for Plumeria obtusa L. in Belize had no data despite the fact that 21 results were indicated.  The search was run on 11 Nov. I requested deletion of the download which was supposed to have happened by the end of 12 Nov, but when I re-executed the same search today, 13 Nov, the previous download file is the only one available.  Two questions: 1. Why did the initial download not have any data (just the column headings were present)?, and 2) Why wasn't the downloaded file not deleted after the system said it would not be available after 12 Nov.  Thank you.
Anthea Gotto

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b1523bcd59ab6d2d66c4b481fd9aed30:f5a4d0fa0891856081c3587e0449517dfd3289870fefba10883440b01531d045d5983087a3d7c139fe953487509163a1724bddea0e7fef3d51147f4f814090883577c94bc68308c1946849a85fd85031cfcc6e0eb50e27aa9ad2fbe23861f44d) - [Send email](https://www.gbif.org/api/feedback/user/mailto/b1523bcd59ab6d2d66c4b481fd9aed30:f5a4d0fa0891856081c3587e0449517dfd3289870fefba10883440b01531d045d5983087a3d7c139fe953487509163a1724bddea0e7fef3d51147f4f814090883577c94bc68308c1946849a85fd85031cfcc6e0eb50e27aa9ad2fbe23861f44d)
System: Chrome 131.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/faq?question=for-how-long-will-does-gbif-store-downloads
Window size: width 1746 - height 927
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-13T20:02:11.277Z',to:'2024-11-13T20:08:11.277Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-13T20:02:11.277Z',to:'2024-11-13T20:08:11.277Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I believe the text says: **eligible for deletion after**. In practice we often keep it around longer to avoid deleting something that a user later regrets.

> Unless [GBIF discovers citations](https://www.gbif.org/literature-tracking) of this download, the data file is eligible for deletion after November 12, 2024.
> Read more about our [deletion policy](https://www.gbif.org/faq?question=for-how-long-will-does-gbif-store-downloads).

Notice also that we do not delete the metadata about the record (what filter was applied and how many records), only the downloadable occurrence data itself.

**Broken download**
It sounds like an error, but hard to tell without a link to the actual download. Could you provide a link to the record please?

> notified per mail

**Comment by leptosynapta** [comment]
Thank you for your reply; good to know the deletion process is not entirely automatic.  I have already deleted the "empty" download, but the same situation happened again with another search and download.  It may be that I have been moving too fast (lots of occurrence downloads to do)  and wasn't giving the system enough time to complete the download. I will document more thoroughly if it happens again and let you know.  Thanks for your help.
Anthea
