### ISSUE TITLE
Literature TSV download is empty

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5579]
**Literature TSV download is empty**

Hello, 

I am trying to download the list of all literature publications citing the 'Geneva Herbarium - General Collection (G)' dataset (https://www.gbif.org/dataset/f577c9f3-ae71-4278-b6bf-512ba1dfaa21). 
This is the first time I try such a download. I would expect a TSV that presents a list of all publications citing our data. 
What I get is a TSV file with a single row listing the attributes. 
Is this a bug or am I doing something wrong?

Thank you in advance for your feedback, 

Best regards, 

Anouk Mentha

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/aadc02213f1a310b154b50f31fc741b0:e4ecf3ffa7a3ef9c389145af6e31046c9acae5b332c60e66168cfecd959c18631be23f54d3b2a28e598de9cf815bae123a38cba44b201bb742cf1a918fa42624da9250cfbee4999737344c496fe4cca5eb73722c1d9421faf4795117a14eab9e55e0eb9ca533678038575eae54e0291d9446937261a8fdd6f5784ccf7be97000218805c538347c3366c426295b3a0502) - [Send email](https://www.gbif.org/api/feedback/user/mailto/aadc02213f1a310b154b50f31fc741b0:e4ecf3ffa7a3ef9c389145af6e31046c9acae5b332c60e66168cfecd959c18631be23f54d3b2a28e598de9cf815bae123a38cba44b201bb742cf1a918fa42624da9250cfbee4999737344c496fe4cca5eb73722c1d9421faf4795117a14eab9e55e0eb9ca533678038575eae54e0291d9446937261a8fdd6f5784ccf7be97000218805c538347c3366c426295b3a0502)
System: Chrome 130.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?contentType=literature
Window size: width 1738 - height 876
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-14T12:24:13.611Z',to:'2024-11-14T12:30:13.611Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-14T12:24:13.611Z',to:'2024-11-14T12:30:13.611Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thanks for reporting this. I'm afraid I cannot replicate it
https://www.gbif.org/resource/search?contentType=literature&gbifDatasetKey=f577c9f3-ae71-4278-b6bf-512ba1dfaa21
click download works fine for me. I get data.

Could you please explain the steps you took?

> notified per email

**Comment by MenthaA** [comment]
Hello, 

Thank you for your prompt answer. I took the 'normal' steps, clicking on 'download as TSV' on the resource search results page. Though when I tried again after your answer, it worked... I don't know what went wrong. Anyway, it seems to be resolved now. 
Thank you again and best regards, 

Anouk

**Comment by MortenHofft** [comment]
Argh, the worst kind of bug - not repeatable. @mike-podolskiy90 you might want to look into this? It sounds like a potential issue with the service?

**Comment by mike-podolskiy90** [comment]
@MortenHofft I'll be back 27th of November, not sure how much time I'll have to look into this next week

**Comment by mike-podolskiy90** [comment]
duplicate, transferred another issue (#5594) to the literature repository
