### ISSUE TITLE
FAQ in the menu?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#558]
**FAQ in the menu?**

How does one get to the FAQ please?

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
User provided contact info: @timrobertson100
System: Chrome 61.0.3163 / Mac OS X 10.11.5
Referer: https://www.gbif.org/
Window size: width 1611 - height 1055
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-16T09:22:21.111Z',mode:absolute,to:'2017-10-16T09:28:21.111Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-16T09:22:21.111Z',mode:absolute,to:'2017-10-16T09:28:21.111Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I take this is a suggestion to put it in the menu? I'll assign to @dnoesgaard  to decide if and where

**Comment by dnoesgaard** [comment]
Rather than adding it to the menu structure, how about a simple question mark in the nav header? Like so:

![homepage_faq_link](https://user-images.githubusercontent.com/21358085/31770439-383dceae-b4d8-11e7-88e4-cd09bde36fd5.png)

**Comment by MattBlissett** [comment]
There's a link in the footer.
