### ISSUE TITLE
Download of CSV File does not work for a large dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5584]
**Download of CSV File does not work for a large dataset**

I used the Sequence ID tool on a fasta file containing 100000 sequences. The tool worked very fast and reliable and was done within a short time. I really appreciate this but when I try to download the generated results as CSV file, at first the window with the cloud-download-symbol on a grey background opens. However, when I press the symbol, the window closes again without letting me choose a file name for the download and also without a download starting. I can do this repeatedly. 

In case this does only work up to a specific number of sequences, please let me know. It would be time consuming to split the files into smaller pieces but I really need to get this analysis done ;)

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3c23ead20f64770170c9135be8dd2cc6:275759bdfb5189b6ca7695316bf0022a968b5e9e81fdae551c365d76d03def9fe76109d256c91daab9be6b64b4348d79ed7dfa04428198d8bb49d8c64406e7b29b65a590d2ec84f3a15b72cc8c4d471c6364119af70f02b34581e7a737d64ffff68b843430f6c9f0947f278cbee786e9) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3c23ead20f64770170c9135be8dd2cc6:275759bdfb5189b6ca7695316bf0022a968b5e9e81fdae551c365d76d03def9fe76109d256c91daab9be6b64b4348d79ed7dfa04428198d8bb49d8c64406e7b29b65a590d2ec84f3a15b72cc8c4d471c6364119af70f02b34581e7a737d64ffff68b843430f6c9f0947f278cbee786e9)
System: Firefox 132.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/tools/sequence-id/about
Window size: width 1536 - height 730
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-21T11:48:00.368Z',to:'2024-11-21T11:54:00.368Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-21T11:48:00.368Z',to:'2024-11-21T11:54:00.368Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
@thomasstjerne do you think this is a limitation of the tool? It used to only be able to handle ~6000 sequences at once, but maybe this has changed?

**Comment by Rhodarian** [comment]
Well, the tool handled analysis of the sequences just fine. I just couldn't get the CSV file. There was no error message.

**Comment by thomasstjerne** [comment]
It is actually the browser that is the limitation. We used to have a hard limit on 6000 seqs pr run, which was around the max of what most browsers were capable of converting to CSV. We lifted that because browsers do get better, and it also depends on the individual sequence length etc.
@Rhodarian I would expect it to work if you simply split your file in two.  Please let us know if that works.

**Comment by Rhodarian** [comment]
Thanks for letting me know. I tried it with a file containing 50000 sequences and it worked very well. :) Again, thanks for the help!
