### ISSUE TITLE
I couldn't download it. Please help me with it.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5587]
**I couldn&#39;t download it. Please help me with it.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/abb4e9b48bf9417cfb117793654f9aaa:86180b6a2c0a1059cdc7c34bae7f80d0af22fdd87673682885c9c6282e936f47361ba49c7daf68a502a8876101acef083ae8a62c7f049b952736af5ee47704ac3c50cc164fb9fd34f069e7e9a3c505bf8eff750c528ef6a527e5369201f2c0255029f97642ae611ed27bf0bf8d7f9e3fca1733a297965a90b3d14c323e31642125399ae6ef688065baeb67059660f12c) - [Send email](https://www.gbif.org/api/feedback/user/mailto/abb4e9b48bf9417cfb117793654f9aaa:86180b6a2c0a1059cdc7c34bae7f80d0af22fdd87673682885c9c6282e936f47361ba49c7daf68a502a8876101acef083ae8a62c7f049b952736af5ee47704ac3c50cc164fb9fd34f069e7e9a3c505bf8eff750c528ef6a527e5369201f2c0255029f97642ae611ed27bf0bf8d7f9e3fca1733a297965a90b3d14c323e31642125399ae6ef688065baeb67059660f12c)
System: Firefox 132.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0028850-241107131044228
Window size: width 1366 - height 643
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-22T17:15:21.952Z',to:'2024-11-22T17:21:21.952Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-22T17:15:21.952Z',to:'2024-11-22T17:21:21.952Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
The download was broken. This link can be used instead: https://www.gbif.org/occurrence/download/0032662-241107131044228. User contacted through helpdesk,
