### ISSUE TITLE
Participant counts have gone missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#560]
**Participant counts have gone missing**

Wondering if this is related to work addressing the [earlier issue on publisher counts](https://github.com/gbif/portal16/issues/571) or an issue with the registry (which was updated with a new participant organization today), but the publisher count is the only one that appears now on the network page.

-----
fbitem-5f8f9aca65a6fc0d0677bfe440ec39d391db6ce0
User provided contact info: @kcopas
System: Safari 11.0.0 / Mac OS X 10.12.6
Referer: https://www.gbif.org/the-gbif-network
Window size: width 1282 - height 853
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-16T14:49:04.364Z',mode:absolute,to:'2017-10-16T14:55:04.364Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-16T14:49:04.364Z',mode:absolute,to:'2017-10-16T14:55:04.364Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
I cant reproduce it, could be a temporary connectivity thing or slow API response.
Can you give it another try @kcopas ?

**Comment by kcopas** [comment]
I checked this morning, they were still missing. But they reappeared a little bit ago and, with a little bit of latency, are there now. #dunno

**Comment by MortenHofft** [comment]
Was missing 1 hour ago as well

**Comment by MortenHofft** [comment]
This has been reported again today by @jlegind
