### ISSUE TITLE
How can I change my email address.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5608]
**How can I change my email address.**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/c397dd6838e9267ab8a1d7a4f042320e:35b300b454a61098253d26d0bcac75d5f6520fc2248da2665d66d025b7461f2c3585a9f77f14eb7efc92a6b47b42f4fad77ee6e0a7c7c33d8c857290b464e22276dcf670c900f5b65dd93eb7481decef282df9ce7daf933feccd048987c70a32cb955f2ede3069140220b7bb044fc1bcda79677d5cbb4d8c0510a55a10303945) - [Send email](https://www.gbif.org/api/feedback/user/mailto/c397dd6838e9267ab8a1d7a4f042320e:35b300b454a61098253d26d0bcac75d5f6520fc2248da2665d66d025b7461f2c3585a9f77f14eb7efc92a6b47b42f4fad77ee6e0a7c7c33d8c857290b464e22276dcf670c900f5b65dd93eb7481decef282df9ce7daf933feccd048987c70a32cb955f2ede3069140220b7bb044fc1bcda79677d5cbb4d8c0510a55a10303945)
System: Chrome 131.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/user/profile
Window size: width 1390 - height 626
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-12-02T17:31:24.886Z',to:'2024-12-02T17:37:24.886Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-12-02T17:31:24.886Z',to:'2024-12-02T17:37:24.886Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
the user has been contacted through helpdesk with the following reply:

> You can change your email in the settings of your profile by clicking the ‘start editing' button in the top right corner

however, the email address of the user is not active, so they may have manged to change it already.
