### ISSUE TITLE
foo@gbif.org intentional as contact email?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#561]
**foo@gbif.org intentional as contact email?**

Under "custom data export", the email given after "If you need assistance..." spells foo@gbif.org. Should that better read helpdesk@gbif.org?

-----
fbitem-57ee03dd725ec36a7faf1f69bca70ff2ef3c507e
User provided contact info: ahahn-gbif
System: Firefox 56.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/citation-guidelines
Window size: width 1248 - height 590
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-18T08:09:41.959Z',mode:absolute,to:'2017-10-18T08:15:41.959Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-18T08:09:41.959Z',mode:absolute,to:'2017-10-18T08:15:41.959Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Placeholder, never meant to survive, natch.
