### ISSUE TITLE
definitions full GBIF data terms/variables

### ISSUE THREAD

**Issue by veronicar239** [gbif/portal-feedback#5614]
I'm looking for a full list of definitions of the GBIF data terms (columns = 223 variables). A subset of the variables are Darwin Core terms, but other GBIF variables are not within the Darwin Core terms. For example, the variable "isSequenced" in GBIF data is not defined in the Darwin Core terms (but "associatedSequences" is defined in Darwin Core) . 
I tried submitting this question via the GBIF Helpdesk but there was an error ("This isn’t good — the feedback system doesn’t work. Please send us a mail or go straight to Github. We are sorry about the trouble.")

**Comment by ManonGros** [comment]
@veronicar239 would this page work for you? https://techdocs.gbif.org/en/data-use/download-formats

**Comment by veronicar239** [comment]
Yes that is it - thank you!
