### ISSUE TITLE
distribution invalid

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#562]
**distribution invalid**

Concerning the Manual of the Alien Plants of Belgium. 

The checklist data get a distribution:invalid tag (e.g. https://www.gbif.org/species/134086869).

-----
fbitem-species134087349
User provided contact info: LienReyserhove
System: Chrome 61.0.3163 / Windows 7 0.0.0
Referer: https://www.gbif.org/species/134087349
Window size: width 1536 - height 772
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-18T09:02:08.627Z',mode:absolute,to:'2017-10-18T09:08:08.627Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-18T09:02:08.627Z',mode:absolute,to:'2017-10-18T09:08:08.627Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by peterdesmet** [comment]
The [verbatim distribution information for this species](https://www.gbif.org/species/134086869/verbatim) is:

> Term | Value
> -- | --
> eventDate | 2005/2016
> occurrenceStatus | present
> locality | Belgium
> countryCode | BE
> establishmentMeans | escape:horticulture
> locationID | ISO3166-2:BE

While the [interpreted distribution information](https://www.gbif.org/species/134086869) is:

> PRESENT IN BELGIUM, ISO3166-2:BE, BELGIUM

The `eventDate` and `establishmentMeans` or not retained. The first is a date range, the second does not follow the http://rs.gbif.org/vocabulary/gbif/establishment_means.xml (but rather [the one proposed](https://github.com/qgroom/ias-dwc-proposal/blob/master/proposal.md#suggested-controlled-vocabulary-2) by @qgroom). Is either of these causing the `distribution invalid` flag?

**Comment by peterdesmet** [comment]
I noticed the `eventDate` is available as `temporal` [via the API](https://api.gbif.org/v1/species/134086869/distributions), with the range:

```
{
    "taxonKey": 134086869,
    "locationId": "ISO3166-2:BE",
    "locality": "Belgium",
    "country": "BE",
    "status": "PRESENT",
    "temporal": "2005/2016"
}
```

The `establishmentMeans` however is lost. That information is available via the API for taxa of other checklists (e.g. [VASCAN](https://api.gbif.org/v1/species/100000791/distributions)), where it conforms to http://rs.gbif.org/vocabulary/gbif/establishment_means.xml

So the `distribution invalid` flag is probably caused by using values that don't conform to http://rs.gbif.org/vocabulary/gbif/establishment_means.xml? And that data is not even exposed through the API?

**Comment by mdoering** [comment]
Yes. The distribution issue in general stands for anything related to any distribution record for the species that failed interpretation. This is mostly interpreting fixed enumeration values, but could be occurrence status, country, establishment means, life stage, etc see http://rs.gbif.org/extension/gbif/1.0/distribution.xml

**Comment by peterdesmet** [comment]
We've updated our dataset to use the current enum for `establishmentMeans` (e.g. in https://www.gbif.org/species/141265785). So this issue can be closed.
