### ISSUE TITLE
Difference in number of taxa: source data versus GBIF data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#564]
**Difference in number of taxa: source data versus GBIF data**

Concerning the [Manual of the Alien Plants of Belgium] (https://www.gbif.org/dataset/9ff7d317-609b-4c08-bd86-3bc404b77c42)

The number of species recorded in the [GBIF checklist] (https://www.gbif.org/species/search?dataset_key=9ff7d317-609b-4c08-bd86-3bc404b77c42&origin=SOURCE&advanced=1) is 2481

The number of species in the [source dataset] (http://ipt.biodiversity.be/resource?r=alien-plants-belgium) is 2500.

Why is there a difference? Could the presence of hybrids explain this difference?

-----
fbitem-1f059dd0d137ccd641e791a2992ee7e29204a773
User provided contact info: LienReyserhove
System: Chrome 61.0.3163 / Windows 7 0.0.0
Referer: https://www.gbif.org/species/search?dataset_key=9ff7d317-609b-4c08-bd86-3bc404b77c42&origin=SOURCE&advanced=1
Window size: width 1536 - height 820
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-18T12:09:13.731Z',mode:absolute,to:'2017-10-18T12:15:13.731Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-18T12:09:13.731Z',mode:absolute,to:'2017-10-18T12:15:13.731Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by LienReyserhove** [comment]
Subject: difference in number of taxa: source data versus GBIF data

Concerning the [Manual of the Alien Plants of Belgium](https://www.gbif.org/dataset/9ff7d317-609b-4c08-bd86-3bc404b77c42)

The amount of species recorded in the [GBIF checklist](https://www.gbif.org/species/search?dataset_key=9ff7d317-609b-4c08-bd86-3bc404b77c42&origin=SOURCE&advanced=1) is 2481

The amount of species in the [source dataset](http://ipt.biodiversity.be/resource?r=alien-plants-belgium) is 2500.

Why is there a difference? Could the presence of hybrids explain this difference?

**Comment by LienReyserhove** [comment]
https://github.com/trias-project/alien-plants-belgium/issues/34

**Comment by ManonGros** [comment]
I can't seem to find this difference.
It looks like both have now 2,531 records.
Closing the issue.
