### ISSUE TITLE
maxent page could need  a brush up

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#565]
**maxent page could need a brush up**

-----
fbitem-e12994a2acb958013f4ff2ab44b704923929a99c
User provided contact info: @dnoesgaard
System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/tool/81279/maxent-software-for-modeling-species-niches-and-distributions
Window size: width 1921 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-18T12:21:04.779Z',mode:absolute,to:'2017-10-18T12:27:04.779Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-18T12:21:04.779Z',mode:absolute,to:'2017-10-18T12:27:04.779Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
Now brushed up :)
