### ISSUE TITLE
GBIF Germany contacts corrected

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#566]
**GBIF Germany contacts corrected**

Page:  https://www.gbif.org/country/DE/summary

GBIF Germany contacts (only corrected entries listed)

Ms. Regine Jahn -> Dr. Regine Jahn;
Gerhard Haszprunar -> Prof. Dr. Gerhard Haszprunar;
Lothar Menner -> Mr. Lothar Menner;
Ms. Dagmar Triebel -> Dr. Dagmar Triebel;
David Lazarus -> Dr. David Lazarus;
Dr. Anton Güntsch -> Mr. Anton Güntsch;
Willi Xylander -> Prof. Dr. Willi Xylander;
Prof. Walter Berendsohn -> Prof. Dr. Walter Berendsohn;
Mr. Jörg Overmann -> Prof. Dr. Jörg Overmann;
Mr. Jörg Spelda -> Dr. Jörg Spelda;
Carola Söhngen -> Dr. Carola Söhngen

-----
fbitem-34c0f2b14bbd17a077dba826f2e4e2731414cdc7
User provided contact info: w.h.kusber@bgbm.org
System: Firefox 56.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/country/DE/summary
Window size: width 1735 - height 824
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-20T18:17:54.363Z',mode:absolute,to:'2017-10-20T18:23:54.363Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-20T18:17:54.363Z',mode:absolute,to:'2017-10-20T18:23:54.363Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
I think these concern directory entries - checking

**Comment by ahahn-gbif** [comment]
The entries are now updated in the directory. Closing.
