### ISSUE TITLE
Error in Lyhtrum flexuosum taxa

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#567]
**Error in Lyhtrum flexuosum taxa**

Good Morning,
my name is ester vega elices and I work in the germplasm bank of the university of salamanca, a registered institution to publish in GBIF. We have recently made the first data upload of wild plant species and we have detected an error in what I imagine will be your botanical species database. Specifically, it is the species Lythrym flexuosum, which changes in listing by species to Lythum acutangulum because you have introduced it as a synonym of Lyhtrum flexuosum. These two species are not synonymous, both are accepted names of two different taxa. I have checked this information with Enrique Rico Hernandez, taxonomist of the University of Salamanca (Spain) and has confirmed that they are different taxa, also very different morphologically, so they can not be synonymous. I think it is important that you change this information, since someone may be thought to have Lyhtrum acutangulum in our accessions when what we have is flexuosum.

Greetings and thank you,

Ester

-----
fbitem-species3988992
User provided contact info: estervega@usal.es
System: Chrome 62.0.3202 / Windows 10 0.0.0
Referer: https://www.gbif.org/species/3988992
Window size: width 1536 - height 759
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-23T10:21:28.117Z',mode:absolute,to:'2017-10-23T10:27:28.117Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-23T10:21:28.117Z',mode:absolute,to:'2017-10-23T10:27:28.117Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
Thanks. We follow the Catalogue of Life which claims this synonymy:
http://www.catalogueoflife.org/annual-checklist/2017/search/all/key/Lythrum+flexuosum/fossil/0/match/1

**Comment by mdoering** [comment]
TaxRef says it belongs to L. junceum non Lag.:
 https://inpn.mnhn.fr/espece/cd_nom/107108/tab/taxo

Same does EUNIS who also recognizes L. junceum Lag.
http://eunis.eea.europa.eu/species/176028
http://eunis.eea.europa.eu/species/176032

**Comment by rdmpage** [comment]
@mdoering I think there are a couple of issues here. The first is that Catalogue of Life get's its information from the World Plants list, which doesn''t strike me as authoritative (see https://github.com/Sp2000/colplus/issues/27 ). Secondly it looks like there are two notions of * Lythrum flexuosum* here, one the actual *Lythrum flexuosum*, the other * Lythrum flexuosum* auct. non Lag. Possibly the synonymy is not "*Lythrum flexuosum* is a synonym" but rather "*Lythrum flexuosum* as used by many people is not *Lythrum flexuosum* but a synonym.

**Comment by mdoering** [comment]
Yes, thats the case at least for the EUNIS synonyms and probably like it should be. CoL/World Plants clearly just has this one regular synonymy entry which appears to be wrong. I will keep this issue open until we rebuild the backbone and make sure its added to our patch list then.

Give me a chance to try Dimas name parser and see how he handles auct/sensu non XYZ names...

**Comment by mdoering** [comment]
Lythrum flexuosum Lag. and L. acutangulum are 2 distinct, accepted species in the Jan 2018 Backbone
