### ISSUE TITLE
"Agrotraining:­ Proofing GBIF (...)" exposes enums.cms.vocabularyTerms filter

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#568]
**&quot;Agrotraining:­ Proofing GBIF (...)&quot; exposes enums.cms.vocabularyTerms filter**

The "Agrotraining:­ Proofing GBIF (...)" item lists a filter for https://www.gbif.org/resource/search?contentType=project&purposes=DATA_CURATION_&_QUALITY with a label of enums.cms.vocabularyTerms.purposes.DATA_CURATION_&amp;_QUALITY" that is a) not functional and b) should not show like this.

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
User provided contact info: ahahn-gbif
System: Firefox 56.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/search?q=work%20program%202018
Window size: width 1044 - height 585
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-23T14:52:01.716Z',mode:absolute,to:'2017-10-23T14:58:01.716Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-23T14:52:01.716Z',mode:absolute,to:'2017-10-23T14:58:01.716Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
The enum hasn't been added to the portal project. Seemingly it has never been used before.

**Comment by MortenHofft** [comment]
Seems the enum have been renamed in contentful or elasitc search. I'll align the portal the the new naming

**Comment by dnoesgaard** [comment]
Old issue, but for some reason it appears to have reverted back to the former.

Example: https://www.gbif.org/project/83348/extending-tools-for-improving-biodiversity-data-quality-to-spanish-speaking-communities

In Contentful we have:
"vocab_term_938" -> "Data curation quality"

In ES
"DATA_CURATION_QUALITY"

In content
"DATA_CURATION_QUALITY"

but the filter uses this translation:
enums.cms.vocabularyTerms.purposes.DATA_CURATION_&_QUALITY

Perhaps this needs updating here: https://github.com/gbif/portal16/blob/c32c08c69e096fcaeb4604b124a2c18dddc84e8b/app/models/enums/cms/purpose.json#L5 ?

**Comment by MortenHofft** [comment]
Thanks Daniel
You are completely right that that file needed updating
I don't believe it has reverted, just wasn't corrected in that file after the renaming in ES.
