### ISSUE TITLE
"GBIF Annual Report 2014" item repeats the description text twice

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#569]
**&quot;GBIF Annual Report 2014&quot; item repeats the description text twice**

The text block in the filter results for this item shows content repeated. Possible reason: the text is so short that there is no second line available (?)

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
User provided contact info: ahahn-gbif
System: Firefox 56.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/search?q=work%20program%202018
Window size: width 1044 - height 585
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-23T14:53:41.017Z',mode:absolute,to:'2017-10-23T14:59:41.017Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-23T14:53:41.017Z',mode:absolute,to:'2017-10-23T14:59:41.017Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
https://app.contentful.com/spaces/uo17ejk9rkwj/entries/82193
summary and body text is the same in the content item

**Comment by kcopas** [comment]
Summary removed.
