### ISSUE TITLE
Occurence records accesible by OccurrenceID

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#572]
**Occurence records accesible by OccurrenceID**

The question is if any record can be addressed by OccurrenceID in the same way it is by “GBIF number” as in:
https://www.gbif.org/occurrence/1275106250  which has a UUID for OccurrenceID…  and so it is unique, universal and permanent, and thus much more adequate for referring to that record in contexts beyond GBIF… in other words, it would be nice to see those identifiers in the URLs referring to occurrences. I know that many data provides still use the DwC triplets (institution:collection:accession), which is not guarantee for uniqueness or persistence, but maybe a hybrid system could be put in place…

-----
fbitem-occurrence1275106250
User provided contact info: PacoPando
System: Chrome 61.0.3163 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/1275106250
Window size: width 1415 - height 894
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-24T10:11:48.520Z',mode:absolute,to:'2017-10-24T10:17:48.520Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-24T10:11:48.520Z',mode:absolute,to:'2017-10-24T10:17:48.520Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 83598aa6-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 0363cbd4-f666-455e-8e86-0bbddcf51950

**Comment by MortenHofft** [comment]
Hi @PacoPando 
Occurrence ids are not necessarily unique. Publishers can use whatever ID they feel like. But you can search for them. [OccurrenceId=1 has 129 results ](https://www.gbif.org/occurrence/search?occurrence_id=1&advanced=1) for example.

But there is a url that can help you https://www.gbif.org/occurrence/first

It does a search. if there is only one result it links to that. Else it shows search results.

* https://www.gbif.org/occurrence/first?occurrenceId=1
* https://www.gbif.org/occurrence/first?occurrenceId=BA9A00CF-A759-4C9D-B369-86E9B0A01DC4

**Comment by MortenHofft** [comment]
That also means you could qualify it by your datasetKey
https://www.gbif.org/occurrence/search?dataset_key=0348540a-e644-4496-89d3-c257da9ad776&occurrence_id=1
