### ISSUE TITLE
Can't handle large file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#573]
**Can&#39;t handle large file**

332 MB DwC-A with 4,859,753 Occurrences 

http://api.biodiversitydata.nl/v0/specimen/search/dwca/?collection=botany  

from the following dataset https://www.gbif.org/dataset/15f819bd-6612-4447-854b-14d12ee1022d is supposedly too large to validate. 

What is too big exactly? Some help text in the interface explaining what is too big would be a valuable improvement. 

Screenshots attached showing error messages.

<img width="1437" alt="screen shot 2017-10-24 at 14 45 54" src="https://user-images.githubusercontent.com/5981100/31944186-851128f6-b8cb-11e7-8cd8-ac046ce66829.png">

<img width="1156" alt="screen shot 2017-10-24 at 14 51 18" src="https://user-images.githubusercontent.com/5981100/31944200-8f80d200-b8cb-11e7-8a3e-356697d060e6.png">

-----
fbitem-066f438500c724cac3af4f667be0f432015473ff
User provided contact info: kbraak
System: Firefox 56.0.0 / Mac OS X 10.10.0
Referer: https://www.gbif-dev.org/tools/data-validator
Window size: width 1440 - height 762
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-24T12:50:59.680Z',mode:absolute,to:'2017-10-24T12:56:59.680Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-24T12:50:59.680Z',mode:absolute,to:'2017-10-24T12:56:59.680Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
The client simply catches the 415 Payload to large error. Maybe @cgendreau or @fmendezh knows about the max allowed size?
