### ISSUE TITLE
The "in" predicate doesn't seem to work for downloads

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#575]
**The &quot;in&quot; predicate doesn&#39;t seem to work for downloads**

Example here:

https://www.gbif.org/occurrence/download/0002141-171020152545675

According to the documentation, type:in should work with this syntax.  

See also (simpler):

https://www.gbif.org/occurrence/download/0002140-171020152545675

-----
fbitem-80a735a41b7b7dcd820ddbb16fe00e9bddc0617d
User provided contact info: dhobern@gbif.org
System: Chrome 61.0.3163 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/download/0002141-171020152545675
Window size: width 1220 - height 901
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-24T16:57:21.410Z',mode:absolute,to:'2017-10-24T17:03:21.410Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-24T16:57:21.410Z',mode:absolute,to:'2017-10-24T17:03:21.410Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Now also http://api.gbif.org/v1/occurrence/download/0030014-180508205500799

**Comment by MattBlissett** [comment]
@dhobern, a bit of a long wait, and now a little bit more wait until it's deployed.
