### ISSUE TITLE
usageKey 8841437

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#576]
**usageKey 8841437**

Dear GBIF,

My r-scripts stopped at this species because $species is empty, which should give Arenaria verna propinqua if it indeed is an accepted name?

Compare the following two names in R, both accepted names:

x <- name_backbone(name="Arenaria verna var. propinqua")
x <- name_backbone(name="Arenaria hirta")
x
x$species

Kind regards,

Niels Raes

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e

System: Chrome 61.0.3163 / Windows 10 0.0.0
Referer: https://www.gbif.org/
Window size: width 1920 - height 959
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-24T19:18:04.707Z',mode:absolute,to:'2017-10-24T19:24:04.707Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-24T19:18:04.707Z',mode:absolute,to:'2017-10-24T19:24:04.707Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
No contact info - also seems like a question for RGBIF
