### ISSUE TITLE
Non existent taxon name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#577]
**Non existent taxon name**

This name (plus I guess a swag of others) entered WoRMS, IRMNG and elsewhere from a bad entry in the 2006 Catalogue of Life (AlgaeBase component); it was most likely an error for the "good" name Parahistioneis paraformis. It has subsequently been cleaned out of AlgaeBase/WoRMS and IRMNG (the latter in April 2016). I can supply a list of similar deletions from IRMNG fr that reason ("no longer listed in WoRMS") if needed. I am thinking that GBIF needs a mechanism to detect and delete such bad data from its backbone taxonomy (records now deleted from system XXX) and would welcome feedback on how best to facilitate this.

-----
fbitem-species7472336
User provided contact info: TonyRees
System: Chrome 61.0.3163 / Windows 8.1 0.0.0
Referer: https://www.gbif.org/species/7472336
Window size: width 1366 - height 637
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-25T01:27:31.562Z',mode:absolute,to:'2017-10-25T01:33:31.562Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-25T01:27:31.562Z',mode:absolute,to:'2017-10-25T01:33:31.562Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
Parahistioneis ptwaformis Kofoid & Skogsberg

**Comment by mdoering** [comment]
Thanks Tony, we will delete these records from our backbone when we rebuild it and its not present anymore in the underlying sources. As the latest copy of [WoRMS and IRMNG](https://www.gbif.org/species/search?q=Parahistioneis%20ptwaformis&dataset_key=2d59e5db-57ad-41ff-97d6-11f5fb264527&dataset_key=0938172b-2086-439c-a1dd-c21cb0109ed5&origin=SOURCE&advanced=1) we have indexed lacks these names I believe we are already good and nothing else is needed to be done apart from a rebuild.

The version of IRMNG we now use is also just the generic index based on http://www.irmng.org/export/IRMNG_genera_DwCA.zip

**Comment by mdoering** [comment]
Parahistioneis ptwaformis is deleted in backbone 2018-01
Parahistioneis paraformis listed as a doubtfully accetped species
