### ISSUE TITLE
Amphidora paralella is a synonym

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#578]
**Amphidora paralella is a synonym**

This species was presumably 'discovered' by digitization of a primary type, and is currently listed as an accepted name.

In fact, Amphidora paralella Casey was synonymized with Stenotrichus rufipes (LeConte, 1851) by Blaisdell in 1933 (http://www.jstor.org/stable/25077298).

Due to later generic synonymies, the current combination is Helops rufipes (LeConte, 1851) - an unfortunate homonym with Helops rufipes Fabricius, 1775.

Unfortunately the nub does not have entries for either  of the newer combinations, so those would need to be created to correct this synonyy.

-----
fbitem-species9224959
User provided contact info: mandrewj
System: Chrome 61.0.3163 / Mac OS X 10.12.6
Referer: https://www.gbif.org/species/9224959
Window size: width 1166 - height 894
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-25T05:24:57.858Z',mode:absolute,to:'2017-10-25T05:30:57.858Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-25T05:24:57.858Z',mode:absolute,to:'2017-10-25T05:30:57.858Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ManonGros** [comment]
The species has been deleted.
