### ISSUE TITLE
Sign-posting deleted then restored/superseded datasets from UK

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#579]
@timrobertson100 @ahahn-gbif not sure whose team this falls to, but I've turned up about three dozen datasets from NBN that I believe wound up being temporarily deleted and are now restored in one fashion or another—sometimes replaced, but in a few instances either lumped or split. 

I agree that we should not get into the mess of, for instance, somehow moving or rerouting DOI-based citations from old dataset to new, but I think the signposting done on earlier segmented versions ([example](https://www.gbif.org/dataset/516bb920-2e4c-11de-909a-b8a03c50a862
)) of what's now a single [Finnish Entomological Database](https://www.gbif.org/dataset/3b301884-51b9-443f-b63c-47feeccfb89f) would be useful in these other instances. I think the phrasing in the example is spot on: 'This dataset was deleted [date]. It is likely replaced by {Dataset}(URL).'

> [List attached here](https://github.com/gbif/portal-feedback/files/1414023/citsci-2016-dataset-crosslinks.xlsx)

How might this best be achieved? @dnoesgaard thought this might have been achieved through an edit to the registry, but my efforts to search for the deleted datasets in the above list are not turning up any results—and even if I did, the thought of me editing the registry directly scares the filling out of my donut.  

NB, these came to light as I revisited and prepared a cleaned-up version of the list of datasets included in the March 2016 citizen science analysis for peer review by the relevant nodes—a small step toward preparing some material for the 1 billion landmark.

**Comment by ManonGros** [comment]
@kcopas I linked as many datasets as I could using your spreadsheet. I couldn't do the ones that were split (as the "duplicate if" tag can only redirect to one dataset) and some of the "new" dataset were deleted as well (for example this one: https://www.gbif.org/dataset/acf23073-3553-4743-ad50-9680de06061d).
I will close the issue now.
