### ISSUE TITLE
Include Funder Information

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#58]
**Include Funder Information**

On the country &#39;pop up&#39; it would be good to include the name of the funder(s), offering them greater visibility.

-----
fbitem-5f8f9aca65a6fc0d0677bfe440ec39d391db6ce0
Reported by: sbjensen@gbif.org
System: Firefox 51.0.0 / Windows 7 0.0.0
Referer: https://demo.gbif.org/the-gbif-network
Window size: width 1311 - height 946
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-06T11:02:48.735Z',mode:absolute,to:'2017-02-06T11:08:48.735Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-06T11:02:48.735Z',mode:absolute,to:'2017-02-06T11:08:48.735Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Just to follow up, I had a good discussion this afternoon with Søren about both the general and specific instances. As if it doesn't go without saying, I think we should take a closer look at the information in the map-based pop-up as soon as is feasible (and probably after the participation tab makes the migration).

On a related note, I'd also like to suggest that on country pages we might consider adding 'Non-participant' where 'Voting' and 'Associate' now appear, as one means of directing interested policymakers toward information on joining GBIF. Some sketches underway on the 4th floor...

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/258
