### ISSUE TITLE
Valid BoR values not shown as interpreted

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#583]
**Valid BoR values not shown as interpreted**

This [archive being validated](http://ipt-togo.gbif.fr/archive.do?r=reptile&v=1.2) has 88 occurrence records total, each of which has the valid BasisOfRecord "livingspecimen". 

What's the problem? 

The column "Interpreted" in the occurrence.txt table is empty for dwc:basisOfRecord. Only dwc:year was interpreted properly according to the table. 

This is confusing for the user. Interpretation should be consistently reported for all terms, with an explanation given why the term couldn't be interpreted for example linking to the validation issues at the bottom of the page corresponding to that term.

-----
fbitem-881b5aa5f331f9f02ba11145b2abe98bb5e23c91
User provided contact info: kbraak
System: Chrome 61.0.3163 / Mac OS X 10.10.5
Referer: https://www.gbif.org/tools/data-validator/1508848348037
Window size: width 1396 - height 1104
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-25T14:21:18.413Z',mode:absolute,to:'2017-10-25T14:27:18.413Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-25T14:21:18.413Z',mode:absolute,to:'2017-10-25T14:27:18.413Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Closing as the archive is no longer available, and it looks like the failure was a lack of occurrenceIds (big red warning).
