### ISSUE TITLE
Missing support for GBIF triplet style ID

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#588]
**Missing support for GBIF triplet style ID**

[This dataset from Togo](http://ipt-togo.gbif.fr/archive.do?r=herbarium_ul ) uses the GBIF triplet style identifier, which is a combination of three fields: catalogNumber, institutionCode and collectionCode.

Each of its records is therefore uniquely identified. 

Contrary to the validator report, the file should be indexible by GBIF and each record should be uniquely identified. 

Of course we want to promote the use of occurrenceIDs instead of the GBIF triplet, however, the validator is supposed to reflect GBIF indexing operating procedures, which supports the GBIF triplet identifier afaik.

-----
fbitem-9ceba7755c086fa5a18ef4c6bd2102ecccab59e7
User provided contact info: kbraak
System: Chrome 61.0.3163 / Mac OS X 10.10.5
Referer: https://www.gbif.org/tools/data-validator/1508848348041
Window size: width 1338 - height 843
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-26T13:21:10.507Z',mode:absolute,to:'2017-10-26T13:27:10.507Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-26T13:21:10.507Z',mode:absolute,to:'2017-10-26T13:27:10.507Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
transferred to https://github.com/gbif/gbif-data-validator/issues/59
