### ISSUE TITLE
Check whether automatic crawling of metadata-only datasets is working

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#589]
**Check whether automatic crawling of metadata-only datasets is working**

This dataset was registered 7 days ago on 2017-10-19 at 21:15. 

Assuming datasets get crawled exactly every 7 days, and that metadata-only datasets are also being recrawled successfully, this dataset should be recrawled tonight at 21:15. 

Logging this issue as a reminder to recheck this is working as expected. See crawl history here: https://registry.gbif.org/web/#/dataset/2bee4a91-9d92-430e-a87e-ab32d3b1ce47/crawl

-----
fbitem-dataset2bee4a91-9d92-430e-a87e-ab32d3b1ce47
User provided contact info: kbraak
System: Chrome 61.0.3163 / Mac OS X 10.10.5
Referer: https://www.gbif.org/dataset/2bee4a91-9d92-430e-a87e-ab32d3b1ce47
Window size: width 1262 - height 805
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-26T13:44:50.025Z',mode:absolute,to:'2017-10-26T13:50:50.025Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-26T13:44:50.025Z',mode:absolute,to:'2017-10-26T13:50:50.025Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
To confirm, the above dataset was never crawled on schedule. 

Either crawling is not functioning properly, or not functioning properly for metadata-only datasets (meaning this crawling issue was never fixed https://github.com/gbif/crawler/issues/7).

**Comment by MortenHofft** [comment]
Given that the issue is still open i think you are right. No need for this duplicate then? If so please reopen.
