### ISSUE TITLE
Validator reports dataset can be indexed by GBIF - yet it wasn't in reality

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#590]
**Validator reports dataset can be indexed by GBIF - yet it wasn&#39;t in reality**

[This simple dataset](https://www.gbif.org/dataset/8bed2129-8839-4141-a06f-455b5ce654cc) was registered with GBIF Oct 11 2017, about two weeks ago. 

The validator says it can be indexed by GBIF, yet its two indexing attempts failed: https://registry.gbif.org/web/#/dataset/8bed2129-8839-4141-a06f-455b5ce654cc/crawl 

Either the validator report is misleading (i.e. there is something that prevented the dataset from actually being indexed that isn't reported in the validator report) or there is something wrong with crawling/indexing. A quick look in Kibana doesn't reveal anything and the dataset page only explains that indexing failed, not why. @jlegind can you spot why the dataset never indexed? 

This situation has the potential to seriously frustrate publishers that expect to see their datasets indexed after passing validation. Otherwise, a good explanation should be given to them IMHO.

-----
fbitem-1f0f4a97d97f89f83a44799d9b0020b414b78221
User provided contact info: kbraak
System: Chrome 61.0.3163 / Mac OS X 10.10.5
Referer: https://www.gbif.org/tools/data-validator/1508848348044
Window size: width 1273 - height 843
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-26T13:58:20.639Z',mode:absolute,to:'2017-10-26T14:04:20.639Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-26T13:58:20.639Z',mode:absolute,to:'2017-10-26T14:04:20.639Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
I think this is an indexing issue. The validator seems to produce a valid result.
See gbif/crawler#3
