### ISSUE TITLE
dataset validates ok, but is not indexed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#591]
**dataset validates ok, but is not indexed**

The Mendoza Herbarium dataset (https://www.gbif.org/dataset/f812093f-5e56-42c9-be74-bd85c68e29e7), on individual check at https://www.gbif.org/tools/data-validator/1508848348043#occurrence.txt-Issues, reports no grave issues, and on the dataset page is listed with a successful crawl (Last Successful crawl    26 October 2017 Crawling completion reasons        100% Normal), but is still listed with 0 occurrences. According to the validator result, the Archive contains 1520 records. The inconsistency between the reported successful crawl and the missing records is somewhat confusing, but may refer back to an initial crawl where data content was not yet available (?).

-----
fbitem-dc717a6f1f8b762edc53a34333236e9286f3c14a
User provided contact info: ahahn-gbif
System: Firefox 56.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/tools/data-validator/1508848348043
Window size: width 1162 - height 540
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-26T14:05:07.531Z',mode:absolute,to:'2017-10-26T14:11:07.531Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-26T14:05:07.531Z',mode:absolute,to:'2017-10-26T14:11:07.531Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
I think this is an indexing issue. The validator seems to produce a valid result.
See https://github.com/gbif/crawler/issues/3
