### ISSUE TITLE
dataset downloads API performance

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#594]
**dataset downloads API performance**

https://api.gbif.org/v1/occurrence/download/dataset/aae308f4-9f9c-4cdd-b4ef-c026f48be551?limit=20&locale=en&offset=0

took 26.4 seconds to respond.

That feels like a long time when waiting to see the result. Just flagging this in case anyone has an idea for how it could be improved easily.

-----
fbitem-datasetaae308f4-9f9c-4cdd-b4ef-c026f48be551
User provided contact info: mortenhofft
System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/dataset/aae308f4-9f9c-4cdd-b4ef-c026f48be551/activity
Window size: width 1308 - height 1196
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T06:17:48.661Z',mode:absolute,to:'2017-10-27T06:23:48.661Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T06:17:48.661Z',mode:absolute,to:'2017-10-27T06:23:48.661Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Noting that performance is similar, although the original test was before we moved UAT to boma.

Retest once the new database servers are delivered and set up.

**Comment by MattBlissett** [comment]
Fixed with the new database servers.
