### ISSUE TITLE
I can't download the file through 'source archive'

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#597]
**I can&#39;t download the file through &#39;source archive&#39;**

When I want to download the data, an error link is returned. ("You don't have permission to access /archives/dr756.zip on this server.")

f.e. with this dataset:  https://www.gbif.org/dataset/e45ea07f-d054-4129-9552-f0c9e6af4019 

With regards,

Thomas

-----
fbitem-00ae90e992d97030ba132967cd01faaf2d95344c
User provided contact info: thomas.lanssens@vliz.com
System: Firefox 56.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/faq
Window size: width 1760 - height 838
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T07:25:19.767Z',mode:absolute,to:'2017-10-27T07:31:19.767Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T07:25:19.767Z',mode:absolute,to:'2017-10-27T07:31:19.767Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you for reporting this

Seems that the publisher have closed of downloads of the original dataset for other than the GBIF secretariat. Unfortunately we have no way of detecting that at this point. But it is a good idea - it seems silly to link to something that is forbidden. Sorry about that. We will see if we can find a solution, but of course external links are in the end beyond our control.

> user contacted per mail
