### ISSUE TITLE
Small update required to IPT @Users section

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#599]
**Small update required to IPT @Users section**

An update was recently applied to the IPT Readme, to advise all users to sign up to the IPT Mailing List. 

Please, can the @Users section of this page be updated to mirror the IPT Readme's @Users section? https://github.com/gbif/ipt/blob/master/README.md#users 

Thank you

-----
fbitem-7139f8609c88dfc8d6f63e185b48f05341718691
User provided contact info: kbraak
System: Firefox 56.0.0 / Mac OS X 10.10.0
Referer: https://www.gbif.org/ipt
Window size: width 1410 - height 798
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T08:28:26.715Z',mode:absolute,to:'2017-10-27T08:34:26.715Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T08:28:26.715Z',mode:absolute,to:'2017-10-27T08:34:26.715Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
@dnoesgaard - is this something you can help with please? It should be as simple as just cutting and pasting a single paragraph of text over to the IPT page in Contentful. Thanks in advance for your help.

**Comment by dnoesgaard** [comment]
Done.

**Comment by kbraak** [comment]
Thanks @dnoesgaard
