### ISSUE TITLE
Notes in the end of page content

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#60]
**Notes in the end of page content**

Remove Discussion and the sentence under.

-----
fbitem-57ee03dd725ec36a7faf1f69bca70ff2ef3c507e
Reported by: @dschigel
System: Firefox 51.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/citation-guidelines
Window size: width 1920 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-06T13:12:23.621Z',mode:absolute,to:'2017-02-06T13:18:23.621Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-06T13:12:23.621Z',mode:absolute,to:'2017-02-06T13:18:23.621Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
@kcopas?

**Comment by dnoesgaard** [comment]
this can be closed
