### ISSUE TITLE
Archive reported as "can be indexed" by the validator, but not picked up in indexing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#604]
**Archive reported as &quot;can be indexed&quot; by the validator, but not picked up in indexing**

The validator at https://www.gbif.org/tools/data-validator/1508848348049 reports no issues, yet the dataset is not indexed, apart from the metadata.

-----
fbitem-dataset90837c06-ff84-47ec-b5fd-98c8b8f541f3
User provided contact info: ahahn-gbif
System: Firefox 56.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/dataset/90837c06-ff84-47ec-b5fd-98c8b8f541f3
Window size: width 1280 - height 543
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T11:45:31.686Z',mode:absolute,to:'2017-10-27T11:51:31.686Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T11:45:31.686Z',mode:absolute,to:'2017-10-27T11:51:31.686Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
This was an indexing issue. The data validator was correctly stating that the dataset was indexable.
I see that it is now correctly indexed.
