### ISSUE TITLE
feedback form incomplete on smaller screens

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#605]
**feedback form incomplete on smaller screens**

E.g. on my laptop screen, the feedback form (= this) is not fully visible, and does not scroll with the main screen. This means that parts of the form are not visible and not accessible, including the submit button (screenshot to follow).

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
User provided contact info: ahahn-gbif
System: Firefox 56.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/
Window size: width 1280 - height 543
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T11:49:57.797Z',mode:absolute,to:'2017-10-27T11:55:57.797Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T11:49:57.797Z',mode:absolute,to:'2017-10-27T11:55:57.797Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
![feedbackform](https://user-images.githubusercontent.com/13435656/32103070-3c66139a-bb1f-11e7-8c42-7816d83840ce.jpg)

**Comment by MortenHofft** [comment]
Hi @ahahn-gbif 
Thanks. Yes it should always be possible to provide feedback. 

If the window height is less than 580px you cannot see the whole form - unless it is also narrow in which case it triggers a mobile layout. I see that yours is 543 pixels. Do you know what your screen resolution is? And is this the maximum window size? Just to better understand the cases that I need to account for.

**Comment by MortenHofft** [comment]
Based on google analytics 2% of our users have a screen with 1280x720. If that browser has a fat header (like in the screen shot), then it leaves very little available screen space. It might be a less rewarding experience, but all essential content should be available on all sizes.

**Comment by ahahn-gbif** [comment]
The window is full size, resolution 1920x1080. Top toolbars (bookmarks and menu) deactivated pulls it up some, but not enough to make it fully visible.

**Comment by ahahn-gbif** [comment]
Setting it to a small window (mobile) layout gives the form a scroll bar, which is all I'd really need on the full version as well.

**Comment by MortenHofft** [comment]
But that isn't pretty!! We can't have that. I've made a separate version for that screen size interval. Will be available on next deployment. thanks
