### ISSUE TITLE
GBIF metadata

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#608]
**GBIF metadata**

Hi !

The webpage found at :

http://rs.gbif.org/schema/eml-gbif-profile/dev/eml-gbif-profile.xsd

does not print properly. 

My naive guess is that there is something missing in the XML code used to present the web page.

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
User provided contact info: guillaume.blanchet@usherbrooke.ca
System: Chrome 61.0.3163 / Mac OS X 10.12.6
Referer: https://www.gbif.org/
Window size: width 1392 - height 763
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T15:18:52.996Z',mode:absolute,to:'2017-10-27T15:24:52.996Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T15:18:52.996Z',mode:absolute,to:'2017-10-27T15:24:52.996Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
I'm not sure it's really meant for printing, other than by opening in a text editor.
