### ISSUE TITLE
Scientific name status

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#609]
**Scientific name status**

I am looking for documentation on what the status of a scientific name is based on and how it is updated; i.e. accepted, synonym etc. I haven't been able to find any describtion of this, but I have sure I just haven't look in the right place. Thank you in advance.

-----
fbitem-00ae90e992d97030ba132967cd01faaf2d95344c

System: IE 11.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/faq?q=name%20status
Window size: width 1920 - height 927
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T16:36:32.591Z',mode:absolute,to:'2017-10-27T16:42:32.591Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-27T16:36:32.591Z',mode:absolute,to:'2017-10-27T16:42:32.591Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi @dnoesgaard - no contact info, but still interesting that it is missed information. It isn't anywhere is it?

**Comment by dnoesgaard** [comment]
I don't know but could make for a good FAQ entry.

@mdoering - is this described somewhere obvious?

**Comment by IBDJ** [comment]
Hi @MortenHofft and @dnoesgaard I submitted the question. I thought my contact info would be pulled from GBIF log in. I tried looking in the FAQ, but couldn't find it. I was thinking it could still be somewhere else obvious and I just wasn't able to find it.

**Comment by mdoering** [comment]
I assume we talk about the GBIF Backbone here. I think it would be best if there would be a page in the portal that describes what the Backbone is and how it is created & maintained.

The taxonomic status of a name is defined by the underlying source with the highest priority, in many cases this is the CoL. The nomenclatural status of a name (e.g. nom inval) is unfortunately not being processed properly currently.

**Comment by mdoering** [comment]
@MortenHofft if we agree on a new page to document the backbone building please let me know where and how I should do so. I would love to use a plain Markdown doc in the checklistbank repo, basically updating this to make this more readable, less tekkie and up to date: https://github.com/gbif/checklistbank/blob/master/docs/BACKBONE.md#2-backbone-building

**Comment by dnoesgaard** [comment]
We could do a simple article page, and link to it from 1) an FAQ entry, 2) the backbone dataset [page](https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c), and possibly other places...

@mdoering - this would be maintained in Contentful, but because we have limited users on our plan, I would set it up. If you prefer to do the text in GitHub, fine with me. I can just grab the MD from here and put it into Contentful...

**Comment by mdoering** [comment]
great. I'd rather have it next to the CLB code as part of its documentation. Ill send the MD file to you when ready. Probably not before 2 weeks as Im gone all of next week

**Comment by mdoering** [comment]
see gbif/checklistbank#44
