### ISSUE TITLE
Validator

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#612]
**Validator**

Reports DWCA_Unreadable for DwCa Zip files and .csv files generated by the AVH, i..e . from the ALA cache ...
http://avh.ala.org.au

-----
fbitem-93ef7bb632945f8be5bdfd0f5468b5599b7719d3
User provided contact info: ja_cooper@hotmail.com
System: Chrome 61.0.3163 / Windows 7 0.0.0
Referer: https://www.gbif.org/tools/data-validator/1508848348067
Window size: width 1920 - height 900
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-30T08:30:28.910Z',mode:absolute,to:'2017-10-30T08:36:28.910Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-30T08:30:28.910Z',mode:absolute,to:'2017-10-30T08:36:28.910Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by thomasstjerne** [comment]
User contacted by email. Asked to send the archive for further investigation

**Comment by thomasstjerne** [comment]
Archive recieved. It is a zip including 3 csv´s and a html file - not a Darwin Core archive.
