### ISSUE TITLE
Doubtful/Accepted is sometimes assigned in a weird way

### ISSUE THREAD

**Issue by andzandz11** [gbif/portal-feedback#613]
https://www.gbif.org/search?q=Centaurea%20scabiosa

Why is the species with the correct author "DOUBTFUL" according to your API (https://api.gbif.org/v1/species/match query: Centaurea scabiosa L.) and the one without author has no "issues" assigned? (like: missing author?)

It seems they should be merged? Shouldn't some sort of automatic action be in place if there are two identical species names, one without an author and the other one with an author name if species B is a) present in more databases b) has more occurence counts and c) has a proper citation?
It seems the "accepted" "doubtful" algorithm needs some fine tuning?

ps: even weirder
https://www.gbif.org/species/8744097
https://www.gbif.org/species/3121319
Why?

Or this one:
The accepted species is a synonym of a doubtful species? (although they have the same name, the accepted species is lacking the author) This makes no sense at all.
https://www.gbif.org/species/9221087
https://www.gbif.org/species/3120060

Here is a list of plats that are possibly affected too (they returned doubtful, although they are from a manually curated plant list):

no| sci_name | auth
1 | Achillea atrata | L.
2 | Achillea clavennae | L.
3 | Achillea millefolium | L.
4 | Achillea nobilis | L.
5 | Achillea ptarmica | L.
6 | Achillea salicifolia | Besser
7 | Aconitum pilipes | (Rchb.) Gáyer
8 | Adenostyles alliariae | (Gouan) Kern.
9 | Adenostyles alpina | (L.) Bluff & Fingerh.
10 | Aethionema saxatile | (L.) R. Br.
11 | Alchemilla hoppeana | (Rchb.) Dalla Torre
12 | Alchemilla splendens | Christ ex Gremli
13 | Ambrosia psilostachya | DC.
14 | Ambrosia trifida | L.
15 | Anaphalis margaritacea | (L.) Benth.
16 | Antennaria carpatica | (Wahlenb.) Bluff & Fingerh.
17 | Antennaria dioica | (L.) J. Gaertn.
18 | Anthemis arvensis | L.
19 | Anthemis cotula | L.
20 | Anthemis ruthenica | M. Bieb.
21 | Aposeris foetida | (L.) Less.
22 | Arctium lappa | L.
23 | Arctium minus | (Hill) Bernh.
24 | Arctium nemorosum | Lej.
25 | Arctium tomentosum | Mill.
26 | Armeria maritima | (Mill.) Willd.
27 | Arnica montana | L.
28 | Artemisia absinthium | L.
29 | Artemisia annua | L.
30 | Artemisia austriaca | Jacq.
31 | Artemisia biennis | Willd.
32 | Artemisia campestris | L.
33 | Artemisia dracunculus | L.
34 | Artemisia laciniata | Willd.
35 | Artemisia maritima | L.
36 | Artemisia rupestris | L.
37 | Artemisia scoparia | Waldst. & Kit.
38 | Artemisia tournefortiana | Rchb.
39 | Artemisia verlotiorum | Lamotte
40 | Artemisia vulgaris | L.
41 | Aster alpinus | L.
42 | Aster amellus | L.
43 | Atocion armeria | (L.) Rafin.
44 | Barbarea vulgaris | R. Br.
45 | Bellis perennis | L.
46 | Bidens cernua | L.
47 | Bidens connata | Muhl. ex Willd.
48 | Bidens frondosa | L.
49 | Bidens radiata | Thuill.
50 | Bidens tripartita | L.
51 | Buphthalmum salicifolium | L.
52 | Calamintha foliosa | Opiz
53 | Calendula arvensis | L.
54 | Calendula officinalis | L.
55 | Cardamine heptaphylla | (Vill.) O. E. Schulz
56 | Carduus acanthoides | L.
57 | Carduus crispus | L.
58 | Carduus defloratus | L.
59 | Carduus nutans | L.
60 | Carduus personata | (L.) Jacq.
61 | Carduus tenuiflorus | Curtis
62 | Carex capitata | L.
63 | Carex depauperata | Curtis ex With.
64 | Carlina acaulis | L.
65 | Carlina biebersteinii | Bernh. ex Hornem.
66 | Carlina vulgaris | L.
67 | Carpesium cernuum | L.
68 | Catapodium rigidum | (L.) C. E. Hubb. ex Dony
69 | Centaurea calcitrapa | L.
70 | Centaurea diffusa | Lam.
71 | Centaurea nigrescens | Willd.
72 | Centaurea phrygia | L.
73 | Centaurea preissmannii | Hayek
74 | Centaurea scabiosa | L.
75 | Centaurea solstitialis | L.
76 | Centaurea stoebe | L.
77 | Centaurea thuillieri | (Dostál) J. Duvign. & Lambinon
78 | Chondrilla chondrilloides | (Ard.) H. Karst.
79 | Chondrilla juncea | L.
80 | Cichorium intybus | L.
81 | Cirsium dissectum | (L.) Hill
82 | Cirsium eriophorum | (L.) Scop.
83 | Cirsium heterophyllum | (L.) Hill
84 | Cirsium oleraceum | (L.) Scop.
85 | Cirsium rivulare | (Jacq.) All.
86 | Cirsium spinosissimum | (L.) Scop.
87 | Cirsium tuberosum | (L.) All.
88 | Cotula coronopifolia | L.
89 | Crepis alpestris | (Jacq.) Tausch
90 | Crepis aurea | (L.) Cass.
91 | Crepis biennis | L.
92 | Crepis capillaris | (L.) Wallr.
93 | Crepis conyzifolia | (Gouan) Kern.
94 | Crepis foetida | L.
95 | Crepis jacquinii | Tausch
96 | Crepis mollis | (Jacq.) Asch.
97 | Crepis paludosa | (L.) Moench
98 | Crepis pontana | (L.) Dalla Torre
99 | Crepis praemorsa | (L.) Walther
100 | Crepis pulchra | L.
101 | Crepis pyrenaica | (L.) Greuter
102 | Crepis setosa | Haller f.
103 | Crepis tectorum | L.
104 | Crepis terglouensis | (Hacq.) Kern.
105 | Crepis vesicaria | L.
106 | Dittrichia graveolens | (L.) Greuter
107 | Doronicum austriacum | Jacq.
108 | Doronicum columnae | Ten.
109 | Doronicum glaciale | (Wulfen) Nyman
110 | Doronicum grandiflorum | Lam.
111 | Doronicum pardalianches | L.
112 | Drymocallis rupestris | L.
113 | Echinops bannaticus | Rochel ex Schrad.
114 | Echinops exaltatus | Schrad.
115 | Echinops sphaerocephalus | L.
116 | Erigeron acris | L.
117 | Erigeron alpinus | L.
118 | Erigeron atticus | Vill.
119 | Erigeron canadensis | L.
120 | Erigeron neglectus | Kern.
121 | Erigeron schleicheri | Gremli
122 | Erigeron sumatrensis | Retzius
123 | Erigeron uniflorus | L.
124 | Eriophorum gracile | W. D. J. Koch ex Roth
125 | Erysimum marschallianum | Andrz. ex DC.
126 | Eupatorium cannabinum | L.
127 | Euphrasia stricta | D. Wolff ex J. F. Lehm.
128 | Eurybia macrophylla | (L.) Cass.
129 | Filago arvensis | L.
130 | Filago gallica | L.
131 | Filago germanica | L. Huds.
132 | Filago lutescens | Jord.
133 | Filago minima | (Sm.) Pers.
134 | Filago neglecta | (Soy.-Will.) DC.
135 | Filago pyramidata | L.
136 | Galatella linosyris | (L.) Rchb.
137 | Galinsoga parviflora | Cav.
138 | Galium valdepilosum | Heinr. Braun
139 | Glebionis segetum | (L.) Fourr.
140 | Gnaphalium hoppeanum | W. D. J. Koch
141 | Gnaphalium norvegicum | Gunnerus
142 | Gnaphalium supinum | L.
143 | Gnaphalium sylvaticum | L.
144 | Gnaphalium uliginosum | L.
145 | Grindelia squarrosa | (Pursh) Dunal
146 | Guizotia abyssinica | (L.f.) Cass.
147 | Helianthus pauciflorus | Nutt.
148 | Helianthus tuberosus | L.
149 | Helichrysum arenarium | (L.) Moench
150 | Helminthotheca echioides | (L.) Holub
151 | Homogyne alpina | (L.) Cass.
152 | Homogyne discolor | (Jacq.) Cass.
153 | Hypochaeris glabra | L.
154 | Hypochaeris maculata | L.
155 | Hypochaeris radicata | L.
156 | Hypochaeris uniflora | Vill.
157 | Inula britannica | L.
158 | Inula ensifolia | L.
159 | Inula germanica | L.
160 | Inula helenium | L.
161 | Inula helvetica | Weber
162 | Inula hirta | L.
163 | Inula salicina | L.
164 | Iva xanthiifolia | Nutt.
165 | Jurinea cyanoides | (L.) Rchb.
166 | Lactuca perennis | L.
167 | Lactuca quercina | L.
168 | Lactuca saligna | L.
169 | Lactuca serriola | L.
170 | Lactuca tatarica | (L.) C. A. Mey.
171 | Lactuca viminea | (L.) J. Presl & C. Presl
172 | Lactuca virosa | L.
173 | Lapsana communis | L.
174 | Leontodon hispidus | L.
175 | Leontodon incanus | (L.) Schrank
176 | Leontodon saxatilis | Lam.
177 | Lepidium campestre | (L.) R. Br.
178 | Leucanthemopsis alpina | (L.) Heywood
179 | Leucanthemum adustum | (W. D. J. Koch) Gremli
180 | Leucanthemum halleri | (Vitman) Ducommun
181 | Leucanthemum vulgare | Lam.
182 | Luzula luzulina | (Vill.) Dalla Torre & Sarnth.
183 | Luzula nivea | (L.) DC.
184 | Matricaria discoidea | DC.
185 | Melilotus officinalis | (L.) Lam.
186 | Muscari armeniacum | Baker
187 | Myosotis ramosissima | Rochel ex Schult.
188 | Nasturtium officinale | R. Br.
189 | Onopordum acanthium | L.
190 | Orobanche lucorum | F. W. Schultz
191 | Orobanche salviae | F. W. Schultz
192 | Petasites albus | (L.) J. Gaertn.
193 | Petasites hybridus | (L.) G. Gaertn., B. Mey. & Scherb.
194 | Petasites paradoxus | (Retz.) Baumg.
195 | Petasites spurius | (Retz.) Rchb.
196 | Petrocallis pyrenaica | (L.) R. Br.
197 | Picris hieracioides | L.
198 | Plantago strictissima | L.
199 | Potamogeton acutifolius | Link
200 | Potentilla brauneana | Hoppe ex Nestl.
201 | Potentilla thuringiaca | Bernh.
202 | Prenanthes purpurea | L.
203 | Pulicaria dysenterica | (L.) Bernh.
204 | Pulsatilla alpina | (L.) Delarbre
205 | Ranunculus stricticaulis | W. Koch
206 | Rosa subcanina | (H. Christ) R. Keller
207 | Rubus albiflorus | Boulay & Lucand
208 | Rubus amiantinus | (Focke) Foerster
209 | Rubus bavaricus | (Focke) Hruby
210 | Rubus bombycinus | Matzk.
211 | Rubus bonus-henricus | Matzk.
212 | Rubus buhnensis | (G. Braun ex Focke) G. Braun
213 | Rubus carduelis | Matzk.
214 | Rubus distortifolius | Matzk.
215 | Rubus elatior | Focke ex Gremli
216 | Rubus infestus | Weihe
217 | Rubus klimmekianus | Matzk.
218 | Rubus lidforssii | (Gelert) Lange
219 | Rubus lusaticus | Rostock
220 | Rubus mortensenii | E. H. L. Krause
221 | Rubus ripuaricus | Matzk.
222 | Rubus siekensis | Banning ex G.Braun
223 | Rubus speculatus | Matzk.
224 | Rubus transvestitus | Matzk.
225 | Rubus ubericus | Matzk.
226 | Rudbeckia hirta | L.
227 | Rudbeckia laciniata | L.
228 | Saussurea alpina | (L.) DC.
229 | Saussurea discolor | (Willd.) DC.
230 | Saussurea pygmaea | (Jacq.) Spreng.
231 | Schlagintweitia huteri | (Bamb.) Gottschl. & Greuter
232 | Schlagintweitia intybacea | (All.) Griseb.
233 | Scorzonera austriaca | Willd.
234 | Scorzonera hispanica | L.
235 | Scorzonera humilis | L.
236 | Scorzonera parviflora | Jacq.
237 | Scorzoneroides autumnalis | (L.) Moench
238 | Sempervivum funckii | Braun ex W. D. J. Koch
239 | Senecio doronicum | (L.) L.
240 | Senecio hercynicus | Herborg
241 | Senecio inaequidens | DC.
242 | Senecio nemorensis | L.
243 | Senecio ovatus | (G. Gaertn., B. Mey. & Scherb.) Willd.
244 | Senecio sarracenicus | L.
245 | Senecio sylvaticus | L.
246 | Senecio viscosus | L.
247 | Senecio vulgaris | L.
248 | Serratula tinctoria | L.
249 | Sigesbeckia serrata | DC.
250 | Silybum marianum | (L.) J. Gaertn.
251 | Solidago canadensis | L.
252 | Solidago gigantea | Aiton
253 | Solidago virgaurea | L.
254 | Sonchus arvensis | L.
255 | Sonchus asper | (L.) Hill
256 | Sonchus oleraceus | L.
257 | Sonchus palustris | L.
258 | Spiraea alba | Du Roi
259 | Stellaria palustris | Ehrh. ex Hoffm.
260 | Symphyotrichum lanceolatum | (Willd.) G. L. Nesom
261 | Symphyotrichum novae-angliae | (L.) G. L. Nesom
262 | Symphyotrichum novi-belgii | (L.) G. L. Nesom
263 | Tanacetum balsamita | L.
264 | Tanacetum macrophyllum | (Waldst. & Kit.) Sch. Bip.
265 | Tanacetum partheniifolium | (Willd.) Sch. Bip.
266 | Teesdalia nudicaulis | (L.) R. Br.
267 | Telekia speciosa | (Schreb.) Baumg.
268 | Tephroseris crispa | (Jacq.) Rchb.
269 | Tephroseris helenitis | (L.) B. Nord.
270 | Tephroseris integrifolia | (L.) Holub
271 | Tragopogon orientalis | L.
272 | Tragopogon pratensis | L.
273 | Trifolium ornithopodioides | L.
274 | Tripleurospermum maritimum | (L.) W. D. J. Koch
275 | Tripolium pannonicum | (von Jacquin) Dobrotschajewa-Kowaltschuk
276 | Tussilago farfara | L.
277 | Viola bavarica | Schrank
278 | Willemetia stipitata | (Jacq.) Dalla Torre
279 | Xanthium spinosum | L.
280 | Xanthium strumarium | L.

**Comment by andzandz11** [comment]
I don't know about other kingdoms, but for plants the most convinient way would be to assign "doubtful" and "acceptetd" by checking Tropicos and Catalogue of Life and if both assign the "accepted" tag to a species+author combination to incorporate this information into the GBIF backbone and give all other species with the same name the "doubtful" tag.
The more elegant way would be to calculate an acceptance score (like Tropicos), possible parameters are: # of occurences, # of databases that also have the same species+author combination, # how complete is my information about this species (author? proper citation? how many times is it cited in literature? (the last one is probably a bad idea because it is very conservative) # etc.) 

One more example:
https://www.gbif.org/search?q=Hypochaeris%20uniflora
GBIF correctly imports the information that Hypochaeris uniflora (Biv.) Kuntze is a synonym. https://www.gbif.org/species/131424618
But it is not reflected in the backbone, because the backbone cites IPNI as a source for Hypochaeris uniflora (Biv.) Kuntze, however IPNI does not even have information on synonyms in thier databse in general.

**Comment by mdoering** [comment]
Hypochaeris uniflora is now fixed and treated as a synonym, not doubtful.

When we find several names with different authorships for the same "canonical" name the backbone selects the version from the most trusted source as the acceted and marks all others as doubtful. That means CoL is always followed as it comes first. IPNI only much later when we cannot find any other evidence. But updating our backbone is happening very slow unfortunately, so many changes are already visible in some of the sources while not applied to the backbone.

I can confirm the start of your list is also accepted now. I will rematch all your list when we go live

**Comment by mdoering** [comment]
I have uploaded the [above species](https://github.com/gbif/portal-feedback/files/1723292/issues-613.txt) into the [species matching batch tool](https://www.gbif.org/tools/species-lookup) to yield the [attached spreadsheet issues-613.xlsx](https://github.com/gbif/portal-feedback/files/1723290/issues-613.xlsx).

All names match with the exact spelling.
221 of the 280 are treated as accepted names, 42 as doubtful and 17 as synonyms.

The example of Artemisia absinth(i)um L. is a uncaught orthographic variant from the types dataset which is wrong, but not a software bug. Achillea millefolium Ledeb (from IPNI) should be considered doubtful if we dont know about any synonymy and the Linnaeus version accepted, thats correct.

There are still 165 thousand doubtful plant species:
https://www.gbif.org/species/search?rank=SPECIES&highertaxon_key=6&status=DOUBTFUL

36276 of them are flagged as very likely orthographic variants.
Quite a few others are named hybrids. I wonder if that is related. Examples are `Rubus ×furcipetalus Sudre & Bouvet` or `Rubus ×semivelatus Sudre`

**Comment by mdoering** [comment]
I am closing the issue now that I cannot find a doubtful species that is incorrectly labeled as doubtful

**Comment by andzandz11** [comment]
Amazing! Thank you very much, now I can continue working :) All seems well. Before the backbone update all 280 were doubtful.

A lot of the genus Rubus is doubtful, but that is only because taxonomists seem to be arguing about species boundaries in that genus. I would pick another genus that is less complicated if you want to check how to reduce the number of "doubtful"s.
Thanks! The most common German plants are now correctly respresented.
