### ISSUE TITLE
Add images to country participant pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#614]
**Add images to country participant pages**

@dnoesgaard In contentful there is the option to add images to all country pages. That might be a nice addition to these pages as well?

-----
fbitem-7acd245d969836bce8ab7733875f7b34eb332e23
User provided contact info: mortenhofft
System: Chrome 61.0.3163 / Mac OS X 10.11.6
Referer: https://www.gbif.org/country/ES/participation
Window size: width 1920 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-30T10:52:24.922Z',mode:absolute,to:'2017-10-30T10:58:24.922Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-30T10:52:24.922Z',mode:absolute,to:'2017-10-30T10:58:24.922Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
We had a talk about this and we don't really see the need for images on country (participant) pages. We did agree that being able to include an optional logo would be nice. What do you think, @ mortenhofft?

**Comment by MortenHofft** [comment]
No need - but looks nicer in my opinion https://www.gbif-dev.org/country/AU/participation

![screen shot 2017-10-30 at 13 35 28](https://user-images.githubusercontent.com/6759267/32171018-3bdd0c4e-bd77-11e7-8bc5-e4e2abd732bf.png)

Logo: we can add that as a special field. Or you can also just add it to the markdown as an image in the cases where you need it. How where did you imagine it being used? Anyhow i guess that is a separate issue. it was created in Jira long ago and moved here https://github.com/gbif/portal16/issues/607

**Comment by MortenHofft** [comment]
Closing this as a won't fix then
