### ISSUE TITLE
Dataset contact

### ISSUE THREAD

**Issue by DimEvil** [gbif/portal-feedback#615]
Hi,

On https://www.gbif.org/dataset/8ae09016-b819-450e-b8f6-c1f249110502 I'm the contact for the dataset (Which I should not ne) while the enveloppe is not to be seen next to the originally provided (in IPT) resource contacts. Is this a bug?

**Comment by MortenHofft** [comment]
If you do not wish to be a contact I suggest adding a mail to an administrative contact (could just be a info@... one) - let me know if you believe that it should be removed, but I personally find it to be convenient to know whom i can write to. And currently you are the only one. I'll close for now

**Comment by DimEvil** [comment]
No, it's ok. I forgot to complete the other email addresses.
