### ISSUE TITLE
[idea] search filter: year or not to year

### ISSUE THREAD

**Issue by andzandz11** [gbif/portal-feedback#616]
I want to search: occurence of species XY before 1900 OR without year.
However, currently that is not possible. As soon as I move the year slider, the year must have a definite value. (?)

side question: If I discover data not being transferred correctly, (data correctly in the original dataset, but in GBIF there is something missing, like year or author) the problem is most likely a technical issue at the dataset provider. Should I contact the dataset provider and let them sort things out (most likely they will contact you for technical assistance), or contact you so you can sort things out together with the dataset provider? (it is also more likely they will act quickly if an email comes from you)

**Comment by MortenHofft** [comment]
**occurrence queries**
The interface only allows for a subset of queries. For more complex requests I suggest that you either download the data and do additional filtering or [use the API](https://www.gbif.org/developer/occurrence#download). We have a standing issue to allow NOT queries in the interface. Unfortunately it requires a lot of changes to our APIs at this point. But we are aware that it would be useful.

For that search you would have to use the API. Unfortunately it isn't working as expected at this moment - i have made an example for you here
https://www.gbif.org/occurrence/download/0002625-171025204727650
Notice asked by inverting the query.

So at this point you best option is to download them all and do the filtering locally.

**Dataset updates**
Regarding dataset issues you should contact the dataset owner yes. Most of them are eager to get their data fixed and now how to update it. Thank you!
