### ISSUE TITLE
Documentation about issues found

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#618]
**Documentation about issues found**

What Taxon match fuzzy means? All validation issues can have some tooltip explaining their meaning.

-----
fbitem-8f75c0e1a204b4afded19b7ef070b8e213cfbc65
User provided contact info: dvdscripter
System: Firefox 56.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/tools/data-validator/1508848348069
Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-30T13:57:03.457Z',mode:absolute,to:'2017-10-30T14:03:03.457Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-30T13:57:03.457Z',mode:absolute,to:'2017-10-30T14:03:03.457Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
This is closely related to https://github.com/gbif/portal-feedback/issues/609 but in the context of the validator. Might also interest you @dnoesgaard

**Comment by dnoesgaard** [comment]
Indeed. Where do these validation issues live? Are they explained anywhere?
