### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#619]
**broken link**

On Become a publisher page:
The 'GBIF Participant node' link (https://www.gbif.org/participation/participant-list) is broken.

-----
fbitem-ab3ccb02d409d7c1b6652ceee60e3937ce068b3e
User provided contact info: a.heughebaert@biodiversity.be
System: Chrome 61.0.3163 / Mac OS X 10.12.6
Referer: https://www.gbif.org/become-a-publisher
Window size: width 873 - height 747
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-30T14:09:08.654Z',mode:absolute,to:'2017-10-30T14:15:08.654Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-30T14:09:08.654Z',mode:absolute,to:'2017-10-30T14:15:08.654Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Thanks, André. Link updated and redirected to the network page.
