### ISSUE TITLE
Old validator provided better results for this archive

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#621]
**Old validator provided better results for this archive**

http://ipt.biologi.lipi.go.id/archive.do?r=hb-rcb

In this case, the previous validator reported "The core data file contains non unique core IDs:" but in the new one it just fails without hint as to why

-----
fbitem-066f438500c724cac3af4f667be0f432015473ff
User provided contact info: timrobertson100
System: Chrome 61.0.3163 / Mac OS X 10.11.5
Referer: https://www.gbif.org/tools/data-validator
Window size: width 1387 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-30T16:04:14.738Z',mode:absolute,to:'2017-10-30T16:10:14.738Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-30T16:04:14.738Z',mode:absolute,to:'2017-10-30T16:10:14.738Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
The response from the validator API is simply
```
jobId : -1,
status : "FAILED"
```

**Comment by thomasstjerne** [comment]
Transferred to https://github.com/gbif/gbif-data-validator/issues/61
