### ISSUE TITLE
Trend charts missing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#623]
**Trend charts missing**

It looks like the trend charts exist but aren't loading properly. 

But since Indonesia has 0 occurrence records, I'm guessing that its publishing trend charts are empty, even if they did exist on disk. 

I'd recommend not showing publishing trend charts for countries with 0 records. The same could probably be said for the taxa icons at the top, each with 0 records.

![screen shot 2017-10-31 at 11 48 40](https://user-images.githubusercontent.com/5981100/32220295-8547814c-be31-11e7-87f2-7841b69747fa.png)

-----
fbitem-1a5d87df214f242141c5b856190ba2e0e40e50a4
User provided contact info: kbraak
System: Safari 10.1.2 / Mac OS X 10.10.5
Referer: https://www.gbif.org/country/ID/publishing
Window size: width 1324 - height 1075
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-31T10:43:18.305Z',mode:absolute,to:'2017-10-31T10:49:18.305Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-31T10:43:18.305Z',mode:absolute,to:'2017-10-31T10:49:18.305Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Indeed. I'm surprised to see that. thanks

**Comment by MortenHofft** [comment]
Turns out it naively just look for datasets from the country. And if there is any show all info we have.

**Comment by MortenHofft** [comment]
Used the about count instead of the published count to decide on showing the data.
