### ISSUE TITLE
Meta data is one word

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#625]
**Meta data is one word**

Submenu at the top shows META DATA but I think it should read  METADATA

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c
User provided contact info: *BATMAN*
System: Chrome 61.0.3163 / Mac OS X 10.11.5
Referer: https://www.gbif.org/dataset/search?q=
Window size: width 1387 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-31T11:27:14.295Z',mode:absolute,to:'2017-10-31T11:33:14.295Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-31T11:27:14.295Z',mode:absolute,to:'2017-10-31T11:33:14.295Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
+1
