### ISSUE TITLE
Loxodonta Occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#626]
**Loxodonta Occurrences**

Hi, 

I recently sent in an API request for all occurrences of Loxodonta (African elephants), and all the results (about 400) I received had event time between 2015 and 2017.  Logically speaking, there should be some observations before 2015, so I want to know if 2015-2017 contains all the data GBIF has on this species or there's some search parameter I can define in order to get more data.

Thanks,

-----
fbitem-b1018fb447ec8b1aa84ee420b36825314783d5a9

System: Chrome 61.0.3163 / Windows 10 0.0.0
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1280 - height 566
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-31T23:11:16.277Z',mode:absolute,to:'2017-10-31T23:17:16.277Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-31T23:11:16.277Z',mode:absolute,to:'2017-10-31T23:17:16.277Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
> No user contact provided

https://www.gbif.org/species/2435350 is the species in question i think. There are [5927](https://www.gbif.org/occurrence/search?taxon_key=2435348) occurrences and [3632 before 2015](https://www.gbif.org/occurrence/search?taxon_key=2435348&year=*,2014)

API call
http://api.gbif.org/v1/occurrence/search?taxonKey=2435348

Perhaps you had the wrong species?
