### ISSUE TITLE
Is there a common map projection for all coordinates for occurrences found on GBIF?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#629]
**Is there a common map projection for all coordinates for occurrences found on GBIF?**

I need to know what the map projection is for the coordinates, so when I project all the occurrence data from multiple datasets, they are an accurate projection. Some state "coordinate reprojected" but does not state what the new projection is, while others state "GEODETIC_DATUM_ASSUMED_WGS84"

-----
fbitem-00ae90e992d97030ba132967cd01faaf2d95344c
User provided contact info: sayamada@vt.edu
System: Chrome 61.0.3163 / Windows 10 0.0.0
Referer: https://www.gbif.org/faq?q=coordinates
Window size: width 958 - height 929
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-01T14:24:18.313Z',mode:absolute,to:'2017-11-01T14:30:18.313Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-01T14:24:18.313Z',mode:absolute,to:'2017-11-01T14:30:18.313Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
They all end up as WGS84 but are only reprojected in case we know about their original CRS different from WGS84

**Comment by MortenHofft** [comment]
@dnoesgaard another one for the FAQ perhaps
