### ISSUE TITLE
Rhamnus ilicifolia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#630]
**Rhamnus ilicifolia**

I am trying to download the occurrences for this species that appear to be in GBIF.  It shows over 2900 records, but when switching to the synonym (Ventia crocea subsp. ilicifolia) it then returns 0 records.

I am currently working on a fire modelling project for this species, and would really like to have access to that data.
Thanks,
Matt

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
User provided contact info: mattab@appliedeco.org
System: Chrome 61.0.3163 / Windows 7 0.0.0
Referer: https://www.gbif.org/search?q=Ventia%20crocea%20subsp.%20ilicifolia%20(Kellogg)%20Hauenschild
Window size: width 1440 - height 769
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-01T20:56:01.171Z',mode:absolute,to:'2017-11-01T21:02:01.171Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-01T20:56:01.171Z',mode:absolute,to:'2017-11-01T21:02:01.171Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you for reporting it.
We recently added redirect for counts to their synonyms. But seemingly something slipped through the testing. I've reverted to previous behaviour for now.

to download the 2,695 results for Rhamnus ilicifolia Kellogg go here
https://www.gbif.org/occurrence/download?taxon_key=3039489

the synonym now have the occurrences as well
https://www.gbif.org/species/3039489

but the accepted name is missing the occurrences as that is a subspecies. This is a shame and shouldn't be like that, but at least you can now see the data and download it.

>user contacted per mail
