### ISSUE TITLE
Can't send the data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#631]
**Can&#39;t send the data**

I'm trying to download some data and it always put that you are not currently available to send me this date. That happened for almost two hours.

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
User provided contact info: pag0026
System: Opera 48.0.2685 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/download?country=ES&has_coordinate=true&has_geospatial_issue=false&taxon_key=5959092&taxon_key=2497306&taxon_key=2437760&taxon_key=2435687&taxon_key=2497921&taxon_key=2438162
Window size: width 1326 - height 658
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-02T11:08:35.371Z',mode:absolute,to:'2017-11-02T11:14:35.371Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-02T11:08:35.371Z',mode:absolute,to:'2017-11-02T11:14:35.371Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I've just started the download - so far it works from here. Waiting for the mail.

**Comment by MortenHofft** [comment]
download worked for me https://www.gbif.org/occurrence/download/0004714-171025204727650
Odd. User hasn't left any contact info - it isn't a github username

**Comment by MortenHofft** [comment]
Ahh - the users email is invalid. This is from the logs

```
http://api.gbif.org/v1/occurrence/search/download/?country=ES&format=SIMPLE_CSV&has_coordinate=true&has_geospatial_issue=false&locale=en&taxon_key=5959092&taxon_key=2497306&taxon_key=2437760&taxon_key=2435687&taxon_key=2497921&taxon_key=2438162&notification_address=pag0026
```

That shouldn't be possible to have in the database.

**Comment by MattBlissett** [comment]
I can't see anything similar in the logs, can you?

**Comment by MortenHofft** [comment]
No - I see the same logs as you i assume? I guess it would be nice to send an error when creating the download if the users email is invalid.
Perhaps we should simply purge all accounts that doesn't have an email?

**Comment by MattBlissett** [comment]
I don't see any invalid emails, or accounts without one.
