### ISSUE TITLE
info

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#632]
**info**

can i get all species data from a single family or order name?
King regards, 
Umberto Lazzaro

-----
fbitem-1f059dd0d137ccd641e791a2992ee7e29204a773
User provided contact info: umbertolazzaro@libero.it
System: Firefox 56.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/species/search
Window size: width 1366 - height 659
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-02T13:37:28.374Z',mode:absolute,to:'2017-11-02T13:43:28.374Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-02T13:37:28.374Z',mode:absolute,to:'2017-11-02T13:43:28.374Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by andzandz11** [comment]
What is "species data"? Occurence data or a list of all species associated to that family/order?

**Comment by MortenHofft** [comment]
Sure like this:
https://www.gbif.org/occurrence/download?taxon_key=42

All data about Annelida in GBIF (notice this isn't filtering out suspicious data)

>send by mail
