### ISSUE TITLE
Download Fungi Species List

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#634]
**Download Fungi Species List**

Hello, 

Is it possible to download just a portion of the gbif taxonomy backbone? I am interested in getting a list of described fungi species.

Thanks

Rick

-----
fbitem-dataset7ddf754f-d193-4cc9-b351-99906754a03b
User provided contact info: richard.levy@botanicgardens.org
System: Chrome 61.0.3163 / Windows 7 0.0.0
Referer: https://www.gbif.org/dataset/7ddf754f-d193-4cc9-b351-99906754a03b
Window size: width 1706 - height 1190
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-03T21:42:04.547Z',mode:absolute,to:'2017-11-03T21:48:04.547Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-03T21:42:04.547Z',mode:absolute,to:'2017-11-03T21:48:04.547Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I'm afraid there is no such download options. You best option is to download the whole dataset and filter them locally.

Depending on your needs you can also use the search API (if you are comfortable writing some code)
```
http://api.gbif-dev.org/v1/species/search?rank=SPECIES&dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&highertaxon_key=5&limit=100&offset=100
//returns 100 items with kingdom==fungi and rank==species and dataset==backbone starting at page 2.
```
This is the same data as seen by browsing this filtered search
https://www.gbif.org/species/search?rank=SPECIES&dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&highertaxon_key=5&advanced=1

For citation you should just use the backbone DOI in either case.

Hope that helps
Seems like an idea for future development as well.

> user answered per email
