### ISSUE TITLE
Do we have duplicates of PaleoDB?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#636]
**Do we have duplicates of PaleoDB?**

This dataset seems like it may be a duplicate of an [older DiGIR-based version](https://www.gbif.org/dataset/84806e86-f762-11e1-a439-00145eb45e9a).

Lots of citations on that earlier one, if it is indeed a dupe.

-----
fbitem-datasetbb5b30b4-827e-4d5e-a86a-825d65cb6583
User provided contact info: kcopas
System: Safari 11.0.1 / Mac OS X 10.12.6
Referer: https://www.gbif.org/dataset/bb5b30b4-827e-4d5e-a86a-825d65cb6583
Window size: width 1314 - height 793
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-06T06:49:03.873Z',mode:absolute,to:'2017-11-06T06:55:03.873Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-06T06:49:03.873Z',mode:absolute,to:'2017-11-06T06:55:03.873Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by tucotuco** [comment]
The new one is a replacement of the defunct DiGIR data set. There will be another Taxon resource coming out of this as well. VertNet is collaborating with PaleoDB to publish these data. It is not clear if the records in this new data set can be linked to the records in the old one.  We are happy to try to work through this with PBDB and GBIF. How do you recommend to move forward?

**Comment by tucotuco** [comment]
From Julian Jenkins and Mark Uhen at PBDB:

[Julian]"In addition to (https://www.gbif.org/dataset/84806e86-f762-11e1-a439-00145eb45e9a) there is also a dataset page of some sort at (https://www.gbif.org/dataset/c33ce2f2-c3cc-43a5-a380-fe4526d63650).

Neither were created by our group directly and should not be considered authoritative resources for PBDB. The records provided in the newly created dataset are comprehensive of the entire Paleobiology Database (at least as of two months ago when the files were exported) so no linking to these other datasets is necessary or, in fact, desirable. It’s our recommendation that both pages listed above (and the underlying datasets) be removed from GBIF to eliminate user confusion and provide the best (and most appropriate) contact information for the actual data source."

[Mark]"I agree with everything that Julian said, except I think that we DID upload https://www.gbif.org/dataset/84806e86-f762-11e1-a439-00145eb45e9a back in the day, when PBDB was housed at NCEAS. Everything about this dataset (data & metadata) is out of date. I think we made the affirmative decision a while back to simply start over and to get rid of this data set.

The other one is a bit confusing too, but I see no particular reason to keep it around either."

**Comment by mdoering** [comment]
Great works! The [PBDB checklist](https://www.gbif.org/dataset/c33ce2f2-c3cc-43a5-a380-fe4526d63650) is rather important to build the GBIF backbone. If there is an official replacement for it coming up and maintained with regular updates that would be very much appreciated and we should take down the old resource - or consider to use its identifier for the new dataset.

The resource was created by myself after some unsuccessful attempts to get the old palaeodb site to publish the data themselves. It is based on [code](https://github.com/mdoering/checklist_builder/blob/master/src/main/java/de/doering/dwca/pbdb/ArchiveBuilder.java#L41) that transforms pbdb downloads into a dwca.

**Comment by tucotuco** [comment]
New Taxon resource is indeed on the way, now that the Occurrence data are published.

**Comment by ManonGros** [comment]
I deleted the old DiGIR dataset and linked it to the new one.
https://www.gbif.org/dataset/84806e86-f762-11e1-a439-00145eb45e9a
