### ISSUE TITLE
Add '@' to GitHub handle in auto-completed feedback?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#637]
**Add &#39;@&#39; to GitHub handle in auto-completed feedback?**

I've got my GitHub account connected to my GBIF one, so when I'm logged in, my handle is already autofilled in the contact field of the feedback dialog.

However, without the @ sign in front of it, it's just plain text. Is there a way to automatically add the @ if we're already pulling the handle?

@ added manually below…

-----
fbitem-b7d0e782243d18e134a319c5602c145e6f6ae4f2
User provided contact info: @kcopas
System: Safari 11.0.1 / Mac OS X 10.12.6
Referer: https://www.gbif.org/user/profile
Window size: width 1314 - height 793
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-06T06:52:02.092Z',mode:absolute,to:'2017-11-06T06:58:02.092Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-06T06:52:02.092Z',mode:absolute,to:'2017-11-06T06:58:02.092Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Yes we can do that. We actually used to have it, but everytime an issue was copied to another folder the user would be informed - so at times it seemed a bit much. At least I found it to be and Tim commented on it as well. But I see what you mean. I can add it again.

**Comment by kcopas** [comment]
Far be it for me to overrule what you've already considered and observed. Happy either way.

**Comment by MortenHofft** [comment]
I've readded it. Not sure what i prefer, but since we don't auto move issues to other repos it is less of a nuissance for users to add it now. Thanks
