### ISSUE TITLE
"Depth" versus "MinimumDistanceAboveSurface"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#638]
**&quot;Depth&quot; versus &quot;MinimumDistanceAboveSurface&quot;**

Dear helpdesk,

At our museum we are facing problems in recording borehole distances  related to paleontological specimen in our database. In particular, which field we should use to  enter the vertical distance into the surface when drilling on land. 

When drilling into the sea floor the DwC definition is quite clear; this distance should be entered in the fields minimumDistanceAboveSurfaceInMeters and maximumDistanceAboveSurfaceInMeters , with the water depth in the fields minimumDepthInMeters and maximumDepthInMeters. 

However, when drilling on land, both ‘depth’ and ‘DistanceAboveSurface’ seem suitable according to the DwC definitions. What does GBIF recommend in this situation? For collection management purposes it is preferred to enter borehole distances in a single field, whether on land or in the sea floor. We hope you can help us with this question

cheers,

Judith Slaa & Jeroen Creuwels, 

Dept. Information management
Naturalis Biodiversity Center - The Netherlands

-----
fbitem-dataset494ceb90-924c-483d-ae58-9dd89efb85a1
User provided contact info: jeroen.creuwels@naturalis.nl
System: Chrome 61.0.3163 / Windows 7 0.0.0
Referer: https://www.gbif.org/dataset/494ceb90-924c-483d-ae58-9dd89efb85a1
Window size: width 2133 - height 1044
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-06T13:58:42.567Z',mode:absolute,to:'2017-11-06T14:04:42.567Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-06T13:58:42.567Z',mode:absolute,to:'2017-11-06T14:04:42.567Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by tucotuco** [comment]
I do not speak for GBIF, but as convenor of the Darwin Core maintenance
group and erstwhile interpreter of its use, my inclination is to do exactly
as you have suggested, put your bore hole depths in the
distanceAboveSurvaceInMeters fields with negative numbers. If you would
like to have a broader community discussion about this, I recommend
submitting this same question to the Darwin Core Questions & Answers site,
either directly in GitHub at https://github.com/tdwg/dwc-qa/issues, or via
the Darwin Core Hour input form at https://docs.google.com/forms/d/e/
1FAIpQLSekd0QSdgiK5ujh6CLZPx9kKTcS-mJRNK_pGWk3b3fHv4x4gQ/viewform?c=0&w=1.
We use these kinds of questions as the basis to produce better
documentation (see, for example,
https://github.com/tdwg/dwc-qa/wiki/Georeferences).

**Comment by MortenHofft** [comment]
@kbraak this sounds like your area of expertise - if nothing else you know more than I.

**Comment by kbraak** [comment]
Thanks @MortenHofft, I have nothing else to add here. The reporter has been informed. Closing issue.

**Comment by jeroencreuwels** [comment]
Thanks all for the input! Jeroen
