### ISSUE TITLE
Rutilus kutum, a fish species of Caspian Sea / Iran.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#639]
**Rutilus kutum, a fish species of Caspian Sea / Iran.**

https://www.gbif.org/occurrence/1012546381

The georeference should likely be 37.53N, 49.24E, which would be on the Caspian coast of Iran.

Instead the gpereference shows a negative longitude of -49.24, which wrongly places this fish species in the middle of the Atlantic Ocean.

Also there is a second georeference point in the southern Atlantic ocean... which would also be incorrect.

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
User provided contact info: landed2shore@gmail.com
System: Safari 11.0.1 / Mac OS X 10.12.6
Referer: https://www.gbif.org/
Window size: width 1170 - height 629
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-07T02:07:35.063Z',mode:absolute,to:'2017-11-07T02:13:35.063Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-07T02:07:35.063Z',mode:absolute,to:'2017-11-07T02:13:35.063Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
Publisher notified; closing
