### ISSUE TITLE
Is eBird data source identifier up to date?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#64]
**Is eBird data source identifier up to date?**

I may be mistaken, but I thought that CLO was now hosting the eBird Obs Dataset. If so, I think the metadata may need a small update, given that the alt.identifier URL, which is still pointing to a VertNET IPT.

-----
fbitem-dataset4fa7b334-ce0d-4e88-aaae-2e0c138d049e
Reported by: @kcopas
System: Safari 10.0.3 / Mac OS X 10.11.6
Referer: https://demo.gbif.org/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e/origin
Window size: width 1285 - height 733
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-07T09:59:42.315Z',mode:absolute,to:'2017-02-07T10:05:42.315Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-07T09:59:42.315Z',mode:absolute,to:'2017-02-07T10:05:42.315Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
@MortenHofft, not sure here, but I thought the "alternative identifiers" section of a dataset page like https://demo.gbif.org/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e/origin was listing additional URLs, not the one we are harvesting from (which would be under "source data")? I am unsure whether this really is a data issue, or concerning the reading.

**Comment by timrobertson100** [comment]
It lists the alternative identifiers the publisher puts in their EML.
As it happens that URL is not the URL we harvest from (see the target of the Darwin Core Archive link has http://ipt.ornith.cornell.edu/dwca-1.0.zip since they go directly now, and not through the IPT).

We should ask the contact to update the EML, and once done we should manually update the EML doc in the registry carefully so as not to trigger a reindexing of eBird.

**Comment by MattBlissett** [comment]
The current EML doesn't contain any alternative identifiers, but is otherwise up-to-date.

I simply deleted the VertNet one.
