### ISSUE TITLE
exporting map

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#647]
**exporting map**

is there a way to export a map from inaturalist to arcgis?

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c
User provided contact info: kimberlee.howell@go.tarleton.edu
System: Chrome 62.0.3202 / Windows 10 0.0.0
Referer: https://www.gbif.org/dataset/search
Window size: width 1920 - height 959
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-08T00:01:43.883Z',mode:absolute,to:'2017-11-08T00:07:43.883Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-08T00:01:43.883Z',mode:absolute,to:'2017-11-08T00:07:43.883Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi Kimberlee. 
iNaturalist simply share data through the GBIF network. They have their own site and might support such an option - for that you should see their website at http://www.inaturalist.org/

All the data in GBIF can be downloaded and transformed (by you) into whatever formats ArcGIS supports.
If you are only interested in the maps (and not the details about the individual observations/points on the map), then we have a dedicated mapping API. You can read more about the maps in [our developer documentation](https://www.gbif.org/developer/maps). I have never worked with ArcGIS, but looking at [their documentation](http://doc.arcgis.com/en/arcgis-online/reference/tile-layers.htm) it seems that they support tile maps (also as vector tiles). We too expose both.

Hope that helps

> send to user per email
