### ISSUE TITLE
Agriphila tristella

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#649]
**Agriphila tristella**

This is a very common European species.  It is normally known as Agriphila tristella (apparently ignoring the usual practice in lepidopterology of keeping the original epithet spelling).  Every single occurrence in GBIF uses A. tristella so every record has the the Fuzzy Match issue.  We should at least insert A. tristella as a synonym and quite possibly reverse the accepted/synonym direction to make A. tristella the accepted name.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: dhobern@gbif.org
System: Chrome 61.0.3163 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/search?taxon_key=1878862&advanced=1
Window size: width 1897 - height 922
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-08T08:25:38.064Z',mode:absolute,to:'2017-11-08T08:31:38.064Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-08T08:25:38.064Z',mode:absolute,to:'2017-11-08T08:31:38.064Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
We could include it as a synonym or accepted name in the patchlist.
Is there a reference to point to that justifies this?

**Comment by dhobern** [comment]
Actually, according to Fauna Europaea, the LepIndex choice is flat-out wrong.  It seems it was originally described as Tinea tristella so there is NO justification for A. tristellus, which does not seem to exist anywhere outside LepIndex/CoL:

https://fauna-eu.org/cdm_dataportal/taxon/e1384cba-5362-472a-8072-5854b8392a6e

**Comment by dhobern** [comment]
A general approach to this could be good.  There seems to be little reason for there to be so many fuzzy or higher taxon matches here:

https://www.gbif.org/occurrence/search?dataset_key=f506be53-9221-4b44-a41d-5aa0905ec216&issue=TAXON_MATCH_FUZZY&issue=TAXON_MATCH_HIGHERRANK&advanced=1

I suspect that import of all Lepidoptera from FaunaEuropaea might fix all of these.

**Comment by mdoering** [comment]
Unfortunately we cannot rank parts of sources differently yet. we would need sth like col+ sectors, otherwise all of FaEu would come before CoL and cause a mess.

We could export FaEu Lepidoptera into its own dataset, the proto Lep GSD. Actually straight forward to do, should we try? Or any other source for lepidoptera or its subgroups?

**Comment by dhobern** [comment]
It's probably not worth getting distracted by this now.  There is no generally viable alternative.  Importing major segments from FaEu and other regional datasets would be a workable approach, but no need to adopt other models right now.

**Comment by mdoering** [comment]
I will extract the FaEu Lepidoptera into a dataset on its own. If you wanna have a quick review it is here: https://www.gbif.org/species/123393197

**Comment by dhobern** [comment]
It looks pretty good to me although naming a placeholder superfamily Lepidopteraincertissedoidea is pretty mental:

https://fauna-eu.org/cdm_dataportal/taxon/c20ed8e7-3d28-4f0d-a015-6c0dd2bd0c41

Of course, being a superfamily, it shouldn't affect us too much ...

**Comment by mdoering** [comment]
I do not have access to that version migrated to the BGBM CDM.
Our copy is based on a file that Yde gave us for publishing. I have modified the dwca export from it this morning so all the "basionym" authors are not all wrong (see gbif/checklistbank#43)

Here it is, still not indexed with the good authors so consider these fixed:
https://www.gbif.org/species/search?dataset_key=90d9e8a6-0ce1-472d-b682-3451095dbc5a&advanced=1

But it seems we also have this nice superfamily (which will simply be ignored and not make it into our backbone): https://www.gbif.org/species/123394630

**Comment by mdoering** [comment]
Is treated as [Agriphila tristella (Denis & Schiffermuller, 1775)](https://www.gbif-uat.org/species/4531511) in the 2018 nub
