### ISSUE TITLE
-1 coordinate precision should not be interpreted as 1

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#65]
**-1 coordinate precision should not be interpreted as 1**

Should we not simply discard, rather than alter that?
Looking at the record diagnostic view, it seems &quot;-1&quot; is used for NULL

-----
fbitem-occurrence1135583752
Reported by: @timrobertson100
System: Chrome 55.0.2883 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/occurrence/1135583752
Window size: width 1721 - height 1099
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-07T18:30:42.473Z',mode:absolute,to:'2017-02-07T18:36:42.473Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-07T18:30:42.473Z',mode:absolute,to:'2017-02-07T18:36:42.473Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: 38b4c89f-584c-41bb-bd8f-cd1def33e92f
publishingOrgKey: b8323864-602a-4a7d-9127-bb903054e97d

**Comment by cgendreau** [comment]
Moved to https://github.com/gbif/occurrence/issues/9
