### ISSUE TITLE
Ad-hoc SOLR map style doesn't take into account underlying data resolution

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#653]
**Problema al mostrar detalles del registro en un bounding box**

A la atención de Federico.
Al realizar un boundix box en el cuadrado que se encuentra más a la izquierda y abajo (en el mar), según el nivel de zoom te va a dar los registros o no.
Muchas gracias.
Saludos

-----
fbitem-632937989213bf4e43cb42556216fa1047383e29
User provided contact info: herbariomgc@uma.es
System: Chrome 61.0.3163 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/map?basis_of_record=PRESERVED_SPECIMEN&has_coordinate=true&has_geospatial_issue=false&institution_code=mgc&taxon_key=2792579
Window size: width 1600 - height 769
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-08T14:28:47.871Z',mode:absolute,to:'2017-11-08T14:34:47.871Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-08T14:28:47.871Z',mode:absolute,to:'2017-11-08T14:34:47.871Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
translation

**Problem when displaying log details in a bounding box**

To Federico's attention.
When making a boundix box in the square that is more to the left and below (in the sea), depending on the level of zoom you will give the records or not.
Thank you very much.
regards

**Comment by MortenHofft** [comment]
@fmendezh sounds like this one is for you señor

**Comment by MortenHofft** [comment]
It is hard to tell from the issue when you weren't there, but I think it is a variant of this issue that has to do with the SOLR maps resolution.

![screen shot 2017-11-24 at 08 37 33](https://user-images.githubusercontent.com/6759267/33199945-cec8138a-d0f2-11e7-83c2-b6d2913fbd7c.png)
![screen shot 2017-11-24 at 08 37 54](https://user-images.githubusercontent.com/6759267/33199946-cee1cfa0-d0f2-11e7-8b8d-a6f2aebf76f5.png)

What is needed is a better ad hoc map styling from Solr. it should adjust style based on zoom level to match the resolution returned.
