### ISSUE TITLE
botany: autonym=synonym ?

### ISSUE THREAD

**Issue by andzandz11** [gbif/portal-feedback#654]
Sorry, I am not hardcore taxonomist enough for that question.

Should there be a consistent way to handle autonyms?
Which one is correct?

https://www.gbif.org/species/116781630/verbatim
https://www.gbif.org/species/7222005

*idea*
It would be relatively easy to create a new linker name "autonym of ..." no? And replace all other links like "synonym of .." by checking if the two names are identical.
Or should "synonym of .." be automatically added to all autonyms?

**Comment by mdoering** [comment]
An autonym is just an infraspecific name that implicitly, automatically gets created when the first infraspecific name for a species is describend and needs no explicit publication. And therefore has no authorship on its own. Its unrelated to synonymy

**Comment by andzandz11** [comment]
Yes, thank you. But my point was why in the records one time it is listed as synonym to its basionym(?) and one time it is not?
