### ISSUE TITLE
Dowload issues for fish data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#655]
**Dowload issues for fish data**

Hello, I am trying to download a number of fish data sets, such as the University of Alberta Museum of Zoology Ichthyology Collection. What I can do is download the file save it and open it. But when I open the file in excel it is a complete mess and the spreadsheet just has a bunch of numbers and names (presumably curators). I had the same problem with the Canadian Museum of Nature data set, so I had to go to the dataset homepage and download from there. Is any of the data on this website useable? How do I download? I need data on fish in BC, Canada.

-----
fbitem-dataset84f3b06c-f762-11e1-a439-00145eb45e9a
User provided contact info: mrogers
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/dataset/84f3b06c-f762-11e1-a439-00145eb45e9a
Window size: width 1150 - height 583
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-10T00:17:48.881Z',mode:absolute,to:'2017-11-10T00:23:48.881Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-10T00:17:48.881Z',mode:absolute,to:'2017-11-10T00:23:48.881Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi @mrogers
It depends on what format you download in. But assuming that you have done this:

* Started at: https://www.gbif.org/dataset/84f3b06c-f762-11e1-a439-00145eb45e9a
* Chose download -> GBIF annotated archive
* Chose download option .CSV
* Waited for the download to be prepared and downloaded it. 

You should now have a compressed zip file on your computer.
* That needs to be [unzipped](https://www.gbif.org/faq?question=why-cant-i-open-the-zip-file-i-downloaded-from-gbif-org) using standard software most computers have.
* Inside that zip is a csv file that can be read by fx excel. [Here](https://www.gbif.org/faq?question=what-is-inside-a-gbif-download-zip-file) is a description of how to open a csv in excel. I also found [this video ](https://www.youtube.com/watch?v=z5Pxil4jVO4) of someone demonstrating it. Notice that GBIF csv files are tab delimited ([see video at 1:34](https://youtu.be/z5Pxil4jVO4?t=1m34s))

Hope that helps

**Comment by MattBlissett** [comment]
For every user that reports an issue like this, there are potentially several that don't bother (so thanks, mrogers!).

Should we add something to the download email? The current email ends with a link to the FAQ, https://www.gbif.org/faq#dataUse, but that doesn't link to a specific question, i.e. needs updating.

**Comment by MortenHofft** [comment]
@dnoesgaard I'm sure you are already aware of this, but here is another example of a user that missed an explanation. 
As for additional download formats I have added it to the list [here](https://github.com/gbif/portal16/issues/589)
