### ISSUE TITLE
Many Palaeo genera wrongly classified

### ISSUE THREAD

**Issue by mdoering** [gbif/portal-feedback#657]
Various genera are classified into a wrong order according to [Taxon list of Jurassic Pisces of the Tethys Palaeo-Environment compiled at the SNSB-JME](https://www.gbif.org/dataset/f5c60e9e-5b76-43b7-aa14-bbc3fa23b7d5):

- Macrosemius, Notagogus, Propterus, Ophiopsiella & Thrissops do not belong to order Amiiformes
- Pachythrissops & Tharsis do not belong to family Leptolepidae
- Leptolepides does not belong to oder Salmiformes.

Instead:
- Macrosemius, Notagogus, Propterus belong to order Semionotiformes;
- Thrissops and Pachythrissops to order Ichthyodectiformes; 
- Leptolepides to family Orthogonikleithridae. 

-----

This is caused because we only accept families and below from other lists than the CoL.
The Jurassic list above is missing a family for Thrissops for example, so it gets attached to the class only. IRMNG then updates the genus classification, adding missing order and family which is apparently wrong: https://www.gbif.org/species/107755019

Thrissops in GBIF Backbone:
https://www.gbif.org/species/4838350

Thrissops in Taxon list of Jurassic Pisces of the Tethys Palaeo-Environment compiled at the SNSB-JME
https://www.gbif.org/species/114607723

**Comment by ManonGros** [comment]
Looks like this is solved.
