### ISSUE TITLE
Occurrence records not crawled?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#658]
**Occurrence records not crawled?**

The [IPT](https://ipt.sibbr.gov.br/peld/resource?r=diversidade_de_macroinvertebrados_bentonicos_peld) shows this sample based dataset has 4019 occurrence records but none show up on GBIF although the crawl says it was successful.

-----
fbitem-dataset32ba1b9a-b06d-417e-98ea-eb0cfb67466a
User provided contact info: GB
System: Chrome 61.0.3163 / Mac OS X 10.11.5
Referer: https://www.gbif.org/dataset/32ba1b9a-b06d-417e-98ea-eb0cfb67466a
Window size: width 1387 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-11T12:34:39.768Z',mode:absolute,to:'2017-11-11T12:40:39.768Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-11T12:34:39.768Z',mode:absolute,to:'2017-11-11T12:40:39.768Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
validation report https://www.gbif.org/tools/data-validator/1509439657243
