### ISSUE TITLE
The CSV doesn't download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#659]
**The CSV doesn&#39;t download**

Trying to download the England Non Native Specie records 1965 to 2017

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
User provided contact info: vdominguezalmela@bournemouth.ac.uk
System: IE 11.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/download?dataset_key=d03f444a-7192-4fa0-bf7a-63714585c611
Window size: width 1280 - height 900
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-13T10:35:07.593Z',mode:absolute,to:'2017-11-13T10:41:07.593Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-13T10:35:07.593Z',mode:absolute,to:'2017-11-13T10:41:07.593Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
We just restarted the downloading service. I'll mail the user.
