### ISSUE TITLE
stalachits hubner

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#660]
**stalachits hubner**

-----
fbitem-f55b22d402f0bf9841531850ab0f3ed8d9273208

System: Chrome 61.0.3163 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/species
Window size: width 1280 - height 590
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-14T02:46:28.166Z',mode:absolute,to:'2017-11-14T02:52:28.166Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-14T02:46:28.166Z',mode:absolute,to:'2017-11-14T02:52:28.166Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Would be guesswork trying to figure out what the user intended.
