### ISSUE TITLE
Record with non scientific name 9192154 = Flowering plant

### ISSUE THREAD

**Issue by jtklein** [gbif/portal-feedback#661]
{"key":9192154,"nameKey":12889138,"taxonID":"gbif:9192154","sourceTaxonKey":126747317,"kingdom":"Plantae","phylum":"Tracheophyta","order":"Piperales","family":"Piperaceae","species":"Flowering plant","kingdomKey":6,"phylumKey":7707728,"classKey":220,"orderKey":404,"familyKey":6678,"speciesKey":9192154,"datasetKey":"d7dddbf4-2cf0-4f39-9b2a-bb099caae36c","constituentKey":"6cfd67d6-4f9b-400b-8549-1933ac27936f","parentKey":6678,"parent":"Piperaceae","scientificName":"Flowering plant","canonicalName":"Flowering plant","authorship":"","nameType":"SCIENTIFIC","rank":"SPECIES","origin":"SOURCE","taxonomicStatus":"ACCEPTED","nomenclaturalStatus":[],"remarks":"","numDescendants":0,"lastCrawled":"2017-02-14T13:42:21.926+0000","lastInterpreted":"2017-02-14T13:33:49.895+0000","issues":[],"synonym":false,"class":"Magnoliopsida"}

**Comment by MortenHofft** [comment]
this indeed looks wrong https://www.gbif.org/species/9192154

**Comment by ManonGros** [comment]
*Flowering plant* is still considered a species in the latest taxonomy update.

**Comment by ManonGros** [comment]
However, I cannot find any type with the name *Flowering plant*, which is unexpected since this name is in the backbone because it is in the [GBIF Type Specimen Names](https://www.gbif.org/dataset/6cfd67d6-4f9b-400b-8549-1933ac27936f) dataset. Could we update this dataset? https://github.com/gbif/portal-feedback/issues/288

**Comment by mdoering** [comment]
we have removed the GBIF Types specimen dataset from the backbone sources
