### ISSUE TITLE
Wrong synonomy for Clarkia lewisii in GBIF

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#663]
**Wrong synonomy for Clarkia lewisii in GBIF**

This species, Clarkia lewisii is showing incorrect synonyms. The Camissonia and Camissoniopsis are NOT synonyms with Clarkia. This severely affects the range in this case, as Clarkia lewisii is a very restricted endemic, known only to 2 counties in California.

Here's the page where I see this:https://www.gbif.org/species/5420977

-----
fbitem-species5420977
User provided contact info: roxanne.bittman@wildlife.ca.gov
System: Firefox 56.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/species/5420977
Window size: width 1594 - height 931
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-14T21:34:04.611Z',mode:absolute,to:'2017-11-14T21:40:04.611Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-14T21:34:04.611Z',mode:absolute,to:'2017-11-14T21:40:04.611Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
fixed. Camissoniopsis lewisii is also accepted now with synonym 
Camissonia lewisii Raven
