### ISSUE TITLE
Import script doesn't take into account unicode characters for MS-SQL

### ISSUE THREAD

**Issue by drgrieve** [gbif/portal-feedback#664]
For the sample archive archive-genus-ophryops-bl3.zip I needed to add the option DATAFILETYPE = ''widechar'' and convert the source file (taxa.txt) to UCS-2 BE ROM (using Notepadd++).

The data imported then included proper conversion of unicode data.

**Comment by MortenHofft** [comment]
Hi @drgrieve 
Thank you for reporting. Could you please provide some more context. Which sample archive on which page are we talking about?
