### ISSUE TITLE
Dataset: broken source archive (occurrence.csv cannot be opened)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#665]
**Dataset: broken source archive (occurrence.csv cannot be opened)**

This dataset could not yet be indexed because the source archive cannot be opened. If this is an artifact of the NBN update work we know is going on, please ignore:
Just noticed that the DwC-A for this new dataset appears broken (reported by DN, GBIFS)

-----
fbitem-datasetf14f3ec9-c54a-477d-82c8-f7ba6925534a
User provided contact info: ahahn-gbif
System: Firefox 57.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/dataset/f14f3ec9-c54a-477d-82c8-f7ba6925534a
Window size: width 925 - height 629
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-15T10:22:37.640Z',mode:absolute,to:'2017-11-15T10:28:37.640Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-15T10:22:37.640Z',mode:absolute,to:'2017-11-15T10:28:37.640Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
Being investigated with NBN folk through me

**Comment by timrobertson100** [comment]
Should be fixed (archive checked manually) and is now in the crawl queue.

**Comment by timrobertson100** [comment]
Confirming fixed https://www.gbif.org/dataset/f14f3ec9-c54a-477d-82c8-f7ba6925534a
