### ISSUE TITLE
Licence mismatch on new NBN-mobilized dataset

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#666]
**Licence mismatch on new NBN-mobilized dataset**

The licence for this new UK dataset is showing as 'Unsupported' on GBIF.org, but the [NBN endpoint](https://registry.nbnatlas.org/public/show/dr1553) shows it as CC BY.

-----
fbitem-dataset11a24c97-653b-4e4c-a524-a4c06ffab25f
User provided contact info: @kcopas
System: Safari 11.0.1 / Mac OS X 10.13.1
Referer: https://www.gbif.org/dataset/11a24c97-653b-4e4c-a524-a4c06ffab25f
Window size: width 1309 - height 793
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-17T09:44:50.036Z',mode:absolute,to:'2017-11-17T09:50:50.036Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-17T09:44:50.036Z',mode:absolute,to:'2017-11-17T09:50:50.036Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
Fixed.
