### ISSUE TITLE
Endemic species in Taiwan not indexed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#667]
**Endemic species in Taiwan not indexed**

The checklist is very fine, but it has a single record at the end with no data at all but rank=species. This causes the validator to say its missing core identifier and thus it never gets indexed. Please contact publisher to fix this!

-----
fbitem-datasete1c9e885-9d8c-45b5-9f7d-b710ac2b303b
User provided contact info: mdoering
System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/dataset/e1c9e885-9d8c-45b5-9f7d-b710ac2b303b
Window size: width 1680 - height 889
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-17T10:36:29.534Z',mode:absolute,to:'2017-11-17T10:42:29.534Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-17T10:36:29.534Z',mode:absolute,to:'2017-11-17T10:42:29.534Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by ahahn-gbif** [comment]
At this point, the dataset is indexed with 8852 records, though the DwC-A appears to be no longer supplied at source (different issue). @mdoering could you confirm that this is no longer an issue? I may be misreading the description.

**Comment by mdoering** [comment]
yes, appears to be fine: https://tools.gbif.org/dwca-reports/054-4304073819778815691.html
