### ISSUE TITLE
Network counts have gone haywire

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#668]
**Network counts have gone haywire**

Something's gotten out of whack on our network map—perhaps it's connected to the addition of Luxembourg as a voting Participant? 

Europe is now showing

+ 62 Voting Participants
+ 47 Other Associate Participants
+ 1.2 billion occurrences

-----
fbitem-2f490e24d093373543a643a154f2bbaa4c6ec09b
User provided contact info: @kcopas
System: Safari 11.0.1 / Mac OS X 10.13.1
Referer: https://www.gbif.org/the-gbif-network/europe
Window size: width 1309 - height 793
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-17T13:05:21.215Z',mode:absolute,to:'2017-11-17T13:11:21.215Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-17T13:05:21.215Z',mode:absolute,to:'2017-11-17T13:11:21.215Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Maybe it was adding EU on top of totals momentarily? Totals have reset and look correct.

![for reference, though...](https://user-images.githubusercontent.com/12379236/32948916-3659d800-cba1-11e7-8834-c75a191eb02f.png)

**Comment by MattBlissett** [comment]
On a first page load of https://www.gbif.org/the-gbif-network/europe it shows 40 participants, clicking "Europe" (or e.g. "Africa", "Europe") then shows 20.

**Comment by MortenHofft** [comment]
Similarly it shows 790 mil occurrence on Europe until you switch tab and back.
