### ISSUE TITLE
small cosmetic issue - network page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#670]
**small cosmetic issue - network page**

Look like some spaces are missing between counts and "voting participants", "associate participants, "other..."

-----
fbitem-5f8f9aca65a6fc0d0677bfe440ec39d391db6ce0
User provided contact info: @dnoesgaard
System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/the-gbif-network
Window size: width 1818 - height 948
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-20T10:17:43.469Z',mode:absolute,to:'2017-11-20T10:23:43.469Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-20T10:17:43.469Z',mode:absolute,to:'2017-11-20T10:23:43.469Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
![gbif](https://user-images.githubusercontent.com/21358085/33013677-2b2c369e-cde5-11e7-8a5e-a5622a0613c4.png)
