### ISSUE TITLE
dev DOI in backbone citation

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#671]
**dev DOI in backbone citation**

cc @mdoering

doi.org/10.5072/hufs9m currently shows up as the backbone taxonomy DOI on species pages...

-----
fbitem-species2439261
User provided contact info: @dnoesgaard
System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/species/2439261
Window size: width 1818 - height 948
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-20T14:43:09.886Z',mode:absolute,to:'2017-11-20T14:49:09.886Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-20T14:43:09.886Z',mode:absolute,to:'2017-11-20T14:49:09.886Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
heads up @mdoering - this issue remains, e.g.

https://www.gbif.org/species/319

> Myxomycetes in GBIF Secretariat (2017). GBIF Backbone Taxonomy. Checklist Dataset https://doi.org/10.5072/hufs9m accessed via GBIF.org on 2017-11-28.

**Comment by mdoering** [comment]
Looks like this should be https://doi.org/10.15468/39omei instead

**Comment by mdoering** [comment]
changed it to 10.15468/39omei manually
