### ISSUE TITLE
DwC Validator - Error or Bug?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#677]
**DwC Validator - Error or Bug?**

I have a DwC-A file that gets the following error report. I understand all errors but one: Why is the references.txt file not read. I can send the file if you give me an email.

-----
fbitem-21a11d652dd522d32d0f9f6dbaeecc77fd4ad2ea
User provided contact info: w.berendsohn@bgbm.org
System: Firefox 57.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/tools/data-validator/1511367174884
Window size: width 2144 - height 1092
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-23T11:44:44.524Z',mode:absolute,to:'2017-11-23T11:50:44.524Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-23T11:44:44.524Z',mode:absolute,to:'2017-11-23T11:50:44.524Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
```[ERROR] [11/23/2017 12:39:09.128] [JobServerSystem-akka.actor.default-dispatcher-18] [akka://JobServerSystem/user/JobMonitor/1511367174884/dataFileRouter_cd868187-74c8-41c7-a60d-9f8ebec18092/$a] Error while evaluating line 0 of /mnt/auto/validator/648f026e-a133-4b38-986e-a897e2741846/references.txt: class java.lang.RuntimeException : Unexpected character (',' (code 44)): Expected separator ('"' (code 34)) or end-of-line
 at [Source: java.io.BufferedReader@8cf5556; line: 1, column: 18]
```

I've emailed Walter to ask if this makes the error clear. We should improve the feedback to the user here.
