### ISSUE TITLE
New publisher has not identified country

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#678]
**New publisher has not identified country**

This newly registered publisher has not identified the UK as its country.

Thanks for the chips, Morten—could see something was wrong at a glance!

-----
fbitem-publisher4d905053-ca42-4fac-bcc4-36f1d08f3127
User provided contact info: @kcopas
System: Safari 11.0.1 / Mac OS X 10.13.1
Referer: https://www.gbif.org/publisher/4d905053-ca42-4fac-bcc4-36f1d08f3127
Window size: width 1149 - height 793
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-23T18:48:14.353Z',mode:absolute,to:'2017-11-23T18:54:14.353Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-23T18:48:14.353Z',mode:absolute,to:'2017-11-23T18:54:14.353Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I've added the country and the latitude and longitude. 
@jlegind  The publisher was registered with lat & long = -1 and no country. Modified by "uknbn" - if this is some of the scripted stuff it might be worth getting them to fix it there?

**Comment by MattBlissett** [comment]
Those are @timrobertson100 / Dave Martin's scripts.
