### ISSUE TITLE
Bad naming of "crawling states".

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#679]
**Bad naming**

The naming on crawling states isn't very good. But they are very long. Could you @dnoesgaard  help me with some better naming for those.

![screen shot 2017-11-24 at 15 09 25](https://user-images.githubusercontent.com/6759267/33213870-c157ca88-d129-11e7-8fb6-71a080936393.png)

I'm especially eager to fix it as we now show it at the top of the page in case of the user being a dataset contact

-----
fbitem-datasetaeeff4d1-a1e0-454e-ae87-2748138279d3
User provided contact info: mortenhofft
System: Chrome 62.0.3202 / Mac OS X 10.11.6
Referer: https://www.gbif.org/dataset/aeeff4d1-a1e0-454e-ae87-2748138279d3
Window size: width 1918 - height 1076
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-24T14:06:00.287Z',mode:absolute,to:'2017-11-24T14:12:00.287Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-24T14:06:00.287Z',mode:absolute,to:'2017-11-24T14:12:00.287Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
@MortenHofft, is there anyway I can see how this is shown to a dataset contact?

**Comment by MortenHofft** [comment]
if you are a registry admin or have a dataset only. but the info in the image above is also at the bottom for everyone to see

**Comment by MattBlissett** [comment]
I have made you a registry admin on gbif-dev, so try something like https://www.gbif-dev.org/dataset/75956ee6-1a2b-4fa3-b3e8-ccda64ce6c2d

NB I earlier changed "crawl" to "ingest", which has a clearer meaning to non-GBIF people. "Crawl" also has a specific, narrower meaning in our software.

**Comment by dnoesgaard** [comment]
me?

**Comment by MattBlissett** [comment]
Yes. You should be logged in with your user dnoesgaard

**Comment by dnoesgaard** [comment]
I don't see it?

**Comment by dnoesgaard** [comment]
I still don't see anything :( I'm not sure if I'm doing something wrong?

**Comment by MortenHofft** [comment]
Nope - just that dev API's haven't been working for a while, so if we are to test website development we have to change the dev site to use UAT endpoints. Or use UAT as our development environment. Neither is ideal - using UAT data on dev is the lesser of two evils in many cases.

So if you are eager - you'll just have to start publishing some data (or wait for dev to become dev again)

**Comment by MattBlissett** [comment]
@dnoesgaard, you can see this section at the bottom of any dataset page, whether logged in or not.

Other than perhaps a subheading ("GBIF data ingestion history" or similar), I don't think there's anything to change.

I'm going through some old issues, let's close this one?

**Comment by dnoesgaard** [comment]
Agreed
