### ISSUE TITLE
Failed crawls for Swedish taxonomic backbone

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#680]
**Failed crawls for Swedish taxonomic backbone**

Just noticed that crawling on this checklist has failed for most of this year. Mentioning it in the event it's otherwise gone undetected.

-----
fbitem-datasetde8934f4-a136-481c-a87a-b0b202b80a31
User provided contact info: @kcopas
System: Mobile Safari 9.0.0 / iOS 9.3.5
Referer: https://www.gbif.org/dataset/de8934f4-a136-481c-a87a-b0b202b80a31
Window size: width 768 - height 984
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-24T16:13:42.227Z',mode:absolute,to:'2017-11-24T16:19:42.227Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-24T16:13:42.227Z',mode:absolute,to:'2017-11-24T16:19:42.227Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by timrobertson100** [comment]
The GBIF.se folks are aware of this and trying to sort things out

**Comment by mdoering** [comment]
I believe the Dyntaxa checklist has never been published by Sweden, but lived on my personal Dropbox account. Would be good if they can do this themselves
