### ISSUE TITLE
In "Basis of Record", what does "Machine Observation" mean?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#681]
**In &quot;Basis of Record&quot;, what does &quot;Machine Observation&quot; mean?**

I've looked at DarwinCore standards to understand what machine observation is, but the definition is simply states as "an observation made by a machine." Not at all helpful. Can you provide an example? Would a wildlife camera taking a photo of an animal be considered a machine observation? I've seen this for plants, too - so what would be an example there? Thanks for your help.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: kpowers4@radford.edu
System: Chrome 62.0.3202 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/search?basis_of_record=OBSERVATION&basis_of_record=LITERATURE&basis_of_record=PRESERVED_SPECIMEN&basis_of_record=LIVING_SPECIMEN&basis_of_record=HUMAN_OBSERVATION&basis_of_record=MATERIAL_SAMPLE&country=US&taxon_key=2436905
Window size: width 1280 - height 893
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-27T14:48:05.583Z',mode:absolute,to:'2017-11-27T14:54:05.583Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-27T14:48:05.583Z',mode:absolute,to:'2017-11-27T14:54:05.583Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by tucotuco** [comment]
Yes, a camera trap photo is a machine observation. Anything where the
machine records the presence is a machine observation.

Someone out making observations with a camera along taking photos and
including those with records sometimes has a human observation as the
intent, so I would use HumanObservation for those.

**Comment by MortenHofft** [comment]
@dnoesgaard you mentioned a page about the various fields and how GBIF understand them. So this might be of interest
