### ISSUE TITLE
Port http://tools.gbif.org/nameparser/ to GBIF.org

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#682]
**Port http://tools.gbif.org/nameparser/ to GBIF.org**

This should be ported as a tool to GBIF.org

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
User provided contact info: @timrobertson100
System: Chrome 62.0.3202 / Mac OS X 10.11.5
Referer: https://www.gbif.org/
Window size: width 1777 - height 1099
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-28T13:53:33.370Z',mode:absolute,to:'2017-11-28T13:59:33.370Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-28T13:53:33.370Z',mode:absolute,to:'2017-11-28T13:59:33.370Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
yes! Uses http://api.gbif.org/v1/parser/name?name=Abies
