### ISSUE TITLE
how to clean dataset on excel after download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#684]
**how to clean dataset on excel after download**

After downloading dataset of a species, the csv excel sheet looks messy. how do you clean it?

-----
fbitem-27b0539729717a9752cf77e37af7ff34c5e8a4d0
User provided contact info: fauziah05@hotmail.com
System: Firefox 57.0.0 / Windows 8.1 0.0.0
Referer: https://www.gbif.org/occurrence/download/0002207-171124123535762
Window size: width 1192 - height 859
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-29T03:14:09.410Z',mode:absolute,to:'2017-11-29T03:20:09.410Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-29T03:14:09.410Z',mode:absolute,to:'2017-11-29T03:20:09.410Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
Hi
It depends on what you need. I guess this is more of a general question about excel use and data cleaning for your needs.

If this has to do with opening the csv file in excel then perhaps this can be helpful. After downloading the file.
* That needs to be [unzipped](https://www.gbif.org/faq?question=why-cant-i-open-the-zip-file-i-downloaded-from-gbif-org) using standard software most computers have.
* Inside that zip is a csv file that can be read by fx excel. [Here](https://www.gbif.org/faq?question=what-is-inside-a-gbif-download-zip-file) is a description of how to open a csv in excel. I also found [this video ](https://www.youtube.com/watch?v=z5Pxil4jVO4) of someone demonstrating it. Notice that GBIF csv files are tab delimited ([see video at 1:34](https://youtu.be/z5Pxil4jVO4?t=1m34s))

Hope that helps
Thanks

> sent per mail
