### ISSUE TITLE
Missing administrative information in participant page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#685]
**Missing administrative information in participant page**

As of the reporting of this issue, the administrative information like "Head of Delegation", "Node Name", "Node Established" are missing. See [the screenshot](https://www.dropbox.com/s/n13x8uxxx4fikpn/Screenshot%202017-11-29%2015.25.51.png?dl=0)

-----
fbitem-dc9112716eed62ae54c50ee0c5fe08d0a317e4bb
User provided contact info: cjk@sinica.edu.tw
System: Firefox 57.0.0 / Mac OS X 10.12.0
Referer: https://www.gbif.org/country/BE/summary
Window size: width 1265 - height 1100
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-29T07:27:25.306Z',mode:absolute,to:'2017-11-29T07:33:25.306Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-29T07:27:25.306Z',mode:absolute,to:'2017-11-29T07:33:25.306Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
Thank you for reporting it. I broke that yesterday i realise now. It is fixed again. That shouldn’t happen of course, but nice that someone notice it and reports it. Thank you.

> sent per mail
