### ISSUE TITLE
Chinese Taipei is for naming, not address

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#686]
**Chinese Taipei is for naming, not address**

In the previous version of GBIF.org, contacts of Chinese Taipei shares "Taiwan" as the location so far as [address](﻿https://www.dropbox.com/s/xb4dbgmjlk81f11/Screenshot%202017-11-29%2016.01.42.png?dl=0) is concerned.

In the real world no sane person will attempt to send a parcel to "Chinese Taipei" and expect his/her precious item will end up in the right hand(Hobern, 2013).

So, could you please kindly revise the address for us?

Thank you so much!

-----
fbitem-b9a89399d6e22a5a19c7088594ffd8667400a71f
User provided contact info: cjk@sinica.edu.tw
System: Firefox 57.0.0 / Mac OS X 10.12.0
Referer: https://www.gbif.org/contact-us/directory?group=associateParticipants
Window size: width 1265 - height 1100
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-29T08:20:28.837Z',mode:absolute,to:'2017-11-29T08:26:28.837Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-29T08:20:28.837Z',mode:absolute,to:'2017-11-29T08:26:28.837Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
@timhirsch should we introduce naming Taiwan/Chinese Taipei differently different places? If so what is the rule to choose when to choose one name over the other?

**Comment by timhirsch** [comment]
General rule is that Taiwan is the geographical location, Chinese Taipei the name of the GBIF participant. So it is logical to see both names. Any doubts refer to me.

**Comment by MortenHofft** [comment]
In that case i guess we have to change our basemaps as well? Since the geographical area is Taiwan
But I see that has been deliberately changed previously.

![5 1x](https://user-images.githubusercontent.com/6759267/33371639-b48b2acc-d4fb-11e7-8637-5a2a47e3d930.png)

**Comment by mdoering** [comment]
... and the occurrence search, details and anywhere we render the country codes?
https://www.gbif.org/occurrence/search?country=TW

**Comment by timhirsch** [comment]
Agreed it makes no sense for Taiwan to be used for base maps, contact addresses or data location. The only use of Chinese Taipei should be e.g. at https://www.gbif.org/participant/239 where the participation status in GBIF is relevant. Strictly the description at the top should be 'An associate participant economy from Asia' as opposed to 'organization' but I am not sure we have that as a separate category in the directory.

**Comment by MortenHofft** [comment]
kk - I'll change it back to Taiwan again then.

**Comment by MortenHofft** [comment]
will be available on next build to production

**Comment by cjk-halodule** [comment]
Thanks @MortenHofft & @timhirsch for this. I am sure my countrymen will all be happy.

**Comment by timhirsch** [comment]
Just for the record (I know the issue has been closed) I realise I mistyped the first line of my last comment - I meant to write 'Agree it makes no sense for **Chinese Taipei** to be used for base maps etc.' But I think that's how everyone has understood it, so fine!

**Comment by cjk-halodule** [comment]
I know it then meant "Chinese Taipei" because Taiwan does make perfect sense. And thanks for the clarification.

**Comment by cjk-halodule** [comment]
https://www.gbif.org/participant/239

Apparently there are still places that use wrong entity. See the country placement in the contacts below. But I can see if we look at the [TaiBIF node entity](https://www.gbif.org/publisher/12b1df00-3f75-11d8-aa2d-b8a03c50a862) the address is correct. Guess some consolidation in the backend is required. Please let me know if there is anything that should come from our end. Thanks again for addressing this issue.

**Comment by MattBlissett** [comment]
I have changed the address for the participant in the directory.

I have also edited the registry, so https://api.gbif.org/v1/enumeration/country will then say Taiwan. This mirrors the change made in the portal, which has it's own copy of the ISO code enumeration. I've not deployed this yet.

@cjk-halodule, do you see any other remaining Chinese Taipei's where there shouldn't be?
