### ISSUE TITLE
What happens when a taxonID in a checklist gets updated

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#688]
**What happens when a taxonID in a checklist gets updated**

Hi,

When a checklist is published, GBIF assigns `taxonKey`s to all taxa, e.g. `134088018` for `2201` (`Fragaria x ananassa (Weston) Rozier`): https://www.gbif.org/species/134088018

But what happens if the checklist is republished with a new taxonID or with a corrected spelling of the scientific name? Basically: what terms in the Taxon core influence the `taxonKey` (either to keep it or to assign a new one)?

* `taxonID`: what happens if this gets updated?
* `scientificName`: I assume an update in this generates a new `taxonKey`... but what about just spelling corrections (e.g. `Fragaria x ananassa (Weston) Rozier` without the `x`)?
* `kingdom`: I assume changing kingdom generates a new `taxonKey`
* `taxonRank`: does changing this affect anything?
* `scientificNameAuthorship`: does changing this affect anything?
* Any of the classification terms...

Having this information will help us to know which terms we can safely update and for which we have to be more cautious if we want stable GBIF assigned `taxonKeys`

Thanks

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
User provided contact info: @peterdesmet
System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/
Window size: width 1199 - height 736
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-30T09:15:21.068Z',mode:absolute,to:'2017-11-30T09:21:21.068Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-30T09:15:21.068Z',mode:absolute,to:'2017-11-30T09:21:21.068Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by mdoering** [comment]
@peterdesmet taxonID is the only property that is used to identify a source record. If it stays the same the same gbif key will be used. Otherwise a new one is generated each time.

**Comment by peterdesmet** [comment]
Thanks! Two more questions:

1. What happens is the scientific name changes for the same taxonID: is the backbone match re-evaluated for every update?
2. What happens with old keys if a new one is generated?

**Comment by mdoering** [comment]
1) yes, on every reindex all records are rematched to the backbone
2) its just gone and not reused. you will get a 404. The only checklist which keeps old ids around marked as deleted are backbone records
