### ISSUE TITLE
Bromeliads occurrence data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#69]
**Bromeliads occurrence data**

Dear of GBIF,

I am a PhD student and in my thesis I am investigate the effects of climate climate change in bromeliad frogs. So, I need occurrence data (decimal degrees) of 11 bromeliads: Aechmea aquilega, A. blanchetiana, A. lamarchei, A. leptantha, A. lingulata, A. nudicaulis, Alcantarea extensa, Neoregelia cruenta, Quesnelia quesneliana, Vriesea neoglutinosa and V. procera. How to download these data?  

Cheers,
Marcio.

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482

System: Chrome 56.0.2924 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/search?taxon_key=2698421&amp;advanced=1
Window size: width 1366 - height 638
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-08T11:23:35.693Z',mode:absolute,to:'2017-02-08T11:29:35.693Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-08T11:23:35.693Z',mode:absolute,to:'2017-02-08T11:29:35.693Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi Marcio
Thank you for trying out the demo site

Download are not implemented on the new development site yet, but it is available on our production site here: http://www.gbif.org/occurrence/search?taxon_key=2698421

Remember that you can add additional filters and that we flag occurrence records with different issues (such as unclear species names, wrong coordinate etc).

Thank you for your interest. 

I don't know if you have saved the link when you provided the feedback, but I see that you haven't provided a mail or other way to get in contact with you. I hope that you see this answer.
