### ISSUE TITLE
Out of sync

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#690]
**Out of sync**

Looks like this dataset is over indexed by ≈3 million

-----
fbitem-dataset6ac3f774-d9fb-4796-b3e9-92bf6c81c084

System: Chrome 62.0.3202 / Mac OS X 10.11.6
Referer: https://www.gbif.org/dataset/6ac3f774-d9fb-4796-b3e9-92bf6c81c084
Window size: width 1478 - height 1299
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-30T14:34:02.219Z',mode:absolute,to:'2017-11-30T14:40:02.219Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-30T14:34:02.219Z',mode:absolute,to:'2017-11-30T14:40:02.219Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MattBlissett** [comment]
@ahahn-gbif, @jlegind  quite a big overindex here.

**Comment by ahahn-gbif** [comment]
@jlegind Auto-deletion does not kick in here due to the protocol (BioCASe). This may need verification first that the last indexing run indeed completed through all name ranges, so that we do not lose records just because the last harvest run was interrupted.

**Comment by ahahn-gbif** [comment]
According to a "count" request to the wrapper endpoint, the dataset currently serves 8,953,374 records. The dataset page gives 8,999,981. This is still a slight discrepancy, but it appears that the main issue has been fixed. Can this be closed then, @jlegind ?

**Comment by jlegind** [comment]
I will leave this to when the pipeline project is rolled out and this resource is re-crawled.
The dataset has crawlID 123 going back to 2016.

**Comment by jlegind** [comment]
Resource failed completing crawl on the 11-12-2019.
It made it to 7,538,672 records out of ~10M

Will plead with them to create a ABCD or DwC archive.

**Comment by MattBlissett** [comment]
That's really the best solution here. We can't reliably retrieve all the data through BioCASe, so using either the BioCASe → ABCD archive, or the BioCASe → DWCA, or some other way, would be great.

**Comment by ManonGros** [comment]
Since the pipeline doesn't generate any over-indexing any more, I guess I will just close this issue.
