### ISSUE TITLE
No of iNaturalist records from November very low

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#691]
**No of iNaturalist records from November very low**

I just happened to notice that we don't seem to have any iNat records from after around Nov 10. Not sure what the problem might be.

cc @kueda

-----
fbitem-dataset50c9509d-22c7-4a22-a47d-8c48425ef4a7
User provided contact info: @dnoesgaard
System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7
Window size: width 1856 - height 953
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-01T12:12:42.375Z',mode:absolute,to:'2017-12-01T12:18:42.375Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-01T12:12:42.375Z',mode:absolute,to:'2017-12-01T12:18:42.375Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by kueda** [comment]
We switched our server provider a few weeks ago and it looks like we neglected to restart the GBIF exports. I fixed that situation and am creating a fresh DwC-A for you folks right now.

**Comment by dnoesgaard** [comment]
Thanks @kueda. Looks better now. Got records from December on yesterday's crawl.
