### ISSUE TITLE
Data Validator Trial Issues

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#692]
**Data Validator Trial Issues**

Using https://www.gbif.org/tools/data-validator.
Around 12:20 PM Washington time I dropped a ca. 70 MB zipped archive into the validator and after a couple of minutes the system returned: "The validation job ID was not found. If you believe this is an error, please report it."

When I paste in the URL for the published archive of the same resource, https://collections.nmnh.si.edu/ipt/archive.do?r=nmnh_paleo_dwc-a&v=1.10
the returned message is "The system is currently not able to process your request. Try to refresh the page and please report the issue if it continues." Is this kind of DwC-A URL listed on an IPT resource page acceptable to the validator?
Thanks!

-----
fbitem-16140b1a95f2e44c85bd9ac06218cf86ccbff0fa
User provided contact info: hollowellt@si.edu
System: Firefox 52.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/tools/data-validator/about
Window size: width 1024 - height 662
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-01T17:29:53.200Z',mode:absolute,to:'2017-12-01T17:35:53.200Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-01T17:29:53.200Z',mode:absolute,to:'2017-12-01T17:35:53.200Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by thomasstjerne** [comment]
User contacted by email.
The issues reported have been filed here: 
https://github.com/gbif/gbif-data-validator/issues/65
https://github.com/gbif/gbif-data-validator/issues/66
