### ISSUE TITLE
Can't find where to get data for environemtal layers on maxent to use the occurence data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#693]
**Can&#39;t find where to get data for environemtal layers on maxent to use the occurence data**

Im trying to collect data to predict a climate envelope for a few species. I can get the csv occurrence file to run on Maxent, but I have looked everywhere and cant find where to get the data for the environmental layers? Were can I get that?? Thanks!

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: adrienne_ducharme@yahoo.com
System: Chrome 62.0.3202 / Windows 8.1 0.0.0
Referer: https://www.gbif.org/occurrence/search
Window size: width 1366 - height 662
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-01T18:18:27.236Z',mode:absolute,to:'2017-12-01T18:24:27.236Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-01T18:18:27.236Z',mode:absolute,to:'2017-12-01T18:24:27.236Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
Hi Adrienne
We provide evidence based occurrences of species. We do not have environmental layers to support your Maxent work. For that you need to go somewhere else I'm afraid. Good luck with your work. 

> sent per mail
