### ISSUE TITLE
Alaska butterfly species with taxon name strings

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#694]
**Alaska butterfly species with taxon name strings**

Hello, 

I'm interested to find records of butterfly species collected in Fairbanks, AK that have taxon name strings, such as "cf" for conferred form, and species that have been determined as a "complex" :

For example : 
Boloria chariclea cf.

Here's a record from the Kenelm W. Philip Lepidoptera Collection, which I have been curating at the University of Alaska Museum

http://arctos.database.museum/guid/KWP:Ento:27045

and here's a saved search of the specimen records (as of 1 December 2017) with that name string : 

https://arctos.database.museum/saved/bcharicleacf

When I searched "Boloria chariclea" I didn't find these and wondered whether they are actually uploading to GBIF ? I downloaded the available dataset 

When using this dataset please use the following citation:
    GBIF.org (2nd December 2017) GBIF Occurrence Download https://doi.org/10.15468/dl.m5keku

I'm concerned that I didn't find "cf" and worry that this additional identification has been lost in the upload since I didn't find it in the infraspecific epithet. 

 I also couldn't find "Pieris marginalis complex"  - 

For example : 

http://arctos.database.museum/guid/KWP:Ento:15144

http://arctos.database.museum/saved/pmarginaliscomplex

Thank you for your time in helping me investigate this! 

Best regards, 

Kath Daly 

Curatorial Assistant
University of Alaska Museum 
Fairbanks, AK

kmdaly@alaska.edu

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51

System: Chrome 62.0.3202 / Windows 8.1 0.0.0
Referer: https://www.gbif.org/occurrence/download?country=US&has_coordinate=true&month=5&month=6&month=4&taxon_key=4299597&taxon_key=5137894&taxon_key=5714914&taxon_key=4299565&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))&geometry=POLYGON((-148.34007096074043%2064.62152957810845,-147.53806900761543%2064.62152957810845,-147.53806900761543%2065.08295535935845,-148.34007096074043%2065.08295535935845,-148.34007096074043%2064.62152957810845))
Window size: width 1094 - height 438
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-02T07:29:37.154Z',mode:absolute,to:'2017-12-02T07:35:37.154Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-02T07:29:37.154Z',mode:absolute,to:'2017-12-02T07:35:37.154Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by rdmpage** [comment]
Hi Kath, this looks like a case where GBIF has parsed the taxonomic name and matched it to the nearest name it already has. I've built a little tool to help me locate individual specimens in GBIF, and this might help you locate the specimens you mention. The tools lives at https://mellow-chill.glitch.me If you pause in "KWP:Ento:27045" you will find it in GBIF as https://gbif.org/occurrence/1502477870

The "cf" has been stripped off and the name interpreted as _Boloria chariclea_. What does "conferred form" mean? I always assumed that "cf" was a way for a taxonomist to say "compare with", in other words, it's like this species but not quite the same thing.

Likewise "KWP:Ento:15144" is https://gbif.org/occurrence/1502464871 and it looks like "Pieris marginalis complex" has been interpreted as a subspecies of _Pieris marginalis_, and since there isn't a subspecies called _complex_ GBIF matches it to the next taxon up, which is _Pieris marginalis_ (which is why there is a "Taxon match higherrank" issued highlighted in orange).

@mdoering will be able to add more detail, but I think the fundamental problem here is that the taxonomic names supplied are being "overloaded" with additional information (i.e., "cf") or are names that are informal ("complex"). Both create difficulties for GBIF. It would be useful to try and figure out a way to represent the information you want to convey in a way that GBIF doesn't misinterpret.

**Comment by mdoering** [comment]
Informal names with "cf." should be treated just as names without it.
The parser strips it off, marking the name as informal: http://api.gbif.org/v1/parser/name?name=Boloria%20chariclea%20cf.

**Comment by mdoering** [comment]
The Alaska Butterfly Boloria chariclea from above can be found here in GBIF:
https://www.gbif.org/occurrence/1502477870

It looks correctly interpreted to me and is searchable by its name and e.g. catalogue number:
https://www.gbif.org/occurrence/search?catalog_number=27045&taxon_key=4299565

Maybe data has changed in the meantime, but I do not see any issues in that case. Do I miss something?

PS: the bad authorship of the species and all others from FaEu should be fixed very soon in the next backbone build
