### ISSUE TITLE
Species in wrong Class

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#695]
**Species in wrong Class**

Acanthosoma haemorrhoidale is an insect, but the Classification says Malacostraca

https://www.gbif.org/species/5866246

-----
fbitem-species5866246
User provided contact info: Leivur Janus Hansen
System: Chrome 62.0.3202 / Windows 10 0.0.0
Referer: https://www.gbif.org/species/5866246
Window size: width 1745 - height 872
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-02T22:40:35.182Z',mode:absolute,to:'2017-12-02T22:46:35.182Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-02T22:40:35.182Z',mode:absolute,to:'2017-12-02T22:46:35.182Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by mdoering** [comment]
in Jan 2018 nub classified as AnimaliaArthropodaInsectaHemipteraAcanthosomatidaeAcanthosoma

https://www.gbif-uat.org/species/search?q=Acanthosoma%20haemorrhoidale
