### ISSUE TITLE
downloads without DOI

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#696]
**downloads without DOI**

How come this download doesn't have a DOI?

Same goes for https://www.gbif.org/occurrence/download/0005855-141123120432318

-----
fbitem-80ab0c5ecdcc17ab116917d15259b816c08e259c
User provided contact info: @dnoesgaard
System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/download/0000572-150116162929234
Window size: width 1876 - height 953
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-04T08:21:22.124Z',mode:absolute,to:'2017-12-04T08:27:22.124Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-04T08:21:22.124Z',mode:absolute,to:'2017-12-04T08:27:22.124Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
api https://api.gbif.org/v1/occurrence/download/0005855-141123120432318 doesn't have it either

**Comment by fmendezh** [comment]
GBIF started generating DOIs for downloads on 2015-02-03, all downloads before that date do not have  DOI:
https://www.gbif.org/occurrence/download/0005855-141123120432318  and https://www.gbif.org/occurrence/download/0005855-141123120432318 are from 2014

**Comment by dnoesgaard** [comment]
Ah, well that explains it. Thanks!

**Comment by MortenHofft** [comment]
In that case i will open this is a ticket to remove it from the UI

**Comment by dnoesgaard** [comment]
Morten, are you suggesting removing the DOI button from the downloads that don't have one?

Alternatively, we could add a faq explainer like "GBIF started generating DOIs for downloads on blablalba"

What do you think?

**Comment by MortenHofft** [comment]
I hadn't really thought it through - just that something had to change. I like it. So a short sentence either in the header where the DOI used to be or on the card explaining why there isn't one. Do you have enough to say that it should be an FAQ entry? Or should we just put it in the translation file (i vote for the latter)

**Comment by dnoesgaard** [comment]
I actually think having a FAQ entry on when we started issuing DOIs is reasonable. I'll make it happen.

**Comment by dnoesgaard** [comment]
https://www.gbif.org/faq?question=how-and-when-does-gbif-assign-digital-object-identifiers-dois

I'm unsure of when we started assigning DOIs to datasets, but if we did it for all datasets, it might not be as important.

**Comment by kcopas** [comment]
Probably corresponds to the release date of IPT v2.2 (whenever that was). Here's [the news item](https://www.gbif.org/news/82383).

**Comment by dnoesgaard** [comment]
Just updating this one to catch what we just discussed:

- we should be able to somehow mint DOIs for pre-Feb 2015 downloads
- if possible, introduce a button for logged-in users to trigger the DOI minting

**Comment by dnoesgaard** [comment]
A quick question related to this:

When did we start assigning identifiers to downloads? In other words, if an author logs into their gbif.org account, how far back in time can they access downloads?

**Comment by MattBlissett** [comment]
The oldest download we have a record for is from 2013-09-23 17:20:27.224551+02, it's this one: https://www.gbif.org/occurrence/download/0000222-130906152512535

The first download with a DOI is this one, from 2015-02-03 15:06:31.015791+01. https://www.gbif.org/occurrence/download/0000364-150202100118378 It was a test by Tim, so we didn't keep the data file.

The first user download with a DOI is this one: https://www.gbif.org/occurrence/download/0000365-150202100118378 from less than a minute later.

So we started assigning DOIs on 2015-02-03 at 15:06:31, but we have identifiers (if the GBIF download link counts) from 2013-09-23.

**Comment by dnoesgaard** [comment]
Thanks @MattBlissett - very useful!

**Comment by MortenHofft** [comment]
I've added the link to the FAQ entry

**Comment by dnoesgaard** [comment]
These are still outstanding, but may be out of scope for this issue?

- we should be able to somehow mint DOIs for pre-Feb 2015 downloads
- if possible, introduce a button for logged-in users to trigger the DOI minting
