### ISSUE TITLE
missing cache header on dataset process summary

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#698]
**missing cache header on dataset process summary**

this means that the dataset isn't properly updated when crawling is completed until 10 minutes or so after.
Either a shorter cache or cachebusting when trusted contact

-----
fbitem-dataset2cc10a76-a0f4-4c6d-8703-3a62dc7f356f
User provided contact info: @MortenHofft
System: Chrome 62.0.3202 / Mac OS X 10.11.6
Referer: https://www.gbif.org/dataset/2cc10a76-a0f4-4c6d-8703-3a62dc7f356f
Window size: width 1220 - height 1320
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-05T10:32:49.933Z',mode:absolute,to:'2017-12-05T10:38:49.933Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-05T10:32:49.933Z',mode:absolute,to:'2017-12-05T10:38:49.933Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
cachebusting added

**Comment by MattBlissett** [comment]
I'd rather fix Varnish so this works everywhere.

`/dataset/process` is set to no caching, which query are you using here?

**Comment by MortenHofft** [comment]
I set cache headers on the server when i need it. this is an internal API call. I deemed that in this case i would rather use the default cache unless the user was a trusted dataset contact and should see the latest info. I do not think you should set it in varnish in this case. 
but thank you

**Comment by MortenHofft** [comment]
cache busting is useful in this case to get the update for example after pushing CRAWL NOW. For users that do not do that, a 10 minute old version is just fine. In cases where i do not think so i set the exp time in express (I believe varnish respects that)
