### ISSUE TITLE
mapbox draw doesn't support ie

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#7]
**mapbox draw doesn&#39;t support ie**

that is a shame. Inform the user so it doesn&#39;t appear like an error and suggest an alternative browser

-----
fbitem-f0b1d8e8c6811b830ef2f932fb5cf1be7ba9cf0a

System: Chrome 54.0.2840 / Mac OS X 10.11.6
Referer: https://demo.gbif-uat.org/tools/species-population
Window size: width 1920 - height 1076

**Comment by MortenHofft** [comment]
The user is now informed, but not exactly in a nice manner. A big white box blocks everything but the menu and states in p.tag that ie isn't supported. hot fix for now. 
We need a general approach to address outdates browsers for the site en general and for individual pages that have functionality that isn't widely supported.

closing as the user is informed. Opening new issue to do this in a more appealing user friendly manner: https://github.com/gbif/portal16/issues/177
