### ISSUE TITLE
system health additions

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#700]
**system health additions**

Hey

Is it possible to add a link to the human-readable version of these endpoints, e.g. for

https://github.com/gbif/portal16/blob/34b21df761d57dfd2b915708b172d745bfc1ec0b/app/controllers/api/health/tests.js#L127

add a link to https://www.contentfulstatus.com/

Similar for Github, we could add a link to https://status.github.com/

Thanks

-----
fbitem-465f4ad16ed342b1a2d0972aceb430078ee021ba
User provided contact info: @dnoesgaard
System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/health
Window size: width 1580 - height 953
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-05T14:01:11.559Z',mode:absolute,to:'2017-12-05T14:07:11.559Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-05T14:01:11.559Z',mode:absolute,to:'2017-12-05T14:07:11.559Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by MortenHofft** [comment]
Sure, do you think anyone else is intersted in it? Since we are having a 5 minutes cache we might link to a page that says happy, while we say not so.

**Comment by dnoesgaard** [comment]
Probably no one else is, but aren't these messages only shown for secretariat staff anyway?

Re the cache, it would be good to include exact timestamps to avoid confusion.

**Comment by MortenHofft** [comment]
some of it is secretariat only. the red error messages in the bottom. I can add the link there. that makes sense to have in all cases.

exact timestamps: you mean instead of the "Updated a few seconds ago" ?

**Comment by dnoesgaard** [comment]
I mean, if the results we're showing are cached, it would make sense to post a timestamp of when they were "fresh". Or maybe I'm misunderstanding how it works.

**Comment by MortenHofft** [comment]
I've added the urls as it was free. timestamps i will leave out for now as it would break the way i detect changes with the current implementation (things would change with every test then despite the results being the same). And this it isn't really the place for debugging. We have other tools for that as mentioned above.
