### ISSUE TITLE
"Content management system" incorrectly shows unstable

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#701]
**&quot;Content management system&quot; incorrectly shows unstable**

When the content crawling is running this shows as unstable when I don't believe it is.  Suggest we need to review how this is monitored, as I see this many times a day (others have also commented)

Minor addition: "Content mangement system" has a typo

-----
fbitem-465f4ad16ed342b1a2d0972aceb430078ee021ba
User provided contact info: @timrobertson100
System: Chrome 62.0.3202 / Mac OS X 10.11.5
Referer: https://www.gbif.org/health
Window size: width 1481 - height 917
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-05T14:09:42.700Z',mode:absolute,to:'2017-12-05T14:15:42.700Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-05T14:09:42.700Z',mode:absolute,to:'2017-12-05T14:15:42.700Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
"Content mangement system" is calling an external url provided by contentful that reports their system health. it has nothing to do with our crawling. If it fails it is because we get an error back from them. I can try to log in more details what happens. The state is sticky for 5 minutes after a failure (that is even if it responds as expected again) - this is done because occurrence search fx can be very flaky at times and to avoid error, no-error, error, no-error and a red dot blinking it has a lag. it is in other words unstable because it failed within the last 5 minutes.

**Comment by dnoesgaard** [comment]
Also, fwiw, Contentful did have serious issue with the content delivery API yesterday...

**Comment by MortenHofft** [comment]
I think the issue has to do with me assuming that the array provided by contentful had a fixed ordering https://www.contentfulstatus.com/history.json that is not the case i see. So yesterday it probably tested for mangement API. it does so now I see. I will change that.

That also fits with their status page https://www.contentfulstatus.com/# where they say they had issues with management API yesterday.

"Content Delivery API" used to be first - or I made a mistake when implementing it.
```
"components": [
{
"status": "operational",
"name": "Content Management API",
"created_at": "2013-11-01T17:17:34.168Z",
"updated_at": "2017-12-05T14:04:16.285Z",
"position": 1,
"description": "API used for content management by editors",
"showcase": false,
"id": "0fdg751p3dxn",
"group_id": null,
"page_id": "4bv17htq00cz",
"group": false,
"only_show_if_degraded": false
},
{
"status": "operational",
"name": "Content Delivery API",
"created_at": "2013-11-01T17:18:03.112Z",
"updated_at": "2017-06-28T14:46:32.625Z",
"position": 2,
"description": "API for delivering content across-platforms to end-users",
"showcase": false,
"id": "b05r4f74kkmg",
"group_id": null,
"page_id": "4bv17htq00cz",
"group": false,
"only_show_if_degraded": false
},
```

**Comment by MortenHofft** [comment]
There was a couple of issues. 

1) the contentful status endpoint would occasionaly time out.
2) we assumed fixed ordering of an array that wasn't so.

the solution has been to only show as a warning, not an outage. And to implement a custom test for contentful that shows as operations if their endpoints fails.

add test https://github.com/gbif/portal16/commit/0457d89d05cfb51c93ccc8819d240de641437395

enable test https://github.com/gbif/portal16/commit/b88302c228708220a30f3266bccbae3680c710d9
