### ISSUE TITLE
Trends page for a participant

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#702]
**Trends page for a participant**

So in front of our auditors I wanted to demonstrate that GBIFS has done a lot in tracking data publishing activities hence the value of contributing to this global effort. Embarrassment follows that those pages were gone, even from the www-old. Now those figures can only be found by downloading country report, but not available online.

Any plan to surface that again? Please do.

-----
fbitem-67cbf865735ab20856e1e6649eab1c4073bc341e
User provided contact info: cjk@sinica.edu.tw
System: Firefox 57.0.0 / Mac OS X 10.12.0
Referer: https://www.gbif.org/
Window size: width 1238 - height 1057
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-06T04:46:24.273Z',mode:absolute,to:'2017-12-06T04:52:24.273Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-06T04:46:24.273Z',mode:absolute,to:'2017-12-06T04:52:24.273Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by kcopas** [comment]
Are you overlooking what's on the [Data about](https://www.gbif.org/country/TW/about) and [Data publishing](https://www.gbif.org/country/TW/publishing) pages?

**Comment by cjk-halodule** [comment]
Strange - should've posted the screenshot when I accessed it on Wednesday but I can see them now, all good.

Thanks for attending the issue.

**Comment by MortenHofft** [comment]
Perhaps related to the slow performance reported in https://github.com/gbif/portal-feedback/issues/710
