### ISSUE TITLE
Unexplained data metrics turning up on GBIF Network page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#705]
**Unexplained data metrics turning up on GBIF Network page**

In the list of Oceania region participants, the new associate participant SPREP is shown as publishing 2 datasets with 17806 records and having 1 publisher; but the SPREP page when you click on it shows no datasets. Not sure what is going on here ...

-----
fbitem-7d2b1d1c147a9c4dc69d03c90d734bc326226c75
User provided contact info: @timhirsch
System: Chrome 62.0.3202 / Mac OS X 10.13.1
Referer: https://www.gbif.org/the-gbif-network/oceania
Window size: width 1920 - height 953
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-07T21:35:47.503Z',mode:absolute,to:'2017-12-07T21:41:47.503Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-07T21:35:47.503Z',mode:absolute,to:'2017-12-07T21:41:47.503Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by thomasstjerne** [comment]
The network page gets data from the registry:
http://api.gbif.org/v1/node/29c6a139-ea7f-41f5-8d9b-c55af8736182/dataset
The [participantpage](https://www.gbif.org/participant/377)  gets data from the directory: 
http://api.gbif.org/v1/directory/participant/377
It seems that the directory is out of sync with the registry here.

**Comment by MortenHofft** [comment]
@thomasstjerne the participant page also gets the dataset list from the registry. So discrepancies must be due to something else. caching likely.

**Comment by timhirsch** [comment]
Yes datasets now showing up on SPREP page - thanks.

**Comment by thomasstjerne** [comment]
@MortenHofft yes, but the node id is retrieved from the directory - so this assertion failed: https://github.com/gbif/portal16/blob/master/app/models/node/participant.js#L114

The node is now created in the directory and synced with the registry.
