### ISSUE TITLE
Gbif information into maxent

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#708]
**Gbif information into maxent**

I am trying to create a .csv list that is able to be processed by maxent. The files I have downloaded so far are unable to be processed by maxent. Is there a simple way to organize a list of species occurrences into a maxent friendly format consisting of species name and long and latitude lists?

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb
User provided contact info: tommyplatero@yahoo.com
System: Chrome 62.0.3202 / Windows 10 0.0.0
Referer: https://www.gbif.org/resource/search?contentType=tool
Window size: width 1920 - height 925
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-09T23:21:50.857Z',mode:absolute,to:'2017-12-09T23:27:50.857Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-09T23:21:50.857Z',mode:absolute,to:'2017-12-09T23:27:50.857Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
@dnoesgaard given that Maxent is something that we promote in the menu it might be worth addressing this?

**Comment by dnoesgaard** [comment]
It seems that a lot of people use GBIF data with Maxent, so I don't think that's a general issue. It might be worth redirecting the user to the helpdesk for assistance.

**Comment by dnoesgaard** [comment]
- follow [these instructions](https://www.gbif.org/faq?q=excel) to get occurrences into Excel
- delete the columns for all but except scientificName, decimalLatitude and decimalLongitude
- swap column order as maxent requires the data format specifically ordered to species name, x (long), y (lat).
- remove header row
- save the file as a .csv, and it should be ready for use in Maxent.

(sent email to user)

**Comment by dnoesgaard** [comment]
(consider adding to Maxent tool page or FAQ)
