### ISSUE TITLE
'Related document and information' section is not showing

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#71]
**&#39;Related document and information&#39; section is not showing**

A section is missing in this BID project page: It should display under the &#39;Related document and information&#39; section this project Midterm report. (see http://www.gbif.org/programme/bid/project/africa/2015/benin-forest-data-mobilization)

-----
fbitem-84f9f43a0cdf469c4d57fbe0612ea740c88b1198
Reported by: mblaursen@gbif.org
System: Firefox 51.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/project/bid/africa/2015/benin-forest-data-mobilization
Window size: width 1920 - height 947
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-09T10:47:34.707Z',mode:absolute,to:'2017-02-09T10:53:34.707Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-09T10:47:34.707Z',mode:absolute,to:'2017-02-09T10:53:34.707Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thank you for reporting this.
You can follow along in the process of this here: https://github.com/gbif/portal16/issues/175

>user informed per mail
