### ISSUE TITLE
Location data for Brotogeris versicolurus not in downloaded file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#711]
**Location data for Brotogeris versicolurus not in downloaded file**

Hello, I am trying to download location records of Brotogeris versicolurus, but when I download the file, the lat/lon fields are blank even though the overview of the data shows a considerable ammount of locations.

-----
fbitem-8cd7f54dc4f3a7704f3fd0363c7a4bf80705fb32
User provided contact info: wilfredo.falcon@ieu.uzh.ch
System: Safari 11.0.2 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/download/0007458-171124123535762
Window size: width 1276 - height 716
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-11T09:07:09.450Z',mode:absolute,to:'2017-12-11T09:13:09.450Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-11T09:07:09.450Z',mode:absolute,to:'2017-12-11T09:13:09.450Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
Hi
I just downloaded the file. Many if the occurrences have lat/lon called `decimallatitude` and `decimallongitude`. I think you might be looking at the wrong columns?
First lines seen in screenshot below.
![screen shot 2017-12-11 at 11 43 50](https://user-images.githubusercontent.com/6759267/33827429-9976dfd0-de68-11e7-819c-839189d6145a.png)
