### ISSUE TITLE
/species/{int}/related has paging

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#712]
**/species/{int}/related has paging**

The `/species/{int}/related` API is listed as having paging = `false`, but I think it does have paging.

-----
fbitem-d7fe0c58772fa99501bfeba54604bc553eb4399f
User provided contact info: @peterdesmet
System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/developer/species
Window size: width 1166 - height 636
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-11T10:11:25.604Z',mode:absolute,to:'2017-12-11T10:17:25.604Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-11T10:11:25.604Z',mode:absolute,to:'2017-12-11T10:17:25.604Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by peterdesmet** [comment]
And probably idem for `http://api.gbif.org/v1/species/5231190/combinations` although the example doesn't return results, so cannot test.

**Comment by peterdesmet** [comment]
@MortenHofft does `/species/{int}/combinations` have paging? If yes, needs to be corrected as well. :blush:

**Comment by mdoering** [comment]
combinations is a plain list. An empty paging response would look like this: http://api.gbif.org/v1/species/search?q=fdferwfgwergcombinations

But related indeed is a paged operation: http://api.gbif.org/v1/species/1/related

**Comment by peterdesmet** [comment]
@mdoering 👍  Is there a combinations example that is not empty?

**Comment by mdoering** [comment]
its the reverse of the basionym relations but only works in case you look at the basionym:
https://api.gbif.org/v1/species/2435104/combinations
