### ISSUE TITLE
Table too wide

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#713]
**Table too wide**

The `Occurrence Metrics` table in the API documentation contains a URL in `Description` that causes the right of the table to disappear. It isn't too bad (because there is no content on the right), but it might be better to set:

```css
.table {
   hyphens: auto;
}
```

Note: this can cause some zealous hyphenation where it isn't necessary, but it will wrap the content nicely.

-----
fbitem-b1018fb447ec8b1aa84ee420b36825314783d5a9
User provided contact info: @peterdesmet
System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1166 - height 636
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-11T10:21:57.889Z',mode:absolute,to:'2017-12-11T10:27:57.889Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-11T10:21:57.889Z',mode:absolute,to:'2017-12-11T10:27:57.889Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by peterdesmet** [comment]
Screenshot:

![table-break](https://user-images.githubusercontent.com/600993/33826725-3bef327e-de66-11e7-856a-1c9ae3e92b6d.png)

**Comment by MortenHofft** [comment]
Hi Peter - yeah those pages really need a makeover. It is on the list :)
Thanks - that might be a quick fix for some of the issues.
