### ISSUE TITLE
dataset crawling / process API not documented

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#714]
**dataset crawling / process API not documented**

There must be a way to read the historic crawls from the registry which is not documented here. Sth the portal uses at https://www.gbif.org/api/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e/processSummary

-----
fbitem-79134785ef60aca67184f0d6352302a982e0c66d

System: Chrome 62.0.3202 / Mac OS X 10.12.6
Referer: https://www.gbif.org/developer/registry
Window size: width 1414 - height 772
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-11T13:33:37.913Z',mode:absolute,to:'2017-12-11T13:39:37.913Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-11T13:33:37.913Z',mode:absolute,to:'2017-12-11T13:39:37.913Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
that URL is not a part of the APIs. You can explore the APIs at https://www.gbif.org/developer/registry

**Comment by timrobertson100** [comment]
Please also be aware that is likely to change format and content in the coming months.  Please feel free to use it, but use with caution that it is volatile.

**Comment by mdoering** [comment]
Should not +/- all information exposed in the portal be publicly available through the API?

**Comment by MortenHofft** [comment]
I believe they are. The exceptions to that rule is

* directory API: that isn't public as it holds private mails and phonenumbers.
* the crawl endpoints: that is public, but undocumented
* contentful api: that requires auth
