### ISSUE TITLE
Lasioglossum is the actual genus (Dialictus is a subgenus from this)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#715]
**Lasioglossum is the actual genus (Dialictus is a subgenus from this)**

Seeing the occurrence I visited this page 
https://en.wikipedia.org/wiki/Dialictus
that said 
Dialictus is a subgenus of sweat bees belonging to the genus Lasiolossum.

-----
fbitem-occurrence665635687
User provided contact info: npascual@imbiv.unc.edu.ar
System: Chrome 63.0.3239 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/665635687
Window size: width 1303 - height 677
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-11T19:48:30.782Z',mode:absolute,to:'2017-12-11T19:54:30.782Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-11T19:48:30.782Z',mode:absolute,to:'2017-12-11T19:54:30.782Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO
datasetKey: 86b3c16c-f762-11e1-a439-00145eb45e9a
publishingOrgKey: 8595cd50-87c0-11dc-bb35-b8a03c50a862

**Comment by mdoering** [comment]
This indeed seems to have been originally published as a subgenus. GBIF has a few checklists that treat it as a genus, but this looks like an error in most case.

It raises a general question how the backbone build deals with generic names that can be treated on genus or subgenus level. As we do not include subgenera the backbone build might only pick up the genus usages, thereby not using our most preferred source. Even if the backbone does not include subgenera it should therefore at least remember a subenus as found in a preferred source so it does not turn into a regular genus is a subsequent source.

**Comment by mdoering** [comment]
Filed under backbone building issue at gbif/checklistbank#51
