### ISSUE TITLE
Change Technical Contact

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#716]
**Change Technical Contact**

Please edit the technical contact for the publisher GBIF-Sweden. 

Manash Shah
manash.shah@gbif.se

-----
fbitem-publisher4c415e40-1e21-11de-9e40-a0d6ecebb8bf
User provided contact info: @shahmanassh
System: Firefox 57.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/publisher/4c415e40-1e21-11de-9e40-a0d6ecebb8bf
Window size: width 1680 - height 894
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-12T08:12:28.563Z',mode:absolute,to:'2017-12-12T08:18:28.563Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-12T08:12:28.563Z',mode:absolute,to:'2017-12-12T08:18:28.563Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MattBlissett** [comment]
@shahmanassh, done.
