### ISSUE TITLE
Possibly dead links

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#717]
@dnoesgaard and @kcopas I've compiled a list of links that looks suspicious one way or another. You might want to go through them. I haven't tested them all and some will work fine. Flickr fx returns unauthroized (403) when I tried by script, but works from the browser. But at least it is a help finding them.

**Likely dead links**

* [x] tool: [ Data Accessibility Benchmark Organizational Self-Assessment Tool by ACZISC ](http://gbif.org/tool/82119) returns 403 for [http://coinatlantic.ca/index.php/coinatlantic/data-accessibility-benchmark-tool](http://coinatlantic.ca/index.php/coinatlantic/data-accessibility-benchmark-tool)
* [x] tool: [ Anymals+plants mobile application ](http://gbif.org/tool/81494) returns 404 for [https://play.google.com/store/apps/details?id=org.anymals.anymallog](https://play.google.com/store/apps/details?id=org.anymals.anymallog)
* [x] tool: [ BerkeleyMapper ](http://gbif.org/tool/81294) returns 404 for [http://berkeleymapper.berkeley.edu/images/diagram.gif](http://berkeleymapper.berkeley.edu/images/diagram.gif)
* [x] project: [ Building Capacity for Biodiversity Data Mobilization and Conservation in Liberia ](http://gbif.org/project/2FbcNn7o2c08W4m2ywUAQi) returns 403 for [http://www.ul.edu.lr/](http://www.ul.edu.lr/)
* [x] project: [ Developing biodiversity informatics in Haiti for better conservation management ](http://gbif.org/project/83257) returns 403 for [https://www.flickr.com/gp/44353813@N02/79xUS5](https://www.flickr.com/gp/44353813@N02/79xUS5)
* [x] project: [ Mobilizing biodiversity information from the Kenya Wildlife Service ](http://gbif.org/project/82706) returns 403 for [https://www.flickr.com/gp/44353813@N02/R7ATK8](https://www.flickr.com/gp/44353813@N02/R7ATK8)
* [x] project: [ Capacity enhancement for the Ghana node of GBIF ](http://gbif.org/project/82661) returns 403 for [https://www.flickr.com/gp/44353813@N02/dc0df8](https://www.flickr.com/gp/44353813@N02/dc0df8)
* [x] project: [ Senegalese National Information System on Biodiversity - SENBIO-INFOS ](http://gbif.org/project/82736) returns 403 for [https://www.flickr.com/gp/44353813@N02/A590K3](https://www.flickr.com/gp/44353813@N02/A590K3)
* [x] project: [ Senegalese National Information System on Biodiversity - SENBIO-INFOS ](http://gbif.org/project/82736) returns 404 for [http://afriquepresse.net/index.php/2016/10/27/gestion-des-donnees-de-la-biodiversite-au-senegal-senbio-info-un-outil-de-facilitation-du-partage-dinformations-fiables/](http://afriquepresse.net/index.php/2016/10/27/gestion-des-donnees-de-la-biodiversite-au-senegal-senbio-info-un-outil-de-facilitation-du-partage-dinformations-fiables/)
* [x] project: [ Senegalese National Information System on Biodiversity - SENBIO-INFOS ](http://gbif.org/project/82736) returns 404 for [http://www.aps.sn/actualites/environnement/article/un-expert-revient-sur-l-importance-de-l-information-en-gestion-des-ecosystemes](http://www.aps.sn/actualites/environnement/article/un-expert-revient-sur-l-importance-de-l-information-en-gestion-des-ecosystemes)
* [x] project: [ Gathering of biodiversity data on bird species for their sustainable management in Benin ](http://gbif.org/project/82723) returns 403 for [https://www.flickr.com/gp/44353813@N02/WSN56S](https://www.flickr.com/gp/44353813@N02/WSN56S)
* [x] project: [ Mobilizing plant diversity data in Uganda through training ](http://gbif.org/project/82781) returns 403 for [https://www.flickr.com/gp/44353813@N02/40uwQ6](https://www.flickr.com/gp/44353813@N02/40uwQ6)
* [x] project: [ Capacity building and biodiversity data mobilization for conservation and policy in Africa ](http://gbif.org/project/82750) returns 403 for [https://www.flickr.com/gp/44353813@N02/u00cJ8](https://www.flickr.com/gp/44353813@N02/u00cJ8)
* [x] project: [ Data rescue for the records of the Botswana Wildlife Management Association ](http://gbif.org/project/82758) returns 403 for [https://www.flickr.com/gp/44353813@N02/bS4831](https://www.flickr.com/gp/44353813@N02/bS4831)
* [x] project: [ Strengthening the institutional network in Angola to mobilize biodiversity data ](http://gbif.org/project/82775) returns 403 for [https://www.flickr.com/gp/44353813@N02/VcfA7X](https://www.flickr.com/gp/44353813@N02/VcfA7X)
* [x] project: [ Biodiversity data mobilization in the Albertine Rift region ](http://gbif.org/project/82764) returns 403 for [https://www.flickr.com/gp/44353813@N02/GUon92](https://www.flickr.com/gp/44353813@N02/GUon92)
* [x] project: [ Providing access to the zoology collection of the Natural History Museum of Zimbabwe ](http://gbif.org/project/82771) returns 403 for [https://www.flickr.com/gp/44353813@N02/G48K00](https://www.flickr.com/gp/44353813@N02/G48K00)
* [x] project: [ Publishing metadata for biodiversity data generated from REDD+ projects in Tanzania ](http://gbif.org/project/82753) returns 404 for [http://www.un-redd.org/aboutredd](http://www.un-redd.org/aboutredd)
* [x] project: [ Agrotraining:­ Proofing GBIF use on agrobiodiversity through needs assessment and training ](http://gbif.org/project/82833) returns 404 for [http://www.colegiof3.ulisboa.pt/index_en.php](http://www.colegiof3.ulisboa.pt/index_en.php)
* [x] project: [ Strengthening the biodiversity stakeholders network in Togo ](http://gbif.org/project/82693) returns 403 for [https://www.flickr.com/gp/44353813@N02/7L1083](https://www.flickr.com/gp/44353813@N02/7L1083)
* [x] project: [ Strengthening the biodiversity stakeholders network in Togo ](http://gbif.org/project/82693) returns 404 for [http://univ-lome.tg/index.php/recherches-scientifiques-9/item/846-atelier-de-renforcement-des-capacites-en-mobilisation-et-publication-des-donnees-sur-la-biodiversite-au-togo](http://univ-lome.tg/index.php/recherches-scientifiques-9/item/846-atelier-de-renforcement-des-capacites-en-mobilisation-et-publication-des-donnees-sur-la-biodiversite-au-togo)
* [x] project: [ Strengthening the biodiversity stakeholders network in Togo ](http://gbif.org/project/82693) returns 404 for [http://univ-lome.tg/index.php/component/k2/item/854-fin-de-l%E2%80%99atelier-de-renforcement-de-capacites-en-mobilisation-et-publication-de-donnees-de-la-biodiversite-au-togo](http://univ-lome.tg/index.php/component/k2/item/854-fin-de-l%E2%80%99atelier-de-renforcement-de-capacites-en-mobilisation-et-publication-de-donnees-de-la-biodiversite-au-togo)
* [x] project: [ Checklist of mammals in the southwestern Mongolian-Manchurian Ecoregion ](http://gbif.org/project/83223) returns 403 for [http://www.greeninitiativengo.org](http://www.greeninitiativengo.org)
* [x] project: [ Mobilization of biodiversity data on protected areas and threatened species  in Benin ](http://gbif.org/project/82703) returns 403 for [https://www.flickr.com/gp/44353813@N02/Uz8GM7](https://www.flickr.com/gp/44353813@N02/Uz8GM7)
* [x] project: [ Towards a Red List of the globally threatened plants of Guinea ](http://gbif.org/project/82721) returns 403 for [https://www.flickr.com/gp/44353813@N02/w95aZT](https://www.flickr.com/gp/44353813@N02/w95aZT)
* [x] project: [ Development of a funding mechanism and efficient management of data on plant biodiversity in Côte d’Ivoire ](http://gbif.org/project/82698) returns 403 for [https://www.flickr.com/gp/44353813@N02/2c94aE](https://www.flickr.com/gp/44353813@N02/2c94aE)
* [x] project: [ Kenya’s other carnivores: harnessing biodiversity data for conservation ](http://gbif.org/project/82779) returns 403 for [https://www.flickr.com/gp/44353813@N02/bpW1Gg](https://www.flickr.com/gp/44353813@N02/bpW1Gg)
* [x] project: [ Capacity building and biodiversity data mobilization to address health and food security priorities in Benin ](http://gbif.org/project/82741) returns 403 for [https://www.flickr.com/gp/44353813@N02/EaFAM2](https://www.flickr.com/gp/44353813@N02/EaFAM2)
* [x] article: [ Data quality requirements: Occurrence-only datasets ](http://gbif.org/article/ADIoPrOOXIWSeeQOQ6K6E) returns 404 for [https://knb.ecoinformatics.org/eml-resource.html#creator](https://knb.ecoinformatics.org/eml-resource.html#creator)
* [x] article: [ Data quality requirements: Occurrence-only datasets ](http://gbif.org/article/ADIoPrOOXIWSeeQOQ6K6E) returns 404 for [https://knb.ecoinformatics.org/eml-resource.html#metadataProvider](https://knb.ecoinformatics.org/eml-resource.html#metadataProvider)
* [x] article: [ Data quality requirements: Occurrence-only datasets ](http://gbif.org/article/ADIoPrOOXIWSeeQOQ6K6E) returns 404 for [https://knb.ecoinformatics.org/eml.html#citation](https://knb.ecoinformatics.org/eml.html#citation)
* [x] article: [ Citizen science ](http://gbif.org/article/3eKXvn2Go8WOWsGgGcKwQG) returns 404 for [http://www.ukeof.org.uk/documents/understanding-citizen-science.pdf](http://www.ukeof.org.uk/documents/understanding-citizen-science.pdf)
* [x] article: [ Funders ](http://gbif.org/article/7aCgeh7TJmuCAsUskqMeAE) returns 404 for [http://www.csiro.au/Outcomes/Environment/Biodiversity/The-Atlas-of-Living-Australia.aspx](http://www.csiro.au/Outcomes/Environment/Biodiversity/The-Atlas-of-Living-Australia.aspx)
* [x] article: [ Funders ](http://gbif.org/article/7aCgeh7TJmuCAsUskqMeAE) returns 404 for [http://www.humboldt.org.co/iavh](http://www.humboldt.org.co/iavh)
* [x] article: [ Funders ](http://gbif.org/article/7aCgeh7TJmuCAsUskqMeAE) returns 404 for [http://www.aka.fi/ENG](http://www.aka.fi/ENG)
* [x] article: [ Funders ](http://gbif.org/article/7aCgeh7TJmuCAsUskqMeAE) returns 404 for [http://www.bafu.admin.ch/index.html?lang=en](http://www.bafu.admin.ch/index.html?lang=en)
* [x] article: [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 404 for [https://www.hindawi.com/journals/dpis/apc/](https://www.hindawi.com/journals/dpis/apc/)
* [x] article: [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 404 for [http://earth-perspectives.springeropen.com/submission-guidelines/fees-and-funding](http://earth-perspectives.springeropen.com/submission-guidelines/fees-and-funding)
* [x] article: [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 404 for [http://onlinelibrary.wiley.com/journal/10.1002/(ISSN)2049-6060/homepage/article_publication_charges.htm](http://onlinelibrary.wiley.com/journal/10.1002/(ISSN)2049-6060/homepage/article_publication_charges.htm)
* [x] article: [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 404 for [http://gigascience.biomedcentral.com/submission-guidelines/fees-and-funding](http://gigascience.biomedcentral.com/submission-guidelines/fees-and-funding)

**Failed for some reason**

* [x] [ GeoCAT - Geospatial Conservation Assessment Tool ](http://gbif.org/tool/81755) returns 500 for [http://geocat.kew.org/](http://geocat.kew.org/)
* [x] [ OpenUp! Data Quality Toolkit ](http://gbif.org/tool/81748) returns 500 for [http://services.bgbm.org/DataQualityToolkit/](http://services.bgbm.org/DataQualityToolkit/)
* [x] [ Getting the plants to all: dissemination of information from the collection of The Mauritius Herbarium ](http://gbif.org/project/aRCxBBF1BYU2C0us62ea4) returns 500 for [https://www.levelovertilemaurice.org/](https://www.levelovertilemaurice.org/)
* [x] [ Capacity advancement for the Nigeria node of GBIF ](http://gbif.org/project/6PYpxnirfiMs2AQYIc0IO2) returns 500 for [https://nsuk.edu.ng/](https://nsuk.edu.ng/)
* [x] [ GBIF.es ](http://gbif.org/project/82954) returns 500 for [https://datos.gbif.es](https://datos.gbif.es)
* [x] [ Atlas of Living Scotland ](http://gbif.org/project/82973) returns 500 for [https://www.als.scot/about-the-atlas-of-living-scotland/objectives/](https://www.als.scot/about-the-atlas-of-living-scotland/objectives/)
* [x] [ Strengthening the biodiversity stakeholders network in Togo ](http://gbif.org/project/82693) returns 500 for [http://www.univ-lome.tg/](http://www.univ-lome.tg/)
* [x] [ Data standards ](http://gbif.org/article/3wusV3o9X2WO6aWU8MK2WG) returns 500 for [https://www.iubs.org](https://www.iubs.org)
* [x] [ Become a member ](http://gbif.org/article/5wXnkJm0sEIGKAIIkIcQYy) returns 500 for [programme/bid](programme/bid)
* [x] [ Data quality requirements: Occurrence-only datasets ](http://gbif.org/article/ADIoPrOOXIWSeeQOQ6K6E) returns 500 for [http://#](http://#)
* [x] [ Data user agreement ](http://gbif.org/article/12nGjIekfQIQG2gCaSAiCw) returns 500 for [privacy-policy](privacy-policy)
* [x] [ What is Darwin Core, and why does it matter? ](http://gbif.org/article/2i9tnW8sQgIka4smKq0MqO) returns 500 for [../ipt](../ipt)
* [x] [ Funders ](http://gbif.org/article/7aCgeh7TJmuCAsUskqMeAE) returns 500 for [http://www.cnre.mg](http://www.cnre.mg)
* [x] [ Funders ](http://gbif.org/article/7aCgeh7TJmuCAsUskqMeAE) returns 500 for [http://www.univ-lome.tg](http://www.univ-lome.tg)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/1817-406X](https://doaj.org/toc/1817-406X)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/2352-3409](https://doaj.org/toc/2352-3409)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/2314-8497](https://doaj.org/toc/2314-8497)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/2194-6434](https://doaj.org/toc/2194-6434)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/1866-3516](https://doaj.org/toc/1866-3516)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/2046-1402](https://doaj.org/toc/2046-1402)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/2049-6060](https://doaj.org/toc/2049-6060)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/2047-217X](https://doaj.org/toc/2047-217X)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/1314-4049](https://doaj.org/toc/1314-4049)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/1314-3301](https://doaj.org/toc/1314-3301)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/1314-2488](https://doaj.org/toc/1314-2488)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/1314-2003](https://doaj.org/toc/1314-2003)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/1932-6203](https://doaj.org/toc/1932-6203)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/2052-4463](https://doaj.org/toc/2052-4463)
* [x] [ Data papers ](http://gbif.org/article/ExNixkGbYWCsgcWE4YScw) returns 503 for [https://doaj.org/toc/1313-2970](https://doaj.org/toc/1313-2970)

**internal**

* [x] [IPT: GBIF Integrated Publishing Toolkit](https://gbif.org/tool/81278) links to [https://www.gbif.org/publishing-data/summary#datasetclasses](https://www.gbif.org/publishing-data/summary#datasetclasses)
* [x] [Internationalization of the ALA node portal](https://gbif.org/project/82202) links to [http://www.gbif.org/resource/80876](http://www.gbif.org/resource/80876)
* [x] [Mentoring Madagascar (MadBIF) - GBIF France](https://gbif.org/project/82213) links to [http://www.gbif.org/capacityenhancement/capacityprogrammes#previous](http://www.gbif.org/capacityenhancement/capacityprogrammes#previous)
* [x] [Promote GBIF in the African Portuguese speaking countries through documentation and seminars](https://gbif.org/project/82205) links to [http://gbif.org/resource/82217](http://gbif.org/resource/82217)
* [x] [Promote GBIF in the African Portuguese speaking countries through documentation and seminars](https://gbif.org/project/82205) links to [http://gbif.org/resource/82252](http://gbif.org/resource/82252)
* [x] [Promote GBIF in the African Portuguese speaking countries through documentation and seminars](https://gbif.org/project/82205) links to [http://gbif.org/resource/82571](http://gbif.org/resource/82571)
* [x] [Promote GBIF in the African Portuguese speaking countries through documentation and seminars](https://gbif.org/project/82205) links to [http://gbif.org/resource/82844](http://gbif.org/resource/82844)
* [x] [Providing access to the zoology collection of the Natural History Museum of Zimbabwe](https://gbif.org/project/82771) links to [http://www.gbif.org/programme/bid/project/africa/2015/african-ant-atlas](http://www.gbif.org/programme/bid/project/africa/2015/african-ant-atlas)
* [x] [Become a member](https://gbif.org/article/5wXnkJm0sEIGKAIIkIcQYy) links to [https://www.gbif.org/resources/80925](https://www.gbif.org/resources/80925)
* [x] [Travel Guidelines](https://gbif.org/article/6wzRmrtYn6kqsUA8UUcEuw) links to [travel@gbif.org](travel@gbif.org)

**Comment by dnoesgaard** [comment]
Thanks for identifying these. I've started working my way through them. I don't understand the Flickr 403s because they all seem fine for me.

Is generating this something we could do on a regular basis? It's really helpful. For instance, thanks to his I was able to identify two data papers journals that no longer exist.
