### ISSUE TITLE
Date formatting issue on BID dataset from Vanuatu

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#719]
**Date formatting issue on BID dataset from Vanuatu**

Great to see this dataset come in, but its '0% with dates' marker signals that the date formats are wrong, I think. There's a date range mentioned in the metadata, and in the raw/interpreted version of an individual occurrence, it looks like syntax like '12/3/85' has been used. Suggest contacting the publisher, yeah?

-----
fbitem-dataset7c518f3a-4a12-48e5-8b81-589c94cca973
User provided contact info: @kcopas
System: Safari 11.0.2 / Mac OS X 10.13.2
Referer: https://www.gbif.org/dataset/7c518f3a-4a12-48e5-8b81-589c94cca973
Window size: width 1237 - height 793
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-13T10:29:53.470Z',mode:absolute,to:'2017-12-13T10:35:53.470Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-13T10:29:53.470Z',mode:absolute,to:'2017-12-13T10:35:53.470Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by ManonGros** [comment]
The publishers have been contacted. We are waiting for their response.

**Comment by ManonGros** [comment]
98% of the occurrences have a valid date!
