### ISSUE TITLE
published dataset from the project is not displayed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#72]
**published dataset from the project is not displayed**

Not sure if it is because they didn&#39;t properly indicate BID project ID in metadata or if &#39;published dataset&#39; section is not displayed on project page, but this is one of the project that already published data on GBIF.org. see http://www.gbif.org/dataset/025769ee-df28-40de-bead-69fe1259bbad

-----
fbitem-a7af25371aa1de6037d2a4476fd4c5db6381ae7e
Reported by: mblaursen@gbif.org
System: Firefox 51.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/project/bid/africa/2015/benin-bird-data-mobilization
Window size: width 1920 - height 947
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-09T10:54:46.366Z',mode:absolute,to:'2017-02-09T11:00:46.366Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-09T10:54:46.366Z',mode:absolute,to:'2017-02-09T11:00:46.366Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
The project identifier is missing from the the api response.
http://api.gbif.org/v1/dataset/025769ee-df28-40de-bead-69fe1259bbad

**Comment by MortenHofft** [comment]
There is also an issue with https @burkeker . So even if it had been filled, it wouldn't show see https://github.com/gbif/portal16/issues/270

**Comment by ahahn-gbif** [comment]
Brief email exchange with the GBIF Node manager Benin on helpdesk, 23/01/17, with general acknowledgement of the required metadata changes. Further follow-up required, including contact with individual project leaders. Some dependency on #84 to ease this workflow and allow communication through the project lead rather than individual dataset owners, but following up with those for the time being.

**Comment by ahahn-gbif** [comment]
Dataset publisher notified, 16/02/17, waiting for response

**Comment by ahahn-gbif** [comment]
Dataset metadata fixed publisher-side, waiting for the indexer to be restarted (currently with scheduled downtime for backbone update). After that, the change needs to be verified:
- does the dataset show up on the list at https://demo.gbif.org/project/bid/africa/2015/benin-bird-data-mobilization?
- does the dataset page at https://demo.gbif.org/dataset/025769ee-df28-40de-bead-69fe1259bbad acquire a "Project" tab (currently not yet showing)

The basic functionality is confirmed for another dataset and project, here:
https://demo.gbif.org/dataset/acca8633-d38a-4cd7-a6f8-5a2d4e29832a
https://demo.gbif.org/project/bid/africa/2015/health-and-food-priorities-benin

**Comment by MortenHofft** [comment]
- does the dataset show up on the list at https://demo.gbif.org/project/bid/africa/2015/benin-bird-data-mobilization?
YES

- does the dataset page at https://demo.gbif.org/dataset/025769ee-df28-40de-bead-69fe1259bbad acquire a "Project" tab (currently not yet showing)
YES

Closing issue then
