### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#721]
**Broken link**

Clicking the "no occurrences on GBIF" button on the page https://www.gbif.org/species/7645352 gets a 404

-----
fbitem-species7645352
User provided contact info: David Attenborough
System: Chrome 62.0.3202 / Mac OS X 10.11.5
Referer: https://www.gbif.org/species/7645352
Window size: width 1680 - height 873
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-14T11:06:05.293Z',mode:absolute,to:'2017-12-14T11:12:05.293Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-14T11:06:05.293Z',mode:absolute,to:'2017-12-14T11:12:05.293Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
thanks David

**Comment by MortenHofft** [comment]
wrong redirect - has been removed
