### ISSUE TITLE
I am having problem downloading Pinus pinsater species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#722]
**I am having problem downloading Pinus pinsater species**

I am working with pinus pinaster as my assessment task but could not get data.

-----
fbitem-9dbbe3f558dc0be86eebf2b73dcc4566154b8bcf
User provided contact info: mgerega3@gmail.com
System: IE 11.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/user/download
Window size: width 1366 - height 651
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-14T11:10:32.398Z',mode:absolute,to:'2017-12-14T11:16:32.398Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-14T11:10:32.398Z',mode:absolute,to:'2017-12-14T11:16:32.398Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
> user approached by mail for further details

**Comment by MortenHofft** [comment]
Since the user committed the feedback from the https://www.gbif.org/user/download page I assume this has to do with the fact that the link to the actual download with the download button is very subtle (you have to click the doi). I have added an explicit `show` buton next to `rerun query`.
