### ISSUE TITLE
Duplicate dataset

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal-feedback#723]
Invertebrate Collection of Dept. of Ecology
https://www.gbif.org/dataset/83bc2910-34c1-11da-9a7b-b8a03c50a862
https://www.gbif.org/dataset/90837c06-ff84-47ec-b5fd-98c8b8f541f3

**Comment by ahahn-gbif** [comment]
Publisher contacted for confirmation; follow up once received.

**Comment by ahahn-gbif** [comment]
Duplicate deleted; closing
