### ISSUE TITLE
content missing?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#724]
**content missing?**

shouldn't an event like this have at least a link to the event. And possible some information about the event. or link to the event directly if this is all the content we provide?

-----
fbitem-20d0242c0147eab8d224ccc4993ee70a4bd6cacf
User provided contact info: @MortenHofft
System: Chrome 62.0.3202 / Mac OS X 10.11.6
Referer: https://www.gbif.org/event/83374/21th-meeting-of-the-subsidiary-body-on-scientific-technical-and-technological-advice-sbstta-21-and-10th-of-the-ad-hoc-open-ended-working-group-on-article-8
Window size: width 1919 - height 1076
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-14T14:29:01.729Z',mode:absolute,to:'2017-12-14T14:35:01.729Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-14T14:29:01.729Z',mode:absolute,to:'2017-12-14T14:35:01.729Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
I think this was due to a misunderstanding. The item in Contentful had more rich content, however, the links weren't published. I've updated the event page now.
