### ISSUE TITLE
Visualization of gbif taxonomy and species occurrence data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#728]
**Visualization of gbif taxonomy and species occurrence data**

Hi,

I am an ESR in BIG4 ITN project and I wanted to discuss an idea to visualize the gbif data with a different perspective. But i am not sure it's useful or not. 
The idea is to use the species dataset and visualize the taxonomy and occurrence on the map. The user can browse through the taxonomic hierarchy and visualize the taxon of interest. Also including country wise taxonomy comparison or checklist hierarchy comparison.

-----
fbitem-species2481139
User provided contact info: aashish.dyp@gmail.com
System: Chrome 59.0.3071 / Linux 0.0.0
Referer: https://www.gbif.org/species/2481139
Window size: width 1920 - height 961
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-15T10:37:03.032Z',mode:absolute,to:'2017-12-15T10:43:03.032Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-15T10:37:03.032Z',mode:absolute,to:'2017-12-15T10:43:03.032Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by rdmpage** [comment]
Personally I'd welcome different perspectives, there's lots of different ways one could imagine exploring and visualising GBIF data. I'd be happy to discuss further, I'm sure there would also be interest from the GBIF team.

**Comment by tomarashish** [comment]
Hi,

Following is the screenshot of the prototype to give a general idea

![image](https://user-images.githubusercontent.com/8381063/34038721-9dd32b7e-e18d-11e7-8fb8-310c9288d11c.png)

**Comment by rdmpage** [comment]
The big question is how these views would interact. If the user interacts with the map does the taxon view change? If the user clicks on a taxon, does its distribution appear on the map? Some things are straightforward (given a taxon display a map), others are more challenging (given a geographic view display the taxa in that area).

**Comment by tomarashish** [comment]
Yes, that is exactly what I am planning to make, so the taxonomic hierarchy and map are interactive. Given the size of data it might be difficult but using sunburst or other layouts might help the user to narrow down the search more intuitively. I am still new to gbif/biodiversity data so have to spend little time to understand it. I am thinking to use the following occurrence data to achieve the objective. Tell me if i am wrong with my approach. 

Scientific Name | Country | Coordinates | Basis Of Record | Month & Year | Dataset | Remarks | Rank | Kingdom | Phylum | Class | Order | Family | Genus | Species
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Cygnus cygnus (Linnaeus, 1758) | Norway | 58.3N, 7.7E | human observation | 2017 January | Norwegian Species Observation Service | 3 | species | Animalia | Chordata | Aves | Anseriformes | Anatidae | Cygnus | Cygnus cygnus
Cygnus olor (Gmelin, 1789) | Norway | 59.1N, 10.4E | human observation | 2017 January | Norwegian Species Observation Service | 3 | species | Animalia | Chordata | Aves | Anseriformes | Anatidae | Cygnus | Cygnus olor

**Comment by rdmpage** [comment]
@tomarashish Maybe another way to think about this is to figure out what problem you are trying to solve. What is wrong with the current GBIF interface? What things do you want to do that you can't easily do at present? I think the best interfaces help users solve problems, even better, they help users do what they want to do without getting in the way. It's tempting to get distracted by bells and whistles . Sunbursts look nice, but do they actually help?

**Comment by tomarashish** [comment]
@rdmpage  Nothing is wrong with gbif interface its perfect. I am having this idea to implement the taxonomic hierarchy with along with the map. If a user wants to select a taxon such as "Coleoptera" and visualize the occurrence on the map along with taxonomic hierarchy. It should not distract user but might help him traversing through the hierarchy and narrowing down the search. The gbif occurrence data has a hierarchy but there is no visual representation of it. The zoomable sunburst might solve the problem of visualizing a big taxonomy tree. If not sunburst maybe something like following image which is created using gbif occurrence data of Coleoptera.

![image](https://user-images.githubusercontent.com/8381063/34040996-71f57166-e196-11e7-8bda-dd5e511797a2.png)

**Comment by rdmpage** [comment]
@tomarashish The GBIF interface is nice, but it is not perfect ;) By "wrong" I guess I meant what do you want to do that isn't easy to do right now? Playing Devils' advocate, If GBIF is indeed "perfect" then why would you want to change the interface? 

Coleoptera are an interesting group to play with, given that they are huge and are likely to be challenging to handle. One limitation of GBIF data is the taxonomic hierarchy is very "shallow", which means that large groups like Coleoptera have trees with nodes with many, many descendants, which makes navigation tough. I look forward to seeing what you come up with.

**Comment by MortenHofft** [comment]
I fully support ideas, mocks etc and will gladly help with knowledge about our APIs and web development in any way I can. And if you mock something that we can all imagine in GBIF.org I'll gladly port that to the website or support that work. 

**Potential challenges to be aware of**
I agree with Rod that the main question is "what does it solve" and the main challenge is performance and data quality/quantity. The mentioned [Coleoptera](https://www.gbif.org/species/1470) have [4792 immediate children](http://api.gbif.org/v1/species/1470/children?offset=4791).

@rdmpage is btw the perfect man to discuss these ideas with.

**Upcoming changes in the backend**
We are currently looking into restructuring our data ingestion and tech choices for search. This so far look promising and could open new doors for search, maps and more. Initial map tests have far far better resolution than the crude ones we see now on https://www.gbif.org/occurrence/map . So far it looks like we will leave SOLR and move to ElasticSearch.

Let me know if there is anything I can help with.

**Comment by rdmpage** [comment]
@tomarashish Have you seen VESpeR? http://www.vesper.org.uk <http://www.vesper.org.uk/>  It is a Javascript Darwin Core viewer (and uses sunburst). Might be a useful source of ideas.

Regarding “problems”, it bugs me that we can’t easily get a list of species for a given country fro the GBIF portal. It would be great to be able to do that, and get a taxonomic classification of those species, so that we can get a sense of what the taxonomic diversity of a country (or any region) is. Is this the sort of thing you envisage your tool to be able to do?

**Comment by MortenHofft** [comment]
> List of species for a country

I know this isn't perfect, but it is the closest we have at this point. And it is a list of species for a country - with counts.
https://www.gbif.org/occurrence/species?country=AW
It cannot be downloaded and it is using speciesKey so subspecies info is lost.

**Comment by tomarashish** [comment]
Yes, I was thinking to create a taxonomic view for selected taxon for a particular country. I got this idea from a recent project I am working for. I had thought something similar to VESPER to compare taxonomy and species data of two countries but not sure it will be of much help to others or not. I am also trying to represent the images along with the hierarchical taxonomic view. In case a user wants to check images related to particular taxon he/she can traverse the taxonomy tree and click on particular taxon will result in specific images.

@rdmpage  @MortenHofft  tell me if the idea is useful or not wrt gbif interface.

**Comment by MortenHofft** [comment]
Hi @tomarashish 

**A separate Github project**
Exploring ideas further sounds wonderful. I suggest creating a Github repository and perhaps a site where everyone can use the tool. The APIs are as you know public, so there isn't anything on the GBIF.org occurrence/species search that you cannot create/explore elsewhere.

That would probably be the best way to explore your visions. That will also make it easier for others (and yourself) to get a feeling for what you envision/how it behaves/what problems it solves etc. And you would have a dedicated Github project where ideas could be exchanged.

**Tools section**
If you guys build a useful tool for exploration, then it would make sense to feature it in our tools section https://www.gbif.org/resource/search?contentType=tool . Other tools that we feature there is RGBIF a library for exploring GBIF data in R.

Look forward to seeing more! Please post a link to your repository. And let me know if you have questions about the APIs.

Thanks

**Comment by MortenHofft** [comment]
See https://github.com/tomarashish/BiodiversityBrowser

**Comment by MortenHofft** [comment]
For future reference: this issue is closely related to the previous ideas to
* add a charts tab to occurrence search https://github.com/gbif/portal16/issues/248
* implement the missing stats and visual breakdowns for datasets https://github.com/gbif/portal16/issues/138#issuecomment-322545546

**Comment by MortenHofft** [comment]
Hi @tomarashish 
You'll be happy to hear that we have started work on dataset statistics and that this work is likely to spill into the [occurrence search](https://www.gbif.org/occurrence/search). So some additional visualisations of occurrence searches is coming.

Your ideas sound like they would be better served by a separate tool (as they seem more complex), but some of it might make sense to have on the occurrence search as well.

If you believe some of it would naturally fit within an occurrence search result then feel free to let us know. Could be that you had either:
* descriptions of what you would like to do/see
* mockups with motivation descriptions
* actual implementations that we can port (we are using angular 1, Highcharts (d3.v.4 is available as well, but we try to avoid it).
