### ISSUE TITLE
Bytoopw

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#729]
**Bytoopw**

-----
fbitem-9f7a6d88273cd0d0a9cefc4960e3b0d77580a9d2

System: Chrome Mobile 63.0.3239 / Android 7.0.0
Referer: https://www.gbif.org/terms/privacy-policy
Window size: width 360 - height 234
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-15T22:24:59.258Z',mode:absolute,to:'2017-12-15T22:30:59.258Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-15T22:24:59.258Z',mode:absolute,to:'2017-12-15T22:30:59.258Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
we have had a couple of these lately
