### ISSUE TITLE
CC Node Manager when sending feedback to publisher

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#73]
**CC Node Manager when sending feedback to publisher**

A great new feature on demo.gbif.org is that record-level feedback/annotations can get sent directly to the publisher. 

During the recent NSG meeting, it was suggested the endorsing Node Manager of the publisher always be CC&#39;d in such feedback emails. The purpose is to involve Node Managers more in the curation of data sets within their realm. Another reason for doing this, is that often publishers ignore feedback messages in a language they don&#39;t recognize. Therefore by CC&#39;ing the Node Manager, this could help broker the curation. 

Note this functionality can be excluded for some nodes such as the Participant Node Managers Committee.

@ahahn-gbif @siro1

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
Reported by: @kbraak
System: Firefox 51.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/occurrence/search?dataset_key=f5de707d-eba1-4f1a-b1df-1a7fa27b1bc7
Window size: width 1337 - height 986
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-09T15:58:42.291Z',mode:absolute,to:'2017-02-09T16:04:42.291Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-09T15:58:42.291Z',mode:absolute,to:'2017-02-09T16:04:42.291Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
closed by https://github.com/gbif/portal16/commit/89146372bcc87b020281f6c0ab1e02024641c869
