### ISSUE TITLE
Dataset author link doesn't always work

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#732]
**Dataset author link doesn&#39;t always work**

Authors appearing at the top of a dataset page are linked to the contributors sections of that dataset. That works fine if the user is on the main dataset page,
 e.g. https://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e#contributors.

But if the user browses to the activity or other subpage of the dataset, the link doesn't work: https://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e/activity#contributors

That is probably because only a `#contributors` anchor is used, irrespective of the page that is loaded.

-----
fbitem-dataset83e20573-f7dd-4852-9159-21566e1e691e
User provided contact info: @peterdesmet
System: Chrome 63.0.3239 / Mac OS X 10.12.6
Referer: https://www.gbif.org/dataset/83e20573-f7dd-4852-9159-21566e1e691e/activity
Window size: width 1163 - height 636
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-18T13:54:15.086Z',mode:absolute,to:'2017-12-18T14:00:15.086Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-18T13:54:15.086Z',mode:absolute,to:'2017-12-18T14:00:15.086Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thanks peter. Should be fixed and will be in next prod build.
