### ISSUE TITLE
Provide standard links to country-level invasive species checklists

### ISSUE THREAD

**Issue by timhirsch** [gbif/portal-feedback#734]
As part of the ongoing partnership with the [IUCN Invasive Species Specialist Group](https://www.gbif.org/publisher/cdef28b1-db4e-4c58-aa71-3c5238c2d0b5) and [Convention on Biological Diversity](https://www.cbd.int/), we want to provide an easy way for the CBD to link directly from their [country profile pages](https://www.cbd.int/countries/) to the relevant national checklist published by ISSG to GBIF.org through the [Global Register of Introduced and Invasive Species (GRIIS)](http://griis.org/). To date, [20 validated national GRIIS lists have been published to GBIF as exemplars](https://www.gbif.org/dataset/search?publishing_org=cdef28b1-db4e-4c58-aa71-3c5238c2d0b5), with lists for remaining countries expected to be rolled out progressively in coming months. In addition, three sub-national lists for islands (Yemen-Soqotra, Chile-Juan Fernández Islands and Chile-Easter Island) have also been published. 

In conversation with the CBD's Information Systems Officer Frédéric Vogel (fred.vogel@cbd.int) their preferred option would be an API call that would enable them to include a link to the GRIIS national list on GBIF.org from the relevant country profile page, and exclude that link if the GRIIS list for that country is not yet available. For example, from the page for South Africa https://www.cbd.int/countries/?country=za , the 'invasive species' link from the left column would link to https://www.gbif.org/dataset/3cabcf37-db13-4dc1-9bf3-e6f3fbfbbe23 , replacing the current links that lead to the unmaintained GIASIP Gateway site.

The sub-national island lists may be excluded from this first implementation, but perhaps be included in future as additional lists from the relevant CBD country pages. Note the complication that some of these islands will have ISO 3166-1 codes in their own right, others will have regional-level 3166-2 codes, and others still will have no codes at all as sub-regional units.

Please note that implementation of these links should await the publication of a paper on the GRIIS lists in Scientific Data journal, expected mid-January 2018 - I will add a comment to this issue once it is clear to go. However, prior technical level discussion both with Fred Vogel at above email and Shyama Pagad of IUCN (s.pagad@auckland.ac.nz) may be useful to get the links set up.
@ahahn-gbif @dschigel @kcopas

**Comment by MortenHofft** [comment]
If I understand correctly this is entirely an API task.
Calling the dataset search API to get the dataset if any, and then compose the link to the dataset page from that.

Currently I don't see any good way to do that search though.

https://api.gbif.org/v1/dataset/search?publishing_org=cdef28b1-db4e-4c58-aa71-3c5238c2d0b5
Will list them all, but how to get the dataset for the relevant country? The `countryCoverage` isn't populated I think? Could `keyword` be used?

**Comment by timhirsch** [comment]
I think it is up to us to recommend to the publisher whatever change is necessary to make the country search easier - whether by keyword or countryCoverage. Eventually it is also going to be useful for us to associate these lists with their respective countries so that they could potentially be shown on country pages.

**Comment by ahahn-gbif** [comment]
TimR this morning was suggesting to explore machine tags on the datasets (under the GRIIS namespace, setting countryCode=...). Does API support machine tags? As all these datasets come from the same publisher, that might also help in filtering.

**Comment by MortenHofft** [comment]
Machine tags are not searchable at this point. That could be added to the API. But as a here and now solution keywords are our best suggestion. Keywords are not shown anywhere on the site but it is available in search. 

So if `keyword = country_ZA` are added to the South African dataset then https://api.gbif.org/v1/dataset/search?publishing_org=cdef28b1-db4e-4c58-aa71-3c5238c2d0b5&keyword=country_ZA would list that and other datasets with that keyword from that publisher

**Comment by MortenHofft** [comment]
Having Country Coverage as something searchable (and auto filled from occurrences if any) would be nice. But as I understand the service, it would be a larger piece of work.

**Comment by timhirsch** [comment]
Assuming this is something that needs to happen at the publisher side, I can contact Shyama at ISSG and request her to add those keywords to each of the national-level species lists coming to us via the IPT.  Once that is done, we can pass on the instructions to CBD for setting up the API call as described, just replacing the country code in each case. Correct? If so, job done!

**Comment by MortenHofft** [comment]
@timhirsch : Yes that should do it.

Once the keywords are there they can search as described above. Then take the result datasetKey (s) and template a link to the relevant dataset(s)

**Comment by timhirsch** [comment]
For reference I have sent the following email to Shyama Pagad. I'm going to close the issue as I think the rest is just implementation, and we can re-open if there are problems to resolve. Thanks!

Dear Shyama
 
Further to my email from Monday, we have now worked out a simple way to provide CBD with the links to the GRIIS lists as they become available on GBIF.org. It involves a small tweak from your side on the metadata for the checklists, which will also help us in future to link those lists to country pages on GBIF.
 
Our proposed solution is to provide an API call for CBD which identifies datasets published by ISSG that include a keyword for the country in question – so for example the call for the South Africa list would be https://api.gbif.org/v1/dataset/search?publishing_org=cdef28b1-db4e-4c58-aa71-3c5238c2d0b5&keyword=country_ZA . For this to work you will need to add a keyword to the metadata file on each national GRIIS dataset via the IPT, using the format country_xx , where xx is the two-letter ISO code for that country (see https://en.wikipedia.org/wiki/ISO_3166-19 ). The attached screenshot shows where you need to add the keywords, but it seems from the current lists that you have already used some keywords so it will just be a matter of adding one more in each case.
 
For now, I would suggest only adding these for the 20 national lists published as exemplars, and exclude the subnational island lists – eventually we will want to enable CBD to pick those up as well, but that will take a bit of thinking and it’s best to keep it simple for now. As you share more of the national lists, please use the same convention for including keywords.
 
I hope this is clear and straightforward – let us know if you have any questions. Once you have made those changes, we can bring in the technical team at CHM to try out the queries.
 
Cheers
 
Tim

**Comment by timhirsch** [comment]
Reopening this thread after finally hearing back from Shyama Pagad, who says (18/1/18) that she has now added keywords as requested to each of the national GRIIS checklists via the IPT. If @MortenHofft is already on leave perhaps @ahahn-gbif or @jlegind could check if these keywords are already showing up at our end and whether the API call as suggested above is functioning correctly?

**Comment by thomasstjerne** [comment]
The datasets has keywords, but none that indicates the country.
E.g. the following keywords are found one the South African checlist:

**Checklist; Inventorythematic; Alien; Invasive; Validated and Verified**

The keyword "country_ZA" should be added to the keywordlist in order for the the above API call to filter out the country properly.

For reference, the list of keywords are shown on the IPT homepage of the dataset:
http://ipt.ala.org.au/resource?r=south-africa-griis-gbif

**Comment by timhirsch** [comment]
Thanks that's strange as Shyama indicated she had added those country keywords as described, but maybe has not yet republished the checklists with those changes. I will check back with her.

**Comment by timhirsch** [comment]
Keywords now corrected and seem to comply with our request in the examples I saw. One exception is for Cuba where Shyama had an error message - details sent via Helpdesk so hopefully that can be dealt with via email. The important part of this issue has been resolved so I will close it again.

**Comment by MortenHofft** [comment]
The API has since been extended, so there is now a better way to do this:
https://github.com/gbif/registry/issues/36#issuecomment-393794019
