### ISSUE TITLE
Incomplete downloaded data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#737]
**Incomplete downloaded data**

I’m trying to download occurrence data of brazilian species (all organisms) at same time, but it is not working, according to expected. On download page preparation, the file size is 828 MB (CSV). After download, the zipped file size is only 790 MB. Furthermore, inside 790 MB file I don’t found some species that appear on GBif’s online searching.

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
User provided contact info: ebalmeidajunior@gmail.com
System: Chrome 63.0.3239 / Linux 0.0.0
Referer: https://www.gbif.org/occurrence/download?country=BR
Window size: width 1366 - height 672
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-20T13:04:06.840Z',mode:absolute,to:'2017-12-20T13:10:06.840Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-20T13:04:06.840Z',mode:absolute,to:'2017-12-20T13:10:06.840Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Download sizes are estimates so don't worry that the actual size isn't the same. This is only intended as an indicator of what you can expect (when downloading 50gb it is useful to know that this is the ballpark area).

![screen shot 2017-12-20 at 14 12 20](https://user-images.githubusercontent.com/6759267/34208774-edc43424-e58f-11e7-86cc-a31719dde4e7.png)
