### ISSUE TITLE
BID Togo dataset badly mapped to DwC

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#738]
**BID Togo dataset badly mapped to DwC**

The dwca of this dataset maps the entire species binomial to dwc:specificEpithet and does not contain a genus or scientificName column:
http://ipt-togo.gbif.fr/resource.do?r=menacees#

-----
fbitem-dataset41b51e96-b2b1-4b93-ac34-b7fd39d552c4
User provided contact info: mdoering@gbif.org
System: Chrome 63.0.3239 / Mac OS X 10.12.6
Referer: https://www.gbif.org/dataset/41b51e96-b2b1-4b93-ac34-b7fd39d552c4
Window size: width 1680 - height 863
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-20T15:08:27.145Z',mode:absolute,to:'2017-12-20T15:14:27.145Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-20T15:08:27.145Z',mode:absolute,to:'2017-12-20T15:14:27.145Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
Snippet from the first records:

```
id	taxonID	family	specificEpithet
1	1	Bombacaceae	Adansonia digitata
2	2	Sapotaceae	Afrosersalisia afzelii
```

**Comment by ManonGros** [comment]
The publishers have been contacted.
