### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#739]
**Broken links**

This page contains broken links to projects description.
eg third Regional project African Insect Atlas: Unleashing the potential of insects in conservation and sustainability research in Africa (Madagascar, Kenya, Zimbabwe, Botswana, Mozambique and South Africa)

-----
fbitem-478d20c06405806b5ad96fac5a78abb2faacb30f
User provided contact info: a.heughebaert@biodiversity.be
System: Chrome 63.0.3239 / Mac OS X 10.13.2
Referer: https://www.gbif.org/news/82784/first-bid-grants-provide-nearly-euro1-million-in-funding-to-23-african-projects
Window size: width 1300 - height 751
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-21T09:55:25.729Z',mode:absolute,to:'2017-12-21T10:01:25.729Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-21T09:55:25.729Z',mode:absolute,to:'2017-12-21T10:01:25.729Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
Link updated, large photo added (per new site reqs).
