### ISSUE TITLE
advanced term "locality" not working as expected

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#740]
**advanced term &quot;locality&quot; not working as expected**

https://www.gbif.org/occurrence/search?locality=botanic%20garden%20berlin&advanced=1

The advanced search term "locality" is not working as expected. Only exact matches seem to work. But all records from the dataset "BoBO - Botanic Garden Berlin Observations" are not found.

Use case: I want to see all observations made in the Botanic Garden in Berlin (NOT only those provided by the publisher Botanic Garden Berlin!!).

Tried: locality = "botanic garden berlin" 
locality = "botanischer garten berlin"

Both not showing expected results.

Best,
Gabi

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: g.droege@bgbm.org
System: Firefox 57.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/search?locality=botanic%20garden%20berlin&advanced=1
Window size: width 1920 - height 1063
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-21T10:10:08.066Z',mode:absolute,to:'2017-12-21T10:16:08.066Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-21T10:10:08.066Z',mode:absolute,to:'2017-12-21T10:16:08.066Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
User contacted by email:

I am afraid that you are right that the locality filter only works for exact matches. The best way to get the results you are looking for is probably to use
a location filter with a polygon like this:
https://www.gbif.org/occurrence/search?geometry=POLYGON%20((13.303585052490234%2052.45862444891168,%2013.29920768737793%2052.45444028433049,%2013.305301666259766%2052.4501511030057,%2013.311309814453125%2052.4525049737448,%2013.30667495727539%2052.456584718345674,%2013.303585052490234%2052.45862444891168))

Interestingly, this search only gives only 129 occurrences from the BoBO – Botanic Garden Berlin Observations dataset. This could indicate that the dataset has many occurrences outside the garden or that some are missing coordinates etc.

**Comment by gdadade** [comment]
Ok, thanks, I'll try. Yes, this particular dataset has worldwide occurrences, so 129 results for this one is correct :)

**Comment by timrobertson100** [comment]
Hi @gdadade - I hope you are well

You can see some with the exact match as provided by your datasets too - seemingly it is not used consistently though:

https://www.gbif.org/occurrence/search?locality=Berlin,%20Botanischer%20Garten%20Berlin&advanced=1
