### ISSUE TITLE
retrieving occurrence records on multiple IDs

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#741]
**retrieving occurrence records on multiple IDs**

I am attempting to create an occurrence download for sets of gbif species ids using rgbif. I am attempting in a batch of 1000 and also in 500 ids. But this is resulting in broken downloads. The character length for the ids is 7999 and 3999 and I understood the max was 12,000. Could you advise on whether it is possible to address this as I have 6435 ids in total. Many thanks!

-----
fbitem-9eb306293c0be4026e69ea7e735b24bc6f40a1fc
User provided contact info: @poldham
System: Chrome 63.0.3239 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/download/0000731-171219132708484
Window size: width 1551 - height 972
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-21T13:45:31.556Z',mode:absolute,to:'2017-12-21T13:51:31.556Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-21T13:45:31.556Z',mode:absolute,to:'2017-12-21T13:51:31.556Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Bypassing the Varnish cache that runs api.gbif.org, and calling the web service directly, I get an HTTP 414 Request URI Too Long for a search query.

Even though the download request is a POST request, we probably have some GET requests somewhere in the pipeline.

I can't suggest any quick workaround, other than reducing the length of the query.

**Comment by MattBlissett** [comment]
Closing in favour of #1588, which has more detail.
