### ISSUE TITLE
Dataset stats: show major taxonomic distribution for each dataset

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal-feedback#744]
From @mdoering in https://github.com/gbif/portal16/issues/138#issuecomment-259914723

> Is there room for showing the major taxonomic distribution for each dataset? At least for the backbone I would like to see some exclusive stats like this: https://github.com/mdoering/backbone-stats/blob/master/README.md

Sounds like a good idea. But I don't know how to do it. As far as I can see it isn't really anything that can be done from existing APIs. Are there?

For occurrences i guess something similar can be done from the occ api. but unclear how to do it for checklists

**Comment by mdoering** [comment]
It needs quite some API calls, so I doubt we can do it on the fly.
I used this script: https://github.com/mdoering/backbone-stats/blob/master/overview.py

**Comment by mdoering** [comment]
but if we know what we want we could preprocess things
