### ISSUE TITLE
Out of date event

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#745]
**Out of date event**

At Koala there's a reference to the Great Koala Count of South Australia. It's scheduled for 2012.

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
User provided contact info: schaar@westnet.com.au
System: Chrome Mobile 62.0.3202 / Android 7.0.0
Referer: https://www.gbif.org/search?q=Whaleshark
Window size: width 360 - height 263
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-31T03:52:16.821Z',mode:absolute,to:'2017-12-31T03:58:16.821Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-31T03:52:16.821Z',mode:absolute,to:'2017-12-31T03:58:16.821Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I'm not sure what is being refered to here. I don't see any events when searching for neither Koala or Whaleshark. Closing as fixed as I'm assuming it made sense at the time and someone else has fixed the issue in contentful
