### ISSUE TITLE
What is the ration public/private owned rhinos?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#749]
**What is the ration public/private owned rhinos?**

One of the most controversial strategies is the proposal to legalize the international trade in rhino horn. The aim of this research is to examine the influence of COP17 outcomes on the legalization debate of the international trade in rhino horn and to investigate the approaches of South African key actors towards COP 18 with respect to this debate. As part of my research and to create a better understanding of the influence of the private rhino sector, I data of the ratio private owned/ public owned rhino's. 

Therefore my request is for data of the amound of rhinos that can be found in public domains like national parks, and private owned rhinos from private game reserves of rhino farms.

-----
fbitem-465f4ad16ed342b1a2d0972aceb430078ee021ba
User provided contact info: pkbuffing@hotmail.com
System: Firefox 57.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/health
Window size: width 1366 - height 656
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-04T09:11:10.767Z',mode:absolute,to:'2018-01-04T09:17:10.767Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-04T09:11:10.767Z',mode:absolute,to:'2018-01-04T09:17:10.767Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jlegind** [comment]
Way out of scope issue.
