### ISSUE TITLE
coordinates wrongly mapped for ZSM data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#75]
**coordinates wrongly mapped for ZSM data**

It seems the coordinates for many if not all records in this ZSM dataset have been wrongly mapped. The location should be Germany and the locality gives some coordination hint, but the mapped lat lng looks rather like an elevation range.

Decimal Latitude		11.742800	Coordinate out of range
Decimal Longitude		207.000000	Coordinate out of range
Locality	Buergenlandkreis - 51,1931991577	Buergenlandkreis - 51,1931991577

-----
fbitem-occurrence883498907
Reported by: mdoering@gbif.org
System: Chrome 56.0.2924 / Mac OS X 10.12.3
Referer: https://demo.gbif.org/occurrence/883498907
Window size: width 1330 - height 815
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-10T10:12:38.883Z',mode:absolute,to:'2017-02-10T10:18:38.883Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-10T10:12:38.883Z',mode:absolute,to:'2017-02-10T10:18:38.883Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
datasetKey: f29ab192-5964-40ae-a397-fa48ffdf0661
publishingOrgKey: 0e2ae538-4332-4f41-bfee-8aa2c693d2a9

**Comment by ahahn-gbif** [comment]
Publisher contacted

**Comment by ahahn-gbif** [comment]
In process publisher-side, see hd 17/02/17

**Comment by ahahn-gbif** [comment]
Mapping reported fixed by publisher. Re-crawling.

**Comment by ahahn-gbif** [comment]
Issue appears fixed (https://demo.gbif.org/occurrence/883498907) - closing
