### ISSUE TITLE
In need ASAP of Country report 2017

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#754]
**In need ASAP of Country report 2017**

Hi, for a yearly report to node board and funders I am in need of a Country report for DanBIF covering 2017. Is it possible to get that somehow?
Best regards,
Isabel

-----
fbitem-c84165e659d5cac89bcd9497557254e01c66ebf6
User provided contact info: icalabuig@snm.ku.dk
System: Chrome 63.0.3239 / Windows 10 0.0.0
Referer: https://www.gbif.org/country/DK/summary
Window size: width 1920 - height 949
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-09T10:11:32.573Z',mode:absolute,to:'2018-01-09T10:17:32.573Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-09T10:11:32.573Z',mode:absolute,to:'2018-01-09T10:17:32.573Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by kcopas** [comment]
email correspondence to follow

**Comment by kcopas** [comment]
@DanBIF are we good on this for now? If so, I'll close the issue—just a little GitHub clean-up.

**Comment by DanBIF** [comment]
YUP ☺ thanx a lot

Isabel Calabuig
M.Sc., Ph.D. biologist, Node manager, Data curator
Natural History Museum of Denmark
DIR +45 35321103 / MOB +45 22136624
