### ISSUE TITLE
Show species count on dataset species tab?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#755]
**Show species count on dataset species tab?**

I love the species tab on occurrence results, but would it be possible to show a count for the number of species represented, whether in a dataset or a search result? 

Meaning, for example, rather than (only) showing the [total number of occurrence records for eBird](https://www.gbif.org/occurrence/species?dataset_key=4fa7b334-ce0d-4e88-aaae-2e0c138d049e), show the total number of species represented in this result. I don't think that users can currently get that calculation, and for something like eBird (among others), it would be very useful. 

It may or may not make sense to replace the occurrence count at the top—maybe the calculation could appear elsewhere in the header, or be generated through an additional interaction if it adds too much to the overhead of the page.

-----
fbitem-f55b22d402f0bf9841531850ab0f3ed8d9273208
User provided contact info: @kcopas
System: Safari 11.0.2 / Mac OS X 10.13.2
Referer: https://www.gbif.org/occurrence/species?dataset_key=4fa7b334-ce0d-4e88-aaae-2e0c138d049e
Window size: width 1309 - height 793
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-09T11:18:36.080Z',mode:absolute,to:'2018-01-09T11:24:36.080Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-09T11:18:36.080Z',mode:absolute,to:'2018-01-09T11:24:36.080Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I would love to as well. There is currently no way to get that information from the API. See https://github.com/gbif/occurrence/issues/25

Clsing as duplicate
