### ISSUE TITLE
Entries on Myrceugenia leptospermoides from Argentina wrong

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#757]
**Entries on Myrceugenia leptospermoides from Argentina wrong**

There are two entries for Myrceugenia leptospermoides reported from Argentina which is obviously wrong as the distribution is restricted to Chile ( entries from Argentina show locality Península Tumbez - which is the Península Tumbes near Concepción, Chile)

-----
fbitem-occurrence416992855
User provided contact info: s6maloer@uni-bonn.de
System: Firefox 57.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/416992855
Window size: width 1536 - height 732
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-10T11:25:25.055Z',mode:absolute,to:'2018-01-10T11:31:25.055Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-10T11:25:25.055Z',mode:absolute,to:'2018-01-10T11:31:25.055Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Publisher notified, closing.
