### ISSUE TITLE
Living Atlases website

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#758]
**Living Atlases website**

Hello,

Could you please add a link to the website : https://living-atlases.gbif.org in the page Living Atlases ? 

Thanks  :-)
Marie

-----
fbitem-2685271de3ece2ea1bc629a115e92efe03e98182
User provided contact info: @melecoq
System: Firefox 57.0.0 / Mac OS X 10.11.0
Referer: https://www.gbif.org/programme/82953/living-atlases
Window size: width 1280 - height 637
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-10T18:22:51.164Z',mode:absolute,to:'2018-01-10T18:28:51.164Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-10T18:22:51.164Z',mode:absolute,to:'2018-01-10T18:28:51.164Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
Added primaryLink: https://living-atlases.gbif.org/

@melecoq - you should see this in the tabs on the top of the page...

**Comment by melecoq** [comment]
It's perfect ! Thanks.
