### ISSUE TITLE
Wrong project lead

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#759]
**Wrong project lead**

Hello,

Project Leads of the CESP International Living Atlases workshop are GBIF France, GBIF Spain and ALA, not Canadensys. 

Thanks!
Marie

-----
fbitem-ec32236dedea40dc477738bb9da3992e5f2c3d2b
User provided contact info: @melecoq
System: Chrome 63.0.3239 / Mac OS X 10.11.6
Referer: https://www.gbif.org/project/83337/international-living-atlases-workshop
Window size: width 1275 - height 612
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-10T18:36:33.509Z',mode:absolute,to:'2018-01-10T18:42:33.509Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-10T18:36:33.509Z',mode:absolute,to:'2018-01-10T18:42:33.509Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Only one lead can be put, as far as I can see.

**Comment by melecoq** [comment]
Yes, but GBIF Spain and ALA are co-organizers and GBIF France is the lead.

**Comment by MattBlissett** [comment]
So is it OK now?

**Comment by melecoq** [comment]
Yes ! Thanks !
