### ISSUE TITLE
red dots all over the world

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#760]
**red dots all over the world**

Hi all

I was seaching for the occurrences of Tillandsia albida (Bromeliaceae). However, the map is showing that the occurrence of this species is all over the world, including Oceans. The red dots are really cool however, I am 100% sure that the real occurrence is restricted to some places in Latin America.

Let me know what to do 

All the best,

Talita Fontoura

-----
fbitem-632937989213bf4e43cb42556216fa1047383e29
User provided contact info: fontoura.talita@gmail.com
System: Firefox 57.0.0 / Mac OS X 10.13.0
Referer: https://www.gbif.org/occurrence/map?basis_of_record=PRESERVED_SPECIMEN&basis_of_record=LITERATURE
Window size: width 1238 - height 705
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-10T20:18:59.105Z',mode:absolute,to:'2018-01-10T20:24:59.105Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-10T20:18:59.105Z',mode:absolute,to:'2018-01-10T20:24:59.105Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by rdmpage** [comment]
Hi Talita,

Looks like you accidentally left out the species, try https://www.gbif.org/occurrence/map?basis_of_record=LITERATURE&basis_of_record=PRESERVED_SPECIMEN&taxon_key=2694760  See also the species view https://www.gbif.org/species/2694760 which is hopefully more like what you’re expecting (ignoring the living specimens in Sweden).


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MortenHofft** [comment]
Thanks Rod
> user informed per email
