### ISSUE TITLE
mark events GBIF S attended

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#761]
**mark events GBIF S attends**

For the open data champion work, it would be desirable to mark events attended by GBIF S staff with some icon. In the future, the same functionality could be used for marking events attended by national GBIF representatives, committee members etc. This is will sort the event from FYI, there is a conference - to GBIF (S) will be there - to no one is going yet, all yours to consider

-----
fbitem-ed6cd123cf3a3ca6ba222d90684fb8f4ea8d17bb
User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/resource/search?contentType=event
Window size: width 1922 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-11T13:04:15.246Z',mode:absolute,to:'2018-01-11T13:10:15.246Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-11T13:04:15.246Z',mode:absolute,to:'2018-01-11T13:10:15.246Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
We already have a field in the content model:

**gbifsAttendee**

It's a _short text_ type field and it's not being indexed (at least it's not in the content wrapper), but we could change it to a more controlled type and start indexing it?

What are all the conceivable options?

**Comment by dnoesgaard** [comment]
Update: It is indexed, e.g.
```
"_index": "event1520351805456",
"_type": "content",
"_id": "59921",
"_score": 0.0035273405,
"_source": {
"venue": "University of Minho (Braga - Portugal)",
"attendees": "<ul>\r\n\t<li>Lima, Nelson (Main organiser)</li>\r\n</ul>\r\n",
```

**Comment by dnoesgaard** [comment]
Just to clarify - this commit adds the text "GBIFS will attend" to the event, if the field __gbifsAttendee__ has _any_ data?

**Comment by dnoesgaard** [comment]
@MortenHofft could we please change the translation:

"gbifWillAttend": "Attended by GBIF Secretariat"

(to avoid confusion about the acronym and future/past tense)

**Comment by MortenHofft** [comment]
>Just to clarify - this commit adds the text "GBIFS will attend" to the event, if the field gbifsAttendee has any data?

yes - least that was the intention and what I understood that you wanted?

![screen shot 2018-03-13 at 14 29 41](https://user-images.githubusercontent.com/6759267/37344594-13405738-26cb-11e8-8f01-f032a8e57efe.png)

**Comment by dschigel** [comment]
Instructions I got from Tim Hirsch is to avoid GBIF S abbreviation outside GBIF S. - Note slightly longer wording from @dnoesgaard above. I agree it makes sense to display this if in the internal system if gbifsAttendee has any data - you might like to ask inputs from the admin, as I just fw meeting information
