### ISSUE TITLE
Information about 200 Tillandsia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#762]
**Information about 200 Tillandsia**

Hi

I would like to have several information about +- 200 Tillandsia species: occurrences, altitude, country, etc. 

Would GBIF have a filter to make multiple selection of species? I this way, I can download some zip files instead of one by one zip file

-----
fbitem-1f059dd0d137ccd641e791a2992ee7e29204a773
User provided contact info: fontoura.talita@gmail.com
System: Chrome 63.0.3239 / Windows 7 0.0.0
Referer: https://www.gbif.org/species/search
Window size: width 1024 - height 1189
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-11T15:02:42.303Z',mode:absolute,to:'2018-01-11T15:08:42.303Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-11T15:02:42.303Z',mode:absolute,to:'2018-01-11T15:08:42.303Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The easiest is probably to [download all 72,613 Tillandsia occurrences](https://www.gbif.org/occurrence/search?taxon_key=8279994) and then analyse them locally for what you need.

And yes you can also download [occurrences from multiple species](https://www.gbif.org/occurrence/search?taxon_key=2695588&taxon_key=2695149), but adding 200 is cumbersome.

Another option is to use our [APIs](https://www.gbif.org/developer/occurrence) if you a comfortable writing scripts.

Hope that helps

>send per mail
