### ISSUE TITLE
Large download

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#764]
**Large download**

I would like to download a large number of observations based on species scientific names trough rgbif. It seems that rgbif (or the API) can't handle large downloads easily.  What would be the best way to do a download for observation of ~5000 species.

I'm intending to use the data in a scientific publication and therefore I hope that I could have a link for the download to make citing it nice and easy. I prefer to do this trough R so that the query could be fitted with the rest of the code to enhance transparency and repeatability.

-----
fbitem-465f4ad16ed342b1a2d0972aceb430078ee021ba
User provided contact info: peter.kullberg@helsinki.fi
System: Chrome 62.0.3202 / Linux 0.0.0
Referer: https://www.gbif.org/health
Window size: width 1301 - height 653
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-15T14:44:31.171Z',mode:absolute,to:'2018-01-15T14:50:31.171Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-15T14:44:31.171Z',mode:absolute,to:'2018-01-15T14:50:31.171Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
@dnoesgaard we have had this question a lot recently. Users that want to download hundreds or thousands of species. And unfortunately we do not support such large queries. I'm not sure what the limits are, but @MattBlissett will know (or know how to find out).

Might be worth having an FAQ entry about and how to go about it? I'm not sure what the best way to go about it is. Download a higher rank and filter locally? Split into N separate downloads? Ask @jlegind ?

**Comment by dnoesgaard** [comment]
What are the limits? I just tried downloading occurrences of 500 species and that did not work:

https://www.gbif.org/occurrence/download/0000842-180131172636756

**Comment by MattBlissett** [comment]
I am closing this as a duplicate.
