### ISSUE TITLE
Some image URLs not correctly encoded

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#765]
**Some image URLs not correctly encoded**

Check the developer console.

Where the image is scaled, the / and (most importantly) the ? are URL encoded, but not for the unscaled ones, which give a 502.

-----
fbitem-species1345418
User provided contact info: @MattBlissett
System: Firefox 57.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/species/1345418
Window size: width 1642 - height 687
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-16T16:16:58.171Z',mode:absolute,to:'2018-01-16T16:22:58.171Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-16T16:16:58.171Z',mode:absolute,to:'2018-01-16T16:22:58.171Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Related to 
https://github.com/gbif/portal16/commit/eee68dfe45504bc6b61db1d5e748e2d6496248c1

The version intended for robots have the full size images that will be downloaded by the client. Those images should be scaled as well and properly include the license and attribution
