### ISSUE TITLE
Edit To Jasminum Grandiflorum Subsp. Grandiflorum.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#766]
**Edit To Jasminum Grandiflorum Subsp. Grandiflorum.**

Can you edit one of the 2 Jasminum Grandiflorum L. to Jasminum Grandiflorum Subps. Grandiflorum? Because, that's the other one like Jasminum Grandiflorum Subsp. Floribundum. There are 3 Jasminum Grandiflorums. Please reply.

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
User provided contact info: email@jasmine257.me
System: Chrome 63.0.3239 / Windows 7 0.0.0
Referer: https://www.gbif.org/search?q=jasminum%20grandiflorum%20subsp%20grandiflorum
Window size: width 1366 - height 662
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-17T09:53:59.175Z',mode:absolute,to:'2018-01-17T09:59:59.175Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-17T09:53:59.175Z',mode:absolute,to:'2018-01-17T09:59:59.175Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Backbone view of Jasminum Grandiflorum L. here https://www.gbif.org/species/3172262

**Comment by kcopas** [comment]
Not sure our idea of what we're doing aligns with this user's—does she want us to include cultivar descriptions? 

Anyway, another email arrived:
-----
From: "Electra. Harbinson." <email@jasmine257.me>
Date: Friday, 26 January 2018 at 03.53
Subject: Display It At Your Web-site.

Dear Plant Service,

Can you display this too? 

Here are some of the best cultivars:

Jasminum officinale ‘Affine’ Maroon new growth ripens to forest green. Clusters of pink tinted buds open to exceptionally large, and deliciously fragrant white flowers throughout summer.

Jasminum officinale ‘Argenteovariegatum’ An exquisite variegated vine with leaves heavily edged in cream with a sage-green interior emerge tinted pink in spring. Masses of sugar-white flowers from pink buds are produced in early summer followed by sporadic bloom throughout the rest of the growing season.

Jasminum officinale ‘Aureovariegatum’ A vigorous selection with leaves and stems irregularly splashed with gold against a deep green background; new growth emerges coral to an exciting effect.

Jasminum officinale ‘Fiona’s Sunrise’ All parts of this dramatic vine emerge chartreuse green and ripen to gold. Foliage color is fully sun-proof with the added bonus of retaining its golden hue in dense shade. ‘Fiona’sSunrise’ bears masses of pure white fragrant flowers in summer.

Jasminum officinale ‘Grandiflorum’ An especially strong cultivar with deep green, handsome foliage. Huge clusters of white flowers are powerfully fragrant—especially at night and when conditions are warm and humid. J. o. ‘Grandiflorum” should not be confused with J. grandiflorum, a tender species cultivated in frost-free areas of the Mediterranean, which is seldom seen in thePacific Northwest.

Jasminum officinale ‘Inverleith’ New foliage on this tidy vine emerges dark red before settling to a deep glossy green; deep red flower buds open to a white center with a red reverse for a wonderful bicolor effect. Bright claret red fall color before leaf drop is an added bonus.

From Electra Jasmine. Harbinson. McCallum.

**Comment by mdoering** [comment]
We can cope with cultivars in checklists, but the backbone as it is explicitly excludes them

**Comment by yroskov** [comment]
Presentation is correct in the CoL:
http://www.catalogueoflife.org/annual-checklist/2019/search/all/key/Jasminum+Grandiflorum/fossil/1/match/1
Jasminum grandiflorum L.
Jasminum grandiflorum subsp. floribundum (R.Br. ex Fresen.) P.S.Green
Jasminum grandiflorum subsp. grandiflorum

CoL does not include cultivars.

**Comment by mdoering** [comment]
... nor does the GBIF Backbone. And the 2 subspecies are there just fine, closing

**Comment by harrison-drift** [comment]
I've had some pretty odd emails from this same email address, but the domain associated bounces around and lands on a Shopify site eventually. Looks kinda spam-like to me.

Sorry to dredge up an old thread!
