### ISSUE TITLE
IndividualCount range

### ISSUE THREAD

**Issue by DimEvil** [gbif/portal-feedback#767]
Many resources I'm working with talk of a individualCount range. 
1
1-10
11-100
101-1000 ....

This gives a validation error, how should this be properly done?

**Comment by ManonGros** [comment]
The individualCount field does not allow for range but for integers, such as "1" or "100" (see the Darwin Core terms http://rs.tdwg.org/dwc/terms/index.htm#individualCount).
Perhaps using organismQuantity and organismQuantityType could be an alternative in your case. Could you give us a little bit of context to help us find a better solution?

**Comment by ManonGros** [comment]
@DimEvil Did you find an alternative to your issue?

**Comment by DimEvil** [comment]
@ManonGros  Will use organismQuantity and organismQuantityType if we have a next update.

**Comment by tucotuco** [comment]
I am curious how you will use organismQuantity and organismQuantityType for this case. The definition for the former "A number or enumeration value for the quantity of organisms" does not allow for ranges either. I would propose that this information be captured in dynamicProperties as, for example, { "individual count range":"1-10" }
