### ISSUE TITLE
That location seemss suspect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#768]
**That location seemss suspect**

-----
fbitem-occurrence1228472286

System: Chrome 63.0.3239 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/1228472286
Window size: width 1600 - height 794
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-17T13:48:13.242Z',mode:absolute,to:'2018-01-17T13:54:13.242Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-17T13:48:13.242Z',mode:absolute,to:'2018-01-17T13:54:13.242Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Publisher notified. Closing
