### ISSUE TITLE
3 Species Of False Jasmines Only.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#769]
**3 Species Of False Jasmines Only.**

Can you display Gelsemium Elegans, Gelsemium Rankinii and Gelsemium Sempervirens? Please reply.

-----
fbitem-species3682357
User provided contact info: email@jasmine257.me
System: Chrome 63.0.3239 / Windows 7 0.0.0
Referer: https://www.gbif.org/species/3682357
Window size: width 1366 - height 662
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-17T14:17:56.238Z',mode:absolute,to:'2018-01-17T14:23:56.238Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-17T14:17:56.238Z',mode:absolute,to:'2018-01-17T14:23:56.238Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
You can either see the individual species such as [Gelsemium Elegans](https://www.gbif.org/species/4020282)

or you can use [occurrence search](https://www.gbif.org/occurrence/gallery?taxon_key=4020282&taxon_key=3169515&taxon_key=7874345&taxon_key=3169513&license=CC_BY_4_0&license=CC0_1_0) to show all more species and with other filters
