### ISSUE TITLE
Wrong name for content type: "Data use"

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#77]
@kcopas @ahahn-gbif 

**Wrong name for content type: &quot;Data use&quot;**

I suspect the name should be &quot;Featured data use instead. Currently this is the name used in the current portal, see http://www.gbif.org/newsroom/uses

Otherwise, this may cause confusion with the literature content type, which often are data use instances as well.

-----
fbitem-683b60301990d1f82520ab24cf69b12e179b31a7
Reported by: @kbraak
System: Firefox 51.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/cms/search
Window size: width 1506 - height 923
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-14T13:14:53.314Z',mode:absolute,to:'2017-02-14T13:20:53.314Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-14T13:14:53.314Z',mode:absolute,to:'2017-02-14T13:20:53.314Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
I would guess this is as simple as changing it in the translation file. URLs are a bit more complicated.

**Comment by dnoesgaard** [comment]
We may consider changing this to expand the scope at a later stage, e.g. to include use in policy, etc. As this issue is now more than a year old, I'm closing it.
