### ISSUE TITLE
Sample ID format

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#771]
**Sample ID format**

Could you please help me describe how to make the format of the specimen number/unitID/catalogory number?

-----
fbitem-00ae90e992d97030ba132967cd01faaf2d95344c
User provided contact info: kairuilunimelb@163.com
System: Chrome 63.0.3239 / Windows 10 0.0.0
Referer: https://www.gbif.org/faq
Window size: width 1242 - height 602
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-18T03:40:57.796Z',mode:absolute,to:'2018-01-18T03:46:57.796Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-18T03:40:57.796Z',mode:absolute,to:'2018-01-18T03:46:57.796Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The user was contacted by email.
