### ISSUE TITLE
CSV file does not parse properly in Excel 2010

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#775]
**CSV file does not parse properly in Excel 2010**

CSV downloads do not open properly in Excel 2010.  Instead of being a single column of text (which can then easily be converted to appropriate data columns) I get up to 11 columns for a single record (though most are just 2).  Almost always a break in the middle of the scientificname authority (i.e., "Buteo jamaicensis (Gmelin, 1788)"  breaks between Gmelin and 1788), with other breaks scattered in no apparent pattern I can detect.  Parsing the first column with Excel's text-to-columns operation results in overwriting subsequent columns.  

My current work-around is to open the CSV in Notepad then copy and paste that into a blank Excel spreadsheet.  I have no idea why that then works, but it does - all records and columns are properly parsed.  The downside is that for widely distributed species the CSV files are too large for Notepad, although they should fit in Excel.

Much obliged for any solution.

John R.

-----
fbitem-1f059dd0d137ccd641e791a2992ee7e29204a773
User provided contact info: jrotenbe@umn.edu
System: Chrome 63.0.3239 / Windows 7 0.0.0
Referer: https://www.gbif.org/species/search?q=gruiformes
Window size: width 1328 - height 988
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-19T19:01:18.151Z',mode:absolute,to:'2018-01-19T19:07:18.151Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-19T19:01:18.151Z',mode:absolute,to:'2018-01-19T19:07:18.151Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email. (Another #799 case.)
