### ISSUE TITLE
Typo on scientific name

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#776]
**Typo on scientific name**

"longitarsus" to be changed to "longitarsis"

-----
fbitem-occurrence1056285248
User provided contact info: biotemail@gmail.com
System: Firefox 57.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/1056285248
Window size: width 1440 - height 768
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-20T21:26:05.129Z',mode:absolute,to:'2018-01-20T21:32:05.129Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-20T21:26:05.129Z',mode:absolute,to:'2018-01-20T21:32:05.129Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Publisher notified. Closing
