### ISSUE TITLE
Duplicate Peruvian datasets

### ISSUE THREAD

**Issue by kcopas** [gbif/portal-feedback#778]
@jlegind these look like straight-up duplicates:
https://www.gbif.org/dataset/d4b72404-5c42-49ea-ab78-9edb3c8957b6
https://www.gbif.org/dataset/833c9914-f762-11e1-a439-00145eb45e9a

Can't really tell which one is more recent—neither's been crawled successfully in years. Note that they're both listed as [candidates for adoption](https://github.com/gbif/watchdog/issues/20), but in the event, only one would need to be adopted.

Corresponding with the node manager now—will flag these and copy you in.

**Comment by jlegind** [comment]
DiGIR dataset removed.
