### ISSUE TITLE
Lionfish datasets from Barbados not connected to BID project

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#779]
**Lionfish datasets from Barbados not connected to BID project**

This dataset and [another](https://www.gbif.org/dataset/8f6d3a0d-10d2-44e3-8612-be219376c860) (at least) should be connected to the [BID project that enabled their mobilization](https://www.gbif.org/project/83254/tracking-the-red-lionfish-invasion-in-barbados). Are they simply missing an appropriate entry in the projectID field?

-----
fbitem-dataset7904180c-36c9-40ca-aed2-463e36a04df7
User provided contact info: @kcopas
System: Safari 11.0.2 / Mac OS X 10.13.2
Referer: https://www.gbif.org/dataset/7904180c-36c9-40ca-aed2-463e36a04df7
Window size: width 1237 - height 793
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-23T12:03:22.382Z',mode:absolute,to:'2018-01-23T12:09:22.382Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-23T12:03:22.382Z',mode:absolute,to:'2018-01-23T12:09:22.382Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by laurarussell** [comment]
Message has been sent yesterday to the Project Lead and VertNet explaining the issue and asking for them to add the ID and republish.

**Comment by ahahn-gbif** [comment]
Issue appears to be fixed now - the project page shows at https://www.gbif.org/dataset/7904180c-36c9-40ca-aed2-463e36a04df7, and the project page itself (https://www.gbif.org/project/83254/tracking-the-red-lionfish-invasion-in-barbados) links to 2 datasets. Closing.
