### ISSUE TITLE
Not sure where or whether my data downloaded.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#780]
**Not sure where or whether my data downloaded.**

Hi, I'm new to using open source data and GBIF. I am trying to download data from  Insecta of costa rica (inbio). My gif page says I have downloaded it, but I can't find it on my computer. Did it download it to this website only? Do I export it from the website to my computer? Thanks in advance.

-----
fbitem-f3c56a621485b1d92337e1cce970e6fd597f3c72
User provided contact info: christyrauch@yahoo.com
System: Safari 11.0.2 / Mac OS X 10.12.6
Referer: https://www.gbif.org/occurrence/download/0011989-171219132708484
Window size: width 1857 - height 996
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-23T18:16:12.328Z',mode:absolute,to:'2018-01-23T18:22:12.328Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-23T18:16:12.328Z',mode:absolute,to:'2018-01-23T18:22:12.328Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.
