### ISSUE TITLE
Identification of the species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#782]
**Identification of the species**

Which method was used to identify the specimen?

-----
fbitem-occurrence865740525
User provided contact info: thierry.bohnenstengel@unine.ch
System: Firefox 57.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/865740525
Window size: width 1920 - height 968
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-24T10:21:14.394Z',mode:absolute,to:'2018-01-24T10:27:14.394Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-24T10:21:14.394Z',mode:absolute,to:'2018-01-24T10:27:14.394Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Try to contact the dataset contacts as linked:
https://www.gbif.org/dataset/5a659248-1f70-11e3-b2c5-00145eb45e9a#contributors

hopefully they can help you.
thanks

>contacted per email
