### ISSUE TITLE
cannot view old portal version of the stats

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#783]
**cannot view old portal version of the stats**

In spite of the invitation and link, it redirects to the new portal only

-----
fbitem-dataset82cb293c-f762-11e1-a439-00145eb45e9a
User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/dataset/82cb293c-f762-11e1-a439-00145eb45e9a/stats
Window size: width 1920 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-24T12:26:43.742Z',mode:absolute,to:'2018-01-24T12:32:43.742Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-24T12:26:43.742Z',mode:absolute,to:'2018-01-24T12:32:43.742Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
See https://www.gbif-uat.org/dataset/82cb293c-f762-11e1-a439-00145eb45e9a/stats for the new version, though the data on UAT is months old now.

Link to the old version sent on Skype, it is intentionally no longer public.
