### ISSUE TITLE
Cannot open "previous version" link for stats

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#784]
**Cannot open &quot;previous version&quot; link for stats**

The "view previous version here" link points at www-old.gbif.org, which re-routes to gbif.org, so that the link ends up back at the current dataset page at gbif.org

-----
fbitem-dataset74f92761-3a24-4d85-9bfb-00b1fee0119d
User provided contact info: @ahahn-gbif
System: Firefox 57.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/dataset/74f92761-3a24-4d85-9bfb-00b1fee0119d/stats
Window size: width 1148 - height 784
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-24T15:02:23.178Z',mode:absolute,to:'2018-01-24T15:08:23.178Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-24T15:02:23.178Z',mode:absolute,to:'2018-01-24T15:08:23.178Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Duplicates https://github.com/gbif/portal-feedback/issues/783.
