### ISSUE TITLE
Show better download file size etc

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#785]
**Show better download file size etc**

> file: 152 MB CSV

It's actually a 152MB ZIP file containing a 1546MB CSV.

Knowing this would require some backend changes to the registry and probably the occurrence downloader.

-----
fbitem-f3c56a621485b1d92337e1cce970e6fd597f3c72
User provided contact info: @MattBlissett
System: Firefox 57.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/occurrence/download/0011989-171219132708484
Window size: width 1651 - height 1176
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-24T15:04:20.449Z',mode:absolute,to:'2018-01-24T15:10:20.449Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-24T15:04:20.449Z',mode:absolute,to:'2018-01-24T15:10:20.449Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Fixed, I think, in https://github.com/gbif/portal16/commit/c66d86637d605ab4ded1a2ef451fba5c2c9b11fa
