### ISSUE TITLE
the data is being cited as 100% georeferenced with coordinates but when being downloaded the coordinates and many other field contents is missing in the CSV file, Can you please kindly advise?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#787]
**the data is being cited as 100% georeferenced with coordinates but when being downloaded the coordinates and many other field contents is missing in the CSV file, Can you please kindly advise?**

the data is being cited as 100% georeferenced with coordinates but when being downloaded the coordinates and many other field contents is missing in the CSV file, Can you please kindly advise?

-----
fbitem-occurrence1292005967
User provided contact info: alqamy@gmail.com
System: Chrome 63.0.3239 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/1292005967
Window size: width 1686 - height 712
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-24T20:11:54.209Z',mode:absolute,to:'2018-01-24T20:17:54.209Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-24T20:11:54.209Z',mode:absolute,to:'2018-01-24T20:17:54.209Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied via helpdesk email.
