### ISSUE TITLE
Waiting for registration confirmation

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#788]
**Waiting for registration confirmation**

I have registered yesterday. I have send my e-mail, aquario.svc.educativo@marinha.pt, my user name as well as the password. I received a message informing me that I woul receive an e-mail confirming my registration. Untill know I have not received any mail and I can get to login. Can you please check what is happening? Thank

-----
fbitem-dataset6005f3b4-da6a-4d88-ac92-81f2e950eb24
User provided contact info: aquario.svc.educativo@marinha.pt
System: IE 11.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/dataset/6005f3b4-da6a-4d88-ac92-81f2e950eb24
Window size: width 1680 - height 955
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-25T10:36:54.321Z',mode:absolute,to:'2018-01-25T10:42:54.321Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-25T10:36:54.321Z',mode:absolute,to:'2018-01-25T10:42:54.321Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.
