### ISSUE TITLE
Location seems suspect

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#790]
**Location seems suspect**

There is a record for Dryas octopetala that shows on the map in the ocean between Tasmania and New Zealand with the coordinates -43.068888 Latitude and 158.203125 Longitude.  However the Verbatim Locality is listed as Provincia di Belluno, Italia.  Additionally, this record is suspect because it is very far outside the accepted range for Dryas octopetala.

-----
fbitem-occurrence1572366926
User provided contact info: @jameshansen91
System: Chrome 63.0.3239 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/1572366926
Window size: width 1600 - height 769
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-26T23:38:26.452Z',mode:absolute,to:'2018-01-26T23:44:26.452Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-26T23:38:26.452Z',mode:absolute,to:'2018-01-26T23:44:26.452Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.

@dnoesgaard, could we get an FAQ item on how to open the SIMPLE_CSV downloads in Excel? It's a common question, and I imagine more people give up trying to use GBIF data without telling us. I would add the link to this to the download email (#789).

**Comment by MattBlissett** [comment]
Marked as suspicious location (by me) in iNaturalist.
