### ISSUE TITLE
Sir/Madam.. Could i get the reference of the publication which indicates its record in Egypt

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#791]
**Sir/Madam.. Could i get the reference of the publication which indicates its record in Egypt**

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: anooj227@gmail.com
System: Chrome 49.0.2623 / Windows XP 0.0.0
Referer: https://www.gbif.org/occurrence/search?taxon_key=5070691
Window size: width 1024 - height 677
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-30T05:54:33.044Z',mode:absolute,to:'2018-01-30T06:00:33.044Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-30T05:54:33.044Z',mode:absolute,to:'2018-01-30T06:00:33.044Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email.
