### ISSUE TITLE
Individual endorsed as publisher?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#792]
**Individual endorsed as publisher?**

This new publisher looks misaligned with our endorsement model, in that, by all appearances, he's an individual researcher. Clicking through the link that's provided, it would seem much more appropriate to have the School of Life Sciences or Lanzhou University.

The description is what really tipped this—it reads like a CV summary.

-----
fbitem-publisher0cb06233-9a34-40ca-a4d1-3f882202373f
User provided contact info: @kcopas
System: Safari 11.0.2 / Mac OS X 10.13.2
Referer: https://www.gbif.org/publisher/0cb06233-9a34-40ca-a4d1-3f882202373f
Window size: width 1245 - height 793
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-30T06:10:46.280Z',mode:absolute,to:'2018-01-30T06:16:46.280Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-30T06:10:46.280Z',mode:absolute,to:'2018-01-30T06:16:46.280Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
@jlegind This entry indeed needs to be removed. It might be worth contacting them explaining that they need to find an institutional home. Could you get communication out?

**Comment by ManonGros** [comment]
The publisher's page no longer exists to I assume the issue has been solved.
