### ISSUE TITLE
Display of image thumbnail for checklists

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#793]
**Display of image thumbnail for checklists**

Images provided for checklists seems to be cut to a 4:3 format. Images in occurrence datasets are seemingly not cut. Is it possible to maintain aspect ratio also for images in checklists?

Example
https://www.gbif.org/species/137679337

https://api.gbif.org/v1/image/unsafe/200x150/http%3A%2F%2Fradiolaria.org%2Fimg%2Fimg96.jpg

And a link to the original source image might also be useful?
http://radiolaria.org/img/img96.jpg

-----
fbitem-species137679337
User provided contact info: @https://github.com/dagendresen
System: Chrome 63.0.3239 / Mac OS X 10.13.2
Referer: https://www.gbif.org/species/137679337
Window size: width 1205 - height 803
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-30T08:50:39.938Z',mode:absolute,to:'2018-01-30T08:56:39.938Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-30T08:50:39.938Z',mode:absolute,to:'2018-01-30T08:56:39.938Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
Hi @dagendresen
Thanks for your feedback. 
You are right, but It will be hard to fit arbitrary formatted images into the current page design.
However, if an image is clicked, it will open in an overlay. Currently, this is also fitted into 4:3 format (in the overlay,) but I will change this to show the image in the originnal format.

Link to the original image can be found on the verbatim tab.
