### ISSUE TITLE
GB21 video links gone bad

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#794]
**GB21 video links gone bad**

Looks like the migration has rotted the links to videos from the GB21 public session. Noting it here so as not to lose the plot.

I have not looked at the MD source, nor do I know whether or to what extent we've already configured video embedding on the new site, but the videos can all be found in [this Vimeo collection](https://vimeo.com/album/3056861).

-----
fbitem-05240c6b2f864d2ff643dd947d9b7bf337cdfbd3
User provided contact info: @kcopas
System: Safari 11.0.2 / Mac OS X 10.13.2
Referer: https://www.gbif.org/news/82361/watch-the-gbif-public-symposium-2014
Window size: width 1245 - height 793
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-30T09:17:45.523Z',mode:absolute,to:'2018-01-30T09:23:45.523Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-30T09:17:45.523Z',mode:absolute,to:'2018-01-30T09:23:45.523Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
@dnoesgaard, did you set up access to the old website?

I don't know about embedding the Vimeo videos into the new one, but the PDF links will be easy to fix.  

https://www.gbif.org/sites/default/files/gbif_resource/resource-81918/DHobern-GBIF-Today-and-Tomorrow.pdf is the first one.

**Comment by dnoesgaard** [comment]
Yeah, will take a look. Shouldn't be hard to fix.

**Comment by dnoesgaard** [comment]
The Vimeo embeds have been fixed. You embed like this

```@[vimeo](#id)```

Slightly confused about the pdf links. Sorry it's been a while since we ported the site. Is the link you mention to a file in Contentful or is a redirect?

**Comment by MattBlissett** [comment]
It's a boring, old-fashioned file on a webserver. The old static files from Drupal were moved to this location.

**Comment by MattBlissett** [comment]
For each one, you'll need to swap www → www-old, which is then a redirect to a resource in Drupal, and then follow the PDF download link, and change the bit before gbif_resource to match. And remove ?download=1.

**Comment by dnoesgaard** [comment]
Just for my own record

```
> GET /resources/10360 HTTP/1.1 -> GET /resource/81918 HTTP/1.1
> GET /resources/10458 HTTP/1.1 -> GET /resource/80939 HTTP/1.1
> GET /resources/10463 HTTP/1.1 -> GET /resource/80943 HTTP/1.1
> GET /resources/10455 HTTP/1.1 -> GET /resource/80937 HTTP/1.1
> GET /resources/10450 HTTP/1.1 -> GET /resource/80934 HTTP/1.1
> GET /resources/10460 HTTP/1.1 -> GET /resource/80942 HTTP/1.1
> GET /resources/10452 HTTP/1.1 -> GET /resource/80935 HTTP/1.1
> GET /resources/10464 HTTP/1.1 -> GET /resource/80944 HTTP/1.1
> GET /resources/10462 HTTP/1.1 -> GET /resource/80941 HTTP/1.1
> GET /resources/10448 HTTP/1.1 -> GET /resource/80932 HTTP/1.1
> GET /resources/10454 HTTP/1.1 -> GET /resource/80936 HTTP/1.1
> GET /resources/10449 HTTP/1.1 -> GET /resource/80933 HTTP/1.1
> GET /resources/10456 HTTP/1.1 -> GET /resource/80938 HTTP/1.1
> GET /resources/10459 HTTP/1.1 -> GET /resource/80940 HTTP/1.1
```

**Comment by MattBlissett** [comment]
I fixed the PDF URLs (wrote a little script to update the URLs according to the new pattern).

Please confirm it's OK and close.

**Comment by dnoesgaard** [comment]
Thanks Matt! Looks good!
