### ISSUE TITLE
Publisher registration form chokes on invalid data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#795]
**Publisher registration form chokes on invalid data**

Submitting an invalid homepage URL (e.g. someone tried by putting both their homepages in the box) gives a "For some reason your submission failed" error, but nothing more.

The log has this: `{"name":"portal16","hostname":"uatnode-vh.gbif.org","pid":1104,"level":50,"msg":"Become a publisher form submission failure: Can not construct instance of java.net.URI from String value 'http://herbaria.plants.ox.ac.uk/bol/mau; http://herbaria.plants.ox.ac.uk/bol/swioorchids': not a valid textual representation\n at [Source: HttpInputOverHTTP@2be8942d[c=2041,s=STREAM]; line: 1, column: 958] (through reference chain: org.gbif.api.model.registry.Organization[\"homepage\"])","time":"2018-01-30T10:50:24.677Z","v":0}`

`<input type="url">` ought to be a nice solution, but it's so lax as to be almost useless.

It would also be useful if the "please contact us" just included the current date and time (in a timezone I can understand), so I can find someone's error in the log.

-----
fbitem-ab3ccb02d409d7c1b6652ceee60e3937ce068b3e
User provided contact info: @MattBlissett
System: Firefox 57.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/become-a-publisher
Window size: width 1684 - height 1119
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-30T10:57:50.872Z',mode:absolute,to:'2018-01-30T11:03:50.872Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-30T10:57:50.872Z',mode:absolute,to:'2018-01-30T11:03:50.872Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Duplicated by https://github.com/gbif/portal-feedback/issues/797
