### ISSUE TITLE
The health popup is extremely prominent on mobile

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#798]
**The health popup is extremely prominent on mobile**

Do we want this to be so prominent? With a small outage, it takes over the whole screen on a mobile browser.

-----
fbitem-465f4ad16ed342b1a2d0972aceb430078ee021ba
User provided contact info: @MattBlissett
System: Firefox 57.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/health
Window size: width 1684 - height 1119
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-30T17:21:32.009Z',mode:absolute,to:'2018-01-30T17:27:32.009Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-30T17:21:32.009Z',mode:absolute,to:'2018-01-30T17:27:32.009Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
It is a bit on the large size, but if we do a popup it seems ok that it is prominent doesn't it. I mean in the case of a partial outage. You need to close it anyhow to continue. It essentially just use the same styling as the feedback popup.

**Comment by MortenHofft** [comment]
The popup only appears if there is a critical outage. That should happen very rarely or else something is critically wrong with the APIs. When that happens large parts of the site will not function. So far the critical popup has reflected real issues and the site has been dysfunctional. It seems reasonable to display that information extremely prominent. Once the popup is closed it will not show again within that session.
