### ISSUE TITLE
FAQ item needed for opening "CSV" downloads in Excel.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#799]
**Downloading Occurrence Records**

I downloaded the tab delimited CSV file for a set of Dryas octopetala L. records and opened it in Excel but the result was not easily comprehensible and did not seem to have separate columns for fields such as scientific name or coordinates.  I mostly just need the coordinates to be able to use them in a MaxEnt model.  What is the best way to download these?  Was there some error when I did it the first time?

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: @jameshansen91
System: Chrome 63.0.3239 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/search?offset=280&basis_of_record=OBSERVATION&basis_of_record=HUMAN_OBSERVATION&basis_of_record=PRESERVED_SPECIMEN&has_coordinate=true&has_geospatial_issue=false&taxon_key=4889932
Window size: width 1600 - height 720
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-31T04:05:27.502Z',mode:absolute,to:'2018-01-31T04:11:27.502Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-31T04:05:27.502Z',mode:absolute,to:'2018-01-31T04:11:27.502Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by thomasstjerne** [comment]
Hi @jameshansen91
The downoladed data is tab separated. In most excel versions you need to 

1. Open a blank spread sheet
2. Open the "data" menu
3. Choose "get external data" --> "Import text file"

Now you can specify that the data is seperated by tab.

Hope this helps.
/Thomas Stjernegaard

**Comment by MattBlissett** [comment]
Replied by email (that is not a Github user).

@dnoesgaard, could we get an FAQ item on how to open the SIMPLE_CSV downloads in Excel? It's a common question, and I imagine more people give up trying to use GBIF data without telling us. I would add the link to this to the download email (#789).

**Comment by dnoesgaard** [comment]
I've created a FAQ entry now:

https://www.gbif.org/faq?question=opening-gbif-csv-in-excel

Let me know if anything is unclear.

**Comment by MattBlissett** [comment]
Looks good, I've added it as a link in the download email.
