### ISSUE TITLE
Plazi datasets have no license

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#8]
**Plazi datasets have no license**

Some Plazi datasets have no license field but should all have one.

-----
fbitem-datasetfbb80520-f927-4ce0-a7a8-fda964bc33e5
Reported by: @timrobertson100
System: Chrome 54.0.2840 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/dataset/fbb80520-f927-4ce0-a7a8-fda964bc33e5
Window size: width 1584 - height 799

**Comment by cgendreau** [comment]
Datasets representing checklist + occurrences were skipped by the first script but all Plazi should have been updated (in theory).

**Comment by timrobertson100** [comment]
FYI @ManonGros - that link only covers datasets having occurrence records. 
[A dataset search for Plazi](https://www.gbif.org/dataset/search?publishing_org=7ce8aef0-9e92-11dc-8738-b8a03c50a862) and then looking at the `License` facet is a more definitive approach.

It also confirms this is now fixed. Thanks for checking!
