### ISSUE TITLE
Location v Locality

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#800]
**Location v Locality**

Can you explain the difference between the two labels?  The record at this site is confusing to me.
https://www.gbif.org/occurrence/1095981802

I presume that the Locality is where the sample was taken from - in this case Mt Koromba, Mba, Viti Levu Fiji.

so not sure what the Location means?  My understanding is that the species is endemic to Fiji - so the connection with Cook Islands is spurious?  It seems weird, to me, to showcase the Location in the summary of all specimens, if the location is not where the specimen comes from.

I presume that the location of the specimen is Sweden?  Or is that where the confusion occurs?

-----
fbitem-occurrence1095981802
User provided contact info: mark.obrien@birdlife.org
System: Chrome 63.0.3239 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/1095981802
Window size: width 1600 - height 809
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-31T05:20:23.191Z',mode:absolute,to:'2018-01-31T05:26:23.191Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-31T05:20:23.191Z',mode:absolute,to:'2018-01-31T05:26:23.191Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by kcopas** [comment]
Good find, Mark! It looks like the country code is the source of confusion. It shows Cook Islands, rather than Fiji, even though that's (presumably) what's on the specimen label.

**Comment by thomasstjerne** [comment]
If you toggle to se the verbatim data:
![toggle_verbatim](https://user-images.githubusercontent.com/1666484/35618048-09261d94-067a-11e8-972e-a22cb7ca6f5c.png)
You will see how the original data came in from the publisher, and that the Location is Country or Area, whereas locality is a more accurate description of the place. So it seems there is an error in the data from the publisher:
![cook_islands](https://user-images.githubusercontent.com/1666484/35618233-9ee4682c-067a-11e8-8d2a-9488b1e4b837.png)

**Comment by thomasstjerne** [comment]
User contacted by email
