### ISSUE TITLE
Add HostingOrg as query parameter to the occurrence search

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#804]
**Add HostingOrg as query parameter to the occurrence search**

Is it possible to add `HostingOrg` (alternative spelling `hosting_org`) as a query parameter to the occurrence search? It is available for the datasets search. `PublishingOrg` is already available for both.

No hard core requirement, but I was interested to see how many occ. we host at INBO and noticed that parameter is only available for the dataset search.

-----
fbitem-b1018fb447ec8b1aa84ee420b36825314783d5a9
User provided contact info: @peterdesmet
System: Chrome 63.0.3239 / Mac OS X 10.13.2
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1342 - height 712
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T10:26:01.523Z',mode:absolute,to:'2018-02-01T10:32:01.523Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T10:26:01.523Z',mode:absolute,to:'2018-02-01T10:32:01.523Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It would be great to have and would allow hosting organisations to gather metrics about the data they host.
Right now we have a few open issues about increasing the visibility of hosting organisations (https://github.com/gbif/portal-feedback/issues/471, https://github.com/gbif/portal-feedback/issues/1383, https://github.com/gbif/portal-feedback/issues/1385, https://github.com/gbif/portal-feedback/issues/1382). Plus we also get asked in our email exchanges as well (just today we got an other one).

Filtering occurrences by hosting organisations would be a great way to start! Is this something we could do?

**Comment by ahahn-gbif** [comment]
A related helpdesk request from 26/12/10, in short: "I was under the impression that OBIS, FishNet 2 and iDigBio supplied georeferenced species location record to GBIF. However, I have been reviewing records for a whole bunch of eastern Pacific fishes and only see FishBase listed as an aggregator source of such records (...)".

OBIS records can be identified through the network page (if you know how to find it), but iDigBio as one of the most active hosts is basically invisible at the record level, without an occurrence filter for the hosting institution, the host not mentioned in downloads, and the publisher page only linking to a list of datasets, but no occurrence filter.

To provide recognition and visibility to data hosts is an important motivation for this kind of service, and the requested API change would be a critical first step.

**Comment by timrobertson100** [comment]
Now live. See Data Hosted by GBIF France as an example https://www.gbif.org/occurrence/map?advanced=1&hosting_organization_key=5d5e5d82-076c-4e9a-b5b0-c88d1b691a6a
