### ISSUE TITLE
How to upload data to GBIF

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#805]
**How to upload data to GBIF**

On behalf of the Tropical Plant Exploration Group (TroPEG) Cameroon we are trying to published data to the GBIF portal but we are experiencing some difficulties at the level of how to go about it on the GBIF website.  
Thanks

-----
fbitem-0059f96b33a12ae38a9a2449c0865b3a3cdfe76c
User provided contact info: mnsainge@tropegcam.org
System: Chrome 57.21.2987 / Windows 7 0.0.0
Referer: https://www.gbif.org/dataset/search?type=METADATA&publishing_org=50a4c4c2-3b12-4515-b4b5-ee39ef7fba8c
Window size: width 1366 - height 662
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T12:14:03.875Z',mode:absolute,to:'2018-02-01T12:20:03.875Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T12:14:03.875Z',mode:absolute,to:'2018-02-01T12:20:03.875Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
I'm guessing this is BID.
