### ISSUE TITLE
Showing affiliation for contributors on dataset pages

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#806]
**Showing affiliation for contributors on dataset pages**

Dear GBIF-helpdesk staff,

One of our data contributors notified us that his institutional affiliation was not shown on the dataset page at the GBIF portal while this information is provided at the side of our IPT. E. g. https://www.gbif.org/dataset/ce0f1750-ad92-46b7-b8c7-59033460de43 vs. http://data.freshwaterbiodiversity.eu/ipt/resource?r=bf_cf8 

Is there something we can do on the publishing end to have the affiliation (in this case "Museum of Natural History, University of Wroclaw") show up and/or could you consider displaying this field on the portal.

We consider this institutional visibility for our data providers very important as the data we publish through BioFresh is generally coming from different institutes.

Thanks in advance for your recommendations and reply.

With best regards,
Aaike De Wever

-----
fbitem-datasetce0f1750-ad92-46b7-b8c7-59033460de43
User provided contact info: aaike.dewever@naturalsciences.be
System: Safari 11.0.3 / Mac OS X 10.13.3
Referer: https://www.gbif.org/dataset/ce0f1750-ad92-46b7-b8c7-59033460de43
Window size: width 2018 - height 1266
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T14:39:53.386Z',mode:absolute,to:'2018-02-01T14:45:53.386Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T14:39:53.386Z',mode:absolute,to:'2018-02-01T14:45:53.386Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Good point. that is an oversight and has been added. it will be available in next release.
thanks
