### ISSUE TITLE
Activity for checklist datasets

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#808]
**Activity for checklist datasets**

Is it possible to view the number of download events of a checklist dataset (as is possible with occurence datasets)?

Best regards,
Sander (Naturalis Biodiversity Center)

-----
fbitem-dataset4dd32523-a3a3-43b7-84df-4cda02f15cf7
User provided contact info: sander.pieterse@naturalis.nl
System: Chrome 63.0.3239 / Windows 7 0.0.0
Referer: https://www.gbif.org/dataset/4dd32523-a3a3-43b7-84df-4cda02f15cf7/metrics
Window size: width 1920 - height 949
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T14:44:33.213Z',mode:absolute,to:'2018-02-01T14:50:33.213Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T14:44:33.213Z',mode:absolute,to:'2018-02-01T14:50:33.213Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
We link directly to the source for checklist downloads, and we don't log whether people click the link.

This dataset's link is to api.biodiversitydata.nl, so Naturalis might have logs for that server.

**Comment by MortenHofft** [comment]
> send to user per mail
