### ISSUE TITLE
Very minor issues in map filtering pane

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#81]
**Very minor issues in map filtering pane**

When selecting the year range it says e.g. &quot;2year&quot; and not &quot;2 years&quot;

The filter for hexagons says the range is 0.0 -&gt; 1.0 but lets you put in e.g. 10000.

-----
fbitem-f0b1d8e8c6811b830ef2f932fb5cf1be7ba9cf0a
Reported by: timrobertson100@gmail.com
System: Chrome 56.0.2924 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/tools/species-population
Window size: width 1660 - height 910
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-15T09:40:53.836Z',mode:absolute,to:'2017-02-15T09:46:53.836Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-15T09:40:53.836Z',mode:absolute,to:'2017-02-15T09:46:53.836Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Thanks - space is there now and validation (highlighted in red) if illegal values
