### ISSUE TITLE
Occurrence dataset has type Metadata

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#810]
**Occurrence dataset has type Metadata**

I'm not sure what's going on here — the type is metadata, but there are occurrences.

-----
fbitem-dataset14f3151a-e95d-493c-a40d-d9938ef62954
User provided contact info: @MattBlissett
System: Firefox 57.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/dataset/14f3151a-e95d-493c-a40d-d9938ef62954
Window size: width 2161 - height 1192
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T17:13:43.620Z',mode:absolute,to:'2018-02-01T17:19:43.620Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T17:13:43.620Z',mode:absolute,to:'2018-02-01T17:19:43.620Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MortenHofft** [comment]
From the website view this is the reason that we increasingly ignore dataset type and look at the available data instead. Type is often not very useful when judging what to display.

**Comment by ahahn-gbif** [comment]
When a dataset initially gets published metadata-only and adds data later, the type is not routinely changed.

**Comment by ahahn-gbif** [comment]
At source (http://ipt.calacademy.org:8080/ipt/), the type is given as occurrence. The only registered endpoint at the registry end, however, is the EML. Two questions relating:
1) Do we ever revisit this part of the metadata - is updating the type of the dataset ever considered during indexing / metadata synchronisation?
2) How come that with an EML endpoint, we still managed to harvest the occurrences?
Ingestions report as successful at https://www.gbif.org/dataset/14f3151a-e95d-493c-a40d-d9938ef62954, but only touch the metadata. The occurrence update happened in Dec 2013.

**Comment by MattBlissett** [comment]
1. I don't think so.

2. Probably we had an occurrence endpoint in December 2013, but it has been removed somehow -- an IPT bug, a manual error, etc. "Successful" for a metadata dataset means the EML was retrieved and parsed successfully.

**Comment by ahahn-gbif** [comment]
1. should we?
2. checking with the publisher whether the removal was intentional and records should be deleted, or endpoint re-registration is the next step

**Comment by ahahn-gbif** [comment]
Reverted to occurrence dataset status with DwC-A endpoint after confirmation from the publisher (helpdesk, 22.5.18). Reharvesting presently reports "not modified", which is consistent with the record numbers in the index and at source. Update at source under revision by the publisher. Closing.
