### ISSUE TITLE
Micropeplus nelsoni

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#811]
**Micropeplus nelsoni**

Only one record which is fossils from the Paleobiology Database. Extant species described here with location

https://www.jstor.org/stable/4008750?seq=3#page_scan_tab_contents
from same state. 

Is there a way as a researcher to add observations from the literature to the GBIF?

-----
fbitem-7c2356766cb3e5969cb9c374354413624320d1cc

System: Firefox 58.0.0 / Mac OS X 10.12.0
Referer: https://www.gbif.org/citizen-science
Window size: width 1436 - height 778
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T21:45:02.318Z',mode:absolute,to:'2018-02-01T21:51:02.318Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-01T21:45:02.318Z',mode:absolute,to:'2018-02-01T21:51:02.318Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
No contact details. Might someone think that because they're logged in, we know the feedback is from them?

**Comment by mdoering** [comment]
Might well be, I did think so in the beginning. Would it be hard to add their account name at least?

**Comment by MattBlissett** [comment]
If so, it should be a pre-filled text box which can be edited, so they know it's about to be public.

**Comment by MortenHofft** [comment]
it does so for github usernames, but not email as i considered that to sensitive. would you consider it okay to display the username? I guess so, we do so in the APIs anyhow
