### ISSUE TITLE
no scale at histogram, X axis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#813]
**no scale at histogram, X axis**

I propose we have the scale and unites back to the X axis, if possible

-----
fbitem-443cc5af8c0b3ef651d332fa2824ee5e830a4158
User provided contact info: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://www.gbif.org/news/4a5wk5LoFykeeOEuqygm6W/a-look-back-at-gbif-in-2017
Window size: width 1920 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-02T15:29:19.683Z',mode:absolute,to:'2018-02-02T15:35:19.683Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-02T15:29:19.683Z',mode:absolute,to:'2018-02-02T15:35:19.683Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by dnoesgaard** [comment]
This better, @dschigel?

![chart 8](https://user-images.githubusercontent.com/21358085/37093876-3bffaf16-2211-11e8-87f7-2052ff51fce9.png)

**Comment by dnoesgaard** [comment]
Sorry, didn't get a notification of your "thumbs-up" reaction ;) 

Fixed.
