### ISSUE TITLE
Interpreting Dataset Keys

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#814]
**Interpreting Dataset Keys**

Is there somewhere I can easily interpret dataset keys so I can convert them into the actual name of the dataset?  I've downloaded a Tab delimited CSV containing occurrence records and I'd like to be able to convert the "datasetkey" column from the keys into the actual names of the dataset.  I've installed the rgbif package and have been using the gbif_citation command to generate the name of the dataset but I was wondering if there was an easier way.

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
User provided contact info: @jameshansen91
System: Chrome 63.0.3239 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/download?has_coordinate=true&has_geospatial_issue=false&taxon_key=4889932
Window size: width 1600 - height 769
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-02T16:39:47.819Z',mode:absolute,to:'2018-02-02T16:45:47.819Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-02T16:39:47.819Z',mode:absolute,to:'2018-02-02T16:45:47.819Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
http://api.gbif.org/v1/dataset/90327333-dbf7-4a3e-9a7e-7c2fd259d963 and looking at the title is the way I would do so. But I agree that it might be nice to include the title in the occurrence index.

>@jameshansen91 doesn't seem to be a github user. and there is no email
