### ISSUE TITLE
Recorded date mismatch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#815]
**Recorded date mismatch**

Andy Bentley here.  I am the owner of the University of Kansas Biodiversity Institute (KUBI)  tissue and voucher resources in GBIF and I am noticing an issue with event dates in interpreted records.  For instance this record:  https://www.gbif.org/occurrence/656957786 is showing that the event year is 2006 which is correct but that the event date is 2005-11-30 which is incorrect.  This record in my database has a partial date and is only being expressed as a year and is being published as such through Darwin Core.  Why then is GBIF interpreting this year as a full date and incorrectly so?  Anything we should or could be doing on our end to prevent this?  There appear to be about 508 similar issues with date in my tissue resource that I suspect are related to the same problem.

-----
fbitem-occurrence656957786
User provided contact info: abentley@ku.edu
System: Chrome 63.0.3239 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/656957786
Window size: width 2133 - height 1425
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-02T21:46:01.355Z',mode:absolute,to:'2018-02-02T21:52:01.355Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-02T21:46:01.355Z',mode:absolute,to:'2018-02-02T21:52:01.355Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Replied by email (data is provided with two dates).
