### ISSUE TITLE
Typo in text

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#82]
**Typo in text**

&quot;species against all data collected [for the] a higher tax[a]nomic group&quot; should read &quot;species against all data collected for [a] higher tax[o]nomic group&quot;

CC @dnoesgaard

-----
fbitem-c907e6e41604f91ef7bc257a44f4499069645c83

System: Chrome 56.0.2924 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/tools/species-population/about
Window size: width 1660 - height 910
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-15T09:44:37.445Z',mode:absolute,to:'2017-02-15T09:50:37.445Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-15T09:44:37.445Z',mode:absolute,to:'2017-02-15T09:50:37.445Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by dnoesgaard** [comment]
Thanks for noticing. I've corrected the typos and it will be live at the next content sync.
