### ISSUE TITLE
Project pages (e.g. for BID): add information on primary contact person

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#84]
**Project pages (e.g. for BID): add information on primary contact person**

In the fact sheet underneath the project description, status and image, add some link to the primary corresponding contact person, comparable to a &quot;corresponding author&quot;.

Background: to follow up on feedback relating to the project (see https://github.com/gbif/portal-feedback/issues/72), to direct questions or to establish contact otherwise, it should be possible to more easily identify the corresponding contact of a project. The link to the partner institution is not sufficient for this purpose.

-----
fbitem-a7af25371aa1de6037d2a4476fd4c5db6381ae7e
Reported by: @ahahn-gbif
System: Firefox 51.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/project/bid/africa/2015/benin-bird-data-mobilization
Window size: width 1395 - height 639
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-16T12:38:16.455Z',mode:absolute,to:'2017-02-16T12:44:16.455Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-16T12:38:16.455Z',mode:absolute,to:'2017-02-16T12:44:16.455Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
If this is added to the content model it is trivial to add to the website. Let me know if you decide to do so.

**Comment by dnoesgaard** [comment]
In the content model, we have **Lead Participant (or partner) contact details** which is shown on project pages as **Contact Details**. This field can contain anything (name, address, phone no, email, etc.) but is limited (I guess) to what the project lead provides.

@MBLaursen - maybe you can elaborate?

**Comment by kcopas** [comment]
Any remaining issues are individual content ones—this practice has been adopted for some time now…closing…
