### ISSUE TITLE
Problems with explore occurrences feature on dataset page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#85]
**Problems with explore occurrences feature on dataset page**

At global zoom level, when you press the explore occurrences icon beside the map, the resulting occurrence search doesn&#39;t include all occurrences that were view on the map. I suspect this is a problem with dateline handling. 

Furthermore, it is confusing with two explore (microscope) icons on the dataset page. How about adding hover over &quot;Explore records in viewable area&quot; to icon beside map to differentiate them? Alternatively, how about keeping a single icon beside the map, but upon clicking, presenting the user with two options: 1. to explore all records, 2. to explore records in viewable area

-----
fbitem-datasetb5cdf794-8fa4-4a85-8b26-755d087bf531
Reported by: @kbraak
System: Firefox 51.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/dataset/b5cdf794-8fa4-4a85-8b26-755d087bf531
Window size: width 1382 - height 751
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-16T17:49:32.151Z',mode:absolute,to:'2017-02-16T17:55:32.151Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-16T17:49:32.151Z',mode:absolute,to:'2017-02-16T17:55:32.151Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
moved to api https://github.com/gbif/occurrence/issues/13 and https://github.com/gbif/portal16/issues/283

and https://github.com/gbif/portal16/issues/282
