### ISSUE TITLE
Improve basis of record facets

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#87]
**Improve basis of record facets**

A basis of record value should match the [Darwin Core Type Vocabulary](http://rs.gbif.org/vocabulary/dwc/basis_of_record.xml): 
* PreservedSpecimen
* FossilSpecimen
* LivingSpecimen
* HumanObservation
* MachineObservation
* MaterialSample 
* Occurrence / Unknown

This means the following basis of record shown on GBIF.org are invalid: 

* Observation (47,653,413)
* Literature (504,040)

GBIF shows these basis of records facets because it accommodates historical data using these values. Ideally these wrong historical values will be fixed at source. In the meantime, here are a couple suggestions to make selecting a basis of record facet on GBIF.org less confusing. 

Proposal #1: Hide invalid facets &quot;Observation&quot; and &quot;Literature&quot; because they a) cause confusion with users, b) cause confusion with publishers who expect to use these values in the IPT but aren&#39;t allowed (because the IPT validates all basis of record values are valid). 

Proposal #2: Categorize these invalid facets under a parent facet to make them easier to understand:

&quot;Observation&quot; could be shown instead as &quot;unknown observation&quot; located under the parent facet &quot;Observation&quot; that includes all types of observations: 

* Observation
  * human observation
  * machine observation
  * unknown observation

&quot;Literature&quot; could be shown instead as &quot;coming from literature&quot; located under parent facet &quot;Unknown&quot; that includes all types of unknown occurrences:  : 

* Unknown
  * coming from literature
  * completely unknown

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
Reported by: @kbraak
System: Firefox 51.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/occurrence/search?basis_of_record=HUMAN_OBSERVATION&amp;basis_of_record=OBSERVATION
Window size: width 1407 - height 994
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-17T13:40:07.294Z',mode:absolute,to:'2017-02-17T13:46:07.294Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-17T13:40:07.294Z',mode:absolute,to:'2017-02-17T13:46:07.294Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
@kbraak is the parent term in option #2 not Occurrence instead of Observation which you want to get rid of as its not an official term anymore?

I would also like to point out that this affects how we interpret values. Our BoR parser does generate Literature values still, cause we have it in our API, and would need to be changed.

Personally I would be in favour of entirely rethinking the BoR vocabulary and create a new, hierarchical one not too different from the current official one. During several TDWG meetings GBIF was told to lead such a vocabulary development

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/284
