### ISSUE TITLE
Omnisearch results: show event date

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#90]
**Omnisearch results: show event date**

It would be enormously helpful to see the date of an event to know if it&#39;s relevant or not. Otherwise right now, one needs to click on each event to see its date. Thanks.

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
Reported by: @kbraak
System: Firefox 51.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/search?q=jrs
Window size: width 1407 - height 1039
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-21T14:34:09.346Z',mode:absolute,to:'2017-02-21T14:40:09.346Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-21T14:34:09.346Z',mode:absolute,to:'2017-02-21T14:40:09.346Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi Kyle. thanks. this issue already exists here: https://github.com/gbif/portal16/issues/180
I will close as duplicate. thanks
