### ISSUE TITLE
Occurrence dot showing up on thumbnail map, but not on extended view

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#92]
**Occurrence dot showing up on thumbnail map, but not on extended view**

A search result for Trochulus caelatus (https://demo.gbif.org/species/search?q=Trochulus%20caelatus) shows a yellow dot for the occurrence in the small thumbnail map to the right of the taxon name. Clicking on that map and switching the view to https://demo.gbif.org/species/5780344, this occurrence locality is no longer visible on the map.

-----
fbitem-species5780344
Reported by: @ahahn-gbif.org
System: Firefox 51.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/species/5780344
Window size: width 1264 - height 629
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-24T14:53:35.137Z',mode:absolute,to:'2017-02-24T14:59:35.137Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-24T14:53:35.137Z',mode:absolute,to:'2017-02-24T14:59:35.137Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
We'll need to regenerate the v2 map tiles.

**Comment by MattBlissett** [comment]
Fixed with the automatic regeneration of V2 tiles.
