### ISSUE TITLE
Incorrect structure of taxon name "Trochulus caelatus (S.Studer,1820) S.Studer, 1820

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#93]
**Incorrect structure of taxon name &quot;Trochulus caelatus (S.Studer,1820) S.Studer, 1820**

The correct name should be &quot;Trochulus caelatus (S.Studer, 1820)&quot;, since a) recombinations in zoology do not get the combination author appended, and b) the combination author would be a much more recent person/event in any case. The cited source (Fauna Europaea, http://www.faunaeur.org/full_results.php?id=428061) does not contain that duplication. A name generation artifact?

-----
fbitem-species5780344
Reported by: @ahahn-gbif
System: Firefox 51.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/species/5780344
Window size: width 1264 - height 629
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-24T14:59:12.316Z',mode:absolute,to:'2017-02-24T15:05:12.316Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-24T14:59:12.316Z',mode:absolute,to:'2017-02-24T15:05:12.316Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
the fauna europaea source indexed in gbif doescontain the error. a new version of FaEu would good
