### ISSUE TITLE
How to download data????

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#94]
**How to download data????**

When i try to download data, is there some error...

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
Reported by: setebuenavista@gmail.com
System: Firefox 51.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/download?taxon_key=7952072
Window size: width 1366 - height 659
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-24T19:14:27.245Z',mode:absolute,to:'2017-02-24T19:20:27.245Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-24T19:14:27.245Z',mode:absolute,to:'2017-02-24T19:20:27.245Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hello thanks for trying out the new site.
I'm not sure i get what the issue you are experiencing is. Could you please explain in more details what is happening. Assuming that you have an account and enter your email you should get an email once the download is ready. And once clicking Understood to the terms you should be taken to the page of the download. once the download is ready you can get the file. This is what I see when trying:

<img width="1432" alt="screen shot 2017-02-26 at 12 46 27" src="https://cloud.githubusercontent.com/assets/6759267/23339431/9b463cc6-fc22-11e6-9710-2a309d92d04c.png">

<img width="1428" alt="screen shot 2017-02-26 at 12 47 02" src="https://cloud.githubusercontent.com/assets/6759267/23339432/9f6dc6a2-fc22-11e6-9a44-978a4ae4f683.png">

<img width="1434" alt="screen shot 2017-02-26 at 12 47 21" src="https://cloud.githubusercontent.com/assets/6759267/23339433/a337e1aa-fc22-11e6-8636-813f7c6a9f39.png">

NB: this last screenshot is a different download as i didn't wait for the download to be ready.
<img width="1436" alt="screen shot 2017-02-26 at 12 47 56" src="https://cloud.githubusercontent.com/assets/6759267/23339434/a8cde574-fc22-11e6-9f2b-2f2f464a6101.png">

**Comment by kbraak** [comment]
On the current portal, after triggering a 'download' a notification box appears at the top of the download page with the following text:

> Download running
> The download has been started and is currently being processed.
> Please expect 10 to 15 minutes for the download to complete.
> A notification email with a link to download the results will be sent to the following addresses once ready:
>     email@address

As far as I can see this information is missing from the new portal. It is quite important to the user at it explains how and when they can retrieve the download. 

![screen shot 2017-02-27 at 10 52 36](https://cloud.githubusercontent.com/assets/5981100/23356727/3e50fd6c-fcdb-11e6-96fe-dee1facbcc4f.png)

**Comment by MortenHofft** [comment]
@kbraak yeah, that could be a part of it. That should be there if not on the previous page as well, I just fear that it is something not working at all. But hard to tell without more details

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/298
