### ISSUE TITLE
Paleodb occurrences as seen through GBIF are at about 50% from the live content at source

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#95]
**Paleodb occurrences as seen through GBIF are at about 50% from the live content at source**

https://paleobiodb.org/#/

-----
fbitem-dataset84806e86-f762-11e1-a439-00145eb45e9a
Reported by: @dschigel
System: Firefox 51.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/dataset/84806e86-f762-11e1-a439-00145eb45e9a
Window size: width 1920 - height 1077
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-26T12:44:02.559Z',mode:absolute,to:'2017-02-26T12:50:02.559Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-26T12:44:02.559Z',mode:absolute,to:'2017-02-26T12:50:02.559Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
Apparently, 147044 names coming from the Paleobiology Database are currently used in building the [GBIF Backbone Taxonomy]( http://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c). @mdoering can you please confirm you build a checklist from this occurrence dataset, and that it would be valuable to get an updated version with more occurrences? Thanks

**Comment by mdoering** [comment]
Hi, there is an overlap now as we have 2 Paleobiology dbs registered. One checklist which I use for backbone building and which is by far the major source of fossil taxa: https://demo.gbif.org/dataset/c33ce2f2-c3cc-43a5-a380-fe4526d63650

And one occurrence dataset: https://demo.gbif.org/dataset/84806e86-f762-11e1-a439-00145eb45e9a


Ideally we would only see a single checklist dataset with attached occurrences. Maybe we can approach publishers? The checklist dataset was done by me using this code: https://github.com/mdoering/checklist_builder/blob/master/src/main/java/de/doering/dwca/pbdb/ArchiveBuilder.java

I would be glad if we see a dwca published by the original website regularly instead

**Comment by kbraak** [comment]
Thanks @mdoering 

Do you have an existing contact associated with this checklist that you would recommend we reach out to? There are several contacts on the 'About' page https://paleobiodb.org/navigator/#aboutModal 

Plus these contacts:

[Checklist dataset](https://demo.gbif.org/dataset/c33ce2f2-c3cc-43a5-a380-fe4526d63650):

The Paleobiology Database
Originator, Administrative point of contact, Primary contact
info@paleobiodb.org 

---
[Occurrence dataset](https://demo.gbif.org/dataset/84806e86-f762-11e1-a439-00145eb45e9a):

Peter Schroeter
Technical point of contact
schroeter@nceas.ucsb.edu

John Alroy
Administrative point of contact, Primary contact
alroy@nceas.ucsb.edu

**Comment by mdoering** [comment]
I am afraid not a stable contact. I had been in touch with Wolfgang Kiessling in the beginnings with whom I worked on the ABCD EFG palaeo extension. And then a little with mmcclenn@geology.wisc.edu.

Id suggest to go the official route of whoever is listed as the maintainer right now.

**Comment by mdoering** [comment]
see also #636

**Comment by ManonGros** [comment]
Since the dataset has been republished and is now hosted by VertNet, the difference between the live content and the one we have on GBIF is not that much any more (although the dataset hasn't been updated since 2017).

**Comment by tucotuco** [comment]
Should we initiate a republication with updates. @dbloom. We usually do
this at the request of the data publisher.

**Comment by dbloom** [comment]
True that usual is at the request of the publisher, but it is not our of
the ordinary for us to initiate if we discover that a dataset is
significantly out of date.

I can contact Mark Uhen and ask if they would like to update their set if
you concur @tucotuco

**Comment by tucotuco** [comment]
I concur.
