### ISSUE TITLE
Login for download: prompts hardly visible in my Firefox interface

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#96]
**Login for download: prompts hardly visible in my Firefox interface**

The login screen that opens when requesting a (CSV) download contains three fields that need to be filled for returning users. On my screen, however, the contrast is so low that the text is close to invisible.

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
Reported by: @ahahn-gbif
System: Firefox 51.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/download?taxon_key=7952072
Window size: width 1264 - height 629
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-27T07:57:28.287Z',mode:absolute,to:'2017-02-27T08:03:28.287Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-02-27T07:57:28.287Z',mode:absolute,to:'2017-02-27T08:03:28.287Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
thanks @ahahn-gbif
The prompt is really temporary until the proper login is in place. I hope the new one is more accessible. If not let me know. thanks
